### ISSUE TITLE
firebase_ml_vision seems working with landscape images only

### ISSUE THREAD

**Issue by lewixlabs** [flutter/flutter#19000]
I'm using first release v0.0.1 of firebase_ml_vision and with image picker plugin i can only detect text from images obtained with camera in landscape mode.

Code sample is copied and edited from official page
https://pub.dartlang.org/packages/firebase_ml_vision

```dart
    var image = await ImagePicker.pickImage(source: ImageSource.camera);

    final FirebaseVisionImage visionImage = FirebaseVisionImage.fromFile(image);
    final TextDetector detector = FirebaseVision.instance.getTextDetector();
    final List<TextBlock> blocks = await detector.detectInImage(visionImage);

    detector.close();

    for (TextBlock block in blocks) {
      final Rectangle<num> boundingBox = block.boundingBox;
      final List<Point<num>> cornerPoints = block.cornerPoints;
      final String text = block.text;

      for (TextLine line in block.lines) {
        // ...

        for (TextElement element in line.elements) {
          // ...
        }
      }
    }
```

Maybe i'm missing something in FirebaseVisionImage configuration?
Thanks for any suggestion.

Lewix

**Comment by lewixlabs** [comment]
Hi,
have you any news?
I tried also latest 0.1.0 but with no success.

In my tests, issue happens to Samsung devices only, where image is picked from camera in portrait mode:
My two device are:
- Samsung Galaxy S8 -> issue happens
- Nexus 6 -> issue doesn't happen

As example project you can try your official:
https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision/example

I only changed row #33 in demo.dart
https://github.com/flutter/plugins/blob/master/packages/firebase_ml_vision/example/lib/main.dart
from ImageSource.gallery to ImageSource.camera
`await ImagePicker.pickImage(source: ImageSource.camera);`

Thanks for any suggestions,
Lewix

**Comment by mongy910** [comment]
I tested the example app on an LG G6 - 
The image shows up correctly as portrait mode when loaded, but when converted to a FirebaseVisionImage, it gets rotated by 90 degrees. This rotated version is what the detection uses, with incorrect results.

I think that the problem is that in the actual plugin file under firebase_ml_vision\android\src\main\java\io\flutter\plugins\firebasemlvision\FirebaseMlVisionPlugin.java
the image is generated from FirebaseVisionImage.fromFilePath() which has no way of knowing the correct image rotation. 

Will play around some more and update....

**Comment by 0x3C** [comment]
I can confirm that I am experiencing this issue as well. 

Running a Galaxy S8. Using a photo that was taken in portrait, or taking a photo in portrait in app, will result in no text detected. If the photo was taken in landscape, all text is detected fine.

**Comment by 0x3C** [comment]
@lewixlabs @mongy910, it appears this issue is tied to flutter/flutter#19458.

**Comment by lewixlabs** [comment]
Thank you @0x3C,
so actual workaround maybe is detect portrait orientation (MediaQuery) and rotate image before passing it to textDetector?

**Comment by 0x3C** [comment]
@lewixlabs, you may be right! I'm not seeing any methods that allow you to change the orientation of a photo, but it seems you should be able to. I'm going to take a little bit of a deeper look sometime today and see what I can find

**Comment by mongy910** [comment]
I couldn't find any way to rotate the image in firebase_ml_vision because the textDetector function only takes in the filepath of the image. My workaround was to use this plugin instead: https://pub.dartlang.org/packages/mlkit
which has a textDetector wrapper that takes in a raw byte stream so I could pass in the rotated image.

**Comment by AlexBacich** [comment]
@mongy910, how do you rotate the image? Once you rotate the image you can save on disk and pass path to mlkit. But problem with this solution is that it takes extra ~5 seconds.

**Comment by lewixlabs** [comment]
> The image shows up correctly as portrait mode when loaded, but when converted to a FirebaseVisionImage, it gets rotated by 90 degrees

@mongy910 I confirm! I wrote an example project based on Camera Plugin (not Camera Picker)
https://pub.dartlang.org/packages/camera#-example-tab-
and i get **the same issue**
This is the link of my example project:
https://github.com/lewixlabs/flutter_mlkit_ocr_realtime

I hope flutter team will release a fix soon :-O

**Comment by 0x3C** [comment]
@lewixlabs @mongy910 
So does this appear to be an issue with the way that `FirebaseVisionImage` is coded in the `firebase_ml_vision` plugin, or is it an issue with the way Flutter itself is handling images on Android? It seems to be tied to the way plugins are handling the `filepath` input, as the raw byte stream works in `mlkit`. 

Is there any way to get more eyes on this to try and come up with a work around, or a resolution to the root cause of the bug?

**Comment by 0x3C** [comment]
@lewixlabs 
I did one more round of testing. I am still not sure where the photo is getting rotated, or how to resolve the issue, but here are some more observations. 

* The photo does not necessarily need to be taken in landscape mode. It is sufficient to have the text itself rotated within the photo. Meaning, you are able to lock your phone in portrait, and rotate orientation of whatever you are taking a photo of, rather than the phone. 
* The photo rotates 90 degrees counter clockwise. Photos taken in one landscape orientation returns backwards text results, while the other returns the results proper.

**Comment by lewixlabs** [comment]
Hi,
has somebody tried v0.2.0 released yesterday?
https://pub.dartlang.org/packages/firebase_ml_vision

**Comment by rlee1990** [comment]
@lewixlabs still not working not in landscape or portrait or in ios at all

**Comment by lewixlabs** [comment]
can somebody from google flutter developers update us about this (probably confirmed) bug?

**Comment by lance-blo** [comment]
For iOS devs, I have been using the below code to solve the issue using that [library](https://github.com/btastic/flutter_native_image).

`if (Platform.isIOS) {
      file = await FlutterNativeImage.compressImage(file.path, quality: 90);
    }`

My guess of why this is working is that somehow the newly created image respects the EXIF data of the picture.

I know this is not the best solution as it creates an overhead (reasonable though) but it is the only way I was able to get the textDetector to work a portrait image on my testing device (iPhone SE).

**Comment by AlexBacich** [comment]
@lance-blo , this didn't work for me as you described (tried for Android), BUT(!!) 
This library compresses image perfectly which I can then rotate programmatically using ImageDecoder. And whole process with compressing + rotating now taking less than a second. 

Again, not a perfect, but working solution.

**Comment by lance-blo** [comment]
@AlexBacich that's good to know. At least, we are going forward.
Any ideas as to generalise this rotation problem?
This initial bug report was produced by the ImagePicker plugin. However, I am also having the issue  but with the camera plugin.
The following issues should be linked: #18391, #16587

**Comment by AlexBacich** [comment]
I think the right place to fix the issue is in initial plugins taking photos. Both ImagePicker, Camera should consider rotation issue and suggest option saving photo with this consideration.

**Comment by thomas-stockx** [comment]
@AlexBacich How to know by how many degrees to rotate the image when doing it your way (flutter_native_image for compression, image for ration)? We're running into the same issue, which is a blocker for our app release. It works fine on a Nexus 5X, while the Pixel 2 only works on landscape.

This issue is definitely device specific, on native Android projects we're used to using [ExifInterface](https://developer.android.com/reference/android/media/ExifInterface) for similar issues.

**Comment by lance-blo** [comment]
@thomas-stockx As you said, this is device specific, I have observed rotation 90 degrees left or 90 degrees right. See #16587

**Comment by AlexBacich** [comment]
@thomas-stockx , you are right. Rotation could differ. You can keep rotating till you get something scanned, but this is ridiculous. Guess the only right move is to correct photo plugin. Take into consideration exif and save photo with rotation correction immediately.

**Comment by AlexBacich** [comment]
@thomas-stockx , you are right. Rotation could differ. You can keep rotating till you get something scanned, but this is ridiculous. Guess the only right move is to correct photo plugin. Take into consideration exif and save photo with rotation correction immediately.

**Comment by thomas-stockx** [comment]
@lance-blo @AlexBacich We have a working solution now by using [ExifDart](https://pub.dartlang.org/packages/exifdart) in combination with your 2 suggested libraries:

```
import 'package:image/image.dart' as rotatingImage;

// other code

_newImage = await FlutterNativeImage.compressImage(_newImage.path, quality: 90);
Map<String, dynamic> tags = await readExifFromFile(_newImage);

if (tags.containsKey("Orientation")) {
  rotatingImage.Image imageToRotate = rotatingImage.decodeImage(_newImage.readAsBytesSync());
  switch (tags["Orientation"]) {
    case 8:
      imageToRotate = rotatingImage.copyRotate(imageToRotate, -90);
      break;
    case 6:
      imageToRotate = rotatingImage.copyRotate(imageToRotate, 90);
      break;
  }
  setState(() {
    _newImage..writeAsBytesSync(rotatingImage.encodePng(imageToRotate));
  });
}
final FirebaseVisionImage visionImage = FirebaseVisionImage.fromFile(_newImage);

// Now faces get detected on every device tested here (Samsung S8, Pixel 2, Nexus 5X)
```

**Comment by lance-blo** [comment]
I would love to do it that way unfortunately I ran into a problem with the function _decodeImage_. It takes around a minute to execute on my device (know bug described here: https://github.com/brendan-duncan/image/issues/72)

However, resolution may be on the way: https://github.com/OpenFlutter/flutter_image_compress/issues/3
Maybe we can vote there as well: https://github.com/OpenFlutter/flutter_image_compress/issues/6 if that motivates the author of the flutter_image_compress package.

**Comment by azihsoyn** [comment]
Hi, I released flutter_mlkit 0.8.1 to fix android rotation problem.

If issue resolved, I'll PR to official plugin too.

Thanks.

**Comment by rlee1990** [comment]
> @lance-blo @AlexBacich We have a working solution now by using [ExifDart](https://pub.dartlang.org/packages/exifdart) in combination with your 2 suggested libraries:
> 
> ```
> import 'package:image/image.dart' as rotatingImage;
> 
> // other code
> 
> _newImage = await FlutterNativeImage.compressImage(_newImage.path, quality: 90);
> Map<String, dynamic> tags = await readExifFromFile(_newImage);
> 
> if (tags.containsKey("Orientation")) {
>   rotatingImage.Image imageToRotate = rotatingImage.decodeImage(_newImage.readAsBytesSync());
>   switch (tags["Orientation"]) {
>     case 8:
>       imageToRotate = rotatingImage.copyRotate(imageToRotate, -90);
>       break;
>     case 6:
>       imageToRotate = rotatingImage.copyRotate(imageToRotate, 90);
>       break;
>   }
>   setState(() {
>     _newImage..writeAsBytesSync(rotatingImage.encodePng(imageToRotate));
>   });
> }
> final FirebaseVisionImage visionImage = FirebaseVisionImage.fromFile(_newImage);
> 
> // Now faces get detected on every device tested here (Samsung S8, Pixel 2, Nexus 5X)
> ```

@thomas-stockx are you using an Exif package?

**Comment by rlee1990** [comment]
@thomas-stockx how are you using ExifDart to get `readExifFromFile(_newImage)` from what I have read it takes an `AbstractBlobReader`

**Comment by thomas-stockx** [comment]
@rlee1990 you can use `import 'package:exifdart/exifdart_io.dart';`.

It will expose the following method:
```
Future<Map<String, dynamic>> readExifFromFile(File file,
    {bool printDebugInfo = false}) {
  return readExif(new FileReader(file));
}
```

**Comment by AlexBacich** [comment]
@thomas-stockx , awesome solution! 

Tested on Sony Compact - working well. 

Just one more improvement to suggest. Reading EXIF file took 2 seconds for me. This is pretty heavy so I let my phone study phone rotation factor on first photo and save it in persistence. So on further photos I immediately rotate photo after scan. 

I guess the only thing can be done further to win more seconds - lowering photo quality to take less time on saving and rotating.

**Comment by AlexBacich** [comment]
Tested iOS and Android, posting whole code for compensating rotation: 

photoRotationFactor - value taken from exifdart_io.dart
_onFilePathAcquired - my method parsing photos with normal rotation

```
  void _compensateRotation(String filePath, int photoRotationFactor) {
    FlutterNativeImage.getImageProperties(filePath).then((properties) {
      FlutterNativeImage.compressImage(
        filePath,
        quality: 80,
        targetWidth: 600,
        targetHeight: (properties.height * 600 / properties.width).round(),
      ).then((newFile) {
    
        // Handle compressed image
        if (Platform.isIOS) {
          // iOS isn't requiring extra rotation so compressing image step is enough
          // Re-run photo scanning
          _onFilePathAcquired(newFile.path, isOriginalPhoto: false);

        } else {
          // Android requires extra file rotation.
          List<int> bytes = newFile.readAsBytesSync();
          imageDecoder.Image originalImage = imageDecoder.decodeImage(bytes);
          imageDecoder.Image rotatedImage;
          switch (photoRotationFactor) {
            case 8:
              rotatedImage = imageDecoder.copyRotate(originalImage, -90);
              break;
            case 6:
              rotatedImage = imageDecoder.copyRotate(originalImage, 90);
              break;
            default:
              print(
                  "Error, shouldn't be here as rotation factor is $photoRotationFactor");
              return;
          }

          List<int> encodedImage =
              imageDecoder.encodeNamedImage(rotatedImage, filePath);
          Io.File(filePath).writeAsBytesSync(encodedImage);

          // Re-run photo scanning
          _onFilePathAcquired(filePath, isOriginalPhoto: false);
        }
      }).catchError((error) {
        print('FlutterNativeImage error: $error');
        _onFilePathAcquired(null, isOriginalPhoto: false);
      });
    }).catchError((error) {
      print('FlutterNativeImage error: $error');
      _onFilePathAcquired(null, isOriginalPhoto: false);
    });
  }
```

**Comment by rlee1990** [comment]
Works for me too thanks @thomas-stockx

**Comment by thomas-stockx** [comment]
Definitely recommending @azihsoyn's mlkit plugin.

Handling the rotation stuff on the native side is the way to go, and way more performant than our workarounds in Flutter code.

Because of this we've switched from firebase_ml_vision to mlkit.

**Comment by rlee1990** [comment]
@thomas-stockx have you gotten the latest version to work on ios that was the issue i was facing for @azihsoyn's mlkit

**Comment by thomas-stockx** [comment]
@rlee1990 I have it running, although we've previously commented out `#use_frameworks!` in the iOS Podfile due to similar issues.

**Comment by rlee1990** [comment]
@thomas-stockx I think that's my issue but I can't comment that out due to other packages. I'll just have to wait for a fix from @azihsoyn

**Comment by lewixlabs** [comment]
> Hi, I released flutter_mlkit 0.8.1 to fix android rotation problem.
> 
> If issue resolved, I'll PR to official plugin too.
> 
> Thanks.

I confirm, @azihsoyn mlkit plugin works in portrait mode! ✌️
![image](https://user-images.githubusercontent.com/7371215/48272097-1b2f7380-e43e-11e8-89c6-f48a9e689fc3.png)
![image](https://user-images.githubusercontent.com/7371215/48272116-24204500-e43e-11e8-8b88-7bad99d856bd.png)

@zoechi please can update us about news? with help of @azihsoyn will flutter team eventually release an update this month? thanks!
Lewix

**Comment by lewixlabs** [comment]
Guys,
with last releases of firebas_ml_vision & camera package, there is a new method to retrieve camera image stream bytes and all works! (actually tested on Android only).
My other post:
https://github.com/flutter/flutter/issues/26348#issuecomment-453668261

My full demo project
https://github.com/flutter/flutter/issues/26348

I have to test iOS side, but seems promising! :)

**Comment by 0x3C** [comment]
@lewixlabs - with the detection working using streams, does that mean we are closer to being able to do real time text detection?

**Comment by sergiuiacob1** [comment]
> Guys,
> with last releases of firebase_ml_vision & camera package, there is a new method to retrieve camera image stream bytes and all works! (actually tested on Android only).
> My other post:
> [#26348 (comment)](https://github.com/flutter/flutter/issues/26348#issuecomment-453668261)
> 
> My full demo project
> https://github.com/lewixlabs/mlkit_ocr_realtime
> 
> I have to test iOS side, but seems promising! :)

Hey! I have just tried your example on an OnePlus 3T. The code doesn't recognize any text. What might be the issue? I managed to recognize text from still images, taken with the `image_picker` package. But the real time scanning isn't working at all.

**Comment by kroikie** [comment]
@lewixlabs

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/771. Any further collaboration will be done there.

**Comment by RaashVision** [comment]
Try increase the resolution of image from medium to high. The live detection will works
