### ISSUE TITLE
RefreshIndicator and the Cupertino equivalent don't work with expanding SliverAppBar

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19024]
The Material widget ends up rendering on top of the app bar and the Cupertino equivalent ends up _before_ the app bar.

**Comment by Hixie** [comment]
Hm weird. I wonder what I did wrong.

**Comment by xster** [comment]
From the description, my only guess is that the sliver orders were inserted in reverse though that seems unlikely.

**Comment by xster** [comment]
https://github.com/flutter/flutter/pull/19282 just in case

**Comment by Hixie** [comment]
I just tested this and couldn't reproduce. My bad. Maybe I put it in the wrong place.
