### ISSUE TITLE
How to get mobile device information, such as wifi MAC, mobile phone model, TIME, PRODUCT？

### ISSUE THREAD

**Issue by pyp163** [flutter/flutter#19029]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/device_info should provide most information.
If specific bits are missing, please create specific issues for them. Thanks!

**Comment by ricardo-lemes** [comment]
I need to get the "macaddress" of the device.
Do you have any way to do this?

**Comment by zoechi** [comment]
@ricardo-lemes I'm not aware of a way to do that

**Comment by zoechi** [comment]
There are packages on pub.dartlang.org that provide some of what is asked here.

https://pub.dartlang.org/packages/device_info
https://pub.dartlang.org/packages/wifi
https://pub.dartlang.org/packages/connectivity

**Comment by hosseinsohan** [comment]
Use this plugin https://pub.dev/packages/wifi#-readme-tab-

(This plugin works Android. iOS later released)
