### ISSUE TITLE
How can i get size of widget?

### ISSUE THREAD

**Issue by KuiRin** [flutter/flutter#19035]
Now, I have a problem.

I can not get size (Width or Height) of widget.

Please support me.

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/after_layout might help.
You should try to avoid getting the height, this might indicate an anti-pattern.
For custom layouts also see 
- https://docs.flutter.io/flutter/rendering/RenderObject-class.html
- https://docs.flutter.io/flutter/widgets/CustomMultiChildLayout-class.html

**Comment by KuiRin** [comment]
@zoechi  thankyou for support me.

But does that mean I can also get child widget using your solution?

**Comment by zoechi** [comment]
See also https://stackoverflow.com/questions/47283319/how-to-calculate-size-of-children
