### ISSUE TITLE
`Navigator.of().pop()` broken in certain criteria, causing ~25% black area at the top of the screen

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#19034]
## Steps to Reproduce

I need to check for the validity of the user session in the Account page. When something goes wrong I will redirect the user back to the sign in page to login again. This is done by calling `Navigator.of(context).pop();` (to go back to the home page) followed by `runApp(new MyApp(homepage: new SignInPage()));`. 

But I encounter a strange issue that sometimes `Navigator.of(context).pop();` doesn't work properly. I think this problem is best illustrated with animated GIFs:

### Abnormal

(The `runApp` call has been delayed to show that `Navigator.of(context).pop();` is the problem)

![ezgif-1-3976d90221](https://user-images.githubusercontent.com/959433/42213344-147bf0bc-7eeb-11e8-8313-c29a718001bb.gif)

The abnormal behavior is triggered by the following simplified code:
```
  _loadData() async {
    // In reality, the following line requests an updated user profile from the remote server.
    var refreshUserFuture = Future.value(null);
    // In reality, the following line requests some additional detail from the remote server.
    var loadUserDetailFuture = Future.value(null);

    Future.wait([refreshUserFuture, loadUserDetailFuture]).then((response) {
      response.forEach((v) {
        // In reality, we need to check the response, and goes to the sign in page if user
        // has logged out.
        _navigateToSignInPage();
        return;
      });
    });
  }

  _navigateToSignInPage() {
    // Need to pop back to the homepage first
    Navigator.of(context).pop();
    // Replaces the homepage with the sign in page
    runApp(new FlutterApp(
      homepage: new SignInPage(
        popStateAfterSignIn: false,
      ),
    ));
  }

```

I tried and found that the problem goes away when 
 * only 1 future is being waited, or 
 * the `_navigateToSignInPage()` line is not executed inside `response.forEach`.

![ezgif-1-7dbda41142](https://user-images.githubusercontent.com/959433/42213351-17754a52-7eeb-11e8-8d87-e990dd541ac5.gif)

```
[√] Flutter (Channel dev, v0.5.5, on Microsoft Windows [Version 10.0.17134.112], locale zh-HK)
    • Flutter version 0.5.5 at C:\flutter
    • Framework revision 020e0ef55c (3 weeks ago), 2018-06-14 13:17:08 -0700
    • Engine revision c3976b3c71
    • Dart version 2.0.0-dev.61.0.flutter-c95617b19c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\CY\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio 3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio 3
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Android Studio (version 2.1)
    • Android Studio at C:\Android\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Nexus 5X • 00e1c63e154fae10 • android-arm64 • Android 8.1.0 (API 27)
```

Also reproduced in this newer Flutter version:
```
[√] Flutter (Channel master, v0.5.6-pre.124, on Microsoft Windows [Version 10.0.17134.112], locale zh-HK)
    • Flutter version 0.5.6-pre.124 at C:\flutter
    • Framework revision 0329f0c179 (5 hours ago), 2018-07-03 07:37:34 +0100
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2
```

**Comment by nesscx** [comment]
I'm not sure but I think if for each pushed screen you have made, you can only make Navigator Pop for the same numbers of screens pushed before. So, if you push screen once and pop two or more times (like the abnormal gif) then you will get the black area.

Instead of using `return`, I'd use `break` statement to stop the `forEach` making sure `Navigator.of(context).pop()` will be executed only a single time.

**Comment by tamcy** [comment]
Yes, you are correct, the issue is caused by `Navigator.of(context).pop();` being called twice!

Also thank you for your advice on using `break`. Actually in my real code there's a check of the response type. What I overlooked is that the condition checking statement of both responses will evaluate to true in the particular case where I need to pop the page and show the login screen.

I'm closing this issue.
