### ISSUE TITLE
flutter textfield cursor is small and thin

### ISSUE THREAD

**Issue by bakatest-me** [flutter/flutter#19041]
flutter textfield cursor is small and thin
can i custom or increase size
thank you
flutter cursor
![screen shot 2561-07-03 at 20 26 22](https://user-images.githubusercontent.com/22494087/42222494-94334bb6-7eff-11e8-8bf6-813741a72014.png)

other other app cursor
![screen shot 2561-07-03 at 20 26 07](https://user-images.githubusercontent.com/22494087/42222504-9b9666c2-7eff-11e8-815e-da4af915cb7d.png)

**Comment by zoechi** [comment]
I think this is covered by #15571.
Just add a comment if you disagree and I'll reopen.

**Comment by bakatest-me** [comment]
@zoechi  sorry thank you.

**Comment by zoechi** [comment]
@bakatest-me no worries 👍
