### ISSUE TITLE
Add a --machine option for `flutter attach`

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#19045]
@devoncarew @mit-mit Looks like `attach` doesn't currently support `--machine` (it also gives a weird error: `The --machine flag is only valid with the --version flag`).

It's currently implemented as its own command and creates a `HotRunner`. Our JSON support is all inside Daemon. Does it makes sense for AttachCommand to work more like RunCommand and spawn a daemon internally (so it gets all the AppDomain stuff)? (I'm not sure if we're going to end up piling lots of stuff in Daemon; but this does want to reuse a lot of the run functionality).

**Comment by devoncarew** [comment]
I think we do want:

- flutter attach to support `--machine`
- and, to export a json interface, the same as flutter run

We may need some slightly different events from it on startup, to help indicate that the app isn't starting up so much as waiting to attach.

> Does it makes sense for AttachCommand to work more like RunCommand and spawn a daemon internally (so it gets all the AppDomain stuff)?

I'm not 100% of the what the impl should look like, but we do want to share as much code as possible here (between flutter run --machine and flutter attach --machine), as well as do whatever we can to make sure that we don't have too many code paths through (to minimize the possibility of flutter attach --machine regressing independently of the regular flutter attach).

**Comment by DanTup** [comment]
Got a basic implementation at https://github.com/flutter/flutter/pull/19077, feedback appreciated!
