### ISSUE TITLE
Exec format error: line 161 /flutter/bin/flutter

### ISSUE THREAD

**Issue by ricardobrg** [flutter/flutter#19040]
I have followed the installation steps in https://flutter.io/setup-linux/

~$ wget https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.5.1-beta.tar.xz
~$ tar xf ~/flutter_linux_v0.5.1-beta.tar.xz
~$ export PATH=`pwd`/flutter/bin:$PATH
~$ flutter doctor
/home/user/flutter/bin/flutter: line 161: /home/user/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
~$ flutter doctor -v
/home/user/flutter/bin/flutter: line 161: /home/user/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error

The OS is Ubuntu 16.04

**Comment by ricardobrg** [comment]
When I try to fork from github I get a similar error:

Building flutter tool...
/dev1/flutter/bin/cache/dart-sdk/bin/pub: line 49: /dev1/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
/dev1/flutter/bin/cache/dart-sdk/bin/pub: line 49: /dev1/flutter/bin/cache/dart-sdk/bin/dart: Success
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
/dev1/flutter/bin/cache/dart-sdk/bin/pub: line 49: /dev1/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
/dev1/flutter/bin/cache/dart-sdk/bin/pub: line 49: /dev1/flutter/bin/cache/dart-sdk/bin/dart: Success
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...

**Comment by DanTup** [comment]
What's the output if you run these two commands?

```
file /home/user/flutter/bin/cache/dart-sdk/bin/dart
```

```
uname -m
```

**Comment by ricardobrg** [comment]
@DanTup 
~$ uname -m
i686
~$ file /home/user/flutter/bin/cache/dart-sdk/bin/dart
/home/user/flutter/bin/cache/dart-sdk/bin/dart: cannot open `/home/user/flutter/bin/cache/dart-sdk/bin/dart' (No such file or directory)

**Comment by DanTup** [comment]
Based on https://github.com/flutter/flutter/issues/865 it seems like 32bit Linux is not supported. `flutter doctor` is supposed to detect it, but if it's downloaded a 64bit Dart VM then it won't get as far as showing you that warning. I've added a comment to that issue to see if anyone in the discussion last time has any ideas (I think if it's not supported then the shell script should output a message before it tries to run the VM).

**Comment by iampawan** [comment]
Getting same issue with aarch64 device (Galaxy Note 9) where I am using linux on dex and got this issue @Hixie @DanTup. It will be huge if you can support this

**Comment by lukasz81** [comment]
> What's the output if you run these two commands?
> 
> ```
> file /home/user/flutter/bin/cache/dart-sdk/bin/dart
> ```
> 
> ```
> uname -m
> ```

I am having the same issue, but my output from the commands are:
1) ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[xxHash]=dd053e8373dd29db, stripped
2) x86_64
Any idea what goes wrong?

**Comment by pantaopt** [comment]
> Getting same issue with aarch64 device (Galaxy Note 9) where I am using linux on dex and got this issue @Hixie @DanTup. It will be huge if you can support this

Did u solved it?I have the same problem in termux on galaxy s9+
