### ISSUE TITLE
Speech Recognition on iOS

### ISSUE THREAD

**Issue by sahil311289** [flutter/flutter#19057]
I'm trying to get Speech Recognition to work on iOS iPhone 8+ device and X emulator. 
It works just fine on Android 5.0. Later versions need permission and I can handle that. 

Can someone help me with that?

**Comment by zoechi** [comment]
> and I can handle that.

Did you mean "can't"?

I'm not sure what problem you're facing exactly.
Can you please elaborate more.

Also please add the output of `flutter doctor -v`

**Comment by sahil311289** [comment]
Sorry for not being clear. I need help implementing it on iOS.
```
/Users/sahil/flutterDevelopment/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.23.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
I found https://github.com/rxlabz/speech_recognition which might help.

**Comment by sahil311289** [comment]
I am using that.
That one works for Android 5.0 just like that.
Doesn't work for newer Android and iOS versions.

**Comment by namnh06** [comment]
You guys right, it doesn't work on IOS, got this problem: https://github.com/rxlabz/speech_recognition/issues/56

With Android, it seems fine.

**Comment by TianSc** [comment]
Getting the exact same issues over here
```
[!] Unable to determine Swift version for the following pods:

- `speech_recognition` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by raphaelbravoei** [comment]
It Does work on IOS without problems

**Comment by namnh06** [comment]
Hi @raphaelbravoei , I don't think it works. I have this error when try to pod install:
`Installing speech_recognition (0.3.0)
[!] Unable to determine Swift version for the following pods:

- `speech_recognition` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.`
Do you have any idea?

**Comment by sahil311289** [comment]
> It Does work on IOS without problems

How are you using it? Swift or Objective C?

**Comment by fellow7000** [comment]
Is there any news on the topic?.. faced to the same problem with speech recognition on IOS

**Comment by stuartmorgan** [comment]
Closing as out of scope, since the discussion here is about third-party packages.
