### ISSUE TITLE
Failure when Xcode is installed but the user has not signed the Xcode EULA

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1905]
So I installed XCode, and tried flutter start again. Now I get:
```
idevice_id not found. To work with iOS devices, please install ideviceinstaller.
If you use homebrew, you can install it with "$ brew install ideviceinstaller".
Error executing simctl: 69


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



Downloading darwin-x64 artifacts from the cloud, one moment please...
Downloading https://storage.googleapis.com/mojo_infra/flutter/9e1e1fba5474b458458b65f1aa1d0d730af2705b/darwin-x64/artifacts.zip.
Unable to run application - no connected devices.
```

- [ ] We don't seem to detect that XCode failed, instead, we blindly continue on into guaranteed doom.
- [x] We don't provide the user with any help in handling this license issue.

**Comment by chinmaygarde** [comment]
There is no way to sign the EULA from the command line without sudo. We can handle this case better via the messaging in the tooling. For now, the Getting Started guide has been updated https://github.com/flutter/website/pull/168

**Comment by Hixie** [comment]
Can we catch this failure case? If we can, then we have several options:
 - tell the user what the problem is and what command to run to fix it
 - tell the user what the problem is and run the command to fix it

**Comment by Hixie** [comment]
Also, can we detect this ahead of time so we can include it in the readiness checks?

**Comment by devoncarew** [comment]
Looking at the brew source, we can detect that the eula hasn't been signed if the output of this command: `/usr/bin/xcrun clang` has the work 'license' in either stdout or stderr (https://github.com/Homebrew/homebrew/blob/master/Library/brew.sh#L97). We can then prompt them to agree by opened xcode or by running that cli command (`sudo xcodebuild -license`).

**Comment by devoncarew** [comment]
We have a check in `doctor` now for the eula: https://github.com/flutter/flutter/pull/2078. We still need to add a eula check in `run`.

**Comment by danrubel** [comment]
We now show:
```
$ flutter run

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```
and 
```
$ sudo /Users/danrubel/bin/flutter run

You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
```
Following the `-license` instructions above displays the license agreement and prompts you to sign it as expected. I believe this issues has been addressed.

**Comment by Hixie** [comment]
Should we show that second message instead of the first?

**Comment by danrubel** [comment]
Both of those messages are not our own and they are both reasonably clear as to what the user should do. We could add code to figure it out and display our own message to save the user a step but I don't think the savings is worth the added complexity in flutter_tools.
