### ISSUE TITLE
FirebaseAuth delete function

### ISSUE THREAD

**Issue by RobertBrunhage** [flutter/flutter#19066]
The problem I have is that in order to follow the GDPR guidelines I need to be able to delete the user's account and data on demand of the user. So I can delete everything except the user in firebaseAuth.

In Android, I could do something similar to firebaseUser.delete(), but with flutter, there is no delete function. How would I do this or is this a feature that needs to be implemented?

In the following image is where I would like to find a delete function:

![image](https://user-images.githubusercontent.com/26344867/42265004-9974bd9e-7f72-11e8-878a-253049afb3bf.png)

This is from the firebase docs:

![image](https://user-images.githubusercontent.com/26344867/42265223-36b85912-7f73-11e8-88da-7559e3f81597.png)

Link to firebase docs (scroll to "delete a user"): https://firebase.google.com/docs/auth/android/manage-users#re-authenticate_a_user

**Comment by zoechi** [comment]
This should be covered by #15907
Please upvote this issue and add related information there.

**Comment by kroikie** [comment]
@RobertBrunhage

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/767. Any further collaboration will be done there.
