### ISSUE TITLE
Flutter does not detect VS code extension

### ISSUE THREAD

**Issue by jerrythomas** [flutter/flutter#19064]
## Steps to Reproduce
When running flutter doctor, the warning message is shown stating that the VS Code extension is not installed even when the plugin is installed and visible from VS Code.

```
code --install-extension Dart-Code.flutter
```
Found 'Dart-Code.flutter' in the marketplace.
Installing...
Extension 'Dart-Code.flutter' v2.15.0 was successfully installed!

```
flutter doctor -v
```

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

```
ls ~/.vscode/extensions
```
dart-code.dart-code-2.15.0 dart-code.flutter-2.15.0

Visual studio code also shows that both the dart and the flutter plugin are installed. 

## Logs

```
flutter doctor -v
```

[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-IN)
    • Flutter version 0.5.1 at /Users/Jerry/Applications/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by DanTup** [comment]
Thanks for the report! This issue has been fixed in the `master` channel but hasn't reached the `beta` channel yet. It's safe to ignore for now, the extension check is informational only so shouldn't affect your use of VS Code or Flutter.
