### ISSUE TITLE
missing xcode dependency: Python module 'six" even after six is available

### ISSUE THREAD

**Issue by shivaprakashpokala** [flutter/flutter#19061]
## Steps to Reproduce

1. Installed Flutter as mentioned in flutter.io/getstarted
2. but facing below error
Missing Xcode dependency: Python module "six"
I have installed six already though..
**Flutter Doctor -v**
Shivas-MacBook-Pro:Flutter shivapokala$ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.1 at /Users/shivapokala/Desktop/Projects/Flutter/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/shivapokala/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone 6s Plus • 9C15922E-173A-4B69-A349-69B0818D0977 • ios • iOS 11.4 (simulator)

! Doctor found issues in 1 category.
Shivas-MacBook-Pro:Flutter shivapokala$ pip install six
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (1.11.0)

**Comment by zoechi** [comment]
Perhaps #16428 has some suggestions that might work for you.

**Comment by shivaprakashpokala** [comment]
i have done that as well, not helping

**Comment by shivaprakashpokala** [comment]
Thanks all. 
brew uninstall python@2  (--force)
brew install python@2
pip install six
and then flutter doctor did not list any issues. 
Issue Resolved. Thanks again.

**Comment by DanTup** [comment]
@E1360 You'll have to be more specific for us to help. What's the error? What did you try?

**Comment by E1360** [comment]
Hi Danny,
Everything is checked except for "Missing Xcode dependency: Python module "six". Install via 'pip install six' or 'sudo easy_install six'." I have both the built-in macOS dependent Python2.7 as well as Python3.7, I ran both pip and pip3 commands to install six. 

$ **which python2.7**
/opt/local/bin/python2.7
$ **which pip**
/Library/Frameworks/Python.framework/Versions/2.7/bin/pip
$ **pip install six**
_Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name main_

$ **which python3.7**
/usr/local/bin/python3.7
$ **which pip3**
/usr/local/bin/pip3
$ **pip3 install six**
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (1.11.0)


$ **sudo easy_install six**
_Searching for six
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file
Using /Users/Cyrus/Library/Python/2.7/lib/python/site-packages
Processing dependencies for six
Finished processing dependencies for six_

Still the same error in Flutter Doctor: 
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-GB)
    • Flutter version 0.5.1 at /Users/Cyrus/development/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/Cyrus/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

**Comment by E1360** [comment]
I ran $brew doctor and had some warning ! Then I ran $sudo mv /opt/local ~/macports  :) 

now the problem solved:
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-GB)
    • Flutter version 0.5.1 at /Users/Cyrus/development/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/Cyrus/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

**Comment by cbracken** [comment]
Fixed in #19281 on master. It should no longer be necessary to manually install the six module if you have a custom Python install on your path.
