### ISSUE TITLE
Add 'read from cache first' to Cloud Firestore

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#19078]
I am currently using Cloud Firestore in an Index Cards app, the main issue with the implementation however is the Cloud Firestore performance under bad network conditions. 
In the case of no network connection Cloud Firestore seems to read data immediately from cache and the user experience remanins uninterrupted. 

In the case of a bad network connection though (read anything slower than 3G), the Cloud Firestore plugin seems to query 'fresh' data from the server first and not return any data until the query is finished, even though this might take more than 5000 ms for one collection that contains less than 10 documents.

This is why I would suggest adding a 'read from cache first' ability to the Cloud Firestore plugin, that allows for the display of cached data first while the server query is running in the background. This would allow for a much better user experience regardless of the network he is in.

**Comment by mikemclin** [comment]
I'm currently using Redux as a caching layer around Firestore (among other things).  If a "cache-first" flag was added, I would probably drop Redux and all of the ceremony that comes with it and just interact with the Firestore library directly.

**Comment by ozexpert** [comment]
@mikemclin was thinking to use Redux for my project too. sad.

**Comment by blaneyneil** [comment]
yep, this should mimic Apollo's graphql client where you can set fetchPolicy of cache-first, cache-and-network, network-only, cache-only.  right now firestore is just network-only or cache-only.

**Comment by kevin-haynie** [comment]
this is really important for my app also since I love FireStore but I must minimize my Firebase costs.  There are some collections which change very infrequently and it would be best to just load those collections from the user's local cache.  Shouldn't we be able to do something like:

Firestore.instance.collection('myCollection').where(myID).get( { source: 'cache' })

also, it would even be better if we could just query an entire collection from cache with something like:

Firestore.instance.collection('myCollection', { source: 'cache'})

Making this a priority would definitely improve the adoption rate of Firestore in Flutter apps and would help us minimize our overheads with cloud storage.

Thanks!

**Comment by salam0smy** [comment]
I love working with firestore. The fact that it doesn't support cache first is making me consider moving away from it. 

Please give this feature priority. I really think adding this feature will accelerate the adaption of firebase.

Thanks

**Comment by shasaf1986** [comment]
I also need this feature ASAP.
I need Server data only ,currently I do not have any way to get only server data ....
Thanks

**Comment by cbenhagen** [comment]
Setting the source like in https://github.com/flutter/plugins/pull/1538 would allow you to add this 'manually' but obviously an option to generally get data from the cache first would be better.

**Comment by Stone2517** [comment]
Check this If you want to do it Manually on ios and android
https://github.com/flutter/plugins/pull/1538#issuecomment-496367142

**Comment by Stone2517** [comment]
@shasaf1986 Thank you.

**Comment by creativecreatorormaybenot** [comment]
This should be closed. You can now use `Source.cache` as an argument in `DocumentReference.get` & `CollectionReference.getDocuments`.

**Comment by blaneyneil** [comment]
> This should be closed. You can now use `Source.cache` as an argument in `DocumentReference.get` & `CollectionReference.getDocuments`.

is there a Source.cacheAndServer?  if not, this should still be open.  what most are looking for is a way to show results while the most recent data is being queried.

**Comment by creativecreatorormaybenot** [comment]
@blaneyneil [Yes, of course](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Source-class.html#serverAndCache). This is the [default behavior](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/getDocuments.html) anyway.

I am not sure if this has always been the case, however, I assume that it has because it has been [in the description for over a year now](https://github.com/flutter/plugins/blob/e62d473eb2bcb7e72062492e7adffe55a63b5a8e/packages/cloud_firestore/pubspec.yaml#L3).

The description might have been false until two weeks ago, however, if you have been using any version [`>=0.12.1`](https://github.com/shasaf1986/plugins/blob/90c53d7ad486fdb8e41814e41a5e590550c147aa/packages/cloud_firestore/CHANGELOG.md), chances are you were using "what most are looking for" already.

**Comment by blaneyneil** [comment]
not serverAndCache.  cacheAndServer.

**Comment by umutseven92** [comment]
@creativecreatorormaybenot As per [the documentation](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Source-class.html), _serverAndCache_:

> Causes Firestore to try to retrieve an up-to-date (server-retrieved) snapshot, but fall back to returning cached data if the server can't be reached.

I think what @stemuk is asking for is _cacheAndServer_, where Firestore tries to retrieve from the cache first, and goes to the server only if no up-to-date data is found in the cache.

**Comment by collinjackson** [comment]
Using the [Source](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Source-class.html#serverAndCache) API added in 0.12.1, the developer can manually retrieve from the cache first (e.g. using a try/catch statement), then query again using the default source behavior.

While it's possible that we could build some Dart-side helpers to do this for the developer automatically, we are trying to keep the Flutter cloud_firestore API as close to the native API as possible, and the native SDKs don't have this functionality yet.

I'll leave this issue open for now to give folks a chance to comment, but I think there's no action for the Flutter team here. Once cache-first functionality is available in the native SDKs we'd be happy to accept changes to the cloud_firestore plugin to achieve feature parity. In the meantime, you could publish helper methods as a package if you want, or file feature requests against the native SDKs here:

https://github.com/firebase/firebase-ios-sdk/issues
https://github.com/firebase/firebase-android-sdk/issues

**Comment by uuunk** [comment]
Per @collinjackson, I added an issue for the ios-sdk: https://github.com/firebase/firebase-ios-sdk/issues/3393

**Comment by uuunk** [comment]
FWIW it looks like this 'cacheThenServer' approach is already how snapshot listeners are working:
https://github.com/firebase/firebase-ios-sdk/issues/3393#issuecomment-513259433

**Comment by kroikie** [comment]
@stemuk

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/765. Any further collaboration will be done there.

**Comment by cubuspl42** [comment]
As FirebaseExtended/flutterfire#765 is now closed and locked, while the feature is still not implemented, I've created yet another issue:
https://github.com/FirebaseExtended/flutterfire/issues/3241

**Comment by ycv005** [comment]
@blaneyneil  @umutseven92 Here is what you are looking for - https://pub.dev/packages/firestore_cache. (Either you can use this code or have a look at its code)

**Comment by JamesCullum** [comment]
If you don't want to use a full package, you can find a convenient snippet here: https://stackoverflow.com/a/66017875/1424378

**Comment by amardeep-singh97** [comment]
I just implemented it in flutter. You can use this code to access cache instead of pining firebase
`var snapShot = await FirebaseFireStore.instance
            .collection('myCollection')
            .doc(myID)
            .get(GetOptions(source: Source.cache));`

and then use

`snapShot.data()`

to access the Map
