### ISSUE TITLE
Localization of iOS information in Info.plist

### ISSUE THREAD

**Issue by sestegra** [flutter/flutter#19075]
If we take the example of camera plugin, we need to add a text to inform user about the permissions request.
https://github.com/flutter/plugins

Is there a way with flutter command line to prepare Info.plist to support multiple language in Info.plist ?

**Comment by iskakaushik** [comment]
Take a look at the appendix section of https://flutter.io/docs/development/accessibility-and-localization/internationalization for how you could internationalize your app.

[This page](https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881) has detailed walk-through on how you could do it.

Please let me know if this does not solve your issue.

**Comment by sestegra** [comment]
It would be better not to use XCode.

A solution could be
- Dart or Yaml file
- flutter command to populate XML strings (for Android) and Info.plist and related XCode files (for iOS)

**Comment by iskakaushik** [comment]
@sestegra We are trying to nail down what things make sense to be part of flutter tooling. Will keep this issue open.

**Comment by jmagman** [comment]
You can leverage CocoaPods to [update the podspec](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles) to include [strings files or images or whatever other resources ](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/20001119-105003)the iOS framework needs to support.


Example:
https://github.com/CocoaPods/CocoaPods/issues/4851

It would be nice if the tool or [intl_translation](https://pub.dev/documentation/intl_translation/) generated this, obviously, but that's the workaround.

Can you explain what you would need to localize in the plugin framework Info.plist?  I get why one would [update the app's Info.plist](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle), but what would need to be updated on the plugin framework Info.plist?

**Comment by jmagman** [comment]
Or, is this a request to generate localization resources for an app?  In which case, does this have anything to do with plugins?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
