### ISSUE TITLE
Internalize our ideviceinstaller dependency

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1907]
Right now we depend on ideviceinstaller on Mac for iOS (and effectively for Android, see #1893).

It's the only uncommon direct dependency we have now other than XCode. As such, it's the only reason to set up homebrew.

If we could somehow internalize this dependency, it would remove all our homebrew issues and our ideviceinstaller issues, and make life easier for devs.

**Comment by Hixie** [comment]
Actually I just discovered you also need `ios-deploy`.

**Comment by abarth** [comment]
We can put the binaries in cloud storage and download them.

**Comment by Hixie** [comment]
Going to close this. We can deal with this in the context of streamlining our install process.
