### ISSUE TITLE
How to write a widget test with  http get request?

### ISSUE THREAD

**Issue by wangtun** [flutter/flutter#19086]
![image](https://user-images.githubusercontent.com/14052340/42308574-910157fc-8068-11e8-8bde-bdab518fb4b9.png)
![image](https://user-images.githubusercontent.com/14052340/42308851-7ac210b6-8069-11e8-849b-99b259957940.png)

I have a widget with a request when it is inited. but it throws 'Failed to load post' error. would you please tell me how to write a widget test of widgets with http request, thanks

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/blob/9f8a70be4cea69660ffc8bf48fe82a0f98d0ad23/packages/flutter/test/widgets/image_headers_test.dart contains an example how to mock an HTTP server using the `mockito` package.

Here is an example for responding with an image https://github.com/flutter/flutter/blob/9f8a70be4cea69660ffc8bf48fe82a0f98d0ad23/dev/manual_tests/test/mock_image_http.dart

When I last tried recently the `runZoned` approach didn't work for me (might have done something wrong) but just

```dart
import 'dart:io';
...
setUp(() {
  HttpOverrides.global = MyTestHttpOverrides();
});

worked for me.

You don't need to use `mockito`, your `MyTestHttpOverrides()` can also forward the request to a real server and return the actual response.

**Comment by wangtun** [comment]
@zoechi thank you very much, I will try according to your illustration

**Comment by anuragvohraec** [comment]
> You don't need to use `mockito`, your `MyTestHttpOverrides()` can also forward the request to a real server and return the actual response.

How do you do that ?
Do you have a real example for the same ?
