### ISSUE TITLE
hot reload is getting stuck

### ISSUE THREAD

**Issue by himakiran** [flutter/flutter#19088]
When i try to use hot reload on  Android Studio on My Mac MacOsHighSierra 10.13.5 .. it gets hung and becomes non responsive. (Refer screenshotA)

The full specs are attached at ScreenshotB
![screenshotb](https://user-images.githubusercontent.com/1641414/42312730-b9247c5a-805e-11e8-8514-8efe37f306a3.png)
![screenshota](https://user-images.githubusercontent.com/1641414/42312731-b97791b0-805e-11e8-84f2-1b87cbd75a2f.png)

**Comment by zoechi** [comment]
I assume this issue is stale. Please let us know if you're still seeing this problem and we'll reopen.

**Comment by sahilgithub** [comment]
Hi facing the same issue. hot reload getting struck. but run smoothly on first run.
![Screenshot 2019-08-25 at 8 55 22 PM](https://user-images.githubusercontent.com/8469525/63652154-c2398d80-c77a-11e9-982b-c9c5d1e7e237.png)
