### ISSUE TITLE
default Flutter project not compiling

### ISSUE THREAD

**Issue by MarcelStassen** [flutter/flutter#19098]
## Steps to Reproduce

1. create new project  follow [https://flutter.io/using-ide/#creating-a-new-project]

2.  flutter run or F5 in VS Code
3.  Launching lib/main.dart on Nokia 7 plus in debug mode...
Initializing gradle...                                       0,6s
Resolving dependencies...                                    0,8s
Running 'gradlew assembleDebug'...
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/material/search.dart:234:58: Error: Too few positional arguments: 1 required, 0 given.
compiler message:   final TextEditingController _queryTextController = new TextEditingController();
compiler message:                                                          ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/widgets/editable_text.dart:60:3: Context: Found this candidate, but the arguments don't match.
compiler message:   TextEditingController(Map<String, dynamic> map, { String text })
compiler message:   ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/material/text_field.dart:337:25: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       _controller = new TextEditingController();
compiler message:                         ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/widgets/editable_text.dart:60:3: Context: Found this candidate, but the arguments don't match.
compiler message:   TextEditingController(Map<String, dynamic> map, { String text })
compiler message:   ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/material/text_form_field.dart:135:25: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       _controller = new TextEditingController(text: widget.initialValue);
compiler message:                         ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/widgets/editable_text.dart:60:3: Context: Found this candidate, but the arguments don't match.
compiler message:   TextEditingController(Map<String, dynamic> map, { String text })
compiler message:   ^
Compiler failed on D:\Mars\Documents\Github\CarAppReact\car_cost\lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Mars\Documents\Github\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'D:\Mars\Documents\Github\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Gradle build failed: 1

## Logs

```
```

[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.137], locale nl-NL)
    • Flutter version 0.5.1 at D:\Mars\Documents\Github\flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Mars\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter  <-- is installed

[√] Connected devices (1 available)
    • Nokia 7 plus • B2NGAA8830513186 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Could you please try 
```sh
flutter packages get
flutter clean
flutter run
```
In a shell in the project directory - the one that contains `pubspec.yaml`?

**Comment by MarcelStassen** [comment]
PS D:\Mars\Documents\Github\CarAppReact\car_cost> ls


    Directory: D:\Mars\Documents\Github\CarAppReact\car_cost


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         5-7-2018     17:18                .idea
d-----         5-7-2018     17:54                .vscode
d-----         5-7-2018     17:19                android
d-----         5-7-2018     18:09                build
d-----         5-7-2018     17:18                ios
d-----         5-7-2018     17:18                lib
d-----         5-7-2018     17:18                test
-a----         5-7-2018     17:18             74 .gitignore
-a----         5-7-2018     17:18            292 .metadata
-a----         5-7-2018     18:08           5973 .packages
-a----         5-7-2018     17:18            913 car_cost.iml
-a----         5-7-2018     17:18           1478 car_cost_android.iml
-a----         5-7-2018     18:08           8749 pubspec.lock
-a----         5-7-2018     17:18           1871 pubspec.yaml
-a----         5-7-2018     17:18            157 README.md


PS D:\Mars\Documents\Github\CarAppReact\car_cost> flutter packages get
Running "flutter packages get" in car_cost...                0,6s
PS D:\Mars\Documents\Github\CarAppReact\car_cost> flutter clean
Deleting 'build\'.
PS D:\Mars\Documents\Github\CarAppReact\car_cost> flutter run
Launching lib/main.dart on Nokia 7 plus in debug mode...
Initializing gradle...                                       0,6s
Resolving dependencies...                                    0,8s
Running 'gradlew assembleDebug'...
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/material/search.dart:234:58: Error: Too few positional arguments: 1 required, 0 given.
compiler message:   final TextEditingController _queryTextController = new TextEditingController();
compiler message:                                                          ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/widgets/editable_text.dart:60:3: Context: Found this candidate, but the arguments don't match.
compiler message:   TextEditingController(Map<String, dynamic> map, { String text })
compiler message:   ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/material/text_field.dart:337:25: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       _controller = new TextEditingController();
compiler message:                         ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/widgets/editable_text.dart:60:3: Context: Found this candidate, but the arguments don't match.
compiler message:   TextEditingController(Map<String, dynamic> map, { String text })
compiler message:   ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/material/text_form_field.dart:135:25: Error: Too few positional arguments: 1 required, 0 given.
compiler message:       _controller = new TextEditingController(text: widget.initialValue);
compiler message:                         ^
compiler message: file:///D:/Mars/Documents/Github/flutter/packages/flutter/lib/src/widgets/editable_text.dart:60:3: Context: Found this candidate, but the arguments don't match.
compiler message:   TextEditingController(Map<String, dynamic> map, { String text })
compiler message:   ^
Compiler failed on D:\Mars\Documents\Github\CarAppReact\car_cost\lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Mars\Documents\Github\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'D:\Mars\Documents\Github\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Gradle build failed: 1

gives the same result

**Comment by zoechi** [comment]
The errors seem really weird, none of them look familiar.
Can you please check if this makes a difference
```sh
flutter channel dev
flutter doctor
flutter run
```

**Comment by MarcelStassen** [comment]
Thanks, it works now 

did the flutter channel dev 
and flutter doctor  and there are no more error's

**Comment by zoechi** [comment]
@MarcelStassen great! With the next beta version you can switch back to `beta` if you prefer.

**Comment by NotSharwan** [comment]
^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:78:5: Error: Type 'ui.TextHeightBehavior' not found.
    ui.TextHeightBehavior textHeightBehavior,
    ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:281:3: Error: Type 'ui.TextHeightBehavior' not found.
  ui.TextHeightBehavior get textHeightBehavior => _textPainter.textHeightBehavior;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:282:26: Error: Type 'ui.TextHeightBehavior' not found.
  set textHeightBehavior(ui.TextHeightBehavior value) {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:145:5: Error: Type 'ui.TextHeightBehavior' not found.
    ui.TextHeightBehavior textHeightBehavior,
    ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:346:3: Error: Type 'ui.TextHeightBehavior' not found.
  ui.TextHeightBehavior get textHeightBehavior => _textHeightBehavior;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:347:3: Error: Type 'ui.TextHeightBehavior' not found.
  ui.TextHeightBehavior _textHeightBehavior;
  ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:348:26: Error: Type 'ui.TextHeightBehavior' not found.
  set textHeightBehavior(ui.TextHeightBehavior value) {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_style.dart:1070:5: Error: Type 'ui.TextHeightBehavior' not found.
    ui.TextHeightBehavior textHeightBehavior,
    ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/basic.dart:5156:12: Error: 'TextHeightBehavior' isn't a type.
  final ui.TextHeightBehavior textHeightBehavior;
           ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/implicit_animations.dart:1589:12: Error: 'TextHeightBehavior' isn't a type.
  final ui.TextHeightBehavior textHeightBehavior;
           ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/implicit_animations.dart:1619:8: Error: 'TextHeightBehavior' isn't a type.
    ui.TextHeightBehavior textHeightBehavior,
       ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/implicit_animations.dart:1658:43: Error: 'TextHeightBehavior' isn't a type.
    properties.add(DiagnosticsProperty<ui.TextHeightBehavior>('textHeightBehavior', textHeightBehavior, defaultValue: null));
                                          ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/media_query.dart:127:51: Error: The getter 'highContrast' isn't defined for the class 'AccessibilityFeatures'.
 - 'AccessibilityFeatures' is from 'dart:ui'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'highContrast'.
      highContrast = window.accessibilityFeatures.highContrast,
                                                  ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:98:8: Error: 'TextHeightBehavior' isn't a type.
    ui.TextHeightBehavior textHeightBehavior,
       ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:153:12: Error: 'TextHeightBehavior' isn't a type.
  final ui.TextHeightBehavior textHeightBehavior;
           ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:204:43: Error: 'TextHeightBehavior' isn't a type.
    properties.add(DiagnosticsProperty<ui.TextHeightBehavior>('textHeightBehavior', textHeightBehavior, defaultValue: null));
                                          ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:436:12: Error: 'TextHeightBehavior' isn't a type.
  final ui.TextHeightBehavior textHeightBehavior;
           ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:491:43: Error: 'TextHeightBehavior' isn't a type.
    properties.add(DiagnosticsProperty<ui.TextHeightBehavior>('textHeightBehavior', textHeightBehavior, defaultValue: null));
                                          ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/transitions.dart:1006:12: Error: 'TextHeightBehavior' isn't a type.
  final ui.TextHeightBehavior textHeightBehavior;
           ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:78:8: Error: 'TextHeightBehavior' isn't a type.
    ui.TextHeightBehavior textHeightBehavior,
       ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:282:29: Error: 'TextHeightBehavior' isn't a type.
  set textHeightBehavior(ui.TextHeightBehavior value) {
                            ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:145:8: Error: 'TextHeightBehavior' isn't a type.
    ui.TextHeightBehavior textHeightBehavior,
       ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:347:6: Error: 'TextHeightBehavior' isn't a type.
  ui.TextHeightBehavior _textHeightBehavior;
     ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:348:29: Error: 'TextHeightBehavior' isn't a type.
  set textHeightBehavior(ui.TextHeightBehavior value) {
                            ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:421:7: Error: No named parameter with the name 'textHeightBehavior'.
      textHeightBehavior: _textHeightBehavior,
      ^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/text.dart:877:3: Context: Found this candidate, but the arguments don't match.
  ParagraphStyle({
  ^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_style.dart:1070:8: Error: 'TextHeightBehavior' isn't a type.
    ui.TextHeightBehavior textHeightBehavior,
       ^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_style.dart:1091:7: Error: No named parameter with the name 'textHeightBehavior'.
      textHeightBehavior: textHeightBehavior,
      ^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/text.dart:877:3: Context: Found this candidate, but the arguments don't match.
  ParagraphStyle({
