### ISSUE TITLE
Rendering PNG problem

### ISSUE THREAD

**Issue by skybur** [flutter/flutter#19090]
Hello, I have a problem when using `Image.network`. Some PNG image rendered inverted in Redmi 3S (MIUI 9.5/Android 6.0) while the same image not rendered at all in Nox Emulator 6.0.3 (Android 4.4.2). Haven't tried other devices. Maybe related to #15600.

## Steps to Reproduce

1. Create new flutter project
2. Add an `Image.network` widget with url: https://imgs.xkcd.com/comics/upside_down_map.png
3. Run app
4. Compare with image opened in browser
5. Here's a screenshot (The first image, don't mind the second image)
![screenshot_2018-07-05-14-55-50-072_com terreciel testpng](https://user-images.githubusercontent.com/11155424/42313593-54758f1a-806d-11e8-9bf3-be6a2e0e16df.png)

## Logs
- flutter run --verbose:
[flutterlog.txt](https://github.com/flutter/flutter/files/2165872/flutterlog.txt)

- flutter doctor -v
```
D:\Repos\flutter-dev\test_png>flutter doctor -v
[√] Flutter (Channel master, v0.5.6-pre.122, on Microsoft Windows [Version 10.0.17134.112], locale en-ID)
    • Flutter version 0.5.6-pre.122 at D:\Repos\flutter-dev\flutter
    • Framework revision 84f5b1cb09 (2 days ago), 2018-07-02 17:20:26 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.15.0

[√] Connected devices (2 available)
    • Redmi 3S  • c37ae0927d63    • android-arm64 • Android 6.0.1 (API 23)
    • G621 TL00 • 127.0.0.1:62001 • android-x86   • Android 4.4.2 (API 19)

• No issues found!
```

**Comment by GaryQian** [comment]
Just to rule out the not rendering at all issue, are you sure your nox emulator is connected to the internet? Nothing renders at all if there is no network to download the image.

**Comment by GaryQian** [comment]
I can't seem to reproduce on devices that are not the RedMi 3s, and since I don't have one to test on, could you try to use a Stack widget and stack the .png onto a colored background. This is to see if the white edges in your image above is actually a transparent section (as is the case in https://github.com/flutter/flutter/issues/15600)  or if it is simply being inverted (which means it is more likely to be a separate issue).

**Comment by skybur** [comment]
Hello, thank you for responding.

> Just to rule out the not rendering at all issue, are you sure your nox emulator is connected to the internet? Nothing renders at all if there is no network to download the image.

It's connected to internet. Image on the bottom is loaded while the other one is not rendered.
![nox_2018-09-16_17-47-11](https://user-images.githubusercontent.com/11155424/45595625-fb994300-b9d8-11e8-8c36-d7a0a86ab86b.png)
And here is in Redmi 3S
![photo6120734263075776543](https://user-images.githubusercontent.com/11155424/45595659-57fc6280-b9d9-11e8-96fd-184d1cb9ba1e.jpg)
And here is the flutter doctor output
```
PS D:\Devs\Flutter\sandbox> flutter doctor -v
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17754.1], locale en-US)
    • Flutter version 0.7.3 at D:\Devs\Flutter\flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.27.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • Redmi 3S • c37ae0927d63 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by skybur** [comment]
> 
> 
> Sorry for not coming back to this earlier.
> I assume this issue is stale. Please let us know if you're still seeing this problem.

I also forgot I made this issue. Currently using stable branch, this issue is not happening anymore.
