### ISSUE TITLE
cloud_firestore - orderBy function of firestore plugin has a strange behaviour

### ISSUE THREAD

**Issue by huextrat** [flutter/flutter#19101]
Hi,

Currently, I'm using firestore in a flutter project and I have to sort data (number), but it has a strange behaviour indeed it considers that 11 is smaller than 9.

After several tests I think that the plugin only takes into account the first digit of the number and not the whole number ...

My code look like this : 

```
child: new StreamBuilder<QuerySnapshot>(
            stream: Firestore.instance.collection(new DateTime(DateTime.now().year, DateTime.now().month, 1).toString()).orderBy("score", descending: true).snapshots(),
            builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
              if (!snapshot.hasData) return new Center(child: CircularProgressIndicator(backgroundColor: primaryBlue,));
              return new Container(
                child: new ListView(children: getExpenseItems(snapshot), padding: new EdgeInsets.only(top: 10.0),),
              );
            }),
```

For instance if I have 4 numbers: <b>4, 11, 22, 9</b> the order by cloud_firestore is: <b>11, 22, 4, 9</b> when it should be: <b>4, 9, 11, 22</b>

Kind regards

**Comment by zoechi** [comment]
Sounds like it treats it as string value and orders alphabetically, not as number.
Probably because of `.toString()`

**Comment by huextrat** [comment]
I don't think since it's supposed to order the documents by the field named score.
I only use ```.tostring()``` to convert date to string but this side works well.

I have a firestore db like this:
2018-07-01  --> Paris --> score (int)

**Comment by zoechi** [comment]
@huextrat right, misinterpteted the code.

**Comment by zoechi** [comment]
The sorting should be done by the server so Flutter or the plugin should not be involved.
Have you checked in the database that the values are stored as number (without quotation marks) not as string?

**Comment by huextrat** [comment]
Yes, atm this is the only way to hack it but if cloud_firestore purpose a ```.orderBy()``` function it should work properly.

I tried both (number and string) and it returns the same result :/

**Comment by zoechi** [comment]
>  this is the only way to hack it

I don't understand what you are referring to. How do you hack it?

**Comment by huextrat** [comment]
The only way to hack it, is to sort data server side as you said

**Comment by zoechi** [comment]
I assumed this was the default behavior without doing anything explicit.
What do you mean by "sort data server side". Do you mean persisting it sorted already? That's definitely not what `orderBy()` is about :D

**Comment by huextrat** [comment]
That's why I opened the issue, I have to use orderBy() but I want the right result xD

I test it directly in the database and I think the problem is not from the dart dependencie but from firebase firestore

**Comment by zoechi** [comment]
> I test it directly in the database

What is the result if you test it directly in the database?

If the issue is from the database then there is nothing the Flutter plugin can do.

**Comment by huextrat** [comment]
Same result as the plugin so the issue is from firebase not from the plugin, I'm pretty sure it worked before :/ 

Thank you

**Comment by zoechi** [comment]
@huextrat great, thanks for the feedback.

**Comment by buster95** [comment]
orderBy function work when you added indexes in cloud_firestore
https://firebase.google.com/docs/firestore/query-data/indexing?authuser=0

**Comment by kroikie** [comment]
@huextrat

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/764. Any further collaboration will be done there.
