### ISSUE TITLE
Error retrieving device properties for ro.product.cpu.abi: error: device still connecting??

### ISSUE THREAD

**Issue by Mahmoudlashin** [flutter/flutter#19108]
Launching lib\main.dart on 6AGDU17522002686 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: C:\Users\Any\AndroidStudioProjects\vme\android\gradlew.bat app:properties:
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.2.0/kotlin-reflect-1.2.0.jar

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Any\AndroidStudioProjects\vme\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve com.android.tools.build:builder-test-api:3.1.2.
     Required by:
         unspecified:unspecified:unspecified > com.android.tools.build:gradle:3.1.2 > com.android.tools.build:gradle-core:3.1.2 > com.android.tools.build:builder:3.1.2
         unspecified:unspecified:unspecified > com.android.tools.build:gradle:3.1.2 > com.android.tools.build:gradle-core:3.1.2 > com.android.tools.build:gradle-api:3.1.2
         unspecified:unspecified:unspecified > com.android.tools.build:gradle:3.1.2 > com.android.tools.build:gradle-core:3.1.2 > com.android.tools.build:builder:3.1.2 > com.android.tools:sdk-common:26.1.2
      > Could not resolve com.android.tools.build:builder-test-api:3.1.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/builder-test-api/3.1.2/builder-test-api-3.1.2.jar'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/builder-test-api/3.1.2/builder-test-api-3.1.2.jar'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 47s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by zoechi** [comment]
Thanks for reporting.
I have seen this error when the emulator was not ready starting.
Can you reproduce this on subsequent tries or was this a single issue?

Can you please also add the output of `flutter doctor -v`

**Comment by Mahmoudlashin** [comment]
Microsoft Windows [Version 10.0.16299.492]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Any>flutter doctor -v
[√] Flutter (Channel master, v0.5.6-pre.113, on Microsoft Windows [Version 10.0.16299.492], locale en-US)
    • Flutter version 0.5.6-pre.113 at C:\flutter
    • Framework revision 7f7ea2d500 (7 days ago), 2018-06-29 14:42:36 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Any\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.4
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
