### ISSUE TITLE
Proguard configuration when use google_sign_in (3.0.4) plugin

### ISSUE THREAD

**Issue by magnumrocha** [flutter/flutter#19102]
Hi guys,

I am using the google_sign_in (v. 3.0.4) in my flutter app.

After wast a time trying to build an Android APK release with different kind of proguard rules. My build only works if I set the following rules:

```
# Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

# GooglePlay Services
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
-keep class com.google.common.** { *; }
-dontwarn com.google.common.**
```

Can you tell me if is this correct ??

**Comment by zoechi** [comment]
Related to #11099

**Comment by jmagman** [comment]
\cc @blasten https://github.com/flutter/flutter/pull/39986

**Comment by blasten** [comment]
This isn't needed on stable anymore. so you don't need custom proguard configurations!
