### ISSUE TITLE
TextField is missing a real maxLines.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#19105]
A common UI pattern is having a text field which grows vertically, adding more lines, as you type, up to a certain number of lines, after which the content scrolls.

Presently, we can have a growing `TextField` by making `maxLines=null`. However, then the `TextField` never stops growing. Otherwise, if we make, say, `maxLines=6`, then it will have 6 fixed lines, and will not grow.

Unfortunatelly, `maxLines` was a bad name. That should have been called simply "lines", since it fixes the number of lines, and is not a maximum. However, that cannot be changed anymore.

I will now suggest adding another parameter, called `maxLineLimit`, which lets the number of lines grow until that number and then no more. And while we're at that, I would also add the less important `minLineLimit`.

So, for example, if we make `maxLines=null, minLineLimit=2, maxLineLimit=6`, then the `TextField` starts with 2 lines, and, if necessary to fit the text, grows until 6 lines. After that it scrolls.

This change is very easy to do, in file `editable.dart`, the method `_preferredHeight` in `class RenderEditable` has these last 2 lines:
```dart
    _layoutText(width);
    return math.max(preferredLineHeight, _textPainter.height);
```
These could be simply changed to:
```dart
      _layoutText(width);
      return math.min(preferredLineHeight * maxLineLimit, math.max(preferredLineHeight * minLineLimit, _textPainter.height));
```

**Comment by marcglasberg** [comment]
Note: As a workaround I have tried to fix the max height of the TextField, by using a ConstrainedBox with maxHeight. However, as soon as the text is enough to pass maxHeight, the TextField actually writes some text outside of its area. I tried adding padding to fix this, but then it creates other problems when there is little text. In other words, I couldn't find a workaround.

**Comment by zoechi** [comment]
Using a `ConstrainedBox` with a `SingleChildScrollView` around the `TextField` worked for me.

**Comment by marcglasberg** [comment]
Thanks Gunter, by now I have already cloned the necessary files and fixed the problem to myself by adding `minLineLimit` and `maxLineLimit` parameters:

    RenderEditable({
        ...
        int maxLines = 1,
        int maxLineLimit = 1000000,
        int minLineLimit = 1,
        ...

Then:

    int get maxLineLimit => _maxLineLimit;
    int _maxLineLimit;

    int get minLineLimit => _minLineLimit;
    int _minLineLimit;

Then:

    double _preferredHeight(double width) {
      if (maxLines != null) return preferredLineHeight * maxLines;
      if (width == double.infinity) {
        final String text = _textPainter.text.toPlainText();
        int lines = 1;
        for (int index = 0; index < text.length; index += 1) {
          if (text.codeUnitAt(index) == 0x0A) // count explicit line breaks
            lines += 1;
        }
        return preferredLineHeight * lines;
      }
      _layoutText(width);  
      return min(preferredLineHeight * maxLineLimit,
          max(preferredLineHeight * minLineLimit, _textPainter.height));
    }

I can confirm this easy change works perfectly as intended. 

@sandrasandeep I saw that you just recently made changes to the `editable.dart` file, concerning the TextField cursor, so please consider if you would be interested in fixing this problem too. Thanks.

**Comment by sandrasandeep** [comment]
Will look at this once I am finished landing a couple other changes.

**Comment by marcglasberg** [comment]
@sandrasandeep Thank you! I also posted (in a comment) the code to fix this other problem also related to the TextField, in case you are interested: https://github.com/flutter/flutter/issues/11416

**Comment by goderbauer** [comment]
Adding "customer: crowd" because a duplicated bug had a lot of upvotes.

**Comment by justinmc** [comment]
@marcglasberg I've just written a proposal for a way to solve this problem and a few other related issues, and I could really use your input if you're still interested.  I borrowed heavily from your min/max line limit idea.

https://github.com/flutter/flutter/pull/27205

**Comment by zoechi** [comment]
Looks like a dup of #15388

**Comment by marcglasberg** [comment]
@justinmc Great! Please make maxLines a double, not an int. I explained the reasoning in a comment in #27205.

**Comment by marcglasberg** [comment]
@justinmc Please also see: https://github.com/flutter/flutter/pull/27205#issuecomment-459588363

**Comment by justinmc** [comment]
Closing this with https://github.com/flutter/flutter/pull/27205.

With that PR, you can now achieve the requested functionality like this as an example:

```dart
TextField(
  minLines: 2,
  maxLines: 4,
)
```
