### ISSUE TITLE
something wrong with flutter doctor

### ISSUE THREAD

**Issue by marklimeichao** [flutter/flutter#19107]
## Steps to Reproduce
54615@▒▒▒▒ MINGW64 ~
$ flutter doctor
Downloading Dart SDK from Flutter engine 6fe748490d1772d72274bf8b9efb72c5c2160237...
Unknown operating system. Cannot install Dart SDK.

## Logs

```
```

```
```

**Comment by zoechi** [comment]
dup of #18953

If you use MinGW it is likely related. Can you reproduce in PowerShell or a normal command prompt?

**Comment by dalinpeng** [comment]
![image](https://user-images.githubusercontent.com/28720577/44707969-81ac2300-aad8-11e8-9942-854187add74f.png)
Execute command in CMD and nothing happened several hours later,

**Comment by zoechi** [comment]
@dalinpeng did you follow https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?

**Comment by dalinpeng** [comment]
Yes. PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL are configured, actually it's worked on android studio 3.1.3, but after upgrade to 3.1.4, the flutter project can't find the devices,always shows loading,and execute the flutter doctor then nothing happened like image

**Comment by zoechi** [comment]
@dalinpeng can you please create a new issue with the above information.
This one is closed and it seems to have a different cause.
