### ISSUE TITLE
Not able to release the apk version of app. (Build failed with an exception)

### ISSUE THREAD

**Issue by VickySalunkhe** [flutter/flutter#19106]
Build is always getting failed due to some unknown issues.
I tried to create new projects but still the problem is occurring.
App is running perfectly without any errors.
but when i am trying to build and apk of it using steps in https://flutter.io/android-release/
the issue is generated.

## Steps to Reproduce

1. ... Make any new flutter application
2. ...Try to make an android release of the application with the steps mentioned in https://flutter.io/android-release/

## Generated lines when tried to compile release version of app
Launching lib\main.dart on Redmi Note 4 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\gradlew.bat app:properties:
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\app\build.gradle' line: 42
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not normalize path for file 'C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\app\<D:\Vicky\keystore.jks>'.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
Finished with error: Please review your Gradle project setup in the android/ folder.

## Logs   (flutter run --verbose)
```
<Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\vicky>flutter run --verbose
[  +27 ms] [D:\Vicky\flutter_windows_v0.4.4-beta\] git rev-parse --abbrev-ref --
symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [D:\Vicky\flutter_windows_v0.4.4-beta\] git rev-parse --abbrev-ref HE
AD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [D:\Vicky\flutter_windows_v0.4.4-beta\] git ls-remote --get-url origi
n
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [D:\Vicky\flutter_windows_v0.4.4-beta\] git log -n 1 --pretty=format:
%H
[  +25 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [D:\Vicky\flutter_windows_v0.4.4-beta\] git log -n 1 --pretty=format:
%ar
[  +24 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[        ] [D:\Vicky\flutter_windows_v0.4.4-beta\] git describe --match v*.*.* -
-first-parent --long --tags
[  +27 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long -
-tags
[        ] v0.5.1-0-gc7ea3ca37
[ +100 ms] "flutter run" took 22ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter
_command.dart:427)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:
247)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/fl
utter_command.dart:323)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner
/flutter_command.dart:279)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/conte
xt.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dar
t:270)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_too
ls/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/conte
xt.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutte
r_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
109)
#19     new Future.sync (dart:async/future.dart:222)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_comma
nd_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/conte
xt.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:50)
#30     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#31     main (file:///D:/Vicky/flutter_windows_v0.4.4-beta/packages/flutter_tool
s/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isola
te_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isol
ate_patch.dart:165)


```

## flutter analyze

##flutter doctor -v
`C:\Users\vicky\AndroidStudioProjects\suraj_intergold>flutter doctor -v
[ΓêÜ] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 6.1.7601], lo
cale en-IN)
    ΓÇó Flutter version 0.5.1 at D:\Vicky\flutter_windows_v0.4.4-beta
    ΓÇó Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    ΓÇó Engine revision 1ed25ca7b7
    ΓÇó Dart version 2.0.0-dev.58.0.flutter-f981f09760

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    ΓÇó Android SDK at C:\Users\vicky\AppData\Local\Android\sdk
    ΓÇó Android NDK location not configured (optional; useful for native profili
ng support)
    ΓÇó Platform android-28, build-tools 28.0.0
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b
02)
    ΓÇó All Android licenses accepted.

[ΓêÜ] Android Studio (version 3.1)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Flutter plugin version 26.0.1
    ΓÇó Dart plugin version 173.4700
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b
02)

[!] VS Code, 64-bit edition (version 1.24.1)
    ΓÇó VS Code at C:\Program Files\Microsoft VS Code
    ΓÇó Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[ΓêÜ] Connected devices (1 available)
    ΓÇó Redmi Note 4 ΓÇó 9441dce20803 ΓÇó android-arm64 ΓÇó Android 7.0 (API 24)

! Doctor found issues in 1 category.`

**one more issue is there in flutter that
IN vscode flutter plugin is installed and works with no problem still in flutter doctor it shows flutter extension is not installed**

## build.gradle file

https://gist.github.com/VickySalunkhe/b6189b5f3966a0429267a1f661658456

i think the problem starts from line 38 to 45
with the keystore file only

because when i remove those line and run the app in debug version
the app is working fine.

i have tried creating new keystore files and tried 2-3 different keystore files in the process but still no luck.

**Comment by VickySalunkhe** [comment]
but earlier also i tried to build the app , then it worked 
that was 2 weeks ago.
i am fairly new to all this so please co-operate.

**Comment by zoechi** [comment]
First I need information to understand what your situation is.
It looks like `D:\Vicky\keystore.jks` causes the problem and that is not something a Flutter project has set by default.

**Comment by VickySalunkhe** [comment]
D:\Vicky\keystore.jks
is the location of keystore file needed to build the release version of android app.

**Comment by zoechi** [comment]
I'd suggest to add the `keystore.jks` file inside the `suraj_intergold\android\app\external\` directory and use `storeFile=external\keystore.jks` in `key.properties` file.

**Comment by VickySalunkhe** [comment]
Same problem occured

> Finished with error: Please review your Gradle project setup in the android/ folder.
> * Error running Gradle:
> Exit code 1 from: C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\gradlew.bat app:properties:
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\app\build.gradle' line: 42
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Could not normalize path for file 'C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\app\<external\keystore.jks>'.
>

**Comment by zoechi** [comment]
Sorry, can't help you here. Perhaps someone else.

**Comment by aravind99** [comment]
Try  
```
storePassword = *******
keyPassword   = *********
keyAlias           = ********
storeFile=app/external/keystore.jks
```

OR

```
.
.
.
storeFile=D://Vicky/keystore.jks
```

**Comment by VickySalunkhe** [comment]
i tried 
storeFile - app/external/keystore.jks

using that mysteriously the app ran in debug mode in my mobile

but when i tried to make an apk file from it

it generated new error

> 

> C:\Users\vicky\AndroidStudioProjects\suraj_intergold>flutter build apk
> Initializing gradle...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:validateSigningRelease'.
> > Keystore file C:\Users\vicky\AndroidStudioProjects\suraj_intergold\android\app
> \<app\external\keystore.jks> not found for signing config 'release'.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 24s
> Gradle build failed: 1
> 

i tried another Keystore file which i used earlier to sign the app but with that also same error occured.



Second method.
try
storeFile=D://Vicky/keystore.jks

This gave the same as previous ones.

**Comment by LeonidVeremchuk** [comment]
Same problem +1

**Comment by zoechi** [comment]
@LeonidVeremchuk Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.

**Comment by VickySalunkhe** [comment]
Can any flutter developer take a look at this issue please...

**Comment by zoechi** [comment]
You could try `dev` channel 
and also create a new project with `flutter create` and compare generated config files with the ones in your project (perhaps something was changed in the meantime and Flutter expects some settings in a different form).

**Comment by fykid** [comment]
i tried this and it worked for me
   storeFile=D:\\Vicky\\keystore.jks
user double forward slash

**Comment by VickySalunkhe** [comment]
sorry, forgot to close the issue, The solution which actually worked for me is bit weird. 
i removed '<' and '>' from the keystore file, and everything worked fine. thankyou all for the help.

**Comment by fykid** [comment]
Ok! All the best

Sent from Mail for Windows 10

**Comment by MakariKevin** [comment]
Those tags('<' and '>') will for sure confuse a newbie to flutter. I think the documentation isn't meant for the starters at low level since small yet critical details have been taken for granted. I've been a victim before I bumped into this thread, @VickySalunkhe thanks!

**Comment by incepio-flutter** [comment]
<img width="730" alt="Screenshot 2019-12-23 at 6 51 57 AM" s@MakariKevin "https://user-images.githubusercontent.com/57838430/71330787-b73c1180-2550-11ea-9dde-6aaca13cb6c7.png">




@MakariKevin @VickySalunkhe  can you please help me as well ?

**Comment by incepio-flutter** [comment]
can any one help me as well ?

**Comment by Asma-cloud** [comment]
* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\Users\<namaj>\abc.jks' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by VickySalunkhe** [comment]
> can any one help me as well ?

what is the issue you are facing?

**Comment by Asma-cloud** [comment]
Thanks for replying.. I solved tdy. thank you again..

**Comment by Raquelgoiania** [comment]
Boa noite!

Ainda sem entender o comentário " removi '<' e '>' do arquivo keystore e tudo funcionou bem. Obrigado a todos pela ajuda." Alguém poderia me ajudar? estou com esse mesmo problema e não entendi a solução,não saio do lugar assim...

**Comment by sourabhmahale** [comment]
if you are windows user then use 
storeFile=C:\\Users\\ABC\\app.jks
This works for me.
Because I search lot  and I use this which solves my problem

**Comment by sainiteshb** [comment]
Hey guys im currently having a problem for releasing my app to play store
The keystone file is at C:/Users/saini/key.jks 


my key.properties file:

storePassword=******
keyPassword=******
keyAlias=key
storeFile=/Users/saini/key.jks 

build.gradile:
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "app.id"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.android.support:multidex:1.0.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
}

When I run the command flutter build apk

i get this error:


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\Users\saini\AndroidStudioProjects\spaceiva\android\app\Users\saini\key.jks ' not foun
d for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ou
tput. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       8.3s
Gradle task assembleRelease failed with exit code 1




Can anyone please help me in this issue as I have to publish my app to the play store but this issue is stopping me

**Comment by Tobotis** [comment]
i have exactly the same issue... :/
