### ISSUE TITLE
How to prevent TabBarView from rebuilding on tab change?

### ISSUE THREAD

**Issue by lakexyde** [flutter/flutter#19116]
Please is there a way I can prevent tabbarviews from rebuilding anytime I switch tabs? I've been having difficulties keeping their individual states.

The parent widget is a Stateless widget using the ```DefaultTabController```.

**Comment by adriancmurray** [comment]
Yeah, I created a complicated way to solve this problem based off what others suggested. Then I learned of a much better solution. Place the child component of each TabBarView into its own class and add the AutomaticKeepAliveClientMixin to the class. 

for example when making a stateful widget: 

`class SampleClassState extends State<SampleClass> with AutomaticKeepAliveClientMixin {}`

**Comment by lakexyde** [comment]
Thanks @adriancmurray . It worked.

**Comment by zoechi** [comment]
@lakexyde I assume it's save to close this issue then?

**Comment by amirfeqhi** [comment]
@adriancmurray What do you mean by this phrase: 

> Place the child component of each TabBarView into its own class

Like @lakexyde I have a stateless widget with DefaultTabController and 3 tabs.
The child of DefaultTabController is another page and in that page I have something like this:

```dart
return Scaffold(
body: TabBarView(
        physics: NeverScrollableScrollPhysics(),
        children: [
          Page1(
            tabBar: tabBarController,
          ),
          Page2(
            tabBar: tabBarController,
          ),
          Page3(
            tabBar: tabBarController,
          ),
        ],
        controller: tabBarController,
      ),
      bottomNavigationBar: Theme(
        data: ThemeData(
            splashColor: Colors.transparent,
            highlightColor: Colors.transparent),
        child: Material(
          child: TabBar(
            tabs: myTabs,
            controller: tabBarController,
          ),
        ),
      ),
);
```
And I did what you said for all 3 page and also put the `super.build(context)` but still I'm getting error.
What's the problem.

**Comment by adriancmurray** [comment]
The original question was more about how to keep tabs in cache rather than being rebuilt which is what my solution was addressing. I can't see exactly what your Page1, 2 or 3 classes look like. Nor do I have a reference to the error you're seeing. Based off of what I do see, it looks as though you're trying to create something similar to the CupertinoTabScaffold. Where you have a bottom row of tabs that control the view of several pages. You might want to give that a try: https://docs.flutter.io/flutter/cupertino/CupertinoTabScaffold-class.html

**Comment by amirfeqhi** [comment]
> The original question was more about how to keep tabs in cache rather than being rebuilt which is what my solution was addressing. I can't see exactly what your Page1, 2 or 3 classes look like. Nor do I have a reference to the error you're seeing. Based off of what I do see, it looks as though you're trying to create something similar to the CupertinoTabScaffold. Where you have a bottom row of tabs that control the view of several pages. You might want to give that a try: https://docs.flutter.io/flutter/cupertino/CupertinoTabScaffold-class.html

@adriancmurray It's not even work on android either.
This is the error: ```
The following assertion was thrown building NotificationListener<KeepAliveNotification>:
Failed assertion: boolean expression must not be null
```
Also it shows nothing in each tab, Just a white (blank) screen.

**Comment by lakexyde** [comment]
I believe in your ```keepAlive``` override you should have this.

```
@override
bool get wantKeepAlive => true;
```

**Comment by adriancmurray** [comment]
@lakexyde might be correct; though you should see this as an error in your IDE before you even run your code. It should tell you that you're missing some overrides before you even compile if that's the case.

**Comment by amirfeqhi** [comment]
> I believe in your `keepAlive` override you should have this.
> 
> ```
> @override
> bool get wantKeepAlive => true;
> ```

@lakexyde I already have this implemented in all of my 3 pages. Like this:

```dart
class Page1 extends StatefulWidget {
  final TabController tabBar;
  Page1({this.tabBar});
  @override
  _Page1State createState() => _Page1State();
}

class _Page1State extends State<Page1>
    with AutomaticKeepAliveClientMixin<Page1> {
Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      body: ...
);
}
@override
  bool get wantKeepAlive => null;
}
```

**Comment by adriancmurray** [comment]
```
@override
  bool get wantKeepAlive => null;
}
```

He was right, that's your issue. It can't be null.

**Comment by amirfeqhi** [comment]
> ```
> @override
>   bool get wantKeepAlive => null;
> }
> ```
> 
> He was right, that's your issue. It can't be null. Instead make that null value "true" and you should be good to go.

@adriancmurray Yeah, the problem was the null. such a mistake 😅
Thank you a lot @adriancmurray and @lakexyde

**Comment by Maunish-dave** [comment]
i have a simple todo list app and i used provider to get the data 
so i do not need to use statefulwidget and so as we can not use AutomaticKeepalivemixin with
the satelesswidget i am not sure how not to rebuild the tabs if there is no change in the data of either 
tabs

**Comment by Nisthar** [comment]
@Maunish-dave Same problem here.

**Comment by danielfpedro** [comment]
> i have a simple todo list app and i used provider to get the data
> so i do not need to use statefulwidget and so as we can not use AutomaticKeepalivemixin with
> the satelesswidget i am not sure how not to rebuild the tabs if there is no change in the data of either
> tabs

You should use same state management as bloc or redux.

**Comment by dekadevelop** [comment]
https://stackoverflow.com/questions/55781317/disable-rebuilds-page-on-change-of-tab-on-bottomnavigationbar
