### ISSUE TITLE
`flutter materialize`: Support for converting a flutter module to a full application template

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#19111]
Flutter modules (`flutter create -t module`) creates projects that have "transient" platform hosts (located in `.android` and `.ios`). This is great when a developer doesn't care about the particulars of those hosts, as we can update them when the change, and as they do not need to be in source control. However, when a developer needs to customize the host (e.g. to change the icon, launchscreen, add platform code) they need support for 'materializing' the host code into a structure where it becomes source code. This tracks said support.

**Comment by mravn-google** [comment]
Only implemented for Android so far.

**Comment by matthew-carroll** [comment]
I'm going to close this ticket in favor per platform tickets.  Also the Android command will need to be renamed to "flutter make-editable" instead of "flutter materialize" as per discussion about confusion around "materialize" and "material design".

See
#21770 
#21771
