### ISSUE TITLE
Support Flutter Module on iOS

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#19113]
- [x] Add iOS support to the Flutter module template
- [x] Dependency steps from xCode to module covered in Wiki https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
- [ ] Reduce amount of boilerplate code needed on the iOS side
- [x] Make sure `flutter attach` works

**Comment by mit-mit** [comment]
The third bullet referred to the fact that you used to have to write a lot fo ObjC code to wire up the flutter view, but looks like that is no longer the case when I look at the add2app wiki page.

**Comment by dnfield** [comment]
I think the original scope of this is covered then.  Closing for now, but please reopen if you disagree!
