### ISSUE TITLE
Help to write custom objects in firestore

### ISSUE THREAD

**Issue by nahuelcabrera** [flutter/flutter#19126]
I am trying to write the objects of my application in Firerestore with flutter, and I find myself without solutions when I write the data, it only allows me the type of Map file, when I want to upload my own objects.

Have you already been practicing this?
Will they have an example?

I do not want to work with map

regards

**Comment by dnys1** [comment]
You want to serialize your objects to Maps: [https://flutter.io/json/](https://flutter.io/json/). 

I would recommend using a package like `json_serializable` or `built_value` so you can avoid manual conversion to and from Map objects.

**Comment by zoechi** [comment]
@nahuelcabrera I believe @dnys1 's suggestion should answers your question.
