### ISSUE TITLE
Firestore crashes when connection turns off

### ISSUE THREAD

**Issue by alexbagirov** [flutter/flutter#19122]
Hi. I have faced an unexpected behavior of Firestore persistence. The problem is that it throws an error when you're running your app and turn off WiFi. After this all database related commands will suspend your app. However, when you restart the app without internet, it seems that all changes have been done.

## Steps to Reproduce

1. Do anything like this:
```dart
Firestore.instance.collection(collection).document().setData(data);
```
or this:
```dart
FutureBuilder<FirebaseUser>(
  future: Auth.currentUser(),
  builder: (context, snapshot) {
    if (snapshot.connectionState == ConnectionState.done) {
      return StreamBuilder<QuerySnapshot>(
        stream: Firestore.instance
                         .collection('collection')
                         .where('owner', isEqualTo: snapshot.data.uid)
                         .snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) {
            return Center(child: CircularProgressIndicator());
          }
          return ListView.builder(
            itemCount: snapshot.data.documents.length,
            itemBuilder: (context, index) {
              var document = snapshot.data.documents[index];
              var documentId = document.documentID;
                      // Display your content somehow
```
2. Run your app and see some data fetched from server
3. Disable the Internet

## Logs

```
V/NativeCrypto(11784): Read error: ssl=0x9e50e908: I/O error during system call, Connection timed out
W/zzaeo   (11784): [{0}] Failed to resolve name. status={1}
V/NativeCrypto(11784): Write error: ssl=0x9e50e908: I/O error during system call, Broken pipe
V/NativeCrypto(11784): Write error: ssl=0x9e50e908: I/O error during system call, Broken pipe
W/zzajf   (11784): Failed closing connection
W/zzajf   (11784): javax.net.ssl.SSLException: Write error: ssl=0x9e50e908: I/O error during system call, Broken pipe
W/zzajf   (11784): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/zzajf   (11784): 	at com.google.android.gms.org.conscrypt.NativeSsl.write(:com.google.android.gms@12685022@12.6.85 (040308-197041431):2)
W/zzajf   (11784): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(:com.google.android.gms@12685022@12.6.85 (040308-197041431):6)
W/zzajf   (11784): 	at com.google.android.gms.internal.firebase-firestore.zzapc.write(Unknown Source)
W/zzajf   (11784): 	at com.google.android.gms.internal.firebase-firestore.zzaot.write(Unknown Source)
W/zzajf   (11784): 	at com.google.android.gms.internal.firebase-firestore.zzapf.close(Unknown Source)
W/zzajf   (11784): 	at com.google.android.gms.internal.firebase-firestore.zzaku.close(Unknown Source)
W/zzajf   (11784): 	at com.google.android.gms.internal.firebase-firestore.zzaim.run(Unknown Source)
W/zzajf   (11784): 	at com.google.android.gms.internal.firebase-firestore.zzahi.run(Unknown Source)
W/zzajf   (11784): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/zzajf   (11784): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/zzajf   (11784): 	at java.lang.Thread.run(Thread.java:818)
W/zzaeo   (11784): [{0}] Failed to resolve name. status={1}
```

```
info • 'debugEnableFadingRoutes' is deprecated and shouldn't be used • lib/main.dart:7:21
info • The method '_signedOut' isn't used • lib/root.dart:33:8

2 issues found. (ran in 10.9s)
```

```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/alex/flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/alex/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Nexus 5 • 0226d62443a398a7 • android-arm • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by DarshanGowda0** [comment]
@alexbagirov you should be using snapshot.connection state to check for active/waiting/done connection states and handle the widgets accordingly rather than using snapshots.hasData

**Comment by alexbagirov** [comment]
Is this fixed now?

**Comment by Ragnaroek** [comment]
No, it isn't. Getting the same error and behaviour on Flutter 1.2.1:

W/OkHttpClientTransport(25323): Failed closing connection
W/OkHttpClientTransport(25323): javax.net.ssl.SSLException: Write error: ssl=0x6f4ce20088: I/O error during system call, Broken pipe
W/OkHttpClientTransport(25323): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/OkHttpClientTransport(25323): 	at com.google.android.gms.org.conscrypt.NativeSsl.write(:com.google.android.gms@15090020@15.0.90 (040406-231259764):4)
W/OkHttpClientTransport(25323): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(:com.google.android.gms@15090020@15.0.90 (040406-231259764):6)
W/OkHttpClientTransport(25323): 	at okio.Okio$1.write(Okio.java:79)
W/OkHttpClientTransport(25323): 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
W/OkHttpClientTransport(25323): 	at okio.RealBufferedSink.close(RealBufferedSink.java:229)
W/OkHttpClientTransport(25323): 	at io.grpc.okhttp.internal.framed.Http2$Writer.close(Http2.java:569)
W/OkHttpClientTransport(25323): 	at io.grpc.okhttp.AsyncFrameWriter$14.run(AsyncFrameWriter.java:203)
W/OkHttpClientTransport(25323): 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
W/OkHttpClientTransport(25323): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/OkHttpClientTransport(25323): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

**Comment by larssn** [comment]
I think that error is harmless. The JS SDK also outputs errors like crazy when you lose the connection, but they're all handled internally, and only output to the console for good measure.

I've tried reproducing the behavior in this thread, but I cannot. My app doesn't suspend (whatever that means exactly), and the data is added to the local caching layer. Upon reestablished internet, the missing documents are uploaded to the server.

What people might be experiencing, is waiting for Futures to resolve while offline, which they will not do.

So if you have a document reference and update it like so: `await docRef.updateData({'hello': 'world'})` it will hang on that promise until the internet is reestablished. It is designed to work that way. You're not meant to wait for Futures when manipulating data.

**Comment by kroikie** [comment]
@alexbagirov

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/763. Any further collaboration will be done there.
