### ISSUE TITLE
Can Flutter print receipts ?

### ISSUE THREAD

**Issue by Phetz** [flutter/flutter#19135]

**Comment by miyoyo** [comment]
Since reciept printers need a USB/Bluetooth/Network driver , you'd need to use the native platform to connect and talk to them.

**Comment by Phetz** [comment]
@miyoyo  Thank you

**Comment by zoechi** [comment]
For more details see https://flutter.io/developing-packages/#plugin

**Comment by zoechi** [comment]
I'm closing this because I don't think there is anything on the roadmap for Flutter.

**Comment by andrey-ushakov** [comment]
If you are looking for printing receipts using a ESC POS thermal printer, you can use [this esc_pos_printer plugin](https://pub.dev/packages/esc_pos_printer)

**Comment by pjjy** [comment]
d
