### ISSUE TITLE
AVD runs an older version of the code even I completely remove the main.dart

### ISSUE THREAD

**Issue by nodesl** [flutter/flutter#19132]
Its seems like an caching issue or something. Everything was working we'll. Then I removed the code inside main.dart and started to write a new app from the first line. But when I run the code below, It doesnt show on the emulator. Instead of the new code it shows the previous version of the app. I tried restarting emulator. Stop and start the app once again. But nothing seems like working : / Need a help. Urgent!

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    Container(
      color: Colors.blueAccent,
      ),
  );
}
```

**Comment by zoechi** [comment]
Could you please check if you get similar behavior as flutter/flutter-intellij#2472?

**Comment by zoechi** [comment]
I believe this is just another case of #16604

**Comment by nodesl** [comment]
@zoechi thanks for having a look : ) i read all the issues that you have listed. yeah it seems like the same issue. so we don't have a fix still right ? coz i didn't found any fix in those topics. im new to github also. so still not friends with how this thing work. but i'll get use to it. don't forget to update me if you saw a fix somewhere. i'll also keep in touch

**Comment by mohith7548** [comment]
Do "flutter clean" in terminal and run app again. Its the build issue with flutter that has been making devs so sad.I think flutter team will fix it soon. The bug always buids the previous version of the app.

**Comment by zoechi** [comment]
There was a fix recently for release builds, but for debug builds there is still some work to do.

**Comment by mohith7548** [comment]
@zoechi which in which version it is fixed? I'm currently on beta channel.
