### ISSUE TITLE
Reversing an AnimationController moving forward but at zero doesn't generate a status listener callback

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1913]
I have an AnimationController per stateful widget.  The widgets call forward on their controller whenever the status is dismissed and on construction.  I have a timer that calls reverse on the controller randomly.

Eventually they all get stuck going forward but never completing:

```dart
[iPad Air 2] Runner: controller 772620419: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 1017552027: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 772620419: AnimationController(◀ 0.439)
[iPad Air 2] Runner: controller 1017552027: AnimationController(◀ 0.439)
[iPad Air 2] Runner: controller 770669481: AnimationController(◀ 0.660)
[iPad Air 2] Runner: controller 1017552027: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 1017552027: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 772620419: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 772620419: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(◀ 0.218)
[iPad Air 2] Runner: controller 770669481: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(◀ 0.650)
[iPad Air 2] Runner: controller 770669481: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(◀ 0.883)
[iPad Air 2] Runner: controller 770669481: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(◀ 0.018)
[iPad Air 2] Runner: controller 770669481: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
[iPad Air 2] Runner: controller 770669481: AnimationController(◀ 0.699)
[iPad Air 2] Runner: controller 770669481: AnimationController(⏮ 0.000; paused)
[iPad Air 2] Runner: controller 770669481: AnimationController(▶ 0.000)
```

**Comment by apwilson** [comment]
Code can be found [here](https://github.com/apwilson/lolwat/blob/master/lib/main.dart)

**Comment by eseidelGoogle** [comment]
Do you believe this to be iOS specific?  (per your title?)

**Comment by apwilson** [comment]
Actually I've reproduced on android just now, so not ios only.

**Comment by apwilson** [comment]
As discussed, I want to get all intermediate status callbacks not reentrantly - ie. use microtasks.

**Comment by Hixie** [comment]
I'm not sure I understand the issue here. Do we know the cause of the behaviour? Is this requesting more asserts to catch misuse of the API? Or is this a bug in the API?

**Comment by abarth** [comment]
Consider the following sequence of events.

1. An AnimationController is dismissed at 0.0.
2. The developer calls `forward()` on the controller.
3. The developer calls `reverse()` on the controller.
4. The animation ticks.

What's currently happening is that no status change notifications are being sent because we send status change notifications when the animation ticks and the status is the same as it was before (i.e., dismissed).

That causes trouble in this example because he's listening to status changes and calls forward when he gets a "dismissed" status.  Conceptually, he thinks that should cause all the animations that reach the dismissed state to start going forward but instead the sequence above can cause animations to get stuck in the dismissed state.

**Comment by abarth** [comment]
The proposed solution is to deliver all the intermediate status changes instead of coalescing them at animation ticks.

**Comment by Hixie** [comment]
Ah, I see. Thanks.

Another possibility is to have a dirty bit, and after coalescing all the changes, if no notification would be sent but the dirty bit is set, send a redundant one.

**Comment by abarth** [comment]
The trouble with a dirty bit is that if the animation never ticks again, we'll never come through and clean the dirty bit.

**Comment by Hixie** [comment]
Sure. I would assume that we would schedule a frame in that case.

**Comment by abarth** [comment]
We schedule a frame and then cancel it.  The cancel doesn't really do anything, so maybe we should leave the frame scheduled and just send the status callback then.
