### ISSUE TITLE
Update website page "Write Your First Flutter App" for latest dart/flutter version.

### ISSUE THREAD

**Issue by willu** [flutter/flutter#19133]
From URL: https://flutter.io/get-started/codelab/

The code on this page doesn't actually seem to work (well, the code in Step 1 at least).  I get a bunch of Dart analysis errors complaining that things are not functions.  By comparing with the sample code in the new project, I figured out that I needed to add a bunch of 'new' keywords and now it works.

**Comment by ram231** [comment]
I don't know why. What IDE or Editor did you use?
I use VSCode and Android Studio, both have Flutter and Dart Plugins.

**Comment by willu** [comment]
This is clearly a problem with the codelab, not my setup. The codelab is inconsistent; the inline code samples are different to the downloadable complete files. The complete files are correct. (The inconsistency is an issue even if you believe that both forms should work.)

**Comment by goderbauer** [comment]
@willu Cab you post the output of `flutter doctor -v`?

**Comment by willu** [comment]
I don't have access to that laptop at present, so I can't get exact version numbers right now.  Will try to check details at the weekend.  Some background might make things clearer:

O(months) ago I installed the flutter command lines tools (on a MacBook Air).  At that point flutter doctor had not complaints.
At the same time I installed Android Studio (prompted by flutter doctor), but I did NOT install the dart/flutter plugins at that point.
Last weekend I got some "hobby time" (unfortunately rare) and so went through the codelab.  It prompted me to install the plugins, which I did.  It also had me update the Android SDK.  I thought it also updated the flutter SDK, but I didn't do that myself and I might have been mistaken.  I did not run flutter doctor again myself.
I think there might have been a really old flutter SDK partially installed at one point, but I removed it and installed fresh O(months) ago.

I assume what may have happened is that at some point the Dart language changed so that `new` keywords were no longer required when constructing objects.  The codelab was partially updated (the inline examples were updated but the complete downloads were not.  e.g.
https://flutter.io/get-started/codelab/#step-1-create-the-starting-flutter-app
contains the text `return MaterialApp(` whereas the complete lib/main.dart linked at the end of section 2 ( https://gist.githubusercontent.com/Sfshaza/bb51e3b7df4ebbf3dfd02a4a38db2655/raw/57c25b976ec34d56591cb898a3df0b320e903b99/main.dart ) has the text `return new MaterialApp(` at the same point.

When I create a new project with Android Studio I get a working example.  It contains `new` keywords.  As I noted in the original report, when I copy and paste the codelab inline examples I get Dart analysis errors.  They say things like (and this is from memory because I don't have the laptop with me): "MaterialApp is not a function".  This is correct - it is a class.

If the language has changed as I surmise, it surprises me that syntax only a few months old is not given a shout-out on the codelab (e.g. "If you're using an older version of Dart then you might need `new` statements when constructing objects.").

**Comment by zoechi** [comment]
This sounds like issues related to the transition phase while migrating Flutter from Dart 1.x to Dart 2.x
There is still #18809 to get rid of `new` in clodelabs. 
Otherwise these issues should be solved. 
Please create a new issue with the output of `flutter doctor -v` if you encounter this again.
