### ISSUE TITLE
window.textScaleFactor set to 1.0 on hot restart

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#19145]
When using my iPhoneX and building a flutter app in debug mode, I noticed an odd thing. Text was slightly smaller on first load than after I did a hot restart. I can reproduce this in the simulator also.

I added the following code:
```
import 'dart:ui' show window;
void main() {
  print(window.textScaleFactor);
  // rest of main to start the app
}
```
This reported `0.8235294117647058` on first load, and `1.0` after a hot restart.

To confirm this, I went into my phone's accessibility settings, and set a larger than normal text size (iPhone, General settings, Accessibility, Vision section, Larger Text, and select a larger size.)

This reported `1.1176470588235294 ` on first load, and `1.0` after a hot restart.

During my investigation, I also noticed that the MediaQuery's `alwaysUse24HourFormat` changes too, between fresh load and hot restart.

> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel dev, v0.5.6, on Mac OS X 10.13.5 17F77, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
> [✓] Android Studio (version 3.1)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
> [✓] VS Code (version 1.24.1)
> [✓] Connected devices (2 available)
> 
> • No issues found!

**Comment by jogboms** [comment]
@zoechi I can also report this to be true as well.
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.108, on Mac OS X 10.13.3 17D47, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by jonahwilliams** [comment]
From a brief glance at the issue, the FlutterViewController sends a notification to the engine when user settings change and when the flutter view appears, however there is nothing sent during a hot restart. Thus the settings would get set to the Dart window default values. The fix is we need to expose or listen to a hot restart lifecycle somehow and send the information again

**Comment by dnfield** [comment]
So this is state (among other things) that we push down to the window at two points:

1. On startup.
2. When the setting is changed by the system.

When we hot-reload the app, we need to make sure these settings get pushed down again.

I'm pretty sure this would affect Android as well.

**Comment by dnfield** [comment]
Note that the fix for this was engine side - should show up in the framework before long, but will require an engine roll.
