### ISSUE TITLE
Cannot get FlutterFire to work with iOS

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19142]
I've tried so many things that its going to be hard to pin this one down, so apologies in advance.

I followed the instructions on Firebase Console (cannot link) and https://codelabs.developers.google.com/codelabs/flutter-firebase/#5

## using cocoapods 1.5.3
- installed credentials into ios/Runner/GoogleService-Info.plist
- did flutter run
got error `fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found`

## using cocoapods 1.4.0
- did flutter clean; flutter run

got error `fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found`

## using cocoapods 1.5.3
- found this https://stackoverflow.com/questions/50125534/firestore-is-failed-to-build-with-flutter-for-ios
- pasted this into my Podfile https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-objc
- flutter clean; flutter run

got error 

```
5.4.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.4.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
```

## using cocoapods 1.5.3
- pasted this into my Podfile because I have no idea if Flutter uses obj-c or swift out of the box https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-swift
- flutter clean; flutter run

got error

```
5.4.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.4.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
```

## user story
Guy knows barely enough es6 javascript to be dangerous and likes react. Decides to learn React-Native. starts to realize that third party libraries are horrible and looks into Flutter. Is excited, perhaps mistakenly so, that he doesn't have to learn anything about iOS/Android specific builds. Uses `npm install firebase` nearly daily for all kinds of projects. Goes to install Firebase into his shiny new Flutter project and the whole process falls flat on its face with very little guidance from Flutter team. Finds some whisperings about this being fixed but can't find any resolution.

Any help?

**Comment by lukepighetti** [comment]
## using flutter branch dev
- flutter clean; flutter run

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/lukepighetti/code/when-coin/when_coin/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found
    #import <firebase_core/FirebaseCorePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by lukepighetti** [comment]
OK. I'm going to try again from stage 1.

- `flutter channel dev`
- `create flutter project in VSC`
- `make first commit with a basic layout`
- open `Runner.xcodeproj`
- set team to ME!
- put bundle identifier `com.example.myproject` into firebase console
- give it a name in Firebase console
- do not give it an App Store id
- download `GoogleService-Info.plist`
- move it to `ios/Runner/`
- `cd ios`
- `pod --version` >> 1.5.3
- `pod init` >> no response

Podfile looks like this

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner

end
```

Add `pod 'Firebase/Core'` to Podfile

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'

end
```

- `pod install`

```
Lukes-iMac:ios lukepighetti$ pod install
Analyzing dependencies
Downloading dependencies
Installing Firebase (5.4.0)
Installing FirebaseAnalytics (5.0.1)
Installing FirebaseCore (5.0.5)
Installing FirebaseInstanceID (3.1.1)
Installing GoogleToolboxForMac (2.1.4)
Installing nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

- added initialization code
```
#include "AppDelegate.h"
@import Firebase;
#include "GeneratedPluginRegistrant.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      [FIRApp configure];
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end
```

- `cd ..; flutter run`

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

- `pod install` >> No podfile found

- `cd ios; pod install`

```
Analyzing dependencies
Downloading dependencies
Using Firebase (5.4.0)
Using FirebaseAnalytics (5.0.1)
Using FirebaseCore (5.0.5)
Using FirebaseInstanceID (3.1.1)
Using GoogleToolboxForMac (2.1.4)
Using nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

OK. looks like this isn't working, will try another way

**Comment by lukepighetti** [comment]
Does anyone have a boilerplate project for FlutterFire that works with iOS and Android? I keep trying different ways and I solve some issues and get others such as 

```
5.4.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
5.4.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
```

I'm totally at a loss here.

**Comment by lukepighetti** [comment]
OK this appears to be WAY easier than the documentation would have you believe. 

- new flutter project
- new iOS app in Firebase Console
- put `GoogleService-Info.plist` into `Runner` directory **in XCode!!!!!!!!!!!!!!**
- make `pubspec.yaml` look like this

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.2.4"
  firebase_database: "^1.0.1"
```
- `flutter packages get`
- `flutter run`

and it appears to work just fine


Also, there appears to be an error that most people ignore and continue to develop.

```
5.4.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.4.0 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
```

**Comment by lukepighetti** [comment]
This will get rid of that error message on Objective-C project

`ios/Runner/AppDelegate.m`
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
@import Firebase; // ADD THIS

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure]; // ADD THIS
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end
```

**Comment by lukepighetti** [comment]
I am updating my recommendation to not use Xcode to place `GoogleService-Info.plist` into `ios/Runner` because it appears to create a link instead of actually copying the file. If you delete the file (like move it from Downloads to Trash) it will break things.

**Comment by yousoff92** [comment]
Hi, I did follow all the troubleshoots above but I still get this error. Tested on iOS Simulator.

```
    /Users/yousoffeffendy/Documents/personal/workspace/flutter-workspace/flutter-firebase-crud-app/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found
    #import <firebase_core/FirebaseCorePlugin.h>
```

Can assist ? 

```
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-MY)
    • Flutter version 0.8.2 at /Users/yousoffeffendy/Documents/software/flutter
    • Framework revision 5ab9e70727 (6 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/yousoffeffendy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • 569D3D1B-E828-4A98-AE81-3B5950B6AAE7 • ios • iOS 11.4 (simulator)
```

**Comment by yousoff92** [comment]
oh ok.. I follow this url above, replace podfile and everything works fine https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-swift

**Comment by sudharsanprasadh** [comment]
> Hi, I did follow all the troubleshoots above but I still get this error. Tested on iOS Simulator.
> 
> ```
>     /Users/yousoffeffendy/Documents/personal/workspace/flutter-workspace/flutter-firebase-crud-app/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_core/FirebaseCorePlugin.h' file not found
>     #import <firebase_core/FirebaseCorePlugin.h>
> ```
> Can assist ?
> 
> ```
> [✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-MY)
>     • Flutter version 0.8.2 at /Users/yousoffeffendy/Documents/software/flutter
>     • Framework revision 5ab9e70727 (6 days ago), 2018-09-07 12:33:05 -0700
>     • Engine revision 58a1894a1c
>     • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
> 
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
>     • Android SDK at /Users/yousoffeffendy/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.4.1, Build version 9F2000
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] Connected devices (1 available)
>     • iPhone X • 569D3D1B-E828-4A98-AE81-3B5950B6AAE7 • ios • iOS 11.4 (simulator)
> ```

Did you get it fixed? if so please share, I'm also stuck

**Comment by zoechi** [comment]
@sudharsanprasadh your Flutter version is quite outdated (from September)

**Comment by pinsoneatra** [comment]
> OK. I'm going to try again from stage 1.
> 
> * `flutter channel dev`
> * `create flutter project in VSC`
> * `make first commit with a basic layout`
> * open `Runner.xcodeproj`
> * set team to ME!
> * put bundle identifier `com.example.myproject` into firebase console
> * give it a name in Firebase console
> * do not give it an App Store id
> * download `GoogleService-Info.plist`
> * move it to `ios/Runner/`
> * `cd ios`
> * `pod --version` >> 1.5.3
> * `pod init` >> no response
> 
> Podfile looks like this
> 
> ```
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'Runner' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for Runner
> 
> end
> ```
> Add `pod 'Firebase/Core'` to Podfile
> 
> ```
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> target 'Runner' do
>   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
>   # use_frameworks!
> 
>   # Pods for Runner
>   pod 'Firebase/Core'
> 
> end
> ```
> * `pod install`
> 
> ```
> Lukes-iMac:ios lukepighetti$ pod install
> Analyzing dependencies
> Downloading dependencies
> Installing Firebase (5.4.0)
> Installing FirebaseAnalytics (5.0.1)
> Installing FirebaseCore (5.0.5)
> Installing FirebaseInstanceID (3.1.1)
> Installing GoogleToolboxForMac (2.1.4)
> Installing nanopb (0.3.8)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.
> 
> [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
> ```
> * added initialization code
> 
> ```
> #include "AppDelegate.h"
> @import Firebase;
> #include "GeneratedPluginRegistrant.h"
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application
>     didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>       [FIRApp configure];
>   [GeneratedPluginRegistrant registerWithRegistry:self];
>   // Override point for customization after application launch.
>   return [super application:application didFinishLaunchingWithOptions:launchOptions];
> }
> 
> @end
> ```
> * `cd ..; flutter run`
> 
> ```
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> Xcode's output:
> ↳
>     === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
>     diff: /Podfile.lock: No such file or directory
>     diff: /Manifest.lock: No such file or directory
>     error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
> Could not build the application for the simulator.
> Error launching application on iPhone X.
> ```
> * `pod install` >> No podfile found
> * `cd ios; pod install`
> 
> ```
> Analyzing dependencies
> Downloading dependencies
> Using Firebase (5.4.0)
> Using FirebaseAnalytics (5.0.1)
> Using FirebaseCore (5.0.5)
> Using FirebaseInstanceID (3.1.1)
> Using GoogleToolboxForMac (2.1.4)
> Using nanopb (0.3.8)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There is 1 dependency from the Podfile and 6 total pods installed.
> 
> [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
> ```
> OK. looks like this isn't working, will try another way

thanks to you. i seem easier than expect.

**Comment by dotdotcommadot** [comment]
I still got the `Could not locate configuration file: 'GoogleService-Info.plist'.` error.
Eventually I found the way to fix it:
- Download the `GoogleService-Info.plist` file from Firebase
- Place it in the `ios/Runner` directory of your flutter project
- open XCode with `open ios/Runner.xcworkspace`
- In XCode, drag the file `GoogleService-Info.plist` from your finder, to the yellow `Runner` folder underneath the blue `Runner`Project`, (in the project navigator on the left side of the screen). This the main step that was missing (at least, for me).

**Comment by NaagAlgates** [comment]
@dotdotcommadot  

> I still got the `Could not locate configuration file: 'GoogleService-Info.plist'.` error.
> Eventually I found the way to fix it:
> 
>     * Download the `GoogleService-Info.plist` file from Firebase
> 
>     * Place it in the `ios/Runner` directory of your flutter project
> 
>     * open XCode with `open ios/Runner.xcworkspace`
> 
>     * In XCode, drag the file `GoogleService-Info.plist` from your finder, to the yellow `Runner` folder underneath the blue `Runner`Project`, (in the project navigator on the left side of the screen). This the main step that was missing (at least, for me).

This helped me.

**Comment by zeh** [comment]
> * In XCode, drag the file `GoogleService-Info.plist` from your finder, to the yellow `Runner` folder underneath the blue `Runner`Project`, (in the project navigator on the left side of the screen). This the main step that was missing (at least, for me).

After a lot of trial and error, this is what finally made it work for me. No idea why this was never mentioned in the documentation.

**Comment by burtonmiller** [comment]
This worked for me as well -- and should be in the instructions.

**Comment by lexdabest** [comment]
I am developing for Android and IOS. After many trial and error, I discovered my setting in the pubspec.yaml file for android would have to be different for that of ios
For Android:
```
firebase_core:^0.2.0
firebase_auth: ^0.7.0
```
while for ios:
```
firebase_core:^0.4.0
firebase_auth: ^0.11.1+8
```

**Comment by workerbee22** [comment]
> oh ok.. I follow this url above, replace podfile and everything works fine https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-swift

Broken link. Anyone else got this to work with a Swift AppDeligate ?

**Comment by workerbee22** [comment]
Opening new issue, this is not fixed.

**Comment by bhargavcode** [comment]
In My flutter app 
Im getting 'Could not locate configuration file: 'GoogleService-Info.plist'.' error

Running Xcode build...
Xcode build done.                                           21.9s
	path: satisfied (Path is satisfied), interface: en0, expensive
6.18.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   Runner                              0x00000001017897aa +[FIRApp configure] + 138
	4   Runner                              0x00000001015c8f3d -[AppDelegate application:didFinishLaunchingWithOptions:] + 93
	5   UIKitCore                           0x00007fff48089ad8 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	6   UIKitCore                           0x00007fff4808b460 -[UIApplication _callInitializationDel<…>
This is taking longer than expected...
