### ISSUE TITLE
Flutter beta 0.5.1 does not upgrade to Flutter Release Preview 1 on macOS 10.13.5

### ISSUE THREAD

**Issue by wbeebe** [flutter/flutter#19140]
The Medium article at https://medium.com/flutter-io/flutter-release-preview-1-943a9b6ee65a?linkId=53249457, "Announcing Flutter Release Preview 1", says:

How do you upgrade to Flutter Release Preview 1? If you’re on the beta channel already, it just takes one command:

$ flutter upgrade

This does not work.

**Comment by MaikuB** [comment]
My understanding is that is the release preview version. It came out around a day before the article did and if you check the download links in the installation guide, they point to that version.

**Comment by zoechi** [comment]
@MaikuB is right, the current beta is the Release Preview 1.

**Comment by Chen-Sir** [comment]
@MaikuB mai  you mean beta 0.5.1  is the release preview version?

**Comment by MaikuB** [comment]
Yes that was confirmed by @zoechi as well. in fact if you look at the install guides for downloading the Flutter SDK zip file then you'll see it's 0.5.1

**Comment by allandaleho** [comment]
Hey sorry for follow up question, is there no upgrade after beta 0.5.1? It seems the last update was 3 months ago? Or should I move to a different branch?

Hope someone can clarify thanks!

**Comment by zoechi** [comment]
@allandaleho `0.5.1` seems still to be the latest `beta` channel version. You could switch to `dev` channel until a new `beta` is released. I don't know what blocks a new `beta` release.
