### ISSUE TITLE
Flutter Error 

### ISSUE THREAD

**Issue by keremcanozcan35** [flutter/flutter#19158]
I worked a project on yesterday and today when I try to open it, I am getting this error : 
writeFrom failed, path = '.\pubspec.lock' (OS Error: The operation completed successfully.
, errno = 0)
pub upgrade failed (66)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
Please try deleting `pubspec.lock`.
Does the user account you are using have write permissions in this directory?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by keremcanozcan35** [comment]
@zoechi 
Same error, nothing changes.

**Comment by zoechi** [comment]
Does the `pubspec.lock` file exist?
Can you open it in the IDE or some editor?
Have you tried restarting your machine?
