### ISSUE TITLE
Flutter share plugin crashes on iPad [iOS 11.4]

### ISSUE THREAD

**Issue by ozc** [flutter/flutter#19152]
Share plugin ( https://pub.dartlang.org/packages/share ) crashes the app on iPad running iOS 11.4. I've sent the app binary to be published but got rejected by Apple, as tapping share button crashed the app. Then I've tested my app on iPhone and iPad simulators, and indeed it crashes on iPad. Just on iPad, no problem on iPhone.

Crashlogs from Apple test:

[crashlog-03A032AA-FDA3-4F68-B436-00F89D7A5398.txt](https://github.com/flutter/flutter/files/2174071/crashlog-03A032AA-FDA3-4F68-B436-00F89D7A5398.txt)
[crashlog-BAD52D99-C3E8-4F13-9852-EEB27490A64A.txt](https://github.com/flutter/flutter/files/2174072/crashlog-BAD52D99-C3E8-4F13-9852-EEB27490A64A.txt)
[crashlog-618F7EAF-8AC9-44A2-B7AB-9F090D38C728.txt](https://github.com/flutter/flutter/files/2174073/crashlog-618F7EAF-8AC9-44A2-B7AB-9F090D38C728.txt)

```
These two are latest outputs from the simulator running iPad - iOS 11.4

*** First throw call stack:
(
	0   CoreFoundation                      0x000000010dadc1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010cf4a031 objc_exception_throw + 48
	2   UIKit                               0x000000010ec3d043 -[UIPopoverPresentationController presentationTransitionWillBegin]<…>
Lost connection to device.


*** First throw call stack:
(
	0   CoreFoundation                      0x00000001111c91e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000011085e031 objc_exception_throw + 48
	2   UIKit                               0x000000011232a043 -[UIPopoverPresentationController presentationTransitionWillBegin]<…>
```

Output from, flutter doctor -v

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-TR)
    • Flutter version 0.5.1 at /Users/redacted/development/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices (1 available)
    • iPad (5th generation) • 17A34F9E-530C-433C-B381-FB7C4AC17FCE • ios • iOS 11.4 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
`dev` channel might be worth a try. `beta` wasn't updated since 6 weeks already.

**Comment by ozc** [comment]
Trying to change to dev channel, bu "flutter channel dev" command is stuck on "Downloading darwin-x64 tools...". -v parameter does not yield much more info either.

**Comment by zoechi** [comment]
This path looks a bit weird

```
 Flutter version 0.5.1 at /Users//development/flutter
```
any idea where these double-slash might come from?

**Comment by ozc** [comment]
That's because I've removed the username with < username > . That's not related to the error anyway. App runs perfectly on iphone ios 11.4, but  crashes on ipad ios 11.4.

**Comment by ozc** [comment]
Changed to dev and still crashes when clicked on the share button, on ipad. And still no problem on iphone.

Even tried running with software rendering enabled.
flutter run --enable-software-rendering

I can't get a crash dump as stated on 127.0.0.1:8100 either. 
Request a crash dump with:
'curl 127.0.0.1:8100/_getCrashDump > dump.json'


$ flutter doctor -v
[✓] Flutter (Channel dev, v0.5.6, on Mac OS X 10.13.3 17D102, locale en-TR)
    • Flutter version 0.5.6 at /Users/< username >/Development/flutter
    • Framework revision 472bbccf75 (2 weeks ago), 2018-06-26 17:01:46 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/< username >/Library/Android/sdk/
    • Android NDK at /Users/< username >/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/< username >/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2 RC)
    • IntelliJ at /Users/< username >/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.14.0

[✓] Connected devices (1 available)
    • iPad Pro (12.9-inch) (2nd generation) • E2074311-9401-4F82-91B0-A18E596921C3 • ios • iOS 11.4 (simulator)

! Doctor found issues in 1 category.

**Comment by ozc** [comment]
I think I've found the reason. On non-phone ios devices creating a share popup is a bit different as it seems. I don't know much about ios development and obj-c, but modified the plugin code from stackoverflow to fit the plugin. It doesn't crash anymore.


https://stackoverflow.com/questions/31506081/sharing-button-works-perfectly-on-iphone-but-crash-on-ipad

https://stackoverflow.com/questions/25644054/uiactivityviewcontroller-crashing-on-ios-8-ipads




SharePlugin.m
```
+ (void)share:(id)sharedItems withController:(UIViewController *)controller {
  UIActivityViewController *activityViewController =
      [[UIActivityViewController alloc] initWithActivityItems:@[ sharedItems ]
                                        applicationActivities:nil];

  // Original code
  //[controller presentViewController:activityViewController animated:YES completion:nil];

    //if iPhone
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
        [controller presentViewController:activityViewController animated:YES completion:nil];
    }
    //if iPad
    else {
        // Change Rect to position Popover
        UIPopoverController *popup = [[UIPopoverController alloc] initWithContentViewController:activityViewController];
        [popup presentPopoverFromRect:CGRectMake(controller.view.frame.size.width/2, controller.view.frame.size.height/4, 0, 0)inView:controller.view permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
    }
}

```

**Comment by iapicca** [comment]
Hi all,
given this [issue](https://github.com/flutter/flutter/issues/44293) 
the error might be related to the ios version;
does @ozc [solution](https://github.com/flutter/flutter/issues/19152#issuecomment-404936259) works for you?
Thank you

**Comment by AirborneEagle** [comment]
For those looking for a workaround,
here is mine using [positioned_tap_detector](https://pub.dev/packages/positioned_tap_detector)
```
PositionedTapDetector(
      behavior: HitTestBehavior.translucent,
      onTap: (p) {
        String message =
            "Hey! Have you seen this? A cool new App!";
        Share.share(
          message,
          sharePositionOrigin:
          Rect.fromCenter(center: p.global, width: 5, height: 5),
        );
      },
      child: Padding(
        padding: Theme.of(context).buttonTheme.padding,
        child: Icon(Icons.share),
      ),
    )
```

since the `sharePositionOrigin` param does nothing on other devices, there is no harm in keeping the widget as is, without checking if the device is an iPad

**Comment by AirborneEagle** [comment]
Wait, why did this close?
this issue is the same as #47220. I believe.

**Comment by iapicca** [comment]
Hi @AirborneEagle 
the issue you linked it appears to be more `up_to_date` than the current one,
please follow up there
Thank you

**Comment by computerzman** [comment]
I face the same problem now ....

**Comment by AirborneEagle** [comment]
@computerzman 
in #47220 @angel1st has a very simple work around. 
But also, see my solution above.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by computerzman** [comment]
> @computerzman
> in #47220 @angel1st has a very simple work around.
> But also, see my solution above.

Thanks, this is working for me 
final Size size = MediaQuery.of(context).size;
......
onPressed: () => Share.share(
     message,
     sharePositionOrigin: Rect.fromLTWH(0, 0, size.width, size.height / 2),
),

**Comment by angel1st** [comment]
@iapicca - I see no reason to flood GitHub with issues since it is obvious [where the problem lies](https://github.com/flutter/flutter/issues/47220#issuecomment-608453383). Simply update [the example](https://github.com/flutter/plugins/blob/master/packages/share/example/lib/main.dart), that's all!

**Comment by campioncino** [comment]
> Thanks, this is working for me
final Size size = MediaQuery.of(context).size;
......
onPressed: () => Share.share(
message,
sharePositionOrigin: Rect.fromLTWH(0, 0, size.width, size.height / 2),
),


is this solution working on emulator? (emulated ipad)
I don't see anything

My popup is somewhere, maybe...

**Comment by angel1st** [comment]
@campioncino - yes, the solution works on emulator iPad.
