### ISSUE TITLE
META - Proposal of an New Feature Announcement Issue

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#19162]
Hi,

due to the fact that the development of Flutter is very fast it's hard to keep track of every new feature that gets added to it. Following all commits is not really its to finely granulated.

So my proposal would be that we create one **New Feature Announcement Issue** that anyone who is interested can follow in which the Flutter team just post "one liners" about newly added merged features. 

What do you think?

Thomas

**Comment by jonahwilliams** [comment]
If commits are too granular, then what granularity is desirable?  Since we squash our commits, a single commit could represent an entire feature.  Though I can see that there are also a lot of tooling/testing/rolling commits that aren't really applicable to a user.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/commits/dev seems to have ~10 entries per day, that doesn't seem to much.

**Comment by escamoteur** [comment]
@jonahwilliams That is exactly the point I want to know if there are new features devs can use. Especially for the onces active in the community this would be helpful to help others

**Comment by Hixie** [comment]
Would it make sense just to add these to the [changelog](https://github.com/flutter/flutter/wiki/Changelog)? we're not very good about doing so right now but we would not be any better at commenting on an issue. :-)

**Comment by escamoteur** [comment]
@Hixie My point was to have something more informal that is easy for you to maintain bewteen versions. Just a one liner about a new feature or removed bigger bug nothing fancy.
So anyone who wants to stay really up to date could subscribe to that issue.

**Comment by Hixie** [comment]
Editing the changelog isn't really any harder than commenting on an issue, I think. I agree that it's weird that you can't subscribe to the changelog, though.

**Comment by Hixie** [comment]
@escamoteur Assuming that we would be as effective at updating a bug as we are about updating the changelog, would you adjust your request at all?

**Comment by escamoteur** [comment]
More important than bugs is to get to know which new features were added :-) But It s not that important. If it would be possible to watch the changelog that would be enough.
