### ISSUE TITLE
How should addTime be used from a test?

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#19175]
When a testWidgets test times out, the following message is printed:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TimeoutException was thrown running a test:
TimeoutException after 0:00:02.100000: The test exceeded the timeout. It may have hung.
Consider using "addTime" to increase the timeout before expensive operations.
```

It's unclear how "addTime" should be called from a test case. Maybe:

```dart
    final TestWidgetsFlutterBinding binding = tester.binding;
    if (binding is AutomatedTestWidgetsFlutterBinding)
      binding.addTime(const Duration(seconds: 30));
```

Seems complicated. The expected way should be documented.

It is also surprising to me that setting the `timeout` property on `testWidgets` alone doesn't increase the actual test timeout and I have to do the `addTime` hack in addition to setting the `timeout` property. This probably also needs a documentation explanation how the two relate to each other. 

/cc @Hixie

**Comment by goderbauer** [comment]
Suggested solution: 

* add the `addTime` method to `TestWidgetsFlutterBinding ` to make usage easier (it will not do anything on the Live Test Binding.
* Add Documentation to the `timeout` property of `testWidgets` explaining its relationship to addTime.
* Improve the timeout message to include more information of how to use `addTime` and how it relates to other test-related timeouts.

**Comment by truongsinh** [comment]
please take a look at #25202, the sample code now is
```dart
    testWidgets('MyWidget', (WidgetTester tester) async {
      tester.addTime(const Duration(seconds: 3));
      await tester.pumpWidget(new MyWidget());
      await tester.tap(find.text('Save'));
      expect(find.text('Success'), findsOneWidget);
    });
```

**Comment by jadolg** [comment]
Can't find any **addTime** method on **WidgetTester**

**Comment by pedrohenriquerls** [comment]
I don't know if this topic still relevant but, I found the doc about the `addTime` here https://docs.flutter.io/flutter/flutter_test/AutomatedTestWidgetsFlutterBinding/addTime.html
But I solve the problem by doing this: 
```dart
final binding = tester.binding as AutomatedTestWidgetsFlutterBinding;
binding.addTime(Duration(seconds: 3));
```

**Comment by truongsinh** [comment]
@jadolg you can't find it because the PR has not been merged, please re-read my comment with care

> please take a look at #25202, the sample code now is
