### ISSUE TITLE
Document and use --build-shared-library in release

### ISSUE THREAD

**Issue by xster** [flutter/flutter#19185]
According to @chinmaygarde: compiling Android AOT snapshot to an .so 
"will probably get faster as well since we dont have to ferry the blob out of compressed storage" at the inconvenience of having to have the NDK available on the machine. It may be a hassle for development but totally makes sense for production if developers can squeeze any amount of launch time performance out of Flutter apps. 

We should:

- [ ] Document this flag in https://flutter.io/android-release/
- [ ] Document this flag in https://flutter.io/fastlane-cd/
- [ ] Have a warning message when users `flutter build apk --release` without an NDK saying 'Your app may launch x% faster if the Android NDK was available during the release APK build'
- [ ] Use it in our own gallery CI/CD on Travis

cc @cbracken

**Comment by dnfield** [comment]
@matthew-carroll - might be worth testing if this help the start up time at all for Add2App

**Comment by jonahwilliams** [comment]
We currently use shard-library for Android now. This does not require the NDK, so there is nothing actionable left on the ticket.
