### ISSUE TITLE
The flutter build command should have a --fail-on-warnings option.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19184]
When there are analysis options, the build command should fail on analysis warnings if the user has requested that it do so, but there is no option for that, so we should add one.

**Comment by zanderso** [comment]
Does the `frontend_server` have a flag like `-Werror` ? @jonahwilliams @aam

**Comment by jonahwilliams** [comment]
We do exit on complication errors. It sounds like this is asking for an exit on lints or analyzer warnings, which are a superset of compilation errors. We do not want to be in the business of running another copy of the analyzer in process - I think features like this are better left to the IDE
