### ISSUE TITLE
Video Recording on flutter

### ISSUE THREAD

**Issue by Amaranadhreddy** [flutter/flutter#19199]
Shall you provide the video recording example on flutter?

**Comment by zoechi** [comment]
https://github.com/flutter/plugins/blob/master/packages/camera/example/lib/main.dart

I'm going to close the issue. If you have further questions you can still add comments 
or create a new issue.

**Comment by Amaranadhreddy** [comment]
Thanks @zoechi In that dart class file where is the find "path_provider.dart" and "video_player.dart" classes?

**Comment by zoechi** [comment]
You either didn't run `flutter packages get` after you changed dependencies or you might need to restart your IDE (if this helps you might need to update to a newer Flutter version - consider using `flutter channel dev` to switch to `dev` channel until a new `beta` version is released.
