### ISSUE TITLE
How to manage Authentication flow, a.k.a SwitchNavigator?

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#19194]
React has support for sensible and easy to use authentication flows, using [SwitchNavigator](https://reactnavigation.org/docs/en/auth-flow.html).

Here is a typical situation:

- The user opens the app, and is presented by a landing page, (like a spinner).
- The app loads some authentication state from persistent storage (like Keychain).
- When the state has loaded, the user is presented with either authentication screens or the main app, depending on whether valid authentication state was loaded.
- When the user signs out, we clear the authentication state and send them back to authentication screens.

In flutter, we only have simple navigation.

If we try to create a landing page + auth page + home page in flutter, the user can accidentally navigate back to the landing page, which results in a wierd UX.

This is solvable, if we could somehow restrict the user from being able to go back to the landing page, i guess.

**Comment by zoechi** [comment]
You can use one of the `replaceXxx` methods of `Navigator` to have the previous route replaced by the new one, then there is no way of navigating back to it.

**Comment by devxpy** [comment]
Thanks, I will try it out and get back to you.

**Comment by devxpy** [comment]
Works flawlessly, thanks!

Here is a sample code.
Can we add this use case to the documentation, it would be quite useful for newcomers.

```
import 'dart:async';
import 'package:flutter/material.dart';

check_if_authenticated() async {
  await Future.delayed(Duration(seconds: 5));  // could be a long running task, like a fetch from keychain
  return true;
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyApp,
      initialRoute: '/',
      routes: {
        '/': (context) => LandingPage(),
        '/login': (context) => LoginPage(),
        '/home': (context) => HomePage(),
      },
    );
  }
}

class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    check_if_authenticated().then((success) {
      if (success) {
        Navigator.pushReplacementNamed(context, '/home');
      } else {
        Navigator.pushReplacementNamed(context, '/login');
      }
    });

    return Center(
      child: CircularProgressIndicator(),
    );
  }
}

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('login'),
        ),
        body: Center(
          child: Text('Login page content'),
        ));
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('home'),
        ),
        body: Center(
          child: Text('home page content'),
        ));
  }
}
```

**Comment by zoechi** [comment]
I'd suggest checking authentication status in `initState()`.
`build()` can be called more than once.

**Comment by zoechi** [comment]
`didChangeDependencies()` it is then, there xou have access to `context`

**Comment by devxpy** [comment]
What if we just do this?

```dart

class LandingPage extends StatefulWidget {
  @override
  _LandingPageState createState() => _LandingPageState();
}

class _LandingPageState extends State<LandingPage> {
  var authSuccess;

  _LandingPageState() {
    checkIfAuthenticated().then((success) {
      setState(() {
        authSuccess = success;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    if (authSuccess != null) {
      if (authSuccess) {
        Navigator.pushReplacementNamed(context, '/home');
      } else {
        Navigator.pushReplacementNamed(context, '/login');
      }
    }

    return Center(
      child: CircularProgressIndicator(),
    );
  }
}

```

**Comment by zoechi** [comment]
Should work. Not sure which way is better.

**Comment by devxpy** [comment]
So that crashed xD

```console
I/flutter (27933): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (27933): The following assertion was thrown building LandingPage(dirty, state: _LandingPageState#b30ea):
I/flutter (27933): setState() or markNeedsBuild() called during build.
I/flutter (27933): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (27933): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter (27933): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (27933): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (27933): Otherwise, the framework might not visit this widget during this build phase.
I/flutter (27933): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (27933):   Overlay-[LabeledGlobalKey<OverlayState>#ee20e](state: OverlayState#1797a(entries:
I/flutter (27933):   [OverlayEntry#e40cf(opaque: false; maintainState: false), OverlayEntry#6e04e(opaque: false;
I/flutter (27933):   maintainState: true), OverlayEntry#08db2(opaque: false; maintainState: false),
I/flutter (27933):   OverlayEntry#40dfa(opaque: false; maintainState: true)]))
I/flutter (27933): The widget which was currently being built when the offending call was made was:
I/flutter (27933):   LandingPage(dirty, state: _LandingPageState#b30ea)

```
I tried doing it using initState, but that fails with same error.

```dart
_LandingPageState() {
    checkIfAuthenticated().then((success) {
      setState(() {
        authSuccess = success;
      });
    });
  }
```
to 
```
@override
  initState() {
    super.initState();
    checkIfAuthenticated().then((success) {
      setState(() {
        authSuccess = success;
      });
    });
  }
```

**Comment by devxpy** [comment]
I even tried a `FutureBuilder`, and it still returns with the same error.
```dart
class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: checkIfAuthenticated(),
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            print(snapshot.data);
            if (snapshot.data) {
              Navigator.pushNamed(context, '/home');
            } else {
              Navigator.pushNamed(context, '/login');
            }
          }
          return Center(
            child: CircularProgressIndicator(),
          );
        });
}
```

**Comment by zoechi** [comment]
dup of #16218

**Comment by devxpy** [comment]
We can access the the `context` from `initState()`, I feel stupid now..

```
class LandingScreen extends StatefulWidget {
  @override
  LandingScreenState createState() {
    return new LandingScreenState();
  }
}

class LandingScreenState extends State<LandingScreen> {
  @override
  void initState() {
    super.initState();
    checkIfAuthenticated().then((success) {
      if (success) {
        Navigator.pushReplacementNamed(context, '/browse');
      } else {
        Navigator.pushReplacementNamed(context, '/login');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Verifying credentials'),
      ),
      body: LoadingScreen(),
    );
  }
}

```

**Comment by zoechi** [comment]
@devxpy not really. 
This only works in your case because `.then(...)` is executed delayed and then the `context` getter from the `StatefulWidget` class is already set.

**Comment by devxpy** [comment]
### setState()

> This only works in your case because .then(...) is executed delayed and then the context getter from the StatefulWidget class is already set.

`checkIfAuthenticated()` is placed in the `State` class, not the `StatefulWidget` class.

The [docs](https://docs.flutter.io/flutter/widgets/State/context.html) on `State` class say - 

> The framework associates State objects with a BuildContext after creating them with StatefulWidget.createState and before calling initState. 

And sure enough, when I print out the `context` in `initState`, it is definitely there.

**However, If I remove the delay and immediately call `pushReplacementNamed()`, it does fail.**
(just like in  [this](https://github.com/flutter/flutter/issues/19194#issuecomment-403975321) comment)

### didChangeDependencies()

Like you suggested earlier, I did try to use `didChangeDependencies()`, but that fails with a similar eror.

### Another approach

I stumbled upon another approach that avoids the life-cycle  of the widget all-together. 
It does use global variables though.

Here is what it looks like -

```dart
void main() async {
  _isAuthenticated = await checkIfAuthenticated();
  print('app loaded!');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'secure pdf viewer',
      initialRoute: '/',
      onGenerateRoute: (RouteSettings settings) {
        switch (settings.name) {
          case '/':
            return MaterialPageRoute(builder: (_) {
              return _isAuthenticated ? BrowseScreen() : LoginScreen();
            });
          case '/login':
            return MaterialPageRoute(builder: (_) => LoginScreen());
          case '/browse':
            return MaterialPageRoute(builder: (_) => BrowseScreen());
        }
      },
    );
  }
}
```

It also,
- Avoids creating a new widget just for waiting, which reduces app launch time.
- Does the "checking" while the splash screen is active which IMO, results in a better UX.

It does however, make the '/' route potentially unusable (which is an acceptable trade-off)

**Comment by darrencole** [comment]
Thanks @devxpy ! Your final approach works great. I added a parameter to the MyApp class to avoid using the global variable.

**Comment by myhendry** [comment]
Thanks @devxpy. it works. 

I would like to separate the login page into 2 pages - one which will display 3 buttons (facebook, google and email login), the other page can be navigated from when pressing email login button. This page will show the signup or login form.

Using the final approach breaks in such instance. Anyone with suggestion to handle this? Thanks

**Comment by darrencole** [comment]
@myhendry how does it break? Sharing your code may help others help you.

**Comment by myhendry** [comment]
@darrencole 

Hi. My code is as follow. AuthPage is the page which will contain the 3 buttons for different types of login methods (google, facebook and email). EmailPage is the page which contains the form for email login and signup. Below setup allows me to navigate between the AuthPage and the EmailPage. However, when i log in from the EmailPage, the isAuthenticated state toggles to true but the EmailPage remains there. I can only see my HomePage after i pop off the EmailPage when i click on 'Go back' button

If it is just the EmailPage without any AuthPage, then @devxpy works wonderfully. If adds in another EmailPage, then it doesn't work. Any advise? Tq

**In my main.dart file**
  @override
  Widget build(BuildContext context) {
    print(_isAuthenticated);
    return ScopedModel<MainModel>(
        model: _model,
        child: MaterialApp(
            theme:
                ThemeData(primaryColor: Colors.lime, buttonColor: Colors.teal),
            title: 'App',
            initialRoute: '/',
            onGenerateRoute: (RouteSettings settings) {
              switch (settings.name) {
                case '/':
                  return MaterialPageRoute(builder: (_) {
                    return _isAuthenticated ? HomePage() : AuthPage();
                  });
                case '/auth':
                  return MaterialPageRoute(builder: (_) => AuthPage());
                case '/email':
                  return MaterialPageRoute(builder: (_) => EmailPage());
                case '/home':
                  return MaterialPageRoute(builder: (_) => HomePage());
                case '/list':
                  return MaterialPageRoute(builder: (_) => ListPage());
                case '/create':
                  return MaterialPageRoute(builder: (_) => CreatePage());
                case '/products':
                  return MaterialPageRoute(builder: (_) => ProductsPage());
              }
            }));
  }

**Inside my auth.dart file**
              RaisedButton(
                child: Text('Email'),
                onPressed: () {
                  Navigator.pushNamed(context, '/email');
                },
              )

**Inside my email.dart file**
                    FlatButton(
                      child: Text('Go back'),
                      onPressed: () {
                        Navigator.pop(context);
                      },
                    )

**Comment by darrencole** [comment]
@myhendry So I see what you're saying. I believe I can help.

Simple answer, in your EmailPage, after the user logs in successfully, you want to use Navigator.pushNamed() to route the user to your HomePage. If you don't want them to use the back arrow to return to the EmailPage, I suggest you use Navigator.pushReplacementNamed() instead.

`//on successful login`
`Navigator.pushReplacementNamed(context,  '/home');`

**Comment by myhendry** [comment]
Thanks @darrencole . I give it a try. Tq

**Comment by myhendry** [comment]
it works. seems ok from my testing

below is my codes for those who need reference

https://github.com/myhendry/flutter

look for my commits named 'Dual Page Auth' to refer to the changes i made to the original source code (as suggested by @darrencole) to have it working. Thanks

**Comment by vemarav** [comment]
Authenticaton flow in flutter - [Medium](https://engineering.classpro.in/building-authentication-flow-with-flutter-29b6924da8fd)
github repo - [vemarav/auth_flow](https://github.com/vemarav/auth_flow)

**Comment by frey1esm** [comment]
> Build Authenticaton flow in flutter - [Medium](https://engineering.classpro.in/building-authentication-flow-with-flutter-29b6924da8fd)
> github repo - [vemarav/auth_flow](https://github.com/vemarav/auth_flow)

@vemarav This is great but in your example the login page is always show for a brief moment even when the user is already authenticated.

**Comment by bface007** [comment]
According to the accepted answer on this [thread](https://stackoverflow.com/questions/49457717/flutter-get-context-in-initstate-method), we can access context from **initState** but code has to be wrapped in a **_Future.delayed_** method to work properly.
Need to give it a try.

**Comment by thevzurd** [comment]
It may not be relevant anymore, but I think I found a better way to do navigation without userinput once the authentication check is completed.

```
class SplashScreen extends StatelessWidget {

  Future<bool> _checkSignIn(BuildContext context) async {
    await globals.checkSignIn();
    globals.intialRoute = '/';
    if (globals.signInMode == SignInMode.SignedIn) {
      Navigator.of(context).pushNamedAndRemoveUntil('/', ModalRoute.withName('/splash'));
    } else {
      Navigator.pushReplacementNamed(context, '/login');
    }
    return true;
  }

  @override
  Widget build(BuildContext context) {
    _checkSignIn(context);
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: const <Widget>[
          CircularProgressIndicator(),
        ],
      ),
    );
  }
}
```
The globals.checkSignIn() methods checks if the user is already signed in. It returns globals.signInMode based on the signin status. Based on the status, the navigator is called to navigate to the next page.

The _checkSignIn() method is called in the build method without an "await". This is because our intention is to just build a screen while waiting for the signin check. Once the check is done, the navigator takes care of the rest.
Hope this helps!

**Comment by hareendranmg** [comment]
Hey folks, What is the best way to store the authenticated user state? Like sqlite. And how to retrieve that for checking?

**Comment by akasHSarode** [comment]
> How can I access the `buildContext` in `initState()`? The context is required for the Navigator to work ..

methods other than build of your stateful widget don't need to receive context as a parameter, it is available throughout the widget.
