### ISSUE TITLE
video_player plugin: 0.6.4 - Future already completed

### ISSUE THREAD

**Issue by rvowles** [flutter/flutter#19197]
I upgraded to this version of the plugin and on iOS on an iPhone 8+ I am getting:

```
[ +391 ms] [VERBOSE-2:dart_error.cc(16)] Unhandled exception:
[        ] Bad state: Future already completed
[        ] #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
[        ] #1      VideoPlayerController.initialize.eventListener (package:video_player/video_player.dart:227:33)
[        ] #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
[        ] #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[        ] #4      _DelayedData.perform (dart:async/stream_impl.dart:584:14)
[        ] #5      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
[        ] #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
[        ] #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

I don't see any particular problems, but my customer on his iPhone 6 cannot see the streaming video until the first redraw of the video player (e.g. turning it landscape).  I need the video to start playing as soon a possible, but this does not seem to affect this exception, it is always thrown. the initState method is:

```dart
_controller = new VideoPlayerController.network(
        event.cameras[0].url,
      )
        ..addListener(() {
          final bool isPlaying = _controller.value.isPlaying;
          if (isPlaying != _isPlaying) {
            setState(() {
              _isPlaying = isPlaying;
            });
          }
          if (_controller.value.hasError) {
            print("error: ${_controller.value.errorDescription}");
          }
        })
        ..initialize().then((_) {
          setState(() {
          _controller.play();
          });
        });
```

and the video player creation is straight from  the example.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by rvowles** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.25, on Mac OS X 10.13.5 17F77, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[✓] Connected devices (1 available)

• No issues found!

**Comment by rvowles** [comment]
i just upgraded to the latest on master, latest dart, etc

octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.94, on Mac OS X 10.13.5 17F77, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
[✓] Connected devices (1 available)

Still the same. doesn't affect my iPhone 8s as I said.

**Comment by recastrodiaz** [comment]
@rvowles this is most likeley caused by a race condition that is still present on iOS devices. See: #21483

**Comment by Abgaryan** [comment]
@zoechi  any updates on the issue?

**Comment by Yarikk26** [comment]
I've played a little with this bug. The cause of this is the multiple notification about changed player status. The player notifies 3 or more times about it's ready to play and sends the event to dart side 3 times also. I've checked, playbackLikelyToKeepUp is called exactly one time. So I've made a simple workaround. I've tested it on the video from example and on our live HLS only. You can check it [here](https://gist.github.com/Yarikk26/7a945223939a48aab0ab089d088c4032).

**Comment by zoechi** [comment]
@Abgaryan @long1eu @LSmint 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by georgepapas** [comment]
Are there any slated releases for this? It's a showstopper for us on ios

**Comment by keitoro** [comment]
It produces the error, but I have not seen it breaks any ios devices. So it seems harmless so far.

**Comment by ganisback** [comment]
please help fix it, i also meet this issue

**Comment by cbenhagen** [comment]
Either we make sure to only send the initialized event once from the iOS side. Or we do this in dart:

```dart
if (!value.initialized) {
  value = value.copyWith(
    duration: Duration(milliseconds: map['duration']),
    size: Size(map['width']?.toDouble() ?? 0.0,
        map['height']?.toDouble() ?? 0.0),
  );
  initializingCompleter.complete(null);
  _applyLooping();
  _applyVolume();
  _applyPlayPause();
}
```
