### ISSUE TITLE
Allow TextField widget to accept character counter for use in TextField.counterText

### ISSUE THREAD

**Issue by cjunmokim** [flutter/flutter#19193]
Hello,

I have a use case where I have a TextField widget with a max character count, and I want to pass in my own character counter rather than use what TextField does internally (iterating through strings as runes).

Screenshot here: 

![screenshot from 2018-07-09 18-39-16](https://user-images.githubusercontent.com/16652911/42484359-7f04376c-83a7-11e8-8aa0-59552ccc181c.png)

For my use case, I am constrained by display width of the TextField text and want to mark Chinese characters for example as two characters, but I feel like this could be a useful feature to have going forward.

I am envisioning something like AngularDart's material-input, which accepts an optional character counter. (https://github.com/dart-lang/angular_components/blob/1b3bad956627e2739d1a66a817a4566c651f898d/lib/material_input/base_material_input.dart#L167)

Would there be interest in having this as a feature?

**Comment by zoechi** [comment]
Is this a dup of #18068?

**Comment by escamoteur** [comment]
Not sure if this is really needed as feauture, you always could use a Stack and create the counter on your own.

**Comment by HansMuller** [comment]
I think this is a reasonable request.  It's one of two mostly complementary TextField/InputDecoratorfeature new feature proposals:

- Allow InputDecorator to provide a characterCounter widget as an alternative to characterCounterText. That's #18068 and it would accommodate app's that want to display something other than the `5 / 10` text we display now.
- Allow TextField to define how the character counter's values are computed.  In this case (#19193) what the user is supposed to see isn't a character count at all, it's the current width of the input string and the available width.

Perhaps what' s needed is `InputDecorator.characterCounterBuilder` a Widget valued callback with `TextField` and `TextEditingController` parameters. Such a callback would address both issues.

**Comment by zoechi** [comment]
I think #25095 fixes this
