### ISSUE TITLE
Request: Bi-directional scroll view

### ISSUE THREAD

**Issue by j4k0bk** [flutter/flutter#19207]
All current scrollables can only scroll in a single direction.

Would be useful to have a (single child?) scroll view which can scroll on both axises.

**Comment by j4k0bk** [comment]
One thing to keep in mind when considering this feature is how it would/could integrate with the Sliver protocol, if even possible.

Also, zoom and pan may be relevant features in this context.

**Comment by zoechi** [comment]
#25164 looks related

**Comment by zoechi** [comment]
Similar to #12878

**Comment by VladyslavBondarenko** [comment]
Hi @j4k0bk 
Please follow up on https://github.com/flutter/flutter/issues/20175
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
