### ISSUE TITLE
It's not about problem. Can I make a korean translation repository of flutter.io?

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19209]
Sorry for using this issue page, I just wanted to ask to translate partial pages of flutter.io.
I'm korean and I'm studying flutter, but there are no documentation of flutter translated or explained by korean. So I want to fork your repository and translate into korean. Can I?

**Comment by zoechi** [comment]
@Hixie

**Comment by baeharam** [comment]
@zoechi Thank you for calling him. I have a bad English skill, but I want to translate to study easier.

**Comment by dessant** [comment]
@baeharam, yes, the license allows you to fork, translate and redistribute the docs.

From the footer of https://flutter.io:
> Except as otherwise noted, this work is licensed under a Creative Commons Attribution 4.0 International License, and code samples are licensed under the BSD License.

**Comment by zoechi** [comment]
Thanks @dessant 

 @baeharam I assume this issue can be closed then. Feel free to ask more questions or create a new issue.

**Comment by Hixie** [comment]
cc @Sfshaza @mjohnsullivan

**Comment by baeharam** [comment]
@dessant @zoechi @Hixie Thx

**Comment by Sfshaza** [comment]
That is what it says in our footer.
