### ISSUE TITLE
DatePicker header overflow error

### ISSUE THREAD

**Issue by stubborncoder** [flutter/flutter#19202]
I opened a stackoverflow question [here ](https://stackoverflow.com/questions/51254421/showdatepickers-header-overflow-error/51256913#51256913), but I think I better open an issue here to check whether this could be a bug or not.

Calling showDatePicker function, does trigger the following output, with an overflow in the header of 4 pixels

![error_sample](https://user-images.githubusercontent.com/11727994/42502332-0756b48a-8436-11e8-90a7-1cecb82f8a45.PNG)

The error log:

```
I/flutter ( 4388): The specific RenderFlex in question is:
I/flutter ( 4388):   RenderFlex#26a8f OVERFLOWING
I/flutter ( 4388):   creator: Column ← Padding ← DecoratedBox ← ConstrainedBox ← Container ← _DatePickerHeader ← Column
I/flutter ( 4388):   ← SizedBox ← LayoutBuilder ← OrientationBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← ⋯
I/flutter ( 4388):   parentData: offset=Offset(16.0, 0.0) (can use size)
I/flutter ( 4388):   constraints: BoxConstraints(w=298.0, h=100.0)
I/flutter ( 4388):   size: Size(298.0, 100.0)
I/flutter ( 4388):   direction: vertical
I/flutter ( 4388):   mainAxisAlignment: center
I/flutter ( 4388):   mainAxisSize: max
I/flutter ( 4388):   crossAxisAlignment: start
I/flutter ( 4388):   textDirection: ltr
I/flutter ( 4388):   verticalDirection: down
```
I changed date_picker.dart file and set the follwing constant from 100 to 115 and it fixed the issue:

`const double _kDatePickerHeaderPortraitHeight = 115.0;`

I tested this out either in emulator Pixel API 28, and in the device Galaxy Note 8.

My excuses if this is not a bug but only my incompetence!.

Fluter doctor:

```
Upgrading Flutter from C:\Users\Rubs\Documents\Desarrollo\Flutter\flutter...
From https://github.com/flutter/flutter
   541356041..b931640c1  master     -> origin/master
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (6 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [VersiÃ³n 10.0.17134.112], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.25.0)
[√] Connected devices (2 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by zoechi** [comment]
Somewhat related #18672

**Comment by zoechi** [comment]
This was reported earlier but #20171 has a complete exception text.
Closing as dup of #20171

**Comment by raquelms203** [comment]
I got this problem too, but I resolve by using the builder propriety and wrapping the return with a ListView.

![image](https://user-images.githubusercontent.com/38962505/57738041-a3603100-768c-11e9-8287-b31728c40961.png)

**Comment by raquelms203** [comment]
I got this problem too, but I found a solution. Just wrap with FittedBox
![image](https://user-images.githubusercontent.com/38962505/57960492-c33f6100-78e7-11e9-97eb-8edffdd44d15.png)
