### ISSUE TITLE
Releasing resources acquired in a plugin

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#19206]
Plugins in standalone flutter apps typically live as long as the application is alive. However, in add2app use case, we would want to be able to free the resources and destroy the plugin if the isolate backing the plugin is no longer active (e.g. if FlutterView is destroyed). In some cases, this can be done by subscribing to the activity lifecycle (e.g. if the Flutter is added as a separate activity) but most often the plugin is attached to a single view.

We need a way to detect that the isolate (i.e. `FlutterNativeView`) is being destroyed.

**Comment by matthew-carroll** [comment]
@mehmetf does this need to apply to the old embedding, or just the new one?

In either case, can you describe what the definition of done should look like?  For example, should all 1P plugins actually free up their resources to consider this ticket done?  Or is there a more narrow interpretation of this ticket that could be handled just by the embedding?

**Comment by mehmetf** [comment]
`We need a way to detect that the isolate (i.e. FlutterNativeView) is being destroyed.`

If this is already there, this ticket can be closed.

`Should all 1P plugins actually free up their resources to consider this ticket done? `

No. The title is poorly worded. This is about embedder capability. Embedder needs to be able to signal to the plugin to clean up its resources.

**Comment by matthew-carroll** [comment]
Ok.  Moving forward, plugins will be capable of being unregistered.  They will be notified of this.  Also, if the FlutterEngine that they are attached to is disposed of, all plugins will automatically be unregistered from that FlutterEngine first.  Is that sufficient?

**Comment by mehmetf** [comment]
Yes.

**Comment by matthew-carroll** [comment]
I'm going to close this ticket now that enough of the plugin API has been merged to facilitate plugin resource cleanup when the `FlutterEngine` is destroyed.
