### ISSUE TITLE
IOS: Invalid Bundle. You've included the "arm64",... must only contain the 64-bit architecture slice

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#19215]
Today i tried to compile and deploy my flutter app for ios 
the flutter build ios command worked well.

But when i tried to validate my project with xcode it returned this error:

`
ERROR ITMS-90503: "Invalid Bundle. You've included the "arm64" value for the UIRequiredDeviceCapabilities key in your Xcode project, indicating that your app may only support 64-bit. Your binary, '******', must only contain the 64-bit architecture slice. Learn more (https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW3)."
`
What i can do?
Thanks

**Comment by eddywm** [comment]
I realized this problem emerging  when I have 3 or more than three Flutter testing apps in the running device.
I solved it by uninstalling at least 1 Flutter App.

**Comment by romaluca** [comment]
I have only 1 app

**Comment by jmrboosties** [comment]
Same issue, working on it now, will report what I find.

**Comment by AppleEducate** [comment]
@eddywm  this is happening when building for release mode too

**Comment by rtolar** [comment]
I encountered this issue as well.   I was able to resolve it by following the workaround specified here: https://github.com/flutter/flutter/issues/16967

e.g. "In the meantime, to fix this, which should allow you to release a 64-bit only binary, you'll want to open your Xcode project settings and set the Architectures setting to arm64"

**Comment by ThinkDigitalSoftware** [comment]
> I encountered this issue as well. I was able to resolve it by following the workaround specified here: #16967
> 
> e.g. "In the meantime, to fix this, which should allow you to release a 64-bit only binary, you'll want to open your Xcode project settings and set the Architectures setting to arm64"

I have that set and I still get the error.

**Comment by jmagman** [comment]
I know you filed this awhile ago, are you still seeing it?

I'm not even sure where that UIRequiredDeviceCapabilities key is coming from; the default `flutter create` template doesn't include it in the Info.plist.

Can we get the output of:
```
$ flutter build ios
$ grep -ri "UIRequiredDeviceCapabilities" .
$ plutil -p ios/Runner/Info.plist 
$ plutil -p build/ios/Release-iphoneos/Runner.app/Info.plist
```

**Comment by rodydavis** [comment]
It was needed on a old flutter version. I just recreated macos. Feel free to delete and recreate iOS and submit a PR! I’m on the master channel. That should fix it

**Comment by jmagman** [comment]
I couldn't find it in flutter/flutter but maybe the message was referencing the Flutter.framework Info.plist, which has since been removed:
https://github.com/flutter/flutter/issues/16124
https://github.com/flutter/engine/pull/5435

**Comment by jonahwilliams** [comment]
Sounds like this issue has been resolved then?

**Comment by jmagman** [comment]
@romaluca Can you confirm you are no longer seeing this on current stable?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
