### ISSUE TITLE
Material Slider track should be customizable.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19216]
Currently the slider thumb and value indicator are fully customizable because the developer can provide their own painter for them, but they are stuck with the material slider's track.

It would be good to add a similar mechanism for the track, factoring out the existing track rendering, and adding a setting for it to the SliderThemeData class.

**Comment by eduardhasanaj2** [comment]
I think that also heigh of thumb should be added to theme data, and based on it, track height can scale to an size, I mean height. It is very overwhelming to use painter to change thumb size.

**Comment by kibantony** [comment]
Here's an example of a slider design that we'd like to be able to achieve in Flutter:
![image](https://user-images.githubusercontent.com/8175821/42536518-2b1c9806-8447-11e8-946e-005ebb47c977.png)

**Comment by gspencergoog** [comment]
Yeah, you won't be able to achieve that easily until we've fixed this limitation in the slider API.

**Comment by kibantony** [comment]
Understood. Happy to roll our own until then.

**Comment by clocksmith** [comment]
This is possible after #25008

**Comment by zoechi** [comment]
Thanks @clocksmith !
