### ISSUE TITLE
ChildViewConnection should also accept a View* mojo struct

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#1921]
Current implementation of ChildViewConnection takes a url which mandates that the the app embedding another app is the first point of connection. We need to connect to the embedee from another app preferably before the embeder.

This should mean that this app should be able to create a mojom struct with all the connection information and pass it to the embeder.

/cc @abarth @j9brown

**Comment by j9brown** [comment]
Technically this means you want the ViewOwner.
