### ISSUE TITLE
Tests should be able to load images from files.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19214]
In flutter/packages#2, I need to load images in order to test the palette generator.  I was able to make a fake `ImageProvider` that would be able to load the images before the test zone was entered, but it fails when trying to access the image bytes themselves, saying "Could not copy pixels from the raster image.", which implies that the SkImage backing things isn't available on a desktop environment.

Is there a way to get the image decoder to load an image from a file in a test that runs in a desktop environment?

**Comment by zoechi** [comment]
They are also not rendered in Golden tests.

**Comment by gspencergoog** [comment]
I spoke with @jason-simmons about this, and he's going to take a look.  In the meantime, I'm going to try and mock out the images I need.
