### ISSUE TITLE
How to use flutter 

### ISSUE THREAD

**Issue by Dule-mart** [flutter/flutter#19221]
How can I use after installation

**Comment by liyuqian** [comment]
1. Connect an Android/iOS device, or start an Android/iOS simulator
2. Go to an example flutter app (e.g., `cd examples/flutter_gallery`)
3. Type `flutter run` and see the example app running on your device or simulator

If anything goes wrong, type `flutter doctor` for diagnosis.

Does this answer your question?

**Comment by zoechi** [comment]
Did you check https://flutter.io especially https://flutter.io/get-started/editor/

I am going to close this issue because there is nothing actionable for the Flutter team.
Feel free to add more questions below if you are still stuck.
