### ISSUE TITLE
[!] VS Code, 64-bit edition (version 1.25.0)

### ISSUE THREAD

**Issue by botaniQQQ** [flutter/flutter#19223]
`[!] VS Code, 64-bit edition (version 1.25.0)`

![42454967-a14f93b0-8399-11e8-94d1-8de056dcfae5](https://user-images.githubusercontent.com/3118010/42537497-b9bf979c-849d-11e8-931b-1808e8470daf.jpg)

**Comment by zoechi** [comment]
@DanTup Perhaps you know what this means.

**Comment by DanTup** [comment]
The `[!]` here does not mean that you don't have VS Code installed, but that either:

1. You don't have the [Flutter plugin](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) installed in VS Code
2. You do have the Flutter plugin installed, but are on the `beta` channel and there is a bug that means it does not detect this correctly (in which case, you can just ignore the warning and it'll go away in the next update).

If you run `flutter doctor -v` (as described on the first line of the output) it would give (slightly) more information.

If you think there is a problem, please provide more information for us to investigate.

**Comment by botaniQQQ** [comment]
@DanTup `flutter doctor -v`

![jztvnag](https://user-images.githubusercontent.com/3118010/42593948-70373a9e-8556-11e8-8027-e32676c43ea5.png)

**Comment by DanTup** [comment]
@botaniQQQ Yep, that's this:

> 2. You do have the Flutter plugin installed, but are on the beta channel and there is a bug that means it does not detect this correctly (in which case, you can just ignore the warning and it'll go away in the next update).

**Comment by yeltsinxyz** [comment]
Sorry for re-opening this issue. But I have the same problem. I run the `flutter doctor -v` here is the log

```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [versÃ£o 10.0.17134.112], locale pt-BR)
    • Flutter version 0.5.1 at C:\Dev\flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\yelts\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.25.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • SM G955F • ce051715c8884cb00d • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

The problem is: Flutter it is installed in VScode. Maybe there is some bug w/ 64 bit-version?

![Visual Studio Code](https://i.imgur.com/FqNw8zd.png)

**Comment by DanTup** [comment]
Yeah sorry, I don't think I worded it very well..

There was a change in VS Code which broke our detection of the extension. I fixed it, but the fix hasn't gotten to the beta channel yet.
