### ISSUE TITLE
[flutter_gallery] text_form_field_demo problems

### ISSUE THREAD

**Issue by hubertdej** [flutter/flutter#19229]
1. `_autovalidate = true;` should be wrapped inside setstate().
2. It is possible to get snackbar information "Please fix the errors in red before submitting." when there are no error messages (fill the name and phone fields correctly, then press Submit button).

**Comment by zoechi** [comment]
I assume you mean https://github.com/flutter/flutter/blob/8e9780767110b8ec420f336572dbb8545190e52d/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart#L100-L101

**Comment by hubertdej** [comment]
Yes

**Comment by TahaTesser** [comment]
Hi @hubertdej 
Please try new https://github.com/flutter/gallery 
Closing as this issue flutter_gallery issn't available anymore and removed 
Thank you
