### ISSUE TITLE
getting-started tells you to go follow the tutorial too early

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1922]
Unclear at “The code for your app is in my_app/lib/main.dart. To learn more about how to build apps with Flutter, please see the tutorial.” Which path I should take.  Should I go to the tutorial now?

I suspect we should save this until after iOS or Android setup.  Perhaps we should hide iOS or Android (or both) under some sort of disclosure view to make the getting-started feel less long?

**Comment by abarth** [comment]
Will be addressed by https://docs.google.com/document/d/1wL_7BvpExxyvLqtf5am3_iMQThWBZ0Ak1uPVFiI3KN8/edit?usp=sharing

**Comment by qchong** [comment]
Fixed in flutter/website#178, based on doc shared by abarth@.

**Comment by qchong** [comment]
Marking as closed.
