### ISSUE TITLE
consider moving iOS instructions above Android instructions

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1923]
Running in the simulator is easier (doesn't require additional installs beyond Xcode), so perhaps we should move that higher on the getting-started page?

**Comment by abarth** [comment]
I've done this in my updated draft of the getting-started instructions:

https://docs.google.com/document/d/1wL_7BvpExxyvLqtf5am3_iMQThWBZ0Ak1uPVFiI3KN8/edit?usp=sharing

**Comment by qchong** [comment]
Made this fix in the [Flutter Setup](https://flutter.io/setup/) page, based on doc shared by abarth@.

**Comment by qchong** [comment]
Marking as closed.
