### ISSUE TITLE
Notification on first page for PageView

### ISSUE THREAD

**Issue by Edward608** [flutter/flutter#19249]
Currently the `onPageChanged` function only get called when a action occurred, but user cannot get notify when the PageView is first loaded on `initialPage`. It is simple to modify the `PageView` class to provide initial notification. Any thoughts on this?

**Comment by zoechi** [comment]
Can you please provide some code that demonstrates what you try to accomplish?

**Comment by Edward608** [comment]
```
class _SomeWidgetState extends State<SomeWidget> {
	var currentIndex = 0;
	
  @override
  Widget build(BuildContext context) {
    return Column(
	    children: <Widget>[
	    	PageView(
                             controller: PageController(initialPage: currentIndex),
			    onPageChanged: (index) {
			    	setState(() {
			    		currentIndex = index;
			    	});
			    },
			    children: <Widget>[],
		    ),
		    Text("$currentIndex"),
	    ],
    );
  }
}
```
In the above case, the initial index of pageview must be pulled out as a state variable, such that the `Text` can render properly on first build. An ideal case would be without the need of `currentIndex` variable inside the `State`.

**Comment by zoechi** [comment]
Can you please elaborate more. It's not clear to me why the state variable is an issue.

Just a wild guess. You can move it out from the state to the widget. 
But I don't really understand what problem you are trying to solve.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by vHanda** [comment]
Hi. I'm trying to add analytics to my app about the page number in the pageView. I was hooking it up to `onPageChanged`, but this is not called for the initial page. I think it should be called for each page.

or is there any other way I can hook up analytics to the PageView?
