### ISSUE TITLE
Add single expanded ExpasionPanel in an ExpansionPanelList option

### ISSUE THREAD

**Issue by braulio94** [flutter/flutter#19240]
When creating an ExpansionPanelList multiple ExpansionPanels can be opened at the same time.
It'd be nice if there was a bool in the ExpansionPanelList to set whether it should behave like a list of CheckBoxes or a list of RadioButtons.

**Comment by zoechi** [comment]
You mean a setting wether 
- only one can be expanded at a time and others should be collapsed when a panel is expanded 
- more than one panel can be expanded at the same time where expanding one doesn't affect others expanded state

**Comment by braulio94** [comment]
@zoechi that's exactly what I mean!
