### ISSUE TITLE
flutter build should run anayzer to catch Dart 2 issues

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#19258]
When you run `flutter build` we compile with CFE from Dart 2. This has known issues that it does not catch all Dart 2 issues. These can be caught with the Dart 2 analyzer. Thus I propose that we change `flutter build` to run `flutter analyze` as a first step before calling the Dart 2 compiler, to ensure that developers are aware of all potential issues in their code prior to a release artifact being built.

In addition, we should make sure that `flutter analyze` in this case analyzes not only the Dart code from the app/library, but also from all the dependencies declared in `pubspec.yaml`

This solution is only expected to be short-term; the CFE should be complete by Dart 2.1.

**Comment by mit-mit** [comment]
@devoncarew this is the issue we discussed earlier this week

**Comment by devoncarew** [comment]
To follow up on this:

- keep in mind that flutter analyze checks the user's source, but doesn't report issues with packages that are used
- plus, we'd be over-reporting - reporting on code that might never be in the runtime path of their app

**Comment by mit-mit** [comment]
What's an example of the latter?

**Comment by devoncarew** [comment]
Not all the code in the project directory would be executed (`tests/`, ...), and for packages, not all their code in `<package_foo>/lib/`) would be executed - libraries that aren't referenced, APIs and code paths unused. The analyzer would report for every dart file, but a build would just report for the transitive set of referenced source files.

**Comment by jonahwilliams** [comment]
I think the correct fix would be to make the CFE and analyzer agree on what is an error, no?

**Comment by mit-mit** [comment]
As I mentioned towards the end of my initial command, this was supposed to be a temporary measure. My understanding is that they do agree now, so I thin we can close this. Is that correct @devoncarew ?

**Comment by devoncarew** [comment]
Yes, this issue was only relevant during the transition, when there wasn't parity w/ dart 2 support between the cfe and analyzer.
