### ISSUE TITLE
Confusing docs for OrientationBuilder

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#19259]
https://docs.flutter.io/flutter/widgets/OrientationBuilder-class.html says

> Builds a widget tree that can depend on the parent widget's orientation (**distinct from the device orientation**).

https://flutter.io/cookbook/design/orientation/ says

> In order to determine the Orientation of the screen, we can use the  OrientationBuilder Widget.

What is the difference between 
- screen orientation
- device orientation
- parent widget's orientation?

**Comment by notnorth** [comment]
It would seem to me that the cookbook is confusing terms. The orientation of the screen (which I would think is synonymous with device) should be retrieved via `MediaQuery.of(context).orientation`.

OrientationBuilder doesn't reflect the orientation of the device / screen at all, but rather if the parents width is greater than its height as detailed in the source comment:

> A widget's orientation is simply a factor of its width relative to its height. For example, a [Column] widget will have a landscape orientation if its width exceeds its height, even though it displays its children in a vertical array.

**Comment by Sfshaza** [comment]
@brianegan

**Comment by brianegan** [comment]
Good call, I'll fix that up!

**Comment by brianegan** [comment]
Proposed solution here: https://github.com/flutter/website/pull/1120

**Comment by brianegan** [comment]
Gotcha... I've pushed another update, please let me know what you think.

**Comment by zoechi** [comment]
LGTM 👍

**Comment by dibusch** [comment]
In any case use "MediaQuery.of(context).orientation". It is much better than OrientationBuilder. OrientationBuilder unexpectedly changes orientation when GridView is primary and the focus is on a TextField. It slows down the SliverAppBar significantly.
