### ISSUE TITLE
Update published Gallery app

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#19262]
It was last published on 2018-05-08 and doesn't contain the search demo

https://github.com/flutter/flutter/blob/226f2c1e99accab83d12bfd49e805f8d7d2d3ed6/examples/flutter_gallery/lib/demo/material/search_demo.dart

**Comment by xster** [comment]
@mit-mit would you like to do this before your trip? :)

You should have all the controls in the Play Console.

**Comment by mit-mit** [comment]
I don't seem to have access to it in the Play Console anymore?

**Comment by xster** [comment]
The one online is the last beta. Should we publish a different version?

**Comment by zoechi** [comment]
Duplicate of #15533
