### ISSUE TITLE
Container padding clips contents, but does not clip to container border radius

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19265]
<img width="948" alt="screen shot 2018-07-11 at 11 10 52 am" src="https://user-images.githubusercontent.com/666539/42581631-3caa2228-84fb-11e8-8240-581cc97f1db2.png">

Not sure if this is a bug, matter of opinion, or designer error. Any insights?

**Comment by zoechi** [comment]
Could you please post a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Ok, I'm going to close. Just add a comment to have it reopened if you think there needs something to be done if possible with a reproduction.
