### ISSUE TITLE
Recommendation postgress package

### ISSUE THREAD

**Issue by ShawnRG** [flutter/flutter#19260]
Hi
Im developing a flutter app at the moment and i need to connect to a postgres db but the packages out there arent ported to dart2 yet.

Any solutions for my issue?

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/postgres/versions/1.0.0-beta.1#-changelog-tab- seems to support Dart 2. If it doesn't please report issues there. Thanks!
