### ISSUE TITLE
ClipRRect is bigger than it's child

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19268]
ClipRRect appears to be bigger than its child in this specific scenario. In an alternative case, ClipRRect was the exact size of its child. You can see that the borderRadius seems to start from much larger bounds.

<img width="935" alt="screen shot 2018-07-11 at 11 44 48 am" src="https://user-images.githubusercontent.com/666539/42583960-23e8fb42-8500-11e8-8403-6fb34eed73b6.png">

**Comment by lukepighetti** [comment]
<img width="1011" alt="screen shot 2018-07-11 at 11 49 30 am" src="https://user-images.githubusercontent.com/666539/42584116-7c531b82-8500-11e8-896d-e21e00844cc2.png">

**Comment by lukepighetti** [comment]
It appears to be the margin on the child container causing the issue

**Comment by lukepighetti** [comment]
OK I found a solution. This works as expected. My only question, is there a more succinct way of achieving this? Eventually I intend to animate the height of the drawer.

<img width="948" alt="screen shot 2018-07-11 at 11 52 17 am" src="https://user-images.githubusercontent.com/666539/42584330-f40130c4-8500-11e8-9e19-4fbe7f58a504.png">

**Comment by darshankawar** [comment]
Hi @lukepighetti,
Is this still an issue or can this be closed ?

**Comment by lukepighetti** [comment]
No idea
