### ISSUE TITLE
BoxDecoration has no padding property

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19266]
padding property is documented

https://docs.flutter.io/flutter/painting/BoxDecoration-class.html

but it is not available

<img width="718" alt="screen shot 2018-07-11 at 11 31 22 am" src="https://user-images.githubusercontent.com/666539/42582824-0ed118fe-84fe-11e8-9119-d770b036e360.png">

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/42583526-6a3716e8-8531-11e8-88cb-e8d69a4acaab.png)

It says `readonly`. 

See also https://github.com/flutter/flutter/blob/09276bea258737e11b109e227f70eac94a4e1691/packages/flutter/lib/src/painting/box_decoration.dart#L153 (only a setter)

**Comment by lukepighetti** [comment]
Ah, thanks. My mistake.
