### ISSUE TITLE
How to get String size, like boundingRectWithSize: options:attributes: context: in iOS?

### ISSUE THREAD

**Issue by jiangjh** [flutter/flutter#19264]

**Comment by jiangjh** [comment]
How to use Offstage-class? String width is fixed, how to get height needed?

**Comment by jiangjh** [comment]
I want to get String height not rendering!

**Comment by jiangjh** [comment]
Thanks very much.You are very patience.

**Comment by zoechi** [comment]
But you need to render first to be able to get the height from the rendered result.

**Comment by jiangjh** [comment]
iOS can get the size of string not rendering. by boundingRectWithSize: options:attributes: context: method.

**Comment by zoechi** [comment]
See https://github.com/flutter/flutter/issues/18431#issuecomment-396990020

**Comment by zoechi** [comment]
I posted a simple example where I reuse the TextPainter from the Text widget as answer to https://stackoverflow.com/questions/52659759/how-can-i-get-the-size-of-the-text-widget-in-flutter/52991124#52991124
