### ISSUE TITLE
setPersistenceEnabled(true) not working in offline app restarts- firebase realtime database

### ISSUE THREAD

**Issue by Apurv2017** [flutter/flutter#19271]
I am using a firebase animated list to show a list of items stored in firebase realtime database.

Now when I start the app(after the app is **killed/terminated**) in the **offline** state, the list does not load.

Persisted to on-device (using setPersistenceEnabled(true)) should survive a terminated app.

I am using latest plugin [firebase_database: "^1.0.1"]

**Comment by zoechi** [comment]
Related https://stackoverflow.com/questions/51288944/is-there-a-way-for-firebase-flutter-apps-to-persist-data-across-offline-app-rest

**Comment by kroikie** [comment]
@Apurv2017

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/758. Any further collaboration will be done there.
