### ISSUE TITLE
Make runCommandAndStreamOutput testable

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#19286]
Currently, in `flutter_tools`, testing invocations of `runCommandAndStreamOutput` relies on mocking out a lot of implementation details (processManager, stream handling). We should write a cleanly-testable alternative/wrapper. This would make testing things like lib/src/android/gradle.dart and lib/src/ios/devices.dart much cleaner.

**Comment by zanderso** [comment]
Obsolete. Closing.
