### ISSUE TITLE
Flutter apps should setState randomly in development mode

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#19297]
As I understand it, the official answer to "when does Flutter call build?" is "potentially once a frame, less as an optimization."  Currently in Flutter it is easy to write widgets which actually rely on only being rebuilt once (which will happen to work because we are quite good at optimizing!) However, there is a hidden danger, which is that a slight change to animations or a parent widget could break this fragile misbehaving Widget. 

To avoid situations like these, we should make sure these Widgets break in development mode.  We can do this easily by inserting a Widget or other binding in runApp if assertions are enabled.  This will mark the tree dirty at the root, which should cause all child widgets to rebuild.  Some examples of bad patterns this will break:
  * FutureBuilders where a new Future is created in `build`.
  * Expensive operations or API calls in `build`
  * Anything else that depends on build only being called a certain # of times.

A similar issue where users can depend on an implementation detail in a dangerous way is the order of iteration of a `Map`.  Dart chose to make the default `Map` ordered, so that it is quite explicit and part of the API.  In contrast Golang randomizes the key order on each iteration, making it impossible to depend on.

**Comment by jonahwilliams** [comment]
Some other errors this would catch:
  * Using randomly generated value keys
  * open snackbars or using overlays in a scheduleMicrotask inside of build

**Comment by jonahwilliams** [comment]
Ahh the navigator, and overlays.  So marking everything dirty could run through a similar path to hot reload though, sounds reasonably promising.

**Comment by zoechi** [comment]
Sounds a bit like Angular development mode where change detection makes an additional 2nd turn every time it runs to check all bindings are actually idempotent.
This is very helpful but caused lots of questions. 
There should be a very prominent information about that behavior.

**Comment by jonahwilliams** [comment]
Possibly we could make it some sort of flag or toggle in debug mode, then a user could opt in to see if there app has issues.  If that works well we could make it the default in future releases

**Comment by Hixie** [comment]
Ironically, doing this can actually paper over issues too. It's just as common to forget to call setState, but rely on something else accidentally forcing an update.

There's also a serious performance cost here. Hot reload takes on the order of hundreds of milliseconds, because of marking everything dirty.

**Comment by jonahwilliams** [comment]
I guess that is true as well- though I wasn't conceiving of running this every second, rather sometime between every 5 - 20 seconds.  Just enough to make misbehaving widgets stand out but not enough to rely on.  Maybe that would still be too much.

Another approach might be to sometimes run `build` twice.  This couldn't be relied on to update state, but it would catch some of the above issues like side-effects in the build methods.

**Comment by Hixie** [comment]
The risk of running it more rarely is that it's basically intentional flakiness, with all the problems of flakes.

**Comment by jonahwilliams** [comment]
Thinking about it more, changing the behavior in such a way is probably too indiscriminate.  Unlike an assert, this won't help anyone pin down exactly where the problem is - so maybe instead what we need (for cases that asserts don't help) is better lints or static analysis.  For example, we should be able to say for build-like methods (defined by some annotation or specified list of Classes/methods),  you can't use X list of APIs in them (defined similarly).  I'm less familiar with the analyzer APIs, but it should be possible to distinguish between a `scheduleMicrotask` in the method body vs in a callback.

I don't think I'll pursue the setState idea further, so I'm closing this for now
