### ISSUE TITLE
Vertical tree healing

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#193]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Oct 08, 2015 at 18:28 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1544_

----

When you want to add or remove gesture detection, it's intuitive to think that the following should all be equivalent:

- Having a test in the handlers.
- Having a test in the build function that decides whether to set the handlers.
- Having a test in the build function that decides whether to have a GestureDetector at all.
- Having a test in the build function that decides whether to have a GestureDetector at all, where the child of the GestureDetector is a KeyedSubtree with a `new GlobalObjectKey(this)`.

The first two and the fourth are in fact equivalent (the second is slightly slower, the fourth slightly slower still), but the third is not. The third will cause all kinds of state to drop.

We should fix that. Until we do, we should document the heck out of it.

**Comment by abarth** [comment]
I'm pretty happy with the "state follows global keys" design we ended up with.
