### ISSUE TITLE
Done button in keyboard show up instead of Next when I set textInputAction: TextInputAction.next

### ISSUE THREAD

**Issue by csnguyen-gmail** [flutter/flutter#19306]
## Steps to Reproduce

I create a normal TextField like below:
`
TextField(
  controller: _controller,
  focusNode: _focus,
  textInputAction: TextInputAction.next,
  onSubmitted: (string) {
    doSomthing();
  },
)
`
I suppose keyboard will appear with Next button as action button.
It works in Flutter Master - commit 541356.
But after this version, Done button appear instead of Next button

## Logs

Chus-MBP-2:cls_user_mobile csnguyen$ flutter doctor --verbose
[✓] Flutter (Channel unknown, v0.5.7-pre.59, on Mac OS X 10.13.5 17F77, locale en-VN)
    • Flutter version 0.5.7-pre.59 at /Users/csnguyen/Documents/Flutter/flutter
    • Framework revision 5413560415 (7 days ago), 2018-07-05 17:58:26 +0100
    • Engine revision 21c7d6a5da
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/csnguyen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.12.2

[✓] Connected devices (1 available)
    • Testflight’s iPhone • 151a3b628eb4a2059ca349c391306f4bfdf03e5d • ios • iOS 11.3.1

• No issues found!

**Comment by jonahwilliams** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
I think this is due to the fact that we haven't rolled the engine into the framework recently.  The engine hasn't been rolled since June 28 and these text input changes landed in the engine on July 1.

When the engine finally gets updated in the framework, this should work as expected.

**Comment by csnguyen-gmail** [comment]
Thanks for feedback, is there any way allow me to track when the engine will be updated?

**Comment by matthew-carroll** [comment]
@csnguyen-gmail it looks like the engine has been rolled past the keyboard addition, so try it with the latest engine and see if things are working.  If things are working for you, please let us know so we can close this ticket.

As far as tracking the engine updates, I don't know of anything other than checking commits to the framework.  The engine version is under bin/internal/engine.version

**Comment by csnguyen-gmail** [comment]
It's work with below versions:
Flutter 0.5.7-pre.105 • channel master • https://github.com/flutter/flutter.git
Framework • revision cc122f1672 (4 days ago) • 2018-07-14 09:32:41 -0700
Engine • revision c5a63d28bf
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
Thanks for support, you can close this issue.

**Comment by matthew-carroll** [comment]
Great. Thanks.
