### ISSUE TITLE
How Can I swipe for back in Flutter? not tap back button

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#19308]
![image](https://user-images.githubusercontent.com/5095376/42632479-e4cbd0b8-860f-11e8-8fca-fa0050d6cbf2.png)

but whis second page is flutter page ,we see rootview is native page, 

native->flutterview->flutterview 2

when i am swipe back in flutterview 2, it is pop to native

**Comment by jslavitz** [comment]
Have you created a material or a Cupertino themed app? It seems as tho swiping to go back is only enabled by default in Cupertino themed apps.

**Comment by lichentao** [comment]
@jslavitz I don't only use Cupertino themed apps, Exixting App . From flutter to native Activity Or . flutter to flutter to Activiey ,an so on

**Comment by lichentao** [comment]
why . i put the flutterviewcontroller to window.rootviewcontroller ,it is work for swipe back

**Comment by goderbauer** [comment]
Sounds like you got it to work? Please re-open with more details if this is still an issue for you.

**Comment by zmtzawqlp** [comment]
你解决了吗？ 你可以把原生的禁止了。。但是当back到根页面的时候。。没法玩耍，我现在也遇到这个问题
