### ISSUE TITLE
Text Fields hidden behind keyboard

### ISSUE THREAD

**Issue by VickySalunkhe** [flutter/flutter#19300]
Related #10826 #18837 #18711

Facing the same issues.
i am using this structure
SingleChildScrollView -> Container -> TabBarView -> Form -> Container -> Listview -> Childrens

this made my view to scroll but the problem remained there only that when keyboard is activated bottom textfields doesnt comeup, an hides behind the keyboard.

tried many different variations but above mentioned structure has given the best output but still the problem persists with keyboard.

IN Flutter Gallery app. the text_form_field code

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart

is working fine with the keyboard also all expected behavior is working but i assume why it is not working with most of the people?

```dart
@override
  Widget build(BuildContext context) {
    return new Scaffold(
        resizeToAvoidBottomPadding: false,
        key: _scaffoldKey,
        body: new Container(
            color: Colors.black,
            child: Column(
              children: <Widget>[
                new Container(
                  margin: const EdgeInsets.only(
                      left: 15.0, right: 15.0, bottom: 15.0, top: 40.0),
                  child: Image.asset(
                    "images/logo-black.jpg",
                    alignment: Alignment.center,
                    height: (MediaQuery.of(context).size.width - 90) / 2,
                    width: MediaQuery.of(context).size.width - 90,
                    fit: BoxFit.contain,
                  ),
                ),
                new TabBar(
                    labelColor: Colors.white,
                    indicatorWeight: 4.0,
                    indicatorColor: Colors.white70,
                    controller: _controller, 
                    //          isScrollable: true,
                    labelStyle: TextStyle(fontSize: 16.0),
                    tabs: _customizePages.map((_CustomizePage _page) {
                      return new Tab(text: _page.text);
                    }).toList()),
                new SingleChildScrollView(
                    // 
                    scrollDirection: Axis.vertical,
                    controller: ScrollController(),
                    child: new Container(
                      height: MediaQuery.of(context).size.height / 1.65,
                    child: new TabBarView(
                      
                        controller: _controller,
                        children: _customizePages.map((_CustomizePage _page) {
                          //return new Tab(text: _page.text);
                          switch (_page.pos.toInt()) {
                            case 0:
                              return _signin();
                              break;
                            case 1:
                              return _signup();
                              break;
                            default:
                              new Text("data");
                          }
                        }).toList()))),
              ],
            )));
  }
```

_signup()

```dart
Widget _signup() {
    return new Form(
      key: _signupformKey,
      autovalidate: _autovalidate,
      onWillPop: _warnUserAboutInvalidData,
      child: new Container (
        margin: const EdgeInsets.only(left: 16.0, right: 16.0),
        child: new ListView(
          children: <Widget>[
            new Container(
              padding: const EdgeInsets.only(left: 15.0),
              color: Colors.white,
              child: new TextFormField(
                decoration: const InputDecoration(
                  fillColor: Colors.white,
                  border: UnderlineInputBorder(),
                  filled: true,
                  icon: const Icon(
                    Icons.person,
                    color: Colors.black,
                  ),
                  hintText: 'Enter your name',
                  labelText: 'Name',
                ),
                keyboardType: TextInputType.text,
                onSaved: (String value) {
                  person.name = value;
                },
              ),
            ),
            const SizedBox(height: 7.0),
            new Container(
              padding: const EdgeInsets.only(left: 15.0),
              color: Colors.white,
              child: new TextFormField(
                decoration: const InputDecoration(
                  fillColor: Colors.white,
                  border: UnderlineInputBorder(),
                  filled: true,
                  icon: const Icon(
                    Icons.email,
                    color: Colors.black,
                  ),
                  hintText: 'Your email address',
                  labelText: 'E-mail',
                ),
                keyboardType: TextInputType.emailAddress,
                onSaved: (String value) {
                  person.email = value;
                },
              ),
            ),

            const SizedBox(height: 7.0),
            new Container(
              padding: const EdgeInsets.only(left: 15.0),
              color: Colors.white,
              child: new TextFormField(
                decoration: const InputDecoration(
                  fillColor: Colors.white,
                  border: UnderlineInputBorder(),
                  filled: true,
                  icon: const Icon(
                    Icons.email,
                    color: Colors.black,
                  ),
                  hintText: 'Your email address',
                  labelText: 'E-mail',
                ),
                keyboardType: TextInputType.emailAddress,
                onSaved: (String value) {
                  person.email = value;
                },
              ),
            ),const SizedBox(height: 7.0),
            new Container(
              padding: const EdgeInsets.only(left: 15.0),
              color: Colors.white,
              child: new TextFormField(
                decoration: const InputDecoration(
                  fillColor: Colors.white,
                  border: UnderlineInputBorder(),
                  filled: true,
                  icon: const Icon(
                    Icons.email,
                    color: Colors.black,
                  ),
                  hintText: 'Your email address',
                  labelText: 'E-mail',
                ),
                keyboardType: TextInputType.emailAddress,
                onSaved: (String value) {
                  person.email = value;
                },
              ),
            ),const SizedBox(height: 7.0),
            new Container(
              padding: const EdgeInsets.only(left: 15.0),
              color: Colors.white,
              child: new TextFormField(
                decoration: const InputDecoration(
                  fillColor: Colors.white,
                  border: UnderlineInputBorder(),
                  filled: true,
                  icon: const Icon(
                    Icons.email,
                    color: Colors.black,
                  ),
                  hintText: 'Your email address',
                  labelText: 'E-mail',
                ),
                keyboardType: TextInputType.emailAddress,
                onSaved: (String value) {
                  person.email = value;
                },
              ),
            ),



            const SizedBox(height: 7.0),
            new PasswordField(
              fieldKey: _signuppasswordFieldKey,
              labelText: 'Password',
              hintText: "Keep a strong password",
              onSaved: (String value) {
                setState(() {
                  person.password = value;
                });
              },
              onFieldSubmitted: (String value) {
                setState(() {
                  person.password = value;
                });
              },
            ),
             const SizedBox(height: 7.0),
                new Container(
              padding: const EdgeInsets.only(left: 15.0),
              color: Colors.white,
              child: new TextFormField(
                  //enabled: person.password != null && person.password.isNotEmpty,
                  decoration: const InputDecoration(
                    fillColor: Colors.white,
                    border: const UnderlineInputBorder(),
                    filled: true,
                    labelText: 'Re-type password',  
                    icon: Icon(Icons.security)
                  ),
                  obscureText: true,
                  validator: _validatePassword,
                )),
            const SizedBox(height: 7.0),
            new MaterialButton(
              height: 50.0,
              color: Colors.white30,
              textColor: Colors.white,
              child: new Text("SIGN UP"),
              onPressed: _signuphandleSubmitted,
              splashColor: Colors.white,
            ),
            const SizedBox(height: 7.0),
            new Text(
              '* indicates required field',
              style: TextStyle(color: Colors.white70),
            ),
            
          ],
        ),
      ),
    );
  }
```

[Video of application is here](https://drive.google.com/open?id=1ecjiCJ2h9yB971J_-cvYgcamCOp3vIJI)
`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`.
Have you tried with `dev` channel? There was a change recently.

**Comment by VickySalunkhe** [comment]
flutter doctor 


> [flutter] flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 6.1.7601], locale en-IN)
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
> [√] Android Studio (version 3.1)
> [!] VS Code, 64-bit edition (version 1.25.0)
> [!] Connected devices
>     ! No devices available
> 
> ! Doctor found issues in 2 categories.
> exit code 0

**Comment by VickySalunkhe** [comment]
dev channel ? sorry but i didn't get it what do you actually mean by that.
and what do you actually want me to do?
i am fairly new in this so please co-operate. thanks.

**Comment by zoechi** [comment]
There are `beta`, `dev`, and `master` channel where `master` contains all merged features and fixes and a `dev` release is created after extensive testing and then eventually a `beta` release.
So this is some levels of stability. 
Using `flutter channel dev` `flutter doctor` switches to `dev` channel and you can switch back to beta using `flutter channel beta` `flutter doctor`.
This way you can check if this is still an issue in recent versions. `0.5.1` is more than 6 weeks old AFAIK.

**Comment by VickySalunkhe** [comment]
i switched to dev channel thanks for the explanation @zoechi 

But the issue is same .
attaching flutter doctor

> D:\Vicky\Work\Flutter Test Apps\testing\test4>flutter doctor -v
> [√] Flutter (Channel dev, v0.5.6, on Microsoft Windows [Version 6.1.7601], locale en-IN)
>     • Flutter version 0.5.6 at D:\Vicky\flutter_windows_v0.4.4-beta
>     • Framework revision 472bbccf75 (2 weeks ago), 2018-06-26 17:01:46 -0700
>     • Engine revision 6fe748490d
>     • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2
> 
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
>     • Android SDK at C:\Users\vicky\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.1)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 26.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
> 
> [√] VS Code, 64-bit edition (version 1.25.0)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.15.0
> 
> [√] Connected devices (1 available)
>     • Redmi Note 4 • 9441dce20803 • android-arm64 • Android 7.0 (API 24)
> 
> • No issues found!


I want behaviour of form similiar to this.
Example video is from Flutter gallery app.

[video here](https://drive.google.com/open?id=16nRkpgBb5Azo6N83cageTT5J7TlO2iwX)

**Comment by zoechi** [comment]
@VickySalunkhe thanks for checking 👍

**Comment by VickySalunkhe** [comment]
sir is there any problem with the form being kept in the tab bar view?

**Comment by zoechi** [comment]
I don't know details. Someone else will need to have a closer look.

**Comment by jaggerwang** [comment]
Same problem, occurred after switch to dev channel.

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by minhtrietbkit** [comment]
My also is the same with widget hierarchy:

... ListView > Custom built widget or other widgets (ex. Card) > Text View

My ListView is **indefinitely long, when the user scrolls down, it requests from server more data and fill them in (like Facebook)**. What want to allow users type comment right on the listview like Facebook UI. However, textfields do not scroll into view when the keyboard shows up. 

I have tried all `dev`, `master` and `beta` branch but the problem persists.

This is a snapshot of my application

1. Before tapping text field
![no_keyboard](https://user-images.githubusercontent.com/31511019/44297739-dbeefc00-a300-11e8-9cff-3dab8512c659.png)

1. After tapping text field
![with_keyboard](https://user-images.githubusercontent.com/31511019/44297742-e4dfcd80-a300-11e8-9f06-9dd820d368ca.png)

Could you please tell me where to track the progress of this issue? Many thanks!

**Comment by VickySalunkhe** [comment]
@minhtrietbkit 

try this
https://www.didierboelens.com/2018/04/hint-4-ensure-a-textfield-or-textformfield-is-visible-in-the-viewport-when-has-the-focus/

using focus node and this library textfields are coming back to focus. / above keyboard.

this is just a work around. but it works.

**Comment by zoechi** [comment]
What is the latest Flutter version you tried with?

**Comment by josvos** [comment]
The `resizeToAvoidBottomPadding` in the `Scaffold` is the source of the problem, see my issue #24856 and the comments there.

**Comment by mrzasoltani** [comment]
> The `resizeToAvoidBottomPadding` in the `Scaffold` is the source of the problem, see my issue #24856 and the comments there.

Brief and useful

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by devaziz0** [comment]
I found this solution to be useful and clear, I had the same problem and it solved the issue to me, I hope it would be helpful to you.
https://github.com/flutter/flutter/issues/24856#issuecomment-509780567
