### ISSUE TITLE
How to disable Flutter crash log uploads to Google

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#19304]
I have tried the solution from https://groups.google.com/forum/#!topic/flutter-dev/M_WZJPDmehA
but whenever Flutter crashes I get this in the log in Android Studio:

```
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: XXXXXXXXXX)
Crash report written to /XXXXXXXXXX/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

In the terminal I run the command `flutter config --no-analytics` and it says analytics is disabled:
```
> flutter config --no-analytics
Analytics reporting disabled.
```

Then to verify I run `flutter config` to verify it says "Analytics reporting is currently disabled.":
 
```
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve
Flutter tools over time. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Usage: flutter config [arguments]
-h, --help                      Print this usage information.
    --[no-]analytics            Enable or disable reporting anonymously tool usage statistics and crash reports.
    --clear-ios-signing-cert    Clear the saved development certificate choice used to sign apps for iOS device deployment.
    --gradle-dir                The gradle install directory.
    --android-sdk               The Android SDK directory.
    --android-studio-dir        The Android Studio install directory.

Run "flutter help" to see global options.
Analytics reporting is currently disabled.
```

But then, crash reports are still uploaded in Android Studio and when using the command line tools.

Using `flutter` with the `--suppress-analytics` flag in the command line works, but only if I use the command-line tools.

Edit: Is this because https://github.com/flutter/flutter/blob/09276bea258737e11b109e227f70eac94a4e1691/packages/flutter_tools/lib/src/usage.dart is not reading from the config?

**Comment by keithmorgan** [comment]
how can i fix this 

`CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 90c51fd53df122d1)
CreateProcessW failed 193
CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\to the moon\AppData\Local\Android\sdk\platform-tools\adb.EXE devices -l
`

**Comment by zoechi** [comment]
@keithmorgan probably  #21391

**Comment by naveenaa** [comment]
Is there a way to set permissions in AndroidManifest.xml to prevent crash reporting to google? Please provide a reply. Thanks

**Comment by blasten** [comment]
This is fixed on master.
