### ISSUE TITLE
Two Tabs are nested, and a bug appears.

### ISSUE THREAD

**Issue by shifeng1993** [flutter/flutter#19302]
Hello, I had a problem with the layout using flutter。

My application in root widget has three tabs
https://github.com/shifeng1993/easy-music-flutter/blob/master/lib/pages/home_screen/HomeScreen.dart#L37

Include three child tabs in one of the tabs
https://github.com/shifeng1993/easy-music-flutter/blob/master/lib/pages/find_screen/FindScreen.dart#L34

Then when I was sliding left and right, I found that the tabs from the child level could not be slid into the parent tab. This is a bug.

React-navigation was originally nested between two tabnavigation will be frozen, but the latest V2 has been fixed, I do not know when the flutter fix.

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
