### ISSUE TITLE
No host specified in URI file:///

### ISSUE THREAD

**Issue by skeksk91** [flutter/flutter#19309]
Luckily, it is fine with exception. It works still ok, but 
"No host specified in URI file:///" meaning not clear to me,
Because I tried to http://

It happens only when the first app startups after build,
after then hot reloading is fine.

```
    // This is how http calls are done in flutter:
    HttpClient http = new HttpClient();
    try {
      // Use darts Uri builder
      var uri = new Uri.http('dog.ceo', '/api/breeds/image/random');
      var request = await http.getUrl(uri);
      var response = await request.close();
      var responseBody = await response.transform(UTF8.decoder).join();
      var json = JSON.decode(responseBody);
      // The dog.ceo API returns a JSON object with a property
      // called 'message', which actually is the URL.
      var url = json['message'];
      imageUrl = url;
    } catch (exception) {
      print(exception);
    }
```

```
exception message is 
I/flutter ( 3671): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter ( 3671): The following ArgumentError was thrown resolving an image codec:
I/flutter ( 3671): Invalid argument(s): No host specified in URI file:///
I/flutter ( 3671): 
I/flutter ( 3671): When the exception was thrown, this was the stack:
I/flutter ( 3671): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2093:9)
I/flutter ( 3671): #1      _HttpClient.getUrl (dart:_http/http_impl.dart:2028:48)
I/flutter ( 3671): #2      NetworkImage._loadAsync (package:flutter/src/painting/image_provider.dart:440:57)
I/flutter ( 3671): <asynchronous suspension>
I/flutter ( 3671): #3      NetworkImage.load (package:flutter/src/painting/image_provider.dart:425:14)
I/flutter ( 3671): #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
I/flutter ( 3671): #5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
I/flutter ( 3671): #6      ImageProvider.resolve.<anonymous closure> 
...
...
...
I/flutter ( 3671): #154    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3671): #155    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 3671): (elided one frame from package dart:async)
I/flutter ( 3671): 
I/flutter ( 3671): Image provider: NetworkImage("", scale: 1.0)
I/flutter ( 3671): Image key: NetworkImage("", scale: 1.0)
```

**Comment by zoechi** [comment]
Have you tried
```dart
var uri = new Uri.http('dog.ceo', '/api/breeds/image/random');
print(uri); 
```
if this leads to the expected URI?

**Comment by skeksk91** [comment]
![screenshot from 2018-07-12 22-14-15](https://user-images.githubusercontent.com/4088583/42635433-ff550632-8620-11e8-90dd-87a27181ec8b.png)

**Comment by zoechi** [comment]
You need to use the debug icon 
![image](https://user-images.githubusercontent.com/405837/42639716-01353dd0-85f1-11e8-80c4-a0d7457b348b.png)
It looks you used the run icon instead. This one doesn't start the debugger.

**Comment by skeksk91** [comment]
It was caused from 
      - image: new NetworkImage(renderUrl ?? ''), 
When argument is null..
I think it is adequate exception :) 
Thank you for your kind response!

**Comment by WyyNever** [comment]
How do you solve this anomaly, I also encountered

**Comment by johnvarg** [comment]
i get the same error too...
flutter: Invalid argument(s): No host specified in URI file:///

How did you solve this issue?

**Comment by vikram94** [comment]
Has this issue been resolved or not?? Please help getting the same error

**Comment by u9520107** [comment]
This is because the app tries to get renderUrl asynchronously. Before the render Url is fetched back, it is null.
NetworkImage(renderUrl ?? '') then tries to use empty string as the url and result in the exception.
I am not sure if this is the best solution, but this seems to work:
```dart
  Widget get dogImage {
    return renderUrl == null ?
      Container() :
      Container(
        width: 100.0,
        height: 100.0,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          image: DecorationImage(
            fit: BoxFit.cover,
            image: NetworkImage(renderUrl),
          ),
        ),
      );
  }
```

I am very new to dart and flutter, so perhaps there are better ways to do this.

**Comment by madrara** [comment]
Anyone who has solved the above challenge....please share

**Comment by alvaroreis** [comment]
I decided to check if the image url was empty before putting it in the widget:
```
CircleAvatar(
backgroundColor: Colors.grey,
backgroundImage: _urlImage.isNotEmpty
? NetworkImage(_urlImagem)
: null,
),
```

**Comment by k1ycee** [comment]
try adding 'https://' to the uri it worked for me

**Comment by AnassErraidi** [comment]
hello world
thank you for your comment thats help to resolve the situation that how to know if the image is loaded or not hope that help 

I use a StatefulWidget
need a editing depend on your AffichScreen

situation : 
 -i have an url that i enter 
 -if url is correct affich the image if not affich an icon
 -if empty affich a Text()
 -precacheImage check if the url is correct if not give an error and change _loadingimage(bool) to false to affich the icon eror

bool _loadingimage;
ImageProvider _image;
Image _imagescreen;

@override
  void initState() {
    _loadingimage = true;
    _imageUrlfocusNode.addListener(_updateImageUrl);
    super.initState();
  }
  
   @override
  void dispose() {
    _imageUrlfocusNode.removeListener(_updateImageUrl);
    _quantityfocusNode.dispose();
    _imageUrlConroller.dispose();
    _imageUrlfocusNode.dispose();
    super.dispose();
  }

  void _updateImageUrl() {
    setState(() {
      _image = NetworkImage(_imageUrlConroller.text);
    });
    if (!_imageUrlfocusNode.hasFocus) {
      if (_imageUrlConroller.text.isNotEmpty) {
        setState(() {
          loadimage();
        });
      }
    }
  }
  
  void loadimage() {
    _loadingimage = true;
    precacheImage(_image, context, onError: (e, stackTrace) {
      // log.fine('Image ${widget.url} failed to load with error $e.');
      print('error $e');
      setState(() {
        _loadingimage = false;
        print(_loadingimage);
      });
    });
    if (_loadingimage == true) {
      _imagescreen = Image.network(
        _imageUrlConroller.text,
        fit: BoxFit.fill,
      );
    }
  }
  
  
  
  Container(
                              width: 100,
                              height: 100,
                              margin: EdgeInsets.only(top: 13, right: 11),
                              decoration: BoxDecoration(
                                border: Border.all(
                                  width: 1,
                                  color: Colors.grey,
                                ),
                              ),
                              child:_imageUrlConroller.text.isEmpty
                                      ? Text('enter an url')
                                      : !_loadingimage
                                          ? Container(
                                              child: Icon(Icons.add_a_photo),
                                            )
                                          : Container(
                                              child: _imagescreen,
                                            ),
                            ),
  
  
see you

**Comment by AnassErraidi** [comment]
hello world
thank you for your comment thats help to resolve the situation that how to know if the image is loaded or not hope that help 

I use a StatefulWidget
need a editing depend on your AffichScreen

situation : 
 -i have an url that i enter 
 -if url is correct affich the image if not affich an icon
 -if empty affich a Text()
 -precacheImage check if the url is correct if not give an error and change _loadingimage(bool) to false to affich the icon eror

bool _loadingimage;
ImageProvider _image;
Image _imagescreen;

@override
  void initState() {
    _loadingimage = true;
    _imageUrlfocusNode.addListener(_updateImageUrl);
    super.initState();
  }
  
   @override
  void dispose() {
    _imageUrlfocusNode.removeListener(_updateImageUrl);
    _quantityfocusNode.dispose();
    _imageUrlConroller.dispose();
    _imageUrlfocusNode.dispose();
    super.dispose();
  }

  void _updateImageUrl() {
    setState(() {
      _image = NetworkImage(_imageUrlConroller.text);
    });
    if (!_imageUrlfocusNode.hasFocus) {
      if (_imageUrlConroller.text.isNotEmpty) {
        setState(() {
          loadimage();
        });
      }
    }
  }
  
  void loadimage() {
    _loadingimage = true;
    precacheImage(_image, context, onError: (e, stackTrace) {
      // log.fine('Image ${widget.url} failed to load with error $e.');
      print('error $e');
      setState(() {
        _loadingimage = false;
        print(_loadingimage);
      });
    });
    if (_loadingimage == true) {
      _imagescreen = Image.network(
        _imageUrlConroller.text,
        fit: BoxFit.fill,
      );
    }
  }
  
  
  
  Container(
                              width: 100,
                              height: 100,
                              margin: EdgeInsets.only(top: 13, right: 11),
                              decoration: BoxDecoration(
                                border: Border.all(
                                  width: 1,
                                  color: Colors.grey,
                                ),
                              ),
                              child:_imageUrlConroller.text.isEmpty
                                      ? Text('enter an url')
                                      : !_loadingimage
                                          ? Container(
                                              child: Icon(Icons.add_a_photo),
                                            )
                                          : Container(
                                              child: _imagescreen,
                                            ),
                            ),
  
  
see you

**Comment by shunjid** [comment]
> try adding 'https://' to the uri it worked for me

saved life :heart:

**Comment by daraxdray** [comment]
> Anyone who has solved the above challenge....please share

Check your API URL and ensure you add or append 'http://' to it as the initials.....example is http://....api_url....

**Comment by codeslash21** [comment]
> > try adding 'https://' to the uri it worked for me
> 
> saved life ❤️

Yes, this solution worked for me. Thanks.

**Comment by codeslash21** [comment]
I also faced the same issue but solved it. 

- Add `https://` before your uri 
Hope this works.
