### ISSUE TITLE
Crash when showPerformanceOverlay is true on Nexus 9 tablet

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1931]
Add showPerformanceOverlay: true to the basic starter app and you get an engine crash.

This is a tablet bug, it does not repro on phones and other devices I've tried.

    [Android] I/flutter : -- EXCEPTION CAUGHT BY RENDERING LIBRARY -------------------------------
    [Android] I/flutter : The following exception was raised during performLayout():
    [Android] I/flutter : BoxConstraints has both a negative minimum width and a negative minimum height.
    [Android] I/flutter : BoxConstraints(w=-191322756.0, h=-191322752.0; NOT NORMALIZED)
    [Android] I/flutter : The following RenderObject was being processed when the exception was fired:
    [Android] I/flutter : RenderView NEEDS-LAYOUT
    [Android] I/flutter : This RenderObject had the following owner:
    [Android] I/flutter : [root]
    [Android] I/flutter : This RenderObject had the following descendants (showing up to depth 5):
    [Android] I/flutter :   RenderCustomPaint NEEDS-LAYOUT
    [Android] I/flutter :     RenderStack NEEDS-LAYOUT
    [Android] I/flutter :       RenderStack NEEDS-LAYOUT
    [Android] I/flutter :         RenderIgnorePointer NEEDS-LAYOUT
    [Android] I/flutter :           RenderSemanticAnnotations NEEDS-LAYOUT
    [Android] I/flutter :         RenderSemanticAnnotations NEEDS-LAYOUT
    [Android] I/flutter :           RenderRepaintBoundary NEEDS-LAYOUT
    [Android] I/flutter :       RenderPerformanceOverlay NEEDS-LAYOUT
    [Android] I/flutter : Stack trace:
    [Android] I/flutter : #0      BoxConstraints.debugAssertIsNormalized.<anonymous closure> (packages/flutter/src/rendering/box.dart:296)
    [Android] I/flutter : #1      BoxConstraints.debugAssertIsNormalized (packages/flutter/src/rendering/box.dart:294)
    [Android] I/flutter : #2      RenderObject.layout (packages/flutter/src/rendering/object.dart:982)
    [Android] I/flutter : #3      RenderView.performLayout (packages/flutter/src/rendering/view.dart:96)
    [Android] I/flutter : #4      RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:944)
    [Android] I/flutter : #5      RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:922)
    [Android] I/flutter : #6      BindingBase&Scheduler&Gesturer&MojoShell&Renderer.beginFrame (packages/flutter/src/rendering/binding.dart:83)
    [Android] I/flutter : #7      WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:95)
    [Android] I/flutter : #8      WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:160)
    [Android] I/flutter : #9      runApp (packages/flutter/src/widgets/binding.dart:166)
    [Android] I/flutter : #10     main (/Users/jackson/flutter/perf/lib/main.dart:4)
    [Android] I/flutter : #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
    [Android] I/flutter : #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
    [Android] I/flutter : ------------------------------------------------------------------------
    [Android] I/flutter : Another exception was raised: 'packages/flutter/src/rendering/object.dart': Failed assertion: line 1349: '!_needsLayout' is not true.
    [Android] --------- beginning of crash
    [Android] F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 7500 (gpu_thread)
    [Android] F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    [Android] F/DEBUG   : Build fingerprint: 'google/volantis/flounder:6.0.1/MMB29V/2554798:user/release-keys'
    [Android] F/DEBUG   : Revision: '0'
    [Android] F/DEBUG   : ABI: 'arm'
    [Android] F/DEBUG   : pid: 7469, tid: 7500, name: gpu_thread  >>> com.example.perf <<<
    [Android] F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
    [Android] F/DEBUG   :     r0 50000000  r1 e023880c  r2 00000000  r3 e0289ae0
    [Android] F/DEBUG   :     r4 ab89df08  r5 ab69d750  r6 0000000f  r7 e02a4800
    [Android] F/DEBUG   :     r8 ea88bc30  r9 e026a000  sl 00000000  fp ffffedf0
    [Android] F/DEBUG   :     ip ab932f08  sp ef6910e8  lr df945008  pc e9dd091e  cpsr 600d0030
    [Android] F/DEBUG   : 
    [Android] F/DEBUG   : backtrace:
    [Android] F/DEBUG   :     #00 pc 0085a91e  /vendor/lib/libglcore.so
    [Android] F/DEBUG   :     #01 pc 0085afed  /vendor/lib/libglcore.so
    [Android] F/DEBUG   :     #02 pc 0087e57f  /vendor/lib/libglcore.so
    [Android] F/DEBUG   :     #03 pc 0085ec17  /vendor/lib/libglcore.so
    [Android] F/DEBUG   :     #04 pc 00230855  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #05 pc 00205f9b  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #06 pc 002056e3  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #07 pc 00201ca9  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #08 pc 00201f09  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #09 pc 000ae363  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #10 pc 002e3d65  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #11 pc 002b347f  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #12 pc 002b300b  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #13 pc 002b2aa9  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #14 pc 002b2c8b  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #15 pc 002b2cdb  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #16 pc 000d8435  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #17 pc 000d93c5  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #18 pc 000d9629  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #19 pc 000d970f  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #20 pc 000be46d  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #21 pc 000baa51  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #22 pc 000c4e15  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #23 pc 000c42fd  /data/app/com.example.perf-1/lib/arm/libsky_shell.so
    [Android] F/DEBUG   :     #24 pc 000415af  /system/lib/libc.so (__pthread_start(void*)+30)
    [Android] F/DEBUG   :     #25 pc 0001918b  /system/lib/libc.so (__start_thread+6)
    [Android] F/DEBUG   : 
    [Android] F/DEBUG   : Tombstone written to: /data/tombstones/tombstone_02

**Comment by abarth** [comment]
Looks like a Skia bug.  Filed: https://bugs.chromium.org/p/skia/issues/detail?id=4958

**Comment by Hixie** [comment]
The assertion in Dart might be related but is in any case rather worrying itself.

**Comment by abarth** [comment]
The Dart assert appears to be gone at HEAD.

**Comment by Hixie** [comment]
Do we know why? I don't think anything changed in relevant code between the time I made the assert have all that detail and now.

**Comment by abarth** [comment]
Maybe I should be more precise and say that I wasn't able to reproduce the Dart assert.
