### ISSUE TITLE
Feature Request: Option to show example code in all examples in the Flutter Gallery App

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#19315]
I browse the Flutter Gallery app to find working examples of code I would like to use. It would be nice to be able to see what code created the example, minus the boilerplate if possible, right from the app. I've seen a few places where that was there, but it allows learning on the go and quicker development.

**Comment by zoechi** [comment]
Perhaps a link to GitHub would do. This would open Chrome and show the directory that contains the source.

**Comment by ThinkDigitalRepair** [comment]
Works for me!

**Comment by TahaTesser** [comment]
Hi @zoechi 
You can now see code examples in new gallery https://gallery.flutter.dev/#/demo/bottom-navigation 
if you disagree please write in the comments and I will reopen it
 Thank you
