### ISSUE TITLE
How to fade in/out a widget from SliverAppBar while scrolling?

### ISSUE THREAD

**Issue by nesscx** [flutter/flutter#19324]
I want to 'fade in' and 'fade out' a widget from SliverAppBar when user scrolls on the screen. This is an example of what I want to do:
<p align="center">
  <img src="https://user-images.githubusercontent.com/16904145/42661073-1780701e-85fb-11e8-9a74-d350086bcc32.gif" width="400" />
</p>

Here is my code without 'fading': https://gist.github.com/nesscx/721cd823350848e3d594ba95df68a7fa

**Comment by zoechi** [comment]
I think this would be a great StackOverflow question.

**Comment by nesscx** [comment]
https://stackoverflow.com/questions/51321804/how-to-fade-in-out-a-widget-from-sliverappbar-while-scrolling
