### ISSUE TITLE
Firebase database.reference(), static problem

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19334]
I tried to use database.reference() in global context of build() method, but it occurred error "Only static members can be accessed in intializers". So I read a code and realized instance of FirebaseDatabase is a static member, but what I'm curious is below code.

```
class _HomeState extends State<Home> {

	final FirebaseDatabase database = FirebaseDatabase.instance;
	DatabaseReference databaseReference = database.reference().child("haram");

	@override
  void initState() {
    // TODO: implement initState
    super.initState();
    databaseReference  = database.reference().child("haram");
  }



  @override
  Widget build(BuildContext context) {
    return Scaffold(
	    appBar: AppBar(
		    title: Text("Community Board"),
		    centerTitle: true,
		    backgroundColor: Colors.deepOrange,
	    ),
	    body: ,
    );
  }
}
```

My question is this. Why database.reference() is valid in initState() method? Thank you for ur helping

**Comment by zoechi** [comment]
> in global context of build() method

What does that mean. Can you please post the code you tried and the exact error message?

Why would it not be valid? I's valid everywhere where any statements are valid.

I think this kind of question is a better fit for https://gitter.im/flutter/flutter or https://stackoverflow.com/questions/tagged/flutter

**Comment by baeharam** [comment]
@zoechi Sorry for my weak knowledge about flutter, it was solved

**Comment by zoechi** [comment]
Glad to hear. I guess it's ok to close then.
