### ISSUE TITLE
assert home == null || !routes.containsKey(Navigator.defaultRouteName)

### ISSUE THREAD

**Issue by arsensaruhanyan2611** [flutter/flutter#19339]
## Steps to Reproduce
I think it's problem in 2 files: [app.dart](https://github.com/arsensaruhanyan2611/TravelMet-Flutter/blob/master/app.dart) and [login_page.dart](https://github.com/arsensaruhanyan2611/TravelMet-Flutter/blob/master/login_page.dart)

1. Some exceptions started after using Google Sign in Template (Deleted it because of I want to solve it after all another problems), so, may be this could help
2. As I understand this is because I try to navigate from LoginPage to HomePage, whose are marked as possible routes in app.dart. So, look at the code (It's too big, don't want to insert it here).
3. After compiling and running it on smartphone I get exception (more in logs)

P.S. Google Sign in always threw an exception "Missing Plugin Exception". Like [here #14137](https://github.com/flutter/flutter/issues/14137)

## Logs

```
Launching lib/main.dart on SM A520F in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (30785): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30785): The following assertion was thrown building TravelMetApp(dirty):
I/flutter (30785): If the home property is specified, the routes table cannot include an entry for "/", since it would
I/flutter (30785): be redundant.
I/flutter (30785): 'package:flutter/src/material/app.dart': Failed assertion: line 109 pos 10: 'home == null ||
I/flutter (30785):          !routes.containsKey(Navigator.defaultRouteName)'
I/flutter (30785):
I/flutter (30785): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30785): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30785): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30785):   https://github.com/flutter/flutter/issues/new
I/flutter (30785):
I/flutter (30785): When the exception was thrown, this was the stack:
I/flutter (30785): #2      new MaterialApp (package:flutter/src/material/app.dart)
I/flutter (30785): #3      TravelMetApp.build (file:///home/anyan/VS%20Code%20Projects/Flutter%20Projects/travelmet/lib/app.dart:8:16)
I/flutter (30785): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3708:28)
I/flutter (30785): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3655:15)
I/flutter (30785): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (30785): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (30785): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (30785): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (30785): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (30785): #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (30785): #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (30785): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (30785): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (30785): #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (30785): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (30785): #17     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (30785): #18     main (file:///home/anyan/VS%20Code%20Projects/Flutter%20Projects/travelmet/lib/main.dart:4:16)
I/flutter (30785): #19     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (30785): #20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (30785): (elided 2 frames from class _AssertionError)
I/flutter (30785): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/libGLESv2(30785): STS_GLApi : DTS, ODTC are not allowed for Package : com.example.travelmet
Application finished.

```

Can't do that because "Command not found" (even if I have it in $PATH).

So, only flutter doctor (without -v)

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.6, on Linux, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.0)
[!] Connected devices
    ! No devices available
```

yeah, I'm sorry, but I just can not do anything else (Here I used command from VSCode)
Also, I'm working on Ubuntu 16.04.

**Comment by zoechi** [comment]
I think it's caused by https://github.com/arsensaruhanyan2611/TravelMet-Flutter/blob/master/app.dart#L21

https://docs.flutter.io/flutter/material/MaterialApp/onGenerateRoute.html says

> If this returns null when building the routes to handle the specified initialRoute, then all the routes are discarded and Navigator.defaultRouteName is used instead (/). See initialRoute.

This is what the error message says is not allowed. If `home:` is provided no route `/` must exist.

**Comment by arsensaruhanyan2611** [comment]
No, I don't understand :( Can you please explain?..

**Comment by zoechi** [comment]
Sorry, don't have deep understanding here myself yet. 
Just checked the docs and that looked related.

**Comment by arsensaruhanyan2611** [comment]
Okay, then I'll try to do something else (or literally wait for somebody else). But in any case, thanks for the help.

**Comment by arsensaruhanyan2611** [comment]
@zoechi oh, I'm sorry, I forgot to change name

**Comment by arsensaruhanyan2611** [comment]
Apparently the compiler realized that it's impossible to just start the application without spending extra time. No, seriously, I deleted Google Sign-in from the list of dependencies 6 hours ago and here it is like nothing happened with lib.
[imgur](https://imgur.com/a/ckQkpas)

P.S. Sorry for cyrillic. A red block with exception is "An exception occurred", block with hashcode, runtimeType and message is "Variables" and the last block on the right place is "Call stack".

**Comment by zoechi** [comment]
> ```
> (30785): If the home property is specified, the routes table cannot include an entry for "/", since it would
> ```

The error message actually tells what is wrong. If `home` is set there can't also be a `"/"` route.

There is another issue about removing plugins not updating some files properly.

I'm going to close as working as intended.

Feels free to add a comment to have it reopened if you disagree
or create a new issue.
