### ISSUE TITLE
did TextField has deleteBackward method like iOS?

### ISSUE THREAD

**Issue by jiangjh** [flutter/flutter#19335]

**Comment by HansMuller** [comment]
Not really sure what you're asking for. Maybe support for clearing the textfield like https://master-docs-flutter-io.firebaseapp.com/flutter/cupertino/CupertinoTextField/clearButtonMode.html ?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
