### ISSUE TITLE
Navigator doesn't work from initState()

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#19330]
Using a Navigator from `initState()`, causes it to crash.

For example, the following code, will result in
```dart
   ...
  @override
  void initState() {
    super.initState();
    Navigator.pushReplacementNamed(context, '/home');  // This is the culprit
  }
```
This error - 

```
I/flutter (30816): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30816): The following assertion was thrown building Builder:
I/flutter (30816): setState() or markNeedsBuild() called during build.
I/flutter (30816): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (30816): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter (30816): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (30816): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (30816): Otherwise, the framework might not visit this widget during this build phase.
I/flutter (30816): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (30816):   Overlay-[LabeledGlobalKey<OverlayState>#c75f5](state: OverlayState#db278(entries:
I/flutter (30816):   [OverlayEntry#c188f(opaque: false; maintainState: false), OverlayEntry#70486(opaque: false;
I/flutter (30816):   maintainState: true), OverlayEntry#4ccb0(opaque: false; maintainState: false),
I/flutter (30816):   OverlayEntry#f1654(opaque: false; maintainState: true)]))
I/flutter (30816): The widget which was currently being built when the offending call was made was:
I/flutter (30816):   Builder
```

## Steps to Reproduce
Run this file inside a flutter application.
[main.dart](https://gist.github.com/devxpy/d2e1892567919d919930be8388cd0010#file-main-dart)

## Logs
[output.txt](https://gist.github.com/devxpy/d2e1892567919d919930be8388cd0010#file-output-txt)

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.utf8)
    • Flutter version 0.5.1 at /home/dev/Apps/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /home/dev/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Nexus 5 • 0553a8d90a662209 • android-arm • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by devxpy** [comment]
Something to note:

If I somehow delay the call to `pushReplacementNamed()`, then the application works fine.

```
import 'package:flutter/material.dart';
import 'dart:async';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyApp',
      initialRoute: '/',
      routes: {
        '/': (context) => LandingPage(),
        '/home': (context) => OtherPage(),
      },
    );
  }
}

class LandingPage extends StatefulWidget {
  @override
  LandingPageState createState() {
    return new LandingPageState();
  }
}

class LandingPageState extends State<LandingPage> {
  @override
  void initState() {
    super.initState();

    // The delay fixes it
    Future.delayed(Duration(milliseconds: 100)).then((_) {
      Navigator.pushReplacementNamed(context, '/home');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: CircularProgressIndicator(),
    );
  }
}

class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('other page'),
        ),
        body: Center(
          child: Text('other page content'),
        ));
  }
}
```

**Comment by Hixie** [comment]
The problem is that by the time you get to initState, the Navigator has already been built. If you tell it to build again, it can't really do anything useful: it's already been built this frame.

**Comment by devxpy** [comment]
Did you see my last comment z explaining how it doesn't throw an error when the call to push() is delayed?

**Comment by Hixie** [comment]
> Did you see my last comment explaining how it doesn't throw an error when the call to push() is delayed?

Right, if you do it not while we're building widgets, then it'll work fine. It'll be a bit weird in that there'll be one frame where the page before the one you pushed is interactive. The right solution is to push before you build the "background" page.

> Which is contradictory to

We build the widgets one by one going down the tree. The Navigator is above your widget, so it gets built first, but then we get to your widget, and it tells the navigator to do something new (to mark itself dirty). Since we're building the widgets for this frame already when initState runs, and since the Navigator has already been built, it's too late to go and update the Navigator to build something else (which we would need to do to put up another dialog).

**Comment by devxpy** [comment]
Thanks for the detailed explanation

**Comment by devxpy** [comment]
I believe this is the correct way?

```
bool _isAuthenticated = false;

void main() async {
  _isAuthenticated = await checkIfAuthenticated();
  print('app loaded!');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'secure pdf viewer',
      initialRoute: '/',
      onGenerateRoute: (RouteSettings settings) {
        switch (settings.name) {
          case '/':
            return MaterialPageRoute(builder: (_) {
              return _isAuthenticated ? BrowseScreen() : LoginScreen();
            });
          case '/login':
            return MaterialPageRoute(builder: (_) => LoginScreen());
          case '/browse':
            return MaterialPageRoute(builder: (_) => BrowseScreen());
        }
      },
    );
  }
}
```

**Comment by bubunyo** [comment]
if you look inside the internals of the Navigator widget, you will realize it is a stateful widget that calls `setState` when you call `pushReplacementNamed`. This is like calling setState inside initState. Since setstate builds the widget tree and initstate also does, it throws and error to avoid a race condition. The solution of calling it with a delay work because by the end of the delay, the widget tree would have been built.

**Comment by Hixie** [comment]
The solution is to do the decision as to what route to show _before_ the build method. Delaying isn't the solution as it causes a flash.

**Comment by bubunyo** [comment]
agreed, but trying to navigate away in `initState` is the first culprit. I don't know or understand why that will be in the first place, except a splash screen is being built.

**Comment by cubuspl42** [comment]
FFR: You can use `Navigator` from `didChangeDependencies`. It is guaranteed to be called for the first time immediately after `initState`. It's like with `InheritedWidget`.

**Comment by taojoe** [comment]
the following code is working.

@override
  void initState() {
    Future.microtask(dothings);
  }

**Comment by cubuspl42** [comment]
@taojoe I'd guess that this solution causes one frame delay, which sounds kind of acceptable, but also like a possible source of difficult to debug bugs
