### ISSUE TITLE
Support Android Studio 3.3 Stable

### ISSUE THREAD

**Issue by asaarnak** [flutter/flutter#19337]
Update flutter tooling and android templates to Gradle 4.9.

> https://androidstudio.googleblog.com/2018/07/android-studio-33-canary-3-available.html
Gradle compatibility: Android Gradle Plugin 3.3.0-alpha3 and higher now requires Gradle 4.9 RC1 or higher.

**Comment by asaarnak** [comment]
> https://androidstudio.googleblog.com/2018/09/android-studio-33-canary-10-available.html
The Android Gradle plugin now requires Gradle 4.10 or higher.

**Comment by neiljaywarner** [comment]
gentle bump since it's been a few months since last update, as we have 3.3 RC1 now and 3.4 is already at canary 6.

**Comment by zoechi** [comment]
Flutter uses Gradle 4.10.2, so this part is fixed.

Please create a new issue for Android Studio in https://github.com/flutter/flutter-intellij (if none exists yet)
