### ISSUE TITLE
Error with space in path to Android SDK 

### ISSUE THREAD

**Issue by multinucliated** [flutter/flutter#19359]
## Steps to Reproduce

1.I got the sdk from official website and try to run simple command "flutter doctor" in flutter_console.bat ,than I got this error : 

## Logs
```
D:\flutter>flutter
CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runSync (package:flutter_tools/src/base/process.dart:296)
#6      _runGit (package:flutter_tools/src/version.dart:449)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:64)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:170)
#14     new Usage (package:flutter_tools/src/usage.dart:26)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:76)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
#17     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
#20     Usage.instance (package:flutter_tools/src/usage.dart:52)
#21     flutterUsage (package:flutter_tools/src/usage.dart:20)
#22     _handleToolError (package:flutter_tools/runner.dart:113)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1126)
#26     _CustomZone.run (dart:async/zone.dart:1023)
#27     runZoned (dart:async/zone.dart:1501)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:50)
#31     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#32     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

D:\flutter>flutter doctor
CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
#2      Process.runSync (dart:io-patch/process_patch.dart:66)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
#5      runSync (package:flutter_tools/src/base/process.dart:296)
#6      _runGit (package:flutter_tools/src/version.dart:449)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:64)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:170)
#14     new Usage (package:flutter_tools/src/usage.dart:26)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:76)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
#17     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
#20     Usage.instance (package:flutter_tools/src/usage.dart:52)
#21     flutterUsage (package:flutter_tools/src/usage.dart:20)
#22     _handleToolError (package:flutter_tools/runner.dart:113)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1126)
#26     _CustomZone.run (dart:async/zone.dart:1023)
#27     runZoned (dart:async/zone.dart:1501)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:50)
#31     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#32     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

D:\flutter>
```

**Comment by darealSplendour** [comment]
same error here also

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by zoechi** [comment]
What command line shell are you using?
What output do you get if you execute `C:\Program Files\Git\cmd\git.EXE` in this shell?

**Comment by multinucliated** [comment]
Normal CMD . 

**OUTPUT:**
C:\Program Files\Git>git.exe
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Reapply commits on top of another base tip
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.

C:\Program Files\Git>

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Could you please try to delete the Flutter install directory and install Flutter again?

**Comment by zoechi** [comment]
Does your Windows user name contain a space?

**Comment by zoechi** [comment]
Are you using some non-standard shell?
Have you tried in powershell? Do you have the latest version of powershell installed?

**Comment by multinucliated** [comment]
Yes, tried in powershell also (as a admin too) .


\ANSHUL> Get-Host


Name             : ConsoleHost
Version          : 5.1.17134.165
InstanceId       : "some secret key"
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by FogelAO** [comment]
@zoechi 
Have the same issue, but if I run `C:\Program Files\Git\cmd\git.EXE` I got error message : `'C:\Program' is not recognized as an internal or external command,
operable program or batch file.`

But when I run `"C:\Program Files\Git\cmd\git.EXE"` all is fine, so could I change Flutter's command to "flutters_command" ?
Thanks

**Comment by zoechi** [comment]
Similar to #18938

**Comment by FogelAO** [comment]
@artcrespo , it will be fixed when it will be merged. When it will be merged - what is the question.

**Comment by philipjbousfield** [comment]
I have the same problem but different output. When I run flutter doctor I get:
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk" 2>nul | find "> bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale en-GB)
|CreateProcessW failed 2
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 652e65c9e22ba987)
\CreateProcessW failed 2 Crash report written to C:\Users\philb\flutter\flutter_01.log;
please let us know at https://g

**Comment by zoechi** [comment]
Similar to #18938

**Comment by cbracken** [comment]
Moving some recent discussion over from #9976 (older issue):

Potential issues involve tooling/Android SDK paths with spaces. We currently run all CI with spaces in the SDK path. Since we build the Gallery example (which is nested under the SDK), we're also covering the case where the user Flutter project directory contains a space.

Other issues I can imagine that AFAIK we don't test for in our CI, but probably should:

  * Space in Android SDK path
  * Space in Xcode path
  * Space in path of command-line tools such as ideviceinstaller, git, etc.

**Comment by Aishwarya1317** [comment]
Hello,
can any one help me with below error?
C:\src\flutter>flutter doctor
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale en-IN)
-CreateProcessW failed 2
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 4f22c8be3f4f8ba9)
\CreateProcessW failed 2                                                                                               Crash report written to C:\src\flutter\flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by zoechi** [comment]
@Aishwarya1317 sounds like you do not have Git installed.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Aishwarya1317** [comment]
@zoechi Thank you so much

**Comment by Aishwarya1317** [comment]
Does Flutter for web development has different way to install? 
can we use CDN for flutter?

**Comment by zoechi** [comment]
@Aishwarya1317 there is currently no Flutter for web development. When https://medium.com/flutter-io/hummingbird-building-flutter-for-the-web-e687c2a023a8 becomes available I assume it will be just part of Flutter.

**Comment by Aishwarya1317** [comment]
So then why it is said that flutter is also available for web development???

**Comment by zoechi** [comment]
@Aishwarya1317 where is it said? I only know of what the Medium article above says. It's work-in-progress.

**Comment by Aishwarya1317** [comment]
@zoechi  https://flutter.io/docs/get-started/flutter-for/web-devs here I found some code for html file. So I was confused...

**Comment by zoechi** [comment]
@Aishwarya1317 I see. It's just an initial guide for former web developers how to "think Flutter"

**Comment by Delocalized-electron** [comment]
> ## Steps to Reproduce
> 1.I got the sdk from official website and try to run simple command "flutter doctor" in flutter_console.bat ,than I got this error :
> 
> ## Logs
> ```
> D:\flutter>flutter
> CreateProcessW failed 193
> 
> CreateProcessW failed 193
> Unhandled exception:
> ProcessException: %1 is not a valid Win32 application.
> 
>   Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
> #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
> #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
> #2      Process.runSync (dart:io-patch/process_patch.dart:66)
> #3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
> #4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
> #5      runSync (package:flutter_tools/src/base/process.dart:296)
> #6      _runGit (package:flutter_tools/src/version.dart:449)
> #7      new FlutterVersion (package:flutter_tools/src/version.dart:23)
> #8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:64)
> #9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
> #10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
> #11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
> #12     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
> #13     FlutterVersion.instance (package:flutter_tools/src/version.dart:170)
> #14     new Usage (package:flutter_tools/src/usage.dart:26)
> #15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:76)
> #16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
> #17     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
> #18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
> #19     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
> #20     Usage.instance (package:flutter_tools/src/usage.dart:52)
> #21     flutterUsage (package:flutter_tools/src/usage.dart:20)
> #22     _handleToolError (package:flutter_tools/runner.dart:113)
> <asynchronous suspension>
> #23     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
> <asynchronous suspension>
> #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
> <asynchronous suspension>
> #25     _rootRun (dart:async/zone.dart:1126)
> #26     _CustomZone.run (dart:async/zone.dart:1023)
> #27     runZoned (dart:async/zone.dart:1501)
> #28     AppContext.run (package:flutter_tools/src/base/context.dart:141)
> <asynchronous suspension>
> #29     runInContext (package:flutter_tools/src/context_runner.dart:43)
> <asynchronous suspension>
> #30     run (package:flutter_tools/runner.dart:50)
> #31     main (package:flutter_tools/executable.dart:49)
> <asynchronous suspension>
> #32     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
> #33     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
> #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
> 
> D:\flutter>flutter doctor
> CreateProcessW failed 193
> 
> CreateProcessW failed 193
> Unhandled exception:
> ProcessException: %1 is not a valid Win32 application.
> 
>   Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
> #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:485)
> #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:631)
> #2      Process.runSync (dart:io-patch/process_patch.dart:66)
> #3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83)
> #4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:321)
> #5      runSync (package:flutter_tools/src/base/process.dart:296)
> #6      _runGit (package:flutter_tools/src/version.dart:449)
> #7      new FlutterVersion (package:flutter_tools/src/version.dart:23)
> #8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:64)
> #9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
> #10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
> #11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
> #12     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
> #13     FlutterVersion.instance (package:flutter_tools/src/version.dart:170)
> #14     new Usage (package:flutter_tools/src/usage.dart:26)
> #15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:76)
> #16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99)
> #17     _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/dart:collection/compact_hash.dart:277)
> #18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87)
> #19     AppContext.[] (package:flutter_tools/src/base/context.dart:114)
> #20     Usage.instance (package:flutter_tools/src/usage.dart:52)
> #21     flutterUsage (package:flutter_tools/src/usage.dart:20)
> #22     _handleToolError (package:flutter_tools/runner.dart:113)
> <asynchronous suspension>
> #23     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
> <asynchronous suspension>
> #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
> <asynchronous suspension>
> #25     _rootRun (dart:async/zone.dart:1126)
> #26     _CustomZone.run (dart:async/zone.dart:1023)
> #27     runZoned (dart:async/zone.dart:1501)
> #28     AppContext.run (package:flutter_tools/src/base/context.dart:141)
> <asynchronous suspension>
> #29     runInContext (package:flutter_tools/src/context_runner.dart:43)
> <asynchronous suspension>
> #30     run (package:flutter_tools/runner.dart:50)
> #31     main (package:flutter_tools/executable.dart:49)
> <asynchronous suspension>
> #32     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
> #33     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
> #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
> 
> D:\flutter>
> ```

I get the same error while running flutter doctor command

**Comment by golicen** [comment]
‘C:\Program Files\Git\cmd\git.EXE’  contain a space, replace the other path

**Comment by MeshkaniMohammad** [comment]
An interesting point: you should also change projects directory to as same as flutter directory.
If you don't you will get below error:
```ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\firstName lastName\projects\project\android\gradlew.bat -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:232:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:248:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37) ......
````

**Comment by epebojot** [comment]
Thanks! Finally solved

**Comment by blasten** [comment]
I think the temporary fix might be to set `runInShell: true` when we call `processManager.runSync`. 

According to this implementation: https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_patch.dart#L249-L250 and https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_patch.dart#L382-L383, all arguments that have a space will be surrender by double quotes `"`.  cc @zanderso

I couldn't come up with a test case that will cause the failure even if  `runInShell: false` and the path contains spaces. I tested on Windows 10 (cmd.exe and powershell).

**Comment by epebojot** [comment]
> I think the temporary fix might be to set `runInShell: true` when we call `processManager.runSync`.
> 
> According to this implementation: https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_patch.dart#L249-L250 and https://github.com/dart-lang/sdk/blob/master/runtime/bin/process_patch.dart#L382-L383, all arguments that have a space will be surrendered by double quotes. cc @zanderso
> 
> I couldn't come up with a test case that will cause the failure even if `runInShell: false` and the path contains spaces. I tested on Windows 10 (cmd.exe and powershell).

If you just have fixed the path without space, or fixed the env. Just try to use different terminal. For example, powershell instead of cmd, or any terninal. Try to restart your computer. These might be a bug.

**Comment by epebojot** [comment]
In short, flutter doctor act strange from different terminal. Try to restart your computer and execute the terminal in powershell

**Comment by epebojot** [comment]
> Thanks! Finally solved

It is already solved. make sure the path for has no space: 

For example: (has space)
C://sdk/has space/sdk

For example: (has no space)
C://sdk/hasnospace/sdk

execute flutter doctor in powershell(not in cmd)

You will see the different result now.

Make sure to follow the documentation correctly about the environment variable path.

Then execute flutter doctor in powershell.

If not fix yet. Restart your computer. And try to run flutter doctor from different terminal. 

I fixed mine by executing flutter syntax in powershell

**Comment by blasten** [comment]
This is fixed on master.

**Comment by zanderso** [comment]
It's looking like the fix for this in package:process is disagreeing with the fix that landed to the Dart SDK. Re-opening this issue for tracking until a stable resolution is in place.

**Comment by blasten** [comment]
Should we still keep this issue open @zanderso?

**Comment by zanderso** [comment]
Yes. The Dart SDK fix has rolled in, and it looks like things are resolved. Thanks!
