### ISSUE TITLE
Add a `closeUrlLauncher` method to package:url_launcher

### ISSUE THREAD

**Issue by thosakwe** [flutter/flutter#19357]
This issue is in relation to my comment on #357 (https://github.com/flutter/flutter/issues/357#issuecomment-404877612), and I plan on sending a PR for this (in fact, I'm about to start working on one).

In addition to `canLaunch` and `launch`, I 100% believe that the `url_launcher` package needs a way to close the launched URL, at least when running in a WebView.

In cases like OAuth or other single-sign on flows, once the user has signed in, there is currently no way to close the WebView opened by `launch`. Having this would be nice in such situations, because the user never has to leave the application get signed; plus, IMO this is low-hanging fruit and can be easily patched with a well-tested community PR.

Anyways, I'm not so sure exactly what the name of the function would be. `close` is far too common. `unLaunch` sounds decent at first, but is not so intuitive and might confuse non-native English speakers. `closeUrlLauncher` is long, but descriptive. I might stick with that, or `closeWebview`.

I'll get started on this ASAP.  It might take me a little bit of time, though, because I know just about zero Objective-C.

**Comment by thosakwe** [comment]
Android changes are done; preview them in this branch: https://github.com/thosakwe/plugins/tree/add-close-to-url-launcher

**Comment by alsocalledchris** [comment]
@thosakwe this seems great, any joy getting the pull request done - really want to use this functionality!

**Comment by naiveai** [comment]
Sorry for necro'ing this issue, but I just wanted to ask if there's been any progress on this... I'd be happy to help with this if anything's needed on Android at least.

**Comment by thosakwe** [comment]
Closing, as the feature has been added for a while now.
