### ISSUE TITLE
Landscape mode with hidden navigation bar overflows screen on tablets

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#19360]
I am writing an app primarily intended to be used in landscape mode. I calculate the height using 

    MediaQuery.of(context).size.height
The full screen height is correctly calculated, but on tablets where the navigation buttons (back, home, square) are hidden, the drawn parts throws an error.

    A RenderFlex overflowed by 28 pixels on the bottom.

The overflow exception would only be correct if the navigation bar was present.

**Comment by Rockvole** [comment]
![screenshot_20180713-150127](https://user-images.githubusercontent.com/4139576/42716903-b071179e-86b2-11e8-89a4-f777f417c0a4.png)

**Comment by Rockvole** [comment]
This has similarities to my other issue :
[Landscape mode with navigation buttons screen redraw on phones broken.](https://github.com/flutter/flutter/issues/19319)


This doesnt seem to be an issue on phones because phones keep the navigation bar on the short edge and it doesnt trigger the same problem.

My workaround for now is to leave a bunch of wasted space at the bottom of the screen on all devices. I cannot find a way to detect what edge the navigation bar is stuck to so that I could at least only have wasted space on tablets.

**Comment by Rockvole** [comment]
This is on a Nexus 9
https://github.com/flutter/flutter/issues/12310

[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.5.1 at /work/installs/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/david/Android/Sdk
    • Java binary at: /work/installs/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /work/installs/android-studio-3.0
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /work/installs/idea-IC-181.4445.78
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 181.4892.1
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by Rockvole** [comment]
I found a way to detect tablet sized screens, so I can have the black bar on tablets only.

    double shortestSide = MediaQuery.of(context).size.shortestSide;
    bool useMobileLayout = shortestSide < 600;
    double heightOffset=0.0;
    if(!useMobileLayout) heightOffset=48.0;
    double screenHeight = MediaQuery.of(context).size.height-heightOffset;

This is not ideal since I believe the majority of my users will use tablet sized devices.

**Comment by Rockvole** [comment]
I searched to find a way to permanently show the navigation bar for the entire app in flutter or android so that I wont just have dead space - but I could not see a way to do that.

**Comment by Rockvole** [comment]
https://github.com/flutter/flutter/issues/22063

**Comment by cbracken** [comment]
cc @GaryQian who's working on this issue.

**Comment by GaryQian** [comment]
You can try SystemChrome.setSystemUIOverlays(...) in system_chrome.dart. This should allow you to set UI elements such as nav bars. In addition, as copied from my response to https://github.com/flutter/flutter/issues/19319:

"flutter/engine#6288 in combination with flutter/engine#6282 should deal with this issue. We now use heuristics to "detect" the keyboard and hide the left/right nav bar as needed. Also we will soon provide a SystemChrome call to allow for restoration of previously set system UI (#22221 and flutter/engine#6322)"

**Comment by GaryQian** [comment]
Many of the changes to safe areas and UI overlays have been landed. Is this still an issue?

**Comment by Rockvole** [comment]
I tested it and it seems to work fine now.
The navigation bar appears as transparent with white buttons on the tablets I tried it on.

    Flutter (Channel master, v1.0.1-pre.2, on Linux, locale en_CA.UTF-8)

**Comment by THEJDEEP1** [comment]
Do we have support for 10 inch tablet? I am getting  this
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

**Comment by zoechi** [comment]
@THEJDEEP1 I think the problem is the CPU not the size factor. See #18494, #26369, #25506
