### ISSUE TITLE
How to get all the images from mobile?

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19368]
I tried to get all the images from mobile using image_picker package.
But it makes user pick only one image at a time. How to get all the images from mobile automatically?
What package or library use to achieve these kinid of things?

**Comment by ThinkDigitalRepair** [comment]
@baeharam For help, you want to ask on StackOverflow. This area is for errors in the Flutter SDK.

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/flutter_multiple_image_picker might do what you want.
If not you can extend on the source of that package and customize it to your needs.

**Comment by zoechi** [comment]
See also flutter/plugins#660

**Comment by baeharam** [comment]
@zoechi Thx for helping. But what I want is to bring all the images from user's device by one button click. Can't be possible?

**Comment by zoechi** [comment]
Perhaps https://pub.dartlang.org/packages/multi_image_picker

**Comment by zoechi** [comment]
Duplicate of #14098
