### ISSUE TITLE
firebase_storage does not auth?

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19361]
I have anonymous auth working.

```
Flutter: signed in! FirebaseUser({displayName: null, providerId: Firebase, uid: 6vj0tYIQsUSjsdiJfkjid37NhKk2, providerData: [], isEmailVerified: false, email: null, photoUrl: null, isAnonymous: true})
```

<img width="883" alt="screen shot 2018-07-13 at 7 01 44 pm" src="https://user-images.githubusercontent.com/666539/42717470-39085600-86cf-11e8-9e92-3d08322c050a.png">

And my rules are as follows

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

And I keep getting this error

<img width="1126" alt="screen shot 2018-07-13 at 7 02 38 pm" src="https://user-images.githubusercontent.com/666539/42717485-562be58a-86cf-11e8-8c6a-858c9976a773.png">

But if I change my rules to public

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}
```

It works!

<img width="738" alt="screen shot 2018-07-13 at 7 03 56 pm" src="https://user-images.githubusercontent.com/666539/42717507-8145ae4a-86cf-11e8-949d-0b3a5bfc8874.png">

Any ideas what's going on?

```
    this.user = await this.auth.signInAnonymously();
    print("signed in! $user");

    await _getAllSocialImageUrls();
    print("got socialUrls! $socialUrls");
```

**Comment by lukepighetti** [comment]
This is simpler than you'd think. If you login like this, it works. If you use the example provided by firebase_core, it breaks. 

https://github.com/flutter/plugins/blob/master/packages/firebase_core/example/lib/main.dart

```
    this.app = FirebaseApp(name: 'when-coin-test');
    this.user = await this.auth.signInAnonymously();
```

**Comment by ikasoumen** [comment]
Same problem with me. 
Does anyone know this issue caused from incorrect document or bug?

**Comment by ikasoumen** [comment]
I figured out how to solve this.

## Not Works
```not_works.dart
final FirebaseAuth auth = FirebaseAuth.instance;
final user = await auth.signInWithGoogle(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
 );
 
/// follow is firebase_storage's example code 
/// ref : https://github.com/flutter/plugins/blob/master/packages/firebase_storage/example/lib/main.dart
final FirebaseApp app = await FirebaseApp.configure(
  name: 'test',
  options: FirebaseOptions(
    ...
  ),
);
final FirebaseStorage storage = FirebaseStorage(
  app: app, storageBucket: '...');
```

## Works
```works.dart
final FirebaseAuth auth = FirebaseAuth.instance;
final user = await auth.signInWithGoogle(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
 );

final FirebaseStorage storage = FirebaseStorage.instance;
```

You should use same setup way as Auth. I cannot find this information in the docs, so I think needs to add about this in the documentation somewhere else.

**Comment by dklenowski** [comment]
Thanks @lukepighetti for the workaround, was having the same problem.

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/754. Any further collaboration will be done there.

**Comment by shikharvaish28** [comment]
I am trying to do the authentication from a non-default firebase app. For this, I tried doing

```
transport = await FirebaseApp.configure(
        name: 'transport_app',
        options: FirebaseOptions(
            googleAppID: '.......:android:............',
            apiKey: 'AI................................LFQwqk',
            projectID: '267282843470'));

    fire = FirebaseAuth.fromApp(transport);

 fire .signInWithCredential(phoneAuthCredential) .then((AuthResult value) async {
           // Some code
}

 await fire.verifyPhoneNumber(
        phoneNumber: "+91${widget.mobileNumber}",
        timeout: const Duration(seconds: 60),
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
  }
```

When  I tried doing this, I get the message as `The request contains malformed or mismatching credentials [ App ID does not match requested project. ]`. I am pretty sure that the credentials that I am using are correct. 

> You should use same setup way as Auth.

As @ikasoumen mentioned in his comment but, I am not able to find any other way than that of using `.configure`. Any suggestions would be really helpful!
