### ISSUE TITLE
Issue from website page Write Your First Flutter App

### ISSUE THREAD

**Issue by kozarbohdan** [flutter/flutter#19373]
From URL: https://flutter.io/get-started/codelab/

When using this code:
```dart
import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Welcome to Flutter',
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Welcome to Flutter'),
        ),
        body: new Center(
          child: new RandomWords(),
        ),
      ),
    );
  }
}

class RandomWords extends StatefulWidget {
  @override
  createState() => new RandomWordsState();
}

class RandomWordsState extends State<RandomWords> {
  @override
  Widget build(BuildContext context) {
    final wordPair = new WordPair.random();
    return (new Text(wordPair.asPascalCase));
  }
}
```

I have an issue. The app loads to device, but it is the standard widget with title "Welcome To Flutter" and text "Hello World" in the middle of the screen.

First I thought that i have missed something, but after copying the source, problem remained.

**Comment by joshuaalm** [comment]
A similar issue is seen when later we are told to "remove the Scaffold and AppBar references from MyApp" because the title and Scaffold are returned as part of Widget object from the build function.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2068](https://github.com/flutter/website/issues/2068) via [**ZenHub**](https://www.zenhub.com/)
