### ISSUE TITLE
Starting an iOS application in the simulator via Atom spawns mutliple lingering processes and pegs CPUs

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#1937]
![screen shot 2016-02-16 at 4 30 30 pm](https://cloud.githubusercontent.com/assets/44085/13096038/fe5d8cb8-d4ca-11e5-8772-f8b79d947f0a.png)

Steps to Reproduce:
* Launch `$FLUTTER_ROOT/examples/` in atom
* Start each application in the simulator by pressing the `Run` button.
* Iterate on a project (say `hello_world`) and press the `Run` button on each iteration.

**Comment by chinmaygarde** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
Can you attach the cli args to those processes (via `ps`?) I'm wondering what they're doing.

**Comment by chinmaygarde** [comment]
I believe this is one of the errant processes `/usr/local/opt/dart/libexec/bin/dart --ignore-unrecognized-flags --checked --pause_isolates_on_start --enable-vm-service:53914 --trace_service_pause_events /Volumes/Mojo/flutter/packages/flutter_tools/bin/flutter_tools.dart start`

**Comment by chinmaygarde** [comment]
Hmm. The application did not actually updated on device. Instead, the old version is being shown.

**Comment by devoncarew** [comment]
that looks a little odd. the debug args are being passed into the dart cli vm, not into the flutter_tools start command

**Comment by devoncarew** [comment]
It looks like the dart process that we're using to start the flutter tool is running w/ `--pause_isolates_on_start`. That won't work great :(

**Comment by chinmaygarde** [comment]
`ps -ef` for full results https://gist.github.com/chinmaygarde/5191f3bc7c9456333ea7

**Comment by chinmaygarde** [comment]
Same goes for errant `tail` processes

**Comment by devoncarew** [comment]
I'll make sure that we're passing the args correctly from atom.

**Comment by devoncarew** [comment]
@chinmaygarde, can you make sure that the plist ID thing isn't an issue here? Thanks!

**Comment by chinmaygarde** [comment]
I didn't see this issue today. So its safe to assume it was the plist ID bug. Closing.

**Comment by chinmaygarde** [comment]
This was happening on the machines of one of the hackathon attendees. Reopening.

**Comment by devoncarew** [comment]
It'd be great to know the platform, what shell they're using, and the cli args for the rouge processes.

**Comment by chinmaygarde** [comment]
I haven't seen this happen in the past few weeks. Will reopen with more information if I can reliably reproduce this.
