### ISSUE TITLE
Modify AnimatedSwitcher to better allow different in vs. out transitions

### ISSUE THREAD

**Issue by dalewking** [flutter/flutter#19395]
See this discussion I had with myself on flutter_dev: https://groups.google.com/forum/#!topic/flutter-dev/mTKt7qJaqBM

`AnimatedSwitcher` is designed to use a single animation for incoming items and the reversed animation for the outgoing items. But that is not always what is desired. For example, I might want to slide new items in from the left and slide the previous item out to the right.

It is not clear how to actually achieve that with `AnimatedSwitcher`. As you can see in that thread I spent a day of hacking and figured out how to make it work, but there should be a better, clearly defined way to accomplish this.

My thought is another optional `AnimatedSwitcherTransitionBuilder` parameter like `exitTransitionBuilder` that can be passed to `AnimatedSwitcher` that is only used on the exiting items. When that parameter is present the Animation should run in the forward direction (i.e. you would not reverse the animation controller for that item).

**Comment by chunhtai** [comment]
Having a different animation between child in and out might cause some unexpected behavior if we change the children really fast. The child, while is still transitioning in, gets kick to transition out. In the current behavior, the child will keep the current animation value and do the reverse. This make sense if the transition are the same, but you might see a suddenly jump due to different animation

Same animation Scale
![same-animation](https://user-images.githubusercontent.com/47866232/62963077-1de83c00-bdb5-11e9-9c28-d896cedab41b.gif)

Different animation Scale vs Fade
![different](https://user-images.githubusercontent.com/47866232/62963097-2771a400-bdb5-11e9-8b85-d333feffa1b6.gif)

It will jump even more if you have very different animations. I will need more clarification on what are the expected behaviors in this two cases to continue on this issue

**Comment by dalewking** [comment]
That is a concern but not one that should prevent allowing for the feature. It can be a note that this is a potential issue.

In my case I was actually looking to only animate the in, and not have any out animation. I have an item that is Swipeable (with a custom implementation that allows me to swipe in any direction) and then all I do is animate the new item in.

**Comment by chunhtai** [comment]
@dalewking 
If the use case to only do partial transition, I think allowing a different out transition builder that are kind of broken to be able to achieve your use case is not ideal. Besides, there is already a way to achieve this.

Here is a more polish version of it
```
transitionBuilder: (Widget child, Animation<double> animation) {
                switch (animation.status){
                  case AnimationStatus.completed:
                  case AnimationStatus.reverse:
                    // In reverse direction
                    return child;
                  case AnimationStatus.dismissed:
                  case AnimationStatus.forward:
                  return ScaleTransition(child: child, scale: animation);
                }
                return child;
              }
```

We will not change the api as this way of changing the animation is not recommended; however, we will document this behavior and add a test to guard against any change to the api.

**Comment by dalewking** [comment]
As I posted in the linked thread there is also some weirdness that the transition builder may or may not be called on the exiting item. If it is a lambda, it fails the equals check and will be called again, if it is a method reference it compares as equal and is not called again.

**Comment by chunhtai** [comment]
We proceed with the plan to not changing animatedswitcher. The reason being animatedswitcher is not really built for supporting different animations for transition in & out. It might create the risk of having broken animation, and that is against our [core values](https://github.com/flutter/flutter/wiki/Values) If you want to have special animation effect different from animatedswitcher, we suggest to build a custom animation widget to achieve the goal. 

let me know if you have trouble doing so, I am always happy to help.

**Comment by MichaelM97** [comment]
This can be achieved using the following custom `transitionBuilder`
```dart
transitionBuilder: (Widget child, Animation<double> animation) {
  if (child.key == ValueKey(index)) {
    return SlideTransition(
      position: Tween<Offset>(
        begin: Offset(1.0, 0),
        end: Offset(0.0, 0),
      ).animate(animation),
      child: child,
    );
  } else {
    return SlideTransition(
      position: Tween<Offset>(
        begin: Offset(-1.0, 0),
        end: Offset(0.0, 0),
      ).animate(animation),
      child: child,
    );
  }
}
```

Here's a more full example
```dart
class MyUI extends StatelessWidget {
}
```

**Comment by dalewking** [comment]
As I pointed out in the thread linked in that ticket that works IF you use
a lambda for defining the transition builder. If you move the transition
builder to a function it will not work due to the fact that they will
compare as equal. So it works but by accident.

At least that's what I remember but I have not looked at it in a long time.
