### ISSUE TITLE
Can't see icons 

### ISSUE THREAD

**Issue by misaelabanto** [flutter/flutter#19391]
Hello, I can't see the icons.
Android 7.1.2
Xiaomi Redmi Note 5A Prime
Screenshot [here](https://screenshot.net/189erbd)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
I think you are using an outdated Flutter version.

**Comment by misaelabanto** [comment]
I'm talking about the main app downloaded from Google Play Store.

**Comment by zoechi** [comment]
Dup of #17485
