### ISSUE TITLE
How to rotate an image around the center with canvas

### ISSUE THREAD

**Issue by netsmertia** [flutter/flutter#19396]
I am trying to implement image scaling and rotation with flutter canvas api using custom painter. The scale is achieved but unable to rotate the image on its center, the default rotate is on its top left corner. 

I have also tried to translate and rotate and translate back but no success.

The same questions is also asked on SO [here](https://stackoverflow.com/questions/51323233/flutter-how-to-rotate-an-image-around-the-center-with-canvas). here is my try [gist](https://gist.github.com/netsmertia/53170bf3a0b2e9fe7822d3786e00971a#file-imagescaleandrotate-dart-L98)

**Comment by BondarenkoStas** [comment]
Closing as SO answer is accepted https://stackoverflow.com/a/54336099/12268368
