### ISSUE TITLE
No application found for TargetPlatform.ios.

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#19398]
Launching lib/main.dart on iPhone 8 Plus in debug mode...
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
Exited (sigterm)

I want debug with VSCode whih existing project ，But It get this error, 
but ,I use XCODE is is work

**Comment by zoechi** [comment]
Please add the output of `flutter doctor`

**Comment by lichentao** [comment]
@zoechi  I have use flutter doctor ,not work

**Comment by lichentao** [comment]
botao-macbookpro:dmcompileflutter botao$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✗] Android Studio (not installed)
[✓] Connected devices (1 available)

**Comment by lichentao** [comment]
@zoechi  directory must be ios ? hou can i change ios project folder

**Comment by lichentao** [comment]
![image](https://user-images.githubusercontent.com/5095376/42756745-1ece6168-8930-11e8-8455-25c923edf811.png)
How Can I change the red(ios) folder to green(DMPortal) folder when I exe flutter run

**Comment by lichentao** [comment]
How Can I change the red(ios) folder to green(DMPortal) folder when I exe flutter run

![image](https://user-images.githubusercontent.com/5095376/42756832-5e4a5f36-8930-11e8-814a-3c52eb1b2a5c.png)

**Comment by zoechi** [comment]
@lichentao why do you need to change that folder?
I don't know if that is possible.

**Comment by lichentao** [comment]
@zoechi because I want debug with exisiting project not flutter create project

**Comment by lichentao** [comment]
evn I move project to ios always working

**Comment by lichentao** [comment]
[  +35 ms] [/Users/botao/Desktop/damai/flutter_ios/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/Users/botao/Desktop/damai/flutter_ios/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/Users/botao/Desktop/damai/flutter_ios/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/botao/Desktop/damai/flutter_ios/flutter/] git log -n 1 --pretty=format:%H
[  +27 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[        ] [/Users/botao/Desktop/damai/flutter_ios/flutter/] git log -n 1 --pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 weeks ago
[        ] [/Users/botao/Desktop/damai/flutter_ios/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +24 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.1-0-gc7ea3ca37
[+1264 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/test/' (OS Error: Permissiondenied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/phpmyadmin/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/mysql/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/performance_schema/' (OS Error: Permission denied, errno = 13)
[ +727 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +222 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +221 ms] /Users/botao/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/botao/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +7 ms] idevice_id -h
[ +306 ms] /usr/bin/xcrun simctl list --json devices
[ +265 ms] Found plugin mtop_plugin at /Users/botao/Desktop/damai/flutter_ios/dmcompileflutter/plugin/mtop_plugin/
[  +32 ms] Found plugin user_info at /Users/botao/Desktop/damai/flutter_ios/dmcompileflutter/plugin/user_info/
[  +36 ms] [/Users/botao/Desktop/damai/flutter_ios/dmcompileflutter/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project /Users/botao/Desktop/damai/flutter_ios/dmcompileflutter/ios/Runner.xcodeproj -target Runner -showBuildSettings
[  +18 ms] "flutter run" took 3,045ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: bbeb786d0320f144)
Crash report written to /Users/botao/Desktop/damai/flutter_ios/dmcompileflutter/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by mofuntech** [comment]
I presented a similar problem and the way to solve it was eliminated all the key (for example: <key> UIRequiredDeviceCapabilities </ key>) manually added in "Info.plist" from the IDE (IntelliJ IDEA) and proceeded to enter these " key "directly from Xcode in Info.plist.

Then I proceeded to install the following libraries that I still lacked:

brew install --HEAD libimobiledevice
brew install ideviceinstaller
brew install ios-deploy
brew install cocoapods
pod setup
sudo easy_install six

Additional also install: Flutter plugin in my IDE.

then install everything always from the directory that contains the project in which all the previous installations "flutter run" were made.

This was the procedure that worked for me.

**Comment by matthew-carroll** [comment]
@DanTup does this issue mean anything to you?  It looks like the issue author mentioned wanting to get some support in VSCode.

**Comment by DanTup** [comment]
I'm not entirely familiar with this (I don't think it's VSCode-specific, I suspect `flutter run` from the terminal will give the same error), though I'm also confused about exactly what' the issue/question is.

For the original error, I would first try running `flutter create .` in the folder as suggested in the error (it's not clear if this has been tried). I don't entirely understand the question about the `ios`/`DMSPortal` folder though.

There are also some issues listed in the `flutter doctor` output related to `libimobiledevice`, `ideviceinstaller` and `CocoaPods` which may be worth resolving to see if they have any effect.

**Comment by dnfield** [comment]
@lichentao is that `DMPortal` folder an existing iOS application that you're trying to add Flutter to?

If it's just a Flutter application you created elsewhere, renaming the folder to `ios` (and deleting the highlighted `ios` folder) should do it.  

If it's an existing Xcode app, you may need to make some additional changes by comparing it to the `ios` folder for now.  We're working on that.  

I'm going to close this for now as a duplicate, but please let me know if you think your problem is different from https://github.com/flutter/flutter/issues/19115 or https://github.com/flutter/flutter/issues/19113!

**Comment by vanab** [comment]
I fixed same problem deleting fonts

**Comment by Ahmedxjs2** [comment]
The easy was: create a dummy project and run it and make sure it run perfectly. Copy all files from the old project(the one can't be run) and paste them in the dummy project.

Open the dummy project again and now it's your old project and will run.
