### ISSUE TITLE
flutter test --flutter-repo only tests package:flutter

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#1939]
It should run tests for all packages.

**Comment by yjbanov** [comment]
I'm going to unassign this for now. Turns out some tests need to run using `flutter test`, others run using `pub run test`. The idiomatic way to choose the right environment for tests is via the `@TestOn` annotation. Let's wait until we have that capability before fixing this. https://github.com/flutter/flutter/blob/master/travis/test.sh is as good a temporary solution as any other.

**Comment by yjbanov** [comment]
@Hixie 

Revisiting this issue. I was trying to find the usages of `flutter test --flutter-repo` and found none, except a note in https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md recommending it as a convenience, and it seems the value of this convenience is fairly small.

Should we remove this option completely?

**Comment by Hixie** [comment]
SGTM
