### ISSUE TITLE
Generate AnimatedIcon

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#19404]
ShapeShifter is a SVG icon animation tool for Android, iOS, and the web
Can I use it to generate AnimatedIcon for Flutter ?

https://github.com/alexjlockwood/ShapeShifter

![screencap](https://user-images.githubusercontent.com/1295961/42760248-213f0b62-890a-11e8-8642-5b0855889ad5.gif)

**Comment by zoechi** [comment]
If you can convert it to Lottie format https://github.com/dnfield/lottie-flutter

**Comment by Solido** [comment]
There's a request to support it 
https://github.com/alexjlockwood/ShapeShifter/issues/19
+1 to support

**Comment by dnfield** [comment]
Important question: Is the desire to use this at compile time or runtime? 

Dynamic: Would you want to load these icons, for example, from a network or other external storage source without recompiling the application?

Static: Would you want this compiled into generated dart code the way vitool does it for it's current animated icon support?

Static will perform better, dynamic gives you more flexibility (which may not be needed).

**Comment by Solido** [comment]
This 'pieces of art' are used in very precises cases so they wont be a lot and there are very lightweight so we can package them with the build. 

In design perception is first citizen so performance should be the guideline.

I see also other advantages in static compilation, if it's dart you can control and animate parameters like colours. Could lead to really interesting effects !

**Comment by kuhnroyal** [comment]
So I just found this https://github.com/flutter/flutter/tree/master/dev/tools/vitool - also we are not supposed to use it. Maybe we can just use it :)
Did anyone try this?

**Comment by YeungKC** [comment]
It would be so exciting to support both dynamic and static.

**Comment by MasiaVittorio** [comment]
I think a way to expose vitool for everyone to use and generate dart files for their custom animated icons would be very beneficial to Flutter, allowing us to design and share many more icons to make Flutter apps engaging and above the competing multiplatform frameworks
