### ISSUE TITLE
Error with executing code for receiving intents from the documentation

### ISSUE THREAD

**Issue by Viibrant** [flutter/flutter#19411]
Hey! I followed the steps on [https://flutter.io/flutter-for-android/#how-do-i-handle-incoming-intents-from-external-applications-in-flutter](this page) and I'm getting an error whenever I execute the code. 
This is the crash report:

> Launching lib/main.dart on BV6000 in debug mode...
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:33: error: ')' expected
      .setMethodCallHandler(MethodChannel.MethodCallHandler() {
                                                             ^
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:35: error: ';' expected
        public void onMethodCall(MethodCall methodCall, MethodChannel.Result result) {
                                ^
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:35: error: ';' expected
        public void onMethodCall(MethodCall methodCall, MethodChannel.Result result) {
                                                                     ^
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:35: error: ';' expected
        public void onMethodCall(MethodCall methodCall, MethodChannel.Result result) {
                                                                                   ^
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:41: error: illegal start of type
      });
       ^
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:44: error: class, interface, or enum expected
  void handleSendText(Intent intent) {
  ^
/home/connor/Documents/programming/flutter/telesharebutrealjava/flutter-share/example/android/app/src/main/java/io/flutter/plugins/shareexample/MainActivity.java:46: error: class, interface, or enum expected
  }
  ^
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Gradle build failed: 1
Exited (sigterm)

**Comment by zoechi** [comment]
Can you please add the output of `flutter doctor -v`?
Please also try with `dev` channel
```
flutter channel dev
flutter doctor
```

**Comment by Viibrant** [comment]
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_GB.UTF-8)
    • Flutter version 0.5.1 at /home/connor/Documents/programming/flutter/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/connor/Android/Sdk
    • Android NDK at /home/connor/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /home/connor/Documents/programming/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/connor/Documents/programming/android-studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.0)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • BV6000 • JNJBDYIBS4KJQ8JJ • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```
The issue is incorrect as I do indeed have the extension installed. Using the dev channel doesn't change the output, I was using the beta channel previously

**Comment by zoechi** [comment]
The extension shown as not installed is a bug fixed in `dev`, you can ignore that.

**Comment by Viibrant** [comment]
I have resolved the issue by modifying the following code:
```new MethodChannel(getFlutterView(), "app.channel.shared.data").setMethodCallHandler(
      new MethodCallHandler() {
        @Override
        public void onMethodCall(MethodCall call, MethodChannel.Result result) {
          if (call.method.contentEquals("getSharedText")) {
            result.success(sharedText);
            sharedText = null;
          }
        }
      });```

**Comment by Viibrant** [comment]
I think the documentation should be edited to reflect this change.

**Comment by zoechi** [comment]
Should we reopen as documentation issue?
It's not clear to me what docs should be updated (haven't used this API myself yet)

**Comment by Sfshaza** [comment]
Yes, when a pass was made over the website to remove unnecessary "new" instances from Dart code, this Java code also got the treatment.

Fixed in the dash branch. We aren't fixing master unless it's a P0.
