### ISSUE TITLE
Error in android devices

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#19413]
_From @SaiKarthikMalyala on July 16, 2018 15:0_

URL: https://pub.dartlang.org/packages/url_launcher

When I tried to open .pfd and .docx files in android devices it exist displaying the blank black screen.

The same files when I opened the Iphone they are opened.

_Copied from original issue: dart-lang/pub-dartlang-dart#1461_

**Comment by isoos** [comment]
@SaiKarthikMalyala This repository is for the pub site, please submit your issues to the package's issue tracker. I'm moving it this time.

**Comment by zoechi** [comment]
@SaiKarthikMalyala are you still seeing this?
