### ISSUE TITLE
"flutter build" should support depsfile

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#1942]
Similar to what dart snapshotter provides https://github.com/domokit/mojo/blob/cda76857c5aaaaafd912eddd5f0e0bb168df7fa5/mojo/public/tools/dart_snapshotter.py#L17

**Comment by abarth** [comment]
Yes!

**Comment by Hixie** [comment]
What does this do?

**Comment by abarth** [comment]
It writes out a file that describes the set inputs it used to compute its output.  It's used by build systems to decide when it's necessary to re-run this step of the build.  If you're familiar with gcc, it's what's generated using the `-MM` flag.

**Comment by abarth** [comment]
I think what he wants is effectively `-MD -MF`, which compiles and outputs the dependency information.
