### ISSUE TITLE
Error 105 received from application: Isolate must be runnable- flutter- vs code

### ISSUE THREAD

**Issue by MeshkaniMohammad** [flutter/flutter#19426]
i start my application and got this error and with page in emulator

Error 105 received from application: Isolate must be runnable
Hot reload received invalid response: {code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: /data/user/0/com.example.firstdart/cache/first_dartRYYGVJ/first_dart/lib/main.dart.dill, packagesUri: /data/user/0/com.example.firstdart/cache/first_dartRYYGVJ/first_dart/.packages, isolateId: isolates/210303830}}, details: Isolate must be runnable before this request is made.}}

**Comment by zoechi** [comment]
/cc @DanTup 

Please add the output of `flutter doctor`.
Does the file `lib/main.dart` contain valid Dart code?

**Comment by MeshkaniMohammad** [comment]
Every thing is ok and I checked it in intelij idea and worked well.but in
vs code it doesn't work and gives this error

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

**Comment by DanTup** [comment]
Could you try collecting some logs for me?

- Run the `Dart: Capture Logs` command from the VS Code command palette
- Tick the `Flutter Run` and `Observatory` options (you can untick others)
- Choose a location to save the log file
- Start a debug session and reproduce the issue by trying some hot reloads
- Click the **Stop Logging** button in the log notification
- Review that log file to ensure it doesn't contain anything sensitive (it'll have paths/project names) and attach here

**Comment by wangqianjun** [comment]
+1

**Comment by zoechi** [comment]
@wangqianjun this issue is long closed. "+1" comments are meaning less.
If you are seeing this, please create a new issue with information about how to reproduce and your environment.

**Comment by wangqianjun** [comment]
@zoechi when i use VSCode debug my program, and i get this error:

Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///Users/arthur/Library/Developer/CoreSimulator/Devices/9B9B9549-7175-407E-AFD2-630F0B455D9F/data/Containers/Data/Application/9F8782F2-1058-4435-8DE7-FB9745C99AA8/tmp/merchant_flutterXa7tne/merchant_flutter/lib/main.dart.incremental.dill, packagesUri: file:///Users/arthur/Library/Developer/CoreSimulator/Devices/9B9B9549-7175-407E-AFD2-630F0B455D9F/data/Containers/Data/Application/9F8782F2-1058-4435-8DE7-FB9745C99AA8/tmp/merchant_flutterXa7tne/merchant_flutter/.packages, isolateId: isolates/324779890}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Exited (255)

`Flutter --version`
Flutter 1.0.0 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

`VSCode version`
1.30.0 (1.30.0)

**Comment by songyu0122** [comment]
You can try flutter run many times. Vscode sometimes compiles incorrectly

**Comment by DanTup** [comment]
@songyu0122 This is certainly not expected - if you can reproduce this and provide more information, please file an issue so we can take a look. Thanks!

**Comment by wangqianjun** [comment]
@DanTup Tank u, I created another issue on the `Dart-Code ` project.
https://github.com/Dart-Code/Dart-Code/issues/1365

**Comment by iCoobin** [comment]
```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'route/CornPayApp.dart';
import 'route/ABCCApp.dart';

void main(){
  return runApp(_widgetForRoute(ui.window.defaultRouteName));
}

Widget _widgetForRoute(String route){
  print(route);
  switch (route){
    case 'CornPayApp':
      return CornPayApp();
    case 'ABCCApp':
      return ABCCApp();
    case '/':
      return ABCCApp();
    default:
      return Center(
        child: Text('Unknown route: $route', textDirection: TextDirection.ltr),
      );
  }
}
```
hot reload error
```
Initializing hot reload...
Syncing files to device iPhone 7...
Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///Users/cheng/Library/Developer/CoreSimulator/Devices/AB6D7686-DD77-4078-8694-D629ACB6F49D/data/Containers/Data/Application/67C76226-4B45-4262-9B37-58BF02F05C11/tmp/flutter-demouWwEgv/flutter-demo/lib/main.dart.incremental.dill, packagesUri: file:///Users/cheng/Library/Developer/CoreSimulator/Devices/AB6D7686-DD77-4078-8694-D629ACB6F49D/data/Containers/Data/Application/67C76226-4B45-4262-9B37-58BF02F05C11/tmp/flutter-demouWwEgv/flutter-demo/.packages, isolateId: isolates/245199374}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
@iCoobin try `flutter clean`. Is there something special about your project? (adding Flutter to an existing app, ...) 
Please add the output of `flutter doctor -v`.

**Comment by DanTup** [comment]
@iCoobin Could you capture some logs (see https://github.com/flutter/flutter/issues/19426#issuecomment-405518546) and also confirm:

- Do you have any plugins used by this project?
- Does this happen on its own at startup, or when you hot reload?

**Comment by mmustafasesudia** [comment]
this issue arises in vs code try to run `flutter clean`  and build the application works fine for me...

**Comment by testing2007** [comment]
I had encounter this issue recently, there was two FlutterViewController in my project and call registerPlugin, By vscode IDE, when you open the debug tab, which shows two main.dart Running , when i delete each FlutterViewController one of them, this error didn't happen again, I don't know if you are same question.

**Comment by asamoahtekyi** [comment]
check the runApp method in your main

**Comment by natchaporing** [comment]
I got this error too. I very new of flutter
These the log that I got

> 
> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> 
> flutter run -d iPhone 6
> 
> ## exception
> 
> _InternalLinkedHashMap<String, dynamic>: {code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: false, rootLibUri: file:///Users/buzzebees-imac/Library/Developer/CoreSimulator/Devices/A7B2479A-F98C-438F-8F63-464C0DD58042/data/Containers/Data/Application/E4161832-C967-4543-86B6-68C32F657EF7/tmp/Flutter_Project_KOIthedneopm/Flutter_Project_KOIthe/lib/main.dart.incremental.dill, packagesUri: file:///Users/buzzebees-imac/Library/Developer/CoreSimulator/Devices/A7B2479A-F98C-438F-8F63-464C0DD58042/data/Containers/Data/Application/E4161832-C967-4543-86B6-68C32F657EF7/tmp/Flutter_Project_KOIthedneopm/Flutter_Project_KOIthe/.packages, isolateId: isolates/300070832}}, details: Isolate must be runnable before this request is made.}}
> 
> ```
> null```
> 
> ## flutter doctor
> 
> ```
> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-TH)
>     • Flutter version 1.7.8+hotfix.4 at /Users/buzzebees-imac/flutter
>     • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /usr/local/share/android-sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /usr/local/share/android-sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.3, Build version 10G8
>     • CocoaPods version 1.7.1
> 
> [✓] iOS tools - develop for iOS devices
>     • ios-deploy 1.9.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 38.2.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Connected device (2 available)
>     • iPhone#60 • 2d0cd55d8b5dd0d8f8483385516f2af5e4469f4f • ios • iOS 12.2
>     • iPhone 6  • A7B2479A-F98C-438F-8F63-464C0DD58042     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
> 
> • No issues found!

could you please help me?

**Comment by DanTup** [comment]
@natchaporing please open a new issue since this one is closed and very old. Please include the full output of `flutter run -v` when this happens (please paste it into a Gist or similar and then include the link in the issue), and if possible a small repro project you see the issue with.

**Comment by daneed** [comment]
I had the same issue today:
whenever I tried to run my app on IOS simulator, with flutter, from VS Code for Insiders, it did not start correctly, and always have this error message.
BUT I MANAGED TO SOLVE THIS:
1. I started XCode, and made a build
2. Then, I tried again to flutter run. And a miracle happened: now, this worked. This is repaired.

So, I think, this is some XCode Magic, and only solvable from XCode. For me flutter clean, flutter pub dev, pod update....none of this helped. Only this XCode magic.

**Comment by jasonhe88** [comment]
got the same problem here,  and i figure out what caused the issue in my case.

I need to add an eventChannel in a plugin, but could not use getFlutterView() as in old version due to upgrade in Flutter plugin , so i used following code as a workaround:

'''dart
FlutterEngine flutterEngine = new FlutterEngine(activity);
eventChannel = new EventChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), "com.xxx.eventChangle");
'''
whenever i remove these two lines, it will be ok, otherwise it gives 105 error when try to hot reload. I think FlutterEngine(activity) starts a new Isolate ?

**Comment by WANGNEWMAN** [comment]
got same problem, I found user MethodChannel,I delete iOS code, It OK


Xcode build done.                                           84.4s
Error -32601 received from application: Method not found
method not available: ext.flutter.platformOverride
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
method not available: ext.flutter.inspector.setPubRootDirectories
Error -32601 received from application: Method not found
method not available: ext.flutter.inspector.isWidgetCreationTracked
Error 105 received from application: Isolate must be runnable
Hot reload received invalid response: {code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///private/var/mobile/Containers/Data/Application/D27FF80F-97ED-4474-8CAD-C1B78A6BE96B/tmp/vsdemo3reAXJ/vsdemo/lib/main.dart.incremental.dill, packagesUri: file:///private/var/mobile/Containers/Data/Application/D27FF80F-97ED-4474-8CAD-C1B78A6BE96B/tmp/vsdemo3reAXJ/vsdemo/.packages, isolateId: isolates/3912448001938899}}, details: Isolate must be runnable before this request is made.}}

**Comment by raymondpang95** [comment]
> @iCoobin Could you capture some logs (see [#19426 (comment)](https://github.com/flutter/flutter/issues/19426#issuecomment-405518546)) and also confirm:
> 
> * Do you have any plugins used by this project?
> * Does this happen on its own at startup, or when you hot reload?

thx  @DanTup  keep helping the people who facing the bug or issues , i seen many comment from you .

**Comment by Jordhan-Carvalho** [comment]
> user MethodChannel,I delete iOS code, I

Having the same issue after adding flutter_messaging and adding the background notification

**Comment by PrashantSamcom** [comment]
Facing same issue. Only showing white screen when i run first time but when i press hot reload, studio fire error which i put below...

this is an error...
> Performing hot restart...
Syncing files to device iPhone 7 Plus...
Error 105 received from application: Isolate must be runnable
Restarted application in 1,339ms.
Error -32000 received from application: Could not run configuration in engine.
Lost connection to device.


Please share if you have solution of this error..

**Comment by royibernthal** [comment]
> > user MethodChannel,I delete iOS code, I
> 
> Having the same issue after adding flutter_messaging and adding the background notification

It started happening to me after adding background messages to flutter_messaging as well.

**Comment by AndrsDev** [comment]
This is happening to me too

**Comment by gladimdim** [comment]
I updated all my dependencies on pubspec to the very latest versions.

Then: 
```
flutter clean
```

Then Started the project from Xcode.

Then it started loading from Android Studio with hot reload too.

**Comment by royibernthal** [comment]
I forgot to update - it seems like `flutter clean` did the job for me as well.

**Comment by itexpert2572000** [comment]
Error 105 received from application: Isolate must be runnable

I got these error while I was running the app, I tried my best to correct this issue but I couldn't.

**Comment by bionara** [comment]
I'm getting this error also - my teammate is not (same branch). I've tried flutter doctor and clean, even tried to reclone the repo but no luck. Any ideas?

**Comment by monajafinerdit** [comment]
This is happenning to me also

**Comment by adurukan** [comment]
This issue happened to me as well, and the way I solve it was doing:
`flutter clean`

**Comment by altafkhan8719** [comment]
i am also facing same problem

**Comment by tapeo** [comment]
Solution for me is:
1. delete file: `ios/Runner.xcodeproj/project.pbxproj`
2. run command `flutter create .`

**Comment by Elias8** [comment]
For me, it is fixed when I deleted the ```.packages``` file and run ```pub get```. I had ```firebase_messaging```, ```flutter_local_notifications```  and many other dependencies.
