### ISSUE TITLE
Meta bug for #19322 regressions

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19439]
Regressions starting with this engine roll https://github.com/flutter/flutter/pull/19322:

* analyzer benchmarks are at least 10% slower #19431
* debug_full_compile_millis regressed about 10% across the board #19432
* complex_layout_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis regression #19433
* complex_layout_scroll_perf__timeline_summary average_frame_rasterizer_time_millis regression #19434
* complex_layout_semantics_perf initialSemanticsTreeCreation ~40% regression #19435
* flutter_gallery__memory_nav diff_total_kb increased #19436
* flutter_test_performance regressed by ~20% #19437
* flutter_gallery__back_button_memory is much more flaky now #19438

**Comment by Hixie** [comment]
* Breakpoints crash flutter application https://github.com/flutter/flutter/issues/19379

**Comment by jonahwilliams** [comment]
* App crashes: JNI DETECTED ERROR IN APPLICATION on Android 22 and below: https://github.com/flutter/flutter/issues/19475

**Comment by Hixie** [comment]
I'm going to close this bug now since we no longer need a meta issue to track this.
