### ISSUE TITLE
analyzer benchmarks are at least 10% slower

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19431]
Starting with this engine roll: https://github.com/flutter/flutter/pull/19322

**Comment by Hixie** [comment]
Update: This is caused by the Dart 2 VM being slower than the Dart 1 VM. We hope to have a mitigation in place for this momentarily.

**Comment by devoncarew** [comment]
There are a few things in progress here:

running with a dart 1 snapshot:
- https://github.com/flutter/flutter/pull/19500 adds support for using a dart 1 analysis server snapshot, if one exists in the dart sdk
- and upstream, we've added a dart 1 analysis server snapshot; this will get picked up after a dart -> engine -> flutter roll

improving regular perf:
- we've made several small performance improvements to the analysis server, in the neighborhood of a 6% improvement total
- we're improved the training of the dart 2 analysis server snapshot, for another 3-4% speed improvement
- we'll also see these changes on the next set of rolls; eventually, we'll remove the dart 1 snapshot, and continue to investigate general perf improvements

**Comment by mkustermann** [comment]
The VM team has also made some improvements. I've landed https://github.com/dart-lang/sdk/commit/6e81d74fccbeba40b30aed5523b3c15be15eb4a3 which shows improvements to the following benchmarks:

  * analysis-server-cold-analysis by 6%
  * analysis-server-warm-analysis by 11%

These are normal analysis_server benchmarks the Dart team is tracking. Hopefully this translates into similar improvements to `flutter analyze`.

**Comment by devoncarew** [comment]
The latest has rolled into Flutter now:
- pre-dart 2 we saw times that were around 75.6s.
- post VM optimizations, analysis server optimizations, and snapshot training we see times that are around 78s.

So, we have about 3% more of a speed difference to recover here.

**Comment by devoncarew** [comment]
I think we should continue working on this, but I'm going to remove the `severe` label; /cc @Hixie.

**Comment by Hixie** [comment]
These performance improvements look great, thanks!
