### ISSUE TITLE
flutter_gallery__back_button_memory is much more flaky now (data)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19438]
Starting with this engine roll: https://github.com/flutter/flutter/pull/19322

**Comment by aam** [comment]
See https://github.com/flutter/flutter/issues/19436#issuecomment-405648525

**Comment by cbracken** [comment]
@Hixie by 'flaky' do you mean broken-flaky or inconsistent results? The results look pretty consistent to me, and I don't see a whole lot of missing data (e.g. from broken runs), but perhaps those were manually re-run?

**Comment by Hixie** [comment]
Update: We're working on improving the benchmark, which will help us track down the issue.

**Comment by Hixie** [comment]
I landed changes to the benchmark.
