### ISSUE TITLE
TextInput: Cursor wont move to next line when pressing `enter` in IME

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#19446]
Occurs in both the latest dev and master channel

![ezgif-1-864ae21019](https://user-images.githubusercontent.com/1160688/42792927-3b1828d4-89aa-11e8-930a-c52a6e5a3c8c.gif)

**Comment by CaiJingLong** [comment]
+1 
I also met the same bug.

**Comment by namiwang** [comment]
Yep. Closing.
