### ISSUE TITLE
When I use Navigator to push a Scaffold,I want to click anywhere to drag back!

### ISSUE THREAD

**Issue by jiangjh** [flutter/flutter#19449]

**Comment by zoechi** [comment]
Perhaps you want to wrap the content with a https://docs.flutter.io/flutter/widgets/GestureDetector-class.html
I think this kind of question is better asked on StackOverflow or https://gitter.im/flutter/flutter anyway.

**Comment by jiangjh** [comment]
Not it , how to Full screen sideslip ?

**Comment by zoechi** [comment]
Did you close the issue intentionally?

**Comment by jiangjh** [comment]
The issue is same as #19510

**Comment by jiangjh** [comment]
Essentially,I want fullscreen-swipe,not Edge-swipe!

**Comment by jiangjh** [comment]
@zoechi Do you has a way of implementing it?

**Comment by jiangjh** [comment]
Thank you!
