### ISSUE TITLE
Document that widgets in the overflow of stack do not respond to gestures

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#19445]
Internal: b/143100923

When a `Stack` contains `MyWidget` inside of a `Positioned`.
```dart
    Stack(
      overflow: Overflow.visible,
      children: [
        Positioned(
        top: -50.0,
        child: MyWidget(),
      )],
    );
```

Since overflow is `Overflow.visible`, `MyWidget` displays outside of the `Stack`. However, it doesn't accept gestures in the overflowed area. I have no idea if it's easy, difficult or downright impossible to make this change, but I can think of a gazillion use cases for that, which at the moment must be satisfied by using the much more complex Overlay, or some Stack tricks.

And in case it's impossible to make this change, then at least the documentation should clearly state that overflowed content can't receive gestures.

Also, see: https://stackoverflow.com/questions/51366761/in-flutter-how-can-a-positioned-widget-feel-taps-outside-of-its-parent-stack-ar

**Comment by modulovalue** [comment]
+1

**Comment by goderbauer** [comment]
It is intentional that widgets in the overflow area of a stack do not react to gestures and that's unlikely to change. I recommend that people with this (or similar) problems refactor their app to keep all interactable elements within the bounds of a stack.

I do realize that we are not properly documenting this behavior of the stack widget in the API docs. Let's turn this bug into a documentation issue to improve that and properly document the gesture behavior of stack on the class.

**Comment by abacaj** [comment]
Has anyone been able to achieve the same desired effect?

I need a stack where one widget slides up behind another and it has a gesture for pressing on it.

**Comment by abacaj** [comment]
> It is intentional that widgets in the overflow area of a stack do not react to gestures and that's unlikely to change. I recommend that people with this (or similar) problems refactor their app to keep all interactable elements within the bounds of a stack.
> 
> I do realize that we are not properly documenting this behavior of the stack widget in the API docs. Let's turn this bug into a documentation issue to improve that and properly document the gesture behavior of stack on the class.

Do you know a way around this? it seems like a bug otherwise how can we have one widget on top of another and the one behind it has a tap detector?

**Comment by lifenautjoe** [comment]
So the answer to this is to formalise the issue by documenting it?

**Comment by frederickcxa** [comment]
Hi guys, I also hit the same rock with an ongoing redesign in our app. 

I used an `OverlayEntry` to display the elements that I was overlapping in the `Stack`. You need to get the position + size of the element which you want to put the other widgets on top, with that you can position the `OverlayEntry` using those coordinates. 

Doing this, you can get the same position you were doing with the `Stack`, but now your elements that are overlapping can handle gestures.

The only problem with this is that the overlay is fixed to those coordinates in the device's viewport. For a scrolling page, the overlay will be floating around, to solve this we used `CompositedTransformTarget` and `CompositedTransformFollower`, wrapping the target element with the former and the overlapping widget with the latter, both accept a `link: LayerLink` property, that lets you linked them, with this your overlay will follow the target widget while you scroll.

Something like this:

```Dart
final _layerLink = LayerLink();
...
return CompositedTransformTarget(
      link: _layerLink,
      child: Text('Overlay target'),
    );
...
_overlay = OverlayEntry(builder: (_) {
        final RenderBox renderBoxRed = context.findRenderObject(); // BuildContext of the target element
        final position = renderBoxRed.localToGlobal(Offset.zero);
        final size = renderBoxRed.size;

        return Positioned(
          left: 16, // Horizontal positioning
          right: 16,
          child: CompositedTransformFollower(
            link: _layerLink,
            offset: Offset(0, (position.dy + size.height)), // Vertical positioning using the target dimensions
            child: Text('Overlay follower...'),
          ),
        );
      });
}

Overlay.of(context).insert(_overlay);
```

Hope it helps, if you want to know more about those widgets and different approaches on how to get a widget's size and position, check out these great articles that guided me to this approach.

[Flutter: Using Overlay to display floating widgets](https://medium.com/saugo360/https-medium-com-saugo360-flutter-using-overlay-to-display-floating-widgets-2e6d0e8decb9)
[Flutter : Widget Size and Position](https://medium.com/@diegoveloper/flutter-widget-size-and-position-b0a9ffed9407)

**Comment by Skyost** [comment]
The problem with all of this is when I want to position an element like this :

```dart
Positioned(
  top: 22,
  left: 22,
  child: GestureDetector(
    onTap: () => Navigator.pop(context),
    child: Icon(
      Icons.arrow_back_ios,
      color: Colors.white,
      size: 28,
    ),
  )
)
```
Well it works fine on Android, iPhone, ... Except the iPhone XS Max (because of its rounded corners a part of this widget become invisible and it becomes unclickable).

**Comment by genesiscz** [comment]
> It is intentional that widgets in the overflow area of a stack do not react to gestures and that's unlikely to change. I recommend that people with this (or similar) problems refactor their app to keep all interactable elements within the bounds of a stack.
> 
> I do realize that we are not properly documenting this behavior of the stack widget in the API docs. Let's turn this bug into a documentation issue to improve that and properly document the gesture behavior of stack on the class.

So what is the way to get the gesture when you have a positioned widget to be out of bounds of a container then?

**Comment by thenexus00** [comment]
Agreed, Because you are going to have lots of cases with design where you have a big button sitting at a bottom of a square which is a button and so on. To say you can not because it is instead cuts out a lot of designs.

**Comment by localpcguy** [comment]
This seems like something that should be a choice for the developer, not a limitation of the framework. I'm ok if the default is how it works currently, but an option to allow the click to allow for interaction outside of the stack boundaries would give that choice to the developer and allow for more options. 

I was trying to implement a TapOutside widget that blocks interaction with other elements on the screen when a TextField is focused, and clears focus when tapped (and then allows interaction again). That's when I ran into this limitation. I don't think I can use a ModalRoute, as I want the user to click on and use a TextField that exists in the current screen (not push them to a new route). 

I don't want to get too much more specific on the use case or ask for help (although if there is a "Flutter way" that I'm not seeing, I would potentially withdraw my complaint), just trying to demonstrate that there could be a use case. I've also looked into adding a GestureDetector at the root of the screen, and while that "works" for clicks not on other elements, because it's at the root, clicks on it do not block clicks on other elements on the screen. Maybe something with RawGestureDetector would work, but that seems like an awfully complex solution when putting a transparent barrier over the elements when the widget is focused is very simple. It just doesn't work due to this issue.

**Comment by adriancmurray** [comment]
I agree that this should be left up to the developer. This is the second time I've come across this issue. My first time around I found a decent enough work around, now, it's incredibly verbose to get what I am aiming at when really this should just be left up to the developer to decide, not necessarily a design limitation of the framework.

**Comment by goderbauer** [comment]
I understand the disappointment. Unfortunately, performing hit-testing outside of the bounds of a stack in the overflow is prohibitively expensive in terms of performance.

I do still believe that you can always restructure your app to not require hit-testing in the overflow of a stack. Maybe, people can post some runnable code examples of where you'd like to do hit testing in the overflow of the stack and we can figure out how to restructure the code to not require that. Those example uses cases would also be good for us to include in the updated docs of overflow.

**Comment by localpcguy** [comment]
The example I posted is basically the scenario I envision it being useful to have hit-testing outside of the stack: basically trying to do a custom modal where you want to create an underlay that accepts click events from a specific widget. In my case, it was a search bar where we wanted to block other clickable elements when the search field is focused, but continue to have the search field above that. We did not want to make it a new "screen", hence not using the existing modal constructs.

**Comment by Eunovo** [comment]
I had a problem like this. 
I animated the position of some children of a Stack so that they moved out of the Stack's bounds.
At the end of the animation, these children did not respond to gestures anymore. 
I solved this problem by setting the 'fit' property of the Stack to 'StackFit.expand'.

`Stack(
    fit: StackFit.expand,
    ...
)`

Hope this helps.

**Comment by gmaggio** [comment]
@frederickcxa: I was so hoping `OverlayEntry` would be the solution but the problem with that method is that the `OverlayEntry` **doesn't go away when navigating to another screen**. In my case, I wanted to create some sort of clickable icon widget with the `OverlayEntry` being the _**hotspot**_ for the clickable area, which is bigger than the icon and often overlaps the surrounding area.

**Comment by gmaggio** [comment]
May I suggest an **option** to create an `OverlayEntry` above the current _Overlay_ instead of **at the topmost** so at least when navigating to the next screen the `OverlayEntry` would be covered and not visible.

**Comment by smkhalsa** [comment]
@goderbauer here's an example which I cannot figure out how to restructure:

![overlay](https://user-images.githubusercontent.com/6362903/64910622-ac374100-d718-11e9-9bb6-d1dec3f39114.gif)

I'm currently using a `SliverAppBar` with the following `bottom` widget:

```
PreferredSize(
    preferredSize: Size.fromHeight(24),
    child: Container(
      height: 24,
      child: Stack(
          overflow: Overflow.visible,
          alignment: AlignmentDirectional.center,
          children: [
            Positioned(
                bottom: -24.0,
                child: SizedBox(
                  height: 48,
                  width: 240,
                  child: RaisedButton(
                      shape: RoundedRectangleBorder(
                          borderRadius:
                              new BorderRadius.circular(30.0)),
                      onPressed: () => {},
                      color: Theme.of(context).accentColor,
                      child: Text('Shuffle Play'.toUpperCase())),
                ))
          ]),
    ));
```

Since the bottom half of the button is overflowing, it cannot be tapped.

I should note that I've also tried the `OverlayEntry` approach with `CompositedTransformTarget` and `CompositedTransformFollower` as described by @frederickcxa above but ran into the same issue as @gmaggio when navigating away from the screen (i.e. the overlay stays on the screen), even if I call `overlayEntry.remove()` in the dispose method of the origin screen.

**Comment by marcglasberg** [comment]
@smkhalsa Put your whole list inside of a `Stack`. You should calculate and position your button using `Positioned` in this Stack, instead of the `Overlay`.

**Comment by smkhalsa** [comment]
@marcglasberg do you mean wrap my CustomScrollView in a stack? How would I sync the position of the button with the SliverAppBar as it expands and contracts?

**Comment by smkhalsa** [comment]
@marcglasberg nevermind, it worked! I wrapped my entire `CustomScrollView` in a stack and used `CompositedTransformTarget` and `CompositedTransformFollower` to sync the position of the button. Thanks so much!

**Comment by phoenixsky** [comment]
same issue +1

**Comment by goops17** [comment]
same issue +1

**Comment by esDotDev** [comment]
Asking developers to re-architect their apps is really an unfortunate response imo. Developers are using these tricks because they're simple, fast, and elegant. Translating an item in a stack, is one of the few ways in Flutter to 'break our of the box', and many designs calls for this behavior. Of course these things need to be clickable.

I have a use-case for this, and interested in how you might workaround it.

The design concept for the app is Skueomorphic, the idea is that it's a bunch of buttons, on a table, and when you change views, it transitions from one spot on the table, to the other. You see the old view sliding out, and while the new one slides in, but crucially, some portion of the old view may still be visible (so I can't just load a new page entirely)

Something like this: 
![image](https://user-images.githubusercontent.com/736973/68414911-5d24ef80-014e-11ea-880c-54d9798a01e6.png)

This is extremely easy to setup with a stack, I just create the 4 views, use Transform() to translate them offscreen, and then I can tween the correct view on screen when needed. 

The only issue... none of the buttons or inputs work on Views 2 - 4, since they were initialized outside the parent stack. 

I can't really think of any other ways to get this same behavior, without doing something very convoluted like rasterizing the whole widget tree, and then transitioning that offscreen, as I load my new view in.

**Comment by amazg** [comment]
see https://api.flutter.dev/flutter/widgets/Stack-class.html

> The stack paints its children in order with the first child being at the bottom. If you want to change the order in which the children paint, you can rebuild the stack with the children in the new order. If you reorder the children in this way, consider giving the children non-null keys. These keys will cause the framework to move the underlying objects for the children to their new locations rather than recreate them at their new location.

you can put the taped widget at the last of the Stack children!

**Comment by micimize** [comment]
I made an [overlay container](https://gist.github.com/micimize/7579a66861cf56ba241b224a64566d51) (based on the [`overlay_container`](https://github.com/MustansirZia/overlay_container) package) that makes replacing `Stack(Positioned)` with relatively positioned `OverlayEntry`s relatively easy. Also works around https://github.com/flutter/flutter/issues/48052

**Comment by mevos19** [comment]
Hi guys you can solve this probleme by use Transform.translate  instead of  Position use
this:
```
Stack(
      overflow: Overflow.visible,
      children: [
        Positioned(
        top: -50.0,
        child: MyWidget(),
      )],
    );
```
becom:
`    Stack(
      overflow: Overflow.visible,
      children: [
        Transform.translate(
        offset: Offset(0,-50),
        child: MyWidget(),
      )],
    );`

**Comment by lukepighetti** [comment]
About a year ago I requested that we be able to define custom hit boxes for our widgets. Some kind of `Rect` with an `Offset` perhaps. This would apply here I think.

**Comment by micimize** [comment]
@goderbauer 
* Does the `Transform.translate` workaround above not incur the same performance penalty?
* in my case, I spent a day or two of development time reworking my code to work with the overlay system, to get something that would have taken me an hour with overflow-aware gesture detection. I would be surprised if it is less expensive computationally

**Comment by esDotDev** [comment]
From my testing, you would have to have some pretty elaborate widget trees to have a significant performance cost on tap. I removed the bounds check completely, running on a mid-range android phone, tap frame was ~10ms, basically no perceivable difference.

**Comment by MuhammedKasujja** [comment]
Stack(
    fit:StackFit.expand, // add this 
    overflow: Overflow.visible,
    children: [
        Container(), // add this as your first stack child 
        Positioned(
        top: 0.0,
        left: 0.0,
        child: MyWidget(),
   )],
);


// that is how I managed to work around it

**Comment by 1g0rrr** [comment]
Oh, just spend half of the day to figure out why my Containers not responds. And still no changes in documentation. Would be great to see any progress here.

**Comment by zahidaz** [comment]
here is how i solved this

```
Positioned(
          // added height and width that it could accommodate all its children, which in my case are 4
            height: 200,
              width: 200,
              right: 30,
              bottom: 30,
              child: Stack(
             // added aliment to put the stack inside boundary of positioned element
                alignment: Alignment.bottomRight,
                children: <Widget>[]))
```

**Comment by 1g0rrr** [comment]
The big problem is that Stack is the only way to free the positioning widget. When you have some complex UI with nested Stacks it's become a nightmare to calculate and expand all these Stacks. 
If you guys are not willing to change its behavior, can you just give some alternative where we can set a position to the widget and forget about it, like in any game engine? It could have worse performance, but if it just works it will save a bunch of time for a lot of situations.

**Comment by Galti** [comment]
Still having the same issue. Have anybody found the solution?
Does flutter have another widget for creating such behavior as @smkhalsa  : https://github.com/flutter/flutter/issues/19445#issuecomment-531491746

**Comment by 1g0rrr** [comment]
You even have Positioned widgets that overflow Stack in your video tutorials. ) https://youtu.be/EgtPleVwxBQ?t=14
But push us to "keep all interactable elements within the bounds of a stack". There is a lot of situations with flutter's tree system when it's nearly impossible to manage. Especially in case of nested stacks.

**Comment by lukepighetti** [comment]
@goderbauer What are the technical / philosophical limitations of allowing someone to specify the hitbox of a widget. Possibly solving:

1) tapping a widget that is positioned outside the bounds of a stack
2) increasing the tappable size of a GestureDetector

**Comment by lucio1392** [comment]
I have to facing with this problem and I have to workaround when put the widget that is a Positioned's child and put its as the last child of `Stack` widget then everything work well, Gesture can response.

```  @override
  Widget build(BuildContext context) {
    final screenHeight = MediaQuery.of(context).size.height;

    final _orientation = MediaQuery.of(context).orientation;

    return GestureDetector(
        onTap: () {
          FocusScope.of(context).requestFocus(FocusNode());
        },
        child: Stack(
          overflow: Overflow.visible,
          fit: StackFit.expand,
          children: <Widget>[
            _buildBackgroundImage(),
            Scaffold(
              backgroundColor: Colors.transparent,
              body: SingleChildScrollView(
                child: Column(
                  children: <Widget>[
                    SizedBox(
                      height: screenHeight / 5,
                    ),
                    Container(
                      padding: EdgeInsets.fromLTRB(
                          _orientation == Orientation.portrait ? 80 : 250,
                          0,
                          _orientation == Orientation.portrait ? 80 : 250,
                          0),
                      child: Image.asset(
                        'assets/images/logo.png',
                        alignment: Alignment.center,
                      ),
                    ),
                    SizedBox(
                      height: screenHeight / 5,
                    ),
                    _buildEmailInputTextFieldWidget(),
                    _buildPasswordInputTextFieldWidget(),
                    _buildSingInButtonWidget(),
                    _buildGestureDetector(context),
                  ],
                ),
              ),
            ),
            _buildBackButton(),
          ],
        ));
  }

  Widget _buildBackButton() {
    return Positioned(
        top: 64,
        left: 15,
        child: GestureDetector(
          onTap: () {
            Navigator.pop(context);
          },
          child: Icon(
            Icons.arrow_back_ios,
            color: Colors.black,
            size: 30,
          ),
        ),
      );
  }````

**Comment by Piinks** [comment]
Those in this thread may be interested in this recent change: https://github.com/flutter/flutter/pull/59364

**Comment by wanjm** [comment]
> Hi guys you can solve this problem by use Transform.translate instead of Position use
> this:
> 
> ```
> Stack(
>       overflow: Overflow.visible,
>       children: [
>         Positioned(
>         top: -50.0,
>         child: MyWidget(),
>       )],
>     );
> ```
> 
> become:
> 
> ```
>  Stack(
>       overflow: Overflow.visible,
>       children: [
>         Transform.translate(
>         offset: Offset(0,-50),
>         child: MyWidget(),
>       )],
>     );
> ```

why 5 peple don't like this?

**Comment by wanjm** [comment]
@Piinks  how does #59364  solve this problem.

**Comment by Piinks** [comment]
> @Piinks how does #59364 solve this problem.

It offers a new approach and mentions deprecating Stack.overflow in the future.

**Comment by lukepighetti** [comment]
This is unifying clip semantics across multiple widgets? That doesn't affect this issue, though, right?

**Comment by 1g0rrr** [comment]
Just switched to master to check #59364. Yes, there is a new parameter "clipBehavior" in Stack, but no, it does not solve this problem, unfortunately.
Still waiting for something else.

**Comment by junaidlodhi22** [comment]
gesture detector is showing weird behavious... for one Screen it is working outside the stack and and for other screen it is not working.
so i solved this using a container with padding top or bottom and color transparent... this way gesture detector detect tap as it comes inside of stack area and is clickable

**Comment by magpiedigital** [comment]
> @frederickcxa: I was so hoping `OverlayEntry` would be the solution but the problem with that method is that the `OverlayEntry` **doesn't go away when navigating to another screen**. In my case, I wanted to create some sort of clickable icon widget with the `OverlayEntry` being the _**hotspot**_ for the **clickable area**, which is **bigger than the icon** and **often overlaps the surrounding area**.

You can just remove the overlay when you navigate.

**Comment by gmaggio** [comment]
@magpiedigital So how do you rebuild the overlay on navigating back with `.pop()`?

**Comment by magpiedigital** [comment]
> @magpiedigital So how do you rebuild the overlay on navigating back with `.pop()`?

Just await the original .push() and rebuild it after that

**Comment by PBrunoCyber** [comment]
"Restructure your project" is a very lazy suggestion @goderbauer , the developers decide whether they want performance or not. 3 years have passed and until today there was no solution, it is really sad.

**Comment by gmaggio** [comment]
@magpiedigital Can you give us a sample code. I've been trying to figure out a way to rebuild upon _popping_ back but the only way I can think of is using `RouteObserver`.

**Comment by magpiedigital** [comment]
@gmaggio This isn't the right place to be asking for this type of help (Stackoverflow is better) but have you tried something like this:

```
navigate() async {
   _overlay.remove() // removes the overlay before navigating
   await Navigator.of(context).push() // navigates and waits until .pop()
   Overlay.of(context).insert(_overlay); // reinserts the same way you initially build
}
```

In case you didn't know you could await a navigation, it's an important concept and allows you to pass values back in the pop as well.

I haven't tested this code btw

**Comment by samerelchami** [comment]
Here's how I dealt with this, I hope you find it helpful:
First off, I have a SizedBox that will take the height and width of my choosing (taking into account the size of the widgets that will overflow), the child of the SizedBox will be a Stack (Stack 1) with children, but the first child will be another SizedBox with your preferred size (not including the widgets that will overflow) and its child is a Stack (Stack 2) that has children that do not overflow. The other children of Stack 1 will be after the first _SizedBox with child (Stack 2)_ and will be the widgets that _do_ overflow.

Here's a quick example that I've put together for a button that overflows the stack (second FAB with a check icon):

```
Scaffold(
      appBar: AppBar(
        title: Text('i.e Contact Details'),
      ),
      body: SizedBox(
        height: MediaQuery.of(context).size.height,
        child: Column(
          children: [
            SizedBox(
              height: 300, /* total size accounting overflow widgets * /
              /* +30 to the 270 in the second stack to take into account the remainder of the button (~60 total diameter of a FAB) */
             /* always add the size for all of widgets that overflow and need to be pressed,
                but only the size that overflows not the whole size of the widget.*/
              child: Stack(
                overflow: Overflow.visible, 
                children: [
                  SizedBox(
                    height: 270, /* size for widgets that are in the stack */
                    child: Stack(
                      children: [
                        Container(
                          color: Colors.grey[300],
                          width: double.infinity,
                          child: Center(
                            child: Text(
                              'i.e Put a contact image here',
                              style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          top: 150,
                          right: 20,
                          child: FloatingActionButton(
                            heroTag: 'i.e Edit Contact',
                            elevation: 0,
                            backgroundColor: Colors.white,
                            onPressed: () {},
                            child: Icon(
                              Icons.edit,
                              color: Colors.black,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  Positioned( /* FAB that overflows and need to be pressed, placed in the first stack */
                    top: 240,
                    right: 20,
                    child: FloatingActionButton(
                      heroTag: 'i.e Save Contact',
                      elevation: 15,
                      onPressed: () {
                        print(
                            'I can be pressed from anywhere even the parts where I overflow the stack xD');
                      },
                      child: Icon(Icons.check),
                    ),
                  ),
                ],
              ),
            ),
            Column(
              children: [
                Center(
                  child: Text(
                    'Do other great things here',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
```

**Comment by yashwp** [comment]
@fluttergithubbot Clean please fix this issue!!! None of the working around are working. You gotta seriously look into this!

**Comment by mehmetyilmaz001** [comment]
This issue must be fixed

**Comment by Akifcan** [comment]
move clickable widget bottom side like this
```
child: Stack(
          children: [
            ListTile(title: _productImage(context), subtitle: _productInfo),
            Positioned( //clickable widget
              right: 20,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  IconButton(
                    icon: Icon(Icons.shopping_basket),
                    onPressed: () {
                      context.read<User>().addFirstItemToBasket(product);
                    },
                  ),
                  Text('0'),
                  IconButton(
                    icon: Icon(Icons.add),
                    onPressed: () {},
                  ),
                  IconButton(
                    icon: Icon(Icons.remove),
                    onPressed: () {},
                  ),
                ],
              ),
            ),
          ],
        ),
```

**Comment by Lurzapps** [comment]
why is this error closed without a clean fix?

**Comment by Lurzapps** [comment]
https://stackoverflow.com/a/62500610/5899585

**Comment by IlyaMax** [comment]
https://dartpad.dev/2ec6318a6658af7501af8f482b84364f? solution

**Comment by leegohi04517** [comment]
why closed this issue

**Comment by snoopdoggy322** [comment]
Please fix this issue 🙏🏻

**Comment by esDotDev** [comment]
This is the best bet for getting a fix for this anytime soon, please share your use cases here: 
https://github.com/flutter/flutter/issues/75747

**Comment by yasinarik** [comment]
Why this issue is still considered as "works as expected" or "works as intended"?

Clearly, an undeniable amount of power users of Flutter facing it.

**Comment by AliYar-Khan** [comment]
> 
> 
> gesture detector is showing weird behavior... for one Screen it is working outside the stack and and for other screen it is not working.
> so i solved this using a container with padding top or bottom and color transparent... this way gesture detector detect tap as it comes inside of stack area and is clickable

code example will be appreciated

**Comment by Hwan-seok** [comment]
I faced the same issue now and resolved it as follows.
This can not apply to every case but some cases would be solved.
In my case, I need to overlap half of the tappable widget to the end of the bigger container.

The key is `Make a Stack bigger than you need and locate tappable positioned widget at the end`

```dart
SizedBox(
              width: dashboardContainerWidth,
              height: dashboardCenterContainerHeight + 50, <-- 
              child: Stack(
                clipBehavior: Clip.none,
                alignment: Alignment.center,
                children: [
                  Align(
                    alignment: Alignment.center,
                    child: Container(
                      height: dashboardCenterContainerHeight,
                      decoration: BoxDecoration(
                        color: AppColors.light_gray,
                        borderRadius: AppBorderRadius.circularMax,
                        border: Border.all(),
                      ),
                    ),
                  ),
                  Positioned( 
                    top: 0,
                    child: OrangeArrowButton( < -- height is 50, tappable widget
                      arrowIcon: AppIcons.arrow_upward,
                    ),
                  ),
                  Positioned(
                    bottom: 0,
                    child: OrangeArrowButton(< -- height is 50, tappable widget
                      arrowIcon: AppIcons.arrow_downward,
                    ),
                  ),
                ],
              ),
            ),
```

**Comment by mitchellsion** [comment]
> The key is `Make a Stack bigger than you need and locate tappable positioned widget at the end`

Wrapping `Stack` with `SizedBox` worked for me
``` dart
SizedBox(
  width: double.infinity, // or `height: double.infinity` based on your case
  child: Stack(
    children: [
      ...
    ],
  ),
)
```

**Comment by adschi** [comment]
Any updates on this? Got a production app and really need this feature.

**Comment by leegohi04517** [comment]
why closed the issue???

**Comment by marcglasberg** [comment]
Hey everyone, this issue was closed because it's now only asking for the documentation to clearly state the limitation.

This documentation change was actually done by https://github.com/flutter/flutter/pull/60726

Please note, there are other issues that could solve this, here: 
* https://github.com/flutter/flutter/issues/75747
* https://github.com/flutter/flutter/issues/31728

And there is also this package:
* https://pub.dev/packages/expand_tap_area
However, it really doesn't work well because it can't feel a tap outside of the parent's bound.
