### ISSUE TITLE
Tab Scroll Duration and Curve

### ISSUE THREAD

**Issue by ricnaaru** [flutter/flutter#19447]
So I am using Carousel library https://pub.dartlang.org/packages/carousel, and it uses `tabs.dart` (its `TabBarView`), and when I try to override `scrollduration` and curve, i have successfully update the property of `TabController`, but in `tabs.dart` still scrolling using `kTabScrollDuration` and `Curves.ease`, isn't it supposed to get from controller?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor` and the code that allows to reproduce.

**Comment by ricnaaru** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.103, on Mac OS X 10.12.6 16G29, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

• No issues found!
```

I don't think there's a problem with the flutter itself, but it's more like tabs.dart's bug causing TabController animation doesn't have the same AnimationCurve and AnimationDuration with TabBarView

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
