### ISSUE TITLE
Issue from website page Write Your First Flutter App

### ISSUE THREAD

**Issue by vphong** [flutter/flutter#19448]
From URL: https://flutter.io/get-started/codelab/

I was following the tutorial from this url, and the code from this specific page is outdated. When reaching [Step 6: Navigate to a new screen](https://flutter.io/get-started/codelab/#step-6-navigate-to-a-new-screen), both Android and iOS apps error'd out with a `'package:flutter/src/widgets/navigator.dart': Failed assertion: line xxxx: '!_debugLocked': is not
true.` I found the Google Codelabs version of this tutorial, and it works. (A major difference was the `final` constants' types are specified in the Google Codelabs version, when they are not specified in the flutter.io version.) I'm assuming this has to do with changes in Flutter.

Suggested solution: Link this doc directly to [Google Codelabs: Write Your First App, Part 1](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/index.html?index=..%2F..%2Findex) and [Google Codelabs: Write Your First App, Part 2](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/index.html?index=..%2F..%2Findex).

**Comment by Sfshaza** [comment]
Yes, this was outdated. Fixed in PR https://github.com/flutter/website/pull/1124.
