### ISSUE TITLE
flutter emulator --launch broken since recent roll

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#19453]
Two issues:

Original issue is:

> Failed to launch emulator: type 'EfficientLengthFollowedByIterable<String>' is not a subtype of type 'List<String>'

However it also looks like code handling exceptions assumes they're always bare strings:

## command

flutter emulators --launch ios

## exception

_TypeError: type '_TypeError' is not a subtype of type 'String'

```
#0      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:75:20)
<asynchronous suspension>
#1      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#9      Future._complete (dart:async/future_impl.dart:472:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.5.8-pre.58, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.5.8-pre.58 at /Users/dantup/Dev/Google/flutter
    • Framework revision 85f09f622e (68 minutes ago), 2018-07-16 22:42:06 -0700
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dantup/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/dantup/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
With the error handling fixed, here's the real error stack:

```
_TypeError: type 'EfficientLengthFollowedByIterable<String>' is not a subtype of type 'List<String>'

```
#0      IOSEmulator.launch.launchSimulator (package:flutter_tools/src/ios/ios_emulators.dart:43:12)
<asynchronous suspension>
#1      IOSEmulator.launch (package:flutter_tools/src/ios/ios_emulators.dart:54:31)
<asynchronous suspension>
#2      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:72:31)
<asynchronous suspension>
#3      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:667:32)
#11     Future._complete (dart:async/future_impl.dart:472:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

**Comment by DanTup** [comment]
Ugh, implicit cast again:

```
List<String> = strings.followedBy(moreStrings);
```

`followedBy` returns `Iterable`.

**Comment by DanTup** [comment]
https://github.com/flutter/flutter/pull/19454

**Comment by Hixie** [comment]
Update: We have a fix in hand, we will review it and land it once it's ready.
