### ISSUE TITLE
Should be possible to work with flutter offline

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1945]
Presumably after having done `flutter cache populate` or some such while online.

Right now there are a bunch of cases where we assume online.  I think this is far from critical, but there are still times when people are offline and would like to do development. :)

**Comment by eseidelGoogle** [comment]
I'm actually tempted to close this or push this off past 1.0.  Needing offline support is a problem of success. :D

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/1977 about XcodeProject.zip not being an artifact.

**Comment by gspencergoog** [comment]
I think we're pretty close to this.  We have downloadable archives that are pre-populated, and if you supply `--offline` to `flutter create` and `flutter packages get`, then it is possible to work offline (if you've pre-populated your pub cache with what you need, that is).

**Comment by gspencergoog** [comment]
Closing this because I feel like we have an acceptable offline experience. There are still some rough edges, but you can work with flutter offline.
