### ISSUE TITLE
InputDecoration prefixPadding

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#19460]
Would be very helpful if you could add some padding to the InputDecoration prefix text to make some space between the "text area" and the prefix text.

**Comment by HansMuller** [comment]
Despite the name, you could use InputDecoration's prefixIcon, a widget, and pad it however you like: https://docs.flutter.io/flutter/material/InputDecoration/prefixIcon.html

**Comment by christian-muertz** [comment]
Ok there is one problem: This is the implementation of the prefixIcon:
```
final Widget prefixIcon = decoration.prefixIcon == null ? null :
      new Center(
        widthFactor: 1.0,
        heightFactor: 1.0,
        child: new ConstrainedBox(
          constraints: const BoxConstraints(minWidth: 48.0, minHeight: 48.0),
          child: IconTheme.merge(
            data: new IconThemeData(
              color: iconColor,
              size: iconSize,
            ),
            child: decoration.prefixIcon,
          ),
        ),
      );
```
As it can be seen there are some box constraints which require a min height of 48.0. Normal text isn't that high... So it would be nice if there were a property like prefixPadding or if prefixText were a Widget instead of a String!

**Comment by chrisDK1977** [comment]
I tired to use the suffixIcon to get an IconButton into a TextField with InputDecoration. But the minimum width/height of 48px makes my TextInput to high. It would be really great to have influence on the with/height of the prefixIcon!
