### ISSUE TITLE
No longer able to debug since todays update on master

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#19464]
Hi,

since today my App either doesn't start up at all or crashes after some time with the message that the connection is lost.

I attach the log from CS code

[Dart-Code-Log-2018-06-02 13-27.txt](https://github.com/flutter/flutter/files/2201425/Dart-Code-Log-2018-06-02.13-27.txt)

My enviroment:

```
PS C:\Entwicklung\FlutterApps\Projects\JoinOrCreate\JoinOrCreate_Mobile> flutter doctor -v
[√] Flutter (Channel master, v0.5.8-pre.58, on Microsoft Windows [Version 10.0.17134.165], locale de-DE)
    • Flutter version 0.5.8-pre.58 at C:\Entwicklung\Flutter
    • Framework revision 85f09f622e (6 hours ago), 2018-07-16 22:42:06 -0700
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition (version 1.25.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.16.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by escamoteur** [comment]
Update: It seems that this only happens if `break on exceptions` is enabled.

**Comment by zoechi** [comment]
Looks a bit like a dup of #19379

**Comment by escamoteur** [comment]
Rolling back: `git reset --hard e22f99743b4f0bea4a9b8e7703ce5ffbfda37a04` fixed it it

**Comment by DanTup** [comment]
Yep, I'm pretty certain this is the same as https://github.com/flutter/flutter/issues/19379 (which I think is also causing me issues with Dart Code debug adapter integration tests).

New integration tests in https://github.com/flutter/flutter/pull/19473 which fail since the last engine roll.

**Comment by escamoteur** [comment]
Seems to be fixed with
Flutter 0.5.8-pre.61 • channel master • https://github.com/flutter/flutter
Framework • revision b8b6d4166c (7 hours ago) • 2018-07-17 18:07:54 -0700
Engine • revision 5557e3006e
Tools • Dart 2.0.0-dev.67.0.flutter-84ca27a09e

**Comment by DanTup** [comment]
Great, thanks for confirming!
