### ISSUE TITLE
Issue from website page Reading and Writing Files

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#19461]
From URL: https://flutter.io/cookbook/persistence/reading-writing-files/

I've changed the code a little bit so as not to use the path_provider package if it creates problems. The function **_localFile** has been changed:

 ```
 Future<File> get _localFile async {
    //final path = await _localPath;
    //return File('$path/counter.txt');
    return File('counter.txt');
  }
```

I also added the next permissions to the AndroidManifest.xml file:

```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

```
However, if change the counter, an error occurs:

```
D/ViewRootImpl(31529): ViewPostImeInputStage ACTION_DOWN
E/flutter (31529): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (31529): FileSystemException: Cannot open file, path = 'counter.txt' (OS Error: Read-only file system, errno = 30)
E/flutter (31529): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
E/flutter (31529): #1      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (31529): #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (31529): #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (31529): #4      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (31529): #5      Future._completeWithValue (dart:async/future_impl.dart:477:5)
E/flutter (31529): #6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
E/flutter (31529): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (31529): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```
What is the reason?

**Comment by zoechi** [comment]
Not sure what you expect but `File('counter.txt')` references the file `/counter.txt` and the app won't have read or write access there.
You need to use the `path_provider` package (or other similar plugins) to get paths where writing application data makes sense.

I think this is working as intended.

**Comment by micrcx** [comment]
/home/misha/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2017.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[!] VS Code (version 1.18.0)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
Process finished with exit code 0

**Comment by zoechi** [comment]
@micrcx you think you should be able to write into the system root folder?

**Comment by micrcx** [comment]
The error is clear. I just assumed by stupidity that maybe flutter by default writes the file to the application space if path contains only file name without folders.
