### ISSUE TITLE
Adding activity before running FlutterActivity

### ISSUE THREAD

**Issue by development-s365** [flutter/flutter#19472]
Hi

Due to a specific authentication flow i need to add an Activity before starting up the FlutterActivity.
Is this possible?
I already tried changing the manifest.

Kind regards.

**Comment by zoechi** [comment]
Is this about integrating Flutter into an existing app or a pure Flutter app?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
