### ISSUE TITLE
Is it possible TextField has multi-line looking?

### ISSUE THREAD

**Issue by skeksk91** [flutter/flutter#19471]
This is my state now which is common TextField.

![image](https://user-images.githubusercontent.com/4088583/42825098-3e7f7a5a-8a1c-11e8-8942-fd29dc0dff00.png)
```

new TextField(
                    maxLines: null,
                    keyboardType: TextInputType.text,
),
```

-------------------------------------------------------------------------------------------------------------------

**I want to make textField with multilne looking like this,**

![image](https://user-images.githubusercontent.com/4088583/42825548-37627b36-8a1d-11e8-9684-24e6fee312c3.png)
**(The photo already has all lines but new line added when new line started)**
Sorry for not correct photo exactly.

but I cannot find how to keep last lines. 

Is there any property for this situation? 
I searched in TextField documentation, but failed..

**Comment by zoechi** [comment]
`TextField` doesn't provide such a feature out of the box.

**Comment by skeksk91** [comment]
@zoechi 
Thank you for your response. Then I will implementation.
