### ISSUE TITLE
On Edge Swipe Gesture

### ISSUE THREAD

**Issue by adriancmurray** [flutter/flutter#19474]
This is a relatively simple question that I've not been able to locate. Is there a way to detect edge swipes such as when Scaffold does for Drawers? @Hixie ?

**Comment by Hixie** [comment]
Sure, do it the same way Scaffold does it. A gesture detector for a drag gesture at the edge of the screen.

**Comment by goderbauer** [comment]
This is implemented in the `_CupertinoBackGestureDetector` [1] in the framework. As said above, you can do the same in your app.

[1] https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/route.dart#L528-L543

**Comment by rajeshzmoke** [comment]
how do i disable edge swipe to open drawer
