### ISSUE TITLE
Issue from website page Get Started: Install on Windows

### ISSUE THREAD

**Issue by u2arejust2cute** [flutter/flutter#19479]
From URL: https://flutter.io/setup-windows/

For the international users, it is very helpful to know that "Control Panel > ..." means "In Windows, go to Control Panel". This could be anywhere.

Secondarily, it should mention somewhere to use the 'flutter config' command to set the sdk path in case it was already installed.

Not related to these issues: I am not sure how legal it is to make users accept agreements they can't read fully because the flutter command line can't show all of their text.

**Comment by u2arejust2cute** [comment]
And while I am at it: Is or isn't ANDORID_HOME depreciated? Because it shows up in the flutter doctor and on the website and it is supposedly no longer used.

**Comment by xster** [comment]
We may need to multiplex these instructions with various Windows versions too. For instance "Control Panel > User Accounts > User Accounts > Change my environment variables" may not exist in the newest version of Windows.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1914](https://github.com/flutter/website/issues/1914) via [**ZenHub**](https://www.zenhub.com/)
