### ISSUE TITLE
Problem with StreamBuilder and Firebase

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#19487]
_From @Shamzic on July 17, 2018 21:32_

The StreamBuilder widget with Firebase can't be displayed when it is inside a children bracket. 
Furthermore it works when it is a simple child.

I have found this post wich resume the same problem : https://stackoverflow.com/questions/50792605/streambuilder-widget-is-not-rendered-if-nested-in-children-widget

Hope someone will find a solution !
Thanks !

_Copied from original issue: dart-lang/sdk#33895_

**Comment by zoechi** [comment]
@Shamzic glad to hear you could make it work. Thanks for the update.
I assume it's ok to close this issue.
