### ISSUE TITLE
Sign in to Xcode 

### ISSUE THREAD

**Issue by Kumuda123** [flutter/flutter#19485]
<img width="722" alt="screen shot 2018-07-17 at 4 04 37 pm" src="https://user-images.githubusercontent.com/35873647/42845341-3999b60e-89db-11e8-8a3f-856d3bc67b7f.png">
I am trying to sign in into xcode using my apple ID but it is throwing an error - The app ID "com.test.testApp" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

How can i resolve this ?

**Comment by zoechi** [comment]
Sounds like the name is already taken. That problem doesn't seem to be related to Flutter.
