### ISSUE TITLE
Runner.xcworkspace 

### ISSUE THREAD

**Issue by Kumuda123** [flutter/flutter#19482]
1. ... In the flutter document, we have to open the default Xcode workspace in your project by running open ios/Runner.xcworkspace in a terminal window from your Flutter project directory.

However, when I run this command it says that ios does not exist. Do I need to be in a certain directory to run this command ? 
## Logs

```
```

**Comment by zoechi** [comment]
`open ios/Runner.xcworkspace` requires the project root directory, the one that contains `pubspec.yaml` to be the current directory.

**Comment by Kumuda123** [comment]
<img width="698" alt="screen shot 2018-07-17 at 3 02 29 pm" src="https://user-images.githubusercontent.com/35873647/42842317-815ac270-89d2-11e8-8f23-2e2836b47adf.png">
I typed find . -name Runner.xcworkspace. Out of these which one do i need to cd into ?

**Comment by zoechi** [comment]
You should look for `pubspec.yaml`, the root directory of your project.
`./examples/hello_world` is probably such a directory. It should contain a `pubspec.yaml` and from your screenshot a `ios/` directory. 
This is usually how Flutter project directories are organizes (besides other files and directories).

If you use `flutter create foo` you will get a `./foo/` directory with the usual content of a Flutter project that you can use to make yourself familiar with the project structure.

**Comment by aidanldeary** [comment]
I experienced the same error when running "open ios/Runner.xcworkspace" in the terminal without the the simulator iOS device running. Opening the simulator (as per "open -a simulator" in the terminal) resolved this

**Comment by yajna-pandith** [comment]
change the directory to " flutter/examples/catalog " and then run the command " open ios/Runner.xcworkspace "
