### ISSUE TITLE
The app ID "com.example.myapp" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

### ISSUE THREAD

**Issue by Kumuda123** [flutter/flutter#19498]
<img width="1263" alt="screen shot 2018-07-17 at 9 12 44 pm" src="https://user-images.githubusercontent.com/35873647/42855444-2ee5af26-8a06-11e8-9ad4-24e78e1bd834.png">

I am not able to connect my apple ID with Xcode. Any ideas on how to solve this issue ??
Also in my iPhone, I am not able to locate General > Device Management. Did anyone have the same problem ?
Thanks 
Kumuda

**Comment by jonasbark** [comment]
Enter a different bundle identifier.

**Comment by Kumuda123** [comment]
I tried different bundle identifier but it does not work.

**Comment by jonasbark** [comment]
Which one? It must be unique. E.g. com.kumuda123.example or something like that.
What error do you get?

**Comment by Kumuda123** [comment]
<img width="588" alt="screen shot 2018-07-18 at 1 52 06 am" src="https://user-images.githubusercontent.com/35873647/42864792-39b52f68-8a2d-11e8-9ad8-b5593946657a.png">

**Comment by Kumuda123** [comment]
<img width="447" alt="screen shot 2018-07-18 at 1 54 38 am" src="https://user-images.githubusercontent.com/35873647/42864879-90f7be3a-8a2d-11e8-99ab-eb7ab8d761a9.png">
My phone is connected to my laptop.

**Comment by jonasbark** [comment]
Can you run it on an emulator?
Btw this is in no way an error of the flutter project. You might want to find solutions over at stackoverflow.com.

**Comment by Kumuda123** [comment]
Yes i can run it on the Simulator. Also how should I open main.dart ? Whenever i open, it gives me this error. 
<img width="367" alt="screen shot 2018-07-18 at 2 02 58 am" src="https://user-images.githubusercontent.com/35873647/42865316-e648a8bc-8a2e-11e8-9e77-2007778086f9.png">

**Comment by jonasbark** [comment]
There are several tutorial videos over at youtube that can help you setup a flutter project.

**Comment by jmagman** [comment]
I don't think there's a bug to track here.  The error is coming from Xcode, and the error message is pretty clear about what to do.  Seems like a setup issue covered on stackoverflow.

**Comment by huyvuro** [comment]
what is unique ID
Give me an example
tsk

**Comment by jmagman** [comment]
@huyvuro Flutter didn't generate this error.  Feel free to file an issue with Apple https://feedbackassistant.apple.com
