### ISSUE TITLE
flutter_gallery__back_button_memory & flutter_gallery__memory_nav are flaky (timeout)

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#19490]

**Comment by goderbauer** [comment]
I did some investigation on this and was able to reproduce the flakes on a Moto device (every 3rd or 4th run seemed to be failing). I did not see any flakes while running on a Pixel XL.

When the test fails, it hangs (for 30+ seconds) either on
```
Request to Dart VM Service timed out: getIsolate
```
or
```
Request to Dart VM Service timed out: _flutter.listViews
```
If the test passes, these requests seem to complete in at most 200ms. This does not seem to be a timeout issue because the timeout is 30s.

**Comment by goderbauer** [comment]
To investigate this further it has been suggested to add add '--trace_service' flag to dart_vm.cc dart flags. Thatmight shed some light as to what requests the vm received and processed.

**Comment by goderbauer** [comment]
Also affected by this with the same symptoms is: `flutter_gallery__memory_nav`

**Comment by Hixie** [comment]
@rmacnak-google Any luck? This is blocking our rolls and blocking the next beta release.

**Comment by rmacnak-google** [comment]
How does one even run this? The only reference to "back_button" in either the framework or cocoon repositories does not name a command.

**Comment by goderbauer** [comment]
```
cd dev/devicelab
dart bin/run.dart -t flutter_gallery__back_button_memory
dart bin/run.dart -t flutter_gallery__memory_nav
```

See https://github.com/flutter/flutter/tree/master/dev/devicelab#running-tests-locally

**Comment by rmacnak-google** [comment]
```
{type: VM, ..., isolates: [{type: @Isolate, fixedId: true, id: isolates/707575481, name: main.dart:_spawn(), number: 707575481}, {type: @Isolate, fixedId: true, id: isolates/543235500, name: main.dart:main(), number: 543235500}]}
```
The harness is waiting for a response from a temporary isolate the framework has spawned, depending on whether it's `getVM` is processed between the temporary isolate starting and finishing.

**Comment by Hixie** [comment]
@rmacnak-google Can you elaborate on that? Where are we spawning a temporary isolate and how is the test running into it?

**Comment by Hixie** [comment]
@rmacnak-google Two questions:
- Is there a way to identify isolates so that we can request the "main" one?
- Is there a way for us to give data to `Isolate.spawn` to name it for debugging purposes? (I'm not sure where you were looking for the name.)

**Comment by rmacnak-google** [comment]
The VM has no concept of a main isolate, that's an interpretation of the embedder. The IsolateRef (in the response to `getVM`) has a property "number", which the VM promises corresponds to Dart_GetMainPortId() and it promises to be unique. An embedder may provide its own service extension to associate extra properties with isolates based on this mapping. IsolateRef also has a property "name", which is related to the arguments the engine passed in Dart_CreateIsolate, but that VM does not promise to have any particular format or be unique. There's an inactive CL that would give the embedder the full choice of the name.

There is no mechanism to plumb extra data from `Isolate.spawn` through to the engine in the create isolate callback (where it could affect the name in Dart_CreateIsolate).

**Comment by rmacnak-google** [comment]
I don't see any flakes since https://github.com/dart-lang/sdk/commit/6a4d64fe0cb50fbf682a228e8b49eb950179ed35 with rolled in with https://github.com/flutter/flutter/commit/1b5dd718d8f3a44fe50d39473bdd9486619d6e1a

**Comment by goderbauer** [comment]
@rmacnak-google can you remove the flakiness label from the tests in https://github.com/flutter/flutter/blob/master/dev/devicelab/manifest.yaml if they are no longer flaky before closing this?
