### ISSUE TITLE
The name 'PlatformException' isn't a type and can't be used in an on-catch clause

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#19499]
![image](https://user-images.githubusercontent.com/5095376/42856465-fdc3bb1e-8a77-11e8-9600-ff8f57dcc58d.png)

WHY IT IS ERROR ??

**Comment by jason-simmons** [comment]
PlatformException is documented here:
    https://docs.flutter.io/flutter/services/PlatformException-class.html

To use it, import the services library:
    ```import 'package:flutter/services.dart'```

**Comment by nikhiljha** [comment]
This is sort of a bug because the Android Studio/VSCode help doesn't suggest importing it.

**Comment by zoechi** [comment]
@nikhiljha for that please upvote and follow dart-lang/sdk#25820

**Comment by adamobrien4** [comment]
Solution:
I had the same problem, I fixed it by importing the following:

`import 'dart:io' show Platform;`

and then using the following:

`try {
    . . . 
} on PlatformException catch (ex) {
    . . .
} . . .`

Hope this helps.
