### ISSUE TITLE
retrieveDynamicLink() is always null

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#19506]
_From @blaneyneil on July 12, 2018 22:29_

URL: https://pub.dartlang.org/packages/firebase_dynamic_links

i'm using version 0.0.5 and on iOS.  i haven't ever been able to use:

`dart
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.retrieveDynamicLink();
`
and get a non-null value for that data var.  that includes clicking on links i've generated in the firebase console, and thru buildUrl() and/or manually.  it doesn't matter if the app is open in the bg, closed, or coming out of a hard reboot.  and i've used both the simulator and a real device, and clicked on the link from sms and email.

generating links works as expected, and clicking on the link(s) always opens the app as expected (everything is configured properly in firebase and xcode).  to make sure i wasn't missing anything i reduced my app to this entry point:

```dart
void main() async {

  final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.retrieveDynamicLink();
  print('main link = $data');

  runApp(MaterialApp(
    home: new LinksTest(data: data),
  ));

```

and rendered LinksTest like so:

```dart
import 'package:flutter/material.dart';

class LinksTest extends StatelessWidget {
  var data;
  LinksTest({this.data});

  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new Text(data.toString(), style: new TextStyle(color: Colors.white, fontSize: 14.0)),
    );
  }
}
```

no matter what i do, the app always opens but data is always null.

_Copied from original issue: dart-lang/pub-dartlang-dart#1451_

**Comment by isoos** [comment]
@blaneyneil: please file such request to the package's repository, in this case flutter/flutter. I'm moving this now.

**Comment by MohamedBerrada** [comment]
I'm experiencing the same issue on iOS, the future returned by the retrieveDynamicLink method always completes to null but works completely fine on Android.

**Comment by diegoveloper** [comment]
I had the same problem but I already solved, You can check the post that I published : https://medium.com/@diegoveloper/flutter-firebase-dynamic-link-6f1b79278ce0

**Comment by MohamedBerrada** [comment]
Yes, I read the post rechecked everything and I've added the delay but I still get a null value.
Thanks for the post though!

**Comment by ordsen** [comment]
I have the same issue as well. Deep links work perfectly on Android but on iOS `retrieveDynamicLink()` always returns null (even if I add that delay @diegoveloper suggested) and I don't see how to make it work.

**Comment by diegoveloper** [comment]
The library was already updated: https://pub.dartlang.org/packages/firebase_dynamic_links ,  did you check the post I mentioned?

**Comment by ordsen** [comment]
Thanks for pointing out, do you mean that issue with the dynamic link not being removed after retrieving it (Problem 3 in your post)? I can't test that one yet as I can't even retrieve the link in the fist place. I'll check if that will be an issue as soon as I manage retrieving the link parameter when my app is started through a tap on a deep link though

**Comment by diegoveloper** [comment]
does it works on android? on iOS is a little different , for that reason I had to add a delay before get the dynamic link.

**Comment by ordsen** [comment]
Yes, and on iOS my app is even started through a tap on the link, it's just that `retrieveDynamicLink()` call that doesn't work as expected.

**Comment by diegoveloper** [comment]
did you add a delay?

**Comment by ordsen** [comment]
Yes. Did you do any special initialization/set up of the plug in I might have missed in your code? And would you mind tell me which parameters you set for your dynamic link for iOS? So which of the parameters [here under 'iOS parameters'](https://firebase.google.com/docs/reference/dynamic-links/link-shortener) did you set and which did you leave empty? I'm just wondering if my problem is caused by a wrong configuration as, apparently, you made it work and my code does not differ form yours.

**Comment by ordsen** [comment]
Never mind I got it working by upgrading to the latest version of Flutter :)

**Comment by kaumudpa** [comment]
Anyone have a resolution to this??? at my end Android part is working properly but for iOS the link works if the app is in the background, But if the app is not in the background, the link launches the app but `retrieveDynamicLink()` is always returned as `null` Any Workaround ???????

**Comment by sunojvijayan** [comment]
@diegoveloper I did like you mentioned. Here is my code.

`@override
  void initState() {
    super.initState();
    checkPreviousData();
    WidgetsBinding.instance.addObserver(this);
  }

@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _timerLink = new Timer(const Duration(milliseconds: 850), () {
        checkPreviousData();
      });
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    if (_timerLink != null) {
      _timerLink.cancel();
    }
    super.dispose();
  }`

In Android everything works fine. In iOS after app installation, if I click the link everything works. But if the app is not installed and I click the link go to appstore and install the app, its not working. The link is null. Any suggestions?

**Comment by kbrmimbyl** [comment]
This thing is freaking me out. Retrieving dynamic link (when app is not installed) working on some two devices (one Android, one iOS), but it doesn't work generally. I'm doing this:
```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _timerLink = Timer(const Duration(milliseconds: 1000), () {
        // Retrieve dynamic link here if app was just installed,
        // or if the user clicked on a dynamic link when app was in the background
        _retrieveDynamicLink();
      });
    }
  }
```
Guys at Google... does this thing work? Why are you shipping this?

**Comment by kafein** [comment]
Hi. I have exact problem 1 week ago. If you use **custom domains** you need to add **FirebaseDynamicLinksCustomDomains** key to your Info.plist file like this;

```
<key>FirebaseDynamicLinksCustomDomains</key>
<array>
  <string>https://example.com/link</string>
  <string>https://example.com/promos</string>
</array>
```

**Comment by longphanmn** [comment]
@kafein thanks man
works after added the key

**Comment by sceee** [comment]
@kafein thank you very much, that also solved it for me. Saved me hours!

**Comment by tapkain** [comment]
always troubles with the shiny ios, f**k that...
P.S. did somebody manage to open the dynamic link on iOS when the app is closed?

**Comment by Catsys** [comment]
what about click handler? I just can’t handle the click through. A new version has already been released, in which the timer is not needed. The callback is registered and it should process, but it does not work!

**Comment by droid-it** [comment]
> @diegoveloper I did like you mentioned. Here is my code.
> 
> ```dart
> @override
>   void initState() {
>     super.initState();
>     checkPreviousData();
>     WidgetsBinding.instance.addObserver(this);
>   }
> 
> @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     if (state == AppLifecycleState.resumed) {
>       _timerLink = new Timer(const Duration(milliseconds: 850), () {
>         checkPreviousData();
>       });
>     }
>   }
> 
>   @override
>   void dispose() {
>     WidgetsBinding.instance.removeObserver(this);
>     if (_timerLink != null) {
>       _timerLink.cancel();
>     }
>     super.dispose();
>   }
> ```
> 
> In Android everything works fine. In iOS after app installation, if I click the link everything works. But if the app is not installed and I click the link go to appstore and install the app, its not working. The link is null. Any suggestions?

I too am stuck at this problem. The link works fine if the app is installed. But if not installed, it redirects to app store but post installation, the deeplink is null on app launch

**Comment by kroikie** [comment]
@isoos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/751. Any further collaboration will be done there.
