### ISSUE TITLE
Mistake in Flutter Documents IndexedStack class

### ISSUE THREAD

**Issue by shashikantdurge** [flutter/flutter#19501]
'fit'property is there in IndexedStack class(flutter docs).
But couldn't find it in the Flutter Code.
https://docs.flutter.io/flutter/widgets/IndexedStack-class.html

**Comment by aravind99** [comment]
You can find `fit` option in parent class of IndexStack i.e. Stack.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/basic.dart#L2702

**Comment by shashikantdurge** [comment]
Thank you for that..
