### ISSUE TITLE
"flutter run --flavor flavorname" fails if gradle flavor contains uppercase letter

### ISSUE THREAD

**Issue by freewheelnat** [flutter/flutter#19507]
build.gradle

```
 productFlavors {

        CLEnToFr {
            dimension "app"
        }
    }
```

`flutter run --flavor clentofr` and `flutter run --flavor CLEnToFr` both build the apk file but they then both end with error message `Gradle build failed to produce an Android package`. The apk is saved, as expected, in `.../CLEnToFr/` folder.

If I change the gradle file to have lowercase letters only, eg "clentofr", everything works fine.

**Comment by jorgecoca** [comment]
I am experiencing the same issue, while it works fine on iOS. Is there an ETA for this fix?

**Comment by felangel** [comment]
Having the same issue as well

**Comment by jorgecoca** [comment]
I believe this is preventing any Android app with flavors configured to ship, right? Or what would be the workaround?

**Comment by jorgecoca** [comment]
In [packages/flutter_tools/lib/src/android/gradle.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L492) we can find this:

```dart
  String _buildTypeFor(BuildInfo buildInfo) {
    final String modeName = camelCase(buildInfo.modeName);
    if (buildTypes.contains(modeName.toLowerCase()))
      return modeName;
    return null;
  }
```

Could this be the problem? Would be the fix removing those `toLowerCase()`?

**Comment by freewheelnat** [comment]
@jorgecoca It seems like it could be the issue.

It is preventing Android apps with uppercase in their flavor names to ship. So the workaround is to change the flavor name to lowercase (it works fine in that case).

**Comment by jorgecoca** [comment]
It is a problem if you actually use flavor dimensions, since then it Gradle will expect a camel case format when composing the flavor.

**Comment by jorgecoca** [comment]
@zoechi thoughts on the given solution? Should we go ahead and open a PR?

**Comment by zoechi** [comment]
cc @tvolkert  @gspencergoog ?
