### ISSUE TITLE
scaffold support edge-swipe,is there way to implement fullscreen-swipe?

### ISSUE THREAD

**Issue by jiangjh** [flutter/flutter#19510]

**Comment by allandaleho** [comment]
@jiangjh Hi have you found anything for this feature? I think I can use something like this for specific screens and would provide a great user experience.

**Comment by goderbauer** [comment]
Can you add more details? What is a fullscreen-swipe and what would you want to do with it?

In general, you can use a GestureDetector [1] to detect all kinds of gestures.

[1] https://master-docs.flutter.io/flutter/widgets/GestureDetector-class.html

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
