### ISSUE TITLE
Add Elaborate Camera Example To Camera Package

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#19515]
The [camera ](https://pub.dartlang.org/packages/camera) dart package has a super useful [example](https://github.com/flutter/plugins/tree/master/packages/camera/example) widget that manages switching cameras and taking pictures.
Most developers will just copy-paste this implementation into their app as a separate page (ie for an image submission form). It'd be really valuable if either:
This example was supplied as a widget in the camera package
or
The example was made into its own package that is dependent on the camera package.

**Comment by stuartmorgan** [comment]
> The example was made into its own package that is dependent on the camera package.

This is something that would be best done as a third-party package depending on the camera plugin--or multiple such packages with different designs, features, etc.--as there's no specific reason it would need to be a first-party plugin. (Essentially what a package like `chewie` provides for `video_player`.)
