### ISSUE TITLE
firebase_auth missing critical methods

### ISSUE THREAD

**Issue by ffeu** [flutter/flutter#19525]
Despite of #17343 and #18959, these critical methods are still missing for the firebase_auth plugin.

```FirebaseUser.updatePassword()```
```FirebaseUser.delete()```

Due to security, updateEmail(), updatePassword() and delete() require a recent authentication, which then could be accomplished using the also absent ```FirebaseUser.reauthenticate()```.

Finally, without the one below, firebase e-mail templates will be sent only in English.
```FirebaseAuth.setLanguageCode()```

**Comment by zoechi** [comment]
`updatePassword` is covered by #16775 `delete` by #15907
I'm closing this as dup. 
PRs welcome ;-)

**Comment by ffeu** [comment]
@zoechi one last question, is FirebaseAuth.setLanguageCode being covered anywhere?

PRs - I'll try! :)

**Comment by zoechi** [comment]
@ffeu I didn't stumble upon that one yet.
Feel free to create a new issue for that one.
PR is especially welcome ;-)

**Comment by JosephDunivan** [comment]
What about passwordless signon with deeplink?
