### ISSUE TITLE
TextField inside a TabBarView causes horizontal wobble

### ISSUE THREAD

**Issue by shinyford** [flutter/flutter#19523]
Opening the keyboard and typing in a text field causes the whole page to wobble, when that text field is on a page inside a TabBarView.

## Steps to Reproduce

1. Clone https://github.com/shinyford/text_field_scroll_demonstrator and deploy to a device or emulator.
2. Click into a text field, and watch the page wobble horizontally as the keyboard opens.
3. Type a few characters and delete them: another wobble as the cursor deletes the last character
4. Type multiple characters to fill the text field: another wobble when the cursor gets to the RH edge

Video demonstrating the wobble: https://photos.app.goo.gl/oQeQK6XXXuDMp7zz7

## Logs

Logs are in the file `logs.txt` in the top level of the above repo.

Flutter analyze:
```
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.5 17F77, locale en-GB)
    • Flutter version 0.5.7 at /Users/nicford/Applications/flutter
    • Framework revision 66091f9696 (9 days ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/nicford/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • iPhone 6s • 74A9D8B0-D9B2-4B68-8614-918D02CC4502 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by SteveAlexander** [comment]
This happens on the dev channel but not on beta. So I guess that means it's a regression.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by Hixie** [comment]
cc @goderbauer this might be fallout from your auto-scroll-to-text-field logic; would you mind taking a look?

**Comment by goderbauer** [comment]
@Hixie It sure is an amusing fall-out of that logic. 

We currently do not differentiate between Scrollables that are allowed to scroll implicitly (e.g. a horizontal list, which should scroll to bring the cursor of a textfield into view) and that are not allowed to scroll implicitly (e.g. scrollers that handle the scroll between two tabs or pages, bringing a textfield back into view should never scroll these).

 I am looking into adding a property to ScrollPhysics that differentiates the two and can be used by the auto-scroll-to-text-field logic as well as the a similar problem with implicit accessibility scrolling on Android.

**Comment by SteveAlexander** [comment]
I think this has regressed: I opened a new bug for this, with an example repo. The wobble this time is up-down rather than side-to-side. Please see #20485

I just verified this against today's Channel master.
