### ISSUE TITLE
[Plugin Request] Cardboard SDK (Update: Google VR SDK not supported anymore)

### ISSUE THREAD

**Issue by nosmirck** [flutter/flutter#19529]
As the title says, we'd like to have a plugin for Google VR SDK (Cardboard and Daydream) for Flutter.

[https://github.com/googlevr/gvr-android-sdk](https://github.com/googlevr/gvr-android-sdk)

At least a 3D 360 VR Video player.

Thanks.
EDIT: If there's anyone out there working on this, please link your repo, I'd like to help.

EDIT 2: GVR SDK seems to be deprecated and Google is not supporting it nor Daydream anymore, however, the Open Sourced [Cardboard SDK](https://github.com/googlevr/cardboard) (by Google) is still under active development and supported with only a plugin for Unity3D.

**Comment by VarolOkan** [comment]
A Cross Platform 3D / VR / AR interface would really complete a big missing chunk of functionality for Flutter.

Is there any way to up-vote this feature request ?

**Comment by ATaysikuu** [comment]
Have to agree, it would be a real blessing to see this coming to Flutter!

**Comment by ilerik** [comment]
+1

**Comment by jamesdixon** [comment]
Is anyone aware of a way to play 360 video? Recently had a client request this.

**Comment by haithamelmengad** [comment]
Any updates on this ?

**Comment by julien-tamade** [comment]
Any updates on this?

**Comment by lorritt** [comment]
It's a real shame that this huge missing feature is being ignored still :(

**Comment by emmanuel-montoya** [comment]
Any update here?

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
