### ISSUE TITLE
Ability to refuse keyboard opening in textfield widget if tapped on it.

### ISSUE THREAD

**Issue by gaurav1999** [flutter/flutter#19521]
Hello,
I was trying to make an Calculator app , I am new to flutter , So when going through building app , I used textfield widget to take handle display the input and output.  This widget comes with controller property by whose help I am manipulating text , But I really don't need it's keyboard calling capability , every time I press on that area the keyboard opens up which totally removes the need of designing the Numeric buttons in UI , So I wanted to stop it popping , therefore , I searched and tried a lot , but did not find anyway to control  it , there was a way but it is not what I require , they do it by making a focusNode and use some Raisedbutton's onpress to change it , now this does not solve my problem , I found the unfocus method in documentation which seems to me can solve this problem , I don't know how to use it ,there is no example in there for it , I just want that I can use textfield widget without invoking any keyboard on tapping it.

**Comment by zoechi** [comment]
I believe this is a dup of #16863
Tentatively closing.
Please update the other issue or add a comment to get this issue reopened if you disagree.
