### ISSUE TITLE
Talkback reads character counter as a fraction 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#19520]
In the trailing character counter on the TextField, "4/8"  is read as "four eighths".  Should probably be something like "4 out of 8" or "4 of 8"

**Comment by thphuc** [comment]
@jonahwilliams I may look at this issue. Can you provide more info of how to reproduce? It would be great if you point out which class I should take a look. Thanks!

**Comment by jonahwilliams** [comment]
Hi @thphuc  to see the issue I would turn on [TalkBack](https://support.google.com/accessibility/android/answer/6283677?hl=en) on an Android device and navigate to the text fields demo in the gallery. If you select a text field with a character counter, you will hear talkback read out the label.

We need to figure out whether it is possible to correctly format this value, or whether we just have to map it to https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#setMaxTextLength(int)  on Android. This latter part might not be an easy fix at all.

**Comment by thphuc** [comment]
Great @jonahwilliams
