### ISSUE TITLE
Video_player is not working with IOS Simulator

### ISSUE THREAD

**Issue by phuongdanh** [flutter/flutter#19531]
Dear all, 
I tried to create application to play video, i followed the example https://pub.dartlang.org/packages/video_player 
It did not worked on Iphone 7 Simulator.
Thanks

**Comment by wwwdata** [comment]
Video do not work in Simulators and only on phones at the moment.

**Comment by zoechi** [comment]
As @wwwdata mentioned this is a known issue.
Closing as dup of #14647
