### ISSUE TITLE
File operations using flutter differently executed in different versions of Android.

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#19530]
I've found that the file operations in flutter when using _path_provider_ are differently executed in different versions of Android:
1) **Android 5.1** (Samsung 6): recursive creation of folders works without problems both in the application space: _getApplicationDocumentsDirectory()_, and on external memory: _getExternalStorageDirectory()_. Creation of files is also performed without problems.
2) **Android 6.0.1** (LG G5 SE) and **Android 7.0** (LG-V520): in the application space you can create a file or folder, but recursive creation of folders like _getApplicationDocumentsDirectory () + "/a/bb/ccc"_ is impossible, but this issue not critical. Creating files on external memory is simply impossible:

```
I/flutter (23327): /storage/emulated/0 -- exists
E/flutter (23327): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (23327): FileSystemException: Cannot open file, path = '/storage/emulated/0/scheme.json' (OS Error: Permission denied, errno = 13)
E/flutter (23327): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
E/flutter (23327): #1      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (23327): #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (23327): #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (23327): #4      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (23327): #5      Future._completeWithValue (dart:async/future_impl.dart:477:5)
E/flutter (23327): #6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507:7)
E/flutter (23327): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (23327): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/FlutterActivityDelegate(23327): onResume setting current activity to this
I/Timeline(23327): Timeline: Activity_idle id: android.os.BinderProxy@7dfa1da time:695440093

```
In principle, this is not an error of _path_provider_. There are some problems with the **_permissions_** of the file system. Inclusion in _AndroidManifest.xml_ file the next lines:

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

```
doesn't solve the problem, although this is actual for **Android 5.1** when working with external memory. Perhaps someone has come across this errors and knows how to solve problem?

**Comment by micrcx** [comment]
This problem is solely related to the problem of permissions of _Android_ since version 6. If manually change the permissions of the application: **settings-> Apps -> [application name] -> Permissions [Storage] -> [ON]**, the error disappears. In fact, in _Android_, if use java, such situations are processing special (as in iOS) way. In flutter, too, there is some mechanism to do this, but need to write additional code in java wrapper, i.e. in MainActivity.java. Ideal: if the problem was solved in the plugin itself.

**Comment by akmishra30** [comment]
settings-> Apps -> [application name] -> Permissions [Storage] -> [ON]
This works for both - Android/iOS
Thanks @micrcx
