### ISSUE TITLE
How to change background color of TabBar without changing the AppBar in flutter? The TabBar does not have a BG proprety, is there a workaround?

### ISSUE THREAD

**Issue by renhaoweixiao** [flutter/flutter#19549]
I just want to change the currently selected TabBar, not the background color of all TabBars.

**Comment by Dregus** [comment]
I'm trying to do it as well.

**Comment by zoechi** [comment]
Did you try get an answer on StackOverflow?

**Comment by inft** [comment]
```dart
            Container(
              color: Colors.red,
              child: Container(
                padding: EdgeInsets.only(
                  bottom: padding.bottom,
                ),
                child: TabBar(
                  unselectedLabelColor: Colors.grey,
                  labelColor: Colors.blue,
                  controller: _tabController,
                  tabs: _tabs,
                ),
              ),
            )
```

**Comment by zoechi** [comment]
It looks like you mean the system status bar instead of `AppBar`.
You can try setting the status bar explicitely `SystemChrome.setSystemUIOverlayStyle()`
See also https://github.com/flutter/flutter/issues/21265

**Comment by rubensdemelo** [comment]
This works fine:
```
child: new Material(
                  color: Colors.indigo,
                  child: new TabBar(
                    tabs: [
                      new Tab(icon: new Icon(Icons.directions_car)),
                      new Tab(icon: new Icon(Icons.directions_transit)),
                      new Tab(icon: new Icon(Icons.directions_bike)),
                    ],
                  ),
                ),
```

https://stackoverflow.com/questions/50566868/how-to-change-background-color-of-tabbar-without-changing-the-appbar-in-flutter

But a backgroundColor property on TabBar would be nice.

**Comment by AshweenMankash** [comment]
Anyone Bothered to add this feature? Currently I am doing some hacks to make it work. Would love an official way, less hack more professional.

**Comment by raphaelsoul** [comment]
for me i have a tab bar in top. And I found I could just put the TabBar in to body rather than the framework layout.

i.e: an 
```
appBar: new AppBar(
    title: new Text("some title"),
    // this will be colored with theme data
    bottom: new TabBar(
        controller: tabController,
        tabs: tabs.map((e) => new Tab(text: e)).toList(),
    ),
    body: new Column(
        children: [
            /// this is will not colored with theme data
            new TabBar(...),
            Expanded(
                new TabBarView(...)
            )
        ]
    )
)
```

**Comment by bgurtz** [comment]
> I just want to change the currently selected TabBar, not the background color of all TabBars.

        bottomNavigationBar: Material(
          color: Colors.blue[900],
          child: TabBar(
            unselectedLabelColor: Colors.white,
            labelColor: Colors.orange[400],
           controller: controller,
           tabs: <Widget>[
             Tab(icon: Icon(Icons.school,),text: "Education",),
             Tab(icon: Icon(Icons.contacts),text: "Contact",),
             Tab(icon: Icon(Icons.adb),text: "Portfolio",),
             Tab(icon: Icon(Icons.computer),text: "Instructor",),
           ],   //  <Widget> []
         ),   //  TabBar

![Capture](https://user-images.githubusercontent.com/38874016/66620072-cabc1b00-eba4-11e9-934d-e72b6427dd7b.PNG)

**Comment by byshy** [comment]
I edited the official Tab widget to have backgroundColor in the following code:
https://pastebin.com/Gjq6aMZn
but I removed the icon and child since I didn't need them, but you can open the official file and see how they are implemented and do it yourself 👍

**Comment by tvolkert** [comment]
It looks like this issue has become a general place for posting samples of how to achieve a certain effect, which StackOverflow is better for.  I'm going to close the issue accordingly.  Please feel free to file a new issue if you see a bug in Flutter related to this.
