### ISSUE TITLE
If you change tabs while we're animating between tabs, it does weird things

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1955]
1. Launch Gallery and slow animations down.
2. Go to the Colors demo.
3. Tap Indigo, then immediately tap Purple.

The page that's animating in changes colours instantly.
The indicator however continues to Indigo until it gets there then it jumps to Purple.

4. Tap Deep Purple, then Red.

The page we're coming from changes colour and the animation reverses. The indicator again continues to the first selected destination then warps to the final one.

5. Tap Pink then Red.

Both pages end up red.

6. Tap Deep Purple.
7. Tap Red, Pink, Purple

The animation jumps all over the place.

**Comment by mpcomplete** [comment]
The jumping indicator is fixed. The tab area is still wonky.
