### ISSUE TITLE
dismiss keyboard has stopped working. (using the FocusNode method)

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#19552]
The following code does not work anymore to dismiss the keyboard. 
The breakpoint hits the  
```FocusScope.of(context).requestFocus(new FocusNode()); ``` 
code but does not really dismiss the keyboard.

```dart
main() {
    runApp(new Home());
}


class Home extends StatelessWidget {
    @override
      Widget build(BuildContext context) {
        var widget = new MaterialApp(
            home: new Scaffold(
                body: new Container(
                    height:500.0,
                    child: new GestureDetector(
                        onTap: () {
                            FocusScope.of(context).requestFocus(new FocusNode());
                        },
                        child: new Container(
                            color: Colors.white,
                            child:  new Column(
                                mainAxisAlignment:  MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                
                                children: [
                                    new TextField( ),
                                    new Text("Test"),                                
                                ],
                            )
                        )
                    )
                )
            ),
        );
           
        return widget;
    }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Not sure if this should be made a dup of #7247 
#7247 asks for docs, this is a regression that draws the proposed workaround invalid.

**Comment by Hixie** [comment]
cc @HansMuller 

Do we know when this regressed? A bisect to find the offending commit would be really useful.

**Comment by manujbahl** [comment]
I just upgraded and its still not working.
Flutter (Channel master, v0.5.8-pre.79, on Mac OS X 10.13.5 17F77, locale en-US)

**Comment by manujbahl** [comment]
any update on this ?

**Comment by Hixie** [comment]
@manujbahl What version did this work on for you? I just tried your sample in v0.5.1, v.0.3.0, and v0.1.0, and it didn't work in any of those versions - I tap the text field, keyboard comes up, I tap elsewhere, nothing happens (but it is calling the onTap callback, I checked).

**Comment by manujbahl** [comment]
@Hixie not sure. I know it used to work on the alpha channel a couple months back. Im surprised other people are not reporting this

**Comment by manujbahl** [comment]
Any progress on this? This is currently blocking us from shipping our app

**Comment by manujbahl** [comment]
Is anyone planning on fixing this ?

**Comment by Hixie** [comment]
We don't currently have anyone working on this but if you would like to debug the problem and submit a patch we would be happy to review it and work with you on it.

**Comment by manujbahl** [comment]
Any pointers on where to start or how it was being done before?

**Comment by Hixie** [comment]
I'm not sure it was ever being done before, as noted above, I couldn't find a version where this test worked.

FWIW, it appears that calling "unfocus" on the node you wish to unfocus is one way to achieve what you're describing. See: https://docs.flutter.io/flutter/widgets/FocusNode/unfocus.html

To actually debug why the code above (requesting the focus be on a new node) doesn't work, I would begin by walking through the code in `packages/flutter/lib/src/widgets/focus_manager.dart` and `packages/flutter/lib/src/widgets/focus_scope.dart`.

**Comment by SteveAlexander** [comment]
To make @zoechi's reference more explicit: an easy way to fix this issue is to make it unnecessary to dismiss the keyboard in this way, and also make an obvious API to allow developers to dismiss the keyboard.

The fix is described in #20227, that is to expose `FocusScopeNode._focus` as `.focus`, so that it is easy to find the currently focused node, and to call `unfocus` on it.

Currently, as @manujbahl describes, and as I encountered, it is not straightforward to keep track of, or to walk though and discover, the currently focused node.

This looks to me like a one-liner to implement in `FocusScopeNode`, although I'm not sure what testing would be needed.

**Comment by SteveAlexander** [comment]
HOWEVER... I've debugged this issue, and I think I have the answer.

There is no regression. The issue in the sample code is to do with the binding of `context` and getting the correct `FocusScope`.

Using a `builder` allows to have a more useful context. See code attached, in which the keyboard goes away, as expected.

So, I think this bug can be closed. Even so, I'd still like `FocusScopeNode.focus` to be available, as it makes for more obvious code, as in #20227.

```
main() {
  runApp(Home());
}


class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) =>
      MaterialApp(
        home: Scaffold(
          body: Builder(
            builder: (context) => Container(
              height: 500.0,
              child: GestureDetector(
              onTap: () {
                FocusScope.of(context).requestFocus(FocusNode());
              },
              child: Container(
                color: Colors.white,
                child: Column(
                  mainAxisAlignment:  MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                
                  children: [
                    TextField( ),
                    Text("Test"),                                
                  ],
                )
              )
            )
          )
        )
      ),
    );
}
```

**Comment by goderbauer** [comment]
Based on the comments above this doesn't sound like a regression. I am going to close this as a dup of https://github.com/flutter/flutter/issues/7247.
