### ISSUE TITLE
Export `kDataSnapshot` from the Dylib containing the precompiled Dart code on next dart-lang/sdk roll

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#1956]
The next roll contains https://codereview.chromium.org/1584443002 which will break precompilation builds unless another symbol is exposed from the dylib to the runner.

cc @abarth: Can you give me a heads up the next time we decide to roll. The patch should be minor but should probably be applied at the same time as the roll.

**Comment by abarth** [comment]
Sure thing.
