### ISSUE TITLE
TextField textInputAction is not found in flutter mac sdk.

### ISSUE THREAD

**Issue by dooboolab** [flutter/flutter#19561]
TextField `textInputAction` is not found in flutter mac sdk. It is readable in `window` sdk and both are `0.5.1-beta`. I've re-downloaded sdk several times.

![image](https://user-images.githubusercontent.com/27461460/42951480-37e6af92-8bb1-11e8-8312-6c067d84dd88.png)

**Comment by zoechi** [comment]
That was added very recently as far as I remember and 0.5.1-beta is about 2 months old.
You can switch to a channel that is updated more frequently like 
```sh
flutter channel master
flutter doctor
```
`dev` and `beta` are safer to use than `master` though.
You can try `dev` first and only switch to `master` only if it still doesn't work.
At least when the next `dev` update becomes available, it's better to switch back to `dev`.
