### ISSUE TITLE
Different import styles cause compile errors (lib1 can't be assigned to lib2)

### ISSUE THREAD

**Issue by StefanSamson** [flutter/flutter#19577]
Using different import styles like:
- import 'package:different_package_import/someotherfolder/class2.dart';
- import '../someotherfolder/class2.dart';
will cause compile errors.

**STEPS TO REPRODUCE**
git clone https://github.com/StefanSamson/flutter_different_package_import.git
run
1) Open Debug Console to see error

**LOGS**
compiler message: lib/main/main.dart:46:12: Error: A value of type 'dart.core::List<#lib1::Class2>' can't be assigned to a variable of type 'dart.core::List<#lib2::Class2>'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::List<#lib2::Class2>'.
compiler message:     Class1(List<Class2>());
compiler message:            ^
Compiler failed on C:\Users\Sam\flutter-projects\different_package_import\lib\main\main.dart
FAILURE: Build failed with an exception.
* Where:
Script 'C:\Users\Sam\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435
* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'C:\Users\Sam\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 8s
Gradle build failed: 1

**FLUTTER DOCTOR**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 64-bit edition (version 1.25.1)
[√] Connected devices (1 available)

! Doctor found issues in 2 categories.

**Comment by zoechi** [comment]
This issue is tracked in https://github.com/dart-lang/sdk/issues/33076

Just don't use relative imports in `lib/main.dart` and don't import `lib/main.dart` anywhere.
