### ISSUE TITLE
Should Draggable use less HapticFeedback on iOS?

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#19574]
From [a comment](https://github.com/flutter/flutter/issues/16763#issuecomment-404482191) by @knopp on #16763:

> Vibration feels very off on iOS. Ideally it should be HapticFeedback.selectionClick(); at the beginning and during every reorder.

The underlying implementation uses Draggable.

Do we have a Material specification for how much HapticFeedback to use on iOS in Draggables?

**Comment by DaveShuckerow** [comment]
I've gotten comments from g3 users on this, too.

**Comment by willlarche** [comment]
Haptics should match iOS expectations when Material Components run on iOS.
