### ISSUE TITLE
Keyboard is showing DONE in ios when there should be SEARCH

### ISSUE THREAD

**Issue by dooboolab** [flutter/flutter#19570]
I am in flutter `beta` channel followed by guide [here](https://github.com/flutter/flutter/issues/19561). In andoird it is showing `search` icon in keyboard when I put `TextInputAction.search` in `textInputAction` in `TextField`. I'd like to contribute to flutter but have no idea where to edit this part yet.

I'll post the image below for more understasnding.
<img width="378" alt="screen shot 2018-07-20 at 4 02 05 am" src="https://user-images.githubusercontent.com/27461460/42964432-fa6b5ea8-8bd1-11e8-9df1-7da5071611aa.png">

**Comment by jonahwilliams** [comment]
@dooboolab I don't believe the change is in the beta - It was added very recently, and the engine changes required to match the framework didn't happen until this week I believe.

**Comment by zoechi** [comment]
Sounds like this should be fixed.
Please add a comment to have it reopened if this is not the case.
