### ISSUE TITLE
iOS: Use double-tap to select text instead of longpress

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#19583]
In native iOS you can double-tap a word in a text field to select the entire word. This does not work in a Flutter app. In a flutter app you have to long-press to select a word, which is the correct gesture on Android. However, when running on iOS Flutter should use double-tap to select a word as users are used to that.

/cc @xster @HansMuller @sandrasandeep

**Comment by xster** [comment]
@sandrasandeep to note when making CupertinoTextField (since touch handling are mapped there). I think we might have to do some tweaks on the RenderEditable to decouple word selection from handleLongPress (since long press and double tap compose differently on iOS)

**Comment by ffeu** [comment]
isn't this the same as #9288 ?

**Comment by xster** [comment]
Oh you're right. Thanks.
