### ISSUE TITLE
Container  transform problem

### ISSUE THREAD

**Issue by shuicheng** [flutter/flutter#19586]
![flutter](https://user-images.githubusercontent.com/13236194/42977186-4db8b77e-8bf8-11e8-9ff6-e117d7fd6d1b.png)

Wide 375 and wide 360 scale 0.96, why the effect is the same？

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v` and the code as text so that it can be copied to a reproduction example.

**Comment by shuicheng** [comment]
Code：

`import 'package:flutter/material.dart';

class Test30 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Welcome to Flutter'),
        centerTitle: true,
      ),
      body: ListView(
        children: <Widget>[
          Text('Screen width = ${MediaQuery.of(context).size.width}'),
          Text('Screen height = ${MediaQuery.of(context).size.height}'),
          Container(
            width: 1080.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 1080.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Container(
            width: 720.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 720.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Container(
            width: 375.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 375.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Container(
            width: 360.0,
            height: 100.0,
            color: Colors.green,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 360.0, height: 100.0, scale(0.96)'),
            ),
          ),
        ],
      ),
    );
  }
}`


flutter doctor -v：


`[√] Flutter (Channel master, v0.5.8-pre.92, on Microsoft Windows [Version 10.0.17134.165], locale zh-CN)
    • Flutter version 0.5.8-pre.92 at C:\flutter
    • Framework revision a66ea0a628 (6 hours ago), 2018-07-19 18:06:44 -0700
    • Engine revision 482469bad8
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\hong\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\hong\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.24.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.13.2

[!] Connected devices
    ! No devices available`

problem：

![flutter](https://user-images.githubusercontent.com/13236194/42989085-5f3bd8c6-8c31-11e8-835a-ed7241ef7131.PNG)

width: 360.0, 375.0, 720.0, 1080.0  scale 0.96, why the effect is the same？Feeling abnormal !!!

@zoechi

**Comment by zoechi** [comment]
Must have to do with `ListView`. If you change it to `Column` `width` works as expected.

**Comment by shuicheng** [comment]
# Code: 

```
import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Welcome to Flutter'),
        centerTitle: true,
      ),
      body: Column(
        children: <Widget>[
          Text('Screen width = ${MediaQuery.of(context).size.width}'),
          Text('Screen height = ${MediaQuery.of(context).size.height}'),
          Container(
            width: 1080.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 1080.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Expanded(
            child: Container(
              width: 720.0,
              height: 100.0,
              color: Colors.greenAccent,
              transform: Matrix4.identity()..scale(0.96),
              child: Center(
                child: Text(' width: 720.0, height: 100.0, scale(0.96)'),
              ),
            ),
          ),
          Center(
            child: Container(
              width: 375.0,
              height: 100.0,
              color: Colors.greenAccent,
              transform: Matrix4.identity()..scale(0.96),
              child: Center(
                child: Text(' width: 375.0, height: 100.0, scale(0.96)'),
              ),
            ),
          ),
          Container(
            width: 360.0,
            height: 100.0,
            color: Colors.green,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 360.0, height: 100.0, scale(0.96)'),
            ),
          ),
        ],
      ),
    );
  }
}

```

The result is the same as the above (显示的效果和上面的图片一样)，
Container width exceed MediaQuery.of(context).size.width ，scale less than 1，Feeling abnormal ！！！

@zoechi

**Comment by zoechi** [comment]
```dart
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Welcome to Flutter'),
        centerTitle: true,
      ),
      body: Column(
        children: <Widget>[
          Text('Screen width = ${MediaQuery.of(context).size.width}'),
          Text('Screen height = ${MediaQuery.of(context).size.height}'),
          Container(
            width: 1080.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 1080.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Container(
            width: 720.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 720.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Container(
            width: 375.0,
            height: 100.0,
            color: Colors.greenAccent,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 375.0, height: 100.0, scale(0.96)'),
            ),
          ),
          Container(
            width: 360.0,
            height: 100.0,
            color: Colors.green,
            transform: Matrix4.identity()..scale(0.96),
            child: Center(
              child: Text(' width: 360.0, height: 100.0, scale(0.96)'),
            ),
          ),
        ],
      ),
    );
  }
}
```
or

```dart
![screenshot_1532081195](https://user-images.githubusercontent.com/405837/42996951-66e1316e-8c15-11e8-979e-150fb18fe73e.png)

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Welcome to Flutter'),
        centerTitle: true,
      ),
      body: ListView(
        children: <Widget>[
          Text('Screen width = ${MediaQuery.of(context).size.width}'),
          Text('Screen height = ${MediaQuery.of(context).size.height}'),
          Center(
            child: Container(
              width: 1080.0,
              height: 100.0,
              color: Colors.greenAccent,
              transform: Matrix4.identity()..scale(0.96),
              child: Center(
                child: Text(' width: 1080.0, height: 100.0, scale(0.96)'),
              ),
            ),
          ),
          Center(
            child: Container(
              width: 720.0,
              height: 100.0,
              color: Colors.greenAccent,
              transform: Matrix4.identity()..scale(0.96),
              child: Center(
                child: Text(' width: 720.0, height: 100.0, scale(0.96)'),
              ),
            ),
          ),
          Center(
            child: Container(
              width: 375.0,
              height: 100.0,
              color: Colors.greenAccent,
              transform: Matrix4.identity()..scale(0.96),
              child: Center(
                child: Text(' width: 375.0, height: 100.0, scale(0.96)'),
              ),
            ),
          ),
          Center(
            child: Container(
              width: 360.0,
              height: 100.0,
              color: Colors.green,
              transform: Matrix4.identity()..scale(0.96),
              child: Center(
                child: Text(' width: 360.0, height: 100.0, scale(0.96)'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```
worked for me (at least what I assumed is the expected result)

![screenshot_1532081195](https://user-images.githubusercontent.com/405837/42996968-72d974e0-8c15-11e8-8b42-5f1bf734dc2b.png)

**Comment by shuicheng** [comment]
hehe, this does not seem to be the effect I want...
呵呵，这个好像不是我想要的效果。。。

Container的width 超过了 MediaQuery.of(context).size.width ，scale( less than 1)，感觉缩放不正常！
Container width exceed MediaQuery.of(context).size.width ，scale (less than 1)，Feeling abnormal ！

比如在MediaQuery.of(context).size.width = 360.0的机型上，
For example, on a model with MediaQuery.of(context).size.width = 360.0，

对Container width= 375.0  ..scale(0.96)，

它的显示效果应该是一个屏幕的宽吧 ？
Its display should be a screen wide ？

@zoechi

**Comment by shuicheng** [comment]
OK，thank you  @zoechi ，   solved（解决了）

### This is the effect I want...

![fluttrt](https://user-images.githubusercontent.com/13236194/43031182-1bb47c72-8ccf-11e8-9605-9f935da9ac31.PNG)

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
