### ISSUE TITLE
Draggable: Pass the draggable's OverlayEntry out in the onDragEnd callbacks so that clients can animate to a final position.

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#19580]
Corresponds to this TODO: https://github.com/flutter/flutter/blob/35291ae3b933a232c2a6928bc4288874546f45b3/packages/flutter/lib/src/widgets/drag_target.dart#L629

Another alternative would be we could allow the onDragEnd callback to describe a final position and an animation curve to apply, then we wouldn't need to worry about the client managing the entry's life cycle.

This would be useful in adding animations to the end of reorder actions in #16763.

**Comment by TahaTesser** [comment]
Hi @zoechi 
Do you think this issue still valid?
Than you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
