### ISSUE TITLE
Remote search with SearchDelegate

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#19591]
I'm trying to do a remote search with SearchDelegate but i don't understand where i can put the request to my server

Widget buildResults(BuildContext context) {

is not a async method and there isn't another method that is called when the query changes.

Thanks

**Comment by zoechi** [comment]
I think this kind of question is better asked on StackOverflow or https://gitter.im/flutter/flutter

**Comment by shehabic** [comment]
in case someone here is new to flutter, the answer to the question above is to return a `FutureBuilder` and inside it build your Widget Asynchronously after fetching the data.
https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html
