### ISSUE TITLE
Run code on app shutdown

### ISSUE THREAD

**Issue by development-s365** [flutter/flutter#19594]
Hi

Is there a way to run code before the application closes?
Like `onDestroy` in android.

Kind regards

**Comment by zoechi** [comment]
You can use https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver-class.html with https://docs.flutter.io/flutter/dart-ui/AppLifecycleState-class.html
I think `suspending` is the closed and to my experience it is also called before the app is killed.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the channels http://flutter.io/support .

I assume this is solved.

**Comment by lionuncle** [comment]
same question 2021

**Comment by happy-san** [comment]
@lionuncle https://stackoverflow.com/a/52074534/11218270

**Comment by alterschwede** [comment]
https://www.refactord.com/guides/flutter-application-system-manager

**Comment by vivaan-m** [comment]
After the update AppLifecycleState.detached never gets called is there any solution to that
