### ISSUE TITLE
Horizontal scroll view inside a nested scroll view throws out of bounds error

### ISSUE THREAD

**Issue by vijaykanta** [flutter/flutter#19596]
I am having difficulty nesting a horizontal list view within a nested scroll view. What I really want is a group of horizontal lists one below the other within a vertical list view sort of container.

My code
```dart
body: new NestedScrollView(
            scrollDirection: Axis.vertical,
            headerSliverBuilder:
                (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                new SliverAppBar(
                  pinned: true,
                  title: new Text("Home"),
                ),
             ];
           },

body: new ListView.builder(
                    padding: const EdgeInsets.only(bottom: 30.0),
                    scrollDirection: Axis.horizontal,
                    itemCount: TooursData.indianTours.length,
                     itemBuilder: getPkgCell,
                  ),
),
...

Widget getPkgCell(BuildContext context, int index) {
return new Container(
      margin: const EdgeInsets.only(right: 20.0),
      width: 300.00,
      decoration: new BoxDecoration(
        color: Colors.white24,
        border: new Border.all(color: Colors.blue, width: 1.0),
        borderRadius: new BorderRadius.circular(2.0),
      ),
      child: ...
```

I get a yellow band with black slant stripes telling me to use flex or expanded which are of no use.

**Comment by zoechi** [comment]
For this kind of question StackOverflow is probably a better place to ask.

**Comment by vijaykanta** [comment]
Okay, after lot of frustration and unsuccessful attempts, finally able to get help from this github project https://github.com/mtellect/FlutterGirliesShop-Part1-/blob/master/lib/userScreens/item_details.dart

Apparently we have to use a SingleChildScrollView which acts like the vertical list, and use a card outside a horizontal list view to have a carousel effect. I had to copy all code instead of reading entriely due to some reasons, so if anyone got explanation, please do

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by syedfaisaljaved** [comment]
wrap your nested listview inside a container and give it a height (e.g. 100) and it will work.
