### ISSUE TITLE
Look at Icon and IconButton clients and see if there are patterns

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#196]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 12, 2015 at 18:02 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1577_

----

For example, do they need a convenience argument to set the color filter rather than having them create one themselves?

**Comment by Hixie** [comment]
(i did look, there were no interesting patterns that i could see)
