### ISSUE TITLE
android studio tools bar  show no devices

### ISSUE THREAD

**Issue by shenmashi** [flutter/flutter#19609]
flutter doctor -v show the picture 2  
but android studio will show no devices forever
please help me!

![image](https://user-images.githubusercontent.com/8580637/43014669-8bc5086a-8c7f-11e8-86b5-9289d08d5408.png)

![image](https://user-images.githubusercontent.com/8580637/43014678-954396ae-8c7f-11e8-9dff-61c62a3b15f1.png)

![image](https://user-images.githubusercontent.com/8580637/43014790-ee686afc-8c7f-11e8-939b-a81db5aff1f9.png)

**Comment by zoechi** [comment]
Closing as dup of https://github.com/flutter/flutter-intellij/issues/1525
Please follow and upvote there.
