### ISSUE TITLE
Tasks for converting flutter/flutter to Cirrus CI

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19608]
In order to switch to Cirrus CI, the following things need to happen:
  - [X] Add Cirrus to the dashboard
    - [x] Remove Travis from dashboard
    - [X] Remove Appveyor from dashboard
  - [X] Move gallery build and publish to Cirrus from Travis
- [X] Remove .travis.yml  and appveyor.yml from repo
  - [X] Convert plugins and packages repos (and others) to use Cirrus (not required)

**Comment by jonahwilliams** [comment]
Cirrus has been added, and travis/appveyor removed

**Comment by zoechi** [comment]
Is there still something to do?

**Comment by gspencergoog** [comment]
Nope, all done.
