### ISSUE TITLE
flutter trace -d 10 did not work on the alpha branch

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1961]
The resulting sky-trace-2016-02-17-170949.json was:
`run-as: Package 'com.example.my_app' is not debuggable`

Flutter from https://github.com/flutter/flutter.git (on alpha)
flutter revision: db7294206a7874c15d983633c3e05fb15a865843 (16 hours ago)
engine revision : 9e1e1fba5474b458458b65f1aa1d0d730af2705b

No clue why.

**Comment by eseidelGoogle** [comment]
Presumably we need to either run `adb root` before running `flutter trace` or we need to add `debuggable=true` to the `AndroidManifest.xml` file for tracing to work.

In either case we should detect this error and explain it to the user.  All I saw was:

```
$ flutter trace -d 5
idevice_id not found. To work with iOS devices, please install ideviceinstaller.
If you use homebrew, you can install it with "$ brew install ideviceinstaller".
Trace file saved to sky-trace-2016-02-17-170949.json
```

**Comment by eseidelGoogle** [comment]
Even once I restarted add as root it still gave me the same output.  Not sure why.

**Comment by abarth** [comment]
We need to re-think how tracing transfers the trace file back to the host.  The current scheme doesn't work well and currently don't work at all in a number of scenarios.

**Comment by eseidelGoogle** [comment]
alpha is no longer a thing. Closing.
