### ISSUE TITLE
Error while building an android app using flutter and vscode

### ISSUE THREAD

**Issue by primeashwini** [flutter/flutter#19614]
I am trying to build an android app with flutter and vscode but I am continuously getting an error.

> Launching lib\main.dart on Micromax Q427 in debug mode...
> * Error running Gradle:
> Exit code 1 from: E:\Flutter\mytestapp\android\gradlew.bat app:properties:
> Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
> Download https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.0.1/builder-3.0.1.jar
> Download https://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
> Download https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> 
> A problem occurred configuring root project 'android'.
> > Could not resolve all files for configuration ':classpath'.
>    > Could not download builder.jar (com.android.tools.build:builder:3.0.1)
>       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.0.1/builder-3.0.1.jar'.
>          > Premature end of Content-Length delimited message body (expected: 26945712; received: 8650688
>    > Could not download intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1)
>  > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar'.
>          > Premature end of Content-Length delimited message body (expected: 8234273; received: 6553552
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14m 39s
> Please review your Gradle project setup in the android/ folder.
> Exited (sigterm)

I have tried many solutions but nothing worked also flutter doctor shows no issue and I am not able to understand why I am getting this error while building my app.

I have also asked this query in stackoverflow but got no reply so far here is the link: https://stackoverflow.com/questions/51449119/error-while-building-an-android-app-using-flutter-and-vscode

**Comment by zoechi** [comment]
Is this still an issue in a recent Flutter version (beta >= 0.6.0).
I believe this was fixed.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by ABNG** [comment]
i have same problem and i am using flutter version flutter_windows_v0.9.4-beta.
Flutter doctor show no issue

**Comment by zoechi** [comment]
@ABNG  see #23404

**Comment by elhakeem** [comment]
It seems this is the same issue I have.
1. I opened android folder in android studio
2. I executed `flutter pub get` in app root folder.
3. I selected `Build => Make Project`
![Issue screenshot](https://i.suar.me/3NLwm/l)
