### ISSUE TITLE
Can not run flutter app on android emulator 

### ISSUE THREAD

**Issue by ihadabs** [flutter/flutter#19619]
## Steps to Reproduce

1. 
```
flutter run -d emulator-5554
```
## Logs

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.0s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleDebug'...                           7.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  3.5s
Syncing files to device Android SDK built for x86...         5.1s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:63372/
For a more detailed help message, press "h". To quit, press "q".
```
then the emulator shows

> flutter_app has stopped.

```
[✓] Flutter (Channel master, v0.5.8-pre.79, on Mac OS X 10.14 j3bjh3, locale en-SA)
    • Flutter version 0.5.8-pre.79 at /Users/ddjbc/flutter
    • Framework revision bb338ef2c6 (30 hours ago), 2018-07-19 07:24:06 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/had1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (3 available)
```

**Comment by zoechi** [comment]
But it does work when run on a device?
Have you tried `flutter clean`?

**Comment by ihadabs** [comment]
@zoechi

I dont have a physical Android device,
And it does not work on IOS simulator or physical   device it show another error which is #19618

yeah I tried “flutter clean”

**Comment by zoechi** [comment]
Does this also happen with a basic app as one created with `flutter create foo` or with an one of the examples shipped with Flutter like `flutter_gallery`?

**Comment by ihadabs** [comment]
no 
when it happens when I added firebase_auth

**Comment by zoechi** [comment]
Could you please check if `flutter logs` provides any additional information about the crash?

**Comment by ihadabs** [comment]
It just keep stoping when I run it.
Emulator shows "App keep stoping"

```
$ flutter logs -d emulator-5554
Showing Android SDK built for x86 logs:
I/flutter ( 1021): Observatory listening on http://127.0.0.1:47399/
```

**Comment by gmlewis** [comment]
I'm running into this too. I started seeing this when I switched from `flutter channel beta` to `flutter channel master` but now I see the problem on all 3 channels.

To reproduce:

* `flutter create flutter_import_test`
* `cd !$`
* add `firebase_auth: ^0.5.18` to `dependencies` section of `pubspec.yaml`
* follow "Android Integration" steps: https://pub.dartlang.org/packages/firebase_auth
* `flutter run -d Android` (emulator) or `flutter run -d Pixel` (Pixel 2XL) - both fail as described above

```bash
$ flutter doctor -v
[✓] Flutter (Channel master, v0.5.9-pre.26, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.5.9-pre.26 at /Users/lewig047/tools/flutter
    • Framework revision 9b309ba8b6 (59 minutes ago), 2018-08-13 20:36:44 +0200
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/lewig047/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.12.2

[✓] Connected devices (3 available)
    • Pixel 2 XL                • 710ABCD1234567                       • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • D253C7DC-FA97-4A56-8B52-0A5A24CC38AB • ios           • iOS 11.4 (simulator)

• No issues found!
```

**Comment by odonckers** [comment]
I have begun having a similar issue, but I don't have `firebase_auth` as a dependency. I can run perfectly fine on iOS, but the app crashes every single time I try to run it on the Android Simulator. I'm unable to test if this is just a simulator issue as I don't have an Android device.

**Comment by joshuachestang** [comment]
Same! grrrr!!!

**Comment by lmcdo** [comment]
I have the same issue. Did anyone get anywhere with this one? Thanks

**Comment by loolooii** [comment]
I have this issue both on emulator and physical device. iOS works fine. I don't have `firebase_auth` as a dependency, but I have `firebase_core` and `cloud_firestore`. Also `flutter logs` shows me:
```
I/flutter (10555): Observatory listening on http://127.0.0.1:36141/2RAZQRvZ0Do=/
```
Sometimes (I don't know why and happens randomly), I get this error: 

```
[        ] Waiting for observatory port to be available...
[ +974 ms] Observatory URL on device: http://127.0.0.1:36141/2RAZQRvZ0Do=/
[   +1 ms] executing: /Users/nima/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward
tcp:0 tcp:36141
[  +11 ms] 59194
[        ] Forwarded host port 59194 to device port 36141 for Observatory
[   +6 ms] Connecting to service protocol: http://127.0.0.1:59194/2RAZQRvZ0Do=/
[  +36 ms] Error connecting to the service protocol: HttpException: Connection closed before full
header was
           received, uri = http://127.0.0.1:59194/2RAZQRvZ0Do=/ws
[   +4 ms] "flutter run" took 8,957ms.
[        ] "flutter run" took 8,957ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:467:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:488:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

```
So it seems that sometimes it connects successfully to this "service protocol" and syncs files and then crashes and sometimes can't connect at all.

**Comment by loolooii** [comment]
This is my `flutter doctor -v`:

```
[✓] Flutter (Channel master, v1.6.7-pre.45, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.6.7-pre.45 at /Users/nima/flutter
    • Framework revision 55d98ddd33 (14 hours ago), 2019-05-30 20:22:55 -0400
    • Engine revision 7f4f52f952
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 445a23a9bc)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nima/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7221
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b02)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by michalsuryntequiqo** [comment]
The same issue for me - the same output as above. The app is generally built and installed on the emulator, but there's no Internet connection.
When running on a real device, the output is the same, but the phone connects to the web and app is _usable/testable_.

No idea how to fix this.

**Comment by loolooii** [comment]
As I mentioned in [this issue](https://github.com/flutter/flutter/issues/33214), I could "solve" this problem by removing the plugin `flutter_webview_plugin`. Try to remove your plugins one by one to see if that will solve the problem. In this case I just used [webview_flutter](https://pub.dev/packages/webview_flutter) from Google. I know that this is not a real solution, but it helped me.

**Comment by michalsuryntequiqo** [comment]
I got rid of `flutter_webview_plugin` and used `webview_flutter` instead, but it didn't help me at all.
The output is still the same:  

```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:61996/lY7IFqAgY_Y=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

**Comment by dpedrinha** [comment]
Same problem here. I rolled back to a previous working version and keep having problems.
I get a white screen on the emulator and the console is stuck syncing.

Other apps work. But what happened to mine that somehow damaged it and didn't rollback?

Yes, tried Flutter Clean. Doctor says it's all fine too.

> Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86...

**Comment by MuhammamdArslanKhan** [comment]
Any Update regarding this issue? I am facing same issue whats solution? should I move to previous flutter version?

 flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at E:\src\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at E:\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = E:\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.37.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by hritik15** [comment]
suncing files to device android sdk built for x86..     49,203ms(!)

**Comment by hritik15** [comment]
syncing files to device android sdk built for x86..     49,203ms(!)

**Comment by kroikie** [comment]
@ihadabs

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/747. Any further collaboration will be done there.

**Comment by osunkoyadavid** [comment]
> But it does work when run on a device?
> Have you tried `flutter clean`?

what does flutter clean do

**Comment by khalil-git-dev** [comment]
problem de lancement de mon application avec mon telephone android

voici le resultat quant je fait flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [version 10.0.18362.900], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code, 32-bit edition (version 1.24.0)
[√] Connected device (1 available)

• No issues found!

et quand j'essaye de duilder ça ne marche pas

**Comment by osunkoyadavid** [comment]
don't understand french

**Comment by gersonjaber** [comment]
Just run: 'flutter create .'

**Comment by osunkoyadavid** [comment]
Thanks for the tip! But I am now on a Mac
