### ISSUE TITLE
Error when launching on iPhone X simulator and physical iPhone.

### ISSUE THREAD

**Issue by ihadabs** [flutter/flutter#19618]
## Steps to Reproduce

1. $ flutter run -d xxxx  

the same issue with a real device.

the app runs but then the debugging disconnects 

## Logs

```
$ flutter run -d 1090A2E8-ACEE-448E-9B0C-8481E4BCB678  // This is iPhone X Simulator
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.8s
 └─Compiling, linking and signing...                  8.2s
Xcode build done.                                           11.5s
Error waiting for a debug connection: FormatException: Invalid character (at character 25)
http://127.0.0.1:64741/
                        ^

Error launching application on iPhone X.
```

```
[✓] Flutter (Channel master, v0.5.8-pre.79, on Mac OS X 10.14 wi4hb3, locale en-SA)
    • Flutter version 0.5.8-pre.79 at /Users/xsjh/flutter
    • Framework revision bb338ef2c6 (30 hours ago), 2018-07-19 07:24:06 -0700
    • Engine revision 5557e3006e
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/had1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (3 available)
```

**Comment by zoechi** [comment]
> http://XXX.X.X.X:XXXXX/ 

seems to be redacted, is it? Would be good to know what the actual character is on that position.

**Comment by ihadabs** [comment]
@zoechi 
This is the message as it is 
Of course the xs are not

**Comment by zoechi** [comment]
> Of course the xs are not

that's what I meant. It looks like one of the characters that are redacted as `x` cause the error.
It would be good to know what character that is.

**Comment by ihadabs** [comment]
I updated the logs.

**Comment by benjaminbeilharz** [comment]
Same error here. 
Error waiting for a debug connection: FormatException: Invalid character (at character 24)
http://127.0.0.1:8100/

**Comment by matteocrippa** [comment]
Same error as the other guys, I think it's un-related to a specific platform, I'm experiencing the same issue with iPhone X simulator.

Behaviour: the app works, but the debugger hangs up.

It seems like the url provided has some spaces appended at the end, and so it raise that error.

It could be an issue with https://github.com/flutter/flutter/blob/dev/packages/flutter_tools/lib/src/ios/simulators.dart#L538 ?

**Comment by bqoli** [comment]
@matteocrippa the regex looks faulty. Looks like the last part of the pattern is greedy. But I don't know by heart.

**Comment by matteocrippa** [comment]
I think sanitising the input should work, basically it is needed to be removed all the stuff that are not url eligible chars

**Comment by tvolkert** [comment]
The regexp isn't specific to observatory URLs -- it's used to produce a stream of generic log lines. 
 Sanitization of the URL makes sense and would be done here:

https://github.com/flutter/flutter/blob/66091f969653fd3535b265ddcd87436901858a1d/packages/flutter_tools/lib/src/protocol_discovery.dart#L61

It'd have to handle both IPv4 and IPv6 patterns.

Out of curiosity, can someone who's experiencing this try adding some instrumentation at that location locally to see what's showing up at the end?

**Comment by meg32** [comment]
Having the same issue:

The characters are:   ASCII  "esc" [ K nl sp sp sp .....

So, it is an escape sequence.  I produced this by: flutter run &> funky.txt
and then od -a funky.txt

**Comment by dustinwtf** [comment]
I don't know if this is what you meant @tvolkert, but I added a print at the top of that function and this is what I got:

```
This is the line (flutter: Observatory listening on http://127.0.0.1:54055/)
```

And here is the code for reference:
```
print('This is the line ($line)');
```

**Comment by tvolkert** [comment]
I think @meg32 is right that it's an unprintable character (maybe always ESC).  The solution is to update `_handleLine()` to sanitize the URL.

**Comment by Luc-H** [comment]
So currently no solution or workaround yet for iOS debugging?

**Comment by matteocrippa** [comment]
Atm I switched using android for debugging purposes

**Comment by meg32** [comment]
Surely there is some way to work around this?  Does anyone yet know where the unprintable "esc [K" sequence comes from??

**Comment by tvolkert** [comment]
FYI, the fix should be pretty straightforward.  I'm currently swamped with other work and won't be free to work on this for a few weeks, but if someone's willing to send a patch, I'd be happy to review it.

https://github.com/flutter/flutter/blob/66091f969653fd3535b265ddcd87436901858a1d/packages/flutter_tools/lib/src/protocol_discovery.dart#L61

**Comment by imWildCat** [comment]
Same problem here. I have to stop dev now.

**Comment by dustinwtf** [comment]
@imWildCat This is in no way a good and permanent workaround, but you could just do something like this in that file mentioned earlier:

```dart
uri = Uri.parse(line.substring(index + _prefix.length, line.length - 4));
```

That will take away the hidden characters mentioned earlier, but it isn't as good as updating the regex (I'm assuming).

**Comment by tvolkert** [comment]
Again, the regex is meant to match the entire line since it's used for more than URL discovery -- it's just the `_handleLine()` method that needs updating.

**Comment by matteocrippa** [comment]
I make a PR with a possible patch using a `regex` instead of the split, it should avoid issue with unexpected chars.

**Comment by imWildCat** [comment]
Hello, @dustinwtf !

I upgraded my flutter to the latest version and found this solution did not work anymore. After that, I downgraded to beta version (`Channel beta, v0.5.1`) and this issue still exist. Any recommendations to solve this issue? For example, build flutter locally?

**Comment by dustinwtf** [comment]
@imWildCat, once you make the change again to your local flutter project (I'm assuming the update removed the modified code?), you'll want to go to the top level directory in the flutter folder and then go to `bin/cache` and remove the file called `flutter_tools.snapshot`.

Next time you run `flutter run`, it will rebuild your local flutter project.

**Comment by imWildCat** [comment]
@dustinwtf Many thanks for your prompt reply! It helps me a lot!

**Comment by meg32** [comment]
@imWildCat has proposed a fix, but the fix causes other problems.  This is working for me now on both iPhone and Android, simulator/emulator and real.  If the line does NOT end with forward-slash, consider it suspicious, and trim to the last found forward-slash, otherwise proceed with normal parse:

if (!line.endsWith('/')) {
    uri = Uri.parse(line.substring(index + _prefix.length, line.lastIndexOf('/')+1));
} else {
    uri = Uri.parse(line.substring(index + _prefix.length));
}

**Comment by matteocrippa** [comment]
@meg32 solution is already on the go #19863

**Comment by bqoli** [comment]
The fix is not working for me. Error persists with the iOS simulator.

**Comment by matteocrippa** [comment]
#20262 for new ref
