### ISSUE TITLE
Text wrapping behavior changes depending on --debug or --release build

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#19612]
From @mehmetf 

Turns out the effect is dependent on the widgets in the column.

The following is consistent between --debug and --release:

```dart
    Column(
      children: [
        new TextFormField(maxLines: null),
        new TextFormField(maxLines: null),
      ],
    ),

    Column(
      children: [
        new TextFormField(maxLines: null),
      ],
    ),
```

The following produces different behavior in --debug than --release mode.

```dart
    Column(
      children: [
        new TextFormField(maxLines: null),
        new TextFormField(maxLines: 1),
      ],
    ),
```

**Comment by Hixie** [comment]
Does `new TextFormField(maxLines: 1)` assert in debug builds?

**Comment by jason-simmons** [comment]
`EditableTextState._isMultiline` is returning different results in debug versus release mode.  Specifically, the `widget.maxLines != 1` expression evaluates as false in release mode if `widget.maxLines` is null

It looks like this was introduced in https://github.com/dart-lang/sdk/commit/c3b59399659804ee27629c285b1b630283cef221

@a-siva @alexmarkov

**Comment by alexmarkov** [comment]
AOT compiler generates incorrect code for negated integer comparisons: on a slow-path (which is used if any of the operands is not a Smi) the result of the call to 'operator ==' was not negated.

Small repro:

```dart

class X {
  final int maxLines;
  X([this.maxLines]);

  bool get isMultiline => maxLines != 1;
}

X x1 = new X(1);
X x2 = new X(42);
X x3 = new X();

main() {
  print(x1.isMultiline);
  print(x2.isMultiline);
  print(x3.isMultiline);
}
```

https://dart-review.googlesource.com/c/sdk/+/67040 should fix the problem.

**Comment by alanrussian** [comment]
Thanks all for the diagnosis and fix here.

**Comment by alexmarkov** [comment]
The fix was rolled into Flutter with the latest Dart SDK roll (https://github.com/flutter/flutter/pull/19931).
