### ISSUE TITLE
Flutter Webview with in app

### ISSUE THREAD

**Issue by shine06** [flutter/flutter#19610]
I Flutter need to create webview with in the app and it should support Bootstrap also.
Can anyone suggest me or provide any sample.

**Comment by ram231** [comment]
Not available as of this moment. But you can use the url_launcher.

**Comment by SteveAlexander** [comment]
https://pub.dartlang.org/packages/flutter_webview_plugin

works fine for me

**Comment by zoechi** [comment]
Dup of #730
