### ISSUE TITLE
Add Cirrus CI to Flutter Dashboard

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19621]
In order to switch to Cirrus, we'll need to have it's status available on our dashboard.

Cirrus doesn't have a web API for getting the status, but that's OK, GitHub does.

To get the list of available info:
https://api.github.com/repos/flutter/flutter

To get the list of commits to flutter, go here:
https://api.github.com/repos/flutter/flutter/commits

To get status information on a particular commit, go here:
https://api.github.com/repos/flutter/flutter/statuses/90a5f4613fa3a9bbce7061b02b10d8de69488e17

So, really, it would be best if we just got all of our status from GitHub anyhow.

To do that, we need to:
  - [ ] Remove the custom status updaters from cocoon for Appveyor and Travis
  - [ ] Write a replacement status updater for the GitHub statuses that shows only the CI agents that we care about (Just the Cirrus ones).

For other tasks related switching to Cirrus, see #19608

**Comment by jonahwilliams** [comment]
Fixed by latest dashboard version
