### ISSUE TITLE
Theme.textTheme.button.color is ignored by RaisedButton & FlatButton

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#19623]
### Problem:
`RaisedButton` and `FlatButton` ignore the `color` attribute provided by the `textTheme.button.color` attribute in `ThemeData`.

Edit: removed noise.

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
There is no `ThemeData.button` anymore.
You can use `ThemeData.buttonTheme.textTheme` to select `accent`, `normal`, `primary`.

I haven't found a way to globally change button text style besides what I mentioned before.

**Comment by modulovalue** [comment]
```
AnimatedTheme(
    data: ThemeData.light().copyWith(
        accentColor: Colors.blue,
        buttonTheme: ButtonThemeData(
            textTheme: ButtonTextTheme.accent,
        ),
        textTheme: ThemeData
            .light()
            .textTheme
            .copyWith(
            button: TextStyle(
                color: Colors.pink,
            )
        ),
    ),
    child: RaisedButton(
        child: Text("ButtonTextTheme.accent"),
        onPressed: () {},
    ),
),
AnimatedTheme(
    data: ThemeData.light().copyWith(
        accentColor: Colors.blue,
        buttonTheme: ButtonThemeData(
            textTheme: ButtonTextTheme.normal,
        ),
        textTheme: ThemeData
            .light()
            .textTheme
            .copyWith(
            button: TextStyle(
                color: Colors.pink,
            )
        ),
    ),
    child: RaisedButton(
        child: Text("ButtonTextTheme.normal"),
        onPressed: () {},
    ),
),
AnimatedTheme(
    data: ThemeData.light().copyWith(
        accentColor: Colors.blue,
        buttonTheme: ButtonThemeData(
            textTheme: ButtonTextTheme.primary,
        ),
        textTheme: ThemeData
            .light()
            .textTheme
            .copyWith(
            button: TextStyle(
                color: Colors.pink,
            )
        ),
    ),
    child: RaisedButton(
        child: Text("ButtonTextTheme.primary"),
        onPressed: () {},
    ),
),                  
```
 
- ThemeData.textTheme.button.color is never used with the currently available `ButtonTextTheme` values.

**Comment by jaumard** [comment]
So here is a small way to reproduce it: 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

final color = Colors.blue;

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primaryColor: color,
        buttonColor: color,
        buttonTheme: ButtonThemeData(buttonColor: color),
        textTheme: const TextTheme(body1: TextStyle(color: Colors.grey), button: TextStyle(color: Colors.red)),
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            FlatButton(onPressed: () {}, child: Text('Test')),
            RaisedButton(onPressed: () {}, child: Text('Test')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
I expect the raised and flat button text is red, but is stay black. 

I'm using 1.0.0 stable version of flutter

**Comment by GiacomoPignoni** [comment]
I have the  same problem

**Comment by fgatti675** [comment]
Any updates on this? Feels weird I can't change the text color of buttons

**Comment by YAPPDEF** [comment]
Same here.. Please upvote the first comment

**Comment by lukepighetti** [comment]
```dart
import 'package:flutter/material.dart';

const _kPrimaryColor = Color(0xFF6D9AEC);
const _kAccentColor = Color(0xFF8FECFF);

class Themes {
  static ThemeData get light => ThemeData(
        primaryColor: _kPrimaryColor,
        accentColor: _kAccentColor,
        buttonTheme: ButtonThemeData(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          padding: EdgeInsets.all(16),
          buttonColor: _kAccentColor,
          textTheme: ButtonTextTheme.normal,
        ),
        textTheme: TextTheme(
          display1: TextStyle(
            fontFamily: "Bahnschrift",
            color: _kPrimaryColor,
            fontSize: 14,
            fontWeight: FontWeight.w600,
          ),
          button: TextStyle(
            fontFamily: "Bahnschrift",
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.w400,
          ),
        ),
      );
}

```dart
        FlatButton(
          color: Theme.of(context).primaryColor,
          onPressed: () => null,
          child: Text("Phone"),
        ),
        FlatButton(
          color: Theme.of(context).accentColor,
          onPressed: () => null,
          child: Text("Email"),
        ),
```

No matter what you do, the color of the button text is not themeable.

**Comment by kolaente** [comment]
I ended up creating my own button widget based on a container which I then could style however I want:

```dart
Container(
          width: width,
          height: height,
          decoration: BoxDecoration(boxShadow: [
            BoxShadow(
              color: vButtonShadow,
              offset: Offset(-5, 5),
              blurRadius: 10,
            ),
          ]),
          child: Material(
            borderRadius: BorderRadius.circular(3),
            color: vButtonColor,
            child: InkWell(
                onTap: onPressed,
                child: Center(
                  child: Text(
                      'Lorem Ipsum',
                      style: TextStyle(color: vButtonTextColor, fontWeight: FontWeight.w600),
                      ),
                )),
          ),
        )
```

The colors are `consts` I defined in another file.

**Comment by vware** [comment]
That should be a rather trivial to change in the Framework... is a pull request desired?

**Comment by ch-muhammad-adil** [comment]
I have tried to change colour of DateTimePicker 
```

        Theme(
            data: Theme.of(context).copyWith(
              primaryColor: Colors.orange,
              accentColor: Colors.green,
              buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal)

            ),
            child: Builder(builder: (context) {
            return Button(onTap:(){
//                  displaying picker from here
              });
            }))
```

I have tried everything with button theme

` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.primary)`
` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.accent)`
` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal)`

and many other things i have tried at in theme, but end results are not worked for me the button's text color stays same  

Here is the screenshot 

<img width="460" alt="Screenshot 2019-04-10 at 12 18 16 PM" src="https://user-images.githubusercontent.com/8264639/55859458-8dda8180-5b8b-11e9-9e31-def5a34360d3.png">

**Comment by fgatti675** [comment]
Guys any update on this? It's the second project I bump into this issue already. I have ended up building my own components instead of using the built in buttons

**Comment by DineshTamang** [comment]
> I have tried to change colour of DateTimePicker
> 
> ```
> 
>         Theme(
>             data: Theme.of(context).copyWith(
>               primaryColor: Colors.orange,
>               accentColor: Colors.green,
>               buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal)
> 
>             ),
>             child: Builder(builder: (context) {
>             return Button(onTap:(){
> //                  displaying picker from here
>               });
>             }))
> ```
> 
> I have tried everything with button theme
> 
> ` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.primary)`
> ` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.accent)`
> ` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal)`
> 
> and many other things i have tried at in theme, but end results are not worked for me the button's text color stays same
> 
> Here is the screenshot
> 
> <img alt="Screenshot 2019-04-10 at 12 18 16 PM" width="460" src="https://user-images.githubusercontent.com/8264639/55859458-8dda8180-5b8b-11e9-9e31-def5a34360d3.png">

I am exactly facing the same problem as mentioned. Please look on this issue asap if possible that would be very helpful.

**Comment by lukepighetti** [comment]
If Flutter team is too busy to fix broken theme stuff, can they point us in the right direction for what blockers can be addressed?

**Comment by Lootwig** [comment]
The docs of ButtonTextTheme states:

```
enum ButtonTextTheme {
  /// Button text is black or white depending on [ThemeData.brightness].
  normal,

  /// Button text is [ThemeData.accentColor].
  accent,

  /// Button text is based on [ThemeData.primaryColor].
  primary,
}
```

For `normal` as well as `accentColor`, the description is in fact working. 
For `primary`. i have observed the text color to actually be dependent on `primarySwatch` rather than just `primaryColor` (resulting in either black or white, according to the programmatically determined brightness of your swatches' colors).

So if you want to colorize your button, you will have to pick the corresponding `accentColor` and set `ButtonTextTheme.accent` accordingly. Maybe the "TextTheme..." properties are now legacy ways to achieve the theming which have been preserved for compatibility reasons..?

**Comment by ykaito21** [comment]
> I have tried to change colour of DateTimePicker
> 
> ```
> 
>         Theme(
>             data: Theme.of(context).copyWith(
>               primaryColor: Colors.orange,
>               accentColor: Colors.green,
>               buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal)
> 
>             ),
>             child: Builder(builder: (context) {
>             return Button(onTap:(){
> //                  displaying picker from here
>               });
>             }))
> ```
> 
> I have tried everything with button theme
> 
> ` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.primary)`
> ` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.accent)`
> ` buttonTheme: ButtonThemeData(textTheme: ButtonTextTheme.normal)`
> 
> and many other things i have tried at in theme, but end results are not worked for me the button's text color stays same
> 
> Here is the screenshot
> 
> <img alt="Screenshot 2019-04-10 at 12 18 16 PM" width="460" src="https://user-images.githubusercontent.com/8264639/55859458-8dda8180-5b8b-11e9-9e31-def5a34360d3.png">

I also have the same problem. Does someone knows any update or way to solve this problem?

**Comment by patelkrunal78** [comment]
Maybe a bit late... but you can use this:

ThemeData(
    primaryTextTheme: Typography(platform: TargetPlatform.iOS).white,
    textTheme: Typography(platform: TargetPlatform.iOS).white,
)

https://icetutor.com/question/how-to-change-the-entire-themes-text-color-in-flutter

**Comment by migalv** [comment]
Hello everyone, I have had this issue and it was very fustrating to solve, but I think I found some kind of work around.

It seems that the only way to apply color to the text of FlatButtons using a Theme is by using a ColorScheme like this:

```
ThemeData yourTheme= ThemeData(

    // Your themes 
    // . . . maybe you could be setting the textTheme
    // . . . or the primary & secondary colors
    // . . . even set your color scheme
    ////////////////

    buttonTheme: ButtonThemeData(
      colorScheme: ColorScheme( // You need to set up a color scheme for your 
        buttomTheme (even if you already did on your ThemeData)
        background: background, // NOT USED
        brightness: Brightness.light, // I have tried dark & light and it seems like this workaround only works on ligh
        error: errorColor, // NOT USED
        onBackground: Colors.black87, // NOT USED
        onError: Colors.white, // NOT USED
        onSurface: Colors.black87, // NOT USED
        onSecondary: Colors.black87, // NOT USED
        onPrimary: Colors.black, // NOT USED
        primary: secondary700, // IMPORTANT LINES: This sets the text color for FlatButtons
        primaryVariant: secondary700,
        secondary: Colors.black, // IMPORTANT LINES: This sets the text color for RaisedButtons
        secondaryVariant: Colors.black, 
        surface: Colors.white, // NOT USED
      ),
      buttonColor: secondaryMain,  // IMPORTANT LINES: This sets the fill color of your raised buttons
      disabledColor: disabledColor, 
      textTheme: ButtonTextTheme.accent, // IMPORTANT LINES: Makes everything happen
    );
  );
```

For some other reason this does not apply to DatePickers, so the workaround for those is to do the same, like this: 

```
DateTime selectedDate = await showDatePicker(
                  context: context,
                  initialDate: DateTime.now(),
                  firstDate: DateTime.now().subtract(Duration(hours: 24)),
                  lastDate: DateTime(2030),
                  builder: (context, child) => Theme(
                    data: ThemeData(
                      colorScheme: ColorScheme(
                        background: background,
                        brightness: Brightness.light,
                        error: errorColor,
                        onBackground: Colors.black87,
                        onError: Colors.white,
                        onSurface: Colors.black87,
                        onSecondary: Colors.black87,
                        onPrimary: Colors.black,
                        primary: secondary700, //  FLAT BUTTON COLOR
                        primaryVariant: secondary700,
                        secondary: Colors.black,
                        secondaryVariant: Colors.black,
                        surface: Colors.white,
                      ),
                      primaryColor: secondaryMain, //  HEADER COLOR
                      accentColor: secondaryMain, // DATE COLOR
                      buttonTheme: ButtonThemeData(
                        textTheme: ButtonTextTheme.accent,
                      ),
                    ),
                    child: child,
                  ),
                );
```

Hope it works for you too ;) 
Let me know if it did! :P

**Comment by vargavince91** [comment]
FWIW, I just copied the code for the time picker and modified it by explicitly setting the colors of the flat buttons, it took around 5 minutes, so that might be the quickest solution.

**Comment by g1eny0ung** [comment]
Currently, for `showDatePicker`, I prefer to use `primarySwatch` to set the buttons' color. This is a relatively simple way that I have found without much more modification.

**Comment by padmanabanSampath** [comment]
> Hello everyone, I have had this issue and it was very fustrating to solve, but I think I found some kind of work around.
> 
> It seems that the only way to apply color to the text of FlatButtons using a Theme is by using a ColorScheme like this:
> 
> ```
> ThemeData yourTheme= ThemeData(
> 
>     // Your themes 
>     // . . . maybe you could be setting the textTheme
>     // . . . or the primary & secondary colors
>     // . . . even set your color scheme
>     ////////////////
> 
>     buttonTheme: ButtonThemeData(
>       colorScheme: ColorScheme( // You need to set up a color scheme for your 
>         buttomTheme (even if you already did on your ThemeData)
>         background: background, // NOT USED
>         brightness: Brightness.light, // I have tried dark & light and it seems like this workaround only works on ligh
>         error: errorColor, // NOT USED
>         onBackground: Colors.black87, // NOT USED
>         onError: Colors.white, // NOT USED
>         onSurface: Colors.black87, // NOT USED
>         onSecondary: Colors.black87, // NOT USED
>         onPrimary: Colors.black, // NOT USED
>         primary: secondary700, // IMPORTANT LINES: This sets the text color for FlatButtons
>         primaryVariant: secondary700,
>         secondary: Colors.black, // IMPORTANT LINES: This sets the text color for RaisedButtons
>         secondaryVariant: Colors.black, 
>         surface: Colors.white, // NOT USED
>       ),
>       buttonColor: secondaryMain,  // IMPORTANT LINES: This sets the fill color of your raised buttons
>       disabledColor: disabledColor, 
>       textTheme: ButtonTextTheme.accent, // IMPORTANT LINES: Makes everything happen
>     );
>   );
> ```
> 
> For some other reason this does not apply to DatePickers, so the workaround for those is to do the same, like this:
> 
> ```
> DateTime selectedDate = await showDatePicker(
>                   context: context,
>                   initialDate: DateTime.now(),
>                   firstDate: DateTime.now().subtract(Duration(hours: 24)),
>                   lastDate: DateTime(2030),
>                   builder: (context, child) => Theme(
>                     data: ThemeData(
>                       colorScheme: ColorScheme(
>                         background: background,
>                         brightness: Brightness.light,
>                         error: errorColor,
>                         onBackground: Colors.black87,
>                         onError: Colors.white,
>                         onSurface: Colors.black87,
>                         onSecondary: Colors.black87,
>                         onPrimary: Colors.black,
>                         primary: secondary700, //  FLAT BUTTON COLOR
>                         primaryVariant: secondary700,
>                         secondary: Colors.black,
>                         secondaryVariant: Colors.black,
>                         surface: Colors.white,
>                       ),
>                       primaryColor: secondaryMain, //  HEADER COLOR
>                       accentColor: secondaryMain, // DATE COLOR
>                       buttonTheme: ButtonThemeData(
>                         textTheme: ButtonTextTheme.accent,
>                       ),
>                     ),
>                     child: child,
>                   ),
>                 );
> ```
> 
> Hope it works for you too ;)
> Let me know if it did! :P

This Did it...... thanks

**Comment by HansMuller** [comment]
@modulovalue, @jaumard @YAPPDEF @lukepighetti @kolaente @Lootwig @vware @ch-muhammad-adil @fgatti675 @DineshTamang @migalv @ykaito21 @padmanabanSampath  There's a rather wide-reaching proposal to remedy the problems that have come up in this issue. Please take a look at https://github.com/flutter/flutter/issues/54776. We'd appreciate your feedback.

**Comment by modulovalue** [comment]
@HansMuller Thank you.

For those stumbling across this issue, please check out #54776 where a concrete solution is being proposed.
