### ISSUE TITLE
port gradle logic to java or kotlin

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#19625]
Apparently using "groovy" is no longer cool (it uses reflection or something), and we should move to Java or Kotlin for our gradle scripts.

**Comment by jonahwilliams** [comment]
I don't think we would plan to do this one ourselves, but I would certainly review/welcome patches from people who felt more strongly about it.

**Comment by jonahwilliams** [comment]
For posterity, the flutter.gradle script lives in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle

**Comment by blasten** [comment]
This has been suggested by the AGP team too. They built AGP in Kotlin

**Comment by stuartmorgan** [comment]
Another reason to switch to Kotlin would be to reduce the number of languages that developers have to interact with when using Flutter. The default app and plugin templates have been using Kotlin for a while, so changing the gradle files in the template to Kotlin would reduce the language set for Android development from {Dart, Kotlin, Groovy} to {Dart, Kotlin}.

(We'd need to update all the docs about gradle files to show both though.)

**Comment by reidbaker** [comment]
Closing this as a dup of #121541 since that bug is a bit better in clarity and scope.
