### ISSUE TITLE
Failed to add image_picker to existing project.

### ISSUE THREAD

**Issue by pblinux** [flutter/flutter#19622]
## Steps to Reproduce

1. Add image_picker to dependencies.
2. Run project.

Dependencies on pubspec.yaml:

```yml
cloud_firestore:
firebase_auth:
flutter_facebook_login:
shared_preferences:
image_picker:
```

## Logs

`flutter run --verbose`

```
[        ] :image_picker:platformAttrExtractor UP-TO-DATE
[  +25 ms] :image_picker:processDebugResources FAILED
[  +11 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':image_picker:processDebugResources'.
[        ] > java.io.IOException: Internal error: Symbol file with package cannot be empty.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[        ] 82 actionable tasks: 5 executed, 77 up-to-date
[ +423 ms] "flutter run" took 5,220ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:404)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:318)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:36)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:377)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:289)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:216)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:395)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     runZoned (dart:async/zone.dart:1501)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#16     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1126)
#20     _CustomZone.run (dart:async/zone.dart:1023)
#21     runZoned (dart:async/zone.dart:1501)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1126)
#31     _CustomZone.run (dart:async/zone.dart:1023)
#32     runZoned (dart:async/zone.dart:1501)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50)
#36     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#37     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

`flutter analyze`

Analyzing top_app...
No issues found! (ran in 1.3s)

`flutter doctor -v`
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /opt/flutter
    • Framework revision c7ea3ca377 (7 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/pblinux/.Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/pblinux/.Android/SDK
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.0)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by sir-boformer** [comment]
I just installed image_picker, and it works perfectly on my machine.

**Comment by zoechi** [comment]
I'd also suggest to try `dev` or `master` channel.
```sh
flutter channel dev
flutter doctor
```

**Comment by pblinux** [comment]
Thanks for response and sorry for delay.

I tried to switch to dev channel but have same result.

`flutter doctor`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

• No issues found!

`flutter run --verbose`
[        ] Execution failed for task ':image_picker:processDebugResources'.
[        ] > java.io.IOException: Internal error: Symbol file with package cannot be empty.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s
[        ] 82 actionable tasks: 6 executed, 76 up-to-date
[ +431 ms] "flutter run" took 6,939ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:368)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:278)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:36)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:376)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:292)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:241)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:400)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#10     _rootRunUnary (dart:async/zone.dart:1134)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#14     Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     Future._complete (dart:async/future_impl.dart:472)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/dart:async/async_patch.dart:28)
#18     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:211)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#21     _rootRunUnary (dart:async/zone.dart:1134)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#25     Future._propagateToListeners (dart:async/future_impl.dart:667)
#26     Future._complete (dart:async/future_impl.dart:472)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:33)
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#34     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

**Comment by cyanglaz** [comment]
@pblinux Are you still experiencing this issue? Could you try to do a `flutter clean` and run again?
