### ISSUE TITLE
Allow custom colors for SegmentedControl

### ISSUE THREAD

**Issue by lukaspili** [flutter/flutter#19636]
The new SegmentedControl widget seems to have hardcoded colors for unselected (`CupertinoColors.white`) and selected (`CupertinoColors.activeBlue`) states. 

Developer should be able to change colors for:
- text
- background
- border
- on press highlight

**Comment by nataliesampsell** [comment]
Issue fixed with https://github.com/flutter/flutter/pull/20005, closing.
