### ISSUE TITLE
Unexpected offset space above ListView 

### ISSUE THREAD

**Issue by alisson226** [flutter/flutter#19648]
Hi guys, I'm trying to build my first app with Flutter and I'm loving it, but with the code below I'm getting an unexpected blank space above my ListView, can someone help me? Thank you !!

Expected:
![image](https://user-images.githubusercontent.com/24798322/43039042-fb28f740-8cfa-11e8-9573-875998dc6656.png)

Getting:
![image](https://user-images.githubusercontent.com/24798322/43039046-0fc711aa-8cfb-11e8-9083-cfc16329090c.png)

All the code:

```dart
import 'package:flutter/material.dart';

class Despesas extends StatelessWidget {
    final List<BoxShadow> myShadows = <BoxShadow>[
      new BoxShadow(color: Colors.grey, blurRadius: 5.0, offset: Offset(2.0, 2.0))
    ];


  @override
  Widget build(BuildContext context) {
    return new Container(
      margin: EdgeInsets.only(left: 10.0, right: 10.0, top: 60.0, bottom: 30.0),
      decoration:  new ShapeDecoration(
        shape: new RoundedRectangleBorder(
          borderRadius: BorderRadius.only(bottomLeft: Radius.circular(20.0), bottomRight: Radius.circular(20.0), topLeft: Radius.circular(20.0), topRight: Radius.circular(20.0)),
          side: new BorderSide( color: Colors.transparent)
        ),
        shadows: myShadows,
      ),
      child: new ClipRRect(
        child: ListView.builder(
          scrollDirection: Axis.vertical,
          shrinkWrap: true,
          itemExtent: 85.0,
          itemBuilder: (BuildContext context, int index) {
            return new Container(
              color: Colors.red,
              margin: EdgeInsets.only(bottom: 0.0, left: 0.0, top: 0.0, right: 0.0),
              child: new Center(
                child: new Text("entry $index", style: new TextStyle(color: Colors.white)),
              )
            );
        },
      ),
      borderRadius: BorderRadius.circular(20.0)
      ),

    );
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Setting `padding` to `0` might help

```dart
          child: ListView.builder(
            padding: EdgeInsets.all(0.0),
```
(or `padding: EdgeInsets.only(top: 0.0),`)

**Comment by alisson226** [comment]
Perfect, the padding worked perfectly!! Thank you so much!

**Comment by zoechi** [comment]
Glad to hear. 
Sounds like the issue can be closed.

Setting
```
debugPaintSizeEnabled = true; // import from 'package:flutter/rendering.dart' 
```
makes ist quite easy to find the cause for such issues.

**Comment by alisson226** [comment]
Thanks for the tip!

**Comment by kapil708** [comment]
> Setting `padding` to `0` might help
> 
> ```dart
>           child: ListView.builder(
>             padding: EdgeInsets.all(0.0),
> ```
> 
> (or `padding: EdgeInsets.only(top: 0.0),`)

Thanks it work for me.

**Comment by HoneyBadger999** [comment]
thanks, worked for me too.

**Comment by sudoosama** [comment]
> Setting `padding` to `0` might help
> 
> ```dart
>           child: ListView.builder(
>             padding: EdgeInsets.all(0.0),
> ```
> 
> (or `padding: EdgeInsets.only(top: 0.0),`)

Why is isnt working for me

**Comment by tungondugi** [comment]
> Setting `padding` to `0` might help
> 
> ```dart
>           child: ListView.builder(
>             padding: EdgeInsets.all(0.0),
> ```
> 
> (or `padding: EdgeInsets.only(top: 0.0),`)

You Saved My Life....Thank you.😂

**Comment by ankittale** [comment]
You saved my life too. Thanks .😂

**Comment by TrungJamin** [comment]
> Setting `padding` to `0` might help
> 
> ```dart
>           child: ListView.builder(
>             padding: EdgeInsets.all(0.0),
> ```
> 
> (or `padding: EdgeInsets.only(top: 0.0),`)

Thank you sir! respect!
