### ISSUE TITLE
how to make video_player prepare and start to play quicklier?

### ISSUE THREAD

**Issue by hyz1992** [flutter/flutter#19643]
video_player now is too slow，because it doesn't start to play until download success. and it will download a same video repeatedly when the VideoController rebuild. So is there some way to resolve this problem, such as use cache?

flutter doctor -v:
`C:\Users\Administrator>flutter doctor -v
[âˆš] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 6.3.9600], lo
cale zh-CN)
    â€¢ Flutter version 0.5.1 at E:\flutter
    â€¢ Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    â€¢ Engine revision 1ed25ca7b7
    â€¢ Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    â€¢ Android SDK at D:\Sdk
    â€¢ Android NDK location not configured (optional; useful for native profili
ng support)
    â€¢ Platform android-P, build-tools 27.0.3
    â€¢ Java binary at: E:\AndroidStudio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b
02)
    X Android license status unknown.

[âˆš] Android Studio (version 3.1)
    â€¢ Android Studio at E:\AndroidStudio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b
02)

[âˆš] Connected devices (1 available)
    â€¢ Android SDK built for x86 â€¢ emulator-5554 â€¢ android-x86 â€¢ Android
6.0 (API 23) (emulator)

! Doctor found issues in 1 category.`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
