### ISSUE TITLE
"flutter create" should use our dependency-testing logic to give appropriate next steps

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1964]
Right now it unconditionally says to call "flutter run", which won't work if your dependencies aren't installed, or your devices aren't plugged in and there's no simulator running, etc.

Since calling "flutter create" happens early in the getting started guide, and before you've got your dependencies ready, having it say to use "flutter run" can be confusing and lead to frustration.

**Comment by devoncarew** [comment]
We should have it call out to `doctor.summary()`, which will tell them what the state of their toolchain is and prompt them to run flutter doctor if necessary.
