### ISSUE TITLE
Google Maps Plugin infoWindow open by default

### ISSUE THREAD

**Issue by Asoseil** [flutter/flutter#19647]
Is there a param to display or hide an infoWindow? I would like to display an infowindow already open on startup

**Comment by lucien-theron** [comment]
Ahh yes please! This would be great.

**Comment by zoechi** [comment]
@lucien-theron Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by emersonsiega** [comment]
I also need this behavior in my app.
Is there a mechanism to show/hide InfoWindow?

**Comment by Xgamefactory** [comment]
guess team has no idea )

**Comment by lucien-theron** [comment]
Hi any updates on this?

**Comment by matte5031** [comment]
would need this aswell

**Comment by kalittles** [comment]
Is there any update on this? 
Or anyone with a potential workaround?

**Comment by viltiki** [comment]
> Is there any update on this?
> Or anyone with a potential workaround?

Look here: https://github.com/flutter/flutter/issues/33481#issuecomment-536334663

**Comment by iskakaushik** [comment]
@giancarlopro has a PR in works for this https://github.com/flutter/plugins/pull/2181/, happy to review it once it is out of the Draft form.

**Comment by kf6gpe** [comment]
Dropping @iskakaushik as I suspect he's not actively working on this; we'll wait for the PR updates.

**Comment by cyanglaz** [comment]
I think a better way would be to add a method to show and hide infoWindows. There is already an issue specifically for that https://github.com/flutter/flutter/issues/33481 and  flutter/plugins#2181 is also trying to address that issue.
@Asoseil Would you agree if I say this issue is a dup with https://github.com/flutter/flutter/issues/33481 and I go ahead close this issue? So it is easier for us to keep track of the fix.

**Comment by cyanglaz** [comment]
Shout-out to @giancarlopro who added this feature in flutter/plugins#2181.
It should be available in 0.5.23+1 and above!
I am going to close the issue.

**Comment by msarkrish** [comment]
@cyanglaz  How to set infowindow to open by default in Google map, is there any parameter is there. because i update to latest version then also it's not showing infowindow by default.

**Comment by msarkrish** [comment]
can i show more than one infowindow open by default?

**Comment by cyanglaz** [comment]
@msarkrish You might have to call the method multiple times with different markerId I assume?

**Comment by msarkrish** [comment]
@cyanglaz at a time it showing only one infowindow open by default. i'm calling that method inside loop with more than one marker but it showing only one marker at a time open by default.

**Comment by giancarlopro** [comment]
@msarkrish In the docs it says 
`Best practices: For the best user experience, only one info window should be open on the map at any one time. ` - [Google Maps Docs](https://developers.google.com/maps/documentation/javascript/infowindows?hl=pt-br#add)
