### ISSUE TITLE
pub --trace upgrade --verbosity=error --no-packages-dir

### ISSUE THREAD

**Issue by zhangxuanru** [flutter/flutter#19642]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

===== asynchronous gap ===========================
package:args/command_runner.dart 194                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                     new Future.sync
package:pub/src/utils.dart 115                                                                 captureErrors.<fn>
dart:async                                                                                     runZoned
package:pub/src/utils.dart 134                                                                 captureErrors
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8  main
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

等待 1 秒，按 CTRL+C 退出 ...
终止批处理操作吗(Y/N)? y

C:\Users\zhang>

![image](https://user-images.githubusercontent.com/11569114/43034474-a42ca576-8d0f-11e8-8637-06682271361a.png)

```
```

**Comment by zoechi** [comment]
In Flutter projects you need use `flutter packages get` or `flutter packages upgrade`.
If this is not a Flutter project then the issue should be reported in https://github.com/dart-lang/pub

Did you follow https://github.com/flutter/flutter/wiki/Using-Flutter-in-China ?
