### ISSUE TITLE
`flutter run` always failed with weird different errors on different physical android devices for a fresh clean project

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#19640]
# Environment

OS: Arch Linux

```shell
$ flutter doctor -v
[✓] Flutter (Channel master, v0.5.8-pre.98, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.8-pre.98 at /home/user/opt/flutter
    • Framework revision f0639bb022 (21 hours ago), 2018-07-20 09:21:41 +0200
    • Engine revision 482469bad8
    • Dart version 2.0.0-dev.68.0.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version openjdk version "1.8.0_152-release"
```

```shell
$ flutter create myapp
$ cd myapp/
```

#  Mobile `Letv X501` case

Android: 6.0
Frequency: 99.9999999999999999999999999999%

```shell
$ flutter run
Launching lib/main.dart on Letv X501 in debug mode...
Initializing gradle...                                       1.3s
Resolving dependencies...                                    1.1s
Running 'gradlew assembleDebug'...                               
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  8.1s
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 FromType=0xffffffff cmp=com.example.myapp/.MainActivity (has extras) }
Error type 3
Error: Activity class {com.example.myapp/com.example.myapp.MainActivity} does not exist.
Error launching application on Letv X501.
```

I tried both English and Chinese Simplified _(中文(简体))_ system language and both gave me the same error result.

# Mobile `Letv X501` VERY RARE case

The reason why I don't say 100% frequency in the last case is because the flutter run did succeed __once__ in my __more than 30 times attempts__ (including rebooting devices and changing system languages etc...). Why? I have no idea.

```
$ flutter run
Launching lib/main.dart on Letv X501 in debug mode...
Initializing gradle...                                       1.2s
Resolving dependencies...                                    1.1s
Running 'gradlew assembleDebug'...                               
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Letv X501...                             
D/IMGSRV  ( 5730): gralloc_register_buffer:1376: hnd=0x7f8abe2e40 ID=3433 fd=63 ref=1

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
```

# Mobile `NX508J` case 1

Android: 5.1.1
System Language: Chinese Simplified _(中文(简体))_

```shell
$ flutter run
Launching lib/main.dart on NX508J in debug mode...
Initializing gradle...                                       1.1s
Resolving dependencies...                                    1.2s
Running 'gradlew assembleDebug'...                               
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                 12.8s
Package install error: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
Error launching application on NX508J.
```

# Mobile `NX508J` case 2

System Language: English
__MUST reboot__ after setting up the system language.

It works this time:

```
$ flutter run
Launching lib/main.dart on NX508J in debug mode...
Initializing gradle...                                       1.1s
Resolving dependencies...                                    1.3s
Running 'gradlew assembleDebug'...                               
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device NX508J...                                
W/art     (16489): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[20,tid=16517,Native,Thread*=0x7fa28ab000,peer=0x12d610a0,"Thread-1499"]

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
```

# Mobile `Redmi Note 3` case

Android: 7.1.1
__ROM__: Lineage OS
System Language: Chinese Simplified _(中文(简体))_

__EDITED:__ It works fine when I use adb over network. Thus I edited this case and removed my old post. (The connection lost when using adb over USB should be due to a loose micro-usb port on the phone.)

# upload apk file to devices and install it through file manager

The installation always works and the app can be run correctly. 

# Conclusion

I have no idea what the problem is because it has different failure behaviors in different android devices. `flutter run` just doesn't work at all. I am unable to develop a program like this... 
Can this bug have a higher priority so that I can continue my app development? 

Thank you very much.

**Comment by sgon00** [comment]
@zoechi 
(1) I haven't tried with Android emulator this time because the emulator was always very slow and I give up using it and don't plan to use it anymore. Physical devices are always much faster. 
(2) Yes, this is the basic app created by `flutter create myapp` with `v0.5.8-pre.98`. I have clarified this in this issue's title. No customization at all. 
(3) I tried to upgrade my android studio from `3.0.1.0-1` to the latest `3.1.3.0-1` after reporting this issue. But no luck, the result is the same. (After upgrading android studio, I did create a new app with `flutter create myapp`.)
(4) I did google those error msgs and found this topic https://stackoverflow.com/questions/20915266/, I am not sure if this is related to this issue.

**Comment by sgon00** [comment]
I have 6 android mobiles and it's working fine on 2 of them. I am OK to use the two working ones for development. I think this is a bug belongs to gradle insead of flutter so I am closing it for now. Cheers.

**Comment by ra7bi** [comment]
im most cases this happened when the app already installed and you try to reinstall it again , to fix this 

uninstall the app using **adb  shell** 

`adb -s DEVICEID  uninstall example.foo.com`

Example in MacOS
First list connected devices 
`flutter devices`

`/Users/coder/Library/Android/sdk/platform-tools/adb -s XFDFDFA00900 uninstall example.foo.com`

**Comment by panw3i** [comment]
> im most cases this happened when the app already installed and you try to reinstall it again , to fix this
> 
> uninstall the app using **adb shell**
> 
> `adb -s DEVICEID uninstall example.foo.com`
> 
> Example in MacOS
> First list connected devices
> `flutter devices`
> 
> `/Users/coder/Library/Android/sdk/platform-tools/adb -s XFDFDFA00900 uninstall example.foo.com`

Working for me!
