### ISSUE TITLE
Flutter Installation broken - flutter_tools requires SDK version >=1.19.0 <2.0.0

### ISSUE THREAD

**Issue by flowhorn** [flutter/flutter#19654]
Hello there,
for the last fest month flutter worked wonderfully, there were just minor issues.
But starting today I can't use it anymore. 
The issue seems to be related to dart2 and some incompatibilty?
This is the error message:

> The current Dart SDK version is 2.0.0-dev.63.0.flutter-4c9689c1d2.

> Because flutter_tools requires SDK version >=1.19.0 <2.0.0, version solving failed.

> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

I tried almost anything:
Deleting any cache i could find of flutter/dart
Updating git
Reinstalling flutter again and again (even archived packages)

Btw: flutter doctor gave a perfect output, at least it did, because I also can't use it anymore. I tried the dev and beta build. The curious thing is, that flutter in the beta channel worked fine before. But I recently switched the channels to try out new features and I updated packages to have everything up to date.
I hope that there will be help, I don't know what to do except for completly wiping the whole pc :/
Actually I wanted to build a new release apk for the play store...

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
Switching to `dev` channel might be worth a try: 
```
flutter channel dev
flutter doctor
```

**Comment by flowhorn** [comment]
I can't use any of these commands. Whether I try to switch the channel or use flutter doctor, the message that version solving failed always appears.

I am also already using the latest dev.

**Comment by flowhorn** [comment]
Is there any cache or so that i can clear? I mean dart 2 is supported for a long time, so the problem seems to be related to my flutter-tools.
I tried the latest beta, dev and master. But the error doesn't disappear.

**Comment by zoechi** [comment]
What OS and what command line shell are you using?
What is the output of `which flutter`?
Perhaps you have an older Flutter version somewhere and the PATH points still to it.
There is no cache outside the Flutter install directory.

**Comment by DanTup** [comment]
If you can't change channel with `flutter` you could try doing it with git:

```
# Run this in your *flutter* install folder, not your project!
git fetch
git reset --hard beta
```

You can also try manually clearing the `bin/cache` folder in your flutter install.

**Comment by flowhorn** [comment]
Thank you for your help,
in the end nothing helped. I deleted the complete flutter folder and downloaded it fresh. Even other git command I found in other commands didn't help.

It was just curios. So I decided to completly wipe my OS (was Windows 10). Now everything workes fine. So I guess you can close this issue. Just weird.

**Comment by zoechi** [comment]
@flowhorn thanks for the update

**Comment by Kerego** [comment]
I am facing the same issue, completely deleting flutter and fresh start didn't help.

> Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 1ed25ca7b7e3e3e8047df050bba4174074c9b336...
Unzipping Dart SDK...
Updating flutter tool...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.
Because flutter_tools requires SDK version >=1.19.0 <2.0.0, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

**Comment by zoechi** [comment]
@Kerego which directory did you install Flutter to?

**Comment by Kerego** [comment]
C:\flutter

**Comment by DanTup** [comment]
> Because flutter_tools requires SDK version >=1.19.0 <2.0.0, version solving failed.

@Hixie You removed this SDK constraint from `flutter_tools` in #19013. Was that to fix issues like the above? Any idea why it would only occur for some people and not others?

**Comment by Kerego** [comment]
I have the it installed in the same directory on different computer and it works fine,
I'll try your solution later today.

**Comment by Kerego** [comment]
The commands above didn't solve the issue.
I've tried manually updating the packages versions, and removing sdk version constraint, but was blocked by package [mustache](https://github.com/xxgreg/mustache) which seems to not support dart 2 yet.

**Comment by zoechi** [comment]
That's an entirely different problem than 

> Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Please post the full output.

**Comment by Hixie** [comment]
@DanTup I removed that because I couldn't figure out what it meant and nobody I spoke to could figure it out either.

**Comment by Kerego** [comment]
@zoechi that is basically all output, after five seconds it retries and shows the same error

**Comment by zoechi** [comment]
@Kerego I meant

> blocked by package mustache which seems to not support dart 2 yet.

**Comment by Kerego** [comment]
oh, that one, I am on different machine now, and cannot get the output till evening, but basically the output was something like 
> flutter_tools depends on mustache >=1.0.1 which requires SDK >=1.0.0 <2.0.0, version solving failed

**Comment by Kerego** [comment]
As said above, this is the only output I get from flutter

> Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 6fe748490d1772d72274bf8b9efb72c5c2160237...
Unzipping Dart SDK...
Updating flutter tool...
The current Dart SDK version is 2.0.0-dev.63.0.flutter-4c9689c1d2.
Because flutter_tools depends on mustache >=0.1.1 which requires SDK version <2.0.0, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

**Comment by DanTup** [comment]
Have you ever set the `_PUB_TEST_SDK_VERSION` environment variable? This seems like the behaviour will be when v2 is stable, which should be opt-in right now - see here:

https://groups.google.com/a/dartlang.org/d/msg/misc/4u_inf0ngbQ/i-Cfnp0dCgAJ

I can repro this message by setting that environment variable, but not otherwise.

**Comment by Kerego** [comment]
I didn't find the environment variable you mentioned;
but there was a different one `PUB_ALLOW_PRERELEASE_SDK` set to `false`
once set to `true` it fixed the issue.
Thanks.
