### ISSUE TITLE
TextFormField inside a InputDecorator

### ISSUE THREAD

**Issue by magnocastro** [flutter/flutter#19656]
## Steps to Reproduce

1. Create a `InputDecorator`
2. Place a simple `new TextFormField()` in the child
3. Run

## Logs

```
I/flutter: The following assertion was thrown during performLayout():
    not implemented
    'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
 I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
      https://github.com/flutter/flutter/issues/new
```
I need this because i try create something like that:
![screenshot_1532222620](https://user-images.githubusercontent.com/14947820/43041433-bce3a69c-8d36-11e8-8d75-ebd58b973435.png)

So, its possible create a `TextFormField` without `InputDecoration` or with `decoration: new InputDecoration(hintText: 'Quantidade')` inside a `InputDecorator`?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
I think that you need to use `TextFormField(decoration: ...)` to set decoration instead of using `InputDecorator` as parent for a `TextField` or `TextFormField`.

/cc @HansMuller is that correct?

**Comment by magnocastro** [comment]
`
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [versÃ£o 10.0.17134.165], locale pt-BR)
    • Flutter version 0.5.1 at D:\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Users\magno\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.5087.20
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
`
I have the Flutter and Dart plugins installed in my IDEA and i still tried reinstall, but this not resolved

**Comment by magnocastro** [comment]
How i say, i want the `DropDownButton` and `TextFormField` in the same `InputDecorator` (if is possible)

**Comment by zoechi** [comment]
I don't know. The closest I found was https://github.com/flutter/flutter/blob/f630f90d6d27ce716ac3c24861c3065b1a981612/examples/flutter_gallery/lib/demo/material/date_and_time_picker_demo.dart

**Comment by cosinus84** [comment]
I had same issues. So I ended up with this.
```
Column(children: <Widget>[
                          InputDecorator(
                            decoration: InputDecoration(
                                labelText: "Client name",
                                isDense: true,
                                border: InputBorder.none,
                                labelStyle: TextStyle(height: 2.0)),
                          ),
                          TextFormField(
                            decoration: InputDecoration(
                                labelStyle: TextStyle(fontSize: 12.0),
                                isDense: true,
                                hintText: "Add client name"),
                          )
                        ]),
```
![screen shot 2018-08-06 at 10 49 18](https://user-images.githubusercontent.com/1459132/43703731-6a869062-9966-11e8-93c8-e40c0b5eabb3.png)

**Comment by zoechi** [comment]
Same error as #18755

**Comment by goderbauer** [comment]
I am de-duping this against https://github.com/flutter/flutter/issues/24705, which has the same underlying issue.
