### ISSUE TITLE
Give us onLoaded and onError hooks and .load() method for Image.network()

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19662]
Requesting a feature addition to Image.network() for the following

1. onLoaded hook
2. onError hook
3. .load() async method

This will make it very easy to build out widgets that do not rely on third party libraries (a big 👍 of flutter imo) with succinct custom logic for

1) retry loads
2) hide loading animations
3) show error widgets

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/flutter_image provides at least some of what you request.

**Comment by Kartik1607** [comment]
You can use [ImageProvider](https://docs.flutter.io/flutter/painting/ImageProvider-class.html), which would get you Image stream to which you can hook the listeners.

**Comment by lukepighetti** [comment]
And here I am again at 1PM on a Monday reading through Flutter source to figure out how to call something when a Network Image loads or errors... 😒

**Comment by lukepighetti** [comment]
community handled by `flutter_advanced_networkimage`

Perhaps Flutter team can consider adding this to master. This is a great package.

https://github.com/mchome/flutter_advanced_networkimage/commit/1345829496bf3273e3a0e4c9bc8e544ab98edcd1

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/pull/18424
