### ISSUE TITLE
Utf8Decoder.convert is ~5x faster in debug mode than in release mode

### ISSUE THREAD

**Issue by miyoyo** [flutter/flutter#19666]
## Steps to Reproduce

using [data.dat](https://github.com/flutter/flutter/files/2217540/data.dat.gz) as a data source (raw msgpack data) and [this simple main.dart](https://gist.github.com/miyoyo/f0b718b715e58d85be98ef31ca41dd6e) as well as the [msgpack](https://pub.dartlang.org/packages/msgpack) package

1. Run in debug mode, take a note of the time reported by the Stopwatch (as low as 21450 ns for me)
2. Run in release mode, compare to the new time (as low as 130954 ns for me)

Looking in the observatory, I noticed that the Utf8Decode function is especially slow.
![Image of the dart observatory, Utf8Decoder.convert takes 71.65% of the unpacking time](https://i.imgur.com/twAduJs.png)
![More details on Utf8Decoder.convert](https://i.imgur.com/AROViIH.png)
(There are a few hundred [Native] calls that aren't visible here)

## flutter doctor -v
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-BE)
    • Flutter version 0.5.1 at C:\tools\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Redmi 3S • c3fadefd7d33 • android-arm64 • Android 6.0.1 (API 23)
```

**Comment by miyoyo** [comment]
The problem shows up on the master branch, but the performance is only 2.5x-3x slower now

**Comment by miyoyo** [comment]
Messing around with benchmarks, I've discovered that accessing a Uint8List up to 4 times in one line is optimized by the compiler, but anything beyond that is not

### This takes 1 µs (Anything smaller does too)
`data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7]`

### This takes 8 µs
`data[3]*0x100000000 +data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7]`

### This takes 10 µs
`data[2]*0x10000000000 + data[3]*0x100000000 +data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7]`

### This takes 13 µs
`data[1]*0x1000000000000 + data[2]*0x10000000000 + data[3]*0x100000000 +data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7]`

### This takes 15 µs
`data[0]*0x100000000000000 + data[1]*0x1000000000000 + data[2]*0x10000000000 + data[3]*0x100000000 +data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7]`

**Comment by miyoyo** [comment]
It looks like manually converting 8 bytes to a 64bit int in compiled mode is slower than converting the Uint8List object to a ByteData, then using getUint64 on it, even though manually converting is faster for smaller Uints.

### Takes less than a microsecond
```
data[0]*0x1000000 + data[1]*0x10000 + data[2]*0x100 + data[3]
```
### Takes 7 microseconds
```
data[0]*0x100000000000000 + data[1]*0x1000000000000 + data[2]*0x10000000000 + data[3]*0x100000000 + data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7]
```

### Takes 3 microseconds
```
data.buffer.asByteData().getUint64(0)
```

**Comment by aartbik** [comment]
I cannot confirm your latter conversion findings with latest dart vm and this may heavily depend on how you time the operation. Both JIT and AOT do better on the manual conversion for me. Can you share the exact stand-alone benchmark you are using to make sure we are measuring the same thing?

**Comment by miyoyo** [comment]
```dart
  //Uint64
  abaseline = 100000;
  for(var i=0;i<10000;i++){
    var s = Stopwatch()..start();
    var cache = data[0]*0x100000000000000 + data[1]*0x1000000000000 + data[2]*0x10000000000 + data[3]*0x100000000 + data[4]*0x1000000 + data[5]*0x10000 + data[6]*0x100 + data[7];
    s.stop();
    if(abaseline > s.elapsedMicroseconds){
      abaseline = s.elapsedMicroseconds;
    }
  }
  bbaseline = 100000;
  for(var i=0;i<10000;i++){
    var s = Stopwatch()..start();
    var cache = data.buffer.asByteData().getUint64(0);
    s.stop();
    if(bbaseline > s.elapsedMicroseconds){
      bbaseline = s.elapsedMicroseconds;
    }
  }
  print("[Uint64] A($abaseline) ${(abaseline == bbaseline ? "=" : (abaseline > bbaseline ? ">": "<"))} B($bbaseline)");
```

Just 10000 iterations to get the best time out of both, and the results are repeatable over time

**Comment by aartbik** [comment]
Having the timer inside the loop makes this benchmark very sensitive, especially for just a few microseconds. I modified this a bit to move the timer outside the loop (has other dangers of course for such loop invariant computations, but it seems okay here).

Results with ToT Dart, on a Intel Xeon(R) 2.60GHz:
```
JIT [Uint64] A(3776) < B(15697), verify 3978709506094216976 vs 3978709506094216976
AOT [Uint64] A( 301) < B( 1752), verify 3978709506094216976 vs 3978709506094216976
```
Modified stand-alone benchmark:

```dart
import 'dart:convert';
import 'dart:typed_data';

int convert8(Uint8List data) {
  return data[0]*0x100000000000000 +
         data[1]*0x1000000000000 +
	 data[2]*0x10000000000 +
	 data[3]*0x100000000 +
	 data[4]*0x1000000 +
	 data[5]*0x10000 +
	 data[6]*0x100 +
	 data[7];
}

int convert1(Uint8List data) {
  return data.buffer.asByteData().getUint64(0);
}

main(List<String> args) {
  var data = new Uint8List.fromList(
    new List<int>.generate(8, (int i) => 1)
  );
  int x8 = 0;
  var s = Stopwatch()..start();
  for(var i=0;i<10000;i++){
    x8 += convert8(data);
  }
  s.stop();
  int abaseline = s.elapsedMicroseconds;
  int x1 = 0;
  s = Stopwatch()..start();
  for(var i=0;i<10000;i++){
    x1 += convert1(data);
  }
  s.stop();
  int bbaseline = s.elapsedMicroseconds;
  print("[Uint64] A($abaseline) ${(abaseline == bbaseline ? "=" : (abaseline > bbaseline ? ">": "<"))} B($bbaseline), verify $x8 vs $x1");
}
```

**Comment by miyoyo** [comment]
With the master branch, on my old benchmarking method, I see an improvement on arm 64 bit (Now the Uint64 test takes 0µs) however the performance is **worse** on 32 bit devices, from 15µs to 20µs


Will test with your method next

**Comment by miyoyo** [comment]
On an MT8127, 32bit ARM chip, in an Archos 101c neon:
  AOT: 
    Master:
      [Uint64] A(181768) > B(11023), verify 3978709506094216976 vs 3978709506094216976
    Beta:
      [Uint64] A(212571) > B(56013), verify 3978709506094216976 vs 3978709506094216976
  JIT:
    Master:
      Cold:
        [Uint64] A(146805) > B(76371), verify 3978709506094216976 vs 3978709506094216976
      Hot:
        [Uint64] A(77993) > B(2418), verify 3978709506094216976 vs 3978709506094216976
    Beta:
      Cold:
        [Uint64] A(100633) > B(73041), verify 3978709506094216976 vs 3978709506094216976
      Hot:
        [Uint64] A(60853) > B(12121), verify 3978709506094216976 vs 3978709506094216976


On a MSM8937, 64bit ARM chip, in a Redmi 3S:
  AOT:
    Master:
      [Uint64] A(2073) < B(15552), verify 3978709506094216976 vs 3978709506094216976
    Beta:
      [Uint64] A(15334) < B(27717), verify 3978709506094216976 vs 3978709506094216976
  JIT:
    Master:
      Cold:
        [Uint64] A(10992) < B(42987), verify 3978709506094216976 vs 3978709506094216976
      Hot:
        [Uint64] A(1260) < B(2586), verify 3978709506094216976 vs 3978709506094216976
    Beta:
      Cold:
        [Uint64] A(11810) < B(47660), verify 3978709506094216976 vs 3978709506094216976
      Hot:
        [Uint64] A(1267) < B(10341), verify 3978709506094216976 vs 3978709506094216976


(I can't seem to find what dart ToT is, so I'll just include tests on the android emulator)
On an i5-4690k, 3.8Ghz, in an x86_64 android VM:
  JIT:
    Master:
      Cold:
        [Uint64] A(2756) < B(8890), verify 3978709506094216976 vs 3978709506094216976
      Hot:
        [Uint64] A(67) < B(124), verify 3978709506094216976 vs 3978709506094216976
    Beta:
      Cold:
        [Uint64] A(5521) < B(8708), verify 3978709506094216976 vs 3978709506094216976
      Hot:
        [Uint64] A(67) < B(584), verify 3978709506094216976 vs 3978709506094216976

**Comment by aartbik** [comment]
Thanks for these results, and sorry for non-standard nomenclature, I am still relatively new to the team. ToT=TopOfTree, i.e., how the Dart development tree is today. If you work with Dart from the Flutter tree, this may be a bit behind of what I am using, depending on when the last roll was.

**Comment by miyoyo** [comment]
Posting an update with the latest master, compared against the master in the previous post
```
Flutter 0.5.9-pre.22 • channel master • https://github.com/flutter/flutter.git
Framework • revision ef71d9d956 (7 hours ago) • 2018-08-12 00:16:43 -0700
Engine • revision e54bc4ea18
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c
```

```
On an MT8127, 32bit ARM chip, in an Archos 101c neon:
  AOT:
    [Uint64] A(2478) < B(31912), verify 3978709506094216976 vs 3978709506094216976
    A ratio:
      73,35x
    B ratio:
      0,34x
  JIT:
    Cold:
      [Uint64] A(43662) < B(78821), verify 3978709506094216976 vs 3978709506094216976
      A ratio:
        3,36x
      B ratio:
        0,96x
    Hot:
      [Uint64] A(1291) < B(2234), verify 3978709506094216976 vs 3978709506094216976
      A ratio:
        60,41x
      B ratio:
        1,08x

On a MSM8937, 64bit ARM chip, in a Redmi 3S:
  AOT:
    [Uint64] A(1885) < B(8330), verify 3978709506094216976 vs 3978709506094216976
    A ratio:
      1,10x
    B ratio:
      1,86x
  JIT:
    Cold:
      [Uint64] A(14917) < B(64492), verify 3978709506094216976 vs 3978709506094216976
      A ratio:
        0,73x
      B ratio:
        0,66x
    Hot:
      [Uint64] A(868) < B(1807), verify 3978709506094216976 vs 3978709506094216976
      A ratio:
        1,45x
      B ratio:
        1,43x

On an i5-4690k, 3.8Ghz, in an x86_64 android VM:
  JIT:
    Cold:
      [Uint64] A(3415) < B(8787), verify 3978709506094216976 vs 3978709506094216976
      A ratio:
        1,61x
      B ratio:
        0,99x
    Hot:
      [Uint64] A(66) < B(122), verify 3978709506094216976 vs 3978709506094216976
      A ratio:
        1,01x
      B ratio:
        1,01x
```

**Comment by miyoyo** [comment]
Just re-did a test on flutter 0.10.3-pre.91 following [this post](https://github.com/dart-lang/sdk/issues/31954#issuecomment-435794571)

It seems performance has been damaged severely
```
On an MT8127, 32bit ARM chip, in an Archos 101c neon:
  AOT:
    [Uint64] A(17525) < B(43426), verify 3978709506094216976 vs 3978709506094216976
On a MSM8937, 64bit ARM chip, in a Redmi 3S:
  AOT:
    [Uint64] A(11172) < B(15624), verify 3978709506094216976 vs 3978709506094216976
```

Will investigate more ASAP

**Comment by mraleph** [comment]
@miyoyo could you please upload the full Dart source you are running to produce these numbers? 

I looked at the assembly produced for @aartbik's benchmark based on your code [this comment]( https://github.com/flutter/flutter/issues/19666#issuecomment-407485109) and while it looks quite bad (we should certainly apply strength reduction to multiplication!) - I don't necessarily see anything that regressed from older version.

**Comment by miyoyo** [comment]
@mraleph Here
[lib.zip](https://github.com/flutter/flutter/files/2557967/lib.zip)

```
[√] Flutter (Channel beta, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale en-BE)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.28.2)
[√] Connected device (1 available)

On an MT8127, 32bit ARM chip, in an Archos 101c neon:
  AOT:
    A(2847) < B(30288), verify 3978709506094216976 vs 3978709506094216976
  JIT:
    Cold:
      [Uint64] A(33232) < B(66076), verify 3978709506094216976 vs 3978709506094216976
    Hot:
      [Uint64] A(1463) < B(2761), verify 3978709506094216976 vs 3978709506094216976
On a MSM8937, 64bit ARM chip, in a Redmi 3S:
  AOT:
    A(1775) < B(9026), verify 3978709506094216976 vs 3978709506094216976
  JIT
    Cold:
      [Uint64] A(11182) < B(46736), verify 3978709506094216976 vs 3978709506094216976
    Hot:
      [Uint64] A(935) < B(2660), verify 3978709506094216976 vs 3978709506094216976
```

No idea why it would have done that, maybe it was a fluke in a specific flutter version?

**Comment by aartbik** [comment]
Results of the previous benchmark for ToT Dart, on a Intel Xeon(R) 2.60GHz, which is faster than previously reported, and it sounds like the arm regression is no longer there. Is there anything left to do for this bug?

> JIT:
> [Uint64] A(3045) <B(8694), verify 3978709506094216976 vs 3978709506094216976
> 
> AOT:
> [Uint64] A(151) <B(701), verify 3978709506094216976 vs 3978709506094216976
>

**Comment by mraleph** [comment]
We need to look at the ARM32 numbers again - which is where this benchmark performs the worst. 

I think yours and @mkustermann changes have given quite a big boost to the benchmark - so there might not be much to do short term, but I have not looked at the code.

**Comment by miyoyo** [comment]
Fresh batch from the latest dev (not master because of #26231 )
Amazing performance!
```
Flutter 1.1.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63b2daff7f (11 days ago) • 2018-12-28 10:43:06 -0800
Engine • revision f0a1d6f91d
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 d1817ddc91)

On an MT8127, 32bit ARM chip, in an Archos 101c neon:
  AOT:
    [Uint64] A(1791) < B(3979), verify 3978709506094216976 vs 3978709506094216976
  JIT:
    Cold:
      [Uint64] A(37794) < B(66763), verify 3978709506094216976 vs 3978709506094216976
    Hot:
      [Uint64] A(1092) < B(2196), verify 3978709506094216976 vs 3978709506094216976

On an MSM8937, 64bit ARM chip, in a Redmi 3S:
  AOT:
    [Uint64] A(834) < B(3225), verify 3978709506094216976 vs 3978709506094216976
  JIT:
    Cold:
      [Uint64] A(13370) < B(58143), verify 3978709506094216976 vs 3978709506094216976
    Hot:
      [Uint64] A(639) < B(1487), verify 3978709506094216976 vs 3978709506094216976
```

**Comment by aartbik** [comment]
Seems we have come a long way, and what is left is tracked by: dart-lang/sdk#31954
Closing this issue.
