### ISSUE TITLE
[!] VS Code (version 1.25.1) facing the same error after installing extension in VS Code

### ISSUE THREAD

**Issue by vishalbhaliya94** [flutter/flutter#19660]
Hello, Please help me to clear this error.

I am facing this error while running `flutter doctor`. it shows **[!] VS Code (version 1.25.1)** error.
then i add `flutter doctor -v` command, and now it shows error `[!] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
`

I have installed this extension. But still facing the same error

**Comment by dushyantss** [comment]
I am assuming that you are working on the beta channel. According to this [comment](https://github.com/flutter/flutter/issues/18717#issuecomment-399652325) :

> There was a change in VS Code recently that broke our detection of the extension. There's a fix for it in master [#18515](https://github.com/flutter/flutter/pull/18515) but it's not available in the beta channel yet.

So, you can safely ignore this warning.

**Comment by zoechi** [comment]
Tentatively closing as dup of #18515. Thanks @dushyantss 

@vishalbhaliya94 if you think this is a different issue please provide more information.
At least the full output of `flutter doctor -v`
