### ISSUE TITLE
Issue from website page Create a horizontal list

### ISSUE THREAD

**Issue by pulkit6299** [flutter/flutter#19673]
From URL: https://flutter.io/cookbook/lists/horizontal-list/ 
I wanted to know how can i add margins to each containers shown in this horizontal list example. I tried various things but neither of them worked for me. If I am adding padding then it is adding space inside the container not around it, exactly what padding should do. But the real problem here is that margin is also adding space inside the container and not around it.

Any help will be highly appreciated.

**Comment by zoechi** [comment]
I think this kind of question is better asked on StackOverflow
