### ISSUE TITLE
Feature request: Show user's location in google_maps_flutter

### ISSUE THREAD

**Issue by matejm** [flutter/flutter#19675]
I have successfully used unpublished package [google_maps_flutter](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter) and have implemented almost everything I wanted (custom map size, custom clickable markers...), but there is one important feature I miss: showing user's location.

This is already implemented [map_view package](https://pub.dartlang.org/packages/map_view), which is not maintained by flutter team, but they do not support inline maps (which I really need).

I would be very happy is you could add `showUserLocation` parameter to `options`, or something similar.

Currently, the best idea I have, is to add 'blue dot' marker to map, but this is far from ideal, because I want to show also direction of user and location precision.

**Comment by iskakaushik** [comment]
@matejm in `master` there is a `myLocationEnabled` for `GoogleMap` widget. Let me know if this solves your use case.

**Comment by matejm** [comment]
Yes, this is exactly what I wanted. Thanks!

**Comment by BwesShr** [comment]
I am getting
E/GoogleMapController(20024): Cannot enable MyLocation layer as location permissions are not granted
I have added <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> in manifest...
