### ISSUE TITLE
Camera Plugin Permissions

### ISSUE THREAD

**Issue by ricamgar** [flutter/flutter#19670]
Hi, 
since you can use the camera plugin just to take pictures (no video), I think the RECORD_AUDIO permission should be optional.

Thanks!

**Comment by lschmierer** [comment]
I've opened a Pull Request addressing this issue https://github.com/flutter/plugins/pull/904.

**Comment by lschmierer** [comment]
I would like to follow up on this issue.

As of today, we can pass `enableAudio: false` when initialising the camera controller to not ask for audio permissions.
However, audio permission is still in `AndroidManifest.xml` and thus still shown in app permissions in Android settings. A user of my app might wonder why that is the case if the app neither uses nor asks for audio permissions.

Might it be possible to remove the permissions (either only audio or both for consistency) from the plugins `AndroidManifest.xml` and ask the plugin user for adding them themselves to their apps `AndroidManifest.xml`?
For iOS manually adding them is necessary anyway.

**Comment by himamis** [comment]
To fix this manually, add this to the `android/app/src/main/Manifest.xml`
```
<manifest ... xmlns:tools="http://schemas.android.com/tools">
    ....
        <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
    ....
</manifest>
```

**Comment by CoderJava** [comment]
> To fix this manually, add this to the `android/app/src/main/Manifest.xml`
> 
> ```
> <manifest ... xmlns:tools="http://schemas.android.com/tools">
>     ....
>         <uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/>
>     ....
> </manifest>
> ```

Thanks. It's work.

**Comment by nicolaslucer0** [comment]
Hi, I'm trying this solution for android devices and it works ok.
But I still see the audio permission popup on iOS devices.
There is a solution I didn't see? Thanks in advance

**Comment by valconetti** [comment]
Hi,

Since the merge of [PR #837](https://github.com/flutter/plugins/pull/837) (version 0.5.2), you are able to enable or disable sound. Because of that, the permission request only happens if you enable the sound. I checked it on both Android and iOS and found that indeed the permission request doesn't happen when disabling sound, so this function works as expected.

Since the audio permission request is isn't mandatory anymore, this issue can be closed.

**Comment by ishannadeep** [comment]
<uses-permission android:name="android.permission.RECORD_AUDIO" tools:node="remove"/> this will not ask audio permission.only camera permissions.but my camera wont open.
