### ISSUE TITLE
Text widget has some visual glitches after changing its content dynamically 

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#19678]
## Steps to Reproduce

1. Create a new app on master channel (tested also on dev 0.5.6)
2. replace the build function with this:
```dart
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Text(
              'You have pushed the button this many times:',
            ),
            new Text(
              '1', // play with this text
              style: new TextStyle(
                fontFamily: 'Helvetica',
                fontSize: 180.0,
                color: Colors.black,
                fontWeight: FontWeight.w700,
                fontStyle: FontStyle.normal,
                decoration: TextDecoration.none,
              ),
            ),
          ],
        ),
      ),
    );
  }
```
3. start the app on a real ios device (I've used an iPhone 7 with iOS 11.1)
4. change the string on the line with "play with this text" comment to `'3'`
5. press hot reload
6. change the same string to `'2'`
7. notice a visual glitch below the number (see screenshot)

WITH GLITCH
![with_glitch](https://user-images.githubusercontent.com/729934/43089044-f9d38946-8ea3-11e8-8faa-9ed6c4bc4573.JPG)

WITHOUT GLITCH
![without_glitch](https://user-images.githubusercontent.com/729934/43089122-36831708-8ea4-11e8-9419-9ef4eef8f2ed.JPG)

The same glitch occurs when a Text widget is used in a dynamic way (e.g. to display a 3..2..1 countdown). It is barely noticeable with some setups, but it's very clear under other (e.g. using Nunito font). I didn't find a reliable way to work around this issue.

NUNITO GLITCH:
![nunito_glitch](https://user-images.githubusercontent.com/729934/43089912-373071f8-8ea6-11e8-940d-35b79b3b4aba.JPG)

## Doctor
```
[✓] Flutter (Channel master, v0.5.8-pre.110, on Mac OS X 10.13.4 17E199, locale it-IT)
    • Flutter version 0.5.8-pre.110 at /Users/sroddy_bs/flutter/flutter
    • Framework revision a7b59b51b8 (24 minutes ago), 2018-07-23 08:38:20 -0700
    • Engine revision 96f5f5b96c
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sroddy_bs/Library/Android/sdk
    • Android NDK at /Users/sroddy_bs/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 19.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Sroddy's iPhone • 4e1661d146c6e07b5835b1e5c3713ff67010a1e1 • ios • iOS 11.1
```

**Comment by sroddy** [comment]
@GaryQian were you able to reproduce it?

**Comment by GaryQian** [comment]
Yes, I have reproduced it. (specifically, on an iphone 6s, ios 11.4.1)

**Comment by GaryQian** [comment]
This may have to do with Skia font rendering. @chinmaygarde  suggested looking at SDF font rendering at large font sizes. I'll see what Skia says.

**Comment by sroddy** [comment]
@liyuqian @GaryQian I'm not 100% sure that this is related but now that we are (indirectly) relying much more on paths and shapes due to the fact that we have transitioned to use SVGs with `flutter_svg` we see a lot of random glitches inside our app, mostly in the form of a single horizontal line near the bottom edge of the shape.

I have some suspects these two things are somewhat related because:
1) They are both happening ONLY on real iOS devices.
2)They are both appearing with the same frequency (almost randomly on a fraction of the total draw events)
3) The visual artifacts are very similar (a single horizontal line near the bottom edge of the shape) with the color of the last drawn path.

![image from ios](https://user-images.githubusercontent.com/729934/46522976-98d2f300-c884-11e8-959b-040f6d9c4d45.jpg)
<img width="140" alt="schermata 2018-10-05 alle 09 52 50" src="https://user-images.githubusercontent.com/729934/46522986-a1c3c480-c884-11e8-87f0-772b36c72b0b.png">
<img width="123" alt="schermata 2018-10-05 alle 09 52 59" src="https://user-images.githubusercontent.com/729934/46522990-a4261e80-c884-11e8-91ae-72a441ff1a94.png">
<img width="248" alt="schermata 2018-10-05 alle 09 56 28" src="https://user-images.githubusercontent.com/729934/46523099-fe26e400-c884-11e8-9e8f-a34d3ff23903.png">

**Comment by liyuqian** [comment]
@csmartdalton86 @bsalomon : do you know if there's any iOS GPU bug that can cause this?

Note that:
1. This only happens on real iOS devices. Not on iOS simulators (which uses software backend), or Android simulators / devices (which uses GPU backend).
2. This only happens on subsequent frames (you have to first render a '3' and then a '2'). According to my knowledge, Flutter always clears the whole canvas in the beginning of each frame.

**Comment by GaryQian** [comment]
Also, the horizontal glitch line is tied to the character. For example, change it from "2" -> "3" -> "2" -> ".2" and the horizontal line will follow the 2 around even with the extra "."

**Comment by csmartdalton86** [comment]
If I had to guess, this looks to me like junk from a different mask in the atlas. Can we try a couple things?

1) contextOptions.fDisableCoverageCountingPaths = true;  // Does this make it go away?

2) contextOptions.fAllowPathMaskCaching = false;  // What about this?

**Comment by GaryQian** [comment]
We suspect that a recent Skia roll has fixed this render bug.

We are no longer able to reproduce it using the latest framework and engine (https://github.com/flutter/flutter/commit/bdc3dda5f298f50b432faaffe71730c4fe26afda)

Can anyone confirm this is fixed?

cc @liyuqian

**Comment by liyuqian** [comment]
I can no longer reproduce the bug either. @sroddy @deckerst : can you please try the Tip-of-Tree flutter to see if those issues are also fixed on your devices?

**Comment by sroddy** [comment]
Sure! I’ll try that tomorrow as first thing and let you know!

**Comment by deckerst** [comment]
The glitches disappeared, thank you!

**Comment by GaryQian** [comment]
It seems that this issue has been resolved. I will close this for now. If you are still experiencing this bug, please feel free to re-open this issue.
