### ISSUE TITLE
Feature request for "hasChild" for a Snapshot in Realtime Database

### ISSUE THREAD

**Issue by parasthekoder** [flutter/flutter#19672]
## Realtime Database
While listening to the `onChildAdded` listener, I'm unable to check if that reference has childs or not.

## Code
```dart
_surgeriesReference = widget.surgeriesReference.child('surgeries');
    _surgeriesSubscription = _surgeriesReference.onChildAdded.listen((Event event){
      DataSnapshot snapshot = event.snapshot;
      if(snapshot.value.toString().isEmpty){
         print('isEmpty : yes');
      }
      else{
        print('isEmpty : no');
      }
      },onError: (Object o){
       Error error = o;
       print('error occured');
       print(error.stackTrace);
      }
    );
```
## Output
```Nothing```

## Expected Output
```
isEmpty : yes // if there is no child
isEmpty : no // if there is atleast one child
```
## Feature Request Details

1. Getter for "hasChild".
2. Callback on "onDone" when the firebase has finished iterating all the childs.
3. Callback on "onError" if there is no child for a reference.

_Note : In Cloud FireStore, There is already a getter defined in DataSnapshot class named "hasChild" which lets you know if there is atleast one child or not._

**Comment by zoechi** [comment]
1. If you do not use `toString()` then you should be able to check for child values.

2. 3. Are there any references that these features are provided by the native Firebase Database API?

Flutter Firebase plugins are just wrappers over the native API and can't provide features the native API doesn't provide.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kroikie** [comment]
@parasthekoder

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/745. Any further collaboration will be done there.
