### ISSUE TITLE
CupertinoNavigationBar statusbar text color was changed by another tab page

### ISSUE THREAD

**Issue by hozhis** [flutter/flutter#19674]
My App is normal when it starts , the first tab page's statusbar text color is black,
<img width="391" alt="wx20180723-193508 2x" src="https://user-images.githubusercontent.com/12829578/43074425-d0782aaa-8eaf-11e8-9348-f5adfbc91d9d.png">
and then I click the third tab page which contains a SliverAppBar with a gradient background and a white statusbar text .
<img width="392" alt="wx20180723-194326 2x" src="https://user-images.githubusercontent.com/12829578/43074690-b6fa2ec4-8eb0-11e8-99da-df6f25a1e5c0.png">

When I go back to the first tab page again，the statusbar text color turns be white and I can't see it, 
<img width="413" alt="wx20180723-194722 2x" src="https://user-images.githubusercontent.com/12829578/43074845-3e249920-8eb1-11e8-9eba-556b2052cf92.png">

How to change its color to be black again?

**Comment by zoechi** [comment]
See https://github.com/flutter/flutter/issues/7347#issuecomment-326382698, #17523

**Comment by jonahwilliams** [comment]
@xster I'm not sure what is involved in the process.

**Comment by xster** [comment]
Send a PR to https://github.com/flutter/website/blob/master/_data/catalog/widgets.json

**Comment by hozhis** [comment]
thanks all
