### ISSUE TITLE
Describe gradle dependency version merging in add2app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#19688]
JD Finance ran into some pain points during their add2app process
https://mp.weixin.qq.com/s/S4FsLluCx1hOO8LKnrw7og.

Translation https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fmp.weixin.qq.com%2Fs%2FS4FsLluCx1hOO8LKnrw7og&edit-text=

When it's ready, we should make sure these topics are covered in https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps. 

[Support Library versioning](https://github.com/flutter/flutter/blob/b4d3808a15efe398396b30d68e499d8dce45acef/packages/flutter_tools/templates/module/android/Flutter.tmpl/build.gradle.tmpl#L47) compatibility might be hard to avoid, though it might be helpful to point it out up from the start. 

It also seems like we [dynamically determine the build tool version](https://github.com/flutter/flutter/blob/b4d3808a15efe398396b30d68e499d8dce45acef/packages/flutter_tools/lib/src/android/android_sdk.dart#L410) to use based on the target sdk version. Not too sure how much JD's existing gradle project's version deviates from it. May be useful to allow setting specific versions of build tools when invoking flutter tools if compatible. 

cc @KuoGao

**Comment by eseidelGoogle** [comment]
@mravn-google @matthew-carroll

**Comment by matthew-carroll** [comment]
@xster is there any time overlap where we can GVC about this?  I'd like to figure out what the exact action items should be to consider this issue handled.

**Comment by jmagman** [comment]
(Add-to-app triage meeting): @blasten any thoughts on this one? It could potentially just be a matter of documentation too if its a generic Android issue.

**Comment by blasten** [comment]
It looks like `com.android.support:support-v13:27.1.1` is conflicting with the host app dependency `com.android.support:support-v4:23.2.1`.

The root problem here is that the versioning scheme of the embedding doesn't follow the same scheme in Android.  For example, we can imagine that we include Android's major version in the version assigned to the embedding.  This way, the embedding version could become something like `23.0.0-<engine-hash>` or `27.0.0-<engine-hash>`. The rule of thumb is that `27.*.*` depends on `27.*.*` core libraries.

This isn't a trivial change though, so for now, maybe the solution is to document which versions the host app should use. Any thoughts?

**Comment by matthew-carroll** [comment]
@blasten I'm a bit confused, are you discussing the possibility of versioning the engine with references to the version of Android support libs that it depends upon?

**Comment by blasten** [comment]
@matthew-carroll After reading https://developers.google.com/android/guides/versioning, the suggestion seems like an anti-pattern.

It looks like we just need to document how to resolve potential conflicts based on https://developer.android.com/studio/build/dependencies#classpath_conflicts

**Comment by matthew-carroll** [comment]
Can we just list the current versions of the engine's dependencies somewhere? Maybe even pull it from the engine's POM? Because this is the standard issue of incompatible dependencies, right?

**Comment by blasten** [comment]
Right. I was trying to figure out what it would mean for us to update the major version of any of the embedding dependencies.

**Comment by xster** [comment]
We can merge this into our phase 1 project set-up doc https://github.com/flutter/flutter/issues/32862
