### ISSUE TITLE
Instructions for debugging Android engine with breakpoints

### ISSUE THREAD

**Issue by xster** [flutter/flutter#19689]
Standard debugging approaches with Xcode and breakpoint work ok for debugging iOS engine. Describe how it can be done in Android Studio with breakpoints for Android engine. 

@jason-simmons pointed out some instructions with GDB for now https://github.com/flutter/engine/blob/6bc4e7e9e452b2ca299e699e6bef64c0dada1e5e/sky/tools/flutter_gdb

**Comment by kangwang1988** [comment]
@xster
Now, I am able to debug the engine product in android(libflutter.so) using flutter_gdb.
Thanks.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2298](https://github.com/flutter/website/issues/2298) via [**ZenHub**](https://www.zenhub.com/)
