### ISSUE TITLE
Add negate operator to Velocity class

### ISSUE THREAD

**Issue by pylaligand** [flutter/flutter#1968]
https://github.com/flutter/flutter/commit/4fb47600e4c4b13c6d22e2b1d2d33fa363075392 introduced a Velocity class to replace uses of Offset as a velocity. It would be useful for Velocity to implement the negate operator as Offset does.

Let me know if you want me to take care of it.

**Comment by abarth** [comment]
Makes sense.  Happy to review a patch if you'd like to send one.
