### ISSUE TITLE
Some Flutter users have expressed they want Bazel support

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#19680]
Bazel (the build system) has gotten more attention and eyes on it this year.

For example:
* https://cloud.google.com/container-builder/docs/cloud-builders
* https://tulipemoutarde.be/posts/bazel-for-mobile-apps-part-2/
* https://github.com/dart-lang/rules_dart/issues/182

It might be worth tracking, longer-term, OS support for Flutter+Bazel.

**Comment by ananthb** [comment]
Would this be implemented in java say in the bazel repository or as a plugin somehow? I'm just picking up bazel biut I'd love to help if its needed anywhere.

**Comment by tautomaton** [comment]
Have a look at the way Dart does it: https://github.com/dart-lang/rules_dart. The model Bazel seems to pursue is that only the core engine is in the actual Bazel repository. The rules targeting specific languages are written in Starlark (https://github.com/bazelbuild/starlark).

**Comment by jhahn21** [comment]
Is there any ongoing effort on this? We really want to use bazel for a consistent dev environment.
For example, it's not easy to keep syncing flutter versions across all dev environments.

**Comment by feliwir** [comment]
Want to use Bazel aswell.

**Comment by perezd** [comment]
I would love this!

**Comment by jonahwilliams** [comment]
We have no plans to support Bazel directly in Flutter. However, we would like the flutter tool to be usable from any build system, including Bazel. This currently only possible through modifying the flutter_tool source, but longer-term a minimal flutter_tools API that could be wrapped via a Bazel build rule or other system.

See also: https://github.com/flutter/flutter/issues/25377

**Comment by perezd** [comment]
OK, but this bug still seems relevant regardless of the API...theres build rules to develop and publish, right?

**Comment by jonahwilliams** [comment]
We have no plans to develop BUILD rules for Dart/Flutter

**Comment by prestonvanloon** [comment]
Some users are still interested and I'm a bit surprised this would not be considered as the bazel team aims to be a world class build tool. 

Is this the end of the road for Bazel consideration?

**Comment by jonahwilliams** [comment]
We'd love to give users of Bazel a way to plug the flutter build system into a rule. We have no way to support bazel through the flutter tool or provide anything out of the box though. There is no support for Dart in bazel rules, and we don't have a mechanism to infer or generate rules from pubspec files. 

Native code is similar, if a package does not already have BUILD rules then there is nothing we can do.

**Comment by zoechi** [comment]
@perezd the package is abandoned, this is why it is in `dart-archive` instead of `dart-lang`.
Seems the approach wasn't viable.

**Comment by rohansingh** [comment]
Apparently there are Flutter targets in the Fuschia SDK:

https://fuchsia.googlesource.com/scripts/+/master/sdk/bazel/#dart-flutter
https://fuchsia.googlesource.com/scripts/+/master/sdk/bazel/base/dart/build_defs/flutter_app.bzl

**Comment by pcj** [comment]
Despite dart-lang/rules-dart being archived, the source actually still works pretty well and there are a few forks that people are maintaining. I'm still planning to maintaining proto support going for dart/bazel, hopefully for flutter eventually.

**Comment by perezd** [comment]
Last I recall, I thought the flutter team was planning to expose compiler primitives that would enable the community to maintain bazel rules for flutter. Has ant progress been made here?

**Comment by zachgrayio** [comment]
We would definitely love to see this at Flare and are happy to contribute as well but it seems like a good starting point might be with anything Google can share

**Comment by cbracken** [comment]
@zachgrayio If you're interested in contributing, cbracken/rules_dart has working VM/web build rules that are maintained on a mostly ad-hoc, whenever-I-get-time-for-it basis but they might make a decent starting point. I authored most of the original Dart rules internally at Google and had a hand in doing the same for our internal Flutter rules. 

I think the biggest difficulty is that you'd want to build a wrapper around the internals of flutter_tools, but flutter_tools doesn't have a stable public API, and I suspect probably won't have anytime soon. In any case, if you're interested in building something, those might be a good starting point. I can't promise quick turnaround time on questions or reviews, but I'm very familiar with Bazel and if you'd like advice or have questions, please feel free to cc e on a PR.

I've added some minimal notes here https://github.com/cbracken/rules_dart/issues/30
