### ISSUE TITLE
I have a conflict between the TabBarView and Gridview!!

### ISSUE THREAD

**Issue by Abosrie** [flutter/flutter#19692]
**Hello,**
I'm new to Flutter and I'm trying to create a simple page of a Top navigation bar and gridview for some products.

The issue is - When I view the gridview alone it's working fine. But once I call the gridview into the main page the gridview disappear. 

There is no error coming in the code so I'm not able to figure out what is the issue.

**main.dart**

```dart
  TabController controller;

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    controller = new TabController(vsync: this, length: 3);
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("NASY"),
        backgroundColor: Colors.cyan[400],
        
        bottom: new TabBar(
          controller: controller,
          tabs: <Widget>[
            new Tab(
              icon: new Icon(Icons.home),
            ),
            new Tab(
              icon: new Icon(Icons.location_on),
            ),
            new Tab(
              icon: new Icon(Icons.event_note),
            )
          ],
        ),
      ),

      body: new TabBarView(controller: controller, children: <Widget>[
        new first.HomePage(),
        new second.EventPage(),
        new third.PlacesPage(),
      ]),
    
    );
  }
}
```

**home_page.dart**

```dart

// Product Listing

  List<Container> daftarSuperhero = new List();

  var karakter = [
    {"nama": "Ipnone 5", "gambar": "iphone1.jpg"},
    {"nama": "Iphone 5s", "gambar": "iphone2.jpg"},
    {"nama": "Iphone 7", "gambar": "iphone3.jpg"},
    {"nama": "Iphone 8", "gambar": "iphone4.jpg"},
    {"nama": "Iphone X", "gambar": "iphone5.png"},
    {"nama": "Ipnone 5", "gambar": "iphone1.jpg"},
    {"nama": "Iphone 5s", "gambar": "iphone2.jpg"},
    {"nama": "Iphone 7", "gambar": "iphone3.jpg"},
    {"nama": "Iphone 8", "gambar": "iphone4.jpg"},
    {"nama": "Iphone X", "gambar": "iphone5.png"},
  ];

  _buatlist() async {
    for (var i = 0; i < karakter.length; i++) {
      final karakternya = karakter[i];
      final String gambar = karakternya["gambar"];

      daftarSuperhero.add(new Container(
          padding: new EdgeInsets.all(10.0),
          child: new Card(
              child: new Column(
            children: <Widget>[
              new Padding(
                padding: EdgeInsets.all(10.0),
              ),
              new Image.asset(
                "assets/products/$gambar",
                fit: BoxFit.cover,
                height: 100.0,
              ),
              new Text(
                karakternya['nama'],
                style: new TextStyle(fontSize: 20.0),
              )
            ],
          ))));
    }
  }

  @override
  void initState() {
    super.initState();
    _buatlist();
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return new Scaffold(
      body: new Column(
        children: <Widget>[
          new Expanded(
            child: new Container(
              child: new Stack(
                children: <Widget>[carousel, banner],
              ),
            ),
            flex: 1,
          ),
          new Expanded(
            child: new GridView.count(
              primary: true,
              crossAxisCount: 2,
              children: daftarSuperhero,
            ),
            flex: 1,
          )
        ],
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Can you please try to reduce the code to a minimal reproduction?
Also please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Thanks. Can you also please create a self-contained minimal reproduction?
The code above seems to contain unrelated code and references to files that are not provided.

**Comment by Abosrie** [comment]
Okay, I will try to do that. But also I have shared the project here
https://bitbucket.org/CVITUAE/flutterproject2/downloads/

**Comment by zoechi** [comment]
Your project shows
![image](https://user-images.githubusercontent.com/405837/43133006-b9a9d204-8f3d-11e8-8a89-774fa608589f.png)

is that not what you want?

**Comment by Abosrie** [comment]
Yes :)
Does the tab controller work in the case? As I can show this result once I remove the tabView.

**Comment by Abosrie** [comment]
Ohh - That is weird. 
Actually, I'm using IphoneX Simulator and it's showing a white screen in the lower section of the screen [Where the gridview should come]. Any Idea on how I can solve this?

**Comment by zoechi** [comment]
Nope, don't know and it's difficult to investigate without being able to reproduce.
Perhaps someone else, but might take a while. 
Can you try with an Android emulator?
The white screen is probably a different issue.

**Comment by Abosrie** [comment]
No issue - Thanks anyway :)
I will try to test on android emulator.

**Comment by Abosrie** [comment]
I tried Android Emulator and I'm still getting the same result!

![screen shot 2018-07-24 at 6 42 20 pm](https://user-images.githubusercontent.com/34103922/43154815-ee99ce6e-8f75-11e8-8b3b-ff92e3501872.png)

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
