### ISSUE TITLE
Colors should not be in Material

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1970]
It would be nice to use Colors without having to pull in Material.dart.

**Comment by Hixie** [comment]
They're the Material colours. ☺

What is the concern with importing the material library?

**Comment by jimbeveridge** [comment]
You've said "don't mix Material and non-Material controls". If I don't include material.dart, then I won't accidentally use a Material control.

**Comment by Hixie** [comment]
But if you don't want to use material, why do you want the material colour palette?

You can always import them using `import 'package:flutter/src/material/color.dart';`.

**Comment by abarth** [comment]
Or `import 'package:flutter/material.dart' show Colors`

Event better, you can create your own library that exports `Colors` from material.dart and just import that library.

**Comment by Hixie** [comment]
@jimbeveridge Do those solutions seem reasonable?

**Comment by jimbeveridge** [comment]
Your "show colors" suggestion will work for me, thanks.
