### ISSUE TITLE
How do I prohibit font size from changing with the font size of the mobile phone?

### ISSUE THREAD

**Issue by hozhis** [flutter/flutter#19707]
Can I set a maximum and minimum font interval to prevent page elements from being confused?

![simulator screen shot - iphone x - 2018-07-24 at 16 43 52](https://user-images.githubusercontent.com/12829578/43127391-f44c7528-8f61-11e8-8d4a-2cb3f107811f.png)
![simulator screen shot - iphone x - 2018-07-24 at 16 44 46](https://user-images.githubusercontent.com/12829578/43127392-f48300ac-8f61-11e8-881d-a3b588516adb.png)
![simulator screen shot - iphone x - 2018-07-24 at 16 44 56](https://user-images.githubusercontent.com/12829578/43127393-f4b8cbd8-8f61-11e8-829a-404b722733d6.png)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
You could wrap your app with a custom `MediaQuery` where you override the default  https://docs.flutter.io/flutter/widgets/MediaQueryData/textScaleFactor.html

See also 
- https://docs.flutter.io/flutter/dart-ui/Window/textScaleFactor.html
- https://docs.flutter.io/flutter/dart-ui/Window/onTextScaleFactorChanged.html

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by kenho85** [comment]
MaterialApp(
      builder: (BuildContext context, Widget child) {
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(textScaleFactor: textScaleFactor),
          child: child,
        );
      },
      title: 'Home Page',
    );

This should do the trick~

**Comment by psygo** [comment]
Isn't making `textScaleFactor: 1.0` much easier than using `MediaQuery` stuff?

For example, the following will prohibit scaling based on system's accessibility settings:

```dart
Text(
  'hello',
  textScaleFactor: 1.0,
),
```

**Comment by bhanuka96** [comment]
> Isn't making `textScaleFactor: 1.0` much easier than using `MediaQuery` stuff?
> 
> For example, the following will prohibit scaling based on system's accessibility settings:
> 
> ```dart
> Text(
>   'hello',
>   textScaleFactor: 1.0,
> ),
> ```

No, I think you should use `MediaQuery` Because of your method doesn't change textField label sizes and etc
