### ISSUE TITLE
flutter packages get command not working

### ISSUE THREAD

**Issue by GOVINDDIXIT** [flutter/flutter#19712]
I want to create new flutter app using flutter console. so I run the command flutter create <app_name>
The command run successfully created the files required for the app but when it run flutter packages get
it is not working 
I am working with a proxy server with a username and password

**Comment by zoechi** [comment]
> it is not working

is not very helpful.

Please post the full error output 
and the output of `flutter doctor -v`.

How did you configure the proxy?
Did you check https://www.dartlang.org/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall ?

**Comment by GOVINDDIXIT** [comment]
C:\Users\govin>set https_proxy=lit2017018:work@fast@172.31.1.4:8080
C:\Users\govin>flutter create walli
Creating project walli...
Wrote 2 files.

Running "flutter packages get" in walli...

it is runnring from last 5 min

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
The issue is probably caused by `set https_proxy=lit2017018:work@fast@172.31.1.4:8080`.
I think this needs to be reported in https://github.com/dart-lang/pub/issues instead.

**Comment by GOVINDDIXIT** [comment]
I solved this by creating environment variables to deal with proxies
variable name = http_proxy
value = http://username:password@address:port
variable = NO_PROXY
value = 127.0.0.1,localhost.

**Comment by yathit** [comment]
I also have very similar issue in Windows 10. flutter is fresh git repo clone.

```
C:\Users\k\xwork\dartsugar>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

C:\Users\k\xwork\dartsugar>flutter doctor -v
[√] Flutter (Channel beta, v0.10.2, on Windows, locale en-SG)
    • Flutter version 0.10.2 at C:\Users\kyawtun\flutter
    • Framework revision d8cbb80206 (2 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\k\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4892.25

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\k\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

C:\Users\k\xwork\dartsugar>flutter upgrade
Upgrading Flutter from C:\Users\kyawtun\flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.10.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d8cbb80206 (2 weeks ago) • 2018-10-26 01:30:21 -0400
Engine • revision 6c2ade9fa2
Tools • Dart 2.1.0-dev.8.0.flutter-bf26f760b1

Running "flutter packages upgrade" in dartsugar...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 1 in 1 second...
Git error. Command: git fetch
pub upgrade failed (69) -- attempting retry 2 in 2 seconds...
```

**Comment by zoechi** [comment]
Sounds like an issue with permissions in the Flutter install directory.
Try deleting the folder and start over with a new Flutter install.
If that's not it it might be because you are behind a proxy and you need to configure proxy settings.

**Comment by GOVINDDIXIT** [comment]
Hey @yathit pls confirm are you working behind a proxy server?

**Comment by yathit** [comment]
@GOVINDDIXIT No proxy. In fact, it is working a week ago.

@zoechi  deleted the folder. fresh clone. switch to beta channel. still the same problem. mac and linux work fine.

**Comment by filipepratalima** [comment]
Im currently having the exact same issue on a fresh clone of flutter 1.0 on a mac.
Im not behind any firewalls or proxies.

After doing "flutter create mysampleproject" I get:

Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 3 in 4 seconds...

**Comment by rahul-bavaliya** [comment]
> Im currently having the exact same issue on a fresh clone of flutter 1.0 on a mac.
> Im not behind any firewalls or proxies.
> 
> After doing "flutter create mysampleproject" I get:
> 
> Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
> pub get failed (69) -- attempting retry 3 in 4 seconds...

I also get same issue in Windows behind the corporate PROXY.
We need solid solution for this...!!!
