### ISSUE TITLE
[website - infra] the Ruby Sass gem is deprecated, use an alternative

### ISSUE THREAD

**Issue by chalin** [flutter/flutter#19715]
From [this Travis log](https://travis-ci.org/flutter/website/builds/407652791):

> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
> * For more details, please refer to the Sass blog:

cc @Sfshaza @filiph

**Comment by filiph** [comment]
Oooh, using Dart Sass would be great.

**Comment by chalin** [comment]
This issue was moved to flutter/website#1175
