### ISSUE TITLE
TextInputType dateTime resets the pointer location to the start of the string

### ISSUE THREAD

**Issue by Shantanu-Kotambkar** [flutter/flutter#19714]
The dateTime Keyboard, puts the pointer to the start of the string on the TextField, every time you validate your string.  I have been using a textField, along with dateTime Keyboard, and when I type something, the dateTime keyboard pointer toggles to the start of the Typed string. its annoying as it has to be put back to the end of the string every time you want to edit the String.

**Comment by Shantanu-Kotambkar** [comment]
This occurs with the android platform :
`W/IInputConnectionWrapper(25185): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(25185): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(25185): getTextAfterCursor on inactive InputConnection`

For iOS: It displays the cursor at the start of the string, but the interaction isn't messed up. If I press a backspace key, it will delete the character at the end of the String. The same is not true with android. No warnings on the console for iOS.

**Comment by Shantanu-Kotambkar** [comment]
`https://github.com/flutter/flutter/issues/11416 .` The problem is mentioned here. And I was able to get the workaround, So closing issue.

**Comment by zoechi** [comment]
dup of #11416 as mentioned by @Shantanu-Kotambkar
