### ISSUE TITLE
Unable to deploy flutter apps to BlueStacks emulator using hardware rendering

### ISSUE THREAD

**Issue by SAFAD** [flutter/flutter#19711]
## Steps to Reproduce

1. Create a Hello World application using flutter (the default template should do fine).
2. Issue 'flutter run' on the console of your IDE (my case it is VSCode but the IDE is irrelevant to this issue).
3. Wait for the App to build and deploy to BlueStacks (3N version).
4. App crashes on start.

## Logs
`flutter run -v`
https://gist.github.com/SAFAD/b419ac59b140bc56875ccf5d730d4227

```
flutter analyze
Analyzing testApp...
No issues found! (ran in 6.9s)
```
```
flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale en-US)
    • Flutter version 0.5.1 at C:\Users\SAFAD\AppData\Local\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\SAFAD\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
[!] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • ONEPLUS A5000 • emulator-5554 • android-x86 • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.
```
##Workaround:
when adding the following argument to flutter run command, the application runs without issues 
`--enable-software-rendering`
However not being able to use hardware rendering in an application that heavily manipulates graphics is an issue.

**Comment by SAFAD** [comment]
@zoechi Indeed, the app runs after adding the argument, but what about hardware rendering support?

**Comment by zoechi** [comment]
I'm not sure, but as far as I remember, hardware rendering in the emulator is not supported.
The problem seems to be that the BlueStacks emulator is not recognized as emulator.
@chinmaygarde  might know more.

**Comment by SAFAD** [comment]
See the logs from `flutter doctor` you can see that it detects the emulator as an android device ONEPLUS A5000.

![image](https://user-images.githubusercontent.com/489520/43139255-8ab8ce0a-8f51-11e8-80e5-b24c78507f73.png)

however if I use the android emulator provided with Android Studio I do not face this issue, it probably is specific to Bluestacks and how it handles rendering.

**Comment by chinmaygarde** [comment]
Unfortunately, different emulators have varying degrees of support for hardware rendering (that is almost always tied to the host platform and GPU). The way the various emulators report the type of emulation in use has been extremely unreliable (if present at all) as well. The software rendering flag was a safe if not optimally performant way of getting a workable emulator.

In this particular case, the application is trying to choose an RGBA 8888 ES 2 config and failing. This is about as plain vanilla of a configuration as it gets. Is the emulator able to run any other OpenGL ES application? Can you dump the results of `adb shell dumpsys SurfaceFlinger` for the emulator?

**Comment by lucassgomes** [comment]
Hello buddy, did you ever change BlueStacks engine settings for hardware rendering?

**Comment by msndvlpr** [comment]
`flutter run lib\main.dart --enable-software-rendering` works fine for me

**Comment by darshankawar** [comment]
@SAFAD Revisiting this issue, is there a way for you to reverify this issue with latest stable version to check if the behavior still persists or not ?
