### ISSUE TITLE
How to preserve the scroll position of tabView when using collapsible app bar (sliverAppBar)?

### ISSUE THREAD

**Issue by HengJunXi** [flutter/flutter#19720]
### Problem:

Scroll position of the tabView **is not** restored correctly when one of the tabView is scrolled to the top (revealing the sliverAppBar). The other tabView will also scrolled to the top (losing its previous scroll position).

* This problem **will not** show up if normal app bar is used (**not** collapsible app bar)
* This problem **only** shows up when the tabView is scrolled to top

### Question:

How to preserve the scroll position of the tabView when using collapsible app bar (sliverAppBar)?

###  Code:

```dart
    import 'package:flutter/material.dart';

    void main() {
      runApp(new MyApp());
    }

    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return new MaterialApp(
          home: new MyHomePage(),
        );
      }
    }

    class MyHomePage extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return new DefaultTabController(
          length: 2,
          child: Scaffold(
            body: NestedScrollView(
              headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                return <Widget>[
                  SliverAppBar(
                    title: Text('Example'),
                    pinned: true,
                    floating: true,
                    forceElevated: innerBoxIsScrolled,
                    bottom: TabBar(
                      tabs: <Widget>[
                        Tab(text: 'One',),
                        Tab(text: 'Two'),
                      ],
                    ),
                  ),
                ];
              },
              body: TabBarView(
                children: <Widget>[
                  Center(
                    key: PageStorageKey<String>('one'),
                    child: ListView.builder(
                      itemBuilder: (BuildContext context, int index) {
                        return new ListTile(
                          title: new Text('One Item $index'),
                        );
                      },
                    ),
                  ),
                  Center(
                    key: PageStorageKey<String>('two'),
                    child: ListView.builder(
                      itemBuilder: (BuildContext context, int index) {
                        return new ListTile(
                          title: new Text('Two Item $index'),
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          )
        );
      }
    }
```

StackOverflow: https://stackoverflow.com/questions/51466964/how-to-preserve-the-scroll-position-of-tabview-when-using-collapsible-app-bar-s

**Comment by zoechi** [comment]
I think you need to pass the `PageStorageKey` to `ListView.builder()`

**Comment by zoechi** [comment]
Does https://github.com/flutter/flutter/issues/27928#issuecomment-463662840 help?

**Comment by zoechi** [comment]
Please check https://github.com/flutter/flutter/issues/27928#issuecomment-464998788

**Comment by mehmetf** [comment]
@zoechi An internal user is also running into this. The problem happens when you use the sample code in https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html verbatim so our docs need to be updated if there's a workaround.

**Comment by najeira** [comment]
@zoechi Which widget of the comment is important? I tried and could not solve this.

How do I change this issue's first code?

**Comment by najeira** [comment]
I copied the whole code and executed https://github.com/flutter/flutter/issues/27928#issuecomment-464998788 , it does not work.

**Comment by najeira** [comment]
I misunderstood, it seems to work. I will find out which widget affects the behavior.

**Comment by najeira** [comment]
This issue's first code works.

**Comment by escamoteur** [comment]
double of https://github.com/flutter/flutter/issues/40740
