### ISSUE TITLE
[website - infra] Fix page descriptions

### ISSUE THREAD

**Issue by chalin** [flutter/flutter#19723]
The meta properties `description` and `og:description` use `page.description` or the initial text from the page. In some cases, the latter isn't very pretty; e.g. from `_site/web-analogs/index.html`:

> \<meta name="description" content="Contents:* TOC Placeholder{:toc}This page is for users who are familiar with the HTML and CSS syntax forarranging components of an application's UI. It maps HTML/CSS code snippets totheir Flutter/Dart code equivalents.The examples assume:* The HTML document starts with a modern HTML DOCTYPE, and the CSS box model for all HTML...">

Maybe all pages should be required to have a description attribute in the Jekyll front matter, or the description could be dropped otherwise.

cc @Sfshaza @filiph

**Comment by Sfshaza** [comment]
Yes, we should add that and be consistent. The lawless days of chaos will soon be over.  ;)

**Comment by chalin** [comment]
This issue was moved to flutter/website#1176
