### ISSUE TITLE
Scroll position issue with animated list

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#19738]
I have an animated list inside a stateful widget. 
The problem is every-time I do a setState on the parent, the list scroll over to the top.

Check the gist 
https://gist.github.com/manujbahl/c53e3bc9c263b9aeb5a1cf8444d12beb

Scroll the list and then click the Press Me button. The list scroll offset resets to top.

**Comment by HengJunXi** [comment]
Just remove the key from the AnimatedList in the build() method of AnimatedListSample

**Comment by manujbahl** [comment]
Can't remove that.
In the actual production code I am using that to to do inserts and removes to the list

**Comment by HengJunXi** [comment]
Try to use different key for the ListModel and AnimatedList?

**Comment by zoechi** [comment]
Having a `GlobalKey` per instance doesn't make sense.
If you change it to 
```dart
static final GlobalKey<AnimatedListState> _listKey =
      new GlobalKey<AnimatedListState>();
```
this fixes your scrolling issue and this way GlobalKey makes more sense, but there are better ways to communicate between components, like Redux or ScopedModel (not tried the later myself)

**Comment by manujbahl** [comment]
What if the list class is reused in multiple screens. I guess I can keep a map of keys associated to each view.

How do you propose to use redux for this?

**Comment by zoechi** [comment]
If you need multiple instances of the list at the same time, then you should have multiple global keys. 
Create an unique global keys for each place where you use it.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
