### ISSUE TITLE
SearchDelegate should respect the theme more

### ISSUE THREAD

**Issue by DFreds** [flutter/flutter#19734]
Currently, the search bar contained in SearchDelegate uses the following code to set the colors of the app:

```dart
  ThemeData appBarTheme(BuildContext context) {
    assert(context != null);
    final ThemeData theme = Theme.of(context);
    assert(theme != null);
    return theme.copyWith(
      primaryColor: Colors.white,
      primaryIconTheme: theme.primaryIconTheme.copyWith(color: Colors.grey),
      primaryColorBrightness: Brightness.light,
      primaryTextTheme: theme.textTheme,
    );
  }
```

This requires a specific override of `appBarTheme` for each SearchDelegate or else it looks horrible for dark themes (even the default `ThemeData.dark()`). Frankly, I don't see why it needs to explicitly specify Colors.white or Colors.grey. It should inherit something from the currently applied theme just like the regular app bar.

I attached two images (light and dark) to prove my point.

![screenshot_1532475976](https://user-images.githubusercontent.com/11878569/43171897-6fc3151e-8f7a-11e8-8fed-ef27cdb39c87.png)
![screenshot_1532475953](https://user-images.githubusercontent.com/11878569/43171898-6fd13ea0-8f7a-11e8-98be-8e09e6227f4a.png)

**Comment by DFreds** [comment]
The style of the search text field in the _SearchPageState needs to be updated as well. 

The code I'm referring to is on line 420 of search.dart.

```dart
        title: new TextField(
          controller: queryTextController,
          focusNode: widget.delegate._focusNode,
          style: theme.textTheme.title,
          onSubmitted: (String _) {
            widget.delegate.showResults(context);
          },
          decoration: new InputDecoration(
            border: InputBorder.none,
            hintText: MaterialLocalizations.of(context).searchFieldLabel,
          ),
        ),
```

I have the following code to override the app bar style.

```dart
 @override
 ThemeData appBarTheme(BuildContext context) {
   final ThemeData theme = Theme.of(context);
   return theme.copyWith(
     primaryColor: theme.primaryColor,
     primaryIconTheme: theme.primaryIconTheme,
     primaryColorBrightness: theme.primaryColorBrightness,
     primaryTextTheme: theme.primaryTextTheme,
   );
 }
```

Which makes it look like this

<img width="384" alt="screen shot 2018-07-24 at 7 58 31 pm" src="https://user-images.githubusercontent.com/11878569/43172187-12b624cc-8f7c-11e8-97ac-03e57865bc55.png">

I'm able to update the text field with this code in my overridden method:

`textTheme: theme.textTheme.copyWith(title: theme.textTheme.title.copyWith(color: theme.primaryTextTheme.title.color))`

Which makes it look like this

<img width="392" alt="screen shot 2018-07-24 at 8 00 25 pm" src="https://user-images.githubusercontent.com/11878569/43172207-3b2d4d86-8f7c-11e8-9541-293f495d5efb.png">

However, the 'Search' hint text is still grey as shown

<img width="383" alt="screen shot 2018-07-24 at 8 00 55 pm" src="https://user-images.githubusercontent.com/11878569/43172222-4e3ad7f4-8f7c-11e8-97f0-1730505adc83.png">

I'm unsure how to fix that part.

**Comment by goderbauer** [comment]
@DFreds I do understand the problem you describe in your second post. We need to provide a way to customize the hint text.

However, I don't understand your issue in the fist post. Overriding `appBarTheme` is the hook to customize the colors used in the app bar of the search screen. What are you missing from there?

**Comment by DFreds** [comment]
It isn't so much an issue as it is unexpected behavior of the search widget. I'm struggling to understand why it would default to Colors.white and Colors.grey for the primary color and primary icon theme instead of inheriting something from the theme like (almost all?) other widgets with color. I think having the override for the theme of it is great for unique customization, but I assumed that it would match the rest of my application by default when I added it.

My example pointed out dark mode. As it stands, I have to do basically zero work if I want a dark mode in my app. Obviously I can customize it, but widgets such as cards, text, icons, etc. all change to match the dark theme. The search widget does not.

Does that clear it up?

**Comment by goderbauer** [comment]
That makes sense. Thanks for the clarification.

**Comment by arieslee** [comment]
> The style of the search text field in the _SearchPageState needs to be updated as well.
> 
> The code I'm referring to is on line 420 of search.dart.
> 
> ```dart
>         title: new TextField(
>           controller: queryTextController,
>           focusNode: widget.delegate._focusNode,
>           style: theme.textTheme.title,
>           onSubmitted: (String _) {
>             widget.delegate.showResults(context);
>           },
>           decoration: new InputDecoration(
>             border: InputBorder.none,
>             hintText: MaterialLocalizations.of(context).searchFieldLabel,
>           ),
>         ),
> ```
> 
> I have the following code to override the app bar style.
> 
> ```dart
>  @override
>  ThemeData appBarTheme(BuildContext context) {
>    final ThemeData theme = Theme.of(context);
>    return theme.copyWith(
>      primaryColor: theme.primaryColor,
>      primaryIconTheme: theme.primaryIconTheme,
>      primaryColorBrightness: theme.primaryColorBrightness,
>      primaryTextTheme: theme.primaryTextTheme,
>    );
>  }
> ```
> 
> Which makes it look like this
> 
> <img alt="screen shot 2018-07-24 at 7 58 31 pm" width="384" src="https://user-images.githubusercontent.com/11878569/43172187-12b624cc-8f7c-11e8-97ac-03e57865bc55.png">
> 
> I'm able to update the text field with this code in my overridden method:
> 
> `textTheme: theme.textTheme.copyWith(title: theme.textTheme.title.copyWith(color: theme.primaryTextTheme.title.color))`
> 
> Which makes it look like this
> 
> <img alt="screen shot 2018-07-24 at 8 00 25 pm" width="392" src="https://user-images.githubusercontent.com/11878569/43172207-3b2d4d86-8f7c-11e8-9541-293f495d5efb.png">
> 
> However, the 'Search' hint text is still grey as shown
> 
> <img alt="screen shot 2018-07-24 at 8 00 55 pm" width="383" src="https://user-images.githubusercontent.com/11878569/43172222-4e3ad7f4-8f7c-11e8-97f0-1730505adc83.png">
> 
> I'm unsure how to fix that part.

I have the same problem. Have you solved it?

**Comment by DFreds** [comment]
I did not solve it. I ended up using the default styling for now

**Comment by maxgmer** [comment]
Same issue, we need a way to customize hint color

**Comment by guojiex** [comment]
I try to change the search.dart at 433 line by adding the hintstyle:

```
title: TextField(
            controller: queryTextController,
            focusNode: widget.delegate._focusNode,
            style: theme.textTheme.title,
            textInputAction: TextInputAction.search,
            onSubmitted: (String _) {
              widget.delegate.showResults(context);
            },
            decoration: InputDecoration(
              border: InputBorder.none,
              hintText: searchFieldLabel,
              hintStyle: theme.inputDecorationTheme.hintStyle,
            ),
          ),
```
Then I override the appBarTheme function (adding inputDecorationTheme):

```
@override
  ThemeData appBarTheme(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    return theme.copyWith(
        inputDecorationTheme: InputDecorationTheme(
            hintStyle: TextStyle(color: theme.primaryTextTheme.title.color)),
        primaryColor: theme.primaryColor,
        primaryIconTheme: theme.primaryIconTheme,
        primaryColorBrightness: theme.primaryColorBrightness,
        primaryTextTheme: theme.primaryTextTheme,
        textTheme: theme.textTheme.copyWith(
            title: theme.textTheme.title
                .copyWith(color: theme.primaryTextTheme.title.color)));
  }
```

And it looks like:
![screenshot from 2019-01-17 14-54-55](https://user-images.githubusercontent.com/5022480/51345024-f7a12e80-1a67-11e9-9c3d-5733a8382b3b.png)

Is this help?

**Comment by hyperpanthera** [comment]
Please merge @guojiex changes to stable.

**Comment by furkanvatandas** [comment]
Same problem, Is there any development?

**Comment by guojiex** [comment]
There is another way to fix this, change the line 433 in search.dart, by adding a theme wrapper for the text_field:

```dart
title: Theme(
            data: theme,
            child: TextField(
              controller: queryTextController,
              focusNode: widget.delegate._focusNode,
              style: theme.textTheme.title,
              textInputAction: TextInputAction.search,
              onSubmitted: (String _) {
                widget.delegate.showResults(context);
              },
              decoration: InputDecoration(
                border: InputBorder.none,
                hintText: searchFieldLabel,
              ),
            ),
          ),
```

**Comment by kw2019ltd** [comment]
when fix for hint color?

**Comment by justinmc** [comment]
Closing this as https://github.com/flutter/flutter/pull/30388 was just merged and built successfully.

SearchDelegate will now respect the `appBarTheme`'s `hintStyle`.  Make sure you're on the master [Flutter channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels), or using a version > 1.7.3 once it's released.

I still think that a more comprehensive solution to this theme problem would be nice, as discussed above, but this fixes the problem for now.

**Comment by mciekurs2** [comment]
As of temporary fix for dark theme I changed line 398 in search.dart
from `final ThemeData theme = widget.delegate.appBarTheme(context);`
to `final ThemeData theme = ThemeData.dark();`.

**Comment by patelkrunal78** [comment]
Maybe a bit late... but you can use this:

ThemeData(
    primaryTextTheme: Typography(platform: TargetPlatform.iOS).white,
    textTheme: Typography(platform: TargetPlatform.iOS).white,
)

https://icetutor.com/question/how-to-change-the-entire-themes-text-color-in-flutter

**Comment by chitgoks** [comment]
The suggestions here work. except for the cursor color. is there a workaround for this?

**Comment by justinmc** [comment]
@chitgoks I don't see a way to set the cursor color in SearchDelegate.  Can you open a separate issue for that?  It would be a pretty straightforward PR if anyone is interested in opening one.

**Comment by zubisofts** [comment]
You can override these methods in the SearchDelegate to customize the search widget.

**Comment by zubisofts** [comment]
You can override the below methods in your search delegate to customize your search widget.

`class SearchWidget extends SearchDelegate<Movie> {

@override
  String get searchFieldLabel => "Search Movie";

  @override
  ThemeData appBarTheme(BuildContext context) {
    return Theme.of(context);
  }`

**Comment by aminikhil** [comment]
> The style of the search text field in the _SearchPageState needs to be updated as well.
> 
> The code I'm referring to is on line 420 of search.dart.
> 
> ```dart
>         title: new TextField(
>           controller: queryTextController,
>           focusNode: widget.delegate._focusNode,
>           style: theme.textTheme.title,
>           onSubmitted: (String _) {
>             widget.delegate.showResults(context);
>           },
>           decoration: new InputDecoration(
>             border: InputBorder.none,
>             hintText: MaterialLocalizations.of(context).searchFieldLabel,
>           ),
>         ),
> ```
> 
> I have the following code to override the app bar style.
> 
> ```dart
>  @override
>  ThemeData appBarTheme(BuildContext context) {
>    final ThemeData theme = Theme.of(context);
>    return theme.copyWith(
>      primaryColor: theme.primaryColor,
>      primaryIconTheme: theme.primaryIconTheme,
>      primaryColorBrightness: theme.primaryColorBrightness,
>      primaryTextTheme: theme.primaryTextTheme,
>    );
>  }
> ```
> 
> Which makes it look like this
> 
> <img alt="screen shot 2018-07-24 at 7 58 31 pm" width="384" src="https://user-images.githubusercontent.com/11878569/43172187-12b624cc-8f7c-11e8-97ac-03e57865bc55.png">
> 
> I'm able to update the text field with this code in my overridden method:
> 
> `textTheme: theme.textTheme.copyWith(title: theme.textTheme.title.copyWith(color: theme.primaryTextTheme.title.color))`
> 
> Which makes it look like this
> 
> <img alt="screen shot 2018-07-24 at 8 00 25 pm" width="392" src="https://user-images.githubusercontent.com/11878569/43172207-3b2d4d86-8f7c-11e8-9541-293f495d5efb.png">
> 
> However, the 'Search' hint text is still grey as shown
> 
> <img alt="screen shot 2018-07-24 at 8 00 55 pm" width="383" src="https://user-images.githubusercontent.com/11878569/43172222-4e3ad7f4-8f7c-11e8-97f0-1730505adc83.png">
> 
> I'm unsure how to fix that part.

You can simply add this in theme.copyWith()

inputDecorationTheme: theme.inputDecorationTheme.copyWith(
        hintStyle: theme.textTheme.title.copyWith(
          color: Colors.white70,
          fontWeight: FontWeight.w400,
        ),
      ),

**Comment by king-11** [comment]
> > The style of the search text field in the _SearchPageState needs to be updated as well.
> > The code I'm referring to is on line 420 of search.dart.
> > ```dart
> >         title: new TextField(
> >           controller: queryTextController,
> >           focusNode: widget.delegate._focusNode,
> >           style: theme.textTheme.title,
> >           onSubmitted: (String _) {
> >             widget.delegate.showResults(context);
> >           },
> >           decoration: new InputDecoration(
> >             border: InputBorder.none,
> >             hintText: MaterialLocalizations.of(context).searchFieldLabel,
> >           ),
> >         ),
> > ```
> > 
> > 
> > I have the following code to override the app bar style.
> > ```dart
> >  @override
> >  ThemeData appBarTheme(BuildContext context) {
> >    final ThemeData theme = Theme.of(context);
> >    return theme.copyWith(
> >      primaryColor: theme.primaryColor,
> >      primaryIconTheme: theme.primaryIconTheme,
> >      primaryColorBrightness: theme.primaryColorBrightness,
> >      primaryTextTheme: theme.primaryTextTheme,
> >    );
> >  }
> > ```
> > 
> > 
> > Which makes it look like this
> > <img alt="screen shot 2018-07-24 at 7 58 31 pm" width="384" src="https://user-images.githubusercontent.com/11878569/43172187-12b624cc-8f7c-11e8-97ac-03e57865bc55.png">
> > I'm able to update the text field with this code in my overridden method:
> > `textTheme: theme.textTheme.copyWith(title: theme.textTheme.title.copyWith(color: theme.primaryTextTheme.title.color))`
> > Which makes it look like this
> > <img alt="screen shot 2018-07-24 at 8 00 25 pm" width="392" src="https://user-images.githubusercontent.com/11878569/43172207-3b2d4d86-8f7c-11e8-9541-293f495d5efb.png">
> > However, the 'Search' hint text is still grey as shown
> > <img alt="screen shot 2018-07-24 at 8 00 55 pm" width="383" src="https://user-images.githubusercontent.com/11878569/43172222-4e3ad7f4-8f7c-11e8-97f0-1730505adc83.png">
> > I'm unsure how to fix that part.
> 
> You can simply add this in theme.copyWith()
> 
> inputDecorationTheme: theme.inputDecorationTheme.copyWith(
> hintStyle: theme.textTheme.title.copyWith(
> color: Colors.white70,
> fontWeight: FontWeight.w400,
> ),
> ),

title has been deprecated using subtitle1 is a better alternate.

**Comment by charleshan** [comment]
It looks like we can't override inputDecoration as shown in the source code:
```
    // material/search.dart
    ...
    return Semantics(
      explicitChildNodes: true,
      scopesRoute: true,
      namesRoute: true,
      label: routeName,
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: theme.primaryColor,
          iconTheme: theme.primaryIconTheme,
          textTheme: theme.primaryTextTheme,
          brightness: theme.primaryColorBrightness,
          leading: widget.delegate.buildLeading(context),
          title: TextField(
            controller: widget.delegate._queryTextController,
            focusNode: focusNode,
            style: theme.textTheme.headline6,
            textInputAction: widget.delegate.textInputAction,
            keyboardType: widget.delegate.keyboardType,
            onSubmitted: (String _) {
              widget.delegate.showResults(context);
            },
            decoration: InputDecoration(
              border: InputBorder.none,
              hintText: searchFieldLabel,
              hintStyle: searchFieldStyle,
            ),
          ),
          actions: widget.delegate.buildActions(context),
        ),
        body: AnimatedSwitcher(
          duration: const Duration(milliseconds: 300),
          child: body,
        ),
      ),
    );
    ...
```
Potential fix: https://github.com/flutter/flutter/pull/55209

**Comment by mehmetf** [comment]
This issue is quite old at this point and is too generic IMO. I am refocusing it to be primarily about InputDecoration theme which remains an issue also raised by several internal teams. Marking as p3 for now.

**Comment by GuvanchBayryyyev** [comment]
I have found the solution !!!

1. Remove building Widget
`@override
  Widget buildLeading(BuildContext context) {
    // TODO: implement buildLeading
    return Container(
      height: 0,
    );
  }`

2. You need to override buildActions to put custom Input

`@override
  List<Widget> buildActions(BuildContext context) {
    // TODO: implement buildActions
    return [
      Expanded(
        flex: 1,
        child: Align(
            alignment: Alignment.center,
            child: IconButton(
                icon: Icon(
                  Icons.arrow_back_ios_outlined,
                  color: Colors.black,
                  size: 20,
                ),
                onPressed: () {
                  close(context, null);
                })),
      ),
      Expanded(
          flex: 7,
          child: Container(
            height: 50,
            child: GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: () {
                  showSearch(context: context, delegate: DataSearch());
                },
                child: Align(
                    alignment: Alignment.centerLeft,
                    child: Padding(
                      padding: EdgeInsets.only(left: 4),
                      child: TextFormField(
                        decoration: InputDecoration(
                          labelStyle: TextStyle(
                              color: Color.fromRGBO(168, 168, 168, 1),
                              fontFamily: 'Kanit'),
                          hintStyle: TextStyle(color: Colors.red),
                          filled: true,
                          fillColor: Colors.white,
                          border: new OutlineInputBorder(
                              borderRadius: BorderRadius.circular(20.0),
                              borderSide: new BorderSide(
                                color: Color.fromRGBO(224, 224, 224, 1),
                              )),
                          errorBorder: InputBorder.none,
                          enabledBorder: InputBorder.none,
                          focusedBorder: InputBorder.none,
                          contentPadding:
                              EdgeInsets.symmetric(vertical: 0, horizontal: 16),
                        ),
                      ),
                    ))),
          )),
      Expanded(
          flex: 2,
          child: Center(
              child: IconButton(
                  icon: Icon(
                    Icons.close_rounded,
                    size: 20,
                    color: Colors.black,
                  ),
                  onPressed: () {
                    query = '';
                  }))),
    ];
  }`
This solved issue, Good Luck!
