### ISSUE TITLE
Allow to pass a primary scroll controller to Scaffold

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#19732]
Mulligan reached out to me to ask about overriding the primary scroll controller that scaffold uses to scroll iOS views to the top when the user taps the status bar.  They want to add custom behavior to the scroll controller that also does this.

From the documentation, it looks like the [PrimaryScrollController](https://docs.flutter.io/flutter/widgets/PrimaryScrollController-class.html) widget is supposed to be able to do this, but it does not.  The Scaffold currently creates a scrollController that can't be overridden: https://github.com/flutter/flutter/blob/810a29d6635169e65a948716a57b6c15a3a1673f/packages/flutter/lib/src/material/scaffold.dart#L1314-L1324

Ideally, we'd do one of the following:
   - pass an alternative primaryScrollController into the Scaffold when we create it, 
   - override the ScaffoldState's primaryScrollController by creating a PrimaryScrollController widget
   - Enable scroll controllers to subscribe to the Scaffold and scroll themselves to the top of the view during the statusBar tap

**Comment by lukepighetti** [comment]
I need a scroll controller that can be programmatically animated to the bottom, spring on extents on iOS, and be able to do a normal tap to the top. Does this issue aim to solve this problem? And if not, what's my best way to go about getting this handled?

**Comment by arieslee** [comment]
I have the same problem.

**Comment by azeek** [comment]
A guide on not to use nested scaffolds. There is no way to use the Persistent
 bottom navigation bar with other nested navigator with other app bars.

**Comment by lonelyteapot** [comment]
This is still needed

**Comment by kamami** [comment]
Any news?

**Comment by Piinks** [comment]
This can be closed since the PrimaryScrollController was moved outside of the Scaffold, it is now at the top of the route, and can be overridden by introducing a PrimaryScrollController anywhere in a subtree.
