### ISSUE TITLE
Flutter - FireBase Authentication Please help ! 

### ISSUE THREAD

**Issue by Kumuda123** [flutter/flutter#19747]
<img width="1175" alt="screen shot 2018-07-25 at 1 28 24 am" src="https://user-images.githubusercontent.com/35873647/43183347-6d36482c-8faa-11e8-82c9-cfe7994d5b37.png">
<img width="1178" alt="screen shot 2018-07-25 at 1 28 17 am" src="https://user-images.githubusercontent.com/35873647/43183349-6d472340-8faa-11e8-89c3-31ca78c32ebb.png">
<img width="1169" alt="screen shot 2018-07-25 at 1 28 10 am" src="https://user-images.githubusercontent.com/35873647/43183350-6d55ef92-8faa-11e8-9dc3-1b14a7571ecf.png">
<img width="1187" alt="screen shot 2018-07-25 at 1 27 59 am" src="https://user-images.githubusercontent.com/35873647/43183351-6d646dba-8faa-11e8-9e60-983cb2c24468.png">
<img width="1184" alt="screen shot 2018-07-25 at 1 27 52 am" src="https://user-images.githubusercontent.com/35873647/43183352-6d71ca00-8faa-11e8-8b2f-ca65b4458315.png">
This is the error I get when I run my code. 

<img width="928" alt="screen shot 2018-07-25 at 1 29 00 am" src="https://user-images.githubusercontent.com/35873647/43183378-875c13bc-8faa-11e8-921c-16622ed99d05.png">
<img width="461" alt="screen shot 2018-07-25 at 1 28 55 am" src="https://user-images.githubusercontent.com/35873647/43183379-876e013a-8faa-11e8-95f1-db6c731b983d.png">
<img width="1213" alt="screen shot 2018-07-25 at 1 28 49 am" src="https://user-images.githubusercontent.com/35873647/43183380-877cbfa4-8faa-11e8-9ae7-69a5ab0738d1.png">
<img width="1065" alt="screen shot 2018-07-25 at 1 28 41 am" src="https://user-images.githubusercontent.com/35873647/43183381-878abc80-8faa-11e8-82d2-c8df6c980312.png">

My code ^^ 

The youtube link I am following - https://www.youtube.com/watch?v=aaKef60iuy8&t=1s

Does anyone know how to resolve this issue ? 
Thanks

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please check if executing `pod update` in the `ios/` directory helps.

**Comment by Kumuda123** [comment]
<img width="700" alt="screen shot 2018-07-25 at 1 41 17 am" src="https://user-images.githubusercontent.com/35873647/43183763-e2082a7a-8fab-11e8-9355-8521998636ec.png">

**Comment by Kumuda123** [comment]
How do i check the pod update ?

**Comment by zoechi** [comment]
Just execute it and try running the app again.
Executing `flutter clean` might also be worth a try to get a clean build without remains from previous builds.

**Comment by zoechi** [comment]
Please prefer posting code or log outputs as text instead of screenshots if there is no specific reason to use a screenshot.

**Comment by Kumuda123** [comment]
[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`. 

This came with a bunch of other stuff after i ran pods update. Should i worry about this ?

**Comment by zoechi** [comment]
Don't think there is a reason to worry about this message. Don't know about the "bunch of other stuff though" ;-)
Did it change anything?

**Comment by Kumuda123** [comment]
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
5.4.1 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.4.1 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.1 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
	[1.1 3498F78A-4769-4C17-AEEA-F1C737DBB11F 10.22.25.241.59020<->172.217.12.42:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.151s, DNS @0.006s took 0.010s, TCP @0.021s took 0.005s, TLS took 0.091s
	bytes in/out: 3466/1062, packets in/out: 9/10, rtt: 0.004s, retransmitted packets: 0, out-of-order packets: 0
Syncing files to device iPhone X...
)
	[2.1 78E79426-0456-4D74-95B4-834F56DD802A 10.22.25.241.59037<->172.217.12.42:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.177s, DNS @0.009s took 0.016s, TCP @0.029s took 0.017s, TLS took 0.045s
	bytes in/out: 3558/1007, packets in/out: 9/10, rtt: 0.014s, retransmitted packets: 0, out-of-order packets: 2
flutter: Error

I this get after I have entered the email and password in the form and presses the login button.

**Comment by kroikie** [comment]
@Kumuda123

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/743. Any further collaboration will be done there.
