### ISSUE TITLE
How can I handle FirebaseAuthUserCollisionException?

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#19748]
I'm writing application using Firebase.
I want to show dialog when user enter the duplicated email in signup form.
There are many exception so I want to catch FirebaseAuthUserCollisionException.
But, I can't find anywhere, how can I use it?

**Comment by zoechi** [comment]
I think this is a dup of #17677

**Comment by baeharam** [comment]
@zoechi I don't understand why it is dup, my issue is that I cannot access to FirebaseAuthUserCollisionException class.

**Comment by zoechi** [comment]
Because this exception does not exist in Dart, only in Java and #17677 is about propagating native exceptions though the platform channel to Dart so that it can be caught there.

**Comment by baeharam** [comment]
@zoechi Then, if I want to use that exception, do I have to code native into dart?

**Comment by zoechi** [comment]
You would have to modify the firebase_auth (I guess) plugin to send a message to Dart in case of a native exception and when you receive such a message throw a matching exception in Dart.
You can also create a Pull Request with a fix for the existing plugin.
  
#17677 is about a generic mechanism or at least a common patter how to pass exceptions along.

**Comment by kroikie** [comment]
@baeharam

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/742. Any further collaboration will be done there.
