### ISSUE TITLE
DatePicker widget is with bug when displayed on small mobile phone screens

### ISSUE THREAD

**Issue by rafaelcb21** [flutter/flutter#19744]
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)
```

The `DatePicker` widget is with bug when displayed on small mobile phone screens.

(LG K130) mobile phone screen is  is height: 521 and width: 320

Below is the evidence and the code used

![screenshot_2018-07-25-02-10-29](https://user-images.githubusercontent.com/9912894/43180959-4a7d6bce-8fb1-11e8-8cd1-21c9cac4db7b.png)

![screenshot_2018-07-25-02-10-44](https://user-images.githubusercontent.com/9912894/43180967-52a87762-8fb1-11e8-9fa1-0301230690f1.png)

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  DateTime _fromDateTime = new DateTime.now();

  Future<Null> _selectDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
      context: context,
      initialDate: _fromDateTime,
      firstDate: new DateTime(2018),
      lastDate: new DateTime(2020)
    );

    if(picked != null && picked != _fromDateTime) {
      setState(() {
        _fromDateTime = picked;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final ui.Size logicalSize = MediaQuery.of(context).size;
    final double _width = logicalSize.width;
    final double _height = logicalSize.height;

    // [height: , 521.3333333333334,   _width: , 320.0]
    print(['height: ', _height, '  _width: ', _width]);
    
    return new Scaffold(
      appBar: new AppBar(),
      body: new InkWell(
        onTap: () {
          _selectDate(context);
        },
        child: new Container(
          padding: EdgeInsets.only(top: 12.0, bottom: 12.0, left: 16.0, right: 16.0),
          decoration: new BoxDecoration(
            borderRadius: new BorderRadius.all(new Radius.circular(4.0)),
            border: new Border.all(
              color: Colors.black45,
              width: 1.0,
            ),
          ),
          child: new Text('${_fromDateTime.toString()}'),
        ),
      )
    );
  }
}
```

```
I/flutter ( 3470): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 3470): The following message was thrown during layout:
I/flutter ( 3470): A RenderFlex overflowed by 40 pixels on the bottom.
I/flutter ( 3470): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter ( 3470): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 3470): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 3470): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 3470): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 3470): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 3470): seen. If the content is legitimately bigger than the available space, consider clippingit with a
I/flutter ( 3470): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 3470): like a ListView.
I/flutter ( 3470): The specific RenderFlex in question is:
I/flutter ( 3470):   RenderFlex#ecf38 relayoutBoundary=up7 OVERFLOWING
I/flutter ( 3470):   creator: Column ← SizedBox ← LayoutBuilder ← OrientationBuilder ← DefaultTextStyle ←
I/flutter ( 3470):   AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#7e953 ink renderer] ←
I/flutter ( 3470):   NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← PhysicalShape
I/flutter ( 3470):   ← _MaterialInterior ← ⋯
I/flutter ( 3470):   parentData: <none> (can use size)
I/flutter ( 3470):   constraints: BoxConstraints(w=240.0, 0.0<=h<=448.0)
I/flutter ( 3470):   size: Size(240.0, 448.0)
I/flutter ( 3470):   direction: vertical
I/flutter ( 3470):   mainAxisAlignment: start
I/flutter ( 3470):   mainAxisSize: min
I/flutter ( 3470):   crossAxisAlignment: stretch
I/flutter ( 3470):   verticalDirection: down
I/flutter ( 3470): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter ( 3470): ════════════════════════════════════════════════════════════════════════════════════════════════════
`
``

**Comment by zoechi** [comment]
I think this is a dup of #19202.

**Comment by HansMuller** [comment]
I've reopened this because it includes a simple test case demonstrates a specific problem.

**Comment by rafaelcb21** [comment]
Just to register, I changed the `date_picker.dart` file for my project to continue and I'm waiting for the official fix.

The changes I made were:

I inserted the line `Navigator.pop(context, _selectedDate);` in the two functions below
```dart
void _handleYearChanged(DateTime value) {
    _vibrate();
    setState(() {
      _mode = DatePickerMode.day;
      _selectedDate = value;
      Navigator.pop(context, _selectedDate); //new
    });
  }

  void _handleDayChanged(DateTime value) {
    _vibrate();
    setState(() {
      _selectedDate = value;
      Navigator.pop(context, _selectedDate); //new
    });
  }
```

I commented on lines 995 and 1017 in which you insert the `action`
```dart
          switch (orientation) {
            case Orientation.portrait:
              return new SizedBox(
                width: _kMonthPickerPortraitWidth,
                child: new Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                    header,
                    new Container(
                     color: theme.dialogBackgroundColor,
                     child: new Column(
                       mainAxisSize: MainAxisSize.min,
                       crossAxisAlignment: CrossAxisAlignment.stretch,
                       children: <Widget>[
                         picker,
                         //actions,
                       ],
                     ),
                    ),
                  ],
                ),
              );
            case Orientation.landscape:
              return new SizedBox(
                height: _kDatePickerLandscapeHeight,
                child: new Row(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: <Widget>[
                    header,
                    new Flexible(
                      child: new Container(
                        width: _kMonthPickerLandscapeWidth,
                        color: theme.dialogBackgroundColor,
                        child: new Column(
                          mainAxisSize: MainAxisSize.min,
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: <Widget>[picker] //, actions],
                        ),
                      ),
                    ),
                  ],
                ),
              );
          }
```

In my humble vision do not need the buttons `CANCEL` and `OK`, the user only wants to choose a date, choose and finished the action. These two buttons only make sense if you choose a range of dates, for example from day 1 to day 7, similar to when you make a hotel reservation

**Comment by aqwert** [comment]
I don't see any recommendation within the Material.io site around Date and Time Pickers, however on the Android site it looks like there is a different way to render these dialogs: (https://developer.android.com/guide/topics/ui/controls/pickers)

I also have (https://play.google.com/store/apps/details?id=com.eajy.materialdesigndemo) on a device and it does change to a smaller version when the real estate is too small.

One has to remember that it is possible to use split screens so either it needs to change to a compact view (as in the android example) or use scrolling (which is not ideal)

**Comment by zoechi** [comment]
#21383 shows quite a similar error on a bigger screen.

**Comment by bennybat50** [comment]
Go the showDatePicker class date_picker.dart , search for **_kDatePickerHeaderPortraitHeight** and change its value to 90.0 also   **_kDatePickerHeaderPortraitHeight**  change its value to 45.0 that show do the trick.

**Comment by bennybat50** [comment]
right click on showDatePicker and got to date_picker.dart  class, Search for  **_kDatePickerHeaderPortraitHeight** and change its value to 90.0 also **_kDialogActionBarHeight** and change its value to 45.0. that should do the trick

**Comment by clemkofi** [comment]
Yes, you have to modify the "date_picker.dart" file but to avoid missing buttons and all the "Side Effects" of using the "SingleChildScrollView" ; you can create new const variables for smaller screens and use conditional statements to select them if those conditions (i.e conditions of a "smaller screen" is met) like so

creating the variables at that the start of the class
```dart
// smaller screens parameters (screens with height smaller than 521)
const double _kDatePickerHeaderPortraitHeight_small = 80.0;
const double _kDialogActionBarHeight_small = 45.0;
const double _kDatePickerLandscapeHeight_small = _kMaxDayPickerHeight + _kDialogActionBarHeight_small;
```
then get the screen dimensions for the device at the start of the _DatePickerHeader widget 
```dart
 Widget build(BuildContext context) {
    // get screen dimensions of the phone 
    final ui.Size logicalSize = MediaQuery.of(context).size;
    final double screenWidth = logicalSize.width;
    final double screenHeight = logicalSize.height;

```
now use the device height to set the height in potrait and landscape modes
```dart
switch (orientation) {
      case Orientation.portrait:
        height = screenHeight < 525 ? _kDatePickerHeaderPortraitHeight_small : _kDatePickerHeaderPortraitHeight; //new
        padding = const EdgeInsets.symmetric(horizontal: 16.0);
        mainAxisAlignment = MainAxisAlignment.center;
        break;
      case Orientation.landscape:
        width = screenHeight < 525 ? _kDatePickerLandscapeHeight_small : _kDatePickerHeaderLandscapeWidth; //new
        padding = const EdgeInsets.all(8.0);
        mainAxisAlignment = MainAxisAlignment.start;
        break;
    }
```
This solves the problem for smaller screens. :wink:

**Comment by bhammer88** [comment]
modifying the local copy doesn't seem to effect it. How do you change it?

**Comment by bhammer88** [comment]
I hope this gets fixed soon, since i need it for my app that is already in production.

**Comment by jerinho** [comment]
> Just to register, I changed the `date_picker.dart` file for my project to continue and I'm waiting for the official fix.
> 
> The changes I made were:
> 
> I inserted the line `Navigator.pop(context, _selectedDate);` in the two functions below
> 
> ```dart
> void _handleYearChanged(DateTime value) {
>     _vibrate();
>     setState(() {
>       _mode = DatePickerMode.day;
>       _selectedDate = value;
>       Navigator.pop(context, _selectedDate); //new
>     });
>   }
> 
>   void _handleDayChanged(DateTime value) {
>     _vibrate();
>     setState(() {
>       _selectedDate = value;
>       Navigator.pop(context, _selectedDate); //new
>     });
>   }
> ```
> 
> I commented on lines 995 and 1017 in which you insert the `action`
> 
> ```dart
>           switch (orientation) {
>             case Orientation.portrait:
>               return new SizedBox(
>                 width: _kMonthPickerPortraitWidth,
>                 child: new Column(
>                   mainAxisSize: MainAxisSize.min,
>                   crossAxisAlignment: CrossAxisAlignment.stretch,
>                   children: <Widget>[
>                     header,
>                     new Container(
>                      color: theme.dialogBackgroundColor,
>                      child: new Column(
>                        mainAxisSize: MainAxisSize.min,
>                        crossAxisAlignment: CrossAxisAlignment.stretch,
>                        children: <Widget>[
>                          picker,
>                          //actions,
>                        ],
>                      ),
>                     ),
>                   ],
>                 ),
>               );
>             case Orientation.landscape:
>               return new SizedBox(
>                 height: _kDatePickerLandscapeHeight,
>                 child: new Row(
>                   mainAxisSize: MainAxisSize.min,
>                   crossAxisAlignment: CrossAxisAlignment.stretch,
>                   children: <Widget>[
>                     header,
>                     new Flexible(
>                       child: new Container(
>                         width: _kMonthPickerLandscapeWidth,
>                         color: theme.dialogBackgroundColor,
>                         child: new Column(
>                           mainAxisSize: MainAxisSize.min,
>                           crossAxisAlignment: CrossAxisAlignment.stretch,
>                           children: <Widget>[picker] //, actions],
>                         ),
>                       ),
>                     ),
>                   ],
>                 ),
>               );
>           }
> ```
> 
> In my humble vision do not need the buttons `CANCEL` and `OK`, the user only wants to choose a date, choose and finished the action. These two buttons only make sense if you choose a range of dates, for example from day 1 to day 7, similar to when you make a hotel reservation
> 
> And if the developer inserts an banner AdMob in bottom, on a small screen of a mobile device the `CANCEL` and `OK` buttons will not be hidden behind banner AdMob

Date picker without button to confirm the selection is the worst idea I ever heard of. I think it's the best thing to overcome the overflow issue rather than dismiss the calendar and return the value on date number clicked

**Comment by bhammer88** [comment]
Any idea when we can see this going live? Its been a while.

**Comment by darrenaustin** [comment]
Closed with #31514

**Comment by VNAPNIC** [comment]
try this

```dart
DateTime dateTime = await showDatePicker(
        context: context,
        initialDate: DateTime(2000),
        firstDate: DateTime(1950),
        lastDate: DateTime(DateTime.now().year + 1),
        builder: (context, child) {
          return SingleChildScrollView(
            child: Theme(
              child: child,
              data: ThemeData.light(),
            ),
          );
        });
```

**Comment by fremfi** [comment]
^ that works, any way to achieve that without having to change the theme?

**Comment by flutterapptesting** [comment]
We are using showDatePicker in flutter. It works fine in the iOS emulator and Android emulator, but it gives an error 'RangeError : value not in range :20' on iPhone. Any help will be appreciable.
Here's the code:
Future<Null> _selectDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
        context: context,
        initialDate: selectedDate,
        firstDate: DateTime(2019, 1),
        lastDate: DateTime(2101));

    if (picked != null)
      setState(() {
        selectedDate = picked;
        _dateController =
            new TextEditingController(text: picked.toString().substring(0, 10));
        actualDateTime = Timestamp.fromDate(picked); //To TimeStamp
        actualDate = picked.toString().substring(0, 10).trim();
      });
  }

**Comment by FilipeAG** [comment]
my datepicker is só small in bigger screens how i resolve this?
code
![image](https://user-images.githubusercontent.com/55716432/82669521-fb236780-9c11-11ea-8829-7ddd9f125deb.png)
in emulator
![image](https://user-images.githubusercontent.com/55716432/82669579-14c4af00-9c12-11ea-8898-db03b8e658cb.png)

**Comment by fluttercorner** [comment]
[How To Use Date Picker in Flutter](https://fluttercorner.com/how-to-use-date-picker-in-flutter/)
