### ISSUE TITLE
firebase_auth: Getting DisplayName after creating account with email returns 'null'

### ISSUE THREAD

**Issue by jmen900** [flutter/flutter#19746]
I came across a bug which returns `null` for `displayName` and `photoUrl` after creating a new account with `email` and `password`. This happens until the user signs out and signs back in. Or the app restarts. `Uid`, `email`, and `token` all seem to work fine. I have not yet tested Google Sign in or Facebook Sign in.

The error reproduces even after making sure to wait for `updateProfile()` to finish updating the `displayName` and `photoUrl`.

Right now my workaround is to logout and log back in, right after creating the new account.

**Comment by kenwen** [comment]
Just experienced this myself but I was using phone auth, haven't had a chance to test with Google sign in. The photoUrl and displayName properties of the auth object don't appear to return a value on iOS, however on Android it works as expected. Signing out and signing back in on iOS appears to fix the problem.

**Comment by zoechi** [comment]
@jmen900 are you also only seeing this on iOS?

**Comment by jmen900** [comment]
I actually only tested on Android and was seeing this problem. I closed this project a couple months ago. I'll see if I can get the project running again just to retest on iOS.

**Comment by Iungad** [comment]
// get signed in user
    FirebaseUser firebaseUser = await _auth.currentUser();
    // reload it
    await firebaseUser?.reload();
// get user again
      firebaseUser = await _auth.currentUser();

**Comment by kroikie** [comment]
@jmen900

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/744. Any further collaboration will be done there.
