### ISSUE TITLE
Change keyboard Action Button

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#19740]
https://stackoverflow.com/q/50107284/6509751
I was not able to find out much more about this. On StackOverflow the consensus was that there is no implementation. This is supported natively in iOS and Android, which is why I feel the "need" to have this supported in Flutter natively.

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/flutter/issues/17525. This has already been implemented on the master branch.
