### ISSUE TITLE
I code a slide, but sometimes it will throw a NoSuchMethodError, why?

### ISSUE THREAD

**Issue by hozhis** [flutter/flutter#19755]
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
Receiver: null
Tried calling: inheritFromWidgetOfExactType(_TabControllerScope)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      DefaultTabController.of (package:flutter/src/material/tab_controller.dart:280:47)
#2      _SlidePageSelectorState._handleArrowButtonPress (package:jixiaoshi/layout/home.dart:232:59)
#3      _SlidePageSelectorState.initState.<anonymous closure> (package:jixiaoshi/layout/home.dart:227:7)
#4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
Receiver: null
Tried calling: inheritFromWidgetOfExactType(_TabControllerScope)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      DefaultTabController.of (package:flutter/src/material/tab_controller.dart:280:47)
#2      _SlidePageSelectorState._handleArrowButtonPress (package:jixiaoshi/layout/home.dart:232:59)
#3      _SlidePageSelectorState.initState.<anonymous closure> (package:jixiaoshi/layout/home.dart:227:7)
#4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.

**Comment by hozhis** [comment]
`class SlidePage {
  SlidePage({@required this.image, this.routeName, this.params})
      : assert(image != null);

  final String image;

  final String routeName;

  final Map params;
}

class _SlidePageSelector extends StatefulWidget {
  const _SlidePageSelector({this.pages});

  final List<SlidePage> pages;

  @override
  _SlidePageSelectorState createState() => _SlidePageSelectorState();
}

class _SlidePageSelectorState extends State<_SlidePageSelector> {
  final GlobalKey<_SlidePageSelectorState> selectorKey =
      GlobalKey<_SlidePageSelectorState>();

  @override
  void initState() {
    super.initState();

    /// 启动轮播图定时器
    Timer.periodic(Duration(milliseconds: 3800), (timer) {
      _autoSlide(selectorKey.currentContext, 1);
    });
  }

  void _autoSlide(BuildContext context, int delta) {
    final TabController controller = DefaultTabController.of(context);
    final List<SlidePage> pages = widget.pages;

    if (!controller.indexIsChanging) {
      if (controller.index >= pages.length - 1 && delta > 0) {
        controller.animateTo(
          (controller.index - pages.length + 1).clamp(0, pages.length - 1),
        );
      } else if (controller.index <= 0 && delta < 0) {
        controller.animateTo(
          (controller.index + pages.length - 1).clamp(0, pages.length - 1),
        );
      } else {
        controller.animateTo(
          (controller.index + delta).clamp(0, pages.length - 1),
        );
      }
    }
  }

  void _handleDragUpdateGesture(DragUpdateDetails details) {}

  @override
  Widget build(BuildContext context) {
    final List<SlidePage> pages = widget.pages;
    final TabController controller = DefaultTabController.of(context);
    return SafeArea(
      key: selectorKey,
      top: false,
      bottom: false,
      child: Column(
        children: <Widget>[
          Expanded(
            child: Stack(
              children: <Widget>[
                GestureDetector(
                  onHorizontalDragUpdate: _handleDragUpdateGesture,
                  onTap: () {
//                    Navigator.pushNamed(context, '/login');
                  },
                  child: TabBarView(
                    children: pages.map(
                      (SlidePage page) {
                        return Container(
                          child: Card(
                            elevation: 0.0,
                            margin: EdgeInsets.zero,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(0.0),
                            ),
                            child: Image.network(
                              page.image,
                              fit: BoxFit.cover,
                              alignment: Alignment.topCenter,
                            ),
                          ),

                          /// end of Card
                        );
                      },
                    ).toList(),
                  ),
                ),

                /// end of GestureDetector

                Positioned(
                  bottom: 5.0,
                  left: 10.0,
                  right: 10.0,
                  child: Center(
                    child: TabPageSelector(
                      controller: controller,
                      color: Color(0xFFFFFFF0),
                      selectedColor: Colors.amberAccent,
                      indicatorSize: 3.0,
                      shape: IndicatorShape.rectangle,
                    ),
                  ),
                ),
              ],
            ),

            /// end of Stack
          ),

          /// end of Expanded
        ],
      ),
    );
  }
}`

**Comment by hozhis** [comment]
`
class SlidePage {
  SlidePage({@required this.image, this.routeName, this.params})
      : assert(image != null);

  final String image;

  final String routeName;

  final Map params;
}

class _SlidePageSelector extends StatefulWidget {
  const _SlidePageSelector({this.pages});

  final List<SlidePage> pages;

  @override
  _SlidePageSelectorState createState() => _SlidePageSelectorState();
}

class _SlidePageSelectorState extends State<_SlidePageSelector> {
  final GlobalKey<_SlidePageSelectorState> selectorKey =
      GlobalKey<_SlidePageSelectorState>();

  @override
  void initState() {
    super.initState();

    /// 启动轮播图定时器
    Timer.periodic(Duration(milliseconds: 3800), (timer) {
      _autoSlide(selectorKey.currentContext, 1);
    });
  }

  void _autoSlide(BuildContext context, int delta) {
    final TabController controller = DefaultTabController.of(context);
    final List<SlidePage> pages = widget.pages;

    if (!controller.indexIsChanging) {
      if (controller.index >= pages.length - 1 && delta > 0) {
        controller.animateTo(
          (controller.index - pages.length + 1).clamp(0, pages.length - 1),
        );
      } else if (controller.index <= 0 && delta < 0) {
        controller.animateTo(
          (controller.index + pages.length - 1).clamp(0, pages.length - 1),
        );
      } else {
        controller.animateTo(
          (controller.index + delta).clamp(0, pages.length - 1),
        );
      }
    }
  }

  void _handleDragUpdateGesture(DragUpdateDetails details) {}

  @override
  Widget build(BuildContext context) {
    final List<SlidePage> pages = widget.pages;
    final TabController controller = DefaultTabController.of(context);
    return SafeArea(
      key: selectorKey,
      top: false,
      bottom: false,
      child: Column(
        children: <Widget>[
          Expanded(
            child: Stack(
              children: <Widget>[
                GestureDetector(
                  onHorizontalDragUpdate: _handleDragUpdateGesture,
                  onTap: () {
//                    Navigator.pushNamed(context, '/login');
                  },
                  child: TabBarView(
                    children: pages.map(
                      (SlidePage page) {
                        return Container(
                          child: Card(
                            elevation: 0.0,
                            margin: EdgeInsets.zero,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(0.0),
                            ),
                            child: Image.network(
                              page.image,
                              fit: BoxFit.cover,
                              alignment: Alignment.topCenter,
                            ),
                          ),

                          /// end of Card
                        );
                      },
                    ).toList(),
                  ),
                ),

                /// end of GestureDetector

                Positioned(
                  bottom: 5.0,
                  left: 10.0,
                  right: 10.0,
                  child: Center(
                    child: TabPageSelector(
                      controller: controller,
                      color: Color(0xFFFFFFF0),
                      selectedColor: Colors.amberAccent,
                      indicatorSize: 3.0,
                      shape: IndicatorShape.rectangle,
                    ),
                  ),
                ),
              ],
            ),

            /// end of Stack
          ),

          /// end of Expanded
        ],
      ),
    );
  }
}

`

**Comment by AskYous** [comment]
I'm having this issue. Did you solve it?

**Comment by zoechi** [comment]
If the error is exactly the same, please post the output of `flutter doctor -v` and if possible a minimal running reproduction of `lib/main.dart`. 
If it is not the same, please create a new issue.
