### ISSUE TITLE
didReceiveRemoteNotification failed

### ISSUE THREAD

**Issue by dimmetrius** [flutter/flutter#19758]
Hello! I use `firebase_auth` and `firebase_messaging` plugins.

For phone auth I use in my app delegate several methods:
1) `didRegisterForRemoteNotificationsWithDeviceToken`
2) `didReceiveRemoteNotification`
like described at [auth docs page](https://firebase.google.com/docs/auth/ios/phone-auth#enable-app-verification)

but using these methods for auth I have an issue with `didReceiveRemoteNotification` in the `firebase_messaging` plugin. Only one of `didReceiveRemoteNotification` methods works

**Comment by zoechi** [comment]
Are you still seeing this?

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by dimmetrius** [comment]
@zoechi To solve the problem, you should not use didReceiveRemoteNotification in your iOS code, except flutter plugins All processing of didReceiveRemoteNotification must be placed in a separate plugin, otherwise only one will work.

**Comment by kroikie** [comment]
@dimmetrius

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/741. Any further collaboration will be done there.
