### ISSUE TITLE
Would like some methods to find out whether a widget is on screen or off screen.

### ISSUE THREAD

**Issue by nightwolf-chen** [flutter/flutter#19759]
I'm looking for something like
- 'viewWillAppear'
- 'viewWillDisappear'

Because I want to remove some resources from widget when it's off screen. Any ideas on it？

**Comment by zoechi** [comment]
How does it get off screen?
Can you elaborate a bit more with a concrete example?

**Comment by nightwolf-chen** [comment]
I'm using Navigator to manage pages, a page（Widget）got off screen when new pages pushed onto it.  I need some way to figure out whether current widget is part of the  page on the top of Navigator.

**Comment by zoechi** [comment]
Perhaps https://docs.flutter.io/flutter/widgets/RouteObserver-class.html

Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by nightwolf-chen** [comment]
Yes. It works.
