### ISSUE TITLE
[website] don't line-wrap code

### ISSUE THREAD

**Issue by chalin** [flutter/flutter#19760]
Wrapping code often makes it difficult to read. For example:

> <img width="342" alt="screen shot 2018-07-25 at 08 34 21" src="https://user-images.githubusercontent.com/4140793/43201116-944b1baa-8fe5-11e8-957f-d51d65720e3d.png">

Cf. https://github.com/dart-lang/site-webdev/issues/643

cc @Sfshaza @filiph

**Comment by Sfshaza** [comment]
How can one handle it on a small phone? We don't wrap in a browser.

**Comment by chalin** [comment]
> How can one handle it on a small phone?

For site-www and -webdev we use scrolling. /cc @kwalrath 

> We don't wrap in a browser.

AFAICT we wrap in desktop browsers atm.

**Comment by Sfshaza** [comment]
D'OH. Of course.

**Comment by chalin** [comment]
This issue was moved to flutter/website#1173
