### ISSUE TITLE
[website] Support autogeneration of heading anchors and links

### ISSUE THREAD

**Issue by chalin** [flutter/flutter#19761]
Normally hidden:
> <img width="310" alt="screen shot 2018-07-25 at 08 38 53" src="https://user-images.githubusercontent.com/4140793/43201396-5efc617e-8fe6-11e8-81d0-66e0b19aa8d2.png">

Hover:
> <img width="305" alt="screen shot 2018-07-25 at 08 36 47" src="https://user-images.githubusercontent.com/4140793/43201427-75ceb5b4-8fe6-11e8-96d0-7d6ac6e8ffa5.png">

cc @Sfshaza @filiph

**Comment by Sfshaza** [comment]
Yes!

**Comment by chalin** [comment]
This issue was moved to flutter/website#1172
