### ISSUE TITLE
[website] firebase config: use clean URLs w/o trailing slashes

### ISSUE THREAD

**Issue by chalin** [flutter/flutter#19769]
The current flutter.io site seems to enforce trailing slashes everywhere. Was there an original reason for not opting for clean URLs clean URLs w/o trailing slashes? Firebase supports URL cleanup (via redirects) for these options:

```json
{
  "hosting": {
    "...": "...",
    "cleanUrls": true,
    "trailingSlash": false,
    "...": "..."
  }
}
```

cc @Sfshaza @filiph

**Comment by Sfshaza** [comment]
If there was a reason, I don't remember. (It seems like it was needed on the most recent version of the *.dartlang sites). But if it's not needed, I'm happy with that.

**Comment by chalin** [comment]
This issue was moved to flutter/website#1126
