### ISSUE TITLE
App crash on launch - Waiting for observatory port to be available...

### ISSUE THREAD

**Issue by dereklakin** [flutter/flutter#19770]
## Steps to Reproduce
1. Update pubspec.yaml to add image_picker as a dependency:
```
dependencies:
  …
  image_picker:
```
2. Launch application.

## Logs
`flutter run --verbose`:
[flutter.run.verbose.txt](https://github.com/flutter/flutter/files/2228513/flutter.run.verbose.txt)

Logcat output while attempting to launch the app:
[logcat.txt](https://github.com/flutter/flutter/files/2228512/logcat.txt)

`flutter analyse`:
```
PS C:\Projects\MedicineManager\medicine_manager_flutter> flutter analyze
Analyzing medicine_manager_flutter...
No issues found! (ran in 19.5s)
```

`flutter doctor -v`:

```
PS C:\Projects\MedicineManager\medicine_manager_flutter> flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.167], locale en-GB)
    • Flutter version 0.5.1 at C:\Tools\flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\derek\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```
(Note: flutter doctor reports that flutter extension is not installed in VS Code, but it is and works fine for everything else)

**Comment by zoechi** [comment]
> flutter doctor reports that flutter extension is not installed

This is a known issue in this Flutter version and already fixed.

**Comment by zoechi** [comment]
Have you tried with `master` channel?
```
flutter channel master
flutter doctor
```

**Comment by dereklakin** [comment]
Just tried. I actually get the same behaviour _without_ image_picker on the `master` channel, i.e. the app crashes on launch :(

**Comment by zoechi** [comment]
Just to be sure. Does a new app created with `flutter create foo` start propery?

**Comment by dereklakin** [comment]
OK, so a new app runs fine (on the master channel). Going back to my original app, but trying from the command line, it seems that it's stalling after the apk build stage. So the app appears to be installed, but the files haven't yet been synced (which would explain the crash on launch).
Running `flutter run --verbose` shows the last statement as `Waiting for observatory port to be available...`
Note: This is still _without_ the image_picker plugin.

Full dependencies list is:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  path_provider:
  redux:
  flutter_redux:
  uuid:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
```

**Comment by zoechi** [comment]
I'm out of ideas.
Perhaps @tvolkert ?

**Comment by dereklakin** [comment]
I put the same dependency list into the `foo` project and it still worked. Upped that to include `image_picker` in the dependency list and even added some simple test code to use the plugin and it actually worked. So, the problem is not with the `image_picker` plugin, it's something else.

**Comment by zoechi** [comment]
I assume you tried `flutter clean`?

**Comment by dereklakin** [comment]
OK, so running `flutter clean` has resolved the problem. I can run the app again _and_ I can include and use `image_picker`.
Thanks for the help. If there's anything I can do to help run down the problem with `Waiting for observatory port to be available`, let me know.

**Comment by zoechi** [comment]
Great!
So one part of this issue is #16604.
I don't know if there is really anything left to do for `Waiting for observatory port to be available`. Fixing #16640 probably fixes this as well.
I'll leave that for others to decide.

**Comment by dereklakin** [comment]
OK great, thanks. I'll watch that issue,

**Comment by tvolkert** [comment]
Seems like something was corrupted in the install of the app at some point, which was wreaking havoc in the Android system when we tried to launch the app:

```
07-25 15:17:49.312 31027 31027 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dereklakin.medicinemanager.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.dereklakin.medicinemanager-Q2fuBGzxVEhlyoiRa8Vy8w==/base.apk"],nativeLibraryDirectories=[/data/app/com.dereklakin.medicinemanager-Q2fuBGzxVEhlyoiRa8Vy8w==/lib/x86, /data/app/com.dereklakin.medicinemanager-Q2fuBGzxVEhlyoiRa8Vy8w==/base.apk!/lib/x86, /system/lib]]
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
07-25 15:17:49.312 31027 31027 E AndroidRuntime: 	... 11 more
```

My guess is that this was a transient error that we're not going to be able to reproduce now that you're back in business.  As such, I'm gonna close this issue, but feel free to reopen if you encounter it again and are able to find out reliable steps to get in the bad state.

**Comment by dereklakin** [comment]
Thanks Todd. If it happens again I'll reopen with any additional information I can find.

**Comment by Almoullim** [comment]
The same issue, app crashes with "Waiting for observatory port to be available..." on the console. Works fine in iOS.

**Comment by mohabmm** [comment]
@Almoullim  did the problem solved on your side I have the same error. I updated flutter and did flutter clean and still, I have the same issue

**Comment by Almoullim** [comment]
> @Almoullim did the problem solved on your side I have the same error. I updated flutter and did flutter clean and still, I have the same issue

@mohabmm I created a new flutter project and moved all my source code there. I couldn't find any other solution.

**Comment by vjulianiocatec** [comment]
same problem... moving source code to other repository is not an option... working with git, my coworkers build the same commit as I and on their machine app doesn't crash...flutter clean doesn't work... any ideas?

**Comment by mohabmm** [comment]
what I did is re-installing android studio again and every thing get back but I don't depend on the old settings that I have in my laptop during the reinstallation.
hope this can help you.

**Comment by mohabmm** [comment]
@zoechi can you help here please ?

**Comment by vjulianiocatec** [comment]
running with flag --release helped... it doesn't crash anymore...
i suspect there is something wrong with gradleDebug task...

i will try to reinstall android studio and see if this fixes it...

Em sex, 30 de ago de 2019 às 14:21, mohabmm <notifications@github.com>
escreveu:

**Comment by vjulianiocatec** [comment]
running with flag --release helped... it doesn't crash anymore...
i suspect there is something wrong with gradleDebug task...

i will try to reinstall android studio and see if this fixes it...

**Comment by vjulianiocatec** [comment]
purging (deleting all files with android in the name on my computer) and reinstalling seemed to work :D

**Comment by chuckinSpace** [comment]
In my case, I was using firebase AdMob and forgot to add the change to the android manifest 
https://pub.dev/packages/firebase_admob
In case anyone runs to that one
