### ISSUE TITLE
XcodeProject.zip should be use the flutter artifact cache

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1977]
Right now we download it fresh every time you run `flutter create`

This is bad for a number of reasons (slow, lack of offline support, etc.):

Downloading https://storage.googleapis.com/flutter_infra/flutter/9e1e1fba5474b458458b65f1aa1d0d730af2705b/ios/FlutterXcode.zip...

Should be trivial to make it an artifact, no?

@chinmaygarde @devoncarew

**Comment by chinmaygarde** [comment]
Its not quite trivial because the Xcode project ends up in a different bucket than the rest of the artifacts. Why do we have multiple buckets anyway?

**Comment by abarth** [comment]
Soon flutter_infra will be the one true bucket.

**Comment by eseidelGoogle** [comment]
I believe flutter_infra is now the one true bucket?

**Comment by chinmaygarde** [comment]
This was fixed a while ago.
