### ISSUE TITLE
JSON and serialization: update docs to latest json_serializable

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#19778]
From URL: https://flutter.io/json/#serializing-json-using-code-generation-libraries

json_serializable and json_annotation are now at v1 and have some new default behaviors (no more mixins) – would be good to update this page!

CC @roughike @Sfshaza

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/json_serializable/issues/271

**Comment by zoechi** [comment]
This looks done.

![image](https://user-images.githubusercontent.com/405837/49587585-93695600-f964-11e8-97d6-fb370ecd2234.png)
