### ISSUE TITLE
showBottomSheet() creates back button on iOS

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19793]
I *think* this is a bug, but if you use `showBottomSheet()` on iOS it creates a back button for it specifically.

**Comment by lukepighetti** [comment]
In a MaterialApp on iOS if you showBottomSheet() a back button will appear in the upper left

**Comment by creativecreatorormaybenot** [comment]
@lukepighetti I feel like this is perfectly appropriate behavior because it is the way to close the bottom sheet (apart from sliding it down) and the back button is Material design.

**Comment by xster** [comment]
What's your expected behavior?

**Comment by lukepighetti** [comment]
I've been using this more and I think the back button is fine!
