### ISSUE TITLE
[image_picker] Camera permission not needed

### ISSUE THREAD

**Issue by ricamgar** [flutter/flutter#19806]
Hi,
since the plugin is not using the camera, just requesting the intent, the CAMERA permission is not needed. Here the tutorial on how to use the camera intent from the official docs: https://developer.android.com/training/camera/photobasics

Thanks!

**Comment by zoechi** [comment]
> since the plugin is not using the camera

https://github.com/flutter/plugins/blob/34962b5025ff8d80b630329d8e349122d270de3d/packages/image_picker/lib/image_picker.dart#L14

It does use the camera.

**Comment by ricamgar** [comment]
It uses the camera intent, not the camera hardware, therefore the permission is not needed.

You can see here an example I created to demonstrate it: 
https://github.com/ricamgar/CameraPermission
