### ISSUE TITLE
Always got this error when trying to use FirebaseAuth (signinwithemailandpassword, createwithemailandpassword, signout, currentuser)

### ISSUE THREAD

**Issue by illukinati** [flutter/flutter#19804]
```
void validateAndSubmit() async {
    if (validateLogin()) {
      await FirebaseAuth.instance
          .signInWithEmailAndPassword(email: _email, password: _password);
      MyNavigator.goToTimeline(context);
    }
  }
```

![screen shot 2018-07-26 at 14 29 11](https://user-images.githubusercontent.com/22829784/43243285-da31990e-90e0-11e8-9021-b6db172f23e0.png)

> [flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
exit code 0

**Comment by zoechi** [comment]
Please post the code that allows to reproduce.
Where does the code of your screenshot come from?

**Comment by illukinati** [comment]
@zoechi it's just simple signin, and always end up got that error.
after I restart my program, it's detected signed in already

**Comment by illukinati** [comment]
> W/DynamiteModule(12506): Local module descriptor class for com.google.firebase.auth not found.
W/BiChannelGoogleApi(12506): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@f860824
W/DynamiteModule(12506): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth(12506): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(12506): [FirebaseAuth:] Preparing to create service connection to gms implementation
D/FirebaseAuth(12506): Notifying id token listeners about user ( WM405Z97NkSjNj8CTGQmf7mRfuf1 ).
D/FirebaseAuth(12506): Notifying auth state listeners about user ( WM405Z97NkSjNj8CTGQmf7mRfuf1 ).
D/FirebaseApp(12506): Notifying auth state listeners.
D/FirebaseApp(12506): Notified 0 auth state listeners.

**Comment by illukinati** [comment]
I just found out everything is error and crash after using 

```
Future<void> checkLoggedIn() async {
    FirebaseAuth.instance.onAuthStateChanged.listen((FirebaseUser user) async {
      if (user != null) {
        Navigator.pushAndRemoveUntil(
            context, mainRoute, (Route<dynamic> route) => false);
      } else {
        Navigator.pushAndRemoveUntil(
            context, welcomeRoute, (Route<dynamic> route) => false);
      }
    });
  }

  @override
  void initState() {
    checkLoggedIn();
    super.initState();
  }
```

**Comment by N3g4tivo** [comment]
I have the same problem. 
How do you resolved it?

**Comment by kroikie** [comment]
@illukinati

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/739. Any further collaboration will be done there.
