### ISSUE TITLE
Rename bug_reports to bug-reports in website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1981]
@chinmaygarde has a doc that we can make public.

**Comment by eseidelGoogle** [comment]
It's public: https://github.com/flutter/website/blob/master/bug_reports.md  I don't know if it's linked anywhere other than the direct link:

https://flutter.io/bug_reports/

**Comment by sethladd** [comment]
Great!

nit: in the future, please use `-` instead of `_` for URLs.

**Comment by chinmaygarde** [comment]
It's linked on the main page  under "See Also". Will be vigilant of the underscores.

**Comment by sethladd** [comment]
I'd like to keep this open, it's something easy to get to later. Keeping it open as a reminder to me.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/website/pull/175
