### ISSUE TITLE
Clear DynamicLink in memory after FirebaseDynamicLinks is retrieved

### ISSUE THREAD

**Issue by diegoveloper** [flutter/flutter#19820]
Tested on iOS :

When I open my app from a dynamic link, I have a button on my widget to get the dynamic link received

```dart
final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.retrieveDynamicLink();
```

Then problem comes  when I open the application again manually (not from the dynamic link).
If I press the button to trigger this method

```dart
final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.retrieveDynamicLink();
```
**Result** : I receive the same value as the first call which is not correct.

**Expected**: I expect to receive null because my app was not open from the dynamic link

**Comment by zoechi** [comment]
#19506 looks related

**Comment by diegoveloper** [comment]
Yes , It's related , I'm trying to do a workaround using the WidgetsBindingObserver to listen when the app go into foreground  but the problem is every time that I call to **retrieveDynamicLink** the data persist from the last dynamic link opened.

**Comment by diegoveloper** [comment]
I can confirm it's working fine in Android   

```
final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.retrieveDynamicLink();
```
When I call the code above It only returns data when I open the app from the dynamicLink.

**Comment by zoechi** [comment]
Seems flutter/plugins#699 fixed this issue

**Comment by kroikie** [comment]
@diegoveloper

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/738. Any further collaboration will be done there.
