### ISSUE TITLE
google_sign_in plugin support prompt  parameter

### ISSUE THREAD

**Issue by martinvarelaaaa** [flutter/flutter#19839]
Unable to force the account to be selected again, this is because the plugin no support [setCustomParameters](https://firebase.google.com/docs/auth/web/google-signin?hl=es-419).

When the user does signout and then signin it does not allow you to select the account.

**Comment by zoechi** [comment]
You need to sign out from GoogleSignIn and FirebaseAuth and then sign in again.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kroikie** [comment]
@martinvarelaaaa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/736. Any further collaboration will be done there.
