### ISSUE TITLE
flutter doctor should check for an available JDK

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1983]
The process will be a bit platform dependent. Not clear if we need a JRE or a JDK. We do use `jarsigner` as part of the android workflow, so probably a JDK.

**Comment by eseidelGoogle** [comment]
According to @HansMuller the JRE is no longer really a separate thing.  We use the JDK I believe.

**Comment by devoncarew** [comment]
Bumping from the hackathon -
