### ISSUE TITLE
BasicMessageChannel with BinaryCodec bug on Android

### ISSUE THREAD

**Issue by mfiels** [flutter/flutter#19849]
I'm using `BasicMessageChannel` with `BinaryCodec` and running into issues.

I've created a simple app so you can easily reproduce: [binary_codec_test](https://github.com/mfiels/binary_codec_test).

This app does the following:
  * Clicking the "+" button sends a message to the native layer
  * The native layer generates a random `ByteBuffer` of 8 bytes
  * The native layer sends that random buffer back up to Dart
  * The native layer also asynchronously sends a random `ByteBuffer` of 8 bytes up to Dart every second

I log the size of the buffer every step of the way. However whenever I get the bytes back in the Dart layer they are **always** empty. The bytes look ok at everywhere else, the problem is only seen when sending from native back up to Dart.

Some code references:
  * [Sending random bytes as a response to an incoming message](https://github.com/mfiels/binary_codec_test/blob/master/android/app/src/main/java/com/example/binarycodectest/MainActivity.java#L29-L42)
  * [Sending random bytes every 1 second](https://github.com/mfiels/binary_codec_test/blob/master/android/app/src/main/java/com/example/binarycodectest/MainActivity.java#L45-L55)
  * [Dart listener](https://github.com/mfiels/binary_codec_test/blob/master/lib/main.dart#L12-L15)
  * [Dart request / response](https://github.com/mfiels/binary_codec_test/blob/master/lib/main.dart#L70-L76)

I haven't tried this on iOS yet.

**Comment by mehmetf** [comment]
Interesting; we routinely use this setup to send protos back and forth. Will take a look tomorrow.

**Comment by mehmetf** [comment]
I see the problem.

The outgoing bytebuffers need to be directly allocated. wrap() does not use direct byte buffers. Instead try doing:

```java
ByteBuffer.allocateDirect(bytes.length).put(bytes);
```

and it will work. We should put this in the documentation of BinaryCodec in java.

**Comment by mfiels** [comment]
Ah got it. Thanks for the help, and for updating the documentation 👍
