### ISSUE TITLE
[Java] MethodChannel should be an interface

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#19847]
To better support writing plugin tests, MethodChannel should be an interface that can be mocked.

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/services/MethodChannel/setMockMethodCallHandler.html does not solve your use case?

**Comment by jtmcdole** [comment]
_cough_ Java _cough_ ;)

**Comment by zoechi** [comment]
You mean for testing the Java code?

**Comment by jtmcdole** [comment]
For unit testing our native code, yes.

**Comment by zoechi** [comment]
@jtmcdole Would #20876 work for you as well?
Can this issue be closed in favor of #20876 or do you think this would still be needed?

**Comment by zoechi** [comment]
Merging with #20876
