### ISSUE TITLE
Snackbar breaks Material Design spec

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19841]
<img width="869" alt="screen shot 2018-07-26 at 6 27 01 pm" src="https://user-images.githubusercontent.com/666539/43291980-9798fb98-9101-11e8-9461-fb6862a5c7b1.png">

Currently the Snackbar cannot have it's position modified to make it Contextual.

**Comment by xqwzts** [comment]
WIP PR: https://github.com/flutter/flutter/pull/21484

**Comment by BondarenkoStas** [comment]
Closing as it's fixed in https://github.com/flutter/flutter/pull/31275 v1.5.8
