### ISSUE TITLE
AdMob banner covers Snackbars

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19840]
AdMob banner covers Snackbars. I haven't found a good way to solve it. I can provide padding my scaffold but that doesn't work on iOS because the banner is supposed to have transparency to the left and right.

**Comment by zoechi** [comment]
Similar to #17075, #14222

**Comment by mulderpf** [comment]
+1 on this.  This is another Admob issue which is breaking my app with no feasible workaround.

**Comment by zoechi** [comment]
Duplicate of #14222

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/735. Any further collaboration will be done there.
