### ISSUE TITLE
[Doctor] Android studio or IntelliJ is showing wrong status indicator character (X,!,✓)

### ISSUE THREAD

**Issue by willlarche** [flutter/flutter#19844]
From a user's experience. Trying to get more information on reproduction steps.

![screen shot 2018-07-26 at 4 11 40 pm](https://user-images.githubusercontent.com/1271525/43293488-671711ba-90ef-11e8-82fe-a598ffd49790.png)

**Comment by zoechi** [comment]
Do you think this is still relevant?

**Comment by kf6gpe** [comment]
@willlarche Will, do you think this is worth keeping open?

**Comment by willlarche** [comment]
Nope!
