### ISSUE TITLE
Unification of names in package 'dart: convert' 

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#19855]
If use package **_'dart: convert'_** in **Flutter**, the constructs  _J̶S̶O̶N̶.encode_ and  _J̶S̶O̶N̶.decode_ are deprecated and _jsonEncode_ and _jsonDecode_ notation need be used. At the same time, if write console or web applications on **dart**, _jsonEncode_ and _jsonDecode_ constructions aren't allowed. Instead of using the same serializer, have to modify the serializer code for **Flutter** if initially serializer was written for console application. All this isn't fatal, of course, but this is an extra work. Maybe it make sense to add _jsonEncode_ and _jsonDecode_ functions to **_'dart: convert'_** also into **dart**?

**Comment by zoechi** [comment]
> jsonEncode and jsonDecode constructions aren't allowed

Why do you think that?
It's the exact same code if you use the same package version and a recent Dart 2 SDK.
These names were aligned with the Dart style guide for Dart 2. If you use Dart 1 SDK they won't work though.
