### ISSUE TITLE
Some problems with antialiasing.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#19851]
I've been working on diagrams, and I've noticed some recent problems with (I think) antialiasing.

The image below was captured on a Pixel 2. There are problems rendering some lines with diagonal slopes (look at the part of the curve that is at about 45 degrees: it appears to be thinner for a bit, when it should appear uniform thickness):

![curve_ease_00025](https://user-images.githubusercontent.com/8867023/43296700-c4f015a4-9101-11e8-8612-44b877a4f781.png)

This is especially bad when we animate this diagram, because the antialiasing becomes noisy over time.

I'm going to guess that this is somehow Skia related, so I'll tag it with that, but I don't really know.

**Comment by chinmaygarde** [comment]
Do you have a reduced test case for that graph?

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/commit/93dac2a88d1695fc9508acabb2e3d4cf5f0429a5 Might fix this. Not sure if it applies here, but before that patch, we were incorrectly passing false for antialiasing for all ClipRects.

**Comment by zoechi** [comment]
@gspencergoog did the engine change fix this?

**Comment by markusaksli-nc** [comment]
@chinmaygarde Isn't this fixed now?

If the issue still happens somewhere, could you share a repro case?

**Comment by pedromassangocode** [comment]
(Triage team)

Closing this since it has been more than 21 days without customer response.
