### ISSUE TITLE
text height is different on android devices with virtual navigation bars than on android devices without virtual navigation bars.

### ISSUE THREAD

**Issue by yohom** [flutter/flutter#19857]
text height of Chinese characters is different on android devices with virtual navigation bars than on android devices without virtual navigation bars. iOS behaves like an android device with a virtual navigation bar.
this is on android devices with virtual navigation bars
![with virtual navigation bars](https://user-images.githubusercontent.com/10418364/43301952-97c0c83c-919a-11e8-9c3f-eab49e2a185c.png)
this is on android devices without virtual navigation bars
![without virtual navigation bars](https://user-images.githubusercontent.com/10418364/43302008-cc6e8f2e-919a-11e8-8897-655ad7cba32b.jpg)
this is on ios
![ios](https://user-images.githubusercontent.com/10418364/43302257-12f55d5a-919c-11e8-8119-9275d34f9c11.jpeg)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.152, on Mac OS X 10.13.6 17G65, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
[✓] VS Code (version 1.25.0)
[✓] Connected devices (3 available)

• No issues found!

```

**Comment by GaryQian** [comment]
I will look into this a bit and see what I can do.

**Comment by GaryQian** [comment]
So far, it seems that the problem is originating in Skia font metrics, which is providing drastically different metrics.fDescent for different devices. Will see if it is a problem with what we are passing to Skia or not.

**Comment by GaryQian** [comment]
@yohom Is your "device without virtual navigation bar" a Samsung device? Also, do you have a non-Samsung device that does not have a virtual navigation bar? I suspect the issue may be from Samsung default fonts rather than something flutter/skia is doing.
