### ISSUE TITLE
update flutter.versionCode alone with versionName when building

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#19864]
re-pro:

1. update `version` in `pubspec` from `0.0.3` to `0.0.4`
2. `flutter build apk`

---

result in `local.properties`

```
flutter.versionName=0.0.4
flutter.versionCode=3
```

---

expected in `local.properties`

```
flutter.versionName=0.0.4
flutter.versionCode=4
```

**Comment by zoechi** [comment]
These two fields are not necessarily related. 
What should happen when you change `version` in `pubspec.yaml` from `0.0.4` to `0.1.0`?
You can use the parameters `--build-number` and `--build-name` to have `pubspec.yaml` and `local.properties` updated at once, but you need to pass the values explicitely.

**Comment by namiwang** [comment]
Yah that's reasonable. Didn't notice the params, thanks!

Closing.

**Comment by mrtampan** [comment]
> These two fields are not necessarily related.
> What should happen when you change `version` in `pubspec.yaml` from `0.0.4` to `0.1.0`?
> You can use the parameters `--build-number` and `--build-name` to have `pubspec.yaml` and `local.properties` updated at once, but you need to pass the values explicitely.

this worked for me .  makasih bang
