### ISSUE TITLE
problem with firebase_admob 0.5.6.

### ISSUE THREAD

**Issue by alvinkonda** [flutter/flutter#19868]
Before used to work fine but after the update i cant build anymore my app on android. on IOS works fine. Flutter doctor shows everything ok.

```
FAILURE: Build failed with an exception.
* What went wrong:
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.0,16.0.0]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.1,16.0.1]], but resolves to 15.0.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```

**Comment by kondasoft** [comment]
Adding the following line on the `app/build.gradle` solved my problem, at least i suppose so. 

`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

**Comment by issmeil** [comment]
Have the same issue.  The disableVersionCheck = true workaround works fine, but is this the only fix we have at this moment ?

**Comment by neifergarcia** [comment]
[https://gist.github.com/jkasten2/2c63ce79c03cac4943e240a46cea218c#file-build-gradle-L45-L47](url)

**Comment by kondasoft** [comment]
@Luckygirlllll 

Anywhere, doesnt matter. Usually at the end of the file with a comment that you did the change.

**Comment by Thien658jjh** [comment]
> @Luckygirlllll
> 
> Anywhere, doesnt matter. Usually at the end of the file with a comment that you did the change.

I got this error after I added that line and update all firebase implementation to the newest version:

`The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.`

Any solution ?

**Comment by yashthakkar1173** [comment]
I have the same issue with firebase but it solved please refer this [link](https://stackoverflow.com/questions/52756049/gradle-issue-in-flutter-when-using-firebase) for more details!

**Comment by devanshsadhotra** [comment]
> Adding the following line on the `app/build.gradle` solved my problem, at least i suppose so.
> 
> `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

it still gives the same error, can u please tell, in which section of app/build.gradle , do I have to put this
?

**Comment by prabhu8511** [comment]
Add this line at the very bottom of your app build.gradle file.

**Comment by hassanbaiga** [comment]
> > Adding the following line on the `app/build.gradle` solved my problem, at least i suppose so.
> > `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`
> 
> it still gives the same error, can u please tell, in which section of app/build.gradle , do I have to put this
> ?

You can't release the app if you do this ... can't upload to playstore console either ... not a fix ..
It happens when you update the version of flutter

**Comment by erluxman** [comment]
> Adding the following line on the `app/build.gradle` solved my problem, at least i suppose so.
> 
> `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

I get this error 

A problem occurred evaluating project ':app'.
> No such property: config for class: com.google.gms.googleservices.GoogleServicesPlugin

**Comment by kroikie** [comment]
@kondasoft

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/734. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by pedromassangocode** [comment]
Hi @kroikie 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  

Closing this as https://github.com/FirebaseExtended/flutterfire/issues/734 is closed for inactivity, if anyone is facing this issue please file a new one by filling the issue template.

If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
