### ISSUE TITLE
Can not run flutter doctor

### ISSUE THREAD

**Issue by rpjayasekara** [flutter/flutter#19860]
#When I run I get this and I can not run flutter doctor with sudo. Can anyone help me with this? 
```
randika@randika-Aspire-F5-573G:~$ export PATH=`pwd`/flutter/bin:$PATH
randika@randika-Aspire-F5-573G:~$ flutter doctor
/home/randika/flutter/bin/flutter: line 161: /home/randika/flutter/bin/cache/dart-sdk/bin/dart: Permission denied
```

**Comment by absin1** [comment]
Yep, did the same blunder.

**Comment by phfontess** [comment]
Hi guys I solved this issue, but my Flutter instalation is inside /opt folder. 
Add flutter to your path and just run: 
`sudo chown [your_user]:root /opt` 
With this command I'm telling that my user is inside root group for /opt folder.
Now I can run flutter =)

**Comment by labermt** [comment]
From what I can see, the owner of the flutter folder is not set up correctly. You are getting around a problem with the install procedure. The ownership of the install is currently set to 1024. Android install is set as root but permissions are set up correctly. Not sure how to report this to the flutter team.

**Comment by Joesta** [comment]
I was facing the same issue, my solution was to delete the flutter install directory and extract flutter using terminal without issuing the sudo command.

**Comment by mateuszmatyszkowicz** [comment]
> Hi guys I solved this issue, but my Flutter instalation is inside /opt folder.
> Add flutter to your path and just run:
> `sudo chown [your_user]:root /opt`
> With this command I'm telling that my user is inside root group for /opt folder.
> Now I can run flutter =)

I added recursive paramater and it works like charm `sudo chown -R [user]:root /opt/flutter`

**Comment by psygo** [comment]
Using more recent syntax it would actually be:

```bash
sudo chown -R <your_username>: <flutter_directory>
```

**Comment by hising** [comment]
@psygo thanks, I got it working with 

`sudo chown -R $USER /opt/flutter`
