### ISSUE TITLE
Plugin google_sign_in: Compatibility with googleapis package

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#19867]
I wasn't able to figure out how to use "account" which I obtained from "google_sign_in" with "googleapis" package (https://pub.dartlang.org/packages/googleapis).

After some searching I gave up and created this beauty:

```dart
class AuthClient implements Client {

  Client _baseClient;
  Map<String, String> headers;

  AuthClient(this._baseClient, this.headers);

  @override
  void close() {
    _baseClient.close();
  }

  @override
  Future<StreamedResponse> send(BaseRequest request) {
    request.headers.addAll(headers);
    return _baseClient.send(request);
  }

  @override
  Future<Uint8List> readBytes(url, {Map<String, String> headers}) {
    return _baseClient.readBytes(url, headers: _mergeHeaders(headers));
  }
 ...

```
... which simply adds authorization headers from GoogleSignInAccount.authHeaders to all requests. Then I use this AuthClient in a constructor of Google Apis clients, like this:

```dart
      var auth = await account.authHeaders; // google_sign_in
      http.Client c = new AuthClient(new http.Client(), auth); // my class
      DriveApi d = new DriveApi(c); // googleapis
```

It all works, no problem there, but it's hardly a smooth developer experience :-)

Please:
1) either provide such "authorized client" class within google_sign_in package
2) OR maybe it's already solved somehow somewhere? Then please mention it in the documentation (specifically the interoperability between those two packages).

Thanks!

**Comment by zoechi** [comment]
Similar https://stackoverflow.com/questions/48477625/how-to-use-google-api-in-flutter/48485898#48485898

I used it partly to access cloud functions in tests but this is covered now by https://github.com/flutter/plugins/tree/master/packages/cloud_functions

**Comment by stuartmorgan** [comment]
This is addressed by https://pub.dev/packages/extension_google_sign_in_as_googleapis_auth

See also https://github.com/flutter/flutter/issues/78090
