### ISSUE TITLE
Flutter SDK is not found on specified location

### ISSUE THREAD

**Issue by fatimah1996** [flutter/flutter#19869]
![flutter](https://user-images.githubusercontent.com/22788032/43319226-966a71c4-91ac-11e8-8f5c-a7fc084cc335.PNG)

hi, i've already installed Flutter , SDK says not found whatever i choose a file , D: file doesnot have permission

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`. (executed in a command line shell)

**Comment by fatimah1996** [comment]
![flutter2](https://user-images.githubusercontent.com/22788032/43320021-accee7e4-91af-11e8-862e-9bc61478408f.PNG)
file D: doesnt need any admin privilages

**Comment by ram231** [comment]
Please update your PATH in your Environment variables. or maybe you're logged in as guest.

**Comment by mrinvicto** [comment]
This problem is pretty common and can easily be fixed. Please refer to the below mentioned link for help.

[Flutter SDK not found](https://ladwhocodes.blogspot.com/2019/02/fix-flutter-sdk-not-found-in-specified-location.html)

**Comment by HamzaTanveer78** [comment]
> This problem is pretty common and can easily be fixed. Please refer to the below mentioned link for help.
> 
> [Flutter SDK not found](https://ladwhocodes.blogspot.com/2019/02/fix-flutter-sdk-not-found-in-specified-location.html)

I'm scratching my head for three days to solve this solution but this solution work. I don't know what the logic behind this. but this works.  thanks man

**Comment by Lanny2016** [comment]
Flutter SDK not found  is the magic for the problem of Flutter SDK is not found on specified location

**Comment by jkhin** [comment]
Guys where the link is?

**Comment by ForceGT** [comment]
If anyone is here and still looking for the fix
It is actually logging in and out of your shell after you set the path either manually or use the "Install SDK" button out there
It is simply because the PATH doesn't get updated 
Thanks to @probe2k for point this out
You can also set up the path by using his script https://github.com/probe2k/ShellScripts/blob/master/flutter_install.sh

**Comment by MartinsSilva** [comment]
Thank you! I had this problem for a long time!

**Comment by bharoojangid** [comment]
Try These:

Open your terminal
type flutter doctor --android-licenses
press y to accept every license.

**Comment by RaviPabari** [comment]
> Try These:
> 
> Open your terminal
> type flutter doctor --android-licenses
> press y to accept every license.

Ty

**Comment by surrenderios** [comment]
try this:
in local.properties:
flutter.sdk=/Users/xxxx/xxxx/flutter

in screen.iml
def flutterRoot = localProperties.getProperty('flutter.sdk') + '/bin/flutter'

**Comment by KBPsystem777** [comment]
Run `flutter doctor -v` first. See if you got a warning **!** in android licenses, under Android toolchain. If yes, run `flutter doctor --android-licenses` you'll have to accept those first by replying `Y` in the terminal

**Comment by sagar98cyber** [comment]
![image](https://user-images.githubusercontent.com/57261622/77594991-f8f8a180-6f1d-11ea-838b-1508f1345549.png)

**Comment by vishvavijay** [comment]
Getting same problem

**Comment by ForceGT** [comment]
> ![image](https://user-images.githubusercontent.com/57261622/77594991-f8f8a180-6f1d-11ea-838b-1508f1345549.png)
> 
> any help is appreciated

Looks like your Android SDK is not properly installed try installing it again

**Comment by ForceGT** [comment]
> Getting same problem

Did You try the above solutions?

**Comment by exeptionerror** [comment]
All Possible Solution Added [[Solved] Flutter SDK is not found in the specified location in Android Studio](https://fluttercorner.com/flutter-sdk-is-not-found-in-the-specified-location-in-android-studio/)
