### ISSUE TITLE
How to cache Listview or Stop rerender after scroll out screen

### ISSUE THREAD

**Issue by 7elven** [flutter/flutter#19866]
The list items my ListView is populated with each contain initState methods fetching data from the internet. So when I scroll through the list and the items get out of view, they get out of the widget tree and when I scroll up to them again they will rerender, fetching the data again.

**Comment by zoechi** [comment]
Such how-to question is better asked on StackOverflow.
You can use Redux or similar to manage state outside of your widgets.

**Comment by 7elven** [comment]
I mean I have 10 items in ListView. I scroll down to item 6 and item 1 is out of view screen. Item 1  was render right? 

When I scroll up to item 1 why it re-render? How to stop re-render or cache item was render

**Comment by zoechi** [comment]
This is for performance optimizations.
I think if the widget implements https://docs.flutter.io/flutter/widgets/AutomaticKeepAliveClientMixin-class.html the widgets are kept alive. 
It's still better to have logic to fetch and cache Data outside of the widgets. 
https://medium.com/@diegoveloper/flutter-persistent-tab-bars-a26220d322bc might help

**Comment by kapil708** [comment]
> This is for performance optimizations.
> I think if the widget implements https://docs.flutter.io/flutter/widgets/AutomaticKeepAliveClientMixin-class.html the widgets are kept alive.
> It's still better to have logic to fetch and cache Data outside of the widgets.
> https://medium.com/@diegoveloper/flutter-persistent-tab-bars-a26220d322bc might help

this link is not working and i have the same issue
https://docs.flutter.io/flutter/widgets/AutomaticKeepAliveClientMixin-class.html

**Comment by Sharperr** [comment]
> I mean I have 10 items in ListView. I scroll down to item 6 and item 1 is out of view screen. Item 1 was render right?
> 
> When I scroll up to item 1 why it re-render? How to stop re-render or cache item was render

If you have just a plentiful of items, I solved this issue by setting the "cacheExtent" property to the amount of items mulitplied by a set amount (the rough average height of one item widget).
I am not sure whether this goes against performance best practices tho (doesn't seem to slow down performance in my case).

**Comment by Renatinaveen** [comment]
@palianskas your method worked performance is smooth but i have children with gesturedetectors on tap i open a new page. After i come back the page scrolls automatically to some random position and stops. What to do to solve this?
