### ISSUE TITLE
How to set up private pub server?

### ISSUE THREAD

**Issue by specneeo** [flutter/flutter#19862]
### How to set up private pub server?
I want to publish my dart lib on private server, not [https://pub.dartlang.org/](https://pub.dartlang.org/)
How to so this?

Also, I found [pub_server](https://github.com/dart-lang/pub_server), but `This is package is an alpha version and is not recommended for production use.`

any one could give me suggestion? many thanks.

**Comment by zoechi** [comment]
There is no other pub server currently.
You can also use a Git repository instead of a pub server.
https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by pd4d10** [comment]
We also run into this issue and make a package named unpub for private packages host.

Link here: [unpub](https://github.com/bytedance/unpub).

Hope it would be helpful for you.
