### ISSUE TITLE
Error: No named parameter with the name 'hasNotch' in BottomAppBar

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#19874]
When creating

```
BottomAppBar(
        hasNotch: true,
```

This shows an error message `Error: No named parameter with the name 'hasNotch'`.
I checked the doc https://docs.flutter.io/flutter/material/BottomAppBar-class.html, it does have this parameter. But my current flutter `flutter/packages/flutter/lib/src/material/bottom_app_bar.dart` lib doesn't have it. 

# Flutter version

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.5.8-pre.128, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.8-pre.128 at /home/song/opt/flutter
    • Framework revision d71d10094d (2 days ago), 2018-07-25 13:43:36 +0100
    • Engine revision 95e91e31fa
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca
```

**Comment by HansMuller** [comment]
Unfortunately the docs haven't sync'd up with the latest changes to BottomAppBar yet. For the moment, you'll have to read the docs in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/bottom_app_bar.dart and check out the example in https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/bottom_app_bar_demo.dart.

**Comment by HansMuller** [comment]
See also the PR that describes the API changes: https://github.com/flutter/flutter/pull/18372

**Comment by sgon00** [comment]
@HansMuller thank you very much for the quick reply. Got it. I am closing this issue.
