### ISSUE TITLE
Editting text of TextField in landscap view

### ISSUE THREAD

**Issue by vijayaragavangkf** [flutter/flutter#19875]
how to achive 
![screenshot_2018-07-27-19-32-16-902 1](https://user-images.githubusercontent.com/35106540/43325319-fb761128-91d3-11e8-97c8-8c10c8346b5b.jpeg)

[like EditText in normal java Android ]

instead
![screenshot_2018-07-27-19-28-04-438 1](https://user-images.githubusercontent.com/35106540/43325441-4a2429ae-91d4-11e8-8aca-057fd22e0734.jpeg)

**Comment by zoechi** [comment]
You can use https://docs.flutter.io/flutter/widgets/MediaQuery-class.html to figure out the orientation and build a different view in case of Landscape orientation.

**Comment by zoechi** [comment]
If this is still an issue please consider asking in one of the channels listed in http://flutter.io/support .
