### ISSUE TITLE
flutter_test from sdk depends on http 0.11.3+16

### ISSUE THREAD

**Issue by ViniciusSossela** [flutter/flutter#19881]
## Steps to Reproduce

1. Add HTTP latest version as dependency breaks the package upgrade.

<img width="874" alt="screen shot 2018-07-27 at 12 05 28" src="https://user-images.githubusercontent.com/4993276/43332250-336b2144-919e-11e8-9f39-9f374bc17ba5.png">

<img width="550" alt="screen shot 2018-07-27 at 13 03 19" src="https://user-images.githubusercontent.com/4993276/43332030-7ef8ab96-919d-11e8-956c-27b410f190c9.png">

Should `fluter_test` from SDK be updated to use the latest HTTP package version (http 0.11.3+17) ?
(https://pub.dartlang.org/packages/http)

**Comment by zoechi** [comment]
I believe this is not a problem anymore in beta 0.6.0

**Comment by Mistic92** [comment]
I'm still getting this error

```
Running "flutter packages get" in xxxxxx_mobile_flutter...      
Because every version of flutter_test from sdk depends on http 0.11.3+17 and Xxxxxx depends on http 0.12.0, flutter_test from sdk is forbidden.
So, because Xxxxxx depends on flutter_test any from sdk, version solving failed.
```

Flutter doctor output

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17763.104], locale pl-PL)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] VS Code (version 1.28.2)
[√] VS Code, 64-bit edition
[√] Connected devices (1 available)

```

**Comment by zoechi** [comment]
@Mistic92 either switch to `dev` channel until a new `beta` is available or use older versions of dependencies that don't depend on `http: 0.12.0`

**Comment by jonahwilliams** [comment]
@Mistic92 we're working on removing our http dependency here: https://github.com/flutter/flutter/pull/23755. In the future this should cause fewer dependency conflicts

**Comment by NightCrawler33** [comment]
> I'm still getting this error
> 
> ```
> Running "flutter packages get" in xxxxxx_mobile_flutter...      
> Because every version of flutter_test from sdk depends on http 0.11.3+17 and Xxxxxx depends on http 0.12.0, flutter_test from sdk is forbidden.
> So, because Xxxxxx depends on flutter_test any from sdk, version solving failed.
> ```
> Flutter doctor output
> 
> ```
> [√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17763.104], locale pl-PL)
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     X Android license status unknown.
> [√] Android Studio (version 3.1)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [√] Android Studio (version 3.2)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [!] IntelliJ IDEA Ultimate Edition (version 2018.1)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [√] IntelliJ IDEA Ultimate Edition (version 2018.3)
> [√] VS Code (version 1.28.2)
> [√] VS Code, 64-bit edition
> [√] Connected devices (1 available)
> ```

Also facing the same error as of today with latest updates.

**Comment by jonahwilliams** [comment]
@NightCrawler33 the current beta is from several weeks ago, while the changes just landed on master a few days ago.
