### ISSUE TITLE
@Nullable annotations for Android engine endpoints

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#19888]
google3 requires large projects to enable nullability checks. Such apps are not able to use Flutter at the moment because our APIs are not marked with nullable annotations.

**Comment by matthew-carroll** [comment]
@mehmetf I should be able to handle this within the add2app work

**Comment by matthew-carroll** [comment]
Closing this ticket in favor of many more granular tickets within the Platform Embedding project:
https://github.com/flutter/flutter/projects/27

**Comment by mehmetf** [comment]
Is there a ticket in particular that is tracking the nullable annotations? This was tied to an internal buganizer issue which is now reopened while the upstream issue is not fixed yet.

**Comment by matthew-carroll** [comment]
I split it into many tickets that are in the project.  It's difficult to say when all annotations are done, much like javadocs.
