### ISSUE TITLE
Validate performance on Android One / old Samsung devices

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#199]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [abarth](https://github.com/abarth)**
_Wednesday Oct 14, 2015 at 00:11 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1607_

---

We should make sure our performance scales down to low-end devices.

**Comment by chinmaygarde** [comment]
We are now keeping track of device/gpu vendor specific issues in their own tickets. Closing. If there is a particular low end device we want to validate, we can open another ticket with specifics.
