### ISSUE TITLE
Flutter Atom devices popup does not show android device, despite being connected

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1990]
Both @iposva-google and @gbracha hit this.

@devoncarew

**Comment by eseidelGoogle** [comment]
Both were on Macs.  Both had adb at /usr/local/bin/adb as well as the Android SDK separately installed in ~/Librarly/Android/sdk.

Both had identical versions (1.0.32) of adb in both locations.  But I do think the two-copies-of-adb may be part of the trouble here.

**Comment by eseidelGoogle** [comment]
Both could see the device with `adb devices` and `flutter devices`.  ivan had ANDROID_HOME set in his shell, gilad did not.  Command-R still ran successfully for both.

**Comment by iposva-google** [comment]
> /Users/iposva/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:26 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
eager_span_scanner.dart:70 info • plugin: logging level: INFO
eager_span_scanner.dart:70 info • plugin: activated
eager_span_scanner.dart:70 info • flutter.sdk: Using Flutter SDK at /Sources/Flutter-Hack/flutter.
eager_span_scanner.dart:70 info • flutter_daemon: Starting Flutter daemon server
disposable.dart:30 flutter - info - activate
index.js:52 Window load time: 989ms
/Users/iposva/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:957 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
events.js:141 Uncaught Error: write EPIPE
eager_span_scanner.dart:70 info • projects: added project /Sources/Flutter-Hack/wispy_bird_9354
eager_span_scanner.dart:70 info • sdk: version 1.15.0-dev.3.0 (/Users/iposva/bin/dart-sdk)
eager_span_scanner.dart:70 info • changelog: dartlang version 0.6.0
SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
eager_span_scanner.dart:70 info • analysis-server: version 1.14.0
eager_span_scanner.dart:70 info • atom.run: Launching 'main.yaml: flutter, lib/main.dart, flutter: {route: null, debug: true, checked: true}'.
eager_span_scanner.dart:70 info • atom.observatory: Connected to observatory on ws://localhost:16227/ws.
eager_span_scanner.dart:70 info • atom.observatory: Connected to arm • Qualcomm MSM 8974 HAMMERHEAD (Flattened Device Tree) • Dart 1.15.0-edge
eager_span_scanner.dart:70 info • atom.run: Launching 'main.yaml: flutter, lib/main.dart, flutter: {route: null, debug: true, checked: true}'.
eager_span_scanner.dart:70 info • atom.observatory: Connected to observatory on ws://localhost:16228/ws.
eager_span_scanner.dart:70 info • atom.observatory: Connected to arm • Qualcomm MSM 8974 HAMMERHEAD (Flattened Device Tree) • Dart 1.15.0-edge

**Comment by devoncarew** [comment]
@iposva-google, if you point ANDORID_HOME to the other android sdk and restart atom, do you see the same issue?

**Comment by iposva-google** [comment]
I have removed the other adb binary without any success. It was just the adb binary without any Android SDK associated with it.

**Comment by eseidelGoogle** [comment]
This was a very common bug at the hackathon.  Not sure why.  I want to say 4-5 folks hit this?  It was easy to work around and not a lot of complaints.  Just common.

**Comment by devoncarew** [comment]
I'm still not clear on what's causing it, but I have a partial attempt to work around the issue. Will need to re-test on a user's machine to be sure :)

**Comment by devoncarew** [comment]
Marking as fixed; I was not able to repro locally - we can re-open as necessary.
