### ISSUE TITLE
Add stanim for intellij

### ISSUE THREAD

**Issue by BM2304** [flutter/flutter#19939]
There is no stanim completion in IntelliJ mit newest flutter and intellij like it says in the documentation:
Live Templates
Live templates can be used to speed up entering typical code structures. They are invoked by typing their ‘prefix’, and then selecting it in the code completion window:

IntelliJ live templates

The Flutter plugin includes the following templates:

Prefix stless: Create a new subclass of StatelessWidget.
Prefix stful: Create a new subclass of StatefulWidget and it’s associated State subclass.
Prefix stanim: Create a new subclass of StatefulWidget, and it’s associated State subclass including a field initialized with an AnimationController.

Sure can add it myself, which i did or do i need to update it in Android Studio ? 

Flutter upgrade:
Upgrading Flutter from C:\Flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (9 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running "flutter packages upgrade" in intro_animations...    9,4s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.165], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2018.2)
[!] VS Code, 64-bit edition (version 1.22.2)
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

**Comment by BM2304** [comment]
Yes exactly.
No there is no point in that.

**Comment by devoncarew** [comment]
Thanks for the report! @brianegan added this about a month ago: https://github.com/flutter/flutter-intellij/commit/1c326c5e316f975db402142c0198aa91dba88a23#diff-529f5cdd5def9e5ce3bd248d3a3b42e8 - it'll be out in the next release in a few days.
