### ISSUE TITLE
Intellij IDEA studio problems after latest update

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#19938]
After yesterday's update Intellij IDEA from version 18.1.3 to 18.2 (Build # IC-182.3684.101, build on July 24, 2018) in the editor hints for methods and properties of objects during editing have disappeared, as well as a "hot" error display. This applies to projects on both the dart and the flutter. Perhaps this is a problem with the settings of the editor, which can solve manually. Maybe someone can tell any? Just in case, the version of the dart plugin: 182.3569.4, flutter plugin is 26.03.

**Comment by zoechi** [comment]
Is this still an issue?
In this case please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
