### ISSUE TITLE
Browser certificate error accessing documentation

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1994]
I Googled MaterialPageRoute and it took me here
<img width="965" alt="screen shot 2016-02-18 at 11 05 28 am" src="https://cloud.githubusercontent.com/assets/394889/13154799/9a675282-d62f-11e5-9295-c220fe0e8593.png">

**Comment by eseidelGoogle** [comment]
@sethladd would know.  @jason-simmons may have worked on our SSL iirc.

**Comment by sethladd** [comment]
hm, that's surprising. Google is making a weird assumption here. This is the problem with hosting our docs directly on Google Cloud Storage, which can't do both custom domains + SSL.

**Comment by eseidelGoogle** [comment]
We now host on Firebase.
