### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by rohit0101rm** [flutter/flutter#19943]
C:\Users\nEW u>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 1ed25ca7b7e3e3e8047df050bba4174074c9b336...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...                               20.2s
Downloading package sky_engine...                            9.8s
Downloading common tools...                                 196.2s
Downloading windows-x64 tools...                            11.3s
Downloading android-arm-profile/windows-x64 tools...         5.6s
Downloading android-arm-release/windows-x64 tools...         3.6s
Downloading android-arm64-profile/windows-x64 tools...       3.2s
Downloading android-arm64-release/windows-x64 tools...       4.8s
Downloading android-x86 tools...                            66.4s
Downloading android-x64 tools...                            62.6s
Downloading android-arm tools...                            20.7s
Downloading android-arm-profile tools...                    15.5s
Downloading android-arm-release tools...                    27.9s
Downloading android-arm64 tools...                          28.2s
Downloading android-arm64-profile tools...                  12.4s
Downloading android-arm64-release tools...                   6.8s
Downloading Gradle Wrapper...                                4.1s
Doctor summary (to see all details, run flutter doctor -v):
CreateProcessW failed 193

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: b05c99056d01c846)
CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Android\Android Studio\jre\bin\java.EXE -version

**Comment by rohit0101rm** [comment]
can anyone help me resolve this??

**Comment by zoechi** [comment]
Thanks @ebeem 
Probably also a dup of #18938 (which is still open)

**Comment by zoechi** [comment]
I'm closing this as dup of #18938
