### ISSUE TITLE
NoSuchMethodError: The method 'update' was called on null.

### ISSUE THREAD

**Issue by liuhuanhui** [flutter/flutter#19948]
```
NoSuchMethodError: The method 'update' was called on null.
Receiver: null
Tried calling: update(bundle: Instance of '_ManifestAssetBundle', bundleDirty: false, bundleFirstUpload: false, dillOutputPath: null, fileFilter: Instance of '_CompactLinkedHashSet<String>', firstBuildTime: Instance of 'DateTime', fullRestart: false, generator: Instance of 'ResidentCompiler', mainPath: "/Users/huanhuiliu/flutter-demos/demo01/lib/main.dart", projectRootPath: "/Users/huanhuiliu/flutter-demos/demo01", target: "lib/main.dart")
```

```dart
import 'package:flutter/material.dart';
// import 'package:english_words/english_words.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    // final wordPair = new WordPair.random();
    return new MaterialApp(
      title: 'lucky',
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or press Run > Flutter Hot Reload in IntelliJ). Notice that the
        // counter didn't reset back to zero; the application is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        appBar: new AppBar(title: new Text("Lucky")),
        body:new Center(
          child: new Text("hello"),
        )
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by liuhuanhui** [comment]
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/huanhuiliu/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/huanhuiliu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices (1 available)
    • iPhone • 2f93e335c899a77347a239129621bfd40d8bb247 • ios • iOS 11.4.1

! Doctor found issues in 1 category.

@zoechi hello

**Comment by zsirfs** [comment]
using `flutter clean`, but not anything function. What is the solution?

**Comment by AngeloGiuseppe** [comment]
I hope this can help , I experienced this error when I edited the property `package` in the AndroidManifest.xml file 


`android\app\src\main\AndroidManifest.xml`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.project01">
```

Its seems that when you change that part you get the error, so just return it to its original name in the meantime
