### ISSUE TITLE
I'm getting an exception error in my code

### ISSUE THREAD

**Issue by rakz25** [flutter/flutter#19942]
I have a grid view with four buttons where I have commented it as of now. But doesn't matter its commented or not neway throw the error mentioned below.

I/flutter (23410): The following assertion was thrown building _ScrollableScope:
I/flutter (23410): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 221 pos 10: 'textDirection
I/flutter (23410): != null': is not true.
I/flutter (23410): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23410): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23410): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23410):   https://github.com/flutter/flutter/issues/new
I/flutter (23410): When the exception was thrown, this was the stack:
I/flutter (23410): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart)
I/flutter (23410): #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
I/flutter (23410): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
I/flutter (23410): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4289:28)
I/flutter (23410): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4768:11)
I/flutter (23410): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
I/flutter (23410): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (23410): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (23410): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (23410): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4667:14)
I/flutter (23410): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3666:16)
I/flutter (23410): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3508:5)
I/flutter (23410): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3635:5)
I/flutter (23410): #85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3782:11)
I/flutter (23410): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3630:5)
I/flutter (23410): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2920:14)
I/flutter (23410): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2723:12)
I/flutter (23410): #89     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
I/flutter (23410): #90     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
I/flutter (23410): #91     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
I/flutter (23410): #92     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (23410): #93     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
I/flutter (23410): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
I/flutter (23410): #95     runApp (package:flutter/src/widgets/binding.dart:704:7)
I/flutter (23410): #96     main (file:///Users/rakesh/Desktop/PracticeFluter/practice_flutter/lib/main.dart:4:16)
I/flutter (23410): #97     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
I/flutter (23410): #98     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter (23410): (elided 2 frames from class _AssertionError)
I/flutter (23410): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by rakz25** [comment]
Here is my code:

mport 'package:flutter/material.dart';


void main() => runApp(Category());

class Category extends StatefulWidget {
  State<StatefulWidget> createState() {
    return CategoryList();
  }
}

class CategoryList extends State<Category> {
  @override
// TODO: implement widget
  Widget build(BuildContext context) {
    return new Container(
      color: Colors.white30,
      child: new GridView.count(
        crossAxisCount: 4,
        childAspectRatio: 1.0,
        padding: const EdgeInsets.all(4.0),
        mainAxisSpacing: 4.0,
        crossAxisSpacing: 4.0,
        children: <Widget>[
          // new RaisedButton(
          //   child: new Text("LogIn"),
          //   color: Colors.blueAccent[600],
          //   onPressed: null,
          // ),
          // new RaisedButton(
          //   child: new Text("SignUp"),
          //   color: Colors.blueAccent[600],
          //   onPressed: null,
          // ),
          // new RaisedButton(
          //   child: new Text("SignUp"),
          //   color: Colors.blueAccent[600],
          //   onPressed: null,
          // ),
          // new RaisedButton(
          //   child: new Text("SignUp"),
          //   color: Colors.blueAccent[600],
          //   onPressed: null,
          // ),
        ],
      ),
    );
  }
}

**Comment by jonahwilliams** [comment]
You need to provide a TextDirection in order to render text and display other widgets that vary between LTR and RTL.  This value is determined from the user locale when using WidgetsApp or MaterialApp.  If the widget in `runApp` isn't one of these, you need to provide one with the Directionality widget.

Example:

```dart

runApp(new Directionality(textDirection: TextDirection.ltr, child: ...));
```

**Comment by rakz25** [comment]
Thanks .
