### ISSUE TITLE
TextField interaction under StreamBuilder

### ISSUE THREAD

**Issue by DarshanGowda0** [flutter/flutter#19950]
### Steps to Reproduce

1. Create a Scaffold with a Navigator.push on any on-clicks to move to next screen. 
2. On the second screen, use a streamBuilder and have TextField as one of the children down the widget tree.
3. Clicking or interacting with the textField which makes the keyboard pop-up or pop-out will trigger the stream call every time. 

```dart
    
    import 'package:flutter/widgets.dart';
    import 'package:flutter/material.dart';
    import 'dart:async';

    
    void main() {
      runApp(new MaterialApp(home: new Home()));
    //  runApp(new MaterialApp(home: new EditProfileInformation()));
    }
    
    class Home extends StatefulWidget {
      @override
      _HomeState createState() => _HomeState();
    }
    
    class _HomeState extends State<Home> {
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: Container(),
          floatingActionButton: FloatingActionButton(onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => EditProfileInformation()),
            );
          }),
        );
      }
    }
    
    class EditProfileInformation extends StatefulWidget {
      @override
      EditProfileInformationState createState() {
        return new EditProfileInformationState();
      }
    }
    
    class EditProfileInformationState extends State<EditProfileInformation> {
      Stream<String> dbCall;
      final StreamController _controller = new StreamController<String>();
      final myController = TextEditingController();
    
      @override
      void initState() {
        super.initState();
        dbCall = _controller.stream;
        myController.addListener(_printLatestValue);
        new Future<void>.delayed(const Duration(seconds: 1)).then((_) {
          _controller.add('streaming');
        });
      }
    
      void _printLatestValue() {
        print("text field: ${myController.text}");
      }
    
      @override
      void dispose() {
        myController.removeListener(_printLatestValue);
        myController.dispose();
        super.dispose();
      }
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: new AppBar(
            title: const Text(
              'Edit profile',
            ),
          ),
          body: new StreamBuilder<String>(
              stream: dbCall,
              builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
                if (snapshot.connectionState == ConnectionState.active) {
                  print(snapshot.data);
                  return new Container(
                    child: new Column(
                      children: <Widget>[
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: TextField(
                            controller: myController,
                          ),
                        ),
                        new Text(snapshot.data.toString()),
                      ],
                    ),
                  );
                } else if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: const CircularProgressIndicator());
                } else {
                  return Center(
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: const <Widget>[
                        Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: const Icon(Icons.error),
                        ),
                        Text('Error loading data')
                      ],
                    ),
                  );
                }
              }),
          floatingActionButton: FloatingActionButton(
            onPressed: () {
    //          _controller.add('streaming...');
            },
            child: const Icon(Icons.done),
          ),
        );
      }
    }
     
```

Some observations, 
1. Can't reproduce this if I use it as the first widget called from runApp(), only happens If I navigate to this page. (Comment the first line in main() and uncomment the second line)
2. Can't reproduce on emulators with virtual keyboards disabled.
3. Doesn't happen with any other widgets which doesn't require keyboard. 
## Flutter Doctor Logs

```
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.14 18A336e, locale en-GB)
    • Flutter version 0.5.7 at /Users/darshangowda/Development/flutter
    • Framework revision 66091f9696 (3 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/darshangowda/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L201y
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • ONEPLUS A5000 • b9c5ee65 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
I think that's a dup of #18828

**Comment by DarshanGowda0** [comment]
Not related to #11659 as textEditingController is just created once and used as shown in the [docs](https://flutter.io/cookbook/forms/text-field-changes/).
Extension of #18828 as mentioned in the code, the stream calls are made because of keyboard pop-up/pop-down.

**Comment by DarshanGowda0** [comment]
Possibly similar to #11426 with AppBar or FAB.
@Hixie Can I draw your attention towards this ?

**Comment by Hixie** [comment]
I don't understand the problem description here.

**Comment by DarshanGowda0** [comment]
> I don't understand the problem description here.

The stream is being called again and again everytime the keyboard pops up or pops out.

**Comment by zoechi** [comment]
> Doesn't happen with any other widgets which doesn't require keyboard.

When the keyboard pops up MediaQuery causes rebuilds of the whole page for `build()` to be able to update according to the now available size.
This causes `class EditProfileInformation extends StatefulWidget {` to be rebuild and with that `final StreamController _controller = new StreamController<String>();` and `new StreamBuilder<String>(`
that of course causes `StreamBuilder` to subscribe again.
I'd start with moving out `new StreamController` from the widget hierarchy into an model layer to make its lifecycle independent of the widgets lifecycles.

**Comment by DarshanGowda0** [comment]
StreamController was used to emulate the behaviour of the stream, in practical applications its one of the Firestore streams that it's subscribed to. Is there an example or any documentation of how to move out the Firestore streams to model layer ? and not directly use them with stream-builders ?

**Comment by eyoeldefare** [comment]
Yeah, unfortunately the FutureBuilder seem to be called everytime I press on the TextFormField input to edit the initial value I have provided from database.

**Comment by eyoeldefare** [comment]
This solved my issue. 
https://stackoverflow.com/questions/51224420/flutter-switching-to-tab-reloads-widgets-and-runs-futurebuilder

**Comment by marianoarga** [comment]
@zoechi I have a similar issue:
In MainScreen build method I make use of MediaQuery, in order to know the users device width.
Next, MainScreen render another widget, that has a StremBuilder with a TextField that makes use of the strem snapshot.data.
The entire tree is rebuilding itself when the keyboard shows up and or hides if I keep using Mediaquery on the MainScreen Widget, and works fine if I remove that. also tried disabling emulator's keyboard, the app works fine without keyboard... I think is directly related to the MediaQuery->keyboard logic you mention.
Hoy can I make use of MediaQuery size without expecting the keyboard to rebuild my widget tree?

**Comment by marianoarga** [comment]
@zoechi It seems that I have to make classes for every widget I need MediaQuery logic on, so they will be rebuild when the keyboard shows up, and not the "parent" main widget, we can't avoid the keyboard triggering the rebuild of "MediaQueried" widgets right?

**Comment by zoechi** [comment]
@DarshanGowda0 is this still an issue?

**Comment by DarshanGowda0** [comment]
@zoechi Yes, I can still reproduce this issue as mentioned in the earlier comments!

**Comment by cjs10lib** [comment]
Checkout this [https://stackoverflow.com/questions/50295726/widget-rebuild-after-textfield-selection-flutter/54421953#54421953](url) i think its related

**Comment by zoechi** [comment]
@marianoarga seems I missed your comment. No you can't prevent rebuild. You can only ensure `build()` doesn't break the behavior by passing the same `TextEditingController` instance to the `TextField`.

**Comment by zoechi** [comment]
Actually I'm still not sure what exactly the problem is. It's just how builders and build work. 
I'm going to close as working as intended.

**Comment by cjs10lib** [comment]
> @cjs10lib I don't understand how this is related! The issue has nothing to do with having a parent and child stateful widget.

Maybe not. I faced similar issues where my form rebuilds (which is a child widget nested in a blocBuilder similar to the stream builder) on clicking on a textfield widget using this package [https://pub.dartlang.org/packages/bloc](url) which implements the bloc pattern and i resolved it following the post.

**Comment by DarshanGowda0** [comment]
@zoechi and @cjs10lib The main problem as in the title is the multiple calls to the stream because of the rebuilds. Because of this **multiple calls** everytime the keyboard pops-up or down, a firestore stream keeps making document reads, which is pretty expensive! @zoechi do you have a workaround where the stream is not subscribed every time the keyboard appears or disappears?

**Comment by zoechi** [comment]
Perhaps you should build your stream so that it takes the result from a cache when available and only makes the request to the server if not. 
I think this should better be asked on StackOverflow.

**Comment by praneethfdo** [comment]
I do have the same issue.. When ever keyboard popups the stream is subscribed again which streams data it have streamed before.. How to avoid building the stream builder when widget tree rebuilds

**Comment by CubeRoshan** [comment]
Have same issue.How to avoid building the stream builder when widget tree rebuilds ?

**Comment by praneethfdo** [comment]
My workaround was to create a new list and  listen to stream outside the build method and append items received from streambuilder to the new list.
`
   Ws.getStream().stream.listen((data) {
      Message message = Message.fromJson(JSON.jsonDecode(data));

      if (widget.friend.id == message.from || widget.friend.id == message.to) {
        setState(() {
          list.insert(0, message);
        });
      }
    });
  }
`

**Comment by DhruvamSharma** [comment]
This issue is still popping up in my application. Any way to solve it?

**Comment by WD-J** [comment]
Still having this issue too.

**Comment by Hixie** [comment]
Please don't comment on closed bugs, closed bugs don't come up in our triage meetings. Just file a new bug starting at https://github.com/flutter/flutter/issues/new/choose and fill out all the information the template suggests.

**Comment by gossiks** [comment]
For those, who come here from google search.
Don't use StreamBuilder in this scenario.
Just manually create stream and apply changes in **async** listen function.
For reference see this repo https://gitlab.com/otsoaUnLoco/animated-stream-list
P.S. Or just use mentioned library for lists, it is great!

**Comment by JayM96** [comment]
Can anyone suggest a solution at my [stackoverflow ](https://stackoverflow.com/questions/53869795/flutters-automatickeepaliveclientmixin-doesnt-keep-the-page-state-after-naviga) I am facing similar issue related to pageState when multiple streambuilders are used.

@zoechi Please take a look.

Thanks.

**Comment by erperejildo** [comment]
I have the same issue: https://stackoverflow.com/questions/59073325/avoid-streambuilder-refreshing-running-setstate-in-flutter

**Comment by cacard** [comment]
mark
