### ISSUE TITLE
url_launcher on iOS has tap transparency on the top bar

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#19951]
1. create scaffold with appBar and ListView for a body
2. add enough list items to be able to scroll down
3. use URL launcher on iOS
4. scroll down on the website
5. tap the native browser AppBar to scroll to home
6. go "back" to your app

At this point, you should notice that the ListView scrolls to home as if it's own appBar has been tapped

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/733. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
It doesn't seem to be related to firebase

**Comment by TahaTesser** [comment]
Hi @lukepighetti 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you

**Comment by lukepighetti** [comment]
@TahaTesser This issue was moved when it shouldn't have been.
