### ISSUE TITLE
We should document main.yaml launch config (and link to docs in the default one)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1995]
It's not at all clear to me what these options do.  Specifically `debug` vs. `checked`.  @devoncarew 

![screen shot 2016-02-18 at 11 19 16 am](https://cloud.githubusercontent.com/assets/11857803/13155219/92f30d64-d631-11e5-8933-df1cf54a0f67.png)

**Comment by Hixie** [comment]
or just put comments in the file

**Comment by eseidelGoogle** [comment]
Atom is no longer our recommended editor.
