### ISSUE TITLE
Feature request: can we have widget size numbers in debug paint? 

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#19969]
In terminal of `flutter run`, press `p` toggles debug painting. I hope the debug painting can print the width and height numbers for all widgets too (including the screen's width and height numbers). That will be much easier for debug. Thanks a lot.

**Comment by timsneath** [comment]
Thanks for the feature request. Closing this now that we have the new [Layout Explorer feature](https://flutter.dev/docs/development/tools/devtools/inspector#flutter-layout-explorer), which should provide the information you're looking for (and a lot more besides!)
