### ISSUE TITLE
Issue from website page Get Started: Test Drive

### ISSUE THREAD

**Issue by gravitymedianet** [flutter/flutter#19962]
From URL: https://flutter.io/get-started/test-drive/

When creating a new project, how do I find the flutter path?

**Comment by zoechi** [comment]
When you install Flutter you have to specify a directory. For example set the current directory before you run `git clone`. 
How did you install Flutter? 
When you execute `flutter doctor -v` in a command line shell/terminal window, what output do you get?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
