### ISSUE TITLE
No pubspec.yaml found 

### ISSUE THREAD

**Issue by rakz25** [flutter/flutter#19973]
I my visual code I continue doing my work suddenly an error come 
```
flutter packages get
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.(very frequently)
```

What  I do is create a new project and replace all my files and modifying manifest xml,yaml file ,info list .  Is this the only solution and  continue repeating this ??

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

> What I do is create a new project and replace all my files and modifying manifest xml,yaml file ,info list . Is this the only solution and continue repeating this ??

This should definitely not be necessary but we need more information to be able to reproduce.

> flutter packages get
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.

Is this the full output?
What does happen if you execute 

```
flutter packages get
```
from a command line shell instead of from VSCode?

**Comment by rakz25** [comment]
Yes from terminal of VSCode and yes again its's the full output . I am not
able to put up a screen shot now since I have already repeated the same
traditional way by creating and replacing files .
I have tried flutter doctor too but the the error doesn't seem to go.

**Comment by DanTup** [comment]
The code that outputs this error only does a basic check to see whether there's a `pubspec.yaml` in the current folder. It's very easy to get this if you've `cd`'d into a sub-folder of your project:

```
dantup-macbookpro:flutter_gallery dantup$ flutter packages get
Running "flutter packages get" in flutter_gallery...         0.8s

dantup-macbookpro:flutter_gallery dantup$ cd lib/

dantup-macbookpro:lib dantup$ flutter packages get
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

When you see this again, you should check the folder that you're running it from (you can run `pwd` (or `cd` on Windows) in the terminal to get the full path). If you believe you're running it from the right place (the root of your Flutter project), you should run `ls pubspec.yaml` (or `dir pubspec.yaml` on Windows) in the same terminal to verify whether the file is there.

**Comment by rakz25** [comment]
Yes, Initially,  I have tried that too export PATH and setting up a path
variable , ls, echo $PATH which shows the correct path ex:if my flutter sdk
is in downloads, /users /name/downloads /flutter /bin :
But sometimes it shows a wrong suddenly
/users/name/downloads/bin:documents/flutter/bin:/usr/bin:
Such weird path but when I quit editor, and run my commands it shows the
correct path but error still remains which ultimately provokes me too go
through such activities like creating a new project and replacing.
Thank you for the support.

**Comment by rakz25** [comment]
These are screenshots : My flutter project is in desktop and flutter sdk is
in downloads:

**Comment by DanTup** [comment]
@rakz25 No screenshots came through with your last message (not sure if GitHub doesn't handle them from emails or if you forgot to attach?)

**Comment by rakz25** [comment]
I have attached it but not showing in GitHub

**Comment by DanTup** [comment]
@rakz25 You need to run those commands in the same VS Code Terminal window where you saw the error message.

Some other potential issues though:

1. You're possibly on an outdated version of Flutter (please post `flutter --version`)
2. VS Code has not detected your project as a Flutter project (it shows `Dart: 1.24.3` in the status bar). Can you confirm which folder you're opening in VS Code? It should be the root of your Flutter project. If it is, then it seems like you may be missing your `pubspec.yaml` file?

**Comment by rakz25** [comment]
Well to be frank: These are the simple steps I followed
1) I created a new project (app_project ex:)

2) Then created a new folder on my desktop (AppFolder -> app_project)

3) When I open VSCode (Goto : Open Folder -> Select -> AppFolder -> Open)

4) Starts analyzing.......
5)Now then it starts well and fine but no idea it sudenly gets the
pubspec.yaml error . Where am I going wrong exactly ? I have tried those
commands on editor terminal too.

**Comment by rakz25** [comment]
Flutter Version:

flutter --version
Flutter 0.5.8-pre.187 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 12eff1d5da (6 hours ago) • 2018-07-31 08:05:24 +0100
Engine • revision af855e063a
Tools • Dart 2.0.0-dev.69.4.flutter-08f59e5de3

**Comment by DanTup** [comment]
You should open the project folder in VS Code, so if `app_project` is the folder that contains a `pubspec.yaml` then that's the folder you want to open in VS Code.

It is possible to open a parent folder (eg. if you have multiple sub-projects) but there are some complications so if you have only one project, you're better open its folder directly.

If you do this correctly, you'll see the Flutter version in the status bar, which will enable functionality you're not currently getting (like fetching packages when you save the pubspec, allowing you to press F5 to run (inc. launching emulators), Flutter-specific snippets and commands in the Palette).

**Comment by rakz25** [comment]
Well I got it ! Thank you so much. Thanks a lot

**Comment by DanTup** [comment]
Great!

You shouldn't need to use the terminal directly so much now, a lot of the Flutter commands appear in the VS Command Palette (and run/debug is handled with F5). If you hit any issues specifically with the VS Code integration, open issues over at https://github.com/Dart-Code/Dart-Code and I'll pick them up.

**Comment by olisteadman** [comment]
@rakz25 what was the adjustment you made to get this working? I have encountered the same issue of flutter's not being able to see my pubspec.yaml file:
<img width="570" alt="screen shot 2019-02-11 at 21 45 24" src="https://user-images.githubusercontent.com/12253176/52596480-4fa13a00-2e48-11e9-97ad-23be9bbc031b.png">

... and I can't elucidate from the comments above, what you did to finally get it working. Any help hugely appreciated.

**Comment by olisteadman** [comment]
I can confirm that I've now solved this, by simply deleting the subdirectory `/Users/oliversteadman/AndroidStudioProjects/nanny/example` which, for some reason it'd be good to understand, flutter seemed to be jumping into when running `flutter packages get`.

The only file inside that subdir was `example.dart` a basic template file, so it's not a big deal. 
But it seems like we are restricted to not having any subdir's named `example` (and maybe other names?). @DanTup is this expected/documented behaviour?

**Comment by DanTup** [comment]
@olisteadman My guess is that `flutter packages get` is set up to also work for your example project (which is news to me, since in VS Code I handle this manually - I'll make a note to check). I think it's expected that *if* you have an example folder, it contains a pubspec (I guess it's supposed to be a whole sample project, so needs to list its dependencies).

**Comment by irenejohn997** [comment]
This is the error i get when i run flutter packages get,please somebody should help me,i have been on this for the past 1 month now
![Screenshot (24)](https://user-images.githubusercontent.com/41710028/74731383-292a9180-5248-11ea-9226-988dcccf560e.png)

**Comment by Giridharaan1705** [comment]
> I my visual code I continue doing my work suddenly an error come
> 
> ```
> flutter packages get
> Error: No pubspec.yaml file found.
> This command should be run from the root of your Flutter project.
> Do not run this command from the root of your git clone of Flutter.(very frequently)
> ```
> 
> What I do is create a new project and replace all my files and modifying manifest xml,yaml file ,info list . Is this the only solution and continue repeating this ??

First open the command prompt and create your project and then open your project in vs code and then run in vs code it will work it seems
