### ISSUE TITLE
onScaleStart event delayed

### ISSUE THREAD

**Issue by ppyupp** [flutter/flutter#19972]
I am developing a picture zoom viewer, but i found is the `onScaleStart` event delayed, not immediately...

is a bug?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ppyupp** [comment]
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.7 at /usr/local/opt/flutter
    • Framework revision 66091f9696 (3 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/ppyupp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /Users/ppyupp/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • iPhone 7 • 19B5F437-3FBD-4906-BA2D-539FBDF9F552 • ios • iOS 11.4 (simulator)

• No issues found!

**Comment by ppyupp** [comment]
I also ran this code:
https://github.com/perlatus/flutter_zoomable_image

When zooming the image, it does not respond immediately, but the two fingers slide out a certain distance before responding.

**Comment by ppyupp** [comment]
GestureDetector(
    onScaleStart: onScaleStart,
    onScaleUpdate: onScaleUpdate,
    onScaleEnd: onScaleEnd,
    onTap: onTap,
    ......
);

I found that if both onTap and onScaleStart are set,
onScaleStart event delayed....

**Comment by iapicca** [comment]
Hi @ppyupp 
I tested this 
<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

  void main() => runApp(MyApp());

  class MyApp extends StatelessWidget {  
    @override
    Widget build(BuildContext context) => MaterialApp(
      home: MyHomePage(),
    );
  }

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String get _now => DateTime.now().toString();
  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: GestureDetector(
        onScaleStart: (_) => print('[ $_now ] onScaleStart'),
        onScaleUpdate: (_) => print('[ $_now ] onScaleUpdate'),
        onScaleEnd: (_) => print('[ $_now ] onScaleEnd'),
        onTapDown: (_) =>  print('[ $_now ] onTapDown'),
        child: Container(
          height: 400,
          width: 400,
          color: const Color.fromRGBO(0, 0, 255, 1),
  ),),),);
}
```

</details>

with the latest master
<details>
  <summary>flutter doctor -v</summary>
```console
[✓] Flutter (Channel master, v1.18.0-5.0.pre.46, on Mac OS X 10.15.4 19E266, locale en-EE)
    • Flutter version 1.18.0-5.0.pre.46 at /Users/nevercode/development/flutter_master
    • Framework revision 0d459f2326 (6 hours ago), 2020-04-08 21:32:25 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```
</details>
and I don't experience the lag you are describing
both on web and mobile

I'm closing the issue as solved,
if you disagree please write in the comments and I will reopen it
Thank you
