### ISSUE TITLE
Flutter overlapped FlatButton is pressed together

### ISSUE THREAD

**Issue by hyochan** [flutter/flutter#19974]
I want my button to be clicked independently in `Stack`.
However they are pressed together. I've captured the [CLIP](https://firebasestorage.googleapis.com/v0/b/foodieon-292ad.appspot.com/o/Flutter%20-%20Flatbuttons%20clicked%20together..mov?alt=media&token=f3febc0f-0614-4763-b1dd-ad7210f36199) for clear understanding.

And here is my sourcecode:

```dart
FlatButton(
  onPressed: () {
    print('profile image pressed');
  },
  padding: EdgeInsets.all(0.0),
  child: Stack(
    children: <Widget>[
      Container(
        child: Image(
          image: Theme.Images.testProfile,
        ),
      ),
      Positioned(
        right: 0.0,
        bottom: 0.0,
        width: 36.0,
        height: 36.0,
        child: FlatButton(
          onPressed: () {
            print('camera icon pressed');
          },
          padding: EdgeInsets.all(0.0),
          child: Container(
            child: Image(
              image: Theme.Icons.icCameraOrange,
            ),
          ),
        ),
      ),
    ],
  ),
),
```

**Comment by jonahwilliams** [comment]
Hi @dooboolab, please include the results of `flutter doctor -v` so we know the exact version of flutter you are running.

**Comment by dooboolab** [comment]
@jonahwilliams Sorry I've missed that.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @hyochan 
I've tested your code (with minimal changes) on both mobile and 

<details>
  <summary>code</summary>

```dart 
import 'package:flutter/material.dart';

  void main() => runApp(MyApp());

  class MyApp extends StatelessWidget {  
    @override
    Widget build(BuildContext context) => MaterialApp(
      home: MyHomePage(),
    );
  }

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
    void _snack(BuildContext context, String message) => Scaffold.of(context)
    .showSnackBar(SnackBar(content: Text(message),),);

  @override
  Widget build(BuildContext context) => Scaffold(
    body:  Builder(
      builder: (context) => Center(
      child: FlatButton(
      onPressed: () => _snack(context,'blue'),
      padding: EdgeInsets.all(0.0),
      child: Stack(
        children: <Widget>[
          Container(
            color: const Color.fromRGBO(0, 0, 255, 1),),
          Positioned(
            right: 0.0,
            bottom: 0.0,
            width: 36.0,
            height: 36.0,
            child: FlatButton(
              onPressed: () => _snack(context,'red'),
              padding: EdgeInsets.all(0.0),
              child: Container(
                color: const Color.fromRGBO(255, 0, 0, 1),
              ),
            ),
          ),
        ],
      ),
  ),),),);
}
```

</details>

with the latest master
<details>
  <summary>flutter doctor -v</summary>
[✓] Flutter (Channel master, v1.18.0-5.0.pre.46, on Mac OS X 10.15.4 19E266, locale en-EE)
    • Flutter version 1.18.0-5.0.pre.46 at /Users/nevercode/development/flutter_master
    • Framework revision 0d459f2326 (6 hours ago), 2020-04-08 21:32:25 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
</details>

and the issue appears to be fixed.

I'm closing the issue as solved
if you disagree please write in the comments and I will reopen it
Thank you
