### ISSUE TITLE
Flutter Firestore StreamBuilder Error

### ISSUE THREAD

**Issue by Daibaku0615** [flutter/flutter#19977]
I'm trying to get data from `firestore` by using `streambuilder` method like so.

 ```dart
 body: new StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance.collection('user').document(uid).collection('userInfo').document(uid).snapshots(),
        builder: (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) return new Center(child: new CircularProgressIndicator());
          if (snapshot.hasData) {
            return new Center(
            child: ListView(
              shrinkWrap: true,
              padding: EdgeInsets.only(left: 24.0, right: 24.0),
              children: <Widget>[
                new Column(
                  children: <Widget>[
                    new CircleAvatar(
                      backgroundColor: Colors.transparent,
                      radius: 48.0,
                      child: Image.asset('assets/logo.png'),
                    ),
                    new Padding(padding: const EdgeInsets.only(bottom: 20.0)),
                    new Text(snapshot.data['name'], 
                    style: new TextStyle(fontSize: 28.0)),
                    new Padding(padding: const EdgeInsets.only(bottom: 35.0)),
                  ],
                ),
                new Column(
                  children: <Widget>[
                    new Row(
                      children: <Widget>[
                        new Column(
                          children: <Widget>[
                            new Icon(
                              Icons.accessibility,
                              size: 18.0,
                            ),
                            new Text('Age',
                                style: new TextStyle(
                                    fontSize: 12.0, color: Colors.blue)),
                          ],
                        ),
                        new Padding(
                            padding: const EdgeInsets.only(right: 16.0)),
                        new Text(snapshot.data['age'].toString(), style: new TextStyle(fontSize: 25.0)),
                      ],
                    ),
                    new Padding(padding: const EdgeInsets.only(top: 3.0)),
                    new Divider(color: Colors.grey, height: 1.0),
                    new Padding(padding: const EdgeInsets.only(bottom: 25.0)),
                    new Row(
                      children: <Widget>[
                        new Column(
                          children: <Widget>[
                            new Icon(
                              Icons.place,
                              size: 18.0,
                            ),
                            new Text('State',
                                style: new TextStyle(
                                    fontSize: 11.0, color: Colors.blue)),
                          ],
                        ),
                        new Padding(
                            padding: const EdgeInsets.only(right: 16.0)),
                        new Text(snapshot.data['state'], style: new TextStyle(fontSize: 25.0)),
                      ],
                    ),
                    new Padding(padding: const EdgeInsets.only(top: 3.0)),
                    new Divider(color: Colors.grey, height: 1.0),
                    new Padding(padding: const EdgeInsets.only(bottom: 25.0)),
                    new Row(
                      children: <Widget>[
                        new Column(
                          children: <Widget>[
                            new Icon(
                              Icons.audiotrack,
                              size: 18.0,
                            ),
                            new Text('Hobby',
                                style: new TextStyle( fontSize: 11.0, color: Colors.blue)),
                          ],
                        ),
                        new Padding(
                            padding: const EdgeInsets.only(right: 16.0)),
                        new Text(snapshot.data['hobby'], style: new TextStyle(fontSize: 26.0)),
                      ],
                    ),
                    new Padding(padding: const EdgeInsets.only(top: 3.0)),
                    new Divider(color: Colors.grey, height: 1.0),
                  ],
                ),
                new SizedBox(height: 45.0),
                new RaisedButton(
                  child: new Text('New Request',
                      style:
                          new TextStyle(color: Colors.white, fontSize: 20.0)),
                  color: Colors.blueAccent,
                  splashColor: Colors.blueGrey,
                  onPressed: () {
                    _toNewRequest();
                  },
                ),
              ],
            ),
          );
        } else {
            return new Center(
              child: new Text('You havent set profile'),
            );
          }
        },
      ),
```

but error says this

     
 

> flutter: The following NoSuchMethodError was thrown building
>  StreamBuilder<DocumentSnapshot>(dirty, state: flutter:
>  _StreamBuilderBaseState<DocumentSnapshot, AsyncSnapshot<DocumentSnapshot>>#f91a2) The method '[]' was
> called on null.  Receiver: null Tried calling:[] ("name")

but if I refresh(restart maybe) the app, click the green arrow,
![2018-07-30 11 26 46](https://user-images.githubusercontent.com/41893584/43384614-851408b2-9419-11e8-8443-79e27675c74b.png)

then it shows data correctly.
why is this not working when app launches?

**Comment by zoechi** [comment]
What does it print when you add

```
 if (snapshot.hasData) {
   print('=== data ===: ${snapshot.data}');  // <<<== add this line
```

**Comment by Daibaku0615** [comment]
This is what printed `(=== data ===: Instance of 'DocumentSnapshot')`
And I noticed that console also printed this 
```
`The behavior for system Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
let db = Firestore.firestore()
let settings = db.settings
settings.areTimestampsInSnapshotsEnabled = true
db.settings = settings`
```
Is this something to do with the error?
Also `flutter doctor -v` returns command not found.
Thank you for your help!

**Comment by zoechi** [comment]
You need to configure the `PATH` environment variable for `flutter`
https://flutter.io/setup-windows/#update-your-path
for `flutter` commands to work.

**Comment by zoechi** [comment]
Please try the print again with
```
print('=== data ===: ${snapshot.data.data}');  // <<<== add this line - now with an additional `.data`
```

**Comment by Daibaku0615** [comment]
Printed this `flutter: === data ===: null`
but if I set some button and set `onPresed`  like so 
```
`if (snapshot.hasData) {
             print('=== data ===: ${snapshot.data.data}');
          }  return new Center(
            child: new FlatButton(
              child: new Text('press'),
              onPressed: () {
                print(snapshot.data.data);
              },
            ),
          );`
```

then `snapshot.data.data` is this `{age: 30, hobby: Music , state: Alabama , name: Myname}`
Also this is flutter doctor output `[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)`

**Comment by zoechi** [comment]
Seems you get an empty snapshot from Firebase at first and than in an additional event the data you expect
Please try

```dart 
if (snapshot.hasData && snapshot.data.data != null) {
```
I don't know this API and can't tell if this behavior is expected or not.

**Comment by Daibaku0615** [comment]
It also didn't work;( 
I also tired `(snapshot.connectionState == ConnectionState.active)` but neither.
Now I tried those 
`(snapshot.connectionState == ConnectionState.active && snapshot.data.data.isEmpty) 
  return new Center(child: new CircularProgressIndicator());
 if (snapshot.connectionState == ConnectionState.active && snapshot.data.data.isNotEmpty)
          print(snapshot.data.data)` 

then, it returns CircularProgressIndicator whole time till I refresh the app.

**Comment by Daibaku0615** [comment]
The problem was `uid`. I implement `setState` right after I get `uid` from `Firestore` it all worked.
So, I close this thank you so much for help zoechi!

**Comment by vinuvish** [comment]
> The problem was `uid`. I implement `setState` right after I get `uid` from `Firestore` it all worked.
> So, I close this thank you so much for help zoechi!

can you explain how to solve this issue im also getting the same issue

**Comment by thienanstudios** [comment]
> The problem was `uid`. I implement `setState` right after I get `uid` from `Firestore` it all worked.
> So, I close this thank you so much for help zoechi!


Can you explain this further, I am having the same problem.

**Comment by thienanstudios** [comment]
> > The problem was `uid`. I implement `setState` right after I get `uid` from `Firestore` it all worked.
> > So, I close this thank you so much for help zoechi!
> 
> can you explain how to solve this issue im also getting the same issue

Did you ever find out the solution?

**Comment by kroikie** [comment]
@ghost

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/732. Any further collaboration will be done there.

**Comment by JoshJavaBoy1** [comment]
> The problem was `uid`. I implement `setState` right after I get `uid` from `Firestore` it all worked.
> So, I close this thank you so much for help zoechi!

Please how did you do that. Can i see the corrected code

**Comment by deliciafernandes** [comment]
> The problem was `uid`. I implement `setState` right after I get `uid` from `Firestore` it all worked.
> So, I close this thank you so much for help zoechi!

implement setState where?

**Comment by SabirBugti** [comment]
Same issue any answer for me ??

**Comment by Khane1** [comment]
In order for the streambuilder to function you need the uid.
 
Initially on page run uid is null,  This is why @ghost receives error  until he reloaded later updating to the new 
value.
`Firestore.instance.collection('user').document(uid).collection('userInfo').document(`***null uid***`).snapshots(),`

So to get the uid up and running we need to use the initState function to first define the uid inside a setState Function.
 
For example;
void initState() {
setState((){
////define your uid /////
});
}
This means Immediately the page is loaded, initstate is triggered and then under setState the uid will be updated and saved.  In turn this makes it possible for the streambuilder to access the new updated uid.

`Firestore.instance.collection('user').document(uid).collection('userInfo').document(`***updated uid***`).snapshots(),`
I know this issue is closed but i also felt that it would help those who need the help since i also figured it out from here.
