### ISSUE TITLE
Can't search docs.flutter.io from a mobile browser

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#19988]
At least in Chrome on iOS (and presumably other mobile browsers) there is no search box on docs.flutter.io.

@mjohnsullivan @jcollins-g

**Comment by jcollins-g** [comment]
dart-lang/dartdoc#1348

**Comment by zoechi** [comment]
Same problem in https://flutter.io and https://docs.flutter.io

**Comment by zoechi** [comment]
dart-lang/dartdoc#1348 is fixed (landscape)
dart-lang/dartdoc/issues/1914 (portrait) is a new issue and still open

**Comment by zoechi** [comment]
Closing here because it's tracked in dart-lang/dartdoc now
