### ISSUE TITLE
Issue from website page Return data from a screen

### ISSUE THREAD

**Issue by evanzhoe** [flutter/flutter#19980]
From URL: https://flutter.io/cookbook/navigation/returning-data/

Small typo there (bolded):

4. When a button is tapped, close the selection screen
Now, we’ll want to update the onPressed callback for both of our buttons! In order to return data to the first screen, we’ll need to use the **Navitator.pop** method.

**Comment by Sfshaza** [comment]
Fixed on the dash branch. We aren't fixing bugs on master unless a P0.  Thanks!
