### ISSUE TITLE
docs.flutter.io scrolls incorrectly on mobile

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#19987]
If you load up docs.flutter.io in Chrome on iOS (and probably on Android or Safari as well) the scroll physics is all wrong.  Waaay to slow.  Maybe it's doing JavaScript based scrolling?

@mjohnsullivan @jcollins-g

**Comment by zoechi** [comment]
#21311 shows the behavior in a screen capture

**Comment by zoechi** [comment]
@Hixie @jcollins-g not sure about how to triage these api docs issues. 
This seems to be part of dartdoc and not part of flutter/website.
Perhaps just move to dart-lang/dart-doc?

**Comment by jcollins-g** [comment]
yes, moving to dartdoc esp. if it is not flutter specific is a good idea.  https://github.com/dart-lang/dartdoc/issues/1469 probably covers some aspects of this and is already linked.

**Comment by Hixie** [comment]
This is apparently iOS-specific.

**Comment by Hixie** [comment]
@jcollins-g The scroll physics are still an issue on iOS.

**Comment by markusaksli-nc** [comment]
Closing, as this seems fixed when testing on on Android Chrome and Firefox, and on IOS. Feel free to reopen if this is not the case.
