### ISSUE TITLE
The library com.google.firebase:firebase-iid is being requested by various other libraries at [[16.2.0,16.2.0]], but resolves to 16.0.0.

### ISSUE THREAD

**Issue by dbhowell** [flutter/flutter#19983]
Using the latest versions of `firebase_messaging` to a project, shared dependencies with other FlutterFire plugins (e.g. `cloud_firestore`) cause shared dependency version resolution issues and will no longer compile successfully.

## Steps to Reproduce
1. Create new flutter app (`flutter create test_fb`)
2. Add `firebase_messaging: ^1.0.4` and `cloud_firestore: ^0.7.4` to pubspec.yaml
3. Add `classpath 'com.google.gms:google-services:4.0.1'` to `android/build.gradle`
4. Add `apply plugin: 'com.google.gms.google-services'` to `android/app/build.gradle`
5. Attempt to run on Android emulator `flutter run`

## Logs
```
The library com.google.firebase:firebase-iid is being requested by various other libraries at [[16.2.0,16.2.0]], but resolves to 16.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```

```
Analyzing message_test...                                        
No issues found! (ran in 2.7s)
```

```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at ...
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at ...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = ...
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at ...
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Similar to #19868

**Comment by RedTech64** [comment]
I'm having this same problem!

**Comment by dbhowell** [comment]
I can confirm that https://github.com/flutter/flutter/issues/19868#issuecomment-408550356 does fix the problem.

**Comment by AlejandroC90** [comment]
@dbhowell Solution worked for me too, Thank you

**Comment by blaneyneil** [comment]
the hack from #19868 does indeed work.   though i found you have to put it after the `apply plugin: 'com.google.gms.google-services'` line.  @JSANL i was then going crazy with the same problem you had, until in app/build.gradle i upped the min sdk version to 21:
           
```
defaultConfig {
        minSdkVersion 21
        targetSdkVersion 27
        ...
}

```

**Comment by rlee1990** [comment]
This didn't work for me at all. I keep getting
`Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex`

**Comment by blaneyneil** [comment]
sorry, I meant it didn't solve for a problem with merging but rather removed the need to use `multiDexEnabled true` in the first place.  prior to SDK 21 i was getting an error that there were too many method names (I can't remember the exact message) even though I was only using about 10 plugins.

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/18579#issuecomment-398484148

**Comment by yashthakkar1173** [comment]
I have the same issue with firebase but it solved please refer this [link](https://stackoverflow.com/questions/52756049/gradle-issue-in-flutter-when-using-firebase) for more details!

**Comment by Aravindhan95** [comment]
Add this line at the very bottom of your app build.gradle file.

com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

**Comment by DaniilDem** [comment]
set `classpath 'com.google.gms:google-services:4.2.0'`
and `implementation "com.google.firebase:firebase-config:16.0.0"`
it is work for me

**Comment by iskakaushik** [comment]
Per https://developers.google.com/android/guides/releases#may_23_2018, if you are using older versions of firebase deps which use version ranges with a newer version of `com.google.gms:google-services` it could create version incompatibility problems.

Please use a newer version of firebase deps if you wish to use newer version of `com.google.gms:google-services`. I've tried the following configuration successfully:

```
1.   firebase_messaging: ^3.0.1
      cloud_firestore: ^0.9.0+1

2. classpath 'com.google.gms:google-services:4.2.0'
```

Let me know if this does not solve your issue. Thanks!

**Comment by kroikie** [comment]
@dbhowell

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/731. Any further collaboration will be done there.
