### ISSUE TITLE
Atom on Linux: "View/Toggle Menu Bar" doesn't toggle

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1999]
Once the menu bar is toggled off, it will not come back.

The IDE keeps track of the togged state and posts a dialog that suggests hitting the "alt" key as an alternative way of toggling the menubar. That doesn't work since the Alt key is grabbed by the desktop.

An 'autoHideMenuBar: true' entry does seem come and go from  ~/.atom/config.cson.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
