### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#200]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [abarth](https://github.com/abarth)**
_Wednesday Oct 14, 2015 at 00:11 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1608_

----

We should come up with a design for how we want localization to work.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Oct 15, 2015 at 03:28 GMT_

----

What are the requirements?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 15, 2015 at 03:35 GMT_

----

We need to work with a customer to figure that out.

**Comment by sethladd** [comment]
@jason-simmons are there more plans here? Or is the integration with Dart's intl library a sufficient first step?

Thanks!

**Comment by jason-simmons** [comment]
I don't know of any plans for localization beyond use of the Dart intl library

**Comment by sethladd** [comment]
Sounds good! I'll close and we can open new issues for further functionality.

**Comment by eseidelGoogle** [comment]
We will need to fully localize an app to work out all the subtleties.  But having Stocks show that its possible is plenty for this bug.
