### ISSUE TITLE
Text message in iOS 

### ISSUE THREAD

**Issue by Kumuda123** [flutter/flutter#20014]
Is there a way I can implement SMS Notifications in iOS ? 
https://pub.dartlang.org/packages/sms#-readme-tab-
I tried using the sms package but it says that it only supports Android. Is there a way to send text message notifications in iOS apps ?

**Comment by zoechi** [comment]
You can delegate to native code in iOS as well. Just someone would need to implement it, like it was done for Android in the package you linked to.

**Comment by Kumuda123** [comment]
MissingPluginException(No implementation found for method send on channel Send SMS )- I get this error. I tried Flutter clean as well but it is still there. Is the call for the function right ??

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart';
//import 'package:sms/contact.dart';
import 'login_page.dart';
class SendSMS extends StatefulWidget{
_SendSMS createState() => new _SendSMS();
}
class _SendSMS extends State{
@override
static const platform = const MethodChannel('Send SMS ');
Future send()async {
print("SendSMS");
try {
**final String result = await platform.invokeMethod('send',<String,dynamic>{"msg":"Hello! I'm sent programatically."});**
} on PlatformException catch (e) {
print(e.toString());
}
}
Widget build(BuildContext context) {
// TODO: implement build

return new Material(
child : new Container(
alignment: Alignment.center,
child : new FlatButton(onPressed: send, child: new Text('send SMS '))
),
);
}
}

**Comment by Kumuda123** [comment]
Okay thanks

**Comment by Hixie** [comment]
I'm going to close this issue because we (the Flutter team) do not plan to write or maintain an SMS package. We would encourage anyone interested in such a package to work together to create one.
