### ISSUE TITLE
`centerSlice` doesn't work properly with resolution-aware image assets

### ISSUE THREAD

**Issue by luizgpa** [flutter/flutter#20013]
## Steps to Reproduce

1. Create an image to be used with `centerSlice`.
![border](https://user-images.githubusercontent.com/4613697/43427846-cc29a78a-9431-11e8-88fe-1ea48c8c52ba.png)
2. Show the image in a widget
```dart
          Image(
            image: AssetImage('assets/border.png'),
            centerSlice: Rect.fromLTRB(15.0, 15.0, 25.0, 25.0),
            height: 71.0,
            width: 190.0,
          ),
```
It works
![1x](https://user-images.githubusercontent.com/4613697/43427937-30b0003c-9432-11e8-9bb7-525efb10f2bd.png)
3. Add an image for higher pixel density devices. 
![border](https://user-images.githubusercontent.com/4613697/43428032-99a6d6ec-9432-11e8-9761-bb26a86a95da.png)
(I changed the color just to be sure the right image is shown.)
4. Run the same code in a device with higher pixel density.
![2x](https://user-images.githubusercontent.com/4613697/43428105-f57bc90a-9432-11e8-9261-a2fc2cf14c05.png) (200%)
Notice that the corners are blurred and don't fit the rest of the image.

If you multiply the `centerSlice` values by 2 the result is correct.
![2xok](https://user-images.githubusercontent.com/4613697/43428449-a98d38d8-9434-11e8-8639-1c667ac75a09.png)
Probably the code that handle centerSlice doesn't consider the 'real' image scale?

The code and images can be found here:
https://github.com/luizgpa/center_slice

Thanks

## Logs

flutter doctor -v
```
[√] Flutter (Channel master, v0.5.8-pre.179, on Microsoft Windows [Version 10.0.17134.165], locale pt-BR)
    • Flutter version 0.5.8-pre.179 at C:\Projects\flutter
    • Framework revision 711ecf7f58 (4 hours ago), 2018-07-30 12:35:15 -0700
    • Engine revision af855e063a
    • Dart version 2.0.0-dev.69.4.flutter-08f59e5de3

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by luizgpa** [comment]
One extra point, `DecorationImage` suffers from the same issue.

**Comment by rockingdice** [comment]
any updates on this? Can we show nine patch images with 2.0x or 3.0x?

**Comment by rockingdice** [comment]
maybe related to https://github.com/flutter/flutter/issues/18682, and there's already a PR: https://github.com/flutter/flutter/pull/20791

**Comment by rockingdice** [comment]
Never think this could be really easy to achieve!

It could be fixed by giving a transform to the canvas with 1.0/scale and make the destinationRect multiplied by its scale before rendering. Then it should be render correctly. Also, don't forget to save/restore the canvas state when doing all the canvas manipulations.

Correct result:
![image](https://user-images.githubusercontent.com/3458134/44704661-cb900b80-aace-11e8-89a3-eb7a1bca83e6.png)

**Comment by sir-boformer** [comment]
If it's related to #20791, maybe we can add the code to fix this issue as well? I created that PR. Or does the PR already fix this issue?

**Comment by rockingdice** [comment]
@sir-boformer 
Yes, we can fix this issue based on your PR with some more changes. I tried your PR but it doesn't fix this issue particularly.

I mentioned https://github.com/flutter/flutter/issues/18682 that might be related because this issue can be traced to the same place and some of your codes are needed. 

You might already notice there's a logic branch when checking the centerSlice if exists, the flutter libs don't handle resolution images in that situation as well. 

here are the changes:

Remove these lines which is using 'sliceBorder':
![image](https://user-images.githubusercontent.com/3458134/44763381-98f11c00-ab7d-11e8-8b7b-3b78e5586539.png)
* Removed sliceBorder related codes.

Modify these codes:
![image](https://user-images.githubusercontent.com/3458134/44763395-a8706500-ab7d-11e8-9556-28d77bef1a69.png)
* Removed sliceBorder related codes.
* added: 
`centerSlice = centerSlice.topLeft * scale & centerSlice.size * scale;`

Modify the codes rendering for the nine patch image:
![image](https://user-images.githubusercontent.com/3458134/44763468-fbe2b300-ab7d-11e8-8265-486f4eee39f7.png)
`   for (Rect tileRect in _generateImageTileRects(rect, destinationRect, repeat)) {
      canvas.save();
      canvas.scale(1.0/scale, 1.0/scale);
      tileRect = tileRect.topLeft * scale & tileRect.size * scale;
      canvas.drawImageNine(image, centerSlice, tileRect, paint);
      canvas.restore();
    }`

**Comment by Quanhua-Guan** [comment]
try  add scale value to Image widget
```
Image.asset(
            'images/mask32x32.png',
            centerSlice: Rect.fromLTWH(15.5, 15.5, 1, 1),
            scale: windowPixelRatio,/// window.devicePixelRatio  from dart:io window.dart
          )
```

**Comment by Quanhua-Guan** [comment]
> try add scale value to Image widget
> 
> ```
>          Image.asset(
>             'images/mask32x32.png',
>             centerSlice: Rect.fromLTWH(15.5, 15.5, 1, 1),
>             scale: window.devicePixelRatio, //  from dart:io window.dart
>           )
> ```

seems still not working, the image used is the 1x one

**Comment by Quanhua-Guan** [comment]
One possible solution: use 4 corner images to substitute the center sliced image.

**Comment by TahaTesser** [comment]
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Image(
            image: AssetImage('assets/border.png'),
            centerSlice: Rect.fromLTRB(15.0, 15.0, 25.0, 25.0),
            height: 71.0,
            width: 190.0,
            repeat: ImageRepeat.repeat,
          ),
          Container(
            decoration: BoxDecoration(
                image: DecorationImage(
              image: AssetImage('assets/border.png'),
              centerSlice: Rect.fromLTRB(15.0, 15.0, 25.0, 25.0),
            )),
            child: SizedBox(width: 190.0, height: 71.0),
          ),
        ],
      ),
    );
  }
}

```

</details> 

[assets.zip](https://github.com/flutter/flutter/files/5371906/assets.zip)

```
  assets:
    - assets/image.jpg
    - assets/border.png
    - assets/2.0x/border.png
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-14.0.pre.152, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-14.0.pre.152 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 62cf4dbf10 (7 hours ago), 2020-10-13 14:12:02 +0800
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7
      19H2 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!
```

</details>
