### ISSUE TITLE
Android race condition in TextInputPlugin caused by redundant update

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#20016]
I'm working on a rich text editor for Flutter and got  an issue described here: https://github.com/memspace/zefyr/issues/15

From my research it seems like it's caused by a race condition in TextInputPlugin itself and only affects Android.

Steps to reproduce:

1. Clone Zefyr repo and checkout this branch: https://github.com/memspace/zefyr/tree/android-text-input-race
2. Go to `packages/zefyr/example` folder and `flutter run` the example app in Android Simulator.
3. Tap "EDIT" on the home screen of the app
4. Put caret on the second line of quote block (under "BUG")
5. Clear console output, if in an IDE, or add a few empty lines if in CLI (helps later if there is no unrelated logs)
5. Press `Enter` to create a new line
6. Observe console output.

Even though the editor behaved correctly in this case you should see some error messages from Android side and several printed logs. I've added two `print` statements: [one in updateRemoveValue](https://github.com/memspace/zefyr/blob/android-text-input-race/packages/zefyr/lib/src/widgets/input.dart#L83) and the other [in updateEditingValue](https://github.com/memspace/zefyr/blob/android-text-input-race/packages/zefyr/lib/src/widgets/input.dart#L147)

Here is what I get in logs:

```
I/flutter ( 8381): <<< updateEditingValue TextEditingValue(text: ┤BUG
I/flutter ( 8381): 
I/flutter ( 8381): 
I/flutter ( 8381): ├, selection: TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter ( 8381): >>> updateRemoteValue: TextEditingValue(text: ┤BUG
I/flutter ( 8381): 
I/flutter ( 8381): ├, selection: TextSelection(baseOffset: 4, extentOffset: 4, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I/flutter ( 8381): <<< updateEditingValue TextEditingValue(text: ┤BUG
I/flutter ( 8381): 
I/flutter ( 8381): 
I/flutter ( 8381): ├, selection: TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
W/IInputConnectionWrapper( 8381): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 8381): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 8381): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 8381): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 8381): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 8381): endBatchEdit on inactive InputConnection
I/flutter ( 8381): <<< updateEditingValue TextEditingValue(text: ┤BUG
I/flutter ( 8381): 
I/flutter ( 8381): ├, selection: TextSelection(baseOffset: 4, extentOffset: 4, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
```

And here is decoded explanation of the above:

1. First `<<< updateEditingValue` occurs when I entered `\n`. This is OK, it updates local state to text `BUG\n\n\n\n` and caret position 5.
2. First `>>> updateRemoteValue` is sent by Zefyr to adjust remote value with text `BUG\n\n\n` (one less line-break) and caret position 4. This is expected. Note that this happens within the same frame (synchronous).
3. Second `<<< updateEditingValue` with the same values as (1). **This is unexpected**. It should've sent new values from (2).
4. Third `<<< updateEditingValue` with the new values, this is expected.

I must note that I get different outputs if I use on screen keyboard instead of physical keyboard on my host machine. With on screen keyboard I only see log records 1 and 2. Which is actually expected, this means that in response to (2) remote side sent correct update but it was discarded as being identical to current local state.

But I can still see `InputConnectionWrapper` errors from Android side even with on screen keyboard.

I looked at implementation of `TextInputPlugin` for Android but couldn't find where things go wrong. Looking for some help getting this fixed.

Here is a recording with me using physical keyboard to reproduce this issue:

![kapture 2018-07-30 at 17 38 51](https://user-images.githubusercontent.com/441756/43430789-919ce71a-941f-11e8-9fc7-9fce870967f6.gif)

**Comment by GaryQian** [comment]
Possibly related to https://github.com/flutter/flutter/issues/20144 ? Putting this here for reference.

**Comment by Drakirus** [comment]
Possibly related to https://github.com/flutter/flutter/issues/35848

**Comment by pedromassangocode** [comment]
Hi @pulyaevskiy 
Are you still facing this issue? If yess, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you
