### ISSUE TITLE
Dynamic attribute itemExtent in ListView

### ISSUE THREAD

**Issue by csnguyen-gmail** [flutter/flutter#20019]
Hi, below is my Flutter version

```
Flutter 0.5.8-pre.184 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3a6228bead (2 hours ago) • 2018-07-30 18:07:23 -0700
Engine • revision af855e063a
Tools • Dart 2.0.0-dev.69.4.flutter-08f59e5de3
```

I have a long heavy list is placed on a tab (I use `DefaultTabController`, not `CupertinoTabView`) and have a demand that the list have to be kept as last scrolling position when tab is reopened. 

It can be done with set `PageStorageKey` to `ListView`, but the problem is performance. Suppose the list is being at bottom of scrolling position, when tab reopen then all items of list have to be built and that affect to performance and make my application is slow.

I can solve if I set itemExtent value explicitly, but the problem is my row height is dynamic base on its content. Can I ask Flutter to support to able to set row height on demand base on item index like IOS `UITableViewController` mechanism? Some thing like:

```dart
ListView.builder（
　itemHeightBuilder: (int index) {
　　if (index % 2 ==0) {
　　　return oddHeight;
　　}
　　return evenHeight;
　},
),
```

Thank you!

**Comment by zoechi** [comment]
If the list usually is scrolled to the bottom, you probably want to use `reverse: true`

**Comment by csnguyen-gmail** [comment]
Thanks, I know about the `reverse`, I just want to take an example to describe about performance problem when change scroll position without setting `itemExtent`

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/24791#issuecomment-442566058 seems related

**Comment by goderbauer** [comment]
Is `reverse: true` fixing the issue for you? If not, what solution would you like to see in the framework?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
