### ISSUE TITLE
flutter atom plugin 'Run' should save (or at least prompt to save)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2001]
Not-having-saved-and-yet-running was a common confusion for several Dart team members when they set up Atom for the first time and tried to run their first Flutter app.

@devoncarew

**Comment by devoncarew** [comment]
Fixed here: https://github.com/dart-atom/dartlang/commit/dbf02a9bed6c7735e80bd175c4d10c1611d22f56. This will be available with the next release.
