### ISSUE TITLE
What's wrong with my Stack?

### ISSUE THREAD

**Issue by Icarus-Xu** [flutter/flutter#20023]
So here is the thing, I was following a demo about Stack and its children, and encountered some weird problem:
```dart
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Stack layout'),
      ),
      body: new Center(
        child: new Stack(
          children: <Widget>[
            new Image.network(
                'http://img2.cxtuku.com/00/13/12/s97783873391.jpg'),
            new Positioned(
              left: 35.0,
              right: 35.0,
              top: 45.0,
              child: new Text(
                'Whatever is worth doing is worth doing well',
                style: new TextStyle(
                  fontSize: 20.0,
                  fontFamily: 'serif',
                ),
              ),
            )
          ],
        ),
      ),
    );
```
So this code works good and the screen looked like this:
![screenshot_2018-07-31-14-45-27-673_cn icarus flutterdemo](https://user-images.githubusercontent.com/11155311/43442599-01de4ff8-94d1-11e8-9c1c-bdabd0bb20a7.png)

And I was satisfied, until I looked into the code and discovered that the `Positioned` widget is aligned according to the `Image`, not the `Stack`. To prove this, I deleted the `Image` and the screen looked like below:

![screenshot_2018-07-31-14-45-47-083_cn icarus flutterdemo](https://user-images.githubusercontent.com/11155311/43442732-65f62de4-94d1-11e8-8703-c4c31d4fb145.png)

well this makes more sense, as the `Positioned` aligns according to the `Stack`.

Weird things happened after I added the `Image` back and try to delete the alignment in the `Positioned` widget:

```dart
return new Scaffold(
      appBar: new AppBar(
        title: new Text('Stack layout'),
      ),
      body: new Center(
        child: new Stack(
          children: <Widget>[
            new Image.network(
                'http://img2.cxtuku.com/00/13/12/s97783873391.jpg'),
            new Positioned(
              top: 45.0,
              child: new Text(
                'Whatever is worth doing is worth doing well',
                style: new TextStyle(
                  fontSize: 20.0,
                  fontFamily: 'serif',
                ),
              ),
            )
          ],
        ),
      ),
    );
```
I was like ??? when I see the screen like below:

![screenshot_2018-07-31-14-46-19-249_cn icarus flutterdemo](https://user-images.githubusercontent.com/11155311/43442856-d6615784-94d1-11e8-92d7-9fe4b2571d1d.png)

Again I deleted the `top` alignment:

```dart
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Stack layout'),
      ),
      body: new Center(
        child: new Stack(
          children: <Widget>[
            new Image.network(
                'http://img2.cxtuku.com/00/13/12/s97783873391.jpg'),
            new Positioned(
              child: new Text(
                'Whatever is worth doing is worth doing well',
                style: new TextStyle(
                  fontSize: 20.0,
                  fontFamily: 'serif',
                ),
              ),
            )
          ],
        ),
      ),
    );
```

and I was like ???WTF??? when the screen changed to this:

![screenshot_2018-07-31-14-46-27-552_cn icarus flutterdemo](https://user-images.githubusercontent.com/11155311/43442947-1e10d9b0-94d2-11e8-9bc0-dba2d3732320.png)

What I don't get is:
1. Theoretically, the image shall be at the very center of the screen, and it was there until I deleted the `top` alignment, which is an attribute of `Positioned` not `Image`, why there is a difference?
2. Why the `Positioned` is aligned according to the `Image`?

**Comment by Icarus-Xu** [comment]
Additional comments to #2: in the third pic, I deleted the `left` and `right`, and the left side of the text is aligned to the left side of `Image`. There is another problem why the rest of the text is "cut" by something, idk why.
Am I doing this wrong?

**Comment by Icarus-Xu** [comment]
below is the output of `flutter doctor -v`
BTW I'm using Android Studio, so I guess problem in VS Code could be ignored
```
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale C)
    • Flutter version 0.5.1 at /home/icarus/Documents/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /home/icarus/Documents/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.0
    • ANDROID_HOME = /home/icarus/Documents/android-sdk
    • Java binary at: /home/icarus/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/icarus/Documents/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /home/icarus/Documents/idea-IU-181.5087.20
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • MIX 2S • 55822fe8 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Is this still an issue?

Can you please post a complete minimal runnable (incl `main() {...}` reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce?

**Comment by StefanLobbenmeier** [comment]
I inserted his code into the demo program and got it working: 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Stack layout'),
      ),
      body: new Center(
        child: new Stack(
          children: <Widget>[
            new Image.network(
                'http://img2.cxtuku.com/00/13/12/s97783873391.jpg'),
            new Positioned(
              left: 35.0,
              right: 35.0,
              top: 45.0,
              child: new Text(
                'Whatever is worth doing is worth doing well',
                style: new TextStyle(
                  fontSize: 20.0,
                  fontFamily: 'serif',
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by StefanLobbenmeier** [comment]
I could also reproduce all the following steps. Now I am trying to wrap my head around if that behaviour is all intended or if there is a bug in there somewhere. The [documentation ](https://docs.flutter.io/flutter/widgets/Stack-class.html) says:

> Each child of a Stack widget is either positioned or non-positioned. Positioned children are those wrapped in a Positioned widget that has at least one non-null property. The stack sizes itself to contain all the non-positioned children, which are positioned according to alignment (which defaults to the top-left corner in left-to-right environments and the top-right corner in right-to-left environments). The positioned children are then placed relative to the stack according to their top, right, bottom, and left properties.

That means the first image is completely reasonable (the stack has the size according to the Image, and the stack is centered because it is wrapped in center).

**Comment by zoechi** [comment]
Without investigating closer I think this is caused by the effect the content of the `Stack` has to how the `Stack` is sized. Have you tried enabling "Debug Paint" and watch the size of the `Stack` change?

![image](https://user-images.githubusercontent.com/405837/53246397-d6f47600-36b0-11e9-8f8b-bf92c3f2116a.png)

**Comment by StefanLobbenmeier** [comment]
> 
> 
> Without investigating closer I think this is caused by the effect the content of the `Stack` has to how the `Stack` is sized. Have you tried enabling "Debug Paint" and watch the size of the `Stack` change?


Good idea. The overlay supports my understanding that I wrote previously:
![grafik](https://user-images.githubusercontent.com/36509607/53247502-d90c0400-36b3-11e9-8a87-ebd05c431b58.png)

![grafik](https://user-images.githubusercontent.com/36509607/53247531-e923e380-36b3-11e9-84a8-b13b3dcf5eb5.png)

![grafik](https://user-images.githubusercontent.com/36509607/53247558-f9d45980-36b3-11e9-8604-346b8dcb9cfb.png)

By the way, I can click on Screenshot in the emulator, but I did not see where it saved so I used snipping tool. @Icarus-Xu please share with us how you did those nice screenshots
