### ISSUE TITLE
Dart and Flutter package menus are visible but empty when no windows are open in Atom.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2002]
Dart and Flutter package menus are visible but empty when no windows are open in Atom.

Strange, non-critical bug.

<img width="156" alt="screen shot 2016-02-18 at 9 52 54 am" src="https://cloud.githubusercontent.com/assets/11857803/13157254/a8eb0388-d63b-11e5-8498-94f980e3ad3b.png">

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
