### ISSUE TITLE
flutter_firestore:  Add a possibility to observe if FireStore is busy 

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#20025]
Currently it seems there is no way telling if  FireStore is currently busy retrieving data. If I use a collection snapshot stream to display the collection with a StreamBuilder I have no chance to display a Spinner to signal the user to wait. My Page will stay empty until the data arrives which can take some seconds depending on my network.

**Comment by DarshanGowda0** [comment]
@escamoteur You could use something like this 
`if (snapshots.connectionState == ConnectionState.active) {
            return Container();
          } else if (snapshots.connectionState == ConnectionState.waiting) {
            return Container(child: Center(child: CircularProgressIndicator()));
          } `

**Comment by escamoteur** [comment]
But I need a event when the state changes / or a stream with busy states because otherwise how do I trigger a rebuild?

**Comment by kroikie** [comment]
@escamoteur

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/729. Any further collaboration will be done there.
