### ISSUE TITLE
Is there any way to implement firebase crash reporting in flutter?

### ISSUE THREAD

**Issue by vithanichandresh** [flutter/flutter#20024]
i found two libraries.
bugsee and sentry but they are provides paid service.

help me to implement firebase crash reporting in flutter.

if you have documentation then please send me link.

**Comment by ebeem** [comment]
not yet as far as I am concerned.
also, it's possible that Crashlytics will replace firebase crash reporting 
Google already integrated firebase with it and recommended using Crashlytics over firebase crash reporting too.

there should be a progress in this, but nothing clear yet.

and you are not alone, a lot want this feature too, add your vote here
https://github.com/flutter/flutter/issues/14765

**Comment by zoechi** [comment]
Closing as dup of #14765 
Thanks @ebeem
