### ISSUE TITLE
Cannot set http_proxy for flutter packages pub get 

### ISSUE THREAD

**Issue by hadilq** [flutter/flutter#20032]
I checked out `https://github.com/flutter/plugins/tree/master/packages/image_picker/example` project and try to set the http proxy to get dependencies by this 

    export http_proxy=http://127.0.0.1:8035

then running

    $ flutter packages pub get --verbosity=all  
    ...
    IO  : Get package from https://pub.dartlang.org/packages/video_player/versions/0.5.2.tar.gz.
    MSG : Downloading video_player 0.5.2...
    IO  : Created temp directory /opt/android-sdk/flutter/.pub-cache/_temp/dirEDYKFN
    IO  : HTTP GET https://pub.dartlang.org/packages/video_player/versions/0.5.2.tar.gz
        | X-Pub-OS: linux
        | X-Pub-Command: get
        | X-Pub-Session-ID: 4CC0B103-8DF0-4CBA-A313-0310AB06C9A5
        | X-Pub-Environment: flutter_cli:interactive
        | X-Pub-Reason: direct
        | user-agent: Dart pub 2.0.0-dev.58.0.flutter-f981f09760
    IO  : HTTP response 403 Forbidden for GET https://pub.dartlang.org/packages/video_player/versions/0.5.2.tar.gz
        | took 0:00:01.532410
        | alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"
        | cache-control: private, max-age=0
        | date: Tue, 31 Jul 2018 10:38:26 GMT
        | content-length: 193
        | x-guploader-uploadid: AEnB2UqvCtydp6TMZC8m38IAx_bqVtZFDSeX8a6Vk1QfhRJEICqOpwWvu5JwmSbNWj2Tgawb0wO4zU_SJ5SCJy5lluFA_M5iQ
        | content-type: application/xml; charset=UTF-8
        | server: UploadServer
        | expires: Tue, 31 Jul 2018 10:38:26 GMT
    ERR : HTTP error 403: Forbidden
    FINE: Exception type: PubHttpException
    ERR : package:pub/src/http.dart 220                _ThrowingClient.send
        | ===== asynchronous gap ===========================
        | dart:async                                   _Completer.completeError
        | package:pub/src/http.dart                    _ThrowingClient.send
        | ===== asynchronous gap ===========================
        | dart:async                                   _asyncThenWrapperHelper
        | package:pub/src/http.dart 194                _ThrowingClient.send
        | package:http_throttle/http_throttle.dart 33  ThrottleClient.send
        | ===== asynchronous gap ===========================
        | dart:async                                   _asyncThenWrapperHelper
        | package:http_throttle/http_throttle.dart 28  ThrottleClient.send
        | package:pub/src/source/hosted.dart 304       BoundHostedSource._download
        | ===== asynchronous gap ===========================
        | dart:async                                   new Future.microtask
        | package:pub/src/source/hosted.dart 297       BoundHostedSource._download
        | package:pub/src/source/hosted.dart 199       BoundHostedSource.downloadToSystemCache
        | ===== asynchronous gap ===========================
        | dart:async                                   new Future.microtask
        | package:pub/src/source/hosted.dart 194       BoundHostedSource.downloadToSystemCache
        | package:pub/src/entrypoint.dart 372          Entrypoint._get.<fn>
        | ===== asynchronous gap ===========================
        | dart:async                                   new Future.microtask
        | package:pub/src/entrypoint.dart 367          Entrypoint._get.<fn>
        | dart:async                                   runZoned
        | package:pub/src/http.dart 275                withDependencyType
        | package:pub/src/entrypoint.dart 367          Entrypoint._get
        | package:pub/src/entrypoint.dart 229          Entrypoint.acquireDependencies.<fn>
        | dart:async                                   Future.wait
        | package:pub/src/entrypoint.dart 229          Entrypoint.acquireDependencies
        | ===== asynchronous gap ===========================
        | dart:async                                   _asyncThenWrapperHelper
        | package:pub/src/entrypoint.dart 192          Entrypoint.acquireDependencies
        | package:pub/src/command/get.dart 38          GetCommand.run
        | package:args/command_runner.dart 194         CommandRunner.runCommand
        | ===== asynchronous gap ===========================
        | dart:async                                   new Future.microtask
        | package:args/command_runner.dart 142         CommandRunner.runCommand
        | package:pub/src/command_runner.dart 168      PubCommandRunner.runCommand.<fn>
        | dart:async                                   new Future.sync
        | package:pub/src/utils.dart 115               captureErrors.<fn>
        | package:stack_trace                          Chain.capture
        | package:pub/src/utils.dart 130               captureErrors
        | package:pub/src/command_runner.dart 168      PubCommandRunner.runCommand
    ERR : This is an unexpected error. Please run
        | 
        |     pub --trace get --verbosity=all
        | 
        | and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
    pub finished with exit code 69

The flutter version  is 

    flutter --version 
    Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
    Framework • revision c7ea3ca377 (9 weeks ago) • 2018-05-29 21:07:33 +0200
    Engine • revision 1ed25ca7b7
    Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

How can I correct this behaviour?

PS: I'm sure '127.0.0.1:8035' is working correctly

**Comment by zoechi** [comment]
There is also HTTP**S**_PROXY that needs to be set.

**Comment by hadilq** [comment]
Thanks, but I just want to use ssh tunneling! Having https proxy is irrelevant. Is there a concern that I cannot fix this in the flutter code?

**Comment by hadilq** [comment]
Thank you @zoechi. I asked it in [pub issues](https://github.com/dart-lang/pub/issues/1957).

**Comment by zoechi** [comment]
Closing as dup of dart-lang/pub#1957

**Comment by hamidpp** [comment]
after change flutter version and change sdk path, i can not install any packge and get this error for all requests:
HTTP error 403: Forbidden

**Comment by alexZaicev** [comment]
Having the same problem.. tried to set various proxy hosts from our company to the HTTP_PROXY, HTTPS_PROXY, flutter still could not download packages

**Comment by huangyanxiong01** [comment]
```shell
export http_proxy=http://localhost:8123
export https_proxy=http://localhost:8123
```

work well for me

**Comment by mushroomlb** [comment]
windows 通过在环境变量中设置
http_proxy=http://localhost:port
https_proxy=http://localhost:port
