### ISSUE TITLE
Speed up bots

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#20036]
The bots to a lot of repetitive work setting up to run tests (moreso on Cirrus, where we currently don't cache anything). I thought it was worth having somewhere to collect notes on what could be done to improve things.

- [x] Add PubCache to build cache https://github.com/flutter/flutter/pull/20080
- [ ] Speed up `pub get` https://github.com/flutter/flutter/issues/2737
- [ ] Cache Dart SDK download (notes below)
- [x] Cache Artifacts folder (notes below) https://github.com/flutter/flutter/pull/20080
- [ ] Cache Pub snapshots (notes below)
- [x] Enable `flutter_tools` tests to run concurrently (#21113)
- [ ] Speed up `flutter_tools` integration tests
- [ ] Some Windows tasks seem *significantly* slower than Linux (notes below)
- [ ] Dart Unzip is slow on Windows (notes below)

## Cache Dart SDK download

Caching the bin\cache\dart-sdk folder could fairly simple, like this:

```yaml
dart_sdk_cache:
  folder: bin\cache\dart-sdk
  fingerprint_script: type bin\internal\engine.version
```

However this currently falls down because if the bin\cache\engine-dart-sdk.stamp file doesn't exist, the SDK gets re-downloaded regardless of the presence of the `dart-sdk` folder. We can't cache the `engine-dart-sdk.stamp` file without caching the whole `bin\cache` folder (can't cache individual files) and I'm not sure of the implications of that (eg. it'll cache `flutter_tools.snapshot`, downloads, etc.). Maybe it's safe to cache this whole folder but just for delete snapshots(+lockfile+downloads) from it?

## Artifacts Folder

If we can't cache the whole bin\cache folder, we may be able to cache `bin\cache\artifacts` which includes engine/gradle_wrapper/material_fonts

## Pub Snapshots

I need to dig into this, but I think when tracing something I saw Pub writing a bunch of snapshots into the `.dart-tool` folder within each packages folder. If this is taking much time, maybe we can find a way to get these snapshots out into the PubCache folder?

## `flutter_tools` Integration Tests are slow

The integration tests I've added seem super slow on Cirrus:

- 54s: test/integration/flutter_attach_test.dart: attached process can hot reload
- 33s: test/integration/hot_reload_test.dart: hot reload works without error
- 51s: test/integration/hot_reload_test.dart: hot reload hits breakpoints with file:// prefixes after reload
- 39s: test/integration/lifetime_test.dart: flutter run does not terminate when a debugger is attached
- 36s: test/integration/lifetime_test.dart: flutter run does not terminate when a debugger is attached and pause-on-exceptions

## Windows slower than Linux

Some of the tasks on Windows seem significantly slower than Linux, see the timings on this build for example:

![screen shot 2018-08-02 at 10 01 21 am](https://user-images.githubusercontent.com/1078012/43574054-19982c02-963b-11e8-9df6-7b4cb29ee304.png)

## Dart Unzip is slow (Windows)

Related to above. On Cirrus Windows, Dart unzip is over 30 seconds. There's a message in the `update_dart_sdk.ps1` script saying the built-in zip is slow (see https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/32 but apparently no fix) and to use 7zip. Maybe having zip cached on the bots would speed this up.

**Comment by zoechi** [comment]
> Pub Snapshots

Passing `--no-precompile` might do that.

```
 (dart2) $ pub get --help
Get the current package's dependencies.

Usage: pub get
-h, --help                 Print this usage information.
    --[no-]offline         Use cached packages instead of accessing the network.
-n, --dry-run              Report what dependencies would change but don't change any.
    --[no-]precompile      Precompile executables and transformed dependencies.
                           (defaults to on)
```

**Comment by DanTup** [comment]
I thought that, but it looked like it was already passing that and still writing snapshots. I got sidetracked and didn't make any notes - I need to go back to it and figure out exactly what it was doing (and also whether it was taking enough time to matter).

**Comment by DanTup** [comment]
Just noticed this in the logs:

> Precompiling executables finished (50.626s).

I think it's precompiling `flutter_tools` during set up, so it might not be all dependencies from all packages. It probably makes sense to precompile the ones for `flutter_tools` since `flutter` is invoked a lot during the runs.

I can't tell without changing the logging, but I think it's probably not happening for `update packages` based on https://github.com/flutter/flutter/issues/20036.

**Comment by jmagman** [comment]
@dnfield and @jonahwilliams were working on Cirrus speedup recently.
https://github.com/flutter/flutter/pull/37880
https://github.com/flutter/flutter/pull/37941

**Comment by dnfield** [comment]
One thing we found was that adding the caches on the Macs was actually slowing things down :(

**Comment by godofredoc** [comment]
Closing as obsolete, we have already implemented several layers of caching and implemented several optimizations.
