### ISSUE TITLE
Is it possible to run a single test via CLI?

### ISSUE THREAD

**Issue by manhluong** [flutter/flutter#20030]
Hi,

I read through the official documentation ( https://flutter.io/testing/ ), and I see that with:

```
flutter test test/widget_test.dart
```

I can run the tests contained in that file.

However I would like to be able to run a single test (the one described via `testWidgets`) but I could not find how in the documentation.

**Comment by manhluong** [comment]
Ok, found out via `flutter test --help`.

Opened MR to update the website.

**Comment by zoechi** [comment]
https://github.com/dart-lang/test contains good docs that apply mostly to Flutter as well.

**Comment by zoechi** [comment]
Right, there is a small gap that should be covered by the docs.
