### ISSUE TITLE
Default resolution of the iOS simulator is large enough to be confusing to users of the hackathon guide

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#2003]
The default resolution of the iOS simulator is large enough that the simulator scrolls the content window to the bottom. The initial steps of the hackathon put all application contents in a tool bar that is initially off screen. This makes it appear that the the step has not succeeded (no errors, logs, etc..)

We should make it clear to scale to simulator window to not have some of its contents offscreen.

**Comment by eseidelGoogle** [comment]
Added a comment to the hackathon doc.  Would you like this added to getting-started as well?  Please feel free to edit either.

**Comment by chinmaygarde** [comment]
Both the website and the guide have been updated.

**Comment by eseidelGoogle** [comment]
Did you mean to update https://flutter.io/getting-started/#running-your-app-in-the-ios-simulator ? (you don't have to, just curious)

**Comment by chinmaygarde** [comment]
Yeah, its updated already.
