### ISSUE TITLE
Toggle Outline View button doesn't seem to do anything?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2004]
At least not while I have main.yaml open?  Maybe it does when a .dart file is open?

<img width="308" alt="screen shot 2016-02-18 at 12 43 49 pm" src="https://cloud.githubusercontent.com/assets/11857803/13157549/56989d82-d63d-11e5-9a37-3d73acf00e5a.png">

**Comment by devoncarew** [comment]
Yeah, it only operates on dart files. I'll re-word the tooltip.

**Comment by eseidelGoogle** [comment]
It does do something when my main.dart is open, but it's empty?
![screen shot 2016-02-18 at 12 47 14 pm](https://cloud.githubusercontent.com/assets/11857803/13157623/d2e98ce8-d63d-11e5-9884-3c41e4954bc0.png)

I'm using the default `flutter create` project, with no modifications.

```
%flutter doctor                                                                                                [~]
Flutter root: /src/flutter.

[✓] iOS toolchain - develop for iOS devices (installed)
  [✓] XCode - enable development for iOS devices (installed)
  [✓] brew - install additional development packages (installed)
    [✓] ideviceinstaller - discover connected iOS devices (installed)
    [✓] ios-deploy - deploy to connected iOS devices (installed)

[✓] Android toolchain - develop for Android devices (installed)
  [✓] Android SDK - enable development for Android devices (installed)

Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: d93a87ee126071ddba26433db5255fc12d6297ca (20 hours ago)
```

**Comment by eseidelGoogle** [comment]
Alternatively we could disable the button when a .dart file isn't front and center?  Not sure how easy that is in atom.

**Comment by devoncarew** [comment]
It's possible. We could even show and hide it as the active file changes.

**Comment by devoncarew** [comment]
No outline view contents is strange.

**Comment by eseidelGoogle** [comment]
Here are my inspector logs in Atom: https://gist.github.com/eseidelGoogle/d5deea07307523076da2

**Comment by devoncarew** [comment]
Fixed by https://github.com/dart-atom/dartlang/pull/779. Changed the tooltip to include the word 'Dart' and enable and disable the button based on the current editor == `.dart`.
