### ISSUE TITLE
"select and jump" flutter ide plugin 

### ISSUE THREAD

**Issue by yohom** [flutter/flutter#20057]
Add the flutter ide plugin the ability to click on the running interface and then the ide jumps to the corresponding user-defined build method , similar to the `toggle select widget mode` function of flutter Inspector.
For programmers who are not familiar with some project, this function can familiarize themselves with the relationship between code and interface as quickly as possible.

**Comment by zoechi** [comment]
"Toggle Select Widget Mode" does that for me.
It selects the widget node in the Inspector view and in the editor window it jumps to the line where it is instantiated.

**Comment by zoechi** [comment]
Sounds familiar but can't find it either right now. 
Perhaps something that was removed for some reason.

Perhaps better to ask in https://github.com/flutter/flutter-intellij instead.

**Comment by yohom** [comment]
Ok, I see. Thank you.
