### ISSUE TITLE
Material DatePicker doesn't show

### ISSUE THREAD

**Issue by kunit1** [flutter/flutter#20065]
The Datepicker on 0.5.8-pre. 194 does not show up.

## Steps to Reproduce

```
class SomeScreen extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
      return new SomeScreenState();
  }
}

class SomeScreenState extends State<SomeScreen> {
  DateTime selectedDate = DateTime.now();

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: Container(
        child: RaisedButton(
          child: Text("Select Date"),
          onPressed: () => _selectDate(context)
        ),
      )
    );
  }

   Future<Null> _selectDate(BuildContext context) async {
    final DateTime picked = await showDatePicker(
      context: context,
      initialDate: selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(Duration(days: 30))
    );

    if (picked != null && picked != selectedDate) {
      selectedDate = picked;
    }
  }

}
```

## Logs

No Errors in the Debug Console

## Flutter Doctor

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.8-pre.194, on Microsoft Windows [Version 10.0.17134.165], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.25.1)
[√] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
Does this mean the same code worked in earlier Flutter versions?

**Comment by kunit1** [comment]
I am not sure in what version it broke, but it was working in the beta version.
The Picker still works, but the date picker is broken as far as I can tell.
Should this be marked as regression?

**Comment by kunit1** [comment]
After a few rebuilds it started working. I am really confused why it wasn't working before. My code did not change. Either way, I will close this issue for now and monitor it. Will re-open if it occurs again or if I find a concrete way of reproducing it.

**Comment by shadyaziza** [comment]
I have just ran in the same issue, date picker does not show up if it was called in a separate method, note how it works on the `RaisedButton` and does not work on the `FloatingActionButton`:
![datepickerbug](https://user-images.githubusercontent.com/12971971/43994041-acd8e710-9d96-11e8-95d4-3d700a03f1b4.gif)

```
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp( DatePickerTask());

class DatePickerTask extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        floatingActionButton: Theme(
          data: Theme.of(context).copyWith(
            primaryColor: Colors.amber,
          ),
          child:  Builder(
            builder: (c) => FloatingActionButton(
                child:  Icon(Icons.date_range),
                onPressed: () => _handleDatePicker(c)),
          ),
        ),
        appBar: AppBar(title: Text('Date Picker Example')),
        body: Center(
            child: Builder(
          builder: (con) => RaisedButton(
                textColor: Theme.of(context).accentTextTheme.display1.color,
                color: Theme.of(context).primaryColor,
                child: Text('Choose a starting date'),
                onPressed: () => showDatePicker(
                      context: con,
                      initialDate:  DateTime.now(),
                      firstDate:
                           DateTime.now().subtract( Duration(days: 30)),
                      lastDate:  DateTime.now().add( Duration(days: 30)),
                    ),
              ),
        )),
      ),
    );
  }

  Future<Null> _handleDatePicker(BuildContext floatContext) async {
    final dateResult = await showDatePicker(
        context: floatContext,
        firstDate: DateTime.now(),
        initialDate: DateTime.now().subtract(Duration(days: 30)),
        lastDate: DateTime.now().add(Duration(days: 60)));

    //prints the chosen date from the picker
    print(dateResult);
 
  }
}

```

output of `flutter doctor -v`:
```
[√] Flutter (Channel master, v0.5.9-pre.17, on Microsoft Windows [Version 10.0.17134.165], locale en-US)    • Flutter version 0.5.9-pre.17 at D:\Development\Flutter\fluttersdk\flutter    • Framework revision 5d8771d18d (12 hours ago), 2018-08-10 21:18:10 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Development\androidsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Development\androidsdk
    • Java binary at: D:\Development\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at D:\Development\Android
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • IntelliJ at D:\Installed\IntelliJ IDEA 2017.1.5
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API
27) (emulator)

• No issues found!
```

**Comment by kunit1** [comment]
One difference that I can see between the raised button and the FAB is that with the Raised button you are calling the datepicker without an await. However, in your FAB you're calling the datepicker with an await inside the method.

From I understanding, the await implementation is the correct one. I am currently calling the datepicker with an await from inside another method and it is working (on master, 0.5.8-pre.286).

Try running clean, and rebuild then try again. If the problem persists I suggest you open a new issue as it is unlikely the team will see this closed issue.

**Comment by zoechi** [comment]
Without a closer look I'd guess it is related to `BuildContext`. Perhaps the context available in FAB doesn't have a reference to the router. 
Is there an error output in the console if you click the FAB?

**Comment by zoechi** [comment]
@shadyaziza In `_handleDatePicker`
```dart
        initialDate: DateTime.now(),
        firstDate: DateTime.now().subtract(Duration(days: 30)),
```
`initialDate` and `firstDate` are mixed up which causes

```
E/flutter (20987): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (20987): 'package:flutter/src/material/date_picker.dart': Failed assertion: line 1082 pos 10: '!initialDate.isBefore(firstDate)': initialDate must be on or after firstDate
```

**Comment by Shantanu-Kotambkar** [comment]
@zoechi  I am facing the same issue. What do you mean by firstDate and initialDate are mixed up. I am not sure why this wont work?

`        initialDate: DateTime.now(),
        firstDate: DateTime.now().subtract(Duration(days: 30)),`

**Comment by zoechi** [comment]
@codigopher not sure what your point is, but the order of named parameters doesn't matter. 
You might want to store the value of `DateTime.now()` and pass this variable for `firstDate` and `initialDate`

**Comment by solution-odii** [comment]
this code will solve your problem

       ```
context: context,
        initialDate: DateTime.now().add(Duration(hours: 1)),
        firstDate: DateTime.now(),
        lastDate: DateTime(2101));
```

**Comment by vitulgoyani** [comment]
This is best Solution 👇🏼
```
final DateTime picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now().subtract(Duration(days: 1)),
      lastDate: DateTime.now().add( Duration(days: 1095)),
    );
```

**Comment by Androidsignal** [comment]
DateTime picked;
    if (toDate != null) {
      picked = await showDatePicker(
        context: context,
        firstDate: new DateTime(fromDate.year, fromDate.month, fromDate.day),
        initialDate: toDate,
        lastDate: new DateTime(DateTime.now().year + 2),
      );
    } else {
      picked = await showDatePicker(
        context: context,
        initialDate: DateTime.now(),
        firstDate: new DateTime(fromDate.year, fromDate.month, fromDate.day),
        lastDate: new DateTime(DateTime.now().year + 2),
      );
    }

**Comment by yusufskebbe** [comment]
after flutter updates this is a common problem, you can solve it but using asyn

**Comment by tejashu7** [comment]
Hello Everyone,

I wanted to know if the showdatepicker method can be reused from other classes. can somebody help me out with this?

**Comment by fluttercorner** [comment]
[How To Use Date Picker in Flutter](https://fluttercorner.com/how-to-use-date-picker-in-flutter/)
