### ISSUE TITLE
Flutter Gallery license page repeats licenses

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#20066]
When you open the Flutter Gallery with the latest build, you will see the `boringssl` license is  displayed many times in the license page (About Flutter Gallery > View Licenses).

<img width="352" alt="lics" src="https://user-images.githubusercontent.com/34681083/43499998-b1ea7b4a-9591-11e8-9e24-fc90fb97e0cd.png">

Version I'm using:
```
Flutter (Channel master, v0.5.8-pre.193, locale en-US)
```

Update: I think there is a problem parsing the `boringssl` licenses there should only be the 4 licenses seen at https://github.com/google/boringssl/blob/master/LICENSE but the Gallery app has many other licenses

**Comment by zoechi** [comment]
@murakamitaichi @nagendran-n please check #18281
