### ISSUE TITLE
Dart/Flutter App is not working on Samsung J7 Prime and many other android devices. #19751

### ISSUE THREAD

**Issue by bharatiprasad** [flutter/flutter#20062]
Dart/Flutter App is not working on Samsung J7 Prime and many other android devices. The simple increment counter example is not working on Samsung J7 Prime with Android 7.0 (Nougat). Did any one come across this issue? if so, is there a solution to fix this? Kindly help me.... App never opens! It throws 'abc' keeps stopping\n x Close app"

I created an issue https://github.com/flutter/flutter/issues/19751

Flutter guys please reply....This is becoming a pain for me! if flutter doesn't work as desired, I will have to look for something else or go back to Xamarin/C#

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by ram231** [comment]
Logs? This isn't very helpful if there were no logs or errors shown.

**Comment by zoechi** [comment]
What is the reason for having this issue in addition to #19751 ?

**Comment by bharatiprasad** [comment]
My Friend, I really don't have answer for the issue with my app not working
on some devices...the situation i am in is, I already have developed the
APP and is about to be released to customer. During the testing stage, we
found that this app is not working on many mobile devices.
And I am not sure how effective is the FLUTTER support! My ass is already
burning....

**Comment by bharatiprasad** [comment]
My Friend! The physical devices (MI Max, Redmi Note 4, LeEco) I am
debugging the app is working fine. But, the same app is not working on some
of the popular android devices (these devices are my customer's...they want
to test this app....in different continent). so, no logs or errors! In
fact, there is no error. It simply shows "Unfortunately, xxxxx keeps
stopping" immediately after the app is launched...

**Comment by zoechi** [comment]
Sorry for the confusion. I meant why did you create 2 bug reports (this one and #19751).
They seem to be about the same problem.

**Comment by kyawswa** [comment]
I also facing that issue when I run flutter app in profile mode. I cannot install flutter app exported with profile mode in Samsung J7 Prime.

Here is log file.
https://drive.google.com/open?id=1gKs7nT5hcLuk6xBovxq6DY8hO_PsFrje

**Comment by ThitSarNL** [comment]
I can pass this error now. 
1. Let it installable, (Setting->BIOMETRICS AND SECURITY->Installl unknown apps->My Files->Allow from this source)
2. Clear internal storage (good if u also clear sd card storage) more than ur app size.
3.  Android Studio->Terminal->Type "flutter build apk" and wait for a while and find the file in folder of YourAppFolder\build\app\outputs\apk\release\app-release.apk
4. (Delete previously installed app if u have and ) Try to install that apk file

**Comment by godlessturtle** [comment]
Same error here, people can install from play store but it returns only black screen

**Comment by sameh-khemira** [comment]
Hello I am having the same error on Samsung galaxy grand prime, client can install the app from play store but when trying to opening it , it keeps crashing "the App  has stopped" .
