### ISSUE TITLE
showBottomSheet is behind my BottomNavigationBar

### ISSUE THREAD

**Issue by hyochan** [flutter/flutter#20067]
I want `showBottomSheet` to appear with full screen from child navigation screen.  How can I achieve it?

```dart
showBottomSheet(
      context: context,
      builder: (BuildContext context) {
        return DialogHost(
          txtTitle: 'host',
        );
      }
);
```

<img width="1136" alt="screen shot 2018-08-01 at 1 40 08 pm" src="https://user-images.githubusercontent.com/27461460/43501487-ba43894a-9590-11e8-933f-72dee7cac850.png">

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.6 17G65, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (2 available)
```

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
Is this still an issue?

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
