### ISSUE TITLE
Enable Paint Debug while running a Flutter App in Debug Mode

### ISSUE THREAD

**Issue by varunpandey0502** [flutter/flutter#20063]
After setting the flag debugPaintSizeEnabled to true, the app the does not display the layout grids while running the app in debug mode.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Do you invoke a rebuild after you set `debugPaintSizeEnabled`?
IntelliJ has a toolbar button to toggle while the app is running

![image](https://user-images.githubusercontent.com/405837/43507979-e773b45c-956e-11e8-947f-01a1b642af65.png)

I don't know if there is one in intelliJ

Also if you use `flutter run` you can toggle it by pressing `p` in the terminal window (might also work in VSCode)

![image](https://user-images.githubusercontent.com/405837/43508087-3ba58f78-956f-11e8-937f-eb12849aef01.png)

**Comment by Coder-Dan** [comment]
Are these commands supported when using VS Code F5 Debug? Because when I go to the debug console it does not respond to these commands.

![image](https://user-images.githubusercontent.com/17520612/50555234-76366600-0d1d-11e9-9fe0-7bc4f0c73819.png)

**Comment by zoechi** [comment]
@DanTup ?

**Comment by DanTup** [comment]
@Coder-Dan Those keys are just shortcut keys in the console runner, they won't work if typed into the  Debug Console (which just evaluates what you type as Dart expressions). However, there are equivalent commands in the VS Code command palette (which, you can keybind if you wish):

<img width="661" alt="screenshot 2019-01-02 at 8 38 57 am" src="https://user-images.githubusercontent.com/1078012/50584852-dd613100-0e69-11e9-86ce-b97e72928fbd.png">

Note: They'll only appear when you're in a debug session that supports them.

Let me know if you have any problems using them!
