### ISSUE TITLE
How to generate documents like docs.flutter.io

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#20060]
How to generate documents similar to https://docs.flutter.io/ locally for offline viewing.
I see that [dartdoc.dart](https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart) has similar work, but it seems to be applied to the automatic maintenance of DOC website.
What is the way to generate an offline document?

**Comment by zoechi** [comment]
As far as I know it's created by https://pub.dartlang.org/packages/dartdoc

**Comment by CaiJingLong** [comment]
Get it.
I will close the issue and open a new dartlang to get help.
thx ☺
