### ISSUE TITLE
Atom awareness of `flutter refresh` to speed up dev cycles

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2007]
Not sure if Atom is aware of `flutter refresh`, but it's a much faster way to iterate if all you are doing is changing code. If you've changed Dart code, run `flutter refresh` instead of `flutter start`. Cuts 11 seconds down to 3 seconds.

**Comment by sethladd** [comment]
cc @jason-simmons @devoncarew

**Comment by devoncarew** [comment]
I'd like to try and refactor a bit to where `start` will use the functionality of refresh behind the scenes, if it detects that that's possible (https://github.com/flutter/flutter/issues/1776).

**Comment by sethladd** [comment]
sgtm! Closing in favor of https://github.com/flutter/flutter/issues/1776
