### ISSUE TITLE
List of widgets: why List<Widget> and not Iterable<Widget>

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#20079]
Wouldn't it be better to accept an`Iterable` rather than a `List` inside widgets that accept a list of widgets (ListView, Stack, etc.) 

The arguments for Iterables that I see are:
- functions like `map` and `where` return Iterables therefore a `.toList()` wouldn't be necessary anymore
- [Other data types that implement the Iterable interface could be used without conversion boilerplate](https://github.com/google/built_collection.dart/)

Is there a reason why `List` was chosen?

**Comment by zoechi** [comment]
@Hixie

**Comment by modulovalue** [comment]
I'll close this as it's not a _real_ issue but it still would be nice to know.

**Comment by Hixie** [comment]
We looked into using an Iterable here but the problem is that it's less efficient. We walk the list often and in a random-access fashion; every time you end up running all the Iterable logic. So we'd have to cache it in the widget by calling toList there. But `const` constructors can't do that.

**Comment by bharatsingh100** [comment]
why dont u make it a implicit conversion from iterable to list, so that it accepts both
