### ISSUE TITLE
Error when trying to set up Firebase and trying to get fingerprint sha1: code for Flutter project in Android

### ISSUE THREAD

**Issue by rakz25** [flutter/flutter#20089]
keytool -exportcert -list -v \
> -alias androiddebugkey -keystore ~/.android/debug.keystore
keytool error: java.lang.Exception: Only one command is allowed: both -exportcert and -list were specified.

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/49699765/keytool-error-java-lang-exception-only-one-command-is-allowed-both-exportcer 
looks like `-exportcert` is redundant.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by relativityboy** [comment]
Looks like this doc needs to be updated `https://developers.google.com/android/guides/client-auth` y'all within the core flutter dev group probably have louder voices than the community.

**Comment by DigitalSolomon** [comment]
Why has this still not been updated? The wrong documentation has been sitting there for over a year, misleading Flutter and Firebase developers around the world. Someone please just delete the `-exportcert` from the docs and save developers manhours.
