### ISSUE TITLE
AVD crashed for normal type mismatch exception

### ISSUE THREAD

**Issue by khajaamin** [flutter/flutter#20083]
This below error is crashing AVD. 

> type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Widget'

whenever I am getting error  above  my avd is not responding . 

please let me know if  more details needed. 

Thanks

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

What exactly do you mean with "avd is not responding"?
I assume with "avd" you mean the Android emulator.
What is "not responding" exactly. Is it the whole emulator application or only the Flutter app?

**Comment by iamprohaktiv** [comment]
Ohh!! @zoechi  please pardon for bad question. 

My Flutter app was not responding when the exception  thrown while debugging app in emulator.

need to restart emulator or  kill app and re start build. 

posting  result of flutter doctor -v 


[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_IN)
    • Flutter version 0.5.1 at /home/khajaamin/flutter/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/khajaamin/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/khajaamin/android-sdk-linux
    • Java binary at: /home/khajaamin/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/khajaamin/android/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)


Thanks

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
