### ISSUE TITLE
Text Widget does not support certain unicode characters on Android.

### ISSUE THREAD

**Issue by parkskier426** [flutter/flutter#20094]
Certain Unicode characters don't show up on Android devices in a Text Widget. When using a '⚡' character in a Text Widget, the character shows up on iOS but not Android. I've tried using the system font, Monterrat, and Comfortaa. I've tried several devices on iOS with success and tested with a Pixel 2 XL running Android 8.1 without success.

## Steps to Reproduce

1. Change a Text Widget in any application to use a '⚡' character.
2. Test on iOS to see the '⚡' character.
3. Test on Android to see the '⚡' character missing.

## Logs

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.1 at /Users/jschmitz/utils/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jschmitz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Pixel 2 XL • 710KPRW0231798                       • android-arm64 • Android 8.1.0 (API 27)
    • iPhone 5s  • 6AD4800E-771E-4AE6-913E-0EBA1AEAE249 • ios           • iOS 11.4 (simulator)
```

**Comment by jason-simmons** [comment]
I was able to render this character on a Pixel 2 XL.  I tested it by adding the character to one of the Text widgets in the template application generated by "flutter create".

The character should render using the system's emoji font (typically "NotoColorEmoji").  If the primary font family in a text widget's style doesn't include the character, then the Flutter engine should search for a fallback font that can handle the character.

In your setup, does this happen if you add the character to the template app?  Or does it only happen in a more complex application?

**Comment by gamebox** [comment]
I get similar behavior on a real Pixel 2 XL device running Android 9 Pie(and the RC of P), but not on the same operating system, same device in the Emulator on Linux(Ubuntu 18.04).

**Comment by zoechi** [comment]
Are you still seeing this?

> In your setup, does this happen if you add the character to the template app? Or does it only happen in a more complex application?

any thoughts?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by BlackGold-1989** [comment]
.............
I/flutter (20718): Cannot decode the string to Latin1.
I/flutter (20718): This font does not support Unicode characters.
I/flutter (20718): If you want to use strings other than Latin strings, use a TrueType (TTF) font instead.
I/flutter (20718): See https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
.............

I met the same issue in there.
I tried the Arial and Monterrat fonts but same result.
