### ISSUE TITLE
firebase_auth - Other provider logins

### ISSUE THREAD

**Issue by samgithub-duplicate** [flutter/flutter#20092]
I noticed the sample for **firebase_auth** is based on just **phone** and **goggle** authentication.  (I got the **googleSignin** working following your example).  

**Question**
Will there be a **Facebook** and **Twitter** signin example from the firebase_auth team anytime soon -- since the firebase claims **"supporting email and password accounts, phone auth, and Google, Twitter, Facebook, and GitHub login, and more"** see https://firebase.google.com/products/auth/

1) Are there any plans to to provide this functionality (samples)?
2) Are there any plans to support Microsoft Azure/Azure B2C authentication? they are an OIDC provider; Azure B2C supports Google-Signin.
3) In the absence of (2) are there plans to support 'generic' OIDC providers?  This will help us fill in he 'gaps'
4) Can you share some kind of a planned feature timeline with us?

BTW:  the documentation on setting up/configuring the app was **right-on.**  The only problem I had was in the integration with the Firebase Console. As you know we search the web for possible solutions.  All my approaches failed until after the better part of an extended full day, I stumbled upon a codelabs 'tutorial' which pointed out that the SHA1 fingerprint for **debugging**  must use the 'debug.keystore' in **%USERINFO%** (windows environment).  Once I did that, my google Sign-in worked in seconds.

I suggest you either specify that on the setup page or provide a link to the relevant info.  I know it might be obvious to you -- bust just that one sentence could have save me over 10 hours..

**Comment by gcshri** [comment]
The updated firebase_auth docs have a phone authentication example ( https://pub.dartlang.org/packages/firebase_auth ).

I personally prefer to research how other apps work, learn and implement my own auth flow. This is a good-ish example of how to add facebook - https://github.com/manhinhang/flutter_fireauth_ui by @manhinhang 

Yes, it the auth examples are very fragmented and the lack of a complete firebase starter (auth, analytics, firestore, state management etc) from an authoritative source is not optimal. :)

**Comment by kroikie** [comment]
@samgithub-duplicate

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/728. Any further collaboration will be done there.
