### ISSUE TITLE
Plugin: Push notifications

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#201]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [abarth](https://github.com/abarth)**
_Wednesday Oct 14, 2015 at 00:12 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1609_

---

We should add support for push notifications via a Mojo service.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Oct 15, 2015 at 05:09 GMT_

----

Do you mean over-the-network push notifications like from GCM, or on-device notifications like you get on the Android lock screen?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 15, 2015 at 05:19 GMT_

----

GCM

**Comment by eseidelGoogle** [comment]
Yet another request for this.  My understanding is that we have an example GCM service:
https://github.com/flutter/flutter_gcm/tree/master/examples/simple
but it may only work on Android at the moment.

**Comment by abarth** [comment]
We should provide an example of how to do this with a FlutterView.

**Comment by mit-mit** [comment]
@mpcomplete are you working on this?

**Comment by adaojunior** [comment]
`flutter/flutter_gcm` is not found. I'm also trying to implement push notification on a app.

**Comment by eseidelGoogle** [comment]
flutter_gcm broke after we re-worked our plugin system last year, so we hid it.  https://github.com/mpcomplete/flutter_gcm is likely a very old version (which will not work with modern flutter) but might provide you inspiration.

**Comment by eseidelGoogle** [comment]
We've had various customers ship flutter using-apps (e.g. newsvoice.se @vlidholt ) which have used push notifications in conjunction with Flutter (by writing some Obj-C or Java code).  However we do not yet have a published plugin which provides this support out of the box.  I know @collinjackson has discussed doing so.

**Comment by collinjackson** [comment]
We currently have a plugin that supports push messaging: https://github.com/flutter/firebase_messaging

**Comment by eseidelGoogle** [comment]
Oh, I somehow missed that in my search.  Should this be closed?

**Comment by collinjackson** [comment]
I'd be curious to hear customer feedback about whether the existing plugin is sufficient. It's possible that some devs will want a plugin that supports raw APNS notifications on iOS (without using Firebase), but it's hard to know for sure without asking. It would be nice to not have maintain two separate plugins if we don't have to...

**Comment by eseidelGoogle** [comment]
I'm going to close this for now, given that we've had multiple applications ship with this model.  Our plugin system is such that anyone can write and publish a plugin, so ideally we won't maintain multiple. :)

**Comment by eseidelGoogle** [comment]
This bug ended up being resolved as part of https://github.com/flutter/flutter/issues/8903.
