### ISSUE TITLE
Flutter.io 'write first app' duplicated at google developers as well

### ISSUE THREAD

**Issue by momoadeli** [flutter/flutter#20106]
It's duplicated at both:
[flutter.io codelabs](https://flutter.io/get-started/codelab/)

..and at:
[google developers codelabs](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#0)

Perhaps best to reference same source.

**Comment by Sfshaza** [comment]
Yes, this was intentional, @momoadeli. But thanks for your vigilance!
