### ISSUE TITLE
app can't auto landscape in ios

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter#20124]
I want a landscape page in my app
use this code
```dart
@override
  void initState() {
    super.initState();
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
    ]);
  }
```

in android, it works well. app could auto landscape.but it doesn't work in ios.

i must  horizontally iphone to make it work.

bug?

**Comment by zoechi** [comment]
Thanks @jaumard !
Merging with #13238
