### ISSUE TITLE
Firebase Auth errors 

### ISSUE THREAD

**Issue by buttonsquared** [flutter/flutter#20127]
Hi,
I am getting 4 errors when I try to run the firebase sample app.  I am using XCODE Version 9.2 (9C40b)

```
ios/Classes/FirebaseAuthPlugin.m:71:41: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
            signInAnonymouslyWithCompletion:^(FIRAuthDataResult *dataResult, NSError *error) {

ios/Classes/FirebaseAuthPlugin.m:104:41: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
                                 completion:^(FIRAuthDataResult *dataResult, NSError *error) {

ios/Classes/FirebaseAuthPlugin.m:132:37: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
                             completion:^(FIRAuthDataResult *dataResult, NSError *error) {

ios/Classes/FirebaseAuthPlugin.m:189:43: error: incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)')
                                   completion:^(FIRAuthDataResult *dataResult, NSError *error) {

ios/Pods/Headers/Public/FirebaseAuth/FirebaseAuth/FIRAuth.h:431:63: note: passing argument to parameter 'completion' here
                       completion:(nullable FIRAuthResultCallback)completion;
```

**<h1>flutter Doctor</h1>**
```
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.12.6 16G1314, locale en)
    • Flutter version 0.5.7 at /Users/Jeff.Gardner/git/flutter
    • Framework revision 66091f9696 (3 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • iPhone X • DA6CA3F5-26F8-4583-8FEE-40B86D284FBA • ios • iOS 11.2 (simulator)
```

**<h1>pubspec YAML</h1>**
```yml
name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.5.15
  google_sign_in: ^3.0.4

flutter:
  uses-material-design: true
```

Any ideas been struggling with this for a while.

**Comment by ram231** [comment]
1. Have you created your own firebase project with authentication?
2. Your googleAppID is different from the example?
3. I don't know in android but it requires SHA1.

Couldnt find the same error here.

**Comment by zoechi** [comment]
Have you tried running `pod update` in `ios/`?

**Comment by buttonsquared** [comment]
I did try pod update I do get an error saying can't connect to github when I run pod update however if I delete PODS and run pod install everything works fine.

**Comment by buttonsquared** [comment]
I am only trying on IOS and I did create a new project and download the GoogleService-info.plist.

**Comment by buttonsquared** [comment]
I was able to run pod update finally now I am getting this error 

5.5.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.5.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50100000 started
5.5.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Syncing files to device iPhone X...
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cd9512b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c429f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ce0a245 +[NSException raise:format:] + 197
	3   Runner                              0x0000000109b0e438 -[GIDSignIn signInWithOptions:] + 242
	4   Runner                              0x0000000109b0ae24 -[GIDSignIn signIn] + 64
	5   Runner                              0x0000000109a69312 -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2114
	6   Flutter                             0x000000010a203d4a __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 118
	7   Flutter                             0x000000010a21be3a _ZNK5shel<…>
Lost connection to device.

**Comment by zoechi** [comment]
Sounds like you are missing https://github.com/flutter/plugins/blob/4acdcc1cdd73fd74fdadba452a37e708ae895731/packages/cloud_firestore/example/lib/main.dart#L12 but the app shouldn't crash from that

**Comment by nick-harris** [comment]
The fix for our project was to update the versions of any packages that depend on google_signin to their latest version to accommodate the signature change that those errors are complaining about.

**Comment by buttonsquared** [comment]
After more struggling and following the tutorial I got it to generate the following error 

MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

Any ideas how to solve that one?

**Comment by buttonsquared** [comment]
I got it working I just added [GeneratedPluginRegistrant registerWithRegistry:self]; to my appDeligate and everything works fine now.

**Comment by lihui2333** [comment]
i got the same error.

**Comment by cyanglaz** [comment]
@buttonsquared Seems the issue resolved for you? Are you ok if I close the issue?

@lihui2333 Do you still have issues? Could you create a separate issue and providing the details of your issue?

**Comment by kroikie** [comment]
@buttonsquared

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1121. Any further collaboration will be done there.
