### ISSUE TITLE
Demo is error . E/flutter (14647): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(44)] Failed to setup Skia Gr context.

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#20126]
Launching lib/main.dart on HUAWEI G750 T20 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
I/FlutterActivityDelegate(14647): onResume setting current activity to this
E/flutter (14647): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(44)] Failed to setup Skia Gr context.
Syncing files to device HUAWEI G750 T20...
Application finished.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by chinmaygarde** [comment]
Update: Investigating if there are GL surface setup issues on ARM Mali 450 MP4.

**Comment by zoechi** [comment]
Looks like a dup of #8610
