### ISSUE TITLE
Error: Flutter command not found

### ISSUE THREAD

**Issue by rakz25** [flutter/flutter#20132]
I have set my path and its showing correct

echo $PATH
Documents/flutter/bin:/usr/bin:/usr/sbin:/bin:/sbin

However when I run flutter doctor.It shows an error
flutter doctor
-bash: flutter: command not found

**Comment by zoechi** [comment]
`Documents/flutter/bin` doesn't look like a correct path.
What is the actual path where you installed Flutter?

**Comment by rakz25** [comment]
I have set my flutter sdk in documents.

**Comment by zoechi** [comment]
That might be but, but `Documents` is not a valid root for a path

**Comment by zoechi** [comment]
I'm going to close this issue. There is nothing for the Flutter team to do.
I'd suggest to ask on StackOverflow how to set the path to a specific directory in the operating system you are using.

**Comment by rakz25** [comment]
ok but somehow it took flutter command but now the issue is: Flutter plugin
not installed
Whereas I have installed dart and flutter plugin viscose

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by nhatlee** [comment]
I have same issue `flutter: command not found`, my path is:`/Users/nhatle/Users/nhatle/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS`.

**Comment by 1990mUkuna** [comment]
having the same problem really need a solution

**Comment by zoechi** [comment]
@1990mUkuna 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
