### ISSUE TITLE
AppBar title is final couldn't be changed, this is inconsistent with native app and daily case

### ISSUE THREAD

**Issue by gaoyuqi** [flutter/flutter#20131]
how could we find a workaround to solve this. this is actually weird experience

**Comment by zoechi** [comment]
Most properties of widgets are final.
In Flutter you usually don't modify properties of widgets, instead you cause a rebuild by calling `setState(...)` and when then a new instance is created pass a different value to the constructor.

**Comment by YahiaAgwa** [comment]
hope this work with you
```

String title;
@override
  void iniState(){
    super.initState();
    setState((){
      title='title first time';
    });
  }
  void _changeTitle(){
    setState((){
      title='Title Changed ^_^';
    });
  }
```
and the app bar will be like that
```
appBar: new AppBar(
        title: new Text(title)
)
```
you cane change the title by add any widget with onpress like that
```
IconButton(icon:Icon(Icons.search),onPressed: _changeTitle,)
```

**Comment by gaoyuqi** [comment]
I've completed this one, but not just setState() on title. since  as you mentioned, this control is final, without rebuilt, it will never change. and my workaround is to rebuild the AppBar while switch between bottom tabs. this have to rely on dart's garbage collection to managed the previously unused AppBar, and this works without explicitly memory leak.

**Comment by gaoyuqi** [comment]
thanks for you two help.
