### ISSUE TITLE
mongo_dart package works with dart but not with flutter?

### ISSUE THREAD

**Issue by niceguy1** [flutter/flutter#20139]
Hi, first post here, trying to fix my mongo_dart error, i appreciate any advice
```
C:\Users\tom>flutter doctor -v
[√] Flutter (Channel dev, v0.5.7, on Microsoft Windows [Version 10.0.16299.547], locale en-US)
    • Flutter version 0.5.7 at C:\src\flutter
    • Framework revision 66091f9696 (3 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\tom\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[√] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.16.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

• No issues found!
```
my code for testing:
```
import 'package:mongo_dart/mongo_dart.dart';

void main() async {
  Db db = new Db(
      'mongodb://(name&paswd)@mycluster.mongodb.net:27017');
  db.open().then((success) {
    if (success) print('connected');
  });
}
```
i have tried both with mongo_dart v0.3.2 and 0.3.3 (after overriding needed dependencies)
both came out with a similar error pointing to the driver file:
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
E/flutter (10779): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (10779): MongoDB ConnectionException: connection closed.
E/flutter (10779): #0      _ConnectionManager._connect (file:///C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/mongo_dart-0.3.3/lib/src/network/connection_manager.dart:25:38)
E/flutter (10779): <asynchronous suspension>
```
looks like im not the only one with this bug:
[https://github.com/mongo-dart/mongo_dart/issues/121](url)
seems its a flutter issue because its working with dart standalone as mentioned in the link
thank you

**Comment by zoechi** [comment]
Usually you would not access MongoDB from Flutter directly, but rather expose only an HTTP (REST) API on a server that itself talks to MongoDB. As far as I know MongoDB is not safe to be exposed to the internet directly.

That said, it should still work.

> works with dart but not with flutter

Does this mean you run the code above from a plain Dart project and there it printed `connected`?

With Flutter did you run it from an emulator or from a real device?

**Comment by niceguy1** [comment]
Hi @zoechi thanks for replying,

how to expose only an HTTP (REST) API on a server that itself talks to MongoDB? i eager to learn! any tutorials somewhere online about that?

i didnt run in personally because another user already did and confirmed it, i can try to do it now and report back

error is the same on emulator and a real device

**Comment by zoechi** [comment]
See also https://www.securityweek.com/thousands-mongodb-databases-found-exposed-internet
(which indicates that MongoDB in principle actually can be exposed to the internet)

There are tutorials and tools out there to create REST APIs like 
- https://docs.mongodb.com/ecosystem/tools/http-interfaces/
- https://www.mongodb.com/blog/post/building-your-first-application-mongodb-creating-rest-api-using-mean-stack-part-1

(discovered by a quick Google search)
That's not really related to Flutter though.

> i didnt run mongo_dart on dart standalone personally because another user already did and confirmed it, i can try to do it now and report back

That would be great. With this information we could be sure that the mongodb package works with your server configuration and reduce the problem to the network part of the device/emulator and the Dart network parts.

**Comment by niceguy1** [comment]
hi @zoechi , i got similar error on dart standalone
```
Unhandled exception:
MongoDB ConnectionException: connection closed.
#0      _ConnectionManager._connect (file:///C:/Users/tom/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/mongo_dart-0.3.3/lib/src/network/connection_manager.dart:25:38)
<asynchronous suspension>
```

**Comment by niceguy1** [comment]
hey @zoechi , are you saying for a mobile app i'de better have an http like website with domain that runs a script and communicates with mongodb
app to http/website to mongodb and back?

**Comment by zoechi** [comment]
>  are you saying for a mobile app

That's basically what I tried to say. Not sure what you mean with "script" though. 
You can this build with Python, Go, Java, Dart, Node.js, ... 

>  similar error on dart standalone

To me this looks like a network issue.
Do you have any other means to access this MongoDB instance from your machine to test if it works?

**Comment by niceguy1** [comment]
Hi @zoechi,  do u think flutter would work with that http method? i mean i didnt see any info about this until now and flutter is pretty new so maybe its not yet supported?

mongo shell works just fine, so as mongo compass, so i dont see how can it be network issue

**Comment by zoechi** [comment]
> mongo shell works just fine

That's what I wanted to know.

If it also does not work from plain Dart, it's also not a Flutter issue.

Flutter can do what Dart can do.
The mongo_dart Dart package is known to work.

I guess you'll need to find someone who can help you with mongo_dart.
If you got it working with plain Dart but not with Flutter, then I might be able to help,
like https://gitter.im/dart-lang/server or StackOverflow

**Comment by niceguy1** [comment]
yes your right, I'm liking the http solution now,  gonna check that out more, much easier for me to pull data from a website with a json file, add u said it's even safer

**Comment by niceguy1** [comment]
closing for now since it's a dart issue 
thanks @zoechi

**Comment by donnyv** [comment]
Since Flutter is being made to work on Windows & MacOS. This might need revisting.

**Comment by shahidcodes** [comment]
As @donnyv said. Also it'll be needed if one has to make mongo db client for Android or iOS.

**Comment by duckroll** [comment]
Is there any way to make mongo_dart work in Flutter Web? I have local mongo database and have no problem connecting to it when running android or macos but It doesn't work in web.
