### ISSUE TITLE
Miss SimpleDialog for Cupertino theme

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#20137]
For Material we have SimpleDialog, but there no equivalent for Cupertino theme, would be nice to have it

**Comment by xster** [comment]
Can you show us a mock-up of the layout you're trying to achieve (or the equivalent in iOS)?

**Comment by matthew-carroll** [comment]
@jaumard Does this reflect an actual iOS dialog type?  If so, please add a screenshot here of the real iOS equivalent for reference.  If not, I don't think we should add this to Cupertino.

CC: @xster @gspencergoog

**Comment by jaumard** [comment]
@matthew-carroll in fact my dialog will look like an alert dialog as I have two button inside, but as my dialog content has some widgets I create a widget to contain those, but buttons need to react to my widget, I can't do that (or maybe I just don't know ^^) if the buttons are not inside my widget too. 

So my code look like this: 
```
showDialog(
              context: context,
              builder: (context) => SimpleDialog(
                    contentPadding: const EdgeInsets.only(top: kNormalPadding),
                    title: Text('Choose device'),
                    children: <Widget>[
                      DeviceSelector((device) {

                      }),
                    ],
                  ),
```
 So here I'm using SimpleDialog but the purpose would be to switch depending on the platform. 
Inside my  DeviceSelector I have:
```
typedef OnDeviceSelectedCallback = Function(Device device);

class DeviceSelector extends StatefulWidget {
  final OnDeviceSelectedCallback onDeviceSelected;
  final String selectedDevice;

  const DeviceSelector(this.onDeviceSelected, {this.selectedDevice});

  @override
  State<StatefulWidget> createState() {
    return _DeviceSelector();
  }
}

class _DeviceSelector extends State<DeviceSelector> {
  Map<String, Device> _devices = {};
  bool _scanning = false;
  StreamSubscription<BluetoothDevice> _subscription;
  StreamSubscription<bool> _subscriptionScanStopped;
  @override
  void initState() {
    _subscription = FlutterScan.devices.listen((device) {
      setState(() {
        _devices[device.address] = device;
      });
    });
    _subscriptionScanStopped = FlutterScan.scanStopped.listen((_) {
      setState(() {
        _scanning = false;
      });
    });
    _scanning = true;
    FlutterScan.startScan();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        const Divider(
          height: kDividerHeight,
        ),
        //... build list of items,
        Container(
          padding: const EdgeInsets.all(kSmallPadding),
          decoration: const BoxDecoration(color: Colors.white),
          child: Row(
            children: <Widget>[
              Expanded(
                child: PlatformDialogAction(
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                  child: Text('cancel', style: TextStyle(color: kPrimaryColor)),
                ),
              ),
              Expanded(
                child: PlatformDialogAction(
                  onPressed: _scanning
                      ? null
                      : () {
                          _devices.clear();
                          _scanning = true;
                          FlutterScan.startScan();
                        },
                  child: Text('rescan', style: TextStyle(color: _scanning ? Colors.grey : kPrimaryColor)),
                ),
              ),
            ],
          ),
        )
      ],
    );
  }
}
```

So maybe I'm doing something wrong, so let me know :) so the main idea is to be able to interact with the buttons of the dialog (change state, colors, maybe text),  my solution with SimpleDialog work nice but I want to keep iOS dialog style and it's not possible. 

I also wanted to do only the simpleDialog iOS style in my app but the problem is that all the theme and constant about dialogs are only private inside flutter code, didn't find a way to access it. Shame to have to copy paste almost the all file. 

Here is the current look: 
![img_8724](https://user-images.githubusercontent.com/2970449/43628287-fb0a6510-96f9-11e8-9f38-6e74b86c4a74.jpg)

**Comment by matthew-carroll** [comment]
@jaumard I didn't completely follow what you're trying to do.  But the screenshot you attached is very different than anything on iOS and so we should not add it to Flutter's Cupertino offering.  You should feel free to publish your own library if you think what you're working on is useful in general.

If you believe that certain iOS details in Flutter should be made public, please file an issue for those and we'll take a look.

As for the standard iOS alert dialog, I've been doing a lot of work on that to make it match iOS.  You can follow that work at #18381

**Comment by matthew-carroll** [comment]
@jaumard If you need a button to update its content then one thing you can do is define your own StatefulWidget that surrounds a CupertinoDialogAction.  Then, within your StatefulWidget you can call setState() at any time to rebuild the button with your updated content.

For example:

```dart
showDialog(
    context: context,
    builder: (BuildContext context) {
        return new CupertinoAlertDialog(
            title: new Text('some title'),
            content: new Text('some message'),
            actions: <Widget>[
                // Instead of directly passing in a CupertinoDialogAction, pass in your StatefulWidget
                // which contains a CupertinoDialogAction within it.
                new MyStatefulWidget(),
                // more buttons here
            ],
        );
    }
);
```

If you need to update all the dialog content then you can do the same thing, but you can wrap the entire CupertinoAlertDialog with your own StatefulWidget and then call setState() as needed.

**Comment by zoechi** [comment]
This issue looks stale.
Please add a comment to have it reopened if you disagree.
