### ISSUE TITLE
Would like an option to clear on every Run

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2013]
Right now flutter logs persist between runs it seems, at least when running on my Android device from Atom.  For my workflow, I typically don't want that.  As I solve one issue and then want to see the next.

**Comment by HansMuller** [comment]
I agree. Viktor and I wasted some time yesterday sorting out a non-existent bug that was really just stale log output. Clearing the log before each run seems like a good default.

**Comment by eseidelGoogle** [comment]
I'm not sure what flutter-atom uses for log display.  adb logcat has known bugs where it won't clear logs correctly.  flutter logs attempts to work around such: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/device_android.dart#L341

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
We should double-check the logic, but both ios simulators and adb devices clear the log before a run by default: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/device_android.dart#L235.

**Comment by sethladd** [comment]
Thanks. Sounds like a bug, then?

**Comment by devoncarew** [comment]
Yeah, we just want to confirm that it is the adb bug that Eric mentioned, and see if we need to apply a workaround, like we use for `trace`.

**Comment by eseidelGoogle** [comment]
Do we plan to complete this for next Tues?  We can punt on it if necessary and see if others hit it.

**Comment by devoncarew** [comment]
I don't think I'll have time to do this.

**Comment by eseidelGoogle** [comment]
Punting.
