### ISSUE TITLE
Xcode build failure with error 'firebase_auth/FirebaseAuthPlugin.h' file not found

### ISSUE THREAD

**Issue by hui1103** [flutter/flutter#20135]
Hi All,

Sorry for my noob question.
My simple firebase auth project is working fine in Android Studio/IntelliJ and flutter build. 
However, it does not work in Xcode 9.4.1 build/Archive(Destination : Generic iOS Device).
It keeps throwing the build error : 'firebase_auth/FirebaseAuthPlugin.h' file not found

## Steps to Reproduce : 
1) Create simple flutter project by command line
> flutter create test
2) open project by Xcode, build the project,
add the /ios/Runner/GoogleService-Info.plist 
3) open project by IntelliJ/Android Studio
4) update the info.plist, add following code before </dict>
```
<!-- Google Sign-in Section -->
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<!-- Copied from GoogleServices-Info.plist key REVERSED_CLIENT_ID -->
				<string>com.googleusercontent.apps.466218294969-5mdmh6opkqd87a5m81nm83u4eqd3bvgk</string>
			</array>
		</dict>
	</array>
	<!-- End of the Google Sign-in Section -->
```

5) update pubspec.yaml to add
  google_sign_in: "^3.0.4"
  firebase_auth: ^0.5.15
6) run : flutter packges get
7) enter folder ios/, and run : pod install
8) open project by Xcode, 
8.1) Product > Destination > Generic iOS Device 
8.2) update Signing
8.3) Product > Build
9) see the build error : 'firebase_auth/FirebaseAuthPlugin.h' file not found

Everything works fine in AndroidStudio. 

I tried to build the project by
> flutter build ios

> open -a Simulator
> flutter run

It works fine in iOS simulator.

## Logs

Here is the output of flutter build iOS:
```
Building com.yesstyle.app for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: XYZ
Running pod install...                                      27.1s
Starting Xcode build...                                          
 ├─Building Dart code...                             212.0s
 ├─Assembling Flutter resources...                    2.7s
 └─Compiling, linking and signing...                 61.5s
Xcode build done.                                           534.2s
Built /Users/frontend/testing/build/ios/iphoneos/Runner.app.
```

Here is the output of pod install :
```
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Downloading dependencies
Installing Firebase (5.4.1)
Installing FirebaseAnalytics (5.0.1)
Installing FirebaseAuth (5.0.2)
Installing FirebaseCore (5.0.6)
Installing FirebaseInstanceID (3.1.1)
Installing Flutter (1.0.0)
Installing GTMOAuth2 (1.1.6)
Installing GTMSessionFetcher (1.2.0)
Installing GoogleSignIn (4.1.2)
Installing GoogleToolboxForMac (2.1.4)
Installing firebase_auth (0.0.1)
Installing google_sign_in (0.0.1)
Installing nanopb (0.3.8)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 13 total pods installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

Here is the result GeneratedPluginRegistrant.m :
```
//
//  Generated file. Do not edit.
//

#import "GeneratedPluginRegistrant.h"
#import <firebase_auth/FirebaseAuthPlugin.h>
#import <google_sign_in/GoogleSignInPlugin.h>

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FLTFirebaseAuthPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTFirebaseAuthPlugin"]];
  [FLTGoogleSignInPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTGoogleSignInPlugin"]];
}

@end

```

Here is the result of flutter analyse :  
```
Analyzing test...                                            
No issues found! (ran in 1.7s)
```

Here is my flutter doctor -v : 
```
$ ~/flutter/bin/flutter doctor -v

[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E199, locale en-HK)
    • Flutter version 0.5.1 at /Users/frontend/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 categories.
```

Thanks for viewing my question. Many thanks for any of help.

**Comment by hui1103** [comment]
Just found that the simple project works fine.

It is caused by my wrong search header setting of pods..

**Comment by rtessler** [comment]
It seems the search paths for firebaseAuth are wrong. It cant findfirebase_auth/FirebaseAuthPlugin.h. But where do I change this and to what

**Comment by kroikie** [comment]
@hui1103

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/727. Any further collaboration will be done there.

**Comment by phong764119** [comment]
try add this to your info.plist file
Copied from GoogleServices-Info.plist key REVERSED_CLIENT_ID and replace ...

<key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLSchemes</key>
            <array>
                
                <string>...</string>
            </array>
        </dict>
    </array>

**Comment by cleberamancio** [comment]
I just run pod install in project/ios. This work for me.

**Comment by NikolinNgjela** [comment]
I got the same issue, but only when I try **Product -> Archive** on Runner -> **Generic iOS Device**
If I run in on a device or simulator it runs correctly.

![image](https://user-images.githubusercontent.com/12495588/94378811-82d33280-012c-11eb-93f8-f087ff6f00af.png)
