### ISSUE TITLE
Flutter doctor is no able to install the dart sdk for the operating system

### ISSUE THREAD

**Issue by ashranbaig** [flutter/flutter#20148]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
This issue looks like it was posted by mistake.
It doesn't contain enough information to be actionable.
If you actually have a bug to report please create a new issue with more information about the scenario.

What actions did lead to the error message?
What Operating System?
How did you install Flutter and in what directory?
