### ISSUE TITLE
ListTile broken in 0.5.1 beta

### ISSUE THREAD

**Issue by opensourcegps** [flutter/flutter#20156]
After upgrading from 0.4.4 to 0.5.1, `ListTile` is broken and not centered properly. Title and subtitle is moved to the very top of `ListTile`, but should be in the middle, according to: https://material.io/design/components/lists.html#specs

 This is breaking change in the app.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)
• No issues found!
```

Code:

`flutter create myapp`

Change main.dart as follows:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(      
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
   
  
  @override
  Widget build(BuildContext context) {
  
    return new Scaffold(
      appBar: new AppBar(
        
        title: new Text(widget.title),
      ),
      body: new Center(
         
        child: new Column(
         
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[

            new ListTile(
                  trailing: const Icon(Icons.keyboard_arrow_right),   
                  title:  new Text('List Tile title'),
                  subtitle: new Text('List Tile subtitle'),
                  //subtitle: new Container(),
                  isThreeLine: true,
              ),

            new Card(
                child: new ListTile(
                  trailing: const Icon(Icons.keyboard_arrow_right),   
                  title:  new Text('List Tile title'),
                  subtitle: new Text('List Tile subtitle'),
                  //subtitle: new Container(),
                  isThreeLine: true,
              ),
            ),
            
            new Card(
                child: new ListTile(
                  trailing: const Icon(Icons.keyboard_arrow_right),   
                  title:  new Text('List Tile title'),                  
                  subtitle: new Container(),
                  isThreeLine: true,
              ),
            ),

            new Card(
                child: new ListTile(
                  trailing: const Icon(Icons.keyboard_arrow_right),   
                  title:  new Text('List Tile title'),                   
                  
              ),


            ),


          ],
        ),
      ),

    );
  }
}


```

The result with 0.5.1:

![screenshot_1533238226](https://user-images.githubusercontent.com/7678445/43606373-6ab6db46-969b-11e8-9043-f8129554b330.png)

Result with 0.4.4:

![screenshot_1533238379](https://user-images.githubusercontent.com/7678445/43606467-b4bd876c-969b-11e8-954f-2ec8efea1191.png)

**Comment by zoechi** [comment]
Could you try in `master` channel as well
```
flutter channel master
flutter doctor
```

**Comment by opensourcegps** [comment]
Same bug in master channel. Not centered properly.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.223, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!

```
Channel master, v0.5.8-pre.223, on Linux:
![screenshot_1533241398](https://user-images.githubusercontent.com/7678445/43608925-d465bccc-96a2-11e8-8093-058180174ea0.png)

**Comment by jason-simmons** [comment]
This changed in https://github.com/flutter/flutter/commit/ee019c0bca05c9d2293599e88aa2da0fdb9a76ce

@HansMuller

**Comment by opensourcegps** [comment]
This is critical problem because we see some crashes in Google Play console with 0.4.4, but we can not update to the latest version because of ListTile problem. 

Please provide details how to upgrade to 0.5.1 and then manually revert [ee019c0](https://github.com/flutter/flutter/commit/ee019c0bca05c9d2293599e88aa2da0fdb9a76ce) in the local copy. At least this will temporary mitigate the issue.

**Comment by shihaohong** [comment]
The change in https://github.com/flutter/flutter/pull/17496 seems to adhere to the Material specifications, as long as the `ListTile` parameters are properly utilized, [as per the ListTile docs](https://docs.flutter.dev/flutter/material/ListTile-class.html). A clearer description of behavior was introduced into the documentation in [a later PR].(https://github.com/flutter/flutter/commit/567db6f0d47ca95ab639dffab0aadeffe92c54e1#diff-53f33273ae4e7462729c5f4b7394428b)

In the example provided, from top to bottom:
ListTile 1, 2 & 3 - With `isThreeLine` set to `true`, the docs specify that three lines of content are expected and the space is created with this in mind
ListTile 4 - With `isThreeLine` set to `false` and having no `subtitle` provided, the `ListTile` configures the title to be a single line.

I wouldn't consider this a regression, but it will require users pre-v0.5.1 using `ListTile` to perhaps update their usage of the widget.

cc/ @HansMuller
