### ISSUE TITLE
Editor Wish: recognize extends StatelessComponent, extends StatefulComponent

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2015]
If I type `class Foo extends StatelessComponent` Atom appends `{}`. It would be even more helpful if it appended an empty build() method.

Similarly, if I type `class Foo extends StatefulComponent` Atom could generate a _FooState class and all the rest of the boilerplate.

**Comment by sethladd** [comment]
Our plugin could make it easier to discover "quick fixes", which in this case can add missing methods like build(). Try Control-1, I think.

We can also argue that the analyzer should just add those methods anyway. If your class isn't abstract, and you just defined it, just fill in all the required methods. Filed https://github.com/dart-lang/sdk/issues/25817 to track.

cc @kevmoo

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#465
