### ISSUE TITLE
Editor Wish: simplify adding a single-child parent Widget

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2016]
This comes up all the time as one realizes that a widget needs padding, or a border, or a background, etc.

Say I start with this:

```
  return new Foo(
    child: new Column(
      justifyContent: FlexJustifyContent.start,
      children: <Widget>[
        ...
      ]
    )
  );
```

and I want to end up with this:

```
return new Foo(
  child: new Padding(
    padding: const EdgeDims.all(16.0),
    child: new Column(
      justifyContent: FlexJustifyContent.start,
      children: <Widget>[
        ...
      ]
    )
  )
);
```

I'd like to be able to put the cursor inside the Column(), press a magic key to get:

```
return new Foo(
  child: new TBD(
    child: new Column(
      justifyContent: FlexJustifyContent.start,
      children: <Widget>[
        ...
      ]
    )
  )
);
```

which is easily finished by changing TBD to Padding and add the padding: parameter.

**Comment by sethladd** [comment]
@pq will the analyzer plugins allow us to add Quick Fixes? If so, we should be able to do this fairly straight forwardly, yes?

cc @scheglov @kevmoo for ideas, too

**Comment by scheglov** [comment]
Yes, DAS has [the extension point](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/plugin/edit/fix/fix.dart) for fixes.

**Comment by sethladd** [comment]
Nice! Looking forward to using them :)

**Comment by sethladd** [comment]
Should we move this, and other "affects: jetbrains-plugin" to their issue tracker?

cc @mit-mit

**Comment by pq** [comment]
> Should we move this, and other "affects: jetbrains-plugin" to their issue tracker?

SGTM. 

Incidentally, IDEA has it's own mechanism for code boiler-plate.  An alternative to using a DAS plugin, would be to contribute some [live code templates](https://blog.jetbrains.com/webide/2012/10/high-speed-coding-with-custom-live-templates/) to the Flutter plugin.  Not as smart since they can't leverage all that the analyzer but maybe in this case that's OK?

**Comment by sethladd** [comment]
Yeah, I think we need something like "smart" live code templates. We need to know if we're wrapping with something that takes a single child or multiple children.

**Comment by mit-mit** [comment]
> Should we move this, and other "affects: jetbrains-plugin" to their issue tracker?

I think that only makes sense for things that apply to "general Dart"? This seems Flutter specific (it would be odd to get this completion while typing Dart for Web or Server code).

@pq shouldn't this (and other Flutter specific issues) go to https://github.com/flutter/flutter-intellij/issues?

**Comment by sethladd** [comment]
> https://github.com/flutter/flutter-intellij/issues

Sorry, that's what I meant.

**Comment by pq** [comment]
SGTM 👍

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#443
