### ISSUE TITLE
Unable to make FloatingActionButton background color transparent.

### ISSUE THREAD

**Issue by zinwalin** [flutter/flutter#20166]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

------------
My code for FloatingActionButton:
```dart
new FloatingActionButton(
                    heroTag: 'backward',
                    **backgroundColor: Colors.transparent,**
                    foregroundColor: Colors.white,
                    child: new Icon(Icons.arrow_back),
                    onPressed: () => Navigator.pop(context),
                  ),
```
As expected, FloatingActionButton should be background transparent, but it's not as showed in the attached image.

**Comment by zinwalin** [comment]
@zoechi thanks your reply.  But it didn't work.  With your change, all buttons' background have a blur shadow which it's not correct.

**Comment by jogboms** [comment]
@zinwalin You need to apply the `Theme` directly above your `FloatingActionButton` widget.

**Comment by zinwalin** [comment]
@zoechi @jogboms  Fixed. The key to fix issue is to use property 'elevation' of FloatingActionButton, thanks for your inspiration.   I check definition of elevation in FloatingActionButton, it's: 

**The z-coordinate at which to place this button. This controls the size of the shadow below the floating action button.**
