### ISSUE TITLE
IDE-specific files should only be generated by `flutter create` when explicitly enabled

### ISSUE THREAD

**Issue by CherryMan** [flutter/flutter#20164]
Currently, `flutter create` generates files specific to IntelliJ and XCode. Not everyone uses these programs, so these files should not be generated unless the user specifically requires them.

**Comment by zoechi** [comment]
I think this is a dup of #14723

**Comment by CherryMan** [comment]
I also wanted to mention XCode.

**Comment by jmagman** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/14723.  The Xcode files are necessary to run any iOS or macOS app--there is no alternative IDE.  You can delete the `ios` or `macos` directories if you don't want your app to support those platforms.
