### ISSUE TITLE
Editor Wish: moving a list element

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2017]
If I had a nickel for every time I moved elements of a Dart list around and forgot to fix up the commas.

In the example below, it would be nice if one could put the cursor within the "new Flexible(...)" statement, hit a magic key several times - moving the scope of the selection outward - until the entire new Flexible() list element was selected. Then, with a different magic key, move the list element elsewhere in the list.

```
  children: <Widget>[
    new Text(destination.description[0], style: descriptionStyle),
    new Text(destination.description[1], style: descriptionStyle),
    new Text(destination.description[2], style: descriptionStyle),
    new Flexible(
      child: new Row(
        justifyContent: FlexJustifyContent.start,
        alignItems: FlexAlignItems.end,
        children: <Widget>[
          new Padding(
            padding: const EdgeDims.only(right: 16.0),
            child: new Text('SHARE', style: buttonStyle)
          ),
          new Text('EXPLORE', style: buttonStyle)
        ]
      )
    )
  ]
```

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#464
