### ISSUE TITLE
ScrollView/Draggable that allows scrolling in both directions (x, y) with overscroll physics

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#20175]
Use cases: tables, calendars, images.

It's quite difficult to do this with the current classes, as classes like `ScrollPosition`, `Scrollable` and `ScrollContext` only support one scroll direction.

The biggest problem I hit so far is that `ScrollPosition` stores it state directly in `ScrollContext.storageContext`, without a key. So when you have two `ScrollPosition`s in a single widget (one for each axis), those will override each other when the scroll offset is saved.

**Comment by justinmc** [comment]
I'm currently working on a demo for the gallery that shows how to do this.  I hope to turn it into its own widget after I get that merged. https://github.com/flutter/flutter/pull/25164

**Comment by lukepighetti** [comment]
Spent the better part of a day trying to get this setup and it feels like this is too far upstream in Flutter to make this a simple task for a layman. Requesting suggestions from team members for a strategy for making a PR against this issue.

**Comment by justinmc** [comment]
My plan was to take the [GestureTransformable](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/transformations/transformations_demo_gesture_transformable.dart) widget from that 2D Transformations gallery demo and move it into the main `widgets/` directory with a few improvements and tests.

I tried to write it in a way that it could easily be made into a first party widget, but there was more work I wanted to do to split it up to make it more reusable and generic.  I started working on that in [this branch](https://github.com/justinmc/flutter/tree/gesture-transformable) but haven't had time to finish it.  Ideally I wanted to split out a core public widget that accepted a `Matrix4` as a parameter and reported gestures on the transformed child, but didn't modify the matrix itself.  Then I wanted a higher level public widget that used the core one internally and worked more or less like GestureTransformable does in that demo.

I won't get to this myself for awhile, so if you want to take that code and turn it into a first party widget yourself, please do!

**Comment by apptum** [comment]
came here while searching for something similar what OP asked for:
I have a PageView and want to be able to transform its children while scrolling according to the dx (on horizontal scroll) movements. 
I tried using a RawGestureDetector with a custom PanGestureRecognizer, but that comes of the price of no longer having the BouncingScrollPhysics and the need to manually implement fling gestures etc...

@justinmc I looked at your GestureTransformable widget but it bugs me if there isn't a more simple solution than that for my specific use case... maybe you have an idea?:
It seems to me the easiest solution would be - while keeping all benefits of ListView/PageView and Physics - if ListView and PageView would register the user input movements (the drag) along their cross-axis.

**Comment by lukepighetti** [comment]
@apptum, this might be helpful for extracting DX for a single page inside a pageview

```dart
final thing = NotificationListener<ScrollNotification>(
  onNotification: (notification) {
    /// Our immediate PageView
    if (notification.depth == 0) {
      final PageMetrics metrics = notification.metrics;
      page = (metrics.page);

      /// page /

      return true;
    }

    /// Default to passing thru
    return false;
  },

  /// Row page view that builds individual cells
  child: PageView.whatever(),
);

/// Here's how to get dx
double get dx => (page - pageIndex).clamp(-1, 1).toDouble();

```

**Comment by apptum** [comment]
hey @lukepighetti & thanks! But on your answer I see that I misdescribed the problem: I want the cross-axis value of a scrollable! On a PageView that'd be the dy (when in default Axis.horizontal) ...

**Comment by l-k22** [comment]
Has anybody been able to make progress on this? I want to make an EPG (electronic/television programme guide) style layout but there doesn't seem to be anything out there that do it.

**Comment by muirandy** [comment]
That's great news @justinmc - I've been hoping for something like this for some time (see 23457).
My use case is similar to @l-k22 's: I need to put lots of custom sized boxes on the display, and be able to scroll about and zoom. The number and sizes of boxes will be dynamic.
I see your PR is nearly there, so I'll wait for it and give it a try out. :)

**Comment by Timmmm** [comment]
I'd like something similar for `ListView`. I have a list of items, but they can overflow the width so I want the list to be horizontally scrollable too. I did try wrapping the entire list in a horizontal `ScrollView` but it gave me errors about unbounded sizes. Maybe it works with a few more widgets but I feel like you should just be able to tell `ListView` to make the cross-axis scrollable.

**Comment by justinmc** [comment]
@muirandy I'm glad this will be useful!  I'm interested to see how the dynamic size of the boxes will work with this.  Let me know once it's merged and you try it out.

**Comment by justinmc** [comment]
@Timmmm Currently ListView can't scroll both axes.  This seems like something that should be doable with InteractiveViewer though.  I'll try to specifically try it out.  See this table example I made:

<img width="200" src="https://user-images.githubusercontent.com/389558/72296283-1c45cd00-360e-11ea-82a3-cb32265e1803.gif" />

**Comment by Timmmm** [comment]
@justinmc That looks interesting, thanks! Do you have a link to this "InteractiveViewer"? Google doesn't seem to know about it.

**Comment by justinmc** [comment]
It's still a work in progress, but hopefully I'll finish it soon: https://github.com/flutter/flutter/pull/44015

**Comment by yasinarik** [comment]
I need such a widget especially for using in Flutter Web. 

- It must have a smooth scrolling for both directions. Also, a bool property for locking the scroll direction after the scroll direction detected. (If it is horizontal, lock it to be scrolled only horizontally, else to be scrolled only vertically. This should be optional. Of course, the default behavior must be both directions. )

- Cells should be rendered on-demand as ListView.builder does. Otherwise, there will be a huge performance loss.

@justinmc Great news to hear! I really appreciate your work and am very thankful.

**Comment by justinmc** [comment]
@yasinarik Thanks for letting me know you need this, I was hoping to get some feedback like this.  I think your first bullet point should be fairly straightforward.  I'll try to include it in my PR.

The second bullet point will be a bit trickier, but I imagine it should be doable just like ListView.builder...  I won't be able to include it in the initial PR, but I think it's something we that would make sense to add afterwards.

**Comment by yasinarik** [comment]
@justinmc Great news!! Actually I've started something on my own too. I'll be available to share it next week :)

**Comment by justinmc** [comment]
The InteractiveViewer widget should now handle this, but it still has some missing features:

  * No on-demand rendering: https://github.com/flutter/flutter/issues/58603
  * Direction locking: https://github.com/flutter/flutter/issues/58043
  * Overscroll: https://github.com/flutter/flutter/issues/58042

**Comment by marcosagni98** [comment]
is there anyway this could be added to a datatable widget? -->Interactive viewer dataTable widget

* can zoom in and out
* scroll in both directions even in diagonal
* fixed title row

**Comment by marcosagni98** [comment]
@justinmc is there anyway in which in the computer i could say that the scroll wheel is for scrolling and then to zoom I have to press control + scroll wheel?
