### ISSUE TITLE
About Flutter Master Channel BottomApbar hasNotch attr.

### ISSUE THREAD

**Issue by kalismeras61** [flutter/flutter#20174]
Hello All, i am using flutter master channel for some reason but when i look BottomapBar widget hasNotch property removed. How can i do floatingAction button with hasNotch property true?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/commit/c39f2f26f7e74c516060fa3475876de21c38bbf3 explains it

**Comment by kalismeras61** [comment]
Thanks.
