### ISSUE TITLE
Google maps on info window on tap not getting called

### ISSUE THREAD

**Issue by DzinVision** [flutter/flutter#20178]
In [google maps plugin](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter) info window on tap is not getting called on iOS platform, but it is getting called on android.

**Comment by gerryhigh** [comment]
Thanks for submitting that. I had fixed it in my fork some time ago (https://github.com/gerryhigh/plugins/commit/b5a9c40814de6185b8615a25cc396c388e38928c ) but was too busy to do the PR.
