### ISSUE TITLE
propose other format to indent widgets components

### ISSUE THREAD

**Issue by cocodrino** [flutter/flutter#20188]
Hi guys, I'm not here to propose use jsx instead of plain dart, but I feel that it's hard to read the flutter components structure, I've tried for several  weeks but I'm still unconfortable reading this: it's not simple and fast know how some widget is composed, maybe you can get help from the editor (if you're using android studio) but it's not the idea, would be better improve the code legibility without need a extra tool...

I've tried several ways to format my code, right now, I've found a fairly good way (although can be improved) to format my code..for instance

```dart
return Expanded(
      child: Padding(
        padding: const EdgeInsets.all(4.0),
        child: new InkWell(
          onTap: onTap,
          child: new Container(
            height: 36.0,
            decoration: new BoxDecoration(
              color: backgroundColor,
              border: new Border.all(color: Colors.white, width: 1.0),
              borderRadius: new BorderRadius.circular(30.0),
            ),
            child: new Center(
              child: new Text(
                text,
                style: new TextStyle(color: textColor),
              ),
            ),
          ),
        ),
      ),
    );


```

what are my gripes here???
1) child components are mixed with "attributes components" so you can't understand the hierarchy here in a easy way
2) you can't understand how the components are composed simply reading from left to right (as xml) nor right to left (because child components and others are mixed)

so what would be my rules
1) component composition must be read from left to right...like xml...so you just need check the code and the indentation will be enought for understand what component is nested and the hierarchy
2) attribute components must have different indentation, avoiding noise when you're building the mental structure
3) attributes are not organized one by one one different lines, this is a waste of space and pollutes the code

this is the same code (can be improved the format)

```dart

      Expanded(child: 
        Padding(padding: const EdgeInsets.all(4.0),child:
          InkWell(onTap: onTap,child: 
            Container(height: 36.0, decoration: 
                      BoxDecoration(color: backgroundColor,
                            border: Border.all(color: Colors.white, width: 1.0,),
                            borderRadius: BorderRadius.circular(30.0)),child: 
              Center(child: 
                Text(text,style: TextStyle(color: textColr),),)
            )
          ),
        ),
      );


```

explaination: 
childs just have one tab for indent, so it's simple understand that this component is like

```
Expanded
   Padding
     InkWell
       Container
          Center
            Text
```
where can you understand and visualize the structure better???

attributes component has 3 tabs instead of one...so they're placing more to the right and can be ignored when you read the first time the code

many attributes for line...similar to xml

what do you think???...is it more simple to read for you too?...

thank you so much

**Comment by zoechi** [comment]
Closing as dup of #11609

**Comment by InMatrix** [comment]
The OP raised a valid point and the solution looks reasonable. I wonder if we can customize dartfmt to run some experiments. Cc: @munificent

**Comment by zoechi** [comment]
Sorry, seems I didn't pay attention when reading the issue.

**Comment by Hixie** [comment]
@cocodrino Can you help me understand your request? Are you asking for `dartfmt` to format code differently? Are you asking for us to use a different style in examples or in the framework?

**Comment by cocodrino** [comment]
HI @Hixie. @zoechi @InMatrix ,I find this formatting much more readable, concise and understandable at first sight, I would like to hear the opinion of others to see what they think, for now it is only my personal opinion but I wanted to show it and you yourselves compare both versions and see which is better.

Obviously I would like dartfmt to support this formatting and for the documentation to have this format as well, but obviously it is something that needs to be tested in greater depth and discussed, currently all the codes that I have transformed from one format to another end up being much more concise, clear and require less mental effort to be able to mentally visualize the structure and hierarchy of the components.

Thank you guys.

**Comment by Hixie** [comment]
Can you show how you would handle a Scaffold, a LayoutBuilder, or a Row?

**Comment by InMatrix** [comment]
I took a snippet from https://flutter.dev/docs/development/ui/widgets-intro and reformatted the way the OP preferred. This snippet includes named child slots such as those in Scaffold and AppBar.

Before:
```dart
return Scaffold(
  appBar: AppBar(
    leading: IconButton(
      icon: Icon(Icons.menu),
      tooltip: 'Navigation menu',
      onPressed: null,
    ),
    actions: <Widget>[
      IconButton(
        icon: Icon(Icons.search),
        tooltip: 'Search',
        onPressed: null,
      ),
    ],
  ),
  body: Center(
    child: Text('Hello, world!'),
  ),
  floatingActionButton: FloatingActionButton(
    tooltip: 'Add', // used by assistive technologies
    child: Icon(Icons.add),
    onPressed: null,
  ),
);

```
After:
```dart
return Scaffold(appBar: 
  AppBar(leading: 
    IconButton(icon: 
      Icon(Icons.menu), tooltip: 'Navigation menu', onPressed: null
    ),title: 
    Text('Example title'),actions: <Widget>[
      IconButton(icon: 
        Icon(Icons.search), tooltip: 'Search', onPressed: null)],
  ),body: 
  Center(child: 
    Text('Hello, world!'),
  ),floatingActionButton:
  FloatingActionButton(child:
    Icon(Icons.add),
    tooltip: 'Add', // used by assistive technologies
    onPressed: null,
  ),
);
```

The main benefit of the reformatted snippet is that widget names are lined up based on how deep they are in the hierarchy. 

The main question this new format raises is: how useful is it to see those named child slots when you're scanning a snippet? I did feel a little uncomfortable not seeing them as easy as I could before, but do I really *need* them to understand what the UI looks like? I'm not sure. This discomfort can potentially be mitigated by automatically re-ordering named child slots based on the reading order. For example, if the UI's directionality is set to be from left to right, then AppBar.leading will always show up before AppBar.title after reformatting.

**Comment by Hixie** [comment]
I certainly think you'd need them to do something like ListTile.

**Comment by Hixie** [comment]
It would also be weird to have builders done in this style, I think.

Overall my impression is that this is not an improvement, and I don't think we should adopt it for Flutter's framework's style.

**Comment by InMatrix** [comment]
I was thinking about custom format for individual users who find this format to read better. I talked to @munificent about this, but there are good reason to maintain a single code format for Dart. I'm investigating other avenues to address the issue from the IDE side. It's fine to close this issue for now.
