### ISSUE TITLE
Editor Wish: simplify adding a Widget that has children

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2018]
It would be nice if adding an element that has List<Widget> children parameter automatically formatted the and selected the children boilerplate.

For example, you type:

```
    new Flexible(
      child: new Row
    ) // I'm imagining that this close paren was added per 'new Flexible'
```

and Atom adds the boilerplate:

```
    new Flexible(
      child: new Row(
        children: <Widget>[
        ]
      )
    )
```

By automatically selecting the two lines begining with "children:" the developer can easily delete the boilerplate and substitute a list valued expression.

**Comment by sethladd** [comment]
* we need a flutter-aware formatter
* Atom might support snippets, which we could add. See https://atom.io/docs/latest/using-atom-snippets

If we have cases that aren't "smart" and we just want to add a snippet of code, I think we can do this easily.

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#463
