### ISSUE TITLE
Atom Wish: format region per the Flutter style guide

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2019]
Flutter's non-standard style is a good match for Dart's role as markup for deeply nested UI structure.

Doing the formatting by hand can be rather slow and tedious.

Of course we need a way to automatically format flutter code. From within Atom a way to apply the formatter to a file or region.

**Comment by eseidelGoogle** [comment]
We don't yet have an auto-formatter for flutter.  We're likely going to end up forking dart-fmt at some point.  I suspect we've filed a separate bug on that.  @munificent

**Comment by sethladd** [comment]
@eseidel I looked, but didn't find a flutter formatter bug. Would love to see what we can do to get the current dartfmt to be "tree-like code aware"

**Comment by sethladd** [comment]
Opened https://github.com/flutter/flutter/issues/2025 to track the request for a flutter-aware formatter.

**Comment by sethladd** [comment]
Hm, closing this one in favor of https://github.com/flutter/flutter/issues/2025 which seems more generic.
