### ISSUE TITLE
Tooltip ends up offscreen

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2020]
Long press on the search button in the Stocks demo:

![tooltip](https://cloud.githubusercontent.com/assets/1377460/13163664/c0db5772-d663-11e5-9656-890341871343.png)

**Comment by Hixie** [comment]
That's a bummer. There's a whole bunch of code in there that actively tries to avoid this, IIRC!

**Comment by Hixie** [comment]
I've also seen this with long-pressing on the X button of the chip in the chips demo in the gallery app.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/3574
