### ISSUE TITLE
BottomNavigationBar styling through ThemeData

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#20203]
### Problem:
I'd like to offer many app themes for a user to choose from. Therefore it would be useful to be able to style flutter "elements" independently from others through the `Theme` widget.

### Description
There are 3 things one would want to change in a (fixed) `BottomNavigationBar`

1. The background color
2. the active `BottomNavigationBarItem` color
3. the inactive `BottomNavigationBarItem` color

The current solution is
1. to change `ThemeData.canvasColor`
2. to change `BottomNavigationBar.fixedColor` or `ThemeData.primaryColor`
3. to change `ThemeData.textTheme.caption` or the widget passed to `BottomNavigationBarItem`

the problem with 1. and 3. is they could [mess up the app](https://stackoverflow.com/questions/49307858/style-bottomnavigationbar-in-flutter/)
and to change 2. through `ThemeData` you'd have to change `ThemeData.primaryColor` and therefore independent styling through ThemeData of the BottomNavigationBar is not possible.

(Similar material styling issue #19623)

**Comment by ebeem** [comment]
I can offer a workaround that might help ...
```
return new Theme(
   data: customThemeData,
   child: customThemeWidget,
);
```

you can have any Widgets as the `child` of a Theme object, they will all be styled according to the custom theme data that you provide independently from the other app widgets.
let me know if this works for you ...

**Comment by modulovalue** [comment]
Yes, this workaround works great, but fails at my specific use case.

If you're using your "main" widget inside a new route with a new Theme, every element wrapped inside a `Theme` will fail to animate to the new theme.

pseudocode:
```
main.dart
...
MaterialApp(
  theme: themeA,
  child: mainContent(),
)
...
```

[example gif](https://user-images.githubusercontent.com/24444584/43681022-86371e72-9848-11e8-8adb-e60bc5f64299.gif)

```
theme_selection.dart (inside a new route)
...
Theme(
  data: themeB,
  child: mainContent(),
)
...
```



I'm sure it's possible to solve that by tracking changes through an InheritedWidget, but this is a workaround that should not be needed.


What I mainly want to point out is that the theming is not flexible enough. @HansMuller what do you think?
Even though there are issues with higher priorities, it would be nice to (one day) be able to "theme" the app without having to go through workarounds.

**Comment by Allan-Nava** [comment]
Is possible to fix globally with a ThemeData globally?
