### ISSUE TITLE
Firebase - Cloud Storage - Continuing Uploads Across Process Restarts using Flutter

### ISSUE THREAD

**Issue by JigneshPatel23** [flutter/flutter#20226]
Firebase - Cloud Storage - Continuing Uploads Across Process Restarts using Flutter

I am looking for the feature to upload files on firebase cloud storage and handle the poor network situations or continuing uploads across process restarts.

I have a reference in Android for the same.

Continuing Uploads Across Process Restarts
Reference - https://firebase.google.com/docs/storage/android/upload-files#continuing_uploads_across_process_restarts

I can't able to find this in flutter package 'firebase_storage' - https://pub.dartlang.org/packages/firebase_storage

Can anyone help? This feature is work in progress or it's already there in the package.

**Comment by kroikie** [comment]
@JigneshPatel23

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/724. Any further collaboration will be done there.
