### ISSUE TITLE
How to update flutter app programmatically in Play/App store?

### ISSUE THREAD

**Issue by MaskyS** [flutter/flutter#20224]
When I send release a new version of my app on the play store, devices having the old version never see the update. The only way to get the changes is to reinstall the app. How do we update flutter apps programmatically?

**Comment by ebeem** [comment]
I will be releasing my app in a couple of days, I never tried to do it with a flutter project before.

However, I have released native apps before, and here is some information that might be helpful to you.

1- whenever you need to update your app, you need to submit a new version to PlayStore by using the `Create Release` feature in google play dashboard

2- PlayStore does **NOT** allow you to submit a version that has the same `versionCode` as the previous release, you can change this code from your `AndroidManifest.xml` file in `defaultConfig` section

3- when you submit a new release with a different version code number, then PlayStore will make your app updatable.

so always make sure to change your `versionCode` first and then create a new release after that

**Comment by MaskyS** [comment]
Thanks for the advice, ebeem! However, I've already done all that during
updates, but still didn't work. Maybe it's because I released my app as a
beta/unstable app?

**Comment by ebeem** [comment]
I had one of my apps on alpha, and updates worked perfectly.
maybe if no one helps, I will be trying this in a couple of days and let you know how things go

**Comment by MaskyS** [comment]
Please do 😄

**Comment by ArcticZeroo** [comment]
Are you sure it hasn't just rolled out yet? I've released several app updates on the play store and haven't done anything other than changed the version # in play console and project files.

**Comment by MaskyS** [comment]
Yes, I'm sure it had been rolled out first (I got the notification from Play Console). However, I encountered this issue ~3 months ago, it could be that this has been fixed now. I will verify and open again if needed. Thanks, @ArcticZeroo for sharing that.

**Comment by pedromorgan** [comment]
So bumping into same problem and last few days rolling 0.1 to .05 ie one per day and new flutter app

- takes around an hour to **appear** in playstore..
- auto client update takes around 8 to 20 hrs 
- however going into `Play > my Apps` and its checks and update is there after **appear**

Am not sure how to hack this... some thought are 
- to put a `const version ` somewhere in app and online when updated,
- somehow ask the flutter app to check for new version every hour

**Comment by NTMS2017** [comment]
There is an upgrader (mostly for iOS) and in_app_update plugin (for android). I try to implement them both and had a difficulty to do so. I post and issues in both plugin but I got no response. So if anyone use this 2 plugin successfully please can you share step-by-step approach details. Thanks

**Comment by MaskyS** [comment]
After another release recently, I figured out that the issue was that the previous version of the app installed on my device was signed using my debug key. https://stackoverflow.com/questions/27020815/play-store-having-new-version-of-the-app-but-not-showing-update
