### ISSUE TITLE
Camera plugin ignoring resolutionPreset

### ISSUE THREAD

**Issue by AlexBacich** [flutter/flutter#20222]
Hello.

I'm using camera plugin (^0.2.1). 

When taking photos it isn't using parameter resolutionPreset. Photos taken are always gigantic 3.840*2.160 JPEG 24-bit color on one phone, 3.456*4.4608 JPEG 24-bit color on another
http://take.ms/eKPGQ

Right from the example for library - changing ResolutionPreset values does nothing

controller = new CameraController(cameras[0], ResolutionPreset.medium);
 
I tried couple of Android phones - same problem, just different specific to phone resolution.

**Comment by AlexBacich** [comment]
According to the code (as far as I understood) - resolutionPreset only affects on preview size. But not on the taken photo size. Preview size is working. 
So I guess this issue should be changed from bug to feature request: adding ability to change quality \ size of photos taken.

**Comment by raymondr** [comment]
I also noticed this issue. The iOS version does set the capture image size based on ResolutionPreset.

**Comment by danielroek** [comment]
Doing a quick test on Android I find that taking a picture with ResolutionPreset.medium results in:
I/flutter (28622): File length is 120227
And taking a picture with ResoultionPreset.ultraHigh results in:
I/flutter (28622): File length is 1664740

Looks like this issue can be closed.

**Comment by mvanbeusekom** [comment]
Closing this issue, since it is fixed in version 0.5.3 which allows quality presets on Android as well.
