### ISSUE TITLE
Another way to add Flutter  to existing apps

### ISSUE THREAD

**Issue by koudle** [flutter/flutter#20225]
The article on the wiki  [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) introduce a way to add Flutter to existing apps. But it has a problem:
1、can't debug Dart code in the project
It's very inconvenient to debug method channel

Why not add exitsing apps to the android directory in the Flutter Project?
![image](https://user-images.githubusercontent.com/13464904/43676787-4f87bcc4-982a-11e8-945f-1ebb3314c340.png)

Why use  [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)  this way to add Flutter?

**Comment by shakil807g** [comment]
yes i am also using flutter same way in existing android app  i just create a new flutter project and copy all the code to android folder

**Comment by lgengsy** [comment]
nice  ...
