### ISSUE TITLE
Provide way to unfocus whatever is currently focused

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#20227]
I want to unfocus the currently focused FocusNode.

I can do this with a dodgy-feeling workaround `FocusScope.of(context).requestFocus(FocusNode())`.

(Actually, I'm holding a FocusNode just for this purpose in my StatefulWidget state, so I can dispose it properly later.)

I seems that it would be more direct to do this by doing `FocusScope.of(context).focus.unfocus()`. This almost works, but `_focus`, while managed by the `FocusScopeNode` isn't exposed as `focus`.

I could get to it by visiting all the managed nodes and asking which has focus. But that's getting silly.

So, I'd propose to expose a getter for `FocusScopeNode._focus` as `focus`, so that it's easy to get the node that has focus.

```
 flutter doctor -v
[✓] Flutter (Channel master, v0.5.8-pre.238, on Mac OS X 10.13.6 17G2208, locale en-GB)
    • Flutter version 0.5.8-pre.238 at /Users/steve/code/flutter
    • Framework revision ddd7e4ead1 (11 hours ago), 2018-08-03 21:10:33 -0700
    • Engine revision 4893b0760d
    • Dart version 2.0.0-dev.69.5.flutter-8bad5c7b29

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[✓] Connected devices (1 available)
    • iPhone X • 1E0393AA-EF50-42AA-A244-3279599BE2C1 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by b-cancel** [comment]
I just wanted to back up @SteveAlexander 
I'm having to the the exact same thing and It hurts to be so inefficient

this would be a great feature to have!

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/19552#issuecomment-410909751

**Comment by goderbauer** [comment]
I'd be curious to know why you need to unfocus whatever is focused? Usually, if you want to unfocus something I'd expect that you also own the corresponding FocusNode and can just call unfocus on that one.

**Comment by SteveAlexander** [comment]
“I'd be curious to know why you need to unfocus whatever is focused?”

Why would I want to unfocus anything else?

Okay, I can think of why I’d want to ensure that a specific widget doesn’t have the focus. But what if I want the UI to enter the state when nothing has the focus? To do that (in the absence of an API for it) is need to invent something that tracks all the focus nodes currently in play, and either track which has focus, or iterate over them to find which might be focused. Then unfocus it.

The FocusScopeNode already manages this collection of focus nodes. And it also tracks the node that has focus, but doesn’t expose it in its API. 

One specific need to unfocus whatever is focused in when I want to ensure a Keyboard is given an opportunity to go away, when I change tabs in a TabView. If one tab has a text field on it, it might have caused the keyboard to appear, so I want to defocus it when it goes out of view. 

Same applies to raising a modal, and various other UI interactions.

**Comment by komapeb** [comment]
2031 as a goal seems like a reasonable date for removing an underscore 😁

**Comment by gspencergoog** [comment]
Closing this, since you can do this with:
```dart
WidgetsBinding.instance.focusManager.primaryFocus?.unfocus();
```
