### ISSUE TITLE
How to navigate to a specific flutter route from an Android activity?

### ISSUE THREAD

**Issue by shakil807g** [flutter/flutter#20234]
I have an existing android application and i have integrated flutter in my project i want to call a flutter specific route which i define in my main method like this 

```dart
    class FlutterView extends StatelessWidget {
     @override
      Widget build(BuildContext context) {
      return new MaterialApp(
      title: 'Platform View',
      initialRoute: '/',
      routes: {
        '/': (context) => HomeScreen(),
        '/secound': (context) => MyCustomForm(),
        '/dashboard': (context) => DashBoardScreen(),
        '/login': (context) => LoginScreen(),
      },
      theme: new ThemeData(
        primarySwatch: Colors.red,
        textSelectionColor: Colors.red,
        textSelectionHandleColor: Colors.red,
        ),
       );
      }
    }
```

 from my android activity i am calling flutter activity like this
```dart
 startActivity(new Intent(this,FlutterActivity.class));
```

it does open my flutter activity but with the initialRoute: '/' which is fine but some time i want to open for eg( '/dashboard')  routes when i open a flutter activity how can i do it ??

**Comment by llearn** [comment]
##### 你应该创建自己的Activity，继承自FlutterActivity；重写createFlutterView。
##### You should create your own Activity, inherited from FlutterActivity; override createFlutterView.
```
public class MainActivity extends FlutterActivity {
    @Override
    public FlutterView createFlutterView(Context context) {
        WindowManager.LayoutParams matchParent = new WindowManager.LayoutParams(-1, -1);
        FlutterNativeView nativeView = this.createFlutterNativeView();
        FlutterView flutterView = new FlutterView(this, (AttributeSet) null, nativeView);
        flutterView.setInitialRoute("/dashboard");
        flutterView.setLayoutParams(matchParent);
        this.setContentView(flutterView);
        return flutterView;
    }
}

```
then
```
startActivity(new Intent(this,MainActivity.class));
```

**Comment by shakil807g** [comment]
@llearn   
but i don't want a separate activity for each flutter screen

**Comment by shakil807g** [comment]
there is a route property already available in flutter activity and i can call something like that

          Intent intent = new Intent(this,FlutterActivity.class);
          intent.putExtra("route","dashboard");
          startActivity(intent);`

**Comment by shakil807g** [comment]
@llearn  @mravn-google  There is another problem when i launch flutter screen eg( dashboard )  it has back button and it take back to home screen which is this  '/': (context) => HomeScreen(),  and i want to back to android activity instead

**Comment by llearn** [comment]
@shakil807g 

```
SystemNavigator.pop();
```


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by peterzagoranski** [comment]
I also expected, that this will work:

`intent.putExtra("route","dashboard");`

But it doesn't! Any suggestions?

**Comment by pandavickey** [comment]
first，**not set initialRoute** in your flutter code;
second, startactivity like this:

```
Intent intent = new Intent(context, YourFlutterActivity.class);
        intent.setAction(Intent.ACTION_RUN);
        intent.putExtra("route", page);
        context.startActivity(intent);
```

**Comment by VinciShark** [comment]
> ##### 你应该创建自己的Activity，继承自FlutterActivity；重写createFlutterView。
> ##### You should create your own Activity, inherited from FlutterActivity; override createFlutterView.
> ```java
> public class MainActivity extends FlutterActivity {
>     @Override
>     public FlutterView createFlutterView(Context context) {
>         WindowManager.LayoutParams matchParent = new WindowManager.LayoutParams(-1, -1);
>         FlutterNativeView nativeView = this.createFlutterNativeView();
>         FlutterView flutterView = new FlutterView(this, (AttributeSet) null, nativeView);
>         flutterView.setInitialRoute("/dashboard");
>         flutterView.setLayoutParams(matchParent);
>         this.setContentView(flutterView);
>         return flutterView;
>     }
> }
> ```
> 
> then
> 
> ```
> startActivity(new Intent(this,MainActivity.class));
> ```

but it show's black screen between splash screen and the first page

**Comment by oth-libs** [comment]
@VinciShark same problem here, I can't find any legit solution to make it seamless

**Comment by VinciShark** [comment]
@oth-libs Now I use FutureBuilder to wait for native method return Intent, then generate route.

**Comment by arifcebe** [comment]
> ##### 你应该创建自己的Activity，继承自FlutterActivity；重写createFlutterView。
> ##### You should create your own Activity, inherited from FlutterActivity; override createFlutterView.
> ```java
> public class MainActivity extends FlutterActivity {
>     @Override
>     public FlutterView createFlutterView(Context context) {
>         WindowManager.LayoutParams matchParent = new WindowManager.LayoutParams(-1, -1);
>         FlutterNativeView nativeView = this.createFlutterNativeView();
>         FlutterView flutterView = new FlutterView(this, (AttributeSet) null, nativeView);
>         flutterView.setInitialRoute("/dashboard");
>         flutterView.setLayoutParams(matchParent);
>         this.setContentView(flutterView);
>         return flutterView;
>     }
> }
> ```
> 
> then
> 
> ```
> startActivity(new Intent(this,MainActivity.class));
> ```

@VinciShark i just try this code and success open my flutter page. you just call onCreate

```kotlin
 override fun onCreate(savedInstanceState: Bundle?) {
        FlutterMain.startInitialization(this)
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)
        routeValue = intent.extras?.getString(ROUTE_NAME).toString()
    }
```
little bit different from example, cause use kotlin for my code. you can try it in java

**Comment by VinciShark** [comment]
@arifcebe Already "work" before adding

> FlutterMain.startInitialization(this)

But it just show a black screen between the splash screen and flutter page
After adding this line to override onCreate, nothing changes

I'm on Android 9, I guess if you are on iOS, and this issue only happens on Android?

Thanks, all the way.

**Comment by jmagman** [comment]
This has been added to the new embedding APIs (https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Activity#launch-flutteractivity) which is in the process of being stabilized in the next quarter. We're unlikely to add more features to the old Android embedding. Please take a look at the new guide and see if it satisfies your needs

**Comment by iapicca** [comment]
Hi @shakil807g 
given @jmagman last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by samiullah225** [comment]
> first，**not set initialRoute** in your flutter code;
> second, startactivity like this:
> 
> ```java
> Intent intent = new Intent(context, YourFlutterActivity.class);
>         intent.setAction(Intent.ACTION_RUN);
>         intent.putExtra("route", page);
>         context.startActivity(intent);
> ```

Thanks for the solution can you please tell how to get the Intent.putExtra("NAME","KK")  when flutter route is launched ?

**Comment by iapicca** [comment]
@samiullah225 
if you need help writing your application I recommend to ask a question on StackOverflow.com
as in the choice `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by yaizudamashii** [comment]
What about if we don't want a new engine for every flutter entry point?  In iOS, we can call `pushRoute(String)` from `FlutterViewController`.  Is there a similar method for Android add-to-app?

**Comment by zeeshan-iqbal-cs** [comment]
> first，**not set initialRoute** in your flutter code;
> second, startactivity like this:
> 
> ```java
> Intent intent = new Intent(context, YourFlutterActivity.class);
>         intent.setAction(Intent.ACTION_RUN);
>         intent.putExtra("route", page);
>         context.startActivity(intent);
> ```

How to pass the data between the pages in this case?

**Comment by TheStarkster** [comment]
@zeeshan-iqbal-cs did you find any solution so far?
