### ISSUE TITLE
assertion  report:  type 'ReversedListIterable<T>' is not a subtype of type 'List<T>

### ISSUE THREAD

**Issue by intra** [flutter/flutter#20232]
I/flutter ( 3688): The following assertion was thrown during performLayout():
I/flutter ( 3688): type 'ReversedListIterable<Goal>' is not a subtype of type 'List<Goal>'
I/flutter ( 3688): 
I/flutter ( 3688): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3688): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3688): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3688):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3688): 
I/flutter ( 3688): When the exception was thrown, this was the stack:
I/flutter ( 3688): #0      CalendarPagerState.pageView.<anonymous closure>.<anonymous closure> (package:gt_app/main/calendar/calendar_pager.dart:47:49)
I/flutter ( 3688): #1      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:197:20)
I/flutter ( 3688): #2      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:716:67)
I/flutter ( 3688): #3      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter ( 3688): #4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:716:26)
I/flutter ( 3688): #5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:55)
I/flutter ( 3688): #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter ( 3688): #7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter ( 3688): #8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter ( 3688): #9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter ( 3688): #10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter ( 3688): #11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter ( 3688): #12     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter ( 3688): #13     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
I/flutter ( 3688): #14     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:169:12)
I/flutter ( 3688): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #16     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
I/flutter ( 3688): #17     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1172:12)
I/flutter ( 3688): #18     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1090:20)
I/flutter ( 3688): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #36     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 3688): #37     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter ( 3688): #38     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 3688): #39     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 3688): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #44     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter ( 3688): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #47     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter ( 3688): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #49     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 3688): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #51     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter ( 3688): #52     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter ( 3688): #53     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter ( 3688): #54     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter ( 3688): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #59     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter ( 3688): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #76     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2831:13)
I/flutter ( 3688): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #78     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 3688): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #80     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #88     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #90     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #92     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 3688): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #94     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 3688): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 3688): #98     RenderView.performLayout (package:flutter/src/rendering/view.dart:125:13)
I/flutter ( 3688): #99     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 3688): #100    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter ( 3688): #101    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 3688): #102    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 3688): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 3688): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 3688): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 3688): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
Reloaded 0 of 559 libraries in 356ms.
I/flutter ( 3688): 4 Goals loaded
I/flutter ( 3688): #108    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 3688): #109    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 3688): #110    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/flutter ( 3688): (elided one frame from package dart:async)
I/flutter ( 3688): 
I/flutter ( 3688): The following RenderObject was being processed when the exception was fired:
I/flutter ( 3688):   RenderSliverFillViewport#91811 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 3688):   creator: SliverFillViewport ← Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#f6085] ←
I/flutter ( 3688):   Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 3688):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#78f7d] ←
I/flutter ( 3688):   _ExcludableScrollSemantics-[GlobalKey#74662] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ← ⋯
I/flutter ( 3688):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter ( 3688):   constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
I/flutter ( 3688):   scrollOffset: 12342.9, remainingPaintExtent: 411.4, crossAxisExtent: 547.4, crossAxisDirection:
I/flutter ( 3688):   AxisDirection.down, viewportMainAxisExtent: 411.4, remainingCacheExtent: 411.4 cacheOrigin: -0.0 )
I/flutter ( 3688):   geometry: null
I/flutter ( 3688):   no children current live
I/flutter ( 3688): This RenderObject has no descendants.

**Comment by jonahwilliams** [comment]
This indicates a bug in your code on line `CalendarPagerState.pageView.. (package:gt_app/main/calendar/calendar_pager.dart:47:49` - `ReversedListIterable<T>` is what you get when you call `List.reversed`, make sure to call `.toList()` if you are passing it to something that takes a List.

**Comment by chandukasm** [comment]
thank you! .toList() saved my day!
