### ISSUE TITLE
Update screenshot in Getting Started, to include new Slow Mode banner

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2024]
The Getting Started guide has a screenshot of the app that you should see. It's missing the new Slow Mode banner.

Let's update the screenshot.

**Comment by sethladd** [comment]
cc @qchong

**Comment by qchong** [comment]
Fix is in [PR #174](https://github.com/flutter/website/pull/174).

**Comment by qchong** [comment]
Marking as closed.
