### ISSUE TITLE
how flutter layout could avoid overflow while input dialog is triggered and occupied the space of screen

### ISSUE THREAD

**Issue by gaoyuqi** [flutter/flutter#20247]
hi all, 
     I wrote an application login page,  it seems good, but while we want to input something by triggering the input box,  the page layout is compressed， and flutter error shows:  it is overflow. 
anyone meets this case , could you give some hint?thanks in advance

**Comment by ebeem** [comment]
seems like you are not using a `ListView` or other scrollable containers in your code ... 
take a look at this 
https://www.didierboelens.com/2018/04/hint-4-ensure-a-textfield-or-textformfield-is-visible-in-the-viewport-when-has-the-focus/

it will help you create a login page that scrolls & focuses on `TextField` on click
to explain your problem quickly, when a keyboard shows up, it takes some space from the screen, your container expects to have a large screen, but it gets a smaller one after they keyboard shows up.
check the article above and see if it helps

**Comment by zoechi** [comment]
@gaoyuqi Looks like this is answered. Thanks @ebeem 
Please add a comment to get it reopened if you disagree.
