### ISSUE TITLE
Some unknown condition causes ValueNotifier listeners to be dropped

### ISSUE THREAD

**Issue by ArcticZeroo** [flutter/flutter#20242]
I'm running my app, and added something to have custom collapsible children using a SizeTransition. At some point, all of the SizeTransitions stop updating because every single ValueNotifier's listener gets dropped for some reason. I do not call `ValueNotifier.removeListener` at all in the app to my knowledge, and if so it's definitely not in a place that should affect this class.

Here's a video of the behavior: https://frozor.io/up/Q8l3ZjYK.mp4 obviously you can't see mouse clicks but when they stop collapsing/expanding that's when all the listeners disappeared.

I put some debug into `flutter/foundation/change_notifier.dart` (on my local version of flutter) to try to track it down, here's the super long logs for that: https://gist.github.com/ArcticZeroo/697809f2d5f337e43a0a806552f81908
Those last three stacktraces show the places where my movies' ValueNotifiers get their listeners removed. At this point, changing the value of `isCollapsed` stops sending listener notifications.

## Steps to Reproduce

I'm trying to figure out a short way to reproduce the problem. I believe it to be related to Scrollables and ValueNotifiers on children of the Scrollable, but I'm not really sure how this could be possible. Based on the stacktrace though, something about how the screen scrolls due to the movie displays being in a ListView may be causing the scroll position rendering to do this. But I don't understand that whole bit enough to give you all anything super helpful.

If somehow this has been reported/discussed before or someone knows the inner workings of ChangeNotifier and scrollables, hopefully I don't have to figure out the reproducible code. 

In the mean time, here's the relevant lines from my code: https://github.com/ArcticZeroo/msu_helper/blob/master/lib/widgets/collapsible/collapsible_custom.dart#L40 and https://github.com/ArcticZeroo/msu_helper/blob/master/lib/widgets/collapsible/collapsible_custom.dart#L52

This class is being used here https://github.com/ArcticZeroo/msu_helper/blob/master/lib/widgets/movie_night/movie_display.dart#L226

## Logs

flutter verbose run: https://gist.github.com/ArcticZeroo/8ed52c51b26471507b37e8c5c19db0e4

flutter analysis (all import warnings): https://gist.github.com/ArcticZeroo/055ce93374a251e8221b3286a83b0290 

flutter doctor just complains about VSCode (which I don't use for flutter): https://gist.github.com/ArcticZeroo/8fd96afbde5a96ae525a006db33d2987

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by ArcticZeroo** [comment]
It has been a while so I don't remember the details 100%, but it was something along the lines of the fact that my `MovieDisplay` widget was stateful, so some rebuild caused the listeners to get killed for some reason. 

This commit I made apparently fixes it: https://github.com/ArcticZeroo/msu_helper/commit/440a011d4b19f67c058c182110e35dd286636055

It looks like the only actual changes made (aside from setting `isEnabled: true`, which is just whether tap to collapse/expand is enabled) were to clean up after itself (the lack of cleanup shouldn't cause listeners to be dropped though), and to make it a stateless widget.

I will investigate later when I get a chance to see if I can reproduce it in a way that is less wonky and might be an issue with how ValueNotifiers work with state, but I'm guessing it might just be an issue with my code
