### ISSUE TITLE
Command “flutter create –t module xxx” is not work

### ISSUE THREAD

**Issue by KuoGao** [flutter/flutter#20249]
I want to Add Flutter to existing apps , but command "flutter create –t module xxx" is not work,
exec command "flutter create –t module xxx" , and output "Multiple output directories specified."

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.241, on Mac OS X 10.12.6 16G1510, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.

**Comment by zoechi** [comment]
I tried and it worked for me. 

```
[✓] Flutter (Channel master, v0.7.1-pre.4, on Mac OS X 10.13.6 17G65, locale en-AT)
```

```
 $ flutter create -t module xxx
Creating project xxx...
  xxx/xxx.iml (created)
  xxx/.gitignore (created)
  xxx/.metadata (created)
  xxx/pubspec.yaml (created)
  xxx/README.md (created)
  xxx/lib/main.dart (created)
  xxx/xxx_android.iml (created)
  xxx/.idea/libraries/Flutter_for_Android.xml (created)
  xxx/.idea/libraries/Dart_SDK.xml (created)
  xxx/.idea/modules.xml (created)
  xxx/.idea/workspace.xml (created)
Running "flutter packages get" in xxx...                    10.3s
Wrote 11 files.

Your module code is in lib/main.dart in the xxx directory.
```

You probably need a newer Flutter version.

Upgrade using
```
flutter upgrade
```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
