### ISSUE TITLE
listview always have extra white space at bottom

### ISSUE THREAD

**Issue by wesleyxiao** [flutter/flutter#20241]
i have a listview build inside a container, which height is giving.

when i scroll to end to list, there always have a white space there.

i am using iphone x simulator.

<img width="322" alt="screen shot 2018-08-05 at 5 17 58 pm" src="https://user-images.githubusercontent.com/2177367/43690197-f3f0c5cc-98d3-11e8-9b3e-4b727246a431.png">

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by wesleyxiao** [comment]
since yesterday i been keep testing why there is extra white space on bottom of container which height is giving, but have no result.

which if i make listview height as screen height, bottom will no extra white space, it is weird :(

**Comment by zoechi** [comment]
Similar to https://github.com/flutter/flutter/issues/19648

Enable debugPaint to investigate where this padding comes from

![image](https://user-images.githubusercontent.com/405837/44569868-0d8e1a00-a77c-11e8-9589-4fc8f64c2711.png)

**Comment by zoechi** [comment]
Is this still an issue?

https://stackoverflow.com/questions/52105557/how-to-remove-automatic-safearea-from-listview/52106410#52106410 
or https://docs.flutter.io/flutter/widgets/ScrollView/shrinkWrap.html
might help

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
