### ISSUE TITLE
The example of android_alarm_manager plugin version 0.1.1 failed to work on my Ubuntu 16.04

### ISSUE THREAD

**Issue by yubrshen** [flutter/flutter#20246]
I just cloned https://github.com/flutter/plugins and did 
at example/
executing 
flutter run

I didn't observe any execution of the background print out, but eventually saw the following error:
```
2018-08-05 21:16:30 /media/yubrshen/rootOld/home_extent_rootOld/MobileExamples/plugins/packages/android_alarm_manager/example
$ flutter run
Launching lib/main.dart on LG SP200 in debug mode...
Initializing gradle...                                       0.6s
Resolving dependencies...                                    0.7s
Running 'gradlew assembleDebug'...                               
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
I/FlutterActivityDelegate(21819): onResume setting current activity to this
I/flutter (21819): [2018-08-05 21:18:28.704893] Hello, main()! isolate=709246965 user='FirebaseUser({providerId: firebase, uid: 9RBh35sAShXJKmRWcSSsZh5QFrR2, displayName: , email: , phoneNumber: , isAnonymous: true, isEmailVerified: false, providerData: [{providerId: firebase, uid: 9RBh35sAShXJKmRWcSSsZh5QFrR2, displayName: , email: , phoneNumber: }]})' token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmNTRmZjM0MTFiZmMwMDJiYTBjZDAwNzA2YmEzYmM4NTBiZWIwMmIifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmx1dHRlci1wbHVnaW5zLWFsYXJtbWFuYWdlciIsInByb3ZpZGVyX2lkIjoiYW5vbnltb3VzIiwiYXVkIjoiZmx1dHRlci1wbHVnaW5zLWFsYXJtbWFuYWdlciIsImF1dGhfdGltZSI6MTUzMzUyNjk2NSwidXNlcl9pZCI6IjlSQmgzNXNBU2hYSkttUldjU1NzWmg1UUZyUjIiLCJzdWIiOiI5UkJoMzVzQVNoWEpLbVJXY1NTc1poNVFGclIyIiwiaWF0IjoxNTMzNTI2OTY2LCJleHAiOjE1MzM1MzA1NjYsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnt9LCJzaWduX2luX3Byb3ZpZGVyIjoiYW5vbnltb3VzIn19.HaDWpICIHGOHMgAnASPBZaiv_Hs6ZfbW89vn1av8pVzVkObme8JDlLzM-Gtk6Dw16kmk5xJU89AX6To8TYjIYhZddTnYCZDsLls__Y8lfkz0DtqCRqRXiXtCMSbtHdjilBorRiq-Kq8fYBhwBJY6QoY6dvMN
Syncing files to device LG SP200...                          2.7s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on LG SP200 is available at: http://127.0.0.1:8104/
For a more detailed help message, press "h". To quit, press "q".
I/FlutterActivityDelegate(21819): onResume setting current activity to this
I/Timeline(21819): Timeline: Activity_idle id: android.os.BinderProxy@c9368d3 time:100112415
I/ViewRootImpl(21819): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(21819): ViewRoot's Touch Event : ACTION_UP
I/FlutterActivityDelegate(21819): onResume setting current activity to this
I/Timeline(21819): Timeline: Activity_idle id: android.os.BinderProxy@c9368d3 time:100174870
I/ViewRootImpl(21819): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(21819): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(21819): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(21819): ViewRoot's Touch Event : ACTION_UP
D/AndroidRuntime(21819): Shutting down VM
E/AndroidRuntime(21819): FATAL EXCEPTION: main
E/AndroidRuntime(21819): Process: io.flutter.plugins.androidalarmmanagerexample, PID: 21819
E/AndroidRuntime(21819): java.lang.AssertionError: This Flutter engine instance is already running an application
E/AndroidRuntime(21819): 	at io.flutter.view.FlutterNativeView.runFromBundle(FlutterNativeView.java:77)
E/AndroidRuntime(21819): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onStartCommand(AlarmService.java:168)
E/AndroidRuntime(21819): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3455)
E/AndroidRuntime(21819): 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
E/AndroidRuntime(21819): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E/AndroidRuntime(21819): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21819): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(21819): 	at android.app.ActivityThread.main(ActivityThread.java:6351)
E/AndroidRuntime(21819): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21819): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
E/AndroidRuntime(21819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
```
Please let me know if there is anything wrong with my environment. I just cloned the repository. My Flutter environment was able to run with some other plugins.

**Comment by yubrshen** [comment]
To simplify the scenario, I commented out the call to .periodic(), just leaving the call .oneShot(), 
It's still failed with similar error:
Launching lib/main.dart on LG SP200 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(22143): onResume setting current activity to this
I/flutter (22143): [2018-08-05 21:26:12.338731] Hello, main()! isolate=925097333 user='FirebaseUser({providerId: firebase, uid: 9RBh35sAShXJKmRWcSSsZh5QFrR2, displayName: , email: , phoneNumber: , isAnonymous: true, isEmailVerified: false, providerData: [{providerId: firebase, uid: 9RBh35sAShXJKmRWcSSsZh5QFrR2, displayName: , email: , phoneNumber: }]})' token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmNTRmZjM0MTFiZmMwMDJiYTBjZDAwNzA2YmEzYmM4NTBiZWIwMmIifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmx1dHRlci1wbHVnaW5zLWFsYXJtbWFuYWdlciIsInByb3ZpZGVyX2lkIjoiYW5vbnltb3VzIiwiYXVkIjoiZmx1dHRlci1wbHVnaW5zLWFsYXJtbWFuYWdlciIsImF1dGhfdGltZSI6MTUzMzUyNjk2NSwidXNlcl9pZCI6IjlSQmgzNXNBU2hYSkttUldjU1NzWmg1UUZyUjIiLCJzdWIiOiI5UkJoMzVzQVNoWEpLbVJXY1NTc1poNVFGclIyIiwiaWF0IjoxNTMzNTI2OTY2LCJleHAiOjE1MzM1MzA1NjYsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnt9LCJzaWduX2luX3Byb3ZpZGVyIjoiYW5vbnltb3VzIn19.HaDWpICIHGOHMgAnASPBZaiv_Hs6ZfbW89vn1av8pVzVkObme8JDlLzM-Gtk6Dw16kmk5xJU89AX6To8TYjIYhZddTnYCZDsLls__Y8lfkz0DtqCRqRXiXtCMSbtHdjilBorRiq-Kq8fYBhwBJY6QoY6dvMN
Syncing files to device LG SP200...
D/AndroidRuntime(22143): Shutting down VM
E/AndroidRuntime(22143): FATAL EXCEPTION: main
E/AndroidRuntime(22143): Process: io.flutter.plugins.androidalarmmanagerexample, PID: 22143
E/AndroidRuntime(22143): java.lang.AssertionError: This Flutter engine instance is already running an application
E/AndroidRuntime(22143): 	at io.flutter.view.FlutterNativeView.runFromBundle(FlutterNativeView.java:77)
E/AndroidRuntime(22143): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onStartCommand(AlarmService.java:168)
E/AndroidRuntime(22143): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3455)
E/AndroidRuntime(22143): 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
E/AndroidRuntime(22143): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E/AndroidRuntime(22143): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22143): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(22143): 	at android.app.ActivityThread.main(ActivityThread.java:6351)
E/AndroidRuntime(22143): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22143): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
E/AndroidRuntime(22143): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
I/Process (22143): Sending signal. PID: 22143 SIG: 9
Lost connection to device.

**Comment by yubrshen** [comment]
With only one call to .periodic(), it still failed with similar error:
Launching lib/main.dart on LG SP200 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(22515): onResume setting current activity to this
I/flutter (22515): [2018-08-05 21:30:58.435716] Hello, main()! isolate=646225365 user='FirebaseUser({providerId: firebase, uid: 9RBh35sAShXJKmRWcSSsZh5QFrR2, displayName: , email: , phoneNumber: , isAnonymous: true, isEmailVerified: false, providerData: [{providerId: firebase, uid: 9RBh35sAShXJKmRWcSSsZh5QFrR2, displayName: , email: , phoneNumber: }]})' token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImZmNTRmZjM0MTFiZmMwMDJiYTBjZDAwNzA2YmEzYmM4NTBiZWIwMmIifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmx1dHRlci1wbHVnaW5zLWFsYXJtbWFuYWdlciIsInByb3ZpZGVyX2lkIjoiYW5vbnltb3VzIiwiYXVkIjoiZmx1dHRlci1wbHVnaW5zLWFsYXJtbWFuYWdlciIsImF1dGhfdGltZSI6MTUzMzUyNjk2NSwidXNlcl9pZCI6IjlSQmgzNXNBU2hYSkttUldjU1NzWmg1UUZyUjIiLCJzdWIiOiI5UkJoMzVzQVNoWEpLbVJXY1NTc1poNVFGclIyIiwiaWF0IjoxNTMzNTI2OTY2LCJleHAiOjE1MzM1MzA1NjYsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnt9LCJzaWduX2luX3Byb3ZpZGVyIjoiYW5vbnltb3VzIn19.HaDWpICIHGOHMgAnASPBZaiv_Hs6ZfbW89vn1av8pVzVkObme8JDlLzM-Gtk6Dw16kmk5xJU89AX6To8TYjIYhZddTnYCZDsLls__Y8lfkz0DtqCRqRXiXtCMSbtHdjilBorRiq-Kq8fYBhwBJY6QoY6dvMN
Syncing files to device LG SP200...
D/AndroidRuntime(22515): Shutting down VM
E/AndroidRuntime(22515): FATAL EXCEPTION: main
E/AndroidRuntime(22515): Process: io.flutter.plugins.androidalarmmanagerexample, PID: 22515
E/AndroidRuntime(22515): java.lang.AssertionError: This Flutter engine instance is already running an application
E/AndroidRuntime(22515): 	at io.flutter.view.FlutterNativeView.runFromBundle(FlutterNativeView.java:77)
E/AndroidRuntime(22515): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onStartCommand(AlarmService.java:168)
E/AndroidRuntime(22515): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3455)
E/AndroidRuntime(22515): 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
E/AndroidRuntime(22515): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
E/AndroidRuntime(22515): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22515): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(22515): 	at android.app.ActivityThread.main(ActivityThread.java:6351)
E/AndroidRuntime(22515): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22515): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
E/AndroidRuntime(22515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
I/Process (22515): Sending signal. PID: 22515 SIG: 9
Lost connection to device.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Is this still an issue?
A new overhauled version was released recently. See #17566

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
