### ISSUE TITLE
[Feature Request] Draggable onDragCompleted needs velocity and offset as well

### ISSUE THREAD

**Issue by snoofer** [flutter/flutter#20258]
Right now only onDraggableCanceled gets velocity and offset. But we need them as well when an item is dropped on an DragTarget.

Right now there is now way to detect where on the DragTarget an item was dropped and that's a featues we're really missing. 

Thanks.

**Comment by diegotori** [comment]
@zoechi, PR #22267 managed to implement this issue BTW. Dunno if it needs to be open anymore.

**Comment by zoechi** [comment]
@snoofer is this fixed for you as well?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
