### ISSUE TITLE
How to disable Ripple effect when use Material Design?

### ISSUE THREAD

**Issue by specneeo** [flutter/flutter#20250]
write once, run anywhere. I use Material for my Application, but do not want ripple effect in ios, how to disable this effect?

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/50020523/how-to-disable-default-widget-splash-effect-in-flutter might help

https://github.com/flutter/flutter/issues/3782 looks related as well

Wrapping the material with a custom implementation of https://github.com/flutter/flutter/blob/ce8ba6e8b32cf2f11291c2da1b0807c3c1fe6a44/packages/flutter/lib/src/material/material.dart#L67 that doesn't add an ink-feature might also work.

None of these tried myself.

**Comment by specneeo** [comment]
@zoechi  thanks, https://stackoverflow.com/questions/50020523/how-to-disable-default-widget-splash-effect-in-flutter works.

**Comment by dJani97** [comment]
As of the present release, this is still an issue. Why is it in closed state?
