### ISSUE TITLE
Navigate between two screens 

### ISSUE THREAD

**Issue by BlizzaN** [flutter/flutter#20263]
Hello, I have a question regarding navigating between two screens. 
When I try to navigate with a toolbaraction to display a new screen I get this error then:

**Unhandled exception:
Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.**

Here is my code when I try to navigate:

 @override
  Widget build(BuildContext context) {

    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text("Test"),
        ),
       body: displayMap(context),
      )
    );
  }
}

 displayMap(BuildContext context) {
    /*mapView.onCameraChanged.listen((cameraPosition){
      print("Camera: ${cameraPosition.center}");
    });*/

     mapView.show(
       new MapOptions(
         title: "Antal kameror: $numberCamera",
         hideToolbar: false,
         showUserLocation: true,
         showMyLocationButton: true,
         initialCameraPosition:
         new CameraPosition(new Location(0,0), 6.0),
       ),
       toolbarActions: <ToolbarAction>[
         new ToolbarAction("Byt radie", 1),
       ],

     );

    mapView.onToolbarAction.listen((identifier){
      switch(identifier){
        case 1:
          //mapView.dismiss();
        print("Navigate to DisplayAlertView");

**Here is the problem when I try to navigate**
          Navigator.push(context, MaterialPageRoute(builder: (context) => new DisplayAlertView()));
          break;
      }
    });

    mapView.onLocationUpdated.listen((location){
      double latitude = location.latitude;
      double longitude = location.longitude;

      for(int i = 0; i < points.length; i++){
        cameraRadius(latitude, longitude, points[i].getY(), points[i].getX());
      }

    });

    mapView.onMapReady.listen((_){
      mapView.visibleAnnotations;
    });

    mapView.setMarkers(markers);
  }

** I would like to display this alertdialog and when I press "ok" I'll pop the screen and come back to the map **
class DisplayAlertView extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new AlertDialog(
        title: new Text("Testing"),
        actions: <Widget>[
          new FlatButton(
            child: const Text("Ok"),
            onPressed: (){
              Navigator.pop(context);
            },
          ),
        ],
      ),
    );
  }
}

**Comment by sir-boformer** [comment]
Put your `Scaffold` and everything under it into a custom ``StatelessWidget`` (name it `HomePage`), and it should work.
