### ISSUE TITLE
Code lab doesn’t explain how to get Flutter SDK

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2026]
Feedback was "Code lab doesn’t explain how to get Flutter SDK"

**Comment by abarth** [comment]
IMHO, we should point to the "getting started" instructions on flutter.io for this purpose.  They should be canonical and battle tested.

**Comment by qchong** [comment]
I've made a few changes to make the setup instructions clearer:

* In 'Step 1: Overview', I've added a 'Frequently Asked Questions' section immediately following 'What you need'. The FAQ points to detailed instructions for installing the Flutter SDK and Atom editor, and iOS and Android setup.
* In 'Step 3: Start a new Flutter project', I've added a note to remind users that they'll need to follow the instructions on the [Flutter Setup](https://flutter.io/setup/) page as a prerequisite.

**Comment by qchong** [comment]
Marking as closed.
