### ISSUE TITLE
Process: checking that all strings are translated before a release of the Flutter Gallery

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#20271]
Currently, my understanding of the current release process is that we push out new builds of the flutter_gallery app as part of each dev release.

We also send the .arb string files to human translators at each dev release.

This means that a dev release with new, untranslated strings in it could enter the gallery app without correct translations.

One possibility to stabilize the translations around beta releases would be to disqualify preview/beta candidates that aren't fully translated.  We could also block preview/beta releases until we are able to cherrypick completed translations into the branch.

@Hixie @HansMuller FYI

**Comment by Hixie** [comment]
Seems reasonable on its face, but how often will we have outstanding translations?

**Comment by DaveShuckerow** [comment]
Material translations currently includes 40 strings ([source](https://github.com/flutter/flutter/blame/eda03e2586b186ffcf8ea2d4424232710dbb7c81/packages/flutter_localizations/lib/src/l10n/material_en.arb): ctrl+f for "@").

According to the blame layer, those strings were added in over 13 changes:
* #11829
* #11967
* #11832
* #13312
* #11989
* #12021
* #12062
* #13714
* #13152
* #13543
* #13711
* #16633
* #17629

All these changes except for the last 2 are >6mo old.  In other words, we're currently adding strings at a rate of ~1-2/quarter.  The only cause for adding new ones so far has been a11y improvements and the addition of new widgets (such as the pending #20108).

There's also the use case of adding support for new locales.  New languages will have the same issue as new strings in existing languages. Although I'm not sure about our practices for doing this.  From what I can tell we haven't added new languages since the 20 we added to support Mulligan (#19567), which was ~4 months after the next-most-recent languages addition (#17121).

**Comment by HansMuller** [comment]
I also think that having "official" translations for all messages is a sensible gate for a beta release. Currently it takes 1-2 weeks for the official translations to roll in.

**Comment by TahaTesser** [comment]
Hi @DaveShuckerow 
Do you think this  issue is still valid for https://github.com/flutter/gallery since `flutter_gallery` is no longer available
Thank you

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
