### ISSUE TITLE
Android Studio: Autocomplete removes code

### ISSUE THREAD

**Issue by AskYous** [flutter/flutter#20277]
I'm not sure where to submit this. I don't even know if it's a flutter bug, Android studio bug, or a Dart bug.

Please see the video here: https://imgur.com/CcKkYeF

Sometimes, when I auto-complete, it deletes the following text and gets very annoying. I don't know why it happens in some cases but not others.

I was on MacOS. I just found it if I press `tab`, it does this bug, but it works fine when I press `enter`.

**Comment by zoechi** [comment]
There are different keys to replace or insert. Check the IntelliJ/AS docs or your keyboard shortcut settings in AS

See also 
- https://stackoverflow.com/questions/35424303/intellij-autocompletion-replacing-the-subsequent-word
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/207001055-How-to-make-autocomplete-replace-the-element-it-is-called-on-
- https://www.jetbrains.com/help/idea/auto-completing-code.html

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by AskYous** [comment]
No it's not. It seems that's intended.

**Comment by heatonandy** [comment]
This is extremely annoying at any rate... happening to me too and driving me crazy.  I can't believe that's intended!

**Comment by zoechi** [comment]
You can configure that behavior in the IDE

**Comment by MartinNiederl** [comment]
> You can configure that behavior in the IDE

@zoechi where exactly can you configure this behaviour?

**Comment by zoechi** [comment]
@MartinNiederl https://www.jetbrains.com/help/idea/auto-completing-code.html should explain all options for IntelliJ/AndroidStudio
