### ISSUE TITLE
Codelab doesn't instruct how to enable developer options on the device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2028]
“, you must enable Developer options in your device’s Settings” -- doesn’t tell me how to do this.

**Comment by abarth** [comment]
IMHO, the code lab should point to the "getting started" instructions, which have all this information.  Otherwise we're going to have to replicate the instructions and they'll get out-of-sync.

**Comment by sethladd** [comment]
Agreed. Both documents will live in the public for quite a while.

**Comment by qchong** [comment]
Fixed by adding the instructions for Android setup in the [Flutter Setup](https://flutter.io/setup/#android-setup) page, based on content shared by abarth@. 

I've also added links in the codelab to point to the setup instructions above.

**Comment by qchong** [comment]
Marking as closed.
