### ISSUE TITLE
There is a ListView problem

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#20287]
When I use ListView in my app with Column, like this(I streamlined the code):
```
Column(children:[
    Widget(),
    ........
    Expanded(child: ListView()),
    Widget(),
])
```
Then when I scroll the ListView to bottom, it always show it's children under the last Widget(), it's beyond the scope of Expanded.But when I slightly scroll up a bit, it become normal and stay in right place.
So, I think maybe it's a bug of flutter.

**Comment by polmp** [comment]
I've tested again with Flutter 0.7.1-pre.7 and now the TextField is above the ListView, so it seems solved.

**Comment by zoechi** [comment]
Thanks for the feedback!
