### ISSUE TITLE
ZWJ Sequences break TextField character count

### ISSUE THREAD

**Issue by kidcosmic** [flutter/flutter#20286]
ZWJ sequences should treat modified glyphs as a single "character" in textfields.

**Reproduce:**

```
// render
TextField(maxLength: 1)
```
Input 👍🏿

**Expected:**
See modified glyph

**Results:**
Textfield will show the unmodified base for a moment then that will disappear.

**Fix:**

1. ZWJ's don't double a modified glyphs count

or

2. Feature Request: Add an onInput block to TextField. OnInput receives the new input string and returns an updated state for the TextField including the TextEditingController

**Comment by zoechi** [comment]
I think this is a dup of #9652
Please add a comment if you disagree.
