### ISSUE TITLE
17 long path

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#20298]
[ Error 0x80010135 sceenshots, 17 EXPECT files path too long](https://groups.google.com/forum/#!topic/flutter-dev/MXLNDLeUHo4)

**Comment by mit-mit** [comment]
Attaching the screenshots from above conversation
[flutter_path.pdf](https://github.com/flutter/flutter/files/2266573/flutter_path.pdf)

**Comment by zoechi** [comment]
@mit-mit I don't understand what this issue is about. Could you please apply labels that apply?

**Comment by mit-mit** [comment]
Based on my limited understanding of French, and experience with using Windows, I think the issue here is that some file path to some of our `.expect` files exceeded 260 characters, potentially because the French localized Windows OS has some base folders that have longer names in French than in English?

**Comment by zoechi** [comment]
Where are `.expect` files from? What are they related to?

**Comment by mit-mit** [comment]
It looks like they are coming from the Dart `front_end` package:

```
find . -name downwards_inference*.transformed.expect
...
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_async_await.dart.strong.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_on_instance_creations_infer_downwards.dart.strong.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_on_constructor_arguments_infer_downwards.dart.direct.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_on_function_arguments_infer_downwards.dart.strong.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_annotations_typedef.dart.strong.transformed.expect
```

**Comment by benedicte69** [comment]
That does not prevent to install flutter but during the installation, it is necessary to remain in front of your computer to authorize these files and this 17 times :)
   Le jeudi 23 août 2018 à 18:59:17 UTC+2, Michael Thomsen <notifications@github.com> a écrit :  
 
 
It looks like they are coming from the Dart front_end package:
find . -name downwards_inference*.transformed.expect
...
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_async_await.dart.strong.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_on_instance_creations_infer_downwards.dart.strong.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_on_constructor_arguments_infer_downwards.dart.direct.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_on_function_arguments_infer_downwards.dart.strong.transformed.expect
./.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/testcases/inference/downwards_inference_annotations_typedef.dart.strong.transformed.expect

**Comment by M123-dev** [comment]
I have just experienced a similar problem while running `pub get`. Just posting here if anyone else encounters the same problem.

```
error: unable to create file packages/webview_flutter/.../.../...java: Filename too long
```

Git on Windows uses an older version of the Windows API and there's a limit of 260 characters for filenames

Running `git config --system core.longpaths true` resolves the problem

**Comment by jonahwilliams** [comment]
I don't think we plan to do anything about this. developers on newer versions of windows should enable long paths.
