### ISSUE TITLE
DefaultTabController not working with dynamic data

### ISSUE THREAD

**Issue by techyrajeev** [flutter/flutter#20292]
## Steps to Reproduce

1. Add `DefaultTabController` widget 
2. add `length` to a dynamic property lets say `tabCount` from view model (_vm)
3. Load data asynchronously and based on that data generate `TabBarView` and `TabNames`
4. Click on tabs ( Error is thrown) also default active tab is set to index 1
5. If `tabCount` is set to a fixed value and `tabNames` are static values lets say `4` or `3` and `["A", "B"]` it works

## Code

  ```dart
@override
  Widget build(BuildContext context) {
    return new StoreConnector<AppState, _ViewModel>(
      onInit: (Store<AppState> store) => store.dispatch(initSportData(context)),
      converter: _ViewModel.fromStore,
      builder: (BuildContext context, _ViewModel vm) {
        return new DefaultTabController(
            length: vm.tabCount,  // <-------------------------------------------Here
            child: Scaffold(
              appBar: PreferredSize(
                  preferredSize: Size.fromHeight(96.0),
                  child: getAppBar(context, vm.tabNames)), // <--------------------------------------Here
              body: new Container(
                  decoration: new BoxDecoration(
                      image: new DecorationImage(
                    alignment: Alignment.topLeft,
                    image: new AssetImage('images/main-bg.png'),
                    fit: BoxFit.cover,
                  )),
                  child: vm.isLoading
                      ? new Center(
                          child: new CircularProgressIndicator(),
                        )
                      : TabBarView(
                          children: getTabBarView(vm.tabDetails), //<------------------------------Here
                        )),
            ));
      },
    );
  }

```
## Logs

```
 ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7806): The following assertion was thrown while handling a gesture:
I/flutter ( 7806): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 110 pos 12: 'value >= 0
I/flutter ( 7806): && (value < length || length == 0)': is not true.
I/flutter ( 7806): 
I/flutter ( 7806): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7806): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7806): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7806):   https://github.com/flutter/flutter/issues/new
I/flutter ( 7806): 
I/flutter ( 7806): When the exception was thrown, this was the stack:
I/flutter ( 7806): #2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart)
I/flutter ( 7806): #3      TabController.animateTo (package:flutter/src/material/tab_controller.dart:162:5)
I/flutter ( 7806): #4      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:864:17)
I/flutter ( 7806): #5      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:939:21)
I/flutter ( 7806): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
I/flutter ( 7806): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
I/flutter ( 7806): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter ( 7806): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter ( 7806): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter ( 7806): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter ( 7806): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter ( 7806): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter ( 7806): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter ( 7806): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter ( 7806): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter ( 7806): #17     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter ( 7806): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
I/flutter ( 7806): (elided 2 frames from class _AssertionError)
I/flutter ( 7806): 
I/flutter ( 7806): Handler: onTap
I/flutter ( 7806): Recognizer:
I/flutter ( 7806):   TapGestureRec
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.5.1 at /private/var/www/flutter
    • Framework revision c7ea3ca377 (2 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/rajeev/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/rajeev/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Brew not installed; use this to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
Can you please provide a complete but minimal reproduction?
You can use `Future.delayed(...)` to simulate async response

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by huyffs** [comment]
Still an issue in `dev` channel
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dynamic Tab Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  List<Tab> _tabs = [];
  List<Widget> _views = [];

  @override
  void initState() {
    super.initState();
    this._addTab();
  }

  void _addTab() {
    setState(() {
      _tabs.add(Tab(
        icon: Icon(Icons.star),
        text: "Tab ${_tabs.length}",
      ));
      _views.add(Center(child: Text("Tab ${_tabs.length}'s view")));
    });
  }

  void _removeTab() {
    setState(() {
      _tabs.removeLast();
      _views.removeLast();
    });
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: _tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text("Dynamic tabs"),
          actions: <Widget>[
            IconButton(icon: Icon(Icons.add), onPressed: this._addTab),
            IconButton(icon: Icon(Icons.remove), onPressed: this._removeTab),
          ],
          bottom: TabBar(
            isScrollable: true,
            tabs: _tabs,
          ),
        ),
        body: TabBarView(
          children: _views,
        ),
      ),
    );
  }
}
```
I/flutter (12849): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12849): The following RangeError was thrown building TabBar(dirty, state: _TabBarState#e5c78):
I/flutter (12849): RangeError (index): Invalid value: Only valid value is 0: 1
I/flutter (12849):
I/flutter (12849): When the exception was thrown, this was the stack:
I/flutter (12849): #0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
I/flutter (12849): #1      _TabBarState.build (package:flutter/src/material/tabs.dart:916:26)
I/flutter (12849): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (12849): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (12849): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #7      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (12849): #8      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (12849): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #18     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (12849): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #34     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (12849): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #62     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #66     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #68     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4521:32)
I/flutter (12849): #69     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4911:17)
I/flutter (12849): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #77     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #81     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #87     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (12849): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
I/flutter (12849): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #97     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #101    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #105    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #109    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #113    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12849): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
I/flutter (12849): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
I/flutter (12849): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (12849): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (12849): #121    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (12849): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:673:20)
I/flutter (12849): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (12849): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (12849): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (12849): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (12849): #127    _invoke (dart:ui/hooks.dart:139:13)
I/flutter (12849): #128    _drawFrame (dart:ui/hooks.dart:128:3)
I/flutter (12849): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12849): Another exception was thrown: A RenderFlex overflowed by 99870 pixels on the bottom.
```

**Comment by zoechi** [comment]
@huyffs sorry that it took me so long.
Not sure if you were about to fix it already.

I think the issue is caused by reusing cached widgets. I don't fully understand it yet, but I have seen this causing such issues in various scenarios.

This worked for me:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dynamic Tab Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  List<Map<String, dynamic>> _tabs = [];
  List<String> _views = [];

  @override
  void initState() {
    super.initState();
    this._addTab();
  }

  void _addTab() {
    setState(() {
      _tabs.add({
        'icon': Icons.star,
        'text': "Tab ${_tabs.length}",
      });
//      _views.add(Center(child: Text("Tab ${_tabs.length}'s view")));
      _views.add("Tab ${_tabs.length}'s view");
    });
  }

  void _removeTab() {
    setState(() {
      _tabs.removeLast();
      _views.removeLast();
    });
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: _tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text("Dynamic tabs"),
          actions: <Widget>[
            IconButton(icon: Icon(Icons.add), onPressed: this._addTab),
            IconButton(icon: Icon(Icons.remove), onPressed: this._removeTab),
          ],
          bottom: TabBar(
            isScrollable: true,
            tabs: _tabs
                .map((tab) => Tab(
                      icon: Icon(tab['icon']),
                      text: "Tab ${_tabs.length}",
                    ))
                .toList(),
          ),
        ),
        body: TabBarView(
          children: _views
              .map((view) => Center(child: Text("Tab ${_tabs.length}'s view")))
              .toList(),
        ),
      ),
    );
  }
}
```

**Comment by huyffs** [comment]
That works better but the tab bar still crashes when tapped on and doesn't respond to screen changes from swiping.

To make it work, I needed to create and use a new customer `TabController` each time the number of tab changes:
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Dynamic Tab Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with TickerProviderStateMixin {
  TabController _tc;

  List<Map<String, dynamic>> _tabs = [];
  List<String> _views = [];

  @override
  void initState() {
    super.initState();
    this._addTab();
  }

  TabController _makeNewTabController() => TabController(
        vsync: this,
        length: _tabs.length,
        initialIndex: _tabs.length - 1,
      );

  void _addTab() {
    setState(() {
      _tabs.add({
        'icon': Icons.star,
        'text': "Tab ${_tabs.length}",
      });
      _views.add("Tab ${_tabs.length}'s view");
      _tc = _makeNewTabController();
    });
  }

  void _removeTab() {
    setState(() {
      _tabs.removeLast();
      _views.removeLast();
      _tc = _makeNewTabController();
    });
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: _tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text("Dynamic tabs"),
          actions: <Widget>[
            IconButton(icon: Icon(Icons.add), onPressed: this._addTab),
            IconButton(icon: Icon(Icons.remove), onPressed: this._removeTab),
          ],
          bottom: TabBar(
            controller: _tc,
            isScrollable: true,
            tabs: _tabs
                .map((tab) => Tab(
                      icon: Icon(tab['icon']),
                      text: "Tab ${_tabs.length}",
                    ))
                .toList(),
          ),
        ),
        body: TabBarView(
          controller: _tc,
          children: _views
              .map((view) => Center(child: Text("Tab ${_tabs.length}'s view")))
              .toList(),
        ),
      ),
    );
  }
}
```

**Comment by huyffs** [comment]
That is still not perfect - the `initialIndex` value doesn't seem to be honoured.

To fix that I had to get rid of the `TabView` on every build:
```dart
      ...
      body: TabBarView(
        key: Key(Random().nextDouble().toString()),
        controller: _tc,
        ...
      ),
      ...
```

**Comment by jwehrle** [comment]
This works but for the sake of clarity alone I think this example should be using the text defined in _tabs and _views. Otherwise each tab has the same title and the same view text.

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Dynamic tabs"),
        actions: <Widget>[
          IconButton(icon: Icon(Icons.add), onPressed: this._addTab),
          IconButton(icon: Icon(Icons.remove), onPressed: this._removeTab),
        ],
        bottom: TabBar(
          controller: _tc,
          isScrollable: true,
          tabs: _tabs
              .map((tab) => Tab(
                    icon: Icon(tab['icon']),
                    text: tab['text'], // use the tab parameter here
                  ))
              .toList(),
        ),
      ),
      body: TabBarView(
        key: Key(Random().nextDouble().toString()),
        controller: _tc,
        children: _views.map((view) => Center(child: Text(view))).toList(), // use the view parameter here
      ),
    );
  }
```

**Comment by jwehrle** [comment]
Also, in my test the tab title and the tab view text were out of sync by one and I'm not exactly sure why. This change to _addTab() fixed that:

```
void _addTab() {
    setState(() {
      _tabs.add({
        'icon': Icons.star,
        'text': "Tab ${_tabs.length + 1}", // + 1 here.
      });
      _views.add("Tab ${_tabs.length}'s view");
      _tc = _makeNewTabController();
    });
  }
```

**Comment by hermantai** [comment]
I am having the same issue. I believe the problem is that DefaultTabController's length can only be set once, due to the tabcontroller being created at initState in _DefaultTabControllerState ([link](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tab_controller.dart#L294)). I am not sure what a workaround should be.

**Comment by lucien-theron** [comment]
Is this issue still being worked on?

**Comment by w4mxl** [comment]
Looking forward to fix this...

**Comment by SayidHosseini** [comment]
The problem still persists.
I do not think that the length property of DefaultTabController cannot be dynamically changed. I tested and starting from length property set to 1 worked. The problem presents itself when the length start from the value 0 and changes to higher numbers.

**Comment by matthew5025** [comment]
Are you on the master branch? Think this fix hasn't made it to the stable
branch yet

**Comment by SayidHosseini** [comment]
This is what I'm testing on:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] VS Code, 64-bit edition (version 1.35.1)
[√] Connected device (1 available)
• No issues found!
```

This does not seem to be a problem without using the `DefaultTabController` and using `TabController` instead!
[Here](https://gist.github.com/SayidHosseini/f7c7647fb2bcfd1115ce05e2b60f834b) is a sample code that works with `TabController`; I could provide a similar sample with `DefaultTabController` that does not work, if you think it is necessary.

**Comment by matthew5025** [comment]
@SayidHosseini Youe sample code runs sucessfully for me. I'm currently on the master channel, please switch as the fix has not made it to the stable channel yet. 

For reference, I've tested the sample code on
`Channel master, v1.8.1-pre.22`

**Comment by SayidHosseini** [comment]
@matthew5025  as I have mentioned, this sample code works; since it is using `TabController`. 
I could provide one with `DefaultTabController `that would not work.

**Comment by SayidHosseini** [comment]
@matthew5025, as I mentioned in the previous comment, that sample uses the `TabController` and works fine (even on stable channel) but the `DefaultTabController` is the one with a problem.

So as you requested, I changed to `Channel master, v1.8.2-pre.56`. Also, I developed a [sample code](https://gist.github.com/SayidHosseini/fb57979d442df109bd78d110a4574c3d) with `DefaultTabController` that throws an exception.

Here is what it complain about:
```
I/flutter (29448): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (29448): The following assertion was thrown building MyApp(dirty, state: _MyAppState#1f685):
I/flutter (29448): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 316 pos 15: 'initialIndex
I/flutter (29448): >= 0 && initialIndex < length': is not true.
```

**Comment by matthew5025** [comment]
@salihgueler My apologies, I've misread your comments

**Comment by salihgueler** [comment]
I guess this was not addressed to me :) @matthew5025

**Comment by matthew5025** [comment]
Yeah it was not! Sorry to both @salihgueler and @SayidHosseini !

**Comment by matthew5025** [comment]
@SayidHosseini I've created a new issue #37139 in order to link the fix to that issue. The PR is at #37140

I've tested it on your example and it works. I'll be grateful if you could test it on your application that was using the DefualtTabController and see if it fixes your problem!

**Comment by SayidHosseini** [comment]
@matthew5025 Thank you.
Tested with your change and it works perfectly fine.

**Comment by fluttercorner** [comment]
[How to Create TabBar in Flutter Complete Guide To Make TabBar](https://fluttercorner.com/how-to-create-tabbar-in-flutter-complete-guide-to-make-tabbar/)
