### ISSUE TITLE
Text field cursor doesn't go down after a new line creation - IOS

### ISSUE THREAD

**Issue by csnguyen-gmail** [flutter/flutter#20293]
Below is my Flutter version

> [✓] Flutter (Channel unknown, v0.5.8-pre.163, on Mac OS X 10.13.6 17G65, locale en-VN)
>     • Flutter version 0.5.8-pre.163 at /Users/csnguyen/Documents/Flutter/flutter
>     • Framework revision 29410abbe7 (10 days ago), 2018-07-27 22:10:39 -0700
>     • Engine revision 72a38a6b13
>     • Dart version 2.0.0-dev.69.3.flutter-937ee2e8ca

## Steps to Reproduce
I got exactly the same phenomena with [#15572](https://github.com/flutter/flutter/issues/15572) but this time on IOS device. I can also fix by [work around](https://github.com/flutter/flutter/issues/15572#issuecomment-396151633) but it's only work well with maxLines is 1 and null.
I also check on newest version of dev, master, beta branch but phenomena is still occur.
So please support to solve this issue.
Thanks

**Comment by jonahwilliams** [comment]
Found the issue - there is a difference in how we handle the text affinity in android and ios, working on a quick fix!

**Comment by vu111293** [comment]
Dear sir,
I can reproduce this bug on IOS using last commit on master:
Commit: 21f22ed3bae713db9bdd1260dfc5f16c5fae888c [21f22ed]
Parents: 6146c0f18e
Author: Ian Hickson <ian@hixie.ch>
Date: 09 August 2018 06:23:36
Committer: GitHub

Bellow is my dart information:
Flutter 0.5.9-pre.10 • channel master • https://github.com/flutter/flutter.git Framework • revision 21f22ed3ba (3 days ago) • 2018-08-09 18:23:36 -0700 Engine • revision e54bc4ea18 Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c

Please check again. Thank you!
