### ISSUE TITLE
iOS: Stocks app crashes when changing the theme

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#203]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [collinjackson](https://github.com/collinjackson)**
_Thursday Oct 15, 2015 at 23:13 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1639_

----

This appears to be an issue with setTaskDescription not being implemented on iOS and asserting

**Comment by chinmaygarde** [comment]
The demo no longer calls setTaskDescription. I was able to change the theme.
