### ISSUE TITLE
"Will Apple reject my app" could be stronger

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#20309]
https://flutter.io/faq/#will-apple-reject-my-flutter-app

"We can’t speak for Apple, but Apple’s policies have changed over the years, and they have allowed apps built with systems like Flutter. We are aware of apps built with Flutter that have been reviewed and released via the App Store.

Of course, Apple is ultimately in charge of their ecosystem, but our goal is to continue to do everything we can to ensure Flutter apps can be deployed into Apple’s App Store."

We could offer stronger examples, such as the fact that Flutter-built apps have even been featured on the Apple App store (e.g. Hamilton).  We could also cite that technologies like Flutter (e.g. Unity) are used to produce *many* apps on the app store.

Thoughts @mjohnsullivan @mit-mit?

**Comment by mit-mit** [comment]
Yes, would be great to rephrase this!

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1937](https://github.com/flutter/website/issues/1937) via [**ZenHub**](https://www.zenhub.com/)
