### ISSUE TITLE
Atom knows where the Flutter SDK is, can't find the Flutter SDK

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2031]
I ran into this problem yesterday on Linux. Today I'm on a Mac. As far as I can tell, I've configured the Flutter SDK location correctly and yet I can't create a Flutter project because the Flutter SDK location isn't configured correctly:

<img width="1263" alt="screen shot 2016-02-19 at 9 52 46 am" src="https://cloud.githubusercontent.com/assets/1377460/13184127/f721cef2-d6ee-11e5-9e4a-4d92114be555.png">

Restarting Atom caused the XCode command line tools install dialog to run. As far as I know, I'd already passed this hurdle, per the git install step.

<img width="682" alt="screen shot 2016-02-19 at 9 58 30 am" src="https://cloud.githubusercontent.com/assets/1377460/13184753/90e14060-d6f2-11e5-8563-4af0c6fcd97f.png">

After restarting Atom again, all appears to be well. Perhaps the root problem was missing xcrun?

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
