### ISSUE TITLE
camera failed when loading preview

### ISSUE THREAD

**Issue by sam0610** [flutter/flutter#20311]
```
Access denied finding property "persist.camera.cfa.packagelist"
W/info.nixon3.nfc( 3183): type=1400 audit(0.0:119384): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=18505 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
```

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by spagni** [comment]
I am having this exact issue right now. I can not save any video

**Comment by kangwang1988** [comment]
@spagni 
`flutter doctor -v` 
and a minimal demo project please.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by TheAlphamerc** [comment]
I am also facing the same issue.I am following  [flutter camera docs](https://flutter.dev/docs/cookbook/plugins/picture-using-camera) to use camera and still getting below debug output on initializing camera:-

`W/mple.qaegis_app(20087): type=1400 audit(0.0:64949): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=17696 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (20087): Access denied finding property "vendor.camera.aux.packagelist"
I/Timeline(20087): Timeline: Activity_launch_request time:139730651 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }`

***Device :-*** Redmi note 7s

**Comment by felipesses** [comment]
I am also facing this issue

W/br.ifba.SpO2(15517): type=1400 audit(0.0:304270): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=24702 scontext=u:r:untrusted_app:s0:c252,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0

E/libc    (15517): Access denied finding property "persist.vendor.camera.privapp.list"
W/BpBinder(15517): Slow Binder: BpBinder transact took 321 ms, interface=android.hardware.camera2.ICameraDeviceUser, code=6 oneway=false

E/libc    (15517): Access denied finding property "persist.vendor.camera.privapp.list"

W/br.ifba.SpO2(15517): type=1400 audit(0.0:304277): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=24702 scontext=u:r:untrusted_app:s0:c252,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0

Device -> Redmi note 9s

**Comment by AndreBerzun** [comment]
Here are my details as well: 

**Logs**
```
[   +5 ms] W/nto.app_name(22109): type=1400 audit(0.0:95112): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=18772 scontext=u:r:untrusted_app:s0:c120,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
[  +14 ms] E/libc    (22109): Access denied finding property "persist.vendor.camera.privapp.list"
[   +2 ms] W/Binder:22109_1(22109): type=1400 audit(0.0:95113): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=18772 scontext=u:r:untrusted_app:s0:c120,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
[        ] E/libc    (22109): Access denied finding property "vendor.camera.aux.packagelist"
[        ] W/Binder:22109_1(22109): type=1400 audit(0.0:95114): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=18772 scontext=u:r:untrusted_app:s0:c120,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
```

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/andre/development/flutter
    • Framework revision 1aafb3a8b9 (4 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

⢿Error 1 retrieving device properties for ro.product.cpu.abi:
error: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
See [http://developer.android.com/tools/device.html] for more information

                                                                                                                                                                                                      ⡿Error 1 retrieving device properties for ro.product.cpu.abi:
error: insufficient permissions for device: user in plugdev group; are your udev rules wrong?
See [http://developer.android.com/tools/device.html] for more information

                                                                                                                                                                                                      ⣻
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/andre/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (3 available)
    • TA 1012 (mobile)          • NB1GAS3770900742 • android-arm64 • Android 9 (API 28)
    • PL2GAR9850702639 (mobile) • PL2GAR9850702639 • android-arm   • Android null (API null)
    • PNXGAM88C1100134 (mobile) • PNXGAM88C1100134 • android-arm   • Android null (API null)

! Doctor found issues in 1 category.
```

I'd be grateful if someone could check this out ... I have to admit, using this plugin was the first time that Flutter actually let me down.
