### ISSUE TITLE
How to listenter the lifecycle of a page(Not app lifecycle)？

### ISSUE THREAD

**Issue by lucifdch** [flutter/flutter#20325]
I need to perform the operation in the page state（like Andoird onStart onPause onActivityResult）。
But there is no way for Flutter to implement it, or the code will be very different.

I need to load the data when the page is displayed on the screen. In order to implement this function, I have to do some work.
1. `WidgetsBinding.addObserver()` adds a listener method.
2. I need to add `then()` to all `Navigator.of(context).push**()` in the current interface.
3. In order to avoid the impact of `WidgetsBinding` on other interfaces, I need to execute `WidgetsBinding.instance.removeObserver()` before `push**()`.
4. Then add `WidgetsBinding.instance.addObserver()` to the `life()` function in the `then()` method.

The purpose of all this is simply to implement a simple loading function when the page is displayed.

example：
```dart
class HomePage extends StatefulWidget {

  HomePage({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return _HomePageState();
  }
}

typedef void HandleResult(resp);

class _HomePageState extends State<HomePage> with WidgetsBindingObserver {
  
  void jumpOfName(String pageName, HandleResult handleResup){
    WidgetsBinding.instance.removeObserver(this);
    saveData();

    Navigator.of(context).pushNamed(pageName).then((resp) {
      handleResup(resp);
      WidgetsBinding.instance.addObserver(this);
      loadData();
    });
  }

  void jumpOfWidget(Widget page, HandleResult handleResup){
    WidgetsBinding.instance.removeObserver(this);
    saveData();

    Navigator.of(context).push(MaterialPageRoute(
      builder: (context) => page
    )).then((resp) {
      handleResup(resp);
      WidgetsBinding.instance.addObserver(this);
      loadData();
    });
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    _controller.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if(state == AppLifecycleState.resumed) {
      loadData();
    } else if(state == AppLifecycleState.paused) {
      saveData();
    }
  } 
}
```

**Comment by shmmly** [comment]
hi,partner  why don't you load data in initState  lifecycle .   when you  bulid Weight ,you can check the data  like this.


![image](https://user-images.githubusercontent.com/18435678/43884548-fc39bac8-9be8-11e8-9543-36a9e895bd3f.png)

**Comment by goderbauer** [comment]
As suggested in the comment above, why not perform the operations in the initState [1] of the widget you're pushing on screen? Is there anything else you need?

[1] https://master-docs.flutter.io/flutter/widgets/State/initState.html

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
