### ISSUE TITLE
Jump page before closing Dialog

### ISSUE THREAD

**Issue by lucifdch** [flutter/flutter#20329]
Jumping the page before closing Dialog causes the page to close unexpectedly, but Dialog cannot be closed

```dart
Future<T> showLoading<T>(BuildContext context, Future<T> call) async {
  return await showDialog(
    context: context,
    barrierDismissible: false,
    builder: (ctx) {
      call.then((resp){
        Navigator.pop(ctx, resp);
      });
      return Center(
        child: Container(
          width: 56.0,
          padding: EdgeInsets.all(4.0),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8.0),
            color: Colors.black54
          ),
          child: Image.asset(
            "assets/imgs/loading.gif",
          )
        )
      );
    }
  );
}

Future doing() async {
    final resp = await  doWork();
    if(resp.isOk) {
        Navigator.of(context).pushNamed("/home");
    } else {
        Navigator.of(context).pushNamed("/register");
    }
}

void _loading() {
    showLoading(context, doing);
}
```

**Comment by zoechi** [comment]
You are aware that `Navigator.pop(ctx, resp)` is called sometimes *after* `builder: (ctx) { ... }` completed. This might cause `Navigator.pop(ctx, resp)` to pop a different route than you expect.

I don't see an easy way to change that because `builder: ...` expects a widget sync.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
