### ISSUE TITLE
abount example sdk version required

### ISSUE THREAD

**Issue by MagicalWater** [flutter/flutter#20331]
about example "hello_world" project, 
there were a error occ when run the project
```

The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because hello_world depends on path >=1.6.1 which requires SDK version >=2.0.0-dev.62.0 <3.0.0, version solving failed.
```

but i don't know how to setting project's version required

**Comment by zoechi** [comment]
Either update Flutter or use a version of `path` that is compatible with your Flutter version.
I don't know which version works with your Flutter version.
I'd check the available versions from https://pub.dartlang.org/packages/path#-changelog-tab- and try the versions one by one (ignoring patch level).


```yml
path: ^1.6.0
```
```yml
path: ^1.5.0
```
```yml
path: ^1.4.0
```
...
