### ISSUE TITLE
better directions on how to launch the simulator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2033]
We need better directions on how to launch the simulator. The Simulator path of ‘Applications/Xcode/Contents/Developer/Applications’ directory is not locatable in Finder. Apple’s own Documentation says:
* Launch Xcode
* Xcode Menu -> Open Developer Tools -> Simulator

Note: `open -a Simulator` also works.  Or typing Simulator in spotlight

**Comment by Hixie** [comment]
I thought I fixed this. maybe I didn't send the patch yet.

**Comment by abarth** [comment]
I've been working on a new draft of the getting started page:

https://docs.google.com/a/chromium.org/document/d/1wL_7BvpExxyvLqtf5am3_iMQThWBZ0Ak1uPVFiI3KN8/edit?usp=sharing

**Comment by qchong** [comment]
Fixed in flutter/website#178, based on doc shared by abarth@.

**Comment by qchong** [comment]
Marking as closed.
