### ISSUE TITLE
Issue from website page JSON and serialization

### ISSUE THREAD

**Issue by readytopark** [flutter/flutter#20343]
From URL: https://flutter.io/json/

Applying this `pubspec` generated an error

https://raw.githubusercontent.com/dart-lang/json_serializable/master/example/pubspec.yaml

```
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because rent_tenant depends on json_serializable >=1.0.0 which requires SDK version >=2.0.0-dev.65 <3.0.0, version solving failed.
pub get failed (1)
```

I'm using flutter beta v0.5.1. This may be solved if I switch to different branch by using `flutter channel master` but the doc says it's strongly recommended to use `beta` instead of `master`.

**Comment by NikoYuwono** [comment]
Like the error message said, you'll need to use Dart SDK version 2.0.0-dev.65 above but you have 2.0.0-dev.65 right now. 
You can use the older vesion of json_serializable (e.g. 0.5.6) or switch to dev channel and run flutter upgrade.

**Comment by zoechi** [comment]
Thanks @NikoYuwono
