### ISSUE TITLE
[question] how stable is Master channel?

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20345]
Hello, just wondering if Flutter team considers Master channel to be production-ready.

Cheers,
Luke

**Comment by tudor07** [comment]
The beta channel is the most stable.
More about this here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by zoechi** [comment]
@tudor07 thanks!

**Comment by lukepighetti** [comment]
Beta seems to be getting a little stale based on that guide. Do we have any indication when it will be updated?
