### ISSUE TITLE
How to get rid of the white screen that flashes between ios SplashScreen and the app's first screen

### ISSUE THREAD

**Issue by manujbahl** [flutter/flutter#20357]
I have an iOS app. 
I have set a launch screen image in xCode.
I set the same image in a container in the main scaffold. 
But I see a brief flash of white (or whatever color the scaffold background is) between the launch image and scaffold image. How can I get rid of that?

**Comment by zoechi** [comment]
Duplicate of #20827

This one has more upvotes but #20827 has more discussion.
