### ISSUE TITLE
[Google Dynamic Links for Firebase] Keep deeplink state when return to forceground

### ISSUE THREAD

**Issue by vu111293** [flutter/flutter#20369]
I implement [Google Dynamic Links for Firebase] for deeplink and catch scene:

* My flutter app (android) has home page and detail page.
1. Click web link to open app > open detail page (deep link contain page id)
2. Back to home page in app and press home to make app as background.
3. Reopen app.
-> Result: app opened and auto direct to detail page (same click deep link case)
Expected: app opened only, not auto direct to detail page. (deep link state should clear)

Please check it. Tks!

**Comment by zoechi** [comment]
Is this like #20944?

**Comment by kroikie** [comment]
@vu111293

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/720. Any further collaboration will be done there.
