### ISSUE TITLE
Flutter Share Plugin Issue

### ISSUE THREAD

**Issue by mrmetech** [flutter/flutter#20363]
Here is the error am getting

```
08-08 18:28:26.481 1856-1984/com.nodemarketcap.nodemarketcap E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      Share.share (package:share/share.dart:44:20)
    #2      _SettingsPageState.build.<anonymous closure> (package:nodemarketcap/settings.dart:79:36)
    #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
    #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
    #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
    #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
    #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
    #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
    #14     _invoke1 (dart:ui/hooks.dart:134:13)
    #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

Here is the code were am getting the error also this error happens when i click it in the app demo 

```dart
                new ListTile(
                  title: const Text('Share App', style: const TextStyle(fontSize: 18.0)),
                  onTap: () {Share.share('check out my website https://example.com');},

                ),
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by fusion44** [comment]
I had the same problem. It worked after reinstalling the app to the phone. Hot reload messed something up.


[✓] Flutter (Channel dev, v0.7.5, on Linux, locale en_US.UTF-8)
    • Flutter version 0.7.5 at /home/stefan/dev/mobile/flutter
    • Framework revision eab5cd9853 (3 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /home/stefan/dev/mobile/andsdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Pixel 2 XL • 711KPPB0618832 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by FlutterAddict** [comment]
Reinstalling the app helps.

**Comment by FlutterAddict** [comment]
it's a problem with hot reload and not the library so I think you can close.

**Comment by VladyslavBondarenko** [comment]
Checked, seems not to be an issue. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code, logs and the output of `flutter doctor -v` please.

**Comment by coolrukshan** [comment]
E/flutter ( 5649): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)
E/flutter ( 5649): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 5649): <asynchronous suspension>
E/flutter ( 5649): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 5649): #2      Share.share (package:share/share.dart:53:20)
E/flutter ( 5649): #3      Today.build.<anonymous closure> (package:DailyQuote/today/today_page.dart:98:35)
E/flutter ( 5649): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 5649): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 5649): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 5649): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 5649): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 5649): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 5649): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 5649): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 5649): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 5649): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 5649): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 5649): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 5649): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter ( 5649): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 5649): #18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 5649): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 5649): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 5649): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 5649): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 5649): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5649): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 5649): #25     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 5649): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 5649): 


[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-LK)
    • Flutter version 1.22.6 at /Users/admin/Desktop/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • SM A507FN (mobile)                 • R58MB5E9V8P   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!
