### ISSUE TITLE
Remove specific class references when tree shaking happens

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#20367]
I always used proguard on android to remove any debug method when compiling for release. This help so much since I didn't have to remove them myself and there were still there in the debug version. For example for logs I would use:

```
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}
```

Is there a way to achieve this with Dart?

**Comment by zoechi** [comment]
Dart does tree-shaking, no need to do anything manually.

**Comment by zoechi** [comment]
You can use `assert()` to make code used only in debug mode.
https://stackoverflow.com/questions/24208213/how-to-exclude-debug-code/24208259#24208259
There is currently no better way, but there is an (one or more) issue in dart-lang/sdk to improve that.

**Comment by long1eu** [comment]
looks good enough for now, can you share a link for the dart issue?

**Comment by zoechi** [comment]
I would have to search myself but I'm sure I saw some discussions. Also discussed in related to requests for "macros" support.

**Comment by zoechi** [comment]
https://github.com/dart-lang/sdk/issues/27192

**Comment by zoechi** [comment]
Can we close this issue? 
It's rather a Dart than Flutter issue.

**Comment by long1eu** [comment]
sure
