### ISSUE TITLE
Using theme's "disabled" color instead of explicit Colors.gray

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2037]
Instead of using Colors.gray for the button, probably should use the theme’s disabled color.

(If this is trivial, let's do it! Seems like a good idea to set precedence. Otherwise, if it's difficult, can close.)

**Comment by Hixie** [comment]
Yeah, we should probably derive all the colours from the Theme in general. We should probably audit all the material widgtes at some point to make sure they do that too.

**Comment by jaasaria** [comment]
Any update on this? 

Im Using: 
`Text(
                      Dummy.paragraph,
                      style: Theme.of(context)
                          .textTheme
                          .body1
                          .copyWith(color: Colors.grey),
                    ),`

but i want to use textTheme with disabled color. Hope theirs already an update on this.

**Comment by bambinoua** [comment]
There is `Theme.of(context).disabledColor`!
