### ISSUE TITLE
Firebase_auth googleSign Exception at await googleUser.authentication;

### ISSUE THREAD

**Issue by jeromebonjour** [flutter/flutter#20377]
I get an exception on the second call of final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

Step to reproduce : 
Signin
Diconnect 
then I try to signIn a second time..

```
E/flutter (28678): Exception getting access token
E/flutter (28678): java.util.concurrent.ExecutionException: com.google.android.gms.auth.GoogleAuthException: Unknown
E/flutter (28678):      at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
E/flutter (28678):      at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
E/flutter (28678):      at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
E/flutter (28678):      at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$3.run(GoogleSignInPlugin.java:337)
E/flutter (28678):      at io.flutter.plugins.googlesignin.BackgroundTaskRunner$1.run(BackgroundTaskRunner.java:62)
E/flutter (28678):      at android.os.Handler.handleCallback(Handler.java:739)
E/flutter (28678):      at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter (28678):      at android.os.Looper.loop(Looper.java:145)
E/flutter (28678):      at android.app.ActivityThread.main(ActivityThread.java:6066)
E/flutter (28678):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28678):      at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (28678):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
E/flutter (28678):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
E/flutter (28678): Caused by: com.google.android.gms.auth.GoogleAuthException: Unknown
E/flutter (28678):      at com.google.android.gms.auth.zzh.zze(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.zzd(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.zze(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.getToken(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.getToken(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
E/flutter (28678):      at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$2.call(GoogleSignInPlugin.java:327)
E/flutter (28678):      at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$2.call(GoogleSignInPlugin.java:322)
E/flutter (28678):      at io.flutter.plugins.googlesignin.BackgroundTaskRunner$2.run(BackgroundTaskRunner.java:84)
E/flutter (28678):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/flutter (28678):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/flutter (28678):      at java.lang.Thread.run(Thread.java:818)
E/flutter (28678): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (28678): PlatformException(exception, Unknown, null)
E/flutter (28678): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:544:7)
E/flutter (28678): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter (28678): <asynchronous suspension>
E/flutter (28678): #2      GoogleSignInAccount.authentication (package:google_sign_in/google_sign_in.dart:65:36)
E/flutter (28678): <asynchronous suspension>
```

**Comment by mouadelamrani** [comment]
having the same error! hope we find a solution for that

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by mouadelamrani** [comment]
here is my Flutter Doctor

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
[√] Connected devices (1 available)

• No issues found!
`

i think it's okay!!

**Comment by davidgalarza** [comment]
I'm geting the same error, any idea?

**Comment by mouadelamrani** [comment]
Try to update all the dependencies to the latest version! That works for me!

**Comment by davidgalarza** [comment]
I  update all the dependencies but continue getting the same error.

Here is my pubspec.yml
```
cloud_firestore: ^0.7.4
  firebase_auth: ^0.5.19
  google_sign_in: ^3.0.5
  flutter_swiper: ^1.0.4
  flutter_svg: ^0.5.5+1
  flutter_facebook_login: ^1.1.1
```

Flutter doctor:
`[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.5 17F77, locale es-EC)
    • Flutter version 0.6.0 at /Users/davidgalarza/development/flutter
    • Framework revision 9299c02cf7 (13 days ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/davidgalarza/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • ALE L23 • G7T7N15B14005901 • android-arm64 • Android 5.0.1 (API 21)

• No issues found!`

**Comment by cyanglaz** [comment]
@jeromebonjour could you provide a reduced test case so that I can try to reproduce your issue and debug? 

@savinmathew Do you have the exact same issue?  If you could provide the reduced test case that'd be great too!

**Comment by kroikie** [comment]
@jeromebonjour

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/719. Any further collaboration will be done there.

**Comment by kristhyanmatos** [comment]
olá, passei pelo mesmo problema. Resolvi ajustando a hora do pc.
