### ISSUE TITLE
TextField doesn't open the keyboard when using Stack

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#20373]
![text_field_error](https://user-images.githubusercontent.com/9283414/43892355-5c48103c-9bd4-11e8-95e5-76717a690708.gif)
I'm using a Stack to cover the main page and require the user to enter a password. But the keyboard doesn't open.

Here is a mcv example: https://gist.github.com/long1eu/0cac0f67eeb3115941cb0366929cc946

**Comment by v7lin** [comment]
I have same question

**Comment by zoechi** [comment]
A reduced reproduction 
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => new MyAppState();
}

class MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Stack(children: [
        Navigator(
          initialRoute: '/x',
          onGenerateRoute: (RouteSettings settings) =>
              MaterialPageRoute(builder: (context) => Container()),
        ),
        LockPage()
      ]),
    );
  }
}

class LockPage extends StatelessWidget {
  const LockPage();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            TextField(
              decoration: InputDecoration(
                hintText: 'password',
              ),
              onChanged: (String text) {
                if (text.length >= 5) {}
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

Commenting out the navigator before `LockPage` makes it work.

Tested with
```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by csells** [comment]
@long1eu does the #17098 fix also fix this issue for you?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
