### ISSUE TITLE
 MissingPluginException(No implementation found for method Query#addSnapshotListener on channel plugins.flutter.io/cloud_firestore)

### ISSUE THREAD

**Issue by joshleong** [flutter/flutter#20379]
Hey guys, just trying to get the Firebase Flutter basic application up and running, but hitting this MissingPluginException all over the place. This seems to have occurred after I did a flutter upgrade. I have another computer in which I did not do a flutter upgrade in which I was able to get the flutter-firebase sample to work.

## Logs

5.4.1 - [Firebase/Analytics][I-ACS023007] Firebase Analytics v.50001000 started
5.4.1 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[1.1 AFBC0916-DE63-43C4-9C55-F73294FFC810 2604:5500:c1a7:3000:a0cc:bf72:780a:1941.49758<->2607:f8b0:4005:802::200a.443]
Connected Path: satisfied (Path is satisfied), interface: en0
Duration: 2.608s, DNS @0.003s took 0.010s, TCP @0.017s took 0.008s, TLS took 1.319s
bytes in/out: 3879/4075, packets in/out: 13/18, rtt: 0.007s, retransmitted packets: 8, out-of-order packets: 0
[2.1 F434C211-2D8E-42BB-A96C-0801F0CC12A2 2604:5500:c1a7:3000:a0cc:bf72:780a:1941.49760<->2607:f8b0:4005:804::200e.443]
Connected Path: satisfied (Path is satisfied), interface: en0
Duration: 4.071s, DNS @0.001s took 0.001s, TCP @0.004s took 0.968s, TLS took 2.793s
bytes in/out: 3642/832, packets in/out: 9/9, rtt: 0.795s, retransmitted packets: 0, out-of-order packets: 0
[3.1 9672580A-9B67-4BC2-B059-8DAD984169A2 2604:5500:c1a7:3000:a0cc:bf72:780a:1941.49764<->2607:f8b0:4005:804::200e.443]
Connected Path: satisfied (Path is satisfied), interface: en0
Duration: 0.087s, DNS @0.000s took 0.002s, TCP @0.003s took 0.007s, TLS took 0.046s
bytes in/out: 3589/1371, packets in/out: 9/10, rtt: 0.006s, retransmitted packets: 0, out-of-order packets: 0
Application finished.

## Flutter Upgrade

Flutter 0.5.8-pre.277 • channel master • https://github.com/flutter/flutter.git
Framework • revision e5432a2843 (15 hours ago) • 2018-08-08 16:45:08 -0700
Engine • revision 3777931801
Tools • Dart 2.0.0-dev.69.5.flutter-eab492385c

Running "flutter packages upgrade" in storymachine...        5.7s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.8-pre.277, on Mac OS X 10.13.5 17F77, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

**Comment by joshleong** [comment]
Oh dang, I think I know what I did, because I replaced the AppDelegate code with the Firebase recommended header, I forgot to include

[GeneratedPluginRegistrant registerWithRegistry:self];

**Comment by rtessler** [comment]
I also have MissingPluginExceptions everywhere. What does you AppDelegate.m look like. Are you saying the recommended AppDelegate.m file doesnt work
