### ISSUE TITLE
firebaseMessaging.getToken() fails to return an FCM token, blocks forever in await

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#20378]
Note: This issue could be Android specific, I didn't test it on iOS yet.

The behavior of `firebaseMessaging.getToken()` is mysterious.

I am facing a problem where `firebaseMessaging.getToken()` no longer returns anything, thus `await firebaseMessaging.getToken()` will block forever. I'm quite sure that the code worked before. I tried to figure out why, but no luck so far - the code behaves differently on Java and Flutter side. 

Here's the details.

There's nothing special on the initialization of `firebaseMessaging`, I'm posting it here anyway:

```dart
  final FirebaseMessaging firebaseMessaging = new FirebaseMessaging();
  firebaseMessaging.configure(onMessage: (Map<String, dynamic> message) async {
    print('OnMessage');
    print(message);
  }, onLaunch: (Map<String, dynamic> message) {
    print('onLaunch()');
  }, onResume: (Map<String, dynamic> message) {
    print('onResume()');
  });

   firebaseMessaging.requestNotificationPermissions();
```

The problem is at the `firebaseMessaging.getToken()` call, which never returns a token and blocks forever:

```dart
String fcmToken = await firebaseMessaging.getToken();
```

This had happened before, but was kind of "resolved" by moving the above line later at my app's init stage. Today it happened again, and I decided to try to figure out the cause.

So I opened the Java project, added the following code (copied from the Firebase's example), had it called from Flutter through platform channel, to see if I could see a more verbose error output by retrieving the token manually (bypassing the firebaseMessaging plugin).

```java
...
if (call.method.equals("getFCMToken")) {
  FirebaseInstanceId.getInstance().getInstanceId()
      .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
        @Override
        public void onComplete(@NonNull Task<InstanceIdResult> task) {
          if (!task.isSuccessful()) {
            Log.w(TAG, "getInstanceId failed", task.getException());
            return;
          }

          // Get new Instance ID token
          String token = task.getResult().getToken();

          // Log and toast
          String msg = "Token: "+ token;
          Log.d(TAG, msg);
          Toast.makeText(MainActivity.this, msg, Toast.LENGTH_SHORT).show();
        }
      });
}
...
```

In Flutter, I added this `getFCMToken()` call **BEFORE** `firebaseMessaging.getToken()`. To my surprise, this `getFCMToken()` finishes almost immediately with an FCM token, no error! But the subsequent `firebaseMessaging.getToken()` still blocks forever!

So I set some breakpoints in the java files of the firebase messaging plugin, and found that `broadcastToken()` was not called at all. This is strange.

Not knowing what happened, I uninstalled the app and run it again (still on the Java side). This time `broadcastToken()` is called, which is invoked from [this line](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java#L70)! As a matter of course, `firebaseMessaging.getToken()` returns the FCM token successfully.

Then I switched to the Flutter side and run my project again hoping to see the issue "fixed" and boom! `getFCMToken()` succeeded but `firebaseMessaging.getToken()` still failed!

Then I went back to the Java side, hoping that it would fail again so that I would know why the code under the "configure" method call isn't running. Unfortunately, the code in Java side worked correctly!

Then I went back to the Flutter side, ran `flutter clean`, and rerun the code. Still fails on `firebaseMessaging.getToken()`.

Now I am in a situation where the same code is acting differently when compiled in "Flutter mode" and "Android mode". I feel really frustrated because it seems impossible to track the cause of the issue.

```
[√] Flutter (Channel dev, v0.5.7, on Microsoft Windows [Version 10.0.17134.165], locale zh-HK)
    • Flutter version 0.5.7 at C:\flutter
    • Framework revision 66091f9696 (4 weeks ago), 2018-07-09 12:52:41 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\CY\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio 3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio 3
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Android Studio (version 2.1)
    • Android Studio at C:\Android\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Nexus 5X • 00e1c63e154fae10 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 3 categories.
```

---

*Addendum:* To temporary work around this issue, I modified my platform channel code as follow, and have it called before `firebaseMessaging.getToken()`.

```dart
...
if (call.method.equals("getFCMToken")) {
    FlutterFirebaseInstanceIDService.broadcastToken(MainActivity.this);
}
...
```

This seems to overcome the issue that `broadcastToken` isn't called from the plugin code. But of course this can't be a solution. Also not tested on iOS.

**Comment by KhamelIT** [comment]
+1 Have you solved this? Have you tested it on iOS? I got this problem too.

**Comment by tamcy** [comment]
@KhamelIT I am still using the workaround in by first post. I'm yet to see similar issue on iOS, just not sure if it'll happen one day, though.

Today I can successfully reproduce the "fail to retrieve FCM token" scenario on Java side.

### Normal case

Here's what would normally happen when `FirebaseMessaging.configure()` is called (see `firebase_messaging.dart` on Flutter side, and `FirebaseMessagingPlugin.java` on Java side).

1. Flutter: Sets up method call handler so that incoming message will be handled by `_handleMethod()`.
2. Flutter: Calls Java side's `configure()` through platform channel.
3. Java: Asks `FlutterFirebaseInstanceIDService` to broadcast the FCM token. Sends local broadcast intent with action `FlutterFirebaseInstanceIDService.ACTION_TOKEN`.
4. Java: `onReceive()` method of `FirebaseMessagingPlugin` gets called.
5. Java: FCM token retrieved.
6. Java: Invokes Flutter's `onToken()` method with the just retrieved FCM token.
7. Flutter: `_handleMethod()` called, method name should match `onToken`.
8. Flutter: Replaces old token if the new one is different (or if the old one is null). Also add the FCM token to the `onTokenRefresh` stream.

The logic `FirebaseMessaging.getToken()` is dead simple: if there's already a token, return it. Otherwise, wait for a value in the `onTokenRefresh` stream.

### What happened when FCM token doesn't return

Using the debugging on the Java side, I learnt that step 1-6 has been run. However, the [`onToken()` method is invoked on the Java side](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java#L65) does **NOT** cause the [`_handleMethod()` on the Flutter side](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/lib/firebase_messaging.dart#L101) to be fired. I've added some debug prints to the `configure()` and `_handleMethod()` methods, no printout is found after step 6.

I actually got step 7-8 working for once during my investigation. This happens after I added some logging statements in between the `onMethodCall()` and `onReceive()` statements in Java code - nothing else. Weird, isn't it?

Here's an excerpt of my latest `flutter doctor -v`:
```
[√] Flutter (Channel dev, v0.7.5, on Microsoft Windows [Version 10.0.17134.228], locale zh-HK)
    • Flutter version 0.7.5 at C:\flutter
    • Framework revision eab5cd9853 (7 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\CY\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio 3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.
```

**Comment by tamcy** [comment]
After spending a day on it I finally have a much simpler codebase that can reproduce the issue, albeit not 100% (it worked once or twice with exactly the same codebase. I don't know why).

As I have no confidence anyone else can reproduce the same issue with my code (similar to #17037 also reported by me), I decided to make a companion video to demonstrate this reported issue. So that other people know what I'm talking about, and that I'm not lying.

Here's how the project is organized:

1. My project has two flavors (dev and prod) with two different entry points named `main_dev.dart` and `main.dart`. The `main()` function will do some environment specific setups like different API endpoints. Then both will call the function `entry()` in `entry.dart`. In the video I am using only `main_dev.dart` with all environment specific code removed, and have copied the code in `entry_dev.dart` to `main_dev.dart`.
2. The `FirebaseMessaging` instance resides in the `Application` class as a static field, so that it can be accessed globally by other widgets. This isn't really needed, it was just designed this way and left unchanged.
3. All early init and binding code resides in `entry()`. This includes calling `FirebaseMessaging.configure()`, and also codes like initializing Firebase anayltics and reading of previous stored app config like locale (removed in thie demo). After that `runApp()` is called with `InitScreen` as the homepage.
4. While `entry()` performs some basic init stuff, `InitScreen` will further set the application up to a usable state by fetching data from the remote API server. This can take some time, so `InitScreen` is a stateful widget and will show the progress of initialization to the user. Again all these are removed in the demo. What's kept is the retrieval of FCM token which is also done in this widget. This is mainly because I need to show an error dialog when the FCM token cannot be retrieved, and showing a dialog needs a context, so it can't be done in `entry()`.

I use the official Firebase messaging plugin, but have added several logging statements so that I know what's going on by checking the console.

[The video](https://www.youtube.com/watch?v=HuvqGjQoTZw&feature=youtu.be) can be split into several parts:

### 0:00 -- Successful case

Shows how the app would look like when an FCM token is successfully retrieved.

### 1:10 -- `getToken()` broken

Shows what is done so that the token is no longer returned. If no timeout is set for `Application.firebaseMessaging.getToken()` it will wait forever.

From the log you can see that the FCM token is broadcasted and intercepted successfully in Java. It also calls Flutter code through method channel, but the Flutter code that receives the call is never run.

I am using `await Future.delayed(Duration(seconds: 0));` in the video for simplicity. In my real project I the offending `await` code tries to load the config file from the file system and set the locale.

### 3:00 -- Demonstrate my original work-around

This is what I had mentioned at the end of my original report - explicitly requesting a broadcast of the FCM token in Java code. This is done before I tracked down the cause of the failure.

This seems to indicate that a call from Java to Flutter though method channel is lost somewhere.

### 5:20 -- Demonstrate a second fix

If I move the Firebase configure code and the `await` statement from `entry()` to the init method of the `InitScreen` widget, the code works normally.

That's it for now. I can upload my sample project, although it may not be useful.

**Comment by calebjoseph** [comment]
Do you think this is related to [https://github.com/flutter/flutter/issues/17699]?

**Comment by tamcy** [comment]
@calebjoseph No it's a completely different story. #17699 is about `getToken()` blocks forever if `firebaseMessaging.configure()` **isn't** called in advance. This one is about `getToken()` blocks forever even when `firebaseMessaging.configure()` **is** called before. Even weirder, the same code occasionally worked. This issue is caused by a Java to Flutter method channel call **isn't** executed on Flutter. I've submitted #21610 to better describe the issue, but decided to leave this open so that other people having the same issue won't mistaken it as already being resolved. The Flutter team can close it if they found more appropriate to do so.

**Comment by buntagonalprism** [comment]
I've been able to consistently reproduce `getToken()` blocking forever issue both on physical iOS devices (iPhone 6) and simulator (tested on iPhone 8)

Crucially, it **only works in initial session after app installation**:
1. Immediately after installing the app, `getToken()` successfully returns a token
2. Subsequent calls to `getToken()` continue to return successfully while the original session of the app is still running (including navigating away to other apps and back, as long as it stays in the background)
3. Force close the app from iOS app switcher. Then re-launch the app (without reinstalling)
4. Now all calls to `getToken()` block indefinitely. Killing and relaunching app again consistently sees getToken block indefinitely. 
5. After uninstalling and reinstalling the app, `getToken()` works again, and stops working after killing and reopening the app 

Interestingly, I have no problem running the same codebase on Android devices.

It feels like a timing issue; on first launch after install it would take a bit of time to retrieve the token which gives time for Flutter to set itself up and to run `fcm.configure()`. On subsequent launches the token would be available straight away from the native cache, and `fcm.configure()` might run too late to catch its value being broadcast during app startup. 

**Fix**: Just tested that this issue is indeed resolved by plugin pull request  [PR 789](https://github.com/flutter/plugins/pull/789) by switching to native `getToken` implementation

**Comment by kroikie** [comment]
@tamcy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/718. Any further collaboration will be done there.

**Comment by LukaGiorgadze** [comment]
Still not fixed.
