### ISSUE TITLE
The use of the floating action button isn’t material design standard

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2038]
The use of the floating action button isn’t material design standard. Instead, perhaps use a icon button for the send button, and place the chat messages on cards. Update: Made this part of my hackathon, only 4 or 5 more lines and it looks more like a real app:

**Comment by sethladd** [comment]
@vlidholt did you want to complete this work and update the code?

**Comment by Hixie** [comment]
@collinjackson Can you look at this and decide if it should be closed or fixed?

**Comment by collinjackson** [comment]
This was already fixed
