### ISSUE TITLE
Try to listen listview drag end event

### ISSUE THREAD

**Issue by wesleyxiao** [flutter/flutter#20385]
Hello,
I am build a list with listview.builder

And use control to listener the scroll position, 

I try to get drag release position, when drag down pass some position point, when user release drag , will process function.

When doing the research I haven’t see any information about listview drag start and drag end event maybe there wasn’t have one?

And I try other method was wrap listview inside gestures , tap event is working but all drag vertical  event is not working. :(

**Comment by wesleyxiao** [comment]
just found out a solution using listener.

wrap listview inside listener.
```
return new Scaffold(
        appBar: appBar,
        body: new Listener(
            onPointerUp: (_) {
              tabup = true;
            },
            onPointerDown: (_) {
              tabup = false;
            },
            child:  put listview here
));
  }
```

**Comment by huuang** [comment]
> just found out a solution using listener.
> 
> wrap listview inside listener.
> 
> ```
> return new Scaffold(
>         appBar: appBar,
>         body: new Listener(
>             onPointerUp: (_) {
>               tabup = true;
>             },
>             onPointerDown: (_) {
>               tabup = false;
>             },
>             child:  put listview here
> ));
>   }
> ```

Your solution helps me, thank you

**Comment by egulhan** [comment]
> just found out a solution using listener.
> 
> wrap listview inside listener.
> 
> ```
> return new Scaffold(
>         appBar: appBar,
>         body: new Listener(
>             onPointerUp: (_) {
>               tabup = true;
>             },
>             onPointerDown: (_) {
>               tabup = false;
>             },
>             child:  put listview here
> ));
>   }
> ```

Thanks for the code snippet and no need to wrap Listener with Scaffold.
