### ISSUE TITLE
Rasterizer performance has outliers

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#20398]
Consider this data which shows the rasterizer times of the complex_layout_scroll_perf__timeline_summary 
benchmark as a histogram with 10 microsecond buckets. There's a normal distribution showing that we have some variance in frame times, but there's also a really really long tail which shows that the ~4ms frame sometimes takes up to 3x as long to render (~12ms):

![](https://user-images.githubusercontent.com/551196/43802187-ee2316a0-9a49-11e8-8fe4-f022721d9a31.png)

It is unclear what the source of these bad frames is.

**Comment by liyuqian** [comment]
Just checked the benchmarks dashboard, and the `worst_frame_rasterizer_time_millis` is still 12ms. @Hixie : do you have any later research on this? In some sense, this 12ms worst frame time is exceptionally good compared to our other cases of 200-300ms worst frame time due to shader compilations.

**Comment by liyuqian** [comment]
I just traced the scrolling of complex_layout app:  [dart-timeline-2020-4-6.json.zip](https://github.com/flutter/flutter/files/4441143/dart-timeline-2020-4-6.json.zip)

The slowest frame in the trace is 8ms (which is still much larger than the average 4ms frame). The tracing events show that 3 `PictureLayer`s are populating raster caches in that frame. So the outlier seems to be just raster cache preparations. The average fast frames are just translating those raster caches without actually rasterizing them.

@Hixie : would this be sufficient to close this issue?

**Comment by markusaksli-nc** [comment]
@Hixie Can this be closed or do you have an update here?

**Comment by pedromassangocode** [comment]
[Triage team]

Closing this since it has been more than 21 days without the customer response.
