### ISSUE TITLE
The reload() function on a FirebaseUser doesn't seem to be working.

### ISSUE THREAD

**Issue by JSANL** [flutter/flutter#20390]
Hey, 

when calling the .reload() function on a FirebaseUser nothing seems to happen, as the data of the user I called reload() on doesn't change and the data of a user when calling FirebaseAuth.instance.currentUser() change nontheless, even when not calling reload().

What makes matter more confusing is that on the [Stackoverflow Problem I opened](https://stackoverflow.com/questions/51709733/what-use-case-has-the-reload-function-of-a-firebaseuser-in-flutter) "Frank van Puffelen", a Firebase Developer at Google said

> If the user was already signed in, requesting auth.currentUser() does not refresh their profile data from the server.  

which makes matter only more confusing, as this is not the case with my tested code.

Here is the example:

```dart
static stackOverflowProblem() async {
    FirebaseUser user = await FirebaseAuth.instance.currentUser();
    print("Name of User: ${user.displayName}"); //prints foo

    //Renaming the name from "foo" to "bar"
    UserUpdateInfo userInfo = UserUpdateInfo();
    userInfo.displayName = "bar";
    await _auth.updateProfile(userInfo);

    print("\nBefore calling user.reload:");
    print("Name of user: ${user.displayName}"); //prints foo
    print("Name of FirebaseAuth.instance.currentUser: ${(await FirebaseAuth.instance.currentUser()).displayName}"); //prints bar

    await user.reload();

    print("\nAfter calling user.reload:");
    print("Name of user: ${user.displayName}"); //prints foo
    print("Name of FirebaseAuth.instance.currentUser: ${(await FirebaseAuth.instance.currentUser()).displayName}"); //prints bar
  }
```   
Output:
```dart
I/flutter (19989): Name of User: Foo
I/flutter (19989): 
I/flutter (19989): Before calling user.reload:
I/flutter (19989): Name of user: Foo
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: bar
I/flutter (19989): 
I/flutter (19989): After calling user.reload:
I/flutter (19989): Name of user: Foo
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: bar
```

The output i would assume, based on the answer from Frank van Puffelen and from my assumption about how the reload method should work, is:
```dart
I/flutter (19989): Name of User: Foo
I/flutter (19989): 
I/flutter (19989): Before calling user.reload:
I/flutter (19989): Name of user: Foo
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: Foo
I/flutter (19989): 
I/flutter (19989): After calling user.reload:
I/flutter (19989): Name of user: bar
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: Foo
```
Maybe also like this, as IMO FirebaseAuth.instance.currentUser() should always give the newest information, atleast that's how I think it works/should work.
```dart
[...]
I/flutter (19989): After calling user.reload:
I/flutter (19989): Name of user: bar
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: bar
```

So any help with that, what is reload() for? Am I just confusing the method should work, or what is happening?!
Please also look at the [Stackoverflow Question](https://stackoverflow.com/questions/51709733/what-use-case-has-the-reload-function-of-a-firebaseuser-in-flutter).
Thanks!

**Comment by JSANL** [comment]
@holyspidoo but why do you even need `user.reload()` then? I mean in your example you could just neglect it, couldn't you?

**Comment by holyspidoo** [comment]
No. If you don't do reload, currentUser() gives you cached data unless you sign out, then sign back in. Calling currentUser will give you new data ONLY if you do it after reload()

**Comment by JSANL** [comment]
@holyspidoo
But that's exactly the root question of my example, because I get the new data **before** calling `user.reload()` from `_auth.currentUser()` and I always get the old data when using the old `FirebaseUser` object, even with `user.reload()`.

**Comment by holyspidoo** [comment]
I think it is because you update the user info. When you do that, you don't need to reload, you've changed data, thus it is reloaded. Emailverification is changed server side, thus to check the emailverification, you must reload from server to see if it changed.

**Comment by dotdoom** [comment]
Looks like not updating the user object that had `reload()` called on is WAI (working as... implemented) to match Android / iOS SDK. See discussion at https://github.com/flutter/plugins/pull/533.

In my understanding, `reload()` is primarily for picking up updates by providers (e.g. Google, Facebook, Twitter) available via `user#providerData`, or Firebase profile updates made on another device, rather than updates done locally in the app.

**Comment by kika** [comment]
> or Firebase profile updates made on another device, rather than updates done locally in the app.

This is also not the case, because right now I'm struggling to see the change in the internal `isEmailVerified` flag, provided by Firebase itself.

**Comment by loolooii** [comment]
@kika that flag is set serverside, so your app doesn't know that it happened before you somehow refresh the FirebaseUser object.

Is it possible to somehow "listen" to this? I mean I know that `onAuthStateChanged` isn't triggered right know when verification link is clicked, but is it possible that this will be implemented in the future? Or is there anyway at this moment that we could navigate from a page in flutter the moment that the user verified their email ?

**Comment by kika** [comment]
@loolooii Exactly, I'm using `reload()` to refresh and this flag doesn't refresh.

**Comment by chris-lsn** [comment]
For a temporary solution, 
simply use `_authenticatedUser = await _auth.currentUser();` 
instead of `_authenticatedUser.reload()`

**Comment by ericduffett** [comment]
I had a lot of issues with trying to grab the current user, reload, etc., etc. as described above. For me, the easiest way was just to sign in the user using 

`var _authenticatedUser = await _auth.signInWithEmailAndPassword(email: _email, password: _password);` where _email and _password were simply what the user typed in the textfields. 

where `final FirebaseAuth _auth = FirebaseAuth.instance;`

Then I could check to see ```
if (_authenticatedUser.isEmailVerified) {
//Verified
} else {
//Not verified
}
```

**Comment by suesitran** [comment]
i'm having same problem with `isEmailVerified`, and I dont wanna keep user password in app, so I dont have a way to signin user only to get updated value of `isEmailVerified`

**Comment by OmarSultan85** [comment]
> Odd, I had the same issue but calling currentUser() a second time seems to fix it for me (using dev flutter). This is what I do for isEmailVerified:
> 
> ```
> FirebaseUser user = await _firebaseAuth.currentUser();
> await user.reload();
> user = await _firebaseAuth.currentUser();
> bool flag = user.isEmailVerified;
> ```
> 
> Where final _firebaseAuth = FirebaseAuth.instance;
> 
> If I don't add the second currentUser() call, it does not work though. But in your example you call it again also when you do await FirebaseAuth.instance.currentUser()).displayName...

I really don't get it but that exact sequence of Current User - Reload - Current User was the only way I was able to get it to work

**Comment by bmcilw1** [comment]
This is still an issue. This is particularly annoying when exposing the current user through the stream available at `_firebaseAuth.onAuthStateChanged`.

I can't get the `onAuthStateChanged` stream to update without calling `_firebaseAuth.signOut()`.

Please fix `user.reload()` to update both the `_firebaseAuth.currentUser()` as well as the `_firebaseAuth.onAuthStateChanged`.

**Comment by cantaspinar** [comment]
I am experiencing the same issue. Any update on that?

**Comment by dungnv2602** [comment]
> This is still an issue. This is particularly annoying when exposing the current user through the stream available at `_firebaseAuth.onAuthStateChanged`.
> 
> I can't get the `onAuthStateChanged` stream to update without calling `_firebaseAuth.signOut()`.
> 
> Please fix `user.reload()` to update both the `_firebaseAuth.currentUser()` as well as the `_firebaseAuth.onAuthStateChanged`.

That exactly what I expect reload() to do. 
I'm exposing Stream<FirebaseUser> through Provider to allow global access.
And reload() doesn't update data of stream at all.

**Comment by kroikie** [comment]
@JSANL

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/717. Any further collaboration will be done there.

**Comment by feinstein** [comment]
I made a package to fix this, grab it here: [firebase_user_stream](https://pub.dev/packages/firebase_user_stream) 

In the Readme I explain the issues and how the package fixes them, there are examples and etc, enjoy!

**Comment by haroonkhan9426** [comment]
I'm even calling **firebaseAuth.currentUser** after reload() like this:
`final user = await _auth.currentUser();
    print('Before update: ${user.photoUrl}');
    user.updateProfile(updatedInfo);
    await user.reload();
    final newUser = await FirebaseAuth.instance.currentUser();
    print('After update:  ${newUser.photoUrl}');`

But the profile is not updated then as well.
Here is the output: 
`I/flutter (17551): Before update: foo
I/flutter (17551): After update:  foo`

**Comment by haroonkhan9426** [comment]
@feinstein I tried the package you have published, but that does not as well.

**Comment by haroonkhan9426** [comment]
Actually It takes sometime for reload() to fetch the data locally:
Here I tried the same code with a 2 seconds delay:
`final user = await _auth.currentUser();`
   ` print('Before update: ${user.displayName}, ${user.photoUrl}');`
    `user.updateProfile(updatedInfo);`
   ` await user.reload();`
    `final newUser = await FirebaseAuth.instance.currentUser();`
    `print('After update: ${newUser.displayName}, ${newUser.photoUrl}');`
   ` await Future.delayed(Duration(seconds: 2));`
   ` final newestUser = await FirebaseAuth.instance.currentUser();`
   ` print('After delay: ${newestUser.displayName}, ${newestUser.photoUrl}');`

And here is the output:

`I/flutter ( 5492): Before update: test20, bar`
`I/flutter ( 5492): After update: test20, bar`
`I/flutter ( 5492): After update: test20, foo`

**Comment by feinstein** [comment]
@haroonkhan9426 you aren't waiting for the update, I already answered the issue you opened at the package's issue page, please keep the conversation there: feinstein/firebase_user_stream#1

**Comment by lukestokes94** [comment]
> @haroonkhan9426 this isn't related to my package, you aren't awaiting for the update, I already answered the issue you opened at the package's issue page, please keep the conversation there: [feinstein/firebase_user_stream#1](https://github.com/feinstein/firebase_user_stream/issues/1)
> 
> PS: You don't need those 2 seconds delay at all, even if you don't use my package.

@feinstein trying to use your manual method and the above Current User - Reload - Current User method and still not working for my use case where I want to assign the DisplayName immediately on account creation to a local User class stream. It seemed to work after a hot reload weirdly so the only foolproof method I've found if is to force a sign out and sign in, so hopefully this is some help to someone:

`Future registerWithEmailAndPassword(String email, String password, String displayName) async {
    try {
      UserUpdateInfo userUpdateInfo = new UserUpdateInfo();
      userUpdateInfo.displayName = displayName;
      AuthResult result = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      FirebaseUser user = result.user;
      await user.updateProfile(userUpdateInfo);
      await user.reload();

      //relevant signout code below as user.reload won't update user object until signin/signout forced and only way to ensure DisplayName is available immediately on first log in
      await _auth.signOut();
      AuthResult result2 = await _auth.signInWithEmailAndPassword(email: email, password: password);
      FirebaseUser user2 = result2.user;
      
      //pass user to custom User class which is used through Provider
      return _userFromFirebaseUser(user2);
    } catch(e) {
      print(e.toString());
      return null;
    }
  }`

**Comment by feinstein** [comment]
@lukestokes94 you have 2 options:

1 - After  you do `user.reload();` make a `await _auth.currentUser()` and use that user to change the name, don't forget to `await` for all the operation, as the changes are only available after the `await` returns.

2 - Use my package that simplifies all of this: https://pub.dev/packages/firebase_user_stream

In your case, you can use it like this: `var user = await FirebaseUserReloader.reloadCurrentUser();`

**Comment by lukestokes94** [comment]
@feinstein thanks for the reply, but I've tried the manual method 1 and it still doesn't work for my use case and shows null for the DisplayName immediately after sign in - I have a button to print the DisplayName getter on my user class and this still won't work until I sign in and out. These are the relevant methods within my AuthService class using method 1 and I've tried multiple different attempts to get it to work. Appreciate the package but trying to understand why the below won't work before I implement it.

```
User _userFromFirebaseUser(FirebaseUser user) {
    return user != null ? User(uid: user.uid, displayName: user.displayName) : null;
  }

  //auth change user stream
  Stream<User> get user {
    return _auth.onAuthStateChanged
    .map(_userFromFirebaseUser);
  }

  //create email sign in method
  Future signInWithEmailAndPassword(String email, String password) async {
    try {
      AuthResult result = await _auth.signInWithEmailAndPassword(email: email, password: password);
      FirebaseUser user = result.user;
      return _userFromFirebaseUser(user);
    } catch (e){
      print(e.toString());
      return null;
    }
  }

  // register

  Future registerWithEmailAndPassword(String email, String password, String displayName) async {
    try {
      UserUpdateInfo userUpdateInfo = new UserUpdateInfo();
      userUpdateInfo.displayName = displayName;
      AuthResult result = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      FirebaseUser user = result.user;
      await user.reload();

      FirebaseUser user2 = await _auth.currentUser();
      await user2.updateProfile(userUpdateInfo);

      return _userFromFirebaseUser(user2);
    } catch(e) {
      print(e.toString());
      return null;
    }
  }
```

**Comment by feinstein** [comment]
You have the following:

```dart
FirebaseUser user2 = await _auth.currentUser();
await user2.updateProfile(userUpdateInfo);

return _userFromFirebaseUser(user2);
```

You are basically asking for the current user, Firebase Auth returns you an object representing the current user, then you as Firebase Auth to update that user's name and then you return the object you got BEFORE you updated the user name. 

Try this instead:

```dart
FirebaseUser user2 = await _auth.currentUser();
await user2.updateProfile(userUpdateInfo);

await user2.reload(); // This might not be necessary at all, test it and let me know
FirebaseUser user3 = await _auth.currentUser();

return _userFromFirebaseUser(user3);
```

**Comment by lukestokes94** [comment]
@feinstein I did wonder if it was some kind of race condition but I'm afraid it's still not working with your update. Full method below, which still returns null on user.displayName until I sign the user out and in again:

```
`  Future registerWithEmailAndPassword(String email, String password, String displayName) async {
    try {
      UserUpdateInfo userUpdateInfo = new UserUpdateInfo();
      userUpdateInfo.displayName = displayName;
      AuthResult result = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      FirebaseUser user = result.user;
      await user.reload();
      FirebaseUser user2 = await _auth.currentUser();
      await user2.updateProfile(userUpdateInfo);

      await user2.reload(); // This might not be necessary at all, test it and let me know
      FirebaseUser user3 = await _auth.currentUser();

      return _userFromFirebaseUser(user3);

    } catch(e) {
      print(e.toString());
      return null;
    }
  }`
```

**Comment by feinstein** [comment]
Change your return type to `Future<User>` instead, avoid using a pure `Future`, if you don't want to return anything, use `Future<void>`.

**Comment by lukestokes94** [comment]
Tried, still no luck thanks. With this thread and the other questions I've seen elsewhere with similar issues I'm writing this down to a bug and/or limitation of Firebase and leaving my signOut method as the current workaround.

**Comment by feinstein** [comment]
Are you awaiting for the result of that method?

**Comment by feinstein** [comment]
So, here's the code that I use in one of my projects, if this doesn't help you, then open a stackoverflow.com question and let's follow there, this has polluted this thread too much already.

I am using try-catch (simplified here), see if this helps you:

```dart
Future<void> onFinished() async {
    try {
      AuthResult result = await _firebaseAuth.createUserWithEmailAndPassword(
          email: _email, password: _password);
      // If there's an exception at this point, a new User will already be created.
      // but the user will not have any `displayName`. Since this is a very rare
      // case, for now no actions will be taken, as the user can already change
      // its name on the user settings.
      await result.user?.updateProfile(UserUpdateInfo()..displayName = name);
    }
```

**Comment by Mr-Martini** [comment]
June 2020, this problem still exits.

**Comment by feinstein** [comment]
@Mr-Martini this won't be fixed or modified, for now it's "intended behavior", the only alternative that I know is my package that you can get here:  [firebase_user_stream](https://pub.dev/packages/firebase_user_stream).

**Comment by kamleshwebtech** [comment]
I wanted to update displayName of firebase user in Flutter application and it worked for me by using below code:

```
import 'package:firebase_auth/firebase_auth.dart';

class Auth {
  final FirebaseAuth auth = FirebaseAuth.instance;

  User user;

  Future<User> handleSignInEmail(String email, String password) async {
    UserCredential result =
        await auth.signInWithEmailAndPassword(email: email, password: password);
    user = result.user;

    return user;
  }

  Future<User> handleSignUp(email, password) async {
    UserCredential result = await auth.createUserWithEmailAndPassword(
        email: email, password: password);
    user = result.user;

    return user;
  }
}
```

`var authHandler = new Auth();`

`User _userInfo;`

```
Future _updateDisplayName(User firebaseUser) async {
    String name = displaynameController.text;
    firebaseUser.updateDisplayName(name).then((value) async {
      await authHandler.user.reload();
      _userInfo = authHandler.auth.currentUser;
      print("_updateDisplayName: ${_userInfo.toString()}");
    }).catchError((e) {
      print(e);
    });
  }
```

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: Text("User Info: ${_userInfo.toString()}"),
        ),
    );
}
```

dependencies in pubspec.yaml file: 

```
firebase_auth: ^1.4.1
firebase_core: ^1.3.0
```

I hope, this solution will help you. Thanks for asking this question.
