### ISSUE TITLE
Please support animated gifs.

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#204]
<a href="https://github.com/apwilson"><img src="https://avatars.githubusercontent.com/u/142874?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [apwilson](https://github.com/apwilson)**
_Friday Oct 16, 2015 at 20:05 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1649_

---

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Saturday Oct 17, 2015 at 02:11 GMT_

----

Noooooooooooooo.  I knew this day would come.  Alright.

**Comment by eseidelGoogle** [comment]
For some uses, video might work instead: https://github.com/flutter/flutter/issues/2319

**Comment by dvdwasibi** [comment]
Also needed for customer:queue 
:)

**Comment by sethladd** [comment]
We don't have this on our roadmap right now. Presumably this can be done as a library. We're going to close, but we can reopen if the framework or engine needs to do something specific here to support this feature.

**Comment by abarth** [comment]
Given that this issue is a customer request from customer: pink, I'd like to keep the issue open.

**Comment by eseidelGoogle** [comment]
Pink sees this as a P2-level issue and would like to have this in the first half of this year if possible.

**Comment by dvdwasibi** [comment]
how bout 'em animated PNGs?

https://chromium.googlesource.com/chromium/src/+/7d2b8c45afc9c0230410011293cc2e1dbb8943a7

**Comment by abarth** [comment]
We'll likely get them working at the same time.

**Comment by perlatus** [comment]
Just wanted to note that this would be useful for displaying animated gifs from sources you don't control and that can't easily be converted. For instance, a reddit app implemented in flutter would need the ability to display gifs from imgur.

**Comment by nanowang** [comment]
Just published a simple plugin for animated gif: https://github.com/nanowang/flutter_animated

It still lacks of a number of key features.

**Comment by Hixie** [comment]
Assigning to myself. I'll speak with @abarth and get a braindump of how he was hoping this would work.

**Comment by abarth** [comment]
I imagined this would work as follows:

1. https://docs.flutter.io/flutter/dart-ui/decodeImageFromList.html would give you back an object that understood that images could have multiple frames and contained whatever information is reasonable about the number of frames and the delay for the next frame.

2. That object would come with the first frame already decoded as well as a function that requests that the next frame be decoded (asynchronously).

3. Something in the framework (probably in the widgets layer) would look at this information and (a) request the next image and (b) schedule a timer to present the next image.

4. When the timer goes off, the framework switches out the current image for the next frame and repeats (3) as needed.

There's a question of what we should do if we can't decode frames fast enough to keep up with the timer.  The traditional thing to do is present all the frames as close to the requested frame rate as possible, which is what the algorithm above does.  That's probably what we want to do as well given that many animated image formats (e.g., GIF) make it hard to skip frames.

The other thing to watch out for is that the actual frame rate at which we're expected to present images doesn't match the value encoded in the image.  The function is slightly tricky, but it might be in the HTML Living Standard somewhere.  As I recall, a delay of zero gets mapped to some non-zero delay, etc.

Finally, it's very important that images that are off-screen do not consume battery animating.  That means we should tie these animations into the TickerProvider mechanism we use to solve this problem for other animations.

**Comment by sethladd** [comment]
thanks @abarth !

**Comment by amirh** [comment]
Animated Images should now be working.
You can just use the normal Image widget with an animated image and it should play.

**Comment by sethladd** [comment]
Thanks @amirh !

**Comment by abarth** [comment]
![mic-drop](http://static3.businessinsider.com/image/56fdb998dd08951c768b4a58-480/neil-degrasse-tyson-mic-drop.jpg)

**Comment by efortuna** [comment]
![excited](https://user-images.githubusercontent.com/2112792/32971648-ffcda576-cba2-11e7-897d-93190ee9b2f0.gif)

**Comment by xster** [comment]
![win](https://media.giphy.com/media/xThuWpoG470Q0stGmI/giphy.gif)

**Comment by txthinking** [comment]
Waiting to be merged into alpha branch
