### ISSUE TITLE
Generate goldens for CupertinoAlertDialog

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#20404]
After #18381 is completed, generate goldens to lockdown the current behavior.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by Hackmodford** [comment]
@pedromassangocode It probably would have helped avoid this issue.
https://github.com/flutter/flutter/issues/151908

**Comment by victorsanni** [comment]
https://github.com/flutter/flutter/pull/150410 adds some goldens for `CupertinoAlertDialog`. I think with the recent work by @dkwingsmt, this issue can be closed.
