### ISSUE TITLE
Flutter Camera Plugin Memory Leak

### ISSUE THREAD

**Issue by bdytx5** [flutter/flutter#20402]
## Steps to Reproduce

https://github.com/flutter/plugins/tree/master/packages/camera
by downloading and running the example, there is a memory leak when taking a picture. Memory is never freed, and continues to build up. This does not happen with video recording however.  Ive attached a screenshot of the memory mountain. Any idea on how to fix this in the objective-c code? Thanks
![screen shot 2018-08-09 at 7 44 24 pm](https://user-images.githubusercontent.com/32812705/43932978-a71f7a54-9c0c-11e8-9d4a-45ad83a4720b.png)

**Comment by zoechi** [comment]
Dup of #20943 
This one is older but the other issue has more information.
Thanks for reporting.
