### ISSUE TITLE
Debugger buttons don't have hover tooltips

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2041]
Which one is step over, step into?

**Comment by sethladd** [comment]
cc @iposva-google @devoncarew

**Comment by eseidelGoogle** [comment]
There was also confusion between the "run" looking button in the Debugger and the "run" looking button in the toolbar.  Maybe they're the same thing?

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-atom/dartlang/pull/779 (for the tooltips)

re: the two run buttons, one means 'launch app' and one means 'resume from paused'. Perhaps different icons would help here.

**Comment by iposva-google** [comment]
Suggestion for the "pause"/"resume" button: Pause generally is two vertical bars, for resume keep the left vertical bar and morph the right vertical bar to a play button.

**Comment by devoncarew** [comment]
I tweaked the icons a bit to avoid confusion. @iposva-google, with the icons sets easily available to us, we don't have that specific combo of icons. I'll keep an eye out for an vcr play-pause button.
