### ISSUE TITLE
StreamBuilder not updating Stateful Widgets

### ISSUE THREAD

**Issue by DevilWarrior** [flutter/flutter#20416]
Hi,

I stumbled upon what it seems to be a bug. I'm using a StreamBuilder in order to build a ListView with messages. If I use a stateless widget than everything works as expected; when adding new items to the database, they are updated in the ListView. If I use a Stateful widget otherwise, the initial list is build but any further events are not displayed unless I manually scroll the list up/down. Why do I need a stateful widget for a ListView? I want to show some animations when tapping on the items. Here's how to reproduce the issue:

**Here's my StreamBuilder:**

```
StreamBuilder(
                  stream: Firestore.instance.collection('messages').document(chatID).collection('chats').orderBy('timestamp', descending: true).snapshots(),
                  builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
                    if(!snapshot.hasData) return const Text('');
                    return ListView.builder(
                      
                      reverse: true,
                      itemCount: snapshot.data.documents.length,
                      itemBuilder: (context, index) {
                        print(index);
                        return _buildMessageItem(snapshot.data.documents[index]);
                      },
                    );
                }
              )
```

**Here's the _buildMessageItem middleware**

```
Widget _buildMessageItem(DocumentSnapshot document) {
    // This does other things in my code
    return new MessageItem(document['message']);
}
```

**Here's the MessageItem class STATELESS (this one works/updates)**
```
class MessageItem extends StatelessWidget {
  final String message;
  MessageItem(this.message);

  @override
  Widget build(BuildContext context) {
    return new Text(message);
  }
}
```

**And here is the STATEFUL message class (it displays the items when built but it never updates)**
```
class MessageItem extends StatefulWidget {
  final String message;
  MessageItem(this.message);
  MessageItemState createState()=>  MessageItemState();
}


class MessageItemState extends State<MessageItem> {
  String message;

  @override
  void initState() {
    super.initState();
    message = widget.message;
  }

  @override
  Widget build(BuildContext context){
    return new Text(message);
  }
}
```

I'm on channel beta, v0.5.1 and `flutter doctor` prints everything OK

**Comment by DevilWarrior** [comment]
This does it, thanks for pointing me in the right direction.

**Comment by DhruvamSharma** [comment]
This is the code I am using in a stateful widget. Whenever I click on a button, I am fetching new data from the network and adding to the stream the StreamBuilder is listening to. It should rebuild and re-render the gridview but that is not happening. 

Where am I going wrong?


```
class HomeScreenListState extends State<HomeScreenList> {
  @override
  void initState() {
    super.initState();
    print("init");
    bloc.fetchAllMovies();
  }

  @override
  void dispose() {
    super.dispose();
    bloc.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      builder: (context, snapshot) {
        if (snapshot.hasData) {
          print("now here");
          return buildList(snapshot);
        } else if (snapshot.hasError) {
          return Text('Error!!');
        }

        return Center(
          child: CircularProgressIndicator(),
        );
      },
      stream: bloc.newResults,
    );
  }

  @override
  void didUpdateWidget(HomeScreenList oldWidget) {
    super.didUpdateWidget(oldWidget);

    setState(() {});
  }

  Widget buildList(AsyncSnapshot<Result> snapshot) {
    var crossAxisCount;

    if (MediaQuery.of(context).orientation == Orientation.portrait) {
      crossAxisCount = 2;
    } else {
      crossAxisCount = 3;
    }

    return GridView.builder(
        itemCount: snapshot.data.results.length,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: crossAxisCount,
        ),
        itemBuilder: (BuildContext context, int index) {
          return Hero(
            tag: snapshot.data.results[index].id,
            transitionOnUserGestures: true,
            child: Material(
              child: InkWell(
                onTap: () {
                  moveToDetailScreen(index, snapshot.data);
                },
                splashColor: Colors.red,
                child: Image.network(
                  'https://image.tmdb.org/t/p/w185'
                      '${snapshot.data.results[index].poster_path}',
                  fit: BoxFit.cover,
                ),
              ),
            ),
          );
        });
  }

  moveToDetailScreen(int index, Result model) {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) {
        return DetailScreen(
          model: model.results[index],
        );
      }),
    );
  }
}


```

**Comment by zoechi** [comment]
@DhruvamSharma 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by toanphung** [comment]
> You need to change the state when the widget changes, initState will only be called once when the state is inited, try adding something like this to the state class
> 
> ```
> @override
> void didUpdateWidget(MessageItem oldWidget) {
>     if(message != widget.message) {
>         setState((){
>             message = widget.message;
>         });
>     }
>     super.didUpdateWidget(oldWidget);
> }
> ```

Worked for me.

**Comment by viratshukla** [comment]
> You need to change the state when the widget changes, `initState` will only be called once when the state is inited, try adding something like this to the state class
> 
> ```dart
> @override
> void didUpdateWidget(MessageItem oldWidget) {
>     if(message != widget.message) {
>         setState((){
>             message = widget.message;
>         });
>     }
>     super.didUpdateWidget(oldWidget);
> }
> ```

How to call this method? When I am rotating my phone, its updating correctly.

**Comment by viratshukla** [comment]
> > You need to change the state when the widget changes, initState will only be called once when the state is inited, try adding something like this to the state class
> > ```
> > @override
> > void didUpdateWidget(MessageItem oldWidget) {
> >     if(message != widget.message) {
> >         setState((){
> >             message = widget.message;
> >         });
> >     }
> >     super.didUpdateWidget(oldWidget);
> > }
> > ```
> 
> Worked for me.

How to call this method didUpdateWidget() ??

**Comment by vitoryugulis** [comment]
> You need to change the state when the widget changes, `initState` will only be called once when the state is inited, try adding something like this to the state class
> 
> ```dart
> @override
> void didUpdateWidget(MessageItem oldWidget) {
>     if(message != widget.message) {
>         setState((){
>             message = widget.message;
>         });
>     }
>     super.didUpdateWidget(oldWidget);
> }
> ```

Worked for me!
Thank you very much.

> You need to change the state when the widget changes, `initState` will only be called once when the state is inited, try adding something like this to the state class
> 
> ```dart
> @override
> void didUpdateWidget(MessageItem oldWidget) {
>     if(message != widget.message) {
>         setState((){
>             message = widget.message;
>         });
>     }
>     super.didUpdateWidget(oldWidget);
> }
> ```

Worked for me!
Thank you very much :D
