### ISSUE TITLE
flutter_driver does not appear to provide a method for testing the value of a checkbox

### ISSUE THREAD

**Issue by mmcc007** [flutter/flutter#20410]
flutter_driver does not appear to provide a method for testing the value of a checkbox (or other non-text-based input like on/off buttons, etc AFAIK). 

I tried to create a custom method 'getChecked', following the pattern used by the 'getText()' method. But the classes and methods required to implement a corresponding 'getChecked() method are not exported or made public. Besides, it is seems unlikely that the necessary json in the request would be interpreted correctly, nor the correct json generated in the response. 

Is there a way to get the state of a checkbox (similar to using `getText()` to get text value associated with a text-related widget)? Is there a suggested workaround, or a plan to implement this feature?

**Comment by mmcc007** [comment]
[Here](https://github.com/brianegan/flutter_architecture_samples/blob/master/example/integration_tests/lib/integration_tests.dart#L94) is an example of how this problem is addressed in an existing project.

This essentially requires reporting the checkbox state in a text-based widget and using `getText()` to retrieve it, which is not an ideal solution.

**Comment by chris-rutkowski** [comment]
Link doesn't work anymore.

**Comment by iapicca** [comment]
Hi @mmcc007 
does this proposed [solution](https://github.com/flutter/flutter/issues/25561#issuecomment-448791696) works for you?
(please note this [answer](https://github.com/flutter/flutter/issues/25561#issuecomment-497458754) as well)
Thank you
