### ISSUE TITLE
Error reading dependency file C:\FlutKart-master\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by dadmad817** [flutter/flutter#20425]
I was Working on my laptop with its battery removed, i opened android studio and was coding then the electricity went off in the middle of the process of gradlew and then when I turned it back on and reopened android studio this error showed up:
Launching lib\main.dart on SM G930V in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Error reading dependency file C:\FlutKart-master\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file C:\FlutKart-master\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file C:\FlutKart-master\build\app\intermediates\flutter\debug\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

Oops; flutter has exited unexpectedly.
Crash report written to C:\FlutKart-master\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Finished with error: Gradle build failed: 1

help please

**Comment by zoechi** [comment]
Can you also please post the content of `C:\FlutKart-master\flutter_07.log;` or what other file is mentioned if you reproduce the problem?

**Comment by dadmad817** [comment]
I solved my problem long time ago I used flutter clean and invalidate
cashes and restart

**Comment by zoechi** [comment]
@dadmad817 thanks for the update.
