### ISSUE TITLE
url_launcher has 2 second delay on OnePlus 5 – 8.1

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20439]
A user is reporting that launching URLs on his OnePlus 5 (running Android 8.1) has a 2 second delay before launching. On my LG Stylo 2 (5.1) it is instant, as it is on my iPhone 5c running iOS 10.

I have tried both of these and they produce the same results.

```dart
  void _launchURL(String url) async {
    try{
      launch(url);
      print('launched $url');
    }
    catch (e){
      print('Cannot launch $url');
      print(e);
    }
  }
```

```dart
  void _launchURL(String url) async {
    print(url);
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
```

**Comment by lukepighetti** [comment]
The user has also mentioned that after a fresh restart the first URL launch is fast and subsequent launches to any URL are slow.

**Comment by TahaTesser** [comment]
Hi @lukepighetti 
Given the old version of the plugin, inactivity of the issue, no mentioned issues, duplicates
 I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
