### ISSUE TITLE
Text background color is not trivial to implement

### ISSUE THREAD

**Issue by eshinkawa** [flutter/flutter#20430]
`TextStyle(
                fontSize: 14.5,
                color: Colors.white,
                fontWeight: FontWeight.w600,
                background: Paint()..color = Color(0xFF3b9c00),
              ),`

This is not documented in Paint() so I had to dig in deeper into the gists. A better implementation of this should be considered.

**Comment by Hixie** [comment]
We could add something like a `backgroundColor` argument on `TextStyle` that creates the right paint. We could even add a `backgroundGradient`. (You can only specify one of those two and `background`.)

What would be REALLY good is to take a Decoration, but that's a whole new thing, and no-one is asking for it.

**Comment by feinstein** [comment]
@Hixie I would like a `Decoration`, I am trying to change the way an error message appears on a `TextFormField` and it's not simple to get something like this:

![image](https://user-images.githubusercontent.com/8120472/53856095-4f134380-3faf-11e9-8d94-22ddf005723a.png)
