### ISSUE TITLE
Feedback on Firebase_Auth

### ISSUE THREAD

**Issue by samgithub-duplicate** [flutter/flutter#20444]
Please provide an option where we can us Firebase for authentication BUT **optionally** not for maintaining user list within Firebase database.  eg
```dart
  FirebaseUser user = await _auth.signInWithGoogle(
    accessToken: googleAuth.accessToken,
    idToken: googleAuth.idToken,
    **maintainInDatabase: false,**   //default --> true
  );
```

**Comment by zoechi** [comment]
> maintaining user list within Firebase database

What does that mean?

**Comment by zoechi** [comment]
Can you please elaborate? I don't understand your request.
What user list are you referring to?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
