### ISSUE TITLE
Does Flutter Run on the web? FAQ entry could link to Dart alternatives

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#20442]
Might want to link to other Dart projects, e.g. Angular from:
https://flutter.io/faq/#does-flutter-run-on-the-web
FYI @kevmoo @mit-mit

**Comment by mit-mit** [comment]
@kevmoo you wanna grab this one?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1963](https://github.com/flutter/website/issues/1963) via [**ZenHub**](https://www.zenhub.com/)
