### ISSUE TITLE
Firebase Storage get reference to a document using download URL

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#20458]
There is no way to get a reference to a document using the document's download URL.

I know that it can be done in Kotlin using `StorageReference.getReferenceFromUrl(url);`

**Comment by puf** [comment]
Another developer was affected by this: https://stackoverflow.com/q/54170250

**Comment by collinjackson** [comment]
This API looks fairly straightforward to add, see flutter/plugins#1208

**Comment by kroikie** [comment]
@AndreHaueisen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/715. Any further collaboration will be done there.
