### ISSUE TITLE
Firebase Analytics plugin does not properly report all types of route changes

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#20452]
If you replace or remove the current route, I would expect it to be reported by `FirebaseAnalyticsObserver`; however, that class does not observer `didRemove` nor `didReplace`.

**Comment by kroikie** [comment]
@alanrussian

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/716. Any further collaboration will be done there.
