### ISSUE TITLE
Expose API for getting a Stream<Route> with the current Route from NavigatorState

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#20451]
It's technically possible to keep track of the current route using a `NavigatorObserver`; however, it's error prone because the logic is a little more complex than it may seem at first (e.g., you can remove and replace routes that are at or below the current route). Providing an API would ensure people are getting a reference to the correct route. 

There's an internal question with more details about my use case.

**Comment by mehmetf** [comment]
Correct me if I am wrong but you are also interested in getting the previous route as well, right? Is that the route that was displayed before the current route or is it the one under the current route in the navigation stack?

**Comment by alanrussian** [comment]
For the use case I opened this issue for, I only need the current route.

**Comment by alanrussian** [comment]
Turns out I need a Stream of the current place. I've updated the title.

**Comment by mehmetf** [comment]
Is this a blocker for beta launch or full launch?

**Comment by alanrussian** [comment]
This isn't a blocker since we can work around it.

**Comment by alanrussian** [comment]
Here's an implementation for what I'm asking for using RouteObserver

```dart
class FlutterCurrentRouteNavigatorObserver extends NavigatorObserver {
  final _onRouteChange = StreamController.broadcast<Route>();

  Route _route;

  // Currently visible route.
  Route get route => _route;

  // A stream that emits a value when the currently visible [route] changes.
  Stream<Route> get onRouteChange => _onRouteChange.stream;

  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    _updateRoute(route);
  }

  @override
  void didReplace({Route<dynamic> newRoute, Route<dynamic> oldRoute}) {
    if (_route == oldRoute) {
      _updateRoute(newRoute);
    }
  }

  @override
  void didPop(Route route, Route previousRoute) {
    _updateRoute(previousRoute);
  }

  @override
  void didRemove(Route route, Route previousRoute) {
    if (route == _route) {
      _updateRoute(previousRoute);
    }
  }

  void _updateRoute(Route route) {
    _route = route;
    _onRouteChange.add(route);
  }
}
```

**Comment by marica27** [comment]
I need also a current route. I'd use now solution that @rrousselGit  suggested.
Though I've tried tweak a Navigator `Route get current => _history.last;` and it is simple

**Comment by rrousselGit** [comment]
Is there any information about why the `history` field is private?

It would solve quite a few of these problems if that field was public. Or if we had a `onHistoryChanged(List<Route> history) ` on `RouteAware`

**Comment by rrousselGit** [comment]
A little update on that topic:

There seems to be an endpoint for this now:

```dart
ModalRoute.of(context)
```

It's definitely better than the previous trick used

**Comment by Ikxyz** [comment]
To get the exact route name eg /home use  

import 'package:path/path.dart';

ModalRoute.of(context).settings.name

**Comment by marcglasberg** [comment]
`Navigator.popUntil` always works, but `ModalRoute.of(context)` doesn't always. 

Besides, history contains all the history, not only the current route.

Instead of making history public we could have a getter:

    List<Route<dynamic>> get history => List.of(_history);

**Comment by rrousselGit** [comment]
The real issue is that history changes over time, and as such, it is anti-pattern to expose it in `Navigator.of` because dependents won't rebuild when history changes.

That's probably why we have _RouteObserver_ instead of exposing _history_ directly.


Maybe a solution instead is to allow dynamically adding _RouteObservers_

**Comment by hazzo** [comment]
> Here's an implementation of a stream as well as the current route using a `NavigatorObserver`.
> 
> ```dart
> class FlutterCurrentRouteNavigatorObserver extends NavigatorObserver {
>   final _onRouteChange = StreamController.broadcast<Route>();
> 
>   Route _route;
> 
>   // Currently visible route.
>   Route get route => _route;
> 
>   // A stream that emits a value when the currently visible [route] changes.
>   Stream<Route> get onRouteChange => _onRouteChange.stream;
> 
>   @override
>   void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
>     _updateRoute(route);
>   }
> 
>   @override
>   void didReplace({Route<dynamic> newRoute, Route<dynamic> oldRoute}) {
>     if (_route == oldRoute) {
>       _updateRoute(newRoute);
>     }
>   }
> 
>   @override
>   void didPop(Route route, Route previousRoute) {
>     _updateRoute(previousRoute);
>   }
> 
>   @override
>   void didRemove(Route route, Route previousRoute) {
>     if (route == _route) {
>       _updateRoute(previousRoute);
>     }
>   }
> 
>   void _updateRoute(Route route) {
>     _route = route;
>     _onRouteChange.add(route);
>   }
> }
> ```

This implementation saved me!!! Thanks a lot! I was getting nuts as I couldn't found a "official" way of tracking every route for a navigator. The RouteAware mixin is kind of limited.

**Comment by pedromassangocode** [comment]
Now that [Navigator 2.0 ](https://github.com/flutter/flutter/issues/45938) was merged I think we now have a way to get the current Route.

@chunhtai can you please confirm?

**Comment by YeungKC** [comment]
@pedromassangocode I confirm that we can, at will, manage the current routing history.

**Comment by pedromassangocode** [comment]
@YeungKC 
Closing this one for now. Feel free to reopen if the new API does not satisfy this issue.

Would be helpful to have some reference in how to do that with the new API!

**Comment by YeungKC** [comment]
This article can help: https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade

Navigator.pages is all the route history.

I'm sorry I didn't express it in enough detail.
