### ISSUE TITLE
What Dart formatter does Flutter team use?

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20461]
Hello, I noticed that Flutter team does not seem to adhere to Dart formatting rules. I was wondering if you could explain what tool or formatter settings you are using, so that I may also use them.

Thank you
Luke

**Comment by jonahwilliams** [comment]
Hi @lukepighetti, we have a style guide here: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo.  It is generally similar to dartfmt, with some exceptions though.

**Comment by lukepighetti** [comment]
@jonahwilliams Thanks for the notes – do you guys edit your code manually after running it through `dartfmt` or is there a version that we can get access to?

**Comment by jonahwilliams** [comment]
100% artisan all natural hand formatted  😄

**Comment by lukepighetti** [comment]
Cold pressed too, I bet. Alright, thanks for the heads up. I will stop looking for the holy grail of flutter formatters. Maybe someday someone will make it happen.
