### ISSUE TITLE
Default format for text counter in TextField doesn't properly support Arabic and Hebrew

### ISSUE THREAD

**Issue by shujames** [flutter/flutter#20473]
Default counter in TextField is hardcoded to [text length]/[max text length]

In both Arabic and Hebrew, it looks like it should be flipped. [max text length]/[text length]

**Comment by amirh** [comment]
As a native Hebrew speaker I think it should stay [text length] / [max text length] as numbers are read from left to right.

**Comment by rami-a** [comment]
Closing this then since it seems that TextField is doing the right thing per @amirh's comment
