### ISSUE TITLE
The tooltip on the website in First Flutter App Part 2 is too excessive

### ISSUE THREAD

**Issue by usama8800** [flutter/flutter#20477]
In [Write Your First Flutter App, part 2](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2), anywhere I stop my mouse, a tooltip appears which is very annoying. 

The tooltip stops showing if I click my mouse once.
Then if I hover my mouse over something that has a tooltip, it starts appearing again wherever I stop my mouse 
Or if I scroll and then move my mouse

Also found the same in [From Java to Dart](https://codelabs.developers.google.com/codelabs/from-java-to-dart/#0) so it seems to be a bug in that kind of steppers

Using Chrome Version 68.0.3440.106 64 bit

**Comment by zoechi** [comment]
When I tried the tooltip was following the mouse for several seconds.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1938](https://github.com/flutter/website/issues/1938) via [**ZenHub**](https://www.zenhub.com/)
