### ISSUE TITLE
Dedup similar code between CupertinoAlertDialog and CupertinoActionSheet

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#20470]
After #18381 is merged, dedup similar code between CupertinoAlertDialog and CupertinoActionSheet.

The two were written in parallel by different developers. The Action Sheet copied a bunch of code from the Alert Dialog work and that copied code needs to be dedup'd.

**Comment by matthew-carroll** [comment]
Related ticket:
Cupertino dialog barrier should be #66000000 #18285

**Comment by Roshan13046** [comment]
is the issue closed?
can I work on this issue?

**Comment by campovski** [comment]
@TahaTesser can I work on this?

**Comment by TahaTesser** [comment]
@campovski 
Feel free to work on it,  to get started read the [contributors guide.](Contributing to Flutter)

**Comment by campovski** [comment]
@TahaTesser Thanks! I already did and I already have my dev env setup. Will work on this tomorrow 😃
