### ISSUE TITLE
gap above the soft keyboard on an iPhone X with SafeArea

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#20484]
There's a gap above the soft keyboard on an iPhone X when used with a SafeArea.

The reason for this appears to be the MediaQuery having bottom padding — there is bottom padding on the iPhone X to keep controls apart from the "home indicator" control.

I have changed the bottom padding on a MediaQuery and verified that the gap above the soft keyboard changes accordingly.

## Steps to Reproduce

1. Clone https://github.com/SteveAlexander/flutter_soft_keyboard_bug
2. Run it on an iPhone X or simulator with soft keyboard enabled
3. Notice the scrolling wobbles as you type (I'm filing a separate issue about that)
4. Notice that there is a gap above the soft keyboard

The gap is the same height as the bottom padding of the SafeArea.

![image](https://user-images.githubusercontent.com/4321921/43995697-cda607e8-9daa-11e8-88d9-c6fe61936a5f.png)

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.5.9-pre.17, on Mac OS X 10.13.6 17G2208, locale en-GB)
    • Flutter version 0.5.9-pre.17 at /Users/steve/code/flutter
    • Framework revision 5d8771d18d (16 hours ago), 2018-08-10 21:18:10 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone X • 1E0393AA-EF50-42AA-A244-3279599BE2C1 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by xlsmearlx** [comment]
Im having the same problem only with iPhone X.

**Comment by xster** [comment]
I strongly suspect this is fixed already but double check before closing

**Comment by HansMuller** [comment]
The wobbling issue was fixed in https://github.com/flutter/flutter/pull/24015

The layout issue appears to been fixed as well. I checked a version of the test app on Android with a fake notch - https://gist.github.com/HansMuller/d95295399ca97bb56e9e77ea34621d39
