### ISSUE TITLE
ScrollController.animateTo not firing the first time

### ISSUE THREAD

**Issue by polmp** [flutter/flutter#20480]
I'm making the FlutterChat app from Codelabs, doing some modifications in the layout. I'm trying to scroll down automatically when I send a message. I've achieved this using the ScrollController.animateTo in the following way:

`_scrollController.animateTo((_messages.length + 1/_messages.length)*_scrollController.position.maxScrollExtent,duration: const Duration(milliseconds: 300),curve: Curves.easeOut);`

Where _messages is a listview containing the messages and this function is called on every submit.

The problem is that the first time scrolling is not working. I deduced that is because when I insert the message, scrolling in the listview is still not enabled, so the function is called before.

<img width="379" alt="captura de pantalla 2018-08-11 a las 18 06 51" src="https://user-images.githubusercontent.com/11884018/43993657-5a1c9742-9d91-11e8-8c5e-5da820cdb6ac.png">

We can see that the scrolling hasn't took effect. But then, if I write another message:

<img width="382" alt="captura de pantalla 2018-08-11 a las 18 08 20" src="https://user-images.githubusercontent.com/11884018/43993670-9b25e202-9d91-11e8-8bdb-b13136150278.png">

Scrolling is working perfectly.

Any possible solution to this? Am I missing something?

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by polmp** [comment]
Hi,

I've tried it and still not working for me

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and if possible a minimal reproduction.

**Comment by lordgreg** [comment]
Hi. I've just had 0 luck with animating to position in ListView until I've found this issue. 

Using `Future.delayed` with Zero duration fixed the issue but this is non-self-explanatory. Maybe it would be good to add a small comment into the documentation?

Thank you for the Future info. 👍 

Regards.

**Comment by zoechi** [comment]
This depends no where you call the code. 
If you call it in `build()` you instruct the scroll view to scroll before the view is rendered and before it is even known if there is overflowing content and how much.

**Comment by zoechi** [comment]
@polmp please post a minimal running reproduction and the output of `flutter doctor -v`.

**Comment by polmp** [comment]
Using Future.delayed:
![issue_scroll_flutter](https://user-images.githubusercontent.com/11884018/45588273-70557a00-b912-11e8-8d03-d0b0c281a211.gif)
Flutter doctor:

> [✓] Flutter (Channel master, v0.8.2-pre.17, on Mac OS X 10.11.6 15G21013, locale es)
    • Flutter version 0.8.2-pre.17 at /Users/USER/Documents/Apps/flutter
    • Framework revision ed698b8165 (8 days ago), 2018-09-07 16:46:44 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/USER/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

> [!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS developmen.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

> [✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

> [✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)
> ! Doctor found issues in 1 category.

I'm having a lot of trouble because sometimes works and sometimes no. I don't have any idea of how to do it properly.

**Comment by zoechi** [comment]
> I'm making the FlutterChat app from Codelabs, doing some modifications in the layout. I'm trying to scroll down automatically when I send a message.

The easiest way would be to use `reverse: true`, then the list does that automatically.
