### ISSUE TITLE
Add support for gender material icons

### ISSUE THREAD

**Issue by arthurgustin** [flutter/flutter#20497]
In my application I have the need for displaying gender icons, not the symbols but the shape of man/women. Funny there is pregnant_woman, but no woman at all !

**Comment by semsturgut** [comment]
@arthurgustin Flutter team cannot add or exclude icon. Flutter get icons from [material.io](material.io) which is developed by Google. According to [material.io](material.io) they only have `baseline-pregnant_woman-24px `. So they don't have any more than this icon.

But you can still find some other 3rd party **Material** free to use icon. Such as [materialdesignicons.com](https://materialdesignicons.com)
You can search words like human_female and you can find different female icons.

<a href="https://imgbb.com/"><img src="https://image.ibb.co/mMDuQp/Screen_Shot_2018_08_12_at_8_26_16_PM.png" alt="Screen Shot 2018 08 12 at 8 26 16 PM" border="0" /></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/bZ1QWU/Screen_Shot_2018_08_12_at_8_26_23_PM.png" alt="Screen Shot 2018 08 12 at 8 26 23 PM" border="0" /></a>

My offer is much more easier than downloading each requirement icon and trying to implement it flutter.
[materialdesignicons.com](https://materialdesignicons.com) has 3rd party **Material** free to use icon library: [material_design_icons_flutter](https://pub.dartlang.org/packages/material_design_icons_flutter)


### Installation

In the `dependencies:` section of your `pubspec.yaml`, add the following line:

`  material_design_icons_flutter: 2.3.50`

### Usage

```
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    return new IconButton(
      // For this situation your icon name should be humanFemale
      icon: new Icon(MdiIcons.humanFemale), 
      onPressed: () { print("Using the sword"); }
     );
  }
}

```
`icon: new Icon(MdiIcons.humanFemale), `
<a href="https://imgbb.com/"><img src="https://image.ibb.co/khSzrU/Screen_Shot_2018_08_12_at_8_35_07_PM.png" alt="Screen Shot 2018 08 12 at 8 35 07 PM" border="0" /></a>

### Name Conversion

Some icons' name is reversed keyword in Dart (and most other languages), so the names have been changed.

- `null` -> `nullIcon`
- `switch` -> `switchIcon`
- `sync` -> `syncIcon`

**Comment by arthurgustin** [comment]
Such a nice answer @semsturgut thank you !

**Comment by zoechi** [comment]
Sounds like this is solved.
Thanks @semsturgut

**Comment by zeinab-sl** [comment]
@semsturgut Since the package does not support null safety, it can't be used anymore. It'd be nice to have an update for that package.

**Comment by semsturgut** [comment]
> @semsturgut Since the package does not support null safety, it can't be used anymore. It'd be nice to have an update for that package.

@zeinab-sl Actually, there is a null-safe version for this package. I haven't tried yet but you may want to take a look at this: https://pub.dev/packages/material_design_icons_flutter/versions/5.0.5955-rc.1
