### ISSUE TITLE
NetworkInterface.list() crashes

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#205]
<a href="https://github.com/kyorohiro"><img src="https://avatars.githubusercontent.com/u/1310669?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kyorohiro](https://github.com/kyorohiro)**
_Saturday Oct 17, 2015 at 02:15 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1655_

----

Following code cause to crash application 

[source]
import 'dart:io';
import 'dart:convert';
import 'dart:async';

main() async {
  List<NetworkInterface> interfaces = await NetworkInterface.list(
      includeLoopback: true, includeLinkLocal: true);
}

[project]
https://github.com/kyorohiro/hello_skyengine/tree/master/dartio_networkinterface

**Comment by FlutterIssues** [comment]
<a href="https://github.com/jason-simmons"><img src="https://avatars.githubusercontent.com/u/14226037?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jason-simmons](https://github.com/jason-simmons)**
_Friday Oct 23, 2015 at 22:14 GMT_

----

This API is not implemented in Dart for Android.  See Socket::ListInterfaces in dart/runtime/bin/socket_android.cc.

Socket::ListInterfaces is also not setting the OSError.  CObject::NewOSError then consumes the null OSError, resulting in a segfault.

**Comment by sethladd** [comment]
Is there an equivalent issue open in the Dart SDK?

**Comment by abarth** [comment]
There is now: https://github.com/dart-lang/sdk/issues/26329

**Comment by sethladd** [comment]
https://github.com/flutter/flutter/issues/3443 might also catch issues like this.

**Comment by sethladd** [comment]
Curious if we can close this? The Dart SDK issue is still open, but we might be able to close that, too.

**Comment by sethladd** [comment]
"should get a dart exception if you try to use it where it's not supported"

So, we're going to close, as there is no more crash.
