### ISSUE TITLE
Writing is totally broken on iOS

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20507]
OK, so maybe I'm missing something, but here goes.

1) No text controls. SO that means no autocorrect controls on cursor which totally breaks typing.  
2) No copy/paste. See above.
3) On multi-line the cursor is one character behind, so when you newline, it shows the cursor on the old line.
4) If you type a ? or ! and then do a send (like from a button) there seems to be no way to switch the keyboard back to home.
5) New emojis break into their components instead of showing the actual emojis.

This is all in a MaterialApp btw on Beta channel, up to date.

I don't mean to be a Debbie downer, but I literally cannot find a way to make any text input not a horrible UX on iOS. Maybe it's different on Android. I feel like I have to be missing something, because this is a blocking situation for any app that uses text input, which in my experience is every app.

**Comment by zoechi** [comment]
> 1. ... autocorrect

covered by #12920

> 2. copy/paste

#20692 shows it's there, but room for improvement

> 3. cursor is one character behind

Is this still an issue? This was an issue in Android as well but I think that's fixed #15572

> 5. Could be https://github.com/dart-lang/sdk/issues/28404

**Comment by lukepighetti** [comment]
1. Yes, but still not triages afaik even though the issue is 1 year old and it effects all iOS users who are typing in a Flutter app.

2. It is there but doesn't respond to double taps, only long holds.

3. seems to be resolved

**Comment by xster** [comment]
Thanks for connecting the issues @zoechi 

https://github.com/flutter/flutter/issues/9652 for the flutter-side issue on #5

**Comment by goderbauer** [comment]
It seems like everything covered by this issue is also covered by the other issues. I am closing this one to avoid duplication. Please post additional information to the individual bugs or open new individual bugs if none exist for the issue at hand.
