### ISSUE TITLE
ANDROID_HOME is blatantly ignored and config --android-sdk when trying to tell flutter where to find the android sdk

### ISSUE THREAD

**Issue by sivang** [flutter/flutter#20504]
## Steps to Reproduce

1. Install Android Studio, let it install for you the Android Sdk
2. Install Flutter
3. flutter -v doctor, will find android sdk
4. delete studio
5. delete android sdk (~/Android/Sdk)
6. install SDK using command line, by first downloading the 'tools' archive, then using sdkmanager --install <pkgs> to install it
7. change $ANDROID_HOME to reflect new install
8. flutter -v doctor:
 [✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
9. flutter config --android-sdk /home/sivan/bin/android-sdk/
10. flutter doctor gives the same android sdk not found error.

## Logs

```
sivan@metal:~$ flutter --verbose doctor
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
    • Flutter version 0.5.1 at /home/sivan/flutter/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/sivan/studio/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

```

```
```

**Comment by sivang** [comment]
So , after more investigations, I fired up the latest Android Studio and it identified that I was missing platform deps and installed them and now flutter works well, can there be some docs online to note how to build the platform development dependency tree manually ?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2446](https://github.com/flutter/website/issues/2446) via [**ZenHub**](https://www.zenhub.com/)
