### ISSUE TITLE
[firebase_database][firebase_animated_list.dart] cannot use with dismissible

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20505]
Hello,

I believe that you cannot use `Dismissible()` with a `FirebaseAnimatedList()` because the latter will not remove the list item fast enough to not throw an on-screen error that a "dismissed widget is still in the tree".

I believe this is because it is waiting for a new snapshot to show up.

I have FirebaseDatabase persistence on.

Any insight is much appreciated, this is blocking without writing my own FirebaseAnimatedList() that exposes the ability to remove an item by index.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by kamiab1** [comment]
you actually can, do this 
key: ObjectKey(index) // for the key 
and then wrap your widget in a FutureBuilder
something like this :
FutureBuilder(
          builder: (BuildContext context, AsyncSnapshot<Widget> value){
            return cardWidget();
          },
Widget cardWidget() { 
 return FirebaseAnimatedList(...)
}

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/713. Any further collaboration will be done there.
