### ISSUE TITLE
Atom Wish: manage flutter.yaml assets

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2051]
Keeping a flutter.yaml file up to date is tedious and error prone.

Atom could recognize explicit asset or icon references in Icon, IconButton, AssetImage (etc) code and offer to update the flutter.yaml file.

Similarly It would be nice if there was a way to show which flutter.yaml entries corresponded to literal source code references.

It would be nice if a specialized flutter.yaml editor could display how much space each of the icons and images would occupy, what the total was, etc.

For the material-design-icons (this is the dream scenario) Atom could be bundle ALL of the icons for test runs and then detect which ones were actually loaded and base an automatically generated flutter.yaml file on that.

**Comment by sethladd** [comment]
I love "convention over configuration"!

There are a lot of good requests in here. Don't hesitate to split these up, to make it easier to track and implement.

**Comment by jimbeveridge** [comment]
Consider the changes the #994 will bring, where all Material Design icons can be represented by a single (small, 56kb to 100KB) font file.  In this case, explicitly loading more than a handful of icons won't be worth it from a size perspective.

**Comment by abarth** [comment]
I'm going to solve this for icons with #994

**Comment by abarth** [comment]
There's no longer any management for icons.  However, we might still want this for other assets.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
