### ISSUE TITLE
minSize of CupertinoButton cannot below 44.0

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#20513]
## Steps to Reproduce

1. Add a CupertinoButton to App
2. Set the minSize to the value below 44.0
``` dart
CupertinoButton(
  minSize: 22.0,
  child: Row(
    children: <Widget>[
      Image(image: AssetImage('assets/icon_reply.webp'), width: 18.0, height: 18.0),
      child: Text(this.replyCount, style: TextStyle(fontSize: 14.0, color: Colors.black87)),
    ],
  ),
),
```
3. Run app, and we found that the CupertinoButton's height is still 44.0.

## Logs

```
```

```
```

```
```

**Comment by NikoYuwono** [comment]
Since it's the minSize not the maxSize, I think it's working as intended.
If you want to set the height to lower than 44.0, you can do it with setting the top and bottom padding to 0 or whatever value you want to set like below

```
CupertinoButton(
    minSize: 22.0,
    onPressed: _incrementCounter,
    color: Colors.blue,
    padding: EdgeInsets.fromLTRB(16.0, 0.0, 16.0, 0.0),
    child: Text("Hello", style: TextStyle(fontSize: 14.0, color: Colors.white)),
),
```

**Comment by jonahwilliams** [comment]
The Cupertino button follows the guidelines of https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/ . Touch targets should not be smaller that 44 by 44 on iOS. We might be missing an assert here

**Comment by talisk** [comment]
@jonahwilliams Thanks. In some cases we need a smaller button. The guideline may not satisfy the desire.

**Comment by xster** [comment]
The CupertinoButton adheres to Apple specs but in the end, it's just a glorified GestureDetector. Since Flutter is highly composable, if you look at the CupertinoButton source, it would be fairly easy to re-create a custom button type that adheres to any desired standards.
