### ISSUE TITLE
flutter run is error!

### ISSUE THREAD

**Issue by warriorBrian** [flutter/flutter#20516]
I tried to initialize the project is correct,
I use the vscode editor,
but, i Excuting an order `flutter run -v`,
prompt : Connection timed out !

**I tried running it a dozen times, still the same error, which made me unable to understand how to use flutter!**

@ianloic @paulcbetts @sgraham @sethladd @kevmoo 

![image](https://user-images.githubusercontent.com/28696399/44010736-ba30f6b8-9ee6-11e8-8f74-e86c1a7e1ee3.png)

![tim 20180813122400](https://user-images.githubusercontent.com/28696399/44012768-03d4a3c0-9ef4-11e8-8334-c345c7634510.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
How did you create the project?
Does this also happen if you do
```
flutter create my_project
cd my_project
flutter run
```
in a terminal window?

**Comment by warriorBrian** [comment]
I have found the reason for this problem, because the network problem causes the dependency to be downloaded. thanks

**Comment by zoechi** [comment]
Thanks for the update!
Sounds like this can be closed then.
