### ISSUE TITLE
Three finger screenshotting throws assert

### ISSUE THREAD

**Issue by taibaiyinxing** [flutter/flutter#20517]
Internal: b/143427192

On our released version of App, we were notified with an exception as the title show, the detail track infos are as follow:

NoSuchMethodError: The getter 'lastPosition' was called on null.

```
6 Receiver: null
7 Tried calling: lastPosition===>#0 PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:246)
8 #1 _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151)
9 #2 ListQueue.addAll (dart:collection/queue.dart:715)
10 #3 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:46)
11 #4 _rootRunUnary (dart:async/zone.dart:1136)
12 #5 _CustomZone.runUnary (dart:async/zone.dart:1029)
13 #6 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
14 #7 _invoke1 (dart:ui/hooks.dart:144)
15 #8 _dispatchPointerDataPacket (dart:ui/hooks.dart:99)
```

That's the full exception stack, from where I cannot get any info where my code got wrong because it's all about the framework layer, and I'm not very familiar with this layer.I did not found anything invoke the function _dispatchPointerDataPacket in hooks.dart from my code. 
This exception appeared only once by now.
Can we avoid this by checking if it's null before invoking lastPosition in converter.dart ?

**Comment by taibaiyinxing** [comment]
This exception appeared only once as our system shows.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by philipgiuliani** [comment]
I can reproduce this in a release build, when tapping anywhere with 3 fingers. It does not crash when tapping with 1 or 2 fingers.

```
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.14 18A391, locale de-DE)
    • Flutter version 0.10.0 at /Users/MyUserName/flutter
    • Framework revision d954ae6850 (2 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/MyUserName/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (3 available)
   --- Removed

• No issues found!
```

**Comment by philipgiuliani** [comment]
I even have more information. My phone has 3 finger screenshot gesture enabled. In debug mode the app does not crash, just in release mode.
I see the following message in debug mode though: `D/ViewRootImpl( 4960): Gesture Screenshot triggered, ignore event`.

**Comment by goderbauer** [comment]
Do you have a reliable way to reproduce this error? If so, can you post a minimal runnable code example that shows the error? That would help us tremendously in fixing this.

**Comment by Hixie** [comment]
My guess would be that some Android device is sending us bogus data (or at least data that we haven't thought to expect). Without knowing more about the device, steps to reproduce, or in general any more information, it's hard for us to do anything.

If you see this, please try to provide such information, as well as an up to date stack trace and the output of `flutter doctor -v`. Thanks.

**Comment by Hixie** [comment]
@goderbauer reports that Android claims to make no promises regarding their events, so we must make the engine robust to arbitrary sequences of input events, and try to convey coherent events to the framework.

**Comment by kongshanshan33** [comment]
I can reproduce this in a xiaomi 6X, when use the three-finger screenshot feature.

**Comment by xster** [comment]
Adding some additional paraphrasing from customers via WeChat:

The Xiaomi OS (?) has a 3 finger screenshot function. When using it on Flutter, it turns into one ACTION_DOWN and one ACTION_POINTER_DOWN in FlutterView. 

On the dart side, that's 2 down. Then there's an ACTION_CANCEL but its getPointerCount is 3. When that reaches dart, it becomes 3 cancels which doesn't match the 2 from before. 

So far, it's only reproducible on a Xiaomi 6X.

**Comment by xster** [comment]
Hopefully we can buy one but I also strongly suspect that the bundled OS for Xiaomi phones domestically and on international versions are different.

**Comment by philipgiuliani** [comment]
Oxygen OS also has the three finger screenshot gesture. As I mentioned above, I get the same crash on my OnePlus 5. I can also reproduce it on my friends OnePlus 5.

**Comment by goderbauer** [comment]
Here's the sequence of pointer events that Flutter is seeing when the user performs the three-finger screenshot gesture:

Pointer 1 down
Pointer 2 down
Cancel Pointer 1, 2, **and 3**

The problem is that we get a cancel event for the third finger even though we never were told to track it. The fix is going to be to filter those "illegal" events out.

**Comment by The-Redhat** [comment]
I can also reproduce this error on a oneplus 3 using the three-finger screenshot feature.

**Comment by Hixie** [comment]
(work is ongoing to fix this. we considered a quick hack, but decided a better fix would be to rearchitect the relevant code a bit, so it's taking a bit longer than it otherwise would.)

**Comment by cbracken** [comment]
@shihaohong @chunhtai any updates here?

**Comment by Hixie** [comment]
@chinmaygarde Sounds like you haven't had the chance to write the proposal you were talking about? What can we do to unblock this bug?

**Comment by tvolkert** [comment]
FYI, this bug was called out by a user in the Q2 user survey.

**Comment by chunhtai** [comment]
Given how critical this issue is, I suggest we should push out a short term fix first, which is fix in framework, so that can buy us some time to develop the long term solution. What do you think @goderbauer @Hixie ?

**Comment by tvolkert** [comment]
Short-term fixes are rarely short-term - we should just fix it properly.

**Comment by chunhtai** [comment]
sounds good

**Comment by Hixie** [comment]
This is still on our radar and considered critical, but unfortunately it is being held up by some even more critical work.

**Comment by mulderpf** [comment]
I just had to add that further to my earlier posts, I'm still seeing thousands of these events logged weekly.  It has no detrimental effect on my app, but it's a lot of noise I've had to filtered through for the last 7 months to find real issues.

**Comment by Hixie** [comment]
Just checked with @chinmaygarde and he confirmed the target milestone still looks plausible.

**Comment by sergicastellsague** [comment]
@Hixie one month after, could you give us an update regarding the milestone?

**Comment by Hixie** [comment]
Yup, @chinmaygarde is planning on looking at this in the next few days.

**Comment by sergicastellsague** [comment]
Thanks @Hixie. I've been wondering if there's a workaround we can implement on the Activity itself, or on the dart side. I've been trying to intercept all touches and allowing only 2 pointers max to pass to Flutter, but without luck so far.

**Comment by mulderpf** [comment]
How can we make this stop happening in the meantime?  It is actually costing me money as it is constantly flooding my Sentry.  What about the short term fix until this gets a priority?

**Comment by sergicastellsague** [comment]
@Hixie, we are close to the end of September... Did this bug receive any love so far?

**Comment by keitoro** [comment]
seems this is still not fixed. I have this issue on an iphone.

**Comment by keitoro** [comment]
> @mulderpf While waiting for the real fix you can hack this into your local copy of Flutter to avoid the problem for now: https://github.com/flutter/flutter/pull/28533/files#diff-c1dfac99ccc50aaadb3a3d5fbd299908

I have tried this, and I have still the same problem where you tap a gesturedetector and it needs another tap to fire off.

**Comment by cbracken** [comment]
I'm pushing this to the Oct milestone. We plan to get to this ASAP but I've asked @chinmaygarde to finish up work on a higher-priority issue first. We realise this is impacting customers, and this is definitely very much on our radar. Thanks for your patience.

**Comment by sergicastellsague** [comment]
@cbracken @chinmaygarde I wonder if there's any feasible workaround we can implement on our side or even an ugly fix would work for us.
Our top three crashes in reported in Fabric come from Flutter's core code, this being the first crash by a big difference.

**Comment by goderbauer** [comment]
@sergicastellsague I posted the workaround a couple of comments above: https://github.com/flutter/flutter/issues/20517#issuecomment-525861220

**Comment by sergicastellsague** [comment]
Thanks @goderbauer, however when I tried it, the code was not matching Flutter's code anymore, so it was not possible to simply apply the patch.

**Comment by sergicastellsague** [comment]
@shihaohong / @chunhtai do you see this happening in October 2019?
This is the top 1 crash in our flutter app (probably the top 2 too)
<img width="1413" alt="imatge" src="https://user-images.githubusercontent.com/5736310/67148193-fc1ba180-f29c-11e9-9b7a-194e631e3000.png">

**Comment by shihaohong** [comment]
Hi @sergicastellsague, I don't think this will be happening in October 2019. I just started looking at the issue and proposed solutions. @chunhtai will be back from vacation next week, so we will discuss what needs to get done when he returns.

**Comment by sergicastellsague** [comment]
@shihaohong I understand. But this issue is really a pain for our users. It's causing a lot of crashes, not only on Android but iOS as well. I guess my users are not taking screenshots constantly, it's just by normal usage of the app that they touch the screen with 3 fingers and experience this crash.

If the bugfix is not released, I'm more than willing to have a patch as a workaround, but I really need something to stop having them.
Do you have any quick and dirty way to prevent them?

Thanks a lot.

**Comment by shihaohong** [comment]
@sergicastellsague Could you elaborate on how the patch that @goderbauer suggested failed to work? Your version of Flutter would certainly become a fork of the original, and that comes with the drawback of having to keep in sync with the official version. That would probably be the only workaround for it for as far as I know.

**Comment by sergicastellsague** [comment]
In case somebody sees this crash and looks for a workaround, modify the file packages/flutter/lib/src/rendering/platform_view.dart 
and add
`if (downTimeMillis == null) return;`
in the handlePointerEvent method, right below this:
`if (event is PointerDownEvent) {
      if (nextPointerId == 0)
        downTimeMillis = event.timeStamp.inMilliseconds;
      pointerProperties[event.pointer] = propertiesFor(event, nextPointerId++);
    }`

**Comment by chenzongwen** [comment]
is there a better way to fix the problem.

**Comment by chenzongwen** [comment]
On ximi 8 Phone, after tapping Tencent map View with 3 fingers.  the map can not move with one or two fingers.

**Comment by flutterfrank** [comment]
I can't find the handlePointerEvent method anymore. Can somebody help me?

**Comment by chunhtai** [comment]
it got moved to the engine side, see 
engine/src/flutter/lib/ui/window/pointer_data_packet_converter.h
