### ISSUE TITLE
Atom Wish: help with browsing the Material Design icons, image assets

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2052]
AFAIK the current best practice for selecting a Material Design icon and adding it to an app is to stare at https://design.google.com/icons/ for a while, then identify an icon by combining the name of the section that it's in with its URL. For example the icon at `https://storage.googleapis.com/material-icons/external-assets/v4/icons/zip/ic_3d_rotation_black_24dp.zip` in the `Action` section is `action/3d_rotation`.

It would be helpful if Atom provided a custom MD icon browser with narrowed views (there are  lot of icons), sorting (there are a LOT of icons), searching (ditto), and of course identifying the icons by asset name. Interactive linking from a flutter.yaml entry to an icon would be nice too.

In the same way, it would be helpful if one could point Atom's image asset browser at a package that contained images, and multi-resolution sets of images.

**Comment by abarth** [comment]
I'm going to solve this with #994.  That will give us auto-complete for icons.

**Comment by abarth** [comment]
You can now browse the list of icons using autocomplete in Atom, but you still need to correlate with the web site to actually see the icon.  Ideally the atom auto complete would show you the icon as well as the name.

**Comment by HansMuller** [comment]
I think that - in addition - an Atom icon browser (an "Atomic" icon browser)  would also help with finding icons, for example by supporting narrowed views, like the "content type icons" or "icons look like this one", as well as just showing them all at once, just like the web page. The current Where's Waldo process of finding the icon you want is pretty tedious.

**Comment by Hixie** [comment]
The dartdocs now include the icons. If Atom shows the dartdocs, and if Atom applies the material design style sheet, it'll make the icons show up in the autocomplete widget in Atom.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
