### ISSUE TITLE
[firebase_database] DataSnapshot.forEach() feature request

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#20524]
Firebase Realtime Database client on Javascript has a great convenience method you can call on a `.once()` or `.onValue()` snapshot called forEach. It iterates through all snapshots and presents each one individually.

This feature is greatly missed in Flutter's `firebase_database` package. I find that breaking apart multiple DataSnapshots is verbose and you lose the static typing that would be so useful.

**Comment by alamboley** [comment]
Well, you can do (inside a `builder: (BuildContext context, AsyncSnapshot<DataSnapshot> snapshot) {`):
```dart
final value = snapshot.data.value as Map;
for (final key in value.keys) {
    Map<dynamic, dynamic> map = value[key];
}
```

**Comment by lukepighetti** [comment]
That only provides values, it doesn't provide individual snapshots, big difference.

**Comment by lukepighetti** [comment]
Truth be told, onValue stream should probably provide List<DataSnapshot>

**Comment by VyMajoris** [comment]
I would like to see this happening.

**Comment by zoechi** [comment]
@VyMajoris "me too" and "+1" comments are pointless. 
Instead use ![image](https://user-images.githubusercontent.com/405837/49718793-716d1d80-fc5b-11e8-8a7a-7288f578a66d.png) on the initial comment to upvote and increase priority.
Comments cause spammy notification mails sent to all subscribers.
If you want to get notified, use ![image](https://user-images.githubusercontent.com/405837/49718838-95306380-fc5b-11e8-8900-0d9173289cc8.png)

**Comment by kroikie** [comment]
@lukepighetti

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/711. Any further collaboration will be done there.
