### ISSUE TITLE
library not found for -limage_picker

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#20526]
Trying to use the image_picker plugin.
This is what I get from Xcode's Procuct -> Archive

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-RO)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.

**Comment by tudor07** [comment]
It was an issue on my side, no issue with the library.

**Comment by strokine** [comment]
@tudor07 how did you solve it? I have the same problem, and couldn't figure it out.

**Comment by tudor07** [comment]
@strokine I don't remember honestly but I think you have to open the workspace file (`Runner.xcworkspace`) in xcode, not the project file (`Runner.xcodeproj`)

**Comment by strokine** [comment]
I've tried the things you guys suggested, didn't help. I found helpful running:
```
rm -rf ~/Library/Developer/Xcode/DerivedData/
```
After that, I was able to build a release, but debug was still failing with the same message. But I did notice that `build/ios/Release-iphoneos` has the missing libs, and `build/ios/Debug-iphoneos` hasn't, so I just manually copy those folders from `release` to `debug` and that allowed me to run the debug mode for testing.
Hope this info helps. But if you'd find the solid solution, please let me know.
