### ISSUE TITLE
[Feature Request] VR Video (Fisheye to Panorama)

### ISSUE THREAD

**Issue by danielbls** [flutter/flutter#20527]
I can't seem to find any flutter plugins that allows someone to display 360 video.  I have fisheye videos I need to dewarp and allow panning around while it plays.  For web we are using videojs and videojs-panorama, which works great.  Is there a native flutter solution that can do the same thing?  I can play the raw video, but dewarping it and panning around is the hard part.  I know the videojs plugin copies the video to a canvas to achieve this, so I imagine something similar would have to be done for flutter.

Maybe there's a way to reuse some of the java-based vr video projects.

**Comment by Nico04** [comment]
Same request for static equirectangular panorama  👍

**Comment by stuartmorgan** [comment]
Given that this is relative niche functionality, it's not something we plan to build a first-party plugin for. This would certainly be a good opportunity for a third-party plugin.
