### ISSUE TITLE
Android Support Library Class Compiler Error "Cannot Resolve Symbol"

### ISSUE THREAD

**Issue by BasedMusa** [flutter/flutter#20535]
### Problem 
I'm writing an Android Wallpaper app in Flutter and when I call the Android Platform Code to set the wallpaper I need to show a Snackbar from the Platform Side (Not from the Flutter side). The Android Studio compiler cannot recognize Snackbar because it is part of the Android Support Library so I added the following line in `app/build.gradle`.

`    implementation 'com.android.support:support-v4:27.1.1'`

That didn't work so I tried it for specifically for the design library

`    implementation 'com.android.support:design:27.1.1'
`

That didn't work so I tried the 'Open for Editing in Android Studio' option, which opened up my app's android module in another window. There, Gradle Sync fixed the error, so the compiler recognized the Snackbar class, when I went back to my main app I could still see  the error. This is a nightmare.

I was previously having this issue when I was requesting some permissions and I needed to import ContextCompat and ActivityCompat. I was able to skip those by using a plugin called `simple_permissions`.

### Steps To Reproduce

Make a new Flutter app. Go to `MainActivity.java` and paste the following line somewhere.

`Snackbar.make(getFlutterView(), "Wallpaper Changed Successfully", Snackbar.LENGTH_LONG).show();`

The compiler will say `Cannot resolve symbol 'Snackbar'`. I have attached a screenshot as well.

![screenshot 110](https://user-images.githubusercontent.com/37034459/44052206-65bc34a2-9f55-11e8-9d50-2b9cc218523b.png)

**Comment by zozoh** [comment]
It's happend to me also

**Comment by AppleEducate** [comment]
This is happening to me with the share_extend plugin

**Comment by zoechi** [comment]
Sounds like https://flutter.io/docs/development/tools/android-studio#editing-android-code-in-android-studio-with-full-ide-support

**Comment by AppleEducate** [comment]
I ended up having to update all my plugins to support AndroidX

**Comment by BondarenkoStas** [comment]
@BasedMusa was your issue solved?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
