### ISSUE TITLE
Better clarity when running multiple emulators via `flutter run -d` and `flutter emulators --list`

### ISSUE THREAD

**Issue by seenickcode** [flutter/flutter#20532]
Dear wonderful Flutter team, 

For folks running 2 or more emulators at a time, it'd be useful to show that there is a `-d` flag available for the `flutter run` command. 

Though, if implemented, I do recommend then showing the emulator "device ID" when running `flutter emulators --list`, as one cannot use this `-d` flag with anything except the actual emulator device ID. I have to manually run `adb devices` in order get the device ID. As for iOS, I am not sure what the ideal behavior would be though or what is possible.

Thanks,

**Comment by zoechi** [comment]
@p30arena Please create a new issue with full details.

**Comment by zoechi** [comment]
@DanTup

**Comment by kangwang1988** [comment]
@seenickcode 
You don't need to run `adb command` manually.
Refer to flutter devices.
KyleWongdeMacBook-Pro:alibaba-flutter kylewong$ /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/bin/flutter devices
3 connected devices:

MHA AL00 • GWY7N14245                         • android-arm64 • Android 8.0.0 (API 26)
iPhone   • 1c8e085cf24bf4a077688af • ios           • iOS 12.1.2
MacOS    • MacOS                                    • darwin-x64    • Mac OS X 10.14.3 18D32a

Is this what you want"
With the printed device-id, you can use `flutter run -d` to run on certain device.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Syafix-dev** [comment]
vs code terminal command for running two emulators?

**Comment by DanTup** [comment]
@Syafix-dev there's info on running concurrently on multiple devices from VS Code here:

https://github.com/flutter/flutter/wiki/Multi-device-debugging-in-VS-Code

**Comment by muzaffar-omer** [comment]
I was also looking for away to find the `device-id`. I used the below commands:
1. `flutter emulators` (to list the available emulators)
2. `flutter emulator --launch <emulator_name>`
3. `flutter devices`

Not sure if this information is available somewhere in the documentation, but it might save some time to others.

Below is the output of the commands (using flutter version `2.1.0-12.2.pre`):

```
$ flutter emulators
2 available emulators:

apple_ios_simulator • iOS Simulator  • Apple  • ios
Pixel_3_API_30      • Pixel 3 API 30 • Google • android

To run an emulator, run 'flutter emulators --launch <emulator id>'.
To create a new emulator, run 'flutter emulators --create [--name xyz]'.

You can find more information on managing emulators at the links below:
  https://developer.android.com/studio/run/managing-avds
  https://developer.android.com/studio/command-line/avdmanager
$ flutter emulators --launch Pixel_3_API_30
$ flutter devices
2 connected devices:

sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
```
