### ISSUE TITLE
Flutter attach only works when the main file is called 'lib/main.dart'

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#20544]
```
$ cd path/to/flutter/examples/flutter_gallery
$ mv lib/main.dart lib/run.dart
$ flutter run lib/run.dart
<snip out waiting for the app to deploy and start.>
^C
$ flutter attach
<start the gallery app back up>
Your application could not be compiled, because its dependencies could not be established.
Could not read "path/to/flutter/examples/flutter_gallery/lib/main.dart" when determining Dart dependencies.
```

**Comment by DaveShuckerow** [comment]
The root cause is that the ResidentRunner we use to attach and do hot reloads with will try to find a main.dart file when a target isn't announced.  Attach doesn't provide a target, so it uses the default behavior always.

**Comment by DaveShuckerow** [comment]
Suggestion from @jacob314: 

> https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#isolate
> Isolate.rootLib should give you a good idea what the root library was. Can we use it to handle this case better?

**Comment by jonahwilliams** [comment]
I think this has since been fixed? https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/attach.dart#L267

Tentatively closing.
