### ISSUE TITLE
AppBar menu action flickering

### ISSUE THREAD

**Issue by codeZee** [flutter/flutter#20559]
I have a search icon on an app bar.

When the search icon is clicked, I update the app bar's view (using setState()) to show a TextField and also add a 'Cancel' icon action button to the right of the app bar - just as with a typical app bar search. 

However, once my app bar changes state to show the textfield and cancel icon button, the icon button flickers briefly (as though it was tapped on). Unsure what is causing this, but would love to gain insight. Hope it is a quick fix!

Note: This is happening on Android (Nexus 5 Android 6.0 physical device) and iOS (iPhone X simulator)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and if possible the minimal code that allows to reproduce.

**Comment by zoechi** [comment]
Did you test only in debug or also in release mode?
Debug mode has different performance characteristics.

**Comment by codeZee** [comment]
This occurs in debug and release builds.

AppBar code:
 ...
return new AppBar(
      actions:_isSearchExpanded ? _getSearchCancelButton() : _getMenuIconsForPage()
...



Icon widget for _getSearchCancelButton():
...
 List<Widget> _getSearchCancelButton() {
    return <Widget>[
      new IconButton(
        icon: new Icon(
          Icons.close,
          color: Colors.white,
        ),
        onPressed: () {
          _searchTextController.clear();
        },
      )
    ];
  }
...

**Comment by jonahwilliams** [comment]
@codeZee if you don't add the flutter doctor output we have no chance of helping you. You could have found a brand new bug that we need to fix or you could have hit an existing bug that was already fixed.

**Comment by codeZee** [comment]
```
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.8 at /Users/user/Documents/flutter
    • Framework revision e4b989bf3d (13 days ago), 2018-08-09 09:45:44 -0700
    • Engine revision 3777931801
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter


```

**Comment by codeZee** [comment]
See above results from `flutter doctor -v`

**Comment by goderbauer** [comment]
This will be easier to debug/reproduce if you post code that I can copy and paste and then just run instead of posting code snippets that need to be pieced together.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by codeZee** [comment]
@zoechi After some random tests, I have discovered what causes this. Basically, when you have menu action items change in size (i.e. say from three menu items to two) on a given toolbar, this flicker occurs. To stop the flickering, one needs to add an empty placeholder widget. See below:

AppBar Code:
`AppBar _getAppBar() {
    return new AppBar(
      actions:
          _isSearchExpanded ? _getSearchCancelButton() : _getMenuIconsForPage(),`

Search Cancel Button Menu Code (one menu item + dummy):
`List<Widget> _getSearchCancelButton() {
    return <Widget>[
      new Container(),  <---- dummy menu item, when removed causes flicker
      new IconButton(
        icon: new Icon(
          Icons.close,
          color: Colors.white,
        ),
        onPressed: () {
          _searchTextController.clear();
        },
      ),
    ];
  }`

Menu Icons For Page Code (notice 2 menu items):
`List<Widget> _getMenuIconsForPage() 
       List<Widget> widgetIconList = <Widget>[];
           switch (_page) {
             case 0:
               widgetIconList.add(searchToolbarIcon);
               widgetIconList.add(moreToolbarIcon);
               return widgetIconList;
........`

**Comment by iapicca** [comment]
Hi @codeZee 
are you still experiencing the issue with the latest stable or above?
If so can you please provide your updated `flutter doctor -v`, 
and a minimal **complete** reproducible code sample.

Thank you

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
