### ISSUE TITLE
fuchsia_tester --coverage sometimes produces empty coverage file

### ISSUE THREAD

**Issue by garymm** [flutter/flutter#20551]
Steps to reproduce:
1. Check out and build fuchsia, with layer set to topaz.
2. Run:
```out/x64/host_tests/lib_setui_module_test --coverage --coverage-path=/tmp/lib_setui_module_test.coverage```

This is a simple shell script which under the hood calls `fuchsia_tester`.

Expected result:
`/tmp/lib_setui_module_test.coverage` contains coverage data.

Actual result:
`/tmp/lib_setui_module_test.coverage` is an empty file.

Note that the empty coverage happens predictably but only for some tests.
For other tests it works as expected (e.g. https://fuchsia.googlesource.com/topaz/+/HEAD/app/dashboard/test/enums_test.dart)

CC @cbracken @tvolkert @nkoroste

**Comment by tvolkert** [comment]
Internal Fuchsia bug FL-93 may be related.

**Comment by garymm** [comment]
That internal bug is now fixed and I can still reproduce it:
`out/x64/dartlang/gen/topaz/lib/setui/common/lib_setui_common_test_test_conductor_builder_test_dart --coverage --coverage-path=/tmp/lib_setui_common_test_test_conductor_builder_test_dart.coverage`

**Comment by garymm** [comment]
@tvolkert any chance you could assign someone to look at this?

**Comment by tvolkert** [comment]
@jonahwilliams, this may make a good first task in Fuchsia once you start to ramp down on a11y

**Comment by jonahwilliams** [comment]
Running the above script with some debug prints added to fuchsia_tester shows that the additional command line arguments are not getting passed in properly:

```
[--packages=/usr/local/google/home/jonahwilliams/fuchsia/out/x64/dartlang/gen/topaz/lib/setui/module/lib_setui_module_test_library.packages, --shell=/usr/local/google/home/jonahwilliams/fuchsia/out/x64/host_x64/flutter_tester, --test-directory=/usr/local/google/home/jonahwilliams/fuchsia/topaz/lib/setui/module, --tests=/usr/local/google/home/jonahwilliams/fuchsia/out/x64/dartlang/gen/topaz/lib/setui/module/tests.json, --sdk-root=/usr/local/google/home/jonahwilliams/fuchsia/out/x64/dartlang/flutter_runner_patched_sdk, --icudtl=/usr/local/google/home/jonahwilliams/fuchsia/third_party/icu/common/icudtl.dat]
```

**Comment by jonahwilliams** [comment]
The initial bash script does not foward command line arguments - updating lib_setui_module_test to the following fixes the issue:

```
#!/bin/bash
  
/usr/local/google/home/jonahwilliams/fuchsia/out/x64/dartlang/gen/topaz/lib/setui/module/lib_setui_module_test "$@"
```

**Comment by jonahwilliams** [comment]
Fixing the above issue, coverage is still not generated. I believe the issue has to do with where we expect test/lib code to be (i.e.) we're filtering coverage incorrectly somewhere.

**Comment by jonahwilliams** [comment]
The issue is that we expected the passed test-directory to only contain the tests, while the fuchsia scripts pass the directory containing lib/ and test/. We have some logic in the coverage collector which takes the test directory's parent and appends a /lib to it to find the library for coverage. in this case, it results in a directory that doesn't exist - so no coverage gets generated.

```dart
    if (collector != null) {
      // collector expects currentDirectory to be the root of the dart
      // package (i.e. contains lib/ and test/ sub-dirs).
     // changes current directory from /topaz/lib/setui/module/ to /topaz/lib/setui/
      fs.currentDirectory = testDirectory.parent;
      if (!await collector.collectCoverageData(argResults[_kOptionCoveragePath]))
        throwToolExit('Failed to collect coverage data');
    }
```
And
```
    if (formatter == null) {
      final coverage.Resolver resolver = coverage.Resolver(packagesPath: PackageMap.globalPackagesPath);
      final String packagePath = fs.currentDirectory.path;
      // changes  directory to /topaz/lib/setui/lib which doesn't exist (shoudl be setui/module/lib)
      final List<String> reportOn = <String>[fs.path.join(packagePath, 'lib')];
      print('reporting on: $reportOn');
      formatter = coverage.LcovFormatter(resolver, reportOn: reportOn, basePath: packagePath);
    }
```

In the case of the setui_module_test, the test-directory is set to `--test-directory=/usr/local/google/home/jonahwilliams/fuchsia/topaz/lib/setui/module/`, but it should have a trailing `/test`. Add this to the script fixes the issue

**Comment by jonahwilliams** [comment]
@garymm this looks like an issue with how fuchsia is generating the test scripts

**Comment by garymm** [comment]
Thanks for looking into it @jonahwilliams.
I'm a little confused why it seems to work for some tests but not others. Maybe the directory structure of our dart code is not following the same convention everywhere?
Anyways, can you please fix the test script generation in the fuchsia code?
I touched that at some point but @tvolkert thoroughly rewrote it all and I think the Flutter team should own it.

**Comment by tvolkert** [comment]
https://fuchsia.googlesource.com/topaz/+/d07ea81/runtime/dart/dart_test.gni#16 sounds related -- some test rules are defined in a base directory off of which `lib` and `test` hang.  Others are defined in the same directory as the tests themselves.

It's not clear that the `source_dir` argument is providing any value.

**Comment by jonahwilliams** [comment]
I can confirm that removing the source_dir (currently set to ".") for the setui tests also fixes half the issue. There is also the problem  of the first bash script not forwarding arguments, still looking into why we're not generating the proper "$@"

**Comment by jonahwilliams** [comment]
It looks like there are several mod tests which use "." as a source directory so that they can directly include lib files as test sources. I think this is done so the test script doesn't depend on the flutter_aot_app rule?

**Comment by jonahwilliams** [comment]
I think we could probably handle this by adding a dart_library containing the shared sources. After we have an alternative for source_dir we should deprecate & remove

**Comment by jonahwilliams** [comment]
I have a partial cleanup of topaz pending here: https://fuchsia-review.googlesource.com/c/topaz/+/200367

There are several targets which will need refactoring first. I will update when I have a better idea of the needs of these targets for the source_dir property.

**Comment by jonahwilliams** [comment]
@garymm Do you know what rule is generating the first `out/x64/host_tests/lib_setui_module_test` script? It doesn't look like any of the dart scripts.

**Comment by garymm** [comment]
I think it's here:
https://fuchsia.googlesource.com/topaz/+/7b528d1fb059916de35d54aceeca8db6271155ec/runtime/dart/gen_test_bundle_invocation.py#76

Which is called by dart_test.gni

**Comment by garymm** [comment]
This is still an issue for some tests in topaz.
For example, flutter_widget_test.

    out/x64/host_x64/dart-tools/fuchsia_tester \
      --packages=out/x64/dartlang/gen/topaz/examples/test/flutter_widget_test/flutter_widget_test_library.packages \
      --shell=out/x64/host_x64/flutter_tester \
      --test-directory=topaz/examples/test/flutter_widget_test/test \
      --tests=out/x64/dartlang/gen/topaz/examples/test/flutter_widget_test/tests.json \
      --sdk-root=out/x64/dartlang/flutter_runner_patched_sdk \
      --icudtl=third_party/icu/common/icudtl.dat \
      --coverage \
      --coverage-path=/tmp/flutter_widget_test.coverage

**Comment by jonahwilliams** [comment]
Confirmed to be fixed at ToT
