### ISSUE TITLE
Add Flutter to existing apps - missing switch statement in main.dart

### ISSUE THREAD

**Issue by clearpath** [flutter/flutter#20567]
Page https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps says

> Above we use the string "route1" to tell the Dart code which widget to display in the Flutter view. The lib/main.dart file of the Flutter module project template contains a switch on the provided route string.

There is no such switch in `main.dart` file when module is generated.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1922](https://github.com/flutter/website/issues/1922) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Hixie** [comment]
Wiki page is gone now.
