### ISSUE TITLE
Get data with a condition

### ISSUE THREAD

**Issue by phuongdanh** [flutter/flutter#20565]
Hi, 
I am using this plugin to get data from firebase. 
How can i get data with a condition?
Thanks

**Comment by ebeem** [comment]
sorry, but I think your question is NOT clear at all ...
what plugin are you talking about? is it firebase?
and if it's the firebase .. then what is it that you want to achieve? `getting data with a condition` is so general.

good luck

**Comment by zoechi** [comment]
This issue doesn't contain enough information to be actionable.
Please create a new issue with more information or consider asking support questions on StackOverflow. Thanks!
