### ISSUE TITLE
Support making Apple watch apps

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2056]

**Comment by chinmaygarde** [comment]
Bitcode is mandatory for Apple Watch apps. We cannot support this because of the precompiler.

**Comment by Hixie** [comment]
Then we'll have to change how the recompiler works.

**Comment by Hixie** [comment]
(Eventually. There's a reason I put this in a post-1.0 milestone.)

**Comment by eseidelGoogle** [comment]
This is not currently on our near-term plan.  Iceboxing.

**Comment by pedia** [comment]
@chinmaygarde @Hixie  How can I make it work?

**Comment by eseidelGoogle** [comment]
This would require https://github.com/flutter/flutter/issues/15288.

**Comment by ventskus-roman** [comment]
As I think the bitcode support is implemented now, so the issue can be reopened?

**Comment by ProgrammingLife** [comment]
Strongly needed this feature

**Comment by sseeron** [comment]
anxiously waiting...

**Comment by istornz** [comment]
+1

**Comment by zeucxb** [comment]
+1

**Comment by elliotPopina** [comment]
+1

**Comment by everydayodyssey-kellancraddock** [comment]
Hi all. We would love to see WatchOS support added as soon as possible. We're currently vetting Flutter as a platform for our clients but that fact that it doesn't support WatchOS apps/extensions is a dealbreaker.

For others following this thread, here are the things we've tried so far:

1. Creating a new Flutter app with bitcode enabled in the Runner xcworkspace
- Successfully built and ran the app with the Flutter SDK via Android Studio
- Successfully built and ran the app via the Flutter CLI
2. Downloaded and compiled a local version of the Flutter engine with bitcode enabled. See [this post](https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app-(experimental)).
- Successfully built and ran the app with the locally compiled engine via the Flutter CLI
3. Added a Watch app/extension to the Runner xcworkspace
- Successfully built and ran the Runner target _from Xcode_ which properly installs the app with Watch extension in iOS
- **FAILED** to build and run the app with the Flutter CLI, locally built engine, and Android Studio. Any attempt to build the Flutter app results in this error which seems to be confirming the fact that Flutter currently doesn't support WatchOS apps/extensions.

```
MacBook-Pro-2018:flutter_bitcode_watch yourNameHere$ flutter run --local-engine=ios_profile -d MY-PHYSICAL-DEVICE-ID
 
Launching lib/main.dart on yourNameHere’s iPhone in debug mode...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: MYDEVELOPMENTTEAMID
Running Xcode build...                                                  
                                                   
Xcode build done.                                            2.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-12-02 19:27:37.075 xcodebuild[19582:27031970]  DTDeviceKit: deviceType from
    SOME-LONG-ID-HERE was NULL
    2019-12-02 19:27:37.230 xcodebuild[19582:27031908] [MT] DTDeviceKit: deviceType from
    SOME-LONG-ID-HERE was NULL
    2019-12-02 19:27:37.236 xcodebuild[19582:27031908] [MT] DTDeviceKit: deviceType from
    SOME-LONG-ID-HERE was NULL
    2019-12-02 19:27:37.242 xcodebuild[19582:27031908] [MT] DTDeviceKit: deviceType from
    SOME-LONG-ID-HERE was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    note: Using new build system
    note: Planning build
    note: Constructing build description
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphoneos' (in target
    'Flutter Bitcode Watch Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphoneos' (in target
    'Flutter Bitcode Watch Extension' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphoneos' (in target
    'Flutter Bitcode Watch' from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphoneos' (in target
    'Flutter Bitcode Watch' from project 'Runner')
    warning: duplicate output file '' on task: RegisterExecutionPolicyException
    /Users/yourNameHere/Documents/PATH/TO/PROJECT/flutter_bitcode_watch/build/ios/Debug-iphoneos
    (in target 'Flutter Bitcode Watch' from project 'Runner')
Could not build the precompiled application for the device.
Error launching application on yourNameHere’s iPhone.
```

Our experiments with this seem to conclude that bitcode support is currently working but we're missing WatchOS extension support. Is this assumption correct @dnfield @Hixie

**Comment by Hixie** [comment]
We (the current Flutter contributors) do not expect to add support for Apple Watch in 2020. We would accept patches from someone committed to providing full support (porting the engine, making the tool support the target well, providing suitable widgets, etc). This is an open source project. If you are interested in joining the team and owning this area, please don't hesitate to contact me directly (ian@hixie.ch, or Hixie on our [chat server](https://github.com/flutter/flutter/wiki/Chat)).

**Comment by kuprel** [comment]
I made a WearOS app no problem with Flutter: https://play.google.com/store/apps/details?id=io.kuprel.golf_score

What's the technical reason this app can't run on WatchOS too?  If its about having watch-friendly widgets, I was able to do just fine with what flutter already provides

**Comment by Henrik-glt** [comment]
@Hixie In my opinion there is no urgent need to support building Apple Watch apps with flutter.
To be able to build iOS apps using flutter and add an Apple Watch Extension is however much needed.
As of today building a flutter app fails just because an Apple Watch Extension is added.

```
Xcode's output:
↳
    note: Using new build system
    note: Planning build
    note: Constructing build description
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphoneos' (in target 'WatchApp Extension'
    from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.watchkit2-extension' for platform 'iphoneos' (in target 'WatchApp Extension'
    from project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphoneos' (in target 'WatchApp' from
    project 'Runner')
    error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphoneos' (in target 'WatchApp' from
    project 'Runner')
    warning: duplicate output file '' on task: RegisterExecutionPolicyException
    LOCATION/build/ios/Release-tst-iphoneos (in target 'WatchApp' from project 'Runner')
```

**Comment by Hixie** [comment]
That's a different issue, please file it as a new issue. Thanks.
