### ISSUE TITLE
colors added from a local theme, or created on the spot, should show inline preview in AndroidStudio

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#20572]
colors added from a local theme, or created on the spot, should show inline preview like the ones from Material do in AndroidStudio

**Comment by zoechi** [comment]
@devoncarew

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2553](https://github.com/flutter/flutter-intellij/issues/2553) via [**ZenHub**](https://www.zenhub.com/)
