### ISSUE TITLE
asset name in AndroidStudio should suggest auto-completions from assets configured in pubspec.yaml

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#20571]
1. When for instance creating an ``Image.asset()`` in AndroidStudio the assets name should suggest auto-completions from the assets already configured in pubspec.yaml.
2. On a second revision a preview of the asset should appear both inline and on the documentation tooltip.
3. On a third revision, it would be nice to have an option to add an asset from file (for when you forgot to add the asset you wanted to pubspec.yaml), which would automatically add it to a default assets folder, and also add it to pubspec.yaml, run a packages get, and finally auto-complete it.

**Comment by zoechi** [comment]
A first step could be a Dart file generated with string constants for each path. This way assets could be selected like icons with `Icons.sear...`.
I thought I saw a PR about that already a while ago but wasn't able to find it just now.

**Comment by zoechi** [comment]
Should this be in flutter/flutter-intellij ?

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2580](https://github.com/flutter/flutter-intellij/issues/2580) via [**ZenHub**](https://www.zenhub.com/)
