### ISSUE TITLE
Pubspec.yaml assets in AndroidStudio should suggest auto-completions

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#20570]
I expected the AndroidStudio flutter plugin to suggest auto-completions when adding an asset, from the asset files present in the flutter project. 
No matter what I expected, this is a really useful feature, to keep us from having to memorize the exact asset path/name, every time we add one.

**Comment by zoechi** [comment]
Is this not covered by #20571 already?

**Comment by d-silveira** [comment]
@zoechi this one is the other half of the coin, the other one is, while in code, suggestions from what's in the pubspec.yaml, in this issue I request that while filing the pubspec.yaml, suggestions appear from the files available in the project folders

**Comment by zoechi** [comment]
You are aware that you can use wildcards (glob) and don't need to list every asset individually anymore?

**Comment by d-silveira** [comment]
@zoechi I am not, can you point me to the doc page if you please?

**Comment by zoechi** [comment]
I only know about https://github.com/flutter/flutter/pull/16413
Seems it's not globs, but directory paths that get scanned for content.

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2581](https://github.com/flutter/flutter-intellij/issues/2581) via [**ZenHub**](https://www.zenhub.com/)
