### ISSUE TITLE
Drawer Open/Close callback

### ISSUE THREAD

**Issue by Jon-Salmon** [flutter/flutter#20581]
An application I'm working on requires being able to detect when a Drawer is opened and closed which currently is not possible. Is it possible to add a callback on this event?

My use case requires the underlying android app to know the status of the drawer and I've been unable to think up any work arounds so far. As far I can tell merge #20015 has already implemented most of the required code for this.

**Comment by zoechi** [comment]
#20856 seems to address that

**Comment by zoechi** [comment]
Looks like a dup of #14510

**Comment by Hixie** [comment]
Closing as duplicate.

**Comment by bikcrum** [comment]
This should be resolved by #67249
