### ISSUE TITLE
Increased height as a result of changes to materialTapTargetSize affecting AlertDialog/ButtonBar heights

### ISSUE THREAD

**Issue by estherhlee1** [flutter/flutter#20585]
Changes to the materialTapTargetSize have affected the margins on AlertDialog, since buttons now have added height.  If you see the pictures attached, after the materialTapTargetSize changes rolled out, our dialogs appear to have more padding on the bottom, and it no longer looks even with the side padding.  We are trying to match [Material Guidelines](https://material.io/design/components/dialogs.html#alert-dialog) regarding padding and overall height, but we also want to respect touch target sizes.  Is it possible for Alert Dialogs or Button Bars to take in more adjustable paddings, or for their paddings to accommodate the changes to buttons?  Are there other suggestions you have for how we can better accommodate this change?

The code was copied out of the [documentation for Alert Dialogs](https://docs.flutter.io/flutter/material/AlertDialog-class.html).

Before the updates to materialTapTargetSize
![before](https://user-images.githubusercontent.com/42388020/44112919-5721df12-9fbb-11e8-9ea9-40c8c2db3c17.png)

After the updates: The button bar is taller (moving from 52 to 64  in height, since the buttons went from 36 to 48), so the paddings all around don't look even anymore.
![after](https://user-images.githubusercontent.com/42388020/44112754-d5e814c0-9fba-11e8-86b4-269eff896f6e.png)

Thank you very much.

**Comment by jonahwilliams** [comment]
We've discussed this and decided we actually cannot shrink the button bar again without potentially breaking user code that relies on this height. 

Instead I'm going to add a configuration enum to the ButtonTheme which defaults to the old behavior. After an announcement process, or when we update the themes, we will switch the default to the correct behavior.  In the meantime users can opt into the flag by setting it in the button theme.

**Comment by rami-a** [comment]
I believe that #37544 will fix this since you will be able to set your own ButtonBarTheme to whatever you'd like.
