### ISSUE TITLE
Support making Apple TV apps

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2058]

**Comment by eseidelGoogle** [comment]
I don't see this on our near-term roadmap. Iceboxing for now.

**Comment by larryaasen** [comment]
Is this still on ice or is Apple TV and Android TV support being considered now?

**Comment by eseidelGoogle** [comment]
No current plan for AppleTV support.  I've definitely seen folks run Flutter Apps on Android TV however, but it's not something we're currently testing/investing in.

**Comment by ngocdaothanh** [comment]
Is this issue a duplicate of https://github.com/flutter/flutter/issues/15288?

**Comment by FullstackJack** [comment]
Would really love to build OTT apps for tvOS and Android TV with Flutter, please consider adding support for this soon.

Probably the most difficult aspect to adding support for TV devices is adding D-Pad remote support which requires spatial navigation of interactive widgets currently rendered to screen (includes AppBar). In addition, it would require scroll into view functionality for lists when navigating through list items. Perhaps a make-shift work around for now is handling key press events with hardcoded next focus widget, not 100% that would be possible.

**Comment by ott-web** [comment]
By the way, I've picked this item back up. I'm currently trying to get Flutter to build to tvOS so I have removed the guard rail platform support check in flutter_tool emulators.dart. so far I've built the xcodeproject to tvOS, but I still haven't been able to open the app. I'm now setting up my environment to compute the Flutter engine since we'll need to provide a new build target .framework for tvOS.

**Comment by tfabacher** [comment]
Any luck ott-web? We are looking to port tvOS to Flutter. We were able to wrap the Amazon FireTV very quickly. Now we need Apple TV.

**Comment by Tonku** [comment]
any update on this ?

**Comment by anticode-403** [comment]
Presumably supported as of 1.9.1

**Comment by FullstackJack** [comment]
Please point to your sources. I have been waiting for this for a while but
it appeared the team had no intentions to implement anytime soon.

**Comment by michaelwills** [comment]
Not yet I would think

https://github.com/flutter/flutter/blob/73c10e8ced9b2171378c5cb291f061cb1edc96bd/packages/flutter_tools/lib/src/ios/simulators.dart#L317

**Comment by criticaltv** [comment]
When WatchOS and tvOS?

**Comment by hpereira98** [comment]
Are there any efforts being made towards the compatibility of Flutter-based apps with tvOS (Apple TV)? I have the doubt if enabling Bitcode would be enough to launch an app for it.

**Comment by 106firestarter** [comment]
> When WatchOS and tvOS?
 
Bump!

**Comment by hkmsadek** [comment]
any luck on 2020?
