### ISSUE TITLE
File Provider for image_picker error

### ISSUE THREAD

**Issue by vibhav2799** [flutter/flutter#20587]
Error below:

> /Users/vibhavkotriwala/Desktop/work/4ceed_app/android/app/src/main/AndroidManifest.xml:14:13-74 Error:
Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.example.myapp.flutter.image_provider) from [:image_picker] AndroidManifest.xml:14:13-74
is also present at [:open_file] AndroidManifest.xml:12:13-64 value=(com.example.myapp.fileProvider).
Suggestion: add 'tools:replace="android:authorities"' to element at AndroidManifest.xml:12:9-20:20 to override.
/Users/vibhavkotriwala/Desktop/work/4ceed_app/android/app/src/main/AndroidManifest.xml:19:17-72 Error:
Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/flutter_image_picker_file_paths) from [:image_picker] AndroidManifest.xml:19:17-72
is also present at [:open_file] AndroidManifest.xml:17:17-50 value=(@xml/filepaths).
Suggestion: add 'tools:replace="android:resource"' to element at AndroidManifest.xml to override.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugManifest'.

**Comment by guangming21** [comment]
How to resolve
