### ISSUE TITLE
Firebase auth persistence across different apps

### ISSUE THREAD

**Issue by js1972** [flutter/flutter#20603]
We have a couple of flutter apps and use firebase custom auth sign in. 
The auth state is persisted across restarts and works offline which is great (unfortunately google sign in doesn’t do this).
What I’m wondering is if there is a way to persist this sign-in state across my different flutter apps. 

Ie. a user with 3 of my apps installed can log in on one and be automatically logged in with the other apps. Log out of one and you are logged out of all ??

Firebase auth must be storing the tokens in the device keychain (iOS) somewhere.

**Comment by zoechi** [comment]
Sounds like 

- https://medium.com/@anshuraguvansi/keychain-sharing-between-applications-on-ios-af1931468e26 (iOS)
- https://stackoverflow.com/questions/13047126/share-data-between-android-applications (Android)

**Comment by js1972** [comment]
Thanks @zoechi. I've also found within the Firebase doco that they mention you can accomplish this by pointing multiple apps to the same firebase project. I haven't test it yet but sounds promising... I think I'll close this for now - doesn't look to have interested too many people...

**Comment by zoechi** [comment]
> by pointing multiple apps to the same firebase project

Yup that sounds interesting.

**Comment by kroikie** [comment]
@js1972

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/708. Any further collaboration will be done there.
