### ISSUE TITLE
ListView inside a TabController disappears when the TextView is focused

### ISSUE THREAD

**Issue by hermantai** [flutter/flutter#20613]
```dart
@overrided
Widget build(BuildContext context) {
return new Scaffold(
  appBar: new AppBar(
    title: new Text(widget.title),
  ),
  body: new Column(
    children: <Widget>[
      new TextField(),
      new Expanded(
        child: DefaultTabController(
          length: 2,
          child: Scaffold(
            appBar: AppBar(
              title: TabBar(
                tabs: [
                  Tab(text: 'Info'),
                  Tab(text: 'News'),
                ],
              ),
            ),
            body: TabBarView(
              children: [
                ListView(
                  children: <Widget>[
                    ListTile(title: Text('row 1')),
                    ListTile(title: Text('row 2')),
                    ListTile(title: Text('row 3')),
                  ],
                ),
                Text("abc"),
              ],
            ),
          ),
        ),
      )
    ],
  ),
  floatingActionButton: new FloatingActionButton(
    onPressed: _incrementCounter,
    tooltip: 'Increment',
    child: new Icon(Icons.add),
  ), // This trailing comma makes auto-formatting nicer for build methods.
);
}
```

[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.1 at /Users/htai/dev/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

I posted a question in stackoverflow as well: https://stackoverflow.com/questions/51834172/listview-inside-a-tabcontroller-disappears-when-the-textview-is-focused

Look like it's a scaffold issue.

**Comment by zoechi** [comment]
The SO question has an accepted answer. I assume this is solved.
Please add a comment to reopen if you disagree.

**Comment by hermantai** [comment]
This is not solved. The answer is just an alternative to workaround the issue.

**Comment by TahaTesser** [comment]
Hi @hermantai 
Trying to reproduce this issue from code sample but listView doesn't disappear when textfield is focused
Are you still experiencing this issue with latest version of Flutter?
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
