### ISSUE TITLE
Issue from website page 国际化 Flutter 应用

### ISSUE THREAD

**Issue by darrennong** [flutter/flutter#20617]
From URL: http://localhost:4000/tutorials/internationalization/
$ pub run intl_translation:extract_to_arb --output-dir=lib/i10n lib/main.dart
Dart 2.0.0 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
I believe this is solved with beta 0.6.0
