### ISSUE TITLE
The `flutter_tester` binary should ensure the `platform_strong.dill` file exists

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#20626]
A recent rename of `platform.dill` to `platform_strong.dill` in https://github.com/flutter/engine/commit/a84b210b3d26513522d65060456517aee3335b20 has caused quite a bit of headache, because it crashed deeply inside the Dart VM.

The `flutter_tester` binary should ensure the `platform_strong.dill` file exists and print an error if it doesn't exist.

**Comment by williamxhannah** [comment]
Hi Martin, any work around - my flutter project is now consistently failing with the following error:
flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/platform_strong.dill': No such file or
directory

**Comment by mkustermann** [comment]
@williamxhannah You could try removing the folder and let flutter re-download the artifacts. In my checkout this file exists.

**Comment by darshankawar** [comment]
@mkustermann Is this still a valid issue ?
If so, can you provide `flutter doctor -v` and minimal complete code sample that shows the issue ?
Thanks.

**Comment by mkustermann** [comment]
Haven't encountered this before. Let's close it.
