### ISSUE TITLE
 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.

### ISSUE THREAD

**Issue by git-xuhao** [flutter/flutter#20621]
## Logs

```
E/flutter (26516): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26516): 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 96 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
E/flutter (26516): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
E/flutter (26516): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
E/flutter (26516): #2      PageController.page (package:flutter/src/widgets/page_view.dart)
E/flutter (26516): #3      BannerGalleryWidget._resetTimer.<anonymous closure> (package:flutter_wanandroid/widgets/banner/banner_widget.dart:123:29)
E/flutter (26516): #4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (26516): #5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (26516): #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
I/FlutterActivityDelegate(26516): onResume setting current activity to this
E/BpSurfaceComposerClient(26516): Failed to transact (-1)
E/BpSurfaceComposerClient(26516): Failed to transact (-1)
I/flutter (26516): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY 
```

**Comment by ThinkDigitalRepair** [comment]
I solved this by checking to see if the widget was mounted first before running the process I was running. It was a PageView widget

**Comment by jacksun0124** [comment]
@ThinkDigitalRepair How did you solve this?

**Comment by zoechi** [comment]
Is this still an issue?
Can you please provide a minimal reproduction?

**Comment by XardoniK** [comment]
When I click on Tab() error has trown like in @git-xuhao log. It's not crash app.
Code:

```
TabController _tabController;

@override
void initState() {
  super.initState();
  _tabController = new TabController(vsync: this, length: 5);
}

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(PROGRAM_SCREEN),
      ),
      body: Container(
        child: Column(
          children: <Widget>[
            TabBar(
              controller: _tabController,
              labelColor: Colors.red,
              tabs: [
                Tab(child: Text('TEst'),),
                Tab(child: Text('TEst'),),
                Tab(child: Text('TEst'),),
                Tab(child: Text('TEst'),),
                Tab(child: Text('TEst'),),
              ],
            ),
            Expanded(
              flex: 1,
              child: TabBarView(
                controller: _tabController,
                children: [
                  Text('TEst'),
                  Text('TEst'),
                  Text('TEst'),
                  Text('TEst'),
                  Text('TEst'),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
```

[√] Flutter (Channel unknown, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale pl-PL)
    • Flutter version 0.7.3 at C:\flutter_sdk
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\karol\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\karol\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 5.0.2 (API 21) (emulator)

**Comment by rubensdemelo** [comment]
+1

**Comment by ssatz** [comment]
How you guys solved? I am also getting this error

**Comment by ssatz** [comment]
I have solved using hasclient property to check page view is build/attached. Here is the link 
https://docs.flutter.io/flutter/widgets/PageController/page.html

**Comment by SteveAlexander** [comment]
This reproduces it for me:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey globalKeyA = GlobalKey(debugLabel: 'A');
  GlobalKey globalKeyB = GlobalKey(debugLabel: 'B');

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: TabBarView(
            children: [
              Text('Page A', key: globalKeyA),
              Text('Page B', key: globalKeyB)
            ]
          ),
          bottomNavigationBar: TabBar(
            labelColor: Colors.black,
            tabs: [
              Tab(text: 'A'),
              Tab(text: 'B')
            ]
          ),
        )
      )
    );
  }
}
```

Switch between the tabs a couple of times, and I get the following error:

```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
'package:flutter/src/widgets/page_view.dart': Failed assertion: line 96 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PageController.page (package:flutter/src/widgets/page_view.dart:96:7)
#3      _TabBarViewState._warpToCurrentIndex (package:flutter/src/material/tabs.dart:1126:25)
<asynchronous suspension>
#4      _TabBarViewState._handleTabControllerAnimationTick (package:flutter/src/material/tabs.dart:1118:7)
#5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:124:19)
#6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:697:5)
#7      Ticker._tick (package:flutter/s<…>
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.11.10-pre.2, on Mac OS X 10.13.6 17G3025, locale
    en-GB)
    • Flutter version 0.11.10-pre.2 at /Users/steve/code/flutter
    • Framework revision b55e52c6f7 (18 hours ago), 2018-11-21 15:48:23 -0500
    • Engine revision 1e37b99ac0
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • iPhone 6S • be56ff15c51ddf97c91ce2cf717f8bdb4549487e • ios • iOS 12.1
    • iPhone XR • 1EE1625B-61BB-421E-B104-CB3C8A5B6076     • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by psyanite** [comment]
I'm trying to find a workaround for this. 

I'm trying to do something like this: https://github.com/jlouage/flutter-carousel-pro/blob/master/lib/src/carousel_pro.dart

jlouage builds a image gallery carousel, and passes the controller down to `DotsIndicator`

Problem is when I try to render `DotsIndicator` at the top of the page before the images, it throws the error. Because I'm trying to get `pageController.page` in `DotsIndicator` despite the null check.

**Comment by psyanite** [comment]
@papakay try share your code and I'll try have a look?

**Comment by zoechi** [comment]
Lots of comments but no thumbs-up on the initial comment

Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by ArtificialPenguins** [comment]
i'm getting this. is there a workaround?

**Comment by psyanite** [comment]
If anyone wanted to read my comment further up I actually fixed it https://github.com/flutter/flutter/issues/20621#issuecomment-445504085

**Comment by sjschnuggsr** [comment]
psyanite I read your comment and I'm glad for you but need some help with where to add your code. I need to get out of a list and back into the parent PageView in a PageView with dots indicator. 

import 'dart:math';
import 'package:flutter/material.dart';


/// An indicator showing the currently selected page of a PageController
class DotsIndicator extends AnimatedWidget {
  static const double _kDotSize = 8.0;

  static const double _kMaxZoom = 2.0;

  static const double _kDotSpacing = 25.0;

  /// The PageController that this DotsIndicator is representing.
   final PageController controller;

  /// The number of items managed by the PageController
  final int itemCount;
  // The base size of the dots
  /// Called when a dot is tapped
  final ValueChanged<int> onPageSelected;

  // The increase in the size of the selected dot
  /// The color of the dots.
  ///
  /// Defaults to `Colors.white`.
final Color color;

  // The distance between the center of each dot
  DotsIndicator({
    this.controller,
    this.itemCount,
    this.onPageSelected,
    this.color: Colors.white,
  }) : super(listenable: controller);



  Widget build(BuildContext context) {
    return new Padding(padding: EdgeInsets.only(bottom: 12.0),
    child: Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: new List<Widget>.generate(itemCount, _buildDot),
    ));
     }

  Widget _buildDot(int index) {
   double selectedness = Curves.easeOut.transform(
      max(
        0.0,
        1.0 - ((controller.page ?? controller.initialPage) - index).abs(),
      ),
    );
    double zoom = 1.0 + (_kMaxZoom - 1.0) * selectedness;
    return new Container(
      width: _kDotSpacing,
      child: new Center(
        child: new Material(
          color: color,
          type: MaterialType.circle,
          child: new Container(
            width: _kDotSize * zoom,
            height: _kDotSize * zoom,
            child: new InkWell(
              onTap: () => onPageSelected(index),
            ),
          ),
        ),
      ),
    );
  }
}

class HailMary extends StatefulWidget {
  @override
  HailMaryState createState() {
    return new HailMaryState();
  }
}

class HailMaryState extends State<HailMary> {

  static const _kDuration = const Duration(milliseconds: 300);

  static const _kCurve = Curves.ease;
  static final _controller = new PageController();
  static final _hailMary = Padding(
      padding: EdgeInsets.only(top: 260, left: 4, right: 4),
      child: RichText(...
        

  static final _hailMaryFirstPage = GestureDetector(
    onHorizontalDragEnd: _onHorizontalDragFirstPage,



  child: Padding(
      padding: EdgeInsets.only(top: 260, left: 4, right: 4),
      child: RichText(...



  static final _hailMaryLastPage = GestureDetector(
      onHorizontalDragEnd: _onHorizontalDragLastPage,



      child: Padding(
          padding: EdgeInsets.only(top: 260, left: 4, right: 4),
          child: RichText(  ...


  final _kArrowColor = Colors.black.withOpacity(0.8);

  final List<Widget> _pages = <Widget>[

    _hailMaryFirstPage,
    _hailMary,
    _hailMaryLastPage,

  ];

  @override
  Widget build(BuildContext context) {
    return  new Stack(
    children: <Widget>[
    new PageView.builder(
      itemCount:_pages.length,
    physics: PageScrollPhysics(),
    controller: _controller,
    itemBuilder: (BuildContext context, int index) {
    return _pages[index % _pages.length];
    },
    ),





    new Positioned(
    bottom: 0.0,
    left: 0.0,
    right: 0.0,
    child: new Container(
    color: Colors.grey[800].withOpacity(0.5),
    padding: const EdgeInsets.all(20.0),
    child: new Center(
    child: new DotsIndicator(
    controller: _controller,
    itemCount: _pages.length,
    onPageSelected: (int page) {
    _controller.animateToPage(
    page,
    duration: _kDuration,
    curve: _kCurve,
    );
    },
    ),
    )))]);
}

  static void _onHorizontalDragFirstPage(DragEndDetails details) {
    if (details.primaryVelocity == 0.0)
      return; // user have just tapped on screen (no dragging)
    if (details.primaryVelocity.compareTo(0) == 1.0)
      SorrowfulMysteriesState()._controller.previousPage(
          duration: Duration(milliseconds: 150), curve: Curves.fastOutSlowIn);
    if (details.primaryVelocity.compareTo(0) == -1.0)
      _controller.nextPage(
          duration: Duration(milliseconds: 150), curve: Curves.fastOutSlowIn);
  }

  static void _onHorizontalDragLastPage(DragEndDetails details) {
    if (details.primaryVelocity == 0.0)
      return; // user have just tapped on screen (no dragging)
    if (details.primaryVelocity.compareTo(0) == -1)
      SorrowfulMysteriesState()._controller.nextPage(
          duration: Duration(milliseconds: 150), curve: Curves.fastOutSlowIn);
    else
      _controller.previousPage(
          duration: Duration(milliseconds: 150), curve: Curves.fastOutSlowIn);
  }}

**Comment by psyanite** [comment]
On which line does it throw an error?

**Comment by sjschnuggsr** [comment]
I'm changing blocks of code around all the time so I can't give you a line. Tried my parent/child PageViews without DotsIndicator and the associated code and got the error. 
Get the error with both PageView and List as the child with every gesture that would take you out of the child, either forward or back. Looks like it's attempting to escape any nested PageView or List inside a parent PageView that does it.

This fellow https://medium.com/flutter-community/flutter-deep-dive-gestures-c16203b3434f talks about using RawGestureDetector to detect the gesture in both the child and the parent.  Might try that.

**Comment by psyanite** [comment]
In that case your problem is probably different to mine. Could this be the cause? 

static final _hailMaryFirstPage = GestureDetector(
    onHorizontalDragEnd: _onHorizontalDragFirstPage,

because it could be defining DragEnd even though controller.nextpage is not yet present. 

Maybe you do need RawGestureDetector. Let us know when you fix it!

**Comment by Vitaly-V** [comment]
Guys, I had the same issue. I solved it by relaunching the emulator.

**Comment by shihaohong** [comment]
I cannot seem to reproduce the issue. Can someone try to create a consistent, reproducible sample? Otherwise, are there steps I need to take to trigger the error? I tried @XardoniK and @SteveAlexander's code samples and they do not throw the error.

**Comment by baylessj** [comment]
I'm also running into this issue. I've put together what I think is the minimal reproducible example of what's causing the error for me:

```
Widget Example extends StatelessWidget {
  static PageController testController = PageController();
  static List<Widget> testScreens = [
    Text('Example 1'),
    Text('Example 2'),
  ];
  Widget conditionalScreen(BuildContext context, PageController controller) {
    if (controller.page.toInt() == (testScreens.length - 1)) {
      return Container();
    } else {
      return Text('Hello!');
    }
  }

  static PageView testView =
      PageView(controller: testController, children: testScreens);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        testView,
        conditionalScreen(context, controller),
      ],
    );
  }
}
```

The above code causes the error in the title to appear. If I add the check for `hasClients` as described in this issue to the conditional line as such:

```
Widget conditionalScreen(BuildContext context, PageController controller) {
    if (controller.hasClients &&
        controller.page.toInt() == (testScreens.length - 1)) {
      return Container();
    } else {
      return Text('Hello!');
    }
  }
```
Then I do not get the error message but I also never have the body of the conditional execute. It seems like the issue stems from PageView not being considered a Client to the PageController, so `hasClients` never evaluates to true. My guess is that it would be possible to hack this functionality together with a dummy listener, but it would be nice if that did not have to be the case.

**Comment by shihaohong** [comment]
Hi @baylessj, could you create a new issue and share your comment there?

**Comment by baylessj** [comment]
@shihaohong Done, the issue is #38927 :+1:

**Comment by DenisBarzanov** [comment]
> I'm trying to find a workaround for this.
> 
> I'm trying to do something like this: https://github.com/jlouage/flutter-carousel-pro/blob/master/lib/src/carousel_pro.dart
> 
> jlouage builds a image gallery carousel, and passes the controller down to `DotsIndicator`
> 
> Problem is when I try to render `DotsIndicator` at the top of the page before the images, it throws the error. Because I'm trying to get `pageController.page` in `DotsIndicator` despite the null check.
> 
> I've fixed it as per @ssatz's suggestion to use `pageController.hasClients`:
> 
> ```
> bool isSelected = controller.hasClients ? controller.page == index : controller.initialPage == index;
> Color color = isSelected ? Colors.orange[200] : Colors.orange[100];
> ```

Is there a reason that `page` does not just return the `initialPage` if there is no `PageView` yet. Seems unnecessary
