### ISSUE TITLE
Firestore Hangs application when trying to fetch document that doesnt exist on iOS but fine on android

### ISSUE THREAD

**Issue by iamjavademon** [flutter/flutter#20623]
```dart
 var detailsRef =
        Firestore.instance.collection('users').document(firebaseUser.phoneNumber);//'08090000000');
    print('Before trans');
    Firestore.instance.runTransaction((transaction) async {
      DocumentSnapshot freshSnap = await transaction.get(detailsRef);
      print('done fetching record');
      if (freshSnap.exists) {
        //UserDetails userDetails = UserDetails();
        userDetails.fromJson(freshSnap.data);
      }
      setState(() {
        widgetState = WidgetState.DONE;
      });
      print('Done with firestore');
    });
```

From the above code, 'await transaction.get(detailsRef)' just hangs if the record doesnt exist on iOS.

**Comment by iamjavademon** [comment]
Ok, it was actually hanging on iOS only. I changed the way i fetch the record and things are fine now.

**Comment by blaneyneil** [comment]
it's still not properly handling the tx.get() though, correct?

**Comment by iamjavademon** [comment]
Well, i really don't know. I removed the code since i changed the way i get document.

**Comment by kroikie** [comment]
@iamjavademon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/706. Any further collaboration will be done there.
