### ISSUE TITLE
Google SignIn and Beacons Incompatibility 

### ISSUE THREAD

**Issue by lchinke** [flutter/flutter#20622]
Hi, 

i am using the plugins: `beacons: ^0.3.0` & `google_sign_in: ^3.0.4`.

Both are working fine in its way, but when I try to monitor/range a beacon after I've signed in through the GoogleSignIn() method, the ranging/monitoring method breaks with the following error (just tested in Android).
```
E/AndroidRuntime(26234): FATAL EXCEPTION: main
E/AndroidRuntime(26234): Process: com.anxaneta.motobeacon, PID: 26234
E/AndroidRuntime(26234): kotlin.KotlinNullPointerException
E/AndroidRuntime(26234): 	at io.intheloup.beacons.logic.PermissionClient.checkDeclaration(PermissionClient.kt:80)
E/AndroidRuntime(26234): 	at io.intheloup.beacons.logic.PermissionClient.check(PermissionClient.kt:49)
E/AndroidRuntime(26234): 	at io.intheloup.beacons.logic.PermissionClient.request(PermissionClient.kt:61)
E/AndroidRuntime(26234): 	at io.intheloup.beacons.logic.BeaconsClient$addRequest$1.doResume(BeaconsClient.kt:111)
E/AndroidRuntime(26234): 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
E/AndroidRuntime(26234): 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
E/AndroidRuntime(26234): 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
E/AndroidRuntime(26234): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(26234): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26234): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(26234): 	at android.app.ActivityThread.main(ActivityThread.java:6499)
E/AndroidRuntime(26234): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26234): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/AndroidRuntime(26234): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/Process (26234): Sending signal. PID: 26234 SIG: 9
Lost connection to device.
```
Any suggestion about this error?

**Comment by ram231** [comment]
[Beacon Issue](https://github.com/loup-v/beacons/issues/12)

I haven't tested the beacon yet, but it works in Google sign_in and other packages.
If I were to encouter it when deploying my beacon. I would make an issue in loup rather than in this repository.

**Comment by lchinke** [comment]
Well. I finally make it work. The error is caused because the google SignIn is destroying the activity related to the beacons. So, when PermissionClient.checkDeclaration() is trying to access the current activity, finds a null. (due to the unbind() method on onActivityDestroyed, in BeaconsPlugin.kt). 

So, what i did is comment the the lines 
//                beaconClient.unbind()
//                permissionClient.unbind()
in BeaconPlugin.kt

**Comment by ram231** [comment]
Glad it helped, I didn't touch the beacon at first because the author might have an update to that. I tried to PM him, can you make a PR on the official repository... the author used Altbeacon for Flutter. but if you have a product that supports SDK for both android and iOS. maybe you can do platform channel too.

**Comment by zoechi** [comment]
Can this issue be closed or is there still something to do for the Flutter team?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kroikie** [comment]
@lchinke

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/707. Any further collaboration will be done there.
