### ISSUE TITLE
Wiki: Obfuscation page issues

### ISSUE THREAD

**Issue by xqwzts** [flutter/flutter#20636]
The [Obfuscating Dart Code](https://github.com/flutter/flutter/wiki/Obfuscating-Dart-Code) page in the wiki has a few issues [we can't submit wiki PRs so putting them down here]:

1- Android/iOS headings are swapped:
  - The instructions to change `<ProjectRoot>/android/gradle.properties:` apply for android, and steps 1, 2, and 3 below that are for iOS.

2- The `Step 2` bit is unnecessary.
  - Instructions to commit changes to the git repo should not be needed here.
  - The second command is incomplete, `flutter` alone will simply bring up the command listing but won't actually do anything. I'm not sure if one of the flutter commands is necessary when changing `xcode_backend.sh` as is done in Step 1, perhaps that's what was intended with this step and has been cut out?

3- The last line refers to Android devices and should be moved up to the real Android section:
> For information on obfuscating the Android host, see Enabling Proguard in Preparing an Android App for Release.

**Comment by Sfshaza** [comment]
Thanks, @xqwzts!

I fixed issue #1 some time ago.
I don't know about #2 either, so I've left it for now.
For #3, I moved the last paragraph up.

**Comment by Sfshaza** [comment]
Fixed.
