### ISSUE TITLE
Flutter Permission denied for IOS 

### ISSUE THREAD

**Issue by mirmahfuz99** [flutter/flutter#20642]
How to open Flutter app on IOS Simulator ....I have seen below problem .
![screen shot 2018-08-16 at 12 45 31 am](https://user-images.githubusercontent.com/20367660/44166645-b6d66f80-a0ed-11e8-9698-c7fc3a0952d3.png)
![screen shot 2018-08-16 at 12 45 52 am](https://user-images.githubusercontent.com/20367660/44166659-bfc74100-a0ed-11e8-9515-8f91f29a7e3a.png)

**Comment by mirmahfuz99** [comment]
Solved : https://github.com/flutter/flutter/issues/19241

**Comment by mirmahfuz99** [comment]
Solved : #19241

**Comment by s2yed** [comment]
why Solved  error: expected identifier
        result([@"Not yet Implemented in iOS"]);
