### ISSUE TITLE
fatal error: "assert(!fRoundCaps)"

### ISSUE THREAD

**Issue by ameiyil** [flutter/flutter#20666]
Seeing this error on Fuchsia, but am unable to reproduce on the Android emulator with flutter run.
`skia/src/gpu/ops/GrOvalOpFactory.cpp:1400: fatal error: "assert(!fRoundCaps)"`

Caused by setting `new Paint()..strokeCap = StrokeCap.round`

Sample test code snippet:
```
import 'dart:math' as math;
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        body: new Container(
          width: 100.0,
          height: 100.0,
          child: new CustomPaint(
            painter: new _ProgressPainter(),
          ),
        ),
      ),
    );
  }
}

class _ProgressPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint()
      ..color = Colors.pink
      ..strokeWidth = 5.0
      ..strokeCap = StrokeCap.round
      ..style = PaintingStyle.stroke;
    canvas.drawArc(
      Offset.zero & size,
      math.pi * 1.5,
      0.5 * 2 * math.pi,
      false,
      paint,
    );
  }

  @override
  bool shouldRepaint(_ProgressPainter other) {
    return true;
  }
}
```

**Comment by chinmaygarde** [comment]
My initial hunch was that this was a non-fatal assertion that was compiled away in NDEBUG builds. However, I cannot reproduce the same in `--unoptimized` builds on the engine on the mobile shells. I also could not find the offending line in the Skia sources at the current Skia revision in `DEPS`. I will try to reproduce this on Fuchsia where this was initially reported.

**Comment by ameiyil** [comment]
Another weird thing to note is that this issue has always been fairly sporadic and not 100% consistent.

**Comment by chinmaygarde** [comment]
Update: Brining this up with the Skia folks during the sync.

**Comment by chinmaygarde** [comment]
This has been fixed and the offending assertion is not even present in the skia revision at the current ToT.
