### ISSUE TITLE
Publish wiki doc and Medium article for Add2App on iOS

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#20662]
Publish wiki doc and Medium article for Add2App on iOS

**Comment by cbracken** [comment]
@matthew-carroll is this still on the agenda? There are a [bunch](https://medium.com/flutter-community/add-flutter-to-existing-android-ios-app-ae8c4fb1582e) of [Medium](https://medium.com/@tpolansk/integrating-flutter-into-an-existing-app-part-one-flutter-with-submodules-9b633ff3cf10) [articles](https://medium.com/@tpolansk/flutter-integration-part-two-flutter-attach-4ab7198851bd) around add2app out there, but we probably do want a detailed page on adding Flutter to existing apps on our [docs page](https://flutter.dev/docs) sidebar.

Is there a separate bug for that? If not, should we re-purpose this bug for that?

**Comment by matthew-carroll** [comment]
Hi @cbracken - this may still be useful, but since I wouldn't be the person to orchestrate such a post, I'll tentatively close this and allow the appropriate dev or devrel to open a new ticket as desired.

As for the website, we have added a number of guides already, and I think we have additional tickets to add more.
