### ISSUE TITLE
Firebase auth causing dexmerger issue

### ISSUE THREAD

**Issue by ashkan117** [flutter/flutter#20669]
Kept on receiving Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

Whenever I try including the   firebase_auth: ^0.5.18 I get the DexMerger issue and I'm unsure why. There are no compile errors and simply commenting that single line out lets me download the app.

These sorts of issues have always been my kryptonite so I greatly appreciate any help and tips on how to debug these sorts of issues better in the future.

**Comment by FerdiHr** [comment]
You should add into your `app/build.grable` :
`android {
    ...
    defaultConfig {
        ...
       multiDexEnabled true  //new
    }
}`

**Comment by cyanglaz** [comment]
@ashkan117 Did @FerdiHr resolve your issue?

**Comment by ashkan117** [comment]
It's been a while and I couldn't seem to find my notes on the fix to this but off the top of my head I believe so.

**Comment by kroikie** [comment]
@ashkan117

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/703. Any further collaboration will be done there.
