### ISSUE TITLE
State in native activity lost when navigating away and back to app.

### ISSUE THREAD

**Issue by fyzs-n9001** [flutter/flutter#20675]
As long as current page is a Flutter page, the home button returns to the desktop, you can return from the launcher icon to the original page; but in the native Activity, then the state is lost, the return page is MainActivity

## Steps to Reproduce

1. In android native SecondActivity , press home key back to desktop
2. click launcher icon enter app , and the MainActivity shows
3. But in Flutter pages , i don't have this problem

## Logs

```
```

```
```

```
```

**Comment by goderbauer** [comment]
Is this a dup of https://github.com/flutter/flutter/issues/6827?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction project ideally shared on GitHub.

**Comment by zoechi** [comment]
Duplicate of #6827
