### ISSUE TITLE
Camera plugin issues on Android:  preview is distorted when using front camera.

### ISSUE THREAD

**Issue by zinwalin** [flutter/flutter#20674]
After one picture took, the final image is correct, the distortion issue only happen in camera preview.

Here's Flutter env I use:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.5.7, on Mac OS X 10.13.5 17F77, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by MichaelSowah** [comment]
could you attach a screenshot with the distortion you are talking about

**Comment by zoechi** [comment]
What device were you using?
Can you reproduce on a different device?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by janniklind** [comment]
I see the same issue on Samsung Galaxy XCover 4 - SM-G390F. And of course I have AspectRatio around CameraPreview. However this only seems to affect the CameraPreview widget size, the aspect ratio of the actual video is still off. Device resolution given by MediaQuery is 360x640.
The weird thing is that both the video captured from front and back is actually 4:3, so I have no idea, why it works for back camera when it doesn't for front camera.

On iOS the code is working just fine.

I have just updated Flutter, so I am running on newest version from master.

**Comment by zoechi** [comment]
@janniklind please create a new issue with full information. Adding a link to this issue would be helpful.
