### ISSUE TITLE
Issue from website page FAQ: The reason not to support mirrors is not limited to iOS

### ISSUE THREAD

**Issue by Cat-sushi** [flutter/flutter#20684]
From URL: https://flutter.io/faq/#does-flutter-come-with-a-reflectionmirrors-system
It says that "Because Flutter apps are pre-compiled for iOS", but nowadays, AFAIK, apps are AOT compiled even for Android.  So, It should be "Because Flutter apps are pre-compiled for production".

**Comment by Sfshaza** [comment]
Fixed in the dash branch. (We aren't fixing issues on master unless it's a P0.)
