### ISSUE TITLE
Improvements: Custom DropdownButton Icon

### ISSUE THREAD

**Issue by jogboms** [flutter/flutter#20686]
If it is not too much to ask, can we have an extra `IconData icon` parameter in the `DropdownButton` so we can have a custom icon for our own needs instead of the material down caret.

**Comment by MatthewJones517** [comment]
I agree... We definitely need this. I'm working with a designer right now who is less than pleased that we're stuck with the default material icon. Flutter has been amazing to work with so far, but this feature is desperately needed. 

If anyone knows of a work-around I'd appreciate it if you'd share.
