### ISSUE TITLE
Obscure error message for flutter run when ios/ directory missing

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2069]
My app doesn't have an iOS directory.  When I run my app, I get this obscure error message:

```
2016-02-20 23:00:47.058 defaults[7720:4714481] 
The domain/default pair of (/[redacted]/ios/Info, CFBundleIdentifier) does not exist
2016-02-20 23:00:47.114 defaults[7721:4714485] 
The domain/default pair of (/[redacted]/ios/Info, CFBundleIdentifier) does not exist
```

```
$ ../../third_party/flutter/bin/flutter --version
Flutter from https://github.com/flutter/flutter.git (on master)
flutter revision: 4ec960847219837d017dde64e41d849e176d4ebc (55 minutes ago)
engine revision : 6e736e7a76600640c5bd854c2fc9ed0f664ee26e

[-] The iOS toolchain is partially installed; more components are available.
[✓] The Android toolchain is fully installed.

Run "flutter doctor" for information about installing additional components.
```

/cc @chinmaygarde @devoncarew

**Comment by chinmaygarde** [comment]
`flutter create` should create the iOS directory for you now. Did you manually nuke this directory?

**Comment by abarth** [comment]
In my case, I'm working on an old app that never had an ios/ directory.  However, we should be robust to people nuking the ios (and android) directories if they don't care about ios (or android).

**Comment by chinmaygarde** [comment]
We can create a manifest of all files created by `flutter create` and check for their existence on run. Or at least add a `doctor` check.

**Comment by abarth** [comment]
I think the ideal behavior would be to just say nothing until I attempt to run the app on iOS.  At that point, the tool should tell me that my ios directory is missing or corrupt and offer to create one for me.

**Comment by danrubel** [comment]
`flutter run` with a connected Android device works fine even if I delete my `ios/` directory.
When an iOS device is connected, I get the message...
```
$ flutter run
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
```
Running `flutter create` fixes the problem.

**Comment by lichentao** [comment]
this problem is so long ,but flutter owner not see it ,
