### ISSUE TITLE
ReorderableListView steals focus from TextField making it impossible to type

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#20699]
## Steps to Reproduce

1. Create a ReorderableListView which has items that contain a TextField.
2. Click on the TextField
3. You will notice that the keyboard will not hold

## Doctor

[√] Flutter (Channel master, v0.5.9-pre.50, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.5.9-pre.50 at C:\Users\andre\flutter
    • Framework revision 58e52cc177 (21 hours ago), 2018-08-15 13:32:22 -0700
    • Engine revision e54bc4ea18
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\andre\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\android-studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • XT1058 • 0425187216 • android-arm • Android 5.1 (API 22)

• No issues found!

**Comment by AndreHaueisen** [comment]
I'm not sure what happened, but the issue stopped occurring after I restarted the system. Feel free to close this issue.  If it happens again, I will leave another message.

**Comment by zoechi** [comment]
This is usually caused by `TextEditingController` instances being recreated instead of being kept where they are not dropped and recreated.
