### ISSUE TITLE
how to set proxy for flutter application

### ISSUE THREAD

**Issue by MeshkaniMohammad** [flutter/flutter#20704]
Hi. I want to set a proxy for all of the connections of my app. how can I do this?
actually, I want to set proxy for firebase.

**Comment by zoechi** [comment]
Did you try to get an answer on StackOverflow?

**Comment by MeshkaniMohammad** [comment]
my account is blocked in stackoverflow and i can't find a way for my problem in stackoverflow!

**Comment by zoechi** [comment]
Probably related to #20376

**Comment by zoechi** [comment]
Duplicate of #26359
