### ISSUE TITLE
@Deprecated should take a message rather than an expiry time

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#20707]
It would be nice if `@Deprecated`'s argument was a message, rather than a deadline. Developers deprecated features would then be encouraged to describe the replacement in the message, e.g. `@Deprecated('Use the Bar.foo() constructor instead.')`.

The `@deprecated` annotation without a message should then probably itself be deprecated in favour of using `@Deprecated` with details.

**Comment by zoechi** [comment]
Seems to be a dup of dart-lang/sdk#34155 with a fix.

**Comment by Hixie** [comment]
Awesome.
