### ISSUE TITLE
plugin: camera - crashes on iOS < 10

### ISSUE THREAD

**Issue by hariprasadiit** [flutter/flutter#20708]
## Steps to Reproduce
Run Camera example on device with `iOS 9.x.x`

## Logs

```
Analyzing example...
No issues found! (ran in 2.6s)

```

```
[✓] Flutter (Channel dev, v0.5.8, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.5.8 at /Users/hari/development/flutter
    • Framework revision e4b989bf3d (7 days ago), 2018-08-09 09:45:44 -0700
    • Engine revision 3777931801
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

\iproxy not found. To work with iOS devices, please install ideviceinstaller. To install, run:
brew install ideviceinstaller.
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPad • 4474fd3c94589784543185ceefc47173d59e2b5f • ios • iOS 9.3.5

• No issues found!

```

**Comment by hariprasadiit** [comment]
this crash is due to not handling some of the new `api`s only available on `iOS 10.x`. 
ex. `AVCaptureDeviceDiscoverySession`

**Comment by cyanglaz** [comment]
cc @bparrishMines @mklim

**Comment by ShubhraDeshpande** [comment]
It still crashes for iOS 9 I am currently on camera: ^0.4.2, the app on iPad crashes as soon as camera is opened. was it resolved already?

**Comment by bparrishMines** [comment]
I added this to https://github.com/flutter/flutter/issues/31225. It explains to why the crash exists for iOS <10.0. We are currently working on a refactor that should fix this.

**Comment by Baileypollard** [comment]
@bparrishMines This is stopping us from releasing, any update on how this is going?

**Comment by jmagman** [comment]
See clang analyzer warnings:
https://github.com/flutter/flutter/issues/42673.

When the availability gets fixed, please remove camera from the list of plugins that are skipped by the CI analyzer:
https://github.com/flutter/plugins/blob/master/script/lint_darwin_plugins.sh#L23

**Comment by bparrishMines** [comment]
Hi @Baileypollard,

We prioritize community issues by thumbs up, but we also accept PRs. The crash for < 10.0 is briefly explained in https://github.com/flutter/flutter/issues/31225 section **Support iOS Camera 8.0+** if you would like to take a crack at it.

The plugin also doesn't support < 21 on Android. Unfortunately we don't have anyone that can work on it as of this moment. The milestone right now is still the end of the year.

**Comment by andesappal** [comment]
https://github.com/flutter/flutter/issues/52020

**Comment by andesappal** [comment]
AVFoundation issue https://gist.github.com/andesappal/ececc77518c47d7eab1e2e05e33d7e57

**Comment by dnfield** [comment]
This will be fixed by https://github.com/flutter/plugins/pull/2928, but unfortunately much of the functionality of the camera plugin doesn't work on < iOS 10. See #31225 for that.

**Comment by dnfield** [comment]
(Camera version 0.5.8+5 fixed this)
