### ISSUE TITLE
Figure out a better story for iOS applications that can't derive from `FlutterAppDelegate`

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#20709]
Adding Flutter to existing iOS applications involves either deriving from `FlutterAppDelegate` or manually implementing a lot of boilerplate.  I expect that some existing iOS applications already derive from a custom `UIApplicationDelegate` and that for them, this requirement is a pain point and introduces some brittleness.

We should investigate ways to improve this situation.  Some possible avenues to look into are using `forwardInvocation:` for Objective-C, protocol extensions for Swift, or perhaps dynamically swizzling in the necessary methods (as described by #9984).

**Comment by xster** [comment]
I'm gonna straight up come out to say that we shouldn't try to get users' AppDelegates to be like FlutterAppDelegates at all if we can. Merging into #32995
