### ISSUE TITLE
Bug: Xcode 10 new build system

### ISSUE THREAD

**Issue by gi097** [flutter/flutter#20710]
Reference: #20685 
## Description
Xcode 10 is using a new build system, which is currently not supported by Flutter.

## Steps to reproduce
1. Install Xcode 10 beta, use default settings
2. Create/open Flutter application on Android Studio
3. Build for iOS

## Logs
```
Multiple commands produce '/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework
```

## Fix
The only workaround for this is to force Xcode to use the `Legacy Build System`. Open the workspace project in Xcode and navigate to `File`, `Workspace Settings`, and select `Legacy Build System`.

![44207656-5fbcb300-a15e-11e8-8d08-0b88f006ec4a](https://user-images.githubusercontent.com/18169417/44234356-afbf6800-a1a6-11e8-92d2-4542fc3d21c7.png)

**Comment by zoechi** [comment]
Is this not the same issue as #20685?
