### ISSUE TITLE
Build the engine with the latest Android SDK

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#20717]
Currently the Flutter engine is build with Android SDK 22.
We should upgrade to build with the latest SDK.

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/flutter/issues/17780 for more background on why this is hard (but I agree)

**Comment by amirh** [comment]
Like you this forced me to use reflection in flutter/engine#6043

**Comment by cbracken** [comment]
@goderbauer did you bump this when you did the NDK bump?

**Comment by goderbauer** [comment]
I bumped the NDK, which is totally separate from the SDK. The SDK still needs a bump, which probably requires more work due to the issue @jonahwilliams linked to.

**Comment by cbracken** [comment]
@jason-simmons will be taking on #17780.

**Comment by dnfield** [comment]
See https://github.com/flutter/buildroot/pull/194 which would fix this but needs a review.
