### ISSUE TITLE
"flutter packages get" error : The current Flutter SDK version is 0.0.0-unknown.

### ISSUE THREAD

**Issue by southpeak** [flutter/flutter#20727]
I upgraded my flutter and there are something wrong with my project: the third libraries can not be found. So I run "flutter packages get",  and the result is: 

```
Running "flutter packages get" in XXX...
The current Flutter SDK version is 0.0.0-unknown.

Because XXX depends on shared_preferences >=0.4.0 which requires Flutter SDK version >=0.1.4 <2.0.0, version solving failed.

pub get failed (1)
```

Then I run "flutter doctor -v", and the result is : 

```
[✓] Flutter (Channel master, v0.0.0-unknown, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.0.0-unknown at ***
    • Framework revision 2239344597 (17 hours ago), 2018-08-16 16:31:34 +0800
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at ***
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

Why the flutter version is  "v0.0.0-unknown"?

**Comment by southpeak** [comment]
Well, it's my fault. I duplicate the flutter project and push to my github, and then cover the official version with my version. So when I run "flutter upgrade", it will upgrade the flutter from my git address, but not the official address.

**Comment by braysonjohn148** [comment]
i have the same issue. How can i slove it..?

**Comment by braysonjohn148** [comment]
> 
> 
> Well, it's my fault. I duplicate the flutter project and push to my github, and then cover the official version with my version. So when I run "flutter upgrade", it will upgrade the flutter from my git address, but not the official address.



> 
> 
> Well, it's my fault. I duplicate the flutter project and push to my github, and then cover the official version with my version. So when I run "flutter upgrade", it will upgrade the flutter from my git address, but not the official address.

i have the same issue. How can i slove it..?

**Comment by Luis-Lobo** [comment]
Hi, braysonjohn148 .
I had the same problem and I fixed it by reinstalling flutter.
