### ISSUE TITLE
How to resolve test library conflicts?

### ISSUE THREAD

**Issue by dyftxpro** [flutter/flutter#20731]
Because every version of flutter_test from sdk depends on crypto 2.0.3 and myapp depends on crypto ^2.0.5, flutter_test from sdk is forbidden.
So, because myapp depends on flutter_test any from sdk, version solving failed.
pub get failed (1)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by YAPPDEF** [comment]
Same issue for me. Tried to add flutter_udid
>flutter_udid: ^0.0.3

```
dependencies:
  flutter:
    sdk: flutter

  flutter_udid: ^0.0.3
```

```
Because every version of flutter_test from sdk depends on crypto 2.0.3 and flutter_udid >=0.0.2 depends on crypto ^2.0.6, flutter_test from sdk is incompatible with flutter_udid >=0.0.2.
So, because yapp depends on both flutter_udid ^0.0.3 and flutter_test any from sdk, version solving failed.
```

**Comment by zoechi** [comment]
In `pubpsec.yaml` add
```yaml
dependency_overrides:
  crypto: ^2.0.6
```

**Comment by YAPPDEF** [comment]
Thanks @zoechi, worked for me!
