### ISSUE TITLE
How to store API Keys In Flutter following best practices.

### ISSUE THREAD

**Issue by pmutua** [flutter/flutter#20735]
[How do I store my API keys in a flutter application if it's consuming an API from the web?. Following best practices.](https://stackoverflow.com/questions/51895194/correct-way-of-storing-api-keys-in-flutter-following-best-practises?noredirect=1#comment90741210_51895194)

**Comment by zoechi** [comment]
Might be a good example for #15297

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/flutter_secure_storage might help

**Comment by pmutua** [comment]
Thanks

**Comment by UnnikrishnanBhargavakurup** [comment]
Facing same issue here:

https://stackoverflow.com/questions/55663207/storing-api-credentials-in-a-flutter-application
