### ISSUE TITLE
Deploy existing SDK for flutter

### ISSUE THREAD

**Issue by MeshkaniMohammad** [flutter/flutter#20738]
Is this possible to deploy existing available SDK for flutter?
Actually, I have a SDK platform from a company like as firebase and I want to deploy it for flutter without writing again all of codes :).

**Comment by MeshkaniMohammad** [comment]
I want to deploy [this ](https://github.com/backtory/storage-java-sdk) SDK for flutter

**Comment by zoechi** [comment]
Create a plugin https://flutter.io/developing-packages/#plugin

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by MeshkaniMohammad** [comment]
Actually yes.

**Comment by zoechi** [comment]
I think this is what lots of plugins do. 
Probably better to ask on StackOverflow.
