### ISSUE TITLE
Support iterating over child nodes of DataSnapshot (in order)

### ISSUE THREAD

**Issue by puf** [flutter/flutter#20745]
I'm trying to implement a value listener that loops over the children of this node in order of timestamp:
```json
  {
    "child1": {
      "timestamp: 1534403793711
    },
    "child2": {
      "timestamp: 1534403771193
    },
    "child3": {
      "timestamp: 1534403747500
    }
  }
```
The tricky bit is that the values are not ascending: the correct order is `child3`, `child2`, `child1`.

I can do something like this:
```dart
var ref = FirebaseDatabase.instance.reference().child("/51808719");
ref.orderByChild("timestamp").once().then((snap) {
  print(snap.value);
});
```
But this prints:
```
flutter: {child2: {timestamp: 1534403771193}, child1: {timestamp: 1534403793711}, child3: {timestamp: 1534403747500}}
```
This makes sense since `snap.value` converts to a `Map` here, and the order of items in a map is undefined. Same as this:
```dart
      Map<dynamic,dynamic> map = snap.value;
      map.forEach((key, value) { print('$key: $value'); });
```
This is an age-old problem for developers on the realtime database: you should only extract the value from a snapshot when order no longer matters.

In JavaScript I'd do `snap.forEach` and in Android `for (DataSnapshot child: snap.getChildren())`, but I don't see a Flutter equivalent. 

How do I iterate the children of a `DataSnapshot` in the requested order?

---

The closest FlutterFire now supports is listening to `onChildAdded`, but this often leads to more complex code than a simpler `once()` listener.

**Comment by kroikie** [comment]
@puf

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/701. Any further collaboration will be done there.
