### ISSUE TITLE
https://flutter.io/ui-performance/#the-performance-overlay looks poor in mobile safari

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#20744]
Seems to look fine in the Chrome Inspector device simulator.

But on my phone:
![img_0516](https://user-images.githubusercontent.com/11857803/44282933-82f46a80-a211-11e8-9bd8-59ac6e06f8cf.png)
![img_0515](https://user-images.githubusercontent.com/11857803/44282934-84259780-a211-11e8-87eb-cb15da13030f.png)

I suspect this is a known issue with our site? FYI @mjohnsullivan

**Comment by Cat-sushi** [comment]
It looks poor in chrome on my phone, too.
![screenshot_20180819-143308](https://user-images.githubusercontent.com/10280770/44305864-05ba2880-a3be-11e8-89c6-f98ba3adc570.png)
![screenshot_20180819-144317](https://user-images.githubusercontent.com/10280770/44305869-5467c280-a3be-11e8-8934-877aaf1123c7.png)

**Comment by Sfshaza** [comment]
Yes, this is a known issue. We are currently working on a new implementation of the site. This is fixed in the new site. Closing this issue.
