### ISSUE TITLE
Slow animation

### ISSUE THREAD

**Issue by hummatli** [flutter/flutter#20753]
Hi, I'm trying the flutter gallary app in my Samsung Galaxy S4 and I see a very slow animation. What is this problem? How to solve this issue? 

By the way, I want to start to develop with the flutter api and with this issue it doesn't seem real.

How can I help to investigate and even solve this problem?

**Comment by hummatli** [comment]
Ok. I will try and write down the result.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
