### ISSUE TITLE
Atom cannot find Dart SDK location after Flutter plugin installed.

### ISSUE THREAD

**Issue by ahmetaa** [flutter/flutter#2075]
After installing Atom and Flutter Plugin, it cannot find the Dart SDK location and it is not clear from the documentation where Flutter installs it (To a cache directory?). Do Atom users need to install a separate Dart SDK? Whatever the case, Flutter or Plugin documentation should explain this.

### Steps to Reproduce
* Install Atom and Flutter plugin. it cannot find Dart SDK location

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on alpha)
flutter revision: 49c0ec3402a58b670d4eefb8ad500d330da59664 (4 days ago)
engine revision : 9e1e1fba5474b458458b65f1aa1d0d730af2705b
[✓] The Android toolchain is fully installed.
```

**Comment by devoncarew** [comment]
The first time the `flutter` tool is run, it downloads a copy of the dart sdk (currently 1.14.1) and puts it in $flutter_root/bin/cache/dart-sdk. The flutter tool will use this SDK when it runs.

Atom's behavior will change once the next version is published (in a day or two). It will try and auto-locate the dart sdk, and failing that, locate the flutter sdk and look for the contained sdk. Atom users shouldn't need to install a separate dart sdk, but can if they chose to. The auto-location behavior can be overridden by explicitly setting a dart sdk location in the `dartlang` plugin and a flutter_root location in the `flutter` plugin.

**Comment by eseidelGoogle** [comment]
We also have https://github.com/flutter/flutter/issues/1982 on file about flutter doctor helping make sure atom is set up correctly.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
