### ISSUE TITLE
Isolate termination should terminate all child isolates.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#20764]
Currently, any isolates spawned by the root isolate will stick around even if the root isolate kills itself or is terminated due to application termination or engine initiated restart events. This puts the onus on the root isolate to correctly clean up after itself before its death. This is [not always possible](https://github.com/flutter/flutter/issues/7160). The engine should keep track of and terminate all child isolates of the specific root isolate.

**Comment by chinmaygarde** [comment]
cc @Hixie. This is potentially a breaking change.

**Comment by Hixie** [comment]
We can mitigate the breaking aspect by making it optional, e.g. if there's an API that you call to shut down the root isolate, it could take a boolean saying what to do with child isolates.

**Comment by GaryQian** [comment]
I will start looking into this.

**Comment by chinmaygarde** [comment]
> I will start looking into this.

Cool. Let me know if you want to pair on this after you done with your initial investigation.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/6099

**Comment by GaryQian** [comment]
@chinmaygarde Has this been accomplished? Is this still relevant?

**Comment by chinmaygarde** [comment]
This has to be verified after the migration to isolate groups. =

**Comment by chinmaygarde** [comment]
Since this should now be done by the VM instead of the engine having to manually terminate all isolates, can you add a test to `runtime_unittests` to verify this?

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/13048 Adds a test to verify this.

**Comment by chinmaygarde** [comment]
Thanks!
