### ISSUE TITLE
Text Selection: Long press shows and moves cursor

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#20768]
Given an editable text field, when a user long presses in the text, a text cursor appears at the user's finger tip. Left/right movement moves the cursor left/right.

**Comment by saurik** [comment]
I think this might be the same issue as #20693, and sounds highly related to #9507?

**Comment by matthew-carroll** [comment]
It does appear to be related to #9507.  This ticket is probably an individual work item for #9507.  #20693 is tagged with "material design" so it looks like that ticket might be broader than this one.  But they are possibly the same.  In any event, this ticket is part of the "Text Entry in iOS Framework" project.

**Comment by xster** [comment]
Duping into #20693. It's tagged Cupertino and Material because the touch handling in general are handled above the Widgets layer.
