### ISSUE TITLE
comment_references lint doesn't support dartdoc's idea of "in scope"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#20765]
As of https://github.com/dart-lang/dartdoc/issues/1153, dartdoc considers pretty much everything it knows about to be in scope regardless of whether it's in scope at the Dart level. Unfortunately, the comment_references lint doesn't follow the same convention. So, for example, `packages/flutter/lib/painting.dart` in flutter's repo ends up flagging the three terms in the library docs (`[TextPainter]`, `[Decoration]`, etc) even though those are valid. This makes the lint unusable for our purposes, even though it actually catches a bunch of errors so we would love to use it.

**Comment by zoechi** [comment]
> the comment_references lint doesn't follow the same convention

Don't you think it should?

Do you plan to file an issue in https://github.com/dart-lang/linter/issues?

**Comment by Hixie** [comment]
Wow I totally filed that in the wrong repo, my bad.

**Comment by Hixie** [comment]
https://github.com/dart-lang/linter/issues/1142
