### ISSUE TITLE
Text Selection: Force touch turns word into draggable

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#20771]
Given an editable text field, if a user force touches the text without initially long pressing, the word beneath the users finger is elevated into a draggable and can be transposed to some other place on the screen (or some other place within the text field).

**Comment by mohith7548** [comment]
Can you show us a gif/images of it?

**Comment by matthew-carroll** [comment]
Sorry I haven't gotten around to this.  Yes I can post a GIF but it might take a couple weeks to get around to it.  Lots to do at the moment.

**Comment by darshankawar** [comment]
Hi @matthew-carroll,
Can you please confirm if you still experience this issue on latest stable or master ? Would be great if you could reply with current behavior.
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
