### ISSUE TITLE
Engine run configuration was invalid.

### ISSUE THREAD

**Issue by shivam340** [flutter/flutter#20777]
I am trying to integrate flutter module inside existing iOS and Android app. For the Android, it is working fine. I am following steps from https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps. But for iOS app When I try to push FlutterViewController I get the following error. 

## Logs
```
[VERBOSE-2:engine.cc(112)] Engine run configuration was invalid.
[VERBOSE-2:FlutterViewController.mm(411)] FlutterViewController.mm(411)] Could not launch engine with configuration.
```
Following is the code that I am using to push flutter view controller 

```
@IBAction func onClickButton(_ sender: Any) {
        print("Tapped on Button");
        let flutterViewController = FlutterViewController()
        navigationController?.pushViewController(flutterViewController, animated: false)
    }
```

an output of running `flutter doctor -v`

```
[✓] Flutter (Channel master, v0.5.9-pre.79, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.5.9-pre.79 at /Users/shivamgosavi/flutter
    • Framework revision 3a4ae280e3 (5 hours ago), 2018-08-17 15:02:39 -0700
    • Engine revision 4ee648914f
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/shivamgosavi/Library/Android/sdk
    • Android NDK at /Users/shivamgosavi/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/shivamgosavi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • iPhone 8 Plus • 0822DE18-6632-4F22-93F3-46770C82A247 • ios • iOS 11.4 (simulator)

• No issues found!
```

Please let me know If I am missing anything. And also please update the doc for integrating flutter into existing `swift` app, currently, the doc is only about ObjectiveC.

**Comment by shivam340** [comment]
Guys do you have any update on above issue, I am really stuck.

**Comment by imkerberos** [comment]
I have the same issue.

**Comment by matthew-carroll** [comment]
@jamesderlin Would you mind taking a quick look into this issue since you're currently working with the bindings?

**Comment by jamesderlin** [comment]
Are you encountering the same problem with the flutter/examples/flutter_view sample on iOS?

**Comment by jamesderlin** [comment]
FWIW, in my experience this error usually means that [`FlutterDartProject.mm`](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm) failed to find the Flutter assets with the various snapshot files.  There are a couple ways that it tries to find them, but the typical way is by looking for a `flutter_assets` directory in your application's bundle.  Does your XCode project include `flutters_assets`?

**Comment by imkerberos** [comment]
@jamesderlin You are right. My demo target lost the flutter_assets folder. After adding the flutter_assets to application bundle, the demo works fine. Thanks.

**Comment by shivam340** [comment]
<img width="261" alt="iosappfiles" src="https://user-images.githubusercontent.com/5505908/44450848-99cefe80-a60f-11e8-82c9-74ae855b69e7.png">

@jamesderlin, The `flutter_assets` directory is available. I am still having the same issue.

**Comment by imkerberos** [comment]
@shivam340 Do not use the "copy" option when add files to group. Please use references.

**Comment by shivam340** [comment]
<img width="559" alt="screen shot 2018-08-22 at 3 06 53 pm" src="https://user-images.githubusercontent.com/5505908/44456003-1916ff00-a61d-11e8-8179-719c29469889.png">


@jamesderlin  Thanks a lot dude, It is working fine after add files to group using references. Thanks!

**Comment by AppleEducate** [comment]
This is happening a lot to me this week. `flutter_assets` folder is there and linked in Xcode. 

Xcode Log Error:
`Engine run configuration was invalid.`
`Could not launch engine with configuration.`

Flutter Doctor:
`[✓] Flutter (Channel master, v0.7.6-pre.48, on Mac OS X 10.13.6 17G65, locale en-US)`
`[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)`
`[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)`
`[✓] Android Studio (version 3.1)`
`[✓] VS Code (version 1.26.1)`
`[✓] Connected devices (3 available)`

**Comment by jamesderlin** [comment]
I'll ask again: Are you also encountering the same problem with the flutter/examples/flutter_view sample?

If you inspect your build output, do you see a `flutter_assets` subdirectory within your `.app` bundle?

**Comment by jamesderlin** [comment]
(And if you do see `flutter_assets` within your application bundle, what are the contents of that directory?)

**Comment by AppleEducate** [comment]
This shedded some light: https://github.com/flutter/flutter/issues/21221#issuecomment-419198496

**Comment by diegogalico** [comment]
Hi, I am fighting with the same error, I have tried the solutions explained before without success. Basically the app get stuck on the launch screen (just in iOS). I will appreciate any help.

```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                      10.1s
Starting Xcode build...
Xcode build done.                                           12.5s
[VERBOSE-2:shell.cc(181)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
        [1.1 A17CCD8F-BD62-4910-8166-A907FC1F4DAF 192.168.1.38.53082<->216.58.211.202:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 0.433s, DNS @0.014s took 0.012s, TCP @0.034s took 0.027s, TLS took 0.286s
        bytes in/out: 3441/1057, packets in/out: 9/10, rtt: 0.027s, retransmitted packets: 0, out-of-order packets: 0
Syncing files to device iPhone X...                          7.5s

```

```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.4 17E199, locale en-ES)
    • Flutter version 0.7.3 at /Users/diego.galico/Dev/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/diego.galico/Library/Android/sdk
    • Android NDK at /Users/diego.galico/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • SM G950F • 988a1b374c4f4b424c • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by jamesderlin** [comment]
I've already asked this twice, but apparently I'm not being clear enough.  Let me be very explicit:

If you encounter this error, please describe *what* you're building and running.  That is, are you encountering this error with your own application?  If so, is it a case where you're trying to add Flutter to an existing iOS application, or is it a pure Flutter application?  Do you get this error with `flutter run` with the `flutter/examples/flutter_view` sample?

If the flutter_view sample works, then we can isolate the problem to a misconfiguration in your application.  If you inspect your build output, do you see a `flutter_assets` subdirectory within your `.app` bundle? (And if you do see `flutter_assets` within your application bundle, what are the contents of that directory?)

These are *not* rhetorical questions.  To anyone dog-piling on this issue, please answer those questions *first*.

**Comment by jamesderlin** [comment]
@diegogalico Regarding your particular issue:  Your main failure is:

> [VERBOSE-2:shell.cc(181)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.

Have you tried doing a clean build?  If you continue to get that error, please file a separate issue.

**Comment by diegogalico** [comment]
@jamesderlin thanks for the quick answer.

I am getting this error on my own application. It is a pure flutter app. I also tried to clean.

The `flutter_assets` folder looks like this: 

![image](https://user-images.githubusercontent.com/1996249/45376680-bbad1700-b5f8-11e8-878d-e712b16204dd.png)

**Comment by matthew-carroll** [comment]
@jamesderlin is @diegogalico 's issue still the same one as the original ticket?  If so, I'll leave this open for you to troubleshoot that.  If not, then we should have that issue opened up on its own and I will close this ticket with a reference to your comment about necessary debugging questions.

**Comment by jamesderlin** [comment]
@diegogalico As I mentioned in my last comment, please file a separate issue regarding the "Invalid kernel binary format version." error.

Also, you haven't answered my question about whether you also get the failure when running one of the example applications, such as `flutter/examples/flutter_view`.

**Comment by shinayser** [comment]
> I've already asked this twice, but apparently I'm not being clear enough. Let me be very explicit:
> 
> If you encounter this error, please describe _what_ you're building and running. That is, are you encountering this error with your own application? If so, is it a case where you're trying to add Flutter to an existing iOS application, or is it a pure Flutter application? Do you get this error with `flutter run` with the `flutter/examples/flutter_view` sample?
> 
> If the flutter_view sample works, then we can isolate the problem to a misconfiguration in your application. If you inspect your build output, do you see a `flutter_assets` subdirectory within your `.app` bundle? (And if you do see `flutter_assets` within your application bundle, what are the contents of that directory?)
> 
> These are _not_ rhetorical questions. To anyone dog-piling on this issue, please answer those questions _first_.

I am having this issue right now. I've posted it on stackoverflow -> https://bit.ly/2OHR195

* I've checked my .app and I *cannot* the flutter_assets folder inside.

**Comment by jamesderlin** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps used to have instructions about adding the `some/path/my_flutter/.ios/Flutter/flutter_assets` folder to your XCode project.  I'm not sure if you're supposed to be doing something else now.  cc @dnfield

**Comment by shinayser** [comment]
> https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps used to have instructions about adding the `some/path/my_flutter/.ios/Flutter/flutter_assets` folder to your XCode project. I'm not sure if you're supposed to be doing something else now. cc @dnfield

Hey man, I can't find any of this on that page. Am I missing something?

**Comment by dnfield** [comment]
There are several ways this could happen that I've seen:

1. You're missing your `flutter_assets` folder completely
2. You're trying to use AOT compiled Flutter app (e.g. profile or release mode) with a debug engine build.
3. You're trying to use JIT compiled Flutter app (debug) with a profile/release engine.

It sounds like you're missing your `flutter_assets`.  Please follow the steps on the Add2App wiki, and look at the previous comments on this page - they should help.

**Comment by jamesderlin** [comment]
@shinayser Sorry if I wasn't clear.  The add2app wiki page *formerly* had instructions about explicitly adding `flutter_assets` to your XCode project; those instructions are gone now. (You can check an [older version of the page](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps/1e7cce6378d493405f52f4ac4cc783d33fef1ee3).)

@dnfield Was removing that intentional?

**Comment by shinayser** [comment]
Hey @dnfield thanks for your help. By mean  "Add2App wiki" you mean this page http://bit.ly/2RcvMZM ?
I've searched for "flutter_assets" by cant find anything. Am i missing something? Can you give me more details?
* Where should I look to see if I have a flutter_assets folder? In my **native ios** app or the .**ios folder** inside flutter's project?

**Comment by dnfield** [comment]
Ahh, it looks like I've removed that information in a recent revision.  Some older conent here should help: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps/1e7cce6378d493405f52f4ac4cc783d33fef1ee3

`flutter_assets` should be in your `.ios` folder, and needs to be embedded into your native Xcode project.  Are you using cocoapods?  If so, this can be made a lot easier.

**Comment by dnfield** [comment]
Try adding the following lines to your `Podfile`:

```ruby
  flutter_application_path = '/Path/to/your/flutter/project'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
```

Where `/Path/to/your/flutter/project` is to the folder that contains the .ios folder.

Then run `pod install` and you should be good to go.

**Comment by shinayser** [comment]
> Try adding the following lines to your `Podfile`:
> 
> ```ruby
>   flutter_application_path = '/Path/to/your/flutter/project'
>   eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
> ```
> 
> Where `/Path/to/your/flutter/project` is to the folder that contains the .ios folder.
> 
> Then run `pod install` and you should be good to go.

@dnfield I've already done that, I've followed the entire "Add Flutter to existing apps" atutorial :'(

**Comment by dnfield** [comment]
Can you share your `Generated.xcconfig` from Flutter?

**Comment by shinayser** [comment]
```
// This is a generated file; do not edit or check into version control.
FLUTTER_ROOT=/Users/danieloliveira/Documents/flutter
FLUTTER_APPLICATION_PATH=/Users/danieloliveira/Documents/iOS Projects/flutter_embeded
FLUTTER_TARGET=/Users/danieloliveira/Documents/iOS Projects/flutter_embeded/lib/main.dart
FLUTTER_BUILD_MODE=debug
FLUTTER_BUILD_DIR=build
SYMROOT=${SOURCE_ROOT}/../build/ios
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1

```

> Can you share your `Generated.xcconfig` from Flutter?

**Comment by dnfield** [comment]
Can you try adding the full path to `Podfile` instead of a relative path, and rerun pod install?

**Comment by shinayser** [comment]
Sure I can, but where do I set it?

**Comment by dnfield** [comment]
Can you share the contents of the `podhelper.rb` file?  I'm wondering if that's not up to date.

Sorry about the path thing, I think I misread something.

**Comment by dnfield** [comment]
Also, can you share the build output of the `xcode_backend.sh` script for build and embed?

**Comment by shinayser** [comment]
**I just deleted my flutter_embeded project, and re-generated it by cli. The problem persists and this is the .rb file:**

`def parse_KV_file(file, separator='=')
    file_abs_path = File.expand_path(file)
    if !File.exists? file_abs_path
        return [];
    end
    pods_array = []
    skip_line_start_symbols = ["#", "/"]
    File.foreach(file_abs_path) { |line|
        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
        plugin = line.split(pattern=separator)
        if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_array.push({:name => podname, :path => podpath});
         else
            puts "Invalid plugin specification: #{line}"
        end
    }
    return pods_array
end

def flutter_root(f)
    generated_xcode_build_settings = parse_KV_file(File.join(f, File.join('.ios', 'Flutter', 'Generated.xcconfig')))
    if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. Make sure `flutter packages get` is executed in ${f}."
        exit
    end
    generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_ROOT'
            return p[:path]
        end
    }
end

framework_dir = File.join(flutter_application_path, '.ios', 'Flutter')

engine_dir = File.join(framework_dir, 'engine')
if !File.exist?(engine_dir)
    # Copy the debug engine to have something to link against if the xcode backend script has not run yet.
    debug_framework_dir = File.join(flutter_root(flutter_application_path), 'bin', 'cache', 'artifacts', 'engine', 'ios')
    FileUtils.mkdir_p(engine_dir)
    FileUtils.cp_r(File.join(debug_framework_dir, 'Flutter.framework'), engine_dir)
    FileUtils.cp(File.join(debug_framework_dir, 'Flutter.podspec'), engine_dir)
end

pod 'Flutter', :path => engine_dir
pod 'FlutterPluginRegistrant', :path => File.join(framework_dir, 'FlutterPluginRegistrant')

symlinks_dir = File.join(framework_dir, '.symlinks')
FileUtils.mkdir_p(symlinks_dir)
plugin_pods = parse_KV_file(File.join(flutter_application_path, '.flutter-plugins'))
plugin_pods.map { |r|
    symlink = File.join(symlinks_dir, r[:name])
    FileUtils.rm_f(symlink)
    File.symlink(r[:path], symlink)
    pod r[:name], :path => File.join(symlink, 'ios')
}
`

**Comment by dnfield** [comment]
Unfortuantely, the Add2App instructions are really only good if you're working from master - it looks like you're working from an older branch.  Can you retry on master?

**Comment by shinayser** [comment]
**OMG IT WORKED**

**Comment by MichaelShnaider** [comment]
@dnfield Thanks so much for your support, embedding flutter into an app is super simple now!

However, now I want to put my flutter project into an embedded binary and make my existing app use that embedded binary, instead of having a my_flutter folder as sibling to the existing app. I get really close, but then I encounter the flutter_assets error discussed above. 

My goal is to make an iOS equivalent of an AAR file in Android. Thus, I was curious if I can add my flutter project to an Embedded Binary and embed that into my project, or if you have any better ideas, I would love to hear them.

**Comment by devDeejay** [comment]
I had same problem with my ios build and spent quite a good amount of time trying to fix it. The fix is to try to use master channel:
```
flutter channel master
flutter upgrade
```

**Comment by n13** [comment]
> I had same problem with my ios build and spent quite a good amount of time trying to fix it. The fix is to try to use master channel:
> 
> ```
> flutter channel master
> flutter upgrade
> ```

This worked, thanks! Glad to have found this workaround that could easily have been a massive time sink. I had switched to "stable" channel from "dev" channel and then got the error.

This trick - switching to master channel - worked.
