### ISSUE TITLE
Access dart:html in flutter app for Web Midi and Web Audio APIs

### ISSUE THREAD

**Issue by xeoneux** [flutter/flutter#20799]
I would like to run a browser instance in the background, exactly like React Native does to access the web midi and the web audio APIs and use Dart to write the code for it.

Is it currently possible in Flutter and if not, will be it supported in the upcoming versions?

**Comment by zoechi** [comment]
There is https://pub.dartlang.org/packages/flutter_webview_plugin
As far as I know there is also an inline WebView widget in the works by the Flutter team.
