### ISSUE TITLE
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.

### ISSUE THREAD

**Issue by PopsHugo** [flutter/flutter#20795]
I am using Visual Studio Code and Visual Studio Emulator for Android.

I created the first example app and tried to run it.

I get the following message and the application closes on the emulator without even becoming visible:
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.

How do I fix this?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by PopsHugo** [comment]
Hi Zoechi,

The sequence of events is as follows:

On the CLI
Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Henry>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

C:\Users\Henry>

On Visual Studio Code:
Debug>Start Debugging

Information Window:
Initiating Gradlew
Resolving Dependancies
	Source: Dart Extension
Running Gradlew  'Assemble Debug'

Debug Console:
Launching lib\main.dart on 7 inch KitKat 4 4 XHDPI Tablet in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.

On the Emulator:
Unfortunately Shzenproj has stopped.


Any suggestions?

**Comment by zoechi** [comment]
The error doesn't seem to be specific to Flutter https://stackoverflow.com/questions/21837532/security-warning-on-libdvm-so-noticed-while-deploying-android-apps

**Comment by PopsHugo** [comment]
Hi, I changed the selected Phone in the emulator and it is now working.

Thank you for pointing me in the right direction.

I think I also have a memory capacity problem and that I will have to upgrade my PCs RAM

Thanks again, much appreciated

**Comment by zoechi** [comment]
Glad to hear. Can this be closed. 
It doesn't look like the Flutter team can do anything about that.
