### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by gregko** [flutter/flutter#20802]
The following assertion was thrown building
```
    _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#96da0](dirty, state: _OverlayEntryState#799d4):
    'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent !=
    null': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
      https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
    #2      new CurvedAnimation (package:flutter/src/animation/animations.dart:340:15)
    #3      ModalRoute._buildModalBarrier (package:flutter/src/widgets/routes.dart:1183:21)
    #4      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
    #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
    #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
    #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
    #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4449:32)
    #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
    #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #16     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
    #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
    #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
    #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
    #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
    #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
    #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
    #26     _invoke (dart:ui/hooks.dart:128:13)
    #27     _drawFrame (dart:ui/hooks.dart:117:3)
    (elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent != null': is not true.
```

>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.9-pre.80, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 32-bit edition (version 1.19.3)
[√] Connected devices (1 available)

! Doctor found issues in 2 categories.

The code was like this:

```dart
  @override
  void initState() {
    super.initState();
    // blah blah
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _getFeed();
  }

  void _getFeed() async {
     // blah blah...
     // Starts dialog with passed BuildContext of this and crashes
  }

```

**Comment by zoechi** [comment]
Can you please provide the full code (minimal reproduction) that allows to reproduce?

**Comment by gregko** [comment]
I tried to reproduce this today in my original project, after updating flutter master channel - still crashes, but the message and stack trace are different, more informative, so I guess the problem is fixed. The code should not be written the way I did (a shot for a quick and dirty test of some idea, not production code).

FYI, flutter doctor output and crash message/stack trace:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.7.1-pre.7, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code, 32-bit edition (version 1.19.3)
[√] Connected devices (1 available)

E: [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
    setState() or markNeedsBuild() called during build.
    This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
    The widget on which setState() or markNeedsBuild() was called was:
      Overlay-[LabeledGlobalKey<OverlayState>#52365](state: OverlayState#8be5c(entries: [OverlayEntry#e38b9(opaque: false; maintainState: false), OverlayEntry#8edbe(opaque: false; maintainState: true), OverlayEntry#29c74(opaque: false; maintainState: false), OverlayEntry#175b9(opaque: false; maintainState: true), OverlayEntry#d14d2(opaque: false; maintainState: false), OverlayEntry#1bae0(opaque: false; maintainState: true)]))
    The widget which was currently being built when the offending call was made was:
      Builder
    #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3448:11)
    #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3474:6)
    #2      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
    #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:301:5)
    #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:40:24)
    #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:182:11)
    #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:858:11)
    #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1538:11)
    #8      showGeneralDialog (package:flutter/src/widgets/routes.dart:1518:53)
    #9      showDialog (package:flutter/src/material/dialog.dart:599:10)
    #10     getLoginPass (package:avar_catalogs/controls/login_pass.dart:182:23)
    <asynchronous suspension>
    #11     _CatalogPageState._getFeed (package:avar_catalogs/catalog_page.dart:136:23)
    <asynchronous suspension>
    #12     _CatalogPageState.didChangeDependencies (package:avar_catalogs/catalog_page.dart:128:5)
    #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3779:12)
    #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
    #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
    #33     Element.inflateWidget (package:flutter/src/w
I: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I: The following assertion was thrown building
    _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#1922d](dirty, state: _OverlayEntryState#06b6b):
    'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent !=
    null': is not true.
I: Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
      https://github.com/flutter/flutter/issues/new
    When the exception was thrown, this was the stack:
I: #2      new CurvedAnimation (package:flutter/src/animation/animations.dart:340:15)
I: #3      ModalRoute._buildModalBarrier (package:flutter/src/widgets/routes.dart:1183:21)
    #4      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:170:25)
    #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
    #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
    #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
    #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
    #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
    #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
    #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I: #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4449:32)
    #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
    #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #16     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
    #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
    #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
    #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
    #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2255:33)
    #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
    #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:214:5)
    #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
    #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
    #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
    #26     _invoke (dart:ui/hooks.dart:128:13)
    #27     _drawFrame (dart:ui/hooks.dart:117:3)
I: (elided 2 frames from class _AssertionError)
    ════════════════════════════════════════════════════════════════════════════════════════════════════
I: Another exception was thrown: 'package:flutter/src/animation/animations.dart': Failed assertion: line 340 pos 15: 'parent != null': is not true.
