### ISSUE TITLE
Firebase Storage Upload progress

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#20803]
Can we get a way to monitor the file upload progress from firebase storage? This can be done in native apps and really is important for a great UX.

**Comment by rlee1990** [comment]
Any updates on this?

**Comment by iamjavademon** [comment]
As in i need this functionality like oxygen.

**Comment by eHorlyck** [comment]
Looking forward to this feature.

**Comment by rlee1990** [comment]
@iamjavademon  @eHorlyck looks like update 1.0.3 added this option. It's a bit different to use then in swift or java but if you use something like this
`task.events.listen((event) {
          setState(() {
            _isLoading = true;
            _progess = event.snapshot.bytesTransferred.toDouble() / event.snapshot.totalByteCount.toDouble();
          });
        }).onError((error) {
          _scaffoldKey.currentState.showSnackBar(new SnackBar(content: new Text(error.toString()), backgroundColor: Colors.red,) );
        });`

**Comment by iamjavademon** [comment]
Cool, i am checking it out asap.

**Comment by iamjavademon** [comment]
Just finished using it. Thanks man.

**Comment by rlee1990** [comment]
@iamjavademon no problem

**Comment by HerrNiklasRaab** [comment]
This method is only called, after the upload.

**Comment by rlee1990** [comment]
The method works its shows as it is being uploaded
@HerrNiklasRaab do you have any code showing the issue?

**Comment by rlee1990** [comment]
I would say open a new issue requesting that shouldn't be hard for them to add.

**Comment by BoxerBuzz559** [comment]
@rlee1990 please can you show a more detailed example on how to do this, if possible linking it with a progress indicator........
would that be possible?

**Comment by rlee1990** [comment]
`class _EditPhotosState extends State<EditPhotos> {

  User user;
  List<SlideShowImage> _images = List();
  List<SlideShowImage> _selectedImages = List();
  Firestore firestore = Firestore.instance;
  FirebaseStorage storage = FirebaseStorage.instance;
  List<CameraDescription> cameras;
  final uuid = new Uuid();
  StreamSubscription _one;
  StreamSubscription _two;
  int _photoLimit;
  bool _isLoading = false;
  double _progress;
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();

  @override
  void initState() {
    _getCameras();
    user = widget.user;
    _one = firestore.collection('slideShowImages').document(user.uid).collection('image').snapshots().listen(_getGallery);
    _two = firestore.collection('photoLimit').document(user.uid).snapshots().listen((DocumentSnapshot snapshot) {
      setState(() {
        _photoLimit = snapshot.data['limit'];
      });
    });

    super.initState();
  }
  _getCameras() async {
    cameras = await availableCameras();
  }

  @override
  void dispose() {
    _one.cancel();
    _two.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: Text('Edit Photos'),
        centerTitle: true,
        actions: <Widget>[
          _selectedImages.length > 0 ? IconButton(icon: Icon(Icons.delete), onPressed: _onDelete) : IconButton(icon: Icon(Icons.add_a_photo), onPressed: _toCamera)
        ],
        bottom: _isLoading ? PreferredSize(
          child: LinearProgressIndicator(
            value: _progress,
            backgroundColor: Colors.white,
          ),
          preferredSize: Size(MediaQuery.of(context).size.width, 5.0),
        ) : null,
      ),
      body: _images.length > 0 ? Padding(
        padding: const EdgeInsets.all(4.0),
        child: GridView.builder(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 3,
              crossAxisSpacing: 4.0,
              mainAxisSpacing: 4.0,
            ),
            itemCount: _images.length,
            itemBuilder: (context, index) {
              SlideShowImage image = _images[index];
              return GestureDetector(
                onTap: () => _zoomPhoto(image.url),
                onLongPress: () => _itemSelected(index),
                child: image.selected ? GridTile(
                    child: Container(
                      decoration: BoxDecoration(
                        image: DecorationImage(image: CachedNetworkImageProvider(image.url), fit: BoxFit.cover),
                      ),
                      child: Center(child: Icon(Icons.check, color: Colors.white, size: 40.0,)),
                    ),
                ) : GridTile(
                  child: CachedNetworkImage(
                      imageUrl: image.url,
                    fit: BoxFit.cover,
                    placeholder: Center(child: CircularProgressIndicator(),),
                    errorWidget: Center(child: Icon(FontAwesomeIcons.exclamationTriangle),),
                  ),
                ),
              );
            }),
      ) : Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          new Center(
            child: new CircularProgressIndicator(),
          )
        ],
      ),
    );
  }

  void _getGallery(QuerySnapshot event) {
    _images.clear();
    event.documents.forEach((DocumentSnapshot snapshot) {
      setState(() {
        _images.add(SlideShowImage.fromSnapshot(snapshot));
      });
    });
  }

  _itemSelected(int index) {
    if (_images[index].selected) {
      setState(() {
        _selectedImages.remove(_images[index]);
        _images[index].selected = false;
      });
    } else {
      setState(() {
        _selectedImages.add(_images[index]);
        _images[index].selected = true;
      });
    }
  }

  _showSubcription() {
    showDialog(
        context: context,
        builder: (context) {
          return Subscriptions(user: user,);
        }
    );
  }

  Future _toCamera() async {
    if (_images.length == _photoLimit) {
      _showSubcription();
    } else {
      Navigator.push(context, MaterialPageRoute(builder: (context) {
        return CameraView(cameras: cameras,);
      })).then((results) async {
        SystemChrome.setEnabledSystemUIOverlays(SystemUiOverlay.values);
        if (results != null && results.containsKey('path')) {
          var fileInfo = results['path'];
          File _imageFile = File(fileInfo);
          String imgUUID = uuid.v4();
          String imageName = '$imgUUID.jpg';
          StorageReference slideshowImageRef = storage.ref().child('Photos').child(user.uid).child('$imageName');
          if (Platform.isIOS) {
            File _newFile = await FlutterNativeImage.compressImage(_imageFile.path, quality: 80, percentage: 80);
            FirebaseVisionFaceDetector detector = FirebaseVisionFaceDetector.instance;
            detector.detectFromPath(_newFile.path).then((faces) {
              if (faces.length == 0) {
                _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text('You must provide a photo of your face'), backgroundColor: Colors.red,));
                return;
              }
              StorageUploadTask slideshowRefTask = slideshowImageRef.putFile(_newFile);
              slideshowRefTask.events.listen((event) {
                setState(() {
                  _isLoading = true;
                  _progress = event.snapshot.bytesTransferred.toDouble() / event.snapshot.totalByteCount.toDouble();
                });
              }).onError((error) {
                _scaffoldKey.currentState.showSnackBar(new SnackBar(content: new Text(error.toString()), backgroundColor: Colors.red,) );
              });
              slideshowRefTask.onComplete.then((snapshot) {
                setState(() {
                  _isLoading = false;
                });
                snapshot.ref.getDownloadURL().then((url) {
                  SlideShowImage _imageSlide = SlideShowImage(url.toString(), slideshowImageRef.path, false);
                  firestore.collection('slideShowImages').document(user.uid).collection('image').add(_imageSlide.toJson());
                });
              });
            });
          } else {
            File _newFile = await FlutterNativeImage.compressImage(_imageFile.path, quality: 80, percentage: 80);
            FirebaseVisionFaceDetector detector = FirebaseVisionFaceDetector.instance;
            detector.detectFromPath(_newFile.path).then((faces) {
              if (faces.length == 0) {
                _scaffoldKey.currentState.showSnackBar(SnackBar(content: Text('You must provide a photo of your face'), backgroundColor: Colors.red,));
                return;
              }
              StorageUploadTask slideshowRefTask = slideshowImageRef.putFile(_newFile);
              slideshowRefTask.events.listen((event) {
                setState(() {
                  _isLoading = true;
                  _progress = event.snapshot.bytesTransferred.toDouble() / event.snapshot.totalByteCount.toDouble();
                });
              }).onError((error) {
                _scaffoldKey.currentState.showSnackBar(new SnackBar(content: new Text(error.toString()), backgroundColor: Colors.red,) );
              });
              slideshowRefTask.onComplete.then((snapshot) {
                setState(() {
                  _isLoading = false;
                });
                snapshot.ref.getDownloadURL().then((url) {
                  SlideShowImage _imageSlide = SlideShowImage(url.toString(), slideshowImageRef.path, false);
                  firestore.collection('slideShowImages').document(user.uid).collection('image').add(_imageSlide.toJson());
                });
              });
            });
          }
        }
      });
    }
  }`

**Comment by rlee1990** [comment]
@BoxerBuzz559 the above example is what I use for a LinearProgressIndicator

**Comment by kroikie** [comment]
@rlee1990

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/697. Any further collaboration will be done there.
