### ISSUE TITLE
Issue from website page Reading and Writing Files

### ISSUE THREAD

**Issue by AkashPro** [flutter/flutter#20807]
I am not able to see the actual file in my ES File Explorar.
I was trying a flutter example and it create a Directory with Path: "/data/user/0/com.example.pathproviderexample/app_flutter" but actually in my Es File Explorar I am unable to find the file.

From URL: https://flutter.io/cookbook/persistence/reading-writing-files/

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the code you used to create the file.

**Comment by AkashPro** [comment]
@zoechi Thanks for quick response. I just realize that one need a rooted device to see the file stored using path_provider. My basic problem is resolved.
I just need some information that if I want to save a video or audio and wants it to appear in gallery. How can I do it because path_provider is saving file to safe location and one need a rooted device to access it and I am unable to use path_provider. 
Any guidance is much appreciated.

**Comment by zoechi** [comment]
Sorry, don't know. Perhaps someone else.

**Comment by AkashPro** [comment]
@zoechi Can you please refer this question to someone you think can answer my question.

**Comment by zoechi** [comment]
You can leave it open but I think cross-linking the SO question and this issue would be a good idea.

**Comment by AkashPro** [comment]
@zoechi I am new to this and don't understand what you mean by "cross-linking SO question and this issue" kindly explain what should I do now.

**Comment by AkashPro** [comment]
@zoechi  got it.

**Comment by zoechi** [comment]
I meant just posting the links. There is no specific functionality for that.

Also asked in https://stackoverflow.com/questions/51927790/flutter-images-and-video-saved-using-path-provider-not-showing-in-gallery

**Comment by AkashPro** [comment]
@zoechi I have posed this question after your advice.

**Comment by goderbauer** [comment]
Looks like the Stackoverflow question got an accepted answer. Closing this for now. Please feel free to re-open with additional information if there are still issues.

**Comment by atta1234** [comment]
it's 2021 in the issue still not resolved, users are not developer ,why they will go to data/ your.pcajge.com. / to access the file?
