### ISSUE TITLE
Unable to subscribe to Flutter-Dev mailing list

### ISSUE THREAD

**Issue by Brahmasmi** [flutter/flutter#20816]
The Flutter-Dev mailing list "subscribe" functionality has been broken for some time now both via Email (flutter-dev+subscribe@googlegroups.com) or via Web interface.

Via Email, the subscription confirmation mail arrives, but when the reply is sent to confirm, there is no "Welcome to List". Via Web interface, there is always the "error 291" which never goes away.

This seems to be a Google Groups wide problem: https://productforums.google.com/forum/#!topic/apps/MC5nerjZdFE;context-place=forum/apps.

I understand that this is not directly related to Flutter, but not being able to subscribe to the Flutter dev mailing list is in a way relevant to Flutter. Would appreciate if volks raised it internally with the Google Groups team. I have also used the "Send feedback" link on the Google Groups web interface to send a screenshot (error 291) as well as a detailed explanation of the problem.

**Comment by Hixie** [comment]
cc @mjohnsullivan

**Comment by Brahmasmi** [comment]
Closing since the subscription went through after close to 36 hours.

During that period, I got a couple of "Delivery Status Notification (Delay)"  mails with standard boilerplate, and one interesting bit under the boilerplate:

"The response was:

Unexpected DFS AddMemberships membership status"
