### ISSUE TITLE
Issue from website page Get Started: Test Drive

### ISSUE THREAD

**Issue by newthings4learning** [flutter/flutter#20839]
From URL: https://flutter.io/get-started/test-drive/

Current documentation is misleading.
It appears as if we can leave Flutter SDK empty snd click Finish for SDK to start getting downloaded automatically. However this is not the case and we have to click on install SDK link first to provide the path where SDK will be installed.

documentation can be improved.

**Comment by Sfshaza** [comment]
A very good point, @newthings4learning. I've fixed this on the new branch.
