### ISSUE TITLE
Remove Simulatable

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2083]
Simulation implements the abstract interface Simulatable, but the latter is only used for Simulation and in an internal detail of the newton package (the way it handles springs). We should simplify newton by removing Simulatable.

**Comment by Hixie** [comment]
cc @chinmaygarde for sanity check

**Comment by chinmaygarde** [comment]
Yeah, its an internal implementation detail. The only other place it is used are the spring solutions (which themselves are internal to newton).

**Comment by Hixie** [comment]
Blocked on https://github.com/flutter/flutter/issues/2441
