### ISSUE TITLE
Image size not right when placed in Container

### ISSUE THREAD

**Issue by specneeo** [flutter/flutter#20847]
When place image in Container, image width and height prop does not work.
```dart
Widget build(BuildContext context){
    return new Container(
        width: 44.0,
        height: 44.0,
        color: Color(0xFF007AFF),
        child: new Image.asset('assets/back.png',width:24.0,height:24.0)
      )
}
```
<img width="61" alt="wx20180821-102808 2x" src="https://user-images.githubusercontent.com/4651410/44376864-edb4e700-a52c-11e8-80aa-b212f35e49a8.png">
inside image width and height should not be it's parent's size.

Is this a bug?

But it could write as, It's no nessary wrap another container for image.
```dart
Widget build(BuildContext context){
    return new Container(
        width: 44.0,
        height: 44.0,
        color: Color(0xFF007AFF),
        child: new Center(
            widthFactor: 24.0,
            heightFactor: 24.0,
            child: new Image.asset('assets/back.png',width:24.0,height:24.0)
        )
      )
}
```

**Comment by zoechi** [comment]
I think this is working as intended. 
You don't need `widthFactor` and `heightFactor`.

**Comment by FoxDaxian** [comment]
I have same problem:
```javascript
new Container(
            color: Colors.blue,
            height: double.infinity,
            width: 80.0,
            child: Image.asset(
              '${data['avator']}',
              width: 40.0,
              height: 40.0,
              fit: BoxFit.fill,
            ),
          ),
```
 I set 40.0 but why do not work?

**Comment by kangwang1988** [comment]
@specneeo 
This snippet do the trick:
```
Container(
                width: 44.0,
                height: 44.0,
                color: Color(0xFF007AFF),
                child: Center(child:new Image.asset('assets/back.png',width:24.0,height:24.0))
            )
```

It's not a bug, just how to write code.
If you want to know more:
Have a look at: 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/proxy_box.dart#L256

Closing this issue now.

**Comment by Hixie** [comment]
The `width` and `height` on `Container` sets the width and height constraints of the child, at which point the `width` and `height` on the child are powerless to do anything.

**Comment by Lillls** [comment]
How should I implement this function

**Comment by zbarryte-luminopia** [comment]
@Lillls - You may be able to get the effect you want by wrapping the child in a `Center` widget, because of the constraints the Center imposes on its child.  For more details on why, see [this Flutter article](https://flutter.dev/docs/development/ui/layout/constraints).

**Comment by kamleshwebtech** [comment]
@zoechi  how to fit small image in big container in flutter ? Please suggest. Thanks.
