### ISSUE TITLE
Example which shows how to use a mobile analytics library

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2084]
Example which shows to use use Google analytics  (possibly the gallery?)

It looks like there is already a package for this:
https://github.com/dart-lang/usage
which @devoncarew has contributed to. :)

It's possible our usage in flutter_tools is sufficient.  A potential flutter customer was asking about our support for on-device usage of google analytics.

**Comment by HansMuller** [comment]
It would be interesting to see what parts of the gallery app users actually try.  Will take a look at the usage API. 

I suppose using the usage API means that we have to obtain the user's permission at install time?

**Comment by devoncarew** [comment]
Analytics supports opt-out; you do need to give the user some UI to do that.

**Comment by eseidelGoogle** [comment]
I spoke with @devoncarew about this again this afternoon, since more customers have brought it up.  He agreed that we would likely want to use package:usage, but that we should probably look at Android's APIs https://developers.google.com/analytics/devguides/collection/android/v4/#add-screen-tracking for inspiration as to if there are mobile-specific considerations.  package:usage was primarily designed for command line dart programs I'm told.

**Comment by sethladd** [comment]
Should we close this in favor of https://github.com/flutter/flutter/issues/3853 ? Not sure if the two issues are duped. Thanks for taking a look!

**Comment by sethladd** [comment]
Gallery needs analytics, so that will hopefully be a great example. See https://github.com/flutter/flutter/issues/4073

I'm going to close this in favor of adding analytics to Gallery, which can act as an example.

**Comment by sethladd** [comment]
For those looking for Google Analytics with Flutter, check out https://github.com/flutter/plugins/tree/master/packages/firebase_analytics
