### ISSUE TITLE
Issue from website page Working with cached images

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#20849]
From URL: https://flutter.io/cookbook/images/cached-images/

This library "cached_network_image" is not maintained anymore.
SO I'm using a custom NetworkImage with LruMap.

**Comment by p30arena** [comment]
@jonahwilliams
does this include FadeInImage too?

```
return new FadeInImage(
    image: new NetworkImage(
        imageUrl,
    ),
    placeholder: const AssetImage('assets/images/img_placeholder.png'),
    width: width,
    height: height,
    fit: fit,
  )
```

**Comment by p30arena** [comment]
[ImageCache class](https://docs.flutter.io/flutter/painting/ImageCache-class.html)

Generally this class is not used directly. The ImageProvider class and its subclasses automatically handle the caching of images.

**Comment by p30arena** [comment]
If true, then I think this https://flutter.io/cookbook/images/cached-images/ is misleading.

**Comment by jonahwilliams** [comment]
@p30arena I don't think so - there is a difference between downloading an image to cache to disk and in memory caching. Your example, and the ImageCache already do the later. The CachedNetworkImage handler the former, which is tricker to get right because you need to have a good strategy for eviction otherwise you will just eat disk space.

**Comment by p30arena** [comment]
This library uses https://github.com/renefloor/flutter_cache_manager
And this is how it works:
https://github.com/renefloor/flutter_cache_manager#how-it-works

> The cached files are stored in the temporary directory of the app. This means the OS can delete the files any time.
> 
> Information about the files is stored in the shared preferences with the key "lib_cached_image_data". (Because images was the first use of this library :)) The date when the cache is last cleaned is stored as "lib_cached_image_data_last_clean".
> 
> This cache information contains the end date till when the file is valid and the eTag to use with the http cache-control.

@jonahwilliams  Storing something in the temp DIR is not a way of persisting for a long period of time.

**Comment by goderbauer** [comment]
I am not sure I understand the issue reported here. @p30arena what would we need to fix so this issue can get closed?

**Comment by p30arena** [comment]
@goderbauer Sorry that the Issue wasn't clear enough, I can't remember the actual requirements.
So I'll close it.
Thanks!
