### ISSUE TITLE
ShaderMask is broken and messes up layout, AppBar rendered in the middle of the screen

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#20859]
It seems like there is a bug in the engine in `SceneBuilder.pushShaderMask` or `SceneBuilder.pop` that causes this.

This makes `ShaderMask` unusable.

<img src="https://user-images.githubusercontent.com/22688477/44394105-ab90a300-a536-11e8-9119-904e989e6b2d.png" width="200">

Example code (taken from the `ShaderMask` docs):

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Playground',
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        title: Text('Test'),
        backgroundColor: Colors.blue.withOpacity(0.5),
      ),
      body: Center(
        child: ShaderMask(
          shaderCallback: (Rect bounds) {
            return new RadialGradient(
              center: Alignment.topLeft,
              radius: 1.0,
              colors: <Color>[Colors.yellow, Colors.deepOrange.shade900],
              tileMode: TileMode.mirror,
            ).createShader(bounds);
          },
          child: const Text('I’m burning the memories'),
        ),
      ),
    );
  }
}
```

Flutter version: Latest master

**Comment by sir-boformer** [comment]
@HansMuller it seems like you initially implemented `ShaderMask`

**Comment by sir-boformer** [comment]
Here is what happens when I run the card_collection test in dev/manual_tests with the sunshine option enabled (adds a ShaderMask):

![screenshot_1534847817](https://user-images.githubusercontent.com/22688477/44397036-0fb76500-a53f-11e8-81a1-560033949b12.png)

**Comment by sir-boformer** [comment]
@zoechi Seems like a bug in the engine

**Comment by sir-boformer** [comment]
Thank you for the fix!

**Comment by jamesblasco** [comment]
@knopp did you find a solution for using BackdropFilter inside ShaderMask ?

**Comment by jascodes** [comment]
This is still an issue
