### ISSUE TITLE
New flutter update breaks several packages.

### ISSUE THREAD

**Issue by pneves001** [flutter/flutter#20854]
Flutter just recently pushed out the following SDK update. 

The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

This upgrade has broken: 
flutterlocation  (Including all forks of this package on github, it says that the plugin requires a version < 2.0.0) It fails to upgrade with the following error: 
Because loyality depends on location from git which requires SDK version <2.0.0, version solving failed.

carousel (same issue as the above plugin) 

latlong (same issue as above.)

flutter_webview_plugin (same issue as above.) 

This latest update to the flutter sdk has completely broken my app. (Some of the plugins in question took a great deal of time for me to find as they were the only plugins that I could find that used to work on both ios and android.) This issue is now completely scuttling my project.

**Comment by zoechi** [comment]
This just means the packages need to be updated to report to be compatible with Flutter ^2.0.0
Please report in the affected packages repo instead.

**Comment by zoechi** [comment]
You can work around using `dependency_overrides:` (at your own risk) if you think the packages should work with this Flutter version anyway until the packages are updated.

**Comment by pneves001** [comment]
How did we get to version number 2.0 when you haven't even released version 1 yet? The current version of flutter is version 1 preview release and now the sdk has jumped to version 2.0 without us getting to version 1. Which is causing breakage in package dependencies. 

The flutter project is now riddled with broken packages where changes to the framework has caused other packages to be broken as well. These are not isolated cases. Many broken packages on github haven't been edited in over a year. Its now causing quite a challenge to find packages that actually work. More then half the packages on flutter.io don't work anymore. What I went through just to find a working version of flutterlocation plugin was quite exceptional as I had someone on gitter recommend it to me. And then I still had to go and find a fork that actually worked on both IOS and android.

**Comment by zoechi** [comment]
Sorry, I meant Dart SDK Version ^2.0.0

If you don't want to change your project, then change your installed Flutter version.
```
flutter channel dev
flutter doctor
```
should do
