### ISSUE TITLE
ListView on  debug  and release get High CPU Memory  VS  iOS native

### ISSUE THREAD

**Issue by lichentao** [flutter/flutter#20857]
my Question:

Sample ListView Page in Diffrent Environment CPU and Memory very Hight, i Want To Know Why ,And How to solution!

====================================================
1. Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.5.1, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)
```

2. 比对：
![image](https://user-images.githubusercontent.com/5095376/44389556-bf033480-a55d-11e8-8894-dd6ba6023889.png)

3. UI页面
![image](https://user-images.githubusercontent.com/5095376/44393027-2cb35e80-a566-11e8-94aa-c2368198f032.png)

4. major Code:

```dart
            child: PageView.builder(
                itemCount: widget.entity.length,
                controller: controller,
//                controller: scrollController,
                onPageChanged: onPageChanged,
                itemBuilder: (BuildContext context,  int index){
                  return RefreshIndicator(
                    child: ListView.builder(
                        itemCount: dataList.length + 1,
                        itemBuilder: (context,index){
                          if (index == dataList.length){
                            return _buildProgressIndicator();
                          }else{
                            return _buildRow(dataList[index],selectIndex,size,context);
                          }
                        }
                    ),
                    onRefresh: fetchList,
                  );
                },
              ),
```

**Comment by lichentao** [comment]
@kangwang1988 Sample ListView Page  in  Diffrent  Environment CPU and  Memory very Hight, i Want To Know Why ,And How to solution!

**Comment by kangwang1988** [comment]
@lichentao 
There are several tips for us to help you figure it out.
1. Please use english if possible
2.Post the flutter environment you're using by
```
flutter doctor -v
```
3.If possible, create a project in github, so that we can reproduce your problem.

**Comment by Wanghuayin** [comment]
@lichentao ref https://github.com/flutter/flutter/issues/20245

> We don't believe that there should be any difference in probability of crash in the "react-style" model vs the "recycler" model, but we're not sure we fully understand your concern. The allocated memory is released regularly, so there should not be a concern of the memory usage being unbounded.

if you use the Listbuilder, it'll create and destory the instances when you scrolling that why it get so unstable CPU and Memory

**Comment by lifenautjoe** [comment]
Uh... At the state of things I'm wondering wether it's fair to say to end-users that Flutter is production ready and have seriously started regretting not going for a PWA.

A lot of the building blocks of basic apps are either missing, incomplete or unstable. (Performant scrolling, date pickers, selectable text fields, non-crashing video players).


On release mode, sluggish scrolling even with caching of widgets, `wantsKeepAlive` , const physics and all tricks I could find to make the thing usable. Still, hugely disappointing.

![img_7152 trim 2019-01-23 00_59_30](https://user-images.githubusercontent.com/12737509/51573566-27a66280-1eaa-11e9-807f-1a6965e6af65.gif)

**Comment by James-A-White** [comment]
My Flutter app (debug) consumed nearly 20% of the battery power of my phone in under 10 minutes of use. This will not be acceptable to end users.  So, I profiled it and noticed some interesting things with the ListView. The most problematic is a situation where the screen with the ListView continues to refresh continuously even when there is no user interaction. And, to make matters worse, the GPU load is pretty high. 

Eventually, I isolated the problem to the CachedNetworkImage library. Apparently, if you include a standard circular progress indicator as a placeholder to display as the images are loading, this is not getting properly disposed after the image loads. Even though it is not displayed on the screen, it is forcing screen refreshes to occur.

So, if you are having problems with your ListView performance and you are also embedding widgets such as the CircularProgressIndicator in your ListView rows, you might want to try removing these and seeing if that fixes the problem.

I'll open an issue in the CachedNetworkImage repo.

Just for grins, my Flutter doctor output is below.

```
Jamess-MacBook-Pro:HarrierCentralMobile-Flutter jameswhite$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.2.2-pre.1, on Mac OS X 10.13.6 17G5019, locale en-US)
    • Flutter version 1.2.2-pre.1 at /Users/jameswhite/projects/flutter
    • Framework revision e0e8e0e0c6 (13 days ago), 2019-03-05 14:02:11 +0100
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jameswhite/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • J- Connect • 30040687a2b6bdecce8b39ffef7e8358e06e00bf • ios • iOS 12.1.4

• No issues found!
```

**Comment by potatoker** [comment]
> @lichentao ref #20245
> 
> > We don't believe that there should be any difference in probability of crash in the "react-style" model vs the "recycler" model, but we're not sure we fully understand your concern. The allocated memory is released regularly, so there should not be a concern of the memory usage being unbounded.
> 
> if you use the Listbuilder, it'll create and destory the instances when you scrolling that why it get so unstable CPU and Memory

so, the truth is Flutter listView has no recycler mechanism, memory will definitely be increasing when scrolling the list and the programmer will only depends on dart vm itself to gc? And gc not only fresh the dart vm heap but also the native renderingObject memory, right?

**Comment by NathanAP** [comment]
I believe thats it, we will depend on dart vm to make things work... The main problem IMO is that we can't do anything to make the ListView smooth or using less memory. 

In my case I have a screen with a ListView.builder with images that if I open twice in any iOS device the app will just crash. Our team got another situation that ListViews were literally making objects being duplicated in the screen.

For the second situation we created Lists with Rows and Columns and I believe I'll do it for the first situation, but this is really disappointing.

**Comment by Kavantix** [comment]
I might have run into a similar issue, for me items int the listview kept rebuilding even though they did not need to.
When I removed the refresh indicator it worked as expected
@NathanAP could you try removing the refresh indicator and see if the performance increases.

**Comment by pedromassangocode** [comment]
Hi @lichentao 
Are you still facing this issue? If yes, please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
