### ISSUE TITLE
The onVerticalDragUpdate event is not triggered when the onLongPress event in GestureDetector is triggered.

### ISSUE THREAD

**Issue by huang-weilong** [flutter/flutter#20867]
my code like this:

> GestureDetector(
      child: Text('text'),
      onLongPress: () {
        print('++++++++++++++++++++++++');
      },
      onVerticalDragUpdate: (updateDetails) {
        print('******************************************');
      },
      onHorizontalDragUpdate: (updateDetails){
        print('-----------------------------------');
      },
    ),

When I press and hold, the onLongPress method is called, but I can't call the onVerticalDragUpdate method when I swipe again. Where am I doing something wrong? How should I make both methods callable?

**Comment by zoechi** [comment]
Looks similar to #17072

**Comment by huang-weilong** [comment]
@zoechi Forgive me for being a beginner, I didn't find the answer I wanted in #17072

**Comment by Hixie** [comment]
did you resolve your issue?

**Comment by huang-weilong** [comment]
@Hixie No, but I changed another way to solve my needs. I used multiple events such as onTapDown, onTapUp, onVerticalDragUpdate, onVerticalDragEnd to implement the requirements. Maybe this is a faster solution
