### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#20865]
[build](https://github.com/dart-lang/build) and [source_gen](https://github.com/dart-lang/source_gen) are the reference for code-generation in dart.

Flutter having disabled `dart:mirror`, code generation is very important (notably for serialization). 
The problem is, the current code-generation workflow is a bit tiresome

First, the command to generate code is the following:
```
flutter pub pub run build_runner build
```

There's far too many repetitions for a relatively common command. It would be much better to have the following (and maybe removing `build_runner` from the project direct dependencies): 

```
flutter generate --watch
```
This would make things much smoother and intuitive

Once we've got this command we can then add a few flags to `run`:

```
flutter run --[no-]generate
```

Which would run a `flutter generate --watch` in background. So that there's no need for multiple terminal instances.

As a bonus point, `flutter run` could detect if the project has a dependency or not on `build` (even indirect), and decides accordingly whether to generate dart files or not.

**Comment by zoechi** [comment]
I think this is related to #13834

**Comment by jonahwilliams** [comment]
While I agree we should improve this workflow, as a temporary workaround I would just create an alias for the build runner command.

`alias pbr="flutter pub pub run build_runner build"`

**Comment by rrousselGit** [comment]
> I think this is related to #13834 perhaps a dup of the linked #9870

That can help. But I fear that the linked PR may make project bootstrap harder.  And this issue is not so much about plugins or builds hooks. 


In the end, almost all projects will want a [de]serializer. And since the official solution is code-generation, I think flutter should make it a "working out of the box" experience.

**Comment by Hixie** [comment]
We will want code gen to be integrated into Flutter's build system so that it can run before analysis in the analyzer server, before tests in `flutter test`, and during hot reload.

**Comment by jonahwilliams** [comment]
We could do so by basing flutter's internal build steps (test, hot reload, build) on `package:build`. This would allow us to integrate with existing builders and source gen, as have a better story for testing our own build

**Comment by tvolkert** [comment]
Depends on https://github.com/flutter/flutter/issues/25377

**Comment by rrousselGit** [comment]
I recently faced Flutter throwing an exception because hot-reload applied before a code-generator could finish.

The solution is likely related to this issue. But is there anything I can do in the meantime to prevent this from reproducing?

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/flutter/issues/25377#issuecomment-457431642

**Comment by jonahwilliams** [comment]
Closed via https://github.com/flutter/flutter/pull/29399. See #27141 for more info
