### ISSUE TITLE
Example in NestedScrollView documentation is overcomplicated and misleading

### ISSUE THREAD

**Issue by jadengis** [flutter/flutter#20877]
I was using the `NestedScrollView` widget in my flutter application and was following the example present in the widget documentation [here](https://docs.flutter.io/flutter/widgets/NestedScrollView-class.html).

Following the example, I wrapped my `SliverAppBar` in a `SliverOverlapAbsorber` and used a `SliverOverlapInjector` in my inner scrollview to align it with the bottom of the `SliverAppBar`

Even though this has the desired effect of aligning the scrollview with the app bar, it has the following issues:
- The `GlowingOverscrollIndicator` is hidden by the sliver app bar when you are scrolling upwards
- The `RefreshIndicator` is not visible if the inner scroll view is wrapped in one.

The fix to all of these issues, to my surprise, was simply to completely remove the overlap absorber and injectors. The scrollview was appropriately aligned and the overscroll indicators and refresh indicators are visible.

I think the documentation here is misleading as it seems to suggest that these absorbers and injectors are necessary in order to use the `NestedScrollView` correctly, and it does not indicate the exact scenario when these special widgets are required (if they are required at all anymore).

Maybe the documentation should be updated to contain a simpler example that targets the simplest most common use case (that is, a scrolling app bar shared across multiple tabs / pages).

**Comment by lifenautjoe** [comment]
Was about to open the same issue.

In general when it comes to Slivers I find not only the docs confusing but the APIs hard to work with. 

Seems like its one of those use-cases that don't quite fit with the _everything is a widget_ motto and all that we have are hacky work-arounds.
