### ISSUE TITLE
Provide fake method channels

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#20876]
Plugin authors are complaining that it is not trivial to test native plugin code. The best option we have today is to refactor the plugin code outside of the method channel handlers and write unit tests for them. 

Ideally, we should have a `FakeMethodChannel` that does not have a messenger or codec but instead provides methods for accessing the last called method and its arguments. This allows plugin unit tests to get closer to testing the whole stack.

**Comment by zoechi** [comment]
Does it address the same issue as #19847?

**Comment by mehmetf** [comment]
It is an extension of it yes. I can move the content there.

I think in addition to providing it as an interface, we should provide a Fake implementation since that's what most users will end up doing.

**Comment by jonahwilliams** [comment]
We're not going to do this
