### ISSUE TITLE
latest flutter breaks some existing plugins

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#20885]
It looks like many plugins which do not specify the <code>environment:</code> line. In this case flutter will use a default range outside the latest version of dart - i'm guessing its something like :

    environment:
      sdk: "<2.0.0"

This causes the plugin to break even though it is probably working.
Example (from my own plugin)

    The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.

    Because pdfview_example depends on pdfview from path which requires SDK version <2.0.0, version solving failed.
    pub get failed (1)

**Comment by Rockvole** [comment]
@zoechi @cbracken

**Comment by Rockvole** [comment]
[✓] Flutter (Channel dev, v0.6.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 0.6.1 at /work/installs/flutter
    • Framework revision ad1eaff45a (26 hours ago), 2018-08-20 12:51:07 -0700
    • Engine revision c23690f0d7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /home/david/Android/Sdk
    • Java binary at: /work/installs/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /work/installs/android-studio-3.0
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /work/installs/idea-IC-181.4445.78
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 181.4892.1
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 1 category.

**Comment by cbracken** [comment]
@Rockvole thanks for the heads-up! 

@gspencergoog did your changes yesterday to the plugins repo cover these fixes? If not, I can take a look.

**Comment by cbracken** [comment]
In terms of third-party plugins, those will need to be updated by maintainers. 

When we do the next beta channel roll, we'll want to ensure this is covered in the changelog as well as communicated via a post to the flutter-dev mailing list.

**Comment by gspencergoog** [comment]
Yes, that's what I was fixing (well, partly: there were other issues too).

**Comment by gspencergoog** [comment]
Here's that PR, for reference: https://github.com/flutter/plugins/pull/729

**Comment by cbracken** [comment]
Thanks for confirming! Once I identify the exact dev channel release we jumped from 2.0-pre to 2.1-pre Dart SDKs, I'll update the [changelog](https://github.com/flutter/flutter/wiki/Changelog) so it makes it into the beta notes.

**Comment by Rockvole** [comment]
I changed to the beta channel and the SDK version error goes away.

I see the advantage of specifying a dart version in pubspec.yaml - you have some confidence it has been tested with a particular major version of dart and shouldnt expect subtle bugs.
Perhaps a lint warning to state that the <code>environment</code> parameter has not been supplied.

**Comment by Rockvole** [comment]
Another idea would be including the <code>environment</code> parameter in projects created with <code>flutter create</code> - a lot of projects start life there.

**Comment by zoechi** [comment]
`environment` is added for projects created with `flutter create` and enforced by `pub publish` as far as I remember. 
I think this issue is stale.
