### ISSUE TITLE
Flutter APK crash

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#20899]
Please check below screen shot I am beginner so don't know how to resolve this.
I removed all the code but still facing this issue I don't know why

![image](https://user-images.githubusercontent.com/13333370/44447596-52904000-a606-11e8-82e3-86d3210595e8.png)

**Comment by zoechi** [comment]
Please try to run `flutter clean` in the terminal in the project directory.

**Comment by zoechi** [comment]
Closing as dup of #16604
Please add a comment if above suggestion doesn't work for you or if you disagree for some other reason.

**Comment by rahulmishra1991** [comment]
Yes it works...Thanks zoechi

**Comment by zoechi** [comment]
Thanks for the update 👍

**Comment by rahulmishra1991** [comment]
I have one more issue if you can help?

**Comment by rahulmishra1991** [comment]
This is my customFun.dart file

import 'dart:async';
import 'dart:io';
import 'package:path_provider/path_provider.dart';


Future<String> get _localPath async {
  final directory = await getApplicationDocumentsDirectory();
  return directory.path;
}
Future<File> get _localFile async {
  final path = await _localPath;
  return new File("$path/token.txt");
}
Future<File> writeToken(String token) async {
  final file = await _localFile;
  return file.writeAsString("$token");
}
Future<String> readToken() async {
  try{
    final file = await _localFile;
    final token = await file.readAsString();

    return token;
  }catch (e) {
    return "No token found!";
  }
}


This is my dashboard.dart file

 void initState() {
    super.initState();
    var data = customFun.readToken();
    print(data.toString());
//    if (data != null) {
//      String message = customFun.readToken();
//      print(message.toString());
//    }
  }

I need to use readToken data for check user logged in or not.

Please help me into this

**Comment by zoechi** [comment]
I don't really understand that last question or problem.
Better to ask in https://gitter.im/flutter/flutter or StackOverflow.
