### ISSUE TITLE
FCM does not pass on data fields to Android

### ISSUE THREAD

**Issue by kroikie** [flutter/flutter#20894]
If the a notification message is received while the app is in the background any accompanying data payload is never passed on to the application when the user taps on the notification.

**Comment by zoechi** [comment]
https://github.com/flutter/plugins/pull/672 seems to address that

**Comment by zoechi** [comment]
@kroikie this has landed. Is this still an issue?

**Comment by kroikie** [comment]
No longer an issue.

**Comment by kroikie** [comment]
@kroikie

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/695. Any further collaboration will be done there.
