### ISSUE TITLE
Any limitation on using macOS 10.12.6 to develop iOS?

### ISSUE THREAD

**Issue by stt106** [flutter/flutter#20909]
From URL: https://flutter.io/setup-macos/
On the setup guide, it say flutter requires Xcode 9.0 or newer, I am aware that mac OS Sierra (10.12.6) works with Xcode 9.0 (though NOT with the latest Xcode 9.4).
So I am assuming it's sufficient to use 10.12.6 to do iOS development with flutter since it's compatible with Xcode 9.0; **but since 10.12.6 is not compatible with the latest version of Xcode**, I wonder whether there is any limitation on using it to do iOS development with flutter? 

My hardware prevents me upgrading to 10.13 hence the question.

**Comment by MisterJimson** [comment]
You will eventually need a newer version of Xcode, especially when iOS 12 comes out.

What hardware do you have?
