### ISSUE TITLE
example for persistence with firestore.

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#20901]
_From @JacquesSchalkwyk on August 22, 2018 7:16_

URL: https://pub.dartlang.org/packages/cloud_firestore#-example-tab-

It would be greatly appreciated if an example is provided to set persistence with firestore.

_Copied from original issue: dart-lang/pub-dartlang-dart#1538_

**Comment by JacquesSchalkwyk** [comment]
In angularfirestore i have this setting 

 AngularFirestoreModule.enablePersistence(),

what is the equivalent in the dart language to enable offline persistence

**Comment by dileepxdn** [comment]
how to enable offline capabilities for flutter firebase firestore. please tell me how to enable Persistence

**Comment by leedstyh** [comment]
`firestore = Firestore.instance..enablePersistence(false);` 

this give me an error message:

`PlatformException(error, FirebaseFirestore has already been started and its settings can no longer be changed. You can only call setFirestoreSettings() before calling any other methods on a FirebaseFirestore object., null)`

so how to use `enablePersistence()` ?

**Comment by andcea** [comment]
Can we get an answer on this?
One of the biggest selling points for Firestore is that it works offline as well so I was surprised to see that is not the case for the Dart/Flutter version.

I've tried to use [enablePersistance](https://pub.dartlang.org/documentation/cloud_firestore/latest/cloud_firestore/Firestore/enablePersistence.html) as well but could not get it to work, and it's marked as deprecated by @amirh anyways with no clear replacement.

**Comment by ride4sun** [comment]
I think the default is that persistence is on for cloud firestore. No need to set it. Only for the web it is off.

**Comment by kroikie** [comment]
@isoos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/694. Any further collaboration will be done there.
