### ISSUE TITLE
The following assertion was thrown during performLayout():

### ISSUE THREAD

**Issue by shiios** [flutter/flutter#20906]
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'BrandModel'

**Comment by zoechi** [comment]
Unfortunately this is not enough information for us to diagnose the problem.
Please explain the steps how to reproduce.
Please also add the output of `flutter doctor -v`.

Is this related to JSON serialization?

**Comment by shiios** [comment]
this is my code:please help me.
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Top Animate Movies'),
      ),
      body: formList == null
          ? Center(child: CircularProgressIndicator())
          : Padding(
        padding: EdgeInsets.symmetric(horizontal: 6.0, vertical: 10.0),
        child: ListView.builder(
          itemCount: formList.length,
          itemBuilder: (BuildContext context, int index) {
            return MyBrand(formList[index]);
          },
        ),
      ),
    );
  }

It crash at  return MyBrand(formList[index]);

**Comment by zoechi** [comment]
Please use StackOverflow or other channels like https://gitter.im/flutter/flutter for support questions.
