### ISSUE TITLE
Camera plugin new feature

### ISSUE THREAD

**Issue by lewixlabs** [flutter/flutter#20911]
Hi,
about Camera package (not camera picker)
https://github.com/flutter/plugins/tree/master/packages/camera
I think this plugin could integrate a function to get camera stream (single picture frame), instead of, every time, take/saving picture to filesystem and reading it.
I'm using mlkit flutter plugin (which i think has a bug when image is converted to a FirebaseVisionImage)
https://github.com/flutter/flutter/issues/19000
and I think being able to capture stream and pass it to mlkit would be more performant.

Thanks!
Lewix

**Comment by zoechi** [comment]
I'm closing this as dup of #18968.
Please add a comment if you disagree.
