### ISSUE TITLE
newton's dx() function is basically never used

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2092]
Other than in tests and within a couple of `isDone` implementations, we never seem to actually use `dx()`. We should probably drop it.

cc @chinmaygarde for sanity check.

**Comment by chinmaygarde** [comment]
The end of some simulations cannot be reliably determined from just `x()`. So I am not sure you will be able to get rid of it completely. And if its not used in most case, it should get tree shaken away right?

**Comment by Hixie** [comment]
If it exists, it's part of the API, and there's a huge developer cognitive cost to having things in the API.

In the cases where simulations want to know their velocity, they also implement their velocity, right? Can't those just have a private velocity calculation they use for isDone?

**Comment by Hixie** [comment]
Turns out the dx has a very important call site: simulation groups that switch to a spring need to know the instantaneous velocity when they create the spring.
