### ISSUE TITLE
[Snackbar] action text color can't be changed

### ISSUE THREAD

**Issue by hammy2899** [flutter/flutter#20928]
## Steps to Reproduce

1. Create a Snackbar with an action
```dart
Scaffold
  .of(context)
  .showSnackBar(new SnackBar(
    content: new Text('Snackbar action'),
    action: new SnackBarAction(
      label: 'Undo',
      onPressed: () {
        // do something
      },
    ),
  ))
;
```
2. Change your accent color to something dark (or the same color as the Snackbar background)
3. Show the Snackbar

![image](https://user-images.githubusercontent.com/11588822/44492697-61eea800-a65d-11e8-991a-37ca3933ffbe.png)

The only way to change the action button text is to change your accent color in your theme. If you have a dark accent color this will lead to being unable to use Snackbar actions.

**Comment by hammy2899** [comment]
Wrapping the SnackbarAction with a theme may work but wouldn't it make more sense to pass a `Text` widget to the `SnackBarAction` instead of the `SnackBarAction` creating it from the string passed? https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/snack_bar.dart#L120

**Comment by najeira** [comment]
`showSnackBar` requires `SnackBar` object, `SnackBar.action` is `SnackBarAction` not `Widget`. So, it can not be wrapped.

**Comment by firsthour** [comment]
A nice improvement would be to make "label" a widget, so we could use an Icon or Text.

But the reason I landed here in the first place was because I wanted to change the text color.

**Comment by pouryazzz67** [comment]
Just add 3 lines of code
![1540394859595710](https://user-images.githubusercontent.com/24470432/47442979-eb783e80-d7a2-11e8-9c05-ee1c2d3a92a4.png)

 to flutter snack_bar.dart from flutter sdk show in this picture

**Comment by najeira** [comment]
WIP https://github.com/flutter/flutter/pull/22489

**Comment by alexandergottlieb** [comment]
At the moment there's no way to change other text theme properties like `fontWeight` either. I'd really appreciate  `label` being a `Text` if possible. Or making it so we can wrap a `DefaultTextStyle` somewhere between `SnackBar` and `SnackBarAction`

**Comment by gitmathub** [comment]
It seems not to be merged yet.

**Comment by ayalma** [comment]
If we can set action button text style from outside, that's will be awesome

**Comment by TahaTesser** [comment]
Hi @hammy2899 

Based on the title of the issue, action text color can be changed so i am going to close this issue and accentColor also effect the action text color properly


```
Scaffold.of(context).showSnackBar(new SnackBar(
            content: new Text('Snackbar action'),
            action: new SnackBarAction(
              label: 'Undo',
              textColor: Colors.yellow,
              onPressed: () {
                // do something
              },
            ),
          ));
```


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (31 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.

Thank you
