### ISSUE TITLE
Flutter iOS engine: layout constraints in launch storyboard don't work correctly

### ISSUE THREAD

**Issue by johnfesa** [flutter/flutter#20933]
In the Flutter engine for iOS, the application's launch storyboard (if present) will be manually inserted into the UIWindow to mask startup latency. However, [the way the engine implements this](https://github.com/flutter/engine/blob/c62248bdd3f46794b78d1bd141e92691d539e56f/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L340) causes some layout constraints (commonly used in launch storyboards) not to work correctly. This causes a visual discontinuity when the OS version of the launch storyboard is removed and the Flutter engine version of the launch storyboard is displayed. Specifically, if a view in the launch storyboard is constrained by the Bottom Layout Guide, it will jump to an incorrect position.

This can be fixed by using the accepted pattern for embedding the content of one UIViewController in another. Apple documents this [here](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html#//apple_ref/doc/uid/TP40007457-CH11-SW1). Specifically, refer to the code example from "Listing 5-1 Adding a child view controller to a container". I think the critical missing piece is the call to "addChildViewController:", although other elements of the example may be important.

This issue affects Mulligan.

**Comment by markusaksli-nc** [comment]
Hi @johnfesa 
This has gone through some revision in the time since this issue was opened. The current implementation is [here](https://github.com/flutter/engine/blob/53d5d6853193b68ae0e0753bcb1ba6eee86713d5/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L408-L424)
It doesn't exactly follow the pattern in the documentation but this no longer seems like an issue. Can we close this?
Thank you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
