### ISSUE TITLE
flutter BottomSheet中Checkbox刷新失效

### ISSUE THREAD

**Issue by jimmonster** [flutter/flutter#20945]
在StatefulWidget对应的widget中可以刷新Checkbox，但是到BottomSheet中Checkbox刷新失效。希望有大佬可以解决下。感谢！

**Comment by pengshaomin** [comment]
搞个图啊，这样描述谁看得懂

**Comment by AAChartModel** [comment]
你在这种国际化的项目中用中文提问,那个大佬能看懂,又有那个大佬愿意看的?!!!

**Comment by kainecy** [comment]
可能需要刷Scaffold 的state

**Comment by zoechi** [comment]
Can you please post in English?
Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
