### ISSUE TITLE
Firebase Dynamic Link continued obtaining the last deep link 

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#20944]
_From @debutdeveloper on August 23, 2018 5:51_

URL: https://pub.dartlang.org/packages/firebase_dynamic_links

**Problem 1**
If our widget was already started, if you open the dynamic link again, it will never go through the initState() method again, so we will never get the deep link.

But it has solution,  WidgetsBindingObserver, by using which we can call link on app resumed.

**Problem 2**
In iOS, the AppLifecycleState.resume is called before the plugin gets the Deep Link. So link is not available by first time, and when we open app again we have link.

But we found solution for this by using some delay (Timer).

**Problem 3**
Major critical problem (No solution found).
In iOS, once we open the app, and get the deep Link using FirebaseDynamicLinks.instance.retrieveDynamicLink(), when we call it again, we continue obtaining the last deep Link, that is, since the call will be executed every time the widget enters the state of AppLifecycleState.resumed, and it happens, when the application is opened, either from a dynamic link or manually by the user, in iOS I had no way of knowing from where it was opened, because after getting a deep link, the method would bring back the same value even if it came out and entered the app manually.
As I observe the variable holding the deep link retained the old value, there must be need to clear that each time link is clicked.

_Copied from original issue: dart-lang/pub-dartlang-dart#1543_

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by debutdeveloper** [comment]
**$ flutter doctor -v**
[✓] Flutter (Channel unknown, v0.5.8, on Mac OS X 10.13 17A365, locale en-IN)
    • Flutter version 0.5.8 at /Users/amit_ios/Desktop/Amit/Flutter/flutter
    • Framework revision e4b989bf3d (3 weeks ago), 2018-08-09 09:45:44 -0700
    • Engine revision 3777931801
    • Dart version 2.0.0-dev.69.5.flutter-eab492385c

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/amit_ios/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (2 available)
    • LGL31L   • LGL31L628ad31c                       • android-arm • Android 4.4.2 (API 19)
    • iPhone X • FEC273FE-2AC0-48F8-B9C6-9F005868D31B • ios         • iOS 11.2 (simulator)

• No issues found!

**Comment by diegoveloper** [comment]
I remember I already fixed the bug on iOS,  does the issue happens on android or iOS ?

**Comment by diegoveloper** [comment]
@zoechi https://pub.dartlang.org/packages/firebase_dynamic_links#-changelog-tab- 
@debutdeveloper  please update the firebase dynamic link dependency: firebase_dynamic_links 0.1.0+1

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kroikie** [comment]
@isoos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/692. Any further collaboration will be done there.
