### ISSUE TITLE
firebase-admin plugin

### ISSUE THREAD

**Issue by raviteja1982** [flutter/flutter#20952]
I am trying to implement a custom authentication with Office365 but still, want to use firebase service APIs after the authentication so in order to do that I need a firebase-admin functionality for generating customtoken.

Is there a plugin to include firebase-admin in flutter already?

admin.createCustomToken(msftUid, additionalUserClaims)
  .then(customToken => {
    // Return this to the client.
  })

**Comment by zoechi** [comment]
I don't think so but you can implement it as cloud functions and call them from Flutter

**Comment by raviteja1982** [comment]
yeah, I think that's a good idea. I appreciate the quick response.
