### ISSUE TITLE
Make the android_views integration test depend on goldens through a github url

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#20959]
It currently depends on the golden package from bin/cache which involved complexities for making sure the local copy is available before running the test.

@xster just pointed out that I could just depend on a github url.

**Comment by eseidelGoogle** [comment]
Is this TODO still valid an useful Amir?

Looks like it uses github now:
https://github.com/flutter/flutter/blob/master/dev/integration_tests/android_views/pubspec.yaml
Speculatively closing.  Obviously re-open if I've misunderstood.  Thanks!

**Comment by amirh** [comment]
You're right, sorry forgot to close this one.
