### ISSUE TITLE
FlutterView should clear surface texture listeners before releasing it

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#20951]
FlutterView sets `OnFrameAvailableListener` [here](https://github.com/flutter/engine/blob/c5f59f53829905007770b72621ff9ed2ed5198fc/shell/platform/android/io/flutter/view/FlutterView.java#L997). However, the `release` method does not clear it. This partly causes async frames to arrive after view has been disposed (such as VideoPlayerPlugin).

**Comment by mehmetf** [comment]
@matthew-carroll FYI

**Comment by matthew-carroll** [comment]
@mehmetf should this be considered a platform embedding concern?  Should we add this ticket to that project?

**Comment by mehmetf** [comment]
Yes, absolutely.
