### ISSUE TITLE
Dependencies failing on dev channel

### ISSUE THREAD

**Issue by noordawod** [flutter/flutter#20960]
On channel dev:

```
$ flutter packages get
Running "flutter packages get" in flutter_app...            
The current Dart SDK version is 2.1.0-dev.1.0.flutter-69fce633b7.

Because system_info 0.0.16 requires SDK version <2.0.0 and no versions of system_info match >0.0.16 <0.1.0, system_info ^0.0.16 is forbidden.
So, because flutter_app depends on system_info ^0.0.16, version solving failed.
```

On channel beta, the app works.

Does this mean `system_info` is incompatible with channel dev? Any way to use dev channel even if such a dependency is not met?

**Comment by zoechi** [comment]
Yes, please report in these repose so they publish an update that claims compatibility with Dart =>2.0.0

**Comment by zoechi** [comment]
You can use `dependency_overrides:` to force pub to accept it anyways until updates are published.

**Comment by noordawod** [comment]
Perfect, thank you very much!
