### ISSUE TITLE
SwitchListTile doesn't have even padding on left and right

### ISSUE THREAD

**Issue by estherhlee1** [flutter/flutter#20961]
The padding on the 'secondary' image on the left is smaller than the padding to the right of the Switch on right.  I think this is because the switch also has padding to increase the touch target, and then the additional horizontal padding is applied, as well.  Ideally, the padding would be even with the visible edge of the switch, as shown in the [Material guidelines](https://material.io/design/components/lists.html#types)  where they show the example with the Switch.

Would it be possible to have SwitchListTile take in an optional contentPadding the same way that ListTile does, and pass it long to the internal ListTile, please?  This would allow us to pass in custom padding to better accommodate the extra padding the Switch is bringing in.

See image attached: 
![switchlisttile](https://user-images.githubusercontent.com/42388020/44547388-cc403080-a6cf-11e8-88b3-99e1b4c44c47.png)

Thanks.

**Comment by alanrussian** [comment]
Looks like the default padding might just be wrong and needs to be corrected (as opposed to making it configurable)?

**Comment by jonahwilliams** [comment]
Agree with @alanrussian  - similar to https://github.com/flutter/flutter/issues/20585 this should just be fixed

**Comment by estherhlee1** [comment]
I'm super down with that, just wasn't sure if it was breaking for others.  I think that sounds reasonable.

**Comment by jonahwilliams** [comment]
I looked into this and I don't think it is actually related to tap targets - we specifically did not increase the tap target sizes of controls within the tile widgets.

**Comment by jonahwilliams** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
By default the ListTile created by SwitchListTile pads its content by 16 on the left and right. The asymmetry you're seeing is due to the difference in the intrinsic white space included by a switch vs the light bulb icon:

![screenshot](https://user-images.githubusercontent.com/1377460/44556652-a0cd3e00-a6ef-11e8-8754-1affc63d6d39.png)

I think it would make sense for SwitchListTile to provide a contentPadding parameter so that one could override the default.

**Comment by estherhlee1** [comment]
I'm okay with either fixing it directly, or allowing us to provide a contentPadding so that those who are interested can update it.  I guess the white space doesn't matter much here since the entire row is the touch target, and I definitely understand why the spacing is visually off -- I think we just want the flexibility to allow ourselves to remove the "extra" padding on the right so that we can compensate for that included whitespace.  The material examples seem to not include that white space when it counts padding for the list tile, and we just need any way that allows us to achieve that spec.   Thanks!!

**Comment by scopendo** [comment]
My app has a ListTile where the title is a column SwitchListTile's.  The layout can only really work by specifying contentPadding, so I've made a copy of SwitchListTile instead, but being able to set contentPadding on SwitchListTile would be preferable.

**Comment by thayesx** [comment]
Any updates on adding a padding parameter to Switch, or on a temporary workaround of any kind?

**Comment by gisinator** [comment]
Any updates? Just found out about switches, but I am missing to option to remove top and bottom padding to make the switches fit into my layout :)

**Comment by rami-a** [comment]
It's already possible to do this indirectly by setting custom contentPadding on your ListTileTheme. I created #38709 to allow for explicitly setting it on the SwitchListTile widget
