### ISSUE TITLE
Android Studio can't find ScrollDirection reference.

### ISSUE THREAD

**Issue by BugsBunnyBR** [flutter/flutter#20972]
Hi, as shown in the image bellow. AS cant find the class or import it from using the shortcuts.
The workaround is to convert it to string and compare strings.
<img width="617" alt="captura de tela 2018-08-23 as 23 21 38" src="https://user-images.githubusercontent.com/70573/44561544-a5afe300-a72b-11e8-9541-dbf57546b677.png">

flutter doctor -v
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale pt-BR)
    • Flutter version 0.5.1 at /Users/juliocotta/flutter/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/juliocotta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/juliocotta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
The DartAnalyzer doesn't yet support suggesting libraries it hasn't imported yet.
It's a bit hard to imagine that the related library is not imported yet at least indirectly.

Try adding the import manually.
```dart
import 'package:flutter/rendering.dart';
```
Perhaps you just need to restart the analyzer (using the red restart icon) in the AS analyzer view

![image](https://user-images.githubusercontent.com/405837/44569017-45e02900-a779-11e8-9532-a430fe9f9367.png)

**Comment by BugsBunnyBR** [comment]
Thanks for the reply. 
Including the import by hand did the trick.
I thought it could be some bug because the IDE allowed me to click in the `userScrollDirection` property and navigate to the source or see the docs with the type, so (I thought) it could know how to import that class.

I restarted my computer, so I had no opportunity to restart the analyzer.
Thanks.

**Comment by zoechi** [comment]
I encountered this as well myself that sometimes things I assumed should work did not. 
The DartAnalyzer is under heavy development so it's expected to some degree.

I'm closing this because it's not Flutter specific. 
If you think there needs something to be fixed, please file in dart-lang/sdk where the Analyzer is maintained.
