### ISSUE TITLE
Android sdkmanager tool not found (C:...\Local\Android\sdk\tools\bin\sdkmanager)

### ISSUE THREAD

**Issue by SelloN** [flutter/flutter#20976]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter build bundle --suppress-analytics --target D:\Git\Lil_APOD\lib\main.dart --preview-dart-2 --depfile D:\Git\Lil_APOD\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir D:\Git\Lil_APOD\build\app\intermediates\flutter\debug/flutter_assets
```

## exception

RangeError: RangeError (index): Invalid value: Only valid value is 0: 1

```
#0      List.[] (dart:core-patch/dart:core/growable_array.dart:141)
#1      readDepfile (package:flutter_tools/src/base/fingerprint.dart:174)
<asynchronous suspension>
#2      Fingerprinter._getPaths (package:flutter_tools/src/base/fingerprint.dart:88)
<asynchronous suspension>
#3      Fingerprinter.doesFingerprintMatch (package:flutter_tools/src/base/fingerprint.dart:60)
<asynchronous suspension>
#4      KernelCompiler.compile (package:flutter_tools/src/compile.dart:104)
<asynchronous suspension>
#5      build (package:flutter_tools/src/bundle.dart:79)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:72)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:344)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1501)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#15     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1126)
#19     _CustomZone.run (dart:async/zone.dart:1023)
#20     runZoned (dart:async/zone.dart:1501)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#24     new Future.sync (dart:async/future.dart:222)
#25     CommandRunner.run (package:args/command_runner.dart:109)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:59)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1126)
#30     _CustomZone.run (dart:async/zone.dart:1023)
#31     runZoned (dart:async/zone.dart:1501)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:50)
#35     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#36     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
encountered exception: Exception: Android sdkmanager tool not found (C:\Users\SelloN\AppData\Local\Android\sdk\tools\bin\sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.io/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      AndroidWorkflow._ensureCanRunSdkManager (package:flutter_tools/src/android/android_workflow.dart:253)
#2      AndroidWorkflow.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:191)
<asynchronous suspension>
#3      AndroidWorkflow.validate (package:flutter_tools/src/android/android_workflow.dart:152)
<asynchronous suspension>
#4      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:88)
#5      Doctor.diagnose (package:flutter_tools/src/doctor.dart:145)
<asynchronous suspension>
#6      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:194)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1126)
#9      _CustomZone.run (dart:async/zone.dart:1023)
#10     runZoned (dart:async/zone.dart:1501)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#12     _doctorText (package:flutter_tools/runner.dart:193)
<asynchronous suspension>
#13     _createLocalCrashReport (package:flutter_tools/runner.dart:171)
<asynchronous suspension>
#14     _handleToolError (package:flutter_tools/runner.dart:126)
<asynchronous suspension>
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:63)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1126)
#18     _CustomZone.run (dart:async/zone.dart:1023)
#19     runZoned (dart:async/zone.dart:1501)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#21     runInContext (package:flutter_tools/src/context_runner.dart:43)
<asynchronous suspension>
#22     run (package:flutter_tools/runner.dart:50)
#23     main (package:flutter_tools/executable.dart:49)
<asynchronous suspension>
#24     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by zoechi** [comment]
Did you add the Android SDK to the PATH?
Also check `android/local.properties` sdk.dir=
You can set it using `flutter config`

**Comment by zoechi** [comment]
Perhaps the missing `sdkmanager` is a different problem.
Does C:\Users\SelloN\AppData\Local\Android\sdk\tools\bin\sdkmanager exist?
What is set for `sdk.dir` in `android/local.properties`?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by danthomas** [comment]
flutter config android-sdk c:\temp (as can't figure out how to clear it)
set ANDROID_HOME environment variable to C:\Users\dan.thomas\AppData\Local\Android\Sdk
flutter doctor:
[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\Users\dan.thomas\AppData\Local\Android\Sdk
      but Android SDK not found at this location.

**Comment by akshansh2000** [comment]
This worked for me:
* open Android Studio's SDK Manager
* go to the **Android SDK** tab
* Under **SDK Tools**, uncheck `Hide Obsolete Packages`
* Install **Android SDK Tools (Obsolete)**

**Comment by candidoneto89** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * Under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * Install **Android SDK Tools (Obsolete)**

I tried a whole bunch of solutions and this is the one that fixed this issue for me. Thanks.

**Comment by Prajwal-Koirala** [comment]
https://github.com/flutter/flutter/issues/20976#issuecomment-594162550

This works.

**Comment by kvt0012** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

this work with me, thank you

**Comment by Cortrano** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

Wow, thank you for help! This solution works for me on macOS.

**Comment by giorgyismael** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

Thank you for help! This worked for me!

**Comment by kevinlalkalathingal** [comment]
This Worked for me:
Try downloading:  https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
then extract and copy tools folder to C:\Users\%User%\AppData\Local\Android\Sdk

**Comment by Ataide** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

Nice Job man. This work for me.

**Comment by ahmad-netlinks** [comment]
@Ataide thank you, this worked for me too

**Comment by IslamMesha** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

Thanks this helps me fix the issue.

**Comment by brunohoppe** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

this worked for me too, thank you

**Comment by tahiriabdo131** [comment]
> This Worked for me:
> Try downloading: https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
> then extract and copy tools folder to C:\Users%User%\AppData\Local\Android\Sdk

Thank you very mucj bro it is worked for me

**Comment by underhiswings** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

Thank you ;D It works for me too!

**Comment by a12591771** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

thank you very much，it worked well.👍

**Comment by GAK1729** [comment]
> This worked for me:
> 
> * open Android Studio's **SDK Manager**
> * go to the **Android SDK** tab
> * under **SDK Tools**, uncheck `Hide Obsolete Packages`
> * install **Android SDK Tools (Obsolete)**

This one worked in Windows 10. Make sure the **SDK Manager**->**Andriod SDK Location** points to the correct SDK location in \AppData\Local\Android\Sdk.

**Comment by timsneath** [comment]
We're tracking the recent issue (Flutter 1.12 can't find sdkmanager in Android Studio 3.6) in #51712, which is different to the original bug reported here.
