### ISSUE TITLE
(minor) flutter config should fail when directory is not a Flutter project directory

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#20979]
In a directory that is not a Flutter project directory
```sh
 $ flutter config --android-sdk foo
Setting "android-sdk" value to "foo".
```
(no error code is set)
```sh
 $ echo $?
0
```
should fail with an error message

**Comment by dnfield** [comment]
`flutter config --no-analytics` is a "global" setting and shouldn't need a Flutter project dir - I'm not really clear on the others though and whether they're per-project or not.

**Comment by ianyon** [comment]
Looking at the [config command](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/config.dart), all the operations are set in the global config file, so it should be ok to run `flutter config` anywhere.
I think this should be closed

**Comment by dnfield** [comment]
Agreed.
