### ISSUE TITLE
Flutter upload image

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#20975]
I am having an issue for header content type for image my code is:

### Button functionality
```dart
floatingActionButton: new FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: new Icon(Icons.add_a_photo),
      ),
```
### Image Picker
```dart
Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    setState(() {
      _image = image;
    });
    print("Uploaded Image: $_image");
    restApis.getUploadimg(_image).then((val) => setState(()
    {
      print("API result: $val");
    }));
  }
```

### API call functionality
```dart
Future getUploadimg(_image) async {
  String apiUrl = '$_apiUrl/user/upload-profile-image';
  http.Response response = await http.post(apiUrl,headers: {
    "content-type": "multipart/form-data",
  }, body: {'avatar':_image});
  print("Result: ${response.body}");
  return JSON.decode(response.body); 
}
```

**Comment by zoechi** [comment]
I don't know about multipart post but I doubt setting the header is enough.
I remember seeing some related discussions like https://stackoverflow.com/questions/26279968/how-can-i-do-a-multipart-post-in-dart-angulardart

**Comment by rahulmishra1991** [comment]
If you have a complete example for flutter please share

**Comment by zoechi** [comment]
I don't have an example. 
This is not really Flutter specific. 
It's better to ask this kind of support question on StackOverflow.

**Comment by slightfoot** [comment]
Your `body` is incorrect. Please read the docs: https://pub.dartlang.org/documentation/http/latest/http/MultipartRequest-class.html

```
Future getUploadImg(File _image) async {
  String apiUrl = '$_apiUrl/user/upload-profile-image';
  final length = await _image.length();
  final request = new http.MultipartRequest('POST', Uri.parse(apiUrl))
	  ..files.add(new http.MultipartFile('avatar', _image.openRead(), length));
  http.Response response = await http.Response.fromStream(await request.send());
  print("Result: ${response.body}");
  return JSON.decode(response.body);
}
```

**Comment by rahulmishra1991** [comment]
Yes i checked that but with field data i also need to pass header for image and access_token.

I am stuck here..

**Comment by slightfoot** [comment]
Are you serious? I gave you a link to the documentation. Did you even try?
```dart
request.headers['Access-Token'] = 'YOUR ACCESS TOKEN';
```
_sigh_

**Comment by d-silveira** [comment]
@slightfoot I have the same use-case as @rahulmishra1991 and had setted the headers like you suggest, and also tried creating a Map<String, String> and adding with headers.addAll, but it didn't work, because those headers get encoded without the '' around header name, so the server does not recognize them.
