### ISSUE TITLE
Add Flutter to existing apps.    iOS Integrated flutter uses FlutterViewController, this controller object does not die, causing app memory bursts

### ISSUE THREAD

**Issue by 534254884** [flutter/flutter#20984]
集成flutter 使用FlutterViewController, 此控制器对象不逝放,造成app内存暴增

> Integrated flutter uses FlutterViewController, this controller object does not die, causing app memory bursts

```
[✓] Flutter (Channel master, v0.7.1-pre.20, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.7.1-pre.20 at /Users/colr/flutter
    • Framework revision 3c624f8b2c (8 hours ago), 2018-08-23 19:23:02 -0700
    • Engine revision 0b728a3140
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/colr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (2 available)
    • iPhone 7黑     • 885a05d56a343b4ab431037a2ac3ac572d4282a2 • ios • iOS 10.2.1
    • iPhone 8 Plus • F818EEC1-2388-4B59-BDE3-9D61EBAABBA0     • ios • iOS 11.4 (simulator)
```

**Comment by 534254884** [comment]
```objective-c
    FlutterViewController *flutterViewController = [[FlutterViewController alloc] init];
    [self.navigationController pushViewController:flutterViewController animated:YES];
```

I used the `Flutter.framework` class `FlutterViewController` to init a viewController and push to display, but not dealloc when I close the viewController by right swipe gesture.

I had use the  `po` command to print the address, the viewControllers were still in the memory. and the use memory of app exploded.

**Comment by ryansong** [comment]
Get the some issue. 

---flutter doctor -v ---

[✓] Flutter (Channel unknown, v0.10.2-pre.82, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.10.2-pre.82 at /usr/local/flutter
    • Framework revision 0f34f52620 (4 days ago), 2018-10-27 00:48:21 -0400
    • Engine revision 6c2a0b3a6d
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected device (3 available)
    • iPhone 7      • 7e30d5cefe20e2e0d835de2261c15cbfea691252 • ios • iOS 11.3.1
    • iPhone 6      • 2BEB3B83-CFC4-4BFF-850D-D7FB9B019A2A     • ios • iOS 8.2 (simulator)
    • iPhone XS Max • FDFB6413-7D10-4BD5-82FA-B75AF90E9885     • ios • iOS 12.0 (simulator)

**Comment by dnfield** [comment]
I'm seeing this locally.  It doesn't seem to happen if you use the `initWithEngine` initializer, but it definitely happens when you have `FlutterViewController` create its own engine instance.  I believe I know what's causing it, hopefully will have a fix soon.

**Comment by z234009184** [comment]
I had the same problem.

**Comment by huclengyue** [comment]
I had the same problem.

**Comment by zoechi** [comment]
@z234009184 @huclengyue Using "add reaction" on the initial comment would increase priority while `+1`, `me too`, ... comments are rather pointless and cause lots of people to get notified for no reason.
To get notified use the [Subscribe] button to the top right instead.
See also https://github.com/flutter/flutter/wiki/Issue-hygiene#thumbs-up-reactions

**Comment by lihui2333** [comment]
it seems appear again when i used the version 1.2.1

**Comment by dnfield** [comment]
@lihui2333 please open a separate issue for your problem, ideally with a sample that reproduces the issue. Feel free to tag me in it ("@dnfield")
