### ISSUE TITLE
Help with material menus

### ISSUE THREAD

**Issue by leisim** [flutter/flutter#20993]
There seems to be no real implementation of material menus (https://material.io/design/components/menus.html). Flutter has the `DropdownButton` but it is very limited for customizations.

How can I do something like this (from https://material.io/design/components/menus.html#dropdown-menu) ![Img](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B54x0KDcs5U-a2JhNkN6RVQxaEU%2Fbaseline-menu-intro.png)

Also is there a way to implement an autocomplete textfield?

**Comment by zoechi** [comment]
Did you check if the flutter_gallyer demo app contains such a menu?

**Comment by leisim** [comment]
Yes I didn't find it...
The popup menu is no problem (using `PopupMenuButton`) but I didn't find a way to create dropdown fields like "Label" and "State" in the screenshot. And there is no autocomplete textfield anywhere...

**Comment by zoechi** [comment]
See for example https://stackoverflow.com/questions/49273157/how-to-implement-drop-down-list-in-flutter

**Comment by zoechi** [comment]
https://flutter.io/catalog/samples/PopupMenuButton_index/

**Comment by zoechi** [comment]
Material widgets are for building material design UIs.
You can copy the source and build your custom versions of the widgets.
The widgets are composed of more specialized widgets, so there is usually not much code at the highest level of widgets where you would usually start customizing.

**Comment by leisim** [comment]
Thank you!
