### ISSUE TITLE
NetworkImage occasionally does not load (continued)

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#210]
<a href="https://github.com/afandria"><img src="https://avatars.githubusercontent.com/u/2432033?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [afandria](https://github.com/afandria)**
_Sunday Oct 18, 2015 at 21:13 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1664_

----

Using flutter 0.0.4. The solution in #801 may not have been applicable to my app, after all. There aren't any Sky errors printed out to stdout (or adb logcat).

I am building the .flx file with all my image assets pointed to in the manifest.yaml. I start Sky with `pub run sky_tools -v --very-verbose run_mojo` (and other options including --enable-multiprocess).

Related #1072

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Monday Oct 19, 2015 at 16:24 GMT_

----

Darn.  We'll keep working on it.

**Comment by sethladd** [comment]
cc @chinmaygarde you fixed networking loading. Do you think we can close this?

**Comment by chinmaygarde** [comment]
Yeah. This is fixed.
