### ISSUE TITLE
Suggestions: What if you remove the semicolon

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#21007]
We are in the 21st century, semicolon seems like an old thing, I suggest experimenting with a Flutter, with no semicolons, and see what

**Comment by DanTup** [comment]
There is an open issue in the Dart SDK discussing the possibility of making semi-colons optional here:

https://github.com/dart-lang/sdk/issues/30347

It's best to keep all discussion there in the same place.

**Comment by pedromassango** [comment]
Thank you.
