### ISSUE TITLE
OrientationBuilder returns landscape when the keyboard pops up in portrait orientation

### ISSUE THREAD

**Issue by codegrue** [flutter/flutter#21000]
When in portrait mode, if a form is on the screen and the keyboard pops up, the OrientationBuilder then thinks it's in landscape mode:

``` dart
          child: OrientationBuilder(
            builder: (context, orientation) {
              return (orientation == Orientation.portrait)
                  ? // triggers in portrait mode
                  :  // triggers in landscape mode or portrait mode with soft keyboard
            },
```

I assume it's looking at visible widget dimensions, rather than the actual device orientation.

**Comment by zoechi** [comment]
OrientationBuilder rebuilds when the orientation (aspect ratio) of the parent widget changes. 
It is not about the orientation of the device. That's a common misconception.
Try to read the docs about OrientationBuilder carefully with this information in mind and you will understand ;-)
To get the orientation of the device, use https://docs.flutter.io/flutter/widgets/MediaQueryData/orientation.html

**Comment by codegrue** [comment]
Thank you for the clarification.

**Comment by billy124** [comment]
Hi @codegrue 

Did you find a solution to this?

**Comment by codegrue** [comment]
Yes the solution is something like this:

```
  Widget build(BuildContext context) {
    var orientation = MediaQuery.of(context).orientation;

    return Scaffold(
      body: Form(
        child: (orientation == Orientation.portrait)
            ? _buildPortraitLayout()
            : _buildLandscapeLayout(),
      ),
    );
```

**Comment by asheshpaul** [comment]
> Yes the solution is something like this:
> 
> ```
>   Widget build(BuildContext context) {
>     var orientation = MediaQuery.of(context).orientation;
> 
>     return Scaffold(
>       body: Form(
>         child: (orientation == Orientation.portrait)
>             ? _buildPortraitLayout()
>             : _buildLandscapeLayout(),
>       ),
>     );
> ```

Thanks a lot, the problem was solved but a new problem arrived.
Now typeahead form field suggestions list not showing.
is there any solution available?

**Comment by codegrue** [comment]
I will update the example(s) to use this technique. Thanks!
