### ISSUE TITLE
Document the reasons behind the slow update cycle of beta

### ISSUE THREAD

**Issue by miyoyo** [flutter/flutter#21006]
Flutter beta has been at 0.5.1 for three months as of today, and I can't find anything about any updates anytime soon.
As said by @DanTup in [this issue](https://github.com/flutter/flutter/issues/20257), a few blocking bugs came out, yet, the [bad builds](https://github.com/flutter/flutter/wiki/Bad-Builds) do not document anything after 0.5.6.
Could we get some insight as to why the beta branch is two minor versions behind?

**Comment by DanTup** [comment]
*I'm not a Googler and speak with no authority* but as I understand it there is no published released schedule for Flutter. The [release process](https://github.com/flutter/flutter/wiki/Release-process#rolling-the-beta-channel) page has a little info on the process and requirements (for example that a build should be verified as having no serious bugs through at least a week on the dev channel).


> Could we get some insight as to why the beta branch is two minor versions behind?

I don't think there is an intention for every build to become a beta build. The [flutter channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) page suggests that periodically the "best" dev build from the previous month will be selected. This suggests there may be several good dev builds between betas.


> Flutter beta has been at 0.5.1 for three months as of today

I think the last beta release was late June (around two months ago). In some places Flutter shows the date of a commit that's not the date it was released (there is a delay between a commit and it being tested, pushed to dev, tested, pushed to beta, and of course, the beta selection process may result in an older build if it's deemed better).


> I can't find anything about any updates anytime soon.

I don't think that's unusual; Google usually don't announce things in advance. Plus, based on the release process above it may be difficult to know when it's going to happen (you can't predict in advance if a build is going to be good).


As mentioned in the other issue, you can switch channels using `flutter channel` to access newer code if you'd like (you can also download any version you want from [the archive page](https://flutter.io/sdk-archive/#macos)). You can always switch back if you hit any serious issues (and helping identify such issues in `dev` builds will help ensure ` more stable `beta` build).


I'm not sure if satisfies your query though - I'll leave this issue open for someone with authority to add to and/or close (cc @hixie).

**Comment by zoechi** [comment]
I also think this issue is not actionable.
I'd expect when Dart 2.0.0 works stable with Flutter and there are not other serious unsolved issues they'll release a new beta.

**Comment by zoechi** [comment]
@Hixie are there any plans in this direction?

**Comment by Hixie** [comment]
We hope to have a new beta out tomorrow! We've been baking the 0.6.0 build for a week now, and I am not aware of any problems having turned up.

**Comment by slightfoot** [comment]
I've been seeing issues with v0.5.8. https://github.com/flutter/flutter/issues/19590

**Comment by slightfoot** [comment]
@Hixie I've done roughly 5 builds and no hot-reload/restart issues at the moment. It's late here, so will be coding more tomorrow and can let you know if there's any issues.

**Comment by Hixie** [comment]
Great! Thanks!

**Comment by slightfoot** [comment]
@Hixie No issues. I think its been resolved.
