### ISSUE TITLE
InkSplash and InkRipple have many pieces of identical code

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#21014]
We should combine those duplicate code pieces into a single one. See https://github.com/flutter/flutter/pull/20751#discussion_r211378022

**Comment by liyuqian** [comment]
CC @HansMuller

**Comment by Elbertbiggs360** [comment]
Hello @liyuqian I am interested in working on this as my first PR. I shall look at the comment (20751) you reference above and raise a PR for it.
I hope I can get some feedback from you 🙂

**Comment by liyuqian** [comment]
Cool! I'm happy to review your PR and give feedback. I'm currently in China
and I'll return to MTV next week. So before the next week, I might be slow
to reply due to the time difference and traveling.

**Comment by mannprerak2** [comment]
HI @liyuqian, I would like to work on this..

So far I've made a mixin 
```dart
abstract class InkSplashRippleMixin {
  // This class is intended to be used as a mixin, and should not be
  // extended directly.
  // Reduces duplicate code between InkSplash and InkRipple 
  factory InkSplashRippleMixin._() => null;

  final BorderRadius _borderRadius;
  final ShapeBorder _customBorder;
  final RectCallback _clipCallback;
  Animation<double> _radius;

  void paintInkCircle(Canvas canvas, Matrix4 transform, Paint paint, Offset center){
    final Offset originOffset = MatrixUtils.getAsTranslation(transform);
    canvas.save();
    if (originOffset == null) {
      canvas.transform(transform.storage);
    } else {
      canvas.translate(originOffset.dx, originOffset.dy);
    }
    if (_clipCallback != null) {
      final Rect rect = _clipCallback();
      if (_customBorder != null) {
        canvas.clipPath(_customBorder.getOuterPath(rect, textDirection: _textDirection));
      } else if (_borderRadius != BorderRadius.zero) {
        canvas.clipRRect(RRect.fromRectAndCorners(
          rect,
          topLeft: _borderRadius.topLeft, topRight: _borderRadius.topRight,
          bottomLeft: _borderRadius.bottomLeft, bottomRight: _borderRadius.bottomRight,
        ));
      } else {
        canvas.clipRect(rect);
      }
    }
    canvas.drawCircle(center, _radius.value, paint);
    canvas.restore();
  }
}
```

This can be used directly in both ink_splash.dart and ink_ripple.dart
I would like to ask -
1. An appropriate name for this Mixin?
2. Where should I declare this mixin?
3. Should I also extract the following variables into the mixin?
```
  final Offset _position;
  final double _targetRadius;
  final TextDirection _textDirection;
```

**Comment by Elbertbiggs360** [comment]
Sorry for holding this up. Got overwhelmed with something else

**Comment by liyuqian** [comment]
Thank you @mannprerak2 ! Overall your mixin looks good. Unfortunately, I'm currently out-of-office. My colleague @goderbauer may be able to provide you faster and better feedback on naming and where to put this mixin.
