### ISSUE TITLE
Because mystery_live depends on csslib ^0.14.5 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#21018]
flutter 0.7.0

Because mystery_live depends on csslib ^0.14.5 which doesn't match any versions, version solving failed.

**Comment by zoechi** [comment]
Please post your pubspec.yaml and the output of `flutter doctor -v`.
Is this the full error output?

**Comment by zoechi** [comment]
Are you in China?
See https://github.com/flutter/flutter/issues/20809#issuecomment-415273351

**Comment by Seifon** [comment]
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
Because flutter_tools depends on file_testing 2.0.3 which doesn't match any versions, version solving failed.

**Comment by Seifon** [comment]
yes , I from China

**Comment by Seifon** [comment]
have already been solved！

Thanks!

**Comment by kiradan** [comment]
how to solved?can you tell me?

**Comment by Seifon** [comment]
use pub.dartlang.org
