### ISSUE TITLE
cloud_firestore isEqualTo matches against null

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#21016]
```dart
QuerySnapshot _query = await someCollection
        .where('field1', isEqualTo: value1)
        .getDocuments();
```

this will match a doc even when value1 in the query is null, but in the doc itself it's populated.  likewise when you string together multiple `isEqualTo` statements.  it just returns everything in the collection.

**Comment by Anuraag93** [comment]
Is there any fix to detect in the query if the isEqualTo is compared with null?

**Comment by neerajyadav** [comment]
``` dart
QuerySnapshot _query = await someCollection
        .where('field1', isEqualTo: null)
        .getDocuments();
```

returns all the documents, even those with `field1` is not `null`.

**Comment by ruhanijeb** [comment]
i am also facing the same issue

**Comment by Anuraag93** [comment]
> QuerySnapshot _query = await someCollection
>         .where('field1', isNull: true)
>         .getDocuments();

Here instead of `isEqualTo: null` give `isNull: true`. Will fix the issue

**Comment by kroikie** [comment]
@blaneyneil

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/691. Any further collaboration will be done there.
