### ISSUE TITLE
ro.product.cpu.abi

### ISSUE THREAD

**Issue by saeiddjawadi** [flutter/flutter#21021]
hello
i'm running flutter in vs code (x64) in windows 7 ultimate 64bit and using a device with API level 17!
in my case when i debug the project it show up this error:

Error retrieving device properties for ro.product.cpu.abi:
Launching lib\main.dart on Custom Phone, 4 2 2, API 17, 768x1280 in debug mode...
Exit code 1 from: D:\flutter\secapp\android\gradlew.bat -v:
Error: Could not find or load main class java.se.ee
Exited (sigterm)

i have the same issue in android studio Ver 3.1.4....:-(

could any one help?

**Comment by zoechi** [comment]
Closing as dup of #20964
