### ISSUE TITLE
Add option to generate a sample unit-test

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#2102]
Provide option `--with-unit-test` (similar to `--with-driver-test`) in `flutter create` that generates a sample unit-test.

**Comment by Hixie** [comment]
We do this now! By default!

**Comment by robertonic** [comment]
Flutter generates one unit test when a new project is created. 

Is it possible to generate a skeleton for unit tests for a specific class?

**Comment by Hixie** [comment]
@robertonic  Please file a new bug for a new topic, thanks! (And please elaborate in that bug on what you mean by "a skeleton for unit tests for a specific class".)
