### ISSUE TITLE
Make focused element visible when keyboard appears

### ISSUE THREAD

**Issue by shakil807g** [flutter/flutter#21027]
I am still facing this issue
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.6.3-pre.7, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.0)
[!] Connected devices
    ! No devices available
```

**Comment by zoechi** [comment]
Can you please post the code for a minimal reproduction?

**Comment by zoechi** [comment]
This should be fixed by #18291

@Hixie shouldn't the PR also list `flutter:beta`?

![image](https://user-images.githubusercontent.com/405837/44954882-ef29cc00-aea9-11e8-9a1e-5d860502fbbf.png)

**Comment by Hixie** [comment]
We push master to dev and dev to beta. Patches always land on master.

**Comment by zoechi** [comment]
@shakil807g is this fixed for you now?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
