### ISSUE TITLE
PrefixIcon and SuffixIcon size on InputDecoration 

### ISSUE THREAD

**Issue by shakil807g** [flutter/flutter#21038]
Due to this commit on master branch i am unable to set size of these icon smaller 

Add minimum height and width box constraints to input decoration icons (#18480)
https://github.com/flutter/flutter/commit/24a1f5706571ca184eab1deb4012fb61160a72b0#diff-0a8c1f8d767d0b3fcfa44f0263486dc3

**Comment by jonahwilliams** [comment]
This was done to follow the accessibility spec of the text field input decoration. Ideally it would always have been done that way but it had to be fixed.

**Comment by zoechi** [comment]
This does not sound like there is any further work planned and this is working as intended.

**Comment by t4ng** [comment]
use Stack[TextField, Icon] instead，remeber set contentPadding-left for textfield
