### ISSUE TITLE
Update assets-for-api-docs to Dart2

### ISSUE THREAD

**Issue by xster** [flutter/flutter#21035]
I don't think there are any dependents of assets-for-api-docs that needs Dart1 compatibility

**Comment by timsneath** [comment]
This work is done, right @xster? I don't see anything Dart 1-related in https://github.com/flutter/assets-for-api-docs (at least, based on a casual inspection)?

**Comment by xster** [comment]
There's still some dart1 code in https://github.com/flutter/assets-for-api-docs/tree/master/packages/diagrams/lib/src but I think I filed this to make dart2 authoring for new files possible (which seems to be the case now). Closing.
