### ISSUE TITLE
Create a flutter view in a native plugin?

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#21032]
Is it possible to create a flutter view dynamically defined in a `.dart` file from a native plugin on android / ios?

What I'm trying to do is write the component in flutter, and have the plugin use that as a RemoteView.

Ideally, the user can design the view using flutter / dart and the plugin can just render it.

The specific use here is a custom view for `Notification` using `setCustomBigContentView`

**Comment by darshankawar** [comment]
Hi @abacaj 
Is still still a valid issue / question ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
