### ISSUE TITLE
Moving android and ios folder to another folder (targets)

### ISSUE THREAD

**Issue by DQvsRA** [flutter/flutter#21041]
After I did this change I'm not able to compile the app, given this messages:

20:04:04.471 1 info flutter.tools Launching app/main.dart on Android SDK built for x86 in debug mode...
20:04:04.475 2 info flutter.tools No application found for TargetPlatform.android_x86.
20:04:04.475 3 info flutter.tools Is your project missing an android/AndroidManifest.xml?
20:04:04.475 4 info flutter.tools Consider running "flutter create ." to create one.

Is there any way how I can make it works again?

BTW: Flutter rocks!

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

If this is still an issue please clarify.
What exactly did you copy from where to where?

**Comment by DQvsRA** [comment]
I just created a new folder in the root of the project called "targets" and moved "ios" and "android" folders to it, then I had this error.

**Comment by jonahwilliams** [comment]
You cannot arbitrary restructure the flutter directory, the android and iOS directories must be where they are currently located - this is what the error message is communicating
