### ISSUE TITLE
video_player plugin can't handle videos without a size

### ISSUE THREAD

**Issue by adrianczuczka** [flutter/flutter#21040]
I am trying to insert a video into my app which has no size. In other words, this video is just a wrapper for audio. I'm trying to use video_player for that but it doesn't seem to know how to handle videos without a size. Would it be possible to just insert a default size if none is given during initialization of the video?

If anyone wants to look at the code, the problem is in video_player.dart, line 225: 
`value = value.copyWith(
            duration: new Duration(milliseconds: map['duration']),
            size: new Size(map['width'].toDouble(), map['height'].toDouble()),
          );`
There is no width or height in the given map, so toDouble() is being called on null, leading to it not working.

Also, it's worth mentioning that when I manually changed `map['width'].toDouble(), map['height'].toDouble()` to an arbitrary value like `10.0, 10.0`, the audio worked as expected, so the problem does not lie with the video/audio sample I am using.

**Comment by adrianczuczka** [comment]
If anyone wants to look at the code, the problem is in video_player.dart, line 225: 
`value = value.copyWith(
            duration: new Duration(milliseconds: map['duration']),
            size: new Size(map['width'].toDouble(), map['height'].toDouble()),
          );`
There is not width or height in the map, so toDouble() is being called on null, leading to it not working.

**Comment by quentinleguennec** [comment]
Hi @adrianczuczka !
I wrote a PR to solve this, it's waiting for review. Would help if you could post a comment on it to help it get more visibility :)
https://github.com/flutter/plugins/pull/813

**Comment by zoechi** [comment]
The PR was merged a week ago. 
Can this issue be closed?

**Comment by adrianczuczka** [comment]
Of course, sorry!
