### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY 

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#21042]
```
Performing hot restart...
Restarted app in 1 288ms.
I/flutter (10540): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10540): The following assertion was thrown building MyApp(dirty, state: _State#fe0a2):
I/flutter (10540): type 'List<dynamic>' is not a subtype of type 'List<Widget>'
I/flutter (10540): 
I/flutter (10540): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10540): more information in this error message to help you determine and fix the underlying cause.
I/flutter (10540): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (10540):   https://github.com/flutter/flutter/issues/new
code used:
[error_radios.txt](https://github.com/flutter/flutter/files/2321780/error_radios.txt)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and more instructions about how to reproduce.

Looks like a dup of https://github.com/dart-lang/sdk/issues/33076

**Comment by benedicte69** [comment]
Thanks @zoechi, I have been said "Dart 2 uses what is call "strong mode" flag by default, in other words, you need to avoid to not properly type your variables." If you want to reproduce the error just paste the code used which is in the error_radios.txt I joined at the end of my initial post.

**Comment by benedicte69** [comment]
Hope it can help, I am too much beginner to understand. But, apparently before  this revision https://github.com/flutter/flutter/commit/c7ea3ca377e909469c68f2ab878a5bc53d3cf66b  things were deifferent  and it was not necessary to change List radiosList = new List();  by  List<Widget> radiosList = List<Widget>();

**Comment by zoechi** [comment]
Because your log was not wrapped in ``` the `<dynamic>` and `<widget>` parts were not visible.
This makes it clear now that this issue is not related to #33076

**Comment by zoechi** [comment]
You just need to change
```dart
List radiosList = new List();
```
to
```dart
List radiosList = new List<Widget>();
```
or
```dart
List<Widget> radiosList = new List<Widget>();
```
or
```dart
List<Widget> radiosList = [];
```
or
```dart
var /* or final */ radiosList = <Widget>[];
```

**Comment by benedicte69** [comment]
yes, thank you. Can we expect a clearer error message when it occurs?   Le lundi 27 août 2018 à 08:10:05 UTC+2, Günter Zöchbauer <notifications@github.com> a écrit :  
 
 
You just need to change
List radiosList = new List();
to
List radiosList = new List<Widget>();
or
List<Widget> radiosList = new List<Widget>();
or
List<Widget> radiosList = [];
or
var /* or final */ radiosList = <Widget>[];

**Comment by zoechi** [comment]
Any suggestion? I found the error message is clear.

**Comment by benedicte69** [comment]
Oh sorry, I am not meaning your answer is not clear, I just mean that 'EXCEPTION CAUGHT BY WIDGETS LIBRARY' can be misleading for beginners. Perhaps in the future as soon as your code will be wrong as mine was, AS will tell you that your variable should be more precise.Anyway, thank you very very much for your help :)   Le lundi 27 août 2018 à 11:11:34 UTC+2, Günter Zöchbauer <notifications@github.com> a écrit :  
 
 
Any suggestion? I found the error message is clear.

**Comment by zoechi** [comment]
I see what you mean.

> EXCEPTION CAUGHT BY WIDGETS LIBRARY

Is reported because Flutter acts as a framework that calls your code and it runs into an error when doing that.

I meant

> type 'List<dynamic>' is not a subtype of type 'List<Widget>'

should give a pretty good hint at what is wrong.
As you see from my answer above there are many valid options and it's hard for the compiler to make a more specific suggestion because the compiler can't know your intention.

**Comment by benedicte69** [comment]
Many thanks for this reassuring and clear answer. Up to me now to learn deeper. I think you really answered to all my beginner's concerns and reactions. The thread can be peacefully closed now :).   Le lundi 27 août 2018 à 12:06:25 UTC+2, Günter Zöchbauer <notifications@github.com> a écrit :  
 
 
I see what you mean.


EXCEPTION CAUGHT BY WIDGETS LIBRARY


Is reported because Flutter acts as a framework that calls your code and it runs into an error when doing that.

I meant


type 'List' is not a subtype of type 'List'


should give a pretty good hint at what is wrong.
As you see from my answer above there are many valid options and it's hard for the compiler to make a more specific suggestion because the compiler can't know your intention.

**Comment by zoechi** [comment]
Great!
