### ISSUE TITLE
Add option for image_picker to force user to take squared photos.

### ISSUE THREAD

**Issue by dmjones** [flutter/flutter#21054]
(Feature request). Using the `image_picker` plugin, it would be great if the user can be forced to take a square photo. Ideally this would be passed as an optional parameter to the `pickImage` method.

```dart
Future<File> pickImage ({
@required ImageSource source,
double maxWidth,
double maxHeight,
ImageAspect aspect
})

enum ImageAspect {
  normal,
  square
}
```

**Comment by dmjones** [comment]
Based on [this StackOverflow post](https://stackoverflow.com/a/17713092/474189), a solution (for iOS, at least) might involve using an overlay to make the camera preview show a square, then cropping the actual image taken so that it matches what the preview showed.

**Comment by cyanglaz** [comment]
@dmjones Different app might want different overlay to match their UX. I am not sure how we can handle this in a single plugin. Any suggestion is welcomed!

**Comment by cyanglaz** [comment]
@dmjones You can also achieve this by using the [camera](https://pub.dartlang.org/packages/camera) plugin and create your custom UI for it. Let me know if this would help, if so I will close this issue.

**Comment by Gujie-Novade** [comment]
@cyanglaz I think you can close this.  
He answered his own question on [StackOverflow](https://stackoverflow.com/questions/51348166/how-to-square-crop-a-flutter-camera-preview)

**Comment by cyanglaz** [comment]
@Gujie-Novade Thank you for letting me know. @dmjones I am glad that you found a solution using the camera plugin! I will close the issue now. If you have more related issues, please feel free to open another issue with details.
