### ISSUE TITLE
require an unambiguous device to launch on

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2106]
I'd like to change us to requiring an unambiguous device to launch on. This would mean that:

- either there is one supported device connected
- the user uses the `--device foobar` cli option if there is more than one valid device connected
- or we fail with a message asking them to choose a device

I think this will simplify the code and remove some current buggy situations. Currently the `run` command takes a `--debug-port` option, but that won't make a lot of sense if trying to launch on more than one device simultaneously.

Some commands would continue to support multiple devices where that makes sense. And some (that are android only) wouldn't need explicit disambiguation if one device is an android one and one ios.

**Comment by apwilson** [comment]
+1  I had a situation over the weekend where I had an iOS simulator running which I didn't want to restart and instead just wanted to launch something on an android device that was connected.

**Comment by abarth** [comment]
+1

**Comment by devoncarew** [comment]
Some work towards this done here: https://github.com/flutter/flutter/pull/2123 (but not yet switching over to one device or fail).

**Comment by devoncarew** [comment]
fixed in https://github.com/flutter/flutter/pull/2612
