### ISSUE TITLE
Hot reloading a page with streambuilder bugs out

### ISSUE THREAD

**Issue by d-silveira** [flutter/flutter#21068]
I have a Streambuilder listening to a behaviourSubject broadcastStream, but whenever I Hot Reload or Hot Restart the code for any small change, The streambuilder stops seing what's on the tip of the stream, forcing me to re-do what I originally did to fill the stream

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the problem.
Please add the output of `flutter doctor -v`
and the code for a working minimal reproduction (main.dart).

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by lifenautjoe** [comment]
I'm actually experiencing this problem.

When the app is hot reloaded, the streambuilder stream gets resetted and set to the `initialData`. Meaning no state is preserved on hot reload.

Happens on every single streambuilder I have. For example

````dart
  Widget _buildUserAvatar(UserService userService) {
    return StreamBuilder(
      stream: userService.loggedInUserChange,
      initialData: null,
      builder: (context, AsyncSnapshot<User> snapshot) {
        var user = snapshot.data;

        var avatar;

        if (user == null) {
          avatar = AssetImage('assets/images/avatar.png');
        } else {
          avatar = NetworkImage(user.profile.avatar);
        }

        return Container(
          child: null,
          decoration: BoxDecoration(
              image: DecorationImage(image: avatar, fit: BoxFit.cover)),
        );
      },
    );
  }
````

Loads well when the app is opened, once its hot reloaded the `initialData` is set to null and therefore state lost.

Here's the doctor output

````
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.14 18A391, locale en-NL)
    • Flutter version 0.10.0 at /Users/joelhernandez/Documents/code/flutter
    • Framework revision d954ae6850 (4 weeks ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/joelhernandez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone XR • FA438BBC-174B-4CD2-88A1-781FB12304BC • ios • iOS 12.1 (simulator)
````

**Comment by zoechi** [comment]
The state is preserved but also `build()` is run again and this causes StreamBuilder to re-subscribe.
You probably don't want to use `StreamBuilder` and instead subscribe imperatively to the stream yourself in `initState`

**Comment by richehmer** [comment]
I experienced the issue too. It's not the end of the world, but it's kinda annoying that we have to avoid StreamBuilders in the upper hierarchy of our apps to keep hot-reload happy. At the same time I understand there are benefits to maintaining a disciplined StreamBuilder api.

**Comment by jonahwilliams** [comment]
If the stream is the same it shouldn't be rebuilt (see https://github.com/flutter/flutter/blob/aae968cd455cd6a4fbd3861afe0f5c55c75e6e2c/packages/flutter/lib/src/widgets/async.dart#L115). It sounds like you are creating a new stream on build accidentally.

**Comment by richehmer** [comment]
Ah, good to know! Working through this saved me a bug. So, for stream-heavy apps that use bloc-style services injected via inherited widget, a couple of implications are:

1. Bloc methods that return streams should return the same stream instance if they want to trouble themselves with avoiding a connecting state on hot reload. (kind of standard behavior for app-level streams like 'user' or 'user-email')
2. Take care not to instantiate Bloc-like services in a build method b.c. Bloc instance change -> stream instance change (actually this is general good advice for Flutter rookies like me who care about managing a handful of high-level app service instances)

**Comment by Y-ndm** [comment]
> Ah, good to know! Working through this saved me a bug. So, for stream-heavy apps that use bloc-style services injected via inherited widget, a couple of implications are:
> 
> 1. Bloc methods that return streams should return the same stream instance if they want to trouble themselves with avoiding a connecting state on hot reload. (kind of standard behavior for app-level streams like 'user' or 'user-email')
> 2. Take care not to instantiate Bloc-like services in a build method b.c. Bloc instance change -> stream instance change (actually this is general good advice for Flutter rookies like me who care about managing a handful of high-level app service instances)

I'm having the same issue, i set the user id from before i get to the home page which has 4 pages into it including a profile page and in the profile page i need the user id .. at first i can retrieve it from the bloc, but when i hot reload the stream returns null..
Do you have any idea how i can fix my issue..

Let me give you a clear picture first..
There's an 
== InitializationPage in it i set the: `BlocProvider<userInfoBloc>(bloc: UserInfoBloc, child ConnectPage).`
==ConnectPage is a stateless widget in the build method i call 
`UserInfoBloc userInformationBloc = BlocProvider.of<UserInfoBloc>(context);`
```
FirebaseAuth.instance.currentUser().then((currentUser){
      userInformationBloc.onUidChanged(currentUser.uid);
      Future.delayed(const Duration(milliseconds: 1000), () {
        _redirectToPage(context, HomePage());
      });
    });
```
==HomePage() has a NavigationTabBar with 4 Pages including ProfilePage()

==ProfilePage is a statefull widget, i've tried to call the bloc from the build method and from initState() but each time after reload it Uid from bloc returns null;

Any help is appreciated, thanks.

**Comment by sashvoncurtis** [comment]
@zoechi Hi,
You mentioned "...subscribe imperatively to the stream yourself in initState",
Can you please provide a rough example of this?

Rolling my own Providers and Blocs (best way to do it, not using provider or builtValue), say for an AuthBloc, has an accounts stream accessed via bloc.accounts, the StreamBuilder stream prop  is bloc.accounts. The reload is re/unsubscribing from the stream and the StreamBuilder has no data. How then could  this stream data be set to the Screens State?

Thanks

**Comment by hientrung** [comment]
Create stream outside widget, keep it as a singleton object, thus StreamBuilder work as usual
