### ISSUE TITLE
firebase_analytics plugin should support setAnalyticsCollectionEnabled

### ISSUE THREAD

**Issue by eggnstone** [flutter/flutter#21063]
The Firebase SDK has Android and iOS methods called `setAnalyticsCollectionEnabled` to enable+disable the collection of analytics data. 
[https://firebase.google.com/support/guides/disable-analytics](https://firebase.google.com/support/guides/disable-analytics)

The Flutter plugin however does not pass this through*.
When users opt out of data collection I can cease sending events but the basic automatic events (screen_view, user_engagement) are still sent.

The plugin should offer one method `setAnalyticsCollectionEnabled` and internally take care of the Android/iOS/* part.

\* for Android I can use `FirebaseAnalytics().android.setAnalyticsCollectionEnabled()` but there is no such thing for iOS.

**Comment by MisterJimson** [comment]
Doesn't this make Firebase Analytics impossible to use in a Flutter app on iOS? Without a way to disable how can you be GDPR compliant?

**Comment by lexmaurer** [comment]
Is there any progress on this issue? From my legal perspective, such opt-out mechanism is a crucial feature in order to make firebase_analytics GDPR compliant.

**Comment by lifenautjoe** [comment]
So how do you disable this?

**Comment by kroikie** [comment]
@eggnstone

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/688. Any further collaboration will be done there.
