### ISSUE TITLE
Let flutter/flutter define C flags for flutter/engine build

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#21078]
Maybe we can add something like `engine_config.h` (which is similar to `SkUserConfig.h` in Chrome/Android for Skia) to flutter/flutter repo, and use the hash of that file to download the engine binary from Google Cloud bucket?

This way, we can use guard flags to make sure that engine roll is always successful even with breaking engine changes. We can also use those flags to trim down binary size by allowing Skia to have optional features.

**Comment by liyuqian** [comment]
CC @chinmaygarde @cbracken @reed-at-google

**Comment by dnfield** [comment]
Would we still need this with FFI in place and the right symbols exported from the engine for extensibility?

**Comment by liyuqian** [comment]
I'm not very familiar with FFI. CC @mehmetf who was just talking about FFI in another email thread.

**Comment by jonahwilliams** [comment]
FFI may not be supported on all platforms

**Comment by dnfield** [comment]
Those platforms probably wouldn't benefit from using different builds of the engine either though right?

**Comment by jonahwilliams** [comment]
Hard to say for fuchsia. it's also not clear how exactly it will be exposed for iOS and Android

**Comment by jonahwilliams** [comment]
We're not going to do this.
