### ISSUE TITLE
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>

### ISSUE THREAD

**Issue by tsuf239** [flutter/flutter#21071]
while I am trying to decode json into a map, it decode it to _InternalLinkedHashMap<dynamic, dynamic> instead... does somebody know about it?

**Comment by zoechi** [comment]
Please ask support questions in one of the support channels https://flutter.io/support/
and please add the code there that allows to reproduce and investigate.
