### ISSUE TITLE
Textfield when using prefix Icon has weird behaviour when clearing text 

### ISSUE THREAD

**Issue by shakil807g** [flutter/flutter#21079]
When i enter text and after that when i start clearing text it overflow over Prefix icon
```
[✓] Flutter (Channel master, v0.7.1-pre.26, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.0)
```

**Comment by jonahwilliams** [comment]
@shakil807g could you include a screenshot of the behavior you are describing and/or some code to reproduce it?

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
Is this still an issue?

Can you please make the code a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
