### ISSUE TITLE
Benchmark and improve performance overlay performance

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#21087]
Considering that performance overlay is one of our main performance tools, we should:

1. Benchmark performance overlay in our device lab. Currently all our performance tests don't have performance overlay enabled.
2. Improve its performance to be less than 1ms per frame. Currently, it's about 4-6ms per frame on Moto G4. That time doesn't even include the actual GPU rendering time. It's just Skia doing CPU work before sending it to GPU... 4-6ms looks quite unacceptable as the whole frame's budget is only 16ms. We should be able to achieve a big speedup by caching the performance overlay to an offscreen buffer. For each new frame, we just add a new vertical blue segment.

![image](https://user-images.githubusercontent.com/22987568/44693209-79da7900-aa1b-11e8-848d-ff7603f0d6d9.png)

**Comment by liyuqian** [comment]
CC @chinmaygarde @jason-simmons @cbracken @Hixie @xster @InMatrix : don't trust the performance overlay until this bug is fixed...

**Comment by GaryQian** [comment]
Performance improved to 1.4ms on Moto G4. Can still be improved further, but this should suffice for now.
