### ISSUE TITLE
Card embedded images problem

### ISSUE THREAD

**Issue by YusufJo** [flutter/flutter#21094]
i cannot apply circular borders for images inside a card, the image edges cannot be clipped to match the card's circular boarders, and it appears to be stacked over the card.

Here's a screenshot from the app : https://imgur.com/a/QpPl0aq

Here's the **main.dart** code :
```dart
Card(
                            shape: OutlineInputBorder(
                              borderRadius: BorderRadius.all(Radius.circular(10.0)),
                            ),
                            color: Colors.grey[200],
                            child: Column(
                              children: <Widget>[
                                Image.asset('assets/food.jpg'),
                                Padding(
                                  padding: const EdgeInsets.symmetric(
                                      vertical: 10.0),
                                  child: Text(element),
                                ),
                              ],
                            ),
                          ),
```
And here's my flutter log :
```
[✓] Flutter (Channel dev, v0.7.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.7.1 at /Users/yusuf/development/flutter
    • Framework revision 3c624f8b2c (4 days ago), 2018-08-23 19:23:02 -0700
    • Engine revision 0b728a3140
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/yusuf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```
Thanks in advance 👍🏻

**Comment by iamarnas** [comment]
I have similar problem, after last Flutter updade form version 0.7+ shape: CircleBorder(), don't work any more, my circle avatar is quadrangle now.

![circle avatar](https://user-images.githubusercontent.com/42679871/44707818-d8e4d000-aaa5-11e8-8f97-3c53fb436d6f.jpeg)

**Comment by HansMuller** [comment]
The original problem, per @YusufJo is happening because the Card's material no longer clips by default (see https://github.com/flutter/flutter/pull/20752, https://github.com/flutter/flutter/pull/18576, https://github.com/flutter/flutter/pull/18576). We need to expose a Card.clipBehavior parameter.

@iamarnas - you need to specify `clipBehavior: Clip.antiAlias` on your Material widget.

**Comment by netsmertia** [comment]
Tried as suggested by @HansMuller but getting some strange behaviour when card is used with `listView.builder`. Its look like a windows is sliding over the cards. Got the same behaviour when `ClipRRect` applied below the `card` or over the `image`.  (Tested on emulator)

![screenshot 2018-12-16 at 8 57 38 pm](https://user-images.githubusercontent.com/4003316/50055513-292b8f00-0176-11e9-9474-afb6b31516e0.png)


```dart
ListView.builder(
        itemCount: videoList.length,
        itemBuilder: (BuildContext builder, int index) {
          return Card(
            clipBehavior: Clip.antiAlias,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Image.asset("assets/thumb${index % 3}.jpg", fit: BoxFit.cover),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(videoList[index].title),
                ),
              ]
            ),
          );
        },
      ),
```

**Comment by zoechi** [comment]
@netsmertia that's probably worth a new issue. This one is closed.

**Comment by dpedrinha** [comment]
> The original problem, per @YusufJo is happening because the Card's material no longer clips by default (see #20752, #18576, #18576). We need to expose a Card.clipBehavior parameter.
> 
> @iamarnas - you need to specify `clipBehavior: Clip.antiAlias` on your Material widget.

That did the trick. But IMO any container should have clipping by default. Specially a card.
