### ISSUE TITLE
Decide officially how much IntelliJ will support Add2App in project creation and linking.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21090]
Decide officially how much IntelliJ will support Add2App in project creation and linking.

**Comment by matthew-carroll** [comment]
Assigning to @devoncarew to make the final call on IntelliJ support for Add2App

**Comment by matthew-carroll** [comment]
@devoncarew based on our conversation, should I close this with the decision that IntelliJ will not receive Add2App project creation support?

**Comment by devoncarew** [comment]
Yes - for project creation. We can re-evaluate based on user feedback.

cc @stevemessick
