### ISSUE TITLE
Unable to run plugin from generated flutter create --template=plugin -i swift

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#21096]
Made no code changes fresh command ran `flutter create --template=plugin -i swift`,

Follow instructions listed at: https://flutter.io/developing-packages/#edit-plugin-package

Navigate to and run: `cd testplugin/example; flutter build ios --no-codesign`

Error from command line: 
```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET testplugin OF PROJECT Pods WITH CONFIGURATION Release ===
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/testplugin-umbrella.h"
            ^
    /Users/anton/personal/testplugin/example/ios/Pods/Target Support Files/testplugin/testplugin-umbrella.h:5:9: error: include of non-modular header inside framework module 'testplugin': '/Users/anton/personal/testplugin/ios/Classes/TestpluginPlugin.h'
    #import "TestpluginPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'testplugin'
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/testplugin-umbrella.h"
            ^
    /Users/anton/personal/testplugin/example/ios/Pods/Target Support Files/testplugin/testplugin-umbrella.h:5:9: error: include of non-modular header inside framework module 'testplugin': '/Users/anton/personal/testplugin/ios/Classes/TestpluginPlugin.h'
    #import "TestpluginPlugin.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'testplugin'
```

When I open the `Runner.xcworkspace` under `/example`, I am also unable to build with the error:

![screen shot 2018-08-27 at 11 36 26 pm](https://user-images.githubusercontent.com/7272343/44699412-099b1a00-aa52-11e8-8124-28adba8d7a23.png)

The android version works. I cannot get the IOS sample to work.

**Comment by abacaj** [comment]
resolved above issue by switching TestpluginPlugin.h membership from project to "public":

![screen shot 2018-08-27 at 11 52 24 pm](https://user-images.githubusercontent.com/7272343/44699870-423bf300-aa54-11e8-8345-e6188908f640.png)

**Comment by abacaj** [comment]
another issue appeared, complaining about x86_arch, I had to add this line to `Debug.xcconfig` file located in ios/Flutter

`FLUTTER_BUILD_MODE=debug`

**Comment by zoechi** [comment]
Looks like a dup of #16049

**Comment by arctouch-matheusromao** [comment]
Thanks @abacaj! Changing to public solved my issue here.

**Comment by jmagman** [comment]
I believe this was fixed with https://github.com/flutter/flutter/pull/41828 / 
https://github.com/flutter/flutter/pull/42204
(though you may also have been hitting https://github.com/CocoaPods/CocoaPods/issues/7463).

Closing.  Let us know if you're still seeing this!
