### ISSUE TITLE
service protocol in the flutter runtime doesn't support streamListen Stdout / Stderr

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#211]
<a href="https://github.com/devoncarew"><img src="https://avatars.githubusercontent.com/u/1269969?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [devoncarew](https://github.com/devoncarew)**
_Monday Oct 19, 2015 at 16:29 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1665_

----

The service protocol in the flutter runtime doesn't support `streamListen('Stdout')` or `streamListen('Stderr')`.

These are listed as optional in the spec, but would probably be useful to have for flutter.

Right now we're getting the stdio output from `adb logcat`. So we wouldn't consume the streams immediately even if they were available. But I could see them as being useful if we're connecting to a VM that we didn't ourselves launch.

@johnmccutchan @turnidge @rmacnak-google

**Comment by abarth** [comment]
I believe this is supported now.
