### ISSUE TITLE
Issue from website page Cupertino (iOS风格) Widgets

### ISSUE THREAD

**Issue by DreamBuddy** [flutter/flutter#21104]
From URL: https://www.flutterchina.club/widgets/cupertino.md

activeIcon seems to unable to correctly use now.

When the tabItem is actrive, it still show the un-active icon

**Comment by DreamBuddy** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.7.2-pre.18, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.

**Comment by DreamBuddy** [comment]
in bottom_tab_bar.dart

_wrapActiveItem(
          new Expanded(
            child: new Semantics(
              selected: active,
              // TODO(https://github.com/flutter/flutter/issues/13452):
              // This needs localization support.
              hint: 'tab, ${index + 1} of ${items.length}',
              child: new GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: onTap == null ? null : () { onTap(index); },
                child: new Padding(
                  padding: const EdgeInsets.only(bottom: 4.0),
                  child: new Column(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: <Widget> [
                      new Expanded(child: new Center(child: items[index].icon)),
                      items[index].title,
                    ],
                  ),
                ),
              ),
            ),
          ),
          active: active,
        ),
change : new Expanded(child: new Center(child: items[index].icon)),
to:  new Expanded(child: new Center(child: active?items[index].activeIcon:items[index].icon)),

**Comment by xster** [comment]
This is solved now.
