### ISSUE TITLE
Google Map Widget

### ISSUE THREAD

**Issue by GaneshShiroleScorg** [flutter/flutter#21101]
My Request to Flutter team please provide Google Map Widget in flutter it will better to add google map inside the flutter widget because I want to develop App like Ola and Uber in Flutter.

**Comment by zoechi** [comment]
It might still miss some features but this exists already https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter

**Comment by GaneshShiroleScorg** [comment]
Hi zoechi,
It's in native not in flutter, I want to use google map inside flutter widget.
https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter

**Comment by zoechi** [comment]
Not sure why you think you can't do that with this plugin.
There is also https://pub.dartlang.org/packages/map_view

**Comment by GaneshShiroleScorg** [comment]
You are not getting my point, I mean can you create MapView Widget like Text, Image, ListView in flutter only.

**Comment by zoechi** [comment]
Actually I think I got that. I still don't know why you think you can't do that.
What do you think these widgets are for?

**Comment by GaneshShiroleScorg** [comment]
![screenshot_2018-08-28-20-25-50-371_com olacabs customer](https://user-images.githubusercontent.com/26405663/44731523-fa26da00-ab00-11e8-945f-784e113b58bc.png)
How can I active this UI in flutter? You got my point?

**Comment by zoechi** [comment]
Did you even look at the links I posted above?

**Comment by zoechi** [comment]
Dup of #19030

**Comment by GaneshShiroleScorg** [comment]
Yes both plugins are developed in Native Android and iOS code not in flutter Dart, Have you seen what is inside the plugin and what is the code in this plugins.

**Comment by GaneshShiroleScorg** [comment]
I will request to Google for develop Google Map Widget in flutter in dart language only without plugin so I can use it within flutter widget.

**Comment by zoechi** [comment]
The MapView plugin renders in a Flutter widget as far as I know.

The Flutter Maps plugin from the Flutter team only projects the native view and might not (yet) do what you want. 
I don't know what implication the migration to the new AndroidView/iOS view has.

That the former also accesses the native pkatform using plugin technology doesn't necessarily mean you can't do what you want.

**Comment by saadmohammed** [comment]
just a few days ago it is created
[https://pub.dartlang.org/packages/google_maps_flutter#-readme-tab-]

**Comment by MoAbdulmalik16** [comment]
Did you manage to get a solution for the issue you mentioned above Ganesh?

**Comment by saadmohammed** [comment]
Bro, I switched to native for few are things that are not available in flutter.

**Comment by MoAbdulmalik16** [comment]
Thanks Saad, Yes certain functions are not available i was looking everywhere until last night. I can't seem to figure out how i can scan credit cards using camera, there is a plug in called Card.io but it is not working. I tried ML kit but it still not working. Same with the map. certain functionalities are not available like navigation. Imagine creating an E hailing app and not giving the driver the direction to his destination.

**Comment by saadmohammed** [comment]
It takes more time to go standard for flutter. Dont waste the time on
searching tutorials, less amount of tutorials are available.

**Comment by MoAbdulmalik16** [comment]
Thanks Moe, i will just do them native and join them.
