### ISSUE TITLE
[firebase_auth] Invalid SMS verification code exception not handled on iOS

### ISSUE THREAD

**Issue by derTuca** [flutter/flutter#21117]
The invalid SMS verification code exception is not handled on the native side on iOS, and as such, when the wrong verification code is entered, onVerificationCode does not get called, and the plugin prints out the following log in the console:
```
Unhandled exception:
PlatformException(Error 17044, FIRAuthErrorDomain, The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code SMS and be sure to use the verification code provided by the user.)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by derTuca** [comment]
The output is as follows:
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-RO)
    • Flutter version 0.5.1 at /Users/alex/dev/flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/alex/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Users/alex/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone • 9f1683e8f02bc5200ca070e8648a23cd990a4759 • ios • iOS 10.3.2

! Doctor found issues in 1 category.

```

**Comment by gosoares** [comment]
I have the same issue in the android side. And whats worst is that the exception comes with a generic code, "exception" so no way to correctly identify this.
If the sms code expires and that method is called, another exception is thrown, with this same code, and a different message.
My currently workaround (working in android, maybe not in ios) is check for the message:
```dart
try {
  final user = await auth.signInWithPhoneNumber(verificationId: verificationId, smsCode: smsCode);
  // ...
} on PlatformException catch (e) {
  print('platformException: $e');
  if (e.message.contains('The sms verification code used to create the phone auth credential is invalid')) {
    // ...
  } else if (e.message.contains('The sms code has expired')) {
    // ...
  }
}
```

I don't see the relevance in that case, but here is the output of flutter doctor:

> [✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_US.UTF-8)
>     • Flutter version 0.7.3 at /opt/flutter
>     • Framework revision 3b309bda07 (11 days ago), 2018-08-28 12:39:24 -0700
>     • Engine revision af42b6dc95
>     • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
>     • Android SDK at /home/gabriel/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.2
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 28.0.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
>     • IntelliJ at /home/gabriel/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/182.4129.33
>     • Flutter plugin version 28.0.4
>     • Dart plugin version 182.4129.13
> 
> [✓] VS Code (version 1.27.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 2.18.0
> 
> [✓] Connected devices (2 available)
>     • moto x4 • 0040499027       • android-arm64 • Android 8.0.0 (API 26)
>     • moto x4 • 192.168.1.5:5555 • android-arm64 • Android 8.0.0 (API 26)
> 
> • No issues found!

**Comment by AmitJoki** [comment]
I've experienced the same. Here's my Sentry log:


`PlatformException(ERROR_INVALID_VERIFICATION_CODE, The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user., null)
`

This was caught in:

```
firebaseUser = await firebaseAuth
            .signInWithCredential(credential)
            .catchError((err) async {
    SentryClient.report(err);
});
```

I also think that lots of phone_auth related error codes aren't documented properly. For example, there's no documentation of what `ERROR_INVALID_VERIFICATION_CODE` means.

**Comment by farickm** [comment]
I have the same issue in Android and IOS.

**Comment by manish3006** [comment]
same issue with me.. any one got solution please share...

**Comment by mohitjadav** [comment]
Unhandled Exception: PlatformException(ERROR_SESSION_EXPIRED, The sms code has expired. Please re-send the verification code to try again., null)



class PhoneSignInSection extends StatefulWidget {
  var phonenumber;

  PhoneSignInSection(this._scaffold, this.phonenumber);

  final ScaffoldState _scaffold;

  @override
  State<StatefulWidget> createState() => _PhoneSignInSectionState(phonenumber);
}

class _PhoneSignInSectionState extends State<PhoneSignInSection> {
  final _phoneNumberController = TextEditingController();
  final _smsController = TextEditingController();
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();

  var phonenumber;
  String codeSent;
  String _message = '';
  String _verificationId;
  String _code;
  FirebaseAuth _auth = FirebaseAuth.instance;

  _PhoneSignInSectionState(this.phonenumber);

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    setState(() {
      _verifyPhoneNumber();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          new Container(
            decoration: new BoxDecoration(
              image: new DecorationImage(
                image: new AssetImage("assests/background_shininghealth.png"),
                fit: BoxFit.cover,
              ),
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              ListTile(
                title: Padding(
                  padding: const EdgeInsets.only(top: 180),
                  child: Container(
                    alignment: Alignment.topCenter,
                    child: Text(
                      "OTP Verification",
                      maxLines: 1,
                      style: new TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Color(0xFFBE3837),
                          fontSize: 35,
                          fontFamily: "montserrat"),
                    ),
                  ),
                ),
              ),
              TextField(
                controller: _smsController,
                decoration: InputDecoration(labelText: 'Verification code'),
              ),
              Container(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                alignment: Alignment.center,
                child: RaisedButton(
                  onPressed: () {
                    _testSignInWithPhoneNumber(_smsController.text);
                  },
                  child: const Text('Sign in with phone number'),
                ),
              ),
            ],
          )
        ],
      ),
    );
  }

  // Exmaple code of how to veify phone number
  void _verifyPhoneNumber() async {
    setState(() {
      _message = '';
    });
    final PhoneVerificationCompleted verificationCompleted =
        (AuthCredential phoneAuthCredential) {
      _auth.signInWithCredential(phoneAuthCredential);
      setState(() {
        _message = 'Received phone auth credential: $phoneAuthCredential';
      });
    };

    final PhoneVerificationFailed verificationFailed =
        (AuthException authException) {
      setState(() {
        _message =
            'Phone number verification failed. Code: ${authException.code}. Message: ${authException.message}';
      });
    };

    PhoneCodeSent codeSent =
        (String verificationId, [int forceResendingToken]) async {
      widget._scaffold.showSnackBar(SnackBar(
        content:
            const Text('Please check your phone for the verification code.'),
      ));
      _verificationId = verificationId;
    };

    final PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout =
        (String verificationId) {
      _verificationId = verificationId;
    };

    await _auth.verifyPhoneNumber(
        phoneNumber: phonenumber,
        timeout: const Duration(seconds: 60),
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
  }

  /// Sends the code to the specified phone number.
  Future<void> _sendCodeToPhoneNumber() async {
    final PhoneVerificationCompleted verificationCompleted =
        (FirebaseUser user) {
      setState(() {
        print(
            'Inside _sendCodeToPhoneNumber: signInWithPhoneNumber auto succeeded: $user');
      });
    } as PhoneVerificationCompleted;

    final PhoneVerificationFailed verificationFailed =
        (AuthException authException) {
      setState(() {
        print(
            'Phone number verification failed. Code: ${authException.code}. Message: ${authException.message}');
      });
    };

    final PhoneCodeSent codeSent =
        (String verificationId, [int forceResendingToken]) async {
      this._verificationId = verificationId;
      print("code sent to " + _phoneNumberController.text);
    };

    final PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout =
        (String verificationId) {
      this._verificationId = verificationId;
      print("time out");
    };

    await FirebaseAuth.instance.verifyPhoneNumber(
        phoneNumber: phonenumber,
        timeout: const Duration(seconds: 60),
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
  }

  Future<String> _testSignInWithPhoneNumber(String smsCode) async {
    final AuthCredential credential = PhoneAuthProvider.getCredential(
      verificationId: _verificationId,
      smsCode: smsCode,
    );
    final FirebaseUser user = await _auth.signInWithCredential(credential);
    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);

    _smsController.text = '';
    return 'signInWithPhoneNumber succeeded: $user';
  }

/*
  _testSignInWithPhoneNumber() async
  {
    /*
    try {
      final AuthCredential credential = PhoneAuthProvider.getCredential(
        verificationId: _verificationId,
        smsCode: _smsController.text,
      );

      final FirebaseUser user = await _auth
          .signInWithCredential(credential)
          .then((user) => Navigator.of(context).pushReplacementNamed('/form'));
    } catch (e) {
      print(e);
    }


}

**Comment by zeromaro** [comment]
Issue still exists. Any timeline when it can be improved?

**Comment by kroikie** [comment]
@derTuca

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/687. Any further collaboration will be done there.

**Comment by tanmoy27112000** [comment]
i have solved this error by this method

signIn() async {
    final AuthCredential credential = PhoneAuthProvider.getCredential(
      verificationId: verificationId,
      smsCode: smsCode,
    );
    try {
      var firebaseUser =
          await FirebaseAuth.instance.signInWithCredential(credential);
      print("Login Successful");
      print(firebaseUser.user);
      Navigator.pushReplacementNamed(context, 'homepage');

    } catch (e) {
      print("Login not successful");
      Navigator.pop(context);
    }
  }

**Comment by ashok08** [comment]
> i have solved this error by this method
> 
> signIn() async {
> final AuthCredential credential = PhoneAuthProvider.getCredential(
> verificationId: verificationId,
> smsCode: smsCode,
> );
> try {
> var firebaseUser =
> await FirebaseAuth.instance.signInWithCredential(credential);
> print("Login Successful");
> print(firebaseUser.user);
> Navigator.pushReplacementNamed(context, 'homepage');
> 
> ```
> } catch (e) {
>   print("Login not successful");
>   Navigator.pop(context);
> }
> ```
> 
> }

@tanmoy27112000  Its works. Thanks!

**Comment by ch-muhammad-adil** [comment]
There is a need of adding an error enum just like we have here `PhoneAuth.ERROR_NUMBER_NOT_VALID`
