### ISSUE TITLE
Consider adding markup for UI

### ISSUE THREAD

**Issue by touseefbsb** [flutter/flutter#21111]
I know flutter is supposed to be efficient because we write all kind of code with dart and have to learn only one language and it prevents us from switching between different type of code, but the reality is markup like **html, xml and xaml** have been used for many years now in order to construct **User Interface** and developers are already very comfortable with it.
On one hand in every development stack we are promoting separation of concerns with **MVVM** and **MVC** etc because it keeps code **testable** and **maintainable**, but here in flutter we are doing the opposite.

**Why markup is better and only using dart can create problems?**
> widgets get too much nested and we have to create methods and classes in order to keep them organized and readable. 

> markup is always easy to read in terms of creating UI.

> markup requires far lesser code than backend code, for example if I want to put padding to a widget in  markup I will only add a property named padding but in dart I need to add an extra widget just to add padding.

> markup promotes separation of concerns with MVVM.

> markup can visually be so readable that you can recognize the number of widgets nested just with one glance at the code.

> we switch between files anyway because when we try to keep dart code clean we create reusable widgets and put them in seperate files, then put models in separate file and we try to put every small working part of the app in separate file, sometimes a small widget can grow up to 2, 3 files along with its functionality, but the problem is it is all in dart code, so it can be confusing which is a widget and which is logic files, with markup we can avoid this confusion.

referring to the issue ( https://github.com/flutter/flutter/issues/9624 ) I would like to disagree because markup still allows you be fully dynamic and there are many straightforward ways to be fully dynamic with the markup, using third party solutions to convert markup into widgets is not a stable solution of this problem I think, unless some third party library is adopted by core flutter team.

>> I am sure there are many other pros and cons to each way as well please do share you thoughts here as well.

**Lastly** we can still keep the option to create widgets with dart ( backend code ) like many frameworks allow that today, but it would be great if we can bring the option to create the UI and also style the UI with a single markup language with something like **xml**.

**Comment by zoechi** [comment]
This was discussed a lot already.
See also #11609, #15922.
