### ISSUE TITLE
Navigate to google maps

### ISSUE THREAD

**Issue by lroige** [flutter/flutter#21115]
I'm currently using google maps for flutter plug-in. I've managed to make it work as I need and I'd like to add a button in some of my routes to see a marker in Google Maps app. Is it possible? I've tried to see how it's done in the maps plug-in, but I haven't found the way.

**Comment by nokia6290** [comment]
These articles might help you find your answer.

https://www.reddit.com/r/FlutterDev/comments/9aphe9/flutter_from_scratch_google_mapsmarkers_and/

https://www.reddit.com/r/FlutterDev/comments/9aieev/flutter_howto_integrate_google_maps_experimental/

**Comment by lroige** [comment]
Thank you, but these articles don't have what I'm looking for. I already have markers in my map, but I'd like to see them in Google Maps, like what happens if I press the map button in this screenshot.
![screenshot_1535527283](https://user-images.githubusercontent.com/25765708/44772161-69d2ae80-ab6d-11e8-9517-ce0835f310f6.png)
Ideally I'd like to have a button on another route that would redirect the user to Google Maps just like it happens with the one from the screenshot.

**Comment by Saifallak** [comment]
You can achieve that with[ url Launcher Plugin](https://pub.dartlang.org/packages/url_launcher)
Ex:
```
                          RaisedButton.icon(
                          /// Documentation :
                          /// Google Maps in a browser: "http://maps.google.com/?q=<lat>,<lng>"
                          /// Google Maps app on an iOS mobile device : "comgooglemaps://?q=<lat>,<lng>"
                          /// Google Maps app on Android : "geo:<lat>,<lng>?z=<zoom>"
                          /// You can also use "google.navigation:q=latitude,longitude"
                          /// z is the zoom level (1-21) , q is the search query
                          /// t is the map type ("m" map, "k" satellite, "h" hybrid, "p" terrain, "e" GoogleEarth)
                          onPressed: () => _launchURL(
                              "google.navigation:q=${_mapLocation['latitude']},${_mapLocation['longitude']}"),
                          icon: Icon(Icons.location_on),
                          label: Text("Open Maps"),
                        ),
```

**Comment by lroige** [comment]
It works, thank you!

**Comment by karmelcorn** [comment]
If you want to use address instead of lat, long, you can use the following.

Referencing https://developers.google.com/maps/documentation/urls/ios-urlscheme, `daddr` Sets the end point for directions searches

```
final url = 'comgooglemaps://?daddr=${Uri.encodeFull(address)}&directionsmode=driving';
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
```

**Comment by tiwariritesh1700** [comment]
> Thank you, but these articles don't have what I'm looking for. I already have markers in my map, but I'd like to see them in Google Maps, like what happens if I press the map button in this screenshot.
> ![screenshot_1535527283](https://user-images.githubusercontent.com/25765708/44772161-69d2ae80-ab6d-11e8-9517-ce0835f310f6.png)
> Ideally I'd like to have a button on another route that would redirect the user to Google Maps just like it happens with the one from the screenshot.


In IOS after click on the markers, the map button is not showing....how u solve that or how u get that for ios??
