### ISSUE TITLE
ListItems should optionally delegate events to their left or right widgets

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2111]
When a ListItem's left or right widgets are input controls it's often useful to have the  input events directed at the ListItem forwarded to one of the left or right widgets.

For example in a settings item like this, it would be nice if clicking anywhere in the list item toggled the item's checkbox.

![image](https://cloud.githubusercontent.com/assets/1377460/13265555/5eed3346-da28-11e5-94a7-30f13e5a1b31.png)

**Comment by abarth** [comment]
Do you want to delegate the events to the widgets or just manipulate the checked state for the widget?

**Comment by Hixie** [comment]
I think the right solution here is actually some subclasses of ListItem that specialise it to have a check box, radio button, or whatever.

**Comment by HansMuller** [comment]
If you funneled all of the input events to the list item's target widget then any subtleties in the way that it responded to them would be preserved. On the other hand, to make that really work you'd have to change the event's coordinates, which would probably lead to those same subtleties not really working.

I agree that the right solution is to just have the ListItem change the target widget's state.

**Comment by Hixie** [comment]
I provided dedicated CheckBoxListItem and RadioListItem widgets, which have largely dealt with the need for this. I'm not sure it would really make sense to make a general solution.
