### ISSUE TITLE
Whitespace unexpectedly failed (with no code changes)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#21110]
This one is weird.. I'm trying to repro some flakes, so I'm running code on my Cirrus fork over and over.

In order to force a build, I've just been pushing empty commits:

```
git commit --allow-empty -m "force build"
```

Randomly on one I got this failure on the `analyze` step:

```
🕐 ELAPSED TIME: 0:00:00.199270 for git diff -U0 --no-color --name-only 2b14ac1efcaf353623cec7503e8374de91d95562 -- *.dart *.cxx *.cpp *.cc *.c *.C *.h *.java *.mm *.m *.yml in .: 
⏩ RUNNING: cd .; grep --line-number --extended-regexp [[:blank:]]$ packages/flutter_tools/test/integration/test_driver.dart 
grep: : No such file or directory
🕐 ELAPSED TIME: 0:00:00.015731 for grep --line-number --extended-regexp [[:blank:]]$ packages/flutter_tools/test/integration/test_driver.dart  in .: 
Whitespace detected at the end of source code lines.
Please remove:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 2 (expected: 1).
Command: grep --line-number --extended-regexp [[:blank:]]$ packages/flutter_tools/test/integration/test_driver.dart 
Relative working directory: .
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Cirrus: https://cirrus-ci.com/task/5153630432788480
(Empty) Commit: https://github.com/DanTup/flutter/commit/5036b47c3976b002b8964e0eec596dfcef405165

The previous build (which didn't error, but should be identical) is https://cirrus-ci.com/task/5084666679787520

@gspencergoog

**Comment by gspencergoog** [comment]
That is odd.  Did `packages/flutter_tools/test/integration/test_driver.dart` exist in your fork?  It may have been determining the fork point incorrectly.

**Comment by DanTup** [comment]
Yep, and I modified it a few changesets before:

First changeset (modified that file):
https://github.com/DanTup/flutter/commit/945d4e637d63cdbc53a11252c40e9dffbdaf208c
Analyze passed

Second changeset (empty):
https://github.com/DanTup/flutter/commit/466834324b521b2f4c1943cb62c1f12aa193e354
Analyze passed

Third changeset (empty):
https://github.com/DanTup/flutter/commit/5036b47c3976b002b8964e0eec596dfcef405165
Analyze failed with this error

**Comment by zoechi** [comment]
Is this still relevant?

**Comment by DanTup** [comment]
I doubt it, I'm pretty sure the formatting checks have been improved at least a few times since then and I haven't seen it. We can re-open if we see it misfire again.
