### ISSUE TITLE
Change links in Flutter docs pointing to 'Getting Started' for installation/setup instructions. Point to 'Flutter Setup' page instead.

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#2112]
Fix any old references pointing to the Getting Started for installation-related instructions.
Instead, they should link to the 'Flutter Setup' page (https://flutter.io/setup) as the central location for installation/configuration steps.

**Comment by Hixie** [comment]
I'm going to close this on the basis that we don't know which links this referred to and we'll fix them as we find them.
