### ISSUE TITLE
TextField pop up menu internationalization on iOS not support

### ISSUE THREAD

**Issue by songfei** [flutter/flutter#21124]
TextField, on iOS, long press pop-up menu, does not support internationalization,

 I tried to modify the code, https://github.com/flutter/flutter/pull/21105

But analyze fail, 

Dependency loop: cupertino depends on material depends on cupertino

MaterialLocalizations class in Material ,I want to know why either design.

and can Cupertino be internationalized in another way?

**Comment by xster** [comment]
closed in #22443
