### ISSUE TITLE
Exception getting access token Flutter google signing

### ISSUE THREAD

**Issue by davidgalarza** [flutter/flutter#21127]
Hello I'm trudging to authenticate users using google_sign_in plugin and firebase official plugin, but I'm getting this error when try to authenticate.

ERROR GETTING TOKEN

```
E/flutter (28678): Exception getting access token
E/flutter (28678): java.util.concurrent.ExecutionException: com.google.android.gms.auth.GoogleAuthException: Unknown
E/flutter (28678):      at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
E/flutter (28678):      at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
E/flutter (28678):      at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
E/flutter (28678):      at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$3.run(GoogleSignInPlugin.java:337)
E/flutter (28678):      at io.flutter.plugins.googlesignin.BackgroundTaskRunner$1.run(BackgroundTaskRunner.java:62)
E/flutter (28678):      at android.os.Handler.handleCallback(Handler.java:739)
E/flutter (28678):      at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter (28678):      at android.os.Looper.loop(Looper.java:145)
E/flutter (28678):      at android.app.ActivityThread.main(ActivityThread.java:6066)
E/flutter (28678):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28678):      at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (28678):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
E/flutter (28678):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
E/flutter (28678): Caused by: com.google.android.gms.auth.GoogleAuthException: Unknown
E/flutter (28678):      at com.google.android.gms.auth.zzh.zze(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.zzd(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.zze(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.getToken(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.zzg.getToken(Unknown Source)
E/flutter (28678):      at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
E/flutter (28678):      at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$2.call(GoogleSignInPlugin.java:327)
E/flutter (28678):      at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$2.call(GoogleSignInPlugin.java:322)
E/flutter (28678):      at io.flutter.plugins.googlesignin.BackgroundTaskRunner$2.run(BackgroundTaskRunner.java:84)
E/flutter (28678):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/flutter (28678):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/flutter (28678):      at java.lang.Thread.run(Thread.java:818)
E/flutter (28678): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (28678): PlatformException(exception, Unknown, null)
E/flutter (28678): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:544:7)
E/flutter (28678): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
E/flutter (28678): <asynchronous suspension>
E/flutter (28678): #2      GoogleSignInAccount.authentication (package:google_sign_in/google_sign_in.dart:65:36)
E/flutter (28678): <asynchronous suspension>`
```
Here is my code:

```dart
static Future<FBApi> signInWithGoogle() async {
final GoogleSignInAccount googleUser = await _googleSignin.signIn();

final GoogleSignInAuthentication googleAuth =
    await googleUser.authentication;


  final FirebaseUser user = await _auth.signInWithGoogle(
      idToken: googleAuth.idToken, accessToken: googleAuth.accessToken);


  assert(user.email != null);
  assert(user.displayName != null);

  assert(await user.getIdToken() != null);


  final FirebaseUser currenUser = await _auth.currentUser();

  assert(user.uid == currenUser.uid);

  return FBApi(user);
}
```
I read that same problem is caused when miss the SHA1 but I have correctly configured for production and debug key.

![](https://i.stack.imgur.com/Pdqow.png)

I update my google-services.json to before compile.

Any idea?

**Comment by zoechi** [comment]
Can you please add the exception as text so that it is searchable and not cut off in the midst of the lines.
Also please add the output of `flutter doctor -v`.

**Comment by davidgalarza** [comment]
I don't know why that happens, when I recently notice than on android emulator and other devices (android 6.0 - 8.0) it works like a charm, but on my device (android 5.0) I get the error.
Flutter doctor:
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.5 17F77, locale es-EC)
    • Flutter version 0.6.0 at /Users/davidgalarza/development/flutter
    • Framework revision 9299c02cf7 (13 days ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/davidgalarza/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
> on my device (android 5.0)

Can you please provide more information about that device?
`flutter doctor -v` adds some info at the end if the device is connected.

**Comment by davidgalarza** [comment]
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.5 17F77, locale es-EC)
    • Flutter version 0.6.0 at /Users/davidgalarza/development/flutter
    • Framework revision 9299c02cf7 (13 days ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/davidgalarza/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • ALE L23 • G7T7N15B14005901 • android-arm64 • Android 5.0.1 (API 21)

**Comment by cyanglaz** [comment]
@davidgalarza It seems to be very device specific? Are you still experiencing the issue?

**Comment by kroikie** [comment]
@davidgalarza

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/686. Any further collaboration will be done there.

**Comment by nerder** [comment]
@cyanglaz from our finding yes seems to happen only on a specific device, still no clue for this issue?
