### ISSUE TITLE
Show Google Map within Flutter Widget

### ISSUE THREAD

**Issue by GaneshShiroleScorg** [flutter/flutter#21121]
![screenshot_2018-08-28-20-25-50-371_com olacabs customer](https://user-images.githubusercontent.com/26405663/44735852-36f7ce80-ab0b-11e8-951e-6484760d0937.png)

Not able to achieve like Google Map within Flutter Widgets like Ola uber android app UI. check screen shot for reference.

**Comment by zoechi** [comment]
Closing as dup of #21101
