### ISSUE TITLE
[Material] Include a no paint Rounded Corner Border option for InputDecoration 

### ISSUE THREAD

**Issue by tianlunlee** [flutter/flutter#21126]
There currently isn't code in `input_border.dart` that allows `InputDecoration` to have a `border` that is both rounded and has no outline. 

No Outline:
<img width="256" alt="no border" src="https://user-images.githubusercontent.com/13839358/44743112-92a46680-aacf-11e8-9dbc-10e2a8435e72.png">

Rounded Corners, with Outline: 
<img width="256" alt="outline border" src="https://user-images.githubusercontent.com/13839358/44743113-92a46680-aacf-11e8-8ebb-b8ddf18862c9.png">

Rounded Corners, no Outline: 
<img width="256" alt="rounded corners" src="https://user-images.githubusercontent.com/13839358/44743111-92a46680-aacf-11e8-9def-023f70d09a8f.png">

**Comment by Hixie** [comment]
Sounds like the PR above fixes this.
