### ISSUE TITLE
How can I add my custom path location of Android sdk to flutter?

### ISSUE THREAD

**Issue by MdMahadiaHossain** [flutter/flutter#21122]
I have set my android sdk to D drive in windows 8.1. Now how can I show the path of sdk to the flutter?

**Comment by zoechi** [comment]
Looks like https://stackoverflow.com/questions/52062907/how-can-i-build-flutter-android-app-with-custom-android-sdk-and-ndk-path-and-add

**Comment by zoechi** [comment]
Perhaps 
```sh
flutter config
```
is what you are looking for

**Comment by MdMahadiaHossain** [comment]
flutter config is working. I have another question- how can I tell flutter about memuplay emulater?

**Comment by MdMahadiaHossain** [comment]
Leave a comment

**Comment by MdMahadiaHossain** [comment]
Done
