### ISSUE TITLE
Request sample code for popular API docs

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#21136]
According to analytics, the following API docs are quite popular but they don't currently have any sample code. These are easy tasks to start contributing to the Flutter repo. Please refer to [Flutter's style guide ](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#provide-sample-code) if you're interested in [contributing](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md) a snippet. 

- [x] https://docs.flutter.io/flutter/material/Scaffold-class.html
- [ ] https://docs.flutter.io/flutter/material/Icons-class.html
- [x] https://docs.flutter.io/flutter/material/RaisedButton-class.html
- [x] https://docs.flutter.io/flutter/material/TextField-class.html
- [ ] https://docs.flutter.io/flutter/widgets/Image-class.html
- [x] https://docs.flutter.io/flutter/widgets/Icon-class.html
- [x] https://docs.flutter.io/flutter/material/BottomNavigationBar-class.html
- [x] https://docs.flutter.io/flutter/widgets/Expanded-class.html
- [x] https://docs.flutter.io/flutter/widgets/Stack-class.html
- [x] https://docs.flutter.io/flutter/widgets/Form-class.html
- [x] https://docs.flutter.io/flutter/material/FlatButton-class.html
- [ ] https://docs.flutter.io/flutter/material/ThemeData-class.html
- [x] https://docs.flutter.io/flutter/material/DropdownButton-class.html
- [x] https://docs.flutter.io/flutter/material/TextFormField-class.html

**Comment by MisterJimson** [comment]
Where in the repo are these docs? I took a quick look around and couldn't find them.

**Comment by zoechi** [comment]
@MisterJimson They are mixed with the code (comments that start with `///`)
https://github.com/flutter/flutter/blob/5177a37fe28a6828e48a68f5caa1dd0281884153/packages/flutter/lib/src/material/scaffold.dart#L657-L691

**Comment by MisterJimson** [comment]
They don't seem to match with the web pages in this issue.

For example, the Scaffold API doc webpage has these sentences not present in the code.

> The color of the Material widget that underlies the entire Scaffold
> This class provides APIs for showing drawers, snack bars, and bottom sheets
> Creates the mutable state for this widget at a given location in the tree

And these sentences from the repo's code Scaffold file are not present on the web page.

> The geometry of the [Scaffold] after all its contents have been laid out
> Creates a copy of this [ScaffoldGeometry] but with the given fields replaced with

This issue is about updating the API docs webpages, from what I can see there does not seem to be a direct relationship between the docs in the code and on the website, unless I am missing something.

**Comment by InMatrix** [comment]
@MisterJimson Sorry about the confusion. The reason you saw the discrepancy between the docs and the code is that docs.flutter.io is generated from the beta branch of Flutter, but the code you were looking at is on the master branch. The API docs for the master branch lives at https://master-docs-flutter-io.firebaseapp.com/

**Comment by NPKompleet** [comment]
@InMatrix I just added some sample code for BottomNavigationBar and Scaffold. Would more later.

**Comment by Piinks** [comment]
Updated/Checked-off the completed sample code snippets. ref: master docs

**Comment by iapicca** [comment]
Hi @InMatrix  cc @Piinks 
from the [list above](https://github.com/flutter/flutter/issues/21136#issue-354924604) are missing only 
[Image class](https://api.flutter.dev/flutter/widgets/Image-class.html), [Icon class](https://api.flutter.dev/flutter/material/Icons-class.html) and [ThemeData class](https://api.flutter.dev/flutter/material/ThemeData-class.html), 
now the docs offer a brief, but representative, code sample

Is it safe to close this issue?
Thank you

**Comment by Piinks** [comment]
> Hi @InMatrix cc @Piinks
> from the [list above](https://github.com/flutter/flutter/issues/21136#issue-354924604) are missing only
> [Image class](https://api.flutter.dev/flutter/widgets/Image-class.html), [Icon class](https://api.flutter.dev/flutter/material/Icons-class.html) and [ThemeData class](https://api.flutter.dev/flutter/material/ThemeData-class.html),
> now the docs offer a brief, but representative, code sample
> 
> Is it safe to close this issue?
> Thank you

Awesome! LGTM, and thank you for checking! I think we can close this now. 🎉
