### ISSUE TITLE
Firestore to be able to update individual field in an array using arrayUnion

### ISSUE THREAD

**Issue by LiveRock** [flutter/flutter#21148]
Firestore to be able to update individual field in an array using arrayUnion

So far, no easy way to just update a single field in a array inside Firestore.

**Comment by zoechi** [comment]
It looks like https://github.com/flutter/plugins/pull/760 is supposed to fix that.

**Comment by johnson-yeap** [comment]
I can't seem to use FieldValue.arrayUnion().

java.lang.IllegalArgumentException: Invalid data. Nested arrays are not supported

**Comment by JamesMcIntosh** [comment]
@zoechi I have been experiencing the same sort of problem but with just a normal object.

After a quick inspection of the code I think that this may be a bug.

The java version of the method is `FieldValue.arrayUnion(Object ... values)` which accepts an Object varargs while the code in the plugin is `return FieldValue.arrayUnion(readValue(buffer));` which I believe delivers a List as a single vararg.

see the FirestoreMessageCodec.readValueOfType()  approx line 642 in https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java

**Comment by JamesMcIntosh** [comment]
I just tested this checking out the plugins and changing the method signature in field_value.dart to only accept a single `dynamic` instead of a `List<dynamic>` and it updates the array correctly.

https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/lib/src/field_value.dart

**Comment by JamesMcIntosh** [comment]
Created pull request https://github.com/flutter/plugins/pull/795

**Comment by pulyaevskiy** [comment]
Nice find, @JamesMcIntosh !

Just out of curiosity, wondering if you also tested it with array of server timestamps and if it works or not?

**Comment by JamesMcIntosh** [comment]
It appears not, I get `PlatformException(error, Invalid data. FieldValue.serverTimestamp() is not currently supported inside arrays, null)`

This was my attempt at writing the data.
```

final data = <String, dynamic>{
 'arraydata': ["Test data", FieldValue.serverTimestamp()],
};
final tsRef = Firestore.instance.collection('TimestampTest');
tsRef.document("TestDocument").setData(data, merge: true);
```

**Comment by pulyaevskiy** [comment]
Great, thanks for confirming!

**Comment by zoechi** [comment]
Is there still work to do or is this fixed?

**Comment by JamesMcIntosh** [comment]
I think that the problem in this ticket is now resolved by the PR https://github.com/flutter/plugins/pull/795 

The conversation about `FieldValue.serverTimestamp() is not currently supported inside arrays` in this ticket is a separate upstream issue with Firestore itself. If it "needs" to be tracked should probably be on a different ticket.

**Comment by zoechi** [comment]
This should be fixed.
If you're still seeing this please add a comment to have the issue reopened.

**Comment by kroikie** [comment]
@LiveRock

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/685. Any further collaboration will be done there.

**Comment by JayM96** [comment]
Hello,
@zoechi @kroikie  @JamesMcIntosh Can you tell me how to update nested fields in firestore ?
Currently, i am using the code like,

await testReference.document(testID).updateData({
       "testMessage": {
         "$index": FieldValue.arrayUnion([
           {
             "dataList": FieldValue.arrayUnion([currentUserID]),
           }
         ])
       },
     });
But, it gives me an error like "Unhandled Exception: PlatformException(error, Invalid data. FieldValue.arrayUnion() can only be used with set() and update(), null)"
Thanks.

**Comment by AlexMainaMunyua** [comment]
I also got the same error "Unhandled Exception: PlatformException(error, Invalid data. FieldValue.arrayUnion() can only be used with set() and update(), null)"

anyone has solved it?
