### ISSUE TITLE
Discard and create the app again programmatically

### ISSUE THREAD

**Issue by hui1103** [flutter/flutter#21144]
Hi All,

My app uses server responses when generating(building) different screens. I get the server responses at initState. 

Some actions in the app require the app resetting(both UI and new server responses). 

Rebuilding the app by
- runApp(new MyApp()); (, or rebuilding all screens)
is fine to refresh the UI widgets.

However, it cannot refresh the screens' state which holds the server responses.

May I know is it possible to do something like flutter markneedsbuild?
I would like to trigger both initState and build when the screen is visited again. 
Does it violate the flutter design/flow?

If initState should not be called like this, I think a simple way should be discarding all the previous screens and states. Everything starts over again.
Is there any way to discard the old MyApp and re-create a new MyApp?

Many thanks for your reading and any of help!

**Comment by zoechi** [comment]
Just call `setState()` on a widget or its parent.

**Comment by zoechi** [comment]
The easiest way is to assign a GlobalKey. That allows you to access it from everywhere.
You can also use a Stream or something like Redux (that provides streams) that notify all subscribers.

I think this question should better be moved to StackOverflow or any of the other channels mentioned in https://flutter.io/support/

**Comment by hui1103** [comment]
Thanks for your help!
