### ISSUE TITLE
[Feature Request] Using System PIN/Password/Pattern for Authentication

### ISSUE THREAD

**Issue by keshava19** [flutter/flutter#21147]
I can't find any package that will allow me to use the PIN/Password/Pattern lock that the user has setup in either Android or IOS device for app authentication.

There is local_auth package for the Biometrics authentication and that works fine, but when the user does not have Biometric scanner then it becomes a problem.

Is there any way to authenticate with the device security that the user has already setup ??

If you didn't get what I'm trying to say, try installing Google Tez app it has the authentication that I am wanting to implement.

**Comment by zoechi** [comment]
As far as I know not out-of-the-box, but you can always make native functionality available to Flutter using https://flutter.io/developing-packages/#plugin

**Comment by mehmetf** [comment]
Unfortunately, this is not possible. Neither iOS nor Android provide a way for *applications* to authenticate using a system-set PIN and password. It is up to the App to manage its own PIN which means you need to have your own PIN setup screens and mechanisms to store it (preferably not on device).

For the same reason you can't use any of the existing accounts to authenticate your app either (e.g. asking user their Google password). There *are* apps that do this (such as Play Store when authenticating purchases) but these are highly privileged apps that belong to the ecosystem and you are not allowed to access those APIs.

**Comment by Henry-Keys** [comment]
@mehmetf, although the only way to use local authentication in iOS it's through biometric inputs, that's not entirely true in Android.

Android provides KeyguardManager (API >= 23) and BiometricPrompt (API >= Q) for local authentication using with PIN, Password, Pattern.

It would be awesome if local_auth adds supports for these authentication methods in Android.
Cheers

**Comment by mehmetf** [comment]
That's interesting! I did not know about KeyguardManager's capability to do that.

I do have an action item to migrate this plugin to use https://developer.android.com/reference/androidx/biometric/BiometricPrompt.html but it seems androidx does not support device credential yet.

I would be happy to review a PR if you would like to send one my way though!

**Comment by Henry-Keys** [comment]
> That's interesting! I did not know about KeyguardManager's capability to do that.
> 
> I do have an action item to migrate this plugin to use https://developer.android.com/reference/androidx/biometric/BiometricPrompt.html but it seems androidx does not support device credential yet.
> 
> I would be happy to review a PR if you would like to send one my way though!

It would be a pleasure to contribute. I'll fork the project and send a PR to you guys.

**Comment by pawarlalit29** [comment]
> @mehmetf, although the only way to use local authentication in iOS it's through biometric inputs, that's not entirely true in Android.
> 
> Android provides KeyguardManager (API >= 23) and BiometricPrompt (API >= Q) for local authentication using with PIN, Password, Pattern.
> 
> It would be awesome if local_auth adds supports for these authentication methods in Android.
> Cheers

Can you provide sample flutter application for local auth
Thanks in advance

**Comment by Mohsin92** [comment]
Hi, 
Is this feature is available for flutter before open app prompt for device PIN/PASSWORD/PATTERN?

as in android by following code can be achieve.

`if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
    KeyguardManager km = (KeyguardManager) getSystemService(KEYGUARD_SERVICE);

    if (km.isKeyguardSecure()) {
        Intent authIntent = km.createConfirmDeviceCredentialIntent(getString(R.string.dialog_title_auth), getString(R.string.dialog_msg_auth));
        startActivityForResult(authIntent, INTENT_AUTHENTICATE);
    }
}`

`// call back when password is correct  
@Override  
protected void onActivityResult(int requestCode, int resultCode, Intent data) {  
    if (requestCode == INTENT_AUTHENTICATE) {  
        if (resultCode == RESULT_OK) {  
            //do something you want when pass the security  
        }  
    }  
}`
