### ISSUE TITLE
Document that rebuilding the Scaffold doesn't rebuild its BottomSheet

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2115]
In the example app below the values of the bottom sheet checkboxes are reflected in the application's ToolBar.

The checkbox onChanged() callbacks can't rely on just calling setState() because rebuilding the Scaffold doesn't cause its bottom sheet to be rebuilt.

The two onChanged() callbacks demo how one can handle this. Neither of them is super-obvious.

It might be better to change Scaffold to always rebuild its bottom sheets.

Note also: the checkbox0 approach was lifted from list_demo.dart. The checkbox1 approach comes from stock_menu.dart.

```
import 'package:flutter/material.dart';

class DrawBottomSheet extends StatefulComponent {
  DrawBottomSheet({ Key key }) : super(key: key);

  DrawBottomSheetState createState() => new DrawBottomSheetState();
}

class DrawBottomSheetState extends State<DrawBottomSheet> {
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
  ScaffoldFeatureController _bottomSheet;
  bool _checkboxValue0 = false;
  bool _checkboxValue1 = false;

  void showBottomSheet() {
    _bottomSheet = _scaffoldKey.currentState.showBottomSheet((_) {
      return new Container(
        decoration: new BoxDecoration(
          border: new Border(top: new BorderSide(color: Colors.black26, width: 1.0))
        ),
        child: new Padding(
          padding: const EdgeDims.all(32.0),
          child: new Column(
            justifyContent: FlexJustifyContent.collapse,
            children: <Widget>[
              new ListItem(
                primary: new Text('ScaffoldFeatureController'),
                right: new Checkbox(
                  value: _checkboxValue0,
                  onChanged: (bool value) {
                    setState(() {
                      _checkboxValue0 = value;
                    });
                    //This line causes the bottom sheet to be rebuilt:
                    _bottomSheet.setState(() { });
                  }
                )
              ),
              new ListItem(
                primary: new Text('StatefulBuilder'),
                right: new StatefulBuilder(
                  builder: (BuildContext context, StateSetter checkboxSetState) {
                    return new Checkbox(
                      value: _checkboxValue1,
                      onChanged: (bool value) {
                        setState(() {
                          _checkboxValue1 = value;
                        });
                        //This line causes the checkbox to be rebuilt:
                        checkboxSetState(() { });
                      }
                    );
                  }
                )
              )
            ]
          )
        )
      );
    });
  }

  Widget build(BuildContext context) {
    return new Scaffold(
      key: _scaffoldKey,
      toolBar: new ToolBar(center: new Text("Checkboxes: $_checkboxValue0, $_checkboxValue1")),
      body: new Center(
        child: new RaisedButton(
          onPressed: showBottomSheet,
          child: new Text('Show BottomSheet')
        )
      )
    );
  }
}

void main() {
  runApp(new MaterialApp(
    title: 'Draw BottomSheet',
    routes: <String, RouteBuilder>{
      '/': (RouteArguments args) => new DrawBottomSheet(),
    }
  ));
}
```

**Comment by Hixie** [comment]
The difficulty in particular is with how to handle changes to the fields in the DrawBottomSheetState that are triggered from outside the bottom sheet. It's not obvious that they need to track the existence of a bottom sheet and call setState() on it, since the state is in the app. It becomes more obvious that this is what you need to do if you imagine calling Scaffold.of(context).showBottomSheet() from way inside some other component, since then it's obvious that setting state on that component won't rebuild the bottom sheet.

**Comment by Hixie** [comment]
Assigning to myself to determine if we should fix this or not.

**Comment by Hixie** [comment]
I'll document it better but I don't think there's much more we can do. It doesn't really make sense to rebuild it if the Scaffold specifically gets rebuilt, because the scaffold is a more or less arbitrary player in this game from the perspective of the app.

**Comment by thelazyindian** [comment]
well this issue is also in modal bottom sheet so how can we run setState so that it rebuilds the modalBottomSheet

**Comment by Hixie** [comment]
Pass a StatefulBuilder as the root widget you pass to showModalBottomSheet, then call its setState.

**Comment by thelazyindian** [comment]
@Hixie can you give an example?

**Comment by Hixie** [comment]
If you look for StatefulBuilder in the repo you'll find some examples of it being used in test.

**Comment by thelazyindian** [comment]
Thanks. Works fine now.

**Comment by gowsikraja** [comment]
Hi @theankurkedia can you give the example for modalBottomSheet or bottomSheet .

**Comment by yy1300326388** [comment]
```
  String update = '更新';

  ///选择省市
  void locationSheet() {
//    showModalBottomSheet(
//        context: context,
//        builder: (BuildContext context) {
//          return LocationPicker();
//        });

    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return StatefulBuilder(builder: (context,state){
            return Center(
              child: FlatButton(
                  onPressed: () {
                    updated(state);
                  },
                  child: new Text('$update')),
            );
          });
        });
  }

  Future<Null> updated(StateSetter updateState) async {
    updateState(() {
      update = '更新后';
    });
  }
```

**Comment by Akashdeep312** [comment]
hi everyone i'm new to flutter and have an list with two items whenever i try to delete last item with bottomSheet it gives error


The following RangeError was thrown building BottomSheet(dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#35052], _InheritedTheme], state: _BottomSheetState#5503c):
RangeError (index): Invalid value: Only valid value is 0: 1

The relevant error-causing widget was
    MaterialApp 
package:test1/main.dart:24
When the exception was thrown, this was the stack
#0      List.[]  (dart:core-patch/growable_array.dart:149:60)
#1      List.elementAt  (dart:core-patch/growable_array.dart:358:16)
#2      _MyAppState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:test1/main.dart:46
#3      _BottomSheetState.build 
package:flutter/…/material/bottom_sheet.dart:212
#4      StatefulElement.build 





and here's my code  


import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    MyApp(),
  );
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<Item> list2 =
      List<Item>.generate(2, (i) => new Item("name $i", false, Colors.red));
  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: ListView.separated(
          itemCount: list2.length,
          itemBuilder: (context, index) {
            return ListTile(
              onTap: () {
                showModalBottomSheet<void>(
                    backgroundColor: Colors.white,
                    context: context,
                    builder: (BuildContext context) {
                      return Container(
                        height: (MediaQuery.of(context).size.height / 3) + 35,
                        margin: EdgeInsets.only(top: 4),
                        color: Colors.white,
                        child: Column(
                          children: <Widget>[
                            
                            !list2.elementAt(index).isColorAdded
                                ? InkWell(
                                    child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceEvenly,
                                      children: <Widget>[
                                        Padding(
                                          padding: const EdgeInsets.all(4),
                                          child: Text(
                                            "Add to data",
                                            style: TextStyle(
                                                fontSize: 16,
                                                backgroundColor: Colors.white,
                                                color: Colors.blue,
                                                fontWeight: FontWeight.w500),
                                          ),
                                        ),
                                      ],
                                    ),
                                    onTap: () {
                                      Navigator.pop(context);
                                    },
                                  )
                                : InkWell(
                                    child: Row(
                                      mainAxisAlignment:
                                          MainAxisAlignment.spaceEvenly,
                                      children: <Widget>[
                                        Padding(
                                          padding: const EdgeInsets.all(4),
                                          child: Text(
                                            "Remove from Data",
                                            style: TextStyle(
                                                fontSize: 16,
                                                backgroundColor: Colors.white,
                                                color: Colors.blue,
                                                fontWeight: FontWeight.w500),
                                          ),
                                        ),
                                      ],
                                    ),
                                    onTap: () {
                                      Navigator.pop(context);
                                      setState(() {
                                        list2.removeAt(index);
                                      });
                                    },
                                  ),

                            Divider(
                              color: Color(0xffDCDCDC),
                              thickness: 0.5,
                            ),
                            InkWell(
                              child: Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceEvenly,
                                children: <Widget>[
                                  Padding(
                                    padding: const EdgeInsets.all(4),
                                    child: Text(
                                      "Remove Excercise",
                                      style: TextStyle(
                                          fontSize: 16,
                                          backgroundColor: Colors.white,
                                          color: Colors.blue,
                                          fontWeight: FontWeight.w500),
                                    ),
                                  ),
                                ],
                              ),
                              onTap: () {
                                list2.removeAt(index);
                                Navigator.pop(context);
                              },
                            ),
                          ],
                        ),
                      );
                    });
              },
              title: Text('${list2[index].name}'),
            );
          },
          separatorBuilder: (BuildContext context, int index) {
            return Divider(
              color: Colors.red,
            );
          },
        ),
      ),
    );
  }
}

class Item {
  String name;
  bool isColorAdded;
  var color;

  Item(this.name, this.isColorAdded, this.color);
}
