### ISSUE TITLE
Flutter ecommerce slider

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#21156]
Is there any plugin or sample code for creating below image slider

![image](https://user-images.githubusercontent.com/13333370/44783953-986e7a80-aba9-11e8-98dc-0f8d1d9c46cd.png)

**Comment by zoechi** [comment]
Please ask such support questions in one of the channels listed in https://flutter.io/support

(not on StackOverflow in this case, they don't like questions about where to find tutorials, resources, libraries, ...)

**Comment by rahulmishra1991** [comment]
OK Thanks..
