### ISSUE TITLE
flutter attach should support a detach command and default to detaching (not terminating the app) on SIGINT/SIGTERM

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#21154]
Currently when you run `flutter attach`, the only ways of exiting are pressing `q` to quit, or Ctrl+C to sent SIGINT. Both of these result in the Android app terminating. It seems like these should instead of "detach" (and that the description of what pressing `q` does should probably be reworded for the attach case).

(@matthew-carroll I'm making some assumptions here, not sure who is best to confirm this is what we're aiming for?)

(@devoncarew do we need to add a new `app.detach` command to the daemon, or should we just use `app.stop`? I don't think we'd ever need both together - I don't think it makes sense to terminate an app we only attached to, but the name `stop` seems slightly weird for detaching).

**Comment by DanTup** [comment]
Related to discussion in https://github.com/flutter/flutter/pull/21106. Based on @stevemessick's comments I think we may need to support both an `app.detach` and an `app.stop`? If so, we also need to make a decision on which one is correct behaviour for if the app is just terminated (eg. SIGINT/SIGTERM).

**Comment by DanTup** [comment]
Based on discussions with @devoncarew we need:

- An `app.detach` command for `--machine` that detaches without terminating the app (it should be possible to detach and re-attach afterwards)
- The signal handling code should default to detaching when you attached to an existing process
- The console runner should have keys/instructions for both terminating and detaching

**Comment by DanTup** [comment]
@devoncarew @stevemessick 

Any opinions on what should happen with the `app.stop` event during a detach? Normally when we send an `app.stop` request, we get both an event (saying the app stopped) and a response to the request.

With current code, detach also sends a `stop` event. It's simple to change this to send `detach` instead, but it means editors will have to specifically look for that in addition to `stop` in disconnect/terminate code (I don't know whether they'd ever do anything different, so not sure if the difference is worthwhile):

```
==> [{"id":1,"method":"app.detach","params":{"appId":"7857543e-2686-4555-91ac-8b95469a5040"}}]
<== [{"id":1,"result":true}]
<== [{"event":"app.stop","params":{"appId":"7857543e-2686-4555-91ac-8b95469a5040"}}]
```

**Comment by DanTup** [comment]
(though now I'm thinking the same thing applies to the `app.start` event.. if we think we should use different events for stop/detach then maybe start/attach should be different, so I think probably leaving the stop might make most sense?)

**Comment by stevemessick** [comment]
@DanTup I think having matched pairs is the right way to go. I'm not yet sure if IntelliJ has a need to know stop/detach are different, but it might and it isn't hard to handle both.
