### ISSUE TITLE
NavigatorState.pushReplacement with the previous route animating out

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#21167]
Is there any method equivalent to pushReplacement that animates the previous route out?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
@Hixie

**Comment by xqwzts** [comment]
@christian-muertz `popAndPushNamed()` should do that: https://docs.flutter.io/flutter/widgets/Navigator/popAndPushNamed.html

**Comment by christian-muertz** [comment]
@xqwzts I want more like a push and then pop. I want the previous route secondary animation to run not the primary :D

**Comment by Piinks** [comment]
> @xqwzts I want more like a push and then remove all below. 

Hi @christian-muertz, have you tried the `pushAndRemoveUntil` method? Please let us know if you are still experiencing an issue.

**Comment by christian-muertz** [comment]
Nope no problems anymore
