### ISSUE TITLE
TextField with TextInputType.number does not replace text selection

### ISSUE THREAD

**Issue by tsvehagen** [flutter/flutter#21162]
I noticed a problem when wanting to have a TextField selection and then replacing the selected text when typing.

I tried the Flutter Gallery app v0.5.1 and it has the same problem.

## Steps to Reproduce

1. Open Flutter Gallery v0.5.1
2. Go to Material -> Text fields
3. Write something in the Salary input
4. Select some numbers and then start writing new ones

I would expect the selected text to be replaced by the new one but instead it is added before the selection. The same behavior is seen on TextInputType.number and TextInputType.phone but not on TextInputType.text for example.

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
cc @jslavitz

**Comment by zoechi** [comment]
Looks like a dup of #18853

**Comment by tsvehagen** [comment]
Oh, yeah it's a duplicate for sure... I guess I didn't look hard enough for a similar issue before posting :)
