### ISSUE TITLE
Flutter on windows 7 sp1 32 bit operating system

### ISSUE THREAD

**Issue by AbdulHadiBhagat** [flutter/flutter#21169]
[hello_world] flutter packages get
This version of F:\Dow\flutter_windows_v0.6.0-beta\flutter\bin\cache\dart-sdk\bin\dart.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
exit code 1

**Comment by zoechi** [comment]
How did you install? `git clone` or download zip?

**Comment by AbdulHadiBhagat** [comment]
Download zip

**Comment by jvashiri** [comment]
This version of C:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
