### ISSUE TITLE
map_view incompatible with flutter_test

### ISSUE THREAD

**Issue by selassie-eye** [flutter/flutter#21177]
Seems like map_view cannot work with Dart 2 yet.

![screen shot 2018-08-29 at 2 41 10 pm](https://user-images.githubusercontent.com/21206427/44809677-6820df00-ab9d-11e8-93f6-f33e12c611aa.png)

**Comment by zoechi** [comment]
Dup or https://github.com/google/uri.dart/issues/34
Workaround - add this to `pubspec.yaml`
```yml
dependency_overrides:
  quiver: ^2.0.0
```
