### ISSUE TITLE
Upgrade to 0.6 beta completely broke my app

### ISSUE THREAD

**Issue by vladaman** [flutter/flutter#21173]
I did flutter upgrade and my app currently does not compile due to numerous problems.

1. In Android Studio I get error 
```
Android dependency 'com.android.support:support-core-utils' has different version for the compile (26.1.0) and runtime (27.1.1) classpath
```
2. When trying to run the app I also get dependency issues - I assume many modules are not compatible.
```
Because my_app depends on geohash any which requires SDK version >=1.0.0 <2.0.0, version solving failed.
pub get failed (1)
```

flutter doctor
```
Software/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by DQvsRA** [comment]
Had same problem.
Adding this to the package `pubspec.yaml` solved the issue:
```
environment:
  sdk: '>=2.0.0 <3.0.0'
```

**Comment by sir-boformer** [comment]
To fix error 1, add this to your build.gradle :

```gradle
dependencies {
    ...
    implementation 'com.android.support:support-v4:27.1.1'
}
```

**Comment by vladaman** [comment]
Well, same thing is with libraries such as:
* Dartson
* Guinness
* Geohash

and probably many others. Any quick fix for now, until all libraries will reflect this change or do I have to roll back to 0.5x flutter?

**Comment by zoechi** [comment]
Well, same thing is with libraries such as:

Please report in these libraries. They need to publish an updated version that claims compatibility with the Dart version and other new package versions you are using.

You can work around using `dependency_overrides:`
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides 
**At your own risk**

**Comment by zoechi** [comment]
`intl_translation: ^0.17.0` works for me though
