### ISSUE TITLE
Please state in the google_sign_in package that it requires devices to pass SafetyNet

### ISSUE THREAD

**Issue by GroovinChip** [flutter/flutter#21179]
I rooted my Pixel XL today and discovered that my Flutter app, which depends on google sign in to function, would not log in. Please state in the package description that passing SafetyNet is a requirement for the package to work as intended.

**Comment by kroikie** [comment]
@GroovinChip

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/683. Any further collaboration will be done there.

**Comment by kf6gpe** [comment]
Closing as the issue has been moved to FirebaseExtended/flutterfire#683
