### ISSUE TITLE
TextField does not lose input focus when window loses focus.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#21193]
To reproduce (Android):
  - place a flutter app in split screen mode with another app.
  - Begin editing a text field. 
  - Tap into the other app, this will dismiss the keyboard
  - Observe that the text field still appears to have focus, the cursor is blinking et cetera.

What should happen:

Upon focusing the other android app, the Flutter input focus should be reset.

**Comment by jonahwilliams** [comment]
There is potentially another issue here: normally dismissing the keyboard on Android would remove input focus. In the scenario above, tapping into the other android app dismisses the keyboard but this does not trigger the loss of focus.

**Comment by samihaddad** [comment]
The same issue occurs when pushing a new route instead of going to another app. The keyboard is dismissed, but the cursor remains. Or is this intentional behavior for navigation?

**Comment by jonahwilliams** [comment]
@samihaddad  this is specifically related to window focus, that sounds like a separate issue.

**Comment by samihaddad** [comment]
@jonahwilliams got you, thanks.

**Comment by jonahwilliams** [comment]
I'm not currently working on this

**Comment by darshankawar** [comment]
This is replicable. Tested on latest stable (1.20.3) on Samsung S10+ device in split mode and observed that the textfield remains active with cursor.

![21193](https://user-images.githubusercontent.com/67046386/92463258-33fb4280-f1e9-11ea-88dc-5e25ab12f0e3.png)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (2 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

**Comment by exaby73** [comment]
This issue is still reproducible on `Master (3.5.0-12.0.pre.175)`. Updating the labels to reflect the same

**Comment by lukepighetti** [comment]
We're getting bug reports on this. Repro:

Action: tap on TextField
Result: TextField is focused, cursor shown, keyboard shown
Action: background the app
Action: foreground the app
Result: TextField is still focused, cursor shown, keyboard is not visible

You have to tap on the TextField to open the keyboard again

But what's more insidious, is if you use EditableText, you cannot tap on it to get the keyboard back!

**Comment by justinmc** [comment]
This bug also happens in Android's desktop mode.
