### ISSUE TITLE
Allow Cursor customization in a TextFormField

### ISSUE THREAD

**Issue by eoinfogarty** [flutter/flutter#21198]
As a follow up to this PR which allowed a cursor in a TextField to be customized.
https://github.com/flutter/flutter/pull/19317

I think this functionality also needs to be enabled for TextFormFields

## Steps to Reproduce

Use any TextFormField

## Logs
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.7.0, on Mac OS X 10.13.4 17E202, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Android Studio (version 3.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (2 available)

• No issues found!
Process finished with exit code 0
```

**Comment by therenca** [comment]
Is this fixed guys?

**Comment by justinmc** [comment]
Yeah should be good now!  As of the referenced PR above, you can specify `cursorWidth`, `cursorColor`, and `cursorRadius` in a TextFormField.

**Comment by therenca** [comment]
For Flutter version 1.0.0, these parameters are still not available for TextFormField

**Comment by zoechi** [comment]
@therenca you need to switch to another channel like `dev` or wait for a newer `stable` Flutter version.

**Comment by therenca** [comment]
I will wait. Thanks guys.
