### ISSUE TITLE
Add footer to ReorderableListView

### ISSUE THREAD

**Issue by leedstyh** [flutter/flutter#21195]
Works like the `header` way, but after the end of the list.

See: [ReorderableListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html)

**Comment by DebugTheCode** [comment]
Let's hope they'll implement it soon!

**Comment by HVLoc** [comment]
https://pub.dev/packages/implicitly_animated_reorderable_list

**Comment by HVLoc** [comment]
I used GestureDetector and onLongPress: () {} to temporarily disable the ReorderableListView's drag feature in the last widget.

....
 children: <Widget>[
          for (final item in list) _buildItem(item),
          _buildFooter(),
        ],
...

Widget   _buildFooter() {
    return GestureDetector(
      onLongPress: () {},
      key: Key('Footer'),
      child: Container()
  );
}
