### ISSUE TITLE
dart:ui should have a method to push the data to the GPU

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#212]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 19, 2015 at 22:58 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1682_

----

...so that we can call it during the frame as soon as we have the data ready, before we deal with cleanup, scheduling the next frame's animations, etc.

If we do that, we can move the call to GlobalKey._notifyListeners() in Element.finalizeTree() to just be an inline call rather than a call through scheduleMicrotask().

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Wednesday Oct 28, 2015 at 14:18 GMT_

----

`ui.window.render` now lets you signal that you want to push to the GPU but it's not wired up to do that in C++ yet.

**Comment by Hixie** [comment]
Specifically all it does now is:

```cc
void SkyView::Render(Scene* scene) {
  layer_tree_ = scene->takeLayerTree();
}
```

**Comment by Hixie** [comment]
Animator::BeginFrame does the actual pushing:

```dart
rasterizer_->Draw(reinterpret_cast<uint64_t>(layer_tree.release()),
      base::Bind(&Animator::OnFrameComplete, weak_factory_.GetWeakPtr()));
```

**Comment by abarth** [comment]
Yeah, we need to flip things around on the C++ side so that `SkyView::Render` actually sends the layer tree to the GPU thread.

**Comment by abarth** [comment]
Will be fixed in https://github.com/flutter/engine/pull/2603
