### ISSUE TITLE
Issue from website page Working with cached images

### ISSUE THREAD

**Issue by rupert2133** [flutter/flutter#21200]
From URL: https://flutter.io/cookbook/images/cached-images/

As seen in the documentation, the package [](https://pub.dartlang.org/packages/cached_network_image) is not working and also it has analysis errors.

**Comment by zoechi** [comment]
Would you mind posting the output of
```
flutter analyze
```
and
```
flutter doctor
```

**Comment by xqwzts** [comment]
@rupert2133 A new version of CachedNetworkImage [the package in that cookbook article] was released a few hours ago, which should be compatible with the latest flutter beta. It should work fine if you upgrade versions:

You can upgrade by running `flutter packages upgrade`, or change your pubspec to include the latest version:
`cached_network_image: ^0.4.2` and then run `flutter packages get`.
