### ISSUE TITLE
FirebaseAdMobPlugin iPhone ok iPad NG

### ISSUE THREAD

**Issue by Ken1101** [flutter/flutter#21204]
FirebaseAdMobPlugin will display banner without problem on iPhone, but on iPad it will display "FirebaseAdMobPlugin <warning> adView: didFailToReceiveAdWithError: Request Error: No ad to show. (MobileAd <FLTBannerAd: 0x1c000e070> PENDING mobileAdId: 915310470 for: <GADBannerView : 0x13bd31cc0; frame = (0 0; 320 50); clipsToBounds = YES; layer = <CALayer: 0x1c4228ea0 >>) "becomes warning and the banner is not displayed.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ganessaa** [comment]
We also have the same problem.
If we get something we will share it.
https://stackoverflow.com/questions/52136942/ads-are-not-showing-on-ios-devices

**Comment by Ken1101** [comment]
privacy->Adverting->Limit Ad Tracking Admob is now displayed when repeating on and off.
Perhaps it is bad that DeviceID is in the same state?

**Comment by Ken1101** [comment]
I'm sorry, it will only be OK once, then it will be a warning again.

**Comment by ganessaa** [comment]
The AdMob representative did not reply to our question at flutter.
They told us that we should ask this problem at GitHub...=(

This problem has also occurred in iPhone 6 plus and iPhone SE.

**Comment by ganessaa** [comment]
Does your ad still not appear?
Our advertisement was displayed.
Our method might be helpful.
https://stackoverflow.com/questions/52136942/ads-are-not-showing-on-ios-devices

**Comment by collinjackson** [comment]
@KenHashizume can you confirm if you're still experiencing this issue? Was @ganessaa's approach helpfu?

**Comment by kroikie** [comment]
@Ken1101

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/681. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by linturian** [comment]
Any updates? I getting this error for both Banner and interstitial

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
