### ISSUE TITLE
Flutter: command not found

### ISSUE THREAD

**Issue by jehan96** [flutter/flutter#21206]
i know,
this had been asked like few times..
but i don't understand..
i already install flutter
set path
and so on..
but still..
command not found..
what i miss?
i follow step by step installation process

edit: i am using linux..to be specific : ubuntu

**Comment by hariprasadiit** [comment]
whats the output of `echo $PATH`?

**Comment by zoechi** [comment]
How and where did you set the PATH?
If you set it in `.bash_profile` you might need to re-login (or restart your system)

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
