### ISSUE TITLE
first flutter command after install on windows triggers tool rebuild

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#21217]
This is on a brand new Windows VM image:

1. Download a flutter .zip from https://flutter.io/setup-windows/
1. Extract to some folder
1. Run the Flutter Console, `<sdk folder>\flutter_console.bat`
1. Type `flutter -v`

=>

```
C:\Users\mit>flutter
Building flutter tool...
Running pub upgrade...
Manage your Flutter app development.

Common commands:
```

**Comment by christopherfujino** [comment]
Not sure what was happening, but I can confirm this no longer happens, as of v1.13.6. Feel free to re-open if you can repro.
