### ISSUE TITLE
flutter upgrade aborting right after packages/flutter_localizations/lib/src/l10n/material_bs.arb

### ISSUE THREAD

**Issue by slabo** [flutter/flutter#21211]
## Steps to Reproduce

**flutter upgrade --verbose** 
```
flutter upgrade --verbose
[  +30 ms] executing: [C:\Users\nabudarwish\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +93 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[   +5 ms] executing: [C:\Users\nabudarwish\flutter\] git rev-parse --abbrev-ref HEAD
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[   +5 ms] executing: [C:\Users\nabudarwish\flutter\] git ls-remote --get-url origin
[  +62 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +4 ms] executing: [C:\Users\nabudarwish\flutter\] git log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] c7ea3ca377e909469c68f2ab878a5bc53d3cf66b
[   +5 ms] executing: [C:\Users\nabudarwish\flutter\] git log -n 1 --pretty=format:%ar
[  +57 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 3 months ago
[   +1 ms] executing: [C:\Users\nabudarwish\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.5.1-0-gc7ea3ca37
[  +73 ms] executing: [C:\Users\nabudarwish\flutter\] git rev-parse @{u}
[  +88 ms] 9299c02cf708497d6f72edda8efae0bb8340660e
[   +1 ms] Upgrading Flutter from C:\Users\nabudarwish\flutter...
[   +2 ms] executing: [C:\Users\nabudarwish\flutter\] git pull --ff-only
[+3650 ms] error: Your local changes to the following files would be overwritten by merge:
[   +1 ms]      .cirrus.yml
[        ]      AUTHORS
[        ]      CONTRIBUTING.md
[        ]      README.md
[        ]      analysis_options.yaml
[        ]      appveyor.yml
[        ]      bin/flutter.bat
[        ]      bin/internal/engine.version
[        ]      bin/internal/goldens.version
[        ]      bin/internal/update_dart_sdk.ps1
[        ]      dev/automated_tests/flutter_test/exception_handling_expectation.txt
[        ]      dev/automated_tests/flutter_test/filtering_test.dart
[   +1 ms]      dev/automated_tests/flutter_test/test_async_utils_guarded_test.dart
[        ]      dev/automated_tests/flutter_test/trivial_test.dart
[   +2 ms]      dev/automated_tests/flutter_test/trivial_widget_expectation.txt
[   +5 ms]      dev/automated_tests/pubspec.yaml
[        ]      dev/automated_tests/test_smoke_test/crash1_test.dart
[        ]      dev/automated_tests/test_smoke_test/crash2_test.dart
[        ]      dev/automated_tests/test_smoke_test/fail_test.dart
[        ]      dev/automated_tests/test_smoke_test/pass_test.dart
[        ]      dev/benchmarks/complex_layout/android/app/build.gradle
[   +1 ms]      dev/benchmarks/complex_layout/android/build.gradle
[  +10 ms]      dev/benchmarks/complex_layout/android/gradle/wrapper/gradle-wrapper.properties
[        ]      dev/benchmarks/complex_layout/ios/Flutter/AppFrameworkInfo.plist
[   +5 ms]      dev/benchmarks/complex_layout/ios/Runner.xcodeproj/project.pbxproj
[   +2 ms]      dev/benchmarks/complex_layout/ios/Runner/Info.plist
[  +11 ms]      dev/benchmarks/complex_layout/lib/main.dart
[   +2 ms]      dev/benchmarks/complex_layout/pubspec.yaml
[  +14 ms]      dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart
[        ]      dev/benchmarks/complex_layout/test_driver/semantics_perf_test.dart
[   +4 ms]      dev/benchmarks/microbenchmarks/android/app/build.gradle
[        ]      dev/benchmarks/microbenchmarks/android/build.gradle
[   +1 ms]      dev/benchmarks/microbenchmarks/android/gradle/wrapper/gradle-wrapper.properties
[   +5 ms]      dev/benchmarks/microbenchmarks/ios/Flutter/AppFrameworkInfo.plist
[        ]      dev/benchmarks/microbenchmarks/ios/Runner.xcodeproj/project.pbxproj
[   +4 ms]      dev/benchmarks/microbenchmarks/ios/Runner/Info.plist
[        ]      dev/benchmarks/microbenchmarks/lib/gestures/data/velocity_tracker_data.dart
[        ]      dev/benchmarks/microbenchmarks/lib/stocks/animation_bench.dart
[        ]      dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart
[        ]      dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart
[        ]      dev/benchmarks/microbenchmarks/pubspec.yaml
[  +11 ms]      dev/bots/README.md
[        ]      dev/bots/analyze-sample-code.dart
[   +4 ms]      dev/bots/docs.sh
[        ]      dev/bots/prepare_package.dart
[   +7 ms]      dev/bots/pubspec.yaml
[        ]      dev/bots/test.dart
[   +5 ms]      dev/bots/test/fake_process_manager.dart
[   +2 ms]      dev/bots/test/fake_process_manager_test.dart
[   +5 ms]      dev/bots/test/prepare_package_test.dart
[  +10 ms]      dev/devicelab/README.md
[  +13 ms]      dev/devicelab/bin/tasks/commands_test.dart
[   +2 ms]      dev/devicelab/bin/tasks/complex_layout_scroll_perf__memory.dart
[  +12 ms]      dev/devicelab/bin/tasks/flutter_gallery__back_button_memory.dart
[   +2 ms]      dev/devicelab/bin/tasks/flutter_gallery__memory_nav.dart
[   +4 ms]      dev/devicelab/bin/tasks/flutter_gallery_instrumentation_test.dart
[   +6 ms]      dev/devicelab/bin/tasks/gradle_plugin_test.dart
[   +2 ms]      dev/devicelab/bin/tasks/hello_world__memory.dart
[   +4 ms]      dev/devicelab/bin/tasks/routing_test.dart
[   +3 ms]      dev/devicelab/bin/tasks/service_extensions_test.dart
[   +7 ms]      dev/devicelab/lib/framework/adb.dart
[   +2 ms]      dev/devicelab/lib/framework/framework.dart
[   +1 ms]      dev/devicelab/lib/framework/ios.dart
[  +10 ms]      dev/devicelab/lib/framework/runner.dart
[        ]      dev/devicelab/lib/framework/utils.dart
[   +5 ms]      dev/devicelab/lib/tasks/analysis.dart
[   +6 ms]      dev/devicelab/lib/tasks/gallery.dart
[   +7 ms]      dev/devicelab/lib/tasks/hot_mode_tests.dart
[   +3 ms]      dev/devicelab/lib/tasks/integration_ui.dart
[   +4 ms]      dev/devicelab/lib/tasks/microbenchmarks.dart
[   +2 ms]      dev/devicelab/lib/tasks/perf_tests.dart
[   +4 ms]      dev/devicelab/lib/tasks/save_catalog_screenshots.dart
[   +1 ms]      dev/devicelab/manifest.yaml
[   +1 ms]      dev/devicelab/pubspec.yaml
[   +1 ms]      dev/devicelab/test/adb_test.dart
[        ]      dev/devicelab/test/manifest_test.dart
[        ]      dev/devicelab/test/run_test.dart
[        ]      dev/devicelab/test/utils_test.dart
[   +1 ms]      dev/integration_tests/channels/android/app/build.gradle
[        ]      dev/integration_tests/channels/android/build.gradle
[   +1 ms]      dev/integration_tests/channels/android/gradle/wrapper/gradle-wrapper.properties
[        ]      dev/integration_tests/channels/ios/Flutter/AppFrameworkInfo.plist
[        ]      dev/integration_tests/channels/ios/Runner.xcodeproj/project.pbxproj
[        ]      dev/integration_tests/channels/ios/Runner/Info.plist
[        ]      dev/integration_tests/channels/lib/src/basic_messaging.dart
[   +1 ms]      dev/integration_tests/channels/lib/s
[        ] error: The following untracked working tree files would be overwritten by merge:
[        ]      .github/move.yml
[        ]      .github/no-response.yml
[        ]      dev/automated_tests/test_smoke_test/timeout_fail_test.dart
[        ]      dev/automated_tests/test_smoke_test/timeout_pass_test.dart
[        ]      dev/benchmarks/complex_layout/test_memory/scroll_perf.dart
[        ]      dev/bots/cirrus_setup.sh
[   +2 ms]      dev/bots/deploy_gallery.sh
[        ]      dev/bots/test/common.dart
[        ]      dev/ci/README.md
[        ]      dev/ci/docker_linux/Dockerfile
[        ]      dev/ci/docker_linux/README.md
[        ]      dev/ci/docker_linux/docker_build.sh
[        ]      dev/ci/docker_linux/docker_login.sh
[        ]      dev/ci/docker_linux/docker_push.sh
[        ]      dev/devicelab/bin/tasks/flutter_attach_test.dart
[        ]      dev/devicelab/bin/tasks/flutter_test_performance.dart
[        ]      dev/devicelab/bin/tasks/hello_world_android__compile.dart
[        ]      dev/devicelab/bin/tasks/hello_world_ios__compile.dart
[        ]      dev/devicelab/bin/tasks/module_test.dart
[        ]      dev/devicelab/bin/tasks/run_release_test.dart
[        ]      dev/devicelab/bin/tasks/tiles_scroll_perf__timeline_summary.dart
[        ]      dev/devicelab/test/common.dart
[   +2 ms]      dev/integration_tests/android_host_app/README.md
[        ]      dev/integration_tests/android_host_app/app/build.gradle
[        ]      dev/integration_tests/android_host_app/app/src/main/AndroidManifest.xml
[        ]      dev/integration_tests/android_host_app/app/src/main/java/io/flutter/add2app/MainActivity.java
[        ]      dev/integration_tests/android_host_app/build.gradle
[        ]      dev/integration_tests/android_host_app/gradle.properties
[        ]      dev/integration_tests/android_host_app/gradle/wrapper/gradle-wrapper.properties
[        ]      dev/integration_tests/android_host_app/settings.gradle
[        ]      dev/integration_tests/ui/lib/keyboard_textfield.dart
[        ]      dev/integration_tests/ui/test_driver/keyboard_textfield_test.dart
[        ]      examples/flutter_gallery/lib/demo/cupertino/cupertino_alert_demo.dart
[        ]      examples/flutter_gallery/lib/demo/cupertino/cupertino_segmented_control_demo.dart
[        ]      examples/flutter_gallery/lib/demo/material/reorderable_list_demo.dart
[        ]      examples/flutter_gallery/test/demo/material/chip_demo_test.dart
[        ]      examples/flutter_gallery/test_memory/back_button.dart
[        ]      examples/flutter_gallery/test_memory/memory_nav.dart
[        ]      packages/flutter/lib/src/animation/tween_sequence.dart
[        ]      packages/flutter/lib/src/cupertino/action_sheet.dart
[   +2 ms]      packages/flutter/lib/src/cupertino/app.dart
[        ]      packages/flutter/lib/src/cupertino/segmented_control.dart
[        ]      packages/flutter/lib/src/material/reorderable_list.dart
[        ]      packages/flutter/lib/src/painting/clip.dart
[        ]      packages/flutter/lib/src/painting/notched_shapes.dart
[        ]      packages/flutter/lib/src/rendering/platform_view.dart
[        ]      packages/flutter/lib/src/services/platform_views.dart
[        ]      packages/flutter/lib/src/widgets/annotated_region.dart
[        ]      packages/flutter/lib/src/widgets/platform_view.dart
[        ]      packages/flutter/lib/src/widgets/visibility.dart
[        ]      packages/flutter/test/cupertino/action_sheet_test.dart
[        ]      packages/flutter/test/cupertino/app_test.dart
[        ]      packages/flutter/test/cupertino/segmented_control_test.dart
[        ]      packages/flutter/test/engine/dart_test.dart
[        ]      packages/flutter/test/flutter_test_alternative.dart
[        ]      packages/flutter/test/material/raw_material_button_test.dart
[        ]      packages/flutter/test/material/reorderable_list_test.dart
[        ]      packages/flutter/test/painting/notched_shapes_test.dart
[   +3 ms]      packages/flutter/test/rendering/annotated_region_test.dart
[        ]      packages/flutter/test/rendering/localized_fonts_test.dart
[        ]      packages/flutter/test/rendering/viewport_test.dart
[        ]      packages/flutter/test/semantics/custom_semantics_action_test.dart
[        ]      packages/flutter/test/services/fake_platform_views.dart
[        ]      packages/flutter/test/services/platform_views_test.dart
[        ]      packages/flutter/test/widgets/annotated_region_test.dart
[        ]      packages/flutter/test/widgets/constrained_box_test.dart
[        ]      packages/flutter/test/widgets/editable_text_show_on_screen_test.dart
[        ]      packages/flutter/test/widgets/opacity_test.dart
[        ]      packages/flutter/test/widgets/platform_view_test.dart
[        ]      packages/flutter/test/widgets/semantics_zero_surface_size_test.dart
[        ]      packages/flutter/test/widgets/visibility_test.dart
[        ]      packages/flutter_driver/test/common.dart
[        ]      packages/flutter_goldens/lib/client.dart
[        ]      packages/flutter_localizations/lib/src/l10n/material_bg.arb
[   +2 ms]      packages/flutter_localizations/lib/src/l10n/material_bs.arb
[   +1 ms] Updating c7ea3ca37..9299c02cf
[        ]      packages/flutter_localizatio
[        ] Aborting
[  +17 ms] "flutter upgrade" took 4,117ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:53:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:348:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:114:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:170:5)
```

**C:\>flutter doctor --verbose**
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.5.1 at C:\Users\nabudarwish\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\nabudarwish\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.17.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Can you please try 
```sh
git clean -xfd
git pull
flutter doctor
```
in the Flutter install directory (C:\Users\nabudarwish\flutter\)

**Comment by slabo** [comment]
It gave me some trouble trying to unlink flutter\bin\cache\dart-sdk\bin\dart.exe 
Found the process holding it, aparently two instances of dart.exe killed both and then ran **git pull**

gets stuck at the same issue :: 

\flutter>git pull
error: Your local changes to the following files would be overwritten by merge:
        .cirrus.yml
        AUTHORS
        CONTRIBUTING.md
        README.md
        analysis_options.yaml
        appveyor.yml
        bin/flutter.bat
        bin/internal/engine.version
        bin/internal/goldens.version
        bin/internal/update_dart_sdk.ps1
        dev/automated_tests/flutter_test/exception_handling_expectation.txt
        dev/automated_tests/flutter_test/filtering_test.dart
        dev/automated_tests/flutter_test/test_async_utils_guarded_test.dart
        dev/automated_tests/flutter_test/trivial_test.dart
        dev/automated_tests/flutter_test/trivial_widget_expectation.txt
        dev/automated_tests/pubspec.yaml
        dev/automated_tests/test_smoke_test/crash1_test.dart
        dev/automated_tests/test_smoke_test/crash2_test.dart
        dev/automated_tests/test_smoke_test/fail_test.dart
        dev/automated_tests/test_smoke_test/pass_test.dart
        dev/benchmarks/complex_layout/android/app/build.gradle
        dev/benchmarks/complex_layout/android/build.gradle
        dev/benchmarks/complex_layout/android/gradle/wrapper/gradle-wrapper.properties
        dev/benchmarks/complex_layout/ios/Flutter/AppFrameworkInfo.plist
        dev/benchmarks/complex_layout/ios/Runner.xcodeproj/project.pbxproj
        dev/benchmarks/complex_layout/ios/Runner/Info.plist
        dev/benchmarks/complex_layout/lib/main.dart
        dev/benchmarks/complex_layout/pubspec.yaml
        dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart
        dev/benchmarks/complex_layout/test_driver/semantics_perf_test.dart
        dev/benchmarks/microbenchmarks/android/app/build.gradle
        dev/benchmarks/microbenchmarks/android/build.gradle
        dev/benchmarks/microbenchmarks/android/gradle/wrapper/gradle-wrapper.properties
        dev/benchmarks/microbenchmarks/ios/Flutter/AppFrameworkInfo.plist
        dev/benchmarks/microbenchmarks/ios/Runner.xcodeproj/project.pbxproj
        dev/benchmarks/microbenchmarks/ios/Runner/Info.plist
        dev/benchmarks/microbenchmarks/lib/gestures/data/velocity_tracker_data.dart
        dev/benchmarks/microbenchmarks/lib/stocks/animation_bench.dart
        dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart
        dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart
        dev/benchmarks/microbenchmarks/pubspec.yaml
        dev/bots/README.md
        dev/bots/analyze-sample-code.dart
        dev/bots/docs.sh
        dev/bots/prepare_package.dart
        dev/bots/pubspec.yaml
        dev/bots/test.dart
        dev/bots/test/fake_process_manager.dart
        dev/bots/test/fake_process_manager_test.dart
        dev/bots/test/prepare_package_test.dart
        dev/devicelab/README.md
        dev/devicelab/bin/tasks/commands_test.dart
        dev/devicelab/bin/tasks/complex_layout_scroll_perf__memory.dart
        dev/devicelab/bin/tasks/flutter_gallery__back_button_memory.dart
        dev/devicelab/bin/tasks/flutter_gallery__memory_nav.dart
        dev/devicelab/bin/tasks/flutter_gallery_instrumentation_test.dart
        dev/devicelab/bin/tasks/gradle_plugin_test.dart
        dev/devicelab/bin/tasks/hello_world__memory.dart
        dev/devicelab/bin/tasks/routing_test.dart
        dev/devicelab/bin/tasks/service_extensions_test.dart
        dev/devicelab/lib/framework/adb.dart
        dev/devicelab/lib/framework/framework.dart
        dev/devicelab/lib/framework/ios.dart
        dev/devicelab/lib/framework/runner.dart
        dev/devicelab/lib/framework/utils.dart
        dev/devicelab/lib/tasks/analysis.dart
        dev/devicelab/lib/tasks/gallery.dart
        dev/devicelab/lib/tasks/hot_mode_tests.dart
        dev/devicelab/lib/tasks/integration_ui.dart
        dev/devicelab/lib/tasks/microbenchmarks.dart
        dev/devicelab/lib/tasks/perf_tests.dart
        dev/devicelab/lib/tasks/save_catalog_screenshots.dart
        dev/devicelab/manifest.yaml
        dev/devicelab/pubspec.yaml
        dev/devicelab/test/adb_test.dart
        dev/devicelab/test/manifest_test.dart
        dev/devicelab/test/run_test.dart
        dev/devicelab/test/utils_test.dart
        dev/integration_tests/channels/android/app/build.gradle
        dev/integration_tests/channels/android/build.gradle
        dev/integration_tests/channels/android/gradle/wrapper/gradle-wrapper.properties
        dev/integration_tests/channels/ios/Flutter/AppFrameworkInfo.plist
        dev/integration_tests/channels/ios/Runner.xcodeproj/project.pbxproj
        dev/integration_tests/channels/ios/Runner/Info.plist
        dev/integration_tests/channels/lib/src/basic_messaging.dart
        dev/integration_tests/channels/lib/s
Aborting
Updating c7ea3ca37..9299c02cf

ignored that and tried again.

\flutter>**flutter doctor --verbose**
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e3687f70c7ece72000b32ee1b3c02755ba5361ac...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
packages/flutter_tools/lib/src/commands/attach.dart:1: Error: The system cannot find the file specified.

Error: Unable to create dart snapshot for flutter tool.
Building flutter tool...
Running pub upgrade...
packages/flutter_tools/lib/src/commands/attach.dart:1: Error: The system cannot find the file specified.

Error: Unable to create dart snapshot for flutter tool.
Building flutter tool...
Running pub upgrade...
packages/flutter_tools/lib/src/commands/attach.dart:1: Error: The system cannot find the file specified.

Error: Unable to create dart snapshot for flutter tool.
Building flutter tool...
Running pub upgrade...
packages/flutter_tools/lib/src/commands/attach.dart:1: Error: The system cannot find the file specified.

.
.
.
loops on and on ....

**Comment by slabo** [comment]
by the way, I assume you wanted me to run **git clean -xfd** from flutter root location

**Comment by zoechi** [comment]
`git pull` is unrelated to Flutter.
Perhaps a network issue?

**Comment by zoechi** [comment]
Is that not `C:\Users\nabudarwish\flutter`?

**Comment by slabo** [comment]
yes, thats where I ran **git clean -xfd**

**Comment by slabo** [comment]
I tried with three different connections. still same issue

**Comment by zoechi** [comment]
Hard to tell but it looks like an issue among Git, Windows, Internet, GitHub,
but Flutter doesn't seem to be involved.
Sorry, I don't have an idea how to debug.

**Comment by slabo** [comment]
meh, like everything in Windows, just wipe it and reinstall. No idea how I got here and what's the problem now. looks fine now. Closing

C:\Users\nabudarwish>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.26.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by romdj** [comment]
> Can you please try
> 
> ```shell
> git clean -xfd
> git pull
> flutter doctor
> ```
> 
> in the Flutter install directory (C:\Users\nabudarwish\flutter)

Although that issue is closed, I encountered that aforementioned issue, and that solution did it for me, so thank you for that!

**Comment by GustavoFenilli** [comment]
After downloading the stable sdk for [windows](https://flutter.dev/docs/get-started/install/windows), unziping it to C:\src\flutter, running flutter channel stable gives a git not commited changes problems, trying the accepted solution here:
> Can you please try
> 
> ```shell
> git clean -xfd
> git pull
> flutter doctor
> ```
> 
> in the Flutter install directory (C:\Users\nabudarwish\flutter)

It fails as the first command `git clean -xfd` will delete EVERYTHING from the folder, meaning that there is nothing there to git pull and flutter doctor can't find bin anymore.

My solution was to clone the git repository, flutter channel stable gives " already on stable " ( good ) and flutter upgrade gives " Flutter is already up to date on channel stable " ( also good ), for anyone having any kinda of problem with those, I would go for the git clone options as it seens to be working as expected, instead of the .zip file.
