### ISSUE TITLE
Snackbar appearance doesn't match Material spec

### ISSUE THREAD

**Issue by michdud** [flutter/flutter#21220]
Currently: 
![screenshot_1535640501](https://user-images.githubusercontent.com/25540019/44859536-59403800-ac42-11e8-8a80-03a993f7b46c.png)

Spec:
![snackbar](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1hJm24PlwoTxWrIMhkPE0RV2Q-ahyQVZq%2Fsnackbars-container-do.png)

**Comment by sir-boformer** [comment]
Yep. Seems like the spec was recently changed.

Another important change: Snackbars should appear above the FAB:

<img src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1BlhZYfz9EClmRaSVq-sPLwyXVGEQKDlj%2Fsnackbars-layout-fab.png">
