### ISSUE TITLE
flutter/dart lexical/semantic analysis

### ISSUE THREAD

**Issue by gggustafson** [flutter/flutter#21224]
When I write
...
const int NUMBER_TILES = 9;
const int cross_axis_count = (sqrt (NUMBER_TILES)).toInt();
...

I receive the popup message "[dart] Const variables must be initialized with a constant value."

This is surprising since NUMBER_TILES is declared const. Although there is a work-around (i.e., declaring cross_axis_count as final instead of const), the fact that the "const-ness" of NUMBER_TILES is being misinterpreted is disconcerting. The dart lexical scanner might need reconsideration.

Please advise.

**Comment by jonahwilliams** [comment]
Dart has intentionally limited ability to do const evaluation at compile time. Dart is not able to const evaluate the expression you posted above, therefore cross_axis_count cannot be const either. If you have questions/feedback/concerns about const I would recommend posting them on https://github.com/dart-lang/sdk

**Comment by gggustafson** [comment]
I'm glad that the Dart developers do not have to tend with the constraints of a standardization process. It makes it so much easier to make bad decisions.
