### ISSUE TITLE
Add more logs for driver.screenshot functionality

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#21228]
We have failures such as:

```
JSON-RPC error -32000: Could not capture image screenshot.
package:json_rpc_2/src/client.dart 110:64                    Client.sendRequest
package:json_rpc_2/src/peer.dart 68:15                       Peer.sendRequest
package:flutter_driver/src/driver/driver.dart 627:53         FlutterDriver.screenshot
```

when trying to do golden image tests. There's no other apparent log that accompanies this (no flutter output in syslog). It would be great if we add more information so we can debug it further. It is happening approximately 5% of the runs.

**Comment by ened** [comment]
Additionally, it would be nice if the error message could state what the cause of the error is.

```[ERROR:flutter/shell/common/rasterizer.cc(321)] Last layer tree was null when screenshotting.
```

Means exactly nothing to developers. :-)
