### ISSUE TITLE
Fastlane fails to build on CircleCI. /bin/xcode_backend.sh: No such file or directory

### ISSUE THREAD

**Issue by alexandrius** [flutter/flutter#21226]
## Steps to Reproduce

Hello. I have issue regarding build at CircleCI. Everything worked just fine until today. Only thing I have changed is that I added some native code in AppDelegate. Everything works just fine on my local laptop but at CircleCI it fails to build.

Buildscript: https://gist.github.com/alexandrius/096c0f1c1c3a7e86638917377ebc5a8a
Fastfile: https://gist.github.com/alexandrius/4a3e94eb7f32c414e5ccd192e39ffa21

## Logs

`/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory`

Here is the snippet from Log: https://gist.github.com/alexandrius/14ed63378a26ca462536fdf32a49e100

```
```

[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-GE)
    • Flutter version 0.5.1 at /Users/alex/Documents/Flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/alex/Library/Android/sdk/
    • Android NDK at /Users/alex/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /Users/alex/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Alexander Pataridze’s iPhone • e4aeba57aa1c2cc11ba2416a1b25ba9603be3a2e • ios • iOS 11.4.1
    • iPhone 6                     • D0EE89B8-C812-4F04-9128-1E1DFC03CEE5     • ios • iOS 10.3 (simulator)

! Doctor found issues in 1 category.

```
```

**Comment by Hixie** [comment]
@alexandrius Does it work if you upgrade to beta 6?
Does it work if you revert your change? If so, what is your change?

cc @cbracken

**Comment by Hixie** [comment]
sorry about closing, i coughed as i was clicking "comment" and my pointer jumped to "close and comment"!

**Comment by alexandrius** [comment]
@Hixie How do I upgrade? Running flutter upgrade doesn't do anything.
I don't want to experiment much since CircleCI is quite expensive. But I will try reverting today.
No problems closing the issue.
Can I provide anything else?

**Comment by alexandrius** [comment]
@Hixie OK I tested the older branch where CircleCI build was working just fine. It doesn't work any more even there. I get the same error which I posted above.

Current CircleCI configuration installs Flutter every time. Did anything change in past 7 days? Did flutter get update?

**Comment by alexandrius** [comment]
@zoechi So I updated Flutter version to 0.6.0 on my laptop, updated some libraries. Now everything works just fine. Thank you for your help.

**Comment by zoechi** [comment]
Glad to hear. Thanks for the update!
