### ISSUE TITLE
ListView automatically adds SafeArea and there's no way to remove it

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#21236]
I just added a ListView as a child of `Scaffold > Stack` and it appears to have SafeArea at the top. Column does not have this problem. Is there any way for me to remove it?

```
    Container(
      color: Colors.grey[100],
      child: ListView(
        children: <Widget>[
          Image(
            image: snapshot.data.hero,
            height: 300.0,
            fit: BoxFit.cover,
          ),
        ],
      ),
    ),
```

*ListView*
<img width="975" alt="screen shot 2018-08-30 at 4 27 11 pm" src="https://user-images.githubusercontent.com/666539/44878206-447c9800-ac74-11e8-9b23-79db0e58699e.png">

*Column*
<img width="964" alt="screen shot 2018-08-30 at 4 27 23 pm" src="https://user-images.githubusercontent.com/666539/44878211-48a8b580-ac74-11e8-9158-ce45bf700987.png">

**Comment by lukepighetti** [comment]
Thank you for the comment link, it was very useful. This was blocking due to documentation I would say then. It would have taken me days to find this had you not provided that link.

As a note, my searches included Google, Stack, and looking for a "RemoveSafeArea()" widget. I also looked for a "noPadding" and "noSafeArea" property on ListView.

```
MediaQuery.removePadding(
              context: context,
              removeTop: true,
              child: ListView(
                children: <Widget>[
                  Image(
                    image: snapshot.data.hero,
                    height: 300.0,
                    fit: BoxFit.cover,
                  ),
                ],
              ),
            ),
```

<img width="1096" alt="screen shot 2018-08-31 at 9 24 57 am" src="https://user-images.githubusercontent.com/666539/44914992-bfd75b80-acff-11e8-81ab-0d919dd807fe.png">

**Comment by lukepighetti** [comment]
Also just found this in documentation: 

```
ListView(
              padding: EdgeInsets.all(0.0),
              children: <Widget>[
                Image(
                  image: snapshot.data.hero,
                  height: 300.0,
                  fit: BoxFit.cover,
                ),
              ],
            ),
```

So I will close. Thanks for the help.

**Comment by zoechi** [comment]
Just for reference https://stackoverflow.com/questions/52105557/how-to-remove-automatic-safearea-from-listview
