### ISSUE TITLE
Divider widget: Add indent property for both sides (startIndent and endIndent)

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#21244]
Currently the `Divider` widget only supports indent on the left side, e.g.:

```dart
Divider(height: 1.0, indent: 16.0)
```
> The amount of empty space to the left of the divider.

I think it would make more sense to have indents on both sides:

```dart
Divider(height: 1.0, startIndent: 16.0, endIndent: 16.0)
```

Dividers like that are commonly found in Material design.

**Comment by rravithejareddy** [comment]
Yeah! i am using padding for now.

**Comment by samueldeschamps** [comment]
It would be very handy!
