### ISSUE TITLE
listSync hangs in release mode with Flutter beta 0.6.0

### ISSUE THREAD

**Issue by ghunter99** [flutter/flutter#21242]
## Steps to Reproduce

I upgraded to Flutter beta 0.6.0 yesterday.

Now my app hangs when calling the listSync function when running in release mode.
listSync works in debug mode & worked in release mode prior to upgrading to 0.6.0

I made a minimally modified version of the default main.dart program that demonstrates the problem. listSync hangs when running on both iOS & Android devices.

Here's the gist:
https://gist.github.com/ghunter99/b05f7cb44c5b49e80d088e1c5c473b72

## Logs

```
```

```
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
Closing as dup of #21297 because there is more discussion going on.

**Comment by zoechi** [comment]
#21297 is another one where debug mode works but release mode doesn't on iOS. There might be a common cause.

**Comment by asapJ** [comment]
I found out this inconsistency started after the reduction in release binary from v0.6.0 upwards,  and It still exist even in v0.7.5.
All is usually good during debug mode but after building apk for release it just breaks the app..
Reduction  in binary size isnt neccesary if it causes inconsistent behaviors.

This should be looked into

**Comment by richgoldmd** [comment]
Is there any short-term work around here that isnt changing to the master channel?

**Comment by SGuzel** [comment]
Flutter 0.7.3 • channel beta • 
Framework • revision 3b309bda07 (3 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282


E/flutter (13016): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Dart_New: could not find constructor 'File.fromRawPath'.

**Comment by rtoshmukhamedov** [comment]
Flutter (Channel beta, v0.8.2)
Still not working on release build.

**Comment by jason-simmons** [comment]
This works on the current master branch of Flutter.  The fix landed in Dart on 9/6 but had not rolled into Flutter in time for v0.8.2

**Comment by rtoshmukhamedov** [comment]
@jason-simmons Thanks a lot. It is working on master channel....

**Comment by zoechi** [comment]
I assume this is fixed.
Please add a comment if you still see this and I'll reopen.
