### ISSUE TITLE
[Image_picker] can't open file with ImageSource.gallery

### ISSUE THREAD

**Issue by nanox77** [flutter/flutter#21257]
Hi, i'm having troubles with [Image_picker](https://pub.dartlang.org/packages/image_picker#-example-tab-) plugin. I can't show image from gallery. However, show image from camera works perfectly.
I try add two permissions to read external storage but doesn't work:
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

## Steps to Reproduce

1. Add `image_picker: ^0.4.10` dependency to `pubspec.yaml`
2. Add `import 'package:image_picker/image_picker.dart';`
3. Code which pick image from plugin:
```dart
pickImageFromGallery() async {
    var image = await ImagePicker.pickImage(ImageSource.gallery);
    print(image.path);
    setState(() {
      _image = image;
    });
  }
```
4. Show image in a `Container` or similar:
```dart
Image.file(_image,)
```

## Logs

```
I/flutter (30940): /data/user/0/com.android.providers.downloads/cache/348s.jpg
I/flutter (30940): Another exception was thrown: FileSystemException: Cannot open file, path = '/data/user/0/com.android.providers.downloads/cache/348s.jpg' (OS Error: Permission denied, errno = 13)
```

Flutter analyze:
```
No issues found! (ran in 1.6s)
```

Flutter doctor -v:
```
[✓] Flutter (Channel dev, v0.7.0, on Mac OS X 10.13.6 17G65, locale en-AR)
    • Flutter version 0.7.0 at /Users/marianocastellano/Documents/Flutter/flutter
    • Framework revision 09fe34708f (8 days ago), 2018-08-22 10:20:51 -0700
    • Engine revision 4b271b2e02
    • Dart version 2.1.0-dev.1.0.flutter-69fce633b7

[!] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/marianocastellano/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
Is this in the emulator, a real device or both?

**Comment by nanox77** [comment]
Oh, sorry i didn't say anything about that. The problems is only in the emulator, in a real device works. Thanks for you replay!.

**Comment by leorachit** [comment]
It's also happening on the device but only with certain images i have downloaded from internet. Is there any copyright check or something?

**Comment by nanox77** [comment]
Hi, @leorachit , could you show the error?. If doesn't work on device, maybe you need add some permissions.

**Comment by lordgreg** [comment]
Hi. To not duplicate an issue, I'm having also an exception thrown (emulator only):
```
E/AndroidRuntime( 8926): 	at android.content.ContentResolver.query(ContentResolver.java:710)
E/AndroidRuntime( 8926): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:117)
E/AndroidRuntime( 8926): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:69)
E/AndroidRuntime( 8926): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:41)
E/AndroidRuntime( 8926): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:395)
E/AndroidRuntime( 8926): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime( 8926): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 8926): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 8926): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 8926): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime( 8926): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime( 8926): 	... 11 more
I/Process ( 8926): Sending signal. PID: 8926 SIG: 9
Lost connection to device.
Exited (sigterm)
```

Using `ImageSource.camera` doesn't throw an error, but it doesn't make an image either.

**Comment by Deepadinesh** [comment]
i have added the picker in pupspec.yaml   image_picker: ^0.4.10 but i cannot able to import in my class

**Comment by geegit** [comment]
I have a similar issue on Android (8.0).  It only occurs when trying to access files saved to Downloads folder.  The stacktrace looks like the files are accessed by the internal "timestamp" name instead of the human readable name.  Also the URI starts with content:// if that's any clue.

/AndroidRuntime(11853): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/1231 flg=0x1 }} to activity {com.whitealfred.whitealfred/com.whitealfred.whitealfred.MainActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/1231
E/AndroidRuntime(11853): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
E/AndroidRuntime(11853): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
E/AndroidRuntime(11853): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(11853): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
E/AndroidRuntime(11853): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(11853): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(11853): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/AndroidRuntime(11853): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11853): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(11853): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(11853): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/1231
E/AndroidRuntime(11853): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
E/AndroidRuntime(11853): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
E/AndroidRuntime(11853): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
E/AndroidRuntime(11853): 	at android.content.ContentResolver.query(ContentResolver.java:760)
E/AndroidRuntime(11853): 	at android.content.ContentResolver.query(ContentResolver.java:710)
E/AndroidRuntime(11853): 	at android.content.ContentResolver.query(ContentResolver.java:668)
E/AndroidRuntime(11853): 	at io.flutter.plugins.imagepickersaver.FileUtils.getDataColumn(FileUtils.java:118)
E/AndroidRuntime(11853): 	at io.flutter.plugins.imagepickersaver.FileUtils.getPathFromLocalUri(FileUtils.java:70)
E/AndroidRuntime(11853): 	at io.flutter.plugins.imagepickersaver.FileUtils.getPathFromUri(FileUtils.java:42)
E/AndroidRuntime(11853): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:429)
E/AndroidRuntime(11853): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:409)
E/AndroidRuntime(11853): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(11853): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(11853): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(11853): 	at android.app.Activity.dispatchActivityResult(Activity.java:7548)
E/AndroidRuntime(11853): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
E/AndroidRuntime(11853): 	... 9 more

**Comment by cyanglaz** [comment]
@nanox77 Are you still experiencing the issue? I checked with the latest image_picker it seems working fine.

**Comment by nanox77** [comment]
I checked latest version few minutes ago and it seems working fine!

**Comment by MichalMisiaszek** [comment]
I have the same problem on Android with newest version of plugin. Selecting image from gallery does not work on device.
```
E/flutter (17811): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/storage/emulated/0/DCIM/100MEDIA/IMAG6697.jpg' (OS Error: Permission denied, errno = 13)
E/flutter (17811): #0      _File._delete.<anonymous closure>  (dart:io/file_impl.dart:291:9)
E/flutter (17811): #1      _rootRunUnary  (dart:async/zone.dart:1132:38)
E/flutter (17811): #2      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (17811): #3      _FutureListener.handleValue  (dart:async/future_impl.dart:126:18)
E/flutter (17811): #4      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:639:45)
E/flutter (17811): #5      Future._propagateToListeners  (dart:async/future_impl.dart:668:32)
E/flutter (17811): #6      Future._completeWithValue  (dart:async/future_impl.dart:483:5)
E/flutter (17811): #7      Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
E/flutter (17811): #8      _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (17811): #9      _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (17811): #10     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter (17811): #11     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
E/flutter (17811): #12     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter (17811): #13     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
E/flutter (17811):
D/SurfaceView(17811): show() Surface(name=SurfaceView - com.pestscope.pestscopemobile/com.pestscope.pestscopemobile.MainActivity@c1e21c1@10[17811])/@0x669f1b9 io.flutter.view.FlutterView{c1e21c1 VFE...... .F...... 0,0-1080,2154}
```

**Comment by darren-f5s** [comment]
> I have the same problem on Android with newest version of plugin. Selecting image from gallery does not work on device.
> 
> ```
> E/flutter (17811): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/storage/emulated/0/DCIM/100MEDIA/IMAG6697.jpg' (OS Error: Permission denied, errno = 13)
> E/flutter (17811): #0      _File._delete.<anonymous closure>  (dart:io/file_impl.dart:291:9)
> E/flutter (17811): #1      _rootRunUnary  (dart:async/zone.dart:1132:38)
> E/flutter (17811): #2      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
> E/flutter (17811): #3      _FutureListener.handleValue  (dart:async/future_impl.dart:126:18)
> E/flutter (17811): #4      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:639:45)
> E/flutter (17811): #5      Future._propagateToListeners  (dart:async/future_impl.dart:668:32)
> E/flutter (17811): #6      Future._completeWithValue  (dart:async/future_impl.dart:483:5)
> E/flutter (17811): #7      Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
> E/flutter (17811): #8      _rootRun  (dart:async/zone.dart:1124:13)
> E/flutter (17811): #9      _CustomZone.run  (dart:async/zone.dart:1021:19)
> E/flutter (17811): #10     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
> E/flutter (17811): #11     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
> E/flutter (17811): #12     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
> E/flutter (17811): #13     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
> E/flutter (17811):
> D/SurfaceView(17811): show() Surface(name=SurfaceView - com.pestscope.pestscopemobile/com.pestscope.pestscopemobile.MainActivity@c1e21c1@10[17811])/@0x669f1b9 io.flutter.view.FlutterView{c1e21c1 VFE...... .F...... 0,0-1080,2154}
> ```

I see it's trying to delete something? It's pretty clear that the app should not be able to delete something from the gallery - but it looks like you have a specific method that calls that? Might be your issue.

**Comment by congfandi** [comment]
guys, why this issue close ?

i have found this issue ...

please tell me how to resolved it ?

i have been installed new version of this library.

thanks.

**Comment by ariefannur** [comment]
i've got some issue. use 0.6.4 version, any suggestion for it?

**Comment by ariefannur** [comment]
it's happen both emulator and device `Unhandled Exception: FileSystemException: Cannot open file, path = ` @nanox77

**Comment by nanox77** [comment]
I don't have any error when open file with ImageSource.gallery, please show us your stacktrace, thank you.

**Comment by ariefannur** [comment]
i have saved path to local and then preview it with the path. got this  @nanox77 
```
I/flutter (23608): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (23608): The following FileSystemException was thrown resolving an image codec:
I/flutter (23608): Cannot open file, path = '' (OS Error: Bad address, errno = 14)
I/flutter (23608): 
I/flutter (23608): When the exception was thrown, this was the stack:
I/flutter (23608): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
I/flutter (23608): (elided 13 frames from dart:async)
I/flutter (23608): ...
I/flutter (23608): 
I/flutter (23608): Path:
I/flutter (23608): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (23608): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = '' (OS Error: Bad address, errno = 14)
E/flutter (23608): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
E/flutter (23608): #1      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (23608): #2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23608): #3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (23608): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (23608): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (23608): #6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (23608): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (23608): #8      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23608): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23608): #10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23608): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (23608): #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (23608): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (23608): 
E/flutter (23608): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot open file, path = '' (OS Error: Bad address, errno = 14)
E/flutter (23608): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
E/flutter (23608): #1      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (23608): #2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23608): #3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (23608): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (23608): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (23608): #6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (23608): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (23608): #8      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23608): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23608): #10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23608): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (23608): #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (23608): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (23608): 
```

**Comment by nanox77** [comment]
Error make sense because can not open file with `path = ' '`. We need more information, we need your piece of code, flutter doctor and version of this library. Thank you

**Comment by ariefannur** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.18.0, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```
use `image_picker: ^0.6.4`

```
FutureBuilder(
  future: Future.value(File(listCustomer[pos].photo)),
  builder: (BuildContext context, AsyncSnapshot<File> snapshot) {
    if ( snapshot.data != null)
      snapshot.data.readAsBytes();
    return snapshot.data != null ? new Image.file(snapshot.data) : Text(listCustomer[pos].name.substring(0, 1).toUpperCase(), style: TextStyle(color: Colors.white));
  }
) 
```

**Comment by nanox77** [comment]
Well, if photo is remote file, you have to download at first. If you photo is local, you don't have to wrapper on `FutureBuilder` or a `Future.value`. 
You are not using library on this code, please tell us where code is used. Try to implement a simple code like this:

```
    File file = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() {
      _file = file;
    });
```
And on you `build` method use:

```
Image.file(file)
```

**Comment by uzumaki258** [comment]
I have retrieved the image if it deleted.
```
void _getImage(BuildContext context, bool fromCamera) async {
    if (await _checkPermission()) {
      try{
      var _image = await ImagePicker.pickImage(
          source: fromCamera ? ImageSource.camera : ImageSource.gallery,
          maxHeight: 800,
          maxWidth: 600,
          );
          
      retrieveLostData();
      if (_image != null && _image.path != null) {
        _goToChoosePage(context, _image);
      }
      }catch (e) {
        _pickImageError = e ;
        print("_pick image error:" +_pickImageError);
      }
    }
  }
```
This only occur on some device:
Galaxy S8+, HUAWEI P30 lite,Galaxy J5 Pro
