### ISSUE TITLE
About "Add Flutter to existing apps" I have a question？

### ISSUE THREAD

**Issue by huohu1007** [flutter/flutter#21258]
Need to add git version control to the ".android" and ".ios" folders generated by the "flutter create -t ​​module flutter_module" command?

**Comment by jmagman** [comment]
They are not intended to be source controlled and can be regenerated at any time.  We are tracking this pattern at https://github.com/flutter/flutter/issues/32989 if you want to comment there about what you need to keep track of in those directories.
