### ISSUE TITLE
Ensure Android architecture works with deep linking

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21255]
Ensure Android architecture works with deep linking: 

https://docs.google.com/document/d/1AKPWL50wzQFTSaEz2AbGZm5Fkm01uvunZH8AEoLJMRI/edit

**Comment by zoechi** [comment]
Is this a duplicate of #5330, #11607 ?

**Comment by matthew-carroll** [comment]
@zoechi I don't think so.  This ticket is about the Android-specific notion of deep linking as is used by Android developers today.  I don't think those other tickets are about that.

**Comment by xster** [comment]
@chunhtai your https://github.com/flutter/engine/pull/22363 will address this one too presumably?

**Comment by chunhtai** [comment]
yes, I don't know this issue exist.

**Comment by xster** [comment]
ok, since you already closed your issue :) I'll just add that your PR fixes this in the description.
