### ISSUE TITLE
plugins need to support flutter 0.6.0(dart 2.1.0)

### ISSUE THREAD

**Issue by Cha0sX** [flutter/flutter#21260]
some plugins (path_provider etc) can not use in 0.6.0

---------------------------------------------------------------------------
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
```
Because test depends on path_provider >=0.1.1 <0.4.0 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
```

**Comment by jonahwilliams** [comment]
The latest version of path_provider (0.4.1) supports any dart SDk < 3.0.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
