### ISSUE TITLE
does not display at sign on phone call

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#21267]
_From @Fotima97 on August 31, 2018 4:14_

URL: https://pub.dartlang.org/packages/url_launcher#-readme-tab-

I am trying to call a number that contains # sign, but the dealer does not show # sign 
                    launch('tel:*150#');

_Copied from original issue: dart-lang/pub-dartlang-dart#1573_

**Comment by isoos** [comment]
@Fotima97: please file issues in the package's repositories, this tracker is for the pub site. I'm moving this now.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Is this on Android or iOS or both?

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/25890866/hash-key-stripped-from-ussd-code-in-tel-links-on-html-pages might help

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
