### ISSUE TITLE
systemNavigationBarIconBrightness: Brightness.dark resets to light onResume.

### ISSUE THREAD

**Issue by iamarnas** [flutter/flutter#21265]
`systemNavigationBarIconBrightness`: `Brightness.dark` resets to `light` `onResume`.

This bug still live from beta 0.5.1 now I testing master 0.7.4 and i have same problem.

This is my code:
```dart
SystemChrome.setSystemUIOverlayStyle(
    SystemUiOverlayStyle.light.copyWith(
      statusBarColor: Colors.white,
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );
```

I have fixed it with this code below, but i think it should work with default code which is above.

```dart
void _updateNavigationBarIconBrightness() async {
  SystemChannels.lifecycle.setMessageHandler((msg) {
    if (msg == AppLifecycleState.resumed.toString()) {
      SystemChrome.setSystemUIOverlayStyle(
        SystemUiOverlayStyle.light.copyWith(
          systemNavigationBarColor: Colors.white,
          systemNavigationBarIconBrightness: Brightness.dark,
        ),
      );
    }
  });
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Looks like a part is missing from the fix to #4630

**Comment by iamarnas** [comment]
@zoechi  Here is my output of `flutter doctor -v`

[✓] Flutter (Channel master, v0.7.4-pre.21, on Mac OS X 10.13.6 17G65, locale sv-SE)
    • Flutter version 0.7.4-pre.21 at /Users/arnas/development/tools/flutter
    • Framework revision 7cebaac985 (28 hours ago), 2018-08-29 21:53:39 -0700
    • Engine revision 252da48082
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/arnas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • Nexus 5X • 013c535795c613eb • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

**Comment by tomosullivan8** [comment]
This constantly happens to me too, everytime the app is re-opened (not the initial open) - has there been a fix for this?

**Comment by PiN73** [comment]
Listening `AppLifecycleState.resumed` with `SystemChannels.lifecycle.setMessageHandler` didn't work for me.

It seems `AnnotatedRegion` can help:

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
      child: MaterialApp(
        ...
      ),
    );
  }
}
```

**Comment by sgehrman** [comment]
Is there a better solution?

**Comment by PiN73** [comment]
@sgehrman why is AnnotatedRegion bad?

**Comment by Xgamefactory** [comment]
Thanks for AnnotatedRegion.
But if you use AppBar it will totally override systemUiStyle
app_bar.dart line 588

 ```
final Brightness brightness = widget.brightness
      ?? appBarTheme.brightness
      ?? theme.primaryColorBrightness;
    final SystemUiOverlayStyle overlayStyle = brightness == Brightness.dark
      ? SystemUiOverlayStyle.light
      : SystemUiOverlayStyle.dark;

    return Semantics(
      container: true,
      child: AnnotatedRegion<SystemUiOverlayStyle>(
        value: overlayStyle,
```

**Comment by iamarnas** [comment]
> Thanks for AnnotatedRegion.
> But if you use AppBar it will totally override systemUiStyle
> app_bar.dart line 588
> 
> ```
> final Brightness brightness = widget.brightness
>      ?? appBarTheme.brightness
>      ?? theme.primaryColorBrightness;
>    final SystemUiOverlayStyle overlayStyle = brightness == Brightness.dark
>      ? SystemUiOverlayStyle.light
>      : SystemUiOverlayStyle.dark;
> 
>    return Semantics(
>      container: true,
>      child: AnnotatedRegion<SystemUiOverlayStyle>(
>        value: overlayStyle,
> ```
> 
> we have edited app_bar.dart by removing AnnotatedRegion not a clean solution but

Just override you AppBar  ThemeData with copywith().

**Comment by Xgamefactory** [comment]
There is a brigthness parameter for appbar but We have custom statusbar and navigation bar coloring not just dark light .

**Comment by nt4f04uNd** [comment]
> Listening `AppLifecycleState.resumed` with `SystemChannels.lifecycle.setMessageHandler` didn't work for me.
> 
> It seems `AnnotatedRegion` can help:

@PiN73 I don't know, why this didn't work for you, but the following code has worked for me perfectly

```dart
class LifecycleEventHandler extends WidgetsBindingObserver {
  LifecycleEventHandler({
    this.onInactive,
    this.onPaused,
    this.onDetached,
    this.onResumed,
  });

  final AsyncCallback onInactive;
  final AsyncCallback onPaused;
  final AsyncCallback onDetached;
  final AsyncCallback onResumed;

  @override
  Future<Null> didChangeAppLifecycleState(AppLifecycleState state) async {
    switch (state) {
      case AppLifecycleState.inactive:
        if (onInactive != null) await onInactive();
        break;
      case AppLifecycleState.paused:
        if (onPaused != null) await onPaused();
        break;
      case AppLifecycleState.detached:
        if (onDetached != null) await onDetached();
        break;
      case AppLifecycleState.resumed:
        if (onResumed != null) await onResumed();
        break;
    }
  }
}

// And then on app initialization
//  ...
WidgetsBinding.instance.addObserver(
    LifecycleEventHandler(
      onResumed: () {
        SystemChrome.setSystemUIOverlayStyle(
            SystemUiOverlayStyle(
              systemNavigationBarIconBrightness: Brightness.dark ,
          ),
        );
      },
    ),
);
```

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.light.copyWith(
        statusBarColor: Colors.white,
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
    );
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-1.0.pre at /home/tesser/Code/flutter_dev
    • Framework revision 456d80b9dd (9 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/tesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/tesser/Code/SDK
    • Java binary at: /home/tesser/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/tesser/Code/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.61

• No issues found!

``` 

</details>

**Comment by iamarnas** [comment]
> <details> 
> <summary>Code Sample</summary> 
> 
> ``` 
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       debugShowCheckedModeBanner: false,
>       title: 'Material App',
>       home: Home(),
>     );
>   }
> }
> 
> class Home extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     SystemChrome.setSystemUIOverlayStyle(
>       SystemUiOverlayStyle.light.copyWith(
>         statusBarColor: Colors.white,
>         systemNavigationBarColor: Colors.white,
>         systemNavigationBarIconBrightness: Brightness.dark,
>       ),
>     );
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Material App Bar'),
>       ),
>       body: Center(
>         child: Container(
>           child: Text('Hello World'),
>         ),
>       ),
>       floatingActionButton: FloatingActionButton(
>         child: Icon(Icons.add),
>         onPressed: () {},
>       ),
>     );
>   }
> }
> ``` 
> 
> </details> 
> 
> <details> 
> <summary>flutter doctor -v</summary> 
> 
> ``` 
> [✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.19.0-1.0.pre at /home/tesser/Code/flutter_dev
>     • Framework revision 456d80b9dd (9 days ago), 2020-05-11 11:45:03 -0400
>     • Engine revision d96f962ca2
>     • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at /home/tesser/Code/SDK
>     • Platform android-29, build-tools 29.0.3
>     • ANDROID_HOME = /home/tesser/Code/SDK
>     • Java binary at: /home/tesser/Code/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /home/tesser/Code/android-studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.8052
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.45.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 3.10.2
> 
> [✓] Connected device (3 available)
>     • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
>     • Web Server • web-server       • web-javascript • Flutter Tools
>     • Chrome     • chrome           • web-javascript • Google Chrome
>       83.0.4103.61
> 
> • No issues found!
> 
> ``` 
> 
> </details> 

This work now? Restore the brightness on resume? It works only on dev channel?

**Comment by TahaTesser** [comment]
### Preview
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/48603081/105988956-6ccb8380-60c6-11eb-94f6-2afc432d6247.gif)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle.light.copyWith(
        statusBarColor: Colors.white,
        systemNavigationBarColor: Colors.white,
        systemNavigationBarIconBrightness: Brightness.dark,
      ),
    );
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.194 at /Users/tahatesser/Code/flutter_master
    • Framework revision 71aec53acb (5 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by thang510023** [comment]
> Listening `AppLifecycleState.resumed` with `SystemChannels.lifecycle.setMessageHandler` didn't work for me.
> 
> It seems `AnnotatedRegion` can help:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return AnnotatedRegion<SystemUiOverlayStyle>(
>       value: SystemUiOverlayStyle(
>         systemNavigationBarColor: Colors.white,
>         systemNavigationBarIconBrightness: Brightness.dark,
>       ),
>       child: MaterialApp(
>         ...
>       ),
>     );
>   }
> }
> ```

it worked for me

**Comment by Stitch-Taotao** [comment]
AnnotatedRegion<SystemUiOverlayStyle>(value: SystemUiOverlayStyle.dark,child: xxx,); not work  in Flutter 2.8.1 on Device run in [MiUi](https://home.miui.com/)

> 
> Flutter 2.8.1 • channel stable • https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
> Framework • revision 77d935af4d (5 weeks ago) • 2021-12-16 08:37:33 -0800
> Engine • revision 890a5fca2e
> Tools • Dart 2.15.1

But the same code work in Flutter 2.5.1 in [MiUi](https://home.miui.com/)

> Flutter 2.5.1 • channel unknown • unknown source
> Framework • revision ffb2ecea52 (4 months ago) • 2021-09-17 15:26:33 -0400
> Engine • revision b3af521a05
> Tools • Dart 2.14.2
>

**Comment by olegyablokov** [comment]
I have tried the solutions described here, nothing has helped yet.

**Comment by bleroux** [comment]
Relying on an `AnnotatedRegion` is the right solution (`SystemChrome.setSystemUIOverlayStyle` is an imperative API that might have to be called again, for instance after resuming the app).

FYI, an `AppBar` automatically inserts an `AnnotatedRegion` and since https://github.com/flutter/flutter/pull/104827 is merged, `AppBar.systemOverlayStyle` can be used to style both the status bar and the system navigation bar.
