### ISSUE TITLE
'FlutterCallbackCache.h' file not found

### ISSUE THREAD

**Issue by Nik99** [flutter/flutter#21275]
## Steps to Reproduce

Compile a flutter app with XCode 9 for iOS > 9.0 with only iPhones allowed.

## Logs

The app runs fine on Android emulator, just doesn't compile itself on IOS after upgrading from SDK 0.5.1 to SDK 0.6.0 

flutter doctor -v
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale it-IT)
    • Flutter version 0.6.0 at /Users/nicolas/flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/nicolas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Please add the full eror output.

**Comment by Nik99** [comment]
![schermata 2018-08-31 alle 18 59 04](https://user-images.githubusercontent.com/2452391/44925918-09e82d80-ad50-11e8-8f77-720fb517060f.png)

This is what i get when i try to compile my app with XCode, there is no full error report. This happens when i try to archive the app on a new build to publish on testflight

**Comment by Nik99** [comment]
Any news on it ?

**Comment by zoechi** [comment]
@Nik99 does the suggestion work for you?

**Comment by Nik99** [comment]
@zoechi i've done a similar thing, which includes flutter clean and Xcode clean option. I re-builded for release from the command, re-installed pod and it worked.
Thanks for the support everyone, @zoechi @MaikuB

**Comment by zoechi** [comment]
Thanks for the update. Great to hear.
Closing as dup of #16604 then.

**Comment by TheLeaf-code** [comment]
I have the same exact problem, except the instructions detailed in this forum have not solved it. Does anyone know of other solutions that could fix this problem?
