### ISSUE TITLE
build-name and build-number ignored

### ISSUE THREAD

**Issue by marnberg** [flutter/flutter#21279]
Build name and build number is ignored during flutter build process after upgrading to beta v0.6.0. This was working in v0.5.1 in our CI system. Now this is causing upload issues to TestFlight since CFBundleVersion needs to increment with each build.
 
## Steps to Reproduce
1. flutter build ios --build-name=1.0.1 --build-number=203
2. Open iOS Info.plist
Expected: 
	<key>CFBundleShortVersionString</key>
	<string>1.0.1</string>
	<key>CFBundleVersion</key>
	<string>203</string>
Actual:
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
3. Open Android build.gradle
Expected: 
        versionCode 203
        versionName "1.0.1"
Actual:
        versionCode 1
        versionName "1.0"

>flutter analyze
Running "flutter packages get" in tokui...                   1.2s
Analyzing xxxxxx...                                               
No issues found! (ran in 8.9s)

>flutter doctor -v
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.6.0 at /Users/martin/Documents/Repos/flutter
    • Framework revision 9299c02cf7 (2 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/martin/Library/Android/sdk
    • Android NDK at /Users/martin/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone 8 • 28FA9FF9-3D19-4139-A771-685EE26DF68A • ios • iOS 11.4 (simulator)

• No issues found!

**Comment by zoechi** [comment]
Closing as dup of #21146

**Comment by zoechi** [comment]
I suggest you create a new Flutter project and compare the files 
`android/local.properties`
`android/app/build.gradle` (`defaultConfig`) section.

If you update the files in your old project according to the new project it will start working again.

**Comment by marnberg** [comment]
if build-name and build-number are ignored they should be removed from 'flutter build' options

**Comment by marnberg** [comment]
Thank you, this fixed most of the issues. looks like flutter.versionName is always reverting to flutter.versionName=0.1.0 in android/local.properties

**Comment by zoechi** [comment]
That is copied from `pubspec.yaml`
![image](https://user-images.githubusercontent.com/405837/44931446-e5954c80-ad61-11e8-8c41-5ffa7bf1aac4.png)

I assume this is solved then.

**Comment by nathansamson** [comment]
I am confused by this.
The original report mentions TestFlight indicating iOS builds are not working, but the fixes for the issue + the linked isuse is for android
(I am having the issue for iOS)

**Comment by nathansamson** [comment]
But comparing to a new flutter project and checking the Info.plist generated from that fixed the issue...

Are there other (subtle) things like that that we need to take care when upgrading to newer flutter releases? Because syncing the ios and android/ directories everytime will be cumbersome and error prone...

**Comment by marnberg** [comment]
The fix is both for Android and iOS, When the template changes in new flutter versions it can be tricky to figure out what has changed and how to upgrade your existing project. This is something I'm now aware of and look out for now, The easiest way to verify the fix after upgrading is to create a new flutter app and then compare the your template with the new template on both iOS and Android.

**Comment by zoechi** [comment]
I got the impression the Flutter team is working on finding better solutions than manually syncing these files, but for now this is the way to go.

**Comment by nathansamson** [comment]
I just did it for my (I suddenly had problems with android building as well, not sure why), and it is a relatively cumbersome process, so Ideally this would be improved in the future :)

**Comment by nathansamson** [comment]
Ok my other problem is related to https://github.com/flutter/flutter/pull/23397/files

**Comment by harithany** [comment]
just change version in pubspec.yaml and then in terminal "flutter build ios " and go to xcode you will see new version in build setting
