### ISSUE TITLE
Shape/Border overdrawn by Widget

### ISSUE THREAD

**Issue by flowhorn** [flutter/flutter#21284]
The Shape or Border is overdrawn by other Widgets like the Container or AppBar Widget.
This behaviour exists since  v0.7.1, in v0.7.0 this wasn't happening.

In the example the material widget is overdrawn by the appbar. In reality it should have rounded Corners at the top. One use case where my material widget had rounded corners was when showing rounded bottom sheets.

```dart
Material(
      color: Colors.red,
      borderRadius: BorderRadius.only(
          topLeft: Radius.circular(24.0), topRight: Radius.circular(24.0)),
      child: Column(
        children: <Widget>[
          AppBar(
            title: Text("Title"),
          ),
          ListTile(
            title: Text("Item1"),
          ),
        ],
      ),
    );
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

A screenshot would be helpful as well.

**Comment by flowhorn** [comment]
Sure, that's not a problem.
Here is the output of flutter doctor -v

> [√] Flutter (Channel dev, v0.7.5, on Microsoft Windows [Version 10.0.17134.228], locale de-DE)
    • Flutter version 0.7.5 at C:\Development\flutter
    • Framework revision eab5cd9853 (2 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

>[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at G:\Porgrammdaten\Android_Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = G:\Porgrammdaten\Android_Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

>[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

>[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

>• No issues found!


So here is the example with the bottomsheet, the corners are rounded using this code:
```dart
showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return Container(
            height: 250.0,
            color: Colors.red,
            child: Material(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(24.0)),
              ),
              child: SingleChildScrollView(
                child: Column(
                  children: <Widget>[
                    AppBar(
                      title: Text("Header"),
                    ), //Removing this shows the difference
                    ListTile(
                        title: Text(
                      "Item1",
                    )),
                    ListTile(
                        title: Text(
                      "Item2",
                    )),
                    ListTile(
                        title: Text(
                      "Item3",
                    )),
                    ListTile(
                        title: Text(
                      "Item4",
                    )),
                  ],
                ),
              ),
              color: Colors.white,
            ),
          );
        });
```

And the two screenshots, one with the AppBar(which shows the issue) and one without. In pratice the background is transparent, but i wanted to make it as clear as possible. In v0.7.0 and earlier the rounded corner is not overdrawn.

![screenshot_1535823410](https://user-images.githubusercontent.com/37595126/44948526-f8218b80-ae1e-11e8-91d2-0441b62990f5.png)
![screenshot_1535823405](https://user-images.githubusercontent.com/37595126/44948525-f8218b80-ae1e-11e8-9fb9-0524ac8c3d1c.png)

**Comment by HansMuller** [comment]
Material not longer clips (to its shape) by default.  You'll need to specify `clipBehavior: Clip.antiaAlias`.

cc @liyuqian

**Comment by liyuqian** [comment]
Yes, please see https://groups.google.com/forum/#!searchin/flutter-dev/liyuqian@google.com%7Csort:date/flutter-dev/XMHE0XdsXxI/nonrNQpbBAAJ for why we disabled clip by default.

**Comment by flowhorn** [comment]
That solves everything, thank you for the useful information.
Now everything works as expected.

**Comment by liyuqian** [comment]
No problem. Thank you for using Flutter!
