### ISSUE TITLE
get documents in array of strings cloud in flutter using cloud firestore

### ISSUE THREAD

**Issue by ahmedelsayedkhalafallah** [flutter/flutter#21281]
it seems it is harder than i think, i am building a flutter app and using cloud firestore as a database that is my simple database looks like
<img src="https://i.stack.imgur.com/32P6i.png">
what i want is to retrieve all documents of the collection "DriverList" in an array of string and retrieve its data in an array of object of driver class all the examples i found was building a new screen with widget that has a stream and a stream builder and return the content into a ListView

**Comment by zoechi** [comment]
Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by ahmedelsayedkhalafallah** [comment]
it is not an error i want help in building my app
the output of flutter doctor
`/home/ahmed/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0`
i have already asked my question on stackoverflow but i got no answer
https://stackoverflow.com/questions/52107009/get-documents-in-array-of-strings-cloud-in-flutter-using-cloud-firestore

**Comment by zoechi** [comment]
If you want support it's still helpful to know what Flutter version, IDE, OS, you have.
It also tells if a feature should be available in your Flutter version or not. 

Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by ahmedelsayedkhalafallah** [comment]
i attached the link of my question on stackoverflow in the previous comment but i had no answer

**Comment by zoechi** [comment]
Why did you delete the SO question?

**Comment by kroikie** [comment]
@ahmedelsayedkhalafallah

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/677. Any further collaboration will be done there.
