### ISSUE TITLE
a new route is pushed, it doesn't pop anymore

### ISSUE THREAD

**Issue by asapJ** [flutter/flutter#21297]
so after recently upgrading flutter,  i rebuilt my app without any errors but noticed the bugs below.

************************************************************************

1. When a new route is pushed, it doesn't pop anymore, just hangs there ( even when using hard or soft keys). (fixed)
2. listSync not working in release build.

**Comment by xster** [comment]
Can you give us more details wrt 1? Is it done via Navigator.of(context).pop? Any repro code would be very helpful. 

Tentatively adding today tag.

**Comment by Hixie** [comment]
Please file separate bugs for each issue, and provide test cases demonstrating the problems. We definitely test pushing routes and showing dialogs with every build, so the situation is presumably a bit more complicated than them just not working. :-)

**Comment by asapJ** [comment]
@xster yes used Navigator.of(context).pop.. worked in debug mode, but twice i built for release it was unstable. 

Fixed the route not poping issue:
so i checked out master branch, then back to beta, and re-ran the upgrade. and it works now.
i still can't figure out what really happen. maybe the initial upgrade didn't complete?

TODO:
listSync() method  not yet working in release build, but works in debug mode

**Comment by asapJ** [comment]
@xster Yes that method,  it lists out the files in debug mode but doesn't work in release build

**Comment by zoechi** [comment]
What does "not working" mean exactly? Is there an error? Is the result empty?

**Comment by zoechi** [comment]
There is already an issue for `listSync` #21242

**Comment by asapJ** [comment]
it "works" in debug mode.
I.e when you are debugging,  it lists out the files you want without errors.
but after you run "flutter build apk" for release mode and install the app on a device, it doesn't list them anymore.

**Comment by zoechi** [comment]
You don't get an error/exception?

**Comment by asapJ** [comment]
no error,  no exceptions.. 
I said when connected via adb and debugging it work! 
how can I see error when it works while debugging? 
after building apk for release  it stops working!

**Comment by zoechi** [comment]
Perhaps `adb logcat` shows something.

**Comment by zoechi** [comment]
#21297 is another one where debug mode works but release mode doesn't on iOS. There might be a common cause.

**Comment by zoechi** [comment]
I updated the title so that this one is now only about the routing issue and #21242 for the `listSync` issue.

**Comment by asapJ** [comment]
The same route popping issue resurface again,  and it's getting really  annoying.. Builds from 0.6.0 upwards are really inconsistent(tried all of them and same issue) . Currently reverted back to 0.5.1 which I must say is the last stable build and all seems back to normal. 

I think this problem comes as a result of the reduction in release binary, reducing binary is not relevant if it makes release APKs very unstable.

**Comment by asapJ** [comment]
@Hixie @zoechi @ianloic @paulcbetts 
Have you considered this route pop issue yet?  
After keen observations, Here's in depth details how it works.

During debug mode,  the routes pop as expected.
After building a release APK, the routes will function as good only once or twice and after that is freezes,  now you will have to go to settings>apps> your app> and clear app data, before before it will begin working again..

Hope this helps

**Comment by Hixie** [comment]
Do you have sample code we can examine that reproduces this problem?

**Comment by Hixie** [comment]
@asapJ We don't really understand the issue. If you could provide a sample app that reproduces the issue we would be happy to look into it.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
