### ISSUE TITLE
Feature Request: SliverAppBar should have the ability to set minimum height

### ISSUE THREAD

**Issue by wamry** [flutter/flutter#21298]
Same as there is the ability to set expandedHeight, there should be a way to set the minimum, I understand the problem that it can't be less than a certain height, but you add it as a constraint I guess.

**Comment by mirmahfuz99** [comment]
I think bottom and Flexible space is enough good . 
   `bottom: PreferredSize(child: new Text('Data'), preferredSize: Size.fromHeight(50.0)),`

` flexibleSpace: Container(
                padding: EdgeInsets.all(10),
                height: 340,
                width: double.infinity,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Container(
                      height: 10,  //decreas the size
                    ),
                    Container(
                      height: 10, //decrease the size
                    ),
                    Expanded(child: Container()),
                    Text('TEST'),
                  ],
                ),
                decoration: BoxDecoration(
                    image: DecorationImage(
                        image: NetworkImage('https://picsum.photos/400/400'),
                        fit: BoxFit.cover)),
              ),`

**Comment by esDotDev** [comment]
No not really, as you don't get:
* The themed styling that title gets
* Automatic scaling on drag
* Easy control of center/leftAlign

.minHeight should just be exposed, would make this widget much more flexible, as we could reserve  room for additional buttons that are not necessarily bottom aligned.  (Close, Settings, Edit, etc)
