### ISSUE TITLE
Heroes don't handle inherited properties

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#213]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Oct 20, 2015 at 17:59 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1698_

---

When we do a hero transition, we need to interpolate any inherited properties that the heroes use from the source to the target. For example, font sizes need to grow when animating from somewhere where the default text style is body1 to somewhere where the default text style is display2. Colours need to crossfade when transitioning from somewhere with primaryColor purple to primaryColor green. Etc.

**Comment by mpcomplete** [comment]
Changing the milestone, since this blocks https://github.com/flutter/flutter/issues/4436 .

**Comment by Hixie** [comment]
This is not going to happen any time soon, if ever.

**Comment by Hixie** [comment]
We are going to close this for now because it's not obvious what a solution should in fact be. We will revisit this when we have more concrete needs, e.g. from a customer.

If you want this please don't hesitate to open a new bug.
