### ISSUE TITLE
broken link to android studio

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2130]
(reported by user)

on https://flutter.io/setup/

broken link
https://flutter.io/setup/https//developer.android.com/sdk/index.html

correct link

https://developer.android.com/sdk/index.html

**Comment by krisgiesing** [comment]
https://github.com/flutter/website/pull/181

**Comment by krisgiesing** [comment]
qchong beat me to it.

**Comment by qchong** [comment]
Marking as closed.
