### ISSUE TITLE
[Feature Request] Save to Camera Roll for iOS

### ISSUE THREAD

**Issue by kmorkos** [flutter/flutter#21307]
I'm trying to save a video that I have in my app's cache to the user's camera roll. On Android this is easy to do with path_provider's `getExternalStorageDirectory`. There should be a `saveToCameraRoll` method to provide the iOS equivalent.

**Comment by zoechi** [comment]
You can make native functionality that is not yet provided by Flutter directly available to Flutter by building https://flutter.io/developing-packages/#plugin

**Comment by kmorkos** [comment]
I can submit a pull request. Do you think it would make sense to be included in the path_provider plugin?

**Comment by zoechi** [comment]
@Hixie

**Comment by kmorkos** [comment]
I created a package for saving photos/videos using PhotoKit on iOS, it can be found [here](https://pub.dartlang.org/packages/flutter_photokit). Closing this issue!
