### ISSUE TITLE
Firestore - disableNetwork and enableNetwork

### ISSUE THREAD

**Issue by GigaDroid** [flutter/flutter#21300]
For my app it would be nice to be able to enable and disable the synchronisation.
On SDKs for other platforms this is already possible, but Firestore for Flutter is missing this feature.
[https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#disableNetwork](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#disableNetwork)

**Comment by Adenosperma1** [comment]
I'd like this too! I can see that you can 'get' from cache, but I can't see if you can write to the cache. I need the app to be offline first and sync when the user wants. Enable/disable would be perfect for this!

**Comment by clemensul** [comment]
I´d like to use this feature as well.
Is there any chance to see this soon?
Thanks!

**Comment by zoechi** [comment]
@Adenosperma1 @clemensul you can increase priority by thumbs-upping the initial comment.

**Comment by jcbrtl** [comment]
Does anyone have a “not so bad” temporary solution for it? I need a way to get information directly from local cache when no internet connection. There are a big part of my app that the user is not required to be connected (in fact, the user CAN’T) and the app gets VERY SLOW as it tries to get information from the servers until it realizes that there’s no connection so it should get information from the local cache. I mean, why is it trying to communicate to the servers when there’s no connection in the first place!

**Comment by jwehrle** [comment]
This is an important feature for my app as syncing is a user option that I need to be able to turn on or off. And since this feature is present in the other implementations and officially documented I had assumed it was already part of the flutter version. This seems like a major oversight to me.

**Comment by kroikie** [comment]
@GigaDroid

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/676. Any further collaboration will be done there.
