### ISSUE TITLE
flutter packages pub publish "no pubspec.yaml file" when pubspec.yaml is present

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#21305]
We tried to publish a package, and we got an error saying `no pubspec.yaml file` even though we had one. `flutter packages pub publish --dry-run` said everything was good to be uploaded. 

Note, I have successfully published packages in other situations, even using this exact repo, so this is a very special case where _something_ is going wrong, but we're reporting the wrong error message (`no pubspec.yaml`). 

Here are the exact steps to reproduce this problem (there may be other ways to do so, but I haven't experimented with all the ways):

    git clone https://github.com/RedBrogdon/barometer
    rm -rf .git 
    # build *iOS* target
    # Recommended step rename the package name in the pubspec to something else so you don't actually publish on top of the barometer plugin.
    flutter packages pub publish

**Comment by efortuna** [comment]
cc @RedBrogdon, @kevmoo, @mit-mit 
so that we can get the right labels on this issue

**Comment by zoechi** [comment]
Can you please post the error output if there is one. 
Perhaps `flutter packages pub publish -v` reveals more information.

**Comment by natebosch** [comment]
How reliably can you reproduce this? Are you on mac?

**Comment by efortuna** [comment]
I can produce this with 100% reliability. I'm on mac, as you have to build the iOS result for this to occur. I'll get a stacktrace from running with -v in a little bit.

**Comment by natebosch** [comment]
I was not able to repro a failure
https://pub.dartlang.org/packages/barometer_test_publish

tar --version:
bsdtar 2.8.3 - libarchive 2.8.3

flutter --version:
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (2 weeks ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282

**Comment by natebosch** [comment]
Pub version (get this with `flutter packages pub run --version`)

Pub 2.1.0-dev.1.0.flutter-ccb16f7282

**Comment by zoechi** [comment]
> I'll get a stacktrace from running with -v in a little bit.

Is this still relevant?

**Comment by efortuna** [comment]
let's close. we weren't able to repro anywhere other than my own computer. :-/
