### ISSUE TITLE
Execution failed for task ':app:compileDebugRenderscript'，Andoidstudio real machine debugging error, what is this problem, compile it?

### ISSUE THREAD

**Issue by frontend-qin** [flutter/flutter#21317]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugRenderscript'.
> llvm-rs-cc is missing

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the full error output.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Ehiremengold** [comment]
![Capture](https://user-images.githubusercontent.com/47524476/68207314-834a6400-ff83-11e9-8864-318e8cf304b0.PNG)


this is the output after running flutter doctor -v

**Comment by Ehiremengold** [comment]
i'm also getting the same error. Please what can be done
