### ISSUE TITLE
UI hangs while calculating SHA256 of file

### ISSUE THREAD

**Issue by kaetemi** [flutter/flutter#21315]
We're calling the following to calculate the file hash of images before uploading them.
```
    Digest contentSha256 =
        await sha256.bind(fileImage.file.openRead()).first;
```
During this action we show a progress spinner.

This works fine under debug mode, but under release mode the UI will hang and stutter for a while when this is processing on images in the file size range of around 5MB.

Tested on Flutter 0.7.0.

Code context is as follows.

```
  /////////////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////
  /////////////////////////////////////////////////////////////////////////////
  // Image upload
  /////////////////////////////////////////////////////////////////////////////

  static int _netUploadImageReq = TalkSocket.encode("UP_IMAGE");
  @override
  Future<NetUploadImageRes> uploadImage(FileImage fileImage) async {
    // Build information on file
    BytesBuilder builder = new BytesBuilder(copy: false);
    Digest contentSha256 =
        await sha256.bind(fileImage.file.openRead()).first; // FIXME: This hangs
    await fileImage.file.openRead(0, 256).forEach(builder.add);
    String contentType = new MimeTypeResolver()
        .lookup(fileImage.file.path, headerBytes: builder.toBytes());
    int contentLength = await fileImage.file.length();

    // Create a request to upload the file
    NetUploadImageReq req = new NetUploadImageReq();
    req.fileName = fileImage.file.path;
    req.contentLength = contentLength;
    req.contentType = contentType;
    req.contentSha256 = contentSha256.bytes;

    // Fetch the pre-signed URL from the server
    TalkMessage resMessage =
        await _ts.sendRequest(_netUploadImageReq, req.writeToBuffer());
    NetUploadImageRes res = new NetUploadImageRes();
    res.mergeFromBuffer(resMessage.data);

    if (res.fileExists) {
      // File already exists, so no need to upload it again
      return res;
    }

    // Upload the file
    HttpClient httpClient = new HttpClient();
    HttpClientRequest httpRequest =
        await httpClient.openUrl(res.requestMethod, Uri.parse(res.requestUrl));
    httpRequest.headers.add("Content-Type", contentType);
    httpRequest.headers.add("Content-Length", contentLength);
    // FIXME: Spaces doesn't process this option when in pre-signed URL query
    httpRequest.headers.add('x-amz-acl', 'public-read');
    await httpRequest.addStream(fileImage.file.openRead());
    await httpRequest.flush();
    HttpClientResponse httpResponse = await httpRequest.close();
    BytesBuilder responseBuilder = new BytesBuilder(copy: false);
    await httpResponse.forEach(builder.add);
    if (httpResponse.statusCode != 200) {
      throw new NetworkException(
          "Status code ${httpResponse.statusCode}, response: ${utf8.decode(responseBuilder.toBytes())}");
    }

    // Upload successful
    return res;
  }
```

**Comment by miyoyo** [comment]
Await isn't actually going to spawn a new process and run the computation in the background, it will merely schedule the computation to be run whenever the stack is empty.

You should read on [isolates](https://docs.flutter.io/flutter/dart-isolate/dart-isolate-library.html)

**Comment by zoechi** [comment]
@kaetemi A convenience function to start an isolate provided by Flutter:
https://docs.flutter.io/flutter/foundation/compute.html

As @miyoyo stated async in Dart causes code to run concurrently in the same isolate.
To run code parallel you need to spawn an isolate and execute the code there.
Isolates usually run on a different thread.
Communication between isolates is done via message passing, therefore no state is shared, which ensures thread-safety.

Closing as working-as-intented.

**Comment by kaetemi** [comment]
@miyoyo That would depend entirely on whether the used function itself processes things off-thread or not.

Not very practical that I can't seem to use an async isolate that returns a future, though... Seems to require synchronous code, which that await call isn't.

**Comment by kaetemi** [comment]
@zoechi Noted. Although I'd assume that the file would end up streamed into the sha256 in small enough chunks, which should allow sufficient processing time in-between for the UI, rather than blocking for several seconds at a time.

**Comment by kaetemi** [comment]
@zoechi Gotcha.

This seems to work.

```
  static Digest _getContentSha256(File file) {
    DigestSink convertedSink = new DigestSink();
    ByteConversionSink fileSink = sha256.startChunkedConversion(convertedSink);
    RandomAccessFile readFile = file.openSync(mode: FileMode.read);
    Uint8List buffer = new Uint8List(65536);
    int read;
    while ((read = readFile.readIntoSync(buffer)) > 0) {
      fileSink.addSlice(buffer, 0, read, false);
    }
    fileSink.close();
    return convertedSink.value;
  }
```

```
Digest contentSha256 = await compute(_getContentSha256, fileImage.file);
```

**Comment by zoechi** [comment]
Looks good. 
For better reusability you could use use a StreamTransformer (example https://github.com/dart-lang/sdk/blob/5721d8af6d8755fa6f70f3951de2c451c57bf12f/sdk/lib/convert/line_splitter.dart)

I'd still consider moving this work to an isolate, because it will still chews on the bit of time left per frame to rebuild the screen. 
But you can always do later when performance measurement shows frame drops. No need to optimize premature.

**Comment by kaetemi** [comment]
It's using `compute` so that should be an isolate already, no?

**Comment by zoechi** [comment]
Sorry, I skipped the last line :-/
I doubt splitting **and** moving to an isolate buys you anything.

**Comment by kaetemi** [comment]
How do you read a file without a buffer?

**Comment by zoechi** [comment]
https://api.dartlang.org/stable/2.0.0/dart-io/File/readAsBytesSync.html

**Comment by kaetemi** [comment]
Until a user decides to push on a giant file. :)
