### ISSUE TITLE
Check links before deploying website

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2131]
As part of the travis CI for the website, we can check links for the website. We should fail if we encounter a 404.

See code for this: https://github.com/dart-lang/dartdoc/blob/master/tool/grind.dart#L292

**Comment by devoncarew** [comment]
+1. I just updated a whole bunch of links (https://github.com/flutter/website/pull/214), and would have linked to have a bit more confidence in the PR :)

**Comment by eseidelGoogle** [comment]
Doesn't https://www.google.com/webmasters/ do this?

**Comment by sethladd** [comment]
Here's a snippet of Dart code that checks links: https://github.com/dart-lang/dartdoc/blob/master/tool/grind.dart#L253

**Comment by eseidelGoogle** [comment]
I believe this is done now?  @mit-mit @LarkAscending.  Please re-open if not.
