### ISSUE TITLE
how can I do something when TextField focus and blur

### ISSUE THREAD

**Issue by StarOfLife** [flutter/flutter#21318]
for example,I want to put a delete button behind the TextField 。when the TextField is focused,show the button and the TextField is blur, the button is hide. I used the suffix attribute，but when TextField is blur,the button is not hide.

**Comment by zoechi** [comment]
You can pass a https://docs.flutter.io/flutter/widgets/FocusNode-class.html to TextField.
You can add listeners to FocusNode.

Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by zoechi** [comment]
Yes, if you have a support question please create a new question in Gitter, StackOverflow, Google Groups, ...
GitHub is for bug reports, feature requests, and doc improvement suggestions.

**Comment by zoechi** [comment]
It sounds like your question is answered.
I'm going to close.
Feel free to add comments anyway if something is still unclear.

**Comment by temirfe** [comment]
this this the first time I see @zoechi not asking to do flutter doctor ))
