### ISSUE TITLE
Textfield re-rendering all time

### ISSUE THREAD

**Issue by furkanvatandas** [flutter/flutter#21316]
## Steps to Reproduce

When I clicked(focused) to the "textfield widget" or closed the keyboard, why re-render all page all time? For example when I press "button widget" flutter doesn't re-render all page. You can see in the code, flutter print() when I press textfield or submit keyboard.
I'm using bloc pattern, if flutter always render like this, why I use bloc pattern.

```void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      onGenerateRoute: routes,
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        margin: EdgeInsets.all(30.0),
        child: TextField(),
      ),
    );
  }
}

Route routes(RouteSettings setting) {
  if (setting.name == "/") {
    return MaterialPageRoute(builder: (context) {
      print("MyHomePage Route");
      return MyHomePage();
    });
  }
}

**Comment by zoechi** [comment]
If the keyboard is shown hidden the screen size changes. The keyboard size is removed from the screen size. This change requires a rebuild so that your view can adapt to the new resized available space to be able to build a responsive UI. Similar to rotating the device.

**Comment by furkanvatandas** [comment]
@zoechi I understand thanks but my real problem is 

```
Route routes(RouteSettings settings) {
    if (settings.name == "/") {
      return MaterialPageRoute(builder: (context) {
        final searchBloc = SearchProvider.of(context);
        searchBloc.fetchMovies();
        return MainPage();
      });
    } 
  }
```
When textfield re-render page "searchBloc.fetchMovies();" recalling this function again. I could not solve this problem.

**Comment by zoechi** [comment]
You shouldn't fetch data in `build` or at least remember somewhere that you fetched the data already and skip it the next time.

**Comment by furkanvatandas** [comment]
@zoechi  Thank you, I will try
