### ISSUE TITLE
https://pub.dartlang.org/flutter is down

### ISSUE THREAD

**Issue by supardyke** [flutter/flutter#21312]
i need to install some packages for my taxi booking app and https://pub.dartlang.org/flutter is down for some reason, kindly contact those in charge, i have been waiting for over a week now and i have a deadline to meet.

**Comment by supardyke** [comment]
Both are not working
Running "flutter packages get" in main_app...
Got socket error trying to find package firebase_messaging at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second...

**Comment by supardyke** [comment]
And am not in china.

**Comment by zoechi** [comment]
It seems to be a network issue on your side. I haven't seen any other complaints and it also works for me.
Do you have a way to check on other computers or devices? 
Perhaps outside your company firewall/proxy (if there is one)

**Comment by cujslive** [comment]
Website is working. And `flutter packages get` is also working.

**Comment by supardyke** [comment]
its all good now, had to connect with a vpn, the team should look into this.
thanks
