### ISSUE TITLE
CircularProgressIndicator does not do anything when background Color is supplied

### ISSUE THREAD

**Issue by jagan999** [flutter/flutter#21329]
When I see the source code for CircularProgressIndicator versus LinearProgressIndicator, the circularprogressindicator does not pass the background Color to it's painter, hence this value does not do anything. 

Instead of dropping support for this parameter, it would be great if this can be fixed.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v.`?
Can you please also post a complete running minimal reproduction (main.dart).

**Comment by C-Alexander** [comment]
Hi Zoechi, 

The first widget is the usual behavior, second is probably the intended behavior, third is the linear behavior. 
![image](https://user-images.githubusercontent.com/847406/44979120-89524880-af6c-11e8-83e4-0adbd4e2478c.png)

Code involved to draw this: 
`new Scaffold(
      appBar: new AppBar(),
      body: Column(children: [
        Container(
            height: 200.0,
            width: 200.0,
            child: CircularProgressIndicator(
              backgroundColor: Colors.blue,
              valueColor: animation,
              value: 0.6,
            )),
        Container(
            height: 200.0,
            width: 200.0,
            child: FixedProgressIndicator(
              backgroundColor: Colors.blue,
              valueColor: animation,
              value: 0.6,
            )),
        Container(
            height: 200.0,
            width: 200.0,
            child: LinearProgressIndicator(
              backgroundColor: Colors.blue,
              valueColor: animation,
              value: 0.6,
            )),
      ]),
    );`

I fixed this by first painting an additional arc at the full potential size in the background color, but that means two paints. I'm guessing there's a way more efficient fix? If not, I don't mind PR-ing it.. but I just figured looking at this problem would help me learn flutter.

**Comment by netsmertia** [comment]
I am also looking to provide background color to circularProgressIndicator but It seems it is not using background color as LinearProgressIndicator. 
I have tried with minimal code.
```dart
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Just a Test"),),
      body: Center(
        child: SizedBox(
          width: 100,
          height: 100,
          child: CircularProgressIndicator(
            backgroundColor: Colors.red,
          ),
        )
      ),
    );
  }
```
Flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.0.0 at /Volumes/SSD/Development/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
....
....
```

**Comment by amsakanna** [comment]
I'm using a circle behind as a workaround for now.

```
  @override
  Widget build(BuildContext context) {
    const double kProgressIndicatorDiameter = 60.0;
    return Stack(
      alignment: Alignment.center,
      children: <Widget>[
        Container(
          width: kProgressIndicatorDiameter + 4.0,
          height: kProgressIndicatorDiameter + 4.0,
          decoration: ShapeDecoration(
            shape: CircleBorder(
              side: BorderSide(
                color: Theme.of(context).accentColor.withOpacity(0.2),
                width: 4.0,
              ),
            ),
          ),
        ),
        SizedBox(
          width: kProgressIndicatorDiameter,
          height: kProgressIndicatorDiameter,
          child: CircularProgressIndicator(
            value: 0.5,
            backgroundColor: Colors.green, // does not work
          ),
        ),
      ],
    );
  }
```

**Comment by mrsensen** [comment]
Hi, Im use Stack widget to fix this problem, but its a temporary plan.

<img width="173" alt="WX20190401-103603@2x" src="https://user-images.githubusercontent.com/12557001/55300435-02b20b00-546a-11e9-9d0c-b251b0df1a76.png">

<pre>
SizedBox(
	height: 25,
	width: 25,
	child: Stack(
	  children: <Widget>[
	    CircularProgressIndicator(
	      value: 1,
	      valueColor: new AlwaysStoppedAnimation<Color>(Colors.grey),
	    ),
	    CircularProgressIndicator(
	      value: 0.5,
	      valueColor: new AlwaysStoppedAnimation<Color>(RGColors.green),
	    ),
	  ],
	),
)
</pre>

**Comment by patelkrunal78** [comment]
You can wrap your CircularProgressIndicator inside a SizedBox widget

@override
Widget build(BuildContext context) {
return Container(
child: Center(
child: Column(
crossAxisAlignment: CrossAxisAlignment.center,
children: [
SizedBox(
child: CircularProgressIndicator(),
height: 200.0,
width: 200.0,
),
SizedBox(
child: CircularProgressIndicator(),
height: 50.0,
width: 50.0,
),
SizedBox(
child: CircularProgressIndicator(),
height: 10.0,
width: 10.0,
)
],
),
),
);

https://icetutor.com/question/how-to-set-size-to-circularprogressindicator/

**Comment by TahaTesser** [comment]
hI @jagan999 

`backgroundColor: Colors.blue,` seems to be working

```
     child: CircularProgressIndicator(
                backgroundColor: Colors.blue,
                valueColor: AlwaysStoppedAnimation<Color>(Colors.black),
                value: 0.6,
              )),
```


![flutter_06](https://user-images.githubusercontent.com/48603081/80001439-fc128d80-84db-11ea-9265-421705feee71.png)

Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
