### ISSUE TITLE
Assets with Space in file names loads only default resolution

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#21326]
## Steps to Reproduce
An asset with name "Comment filled.png" of different resolutions is set in directories as follows:

`assets/images/Comment filled.png`
`assets/images/1.5x/Comment filled.png`
`assets/images/2.0x/Comment filled.png`
`assets/images/3.0x/Comment filled.png`
`assets/images/4.0x/Comment filled.png`

`pubspec.yaml` loads `assets/images/Comment filled.png`

## What is observed?
This asset is always loaded from `assets/images/Comment filled.png`

## Expected
Asset `assets/images/4.0x/Comment filled.png` (or 3.0x) to be loaded on a FHD display

## Resolution
I tried changing the file name from `Comment filled.png` to `CommentFilled.png`. Now assets are loaded as per resolution.

**Comment by jonahwilliams** [comment]
Another potentially interesting tool issue @andrewkolos , though definitely double check if this one can be reproduced
