### ISSUE TITLE
Summary message at end of flutter doctor

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2132]
It would be really cool if `flutter doctor` printed a simple GREEN / YELLOW / RED summary of the state of your project.

The output has a lot of stuff:

```
~/flutter/testme $ flutter doctor
Downloading Dart SDK 1.14.1...
######################################################################## 100.0%
Downloading Flutter engine 6e736e7a76600640c5bd854c2fc9ed0f664ee26e...
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
Building flutter tool...
Flutter root: /Users/sethladd/Code/flutter.

[✓] iOS toolchain - develop for iOS devices (installed)
  [✓] XCode - enable development for iOS devices (installed)
    [✓] version - Xcode minimum version of 7.2.0 (installed)
    [✓] EULA - XCode end user license agreement (installed)
  [✓] brew - install additional development packages (installed)
    [✓] ideviceinstaller - discover connected iOS devices (installed)
    [✓] ios-deploy - deploy to connected iOS devices (installed)

[✓] Android toolchain - develop for Android devices (installed)
  [✓] Android SDK - enable development for Android devices (installed)

[✓] Atom development environment - a lightweight development environment for Flutter (installed)
  [✓] Atom editor (installed)
  [✓] Flutter plugin - adds Flutter specific functionality to Atom (installed)

Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 755a180af2ce521fb2646483e0e9200e8c1264dc (18 minutes ago)
engine revision : 6e736e7a76600640c5bd854c2fc9ed0f664ee26e
```

And to put a bow around it, at the very bottom, we could print:

```
[✓] All systems are a go. You are cleared to Flutter.
```

(bonus points if you make it green)

or

```
[X] Something doesn't check out. If the above diagnostics don't help resolve the issue, please file a bug when the full output of this command: https://github.com/flutter/flutter/issues/new
```

Without this summary output, it's not immediately clear if we're good to go. Also, it makes it easier to document, so we can say: "Look for this message to tell you if you are good to go, or not."

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew for thoughts

**Comment by eseidelGoogle** [comment]
I expect it's inevitable which we will want to change `flutter doctor` away from the current "tell you everything it can check and whether it is OK" to the "only tell me things which went wrong and how to fix them".  All systems like this go through this. :)  We went through it with buildbot for Chromium (now they have too many bots to bother showing a thousand green/red dots and instead just show broken issues in a list and baloons otherwise) and homebrew's doctor command does similar:

e.g.  ```
%brew doctor                                                                       [/src/engine/src]
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
```

Once I update:
```
%brew doctor                                                                                   [/src/game]
Your system is ready to brew.
```

**Comment by Hixie** [comment]
@devoncarew, did your recent work affect this?

**Comment by devoncarew** [comment]
Yeah, it's changed to emitting warnings if there are issues. Otherwise it prints install versions and paths. It's less verbose now.
