### ISSUE TITLE
Image.network wrapped with try / catch doesn't get caught

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#21330]
Not really sure If I am doing something wrong but this seems really odd, if I get a bad image to `Image.network`, by bad I mean 404 not found error, it will throw the exception and I can't seem to catch it.

The error is:
```
Exception has occurred.
Exception: HTTP request failed, statusCode: 404, https://s3.reutersmedia.net/resources_v2/images/apple-touch-icon.png
```

My catch statement is never hit, any ideas?

```
      try {
        var img = Image.network("https://s3.reutersmedia.net/resources_v2/images/apple-touch-icon.png");
        return img;
      } catch (e) {
        log.severe(e);
      }
```

**Comment by zoechi** [comment]
That's because the error is thrown in code called by Flutter, not by your code.

https://github.com/flutter/flutter/pull/18424 should allow you to handle errors.

Sorry, I don't have a code example at hand. Have to dig myself first.

**Comment by abacaj** [comment]
Yeah that would explain it. Thank you.

Gonna close because as a workaround it's possible to use my own 'NetworkImage' class which will catch the exception.

**Comment by wanjm** [comment]
@abacaj  how did you handle it; 
I think Image.network should handle for us; but now it still throw exception
