### ISSUE TITLE
FormatException: Invalid radix-16 number when trying to send a post request

### ISSUE THREAD

**Issue by mrdimaan** [flutter/flutter#21334]
I'm trying to make a post request by HttpClient but I get this error:

`FormatException: Invalid radix-16 number`
and this is the code:

```
HttpClientRequest request = await _httpClient.postUrl(
      new Uri(
        host: "http://x.x.x.x",
        port: 9080,
        path: "/api/prescriptions"
      )
  );
```
I also tried this:

```
HttpClientRequest request = await _httpClient.postUrl(
          new Uri(
            host: "http://x.x.x.x",
            port: int.parse("9080", radix: 16),
            path: "/api/prescriptions"
          )
      );
```
and it didn't work also by using post method. what am I doing wrong here?

**Comment by zoechi** [comment]
I assume this is solved because you deleted the related SO question.

**Comment by mrdimaan** [comment]
Sorry I deleted that for the IP info.

**Comment by zoechi** [comment]
Hard to tell. Probably a network issue. 
Is the server on your development machine, somewhere in the company network, or public?

**Comment by mrdimaan** [comment]
I started the server on my system and tried again. the question is why the flutter sends the request to other port!! for example when I set the port to 2378 it sends the request to port 56640
`SocketException: OS Error: Connection timed out, errno = 110, address = 172.16.1.12, port = 56640`

**Comment by mrdimaan** [comment]
Actually, I was trying it on a real device from the first time! I found out when I send the request to another server it's ok. but when I'm sending the request to my system the problem happens.

**Comment by zoechi** [comment]
Is the IP address you use the IP address of the WIFI NIC?
If you have a LAN cable attached as well, your machine will have more than one IP.

**Comment by ignertic** [comment]
How did you solve this

**Comment by mrdimaan** [comment]
@ignertic I wanted to send some files to the server and that method didn't work i used this method for sending files:
```
var request = new http.MultipartRequest(
    "POST",
    new Uri(
      scheme: SCHEME,
      host: HOST,
      port: PORT,
      path: "/api/blahblah",
    ),
  );

.....

request.files.add(
      new http.MultipartFile(
        "blah",
        prescriptionFile.readAsBytes().asStream(),
        await prescriptionFile.length(),
        filename: "some.jpg",
        contentType: new MediaType("image", "jpg"),
      ),
    );
```

most of the time if you are facing this issue the problem is an internet connection

**Comment by ignertic** [comment]
Thank you so much, i just started using flutter so i still have a lot to learn

On Jan 23, 2019, at 12:10 AM, Moein Hosseini <notifications@github.com> wrote:

@ignertic I wanted to send some files to the server and that method didn't work i used this method for sending files:

var request = new http.MultipartRequest(
    "POST",
    new Uri(
      scheme: SCHEME,
      host: HOST,
      port: PORT,
      path: "/api/blahblah",
    ),
  );

.....

request.files.add(
      new http.MultipartFile(
        "blah",
        prescriptionFile.readAsBytes().asStream(),
        await prescriptionFile.length(),
        filename: "some.jpg",
        contentType: new MediaType("image", "jpg"),
      ),
    );
most of the time if you are facing this issue the problem is an internet connection

**Comment by osamagamal65** [comment]
I used and it worked
`Uri.parse('www.example.com/api');`
