### ISSUE TITLE
More documentation needed for scrollable and viewport class.

### ISSUE THREAD

**Issue by wamry** [flutter/flutter#21336]
Can you please add more documentation for  [Scrollable](https://docs.flutter.io/flutter/widgets/Scrollable-class.html) and [Viewport](https://docs.flutter.io/flutter/widgets/Viewport-class.html), and maybe also add a basic example on how to get them to work together.

**Comment by Piinks** [comment]
Closing this as I think we have added a lot of docs over the years now. If there is something specific that is lacking, please file a new issue. Thank you!
