### ISSUE TITLE
Because every version of flutter_test from sdk depends on string_scanner 1.0.4 which doesn't match any versions, flutter_test from sdk is forbidden. So, because flutter_tst depends on flutter_test any from sdk, version solving failed？

### ISSUE THREAD

**Issue by 204138282** [flutter/flutter#21338]
## flutter doctor -v
```bash
PS G:\Flutter\flutter_tst> flutter doctor -v
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 10.0.16299.15], locale en-GB)
    • Flutter version 0.6.0 at C:\Flutter_SDK\flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\jp131\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at D:\IntelliJ IDEA\IntelliJ IDEA 2018.2.2
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[√] Connected devices (1 available)
    • Custom Phone, 5 0 0, API 21, 768x1280 • 192.168.71.101:5555 • android-x86 • Android 5.0 (API 21)

! Doctor found issues in 1 category.
```

## flutter run
```bash
PS G:\Flutter\flutter_tst> flutter run
Running "flutter packages get" in flutter_tst...
Because every version of flutter_test from sdk depends on string_scanner 1.0.4 which doesn't match any versions, flutter_test from sdk is forbidden.
So, because flutter_tst depends on flutter_test any from sdk, version solving failed.
pub get failed (1)
PS G:\Flutter\flutter_tst>
```

**Comment by zoechi** [comment]
Might be a dup of #20809 or you just need to update your dependency constraints to allow newer versions.

**Comment by 204138282** [comment]
@zoechi Thanks, I will be try.

**Comment by 204138282** [comment]
### I solved this, just 
1.  uninstalled the apk that has been run; 
2.  delete the file at `flutter/bin/cache/lockfile`
**Is't  OK!**

**Comment by zoechi** [comment]
Sounds like the issue can be closed then.
Thanks for the update.

**Comment by raqib850** [comment]
Because every version of flutter_test from sdk depends on http 0.11.3+17 and Fluttergram depends on http ^0.12.0, flutter_test from sdk is forbidden.
So, because Fluttergram depends on flutter_test any from sdk, version solving failed.
pub upgrade failed (1)


same issue , any solutions?

**Comment by sjmcdowall** [comment]
@zoechi  -- The above didn't work for me since I have a dependnecy (graphql_flutter) that IS dependent on http 0.12.0.  So when I switch back to ^0.11.3 it fails because of flutter_test being dependent on http 0.11.blahlbhalbha .. 

Any ideas??

**Comment by zoechi** [comment]
@sjmcdowall  Switch to `dev` channel
```
flutter channel dev
flutter doctor
```

**Comment by sjmcdowall** [comment]
@zoechi -- Our team manager rather rejected using the Dev Channel for our work for now, only beta and prod .. Is there a date when the test framework will be upgraded to use newer packages??  Cheers!

**Comment by zoechi** [comment]
A new beta should be out soon. 
You can use dependency_overrides to force `pub get` to accept certain package versions, but if your team manager doesn't accept `dev` he probably won't accept `dependency_overrides`.
Another alternative is to stick with older dependency versions that are compatible with `test ^0.11.3`

**Comment by kw3ku** [comment]
downgrade to http: ^0.11.3

**Comment by ride4sun** [comment]
Seems like this problem comes and goes for me. Not sure what fixed it or what makes it come back. So frustrating....

flutter_test from sdk is incompatible with test >=1.6.11

This is the complete message:
Running "flutter pub get" in bluetooth_bloc...                  

Because every version of flutter_test from sdk depends on test_api 0.2.5 and test >=1.6.11 depends on test_api 0.2.8, flutter_test from sdk is incompatible with test >=1.6.11.
So, because bluetooth_bloc depends on both test ^1.9.1 and flutter_test any from sdk, version solving failed.
pub get failed (1)



C:\Projects\chkobd>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at c:\sdks\flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 32-bit edition (version 1.30.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (2 available)
    • Nexus 5 • 03b71506f0b4f6b6 • android-arm   • Android 6.0.1 (API 23)
    • E5306   • WUJ01MFTX8       • android-arm64 • Android 6.0 (API 23)

• No issues found!

**Comment by derohimat** [comment]
try with this, work well on my mac

`flutter config --android-sdk ANDROID_HOME`

**Comment by thejppablo** [comment]
> 
> ### I solved this, just
> 
>     1. uninstalled the apk that has been run;
> 
>     2. delete the file at `flutter/bin/cache/lockfile`
>        **Is't  OK!**

HE LIIIEEESSSSSSSSSS

**Comment by Harbdollar** [comment]
Sometimes it may be because of a particular dependency you just add in your pubspec.yaml.
Try to remove the recent dependency you just add, and save it. If there error doesn't occur. Then
You just need to add the dependency without version like:  `mage:` instead of `image: ^2.1.12`

**Comment by kvt0012** [comment]
> @sjmcdowall Switch to `dev` channel
> 
> ```
> flutter channel dev
> flutter doctor
> ```

It works with me, thank you
