### ISSUE TITLE
Error in package gets 

### ISSUE THREAD

**Issue by bkanhucharan** [flutter/flutter#21333]
###  **While make changes in `pubspec.yaml` i get below error: Check**

[WhatTodo] flutter packages get
Running "flutter packages get" in WhatTodo...
flutter packages get was already running; terminating…
The current Dart SDK version is 2.1.0-dev.3.0.flutter-760a9690c2.

Because flutter_app depends on path_provider >=0.1.1 <0.4.0 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
exit code null
[WhatTodo] flutter packages get
Running "flutter packages get" in WhatTodo...
The current Dart SDK version is 2.1.0-dev.3.0.flutter-760a9690c2.

Because flutter_app depends on path_provider >=0.1.1 <0.4.0 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
exit code 1
### **CheckOut the `flutter doctor` command**

C:\Users\qaz\Desktop\WhatTodo>flutter doctor -v
[√] Flutter (Channel master, v0.7.6-pre.20, on Microsoft Windows [Version 6.1.7601], locale en-IN)
    • Flutter version 0.7.6-pre.20 at C:\native\flutter
    • Framework revision 457e7b23df (18 hours ago), 2018-09-01 04:06:46 -0700
    • Engine revision 017dafd426
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\qaz\AppData\Local\Android\sdk\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_161\bin\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
    • All Android licenses accepted.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.1
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[√] VS Code (version 1.26.1)
    • VS Code at C:\Users\qaz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • Lenovo K33a42 • 0123456789ABCDEF • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
> Because flutter_app depends on path_provider >=0.1.1 <0.4.0

Don't limit `path_provider` to `<0.4.0`
Change it to `path_provider: ">= 1.1.1 <0.5.0"`
