### ISSUE TITLE
Flutter logs mute Exceptions from Widget or Source

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#21344]
I know that a widget from an outside source throws some exceptions on a regular basis.
The **Flutter logs** will not only be polluted by that exceptions (which I do not need to see in the logs at that point), but *other exceptions will not be displayed in detail* anymore because every exception after the first one is printed like this:

```
Another exception was thrown: ...
```

I know that there is no way to achieve this currently, which means that this is a kind of feature request.  
It would really help if there was at least one way to remove these unnecessary exceptions from the logs.  
In the following I will list what I consider options (I have no idea how the logs are implemented) in a descending order (I like the first one best):

1.  A widget or another programmatic implementation that allows you to catch and mute all exceptions from a widget.
1.  An option in the logs interface or in some configuration file to ignore exceptions from a specific source, e.g. `dart_package`.
1.  Somehow being able to filter the exceptions in logs and or displaying other exceptions in full detail.

Hope that someone knows how to implement this (easily) and that I was helpful in some way.

**Comment by zoechi** [comment]
That's all quite easy for code that uses the https://pub.dartlang.org/packages/logging package.
You should request that from package maintainers who don't do that (or to use any of the other available logging packages.
Also using https://github.com/flutter/sentry or configuring a custom `FlutterError.onError` exception handler and using a Zone helped me to customize error reporting.

See also https://github.com/flutter/sentry#tips-for-catching-errors

**Comment by zoechi** [comment]
See also #19993
