### ISSUE TITLE
ProcessException: adb did not report forwarded port

### ISSUE THREAD

**Issue by cocodrino** [flutter/flutter#21340]
Hi guys, I had installed adb from my prior phone and flutter worked ok, now I'm trying to run on an emulator (because my phone is broken right now)...the emulators that I tried are memu and nox player...

both emulators includes an adb.exe in their installation, I notice that using the adb from my prior phone always appear "no device detected" when I tried to run flutter, even when running adb devices display the emulator in the list...

so I replace my sistem adb with the file include in those emulators, first memu was able to compile flutter but before send the executable to the emulators displayed an error indicating that the adb.exe was so old

```

The ADB at "C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb" is too old; please install version 1.0.32 or later.
Error launching application on N8010.

```

then I tried with the nox emulator, I did the same step, copy the adb to the Sdk folder and run...this is the message

```

Launching lib/main.dart on SM N950W in debug mode...
Initializing gradle...                                      17,4s
Resolving dependencies...                                   17,7s
Running 'gradlew assembleDebug'...                          102,2s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                  7,0s
Error waiting for a debug connection: ProcessException: adb did not report forwarded port
  Command: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb -s 127.0.0.1:62001 forward tcp:0 tcp:52313
Error launching application on SM N950W.


adb devices
List of devices attached
127.0.0.1:62001 device
```

the tcp port always chage so using adb tcp:0 tcp:xxx doesnt works, for nox I had  [this guide](https://www.bignox.com/blog/how-to-connect-android-studio-with-nox-app-player-for-android-development-and-debug/) I follow the steps without luck, for me it's an incompatibilitie between adb's...I tried downloading the android sdk again and placing that adb.exe in the sdk folder...I'm receiving the old message "no connected devices"

I didn't have so much experience with adb and android development, do you know what I need to do here???

thank you so much

**Comment by zoechi** [comment]
Any reason you don't use the emulator included with Android Studio?

**Comment by cocodrino** [comment]
hi...yes...basically I don't like android studio and I had these emulators installed in my machine...

**Comment by zoechi** [comment]
As far as I know the emulator is part of the Android SDK, not of Android Studio.
Android Studio just installs the Android SDK with it.

**Comment by zoechi** [comment]
@cocodrino is this still an issue?

**Comment by cocodrino** [comment]
yes @zoechi ...running the android emulator freeze in my machine, It keeps showing the android logo in the startup....I'm moving to linux right now and installing the sdk...I noticed that the documentation about running android emulator has changed a lot recently, it doesnt show now how run and create avd images using the temrinal...I remember that even there was even a small gui for handle emulators...

right now this doesnt look like a flutter issue any more...so I'll close the issue, at the night when I'll check my windows machine I'll try the @vinodraghu suggestion and comment here...thanks  @vinodraghu by the way...
