### ISSUE TITLE
Unable to release FlutterViewController even when there is nothing referencing it.  

### ISSUE THREAD

**Issue by nightwolf-chen** [flutter/flutter#21347]
We‘ve embed Flutter into our existing App. The problem is that we want to release FlutterViewController when there are no Flutter Pages to save some memory. But we found that FlutterViewController can't be released even there are no references to it. 

I've debug into Flutter Engine and found that there are some retain circles between FlutterChannels and FlutterViewController. I tried to break the retain circles and released FlutterViewController successfully. But there are some Skia Images leaked during the release of FlutterViewController.

I was wondering is there any official support for FlutterViewController releasing and rebuilding without those memory leak problems.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel xy_beta_v0.5.6, v0.5.6-pre.112, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by xster** [comment]
cc @jamesderlin

**Comment by seanWongs** [comment]
Is there any progress?

**Comment by jamesderlin** [comment]
cc @dnfield

**Comment by nightwolf-chen** [comment]
https://github.com/flutter/engine/pull/6464 This should be related to the retain circles.

**Comment by dnfield** [comment]
flutter/engine#6447 should make this more doable.  I'm curious about the Skia images leaking though, do you have a reproduction for that by chance?

**Comment by nightwolf-chen** [comment]
Please notice this problem was on 0.5.6 beta version.

**Comment by dnfield** [comment]
Can you try with the code in https://github.com/flutter/engine/pull/6447 and see if you're able to successfully release the view controller without memory leaks?  I don't know if I'm doing exactly what you did, but I'm pretty sure it should work with that patch.

**Comment by nightwolf-chen** [comment]
@dnfield  I didn't see the same problems so far. I will continue investigate. For now I should just close the issue for this particular problem. Thanks!

**Comment by firetheworld** [comment]
@nightwolf-chen I have this problem in flutter release 1.0
I follow this [page](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)  step by step
On different is that I  use navigation push the FlutterViewController, not present.
After several times push and pop operations, memory has increased to 300+M

**Comment by zoechi** [comment]
@firetheworld sounds like #25255

**Comment by Natoto** [comment]
https://juejin.im/post/5c24ad306fb9a049d2361cff

**Comment by krishnakirana** [comment]
Call flutterEngine?.destroyContext() when you want release flutterViewController
