### ISSUE TITLE
ListView.builder issue with Firebase

### ISSUE THREAD

**Issue by yousoff92** [flutter/flutter#21366]
I'm trying to create an expenses app to track my personal expenses. After adding new expenses, seems like there are something wrong with the listview. It shows duplicated card and the new expenses that I add is not there. But after I scroll to the bottom and go up, it is shown correctly.

<img src="https://user-images.githubusercontent.com/12526574/44995530-f1894480-afd5-11e8-91ba-1f225e0175df.gif" width="50%" height="50%">

## Steps to Reproduce

1. At listing page, notice that I have test1 - test7 and other stuffs. Click Add button.
2. At the form page, put test8 and click Submit button. It will pop to the previous page.
3. Notice that the new test8 is not there at first. There are also duplicated cards e.g lunch RM7.80.
4. Scroll to the bottom and then go to the top.
5. Notice that the new test8 is there. The duplicated cards are also gone.

## Sample source code

Source code for the listing page.
[expenses.txt](https://github.com/flutter/flutter/files/2346175/expenses.txt)

## Logs

There's nothing in the log. 

```

flutter doctor -v
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.228], locale en-MY)
    • Flutter version 0.5.1 at C:\Users\Yousoff Effendy\Documents\Software\flutter_windows_v0.5.1-beta\flutter
    • Framework revision c7ea3ca377 (3 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Yousoff Effendy\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\Yousoff Effendy\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.26.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available
```
Tested on real android device (Lolipop). I'm not connected to the device when running the flutter doctor. Let me know if there's any other info needed

**Comment by zoechi** [comment]
Can you please provide a running minimal reproduction?
The provided code imports several files that are not available and it's quite a lot of code already that should be reduce to the minimum required to demonstrate the issue,
ideally also without a dependency to Firebase. 

Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by yousoff92** [comment]
The issue is due to the autogenerated key for the state. Specifying explicit key for the stateful object solved the issue.

```
Key myKey = new Key(item.key);
expensesList.add(new ExpensesCardStateful(myKey, item));
```

item.key is the key generated from firebase.

**Comment by uzairleo** [comment]
i am facing the same issue can anyone help please
