### ISSUE TITLE
Row widget having padding issue

### ISSUE THREAD

**Issue by rahulmishra1991** [flutter/flutter#21361]
I am trying to add multiple lines of content in the row with the button but there is some padding issue...How to separate padding for Text 

    return Container(
                            alignment: Alignment.topLeft,
                            height: 30.0,
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              //mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: <Widget>[
                                Container(child: Text("${address1+', '+address2+', '+city+', '+state+', '+country}")),
                                IconButton(
                                  padding: EdgeInsets.all(1.0),
                                  icon: Icon(Icons.edit,size: 20.0,), 
                                  onPressed: () => print("a")
                                )
                              ],
                            ),
                          );

**Comment by zoechi** [comment]
Can you please add a screenshot and use this screenshot to explain what you'd like to have rendered differently. 
Please also add the output of `flutter doctor -v`.

**Comment by rahulmishra1991** [comment]
Please check shared screenshot Thanks!

![image](https://user-images.githubusercontent.com/13333370/45012213-af8eeb80-b033-11e8-96a4-802c22def94f.png)


Please check flutter version here:

![image](https://user-images.githubusercontent.com/13333370/45012253-e1a04d80-b033-11e8-9616-03ad83b6c78f.png)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by rahulmishra1991** [comment]
ok
