### ISSUE TITLE
RadioListTile横向排列的问题

### ISSUE THREAD

**Issue by xiaoming062** [flutter/flutter#21378]
From URL: https://docs.flutter.io/flutter/material/RadioListTile-class.html
RadioListTile横向排列的问题，换言之Radio怎么做到点击后面文本也响应操作

Google translate
> The problem of RadioListTile horizontally arranged, in other words, how does Radio do the click text and respond to the operation

**Comment by scscms** [comment]
[√] Flutter (Channel beta, v0.6.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
 
你什么版本？这里测试点击整行都可响应呀

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
