### ISSUE TITLE
Cannot open file,  (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by inft** [flutter/flutter#21379]
#### pubspec.yaml:
```
  assets:
    - assets/test.con
```
#### code:
```dart
File("assets/test.con").readAsString();
```

#### Console:
```
flutter: Cannot open file, path = 'assets/test.con' (OS Error: No such file or directory, errno = 2)
```
how can i use File?

**Comment by zoechi** [comment]
The docs explain that use case https://flutter.io/assets-and-images/#loading-assets

Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by inft** [comment]
But, I need use File instance, how can i do?

**Comment by zoechi** [comment]
You'll need to write it to a file after reading.
Assets are packed into the APK, they are not copied to the phone as individual files.
Why do you need it as `File`?

**Comment by inft** [comment]
I‘m sorry, my fault.
Thanks

**Comment by naveenyadav15** [comment]
My doubt is same I need do upload a default image which i provide it in assets but i don't get the path of image.

**Comment by moksh112** [comment]
I am facing the same issue,I need the abi.json of my smart contract but it is giving the same error

**Comment by mundhrakeshav** [comment]
> I am facing the same issue,I need the abi.json of my smart contract but it is giving the same error

did it work? I am facing the same issue with abi.json. 
Trying to implement web3dart.

**Comment by ibrahim-demirci** [comment]
This is worked.  
I was using this : 

 String kmlText;
    await File(path).readAsString().then((String contents) {
      kmlText = contents;
    });

But it wasn't working.  Then I use this :

 kmlText = await loadAsset(path);

Function is : 
 Future<String> loadAsset(String assetPath) async {

    return await rootBundle.loadString(assetPath);
  }

this return text in your file.
