### ISSUE TITLE
If opening observatory port on Android fails with error 13, we should check INTERNET permission

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2138]
If your `AndroidManifest.xml` is missing this line:

``` xml
<uses-permission android:name="android.permission.INTERNET"/>
```

...then when we try to hook up the observatory port we will get an error 13 (permission denied).

We should catch this case and explain what to do about it.

**Comment by eseidelGoogle** [comment]
An alternative would be to make `flutter start` be smart enough to modify the AndroidManifest.xml to add the internet and debugging permissions.  We need internet for observatory and debuggable for `flutter trace`.

**Comment by HansMuller** [comment]
I'll include ` <uses-permission android:name="android.permission.INTERNET"/>` in my next gallery commit.

**Comment by eseidelGoogle** [comment]
That's fine.  I like the auto-add approach in the long-term as it allows our developers to separate their shipping permissions from their development permissions.  Curious what Android Studio does here?

**Comment by eseidelGoogle** [comment]
Another approach would be for `flutter run --debug` to know how to check the AndroidManifest.xml for INTERNET and bail out if it's not there?  Auto-adding for --debug seems best if possible.  Thoughts @danrubel?  We just got another report of this today in https://github.com/flutter/flutter/issues/6834.

**Comment by Hixie** [comment]
Subsumed by https://github.com/flutter/flutter/issues/8421
