### ISSUE TITLE
hintStyle of InputDecorationTheme not correctly applied

### ISSUE THREAD

**Issue by fhuonder** [flutter/flutter#21385]
Hi all,

When having a custom theme with a custom InputDecorationTheme, like
```dart
new ThemeData(
    //...
    inputDecorationTheme: const InputDecorationTheme(
      focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.red)),
      enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.yellow)),
      labelStyle: TextStyle(color: Colors.yellow),
      hintStyle: TextStyle(color: Colors.red),
    ));
```
my expectation, according to the documentation of the hintStyle property, is that the label text of a focused text field gets the color of the hint style. Unfortunately it stays the color of the labelStyle. When no custom InputDecorationTheme is in use it works.

------------------------------------
**With** custom theme (expectation: in the focused case the text 'Place' should be red):
![custom_theme](https://user-images.githubusercontent.com/39723648/45040935-69ec1600-b067-11e8-9c14-6c015c23d40c.png)

------------------------------------

**Without** custom theme (where primary color is cyan and accent color is purple):
![no_custom_theme](https://user-images.githubusercontent.com/39723648/45040419-42e11480-b066-11e8-8974-917a221478b3.png)

------------------------------------

Is the configuration wrong or is it really a bug?

Regards,
Florian

**Comment by fhuonder** [comment]
Hi Hans,

The problem occurs when you use _labelText_ (instead of _hintText_) of the InputDecoration.

```dart
new TextField(
    decoration: new InputDecoration(labelText: "Hello 1"),
)
```

On focus the text moves upwards and should adopt the hintStyle, according to the documentation of the InputDecorationTheme's hintStyle (it says: _Also used for the [labelText] when the [labelText] is displayed on top of the input field (i.e., at the same location on the screen where text may be entered in the input field)._).

Hope this helps.

Regards,
Florian

**Comment by HansMuller** [comment]
Aha! You are correct, the implementation does not match the documentation.  And we're not currently testing the floating label's text style.

Although it's easy enough to "fix" this issue, it may just be a documentation bug. On the face of it, there doesn't seem to be any reason for the label's style to change when it "floats". It does change color if errorText is (also) specified or if the input decorator is disabled.

@willlarche - If a textfield's hint and label styles are different, should the label's style morph to the hint style when the textfield gets the focus and the label floats (moves upwards)?

**Comment by willlarche** [comment]
Just to make sure I understand the issue:
Given:
- There is no hint text.
- There is label text.
- There is styles for both label and hint.
Expectation:
- When the label is down, it's label style
- When the label is up, it's hint style
Result:
- Always label style.

Question:
- Should they morph back and forth?

**Comment by HansMuller** [comment]
Right, if the text field is displaying a label, should the label's style morph from the specified label-style to the hint-style when it moves up (upon focus) or back down again upon losing focus.

**Comment by willlarche** [comment]
I think, Hans, that your documentation didn't mean floating but being inline (not floating).

> Also used for the [labelText] when the [labelText] is displayed on top of the input field (i.e., **at the same location on the screen where text may be entered in the input field**)

In which case that means use the hint style when it's not floating and the label style when it is.

Certainly you shouldn't use the hint style when floating, period. But we should support having 2 different styles for the label: one for floating and one for not-floating.

The other platforms just do color and size since they can't animate font or weight changes. If Flutter can animate font or weight changes, it would be cool to allow that interpolation.

Incidentally, this underline style of text field is deprecated. Consider adding a filled background like you find in the [current guidelines](https://material.io/design/components/text-fields.html#filled-text-field). Our extensive UX research shows people are vastly more likely to properly interact with a text field that defines its touchable space than the legacy designs!

**Comment by fhuonder** [comment]
So...

- The label should not morph into the hint style when it's floating (goes upwards on selection of the text field). That figures.
- Is the default behavior wrong? In case no InputDecorationTheme is defined the label morphs when it floats (see my print screens). Is this a bug or is there another style applied in that case?
- Should the documentation be adapted so that it is more clear?
- What about the point that the style is deprecated?

**Comment by leonb2** [comment]
So, how to control the label text color now?
What properties apply to the floating and not floating state?

**Comment by clocksmith** [comment]
Is it still not possible to have a different floating text style from the inline text style on a TextField?

**Comment by patelkrunal78** [comment]
Maybe This Can Help You [Here](https://icetutor.com/question/flutter-how-to-change-textfield-hint-color)

**Comment by shinyford** [comment]
I believe this is still wrong (and that there was a misunderstanding the thread above).

The documentation states:
GIVEN
- `hintStyle` is null
- `labelText`, `labelStyle` and `hintStyle` are not null
THEN
- when the input text is empty, the label is positioned inside the input box and takes the `hintStyle`
- when the input text is not empty, the label is positioned above the input box and takes the `labelStyle`

(The discussion above had it the other way around: labelStyle when raised, hintStyle when in the input box.)

This makes sense to me, but currently is not what happens. Is there likely to be a fix? Many thanks.

**Comment by TahaTesser** [comment]
Issue still exist

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (31 hours ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.113
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by fernando-s97** [comment]
Any updates on this? I'm still facing this issue

$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.4 at /opt/libs/flutter
    • Framework revision 1aafb3a8b9 (8 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/fernando/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ASUS X00QD (mobile) • 192.168.1.39:5555 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by freitzzz** [comment]
For me the problem was the hint color was not being inherited from the `hintStyle` property. It prefers the `hintColor` given in ThemeData rather than hintStyle.

**Comment by TahaTesser** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark().copyWith(
          inputDecorationTheme: const InputDecorationTheme(
        focusedBorder:
            UnderlineInputBorder(borderSide: BorderSide(color: Colors.red)),
        enabledBorder:
            UnderlineInputBorder(borderSide: BorderSide(color: Colors.yellow)),
        labelStyle: TextStyle(color: Colors.yellow),
        hintStyle: TextStyle(color: Colors.red),
      )),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          decoration: new InputDecoration(labelText: "Hello 1"),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.128, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-18.0.pre.128 at /Users/tahatesser/Code/flutter_master
    • Framework revision 502ff3dbfe (59 minutes ago), 2021-02-02 05:41:03 -0500
    • Engine revision 7334085fc1
    • Dart version 2.12.0 (build 2.12.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos            • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by afzalali15** [comment]
It's very obvious behavior in my opinion. 

**labelText** serves two purpose, 
1. A Hint (when not focused)
2. A Title Label (when focused)

### It should take **hintStyle** in first state (Hint in the same position where user will enter) 
### and **labelStyle** in second state (Label vertically above input)

Currently, Flutter is not behaving correctly for labelStyle and hintStyle. Please put below code in DartPad and check.

_Code Sample:_
`            TextFormField(
              decoration: InputDecoration(
                labelText: 'Username',
                labelStyle: TextStyle(color: Colors.grey),
                hintStyle: TextStyle(color: Colors.red),
              ),
            ),`

[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

**Comment by ataberkw** [comment]
Document says:

```
When the [labelText] is on top of the input field, the text uses the
[hintStyle] instead.
```

But case doesn't fit when you set `floatingLabelBehavior: FloatingLabelBehavior.always`. Because it is on top even if it's focused or not.

**Comment by Sominemo** [comment]
Yup, still a problem, there's no way to set different styles for the label while it's inside the input or floating using the theme constructor 😕

**Comment by HansMuller** [comment]
@fhuonder, @shinyford, @Sominemo, @ataberkw, @afzalali15, @freitzzz, @fernando-s97 - please take a look at https://github.com/flutter/flutter/issues/86389; we're hoping that will resolve this issue.
