### ISSUE TITLE
AnimatedSize Shrink to minimal size without animation

### ISSUE THREAD

**Issue by LittleMango** [flutter/flutter#21384]
My problem is that when the size is smaller than current size，the sub widget in AnimatedSize will shrink to minimal size without animation，but the AnimatedSize will shrink with animation。

my Code is [AnimatedSizeSample.dart](https://gist.github.com/LittleMango/2df29b4c06b48b7b6da615c73804ff79)

my environment is:

Flutter 0.6.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 9299c02cf7 (3 weeks ago) • 2018-08-16 00:35:12 +0200
Engine • revision e3687f70c7
Tools • Dart 2.1.0-dev.0.0.flutter-be6309690f

I also use the Genymotion with SDK 27 and XiaoMi 6 phone with SDK 27，but it both looks the same.

**Comment by zoechi** [comment]
Same behavior with this example https://medium.com/flutter-community/flutter-working-with-animatedsize-35253ff8f16a

**Comment by zoechi** [comment]
![resize](https://user-images.githubusercontent.com/405837/45048320-e38dff00-b07b-11e8-8992-3cab923e905e.gif)

**Comment by LittleMango** [comment]
Now that I know why, when the size of the child widget changes, it has the following effect:

1. The child widget will immediately change to the final size without animation.
2. AnimatedSize will be animated to the final size.

By setting the child widget to be a picture, you can clearly see the following effect:

![sample1](https://user-images.githubusercontent.com/11766065/45066921-3f479f00-b0f3-11e8-9e56-fec75a80083b.gif)

However，I think the [API's](https://docs.flutter.io/flutter/widgets/AnimatedSize-class.html)  description is ambiguous.

**Comment by zoechi** [comment]
Lets reopen for API doc improvment.

**Comment by Martibis** [comment]
Been having this problem as well, AnimatedSize lets me animate between BoxConstraints() and BoxConstraints(maxHeight: 150) without throwing errors, with AnimatedContainer I get the error: " Cannot interpolate between finite constraints and unbounded constraint"

**Comment by Hixie** [comment]
AnimatedSize animates _its_ size. If you want to animate another widget's size, you need to make that widget into an implicitly animated widget (or rather, wrap it in one).

**Comment by Jan-pp** [comment]
Any word on this issue? I have a Text widget with a bunch of text of which I'd like to animate its height from 0 to null and back. A height of null results in a size that tightly fits the text. From 0 to null (expanding) works perfectly but from null to 0 (collapsing) doesn't animate, like others have pointed out before.

AnimatedContainer works fine if you enter a number but it doesn't accept null.

This seems such a trivial issue. I can't think of a reason why this is designed this way.
Any ideas?

**Comment by azamatdev** [comment]
To have the intended animation, I would recommend to use [AnimatedContainer](https://api.flutter.dev/flutter/widgets/AnimatedContainer-class.html). 


`class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  int _counter = 0;
  double _animatedWidth = 250.0;
  double _animatedHeight = 250.0;
  bool isResized = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
          alignment: Alignment.center,
          decoration: BoxDecoration(color: Colors.black87),
          child: AnimatedContainer(
            width: _animatedWidth,
            height: _animatedHeight,
            curve: Curves.fastOutSlowIn,
            duration: Duration(seconds: 1),
            child: InkWell(
              onTap: () {
                setState(() {
                  if (isResized) {
                    _animatedWidth = 250.0;
                    _animatedHeight = 250.0;
                    print("Back");
                    isResized = false;
                  } else {
                    _animatedWidth = 64.0;
                    _animatedHeight = 64.0;
                    print("Resized");
                    isResized = true;
                  }
                });
              },
              child: AnimatedContainer(
                width: _animatedWidth,
                height: _animatedHeight,
                curve: Curves.fastOutSlowIn,
                duration: Duration(seconds: 1),
                child: Container(
                    height: 64.0,
                    alignment: Alignment.center,
                    decoration: BoxDecoration(color: Colors.white),
                    child: Text(
                      "Some Text",
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.black),
                    )),
              ),
            ),
          )
          ),
    );
  }
}

![animation](https://user-images.githubusercontent.com/29502563/76070351-3076cc80-5fb6-11ea-85b0-4d78b5ff04b2.gif)

**Comment by Jan-pp** [comment]
AnimatedContainer doesn't allow null as a size... I would like to animate from null to 0. I have a box of text that I'd like to show and hide. When size is null it is as big as it needs to fit all the text.
