### ISSUE TITLE
complex_layout_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis is twice slow (40ms => 90ms)

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#21393]
The regression is caused by an engine roll that has only one Skia roll that has only one Skia commit.

See:
https://flutter-dashboard.appspot.com/benchmarks.html
https://github.com/flutter/flutter/commit/84ee41686d1332bdb7c0a62f2f7b883d912629ba
https://github.com/flutter/engine/pull/6144
https://skia.googlesource.com/skia.git/+log/2f53025e8bf1..09a7bb222172

**Comment by liyuqian** [comment]
CC @Hixie @csmartdalton @bsalomon

**Comment by liyuqian** [comment]
No persistent cache yet. Please see https://github.com/flutter/flutter/issues/14028

**Comment by csmartdalton86** [comment]
The slowdowns are limited strictly to Mali GPUs and NVPR (oddly enough).

If this were a Mali GPU slowdown, we would also see the average frame time slow down, not just worst_frame_rasterizer_time_millis.

**Comment by liyuqian** [comment]
Now https://github.com/flutter/flutter/issues/14028 has been closed. Why is it still slow? @chinmaygarde : we should have the persistent cache between test runs, right?

**Comment by chinmaygarde** [comment]
1. The persistent cache is only effective on devices where `GL_NUM_SHADER_BINARY_FORMATS` is > 0. Maybe these devices don't support binary shader formats?
2. Do we delete the old application before installing the new one on our bots? In that case, the cached directories are cleared.

**Comment by liyuqian** [comment]
Fixed by https://github.com/flutter/flutter/pull/27660
