### ISSUE TITLE
Heroes need to be more physical when redirected in-flight

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#214]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Oct 20, 2015 at 18:00 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1699_

---

If you are in a hero transition and tap your way to the next screen, or back to the previous screen, the heroes get new quests to go on. They should transition from one quest to the next in a velocity-continuous fashion, with the discontinuity only being in the acceleration/force.

**Comment by Hixie** [comment]
We are going to close this for now because it's not something that anybody has actually asked for. We will revisit this when we have more concrete needs, e.g. from a customer.

If you want this please don't hesitate to open a new bug.
