### ISSUE TITLE
Bad first frame when merging all engine threads on iOS

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#21403]
When merging ui, io, gpu, and platform threads on iOS this is what I get for first frame:

![image](https://user-images.githubusercontent.com/1024117/45057497-9e9da480-b04a-11e8-845d-226260ec443f.png)

Other than the first frame things seems to work fine.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/34330

**Comment by liyuqian** [comment]
@amirh : any update on this issue? Is it still happening?
