### ISSUE TITLE
Run in both OS

### ISSUE THREAD

**Issue by akshaypujari2507** [flutter/flutter#21416]
Hii Flutter Team,
I m Akshay Pujari From India I Make an Small Mobile App Using Flutter in Android Studio and Run on Android Device It seen's fine,
But now I want to Run Same App in IOS Device Using Android Studio so how can i run in my app in IOS 
Device Please Help me

System Info.
OS : I Have Windows 10

**Comment by DanTup** [comment]
@ragasubekti is correct; you unfortunately do require a Mac to compile and run for iOS:

> To develop Flutter apps for iOS, you need a Mac with Xcode 9.0 or newer

https://flutter.io/setup-macos/#install-xcode
