### ISSUE TITLE
Crash when Flutter runs ADB on Windows10

### ISSUE THREAD

**Issue by gaganalakruwan** [flutter/flutter#21422]
after install flutter i try to run default application but not run show some errors.

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --device-id=emulator-5554 lib\main.dart

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /usr/bin/xcode-select.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#2      Xcode.xcodeSelectPath (package:flutter_tools/src/ios/mac.dart:97:43)
#3      Xcode.isInstalled (package:flutter_tools/src/ios/mac.dart:106:9)
#4      Xcode.isInstalledAndMeetsVersionCheck (package:flutter_tools/src/ios/mac.dart:91:47)
#5      IOSWorkflow.canLaunchDevices (package:flutter_tools/src/ios/ios_workflow.dart:33:38)
#6      Doctor.canLaunchAnything.<anonymous closure> (package:flutter_tools/src/doctor.dart:285:58)
#7      _ListBase&Object&ListMixin.any (dart:collection/list.dart:130:15)
#8      Doctor.canLaunchAnything (package:flutter_tools/src/doctor.dart:285:22)
#9      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:385:17)
<asynchronous suspension>
#10     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:237:21)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:350:11)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:109:11)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:50:10)
#42     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#43     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

> [✓] Flutter (Channel master, v0.7.6-pre.45, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
>     • Flutter version 0.7.6-pre.45 at C:\flutter
>     • Framework revision 58d98ce31e (6 hours ago), 2018-09-04 19:36:47 -0700
>     • Engine revision de4c7a53f2
>     • Dart version 2.1.0-dev.3.0.flutter-760a9690c2
> 
> [!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
>     • Android SDK at C:\Users\Gagana\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
>     ✗ Android license status unknown.
> 
> [✓] Android Studio (version 3.0)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 23.2.1
>     • Dart plugin version 171.4424
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> 
> [!] VS Code, 32-bit edition (version 1.9.1)
>     • VS Code at C:\Program Files (x86)\Microsoft VS Code
>     • Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [!] VS Code, 64-bit edition (version 1.18.0)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected devices (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
> 
> ! Doctor found issues in 3 categories.

### 
C:\Users\Gagana>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.7.6-pre.45, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.0)
[!] VS Code, 32-bit edition (version 1.9.1)
[!] VS Code, 64-bit edition (version 1.18.0)
[√] Connected devices (1 available)

! Doctor found issues in 3 categories.

**Comment by zoechi** [comment]
Closing as dup of #21418
