### ISSUE TITLE
Referenced repository no longer available - Change path of .packages file? (Dual Development Win macOS)

### ISSUE THREAD

**Issue by Tomblarom** [flutter/flutter#21435]
I'm developing my flutter app primarily on windows. I run my code in a VM in which macOS High Sierra 10.13.6 from Techsviewer is installed, to compile it for iOS devices. Flutter generates a `.packages` file in the root of my project, every I run it.

I'm using Visual Studio Code 1.26.1 on Windows and macOS. If I close it on Windows, open the exact same directory under VS on macOS (shared through network drive or VM shared folder) and launch my app, it throws the following error:

[![GitHub Logo](https://i.imgur.com/tOii1FL.png)](https://i.imgur.com/tOii1FL.png)

```
Warning! This package referenced a Flutter repository via the .packages file that is
no longer available. The repository from which the 'flutter' tool is currently
executing will be used instead.
  running Flutter tool: /Users/nikulskik/dev/flutter
  previous reference  : /C:/dev/flutter
This can happen if you deleted or moved your copy of the Flutter repository, or
if it was on a volume that is no longer mounted or has been mounted at a
different location. Please check your system path to verify that you are running
the expected version (run 'flutter --version' to see which flutter is on your path).
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Volumes/home$/felix-platter-app/lib/main.dart
...refers, in an import, to the following library:
  /C:/dev/flutter/packages/flutter/lib/material.dart
Unfortunately, that library does not appear to exist on your file system.
Exited (sigterm)
```

A **solution** is to delete the `.packages` file before every OS switch. That's nasty and I was wondering if it's possible to set a custom `.packages` path for each OS or Visual Studio?

I want to avoid commiting to my git repo before every OS switch and work simultaneously on both OSs.

**Comment by zoechi** [comment]
That shouldn't be a problem. The `.packages` file is only valid on the machine+user where it was created. You shouldn't commit it. It's in `.gitignore` by default.

**Comment by SouravBOrion** [comment]
Took me time to figure out. LOL

**Comment by mirmahfuz99** [comment]
Just remove .packages file .It works for me .

**Comment by markronnelcamilon** [comment]
Wow, amazing. Thanks for this.

**Comment by muhamedebrahim** [comment]
> Just remove .packages file .It works for me .

Many Thanks

**Comment by affandyyy** [comment]
> Just remove .packages file .It works for me .

Where is it ?

**Comment by uzairleo** [comment]
works for me take some of my time lol

**Comment by asa-odoo** [comment]
where this file `.packages` is located?

**Comment by AkramChauhan** [comment]
> where this file `.packages` is located?

In your project's root directory.

**Comment by AkramChauhan** [comment]
Here is complete solution.
1. Delete .packages file and 
2. Run following command ` flutter pub get`

It solved issue for me.

**Comment by Lautee** [comment]
Deleting the .package file worked for me but with some extra steps. After deleting the file and run "flutter pub get" some error occured when trying to open the .flutter-plugins file and the .flutter-plugins-dependencies file. So I delete both of them (as I did with .package), run the "flutter pub get", and it works.

In my case I work in a Windows and in a Mac, and this error happened when I copy-paste the project folder from Windows to Mac, make some changes in Android Studio (in the Mac), and then copy-paste again my folder from Mac to Window.

**Comment by ChrisMukasa** [comment]
> Just remove .packages file .It works for me .
Many thanks, you save my life, 👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏

**Comment by dragooninasia** [comment]
Where is the .packages file located in the source folder.  I can't find it

**Comment by tlquan2809** [comment]
> Where is the .packages file located in the source folder. I can't find it

Show hidden files in your project's root folder.

**Comment by ChinmoyJana14** [comment]
Update the new path in env variable if needed and delete old
Delete .packages file from code repository in local and
Run following command flutter pub get

**Comment by VISHALBHAGWAT88** [comment]
if you are windows machine user please check 
Hidden Item always shows then go to your project folder root directory and then Run command flutter pub get
