### ISSUE TITLE
Need a way to position the label of the TextField

### ISSUE THREAD

**Issue by benqethan** [flutter/flutter#21437]
Right now, there is no way to position the label the same level with the decorated `TextField` like this:

Label:  TextValue

It always put on top of the `TextFiled`, which is annoying when you need more space:
```dart
new TextField(
              textAlign: TextAlign.left,
              maxLines: 1,
              enabled: false,
              decoration: const InputDecoration(
                icon: const Icon(Icons.person),
                labelText: 'From:',
                labelStyle: const TextStyle(debugLabel: "From Label Style", ),
              ),
              controller: new TextEditingController(text: "$fromAddress"),
            ),
```

It would be nice if adding a property in decoration to control this something like:
```
labelAlign: TextAlign.left
```

**Comment by zmm2tysu** [comment]
I can't agree with you anymore. :)

**Comment by justinmc** [comment]
I'm going to close this as I'm not quite sure what kind of solution is being asked for, and it hasn't attracted much activity in quite some time. If @benqethan or anyone else is still looking for something like this, please comment and we can reopen, or create a new issue.
