### ISSUE TITLE
CircularProgressIndicator causes 100% CPU on IOS simulator

### ISSUE THREAD

**Issue by mgleason** [flutter/flutter#21445]
## Steps to Reproduce

1) Create `main.dart` containing:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CircularProgressIndicator(
          value: .8,
        ),
      ),
    );
  }
}
```
2) Run it on the IOS simulator
3) Run `top -o cpu`
> PID    COMMAND      %CPU
> 47633  Runner       58.6
> 46728  backboardd   43.4

4) Replace `CircularProgressIndicator(value: .8),` with `Column(),`
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(),
      ),
    );
  }
}
```
5) Note Simulator CPU usage drops to zero.

## Flutter Doctor
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.0 at /Users/jeff/Dev/2_flutter_tool/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 7 • D840D735-FEF3-4486-940C-923FC8044EB5 • ios • iOS 11.4 (simulator)

**Comment by kirgene** [comment]
I see high CPU usage when running flutter app using [desktop-embedding](https://github.com/google/flutter-desktop-embedding) on Ubuntu 18.04.
Here is an endless animation example that demonstrates this issue:
https://gist.github.com/kirgene/00362d280430df48513ee691b2149a9e

**Comment by danydev** [comment]
This is still a problem with latest flutter and iOS simulator.

@jason-simmons do you want me to file a new issue for it?

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-IT)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by DazChong** [comment]
This issue still exist today:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (2 available)
```

**Comment by magnuswikhog** [comment]
This issue affects Android Emulators as well, CPU usage skyrockets and fans go on full blast after showing a `CircularProgressIndicator` for ~20+ seconds.

    [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.5 18F132, locale en-SE)
    [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    [✓] Android Studio (version 3.3)
    [✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    [✓] Connected device (1 available)

**Comment by kasvith** [comment]
Still exists

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)
```

**Comment by retkpop** [comment]
Still exists

**Comment by treeder** [comment]
Still exists, in particular when indeterminate.  Why was this closed?

**Comment by nicholasspencer** [comment]
I experience this regularly.

**Comment by treeder** [comment]
Also a problem on flutter web, pins the CPU in Chrome. Especially bad when dev tools is open and it looks like it's continuously logging the frame output to debug (hidden logs in dev tools, that you can unhide to see).

**Comment by xurshid29** [comment]
Still exists
