### ISSUE TITLE
 onMessage, onResume ,onLaunch don't get triggered on iOS, but work perfectly fine on android

### ISSUE THREAD

**Issue by trey-rosius** [flutter/flutter#21443]
While using the plugin `firebase_messaging: ^2.0.0`, everything works well, when receiving notifications on android devices.
 I see all print statements in `OnMessage`, `OnResume` and `OnLaunch` and the notification is the notification tray.
But on iOS, all i see is the basic(no data payload ) notification in the notification tray(I'm sending notifications from the firebase console). No Print statements are displayed in the above methods.
I can't seem to wrap my head around what's actually happening. 
When i also use the generated `FCM_TOKEN`, i get the notification(no payload data), but the methods are not triggered.

Can i please get some help @collinjackson . Please
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-CM)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✗] Android Studio (not installed)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.
```

**Comment by anderscheow** [comment]
@zoechi I encountered this problem too when "flutter_local_notifications" package is installed.

**Comment by IAmKio** [comment]
FYI: Right at the bottom of the readme: https://pub.dartlang.org/packages/flutter_local_notifications#-readme-tab-

**Comment by trey-rosius** [comment]
thanks, i saw that. I've also searched around the web for an alternative, to no avail. 
I'll be glad to know if you've finally found a solution to receive push notifications in flutter-ios

**Comment by eseidelGoogle** [comment]
Does this content of the flutter_local_notifications readme mean this bug is "works as intended"?

```
NOTE: this plugin registers itself as the delegate to handle incoming notifications and actions. This may cause problems if you're using other plugins for push notifications (e.g. firebase_messaging) as they will most likely do the same and it's only possible to register a single delegate. iOS handles showing push notifications out of the box so if you're only using this plugin to display the notification payload on Android then it's suggested that you fork the plugin code and remove the following part in the iOS code

UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
center.delegate = instance;
Unfortunately, this platform limitation does mean that it's not possible to use this plugin together other plugins for push notifications on iOS. If you are in this situation, then my only advice is that you'll need to need to look at writing customised platform-specific code for your application that may involve taking bits and pieces of code from the plugins you need.
```

Or is there something more we can do here @collinjackson @kroikie @cbracken?

**Comment by kroikie** [comment]
This is working as intended, but I wonder if there is some way we can include the functionality of the local notifications in the FCM plugin since it is likely that devs will want to do both in their apps.

**Comment by eseidelGoogle** [comment]
This bug got sent to me on Twitter again just now:
https://twitter.com/atehrosius/status/1103361199360667648

I'm not sure what the correct actions here are.  Is this bug phrased properly such that we should keep it around and encourage folks to up-vote it?  Do we know what to do if/when we eventually plan to solve it?

**Comment by geekywoman** [comment]
I am actually facing the same issue. In my case, I am using only onMessage callback. It is perfectly triggered on android, but not on iOS.

I followed all steps listed here: https://pub.dartlang.org/packages/firebase_messaging#ios-integration
and yet nothing is triggered. 

Here is my flutter implementation:
```
 void _initFirebaseMessaging() {
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        LastMessage lastMessage =
            LastMessage.fromNotificationMap(message['data']);
        Fimber.d("notification : $lastMessage");
        _displayNotification(lastMessage);
      },
    );
    _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });
    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      Fimber.d('Firebase messaging registration successful');
      _firebaseMessaging
          .subscribeToTopic('new-message-${FirebaseManager().companyName}');
    });
  }
```

I enabled firebase logs on xcode for more details.

```
NotificationManager._initFirebaseMessaging.<ac>:	 Firebase messaging registration successful
2019-03-11 16:58:11.331812+0000 Runner[438:38654] flutter: Settings registered: PushNotificationSettings {sound: true, alert: true, badge: true}
```

**Comment by kroikie** [comment]
@trey-rosius

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/671. Any further collaboration will be done there.
