### ISSUE TITLE
Text size adjustments

### ISSUE THREAD

**Issue by MarcinusX** [flutter/flutter#21451]
According to [this StackOverflow response](https://stackoverflow.com/questions/44173641/how-can-flutter-handle-dpi-text-and-image-size-differences/44181798#44181798) Text widgets should adjust their size automatically according to device pixel ratio.

I have tried the same code on different screen resolutions and the text did not adapt. Below you can see that text on a small device is significantly bigger than on the big one. I am not sure if this is a bug or expected behavior. If this is expected then how can we maintain the same font size across all devices?

## Steps to Reproduce
Run this code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  MediaQueryData queryData;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    queryData = MediaQuery.of(context);
    double devicePixelRatio = queryData.devicePixelRatio;
    TextStyle style38 = new TextStyle(
      inherit: true,
      fontSize: 38.0,
    );
    TextStyle style20 = new TextStyle(
      inherit: true,
      fontSize: 20.0,
    );
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          new Text(
            'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
            style: style38,
          ),
          new Text(
            'size (pixels): w=${queryData.size.width * devicePixelRatio}, h=${queryData.size.height * devicePixelRatio}',
            style: style20,
          ),
          new Text(
            'devicePixelRatio: $devicePixelRatio',
            style: style20,
          ),
          new Text(
            'size: w=${queryData.size.width}, h=${queryData.size.height}',
            style: style20,
          ),
          new Text(
            'textScaleFactor: w=${queryData.textScaleFactor}',
            style: style20,
          ),
        ],
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```
### Those are the results:
Nexus S:
![nexus s](https://user-images.githubusercontent.com/16286046/45115665-d0009800-b150-11e8-96b3-35af626d14c8.png)
Pixel 2:
![pixel2](https://user-images.githubusercontent.com/16286046/45115649-c5de9980-b150-11e8-8068-5707b61aa713.png)
Pixel 2 XL:
![pixel2 xl](https://user-images.githubusercontent.com/16286046/45115661-ce36d480-b150-11e8-9850-583a88975367.png)

Running on:
```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_GB.UTF-8)
```

**Comment by sir-boformer** [comment]
Actually that's exactly what happens, there is nothing wrong here.

Here is what happens when you scale down the first screenshot by 1.5, the second screenshot by 2.625:

![grafik](https://user-images.githubusercontent.com/22688477/45126038-a1df8000-b171-11e8-8b91-45de46618265.png)

Text and UI elements are exactly the same size, the size in logical pixels. Same applies to the third screenshot.

That doesn't mean that the physical size of text is the same on all 3 devices. `devicePixelRatio` is set by the manufacturer, and on Android the user can change it to a different value.

**Comment by MarcinusX** [comment]
So is there any recommended way to have a text not look small on a big screen and not look big on a small screen?

**Comment by sir-boformer** [comment]
No idea what you are talking about. The `devicePixelRatio` depends on user settings. Some users want a physically larger UI, some like small text and buttons.

Here are screenshots from the same phone:

<img src="https://user-images.githubusercontent.com/22688477/45145100-22c56880-b1c0-11e8-9d60-e2e63281dbf5.png" width="200"><img src="https://user-images.githubusercontent.com/22688477/45145117-2e189400-b1c0-11e8-9c6a-73fb6e925192.png" width="200">

If you somehow need the physical size of the device (e.g. to create a ruler app): There is no native way to get it in Flutter, you would have to use platform channels.

Getting the real size on Android seems to be unreliable: https://stackoverflow.com/questions/2193457/is-there-a-way-to-determine-android-physical-screen-height-in-cm-or-inches

**Comment by MarcinusX** [comment]
Ok, so is there any recommended way to have the same text look similar on small and big screen?
By similar, I mean that if text takes let's say 50% of big device it will take the same width on a small device?

**Comment by sir-boformer** [comment]
Ah, so you want a single-line text that takes up a fraction of the screen size?

Take a look at `FittedBox`. It wills scale its child so that it fills the parent element

**Comment by MarcinusX** [comment]
Not really. I mean, I know that it would work but I can't imagine using it for all texts in the app. I just want the texts to look similar on small screens and big screens.

From what I understand it is not possible without manual changing of the font or fontSizeFactor depending on MediaQuery data. :(

**Comment by sir-boformer** [comment]
Why do you want to do that? It's against all UI guidelines.

**Comment by MarcinusX** [comment]
My thought process was:
If I design a view to look like this on my device:
![webp net-resizeimage 1](https://user-images.githubusercontent.com/16286046/45175274-52e72880-b20d-11e8-91f8-1c2e720dc3f3.png)
Then I would like to have it look the same on a bigger device and not like this:
![webp net-resizeimage 2](https://user-images.githubusercontent.com/16286046/45175377-9b9ee180-b20d-11e8-889d-f52a9bc08998.png)
I am sorry to be so ignorant on that topic but is that really that weird to expect the same result? Or should I just accept that on big screens there is more space therfore the elements will look smaller?
I'm really trying to actually udnerstand what should I expect and what shouldn't.

**Comment by zoechi** [comment]
Bigger screens usually have poorer resolution (DPI) and therefore a bigger text is required.
Also bigger screens usually are kept further away from the eyes.
In the end it's a user setting as mentioned above. The default is a setting the manufacturer came up with that he assumed would be a good fit for the device.

I have no deep knowledge here myself. That's just what I gathered so far.

**Comment by MarcinusX** [comment]
> Bigger screens usually have poorer resolution (DPI) and therefore a bigger text is required.
Also bigger screens usually are kept further away from the eyes.

That's why I feel weird when it's the opposite :D
> The default is a setting the manufacturer came up with that he assumed would be a good fit for the device.

Well, it seems like an answer to the question then. Thank you @sir-boformer and @zoechi .

**Comment by zoechi** [comment]
> If so then you issue would still be valid.

I think it would be valid if physical DPI and scaling setting are identical, of if physical scaling setting applied to DPI would result in the same value.

**Comment by MarcinusX** [comment]
![webp net-resizeimage 4](https://user-images.githubusercontent.com/16286046/45251335-ac05a800-b344-11e8-965f-e5b812da6807.png) ![webp net-resizeimage 5](https://user-images.githubusercontent.com/16286046/45251340-adcf6b80-b344-11e8-964b-3b6e88b8bbbc.png)
Well, I guess that those screenshots prove that it actally depends on manufacturer and setting and if in the font settings they say "This is how text should look" then we shouldn't fight with that.
In my opinion issue can be closed.

**Comment by AyushAgrawal25** [comment]
Try Using AutoSizeFont
That might help.
