### ISSUE TITLE
Consider moving Run button next to target selector

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2145]
![menubar_and_main_dart_ __users_sethladd_flutter_testme_and_hangouts_-_sethladd_google_com_and_scary_error_after_running_on_nexus_5_ _issue__2144_ _flutter_flutter_and_testme_ _-bash_ _111x93](https://cloud.githubusercontent.com/assets/5479/13306855/f406a16c-db1b-11e5-8c00-8f52be7210f7.png)

There's a gulf between the button to take an action on a target (run) and the target selector. It might help to connect those two concepts together in the UI, because they are so closely related.

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
https://github.com/dart-atom/dartlang/pull/799

**Comment by sethladd** [comment]
Coolness, thanks!
