### ISSUE TITLE
List of missing features in flutter

### ISSUE THREAD

**Issue by emmanuelchucks** [flutter/flutter#21468]
This is curated list of missing features that I believe need to be made available to make flutter robust for many common production use cases. 

Some of these are been worked on but are not yet robust enough to be taken off the list. 

Feel free to add yours in the comments and I'll update the list accordingly. 

¤ Inline maps
¤ Inline Webview
¤ Full Firebase integration 
¤ GraphQL client

**Comment by jonahwilliams** [comment]
- Webview is tracked here: https://github.com/flutter/flutter/issues/730
- Maps is tracked here: https://github.com/flutter/flutter/issues/73

Please file specific and actionable bugs for firebase integration. GraphQL client sounds like a great external package, we have no plans to include one in the flutter framework.

**Comment by zoechi** [comment]
Please check http://pub.dartlang.org for packages. There are GraphQL packages (probably not full-featured yet). There is also good support for Firebase and its continually improved.
See also https://github.com/flutter/plugins/tree/master/packages
