### ISSUE TITLE
`flutter doctor` should diagnose damaged/outdated projects

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2146]
### Steps to Reproduce
* Opened an existing app in Atom
* Ran flutter doctor from command line, all checkmarks
* Went back to Atom
* Selected the 6S (simulator)
* Clicked the Run button from the toolbar

### Flutter Version

```
~/flutter/testme $ flutter --version
Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 62609669d8bf3d870424ed7f5ce7bce36155a688 (26 minutes ago)
engine revision : a53faaf7983025f83a2059021a409c6e98beb58d

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.
```

### Logs

```
flutter start --checked --debug-port=16248 --start-paused --device-id CBC62802-2CBE-4643-BD1A-AE017EBD04C8 • flutter logs
testme/ • checked mode • debug
2016-02-24 17:29:40.222 defaults[8348:876134] 
The domain/default pair of (/Users/sethladd/flutter/testme/ios/Info, CFBundleIdentifier) does not exist
2016-02-24 17:29:40.277 defaults[8349:876138] 
The domain/default pair of (/Users/sethladd/flutter/testme/ios/Info, CFBundleIdentifier) does not exist
Unable to run application
exited with code 2
```

**Comment by sethladd** [comment]
Do we have any way to check if the current project is "iOS enabled" or not? flutter doctor and version are all checkmarks, but I think some state is wrong for my app. Maybe I'm missing a file?

**Comment by chinmaygarde** [comment]
This happens when the project is damaged. In this instance, there is likely no **ios** directory (more specifically, the **Info.plist** therein). Flutter doctor analyzes the your environment but not your project. This can be fixed by specifying **flutter create** on an existing project to fill in the missing files.

**Comment by danrubel** [comment]
The `flutter run` command now gives you more concrete information and suggests how to fix the problem.
```
$ flutter run
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
```
Please reopen if there is more to be done here.
