### ISSUE TITLE
Different version for the compile (11.8.0) and runtime (15.0.1) classpath.

### ISSUE THREAD

**Issue by alciomarhollanda** [flutter/flutter#21469]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-tasks' has different version for the compile (11.8.0) and runtime (15.0.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Finished with error: Gradle build failed: 1

**Comment by zoechi** [comment]
Closing as dup of #20511 
Please upvote and comment there. 
Please also post your `flutter doctor -v` output there if you are using a different version than Flutter 0.5.8 mentioned there.

**Comment by alciomarhollanda** [comment]
Hello @zoechi, my Flutter version is   0.7.6.

how i change this version ? 

[√] Flutter (Channel master, v0.7.6-pre.56, on Microsoft Windows [versÃ£o 10.0.15063], locale pt-BR)
    • Flutter version 0.7.6-pre.56 at D:\flutter
    • Framework revision 409baff3ac (16 hours ago), 2018-09-05 21:31:29 +0100
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\alciomar.hollanda\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\alciomar.hollanda\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.26.1)
    • VS Code at C:\Users\alciomar.hollanda\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
@alciomarhollanda can you please post this in #20511 
to have all related info collected in one issue instead spread all over the place.
