### ISSUE TITLE
Bottom Bar showing a huge divot for no reason 

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#21471]
For some reason it only shows on ios not android 

![image0](https://user-images.githubusercontent.com/13773566/45128816-f0225e00-b134-11e8-8b68-62f85b50e19f.png)

That is the code 

```
appBar: new AppBar(
          title: new Text('Tasks'),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: FloatingActionButton.extended(
          elevation: 4.0,
          icon: const Icon(Icons.add),
          label: const Text('Add a task'),
          onPressed: _openAddTaskDialog,
        ),
        bottomNavigationBar: BottomAppBar(
          color: Colors.white,
          child: new Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.info),
                color: Colors.grey,
                onPressed: _showAboutDialog,
              ),
            ],
          ),
        ),
```

**Comment by jonahwilliams** [comment]
cc @amirh and @liyuqian

**Comment by amirh** [comment]
This looks like what you will get if you set BottomAppBar's shape to a `CircularNotchedRectangle`...
Just to confirm - in the snippet above you do not set the BottomAppBar's shape parameter, is that the code you used to generate the screenshot?

**Comment by EliasDeuss** [comment]
This is the same exact code but running on android

![screenshot_20180905-202521](https://user-images.githubusercontent.com/13773566/45133416-ee16ca00-b149-11e8-9000-adcbbd1297fb.jpg)

**Comment by liyuqian** [comment]
I tested on iOS simulator and iPhone 6S. They both seem to render as expected:

![flutter_01](https://user-images.githubusercontent.com/22987568/45189811-99c62580-b1ef-11e8-95c5-59dabad08b1b.png)

**Comment by EliasDeuss** [comment]
That I weird I just tried it and a simulator and it still does it. 
You can look at my full page of code here: https://github.com/isontic/Redwood/blob/master/lib/todo/todo.dart

![simulator screen shot - iphone x - 2018-09-06 at 19 01 32](https://user-images.githubusercontent.com/13773566/45194440-e61d5f80-b207-11e8-9f6c-ef2845fb7bf6.png)

**Comment by zoechi** [comment]
@EliasDeuss did you close intentionally?

**Comment by zoechi** [comment]
Looks similar to #21650

**Comment by EliasDeuss** [comment]
Yes @zoechi I recent flutter update fixed it
