### ISSUE TITLE
cloud_functions plugin - undefined parameter

### ISSUE THREAD

**Issue by raviteja1982** [flutter/flutter#21477]
I'm using   cloud_functions: ^0.0.4

when the below code executes cloud function does not receive values provided. The log from the cloud functions displays the paramerters passed as undefined for all of them. I made sure with debugging that the values are indeed being populated in the code and i have also used static data before i made a call to cloud function.  the regular http call with parameters works fine but it does not work with the cloud_functions plugin.

Any ideas what i am doing wrong here ?

```dart
resp = await CloudFunctions.instance.call(
        functionName: 'createFirebaseToken',
        parameters: <String, dynamic>{
          'uid': usr.id,
          'name': usr.displayName,
          'email': usr.mail,
        },
      );

```

this is what i see in the cloud function log in the firebase UI 

> parameters Received:  undefined, undefined, undefined

**Comment by raviteja1982** [comment]
>flutter doctor -v

[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale en-US)
    • Flutter version 0.7.3 at C:\Users\ravit\source\flutter
    • Framework revision 3b309bda07 (9 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\ravit\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = C:\Users\ravit\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

**Comment by faradie** [comment]
i'm a flutter newbie, and i want to learn.. but i have same problem like that. 

this my flutter on button code 
 CloudFunctions.instance.call(
                        functionName: "createUser",
                        parameters: <String, dynamic>{
                          "password": _pass,
                          "email": _email,
                          "phoneNumber": _noTelp,
                          "displayName": _namaPemagang,
                        });

this is my function log

Function execution took 664 ms, finished with status code: 500
Unhandled error TypeError: Cannot read property 'email' of undefined
    at exports.createUser.functions.https.onCall (/user_code/index.js:35:18)
    at /user_code/node_modules/firebase-functions/lib/providers/https.js:330:32
    at next (native)
    at fulfilled (/user_code/node_modules/firebase-functions/lib/providers/https.js:25:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
createUser | undefined
-- | --


this my flutter doctor -v

[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at E:\FlutterProject\flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\AlfinMuhammadNurulFi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: E:\apps\A Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\apps\A Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1


big thanks 👍

**Comment by diegoveloper** [comment]
Same error here, android & ios  , it looks like the parameters are not send to the cloud function.

I'm using :  cloud_functions: 0.0.5

```[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.2 18C54, locale en-PE)```

**Comment by collinjackson** [comment]
We have integration testing for this plugin, and also the API has changed. Are you still experiencing the issue?

**Comment by GolakiyaVishal** [comment]
Yes, I am still experiencing the issue

**Comment by kroikie** [comment]
@raviteja1982

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/668. Any further collaboration will be done there.
