### ISSUE TITLE
Debugging problems on Android 7.0

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#21480]
The most recent flutter updates (on this week) have made some problems with debugging for applications in android 7.0. In particular, there is no feedback between Android Studio / Intellij IDEA and the device. The only thing can see on the console (tab **_"run"_**) is the following lines after running:

**Phone LG G5 SE. Android 7.0**
```Launching lib/main.dart on LG H840 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
```
**Tablet LG  LG G Pad™ X 8.0. Android 7.0**
```Launching lib/main.dart on LG V520 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
```
You can't debug the application. It's impossible to even see tracing. Further, no interaction between studio and android device is observed. Can't also terminate the application on the device.
The most interesting thing is that with devices with android 5.* such problems aren't present:

**Samsung Galaxy S6 Edge,  Android 5.1.1**
```Launching lib/main.dart on SM G925I in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/Timeline(12673): Timeline: Activity_idle id: android.os.BinderProxy@1b24ffd1 time:23912481
Syncing files to device SM G925I...
D/        (12673): [G3D][cpomp_get_shader_from_blob_cache][compile_status: 1][shader_size: 0][ir_size: 7582]
D/        (12673): [G3D][cpomp_get_shader_from_blob_cache][compile_status: 1][shader_size: 0][ir_size: 11059]+
D/        (12673): [G3D][cpomp_get_shader_from_blob_cache][compile_status: 1][shader_size: 0][ir_size: 7582]
D/        (12673): [G3D][cpomp_get_shader_from_blob_cache][compile_status: 1][shader_size: 0][ir_size: 7582]
```
**LG G3, Android 5.0**
```Launching lib/main.dart on LG D855 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device LG D855...
I/flutter (20614): /storage/emulated/0/hsmSchemes/Scheme -- exists
I/flutter (20614): read->{
I/flutter (20614):   "uuid": "5d84d460-9620-11e8-d1cb-1d6135b0da84",
I/flutter (20614):   "name": "basicEvents",
I/flutter (20614):   "time": 1534353138859,
I/flutter (20614):   "updateTime": 1534353138859,
I/flutter (20614):   "events": {
I/flutter (20614):     "container": [
I/flutter (20614):     ]
I/flutter (20614):   },
I/flutter (20614):   "shapes": {
I/flutter (20614):     "shapes": [
I/flutter (20614):     ]
I/flutter (20614):   }
I/flutter (20614): }
```
You couldn't explain, what's the matter and how to get out of this situation, except to return to the old phone model? The situation is absolutely the same in Android Studio and Intellij IDEA. Apparently the problem with the plugin. Just in case, the result of execution of flutter doctor:
```
/home/misha/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_IL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0
```
_**NB!** I've checked this strange issue on three computers with three different versions of **Linux** (Linux Mint 17.3, 18.2 & 19.0). Everywhere the same thing is repeated. The error is regular._

**Comment by zoechi** [comment]
Have you tried with an emulator?

**Comment by micrcx** [comment]
In this case (without any connected appliances) a message box appears with the text:
_"No connected devices found; please connect a device, or see flutter.io/setup for getting started instructions"._

**Comment by micrcx** [comment]
Recent updates of flutter have solved the problem.
