### ISSUE TITLE
Push Notification in China

### ISSUE THREAD

**Issue by surbhitydy** [flutter/flutter#21488]
I have build my cross platform mobile application using Flutter and integrated push notifications also using FCM but since Google Services are blocked in China the chinese users are not getting any push notifications. 

I have searched a little and found [pushy](https://pushy.me/) as the best solution for push notification in China but seems like flutter doesn't support pushy integration yet now. So can we you please integrate [pushy](https://pushy.me/) or any other service for enabling the push notifications in China.

Thanks!

**Comment by zoechi** [comment]
Closing as dup of #13328

**Comment by pushy-me** [comment]
@surbhitydy We have just released official support for Flutter! 😄 
https://pushy.me/docs/additional-platforms/flutter

As you mentioned, you can use Pushy to deliver notifications reliably in China without relying on Google services.
