### ISSUE TITLE
Add Flutter to my iOS app 

### ISSUE THREAD

**Issue by SinglTown** [flutter/flutter#21489]
Hello, i have already added the Flutter in my iOS app, but if i delete the Launch Screen File of LaunchScreen.storyboard, it  crashed when i launch the app. I'm really don't know what happend and how to do.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by SinglTown** [comment]
[✓] Flutter (Channel master, v0.7.6-pre.45, on Mac OS X 10.13.2 17C205, locale zh-Hans-CN)
    • Flutter version 0.7.6-pre.45 at /Users/zhaochuanbao/flutter
    • Framework revision 58d98ce31e (32 hours ago), 2018-09-04 19:36:47 -0700
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 2.0.0
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.27.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (3 available)
    • rainyluoo  • 7f2b61be9fc85f6e33ec2f4c093d1ffc397e13fb • ios • iOS 11.1
    • iPhone (2) • 98b0c8a5d8c1be6af8ec0025264bd18a18e43e7b • ios • iOS 12.0
    • iPhone 7   • 40995363-94D2-4769-8829-E7E2D13C3C82     • ios • iOS 11.2 (simulator)

! Doctor found issues in 4 categories.

**Comment by zoechi** [comment]
>  it crashed when i launch the app

Can you provide any error output?
Perhaps like mentioned in https://github.com/flutter/flutter/issues/20998#issuecomment-418845807 (not sure if this works in your case - don't know iOS yet)

**Comment by SinglTown** [comment]
If I load thestartup map in the way of Launch Images Source, I have to remove the LaunchScreen File from target-> General, but if I delete it, the startup map of my APP is normal and will crash when I jump from my APP page to Flutter page. But if I load the startup map in the way of LaunchScreen.storyBoard, the Flutter page will call this LaunchScreen.storyboard first. So my native app can't display the startup map properly. I think this is a conflict.

**Comment by SinglTown** [comment]
the crash log:
*** Assertion failure in +[UIStoryboard storyboardWithName:bundle:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.33.6/UIStoryboard.m:88

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by carlank** [comment]
Hmm. Yes? But I assume this doesn't apply to me? Sorry in advance.

**Comment by SinglTown** [comment]
There is no such problem with the latest version.
