### ISSUE TITLE
flutter_maps: Activity Livecycle Event 'DISPOSE' not handled

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#21497]
Hi.

first of all I want to say that the new approach is awesome!!! I'm able to place other Flutter Widgets on top that is amazing!

I found today an interesting bug when integrating the new version into my App. Depending if I logged in with Facebook or email I got an Exception that read 

`"Cannot interpret  6 as an activity state"`

I dug a bit deeper into the java code and found that it comes from GoogleMapController.Init

```Java
  void init() {
    switch (activityState.get()) {
      case STOPPED:
        mapView.onCreate(null);
        mapView.onStart();
        mapView.onResume();
        mapView.onPause();
        mapView.onStop();
        break;
      case PAUSED:
        mapView.onCreate(null);
        mapView.onStart();
        mapView.onResume();
        mapView.onPause();
        break;
      case RESUMED:
        mapView.onCreate(null);
        mapView.onStart();
        mapView.onResume();
        break;
      case STARTED:
        mapView.onCreate(null);
        mapView.onStart();
        break;
      case CREATED:
        mapView.onCreate(null);
        break;
      default:
        throw new IllegalArgumentException(
            "Cannot interpret " + activityState.get() + " as an activity state");
    }
    registrar.activity().getApplication().registerActivityLifecycleCallbacks(this);
    mapView.getMapAsync(this);
  }
``` 

In `GoogleMapsPlugin` I found

```Java
public class GoogleMapsPlugin implements Application.ActivityLifecycleCallbacks {
  static final int CREATED = 1;
  static final int STARTED = 2;
  static final int RESUMED = 3;
  static final int PAUSED = 4;
  static final int STOPPED = 5;
  static final int DESTROYED = 6;
```

Which makes me guess that when I login with facebook the Fluttter Activity is destroyed but this isn't handled by the plugin.

I see two ways to solve this,

1. Handle DESTROYED correctly with saving the current context of the Map and restoring it
2. Don't register to the live-cycle events on AppStartup but in an `Init` function that an app can call after authentication.

If you know any workaround for now I would be happy :-)

**Comment by escamoteur** [comment]
@amirh did you know that?

**Comment by amirh** [comment]
Thanks @escamoteur, happy to read that you are already finding it useful!

And thanks for pinpointing this bug! we should definitely handle onDestroy without crashing 😄 
I'm not sure about saving the current map state, as we are probably losing the rest of the Flutter app's state on destroy.

Can you add some details about the specific flow in your application that leads to the crash? Are you trying to only show the map after the user was logged in?

Another thing I'll mention is that the maps plugin should be still considered experimental, I'm currently focusing on looking for an iOS solution so it might take me some time to get to bug fixes / new features / pull requests.

**Comment by escamoteur** [comment]
@amirh We actually really need a working map_view in our App so we have to find a solution. I have a working one using the old version with the overlay but that involves a lot of activating/deactivating the overlay to be able to show things above the map.

Yeah, I use FirebaseAuth together with the Facebok_Auth. So it starts up the browser to do the login. May App then listens for the completion of the login and does a replace_plage to show a Page that also contains the map.

I already tried to just add an empty DISTROYED case or replicating what's done on a STOP. The App then doesn't crash but also don't display the map anymore. I fear that could be a problem not only for the map but also for all AndroidViews.  As most App offer a social login I think this is a quite important issue.

Cheers
Thomas

**Comment by amirh** [comment]
It's actually somewhat surprising that `GoogleMapController#init` is called while the activity is destroyed, I would expect that the map widget will first be added to the tree after you returned from the browser, and at that point the activity should be resumed.

Are you pumping a new frame with the map just before launching the auth flow?
Will be great if you can provide a short example that reproduces the crash.

**Comment by escamoteur** [comment]
Hi @amirh, 

I did some further research and you are right `init` isn't called in a disposed state but called with a wrong/outdated livecycle state.

I added some debug output in GoogleMapsPlugin in all live cycle event handlers 

[+10520 ms] D/map_view_Plugin( 5598): onActivityPaused: ----------------------------------------------
[  +13 ms] D/map_view_Plugin( 5598): onActivityCreated: ----------------------------------------------
[   +8 ms] D/map_view_Plugin( 5598): onActivityStarted: ----------------------------------------------
[   +8 ms] D/map_view_Plugin( 5598): onActivityResumed: ----------------------------------------------
[  +22 ms] W/System  ( 5598): ClassLoader referenced unknown path: /system/app/Chrome/lib/x86
[        ] D/ApplicationLoaders( 5598): ignored Vulkan layer search path /system/app/Chrome/lib/x86:/system/app/Chrome/Chrome.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xa94c40d0
[        ] I/WebViewFactory( 5598): Loading com.android.chrome version 55.0.2883.91 (code 288309112)
[   +7 ms] I/cr_LibraryLoader( 5598): Time to load native libraries: 1 ms (timestamps 6126-6127)
[   +1 ms] I/cr_LibraryLoader( 5598): Expected native library version number "55.0.2883.91", actual native library version number "55.0.2883.91"
[  +38 ms] D/map_view_Plugin( 5598): onActivityPaused: ----------------------------------------------
[   +9 ms] D/map_view_Plugin( 5598): onActivityCreated: ----------------------------------------------
[  +14 ms] D/map_view_Plugin( 5598): onActivityStarted: ----------------------------------------------
[   +2 ms] D/map_view_Plugin( 5598): onActivityResumed: ----------------------------------------------
[   +3 ms] D/map_view_Plugin( 5598): onActivityPaused: ----------------------------------------------
[ +286 ms] D/EGL_emulation( 5598): eglMakeCurrent: 0x99bd6680: ver 3 1 (tinfo 0x7bb7e240)
[ +915 ms] D/map_view_Plugin( 5598): onActivitySaveInstanceState: ----------------------------------------------
[   +2 ms] D/EGL_emulation( 5598): eglMakeCurrent: 0x99bd6680: ver 3 1 (tinfo 0x7bb7e240)
[   +4 ms] D/map_view_Plugin( 5598): onActivityStopped: ----------------------------------------------
[   +2 ms] D/map_view_Plugin( 5598): onActivitySaveInstanceState: ----------------------------------------------
[  +12 ms] D/map_view_Plugin( 5598): onActivityStopped: ----------------------------------------------
[   +2 ms] D/map_view_Plugin( 5598): onActivitySaveInstanceState: ----------------------------------------------
[   +7 ms] D/map_view_Plugin( 5598): onActivityStopped: ----------------------------------------------
[+40889 ms] D/map_view_Plugin( 5598): onActivityCreated: ----------------------------------------------
[   +4 ms] D/map_view_Plugin( 5598): onActivityStarted: ----------------------------------------------
[   +4 ms] D/map_view_Plugin( 5598): onActivityResumed: ----------------------------------------------
[  +14 ms] D/map_view_Plugin( 5598): onActivityPaused: ----------------------------------------------
[  +42 ms] D/EGL_emulation( 5598): eglMakeCurrent: 0x99bd6680: ver 3 1 (tinfo 0x7bb7e240)
[  +15 ms] D/map_view_Plugin( 5598): onActivityStarted: ----------------------------------------------
[  +33 ms] D/EGL_emulation( 5598): eglCreateContext: 0x99bf29c0: maj 3 min 1 rcv 4
[  +14 ms] D/EGL_emulation( 5598): eglMakeCurrent: 0x99bf29c0: ver 3 1 (tinfo 0x99b9e320)
[   +6 ms] E/eglCodecCommon( 5598): glUtilsParamSize: unknow param 0x000082da
[        ] E/eglCodecCommon( 5598): glUtilsParamSize: unknow param 0x000082da
[  +84 ms] D/EGL_emulation( 5598): eglMakeCurrent: 0x99bd6680: ver 3 1 (tinfo 0x7bb7e240)
[   +3 ms] D/EGL_emulation( 5598): eglMakeCurrent: 0x99bf29c0: ver 3 1 (tinfo 0xa9283970)
[ +122 ms] D/map_view_Plugin( 5598): onActivityResumed: ----------------------------------------------
[ +371 ms] D/map_view_Plugin( 5598): onActivityDestroyed: ----------------------------------------------
[        ] D/map_view_Plugin( 5598): onActivityDestroyed: ----------------------------------------------
[   +8 ms] D/map_view_Plugin( 5598): onActivityStopped: ----------------------------------------------
[        ] D/map_view_Plugin( 5598): onActivityDestroyed: ----------------------------------------------
> This was the last event change that GoogleMapsPlugin received

[ +161 ms] W/DynamiteModule( 5598): Local module descriptor class for com.google.firebase.auth not found.
[        ] W/BiChannelGoogleApi( 5598): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@a1998fe
[        ] W/DynamiteModule( 5598): Local module descriptor class for com.google.firebase.auth not found.
[   +1 ms] I/FirebaseAuth( 5598): [FirebaseAuth:] Loading module via FirebaseOptions.
[        ] I/FirebaseAuth( 5598): [FirebaseAuth:] Preparing to create service connection to gms implementation
[+1301 ms] D/FirebaseAuth( 5598): Notifying id token listeners about user ( WeeIOFjbaYhP5RB9irqKtZEzIbJ2 ).
[   +4 ms] D/FirebaseAuth( 5598): Notifying auth state listeners about user ( WeeIOFjbaYhP5RB9irqKtZEzIbJ2 ).
[   +2 ms] D/FirebaseApp( 5598): Notifying auth state listeners.
[        ] D/FirebaseApp( 5598): Notified 0 auth state listeners.

> here the login process is finished and returned a valid user

[   +6 ms] I/flutter ( 5598): ++++++++++++++++++++++++++++++++++++++++++++++++++++++FirebaseUser({providerData: [{email: tom@tom-bennett.de, uid: WeeIOFjbaYhP5RB9irqKtZEzIbJ2, providerId: firebase, displayName: Tom Bennett, photoUrl: https://graph.facebook.com/2081746548506774/picture}, {email: tom@tom-bennett.de, uid: 2081746548506774, providerId: facebook.com, displayName: Tom Bennett, photoUrl: https://graph.facebook.com/2081746548506774/picture}], providerId: firebase, photoUrl: https://graph.facebook.com/2081746548506774/picture, email: tom@tom-bennett.de, isAnonymous: false, uid: WeeIOFjbaYhP5RB9irqKtZEzIbJ2, isEmailVerified: false, displayName: Tom Bennett})
[  +15 ms] I/flutter ( 5598): signed in Tom Bennett
[   +3 ms] W/Firestore( 5598): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
[        ] W/Firestore( 5598): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
[        ] W/Firestore( 5598):
[        ] W/Firestore( 5598): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
[        ] W/Firestore( 5598): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
[        ] W/Firestore( 5598):     .setTimestampsInSnapshotsEnabled(true)
[        ] W/Firestore( 5598):     .build();
[        ] W/Firestore( 5598): firestore.setFirestoreSettings(settings);
[        ] W/Firestore( 5598):
[        ] W/Firestore( 5598): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
[        ] W/Firestore( 5598):
[        ] W/Firestore( 5598): // Old:
[        ] W/Firestore( 5598): java.util.Date date = snapshot.getDate("created_at");
[        ] W/Firestore( 5598): // New:
[        ] W/Firestore( 5598): Timestamp timestamp = snapshot.getTimestamp("created_at");
[        ] W/Firestore( 5598): java.util.Date date = timestamp.toDate();
[        ] W/Firestore( 5598):
[        ] W/Firestore( 5598): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
[   +4 ms] W/common.FileUtils( 5598): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
[        ] W/common.FileUtils( 5598): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
[   +3 ms] W/common.FileUtils( 5598): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
[        ] W/common.FileUtils( 5598): Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
[   +1 ms] W/linker  ( 5598): /system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86/libconscrypt_gmscore_jni.so: unused DT entry: type 0xf arg 0x91
[        ] V/NativeCrypto( 5598): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 279 native methods...
[   +6 ms] I/ProviderInstaller( 5598): Installed default security provider GmsCore_OpenSSL
[  +31 ms] W/art     ( 5598): Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
[        ] W/art     ( 5598): Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
[        ] W/art     ( 5598): Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
[+1202 ms] I/flutter ( 5598): Success! Event ID: a69ab6519aeb4bf5a9562bfb5e0a2d1f
>Here my app has received an AuthState changed event

[        ] I/flutter ( 5598): Before replacing loging page with main page
[  +17 ms] I/flutter ( 5598): Building MainPage
> It creates the GoogleMap Object here the activity is clearly alive but no state update

[ +121 ms] I/flutter ( 5598): Building Creating GoogleMap
>Using GoogleMap in the build method

[   +3 ms] I/flutter ( 5598): Creating MapView
>Init in GoogleMapController is called with last reported state: DESTROYED

[  +21 ms] D/map_view_init( 5598): map_view_init: 6   ----------------------------------------------
[        ] I/zzbz    ( 5598): Making Creator dynamically
[   +5 ms] I/DynamiteModule( 5598): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:219
[        ] I/DynamiteModule( 5598): Selected remote version of com.google.android.gms.maps_dynamite, version >= 219
[   +7 ms] W/System  ( 5598): ClassLoader referenced unknown path:
[        ] W/System  ( 5598): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
[   +4 ms] D/ApplicationLoaders( 5598): ignored Vulkan layer search path /system/priv-app/PrebuiltGmsCore/lib/x86:/system/fake-libs:/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk!/lib/x86:/system/lib:/vendor/lib for namespace 0xa94c4110
[  +78 ms] I/Google Maps Android API( 5598): Google Play services client version: 12451000
[   +5 ms] I/Google Maps Android API( 5598): Google Play services package version: 12521024
[  +30 ms] D/        ( 5598): HostConnection::get() New Host Connection established 0x6d976f40, tid 5692
[ +139 ms] D/        ( 5598): HostConnection::get() New Host Connection established 0x6cc7f1c0, tid 5610
>onMapCreated callback is called

[  +54 ms] I/flutter ( 5598): onMapCreated!!!!!!!!!!!!!!!!!!!!!!!!

My theory is that `GoogleMapsPlugin.registerWith` is only called with the initial activity but not updated when this activity is destroyed  and the new one is created.
**This could be a problem that applies to all plugins if they all to registration like this**

I have for now changed the 'DESTROYED` case to

```Java
      case DESTROYED:
      // This is only a preliminary fix. For the case that the newly created MapVIewController gets a wrong livecycle state
      // Withthin you know can use the map_plugin together with any authetication that destroys the Activity
        mapView.onCreate(null);
        mapView.onStart();
      break;
```
 
Which seems to fix the problem although I'M not sure if it can lead to other problems.

Would be great if we could find a final solution here.
Cheers
Thomas

**Comment by escamoteur** [comment]
@eseidel Could this be a general problem for plugins registering to live cycle events?

**Comment by eseidelGoogle** [comment]
@escamoteur @amirh or @bparrishMines would know better than I. :)

**Comment by amirh** [comment]
My first guess won't be a problem with the activity lifecycle callback registration (as the plugin is directly using a mature Android mechanism for that).

Your theory that there's some issue with the invocation of the plugin's registerWith sounds reasonable.
We will need to further investigate here, I hope to get to it sometime soon.

Are you using the standard project template? (A FlutterActivity that calls `GeneratedPluginRegistrant.registerWith(this);` in its onCreate)

**Comment by escamoteur** [comment]
@amirh yes, standard template. But Is the MainActivity.onCreate called again after the app is called over the return link from the Authprovider, meaning does the plugins get registered again?
I would recommend adding my fix for now to the code so that people can use it together with an Authprovider.



@eseidel I copied in case this is a general problem of the plugin ecosystem.

**Comment by mklim** [comment]
Thanks for the detailed report @escamoteur, it's been really helpful!

I have a consistent repro of this by modifying the example app to immediately `finish()` and then start a new `MainActivity` the very first time it's resumed.

The root issue to me looks like the code in `GoogleMapsPlugin.java` is trying to equate the `Application.ActivityLifecycleCallbacks` from `Application.registerWith` with just one instance of `MainActivity`'s lifecycle, and then using those directly to try and update the `activityState` for `GoogleMapController.java`. In cases where `MainActivity` is destroyed and recreated the callbacks appear to be called out of order since they're really being called multiple times for each of the two activities, so `state` ends up getting set incorrectly.

Here's the output from some debug logs I added to the application lifecycle callbacks in `GoogleMapsPlugin.java`, with the instance of the activity they're associated with included.

```
onCreate, registering callbacks under io.flutter.plugins.googlemapsexample.MainActivity@2f6bee6
onActivityStarted (io.flutter.plugins.googlemapsexample.MainActivity@2f6bee6)
onActivityResumed (io.flutter.plugins.googlemapsexample.MainActivity@2f6bee6)
Finishing and restarting MainActivity
onActivityPaused (io.flutter.plugins.googlemapsexample.MainActivity@2f6bee6)
onCreate, registering under io.flutter.plugins.googlemapsexample.MainActivity@edfe372
onActivityStarted (io.flutter.plugins.googlemapsexample.MainActivity@edfe372)
onActivityResumed (io.flutter.plugins.googlemapsexample.MainActivity@edfe372)
onActivityStopped (io.flutter.plugins.googlemapsexample.MainActivity@2f6bee6)
onActivityDestroyed (io.flutter.plugins.googlemapsexample.MainActivity@2f6bee6)
# open map view
creating PlatformView
activityState in init() is: 6, DESTROYED
```

Fix is in progress.

**Comment by hnvn** [comment]
Hi, it sounds like the issue I faced and I also made a pull request to address it. Hope that it's useful:
https://github.com/flutter/plugins/pull/874

**Comment by amirh** [comment]
Hi @hnvn  I'm sorry I missed your PR, and thanks for the contribution!
Left some feedback on the PR.
