### ISSUE TITLE
[Feature] could we add some http proxy configuration to flutter command? 

### ISSUE THREAD

**Issue by nicqchen01** [flutter/flutter#21494]
my computer is behind the proxy configuration URL and need credentials to connect to internet. 

without this setting it is quite hard to me to get packages.

**Comment by zoechi** [comment]
Please check if https://www.dartlang.org/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall solves your problem.

**Comment by nicqchen01** [comment]
thanks zoe. let me try it, but our company using proxy like http://xxxxxxxxxx.bat. how can i configure it use http_proxy ?

**Comment by zoechi** [comment]
> using proxy like http://xxxxxxxxxx.bat

just try it. I never had the need to configure a proxy myself and therefore no experience.

**Comment by amandadebler** [comment]
Hi nicqchen01 - that's probably a proxy configuration script that IE/Edge Windows proxy settings uses to determine whether your target address is inside the corporate network (no web proxy needed) or is external. I've mostly seen http://someinternaladdress/wpad.dat for that purpose. Those files have a fairly standard format, so you can extract the proxy address and the list of non-proxied hosts/IP ranges for your no_proxy value

Most Unix-style tools that use http_proxy and https_proxy need the actual web proxy address, which should be something like http://proxy.companyname.com:8080. https_proxy *usually* uses the same address as http_proxy, including http:// prefix.

Depending on your authentication method, http://user:pass@proxy.companyname.com:8080 *might* work, but if it's really Windows-centric and different users get different levels of external web access, you'll need something like CNTLM to do the NTLM authentication. Some newer cloud-based proxies will validate an internal IP address as belonging to a specific user for about an hour, and might only be authenticated via Active Directory. I deal with ours using a PowerShell script that runs once an hour and opens and closes an IE window in the background to a very small, external HTTPS page. Upside: no further auth needed.

**Comment by nicqchen01** [comment]
thanks, I am in block leave now, can't access computer. :<

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
I'm going to close.
Please add a comment to have it reopened.
