### ISSUE TITLE
A lightweight logging framework for Flutter.

### ISSUE THREAD

**Issue by pq** [flutter/flutter#21504]
# Flutter Logging

## Background and Motivation

**Logging Streams.** Understanding and debugging the runtime behavior of Flutter applications requires an awareness of interactions that reach far outside user-defined code.  The debugger and visual inspection tools provide powerful visibility into execution and widget and render trees yet crucial aspects remain opaque.  Practical “black boxes” include things like UI performance, network communications, and native platform channel interactions.  To remedy, we propose a unified logging mechanism that allows framework (and third-party) authors to instrument interactions to which end-users can register interest at runtime.  IDE integration will make it easy to filter and focus on relevant details.  

**A holistic view of application lifecycle.** Debug-time logging complements tools like the VM debugger and visual widget inspector to provide a window into the lifecycle of an application and the inner-workings of the Flutter framework.  Allowing for on-demand accounting of framework events would enable exploration of processes that are tricky to debug (e.g., native platform channel communication) or otherwise require additional tools (e.g., network traffic).  Providing an integrated view of Flutter application lifecycle across platform channels and the network promotes a holistic understanding of the app and remedies any possible perception that the framework is a “black box”.  Further, by providing logging API hooks, it extends that visibility to third-party frameworks who can contribute their own logging information to further fill out this integrated view of the living app.

**Framework hook discoverability / debug-ability.** Besides providing a means to capture _new_ streams of logging data, it's worth pointing out that there are a number of places where a unified logging story could further cleanup and improve the debug-ability of the existing framework.  For example, there's a big family of runtime tracing configured with a host of `debug*` flags that are hard to discover (and cumbersome for none platform developers to change).

### Framework

The envisioned Flutter Logging framework would provide a means for Flutter developers to contribute logging events that can easily be opted into by clients (IDEs and CLI tools) allowing developers to selectively enable streams of logging data to understand the behavior of certain subsystems at runtime.  Supporting goals are for the API to be ergonomic, unsurprising, performant and support opt-in monitoring of potentially noisy streams (e.g., platform channel communications, network activity, etc).  The API should be compatible with existing logging as provided by [`package:logging`](https://github.com/dart-lang/logging).  A natural approach to implementation is essentially a call through to [`dart:developer log()`](https://api.dartlang.org/stable/2.0.0/dart-developer/log.html).

#### Examples

**Platform Channel communications.**

A hook to log platform channel invocations could be added here

https://github.com/flutter/flutter/blob/cc1766d44cb15af7935678badc59dbede315c2b2/packages/flutter/lib/src/services/platform_channel.dart#L271-L273

and minimally look something like:

```dart
final Logger _logger = new Logger('platform.channel');

profile(() {
  _logger.info('Invoked method $method with arguments $arguments on channel $name');
  return true;
}());
```

where IntelliJ (assuming a subscription to the `'platform.channel'` stream), could present events in the extended logging console

![image](https://user-images.githubusercontent.com/67586/45178612-0a0e8000-b1cb-11e8-82d6-8227291afd57.png)

**Gesture hit debugging.**

Currently, gesture hits can be printed if the top-level `debugPrintHitTestResults` is manually edited.  Alternatively we might migrate this to a logger.  In that case,

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/binding.dart#L88-L92

could be replaced with something like:

```dart
assert(() {
  _logger.fine('$event: $result');
  return true;
}());
```

and hit logging can be enabled directly in the IDE without needing to modify platform source.

### Tools / IDEs

Corresponding work to support logging streams is already under-way for IntelliJ (see e.g., https://github.com/flutter/flutter-intellij/issues/2200); additional support also be added to VSCode and potentially the flutter CLI.

---

/cc @Hixie @devoncarew @jacob314 @DanTup @InMatrix

**Comment by Hixie** [comment]
Why is what we have today insufficient?

Flags like debugPrintHitTestResults can be set on the fly in user code (they're globally mutable), or from debuggers/IDEs (using evaluation in the VM, the same way the inspector does it). Fundamentally there's not really any difference between these flags and having a map of keys to booleans or some such, except that the map would be harder to optimise away.

**Comment by pq** [comment]
Closing this one for now.  We're actively working on improved logging in the IntelliJ plugin (see, e.g., https://github.com/flutter/flutter-intellij/issues/2200) and will follow-up with possible framework changes as we understand the motivating use cases better.
