### ISSUE TITLE
SIGABRT at creating FlutterViewController. (iOS)

### ISSUE THREAD

**Issue by yjoo9317** [flutter/flutter#21518]
## Steps to Reproduce

I successfully did simple launch with "Add Flutter to existing Apps".
But whenever I tried to do exact same thing from my iOS app, it outputs SIGABRT
at `FlutterViewController* flutterViewController = [[FlutterViewController alloc] init];`
It builds OK and there was no complain at all while compilation.
I might miss simple step or so?
Thanks.
## Logs

```
```

```
```

[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.0 at /Users/myname/Library/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Android NDK at /Users/myname/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/myname/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

**Comment by zoechi** [comment]
Can you please post the error output if there is any?

**Comment by yjoo9317** [comment]
unfortunately there were no error outputs except SIGABRT due to the viewer becomes nil.
After that, I was building again now it failed to build by outputting our framework kit is not found. 
so it pointed `@import ourframework` by complaining that `frameworkKit not found`
But when I checked that the framework's target membership was public.
So I have kind of a feeling that it seemed to have it linked correctly but it failed to create FlutterViewController since it became `nil`. After that, when it builds again, then the actual visibility was set (in which the visibility to our framework was broken.).
I don't know if it makes sense at all. But believe me I did reproduce the above two times already.

**Comment by yjoo9317** [comment]
I've got the following.

[VERBOSE-2:dart_vm.cc(276)] VM snapshot must be valid
[VERBOSE-3:shell.cc(205)] Check failed: vm. Must be able to initialize the VM.

**Comment by yjoo9317** [comment]
I found that it was due to setting build mode as `release` in `debug.xcconfig` since our `debug.xcconfig` includes 'release.xcconfig' in which the mode has been set as `release`.
So we added line to `debug.xcconfig` to set the mode as `debug`.
