### ISSUE TITLE
Two warnings when running the wrong flutter for a downloaded package

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#21510]
I downloaded a Flutter SDK archive and tried to run `flutter_gallery` but I used my other checkout's `flutter` tool. This was the output:

```
Warning: the 'flutter' tool you are currently running is not the one from the current directory:
  running Flutter  : /Users/ianh/dev/flutter
  current directory: /Users/ianh/dev/beta-test/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify
that you're running the expected version (run 'flutter --version' to see which flutter is on your path).

Warning! The 'flutter' tool you are currently running is from a different Flutter
repository than the one last used by this package. The repository from which the
'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/ianh/dev/flutter
  previous reference  : /Users/ianh/dev/beta-test/flutter
This can happen when you have multiple copies of flutter installed. Please check
your system path to verify that you are running the expected version (run
'flutter --version' to see which flutter is on your path).
```

**Comment by sevenOnClass** [comment]
I have the same question , I'v already set in ~/.zshrc, just like the code below. 
`export FLUTTER_HOME=/Users/Seven/Documents/company/code/yx_flutter/.flutter
export PATH=${FLUTTER_HOME}/bin:$PATH
 `
When i use the console command  "flutter run", it's ok, but using the Android Stuio it notice the message:

> Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/Seven/Downloads/iOS_Flutter_Hybrid_Project-master/Example/my_flutter/.flutter
  previous reference  : /Users/Seven/Documents/company/code/yx_flutter/.flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

**Comment by cbracken** [comment]
Curiously I see the message still exists in the code, but I'm not able to repro this  using either `flutter run` or `flutter build apk`. Steps I took were to run those commands in ~/src/donkey/flutter/examples/hello_world` using the flutter command on my path at `~/src/flutter/flutter/bin/flutter`.

Can you provide repro instructions?

**Comment by zanderso** [comment]
I'm closing this issue because it appears to be stale. Please feel free to re-open if I'm mistaken.
