### ISSUE TITLE
FloatingActionButton below ListView on iOS and Android but OK on Simulator

### ISSUE THREAD

**Issue by dmvvilela** [flutter/flutter#21521]
I built a simple app, it is a scaffold with an Appbar and a FloatingActionButton and the body composed of a Card and below inside an Expanded a ListView with some ListTile as its children, with some containers as well.

On iOS simulator it works fine, but on actual device (android AND iOS) the FloatingActionButton is below everything else until tapped.. when you tap it it goes to the front as it should.

So it is something like this (resumed - just the tree and the FloatingActionButton stuff):

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    return MaterialApp(
      title: 'Title,
      debugShowCheckedModeBanner: false,
      home: SomeClass(),
    );
  }
}

class _SomeClassState extends State<someClass> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        elevation: 2.0,
        onPressed: () => print('add button pressed'),
        tooltip: 'Add something',
      ),
      body: Column(
        children: <Widget>[
          Card(),
          Expanded(
            child: ListTileTheme(
              style: ListTileStyle.drawer,
              child: ListView(
                children: <Widget>[
                  Container(),
                  ListTile(),
                  Divider(),
                  ListTile(),
                  Divider(),
                  ListTile(), 
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

PICs (before tapping it and after tapping it):
![captura de tela 2018-09-06 as 21 13 39](https://user-images.githubusercontent.com/8460696/45191475-cf800400-b219-11e8-95f1-6cec13463c34.png)
![captura de tela 2018-09-06 as 21 13 48](https://user-images.githubusercontent.com/8460696/45191477-d444b800-b219-11e8-96ea-d913a8506fda.png)

So it is an overlay problem but not on the simulator, just devices.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by dmvvilela** [comment]
MacBook-Pro-de-Daniel:~ danvilela$ flutter doctor -v
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale pt-BR)
    • Flutter version 0.6.0 at /Users/danvilela/Code/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/danvilela/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 6 • 1A25F04A-B601-4BE6-B499-78A700D76680 • ios • iOS 11.4 (simulator)

• No issues found!

**Comment by dmvvilela** [comment]
Well, i just ran flutter upgrade and it worked fine.. sorry about that, i had upgraded not a long time ago.. here is the new flutter doctor -v:

MacBook-Pro-de-Daniel:~ danvilela$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale pt-BR)
    • Flutter version 0.7.3 at /Users/danvilela/Code/flutter
    • Framework revision 3b309bda07 (10 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/danvilela/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (3 available)
    • XT1635 02        • 0029970930                               • android-arm • Android 8.0.0 (API 26)
    • iPhone de Daniel • d68d9565a3625e69f3295b980e341b26bc867c78 • ios         • iOS 11.4.1
    • iPhone 6         • 1A25F04A-B601-4BE6-B499-78A700D76680     • ios         • iOS 11.4 (simulator)

! Doctor found issues in 1 category.
