### ISSUE TITLE
The following assertion was thrown while dispatching notifications for _NestedScrollController

### ISSUE THREAD

**Issue by bolingithub** [flutter/flutter#21527]
When I use TabBar and TabBarView inside the NestedScrollView [body], and per tab widget is ListView. The code  ` var controller = PrimaryScrollController.of(context);`  listening the ListView scroll, but it will throw the following error, when I switch the tab.

```
I/flutter ( 1320): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 1320): The following assertion was thrown while dispatching notifications for _NestedScrollController:
I/flutter ( 1320): ScrollController attached to multiple scroll views.
I/flutter ( 1320): 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 111 pos 12:
I/flutter ( 1320): '_positions.length == 1'
```
How can I solve it ？

**Comment by zoechi** [comment]
Merging with #17764
Please upvote and follow #17764 
and if possible provide information about how to reproduce (mininal code example, ...)
and the output of `flutter doctor -v`
