### ISSUE TITLE
complex_layout_scroll_perf__timeline_summary/worst_frame_rasterizer_time_millis regressed

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#21534]
https://github.com/flutter/flutter/commit/84ee41686d1332bdb7c0a62f2f7b883d912629ba (engine roll with containing only skia roll) caused a regression for benchmark `complex_layout_scroll_perf__timeline_summary/worst_frame_rasterizer_time_millis` from 50ms to 103ms.

If this change is expected the benchmark should be rebased.

/cc @cbracken @liyuqian

**Comment by liyuqian** [comment]
Duplicate of https://github.com/flutter/flutter/issues/21393

I'll rebase the benchmark.
