### ISSUE TITLE
ListView Performance and PrecomputedText

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#21536]
Prefetch Text Layout in RecyclerView

https://medium.com/androiddevelopers/prefetch-text-layout-in-recyclerview-4acf9103f438

in the above article, they're using a method that reduces render time by 95%
is this how we use "const Text" instead of "new Text"?

**Comment by zoechi** [comment]
That's not related at all. Creating an instance of `Text` doesn't render the text.
The difference between `new` and `const` here is that with `new` a new instance of `Text` is created every time the code is executed, while with `const Text('foo')` a `Text` instance with the parameter `'foo'` is created at compile time and reused every time `const Text('foo')` is executed anywhere in your app.
This is a pure Dart language feature.

Rendering text would be the job of the engine (libtxt, Skia, ...)

**Comment by p30arena** [comment]
Then why the docs say:
> Use const widgets where possible. (This is equivalent to caching a widget and re-using it.)

https://docs.flutter.io/flutter/widgets/StatefulWidget-class.html

How can I actually cache a widget?
Using Key? or GlobalKey?

**Comment by zoechi** [comment]
Flutter is able to do optimizations down the line if widgets are const.
Caching a widget instance (in a field) and returning the same instance for every call to `build()` would have a similar effect.

> How can I actually cache a widget?

Depends on the purpose.

**Comment by p30arena** [comment]
@zoechi 
we need a doc specifically concentrated on optimizations.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1965](https://github.com/flutter/website/issues/1965) via [**ZenHub**](https://www.zenhub.com/)
