### ISSUE TITLE
Dev 0.5.8 to update new one has error

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#21538]
Niyazis-MBP:capital niyazitoros$ flutter --version
Flutter 0.5.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision e4b989bf3d (4 weeks ago) • 2018-08-09 09:45:44 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2
Niyazis-MBP:capital niyazitoros$ flutter upgrade
Upgrading Flutter from /Users/niyazitoros/flutter...
From https://github.com/flutter/flutter
   5735adab5..3c5819535  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        CONTRIBUTING.md
        README.md
        analysis_options.yaml
        bin/flutter
        bin/flutter.bat
        bin/internal/engine.version
        bin/internal/goldens.version
        dev/automated_tests/pubspec.yaml
        dev/benchmarks/complex_layout/pubspec.yaml
        dev/benchmarks/microbenchmarks/pubspec.yaml
        dev/bots/analyze-sample-code.dart
        dev/bots/docs.sh
        dev/bots/prepare_package.dart
        dev/bots/pubspec.yaml
        dev/bots/test.dart
        dev/bots/test/prepare_package_test.dart
        dev/devicelab/README.md
        dev/devicelab/bin/tasks/gradle_plugin_test.dart
        dev/devicelab/bin/tasks/module_test.dart
        dev/devicelab/lib/framework/adb.dart
        dev/devicelab/lib/framework/framework.dart
        dev/devicelab/lib/framework/runner.dart
        dev/devicelab/lib/framework/utils.dart
        dev/devicelab/lib/tasks/microbenchmarks.dart
        dev/devicelab/lib/tasks/perf_tests.dart
        dev/devicelab/manifest.yaml
        dev/devicelab/pubspec.yaml
        dev/devicelab/test/adb_test.dart
        dev/devicelab/test/run_test.dart
        dev/integration_tests/channels/pubspec.yaml
        dev/integration_tests/channels/test_driver/main_test.dart
        dev/integration_tests/external_ui/pubspec.yaml
        dev/integration_tests/external_ui/test_driver/main_test.dart
        dev/integration_tests/flavors/pubspec.yaml
        dev/integration_tests/platform_interaction/pubspec.yaml
        dev/integration_tests/ui/pubspec.yaml
        dev/integration_tests/ui/test_driver/screenshot_test.dart
        dev/manual_tests/pubspec.yaml
        dev/tools/dartdoc.dart
        dev/tools/gen_date_localizations.dart
        dev/tools/pubspec.yaml
        dev/tools/update_icons.dart
        dev/tools/vitool/pubspec.yaml
        examples/catalog/pubspec.yaml
        examples/flutter_gallery/lib/demo/cupertino/cupertino_dialog_demo.dart
        examples/flutter_gallery/lib/demo/cupertino/cupertino_navigation_demo.dart
        examples/flutter_gallery/lib/demo/cupertino/cupertino_picker_demo.dart
        examples/flutter_gallery/lib/demo/cupertino/cupertino_refresh_demo.dart
        examples/flutter_gallery/lib/demo/material/bottom_app_bar_demo.dart
        examples/flutter_gallery/lib/demo/material/leave_behind_demo.dart
        examples/flutter_gallery/lib/demo/material/list_demo.dart
        examples/flutter_gallery/lib/demo/material/material.dart
        examples/flutter_gallery/lib/demo/material/menu_demo.dart
        examples/flutter_gallery/lib/demo/material/progress_indicator_demo.dart
        examples/flutter_gallery/lib/demo/material/scrollable_tabs_demo.dart
        examples/flutter_gallery/lib/demo/material/search_demo.dart
        examples/flutter_gallery/lib/demo/pesto_demo.dart
        examples/flutter_gallery/lib/gallery/backdrop.dart
        examples/flutter_gallery/lib/gallery/demo.dart
        examples/flutter_gallery/lib/gallery/demos.dart
        examples/flutter_gallery/lib/gallery/options.dart
        examples/flutter_gallery/pubspec.yaml
        examples/flutter_gallery/test/live_smoketest.dart
        examples/flutter_gallery/test/pesto_test.dart
        examples/flutter_gallery/test_driver/transitions_perf_test.dart
        examples/flutter_view/lib/main.dart
        examples/flutter_view/pubspec.yaml
        examples/hello_world/pubspec.yaml
        examples/layers/pubspec.yaml
        examples/platform_channel/pubspec.yaml
        examples/platform_channel_swift/pubspec.yaml
        examples/platform_channel_swift/test_driver/button_tap_test.dart
        examples/platform_view/pubspec.yaml
        examples/stocks/pubspec.yaml
        packages/flutter/lib/analysis_options_user.yaml
        packages/flutter/lib/src/animation/animation_controller.dart
        packages/flutter/lib/src/animation/animations.dart
        packages/flutter/lib/src/cupertino/app.dart
        packages/flutter/lib/src/cupertino/bottom_tab_bar.dart
        packages/flutter/lib/src/cupertino/dialog.dart
        packages/flutter/lib/src/cupertino/icons.dart
        packages/flutter/lib/src/cupertino/nav_bar.dart
        packages/flutter/lib/src/cupertino/picker.dart
        packages/flutter/lib/src/cupertino/route.dart
        packages/flutter/lib/src/cupertino/scrollbar.dart
        packages/flutter/lib/src/cupertino/segmented_control.dart
        packages/flutter/lib/src/cupertino/slider.dart
        packages/flutter/lib/src/cupertino/text_selection.dart
        packages/flutter/lib/src/material/bottom_navigation_bar.dart
        packages/flutter/lib/src/material/bottom_sheet.dart
        packages/flutter/lib/src/m
Aborting
Updating e4b989bf3..a74f591d0

**Comment by zoechi** [comment]
In a terminal window in the Flutter install directory execute
```
git clean -xfd
git pull
flutter doctor
```

**Comment by NTMS2017** [comment]
didn't work. I delete the flutter folder in my Mac and clean install. I also update my IntelliJ and android studio plugin. I am getting error as shown below....

any help please

Niyazis-MBP:capital niyazitoros$ flutter channel
Flutter channels:
  beta
* dev
  master
Niyazis-MBP:capital niyazitoros$ flutter --version
Flutter 0.8.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision a74f591d0c (3 days ago) • 2018-09-04 17:12:24 +0100
Engine • revision de4c7a53f2
Tools • Dart 2.1.0-dev.3.0.flutter-760a9690c2
Niyazis-MBP:capital niyazitoros$ 


Running "flutter packages get" in capital...
The current Dart SDK version is 2.1.0-dev.3.0.flutter-760a9690c2.

Because decimal 0.2.0 requires SDK version >=2.0.0-dev.15.0 <2.0.0 and no versions of decimal match >0.2.0 <0.3.0, decimal ^0.2.0 is forbidden.
So, because capital depends on decimal ^0.2.0, version solving failed.
pub get failed (1)

**this is my pubspec.yaml** 

name: capital
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.2"
  connectivity: "^0.3.1"
  decimal: "^0.3.2". // I update to 0.3.2
  intl: "^0.15.6"
  url_launcher: "^3.0.2"
  map_view: "^0.0.14"
  tripledes: "^2.0.1"
  shared_preferences: "^0.4.2"
  image: "^2.0.4"
  path_provider: "^0.4.1"
  scalable_image: "^1.1.1"
  mailer2: "^1.2.3"
  image_picker: "^0.4.6"
  flutter_slidable: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by NTMS2017** [comment]
Now I run the upgrade and get these error:


/Users/niyazitoros/flutter/bin/flutter --no-color packages upgrade
Running "flutter packages upgrade" in capital...
The current Dart SDK version is 2.1.0-dev.3.0.flutter-760a9690c2.

Because uri >=0.11.3 depends on quiver >=0.17.0 <0.30.0 and uri >=0.7.1 <0.11.3 requires SDK version >=0.8.10 <2.0.0 or >=2.0.0-dev.18 <2.0.0, uri >=0.7.1 requires quiver >=0.17.0 <0.30.0.
And because every version of flutter_test from sdk depends on quiver 2.0.0+1 and map_view >=0.0.13 depends on uri ^0.11.1, flutter_test from sdk is incompatible with map_view >=0.0.13.
So, because capital depends on both map_view ^0.0.14 and flutter_test any from sdk, version solving failed.
pub upgrade failed (1)
Process finished with exit code 1

**Comment by NTMS2017** [comment]
Flutter Doctor

/Users/niyazitoros/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.8.0, on Mac OS X 10.13.6 17G65, locale tr-CY)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] Connected devices (1 available)

• No issues found!
Process finished with exit code 0

**Comment by NTMS2017** [comment]
switch to beta channel and got similar error

Niyazis-MBP:capital niyazitoros$ flutter channel
Flutter channels:
  beta
* dev
  master
Niyazis-MBP:capital niyazitoros$ flutter channel beta
Switching to flutter channel 'beta'...
git: From https://github.com/flutter/flutter
git:    3c5819535..976cffa24  master     -> origin/master
git: Switched to branch 'beta'
git: Your branch is up to date with 'origin/beta'.
Niyazis-MBP:capital niyazitoros$ flutter --version
Downloading Dart SDK from Flutter engine af42b6dc95bd9f719e43c4e9f29a00640f0f0bba...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.9M  100 95.9M    0     0  1567k      0  0:01:02  0:01:02 --:--:-- 2005k
Building flutter tool...
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (10 days ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
Niyazis-MBP:capital niyazitoros$ 



/Users/niyazitoros/flutter/bin/flutter --no-color packages get
Downloading package sky_engine...
Downloading common tools...
Downloading darwin-x64 tools...
Downloading android-arm-profile/darwin-x64 tools...
Downloading android-arm-release/darwin-x64 tools...
Downloading android-arm64-profile/darwin-x64 tools...
Downloading android-arm64-release/darwin-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
Downloading android-arm64 tools...
Downloading android-arm64-profile tools...
Downloading android-arm64-release tools...
Downloading android-arm-dynamic-profile tools...
Downloading android-arm-dynamic-release tools...
Downloading android-arm64-dynamic-profile tools...
Downloading android-arm64-dynamic-release tools...
Downloading ios tools...
Downloading ios-profile tools...
Downloading ios-release tools...
Running "flutter packages get" in capital...
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because uri >=0.7.1 <0.11.3 requires SDK version >=0.8.10 <2.0.0 or >=2.0.0-dev.18 <2.0.0 and no versions of uri match >0.11.3 <0.12.0, uri >=0.7.1 <0.11.3-∞ or >0.11.3 <0.12.0 is forbidden.
And because uri 0.11.3 depends on quiver >=0.17.0 <0.30.0 and every version of flutter_test from sdk depends on quiver 2.0.0+1, flutter_test from sdk is incompatible with uri >=0.7.1 <0.12.0.
And because map_view 0.0.14 depends on uri ^0.11.1 and no versions of map_view match >0.0.14 <0.1.0, flutter_test from sdk is incompatible with map_view ^0.0.14.
So, because capital depends on both map_view ^0.0.14 and flutter_test any from sdk, version solving failed.
pub get failed (1)
Process finished with exit code 1

**Comment by zoechi** [comment]
> Because uri >=0.11.3 depends on quiver >=0.17.0 <0.30.0 and uri 

Looks like

https://github.com/google/uri.dart/issues/34

You should be able to work around adding

```yml
dependency_overrides:
  quiver: '>=2.0.0 <3.0.0'
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the channels http://flutter.io/support .

**Comment by zoechi** [comment]
I'm going to close this issue because I believe there is nothing to do for the Flutter team.
Feel free to add comments and I'll try to respond if I think I can help.

**Comment by NTMS2017** [comment]
Thank you very much. I add the "dependency_overrides" and its working again...

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

dependency_overrides:
  quiver: '>=2.0.0 <3.0.0'
