### ISSUE TITLE
Make it easy in flutter.yaml to bundle specifically Roboto and Noto

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2154]
MD uses both of these.
https://www.google.com/design/spec/style/typography.html#typography-typeface

We'll want to make it easy to bundle these "by default" with one line changes, something like:
```
flutter.yaml

- fonts:
  - roboto
  - nato
```
maybe? @jason-simmons 

At which point probably the `flutter create` template wants to include them? (since the framework always wants these fonts)?

**Comment by abarth** [comment]
Rather than using the `fonts` key for this feature, we should probably use something like `uses-material-design: true` that's a signal to include these fonts (and whatever other resources the material.dart library needs).  This is similar to how `material-design-icons` is a more opinionated version of `assets`.

**Comment by abarth** [comment]
As an example, if your app `uses-material-design` we should include the menu and back-arrow icons because those are used by the built-in `Scaffold` widget.

**Comment by eseidelGoogle** [comment]
I like the `uses-material-design: true` proposal. sgtm.

**Comment by abarth** [comment]
I'm going to introduce `uses-material-design: true` with #994

**Comment by abarth** [comment]
Here's a source for Roboto with a clear license:
https://github.com/google/fonts/tree/master/apache/roboto

Noto looks a bit more involved:
https://www.google.com/fonts/specimen/Noto+Sans

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/2315 creates a bunch of mechanism that will be useful for resolving this issue.

**Comment by eseidelGoogle** [comment]
@collinjackson will want to use this in the firechat example once it works.

**Comment by collinjackson** [comment]
this should probably be included by default when you run "flutter create" since that generates a Material app for you

**Comment by abarth** [comment]
Yeah, we should be able to extend the pattern that we're using for the icon font to include roboto.  The one wrinkle is that we don't need to include roboto on android.

**Comment by abarth** [comment]
@jason-simmons did this.
