### ISSUE TITLE
Orientation(Rotation) Issue of Camera Plugin

### ISSUE THREAD

**Issue by chandeepadissanayake** [flutter/flutter#21545]
Even with the provided example, I'm experiencing an issue with camera plugin's orientation when device is rotated. I confirmed this error across different android versions. When the orientation is portrait, everything is fine, working so well. But when we turn around the device, the camera view is 90 degrees off the correct view in clockwise direction, that it should provide. I will attach few screenshots which would help to describe the issue more precisely.

Portrait View
![whatsapp image 2018-09-07 at 3 35 39 pm](https://user-images.githubusercontent.com/13079067/45213254-a5c7eb00-b2b4-11e8-91de-8eb69473e512.jpeg)

Landscape View
![screenshot_20180907-153515](https://user-images.githubusercontent.com/13079067/45213276-b6786100-b2b4-11e8-9bf3-b3a91bc97105.png)

**Comment by zoechi** [comment]
#18391 #16587 look similar.

**Comment by zoechi** [comment]
Merging with #16587
Please upvote and subscribe there. 
If you can provide additional information please also comment on #16587
