### ISSUE TITLE
Add Example using flutter's custom font support

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2155]
Now that #116 is fixed, we need to add an example of using it in examples.  In part to make it easy for others to copy, but also to make sure the codepath is tested on the bots.

The Gallery can be that example.  See #1806.  The Game (https://github.com/flutter/game/issues/47) also needs custom fonts and could be an example.

@jason-simmons

**Comment by sethladd** [comment]
I'm looking to change the fonts of a Flutter app, but can't find an example or docs. So, +1 for this request :)

**Comment by jason-simmons** [comment]
The game now includes an example of font embedding

**Comment by sethladd** [comment]
To see how the game uses a custom font, check out https://github.com/flutter/game/blob/master/flutter.yaml and https://github.com/flutter/game/blob/75cca761d99e3270f7b531127bfdb0a362e41fae/lib/main.dart and https://github.com/flutter/game/blob/57c5ac443a69d941fabd08c805666944dea6a286/lib/game_objects.dart  (search for Orbitron)
