### ISSUE TITLE
Move RenderCoordinateSystem into flutter/rendering package

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2156]
@Hixie says this would be generally useful and we should move it out of the Game:
https://github.com/flutter/game/blob/master/lib/render_coordinate_system.dart

@vlidholt 

Ian mentioned this to me yesterday, so writing it down for posterity.

**Comment by Hixie** [comment]
We haven't had customers request this, and that codebase is no longer one we maintain, so closing.
