### ISSUE TITLE
Insufficient flutter doctor instructions

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2157]
`flutter doctor` wants the Android SDK, but doesn't say where to put it or how to point to it. The Android Setup section on the web site at  https://flutter.io/setup/#android-setup says to install Android Studio.  Based on a conversation with abarth, it appears that installing just the SDK is not sufficient - you also need the JDK.

(Maybe it's also worth saying that ANDROID_HOME is not set in case the user decides to install everything manually because ANDROID_HOME won't be set in existing terminal windows.)

Here is the text displayed by `flutter doctor`:
```
[ ] Android toolchain - develop for Android devices (missing)
  [ ] Android SDK - enable development for Android devices (missing)
      Download at https://developer.android.com/sdk/
```

### Steps to Reproduce
Run `flutter doctor` on a system where the Android SDK is not properly set up.

### Flutter Version
```
Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 4860e63f444cf3786a6b136430f3058a7b851041 (8 hours ago)
engine revision : a53faaf7983025f83a2059021a409c6e98beb58d
```

**Comment by abarth** [comment]
The intent is that you should be able to install Android Studio in the default way and everything should work.  Maybe we should link to https://flutter.io/setup/#android-setup which has more detailed information?

**Comment by jimbeveridge** [comment]
I've updated the title and the text of my initial description after a discussion with abarth.

**Comment by devoncarew** [comment]
That PR will give the user a bit more info about how to install the android sdk. We should also add a check to validate that there's an available JDK (https://github.com/flutter/flutter/issues/1983).
