### ISSUE TITLE
How to implement a side-slide close page on the Android platform?

### ISSUE THREAD

**Issue by yy1300326388** [flutter/flutter#21589]
Flutter setting TargetPlatform.iOS

```
new MaterialApp(
  title: 'Mian',
  theme: new ThemeData(
    primarySwatch: Colors.orange,
    platform: TargetPlatform.iOS,
  )
)
```
Can skip the close page.

![screenrecorder-2018-09-08-10-18-34-6](https://user-images.githubusercontent.com/8764899/45249928-66080e80-b35b-11e8-97e9-3c4cd05900dd.gif)

Flutter setting TargetPlatform.android

```
new MaterialApp(
  title: 'Mian',
  theme: new ThemeData(
    primarySwatch: Colors.orange,
    platform: TargetPlatform.android,
  )
)
```
Can‘t skip the close page.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the channels listed in http://flutter.io/support .

**Comment by yy1300326388** [comment]
I found the answer here.

[How to implement a side-slide close page on the TargetPlatform.android?](https://stackoverflow.com/questions/52231476/how-to-implement-a-side-slide-close-page-on-the-targetplatform-android)
