### ISSUE TITLE
The startup diagram cannot be changed (integrated Flutter in iOS native project)

### ISSUE THREAD

**Issue by SinglTown** [flutter/flutter#21591]
I have integrated Flutter in my iOS project, but when I jump from the native page to the Flutter page, the startup diagram of the iOS native project will still be displayed, and I cannot change the startup diagram of Flutter. This problem has been bothering me for many days, looking forward to the reply.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
Can you please provide more information how to reproduce?

**Comment by SinglTown** [comment]
[✓] Flutter (Channel master, v0.7.6-pre.45, on Mac OS X 10.13.2 17C205, locale zh-Hans-CN)
    • Flutter version 0.7.6-pre.45 at /Users/zhaochuanbao/flutter
    • Framework revision 58d98ce31e (4 days ago), 2018-09-04 19:36:47 -0700
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 2.0.0
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.27.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 7 • 40995363-94D2-4769-8829-E7E2D13C3C82 • ios • iOS 11.2 (simulator)

**Comment by SinglTown** [comment]
I'm accessing it from this document.
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#experiment-turn-the-flutter-project-into-a-module

**Comment by SinglTown** [comment]
I've tried it many times,I guess it's your problem. I hope you can try this process and find the problem

**Comment by zoechi** [comment]
Are you still seeing this with recent Flutter versions?

**Comment by SinglTown** [comment]
There is no such problem with the latest version. Thank you for your reply!
