### ISSUE TITLE
Drawer How to set custom animation

### ISSUE THREAD

**Issue by Im-Kevin** [flutter/flutter#21590]
Drawer How to set custom animation

**Comment by dnfield** [comment]
I think I might have an idea about what you're asking, but can you describe a bit more about what you're trying to do?  What's the behavior you want to change, and what have you tried to do to change it?

**Comment by Im-Kevin** [comment]
I want Body and APPBar to move together.

**Comment by talatkuyuk** [comment]
It would be nice feature that The drawer can have different opening animations/physics, like easein, easeout etc. predefined animations.
