### ISSUE TITLE
How to downgrade the dart version?

### ISSUE THREAD

**Issue by xioxu** [flutter/flutter#21599]
I upgrade the dart version to 2.1 in my Windows Env,  but it brokes my project, since one module 'audio-play' throws : 
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.
Because ***** depends on audioplayer any which requires SDK version >=1.8.0 <2.0.0, version solving failed.
I try to reinstall the flutter to a old version, and I can sure the dart-sdk is 2.0, but the flutter --version still outpus the dart version is 2.1.
So, I realy want to know how to make my project works, thanks in advance.

**Comment by zoechi** [comment]
You can't downgrade Dart independent of Flutter.
You can only downgrade Flutter to a version that contains the Dart version you desire.

You can also use `dependency_overrides` to overrule dependency constraints.
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

```
dependency_overrides:
  audioplayer: ^0.5.0
```

Ideally you'd report an issue with the package that claims not to be compatible with Dart 2.0 final
or even better create a pull request with a fix.
