### ISSUE TITLE
AnimatedValue should not be mutable

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#216]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Oct 21, 2015 at 16:51 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1709_

----

Rather than AnimatedValue being mutable, it should just represent a begin/end range and have an API that, given a value 0.0..1.0, returns a lerp over that range.

Alternatively, we could make AnimatedValue take an object that represents 0..1, a direction, and a change notification API, and exposes a value in the range begin..end and a change notification API. That way you would just plug AnimatedValues straight into the things they were animated by.

**Comment by abarth** [comment]
Fixed.
