### ISSUE TITLE
Weird behaviour of Text Field when adding flutter to existing Android app as a module .

### ISSUE THREAD

**Issue by shakil807g** [flutter/flutter#21603]
I had follow this guide to add flutter to existing android app [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url) but i when i tap on textfield and keyboard pop ups but , some how screen get flicker . 
```
[✓] Flutter (Channel master, v0.7.1-pre.26, on Mac OS X 10.13.5 17F77, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[✓] VS Code (version 1.26.1)
[!] Connected devices
    ! No devices available
```

**Comment by zoechi** [comment]
You probably need to assign a `TextEditingController` to the text field that you keep around so that it is not recreated when the widget is rebuilt.

**Comment by shakil807g** [comment]
Here is gif of this behaviour  there is black view showing when keyboard open or close
![text](https://user-images.githubusercontent.com/13196689/45737951-9b88e380-bc08-11e8-941e-e37108375832.gif)

**Comment by zoechi** [comment]
Are you still seeing this with recent Flutter versions?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
