### ISSUE TITLE
Non-Project Files Protection Error

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#21604]
When debugging, instead of getting the breakpoints and other debugging features on my current file, Intellij opens another file with the same name, but it's not editable.
<img width="989" alt="screen shot 2018-09-08 at 2 23 52 pm" src="https://user-images.githubusercontent.com/23037821/45258886-61505400-b375-11e8-9c6c-bbdce2337840.png">
 I finally figured out what's happening. I have a directory softlinked inside my Mac so I can sync it with Google Drive folder but access it from my home directory. So I found the path of each file, and this is what it shows.

1. The file I actively work on and can set and remove breakpoints from:
_/Users/thinkdigital/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/lib/blocs/contacts_bloc.dart_
<img width="1020" alt="screen shot 2018-09-08 at 2 36 56 pm" src="https://user-images.githubusercontent.com/23037821/45258873-29e1a780-b375-11e8-9df5-4b3b73cbe12b.png">
Notice the breakpoint on line 19.

2. The file that comes up when the debugger breaks on a breakpoint.
_/Users/thinkdigital/Google Drive/Development/IdeaProjects/SMS and Contacts Database Importer/sms_and_contacts_db_importer/lib/blocs/contacts_bloc.dart_
<img width="1029" alt="screen shot 2018-09-08 at 2 29 16 pm" src="https://user-images.githubusercontent.com/23037821/45258881-44b41c00-b375-11e8-9935-8131bb2a83a9.png">
Notice there's also no syntax highlighting on the second one.
When I open this project from the directory directly and not through the softlink, everything works as expected, and even breakpoints that were previously being ignored are now showing up. I'm not sure if this is a result of reopening the project or the fact that it's working better. This also touches on issue #18590

**Comment by zoechi** [comment]
Do you have any relative imports in `lib/main.dart`?
Do you import `lib/main.dart` from any other file?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ThinkDigitalRepair** [comment]
I do have one unused local import. And upon checking, I still get the locked files thing. But now it's just _/main.dart_ as the full path.

> flutter doctor -v
> [✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.14 18A384a, locale en-US)
>     • Flutter version 0.7.3 at /Users/thinkdigital/development/flutter
>     • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
>     • Engine revision af42b6dc95
>     • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
>     • Android SDK at /Users/thinkdigital/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.1
>     • ANDROID_HOME = /Users/thinkdigital/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.4.1, Build version 9F2000
>     • ios-deploy 1.9.2
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 27.1.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
>     • IntelliJ at /Users/thinkdigital/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
>     • Flutter plugin version 26.0.3
>     • Dart plugin version 182.3569.4
> 
> [✓] VS Code (version 1.27.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.18.0
> 
> [✓] Connected devices (2 available)
>     • Android SDK built for x86 • emulator-5554                        • android-x86 • Android P (API 27) (emulator)
>     • iPhone 6                  • 8449EA9B-2433-48C0-A295-4F9FB9249A92 • ios         • iOS 11.4 (simulator)
> 
> • No issues found!
>

**Comment by ThinkDigitalRepair** [comment]
It doesn't show that the file is not in the project directory, but it does lock it and say the file isn't writable and the same no syntax highlighting occurs.

**Comment by zoechi** [comment]
Can you please post the imports you have in `lib/main.dart`?

**Comment by ThinkDigitalRepair** [comment]
Sure, as of now, I have:
```
import 'package:flutter/material.dart';

import 'ui/main.dart';

```

I'll remove the relative import and try again.

**Comment by zoechi** [comment]
`import 'ui/main_view.dart';` do not use such imports in `lib/main.dart`
only use imports with `package:...` or `dart:...` in this file.
Relative imports are fine in other files but on in such entry-point files.
Also don't import `lib/main.dart` from other files.

Closing as dup of https://github.com/dart-lang/sdk/issues/33076

**Comment by ThinkDigitalRepair** [comment]
Without the relative import, it works just fine. Shouldn't a softlink be sufficient for nearly every use of the path? How does the debugger get wind of the full non-softlinked path?

**Comment by ThinkDigitalRepair** [comment]
And can a warning be thrown in cases like this?

**Comment by zoechi** [comment]
Complicated question and I only have vague knowledge. 
Dart started with softlinks but if Windows should be supported as well this is a **very** bad idea and so Dart got rid of them. 

Dart supported entry-point files only in directories outside `lib/` but Flutter put it into `lib/` anyway, this is why it is not a beaten path. 

> And can a warning be thrown in cases like this?

It's planned to be fixed anyway. This is what the linked issue is about.

**Comment by ThinkDigitalRepair** [comment]
Right, that's what I was reading. OK, thanks!
