### ISSUE TITLE
dismissible widget, can only dismiss one at a time

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#21602]
I am only able to dismiss one dismissible at a time, if I try to dismiss in a rapid-fire (swiping fast) fashion it will keep the previous state, because we have to set the state (in onDismissed) the state update will prevent the last fired dismissible to dismiss. It seems like dismissing fast is too fast for the state updates to take place.

In apps like gmail, it is possible to rapid-fire dismiss items I wonder how it is done there.

I tried to update state at a later time but I get the key exception (a dismissed widget is still part of the tree)

**Comment by zoechi** [comment]
I tried with the complete example from https://flutter.io/cookbook/gestures/dismissible/ 
with ` final items = List<String>.generate(30`
and wasn't able to reproduce, or don't understand correctly what you mean.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.7.5, on Mac OS X 10.13.6 17G65, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
[✓] Connected devices (2 available)

• No issues found!

**Comment by abacaj** [comment]
hi @zoechi sorry, I will post a video it can be reproduced in the flutter gallery app as well.

**Comment by zoechi** [comment]
Can you try with the example I linked to above?
Might just be a bug in Flutter Gallery.

**Comment by abacaj** [comment]
It is the same issue, if you swipe quickly - I don't mean super natural fast but just quickly swipe the next item before the first item disappear it only removes the first.

Here is the video with the example you gave:

https://streamable.com/vcvq3

**Comment by zoechi** [comment]
Weird. I swiped all 30 really quick.
The items were gone and the snackbars kept popping up for a few more minutes.

**Comment by abacaj** [comment]
@zoechi really? how do you explain the 2 videos lol. The first one was on android, the second one is on iOS it happens on both platforms.

**Comment by abacaj** [comment]
Interesting find, if I dismiss in reverse (starting at the last item and dismiss the next one above it) it works!

**Comment by abacaj** [comment]
@zoechi here is a video of it working in reverse, and failing in normal order.

https://streamable.com/xcb22

**Comment by zoechi** [comment]
> how do you explain

I'll try to find some time to investigate more to figure it out.
I don't claim that your case is not valid, only that I haven't found a way to reproduce it.

**Comment by abacaj** [comment]
@zoechi tried debugging it earlier, it seems the second animation is being disposed of during the first animation.

The first animation ends, causing a `setState` update and disposing of the second animation before it finishes.

It seems this order is different when swiping from bottom to top. The second animation is not disposed of.

**Comment by abacaj** [comment]
Interesting... If i don't dispose of the animation controllers - even the second one gets removed properly - but of course that is not right because that is a leak and I get a minor exception.

**Comment by abacaj** [comment]
@zoechi any ideas? Is this a problem with flutter or my code?

I can reproduce it in the flutter gallery and with a basic minimal example from the flutter docs.

**Comment by nklayman** [comment]
I noticed this as well. It pops back up if I go top to bottom, but works fine if I go bottom to top.

**Comment by nklayman** [comment]
Also, if you swipe 5 or so at a time, only one is removed (but works fine bottom to top).

**Comment by egorges** [comment]
> Interesting... If i don't dispose of the animation controllers - even the second one gets removed properly - but of course that is not right because that is a leak and I get a minor exception.
> 
> Seems to be why is the second item being disposed of during the first animation.

This means when you go bottom up, you dismiss item 5-4-3-2-1 and at last 0. But when you rapid-fire top-down, both 0 and 1 start a dismiss, so when the first (0) is actually dismissed, the item indexes are rearranged and you will have only item 0, while the command to dismiss item 1 didn't finish yet. 

So to enable rapid-fire you will need a different way to lookup the item to be dismissed.

**Comment by zoechi** [comment]
Possible duplicate #20563

**Comment by karmazinkd** [comment]
It's almost 2020 and it's haven't been fixed yet. 
Is it so exotic behavior when a user swipes two items fast instead of waiting for the first one to be gone? 
This bug is a blocker to most of the apps with dismissable item lists

**Comment by TahaTesser** [comment]
Hi @abacaj 
Not able to reproduce this issue on latest `dev` channel

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(10000, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: ListView.builder(
          itemCount: items.length,
          itemBuilder: (context, index) {
            return Dismissible(
              key: Key(items[index]),
              background: Container(color: Colors.red),
              onDismissed: (direction) => print(direction.index.toString()),
              child: ListTile(
                title: Text('${items[index]}'),
              ),
            );
          },
        ),
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.18.0-10.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-10.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 9b7b9d795e (18 hours ago), 2020-05-05 12:09:51 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details> 

If you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
