### ISSUE TITLE
Platform channel method invocation fails when waiting await to finish

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#21610]
This supersedes #20378. I open this new issue to describe the problem more precisely and correctly base on my latest findings.

The code that reproduces the issue (at least on my machine) can be found [here](https://github.com/tamcy/fcm-get-token-issue). The repo uses `firebase_messaging plugin` to reproduce the issue, but I suspect the problem relates to Flutter and is a more generic one. 

(I didn't include `google-services.json` in the repo, but am happy to provide one if needed)

Flutter's firebase_messaging plugin sets up a method channel to communicate with the platform code. On Android, calling `FirebaseMessaging.configure()` in Dart will trigger `FirebaseMessagingPlugin.onMethodCall()` to be called in Java, followed by some logic to retrieve the FCM token. When the Java code receives the FCM token through a callback, it calls Dart's `onToken()` method through method channel, which in turns trigger's the method call handler of the Dart code i.e. `FirebaseMessaging._handleMethod()` to run.

The problem is that if I have a long enough `await` statement after `FirebaseMessaging.configure()`, the Java code can still get the FCM token and calls `channel.invokeMethod("onToken", token);`, but this will no longer trigger the execution of `FirebaseMessaging._handleMethod()` in Dart. The message is lost, casuing the FCM token never returned to Dart. So if we wait for the FCM token to return in Dart, it will block forever.

Strangely this seems to be broken only when the code appears before `runApp`. If I move the configure and await code to the init method of a widget, the FCM token will return properly. Not sure if this is of any indication though.

I had a hard time isolating the exact cause of the problem and constructing a codebase that reproduce this issue 100%, which I don't want to repeat here. But this means that I'm not sure if the issue is reproducible on other people's machine. Please see #20378 to know more of my journey and some screencasts. 

I am yet to have the time to test it on iOS.

```
[√] Flutter (Channel dev, v0.8.1, on Microsoft Windows [Version 10.0.17134.228], locale zh-HK)
    • Flutter version 0.8.1 at C:\flutter
    • Framework revision 0235ec59d1 (2 days ago), 2018-09-06 20:23:13 -0700
    • Engine revision 9b297b3b51
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\CY\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio 3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio 3
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Android Studio (version 2.1)
    • Android Studio at C:\Android\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] VS Code, 64-bit edition (version 1.23.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Nexus 5X • 00e1c63e154fae10 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
I think https://github.com/flutter/plugins#869 was supposed to fix that.
Feel free to add a comment to have it reopened if you disagree.
