### ISSUE TITLE
Updater process tries to open observatory on the same port as the main app

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2161]
When you launch a Flutter app, we actually launch two processes: the app, and the updater. The app starts first, opens the observatory port. Then the updater launches, and tries to do the same, but fails because it's already open.

We should probably open the updater on the port+1 or something.

cc @mpcomplete

**Comment by yjbanov** [comment]
Is there a way to launch the Dart VM asking observatory to pick a random available port and report it back, say, via stdout? If not, perhaps we should file an issue with the Dart VM?

**Comment by devoncarew** [comment]
This is something we control in the embedder (re: printing the obs. port). We could have the embedder bind to an available port and print that to stdout. I think our run process would need to be tightened up a bit to do that however. We'd want to make sure we started capturing log output before we ran, that we were always getting log output (from adb devices, ios devices, ios simulator).

**Comment by eseidelGoogle** [comment]
I don't think we want to be including/launching the updater unless applications opt in to it.  Presumably this is in an app which has the updater turned on?  @mpcomplete is currently in the process of fixing the updater I believe it broke during the engine/flutter split.  See https://github.com/flutter/flutter/issues/1841

**Comment by mpcomplete** [comment]
I removed the UpdateService for now.
