### ISSUE TITLE
99th percentile and worst frame raster time regressed on Pre-Dart SDK roll

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#21617]
See commit https://github.com/flutter/flutter/commit/6a8a73c4fc29616ce4d241e42054f376a086741e and
-  complex_layout_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis
-  complex_layout_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis
-  futter_gallery_ios32__transition_perf 99th_percentile_frame_rasterizer_time_millis

**Comment by jason-simmons** [comment]
This was introduced in https://github.com/flutter/engine/commit/93dac2a88d1695fc9508acabb2e3d4cf5f0429a5 (specifically the change to anti-aliasing)

@liyuqian @GaryQian

**Comment by GaryQian** [comment]
Previously, we were **not** anti-aliasing on all ClipRect, even when the clipBehavior is says it should. After passing the correct anti-aliasing, there is likely a performance hit due to a lot more anti-aliasing being performed where it should have before.

**Comment by liyuqian** [comment]
Ah yes, you're correct. `doAntiAlias` is default to `false` for `SkCanvas::ClipRect`

**Comment by liyuqian** [comment]
To fix the issue, we'll have to change our default `clipBehavior` to be `hardEdge` instead of `antiAlias` in [ClipRect](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/basic.dart#L499). Gary is on changing that.

This will be a breaking change but most people probably can't tell a visual difference (other than the performance). @Hixie

**Comment by Hixie** [comment]
how will we ensure we don't get ugly clips when the ClipRect is in a transform?

**Comment by liyuqian** [comment]
@Hixie We still provide the `clipBehavior` option to the user. I think most cases doesn't have a perspective/rotated transform so we should default it to `hardEdge`. If the developer finds the clip ugly, they can always change it to `antiAlias`.

**Comment by Hixie** [comment]
Fair enough. Please make sure to really clearly document this in the ClipRect widget docs, ideally including sample code and screenshots showing the difference so that people can understand it.

**Comment by Hixie** [comment]
(cc @gspencergoog who may have advice on doing that)

**Comment by liyuqian** [comment]
FYI, our `ClipRectLayer` never had anti-aliased clip (it was https://github.com/flutter/engine/blame/16c56afb09ee1271076e3285be43e83318c328cd/flow/layers/clip_rect_layer.cc#L45 before Gary's change). Nobody seems to have complained. That's probably also why I missed it during the breaking Clip change: everything else was anti-aliased clip while this one was actually non-anti-aliased clip...

**Comment by gspencergoog** [comment]
Yeah, I can help with the diagrams for the docs if you want.

**Comment by liyuqian** [comment]
This bug should have been fixed as https://github.com/flutter/flutter/pull/21703 is merged.

**Comment by Hixie** [comment]
Looks like it's not fixed.
