### ISSUE TITLE
How to make datatable support landscape display?

### ISSUE THREAD

**Issue by stt106** [flutter/flutter#21622]
I just want to use a simple `DataTable` because my data is static and limited (e.g. won't be paged) and I won't need sorting or any fancy user interaction.

But the problem is even with just a few columns in the data table, it's too wide and overflows the screen since I can't control each column width.
To overcome this, I used a `SingleChildScrollView` with `scrollDirection = Axis.horizontal` which does solve the problem.

But I want to it work with landscape display where the screen is much wider hence I don't need to scroll horizontally to see the whole data table. How to do this?

Below is a sample reproduction:

```
import 'package:flutter/material.dart';
void main() => runApp(new Demo());
class Demo extends StatelessWidget {
  static List<DataCell> _dataCells =
      ['A', 'B', 'C', 'D', 'E'].map((c) => DataCell(Text(c))).toList();
  final List<DataRow> _sampleDataRows =
      [1, 2, 3, 4, 5].map((i) => DataRow(cells: _dataCells)).toList();
  final List<DataColumn> _dataColumns =
      [1, 2, 3, 4, 5].map((i) => DataColumn(label: Text('Col$i'))).toList();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(padding: EdgeInsets.all(20.0), children: <Widget>[
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: DataTable(
              rows: _sampleDataRows,
              columns: _dataColumns,
            ),
          ),
        ]),
      ),
    );
  }
}
```
Cross-link https://stackoverflow.com/questions/52303224/how-to-make-flutter-datatable-support-landscape-display

**Comment by zoechi** [comment]
Can you please provide a running minimal reproduction
and/or a screenshot.

Please add the output of `flutter doctor -v`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by stt106** [comment]
@zoechi  thanks for the reply. I have updated my question with some reproduction code.

**Comment by zoechi** [comment]
As commented at the SO question. It's not clear to me what the problem is. Please elaborate and perhaps add a screenshot.

Please also add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/45471587-d8993580-b731-11e8-8151-aca2d8363ca6.png)

![image](https://user-images.githubusercontent.com/405837/45471606-e2bb3400-b731-11e8-8218-165a4fc8b524.png)

```
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.8.2 at /Users/zoechi/flutter/flutter
    • Framework revision 5ab9e70727 (5 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by stt106** [comment]
What? No way... 
My flutter is v0.7 but don't think that could be a problem and my Android SDK is 28 too.
Will update flutter and retry tonight.
Thanks for checking this.

**Comment by stt106** [comment]
Not entirely sure why but I didn't get the landscape button on my emulator before I updated Android SDK and Java API 28.
Now it does display the data table properly in landscape mode now.
So I have closed this.
Thanks again for looking into this.
