### ISSUE TITLE
flutter version is unknown using git version < 2.0

### ISSUE THREAD

**Issue by bangbang93** [flutter/flutter#21626]
## Steps to Reproduce
Fresh install on CentOS 7
1. flutter channel beta
2. flutter upgrade
3. flutter --version

## Logs
```
Flutter 0.0.0-unknown • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (12 days ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
```

```
[✓] Flutter (Channel beta, v0.0.0-unknown, on Linux, locale en_US.UTF8)
    • Flutter version 0.0.0-unknown at /opt/flutter
    • Framework revision 3b309bda07 (12 days ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_181-b13)
    • All Android licenses accepted.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

https://github.com/flutter/flutter/blob/beta/packages/flutter_tools/lib/src/version.dart#L530

Here use the `--first-parent` argument, which not be supported on CentOS 7 bundled git version 1.8.3.1

And is this argument is necessary?
![image](https://user-images.githubusercontent.com/3430784/45277484-a356d280-b4fa-11e8-8428-92de2830329d.png)

**Comment by zoechi** [comment]
Can't you update `git` to 2.xx?

**Comment by bangbang93** [comment]
That I need to add a third-party yum repo.
As far as I can see, if the `--first-parent` arguments didn't affect the result, remove this is much better than import a third-party yum repo.

**Comment by GWYloved** [comment]
update git version to 2.x.x will finish the unkown version 

```
yum remove git
yum install http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm
yum install git
```

**Comment by hpsoar** [comment]
edit

`
flutter/packages/flutter_tools/lib/src/version.dart
`
and remove `--first-parent`

remove
`
flutter/bin/cache/flutter_tools.snapshot
`

then, it works

**Comment by christopherfujino** [comment]
We now officially require git version 2.x https://docs.flutter.dev/get-started/install/linux#system-requirements
