### ISSUE TITLE
flutter run not working on VSCode

### ISSUE THREAD

**Issue by kimeuichan** [flutter/flutter#21637]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.228], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.27.1)
[√] Connected devices (1 available)

• No issues found!
```

When I start terminal `flutter run`, It's alright, but VScode F5(debugging) is not working on real smart phone(LG V30S).
just show white screen on Windows 10. It's alright on macOS and emulator in Windows 10!

**Comment by muddassirm** [comment]
Check if your device is connected using

`> flutter devices`

**Comment by kimeuichan** [comment]
I'm already checked it. I found my phone...

**Comment by DanTup** [comment]
Can you try running the `Dart: Capture Logs` command from the VS Code command palette, select the `Flutter Run` and `Observatory` categories, and then try running. Once you get the white screen, leave it for approx 30 seconds then press `Stop Logging` and attach the log.

**Comment by kimeuichan** [comment]
I did `Dart: Capture Logs` command. but I don't find errors or warnings.. 
Can you see the logs?
[Dart-Code-Log-2018-08-03 15-08.txt](https://github.com/flutter/flutter/files/2373770/Dart-Code-Log-2018-08-03.15-08.txt)

**Comment by DanTup** [comment]
@kimeuichan Can you try installing this version of Dart Code:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.1-beta.1

(Download the VSIX file, then run the `Extension: Install from VSIX` command from the VS Code command palette, then select the vsix file, then click the Reload button)

And then try editing your `launch.json` to run Flutter in Verbose mode (see https://github.com/flutter/flutter/issues/16604#issuecomment-419494943).

Then capture the log again; hopefully it'll have more info in it then.

**Comment by kimeuichan** [comment]
@DanTup 
Log is too long. I copied some lines from tail. 
Maybe, app is waiting for something. Do you want to full log?
```
[ +431 ms] package:com.example.test11
[   +2 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s LGMV300Sdeb664df shell cat /data/local/tmp/sky.com.example.test11.sha1
[  +53 ms] 5a61b4718560b2c9bfa6858ffe212612bf8258c2
[        ] Latest build already installed.
[        ] LGM V300S startApp
[   +1 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb -s LGMV300Sdeb664df shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez start-paused true com.example.test11/com.example.test11.MainActivity
[ +112 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.test11/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```

**Comment by DanTup** [comment]
If you run from powershell with `-v --start-paused` (eg. `flutter run -v --start-paused`) does that stop on the same line as VS Code ("Waiting for observatory port to be available...") or does that also work?

**Comment by DanTup** [comment]
This looks suspiciously like https://github.com/flutter/flutter/issues/18889#issuecomment-420734145. Could you try something for me?

1. Run `adb logcat` in a terminal, then try to launch the app and see if there is any output from `logcat`

2. Repeat but running `adb shell -t "logcat -v time"` before trying to run the app, and see if there is any output

**Comment by DanTup** [comment]
Also - can you confirm the model of your phone? An LG MV300S?

**Comment by kimeuichan** [comment]
`flutter run -v --start-paused` command's result was same.
Two `adb` commands were not working... 
My phone model is `LGM V300S • LGMV300Sdeb664df • android-arm64 • Android 8.0.0 (API 26)`

**Comment by DanTup** [comment]
@kimeuichan Have a look at https://github.com/flutter/flutter/issues/18889#issuecomment-421432066. It seems like there may be an issue with the latest platform tools in the Android SDK. It'd be interesting to know if you have 28.0.1 and if so, whether downgrading to 28.0.0 solves the issue?

**Comment by kimeuichan** [comment]
@danrubel Thanks!.. It's working for me!!!

**Comment by kimeuichan** [comment]
@DanTup Thanks!.. It's working for me!!!

**Comment by DanTup** [comment]
@kimeuichan I've landed a better fix for this - if you're using master, please try re-upgrading your platform tools and flutter to latest and see if it solves your issue too (we believe that the issue may have been specific to some LG devices) and let me know.

**Comment by alexandremjacques** [comment]
I am having that same problem with a LG X230 (K4 model). App runs on command line (`flutter run`) but no luck debugging it on VS Code. 

Running platform-tools 28.0.3 on macOS 10.13.6. 

Also tried switching to `master` and `--start-paused` but still the same behaviour. 

Anything else I should try? Ditch the LG device and get a new one?

TIA

**Comment by DanTup** [comment]
Try doing some debugging with `adb logcat` and `adb shell logcat`. While it's running, if you launch the app with Flutter (eg. from another terminal window) you should see log output. If you are not, then something may be wrong between `adb` and your device. If you do see output, it's likely Flutter-related and we should be able to track it down (in which case, please open a new issue with the details, and feel free to CC me).

**Comment by lucianoo6** [comment]
Solve with Flutter Upgrade Command 
more https://atshop.com.br/flutter-run-nao-funciona/
