### ISSUE TITLE
flutter engine segfaults when setting text.

### ISSUE THREAD

**Issue by james-lawrence** [flutter/flutter#21636]
to be clear not working in the standard flutter environment when running into this.
working with a library that is attempting to get flutter working on desktops. mainly opening this to expose the bug and hope that better error reporting on the cause comes out of it.

in version 0.5.1 of flutter the example stocks app starts up correctly and runs. (with a custom font used)
in version 0.7.3 of flutter the example stocks app segfaults. we believe it is font related.

debugging details can be found [here](https://github.com/Drakirus/go-flutter-desktop-embedder/issues/2)

this [branch](https://github.com/james-lawrence/go-flutter-desktop-embedder/tree/flutter-issue) can be used to reproduce the issue if the stack trace below isn't enough.

```
#6  0x00007fc4e4090e0c in minikin::WordBreaker::setText(unsigned short const*, unsigned long) () from flutter/library/linux/libflutter_engine.so
#7  0x00007fc4e408e643 in minikin::LineBreaker::setText() () from flutter/library/linux/libflutter_engine.so
#8  0x00007fc4e4095e02 in txt::Paragraph::ComputeLineBreaks() () from flutter/library/linux/libflutter_engine.so
#9  0x00007fc4e40978b7 in txt::Paragraph::Layout(double, bool) () from flutter/library/linux/libflutter_engine.so
#10 0x00007fc4e40c9d2c in blink::Paragraph_layout(_Dart_NativeArguments*) () from flutter/library/linux/libflutter_engine.so
#11 0x00007fc4e42e3718 in dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck (args=0x7fc4b3ffaed0, func=0x7fc4e40c9cc0 <blink::Paragraph_layout(_Dart_NativeArguments*)>)
    at ../../third_party/dart/runtime/vm/native_entry.cc:198
```

**Comment by james-lawrence** [comment]
we're passing it the path to the icudtl.dat file. we used the same icudtl.dat file between the versions? i'm not familiar with what the file does. I'll dig in that direction and see if anything comes up.

**Comment by james-lawrence** [comment]
it was due to the icudtl.dat file, we were still using the one from the previous engine. we updated and the issue resolved. 

is there a way to detect this state and generate a decent error message for others in the future?

**Comment by jonahwilliams** [comment]
I'm not sure how we would detect that the ICU data was malformed or not correct. @jason-simmons or @goderbauer might have some ideas here.

**Comment by goderbauer** [comment]
I don't think there is a good way to detect a version miss-match between the ICU data and the ICU library compiled into the engine. I also don't think that it's worth adding any such check to the engine since we always bundle engine and ICU data together to ensure they are of the same version and I'd strongly encourage any embedder to do the same.
