### ISSUE TITLE
Add an assert that you don't setState during layout.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2163]

**Comment by eseidelGoogle** [comment]
SizeObserver is gone.  Is this still valid?

**Comment by Hixie** [comment]
Yes, this was dependent on first removing SizeObserver.

**Comment by jonahwilliams** [comment]
This seems easy to do by checking for `_element.renderObject.debugDoingThisLayout == true`.  However, I'm not really sure what circumstances would lead to someone calling setState during layout (LayoutBuilder?).  @Hixie could you provide some more context? for the sake of my error messages

**Comment by Hixie** [comment]
The original context was that we had a RenderObject that, during layout, invoked a callback with its `size`, and people would, in that callback, call `setState` so that they could update their rendering with that size, but unfortunately doing so meant that their layout was always one frame behind (because they would schedule their widget to get rebuilt in the subsequent frame).

**Comment by pedromassangocode** [comment]
Not sure if this still needs to be implemented but the issue is valid since there is no assertion in the `setState()` method related to calling it during layout.

https://github.com/flutter/flutter/blob/5a2153d340f3c591d84d05d4634d34da32006943/packages/flutter/lib/src/widgets/framework.dart#L1203-L1265

If it still valid I would like to make a PR for this.

**Comment by Abhishek01039** [comment]
Hello @Hixie 
we are getting the warning in the console while calling the `setState` during layout.
This is still an issue?
Thanks

**Comment by Hixie** [comment]
@Abhishek01039 By "during layout" you mean while handling a "performLayout" call in a RenderObject subclass?

**Comment by Abhishek01039** [comment]
```
I/flutter ( 4657): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4657): The following assertion was thrown building StreamBuilder<Map<dynamic, dynamic>>(dirty, state:
I/flutter ( 4657): _StreamBuilderBaseState<Map<dynamic, dynamic>, AsyncSnapshot<Map<dynamic, dynamic>>>#a5165):
I/flutter ( 4657): setState() or markNeedsBuild() called during build.
I/flutter ( 4657): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter ( 4657): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter ( 4657): only if one of its ancestors is currently building. This exception is allowed because the framework
```

This is we are getting while calling the `setState` during layout.

**Comment by Hixie** [comment]
That's during build, not layout. (You can tell because it says "The following assertion was thrown building..." and "the framework is already in the process of building widgets".)

**Comment by creativecreatorormaybenot** [comment]
@Hixie How would it be possible for a user to call `setState` during layout? I am wondering because `State` does not expose any layout-related methods 🤔

**Comment by Hixie** [comment]
This is still valid but realistically we can't add asserts at this low level anymore without breaking tons of apps so I'm going to make a call that we're not fixing it. :-(
