### ISSUE TITLE
The AdMob at the top is not displayed in the correct position.

### ISSUE THREAD

**Issue by ganessaa** [flutter/flutter#21634]
It will be displayed in the correct position when we display AdMob at the bottom. However, when we display AdMob to the top, that position is incorrect. We just set AnchorType.top to show() anchorType. What did we make a mistake? What should we do?

![screen shot 2018-09-10 at 16 46 26](https://user-images.githubusercontent.com/20409050/45287419-3277e080-b523-11e8-840f-23e93c352da8.png)

```dart
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Title',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MainPage(),
    );
  }
}

class MainPage extends StatefulWidget {
  MainPageState createState() => MainPageState();
}

class MainPageState extends State<MainPage> {
  BannerAd _bannerAd;

  @override
  Widget build(BuildContext context) {
    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
    if (_bannerAd == null) {
      _bannerAd = createBannerAd();
    }
    _bannerAd
      ..load()
      ..show(anchorType: AnchorType.top);
    return Container();
  }

  BannerAd createBannerAd() {
    return new BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      targetingInfo: MobileAdTargetingInfo(
        testDevices: <String>[],
        keywords: <String>[],
        birthday: new DateTime.now(),
        gender: MobileAdGender.female,
      ),
      listener: (MobileAdEvent event) {
        print("BannerAd event $event");
      },
    );
  }
}

```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.7.5, on Mac OS X 10.13.6 17G65, locale ja)
    • Flutter version 0.7.5 at /Applications/flutter
    • Framework revision eab5cd9853 (10 days ago), 2018-08-30 14:47:04 -0700
    • Engine revision dc7b5eb89d
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xxxxx/src/android-sdks
    • Android NDK at /Users/xxxxx/src/android-sdks/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xxxxx/src/android-sdks
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 6 Plus • 60e0f8bcceec5dcf9fe990b894577912cfb12b26 • ios • iOS 11.4.1

• No issues found!
```

**Comment by westy92** [comment]
I'm consistently seeing this issue as well on release builds (debug builds don't always show ads). It's only an issue on my 5th gen iPod Touch, with iOS 9, which is the only physical iOS device I have to test with.

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/westy92/Source/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
 
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/westy92/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.
 
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2
 
[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
 
[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1
 
[✓] Connected device (1 available)
    • Seth's iPod touch • <redacted> • ios • iOS 9.3.5
 
• No issues found!
```

**Comment by fguichard09** [comment]
Hi, I have the same problem on iOS (iPhone 6s, iPhoneX or simulators).
It's working great on Android.

`flutter doctor -v
[✓] Flutter (Channel master, v1.3.15-pre.26, on Mac OS X 10.14.3 18D109, locale fr-FR)
    • Flutter version 1.3.15-pre.26 at /Users/fabien/Projets/flutter
    • Framework revision 6e50ccc803 (5 hours ago), 2019-03-26 15:26:13 +0800
    • Engine revision 0d83a2ecd1
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fabien/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (5 available)
    • Pixel 3 XL                • 8AHY0LBEU                                • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5556                            • android-x86   • Android 8.1.0 (API 27) (emulator)
    • iPhone de Fabien          • 8859cf67206270eb784bfe4e78a405d9454e1165 • ios           • iOS 12.1.4
    • iPhone 6s                 • 68ED0E05-3796-43C8-BB0A-DBFA829DDD7A     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone Xʀ                 • 6A39CA66-38AB-4E2F-A04B-4F9C2A407A33     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
`
Thanks for your help

**Comment by kroikie** [comment]
@ganessaa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/665. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/97
https://github.com/FirebaseExtended/flutterfire/pull/45

**Comment by westy92** [comment]
This is still an issue on iOS 9.3.5 (and likely all of iOS 8-10). I just tested firebase_admob 0.9.3 to confirm.

**Comment by bparrishMines** [comment]
Reopening to fix ios 8

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
