### ISSUE TITLE
Potential Security Issue in Firebase or Firebase Auth Plugin

### ISSUE THREAD

**Issue by or1own** [flutter/flutter#21645]
Hi all,

hope I got something wrong, otherwise this seems to be a security issue in Firebase or the Firebase Auth Plugin. When creating user accounts, in the code I execute:

`user = await _auth.createUserWithEmailAndPassword(...);`

The function signs in new users to Firebase immediately. It means that someone can create an account with the email address from another person, and this other person won't be informed about it. After creating the account, someone can sign in with this other person's address over and over again via the normal sign in function:

`user = await _auth.signInWithEmailAndPassword(...);`

IMHO, after creating an account this account should be blocked and a verification mail should be sent first. After verification, the account should be unblocked. It would prevent someone from using other people's mail addresses.

I created a workaround that is still not ideal... new users will only provide their mail addresses in my form. I placed a fake password in the frontend code and force a password reset. Users then reset their passwords and they can use their account from a verified mail address.

I started coding in Flutter one week ago, hope I didn't miss anything.

Thanks for your help.

**Comment by KevinTheGray** [comment]
The `FirebaseUser` class has an `isEmailVerified` field on it, and there is also an option to send this email verification [seen here](https://github.com/flutter/plugins/blob/21bc07c40f9856f67bf645992698c65c59f54e80/packages/firebase_auth/lib/firebase_auth.dart#L84).

There is also [this blog post](https://firebase.googleblog.com/2017/02/email-verification-in-firebase-auth.html) about email verification for firebase, which sheds some light on the intended uses.

With these options, you should be able to build a flow that would require a user to validate their email before being able to do anything with your app.

**Comment by zoechi** [comment]
@or1own I believe the information from @KevinTheGray solves the issue.
Closing as working as intended.

**Comment by or1own** [comment]
Works perfectly, thanks.
