### ISSUE TITLE
Images Optimizations

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#21649]
Hi, I need some info on optimizing images on the application side (not the server side, for e.g. responding with different sizes for the image).

Are there any Down Sampling or Image Resizing available in the flutter?
https://developer.android.com/topic/performance/graphics/load-bitmap

**Comment by zoechi** [comment]
Please check https://pub.dartlang.org/packages?q=image

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by p30arena** [comment]
This is more of a core feature request.
I've used most of the community libraries, most are buggy and not
maintained anymore or are maintained by an unprofessional programmer.
Customers complain about the performance of the apps we make using flutter.
I've made all of the optimizations one can think of, but the app still
doesn't feel completely native.

**Comment by zoechi** [comment]
I doubt the Flutter team will engage in image manipulation libraries.
You can always use a plugin to make native implementations available to Flutter https://flutter.io/developing-packages/

@Hixie any thoughts?

**Comment by Hixie** [comment]
I don't really understand the feature request here.

**Comment by CaiJingLong** [comment]
@p30arena  
If you just need compress image file, you can use [flutter_image_compress](https://pub.dartlang.org/packages/flutter_image_compress)

But I think an efficient down-sample algorithm is necessary, and flutter's `Image` is not as efficient as `Glide` at loading large images.
It load about 3 to 5 seconds to load 30 5M + local image into a `RecyclerView` using `Glide` in Android, and 15 seconds or more to use `GridView` +  `Image. file` in Flutter.

Flutter official provides a more efficient way to load large pictures is actually a more important thing.After all, the app itself is more often based on pictures and text

@zanderso  @Hixie

**Comment by p30arena** [comment]
> @p30arena
> If you just need compress image file, you can use [flutter_image_compress](https://pub.dartlang.org/packages/flutter_image_compress)
> 
> But I think an efficient down-sample algorithm is necessary, and flutter's `Image` is not as efficient as `Glide` at loading large images.
> It load about 3 to 5 seconds to load 30 5M + local image into a `RecyclerView` using `Glide` in Android, and 15 seconds or more to use `GridView` + `Image. file` in Flutter.
> 
> Flutter official provides a more efficient way to load large pictures is actually a more important thing.After all, the app itself is more often based on pictures and text
> 
> @zanderso @Hixie

That's my point, I wasn't able to elaborate, thanks.

**Comment by xuexin** [comment]
@zoechi @Hixie 
I think this issue should be opened again.
Thanks to @CaiJingLong 

> Flutter official provides a more efficient way to load large pictures is actually a more important thing.After all, the app itself is more often based on pictures and text

**Comment by p30arena** [comment]
We should also consider animated gifs, they take too much memory,
https://github.com/flutter/flutter/issues/22299#issuecomment-424836254

**Comment by zoechi** [comment]
I leave it to @Hixie to decide if this issue should be kept open or if this is left to community effort (plugin, ...)

**Comment by xuexin** [comment]
Gif takes too much memory
https://github.com/flutter/flutter/issues/20521

**Comment by zoechi** [comment]
Related #26194

**Comment by cbracken** [comment]
Since it's unclear to me what specifically is being requested here, I'm closing this in favour of #32156 which I've opened as a tracking issue for a collection of memory-related Flutter issues.
