### ISSUE TITLE
Failed assesrtion: boolean expression must not null

### ISSUE THREAD

**Issue by amansrii8** [flutter/flutter#21641]

**Comment by amansrii8** [comment]
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> 09-10 19:09:29.381 22644-24024/parentapp.com.parentappflutter I/flutter: The following assertion was thrown building LoginPage(dirty, state: _LoginPageState#dedbc):
> 09-10 19:09:29.424 22644-24024/parentapp.com.parentappflutter I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
> 09-10 19:09:29.425 22644-24024/parentapp.com.parentappflutter I/flutter: When the exception was thrown, this was the stack:
> 09-10 19:09:29.460 22644-24024/parentapp.com.parentappflutter I/flutter: #0      _LoginPageState.build._buildBody (package:parent_app_flutter/pages/MainLogin.dart:134:11)
> 09-10 19:09:29.461 22644-24024/parentapp.com.parentappflutter I/flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
> 09-10 19:09:29.462 22644-24024/parentapp.com.parentappflutter I/flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
> 09-10 19:09:29.463 22644-24024/parentapp.com.parentappflutter I/flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.464 22644-24024/parentapp.com.parentappflutter I/flutter: #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
> 09-10 19:09:29.465 22644-24024/parentapp.com.parentappflutter I/flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
> 09-10 19:09:29.466 22644-24024/parentapp.com.parentappflutter I/flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
> 09-10 19:09:29.467 22644-24024/parentapp.com.parentappflutter I/flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
> 09-10 19:09:29.468 22644-24024/parentapp.com.parentappflutter I/flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.469 22644-24024/parentapp.com.parentappflutter I/flutter: #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4666:14)
> 09-10 19:09:29.470 22644-24024/parentapp.com.parentappflutter I/flutter: #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
> 09-10 19:09:29.471 22644-24024/parentapp.com.parentappflutter I/flutter: #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
> 09-10 19:09:29.472 22644-24024/parentapp.com.parentappflutter I/flutter: #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
> 09-10 19:09:29.473 22644-24024/parentapp.com.parentappflutter I/flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
> 09-10 19:09:29.474 22644-24024/parentapp.com.parentappflutter I/flutter: #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
> 09-10 19:09:29.475 22644-24024/parentapp.com.parentappflutter I/flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.476 22644-24024/parentapp.com.parentappflutter I/flutter: #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.477 22644-24024/parentapp.com.parentappflutter I/flutter: #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
> 09-10 19:09:29.478 22644-24024/parentapp.com.parentappflutter I/flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.479 22644-24024/parentapp.com.parentappflutter I/flutter: #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
> 09-10 19:09:29.480 22644-24024/parentapp.com.parentappflutter I/flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.481 22644-24024/parentapp.com.parentappflutter I/flutter: #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
> 09-10 19:09:29.482 22644-24024/parentapp.com.parentappflutter I/flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
> 09-10 19:09:29.483 22644-24024/parentapp.com.parentappflutter I/flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
> 09-10 19:09:29.484 22644-24024/parentapp.com.parentappflutter I/flutter: #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
> 09-10 19:09:29.485 22644-24024/parentapp.com.parentappflutter I/flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
> 09-10 19:09:29.486 22644-24024/parentapp.com.parentappflutter I/flutter: #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
> 09-10 19:09:29.487 22644-24024/parentapp.com.parentappflutter I/flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.488 22644-24024/parentapp.com.parentappflutter I/flutter: #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
> 09-10 19:09:29.489 22644-24024/parentapp.com.parentappflutter I/flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
> 09-10 19:09:29.490 22644-24024/parentapp.com.parentappflutter I/flutter: #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
> 09-10 19:09:29.491 22644-24024/parentapp.com.parentappflutter I/flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
> 09-10 19:09:29.492 22644-24024/parentapp.com.parentappflutter I/flutter: #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
> 09-10 19:09:29.493 22644-24024/parentapp.com.parentappflutter I/flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
> 09-10 19:09:29.494 22644-24024/parentapp.com.parentappflutter I/flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
> 09-10 19:09:29.495 22644-24024/parentapp.com.parentappflutter I/flutter: #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
> 09-10 19:09:29.496 22644-24024/parentapp.com.parentappflutter I/flutter: #116    StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
> 09-10 19:09:29.497 22644-24024/parentapp.com.parentappflutter I/flutter: #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
> 09-10 19:09:29.498 22644-24024/parentapp.com.parentappflutter I/flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
> 09-10 19:09:29.499 22644-24024/parentapp.com.parentappflutter I/flutter: #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:653:20)
> 09-10 19:09:29.500 22644-24024/parentapp.com.parentappflutter I/flutter: #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
> 09-10 19:09:29.501 22644-24024/parentapp.com.parentappflutter I/flutter: #130    _invoke (dart:ui/hooks.dart:128:13)

**Comment by zoechi** [comment]
This looks like an issue in your code _LoginPageState.build._buildBody (package:parent_app_flutter/pages/MainLogin.dart:134:11)

Perhaps the common mistake to assume that `if(foo)` always evaluates to `true` or `false`.
If `foo` is `null` you'll get this exception.
In Dart variables of type bool can have value `null` (until Dart gets non-nullable types). 

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
