### ISSUE TITLE
How to see how widgets will display without implementing it

### ISSUE THREAD

**Issue by lkhgvsuren** [flutter/flutter#21643]
In flutter.io docs there are bunch of words. How to see a demo of widgets in gifs or pictures? I don't know how these widgets will display.

**Comment by zoechi** [comment]
There are a lot of images of the widgets in https://flutter.io/widgets/material/ and https://flutter.io/widgets/cupertino/

Can you please be more specific about what you are missing?

**Comment by lkhgvsuren** [comment]
@zoechi for example,
https://docs.flutter.io/flutter/material/Drawer-class.html in this drawer doc there is no such a image.

**Comment by zoechi** [comment]
The drawer is just an empty frame. It only shows what you put into it.
So it's a bit difficult to make a screenshot of it.

**Comment by Sfshaza** [comment]
Thanks, @zoechi! @lkhgvsuren, please open new bugs if you have specific requests.
