### ISSUE TITLE
Flutter doctor doesn't know patient is dead

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2166]
If I run `flutter doctor`, it shows everything is good. When I run `flutter start`, it says "Cannot locate the sky_engine package; did you include 'flutter' in your pubspec.yaml file?" This feels strange that the doctor says things are good but the patient is non-responsive.

Talked to Devon and he agrees that we should probably do some basic checking of the current project if `flutter doctor` is run from a project directory.

### Steps to Reproduce
This is a little tricky to recreate because `flutter start` will automatically run pub get for a new project. I saw this problem happen when I did a git pull on my flutter directory, then tried to run a file in examples/widgets without running pub get.

### Flutter Version
Flutter from <unknown> (on )
flutter revision: a6f0c97a22ba52e5522428f9baff0dd19f317d96 (6 days ago)
engine revision : 139bdb96422003f3b931a9dfbbbe2479317bb43d

**Comment by jimbeveridge** [comment]
In another case, I saw this error:
```
Error: incompatible sky_engine package; please run 'pub get' to get the correct one.
```

**Comment by abarth** [comment]
> Cannot locate the sky_engine package; did you include 'flutter' in your pubspec.yaml file?"

This error no longer exists.  The other error you mention also doesn't exist anymore.

**Comment by abarth** [comment]
I'm going to close this issue because the specific errors reported here don't exist anymore.  There are certainly cases we can improve about flutter doctor, but we should file separate issues for them.
