### ISSUE TITLE
pubspec.lock->sdks->dart:"<empty>"

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter#21673]
I have upgrade Flutter today
when I use Flutter packages get
the pubspec.lock->sdks change like this
```
sdks:
  dart: "<empty>"
  flutter: ">=0.4.1 <=0.5.7"
```

then I use `flutter packages get` it's error

```
Error on line 521, column 9 of pubspec.lock: Invalid version constraint: Expected version number after "<" in "<empty>", got "empty>".
  dart: "<empty>"
        ^^^^^^^^^
package:pub/src/lock_file.dart 189:7                                                        LockFile._wrapFormatException
package:pub/src/lock_file.dart 175:12                                                       LockFile._parseVersionConstraint
package:pub/src/lock_file.dart 116:13                                                       LockFile._parse.<fn>
dart:collection                                                                             MapView.forEach
package:pub/src/lock_file.dart 113:23                                                       LockFile._parse
package:pub/src/lock_file.dart 78:21                                                        new LockFile.load
package:pub/src/entrypoint.dart 92:28                                                       Entrypoint.lockFile
package:pub/src/entrypoint.dart 201:19                                                      Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                                      GetCommand.run
package:args/command_runner.dart 194:27                                                     CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168:39                                                  PubCommandRunner.runCommand.<fn>
dart:async                                                                                  new Future.sync
package:pub/src/utils.dart 109:12                                                           captureErrors.<fn>
dart:async                                                                                  runZoned
package:pub/src/utils.dart 126:5                                                            captureErrors
package:pub/src/command_runner.dart 168:13                                                  PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117:11                                                  PubCommandRunner.run
===== asynchronous gap ===========================
/b/build/slave/Mac_Engine/build/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (65)
Process finished with exit code 65
```

I dont know why.it works well before upgrade(from flutter 0.5.7).

chinese:
今天我运行了Flutter upgrade 进行更新（从0.5.7版本）
更新后只要我运行flutter packages get，pubspec.lock中的sdks里的dart就会变成empty。这时候只要再进行flutter packages get，就会报错，错误信息如上。我不知道怎么回事，在更新之前没有这样的问题，现在我只能每次运行get以后再把之前的
`>=2.0.0-dev.52.0 <=2.0.0-dev.58.0.flutter-f981f09760`
粘贴回去才可以再次获取新的packages

**Comment by zoechi** [comment]
Can you please try
```
flutter packages upgrade
```

and please post the output of `flutter doctor -v`

**Comment by 39499740** [comment]
`[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.7.3 at /Users/haoyi/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/haoyi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone X • 636655C2-3AC3-4FD6-AECF-7D0F6BC87069 • ios • iOS 11.4 (simulator)

• No issues found!
`

**Comment by 39499740** [comment]
This is my pubspec.yaml
`dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.0.2
  dio: 1.0.4
  shared_preferences: ^0.4.2
  fluttertoast: ^2.0.6
  http: ^0.11.3+16
  uuid: ^1.0.3
  image_picker: ^0.4.5
  native_widgets: ^0.1.1+1
  photo_view: ^0.0.3
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  flutter_cupertino_date_picker: ^0.0.3
  charts_flutter: ^0.4.0
  flutter_spinkit: "^2.0.0"
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  dropdown_menu: ^1.1.0
  flutter_sticky_header: "^0.3.4"
`

**Comment by zoechi** [comment]
Did you try
```
flutter packages upgrade
``` 
?

**Comment by 39499740** [comment]
➜  emp git:(master) flutter packages upgrade
Running "flutter packages upgrade" in emp 14.01.52...       45.9s
➜  emp git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.7.3 at /Users/haoyi/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/haoyi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone X • 636655C2-3AC3-4FD6-AECF-7D0F6BC87069 • ios • iOS 11.4 (simulator)

• No issues found!

yes

**Comment by zoechi** [comment]
Does this mean `flutter packages upgrade` worked?
The output looks incomplete.

**Comment by 39499740** [comment]
i dont know. it's worked this morning.my flutter is 0.5.7,and 0.7.3 now

**Comment by 39499740** [comment]
Once I've executed "flutter packages get," the "sdks: dart:" in the pubspec. lock file becomes "<empty>". I don't know why, but this happens every time.

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by leorachit** [comment]
Yes, it's still happening after running flutter packages upgrade. Please help.
