### ISSUE TITLE
flutter doesn't think I have a device connected despite adb devices returning one.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2167]
$ flutter start  && flutter logs
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.

Running flutter doctor indicates no problems:
```
$ flutter doctor
Flutter root:<redacted>/flutter.

[✓] Android toolchain - develop for Android devices (installed)
  [✓] Android SDK - enable development for Android devices (installed)

[✓] Atom development environment - a lightweight development environment for Flutter (installed)
  [✓] Atom editor (installed)
  [✓] Flutter plugin - adds Flutter specific functionality to Atom (installed)

Flutter from <unknown> (on )
flutter revision: 135a38d693b5f8a255c506fd61cf2d388d9afb95 (80 minutes ago)
engine revision : a53faaf7983025f83a2059021a409c6e98beb58d
```

**Comment by devoncarew** [comment]
What's the output from `flutter devices`?

**Comment by apwilson** [comment]
It lists the device as well:

$ flutter devices
1 connected device:

Pixel C (5A17000207)

**Comment by apwilson** [comment]
I'll close this issue in favor of ther other.

**Comment by sandeepreddy-vinta** [comment]
flutter devices is unable to detect my connected android device on my Windows Machine.


flutter doctor output:

C:\Users\tejaswini>flutter doctor
[ΓêÜ] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-IN, channel al
pha)
    ΓÇó Flutter at C:\Users\tejaswini\flutter
    ΓÇó Framework revision 1c372c6803 (9 days ago), 2017-08-31 15:54:45 -0700
    ΓÇó Engine revision f9e00a7c72
    ΓÇó Tools Dart version 1.25.0-dev.11.0

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    ΓÇó Android SDK at C:\Users\tejaswini\AppData\Local\Android\sdk
    ΓÇó Platform android-25, build-tools 25.0.3
    ΓÇó ANDROID_HOME = C:\Users\tejaswini\AppData\Local\Android\sdk
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[ΓêÜ] Android Studio (version 2.3)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[ΓêÜ] IntelliJ IDEA Community Edition (version 2017.2)
    ΓÇó Flutter plugin version 17.0
    ΓÇó Dart plugin version 172.3757.55

[ΓêÜ] Connected devices
    ΓÇó None



flutter devices output


C:\Users\tejaswini>flutter devices
No devices detected.

If you expected your device to be detected, please run "flutter doctor" to diagn
ose
potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.


Request your kind help. Desperate to try running flutter.

**Comment by deepak-gehlot** [comment]
@sandeepreddy-vinta  facing same isse in window machin.

**Comment by ddave-22** [comment]
Yes I am having the same issue.. with android studio as well as VS Code i guess something wrong with adb

**Comment by NathanaelA** [comment]
If `flutter devices` isn't working for Android try doing `adb devices` and verify that adb is actually seeing it.
In the event adb doesn't see it; if you haven't ever used this device for development you need to enable USB debugging (see my answer at SO: https://stackoverflow.com/questions/50609664) otherwise `adb` will never see it.

If `flutter devices` isn't working for iOS try seeing if xcode can see your devices.  You might have to actually activate the device for development if you have never done so OR have upgraded iOS on the device since the last time you did.

**Comment by Deracination** [comment]
I had the same problem in Windows 10 with android SDK installed to a 'non-standard' location (not on C:\)

Setting the ANDROID_HOME environment variable fixed the problem (via Control Panel, System, Advanced system settings, Environment variables, or using setx at the commandline)

I guess the flutter plugin doesn't query the android studio environment for the sdk location?

**Comment by neelu004** [comment]
Hi, I am not able to run the flutter project via cmd when using the command flutter run when my iPhone device is still connected.
Yes I am using Mac to build iOS flutter
Please suggest some solution.
Thanks
