### ISSUE TITLE
0.7.3v introduced "controller not attached" exception

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#21683]
When I was on v0.6.1 I did not have any issues. I upgraded to v0.7.3 and now I get an unhandled exception when I try to manipulate the position of a PageView.

Interestingly enough, everything works except for this exception which is only removed when I comment out the `.jumpTo()` line

```dart
  Widget build(BuildContext context) {
    final _controller = PageController();
    double height = 36.0;

    BlocProvider.of(context).page.listen((page) { // this streams _controller.page() from another PageView
      _controller.jumpTo(height * page); // this manipulates the position, exception disappears when commented out
    });

    return Container(
      height: height,
      child: PageView(
        controller: _controller, // it is attached here
        scrollDirection: Axis.vertical,
        pageSnapping: false,
        physics: NeverScrollableScrollPhysics(),
        children: categories
            .map((c) => _Title(
                  title: c.title,
                  index: categories.indexOf(c),
                ))
            .toList(),
      ),
    );
  }
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (2 available)

• No issues found!
```

```
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 169 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:169:12)
#3      MyTitle.build.<anonymous closure> (file:///Users/lukepighetti/code/when-coin/when_coin_2/lib/screens/rate/widgets/title.dart:18:19)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by lukepighetti** [comment]
Downgraded to v0.6.2 via `git checkout 392a178169a9e620a5ae8e55c40d4276cddd3b36` and having the same problem.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.6.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (2 available)

• No issues found!
```

**Comment by lukepighetti** [comment]
Downgraded to v0.6.0 via `git checkout 9299c02cf708497d6f72edda8efae0bb8340660e` and I can confirm that the problem is resolved at this commit. Not sure which commit introduced the failed assertion. Would love some guidance on if I'm doing something wrong here, I don't want to get left behind.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (2 available)

• No issues found!
```

**Comment by lukepighetti** [comment]
Just tried v0.6.1 via `git checkout ad1eaff45ab97ab65e2dd5aba768d19a4b48d49b` and the failed exception error is present. So apparently the error was introduced between commit `392a178169a9e620a5ae8e55c40d4276cddd3b36` and `9299c02cf708497d6f72edda8efae0bb8340660e`.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.6.1, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.1)
[✓] Connected devices (2 available)

• No issues found!
```

**Comment by lukepighetti** [comment]
Just refactored from a PageView to a ListView and the problem persists on `v0.7.3`

Is `ScrollController.jumpTo()` broken after v0.6.1? 🤔

**Comment by zoechi** [comment]
Are you still seeing this?
Can you please create a complete runnable minimal reproduction?

**Comment by lukepighetti** [comment]
Haven't written code like this in a few months. I think it can be closed.

**Comment by crimsonsuv** [comment]
Getting this issue I dont know the reason yet, few days back everything was working fine now suddenly started getting this issue.

`E/flutter ( 9253): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter ( 9253): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 9253): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 9253): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
E/flutter ( 9253): #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:118:24)
E/flutter ( 9253): #4      PostsListState._fetchPosts.<anonymous closure> (package:wakwat/src/screens/posts/posts_list.dart:148:57)
E/flutter ( 9253): #5      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 9253): #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9253): #7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 9253): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 9253): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 9253): #10     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 9253): #11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 9253): #12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 9253): #13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 9253): #14     getPosts (package:wakwat/api/get_services/posts_service.dart)
E/flutter ( 9253): <asynchronous suspension>
E/flutter ( 9253): #15     PostsListState._fetchPosts (package:wakwat/src/screens/posts/posts_list.dart:119:20)
E/flutter ( 9253): <asynchronous suspension>
E/flutter ( 9253): #16     PostsListState.initState (package:wakwat/src/screens/posts/posts_list.dart:56:5)
E/flutter ( 9253): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter ( 9253): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 9253): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 9253): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 9253): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 9253): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 9253): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 9253): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 9253): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 9253): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #37     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
E/flutter ( 9253): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 9253): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 9253): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 9253): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 9253): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 9253): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter ( 9253): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 9253): #45     Element.inflateWidget (package:flutter/sr`

Here is the flutter doctor Output:
`/home/maximus/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_IN)
    • Flutter version 1.5.4-hotfix.2 at /home/maximus/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/maximus/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/maximus/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/maximus/Documents/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!`
