### ISSUE TITLE
VM failed to initialize: Failed to work with existing iOS app 

### ISSUE THREAD

**Issue by yjoo9317** [flutter/flutter#21684]
## Steps to Reproduce

I followed exactly https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
But it fails at `FlutterViewController *flutterViewController = [[FlutterViewController alloc] init];`
with errors saying VM snapshot is not valid and not initialized.

I attached the contents of the folder after success build.

![screen shot 2018-09-11 at 7 35 21 am](https://user-images.githubusercontent.com/21015969/45367139-67bd1680-b595-11e8-8447-767e2f2d3a04.png)
The above is under flutter.assets

![screen shot 2018-09-11 at 7 37 30 am](https://user-images.githubusercontent.com/21015969/45367200-9509c480-b595-11e8-8895-583138610194.png)
The above is under flutter module build dir. 

I have noticed that we might need snapshot data under `flutter.assets` dir to implant in the device.
(I could be wrong.)
If it does, then somehow it failed to generate that data in the designated dir.

## Logs

[VERBOSE-2:dart_vm.cc(278)] VM snapshot must be valid.
[VERBOSE-3:shell.cc(209)] Check failed: vm. Must be able to initialize the VM.

[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.7.3 at /Users/youngjoo.park/Library/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/name/Library/Android/sdk
    • Android NDK at /Users/name/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/name/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

**Comment by yjoo9317** [comment]
It was due to release/debug xcconfig issue. In our configuration, debug.xcconfig includes release.xcconfig internally which eventually set both (release&debug) mode=release.

**Comment by jt100xu** [comment]
Hi @yjoo9317, I'm facing this issues. I'm just setting up my ios project follow the Wiki.
Did you do some things else?

**Comment by yjoo9317** [comment]
> Hi @yjoo9317, I'm facing this issues. I'm just setting up my ios project follow the Wiki.
> Did you do some things else?

Hello @jt100xu 
To be clear on my issue, 
in release.xcconfig, as you know, we are setting build mode as `release`.
Our debug.xcconfig is including release.xcconfig which makes debug.xcconfig run as release mode as well.
So I added the line setting build mode as `debug` to `debug.xcconfig`.
Also check if you have snapshot-data file in your asset directory after build.
Without it, it looks like it fails to initialize VM.

**Comment by jt100xu** [comment]
@yjoo9317 , yes you are right, there is no snapshot-data file in my flutter_assets directory.
Can you help me how to fix it?
