### ISSUE TITLE
iOS Plugin fails to build with Flutter, runs in Xcode

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#21695]
## Steps to Reproduce

This is an issue encountered by one of our customers. 

This issue seems to only repro on a physical ios (iphone 6s/11.4.1) device. Build on emulator device just works fine. The plugin won't build with flutter, but will build in Xcode. Additionally if you try to build in Flutter after successfully building with Xcode, it still won't build.  Here is the call stack:

## Logs

```
ld: warning: ignoring file /Users/foo/projects/flutter/project_name/example/ios/ProjectName.framework/ProjectName, missing required architecture armv7 in file /Users/foo/projects/flutter/project_name/example/ios/ProjectName.framework/ProjectName (2 slices)
    Undefined symbols for architecture armv7:
      "_PNErrorDebugMessageKey", referenced from:
          ___43-[ProjectNamePlugin handleMethodCall:result:]_block_invoke_2 in ProjectNamePlugin.o
          -[ProjectNamePlugin checkoutController:didFailWithError:] in ProjectNamePlugin.o
          -[ProjectNamePlugin projectSettingsController:didFailToPresentWithError:] in ProjectNamePlugin.o
      "_OBJC_CLASS_$_ProjectSDK", referenced from:
          objc-class-ref in ProjectNamePlugin.o
      "_OBJC_CLASS_$_PrjectNameSettingsController", referenced from:
          objc-class-ref in ProjectNamePlugin.o
      "_SQRDErrorDebugCodeKey", referenced from:
          ___43-[ProjectNamePlugin handleMethodCall:result:]_block_invoke_2 in ProjectNamePlugin.o
          -[ProjectNamePlugin checkoutController:didFailWithError:] in ProjectNamePlugin.o
          -[ProjectNamePlugin projectSettingsController:didFailToPresentWithError:] in ProjectNamePlugin.o
      "_OBJC_CLASS_$_Bar", referenced from:
          objc-class-ref in ProjectNamePlugin.o
      "_OBJC_CLASS_$_Baz", referenced from:
          objc-class-ref in ProjectNamePlugin.o
      "_OBJC_CLASS_$_Qux", referenced from:
          objc-class-ref in ProjectNamePlugin.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
```

**Comment by zoechi** [comment]
#13638 shows a similar error message and also on real devices

Please try the workaround mentioned in  https://github.com/flutter/flutter/issues/13638#issuecomment-413022948

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by CharlesCleveJr** [comment]
No, I was able to clear it with a new Flutter build

**Comment by zoechi** [comment]
Reopen - wait for @efortuna to confirm

**Comment by efortuna** [comment]
paging @hukid to confirm this is no longer an issue

**Comment by hukid** [comment]
This isn't an issue anymore. @efortuna

**Comment by zoechi** [comment]
Thanks all!

**Comment by gerry05** [comment]
I still encounter this issue. I tried also the solution in https://github.com/flutter/flutter/issues/13638#issuecomment-413022948 but I still get the errors.

![nxplayer bin_jmUKtiEDTn](https://user-images.githubusercontent.com/26299783/60758708-02b73d80-a04d-11e9-8c68-d56e020d4fe9.png)

**Comment by lifenautjoe** [comment]
Still encoutering the issue here too.. The workaround mentioned doesn't work

**Comment by lifenautjoe** [comment]
Update: Doing a `flutter build ios` works... `flutter run` doesn't.
