### ISSUE TITLE
Can you guys do some work on you documents

### ISSUE THREAD

**Issue by Su9Tail** [flutter/flutter#21692]
I'm new to flutter. When I check the documents of flutter on the officical website, i was shocked that i even cannot find a full list of widgets and the way to use them. I must go `docs.flutter.io` to find what i want to find on `https://flutter.io/docs/`. If you do not want to build the website, please make us know how to use flutter and how to find you docs.

**Comment by zoechi** [comment]
Thanks for checking out Flutter.

I don't see an issue with clicking the "Docs" link in http://flutter.io
That not all widgets are listed is a known issue.

A lot of things are work-in-progress and things might be inconsistent or incomplete.
A general rant isn't actionable though.

Please report only concrete issues and create a new issue for every problem.
Issues with a list of problems are hard to manage.

Please also check if there already exists an issue before you create a new one.
 
Closing this as not actionable.
