### ISSUE TITLE
flutter and flutter --version keep telling me my atom dev environment and android sdk are good

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2169]
I feel like that's extraneous information that's not important to flutter.  (ie. what if I'm a  developer that works in vi or emacs or something working on an iOS app, I'd have neither checked ever).

**Comment by Hixie** [comment]
This seems reasonable.

cc @devoncarew

**Comment by devoncarew** [comment]
`flutter --version` now only emits flutter version info, not a compact version of doctor. We can change `flutter -h` to do the same. (https://github.com/flutter/flutter/pull/2859)
