### ISSUE TITLE
The padding in a Material TabBar is hard-coded

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#21694]
The padding between tabs in a Material TabBar is hard-coded, and this makes it hard to achieve some quite reasonable designs.

I would like this padding between tabs to be configurable per-TabBar, and not hard-coded in the Flutter libraries.

Here's an example. My designer would like to achieve this:

![image](https://user-images.githubusercontent.com/4321921/45377099-7f29ed00-b5f1-11e8-9553-568bc48a2d4f.png)

I can approach it in Flutter, but I have a problem:

![image](https://user-images.githubusercontent.com/4321921/45377126-8f41cc80-b5f1-11e8-9d08-8ffa4d7edb73.png)

The tab heading "MON 22" is too long for the space that is available. Here's why:

![image](https://user-images.githubusercontent.com/4321921/45377152-a8e31400-b5f1-11e8-8709-06c7808211a8.png)

There is padding around each tab:

![image](https://user-images.githubusercontent.com/4321921/45377174-b7313000-b5f1-11e8-994c-26a2486f954d.png)

The reason for this is in material/tabs.dart, line 880:

```
  @override
  Widget build(BuildContext context) {
    final MaterialLocalizations localizations = MaterialLocalizations.of(context);
    if (_controller.length == 0) {
      return new Container(
        height: _kTabHeight + widget.indicatorWeight,
      );
    }

    final List<Widget> wrappedTabs = new List<Widget>(widget.tabs.length);
    for (int i = 0; i < widget.tabs.length; i += 1) {
      wrappedTabs[i] = new Center(
        heightFactor: 1.0,
        child: new Padding(
          padding: kTabLabelPadding,
          child: new KeyedSubtree(
            key: _tabKeys[i],
            child: widget.tabs[i],
          ),
        ),
      );

    }
```

Each tab is padded by `kTabLabelPadding` — which I think is Hungarian for a constant tab label padding.

This is defined as:

```
/// The horizontal padding included by [Tab]s.
const EdgeInsets kTabLabelPadding = EdgeInsets.symmetric(horizontal: 16.0);
```

If I change this to `8.0` and restart my app, the tab fits:

![image](https://user-images.githubusercontent.com/4321921/45377421-7dacf480-b5f2-11e8-9f66-d7d893ec46cc.png)

My designer is happy

![image](https://user-images.githubusercontent.com/4321921/45377449-8d2c3d80-b5f2-11e8-9d5a-76f29ae6adf8.png)

This is on today's Flutter master channel.

 @HansMuller filing this separate issue as requested in https://github.com/flutter/flutter/issues/21026

**Comment by zoechi** [comment]
It's always a good idea to add the output of `flutter doctor -v` to make it clear what Flutter version this issue is related to and in what environment you are using Flutter.

**Comment by SteveAlexander** [comment]
@zoechi Thanks, good call!

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.8.2-pre.24, on Mac OS X 10.13.6 17G2307, locale en-GB)
    • Flutter version 0.8.2-pre.24 at /Users/steve/code/flutter
    • Framework revision 4d9bbc10f2 (3 days ago), 2018-09-09 03:15:34 -0400
    • Engine revision 1770f88548
    • Dart version 2.1.0-dev.4.0.flutter-cd9a42239f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone X • 1E0393AA-EF50-42AA-A244-3279599BE2C1 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by SteveAlexander** [comment]
Thanks @HansMuller !
