### ISSUE TITLE
Provide pubspec control of AndroidManifest and Info.plist

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21701]
Flutter plugins may require editing of AndroidManifest.xml and/or Info.plist.  This is impossible with a generated host app, though it is possible with an editable host app.

However, we don't want to force developers to make their host app editable at the first plugin requirement.  So this ticket is to add appropriate configuration options to pubspec.yaml that are automatically injected into AndroidManifest.xml and Info.plist as needed within the generated project.

CC @dnfield

**Comment by dnfield** [comment]
My initial thought on this was to provide some interface through pubspec.yaml to specify an XPath or something to set attributes/nodes in plist/AndroidManifest.

However, a potentially "simple" solution for this would be to allow the user to have an override file. for these, and have them provide that to `flutter create`.  The build process(es) could then be made to look for that override file if it's specified in pubspec, and copy it into the hidden generated area.

**Comment by dnfield** [comment]
This is no longer as critical given changes in app structure proposals - may need to revist at some point, but closing for now.
