### ISSUE TITLE
Android Studio 3.2 RC 3 is not working correctly with the Flutter plugin

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#21700]
*Everytime opening a Flutter project*, no matter what I have tried, I will have to do either or multiple of the following things:

   1. Reassign the `Flutter SDK path`: 
![](https://i.imgur.com/chInLbR.png)

   1. Enable Dart support for the project: 
![](https://i.imgur.com/vldv3oZ.png)

   1. Sync project with Gradle Files.

Before that, the project view looks like this: 
![](https://i.imgur.com/zth0M6h.png)
That means that I am unable to access any project directories (`android`, `ios` or `lib`) because the Flutter plugin is not connected properly (until I fix it with the necessary steps described above).  
This also disables all code analysis and completion features (if I open a file externally because I cannot access it from inside the workspace before enabling support and syncing) & the ability to run the application from within Android Studio.

### I have tried

Reinstalling from [the Android Studio Preview website](https://developer.android.com/studio/preview/) and `flutter upgrade`..

### Doctor

```
flutter doctor -v
[√] Flutter (Channel master, v0.8.3-pre.28, on Microsoft Windows [Version 10.0], locale en-US)
    • Flutter version 0.8.3-pre.28 at flutterRoot
    • Framework revision 0e8103ff13 (4 hours ago), 2018-09-11 18:16:21 +0200
    • Engine revision 9a173a8dc8
    • Dart version 2.1.0-dev.4.0.flutter-ef72098353

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at sdkRoot
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: javaRoot
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at studioRoot
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2600](https://github.com/flutter/flutter-intellij/issues/2600) via [**ZenHub**](https://www.zenhub.com/)
