### ISSUE TITLE
Why can't I find the documentation for some widgets in the Flutter Widget Index

### ISSUE THREAD

**Issue by TaroXin** [flutter/flutter#21722]
Why can't I find the documentation for some widgets in the Flutter Widget Index, Such as `AnnotatedRegion`, i want to know if there is a way to query a widget's usage document, Thank you very much!

**Comment by zoechi** [comment]
It is known that not all widgets are listed in the widgets gallery. I don't know what the reasons are.

Searching always works for me (if I know the name)

![image](https://user-images.githubusercontent.com/405837/45418605-36237880-b685-11e8-95ec-7037b9304316.png)

![image](https://user-images.githubusercontent.com/405837/45418638-4a677580-b685-11e8-840f-963a022cd7fa.png)

**Comment by zoechi** [comment]
Merging with #18319
