### ISSUE TITLE
Correction in 'Spelling'

### ISSUE THREAD

**Issue by joyatjoseph** [flutter/flutter#21721]
There is a spelling mistake in the below link of flutter on 'Undestanding' existing layouts.
 URL is   https://flutter.io/inspector/#flutter-widget-inspector
![correction](https://user-images.githubusercontent.com/41567138/45416899-8955f500-b69e-11e8-80cf-52c128342b11.png)

**Comment by Sfshaza** [comment]
Thanks for catching that, @joyatjoseph! Fixed on the dash branch.
