### ISSUE TITLE
Do you have any plan to publish a visual designer?

### ISSUE THREAD

**Issue by xioxu** [flutter/flutter#21720]
I am a new user of flutter, and I think it is a greet product.
But I think if flutter have a visual designer to generate the wiget layout code may same many tilme of the programmer.
So I want to know do you have any plan to publish a visual designer?

**Comment by flddr** [comment]
@xioxu 

there are several designers out already, have a look at https://medium.com/@pmutisya/flutter-studio-version-2-41cce10fcf3d

or look for other online tools :)

**Comment by zoechi** [comment]
Closing as dup of https://github.com/flutter/flutter-intellij/issues/2347

**Comment by zoechi** [comment]
Flutter Inspector gets a preview. Haven't tried it since a while. It didn't yet work for me the last time.
