### ISSUE TITLE
updated video player 0.7.5 "Could not find method android.graphics.SurfaceTexture.setOnFrameAvailableListener"

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#21730]
```
I/dalvikvm( 5366): Could not find method android.graphics.SurfaceTexture.setOnFrameAvailableListener, referenced from method io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>
W/dalvikvm( 5366): VFY: unable to resolve virtual method 697: Landroid/graphics/SurfaceTexture;.setOnFrameAvailableListener (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V
D/dalvikvm( 5366): VFY: replacing opcode 0x6e at 0x0015
E/flutter ( 5366): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
E/flutter ( 5366): 	at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:969)
E/flutter ( 5366): 	at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:955)
E/flutter ( 5366): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:291)
E/flutter ( 5366): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/flutter ( 5366): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/flutter ( 5366): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 5366): 	at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter ( 5366): 	at android.os.Looper.loop(Looper.java:150)
E/flutter ( 5366): 	at android.app.ActivityThread.main(ActivityThread.java:5323)
E/flutter ( 5366): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter ( 5366): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter ( 5366): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
E/flutter ( 5366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
E/flutter ( 5366): 	at dalvik.system.NativeStart.main(Native Method)
E/flutter ( 5366): 
F/flutter ( 5366): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    ( 5366): Fatal signal 6 (SIGABRT) at 0x000014f6 (code=-6), thread 5366 (ive.mysterylive)
handle_request(15)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Have you tried `flutter clean`?

**Comment by Seifon** [comment]
[✓] Flutter (Channel dev, v0.8.2, on Mac OS X 10.13.1 17B1003, locale zh-Hans-CN)
    • Flutter version 0.8.2 at /Library/Java/flutter
    • Framework revision 5ab9e70727 (6 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Library/Java/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Library/Java/android-sdk-macosx
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (1 available)
    • M10 • 0123456789ABCDEF • android-arm • Android 7.0 (API 19)

! Doctor found issues in 1 category.

**Comment by Seifon** [comment]
I found the reason. It's a question of flutter 0.8.2

I updated flutter 0.8.2, This problem arises.

**Comment by Mariluk** [comment]
Hi, I have same error in my camera plugin after updated flutter on line:

FlutterView.SurfaceTextureEntry surfaceTextureEntry = flutterView.createSurfaceTexture();

For android lollipop and higher it works fine.

[✓] Flutter (Channel master, v0.9.4-pre.31, on Linux, locale cs_CZ.UTF-8)
• Flutter version 0.9.4-pre.31 at /home/lmarik/flutter
• Framework revision 52697ef (5 hours ago), 2018-09-26 07:57:05 +0200
• Engine revision 38a646e14c
• Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
• Android SDK at /home/lmarik/Android/Sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-27, build-tools 27.0.3
• Java binary at: /usr/local/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
• All Android licenses accepted.

[✓] Android Studio (version 3.2)
• Android Studio at /usr/local/android-studio
• Flutter plugin version 28.0.2
• Dart plugin version 181.5616
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
• IntelliJ at /home/lmarik/Stažené/ideaIU-2018.1.4/idea-IU-181.5087.20
• Flutter plugin version 26.0.2
• Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
• Lenovo A7600 F • HJA4RYNC • android-arm • Android 4.4.2 (API 19)

• No issues found!

**Comment by rmtmckenzie** [comment]
I'm seeing the same issue as well (as I imagine anyone using createSurfaceTexture is). My app is affected on any device older than lollipop, and the qr plugin I'm maintaining has several users who will be affected by this as well - a few of them requested support down to api level 16...

**Comment by Mariluk** [comment]
I must build on version Flutter v0.7.6-pre.25 on master channel, for now and wait for repair.  Its for fine.

**Comment by Seifon** [comment]
> I must build on version Flutter v0.7.6-pre.25 on master channel, for now and wait for repair. Its for fine.

me too, I stay Flutter v0.8.0
