### ISSUE TITLE
Firestore runTransaction offline behavior should be mentioned in readme?

### ISSUE THREAD

**Issue by holyspidoo** [flutter/flutter#21740]
Took me a while to figure out runTransaction won't work offline after it retries a few times whereas an operation (update,create,etc.) on the document reference works with offline persistence.

I feel like that is such a big deal, maybe it should be noted in the Readme.md? Especially now that we can set persistence off.

Right now, the readme leads one to believe that one should always go with Transactions.

**Comment by zoechi** [comment]
Is this behavior different then with other clients (Android, iOS, web, ...)?

I don't think it makes sense to replicate all Firebase docs in the plugin repo.

**Comment by holyspidoo** [comment]
Yeah, I guess it is mentioned in the Cloud Firestore API docs

**Comment by 1and1get2** [comment]
If i  didn't come across this issue I wouldn't have thought of it
