### ISSUE TITLE
TextField cursor jump to the first character when typing Thai vowel above and below the alphabet

### ISSUE THREAD

**Issue by heart** [flutter/flutter#21745]
I using Textfield
but I see a problem about text cursor 
when I typing Thai language to the TextField

please see in this video
https://www.youtube.com/watch?v=s8QbaDK0tvA

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by heart** [comment]
I'm tried on Chinese, Korea, Japanese keyboard it's working fine but Thai keyboard

## Steps to Reproduce
1. add Thai keybaord to iOS device
1. create new flutter project
1. add TextField widget
```
TextField(
              decoration: InputDecoration(labelText: 'Product description'),
              maxLines: 4,
              onChanged: (String t) {
                setState(() {
                  descriptionValue = t;
                });
              },
            ),
```
1. Run to physical iOS Device (i never try on iOS emulator)
1. type some 4-6 Thai characters by slowly and alternate with a space and type some 4-6 Thai characters again 
1. try to delete by pressing back space key several times.
1. bug will happen every time you type the vovel above and below the alphabet.
eg. สวัสดี กรุงเทพ bug will happen on ั and ี and ุ 
![thai language](https://image.ibb.co/bXKex9/Artboard_2.png)


## flutter doctor -v

[✓] Flutter (Channel master, v0.8.3-pre.31, on Mac OS X 10.13.6 17G65, locale en-TH)
    • Flutter version 0.8.3-pre.31 at /Users/heart/flutter
    • Framework revision d927c93310 (34 hours ago), 2018-09-12 08:29:29 +0200
    • Engine revision e65beb89da
    • Dart version 2.1.0-dev.4.0.flutter-ef72098353

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/heart/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Nexus 5X • 00e4144ec189a1ea • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by heart** [comment]
Hello if you can point me to the code I should be looking at I'm happy to help you find the solution for this bug

**Comment by worawutt** [comment]
Same issue for me both iOS and Android, the cursor jump to the first character when typing vowel character for Thai language.

And another relate issue about vowel, there is dot circle below or above vowel character draw on alphabet character, the issue occur only on iOS.

![screen shot 2561-10-25 at 18 46 46](https://user-images.githubusercontent.com/15317912/47498289-002e0280-d887-11e8-88b4-eecfd90f309a.png)

**Comment by heart** [comment]
Not only thai language

it happen to many language if it have above and below wovel

**Comment by worawutt** [comment]
@heart version 0.11.14-pre2 fixed cursor jump but cannot delete vowel character.

**Comment by heart** [comment]
@worawutt I decide to not use Flutter for my customer because of this bug

**Comment by worawutt** [comment]
version 1.1.2-pre.38 cursor jump when typing vowel character still be issue.

**Comment by zoechi** [comment]
Can you please check if https://github.com/flutter/flutter/pull/24797 fixed this for you (in `master` channel)?

**Comment by satjawat** [comment]
> Can you please check if #24797 fixed this for you (in `master` channel)?

I just check with that commit it not fix

**Comment by blackpigeon** [comment]
This is a serious issue for me. Because I am creating a Flutter App that must support Thai language.

**Comment by HelloCore** [comment]
@heart I think this should be fixed on master channel as PRs were merged.

**Comment by heart** [comment]
Thank you Flutter team

**Comment by htetwaiyan** [comment]
@heart How to fix it?

**Comment by htetwaiyan** [comment]
I have same Problem in  Myanmar language.

**Comment by heart** [comment]
Hi @htetwaiyan
I just use the master branch

I never try on Myanmar language before
But for Thai language it’s work good now

**Comment by htetwaiyan** [comment]
is this flutter stable channel you used?

**Comment by htetwaiyan** [comment]
How to fix this. In my app, even Thain Language is not work

**Comment by htetwaiyan** [comment]
@heart  How to fix this. In my app, even Thain Language is not work

**Comment by HelloCore** [comment]
@htetwaiyan It's work on master channel.
You can use command `flutter channel master` to switch the channel.

**Comment by htetwaiyan** [comment]
@HelloCore @heart It is not completely work. When I delete this above and  below letter, cursor jump to the before this letter

**Comment by htetwaiyan** [comment]
@heart 
[✓] Flutter (Channel master, v1.5.9-pre.177, on Mac OS X 10.14 18A391, locale
    en-MM)
    • Flutter version 1.5.9-pre.177 at
      /Users/htetwaiyan/htetwaiyan/flutter_dev/flutter
    • Framework revision 91aa36b7bd (19 hours ago), 2019-05-08 03:03:39 -0400
    • Engine revision 436a3c70a9
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 8143450941)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/htetwaiyan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Htet Wai Yan iPhone • d0b2188916572888cd0f8b5e2e5e0598a5f3291b • ios • iOS
      12.1.4

**Comment by htetwaiyan** [comment]
@heart  @HelloCore  Now flutter 1.5 is release, should i change to stable?

**Comment by htetwaiyan** [comment]
@heart @HelloCore Thanks you two. In stable 1.5 is ok. Every Language

**Comment by heart** [comment]
@htetwaiyan I'm good to hear that

**Comment by azonda** [comment]
Thai Language, Backspace broken in TextField

**Comment by GaryQian** [comment]
@azonda Do you mind opening a separate issue with details or linking an existing issue for this backspace bug? Thanks!

**Comment by draoinaja** [comment]
I have same issue at flutter web (stable 2.2.3) in Thai Language.
