### ISSUE TITLE
Request: More descriptive Exceptions

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#21748]
Errors like
`type 'List<dynamic>' is not a subtype of type 'String'`
Could be improved with the data that was attempted in order to help narrow down what data was incorrect. It points me to this line, 

```Dart
result.where((entry) => entry['mimetype_id'] == 1).map((entry) {
              return Item(
                  label: emailType[entry['data2']], value: entry['data1']);
            }).toList(growable: false)
```

but it would be helpful if it could say, "We attempted to add `myString: [my, list]` as a `String` in adding it to a `Map<int, String>`, but it failed because `'[my,list]'` is not a subtype of type `'String'`"

**Comment by zoechi** [comment]
Could you please re-file in https://github.com/dart-lang/sdk ?
