### ISSUE TITLE
Having adb in your path but not as part of a full-fledged android-sdk causes flutter start to fail saying it can't find any device to run on (despite flutter devices working).

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2174]
It turns out that flutter inferred my android-sdk from the path to my adb but I had moved my adb out of an android-sdk.  I hadn't set ANDROID_HOME so flutter thought incorrectly that:
```
<path-to-adb>/../.. == ANDROID_HOME
```

**Comment by apwilson** [comment]
Same issue as https://github.com/flutter/flutter/issues/2167

**Comment by eseidelGoogle** [comment]
Just another thing for `flutter doctor` to detect.

**Comment by devoncarew** [comment]
We have some validation logic for the android sdk; we either need to expose that in flutter doctor (instead of saying that the android adk looks ok), or use the validation logic when locating an sdk, so we don't return a bad one.

**Comment by devoncarew** [comment]
We've added some validation logic to the `doctor` command which should help diagnose these issues. Closing...

**Comment by slolife** [comment]
> $ flutter devices
> No devices detected.
> 
> If you expected your device to be detected, please run "flutter doctor" to diagnose
> potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.
> 
> 
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel beta)
> [√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
> [√] Android Studio (version 3.0)
> [√] VS Code (version 1.20.1)
> [!] Connected devices
>     ! No devices available
> 
> ! Doctor found issues in 1 category.

flutter doctor is not super helpful in helping me fix the devices not found. I have installed a number of devices thru Android Studio, but flutter and vscode do not see them.  I probably have a bad setup I need to fix, but not sure where to start.

**Comment by abhishekkrrao** [comment]
go to project structure and select any of them sdk platform 27,28 ....its ok

**Comment by abhishekkrrao** [comment]
[](http://abhishek.coolpage.biz/imagfile/sn.PNG)

**Comment by abhishekkrrao** [comment]
http://abhishek.coolpage.biz/imagfile/sn.PNG
