### ISSUE TITLE
I want to know the difference between using the new keyword and not using the new keyword

### ISSUE THREAD

**Issue by TaroXin** [flutter/flutter#21769]
In my app, no matter if I use or don't use the new keyword, the form of the program is the same. I want to know what's the difference between them.

For example
``` dart
return new Scaffold(
  appBar: new AppBar(
     title: new Text('Hello')
  )
)
```

**It is no different from the program representation below**

``` dart
return Scaffold(
  appBar: AppBar(
     title: Text('Hello')
  )
)
```
I want to know why, thank you very much !!

**Comment by TaroXin** [comment]
I wonder if it's because of `Dart2` syntax for omitting the `new` keyword.

**Comment by zoechi** [comment]
`new` became optional in Dart 2. `const` is optional as well inside a const context.

https://medium.com/@wmleler1/remember-that-dart-2-makes-the-new-and-const-keywords-optional-so-this-will-very-soon-a7cdf11db819

https://www.dartlang.org/dart-2

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
```
dartfmt -w --fix lib
```
removes redundant `new` and `const` from all dart files in `lib`

**Comment by komputerboy** [comment]
@zoechi 
where i can input that function?

**Comment by zoechi** [comment]
@komputerboy that's a command to run in the terminal window
