### ISSUE TITLE
Atom doesn't know that my Flutter project has a runnable app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2176]
I opened a new Flutter project, but plugin says "No runnable apps".

I have latest versions of Atom plugins, plus am using the hackathon branch and a freshly created Flutter project.

Expected: opening a Flutter project in Atom is enough for Atom to know that there is at least one runnable app.

![screen shot 2016-02-25 at 1 23 04 pm](https://cloud.githubusercontent.com/assets/5479/13334872/fa7dc668-dbc2-11e5-9389-fca5af07018d.png)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
If you open a file, does the pulldown update?

**Comment by sethladd** [comment]
Yes, I opened pubspec.lock and it found lib/main.dart. Could we discover lib/main.dart automatically?

**Comment by devoncarew** [comment]
Yup. We need to iterate a bit on the launch UX in any case.

**Comment by appsforartists** [comment]
If you close all the files, it forgets it has a runnable app.

**Comment by eseidelGoogle** [comment]
Is this the same as https://github.com/flutter/flutter/issues/2587 ?

**Comment by devoncarew** [comment]
This will get a little better from https://github.com/flutter/flutter/pull/2644, with some additional work remaining.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
