### ISSUE TITLE
support onShowPopupMenu  on PopupMenuButton

### ISSUE THREAD

**Issue by zhangjianlin77** [flutter/flutter#21773]
add onShowPopupMenu function on PopupMenuButton,  the  lifecycle of PopupMenu show have "onShow" event

**Comment by zoechi** [comment]
What is the use case?
A popup doesn't show automagically, it only shows when you call `showDialog` or similar, so you can notify yourself.

**Comment by zhangjianlin77** [comment]
> What is the use case?
> A popup doesn't show automagically, it only shows when you call `showDialog` or similar, so you can notify yourself.

https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter/lib/src/material/popup_menu.dart

the 'showButtonMenu' function is written in the _PopupMenuButtonState,  and I can't know when the PopupMenu is appeared

**Comment by zhangjianlin77** [comment]
> What is the use case?
> A popup doesn't show automagically, it only shows when you call `showDialog` or similar, so you can notify yourself.
I need to transform the button  from  '+'  to '×'  when the button is click

**Comment by zhangjianlin77** [comment]
Do you mean I call the showMenu to custom my menu?

**Comment by zoechi** [comment]
Your code somewhere calls `showDialog()`. This code can notify about the dialog showing.

**Comment by zhangjianlin77** [comment]
Thanks, Maybe i can use the showMenu, This issue is talk about menu,  the dialog cann't calculate the position where to locate
By the way, I see the PopupMenu is vertical only,  Is there common pop widget that can be use to custom my child.  Maybe I need to write by myself.  /(ㄒoㄒ)/~~

**Comment by egramond** [comment]
We also have a use-case that requires the onShowPopupMenu() function:  We want to be able to log the activity when the user taps the button to show the menu.

Currently this isn't possible to check because the showMenu call is burried inside _PopupMenuButtonState.showButtonMenu()

**Comment by popiosifcristian** [comment]
Any updates on this issue? I have a case where I need to change the UI if the popup menu is open.  Since it does provide onCanceled, it would be nice to have onShow functionality.

**Comment by eugenioamato** [comment]
... guys asking "use cases" ? like you cannot imagine one?
Why not just provide this missing feature instead of bullying developers

**Comment by fedotxxl** [comment]
Here is my use case: rebuild items just before it's opened

**Comment by fluttercorner** [comment]
[How to Create Popup in Flutter Popup Menu Example](https://fluttercorner.com/how-to-create-popup-in-flutter-with-example/)
