### ISSUE TITLE
Create a harness for measuring thread times and dropped frames in flutter

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2177]
@yjbanov has created `flutter drive` which can do functional integration tests.

This bug is about extending such to tell us about thread times and dropped frames.

Until we have something like this, we can't easily know (in an automated fashion) if we're fast yet.

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/flutter/pull/3058. Next steps: create some benchmarks, create dashboard showing benchmark results.
