### ISSUE TITLE
Adjust FlutterView to attach and detach a FlutterRenderer

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21784]
FlutterView previously did not allow for a given Flutter engine (AKA FlutterNativeView) to be attached and detached at will.  It was attached in the constructor and that was it.

This ticket is to support arbitrary FlutterEngine attachment to a given FlutterView.

**Comment by xster** [comment]
This can be closed now right?

**Comment by matthew-carroll** [comment]
Yep!
