### ISSUE TITLE
Animation chaining

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#218]
<a href="https://github.com/HansMuller"><img src="https://avatars.githubusercontent.com/u/1377460?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HansMuller](https://github.com/HansMuller)**
_Wednesday Oct 21, 2015 at 23:10 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1727_

---

 I'd like a way to chain performances together.

Sometimes animations are too complex to easily define in terms of one performance.  It would be nice if one could chain performances together. For example: I'd like to be able to say that performance B should begin when performance A passes t=0.5 or when performance A starts or ends.

**Comment by abarth** [comment]
There's a bunch of variants:
 - [ ] Sequential composition
 - [ ] Parallel composition

**Comment by Hixie** [comment]
We have this, you can now write a method with "async" and "await" that runs different controllers in sequence.
