### ISSUE TITLE
Transparent Flutter background

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21808]
Transparent Flutter background

**Comment by matthew-carroll** [comment]
Was done here: https://github.com/flutter/engine/pull/6172

Still need to add splash color support

**Comment by matthew-carroll** [comment]
FYI @dnfield

**Comment by dnfield** [comment]
Possible gpu related issue?

**Comment by dinozero** [comment]
> Possible gpu related issue?

I don't know, I will try to test with iphone 6, 7.

**Comment by dnfield** [comment]
Can you share the code you're using to present the FlutterViewController?

**Comment by dinozero** [comment]
> Can you share the code you're using to present the FlutterViewController?
I have a main view controller as image.
And I override viewDidLoad of that main view controller.  I add View of FlutterViewController into Map View.
On simulator, It is perfect. 

`override func viewDidLoad() {
        super.viewDidLoad()
        
        mapView.isExclusiveTouch = false
        mapView.touchDelegate = self
        initFlutterViewController()` 

`func initFlutterViewController() {
        flutterViewController = storyboard!.instantiateViewController(withIdentifier: "flutterview") as? FlutterViewController
        addChildViewController(flutterViewController)
        flutterViewController.view.translatesAutoresizingMaskIntoConstraints = false
        mapView.addSubview(flutterViewController.view)
        
        let horConstraint = NSLayoutConstraint(item: flutterViewController.view, attribute: .centerX, relatedBy: .equal,
                                               toItem: mapView, attribute: .centerX,
                                               multiplier: 1.0, constant: 0.0)
        let verConstraint = NSLayoutConstraint(item: flutterViewController.view, attribute: .centerY, relatedBy: .equal,
                                               toItem: mapView, attribute: .centerY,
                                               multiplier: 1.0, constant: 0.0)
        let widConstraint = NSLayoutConstraint(item: flutterViewController.view, attribute: .width, relatedBy: .equal,
                                               toItem: mapView, attribute: .width,
                                               multiplier: 1.0, constant: 0.0)
        let heiConstraint = NSLayoutConstraint(item: flutterViewController.view, attribute: .height, relatedBy: .equal,
                                               toItem: mapView, attribute: .height,
                                               multiplier: 1.0, constant: 0.0)
        
        mapView.addConstraints([horConstraint, verConstraint, widConstraint, heiConstraint])
        
        flutterViewController?.view.isOpaque = false
        flutterViewController?.view.isExclusiveTouch = false
        flutterViewController?.view.backgroundColor = UIColor.clear
        flutterViewController?.view.layer.backgroundColor = UIColor.clear.cgColor
        flutterViewController?.view.subviews.forEach{
            $0.isOpaque = false
            $0.backgroundColor = UIColor.clear
            $0.layer.backgroundColor = UIColor.clear.cgColor
        }
        
        flutterViewController?.splashScreenView.isOpaque = false
        flutterViewController?.splashScreenView.backgroundColor = UIColor.clear
        flutterViewController?.splashScreenView.layer.backgroundColor = UIColor.clear.cgColor
        GeneratedPluginRegistrant.register(with: flutterViewController!)
    }`

// Main View Controller.
![screen shot 2018-09-28 at 13 22 02](https://user-images.githubusercontent.com/29195673/46191428-b4d51280-c321-11e8-98cb-7d230323aa0e.png)

//Simulator iOS (iphone 5s 10.0)
![42677886_580790799002683_5628308621386317824_n](https://user-images.githubusercontent.com/29195673/46191590-50668300-c322-11e8-9834-1830d109416d.png)

**Comment by dinozero** [comment]
> Possible gpu related issue?
I had same this problem with iphone 6.

**Comment by dnfield** [comment]
I can reproduce this, continuing to look into it.

**Comment by dnfield** [comment]
Culprit is here: https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterView.mm#L48

This is done per Apple recommendation for performance reasons.  It may be nice to make it user configurable - I don't think there's a good way that even an add to app user could change this today.  Looking into that.

**Comment by dnfield** [comment]
I'm proposing adding a property to `FlutterViewController` called `viewIsOpaque` to address this in the linked PR.

**Comment by dinozero** [comment]
> 
> 
> I'm proposing adding a property to `FlutterViewController` called `viewIsOpaque` to address this in the linked PR.
> 
> The reason your existing code doesn't work is that we repeatedly set this property to `YES` in `layoutSubviews`, which would override what you're trying to set in your code.

Oh, I understand the reason, thanks you. If I can adjust it then better.

**Comment by searchy2** [comment]
The key for me in getting a transparent FlutterView to work and get rid of the black background is adding the following line to the ViewController.

`flutterViewController.modalPresentationStyle = UIModalPresentationStyle.overCurrentContext`

Hope this helps!

**Comment by Jichao** [comment]
Thank you @searchy2 save my day.
