### ISSUE TITLE
After upgrading to Flutter 0.7.3 channel beta the WidgetsBindingObserver is not working?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#21809]
After upgrading to Flutter 0.7.3 channel beta (Dart 2.1.0-dev.1.0.flutter-ccb16f7282) the WidgetsBindingObserver is not working.

Any idea how to make it to run? I use android emulator and after login **wait over 90 second** and nothings happens. Need urgent help??? 

It worked before, after login if AppLifecycleState paused, inactive or suspended more than 60 second it goes back to main page so user must login again... Any help please

```
// Statefull HomePage
class PersonalLoginPage extends StatefulWidget {
  const PersonalLoginPage({ Key key }) : super(key: key);
  @override
  _PersonalLoginPageState createState() => new _PersonalLoginPageState();
}
class _PersonalLoginPageState extends State<PersonalLoginPage> with WidgetsBindingObserver {
  AppLifecycleState _appLifecycleState;
  bool _appStatePause;
  
  // TODO: initState function
  @override
  void initState() {
    print("initState Starting Now .......................");
    super.initState();
    authenticateUser();
	WidgetsBinding.instance.addObserver(this);
  }
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    Timer _timer;
    setState(() {
      _appLifecycleState = state;
      if (_appLifecycleState == AppLifecycleState.paused ||
          _appLifecycleState == AppLifecycleState.inactive ||
          _appLifecycleState == AppLifecycleState.suspending) {
        _appStatePause = true;
        print("New Timer Starting Now .......................");
        _timer = Timer.periodic(Duration(seconds: 60), _callback);
      } else {
        _appStatePause = false;
      }
    });
  }
  void _callback(_timer) {
    if (_appStatePause == true) {
      print("Timer Finished without cancel...................");
      setState(() {
        Navigator.push(
          context,
          SlideRightRoute(widget: MyApp()),
        );
      });
    } else {
      _timer.cancel();
      print("Timer cancel now................................");
    }
  }
  // TODO: authenticateUser function
  Future authenticateUser() async {
    ……
	……
	……
  }
  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
  // TODO: main build Widget
  @override
  Widget build(BuildContext context) {
    return Scaffold(
         body: new Center(
			child: new Text(“Hello World”)
		)
    );
  }
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by NTMS2017** [comment]
Thanks Günter, here it is;

Niyazis-MBP:capital niyazitoros$ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale tr-CY)
    • Flutter version 0.7.3 at /Users/niyazitoros/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
Niyazis-MBP:capital niyazitoros$

**Comment by NTMS2017** [comment]
problem is, if I put print statement on didChangeAppLifecycleState before Timer decalarion  console output is not showing any print statement. After upgrade, I guess its never run the WidgetsBinding.instance.addObserver(this); line... 

Kind Thanks

**Comment by zinwalin** [comment]
same issue.

**Comment by NTMS2017** [comment]
any news about the issue?

**Comment by wanyt** [comment]
I met the same situation. 

[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A384a, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
[✓] VS Code (version 1.28.1)
[✓] Connected devices (1 available)

**Comment by zoechi** [comment]
This issue doesn't have a single upvote. "Me too" or "any news" comments won't increase priority.

**Comment by NTMS2017** [comment]
I achieve using InheritedWidget instead of using WidgetsBindingObserver, so I think we can close this.

https://github.com/flutter/flutter/issues/24673
