### ISSUE TITLE
Let iOS keyboard be dismissed

### ISSUE THREAD

**Issue by qwilbird** [flutter/flutter#21814]
Hi,

when using a listview in Flutter, we need to be able to dismiss the keyboard.
iOS has the **keyboardDismissMode** option for scrollviews with the enum **UIScrollViewKeyboardDismissModeInteractive**

Could this be implemented?

**Comment by I-am-original** [comment]
@zoechi  Same behavior is on Android for now. Keyboard not hiding while scrolling list view

**Comment by fvisticot** [comment]
Facebook and iMessage app are supporting this feature to dismiss the keyboard.
Can you please add this property in the ListView implementation or provide a better solution ?

**Comment by mleonhard** [comment]
This is the behavior that iOS users expect.  It is found in iMessage, FB Messenger, Instagram, and all popular iOS apps.  I need my app to work the same way.  This is very important to me.  Please support it as soon as possible.

[`UIScrollView.KeyboardDismissMode.interactive`](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode/interactive)
"The keyboard follows the dragging touch offscreen, and can be pulled upward again to cancel the dismiss."

In the meantime, I will make-do with a class that implements the less-popular mode:
[`UIScrollView.KeyboardDismissMode.onDrag`](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode/ondrag)
"The keyboard is dismissed when a drag begins."

To help others facing this problem, I'm providing my code (under the same license as Flutter):
```
import 'dart:io' show Platform;
import 'package:flutter/widgets.dart'
    show
        BuildContext,
        FocusNode,
        FocusScope,
        NotificationListener,
        ScrollNotification,
        State,
        StatefulWidget,
        UserScrollNotification,
        Widget;

class DismissKeyboardOnDrag extends StatefulWidget {
  final bool enabled;
  final Widget child;

  /// DismissKeyboardOnDrag dismisses the keyboard when the user finishes
  /// scrolling the page.  [enabled] defaults to true on iOS and false on Android.
  ///
  /// Android users habitually use the 'Back' button to dismiss the keyboard.  So
  /// by default this class does nothing on Android builds.
  ///
  /// iOS users are accustomed to swiping the keyboard down.  This is behavior
  /// comes from using [UIScrollView.KeyboardDismissMode.interactive](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode/interactive).
  /// There is a [feature request to add that mode to Flutter](https://github.com/flutter/flutter/issues/21814).
  ///
  /// Until that feature is implemented, we can make-do with dismissing the
  /// keyboard when the user scrolls the page.  This is very similar to the
  /// behavior when using [UIScrollView.KeyboardDismissMode.onDrag](https://developer.apple.com/documentation/uikit/uiscrollview/keyboarddismissmode/ondrag).
  DismissKeyboardOnDrag({bool enabled, this.child})
      : this.enabled = enabled == null ? Platform.isIOS : enabled;

  @override
  State createState() => new _DismissKeyboardOnDragState();
}

class _DismissKeyboardOnDragState extends State<DismissKeyboardOnDrag> {
  final FocusNode _focusNode = new FocusNode();

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  bool _onScrollNotification(ScrollNotification notification) {
    if (notification is UserScrollNotification) {
      FocusScope.of(context).requestFocus(_focusNode);
    }
    return false;
  }

  @override
  Widget build(BuildContext context) => this.widget.enabled
      ? NotificationListener<ScrollNotification>(
          onNotification: _onScrollNotification, child: this.widget.child)
      : this.widget.child;
}
```

**Comment by mcrovero** [comment]
I've created a plugin to implement this feature, it is still in development but if you'd like to check it out here is the link: [Flutter Interactive Keyboard](https://github.com/mcrovero/flutter_interactive_keyboard)

**Comment by mleonhard** [comment]
Hi Google Flutter Product Management Team,
Keyboard behavior is crucial for apps to feel normal to users.  The lack of this key feature for iOS harms Flutter's long-term growth.  Who can take a platform seriously when it can't even handle the keyboard properly?  I and many other app developers target iOS first.  Flutter's incomplete Cupertino library requires lots of wasted effort just to make an iOS app function normally.  Flutter's userbase will grow faster when iOS functionality is at parity with Android.  Please reallocate headcount accordingly to eliminate the iOS backlog.

**Comment by gaaclarke** [comment]
Implementation Notes:
- #52068 adds the ability to dismiss the keyboard when the scroll area is dragged
- [flutter_interactive_keyboard](https://github.com/mcrovero/flutter_interactive_keyboard) performs the following:
  1) detects drags over the keyboard from flutter
  1) does a screen capture of the portion of the screen with the keyboard
  1) dismisses the keyboard without animations
  1) adds the screen capture view over the FlutterView which gets translated as a result of the drag messages from flutter
  1) (detects if the user flings the keyboard)
- If we wanted to integrate similar logic into the engine we'd probably have to edit the [FlutterTextInputPlugin](https://github.com/flutter/engine/blob/8b6119ec8367bbe3de52fd5f40737219be8d5b8b/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L690:L690).

**Comment by gaaclarke** [comment]
I had a chat offline with @xster.  His opinion is that while UIScrollView.KeyboardDismissMode.interactive only exists in iOS and has no Android analog, since it is key functionality it should have a place in the framework and we shouldn't rely on a plugin.  If you use it on Android, it can just behave differently.

**Comment by xster** [comment]
The keyboard now dismisses on Android and iOS when you start scrolling. 

You can also manually dismiss the keyboard by calling `unfocus()` on FocusScopes from Dart. 

Leaving this bug open to implement the 'fancier' iOS animation of letting the keyboard dismiss with the finger drag gesture.

**Comment by gabdsg** [comment]
Any update on this?

**Comment by xster** [comment]
This bug is confusing since it's already done. Closing this one and branching off https://github.com/flutter/flutter/issues/57609 for synchronized keyboard dismissal during scroll.
