### ISSUE TITLE
Invalid kernel binary format version

### ISSUE THREAD

**Issue by diegogalico** [flutter/flutter#21810]
Hi, after upgrading flutter version I am getting an ` Invalid kernel binary format version` error. Basically the app get stuck on the launch screen (just in iOS). The application is a pure flutter app.  I will appreciate any help.

Error:
```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                      10.1s
Starting Xcode build...
Xcode build done.                                           12.5s
[VERBOSE-2:shell.cc(181)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
        [1.1 A17CCD8F-BD62-4910-8166-A907FC1F4DAF 192.168.1.38.53082<->216.58.211.202:443]
        Connected Path: satisfied (Path is satisfied), interface: en0
        Duration: 0.433s, DNS @0.014s took 0.012s, TCP @0.034s took 0.027s, TLS took 0.286s
        bytes in/out: 3441/1057, packets in/out: 9/10, rtt: 0.027s, retransmitted packets: 0, out-of-order packets: 0
Syncing files to device iPhone X...                          7.5s
```
```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.4 17E199, locale en-ES)
    • Flutter version 0.7.3 at /Users/.../Dev/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/diego.galico/Library/Android/sdk
    • Android NDK at /Users/diego.galico/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] Connected devices (1 available)
    • SM G950F • 988a1b374c4f4b424c • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by CLARKYJ** [comment]
@zoechi i'm getting the same problem, is this issue done?

**Comment by zoechi** [comment]
@CLARKYJ no, it would be closed if it were done.
Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.

**Comment by amisare** [comment]
The building engine version  may not same  as FLUTTER_ROOT version

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by htaryuswe** [comment]
> 
> 
> @CLARKYJ no, it would be closed if it were done.
> Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.

**Comment by clearloop** [comment]
> @CLARKYJ no, it would be closed if it were done.
> Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.

It works! thanks!

**Comment by guccisekspir** [comment]
If you changed your flutter channel try 

> flutter upgrade

. It works for me.

**Comment by hoonblizz** [comment]
> @CLARKYJ no, it would be closed if it were done.
> Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.


Works like a charm! 👍

**Comment by lutang123** [comment]
> @CLARKYJ no, it would be closed if it were done.
> Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.

Hi, Can you explain exactly which bin/cache directory? I followed your step and deleted the "cache" file in "flutter/bin/cache", and then I got a whole bunch of new error, the whole Flutter seems crashed, can't run any App. Do you have more explanation on how to solve the problem? Thank you! 

And also this happened after running flutter upgrade, so should we not upgrade? what can we do to prevent this error?

**Comment by amitsingh6391** [comment]
Find your file where u install flutter and go to bin/cache directery and delete it then run flutter clean /flutter doctor
Restart your PC and now everything is working for me

**Comment by idjd2018** [comment]
> @CLARKYJ no, it would be closed if it were done.
> Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.
It works for me! But after delete cache，you have to run flutter pub get and pod install again.

**Comment by hassanasif0423** [comment]
@zoechi  Hi Sir,
I will face this error in running the app Can't load Kernel binary: Invalid kernel binary format version.
if anyone resolved this issue kindly help me.

**Comment by itwondersteam** [comment]
@hassanasif0423 can try following, it works for me
```
rm -rf <flutter-installation-directory>/flutter/bin/cache
flutter doctor
```

**Comment by Saransh-cpp** [comment]
> @CLARKYJ no, it would be closed if it were done.
> Can you please try deleting the `bin/cache` directory in your Flutter installation directory, then run `flutter doctor` and try again.

Thank you so much, this works
