### ISSUE TITLE
Old template

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#21816]
The templates used are very old. Using old libraries like gradle 4.4 and gradle build 3.1.2.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Are you referring to what is created by `flutter create foo`?

**Comment by dovahkiin98** [comment]
Yes, sadly Android Studio 3.3 alpha 10 still doesn't support flutter, so I had to use `flutter create`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by dovahkiin98** [comment]
> [√] Flutter (Channel dev, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
>     • Flutter version 0.8.2 at C:\Programming\flutter
>     • Framework revision 5ab9e70727 (6 days ago), 2018-09-07 12:33:05 -0700
>     • Engine revision 58a1894a1c
>     • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
> 
> [!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
>     • Android SDK at C:\Programming\Android\Android_SDK
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.2
>     • Java binary at: C:\Programming\Android\Android Studio Canary 1\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [√] Android Studio (version 3.3)
>     • Android Studio at C:\Programming\Android\Android Studio Canary 1
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [!] IntelliJ IDEA Community Edition (version 2018.2)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.io/intellij-setup/#installing-the-plugins
> 
> [√] VS Code, 64-bit edition (version 1.24.0)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.16.0
> 
> [√] Connected devices (1 available)
>     • !!! • 192.168.1.100:5555 • android-arm64 • Android 8.0.0 (API 26)
> 
> ! Doctor found issues in 2 categories.

Probably not detecting Flutter but it is install on android studio cause it's 3.3 Canary.

**Comment by zoechi** [comment]
I think this issue is stale.
Please let us know if you disagree to have the issue reopened.
