### ISSUE TITLE
How to decrease the size of app.framework on iOS?

### ISSUE THREAD

**Issue by youyou76** [flutter/flutter#21813]
Hi,
As we add more and more dart code to our flutter application, we found that the size of app.framework increased greatly(about 5MB for each architecture). We expect there could be some tools or methods to help us determine the most influential factor of the size.

We generate app.framework by using command :
```terminal
flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=lib/main.dart --release --ios-arch=armv7,arm64 --extra-gen-snapshot-options=--print-snapshot-sizes
```

We tested a case that adding a simple class to the application and use it in some place, before we added the class:
```
[+14501 ms] VMIsolate(CodeSize): 4732
[        ] Isolate(CodeSize): 2482670
[        ] ReadOnlyData(CodeSize): 2609504
[        ] Instructions(CodeSize): 6835712
[        ] Total(CodeSize): 11932618
```
and after we added the class:
```
[+14446 ms] VMIsolate(CodeSize): 4732
[        ] Isolate(CodeSize): 2482791
[        ] ReadOnlyData(CodeSize): 2609728
[        ] Instructions(CodeSize): 6835840
[        ] Total(CodeSize): 11933091
```

Code of the class:
```dart
class RentHeadTest extends StatefulWidget {
  final VisibilityChange _visibilityChange = new VisibilityChange();

  @override
  State<StatefulWidget> createState() => RentHeadCommonState();
}
```

flutter doctor -v
```terminal
[✓] Flutter (Channel unknown, v0.8.2, on Mac OS X 10.14 18A293u, locale zh-Hans-CN)
    • Flutter version 0.8.2 at /Users/kangkai/fwn_idlefish/flutter
    • Framework revision 5ab9e70727 (6 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/kangkai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode9.3.1.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```

**Comment by kangwang1988** [comment]
@eseidelGoogle @mraleph 
The app.framework's size increases rapidly after we refactor another business in our app.
Why?
It could be a problem if we want refactor more original existed native logic into flutter if the package size issue lasts.

**Comment by eseidelGoogle** [comment]
Thanks for the report.  A couple questions:
1.  You only have one app.framework, correct (not multiple)?
2.  Can you provide a rough estimate of the number of files or LOC in your app and the resulting rough-estimate of the size of app.framework (to sanity check that we aren't facing an egregious compile-size bug)?

@mraleph @a-siva  Are there code-side profiling tools to point @kangwang1988 at?

**Comment by eseidelGoogle** [comment]
FYI @goderbauer who is working on reducing our compile sizes across all platforms.

**Comment by mraleph** [comment]
@kangwang1988 @youyou76 can you specify which part of the snapshot grew by 5mb? was it `Instructions` or `ReadOnlyData`?

if you are looking  specifically at the instructions then you can use `--print_instructions_sizes_to` - you pass this option to the `gen_snapshot` and it would write out a JSON file that contains size for each instruction object written into the snapshot. you can then visualize this data using [this script](https://github.com/dart-lang/sdk/blob/master/pkg/vm/bin/run_binary_size_analysis.dart) (you need to run it from the Dart SDK checkout).

**Comment by youyou76** [comment]
@mraleph @eseidelGoogle OK, I will compare the size of the old（24MB） and new（34MB） framework by the method you suggested to determine which part impacts size most, thank you!

**Comment by youyou76** [comment]
Hi, @mraleph @eseidelGoogle 
We now get the result of comparison:
【before】
VMIsolate(CodeSize): 4664
Isolate(CodeSize): 1753133
ReadOnlyData(CodeSize): 2600528
Instructions(CodeSize): 5915552
Total(CodeSize): 10273877
Building App.framework for arm64...

【now】
VMIsolate(CodeSize): 4664
Isolate(CodeSize): 2568696
ReadOnlyData(CodeSize): 3719408
Instructions(CodeSize):8391424 
Total(CodeSize): 14684192
Building App.framework for arm64...

The code size of Isolate increased about 800K, ReadOnlyData increased about 1.1MB, and Instructions increased about 2.4MB. 

By using --print_instructions_sizes_to option, we get following comparison of instructions code size:
【before】
![image](https://user-images.githubusercontent.com/8768091/45547069-142b2100-b852-11e8-9e1b-da93a2c0c018.png)

【after】
![image](https://user-images.githubusercontent.com/8768091/45547096-2a38e180-b852-11e8-8b41-6d9f2ffaad65.png)

That is awesome and we are able to make more in-depth analysis now.  However, we have no idea about how to analyze the code size of Isolate and ReadOnlyData, is there any way to approach that?

**Comment by goderbauer** [comment]
One thing that will help with the size of app.framework is stripping debug symbols. I am working on that as part of https://github.com/flutter/flutter/issues/18693#issuecomment-421308268.

**Comment by mraleph** [comment]
One thing I observe here - is that we still have dart:vmservice lurking around - this should be gone now (/cc @sjindel-google could you verify what is still pulling that in even after we excluded it?)

> However, we have no idea about how to analyze the code size of Isolate and ReadOnlyData, is there any way to approach that?

I was planning to implement similar JSON output for `ReadOnly`/`Isolate` components - but I did not get to it. That should not be _that_ hard - so I will look into that while on my flights next week.

**Comment by youyou76** [comment]
@mraleph 
sorry, the data I supplied is exported by using flutter v0.5.6, so I think it's OK to have dart:vmservice.

**Comment by hamiao123** [comment]
Hi，@mraleph @eseidelGoogle 

We notice that Json parsing and conversion adds big size in our flutter application, the original size:

    Building AOT snapshot in release mode (android-arm-release)...      
    VMIsolate(CodeSize): 4660
    Isolate(CodeSize): 1189322
    ReadOnlyData(CodeSize): 1295080
    Instructions(CodeSize): 3922880
    Total(CodeSize): 6411942
    Built to build/aot/.


after add a series of json parses，It's increased by 10068 bytes

    void testSize(Map<dynamic, dynamic> json) {
        String name1 = json["name1"] as String;
        String name2 = json["name2"] as String;
        String name3 = json["name3"] as String;
        String name4 = json["name4"] as String;
        String name5 = json["name5"] as String;
        String name6 = json["name6"] as String;
        String name7 = json["name7"] as String;
        String name8 = json["name8"] as String;
        String name9 = json["name9"] as String;
        String name10 = json["name10"] as String;
        String name11 = json["name11"] as String;
        String name12 = json["name12"] as String;
        String name13 = json["name13"] as String;
        String name14 = json["name14"] as String;
        String name15 = json["name15"] as String;
        String name16 = json["name16"] as String;
        String name17 = json["name17"] as String;
        String name18 = json["name18"] as String;
        String name19 = json["name19"] as String;
        String name20 = json["name20"] as String;
        String name21 = json["name21"] as String;
        String name22 = json["name22"] as String;
        String name23 = json["name23"] as String;
        String name24 = json["name24"] as String;
        String name25 = json["name25"] as String;
        String name26 = json["name26"] as String;
        String name27 = json["name27"] as String;
        String name28 = json["name28"] as String;
        String name29 = json["name29"] as String;
        String name30 = json["name30"] as String;
      }

    Building AOT snapshot in release mode (android-arm-release)...      
    VMIsolate(CodeSize): 4660
    Isolate(CodeSize): 1190054
    ReadOnlyData(CodeSize): 1297248
    Instructions(CodeSize): 3930048
    Total(CodeSize): 6422010
    Built to build/aot/.

after define independent parse method,the size was reduced by 6403 bytes.

    String _getString(Map<dynamic, dynamic> json, String name) {
      return json[name] as String;
    }
    
    void testSize(Map<dynamic, dynamic> json) {
      String name1 = getString(json, "name1");
      String name2 = getString(json, "name2");
      String name3 = getString(json, "name3");
      String name4 = getString(json, "name4");
      String name5 = getString(json, "name5");
      String name6 = getString(json, "name6");
      String name7 = getString(json, "name7");
      String name8 = getString(json, "name8");
      String name9 = getString(json, "name9");
      String name10 = getString(json, "name10");
      String name11 = getString(json, "name11");
      String name12 = getString(json, "name12");
      String name13 = getString(json, "name13");
      String name14 = getString(json, "name14");
      String name15 = getString(json, "name15");
      String name16 = getString(json, "name16");
      String name17 = getString(json, "name17");
      String name18 = getString(json, "name18");
      String name19 = getString(json, "name19");
      String name20 = getString(json, "name20");
      String name21 = getString(json, "name21");
      String name22 = getString(json, "name22");
      String name23 = getString(json, "name23");
      String name24 = getString(json, "name24");
      String name25 = getString(json, "name25");
      String name26 = getString(json, "name26");
      String name27 = getString(json, "name27");
      String name28 = getString(json, "name28");
      String name29 = getString(json, "name29");
      String name30 = getString(json, "name30");
    }

    Building AOT snapshot in release mode (android-arm-release)...      
    VMIsolate(CodeSize): 4660
    Isolate(CodeSize): 1189819
    ReadOnlyData(CodeSize): 1296264
    Instructions(CodeSize): 3924864
    Total(CodeSize): 6415607
    Built to build/aot/.

Why? Whether my optimization method will have a performance impact？Are there other ways to optimize？

**Comment by mraleph** [comment]
@kangwang1988  `x as String` is compiled down to some big code. if you do an implicit cast:

```dart
    String name1 = json["name1"] /* as String */;
```

that should yield smaller AOT code.

Of course the result would be even smaller if you share the code across all the call-sites like you did with a helper method.

> Whether my optimization method will have a performance impact？

I would say that impact should not be very large - if size is important to you then you should definitely use helpers like that.

**Comment by kangwang1988** [comment]
@mraleph 
Is there any optimization which can be compiled when generating aot code?
Like the optimization level and flags in clang.
As to the call-sites, do you think it should be done by the developers or the compiler might optimize it later?

**Comment by Hixie** [comment]
@youyou76 Can you elaborate on what action you would like us to take specifically to resolve this bug? We are definitely continuing to work on making both our overall footprint smaller and on making specific features in Dart compile more efficiently. If you have a specific concern that you would like us to focus on we can definitely look at doing that too. We're not sure at this point what exactly it is we should do for you to consider this bug resolved, though.

**Comment by goderbauer** [comment]
FYI: I just submitted https://github.com/flutter/flutter/pull/22245, which reduces the size of `App.framework` by about 22% (uncompressed) in my tests on the hello_world and flutter gallery app simply by stripping the debug symbols. A dSYM file with the debug information is created under `build/aot/App.dSYM` in case they're needed.

**Comment by youyou76** [comment]
> @youyou76 Can you elaborate on what action you would like us to take specifically to resolve this bug? We are definitely continuing to work on making both our overall footprint smaller and on making specific features in Dart compile more efficiently. If you have a specific concern that you would like us to focus on we can definitely look at doing that too. We're not sure at this point what exactly it is we should do for you to consider this bug resolved, though.

I think we need tools to analyze code size of Isolate and ReadOnlyData, just like Instructions.

**Comment by mraleph** [comment]
I have filed https://github.com/dart-lang/sdk/issues/34632 to track this work. @sjindel-google would be looking into that.

We also discussed if we can implement outlining pass in the AOT compiler - similar to LLVM's outlining pass - and we will looking into that.

@youyou76 can you share with us more details about the size breakdown of your app? e.g. I saw in the previous screenshots that you have .5MB in the `proto` section - is that some sort of protobuf serialization/deserialization code? Have you tried drilling down to see where the size comes from?

**Comment by hamiao123** [comment]
@mraleph Can you tell me the specific meaning represented by VMIsolate/Isolate/ReadOnlyData/Instructions ?

**Comment by mraleph** [comment]
- `Instructions` are the generated code.
- `ReadOnlyData` are generated code metadata (`PcDescriptor`, `StackMap`, `CodeSourceMap`) and strings
- Isolate/VMIsolate are the rest of objects. (e.g. constants you have written in your code and any other VM specific metadata like `Class`, `Function` etc objects).

**Comment by hamiao123** [comment]
@mraleph thank you! 
why  `x as String`  compiled down to some big code? What is the internal treatment？

**Comment by mraleph** [comment]
@hamiao123 it used to be compiled to a range check and inlined throw, essentially this:

```
if (x.classId < A && x.classId > B) throw "x is not subtype of String";
```

We have removed this treatment upstream in https://dart-review.googlesource.com/c/78748 now it should compile down to a much smaller code.

**Comment by Hixie** [comment]
Status: We are awaiting progress on https://github.com/dart-lang/sdk/issues/34632 to be able to make more useful progress here.

**Comment by Hixie** [comment]
@youyou76 Is this still an issue for you?

We're still waiting for the tool to be available to help you see where the space is actually going.

**Comment by youyou76** [comment]
> @youyou76 Is this still an issue for you?
> 
> We're still waiting for the tool to be available to help you see where the space is actually going.

Yes, and recently we added more dart code to our project which caused about 1MB the App.framework to increase by about 1MB. 
We'd like to know how the development of the tool is going.

**Comment by sjindel-google** [comment]
The tool has been complete since early December. The docs are in `runtime/docs/snapshot_profiling.md` in the Dart repo.

**Comment by mraleph** [comment]
@youyou76 could you try the tool and let us know what you think? if exploring snapshot in Chrome DevTools does not give you enough information about your app, then we could look into other ways to surface the data. Now that we can actually dump it - this should be just a question of post processing the profile.

**Comment by youyou76** [comment]
> @youyou76 could you try the tool and let us know what you think? if exploring snapshot in Chrome DevTools does not give you enough information about your app, then we could look into other ways to surface the data. Now that we can actually dump it - this should be just a question of post processing the profile.

OK, we'll try, and we'll be very appreciate if  the tool could output the difference between  two profiles.

**Comment by xster** [comment]
@mraleph also some context in https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fwww.jianshu.com%2Fp%2F1c2724a7f810 for consideration

**Comment by mraleph** [comment]
@youyou76 @kangwang1988 do not hesitate to reach to us directly if you need some specific help understanding what you see in the snapshot or if information provided there does not help to understand size of your application.

**Comment by kangwang1988** [comment]
> @youyou76 @kangwang1988 do not hesitate to reach to us directly if you need some specific help understanding what you see in the snapshot or if information provided there does not help to understand size of your application.

OK. Thanks

**Comment by Hixie** [comment]
I'm going to close the issue since there's nothing actionable for us here any more; please don't hesitate to open a new bug if there's more you would like us to do!

**Comment by hasen6** [comment]
It looks like this never got fixed. All my apps so far are 6-8mb in Android and 30mb each in iOS. All the apps are pretty much basic templates since they use zero images. I even removed the Cupertino icons package so should be very small indeed.

It seems to be about the size everyone is getting on iOS, based on my experience, the OP here and the author of this: https://blog.codemagic.io/flutter-vs-swift/

The question is - why.....Anyway, any idea when this is going to be addressed?

**Comment by wangying3426** [comment]
> Instructions(CodeSize): 5915552

By the way，anyone know why "Instructions(CodeSize): 5915552" is different from the binary size shown by html file?
