### ISSUE TITLE
Firebase Realtime Database setPersistenceEnabled value set to "true" by default.

### ISSUE THREAD

**Issue by ram231** [flutter/flutter#21811]
Firestore has offline access by default  which is the same as `FirebaseDatabase.setPersistenceEnabled(true)` in Firebase Realtime Database. may I know why it's not set to default?

**Comment by zoechi** [comment]
https://firebase.google.com/docs/database/android/offline-capabilities

![image](https://user-images.githubusercontent.com/405837/45489546-cbe20500-b764-11e8-9297-ed1623503ada.png)

It's the same behavior as in the native platform.

**Comment by ram231** [comment]
Not the answer I wanted but, nevermind. I mean there's a way that this function is  set to true by default.

**Comment by zoechi** [comment]
Why is that an issue?
Just set it to true when you initialize the Firebase connectiin.
It's just one line of code.
