### ISSUE TITLE
date_picker_test.dart appears hung on the bots

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2181]
https://build.chromium.org/p/client.flutter/builders/Linux/builds/227/steps/steps/logs/stdio

@HansMuller

**Comment by eseidelGoogle** [comment]
Two separate builds:
https://build.chromium.org/p/client.flutter/builders/Linux/builds/233/steps/steps/logs/stdio

@Hixie

**Comment by eseidelGoogle** [comment]
Please disable this test until #2182 is resolved or this test can be made not to timeout occasionally.  Strange that it ran fine for a month.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/test/widget/date_picker_test.dart is the file in question.

**Comment by abarth** [comment]
Looks like we've had 24 clean builds: https://build.chromium.org/p/client.flutter/builders/Linux?numbuilds=25 .  I'm going to close this issue.
