### ISSUE TITLE
CupertinoSliverRefreshControll not work on Android

### ISSUE THREAD

**Issue by AndreyTCR** [flutter/flutter#21820]
## Steps to Reproduce

CupertinoSliverRefreshControll not work on Android. On iOS works perfectly
```dart
new CustomScrollView(
          slivers: <Widget>[
            new  CupertinoSliverRefreshControl(
              onRefresh: ,
            ),
            new SliverSafeArea(
              top: true, 
              sliver: new SliverPadding(
                sliver: new SliverList(
                  delegate: new SliverChildBuilderDelegate(
                        (context, index) => ,
                    childCount: ....,
                  ),
                ),
              ),
            ),
          ],
        );
```

![screenshot_1536847924 2 2](https://user-images.githubusercontent.com/43211982/45494415-aad7df00-b779-11e8-82f3-b4be7aa09c2c.png)
![simulator screen shot - iphone x - 2018-09-13 at 17 12 26 2](https://user-images.githubusercontent.com/43211982/45494416-aad7df00-b779-11e8-8671-f808d235b000.png)

```
[✓] Flutter (Channel master, v0.8.3-pre.24, on Mac OS X 10.13.6 17G2307, locale ru-RU)
    • Flutter version 0.8.3-pre.24 at /users/tencar/development/flutter
    • Framework revision 387948a239 (2 days ago), 2018-09-11 08:51:42 +0200
    • Engine revision e65beb89da
    • Dart version 2.1.0-dev.4.0.flutter-ef72098353

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/tencar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone (Андрей)           • e09c97faece05a08ba4dad424760438835e7aa4b • ios         • iOS 11.4.1
    • iPhone X                  • 7C386461-A480-4EAA-B478-26142C473ED0     • ios         • iOS 11.4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by gildaswise** [comment]
You need to set `physics: BouncingScrollPhysics(),` on your `CustomScrollView` for it to work. You should also change the `builder` of `CupertinoSliverRefreshControl` to something more Material, like this:

```Dart
CupertinoRefreshControl(
    builder: isApple(context)
        ? buildAppleRefreshIndicator
        : buildAndroidRefreshIndicator,
    onRefresh: ...,
)
```

I did this on my app and here's a [gist](https://gist.github.com/gildaswise/f46c9645dbb07804e92edfa0e051b7e1) with both refresh indicator methods.

**Comment by AndreyTCR** [comment]
thank you! all works now

**Comment by AndreyTCR** [comment]
Reopen. If SliverList have only one item refresh indicator not work(on iOS and Android too)

**Comment by gildaswise** [comment]
@AndreyTCR Is the List occupying all available space or is it only with the item's height? There might not be enough space for the RefreshIndicator to appear, or you are pulling from the middle of the screen instead of right in your list

**Comment by AndreyTCR** [comment]
problem, i think, on SliverList height. If we have 1 item on it then bounce not work correctly, but if we have more items(more i mean Sliverlist bigger then viewport) then all work correctly.

**Comment by Dpuntu** [comment]
You may not be able to swipe on an android device when physics is AlwaysScrollableScrollPhysics. But there's a pit here, you can't do pull-down refresh without the sub controller filling the screen if you
change AlwaysScrollableScrollPhysics to BouncingScrollPhysics. The following code can be pulled down in any case.

```
class RefreshScrollPhysics extends BouncingScrollPhysics {
  const RefreshScrollPhysics({ScrollPhysics parent}) : super(parent: parent);

  @override
  RefreshScrollPhysics applyTo(ScrollPhysics ancestor) {
    return RefreshScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  bool shouldAcceptUserOffset(ScrollMetrics position) {
    return true;
  }
}
```

**Comment by sgon00** [comment]
FYI: I just found out the official example `flutter_gallery` --> `Cupertino` --> Pull to refresh does not work on my Android today. I am not sure if this is the same issue.

**Comment by xster** [comment]
I think the fix here is documentation. Since there are no specs for how an Android + Material native scroll overscroll should behave, we should just offer the components but also make it clear how users can compose the Cupertino components together for use on Android. 

Specifically:

1. Wrap the gallery demo's list with the right scroll physics so it works on Android too.
2. Document the class doc of CupertinoSliverRefreshControl for how to make it work on Android.
3. Let the code in the gallery demo point to the class doc for how to make it work on Android.

**Comment by xster** [comment]
Extracted #30466 from this bug.
