### ISSUE TITLE
When I try to Open a Flutter app demo from github in VisualStudio Code, it says "[Flutter-Music-Player-master] flutter packages get 'Flutter' is not recognized as an internal or external command, operable program or batch file. The system cannot find the path specified. exit code 1"... Here 'Flutter-Music-Player-master' is my Flutter app demo

### ISSUE THREAD

**Issue by iftee939** [flutter/flutter#21823]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Sounds like you didn't add the `flutter` executable to the `PATH` environment variable.

Please check the installation instructions for your OS
https://flutter.io/get-started/install/

**Comment by iftee939** [comment]
@zoechi you're fast man! Nice Service and Thanks for the Advice mate
