### ISSUE TITLE
Text wrap algorithm transparency

### ISSUE THREAD

**Issue by mkliger11** [flutter/flutter#21822]
I am trying to programatically scroll to certain points of my list vie of text widgets.

I have successfully created this algorithm, however, it depends on each device's displayed max characters per line (at what point does the view port decide to wrap text). I use a mono spaced font to account for uniformity. However, different devices/software will wrap at different lengths. The pixels vs points vs dp dilemma makes it even harder to compute.

Thus, this algorithm will break if I cannot compute the characters per line upon app start up. There does not seem to be a formula dependent on the various media query of attributes.

My issue is - I would like either a) Flutter to provide a "did wrap" type of bool so I can run a quick test on each device and figure out at what point does Flutter decide to wrap text. 

Or, b) provide transparency, and allow us to see the text wrapping algorithm if possible. I am new to mobile development and I would assume that this is not handled by flutter, but by ios and android themselves.

**Comment by zoechi** [comment]
One of these might do what you want (I haven't tried any of them myself yet)
https://docs.flutter.io/flutter/painting/TextPainter-class.html 
https://docs.flutter.io/flutter/dart-ui/Paragraph-class.html
https://docs.flutter.io/flutter/rendering/RenderParagraph-class.html
Comments from #19264 might help as well.

**Comment by zoechi** [comment]
A comment from a more knowledgable member of the Flutter team https://github.com/flutter/flutter/issues/18431#issuecomment-396990020

**Comment by mkliger11** [comment]
@zoechi 
Do you have any tips as how to run a test described above - without showing the widget in the view port?

If not, then this issue should be able to be resolved in a cleaner way.

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/widgets/Offstage-class.html might allow that.

**Comment by zoechi** [comment]
@goderbauer @mkliger11 closed the issue but I thought someone might be able to provide better advice than I did above and I reopened it. 
If you think that's not the case I assume it's ok to just close.

**Comment by SteveAlexander** [comment]
I'll offer some code from my project that demonstrates using `LayoutBuilder` with inspecting rendered text lengths.

My requirement is to take a list of strings, and format them so they would fit on exactly one line. The list might be like one of the following:

- `[]`
- `['single item']`
- `['item 1', 'item 2', 'item 3', 'item 4', 'item 5']`

With no items, it is rendered as a `Text('')`. Otherwise, It is rendered like:

- `single item`
- `item 1, item 2, item 3, item 4, item 5`

But, if the width available is too small, it is rendered like:

- `single it...` (or however the Flutter Text ellipsis renders it)
- `item1, item 2, (+3)` (to show two visible items and three more remaining)

Props to our designer Stephen for coming up with this scheme.

```dart
import 'dart:ui' show ParagraphBuilder, ParagraphConstraints;

import 'package:flutter/widgets.dart';

class SingleLineList extends StatelessWidget {
  final List<String> strings;
  final TextStyle style;
  
  SingleLineList(this.strings, {this.style});

  @override
  build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) =>
        Container(
          child: Text(        
            _listFormattedToWidth(
              context,
              constraints.maxWidth,
              strings
            ),
            overflow: TextOverflow.ellipsis,
            style: style
          )
        )
    );
  }

  TextStyle _effectiveTextStyle(BuildContext context) {
    final DefaultTextStyle defaultTextStyle = DefaultTextStyle.of(context);
    if (style == null) return defaultTextStyle.style;
    if (style.inherit) return defaultTextStyle.style.merge(style);
    return style;
  }

  String _listFormattedToWidth(
        BuildContext context,
        double maxWidth,
        List<String> strings
        ) {
    if (strings.isEmpty) return '';
    if (strings.length == 1) return strings.first;

    final effectiveTextStyle = _effectiveTextStyle(context);

    final paragraphStyle = effectiveTextStyle.getParagraphStyle(maxLines: 1);

    bool isTextTooLong(String text) {
      final paragraphBuilder = ParagraphBuilder(paragraphStyle)
          ..pushStyle(style.getTextStyle())
          ..addText(text);
      final paragraph = paragraphBuilder.build();
      paragraph.layout(ParagraphConstraints(width: maxWidth));
      return paragraph.didExceedMaxLines;
    }

    final length = strings.length;

    int position = 0;
    String previousText;
    while (position < length) {
      ++position;
      final numRemaining = length - position;
      final text =
          strings.sublist(0, position).join(', ') + ', (+$numRemaining)';
      if (isTextTooLong(text)) return previousText ?? text;
      previousText = text;
    }

    final fullText = strings.join(', ');
    if (isTextTooLong(fullText)) return previousText;
    return fullText;
  }
}
```
