### ISSUE TITLE
`flutter test` should have a timeout at the platform plugin level

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2182]
See https://github.com/flutter/flutter/issues/2181

`flutter test` was hung on the bots for 23 hours in this case.  `date_picker_test.dart` was where the hang happened, but presumably `flutter test` (or `package:test`) needs to know how to timeout tests.  `package:test` probably already does and we're just holding it wrong.

@abarth @nex3 @yjbanov

**Comment by nex3** [comment]
There are a few ways to write a test that runs forever without timing out. The timeout logic is handled entirely in the test's isolate (or iframe or process), so if it enters a synchronous infinite loop it will never time out. Also, the test runner only times out after a certain period of *inactivity*, which is defined based on the test's interaction with testing primitives. If it's registering new callbacks with `expectAsync()` or the `completes` or `completion` matcher those callbacks are firing, then it won't time out.

**Comment by Hixie** [comment]
@nex3 In our case, there's a problem in that we don't really test the subprocess (it's one of the things we're testing). It would be ideal if we could have the timing logic in the outer process.

**Comment by nex3** [comment]
Having an external timeout doesn't work very well when you want to frequently reset it from within the test. If you need one, I suggest building it into your platform plugin—if you emit a timeout error through the returned `StreamChannel`, the runner should handle that gracefully.

**Comment by Hixie** [comment]
Ah, I didn't realise tests could interact with their timeouts.

**Comment by nex3** [comment]
Yeah, that's how it formalizes the idea of "inactivity".

**Comment by eseidelGoogle** [comment]
I'm actually convinced my change to add a timeout was wrong.  I believe the underlying error is that flutter does not pass  https://github.com/dart-lang/sdk/blob/master/tests/isolate/handle_error2_test.dart as far as I can tell.  See comments on #3366.

**Comment by Hixie** [comment]
I studied this and decided to WONTFIX it. Our bots have their own timeouts, which should be good enough to catch regressions. The test framework has timeouts to catch well-behaving slow/hung tests. There's not really a good place to put another timeout.
