### ISSUE TITLE
Code Sample: Adding Flutter to an app within a ListView and RecyclerView

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21839]
Publish a code sample that demonstrates flutter/website#7786

**Comment by rohan20** [comment]
This would be amazing! Any progress so far? How can I help?

**Comment by matthew-carroll** [comment]
@rohan20 Work on this use-case is on-going.  There are some fundamental performance issues that need to be solved, so it's unclear when this use-case might be supported.

**Comment by kamssun** [comment]
I am amazing too .
