### ISSUE TITLE
Code Sample: Adding Flutter to an app with FlutterView

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21840]
Publish a code sample that demonstrates flutter/website#7785

**Comment by ened** [comment]
@matthew-carroll https://github.com/flutter/flutter/tree/master/examples/flutter_view ?

**Comment by matthew-carroll** [comment]
This ticket refers to a new version of the Android embedding which is structured much differently than the current one.

**Comment by reidbaker** [comment]
https://docs.flutter.dev/add-to-app/android/add-flutter-view
