### ISSUE TITLE
Website Guide: Adding Flutter to an iOS app within a fullscreen ViewController

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21845]
Publish a website guide that explains how to use Flutter with a fullscreen FlutterViewController on iOS.

A fullscreen FlutterViewController is the simplest way to integrate Flutter within an iOS app.  This is analogous to using a FlutterActivity on Android.

Please ensure that this guide is written against the newest version of the iOS embedding.

**Comment by xster** [comment]
This one specifically is done at https://github.com/flutter/samples/tree/master/add_to_app/ios_fullscreen

**Comment by xster** [comment]
Oops, this one is asking for docs. https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen then.
