### ISSUE TITLE
Code Sample: Adding Flutter to an app with FlutterFragment

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21841]
Publish a code sample that demonstrates #21848

**Comment by RedBrogdon** [comment]
After this was filed (but some time ago), FlutterFragment arrived in a sample demonstrating how to use multiple Flutter engines in a single Android app:

https://github.com/flutter/samples/blob/main/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/DoubleFlutterActivity.kt

This issue should have been closed at that time, so I'm going to go ahead and close it now.
