### ISSUE TITLE
Website Guide: How to link a Flutter module to an existing iOS project

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21851]
Website Guide: How to link a Flutter module to an existing iOS project.

This refers to the creation of a Flutter module project and then linking that module project to an existing XCode project via project configuration.

This guide should demonstrate a CLI-only approach.  I don't believe we will have any IDE support for this by delivery time.

**Comment by neiljaywarner** [comment]
this would probably help our company decide if Flutter is usable.  Even a case study with groupon if they did it..

**Comment by matthew-carroll** [comment]
@neiljaywarner I responded to your comment on a related issue, but I'll repeat here that we'd like to hear how you intend to use Add2App behavior.  We're taking a 2nd look at specific use-cases for Add2App to ensure that we're covering the necessary bases.

**Comment by zoechi** [comment]
Is this issue about https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps but more elaborate and for https://flutter.io/ ?
Should this be moved to flutter/website?

**Comment by zoechi** [comment]
I think it's fine to leave it here if it is to track your own work. 
If you want the website team to take over the task, then I think it should be moved to flutter/website.

**Comment by matthew-carroll** [comment]
For now it's for me, so we can leave it.

**Comment by jmagman** [comment]
The website now has a [Flutter module into your iOS project](https://flutter.dev/docs/development/add-to-app/ios/project-setup) page.  Closing.
Feel free to re-open if there was more you wanted to include that isn't covered with https://github.com/flutter/flutter/issues/45224.
