### ISSUE TITLE
Website Guide: How to link a Flutter module to an existing Android project

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#21850]
Website Guide: How to link a Flutter module to an existing Android project.

This refers to the creation of a Flutter module project and then linking that module project to an existing Android project via Gradle.

This guide should demonstrate a CLI-only approach, and also include an Android Studio IDE approach.

**Comment by Bad-Toro** [comment]
Any progress or ETA on this issue?

**Comment by karanshah89** [comment]
Looking forward to this, also one for iOS :)

**Comment by SillyRabbite** [comment]
any progress?

**Comment by joaquini** [comment]
Guys, what do you think about this guide? https://medium.com/flutter-community/add-flutter-to-existing-android-ios-app-ae8c4fb1582e#targetText=Android%2FiOS%20Module,results%20and%20updates%20the%20UI.

**Comment by xster** [comment]
This is done now in https://flutter.dev/docs/development/add-to-app.
