### ISSUE TITLE
Firestore - Issue reestablishing connection

### ISSUE THREAD

**Issue by madtocc** [flutter/flutter#21852]
I'm currently facing an issue with a device (particularly a Redmi Note 3 • android-arm64 • Android 8.1.0 (API 27)). I have tested it with other 4 devices and didn't face this problem, though. 

Whenever I turn off Wifi and then turn it back on, the Firestore does not fire any event nor listen to changes, it simply acts like it was offline. If I close the app and start the app again it fires all the actions made at once (sure, because of the persistent mode). I would like to know if there's any way to force it to reestablish a connection with Firestore. Thanks!

**Comment by holyspidoo** [comment]
Yes, this completely breaks my app on Android. Even if the app is in the background, turning off/on wifi will make it so the tasks don't update anymore. Does not happen on iOS.

**Comment by kroikie** [comment]
@madtocc

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/664. Any further collaboration will be done there.
