### ISSUE TITLE
How to disable signInSilently

### ISSUE THREAD

**Issue by Mantas0726** [flutter/flutter#21867]
I'm using [firebase_auth package](https://pub.dartlang.org/packages/firebase_auth) for email/pass, google, facebook signins. 

The problem I face is that once I sign in with one google account, I cannot change the account after the logout, it does signin automatically with the previously used account. I assume that's because of the silent sign in. How can I disable this and show account selection popup each time user presses sign in? 

Threre is the same issue with facebook, I wonder whether that's to be resolved via firebase or facebook sdk?

**Comment by zoechi** [comment]
Try signout for both FirebaseAuth and GoogleSignIn

**Comment by Mantas0726** [comment]
Worked like a charm, thanks!
