### ISSUE TITLE
DataTable: allow row background colors to be configured

### ISSUE THREAD

**Issue by wolfcro1984** [flutter/flutter#21864]
In my app I had the need to color differently alternative (even) rows so the table could become more readable.

I suggest that you add to the constructor new parameters to provide the desired feature:
```dart
this.selectedRowBackgroundColor = _grey100Opacity,
this.alternateRowBackgroundColor = Colors.transparent,
```

I've done my own implementation of `DataTable` with that functionality but I think it would be useful to others also.

I had problems with the ripple effect on the `DataCell` `InkWell` on the alternative rows that were with a different background color so I had to do the standard workaround with the `Material` widget:
```dart
label = Material(
        color: Colors.transparent,
        child: new InkWell(
          onTap: onTap,
          child: label,
        ),
      );
```

**Comment by mohamed6996** [comment]
@NewITCorp 
could you please show me how did you change the background color?

**Comment by wolfcro1984** [comment]
This are the snippets from my implementation: 

`final BoxDecoration _kSelectedDecoration = new BoxDecoration(
      border: new Border(bottom: Divider.createBorderSide(context, width: 1.0)),
      color: selectedRowBackgroundColor,
    );
    final BoxDecoration _kUnselectedDecorationEven = new BoxDecoration(
      border: new Border(bottom: Divider.createBorderSide(context, width: 1.0)),
    );
    final BoxDecoration _kUnselectedDecorationOdd = new BoxDecoration(
      border: new Border(bottom: Divider.createBorderSide(context, width: 1.0)),
      color: alternateRowBackgroundColor,
    );`

Here we define a decoration for the rows in the build method. I think the names explain the use case.
Next we use it in when the rows are created.

`final List<TableRow> tableRows = new List<TableRow>.generate(
      rows.length + 1, // the +1 is for the header row
      (int index) {
        return new TableRow(
            key: index == 0 ? _headingRowKey : rows[index - 1].key,
            decoration: index > 0 && rows[index - 1].selected
                ? _kSelectedDecoration
                : index.isEven ? _kUnselectedDecorationEven : _kUnselectedDecorationOdd,
            children: new List<Widget>(tableColumns.length));
      },
    );`

When I did only this change the table looked good but you couldn't tap on the cells with not transparent background. Well in the original code there was a comment "The backgroundColor has to be transparent so you can see the ink on the material" so don't forget to implement the workaround I wrote in the initial issue explanation.

**Comment by mohamed6996** [comment]
i have a small question,, you are using list of TableRows, so it is impossible to use it inside rows property of DataTable.

DataTable takes in columns and rows that each of them require list of DataColumn and DataRow respectively.

**Comment by wolfcro1984** [comment]
I think the DataRow class shouldn't have UI settings in them but should only have data values compatible with the provided DataColumns. That kind of decoupling feels more right :) 
What I did is add a configuration to the DataTable (which is a widget that controls the table layout), not to the single DataRow.
Well in your own implementation you can easily have your own DataRow that has that kind of configuration. Maybe that functionality will be added too, let's wait and see like @NewITCorp said.

**Comment by lucien-theron** [comment]
It would also be nice to change the color per cell, rather than whole row and column

**Comment by Kiruel** [comment]
Anynews on this one ?

**Comment by Laban1** [comment]
Being able to set cell colors conditionally from code would be _very_ useful.  

An example: a grid with inventory data where certain items should have a different background or foreground color depending on whatever business rules (e.g.  discontinued items = grey b/g, back-ordered items = light blue b/g, hot items = red f/g, etc.).

**Comment by KenAragorn** [comment]
Hi, any good news on this?

**Comment by p30arena** [comment]
Still waiting for this

**Comment by deadsoul44** [comment]
It has been 1.5 years with 14 thumbs up. This issue deserves attention.

**Comment by deadsoul44** [comment]
I found more simple workaround. You have to put Container inside DataCell with a minimum height of 48 and use color property of Container.

**Comment by mutuc4** [comment]
Any solutions to change DataColumn color? This is the result if I try to add Expanded with Container color in label field. Dont be a good idea if can I configure all(padding, hover,color, margin) in child Widget?

<a href="https://imgbb.com/"><img src="https://i.ibb.co/zsgh8s7/data-Column.png" alt="data-Column" border="0"></a>

**Comment by juanzero000** [comment]
The only workaround that I have found that really works is to copy the whole data_table.dart file and apply your custom changes. You  can even extend it adding new parameters to support the desired styles in headers and rows.

**Comment by NewITCorp** [comment]
> The only workaround that I have found that really works is to copy the whole data_table.dart file and apply your custom changes. You can even extend it adding new parameters to support the desired styles in headers and rows.

yes. I use this solition 1.5 years ago until now.

**Comment by Ahmadre** [comment]
You can follow this PR for updates: https://github.com/flutter/flutter/pull/60744

**Comment by perclasson** [comment]
With https://github.com/flutter/flutter/pull/60764 merged to master, this is now available on the master channel. The argument `color` has been added to `DataRow` to support customizing colors in a `DataTable`.

**Comment by Ahmadre** [comment]
@perclasson I am getting this error, when trying to set the color:

<img width="1181" alt="Bildschirmfoto 2020-07-08 um 23 41 38" src="https://user-images.githubusercontent.com/18512224/86973261-99dd3680-c174-11ea-88a6-56ae95a6ff09.png">

what do I have to do?

**Comment by perclasson** [comment]
@Ahmadre I think you're missing an extra parentheses.

```dart
color: MaterialStateProperty.resolveWith<Color>((Set<MaterialState> states) {
...
}
```

**Comment by Ahmadre** [comment]
@perclasson 

<img width="848" alt="Bildschirmfoto 2020-07-08 um 23 58 12" src="https://user-images.githubusercontent.com/18512224/86974593-e9246680-c176-11ea-9180-7faac2ffdf91.png">

Then you should please update your example code. But thanks :)

**Comment by Ahmadre** [comment]
> Edit:
> I think the example doc under DataRow is missing one too. Should be updated.

Perfect! Thanks a lot! Love your changes ❤️

**Comment by giorgio79** [comment]
How can I change only the header row color?

**Comment by giorgio79** [comment]
Added a new req https://github.com/flutter/flutter/issues/63340
