### ISSUE TITLE
PaginatedDataTable: make header an optional parameter

### ISSUE THREAD

**Issue by wolfcro1984** [flutter/flutter#21862]
The `header` parameter of a `PaginatedDataTable` is required.  
In my case I have bottom navigation tab which name explains what is in the table so I don't need the same name in the table header and it uses a lot of space. 

I suggest that you make the `header` parameter optional and don't show the header row 
(headerWidgets) 
`if(header == null && _selectedRowCount == 0 && widget.actions == null)`.

I've done my own implementation of `PaginatedDataTable`  with that functionality but I think it would be useful to others also.

**Comment by goderbauer** [comment]
PRs with your fix are welcome!

**Comment by wolfcro1984** [comment]
Ok, you can expect it week.

Datuma čet, 3. sij 2019. 21:51 Michael Goderbauer <notifications@github.com
piše:

**Comment by wolfcro1984** [comment]
The pull request has passed the checks, now someone with write privileges needs to merge it.

**Comment by wolfcro1984** [comment]
Can anybody help me with this merge? I don't know what went wrong. It says that there is an error but not where:

ERROR: Last command exited with 1 (expected: zero).
Command: ..\..\bin\flutter.bat test
Relative working directory: packages\flutter

**Comment by jlubeck** [comment]
Any updates on this?
