### ISSUE TITLE
PaginatedDataTable: non logical PageRowsInfoTitle

### ISSUE THREAD

**Issue by wolfcro1984** [flutter/flutter#21869]
If we want a table that can show 10 rows (we set `rowsPerPage` in the constructor) and the current data has 5 rows. The `PageRowsInfoTitle` at the bottom of the table shows `1-10 of 5` which is not a great info. The correct way in this situation should be `1-5 of 5` even if the grid is showing 10 rows (5 blank).

I resolved that issue by doing my implementation of the `PaginatedDataTable` and correcting the part that is generating the `PageRowsInfoTitle`:
```dart
new Text(localizations.pageRowsInfoTitle(
          _firstRowIndex + 1,
          _rowCount >= 0 && _firstRowIndex + widget.rowsPerPage > _rowCount ? _rowCount : _firstRowIndex + widget.rowsPerPage,
          _rowCount,
          _rowCountApproximate)),
```

Hope you implement that check in the official track.

**Comment by wolfcro1984** [comment]
Another illogial situation is when you don't have any rows in the paginated data table. The table now shows "1 - 10 of 0" but the correct way should be "0 - 0 of 0".

I resolved that issue by doing my implementation of the PaginatedDataTable and correcting the part that is generating the PageRowsInfoTitle:

```
new Text(localizations.pageRowsInfoTitle(
          _rowCount > 0 ? _firstRowIndex + 1 : 0,
          _rowCount >= 0 && _firstRowIndex + widget.rowsPerPage > _rowCount ? _rowCount : _firstRowIndex + widget.rowsPerPage,
          _rowCount,
          _rowCountApproximate)),
```

**Comment by TahaTesser** [comment]
Hi @wolfcro1984 
Are you still experiencing this issue with latest version of Fluttter?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/flutter/flutter/issues/21869

**Comment by jlubeck** [comment]
hey @VladyslavBondarenko you asked to follow up on #21869 but that is that same issue... do you have the proper follow up?

**Comment by TahaTesser** [comment]
@jlubeck 
please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`

**Comment by jlubeck** [comment]
@TahaTesser well, the description is exactly what @wolfcro1984 described in the first place... if it hasn't been fixed, I'm not sure why it was closed. I do have a fix myself which I can PR though. So if you can reopen this one, I'm happy to send the PR

**Comment by TahaTesser** [comment]
Hi @jlubeck 
Can you please provide details? Please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
