### ISSUE TITLE
iOS: Reduce the size of the IPA when using precompilation

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#2187]
- [x] Get rid of the precompilation snapshot generation machinery from the embedder VM.
- [ ] Get rid of observatory assets.
- [x] Ignore checked mode when generating the precompilation snapshot.
- [x] `-fdead-strip` is disabled on the precompilation dylib due to `lld` crash. Not sure if this gives any size savings since the engine is separate and has dead stripping enabled.

**Comment by chinmaygarde** [comment]
cc @fsc8000

**Comment by fsc8000** [comment]
nr 1: can be now done by replacing libdart with libdart_precompiled_runtime for the ios shell runner.

nr 4: I don't expect the ```-fdead-strip``` option to make much of a difference on the precompiled dylib. The symbols in there are the ones left after tree-shaking from the Dart precompiler, so they are all needed.

**Comment by fsc8000** [comment]
nr 3: checked mode can be disabled by omitting ```--checked``` when generating the snapshot, (and when running the app)

In the standalone VM case, unchecked hello_world code size is around 35% smaller than checked.

**Comment by abarth** [comment]
WIll that strip out the asserts entirely?  We have lots of code that's reachable only through asserts.

**Comment by fsc8000** [comment]
Yes, it should strip out explicit asserts, plus their subexpressions, and implicit type assertions that come with checked mode.

The size difference may actually be larger in your case compared to hello_world.

**Comment by chinmaygarde** [comment]
For hello_world with precompilation: 3652k in checked mode, 3048k in unchecked. I have disabled checked mode in precomp for both the snapshotter and the embedder VM.
