### ISSUE TITLE
Error show when running `flutter create` in a folder without write-acesss is confusing

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#21873]
1. cd to some directory where you do not have write access
1. `flutter create foobar`

=>

```
$ flutter create foobar
Creating project foobar...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 9c0f7e1861f4da43)
Crash report written to /var/folders/8p/m8bypz3d0xj3d3m_p4ckk_4w00768h/T/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.

```

**Comment by mit-mit** [comment]
From the log file, looks like we are failing to catch the file exception:
```
FileSystemException: FileSystemException: Creation failed, path = '/foobar' (OS Error: Permission denied, errno = 13)

```
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      Template.render (package:flutter_tools/src/template.dart:71:17)
#3      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:364:21)
#4      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:305:23)
```

**Comment by mit-mit** [comment]
cc @gspencergoog

**Comment by filleduchaos** [comment]
I could take a crack at this this weekend, if @gspencergoog doesn't mind

**Comment by gspencergoog** [comment]
I've already got a fix.  Prepping a PR.

**Comment by zoechi** [comment]
```
 $ flutter create foo
Creating project foo...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 8ccbfc919a98320a)
Crash report written to /var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by csells** [comment]
@gspencergoog did you post the PR?
@mit-mit are you still seeing this behavior?

**Comment by gspencergoog** [comment]
Huh.  Well, whether I did or not (I looked and didn't find anything related from that era), we still don't appear to catch the exception and print something reasonable. I'm able to easily reproduce this.

**Comment by jonahwilliams** [comment]
I'm de-duping into a larger issue: https://github.com/flutter/flutter/issues/50880 .

We can't handle this as a one off for each crash, since the set of files we need permissions for is quite large (and continues growing)
