### ISSUE TITLE
Flutter templates contain a lot of IntelliJ files

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#21876]
The Flutter templates contain a lot of IntelliJ files, e.g.:
```
drwxr-xr-x   5 mit  primarygroup   160B Sep 14 12:05 .idea
-rw-r--r--   1 mit  primarygroup   896B Sep 14 12:05 testmod.iml
-rw-r--r--   1 mit  primarygroup   1.4K Sep 14 12:05 testmod_android.iml
```

These have no utility to a developer using another editor/IDE (such as vscode), or using the terminal. Should we consider only creating these when creating projects from within IntelliJ/Android Studio?

**Comment by mit-mit** [comment]
cc @devoncarew, WDYT?

**Comment by devoncarew** [comment]
It may be possible to move the `foo_android.iml` inside the android directory; I - @stevemessick - would have to look into it.

> These have no utility to a developer using another editor/IDE (such as vscode)

Agreed. What I want to make sure is that there's as little friction or issues as possible with opening the project w/ Android Studio. It's generally not as easy to open a new project with IntelliJ based tools as I'd like, so doing what we can to reduce friction here is worthwhile.

A while ago we did put some code into IntelliJ to create missing project files when necessary - we'd have to verify that this handles all anticipated use cases (that the metadata files really are optional).

**Comment by stevemessick** [comment]
A quick experiment indicates that, yes, you could move the `*_android.iml` file into the `android` directory, as long as `.idea/modules.xml` exists and is changed to point to the new location. You cannot move the other `*.iml` file, though. I'm not sure if that is because something in the Flutter plugin expects it to be at top-level (and could be changed) or if it is something IntelliJ depends on.

**Comment by mit-mit** [comment]
Did we decide on a solution here?

**Comment by devoncarew** [comment]
I'd say we should move the `foo_android.iml` inside the `android/` directory, but that may now be more trouble than it's worth. The name of the directory can now be either `.android/` or `android/`, and if we move where the file is, the make-app-editable command would have to know to update the references to the .iml file from the `.idea/modules.xml` file.

I'd like to close this as won't do, or drop it to a P3.

**Comment by mit-mit** [comment]
I agree that moving the file has little value to IntelliJ developers. However, I still question the value of 7 extra IntelliJ metadata files for developers that use terminal or vscode. So could we not consider creating these only during project creation in an IntelliJ-based IDE?

**Comment by DanTup** [comment]
Possibly this is the same as #14723?

**Comment by stevemessick** [comment]
This was addressed in https://github.com/flutter/flutter/pull/24311. Whatever is left is a dup of #14723.
