### ISSUE TITLE
Link code snippets to the GitHub page

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter#21892]
Flutter.io's tutorial pages (e.g. [Building Layouts in Flutter](https://flutter.io/tutorials/layout/)) have multiple code snippets to explain different parts of an app, but it is hard to see each snippet in the context of a complete app. 

Can we link each snippet to its full app on GitHub, with highlights on the snippet's location (line #)?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1967](https://github.com/flutter/website/issues/1967) via [**ZenHub**](https://www.zenhub.com/)
