### ISSUE TITLE
Enhance UI for sample codes

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter#21891]
For the sample codes in flutter.io, I'd like to suggest adding a unique UI:

1. On hover, highlight a block of code, starting from the line under a mouse pointer to the end of the widget, variable, or child (closing bracket, end of line, etc.) 
2. When highlighted, show a copy button on the corner of the highlighted block so that the user can copy the whole block without worrying about finding a matching closing bracket
3. Highlight goes away on click so that the user can copy custom parts of the sample

It can be particularly useful for users going through the tutorials such as: 
https://flutter.io/tutorials/layout/

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1968](https://github.com/flutter/website/issues/1968) via [**ZenHub**](https://www.zenhub.com/)
