### ISSUE TITLE
flutter analyze needs to handle errors that are purportedly in the generated main.dart more gracefully

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2189]
Analyzing 48 files...
FileSystemException: Cannot open file, path = '/tmp/flutter-analyze-0ijrLW/main.dart' (OS Error: No such file or directory, errno = 2)
dart:io                                                           _File.readAsLinesSync
package:flutter_tools/src/commands/analyze.dart 344               AnalyzeCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/analyze.dart 386               AnalyzeCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/analyze.dart                   AnalyzeCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 87          FlutterCommand.run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 201  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/executable.dart 72                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 65                          main.<async>

**Comment by apwilson** [comment]
Turns out you get this error if you supply a file name that doesn't exist as well.

**Comment by apwilson** [comment]
ie. flutter analyze i_dont_exist.dart

**Comment by Hixie** [comment]
Yeah the problem is that the error message we're getting from the dartanalyzer is in the main.dart file and by the time we try to read it we've already deleted it.

**Comment by eseidelGoogle** [comment]
Is it having some sort of race with the creation/deletion of its temp directory?  Do you believe this is a problem with `flutter analyze` (in which case @Hixie) or the underlying analyzer (in which case @pq).

**Comment by pq** [comment]
A quick fix might just be to move `host.deleteSync(recursive: true)` until after the processing of `errorLines`?

**Comment by Hixie** [comment]
That would at least change the error message. But we should never be getting errors in the generated file regardless (which is why I put the delete first -- so that it would fail hard if we did).

**Comment by apwilson** [comment]
So if I remove the deleteSync I actually get some valid errors.

The only one I think is different than others which don't break the system is this one:
```
The imported libraries '<redacted>_test.dart' and '<redacted>_test.dart' cannot have the same name '<redacted>_test' (/tmp/flutter-analyze-iKe27T/main.dart, line 44, col 1)

```

**Comment by pq** [comment]
>  But we should never be getting errors in the generated file regardless 

Should we add an existence check on `flutter analyze` targets?

**Comment by pq** [comment]
@apwilson : is this failure repeatable?

**Comment by Hixie** [comment]
I have a fix but in trying to verify it I ran into a problem whereby it turns out we're not checking several of our tests so I'm fixing that too.

**Comment by apwilson** [comment]
Yes, happens every time.
