### ISSUE TITLE
48px by 48px padding around TextField's prefixIcon is restrictive

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#21908]
My designer would like a search field like this:

![image](https://user-images.githubusercontent.com/4321921/45588278-25376900-b90a-11e8-9104-8da15d5cb80a.png)

I can get close in Flutter using a `TextField` and specifying my own `InputDecoration`:

![image](https://user-images.githubusercontent.com/4321921/45588320-f40b6880-b90a-11e8-985a-a9ab60195beb.png)

But, there remains a problem that I cannot solve using `InputDecoration`. The `prefixIcon` is forced to have a minimum size of 48x48. From `input_decorator.dart`:

```
    final Widget prefixIcon = decoration.prefixIcon == null ? null :
      Center(
        widthFactor: 1.0,
        heightFactor: 1.0,
        child: ConstrainedBox(
          constraints: const BoxConstraints(minWidth: 48.0, minHeight: 48.0),
          child: IconTheme.merge(
            data: IconThemeData(
              color: iconColor,
              size: iconSize,
            ),
            child: decoration.prefixIcon,
          ),
        ),
      );
```
The same is true of the `suffixIcon` — although that's not visible in this design, there's a similar issue.

Another issue is the height of the text field: without prefix and suffix icons, the text field can be made slightly less tall, which is also what my designer is asking for. But, the mandatory minimum height of the prefix and suffix icons means that any text field using prefix/suffix icons will have a minimum height of 48px.

![image](https://user-images.githubusercontent.com/4321921/45588462-1ef6bc00-b90d-11e8-9518-849383cb312c.png)

With the icons removed, I'm able to control the text field's height using the decoration's `contentPadding` attribute:

![image](https://user-images.githubusercontent.com/4321921/45588477-51081e00-b90d-11e8-9274-6e6ab86ee070.png)

With icons present, the `contentPadding` is not that useful.

The rationale for the mandatory padding is given around line 2115 of the same file. I'm reading into this that the 48px by 48px comes from Material Design guidelines.

```
  /// The prefix icon is constrained with a minimum size of 48px by 48px, but
  /// can be expanded beyond that. Anything larger than 24px will require
  /// additional padding to ensure it matches the material spec of 12px padding
  /// between the left edge of the input and leading edge of the prefix icon.
  /// To pad the leading edge of the prefix icon:
```

I expect I can achieve what I want by not using an `InputDecoration` at all, and putting various widgets together in a `CustomLayout` or `Stack` arrangement. But, it feels to me like `InputDecoration` is meant to do what I'm trying to do — it's just I'm finding the minimum size constraint restrictive.

For context, I've given some further discussion of my experience of flutter and material in #21026

@HansMuller filing this separate issue as requested in #21026

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.8.5-pre.5, on Mac OS X 10.13.6 17G2307, locale en-GB)
    • Flutter version 0.8.5-pre.5 at /Users/steve/code/flutter
    • Framework revision 1ad538e454 (16 hours ago), 2018-09-14 16:47:28 -0700
    • Engine revision 24d94601b9
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone X • 1E0393AA-EF50-42AA-A244-3279599BE2C1 • ios • iOS 11.4 (simulator)

• No issues found!
```

**Comment by shakil807g** [comment]
@SteveAlexander yes i had same issue with TextField

**Comment by 2015-lizaiyang** [comment]
没办法，您只能自己去拼凑一个自己想要的。

**Comment by ebastuart** [comment]
prefixIcon expects a Widget, not an Icon directly. You can adapt the padding by using the Padding widget.
```
prefixIcon: Padding(
 padding: EdgeInsets.all(0.0),
 child: Icon(Icons.place),
), 
```

**Comment by SteveAlexander** [comment]
@ebastuart thanks, but unfortunately this does not reduce the padding below the minimum. The minimum is applied as extra padding (a sized box iirc) within the code that lays out the text field decorations.

**Comment by sprmrkt** [comment]
Any workarounds? @SteveAlexander Can we somehow extend widget and remove the restrictions?

**Comment by ReginFell** [comment]
Any news on that? Really annoying that I have to create a replica of TextField just to get rid of the icon's padding

**Comment by SaravanarajaGITHUB** [comment]
In my case i used this helper widget to my TextFormField's prefixIcon, & it solve this issue

```
Widget buildCustomPrefixIcon(IconData iconData) {
  return Container(
    width: 0,
    alignment: Alignment(-0.99, 0.0),
    child: Icon(
      iconData,
    ),
  );
}
```


![SmartSelect_20190612-192628](https://user-images.githubusercontent.com/6235704/59357257-1fab6a00-8d48-11e9-9491-dc087db7c1d9.jpg)

**Comment by guokangf** [comment]
so do i

**Comment by saitbnzl** [comment]
Same annoying issue with the suffixIcon.. It has to be optional.

**Comment by miguelpruivo** [comment]
For those struggling with the `TextFormField` that has a `suffixIcon` or `prefixIcon` not being allowed to be smaller due to the 48x padding, you can achieve so, by wrapping it with an `IntrinsicHeight` that will force the child (`TextFormField` in this case) to shrink to a more reasonable size, mostly like it will be sized to the input font size + any decoration padding.

However, have in mind that this should only be a workaround and there should be an option to set the icon padding manually. With this solution, if you have your icon bigger than the `TextFormField` input text, it won't care and the Icon will overflow the box.

**Comment by k00na** [comment]
One way to solve this is to put a custom widget to the prefix or suffix property and not to use the prefixIcon/suffixIcon property at all. 

`decoration: InputDecoration(
          //suffixIcon: Icon(Icons.comment),
          suffix: Padding(
            padding: const EdgeInsets.all(2.0),
            child: Icon(Icons.comment),
          ),`

Bellow you can see the difference in the amount of padding: 

Using prefix property with custom widget - no crazy padding, only what you specify:

<img width="306" alt="Screenshot 2019-08-27 at 10 52 20" src="https://user-images.githubusercontent.com/13611208/63756488-c4a20180-c8b8-11e9-9caa-ce7acaa103ee.png">

Using prefixIcon property with all that fat padding... 
<img width="304" alt="Screenshot 2019-08-27 at 10 53 06" src="https://user-images.githubusercontent.com/13611208/63756563-e307fd00-c8b8-11e9-8050-897a0cf6be17.png">

However, one minus when using prefix property is that you don't get all the out-of-the-box features for icons, like automatically changed colour when field has focus, etc. Might work on this on my own.

**Comment by ksankumar** [comment]
Any update on this issue?
This issue(Prefix icon padding) causing big design collapse in low height devices such as iphone 5, Nexus 5, etc.

**Comment by erkanmaras** [comment]
Any update on this issue?

**Comment by gitfornncn** [comment]
Any update on this issue?

**Comment by leandro070** [comment]
My temporary solution for the height of TextField is to wrap TextField in a Container with `height: 30`, for example.

**Comment by omri1100** [comment]
Any update?
