### ISSUE TITLE
improve IOWebSocketChannel

### ISSUE THREAD

**Issue by SeniorIvan** [flutter/flutter#21902]
i write chat on websocket, I do not have access to the socket connection state, I found states in private sources(connecting, open etc)

in current implementation unclear, client connected to socket or performed connection.

in below example , onDone called with long delay, although pong not received and socket closed.

    var channel = IOWebSocketChannel.connect('ws://echo.websocket.org', pingInterval: Duration(milliseconds: 1000));
    channel.stream.listen((d) {
      print(d);
    }, onDone: () {
      print('done');
    }, onError: (error) {
      print(error);
    });

what I want: example, stream of connection state(connecting, connected, error, closed, etc)
i subscribed in page for change ui state(example show connection indicator(color dot). or make access to socket state, and run Timer with checking it value.

**Comment by zoechi** [comment]
Closing as dup of https://github.com/dart-lang/web_socket_channel/issues/16
If you think it is not a duplicate, please create a new issue in the `web_socket_channel` repo.

**Comment by jinfagang** [comment]
@zoechi  You are link them recurse but still didn't find any solution about this issue.....

**Comment by TomLiu-GitHub** [comment]
我也很苦恼,在我断网后我应该怎么办?
