### ISSUE TITLE
flutter version 0.0.0 cannot install packages and dependencies

### ISSUE THREAD

**Issue by jayantakumar** [flutter/flutter#21918]
hi guys i have my flutter version showing 0.0.0 and when i try to install or upgrade flutter or to get packages like fire base it shows

**The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.
The current Flutter SDK version is 0.0.0-unknown.
```
Because google_sign_in >=3.0.0 requires Flutter SDK version >=0.1.4 <2.0.0 and google_sign_in <3.0.0 requires SDK version >=1.8.0 <2.0.0, google_sign_in is forbidden.
So, because flutter_app depends on google_sign_in any, version solving failed.
pub get failed (1)**
```
**PLEASE HELP ME!!**

**Comment by zoechi** [comment]
Please try 

```
git clean -xfd
git pull
flutter doctor
```
in your Flutter install directory.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by Alekcei** [comment]
Dont work at CentOS-7

**Comment by VASPTRak** [comment]
not working on CentOS-7

**Comment by Alekcei** [comment]
@VASPTRak please update to latest version.

**Comment by liuhong1happy** [comment]
not working on CentOS-7

**Comment by lanss315425** [comment]
not working on centos-7
