### ISSUE TITLE
Snackbar and BottomNavigationBar are not getting fontFamily from ThemeData.

### ISSUE THREAD

**Issue by xclud** [flutter/flutter#21914]
## Steps to Reproduce

1. Setup a MaterialApp and set font family in `theme`:
```dart
return new MaterialApp(
   theme: new ThemeData(primarySwatch: Colors.blue, fontFamily: 'SomeFont'),
   ...
```
2. Display a `Snackbar` or show a `BottomNavigationBar` widget somewhere on the screen.
3. You will see the default font family for them has not changed while whole the app font is changed.

## Logs

```
[√] Flutter (Channel master, v0.8.5-pre.5, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.8.5-pre.5 at D:\Android\flutter
    • Framework revision 1ad538e454 (35 hours ago), 2018-09-14 16:47:28 -0700
    • Engine revision 24d94601b9
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[√] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    • All Android licenses accepted.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • LG K430 • 192.168.1.5:5555 • android-arm • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by mavr301** [comment]
Have same issue with Drawer.

**Comment by peratik** [comment]
yes i have same issue

**Comment by sm2017** [comment]
@xclud I have same issue , any solution?

**Comment by xclud** [comment]
@sm2017 you can define a theme like this:

```
final theme = ThemeData(
  fontFamily: 'MyFont',
  snackBarTheme: SnackBarThemeData(
    contentTextStyle: TextStyle(fontFamily: 'MyFont'),
  ),
);
```

Above code fixes the issue for `SnackBar` default font. But for `BottomNavigationBar` you should pass a `TextStyle` manually to your `Text` widgets:

```
final textStyle = TextStyle(fontFamily: 'MyFont');
BottomNavigationBar(
  items: [
    BottomNavigationBarItem(
      icon: Icon(Icons.audiotrack),
      title: Text(
        'Some text',
        style: textStyle,
      ),
    ),
  ],
);
```

I hope this helps.

**Comment by eseidelGoogle** [comment]
It sounds like the remaining request here is for BottomNavigationBar to inherit its theme from the MaterialApp's theme.  The SnackBar already has a separate theme.

**Comment by eseidelGoogle** [comment]
Actually, I don't think there is anything to do here.

The Text is provided by the user to the BottomNavigationBar.  It's always possible to use Theme.of(context).textTheme to grab the current theme from the text provided, I believe?

Let me know if I've misunderstood.  Speculatively closing.  Thanks for the report!

**Comment by xclud** [comment]
> Actually, I don't think there is anything to do here.
> 
> The Text is provided by the user to the BottomNavigationBar. It's always possible to use Theme.of(context).textTheme to grab the current theme from the text provided, I believe?
> 
> Let me know if I've misunderstood. Speculatively closing. Thanks for the report!

Sorry for reopening,

As you mentioned, Snackbar already has a separate theme. But i believe, when no font family is specified, it should grab the font family from MaterialApp theme. Currently is not having this behavior.
