### ISSUE TITLE
GlobalKey.currentState is null when the element is assigned with the key in Flutter inspector

### ISSUE THREAD

**Issue by RyanAfrish7** [flutter/flutter#21923]
Simplified widget tree of my application is

```
+ Scaffold
++ Body
+++ PageView
++++ FooView  (with GlobalKey 'FooViewKey')
++++ BarView  (with GlobalKey 'BarViewKey')
```

Most times, the currentState of `FooViewKey` or `BarViewKey` is returned with a null value. I tried debugging and found that those `GlobalKey`s are missing from the `GlobalKey._registry`. I'm not able to predict the cases when they have values and when they are null. 

1) How to fix this issue? (happy to provide any required info)
2) Is there any restrictions on when setState() can be called.

**Comment by dnfield** [comment]
Can you provide some code that leads to this issue?

**Comment by RyanAfrish7** [comment]
I created a simple proof. Try that out. 

@dnfield https://gist.github.com/RyanAfrish7/c9a9553cf9f821769347f1b7f9ddc9c7

**Comment by dnfield** [comment]
The reason `currentState` comes up as null is that the `PageView` doesn't keep the widget around when it's not on screen.  You can see this if you refactor your `PageView` to something like a `Column`.  You're also not calling `setState` when you modify the state, so even if the state __was__ non-null, the changes wouldn't reflect in the UI.

Generally speaking, you should probably try to avoid managing state from one widget to another like this.  There are several patterns available for state management, and you can read up on a bunch of examples [here](https://github.com/brianegan/flutter_architecture_samples).  You should also seek to use `GlobalKeys` as sparingly as possible, and generally only try to use them in such a way that you can be sure that the widget it's Keyed to is actually onstage.

**Comment by RyanAfrish7** [comment]
I understand that it's better to design the app without using GlobalKeys. But can you provide a solution for the the use case I mentioned above. In my real use case, I have a `TextField` in place of `int i` and I'm trying to change the value of `TextField` based on input from another sibling widget.

**Comment by dnfield** [comment]
A very simple way to do that can be found here: https://github.com/brianegan/flutter_architecture_samples/tree/master/example/vanilla

Or, using `InheritedWidget`s, here: https://github.com/brianegan/flutter_architecture_samples/tree/master/example/inherited_widget

The basic idea is that you want updates to that `TextField` to change something in a state repository.  There are tons of ways to handle that, and designing it will depend on your app.  We don't currently have a single recommended way to maintain state across the whole app, but the architecture samples repo provides at least some starting points.
