### ISSUE TITLE
[video_player] Add a state event for video completion

### ISSUE THREAD

**Issue by once10301** [flutter/flutter#21929]

**Comment by yasincidem** [comment]
A solution would be something like the code below until video_player has a isEnded or isFinished method.



```

import 'package:flutter/material.dart';
import '../widgets/YourWidget.dart';
import 'package:video_player/video_player.dart';
import 'dart:async';

class YourState extends State<YourWidget> {
  VideoPlayerController _controller;
  bool _isPlaying = false;
  Duration _duration;
  Duration _position;
  bool _isEnd = false;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
    )
    ..addListener(() {
      final bool isPlaying = _controller.value.isPlaying;
      if (isPlaying != _isPlaying) {
        setState(() {
          _isPlaying = isPlaying;
        });
      } 
      Timer.run(() {
          this.setState((){
            _position = _controller.value.position;
          });
        });
        setState(() {
          _duration = _controller.value.duration;
        });
        _duration?.compareTo(_position) == 0 || _duration?.compareTo(_position) == -1 ? this.setState((){
          _isEnd = true;
        }) : this.setState((){
          _isEnd = false;
        });
      })
    ..initialize();
  }

 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _position.toString(),
      home: Scaffold(
        body: Column(
          children: <Widget> [
            _controller.value.initialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
            Text('Duration ${_duration?.toString()}'),
            Text('Position ${_position?.toString()}'),
            Text('isEnd?  $_isEnd'),
          ]
        ),
        floatingActionButton:  FloatingActionButton(
          onPressed: _controller.value.isPlaying
              ? _controller.pause
              : _controller.play,
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }
}

```

**Comment by once10301** [comment]
Thank you, I have another question.

`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:video_player/video_player.dart';

class SplashActivity extends StatefulWidget {
  @override
  SplashState createState() => new SplashState();
}

class SplashState extends State<SplashActivity> {
  VideoPlayerController controller;
  VoidCallback listener;

  @override
  void initState() {
    super.initState();
    controller = VideoPlayerController.asset('assets/analects.mp4');
    listener = () {
      if (controller.value.initialized) {
        Duration duration = controller.value.duration;
        Duration position = controller.value.position;
        if (duration.compareTo(position) != 1) {
          Navigator.pushReplacementNamed(context, '/main');
        }
      }
    };
    controller
      ..addListener(listener)
      ..setVolume(1.0)
      ..initialize();
    controller.play();
  }

  @override
  void deactivate() {
    super.deactivate();
    controller.removeListener(listener);
    controller.setVolume(0.0);
  }

  @override
  Widget build(BuildContext context) {
    /// 隐藏状态栏
    SystemChrome.setEnabledSystemUIOverlays([]);
    return Scaffold(
      body: Container(
        child: VideoPlayer(controller),
      ),
    );
  }
}
`
I/flutter (28816): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (28816): The following assertion was thrown while dispatching notifications for VideoPlayerController:
I/flutter (28816): Navigator operation requested with a context that does not include a Navigator.
I/flutter (28816): The context used to push or pop routes from the Navigator must be that of a widget that is a
I/flutter (28816): descendant of a Navigator widget.

**Comment by once10301** [comment]
I find another question.
in iOS this can't work.

I used 
print('duration:${controller.value.duration}');
print('position:${controller.value.position}');

flutter: duration:0:00:08.040000
flutter: position:0:00:00.000000
flutter: duration:0:00:08.040000
flutter: position:0:00:00.000000
flutter: duration:0:00:08.040000
flutter: position:0:00:01.153000
flutter: duration:0:00:08.040000
flutter: position:0:00:01.650000
flutter: duration:0:00:08.040000
flutter: position:0:00:02.152000
flutter: duration:0:00:08.040000
flutter: position:0:00:02.652000
flutter: duration:0:00:08.040000
flutter: position:0:00:03.152000
flutter: duration:0:00:08.040000
flutter: position:0:00:03.656000
flutter: duration:0:00:08.040000
flutter: position:0:00:04.160000
flutter: duration:0:00:08.040000
flutter: position:0:00:04.650000
flutter: duration:0:00:08.040000
flutter: position:0:00:05.153000
flutter: duration:0:00:08.040000
flutter: position:0:00:05.652000
flutter: duration:0:00:08.040000
flutter: position:0:00:06.150000
flutter: duration:0:00:08.040000
flutter: position:0:00:06.656000
flutter: duration:0:00:08.040000
flutter: position:0:00:07.152000
flutter: duration:0:00:08.040000
flutter: position:0:00:07.656000
flutter: duration:0:00:08.040000
flutter: position:0:00:07.656000

**Comment by jffiorillo** [comment]
@once10301  
Have you tried using the following listener?
```
listener = () {
  if (controller.value.initialized && !controller.value.isPlaying){
    Navigator.pushReplacementNamed(context, '/main');
  }
};
```

I used in iOs and it worked for me....

**Comment by jerryzhoujw** [comment]
You can set the `loop:false`, then when it play finished, fire another `play` if you want `loop` feature. and do the thing you want in that finished event.

**Comment by nt4f04uNd** [comment]
player position is not accurate at all for me
this always gives me 1
```dart
player.duration - player.position == const Duration()
```
so i need to add 200 milliseconds gap like, which i also can't fully on
```dart
player.duration - player.position < const Duration(milliseconds: 200)
```

**Comment by glosama** [comment]
> A solution would be something like the code below until video_player has a isEnded or isFinished method.
> 
> ```dart
> import 'package:flutter/material.dart';
> import '../widgets/YourWidget.dart';
> import 'package:video_player/video_player.dart';
> import 'dart:async';
> 
> class YourState extends State<YourWidget> {
>   VideoPlayerController _controller;
>   bool _isPlaying = false;
>   Duration _duration;
>   Duration _position;
>   bool _isEnd = false;
> 
>   @override
>   void initState() {
>     super.initState();
>     _controller = VideoPlayerController.network(
>       'http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_20mb.mp4',
>     )
>     ..addListener(() {
>       final bool isPlaying = _controller.value.isPlaying;
>       if (isPlaying != _isPlaying) {
>         setState(() {
>           _isPlaying = isPlaying;
>         });
>       } 
>       Timer.run(() {
>           this.setState((){
>             _position = _controller.value.position;
>           });
>         });
>         setState(() {
>           _duration = _controller.value.duration;
>         });
>         _duration?.compareTo(_position) == 0 || _duration?.compareTo(_position) == -1 ? this.setState((){
>           _isEnd = true;
>         }) : this.setState((){
>           _isEnd = false;
>         });
>       })
>     ..initialize();
>   }
> 
>  @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: _position.toString(),
>       home: Scaffold(
>         body: Column(
>           children: <Widget> [
>             _controller.value.initialized
>               ? AspectRatio(
>                   aspectRatio: _controller.value.aspectRatio,
>                   child: VideoPlayer(_controller),
>                 )
>               : Container(),
>             Text('Duration ${_duration?.toString()}'),
>             Text('Position ${_position?.toString()}'),
>             Text('isEnd?  $_isEnd'),
>           ]
>         ),
>         floatingActionButton:  FloatingActionButton(
>           onPressed: _controller.value.isPlaying
>               ? _controller.pause
>               : _controller.play,
>           child: Icon(
>             _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

Is this a Good practice to use setState in addListener?
Didn't you getting the error of `setState() or markNeedsBuild() called when widget tree was locked.`

**Comment by yy1300326388** [comment]
```
videoPlayerController.addListener(() {
      if (!videoPlayerController.value.isPlaying &&
          videoPlayerController.value.position.inSeconds >=
              videoPlayerController.value.duration.inSeconds) {
        // completion
        print('videoPlayer completion');
      }
    });
```

**Comment by yy1300326388** [comment]
@once10301 
Did it solve your problem?

**Comment by omidraha** [comment]
Related [SO](https://stackoverflow.com/questions/57584726/how-can-i-detect-the-progressinitialize-end-of-video-player-in-flutter).

**Comment by stuartmorgan** [comment]
Per discussion in https://github.com/flutter/plugins/pull/4318, the best way to improve this use case would be to have more details in the event stream such that the completion doesn't have to be inferred from other properties. There will need to be some thought given to how it would interact with other state change events, and things like looping, to make sure it's sufficiently flexible to not cause issues later that can't be fixed without breaking changes.

**Comment by aytunch** [comment]
I agree with @bselwe this condition is not solid. Especially when we are dealing with multiple videos in a pageview and we have to be sure the completed condition firing once, we have to construct a nasty condition. This is not nice to have in UI code. A video player controller API should tell when the video is completed and we should not be trying to get that info by other means.

I am wondering if the underlying native plugins fire a `onCompleted` kind of callback? Can't we just expose them to video player and call it a day?

**Comment by luis901101** [comment]
Definitely as @aytunch wonders, the best would be if the native plugins offered the callback. In the mean time using the suggested workaround is an alternative, although I've found some things to improve, for instance, using position and duration **inSeconds** is not as accurate as using it **inMilliseconds**, because the video can show some frames in the milliseconds after the last integer second. Another thing to improve is to use some flag to indicate video is completed, to avoid duplicated calls.
Here are some improvements to the workaround with support for **onStarted()** and **onCompleted()** callbacks with no duplicated callbacks:

```dart
void initState(){
    ....
    videoPlayerController.addListener(statusListener);
    ...
}

void statusListener() {
    final controllerValue = videoPlayerController.value;
    bool isPlaying = controllerValue.isPlaying;
    int position = controllerValue.position.inMilliseconds;
    int duration = controllerValue.duration.inMilliseconds;
    if(!alreadyStarted && isPlaying && (position == 0 || position < duration)) return onStarted();
    if (!alreadyCompleted && !isPlaying && position > 0 && position >= duration) return onCompleted();
  }

  void onStarted() {
    alreadyStarted = true;
    alreadyCompleted = false;
    //TODO: Video just started
  }

  void onCompleted() {
    alreadyStarted = false;
    alreadyCompleted = true;
    //TODO: Video just completed
  }
```

**Comment by ciriousjoker** [comment]
How is this still an issues after 4 years?

**Comment by Syed-Waleed-Shah** [comment]
Here is the simplest solution:
videoPlayerController.addListener(() {
                if (videoPlayerController.value.position ==
                    videoPlayerController.value.duration) {
                  Get.off(() => const HomeView());
                }
              });

**Comment by carrasc0** [comment]
> 

Not working, sometimes for some reason the position does not reach the end, in my case for exmaple the listener reah until here:

Position: 0:00:10.908000
duration: 0:00:11.436000
