### ISSUE TITLE
Plugins do not work for iOS background execution

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#21925]
Attempting to use a plugin in the context of a background isolate spawned by another plugin will cause failures when making calls over method channels. On Android, the `PluginRegistrant` interface is used to allow for plugins to register the application's plugins with a `FlutterNativeView` but no equivalent is available on iOS.

**Comment by xtelinco** [comment]
Hey, I was wondering if you have had any ideas on how to solve this.

At the moment plugins are registered in the AppDelegate didFinishLaunchingWithOptions. However they are only registered within the FlutterViewController and hence the main UI isolate. So the plugin method channels are only known by the UI isolate.

My idea is to provide a new registerHeadlessPlugins method on the AppDelegate to register plugins for the FlutterHeadlessDartRunner (Background Isolate). You could then register any plugins you need for the background isolate. I think that you may well have differing requirements for the plugins required for the Background tasks, and using the same list as the UI isolate seems a little inflexible.

- (void)registerHeadlessPlugins:(NSObject<FlutterPluginRegistry>*)registry {
    [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
}

I have created a patch using this idea. It seems to work in my environment, but I am only a beginner when it comes to Flutter so I may well be missing something.

https://github.com/xtelinco/engine/commit/eccfdfa83ac009857cd1797f6fac4b7e15a7bfa5

**Comment by bkonyi** [comment]
Also assigning to @dnfield as he's working on updating the iOS APIs which should resolve this.

**Comment by dnfield** [comment]
We've had some discussion of this internally. I think at a high level our options are either:

1. Run plugin code on any isolate at any time.  May result in thread-safety issues (e.g. SQLite plugins running on multiple threads trying to lock the same DB file).
1. Run plugin code on only one isolate at a time.  More complicated to coordinate, but thread safe.

There are a few ways we could attack the second option; all of these require some way to start the main isolate if it's not already running.

1. Devise a way to check that we're the only running isolate - if so, register whatever plugin we want and run it.  If not, "wake up" the main isolate and send a message to it to run the plugin code.
1. Devise a way to always forward the plugin message to the main isolate (waking it up if necessary).
1. Don't have any background isolates for "regular" Flutter apps - always have plugins run the main isolate (waking it up if necessary).

**Comment by dnfield** [comment]
I think that's a good idea for things going forward, but it doesn't really help with existing plugins today, right?

**Comment by sir-boformer** [comment]
A typical use case that I'm currently trying to implement:

APNS receives a silent notification with a content update (maybe via firebase_messaging plugin). The content is stored in a sqlite database (using the sqflite plugin) and must be updated by the headless dart code.

**Comment by xtelinco** [comment]
So I think like above, my use case is a pretty common one for flutter developers. Executing something in background without starting up all the UI infrastructure, there by keeping power / processor time to a minimum. This maybe, update sqllite, send a local notification, lookup the application directory, all things that need plugins.

I don't necessarily need do this in a separate isolate, but if I were to use the UI isolate this would need to be started in a way that doesn't start the UI initialisation. 

To use the UI isolate we would need to support, background launch - enter at a particular entry point (not main), execute a background task in the UI isolate. However we would still need to be able to initialise the UI isolate properly at a later point by executing main, on the app receiving a viewWillAppear.

I see this as being quite tricky. I think the way to do it would be some sort of messaging, and tracking whether or not the UI isolate had done its main initialisation. So the UI isolate is Run at app launch, but it doesn't do anything until it receives a message to either launch a background task, or initialise the UI. 

Whether or not this is simpler than a separate Isolate I'm not sure. However from a developer point of view it is maybe nicer, as they don't have to get their head around isolates at all.

**Comment by perezd** [comment]
> A typical use case that I'm currently trying to implement:
> 
> APNS receives a silent notification with a content update (maybe via firebase_messaging plugin). The content is stored in a sqlite database (using the sqflite plugin) and must be updated by the headless dart code.

This is 100% the use case we need to support ourselves (internal g3 customer).

**Comment by dnfield** [comment]
Would you be doing this in a customized Xcode based application, or you'd want to do this from a plugin in a simple Flutter application (where the plugin spawns the headless isolate)?

**Comment by sir-boformer** [comment]
Looking at this again, I'm not sure if there is a realistic chance to run plugins from headless code. Imagine this scenario:

The phone is booted. The Flutter application (`AppDelegate`, `MainActivity`) is not running. At this point, the plugins are not registered or registered.

The backend sends a silent push notification.

On Android, the `Application` is initialized (but not the activity). A service that extends `FirebaseMessagingService` receives the silent push notification in a (Android) background thread.

On iOS, `application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) -> Void)` is called

----

At this point I wanted to run some dart code that processes the silent notification and makes use of various flutter plugins (shared_preferences and sqflite) to update the database. 

If the main isolate was currently running, it would have been beneficial to run the code in the main isolate to prevent concurrency issues and to update the UI. If no main isolate was found, the dart code should have been run in a headless isolate.

**The problem I'm seeing is that flutter plugins are not registered at all before the application is launched by the user.**

It seems that we have to handle background updates in native code.

**Comment by dnfield** [comment]
There's nothing stopping us from registering plugins in the `application` call on iOS.  There's also no reason to think we can't either send a message to the running isolate or spin it if up if it's not running.

**Comment by dnfield** [comment]
@bkonyi , I know you've been doing more work on this lately - I don't know if March is the right bucket, but I know January isn't.  Feel free to update it if you think we're closer to having all the use cases and design work closer in than I'm aware of right now.

**Comment by matthew-carroll** [comment]
@bkonyi I would recommend de-committing this issue from any milestone given that we're still very unclear on scope.  Recently @Hixie talked about avoiding promises that we're unlikely to keep, and I think this is one such candidate.  We know we need to solve it, and we're working on it, but I'm not sure there is any month that we can confidently promise for this project.

**Comment by matthew-carroll** [comment]
👍

**Comment by cdharris** [comment]
Just chiming in with my use case that appears to require a fix for this issue. 

I'm looking for a way to upload a file (Firebase Cloud Storage) in the background.

It appears running this in an isolate would be best, but it would need access to the firestore plugins. I would pass the isolate code the userId, the file path, etc and it would do the uploading, reporting on the ongoing progress.

**Comment by hpoul** [comment]
@bkonyi i was wondering if there is any update on this issue? looking for processing background notifications and need to send out local notifications via plugin.. if this is a harder issue to fix in flutter i'd probably need to find different workarounds. thanks

**Comment by mehmetf** [comment]
Another use case from an Google customer:

> We are integrating firebase messaging and need a way to do background sync with data messages.

As an example use case we should provide guidelines to people around how to do this since we own the firebase messaging plugin.

**Comment by bkonyi** [comment]
@hpoul @cdharris, sorry for the delayed response!

I've uploaded PR flutter/engine#7843 which should make it easier to use other plugins from a background context. Once that lands, I'll be updating the background execution Medium article with an example on how to add this support to a plugin.

**Comment by hpoul** [comment]
@bkonyi thanks for that change - i guess it has not even landed on beta yet, but when do you think you could update your medium post? :-) i can't quite figure out how to use those changes to enable "background" isolates to interact with plugins. I guess this would have to be supported by the plugin starting the background job, as well as the plugins i'm using while in the background? any hints appreciated :-)

**Comment by bkonyi** [comment]
> @bkonyi thanks for that change - i guess it has not even landed on beta yet, but when do you think you could update your medium post? :-) i can't quite figure out how to use those changes to enable "background" isolates to interact with plugins. I guess this would have to be supported by the plugin starting the background job, as well as the plugins i'm using while in the background? any hints appreciated :-)

The Medium post has already been updated :) You're assumption that plugins will need to be updated to use this functionality is correct. I've updated my geofencing plugin example to utilize this change as well (see [here](https://github.com/bkonyi/FlutterGeofencing)).
