### ISSUE TITLE
type 'CupertinoActivityIndicator' is not a subtype of type 'List<Widget>'

### ISSUE THREAD

**Issue by tiankun** [flutter/flutter#21928]
type 'CupertinoActivityIndicator' is not a subtype of type 'List<Widget>'

**Comment by zoechi** [comment]
I think the error message is right ;-)

Can you please provide information about how to reproduce?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
