### ISSUE TITLE
Flutter: Keypad Number with Options not showing on Android Device, only on Emulator.

### ISSUE THREAD

**Issue by sumation** [flutter/flutter#21924]
Keypad on Emulator executes correctly, Keypad on Android device doesn't show the extended keypad, only shows number only keypad. Any ideas why would same code would execute different? 
-- Keypad on Android Device--
![screenshot_2018-09-16-17-05-05](https://user-images.githubusercontent.com/1269044/45601402-45365d80-b9da-11e8-894b-2b2a4e47db93.png)

--Keypad on Android Emulator 

![keypad](https://user-images.githubusercontent.com/1269044/45601422-6e56ee00-b9da-11e8-8f05-35dde9804557.PNG)

Code:
`   new TextFormField(
           keyboardType: TextInputType.numberWithOptions(),`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
