### ISSUE TITLE
Material Card Corners No Longer Appear

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#21926]
## Steps to Reproduce
1. Set the root Material widget's borderRadius to BorderRadius.circular(8.0)
2. No rounded corners appear.

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Material(
      borderRadius: new BorderRadius.circular(8.0),
      child: Container(
        width: double.infinity,
        height: double.infinity,
        color: Color(0xFFFFFFFF),
      ),
    );
  }
}

```

Expected: 
![maxthonsnap20180916165737](https://user-images.githubusercontent.com/19896174/45601777-f982b480-b9d7-11e8-834e-67f08faa5148.png)

Actual:
![maxthonsnap20180916165751](https://user-images.githubusercontent.com/19896174/45601780-fedfff00-b9d7-11e8-8035-3efc06641fd1.png)

**Comment by searchy2** [comment]
Problem exists on latest Dev and Master branch. Tested on Android Lollipop to Oreo.

**Comment by searchy2** [comment]
@jason-simmons Thank you so much! This works :)

**Comment by YouCii** [comment]
@jason-simmons 666

**Comment by ccornici** [comment]
I encountered a bug: I saved -> hot reload and the Clip.antiAlias did not do anything. I had to completely restart the app to see the changes, kinda bad, I thought I'm doing it wrong and searched for 30 min to find this answer and figured that it might be an actual bug, and it is. After restarting it works fine.

**Comment by liyuqian** [comment]
@ccornici : Thanks for reporting! We're sorry about the confusion. We're tracking the fix of it in https://github.com/flutter/flutter/issues/21926

**Comment by yhowwon** [comment]
@jason-simmons 牛逼👍
