### ISSUE TITLE
Android keeping the app state alive

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#21930]
When a user presses back at the root it completely closes the app (state is removed), my app needs to stay alive.

When the user presses the center button to go back to the android home screen the app is kept alive (state is in tact).

It seems the android Activity is terminated `onDestroy()` when the user presses back.

I already use a native background service (which stays alive) but the UI state is gone.

What is the right way if any to keep the app state alive when the user presses back at the root?
Other native apps seem to be able to do it but I'm not as experienced in android.

**Comment by abacaj** [comment]
probably wasn't the place to ask this, but I had to override the `onBackPressed` in android to
```
  @Override
  public void onBackPressed() {
    moveTaskToBack(true);
  }
```

**Comment by Nidhi1461996** [comment]
Bump

**Comment by tonisostrat** [comment]
@abacaj, would be nice of you to actually share the solution after you so victoriously claimed you solved it..
