### ISSUE TITLE
video player has more bug on IOS

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#21932]
![](https://img.vim-cn.com/47/9f474018e44eba3c76e802eb51e66ee7591181.jpg)

more network video can't play! When network video's url has parameter, it can't play!

I hope video player 's IOS core can change to [ijkplayer](https://github.com/Bilibili/ijkplayer)

Failure case:
http://ws4.stream.xxxx.com/xxxxlive/98095948-98095948-421318888530116608-4370637416-10057-A-0-1.flv?wsSecret=ad14e46157f1b54a0e6f4b91ff4da5d0&wsTime=5b9e513a&ratio=1200

http://ws4.streamhls.xxxx.com/xxxlive/98095948-98095948-421318888530116608-4370637416-10057-A-0-1.m3u8?wsSecret=7c1937e5a12a4a2ea82e6def4575b7ae&wsTime=0&ratio=1200

Success case:
https://youku.cdn-56.com/20180622/3878_d3968706/index.m3u8

Thanks, very much!

**Comment by yasincidem** [comment]
I think it doesn't have anything to do with parameter in url. The links in failure case are broken.  Please try out these links

https://m.ok.ru/dk/video.mp4?st.cmd=moviePlaybackRedirect&st.sig=909e373ebe7bb271a307649c683c6f89f711e458&st.mq=5&st.mvid=955361463032&st.ip=81.213.247.148&st.dla=on&st.exp=1537369985222&st.hls=off&_prevCmd=movieLayer&tkn=5769&vdsig=I-iW4aM2yzKz7ObY23nVSIfcTxE


https://n-harcourt.betterstream.co/abrplayback/4a/70/08489dd53466c90011796f69ec9c04cb5d01f363de332ef935fecb97b6fd81d66d77ea4b7a5b162a05e4b8b7ac04050a84c87d356886c59e6c97ba52b1bdf7204b6d2db65d8caee2dcc3a3a7d60fdbae289f73a2cc5172ac3ae9fce548624b6093acfc6b427abab186141736698f7d2cfe29c960d91f6e95ef677810f840c918/playlist.m3u8?q=720

**Comment by Seifon** [comment]
My links in failure case are live stream video, this url is dynamic. you get play url from this url: [https://m.douyu.com/html5/live?roomId=100](https://m.douyu.com/html5/live?roomId=100)

**Comment by Seifon** [comment]
this stream url don`s https

**Comment by Seifon** [comment]
http://pan.baidu.com/s/1dEq9q4h password: ydm7

this ios demo support flv, I hope flutter video_player' core chang to this, Thanks

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by Seifon** [comment]
> Please add the output of `flutter doctor -v`.

$ flutter doctor -v
[✓] Flutter (Channel dev, v0.8.0, on Mac OS X 10.13.1 17B1003, locale zh-Hans-CN)
    • Flutter version 0.8.0 at /Library/Java/flutter
    • Framework revision a74f591d0c (3 weeks ago), 2018-09-04 17:12:24 +0100
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Library/Java/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Library/Java/android-sdk-macosx
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.0.3
    • Dart plugin version 182.3569.4

[✓] Connected devices (2 available)
    • M10      • 0123456789ABCDEF                     • android-arm • Android 7.0 (API 19)
    • iPhone X • 5566700A-FF74-438C-962E-D203F68924C3 • ios         • iOS 11.2 (simulator)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Can you please provide links to videos that stay available?
Above links seem all to be broken.

**Comment by Seifon** [comment]
> Can you please provide links to videos that stay available?
> Above links seem all to be broken.

[
http://hdla.douyucdn.cn/live/1863767rkpl_900.flv?wsAuth=48bd60fdeeb7364f24184c257613cc82&token=app-wp-0-1863767-fcc77a20199a90fdd19abfd57e276aef&logo=0&expire=0&pt=1](http://hdla.douyucdn.cn/live/1863767rkpl_900.flv?wsAuth=48bd60fdeeb7364f24184c257613cc82&token=app-wp-0-1863767-fcc77a20199a90fdd19abfd57e276aef&logo=0&expire=0&pt=1)

this url is dynamic, sometimes it don't open.

yo can try play video by any .flv suffix.

IOS default don't support .flv video, so need some Decoder.

case : 
[https://github.com/Bilibili/ijkplayer](https://github.com/Bilibili/ijkplayer)

ijkplayer support many format

**Comment by stuartmorgan** [comment]
FLV support is out of scope for `video_player`; it is intended to provide access to the OS-provided video playback functionality. If you want to use a specific alternate player, that would be something that would need to be done via a different plugin.
