### ISSUE TITLE
PaginatedDataTable, how to beautify

### ISSUE THREAD

**Issue by NewITCorp** [flutter/flutter#21933]
Hi, 

Could you please guide  me how to beautify PaginatedDataTable?
- Column header background color
- even-odd row background color
- column text decoration (bold/italic/etc.)

thanks

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

See also #21864, #12775

If you want to request new features, please create individual more specific issues.
