### ISSUE TITLE
Document how to disable Slow Mode when running from Atom

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2193]
When running from Atom, my apps have a Slow Mode banner. Not sure how to turn this off.

Let's document how to toggle slow mode via Atom.

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew is it as simple as "click the gear in the toolbar, and change checked: true" ?

Should we rename that to "slow: true | false" ?

**Comment by Hixie** [comment]
`slow: false` sounds like it will make it fast. Which it might not. :-)

But we should have a noticeable comment that mentions "the SLOW MODE banner" and says what it means, and what toggling the option implies.

**Comment by sethladd** [comment]
> Which it might not. :-)

Good point!

**Comment by eseidelGoogle** [comment]
Part of this is that "Slow" is the wrong word.  It's really "Checked" but no one knows what that is.  We could try "Debug". :)

**Comment by devoncarew** [comment]
What about development mode (vs. deployment or production mode)? Some differences:

- development mode might run checked; production mode wouldn't
- dev might load code resources differently from production mode
- production might be AOT compiled; dev mode likely only JITed or interpreted
- dev mode would support debugging, but production mode might not

**Comment by sethladd** [comment]
Let's open a new issue. I think it's worth exploring new mental models and names for our modes.
