### ISSUE TITLE
image_picker plugin is not working with android_alarm_manager

### ISSUE THREAD

**Issue by rupert2133** [flutter/flutter#21940]
After installing `android_alarm_manager` I have an error on `image_picker` please see the link below for a detailed explanation [https://stackoverflow.com/questions/52367347/flutter-java-io-file-android-app-activity-getexternalfilesdirjava-lang-string](https://stackoverflow.com/questions/52367347/flutter-java-io-file-android-app-activity-getexternalfilesdirjava-lang-string)

**Comment by zoechi** [comment]
Merging with #21972
