### ISSUE TITLE
Animation doesn't play on the right widget when they are moved in the stack before starting the animation.

### ISSUE THREAD

**Issue by quentinleguennec** [flutter/flutter#21945]
## Steps to Reproduce
1. Create a Stack of Stateful widgets each one having an AnimationController, a GestureDetector and a VoidCallback. 
2. Have the GestureDetector send the VoidCallback when any of the the wigdets is tapped. The VoidCallback triggers a rebuild of the Stack (`setState`) with the widgets reordered to have the tapped widget at the bottom of the stack (last item) in order to have it draws on top of all the other widgets in the Stack.
3. After sending the VoidCallback, the GestureDetector calls `forward()` on the AnimationController.
4. Notice how the widget that animates is not the one that was tapped. Instead, it's the one just after.

Hypothesis: The AnimationController and the Stack are somehow using the position of the widget in the Stack to play the animation. But they are not taking the reordering of the Stack in consideration, effectively playing the animation on the widget that is at the position of the tapped widget before reordering.

Note: Doing step 3 before step 2 yield the same result. Tested on iOS only.

### flutter run --verbose

No exception here.

### flutter analyze

Nothing here related to the issue. 

### flutter doctor -v

```
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.7.3 at /Users/mario/dev/flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mario/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone • 995f3a6eb01e8c6c241fb5de3ea98ab82384e894 • ios • iOS 11.4.1

! Doctor found issues in 1 category.

```

**Comment by quentinleguennec** [comment]
Here is a link to a video of the issue:
https://drive.google.com/file/d/1VdkZPKc2boOIMm7Xa5T91CZL926crNGv/view?usp=sharing

When I press a message it goes at the bottom of the Stack but the one under animates instead.

**Comment by quentinleguennec** [comment]
Here is a demo app with the issue:
https://gist.github.com/quentinleguennec/45b0297247eda36fab9786155e57232f

**Comment by sigurdm** [comment]
Could it be a problem with missing keys? I have not tried your example, but that would make sense when you are reordering elements in a children-list.
https://docs.flutter.io/flutter/foundation/Key-class.html
See for example use of keys in: https://flutter.io/cookbook/gestures/dismissible/

**Comment by quentinleguennec** [comment]
Thanks @sigurdm !
That was it, I added a `UniqueKey` and now it works as expected!
