### ISSUE TITLE
Allow multiline TextField to expand vertically to fit container

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#21943]
This is the only way I have been able to achieve this and its pretty hacky. Would be nice if TextFields were able to expand vertically to fit the container.

```dart
Container(
  margin: EdgeInsets.all(8.0),
  // hack textfield height
  padding: EdgeInsets.only(bottom: 40.0),
  child: TextField(
    maxLines: 99,
    decoration: InputDecoration(
        hintText: "Comment!",
        border: OutlineInputBorder(),
    ),
  ),
),
```

**Comment by lukepighetti** [comment]
![img_c9e618da70e3-1](https://user-images.githubusercontent.com/666539/45629712-fe417a00-ba64-11e8-9783-4d35fc89ea0d.jpeg)

**Comment by zoechi** [comment]
What part do you find hacky? 
How would you prefer it to be?

Please add the output of `flutter doctor -v`.

**Comment by lukepighetti** [comment]
Having to put it in a container with an arbitrary 40px padding and force it to spill by giving it a manliness of 99.

Due to the speed of flutter development my `flutter doctor -v` has changed considerably since I made this post. Sorry about that.

**Comment by zoechi** [comment]
Thanks for your update!

I don't think flutter doctor output is essential for this feature request. 
I just try to annoy people with requesting it until everyone adds it automatically everywhere ;-)

Actually `flutter doctor -v` output provides some context that is usually helpful and often essential.

**Comment by Will-W** [comment]
The user expectation is probably that you would be able to do this:

```
Column(
  children: <Widget>[
    AFixedSizeWidget(),
    Expanded(
      child: TextField(),
    )
  ],
)
```

Possibly based on implementation, you may also need `maxLines: null` or some other value. The above is how you lay out every other set of widgets in a column, it's a surprise that the TextField handles its own size and doesn't expand.

**Comment by scottwinter** [comment]
@Will-W That was my expectation/hope as well.  So now sample size is you and me :).  When doing native Android development, it's rather easy to make the textfield/textarea fill the parent dynamically and auto adjust when the keyboard opens and closes and when the device orientation changes, instead of giving it a fixed maxLines.

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/51205333/flutter-textfield-that-auto-expands-when-text-is-entered-and-then-starts-scrolli/51205467 might do what you want.

**Comment by Will-W** [comment]
@zoechi That is a solution to a separate problem (a problem I also have, and the solution that I'm using). That is about scaling the textfield differently based on amount of content. This issue is about a textfield that scales once (for a given screen size) to take up the remaining space.

E.g., you can do this:

```
Column(children: [
          Container(height: 100.0),
          Expanded(child: Placeholder())
        ])
```
100 px of the available height will be a container, and the rest will be the Placeholder. You can replace the placehold with most normal widgets, and get the same behaviour. If you replace it with a TextField, that's *not* what happens, and this is surprising.

**Comment by Will-W** [comment]
I'm sorry, the use of the word "scale" was very misleading. "Changes size" would be more appropriate.

**Comment by zoechi** [comment]
Looks like a dup of #18825, #15388

**Comment by justinmc** [comment]
Closing this with https://github.com/flutter/flutter/pull/27205.

The `expands` parameter on `TextField` will do what's desired in this issue and allow the `TextField` to be sized based on its parent.  So @Will-W's example could be achieved like this now:

```dart
Column(children: [
  Container(height: 100.0),
  Expanded(
    child: TextField(expands: true),
  )
])
```

**Comment by patelkrunal78** [comment]
To adjust the width, you could wrap your TextField with a Container widget, like so:

new Container(
width: 100.0,
child: new TextField()
)

Find Full Code At [Here](https://icetutor.com/question/how-to-update-flutter-textfields-height-and-width)

**Comment by milanpatel18** [comment]
Already Defined at https://github.com/flutter/flutter/issues/27838#issuecomment-541342145

**Comment by AshfaqAshi** [comment]
To get it like a WhatsApp textbox which increases height up to a few lines then stop,
```
ConstrainedBox(
        constraints: BoxConstraints(
          maxHeight: 100 //put here the max height to which you need to resize the textbox
        ),
child: TextField(
maxLines: null, ),
)
```

**Comment by martianvenusian** [comment]
```dart
return TextFormField(
      keyboardType: TextInputType.multiline,
      textInputAction: TextInputAction.newline,
      maxLines: 16,
      maxLength: 128,
      maxLengthEnforced: true,
      initialValue: _content,
      decoration: InputDecoration(
        labelText: 'Content',
        hintText: 'Enter contetn',
        alignLabelWithHint: true,
        labelStyle: TextStyle(fontSize: 18.0, fontWeight: FontWeight.w500),
      ),
      validator: (value) =>
          value.isNotEmpty ? null : 'content can\'t be empty',
      style: TextStyle(fontSize: 20.0, color: Colors.white),
      onSaved: (content) => _content = content,
    );
  }
```

![Simulator Screen Shot - iPhone 8 - 2020-06-25 at 03 08 54](https://user-images.githubusercontent.com/22003438/85609683-4ad1d480-b691-11ea-849f-1fe99b55dc2f.png)


![Simulator Screen Shot - iPhone 8 - 2020-06-25 at 03 09 01](https://user-images.githubusercontent.com/22003438/85609707-4efdf200-b691-11ea-8291-c509179093b7.png)

**Comment by note8g2018** [comment]
> Closing this with #27205.
> 
> The `expands` parameter on `TextField` will do what's desired in this issue and allow the `TextField` to be sized based on its parent. So @Will-W's example could be achieved like this now:
> 
> ```dart
> Column(children: [
>   Container(height: 100.0),
>   Expanded(
>     child: TextField(expands: true),
>   )
> ])
> ```

I try it, I got error

**Comment by lukepighetti** [comment]
> I try it, I got error

Please provide a code snippet for reproduction. Thanks!

**Comment by angel1st** [comment]
> 
> 
> > Closing this with #27205.
> > The `expands` parameter on `TextField` will do what's desired in this issue and allow the `TextField` to be sized based on its parent. So @Will-W's example could be achieved like this now:
> > ```dart
> > Column(children: [
> >   Container(height: 100.0),
> >   Expanded(
> >     child: TextField(expands: true),
> >   )
> > ])
> > ```
> 
> I try it, I got error

I suspect the error you have got is `assert`. When you use `expanded = true` both `minLines` and `maxLines` have to be `null`. All that said, the correct code snippet should be:

`TextField(expands: true, minLines: null, maxLines: null)`

**Comment by omidraha** [comment]
Sample worked codes:


```dart
Container(
            child: new TextField (
              keyboardType: TextInputType.multiline,
              minLines: 1,
              maxLines: 10,
              decoration: new InputDecoration(
                  border: new OutlineInputBorder(
                    borderRadius: const BorderRadius.all(
                      const Radius.circular(10.0),
                    ),
                  ),
                  filled: true,
                  hintStyle: new TextStyle(color: Colors.grey[800]),
                  hintText: "Type in your text",
                  fillColor: Colors.white70),
            ),
            padding: new EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 16.0),
          );
```


```dart
TextField(
    maxLines: null,
    keyboardType: TextInputType.multiline,
) 
```
Links: [1](https://stackoverflow.com/a/65377995), [2](https://stackoverflow.com/a/60985705).
