### ISSUE TITLE
Provide RegEx library that matches characters that can be displayed by Flutter

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#21942]
Flutter is unable to properly render Emojis across platforms. I am not sure if this problem exists for other characters, but until Emoji's are supported by Flutter it would be very helpful to have a RegEx library included that matches characters that are supported across all Flutter installs.

Or provide a text formatter that doesn't display the dreaded box so these characters fail gracefully.

**Comment by zoechi** [comment]
Can you please provide a concrete emoji example that doesn't work across platforms.

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Looks like a dup of #16702 #16660

**Comment by lukepighetti** [comment]
Any skin color or flag emoji

**Comment by GaryQian** [comment]
We have since improved emoji support. Please let me know if you are still having issues with emojis. I will close this now.
