### ISSUE TITLE
Splash screen on iPhone X displays a white block briefly 

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#21947]
This may be an issue with Skia engine when launches the app on iPhone X (at least, seems the only device affected so far). 

**Steps to reproduce:**
1. Add a splash screen to the iPhone X in the Xcode project (with the correct dimension).
2. Launch the app, it will first display it full screen and then, right before rendering the first screen, it crops to half of the screen and the other half is blank.

**Comment by zoechi** [comment]
Looks like a dup of #20827 to me
