### ISSUE TITLE
Apple is rejecting flutter apps, throwing "Missing Purpose String in Info.plist File" for permissions the app is not using

### ISSUE THREAD

**Issue by manuelgomes2** [flutter/flutter#21941]
After upgrading to flutter v.0.8.4, apple is rejecting our binaries. We are receiving an email message from apple with the message below.

The problem is that all the APIs indicated are not being used by our app:  
`NSContactsUsageDescription, NSCalendarsUsageDescription, NSAppleMusicUsageDescription(!), NSMotionUsageDescription, NSSpeechRecognitionUsageDescription`. 

We have published this app before, and the new binary has only minor corrections from the previous app, except for the flutter upgrade (0.5 to 0.8, dev channel).

Are these APIs being referenced by flutter in all builds? 

------------  message sent by apple when rejecting the binary ----------
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 

---- our current flutter doctor output ---
```
[✓] Flutter (Channel dev, v0.8.4, on Mac OS X 10.13.3 17D102, locale pt-PT)
    • Flutter version 0.8.4 at /Users/manuelgomes/development/flutter
    • Framework revision 7f7a731da0 (3 days ago), 2018-09-14 13:11:32 -0400
    • Engine revision 7a9b430d74
    • Dart version 2.1.0-dev.4.0.flutter-c28db2d6e1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available
```

**Comment by lukepighetti** [comment]
I have noticed that the Flutter plugins written by the Flutter Team take a broad brush approach to user permissions (hi, Google!) which does NOT jive with iOS ecosystem. Some of us have asked them to not include permissions in their libraries (eg, `image_picker`) so that we can cherry-pick exactly what permissions we need.

Hopefully someone from the team will read this and seriously consider the implications of broad-brush permissions at the library level. 

In the meantime, you can add the description yourself. I had to do this for camera access even though I never used camera access. (I was picking from the photo library.)

**Comment by manuelgomes2** [comment]
So, i have to make up some bogus reason why my app needs access to Apple Music.... Anyway, thank you for your reply, i only needed confirmation. BTW: do you know how can i check which libraries are requiring which permissions?

**Comment by manuelgomes2** [comment]
I have found, in my case, what is causing the problem: the package "permission_handler" - it is not required by my app directly, but the package "geolocator" requires it...

**Comment by lukepighetti** [comment]
Yeah, that's a perfect example. Unfortunately I think this is a Flutter culture thing. I hope the community will right this misguided way of handling permissions.

**Comment by dnfield** [comment]
Can you provide a list of plugins you're using?

**Comment by dnfield** [comment]
Also, if you're finding that a particular plugin is requesting permissions you don't think it needs, please feel empowered to open an issue in the appropriate repo (here if it's in flutter/plugins, or the specific repo if it's a 3rd party plugin).

Unfortunately, it's sometimes difficult to figure out what permissions a plugin requires.  It should be documented, but it isn't always documented well.

If [this](https://github.com/baseflowit/flutter-geolocator) is the plugin requiring these permissions, you may want to open an issue there (if one isn't already) - their documentation doesn't seem to indicate that they're using those permissions. 

If a flutter upgrade caused this, it's likely because you're pulling in a newer/later version of that plugin since you upgraded flutter.

**Comment by miyoyo** [comment]
I understand that plugins might _need_ a permission, but I don't agree with users not being able to control the rest, I much prefer having to do setup and reduce magic than having magic and not being able to get rid of it.

**Comment by swavkulinski** [comment]
We have encountered this when using https://pub.dartlang.org/packages/simple_permissions . Plugin references a number of permissions that we actually don't use. However App Store team raised this as an issue. For now we have added strings (which will never be used) but we are planning come up with a suit of plugins that treat each permission separately to avoid being flagged.

**Comment by dnfield** [comment]
I'm starting to suspect there's some misunderstanding out there about how permissions work on mobile devices...  Some of you posting here may know this, but just to clarify for everyone:

- You cannot "check" or "request" many permissions without explicitly warning that your app may need those permissions in your plist/AndroidManifest.  If you try, your app will crash (assuming it can even get through the Store's filtering process in the first place).
- If you add a plugin that can test/check many permissions for you, __your app will appear to require those permissions in at least some paths, even if you have no intention of ever using them__.  This is true even if the offending plugin is a transitive dependency.
- From a store and user perspective, your app needs to declare that it might access certain APIs that allow it to control hardware or access information users might not want you to have (e.g. contacts, camera, location, etc.).  This is true even if your app never actually executes the code that calls that API (even if the code is a dead path - and note, it's not Dart code so it doesn't get shaken out).

The community has done a lot of great work around developing and offering plugins, and the Flutter team is also working hard to make sure there are some excellent first party options.  That said, people make mistakes and may have made choices that are aggressively seeking unnecessary permissions.  The issues being raised here seem to have to do with specific plugins requiring unexpected permissions.  __That should be raised in the proper repository for that plugin, so the maintainers can address it.__  If you're seeing that with a plugin from https://github.com/flutter/plugins, this is the right place to raise it - but please indicate which plugin it is!

**Comment by lukepighetti** [comment]
To have the permissions added by the user, not the package.

**Comment by dnfield** [comment]
Sticking with the Image Picker - let's say you decide you want to use `image_picker`, but don't want to allow users to pick from their camera, so you try to avoid having that in your plist and only add the Photos access.  And let's say you remove the asserts from the code to make it all compile.  User taps "pick image" and then taps "camera" and your app crashes, which is why Apple will reject your app (it will run code analysis and see that code is there, regardless of whether you use it intentionally or not).

If you're looking for an ImagePicker that doesn't access the camera, you'd need to use completely different code from what the `image_picker` plugin (and you can't use the built-in native `UIImagePickerController` for it, since that requires camera permissions).  In fact, if that's really all you want you could probably build it up in Dart (from what I understand, half the reason for the `image_picker` plugin is to allow native access to the camera, which users may well expect since that's how image picking works in many apps).

I completely agree that a plugin should not be requiring more permissions than it actually needs.  However, it's also possible that a plugin has code for features you don't intend to use - _but it will still need permissions for those features because the code will still be present in the app you send to the store_. And if you're finding plugins that require arbitrary permissions simply to check if the app has access to those permissions, I'd avoid using that plugin completely.

**Comment by lukepighetti** [comment]
@dnfield I don't know what to say at this point. Your understanding of ImagePicker on iOS is simply wrong. You can pick files without accessing the camera.


Here is ImagePicker on iOS being called with 

```
File image = await ImagePicker.pickImage(
      source: ImageSource.gallery,
      maxHeight: 240.0,
      maxWidth: 240.0,
    );
```

And here you can see there is no way to pick from the camera.

![screenrecording_09-20-2018 15-57-57 2018-09-20 15_59_59](https://user-images.githubusercontent.com/666539/45843796-89817080-bcee-11e8-9827-e0bc0f02233e.gif)


And this problem exists for me on Android as well,

here is where `image_picker` forces three permissions when all I need is one

https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/AndroidManifest.xml#L3-L5

**Comment by zoechi** [comment]
I think a solution could be to create smaller composable plugins instead of swiss army knife plugins.
In case of the image picker I think this would be quite advantageous because one plugin could allow access to camera another to photo gallery, ... and then the UI could be built in Dart instead of depending on the provided UI as it is now.
Each plugin would then only depend on a small set of (or a single) permissions.

**Comment by HerrNiklasRaab** [comment]
The solution to this is still providing, "fake" description despite the fact, those permissions are not used in any way, right?

To depict the problem, to the flutter team, this is the rejection i get from the appstore, but I am not using any of those permissions:

> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSSpeechRecognitionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by dnfield** [comment]
The way to solve it is to just add the strings.

More composable plugins is a good idea though.

**Comment by collinjackson** [comment]
Trying to triage this issue, it's not clear to me that it's actionable at this time.

It's possible that the image_picker could be refactored into multiple plugins, and we could create a separate issue to track that.

**Comment by lukepighetti** [comment]
@dnfield A few months later, I am now a *little* bit wiser 🤭, and I wanted to ask a clarifying question!

If I understood you correctly even dead code needs the permissions and you'd have to refactor `image_picker` into `image_file_picker` and `image_camera_picker` to split up the permissions.

I have heard people say that Apple crawls the binary as part of the review process, but I've never seen anything to back up that claim.

Does Dart do tree shaking to the point where this dead code would be removed automatically? 

Hoping for some clarification on the blockers to a-la-carte permissions.

(And sorry for my horrible tone earlier in the thread.)

**Comment by dnfield** [comment]
I'm almost certain apple checks your binary.

Unfortunately, no amount of dart tree shaking would fix this because the code apple sees using the permissions is Objective C or Swift.

**Comment by lukepighetti** [comment]
Thanks @dnfield , if this were my issue I would close it. Appreciate all the hard work you guys invest in these plugins for us to use.

**Comment by iskakaushik** [comment]
Closing this issue as there does not seem to be anything actionable here.

**Comment by MarcelEdward** [comment]
When some strings are required for the acceptance of apple then those should be in the info.plist by default I think.

**Comment by AndroidNils** [comment]
I have the same problem... Why needs the plugin so much access to the personal data? I have to add these strings:

- NSAppleMusicUsageDescription
- NSCameraUsageDescription
- NSMicrophoneUsageDescription
- NSPhotoLibraryUsageDescription
- NSContactsUsageDescription
- NSCalendarsUsageDescription
- NSMotionUsageDescription
- NSSpeechRecognitionUsageDescription
- NSLocationAlwaysUsageDescription
- NSLocationWhenInUseUsageDescription

Really? I mean for normal file or image picker...

**Comment by vladaman** [comment]
Got same problem. Rejected by App Store. List of plugins:

dependencies:
  flutter:
    sdk: flutter

  location: ^2.3.5
  permission_handler: ^3.1.0
  cupertino_icons: ^0.1.2
  firebase_messaging: ^5.0.2
  shared_preferences: ^0.5.3+1
  flutter_webview_plugin: ^0.3.5
  flutter_local_notifications: ^0.7.1+1
  firebase_analytics: ^3.0.2

**Comment by smile921** [comment]
Got this problem too . So from the dissguss above , we have nothing to do except  just make up some bogus reason to pass the check

**Comment by nws-jstorm** [comment]
> Got this problem too . So from the dissguss above , we have nothing to do except just make up some bogus reason to pass the check

I added messages like in short "You should never see this, please contact us". So you can know, if one of your plugins really use this permission in future.

**Comment by lukepighetti** [comment]
The more I use Flutter the less I advocate for community cross-platform packages. It's not anyone's fault, it's just the way these things are structured.

**Comment by ZHanOBa** [comment]
I had the same problem,
I'm trying to configure all the permissions that apple pointed out into the project info.plist,
Then submit the application again

**Comment by Tahaan** [comment]
My app has been rejected despite having a "placeholder reason" string for Apple Music. 

The Reject explanation has a screenshot of where the app is requesting access to Apple Music. This is weird - I don't actually use Apple music so I don't know how they managed to do that.

The explanation is basically that the "Reason string" does not explain to the user why the app needs access to Apple Music.  Which the app doesn't - of course.

I will find another plugin that checks only the permissions that my app only needs.

**Comment by amenk** [comment]
Is there a "simple" way to see which of the packages / plugins an app uses requires which permissions?

**Comment by aravindhkumar23** [comment]
I am also facing the same issue 

my package includes
  ```
flare_flutter: ^1.8.3
  shared_preferences: ^0.5.6
  connectivity: ^0.4.6+1
  scoped_model: ^1.0.1
```

and mail from apple 
```

ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

```
any workaround to fix the warning?

**Comment by amenk** [comment]
@aravindhkumar23 As you asked for a workarkound: That one worked for me: https://github.com/flutter/flutter/issues/21941#issuecomment-536444558

**Comment by amit-onappr** [comment]
Check if you are using permission handler package. If you have explicitly set the permissions you don't need for your app in Podfile. 

https://github.com/Baseflow/flutter-permission-handler#android-and-ios-specific-permissions

IMPORTANT: On iOS you will have to include all permission options when you want to submit your App. This is because the permission_handler plugin touches all different SDKs and because the static code analyser (run by Apple upon App submission) detects this and will assert if it cannot find a matching permission option in the Info.plist. More information about this can be found here.

On iOS, the permission_handler plugin use macros to control whether a permission is supported.

By default, all the permissions listed here are supported.

You can remove permissions you don't use by:

Add the following to your Podfile file:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      ... # Here are some configurations automatically generated by flutter

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',
       
        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0'
      ]

    end
  end
end

**Comment by adityadroid** [comment]
> Check if you are using permission handler package. If yes then you have to explicitly set the permissions you don't need in your app in the **Podfile**.
> Don't forget to run the command `pod install` after updating Podfile
> [https://github.com/Baseflow/flutter-permission-handler#android-and-ios-specific-permissions ](https://github.com/Baseflow/flutter-permission-handler#android-and-ios-specific-permissions)
> IMPORTANT: On iOS, you will have to include all permission options when you want to submit your App. This is because the permission_handler plugin touches all different SDKs and because the static code analyser (run by Apple upon App submission) detects this and will assert if it cannot find a matching permission option in the Info.plist. More information about this can be found here.
> 
> On iOS, the permission_handler plugin uses macros to control whether permission is supported.
> 
> By default, all the permissions listed here are supported.
> 
> You can remove permissions you don't use by:
> 
> Add the following to your Podfile file:
> 
> post_install do |installer|
> installer.pods_project.targets.each do |target|
> target.build_configurations.each do |config|
> ... # Here are some configurations automatically generated by flutter
> 
> ```
>   # You can remove unused permissions here
>   # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/ios/Classes/PermissionHandlerEnums.h
>   # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
>   config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
>     '$(inherited)',
> 
>     ## dart: PermissionGroup.calendar
>     # 'PERMISSION_EVENTS=0',
> 
>     ## dart: PermissionGroup.reminders
>     # 'PERMISSION_REMINDERS=0',
> 
>     ## dart: PermissionGroup.contacts
>     # 'PERMISSION_CONTACTS=0',
> 
>     ## dart: PermissionGroup.camera
>     # 'PERMISSION_CAMERA=0',
> 
>     ## dart: PermissionGroup.microphone
>     # 'PERMISSION_MICROPHONE=0',
> 
>     ## dart: PermissionGroup.speech
>     # 'PERMISSION_SPEECH_RECOGNIZER=0',
> 
>     ## dart: PermissionGroup.photos
>     # 'PERMISSION_PHOTOS=0',
> 
>     ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
>     # 'PERMISSION_LOCATION=0',
>    
>     ## dart: PermissionGroup.notification
>     # 'PERMISSION_NOTIFICATIONS=0',
> 
>     ## dart: PermissionGroup.mediaLibrary
>     # 'PERMISSION_MEDIA_LIBRARY=0',
> 
>     ## dart: PermissionGroup.sensors
>     # 'PERMISSION_SENSORS=0'
>   ]
> 
> end
> ```
> 
> end
> end

The permission handler ENUM class has now been moved to:
https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h

**Comment by egorges** [comment]
Flutter compiler won't be able to identify dead code that could be used (changing a parameter, for example).

I would suggest:
1) plugins must explicitly document their requested services;
2) plugins could encapsulate the optional services iwith a standard pattern like "**if (kPurposeLocationAlwaysUsage)**" the same way we may use "if (kDebugMode)". This way we could replace 1 plugin line with "**static const kPurposeLocationAlwaysUsage = false**" and Flutter compiler would remove the dead code - and no permissions would be needed;
3) Flutter Team _must_ include in release build standard checks for the required services. We should not be surprised by Apple review something we must adhere to on build time.

**Comment by muzi131313** [comment]
I have the same issue when upload to the appstore for the TestFlight version, After I handled the permission of [permission_handle](https://pub.dev/packages/permission_handler) plugin, there still tell me I used location permission.
Finally I found that was [connectivity](https://pub.dev/packages/connectivity) plugin asked the location permission.
![image](https://user-images.githubusercontent.com/2398149/90360531-889a1a80-e08e-11ea-8942-465ba786fe46.png)

**Comment by halvorsen** [comment]
same issue as muzi131313, resolved this two weeks ago in a app submission by adding these to the list:        'PERMISSION_GROUP_LOCATION_ALWAYS=0',
'PERMISSION_GROUP_LOCATION_WHEN_IN_USE=0',
however, created a new binary today and I have muzi's issue again.

**Comment by jdeltoft** [comment]
I too had permission_handler in my pubspec.yaml but I didn't recall why and was able to remove it without issue.  I then was only required to add the real permissions I needed for the app.
