### ISSUE TITLE
Flutter CLI ignores format of flavors and dimensions, making it impossible to run 

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#21959]
I have a Flutter app, and on the Android side, I define, as flavorDimensions: brand and region, and then I have the usual build types: debug and release.

Let's say my brands are "brandLight" and "brandDark", and mi regions are "northAmerica" and "spain".

From the CLI, if I want to build brandLight-northAmerica-debug, I should run:

```
flutter run --flavor brandLightNorthAmerica --debug
```

However, that command generates:
```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    0.9s
Running 'gradlew assembleBrandlightnorthamericaDebug'...            1.7s
Gradle build failed to produce an Android package.
```

As you can see, it tries to run `gradlew assembleBrandlightnorthamericaDebug`, and that's where the run command fails.

Is there an alternative to fix this, or is it a real bug?

**Comment by zoechi** [comment]
#19507 might be related

Please add the output of `flutter doctor -v`.

**Comment by jorgecoca** [comment]
```
➜  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
[✓] VS Code (version 1.27.2)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.```

**Comment by jorgecoca** [comment]
@zoechi I believe #19507 might be the same issue, so feel free to close this one if necessary.

Thanks!

**Comment by zoechi** [comment]
Thanks for the update.
Closing as dup of #19507
