### ISSUE TITLE
Flutter should provide the way to pop to root for CupertinoTabBar

### ISSUE THREAD

**Issue by TJ543** [flutter/flutter#21956]
Hi, I've been enjoying flutter very much so far.  However there is one thing annoying me a little which is `CupertinoTabBar`. 

`CupertinoTabBar` doesn't provide the way go back to root page of the current index when a tab tapped. Let's say for example in Instagram, there is feed and if you tap user's icon, navigate to the user profile page and be able to see previous posts. Then, if you tap the feed icon (which is tab index 0), go back to the first feed page. It might not be expected behavior in Android. But this is helpful when you push multiple pages and did some action like follow unfollow, but no need go back to the previous page. Especially, for iPhone users. I'm using iPhone and this kind of behavior is pretty weird and not great UX. Does this make sense? I have been searching this solution but couldn't find it. If there is the way already, sorry and please tell me where I can find it.

**Comment by TJ543** [comment]
Thank you for replying. 
This is the `CupertinoTabBar` from `flutter` example 

`class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => new _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final List<StatelessWidget> pages = [
    new Page1(),
    new Page2(),
    new Page3(),
    new Page4(),
  ];

  @override
  Widget build(BuildContext context) {
    return new WillPopScope(
      onWillPop: () async {
        await Future<bool>.value(true);
      },
      child: new CupertinoTabScaffold(
        tabBar: new CupertinoTabBar(
          iconSize: 35.0,
          activeColor: Colors.black,
          inactiveColor: Colors.grey,
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.looks_one),
              title: Text('Page1'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.looks_two),
              title: Text('Page2'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.looks_3),
              title: Text('Page3'),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.looks_4),
              title: Text('Page4'),
            ),
          ],
        ),
        tabBuilder: (BuildContext context, int index) {
          return new DefaultTextStyle(
            style: const TextStyle(
              fontFamily: '.SF UI Text',
              fontSize: 17.0,
              color: CupertinoColors.black,
            ),
            child: new CupertinoTabView(
              routes: <String, WidgetBuilder>{
                '/Page1': (BuildContext context) => new Page1(),
                '/Page2': (BuildContext context) => new Page2(),
                '/Page3': (BuildContext context) => new Page3(),
                '/Page4': (BuildContext context) => new Page4(),
              },
              builder: (BuildContext context) {
                return pages[index];
              },
            ),
          );
        },
      ),
    );
  }
}`

And if you push a couple of times like so,

`class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: new Text('Page1'),
          leading: new IconButton(
            icon: new Icon(Icons.text_fields),
            onPressed: () {
              Navigator.of(context)
                  .push(MaterialPageRoute(builder: (context) => Page5()));
            },
          )),
      body: new Center(
        child: new Text('Page1'),
      ),
    );
  }
}

class Page5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: new Text('Page1'),
          actions: <Widget>[
            new IconButton(
            icon: new Icon(Icons.text_fields),
            onPressed: () {
              Navigator.of(context)
                  .push(MaterialPageRoute(builder: (context) => Page6()));
            },
          )
          ],
      ),
      body: new Center(
        child: new Text('Page5'),
      ),
    );
  }
}

class Page6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: new Text('Page1'),
          actions: <Widget>[
            new IconButton(
            icon: new Icon(Icons.text_fields),
            onPressed: () {
              Navigator.of(context)
                  .push(MaterialPageRoute(builder: (context) => Page6()));
            },
          )
          ],
      ),
      body: new Center(
        child: new Text('Page6'),
      ),
    );
  }
}`

Then if you want to go back to `Page1` you have to tap twice left-upper arrow which is `leading` in `AppBar`. But in native iOS development if you tap first tab icon which is this
`  BottomNavigationBarItem(
              icon: Icon(Icons.looks_one),
              title: Text('Page1'),
    )`

Then pop to `Page1` without tap button twice and since I couldn't find this property, I thought flutter should provide this.
Does this make sense? 
Thank you for your help I really appreciate it.

**Comment by zoechi** [comment]
I still don't understand what exactly you try to accomplish.
The way you are mixing tabs with page navigation is especially confusing to me. 
I don't know iOS native development can can't translate how you would do it in Flutter.

I'd suggest to ask in one of the other channels listed at http://flutter.io/support .
GitHub is for bug reports and feature requests.

The code I used (fixed some errors from above fragments) can be found https://gist.github.com/zoechi/0ba9fc507359e48bb3e9f2eed7507860
