### ISSUE TITLE
Support RichText in finders

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#21961]
Internal: b/193847760

Let's make this test pass:

```dart
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(body: RichText(text: TextSpan(text: "MyRichText"))),
    ));
    expect(find.text("MyRichText"), findsOneWidget);
```

**Comment by jonahwilliams** [comment]
I think we should expose this as find.richText or a named argument to find.text, otherwise we will always find two widgets in the case of a regular text.

```
find.richText('asdas');
// Or
find.text('asadass', rich: true); // only looks at rich text instances.
```

Thoughs @mehmetf?

**Comment by mehmetf** [comment]
Could we try to be clever about this and just have find.text support RichText somehow? Reasons for pushing that direction:

- I can imagine this causing some confusion when testing. E.g. you change from Text to RichText w/o changing content and finders start failing.
- `find.text` is currently for many more things than just Text widget. For instance, you can find an AppBar title with it. So our users are already accustomed to being able to find any text that can see on screen.
- This kind of api change would need to spread to driver tests too.

**Comment by jonahwilliams** [comment]
That is a good point - I think we can handle this case just by skipping it if the parent element is a Text widget.

**Comment by jonahwilliams** [comment]
My implementation caused some issues in g3 tests, will take a look and update.

**Comment by lilyzq** [comment]
Does SerializableFinder in flutter driver support RichText now?

**Comment by stevenspiel** [comment]
I am not having any luck with it on `stable`

**Comment by gepd** [comment]
is there a workaround for this? currently doesn't seem to have any easy way to get the text

**Comment by Xavjer** [comment]
This should be fixed with https://github.com/flutter/flutter/pull/48809

**Comment by iqbalmineraltown** [comment]
will this support for finding combined text `children` from `TextSpan` via flutter driver?

or they should be checked separately for each child?

**Comment by TahaTesser** [comment]
Hi @mehmetf 
Do you think this issue still valid?
Thank you

**Comment by mehmetf** [comment]
I believe so. flutter_driver != flutter widget tester. Seems like we currently support it in driver but not widget tester.

**Comment by rumithrasena** [comment]
Hi, 
expect(
  find.byWidgetPredicate((Widget widget) =>
      widget is RichText &&
      widget.text.toPlainText() == 'textToCompare'),
  findsOneWidget,
);
I have tried this code and it says "byWidgetPredicate" method is not define. 
![image_2020_06_25T12_12_32_616Z](https://user-images.githubusercontent.com/59366725/85734862-f7a46400-b71a-11ea-90dc-d753724f3cbe.png)

**Comment by mehmetf** [comment]
I know that this is a P4 for now but the current favorite customer workaround for this is to use a protected method from `InlineSpan`. :-/

```dart
  @protected
  void computeToPlainText(StringBuffer buffer, {bool includeSemanticsLabels = true, bool includePlaceholders = true});
```

**Comment by mehmetf** [comment]
Ah, I did not see `toPlainText`. That'll do.

**Comment by neiljaywarner** [comment]
@mehmetf  what do you think of this ? How do we tap on something embedded in it?

  https://stackoverflow.com/questions/67576361/flutter-widgettest-cannot-click-on-textspan

**Comment by neiljaywarner** [comment]
@darshankawar the workaround does _not_ work for finding a textspan as in https://github.com/flutter/flutter/issues/82853#issue-894770088 though correct?

**Comment by neiljaywarner** [comment]
@TahaTesser this says severe and the docs indicate flutter driver not recommended in fact integrated test is also brought into sdk just recently so pub.dev version is updated.

Any eta please?

**Comment by SAGARSURI** [comment]
Any update on this?

**Comment by creativecreatorormaybenot** [comment]
I have created a PR that resolves this issue by providing an optional `skipRichText` flag that can be set to false:

```dart
expect(find.text('Standalone RichText', skipRichText: false`), findsOneWidget);
```

🎉
