### ISSUE TITLE
Flutter app keep failing in my apk build

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#21962]
Initializing gradle...                                       1.1s
Resolving dependencies...                                    2.7s
Running 'gradlew assembleRelease'...                             
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
compiler message: lib/main.dart:1: Error: No 'main' method found.
compiler message: Try adding a method named 'main' to your program.
Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script '/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 428

* What went wrong:
Execution failed for task ':app:flutterBuildRelease'.
> Process 'command '/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s                                                                                                                                                               12.1s
Gradle build failed: 1

## Logs

[  +36 ms] executing: [/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [/flutter/] git log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 9f359aeee2a474fe9c565b3b59cf1d504b919b4d
[        ] executing: [/flutter/] git log -n 1 --pretty=format:%ar
[  +15 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 hours ago
[   +1 ms] executing: [/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +99 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.8.5-4-g9f359aeee
[ +504 ms] executing: /Users/test/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/test/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:11
           emulator-5556          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:13
[  +15 ms] executing: idevice_id -h
[  +49 ms] /usr/bin/xcrun simctl list --json devices
[ +145 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] /Users/test/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[ +102 ms] ro.hardware = ranchu
[   +2 ms] /Users/test/Library/Android/sdk/platform-tools/adb -s emulator-5556 shell getprop
[  +51 ms] ro.hardware = ranchu
[   +5 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[   +2 ms] Android SDK built for x86 • emulator-5556                        • android-x86 • Android 9 (API 28) (emulator)
[        ] iPhone X                  • 781DAF1A-F6B7-4DDA-90C3-416541579D07 • ios         • iOS 11.4 (simulator)
[  +16 ms] "flutter run" took 833ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:239:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:350:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:109:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
```

Analyzing ........                                         
No issues found! (ran in 2.5s)
```
```

```✓] Flutter (Channel master, v0.8.6-pre.4, on Mac OS X 10.14 18A389, locale en-US)
    • Flutter version 0.8.6-pre.4 at /flutter
    • Framework revision 9f359aeee2 (4 hours ago), 2018-09-17 13:02:34 -0700
    • Engine revision b0b19d6ce1
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/test/Library/Android/sdk
    • Android NDK at /Users/test/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Users/test/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (3 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • Android SDK built for x86 • emulator-5556                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone X                  • 781DAF1A-F6B7-4DDA-90C3-416541579D07 • ios         • iOS 11.4 (simulator)

• No issues found!
```

**Comment by ram231** [comment]
`void main()` is missing. That's the main entry point to any dart program.

**Comment by pojoba02** [comment]
But! do have void main() => runApp(new MyApp()) in my login.dart doe, which is the entry point of the app, it does debug and run well, only issue is building release apk...

**Comment by ram231** [comment]
main.dart maybe?

**Comment by pojoba02** [comment]
I still have main.dart in my lib folder, but login.dart do start the app

**Comment by dnfield** [comment]
If you want to build your release app with the main entrypoint in a file other than `lib/main.dart`, you have to do so like this:

`flutter build --target=lib/login.dart`

**Comment by pojoba02** [comment]
@dnfield when I run flutter build --target=/lib/login.dart, this the outcome

'Could not find an option named "target".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.'

**Comment by dnfield** [comment]
Hmm.. try `flutter build -t lib/login.dart`

**Comment by dnfield** [comment]
Errr, it really needs the platform your building for haha.
e.g.
`flutter build android -t lib/login.dart`

Swap android for ios if building for ios.

**Comment by pojoba02** [comment]
@dnfield is there anyway to build an app release cos this is too frustrating doe,

**Comment by dnfield** [comment]
It's `flutter build apk -t lib/main.dart` ...  sorry for the confusion here, my memory is full of holes I guess.

**Comment by pojoba02** [comment]
@dnfield. Thanks for making life awesome for me
