### ISSUE TITLE
Pub get fail on dependency with relative path

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#21978]
I have a private repo with the following structure:

```
lib/
   /backend
  my_module.dart
```

`backend` is an auto generate library from a swagger definition. So I need to specify it on my pubspec file
```
dependencies:
  backend:
    path: lib/backend
```
No compilation problem on the library itself, but once I push this on GitHub and refer my module into my app like this: 

```
dependencies:
  my_module:
    git: https://github.com/name/my_module
```

I get this error:   
```
Error on line 12, column 11: Invalid description: "lib/backend" is a relative path, but this isn't a local pubspec.
    path: lib/backend
```

I notice that pub get the following structure: 
```
my_module/
   backend/
   my_module.dart
```
Where is should be 
```
my_module/
   lib/
      backend/
   my_module.dart
```

I tried moving backend module outside of lib folder but in that case it's not even retrieve anymore... Any idea what's wrong here ?

**Comment by zoechi** [comment]
Can you not generate it into another directory outside your current projects directory?
Also why do you think you need to add it to `pubspec.yaml` `dependencies:`?

If there is no `pubspec.yaml` it is not a Dart package. 
If it's not a Dart package, there is no point in adding it to `dependencies:`.
If it's just a `xxx.dart` file, you can just import it where you need to use code it contains.
