### ISSUE TITLE
Adding comment that toggling checked is same as toggling slow mode

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2197]
The `main.yaml` launch configuration should make it more clear than `checked: false` means "disable slow mode and remove the banner".

Suggestion:

```
# Flutter launch configuration for lib/main.dart.
type: flutter
path: lib/main.dart

flutter:
  # Set this to false to disable SLOW MODE and remove the red banner from your app.
  checked: true
  debug: true
  route:
```

Open to tweaks in the wording.

**Comment by Hixie** [comment]
I'd add even more, e.g. say what "slow mode" is (that it's dart's checked mode, which turns on asserts and that this enables flutter to do significantly more work to aid in development, e.g. turning on integrity checks in the framework), and that it should only be disabled for deployment and when testing performance.

**Comment by sethladd** [comment]
How about we link to the FAQ entry? 

https://flutter.io/faq/#my-app-has-a-slow-mode-bannerribbon-in-the-upper-right-why-am-i-seeing-that

or, https://goo.gl/6jbOul

**Comment by Hixie** [comment]
Yeah that would be fine too.

**Comment by devoncarew** [comment]
FYI, the code that generates that file lives here: https://github.com/dart-atom/dartlang/blob/master/lib/flutter/flutter_launch.dart#L74.

**Comment by Hixie** [comment]
Atom isn't supported any more.
