### ISSUE TITLE
firebase_messaging v2.0.0 iOS crash on first install

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#21984]
I just upgraded to firebase_messaging v2.0.0 and now on first install I get this
```
2018-09-18 09:11:40.313952-0400 Runner[2063:37675700] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FLTFirebaseMessagingPlugin messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x60c0000294c0'
```
If I launch again it seems to load without a problem.  Has anyone seen this or know a fix for this?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by daniel-mf** [comment]
I got the same exact issue
Here's the output of `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale pt-BR)
    • Flutter version 0.8.2 at /Users/daniel/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = /Users/daniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone de John • ad4f5315fcc8daf19b1bf3f9d7eba72594ecf0f3 • ios • iOS 12.0
```

**Comment by daniel-mf** [comment]
This looks like a solution:
https://stackoverflow.com/questions/44116626/fira-appdelegate-messagingdidrefreshregistrationtoken-unrecognized-selecto/44117191
But I'm not sure how to do that on Flutter.

Could somebody please help?

**Comment by daniel-mf** [comment]
@abbadabbatech @zoechi I just fixed the issue by implementing the method `didRefreshRegistrationToken` in `FirebaseMessagingPlugin.m`

The method `didRefreshRegistrationToken` was kind of renamed to `didReceiveRegistrationToken`, you can see [here](https://github.com/firebase/firebase-ios-sdk/blob/ea4c8c7677112a0212d46b05e3f2a30e2753a8a8/Firebase/Messaging/CHANGELOG.md#2018-05-08----v300)

The flutter plugin `firebase_messaging` was already updated to use the renamed method, but I think the `Firebase/Messaging` dependency is old and still requires `didRefreshRegistrationToken`

Anyway, as a workaround I implemented the old method `didRefreshRegistrationToken` as a copy of the new one.

**Comment by cyanglaz** [comment]
@abbadabbatech Do you still experience issue on this?

**Comment by kroikie** [comment]
@abbadabbatech

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/657. Any further collaboration will be done there.
