### ISSUE TITLE
Turn examples/resolution_awareness.dart into an automated test

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#2198]
See https://github.com/flutter/flutter/pull/2190

**Comment by Hixie** [comment]
@krisgiesing Do you have an ETA on this one?

**Comment by krisgiesing** [comment]
I can work on it today and tomorrow if it's important, I wasn't sure of the urgency of this.

**Comment by Hixie** [comment]
that'd be great. We'd like to clean up the directory structure.

**Comment by krisgiesing** [comment]
Will do.

**Comment by krisgiesing** [comment]
This is in progress; I need to do some minor refactoring so that I can mock properly.
