### ISSUE TITLE
MuMu emulator - flutter run Error while initializing the Dart VM: SSE2 is required

### ISSUE THREAD

**Issue by gwhzh21** [flutter/flutter#21988]
1.win10
2.
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (3 weeks ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
3.mumu 模拟器
4.flutter create newproject 
5.cd newproject
6.flutter run

F/flutter ( 1645): [FATAL:flutter/runtime/dart_vm.cc(445)] Error while initializing the Dart VM: SSE2 is required.

**Comment by xkrumeng** [comment]
me too

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by werfei** [comment]
![default](https://user-images.githubusercontent.com/18606985/46009085-03e83100-c0f1-11e8-9281-3e1f53e4d9e5.png)

**Comment by zoechi** [comment]
@werfei What is `MuMu` in `Connected devices`?
Is this some emulator? Which one?
Is this happening with real devices as well?

**Comment by werfei** [comment]
mumu emulator 
Only the emulator has this problem.

**Comment by werfei** [comment]
I don't have x86 real devices

**Comment by ieras** [comment]
> 1.win10
> 2.
> Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision [3b309bd](https://github.com/flutter/flutter/commit/3b309bda072a6b326e8aa4591a5836af600923ce) (3 weeks ago) • 2018-08-28 12:39:24 -0700
> Engine • revision af42b6dc95
> Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282
> 3.mumu 模拟器
> 4.flutter create newproject
> 5.cd newproject
> 6.flutter run
> 
> F/flutter ( 1645): [FATAL:flutter/runtime/dart_vm.cc(445)] Error while initializing the Dart VM: SSE2 is required.

Me Too!but my Flutter sdk version is 0.94.

**Comment by ieras** [comment]
➜  ~ flutter doctor -v
[✓] Flutter (Channel dev, v0.9.4, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.9.4 at /Users/mampod/Documents/product/client/flutter
    • Framework revision f37c235c32 (2 days ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/mampod/Documents/product/client/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mampod/Documents/product/client/AndroidSDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (2 available)
    • MuMu     • emulator-5554                        • android-x86 • Android 4.4.4 (API 19)
    • iPhone 8 • EB534312-FC79-44F2-8BAB-E8A3031246A2 • ios         • iOS 11.4 (simulator)

• No issues found!

**Comment by ieras** [comment]
Platform android-28, build-tools 28.0.3
我想知道 这个 应该怎么改？

**Comment by DaZiYuan** [comment]
> @werfei What is `MuMu` in `Connected devices`?
> Is this some emulator? Which one?
> Is this happening with real devices as well?

Mumu emulator official site http://mumu.163.com/
encountered same issue

**Comment by kangwang1988** [comment]
@DaZiYuan 
See https://developer.android.com/ndk/guides/abis
![image](https://user-images.githubusercontent.com/817851/52518833-5d11c500-2c8c-11e9-9117-faac7701cd24.png)
It seems for a X86 emulator(Mumu), it's expected to have SSE2 support.
Can you check if this issue can be reproduced using an officially supported x86(API 19) simulator from Android Studio?

**Comment by DaZiYuan** [comment]
officially simulator from Android Studio works fine, I have already uninstall Mumu 😄

**Comment by kangwang1988** [comment]
@DaZiYuan 
I'm closing this issue now. Feel free to comment below, and we'll reopen it when needed.

**Comment by zhangyanling77** [comment]
i have the same problerm! help~
$ flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at D:\fluttersdk\flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\wb-zyl537012\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\wb-zyl537012\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • MuMu • 127.0.0.1:7555 • android-x86 • Android 6.0.1 (API 23)

• No issues found!

**Comment by zhangyanling77** [comment]
> Platform android-28, build-tools 28.0.3
> 我想知道 这个 应该怎么改？
我也想知道了，请问您解决了吗

**Comment by jp1017** [comment]
@zoechi Same issue
