### ISSUE TITLE
VM intermittently crashes upon disconnection from Observatory

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#21981]
I'm not sure if this belongs in sdk, but while working on flutter/devtools I've noticed some intermittently, the VM on the device will crash when I hit Reload on the browser (which has a ws connection open to the VM on the device).

It's possible to repro without flutter/devtools by just opening Observatory in your browser and hitting reload a few times. 

1. `flutter run -v` in a console
2. Wait for `An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:59279/`
3. Copy and paste this url into your browser to load Observatory
4. Hit reload on your browser repeatedly (it doesn't need to be particularly fast)
5. Observe Flutter app vanish from the device and `flutter run` terminates:

```
[        ] An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:60056/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+14348 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
```

I'm hitting this using macOS on the iOS Simulator running the `flutter_gallery` example app (using `master` code from today).

**Comment by devoncarew** [comment]
cc @a-siva - it looks like the VM will sometimes crash when it loses the connection to a service protocol client

**Comment by DanTup** [comment]
Duplicate of #26241.
