### ISSUE TITLE
Loaded scripts issue?

### ISSUE THREAD

**Issue by haoguo** [flutter/flutter#21993]
Hi all, 
I found something strange on my application.
In my entry point file (**main.dart**) I have class A like
``` dart
class A extends StatelessWidget {
  static final GlobalKey _globalKey = GlobayKey(debugLabel: 'blahblah');
  
  @override
  Widget build(BuildContext context) {
     return Navigator(key: _globalKey.......something else);
  }
}
```
And in my another file **b.dart** I have import the main.dart. But found the _globalKey has been initialized again and it's not the same with the rendered one.
Then I moved the code above to a new single file and import it in **main.dart** and **b.dart**. There are only one _globalKey at this time. So I can use it to do things I want.

I guess maybe the entry point file maybe not recorded in the loaded scripts so the vm load it again? Hope someone else can help me about this.

**Comment by zoechi** [comment]
> I have import the main.dart

Don't import that from from other files.
Instead move the code to another file and import it into `lib/main.dart` and other files if needed.

Also don't use relative imports in `lib/main.dart`

Closing as dup of https://github.com/dart-lang/sdk/issues/33076
