### ISSUE TITLE
Please allow the custom appbar's leading width

### ISSUE THREAD

**Issue by cgx9** [flutter/flutter#21991]
now，leading width is `kToolbarHeight`，it in material/constants.dart : `const double kToolbarHeight = 56.0`.

https://github.com/flutter/flutter/blob/262f12b4a9269a77bce499926afa681b20790d6c/packages/flutter/lib/src/material/app_bar.dart#L31

I want to show more content.it is to small.

**Comment by cgx9** [comment]
it say: The height of the toolbar component of the [AppBar], why _kLeadingWidth value equal kToolbarHeight ?

**Comment by davbaron** [comment]
I too wanted to have a wider Leading widget than the default 56. I wanted to have the word 'Cancel' presented to the user (versus the standard X icon), when using the route as a fullScreenDialog. I was able to work around this 'issue' by wrapping my leading 'Flatbutton' in an OverflowBox, with a maxWidth of 90.0.

I do not know if this 'issue' is in fact a 'bug' or a 'feature' or a 'placeholder for future functionality. I see @zoechi marked this as a 'new feature', so maybe it is something that will get addressed someday.  Thanks!

**Comment by zoechi** [comment]
Tangential related to #7330

**Comment by lifetin** [comment]
我也希望能自定宽度。
因为我要把前面放一张图片，或是自定义文 字，结果无法定义宽。

**Comment by cnsnet** [comment]
> 我也希望能自定宽度。
> 因为我要把前面放一张图片，或是自定义文 字，结果无法定义宽。

跟你一样,  我想放两个图片按钮, 结果overflow了

**Comment by yuangu** [comment]
@lifetin @cnsnet 你们后面怎么解决的？

**Comment by lifetin** [comment]
> @lifetin @cnsnet 你们后面怎么解决的？
整个title给这个了
` Widget titleBar() {
    return Row(
      children: <Widget>[
        Container(
            width: 80,
            child: GestureDetector(
              child: Text(
                AppInfo.name,
                style: TextStyle(
                  fontSize: 26,
                  color: Config.activeColor,
                  fontWeight: FontWeight.bold,
                ),
              ),
              onTap: () {
                logoClickCount++;
                if (logoClickCount % 2 == 0) {
                  Navigator.of(context).push(MaterialPageRoute(builder: (_) {
                    return TestPage();
                  }));
                }
              },
            )),
        Expanded(
          child: Container(
            height: 38,
            margin: EdgeInsets.only(top: 8, bottom: 8, left: 16, right: 8),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(16),
              color: Color(0xffeeeeee),
            ),
            child: TextField(
              style: TextStyle(
                fontSize: 16,
              ),
              controller: _controller,
              maxLines: 1,
              textInputAction: TextInputAction.search,
              decoration: InputDecoration(
                  contentPadding: EdgeInsets.symmetric(vertical: 5),
                  hintText: '选份好心礼物送给TA',
                  //  hintStyle: TextStyle(fontSize: 16),
                  border: InputBorder.none,
                  focusedErrorBorder: InputBorder.none,
                  errorBorder: InputBorder.none,
                  enabledBorder: InputBorder.none,
                  focusedBorder: InputBorder.none,
                  disabledBorder: InputBorder.none,
                  prefixIcon: Icon(
                    Icons.search,
                    color: Colors.black54,
                  ),
                  suffixIcon: Offstage(
                    offstage: isHideClearBtn,
                    child: IconButton(
                      splashColor: Colors.transparent,
                      highlightColor: Colors.transparent,
                      icon: Icon(Icons.clear),
                      color: Colors.black45,
                      onPressed: () {
                        setState(() {
                          _controller.text = '';
                          isHideClearBtn = true;
                        });
                      },
                    ),
                  )),
              autocorrect: false,
              onChanged: (String newText) {
                setState(() {
                  isHideClearBtn = newText.isEmpty;
                });
              },
              onSubmitted: (String val) {
                //todo: 提交搜索,进入搜索页面
              },
              onTap: () {
                //TODO: 提交搜索,进入搜索页面
              },
            ),
          ),
        ),
        Container(
          alignment: Alignment.center,
          margin: EdgeInsets.only(left: 8),
          child: Icon(
            Icons.camera_alt,
            color: Config.activeColor,
          ),
        )
      ],
    );
  }`

**Comment by devforey** [comment]
Is there any news about this feature?

**Comment by SinoMiles** [comment]
@devforey use title to set child widget 
```
AppBar(
        automaticallyImplyLeading: false,
        title: Row(
          children: <Widget>[
            Container(
              height: 100,
              width: 100,
              child: Image.asset(
                'assets/images/logo.png',
              ),
            ),
          ],
        )
```

**Comment by anthonysette** [comment]
This issue should be closed. For those who don't know you can use `AppBar`'s `leadingWidth` attribute to set the width of the leading widget. ie. for the cancel button you may set the leadingWidth to be around 100.

**Comment by ventr1x** [comment]
What are you talking about? AppBar does NOT have a 'leadingWidth' attribute.

**Comment by Lomski** [comment]
> Funnily enough in current Flutter you cannot even deactivate leading at all.
> "automaticallyImplyLeading: false" does still occupy the leading width, so a title Row() workaround does not work anymore.

@ventr1x you can set **titleSpacing: 0** for this case.

But it would be great to have somthing like **leadingWidth**.

**Comment by anthonysette** [comment]
@ventr1x @Lomski What version of Flutter are you running? I believe I am running Flutter's latest stable release, and although it is not in their documentation online, `leadingWidth` is an attribute of AppBar in Flutter `v1.21.0-6.0.pre.3`. Refer to this image below. Perhaps you should upgrade Flutter on your computer, or clone flutter from the git repo so you always have the latest version and can switch between different channels easily. I hope this clears up any misunderstanding.

![image](https://user-images.githubusercontent.com/34931223/90074415-28d7f400-dcc9-11ea-9e06-d2fbc7e6d668.png)

**Comment by Lomski** [comment]
```
Flutter is already up to date on channel stable
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git

```

**Comment by anthonysette** [comment]
@Lomski You are correct I am not on the stable channel, I didn't realize. However, this is good news because this means the change is coming. Also if you would like you can create your own custom AppBar based on the AppBar in the version I am running which will give you the capability you are looking for.

**Comment by TheBiirb** [comment]
@Hixie Since there is a leadingWidth property now, should we close this?

**Comment by Hixie** [comment]
I guess so! Thanks! @cgx9 let us know if that doesn't solve it!
