### ISSUE TITLE
CI: add build step to validate that pubspecs do not include dependency_overrides

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#220]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Thursday Oct 22, 2015 at 23:07 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1747_

----

We noticed that some code reviews notice that the pubspec.yaml has a dependency_override mention. Would it help to add a small step to the Travis build that fails when it notices a dependency_override in any pubspec.yaml ?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 22, 2015 at 23:25 GMT_

----

We use dependency_override in packages that we don't intend to publish to pub...  Maybe there's a better way?

**Comment by abarth** [comment]
This issue seems obsolete.
