### ISSUE TITLE
Because flutter_tools depends on file 5.0.6 which doesn't match any versions, version solving failed

### ISSUE THREAD

**Issue by naxiaoguang** [flutter/flutter#22002]
Downloading Dart SDK from Flutter engine 58a1894a1cd798de2f9a206f157a90d45944028b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93.6M  100 93.6M    0     0  1436k      0  0:01:06  0:01:06 --:--:-- 1451k
Building flutter tool...
Because flutter_tools depends on file 5.0.6 which doesn't match any versions, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

**Comment by hetian9288** [comment]
The same problem after upgrading.

**Comment by dengsgo** [comment]
+1

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified use the [Subscribe] button to the top right instead.

**Comment by yuhaocan** [comment]
![image](https://user-images.githubusercontent.com/12983937/46012850-0f415980-c0fd-11e8-9b07-f574b6e491a7.png)
+1

**Comment by yuhaocan** [comment]
> The same problem after upgrading.
> Upgrade to 0.9.2 solution

how to do

**Comment by zoechi** [comment]
Is there something special about your network? Self-signed certificate, proxy, ...?
Did you install Flutter into a directory where your user account doesn't have write permissions? (C:\Program Files\...)?

**Comment by yuhaocan** [comment]
> Is there something special about your network? Self-signed certificate, proxy, ...?
> Did you install Flutter into a directory where your user account doesn't have write permissions? (C:\Program Files...)?

with MacOS,even use proxy

**Comment by zoechi** [comment]
Please check https://www.dartlang.org/tools/pub/troubleshoot

**Comment by zoechi** [comment]
Also check https://github.com/flutter/flutter/wiki/Using-Flutter-in-China if applicable

**Comment by yuhaocan** [comment]
> Also check https://github.com/flutter/flutter/wiki/Using-Flutter-in-China if applicable

![image](https://user-images.githubusercontent.com/12983937/46023118-83d4c200-c116-11e8-9bfe-98f048a65aee.png)
https://pub.flutter-io.cn/packages/file
I see file package build status is failing

**Comment by zoechi** [comment]
@yuhaocan I don't think that matters. It's failing for the master branch of a not-yet-published commit

**Comment by yuhaocan** [comment]
@zoechi I try again use China wiki with same steps ,but it same as before "Command 'pub upgrade' still failed after 10 tries"

**Comment by pujyzx** [comment]
> @zoechi I try again use China wiki with same steps ,but it same as before "Command 'pub upgrade' still failed after 10 tries"

Have you solved it?

**Comment by yuhaocan** [comment]
@zoechi   Finally it success, I  try so many times that  run it background.Too disappointed with the GW firewall.

**Comment by pujyzx** [comment]
![1538288894279](https://user-images.githubusercontent.com/12537655/46254141-27c6c080-c4bd-11e8-9e60-bceabda14aad.jpg)
 Today it`s ok

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by WenWu92** [comment]
https://github.com/flutter/flutter/issues/18937#issuecomment-405102627
https://github.com/flutter/flutter/issues/18937#issuecomment-422328273
These comments solved my problem.
