### ISSUE TITLE
Do crossover so that "flutter create" uses new ephemeral project structure instead of old structure.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#22003]
Do crossover so that the default "flutter create" invocation uses new "-t application" ephemeral project structure instead of the old "-t app" structure.

Prerequisites: 
 - the "flutter create -t application" variation has been introduced (@gspencergoog)
 - the "flutter make-host-app-editable" command exists and appears to be working correctly
 - the "flutter create -t app" and "flutter create -t module" variations no longer have public docs
 - at least 1 Flutter plugin cycle has gone by to allow the plugin to stop depending upon the old project structure variations in the project creation wizard

**Comment by mit-mit** [comment]
I think @gspencergoog did this in https://github.com/flutter/flutter/pull/22565?

**Comment by gspencergoog** [comment]
I've done the "the "flutter create -t app" and "flutter create -t module" variations no longer have public docs" part in that I've made their help text in the --help output only show if you say --help --verbose.

My PRs do indeed make the first part true: flutter create now uses "application" as the default ephemeral project, but some of the prerequisites are still not satisfied.

**Comment by matthew-carroll** [comment]
Closing this as "won't do" for now because we're going to treat the "module" project as an iterative improvement on top of the existing project structure.
