### ISSUE TITLE
Add PopupMenuItemDivider, remove hasDivider

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2201]
Dividers should occupy 16 pixels of their own vertical space, see https://www.google.com/design/spec/components/menus.html#menus-specs

Will need to refactor PopupMenuItem to allow for this.

**Comment by Hixie** [comment]
@HansMuller Did you end up doing this? I seem to recall seeing a PR to do this.

**Comment by HansMuller** [comment]
Yes: https://github.com/flutter/flutter/pull/2311
