### ISSUE TITLE
Implement ability for Flutter tooling to discover engine ports for running engines in an iOS app. Needed by attach command.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#22010]
Implement ability for Flutter tooling to discover engine ports for running engines in an iOS app. Needed by attach command.

Implementing this for iOS will be much more tedious than Android.  For robust use of "flutter attach", the flutter tool needs to be able to request the current running engine ports to select from.  But there is no obvious way to request this information from the running app.

@cbracken is currently investigating some options to facilitate this.

**Comment by dnfield** [comment]
I think @GaryQian is actually working on this

**Comment by GaryQian** [comment]
Thanks @dnfield for taking this on. His PR: https://github.com/flutter/engine/pull/6533

**Comment by dnfield** [comment]
Do we have a separate issue for tracking changes that will need to be made to the flutter_tools, or are we going to use this one for both?

**Comment by dnfield** [comment]
flutter/engine#6533 has landed, I'll close this and open a new issue for the tooling side.
