### ISSUE TITLE
Lost connection to device.

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter#22017]
I have update Flutter today .
After that,my project can't run in simulator and iPhone 6(iOS 12)

`➜  emp git:(master) ✗ flutter doctor -v        
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.8.2 at /Users/haoyi/flutter
    • Framework revision 5ab9e70727 (11 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/haoyi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (2 available)
    • 郝怿的 iPhone • 6d4a90c14794752f1d56db848716a8c609b7448b • ios • iOS 12.0
    • iPhone XS  • A4E0A17F-6E4A-48C0-8AE0-B16340BFF203     • ios • iOS 12.0 (simulator)

• No issues found!
`

in simulator:
`Launching lib/main.dart on iPhone XS in debug mode...
Starting Xcode build...
Xcode build done.
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ee4a29b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e3e6735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ee4a022 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010ddeab47 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x0000000117c9755b +[UIStoryboard storyboardWithName:bundle:] + 580
	5   Flutter                             0x000000010c6828b1 -[FlutterViewController splashScreenView] + 115
	6   Flutter                             0x000000010c682487 -[FlutterViewController installSplashScreenViewIfNecessary] + 134

	7   UIKitCore                           0x0000000117ecf38e -[UIViewContro<…>
Lost connection to device.
Syncing files to device iPhone XS...`

in iPhoen 6:
`Launching lib/main.dart on 郝怿的 iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 35DV8GEMR8
Starting Xcode build...
Xcode build done.
Installing and launching...
`
The app will install and crash,and idea will always be like this.

But there is nothing wrong with my new project.

**Comment by 39499740** [comment]
Flutter upgrade

**Comment by 39499740** [comment]
But there is nothing wrong with my new project.

**Comment by 39499740** [comment]
please close

**Comment by kneckel** [comment]
I'm experiencing the same issue! Is there a solution?

**Comment by wiliambuzatto** [comment]
I'm experiencing the same issue, but my environment is Windows with Nexus Android Emulator.

**Comment by zoechi** [comment]
@kneckel @wiliambuzatto  please create a new issue with filled out issue template.
A link to this issue would be helpful as well.

**Comment by DeepStyles** [comment]
Same Issue, Every time I had to close and delete app from emulator in order to run app again!!!!!

**Comment by zoechi** [comment]
@DeepStyles that is supposed to be fixed in `master` channel already.

**Comment by sujithm328** [comment]
Any idea about this type error .



Launching lib\main.dart on RCT6773W22 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
F/libc    ( 7731): Fatal signal 11 (SIGSEGV) at 0x00000004 (code=1), thread 7746 (1.ui)
handle_request(15)
check process 7731 name:ample.hellotest
tid 7746 abort msg address is:0
BOOM: pid=7731 uid=10090 gid=10090 tid=7746
[OnPurpose Redunant in preset_info] pid: 7731, tid: 7746, name: 1.ui  >>> com.example.hellotest <<<
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'RCA/RCT6773W22/RCT6773W22:4.4.2/KOT49H/1403615884:user/release-keys'
pid: 7731, tid: 7746, name: 1.ui  >>> com.example.hellotest <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000004
r0 00000000  r1 613b48e0  r2 00010000  r3 00470278
r4 6041c5f0  r5 63b32148  r6 602f5114  r7 00000001
r8 6143f228  r9 62309329  sl 6041c37c  fp 63b31080
ip 603160c8  sp 6041bf20  lr 5fd04ec4  pc 60220246  cpsr 200d0030
backtrace:
#00  pc 00556246  /data/app-lib/com.example.hellotest-2/libflutter.so
#01  pc 0003aec0  /data/app-lib/com.example.hellotest-2/libflutter.so
