### ISSUE TITLE
`flutter upgrade` command shows the previous version after successful upgrade.

### ISSUE THREAD

**Issue by berosoboy** [flutter/flutter#22018]
After the upgrade process the command shows the previous version rather than current one. I needed to run `flutter --version` to see the current installed version.

**Before upgrade:**
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (3 weeks ago) • 2018-08-28 12:39:24 -0700
Engine • revision af42b6dc95
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282

**While running `flutter upgrade`:**
Flutter 0.7.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 3b309bda07 (3 weeks ago) • 2018-09-07 12:33:05 -0700  **<== _(NOTE that the date is wrong)_**
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.1.0.flutter-ccb16f7282

**After running `flutter --version`:**
Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (11 days ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

Complete log:
[flutter-upgrade-log.txt](https://github.com/flutter/flutter/files/2395236/flutter-upgrade-log.txt)

**Comment by zoechi** [comment]
I think this is a dup of #22254 - merging
