### ISSUE TITLE
Video player controller cannot reference a List of Strings/array of paths to videos to loop and make a playlist   

### ISSUE THREAD

**Issue by Chimba123** [flutter/flutter#22015]
The Video player plugin apparently cannot loop through a string of paths/array that reference multiple videos locally. The controller only accepts one string. What if one wants to display/play 50, 100 or even a 1000 videos? the controller is insufficient for this implementation lest I am missing something

**Comment by harisk92** [comment]
@Chimba123 dispose current controller and create new one with url of video you want to play

**Comment by Chimba123** [comment]
Thanks

Could you please show me a sample if its not much trouble am not a veteran
programmer sometimes i need references to learn from.


Regards

**Comment by Chimba123** [comment]
@harisk92 do you have a working example?

**Comment by harisk92** [comment]
@Chimba123 

`void play(String url) {
     controller = VideoPlayerController.network(url);		    
     controller.initialize().then((_) => setState(() {}));		       
     controller.play();		       
     controller.addListener(checkIfVideoFinished);		       
   }		
		
   void checkIfVideoFinished() {		
     if (controller == null ||		
         controller.value == null ||		
         controller.value.position == null) return;		
     if (controller.value.position.inSeconds ==		
         controller.value.duration.inSeconds) {		
       if (widget.videos.length - 1 > currentVideo) {		
         play(currentVideo + 1);		
       } else {		
         play(nextVideoUrl);		
         controller.removeListener(checkIfVideoFinished);		
       }		
     }		
   }`

**Comment by Chimba123** [comment]
Thanks a lot harisk I'll try it out

**Comment by zoechi** [comment]
Looks like this is about a support question that got answered.
