### ISSUE TITLE
Flutter command should enable dex for debug build

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#22021]
I have this use case right now: 
- with flutter command -> can't run app in debug cause of multidex
- with Android studio -> run without problem because for debug version it enable multidex by default

So I'm basically force to enable multidex just to be able to run the app in debug from a Flutter project. Flutter should be able to have the same behavior to avoid enabling multidex for nothing.

**Comment by zoechi** [comment]
Seems related to #21009

**Comment by jaumard** [comment]
Definitely related :)

**Comment by zoechi** [comment]
I'm going to close as duplicate of #21009 
I think this is all covered by the other issue.
