### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [flutter/flutter#22031]
## Steps to Reproduce

1. Create a new project
2. Run the project on a device

## Logs

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\sawan\Documents\test-app> flutter run --verbose
[  +41 ms] executing: [D:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +134 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [D:\flutter\] git rev-parse --abbrev-ref HEAD
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [D:\flutter\] git ls-remote --get-url origin
[  +89 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [D:\flutter\] git log -n 1 --pretty=format:%H
[  +93 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5ab9e70727d858def3a586db7fb98ee580352957
[        ] executing: [D:\flutter\] git log -n 1 --pretty=format:%ar
[  +90 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 days ago
[        ] executing: [D:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +95 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.8.2-0-g5ab9e7072
[ +325 ms] executing: D:\android\android-sdk\platform-tools\adb devices -l
[  +46 ms] Exit code 0 from: D:\android\android-sdk\platform-tools\adb devices -l
[        ] List of devices attached
           ENU7N15A20008567       device product:angler model:Nexus_6P device:angler transport_id:1
[ +119 ms] Found plugin cloud_firestore at D:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.8.0\
[   +8 ms] Found plugin firebase_auth at D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.5.20\
[   +2 ms] Found plugin firebase_core at D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.2.5\
[   +1 ms] Found plugin firebase_storage at D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-1.0.2\
[   +7 ms] Found plugin flutter_facebook_login at D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-1.1.1\
[  +16 ms] Found plugin image_picker at D:\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.10\
[  +13 ms] Found plugin path_provider at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.4.1\
[   +7 ms] Found plugin shared_preferences at D:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.4.2\
[  +17 ms] Found plugin url_launcher at D:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-3.0.3\
[  +44 ms] Found plugin cloud_firestore at D:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.8.0\
[   +3 ms] Found plugin firebase_auth at D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.5.20\
[   +2 ms] Found plugin firebase_core at D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.2.5\
[   +2 ms] Found plugin firebase_storage at D:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-1.0.2\
[   +4 ms] Found plugin flutter_facebook_login at D:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-1.1.1\
[   +6 ms] Found plugin image_picker at D:\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.4.10\
[   +8 ms] Found plugin path_provider at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.4.1\
[   +2 ms] Found plugin shared_preferences at D:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.4.2\
[   +8 ms] Found plugin url_launcher at D:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-3.0.3\
[  +55 ms] D:\android\android-sdk\platform-tools\adb -s ENU7N15A20008567 shell getprop
[ +139 ms] ro.hardware = angler
[        ] ro.build.characteristics = nosdcard
[ +572 ms] Launching lib/main.dart on Nexus 6P in debug mode...
[  +22 ms] Initializing gradle...
[        ] Using gradle from C:\Users\sawan\Documents\test-app\android\gradlew.bat.
[ +116 ms] executing: C:\Users\sawan\Documents\test-app\android\gradlew.bat -v
[ +728 ms]
                   ------------------------------------------------------------
                   Gradle 4.1
                   ------------------------------------------------------------

                   Build time:   2017-08-07 14:38:48 UTC
                   Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

                   Groovy:       2.4.11
                   Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
                   JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b02)
                   OS:           Windows 10 10.0 amd64
[        ] Initializing gradle... (completed)
[        ] Resolving dependencies...
[        ] executing: [C:\Users\sawan\Documents\test-app\android\] C:\Users\sawan\Documents\test-app\android\gradlew.bat app:properties
[ +950 ms]
                   FAILURE: Build failed with an exception.

                   * Where:
                   Build file 'C:\Users\sawan\Documents\test-app\android\build.gradle' line: 27

                   * What went wrong:
                   A problem occurred evaluating root project 'android'.
                   > A problem occurred configuring project ':app'.
                      > No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

                   * Try:
                   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

                   * Get more help at https://help.gradle.org

                   BUILD FAILED in 0s
[   +3 ms] Resolving dependencies... (completed)
[   +2 ms] * Error running Gradle:
           Exit code 1 from: C:\Users\sawan\Documents\test-app\android\gradlew.bat app:properties:

           FAILURE: Build failed with an exception.

           * Where:
           Build file 'C:\Users\sawan\Documents\test-app\android\build.gradle' line: 27

           * What went wrong:
           A problem occurred evaluating root project 'android'.
           > A problem occurred configuring project ':app'.
              > No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 0s

[  +10 ms] "flutter run" took 3,074ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:115:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:270:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:261:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:391:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

PS C:\Users\sawan\Documents\test-app>

```
```

```
```

PS C:\Users\sawan\Documents\test-app> flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.8.2 at D:\flutter
    • Framework revision 5ab9e70727 (12 days ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at D:\android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = D:\android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.27.2)
    • VS Code at C:\Users\sawan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[√] Connected devices (1 available)
    • Nexus 6P • ENU7N15A20008567 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
PS C:\Users\sawan\Documents\test-app>

```
```

**Comment by sawankumarbundelkhandi** [comment]
mips64el-linux-android is missing in the NDK as it got deprecated

The old version of android Gradle plugin(<3.3.+) tries to access mips toolchain without checking if it exists. Upgrading the plugin version fixed the issue.

**Comment by MNGsulochana** [comment]
Try to update the studio..If u r trying to upload old project then update the gradle  as manually to the latest

**Comment by bbcbreno** [comment]
> I ran into this problem after upgrading Android Studio and trying to run a slightly older Flutter project. This fix worked for me:
> 
> ### Open `android/gradle/gradle-wrapper.properties` and change this line:
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
> ```
> to this line:
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
> ```
> ### Open `android/build.gradle` and change this line:
> ```
> classpath 'com.android.tools.build:gradle:3.0.1'
> ```
> to this:
> 
> ```
> classpath 'com.android.tools.build:gradle:3.1.2'
> ```

Hey @brianegan , thank you! That's worked fine. But, there's some easy way to update all this dependencies url instead change by hand?

**Comment by chazhenry** [comment]
The grade and gradle plugin fixes able work, but I did mine via:
File > Project Structure > Project

**Comment by vialyx** [comment]
@bbcbreno thank you!

**Comment by keviepanas** [comment]
> I ran into this problem after upgrading Android Studio and trying to run a slightly older Flutter project. This fix worked for me:
> 
> ### Open `android/gradle/gradle-wrapper.properties` and change this line:
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
> ```
> to this line:
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
> ```
> ### Open `android/build.gradle` and change this line:
> ```
> classpath 'com.android.tools.build:gradle:3.0.1'
> ```
> to this:
> 
> ```
> classpath 'com.android.tools.build:gradle:3.1.2'
> ```

This solved my solution. thanks!!

**Comment by zoechi** [comment]
@keviepanas 

> gradle-4.4-all.zip

`4.10.2` is current.
You can just create a new project with `flutter create foo` and check there.
See also https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by ThinkDigitalRepair** [comment]
or rename your gradle folder and `flutter create .` within the same project to have it regenerate

**Comment by zoechi** [comment]
> to this:
>
> ```
> classpath 'com.android.tools.build:gradle:3.1.2'
> ```

Should now be
```
classpath 'com.android.tools.build:gradle:3.2.1'
```
Just create a new project using `flutter create foo` and compare
or regenerate the files like explained in https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by kevinhao426** [comment]
> I ran into this problem after upgrading Android Studio and trying to run a slightly older Flutter project. This fix worked for me:
> 
> ### Open `android/gradle/gradle-wrapper.properties` and change this line:
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
> ```
> to this line:
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
> ```
> ### Open `android/build.gradle` and change this line:
> ```
> classpath 'com.android.tools.build:gradle:3.0.1'
> ```
> to this:
> 
> ```
> classpath 'com.android.tools.build:gradle:3.1.2'
> ```

Thanks man you saved my day!
