### ISSUE TITLE
Custom FocusNodes in TextFields on second navigator route cause visual glitches

### ISSUE THREAD

**Issue by bkayfitz-cara** [flutter/flutter#22045]
There seems to be weird UI glitches that happen when you try to use `TextFields` with your own `FocusNodes` (so you can control the flow from one field to the next)

After pushing a second route with the `Navigator`, when you tap on a `TextField`, the `InputDecorator` will flash for a second and then disappear, however the field will still be selected, it just won't have the visual appearance of being selected.  You can still type normally.

The issue seems to correct itself when you tap on the next `TextField`, if you are using the software keyboard. With the hardware keyboard attached (like with the simulator) you can see every field eventually have a cursor without looking "selected"

## Steps to Reproduce

https://gist.github.com/bkayfitz-cara/8da2afd964c7f4417435e9df49b4cd9e

1. Attach hardware keyboard (optional, but makes the issue more apparent)
2. Select the "push to new screen" button
3. Tap on any TextField,
4. The field will blink and look like its deselected.  The cursor will remain.
5. Tap on another field and that will also blink (if hardware keyboard is connected). Now you will see both fields with cursors

## Logs
No logs are printed.

```

[✓] Flutter (Channel dev, v0.8.6, on Mac OS X 10.13.6 17G65, locale en-CA)
    • Flutter version 0.8.6 at /Users/bkayfitz/flutter
    • Framework revision 9f359aeee2 (2 days ago), 2018-09-17 13:02:34 -0700
    • Engine revision b0b19d6ce1
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/bkayfitz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone X • 76DC8103-0560-4DC6-9F2F-8444B1337975 • ios • iOS 12.0 (simulator)

• No issues found!


```

**Comment by zoechi** [comment]
Thanks for the reproduction!

**Comment by zoechi** [comment]
Can't reproduce. Seems to covered by the fixes recently made to focus management with routed pages.
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```
