### ISSUE TITLE
Firebase Realtime Database Plugin,Not Working after DART 2 Upgrading

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#22040]
**Console Message:**
Running "flutter packages get" in yazhiragu...
Could not find a file named "pubspec.yaml" in "C:\Program Files\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-1.0.4".
pub get failed (66)
exit code 66

**Comment by zoechi** [comment]
Could you please try to create a new project with `flutter project` and copy the custom files from the old project to the new one?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
