### ISSUE TITLE
Add2App for iOS requires lots of manual steps that could be automated

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#22055]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps provides steps to add Flutter to an existing app.

On iOS, it would be nice to automate these steps into the tooling to:

- [ ] Add references to the Flutter Framework
- [ ] Add/update appropriate config files
- [ ] Add the Flutter build script phase
- [ ] Add CocoaPods if it's not already added

/cc @matthew-carroll

**Comment by mit-mit** [comment]
any updated on this?

**Comment by dnfield** [comment]
Not yet

**Comment by dnfield** [comment]
Currently exploring making better use of Cocoapods to help automate some of this.  I've made some progress but continuing to experiment - it can definitely add the correct framework related references, but I'm still seeing if I can get it to add the build script phase and make sure it can support changes to the Flutter/Dart project properly.

**Comment by dnfield** [comment]
Also, to be clear, this would not require that the intial Flutter app requries Cocoapods - although it would mean that our recommended way of adding a Flutter app to a iOS app requires Cocoapods.

In other words, our default template would have to have a `foo_app.podspec` file, but not a `Podfile` itself.  Flutter users would not be required to install Cocoapods to run and test Flutter on iOS.
