### ISSUE TITLE
Why Android studio can open the iOS simulator, but when running, the total prompt is not connected, how to connect?

### ISSUE THREAD

**Issue by liuyangqiao** [flutter/flutter#22059]
mac os

**Comment by zoechi** [comment]
> the total prompt is not connected

what does that mean?

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
