### ISSUE TITLE
On-screen Keyboard makes hidden UI elements such as status bar and nav bar reappear until app loses+regains focus

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#22061]
When UI status and/or navigation bars are disabled with
```
main() {
    SystemChrome.setEnabledSystemUIOverlays([]);
    runApp(...);
}
```
Opening the on-screen keyboard (eg, tapping on a textfield) re-enables the UI overlays (all the appropriate padding and everything is added on).

The UI overlays remain enabled even if the keyboard is closed until the app loses+regains focus (eg, putting phone to sleep and turning back on or switching to different app and switching back). After the reload, the overlays are off again.

It is reasonable to provide the navigation bars on Android when the keyboard appears because the back button is required to close it, but the bar should go back to being hidden after the keyboard is closed.

**Comment by GaryQian** [comment]
Considering adding SystemChrome method that restores the system UI overlays back to whatever was previously set in `setSystemUiOverlays()`. The system sometimes forces UI overlay changes and has anti-malware protections through prevention of hiding navbar for 1 second.

We should provide an easy way for users to revert system UI to what they set it to such as `SystemChrome.restoreSystemUiOverlays()`. Currently, users can re-call `SystemChrome.setSystemUiOverlays(...)` to force the UI but this requires the user to repeatedly keep track of the UI settings desired throughout the app even though the SystemChrome already knows the settings.

Thoughts? @Hixie

**Comment by GaryQian** [comment]
Added API `SystemChrome.restoreSystemUIOverlays();` to allow for reverting to the settings previously provided in `setEnabledSystemUIOverlays(...);` This should be manually called whenever the UIOverlays should be forced to be the overlays set. This call will fail if called too rapidly after a system UI force change (eg, <1s after keyboard brings up navbar).

**Comment by TomassMaximum** [comment]
Is there a way to show the on-screen keyboard without bringing up the status bar and navigation bar? I have a landscape app which is completely full screen. And I don't want to show the bars when users are typing because it blocks the UI. Users can click complete button on the keyboard or tap blank space to release the focus.
![Screenshot_20190318-100430_mBlock](https://user-images.githubusercontent.com/14291993/54504045-eb085c00-496c-11e9-8a40-a75950c14f53.jpg)

**Comment by adrianvintu** [comment]
(How) Can we hook to the onHideEvent of the keyboard to call `SystemChrome.restoreSystemUIOverlays()`, or when can we call the restore?

**Comment by GaryQian** [comment]
@TomassMaximum Android forces the status bar and navigation bar to appear when the keyboard appears. This the system's way to prevent malicious apps from locking users in their app.

@adrianvintu calling `restoreSystemUIOverlays` in the onHideEvent will not work, since Android prevents hiding the overlays for about 1 second after the event. You will need to call it either on a timer, when the user does something, or some other trigger.

**Comment by adrianvintu** [comment]
@GaryQian why do you keep saying this? "Android forces the status bar and navigation bar to appear when the keyboard appears. This the system's way to prevent malicious apps from locking users in their app."

Please specify source and also that if it is true, it only applies to OVERLAYS, but not the usual fullscreen API

getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);

@GaryQian Can we hook to the onHideEvent of the keyboard to call SystemChrome.restoreSystemUIOverlays() to call a future with a 1 second delay?

**Comment by GaryQian** [comment]
@adrianvintu The API specifies the behavior, and my comments are my best attempt at concisely conveying why the API is designed that way, after talking with the android team about it. I am not aware of any public reference that formally documents the reasoning process of this part of Android, but if I come across it, I will be sure to link it.

Unfortunately, there isn't too much I'm able to do about Android's behavior here. If you search the problem, you'll see it is not unique to flutter and impacts all Android apps.

I don't see why you couldn't, as long as the restore method is called after the protected time period.

**Comment by adrianvintu** [comment]
Thank you @GaryQian, i am making a ticket to collect other tickets regarding this and hopefully introduce a new API.
