### ISSUE TITLE
I will recieved data when come from firebase console

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#22069]
_From @Pradipkoravi on September 20, 2018 6:14_

URL: https://pub.dartlang.org/packages/firebase_messaging

{notification: {body: this is test notification.Run the following command to create the client for our notes app.This shou..., title: Test}, data: {ni: 1, text: notification, color: red, image: image ur, title: Test}}

but I need to get individual value from it 

_Copied from original issue: dart-lang/pub-dartlang-dart#1634_

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

What do you mean by "individual value"? 
Where do you want to get it?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
