### ISSUE TITLE
IphoneX + SafeArea + landscape + pushReplacement = screen flicker

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#22063]
I have an app on the Apple store :
https://itunes.apple.com/us/app/aac-keyboard-with-friends/id1434587499?ls=1&mt=8

Unfortunately I get a flickering screen on the IPhone X. It is primarily intended to be used in landscape mode. I have reproduced the problem with a small amount of code. Attached are the minimum files which reproduce the glitches.

[glitches.tar.gz](https://github.com/flutter/flutter/files/2399163/glitches.tar.gz)

@cbracken

**Comment by Rockvole** [comment]
Attached are 2 screen recording video files which show the screen glitches as they happen.

[glitch_vids.tar.gz](https://github.com/flutter/flutter/files/2399184/glitch_vids.tar.gz)

**Comment by Rockvole** [comment]
[✓] Flutter (Channel master, v0.8.5-pre.7, on Mac OS X 10.13.6 17G65, locale en-CA)
    • Flutter version 0.8.5-pre.7 at /work/installs/flutter
    • Framework revision 2bca8007bd (3 days ago), 2018-09-16 12:30:34 -0400
    • Engine revision 72665c6827
    • Dart version 2.1.0-dev.4.0.flutter-bb56d4592f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/david/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • 9717A4E1-0F44-455A-979D-3CBD0B7D8BD0 • ios • iOS 11.4 (simulator)

• No issues found!

**Comment by cbracken** [comment]
@Rockvole thanks for reporting! 

Labelling as both framework and engine until we've figured out where the issue lies (possibly both). 

/cc @HansMuller @Hixie who are far more familiar with routes/navigation than I am for ideas, and @GaryQian who's currently looking at some SafeArea-related issues.

**Comment by Rockvole** [comment]
Thanks @cbracken . Does anyone know if the new flutter release preview 2 will have changes to fix this problem ? I actually have not seen the problem myself (I don't have an IPhone X) its my friend who lives 1,000s of miles away (he is a developer) - he was helping me using testflight.

**Comment by Rockvole** [comment]
Problem still present in 

    Flutter (Channel master, v0.11.1-pre.57, on Mac OS X 10.13.6 17G65, locale en-CA)

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by Rockvole** [comment]
Looks like it is fixed - thank-you.

Tested in :

    Flutter 1.2.2-pre.43 • channel master • https://github.com/flutter/flutter.git
    Framework • revision 5169ab5974 (8 hours ago) • 2019-02-21 09:27:07 +0100
    Engine • revision 6d7eb52185
    Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
