### ISSUE TITLE
'GoogleUtilities/GULAppEnvironmentUtil.h' file not found, build failing in iOS

### ISSUE THREAD

**Issue by jashanpj** [flutter/flutter#22071]
## Steps to Reproduce

1. First of all I revert back my dart and flutter downgraded to 1.XX to avoid cloud_firestore plug in implementation problem which cause a FirebaseCore error with pod. Unfortunately I didn’t find any fix for it. Which may you can refer here [#22036](https://github.com/flutter/flutter/issues/22036)
2. In this build I use cloud_firestore: 0.7.4, and it manage to run in android devices successfully. The ios part is again stuck with this time another missing problem 

`  /Users/jashan/Desktop/Programming/vueboomobile/ios/Pods/FirebaseCore/Firebase/Core/FIRLogger.m:18:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
    #import <GoogleUtilities/GULAppEnvironmentUtil.h>`

## Logs

![screen shot 2018-09-20 at 12 08 03 pm](https://user-images.githubusercontent.com/42855222/45800299-1bc54c80-bcce-11e8-873b-cf9385910f9c.png)
```
```
# This is the console out
```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    2018-09-20 11:51:19.626 xcodebuild[24486:176349] warning:  The file reference for "Firebase.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2018-09-20 11:51:19.648 xcodebuild[24486:176349] warning:  The file reference for "GoogleUtilities.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    ** BUILD FAILED **
    
Xcode's output:
↳
    /Users/jashan/Desktop/Programming/vueboomobile/ios/Pods/FirebaseCore/Firebase/Core/FIRLogger.m:18:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
    #import <GoogleUtilities/GULAppEnvironmentUtil.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.

```

This is my `flutter doctor -v`

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.5.1 at /Users/jashan/Documents/Programming/Flutter/flutter
    • Framework revision c7ea3ca377 (4 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/jashan/Library/Android/sdk
    • Android NDK at /Users/jashan/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 473AE7A7-1E8A-4513-965A-F58742C2AF3A • ios         • iOS 11.3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by 1and1get2** [comment]
I had this exact issue, but forgot how i fixed it

**Comment by JigneshPatel23** [comment]
Facing the same issue. Does anyone have any idea?

**Comment by DanielSmith1239** [comment]
I'm having this issue trying to build on the master branch.

**Comment by CristiTr** [comment]
+1

**Comment by zoechi** [comment]
@CristiTr 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason. 
Use the [Subscribe] button on the right to get notified about updates.

**Comment by JCPradelPH** [comment]
Already fixed this issue on my end by doing the following while xcode is closed:

1. In terminal: flutter clean
1. Delete Podfile.lock
2. Delete Pods folder
3. Delete Podfile (I backed up my existing Podfile)
4. In terminal: pod init
5. In terminal: pod install
6. Copied the contents of my previous Podfile into the Podfile generated by the pod init command
7. pod install
8. In terminal: flutter run

### Podfile content
`# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

pod 'Firebase/Core'
pod 'FBSDKLoginKit'
pod 'GoogleAnalytics'

def parse_KV_file(file, separator='=')
    file_abs_path = File.expand_path(file)
    if !File.exists? file_abs_path
        return [];
    end
    pods_ary = []
    skip_line_start_symbols = ["#", "/"]
    File.foreach(file_abs_path) { |line|
        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
        plugin = line.split(pattern=separator)
        if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_ary.push({:name => podname, :path => podpath});
            else
            puts "Invalid plugin specification: #{line}"
        end
    }
    return pods_ary
end

target 'Runner' do
    use_frameworks!
    
    # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
    # referring to absolute paths on developers' machines.
    system('rm -rf .symlinks')
    system('mkdir -p .symlinks/plugins')
    
    # Flutter Pods
    generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
    if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
    end
    generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
            symlink = File.join('.symlinks', 'flutter')
            File.symlink(File.dirname(p[:path]), symlink)
            pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
        end
    }
    
    # Plugin Pods
    plugin_pods = parse_KV_file('../.flutter-plugins')
    plugin_pods.map { |p|
        symlink = File.join('.symlinks', 'plugins', p[:name])
        File.symlink(p[:path], symlink)
        pod p[:name], :path => File.join(symlink, 'ios')
    }
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '4'
        end
    end
end
`
Hope this helps.

**Comment by JCPradelPH** [comment]
Hi @leorachit,

I just added these three lines at the top of my Podfile

```
pod 'Firebase/Core'
pod 'FBSDKLoginKit' # This is optional
pod 'GoogleAnalytics'
```

**Podfile**

```
platform :ios, '10.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Added these lines for firebase, google and flutter_facebook_login plugin
pod 'Firebase/Core'
pod 'FBSDKLoginKit' #optional
pod 'GoogleAnalytics'

def parse_KV_file(file, separator='=')
    file_abs_path = File.expand_path(file)
    if !File.exists? file_abs_path
        return [];
    end
    pods_ary = []
    skip_line_start_symbols = ["#", "/"]
    File.foreach(file_abs_path) { |line|
        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
        plugin = line.split(pattern=separator)
        if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_ary.push({:name => podname, :path => podpath});
            else
            puts "Invalid plugin specification: #{line}"
        end
    }
    return pods_ary
end

target 'Runner' do
    use_frameworks!
    
    system('rm -rf .symlinks')
    system('mkdir -p .symlinks/plugins')
    
    generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
    if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
    end
    generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
            symlink = File.join('.symlinks', 'flutter')
            File.symlink(File.dirname(p[:path]), symlink)
            pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
        end
    }

    plugin_pods = parse_KV_file('../.flutter-plugins')
    plugin_pods.map { |p|
        symlink = File.join('.symlinks', 'plugins', p[:name])
        File.symlink(p[:path], symlink)
        pod p[:name], :path => File.join(symlink, 'ios')
    }
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '4'
        end
    end
end
```

Hope this helps.

**Comment by ThinkDigitalRepair** [comment]
> Already fixed this issue on my end by doing the following while xcode is closed:
> ...
> 4. Delete Podfile (I backed up my existing Podfile)
> 5. In terminal: pod init
> 6. In terminal: pod install
> 7. Copied the contents of my previous Podfile into the Podfile generated by the pod init command
> 8. pod install
> 9. In terminal: flutter run

Won't deleting the Podfile, then restoring the contents from the file be redundant? It's just text, so the file will be identical after doing this

**Comment by aidandavis** [comment]
I'm having this issue also. Builds find from xcode but not from 'flutter run' in vs code.

**Comment by owenmech** [comment]
Having this issue at the moment as well. Error shows up when building from xcode

**Comment by kodeine** [comment]
same issue on cordova

**Comment by Vikas-Jilla** [comment]
Doing `flutter clean` solved the issue for me.

**Comment by collinjackson** [comment]
It seems like this issue might not be specific to cloud_firestore

#27797 is the master bug for iOS Pod-related compile flakes

**Comment by filiph** [comment]
Encountered a very similar error just now, which I was able to solve with `flutter clean`.

The error:

```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/filiph/dev/flutter_egamebook/ios/Pods/GoogleUtilities/GoogleUtilities/Logger/GULLogger.m:15:
    /Users/filiph/dev/flutter_egamebook/ios/Pods/GoogleUtilities/GoogleUtilities/Logger/Private/GULLogger.h:19:9: fatal error:
    'GoogleUtilities/GULLoggerLevel.h' file not found
    #import <GoogleUtilities/GULLoggerLevel.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from
    /Users/filiph/dev/flutter_egamebook/ios/Pods/GoogleUtilities/GoogleUtilities/Network/GULNetworkConstants.m:15:
    /Users/filiph/dev/flutter_egamebook/ios/Pods/GoogleUtilities/GoogleUtilities/Network/Private/GULNetworkConstants.h:18:9:
    fatal error: 'GoogleUtilities/GULLogger.h' file not found
    #import <GoogleUtilities/GULLogger.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Encountered error while building for device.
```

What worked for me:

1. Close XCode
2. Run `flutter clean`
3. Run `flutter build ios`
4. Open XCode again

Problem fixed. Possibly, the closing of XCode is not needed, but I included it just in case. Hope this helps.

**Comment by willcalderbank** [comment]
For thoses still having problems, updating cocoapods was the only way I could fix this problem

``` gem install cocoapods```

**Comment by kroikie** [comment]
@jashanpj

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/655. Any further collaboration will be done there.

**Comment by Fatimamostafa** [comment]
> Already fixed this issue on my end by doing the following while xcode is closed:
> 
> 1. In terminal: flutter clean
> 2. Delete Podfile.lock
> 3. Delete Pods folder
> 4. Delete Podfile (I backed up my existing Podfile)
> 5. In terminal: pod init
> 6. In terminal: pod install
> 7. Copied the contents of my previous Podfile into the Podfile generated by the pod init command
> 8. pod install
> 9. In terminal: flutter run
> 
> ### Podfile content
> ```
> platform :ios, '10.0'
> 
> ENV['COCOAPODS_DISABLE_STATS'] = 'true'
> 
> pod 'Firebase/Core'
> pod 'FBSDKLoginKit'
> pod 'GoogleAnalytics'
> 
> def parse_KV_file(file, separator='=')
>     file_abs_path = File.expand_path(file)
>     if !File.exists? file_abs_path
>         return [];
>     end
>     pods_ary = []
>     skip_line_start_symbols = ["#", "/"]
>     File.foreach(file_abs_path) { |line|
>         next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
>         plugin = line.split(pattern=separator)
>         if plugin.length == 2
>             podname = plugin[0].strip()
>             path = plugin[1].strip()
>             podpath = File.expand_path("#{path}", file_abs_path)
>             pods_ary.push({:name => podname, :path => podpath});
>             else
>             puts "Invalid plugin specification: #{line}"
>         end
>     }
>     return pods_ary
> end
> 
> target 'Runner' do
>     use_frameworks!
>     
>     system('rm -rf .symlinks')
>     system('mkdir -p .symlinks/plugins')
>     
>     generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
>     if generated_xcode_build_settings.empty?
>         puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
>     end
>     generated_xcode_build_settings.map { |p|
>         if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
>             symlink = File.join('.symlinks', 'flutter')
>             File.symlink(File.dirname(p[:path]), symlink)
>             pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
>         end
>     }
> 
>     plugin_pods = parse_KV_file('../.flutter-plugins')
>     plugin_pods.map { |p|
>         symlink = File.join('.symlinks', 'plugins', p[:name])
>         File.symlink(p[:path], symlink)
>         pod p[:name], :path => File.join(symlink, 'ios')
>     }
> end
> 
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings['ENABLE_BITCODE'] = 'NO'
>             config.build_settings['SWIFT_VERSION'] = '4'
>         end
>     end
> end
> ```

I did everything mentioned here. But still, the issue was there. What I did more to solve this is: 


1. Open project's iOS terminal
2. Run `pod update`
3. Open XCode
4. Clean Build Files 
5. Run Project

**Comment by rafekun** [comment]
I just added this code in Podfile, and worked.
`pod 'GoogleUtilities', '6.6.0'`
https://stackoverflow.com/questions/62905585/googleutilities-appdelegateswizzler-private-gulapplication-h-file-not-found

**Comment by imWildCat** [comment]
What's wrong with this bug? It is 2020 and this bug still exists!

**Comment by Cornelius92** [comment]
This fixed the issue for me:
1. Open project directory in terminal
2. run `pod deintegrate`
3. run `pod install`

https://stackoverflow.com/questions/62897711/gdtcorlibrary-public-gdtcortransport-h-file-not-found

**Comment by MichalDanielDobrzanski** [comment]
This bug is still present. Any solutions for its anniversary?

**Comment by imWildCat** [comment]
@MichalDanielDobrzanski It looks like CocoaPods bug I believe.

Try to clear all your CocoaPods cache and repeat 
https://github.com/flutter/flutter/issues/22071#issuecomment-668925533

**Comment by SebghatYusuf** [comment]
@imWildCat
I'm facing the bug, tried #22071 but didn't worked for me.

**Comment by imWildCat** [comment]
@SebghatYusuf can you try:

```shell
rm ~/Library/Caches/CocoaPods && rm ~/.cocoapods && pod cache clean -f
```

Also follow you on Twitter. You can DM me if you need future help.

**Comment by SebghatYusuf** [comment]
@imWildCat 
Thank you so much, I'll try and share the results :)
