### ISSUE TITLE
[Firebase Messaging] Receive data notifications while the app is terminated

### ISSUE THREAD

**Issue by philipgiuliani** [flutter/flutter#22072]
Since we have background execution of dart code now, would it be possible to receive data notifications while the app is terminated?

**Comment by perezd** [comment]
Our project needs this too (internal g3 customer).

**Comment by danwulff** [comment]
Definitely desired for our Android app.

**Comment by dude8604** [comment]
Please see my comment here, I think it's more specific: https://github.com/flutter/flutter/issues/22197#issue-363002132

**Comment by facundomedica** [comment]
Is it possible to use a method channel when the notification is clicked and the app is terminated? (Android)

**Comment by rajeevjaiswal** [comment]
any update on this?

**Comment by thevzurd** [comment]
The FirebaseMessaging service sends intend to the local broadcast manager from its onMessageRecieve method. While testing with app terminated, I found that it sends the intend to a different local broadcast manager (that when it was running) even though I can see logs from my apps background. Is there a way to activate the same broadcast receiver (FirebaseMessaging plugin class) incase it is not running ? (Novice here!)

**Comment by facundomedica** [comment]
@thevzurd that's exactly what this issue is about.  Hopefully we'll get an update soon? 🤔

**Comment by thevzurd** [comment]
There is a work around. Data messages can be processed from the on recieved method, and notifications can be sent to broadcast. But this would mean that we write a logic for Android and iOS (like for eg storing the recieved message in db) or use method channel to call dart.

**Comment by facundomedica** [comment]
@thevzurd I've thought about that, but currently we don't have the need for that amount of customization in notifications, so we decided to wait until the flutter team fixes this

**Comment by thevzurd** [comment]
My thinking was to completely remove the subscriptions and listeners to firebase from the App. Instead, push the data as messages to the app whenever there is some activity in the collection. In that way, I could save some power and data charges on the network on the device and push that responsibility to the server.  Is this an incorrect approach ?

**Comment by agent306** [comment]
Any updates on this? In DIRE need of this feature for a commercial Cinema app

**Comment by rajeevjaiswal** [comment]
This should be the top most priority of flutter team to provide same behavior that one gets from native code.
I am currently working on a very big project and this is such a critical feature which fcm plugin lags

**Comment by perezd** [comment]
Also critical to me.

**Comment by pavankumarkatakam** [comment]
I also need this feature, so for now im cloning this repo and doing changes in Plugin onRecieved class to open `MainActivity` using **startActivity** so that **channel.invokeMethod** will work as expected but how do i detect the app is terminated or in foreground so that while app is terminated only i need to startActivity otherwise Flutter onMessageRecieved work as usual.

**Comment by pavankumarkatakam** [comment]
But how should i start the **FlutterActivity** from java code. I know generally we use **startActivity**, but here we need to open the FlutterActivity from plugin implementation.

**Comment by rolandbodenstaff** [comment]
Any update on this?

**Comment by samuelg123** [comment]
Any update? I really need this :)

**Comment by rodrigosmarques** [comment]
I solved the problem by adding the tag "notification":

{notification: {body: "Body Push", title: "Title"}, data: {data: {alert:"Alert Push"}, time: 2019-07-04T13:33:02.594Z}}

**Comment by samuelg123** [comment]
@rodrigosmarques Thanks for the solution. I tried that yesterday. It didn't solve my problem actually. What I want to achieve is background execution inside onMessage when the app is terminated. It seems flutter doesn't have service like Android until now. CMIIW

My thought: I think if flutter can also provide separate task like android service that would be great. So the whole flutter app doesn't need to be running. And provide the binder to connect flutter service and main flutter app.

**Comment by Thomaslay7** [comment]
> I solved the problem by adding the tag "notification":
> 
> {notification: {body: "Body Push", title: "Title"}, data: {data: {alert:"Alert Push"}, time: 2019-07-04T13:33:02.594Z}}

how to receive data from message push notification?

**Comment by ivk1800** [comment]
this is what you need? my implementation not completed and only android, but if needed, i will do PR
https://github.com/ivk1800/plugins/commit/526169dcf8236a1286a6397644bf04e45174fe0b

**Comment by abhi12299** [comment]
Hey, @ivk1800. Does this fork of yours put the data message received in shared preferences when the app is terminated? I do need access to data message in all situations and any solution will do for now..

**Comment by ivk1800** [comment]
@abhi12299 it was planned to register the broadcast receiver and, after receiving the message, do whatever you want with it

**Comment by pavankumarkatakam** [comment]
> @abhi12299 it was planned to register the broadcast receiver and, after receiving the message, do whatever you want with it

So, we can register our own receiver with intent name `ACTION_BACKGROUND_REMOTE_MESSAGE` and do what ever we want right?

R u going to add anything else or merging the same in master.

**Comment by kroikie** [comment]
https://github.com/flutter/plugins/pull/1900 should allow you to handle background messages in your Dart code

**Comment by abhi12299** [comment]
When will it be merged to master? @kroikie

**Comment by XSiyabonga** [comment]
@kroikie Can you find out for us when your commit will be merged into master. This is a critical feature for our app. This will allow custom notifications using the data payload on terminated.

**Comment by athornz** [comment]
@XSiyabonga if it's critical to your app you can start using the branch right now.

Just update your pubspec to point to the branch:

```
  firebase_messaging:
    git:
      url: https://github.com/kroikie/plugins.git
      ref: fcm_background
      path: packages/firebase_messaging
```

**Comment by kroikie** [comment]
There are some outstanding comments that I'm working to resolve from reviewers. Once resolved I will merge and publish. @athornz is also correct.

**Comment by softcoder** [comment]
Sadly the fcm_background git package does not compile at the moment

**Comment by softcoder** [comment]
Getting package errors when I try to use the git repo on compile:

/home/softcoder/flutter/.pub-cache/git/plugins-52a19bacbeadac4d0e989091d3ad58e4da3368b1/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java:143: error: method findAppBundlePath in class FlutterMain cannot be applied to given types;
    String appBundlePath = FlutterMain.findAppBundlePath();
                                      ^
  required: Context
  found: no arguments
  reason: actual and formal argument lists differ in length
Note: /home/softcoder/flutter/.pub-cache/git/plugins-52a19bacbeadac4d0e989091d3ad58e4da3368b1/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java uses or overrides a deprecated API.

**Comment by kroikie** [comment]
@softcoder if you try again the build errors should be resolved.

**Comment by eparenti76** [comment]
I have some problems using firebase_messaging plugin.

On Android:

In the emulator work well. Push notifications work when app is terminated, foreground and background, but when I install my app on my device Asus ZenPhone 5 and the app is terminated push notifications not work. Documentation says that when the app is terminated only Notification works.

OK, I Use FirebaseAdmin library on C# and I try exclude data and push only simple notification but not work.
I try from firebase console but nothing change.

…
Dictionary<string, string> data = new Dictionary<string, string>();
data.Add("click_action", "FLUTTER_NOTIFICATION_CLICK");
data.Add("istanza", istanza);
data.Add("username", username);
data.Add("oggetto", oggetto);
data.Add("id", id);

    // See documentation on defining a message payload.
    var message = new FirebaseAdmin.Messaging.Message();

    message.Token = token;
    //message.Data = data;
    message.Notification = new Notification();
    message.Notification.Title = title;
    message.Notification.Body = body;


    //non mi interessa aspettare l'esito
    FirebaseMessaging.DefaultInstance.SendAsync(message);
On Android when app is teminated this notifications not work and not work even i add data payload.
The strange is that in emulator work all fine even i add data payload.

On IOS:

I configure all in firebase console and app store.

In IOS push notification works well when the app is in background and terminated, but when is in foreground not work.
The strange is that id I install the .ipa manually on my IPhone, push notifications work only if the app is foreground.
I think is normally that not work push notification if I install my app manually but the strange is that works in foreground and the playstore installation not works in foregrand.

Can you help me?
Thanks

**Comment by sd-timaru** [comment]
Let's say that the device receives an FCM notification with data payload and the app is killed in that moment.
When the user taps the notification, the app opens and the data is retrieved by the onResume method. But if the user opens the app from the app list (and not by tapping the notification)? How is the data from the payload retrieved?
Thanks!

**Comment by kroikie** [comment]
It is not, the payload of the notification is only available if the user
taps the notification.

**Comment by kliyer-ai** [comment]
@softcoder How did you get this to work? I am getting the exact same error? Thanks.

**Comment by kroikie** [comment]
@kliyer-ai what exactly is the error you are seeing, also what version of the plugin are you using?

**Comment by softcoder** [comment]
My project is in github here, feel free to take a look: https://github.com/softcoder/riprunner/tree/master/flutter/riprunner

**Comment by kroikie** [comment]
I think it is safe to close this issue now. Please file new issues, at github.com/FirebaseExtended/flutterfire

**Comment by Niek** [comment]
This is working on Android since firebase_messaging 5.1.6, iOS needs this PR to be merged: https://github.com/FirebaseExtended/flutterfire/pull/53

**Comment by kliyer-ai** [comment]
@kroikie The version I am using is 5.1.6. In the end I solved it by updating my flutter version to the latest release. Too bad it doesn't work with older Flutter versions.

**Comment by alvinotienokelly** [comment]
I am using the updated firebase_mesaging plugin and when i add the parameter onBackgroundMessage it says that its unknown 
can anyone help on this

**Comment by alvinotienokelly** [comment]
I am using the updated flutter_messaging and when i add  onBackgroundMessage it says parameter does not exist can anyone help

**Comment by kroikie** [comment]
@philipgiuliani

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1066. Any further collaboration will be done there.

**Comment by braysonjohn148** [comment]
```
Future<dynamic> _backgroundMessageHandler(Map<String, dynamic> message) async {
  print("------------------_backgroundMessageHandler");
}
```

```
exports.commentsData = functions.firestore.document('comments/{post}').onCreate(async(snapshot, context) => {
    const postss = snapshot.data();
    const payload = {
        data: {
            'type': `comment`,
            'otheruserID': postss.otheruserID,
            'message': postss.title, 
        }
    };
    return fcm.sendToTopic(postss.channel, payload);
});
```

When the App is in the background, i get the data notification. And insert it into mysql database successfully. But when the app is completely terminated, It does not call the function to insert to the database.
