### ISSUE TITLE
Flutter is crashing while deploying app to the device

### ISSUE THREAD

**Issue by sonulohani** [flutter/flutter#22083]
Please check the log I have added in the attachment. Whenever I run "flutter run" the flutter crashes.
[flutter_01.log](https://github.com/flutter/flutter/files/2401717/flutter_01.log)

Thank you

**Comment by kangwang1988** [comment]
<img width="828" alt="screen shot 2018-09-20 at 10 42 27 pm" src="https://user-images.githubusercontent.com/817851/45826160-78545600-bd26-11e8-9e4f-90fa3addfa25.png">

Not a flutter's problem. Pay attention to the java.net.UnknownHostException: services.gradle.org 
So make sure services.gradle.org is available in your computer.

**Comment by sonulohani** [comment]
Hi @kangwang1988 ,

Thanks for the update. I have updated my gradle using android studio. You can close this issue now.
