### ISSUE TITLE
CupertinoPicker _buildMagnifierScreen() is drawing double border lines

### ISSUE THREAD

**Issue by csjames** [flutter/flutter#22087]
![42146057_490982894711596_8508063800849596416_n](https://user-images.githubusercontent.com/12152421/45828350-3b6d6c80-bcf0-11e8-9c14-11bcefa1e507.jpg)

See the lines above and below the 4 and the 25, 

These lines only appear after scrolling the pickers. Not in their initial state

I currently have four Cupertino pickers side by side, with flex values 2,1,1,1

`
   child: new Row(
                  children: <Widget>[
                    new Flexible(
                      flex: 2,
                      child: Container(
                        height: 140.0,
                        child: new CupertinoPicker(
                          useMagnifier: false,
                          scrollController: new FixedExtentScrollController(
                            initialItem: _selectedDay,
                          ),
                          itemExtent: 28.0,
`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by xster** [comment]
Could you add some details on how to reproduce this issue? I couldn't produce it from your description from HEAD.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
