### ISSUE TITLE
my container color is overriding the color of it is parent container

### ISSUE THREAD

**Issue by sasukeamjed** [flutter/flutter#22086]
guys i am having an issue with my code:
why the container color is overriding the color of it is parent, i put two containers inside each other, one with width and height of 400 with color red and the one inside is with width and height 155 with color green, what is happening here ? is it a bug ?
![untitled](https://user-images.githubusercontent.com/31798947/45827802-4e8c3680-bd08-11e8-9ab8-0b93d852f5a3.png)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

You might want to check https://flutter.io/debugging/#visual-debugging

I doubt the container is overriding the parents color. I assume the container is enlarged to the size of the parent.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
