### ISSUE TITLE
remove "flutter start"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2208]
```
~/flutter/testme2 $ flutter start --help
Run your Flutter app on an attached device.

Usage: flutter run [arguments]
```

Which is the real one? If start is deprecated in favor of `run`, maybe we can print out "start is replaced by run. Please update your scripts, as we will soon remove start."

**Comment by abarth** [comment]
We should remove `start`.  It's the old name for `run`.

**Comment by sethladd** [comment]
Good to know. I opened https://github.com/flutter/flutter/issues/2210 to track the Atom work.

**Comment by devoncarew** [comment]
A few of our commands are aliased, which I think is ok. All the docs should specify `flutter run` at this point.
