### ISSUE TITLE
CupertinoTabScaffold Hero animation

### ISSUE THREAD

**Issue by Asoseil** [flutter/flutter#22084]
I would like to animate an element from a page of CupertinoTabScaffold to a new cupertino page pushed with rootNavigator:true. 

At now seems that isn't supported, but previously, about 10 days ago, it was supported on master and also on dev

**Comment by Asoseil** [comment]
It works if i disable this in heroes.dart at line 205

```
// Don't perform transitions across different Navigators.
      if (element.widget is Navigator) {
        return;
      }
```

**Comment by Asoseil** [comment]
octor summary (to see all details, run flutter doctor -v):                                                                                                                                                                                                                                                                                                     [✓] Flutter (Channel master, v0.9.3-pre.12, on Mac OS X 10.13.6 17G65, locale en-IT)                                                                                                                                                                                                                                                                            [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)                                                                                                                                                                                                                                                                                        [✓] iOS toolchain - develop for iOS devices (Xcode 10.0)                                                                                                                                                                                                                                                                                                        [✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.                                                                                                                                                                                                                                                                                        [✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)                                                                                                                                                                                                                                                                                                           [!] VS Code (version 1.26.1)                                                                                                                                                                                                                                                                                                                                     [✓] Connected devices (1 available)

**Comment by xster** [comment]
It seems like this effect is achievable in native iOS. I'll add back support for this.

**Comment by jinfagang** [comment]
@xster waiting for new updates.

**Comment by jinfagang** [comment]
@xster So how to make the bottom bar hide when push it with rootNavigator as true? the default behaviour are still keep the bottom bar (I mean the tab bar in the main page)

**Comment by xster** [comment]
Not sure I understand your question. Is it related to the original issue?

Does the third tab of the navigation demo in the Flutter gallery match your intentions? The sample code is at https://github.com/flutter/flutter/blob/55f3da7afc3e413d06459278474b895333a7f42f/examples/flutter_gallery/lib/demo/cupertino/cupertino_navigation_demo.dart#L727. 

Please file a separate issue if there are further problems with the API.

**Comment by jinfagang** [comment]
@xster Yeah, I have post an issue previously, it's still the effect as WeChat, push to next screen with navigation transition and hide bottombar. This code you provide does the navigation transition but if previous page has CupertinoTabbarScaffold, the bottombar can not be hide (It will exit in the next screen).

If you understand what I mean, my situation is simply (keep the navigation transition animation as well as hide the bottom bar), does it can be done?

**Comment by xster** [comment]
I'm still not sure I understand. It still sounds like you're describing the same scenario as what's shown in Flutter gallery (navigate to the next page with a bottom up transition and hid the bottom tab bar). 

I couldn't find your previous issue. https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+jinfagang

Could you create a new issue with this new request? Any graphical mockups would be helpful for me to understand.

**Comment by jinfagang** [comment]
@xster Oh........ I will test it this night, and paste some screen shot to clarify my points. this params seems create a full screen dialog from bottom to the to rather than push to next screen with left to right transition.

```
                    fullscreenDialog: true,
```

**Comment by calvinmuller** [comment]
also looking for an option with a slide transition to hide the tab bar.

**Comment by jinfagang** [comment]
@calvinmuller I just posted an issue yesterday, @xster  indicates us that this feature are not supported yet.

However this is exactly one of iOS design style isn't it? In XCode we can choose to push to next ViewController and hide or not hide the bottom bar, otherwise, it can not be called `Cross Platform` or `Native like`
