### ISSUE TITLE
Engine crash when running a flutter app with no main method

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#22081]
1. `flutter create repro`

1. `flutter run`

   => everything works great

1. stop app, and remove `void main() => runApp(new MyApp());` from `lib/main.dart`

   => 

    ```
    E/flutter ( 7356): [ERROR:flutter/shell/common/engine.cc(158)] Could not prepare to run the isolate.
    E/flutter ( 7356): [ERROR:flutter/shell/common/engine.cc(117)] Engine not prepare and launch isolate.
    E/flutter ( 7356): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(166)] Could not launch engine in configuration.
    ```

**Comment by mit-mit** [comment]
cc @chinmaygarde do you think this is an engine issue, or vm issue?

**Comment by asapJ** [comment]
from what i know, dart programs begins execution from the main method.
Flutter itself uses Dart. With the absence of a the main method, which other behavior(s) did you expect?

**Comment by jason-simmons** [comment]
This is similar to https://github.com/flutter/flutter/issues/21010.  In the engine Dart_RootLibrary returns null after loading a kernel with no main method.

Is it possible to catch this at compile time?

**Comment by mit-mit** [comment]
> With the absence of a the main method, which other behavior(s) did you expect?

I expected a better, more easy to understand error message.

**Comment by zoechi** [comment]
Just a wild guess. 
Could a fix for https://github.com/dart-lang/sdk/issues/33076 lead to a better error here as well?

**Comment by kf6gpe** [comment]
I claim that this has been addressed --- doing this now results in the following trying to compile:
```
Compiler message:                                                       
package:repo/main.dart: Error: No 'main' method found.                  
Try adding a method named 'main' to your program.    
```
