### ISSUE TITLE
Documentation missing for background execution

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#22080]
This was added recently by @bkonyi and he [posted on medium](https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124), however there [was feedback](https://github.com/flutter/flutter/issues/3671#issuecomment-423133583) we should also cover it on flutter.io

**Comment by ram231** [comment]
can you also add Inherited Model, i can't seem to find any tutorials or documentation about Inherited Model.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1986](https://github.com/flutter/website/issues/1986) via [**ZenHub**](https://www.zenhub.com/)
