### ISSUE TITLE
How to paint a border with this custom shape ?

### ISSUE THREAD

**Issue by nashfive** [flutter/flutter#22094]
Hi there!
I need to draw a Container (or any kind of Widget that can hold other widgets) with a custom border like the one on the attached screenshot. How can I draw those two semi-circle marks ?

I am looking at the source of `ShapeBorder` and its subclasses but I have no idea how to tackle this... 

Can anyone help me or point me to the right direction ? I am at loss here.

<img width="229" alt="shape" src="https://user-images.githubusercontent.com/50933/45838163-5ef4df00-bd11-11e8-9c25-564173eb628e.png">

_Note: I have been developing with Flutter for 2 months already, but I am totally new in custom painting with Flutter_

**Comment by sasukeamjed** [comment]
i am new to flutter too, but i think you can use paint class

**Comment by goderbauer** [comment]
Questions like this are probably better asked on StackOverflow.

**Comment by zoechi** [comment]
Similar 

- https://stackoverflow.com/questions/50205022/how-to-draw-a-custom-rounded-rectangle-border-shapeborder-in-flutter
- https://stackoverflow.com/questions/51232532/how-to-add-a-border-to-a-clipped-image/51241175#51241175
