### ISSUE TITLE
How do I add new CLI args to a Flutter launch via Atom?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2209]
I'd like to add "--verbose" to my flutter launches, via Atom. I clicked "Configure" and it opens the main.yaml. It's not clear where I add arbitrary CLI args.

Thanks!

**Comment by devoncarew** [comment]
In the `flutter` section, add `args: -v`. This needs better docs though.

**Comment by sethladd** [comment]
Where can I add an empty args: to be added to any new main.yaml file generated? I'll be happy to send the PR.

**Comment by devoncarew** [comment]
Hereabouts: https://github.com/dart-atom/dartlang/blob/master/lib/flutter/flutter_launch.dart#L74

**Comment by sethladd** [comment]
PR https://github.com/dart-atom/dartlang/pull/807
