### ISSUE TITLE
Support for Material bottom sheet

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#221]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [collinjackson](https://github.com/collinjackson)**
_Thursday Oct 22, 2015 at 23:43 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1749_

----

https://www.google.com/design/spec/components/bottom-sheets.html

**Comment by abarth** [comment]
@HansMuller Is this done?
