### ISSUE TITLE
Adapt Switch widget appearance to Platform

### ISSUE THREAD

**Issue by jklint-g** [flutter/flutter#22101]
The Switch widget should adjust its appearance to match the native control of the current platform (iOS vs android). There's a material guideline advising this, with example images https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

> Controls
>
> Android
> Use Material switches, checkboxes, and radio buttons.
> 
> iOS
> Native platform switches may be used as they have matching functionality and appearance as Material switches.

Flutter already adjusts appearance like this for the 3-dot PopupMenu (horizontal vs vertical) and for BackButtons. Switch is another basic widget which should adapt.

**Comment by Hixie** [comment]
cc @xster @HansMuller
