### ISSUE TITLE
Error: The getter 'boldText' isn't defined for the class 'dart.ui::AccessibilityFeatures'.

### ISSUE THREAD

**Issue by synonymous1984** [flutter/flutter#22119]
Hi there,

I´ve just **upgraded to Flutter 0.8.2** with "flutter upgrade". Now if I try to run my app the following error occurs:

**Stacktrace:**
`Restarted application in 1 232ms.
I/flutter ( 4122): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4122): The following _CompileTimeError was thrown building WidgetsApp-[GlobalObjectKey
I/flutter ( 4122): _MaterialAppState#cde2d](dirty, state: _WidgetsAppState#616e7):
I/flutter ( 4122): 'package:flutter/src/widgets/media_query.dart': error: line 67 pos 47:
I/flutter ( 4122): file:///Users/michaelfuerst2/Documents/Development/flutter/packages/flutter/lib/src/widgets/media_query.dart:67:47:
I/flutter ( 4122): Error: The getter 'boldText' isn't defined for the class 'dart.ui::AccessibilityFeatures'.
I/flutter ( 4122): Try correcting the name to the name of an existing getter, or defining a getter or field named
I/flutter ( 4122): 'boldText'.
I/flutter ( 4122):       boldText = window.accessibilityFeatures.boldText,
I/flutter ( 4122):                                               ^
I/flutter ( 4122):       boldText = window.accessibilityFeatures.boldText,
I/flutter ( 4122):                                               ^
I/flutter ( 4122): When the exception was thrown, this was the stack:
I/flutter ( 4122): #0      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:664:17)
I/flutter ( 4122): #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
I/flutter ( 4122): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
I/flutter ( 4122): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 4122): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 4122): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 4122): #44     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
I/flutter ( 4122): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
I/flutter ( 4122): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3634:5)
I/flutter ( 4122): #50     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3781:11)
I/flutter ( 4122): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3629:5)
I/flutter ( 4122): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2919:14)
I/flutter ( 4122): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2722:12)
I/flutter ( 4122): #54     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:881:16)
I/flutter ( 4122): #55     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:852:5)
I/flutter ( 4122): #56     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:798:17)
I/flutter ( 4122): #57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter ( 4122): #58     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:797:13)
I/flutter ( 4122): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:689:7)
I/flutter ( 4122): #60     runApp (package:flutter/src/widgets/binding.dart:728:7)
I/flutter ( 4122): #61     main (file:///Users/michaelfuerst2/Documents/Development/flutter_course/lib/main.dart:15:3)
I/flutter ( 4122): #62     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 4122): #63     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 4122): ════════════════════════════════════════════════════════════════════════════════════════════════════`

**System information:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.12.6 16G1510)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (1 available)

Maybe someone has a hint for me?

Thanks in advance,
best,
Michael

**Comment by SouthSouthWind** [comment]
Have you solved this problem?

**Comment by Maricha** [comment]
Same problem

**Comment by nakashima-koki** [comment]
Me too... 😢 
Flutter 0.8.2 not working
```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
[!] VS Code (version 1.27.2)
[✓] Connected devices (1 available)
```

**Comment by synonymous1984** [comment]
Nope, no solution yet. How do you switch the version of the flutter sdk? Is there a way besides manual checkout?

**Comment by synonymous1984** [comment]
Well, I solved it. You have to run "**flutter clean**" in your project directory. It seems that there are some parts in the build directory which get not replaced and are the reason for the incompatibility.

**Comment by berosoboy** [comment]
I think it should be mentioned in the flutter upgrading docs: https://flutter.io/upgrading/
