### ISSUE TITLE
Asset images in package dependencies package do not support local plugin

### ISSUE THREAD

**Issue by kongshanshan33** [flutter/flutter#22116]
The flutter_tools will determine path of package startWith file when parse .packages file. While local Plugin is relative path like '../' , so project cannot use package's assets. source:

```javascript
for (String packageName in packageMap.map.keys) {
      final Uri package = packageMap.map[packageName];
      if (package != null && package.scheme == 'file') {
        final String packageManifestPath = fs.path.fromUri(package.resolve('../pubspec.yaml'));
        final FlutterManifest packageFlutterManifest = await FlutterManifest.createFromPath(packageManifestPath);
        if (packageFlutterManifest == null)
          continue;
        // Skip the app itself
        if (packageFlutterManifest.appName == flutterManifest.appName)
          continue;
        final String packageBasePath = fs.path.dirname(packageManifestPath);

        final Map<_Asset, List<_Asset>> packageAssets = _parseAssets(
          packageMap,
          packageFlutterManifest,
          packageBasePath,
          packageName: packageName,
        );

        if (packageAssets == null)
          return 1;
        assetVariants.addAll(packageAssets);

        fonts.addAll(_parseFonts(
          packageFlutterManifest,
          includeDefaultFonts,
          packageMap,
          packageName: packageName,
        ));
      }
    }
```

**Comment by kongshanshan33** [comment]
Thank you for your reply。
I use ‘flutter create’ command to create a plugin package 'hello' . 
This plugin has a asset('icons/heart.png') that  is specified in the pubspec.yaml file of this plugin package. I use this code to load the asset that in 'example' like :
```javascript
AssetImage('icons/heart.png', package: 'hello')
```
But the the image can not show in screen。I unpacked the apk file and found that this asset does not exist. The '.pcakage' file about 'example' project is:
```javascript
hello:../lib/
```
When ‘flutter_tools’ bundle assets will ignore the assets of 'hello' plugin package  because  scheme of ‘hello’ package is not  ‘ file’ .

**Comment by zoechi** [comment]
Did you add `hello` to `dependencies` of the `pubpsec.yaml` of your application project?

```yaml
dependencies:
  hello:
    path: "../hello"
```

**Comment by kongshanshan33** [comment]
I add hello to dependencies of the pubpsec.yaml of your application project like this:
```javascript
 hello:
    path: ../
```

**Comment by zoechi** [comment]
That doesn't look like a valid dependency path. That points back to the self.

**Comment by zoechi** [comment]
I'm going to close the issue because it is a support request.
Feel free to add more comments and I'll try to respond, but there isn't anything for the Flutter team to do.

**Comment by kongshanshan33** [comment]
The dependency path is automatic generated when I create flutter plugin by ‘flutter create’ command.This is valid dependency path because I can run flutter project by android studio.

**Comment by zoechi** [comment]
Can you please demonstrate your package layout. 
Honestly I can't make any sense from the comments above so far.
