### ISSUE TITLE
Add currency icons to Icons class

### ISSUE THREAD

**Issue by sbadisa** [flutter/flutter#22126]
Currently, the only currency symbol icons available are for dollar symbol $ and euro symbol €.

Other major currencies would be a welcome addition (eg £, ¥, etc).

**Comment by zoechi** [comment]
What icons are you referring to exactly?

**Comment by sbadisa** [comment]
The icons in the IconData class. Eg

Icon(IconData euro_symbol).

Would be good to have other currencies also, mainly £, ¥ in my particular use case

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/material/Icons-class.html only contains material icons from https://material.io/tools/icons/ 
You would need to request these icons there.

https://pub.dartlang.org/packages/font_awesome_flutter might provide the icons you are looking for.

**Comment by sbadisa** [comment]
Thank you
