### ISSUE TITLE
Generate API docs for sky_services

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2212]
We no longer publish/push sky_services to pub.dartlang.org. Therefore, we need to start generating and hosting API docs for sky_services.

Once we have this, I can link to it from our Services doc page.

**Comment by sethladd** [comment]
@devoncarew is this something you can add to how we generate API docs for docs.flutter.io ? I'm compiling a list of all our services, and I'd like to link to docs for the services that come from sky_services. I'm not actually sure what's in there :) Thanks!

**Comment by devoncarew** [comment]
The doc generation is now entirely controlled by this script: https://github.com/flutter/flutter/blob/master/dev/dartdoc.dart#L52

If you pass another `--include-external` flag in there for `sky_services`, it _should_ show up as well. You can run the script locally; the results are written to dev/docs/doc/api.

**Comment by sethladd** [comment]
Nice! Trying it now.

**Comment by sethladd** [comment]
Thanks to @devoncarew , I am now using library names and not package names.

Addressed by https://github.com/flutter/flutter/pull/3170

**Comment by sethladd** [comment]
We are now generating docs for the libraries in sky_services.
