### ISSUE TITLE
Material + MaterialButton + borderRadius doesn't work anymore.

### ISSUE THREAD

**Issue by ilvassa** [flutter/flutter#22125]
Hello! this is for sharing a problem.
This code after the last update has lost his shape. I know it's a little triky... but before the update all was rounded and fitted.... Now the materialButton is rectangular and floating over the rounded shadow.
Nothing too problematic, I will use a FlatButton with a shape or something like that.. but like i said, it's for sharing the bug.

```dart
final roundedButton = Padding(
padding: EdgeInsets.symmetric(vertical: 16.0),
      child: Material(
        borderRadius: BorderRadius.circular(32.0),
        shadowColor: Colors.lightBlue,
        elevation: 5.0,
        child: MaterialButton(
          minWidth: 200.0,
          height: 42.0,
          onPressed: () { },
          color: Colors.lightBlue.shade900,
          child: Text('Button', style: TextStyle(color: Colors.white)),
        ),
      ),
```

**Comment by searchy2** [comment]
#21926

**Comment by zoechi** [comment]
@ilvassa does the linked issue answer your question?

**Comment by esthrim** [comment]
i have the same problem like zoechi and already tried the solution from the link above, but still not working 
`final loginButton = Padding(
      padding: EdgeInsets.symmetric(vertical: 16.0),
      child: Material(
          borderRadius: BorderRadius.circular(10.0),
          shadowColor: Colors.lightBlueAccent.shade100,
          elevation: 5.0,
          clipBehavior: Clip.antiAlias,
          child: MaterialButton(
              
              minWidth: 200.0,
              height: 42.0,
              onPressed: () {},
              color: Colors.lightBlueAccent,
              child: Text(
                'Log In',
                style: TextStyle(color: Colors.white),
              ))),
    );`

**Comment by ilvassa** [comment]
Yes it does!.... I'm sorry but I've tested it right now...

**Comment by fluttercorner** [comment]
[How to Create a rounded button / button with border-radius in Flutter](https://fluttercorner.com/how-to-create-rounded-button-button-with-border-radius-in-flutter/)
