### ISSUE TITLE
SwitchListTile has no controlAffinity property like CheckboxListTile or RadioListTile

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#22134]
Why does SwitchListTile has no **controlAffinity** property like CheckboxListTile or RadioListTile?

Please add, thanks!

**Comment by AyushBherwani1998** [comment]
@shihaohong is Flutter team looking forward to adding `controlAffinity` to the `SwitchListTile`?  I have not seen many use case where a switch is placed in a leading position.

If team is willing to add the property, I would like to work on the issue.

**Comment by AyushBherwani1998** [comment]
@shihaohong Also, in the documentation, it states that it doesn't have enough space to show `Switch` at `ListTile.leading`. Check [here](https://github.com/flutter/flutter/blob/af9b6a6efa83a3aec34577c6a4d65f833cc8282c/packages/flutter/lib/src/material/switch_list_tile.dart#L42). But, according to my understanding there are no space restrictions for `ListTile.leading`.

**Comment by shihaohong** [comment]
@YAPPDEF Could you describe your use case? I find it's a lot easier to justify implementing a feature when it's clear what type of work is being blocked. 

This would also help answer @AyushBherwani1998's question about whether or not we would like to add `controlAffinity` to `SwitchListTile`. Could you look into the history for the comment that you found? I'm not exactly sure why that comment was added either. Maybe add the feature and see what happens on a sample application?

**Comment by AyushBherwani1998** [comment]
@shihaohong I added the feature and tested the property in a sample application by positioning the `Switch` at `ListTile.leading` and it worked fine.

**Comment by shihaohong** [comment]
Looking at [git blame](https://github.com/flutter/flutter/blame/af9b6a6efa83a3aec34577c6a4d65f833cc8282c/packages/flutter/lib/src/material/switch_list_tile.dart#L42), it seems like this was a decision made when all the control [foo]ListTile widgets were created a few years ago. If adding the control doesn't cause weird layout issues, I don't see a problem with introducing the flexibility of `controlAffinity`.

> Also, in the documentation of ListTile there's an example which resembles YouTube video list where the Container is fairly large. Check here
That documentation is actually a demonstration that you `ListTile` is not a one size fits all widget. That sample is actually a Row with a bunch of widgets in it :)

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR, looking forward to reviews :)
