### ISSUE TITLE
flutter String API

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#22135]
Can string support format ?

case :

String.format("123{}344{}", 43, 54);  #print result:  1234334454

**Comment by vanesyan** [comment]
You can use interpolation for such purpose. And this issue isn't related to Flutter at all, rather to Dart itself.

Example:
```dart
final first = 43;
final second = 54;
final str = "123${first}344${second}";
```

**Comment by Seifon** [comment]
> You can use interpolation for such purpose. And this issue isn't related to Flutter at all, rather to Dart itself.
> 
> Example:
> 
> ```dart
> final first = 43;
> final second = 54;
> final str = "123${first}344${second}";
> ```

str I want to read config from preperties

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
