### ISSUE TITLE
DatePicker close on select & range possibility

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#22130]
1. Is it possible to add an additional parameter (eg. <bool> closeOnSelect) to close the date picker when a date is selected?
2. Is it possible to implement a range selection for a period as well?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Please add the output of `flutter doctor -v`.

Also please create a new issue for each feature request / bug report.
Using a single issue for multiple questions/requests/bugs is hard to maintain.

**Comment by zoechi** [comment]
Do you think there is still something to do for the Flutter team?
