### ISSUE TITLE
Loading Flutter Fragment in Android App is Slow

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#22133]
Including Flutter in existing apps is fantastic but the load times are very slow. It takes over 1 second to load flutter views/fragments. Is there a way to decrease the loading time?

## Steps to Reproduce
1. Create an Android app.
2. Add Flutter to Android app as module (https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)
3. Launch Flutter Fragment or View from Android app. This part is very slow and takes over a second to load. (Sample -> https://github.com/searchy2/FlutterAndroid)

Sample project -> https://github.com/searchy2/FlutterAndroid
Clicking on the FAB loads the Flutter view which takes a long time to load.

**Comment by searchy2** [comment]
I understand that loading Flutter inside an Android app requires loading an entire framework which means taking 1-2 seconds makes sense. Comparatively, loading only the Flutter app takes at least 0.6 seconds so I wouldn't expect it to be quicker. However, there should be ways to optimize using Flutter in an existing Android app right?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by searchy2** [comment]
```dart
[√] Flutter (Channel dev, v0.9.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.9.2 at D:\Development\flutter-sdk
    • Framework revision 85b4670b2a (5 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at D:\Development\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = D:\Development\android-sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment]
#22363 sounds related

**Comment by neiljaywarner** [comment]
@searchy2 Is it still slow in release mode? I discovered when i generated a release build from Android Studio I didn't have that delay.
Although I did take the flutterView stuff from FlutterFragment.java and pull it out in order to use method channel stuff..

**Comment by searchy2** [comment]
Let me fire up my FlutterAndroid repo, update everything, and give it a test again. Hopefully the loading times are faster with v1.2 around vs pre-release last time I tested.

**Comment by neiljaywarner** [comment]
Please observe if debug mode is in upper right or not

**Comment by searchy2** [comment]
I tested it again in debug mode and it still takes around 1 second to load up which I've said is fine. 

Unfortunately, I am unable to run it in release mode as it crashes anytime the Flutter module is loaded. I'll file an issue and try to see if I can get it working in release mode.

**Comment by searchy2** [comment]
As an aside, I ran into the biggest frustration I have with including Flutter in an existing Android app. 

Flutter generate the Flutter android files but uses an old targetSDK 27 and non-AndroidX libraries. My projects all target API 28 and use AndroidX which means I have to go in and manually edit multiple files everytime I want to start coding. My project doesn't even build correctly without manually editing the files. :(

**Comment by searchy2** [comment]
Here's the bug I'm running into with a production build:
```
    Process: com.flutter.android, PID: 23362
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.flutter.android-mhSz8YyZn1nTUTnv0BOciw==/base.apk"],nativeLibraryDirectories=[/data/app/com.flutter.android-mhSz8YyZn1nTUTnv0BOciw==/lib/x86, /system/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:159)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:134)
        at io.flutter.facade.Flutter.createView(Flutter.java:71)
        at com.flutter.android.MainActivity$onCreate$1.onClick(MainActivity.kt:23)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by neiljaywarner** [comment]
I had to put abi filters line in..

**Comment by searchy2** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Can you share that line of code with me? Much appreciate it - Ray                                                                                                                                                                          From: notifications@github.comSent: March 3, 2019 1:49 PMTo: flutter@noreply.github.comReply-to: reply@reply.github.comCc: ray.li.verified@gmail.com; mention@noreply.github.comSubject: Re: [flutter/flutter] Loading Flutter Fragment in Android App is Slow (#22133)  I had to put abi filters line in..

**Comment by neiljaywarner** [comment]
See:
https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd

**Comment by searchy2** [comment]
Sigh, opened up the project to try and build using the method you shared and all the generated files got reset. Going to create a brand new Android project and import a Flutter module to see if I can get your results. Otherwise, Flutter in Android is unworkable at the time being.

**Comment by searchy2** [comment]
Just tried creating a brand new Android project and adding a brand new Flutter module. Auto generated files are not compatible.

**Comment by searchy2** [comment]
A year later, loading Flutter in app is a lot faster and feels like native. Great job Flutter team; thanks for the continuous improvements!
