### ISSUE TITLE
Firestore runTransaction timeout does not stop the transaction

### ISSUE THREAD

**Issue by holyspidoo** [flutter/flutter#22140]
If you run a transaction with a timeout, when the timeout function runs, the transaction will still try its 5 attempts.

```
await Firestore.instance.runTransaction((Transaction tx) async {
          DocumentSnapshot postSnapshot = await tx.get(postRef);
          if (postSnapshot.exists) {
            await tx.update(postRef, mapData);
          }
        }).timeout(Duration(seconds: 5),onTimeout: (){throw("Timeout trying to update, maybe you're offline");});
```

To test: 

1. Turn off Wifi
2. Try to update
3. Wait for timeout
4. Turn Wifi on quickly
5. The update goes through to firestore

If you wait 25+ seconds before turning Wifi back on, it won't go through.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by holyspidoo** [comment]
Had the same issue with dev and beta channels for flutter

[✓] Flutter (Channel dev, v0.9.2, on Mac OS X 10.13.6 17G65, locale en-CA)
    • Flutter version 0.9.2 at 
    • Framework revision 85b4670b2a (4 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at 
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

**Comment by ironaraujo** [comment]
Is there a solution? I still did not find a way to suspend the action when timeout is called...

**Comment by kroikie** [comment]
@holyspidoo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/653. Any further collaboration will be done there.

**Comment by PritishSawant** [comment]
The timeout does not seem to work with cloud firestore. Though the timeout happens successfully, the operation continues. IS this a bug??

**Comment by ronak197** [comment]
> Is there a solution? I still did not find a way to suspend the action when timeout is called...
> 
> **EDIT 1**:
> I found out a solution. You just need to invoke the FirebaseDatabase method purgeOutstandingWrites inside your timeout function...
> 
> ```
> firebaseReference.set(....).timeout(Duration(seconds: 5),
>             onTimeout: () {
>       **FirebaseDatabase.instance.purgeOutstandingWrites();**
>       throw ("Without Internet?");
> }
> ```

How can this be done with Cloud Firestore? I can't find anything with purgeOutstandingWrites() for Firestore.instance.

**Comment by Christyansoft** [comment]
Anyone solution ? @PritishSawant did you get it ?
