### ISSUE TITLE
Lock down importing private Dart headers in engine source

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#22151]
We need to have a presubmit check that prevents headers like:

```c
#include "third_party/dart/runtime/bin/crypto.h"
#include "third_party/dart/runtime/bin/io_natives.h"
```

from being used.

Instead, we should expose the functionality in public Dart SDK headers such as dart_api.h or dart_embedder_api.h first and use that.

Either the presubmit should verify that every include of the form third_party/dart/* starts with "third_party/dart/runtime/include/" or we need to figure out a way to prevent these imports by limiting gn deps.

**Comment by mehmetf** [comment]
This prevents the engine from being compiled in Google.

**Comment by cbracken** [comment]
Looks like we're down to just:
```
shell/platform/embedder/tests/embedder_test_context.cc:9:#include "third_party/dart/runtime/bin/elf_loader.h"
shell/platform/embedder/tests/embedder_test_context.h:20:#include "third_party/dart/runtime/bin/elf_loader.h"
shell/platform/fuchsia/dart_runner/builtin_libraries.cc:13:#include "third_party/dart/runtime/bin/io_natives.h"
```

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by mehmetf** [comment]
There are no such sources in engine anymore so we can close this.
