### ISSUE TITLE
video player cannot play .flv netword stream video on IOS!

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#22165]
on ios,

video player cannot play xxxx.flv?param=xxx  netword video!

this video is stream video

help me, Thanks!

case: [http://hdla.douyucdn.cn/live/1863767rkpl_900.flv?wsAuth=48bd60fdeeb7364f24184c257613cc82&token=app-wp-0-1863767-fcc77a20199a90fdd19abfd57e276aef&logo=0&expire=0&pt=1](http://hdla.douyucdn.cn/live/1863767rkpl_900.flv?wsAuth=48bd60fdeeb7364f24184c257613cc82&token=app-wp-0-1863767-fcc77a20199a90fdd19abfd57e276aef&logo=0&expire=0&pt=1)

**Comment by Seifon** [comment]
http://pan.baidu.com/s/1dEq9q4h   password: ydm7

this ios demo support flv, I hope flutter video_player' core chang to this, Thanks

**Comment by zoechi** [comment]
I believe this is a dup of #21932

**Comment by Seifon** [comment]
> I believe this is a dup of #21932

yes, I hope video player plugin can be improved, thanks!
