### ISSUE TITLE
After upgrading to 0.9.2, All my old and newly created Apps are Stuck in main.dart execution 

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#22163]
Upgraded My SDK from `0.5.8 to 0.9.2` today and did a system restart but 
all my old and newly created Flutter apps are stuck befroe executing main.dart file.
Console Message:

> Built build\app\outputs\apk\debug\app-debug.apk.
> Error -32601 received from application: Method not found
> Application finished.

If i force stop the application and try again start debugging it runs the Default `Counter app,`
if i disconnected my mobile and open the debugging app,then i works well but not opening when connected with laptop

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
Have you tried `flutter clean`?

**Comment by rajeshjeshar** [comment]
not only for me i asked 2 devs they also said the same,on 0.8.2 thers no issues

**Comment by zoechi** [comment]
Please add the requested information.

**Comment by rajeshjeshar** [comment]
ill upgrade again tmrw then ill add the output as soon as possible

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
