### ISSUE TITLE
Row in container occupy full screen

### ISSUE THREAD

**Issue by gagaJay** [flutter/flutter#22169]
Hi guys, I have been searching around on google but did not find an answer. 

It seems like the container is not resized to the configured height and row height is not sized to fit the child widget. Please check below the simple code snippet that I written. My confusion is that: since the Container(red) is the root so it makes sense that it got stretched to fill the screen, but 
1. why the second container(blue) still occupy the whole screen(base on the doc it should resize to child)? 
2. Why the Row height is stretched to fill the screen too(thats why it got centerED in the middle)? Base on the doc, isn't it suppose to resize to fit the child as well?

I saw a stackoverflow post says don't use container as root but did not explain clear enough to me, I would like to know what is really happening under the hood. So thank you in advance.

`
  Widget build(BuildContext context) {

    return Directionality(
        textDirection: TextDirection.ltr,
        child: Container(
          height: 100.0
          decoration: BoxDecoration(color: Colors.red),
          // Row is a horizontal, linear layout.
          child: Container(
              color: Colors.blue,
              child: Row(
                children: <Widget>[
                  Text("Hello world"),
                ],
              )),
        ));
  }
`

![image](https://user-images.githubusercontent.com/3827781/45917717-d8d2c700-becf-11e8-8399-b47816d9b5f2.png)

**Comment by zoechi** [comment]
I think this is a dup of #5872.
See also the change in the PR that closed this issue #5904
