### ISSUE TITLE
flutter doctor not working

### ISSUE THREAD

**Issue by heartinfei** [flutter/flutter#22164]
~ flutter doctor
Downloading Dart SDK from Flutter engine 58a1894a1cd798de2f9a206f157a90d45944028b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93.6M  100 93.6M    0     0  7212k      0  0:00:13  0:00:13 --:--:-- 6959k
Building flutter tool...
Because flutter_tools depends on file 5.0.6 which doesn't match any versions,
  version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

**Comment by zoechi** [comment]
What OS?
What directory did you install Flutter to?
Are you behind a firewall/proxy? (China?)

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
