### ISSUE TITLE
"non-ASM statement in naked function is not supported" when building for armeabi

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#22172]
@mraleph 

Please have a look at a new wiki I built for flutter engine build
[Android-Builds-Supporting-armeabi](https://github.com/flutter/engine/wiki/Android-Builds-Supporting-armeabi)

I met up with a problem "non-ASM statement in naked function is not supported", where the code seems to be your commit.

So how can I fix the clang error?

KyleWongdeMacBook-Pro:skia kylewong$ flutter doctor -v
[✓] Flutter (Channel unknown, v0.8.2, on Mac OS X 10.14 18A389, locale en-CN)
    • Flutter version 0.8.2 at /Users/kylewong/Codes/fwn_idlefish/flutter
    • Framework revision 5ab9e70727 (2 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A254a
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

**Comment by mraleph** [comment]
This should fix it - https://dart-review.googlesource.com/c/sdk/+/76021 though it is hard to actually provide a reliable work-around for this bug.

**Comment by kangwang1988** [comment]
@mraleph 
Got it. Thanks.
