### ISSUE TITLE
after installing this plugin my app wont build on android

### ISSUE THREAD

**Issue by rayjadore** [flutter/flutter#22173]
the plugin breaks android app due to it require some dependencies yet unkonown please check it out.

 What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/14020#issuecomment-380178542 might help

**Comment by rayjadore** [comment]
geolocator

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Rushit4553** [comment]
resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.0.1"
            }
        }

Same issue with me after adding the dependency flutter_downloader, tried above solution but getting the same error, is it possible that multidex is getting ignores because of above code ? Please advise i'm stuck

**Comment by KarimMohamed2005** [comment]
@Rushit4553 
After you add this you will solve the problem but your app will crash in runtime
