### ISSUE TITLE
flutter packages get error

### ISSUE THREAD

**Issue by minh98** [flutter/flutter#22182]
i can't update packages after add mqtt lib 
i was remove mqtt, clean, restart ide but still has error
## Logs
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because every version of flutter_test from sdk depends on test 1.3.0 and mqtt >=1.1.4 depends on test ^0.12.0, flutter_test from sdk is incompatible with mqtt >=1.1.4.
And because mqtt >=1.0.2 <1.1.4 requires SDK version <2.0.0, flutter_test from sdk is incompatible with mqtt >=1.0.2.
So, because flutter_mqtt_test depends on both mqtt ^1.1.0 and flutter_test any from sdk, version solving failed.
pub get failed (1)
Process finished with exit code 1

```
```

```
```

```
```

**Comment by zoechi** [comment]
Closing as dup of https://github.com/jnguillerme/mqtt.dart/issues/16
