### ISSUE TITLE
Flutter needs to stay in sync with Material Design's standard icons

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2218]
The icons we're currently bundling with apps aren't up to date per the current MD spec.

The gallery "Menus" demo has run into this:
```
W/flutter : [WARNING:zip_asset_bundle.cc(167)] Requested asset 'action/ic_visibility_black_24dp.png' does not exist.
W/flutter : [WARNING:zip_asset_bundle.cc(167)] Requested asset 'content/ic_link_black_24dp.png' does not exist.
```

**Comment by abarth** [comment]
I'm going to solve this with #994

**Comment by ThinkDigitalRepair** [comment]
There's one I noticed that isn't the same. In Flutter, the [chat icon] 
<img width="57" alt="screen shot 2018-12-12 at 1 48 48 pm" src="https://user-images.githubusercontent.com/23037821/49900884-b4262580-fe14-11e8-916f-6d5324d8d2f3.png">
(https://docs.flutter.io/flutter/material/Icons/chat-constant.html) is mainly filled with color whereas the material design [chat icon](https://material.io/tools/icons/?search=chat&icon=chat&style=outline)
<img width="106" alt="screen shot 2018-12-12 at 1 48 40 pm" src="https://user-images.githubusercontent.com/23037821/49900906-bf795100-fe14-11e8-9794-8f1820158d9a.png">

is mainly stroked.

**Comment by zoechi** [comment]
The icons Flutter uses are from https://material.io/tools/icons/?search=chat&icon=chat&style=baseline

**Comment by ThinkDigitalRepair** [comment]
Oh... I didn't see that Dropdown before. Ok. Thanks for the clarification
