### ISSUE TITLE
Blank white screen on launching my flutter app on iOS 

### ISSUE THREAD

**Issue by Xbobo5530** [flutter/flutter#22188]
## Steps to Reproduce
1. Run the app on the iPhoneX simulator or my iPhone 6s.(The app and the developer are all verified)
2. The app runs Pod install and installs the application
3. When the app launches a blank white screen flashes before the app crashes with the logs below.

Note:
- The app uses cloud_firestore as a dependancy
- The app uses url_launcher as a dependancy

## Logs
```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001092531e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001088e8031 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001092c8975 +[NSException raise:format:] + 197
	3   Runner                              0x00000001046dec76 +[FIRApp configure] + 470
	4   Runner                              0x0000000104a385e9 -[FLTCloudFirestorePlugin init] + 185
	5   Runner                              0x0000000104a384a1 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 289
	6   Runner                              0x00000001046882fc +[GeneratedPluginRegistrant registerWithRegistry:] + 124
	7   Runner                        <…>


```

##xCodeLogs
```
2018-09-23 16:51:21.716428+0300 Runner[85771:19470478]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2018-09-23 16:51:22.239910+0300 Runner[85771:19469730] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2018-09-23 16:51:22.240079+0300 Runner[85771:19469730] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2018-09-23 16:51:22.322985+0300 Runner[85771:19469730] *** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b6941e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010ad29031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b709975 +[NSException raise:format:] + 197
	3   Runner                              0x00000001068d37f6 +[FIRApp configure] + 470
	4   Runner                              0x0000000106c2d309 -[FLTCloudFirestorePlugin init] + 185
	5   Runner                              0x0000000106c2d1c1 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 289
	6   Runner                              0x000000010687ced9 +[GeneratedPluginRegistrant registerWithRegistry:] + 121
	7   Runner                              0x000000010687d15a _T06Runner11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tF + 122
	8   Runner                              0x000000010687d94a _T06Runner11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tFTo + 186
	9   UIKit                               0x000000010c4596fb -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
	10  UIKit                               0x000000010c45b172 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4123
	11  UIKit                               0x000000010c4605cb -[UIApplication _runWithMainScene:transitionContext:completion:] + 1677
	12  UIKit                               0x000000010c822f7e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
	13  UIKit                               0x000000010cbf5a39 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	14  UIKit                               0x000000010c822bba -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	15  UIKit                               0x000000010c8233db -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 675
	16  UIKit                               0x000000010d194614 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 299
	17  UIKit                               0x000000010d1944ae -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	18  UIKit                               0x000000010ce7875d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
	19  UIKit                               0x000000010d0734b7 _performActionsWithDelayForTransitionContext + 100
	20  UIKit                               0x000000010ce78627 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	21  UIKit                               0x000000010cbf50e0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	22  UIKit                               0x000000010c45eeac -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
	23  UIKit                               0x000000010ca31bcb -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	24  FrontBoardServices                  0x0000000113c1a2f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 331
	25  FrontBoardServices                  0x0000000113c22cfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 225
	26  libdispatch.dylib                   0x000000010f0f47ec _dispatch_client_callout + 8
	27  libdispatch.dylib                   0x000000010f0f9db8 _dispatch_block_invoke_direct + 592
	28  FrontBoardServices                  0x0000000113c4e470 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	29  FrontBoardServices                  0x0000000113c4e12e -[FBSSerialQueue _performNext] + 439
	30  FrontBoardServices                  0x0000000113c4e68e -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	31  CoreFoundation                      0x000000010b636bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	32  CoreFoundation                      0x000000010b61b4af __CFRunLoopDoSources0 + 271
	33  CoreFoundation                      0x000000010b61aa6f __CFRunLoopRun + 1263
	34  CoreFoundation                      0x000000010b61a30b CFRunLoopRunSpecific + 635
	35  GraphicsServices                    0x000000011229ea73 GSEventRunModal + 62
	36  UIKit                               0x000000010c462057 UIApplicationMain + 159
	37  Runner                              0x000000010687daa7 main + 55
	38  libdyld.dylib                       0x000000010f171955 start + 1
	39  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

```
##flutter analyze
Analyzing linki...                                               
No issues found! (ran in 5.9s)
##
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Community Edition (version 2016.2.4)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    ✗ This install is older than the minimum recommended version of 2017.1.0.
[✓] VS Code (version 1.27.2)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.


```

**Comment by polbatllo** [comment]
Same issue.

**Comment by zoechi** [comment]
> could not find a valid GoogleService-Info.plist in your project.

Could it be there went something wrong when you added the Firebase plugin?

**Comment by polbatllo** [comment]
Actually I must clarify. In my case there are no errors displayed during the build process. However on release mode, the iOS build "randomly" shows only a blank screen. Out of 3 or 4 builds 1 usually works fine.

Sorry for the disturbance, the issue in my case is most likely not related with the current issue.

**Comment by maxlapides** [comment]
@polbatllo I'm having the same issue with my iOS builds. Have you figured anything out with regards to this?

**Comment by snstool** [comment]
Any solutions?

**Comment by lukestokes94** [comment]
@maxlapides I had the same issue, following a codelabs tutorial. I think the issue is the missing GoogleService-Info.plist, so if you ignore for now and download the plist from Firebase and add it to runner/runner, the app loads.

**Comment by Xbobo5530** [comment]
> @maxlapides I had the same issue, following a codelabs tutorial. I think the issue is the missing GoogleService-Info.plist, so if you ignore for now and download the plist from Firebase and add it to runner/runner, the app loads.

this worked. So I tried to add the GoogleService-Info.plist from firebase, and it worked. I don't know why the original one didn't work. Thanks guys.

**Comment by athornz** [comment]
I'm having issues with this as well. 

I've added the GoogleServices-info.plist file multiple times, but when running a release build, it's always a white screen.

Running from xcode does work though, it's only when building using the flutter tool that I get a white screen.

Any ideas?

**Comment by syn-rupendra** [comment]
> I'm having issues with this as well.
> 
> I've added the GoogleServices-info.plist file multiple times, but when running a release build, it's always a white screen.
> 
> Running from xcode does work though, it's only when building using the flutter tool that I get a white screen.
> 
> Any ideas?

Did anyone find a solution for this?

**Comment by illia-romanenko** [comment]
If you are building for device try to run flutter clean first & xcode clean - then follow tutorial on how to build for release from flutter site. Also it was important for me before building release from xcode to run flutter build ios from terminal.

**Comment by syn-rupendra** [comment]
> If you are building for device try to run flutter clean first & xcode clean - then follow tutorial on how to build for release from flutter site. Also it was important for me before building release from xcode to run flutter build ios from terminal.

On debug / run mode it works fine, but when I archive the app, it shows blank white screen.

**Comment by illia-romanenko** [comment]
I meant archive by "building for device"

**Comment by zoechi** [comment]
@syn-rupendra 

> On debug / run mode it works fine, but when I archive the app, it shows blank white screen.

for that you need to run `flutter build ios --release` before you archive the app.
This is a known issue.

**Comment by syn-rupendra** [comment]
> @syn-rupendra
> 
> > On debug / run mode it works fine, but when I archive the app, it shows blank white screen.
> 
> for that you need to run `flutter build ios --release` before you archive the app.
> This is a known issue.

Its working now, thanks... you are a lifesaver

**Comment by awazgyawali** [comment]
Why is there no update on an issue this serious? Every time I try to deploy apps to IOS I get a blank screen and have to go through all these steps again and again to fix it.

**Comment by juanjoserodrigolazaro97** [comment]
same problem it appears and disappears 1 month ago i have the problem then nothing now again....  

here i paste the logs of xcode when running the release version:

2019-08-14 17:24:05.665679-0400 Runner[6832:1874400] [DYMTLInitPlatform] platform initialization successful
W0814 17:24:06.374780 1 commandlineflags.cc:1503] Ignoring RegisterValidateFunction() for flag pointer 0x104b674d0: no flag found at that address
2019-08-14 17:24:06.884275-0400 Runner[6832:1874211] [VERBOSE-2:dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
2019-08-14 17:24:06.884309-0400 Runner[6832:1874211] [VERBOSE-2:dart_vm.cc(238)] Could not setup VM data to bootstrap the VM from.
2019-08-14 17:24:06.884320-0400 Runner[6832:1874211] [VERBOSE-2:dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
2019-08-14 17:24:06.884374-0400 Runner[6832:1874211] [VERBOSE-3:shell.cc(218)] Check failed: vm. Must be able to initialize the VM.

also throws a signal SIGABRT on flutterappdelegate

**Comment by flyrboy96** [comment]
@juanjoserodrigolazaro97 I am having the same issue.

**Comment by TheColdVoid** [comment]
@flyrboy96 I solve this problem by:

1. add `export NO_PROXY=localhost,127.0.0.1` to ~/.bashrc ( or ~/.zshrc if you use zsh )
2. `flutter clean`
3. close all IDE and simulator
4. re-run debug and then it worked;

**Comment by kroikie** [comment]
@Xbobo5530

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/650. Any further collaboration will be done there.

**Comment by shadowdom24** [comment]
Running `flutter clean` fixed things for me.

**Comment by 50shashwat** [comment]
I am having the same issue even in the debug app as well.

**Comment by urvashikharecha** [comment]
> @syn-rupendra

I am new to flutter and this issue comes may i know flutter build ios --release will this works on specific Devices??

**Comment by theindianappguy** [comment]
flutter clean worked for me
