### ISSUE TITLE
how to remove this block

### ISSUE THREAD

**Issue by rakeshlanjewarwork** [flutter/flutter#22189]
## Steps to Reproduce

https://gist.github.com/rakeshlanjewarwork/496a08e09720866cd8c5f40640267812
## Logs

screenshots:-
With Keyboard
https://ibb.co/k0X4Mp

Without Keyboard
https://ibb.co/eEt0u9

```
```

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.286], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
[√] Connected devices (2 available)

• No issues found!

**Comment by zoechi** [comment]
Can you please create a minimal reproduction - strip all code that is not absolutely necessary to reproduce the issue - and still have runnable that allows to reproduce?

**Comment by zoechi** [comment]
Might be a dup of #15947

**Comment by rakeshlanjewarwork** [comment]
Thanks! 

But I am Unable to reproduce !
