### ISSUE TITLE
I want to be able to easily retrieve the device's local image data and customize the rendering to the widget

### ISSUE THREAD

**Issue by EForinaJ** [flutter/flutter#22191]
When I was developing app, I sometimes wanted to get pictures of the device. Although the image_picker package in plugin was available, it couldn't make me customize the page, so it felt bad. 
We want to have access to the device's local albums and images, so we can customize the page rendering and select the images ourselves.

**Comment by zoechi** [comment]
As a workaround you could fork the plugin and replace the UI with your own.

**Comment by MichaelSowah** [comment]
I recently discorvered this 
https://pub.dartlang.org/packages/photo#-readme-tab-  
and this 
https://pub.dartlang.org/packages/photo_manager

Hope it helps
