### ISSUE TITLE
Feature Request: Callbacks for events that occur when the main app isn't running

### ISSUE THREAD

**Issue by dude8604** [flutter/flutter#22197]
I want to run a background service that can read certain events, process and possibly record the data, and if appropriate create a notification which will launch the main app if pressed. Some examples of the events would be: new Bluetooth device in range, incoming data on a socket, incoming data from a USB device, SMS received, GPS location changed, Bluetooth device connection attempt, a certain physical button is pressed, accelerometer data exceeds a specified value, if the main app is terminated, and a lot of other things I'm not thinking of.

Can someone make a comprehensive plugin (with a free or open source license) for this that works on iOS and Android? I know that iOS is more restrictive about background execution, but the plugin could include events associated with [these](https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW23) and their Android equivalents.

**edit: I'm aware of the new background execution feature. The problem is it's only for plugin developers, and requires a lot of platform specific code. I think there needs to be a higher level, platform independent plugin that is accessible to normal developers, not just plugin developers with experience in Android and iOS programming.

See https://github.com/flutter/flutter/issues/3671#issuecomment-423782376 and the responses.**

**Comment by zoechi** [comment]
Did you check https://pub.dartlang.org/packages/android_alarm_manager
See also #3671
https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

Please create more specific issues about what features you are missing.

**Comment by dude8604** [comment]
@zoechi I've been following that issue closely and I've already seen the links you posted. The problem is that the new background execution feature is for plugin developers, and requires a lot of platform specific code. I think there needs to be a higher level, platform independent plugin that is accessible to normal developers, not just plugin developers with experience in Android and iOS programming.

See https://github.com/flutter/flutter/issues/3671#issuecomment-423782376 and the responses.

**Comment by Pushan-Gupta** [comment]
Can you please provide some resources for "new background execution feature"? I might be able to help develop a plugin for different use cases like wifi trigger, notification execution or some others.

**Comment by dude8604** [comment]
https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

**Comment by zoechi** [comment]
closing as dup of #22072 because that has more upvotes

**Comment by dude8604** [comment]
@zoechi It's actually not a duplicate because that issue is for Firebase, but this feature is independent of Firebase.

**Comment by zoechi** [comment]
I think this is also covered by #24278

**Comment by dude8604** [comment]
> I think this is also covered by #24278

Yeah, I think you're right. You can close this issue.
