### ISSUE TITLE
Use .gni list of dart:mojo.internal sdk extension sources

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#222]
<a href="https://github.com/johnmccutchan"><img src="https://avatars.githubusercontent.com/u/224266?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [johnmccutchan](https://github.com/johnmccutchan)**
_Friday Oct 23, 2015 at 00:40 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1753_

----

The list of sources can be found in `mojo/public/dart/sdk_ext_sources.gni` with the name `dart_mojo_internal_sdk_sources`

**Comment by FlutterIssues** [comment]
<a href="https://github.com/johnmccutchan"><img src="https://avatars.githubusercontent.com/u/224266?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [johnmccutchan](https://github.com/johnmccutchan)**
_Friday Oct 23, 2015 at 00:45 GMT_

----

https://codereview.chromium.org/1421003002/ @chinmaygarde

**Comment by Hixie** [comment]
@johnmccutchan Is this resolved?
