### ISSUE TITLE
Make "flutter-build" github check wait for X minutes if the tree is closed

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#22208]
Majority of the failures in https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
are due to:
"Trybots failed. These were the failed builds: https://flutter-dashboard.appspot.com/build.html"
which comes from the "flutter-build" github check.

Would it be possible to have the check wait for X minutes if the tree is closed?
This is similar to how Chromium's tree check works in the Commit Queue.

The downside of this is that there could be a flood of changes submitted when the tree opens. It might not be too bad if the waiting period is kept relatively short. 30 minutes maybe?

**Comment by liyuqian** [comment]
Waiting for several minutes sounds reasonable to me. I'll check what's the best time to wait.

**Comment by rmistry** [comment]
If there are failures, the other rollers rerun their CQs after an hour if there are no new commits.
I have not been able to do this in the github roller because the checks API is not returning things like the "flutter-build".

Eg:
Go to https://github.com/flutter/flutter/pull/22280
Click on the checks tab https://github.com/flutter/flutter/pull/22280/checks

This is the small subset of all the checks that the API returns, it does not include any of the other non Cirrus CI checks.

**Comment by liyuqian** [comment]
@yjbanov : if we don't change the status frome failure to pending, do you know how to add "flutter-build" check information to https://github.com/flutter/flutter/pull/22280/checks ?

**Comment by liyuqian** [comment]
@rmistry : I think that the status API already provided us the name of a failed test. For example:

https://api.github.com/repos/flutter/flutter/commits/903ee7255d1468deaddd712aa4ea4bb13d241afc/statuses

So it seems to me that we can just change the auto-roller without changing anything else?

**Comment by liyuqian** [comment]
BTW, it seems that the auto-roller is currently using the combined status API:

https://api.github.com/repos/flutter/flutter/commits/903ee7255d1468deaddd712aa4ea4bb13d241afc/status

The "flutter-build" name should be available in the "context" field.

**Comment by rmistry** [comment]
Yes the auto-roller is using the combined status API:
https://skia.googlesource.com/buildbot/+/master/go/github/github.go#251
from:
https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

But there is no way to rerun a "status".
The new checks API lets you rerun a check suite:
https://developer.github.com/v3/checks/suites/#rerequest-check-suite

But "flutter-build" does not show up there
If you figure out a generic way to do this [1] let me know, the only way I found was the checks API. But there may be another way I did not yet find.

[1] You can play with the github API, and point it to a flutter PR, using even python.

**Comment by yjbanov** [comment]
@rmistry what the auto-roller do when it sees a pending status? Can it do the same thing when it sees a failed "flutter-build"?

**Comment by rmistry** [comment]
The auto-roller does not do anything when it sees a pending status. It waits till the status is success or failure.

**Comment by yjbanov** [comment]
Can it do the same thing when "flutter-build" says it's broken?

**Comment by yjbanov** [comment]
> It would be a hack.

To use "pending" check status for a broken build is also a hack :)

> the right fix (IMO) should be to have flutter-build wait X minutes (what this bug is for)

I am not yet able to translate your original request to Flutter's infra. For example:

> Would it be possible to have the check wait for X minutes if the tree is closed?

This question does not make sense in Flutter case. The build status check and "tree is closed" are not independent things. The build status check is how we close the tree in the first place.

To be fair, failing a PR check to indicate "tree is closed" is also kind of hacky. We only use this approach because GitHub doesn't give us anything better. The current system was built for human contributors and not auto-rollers. Our contributors are already used to the various visual cues associated with this check. Changing it will affect that. Which is why I strongly prefer that we fix the auto-roller rather than re-educate Flutter contributors.

**Comment by rmistry** [comment]
I think the disconnect here is that I completely do not understand how flutter-build works.
I kind of understand what cirrus checks are. I also understand how Chromium's Commit Queue tree status verifier works: It waits for the tree to be open.

Keeping in mind that I do not know how flutter-build works: Is it possible to convert it into a cirrus check and still make it do what it does today, so that workflow does not have to change? 
Trying to explore all other possibilities first before introducing that hack into the autoroller framework, which is used by 30 other rollers into 9 different repositories.

**Comment by yjbanov** [comment]
Our CI system (a.k.a. "Cocoon") continuously monitors the build and computes the overall build status based on the latest history of individual builds. You can see the same data on the [dashboard](https://flutter-dashboard.appspot.com/build.html).

The CI system marks all of the commits in the currently pending pull requests with the build status under the "flutter-build" check. If the latest build status is a success, all the PRs are marked with "flutter-build" check as passing, allowing the PRs to be submitted freely, which is the same having an "open tree". If the latest build status is a failure, all the PRs are marked with "flutter-build" check as failed and a message encouraging contributors to fix the build before merging anything else. The PRs cannot be merged freely (you have to override Github UI to force-merge the PR). This has the effect of closing the tree.

**Comment by rmistry** [comment]
Thank you for the explanation. Sounds like there is no way to do the cirrus check and the original "wait for tree open" request. I'm going to file an skbug.com for tracking.

**Comment by rmistry** [comment]
One more question:
Lets say the CI marks a pending PR as "flutter-build" check failed.
When the build status is eventually green, does the CI go back to the same pending PR and mark "flutter-build" as success?

**Comment by gspencergoog** [comment]
Yes, it does.

**Comment by liyuqian** [comment]
Sorry that I missed much of the discussion in the last 2 days as I was busy solving a thread issue in retained rendering. Is there anything that I can help with issue now? I guess that I'll have to close https://github.com/flutter/cocoon/pull/230, right?

**Comment by rmistry** [comment]
FYI: This is done.

- https://github.com/flutter/flutter/pull/22704 - waited for 2 hours for the tree to open and then merged.
- https://github.com/flutter/flutter/pull/22709 - has been waiting for the tree to open for the last 10+ hours. Will merge after the tree opens next.

**Comment by liyuqian** [comment]
Thank you!
