### ISSUE TITLE
Usage of Websocket, STOMP in flutter application

### ISSUE THREAD

**Issue by srivanigorthi** [flutter/flutter#22203]
While trying to work with STOMP, websockets, facing issue for "packages get" after updating pubspec with required stomp/websocket details. I have tried for stomp, stompdart, websocket none of them worked.
Error observed while running "packages get" is
"The current Dart SDK version is 2.1.0-dev.4.0.flutter-4eb879133a.

Because project_name depends on stompdart >=0.0.2 which requires SDK version >=1.5.0 <2.0.0, version solving failed.
pub upgrade failed (1)"

If I try to downgrade flutter version then it has thrown exception informing 'current project needs SDK version > 2.0.0

Please help to clear the issue or suggest some other way as I am using STOMP at server end.

**Comment by zoechi** [comment]
` which requires SDK version >=1.5.0 <2.0.0, ` means the package is not compatible with Dart 2.
Please report the issue there instead.

**Comment by srivanigorthi** [comment]
@zoechi Can you please let me know where should I report the issue.

**Comment by zoechi** [comment]
The `stompdart` package should have a homepage link in pub.dartlang.org that usually leads to its GitHub repo.

**Comment by srivanigorthi** [comment]
> The `stompdart` package should have a homepage link in pub.dartlang.org that usually leads to its GitHub repo.

Thank you. Posted issue in concerned location.

**Comment by srivanigorthi** [comment]
@zoechi No response from the concerned location, @michaelkrog  informed repo is old and dead, and owner marked repository as archived. Please help me to connect to spring stomp from flutter. Is there any possible way for that?

**Comment by zoechi** [comment]
I don't think there is anything Flutter can do.
If the package is outdated it needs to be updated. It is open source. You can fork it and fix it.

**Comment by srivanigorthi** [comment]
@zoechi Can you please let me know is there any way to connect from flutter(client) to spring websocket(server) to receive broadcasted messages from server.

**Comment by srivanigorthi** [comment]
@zoechi Is there any other way to connect?  Do you have idea to clear the issue? Do you have any idea how to connect from flutter(acting as client) to spring websockets ( acting as server) to receive the messages broadcasted from server?

**Comment by srivanigorthi** [comment]
@zoechi Is there any other way to connect? Do you have idea to clear the issue? Do you have any idea how to connect from flutter(acting as client) to spring websockets ( acting as server) to receive the messages broadcasted from server?

**Comment by srivanigorthi** [comment]
@zoechi Is there any other way to connect? Do you have idea to clear the issue? Do you have any idea how to connect from flutter(acting as client) to spring websockets ( acting as server) to receive the messages broadcasted from server?

**Comment by srivanigorthi** [comment]
@zoechi Can you please suggest
