### ISSUE TITLE
Firestore ios bug

### ISSUE THREAD

**Issue by apnero** [flutter/flutter#22200]
Hi.  This should work.  It broke in late June.  It works on Android.  The error comes up only in iOS (simulator and ipad).
I'm am requesting an empty reference because I want to save the reference UID with the record.

From `firebase.firestore.CollectionReference` API:

> doc(documentPath) returns `firebase.firestore.DocumentReference`
> 
> Gets a `DocumentReference` for the document within the collection at the specified path. If no path is specified, an automatically-generated unique ID will be used for the returned `DocumentReference`.
> 

Code:
------------------------------------------------------------------------------------------
```dart

    final CollectionReference refSelections = Firestore.instance.collection('Selections');

    Firestore.instance.runTransaction((transaction) async {

        try {
          final DocumentSnapshot newDoc = await transaction.get(refSelections.document());
          ....
          ....
        }
        catch (error) {
          print(error);
        }

  }
```
-----------------------------------------------------------------------------------------

```
      ] flutter: PlatformException(DOCUMENT_NOT_FOUND, Document not found., null)
[   +1 ms] [DEVICE LOG] 2018-09-23 23:51:47.931981-0400  localhost Runner[20869]: (Flutter) [VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
[        ] [DEVICE LOG] PlatformException(9, Transaction failed all retries., null)
[        ] [DEVICE LOG] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
[        ] [DEVICE LOG] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
[        ] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #2      Firestore.runTransaction (file:///Users/andrew/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.7.2/lib/src/firestore.dart:115:10)
[        ] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #3      FirebaseCalls.modifySelection (package:nero_restaurant/services/firebase_calls.dart:86:24)
[        ] [DEVICE LOG] #4      _AnimatedFabState._onAddToCartClick (package:nero_restaurant/ui/item_page/animated_fab.dart:204:19)
[        ] [DEVICE LOG] #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
[        ] [DEVICE LOG] #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
[        ] [DEVICE LOG] #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recog<…>
[        ] [VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
[        ] PlatformException(9, Transaction failed all retries., null)

```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by apnero** [comment]
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.8.2 at /Users/andrew/Documents/development/flutter
    • Framework revision 5ab9e70727 (2 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices (1 available)
    • iPhone X • 04A736E8-A478-43F0-908D-8314DC1FD73E • ios • iOS 11.3 (simulator)

**Comment by miduch** [comment]
hello, 
Any news about this? tried older 0.7.4 version also but it also has similar issue on iOS. 
Android works fine 

21:00:06.749 1662 info flutter.tools [+16582 ms] [DEVICE LOG] 2018-10-07 21:00:06.741062+0300  localhost Runner[48043]: (Flutter) flutter: create profile error: PlatformException(9, Transaction failed all retries., null)
21:00:06.749 1663 info flutter.tools [        ] flutter: create profile error: PlatformException(9, Transaction failed all retries., null)

**Comment by apnero** [comment]
Hi,
I haven't heard anything.

I have a simple work-around for what I'm using it for.

My goal was to save the UID of the document inside the record.  So when someone selects the record off a list, a cloud function would be called with the UID as a parameter.

My workaround was to do a separate add then update call:

final DocumentReference docRef =await refSelections.add(selection.toMap());
await docRef.updateData({'selectionId': docRef.documentID});

**Comment by miduch** [comment]
thanks @apnero , took into use workaround for iOS. Hopefully this gets fixed soon

**Comment by zoechi** [comment]
Duplicate of #18747

**Comment by kroikie** [comment]
@apnero

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/648. Any further collaboration will be done there.
