### ISSUE TITLE
Listview has been added indefinitely when changing state

### ISSUE THREAD

**Issue by qq277049** [flutter/flutter#22209]
Why update the listview state, it will be added cyclically.

After viewing, there will always be an infinite request interface.

How to write code to properly request and update the list view 

    import 'package:flutter/material.dart';
    import 'package:http/http.dart' as http;
    import 'dart:convert';
    import 'package:video/AppConfig.dart';
    
    class Home extends StatefulWidget{
      @override
      State<StatefulWidget> createState() {
        // TODO: implement createState
        return HomeState();
      }
    }
    
    class HomeState extends State<Home> {
      double _width = 0.0;
    
      Widget build(BuildContext context) {
        this._width = MediaQuery.of(context).size.width;
        print(this._width);
        return new Scaffold(
          appBar: new AppBar(
              title: new Text("这个是首页的")
          ),
          body: new ListDislay(),
        );
      }
    
    
    }
    
    //动态列表
    class ListDislay extends StatefulWidget {
      @override
      State<StatefulWidget> createState() {
        // TODO: implement createState
        return ListDisplayState();
      }
    }
    
    class ListDisplayState extends State<ListDislay>{
      List _card = new List();
      double _width = 0.0;
      Widget build(BuildContext context){
        this._width = MediaQuery.of(context).size.width;
        this.getList();
        return new Scaffold(
          body:new ListView.builder(
            itemCount: _card.length,
            itemBuilder: (context,i){
              //          return _card[i];
              print("长度:"+this._card.length.toString());
              return new GestureDetector(
                child: _card[i],
                onTap: (){
                  print("点击索引"+i.toString());
                },
              );
            },
          ) ,
        );
      }
    
      getList() async{
        var url = AppConfig.base + '/api/new_list';
        //向指定URL发送GET请求
        http.get(url).then((response) {
          var data = json.decode(response.body);
          var _TempCard = [];
          data.forEach((v){
            print(v);
            _TempCard.add(new Card(
              child: new Flex(
                direction: Axis.vertical,
                children: <Widget>[
                  new Image.network(
                    AppConfig.base + '/file/'+v["Id"]+'/1.jpg',
                    fit: BoxFit.fill,
                    width: this._width,
                    height: 200.0,
    //              width: new Width,
                  ),
                  new Text(v["Originalname"])
                ],
              ),
            ));
          });
          //Update the status here, it will always be added infinitely
          setState(() {
            this._card = _TempCard;
          });
        });
    
      }
    }

**Comment by zoechi** [comment]
Just don't call `this.getList()` in `build()`. `build()` is expected to be called repeatedly and at various times. You can call it in `initState()` or better outside of Flutter widgets in the model or similar.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
