### ISSUE TITLE
android 4.2 OS Error: Invalid argument, errno = 22

### ISSUE THREAD

**Issue by FangWW** [flutter/flutter#22213]
android 4.2

```dart
     File file = await new File(
              '${(await getExternalStorageDirectory()).path}/poster/poster-${DateTime.now()}.jpg')
          .create(recursive: true);
      await file.writeAsBytes(pngBytes);
```
```
FileSystemException: Cannot open file, path = '/mnt/sdcard/poster/poster-2018-09-25 00:04:39.777259.jpg' (OS Error: Invalid argument, errno = 22)
```
i have a exception.

**Comment by zoechi** [comment]
What path does this code print?
```
File file = await new File( '${(await getExternalStorageDirectory()).path}/poster/poster-${DateTime.now()}.jpg');
print('===${file.path}===');
```

**Comment by FangWW** [comment]
print('===${file.path}===');   print:
` ===/mnt/sdcard/poster/poster-2018-09-25 22:47:01.966116.jpg===`

`E:\workspace5_studio\greatMen>flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.2.9200], locale en-US)
    • Flutter version 0.8.2 at D:\ProgramData\flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\ProgramData\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • MI • 127.0.0.1:26944 • android-x86 • Android 4.2.2 (API 17)

! Doctor found issues in 1 category.
`

**Comment by FangWW** [comment]
but can only generate folders without generating files.

**Comment by zoechi** [comment]
> but can only generate folders without generating files.

what does that mean?

**Comment by FangWW** [comment]
` File file = await new File(
              '${(await getExternalStorageDirectory()).path}/poster/poster-${DateTime.now()}.jpg')
          .create(recursive: true);`

but only generate folders ('/mnt/sdcard/poster/')without generating files(*.jpg).

**Comment by FangWW** [comment]
Thank You're right !

**Comment by FangWW** [comment]
Hope to be compatible with this problem.

**Comment by zoechi** [comment]
So `foo.jpg` is created, but `/mnt/sdcard/poster/poster-2018-09-25 22:47:01.966116.jpg` is not?

**Comment by FangWW** [comment]
yes

**Comment by FangWW** [comment]
yes

**Comment by zoechi** [comment]
Might be https://stackoverflow.com/questions/18685348/why-does-fopen-thown-errno22-when-i-use-the-file-name-with-colon-in-android
