### ISSUE TITLE
We should keep track of our symbols for released engines

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2221]
Currently, if we have an engine crash, we have no way to symbolize the stack trace. We should be able to take a stack trace and the `flutter --version` output and get something useful out.

**Comment by eseidelGoogle** [comment]
Ran into this with https://github.com/flutter/flutter/issues/490#issuecomment-226021171 again just now.  our published `android_x86/lib_skyshell.so` is stripped, so I'd have to build my own to symbolicate that stack trace.

**Comment by eseidelGoogle** [comment]
We do this now.  I've documented the (currently manual) process for using them:
https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks
