### ISSUE TITLE
Flutter Debug: Syncing files to device

### ISSUE THREAD

**Issue by cosminstoinescu** [flutter/flutter#22229]
After an upgrade, done with **flutter upgrade** command, Android Studio stopped working properly when running a flutter project in debug mode.

Here is what the Console sowes:
Launching lib\main.dart on ALE L21 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device ALE L21...

Seems that there is a problem with the syncing files process because Android Studio remain blocked at this line and on the device the aplication was instaled, and started but the screen is white, so no screen is loaded. 

**Important**
If I press **Stop** button in Android Studio, in the Console are added the following 2 lines:
Error -32601 received from application: Method not found
Application finished.

![syncing](https://user-images.githubusercontent.com/36987703/45975550-2e80ae00-c04d-11e8-8862-57779c5f6391.PNG)

But on the device, the application that remained stuck is not closing, so I need to do a force stop using the mobile application manager.

If I try to start manually the newly instaled application, on the device, I workes fine.
Also if I use **Run(Shift+F10)** to build my application, everything works.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Have you tried `flutter clean`?
Have you tried with a new project?
Does your code have by any chance something to do with cryptocurrency?

**Comment by cosminstoinescu** [comment]
I installed Android Studio on another device, install flutter plugin and it works. I suppose that something went wrong with the flutter upgrade process for the other device.

If you will have a look at the attached image you will see that after 
**Gradle task'assembleDebug'...** 
I receive 
**timeout waiting for the application to start**
![image](https://user-images.githubusercontent.com/36987703/46022958-452a1200-c0ec-11e8-91fd-079af2b71b26.png)

Have any idea why this can happen?

Yes I tried flutter clean command, also deleted manually the build content.

**Comment by zoechi** [comment]
Hard to tell. It's likely something outside Flutter. Either an issue with the device or `adb`.
Perhaps manually uninstalling the app from the device, running `adb kill-server`, restarting the computer, ... might solve it.

**Comment by oexza** [comment]
I have this very same issue.

**Comment by yannbanvi** [comment]
If you are using Android Studio, Invalidate Caches and Restart... may solve the problem. It worked for me.

**Comment by TrumanCai** [comment]
This message comes from [here](https://github.com/flutter/flutter/blob/db9fe3f827836a0b29657d24bb87be90c5fca2c3/packages/flutter_tools/lib/src/commands/daemon.dart#L434).
I think this is not kind of issue, or maybe it just a output to confuse us, because everything seems like normal.

**Comment by gbaldeck** [comment]
I am having this issue as well. I have a Windows 10 system and a Windows 7 system and it only seems to be happening on my Windows 7 system. I can't even start my app now though... so this is a serious problem. Has anyone found a solution?

**Comment by kissoflove** [comment]
Just run a few times more.

**Comment by muhannadshubita** [comment]
Just came across this issue today for the first time!

I tried "flutter clean", running "flutter doctor -v" to look for issues but everything seemed OK, switched flutter channels from stable to dev, etc. nothing worked until I finally unplugged my Android tablet from one USB port & into another and it worked :)

Still, this happens randomly, I was playing around with hot reload, after adding an import which later generated a compilation error, the app stopped responding to hot reload and no error came up. I restarted the app, encountered the compilation error, fixed it, tried another restart and now stuck on "Syncing files to device.." again!

**Comment by kevin-haynie** [comment]
I have the same issue.  Device doesn't seem to make any difference.  Would appreciate a fix as this very much slows down development.  :-(

**Comment by NaagAlgates** [comment]
And today I'm facing this issue!

**Comment by wjnesham** [comment]
"Syncing files to device William’s iPhone..."
Is there a fix yet?
Hopefully there is one before my iPhone syncs files, lol

**Comment by kevin-haynie** [comment]
Yup.  I still have the same problem....

**Comment by jclink** [comment]
I ran into this today, and many times in the past.
Flutter clean, upgrade, doctor, and adb anything, did not work.

**What did work**:
 Open AVD Manager, wipe device data -> restart app.  

Problem had gone away for a while, but reappeared just after update.

**Comment by antonvalletas** [comment]
This is happening to me right now, and can't get it to work and I have tried absolutely everything, it is making developing very hard and tedious. Please help. flutter doctor -v attached:

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /opt/flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/valletas/Android/Sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

**Comment by Radkeke** [comment]
I had this problem today, and found somewhere in logs we have to put `WidgetsFlutterBinding.ensureInitialized();` before `runApp();` call,  becouse of error:

> ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.

In my case it was caused by using camera plugin async in main().
Now everything works perfect for me.

**Comment by alokkumax** [comment]
wait. what!!!! it was simple!!!!
it's actually a code error that usually comes in the run-App section.
if not,
then rewrite your code,
if not clear caches and restart.
thanks.
hope it helps.

**Comment by antonvalletas** [comment]
> This is happening to me right now, and can't get it to work and I have tried absolutely everything, it is making developing very hard and tedious. Please help. flutter doctor -v attached:
> 
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
> • Flutter version 1.12.13+hotfix.5 at /opt/flutter
> • Framework revision [27321eb](https://github.com/flutter/flutter/commit/27321ebbad34b0a3fafe99fac037102196d655ff) (12 days ago), 2019-12-10 18:15:01 -0800
> • Engine revision 2994f7e1e6
> • Dart version 2.7.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> • Android SDK at /home/valletas/Android/Sdk/
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-29, build-tools 29.0.2
> • Java binary at: /opt/android-studio/jre/bin/java
> • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.5)
> • Android Studio at /opt/android-studio
> • Flutter plugin version 42.1.1
> • Dart plugin version 191.8593
> • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
> • IntelliJ at /opt/intellij-idea-ultimate-edition
> • Flutter plugin version 42.1.4
> • Dart plugin version 193.5731

This is still happening to me on Linux Kernel 5.5 but not on 5.4 for some reason...

**Comment by v4rakh** [comment]
I can confirm, starting from 5.5.0 synching never stops. Works fine on the LTS 4.19 kernel.

**Comment by nojusr** [comment]
Same problem here, everything worked fine before I upgraded to kernel version 5.5.1

**Comment by Rowisi** [comment]
kernel 5.5.1 is broken.

I need to use LTS kernel for now.

**Comment by JulianVolodia** [comment]
Same issue for me on Arch Linux. Does someone traced that error and know anything about it? Maybe you know sth @v4rakh ? @Rowisi @nojusr ?

**Comment by vladimir-kirillovskiy** [comment]
I also have the same problem on Arch Linux kernel 5.5.2
Android studio does render at least something, but syncing never stops. VS Code doesn't render anything at all. 
Is there any ticket for this issue? any additional information required?

**Comment by JulianVolodia** [comment]
@vladimir-kirillovskiy Idk. As I was using pretty old machine to run this with Nexus 5X emu on it, I got many errors. On real device was not working and I just got fallback to linux-lts - for 2 next weeks don't have time for more inspection.

**Comment by vladimir-kirillovskiy** [comment]
@JulianVolodia I see, thank you, will fallback as well

**Comment by Rowisi** [comment]
> Same issue for me on Arch Linux. Does someone traced that error and know anything about it? Maybe you know sth @v4rakh ? @Rowisi @nojusr ?

Linux 5.5 is marked as very unstable now. Many people are complaining about critical bugs(GPU, USB, ...) in the archlinux reddit section.

**Comment by alfianguide** [comment]
So it's because the arch linux kernel? same here on kernel 5.5.3

**Comment by Rowisi** [comment]
it wasn't a kernel [issue](https://github.com/flutter/flutter/issues/49185#issuecomment-586259403)

**Comment by alfianguide** [comment]
Then what?

**Comment by alfianguide** [comment]
Ah dart:io

**Comment by andycute** [comment]
still does not fixed yet?

**Comment by alfianguide** [comment]
Nah

**Comment by JulianVolodia** [comment]
@andycute @alfianguide as @vladimiry said, 3rd party have been fixed.

**Comment by JulianVolodia** [comment]
And, last  but not least dear @dnfield "thumbing up" is disabled after your lock out of issue, so bear it in mind (or sorry if that was desired). I will rather propose changing FAQ and count subscribers than thumbed out - this second action is almost always irrelevant (if you are involved with subscribe button, so you are intrested in changes of this issue, so you "like" it, already).

**Comment by Rowisi** [comment]
Dear @JulianVolodia please stop spamming. The issue will be fixed soon and ported directly to stable. If you want to use flutter now just use LINUX LTS

**Comment by dnfield** [comment]
@JulianVolodia the locked issue is actively being worked on. It has attention from the right people. It was attracting unhelpful noise, so I locked it.  I will update the faq to explain this.

**Comment by dnfield** [comment]
I've updated the issue hygiene wiki to address this specific case: https://github.com/flutter/flutter/issues/49492  @JulianVolodia please feel free to contact me directly if you have any concerns about this or want to discuss it further.
