### ISSUE TITLE
Inline Google Maps - zoom crash

### ISSUE THREAD

**Issue by cosminstoinescu** [flutter/flutter#22228]
"Go to London"  button set attributes:
- bearing: 270.0
- target: LatLng(51.5160895, -0.1294527)
- zoom: **17.0**

Case 1:
If I press '**Go to London**' button, the map goes at the specified location. 
Next I try to do a **zoom out** and the application stop working and closes, please see the attached video.

Case 2:
Also, after pressing '**Go to London**' button, next do **zoom in** (everithing works when I do zoom in), and after followed by a **zoom out**, the zoom out action works until the value reaches zoom **17.0**.

[google maps issue.zip](https://github.com/flutter/flutter/files/2412532/google.maps.issue.zip)

Log file: 
[Log.txt](https://github.com/flutter/flutter/files/2412555/Log.txt)

**Comment by zoechi** [comment]
Is this a dup of #22078 ?

**Comment by cosminstoinescu** [comment]
Yes

**Comment by zoechi** [comment]
Merging with #22078

**Comment by chanchanbn** [comment]
Do you have a solution for this issue?
