### ISSUE TITLE
change color of DataTable rows and columns

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#22220]
I have a small data table and i want to change the column and row color 
but unfortunately there is no property in DataColumn or DataRow to achieve this.
the only way i found is through modifying the label of DataColumn 
DataColumn(label: Container(child: Text('Person'),color: Colors.amberAccent,)),

but there is a default padding for the DataColumn and the color only applies to the text.

**Comment by zoechi** [comment]
I'll merge this as dup of #21864

**Comment by frimansyah01** [comment]
Please take a look on this refference guys:
https://stackoverflow.com/questions/58398787/fixed-column-and-row-header-for-datatable-on-flutter-dart/58467209#58467209

So u can modify the color on it.
