### ISSUE TITLE
FlutterCommand.argParser should allow trailing options

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#22231]
https://github.com/flutter/flutter/blob/989cf18b0daed99ea7c83226bd76fa39693bf94c/packages/flutter_tools/lib/src/runner/flutter_command.dart#L76

We should set this to true: it makes it easy for a run command to break when you accidentally give options out of order and some of them are ignored by the parser.

**Comment by mehmetf** [comment]
I added customer crowd here since this affects all of Google customers.

I am also not sure whether this is a new feature as opposed to a bug fix.

**Comment by Hixie** [comment]
Can you clarify what is being requested here? Specifically, what problem it solves?

**Comment by dnfield** [comment]
I'm going to close this since it seems like the bot is just missing it - it's had the label for > 21 days.

@DaveShuckerow if you want to add more details feel free to reopen.
