### ISSUE TITLE
Feature Request: Native Extensions for Flutter

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#22248]
For Dart VM we have [native extensions](https://www.dartlang.org/articles/dart-vm/native-extensions), which would be useful for working with various pure c libraries on iOS and Android. 

I understand we already have [Flutter Plugins](https://flutter.io/developing-packages/) that talk to this requirement, however native extensions could possibly enable faster Android trampolining of calls to libraries like SQLite, without having to go via [Android Runtime](https://en.wikipedia.org/wiki/Android_Runtime).

**Comment by zoechi** [comment]
Merging with #7053
