### ISSUE TITLE
Run AOT code on the host runner

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#22250]
Currently, there is no good way to test running AOT code short of compiling it and running it in release mode in a Flutter app.

It would be nice to be able to run AOT code for testing/experiments on the host runner.

/cc @chinmaygarde @cbracken

**Comment by pedromassangocode** [comment]
Is this still an issue today?

**Comment by dnfield** [comment]
The engine now runs AOT and even release tests on the host.
