### ISSUE TITLE
flutter sdk path in Flutter/Android Studio /Windows drive separator (:) are not escaped

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#22255]
Hello, I do not know if it is important but the Windows drive separator are not escaped 
![02_sdk_path](https://user-images.githubusercontent.com/19499129/46005246-1fcde180-c0b5-11e8-9b9e-eaa2d20a7a54.PNG)

**Comment by eseidelGoogle** [comment]
Thank you for filing!

Presumably the file in question is somewehre in here: https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates

Or maybe this is a bug in the IntelliJ plugin itself.  @devoncarew or @pq  would know.

**Comment by benedicte69** [comment]
Thanks, Eric, a little forgetfulness somewhere for sure, intelliJ has been able to do it properly in Android so there is no reason that they should not transfer it correctly into Flutter :)

    Le jeudi 27 septembre 2018 à 17:59:19 UTC+2, Eric Seidel <notifications@github.com> a écrit :  
 
 
Thank you for filing!

Presumably the file in question is somewehre in here: https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates

Or maybe this is a bug in the IntelliJ plugin itself. @devoncarew or @pq would know.

**Comment by devoncarew** [comment]
I _believe_ this file (`local.properties`) is generated the flutter tool, and consumed by the gradle script.

**Comment by Hixie** [comment]
It's not clear why they would need to be escaped?

**Comment by benedicte69** [comment]
maybe they are in the IDE some code such as  C: ? get the file : return null;   and it is more cautious to be explicit about the meaning of :     Le lundi 6 janvier 2020 à 23:11:18 UTC+1, Ian Hickson <notifications@github.com> a écrit :  
 
 
It's not clear why they would need to be escaped?

**Comment by blasten** [comment]
We already escape the path on Windows.
