### ISSUE TITLE
Segmentation fault in flutter build (DUPE #21623) 

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#22259]
Flutter V0.8.2 which is currently Flutter Release Preview 2 still has the problem and the app gives similar output which is dupe of https://github.com/flutter/flutter/issues/21623, Requesting the team to change the release preview 2 to v0.8.7 from 0.8.2

**Comment by zoechi** [comment]
Please check https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

> Every few weeks, we pick the "best" dev build of the previous month or so, and promote it to beta. These builds have been tested with our codelabs.

If the fix for #21623 doesn't cause other issue it will be included in the next beta.
