### ISSUE TITLE
The UI doesn`t refresh  when I tried to call setState ()   in  the  method, and the method return  Widget.

### ISSUE THREAD

**Issue by YijingwanWang** [flutter/flutter#22251]
Because there are more code, I only select part of it to show here.If I write this way  the code work well.

```
/**
   * 复选框
   */
  Widget _getRoundCheckBox() {
    return new GestureDetector(
      onTap: (){
        setState(() {
          _pageVCcheck1=!_pageVCcheck1;
          print('getRoundCheckBox----->>$_pageVCcheck1');
        });
      },
      child: _pageVCcheck1
          ? new Image.asset(
        'res/images/baseline_cb_selected.png',
        width: 30.0,
        fit: BoxFit.fill,
      )
          : new Image.asset(
        'res/images/baseline_cb.png',
        width: 30.0,
        fit: BoxFit.fill,
      ),
    );
  }
  @override
  void initState() {
    super.initState();
      contentWidget = _getRoundCheckBox();
  }
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      //软件盘弹出时刻能会在输入框的下方提示"Flutter bottomover flowed by x pixels"
      //解决办法1，嵌套SingleChildScrollView ；2,设置resizeToAvoidBottomPadding: false,
        resizeToAvoidBottomPadding: false,
        body:
            //contentWidget        
            new GestureDetector(
      onTap: () {
        setState(() {
          _pageVCcheck1 = !_pageVCcheck1;
          print('getRoundCheckBox----->>$_pageVCcheck1');
        });
      },
      child: _pageVCcheck1
          ? new Image.asset(
              'res/images/baseline_cb_selected.png',
              width: 30.0,
              fit: BoxFit.fill,
            )
          : new Image.asset(
              'res/images/baseline_cb.png',
              width: 30.0,
              fit: BoxFit.fill,
            ),
    ),
);
}
```
**But if I write** 
```
@override
  Widget build(BuildContext context) {
    return new Scaffold(
      //软件盘弹出时刻能会在输入框的下方提示"Flutter bottomover flowed by x pixels"
      //解决办法1，嵌套SingleChildScrollView ；2,设置resizeToAvoidBottomPadding: false,
        resizeToAvoidBottomPadding: false,
        body:
            contentWidget,      
);
}
```
the setState() is  running normally,but UI doesn`t refresh .Is it right where I use it? I am new to Flutter.Thanks in advance.

**Comment by zoechi** [comment]
In the 2nd example after "But if I write", what `setState()` are you referring to and what UI change do you expect? 
What difference are you trying to demonstrate with that 2nd example?

Please add the output of `flutter doctor -v`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by YijingwanWang** [comment]
**Sorry, maybe I said it was not detailed enough, and I lacked the necessary information.**

[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.12.6 16G1314, locale zh-Hans-CN)
    • Flutter version 0.6.0 at /Users/wangyijin/Library/FlutterSDK/flutter
    • Framework revision 9299c02cf7 (6 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/wangyijin/Library/Android/sdk
    • Android NDK at /Users/wangyijin/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = /Users/wangyijin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • FRD AL00 • WTKDU16712014907 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**In addition，in the 2nd example I expect the UI to switch properly after clicking on the image as in Example 1.
Currently, instance 1 can be switched normally, but in example 2, although the value of the variable in  `setState()` (`_pageVCcheck1`) changes normally every time, the picture does not switch.**
The only difference between instance 2 and instance 1 is that `contentWidget `  used in instance 2 accepts the value returned by `_getRoundCheckBox()`,and initialize in `initState()`(contentWidget = _getRoundCheckBox() ).Then assigned to "Scaffold->body".And instance 1 is a simple assignment of the specific implementation of `_getRoundCheckBox()` directly to "Scaffold->body"......
Sorry, my statement may not be clear, and the language organization is not enough,too. I hope that you can patiently look at the above code and you should understand.

**Comment by zoechi** [comment]
That's working as intended. 
In the first example is only called once, in the second example the code is executed after each `setState()` because that causes `build()` to be executed again.

**Comment by OmiWakode** [comment]
I had the same issue! Consider using StreamBuilder if nothing works
