### ISSUE TITLE
flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by jaituteja97** [flutter/flutter#22265]
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to C:\Users\JaiTuteja\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by zoechi** [comment]
Can you please provide more information about what steps led to this error?

Please post the content of `C:\Users\JaiTuteja\flutter_01.log;`
and the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
