### ISSUE TITLE
Document that Swift increases app size significantly

### ISSUE THREAD

**Issue by hariprasadiit** [flutter/flutter#22270]
With current beta `0.8.2` and latest `dev`, `flutter build ios --release` produces app which is 5 times the size of the app built with `0.7.2`.

with `0.7.2` the size was around `22mb`
with `0.8.2` the size is around `100mb`

I've tested with basic flutter app by creating new flutter app and building it. Even basic app size is around `61mb`

## Steps to Reproduce
1. Create new flutter app.
2. Run `flutter build ios --release`
3. Check the size of the app

## Images for reference
**`aot` and `app` size**

<img width="629" alt="screen shot 2018-09-25 at 10 08 37 pm" src="https://user-images.githubusercontent.com/1260204/46030076-c5636e00-c112-11e8-9862-32a8bfcd0f90.png">

**contents of the `app`**

<img width="619" alt="screen shot 2018-09-25 at 10 09 53 pm" src="https://user-images.githubusercontent.com/1260204/46030083-c98f8b80-c112-11e8-8dc3-dc60cbd0f88d.png">

## Logs

```
[✓] Flutter (Channel dev, v0.9.2, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.9.2 at /Users/hari/development/flutter
    • Framework revision 85b4670b2a (6 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by hariprasadiit** [comment]
I've tested with `0.7.5` and `0.6.2`. even this version created basic app of size `69mb` which is higher than current beta. I do remember that the older beta was producing app with less size. is this expected? did something changed in the tools which is resulting in huge size of the app?

@zoechi could you please escalate this, as this effects app store downloads. I feel this should be top priority.

**Comment by kf6gpe** [comment]
@goderbauer Any thoughts in how this might be related to your work?

**Comment by goderbauer** [comment]
This doesn't reproduce for me on the latest master (see below). Can you tell me what exactly you measured the size of?

```
~/dev/ $ flutter create size_test
<output omitted>
~/dev $ cd size_test/
~/dev/size_test $ flutter build ios --release
Building com.example.sizeTest for device (ios-release)...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Micharl Goderbauer (KY4Q2ZN4ME)"
Starting Xcode build...                                          
 ├─Building Dart code...                             18.6s
 ├─Generating dSYM file...                            0.8s
 ├─Stripping debug symbols...                         0.0s
 ├─Assembling Flutter resources...                    1.3s
 └─Compiling, linking and signing...                 10.5s
 
Xcode build done.                                           32.8s
Built /Users/goderbauer/dev/size_test/build/ios/iphoneos/Runner.app.
~/dev/size_test $ du -hs /Users/goderbauer/dev/size_test/build/ios/iphoneos/Runner.app
 24M	/Users/goderbauer/dev/size_test/build/ios/iphoneos/Runner.app
```

The produces app has a size of 24 MB, which seems about right.

Note: The size of Runner.app does not tell you anything about the download size your app will have on the store or the size it is going to occupy on user's devices. When downloaded from the store, Apple applies a process called app thinning that removes all artifacts and architectures from the app that are not needed for the target device. The inly way to determine the true app size is to upload the app to app store connect and see what numbers apple reports there.

**Comment by hariprasadiit** [comment]
@goderbauer sorry my bad. The app size is `~27mb` for me with `objc` and `~59mb` with `swift`. In screenshot above, swift libraries contribution was about half of the app size.

Would it be useful for anyone who is new to iOS, if we mention about swift effect on final app size somewhere in the flutter website?

thanks for the help

**Comment by goderbauer** [comment]
Yes, Swift apps are known to be bigger because they currently have to ship their own Swift runtime - this effect is unrelated to Flutter.

I'll turn this bug into a request to update documentation to mention that fact for Flutter as well.

**Comment by hariprasadiit** [comment]
@swingywc if you can switch to `objective-c` you can reduce your app size by almost `50%`. App store also compresses your app before sending it to the target device, also it does app thinning to reduce the bytes downloaded on to the device. The size seems to be normal for `swift` apps. 

  for me, generated IPA file is around `100mb` but the download size from the app store is around `45mb`, this is a fat binary which supports both 32 and 64 bits.  If you can upload different IPAs for different architecture, which is possible, then the download size can further be reduced by about `35%` to `40%`. These numbers are based on my app sizes.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2011](https://github.com/flutter/website/issues/2011) via [**ZenHub**](https://www.zenhub.com/)
