### ISSUE TITLE
Flutter Doctor doesn't recognize Xcode 10.0

### ISSUE THREAD

**Issue by S1ark** [flutter/flutter#22275]
Xcode 10.0 is not recognized by flutter.

## Steps to Reproduce
Trying to install ios-deploy and iOS toolchain using brew commands. I have Xcode 10 installed and its set as default using Xcode-Select cmd. When I run '_flutter doctor_' I  get the below error 

```
Error: Your Xcode (1) is too outdated.
Please update to Xcode 9.0 (or delete it).
Xcode can be updated from
  https://developer.apple.com/download/more/

Error: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

_**Flutter Doctor Output :**_ 
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (1 available)
```

**Comment by zoechi** [comment]
Have you tried
```
brew install --HEAD libimobiledevice
brew install ideviceinstaller
```
`flutter doctor` recognizes Xcode 10 just fine for me with the same Flutter version.

**Comment by javiercbk** [comment]
I'm having the same issue.

```sh
brew install --HEAD libimobiledevice
```

> ==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
> Updating /Users/myuser/Library/Caches/Homebrew/libimobiledevice--git
> ==> Checking out branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> HEAD is now at b34e343 tools: Remove length check on device UDID arguments to support newer devices
> ==> ./autogen.sh
> Last 15 lines from /Users/myuser/Library/Logs/Homebrew/libimobiledevice/01.autogen.sh:
> checking dynamic linker characteristics... darwin18.0.0 dyld
> checking how to hardcode library paths into programs... immediate
> checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for libusbmuxd >= 1.1.0... no
> configure: error: Package requirements (libusbmuxd >= 1.1.0) were not met:
> 
> Requested 'libusbmuxd >= 1.1.0' but version of libusbmuxd is 1.0.10
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables libusbmuxd_CFLAGS
> and libusbmuxd_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> 
> READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by neelu004** [comment]
Hi, I would like to know if I don't have the iOS  iOS toolchain - develop for iOS devices (Xcode 10.2) the it will not upgrade the dependency on Mac as I am adding the shared pref dependency in flutter project but it is showing error on Xcode as '-L/Users/ghanshyam/Development/Android/Workspace/my_app/build/ios/Debug-iphoneos/shared_preferences'
ld: library not found for -lshared_preferences
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
Please suggest some ideas about the same so that I can solve my issue.
Thanks!
