### ISSUE TITLE
OSX - Android sdkmanager tool not found

### ISSUE THREAD

**Issue by mrcartier** [flutter/flutter#22279]
Previously flutter worked without any issues. Just tried flutter create in terminal & it fails; upon running flutter doctor I got an error about not being able to find the sdkmanager. I upgraded flutter from v0.3.5 to v0.9.2 but it still won't find sdkmanager...

    Apples-iMac:~ apple$ flutter doctor -v
    [✓] Flutter (Channel dev, v0.9.2, on Mac OS X 10.13.3 17D47, locale en-US)
    • Flutter version 0.9.2 at /Users/apple/flutter
    • Framework revision 85b4670b2a (6 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

    Android sdkmanager tool not found (/Users/apple/Library/Android/sdk/tools/bin/sdkmanager).
    Try re-installing or updating your Android SDK,
    visit https://flutter.io/setup/#android-setup for detailed instructions.

Can't understand why flutter fails now? Haven't upgraded Android Studio since I got it to work the first time with Flutter; still using Android Studio 3.0.1. When I do upgrade Android Studio I use the zip file rather than download the latest .dmg file. Oddly I can use sdkmanager but in Finder I don't see the tools/bin folder; the closest thing I have is tools/bin64? Android Studio appears to work just fine though? Anyone ever seen this before or something similar?

![screen shot 2018-09-25 at 4 48 40 pm](https://user-images.githubusercontent.com/6580221/46042385-3c810e00-c0e3-11e8-8e72-33767776ce4e.png)

**Comment by zoechi** [comment]
What about "Android SDK tools under the "SDK Tools" tab (from your screenshot)?

**Comment by zoechi** [comment]
Is it possible that you have multiple Android SDK or Android Studio installations?
What does `which sdkmanager` print?

**Comment by mrcartier** [comment]
Thanks for replys @zoechi. I pretty certain I don't have multiple Android Studio/SDK installs; initially installed 2.?.? using .dmg file & have updated using only the zip files. I don't have multiple launchers, I'm familiar with how to do it on Windows but never tried on OSX. Tried to run 'which sdkmanager' under 

    /Users/apple/Library/Android/sdk/tools/ 
    /Users/apple/Library/Android/sdk/

but no luck, the only success I had was with './android' at /Users/apple/Library/Android/sdk/tools/ which opened the sdkmanager which I guess is 25.1.3 by the screenshot...


![screen shot 2018-09-26 at 10 27 29 am](https://user-images.githubusercontent.com/6580221/46086931-389ecb80-c177-11e8-8dbd-a34998682f03.png)

As far as your first reply, Android SDK tools under the SDK Tools tab screenshot is below

![screen shot 2018-09-26 at 9 58 58 am](https://user-images.githubusercontent.com/6580221/46087116-a1864380-c177-11e8-8bbc-d0869fd6f3af.png)

**Comment by zoechi** [comment]
There is no need to run `which sdkmanager` in a specific directory. It should instead find the directory that contains `sdkmanager` for you.

https://stackoverflow.com/questions/19986214/setting-android-home-enviromental-variable-on-mac-os-x should help

**Comment by mrcartier** [comment]
This really has me scratching my head. Followed the link you gave & tried several different solutions but none of them print anything when `which sdkmanager` is called from the terminal...

Attempt 1

![screen shot 2018-09-27 at 12 46 43 pm](https://user-images.githubusercontent.com/6580221/46161564-dd8ed680-c253-11e8-84bc-0dbbe76e1a51.png)

Attempt 2

![screen shot 2018-09-27 at 12 48 30 pm](https://user-images.githubusercontent.com/6580221/46161575-e41d4e00-c253-11e8-8623-94f021211c9d.png)

Attempt 3

![screen shot 2018-09-27 at 12 44 55 pm](https://user-images.githubusercontent.com/6580221/46161583-ea132f00-c253-11e8-872e-7b6c3d505e9e.png)

Attempts 2 & 3 are very similar, but Attempt 1 has 3 Android paths: sdk, tools & platform tools. I've been certain to quit terminal & start a new one each time I changed .bash_profile b/c `'source ~/.bash_profile ` seemed to not update at times & `adb` works from terminal so the paths are fine but `which sdkmanager` still doesn't print anything...

**Comment by zoechi** [comment]
Did you try to install the suggested updates in the "SDK Platforms" and "SDK Tools" tabs?

**Comment by mrcartier** [comment]
Resolved by 'flutter create' under another folder but sdkmanager issue using command line remains. It seems to work OK though using IDE...

**Comment by ShulinZ** [comment]
Install Android SDK Command-line Tools will fix the issue.
<img width="1012" alt="Screen Shot 2020-03-06 at 10 33 10 PM" src="https://user-images.githubusercontent.com/3187091/76135984-7d7c9200-5ffa-11ea-98ff-df20a840c410.png">
