### ISSUE TITLE
Flutter should switch to using SkLiteDL instead of SkPictures on the recording canvas.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#22286]
Flutter is one of the last users of Skia's SkPictures. Guidance from the Skia team is that using [SkLiteDL](https://cs.chromium.org/chromium/src/third_party/skia/src/core/SkLiteDL.h?q=sklitedl&sq=package:chromium&g=0&l=19)s is a more performant alternative. The API appears to be the same and should be a drop-in replacement to the pictures used in the engine.

**Comment by gw280** [comment]
Should we close this?

**Comment by jonahwilliams** [comment]
We now use our own display list format
