### ISSUE TITLE
Animate Background Colors

### ISSUE THREAD

**Issue by nahuelcabrera** [flutter/flutter#22282]
Hi guys, i need a solution to implement color transitions on a background, or animate these when i set new bg colors via setstate.

Thanks !

**Comment by samarthagarwal** [comment]
You can use `Tween<Color>` to animate from one `Color` to another.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
Thanks @samarthagarwal
