### ISSUE TITLE
it broke when I played with colors, for the theme of the app

### ISSUE THREAD

**Issue by legallyfree** [flutter/flutter#22281]
the app broke
when I changed the theme of the app,
I was testing the colors to put the subject
using accentColor, primaryColor,
and suddenly, it broke,
I was following the codeLabs # 2
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2
step 7

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Name App',
      theme: ThemeData(
        primaryColor: Colors.black26,
        accentColor: Colors.red,
      ),
      home: RandomWords(),
    );
  }
}
```
![screenshot_1537911610](https://user-images.githubusercontent.com/34919268/46044882-6c83dd80-c0f2-11e8-852e-a33c03b6d714.png)

**Comment by legallyfree** [comment]
was arranged with this line of code
theme: ThemeData.dark(),
I loved

**Comment by zoechi** [comment]
@legallyfree Does this mean your problem is solved and the issue can be closed
or do you think there still something to do for the Flutter team?

**Comment by legallyfree** [comment]
this is closed

**Comment by starbugs2008** [comment]
I found 
 theme: ThemeData(
        primaryColor: Colors.black,
        accentColor: Colors.red,
      ),
will work. 
both primaryColor and accentColor is Color type, but when assign with Color it will crash and when it assign with MaterialColor, it works.  

Also the crash happened on Title.dart line 24, I debug it in, the call color is not null but when step into Title constructor, the color show is null
