### ISSUE TITLE
Default SliderTheme does not meet Material Spec

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#22289]
The slider track and thumb colors are supposed to be based off of the secondary color but Flutter's implementation bases it off of the primary color.

![image](https://user-images.githubusercontent.com/2225255/46051243-2bd59580-c0ed-11e8-8aff-819707113869.png)

https://github.com/flutter/flutter/blob/f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92/packages/flutter/lib/src/material/theme_data.dart#L208

**Comment by clocksmith** [comment]
The example linked is the styling for a custom app. Primary is the correct default color for the Slider. The theme was updated to use the latest colorScheme in https://github.com/flutter/flutter/pull/31564/files
