### ISSUE TITLE
Make raster cache allocate textures from a texture cache.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#22284]
Instead of allocating a texture eagerly as part of the GPU thread frame workload, textures should be acquired from a texture cache. Textures can be recycled and shared between GrContexts whose underlying OpenGL contexts are in the same sharegroup using the [SkImage::MakeBackendTextureFromSkImage](https://cs.chromium.org/chromium/src/third_party/skia/include/core/SkImage.h?q=SkImage::MakeBa&sq=package:chromium&g=0&l=877) API.

**Comment by pedromassangocode** [comment]
Is this still a valid issue today? I'm not sure where to verify that this was implemented or not.

**Comment by chinmaygarde** [comment]
> Is this still a valid issue today? 

Yes.

> I'm not sure where to verify that this was implemented or not.

We still [create a bespoke surface](https://github.com/flutter/engine/blob/89a46af119a4f9b989a6af98da2b64af810e8cd5/flow/raster_cache.cc#L104) (backed by a texture) for each raster cache entry.

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
