### ISSUE TITLE
TickerMode option to render only end of animation for perfs & battery use.

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#22300]
Currently `TickerMode` will just block animation by rendering only the first value.

I'd like to offer a performance mode that disable the intermediate state of animation
but still send the `AnimationStatus` and last value.

Case is saving battery and perfs on very small devices while still having a functional UI.
Full UI is then available only on devices with good performances.

```dart
TickerMode(
   enabled : true,
   skip : true // Skip the intermediate value of animation
   child : ...
)

**Comment by goderbauer** [comment]
Somewhat related: https://github.com/flutter/flutter/issues/4827
