### ISSUE TITLE
[plugin] firebase_messaging can not receive Push Notification when app is close or killed 

### ISSUE THREAD

**Issue by carlosbdw** [flutter/flutter#22305]
when the app is running or I put it in the "background" by switching to the Android desktop (or to another app) a push notification is received. and I could see the log of 'onMessage' and 'onResume' .

but I can not receive any push notification when app is close or killed  ,so I can not test onLaunch .

Any idea?

**Comment by zoechi** [comment]
Please check https://github.com/flutter/plugins/tree/master/packages/firebase_messaging#receiving-messages

**Comment by carlosbdw** [comment]
include the following intent-filter within the <activity> tag of your android/app/src/main/AndroidManifest.xml:

<intent-filter>
    <action android:name="FLUTTER_NOTIFICATION_CLICK" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>

Done

Make sure to include click_action: FLUTTER_NOTIFICATION_CLICK as a "Custom data" key-value-pair (under "Advanced options") when targeting an Android device. 

Done

and I could receive push notification when app is in background ,and I can click it to the specified page .

now the problem is I can not receive it when app is close or killed

**Comment by zoechi** [comment]
Perhaps you want something like https://github.com/flutter/flutter/issues/22197 where background execution can react to notifications (as the mentioned event).

**Comment by lubritto** [comment]
With the newest dart background service, it's possible to solve this issue ?

**Comment by zoechi** [comment]
Closing as dup of #22072

**Comment by kroikie** [comment]
@carlosbdw

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/645. Any further collaboration will be done there.
