### ISSUE TITLE
Flutter always no device

### ISSUE THREAD

**Issue by Unfreeze-kk** [flutter/flutter#22307]
## Steps to Reproduce

1. start android studio 
2. press run
3. get no connected devices found 
4. execute  flutter doctor 

## Logs

```
[√] Flutter (Channel master, v0.9.4-pre.31, on Microsoft Windows [Version 10.0.17134.285], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Android Studio (version 3.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected devices (1 available)

! Doctor found issues in 1 category.

```

```
```

**Comment by zoechi** [comment]
> flutter run error : can't find /lib/main.dart(It's exist)

does not look related to devices found or not.

Please post the comment you executed to get the error message 
and the exact and full error output the command caused.

**Comment by Unfreeze-kk** [comment]
> > flutter run error : can't find /lib/main.dart(It's exist)
> 
> does not look related to devices found or not.
> 
> Please post the comment you executed to get the error message
> and the exact and full error output the command caused.

I did .

**Comment by zoechi** [comment]
What is the actual error now

>  can't find /lib/main.dart

or

> no connected devices found

**Comment by zoechi** [comment]
Did you try restarting your computer?

**Comment by Unfreeze-kk** [comment]
> What is the actual error now
> 
> > can't find /lib/main.dart
> 
> or
> 
> > no connected devices found

no connect devices found

**Comment by Unfreeze-kk** [comment]
> Did you try restarting your computer?
Now  i execute flutter. I always get this 

>  `Because flutter_tools depends on file 5.0.6 which doesn't match any versions, version solving failed`

**Comment by Unfreeze-kk** [comment]
> What is the actual error now
> 
> > can't find /lib/main.dart
> 
> or
> 
> > no connected devices found
  no connected devices found.I try to use  `flutter run ` then I get this `can't find /lib/main.dart`

**Comment by zoechi** [comment]
Try switching to `beta` or `dev` channel
```
flutter channel beta
flutter doctor
```

**Comment by Unfreeze-kk** [comment]
> Try switching to `beta` or `dev` channel
> 
> ```
> flutter channel beta
> flutter doctor
> ```

get this `Can't load Kernel binary: Invalid kernel binary format version. `

**Comment by wlans** [comment]
If you are trying to execute 'flutter run' make sure you are in your projects folder. Also, Andrioid Studio would only see my LG phone if it was connected in chargeing mode.

**Comment by zoechi** [comment]
Also try `flutter clean`

**Comment by Ronnieb23** [comment]
from what you provided you need to install or finish installing flutter and dart.  https://flutter.io/get-started/editor/

**Comment by Unfreeze-kk** [comment]
I made it work.I reinstalled  flutter.Thanks for you.

**Comment by Krunal79-flutter** [comment]
lutter supports both iOS and Android device/simulators.

In terminal, run the flutter devices command to verify that Flutter recognizes your connected Android device.

Here is a reference document, How you can setup Device/Simulator to run your application.

For, Android (on mac system)
Set up your Android device
To prepare to run and test your Flutter app on an Android device, you’ll need an Android device running Android 4.1 (API level 16) or higher.

Enable Developer options and USB debugging on your device. Detailed instructions are available in the Android documentation.
Using a USB cable, plug your phone into your computer. If prompted on your device, authorize your computer to access your device.
In the terminal, run the flutter devices command to verify that Flutter recognizes your connected Android device.
Start your app by running flutter run.
By default, Flutter uses the version of the Android SDK where your adb tool is based. If you want Flutter to use a different installation of the Android SDK, you must set the ANDROID_HOME environment variable to that installation directory

Find Out At [Here](https://icetutor.com/question/flutter-run-no-connected-devices/)
