### ISSUE TITLE
Provide ability to make origin of active track color in Slider start at arbitrary value

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#22325]
Mulligan has a use case where the start point of the active track color for the Slider is at an arbitrary value. Right now, the effective start point of the slider is at `min`. For this feature request, I'm requesting for a new field named something like `startValue` such that the track is drawn from `startValue` to `value`.

This would look something like this:

![image](https://user-images.githubusercontent.com/2225255/46111115-a01a4280-c19a-11e8-81c7-5e5d29600b29.png)

![image](https://user-images.githubusercontent.com/2225255/46111128-a8727d80-c19a-11e8-927c-03660993706b.png)

To elaborate some more on the use case, the slider is supposed to represent a numeric value where the min value is < 0 and the max value is > 0. We want to assign `startValue` to 0. 

Looking at the code, it looks like this would be a relatively easy change to the framework's implementation of the widget. However, the widget isn't built in such a way that I can compose parts myself. I'd have to fork the entire widget. 

cc @johnfesa

**Comment by johnfesa** [comment]
Also, for the record, it's a design that's internally approved and gone through UX review.

**Comment by Hixie** [comment]
cc @willlarche to update the material design spec (unless it's already updated?) I don't see anything on https://material.io/design/components/sliders.html (the closest is the dual-value sliders, which we don't currently support).

**Comment by Hixie** [comment]
cc @clocksmith any updates perchance?

**Comment by mehmetf** [comment]
@alanrussian Is this a blocker for your releases in Q1?

**Comment by alanrussian** [comment]
I wouldn't describe this as a blocker, but our workaround is not particularly great/stable so it would be nice to get this fixed at some point.

**Comment by clocksmith** [comment]
This should be achievable after https://github.com/flutter/flutter/pull/25008#pullrequestreview-186778334 is merged

**Comment by mehmetf** [comment]
@zoechi Why is this waiting for customer reponse? Alan said it is not a blocker but it is important.
