### ISSUE TITLE
flutter attach command not work

### ISSUE THREAD

**Issue by specneeo** [flutter/flutter#22340]
From [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps), this works well and gradle plugin version is 3.1.4.
`classpath 'com.android.tools.build:gradle:3.1.4'`

But if gradle plugin version is `2.3.3`, 
`classpath 'com.android.tools.build:gradle:2.3.3'`
 `flutter attach` command not work.
I do not konw whether this is root cause?

`flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.7-pre.105, on Mac OS X 10.13.1 17B1003, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
[✓] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
`flutter attach` is rather new as far as I know and your Flutter version is rather outdated.
Can you please try again with a recent Flutter version?

**Comment by specneeo** [comment]
The same version of flutter, when use gradle plugin 3.1.3, flutter attach command works and could hot reload darrt code. But when change  gradle plugin 2.3.3, this command not works, could not hot reload  dart code.

I will upgrade flutter version and replay later

**Comment by specneeo** [comment]
@zanderso  I think this issue may be closed now. It seems does not matter about gradle plugin version, because my colleague could work with gradle plugin 3.1.3。

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by rahuldevanavar91** [comment]
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

```

Yes still  I am facing the issue .
Always it shows
`Waiting for a connection from Flutter on SM N900...
`
