### ISSUE TITLE
How to expand or collapse ExpansionTile programatically

### ISSUE THREAD

**Issue by jagdishjadeja** [flutter/flutter#22351]
How can i collapse/expand ExpansionTile programatically ?
i dont see any way to toggle ExpansionTile in its definition 
can anyone suggest me how can i achieve that ?

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/material/ExpansionTile/initiallyExpanded.html

I assume I mentioned this already somewhere to you.
The problem is not `ExpansionTile` but how you propagate the state.
Try a simpler example without FAB and use a FlatButton or similar that is added to the same widget as the ExpansionTile and when you got that working you can extend to use it with FAB.
Then you might have a simple example and be able to ask more specific question.

Sorry, but we don't have the resources for individual support.
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jagdishjadeja** [comment]
i dont see why you are referring FAB or FlatButton with ExpansionTile
i used that FAB's onPressed event just to toggle that Collapse/Expand ExpansionTile only and not for actual use
but still i dont find it that how to Collapse/Expand ExpansionTile
@zanderso

**Comment by zoechi** [comment]
I just try to guide you with debugging. I don't have a solution ready in my head.
Anyway, it's a support question that should be discussed in other channels.

**Comment by jagdishjadeja** [comment]
I tried gitter but no answer 
i don't know where else to ask

**Comment by zoechi** [comment]
Set up a proper StackOverflow question.

**Comment by zoechi** [comment]
Duplicate of #7024

**Comment by shree-krishna-gapi** [comment]
how can callback to ExpansionTile, if one Expaneded then other will close automatically.

**Comment by jlokesh20** [comment]
any solution to this problem yet ?

**Comment by jdavies** [comment]
I think you'll need to track the expansion state of each expansion tile individually. Something like:
```
Map<String, bool> expansionState = Map();
```
On initialization, you'll need to specify the keys and whether or not you want the associated expansion tile to show as opened or closed. In my code I have a List<String> for the expansion tile names. On page load, I do the following:
```flutter
categoryList.forEach((name) {
              expansionState.putIfAbsent(name, () => true);
            });
```
Then the builder simply refers to the expansionState:
```flutter
Widget _buildCategory(String name, List<OrderItem> children) {
    return ExpansionTile(
      key: PageStorageKey<String>(name),
      initiallyExpanded: expansionState[name], // true,
      title: RichText(
          text: TextSpan(
        text: name,
        style: TextStyle(
            color: Colors.blue[800], fontSize: 16, fontWeight: FontWeight.bold),
        children: <TextSpan>[
          TextSpan(
              text: ' - ' + children.length.toString() + ' items',
              style: TextStyle(
                  color: Colors.grey[800],
                  fontSize: 16,
                  fontWeight: FontWeight.normal)),
        ],
      )),
      onExpansionChanged: ((newState) {
        print(name + ' is now ' + newState.toString());
        expansionState[name] = newState;
      }),
      children: children.map<Widget>(_buildChild).toList(),
    );
  }
```
At this point, you have the ability to add a button whose `onPressed()` method can manipulate the expansionState map any way you want inside of a `setState()` call. You could open them all, close them all, toggle their current states, etc.

**Comment by aydin-faruk** [comment]
> I think you'll need to track the expansion state of each expansion tile individually. Something like:
> 
> ```
> Map<String, bool> expansionState = Map();
> ```
> 
> On initialization, you'll need to specify the keys and whether or not you want the associated expansion tile to show as opened or closed. In my code I have a List for the expansion tile names. On page load, I do the following:
> 
> ```
> categoryList.forEach((name) {
>               expansionState.putIfAbsent(name, () => true);
>             });
> ```
> 
> Then the builder simply refers to the expansionState:
> 
> ```
> Widget _buildCategory(String name, List<OrderItem> children) {
>     return ExpansionTile(
>       key: PageStorageKey<String>(name),
>       initiallyExpanded: expansionState[name], // true,
>       title: RichText(
>           text: TextSpan(
>         text: name,
>         style: TextStyle(
>             color: Colors.blue[800], fontSize: 16, fontWeight: FontWeight.bold),
>         children: <TextSpan>[
>           TextSpan(
>               text: ' - ' + children.length.toString() + ' items',
>               style: TextStyle(
>                   color: Colors.grey[800],
>                   fontSize: 16,
>                   fontWeight: FontWeight.normal)),
>         ],
>       )),
>       onExpansionChanged: ((newState) {
>         print(name + ' is now ' + newState.toString());
>         expansionState[name] = newState;
>       }),
>       children: children.map<Widget>(_buildChild).toList(),
>     );
>   }
> ```
> 
> At this point, you have the ability to add a button whose `onPressed()` method can manipulate the expansionState map any way you want inside of a `setState()` call. You could open them all, close them all, toggle their current states, etc.

What is "categoryList" ??? Where is your categoryList function?

**Comment by aydin-faruk** [comment]
This great solution

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ExpansionTile Collapse',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'ExpansionTile Collapse'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  // selected's value = 0. For default first item is open.
  int selected = 0; //attention

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,title: Text('ExpansionTile Collapse', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
      ),
      body: Container(color: Colors.white,
          child: SingleChildScrollView(
              child : Column( 
                children : [                  
                  ListView.builder(

                      key: Key('builder ${selected.toString()}'), //attention

                      padding: EdgeInsets.only(left: 13.0, right: 13.0, bottom: 25.0),
                      shrinkWrap: true,
                      physics: NeverScrollableScrollPhysics(),
                      itemCount: 5,
                      itemBuilder: (context, index) {                        
                        return Column(
                          children: <Widget>[
                            Divider(
                              height: 17.0,
                              color: Colors.white,
                            ), 
                                  ExpansionTile(  

                                        key: Key(index.toString()), //attention                                                                  
                                        initiallyExpanded : index==selected, //attention

                                        leading: Icon(Icons.person, size: 50.0, color: Colors.black,),
                                        title: Text('Faruk AYDIN ${index}',style: TextStyle(color: Color(0xFF09216B), fontSize: 17.0, fontWeight: FontWeight.bold)), 
                                        subtitle: Text('Software Engineer', style: TextStyle(color: Colors.black, fontSize: 13.0, fontWeight: FontWeight.bold),),
                                        children: <Widget>[                                       
                                          Padding(padding: EdgeInsets.all(25.0), 
                                                      child : Text('DETAİL ${index} \n' + 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using "Content here, content here", making it look like readable English.',)
                                                      ) 
                                        ],
                                        onExpansionChanged: ((newState){
                                            if(newState)
                                                setState(() {
                                                  Duration(seconds:  20000);
                                                  selected = index; 
                                                });
                                                else setState(() {
                                                  selected = -1; 
                                                });        
                                        })
                                      ),
                                 
                              ]
                            );
                      },
                        )
                ]
                    ),
          )           
        )
    );
  }
}

```

**Comment by jdavies** [comment]
Here is my categoryList and expansionState:
```
List<String> categoryList = <String>[]; // List of String keys to the categorizedMap
Map<String, bool> expansionState = <String, bool>{};
```
This allows me to programatically open and close expansion tiles simply by manipulating the `expansionState` inside of a `setState()`

**Comment by zacktagnan** [comment]
@aydin-faruk , good solution!! But it's a pity that animation effect on the expanding/collapsing was lost … Any idea to recover it?

**Comment by hariom007** [comment]
hi ! aydin-faruk.  How to do samething in without listview builder.

**Comment by tokki-stack** [comment]
but there is one more thing on aydin-faruk's comment,
I changed the duration from 20000 into more smaller value, after that it works on my side,
thanks

**Comment by eyponder** [comment]
@aydin-faruk  kod çok güzel sağolasın 👍

**Comment by nurbek-b** [comment]
@aydin-faruk it is a great solution. But I have one bug I trying to solve for two days. After calling function onExpasionChanged, the state is restarting and listview scrolling to top, but not to expansion that I expanded. IS there any solution?

**Comment by Fayiz-A** [comment]
Hey @nurbek-b . I faced the same challenge. I used scroll controller (from listview.builder) and scroll to the one you are expanding. It solved my problem.

https://api.flutter.dev/flutter/widgets/ScrollController-class.html

Please let me know if it helps.

**Comment by nurbek-b** [comment]
I am working on this way for many hours indeed)), but no luck. Can you show me the code you wrote? I'm already desperate.))

**Comment by ilkbahar** [comment]
I have solution for this
First copy the ExpansionTile to another dart file 
then add this class under the ExpansionTile
`class ExpandedTileController extends ChangeNotifier {
  bool isExpanded;
  void expand() {
    isExpanded = true;
    notifyListeners();
  }

  void collapse() {
    isExpanded = false;
    notifyListeners();
  }
}`
when we create the class we have to get it from user
`@required this.controller,
final ExpandedTileController controller;`

After adding, call this class inside of state
`ExpandedTileController controller;`
add below the code in initstate
`controller = widget.controller;
    widget.controller.addListener(() {
        setState(() {
          _isExpanded = controller.isExpanded;
        });
        _handleController();
    });`

handle Controller
`_handleController(){
    if (_isExpanded) {
        _controller.forward();
      } else {
        _controller.reverse().then<void>((void value) {
          if (!mounted) return;
          setState(() {
            // Rebuild without widget.children.
          });
        });
      }
  }`

**Comment by jagdishjadeja** [comment]
For those who are still looking for the answer, I had used `ExpansionPanel()` to expand/collapse tiles programmatically
here's sample code that I used

```dart
class _ToolsPageState extends State<ToolsPage> {
  List<bool> _states = List();
  @override
  void initState() {
    super.initState();
    _states.addAll([false, false, false, false, false]);
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: <Widget>[
        ExpansionPanelList(
          expansionCallback: (int index, bool value) {
            setState(() {
              for (int i = 0; i < _states.length; i++) {
                if (i != index) {
                  _states[i] = false;
                }
              }
              _states[index] = !_states[index];
            });
          },
          children: [
            ExpansionPanel(
              isExpanded: _states[0],
              headerBuilder: (BuildContext context, bool isExpanded) =>
                  ListTile(
                leading: Icon(FontAwesomeIcons.bookmark),
                title: Text("text"),
              ),
              body: ListTile(
                leading: SizedBox(),
                title: Text("text 2"),
              ),
            ),
            ExpansionPanel(
              isExpanded: _states[1],
              headerBuilder: (BuildContext context, bool isExpanded) =>
                  ListTile(
                leading: Icon(FontAwesomeIcons.bookOpen),
                title: Text("text"),
              ),
              body: Column(
                children: <Widget>[
                  ListTile(
                    leading: SizedBox(),
                    title: Text("Text 1"),
                  ),
                  ListTile(
                    leading: SizedBox(),
                    title: Text("text"),
                  ),
                  ListTile(
                    leading: SizedBox(),
                    title: Text("textCode"),
                     ),
                  ListTile(
                    leading: SizedBox(),
                    title: Text("Text"),
                  ),
                ],
              ),
            ),
            ExpansionPanel(
              isExpanded: _states[2],
              headerBuilder: (BuildContext context, bool isExpanded) =>
                  ListTile(
                leading: Icon(FontAwesomeIcons.graduationCap),
                title: Text("Text"),
              ),
              body: Column(
                children: <Widget>[
                  ListTile(
                    leading: SizedBox(),
                    title: Text("Text"),
                  )
                ],
              ),
            ),
            ExpansionPanel(
              isExpanded: _states[3],
              headerBuilder: (BuildContext context, bool isExpanded) =>
                  ListTile(
                leading: Icon(FontAwesomeIcons.child),
                title: Text("Another"),
              ),
              body: Column(
                children: <Widget>[
                  ListTile(
                    leading: SizedBox(),
                    title: Text("Text"),
                  )
                ],
              ),
            ),
            ExpansionPanel(
              isExpanded: _states[4],
              headerBuilder: (BuildContext context, bool isExpanded) =>
                  ListTile(
                leading: Icon(FontAwesomeIcons.bookOpen),
                title: Text("Text"),
              ),
              body: Column(
                children: <Widget>[
                  ListTile(
                    leading: SizedBox(),
                    title: Text("Text"),
                  )
                ],
              ),
            ),
          ],
        ),
      ],
    );
  }
}
```
this is one of my old code if some syntax is updated

**Comment by AmbujaAK** [comment]
i did it by managing state (say: isExpanded ) by provider and changing the state on clicking FAB or any Widget..

now show its childeren widget if expanded else show Container()
