### ISSUE TITLE
Cupertino navigator push don't have a hide bottom tab option.

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#22354]
Cupertino navigation examples show how to navigate in cupertino. but there is no options provide when push to next page and hide bottom tab bar.

These to push method are different:

```
// this one can hide, but not same behaviour with original iOS transition
Navigator.of(context, rootNavigator: true).push(
      new CupertinoPageRoute(
        builder: (c) {
          return new ChatPage(sess: session);
        },
      ),
    );

// this one can not hide, but have same behaviour with original iOS transition
// however how to hide that tab bottom in this transition style?
Navigator.of(context).push(
      new CupertinoPageRoute(
        builder: (c) {
          return new ChatPage(sess: session);
        },
      ),
    );
```

**Comment by xster** [comment]
Can you describe a bit your desired behavior or an example in iOS where you see the desired pattern?

The only scenario I'm aware of in iOS is going to a fullscreen dialog from a page from tabs such as tapping on the 'profile' button in the App Store. A bottom-up transition is triggered in this case. 

The equivalent code would be 

```dart
Navigator.of(context, rootNavigator: true).push(
  new CupertinoPageRoute(
    fullscreenDialog: true
    builder: ...
  ),
);
```

**Comment by jinfagang** [comment]
Thanks for reply. I know what you mean, it's a push up from bottom transition with fullscreen options true. But what I means is, when not provide `rootNavigator` option, the transition in cupertino navigator will have a transition animation with the **page  title** ( I mean the big title in page and become the previous title in next screen).  But if we using rootNavigator as true, then there is not such animation. You will say without animation is also work on transition, yes it is, and works very well. But sometimes we want the vivid title animation between first and detail page (first one I decribe has, but **can not hide bottom bar which is the problem**).

**Comment by xster** [comment]
I'm still not sure what is the desired effect. 

I understood the part that you want to perform the transition at a higher level than the CupertinoTabScaffold. 

Do you want a horizontal transition or a vertical transition? 

I'm also not sure that either transition is present natively on iOS where a page transition above a bottom tab bar either horizontally or vertically AND has the nav bar's subcomponents transition between the outgoing and incoming nav bars. 

Do you have an example of the effect you're looking for in a system iOS app?

**Comment by jinfagang** [comment]
@xster Thanks for your patiance, I made a screen record to show what I mean. https://drive.google.com/open?id=1W61EJZmnMBu5B8aiKagYZU2YL9tCYHR6

As you can see, The first push from father screen to child screen, it has a title animation. But the bottombar can not hide after pushed. The second push has no animation but can hide the bottombar. What I want is, push with animation and same time has the option to hide bottom bar.

**Comment by xster** [comment]
Can you give access to your file? I can't see the video.

**Comment by jinfagang** [comment]
@xster Sorry, can this be seen? https://drive.google.com/file/d/1W61EJZmnMBu5B8aiKagYZU2YL9tCYHR6/view?usp=sharing

**Comment by xster** [comment]
I think I understand what you mean. So a bit like the transition in WeChat where the conversation page does a horizontal transition above the tab bar. 

If it's achievable in iOS, I think it's reasonable to let the Flutter API match. I'll close this bug for now but you can follow the progress on #22084.
