### ISSUE TITLE
Android Native platform configuration 

### ISSUE THREAD

**Issue by morad00** [flutter/flutter#22352]
How can I config my code to run in all native platforms like
arm64-v8a, armeabi-v7a and other architecture

I know it could be configured in (app build.gradle) using split but It always generates a release apk that only run for armeabi-v7a

My reason for this is I want to upload an update for an existing app in google play that has "Native platform = none", So my app must have the same platform dependencies to not lose some users ..

**Comment by morad00** [comment]
Any help here ?

**Comment by jonahwilliams** [comment]
This is all documented https://flutter.dev/docs/deployment/android#building-the-app-for-release
