### ISSUE TITLE
Several black-screen issues happens on Flutter

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#22353]
Till now, we've made two workarounds for skia, which help us overcome black-screen issues in Flutter.
Those two are all located in skia/src/gpu/gl/GrGLInterface.cpp, when the "bool GrGLInterface::validate" fails, the screen is black.

a. Huawei Honor 3C(Model:H30-T00 OS:4.2.2)
![image](https://user-images.githubusercontent.com/817851/46154904-b44c6580-c2a8-11e8-9bcc-ba4fa199a4da.png)
I solve it by a workaround as below:
![image](https://user-images.githubusercontent.com/817851/46155041-042b2c80-c2a9-11e8-8af9-178dfbbee84e.png)

b. Mi Pad2 
![System Info](https://user-images.githubusercontent.com/817851/46005965-034b9c80-c0e9-11e8-8b72-b1c9a9fec1af.png)
I solved it by a workaround as below:
![](https://user-images.githubusercontent.com/817851/46005424-d2b73300-c0e7-11e8-9b42-858563cf8de2.png)

@cbracken 
The repro instructions is quite simple, it will definitely appear if you run a flutter app(like FlutterGallery) in the specific device&os.

**Comment by brianosman** [comment]
As written, these changes can't be upstreamed - those drivers are broken. In this case, they're advertising certain GL extensions, then failing to provide all of the functions required by those extensions. We no longer use the texture buffer functions, so those could be removed, but that's a fairly time-consuming process (involving Chrome, etc.)

A better solution would be to disable extensions that are advertised but not implemented correctly. Some work towards doing that is captured in http://skbug.com/8474, but that's a large scope task that no one's going to work on in the short term.

**Comment by xster** [comment]
@brianosman seems like the upstream issue was fixed. Can we close this issue now?

**Comment by brianosman** [comment]
Hmm. We've made some large changes to the interface assembly code, but I'm not sure it directly solved this problem. I'd want to hear from @kangwang1988. In any case, I think we could now add logic to ignore the broken extension, if necessary.

**Comment by kangwang1988** [comment]
@brianosman 
As we can't use the latest code unless in stable branch, and also I can't confirm if this bug is resolved unless reported from the custom side.
I think we can close this issue now, if I receive this issue from the custom side again later, I will reopen it.

**Comment by darshankawar** [comment]
Closing per [this](https://github.com/flutter/flutter/issues/22353#issuecomment-627666479) comment.
