### ISSUE TITLE
FirebaseAnalytics.setUserId does not accept null user ID

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#22368]
`FirebaseAnalytics().setUserId(null)` to remove User ID.

The official documentation states that "Setting the ID to null removes the user ID" [1]. However, this is not possible with Flutter plugin:

https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/lib/firebase_analytics.dart#L70

```dart
  Future<Null> setUserId(String id) async {
    if (id == null) {
      throw ArgumentError.notNull('id');
    }
```

In addition, FirebaseAnalytics stands out from all other Firebase plugins because its singleton is obtained using a factory constructor rather than `.instance` class method.

[1]: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setUserId(java.lang.String)

**Comment by kroikie** [comment]
@dotdoom

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/643. Any further collaboration will be done there.
