### ISSUE TITLE
Would like embedding-flutter overhead metrics

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#22363]
The specific one I'm being asked for is overhead on startup time.  How much would one expect to add adding a FlutterView to ones home-screen to startup time.

We track startup time of flutter_gallery, but I could imagine us getting this number by tracking startup time of hello_world Android and then hello_world Android + a FlutterView.

FYI @cbracken @gspencergoog @matthew-carroll

**Comment by xster** [comment]
This has been specified in https://flutter.dev/docs/development/add-to-app/performance.
