### ISSUE TITLE
borderRadius should document that manual clipping may be necessary to get rounded corner effect

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#22370]
old title: Container borderRadius not applied when using image inside it
The picture says it all, the image edges are sharp, the bottom edges are rounded.

![screenshot_1538078543](https://user-images.githubusercontent.com/1261332/46171709-2f644a80-c2ae-11e8-8aae-4e22aed3ca70.png)

**Comment by p30arena** [comment]
```
Container(
          decoration: BoxDecoration(
            color: Colors.white,
            boxShadow: <BoxShadow>[
              BoxShadow(
                color: Colors.black38,
                offset: Offset(0.0, 8.0),
                blurRadius: 10.0,
              ),
            ],
            borderRadius: BorderRadius.circular(8.0),
          ),
            child: image
```

**Comment by quetool** [comment]
What about if you use the image as the Container DecorationImage?

**Comment by p30arena** [comment]
@quetool 
Haven't tested it, but the Container is not the only thins I need to place an Image in it,
For e.g. RawMaterialButton behaves the same:

![screenshot_1539436340](https://user-images.githubusercontent.com/1261332/46905909-3c687700-cf07-11e8-92b9-b6d6e2bb4495.png)

**Comment by p30arena** [comment]
> https://docs.flutter.io/flutter/widgets/ClipRRect-class.html might help?

@SteveAlexander Thank you Steve!
So it was an overflow over round corners, and the solution is to clip the edges.

is this bad for performance?

**Comment by p30arena** [comment]
@zoechi I think this is bad for performance:

**RawMaterialButton** with a shape of
`new RoundedRectangleBorder(borderRadius: new BorderRadius.circular(5.0))`
and a child of
```
new ClipRRect(
  borderRadius: const BorderRadius.only(
    topLeft: const Radius.circular(5.0),
    topRight: const Radius.circular(5.0),
  ),
  child: new Image.network("u r l")
```

**Comment by liyuqian** [comment]
Yes, applying a ClipRRect right on top of the image that needs to be clipped seems to be the most performance friendly way to me.

Note that the clip has to be applied somewhere to have a round-cornered image. Applying the clip only to the image and no more widgets else is therefore the least performance cost you need to pay. If the performance is a big concern, you can try override the default `Clip.antiAlias` [clipBehavior](https://docs.flutter.io/flutter/widgets/ClipRRect/clipBehavior.html) to `Clip.hardEdge`.

**Comment by goderbauer** [comment]
@p30arena Does that resolve this issue for you and we can close it?

**Comment by p30arena** [comment]
@goderbauer 
I think the borderRadius of Container should be responsible for rounding the corners,
but here I have to use a ClipRRect then the Container/Widget inside it.

I'm surprised buy the Container's borderRadius behavior.

**Comment by goderbauer** [comment]
We don't do it automatically because clipping is expensive and not always needed (for example, if your rounded corner container only contains text the rounded corner effect is correct without expansive clipping). That's why you have to apply it manually when you need it.

We should document that on the border radius property, though.

**Comment by p30arena** [comment]
@goderbauer documenting seems fair enough.
Thank you.
