### ISSUE TITLE
Apk release build failed with an exception

### ISSUE THREAD

**Issue by pojoba02** [flutter/flutter#22395]
@dnfield, am having another issue with building apk release, but this time coming from fluttertoast,
this is the result..Execution failed for task ':app:lintVitalRelease'.

Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
Could not resolve project :fluttertoast.
Required by:
project :app
> java.lang.NullPointerException (no error message),
most interesting thing is the app does run fully in emulator

**Comment by dnfield** [comment]
Really don't have much to go on based on these logs...

**Comment by pojoba02** [comment]
I created another ticket with much log info..

**Comment by pojoba02** [comment]
Log#22397

**Comment by dnfield** [comment]
Duplicate of #22397
