### ISSUE TITLE
'package:flutter/src/widgets/app.dart': Failed assertion: line 106 pos 15: 'navigatorObservers != null': is not true.

### ISSUE THREAD

**Issue by micck2** [flutter/flutter#22406]
```
I/flutter (31448): When the exception was thrown, this was the stack:
I/flutter (31448): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:106:15)
I/flutter (31448): #3      _MaterialAppState.build (package:flutter/src/material/app.dart:377:14)
I/flutter (31448): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3766:27)
I/flutter (31448): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
I/flutter (31448): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (31448): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (31448): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3805:11)
I/flutter (31448): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (31448): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (31448): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (31448): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
I/flutter (31448): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
I/flutter (31448): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3658:5)
I/flutter (31448): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter (31448): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter (31448): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter (31448): #18     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:901:16)
I/flutter (31448): #19     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:872:5)
I/flutter (31448): #20     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:818:17)
I/flutter (31448): #21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter (31448): #22     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:817:13)
I/flutter (31448): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:709:7)
I/flutter (31448): #24     runApp (package:flutter/src/widgets/binding.dart:748:7)
```

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the problem.
Can you please post the output of `flutter doctor -v` 
and a minimal reproduction?

**Comment by xgz123** [comment]
Get this error when I forgot to use `MaterialApp` on the root.

**Comment by BashardinhoGitHube** [comment]
well, this is my code + the output of flutter doctor:


import 'dart:io';
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:path_provider/path_provider.dart';

void main() async{
  var myData = await readData();
  if (myData!=null){
    print(myData);
  }else{
    print(' Sorry nothing to print');
  }

  runApp(new MaterialApp());
}

TextEditingController myController = new TextEditingController();

class Home extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Home();
  }
}

class _Home extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(
        title: new Text('Store Data'),
      ),
      body: ListView(
        padding: EdgeInsets.only(top: 10.1),
//        margin:EdgeInsets.all(5.1),

        children: <Widget>[
          new TextFormField(
            controller: myController,
            decoration: InputDecoration(
                labelText: 'Write Something',
                icon: new Icon(
                  Icons.storage,
                  color: Colors.deepPurple,
                  size: 22.2,
                )),
          ),
      new Padding(padding: EdgeInsets.only(top: 10.1),),
          new RaisedButton(
            onPressed: () {
              writeData(myController.text);
              print('Done');

            },
            child: new Text(
              'Save',
              style: new TextStyle(fontSize: 22.2, color: Colors.deepOrange),
            ),
            
          ),
          new Padding(padding: EdgeInsets.only(top: 10.1),),
//      new FutureBuilder(builder:(BuildContext context,AsyncSnapshot<String> data){
// )
        ],
      ),
    );
  }
}

Future<String> get localPath async {
  final path = await getApplicationDocumentsDirectory();
  return path.path;
}

Future<File> get localFile async {
  final file = await localPath;
  return new File('$file/data.txt');
}

Future<File> writeData(String value) async {
  final file = await localFile;
  return file.writeAsString('$value');
}

Future<String> readData() async {
  try {
    final file = await localFile;
    String data = await file.readAsString();
    return data;
  } catch (e) {
    return 'error';
  }
}


output of doctor -v:


[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\sdk
    • Java binary at: C:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • Lenovo K53a48 • f973d4d2 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!

and still getting the error !
