### ISSUE TITLE
Please use latest dartdoc when creating API docs for Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2240]
This is a request for our infra.

The latest dartdoc fixes an issue, and will now be able to generate API docs for dart:ui, dart:jni, and dart:* as implemented by Flutter.

To start, please update https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/flutter.py to use dartdoc at least 0.9.1.

See also https://github.com/dart-lang/dartdoc/issues/1106#issuecomment-189516604

**Comment by sethladd** [comment]
cc @eseidelGoogle not sure if there's a better place to file requests for infra?

**Comment by abarth** [comment]
I can do this.

**Comment by sethladd** [comment]
Coolness, thanks!

**Comment by abarth** [comment]
https://codereview.chromium.org/1743323002

**Comment by abarth** [comment]
Done.
