### ISSUE TITLE
F/flutter ( 3850): [FATAL:flutter/runtime/dart_vm.cc(413)] Error while initializing the Dart VM: SSE2 is required.

### ISSUE THREAD

**Issue by ieras** [flutter/flutter#22416]
F/flutter ( 3850): [FATAL:flutter/runtime/dart_vm.cc(413)] Error while initializing the Dart VM: SSE2 is required.
有没有遇到相同问题的朋友啊？
```
flutter doctor -v
[✓] Flutter (Channel dev, v0.9.4, on Mac OS X 10.13.4 17E199, locale zh-Hans-CN)
    • Flutter version 0.9.4 at /Users/mampod/Documents/product/client/flutter
    • Framework revision f37c235c32 (2 days ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/mampod/Documents/product/client/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mampod/Documents/product/client/AndroidSDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (2 available)
    • MuMu     • emulator-5554                        • android-x86 • Android 4.4.4 (API 19)
    • iPhone 8 • EB534312-FC79-44F2-8BAB-E8A3031246A2 • ios         • iOS 11.4 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Why did you create a new issue? 
You already commented on #21988.
Do you think they are not the same? Please point out why.

**Comment by ieras** [comment]
[FATAL:flutter/runtime/dart_vm.cc(411)] Error while initializing the Dart VM: SSE2 is required.
现在错误码变成411了，但是依然不能解决问题

**Comment by zoechi** [comment]
Merging with #21988

**Comment by zhangyanling77** [comment]
$ flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at D:\fluttersdk\flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\wb-zyl537012\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\wb-zyl537012\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • MuMu • 127.0.0.1:7555 • android-x86 • Android 6.0.1 (API 23)

• No issues found!
我也是这个问题，请问有解决了的嘛？

**Comment by jp1017** [comment]
@zhangyanling77 https://github.com/flutter/flutter/issues/21988#issuecomment-536243610
