### ISSUE TITLE
image_picker showing "detected problems with api compatibility"

### ISSUE THREAD

**Issue by Icarus-Xu** [flutter/flutter#22412]
## Steps to Reproduce

* using `image_picker` sample project on android p
* click the floating action button and take a photo
* after get back to the preview page, a dialog pops up saying "detected problems with api compatibility"
* second try is fine, no popups

**first picture after quit -> kill background task -> open will produce the problem, without killing background task it works fine**

## Logs

nothing good to use

## flutter analyze

nothing valuable, bunch of "unused import"s

## flutter doctor -v
```
[✓] Flutter (Channel beta, v0.8.2, on Linux, locale C)
    • Flutter version 0.8.2 at /home/icarus/Documents/flutter
    • Framework revision 5ab9e70727 (3 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /home/icarus/Documents/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /home/icarus/Documents/android-sdk
    • Java binary at: /home/icarus/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/icarus/Documents/android-studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • MIX 2S • 55822fe8 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Icarus-Xu** [comment]
sorry for leaving a plugin-related bug in this repo but I could not report this in plugin repo

**Comment by pengMaster** [comment]
thanks

**Comment by zoechi** [comment]
@Icarus-Xu issues in the plugin repo are disabled because they are maintained here.
So all is fine. Thanks for reporting!

**Comment by Icarus-Xu** [comment]
@zoechi I tested this issue again on an **Android O Emulator** just now, and it works fine. would that be related to api changes in android p?

**Comment by Icarus-Xu** [comment]
or it just does not show in emulators, I don't have a Android O device now so I cannot test this, would you do that for me if you got time?

**Comment by jackz314** [comment]
I think this is probably caused by Google's new restriction on Android private API (reflection methods, for example) usages, refer to this [link](https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces) for more detail. Basically, whenever you use non-SDK Interfaces, that dialog is going to pop up. It's introduced in Android P so that's why the dialog is not shown in Android O devices.

**Comment by Icarus-Xu** [comment]
> I think this is probably caused by Google's new restriction on Android private API (reflection methods, for example) usages, refer to this [link](https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces) for more detail. Basically, whenever you use non-SDK Interfaces, that dialog is going to pop up. It's introduced in Android P so that's why the dialog is not shown in Android O devices.

Yeah I'm just asking what "private API" image_picker used, and according to this restriction you mentioned, the usage shall be replaced/re-implemented

**Comment by cyanglaz** [comment]
@Icarus-Xu I just tried with the image_picker plugin and could not reproduce the issue. Could you confirm whether the issue has been resolved for you as well?
