### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by pengMaster** [flutter/flutter#22415]
Could not resolve all artifacts for configuration ':app:dynamicProfileRuntimeClasspath'.
Could not resolve project :fluttertoast.

**Comment by zoechi** [comment]
Can you please provide more information about how to reproduce?

Is `fluttertoast` from a plugin or is this the name of your project?

Please add the output of `flutter doctor -v`.

**Comment by pengMaster** [comment]
I've solved it, thank you

**Comment by pojoba02** [comment]
@pengMaster had been having the same issue for the past 4 days, tried all kind of troubleshoot but still heading nowhere, please how did you solved it?

**Comment by zhangdaren** [comment]
me too
