### ISSUE TITLE
`flutter run` fails against the iOS simulator

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#22423]
Repro steps in master:

1. `flutter create -t module testmod`
1. `cd testmod`
1. start iOS simulator
1. `flutter run`

=>

```
Launching lib/main.dart on iPhone X in debug mode...
2018-09-28 15:39:09.853 xcodebuild[77449:2458709] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '0x3b' at line 381" UserInfo={NSDebugDescription=Unexpected character '0x3b' at line 381}}
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Project /Users/mit/tmp/testmod/.ios/Runner.xcodeproj cannot be opened because the project file cannot be parsed.

Oops; flutter has exited unexpectedly: "Exit code 74 from: /usr/bin/xcodebuild -list".
```

**Comment by mit-mit** [comment]
cc @matthew-carroll is this expected?

**Comment by matthew-carroll** [comment]
@dnfield would you mind taking a look at this?

One thing I'll mention for sure is that the "module" project should still support host apps.  So if that isn't the case right now for any reason, we need to fix that for sure.

**Comment by dnfield** [comment]
I'm not able to reproduce.  `flutter create -t module testmod` can run on both my Simulator and a real iPhone.

It looks like you're getting a build error.  Could you check in your project somewhere I could look at the pbxproj etc?

**Comment by mit-mit** [comment]
Apologies, I thought I was on an updated master, but I messed up and was running an older build. After upgrading to tip of master, I don't see this issue anymore.
