### ISSUE TITLE
Firebase Phone Auth Proving to be unreliable

### ISSUE THREAD

**Issue by iamjavademon** [flutter/flutter#22425]
So i have been having issues with the phone auth. The code NEVER comes whenever the testers are based in America. Also for iOS the code sending doesnt work the same way all the time, sometimes it asks for captha and sometimes it doesnt. On iOS i have to try for up to 2 days before i receive the code. Phone Auth is the only form of login my app uses so its really a deal breaker. Please help

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by iamjavademon** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (1 available)

**Comment by iamjavademon** [comment]
[✓] Flutter (Channel dev, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-NG)
    • Flutter version 0.9.4 at /Users/olaide.ekeolere/Development/flutter
    • Framework revision f37c235c32 (4 days ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/olaide.ekeolere/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPad Pro (12.9-inch) • 9971E2A2-8983-4C3F-AA5E-9952AE8D2800 • ios • iOS 11.4 (simulator)

**Comment by iamjavademon** [comment]
Hi Gunter,   I have added it almost immediately.
    On Friday, September 28, 2018, 3:46:11 PM GMT+1, Günter Zöchbauer <notifications@github.com> wrote:  
 
 
Please add the output of flutter doctor -v.

**Comment by kroikie** [comment]
@iamjavademon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/642. Any further collaboration will be done there.
