### ISSUE TITLE
Samsung S8 losing touch randomly when scrolling 

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#22424]
I am using the GestureDetector in my app to detect scrolling in order to change some widgets.
I noticed that on the Samsung S8, while scrolling, sometimes it's like the touch is lost, even if my finger is touching the phone. So my finger is still on the screen, but the app behaves like I lifted my finger. This happens randomly. This only happens to me on the Samsung S8. I also tried on Lenovo P2 and iPhone 5S and I had no issue there.
I managed to reproduce the exact same issue in the Flutter Gallery app from the Play Store, in the screen where there is a list with a refresh indicator. I tried doing in other apps like Gmail and I didn't have the same issue there, so only in Flutter apps it happens.
You can see in the video that even if I keep dragging my finger down, sometimes the refresh indicator goes up again, as if I lifted my finger from the screen, but I didn't. 
Please check this video: https://drive.google.com/open?id=1Q-HZ5cLiAFtBj_5M37ldCExLplBm5eZH

```
[✓] Flutter (Channel master, v0.9.5-pre.12, on Mac OS X 10.14 18A391, locale en-RO)
    • Flutter version 0.9.5-pre.12 at /Users/tudor/dev/flutter
    • Framework revision 020fd590b0 (2 days ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (3 available)
    • Lenovo P2a42  • ZY223X3XB2                           • android-arm64 • Android 7.0 (API 24)
    • SM G950F      • 988a1644544d44384c                   • android-arm64 • Android 8.0.0 (API 26)
    • iPhone 7 Plus • B9DE9C96-08CB-4225-8008-89BDB54DFE6E • ios           • iOS 12.0 (simulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @tudor07 do you have possibility to check is it still an issue?

**Comment by tudor07** [comment]
@VladyslavBondarenko Still happening with the latest Flutter Gallery app from Play Store.

**Comment by TahaTesser** [comment]
Hi @tudor07 
Please try again on latest stable, 
 if problem still exist can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
