### ISSUE TITLE
Scrolling Menus

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2243]
If a menu's items will not fit (vertically) within the padded screen bounds, the menu should become scrollable.

**Comment by Hixie** [comment]
The scrolling is there. Is the size wrong?

**Comment by HansMuller** [comment]
A simple menu is supposed to behave like a dropdown if an initialValue (an initially selected item) is specified, i.e. the item needs to be visible and aligned with menu's parent widget. 

This currently works for non-scrollable menus. Not yet for scrollable ones. A scrollable menu needs to ensure that the selected item is visible and then take the scroll offset into account when aligning itself.

Also: scrollable menus should display a scrollbar (as in the scrollbar.dart example)

**Comment by eseidelGoogle** [comment]
@HansMuller says we definitely need this feature, but it doesn't come up in the current gallery demos.
