### ISSUE TITLE
Flutter Driver

### ISSUE THREAD

**Issue by antoninobajeli** [flutter/flutter#22431]
I'm writing and integration test for my App using Flutter Driver.
Is it possible to let the App aware of the fact that it is drived by FlutterDriver?

Thanks, Tony

**Comment by zoechi** [comment]
You can register a handler in the entry-point file of the app.
https://docs.flutter.io/flutter/flutter_driver_extension/enableFlutterDriverExtension.html
and pass text messages to it from the driving file.

**Comment by antoninobajeli** [comment]
That sounds good!! 
Thank you very much :)
