### ISSUE TITLE
Add function to share content on Android and IOS

### ISSUE THREAD

**Issue by jorgevvr** [flutter/flutter#22437]
Why havent a function to share content as files, images, text etc? i searched over the docs and web and no function and no plugins with this function. I think is a basic function cause we want to share things on almost every app.

I found this plugin  https://pub.dartlang.org/packages/share, but it only shares text that's not enough for the most of apps. 

Is hard to people that have experience with only one platform to do specific platform calls with channels.

I'm sorry if i am wrong.

**Comment by zoechi** [comment]
Merging with #19607
