### ISSUE TITLE
cloud_firestore README is outdated

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#22436]
https://github.com/flutter/plugins/tree/master/packages/cloud_firestore
and therefore also https://pub.dartlang.org/packages/cloud_firestore says:

> Recent versions (0.3.x and 0.4.x) of this plugin require extensible codec functionality that is not yet released to the beta channel of Flutter. If you're encountering issues using those versions, consider switching to the dev channel.

cc @kroikie @bparrishMines

**Comment by ened** [comment]
@filiph seems like resolved already?

**Comment by filiph** [comment]
Yes, thanks!

**Comment by kroikie** [comment]
@filiph

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/641. Any further collaboration will be done there.
