### ISSUE TITLE
cloud_firestore should throw own exceptions

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#22440]
As of `cloud_firestore` v0.8.0, all exceptions coming from the plugin are `PlatformException`. This makes it hard to catch specific problems.

For example, this is what I get from a regular transaction timeout exception:

```
PlatformException(9, Transaction failed all retries., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      Firestore.runTransaction (file:///Users/filiph/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.0/lib/src/firestore.dart:115:10)
```

In this particular example, I would love to have a `TimeoutException` instead, and catch only that.

cc @kroikie @bparrishMines

**Comment by zoechi** [comment]
Similar to #17024

**Comment by kroikie** [comment]
@filiph

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/638. Any further collaboration will be done there.
