### ISSUE TITLE
Gallery App has a text editing menu demo

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2244]
https://www.google.com/design/spec/components/menus.html#menus-behavior

Enable the user to apply cut/copy/paste to the selected text.

**Comment by mpcomplete** [comment]
Is this about selecting non-editable text? e.g. https://github.com/flutter/flutter/issues/5422

**Comment by HansMuller** [comment]
The original issue was about supporting editable text. I think we can close it.
