### ISSUE TITLE
cloud_firestore IllegalStateException: Task is already complete

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#22442]
## Steps to Reproduce

1. Create or open a new Flutter app
2. Add the current version of `cloud_firestore` (`0.8.0`) to dependencies.
2. Add a transaction call to the app (for example, the one specified in the official [Cloud Firestore + Flutter codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#9))
3. `flutter run` this in Android emulator or device
4. Initiate the transaction many times in quick succession (in the codelab example, tap on a name many times in a row)

This should fail with a `PlatformException` (or better, a TimeoutException, see https://github.com/flutter/flutter/issues/22440). Instead, it fails with `java.lang.IllegalStateException: Task is already complete`.

This bug doesn't manifest on iOS, as far as I can tell.

## Logs

```
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): Failed to handle method call result
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): java.lang.IllegalStateException: Task is already complete
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source:8)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at com.google.android.gms.tasks.zzu.zzdr(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at com.google.android.gms.tasks.zzu.setResult(Unknown Source:3)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3$1.success(CloudFirestorePlugin.java:287)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:169)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at io.flutter.view.FlutterNativeView.handlePlatformMessageResponse(FlutterNativeView.java:199)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/cloud_firestore( 9569): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

cc @kroikie @bparrishMines

**Comment by 1and1get2** [comment]
had the exact same issue, not use traction to bypass it for now

**Comment by lohanidamodar** [comment]
I am having the same issue, has anyone got the solution yet?

**Comment by itsurmvk** [comment]
I am facing the same issue . It is happening when i tap my widget which calls below method. It is observed that the print statement within runTransaction are printed twice in console.

`updateLikes(String docId, bool liked) {
  final DocumentReference postRef = collectionEvents.document(docId);
  Firestore.instance.runTransaction((Transaction tx) async {
    print("In Transaction");
    DocumentSnapshot eventDoc = await tx.get(postRef); //await tx.get(postRef);
    List<dynamic> likes =
        new List<String>.from(eventDoc.data['likesArray'] ?? []);
    liked ? likes.add(firebaseUser.uid) : likes.remove(firebaseUser.uid);
    var saveData = {'likesArray': likes, 'likeCount': likes.length};
    await tx.update(eventDoc.reference, saveData);

    print("updateLikes Success $docId: $liked");
  });
}`

**Comment by itsurmvk** [comment]
I am facing the 'task is already complete issue' in my app. onTap of my widget it calls below method.
On debug it is observed that print statements in runTransaction are printed twice, which implies the callback is called twice. Please fix this issue.


```dart
updateLikes(String docId, bool liked) {
 
   final DocumentReference postRef = collectionEvents.document(docId);
   Firestore.instance.runTransaction((Transaction tx) async {

    print("In Transaction");
    DocumentSnapshot eventDoc = await tx.get(postRef); //await tx.get(postRef);
    List<dynamic> likes =
        new List<String>.from(eventDoc.data['likesArray'] ?? []);
    liked ? likes.add(firebaseUser.uid) : likes.remove(firebaseUser.uid);
    var saveData = {'likesArray': likes, 'likeCount': likes.length};
    await tx.update(eventDoc.reference, saveData);

    print("updateLikes Success $docId: $liked");
  });
}
```

**Comment by nemoryoliver** [comment]
I am also getting this issue right now... Hoping for the fix...

```
E/MethodChannel#plugins.flutter.io/cloud_firestore(22983): Failed to handle method call result
E/MethodChannel#plugins.flutter.io/cloud_firestore(22983): java.lang.IllegalStateException: Task is already complete
```

**Comment by nemoryoliver** [comment]
I have made a temporary fix.. Open the cloud_firestore package manually and go to CloudFirestorePlugin.java 

Replace this code

`result.success(transactionResult);`

With

```
if (!transactionTCSTask.isComplete()) { // fix for error (java.lang.IllegalStateException: Task is already complete)
  result.success(transactionResult);
}
```

I hope this helps.

**Comment by rostopira** [comment]
I were experiencing the same issue, but it's actually misleading error message
I had following code
```dart
dbRef.runTransaction((trans) async {
      final or = await trans.get(selfRef);
      final Map<String, dynamic> aa = or.data['aa'] ?? {};
      aa[id] = 1;
      await trans.update(selfRef, {'aa': aa});
});
```
It's not obvious, but `or.data['aa']` is subtype of `Map<dynamic,dynamic>` so code inside failed
After I fixed that, following code worked without issue
```dart
dbRef.runTransaction((trans) async {
      final or = await trans.get(selfRef);
      final Map aa = or.data['aa'] ?? {};
      aa[id] = 1;
      await trans.update(selfRef, {'aa': aa});
});
```

**Comment by kroikie** [comment]
@filiph

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/637. Any further collaboration will be done there.
