### ISSUE TITLE
Error: The method 'pushOffset' isn't defined for the class 'dart.ui::SceneBuilder'.

### ISSUE THREAD

**Issue by ifanfaizal** [flutter/flutter#22457]
After upgrading flutter to v0.9.6-pre.35 via command "flutter upgrade" (I'm using master channel btw), I got an error from layer.dart which is part of Flutter package. This error made my app only show the blank white screen as soon as I hit the run "debug". You can see the error on this screenshot,

![screen shot 2018-09-29 at 10 00 11](https://user-images.githubusercontent.com/13832383/46240497-be6a8300-c3d2-11e8-97cf-b689e8ee4a51.png)

Thanks for any helps! :)

**Comment by zoechi** [comment]
`master` channel can be broken occasionally. 
I'd suggest using `dev` channel until this is fixed.

**Comment by ErasoftTeknologi** [comment]
> `master` channel can be broken occasionally.
> I'd suggest using `dev` channel until this is fixed.

Thanks for your suggestion, but I've managed this error by execute "flutter clean" command and than rebuild my project.. Now, my app can run normally again :smiley:

**Comment by ifanfaizal** [comment]
> `master` channel can be broken occasionally.
> I'd suggest using `dev` channel until this is fixed.

Thanks for your suggestion, but I've managed this error by execute "flutter clean" command and than rebuild my project.. Now, my app can run normally again :smiley:

**Comment by sasukeamjed** [comment]
> > `master` channel can be broken occasionally.
> > I'd suggest using `dev` channel until this is fixed.
> 
> Thanks for your suggestion, but I've managed this error by execute "flutter clean" command and than rebuild my project.. Now, my app can run normally again 😃

thank god i had the same issue and this worked fine, thank you

**Comment by kf6gpe** [comment]
Sounds like based on the feedback from @ifanfaizal and @sasukeamjed we can close this issue at this point?

**Comment by ifanfaizal** [comment]
> Sounds like based on the feedback from @ifanfaizal and @sasukeamjed we can close this issue at this point?

yup, thanks
