### ISSUE TITLE
Issue from website page JSON和序列化

### ISSUE THREAD

**Issue by Dragon-Boat** [flutter/flutter#22456]
From URL: https://www.flutterchina.club/json.md

json object in json.dart have been changed to "const JsonCodec json = const JsonCodec();"
so maybe json.md should be adjusted from "JOSN.parse" to "json.parse", just the same as "json.md" in flutter.io.

**Comment by zoechi** [comment]
This site is not maintained by the Flutter team.
Please check about how to contact the maintainers or check the www.flutterchinal.club site.
