### ISSUE TITLE
flutter always uses buildType 'release' even when i am building/running debug app

### ISSUE THREAD

**Issue by apgapg** [flutter/flutter#22466]
## Steps to Reproduce

I tried to customize the output apk file name by adding a property 'archivesBaseName' in my app build.gradle file. I noticed that if i run 'flutter clean' and then try to build app as debug from terminal, or simply run the flutter application from android studio.   
The gradle fails saying:

    Gradle build failed to produce an Android package.   

When i check the build folder I found apk is already generated `CustomApp-debug.apk`. I already know custom naming of output apk fails as per #11095 but i am not able to understand why in debug mode it is using `release` buildType parameters.
Note: if I comment the `archivesBaseName` line everything works fine then.

![screenshot from 2018-09-29 15-11-34](https://user-images.githubusercontent.com/13887407/46244376-d73b5e80-c3fb-11e8-90b0-d531035d275a.png)

## Logs

Output of flutter doctor:
```
[✓] Flutter (Channel dev, v0.9.5, on Linux, locale en_IN)
    • Flutter version 0.9.5 at /home/master/flutter
    • Framework revision 020fd590b0 (3 days ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/master/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/master/android-studio-ide-182.4968538-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.3)
    • Android Studio at /home/master/android-studio-ide-182.4968538-linux/android-studio
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Do you see the same behavior when your create a new project with `flutter create foo`?
You might need to update files in the `android/` directory that are now generated differently then when your project was initially created.

**Comment by apgapg** [comment]
I have used a new project only while opening this issue. This project is
all new except the gradle file change as above in screenshot

**Comment by danwulff** [comment]
Having the same issue with a 1.0 project. There is no foreseeable way to run different grade buildTypes from the Flutter CLI (that I'm aware of).

**Comment by Michael77** [comment]
Having the same problem. Need different buildTypes to use different signingConfig for dev and prod builds.

**Comment by zoechi** [comment]
I was able to make it work in my last project like
```gradle

    signingConfigs {

        debug {
            keyAlias "androiddebugkey"

            storeFile rootProject.file("app/external/debug.keystore")
        }
        releaseFlav1 {
            keyAlias "flav1key"

            storeFile rootProject.file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyPassword keystoreProperties['keyPassword']
        }
        releaseFlav2 {
            keyAlias "flav2key"

            storeFile rootProject.file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyPassword keystoreProperties['keyPassword']
        }
    }
    productFlavors {
        flav1 {
            applicationId "com.mydomain.flav1"
            manifestPlaceholders = [
                appIcon: "@mipmap/ic_launcher_flav1",
                appTitle: "Flav1"
            ]

            dimension "tenant"
        }
        doh {
            applicationId "com.mydomain.flav2"
            manifestPlaceholders = [
                appIcon: "@mipmap/ic_launcher_flav2",
                appTitle: "Flav2"
            ]

            dimension "tenant"
        }
    }

    buildTypes {
        release {
            productFlavors.flav1.signingConfig signingConfigs.releaseFlav1
            productFlavors.flav2.signingConfig signingConfigs.releaseFlav2
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
```

This was quite cumbersome but I got the impression this is more a Gradle issue than a Flutter issue.
I don't have Gradle or Android native experience but when I investigated I couldn't find better solutions for Android native.

**Comment by gppam** [comment]
@zoechi May I ask what's the change here? I mean, were you able to run a 'debug' build type from flutter?

**Comment by PandaGeek1024** [comment]
@zeochi, same question here. how does the flutter knows which build type to pick in your example? thanks

**Comment by jonahwilliams** [comment]
This issue is likely stale, as the implementations of the gradle plugin have changed dramatically since this was filled.

**Comment by jonherbla** [comment]
I had the same problem, flutter always used buildType release. To solve this I put a buildtype debug in the `flutter.gradle` file, this file is located in `flutter/packages/flutter_tools/gradle/`:
`project.android.buildTypes {
           ...
            if (shouldShrinkResources(project)) {
              //Add this buildtype
                debug {
                    
                }
              ...
            }
        }`
