### ISSUE TITLE
Unable to connect to firebase

### ISSUE THREAD

**Issue by ArunSharma009** [flutter/flutter#22483]
![screen shot 2018-09-30 at 12 21 24 pm](https://user-images.githubusercontent.com/18621379/46254357-aca8de80-c4ab-11e8-8d5f-1db5f4430e30.png)

**Comment by zoechi** [comment]
Please add the code to reproduce and the error output as text. Screenshots are not searchable.

Please also add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
