### ISSUE TITLE
[firebase_admob plugin] _interstitialAd?.dispose() throws PlatformException every time

### ISSUE THREAD

**Issue by noma15** [flutter/flutter#22488]
I am using `firebase_admob` plugin(0.6.1) to display banner and interstitial ads.

When `_interstitialAd?.dispose()` is call, PlatformException occurs every time.

My code is the same as the example of firebase_admob plugin.
```
  @override
  void dispose() {

    _interstitialAd?.dispose();  --> exception occurs every time

    super.dispose();
  }
```

Flutter : 0.8.2
Dart : 2.1.0-dev.3.1.flutter-760a9690c2
firebase_admob plugin : 0.6.1
```
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
PlatformException(no_ad_for_id, dispose failed, no ad exists for id=861467796, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:509:61)
<asynchronous suspension>
#3      MobileAd.dispose (package:firebase_admob/firebase_admob.dart:229:12)
#4      _ExerciseWidgetState.dispose (file:///Users/upinel9/work/bitbucket/upinel9_treasure_house/dart/flutter/kest/lib/exercise_widget.dart:60:22)
#5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3833:12)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
#7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
#8      SingleChildRenderObjectElement<…>
```

**Comment by wiserbird** [comment]
Hello, let me explain about this problem.

In my app, a banner ads is created in main page.
And a banner and a interstitial ads are created in a new page.
When a new page is popped, this problem happens.

I recently found that a banner ads is displayed every page after it is created.
I thought that I don't need to create a banner ads in a new page.
So I removed it in a new page and this problem doesn't happen any more.

Let me ask some more questions.
1. A banner ads is displayed every page after it is created. What's the reason?
2. How can I hide a banner ads in some specific pages. Is it possible?

# main page
class _MyTabbedPageState extends State<MyTabbedPage> with SingleTickerProviderStateMixin {

  BannerAd _bannerAd;

  @override
  void initState() {
    super.initState();

    FirebaseAdMob.instance.initialize(appId: Constants.admobAppId);
    _bannerAd = createBannerAd()..load()..show();
  }
}

# new page
class _ExerciseWidgetState extends State<ExerciseWidget> {

  InterstitialAd _interstitialAd;
  BannerAd _bannerAd;             // I removed this banner recently and this problem doesn't happen any more.

  @override
  void initState() {
    super.initState();

    FirebaseAdMob.instance.initialize(appId: Constants.admobAppId);
    _interstitialAd = createInterstitialAd()..load();
    _bannerAd = createBannerAd()..load()..show();  // I removed this banner recently and this problem doesn't happen any more.
  }
}

**Comment by kroikie** [comment]
@noma15

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/635. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by ericel** [comment]
Any solution on this yet?

**Comment by lhdio** [comment]
it is worked 100% 

```
@override
  void dispose() {
    _interstitialAd = createInterstitialAd()..load();
    _interstitialAd?.dispose();
    super.dispose();
 }
```

**Comment by drexel-ue** [comment]
is anyone noticing this error is happening at the same time, as well?

```
flutter: Error caught by Crashlytics plugin <recordError>:
flutter: 'package:firebase_admob/firebase_admob.dart': Failed assertion: line 241 pos 12: '_allAds[id] != null': is not true.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      MobileAd.dispose (package:firebase_admob/firebase_admob.dart:241:12)
#3      AdBloc._disposeAds (package:trivia_black/blocs/ad_bloc.dart:114:39)
#4      AdBloc._init.<anonymous closure> (package:trivia_black/blocs/ad_bloc.dart:52:32)
#5      _rootRunUnary (dart:async/zone.dart:1155:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#12     _rootRun (dart:async/zone.dart:1143:38)

#13     _CustomZone.run (dart:async/zone.dart:1040:19)

**Comment by willmeet** [comment]
[That issue is clearly shown here how to solve admob failed to load ads](http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html)

**Comment by FonzTech** [comment]
@drexel-ue I fixed this error by adding a line like this in the listener function for my BannerAd:
print("FixForHashcode " + DateTime.now().millisecondsSinceEpoch.toString());
so the id variable will change "forcefully".
Let us know.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
