### ISSUE TITLE
Run flutter on ARMv6

### ISSUE THREAD

**Issue by galvesribeiro** [flutter/flutter#22492]
Hello folks!

I have an ARMv6l hardware that has no FPU nor GPU and 64mb RAM. Is there a way to build flutter to use software rendering (i.e. directly draw to linux framebuffer at /dev/fb without window manager) rather relying on Vulkan/GL?

I was able back in the day to build Skia so it doesn't depends on GL and made it work properly on linux framebuffer but I wonder if flutter have any extra dependencies on it.

Would love to use Flutter on our ARM devices and appreciate any guidance.

Best regards!

**Comment by zoechi** [comment]
See the initial comment in https://github.com/flutter/flutter/issues/18208#issue-329550925

**Comment by galvesribeiro** [comment]
Thanks @zoechi 

That issue is related to Metal on iOS... Do you mean that by implementing that issue you are opening new backends for Flutter to be possible?

My big problem is that I have several embedded ARMv6l devices that needs a _modern_ UI framework and looks like flutter would be THE thing we are looking for except that it today depends on GL. So if it can be used with any Skia backend, without a GPU, awesome! :)

**Comment by zoechi** [comment]
@cbracken ?

**Comment by cbracken** [comment]
We definitely support running with Skia's software backend, and the VM can be built for armv6 with soft floating point support. We don't currently produce such a build, but it should be possible to build the engine from source with some tweaking. In terms of running on Linux, some of the example code in the [flutter-desktop-embedding](https://github.com/google/flutter-desktop-embedding) repo might be relevant.

I think the deal-breaker in this case is the small amount of RAM you have available; 64MB is definitely far less than any device we've ever tested with.

Does that answer your questions?

**Comment by galvesribeiro** [comment]
@cbracken thanks for the reply!

I wonder if you could provide us some places where those tweeks are required in order to build it. The 64mb is the worse case scenario. We have more powered devices. Even those worse devices actually have 64mb physical memory + 128mb of paging so, it will probably work. The apps that run there are simple payment apps so we should hit any big issue.

We have mono + Skia running on it in the current apps based on .Net and C# already so, yeah, even with those low resources we are able to do something.

I would appreciate if we have some light on where we should _adapt_ in order to get it building. Build skia last time we did required a lot of gn file changes as it wasn't flexible and as we are not very familiar with GN tooling, it would be a pain for us.

Thanks! Really appreciate the help.

**Comment by cbracken** [comment]
Merging with #22380.
