### ISSUE TITLE
Firebase Auth Convert anonymous acccount to Phone Number Account

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#22491]
I saw that Flutter's implementation of Firebase Auth only provides the following linking methods: **`linkWithEmailAndPassword`**, **`linkWithGoogleCredential`** and **`linkWithFacebookCredential`**.  
After that I looked at the Firebase documentations for Android, Web and iOS and recognized a pattern, where they only showed how to accomplish these three links as well, **but** after [asking about this on StackOverflow](https://stackoverflow.com/q/52578119/6509751), I was now told that it should be possible.  

Since all the Flutter Firebase Auth methods are working with PlatformChannel methods I do not see a way to do this in Flutter and would thus greatly appreciate if this was a possibility (if someone does know a way to do it and I just cannot see it, I prefer that).

**Comment by creativecreatorormaybenot** [comment]
https://github.com/flutter/plugins/pull/809

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/634. Any further collaboration will be done there.
