### ISSUE TITLE
New iPhone not listed correctly in Device menu

### ISSUE THREAD

**Issue by mortenboye** [flutter/flutter#22509]
when plugging in an iPhone XS, the device menu in Android Studio fails to display the correct name for the device and instead show an error message from libidevice.

<img width="1675" alt="screenshot 2018-10-01 at 12 36 50" src="https://user-images.githubusercontent.com/604314/46284054-b6e3df00-c576-11e8-9223-75f594be74b8.png">

Libidevice have recently been updated to work with new iPhones (UDIDs): [https://github.com/libimobiledevice/libimobiledevice/pull/705/commits](https://github.com/libimobiledevice/libimobiledevice/pull/705/commits)

**Comment by zoechi** [comment]
Merging with #22147
