### ISSUE TITLE
flutter doctor error Could not authenticate download server. You may be experiencing a man-in-the-middle attack.

### ISSUE THREAD

**Issue by jitenders859** [flutter/flutter#22502]
$ flutter doctor
Downloading android-arm tools...
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.googleapis.com/flutter_infra/flutter/0c2b6dc6e3395b41ea284c505067455a4081949e/android-arm/artifacts.zip

**Comment by zoechi** [comment]
What is `artifacts.zip`? 
How did you install Flutter?
Did Flutter (`flutter doctor`) work before already?

**Comment by jitenders859** [comment]
flutter doctor works now
first i deleted flutter folder and unzip the below download link to C:/Dev/flutter
https://storage.googleapis.com/flutter_infra/releases/beta/windows/flutter_windows_v0.8.2-beta.zip
and in environment variables in path i Added new path C:/Dev/flutter/bin
and run flutter doctor in git command so it's working now

**Comment by zoechi** [comment]
@jitenders859 thanks for the update!
I assume it's ok to close then.

**Comment by phanirithvij** [comment]
I have the same issue. When I do `flutter upgrade`
```shell
Upgrading engine...
Downloading Android Maven dependencies...                           3.7s
Downloading android-x86 tools...                                   29.2s
Downloading android-x64 tools...
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.googleapis.com/flutter_infra/flutter/9726b4cb99d31f213ac4baf141dec902049f73fd/android-x64/artifacts.zip
```
I'm behind a proxy.
