### ISSUE TITLE
Problem on starting my app on iOS

### ISSUE THREAD

**Issue by firelight22** [flutter/flutter#22506]
## Steps to Reproduce

1. ```flutter run --debug``` with the iOS simulator

## Logs

```
*** First throw call stack:
(
        0   CoreFoundation                      0x000000010cfc329b __exceptionPreprocess + 331
        1   libobjc.A.dylib                     0x000000010c567735 objc_exception_throw + 48
        2   CoreFoundation                      0x000000010cfe1fa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
        3   CoreFoundation                      0x000000010cfc7fb6 ___forwarding___ + 1446
        4   CoreFoundation                      0x000000010cfc9e88 _CF_forwarding_prep_0 + 120
        5   UIKitCore                           0x000000011517dcbe -[UIApplication _checkBackgroundRefreshAPIAdoption] + 174
        6   UIKitCore                           0x000000011515a44a -[UIApplication _runWithMainScene:transitionContext:completion:] + 1402
        7   UIKitCore                           0x00000001159fce3e __111-[__UICanvasLifecycleMon<…>
```

flutter analyze:

```
Analyzing my_app...                                       
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel dev, v0.9.5, on Mac OS X 10.14 18A391, locale en-FR)
    • Flutter version 0.9.5 at /Users/quentin/Documents/Flutter/flutter
    • Framework revision 020fd590b0 (5 days ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/quentin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • IPHONEX11.4 • A3EB6541-FE31-4754-B35D-31D195A05F05 • ios • iOS 12.0 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by firelight22** [comment]
Hi @mklim. Sadly the code doesn't start at all. I've got a white screen for like one second and the app crashes. I can give you the dependencies to help you if you want.

**Comment by mklim** [comment]
Thanks for the offer. I'm not seeing enough information in just the stack trace to understand the problem, so I'm going to need some kind of case where I can trigger this crash myself to debug it and get a fix in. The dependencies from your app wouldn't be enough unfortunately. Could you get this crash happening in a small test case? For example by altering the hello world app produced by `flutter create`, just enough to replicate the problem.

**Comment by crashless** [comment]
I just ran into this my first time going over to iOS from a project I had made on my Windows system. The issue turned out to be that while I had configured the app with Firebase on the Android side, I hadn't done the same on the iOS side.

Try the iOS stuff here: https://firebase.google.com/docs/flutter/setup

**Comment by kostyaVyrodov** [comment]
Same thing for me when I run ```flutter run```
```
Launching lib/main.dart on iPhone 8 in debug mode...
Starting Xcode build...
 ├─Assembling Flutter resources...                    2.2s

 └─Compiling, linking and signing...                  6.4s

Xcode build done.                                           10.6s
FirebaseAdMobPlugin <warning> [FIRApp configure]
5.12.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];`
(`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.12.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
5.12.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001136071bb __exceptionPreprocess + 331
        1   libobjc.A.dylib                     0x0000000112bad735 objc_exception_throw + 48
        2   CoreFoundation                      0x0000000113607015 +[NSException raise:format:] + 197
        3   Runner                              0x000000010b5cb800 +[FIRApp configure] + 576
        4   Runner                              0x000000010b63e7f8 -[FLTFirebaseAdMobPlugin init] + 248
        5   Runner                              0x000000010b63e56e +[FLTFirebaseAdMobPlugin registerWithRegistrar:] + 78
        6   Runner                              0x000000010b57595e +[GeneratedPluginRegistrant registerWithRegistry:] + 126
        7   Runner                           <…>
```

Software: 

- Mac OS: 10.13.6
- Xcode: 10.1
- Flutter 0.10.2 • channel beta • https://github.com/flutter/flutter.git
- Framework • revision d8cbb80206 (3 weeks ago) • 2018-10-26 01:30:21 -0400
- Engine • revision 6c2ade9fa2
- Tools • Dart 2.1.0-dev.8.0.flutter-bf26f760b1

**Comment by GyuriMajercsik** [comment]
> Same thing for me when I run `flutter run`
> 
> ## Logs
> ```
> Launching lib/main.dart on iPhone 8 in debug mode...
> Starting Xcode build...
>  ├─Assembling Flutter resources...                    2.2s
> 
>  └─Compiling, linking and signing...                  6.4s
> 
> Xcode build done.                                           10.6s
> FirebaseAdMobPlugin <warning> [FIRApp configure]
> 5.12.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];`
> (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
> 5.12.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
> 5.12.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
> *** First throw call stack:
> (
>         0   CoreFoundation                      0x00000001136071bb __exceptionPreprocess + 331
>         1   libobjc.A.dylib                     0x0000000112bad735 objc_exception_throw + 48
>         2   CoreFoundation                      0x0000000113607015 +[NSException raise:format:] + 197
>         3   Runner                              0x000000010b5cb800 +[FIRApp configure] + 576
>         4   Runner                              0x000000010b63e7f8 -[FLTFirebaseAdMobPlugin init] + 248
>         5   Runner                              0x000000010b63e56e +[FLTFirebaseAdMobPlugin registerWithRegistrar:] + 78
>         6   Runner                              0x000000010b57595e +[GeneratedPluginRegistrant registerWithRegistry:] + 126
>         7   Runner                           <…>
> ```
> ## Software
> * Mac OS: 10.13.6
> * Xcode: 10.1
> * Flutter 0.10.2 • channel beta • https://github.com/flutter/flutter.git
> * Framework • revision [d8cbb80](https://github.com/flutter/flutter/commit/d8cbb80206db06d151206f8b599b7dde5a386a2d) (3 weeks ago) • 2018-10-26 01:30:21 -0400
> * Engine • revision 6c2ade9fa2
> * Tools • Dart 2.1.0-dev.8.0.flutter-bf26f760b1

You should setup firebase for iOS as well, as mentioned in previous comment. 

It worked for me.

**Comment by VikasaurusRex** [comment]
I have gotten the same issue. It is caused when I try to integrate Firebase into my project. I believe if you want to replicate, you must attempt to add Firebase to your project following the instructions on Firebase's website. I ran `flutter packages get' and ran the project again (iPhone XS Max in Simulator). Then it was still not working so I went into the ios/ and ran `pod install` to install the pods and see if that would help (spoiler: it didn't). At this point I got the above errors. Since then, I have been editing and removing edits from ios/AppDelegate.swift to see if I can fix the problem by adding the FirebaseApp.configure() line. This was also to no avail, as I still get the above errors. Please advise.

**Comment by arzon94** [comment]
@VikasaurusRex I have also been struggling with this for the past day. Trying the IOS stuff suggested by crashless and similar steps to you did not work. Following the suggestion here [https://stackoverflow.com/questions/45317777/could-not-find-a-valid-googleservice-info-plist-in-your-project](url) worked! It seems like Xcode requires you to add the Google-Info.plist file in Xcode (I added my Google-Info.plist file through a different IDE primarily which I think is what caused the issue). Some clarification on the flutter documentation would help if this really is the issue.

**Comment by awazgyawali** [comment]
Maybe you guys didn't add Google Service-Info.plist using Xcode.

Check this https://github.com/flutter/flutter/issues/16871#issuecomment-383512995
Worked for me!!!!

**Comment by dark-chocolate** [comment]
@zoechi  Do we have to install `google-services.json` for showing Admob ads in the app? I am able to show the ads in Android (without putting `google-services.json` file) but for iOS it shows an error. 

`FirebaseAdMobPlugin <warning> [FIRApp configure]`

Even after adding 
`pod 'Firebase/AdMob'`
and running pod install, and using 
`[FIRApp configure];` in my `AppDelegate.m` file, it shows the same error. Do I have to include google-services.json file?

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by nanangassa88** [comment]
In my case using google map. I did not ass location permission in info.plist and applegate.m,
worst crash ever, no notice

**Comment by markzero** [comment]
In my case it was [this](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Core/FIRApp.m#L163).

I searched for `NSException ` since Flutter error log was very generic, not helpful. So, your app name when calling `FirebaseApp.configure` must not contain spaces. I thought it's a **NAME** but it's actually a slug, and I pasted from Firebase console the "Project name" field.

**Comment by kwmt** [comment]
In my case using firebase_admob. I did not update my info.plist.
https://firebase.google.com/docs/admob/ios/quick-start?hl=en#update_your_infoplist

**Comment by Faisalkc4u** [comment]
In my case, I was using Facebook and Google Auth. 
There was a conflict happen in Info.plist 

```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>fbxxxxxxxxxxxxx</string>
        </array>
    </dict>
	<dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLSchemes</key>
            <array>
              <string>com.google.xxxxxxxxxxx</string>
            </array>
          </dict>
</array>

<key>FacebookAppID</key>
<string>xxxxxxxxxx</string>
<key>FacebookDisplayName</key>
<string>Name</string>
```

This made it works perfectly.
Try to place this code after 
```

	<key>LSRequiresIPhoneOS</key>
	<true/>
```

**Comment by chithanh12** [comment]
I have the same issues on the firebase_admod

https://firebase.google.com/docs/admob/ios/quick-start?hl=en#update_your_infoplist

**Comment by alpertt5** [comment]
I had the same issue and my problem was about the name of the "Google Service-Info.plist" file. If you install this file more than once it gets like "thisGoogle Service-Info (1).plist". I just changed the name of the file by deleting "(1)" and it works.

**Comment by francomacri17** [comment]
> @VikasaurusRex I have also been struggling with this for the past day. Trying the IOS stuff suggested by crashless and similar steps to you did not work. Following the suggestion here [https://stackoverflow.com/questions/45317777/could-not-find-a-valid-googleservice-info-plist-in-your-project](url) worked! It seems like Xcode requires you to add the Google-Info.plist file in Xcode (I added my Google-Info.plist file through a different IDE primarily which I think is what caused the issue). Some clarification on the flutter documentation would help if this really is the issue.

I had followed all the steps, and I didn't understand what my mistake was. Your answer served for me.
Thank you!

**Comment by babaosoftware** [comment]
The problem seems to be, like @VikasaurusRex mentioned, that you cannot add GoogleService-Info.plist through Android Studio, you have to drag-and-drop the file directly into xcode. See this article, there's a screenshot of that step.
https://medium.com/flutterpub/enabling-firebase-cloud-messaging-push-notifications-with-flutter-39b08f2ed723
After that everything started working. It's really annoying, and a lot of time wasted for something that should be part of the official install steps. It might be obvious for people familiar with iOS development, I don't know.

**Comment by kroikie** [comment]
@firelight22

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/633. Any further collaboration will be done there.

**Comment by shahbajk28** [comment]
Xcode build done.                                           123.3s
	path: satisfied (Path is satisfied), interface: en1
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001176eb27e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00000001144c1b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001176eb0bc +[NSException raise:format:] + 188
	3   Runner                              0x000000010fa9395a +[FIRApp configure] + 138
	4   Runner                              0x000000010fa3a10f $s6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtF + 143
	5   Runner                              0x000000010fa3a4a4 $s6Runner11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0j6LaunchI3KeyaypGSgtFTo + 21<…>

**Comment by shahbajk28** [comment]
I have this issue I try much time but solve anyone can help me out
