### ISSUE TITLE
About Flutter Installation

### ISSUE THREAD

**Issue by Yogiraj-Patil** [flutter/flutter#22515]
I download Flutter and install in `H:/flutter/flutter` folder and update my Environment path for the  flutter.
but when i used `flutter doctor` command it shows 
my Environment Path for flutter is `H:\Flutter\flutter\bin;`

Doctor summary (to see all details, run flutter doctor -v):
```
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.3.9600], locale en-US)
Unhandled exception:
SocketException: Write failed (OS Error: The pipe is being closed.

, errno = 232), port = 0
#0 _rootHandleUncaughtError. (dart:async/zone.dart:1112:29)
#1 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3 _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4 _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5 _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
exit code 255
```

I am not getting this error and due to this i am cant able to try or learn flutter also i used both editor visual code and android studio but still same problem occurs 
hope u will help me 
Thankyou!

**Comment by zoechi** [comment]
Is there anything special with the `H:` drive? Does your current user have write permissions?

**Comment by Yogiraj-Patil** [comment]
Actually it's normal windows drive incase my all android related stuff is
in H: drive including Android SDK,Android studio etc..

**Comment by zoechi** [comment]
Closing as dup of #22223
