### ISSUE TITLE
The flex property should have type double instead of int

### ISSUE THREAD

**Issue by josvos** [flutter/flutter#22512]
Why is the `flex` property (e.g. in the `Flexible` widget) an int instead of a double?  If I for example want to use the golden ratio for relative sizing, I now have to use 161803398875 and 100000000000 as the (approximate) relative values.

**Comment by zoechi** [comment]
@Hixie

**Comment by zoechi** [comment]
@Hixie any plans to do anything about it or should the issue be closed?
Using `num` instead would allow `double` as well without breaking old code.

**Comment by zekunyan** [comment]
I have the same question...

**Comment by Hixie** [comment]
Using `num` is interesting.

In practice, just multiply your doubles by 1000 and round, and it'll be close enough. But yeah, maybe `num` would work. There's a performance cost there though.

**Comment by duzenko** [comment]
It should absolutely be `double` or `num` just to size Spacer to a fraction of a regular widget

```
                            Row(
                              children: <Widget>[
                                Spacer(flex: 0.5), // !!!
                                widget1,
                                widget2,
...
                                widgetN,
                              ],
                            ),
```

**Comment by Hixie** [comment]
@duzenko If there's only one widget with flex, the number has no effect anyway, whether it's 0.5, 1, 2, or 1000.

**Comment by duzenko** [comment]
> 
> 
> @duzenko If there's only one widget with flex, the number has no effect anyway, whether it's 0.5, 1, 2, or 1000.

It has if other widgets are Expanded, etc.

**Comment by weenzeel** [comment]
Could the flex property be changed to double now that Dart 2.10 made integer literals work in double contexts?

From the Dart Changelog for version 2.10:

When passing a literal number to a function that expects a double, you no longer need an explicit .0 at the end of the number. In releases before 2.1, you need code like this when setting a double like fontSize:

TextStyle(fontSize: 18.0)
Now you can remove the .0:

TextStyle(fontSize: 18)
In releases before 2.1, fontSize : 18 causes a static error. This was a common mistake and source of friction.

**Comment by HassanElshazlyEida** [comment]
```
                 Expanded(
                    flex: 1500, // 15%
                    child: Container(color: Colors.red),
                  ),
                  Expanded(
                    flex: 3000, // 30%
                    child: Container(color: Colors.green),
                  ),
                  Expanded(
                    flex: 5000, // 50%
                    child: Container(color: Colors.blue),
                  )
```

**Comment by Hixie** [comment]
@ValentinVignal did great work in https://github.com/flutter/flutter/pull/147976 to investigate the performance impact of using `num` and we concluded that it's not worth it, so I'm going to close this.
