### ISSUE TITLE
Get Android unique ID

### ISSUE THREAD

**Issue by Nik99** [flutter/flutter#22513]
I'm trying to use the plugin device_info for getting unique device IDS for both Android and IOS.
While iOS does have vendorID, on the Android side there is not a secure ID or something similar.

Is it possible to implement it ? I've tryed external libraries but they aren't udated and i think this should be something integrated in to Flutter.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

https://stackoverflow.com/questions/45031499/how-to-get-unique-device-id-in-flutter
