### ISSUE TITLE
Update all Flutter repo "example" apps to use the new project structure

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#22529]
Update all Flutter repo "example" apps to use the new project structure.

This should be done after the "flutter create -t project" and "flutter make-host-app-editable" commands are working on master.

**Comment by mit-mit** [comment]
As a way of testing the new default application testing, I created a new hello_world, and moved over the existing .dart files, and verified that it still ran. Sent a PR for that: https://github.com/flutter/flutter/pull/22716

@gspencergoog will you be looking at the others?

**Comment by mit-mit** [comment]
Topic raised in https://github.com/flutter/flutter/pull/22716: For apps that need custom hosts (for platform channels, icons, etc.), we would need to make the hosts editable.

**Comment by matthew-carroll** [comment]
Closing as done.
