### ISSUE TITLE
Ability to disable text selection in TextField

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#22520]
mulligan has a text field that does not have a cursor and does not permit text to be selected. However, it still has other Material features such as the error display and the border. This was already UX approved and launched in their legacy app.

**Comment by alanrussian** [comment]
We also want to disable changing the selection including the cursor position (effectively always leaving it at the end of the field). Let me know if I should file a separate issue for this.

**Comment by Hixie** [comment]
Does InputDecoration do what you describe? (It provides the ability to do all the things you can do with a text field, minus the "text field" part.)

**Comment by alanrussian** [comment]
We need to be able to remove the cursor handle. This is provided by the `TextSelectionControls` class via `EditableText`'s `selectionControls` parameter. The `TextField` class does not support specifying a customer `selectionControls`. [It only builds the `EditableText` with the material or cupertino controls.](https://github.com/flutter/flutter/blob/85b4670b2aee067838821d4c4020315c16e8930a/packages/flutter/lib/src/material/text_field.dart#L570-L572)

**Comment by HansMuller** [comment]
Does this text field support taking the focus and input? 

If it's just a text display that looks like a TextField, then:
```
InputDecorator(decoration: InputDecoration(...), child: const Text('Hello World'))
```

**Comment by alanrussian** [comment]
It does support taking focus and input. The cursor is effectively always at the end of the input. It's kind of like the Google Wallet input field.

**Comment by HansMuller** [comment]
OK, I think I understand what's needed.

**Comment by HansMuller** [comment]
@alanrussian Should users interacting with this textfield via an a11y interface like TalkaBack or VoiceOver be prevented from moving the caret or selecting/copy/pasting text?

**Comment by alanrussian** [comment]
Yes.

**Comment by flutterq** [comment]
Step By Step Guide to [How to disable text edit field in flutter ?](https://flutterq.com/wp-admin/post.php?post=243&action=edit)
