### ISSUE TITLE
Measure/benchmark edit/refresh cycle

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2253]
In order to help catch regressions in our dev edit/refresh cycle, we might consider benchmarking and measuring the timings of `flutter run` for android devices, emulator, ios devices, simulator.

**Comment by sethladd** [comment]
cc @devoncarew @yjbanov

**Comment by eseidelGoogle** [comment]
I believe we do this now, no?  @johnmccutchan

**Comment by abarth** [comment]
We do this now.
