### ISSUE TITLE
 android.graphics.SurfaceTexture.setOnFrameAvailableListener

### ISSUE THREAD

**Issue by Mariluk** [flutter/flutter#22549]
Hello,

After update flutter my camera plugin crash for Android SDK < 21. Higher is ok. The crash occurs on the line with the createSurfaceTexture method.

`FlutterView.SurfaceTextureEntry surfaceTextureEntry = flutterView.createSurfaceTexture();`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.9.4-pre.31, on Linux, locale cs_CZ.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
Please post the full error output.

**Comment by Mariluk** [comment]
E/flutter (19939): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
E/flutter (19939):      at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:1044)
E/flutter (19939):      at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:1030)
E/flutter (19939):      at cz.bcx.qrscanner.Camera1.createCameraInstance(Camera1.java:72)
E/flutter (19939):      at cz.bcx.qrscanner.QrScannerPlugin$2.run(QrScannerPlugin.java:206)
E/flutter (19939):      at cz.bcx.qrscanner.QrScannerPlugin.onInitialize(QrScannerPlugin.java:220)
E/flutter (19939):      at cz.bcx.qrscanner.QrScannerPlugin.onMethodCall(QrScannerPlugin.java:93)
E/flutter (19939):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/flutter (19939):      at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/flutter (19939):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (19939):      at android.os.MessageQueue.next(MessageQueue.java:138)
E/flutter (19939):      at android.os.Looper.loop(Looper.java:150)
E/flutter (19939):      at android.app.ActivityThread.main(ActivityThread.java:5292)
E/flutter (19939):      at java.lang.reflect.Method.invokeNative(Native Method)
E/flutter (19939):      at java.lang.reflect.Method.invoke(Method.java:515)
E/flutter (19939):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
E/flutter (19939):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
E/flutter (19939):      at dalvik.system.NativeStart.main(Native Method)
E/flutter (19939): 
F/flutter (19939): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).

**Comment by Mariluk** [comment]
#21730

**Comment by zoechi** [comment]
Merging with #21730
