### ISSUE TITLE
[Error] Could not build Objective-C module when adding the objc framework in plugin

### ISSUE THREAD

**Issue by dzeroab** [flutter/flutter#22543]
hi all
i want to add the objc framework to my flutter plugin. i search around and found the solution that 
adding the below lines into plugin podspec file

```
s.preserve_paths = ‘./my_framwork'
s.xcconfig = { 'OTHER_LDFLAGS' => '-framework my_framwork' }
s.framework = “my_framwork"
s.vendored_frameworks = 'my_framwork.framework'
```
but i got the error "error: could not build Objective-C module"
can someone help me?
p/s: i'm an android dev. dont know much about ios

**Comment by zoechi** [comment]
Looks related #14214

**Comment by markusaksli-nc** [comment]
Hi @dzeroab 
The plugin development [guide](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm) has been updated since this issue was created. Is this still relevant?
Thank you

**Comment by dzeroab** [comment]
Thanks @markusaksli-nc, i think we can close this ticket 
thanks so much
