### ISSUE TITLE
iOS toolchain error when running flutter doctor

### ISSUE THREAD

**Issue by DamionA** [flutter/flutter#22564]
I have gone through the set up as per the instruction on flutter.io and i keep getting an error on the iOS toolchain section.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

Every time i run brew install --HEAD libimobiledevice i get another error and i am at a loss on how to fix it. 

==> ./autogen.sh
Last 15 lines from /Users/dewy/Library/Logs/Homebrew/libimobiledevice/01.autogen.sh:
checking dynamic linker characteristics... darwin17.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libusbmuxd >= 1.1.0... no
configure: error: Package requirements (libusbmuxd >= 1.1.0) were not met:

Requested 'libusbmuxd >= 1.1.0' but version of libusbmuxd is 1.0.10

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libusbmuxd_CFLAGS
and libusbmuxd_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details

I have tried a couple of ideas and did some googling but couldn't find an answer

**Comment by hasseye** [comment]
Having the same problem. Let me know if you resolve it.

**Comment by danielwii** [comment]
Solved by this: https://stackoverflow.com/a/52604913/3480445

**Comment by zoechi** [comment]
@DamionA does @danielwii's suggestion help?

**Comment by DamionA** [comment]
That has worked a treat, thanks @danielwii

**Comment by shyandsy** [comment]
the message shows after the flutter upgraded to 1.2.1

```
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
```

the method provided by @danielwii doesnt work

**Comment by LiuL0703** [comment]
> the message shows after the flutter upgraded to 1.2.1
> 
> ```
> [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     ✗ Verify that all connected devices have been paired with this computer in Xcode.
>       If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
>       To update with Brew, run:
>         brew update
>         brew uninstall --ignore-dependencies libimobiledevice
>         brew uninstall --ignore-dependencies usbmuxd
>         brew install --HEAD usbmuxd
>         brew unlink usbmuxd
>         brew link usbmuxd
>         brew install --HEAD libimobiledevice
>         brew install ideviceinstaller
> ```
> all the commands listed above has been performed, not work
> 
> the method provided by @danielwii doesnt work

same problem

**Comment by eduardo-calzado-agentero** [comment]
Same here...

**Comment by ripperhe** [comment]
Same here...

**Comment by arwaal** [comment]
`[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller`

HELP!
it runs in my simulator tho!

**Comment by imrakilahmed** [comment]
Hey guys, it seems this issue can be fixed (at least ios toolchains issue) by plugging in a iphone 6 or 6s (older works maybe IDK) then try flutter doctor again...

**Comment by Zhaimm** [comment]
![Snip20190507_7](https://user-images.githubusercontent.com/32920612/57270235-11b95800-70bd-11e9-89c6-f7827d50fb14.png)
同样的问题

**Comment by ripperhe** [comment]
我重启电脑就好了，过一会儿又报错，但是貌似不影响使用

**Comment by ImproperMelon** [comment]
try this:https://github.com/nesger/FlutterNote/issues/1#issuecomment-444806569
