### ISSUE TITLE
Support "--target" on iOS

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#2256]
Flutter CLI does not support `--target` when running on iOS (in fact it silently ignores this option and defaults to `lib/main.dart`). We should add this support. Lack of this support means developers won't be able to create mini test apps for e2e testing in the same project.

### Flutter Version

flutter revision: 7792ba083bcec67fd0d0f8ede65304936f06b06d (3 days ago)
engine revision : d4f97e4fd143b075b52269e22098339941525d8e

**Comment by chinmaygarde** [comment]
Working on it. Fix will be up for review today.
