### ISSUE TITLE
After running flutter upgrade I get this error and it broke my project

### ISSUE THREAD

**Issue by Isonomic** [flutter/flutter#22562]
. The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because practice_app depends on location >=1.0.1 <1.4.1 which requires SDK version <2.0.0, version solving failed.
pub get failed (1)
exit code 1

**Comment by zoechi** [comment]
Change the version constraint for `location` to allow newer versions
 
```yml
dependencies:
   location: ^1.4.1
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
