### ISSUE TITLE
App Store Upload fails when App.framework.dSYM is present

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#22560]
See https://github.com/flutter/flutter/pull/22540. There are several open questions:

Does the same happen when dSYM files for other frameworks are present, e.g. `FLutter.framework.dSYM`? Is this a problem with how we generate App.framework.dSYM? Is this a bug in Xcode or `symbols`, which Xcode calls during App Store Upload?

**Comment by goderbauer** [comment]
Work around is to hide App.framework.dSYM from Spotlight, which `symbols` uses to find dSYM files.

**Comment by goderbauer** [comment]
During App Store upload, Xcode executes the following command (make sure `~/Desktop/symbols` exists before running):

```
symbols -noTextInSOD -noDaemon -arch all -symbolsPackageDir ~/Desktop/symbols App.framework/App
```

When `App.framework.dSYM` is indexed by Spotlight this fails with

```
pp [armv7, 0.000992 seconds]:
error: Could not load symbol information for 61FCF67E-9AD8-3B99-A788-1A68A41F0066.  Symbols file will contain no data.
App [arm64, 0.000992 seconds]:
error: Could not load symbol information for 335E4359-0E7F-3133-B2AE-5BCC7648D032.  Symbols file will contain no data.
```

When the dSYM file is not present (or hidden from Spotlight in a folder ending with `.noindex`) the call to symbols is successful:

```
App [armv7, 0.006400 seconds]:
App [arm64, 0.006400 seconds]:
```

Interestingly, the same `symbols` call on `Flutter.framework/Flutter` succeeds whether or not its dSYM file is present. This makes me believe that the problem is specific to `App.framework`.

**Comment by goderbauer** [comment]
Some interesting background reading:
* http://wiki.dwarfstd.org/index.php?title=Apple%27s_%22Lazy%22_DWARF_Scheme
* https://stackoverflow.com/questions/10044697/where-how-does-apples-gcc-store-dwarf-inside-an-executable

**Comment by gwik** [comment]
I have the same issue with a other project when linking a static framework. Is flutter a static framework 
 library ?

**Comment by jmagman** [comment]
I don't think this is an issue, https://github.com/flutter/flutter/pull/101586 likely made this obsolete.
