### ISSUE TITLE
Problem running custom Flavor on iOS

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#22587]
I am trying to creating custom flavos. Everything works fine for Android and the gradle build system, but for iOS things are more problematic.

When I try to run the app using custom schemes and, each using a custom .xcconfg file (containing the custom bundleID), the flutter compiler cannot attach to the device. It builds correctly, the app ins installed on the device but does not start automatically and hot reload does not work.

This is my custom .xconfig:
```
#include "Generated.xcconfig"
FLUTTER_TARGET=lib/run_porto.dart
IS_APP_BUNDLE_ID=com.denox.mydenox.porto
IS_APP_NAME=Porto
```
_I have other files, each one has a **different bundleId**._

I've run the command: **flutter run --debug -v -t lib/run_denox.dart --flavor porto** and get this error on the end:

**An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
           The request to open "${IS_APP_BUNDLE_ID}" failed.
           The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "${IS_APP_BUNDLE_ID}" is unknown to FrontBoard").**

**Comment by leorachit** [comment]
need help on this

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

https://github.com/flutter/flutter/issues/21335#issuecomment-423969759 might help to work around

Merging with #15567
