### ISSUE TITLE
libimobiledevice install instructions are incorrect

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#22595]
Originally [reported on StackOverflow](https://stackoverflow.com/questions/52602425/libusbmuxd-version-error-during-flutter-install).

A [recent change](https://github.com/libimobiledevice/libimobiledevice/commit/f1ee0fd8b2b1dd65c64f5a67e208efc708295caa) to `libimobiledevice` [bumped the constraint](https://github.com/libimobiledevice/libimobiledevice/commit/f1ee0fd8b2b1dd65c64f5a67e208efc708295caa#diff-67e997bcfdac55191033d57a16d1408aL21) on libusbmuxd to >= version 1.1.0. The current `usbmuxd` homebrew package is version 1.0.10.

As a result, homebrew `--HEAD` installs of libimobiledevice no longer build without a `--HEAD` install of `usbmuxd`.

Until the `usbmuxd` homebrew formula is updated, a workaround is to install it at HEAD:

```
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
```

Ideally, we should send a PR to get the `usbmuxd` homebrew formula updated to 1.1.0. If we can't do that, we should update the instructions we emit from `flutter doctor`.

**Comment by cbracken** [comment]
Instructions are updated in flutter doctor. Based on the fact that my stackoverflow karma from [my original answer](https://stackoverflow.com/questions/52602425/libusbmuxd-version-error-during-flutter-install) has stopped, I think it's safe to close this.

If someone wants to send a PR to the libusbmuxd brew recipe, that can be done as a separate followup.

**Comment by sjmcdowall** [comment]
This is (maybe) a related question -- but -- why am I still seeing an error/warning in the iOS part of flutter doctor when I did the instructions -- and I don't even have any devices connected (iOS ones) at the time?  This started ever since I upgraded to Flutter 0.11.9 .. I am not sure I understand the logic it is using for the error.  

flutter doctor -v                                                                                                         ✔  10085  13:37:41
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14.1 18B75, locale en)
    • Flutter version 0.11.9 at /Users/sjm/Development/flutter
    • Framework revision d48e6e433c (6 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sjm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Users/sjm/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
  …/mms4/mobile     8537fcc1  master   1  flutter devices                                                                                                           ✔  10086  13:37:54
1 connected device:

Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

**Comment by tvolkert** [comment]
The message could certainly be improved in the case of no connected devices.  It's basically saying that it's detected that your `libimobiledevice` and `usbmuxd` are out of date and could cause issues if you *were* to attach devices.

**Comment by sjmcdowall** [comment]
@tvolkert -- except I am still seeing the exact same message after I followed the steps outlined in the flutter doctor -v .. so .. something is a bit amiss I think?

**Comment by tvolkert** [comment]
@sjmcdowall ah, sorry I missed that part of your comment before.  Can  you please file a separate issue with the output of `flutter --verbose doctor -v` (note the extra `--verbose`)?  Thanks!

**Comment by sjmcdowall** [comment]
Ha!  Go figure -- now flutter doctor -v is a happy camper once I DID plug in an iOS physical device .. no other changes.. I guess if there is no physical device plugged in so it doesn't know if it will work -- it puts out the error?  That seems ... wrong and "scary"

**Comment by neiljaywarner** [comment]
@eseidelGoogle Any thoughts here please?

**Comment by tvolkert** [comment]
The real fix here is to have usbmuxd update their homebrew formula to list `1.1.0` as stable.  Until they do, we need to tell users to install usbmuxd at HEAD.

**Comment by tvolkert** [comment]
Filed https://github.com/Homebrew/homebrew-core/issues/34601

**Comment by ciscolxh** [comment]
[  +58 ms] executing: [/Users/howard/Public/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +110 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] origin/beta
[   +1 ms] executing: [/Users/howard/Public/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +5 ms] beta
[  +18 ms] executing: [/Users/howard/Public/flutter/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/howard/Public/flutter/flutter/] git log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/howard/Public/flutter/flutter/] git log -n 1 --pretty=format:%ar
[  +16 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 days ago
[   +1 ms] executing: [/Users/howard/Public/flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +79 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fae
[ +539 ms] executing: /usr/bin/defaults read /Applications/Android Studio 2.app/Contents/Info CFBundleShortVersionString
[ +261 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio 2.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +944 ms] executing: /usr/bin/defaults read /Applications/Android Studio 2.app/Contents/Info CFBundleShortVersionString
[  +95 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio 2.app/Contents/Info CFBundleShortVersionString
[        ] 3.1
[ +121 ms] java -version
[ +685 ms] executing: idevice_id -h
[  +10 ms] executing: idevice_id -h
[  +10 ms] executing: ideviceinfo -u 00008020-001C2D903C42002E
[  +16 ms] executing: pod --version
[ +188 ms] executing: /usr/bin/defaults read /Applications/IntelliJ IDEA.app/Contents/Info CFBundleShortVersionString
[  +94 ms] Exit code 0 from: /usr/bin/defaults read /Applications/IntelliJ IDEA.app/Contents/Info CFBundleShortVersionString
[        ] 2017.3.1
[  +51 ms] [✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[   +1 ms]     • Flutter version 1.0.0 at /Users/howard/Public/flutter/flutter
[        ]     • Framework revision 5391447fae (8 days ago), 2018-11-29 19:41:26 -0800
[        ]     • Engine revision 7375a0f414
[        ]     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
⣾[   +3 ms] executing: /Users/howard/Public/androidsdk/android-sdk-macosx/platform-tools/adb devices -l
[  +26 ms] Exit code 0 from: /Users/howard/Public/androidsdk/android-sdk-macosx/platform-tools/adb devices -l
[        ] List of devices attached
           621MECQH3FLM2          device usb:336592896X product:meizu_M5 Note model:M5_Note device:M5Note transport_id:1
[  +12 ms] executing: idevice_id -h
⣽[ +207 ms] Usage: ideviceinfo [OPTIONS]
                    Show information about a connected device.

                      -d, --debug		enable communication debugging
                      -s, --simple		use a simple connection to avoid auto-pairing with the device
                      -u, --udid UDID	target specific device by its 40-digit device UDID
                      -q, --domain NAME	set domain of query to NAME. Default: None
                      -k, --key NAME	only query key specified by NAME. Default: All keys.
                      -x, --xml		output information as xml plist instead of key/value pairs
                      -h, --help		prints usage information

                      Known domains are:

                      com.apple.disk_usage
                      com.apple.disk_usage.factory
                      com.apple.mobile.battery
                      com.apple.iqagent
                      com.apple.purplebuddy
                      com.apple.PurpleBuddy
                      com.apple.mobile.chaperone
                      com.apple.mobile.third_party_termination
                      com.apple.mobile.lockdownd
                      com.apple.mobile.lockdown_cache
                      com.apple.xcode.developerdomain
                      com.apple.international
                      com.apple.mobile.data_sync
                      com.apple.mobile.tethered_sync
                      com.apple.mobile.mobile_application_usage
                      com.apple.mobile.backup
                      com.apple.mobile.nikita
                      com.apple.mobile.restriction
                      com.apple.mobile.user_preferences
                      com.apple.mobile.sync_data_class
                      com.apple.mobile.software_behavior
                      com.apple.mobile.iTunes.SQLMusicLibraryPostProcessCommands
                      com.apple.mobile.iTunes.accessories
                      com.apple.mobile.internal
                      com.apple.mobile.wireless_lockdown
                      com.apple.fairplay
                      com.apple.iTunes
                      com.apple.mobile.iTunes.store
                      com.apple.mobile.iTunes

                    Homepage: <http://libimobiledevice.org>
[  +11 ms] executing: ios-deploy --version
⣻[ +112 ms] executing: /Users/howard/Public/androidsdk/android-sdk-macosx/tools/bin/sdkmanager --licenses
[   +3 ms] executing: ios-deploy --version
⢿[  +46 ms] 1.9.4
[   +5 ms] executing: ios-deploy --version
[  +44 ms] executing: ios-deploy --version
⡿[  +35 ms] 1.9.4
⣷[ +358 ms] executing: which ideviceinstaller
[  +18 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[  +14 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +6 ms] /usr/bin/xcrun simctl list --json devices
[ +639 ms] /Users/howard/Public/androidsdk/android-sdk-macosx/platform-tools/adb -s 621MECQH3FLM2 shell getprop
⣽[ +126 ms] ro.hardware = mt6755
[        ] ro.build.characteristics = default
⣟[ +384 ms] 1.5.3
[+3139 ms] [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[        ]     • Android SDK at /Users/howard/Public/androidsdk/android-sdk-macosx
[        ]     • Android NDK at /Users/howard/Public/androidsdk/android-sdk-macosx/ndk-bundle
[        ]     • Platform android-28, build-tools 28.0.3
[        ]     • ANDROID_HOME = /Users/howard/Public/androidsdk/android-sdk-macosx
[        ]     • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
[        ]     • All Android licenses accepted.
[   +1 ms] [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 10.1, Build version 10B61
[        ]     ✗ Verify that all connected devices have been paired with this computer in Xcode.
[        ]       If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
[        ]       To update with Brew, run:
[        ]         brew update
[        ]         brew uninstall --ignore-dependencies libimobiledevice
[        ]         brew uninstall --ignore-dependencies usbmuxd
[        ]         brew install --HEAD usbmuxd
[        ]         brew unlink usbmuxd
[        ]         brew link usbmuxd
[        ]         brew install --HEAD libimobiledevice
[        ]         brew install ideviceinstaller
[  +23 ms]     • ios-deploy 1.9.4
[        ]     • CocoaPods version 1.5.3
[        ] [✓] Android Studio (version 3.1)
[        ]     • Android Studio at /Applications/Android Studio 2.app/Contents
[        ]     • Flutter plugin version 25.0.1
[        ]     • Dart plugin version 173.4700
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
[        ] [✓] IntelliJ IDEA Ultimate Edition (version 2017.3.1)
[        ]     • IntelliJ at /Applications/IntelliJ IDEA.app
[        ]     • Flutter plugin version 25.0.1
[        ]     • Dart plugin version 173.3942.31
[        ] [✓] Connected device (2 available)
[        ]     • M5 Note     • 621MECQH3FLM2                            • android-arm64 • Android 6.0 (API 23)
[        ]     • iPhone • 50c8d8d6c76c8fc70921c11657806153444ececb • ios           • iOS 12.1
[        ] ! Doctor found issues in 1 category.
[  +18 ms] "flutter doctor" took 8,156ms.

What should I do?

**Comment by ciscolxh** [comment]
I have done these actions but did not solve the problem
What should I do?
 run:
[ ] brew update
[ ] brew uninstall --ignore-dependencies libimobiledevice
[ ] brew uninstall --ignore-dependencies usbmuxd
[ ] brew install --HEAD usbmuxd
[ ] brew unlink usbmuxd
[ ] brew link usbmuxd
[ ] brew install --HEAD libimobiledevice
[ ] brew install ideviceinstaller

**Comment by sjmcdowall** [comment]
Try running flutter doctor -v but with a real physical iOS device plugged in ..

I.e. flutter devices recognizes it ..

**Comment by Romnn** [comment]
Its 31 Jan  2019 and the first comment worked.  Thank You

![screen shot 2019-01-31 at 8 55 14 pm](https://user-images.githubusercontent.com/16022010/52063398-ae3dfc80-259a-11e9-98ca-363abbf0283c.png)

**Comment by Romnn** [comment]
This one : https://github.com/flutter/flutter/issues/22595#issue-366137390 
I was having issues with iOS toolchain devices . Still, Android Studio couldn’t install my app to iPad, it suggested to use Runner.workspace file with Xcode. With code signin, it worked. 👍👌

**Comment by Romnn** [comment]
> Originally [reported on StackOverflow](https://stackoverflow.com/questions/52602425/libusbmuxd-version-error-during-flutter-install).
> 
> A [recent change](https://github.com/libimobiledevice/libimobiledevice/commit/f1ee0fd8b2b1dd65c64f5a67e208efc708295caa) to `libimobiledevice` [bumped the constraint](https://github.com/libimobiledevice/libimobiledevice/commit/f1ee0fd8b2b1dd65c64f5a67e208efc708295caa#diff-67e997bcfdac55191033d57a16d1408aL21) on libusbmuxd to >= version 1.1.0. The current `usbmuxd` homebrew package is version 1.0.10.
> 
> As a result, homebrew `--HEAD` installs of libimobiledevice no longer build without a `--HEAD` install of `usbmuxd`.
> 
> Until the `usbmuxd` homebrew formula is updated, a workaround is to install it at HEAD:
> 
> ```
> brew update
> brew uninstall --ignore-dependencies libimobiledevice
> brew uninstall --ignore-dependencies usbmuxd
> brew install --HEAD usbmuxd
> brew unlink usbmuxd
> brew link usbmuxd
> brew install --HEAD libimobiledevice
> ```
> Ideally, we should send a PR to get the `usbmuxd` homebrew formula updated to 1.1.0. If we can't do that, we should update the instructions we emit from `flutter doctor`.

![](https://user-images.githubusercontent.com/16022010/52063398-ae3dfc80-259a-11e9-98ca-363abbf0283c.png)

**Comment by eduardo-calzado-agentero** [comment]
I solved the problem just **connecting an real iPhone device** to my computer. I hope it helps someone.

Before connecting it:
> $ flutter doctor -v
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

After that:
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

**Comment by wensonsmith** [comment]
@eduardo-calzado-agentero  Thanks, you save my day!

**Comment by FedericoHenze** [comment]
In my case, it only works after I deleted al the homebrew cache

`rm -rf ~/Library/Caches/Homebrew/`

After it, I just followed the instruction in the Flutter site

**Comment by umukoro6** [comment]
Thanks. This worked perfectly. After three weeks of debugging. I almost gave up...

**Comment by shrop** [comment]
I was having some different issues with thinks like `./config.status: line 1337: /usr/bin/awk: Permission denied` and `./config.status: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/sed: /bin/bash: bad interpreter: Permission denied`

I was in Zsh and just ran the same commands in bash and they worked. I know this probably isn’t directly related to the issue at hand, but in case someone has some odd configure and make related errors.

**Comment by 0123cf** [comment]
I have the same problem. I was okay last time, but this time I can't. I want to know what happened. I don't want to update it all the time. I just want to be able to do it the next time I execute it. Because it's very unstable, it makes me very troublesome and insecure. I never know what's going to happen next. And I'm in China. China has walls. It takes tens of hours to download something.



Thank you

----

我同样的问题，我上次还可以，这次运行就不行，我想知道到底发生了什么，我不想动不动就更新，我只想当我下次执行的时候依然可以。因为这很不稳定，让我很麻烦，也很没有安全感，我永远也不知道下一步会发生什么。而且我是在中国，中国有墙，下载一个东西往往就是几十个小时。

谢谢

**Comment by tvolkert** [comment]
Note that on the newest versions of Flutter, you no longer have to install libimobiledevice - it's bundled with the Flutter SDK.

**Comment by 0123cf** [comment]
> Note that on the newest versions of Flutter, you no longer have to install libimobiledevice - it's bundled with the Flutter SDK.

I had run `flutter run'successfully before. Why did I install libimobiledevice this time? Do I automatically update something when my device has a network?

**Comment by 0123cf** [comment]
```

file:///Users/xiexiuyue/Documents/flutter/packages/flutter/lib/src/semantics/sem
antics.dart:3790:4: Error: This can't be used as metadata; metadata should be a
reference to a compile-time constant variable, or a call to a constant
constructor.
  @required TextDirection thisTextDirection,
   ^
file:///Users/xiexiuyue/Documents/flutter/packages/flutter/lib/src/semantics/sem
antics.dart:3791:4: Error: Getter not found: 'required'.
  @required TextDirection otherTextDirection,
   ^^^^^^^^
file:///Users/xiexiuyue/Documents/flutter/packages/flutter/lib/src/semantics/sem
antics.dart:3791:4: Error: This can't be used as metadata; metadata should be a
reference to a compile-time constant variable, or a call to a constant
constructor.
  @required TextDirection otherTextDirection,
   ^
Compiler failed on /Users/xiexiuyue/Documents/www/flutter/cjyy/lib/main.dart
Error launching application on iPhone Xʀ.
xiexiuyuedeMacBook-Pro:cjyy xiexiuyue$ 

```

flutter run   ERROR

@tvolkert

**Comment by patelkrunal78** [comment]
This Can help You https://icetutor.com/question/libusbmuxd-version-error-during-flutter-install/

**Comment by Krunal79-flutter** [comment]
Maybe This Can Solve Your Error

**Comment by patelkeval78** [comment]
A recent change to libimobiledevice bumped the constraint on libusbmuxd to >= version 1.1.0. The current usbmuxd homebrew package is version 1.0.10.

As a result, homebrew --HEAD installs of libimobiledevice no longer build without a --HEAD install of usbmuxd.

Until the usbmuxd homebrew formula is updated, a workaround is to install it at HEAD:

brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew install --HEAD libimobiledevice

See More at [Here](https://icetutor.com/question/libusbmuxd-version-error-during-flutter-install/)

**Comment by enesecer** [comment]
Hi, 
I have the same problem with different versions. I'm trying to follow the steps from first post but can't install: $brew install --HEAD usbmuxd

Getting this error: 
Updating Homebrew...
==> Cloning https://git.sukimashita.com/libusbmuxd.git
Updating /Users/mobile/Library/Caches/Homebrew/usbmuxd--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at c7d7d1a Post release version bump to 2.0.3
==> ./autogen.sh
Last 15 lines from /Users/mobile/Library/Logs/Homebrew/usbmuxd/01.autogen.sh:
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libplist-2.0 >= 2.2.0... no
configure: error: Package requirements (libplist-2.0 >= 2.2.0) were not met:

No package 'libplist-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libplist_CFLAGS
and libplist_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Thanks!
