### ISSUE TITLE
Can't produce 32-bit armv7 binaries from a 64-bit environment

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#22598]
## Steps to Reproduce

```
./flutter/tools/gn --android --runtime-mode release
ninja -C out/android_release
```

Up to now I have built the engine many times. But this week I can not build for Android. I do not know which version is problematic or another problem. Last week I updated Xcode to `10.0 (10A255)`.

I tried engine revisions `38a646e14cc25f5a56a989c6a5787bf74e0ea386
`(used from v0.9.5) and `58a1894a1cd798de2f9a206f157a90d45944028b`(used from v0.8.2).

`ninja -C out/ios_release` is OK.

## Logs

```
ninja: Entering directory `out/android_release'
[1/5] LINK clang_x86/gen_snapshot
FAILED: clang_x86/gen_snapshot 
../../buildtools/mac-x64/clang/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -m32 -flto -stdlib=libc++ -Wl,-dead_strip -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie -Xlinker -rpath -Xlinker @executable_path/Frameworks -o clang_x86/gen_snapshot -Wl,-filelist,clang_x86/gen_snapshot.rsp  -framework CoreFoundation -framework CoreServices -framework AppKit -framework ApplicationServices -framework Carbon -framework CoreVideo -framework Foundation -framework OpenGL -framework Security -framework IOKit -ldl -lpthread
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreServices.framework/CoreServices.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreServices.framework/CoreServices.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//ApplicationServices.framework/ApplicationServices.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//ApplicationServices.framework/ApplicationServices.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Carbon.framework/Carbon.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Carbon.framework/Carbon.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreVideo.framework/CoreVideo.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreVideo.framework/CoreVideo.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//OpenGL.framework/OpenGL.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//OpenGL.framework/OpenGL.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd (2 slices)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//AppKit.framework/AppKit.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//AppKit.framework/AppKit.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libpthread.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Foundation.framework/Foundation.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//IOKit.framework/IOKit.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//IOKit.framework/IOKit.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Security.framework/Security.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks//Security.framework/Security.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libc++.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libc++.tbd
Undefined symbols for architecture i386:
  "_trunc", referenced from:
      __GLOBAL__sub_I_runtime_entry.cc in lto.o
     (maybe you meant: __ZN4dart12Intrinsifier19Integer_truncDivideEPNS_9AssemblerEPNS_5LabelE, __ZN4dart26FLAG_truncating_left_shiftE , __ZN4dart16BootstrapNatives19DN_Double_trunc_divEP21_Dart_NativeArguments , __ZN4dart16BootstrapNatives18DN_Double_truncateEP21_Dart_NativeArguments , __ZN4dart16BootstrapNatives30DN_Integer_truncDivFromIntegerEP21_Dart_NativeArguments )
```
... many errors ...
```
ld: symbol(s) not found for architecture i386
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

whole log: https://gist.github.com/najeira/82b601dcc4184bda9e9033766af2d092

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale ja-JP)
    • Flutter version 0.8.2 at /Applications/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0
```

**Comment by najeira** [comment]
Xcode 10 SDK seems not to include i386 architecture.

**Comment by zoechi** [comment]
#17749 looks similar but for iOS.

**Comment by dilbert2** [comment]
Get the MacOS 10.13 SDK from Xcode 9.4 from [Apple](https://developer.apple.com/download/more/) or [Github]( https://github.com/alexey-lysiuk/macos-sdk)， and uncompress the SDK into /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs and name the SDK `MacOSX10.13.sdk` ... This works for me.
（Refer to [Supporting-legacy-platforms](https://github.com/flutter/flutter/wiki/Supporting-legacy-platforms#building-armv7-ios--armeabi-v7a-android-with-xcode10) ）

**Comment by dnfield** [comment]
Can't build Flutter engine with Xcode 10 because it removed i386 support - but that's required at this point.  I believe there's another issue open for this but I can't find it, @cbracken  knows more.

**Comment by cbracken** [comment]
Correct - Xcode 10 removed 32-bit stubs for linking against the macOS SDK. This is required for to build the armv7 build of `gen_snapshot` (used for AOT compilation).

The upstream bug is dart-lang/sdk#31709.

**Comment by cbracken** [comment]
Assigned to @mraleph who'll be working on this.

**Comment by GuoZhiQiang** [comment]
As @cbracken @najeira said above you can do this : 

If you have multi-version of Xcode , run the command 
`sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

In which replace `Xcode.app` with the name of your Xcode9.4

**Comment by MilkBiscuit** [comment]
> Get the MacOS 10.13 SDK from Xcode 9.4 from [Apple](https://developer.apple.com/download/more/) or [Github](https://github.com/alexey-lysiuk/macos-sdk)， and uncompress the SDK into /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs and name the SDK `MacOSX10.13.sdk` ... This works for me.
> （Refer to [Supporting-legacy-platforms](https://github.com/flutter/flutter/wiki/Supporting-legacy-platforms#building-armv7-ios--armeabi-v7a-android-with-xcode10) ）

Unfortunately this does not work on my side.

**Comment by mraleph** [comment]
I want to give an update on this: instead of solving a much wider problem (one described in dart-lang/sdk#31709), we have decided to switch to a problem with a much smaller scope: just enable building `gen_snapshot` targeting ARM for X64 host. 

I have started working on this couple of weeks ago and made a good progress, I now have a version where I can build such `gen_snapshot` and most of the tests we have pass in such configuration:

```console
╭─~/s/d/sdk ⟨simarm_x64 ↑4 …1⟩
╰─» tools/test.py -m release -c dartkp -a simarm --gen-snapshot out/ReleaseXSIMARM_X64/gen_snapshot --use-blobs
[30:40 | 100% | + 8685 | -   35]
```

The [CL itself](https://dart-review.googlesource.com/c/sdk/+/100644) is pretty large and hackish so I will have to work on splitting it into pieces next. At this point I am pretty confident that we will complete this work in the next few weeks.

**Comment by PandaGeek1024** [comment]
getting the same issue here:

`Undefined symbols for architecture i386: "_FlutterMethodNotImplemented", referenced from: ___47+[FLTPathProviderPlugin registerWithRegistrar:]_block_invoke in PathProviderPlugin.o "_OBJC_CLASS_$_FlutterMethodChannel", referenced from: objc-class-ref in PathProviderPlugin.o ld: symbol(s) not found for architecture i386 clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by lawonga** [comment]
Same issue here! Don't want to download xcode :(

**Comment by buaashuai** [comment]
> Get the MacOS 10.13 SDK from Xcode 9.4 from [Apple](https://developer.apple.com/download/more/) or [Github](https://github.com/alexey-lysiuk/macos-sdk)， and uncompress the SDK into /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs and name the SDK `MacOSX10.13.sdk` ... This works for me.
> （Refer to [Supporting-legacy-platforms](https://github.com/flutter/flutter/wiki/Supporting-legacy-platforms#building-armv7-ios--armeabi-v7a-android-with-xcode10) ）

i rename the MacOSX10.13.sdk to MacOSX10.14.sdk, solved this problem.

**Comment by kangwang1988** [comment]
On Mac OS 10.15, gen_snapshot with i386 arch will fail.

**Comment by kangwang1988** [comment]
cc @mraleph

**Comment by cbracken** [comment]
@liamappelbe is working on this. 

Liam, can you link to the dart-lang/sdk bug for this that you're working on? I notice this one, which I think is probably a dupe: https://github.com/dart-lang/sdk/issues/36839

**Comment by liamappelbe** [comment]
@cbracken Yep, that's the dart bug

**Comment by AndreaMiotto** [comment]
is there any fix on this? I'm having the same issue on mac os 10.15 beta Catalina

**Comment by jobslong** [comment]
> is there any fix on this? I'm having the same issue on mac os 10.15 beta Catalina

https://github.com/flutter/flutter/issues/33909#issuecomment-508995034

**Comment by mraleph** [comment]
The fix is very close to landing. Most of the necessary pieces are already part of the upstream.

**Comment by Oklahomawhore** [comment]
Greeeeeeeat! work has been a halt since updated to 10.15

**Comment by Oklahomawhore** [comment]
How many hours to landing may I kindly ask?

**Comment by Oklahomawhore** [comment]
`Please`

**Comment by assertme** [comment]
I have the same error  on mac os 10.15 beta Catalina...

**Comment by rabingaire** [comment]
Waiting for the fix :)

**Comment by Oklahomawhore** [comment]
waiting and waiting.... until my head turns bold.....

**Comment by MacLeeIn** [comment]
Waiting for 10.15 bug fixing Downloaded executables cannot execute on host. 
Please let me know.

**Comment by daveleenew** [comment]
Waiting for the fix :)

**Comment by DazChong** [comment]
Catalina, waiting..

**Comment by Hixie** [comment]
(Moving blocker label to umbrella bug https://github.com/flutter/flutter/issues/36290 for triage purposes.)

**Comment by JosepRoo** [comment]
any news?

**Comment by trevburley** [comment]
"By August 1, 2019, all apps that use native code must provide a 64-bit version in order to publish an update."

Glad to see this is getting some attention. Hope we can build on Catalina soon, it was necessary for me to update to start testing my desktop applications and unfortunately don't have a second machine to get these x64 Google Play builds done...stitched myself up a bit there!

**Comment by nohli** [comment]
You could use Codemagic to build and deploy your app ;)

**Comment by knopp** [comment]
There's another option. You can install Mojave in virtual machine and produce the build there.

**Comment by trevburley** [comment]
Thanks @nohli and @knopp - those were going to be my last resort :)

**Comment by liamappelbe** [comment]
Status update: I have a fix working locally (I'm able to build for a 32-bit iPhone 4S on Catalina using Xcode 10). PRs are being reviewed, and the fix should be in the dev channel in a few weeks.

**Comment by zanderso** [comment]
There is a small amount of clean up work remaining for which we'll have other issues filed, but the work for this issue is done.

**Comment by JannieT** [comment]
Has this fix made it into the stable channel (Flutter 1.12) yet? Currently holding our team from upgrading to macOS Catalina

**Comment by zanderso** [comment]
Yes, the changes mentioned here are in 1.12. If you encounter any problems in this area, please file a new issue. Thanks!

**Comment by AlexBacich** [comment]
@dilbert2 , how did you make it working? 

I've downloaded necessary files and put in path you gave. https://take.ms/HFiiC
Then run command flutter version v1.5.4-hotfix.2 
At the end command failed with same error: 

> Downloaded executables cannot execute on host.
>       See https://github.com/flutter/flutter/issues/6207 for more information

Am I missing something?

**Comment by dhyani15** [comment]
gen_snapshot cannot be verified.

When running flutter doctor I am getting the following logs
`[!] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-arm, locale en-IN)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.55.0)
[✓] Connected device (1 available)`

**Comment by AlexZeitler** [comment]
@dhyani15 (How) did you solve this?
