### ISSUE TITLE
Text color of material buttons should animate when disabling/enabling

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#226]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 16:50 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1784_

---

See the top image in [the spec video](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFSTNhRndpWXBwRDA/components-buttons-flatbuttons.webm).

Source: http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 16:52 GMT_

----

I'm thinking the right way to do this is to have an AnimateDefaultTextStyle widget which acts like a DefaultTextStyle widget except that it just animates the DefaultTextStyle value from whatever it inherited before to whatever it inherits now anytime what it inherits changes.

**Comment by zoechi** [comment]
![material_button_animate_text_color_enable_disable](https://user-images.githubusercontent.com/405837/49281717-8ee8fd00-f48d-11e8-9257-255439cd5a9c.gif)

Looks like that's done.
