### ISSUE TITLE
my flutter can't run on Android Deviece

### ISSUE THREAD

**Issue by 15179966403** [flutter/flutter#22608]
* Where:
Finished with error: FormatException: Bad UTF-8 encoding 0xbb (at offset 17)
[flutter_06.log](https://github.com/flutter/flutter/files/2441907/flutter_06.log)

**Comment by zoechi** [comment]
The log file you attached contains

>  Flutter (Channel master, v0.1.8-pre.33, on Microsoft Windows [Version 10.0.17134.285], locale zh-CN)
>     • Flutter version 0.1.8-pre.33 at C:\Users\黄荣聪\flutter
>     • Framework revision da24ad0b33 (**7 months ago**), 2018-03-02 06:23:59 -0800

Which indicates your are using quite an old Flutter version.
If you still see this with a recent Flutter version, please create a new issue.
