### ISSUE TITLE
Add bot for testing Dart VM head against Flutter Engine head

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#2260]
Add bot for testing Dart VM head against Flutter Engine head

**Comment by eseidelGoogle** [comment]
Thanks!  Hopefully this will make Dart rolls less painful.  FYI @abarth @chinmaygarde

**Comment by sethladd** [comment]
Very cool, thanks!

**Comment by johnmccutchan** [comment]
Closing as this has been superseded by https://github.com/dart-lang/sdk/issues/26605
