### ISSUE TITLE
Error "RenderBox was not laid out"

### ISSUE THREAD

**Issue by amit-deligence** [flutter/flutter#22600]
Page is not view when using singlechildscrollview error throwing Another exception was thrown: RenderBox was not laid out: RenderFlex#4863a relayoutBoundary=up12 NEEDS-PAINT even i have used Expanded with listview. but not a bit improvement.

Another exception was thrown: RenderBox was not laid out: RenderFlex#4863a relayoutBoundary=up12 NEEDS-PAINT

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`,
the code (minimal reproduction) that allows to reproduce the problem,
explanation of the steps how to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
