### ISSUE TITLE
FlutterHandshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: self signed certificate

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#22610]
Hi,

I mange to add openssl self sign certificate and start aqueduct server successfully. 
Problem is that I am getting Flutter Mobile app error as: 

HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:363)

Any help on this please?

**Comment by zoechi** [comment]
Did you check 

- https://dart-lang.github.io/server/tls-ssl.html
- https://stackoverflow.com/questions/25388750/dart-https-request-with-ssl-certificate-please

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by NTMS2017** [comment]
Thanks a lot. I installed Nginx on Ubuntu 18.04 which my aqueduct server runs. I am going to get domain and apply to ssl certificate from letsencrypt.org. I will also change my flutter code that calls http. Will try to change to call https. I will use Nginx as reverse proxy and redirect to all request to aqueduct server. I am hoping to get good result. If I do, I will paste the complete solution with small example in here.

**Comment by zoechi** [comment]
I think StackOverflow would be a better place.
They are quite good at SEO and it's much more discoverable there.

**Comment by nasr25** [comment]
> Thanks a lot. I installed Nginx on Ubuntu 18.04 which my aqueduct server runs. I am going to get domain and apply to ssl certificate from letsencrypt.org. I will also change my flutter code that calls http. Will try to change to call https. I will use Nginx as reverse proxy and redirect to all request to aqueduct server. I am hoping to get good result. If I do, I will paste the complete solution with small example in here.

we are waiting

**Comment by esanthosh28** [comment]
> Thanks a lot. I installed Nginx on Ubuntu 18.04 which my aqueduct server runs. I am going to get domain and apply to ssl certificate from letsencrypt.org. I will also change my flutter code that calls http. Will try to change to call https. I will use Nginx as reverse proxy and redirect to all request to aqueduct server. I am hoping to get good result. If I do, I will paste the complete solution with small example in here.

can u please  update the solution...

**Comment by yeszao** [comment]
I caused this error because my mobile time was misplace, it was worked after I adjusted the clock.

**Comment by contactlutforrahman** [comment]
Please write your codes for calling http.
