### ISSUE TITLE
"Unable to resolve dependency" errors when opening Example of new Flutter Plugin project

### ISSUE THREAD

**Issue by admarwick** [flutter/flutter#22614]
I'm seeing errors when opening the Android module of a fresh Flutter Plugin project's example project. Sample error: 
`Unable to resolve dependency for ':app@dynamicProfile/compileClasspath': Could not resolve project :<project>` 

To reproduce, create a new Flutter Plugin project with Kotlin support using the 'New Flutter Project' wizard in Android Studio. To resolve warnings, change the kotlin version from 1.2.30 to 1.2.61 (this version ships with the IDE) in `project/Android/build.gradle` and `project/Example/Android /build.gradle`. Also resolve warnings by changing the gradle version to 3.2.0 in both `build.gradle` files, and if prompted change `example/android/gradle.wrapper/gradle-wrapper.properties` to reference `gradle-4.6`.

After these adjustments suggested by the IDE, check that the example project builds and runs in the emulator from the plugin project, which it does.

Next, select the example/android folder in the IDE and from the context menu select Flutter>Open Android module from Android Studio. The project opens but build terminates with the subject errors.

Flutter doctor:
 ```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.8.2 at /Users/alan/Documents/util/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/alan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by alann-maulana** [comment]
I'm having this issue too. When trying to add `com.google.android.gms:play-services-location:16.0.0` then getting error below :
```
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-location:16.0.0.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-location:16.0.0.
Open File
Show Details


Unable to resolve dependency for ':location@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-location:16.0.0.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-location:16.0.0.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-location:16.0.0.
Open File
Show Details
```

**Comment by ened** [comment]
@admarwick @alann-maulana could you please apply the suggested changes in #22790 and feedback if that resolves the issue for you?

**Comment by alann-maulana** [comment]
@ened mine still error after updating changes in #22790

**Comment by ened** [comment]
@alann-maulana , just reading your error message: `com.google.android.gms:play-services-location:16.0.0`
Did you follow the steps here? https://developers.google.com/android/guides/setup
Also, you may want to add:
```
allprojects {
    repositories {
        google()
    }
}
```

To the build.gradle in the *root* folder of your project. 

#22790 should actually help with the issue reported by @admarwick

**Comment by g123k** [comment]
Your PR @ened seems to solve the problem on my side.
The fix is to upgrade the Gradle wrapper version.

**Comment by daimionsg** [comment]
I am still getting a similar error even after updating all the versions across all the plugins. My errors are 

    Unable to resolve dependency for ':app@dynamicProfile/compileClasspath': Could not resolve project 
    :google_api_availability.
    Open File
    Show Details


    Unable to resolve dependency for ':app@dynamicProfile/compileClasspath': Could not resolve project 
    :permission_handler.
    Open File
    Show Details


     Unable to resolve dependency for ':app@dynamicProfileUnitTest/compileClasspath': Could not 
     resolve project :google_api_availability.
     Open File
     Show Details


    Unable to resolve dependency for ':app@dynamicProfileUnitTest/compileClasspath': Could not 
    resolve project :permission_handler.
    Open File
    Show Details


    Unable to resolve dependency for ':app@profile/compileClasspath': Could not resolve project         
    :google_api_availability.
    Open File
    Show Details


    Unable to resolve dependency for ':app@profile/compileClasspath': Could not resolve project                 
    :permission_handler.
    Open File
    Show Details


    Unable to resolve dependency for ':app@profileUnitTest/compileClasspath': Could not resolve project     
    :google_api_availability.
    Open File
    Show Details


    Unable to resolve dependency for ':app@profileUnitTest/compileClasspath': Could not resolve project     
    :permission_handler.
    Open File
    Show Details


    Unable to resolve dependency for ':app@dynamicRelease/compileClasspath': Could not resolve 
    project :google_api_availability.
    Open File
    Show Details


    Unable to resolve dependency for ':app@dynamicRelease/compileClasspath': Could not resolve 
    project :permission_handler.
    Open File
    Show Details


    Unable to resolve dependency for ':app@dynamicReleaseUnitTest/compileClasspath': Could not 
    resolve project :google_api_availability.
    Open File
    Show Details


    Unable to resolve dependency for ':app@dynamicReleaseUnitTest/compileClasspath': Could not 
    resolve project :permission_handler.
    Open File
    Show Details

My gradles files are as follows:

Android Gradle:

    buildscript {
        ext.kotlin_version = '1.2.71'
        repositories {
            google()
            jcenter()
            maven {
                url "https://maven.google.com"
            }
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:3.2.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'com.google.gms:google-services:4.1.0'
        }
    }
    apply plugin: 'kotlin'

    allprojects {
        repositories {
            google()
            jcenter()
    
        }
    }

    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(':app')
    }
    
    task delete(type: Delete) {
        delete rootProject.buildDir
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    }
    compileKotlin {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
    compileTestKotlin {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }

App Gradle

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }

    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the         
    local.properties file.")
    }

    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        throw new GradleException("versionCode not found. Define flutter.versionCode in the     
    local.properties file.")
    }

    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        throw new GradleException("versionName not found. Define flutter.versionName in the     
    local.properties file.")
    }

    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    
    android {
    
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    
        compileSdkVersion 28
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
        lintOptions {
            disable 'InvalidPackage'
        }
        defaultConfig {
            // TODO: Specify your own unique Application ID         
    (https://developer.android.com/studio/build/application-id.html).
            applicationId "XX.XX.XX.XX"
            minSdkVersion 25
            targetSdkVersion 28
            multiDexEnabled true
            versionCode 18
            versionName "2.02.000"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                // TODO: Add your own signing config for the release build.
                // Signing with the debug keys for now, so `flutter run --release` works.
                signingConfig signingConfigs.debug
            }
        }
        productFlavors {
        }
    }
    
    flutter {
        source '../..'
    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
        implementation 'com.google.android.gms:play-services-ads:17.0.0'
        implementation 'com.google.android.gms:play-services-auth:16.0.1'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
        androidTestImplementation 'com.android.support.test:rules:1.0.2'
    }
    
    apply plugin: 'com.google.gms.google-services'
    com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
    

google_api_availability Gradle

    group 'com.baseflow.googleapiavailability'
    version '1.0-SNAPSHOT'

    buildscript {
        ext.kotlin_version = '1.2.71'
        repositories {
            google()
            jcenter()
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:3.2.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        }
    }
    
    rootProject.allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    apply plugin: 'com.android.library'
    apply plugin: 'kotlin-android'
    
    android {
        compileSdkVersion 27
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
        defaultConfig {
            minSdkVersion 25
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        lintOptions {
            disable 'InvalidPackage'
        }
        productFlavors {
        }
    }
    
    dependencies {
        api 'com.google.android.gms:play-services-location:16.0.0'
        implementation 'com.google.code.gson:gson:2.8.5'
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    }
    

permission_handler Gradle
    
    group 'com.baseflow.permissionhandler'
    version '1.0-SNAPSHOT'
    
    buildscript {
        ext.kotlin_version = '1.2.71'
        repositories {
            google()
            jcenter()
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:3.2.0'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        }
    }
    
    rootProject.allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    apply plugin: 'com.android.library'
    apply plugin: 'kotlin-android'
    
    android {
        compileSdkVersion 27
    
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
        defaultConfig {
            minSdkVersion 17
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        lintOptions {
            disable 'InvalidPackage'
        }
    }
    
    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
        implementation "com.google.code.gson:gson:2.8.5"
        implementation "com.android.support:support-compat:27.1.1"
    }
    

A few other warnings I get are:

android Gradle:

    dependencies {
        compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    }

This has a "Plugin version (1.2.71) is not the same as library version (jdk8-1.2.71)

app Gradle:
    
    androidTestImplementation 'com.android.support.test:rules:1.0.2'

This has a "All com.android.support libraries must use the exact same version specification...."

**Comment by alann-maulana** [comment]
@ened `google()` repo has been added already on my project. The last thing that worked for me was deleting `~/.gradle` folder and redownload all again from scratch, voila.. 👍

**Comment by 5ummit** [comment]
> @ened `google()` repo has been added already on my project. The last thing that worked for me was deleting `~/.gradle` folder and redownload all again from scratch, voila.. 👍

Didn't work for me - https://github.com/flutter/flutter/issues/22902 https://github.com/flutter/flutter/issues/23131

**Comment by g123k** [comment]
@5ummit Try to upgrade your gradle wrapper version by editing the file:
`android/gradle/wrapper/gradle-wrapper.properties`

And change the following line:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`

**Comment by Saraujoc92** [comment]
In my case, this error appeared when updating the build gradle tools.
> classpath 'com.android.tools.build:gradle:3.2.1'

Downgrading to 3.1.4 solved it.
> classpath 'com.android.tools.build:gradle:3.1.4'

**Comment by TahaAli07** [comment]
In my case, this error appeared when updating the build gradle tools.

> classpath 'com.android.tools.build:gradle:3.3.0'

Downgrading to 3.1.4 solved it.

> classpath 'com.android.tools.build:gradle:3.1.4'

**Comment by kinmengcoder53** [comment]
In my case, it was due to bintray being down. What works for me as follow:

1. Edit  <flutter root>/packages/flutter_tools/gradle/flutter.gradle
2. Remove jcenter()
3. Add the following below google()
`maven { url 'https://maven.fabric.io/public' }
      maven { url 'https://jitpack.io' }
      mavenCentral()
      maven { url 'https://maven.fabric.io/public' }
      maven {  url "https://maven.google.com"  }`

You may need to do the same thing to your project's build.gradle.

**Comment by Aidanvii7** [comment]
I'm seeing a similar issue with plugins.

I have a plugin (android only but besides the point) whereby it depends on another local module i.e:
```
implementation project(':rtmp-publisher')
```
This fails with the same error message as described here.

This is making hybrid app development with Flutter very difficult.

**Comment by bobatsar** [comment]
I have the same issue as @Aidanvii7 
Is there any workaround to fix this?

**Comment by bobatsar** [comment]
@Aidanvii7 in my case it was the issue as described [here](https://stackoverflow.com/a/47029361/3607358)
I didn't had the debug buildType set. So adding the following to buildTypes fixed the problem
`
debug{
            matchingFallbacks = ["release"]
        }
`

**Comment by jonahwilliams** [comment]
This issue has quite likely been fixed through a combination of tool updates and documentation. I would recommend that anyone experiencing this file a new bug with complete details, as it is likely something different
