### ISSUE TITLE
Google Sign In for iOS returns token with limited information

### ISSUE THREAD

**Issue by dawidkunicki** [flutter/flutter#22615]
Google Sign works, but it returns a token with limited information for iOS (without firstName, lastName and pictureUrl)
This happens only on the second or further authentications.
No exception gets thrown.
On Android it works perfectly fine and the token contains all the information.

## Logs
```
Flutter run --verbose output:
No exceptions or warnings here.

Flutter analyse output:
Analyzing offhub_flutter...                                      
No issues found! (ran in 2.6s)

Flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.8.7-pre.5, on Mac OS X 10.13.4 17E199, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @dawidkunicki 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you

**Comment by lwasyl** [comment]
@TahaTesser This is an issue due to difference in how Android and iOS Google Sign functionality works in their respective native libraries. I tried to report it to Firebase at some point but there's no channel for that
