### ISSUE TITLE
Add InheritedModel documentation

### ISSUE THREAD

**Issue by josvos** [flutter/flutter#22613]
Add documentation for the recently introduced `InheritedModel` class.

**Comment by josvos** [comment]
I was indeed referring to the missing documentation on https://docs.flutter.io/ 

Just trying to find out the use cases for `InheritedModel` compared to `InheritedWidget`.  The github code indeed seems to include some clarification, thanks.  I had looked at the sample in https://gist.github.com/HansMuller/b947e76c34d941397989eaab537d45ca and that wat a bit confusing at first sight (especially the role of the `aspects`).

**Comment by HansMuller** [comment]
The InheritedModel doc has landed on flutter.io: https://docs.flutter.io/flutter/widgets/InheritedModel-class.html
