### ISSUE TITLE
Flutter and VM behaving differently on data reception

### ISSUE THREAD

**Issue by shamblett** [flutter/flutter#22657]
I have this[ issue](https://github.com/shamblett/mqtt_client/issues/34) raised on one of my packages. Basically its saying when data is received from, in this case an MQTT broker, Dart on the VM is OK no matter what the data size, but flutter seems to have a problem in that it raises exceptions when processing the data if it gets to large.

Could the flutter runtime be causing this?

**Comment by zoechi** [comment]
https://github.com/dart-lang/sdk/issues/34591 was reopened, so closing here.
