### ISSUE TITLE
Flutter app with cloud_firestore does not build (Xcode 10, ios 12, Mojave)

### ISSUE THREAD

**Issue by krishnabhargav** [flutter/flutter#22652]
I created a simple flutter app and then added cloud_firestore. It seems like a common issue and I tried everything suggested across all the issues. No luck!

Steps I followed multiple times to reproduce the issue:

- Create a new flutter app. Ensure `flutter run` launches in ios simulator. This works good.
- Add `cloud_firestore: ^0.8.1` to the pubspec.yaml
- If you try to run, you will encounter the issue reported in #20685 .
- Apply the legacy build fix as described in the issue.
- Attempt a `flutter run` again displays 18 warnings and a linker error. The warnings are similar to what was listed in #21611
- Repeating a `flutter run` shows no warnings this time but still fails to run.
```
Launching lib/main.dart on iPhone XS Max in debug mode...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: file too small (length=0) file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks//SystemConfigu$
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
- Following the advice in #21611, did a `pod update Firebase` from the ios directory.
- Tried to do a `flutter run` again. Same output as the above.

Flutter Doctor output
```
krishnas-imac:hello buddi$ flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.8.2 at /Users/buddi/development/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/buddi/development/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/buddi/development/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • iPhone XS Max • A7C6094A-B70B-4AEA-ABED-F6A648F2E3B5 • ios • iOS 12.0 (simulator)
```

**Comment by poudja** [comment]
Try to update your firebase SDK.
Open a terminal attached to your project folder.
Then write "cd ios".
Finally, write "pod update Firebase".
It has worked for me.

**Comment by krishnabhargav** [comment]
I believe I done that already and didn't work. I will try again and reply back in a bit.

**Comment by krishnabhargav** [comment]
**If Flutter + Firebase doesn't work on XCode 10, use an older version of XCode (9.4.1 worked for me)**

Turns out it is not an issue with either firebase/firestore/flutter or Xcode/Mojave for that matter. 
The latest flutter + firebase setup does not to be compatible with XCode 10. I installed Xcode 9.4.1 and switched command line tools to be primary on that version. Then everything is working as expected.

With XCode 10, no matter how many workarounds I applied, they all did not work for me.

**Comment by JosephDunivan** [comment]
I have a problem where adding cloud firestore makes gRPC load over 300 files for the dependency everytime I go to build. Is this related?

**Comment by krishnabhargav** [comment]
Not sure I understand your issue.

Anyway, this is no longer an issue with recent flutter builds. Not entirely sure when it got resolved. But XCode 10 works with flutter on Mojave just fine.

**Comment by kroikie** [comment]
@krishnabhargav

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/628. Any further collaboration will be done there.
