### ISSUE TITLE
PerformanceOverlay: It's not clear which time series shows what

### ISSUE THREAD

**Issue by letsar** [flutter/flutter#22663]
The documentation says:

> The overlay show two time series. The first shows how much time was required on this thread to produce each frame. The second shows how much time was required on the GPU thread to produce each frame. 

The **first** means the top or the bottom one?

On flutter.io website we have this image (https://flutter.io/ui-performance/):
<img width="175" alt="performance-overlay-green" src="https://user-images.githubusercontent.com/9378033/46459437-3a8d0e00-c7b9-11e8-9089-b83c6c267674.png">

The top graph is labelled **GPU**, an and the bottom one **UI**. 
To me, first means top and in that case it looks like it's the opposite. Did I misunderstood something?

**Comment by GaryQian** [comment]
Yes, the bottom one should be the UI thread on CPU. The top is GPU rasterization time.

We should fix that.

**Comment by GaryQian** [comment]
Merged in. Also updated in other places. Thanks for your contribution! We appreciate it!
