### ISSUE TITLE
print() statements in Flutter are truncated in flutter run output

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#22665]
Originally raised at https://github.com/Dart-Code/Dart-Code/issues/1223 by @rajeshzmoke. If you `print()` a long string in Flutter, it gets truncated with `<…>` in the `flutter run` output:

```dart
void main() {
  print('a' * 100 + 'b' * 100 + 'c' * 100 + 'd' * 100 + 'e' * 100 + 'f' * 100 +
      'g' * 100 + 'h' * 100 + 'i' * 100 + 'j' * 100 + 'k' * 100);
  runApp(const GalleryApp());
}
```

<img width="1143" alt="screen shot 2018-10-04 at 10 55 44 am" src="https://user-images.githubusercontent.com/1078012/46466777-12ef7300-c7c4-11e8-8741-2f95e0e96a56.png">

I'm using the iOS Simulator - it's possible this is a limitation of how we're reading the logs from the device, I'm not sure.

**Comment by iozozturk** [comment]
This took my hours to debug, because I was relying on logs and copying access token from there. I was using new experimental log window in Android Studio flutter plugin. No <..> truncation indication there sadly, so didn't realize truncation going on.

**Comment by trevorwang** [comment]
I have met the same issue.  I am trying to print access_token from oauth, but it's trunked.

```
eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFDNXVuYTBFVUZnVElGOEVsYXh0V2pUNk85Wmd4ZkE5dEo0MjdvWkdmc3hWUkJhMXNnNlNGOGwtVktMTGlxVHRYQTVGX0VpQWdBZkwzRzlybFl0c05IQTBiSUR1ZERESk43bVlNU284cHU0TFNBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoibmJDd1cxMXczWGtCLXhVYVh3S1JTTGpNSEdRIiwia2lkIjoibmJDd1cxMXczWGtCLXhVYVh3S1JTTGpNSEdRIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzU3YzdmNGItNjQyNy00M2Y4LWI3Y2EtZTQ5NmQ1OTVjZjJhLyIsImlhdCI6MTU0NTM1NjcwOSwibmJmIjoxNTQ1MzU2NzA5LCJleHAiOjE1NDUzNjA2MDksImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiI0MlJnWUhDZDA5c3RrYUN4ZGZmN2xld2JBNlBxRkpzSzN4M1paN2ZzbkJESDhjWW5KajhCIiwiYW1yIjpbInB3ZCJdLCJhcHBfZGlzcGxheW5hbWUiOiJBcHBDZW50ZXIiLCJhcHBpZCI6IjIxOGZlZmYyLWI5ZWItNGUxYi04Y2U5LTc0NzcyZGZhYzQwYiIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiVHJldm9yIiwiZ2l2ZW5fbmFtZSI6IldhbmciLCJpcGFkZHIiOiIyMDIuNjQuNTMuOTAiLCJuYW1lIjoiVHJldm9yIFdhbmciLCJvaWQiOiI5ZmMwMWE5MS05YzQyLTQ2OTEtOTNlMy1mMDNhZTc1MTE5NTMiLCJwbGF0ZiI6IjIiLCJwdWlkIjoiMTAwM0JGRkRBQkZCNzhGQiIsInNj<…>
```

**Comment by SachinGanesh** [comment]
You can use **debugPrint** instead of **print** to log long text
https://flutter.io/debugging/#print-and-debugprint-with-flutter-logs
https://stackoverflow.com/a/49156942/8059845

**Comment by trevorwang** [comment]
@SachinGanesh  I used debugPrint also, but it doesn't work.

**Comment by aaronfg** [comment]
Having this exact issue. I've resorted to a janky overlayed TextField that I can toggle on that mirrors the log output and is text-selectable. 

Really annoying.

**Comment by andrewackerman** [comment]
Can confirm that both `print` and `debugPrint` truncate console output when testing on an iOS device.

**Comment by Suraj-Tiwari** [comment]
@trevorwang 
This could be the dirtiest workaround in the history of mankind but it works.
what i did is first 
` print(auth.idToken.toString());`
in this way you'll get truncated string. copy it and write somewhere.

then replace first statement with this 
`print(auth.idToken.replaceAll(previousTruncatedString, "")toString());` 
with this you'll get rest of the string

**Comment by trevorwang** [comment]
@Suraj-Tiwari   Thanks. will have a try.

**Comment by DanTup** [comment]
> This could be the dirtiest workaround in the history of mankind but it works.

A slightly nicer workaround might be to create your own `print` that splits into smaller chunks, then you don't need to modify the code for each long string. Eg.:

```dart
void printWrapped(String text) {
  final pattern = new RegExp('.{1,800}'); // 800 is the size of each chunk
  pattern.allMatches(text).forEach((match) => print(match.group(0)));
}
```

(note: I haven't battle-tested that function but it worked in a quick test..).

**Comment by RobertoManfreda** [comment]
I had a veri long json string to be printed out but in the console i saw a single string truncated so i used this method (if can be helpful for someone):
```
JsonEncoder encoder = new JsonEncoder.withIndent('  ');
String prettyprint = encoder.convert(yourJsonString);
debugPrint(prettyprint);
```

**Comment by namiwang** [comment]
Confirmed here.

I printed and copied a JWT from the console and wasted a few hours in debugging.

At least a trailing ellipsis "…" would be nice.

**Comment by markathomas** [comment]
Same issue here.  I have noticed a 1024 character limit in the console.

**Comment by ngprnk** [comment]
any fixes for this issue ?

**Comment by Suraj-Tiwari** [comment]
workarounds but no proper fix.

**Comment by ineelp** [comment]
I checked with full access token length and after printing it. There is a huge difference in size.

**Comment by chenenyu** [comment]
plz fix this issue.

**Comment by andrewackerman** [comment]
So as it turns out, this isn't a bug in Flutter. It seems like this is a hard limitation set by the mobile platforms themselves. For iOS, there doesn't seem to be any kind of configuration for it but it does have a (very) dirty fix:

https://stackoverflow.com/questions/39584707/nslog-on-devices-in-ios-10-xcode-8-seems-to-truncate-why

For Android, there doesn't seem to be any fix. Only the workaround of the kind like DanTup mentioned:

https://stackoverflow.com/questions/8888654/android-set-max-length-of-logcat-messages

**Comment by jesobremonte** [comment]
There is a second optional parameter in debugPrint you can use to wrap the log text:
```dart
debugPrint(someSuperLongString, wrapWidth: 1024);
```

**Comment by Akshar-Patel** [comment]
> > This could be the dirtiest workaround in the history of mankind but it works.
> 
> A slightly nicer workaround might be to create your own `print` that splits into smaller chunks, then you don't need to modify the code for each long string. Eg.:
> 
> ```dart
> void printWrapped(String text) {
>   final pattern = new RegExp('.{1,800}'); // 800 is the size of each chunk
>   pattern.allMatches(text).forEach((match) => print(match.group(0)));
> }
> ```
> 
> (note: I haven't battle-tested that function but it worked in a quick test..).

This is the only workaround that can work easily right now.

**Comment by lionnner** [comment]
when to fix it? so long time...

**Comment by Furtim** [comment]
> There is a second optional parameter in debugPrint you can use to wrap the log text:
> 
> ```dart
> debugPrint(someSuperLongString, wrapWidth: 1024);
> ```

This works perfectly. I set it to 1000 rather than 1024 to give some headroom as I wasn't clear whether the 'flutter:' prefix counted in the total, but it splits the message into multiple lines and everything is shown.

Spot on!

**Comment by andrewackerman** [comment]
Can this issue be locked? It's become an endless cycle of people either requesting an update or posting the same fix/workaround.

**Comment by MuhammadAliKhan1** [comment]
Any updates on print()? Having the same problem.

**Comment by rtviwe** [comment]
VSCode prints only first 1000 symbols. There is my solution:
```
void log(String text) {
  if (text.length <= 1000) {
    debugPrint(text);
  } else {
    final count = text.length ~/ 1000;
    for (int i = 0; i <= count; i++) {
      log(text.substring(i * 1000, min((i + 1) * 1000, text.length)));
    }
  }
}
```

**Comment by badelectron77** [comment]
I'm heading the same issue in Android Studio. Finally wrote a function for logging which splits the string into pieces:
```
void logLongString(String s) {
    if (s == null || s.length <= 0) return;
    const int n = 1000;
    int startIndex = 0;
    int endIndex = n;
    while (startIndex < s.length) {
      if (endIndex > s.length) endIndex = s.length;
      print(s.substring(startIndex, endIndex));
      startIndex += n;
      endIndex = startIndex + n;
    }
}
```

**Comment by Aqua-Ye** [comment]
you can see the full log output in the DevTools https://flutter.dev/docs/testing/debugging

**Comment by zanderso** [comment]
Hi folks, please see the solution here: https://github.com/flutter/flutter/issues/22665#issuecomment-506687219
