### ISSUE TITLE
Create a template for Travis for building flutter apks/ipas

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2267]
The game would want to use such:
https://github.com/flutter/game/issues/56

I'm not sure if Travis has literal templates, but the Game's repo could serve as one for other projects.

**Comment by sethladd** [comment]
Travis has the concept of community-supported templates. See https://docs.travis-ci.com/user/languages/community-supported-languages/

**Comment by eseidelGoogle** [comment]
@abarth said he'd like to try.

**Comment by abarth** [comment]
@chinmaygarde mentioned in the standup that he was working on this.  Feel free to kick it back to me if I misunderstood.

**Comment by chinmaygarde** [comment]
Yeah, I am working on this right now.

**Comment by sethladd** [comment]
It would be cool if the template also made it easy to run the driver and tests on Travis.

**Comment by Hixie** [comment]
We don't think this is something we're going to do ourselves. We encourage the community to provide such templates.
