### ISSUE TITLE
In iOS, it's impossible to show the TextSelectionToolbar without a selection within a TextFields

### ISSUE THREAD

**Issue by Xavjer** [flutter/flutter#22674]
Currently, you can only paste text on iOS devices at the end of the line.

How it should work:
- Pressing anywhere within the textfield should put the marker at that position (Already in place)
- Pressing the same position twice fast selects the word (Not working)
- Pressing the same position twice slow will show the context menu at this position (Not working)
- Press and keep pressing while moving will move the marker, letting go will show the context menu (Not working, also the loupe is missing, see #9507 )

I will not go into the details for 3D-Touch as they are not that relevant (If the above things works)

In #11148 , the Platform specific text handle was implemented, but there are still a few other related issues opened.
#9507, #11274, #11254, #22576

## Steps to Reproduce

1. Copy any text into the clipboard
2. Go to a text field and enter some text
3. Long-press anywhere within the textfield, it will always start with a selection instead of just showing the context menu (Copy/Select/Select All/Paste) and will always contain at least one character (Which is correct within iOS that a selection has at least 1 Character, but the selection itself is wrong)

Just for clarification: (Context Menu without selected Text has different behaviour than the Context Menu with selected Text)
Copy => Then copies the whole textField
Select => Will select the nearest word
Select All => Selects the whole text
Paste => Pastes the clipboard at the current position

```

Flutter (Channel master, v0.9.7-pre.27, on Mac OS X 10.13.6 17G65, locale en-CH)
    • Flutter version 0.9.7-pre.27 at /Users/xxx/Documents/Projects/flutter
    • Framework revision 2985b3ae93 (3 hours ago), 2018-10-04 14:54:23 +0200
    • Engine revision 74662ab695
    • Dart version 2.1.0-dev.6.0.flutter-d2c5a24fd9

```

**Comment by goderbauer** [comment]
> Pressing anywhere within the textfield should put the marker at that position (Already in place)
> Pressing the same position twice fast selects the word (Not working)
> Pressing the same position twice slow will show the context menu at this position (Not working)

These three are working for me on the current master.

> Press and keep pressing while moving will move the marker, letting go will show the context menu (Not working, also the loupe is missing, see #9507 )

This one is covered by https://github.com/flutter/flutter/issues/20693 and https://github.com/flutter/flutter/issues/9507.

I am closing this for now. Feel free to add additional comments to the existing bugs or open new issues for individual bugs. Thanks!
