### ISSUE TITLE
Trouble with Firebase OnValue listener in Flutter... Listener fails only in iOS release mode, but works fine in debug mode. 

### ISSUE THREAD

**Issue by takaoandrew** [flutter/flutter#22692]
THE ISSUES:
When I leave the app in debug mode (flutter run), my onValue listener will still be listening. I can change a value in firebase, and see log statements in my flutter console. However, when I run it in release mode, (flutter run --release, or through TestFlight, or through the app store), the listener dies when I leave the app. I am trying to understand what differences there are between the debug and release builds in iOS, and hopefully find a workaround to get the firebase database listener to continue listening even though the app is not in the foreground.

## Steps to Reproduce

Put the following in your main dart file. Observe as users are printed when you manually change values in your database. Now leave the app. 

Now try changing values in firebase console again. 

If you ran in debug mode (flutter run) -> You will still see the messages being printed.
If you ran in release mode (flutter run --release OR testflight OR app store) -> You will no longer see messages being printed. However, they will be printed when you go back into the app.

What is going on??

```dart
  void listenToFirebase() {
    FirebaseDatabase.instance
        .reference()
        .child(
        "users")
        .onValue
        .listen((Event user) {
          print("user = " + user.snapshot.value.toString());
    }).onData((Event event) {
      print("Error = $event");
    });
  }

  @override
  void initState() {
    listenToFirebase();
    super.initState();
  }
```

## Logs
The issue here is a lack of log statements-

``` 
No issues found! (ran in 3.6s)
```

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.5.1 at /Users/andrewtakao/Desktop/Coding/flutter/flutter
    • Framework revision c7ea3ca377 (4 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/andrewtakao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Andrew’s iPhone • ************************** • ios • iOS 11.4.1

• No issues found!
```

**Comment by zoechi** [comment]
Your Android version is very old. Please check with a recent version.

**Comment by takaoandrew** [comment]
Would this affect the iOS performance in any way, though?

**Comment by zoechi** [comment]
What do you mean with "this"?

**Comment by takaoandrew** [comment]
Since you said my Android version is very old... I was wondering if you were telling me that 'this' (an old android version) might be the cause of the problem, even though I am experiencing the issue in iOS?

**Comment by zoechi** [comment]
Sorry, my bad. I meant old Flutter version 

>  • Framework revision c7ea3ca377 (4 months ago), 2018-05-29 21:07:33 +0200

**Comment by takaoandrew** [comment]
I see. Well I upgraded my version, and am still running into the same issue.

[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.8.2 at /Users/andrewtakao/Desktop/Coding/flutter/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/andrewtakao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Andrew’s iPhone • a24d32777c81c60314096b0338ed10c523b7dfa8 • ios • iOS 11.4.1

**Comment by zoechi** [comment]
Are you still seeing this?
It might be caused by conflicts with other plugins.
Can you please post the `pubspec.yaml`?

**Comment by randikap** [comment]
The same issue happening on Android 8.1 Go.

**Comment by kroikie** [comment]
@takaoandrew

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/627. Any further collaboration will be done there.
