### ISSUE TITLE
Implement the full set of Floating Action Button features in the Material spec

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#227]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 16:59 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1785_

---

http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button
- [x] It comes in two sizes, regular and mini.
- [x] It's always a hero.
- [x] It heroates by growing and spinning in, and shrinking and spinning out.
- [x] It heroates even when switching tabs, by disappearing then reappearing in the new location.
- [x] It can transform into a toolbar.
- [x] It can transform into a popup menu.
- [x] It can fling out 2-6 extra actions.
- [x] It can morph into a part of an application's structure (going down a z-level and merging with material already there, of the same colour, potentially morphing the existing text to make room)
- [x] It can transform into a new page, though that page's exit animation is a slide out, not morphing back to the fab.
- [ ] it can be disabled

**Comment by rrousselGit** [comment]
> It comes in two sizes, regular and mini.

In one of the video example, there's a third size which is bigger than the both regular and mini :

https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B6Okdz75tqQsWm9PdVplYzZvNTg/components-buttons-fab-behavior-03-xhdpi-001.webm


![image](https://user-images.githubusercontent.com/20165741/39303681-60d61cfe-4957-11e8-82b5-f5cd11b6c0d6.png)

**Comment by rrousselGit** [comment]
@Hixie  I think the "morph" related features should be extracted into another issue. As they are not specific to floating button. 


For example, Floating Button's morph is based on the specs [here](https://material.io/guidelines/motion/transforming-material.html#transforming-material-radial-transformation)

**Comment by JulianBissekkou** [comment]
Any updates on this?

**Comment by Levi-Lesches** [comment]
> It can fling out 2-6 extra actions.

There is a package for this now: [`flutter_speed_dial`](https://pub.dev/packages/flutter_speed_dial), and judging by the 97% popularity score, it seems to be used often. Maybe it can be merged into the default FAB?

> It can be disabled

IMO this one's important. Currently, the docs say that we should _avoid_ disabling the FAB, and if we do, we should change the color by ourselves, which can get messy with Theme-level and Widget-level color overrides. Also, in my experience, when changing the color the FAB still has its elevation (or some other property) such that the disabled color is not a "flat" grey, but rather a semi-transparent black.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/53502 covers the last item here, the rest is possible with packages like the animations package or built-in behaviours.
