### ISSUE TITLE
SilverAppBar interfering with keyboard's ability to move inputs into view.

### ISSUE THREAD

**Issue by kevincherryholme** [flutter/flutter#22703]
Hi everyone,

I'm dealing with what I think is odd behavior.

Normally, when you use a `TextFormField` in your app and you focus it, the keyboard will move the input above the keyboard if it needs to.

When I use a `TextFormField` with a keyboard type of `TextInputType.number` or `TextInputType.numberWithOptions()` in a `SilverAppBar`, the keyboard does not push the `TextFormField` above itself when the keyboard is blocking the `TextFormField`.

If I use any other type of keyboard, like `TextInputType.text`, the keyboard successfully pushes the input above itself.

The build method of my page.
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              actions: <Widget>[
                new IconButton(
                    icon: new Icon(Icons.save),
                    onPressed: () {
                      _saveForm(context);
                    })
              ],
              expandedHeight: 200.0,
              floating: false,
              pinned: true,
              flexibleSpace: FlexibleSpaceBar(
                  title: Text("Test Title"),
                  background: Container(
                    color: Color.fromRGBO(45, 45, 45, 1.0),
                  )),
            ),
          ];
        },
        body: _buildForm(),
      ),
    );
  }
```
The form being built.
```dart
Widget _buildForm() {
    return GestureDetector(
        onTap: () {
          FocusScope.of(context).requestFocus(FocusNode());
        },
        child: Container(
          child: Form(
            key: _formKey,
            child: ListView(
              children: <Widget>[
                Container(
                  height: 600.0,
                ),
                _buildExerciseTHRTFF(),
              ],
            ),
          ),
        ));
  }
```

The TextFormField being built.
```dart
Widget _buildExerciseTHRTFF() {
    return Container(
        margin: EdgeInsets.symmetric(horizontal: 16.0),
        child: TextFormField(
          keyboardType: TextInputType.numberWithOptions(signed: false, decimal: false),
          decoration: InputDecoration(
              labelText: "Target Heart Rate", labelStyle: _labelTextStyle),
        ));
  }
```

Now if you scroll to the very bottom of this page, you will see the `TextFormField` 'Target Heart Rate'. When you tap it to focus it, the keyboard slides up and blocks it. The keyboard isn't pushing the TextFormField up. It does if you change the TextInputType to text.

All help is appreciated! :)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by cherryholme7** [comment]
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-CA)
    • Flutter version 0.8.2 at C:\src\flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\KevinCherryholme\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by zoechi** [comment]
Is this still an issue?
Can you please make the reproduction a complete runnable example (incl `main() {...}`)
