### ISSUE TITLE
examples/stocks should be moved to dev/

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#22718]
The application example located in `examples/stocks` is outdated, and should be removed. Alternatively, if still used for internal test purposes, it should be moved to `dev/`

**Comment by mit-mit** [comment]
cc @gspencergoog can you help with this? I had a previous attempt in https://github.com/flutter/flutter/pull/22422, but it now conflicts with your template changes

**Comment by Hixie** [comment]
Removing milestone since nobody is assigned.

**Comment by Hixie** [comment]
cc @kf6gpe who was looking at this

**Comment by kf6gpe** [comment]
Thanks. I hadn't dove into specific sub-examples, but that would be next on my proposal. I'll have a look.

**Comment by mit-mit** [comment]
Thanks @kf6gpe, you should be able to base this on https://github.com/flutter/flutter/pull/22422/files (which I had to revert after we changed the default templates)

**Comment by kf6gpe** [comment]
I've actually never gotten to this. I know that @RedBrogdon has spent some time on our samples. Any thoughts here?

**Comment by gspencergoog** [comment]
I can move it to dev if you want.  We do use it for some benchmarks and tests.

**Comment by gspencergoog** [comment]
Is the gallery similarly deprecated?  We seem to do a lot more with that, so it would be harder to move, but it does seem odd to have two versions of the gallery.

**Comment by CaseyHillers** [comment]
Closing as PR https://github.com/flutter/flutter/pull/49559 has landed.
