### ISSUE TITLE
Flutter stream builder always received data when state changed.

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#22713]
I think it is a stream bug or something (at least it's not work as user expected). 
I have a simple page, with a stream builder like this:

```dart
@override
Widget build(BuildContext context) {
  return new CupertinoPageScaffold(
    key: _scaffoldKey,
    navigationBar: CupertinoNavigationBar(

//            ),
        ),
    child: new StreamBuilder(
      stream: globalWsStream,
      builder: (context, snapshot) {
        // from snapshot we can get new data
        // add to globalData and start animation
        switch (snapshot.connectionState) {
          case ConnectionState.none:
            return new Text('none');
          case ConnectionState.waiting:
            return new Text('等待');
          default:
            if (snapshot.hasError) {
            } else if (snapshot.hasData) {
              if (snapshot.hasData) {
                print('--- why this called many times when state changed.');
                _solveReceivedMessage(snapshot.data);
                return new GestureDetector(
                    onTap: () {
                      print("点击了");
                      _hideKeyboard('');
                    },
                    child: new Stack(
                      children: <Widget>[
                        new Container(
                          padding: new EdgeInsets.all(0.0),
                          child: globalAppSettings.isBlurBk
                              ? new BackdropFilter(
                                  filter: new ImageFilter.blur(
                                      sigmaX: 5.0, sigmaY: 5.0),
                                  child: new Container(
                                    decoration: new BoxDecoration(
                                        color: Colors.white.withOpacity(0.0)),
                                  ),
                                )
                              : null,
                          decoration: new BoxDecoration(
                              image: new DecorationImage(
                                  // image: _getBkImage(),
                                  image: !_hasCustomBk
                                      // ? new AssetImage("assets/images/chat_bk_5.jpg")
                                      ? new AssetImage(
                                          'assets/images/chat_bk_6.jpg')
                                      : new FileImage(_chatBkFile),
                                  fit: BoxFit.cover)),
                        ),
                        new Container(
                          padding: new EdgeInsets.all(0.0),
                          child: new Container(child: _buildMsgList()),
                        ),
                        new Column(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: <Widget>[
                            new Container(
                                // color: Colors.white,
                                padding: new EdgeInsets.only(
                                    top: 15.0,
                                    bottom: 15.0,
                                    left: 5.0,
                                    right: 5.0),
                                child: _buildComposer2())
                          ],
                        ),
                      ],
                    ));
              } else {
                print('Chat 被锁住了不会进行任何操作');
              }
            }
        }
      },
    ),
  );
}
```

the child is a stream builder which listen to a globalStream which is as global variable and receive data from websockets. the logic for receive data is not in current page, so I must using a stream or something to get the data callback. But question is **the stream can got data, but everytime state changes like input method popup or type something or click something, the previous data still received**. I dont want that, I want a snapshot data can be receive only once. What should I do correctly anyway. Sorry for me not post in stackoverflow, but this maybe a bug.

**Comment by zoechi** [comment]
When `StreamBuilder` is rebuilt, it subscribes again and receives a value if the stream emits one after subscription.
If you don't want that, you need to create the stream so that it doesn't emit a value or move the StreamBuilder higher up so it doesn't get rebuilt when `setState()` is called for this widget.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jinfagang** [comment]
@zoechi What do you mean `create the stream builder`? the stream builder I created and its a custom stream, how to exactly avoid repeat construct the stream when setState called?

**Comment by jinfagang** [comment]
@zoechi Thanks for reply. Then how should I avoid that? As the stream used for update UI, it must write inside build, otherwise how to write the code?

**Comment by zoechi** [comment]
I don't think I can help you here. You need to align your stream to behave like your stream consumer `StreamBuilder` needs it to update the view when you want.

**Comment by Magicskys** [comment]
I also encountered the same problem, how do you solve it?

**Comment by jinfagang** [comment]
@Magicskys I didn't solve it...................... it's still a problem.............. what do u got?>

**Comment by Magicskys** [comment]
@jinfagang Maybe you can try stream listen, this is a similar link.
https://stackoverflow.com/questions/50482557/flutter-how-to-make-websocket-stream-broadcast-to-many-other-pages

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Magicskys** [comment]
@jinfagang I tested it, it is a solution.
`@override`
`void initState() {`
`// TODO: implement initState`
`      super.initState();`
`      widget.channel.stream.listen((onData){`
`        print(onData);`
`        ChatMessage message=new ChatMessage(`
`          text: onData,imgurl:null,flag: false `
`        );`
`        setState(() {`
`          _messages.insert(0, message);`
`        });`
`      });`
`    }`

**Comment by SPK-RPI** [comment]
I am also facing the same issue...
I have a StreamBuilder with a stream attached to it. I have a progress bar which starts and wait for a particular task to be completed and change the UI using the setState(){}. Whenever the progress starts there is a flicker or a reload of all the widgets and this forces some of the images to reload.
