### ISSUE TITLE
examples/catalog should be deprecated

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#22719]
The application example located in `examples/catalog` is not a good customer demo, and should be removed. Alternatively, if still used for internal purposes, it should be moved to `dev/`

**Comment by mit-mit** [comment]
cc @gspencergoog can you help with this?

**Comment by Hixie** [comment]
Removing milestone since nobody is assigned currently.

**Comment by Hixie** [comment]
cc @kf6gpe who was looking at this

**Comment by kf6gpe** [comment]
Thanks --- as with the other issue in examples, I'll have a look!

**Comment by kf6gpe** [comment]
I've actually never gotten to this. I know that @RedBrogdon has spent some time on our samples. Any thoughts here?

**Comment by goderbauer** [comment]
Closing this as `examples/catalog` no longer exists.
