### ISSUE TITLE
[firebase_auth] codeAutoRetrievalTimeout callback never called

### ISSUE THREAD

**Issue by t-fi** [flutter/flutter#22725]
Using the [flutterfire](https://github.com/flutter/plugins/blob/master/FlutterFire.md) [firebase_auth plugin](https://pub.dartlang.org/packages/firebase_auth) and its [example project](https://github.com/flutter/plugins/tree/master/packages/firebase_auth/example) I stumble upon the following issue:

The [callback for auto retrieval timeout](https://github.com/flutter/plugins/blob/e920cf709122505c981377e9a323dd7a997214e0/packages/firebase_auth/example/lib/main.dart#L112) is never called. It should be called after the duration specified in the [`verifyPhoneNumber(...)` call](https://github.com/flutter/plugins/blob/e920cf709122505c981377e9a323dd7a997214e0/packages/firebase_auth/example/lib/main.dart#L120).

I assume firebase is set up correctly for my app, as auto authentication works fine when using a real number. Using a second device to receive a verification code however is not straight forward. In principle it would be possible to show a "please insert verification code" - text field after the "code sent" callback. But this is more a hacky workaround and completely ignores the timeout feature.

It would be nice to only show the verification code text field after the auto verification timed out. This is currently not possible.

**Comment by kroikie** [comment]
@t-fi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/625. Any further collaboration will be done there.
