### ISSUE TITLE
collection(x).document(id).collection(y).getDocuments() always returns 0 documents

### ISSUE THREAD

**Issue by Marcelh1983** [flutter/flutter#22731]
I have collection that contains subjects. 
A subject contains a collection of posts.

`await collection.document(this.id).collection('posts').document('explanation')`

Returns Instance of 'DocumentSnapshot'

While
`await collection.document(this.id).collection('posts').getDocuments() `

always returns 0 documents`

`collection.document(this.id).collection('posts').snapshots` does not work either

--- Flutter doctor ---

[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.286], locale nl-NL)
    • Flutter version 0.8.2 at C:\src\flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\marcelh\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\marcelh\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.27.2)
    • VS Code at C:\Users\marcelh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by 5ummit** [comment]
Hi there, can you please send a `flutter doctor -v` `flutter analyze` and show a bit more of the code?

**Comment by Marcelh1983** [comment]
sorry had a typo in the collection name
