### ISSUE TITLE
Nullability is a breaking change

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#22737]
https://github.com/flutter/engine/pull/6393 broke our client's tests. According to the rolling process, we should notify our clients from  https://github.com/flutter/flutter/wiki/Changelog

**Comment by liyuqian** [comment]
@matthew-carroll

**Comment by matthew-carroll** [comment]
@mehmetf what do you think is the appropriate thing to do here?  Do we need to roll back the nullability annotations?  Or should we just update the broken G3 tests?

**Comment by liyuqian** [comment]
The Google 3 tests have already been fixed. I wonder if we shall out the
information in our change log

**Comment by matthew-carroll** [comment]
I'm not sure what the right action is here so I'll assign to @mehmetf and @DaveShuckerow and they can grab me if I need to take action to fix this.

**Comment by DaveShuckerow** [comment]
If we can fix to keep the tree stable without having to make additional upstream changes, then we can close this issue.

AFAIK, updating the changelog is the responsibility of the roller as part of landing the change in g3.

**Comment by liyuqian** [comment]
Fine. I'll close this issue and just add the title of that pull request to the Changelog. If you think that the Changelog should have a better description, please directly change there.

**Comment by liyuqian** [comment]
cl/215915813

**Comment by nichtverstehen** [comment]
Thank you! That test breaking is, perhaps, WAI: that team is explicitly enabling testing with the nullability checker. In any case, apologies for making the rollup harder for you.

**Comment by liyuqian** [comment]
That's Ok. This is very small and easy to fix compared to many other bigger breaking changes :smile:
