### ISSUE TITLE
Flutter Project Directory

### ISSUE THREAD

**Issue by bipin-adh** [flutter/flutter#22758]
/home/bpn8adh/AndroidStudioProjects/android-architecture-todo-mvp/flutter_app
This is the default project location of a new project , flutter_app being the project name. 
Even though i changed the location to a new one, the application files moves this very same default directory.

Note: This problem arises when i create a new flutter project from android studio itself. It works fine if i use terminal to create a new project . 

i.e.  flutter create test_app worked fine . I was able to create a project in my desired location.

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2674](https://github.com/flutter/flutter-intellij/issues/2674) via [**ZenHub**](https://www.zenhub.com/)
