### ISSUE TITLE
Dark Material Theme: OutlineButton is flickering when pressed, showing black opaque rectangle

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#22755]
Flutter version: Latest master

The `OutlineButton` is displaying a black rectangle shortly after being pressed, and flickers on release.

When I set a button `color`, the black rectangle no longer appears, instead the opaque version of the color is used as a background while the button is pressed. Transparency values are ignored. It all seems broken.

Other buttons like `FlatButton` do not show the same behavior.

![ezgif-3-af8f818f2ae8](https://user-images.githubusercontent.com/22688477/46565913-fb280400-c915-11e8-8639-c6a03ab866d5.gif)

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Stroke Button Test',
      theme: ThemeData.dark(),
      home: new HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Outline Button Test')),
      body: Center(
        child: OutlineButton(
          onPressed: () {},
          child: Text('Do something'),
        ),
      ),
    );
  }
}
```

**Comment by jonahwilliams** [comment]
cc @HansMuller

**Comment by sir-boformer** [comment]
I created PR #22781 to fix this.

**Comment by Borduni** [comment]
Still not fixed

**Comment by KajetanSpionek** [comment]
I've got same issue. Hope to see fix soon.
