### ISSUE TITLE
One isolate per multiple engine instances

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#22750]
1. Create an app with two flutter views:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:orientation="vertical"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  >

  <io.flutter.view.FlutterView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_weight="1"
    />

  <io.flutter.view.FlutterView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_weight="1"
    />
</LinearLayout>
```

Expected: Two debug logs for `Observatory listening on http://address:port/`. Each port can be attached to with `flutter attach --debug-port` and used to control one of the flutter instances.

Actual: One debug log of `Observatory listening on http://address:port/`. Attaching to that port controls both instances of flutter simultaneously. 

This repros both on `flutter/engine:master` and `flutter/engine:21008_rewrite-android-embedding-to-reduce-coupling`. The single port also persists when creating multiple instances of `FlutterEngine.java`, and when destroying and creating new `FlutterViews`. The only time I've ever seen ports created is once, after the app has been started for the first time.

**Comment by mklim** [comment]
Not in that example, but there's only one port regardless of how many `FlutterEngine` instances are created as well.

Though a point of confusion for me here is that I'm not seeing how instantiating a `FlutterEngine` in the Java layer should call through and create an engine in the native layer in a way that `FlutterView` isn't already doing in this example, could you explain that more?

I'm seeing `FlutterEngine` create a `FlutterJNI` in its constructor and call `attach()` on it, but that doesn't seem materially different for me than what `FlutterView` itself does. See flutter/engine#6425 in the new branch, it ends up creating a `FlutterNativeView` that also constructs a `FlutterJNI` and calls `attach()` in its constructor. The one thing it's doing that looks different is creating a `DartExecutor.java`, but that class doesn't look like it's doing anything other than managing its own state in its constructor.

**Comment by matthew-carroll** [comment]
I thought you were using the new FlutterView.  For the old FlutterView that probably makes sense.

**Comment by mklim** [comment]
/cc @chinmaygarde 

It looks like flutter/engine#4932 defined this behavior deliberately. The relevant logic and relationships are detailed there.

> There can only be one Dart VM in the process. The numerous shell
interact with one another to manage the VM lifecycle. Once the last
shell goes away, the VM does as well and hence all resources
associated with the VM are collected.

> Isolate management has been significantly overhauled. There are no
owning references to Dart isolates within the shell. The VM owns the
only strong reference to the Dart isolate. 

Is this something we want to change?

**Comment by mklim** [comment]
Talked offline. The real issue here isn't one isolate per engine instance, it's one Dart VM, service protocol, and debug port per process. There are multiple isolates for the single debug port, and it should be possible to choose which one we're connecting to when attaching to the port. Right now there's fallback logic for picking an isolate in [`service_protocol.cc`](https://github.com/flutter/engine/blob/master/runtime/service_protocol.cc).

**Comment by matthew-carroll** [comment]
@mklim Please be sure to open a new issue with the new details and new approach.
