### ISSUE TITLE
Flutter FutureBuilder is keep firing even if im on a different page

### ISSUE THREAD

**Issue by shtengel** [flutter/flutter#22768]
Hi, i have a StatelessWidget with FutureBuilder.
when i leave the current page to the next by calling `Navigator.of(context).push(..)`  the FutureBuilder is being called again, even if i continue to call `Navigator.of(context).push(..)` to the next page the FutureBuilder is fired again!
i used some printing in my StatlessWidget to discover that the `Widget build `method is not being called its only the FutureBuilder.builder function

i tried following the suggestion here https://github.com/flutter/flutter/issues/11426
but without success...

how do i fix it ?? thanks!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

I think this requires a minimal running reproduction to diagnose.
