### ISSUE TITLE
OutlineButton doesn't follow Material spec, does not have a materialTapTargetSize property

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#22778]
The Outline Button should not be elevated when pressed. The border should be thinner.

Fixing this will also fix https://github.com/flutter/flutter/issues/22755, which is caused by a hack where the button is filled with opaque color while pressed to make elevation look right.

https://material.io/design/components/buttons.html#outlined-button

<img src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1VeAknkDyfsIiVrvEMVovd69hGLdYrlbL%2Foutlined-button-states.png">

**Comment by HansMuller** [comment]
> Fixing this will also fix #22755, which is caused by a hack where the button is filled with opaque color while pressed to make elevation look right.

Definitely not "a hack". The original outline button design included the elevation change and opaque fill.  It turned out to be difficult to implement (might have tempted some toolkit devs to resort to "hacks") and isn't part of the spec anymore. As you've pointed out.
