### ISSUE TITLE
Tutorial page is not opening on Firefox 

### ISSUE THREAD

**Issue by learnNcode** [flutter/flutter#22776]
Firebase for flutter tut page is not opening on Firefox, Attaching screenshot for reference 

Screenshot link : https://drive.google.com/open?id=1VpRAaiKFHuDy_Iq85V3aXpH_kO5ZqUn_

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
