### ISSUE TITLE
how can i solve this error

### ISSUE THREAD

**Issue by beshoyramzy** [flutter/flutter#22779]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by 5ummit** [comment]
Am I the only one seeing this?
<img width="778" alt="screen shot 2018-10-07 at 16 00 43" src="https://user-images.githubusercontent.com/33470998/46582060-2ad82880-ca4a-11e8-88bb-5633fedfc17b.png">

In any case,  consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
This doesn't look like a valid issue.

**Comment by zoechi** [comment]
You copied the link in a comment section. I updated your issue.
Try deleting `F:\flutter\bin\cache` and then `flutter doctor` again.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
