### ISSUE TITLE
[documentation] provide code sample for MergeSemantics

### ISSUE THREAD

**Issue by 1166544** [flutter/flutter#22782]
Whether each widget sample API docs provide sample code ?
For example, this:
https://docs.flutter.io/flutter/widgets/Row-class.html
```dart
new Row(
  children: <Widget>[
    new Expanded(
      child: new Text('Deliver features faster', textAlign: TextAlign.center),
    ),
    new Expanded(
      child: new Text('Craft beautiful UIs', textAlign: TextAlign.center),
    ),
    new Expanded(
      child: new FittedBox(
        fit: BoxFit.contain, // otherwise the logo will be tiny
        child: const FlutterLogo(),
      ),
    ),
  ],
)
```

But some of them are not, for example:
https://docs.flutter.io/flutter/widgets/MergeSemantics-class.html

So, we hope the offical site provide all of them and easily to find out how to use them, and can each widget provide a corresponding GIF animation display what their running effects?

**Comment by iapicca** [comment]
Hi @1166544 
providing a code sample for all the classes in the API is obviously desirable,
but hardly addressable in a single issue moreover it is natural for some classes
to get higher priority than others and therefore providing code sample accordingly.

I'm hijacking this issue as request of code sample for the class you mentioned,
for other class you or other feel the need for code sample I suggest to open a separated issue
for each specific class.

Thank you
