### ISSUE TITLE
Google sign in returns null for 3.2.1 and CANCELED state for 3.0.5

### ISSUE THREAD

**Issue by svanschooten** [flutter/flutter#22784]
After debugging for multiple hours without any result at all, I have given up. I have been learning Flutter by creating an application that connects to a Firebase realtime database, which work in debug mode and local installation through adb. But whenever I (or any of my friends) install the package though something else than adb (such as package manager or something else) I am gettings issues.

For starters, here is the relevant part of my pubspec.yaml:

    dependencies:
      google_sign_in: 3.2.1
      firebase_auth: 0.5.20
      firebase_core: 0.2.5

At the beginning of my statefull widget:

    final FirebaseAuth _fAuth = FirebaseAuth.instance;
    final GoogleSignIn _gSignIn = new GoogleSignIn();
    final DatabaseReference database = FirebaseDatabase.instance.reference().child("users");

And the relevant part of my code:

    googleSignInAccount = await _gSignIn.signIn(); // [1]
    authentication = await googleSignInAccount.authentication; // [2]

    ...

    _firebaseUser = await _fAuth.signInWithGoogle(
        idToken: authentication.idToken,
        accessToken: authentication.accessToken);

    ...

So the problem is that, with a bit older 3.0.5 version of the google_sign_in package, I get the error:

    PlatformException(sign_in_failed, Status{statusCode=CANCELED, resolution=null}, null)

Already at point [1], even though the login dialog was never cancelled, just after selecting a google account to use. This never happens in debug mode, as if google rejects the production application on login. When I update the google_sign_in package to version 3.2.1, I get the following message at point [2]:

    NoSuchMethodError: The getter 'authentication' was called on null.
    Receiver: null
    Tried calling: authentication

Which means step [1] does not result in an error any more, but just returns null, and as such it fails at step [2]. I do not have this problem in debug mode, so there should be nothing wrong with the login flow.

Note: I do use a local signing keystore, but I never had any issue with that.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by idofilus** [comment]
@zoechi I've having the same issue, my doctor verbose is:

```
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.286], locale en-US)
    • Flutter version 0.8.2 at D:\Flutter\flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Ido\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\Ido\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.3
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] VS Code, 32-bit edition (version 1.25.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • ONEPLUS A3003 • a76707df • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by svanschooten** [comment]
> Please add the output of `flutter doctor -v`.

Will do when I get home, though it is not very interesting as all tests pass

**Comment by zoechi** [comment]
> not very interesting as all tests pass

The `all tests pass` at the bottom is the least interesting part of the whole output ;-)

**Comment by svanschooten** [comment]
Haha, okay then, here it is! (thought he bottom part is if there is a device connected... ??)

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/stijn/Tools/flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/stijn/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /home/stijn/Tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/stijn/Tools/android-studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at /home/stijn/Tools/idea-IU-173.4548.28
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700

[✓] Connected devices (1 available)
    • ONEPLUS A6003 • ee2aa1a0 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by ratsey** [comment]
I'm going to add a 'me too' to this one. The exact same issue - I can run in debug and the GoogleSignIn.signIn method works fine (his [1] line), same if running with `flutter run --release`. However, if I then take the output from that `--release` run and push it through the Play store, the resulting install will not run, the signIn method returning Null, exactly as @svanschooten describes.

What's interesting is that it's supposedly the same APK, running on the same hardware test device, my LG V20. What is happening during that Play release?

I have a device monitor hooked up and there are no errors thrown, the `Future<GoogleSignInAccount> signIn() {` method in `google_sign_in.dart` is just returning Null. I'm playing around with adding print statements to the `google_sign_in.dart` code to try to trace it but it's a bit of a shot in the dark.

```
 google_sign_in: "^3.2.1"
  firebase_auth: "^0.6.2+1"
  firebase_core: ^0.2.5+1
```

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at E:\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\jens\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA Community Edition 181.4203.6
    • Flutter plugin version 22.2.3
    • Dart plugin version 181.4096.12

[√] VS Code, 64-bit edition (version 1.28.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by ratsey** [comment]
I'm certain this is a problem with how Flutter 'core code' is handling the return message from Google authentication.

As Flutter developers, we're just seeing `NoSuchMethodError: The getter 'authentication' was called on null` when we follow the example code provided. However, the underlying issue is issued by Flutter at `package:flutter/src/services/message_codecs.dart:551` in attempting to decode the message returned. If you look at that source code, you'll see that it expects a 0 first byte to indicate a successful response. For some reason, that message does not pass and is returned as an error, and a Null value. I don't know if this is legitimate, ie Google authentication really is returning an error message incorrectly, or if it's the decode function that's at fault. This needs someone from the Flutter core team to investigate.

**Comment by Mantas0726** [comment]
But it's working for others... What channel are they using? Btw, it used to work for me, but I cannot recall what caused it to stop :/

**Comment by ratsey** [comment]
Looks like the signin code was last updated 16 days ago by @mehmetf as 

> Handle user cancel when signing in (#805)

 which seems like it's probably related (unless this was the fix?) [https://github.com/flutter/plugins/commit/07176dd3642e735ed68e0c99ba2e552281814424](url)

**Comment by mehmetf** [comment]
Thank you all for the detailed reports. So, to summarize, GoogleSignIn returns null as opposed to cancelled (and both are wrong). We need more investigation on both counts. The latest PR I submitted has nothing to do with either of these and should only affect the reauthentication flow when the OS asks for that.

My gut feeling is that something has changed in the way Google sets up authentication so I am going to try to build a fresh Android app and see if I can successfully get a token and fix up the sample app.

**Comment by mehmetf** [comment]
Quick question to @ratsey @svanschooten: How are you setting up your application and your firebase entries? One possibility is that you are not using the right Android package name/client id combination. For instance, you might be copying the sample app (which would work in debug mode) but upon releasing it with the proper package name, it stops working.

We realized that the firebase project we were using for the google_sign_in example was defunct and we are seeing similar issues (cancelled with old version, null with the new) so we are in the process of [updating it](https://github.com/flutter/plugins/pull/859). After update, it works once again according to @bparrishMines.

**Comment by svanschooten** [comment]
@mehmetf I set it up as a new project, using a new keystore (didn't have one yet) and followed the signing manual to the letter. Should I have two separate keystores for development and production? Because there is no reference to that in the firebase manual.

**Comment by ratsey** [comment]
@mehmetf WINNER! WINNER! 

I completely forgot about Google Play resigning the APKs.

> Google re-signs the APKs with the original app signing key you provided and delivers your app to the user.

From the App Signing menu in the Google Play store, I see that the App Signing certificate SHA1 fingerprint is NOT the same as the one I'm signing my release APK with. Adding that fingerprint to the Firebase Console WORKED!

I do think that the error message passed back needs to be reviewed - saying that the user cancelled the login process is completely wrong and some indication that it's a certificate configuration/general security issue would be far more appropriate.

**Comment by mehmetf** [comment]
Great!

As for error messages, if you look at the [source code](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java), CANCEL result is only returned if Android itself tells us the operation was cancelled. However, I do think that the ActivityResult code does not reflect what *really* happened. I am going to look into differentiating the errors if possible.

**Comment by akeating** [comment]
Thanks for the clues. I solved this issue by adding a SHA-1 fingerprint to my firebase android app. Perhaps there's a documentation issue here too, in addition to improved error specificity?

**Comment by vmihalachi** [comment]
Out of curiosity, is there any difference between setting a SHA-1 and a SHA-256 key on Firebase?

**Comment by mehmetf** [comment]
@akeating I feel your pain. Unfortunately, *from application setup point of view*, there's not much we can do here other than linking to Firebase documentation. If following that does not get you the result you would like, it is not something Flutter documentation can fix. Ultimately, we don't own the Android auth system so I suggest you ask for clarification on Firebase/Android forums.

What we are responsible for is making sure google_sign_in plugin is compatible with the Android Auth APIs (and any changes that might require).

My personal experience: 95% of the time, if Android Auth is failing you in unexpected ways, either your package name is incorrect or your signing key fingerprint is incorrect.

**Comment by akeating** [comment]
@mehmetf  you're right, there is a division of responsibilities here and you likely do not have control over large chunks of the ecosystem. That said, it does seem a pain-point related to getting started with flutter with google sign-in since firebase is an integral part of the setup flow. I will certainly look for ways to influence stakeholders to reduce the friction here _from a product perspective_.

**Comment by svanschooten** [comment]
@mehmetf I have issues with both APKs installed through the playstore and when I transfer and install them over an different medium, such as whatsapp and ftp. I shall check in the APK self if the fingerprint matches.

**Comment by mehmetf** [comment]
I am closing this issue because the remaining problems are not Flutter related. https://pub.dartlang.org/packages/google_sign_in 3.2.2 has been published which should give a better error code.

**Comment by svanschooten** [comment]
@mehmetf The google_sing_in update gave me a clear message and I was able to resolve it. Thanks for all the help!

**Comment by thekeenant** [comment]
For anyone who comes across this... I encountered this error in debug mode within an emulator. It had been a while since I used the emulator and it turns out that I had been signed out (changed password probably) of the Google account I was trying to select within the Flutter app.

This may seem obvious but since there was no error it was tricky to narrow down. Seems like there should be some error thrown/logged indicating the account is not signed in properly.

**Comment by gilbertmpanga12** [comment]
@thekeenant  Same issue here, how did you solve it ?

**Comment by gilbertmpanga12** [comment]
@thekeenant 

This issue has really saved me after a number of days being stuck so here's how you solve it.
Turns out after creating a debug key e.g  keytool -exportcert -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore
You list the debug key certficate SHA or SHA keys by  keytool -list -v -keystore {keystore_name} -alias {alias_name} 
Save that SHA key in your firebase app project savings

For production, you need to re-create a key using the previous commands
and list the SHA certificate by  keytool -list -v -keystore {keystore_name} -alias {alias_name}
and add it to firebase app project settings again voila!!

**Comment by ManavBrothers** [comment]
do anyone have the solution for it ! or just revolving in the same question again and again...
