### ISSUE TITLE
AlertDialog action buttons have the wrong text color

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#22789]
Flutter version: latest master

I created an app with a dark theme, `pink` primary swatch and `orange` accent color.

When I open an `AlertDialog`, the action buttons are turquoise. The theme colors are ignored:

![screenshot_1538957302](https://user-images.githubusercontent.com/22688477/46588600-8a145800-ca9f-11e8-8fa8-f4562ef452c6.png)
 
This problem started recently on the master branch.

Code to reproduce:
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.pink,
        accentColor: Colors.orange,
        brightness: Brightness.dark,
      ),
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _showDialog() {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: Text('Some Title'),
          content: Text('Some content'),
          actions: <Widget>[
            FlatButton(
              onPressed: null,
              child: Text('DISABLED'),
            ),
            FlatButton(
              onPressed: () => Navigator.pop(context),
              child: Text('ENABLED'),
            )
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(),
      body: new Center(
        child: FlatButton(
          textTheme: ButtonTextTheme.accent,
          onPressed: _showDialog,
          child: Text('SHOW DIALOG'),
        ),
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by sir-boformer** [comment]
The root of the problem is here:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/dialog.dart#L276

The dialog creates a blank `ButtonTheme.bar` without taking into account the `colorScheme` of the base theme. `ButtonTheme.bar` then uses the default `ColorScheme.light`, which comes with the turquoise secondary color:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/button_theme.dart#L145

@HansMuller

**Comment by HansMuller** [comment]
#22827 was a  temporary fix. Will close this bug (again) when the permanent fix lands.

**Comment by Levi-Lesches** [comment]
Can someone take a look at #38646? I still see this issue.
