### ISSUE TITLE
The generated Flutter projects don't compile

### ISSUE THREAD

**Issue by senselogic** [flutter/flutter#22799]
I've just installed Dart, Flutter and Android Studio on my Linux Mint XFCE 18.3 system.

Each time I create a Flutter project (using the "Start a new Flutter project" wizard in Android Studio or with the "flutter create" command), I have to **manually fix all the following files** to be able to compile the generated demo application and run it in the Android device emulator.

myapp/android/build.gradle :

```
classpath 'com.android.tools.build:gradle:3.2.0'
```

myapp/android/gradle/wrapper/gradle-wrapper.properties :

```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```

myapp/android/app/build.gradle :

```
...
afterEvaluate {
    android.applicationVariants.all {
        Task flutterX86Jar = project.tasks.findByName("flutterBuildX86Jar")
        Task checkClasspath = project.tasks.findByName("check${it.name.capitalize()}Classpath")
        if (flutterX86Jar && checkClasspath) {
            checkClasspath.dependsOn flutterX86Jar
        }
    }
}
```
Why this, and what have I done wrong ?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
> Flutter version 0.0.22-pre.1 at /home/eric/flutter
[        ]     • Framework revision 553fc4264e (il y a 7 mois),

that looks quite outdated. Please try with a newer Flutter version.

**Comment by senselogic** [comment]
Ok, I'll reinstall everything.

As the archive version don't work on my system, I'll reinstall flutter using the following commands :

git clone -b master https://github.com/flutter/flutter.git
cd ~/flutter/bin
./flutter doctor -v

**Comment by zoechi** [comment]
That should lead to a recent Flutter version.
Perhaps it's just the PATH that still points to an older Flutter version somewhere else on your system.

**Comment by senselogic** [comment]
Thanks a lot for your advices !

To be sure I'll be running the latest version, this time I've :
- removed manually any android/flutter folders I could find on my system
- reinstalled Flutter directly from its Github depot
- completely overridden the Path environment variable in ~/.profile (export PATH=/home/eric/flutter/bin:/usr/lib/dart/bin:/home/eric/android-studio/bin:/home/eric/Android/Sdk/platform-tools:/home/eric/Android/Sdk/tools/bin:/home/eric/Android/Sdk/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

Now the generated Flutter project compiles and runs well, so I guess one of the above steps has made the difference :)

I've just had a popup from the Android emulator complaining that my ADB binary (in /home/eric/Android/Sdk/platform-tools/adb) was obsolete and will have performance issues, but apart from that everything seems to work fine now :)
