### ISSUE TITLE
Shared preferences plugin default values

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#22806]
Would be nice if the plugin allow to return a default value if the key is not in the preferences. 
like: 

```dart
String getString(String key, {String defaultValue = null})
```

**Comment by jaumard** [comment]
@zoechi I've done a PR to fix this if you want to take a look :)

**Comment by zoechi** [comment]
@jaumard Great, we'll have to wait for someone from the Flutter team though.

**Comment by cyanglaz** [comment]
I don't think this is really necessary. You can just use `??` to have the same behavior. E.g.
```
String myString = getBool('myKey') ?? "a default string";
```

Closing this issue. Please feel free to open another issue if you think it is otherwise necessary.

**Comment by RdeWilde** [comment]
Passing a default value as a second argument is more straight forward imho.

The example above is strange anyway. I'd say the type of the second argument has to match the return type.
