### ISSUE TITLE
Why Flutter project can't find build folder, but the build folder assits in my PC Folder?

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#22813]
When building Flutter project, i can find the `build` folder in my computer folder,but I can't find it in my project. 

EveryTime I find the apk that builded by Flutter in my computer folder,  It is so troublesome.

Please fix it! Thank you!

Show me the problem pictures like this:

> this is the project，look, you can't find the `build` folder after building apk：

![Flutter project](https://user-images.githubusercontent.com/27602662/46620893-9ad4d480-cb58-11e8-80f3-dc750b3f2ab7.png)

> this is the `build` folder in computer:

![PC folder](https://user-images.githubusercontent.com/27602662/46620912-a6c09680-cb58-11e8-9c8e-a99411b60a7c.png)

**Comment by zoechi** [comment]
I think this is some setting in IntelliJ (like scope) that hides this folder.
I doubt there is anything the Flutter team can do.

**Comment by AweiLoveAndroid** [comment]
Thank you.  The problem  I  had solved.

**Comment by kf6gpe** [comment]
Per @AweiLoveAndroid's lat comment, closing this issue. Thanks!

**Comment by AravindTamizh** [comment]
i am also having the same problem

**Comment by Ravikumawat1990** [comment]
i am also having the same problem
