### ISSUE TITLE
Support "highlight" state on mouse hover

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#22816]
This involves modifying the core Material elements to go into "base hover" state. You can see the effect of this by hovering the mouse over Github buttons.

This is an L1 Chromebook requirement.

**Comment by jslavitz** [comment]
Do we have the spec for this yet? I'm happy to resume working on this, but I'm not sure of the spec requirements at this point.

**Comment by zoechi** [comment]
Related to #757

**Comment by gspencergoog** [comment]
This is complete, as far as I understand it.  Material components now respond to hover with the appropriate hover feedback.
