### ISSUE TITLE
Support for showing tooltip on mouse hover

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#22817]
Show a widget's tooltip if the cursor pauses within a tooltip-enabled widget for some period of time.  Open question: do we reset the timer if they move the cursor within the widget, so that we only count time when the cursor isn't moving? We need UX guidance on this.

This is an L2 Chromebook requirement.

**Comment by zoechi** [comment]
Related to #757

**Comment by JediBurrell** [comment]
Everything for this is outlined in the [design spec](https://material.io/design/components/tooltips.html#behavior). There shouldn't be a pause in the cursor for the tooltip to display; additionally, moving the mouse should not affect the tooltip unless the cursor is moved outside of the widget.

**Comment by gspencergoog** [comment]
Reopened until https://github.com/flutter/flutter/pull/31699 re-lands the support for it.
