### ISSUE TITLE
Flutter.h' file not found with  shared_preferences Plugin

### ISSUE THREAD

**Issue by ChristBKK** [flutter/flutter#22821]
##Steps to Reproduce

1. Add   shared_preferences: "^0.4.2" to pubspec.yaml
2. Run flutter run

## Logs
```
Launching lib/main.dart on iPhone XS Max in debug mode...
Running pod install...                                       1.0s
Starting Xcode build...
Xcode build done.                                            1.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/christian/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/ios/Classes/SharedPreferencesPlugin.m:5:
    /Users/christian/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
```

```
[✓] Flutter (Channel dev, v0.9.6, on Mac OS X 10.13.6 17G2307, locale en-TH)
    • Flutter version 0.9.6 at /Users/christian/documents/coding/flutter
    • Framework revision 13684e4f8e (6 days ago), 2018-10-02 14:15:17 -0400
    • Engine revision f6af1f20ba
    • Dart version 2.1.0-dev.6.0.flutter-8a919426f0

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/christian/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone XS Max • F701DB9C-85B5-425E-A5B8-9749A44CA6D2 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Is your project using Swift?

Please try 
```
flutter clean
rm -rf ios/Podfile.lock ios/Pods/
flutter run
```

**Comment by ChristBKK** [comment]
@zoechi  thanks , I tried that. Same error unfortunately

**Comment by bbofrk** [comment]
+1

**Comment by martflu** [comment]
This is what helped me to finally build on iOS again:
https://github.com/flutter/flutter/issues/23186#issuecomment-434452028

**Comment by malibayram91** [comment]
this is the best solution 
https://github.com/flutter/flutter/issues/24428

**Comment by endrelovas** [comment]
`
cd ios
rm Podfile
rm Podfile.lock
cd ..
flutter packages get
flutter run
`
worked for me

**Comment by nghianm-cmyk** [comment]
> Is your project using Swift?
> 
> Please try
> 
> ```
> flutter clean
> rm -rf ios/Podfile.lock ios/Pods/
> flutter run
> ```

You saved my life!

**Comment by erperejildo** [comment]
none of the above worked for me

**Comment by istidanaharjanti** [comment]
me too.. i get this error 
```
Support Files/firebase_core/firebase_core-umbrella.h:13:
    /Users/istidanaharjanti/Documents/flutter/.pub-cache/hosted/pub.da
    rtlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h
    :8:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
```

after upgrade flutter 2.0.6 and change the `compatibilityVersion = "Xcode 12.0";`
tried above, but none worked  for me.

**Comment by erperejildo** [comment]
> me too.. i get this error
> 
> ```
> Support Files/firebase_core/firebase_core-umbrella.h:13:
>     /Users/istidanaharjanti/Documents/flutter/.pub-cache/hosted/pub.da
>     rtlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h
>     :8:9: fatal error: 'Flutter/Flutter.h' file not found
>     #import <Flutter/Flutter.h>
>             ^~~~~~~~~~~~~~~~~~~
> ```
> 
> after upgrade flutter 2.0.6 and change the `compatibilityVersion = "Xcode 12.0";`
> tried above, but none worked for me.
> 
> this is `flutter doctor -v` on my project:
> 
> ```
> [✓] Flutter (Channel unknown, 2.0.6, on macOS 11.3.1 20E241
>     darwin-x64, locale en-ID)
>     • Flutter version 2.0.6 at
>       /Users/istidanaharjanti/Documents/flutter
>     • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58
>       -0700
>     • Engine revision 05e680e202
>     • Dart version 2.12.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK
>     version 30.0.3)
>     • Android SDK at /Users/istidanaharjanti/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.3
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5, Build version 12E262
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
>       Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.56.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.22.0
> 
> [✓] Connected device (2 available)
>     • iPhone 11 Pro (mobile) • 978CBCB7-ABF1-4C00-AE69-DA213D0EA6F0 •
>       ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
>       (simulator)
>     • Chrome (web)           • chrome                               •
>       web-javascript • Google Chrome 90.0.4430.93
> 
> • No issues found!
> ```

I fixed the error checking all the packages I have. One of them doesn't support Flutter 2 yet. This is the **only** solution.
For this go to your files and see if some of the imports have any warning

**Comment by TylerSustare** [comment]
I'm pretty sure the only thing that is going to resolve this for me going forward is to update flutter like I would react native... just don't.

**Comment by erperejildo** [comment]
> I'm pretty sure the only thing that is going to resolve this for me going forward is to update flutter like I would react native... just don't.

Kind of. The main problem here are dependencies not updated yet to the new version. There is at least one creating this conflict. You can always try to ask directly on their repos, some owners will update without not much effort.

Last option is to adapt them yourself... or use a different one already updated

**Comment by istidanaharjanti** [comment]
> > me too.. i get this error
> > ```
> > Support Files/firebase_core/firebase_core-umbrella.h:13:
> >     /Users/istidanaharjanti/Documents/flutter/.pub-cache/hosted/pub.da
> >     rtlang.org/firebase_core-0.5.3/ios/Classes/FLTFirebaseCorePlugin.h
> >     :8:9: fatal error: 'Flutter/Flutter.h' file not found
> >     #import <Flutter/Flutter.h>
> >             ^~~~~~~~~~~~~~~~~~~
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after upgrade flutter 2.0.6 and change the `compatibilityVersion = "Xcode 12.0";`
> > tried above, but none worked for me.
> > this is `flutter doctor -v` on my project:
> > ```
> > [✓] Flutter (Channel unknown, 2.0.6, on macOS 11.3.1 20E241
> >     darwin-x64, locale en-ID)
> >     • Flutter version 2.0.6 at
> >       /Users/istidanaharjanti/Documents/flutter
> >     • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58
> >       -0700
> >     • Engine revision 05e680e202
> >     • Dart version 2.12.3
> > 
> > [✓] Android toolchain - develop for Android devices (Android SDK
> >     version 30.0.3)
> >     • Android SDK at /Users/istidanaharjanti/Library/Android/sdk
> >     • Platform android-30, build-tools 30.0.3
> >     • Java binary at: /Applications/Android
> >       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> >     • Java version OpenJDK Runtime Environment (build
> >       1.8.0_242-release-1644-b3-6915495)
> >     • All Android licenses accepted.
> > 
> > [✓] Xcode - develop for iOS and macOS
> >     • Xcode at /Applications/Xcode.app/Contents/Developer
> >     • Xcode 12.5, Build version 12E262
> >     • CocoaPods version 1.10.1
> > 
> > [✓] Chrome - develop for the web
> >     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
> >       Chrome
> > 
> > [✓] Android Studio (version 4.1)
> >     • Android Studio at /Applications/Android Studio.app/Contents
> >     • Flutter plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
> >     • Dart plugin can be installed from:
> >       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> >     • Java version OpenJDK Runtime Environment (build
> >       1.8.0_242-release-1644-b3-6915495)
> > 
> > [✓] VS Code (version 1.56.0)
> >     • VS Code at /Applications/Visual Studio Code.app/Contents
> >     • Flutter extension version 3.22.0
> > 
> > [✓] Connected device (2 available)
> >     • iPhone 11 Pro (mobile) • 978CBCB7-ABF1-4C00-AE69-DA213D0EA6F0 •
> >       ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
> >       (simulator)
> >     • Chrome (web)           • chrome                               •
> >       web-javascript • Google Chrome 90.0.4430.93
> > 
> > • No issues found!
> > ```
> 
> I fixed the error checking all the packages I have. One of them doesn't support Flutter 2 yet. This is the **only** solution.
> For this go to your files and see if some of the imports has any warning

already solved this. there is package that doesn't support flutter 2.0.6 yet, so i just upgrade it to 2.0.3 and it run well.
thanks anyway. (well this is old issue but i remember didn't reply this yet).
