### ISSUE TITLE
StreamBuilder and AsyncSnapshot + rxdart question

### ISSUE THREAD

**Issue by gangstafrog** [flutter/flutter#22820]
I have `final _fetcher = PublishSubject<MyModel>() ;` in my bloc Component. Here is structure of MyModel: 
`MyModel {
  List<MyObjects> _objects = [];
  List<MyObjects> get allObjects => _objects;
}`
also there is  `Observable<MyModel> get myObjects => _fetcher.stream;`  in bloc. I have two pages, first displays list of MyObjects inside Listview.builder, and second displays selected MyObject data. I trying to get data from myObjects using StreamBuilder. In the first page all objects displays perfectly. But when i open page with selected object, my AsyncSnapshot inside StreamBuilder always has connections.state waiting, although I have data in stream. What am I doing wrong?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
