### ISSUE TITLE
TextField: "autocorrect: false" still shows suggestions in keyboard

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#22828]
Flutter version: Very recent master build

Happens in the Android Emulator (with Google Keyboard) and on a real Android device (with Sony keyboard). I'm not sure about iOS.

<img src="https://user-images.githubusercontent.com/22688477/46633912-79231f80-cb4f-11e8-91fe-bacb722a3546.png" width="200">

Code to reproduce:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_playground/text_area.dart';
import 'package:path/path.dart' as path;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Playground',
      home: AutoCorrectTest(),
    );
  }
}

class AutoCorrectTest extends StatefulWidget {
  @override
  _AutoCorrectTestState createState() => _AutoCorrectTestState();
}

class _AutoCorrectTestState extends State<AutoCorrectTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('TextField with autocorrect: false'),
      ),
      body: Padding(
        padding: EdgeInsets.all(16.0),
        child: TextField(
          autocorrect: false
        )
      ),
    );
  }
}
```

```
[√] Flutter (Channel master, v0.9.7-pre.61, on Microsoft Windows [Version 10.0.17134.285], locale de-DE)
    • Flutter version 0.9.7-pre.61 at C:\flutter
    • Framework revision 2d81adf74c (3 days ago), 2018-10-05 22:29:37 -0700
    • Engine revision 572fa5646a
    • Dart version 2.1.0-dev.6.0.flutter-c6254163dc

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at F:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by sir-boformer** [comment]
After further investigation, I'm not sure what would be the best way to implement this:

On iOS, autocorrect and keyboard suggestions are directly connected (`UITextAutocorrectionTypeNo` disables suggestions and autocorrect). In the current version of Flutter, a `TextField` with `autocorrect: false` displays no keyboard suggestions on iOS:

https://github.com/flutter/engine/blob/d1c71e5206bd9546f4ff64b7336c4e74e3f4ccfd/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L707-L709

-------

On Android, autocorrect and keyboard suggestions can be toggled separately.
I guess this is more or less a new feature, because suggestions and autocorrect are two separate things:

* `InputType.TYPE_TEXT_FLAG_AUTO_CORRECT` to enable autocorrect
* `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` to disable suggestions

Here is how the flags are currently set by flutter:

https://github.com/flutter/engine/blob/d1c71e5206bd9546f4ff64b7336c4e74e3f4ccfd/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L93-L99

----

So for Android it would make sense to add a new property `bool keyboardSuggestions` to `TextField` and `TextFormField`. In the documentation, it should be noted that on iOS setting either `autocorrect: false` or `keyboardSuggestions: false` disables both features.

**Comment by mploigt** [comment]
I have the same problem implementing a textfield without the suggestion bar on android. For my app the user can input specific codes that should not be changed with suggestions or autocomplete. The suggestion bar is really not helpful in this situation and I can't disable it on android. 

Any idea on when the feature to disable the suggestion bar on android will be implemented?

**Comment by josvos** [comment]
This technically sounds like pretty "low hanging fruit" for the Flutter dev team (but I might be wrong), but the fact that it is not possible to disable the suggestions in a Flutter app is extremely annoying for app developers.

**Comment by daveparks23** [comment]
Any update on this... I am having the same problem.  Love Flutter!

**Comment by OscarEReyes** [comment]
Any update on this? 
Predictive text ruins my textfields. 
Highlighting a textfield with text inside and typing results in duplicated text.
Awful for UX.

This is fixed locally for me by turning off predictive text... can't expect that of users....

**Comment by Piinks** [comment]
> On Android, autocorrect and keyboard suggestions can be toggled separately.
> I guess this is more or less a new feature, because suggestions and autocorrect are two separate things:
> 
> * `InputType.TYPE_TEXT_FLAG_AUTO_CORRECT` to enable autocorrect
> * `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` to disable suggestions
> 
> Here is how the flags are currently set by flutter:
> 
> https://github.com/flutter/engine/blob/d1c71e5206bd9546f4ff64b7336c4e74e3f4ccfd/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L93-L99
>
I've looked into this and it seems that the `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` doesn't actually dismiss the keyboard suggestions on the Android platform.  There is also a comment here that:

>// Some devices ignore TYPE_TEXT_FLAG_NO_SUGGESTIONS.

Why this is the case may be the root of the problem.

**Comment by dnfield** [comment]
Are we positive that this is a real regression?  Is it possible that @sir-boformer is testing this on a device that doesn't respect the flag?

**Comment by cbracken** [comment]
@dnfield agreed, this is not a regression. I did the initial implementation on Android and iOS and the difference would have been an oversight on my part. As suggested above, I think the answer is that we add additional API and document the platform differences between iOS and Android.

**Comment by markmoskalenko** [comment]
Help solve the problem! Our release is delayed because of this.

Here is a similar problem https://github.com/flutter/flutter/issues/19743
A year has passed ..

**Comment by OscarEReyes** [comment]
Hey @markmoskalenko ,

I see the issue you are referencing and I experienced something similar.

The issue was if I selected a text field that had text in it and started typing the text would duplicate and add the character typed.

Ex:

You have the word fire in the text field
You select it and type t

Now it has firefiret in it.

Now that looked similar to issue 19743 so if this is also bothering you, I can help you fix it as I implemented a workaround in my app.

**Comment by markmoskalenko** [comment]
@OscarEReyes 

Very worried!
Please tell me how to get around this ?!

**Comment by OscarEReyes** [comment]
> @OscarEReyes
> 
> Very worried!
> Please tell me how to get around this ?!

I went ahead and commented on issue #19743 on how to solve this. 
Let me know if it works.

**Comment by amreniouinnovent** [comment]
Temporary solution
`keyboardType: TextInputType.emailAddress`

**Comment by kevinengel** [comment]
This is a bug.

Assuming earlier comments have identified the correct [source code](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java), InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS is only being added when obscureText is true, _not when autocorrect is false_

I've verified on my Pixel 3 that setting obscureText = true does disable keyboard suggestions, whereas setting autocorrect = false does not.

**Comment by mikeesouth** [comment]
> This is a bug.
> 
> Assuming earlier comments have identified the correct [source code](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java), InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS is only being added when obscureText is true, _not when autocorrect is false_
> 
> I've verified on my Pixel 3 that setting obscureText = true does disable keyboard suggestions, whereas setting autocorrect = false does not.

Nice catch. This works for me too but obscureText have several negative effects in my case (using a Huawei Mate 20 Pro with Android 9 and Swiftkey keyboard):
- obscures the text
- on my phone it displays the numbers row above the default keyboard instead of suggestions
- on my phone it prevents swipe typing

Is anyone working on a bug fix/PR for the Inputype flag?

**Comment by KristineTrona** [comment]
I am experiencing the same issue also on ios - `autoCorrect={false}` seems to work on simulator, but in a release build on a device it was not working. Is there no way to disable the keyboard suggestions?

**Comment by mikeesouth** [comment]
> I am experiencing the same issue also on ios - `autoCorrect={false}` seems to work on simulator, but in a release build on a device it was not working. Is there no way to disable the keyboard suggestions?

You can set obscureText=true but that have some negative effects as stated above.

But I agree - is there any progress on this issue?

**Comment by maks** [comment]
The [Android documention](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_NO_SUGGESTIONS) is pretty clear that the semantics of TYPE_TEXT_FLAG_NO_SUGGESTIONS are different to TYPE_TEXT_FLAG_AUTO_CORRECT, it would be really useful to have this exposed on Flutters TextField.

**Comment by Blindjoedeath** [comment]
Common...

**Comment by justinmc** [comment]
I just opened two PRs for this: https://github.com/flutter/flutter/pull/42550 and https://github.com/flutter/engine/pull/13099

I'm pretty much following exactly what @sir-boformer wrote in [his analysis above](https://github.com/flutter/flutter/issues/22828#issuecomment-428093243) (thank you for that by the way!).  I added a flag that only affects Android called `noSuggestions`, and I commented about the fact that it doesn't affect iOS:

```
  /// This flag only affects Android. On iOS, suggestions are tied directly to
  /// [autocorrect], so that suggestions are only shown when [autocorrect] is
  /// true. On Android autocorrection and suggestion are controlled separately.
```

**Comment by RudolfVonKrugstein** [comment]
How cannot find the option to disable suggestions. What am I missing? Why is this closed?

**Comment by Piinks** [comment]
Hi @RudolfVonKrugstein, what version of Flutter are you using?

**Comment by atreeon** [comment]
Hi @Piinks, I'm having the same problem.  Am I doing something wrong?

I am on the very latest master branch (v1.12.17-pre.38) but I'm getting the following result (ie suggestions)

<img width="347" alt="Screenshot 2019-12-03 at 12 49 29" src="https://user-images.githubusercontent.com/4139336/70053507-83af3c80-15cd-11ea-94d7-d789190ac05d.png">


with the following code
```

          TextField(
            enableSuggestions: false,
            autocorrect: false,
            autofocus: false,
            keyboardType: TextInputType.text,
          ),
```

**Comment by Piinks** [comment]
cc/ @justinmc who worked on the fix for this. I haven't reproduced it yet on master.

**Comment by MichalOlechowskiDev** [comment]
@atreeon @RudolfVonKrugstein  Try with this 
```
TextField(
  enableSuggestions: false,
  keyboardType: TextInputType.visiblePassword
)
```

**Comment by atreeon** [comment]
Hi @MichalOlechowskiDev, that does indeed work.  I would say that it isn't so obvious and also enableSuggestions doesn't seem to alter the behaviour at all (just the keyboardType property) and this doesn't work when the keyboardType is set to anything else other than visiblePassword.  The result is what I am after though so thank you!

**Comment by mikeesouth** [comment]
> @atreeon @RudolfVonKrugstein Try with this
> 
> ```
> TextField(
>   enableSuggestions: false,
>   keyboardType: TextInputType.visiblePassword
> )
> ```

Thanks, this helps. I think that setting any form om password input type will prevent swiping functionality on keyboards that supports it, e.g. stock android and swiftkey. Not sure though and I haven't tested it.

I was expecting it to work like this:
* Swiping would work for all non-password prompt
* autocorrect would autocorrect words when swiping or tapping letters
* enableSuggestions would show/hide the top row with suggested (predicted) words

If that is correct I would like to set a non password type of keyboard, enable autocorrect and disable suggestions.

**Comment by justinmc** [comment]
Gboard ignores the TYPE_TEXT_FLAG_NO_SUGGESTIONS flag in some situations (see [this StackOverflow post](https://stackoverflow.com/questions/45462683/programmatically-disable-auto-suggestions-on-gboard)), which is what is controlled by the `enableSuggestions` parameter in Flutter.

We want to provide a nice platform-independent API and not just create a parameter for every native flag, but we also might not want to special-case things for Gboard in the engine.  I'm not sure if there's a clear improvement to be made here, but I'm definitely interested if someone has a proposal.

**Comment by deandreamatias** [comment]
> Gboard ignores the TYPE_TEXT_FLAG_NO_SUGGESTIONS flag in some situations (see [this StackOverflow post](https://stackoverflow.com/questions/45462683/programmatically-disable-auto-suggestions-on-gboard)), which is what is controlled by the `enableSuggestions` parameter in Flutter.
> 
> We want to provide a nice platform-independent API and not just create a parameter for every native flag, but we also might not want to special-case things for Gboard in the engine. I'm not sure if there's a clear improvement to be made here, but I'm definitely interested if someone has a proposal.

In this case, is better reopen the issue?

**Comment by kevinengel** [comment]
This still doesn't do what I want.

As noted above, the enableSuggestions flag appears to do nothing by itself.  Only when paired with keyboardType: TextInputType.visiblePassword do the suggestions go away.

However, now other options, such as textCapitalization: TextCapitalization.words are ignored.

These are my main requirements - no suggestions (preferably without any space wasting empty grey box or numbers which appear with visiblePassword), and capitalized words.  Is there anyway to achieve this currently in flutter?

**Comment by justinmc** [comment]
@kevinengel Can you achieve that in native Android, and if so what flags do you use?

**Comment by kevinengel** [comment]
Good point, same issue does occurs with Android, please ignore my last post.  Guess it's just a keyboard issue (though c'mon Pixel 3, I feel like you of all phones should be supporting all the Android features ...)

**Comment by justinmc** [comment]
Gboard definitely seems to be doing some non-intuitive things based on the flags that are given.

**Comment by cihadturhan** [comment]
Any chance on reopening this issue?

I'm having this issue on Huawei mate and setting `keyboardType: TextInputType.visiblePassword` is not an option for me because I have to use `TextInputType.multiline`.

I don't want user to use autocomplete because they might enter non-word texts.
Also, if I use `TextInputType.visiblePassword`, enter button on keyboard doesn't work as expected. So it's not a viable option.

**Comment by dnfield** [comment]
@cihadturhan you would have better luck filing a specific issue for Huawei devices with reproduction instructions.

**Comment by louia** [comment]
May 2020, flutter stable 1.17.1, still experimenting this issue with default samsung's keyboard and with this code :

```
TextField(
          autocorrect: false,
          enableSuggestions: false,
          autofocus: false
````

PLEASE RE OPEN

**Comment by justinmc** [comment]
@louia Can you achieve what you want with a native Android app?  If so, how? See https://github.com/flutter/flutter/issues/22828#issuecomment-566269059

If you can reproduce a case that is possible in native Android but not possible in Flutter given the flags being set, go ahead and open a separate issue with reproduction steps.  Please tag me and I'll be interested to see what's going on.

**Comment by PhamTruongHung** [comment]
> @atreeon @RudolfVonKrugstein Try with this
> 
> ```
> TextField(
>   enableSuggestions: false,
>   keyboardType: TextInputType.visiblePassword
> )
> ```

That's work.

**Comment by nicolasfavier** [comment]
I am facing the same issue,
I want to have a multiple lines TextField without suggestions.

Ios work just fine using : 
`           
keyboardType: TextInputType.multiline,
enableSuggestions: false,
autocorrect: false,
`

But in an android device I still have the suggestions.

In Android natif you can get this using : 
`android:inputType="textFilter|textMultiLine|textNoSuggestions"`

@louia do you want me to open a new issue ?

**Comment by justinmc** [comment]
@nicolasfavier I say yes, please open a new issue with this info!  Someone can double check whether or not those exact inputType flags you mentioned are being set by the Flutter engine.
