### ISSUE TITLE
`flutter create test` should be disallowed

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2283]
We can't actually create a project named "test" because that name conflicts with `package:test`, which we depend upon.  Several people have hit this mysterious error when creating projects.  We should catch this case in the tool, probably by refusing to use that name and explaining why.

**Comment by sethladd** [comment]
Oh yeah, good catch.

**Comment by Hixie** [comment]
We should probably catch all the packages we depend on.

(Yet another reason to reduce our dependencies...)
