### ISSUE TITLE
FATAL EXCEPTION: TokenRefresher in firebase authentication(Google Login)

### ISSUE THREAD

**Issue by rakeshlanjewarwork** [flutter/flutter#22848]
## Steps to Reproduce

Login with google and facebook crashing app first time with firebase authentication which was working fine before package upgrade.

## Logs

```
E/AndroidRuntime( 5654): FATAL EXCEPTION: TokenRefresher
E/AndroidRuntime( 5654): Process: com.adilstore.rakeshproject, PID: 5654
E/AndroidRuntime( 5654): java.lang.NoSuchFieldError: No static field PREFER_HIGHEST_OR_REMOTE_VERSION_NO_FORCE_STAGING of type Lcom/google/android/gms/dynamite/DynamiteModule$VersionPolicy; in class Lcom/google/android/gms/dynamite/DynamiteModule; or its superclasses (declaration of 'com.google.android.gms.dynamite.DynamiteModule' appears in /data/app/com.adilstore.rakeshproject-CsXsXRhlSbbnXzGSokre7Q==/base.apk!classes2.dex)
E/AndroidRuntime( 5654): 	at com.google.android.gms.flags.FlagValueProvider.initialize(Unknown Source:7)
E/AndroidRuntime( 5654): 	at com.google.android.gms.flags.FlagRegistry.initialize(Unknown Source:4)
E/AndroidRuntime( 5654): 	at com.google.firebase.auth.internal.zzx.initialize(Unknown Source:3)
E/AndroidRuntime( 5654): 	at com.google.firebase.auth.internal.zzt.run(Unknown Source:14)
E/AndroidRuntime( 5654): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 5654): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5654): 	at android.os.Looper.loop(Looper.java:171)
E/AndroidRuntime( 5654): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/Process ( 5654): Sending signal. PID: 5654 SIG: 9
Application finished.
```

## flutter analyze
```
E:\flutterProjects\Rakesh_New\rakesh_project>flutter analyze
Analyzing rakesh_project...
No issues found! (ran in 3.8s)

E:\flutterProjects\Rakesh_New\rakesh_project>
```
## flutter doctor -v

```
E:\flutterProjects\Rakesh_New\rakesh_project>flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.320], locale en-US)
    • Flutter version 0.8.2 at E:\flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at E:\MyProgramFiles\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = E:\MyProgramFiles\android-sdk
    • Java binary at: E:\MyProgramFiles\android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at E:\MyProgramFiles\android
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (2 available)
    • Redmi Note 5 Pro          • 60c198c9      • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

**Comment by rakeshlanjewarwork** [comment]
Also this fixes the issue 

https://stackoverflow.com/questions/52730515/flutter-error-java-lang-nosuchfielderror-prefer-highest-or-remote-version-no-fo

**Comment by rakeshlanjewarwork** [comment]
This is because of firebase plugin which uses the outdated versions of google play services & firebase apis

**Comment by escamoteur** [comment]
@timsneath  The gradle hack solves this but this has to be adressed

**Comment by timsneath** [comment]
Adding @bparrishMines to take a look.

**Comment by zoechi** [comment]
Seems new versions of the Firebase plugins were published yesterday.
Is this still an issue?

**Comment by rakeshlanjewarwork** [comment]
Verifying .......

**Comment by rakeshlanjewarwork** [comment]
Verified 👍  🥇 💯 👍  

### Yo! This issue has been fixed after Update.

**Comment by escamoteur** [comment]
I can confimr it works now although I had to uninstall the App after doing the package upgrade because I got some internbal Firebase Error

**Comment by escamoteur** [comment]
I fear I was a bit fast, after my App ran for some time I got this error again

```
E/AndroidRuntime( 7670): FATAL EXCEPTION: TokenRefresher
E/AndroidRuntime( 7670): Process: com.joinorcreate.mobile, PID: 7670
E/AndroidRuntime( 7670): java.lang.NoSuchFieldError: No field PREFER_HIGHEST_OR_REMOTE_VERSION_NO_FORCE_STAGING of type Lcom/google/android/gms/dynamite/DynamiteModule$VersionPolicy; in class Lcom/google/android/gms/dynamite/DynamiteModule; or its superclasses (declaration of 'com.google.android.gms.dynamite.DynamiteModule' appears in /data/app/com.joinorcreate.mobile-2/base.apk:classes2.dex)
E/AndroidRuntime( 7670): 	at com.google.android.gms.flags.FlagValueProvider.initialize(Unknown Source)
E/AndroidRuntime( 7670): 	at com.google.android.gms.flags.FlagRegistry.initialize(Unknown Source)
E/AndroidRuntime( 7670): 	at com.google.firebase.auth.internal.zzx.initialize(Unknown Source)
E/AndroidRuntime( 7670): 	at com.google.firebase.auth.internal.zzt.run(Unknown Source)
E/AndroidRuntime( 7670): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 7670): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7670): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 7670): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by escamoteur** [comment]
@bparrishMines

**Comment by rakeshlanjewarwork** [comment]
> I fear I was a bit fast, after my App ran for some time I got this error again
> 
> ```
> E/AndroidRuntime( 7670): FATAL EXCEPTION: TokenRefresher
> E/AndroidRuntime( 7670): Process: com.joinorcreate.mobile, PID: 7670
> E/AndroidRuntime( 7670): java.lang.NoSuchFieldError: No field PREFER_HIGHEST_OR_REMOTE_VERSION_NO_FORCE_STAGING of type Lcom/google/android/gms/dynamite/DynamiteModule$VersionPolicy; in class Lcom/google/android/gms/dynamite/DynamiteModule; or its superclasses (declaration of 'com.google.android.gms.dynamite.DynamiteModule' appears in /data/app/com.joinorcreate.mobile-2/base.apk:classes2.dex)
> E/AndroidRuntime( 7670): 	at com.google.android.gms.flags.FlagValueProvider.initialize(Unknown Source)
> E/AndroidRuntime( 7670): 	at com.google.android.gms.flags.FlagRegistry.initialize(Unknown Source)
> E/AndroidRuntime( 7670): 	at com.google.firebase.auth.internal.zzx.initialize(Unknown Source)
> E/AndroidRuntime( 7670): 	at com.google.firebase.auth.internal.zzt.run(Unknown Source)
> E/AndroidRuntime( 7670): 	at android.os.Handler.handleCallback(Handler.java:751)
> E/AndroidRuntime( 7670): 	at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime( 7670): 	at android.os.Looper.loop(Looper.java:154)
> E/AndroidRuntime( 7670): 	at android.os.HandlerThread.run(HandlerThread.java:61)
> ```

hey! can you post your pubspec.yaml dependency section

**Comment by rakeshlanjewarwork** [comment]
#firebase Dependencies
  cloud_firestore: any
  google_sign_in: ^3.2.1
  firebase_performance: any
  firebase: any
  firebase_remote_config: any
  firebase_auth: any
  flutter_facebook_login: any


try deleting pubspec.lock

**Comment by escamoteur** [comment]
Ok, seems to work, I was a victim ogf the version bump, now really on the latest version

**Comment by mk-dev-1** [comment]
Unfortunately, none of the solutions seem to work for me:

- Explicitly listed `implementation 'com.google.firebase:firebase-core:16.0.4'`
- Removed `pubspec.lock` and ran `flutter packages get`
- Ran `flutter clean`

Any other ideas?

**Comment by rakeshlanjewarwork** [comment]
Reopening the issue

**Comment by zoechi** [comment]
@rakeshlanjewarwork are you seeing this issue again as well?

**Comment by escamoteur** [comment]
Did you run also a Flutter package upgrade?

**Comment by rakeshlanjewarwork** [comment]
No , i don't seeing this issue, 

But @mk-dev-1 has the problem thats why i am reopening the issue .

**Comment by zoechi** [comment]
@rakeshlanjewarwork If it is now working for you it's unlikely a Flutter bug.

I'm going to close again.
Feel free to continue investigating and discussing here though.

@mk-dev-1 If it turns out to be another Flutter bug please create a new issue with
a properly filled out issue template with as much information as possible how to reproduce.

**Comment by mk-dev-1** [comment]
@escamoteur: Yes, I did. Sorry I did not mention it already. This got me to version 0.9.4 - not sure why it's not 0.10.0 though...

@zoechi: This is an existing project. I'll see if I can find out more...

**Comment by zoechi** [comment]
@mk-dev-1 for 0.10.0 you'd need to switch to `master` channel
```
flutter channel master
flutter doctor
```

**Comment by escamoteur** [comment]
Dev channel also works

**Comment by mk-dev-1** [comment]
Just saw that `flutter upgrade` shoudl also update packages, so not sure if that is going to be of help. But I'll give it a shot anyway. Also will try `flutter update-packages --force-upgrade`

@zoechi: Thanks, that's what I thought

**Comment by zoechi** [comment]
```
flutter update-packages --force-upgrade
```
is for updating dependencies in packages and examples included in Flutter and you should **not** use it except when you are trying to modify these packages yourself.

```
flutter packages upgrade
```
updates the dependencies in your project as far as the version constraints allow it.

**Comment by mk-dev-1** [comment]
Tried again `flutter clean`, `flutter upgrade` - no change.

Error message
```10-19 18:27:06.112 29127-29153/? E/AndroidRuntime: FATAL EXCEPTION: TokenRefresher
    Process: app.apax.monitor, PID: 29127
    java.lang.NoSuchFieldError: No field PREFER_HIGHEST_OR_REMOTE_VERSION_NO_FORCE_STAGING of type Lcom/google/android/gms/dynamite/DynamiteModule$VersionPolicy; in class Lcom/google/android/gms/dynamite/DynamiteModule; or its superclasses (declaration of 'com.google.android.gms.dynamite.DynamiteModule' appears in /data/app/app.apax.monitor-1/base.apk)
        at com.google.android.gms.flags.FlagValueProvider.initialize(Unknown Source)
        at com.google.android.gms.flags.FlagRegistry.initialize(Unknown Source)
        at com.google.firebase.auth.internal.zzx.initialize(Unknown Source)
        at com.google.firebase.auth.internal.zzt.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

flutter doctor -v
```
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /opt/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/apax/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.19.0

[✓] Connected devices (2 available)
    • SM A510F                  • 3300348d396223b5 • android-arm • Android 7.0 (API 24) (emulator)
    • Android SDK built for x86 • emulator-5554    • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by mk-dev-1** [comment]
Somehow I was stuck on `firebase_auth: ^0.5.20` - not sure I understand why. I now added 0.6.2+1 manually, and would imagine that that fixes it....

**Comment by kroikie** [comment]
@rakeshlanjewarwork

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/618. Any further collaboration will be done there.
