### ISSUE TITLE
It should be stated that you should not have a "~/.flutter" directory.

### ISSUE THREAD

**Issue by ndac-todoroki** [flutter/flutter#22842]
Environment: Linux (ubuntu 18.04 LTS)

The `flutter` command tries to create a `~/.flutter` directory automatically, and it aborts if that fails.
Following the instructions [here](https://flutter.io/setup-linux/), I tried to untar the Flutter SDK into my desired `~/.flutter`, and all the `flutter` commands did not work.

I think it should be stated the you should not have that directory.

**Comment by zoechi** [comment]
Duplicate of #25089

**Comment by zoechi** [comment]
This issue is older but #25089 has more activity

**Comment by zoechi** [comment]
Duplicate of #4674
