### ISSUE TITLE
Uploading many files using firebase storage

### ISSUE THREAD

**Issue by ronaldG19** [flutter/flutter#22840]
```
imageList<String> = <String>[ ];  //taking images from the phone and add their paths here.
var imageDataPath = { };

 Future<Null> _addImages(File file) async {
    StorageReference ref = FirebaseStorage.instance
        .ref()
        .child('Pictures')
        .child('${_primaryId()}'); //RandomNumberGenerator
    StorageUploadTask task = ref.putFile(file);
    Uri downloadUrl = (await task.future).downloadUrl;
    var url = downloadUrl.toString();
    imageDataPath['image${i + 1}'] = url;
i++;
  }
//uploading images
void uploadDetails() async {
    for (var pic in imageList) {
      await _addImages(File(pic));
    }
  }
```

**When you upload 4 images you find a pile of them uploaded (10-12) in firebase storage**
What is the problem?

Flutter Doctor:
[✓] Flutter (Channel beta, v0.8.2, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] Connected devices (1 available)

**Comment by kroikie** [comment]
@ronaldG19

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/619. Any further collaboration will be done there.
