### ISSUE TITLE
FieldPath

### ISSUE THREAD

**Issue by rayjadore** [flutter/flutter#22849]
i think  FieldPath is missing in flutter firrestore, so please i think its an important thing that should not be left out the current stage of flutter. thanks

**Comment by creativecreatorormaybenot** [comment]
You can just use `__name__` as [described here](https://stackoverflow.com/a/52469844/6509751).

**Comment by alfiepoleon** [comment]
@creativecreatorormaybenot how would I run such a query in flutter `admin.firestore.FieldPath.documentId()`?

**Comment by creativecreatorormaybenot** [comment]
@alfiepoleon I updated the answer. You just use it as a `String`.

**Comment by kroikie** [comment]
@rayjadore

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/617. Any further collaboration will be done there.
