### ISSUE TITLE
type 'MappedListIterable<String, Project>' is not a subtype of type 'List<Project>'

### ISSUE THREAD

**Issue by akeating** [flutter/flutter#22841]
The following code appears to type-check but fails with `flutter run`:
```
final List<Project> projects = ['a', 'b', 'c'].map((name) {
    return Project(name);
});
```
and `Project`:
```
class Project {
  final String name;
  Project(this.name);
}
```

The resulting exception is:
```
I/flutter (13088): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY I/flutter (13088): The 
following assertion was thrown building Builder:
I/flutter (13088): type 'MappedListIterable<String, Project>' is not a 
subtype of type 'List<Project>'
```

```
$ flutter analyze
Analyzing flutter_app...                                         
No issues found! (ran in 1.9s)
```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.9.7-pre.76, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.27.2)
[✓] Connected device (1 available)

• No issues found!
```

I have attached the default flutter project, modified to illustrate the problem
[main.dart.zip](https://github.com/flutter/flutter/files/2458648/main.dart.zip)

Expected: Since the code appears to type-check, the code should not fail at run-time.
Actual: The code fails at run-time.

I know that adding `.toList()` gets around this. The problem is that code that the ecosystem thinks is valid fails unexpectedly at run-time. 

I'm thinking the code should fail to type-check in this case, but interested to hear of another perspective.

**Comment by zoechi** [comment]
Can you please try adding to your `analysis_options.yaml`

```
analyzer:

  strong-mode:
    implicit-casts: false
```
and check if the error is reported statically.

**Comment by akeating** [comment]
@zoechi this additional option did not appear to make any difference.

**Comment by zoechi** [comment]
It's weird. I'd suggest to move the issue over to https://github.com/dart-lang/sdk
I can reproduce in pure command-line Dart without Flutter.
