### ISSUE TITLE
TextField autofill for SMS verification messages

### ISSUE THREAD

**Issue by pdefuns** [flutter/flutter#22858]
Is it planned to support autofill possibility for verification messages in TextFields?

[How to show verification code suggestion on keyboard from Message](https://stackoverflow.com/questions/50772090/how-to-show-verification-code-suggestion-on-keyboard-from-message) (iOS 12 with .oneTimeCode)

**Comment by Xavjer** [comment]
As this feature is currently only supported with the iOS `UITextField` and the system keyboard, this probably cannot be implemented currently from my point of view, as flutter draws it's elements itself and does not rely on native components.

**Comment by jaumard** [comment]
Did you try https://pub.dartlang.org/packages/sms_autofill ? :)

**Comment by stefandevo** [comment]
> Did you try https://pub.dartlang.org/packages/sms_autofill ? :)

The package is Android only

**Comment by jaumard** [comment]
@stefandevo for me it works also on iOS (at least at some point it did^^)

**Comment by skela** [comment]
This was implemented a while ago (https://github.com/flutter/flutter/issues/4818) , but I think it seems quite broken at the moment. Not only is it unreliable, but the suggestion bar somehow gets placed on top of the Keyboard, meaning its hard to see and click.

![215895_image-2019-04-23-07-59-29-059](https://user-images.githubusercontent.com/58268/60721563-a827bf80-9f2e-11e9-8c03-88c3b5a00e44.png)

**Comment by locpt** [comment]
@jaumard Testing with your example and I tried to request SMS OTP code from Firebase Phone Auth, but it's not working. Did I miss something?

**Comment by jaumard** [comment]
@locpt firebase phone auth is not compliant with this package, as the readme state:  SMS must `End with an 11-character hash string that identifies your app ` and you can't do that with firebase phone auth. That's why it doesn't work

**Comment by locpt** [comment]
@jaumard Is there any ways to archive like your package `sms_autofill` for Firebase Phone Auth? I don't want to request SMS permission from the user to auto-fill the OTP code. It sounds weird. I have tried some packages or research so far but seem like no way to archive that requirement. I wanna receive your recommendation.

**Comment by jaumard** [comment]
No there is no way, but you don't need SMS permission to auto-fill the OTP code if you follow the instructions of auto_fill package.

**Comment by rfitz123** [comment]
```
@locpt firebase phone auth is not compliant with this package, as the readme state: SMS must End with an 11-character hash string that identifies your app and you can't do that with firebase phone auth. That's why it doesn't work
```

Does this mean using firebase to authenticate users makes this package impossible to use? I'm confused whether firebase phone auth is different from firebase auth.

**Comment by enzobonggio** [comment]
So firebase is the problem?

**Comment by ClebsonDantasUchoa** [comment]
Two years later, now the flutter has support for autofill on ios, but i couldn't run on ios

**Comment by Superkramar** [comment]
But it is not works properly. Sms code above keyboard does not hide when I focuse on another TextField ( on the other screen ). And I ever can't disable autosuggestion by myself, with my keyboardType =(

**Comment by LongCatIsLooong** [comment]
OTP works for me on iOS: 
![image](https://github.com/flutter/flutter/assets/31859944/d42e5769-3cb8-4da3-8866-2c1abc5ff148)
