### ISSUE TITLE
On Android when there are multiple flavors and no --flavor flag is specified then use a default one

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#22856]
On Android, when there are multiple flavors defined, and the user runs the app but does not specify a value for the `--flavor` flag then the following error is shown:

> You must specify a --flavor option to select one of them.

This is implemented like that here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L342

This makes it so that everytime we have to specifiy a value for `--flavor`.
I would propose when the flag is not specified to just default to the first one.
This will make it faster to start your Flutter app, not having to write `--flavor _flavor_` everytime.

**Comment by matthewcook333** [comment]
Also running into this issue, it is a pain to not be able to just run with default commands. Would be nice to have a default flavor.

**Comment by royorange** [comment]
+1  Also face the same issue.

**Comment by bradyt** [comment]
@cmwarrington, do you know if flutter should be able to move forward on this? I saw your involvement at the following commits, and made a naive guess you might have an idea for this.

- https://android.googlesource.com/platform/tools/base/+/1765a36f717040b4df061ca78019ce8bba4933e5
- https://android.googlesource.com/platform/tools/adt/idea/+/48dd5e4bee7a79c8f3456f391bb706bf49186f04

**Comment by mewadaArvind** [comment]
Also face the same issue. please give a answer this question.

**Comment by hieuseesaa** [comment]
Hello. I have the same problem.
I fixed it the following way
open **Edit Configurations** -> **build flavor** -> enter flavor name (example :  develop)

**Comment by bradyt** [comment]
@hieuseesaa I am looking around my terminal for "Edit Configurations", and I'm not seeing it. Which terminal are you using?

**Comment by erabti** [comment]
Any work around for this? This is really needed for us.

**Comment by msmaromi** [comment]
in vscode you can setup debug configuration
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter Dev",
            "request": "launch",
            "args": ["--flavor", "development"],
            "type": "dart"
        }
    ]
}
```

**Comment by hieuseesaa** [comment]
@erabti If you use Android Studio. You can try my way.
open Edit Configurations -> build flavor -> enter flavor name (example : develop)

**Comment by nazdream** [comment]
Does anybody know how to set default flavor in Bitrise? I am getting the same error when Bitrise is trying to build the app, and I can't find a way to set flavor.

**Comment by hieuseesaa** [comment]
@nazdream 
--debug --flavor develop -t lib/main_develop.dart 

Try it

**Comment by nashihu** [comment]
I'm looking forward until it solved..

**Comment by bobatsar** [comment]
I have the same issue and tried the suggested solution in 
https://stackoverflow.com/a/60197203/3607358
which references the bug https://issuetracker.google.com/issues/36988145

but I cant make it work. Does anybody know how to use this with flutter?

This is especially annoying when using tests e.g. widgetTests. Every time I want to run a test it needs the --flavor flag

**Comment by hieuseesaa** [comment]
@bobatsar 
If you use Android studio. Try it.
<img width="1071" alt="Screen Shot 2021-09-23 at 15 22 29" src="https://user-images.githubusercontent.com/20986905/134475687-dcc0c3a2-8fa4-42e7-afcc-3f4eccbf4755.png">

**Comment by bobatsar** [comment]
@hieuseesaa for sure I can provide the flavor e.g. in Android Studio or via commandline but I would like that gradle chooses a default one if none is specified.

**Comment by aismaniotto** [comment]
+1

**Comment by mrRedSun** [comment]
Also agree to this one, would be nice if the default flavor could be specified as well

**Comment by pattobrien** [comment]
> ... **especially** when Flutter gives cryptic error messages that doesn't suggest the flavor is missing?

Here's the cryptic message in question:

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
main.dart:1
Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under /Users/pattobrien/dev/fine_designs/template/src/frontend/build, but the tool couldn't find it.
Exited
```
This is not a helpful message in the slightest, especially because there **is** an apk file in that directory, it's just not the name expected.

If a default flavor cannot be selected, then it would be helpful to at least mention what the expected file name is, so that a user can easily spot the difference between the file that does exist vs. the file that the flutter tool is expecting. This seems like a quick win IMO.

**Comment by vietstone-ng** [comment]
Please support this

**Comment by giljulio** [comment]
Not a default, but if you rather make the issue more explicit - you can use the following code to fail the build when it's not specified

```
gradle.taskGraph.whenReady { taskGraph ->
    if (!project.hasProperty('android.injected.build.model') // ensure we're not in sync mode
        && taskGraph.allTasks.any { it.name.toLowerCase().equals("assembledebug") || it.name.toLowerCase().equals("assemblerelease") }) {
        throw new Exception("Please specify a flavor with --flavor argument")
    }
}
```

**Comment by SilenceCodder** [comment]
> https://stackoverflow.com/a/60197203/3607358



> > ... **especially** when Flutter gives cryptic error messages that doesn't suggest the flavor is missing?
> 
> Here's the cryptic message in question:
> 
> ```
> Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
> main.dart:1
> Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under /Users/pattobrien/dev/fine_designs/template/src/frontend/build, but the tool couldn't find it.
> Exited
> ```
> 
> This is not a helpful message in the slightest, especially because there _**is**_ an apk file in that directory, it's just not the name expected.
> 
> If a default flavor cannot be selected, then it would be helpful to at least mention what the expected file name is, so that a user can easily spot the difference between the file that does exist vs. the file that the flutter tool is expecting. This seems like a quick win IMO.

Does this error mean that it's missing a Flavour name?
Can't the project run by default using flutter run?

**Comment by slaci** [comment]
I just bumped into this and with flutter 3.16.x (and gradle 8.2) flutter picks a default flavor (I don't know since which version).

By default gradle sorts the flavor names in alphabetical order and picks the first one. Seems like flutter only supports this.

In Gradle it is possible to mark a flavor as default, but from my tests flutter ignores it:

```groovy
flavorDimensions=["version"]
    productFlavors {
        b {
            getIsDefault().set(true)
            dimension "version"
        }
        a {
            dimension "version"
        }
    }
```

When defining this I would expect `b` as the default, but when running the app with `flutter run` then it picks `a` instead. I have tried just `isDefault true` instead, but without luck. So basically prefixing the default flavor with `a` should work currently.

Can anyone confirm this behavior?

**Comment by ChaseGuru** [comment]
**Why setting a default doesn't work**

Flutter seems to by default do all flavors.
```
    productFlavors {
        dev {
            dimension "default"
            resValue "string", "app_name", "Myapp Dev"
            applicationIdSuffix ".dev"
        }
        live {
            dimension "default"
            resValue "string", "app_name", "Myapp"
            applicationIdSuffix null
        }
        beta {
            dimension "default"
            resValue "string", "app_name", "Myapp Beta"
            applicationIdSuffix ".beta"
        }
    }
```

```bash
> rm -r ./build/app/outputs/flutter-apk
> flutter build apk
..snip..
Gradle build failed to produce an .apk file. It's likely that this file was generated under /path/to/project/build, but the tool couldn't find it.
> ls -la build/app/outputs/flutter-apk
-rw-rw-r-- 1 chase chase 29548328 May  9 20:21 app-dev-release.apk
-rw-rw-r-- 1 chase chase 29548326 May  9 20:21 app-beta-release.apk
-rw-rw-r-- 1 chase chase 29548300 May  9 20:21 app-live-release.apk
```

Contrarily though, appbundle seems to only produce one.

flutter run also fails for me without a flavor

**Comment by hasanm08** [comment]
can you please merge this PR? #147968

**Comment by andrewkolos** [comment]
https://github.com/flutter/flutter/pull/147968 will allow users to specify a `default-flavor` in their pubspec and should be available in the next stable release (whatever comes after 3.22). I believe this satisfies the primary concern/request of this issue.

https://github.com/flutter/flutter/issues/139286 tracks the issue of the confusing error message shown when an Android-enabled project has flavors configured but `--flavor` is not provided.
