### ISSUE TITLE
Provide links between dart:ui classes and their corresponding classes in higher layers

### ISSUE THREAD

**Issue by josvos** [flutter/flutter#22859]
The documentation at https://docs.flutter.io/flutter/dart-ui/TextStyle-class.html is incomplete.  The `TextStyle` class seems to have many more methods, like `apply`, `copyWith`, and `merge`.

**Comment by goderbauer** [comment]
You are probably looking for the TextStyle in the material package, which is documented here: https://master-docs.flutter.io/flutter/painting/TextStyle-class.html. That one has all the methods you're looking for.

We should probably provide links in the docs from one to the other. I am re-purposing the bug for that.

**Comment by Piinks** [comment]
Is there potentially another `{@tool ...}` opportunity here to achieve this?

**Comment by goderbauer** [comment]
What would that tool do? (I suspect that linking one to the other will be a one-off work task)
