### ISSUE TITLE
HTTP manipulating complete request / get raw response

### ISSUE THREAD

**Issue by flddr** [flutter/flutter#22861]
Hi,

i need to manipulate HTTP requests before they are sent; i want no manipulate the whole request (headers, data) and i think, all this could be possible starting here at the docs: https://docs.flutter.io/flutter/package-http_http/BaseClient-class.html

Is it possible? I think.

But for getting **raw** response as string/byte[] to extract all needed details, where should i start? I am not sure. I want to work with the response like a normal response and i want to work besides with all headers of this response to check exactly whats in - not consumed already, only **raw response string/byte[]**

Can you give me the right starting points?

**Comment by zoechi** [comment]
You can do in Flutter what `dart:io` can do (if not create an issue).
Your issue should be filed in https://github.com/dart-lang/sdk, but better first check on StackOverflow if someone can answer your question.

Being a bit more specific what exactly package `http` or `dart:io` don't allow you to do that "manipulating complete request" would allow you to do, and why you think you need that, would probably help to get a good answer.

**Comment by flddr** [comment]
@zoechi whats the problem to answer this question? Thats an issue for help me writing my app. Thats a topic in your issues

**Comment by flddr** [comment]
As you can see i am talking about your docs. So, i am not interested running around the world

**Comment by flddr** [comment]
And there is nothing to explain on *manipulating the request*. It contains of headers and data. I want to modify it. Like thousands of tools are doing.

The same for **raw response as string/byte[]** - thats clear, too.

**Comment by zoechi** [comment]
I don't even understand what the problem is and you don't seem to be interested to explain it. 
Every method to send HTTP requests allows you to set header and data. 
StackOverflow is the right place to ask this kind of question.

**Comment by flddr** [comment]
@zoechi LOL - you simply closed my issue - where is your interest? Because you do not know the answer about the raw response in gitter?

Go home

**Comment by zoechi** [comment]
Because this is not the right place for your question.
It tried to point you in the right direction as far as the information you provided allowed.

Please also check https://flutter.io/design-principles/#code-of-conduct
