### ISSUE TITLE
iOS caret fidelity 

### ISSUE THREAD

**Issue by xster** [flutter/flutter#22879]
Compared to native iOS 12
- [x] blink speed is a bit faster than it should
- [x] blink opacity actually should fade in and fade out
- [x] the caret height should extend as far down as the lowest descenders and higher than the highest ascenders
- [x] caret corners should be rounded
- [x] the caret position horizontally is a bit off. We're too far into the previous glyph.

**Comment by zoechi** [comment]
Related #20694

**Comment by xster** [comment]
Note to future self: use https://github.com/flutter/flutter/issues/21997#issuecomment-432850734

**Comment by crossle** [comment]
OOPS, the fade in and out cursor make the macOS flutter so high CPU. At least 30% CPU...
