### ISSUE TITLE
Add a skia screeshot option to the resident runner

### ISSUE THREAD

**Issue by xster** [flutter/flutter#22877]
Currently to get a skia screenshot, one has to flutter run, then disconnect from the vm service or open a new terminal and then invoke `flutter screenshot --type=skia --observatory-port=<the port from flutter run>` which is cumbersome. Would be nice to add a key such as "k" to the vm service to get a skia screenshot.

**Comment by Hixie** [comment]
This seems like a very esoteric feature that most people wouldn't know what to do with. If you really want this, then please implement it. :-)
