### ISSUE TITLE
Support "in List"/"Out of List" announcements on Android

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#22876]
When moving the accessibility focus into a "List" of items, an announcement is generated describing the total number of list items. When first moving the accessibility focus out of a "List" of items, "out of list" (or another localized phrase) is generated.

We might need to tweak the semantics or accessibility bridge to ensure these announcements are generated, but we can probably reuse the information needed to support scroll semantics.  To figure out the required parameters we can talk to Android a11y folks or consult the TalkBack source.

**Comment by alanrussian** [comment]
We have a horizontally scrollable `ListView` within a vertically scrollable `ListView`. Without this issue being fixed, I don't think our users would realize that they're in the horizontal `ListView`. They wouldn't know they could scroll horizontally.

**Comment by jonahwilliams** [comment]
I don't see how this is related to horizontal lists

**Comment by alanrussian** [comment]
I guess I'm saying the problem is worse with nested lists. We're introducing a nested list in our app.

In the home screen of our application, we have a vertical list view. I think our users are accustomed to this. We're now adding a horizontal list view as one of the items in the vertical list view. If I were to focus on an item in the horizontal list with my eyes closed, I would have no context that I could scroll horizontally.

**Comment by jonahwilliams** [comment]
Ahh okay, thank you for the details here. @dnfield would you be willing to take a look at this? 

These announcements are generated here under "collection_transition": https://github.com/google/talkback/blob/e69d4731fce02bb9e69613d0e48c29033cad4a98/compositor/src/main/res/raw/compositor.json#L704

We'll need to figure out what the expected structure of the accessibility nodes are so that we go down the right path here

**Comment by dnfield** [comment]
I'm close on this one.

I will say that working with this myself, I would probably find it confusing as a vision impaired user to navigate nested lists.  We can make the announcements say you're in a list, but it might be especially confusing if the lists end up having the same number of items.
