### ISSUE TITLE
FR: BottomNavigationBar fixed with no titles

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#22882]
Would love to be able to use BottomNaviationBar fixed but without titles.

See Twitter for an example.

![img_79014a936049-1](https://user-images.githubusercontent.com/666539/46699282-547a8680-cbe7-11e8-8251-24838c695d0f.jpeg)

**Comment by dooboolab** [comment]
@lukepighetti Got `PR` for you.

**Comment by jonahwilliams** [comment]
I don't believe material bottom navigation bars are spec'd for not having a title, nor would those meet a11y requirements without them.  cc @willlarche 

Not that there couldn't be a bottom navigation without titles, but I don't think it belongs in the material library if it's not part of the spec.

**Comment by lukepighetti** [comment]
How do we do a PR on the spec? 😇

**Comment by willlarche** [comment]
It's definitely encouraged to have the Material library be a superset of features in the guidelines! But we should not add this particular feature as we believe it creates a worse a11y experience.

**Comment by lukepighetti** [comment]
This request is not outside the mainstream for app design and I believe it is quite reasonable even though it is omitted from Material spec. I would argue that the shifting icons are less accessible because they move position and break procedural knowledge

![nav bar](https://user-images.githubusercontent.com/666539/46842223-6f412c80-cd9a-11e8-9429-ae68f898675d.jpg)

**Comment by jonahwilliams** [comment]
I don't think I should be the arbiter of whether or not this meets the guidelines for a11y. We can provide caveats and documentation but ultimately we're not the arbiters of how users develop apps.  I also don't want to create a situation where we have a lot of customizations supported in the framework which have to be documented with `"Don't use this if ..."`.

Some potential action items:

- Can we abstract the concept of the bottom nav into `widgets`? 
Though detangling the material specific properties might be difficult. Then we could have a more generic view which just took a Widget for the tabs.
- Can a bottom nav bar without titles (material or not) be accessible via other properties or sufficient labels?

**Comment by lukepighetti** [comment]
I was imagining a scenario where this collapsed the padding under the icons.

```
      BottomNavigationBarItem(
        title: null,
        icon: Icon(Icons.notifications),
      ),
```

From the standpoint of culture around these decisions, all I ask is that you guys don't "Internet Explorer" native app development.

**Comment by willlarche** [comment]
Ah! Well that’s different. The fastest way for that to be solved is for you to put in a PR. Otherwise this will be triaged and prioritized for a later date.

**Comment by dooboolab** [comment]
@willlarche I've done the `PR` for this. I needed this feature either. Thanks.

**Comment by willlarche** [comment]
@dooboolab , I think @lukepighetti is describing a motion issue. Should probably be in another issue.

@lukepighetti Could you write up a new issue since you understand it?

**Comment by willlarche** [comment]
Ok! We have plan that we believe will satisfy our requirements:
- Keep the title strings mandatory for the `Semantics` system to read.
- Make titles something that's shown by default but hideable. 
  - When hidden, the layout responds as if they are not there at all (as opposed to now where you pass `""` and still have room for titles.)

@dooboolab , I'll add this feedback to your PR too.

@lukepighetti , please create a new ticket, if you haven't already, for the layout problems

**Comment by lukepighetti** [comment]
Thanks Will, feel free to close this issue whenever you feel it is necessary

**Comment by ankitchouhan** [comment]
You guys can also use this as

` BottomNavigationBarItem(
          icon: Icon(
            Icons.card_giftcard,
          ),
          title: SizedBox.shrink(),
        )`

i.e set title to 
> SizedBox.shrink() 

And you can get rid of those titles.

Hope this helps @lukepighetti

**Comment by ranggalb** [comment]
> You guys can also use this as
> 
> ` BottomNavigationBarItem( icon: Icon( Icons.card_giftcard, ), title: SizedBox.shrink(), )`
> 
> i.e set title to
> 
> > SizedBox.shrink()
> 
> And you can get rid of those titles.
> 
> Hope this helps @lukepighetti

Great job!! :D

**Comment by AtillaPehlivan** [comment]
try `showSelectedLabels: false,
            showUnselectedLabels: false`  instead of unused title widget
@lukepighetti 

> > You guys can also use this as
> > ` BottomNavigationBarItem( icon: Icon( Icons.card_giftcard, ), title: SizedBox.shrink(), )`
> > i.e set title to
> > > SizedBox.shrink()
> > 
> > 
> > And you can get rid of those titles.
> > Hope this helps @lukepighetti
> 
> Great job!! :D
