### ISSUE TITLE
update_dart_sdk.ps1 should prepend the module name for Expand-Archive

### ISSUE THREAD

**Issue by andyp60** [flutter/flutter#22896]
## Steps to Reproduce

```
F:\flutter\bin>F:\flutter\bin\flutter upgrade
```

## Logs

```
Checking Dart SDK version...
VERBOSE: [10/9/2018 9:02:45 PM] Initialize Transcript
Transcript started, output file is C:\Users\Andy\Documents\WindowsPowerShell\Transcripts\PSLOG_09-10-2018.txt
Downloading Dart SDK from Flutter engine 74625aed323d04f2add0410e84038d250f51b616...
Unzipping Dart SDK...
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
At F:\flutter\bin\internal\update_dart_sdk.ps1:65 char:32
+     Expand-Archive $dartSdkZip -DestinationPath $cachePath
```
-->
I edited `update_dart_sdk.ps1` replacing `-DestinationPath with -OutputPath`
```
    #Expand-Archive $dartSdkZip -DestinationPath $cachePath
	Expand-Archive $dartSdkZip -OutputPath $cachePath
```

```
F:\flutter\bin>F:\flutter\bin\flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.9.4 at F:\flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Andy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!

F:\flutter\bin>
```

**Comment by zoechi** [comment]
The title says 

> via Android Studio

steps to reproduce says

> F:\flutter\bin>F:\flutter\bin\flutter upgrade

What are the actual steps to reproduce?

**Comment by andyp60** [comment]
Yes I should have been more clear. 

 

Android Studio 3.2

Build #AI-181.5540.7.32.5014246, built on September 17, 2018

JRE: 1.8.0_152-release-1136-b06 amd64

JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Windows 10 10.0

PS C:\Users\Andy> $psversiontable

 

Name                           Value

----                           -----

PSVersion                      5.1.17134.228

PSEdition                      Desktop

PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}

BuildVersion                   10.0.17134.228

CLRVersion                     4.0.30319.42000

WSManStackVersion              3.0

PSRemotingProtocolVersion      2.3

SerializationVersion           1.1.0.1

 

 

While in android studio, I received a notice that there was a flutter upgrade available.  In terminal pane I executed the following: 

Microsoft Windows [Version 10.0.17134.345]

(c) 2018 Microsoft Corporation. All rights reserved.

 

C:\Users\Andy\Documents\Android\flutter\flutter_firebase\flutter_firebase>f:

F:\>cd flutter

F:\flutter>cd bin

F:\flutter\bin> 

F:\flutter\bin>flutter upgrade

 

 

As noted the resolution was to update the  update_dart_sdk.ps1 file in <flutterhome>/bin/internal by

Changing line 65:

                Expand-Archive $dartSdkZip -DestinationPath $cachePath

To:

                Expand-Archive $dartSdkZip -OutputPath $cachePath

                

 

 

 

Cheers

 

Andy ( Andre ) Paradis

**Comment by zoechi** [comment]
and `flutter upgrade` worked without errors, right?

**Comment by andyp60** [comment]
Correct flutter upgrade worked without errors.

 

Cheers

 

Andy ( Andre ) Paradis

**Comment by zoechi** [comment]
@devoncarew

**Comment by TheGU** [comment]
I just found this problem recently. After some investigation, it's because Pscx module in powershell. So,

If you install Pscx module in powershell, it will overwrite alias for command Expand-Archive to use from Pscx instead of from Powershell. Two command work the same but Pscx use -OutputPath however Powershell use -DestinationPath.

For quick fix just change:
https://github.com/flutter/flutter/blob/a226c0f0d9f5d699a3d706fd9060edf6da45b13b/bin/internal/update_dart_sdk.ps1#L65
from 
`Expand-Archive $dartSdkZip -DestinationPath $cachePath`
to 
`Expand-Archive $dartSdkZip -OutputPath $cachePath`

Or it should specific which module to use as suggested in [PowerShell issue#52](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/52#issuecomment-374022845)
`Microsoft.PowerShell.Archive\Expand-Archive $dartSdkZip -DestinationPath $cachePath`
