### ISSUE TITLE
CircleAvatar image doesn't display in Android Emulator

### ISSUE THREAD

**Issue by fusilin** [flutter/flutter#22895]
Figure 1： my code, 
Figure 2：the problem，the second and third picture is not displayed,
gif 3：another page, I found that the image was covered by the page and could not be scrolled

the link can't work for me [https://github.com/flutter/flutter/commit/0b389fc92e6cd81c4207aa3efcfc3bbf8251c65c](url)
my Flutter version: 0.8.2

![1](https://user-images.githubusercontent.com/33337793/46710116-1cbc1f00-cc79-11e8-944d-4a7c6ba4b475.png)
![2](https://user-images.githubusercontent.com/33337793/46710125-22b20000-cc79-11e8-8ab7-2c9b8b8c4e6e.png)
![3](https://user-images.githubusercontent.com/33337793/46710127-25145a00-cc79-11e8-9bba-7bd7f7029708.gif)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by fusilin** [comment]
> What emulator are you using? Have you tried on a different device or emulator?

i'm trying

**Comment by fusilin** [comment]
> What emulator are you using? Have you tried on a different device or emulator?

just now, I have tried device: ONE PLUS 3T and xiaomi 5, CircleAvatar image can work.
but the two emulator in the image below, CircleAvatar image cannot be displayed.

**Comment by fusilin** [comment]
> What emulator are you using? Have you tried on a different device or emulator?

just now, I have tried device: ONE PLUS 3T and xiaomi 5, CircleAvatar image can work.
but the two emulator in the image below, CircleAvatar image cannot be displayed.
![5](https://user-images.githubusercontent.com/33337793/46720388-f90dce80-cca2-11e8-8f89-6991452d2c42.png)

**Comment by zoechi** [comment]
Thanks a lot for checking!

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/22952#issuecomment-428992385 might be worth a try

**Comment by TahaTesser** [comment]
This isn't reproduced on 

<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.19041.84], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\Code\flutter_stable
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Code\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: CircleAvatar(
          radius: 50.0,
          backgroundImage: NetworkImage("https://i.imgur.com/C5xknx8.png"),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
