### ISSUE TITLE
Google Maps Flutter plugin won't download

### ISSUE THREAD

**Issue by Mroles** [flutter/flutter#22891]
I am building an app that requires google maps, however when I add it as a dependency(along with the github url and path), it gives me this error:

[practice_2] flutter packages get
Running "flutter packages get" in practice_2...
Could not find a file named "packages/google_maps_flutter/pubspec.yaml" in git://github.com/flutter/plugins 5ab9e70727d858def3a586db7fb98ee580352957.
pub get failed (1)
exit code 1

**Comment by ronaldG19** [comment]
You can opt MapBox,after all Google Maps will have you pay to emulate.
I encountered the error too.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the `dependencies:` section of your `pubspec.yaml`

**Comment by zoechi** [comment]
I don't see any maps from git in your dependencies.

**Comment by Mroles** [comment]
I removed it after the issues...should i add it again?

**Comment by Mroles** [comment]
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_sign_in:
  firebase_auth:
  cloud_firestore:
  shared_preferences:
  image_picker:
  firebase_storage:
  fluttertoast:
  cached_network_image: 
  intl:
  photo_view:
  datetime_picker_formfield:
  map_view:
  location:
  google_maps_flutter:
   git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter


And the output of flutter packages get

[practice_2] flutter packages get
Running "flutter packages get" in practice_2...                 
Could not find a file named "packages/google_maps_flutter/pubspec.yaml" in git://github.com/flutter/plugins f37c235c32fc15babe6dc7b7bc2ee4387e5ecf92.

pub get failed (1)
exit code 1


And the output of flutter doctor -v

[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at C:\Users\asdkm\Downloads\Compressed\flutter_windows_v0.7.3-beta\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\asdkm\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • Samsung Galaxy S8, 8 0, API 26, 1440x2960 • 192.168.42.103:5555 • android-x86 • Android 8.0.0 (API 26)

• No issues found!

**Comment by zoechi** [comment]
Please try running 
```
flutter packages pub cache repair
```
or delete
```
~/.pub-cache/git/plugins-*
```
and then run `flutter packages get` again.

**Comment by zoechi** [comment]
@Mroles any progress?

**Comment by nak411** [comment]
I had the same problem and ran `flutter packages pub cache repair` which did not work but removing cache does work
```
{path-to-flutter-sdk}/.pub-cache/git/plugins-*
```

**Comment by mulenatni** [comment]
> I don't see any maps from git in your dependencies.

thanks my problem solved
