### ISSUE TITLE
UnderlineInputBorder change textfield underline color doesn't work

### ISSUE THREAD

**Issue by KinsomyJS** [flutter/flutter#22894]
i have a form use textfield，then implement the textfield，but the default edittext underline color is blue(flutter primary color), and  there is a border property in it，i want to set the underline color with Colors.White, but it doesn't work, i think it is  a bug.
```dart
                          child: new TextField(
                            maxLines: 1,
                            style: TextStyle(
                                fontSize: 16.0, color: Colors.white), //输入文本的样式
                            decoration: InputDecoration(
                              //doesn't work
                              border: new UnderlineInputBorder(
                                  borderSide: new BorderSide(
                                      color: Colors.white,
                                      style: BorderStyle.solid)),
                              hintText: '查询其他城市',
                              hintStyle: TextStyle(
                                  fontSize: 14.0, color: Colors.white),
                              prefixIcon: new Icon(
                                Icons.search,
                                color: Colors.white,
                                size: 20.0,
                              ),
                            ),
                          ),

```

so i have no choice but to wrap the textfield with Theme, it works, but it looks so strange.
```dart
                        child: new Theme(
                          data: theme.copyWith(primaryColor: Colors.white),
                          child: new TextField(
                            maxLines: 1,
                            style: TextStyle(
                                fontSize: 16.0, color: Colors.white), //输入文本的样式
                            decoration: InputDecoration(
//                              //bug doesn't work
//                              border: new UnderlineInputBorder(
//                                  borderSide: new BorderSide(
//                                      color: Colors.white,
//                                      style: BorderStyle.solid)),
                              hintText: '查询其他城市',
                              hintStyle: TextStyle(
                                  fontSize: 14.0, color: Colors.white),
                              prefixIcon: new Icon(
                                Icons.search,
                                color: Colors.white,
                                size: 20.0,
                              ),
                            ),
                          ),
                        )),

```

**Comment by unain** [comment]
see the #19694

**Comment by zoechi** [comment]
Merging with #17717

**Comment by AllenNow** [comment]
> i have a form use textfield，then implement the textfield，but the default edittext underline color is blue(flutter primary color), and there is a border property in it，i want to set the underline color with Colors.White, but it doesn't work, i think it is a bug.
> 
> ```dart
>                           child: new TextField(
>                             maxLines: 1,
>                             style: TextStyle(
>                                 fontSize: 16.0, color: Colors.white), //输入文本的样式
>                             decoration: InputDecoration(
>                               //doesn't work
>                               border: new UnderlineInputBorder(
>                                   borderSide: new BorderSide(
>                                       color: Colors.white,
>                                       style: BorderStyle.solid)),
>                               hintText: '查询其他城市',
>                               hintStyle: TextStyle(
>                                   fontSize: 14.0, color: Colors.white),
>                               prefixIcon: new Icon(
>                                 Icons.search,
>                                 color: Colors.white,
>                                 size: 20.0,
>                               ),
>                             ),
>                           ),
> ```
> 
> so i have no choice but to wrap the textfield with Theme, it works, but it looks so strange.
> 
> ```dart
>                         child: new Theme(
>                           data: theme.copyWith(primaryColor: Colors.white),
>                           child: new TextField(
>                             maxLines: 1,
>                             style: TextStyle(
>                                 fontSize: 16.0, color: Colors.white), //输入文本的样式
>                             decoration: InputDecoration(
> //                              //bug doesn't work
> //                              border: new UnderlineInputBorder(
> //                                  borderSide: new BorderSide(
> //                                      color: Colors.white,
> //                                      style: BorderStyle.solid)),
>                               hintText: '查询其他城市',
>                               hintStyle: TextStyle(
>                                   fontSize: 14.0, color: Colors.white),
>                               prefixIcon: new Icon(
>                                 Icons.search,
>                                 color: Colors.white,
>                                 size: 20.0,
>                               ),
>                             ),
>                           ),
>                         )),
> ```

same

**Comment by hehuapei** [comment]
see the #19694
i use enabledBorder, it works!

**Comment by patelkrunal78** [comment]
Maybe This Can Help You Here[https://icetutor.com/question/flutter-how-to-change-textfield-hint-color](url)
