### ISSUE TITLE
[plugins/firebase_messaging] proguard warnings (build failure)

### ISSUE THREAD

**Issue by pboos** [flutter/flutter#22892]
Without any changes to firebase plugins (or any other dependencies for that matter) my build started failing with proguard. It seems related to an updated firebase-iid. The new build used firebase-iid 17.0.3 instead of 17.0.0 from previous build. I guess this must be the reason for the problem. Not sure though why it updated the version (guessing because somewhere in the flutter dependencies it uses 17.0.+).

All my firebase dependencies are on the newest version (see below). So I would expect it to work correctly.

```
Warning: com.google.firebase.messaging.FirebaseMessaging: can't find referenced method 'boolean zzq()' in program class com.google.firebase.iid.FirebaseInstanceId
Warning: com.google.firebase.messaging.FirebaseMessagingService: can't find referenced method 'com.google.android.gms.tasks.Task zza(int,android.os.Bundle)' in program class com.google.firebase.iid.zzaa
Warning: com.google.firebase.messaging.FirebaseMessagingService: can't find referenced method 'com.google.firebase.iid.zzaa zzc(android.content.Context)' in program class com.google.firebase.iid.zzaa
Warning: com.google.firebase.messaging.FirebaseMessagingService: can't find referenced method 'com.google.firebase.iid.zzau zzah()' in program class com.google.firebase.iid.zzau
Warning: com.google.firebase.messaging.FirebaseMessagingService: can't find referenced method 'android.content.Intent zzai()' in program class com.google.firebase.iid.zzau
Warning: com.google.firebase.messaging.zza: can't find referenced method 'android.app.PendingIntent 

...

Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Warning: there were 6 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)

FAILURE: Build failed with an exception.
```

My firebase dependencies:
```
cloud_firestore: 0.8.1
firebase_auth: 0.5.20
firebase_core: 0.2.5+1
firebase_messaging: 2.0.0
```

Note: Well possible that this will not reproduce locally because of dependencies already being there. I noticed this problem on my build server where I do a clean build within docker every time.

**Comment by wbaeck** [comment]
my build server started to have the same problem!

**Comment by pboos** [comment]
### Current temporary workaround
I found two ways to temporary fix this issue. Just use the one you prefer. I have tested them both separately and they both worked for me.

#### Possible workaround 1:
In your pubspec.yaml add a dependency for `firebase_core` the following line:
```
dependencies:
  firebase_core: "0.2.5" # to force 0.2.5 instead of 0.2.5+1 to temporary fix https://github.com/flutter/flutter/issues/22892
```

#### Possible workaround 2:
In your `android/app/build.gradle` add the following below `dependencies { ... }`
```
// Temporary fix for: https://github.com/flutter/flutter/issues/22892
configurations.all {
    resolutionStrategy {
        force 'com.google.firebase:firebase-iid:17.0.0'
        force 'com.google.firebase:firebase-core:16.0.1'
    }
}
```

### More information on the problem
17.0.3 seems to be pulled in through the firebase-core which updated in 0.2.5+1.
```
+--- project :firebase_messaging
|    \--- com.google.firebase:firebase-messaging:17.3.0
|         +--- com.google.firebase:firebase-iid:[17.0.0] -> 17.0.3
+--- project :firebase_core
|    \--- com.google.firebase:firebase-core:16.0.4
|         +--- com.google.firebase:firebase-analytics:16.0.4
|         |    +--- com.google.android.gms:play-services-measurement-api:16.0.2
|         |    |    +--- com.google.firebase:firebase-analytics-impl:16.2.2
|         |    |    |    \--- com.google.firebase:firebase-iid:17.0.3 (*)
|         |    |    \--- com.google.firebase:firebase-iid:17.0.3 (*)
```

As well interesting to see is that builds are failing for firebase ;-)
<img width="991" alt="screen shot 2018-10-12 at 08 28 38" src="https://user-images.githubusercontent.com/398400/46839691-1bfec680-cdfa-11e8-9087-3710920d09c7.png">

**Comment by pboos** [comment]
This seems to be fixed now with the newest versions:

```
  firebase_auth: "^0.6.2+1"
  firebase_messaging: "^2.0.2"
  cloud_firestore: "^0.8.2+1"
```

**Comment by pboos** [comment]
This seems to be fixed now with the newest versions:

```
  firebase_auth: "^0.6.2+1"
  firebase_messaging: "^2.0.2"
  cloud_firestore: "^0.8.2+1"
```

**Comment by kroikie** [comment]
@pboos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/616. Any further collaboration will be done there.
