### ISSUE TITLE
Write up a document on the debug* constants, debug*() methods, etc

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#229]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 19:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1794_

----

**Comment by Hixie** [comment]
https://github.com/flutter/flutter.github.io/pull/131
