### ISSUE TITLE
Would like testing docs to include discussion of golden tests

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#22909]
This was brought up in a customer discussion.  @filiph was there.

The customer in question seems to have figured them out (so addressing this is not urgent), just recording the desire.

**Comment by eseidelGoogle** [comment]
Notes I took to myself:
* Why don't golden tests work on Mac/Linux shared / Should we update the docs to talk about this?
* What other testing solutions should we recommend? (e.g. reference tests)
* What other caveats should we put in the golden docs?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package%3Aflutter provides some information but focused on adding them to the Flutter repo itself.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2100](https://github.com/flutter/website/issues/2100) via [**ZenHub**](https://www.zenhub.com/)
