### ISSUE TITLE
Material: TextFieldButton with "filled" or "outline" appearance, labels, theming

### ISSUE THREAD

**Issue by sir-boformer** [flutter/flutter#22904]
I think it would make sense to have some kind of `TextFieldButton` that is styled like a `TextField` with an optional icon on the right. The button could be styled with an `InputDecoration`, and have a simple `onPressed` callback.

Usage:

* Dropdown
* Dropdown with picker dialog
* Date Picker (with calendar icon on the right)
* Time Picker
* Color Picker

Material Spec: 

> Text field dropdown menu
> 
> Text field dropdown menus look like text fields and display the currently selected item above the menu.
>
> On desktop, a text field dropdown menu appears below the element triggering the dropdown. On mobile, a text field dropdown menu can open a native picker.

<img src="https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1waT1DSvLGYu9Bi_nGAOPqcO4X5jOkEVy%2Ftext-field-menu-intro.png">

https://material.io/design/components/menus.html#exposed-dropdown-menu

Maybe

**Comment by sir-boformer** [comment]
Here is a very basic version that seems to work quite well so far:

```dart
import 'package:flutter/material.dart';

class TextFieldButton extends StatelessWidget {
  final String value;
  final InputDecoration decoration;
  final TextStyle style;
  final TextAlign textAlign;
  final VoidCallback onTap;

  TextFieldButton({
    Key key,
    this.value,
    this.decoration = const InputDecoration(),
    this.style,
    this.textAlign = TextAlign.start,
    this.onTap,
  }) : super(key: key);

  bool get _enabled => onTap != null;

  @override
  Widget build(BuildContext context) {
    final effectiveDecoration = (decoration ?? const InputDecoration())
        .applyDefaults(Theme.of(context).inputDecorationTheme)
        .copyWith(
      enabled: _enabled,
    );

    final effectiveBorder = effectiveDecoration.border ?? const UnderlineInputBorder();

    return InkWell(
      onTap: onTap,
      customBorder: effectiveBorder,
      child: InputDecorator(
        decoration: effectiveDecoration,
        baseStyle: style,
        textAlign: textAlign,
        isFocused: false,
        isEmpty: (value == null),
        child: Text(value ?? ''),
      ),
    );
  }
}
```

**Comment by abartolo** [comment]
I would love this feature. As @sir-boformer said, it would be great to have the DropDownButton have the same material design look at the material documentation states https://material.io/design/components/menus.html#exposed-dropdown-menu.

I am new to Flutter and while I am enjoying the developer experience, I am shocked the DropDownButton doesn't have the material support out of the box like the TextField.

**Comment by dshukertjr** [comment]
Yeah, this needs to be added.

**Comment by metaa** [comment]
I'd also love to be able to use the material dropdown as seen in the contacts app, as I'd like to move within the Material spec.

![2019-11-03_01-29-05](https://user-images.githubusercontent.com/5056880/68078591-6114e280-fdd9-11e9-9e4a-0fa7aa7de630.gif)

The thought of having to rebuild that manually makes me not wanna do it 😕

**Comment by lokeshpaladugula** [comment]
im new to flutter and i want to create a dropdown button with the dropdwon menu sholud not cover the button as shown above, pleease help me..

**Comment by LRNZ09** [comment]
This would be a really nice-to-have!

**Comment by tombowers** [comment]
This is possible with the `DropdownButtonFormField` class. https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html

**Comment by Vedsaga** [comment]
I hope this [Exposed dropdown menus](https://material.io/components/menus/android#exposed-dropdown-menus) feature get implemented. It is really important one which is missing and this case is open since 3 year.
![image](https://user-images.githubusercontent.com/59083528/171066428-80eefea3-a1a2-45a1-bc03-d9c375b535eb.png)

**Comment by Vedsaga** [comment]
Just making follow up check, if it's possible to add into next milestone.

**Comment by bleroux** [comment]
This was added sometimes ago with the new `DropdownMenu` widget which implements https://m3.material.io/components/menus/overview#b39b2819-a579-4de1-bca2-8d7dbd3b332c.

See https://api.flutter.dev/flutter/material/DropdownMenu-class.html
