### ISSUE TITLE
draw a line between two coordinates inside map , how to show multiple markers with fit zoom levell in map 

### ISSUE THREAD

**Issue by sathishRA91** [flutter/flutter#22906]
draw a line between two coordinates inside map , how to show multiple markers with fit zoom levell in map

**Comment by sathishRA91** [comment]
@zoechi Hi any solution to find out draw a line between two coordinates please help

**Comment by zon7** [comment]
> @zoechi Hi any solution to find out draw a line between two coordinates please help

You will have to wait till polyline is implemented

**Comment by csells** [comment]
closed as duplication of #17832
