### ISSUE TITLE
Atom: Running an app should save all open buffers first

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2290]

**Comment by devoncarew** [comment]
It should do that today (https://github.com/dart-atom/dartlang/blob/master/lib/launch/run.dart#L132). Perhaps it's buggy.

**Comment by Hixie** [comment]
Looks like the play button doesn't do it, but command+r does.

**Comment by devoncarew** [comment]
I believe this was fixed by upgrading to the latest plugin.
