### ISSUE TITLE
flutter/dart popup tooltips poorly positioned

### ISSUE THREAD

**Issue by gggustafson** [flutter/flutter#22912]
I am using VS Code on Windows 7 SP1

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code, 64-bit edition (version 1.28.0)
[√] Connected devices (1 available)

• No issues found!

```
When I hover over a recognized object, a tooltip popup appears. A problem is that if the object over which I hover is close to the top of the screen, the tooltip appears too far up; its top contents are hidden; and I have to reposition the object lower on the screen.

The first image displays the tooltip positioning problem. I have hovered over **Column** (line 78) where **Column** is near the top of the screen. 

![tooltip_too_high](https://user-images.githubusercontent.com/13719145/46748062-593b4b00-cc78-11e8-8a75-adad48624fb7.png)

The second image displays the tooltip when **Column** is located towards the center of the screen.

![tooltip_ok](https://user-images.githubusercontent.com/13719145/46748096-7112cf00-cc78-11e8-9e27-f2a39f0322e8.png)

It appears that tooltips require 9 lines. So through simple computations, the tooltip could be placed so that all 9 lines appear near the object it is discussing.

**Comment by zoechi** [comment]
@DanTup

**Comment by DanTup** [comment]
@gggustafson Thanks for the report! The positioning of the hovers is controlled by VS Code, so this seems like a bug there. (By coincidence, it looks like [this issue](https://github.com/Microsoft/vscode/issues/10051) I raised many years ago). Would you mind raising it [there](https://github.com/Microsoft/vscode/issues/new?template=bug_report.md) and post the link back here?

**Comment by gggustafson** [comment]
Microsoft/vscode flutter/dart popup tooltips poorly positioned #60534

**Comment by DanTup** [comment]
Thanks! Seems like it was closed unfairly - I don't believe I can fix it; the hover provider is unable to influence the rendered position. I've added a comment and will see what comes back.

**Comment by gggustafson** [comment]
Sorry for the trouble. Seems MS is a little touchy.

The problem is cosmetic and does have a workaround - position the hovered item in the center of the screen. Even still I believe it is a bug.

**Comment by zoechi** [comment]
Can this issue be closed here and maintained  in Microsoft/vscode?
It doesn't look like the Flutter team can do anything here.

**Comment by gggustafson** [comment]
Yes, let's close this. I will look to MS to add info to their copy.

**Comment by DanTup** [comment]
VS Code team have re-opened the related issue and there's nothing we can do here (we can't even provide a workaround, since the rendering code is entirely Codes), so closing makes sense. Thanks for bringing it up all the same! 👍
