### ISSUE TITLE
DropDownButton menu shows behind Overlay.

### ISSUE THREAD

**Issue by shalaby** [flutter/flutter#22917]
I have a DropDownButton in an Overlay, the problem is the menu shows behind the overlay.
I used PopupMenuButton too, same issue.

```dart
Widget build(BuildContext context) {
    OverlayState overlayState = Overlay.of(context);
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: RaisedButton(
          child: Text("Open Overlay"),
            onPressed: () {
          OverlayEntry topOverlay = OverlayEntry(builder: (context) {
            return Positioned(
              top: 100.0,
              right: 0.0,
              child: Material(
                child: Container(
                  decoration: BoxDecoration(
                      color: Colors.lightGreenAccent,
                      boxShadow: [BoxShadow(blurRadius: 5.0)]),
                  height: 50.0,
                  width: MediaQuery.of(context).size.width,
                  child: Center(
                    child: DropdownButton(
                        value: "1",
                        items: [
                          DropdownMenuItem(value: "1", child: Text("1")),
                          DropdownMenuItem(value: "2", child: Text("2")),
                        ],
                        onChanged: (value) {
                        }),
                  ),
                ),
              ),
            );
          });
          overlayState.insert(topOverlay);
        }),
      ),
    );
  }
```
![screenshot_1539193613](https://user-images.githubusercontent.com/149119/46755656-eb1d7500-ccc5-11e8-82f8-fcdef3789c53.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by shalaby** [comment]
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
    • Flutter version 0.8.2 at C:\Users\shala\flutter
    • Framework revision 5ab9e70727 (5 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\shala\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Users\shala\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4323.18
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.4323.44
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

**Comment by jmolins** [comment]
I've been studying this issue and I'm afraid what you see is the expected behaviour.

The result is the same if you just substitute the `DropDownButton` with a call to a route.

```
              OverlayEntry topOverlay = OverlayEntry(
                  maintainState: true,
                  builder: (context) {
                    return Positioned(
                        top: 100.0,
                        right: 0.0,
                        child: Material(
                            child: Container(
                          decoration: BoxDecoration(
                              color: Colors.lightGreenAccent,
                              boxShadow: [BoxShadow(blurRadius: 5.0)]),
                          height: 50.0,
                          width: MediaQuery.of(context).size.width,
                          child: Center(
                            child: FlatButton(
                                onPressed: () {
                                  Navigator.of(context).push(MaterialPageRoute(
                                      builder: (context) =>
                                          Container(color: Colors.blue)));
                                },
                                child: Text("Show page")),
                          ),
                        )));
                  });

```

This is what happens:

The app Navigator has a list of routes (`_history`) and each route has its list of `OverlayEntry`'s. When you push a new route using `Navigator.push()` you are inserting the route overlays above the overlays of the last route. The following method in 'Navigator` gets the last route to use it as the insertion point.

```
  OverlayEntry get _currentOverlayEntry {
    for (Route<dynamic> route in _history.reversed) {
      if (route.overlayEntries.isNotEmpty)
        return route.overlayEntries.last;
    }
    return null;
  }

```
And `DropDownButton` and `PopupMenuButton` both use routes (`OverlayRoute`'s) behind the scenes.

So, when you add an independent `Overlay` with just `Overlay.of(context).insert(myOverlay);` it will always be above any route/overlay managed by the app `Navigator` (if what you receive from the of() method is the Navigator Overlay).

If you want to get in the game of the `Navigator`'s `OverlayEntry`s list, you must use a `Route`. Otherwise your `OverlayEntry` will always be on top of the `Navigator`'s list.

I hope the analysis is accurate.

**Comment by goriyasno** [comment]
@jmolins sorry i'm new in flutter, can you show example how to use overlay with route? Thanks.

**Comment by ride4sun** [comment]
@jmolins Seems like with that in mind that the overlay is useless for more complex content. Is the Stack a better choice than?

**Comment by dannnnthemannnn** [comment]
For anyone in the future I was able to overcome this by using showDialog (https://api.flutter.dev/flutter/material/showDialog.html) instead of putting things into the overlay with overlay entries. Then just navigator.pop instead of overlayentry.remove.

**Comment by TahaTesser** [comment]
Hi @shalaby 
I think this is working as intended and well explained by this [comment](https://github.com/flutter/flutter/issues/22917#issuecomment-431457670)

if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by miDeb** [comment]
I was able to solve a similar issue by switching to the third-party package [flutter_portal](https://pub.dev/packages/flutter_portal). (Just in case somebody finds this helpful)

**Comment by HasanAlyazidi** [comment]
I think `DropDownButton`, `PopupMenuButton`, or else should be shown above the overlay if opened from inside the overlay.

**Comment by bitsdominicada** [comment]
> I was able to solve a similar issue by switching to the third-party package [flutter_portal](https://pub.dev/packages/flutter_portal). (Just in case somebody finds this helpful)

Hi, I have the same issue with  flutter_portal. I did you resolved?

**Comment by bitsdominicada** [comment]
> I was able to solve a similar issue by switching to the third-party package [flutter_portal](https://pub.dev/packages/flutter_portal). (Just in case somebody finds this helpful)

Hi, I have the same issue with flutter_portal. How did you resolved?

**Comment by benoitrongeard** [comment]
Hi, any news about it ? 
I have the same problem and don't find a solution...
@jmolins where is this Navigator function ? I search a solution to push overlay in route stack like this but didn't work : 

 ```
 NavigatorState navigator = Navigator.of(context, rootNavigator: false);
  navigator.overlay.insert(overlay);
```
Thanks !
