### ISSUE TITLE
Documentation - What ThemeData is used by default for each widget color(s)?

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#22925]
I'm finding ThemeData almost pointless because, because there seems to be no documentation anywhere that states what ThemeData is used for the color of every widget be default. eg. How do I know which widgets use accent color by default?

Every widget pixel rendered uses a color, hopefully something from ThemeData, but which theme data? If I can't easily find out, or I have to look inside the code or I have to just override all theme data to get what I want ... I may as well hard code all the colors and avoid theming all together.

**Comment by workerbee22** [comment]
Should be labelled *d: api docs*

**Comment by zoechi** [comment]
Merging with #22773
