### ISSUE TITLE
[Question] Dropdown multiple selection

### ISSUE THREAD

**Issue by laertispappas** [flutter/flutter#22927]
Hello, 

I'm currently playing with flutter and building a mobile app. I'm looking on how to create a dropdown with multiple select options. I couldn't find something related and I was wondering if there is a way to achieve this or should I take a different approach?

thank you in advance.

**Comment by laertispappas** [comment]
@sir-boformer thanks for the feedback. It looks that it gets the job done. I will rethink it for now I render some filter chips. 

@zoechi shall I close the Issue? I see you added some labels.

**Comment by zoechi** [comment]
If that satisfy your need lets close.
Feel free to create a new issue if you thing there should something be done.
Thanks for the update!

**Comment by muwal** [comment]
> You could go with a multi select dialog like this:
> 
> ![](https://camo.githubusercontent.com/ffa8ddd6581ba8e261e77028e5be2a3dc4dce4e1/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f524575624d2e6a7067)
> 
> Usability on mobile is probably better, especially if you have a long list of items. Flutter provides everything you need for it.

can i get the code?

**Comment by sir-boformer** [comment]
@muwal Sorry, that's not a screenshot from a Flutter app. Use `AlertDialog`, `ListView` and `CheckboxListTile` and `Navigator.pop(selectedItem)`
