### ISSUE TITLE
Content in CupertinoTabView covered by keyboard 

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/flutter#22923]
Right now, CupertinoPageScaffold automatically accounts for the soft keyboard with its `resizeToAvoidBottomInset` property:

https://docs.flutter.io/flutter/cupertino/CupertinoPageScaffold/resizeToAvoidBottomInset.html

This is not the case for CupertinoTabView, which is causing the keyboard to overlap the ListView in our Cupertino sample's search screen:

https://github.com/flutter/samples/blob/master/veggieseasons/lib/screens/search.dart

Content at the bottom of the list is unaccessible when the keyboard is open.

## Steps to Reproduce

1. Run the `veggieseasons` Cupertino samples from https://github.com/flutter/samples.
2. Navigate to the search screen.
3. Focus the keyboard, and attempt to scroll the list all the way up.

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
[!] VS Code (version 1.24.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

**Comment by lifenautjoe** [comment]
Hi @RedBrogdon, 
Any current workaround this other than manually adding the bottom padding?

Cheers.
