### ISSUE TITLE
IOWebSocketChannel.connect fails silently for invalid addresses

### ISSUE THREAD

**Issue by ecpost** [flutter/flutter#22938]
When calling IOWebSocketChannel.connect with an URL that does NOT point to a listening server, rather than throwing an exception or giving any indication that it failed, the call behaves as if everything is fine:
- It returns an IOWebSocketChannel instance.
- The returned channel's closeCode property is null.
- Calls to the channel's sink.add method don't throw an exception.

I also tried hooking in to channel.stream.handleError, but the handler was never called.

What should I be doing to determine that a connection was unsuccessful?  Or should it be throwing an exception?  Hopefully I'm not missing something obvious.  I looked through the channel.dart and related source code, but I couldn't find anything accessible that would help.

An easy way to reproduce the problem:

1. Follow the "[Working with WebSockets](https://flutter.io/cookbook/networking/web-sockets/)" example.  The example as-is works as expected.  Entered text is echoed back.
2. Change the hostname in the URL from "echo.websocket.org" to some garbage (or just append some arbitrary port like ":1234"), and rerun with the changes.  No exception is thrown upon startup or when entering text.  (Of course the text isn't echoed back either.  But there's no clear indication that it's because there's no actual connection.)
3. You can also assign the connection/channel to a local var and look at closeCode, e.g. `print(channel.closeCode);`, which outputs "null".  Normally with a valid connection, after it closes, it's a value like 1000.

This occurs for me on an iPhone with iOS 12.0 as well as an LGL163BL with Android 7.0 (API 24). 
 Flutter versions 0.8.2 and 0.9.4 (on Mac OS X 10.13.6).

**Comment by zoechi** [comment]
Would you mind reporting in https://github.com/dart-lang/web_socket_channel instead?

**Comment by ecpost** [comment]
Will do.  Sorry about that.

**Comment by zoechi** [comment]
No prob. It's just much more likely that you get the attention of the right people there.
The docs are not too clear about where to report what bug. So no worries :)

**Comment by ecpost** [comment]
...And had I gone there in the first place I would have seen the related issues already reported there :)
