### ISSUE TITLE
How to catch Errors on MethodChannel.invokeMethod crash using sentry

### ISSUE THREAD

**Issue by zinwalin** [flutter/flutter#22930]
App crash without any issues recorded in sentry even if set up catchError for MethodChannel.invokeMethod.

**Comment by zoechi** [comment]
I assume sentry can only cover Dart exception. If your exception is thrown by native plugin code it won't reach Dart.
Not sure if #14765 would cover that, but I assume so.

**Comment by truongsinh** [comment]
Can/Should we do such that all native code is put in `try/catch` block, and we `result.error` such caught exception?

**Comment by cyanglaz** [comment]
Adding result.error in java and result([FlutterError...]) in objective-c should forward the error to dart and dart will be able to catch it. @zinwalin, could you provide the plugin name that caused the issue?

**Comment by truongsinh** [comment]
> Adding `result.error` in Java and `result([FlutterError...])` in objective-c should forward the error to Dart and Dart will be able to catch it. @zinwalin, could you provide the plugin name that caused the issue?

I believe the sample code like this won't forward the error:
```kotlin
package io.github.ponnamkarthik.flutternativelog

import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.PluginRegistry.Registrar

import android.util.Log

class FlutterNativeLogPlugin(): MethodCallHandler {
  companion object {
    @JvmStatic
    fun registerWith(registrar: Registrar): Unit {
      val channel = MethodChannel(registrar.messenger(), "flutter_native_log")
      channel.setMethodCallHandler(FlutterNativeLogPlugin())
    }
  }

  fun somethingThatCrash(): Integer {
    return 0/0
  }
  override fun onMethodCall(call: MethodCall, result: Result): Unit {
    if (call.method.equals("getPlatformVersion") {
      val result = somethingThatCrash();
      result.success(result)
    } else {
      result.notImplemented()
    }
  }
}
```

and my idea of having it wrapped something like this:
```kotlin
override fun onMethodCall(call: MethodCall, result: Result): Unit {
  try {
    if (call.method.equals("getPlatformVersion") {
      val result = somethingThatCrash();
      result.success(result)
    } else {
      result.notImplemented()
    }
  } cache (exception e) {
    result.error(e.toString())
  }
}

**Comment by cyanglaz** [comment]
> Can/Should we do such that all native code is put in `try/catch` block, and we `result.error` such caught exception?

@truongsinh It is correct that you have to send the error from android side by `result.error()` to let dart catch the error. Is there any action item left for this issue?
