### ISSUE TITLE
Atom editor didn't find Nexus 5x

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#2293]
### Steps to Reproduce
1. Open Atom
2. Upgrade to Atom 1.5.4 and 0.2.1
3. Run `Packages > Flutter > Create`
4. Open `flutter.yaml` to get Devices panel to appear

### Expected Results
Nexus 5x appears.

### Actual Results
Device not found until after Atom is restarted.

### Notes
It looks like the daemon didn't start until I ran `adb devices` manually.  The Flutter SDK should check for devices whenever I open the menu (and run any missing requisite daemons at that time).

### Flutter Version
49c0ec3402a58b670d4eefb8ad500d330da59664

### Logs
    $ adb devices
    List of devices attached
    * daemon not running. starting it now on port 5037 *
    adb I 18680 189988 usb_osx.cpp:259] Found vid=18d1 pid=4ee2 serial=00b8d582d79b3249
    adb I 18680 189988 usb_osx.cpp:259] 
    * daemon started successfully *
    00b8d582d79b3249  device

    $ flutter devices
    1 connected device:

    Nexus 5X (00b8d582d79b3249)

(Atom still didn't see the device at this point until after I restarted it.)

**Comment by devoncarew** [comment]
Note that we've had a few reports of this.

**Comment by jimbeveridge** [comment]
This has happened to me several times.

**Comment by aghassemi** [comment]
I ran into Atom not showing my connected devices (despite `flutter devices` and `adb devices` working fine) as well but my issue happened to be related to https://github.com/flutter/flutter/issues/3531 so not using Launcher to start Atom fixed it for me.

**Comment by sethladd** [comment]
Thanks for the report! Going to close this in favor of the IntelliJ plugin.
