### ISSUE TITLE
Codelab documentation needs update - Write Your First Flutter App, part 2

### ISSUE THREAD

**Issue by palaniraja** [flutter/flutter#22948]
In codelab ["Write Your First Flutter App, part 2"](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#0)  Section [6. Navigate to a new screen](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#5) 

code starts with `Scaffold` but, at the end of [Part-1](https://flutter.io/get-started/codelab/) already refactored it to `MaterialApp`. 

I file this issue here, as it was the link for submitting bug from codelab page.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1976](https://github.com/flutter/website/issues/1976) via [**ZenHub**](https://www.zenhub.com/)
