### ISSUE TITLE
how to package the snapshots into a single dynamic library

### ISSUE THREAD

**Issue by Oo121oO** [flutter/flutter#22947]
Hi, all,  I do not know it very clearly, would you please provide a DOC to specify this step by step? I think it is very cool to make app more simple. And for one more thing, may I suggest that, package all things into one should be very cool, include all bundle resource, like android *.asrc package.

**Comment by Oo121oO** [comment]
Yes, of cause.

**Comment by Oo121oO** [comment]
We get an error while run command `flutter build aot --build-shared-library` as follow:

Building AOT snapshot in release mode (android-arm-release)...      

Exit code 1 from: ~/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot ~/Library/Android/sdk/ndk-bundle/platforms/android-16/arch-arm -shared -nostdlib -o build/aot/app.so build/aot/snapshot_assembly.S:

ld: unknown option: --sysroot=~/Library/Android/sdk/ndk-bundle/platforms/android-16/arch-arm

clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to fix it?

**Comment by Hixie** [comment]
It's not clear exactly what the use case is here or what problem is being described. It would be helpful if more detail could be provided to fully explain exactly what it is that is unclear in the documentation.
