### ISSUE TITLE
Flutter Firebase plugins are using old versions of their counterparts

### ISSUE THREAD

**Issue by leovinsen** [flutter/flutter#22941]
Hi, 

My Flutter app that was using firebase_auth and firebase_database was crashing with this message:

`The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1.`

Turns out that the flutter packages are outdated as referenced on [StackOverflow](https://stackoverflow.com/questions/52730515/flutter-error-java-lang-nosuchfielderror-prefer-highest-or-remote-version-no-fo). Just wanted to give the developers a friendly reminder to update the said plugins.

Cheers.

**Comment by zoechi** [comment]
The updates were published a while ago.
