### ISSUE TITLE
InkWell Lag: Using onDoubleTap(), slows down on tap().

### ISSUE THREAD

**Issue by SuitMonkeyB** [flutter/flutter#22950]
If you have a widget surrounded by an InkWell, and you define both the onTap() and onDoubleTap() members, it seems that the mere presence of the onDoubleTap definition causes an abnormal amount of lag in executing the onTap()/ single tap action. 
I know that the OS  needs to give a small delay in order to detect between a single and a double tap, but this lag seems longer than it should be in Flutter. In the example I'm talking about, tapping a card pushes to a new route, and double tapping the card adds a star to the card. In every case, tapping once and pushing to the new page is always snappier with onDoubleTap() omitted. 
So it seems like the gesture detection adds lag to allow for a double tap to occur, but as a result, it makes navigation feel really laggy. Is there a way to mitigate this somehow?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by SuitMonkeyB** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.9.7-pre.76, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.


Sorry about that.

**Comment by jslavitz** [comment]
@SuitMonkeyB After looking into this, it seems like it's not a bug, it's really just the intended functionality. Right now, a double tap can happen up to 300ms after the first tap up. This might be a little on the long side, so we can will look into shortening it, but in the mean time, you can edit the value of `kDoubleTapTimeout` in constants.dart.

**Comment by SuitMonkeyB** [comment]
Damn, ok. Yea I figured it couldn't be avoided. I'll try tweaking the constraint and seeing if I can get some better feeling results. Thanks a lot jslavitz.
