### ISSUE TITLE
Unable to upgrade flutter v0.9.6

### ISSUE THREAD

**Issue by braulio94** [flutter/flutter#22957]
## Steps to reproduce

`flutter upgrade`

## Result

![flutter upgrade](https://user-images.githubusercontent.com/20057010/46809396-49019980-cd66-11e8-96dd-9d3d4caac986.jpg)

**Comment by zoechi** [comment]
```
git clean -xfd
git pull
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

I'm closing, but feel free to add more comments.
