### ISSUE TITLE
It's sad that to use an Input you have to shuttle the data around

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2295]
The simplest example of using an Input involved having to track the state of the text input. It feels like you should just be able to plop a text input into the app and read the value out later, without having to keep shuttling it around.

**Comment by abarth** [comment]
This follows the reactive pattern that we use for Checkbox and all the other form controls.  Maybe we should create a Form widget to help you manage this state?

**Comment by Hixie** [comment]
Yeah, I dunno. With Checkbox it doesn't seem as burdensome because every change is relevant. With a text field, you have to build the value before sending it.

**Comment by DaveShuckerow** [comment]
I recently encountered this, and it's somewhat troublesome from a client perspective -- as a developer, the intermediate values of a text input are not important in the average case, and so the behavior I was expecting when I tried out the Input widget is that the framework will take care of that internal text statekeeping behavior without requiring several lines of boilerplate.

**Comment by Hixie** [comment]
@mpcomplete is adding some logic to simplify this. It's still got some rough edges (e.g. it doesn't handle the build structure changing), but we're iterating on it. See https://github.com/flutter/flutter/pull/2850.

**Comment by DaveShuckerow** [comment]
Wow, that was a fast response!  Thanks for being so helpful!

**Comment by mpcomplete** [comment]
Just committed #2850 . AFAICT this solves the original problem in this bug - you no longer have to deal with InputValues yourself. Closing.
