### ISSUE TITLE
Broadcast Receiver to FlutterActivity

### ISSUE THREAD

**Issue by tiagojencmartins** [flutter/flutter#22962]
Hello,

I'm writting an application on which the notification has several actions.  The action button events go to the a class that extends BroadcastReceiver and from there I want to invoke a method on the flutter view. 

To achieve this I'm using an Observable object which connects the BroadcastReceiver class to the MainActivity, and the later invokes the method on Flutter via invokeMethod on the MethodChannel object.

Is there a less verbose way to do this?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
I think that's a good question for StackOverflow (if you include the current code).

**Comment by Sanjay007** [comment]
@tiagojencmartins Can you help , How did you got Method Channel Instance inside Broadcast Receiver i am stuck there . I want to send callback to my Flutter View
