### ISSUE TITLE
Hint text in API documentation Search box in distracting

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#22967]
See https://github.com/flutter/website/issues/1422

**Comment by InMatrix** [comment]
I'm not seeing the issue in your screenshots on my Chrome for Mac OS X. It could be a browser/OS specific bug. 

Cc: @gspencergoog @jcollins-g

**Comment by jcollins-g** [comment]
I'm seeing it on Chrome for Linux.  But it only appears to be a thing on the flutter site, not pub.dartlang.org or other dartdoc sites.  It might have something to do with the custom CSS for Flutter.

**Comment by jcollins-g** [comment]
Poking around in the inspector, disabling overrides.css `#searchbox` css for border, border radius, font family, and padding seems to make the issue go away.  However I don't know if that would make things worse on other platforms.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2010](https://github.com/flutter/website/issues/2010) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gspencergoog** [comment]
This is not a "website" issue, it's an API docs issue.

**Comment by zoechi** [comment]
@gspencergoog thanks for the feedback!
I concluded because of 

> not pub.dartlang.org or other dartdoc sites

**Comment by gspencergoog** [comment]
Yeah, no worries, it was a little unclear.  The API docs are hosted on [docs.flutter.io](https://docs.flutter.io) (as opposed to the website at [flutter.io](https://flutter.io), in case you see that referenced in other places.

**Comment by zoechi** [comment]
This doesn't looks so bad now 

![image](https://user-images.githubusercontent.com/405837/50097839-0606eb00-021b-11e9-9517-97887cdd40f5.png)

vs the image posted in https://github.com/flutter/website/issues/1422

![image](https://user-images.githubusercontent.com/405837/50097861-13bc7080-021b-11e9-90c6-b1414b1716ff.png)

**Comment by jcollins-g** [comment]
I'm going to try to fix the custom CSS here; at head currently things are much worse on Safari yet changed a little bit on Chrome.
