### ISSUE TITLE
Issue using firebase_ml_vision

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#22965]
When using firebase_ml_vision on IOS I receive an error for Firebase Auth.
On android I receive an output that no faces were detected no matter if I use portrait or landscape.
The output is:

```
W/DynamiteModule(14227): Local module descriptor class for com.google.android.gms.vision.dynamite.face not found.
I/DynamiteModule(14227): Considering local module com.google.android.gms.vision.dynamite.face:0 and remote module com.google.android.gms.vision.dynamite.face:0
D/FaceNativeHandle(14227): Cannot load feature, fall back to load whole module.
W/DynamiteModule(14227): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(14227): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(14227): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
V/DynamiteModule(14227): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Vision  (14227): Loading library libmobile_vision_face.so
I/Vision  (14227): libmobile_vision_face.so library load status: true
```

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.10.1-pre.25, on Mac OS X 10.13.6 17G65, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
[✓] VS Code (version 1.27.2)
[✓] Connected device (3 available)

• No issues found!
Process finished with exit code 0
```

**Comment by rlee1990** [comment]
So after the update to version 0.2.0+1 the package works on IOS but in android it still does not detect faces at all
`I/flutter (13932): /storage/emulated/0/Android/data/com.nexttechphilly.fluttercrushn/cache/1539441270673_compressed3355293034334504468.jpg
I/DynamiteModule(13932): Considering local module com.google.android.gms.vision.dynamite.face:0 and remote module com.google.android.gms.vision.dynamite.face:0
D/FaceNativeHandle(13932): Cannot load feature, fall back to load whole module.
W/DynamiteModule(13932): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule(13932): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule(13932): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
V/DynamiteModule(13932): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/zygote64(13932): Skipping duplicate class check due to unrecognized classloader
I/Vision  (13932): Loading library libmobile_vision_face.so
I/pittpatt(13932): wrapper.cc:442] JNI_OnLoad successful
I/Vision  (13932): libmobile_vision_face.so library load status: true
I/flutter (13932): empty!!!!!`

**Comment by rlee1990** [comment]
Any update on this? This is delaying my application.

**Comment by mazzonem** [comment]
@rlee1990 I had the same issue, taking a picture sideways seem to make it detect faces. So It could be because of the orientation of your image.

**Comment by rlee1990** [comment]
@mazzonem how would I rotate the image after its taken. There is currently an issue with the camera plugin with landscape.

**Comment by rlee1990** [comment]
This is now working after the version update.

**Comment by kroikie** [comment]
@rlee1990

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/612. Any further collaboration will be done there.
