### ISSUE TITLE
Cloud Firestore - Excluding / filtering data from stream of query snapshots

### ISSUE THREAD

**Issue by Butzlabben** [flutter/flutter#22973]
Hi there,

I have the following problem:
In a CollectionReference I can do the following: 
`Firestore.instance.collection("jobs").where('user', isEqualTo: uid).snapshots()`

I want to exclude a particular user from my stream but I can't do it.
There isn't any 
`Firestore.instance.collection("jobs").where('user', is**Not**EqualTo: uid).snapshots()`
or
`Firestore.instance.collection("jobs").retainWhere('user', isEqualTo: uid).snapshots()`

The second solution would be the best one, it would be as it is in a List (https://api.dartlang.org/stable/2.0.0/dart-core/List/retainWhere.html).

With kind regards
Butzlabben

**Comment by zoechi** [comment]
I don't really understand the question.
Do you get an error?
https://firebase.google.com/docs/firestore/query-data/queries shows what queries are supported.
Flutter can't support anything that is not supported by Firebase.

If you want to filter the result of a Firebase query, you can use methods of collections like `where` or `retainWhere()` 

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
