### ISSUE TITLE
Issue from website page 使用缓存图片

### ISSUE THREAD

**Issue by gxzlolo** [flutter/flutter#22991]
From URL: https://www.flutterchina.club/cookbook/images/cached-images.md
```
Because every version of flutter_test from sdk depends on http 0.12.0 and flutter_cache_manager >=0.1.0-rc.1 depends on http ^0.11.3+14, flutter_test from sdk is incompatible with flutter_cache_manager >=0.1.0-rc.1.
Because cached_network_image >=0.4.1 <0.4.2 depends on flutter_cache_manager ^0.1.1 and cached_network_image >=0.4.2 depends on flutter_cache_manager ^0.1.2, cached_network_image >=0.4.1 requires flutter_cache_manager ^0.1.1.
Thus, flutter_test from sdk is incompatible with cached_network_image >=0.4.1.
So, because aicoin depends on both cached_network_image ^0.4.1 and flutter_test any from sdk, version solving failed.

pub get failed (1)
exit code 1
```

**Comment by zoechi** [comment]
Some version constraints need to be updated or `flutter_cache_manager` needs an update to support newer dependencies.

I'm going to close because this site is not maintained by the Flutter team.

**Comment by gxzlolo** [comment]
Flutter (Channel dev, v0.10.0, on Mac OS X 10.13.6 17G3015, locale zh-Hans-CN)
    • Flutter version 0.10.0 at /Users/charles/flutter
    • Framework revision d954ae6850 (2 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

**Comment by gxzlolo** [comment]
> Some version constraints need to be updated or `flutter_cache_manager` needs an update to support newer dependencies.
> 
> I'm going to close because this site is not maintained by the Flutter team.

 Flutter (Channel dev, v0.10.0, on Mac OS X 10.13.6 17G3015, locale zh-Hans-CN)
    • Flutter version 0.10.0 at /Users/charles/flutter
    • Framework revision d954ae6850 (2 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

**Comment by zoechi** [comment]
With "version constraints` I mean the `dependencies: ...` section in `pubspec.yaml`

**Comment by sgon00** [comment]
@gxzlolo please check the bug https://github.com/renefloor/flutter_cache_manager/issues/48 and its workaround.
