### ISSUE TITLE
Can you provide a way to customize the keyboard?

### ISSUE THREAD

**Issue by Im-Kevin** [flutter/flutter#22994]
Can you provide a way to customize the keyboard?

**Comment by Im-Kevin** [comment]
It is better to customize the whole keyboard, because I need to make a convenient keyboard according to the needs of the business.
example:
![image](https://user-images.githubusercontent.com/15227529/46851933-cb07c600-ce2b-11e8-9c0b-14c66a1960fd.png)

**Comment by Im-Kevin** [comment]
https://github.com/Im-Kevin/cool_ui
I wrote a plug-in by reference to your source code.

**Comment by stuartmorgan** [comment]
Since there has not been significant demand for this, closing; there's no reason this use couldn't be addressed by the larger community.
