### ISSUE TITLE
Figure out how to do Material icon transitions

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#230]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 21:00 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1801_

---

See: https://www.google.com/design/spec/animation/delightful-details.html

**Comment by Hixie** [comment]
This page talks about how to implement a general fashion:
http://alex.miller.im/posts/material-design-css-spinning-icon-transitions/

We also need to support arbitrary pre-canned animations from specific icons to specific icons. We should probably support both.

**Comment by abarth** [comment]
There as another page somewhere that had a general algorithm for most of the path-based icons.  It was done entirely in CSS with by transforming divs using a css transition.

**Comment by abarth** [comment]
Found a bunch of people trying something similar, but not quite the one I was looking for.

**Comment by zoechi** [comment]
Above link is dead.
https://material.io/design/iconography/animated-icons.html#usage shows icon transitions

**Comment by zoechi** [comment]
Related #19404

**Comment by goderbauer** [comment]
I believe our answer here is https://master-api.flutter.dev/flutter/material/AnimatedIcon-class.html.
