### ISSUE TITLE
event log when launching flutter app disappeared.

### ISSUE THREAD

**Issue by nokia6290** [flutter/flutter#23003]
When running flutter app via phone the event log does not display anything anymore.

It was working fine until I performed the beta 0.9.4 update.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by nokia6290** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected devices (1 available)

• No issues found!

Here you go.

I've tried invalidate caches & restart.
Completely uninstalling android studio and install a fresh copy.

Same result.

**Comment by nokia6290** [comment]
oops I got the wrong flutter doctor at first.

[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-AU)
    • Flutter version 0.9.4 at /Users/kozeris/Documents/flutter-sdk/flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/kozeris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • SM G950F • ce031713ab94bc200d • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by nokia6290** [comment]
This morning Android studio had an update 'XAM' related. and it's back.
All sorted.

I suspect it was android studio updates.

**Comment by zoechi** [comment]
@nokia6290 thanks for the update!
