### ISSUE TITLE
Intl library is not available?

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#23005]
Hello, I am unable to access `NumberFormat()`. It could be human error but I am unable to import the `intl` library or access the class. Have there been breaking changes recently?

https://docs.flutter.io/flutter/intl/NumberFormat-class.html

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.28.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by zoechi** [comment]
How are you unable to access?
Have you tried restarting the IDE. 
I have seen it a few times the past months that DartAnalyzer in the IDE complained about invalid imports that where clearly valid, but then the problem vanished for unknown reasons.

**Comment by berosoboy** [comment]
Did you add intl in dependencies?
https://pub.dartlang.org/packages/intl#-installing-tab-

**Comment by zoechi** [comment]
>  I was able to import intl package without adding this into dep.

it's shipped as part of Flutter

**Comment by lukepighetti** [comment]
After playing around with it I am only able to use `import 'package:intl/intl.dart';` if I first add it to deps, I was expecting to be able to just use it like @dooboolab

**Comment by berosoboy** [comment]
The docs (https://flutter.io/tutorials/internationalization/) suggests to add the dependencies.

> it's shipped as part of Flutter

I don't know if it was in the previous versions. But it seems the intl is part of flutter_localizations dep.

**Comment by dooboolab** [comment]
@berosoboy You are right. I think it is because I use `internationalization` package.

**Comment by lukepighetti** [comment]
Thanks for the help, everyone! I’ll close this
