### ISSUE TITLE
How to build flutter engine without vulkan

### ISSUE THREAD

**Issue by southpeak** [flutter/flutter#23006]
I want to build flutter engine to support "armeabi", and I follow the article "[Android Builds Supporting armeabi](https://github.com/flutter/engine/wiki/Android-Builds-Supporting-armeabi)" and config the engine project.

However, It's failed because of vulken：

```
.....

In file included from ../../third_party/skia/include/gpu/vk/GrVkDefines.h:15:
In file included from ../../third_party/skia/include/gpu/vk/../../../third_party/vulkan/SkiaVulkan.h:8:
In file included from ../../third_party/skia/include/gpu/vk/../../../third_party/vulkan/vulkan/vulkan_core.h:31:
../../third_party/skia/include/gpu/vk/../../../third_party/vulkan/vulkan/vk_platform.h:55:6: error: "Vulkan isn't supported for the 'armeabi' NDK ABI"
    #error "Vulkan isn't supported for the 'armeabi' NDK ABI"

......
```

So, how can i build the engine project succefully without vulkan?

**Comment by pedromassangocode** [comment]
Hi @southpeak 
Are you still having this issue?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
