### ISSUE TITLE
Enter key not detected on TextFields on desktop embedder

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#23014]
When running Flutter on desktop ([desktop embedder](https://github.com/google/flutter-desktop-embedding)), hitting the Enter key while editing a TextField doesn't call onSubmitted or onEditingComplete. This only happens on iOS and Android simulators.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`. 

> This only happens on iOS and Android.

What does this mean? Flutter only supports iOS and Android.

**Comment by franciscojma86** [comment]
Sorry, my comment wasn't clear enough. I'm running Flutter on desktop through an [embedder](https://github.com/google/flutter-desktop-embedding). Behavior in iOS and Android both device and simulator, are as intended. This is a [PR](https://github.com/google/flutter-desktop-embedding/pull/136) for the embedder to make it work, along with the referenced PR here.

**Comment by zoechi** [comment]
The PR was merged. Is this fixed?

**Comment by zoechi** [comment]
Is this a duplicate of #15757 ?

**Comment by franciscojma86** [comment]
I'm not sure it's a duplicate since this that issue seems a bit broad, and may not be talking about the embedder, where the key does nothing. The change merged adds an onSubmitted action if the text field maxLines == 1, but does nothing if it's > 1. I think we can keep it open until the latter is addressed.

**Comment by franciscojma86** [comment]
This was fixed long ago, apologies for the delay.
