### ISSUE TITLE
Video player using deprecated API

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#23019]
## Steps to Reproduce
Pubspec

```yaml
dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.6.5
```

## Logs
Warning in Logs while running the build
```
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.6.5\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

## flutter doctor -v

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-IN)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (2 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Rohit\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Rohit\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • ONEPLUS A5010 • f0f79579 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by lishuhao** [comment]
+1

**Comment by zoechi** [comment]
Thanks @berosoboy 
Closing as dup of #22511

**Comment by JoaoVictorCardoso** [comment]
_**### compileOptions**_

I solved this problem by adding this line in build.gradle, as say the compile log :smile:  

android {
        compileOptions {
            sourceCompatibility 1.8
            targetCompatibility 1.8
        }
    }

**Comment by jde-gr** [comment]
> 
> 
> _**### compileOptions**_
> 
> I solved this problem by adding this line in `build.gradle`, as say the compile log 😄
> 
> ```
> android {
>         compileOptions {
>             sourceCompatibility 1.8
>             targetCompatibility 1.8
>         }
>     }
> ```

This worked for me with SpeechRecognition, which also was throwing that same " uses or overrides a deprecated API" warning.

**Comment by UtkarshKunwar** [comment]
> _**### compileOptions**_
> 
> I solved this problem by adding this line in `build.gradle`, as say the compile log 
> 
>  ```
> android {
>         compileOptions {
>             sourceCompatibility 1.8
>             targetCompatibility 1.8
>         }
>     }
> ```

I was getting errors while building then realised that I was editing the wrong `build.gradle`. The correct one is `android/app/build.gradle` and not `android/build.gradle`.
