### ISSUE TITLE
Issue In Card App

### ISSUE THREAD

**Issue by sabarinathancs** [flutter/flutter#23013]
```
 ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 1705): The following message was thrown during layout:
I/flutter ( 1705): A RenderFlex overflowed by 4668 pixels on the bottom.
I/flutter ( 1705): The overflowing RenderFlex has an orientation of Axis.vertical.
I/flutter ( 1705): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 1705): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 1705): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 1705): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 1705): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 1705): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter ( 1705): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 1705): like a ListView.
I/flutter ( 1705): The specific RenderFlex in question is:
I/flutter ( 1705):   RenderFlex#2e63d OVERFLOWING
I/flutter ( 1705):   creator: Column ← RepaintBoundary-[<0>] ← NotificationListener<KeepAliveNotification> ← KeepAlive
I/flutter ( 1705):   ← AutomaticKeepAlive ← SliverFillViewport ← Viewport ← _ScrollableScope ←
I/flutter ( 1705):   IgnorePointer-[GlobalKey#1b5c0] ← Semantics ← Listener ← _GestureSemantics ← ⋯
I/flutter ( 1705):   parentData: <none> (can use size)
I/flutter ( 1705):   constraints: BoxConstraints(w=360.0, h=512.0)
I/flutter ( 1705):   size: Size(360.0, 512.0)
I/flutter ( 1705):   direction: vertical
I/flutter ( 1705):   mainAxisAlignment: start
I/flutter ( 1705):   mainAxisSize: max
I/flutter ( 1705):   crossAxisAlignment: center
I/flutter ( 1705):   verticalDirection: down
```

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the problem.

Please add the output of `flutter doctor -v`
and a minimal reproduction.

**Comment by sabarinathancs** [comment]
[✓] Flutter (Channel dev, v0.9.7-pre.25, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.9.7-pre.25 at /Users/Mac/Documents/flutter
    • Framework revision a68b03e9ce (2 weeks ago), 2018-10-03 17:37:00 -0700
    • Engine revision 74662ab695
    • Dart version 2.1.0-dev.6.0.flutter-d2c5a24fd9

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Google Nexus 5, 6 0 0, API 23, 1080x1920 • 192.168.56.101:5555 • android-x86 • Android 6.0 (API 23)

! Doctor found issues in 2 categories.

**Comment by sabarinathancs** [comment]
Fixed
