### ISSUE TITLE
Test flutter_tool

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#23031]
Right now the majority of it is untested, or only verified to throw exceptions given invalid params.

At least these are missing smoke tests for their basic functionality:
- [ ] `commands/run.dart`
- [ ] `run_hot.dart`
- [ ] `run_cold.dart`
- [ ] `vmservice.dart`

These other commands are tested, but are mocking out so many of their dependencies in the process that they're not capable of verifying their behaviors all the way through to the VM level:
- [ ] `commands/attach.dart`
- [ ] `commands/daemon.dart`

**Comment by jonahwilliams** [comment]
@mklim do you plan to continue using this tracking issue or can we close it?

**Comment by blasten** [comment]
we are still missing these tests. Are we tracking the issue somewhere else?
