### ISSUE TITLE
Better handling of pending images in the ImageCache when an ImageStreamCompleter fails

### ISSUE THREAD

**Issue by tarobins** [flutter/flutter#23030]
Currently, when an ImageStreamCompleter fails, the ImageStreamCompleter is never removed from _pendingImages map, making it difficult to retry image loading if desired.  

Upon the failure of an ImageStreamCompleter, one or both of the following should probably happen

1) evict should remove the ImageStreamCompleter from pending as well as the cache.
2) failed ImageStreamCompleters should be moved to the regular cache.

**Comment by fhuonder** [comment]
I added a new pull request https://github.com/flutter/flutter/pull/23824 that adds a small fix to #23034.

**Comment by fhuonder** [comment]
@goderbauer / @jonahwilliams

This should be this pr https://github.com/flutter/flutter/pull/23860

Regards, 
Florian

**Comment by csells** [comment]
@tarobins does this fix solve your issue?

**Comment by tarobins** [comment]
I don't remember all the details of what was going on, though I sort of do.  
From the description of the PR and a quick look at the code, it doesn't look like #23860 solves the same problem with the problem being that failures were sitting around in the some cache (I don't remember the various caches) and the PR seems to clear them when a clear or evict is requested.  

I've been requested to look at image caching issues pertaining to Fuchsia, so I can look at this in a bit more detail in a bit once I finish with some other issues.
