### ISSUE TITLE
convert iconfont.css to icon.dart

### ISSUE THREAD

**Issue by jiqimaogou** [flutter/flutter#23040]
i have a iconfont.css generated from the iconfont managerment website. and the website can generator a iconfont.css file, like this:

```

.icon-wodetiwen:before { content: "\e669"; }

.icon-wodeshoucang:before { content: "\e66a"; }

.icon-wodedingdan:before { content: "\e66b"; }

.icon-wodebushi:before { content: "\e66c"; }

```

can you provide a tool to convert iconfont.css to icon.dart

**Comment by zoechi** [comment]
I think this can easily be done as community project.
