### ISSUE TITLE
FlutterFire plugins do mostly not support non-default firebase apps.

### ISSUE THREAD

**Issue by JSANL** [flutter/flutter#23049]
Hey, my plan was to make a Firebase debug project, which get's automatically used when being in debug mode with the help of `firebase_core`.
It should've gone something like this:
```dart
  final FirebaseOptions options = const FirebaseOptions(
    projectID: "****-debug",
    googleAppID: "1:36*******:android:**********",
    apiKey: "AIza***********************************",
    gcmSenderID: '29********' 
  );

    final FirebaseApp app = await FirebaseApp.configure(
      name: "****-debug",
      options: options,
    );

    Firestore firestore = Firestore(app: app);
    FirebaseAuth firebaseAuth = FirebaseAuth(app: app); //Not supported
    ....
    ....
```
I noticed that except a few plugins most don't support non-default FirebaseApps.
Supporting this would be a benefit, as there can be programmatically swichting between several Firebase projects without moving files.

### Plugins **not** supporting non-default FirebaseApps:
_Note: I mostly looked through the API-Docs, as I don't use all plugins in production:_

- [X] firebase_auth
- [ ] firebase_messaging
- [ ] firebase_analytics
- [ ] firebase_dynamic_links
- [ ] firebase_ml_vision
- [ ] firebase_performance
- [ ] firebase_remote_config
- [ ] cloud_functions

**Comment by YamauchiEA** [comment]
Any estimate for implement cloud_functions using non-default firebase app?

**Comment by brettclutch** [comment]
firebase_auth still not working in combination with cloud firestore. You are unable to use flutter + user ID based cloud firestore rules since its not possible to login securely to cloud firestore via the cloud firestore flutter plugin. I reported also on #22157 and #18075 which are dups since this is a day 1 feature which is currently missing that is a roadblock for my usage of flutter.

**Comment by brettclutch** [comment]
@zoechi Thanks, that solved the problem! 

FYI -> I for sure did not come up with that .configure() code myself and tried to find the resource where that was recommended but alas I now cannot find it. Either way, I'm resolved.

Thank You.

**Comment by collinjackson** [comment]
I don't think there's much value to having an open tracking bug for all Firebase multiple app support issues. Instead, let's file issues against the relevant plugins and we'll fix them. I opened #27888 for cloud_functions and will look at #27548.

**Comment by JSANL** [comment]
@collinjackson 
My reasoning behind this was that one can quickly see if all the plugins one uses support multiple apps, and if not, which exactly do not.
But I mean, if the other approach is more convenient/easier for you, then that's also alright😉

We would still need issues (afaik) for 
 firebase_messaging
 firebase_analytics
 firebase_dynamic_links
 firebase_ml_vision
 firebase_performance
 firebase_remote_config
though.

**Comment by collinjackson** [comment]
The best way to determine if multiple app support is available is whether the constructor has an optional `app` argument.

Should support multiple apps, because the iOS and Android SDKs support multiple apps: 

firebase_ml_vision (issue #28149 filed)

No plans to support multiple apps, because the wrapped iOS and Android SDKs do not support multiple apps:

firebase_messaging
firebase_analytics
firebase_dynamic_links
firebase_performance
firebase_remote_config

**Comment by JSANL** [comment]
@collinjackson
Understood.

Is there are reason why the wrapped SDKs do not support it?
As of right now one could not change the "whole" underlying firebase project of an app if it uses messaging etc, but only parts of it.

My original intention was that I could simply change the firebase project by passing different values. Instead I now have to rely on app flavors and supply different google-services.json files at build time, which also can't be changed dynamically.

In my opinion it would be a nice improvement to have this.

(I suppose this not the correct place to have this discussion, should this be in another Issue somewhere else?)

**Comment by kroikie** [comment]
@JSANL

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/611. Any further collaboration will be done there.

**Comment by ollydixon** [comment]
@JSANL completely agree with what you are saying. Just like JS implementations, you should be able to load a new ```google-services.json``` for Flutter Firebase to use. Right now making debug projects inside Flutter Firebase is painful.
