### ISSUE TITLE
HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))

### ISSUE THREAD

**Issue by jitenders859** [flutter/flutter#23045]
while running http request i am getting this error.

my code is
```dart
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

Future<Post> fetchPost() async {
  final response =
      await http.get('https://jsonplaceholder.typicode.com/posts/1');

  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON
    return Post.fromJson(json.decode(response.body));
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load post');
  }
}

class Post {
  final int userId;
  final int id;
  final String title;
  final String body;

  Post({this.userId, this.id, this.title, this.body});

  factory Post.fromJson(Map<String, dynamic> json) {
    return Post(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}

class Http extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center(
          child: FutureBuilder<Post>(
            future: fetchPost(),
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Text(snapshot.data.title);
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }

              // By default, show a loading spinner
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the full error output.

Is this related to self-signed certificates?

**Comment by jitenders859** [comment]
flutter doctor - v  gives me this
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-IN)
    • Flutter version 0.9.4 at C:\Dev\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Dev\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.4
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4505.50

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by zoechi** [comment]
Thanks for the update!

**Comment by ramanroy911** [comment]
flutter doctor --android-licenses is not working for me

**Comment by shenglijin** [comment]
how  to  ignore the certificate

**Comment by ramanroy911** [comment]
I found an error in SSL certificate, issue was resolved when the certificate was corrected.

You can find detail about certificate here https://digicert.com/help

------------------------------------

Another method is

Future<http.Response> getApplicationsAPICall(CurrencyRequestModel post) async {
  bool trustSelfSigned = true;
  HttpClient httpClient = new HttpClient()
    ..badCertificateCallback =
        ((X509Certificate cert, String host, int port) => trustSelfSigned);
  IOClient ioClient = new IOClient(httpClient);

  //final response = await http.post('$url', // Previous Code

  final response = await **ioClient**.post('$url',
      headers: {
        HttpHeaders.contentTypeHeader: 'application/json',
        //HttpHeaders.authorizationHeader: '',
        
      },
      body: currencyRequestToJson(post)
      );
  return response;
}

**Comment by acebeing** [comment]
Make sure your device connect the same wifi with your computer.

**Comment by bernardohrl** [comment]
I'm having the same error as mentioned above and the command
```
flutter doctor --android-licenses
```
did not worked for me. Actually I get an warning:
```
Warning: File C:\Users\04860826108\.android\repositories.cfg could not be loaded.
```

I'm trying to @ramanroy911's method, I don't know from where classes as 'HttpHeaders', 'X509Certificate', 'HttpClient' and 'CurrencyRequestModel' are imported.

**Comment by ramanroy911** [comment]
// API Side
import 'package:http/http.dart' as http;
import 'dart:async';
import 'dart:io';
import 'package:http/io_client.dart';

// Model Side
import 'dart:convert';

String url = 'URL';

Future<http.Response> getApplicationsAPICall(CurrencyRequestModel post) async {
  bool trustSelfSigned = true;
  HttpClient httpClient = new HttpClient()
    ..badCertificateCallback =
        ((X509Certificate cert, String host, int port) => trustSelfSigned);
  IOClient ioClient = new IOClient(httpClient);

  final response = await ioClient.post('$url',
      headers: {
        HttpHeaders.contentTypeHeader: 'application/json',
        //HttpHeaders.authorizationHeader: '',
        
      },
      body: currencyRequestToJson(post)
      );
  return response;
}

String currencyRequestToJson(CurrencyRequestModel data) {
  final dyn = data.toJson();
  return json.encode(dyn);
}

CurrencyCommonResponseModel currencyResponseFromJson(String str) {
  final jsonData = json.decode(str);
  return CurrencyCommonResponseModel.fromJson(jsonData);
}

// Request Model
class CurrencyRequestModel {
  String token;

  CurrencyRequestModel({
    this.token,
  });

  Map<String, dynamic> toJson() => {
        "token": token,
      };
}

class CurrencyCommonResponseModel {
  int code;
  String message;
  final List<CurrencyResponseModel> data;

  CurrencyCommonResponseModel({
    this.code,
    this.message,
    this.data,
  });

  factory CurrencyCommonResponseModel.fromJson(Map<String, dynamic> json) {
    var list = json['data'] as List;
    List<CurrencyResponseModel> dataList =
        list.map((i) => CurrencyResponseModel.fromJson(i)).toList();

    return new CurrencyCommonResponseModel(
      code: json["code"] as int,
      message: json["message"] as String,
      data: dataList,
    );
  }
}

class CurrencyResponseModel {
  int id;
  String name;
  String code;

  CurrencyResponseModel({
    this.id,
    this.name,
    this.code,
  });

  factory CurrencyResponseModel.fromJson(Map<String, dynamic> json) {
    return new CurrencyResponseModel(
      id: json["id"] as int,
      name: json["name"] as String,
      code: json["code"] as String,
    );
  }
}

Above is the complete example, CurrencyRequestModel is the data response type from API

**Comment by bernardohrl** [comment]
thanks @ramanroy911 !

**Comment by amirahazhari** [comment]
@ramanroy911 can i know where to put this code?? I'm new to this.

> // API Side
> import 'package:http/http.dart' as http;
> import 'dart:async';
> import 'dart:io';
> import 'package:http/io_client.dart';
> 
> // Model Side
> import 'dart:convert';
> 
> String url = 'URL';
> 
> Future<http.Response> getApplicationsAPICall(CurrencyRequestModel post) async {
> bool trustSelfSigned = true;
> HttpClient httpClient = new HttpClient()
> ..badCertificateCallback =
> ((X509Certificate cert, String host, int port) => trustSelfSigned);
> IOClient ioClient = new IOClient(httpClient);
> 
> final response = await ioClient.post('$url',
> headers: {
> HttpHeaders.contentTypeHeader: 'application/json',
> //HttpHeaders.authorizationHeader: '',
> 
> ```
>   },
>   body: currencyRequestToJson(post)
>   );
> ```
> 
> return response;
> }
> 
> String currencyRequestToJson(CurrencyRequestModel data) {
> final dyn = data.toJson();
> return json.encode(dyn);
> }
> 
> CurrencyCommonResponseModel currencyResponseFromJson(String str) {
> final jsonData = json.decode(str);
> return CurrencyCommonResponseModel.fromJson(jsonData);
> }
> 
> // Request Model
> class CurrencyRequestModel {
> String token;
> 
> CurrencyRequestModel({
> this.token,
> });
> 
> Map<String, dynamic> toJson() => {
> "token": token,
> };
> }
> 
> class CurrencyCommonResponseModel {
> int code;
> String message;
> final List data;
> 
> CurrencyCommonResponseModel({
> this.code,
> this.message,
> this.data,
> });
> 
> factory CurrencyCommonResponseModel.fromJson(Map<String, dynamic> json) {
> var list = json['data'] as List;
> List dataList =
> list.map((i) => CurrencyResponseModel.fromJson(i)).toList();
> 
> ```
> return new CurrencyCommonResponseModel(
>   code: json["code"] as int,
>   message: json["message"] as String,
>   data: dataList,
> );
> ```
> 
> }
> }
> 
> class CurrencyResponseModel {
> int id;
> String name;
> String code;
> 
> CurrencyResponseModel({
> this.id,
> this.name,
> this.code,
> });
> 
> factory CurrencyResponseModel.fromJson(Map<String, dynamic> json) {
> return new CurrencyResponseModel(
> id: json["id"] as int,
> name: json["name"] as String,
> code: json["code"] as String,
> );
> }
> }
> 
> Above is the complete example, CurrencyRequestModel is the data response type from API
> 
> But we found an issue in server SSL certificate when that was corrected then we can use
> 
> //final response = await http.post('$url', // Previous Code
> 
> Find the issue in SSL from here https://digicert.com/help

**Comment by ramanroy911** [comment]
All the headings have already been mentioned like // API Side, // Model Side etc

Do some research on flutter architecture

**Comment by Aaron009** [comment]
@jitenders859 @zoechi @ramanroy911 @shenglijin @acebeing 

 I have this problem too.
```dart
import 'dart:io';

main() async {
  HttpClient client = new HttpClient();
  var request = await client.getUrl(Uri.parse('https://shop.io.mi-img.com/app/shop/img?id=shop_88f929c5731967cbc8339cfae1f5f0ec.jpeg'));
//  var request = await client.getUrl(Uri.parse('https://www.baidu.com/'));
  var response = await request.close();
  print(response.headers);
  client.close(force: true);
}
```

I found that if the link is `www.baidu.com`, it will not report an error. What is the reason and how can I solve it?

**Comment by kechkibet** [comment]
I hadent concatenated certificate bundle and certificate on the server side thats why i was getting the error

**Comment by milesgranger** [comment]
It was happening to me because I was using Genymotion combined with NAT, once I switched over to Bridge networking, it was ok again.

**Comment by njovy** [comment]
This happened to me all of a sudden without any clue. My flutter app was up and running for a while and suddenly this happens. I set a validity to 9999 so this shouldn't happening. Does anyone have a similar issue?

![Screen Shot 2020-03-11 at 2 04 26 AM](https://user-images.githubusercontent.com/1792070/76338856-a83d5200-633c-11ea-84c5-ab33816244e8.png)

I tried digicert and it doesn't contain any error.

**Comment by MOOUDE** [comment]
this code worked well for me 

`
HttpClient client = new HttpClient();
client.badCertificateCallback = ((X509Certificate cert, String host, int port) => true);

String url ='xyz@xyz.com';

Map map = { 
     "email" : "email" , 
     "password" : "password"
};

HttpClientRequest request = await client.postUrl(Uri.parse(url));

request.headers.set('content-type', 'application/json');

request.add(utf8.encode(json.encode(map)));

HttpClientResponse response = await request.close();

String reply = await response.transform(utf8.decoder).join();

print(reply);
`

**Comment by MOOUDE** [comment]
this code worked very well for me 
`HttpClient client = new HttpClient();
client.badCertificateCallback = ((X509Certificate cert, String host, int port) => true);

String url ='xyz@xyz.com';

Map map = { 
     "email" : "email" , 
     "password" : "password"
};

HttpClientRequest request = await client.postUrl(Uri.parse(url));

request.headers.set('content-type', 'application/json');

request.add(utf8.encode(json.encode(map)));

HttpClientResponse response = await request.close();

String reply = await response.transform(utf8.decoder).join();

print(reply);`

**Comment by pacifire** [comment]
> bool trustSelfSigned = true;
>   HttpClient httpClient = new HttpClient()
>     ..badCertificateCallback =
>         ((X509Certificate cert, String host, int port) => trustSelfSigned);
>   IOClient ioClient = new IOClient(httpClient);
> 
>   final response = await ioClient.post('$url',
>       headers: {
>         HttpHeaders.contentTypeHeader: 'application/json',
>         //HttpHeaders.authorizationHeader: '',
>         
>       },
>       body: currencyRequestToJson(post)
>       );
>   return response;

Thank-you, it worked.
