### ISSUE TITLE
keyboard - padding added to the Scrollable

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#23051]
## Steps to Reproduce
![screenshot_1539431880](https://user-images.githubusercontent.com/1261332/46905177-e55da480-cefc-11e8-9bf5-4767d116654c.png)
![screenshot_1539431884](https://user-images.githubusercontent.com/1261332/46905178-e5f63b00-cefc-11e8-9daa-2bfbbb3aff4e.png)

```
[√] Flutter (Channel dev, v0.10.0, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 0.10.0 at M:\flutter
    • Framework revision d954ae6850 (4 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_45\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
    • All Android licenses accepted.

[X] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.
```

**Comment by p30arena** [comment]
it also doesn't change when setting:

`resizeToAvoidBottomPadding: false,`

and this is the config in AndroidManifest.xml:

```
android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
android:windowSoftInputMode="adjustResize"
```

**Comment by p30arena** [comment]
@Hixie @zoechi 
customers are noticing the issue and reporting it, I'm disgraced :smile: 

![photo_2018-10-14_16-13-51](https://user-images.githubusercontent.com/1261332/46916783-2c669b00-cfcc-11e8-945f-313eff4c37b8.jpg)

**Comment by Hixie** [comment]
Weird. Any idea what's going on? Can you reproduce it in a small app (something like the default `main.dart` but with suitable changes) that you can upload so we can study it?

**Comment by p30arena** [comment]
@Hixie 
I couldn't reproduce it in a new app,
now `resizeToAvoidBottomPadding: false,` is working.
do you recommend a way of cleaning? I think that some old code could've been stuck in there.
maybe `.\gradlew.bat clean` ?

### I've also observed that the opacity was a **padding** in the last image.

In the first Image, I'm using **[carousel_pro](https://pub.dartlang.org/packages/carousel_pro)** which disappears on Soft Input,
I replaced it with an Image, and the issue is gone.

### So in the first Image, its a problem with carousel_pro, do you suggest a solution to fix it?

**Comment by p30arena** [comment]
@Hixie 
https://github.com/flutter/flutter/issues/13339#issuecomment-385040551

**Comment by zoechi** [comment]
> .\gradlew.bat clean

usually `flutter clean` is sufficient.

> some white content on top 

Do you have nested Scaffolds?

**Comment by zoechi** [comment]
> Error from the Compiler when using nested Scaffolds,

I'm not convinced this makes sense. 
Lots of things might not make sense for one developer but not for others.

You can of course create an issue and wait for a response from someone from the Flutter team.

**Comment by zoechi** [comment]
I assume this issue can be closed then.
Please add a comment to have it reopened if you disagree.
