### ISSUE TITLE
How to download packages when 7za.exe is blocked in by AV in system

### ISSUE THREAD

**Issue by cal2dev** [flutter/flutter#23058]
## Just need help how I can install packages manually

when I install get packages I get error access denied

```
 flutter packages get
Running "flutter packages get" in startup_namer...              
CreateProcessW failed 5
Access is denied.

Command: \flutter\bin\cache\dart-sdk\lib\_internal\pub\asset\7zip\7za.exe e data.tar.gz

pub get failed (1)
exit code 1
```
This is basically due to system antivirus (Mcafee) blocking 7za.exe.

I cant do anything right now to stop antivirus doing this.

Can anybody help how we can download packages zip file and install manually or any other workaround. 

Please help asap.

Thanks

**Comment by cal2dev** [comment]
Hey @zoechi 

Just want to know, will it be a temporary approach is right?
If I manually download the plugins from their github page and put it in this directory
`\flutter\.pub-cache\hosted\pub.dartlang.org\`
And then  create a entry .packages file.

Can this approach will work? what is the drawback/risks of this approach i should be aware of?
Do i need to make a entry in pubspec.lock file also ?
Suppose one package has dependency of another package, do I need to download that also and put in directory (.pub-cache/hosted/...) ?
anything else I need to do make this approach work?

Please help.

**Comment by zoechi** [comment]
> is blocked in by AV in system

The solution is to unblock it in AV

I'm going to close because I don't think there is anything the Flutter team can do.
