### ISSUE TITLE
ExpansionTile - can't change trailing default Icon color even though it looks like one should be able to

### ISSUE THREAD

**Issue by sjmcdowall** [flutter/flutter#23053]
## Steps to Reproduce

Create any Flutter App that uses an ExpansionTile 

Try to change the default Icon color ... 

Although the code looks like one should be to set the following:
theme.unSelectedWidget    and 
theme.accentColor

it actually doesn't do anything ..the Icon color stays the same.. 

I finally had to copy the code and change the Icon logic to the following (see the color: attribute)  

`              trailing: widget.trailing ??
                  RotationTransition(
                    turns: _iconTurns,
                    child: Icon(Icons.expand_more, color: _iconColor.value),
                  ),`

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en)
    • Flutter version 0.9.4 at /Users/sjm/Development/tools/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sjm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (2 available)
    • iPhone 8 • 0CF10D1F-D5FD-4887-BCA1-6BE9818C5AB7 • ios • iOS 12.0 (simulator)
    • iPhone X • 78590509-1E81-4378-8BDE-92EBAFDB00A0 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by jmolins** [comment]
I have also reproduced the problem, which can be seen in the Gallery app (Material > Expand/collapse list control). The trailing icon does not get the blue color it should.

I have submitted PR [#23118](https://github.com/flutter/flutter/pull/23118) that tries to fix the issue.

**Comment by yostrokon** [comment]
There is no access to the widget parametes.
Would be great if developer can build him with like constructor ExpansionTile.trailing({options_to_override_defaults})

**Comment by jmolins** [comment]
On the contrary. You can set a trailing widget icon in ExpansionTile and you can give it the color you want.
The question is that if you do that you lose the integrated animation for the trailing arrow.
This is the code:
```
              trailing: widget.trailing ?? RotationTransition(
                turns: _iconTurns,
                child: const Icon(Icons.expand_more),
              ),
```
You can see that first it uses your trailing widget without applying any animation. If you don't provide a trailing widget it uses the default `Icons.expand_more` and applies the transition and the theme color.

What was not working and tries to solve the PR is that the default icon was not transitioning to the correct theme color during the animation.

**Comment by yostrokon** [comment]
@jmolins 
"The question is that if you do that you lose the integrated animation for the trailing arrow."

This is a point of the issue - to override hardcoded defaults. The question is about to change the color, but somebody would like to have different icon, and may be not exactly icon, but circularavatar widget with his face rotated upside down and back.

**Comment by sjmcdowall** [comment]
@jmolins -- I'd happily open a new issue -- except - -not sure what exactly to say in it :) Also -- do PR's ever get accepted and included!?  :(

**Comment by Anyoks** [comment]
Was this implemented? I will find it very useful!

**Comment by CarltonK** [comment]
I resolved the issue albeit in a less than desirable manner. In Material App, change the color of "unselectedWidgetColor" to the desired color

**Comment by Popovma** [comment]
I am a little late to the party, but if someone else needs a work around you can wrap the Expansion tile in a theme widget, then add ThemeData and set the accent color to whatever color you are looking for.  It is sort of a hack but it works...
Theme(data: ThemeData(accentColor: Colors.red),child: ExpansionTile())
