### ISSUE TITLE
Flutter requires a minimum Xcode version of 9.0.0.

### ISSUE THREAD

**Issue by ai930** [flutter/flutter#23057]
[!] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    ✗ Flutter requires a minimum Xcode version of 9.0.0.
      Download the latest version or update via the Mac App Store.
    ✗ ios-deploy out of date (1.9.2 is required). To upgrade:
        brew upgrade ios-deploy
Xcode 7.2.1 how to use Flutter？

**Comment by salihgueler** [comment]
As you see [in this documentation](https://flutter.io/setup-macos/#ios-setup), it is not possible to use it in the earlier versions.

**Comment by zoechi** [comment]
Thanks @salihgueler

**Comment by Mauricio-001** [comment]
try this     flutter run build

**Comment by GeekOnHeels01** [comment]
> try this flutter run build

Here it the response:

Target file "build" not found.
