### ISSUE TITLE
Flutter app drops java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by AlexBacich** [flutter/flutter#23055]
I've built an app written on Flutter and it's running well on my device.

On client device however it is crashing at start (even before Centry initiates).

The only log I have from GooglePlay:

```
 at java.lang.Runtime.loadLibrary (Runtime.java:367)
  at java.lang.System.loadLibrary (System.java:1076)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:172)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:149)
  at io.flutter.app.FlutterApplication.onCreate (FlutterApplication.java:22)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1037)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6496)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:229)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1887)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:7406)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

I'm building specifically using arm64 (app crashes even on my device if I'm trying to run on arm (32).

flutter build apk --release --target-platform=android-arm64

Flutter doctor gives no issues:
```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.28.0)
[✓] Connected devices (1 available)
```

**Comment by AlexBacich** [comment]
Solution is described in this article. https://medium.com/flutterpub/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd



In build.gradle of app this lines should be added:

```
android {
     ...
    defaultConfig {
       ....    
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }
```

Build should be made using flutter build apk

**Comment by rlee1990** [comment]
Looks like I had the same issue. This bug really needs to be fixed.
My issue #23627

**Comment by Hixie** [comment]
cc @zanderso

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
Android does not support loading 32-bit and 64-bit ARM native libraries within the same process.  If your app includes another 32-bit library, then the app's build scripts will need to explicitly select the 32-bit version of Flutter.

Alternatively, the app could include both 32-bit and 64-bit versions of Flutter within the same package.  But that will increase the size of the APK.

**Comment by rockwotj** [comment]
Instead of only having a certain arch, https://github.com/flutter/flutter/pull/24440 would be the ideal solution to this.

**Comment by Hixie** [comment]
If Android bundles do resolve this, that does seem like the better solution. Let's wait for #24440 to be fixed before doing further work here.

**Comment by Hixie** [comment]
@rockwotj Can you talk about what someone would have to do to ensure that they generate the right APKs for 32bit and 64bit once #24440 lands? (So that we can document it.) I'm not familiar with Bundles enough to describe it myself.

**Comment by rockwotj** [comment]
FWIW right now what I do is generate APKs (https://developer.android.com/google/play/publishing/multiple-apks#CreatingApks) one of which using --target-platform=android-arm and the other which is --target-platform=android-arm64 

Then I also set the right abiFilter in the Gradle files for each of those. Just a minor bit of hassle to get 64bit libraries for higher end devices.

**Comment by Hixie** [comment]
Thanks for the explanation @rockwotj. We definitely want to fix this, though we currently don't have anyone available who can work on this area. If anyone is interested in writing up a patch to address this, please don't hesitate to reach out, we would be happy to help with the design and review.

**Comment by Hixie** [comment]
I'm going to remove the `blocker` label because while we think it is important that we eventually make this easy (whether by documenting it better or making the tool better or some combination), it can currently be worked around by a sufficiently wizardly Gradle engineer.

**Comment by rockwotj** [comment]
FYI this is relevant here, the Play Store is going to require 64 bit support by August: https://developer.android.com/distribute/best-practices/develop/64-bit

Looks like this will be a blocker by then.

**Comment by pranayairan** [comment]
I am planning to add support for this inside appbundle in upcoming PR. Stay tuned.

**Comment by HPH92** [comment]
Whats the status @pranayairan ? :)

**Comment by iassal** [comment]
@pranayairan, any update here? As @rockwotj mentioned, Google play store will require applications to provide 64 bit versions starting August 1, 2019. 

https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

**Comment by pranayairan** [comment]
@iassal Flutter added the support for both 32 bit and 64 bit, look at this issue for more details https://github.com/flutter/flutter/issues/18494. The changes are already in dev and will be in beta soon.

**Comment by GyuriMajercsik** [comment]
We got the following exception in production ~13 times from two devices: 

* Huawei P8 (HWGRA), Android 6.0
* Asus ZenFone 2 (ZE500CL) (ASUS_Z00D), Android 5.0

```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary (Runtime.java:366)
  at java.lang.System.loadLibrary (System.java:989)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java)
  at io.flutter.app.FlutterApplication.onCreate (FlutterApplication.java)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1011)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4550)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:147)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1342)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5253)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:949)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:744)
```

The release was built with `flutter build appbundle`, so it should contain both 32 and 64 bit versions. The used Flutter version is: `Flutter 1.7.8+hotfix.4` channel stable.

**Comment by gofur** [comment]
i got same errors ?? any update ? @pranayairan  or others can help??

Asus ZenFone 2 (ZE550ML) (Z008_1), Android 5.0

`java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary (Runtime.java:366)
  at java.lang.System.loadLibrary (System.java:989)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:122)
  at io.flutter.view.FlutterMain.startInitialization (FlutterMain.java:99)
  at io.flutter.app.FlutterApplication.onCreate (FlutterApplication.java:22)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1011)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4550)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:147)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1342)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5253)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:900)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:695)`

**Comment by Row7** [comment]
Same problem here with these devices:
- Samsung Galaxy Note9 (crownlte), Android 9
- Samsung Galaxy J6 (j6lte), Android 9
- Samsung Galaxy Tab A 8.0 (gtasliteltecs), Android 9

The release was built with `flutter build appbundle` on stable channel.

**Comment by zanderso** [comment]
@blasten Would you mind taking a quick look at this one to see if there's any new advice in light of your recent work. Thanks!

**Comment by davidmartos96** [comment]
@Row7 What version of Flutter is it? 1.7.8 or 1.9.1?

**Comment by Row7** [comment]
> @Row7 What version of Flutter is it? 1.7.8 or 1.9.1?

Flutter 1.7.8+hotfix.4

**Comment by Row7** [comment]
> @Row7 What version of Flutter is it? 1.7.8 or 1.9.1?

1.7.8

**Comment by mohlam12** [comment]
Same problem on emulator when deploying a release-built apk (without even spliting per abis) 👍 

`09-16 13:08:53.670  9530  9530 E AndroidRuntime: FATAL EXCEPTION: main
09-16 13:08:53.670  9530  9530 E AndroidRuntime: Process: XXXXXXXX, PID: 9530
09-16 13:08:53.670  9530  9530 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/XXXXXXXX-iYKv7sNLPGEKuJRp42Y1YA==/base.apk"],nativeLibraryDirectories=[/data/app/XXXXXXXX-iYKv7sNLPGEKuJRp42Y1YA==/lib/x86, /data/app/XXXXXXXX-iYKv7sNLPGEKuJRp42Y1YA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libflutter.so"
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1667)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(Unknown Source:34)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at io.flutter.view.FlutterMain.startInitialization(Unknown Source:10)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at io.flutter.app.FlutterApplication.onCreate(Unknown Source:3)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 13:08:53.670  9530  9530 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)`

**Comment by blasten** [comment]
@mohlam12 It looks you need an ARM32 or ARM64 emulator if you running a release (fat) APK. 

Update on this issue:

A few things have changed since this issue was filed, Flutter supports fat APKs, split APK per ABI APKs and App bundles. This currently works for ARM32 and ARM64 devices.  Additionally, we plan to add support for x86_64 soon (Follow https://github.com/flutter/flutter/issues/9253 for updates. cc @jonahwilliams).

As a result, I'm closing this issue.

**Comment by creativecreatorormaybenot** [comment]
@blasten I do not understand why you closed this. This issue is not fixed and it is the most frequent crash for my app on Android.

Maybe the work regarding #9253 added the possibility to fix it, however, I do not understand how.

**Comment by blasten** [comment]
@creativecreatorormaybenot https://github.com/flutter/flutter/issues/23055#issuecomment-531872707

**Comment by creativecreatorormaybenot** [comment]
@blasten I am using Android App Bundles. I might just not understand what you are saying there.

**Comment by aldwnesx** [comment]
> FWIW right now what I do is generate APKs (https://developer.android.com/google/play/publishing/multiple-apks#CreatingApks) one of which using --target-platform=android-arm and the other which is --target-platform=android-arm64
> 
> Then I also set the right abiFilter in the Gradle files for each of those. Just a minor bit of hassle to get 64bit libraries for higher end devices.

how do you publish two different apks version number? i tdoesn't allow me to generate two same version but iw ant to publish both arm and arm64
