### ISSUE TITLE
how to pass auth token using flutter cloud_firestore package

### ISSUE THREAD

**Issue by stt106** [flutter/flutter#23067]
If I set my Cloud Firestore database rule to 

```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```

After a user is authenticated, how to pass in the `uid` to the a cloud firestore request e.g. I want to write to a collection:
`Firestore.instance.collection('myCollection').document()
          .setData(myData);`

Btw, does cloud_firestore package not support serializing enum?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Trenton-Lyke** [comment]
Could you please show the answer here

**Comment by alterschwede** [comment]
Take a look at this Answer ("Just in case..."):
https://stackoverflow.com/questions/52812514/how-to-pass-firestore-auth-token-using-flutter-cloud-firestore-package
