### ISSUE TITLE
flutter_test's http dependency locked?

### ISSUE THREAD

**Issue by raveesh-me** [flutter/flutter#23062]
## Steps to Reproduce

1. Try to install cached_network_image: ^0.5.0 on flutter 0.9.4
2. Run packages get

## Logs

```
Not applicable
```

```
Running "flutter packages get" in DevFestKolkata...              
Because flutter_cache_manager 0.2.0 depends on http ^0.12.0 and no versions of flutter_cache_manager match >0.2.0 <0.3.0, flutter_cache_manager ^0.2.0 requires http ^0.12.0.
And because every version of flutter_test from sdk depends on http 0.11.3+17, flutter_test from sdk is incompatible with flutter_cache_manager ^0.2.0.
And because cached_network_image 0.5.0 depends on flutter_cache_manager ^0.2.0 and no versions of cached_network_image match >0.5.0 <0.6.0, flutter_test from sdk is incompatible with cached_network_image ^0.5.0.
So, because devfest_18_kolkata depends on both cached_network_image ^0.5.0 and flutter_test any from sdk, version solving failed.                                                               
pub get failed (1)

```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-IN)
    • Flutter version 0.9.4 at /Users/raveesh/MyCode/SDKs/Flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/raveesh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone XS Max • F342DE0E-20A7-4430-A36A-F539F8F2A7C3 • ios • iOS 12.0 (simulator)

• No issues found!

```

**Comment by raveesh-me** [comment]
Test dependency needs to update http dependency IMHO

**Comment by raveesh-me** [comment]
for now, commenting the test dependency out allows me to move forward with code.

**Comment by eseidelGoogle** [comment]
@goderbauer or @tvolkert would know.

**Comment by tvolkert** [comment]
Alternatively, bumping the version constraints on `http` within [`http_multi_server`](https://github.com/dart-lang/http_multi_server/blob/master/pubspec.yaml) (and then updating the pinned versions in flutter) should fix this.

/cc @kevmoo

**Comment by kevmoo** [comment]
http_multi_server should be able to support a dependency of `>=0.11.0 <0.13.0` – but we should validate/verify this.

There is no clear owner of http_multi_server now, though

**Comment by tvolkert** [comment]
@jonahwilliams has a proposal out to trim down `flutter_test`'s transitive dependencies that we pick up through `test`.

**Comment by jmmartinezcdo** [comment]
I ran into this problem, so I ran the command: 
**`flutter update-packages --force-upgrade`**, 
which seemed to fix the problem, but now I get 
**`undefined class IOClient`** 
(I use IOClient to allow connection to urls with self signed certificates).

**Comment by kevmoo** [comment]
https://pub.dartlang.org/documentation/http/latest/io_client/io_client-library.html

Are you importing `package:http/http_io.dart` ?

**Comment by jmmartinezcdo** [comment]
@kevmoo :  I'm not importing it, I didn't have to before updating packages. 
However I just tried and can't. What it looks like is that flutter update-packages removed that package (http_io).

**Comment by kevmoo** [comment]
Someone is using the PACKAGE http_io? It's not published.

You mean the library pkg:http/http_io.dart?

**Comment by jonahwilliams** [comment]
@jmmartinezcdo `flutter update-packages --force-upgrade` is for development on flutter, not for flutter apps. This will modify the flutter repo in potentially unstable ways

**Comment by jmmartinezcdo** [comment]
Thanks @jonahwilliams  . What can I do to go back or reinstall original packages?

**Comment by jonahwilliams** [comment]
If you're familiar with git you can use `git checkout` to revert any changed files. Otherwise you will need to re-download flutter

**Comment by kevmoo** [comment]
Wouldn't 'git reset --hard' do the trick? (use w/ caution)

**Comment by jmmartinezcdo** [comment]
I reinstalled flutter and importing pkg:http/http.dart fixes the IOClient issue. 
However I'm back to original issue: cannot install cached_network_image : 
flutter_test from sdk is incompatible with cached_network_image >=0.5.0

**Comment by jmmartinezcdo** [comment]
I commented out flutter_test, that allows me to install cached_network_image as @raveesh-me  did, but after that, IOClient issue comes back. There is no http_io package to import.

**Comment by zoechi** [comment]
I think this issue is stale.
Please let us know if you are still seeing this.
