### ISSUE TITLE
ImagePicker -  libjpeg error 122 <Invalid SOS parameters for sequential JPEG>

### ISSUE THREAD

**Issue by mrdimaan** [flutter/flutter#23066]
Hi, I'm trying to upload an image and I'm getting this message:
```
D/skia    ( 1253): libjpeg error 122 <Invalid SOS parameters for sequential JPEG> from output_message
I/ExifInterface_JNI( 1253): Raw image not detected
I/ExifInterface( 1253): innerIfdHint: 1
I/ExifInterface_JNI( 1253): Raw image not detected
```
And the flutter doctor:
```
[~/Documents]$ flutter doctor -v                                                                                                                             
[✓] Flutter (Channel master, v0.10.1-pre.40, on Linux, locale en_US.utf8)
    • Flutter version 0.10.1-pre.40 at /home/moein/Documents/flutter-master
    • Framework revision 8e2ca93f52 (28 hours ago), 2018-10-12 21:07:55 -0700
    • Engine revision 50c2e69daf
    • Dart version 2.1.0-dev.7.0.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/moein/Android/Sdk
    • Android NDK at /home/moein/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • SM J730F • 5200f825ee301577 • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by tudor07** [comment]
@cyanglaz he means picking up an image using `iamge_picker` plugin. I have the same problem but it happens randomly on some Redmi device.

**Comment by jay2jp** [comment]
I have the same problem in my app.

**Comment by cbracken** [comment]
@mrdimaan can you add a reduced repro case and add details of your device? This error appears to be potentially device-specific. It would also be useful if you could attach an image that produces this behaviour.

Potentially related patch on the golang side: https://github.com/golang/go/commit/5f7bec693d3d383061586d6f29f4fea2648399a7

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
