### ISSUE TITLE
flutter cli output should have a constrained character width

### ISSUE THREAD

**Issue by CherryMan** [flutter/flutter#23074]
Some `flutter` help commands have very long lines, which look inconsistent and can be unreadable in very wide terminals. wrapping also becomes ugly for indenting text. Usually, commands will constrain their output to a certain character width, such as 80 characters.

Shorted width looks much nicer and more consistent, and is also easier to read.

**Comment by zoechi** [comment]
Looks related to #22831

@gspencergoog ?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by gspencergoog** [comment]
You can specify the wrapping width with `--wrap-column`.  It defaults to the width of the terminal, because for most users this is the right answer.

**Comment by CherryMan** [comment]
Ah, I forgot to mention this is specifically for the help menus, I think it's fine if normal output is constrained to terminal width. I should have been more specific about that. Below are a few examples. As you can see, the wrapping doesn't look very nice and makes the text unreadable.

`flutter build apk --help`
![image](https://user-images.githubusercontent.com/15808018/47055563-f705ad00-d185-11e8-9b7c-f12056fc5afd.png)

`flutter analyze --help`
![image](https://user-images.githubusercontent.com/15808018/47055632-65e30600-d186-11e8-9049-1c8f7b11d2f5.png)

**Comment by gspencergoog** [comment]
Turns out that, due to an oversight, some commands were not getting their usage wrapped.  This should be fixed when #28264 lands.
