### ISSUE TITLE
Can flutter access device heading & pitch, similar to how Google Sky Map works?

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [flutter/flutter#23073]
I'd like to access the devices heading and pitch data similar to how Google Sky Map works. Is Flutter able to access that data (with user permissions of course)?

I'm sorry for asking this in the issues forum, but Flutter is new enough that I can't seem to find anything about this already out on the net.

Thank you!

**Comment by zoechi** [comment]
If there is a plugin in https://pub.dartlang.org that provides that, you can use that or 
you can make native functionality available to flutter by 
https://flutter.io/developing-packages/#plugin

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
