### ISSUE TITLE
Need a way to trigger tap handler on a TextField()

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#23071]
I need to detect taps on a TextField. I'm trying to do this with GestureDetector, but it doesn't seem be working:

```dart
GestureDetector(
  behavior: HitTestBehavior.translucent,
  onTap: () {
    print('hi');
  },
  child: TextField(),
),
```

Nothing is printed when tapping.

Note that I need to perform an action every time the TextField is tapped, **even after it has focus**. Therefore, I don't believe utilizing FocusNode would work.

**Comment by mehmetf** [comment]
Also worth noting that, I tried using Stack since the use case is to trigger an action on a Widget that is outside of the TextField but:

```dart
Stack(
  children: [
    TextField(),
    GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTap: () {
        print('hi');
      },
      child: SizedBox(...),
    ),
  ],
)
```

and interestingly it did not work. Despite the translucent mode, I could not tap on TextField.

**Comment by berosoboy** [comment]
It's similar to #15882

**Comment by mehmetf** [comment]
@alanrussian See the comment above. The `IgnorePointer` widget might indeed work for you. It feels a bit of a hack since you have to manipulate the focus of the input text yourself but definitely workable.

**Comment by alanrussian** [comment]
Thanks, Mehmet. This seems to work for now (as long as we pass false to `ignoringSemantics`).

**Comment by mehmetf** [comment]
Closing as duplicate of #15882
