### ISSUE TITLE
Convert Future<int> to int in Flutter

### ISSUE THREAD

**Issue by marj29** [flutter/flutter#23084]
How to convert Future int to int in flutter?

Example: I have a function that return a Future int and I want to compare if the return output is greater than or equal to zero.

Thanks in advance

**Comment by tomkowz** [comment]
@marj29 in order to get value out of the future you need to use async/await.

```
class A {
  Future<int> getInt() {
    return Future.value(10);
  }
}

class B {
  checkValue() async {
    final val = await A().getInt();
    print(val == 10 ? "yes" : "no");
  }
}
```

You can find more on that in the [dart lang tutorials](https://www.dartlang.org/tutorials/language/futures).

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by marj29** [comment]
@tomkowz thank you so much for your response

**Comment by langaro** [comment]
@tomkowz Thank you. Just what I need.

**Comment by hekmatnajafi** [comment]
suppose you have a function called `getCount()` that returna a Future value.
simply do this:
`int count = await getCount();`
now you can use `count` variable any where needed.
