### ISSUE TITLE
flutter stdout ascii coloring breaks down in presence of warnings

### ISSUE THREAD

**Issue by aam** [flutter/flutter#23082]
See screenshot below - on Windows everything from the warning down is colored in yellow:
![image](https://user-images.githubusercontent.com/381137/46930172-ea078300-cff8-11e8-85ba-7fcfec64aa51.png)

**Comment by jonahwilliams** [comment]
Current doctor check looks OK on windows with warnings/errors. This is has probably been fixed since 2018
