### ISSUE TITLE
Rename StatefulComponent and StatelessComponent to StatefulWidget and StatelessWidget

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2308]

**Comment by HansMuller** [comment]
This seems like a healthy change. It would be nice if the two widget types didn't appear to be fundamentally different.  In other words it would be nice if they both were used like:

```
class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) { ... }
}

class MyWidget extends StatefulWidget {
  MyWidgetState createState() { ... }
  Widget build(BuildContext context, MyWidgetState state) { ... }
}
```
Doubtless not the right solution but. I think it would be easier for developers to understand our fundamentals if  these two classes were a little bit more symmetrical.

**Comment by abarth** [comment]
The trouble with `Widget build({ BuildContext context, MyWidgetState state }) { ... }` is that closures defined in that function will implicitly capture `this`, which is the widget rather than the state.

**Comment by Hixie** [comment]
also the build function wants to get at the State objects' members, typically

**Comment by sethladd** [comment]
Nice rename.

**Comment by apwilson** [comment]
You know that yesterday was March 1st and not April 1st, right?

**Comment by eseidelGoogle** [comment]
I'm supportive of this change, but I wonder if we shouldn't have a grand review (and resulting grand-rename) of our Widget APIs at once to minimize the burden on our customers?

**Comment by abarth** [comment]
@eseidelGoogle We've been accumulating rename issues with the label "rename fixit candidate".  I think it makes a lot of sense to do all the renames all at once.  We could even provide folks with a script to update their code automagically.

**Comment by sethladd** [comment]
If/when we do this, let's also comb through our website and rename everything there, too.
