### ISSUE TITLE
* Error running Gradle:

### ISSUE THREAD

**Issue by Sky24n** [flutter/flutter#23095]
## Steps to Reproduce

```
Launching lib\main.dart on Letv X500 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: D:\Program Files\Android\temp workspace\flutter_appp\android\gradlew.bat app:properties:
Parallel execution with configuration on demand is an incubating feature.

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Program Files\Android\temp workspace\flutter_appp\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.1.0-alpha01).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
   > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

Finished with error: Please review your Gradle project setup in the android/ folder.

## Logs

```
D:\Program Files\Android\temp workspace\flutter_appp\foo>flutter run
Launching lib/main.dart on Letv X500 in debug mode...
Initializing gradle...                                       1.2s
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: D:\Program Files\Android\temp workspace\flutter_appp\foo\android\gradlew.bat app:properties:
Parallel execution with configuration on demand is an incubating feature.

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Program Files\Android\temp workspace\flutter_appp\foo\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.1.0-alpha01).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
   > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.1.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Please review your Gradle project setup in the android/ folder.

```

```
D:\Program Files\Android\temp workspace\flutter_appp>flutter doctor -v
[√] Flutter (Channel beta, v0.8.2, on Microsoft Windows [Version 10.0.17134.345], locale zh-CN)
    • Flutter version 0.8.2 at D:\Develop\Flutter\flutter
    • Framework revision 5ab9e70727 (5 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at D:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = D:\sdk
    • Java binary at: D:\Develop\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Develop\Android\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at D:\Develop\JetBrains\IntelliJ IDEA 2017.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected devices (1 available)
    • Letv X500 • E6C6TKSKCUDM7P4T • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.

```

**Comment by pboos** [comment]
Just had this start to appear on my builds (on build server) today. Even though I didn't change anything in the dependencies.

**Comment by rodolph66** [comment]
I have just finished setting up flutter on windows 10 with Android Studio...

FLutter doctor output:

`C:\Users\Bob>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.28.2)
[√] Connected devices (1 available)

• No issues found!`

However when I perform the test drive I get the following in studio's console:

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: G:\flutter\flutter_test_01\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'G:\flutter\flutter_test_01\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Finished with error: Please review your Gradle project setup in the android/ folder.`

I am unable to move beyond this. I have tried Visual Studio Code and it also failed..!

**Comment by mrmitew** [comment]
Absolutely same thing here. I submitted a pull request that fixes it: https://github.com/flutter/flutter/pull/23397

**Comment by DaviDeMo89** [comment]
Same here... well I started to use flutter in the wrong time haha

**Comment by DaviDeMo89** [comment]
> > Same here... well I started to use flutter in the wrong time haha
> 
> Take a look at the PR I submitted earlier. It resolves the issue.

thank you, it's working

**Comment by pboos** [comment]
Strangely is that I do not get the problem locally. I wonder why not. Same version and everything I think. Just locally is Mac OS, build server is inside docker (linux).
So kind of hard to reproduce and fix on the build server.

@mrmitew how would you fix it on a build server?

**Comment by Sky24n** [comment]
Win10 OS run error

FAILURE: Build failed with an exception.

    Where:
    Build file 'D:\Program Files\Android\temp workspace\flutter_appp\android\app\build.gradle' line: 25

    What went wrong:
    A problem occurred evaluating project ':app'.

    Could not resolve all files for configuration 'classpath'.
    Could not find bundletool.jar (com.android.tools.build:bundletool:0.1.0-alpha01).
    Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01.jar
    Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
    Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
    Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.1.0).
    Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0.jar

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

**Comment by Sky24n** [comment]
@waleedbasit 
Temporary solution：
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

**Comment by waleedbasit** [comment]
@Sky24n it gives an error on distributionUrl

**Comment by Sky24n** [comment]
@waleedbasit 
distributionUrl is in gradle-wrapper.properties

**Comment by zoechi** [comment]
Merging with #23404

**Comment by waleedbasit** [comment]
@Sky24n  I updated distributionUrl and the classpath but it still gives the same error

**Comment by Sky24n** [comment]
@waleedbasit publish your error message

**Comment by Sky24n** [comment]
@ShowMeThe   build.gradle 用3.0.1
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

**Comment by mrmitew** [comment]
> Win10 OS run error
> 
> FAILURE: Build failed with an exception.
> 
> ```
> Where:
> Build file 'D:\Program Files\Android\temp workspace\flutter_appp\android\app\build.gradle' line: 25
> 
> What went wrong:
> A problem occurred evaluating project ':app'.
> 
> Could not resolve all files for configuration 'classpath'.
> Could not find bundletool.jar (com.android.tools.build:bundletool:0.1.0-alpha01).
> Searched in the following locations:
> https://jcenter.bintray.com/com/android/tools/build/bundletool/0.1.0-alpha01/bundletool-0.1.0-alpha01.jar
> Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
> Searched in the following locations:
> https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
> Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.1.0).
> Searched in the following locations:
> https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.1.0/aapt2-proto-0.1.0.jar
> 
> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> Get more help at https://help.gradle.org
> ```

It is evident from your error log that gradle isn't looking at the google's repo, but only at jcenter.
The `google()` repo has to be added *NOT* in your gradle file, but in flutter's. A pull request was already merged that fixes the problem (not sure if it was also merged in the beta or only in master).

**Comment by ViasVegas** [comment]
I found the solution there : https://github.com/flutter/flutter/pull/23397/commits/e93d19c0e7805e375b650ddf69009fa4549ad678#diff-d9b052388990c36138e397b5bb529025 thanks to @mrmitew . 
Just find the flutter.gradle file in your folder : flutter/package/flutter_tool/gradle and add 'google()' to the buildscript. It fixed the issue for me.

**Comment by OfficialSameer** [comment]
![error](https://user-images.githubusercontent.com/41697881/47515735-42643d80-d8a1-11e8-8ae5-89afb4dd0d12.PNG)

**Comment by juceliocalado** [comment]
Aqui tem a solução, nos textos anteriores explicam tbm... testei aqui e deu certo \0/...

https://github.com/mrmitew/flutter/commit/e93d19c0e7805e375b650ddf69009fa4549ad678

**Comment by nishp77** [comment]
> I found the solution there : [e93d19c#diff-d9b052388990c36138e397b5bb529025](https://github.com/flutter/flutter/commit/e93d19c0e7805e375b650ddf69009fa4549ad678#diff-d9b052388990c36138e397b5bb529025) thanks to @mrmitew .
> Just find the flutter.gradle file in your folder : flutter/package/flutter_tool/gradle and add 'google()' to the buildscript. It fixed the issue for me.

But where exactly. I'm so sorry but i can't it

**Comment by katyak** [comment]
@mrmitew solution worked for me. Thank you!

**Comment by dnfield** [comment]
We will be releasing a new beta soon that contains the fix for this.

**Comment by AmandaMML** [comment]
> **Making the answer Clear:** All you have to do is go to your have your flutter installed and make sure maven is above jcenter in the flutter.gradle file
> ![flutter_issue](https://user-images.githubusercontent.com/20386334/47843669-747f1d80-de14-11e8-97f1-26852c146268.PNG)

I've tried it. It doesn't work.

**Comment by aizuddineismail** [comment]
@AmandaMML Did you try adding google() ? I only followed this and it works!

> I found the solution there : [e93d19c#diff-d9b052388990c36138e397b5bb529025](https://github.com/flutter/flutter/commit/e93d19c0e7805e375b650ddf69009fa4549ad678#diff-d9b052388990c36138e397b5bb529025) thanks to @mrmitew .
> Just find the flutter.gradle file in your folder : flutter/package/flutter_tool/gradle and add 'google()' to the buildscript. It fixed the issue for me.

**Comment by AmandaMML** [comment]
> @AmandaMML Did you try adding google() ? I only followed this and it works!
> 
> > I found the solution there : [e93d19c#diff-d9b052388990c36138e397b5bb529025](https://github.com/flutter/flutter/commit/e93d19c0e7805e375b650ddf69009fa4549ad678#diff-d9b052388990c36138e397b5bb529025) thanks to @mrmitew .
> > Just find the flutter.gradle file in your folder : flutter/package/flutter_tool/gradle and add 'google()' to the buildscript. It fixed the issue for me.

Now it works!! Thank you @aizuddineismail !!

**Comment by Dhanabhon** [comment]
@aizuddineismail I've I've tried it. It Work!
Thanks

**Comment by Dhanabhon** [comment]
> @AmandaMML Did you try adding google() ? I only followed this and it works!
> 
> > I found the solution there : [e93d19c#diff-d9b052388990c36138e397b5bb529025](https://github.com/flutter/flutter/commit/e93d19c0e7805e375b650ddf69009fa4549ad678#diff-d9b052388990c36138e397b5bb529025) thanks to @mrmitew .
> > Just find the flutter.gradle file in your folder : flutter/package/flutter_tool/gradle and add 'google()' to the buildscript. It fixed the issue for me.

@aizuddineismail  I've I've tried it. It Work!
Thanks

**Comment by Jean-Baptiste-99** [comment]
C:\Users\###Jean_Baptiste\AndroidStudioProjects\flutter_app>flutter run
Launching lib\main.dart on TECNO LA7 in debug mode...
Running Gradle task 'assembleDebug'...
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\###Jean_Baptiste\AndroidStudioProjects\flutter_app\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> org/jetbrains/kotlin/cli/common/PropertiesKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 18s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       202,0s (!)
Exception: Gradle task assembleDebug failed with exit code 1


Svp j'ai besoin de votre aide
