### ISSUE TITLE
Remove the first link to "Flutter" on http://docs.flutter.io/

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2309]
On http://docs.flutter.io/ if you tell people to "click flutter" they might click the wrong one. We should make the first word Flutter not a link, and then add a "Learn more" link at the end of the paragraph or some such.

cc @sethladd

**Comment by sethladd** [comment]
For reference, here's the page: https://github.com/flutter/flutter/blob/master/doc/index.html
