### ISSUE TITLE
Flutter Listview autoscroll scrollController.animateTo could not work in iOS

### ISSUE THREAD

**Issue by lbkhanh** [flutter/flutter#23090]
Hi Team,

I have faced problem with method scrollController.animateTo.
It could scroll automatically to specified Index with fixed height item on Android but it could not work in iOS.
Could you please help me to check?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the code (minimal runnable reproduction) that allows to reproduce the issue.

**Comment by lbkhanh** [comment]
Hi zoechi,

Please refer to below for **flutter doctor -v**

Les-MacBook-Pro:cls_mobile lbkhanh$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14.1 18B57c, locale en-US)
    • Flutter version 0.9.4 at /Users/lbkhanh/Desktop/Flutter/flutter_android/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/lbkhanh/Library/Android/sdk
    • Android NDK at /Users/lbkhanh/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • Testflight’s iPhone • 151a3b628eb4a2059ca349c391306f4bfdf03e5d • ios • iOS 12.0.1

• No issues found!

And the code is 

```
void goToElement(int index) {
      _scrollController.animateTo((105.0 * index),
          duration: const Duration(milliseconds: 1000),
          curve: Curves.easeOut);
  }
```

**Comment by goderbauer** [comment]
Can you post some code that I can just copy and paste to run that demonstrates the issue? In my little example, the little snippet you posted works just fine (assuming that the item height is 105).

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
