### ISSUE TITLE
Allocating a FlutterViewController after app startup is slow

### ISSUE THREAD

**Issue by sundayman** [flutter/flutter#23093]
On iPhone6 more than 300ms cost
On iPhoneX more than 80ms cost
I add Flutter to my existing app, it is a bad user experience when open Flutter ViewController first time 

Is it possible to improve performance here ？

**Comment by zoechi** [comment]
#22363, #22133 look related

**Comment by sundayman** [comment]
flutter doctor -v
[✓] Flutter (Channel master, v0.10.1-pre.40, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 0.10.1-pre.40 at /Users/zjq/Documents/flutter_biz/flutter
    • Framework revision 8e2ca93f52 (3 days ago), 2018-10-12 21:07:55 -0700
    • Engine revision 50c2e69daf
    • Dart version 2.1.0-dev.7.0.flutter-b99bcfd309

**Comment by zoechi** [comment]
Would you mind adding the full `flutter doctor -v` output?

**Comment by sundayman** [comment]
[✓] Flutter (Channel master, v0.10.1-pre.49, on Mac OS X 10.13.6 17G65, locale
    zh-Hans-CN)
    • Flutter version 0.10.1-pre.49 
    • Framework revision 707eaf5edf (30 hours ago), 2018-10-15 21:30:40 -0700
    • Engine revision 08272ee6aa
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

**Comment by dnfield** [comment]
Pre-warm your engine by allocating a `FlutterEngine` (e.g. in your AppDelegate) first and using the `FlutterViewController initWithEngine` initializer.  It should speed things up.

**Comment by sundayman** [comment]
Can FlutterEngine be allocate at a thread (not platform thread)  @dnfield 
Thanks

**Comment by dnfield** [comment]
It's not a configuration we really test for.  I think it's possible but I'm not sure what might go wrong.  Basically the engine will assume whatever thread it's running on is the platform thread.  I suppose you could try spinning up a thread and starting the engine on that.

**Comment by sundayman** [comment]
I Found there are three expensive operation:
1、IOSGLContext  allocate first time ( for iOS)
2、Dart_CreateIsolate call first time (Low-end machine）
3、Engine allocate ( Android) (almost cost 70% start up time)
      ```
  engine = std::make_unique<Engine>(*shell,                        //
                                          shell->GetDartVM(),            //
                                          std::move(isolate_snapshot),   //
                                          std::move(shared_snapshot),    //
                                          task_runners,                  //
                                          shell->GetSettings(),          //
                                          std::move(animator),           //
                                          std::move(snapshot_delegate),  //
                                          std::move(resource_context),   //
                                          std::move(unref_queue)         //
```


**Any ideal  why Engine allocate so expensive on Android**

**Comment by sprhawk** [comment]
> Pre-warm your engine by allocating a `FlutterEngine` (e.g. in your AppDelegate) first and using the `FlutterViewController initWithEngine` initializer. It should speed things up.


I setup an instance of Engine in AppDelegate: 
```
var flutterEngine: FlutterEngine!
    func setupFlutter() {
        if nil == self.flutterEngine {
            flutterEngine = FlutterEngine(name: "flutter.safe2save", project: nil)
            flutterEngine.run(withEntrypoint: "/")
        }
    }
```

push view controller here:

```
if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
            let engine = appDelegate.flutterEngine
            let viewCon = FlutterViewController.init(engine: engine, nibName: nil, bundle: nil)!
            viewCon.setInitialRoute("/register")
            let _ = viewCon.view
            self.navigationController?.pushViewController(viewCon, animated: true)
        }
```

But it shows blank black screen

**Comment by zoeyfan** [comment]
@xster I wonder with the new Add to App work, is this going to be better?

**Comment by jmagman** [comment]
There has been some work to improve performance: https://github.com/flutter/flutter/issues/32945#issuecomment-513387195

If you're still seeing this, can you see if it's better on the current stable version of Flitter?
