### ISSUE TITLE
Unable to reuse views in flutter using appdrawer

### ISSUE THREAD

**Issue by AnandAron** [flutter/flutter#23107]
HomePage.dart

```dart
class _HomePageState extends State<HomePage> {
var _scaffoldBody;
var _scaffoldTitle;

@override
initState() {
    _scaffoldTitle=new Text("Wall");
    _scaffoldBody=new Center(child:CircularProgressIndicator());
}


@override
Widget build(BuildContext context) {
return Scaffold(

    drawer: new Drawer(
      child: ListView(

        padding: EdgeInsets.zero,
        children: <Widget>[
          DrawerHeader(
            child: Text('Drawer Header'),
            decoration: BoxDecoration(
                color:Theme.of(context).accentColor,
            ),
          ),
          ListTile(
            title: Text('Home'),
            onTap: () {

              setState(() {
                _scaffoldTitle=new Text("Home");
                _scaffoldBody=new Text("Home Page");
              });

              Navigator.pop(context);
            },
          ),
          ListTile(
            title: Text('MenuItem1'),
            onTap: () {

              setState(() {
                _scaffoldTitle=new Text("1st Menu");
                _scaffoldBody=new TestPage("Page 1");
              });

              Navigator.pop(context);
            },
          ),
          ListTile(
            title: Text('MenuItem2'),
            onTap: () {

              setState(() {
                _scaffoldTitle=new Text("2nd Item");
                _scaffoldBody=new TestPage("Page 2");
              });

              Navigator.pop(context);
            },
          ),
        ],
      ),
    ),
    appBar: new AppBar(

      title: _scaffoldTitle,
      elevation: 2.0,
      actions: <Widget>[
      ],
    ),
    body:_scaffoldBody,

);
```

TesPage.dart

```dart
import 'package:flutter/material.dart';
class TestPage extends StatefulWidget{
  final String rollNumber;
  TestPage(this.rollNumber);

  @override
  TestPageState createState() => new TestPageState(rollNumber);

}
class TestPageState extends State<TestPage>{
  String rollNumber;
  TestPageState(this.rollNumber);
  @override
  Widget build(BuildContext context) {
    return new  Text(rollNumber);
  }

}
```
Output:

- When I chose : "Home" from drawer it shows "Home Page"
- Then I chose : "MenuItem1" it showed "Page 1"
- Then I chose : "MenuItem2" it showed same "Page 1" (unexpected)
- Then I chose : "Home" it showed "Home Page"
- Then I chose : "MenuItem2" it showed correctly as "Page 2"
- Then I chose : "MenuItem1" it showed "Page 2" (unexpected)

Cant solve. Help me. Thanks in advance.!!

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by AnandAron** [comment]
Output of flutter doctor -v

[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_IN)
    • Flutter version 0.5.1 at /home/malyf/flutter
    • Framework revision c7ea3ca377 (5 months ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /home/malyf/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /home/malyf/Android/Sdk
    • Java binary at: /home/malyf/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /home/malyf/android-studio
    • Flutter plugin version 23.1.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Related SO question https://stackoverflow.com/questions/52821490/flutter-unable-to-reuse-views-in-appdrawer

**Comment by AnandAron** [comment]
Yeah It is my post!

**Comment by zoechi** [comment]
Is this still an issue?
