### ISSUE TITLE
Support --flutter-assets-dir flag in flutter_tester for assets

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#23103]
This flag is currently passed to the tester with the bundle path which points to the SDK location. This is done so that the tester can load the platform dill files. This was done as part of Dart 2 migration (https://github.com/flutter/flutter/pull/14135). We need to:

- [x] Provide a new flag/property to tell the tester where the dill files are.
- [ ] Repurpose the --flutter-assets-dir so we can support tests that load assets (and consequently support testing of widgets that load assets).

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/12999

**Comment by mehmetf** [comment]
This is now obsolete. As discussed extensively in https://github.com/flutter/flutter/issues/23179, we will need to document this limitation and solve for explicit use cases rather than blanket asset support.
