### ISSUE TITLE
ExpansionTile within ListView doesn't scroll when fully expanded and off the screen

### ISSUE THREAD

**Issue by sjmcdowall** [flutter/flutter#23100]
## Steps to Reproduce

Use the ExpansionTile sample app that is part of the examples area within an iOS emulated devices with the latest OS.  I used both an 8 Plus and an X. 

Run and open up all the possible Tiles ... 

Note that the list (see attachment) goes behind the window yet it doesn't scroll .. 

<img width="426" alt="screen shot 2018-10-15 at 9 38 38 am" src="https://user-images.githubusercontent.com/2034925/46958516-99774080-d05f-11e8-93e7-15bad056124c.png">

## Logs

Nothing in the logs happened after the "To hot reload ..." message.

```
Analyzing flutter_treeview...

   info • Unused import: 'package:flutter_treeview/main.dart' • test/widget_test.dart:10:8 • unused_import
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' • test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'MyApp' • test/widget_test.dart:15:33 • undefined_class
```

```
 …/play/flutter_treeview  flutter doctor -v                                                                    1 ↵  10190  09:47:04
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en)
    • Flutter version 0.9.4 at /Users/sjm/Development/tools/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sjm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (2 available)
    • iPhone 8 • 0CF10D1F-D5FD-4887-BCA1-6BE9818C5AB7 • ios • iOS 12.0 (simulator)
    • iPhone X • 78590509-1E81-4378-8BDE-92EBAFDB00A0 • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by jslavitz** [comment]
@sjmcdowall Have you found this to be an issue only in the gallery app or framework wide? You should certainly be able to put list views in scrollables!

**Comment by sjmcdowall** [comment]
Gallery app only?  No -- I first saw this in my app and wondered if I was missing something obvious -- so then I figured I'd tried the gallery app and when it was also not scrolling figured I'd submit a bug ... 

Cheers!

**Comment by jmolins** [comment]
I tested the[ sample app](https://flutter.io/catalog/samples/expansion-tile-sample/) in my Android physical device and the scrolling works properly.

**Comment by sjmcdowall** [comment]
I’ll have to try it on Android simulator .. I only tried it on an iOS simulator .. will try physical device too

**Comment by sjmcdowall** [comment]
OK -- User error -- appears that to "scroll" in the simulators -- one needs to hold the mouse button down and GESTURE .. just gesturing doesn't do it.  DOH!  :)
