### ISSUE TITLE
`flutter run` inconsistently shows compilation errors for imported dart libraries 

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#23121]
## Steps to Reproduce

1. Modify `flutter/examples/hello_world/lib/main.dart` to add a line: `import foo.dart;`
2. Add a `flutter/examples/hello_world/lib/foo.dart` file.  Add some garbage to it that won't compile (e.g. a single line containing `asdf`).
3. Invoke `flutter run`.  It reports a compilation error and fails, as expected:

```
$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                           0.7s
Resolving dependencies...                                        1.3s
Gradle task 'assembleDebug'...                                  

Compiler message:
lib/foo.dart:1:1: Error: Variables must be declared using the keywords 'const',
'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
asdf
^^^^
lib/foo.dart:1:1: Error: Expected ';' after this.
asdf
^^^^
Compiler failed on
/home/jamesdlin/git/flutter/flutter/examples/hello_world/lib/main.dart
 6.3s
Gradle task assembleDebug failed with exit code 1
```

4. Without modifying any files, invoke `flutter run` again.  

## Result
I expect to see the same failure as in step 3.  Instead `flutter run` syncs files to the emulator, runs the app, and doesn't show the error:

```
$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                           0.7s
Resolving dependencies...                                        1.2s
Gradle task 'assembleDebug'...                                   8.4s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                      0.6s
D/        ( 4463): HostConnection::get() New Host Connection established
0xe9e08bc0, tid 4484
D/EGL_emulation( 4463): eglMakeCurrent: 0xebc2dae0: ver 2 0 (tinfo 0xe9e036d0)
Syncing files to device Android SDK built for x86...             1.0s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available
at: http://127.0.0.1:38847/
For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
```
I see this behavior only with compilation errors in imported files; if I instead introduce compilation errors into `main.dart`, `flutter run` consistently fails.

## Doctor

```
[✓] Flutter (Channel master, v0.10.1-pre.43, on Linux, locale en_US.UTF-8)
    • Flutter version 0.10.1-pre.43 at /home/jamesdlin/git/flutter/flutter
    • Framework revision 4f4005ee65 (2 hours ago), 2018-10-15 12:18:13 -0700
    • Engine revision 50c2e69daf
    • Dart version 2.1.0-dev.7.0.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/jamesdlin/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /home/jamesdlin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/jamesdlin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Is this still reproducable?

**Comment by zoechi** [comment]
Are you still seeing this with recent Flutter version?

**Comment by jamesderlin** [comment]
Yes, it still occurs (Channel master, v0.8.3-pre.1031, on Linux, locale en_US.UTF-8).  It is quite easy to reproduce.

**Comment by kangwang1988** [comment]
@jamesderlin 
Have you ever tried the latest master?
v0.8.3-pre.1031 is quite old.

**Comment by jamesderlin** [comment]
I didn't think 0.8.3 sounded right, but I did do `git fetch upstream master` and `flutter upgrade` first.  I've been on leave for the past few weeks so I might have forgotten a step, but `flutter doctor -v` says:

[✓] Flutter (Channel master, v0.8.3-pre.1031, on Linux, locale en_US.UTF-8)
    • Flutter version 0.8.3-pre.1031 at /home/jamesdlin/git/flutter/flutter
    • Framework revision 150079db6e (31 minutes ago), 2019-01-14 15:21:06 +0000
    • Engine revision abbc34e148
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 f81dd1da9f)

**Comment by kangwang1988** [comment]
@jamesderlin  
Got it.
Will try tomorrow. It's wee hours now, Shanghai time.

**Comment by kangwang1988** [comment]
@jamesderlin 
It's a bug.
Now, app.dill will always be generated no matter there is a compilation error.
In this case.
In the first run, app.dill is generated(frontend_server.dart.snapshot) with reporting an error.
In the second run, app.dill will not be generated as there is no changes and all files compiled in the app.dill. So there is no error reported, which resulted in this weird thing.
<img width="1436" alt="screen shot 2019-01-15 at 3 43 43 pm" src="https://user-images.githubusercontent.com/817851/51165832-71a4ac80-18dc-11e9-958a-25b97712f6b3.png">

**Comment by mraleph** [comment]
I have filed an upstream bug for this. Thanks for reporting @jamesderlin!

**Comment by zoechi** [comment]
@mraleph I assume the upstream issue is https://github.com/dart-lang/sdk/issues/35666
Please correct if wrong

**Comment by zoechi** [comment]
@jamesderlin are you still seeing this? I think it should be fixed.

**Comment by jamesderlin** [comment]
Yes, looks fixed.
