### ISSUE TITLE
The Send icon from the code lab has horrific aliasing

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#2313]
It should look like this, but orange:

![material-send-icon](https://storage.googleapis.com/icons.google.com.a.appspot.com/google-assets/system_icons/quantum/content/res-export/ic_send_48px.svg)

Instead, it looks like this:

![flutter-send-icon](https://cloud.githubusercontent.com/assets/926648/13446980/a92f1358-dfcc-11e5-8513-b1a78c76ce02.png)

Notice the warbly edges.

(See also #1831)

**Comment by abarth** [comment]
What platform/device were you using?

/cc @krisgiesing

**Comment by appsforartists** [comment]
Android on a Nexus 5x

**Comment by abarth** [comment]
I'm going to solve this with #994

**Comment by eseidelGoogle** [comment]
Looks great.  I'm sure the memory profile is different now, since we're trading GlpyhPageCacheNodes for BitmapImages at the c++ level.  Probably a win in that regard too, but hard to know.
