### ISSUE TITLE
Make duration of InkSplash configurable

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#23142]
The duration of the InkSplash is currently hardcoded, would be nice to make that one configurable.

**Comment by HansMuller** [comment]
The splash/ripple system is a bit complicated.

Buttons are other components that generate a splash upon tap incorporate an [InkWell](https://docs.flutter.io/flutter/material/InkWell-class.html). The InkWell can be configured with a [splashFactory](https://docs.flutter.io/flutter/material/InteractiveInkFeatureFactory-class.html). By default the splashFactory is defined by the Theme. Splash factories can return an [InkSplash](https://docs.flutter.io/flutter/material/InkSplash-class.html) or an [InkRipple](https://docs.flutter.io/flutter/material/InkRipple-class.html) or a custom [InteractiveInkFeature](https://docs.flutter.io/flutter/material/InteractiveInkFeature-class.html).

Applications that configure [ThemeData.splashFactory](https://docs.flutter.io/flutter/material/ThemeData/splashFactory.html) might want to subclass InkSplash (2 animation controllers) or InkRipple (3 animation controllers).  Currently, subclasses can easily reconfigure some aspects of the ink's appearance, but not the animations. 

So: what kinds of animation changes we should enable for InkSplash and InkRipple subclasses? Is it really just the duration of InkSplash's two AnimationControllers?

For example: more flexible approach for InkRipple would be to give subclasses a way to define the durations and Tweens for its fade-in, radius, and fade-out animations.  See also: [TweenSequence](https://docs.flutter.io/flutter/animation/TweenSequence-class.html).

**Comment by HansMuller** [comment]
@jszczygiel - There's a version of InkRipple whose animations and durations can be configured through subclassing here: https://github.com/flutter/flutter/pull/23265.  A diff you can apply to a local repo would be https://patch-diff.githubusercontent.com/raw/flutter/flutter/pull/23265.diff

I'd appreciate it if you'd try this out carefully enough to decide if subclassing InkRipple is cleaner (for your use case) than writing a custom InteractiveInkFeature based on a copy of InkRipple.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by jszczygiel** [comment]
Hello zoechi, sorry for long silence. I was moved to other task with higher prioriety. Change presented by HansMuller looks good.
