### ISSUE TITLE
debugPrint() throws error on NULL values

### ISSUE THREAD

**Issue by FViscardi** [flutter/flutter#23149]
Is it intended behavior for `debugPrint()` to not handle `null` values?

In  flutter/packages/flutter/lib/src/foundation/print.dart:
```dart
 /// Implementation of [debugPrint] that throttles messages. This avoids dropping
 /// messages on platforms that rate-limit their logging (for example, Android).
 void debugPrintThrottled(String message, { int wrapWidth }) {
   if (wrapWidth != null) {
     _debugPrintBuffer.addAll(message.split('\n').expand<String>((String line) => debugWordWrap(line, wrapWidth)));
   } else {
     _debugPrintBuffer.addAll(message.split('\n'));
   }
   if (!_debugPrintScheduled)
     _debugPrintTask();
 }
```

The line `message.split('\n')` will throw a `NoSuchMethodError`, if `message` happens to be `null`.

To reproduce:
```dart
String test;
debugPrint( test );
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by FViscardi** [comment]
Sure:

> $ flutter doctor -v
> [✓] Flutter (Channel beta, v0.8.2, on Linux, locale en_US.UTF-8)
>     • Flutter version 0.8.2 at /home/wdva/flutter
>     • Framework revision 5ab9e70727 (6 weeks ago), 2018-09-07 12:33:05 -0700
>     • Engine revision 58a1894a1c
>     • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     • Android SDK at /home/wdva/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /home/wdva/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.2)
>     • Android Studio at /home/wdva/android-studio
>     • Flutter plugin version 29.1.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [✓] Connected devices (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> • No issues found!

**Comment by goderbauer** [comment]
This should totally handle null values. Working on a fix.
