### ISSUE TITLE
Ability to debug with Flutter drive

### ISSUE THREAD

**Issue by jonsamwell** [flutter/flutter#23145]
Hi,

I can't see any way debugging integration tests run with flutter drive.

On the wiki page for integration tests it only mentions how to run them via the command line not debug them from an IDE like vscode. 

https://flutter.io/cookbook/testing/integration-test-introduction/

My integration test are getting quick complication now so it would be good to know how to debug them or if you cannot currently do that add the ability to.

Thanks,

**Comment by zoechi** [comment]
Can you please elaborate?
A concrete example of what you try to test and what you want to debug would probably be helpful.

**Comment by jonsamwell** [comment]
@zoechi I have figured this out.

**Comment by tevaAutomation** [comment]
> @zoechi I have figured this out.

could you share with me the solution? i also don't know how to debug integration test.i tried the ObservatoryVM but i couldn't debug with it.
i'll appreciate if you can help me with it.

**Comment by jonsamwell** [comment]
@tevaAutomation I can't actually find the vs launch.json config I used to debug the tests.  However, what I had to do was.

1) Launch the app under test (which enables flutter driver) using a command line.
```flutter run --target="test_driver/app.dart"```
2) That will tell you the observatory debugger uri (something like http://127.0.0.1:54215/)
3) Set the environment variable "VM_SERVICE_URL" with the uri from the previous step.  This will allow the Flutter Driver to connect to and driver the app.
4) Then start the debugger (having set the environment variable above) pointing at your integration test file.
5) The driver should now connect and you can debug!

It was a bit of a pain and I wanted to integration tests in BDD style so I created a library to do this.  Debugging tests in the is as simple as putting a breakpoint on and starting the debugger as it does the above for you https://github.com/jonsamwell/flutter_gherkin (pub package https://pub.dartlang.org/packages/flutter_gherkin)

**Comment by bigbang489** [comment]
> @tevaAutomation I can't actually find the vs launch.json config I used to debug the tests. However, what I had to do was.
> 
> 1. Launch the app under test (which enables flutter driver) using a command line.
>    `flutter run --target="test_driver/app.dart"`
> 2. That will tell you the observatory debugger uri (something like http://127.0.0.1:54215/)
> 3. Set the environment variable "VM_SERVICE_URL" with the uri from the previous step.  This will allow the Flutter Driver to connect to and driver the app.
> 4. Then start the debugger (having set the environment variable above) pointing at your integration test file.
> 5. The driver should now connect and you can debug!
> 
> Your launch.json should look something like this (you'll have to update the uri in the "env" section every time you restart the app to test)
> 
> ```json
> {
>   // Use IntelliSense to learn about possible attributes.
>   // Hover to view descriptions of existing attributes.
>   // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "name": "Flutter",
>       "request": "launch",
>       "type": "dart"
>     },
>     {
>       "name": "Debug intergration test",
>       "request": "launch",
>       "type": "dart",
>       "env": {
>         "VM_SERVICE_URL": "http://127.0.0.1:54215/"
>       },
>       "program": "test_driver/app_driver_test.dart",
>       "flutterMode": "debug"
>     }
>   ]
> }
> ```
> 
> It was a bit of a pain and I wanted to integration tests in BDD style so I created a library to do this. Debugging tests in the is as simple as putting a breakpoint on and starting the debugger as it does the above for you https://github.com/jonsamwell/flutter_gherkin (pub package https://pub.dartlang.org/packages/flutter_gherkin)

I added as your suggestion to launch.json, but every time I start it from vscode, it always restarts my flutter app, and the driver cannot connect to the application. Anyone can help me to start debugging dart app without restart the application in my simulator?
