### ISSUE TITLE
Getting error : SocketException: OS Error: Connection refused

### ISSUE THREAD

**Issue by tripathiaman** [flutter/flutter#23147]
Hi, I am new to Flutter and tried the example from URL https://flutter.io/cookbook/networking/fetch-data/ to get understanding on how to consume Rest API. 

But I am getting error 

> SocketException: OS Error: Connection refused, errno = 111"

Any Idea what could be the issue.

## Steps to Reproduce

Example from https://flutter.io/cookbook/networking/fetch-data/. 

```dart
Future<Post> fetchPost() async {
  final response =
      await http.get('https://jsonplaceholder.typicode.com/posts/1');

  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON
    return Post.fromJson(json.decode(response.body));
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load post');
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by tripathiaman** [comment]
C:\WINDOWS\system32>flutter doctor -v
[ΓêÜ] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 6.1.7601], lo
cale en-US)
    ΓÇó Flutter version 0.9.4 at C:\work\SelfBuild\Flutter\flutter
    ΓÇó Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    ΓÇó Engine revision 74625aed32
    ΓÇó Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ΓÇó Android SDK at C:\Users\ah0179816.HEWITT-NA\AppData\Local\Android\sdk
    ΓÇó Android NDK location not configured (optional; useful for native profili
ng support)
    ΓÇó Platform android-27, build-tools 27.0.3
    ΓÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b
02)
    X Android license status unknown.

[ΓêÜ] Android Studio (version 3.1)
    ΓÇó Android Studio at C:\Program Files\Android\Android Studio
    ΓÇó Flutter plugin version 28.0.1
    ΓÇó Dart plugin version 173.4700
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b
02)

[ΓêÜ] VS Code, 64-bit edition (version 1.28.1)
    ΓÇó VS Code at C:\Program Files\Microsoft VS Code
    ΓÇó Flutter extension version 2.19.0

[ΓêÜ] Connected devices (1 available)
    ΓÇó Android SDK built for x86 ΓÇó emulator-5554 ΓÇó android-x86 ΓÇó Android
P (API 27) (emulator)

! Doctor found issues in 1 category.

C:\Windows\System32>

**Comment by zoechi** [comment]
My guess would be that this is a network issue, not a Flutter issue.
If you open the browser in the emulator and open the URL `https://jsonplaceholder.typicode.com/posts/1`, does it show the JSON content?

**Comment by tripathiaman** [comment]
Yes, I can  access this through browser. Moreover, I also tried this through calling this rest api through c# and didn't get any issue on that.

![image](https://user-images.githubusercontent.com/10772218/47018486-78534480-d172-11e8-9008-4919ea329c43.png)

**Comment by zoechi** [comment]
I meant

> the browser in the emulator

not the desktop browser.

**Comment by zoechi** [comment]
https://developer.android.com/studio/run/emulator-networking should help.

I'm closing this issue because this is unrelated to Flutter.

**Comment by AppleEducate** [comment]
This still happens to me on a real device

**Comment by zoechi** [comment]
@AppleEducate please create a new issue with full information.

**Comment by AppleEducate** [comment]
Will do.

**Comment by Karlheinzniebuhr** [comment]
@AppleEducate could you link your new issue? I'm having the same problem but on my localhost

**Comment by AppleEducate** [comment]
Haven’t created an issue yet, this is similar though: https://github.com/flutter/flutter/issues/27883

**Comment by Karlheinzniebuhr** [comment]
Just noticed that my phone is not on my local network, my bad :D

**Comment by AppleEducate** [comment]
That would do it!

**Comment by jawand** [comment]
Consider, closing the httpClient object by calling `http.close();` after the use.

**Comment by irakli1990** [comment]
i have same problem can somene help me?

```
  Future<CountryMapper> _sendCountryBorder(CountryBorder border) async {
    var data = {
      "CountryFrom": border.countryFrom,
      "CountryTo": border.countryTo,
      "IDDriver": border.iDDriver,
      "EnteryTime": "\/Date(${border.dateTime.millisecondsSinceEpoch})\/"
    };
    var body = json.encode(data);
    print(body);
    final response = await http.post('$endpoint',
        headers: {HttpHeaders.contentTypeHeader: 'application/json'},
        body: body);
    return borderFromJson(response.body);
  }

  CountryMapper borderFromJson(String str) {
    final jsonData = json.decode(str);
    return CountryMapper.fromJson(jsonData);
  }
```


```
FlatButton(
                    child: Text('TAK'),
                    onPressed: () => this.borderList.forEach((countryBorder) {
                          _sendCountryBorder(countryBorder);
                        })),
```

any idea someone?

{"CountryFrom":"ARM","CountryTo":"AUT","IDDriver":"246","EnteryTime":"/Date(1565690400000)/"}
E/flutter (23258): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = tsonlinenew.tachoapi.com, port = 41542
E/flutter (23258): #0      IOClient.send (package:http/src/io_client.dart:33:23)
E/flutter (23258): <asynchronous suspension>
E/flutter (23258): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter (23258): <asynchronous suspension>
E/flutter (23258): #2      BaseClient.post (package:http/src/base_client.dart:54:7)
E/flutter (23258): #3      post.<anonymous closure> (package:http/http.dart:70:16)
E/flutter (23258): #4      _withClient (package:http/http.dart:166:20)
E/flutter (23258): <asynchronous suspension>
E/flutter (23258): #5      post (package:http/http.dart:69:5)
E/flutter (23258): #6      _BordersListPageState._sendCountryBorder (package:techo_speed/src/ui/borders.dart:87:28)
E/flutter (23258): <asynchronous suspension>
E/flutter (23258): #7      _BordersListPageState._sendToServer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:techo_speed/src/ui/borders.dart:154:27)
E/flutter (23258): #8      List.forEach (dart:core-patch/growable_array.dart:278:8)
E/flutter (23258): #9      _BordersListPageState._sendToServer.<anonymous closure>.<anonymous closure> (package:techo_speed/src/ui/borders.dart:153:54)
E/flutter (23258): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (23258): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (23258): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23258): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (23258): #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (23258): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (23258): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (23258): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (23258): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (23258): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23258): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23258): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23258): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23258): #23     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (23258): #24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23258): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23258): #26     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (23258): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (23258):

**Comment by irakli1990** [comment]
sorry did not mentioned that issue is closed.

**Comment by Agonz937** [comment]
Getting the same issue for iOS

**Comment by mohamed-eltwahy** [comment]
Exception has occurred.
SocketException (SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 53424)

the same error
