### ISSUE TITLE
firebase messaging, push message onMessage and onLaunch, onResume is different on Android

### ISSUE THREAD

**Issue by pepegich** [flutter/flutter#23148]
I am use:
  firebase_messaging: 2.0.1
  firebase_storage: 1.0.4

in `2.0.1` version I cant use common function for parse data from `onMessage` and `onResume`. I must write two version of parse function.

Message from https://console.firebase.google.com:

`onMessage` (2.0.1):
```
{notification: {body: hello message, title: null}, data: {my_message: hello message, click_action: FLUTTER_NOTIFICATION_CLICK}}
```

`onResume` (2.0.1):
```
 {google.sent_time: 1539686964594, click_action: FLUTTER_NOTIFICATION_CLICK, google.original_priority: high, collapse_key: 'value', google.delivered_priority: high, my_message: hello message, from: 704725088829, google.message_id:''value, google.ttl: 2419200}
```
why structure of message is different? 
in the 1.05 there was no problem

`onMessage` (1.0.5):
```
{my_message: hello message, click_action: FLUTTER_NOTIFICATION_CLICK}
```

flutter doctor
```
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.14 18A391, locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
[✓] Connected device (1 available)
```

**Comment by va-andrew** [comment]
+1 for this, I much preferred not having to write target platform checks everywhere

**Comment by eoinfogarty** [comment]
I think its because of this pr that added notification title and body to be sent to flutter.
It added separate `notification` and `data` objects for android. It leaves ios as the plain apns payload 

https://github.com/flutter/plugins/pull/672

The thing is this pr is an accurate reflection of how android messages in firebase are represented.
But it puts a mulligan on our ability to use a single parsing method.

The workaround for us is to ensure when we send a payload to an ios device it is wrapped in a `data` object so flutter will receive the same data from android and ios.

**Comment by eoinfogarty** [comment]
And the above pr only targeted `onMessage` on android so we need to have separate handling for this one instance

**Comment by collinjackson** [comment]
flutter/plugins/pull/957 looks like a good fix, waiting for @pepegich to agree to CLA so I can merge it

**Comment by josejbarneto** [comment]
I'm still having OP problem, isnt fixed yet?

**Comment by kroikie** [comment]
@ivk1800

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/608. Any further collaboration will be done there.
