### ISSUE TITLE
Allow plugin authors to force their code to only execute in development/ dev_dependencies

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter#23154]
Hey there -- I have a plugin ([flutter_stetho](https://github.com/brianegan/flutter_stetho)) that should be used only during development for inspecting Network requests and Databases for Flutter apps. 

I ask users to use a `main.dart` and `main_dev.dart` so they can instantiate the code only during their dev process, and to include the plugin only in the `dev_dependencies` section in the `pubspec.yaml` file.  

However, if you build the app in production mode using the `main.dart` entry point, I believe the Dart code will be properly removed / tree shaken, but the Android plugin code is still being shipped. That makes the app size larger, and potentially makes Stetho a security risk (might accidentally allow users to inspect the Database or network requests)

Is there a way for plugin authors to indicate to Flutter: "Hey, only include this Android/iOS for Dev builds, but not for production builds"?

Also, more of a General Question: I was a bit confused as to why `dev_dependencies` are being included in Production builds at all. Is this by design? If so, could you describe why / when those are included?

**Comment by jmagman** [comment]
I split out that last question about dev_dependencies re: iOS to https://github.com/flutter/flutter/issues/49101

**Comment by jonahwilliams** [comment]
I think this is essentially the same as https://github.com/flutter/flutter/issues/45714

**Comment by jmagman** [comment]
@jonahwilliams Does that one need to be re-titled then and this one duped over?  I can't say I got the request from the "native buildscripts" part (at least for iOS, this would require changing CocoaPods logic):
```
pod 'dev_only_plugin', :configuration => 'Debug'
```

**Comment by jonahwilliams** [comment]
I think it is similar in spirit. Though FWIW I think it would be a mistake to conditionally include dependencies based on runtime mode

**Comment by jonahwilliams** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/45714
