### ISSUE TITLE
Running unit tests with coverage enabled takes up to 10x times longer than without coverage

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#23157]
I have a test suite of 150 tests (unit tests, and widget tests). If I run them **without coverage** enabled (`flutter test`), they take less than **10 seconds** to run; however, if I **enabled coverage**, (`flutter test --coverage --coverage-path ./coverage/lcov.info`), then it takes around **1 minute and 40 seconds**.

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.1)
[✓] VS Code (version 1.28.1)
[✓] Connected devices (1 available)

• No issues found!
```
I am attaching the `--verbose` reports for more information:

[test_report_no_coverage.txt](https://github.com/flutter/flutter/files/2483477/test_report_no_coverage.txt)
[test_report_with_coverage_enabled.txt](https://github.com/flutter/flutter/files/2483478/test_report_with_coverage_enabled.txt)

**Comment by felangel** [comment]
Also I've noticed that after running `flutter test --coverage` my computer's CPU usage will skyrocket

**Comment by eseidelGoogle** [comment]
@a-siva @cbracken any sense as to if this is expected?  This isn't blocking customer: vroom (yet) but they brought it up recently.

**Comment by guitcastro** [comment]
This is becoming a block for us as well. Test coverage is very important for us, but it's taking up to 25 minutes to run 491 tests with coverage and 2 minutes without it. 

If this does not get fix we will be forced to drop coverage metrics

**Comment by zoechi** [comment]
@guitcastro don't forget to thumbs-up the initial comment to raise priority.

**Comment by JZ-at-TP** [comment]
This is hitting us as well. We have 520 tests at the moment and with coverage its taking 53 min. without its taking 10.

**Comment by eseidelGoogle** [comment]
Disabling code-coverage was recently covered as a tip on the Flutter subreddit. :/
https://twitter.com/r_FlutterDev/status/1096427283185836032

**Comment by JZ-at-TP** [comment]
> Your flutter tests are taking too long? Disable the code coverage!

This isn't viable! we need coverage results as being about 98% is a test by itself.

**Comment by a-siva** [comment]
We are investigating the reason for this slowdown with code coverage turned on and will update the issue once we have more concrete information.

**Comment by jorgecoca** [comment]
@a-siva any news on this topic? Thanks!

**Comment by jorgecoca** [comment]
I am so sorry to bring this again, but is someone working actively on this? If not, can someone indicate what would be the best place to start looking? I don't mind helping with this, but I think I will need some initial support.

**Comment by a-siva** [comment]
We think the potential issue causing the slowdown is because 'fliutter tools' uses a websocket with compression turned on to extract the coverage data, since 'flutter tools' always uses 'localhost' to talk to the  vm service it should be ok to not use compressed data. We are investigating this to see if it results in a speed up of test runs.

**Comment by jorgecoca** [comment]
Thanks for the update! Let me know if there's anything I can do to help

**Comment by jonahwilliams** [comment]
I'm currently looking at a variety of ways to improve coverage performance, starting with a benchmark of the current state of the world.

**Comment by jonahwilliams** [comment]
I have some promising preliminary results which I will look into landing when I am back from Vacation:

### Current
```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter test --coverage
00:12 +1: All tests passed!                                                                                                                                                                                
Collecting coverage information...                                  59ms
```

### Updated
```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter --local-engine=host_debug_unopt test --coverage
00:03 +1: All tests passed!                                                                                                                                                                                
Collecting coverage information...                                  12ms
jonahwilliams-macbookpro2:hello_world jonahwilliams$ 

```

**Comment by jorgecoca** [comment]
Thank you @jonahwilliams that is very promising!

**Comment by jorgecoca** [comment]
@jonahwilliams is the intention to include these changes in the next `1.4.x` stable release, or it would be for a future version? Thanks!

**Comment by jonahwilliams** [comment]
My intention is to land the changes Today after we track down the issue with the ios32 devicelab. I can't say for sure what version that will ultimately end up in though.

**Comment by eseidelGoogle** [comment]
Looks like these won't make 1.4, but *might* make 1.5.  Either way they'll be in dev within a day or two.

**Comment by jonahwilliams** [comment]
This has landed in the latest dev release. I would appreciate it if anyone measuring coverage collection could report back with updated execution times. Locally I've benchmarked this as taking only marginally more time than a regular test, but it would great to know how well that scales past our own benchmarks.

**Comment by guitcastro** [comment]
Before update:
26:55 +717: All tests passed!                                                                                                                                                                              
After update to dev branch:
04:43 +717: All tests passed!                                                                                                                                                                              

Nice work guys!

**Comment by mulderpf** [comment]
Definitely significantly better.  I'm getting varying results, but my tests which used to take at least 4 minutes now take less than 30 seconds.  (And yes, I should fix some of them!)

Stable channel (1.2.1)

Without coverage: 00:31 +191 ~3 -2: Some tests failed.
With coverage: 05:07 +191 ~3 -2: Some tests failed.

Dev channel (1.5.7)

Without coverage: 00:20 +191 ~3 -2: Some tests failed.
With coverage: 00:23 +191 ~3 -2: Some tests failed.

**Comment by tomgilder** [comment]
Has this somewhat regressed? Our 545 tests execute in 28s with `flutter test`, but take 2m07s with `flutter test --coverage`.

On a Mac, Flutter 2.0.3.

**Comment by MalukiMuthusi** [comment]
I am also experiencing the same problem:

With coverage: 10:49 +525: All tests passed!

without coverage: 02:20 +525: All tests passed!

**Comment by MalukiMuthusi** [comment]
> I am also experiencing the same problem:
> 
> With coverage: 10:49 +525: All tests passed!
> 
> without coverage: 02:20 +525: All tests passed!

Is there any fix for this

**Comment by jonahwilliams** [comment]
An example project that shows how coverage slows down would be required for us to do any bisecting. That said, happy to take on any performance bugs here as long as they are reproducible.

**Comment by MalukiMuthusi** [comment]
> @jonahwilliams does it make sense to open a new issue to track what appears to be a regression?
> 
> @MalukiMuthusi can you confirm if you are seeing a regression with Flutter 2.0.3

yes

$ flutter --version
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (3 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

**Comment by jonahwilliams** [comment]
Do you have an example project that shows a slowdown?

**Comment by MalukiMuthusi** [comment]
> Do you have an example project that shows a slowdown?

The data I have shown is from a private project

**Comment by jonahwilliams** [comment]
Then we cannot look at it

**Comment by orestesgaolin** [comment]
Hey there, I have prepared [sample repository](https://github.com/orestesgaolin/coverage_test_regression) that shows how much different the duration of test run is on their first launch with and without coverage:

For instance _with coverage_:

```
flutter clean
flutter pub get
flutter test --no-pub --coverage --test-randomize-ordering-seed random -j 28 --no-track-widget-creation
...
00:14 +8: All tests passed!
```

and _without_:

```
flutter test --no-pub --test-randomize-ordering-seed random -j 28 --no-track-widget-creation
...
00:04 +8: All tests passed!
```

Calling it again _with coverage_ results with very short run (about 0:04) but after `flutter clean` the following call _without coverage_ gives relatively shorter run:

```
flutter clean
flutter pub get
flutter test --no-pub --test-randomize-ordering-seed random -j 28 --no-track-widget-creation
...
00:08 +8: All tests passed!
```

See [this workflow run](https://github.com/orestesgaolin/coverage_test_regression/pull/2/checks?check_run_id=2353871491) where the difference is even larger.

![image](https://user-images.githubusercontent.com/16854239/114889725-a466e380-9e0a-11eb-9f3b-b7a8ac59d797.png)


Sample app https://github.com/orestesgaolin/coverage_test_regression

**Comment by jonahwilliams** [comment]
Thank you @orestesgaolin , please include this information in a new bug and I'll follow up
