### ISSUE TITLE
please add all google maps features to flutter

### ISSUE THREAD

**Issue by jayantakumar** [flutter/flutter#23166]
you know there are some things that are essential  to survive and for us maps is one such thing the plugin you have is no where near to real life use cases so just do it it is as important as the bin folder .. thank you for reading    it          .  ..    .............

**Comment by zoechi** [comment]
It doesn't really make sense to keep this issue around because it's too generic.
Of course all features should be available.
If you need specific features please create specific issues or upvote existing ones. Thanks!
