### ISSUE TITLE
Scrollable tabs no longer scroll

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2316]
See the gallery components/tabs demo for example.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/2350

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (418/400 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:53731 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMd-000ajm-PW
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:22 +0100
Date: Mon, 14 Mar 2016 11:09:04 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457978945;
	bh=/bwcUQar7t99GzrOyyAjLWR9AcAwohf3AzutLaAObkg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xU8gcYmh7CxSM9Sh3KZOXBrvoV4ZzlspGyt9jNVwVjjj8fklsTW6wgfVjlTMAbj93
	 sIGRfRtOxuUXEGQlRIgYgBPfbhHXtEGxQuXdQCDF913cs5Hzetmx5tHxBDcWF1IICi
	 VmYihxpWUj12XE5HPsxRe81oStywJ3vn4cm5likQ=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (425/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:57985 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmN2-000aoQ-A2
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:44 +0100
Date: Mon, 14 Mar 2016 11:09:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457978945;
	bh=Ag1Ln4gEn16/mRM4E/pgL6RgKFDSsoEz+W/cFbTZ3/A=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FG/y8OQxseSu30+DeyveSHLo+5EAvvNV3TzxJnxwTK+E+A7V7qfkIH7fxJDuztjAI
	 L2S53dVm3AVw7r4LOA2ecYZVkxTSJ8yQYrIaTcU35ut2dDZzpAMPbUNosb0aZzKW0U
	 lQ6xI/MAd3tXofvIbQt4skKnpYtDecijaGKiGYNo=
