### ISSUE TITLE
i have problem with update android studio

### ISSUE THREAD

**Issue by Mahmoudlashin** [flutter/flutter#23160]
Failed to prepare an update: Cannot download 'https://dl.google.com/android/studio/patches/AI-173.4720617-181.5540.7.32.5056338-patch-win.jar': Read timed out , response: 200 OK

i download this file by idm now how can install this jar file

**Comment by 5ummit** [comment]
I literally just clicked the link and it worked, try restarting android studio or your pc.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Android Studio is outside Flutters control anyway. If you have still an issue, please report in their bug tracker.
