### ISSUE TITLE
flutter_tester is unable to handle engine-managed platform calls

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#23179]
While trying to wire up asset support for widget tests, I came across a very odd bug.

First off, I tried this very simple widget test which should fail:

```dart
void main() {
  testWidgets('Counter test', (WidgetTester tester) async {
    await tester.pumpWidget(MaterialApp(home: Image.asset('doesnt_matter')));
    await tester.pumpAndSettle();
    Finder counterButton = find.byType(Image);
    expect(counterButton, findsOneWidget);
  });
}
```

but it was succeeding.
> Sidebar: One might argue that this should *not* fail but let's not get hung up on that since it has nothing to do with this issue.

At first, I thought we were doing this intentionally (swallowing asset exceptions in tester) but after tracing the code, I found out that the platform call in `PlatformAssetBundle` was not returning:

```dart
final ByteData asset =
        await BinaryMessages.send('flutter/assets', encoded.buffer.asByteData());
```

I traced this in the engine and finally found out that the posted tasks in task runner were not executing (thus the null/empty response returned by the asset manager was never making it to Dart):

```c++
void PlatformMessageResponseDart::CompleteEmpty() {
  FML_LOG(ERROR) << "CompleteEmpty";
  if (callback_.is_empty())
    return;
  FML_DCHECK(!is_complete_);
  is_complete_ = true;
  FML_LOG(ERROR) << "Posting task";
  ui_task_runner_->PostTask(
      fml::MakeCopyable([callback = std::move(callback_)]() mutable {
        FML_LOG(ERROR) << "CompleteEmptyPostTask";
        std::shared_ptr<tonic::DartState> dart_state =
            callback.dart_state().lock();
        FML_LOG(ERROR) << "Check Dart State";
        if (!dart_state)
          return;
        FML_LOG(ERROR) << "Let's Call Dart";
        tonic::DartState::Scope scope(dart_state);
        tonic::DartInvoke(callback.Release(), {Dart_Null()});
      }));
}
```

Output:

```
Shell: [ERROR:flutter/shell/common/engine.cc(430)] Calling asset manager
Shell: [ERROR:flutter/shell/common/engine.cc(433)] Done!
Shell: [ERROR:flutter/shell/common/engine.cc(440)] Sending back empty!
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(82)] CompleteEmpty
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(87)] Posting task
```

@chinmaygarde suggested a patch to make tester multi threaded: https://gist.github.com/chinmaygarde/5b1b75016869163a20879d1bf058036c but that did not help. Also it is worth reiterating that the test exits _successfully_ with no timeouts.

Even weirder is if I put a `await Future.delayed()` in the test code, _then_ I have a deadlock where the test times out no matter how short the delay is. **But** I see the tasks executing:

```dart
void main() {
  testWidgets('Counter test', (WidgetTester tester) async {
    /// For instance, you can pump the entire app.
    await tester.pumpWidget(MaterialApp(home: Image.asset(
       'whatever',
    )));
    await tester.pump();
    await Future.delayed(const Duration(milliseconds: 1), () {});
    Finder counterButton = find.byType(Image);
    expect(counterButton, findsOneWidget);
    print('test done');
  });
}
```

results in:

```
Shell: [ERROR:flutter/shell/common/engine.cc(430)] Calling asset manager
Shell: [ERROR:flutter/shell/common/engine.cc(433)] Done!
Shell: [ERROR:flutter/shell/common/engine.cc(440)] Sending back empty!
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(82)] CompleteEmpty
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(87)] Posting task
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(90)] CompleteEmptyPostTask
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(93)] Check Dart State
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(96)] Let's Call Dart
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(90)] CompleteEmptyPostTask
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(93)] Check Dart State
Shell: [ERROR:flutter/lib/ui/window/platform_message_response_dart.cc(96)] Let's Call Dart
```

Again, *but* I don't see the Dart code executing:

```dart
 class PlatformAssetBundle extends CachingAssetBundle {
   @override
   Future<ByteData> load(String key) async {
+    print('Load key $key');
     final Uint8List encoded = utf8.encoder.convert(Uri(path: Uri.encodeFull(key)).path);
     final ByteData asset =
         await BinaryMessages.send('flutter/assets', encoded.buffer.asByteData());
+    print('Got back $asset');
     if (asset == null)
       throw FlutterError('Unable to load asset: $key');
```

I never managed to get "Got back null" message which I expected.

**Comment by jason-simmons** [comment]
The `flutter_tester` process is exiting before the deferred tasks for the `flutter/assets` message can run.

The `main` function in the test Dart code has returned, and the async function passed to `testWidgets` is also running to completion.  At this point the `ScriptCompletionTaskObserver` in `flutter_tester` calls `Dart_HasLivePorts()`, which returns false.  So `flutter_tester` thinks there is no remaining work on behalf of the test and it terminates its message loop.

The remaining tasks on the message loop will running during termination.  But any additional work queued by those tasks (such as the task posted by `PlatformMessageResponseDart::CompleteEmpty`) will not run.

If you run `flutter_tester` with the `--run-forever` flag it will never terminate the message loop.  With `--run-forever` the `CompleteEmpty` queued task will run, and the Dart code will get the response and throw an exception in `PlatformAssetBundle.load`

**Comment by jason-simmons** [comment]
Another factor affecting the timing is the test controller in the Flutter tools.

When the test controller receives notification that the test has succeeded, it explicitly kills the `flutter_tester` process (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L490)

So even though the controller is starting `flutter_tester` with the `--run-forever` flag, the controller will probably stop `flutter_tester` before it has a chance to run the deferred tasks and log the asset loading exception.

**Comment by mehmetf** [comment]
Thanks for explaining. This also explains why @chinmaygarde thought this was a timing issue. Internally, we bring in optimized/release versions of flutter_tester which runs faster and is why we see that exception in our test logs. We actually run into a separate timing issue there with flaky tests because sometimes the exception bubbles up before the test gets a chance to complete and is caught by the test framework as failure. Other times, it is logged after the test passes marking it as success.

>At this point the ScriptCompletionTaskObserver in flutter_tester calls Dart_HasLivePorts(), which returns false. So flutter_tester thinks there is no remaining work on behalf of the test and it terminates its message loop.

Can we do something about this to make this behavior more predictible?

**Comment by jason-simmons** [comment]
The cleanest solution to this class of problems would be changing the test's implementation so that it does not finish until all the async tasks related to the test have completed.

**Comment by mehmetf** [comment]
From your comment, it is not clear. Do you expect the test framework to accommodate this? or should the user test somehow track which tasks it has spawned and wait for all those to finish?

**Comment by jason-simmons** [comment]
The latter - the test function should not return until it has waited for all tasks related to the test to finish

**Comment by mehmetf** [comment]
That's pretty difficult to do for widget tests which test a high level widget. Its children may or may not load platform assets. Unless we provide a machinery in the framework (test or otherwise) to do so, I don't think that's a reasonable request and if we provide that machinery, I don't see why test framework can't do this.

**Comment by mehmetf** [comment]
Following on....

I put in a hack to see whether I can make the test wait for the `Future` created by the platform message.

```diff
diff --git a/packages/flutter/lib/src/services/asset_bundle.dart b/packages/flutter/lib/src/services/asset_bundle.dart
index a89b2f56d..6ae6456b2 100644
--- a/packages/flutter/lib/src/services/asset_bundle.dart
+++ b/packages/flutter/lib/src/services/asset_bundle.dart
@@ -212,11 +212,16 @@ abstract class CachingAssetBundle extends AssetBundle {
 
 /// An [AssetBundle] that loads resources using platform messages.
 class PlatformAssetBundle extends CachingAssetBundle {
+  static Future<ByteData> activeCall = null;
+
   @override
   Future<ByteData> load(String key) async {
+    print('Load key $key');
     final Uint8List encoded = utf8.encoder.convert(Uri(path: Uri.encodeFull(key)).path);
-    final ByteData asset =
-        await BinaryMessages.send('flutter/assets', encoded.buffer.asByteData());
+    activeCall = BinaryMessages.send('flutter/assets', encoded.buffer.asByteData());
+    final ByteData asset = await activeCall;
+    activeCall = null;
+    print('Got back $asset');
     if (asset == null)
       throw FlutterError('Unable to load asset: $key');
     return asset;
```

Then I `await PlatformAssetBundle.activeCall;` in the test defined in the first comment of this issue.

I saw the engine _try_ to complete the call but Dart never received it and timed out (similar to what happened when I put a fake await Future.delayed).

@jason-simmons took a look at this (thank you!) and I quote:

> Took a look at this.  I don't fully understand the whole story, but we should chat with @Hixie about how to build the kind of test you have in mind.  The test infrastructure is using various zone wrappers to simulate the way that the production environment would handle async tasks.
>
> In your test, the PlatformAssetBundle.activeCall future is completing.  But when the completion microtask is scheduled, it's actually going to a FakeAsync zone wrapper instead of the engine's real microtask queue.  I'm not sure how the test is supposed to force a drain of the fake microtask queue.

**Comment by mehmetf** [comment]
To restate my two-part goal:

- I want to wire up support in the tester for asset-loading widgets such that widget tests _reliably fail_ when asset could not be loaded.
- Since #1 is a "breaking change" (as in it will break lots of existing tests), I want to tests to be able to configure whether they want asset loading to be tested or not.

**Comment by Hixie** [comment]
> Even weirder is if I put a `await Future.delayed()` in the test code, _then_ I have a deadlock where the test times out no matter how short the delay is. **But** I see the tasks executing:

This part is expected. The tests are running in a fake async zone, so time doesn't advance unless you call pump. But if you're awaiting a future, then you're not calling pump. So nothing happens.

**Comment by Hixie** [comment]
To run an actual async task within the fake async zone, you can use [runAsync](https://master-docs-flutter-io.firebaseapp.com/flutter/flutter_test/WidgetTester/runAsync.html).

**Comment by Hixie** [comment]
What does asset loading in a test look like? There's no bundle to load the assets from. Or do you mean mock assets? I _think_ that should work today without needing any real asynchrony.

**Comment by mehmetf** [comment]
Right, runAsync won't help me here either I presume since the async task being invoked isn't invoked in the test code. I am grasping this problem more now 👍 

Here's the use case I am trying to solve. It also leads to a P1 goal which sits above the goals I mentioned before:

MyApp (approximate widget tree representation):

```
MyApp >
Scaffold >
  AppBar
  Body >
    Column >
      Image.asset('assets/my_profile.png')
      Text('My Profile')
```

Here's a widget test:

```dart
  testWidgets('MyApp test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    await tester.pumpAndSettle();
    expect(find.byType(Text), findsOneWidget);
  });
```

Test has no clue that in the MyApp widget, there's a widget that tries to load an asset.

Today, everything passes even though the asset is unable to load (due to timing (Jason's guess)). Then developer defines a screendiff test:

```dart
  testWidgets('MyApp test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    await tester.pumpAndSettle();
    expect(find.byType(Text), findsOneWidget);
    await expectLater(find.byType(MyApp), matchesGolden('MyApp'));
  });
```

The test now becomes flaky since loading the asset my_profile always fails but sometimes the test manages to finish before the failure bubbles up to test harness.

P1 goal is to make this behavior consistent and deflake the test. We should do one of the following:
* Declare loading assets within the widget tester a non-goal and provide a mock PlatformAssetBundle for tests (driven by runtime context?). That means users, by design, can't rely on widget tests to make sure they are loading the assets correctly.
* Fix this issue so the assets can be loaded in the tester environment provided that the engine switch `--flutter-asset-path` is set correctly. flutter_tester seems to wire this up: https://github.com/flutter/engine/blob/2707b7433874a8b03e4a1f7341d45b5cdcc8dfc6/shell/testing/tester_main.cc#L151 which is why I started pursuing a fix.

**Comment by Hixie** [comment]
Mehmet and I discussed this.
- We should probably support exposing the actual app asset bundle to tests in `flutter test` (to match the way we do to tests in `flutter run`). If we do this, we should probably also make the test framework hook the asset loading platform channel so that it keeps tests pending until all requests are resolved.
- In the meantime, flaky tests should be updated with a DefaultAssetBundle that uses a mock asset bundle that fails everything synchronously. Search for TestAssetBundle for some examples of this.

**Comment by gamebox** [comment]
It seems that this issue blocks internal work for me, should I assign myself here @mehmetf ?

**Comment by jonahwilliams** [comment]
cc @matanlurey 
AssetBundle issues with testing came up recently, it wasn't really clear if it should work or how to work around it

**Comment by jonahwilliams** [comment]
related: https://github.com/flutter/flutter/issues/12999

**Comment by mehmetf** [comment]
@gamebox has looked at this issue extensively. I am not sure if he has seen @matanlurey 's solution here: https://github.com/flutter/flutter/issues/12999#issuecomment-450677379.

One thing that tripped us up was that decoding an image was also happening via async hooks so providing a DefaultAssetBundle that just loaded bytes from disk was not enough AFAIK. I would be happy to see a golden file test that successfully loads and decodes an image via the disk asset bundle.

**Comment by matanlurey** [comment]
@mehmetf I looked at this today with @jonahwilliams. My `DiskAssetBundle` seems to partially work, that is, assets are loadable (and readable), but it does look like - as you mentioned - image decoding does not happen, so no images are ever rendered (all images are effectively blank in golden tests).

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

Not sure if this is the way to reproduce this issue, but I ran the first test in the OP and it fails now.

<details><summary>Test logs</summary>

```
Testing started at 11:21 ...
/Users/pedromassango/dev/Projects/flutter_personal_fork/bin/flutter --no-color test --machine --start-paused --plain-name "Counter test" test/widget_test.dart

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown while resolving an image:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:225:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:33)
#2      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:167:18)
#3      CachingAssetBundle.loadStructuredData (package:flutter/src/services/asset_bundle.dart:188:5)
#4      AssetImage.obtainKey (package:flutter/src/painting/image_resolution.dart:176:18)
#5      ScrollAwareImageProvider.obtainKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:113:74)
#6      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:455:15)
#10     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:452:16)
#11     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:330:5)
#12     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1154:16)
#13     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1107:5)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4814:11)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4630:5)
...     Normal element mounting (132 frames)
#147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3596:14)
#148    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6263:32)
...     Normal element mounting (267 frames)
#415    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3596:14)
#416    Element.updateChild (package:flutter/src/widgets/framework.dart:3358:20)
#417    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1215:16)
#418    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1193:5)
#419    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1207:7)
#420    Element.rebuild (package:flutter/src/widgets/framework.dart:4350:5)
#421    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2758:33)
#422    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1095:18)
#423    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:310:5)
#424    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#425    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#426    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:968:9)
#429    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#430    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:955:27)
#431    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#434    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#435    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#436    main.<anonymous closure> (file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:21:18)
#437    main.<anonymous closure> (file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:20:31)
#438    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
#449    FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#450    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1196:17)
#451    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1184:35)
(elided 32 frames from dart:async and package:stack_trace)

Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#7e7f9(), devicePixelRatio: 3.0,
  locale: en_US, textDirection: TextDirection.ltr, platform: android)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Counter test
```
</details>

**Comment by jonahwilliams** [comment]
This is a design choice of the flutter_test framework. flutter_tester itself is perfectly able to load assets.
