### ISSUE TITLE
Provide a safe way to get a box's height between frames

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2317]
This is a common pattern:

```
  double get size {
    assert(mounted);
    RenderBox box = context.findRenderObject();
    assert(box != null);
    assert(box.hasSize);
    return box.size;
  }
```

We should add this to the BuildContext method as a function that returns a Size. It should assert we're not calling it during a frame (certainly not in the build phase, anyway). In checked mode, it should return a _WidgetDebugSize, a new class that refuses to be used during the build phase.

**Comment by abarth** [comment]
Duplicate of #2321
