### ISSUE TITLE
BottomNavigationBar animation exceeds Material spec

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#23178]
I think Flutter's BottomNavigationBar gratuitously moves outside the Material Design specification.

https://material.io/design/components/bottom-navigation.html#specs

The Specification shows examples of buttons that show and reveal their text, but they do not shift side to side.

The shifting side to side animation on Flutters BNB (`type: BottomNavigationBarType.shifting`) is distracting, not specified by MD, and confusing for users. (And by users, I mean me. It's not like I've tested it or anything!)

This is personally low priority for me now knowing that there is forward movement on https://github.com/flutter/flutter/issues/22882#issuecomment-430409480 but I figured I should post it here for someone to at least consider it.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
