### ISSUE TITLE
Flutter_gallery__memory_nav diff-median regressed

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#23171]
22353 -> 28952 after our [big engine roll with text shadows support](https://github.com/flutter/flutter/commit/bdc3dda5f298f50b432faaffe71730c4fe26afda)

Similar regression for flutter_gallery__memory_nav end-median too.

**Comment by liyuqian** [comment]
@GaryQian do you think if it has anything to do with your text shows work?

**Comment by GaryQian** [comment]
I doubt it because the only major memory related change is potentially keeping an empty list in TextStyle (since nothing uses text shadows yet).

**Comment by liyuqian** [comment]
My bisection shows that https://github.com/flutter/engine/pull/6468 is the commit that caused the regression. I didn't expect that PR to increase the memory usage in mega-bytes. I will investigate what's going wrong.

**Comment by liyuqian** [comment]
CC @jason-simmons who's also working on this issue.

**Comment by jason-simmons** [comment]
I'm seeing the same effect from https://github.com/flutter/engine/pull/6468.  I think it would be reasonable to update the baseline of this test to reflect the cost of the EngineLayer objects that are referenced by Dart and may not yet be GCed.

EngineLayer can also provide an estimate of its size to Dart for use in GC metrics.

Ideally the test would force a GC before collecting results, but the test infrastructure doesn't seem to have a way to do that (especially given that this benchmark runs in release mode)

**Comment by jason-simmons** [comment]
This benchmark is within the expected range again.
