### ISSUE TITLE
Create a Point from a Rect and an Offset

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2318]
We should consider exposing something on Offset or Point or Rect that does this:
```dart
Point _offsetToPoint(Offset offset, Rect rect) {
  return new Point(rect.left + offset.dx * rect.width, rect.top + offset.dy * rect.height);
}
```

Maybe `Point.fromRectAndOffset()`?

**Comment by abarth** [comment]
This is a little odd because it's treating dx and dy as fractional values.  Maybe the gradients should use FractionalOffset instead.
