### ISSUE TITLE
Dart Analysis Server never stops Analyzing with Android Studio 3.2.1

### ISSUE THREAD

**Issue by jgv115** [flutter/flutter#23187]
Hi there,

I'm not sure if anyone else has had this issue but as soon as I upgraded to Android Studio 3.2.1, my Dart Analysis Server has never stopped analyzing and is taking up 100% of my RAM. Please see the below screenshot:

![image](https://user-images.githubusercontent.com/31205144/47058874-b011c900-d212-11e8-99be-97013ab2b8eb.png)

I am wondering if there is a way to fix this?

**Comment by zoechi** [comment]
Looks like #23155

**Comment by zoechi** [comment]
Merging with #23155
