### ISSUE TITLE
Flutter needs a way to play inline video

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2319]
I thought we already had a bug on this, but I don't see one.

It is currently possible to play video fullscreen or over-the-top of other Flutter content, and there are various community-authored plugins to make that easy (e.g. https://pub.dartlang.org/packages/video_launcher)

However this bug is about making it possible to have inline video content (e.g. a video inside a scrolling ScrollView widget inside your Flutter app) properly clipped/positioned/composited with other Flutter content.

**Comment by chinmaygarde** [comment]
This is video that is part of the layer tree right? As opposed to a control that is placed by the embedder over the Flutter view. If it is the latter, the existing platform messages API should allow custom embedders to control platform widgets manually. I can take a look at introducing a custom layers type that allows us to support video within the layer tree.

**Comment by abarth** [comment]
> This is video that is part of the layer tree right?

Correct.

**Comment by mravn-google** [comment]
Fixed by texture support #12525. A demo plugin for making use of this facility for video playback is available [here](https://github.com/sigurdm/video_player).

**Comment by eseidelGoogle** [comment]
Exciting. :D  Are there bugs tracking the remaining planned work around inline video (e.g. publishing that package, updating it's readme, possibly including an example of video playback in one of our examples, etc.)?

**Comment by xster** [comment]
+1 on publishing the plugin
(nit: would it make sense to let the plugin publish a VideoPlayer widget object with a controller rather than a Texture?)

**Comment by mravn-google** [comment]
@eseidelGoogle I'll add links here once there are.

@xster Yes, in fact @sigurdm and I just discussed that today.

**Comment by sethladd** [comment]
People following along might also be interested in https://pub.dartlang.org/packages/chewie , a video player with platform aesthetic controls.

**Comment by sethladd** [comment]
Canonical location for the video player plugin is now here: https://github.com/flutter/plugins/tree/master/packages/video_player

**Comment by JohnGalt1717** [comment]
does it support HTTP headers, AES, and other encryption as well?

**Comment by chinmaygarde** [comment]
The plugin uses the platform's video playback mechanism. So [MediaPlayer on Android](https://developer.android.com/reference/android/media/MediaPlayer.html) and [AVPlayer on iOS](https://developer.apple.com/documentation/avfoundation/avplayer). This issue was related to using the textures for video feeds generated by the platform during composition of the Flutter layer tree.

I can't answer your question about support for specific features but you might find the answer in the linked documentation.

**Comment by keremkusmezer** [comment]
I see they moved to exoplayer for Android
