### ISSUE TITLE
how to use xpath with flutter?

### ISSUE THREAD

**Issue by YoneHsiung** [flutter/flutter#23200]
I have an application that needs to parse the Html,**I don't want to use regular expressions** because it's too inconvenient,so i want to use **xpath**,then i found a lib(https://pub.dartlang.org/packages/xpath),
but it cant be parse all html(eg:https://www.xs8.cn/all)
,so how does i do ? anyone can help me ,or build a library, 
thanks all .

**Comment by zoechi** [comment]
The https://pub.dartlang.org/packages/html package might be useful. 
It doesn't support `xpath` though.

The xpath package is quite new.  
It might be helpful to raise an issue there to fix the problem you run into.

I doubt the Flutter team will add xpath support to Flutter.

Support questions are better asked in one of the other channels listed at http://flutter.io/support .
