### ISSUE TITLE
Add OrderByKey() and OrderBy(field,"desc") and asc for StreamBuilder

### ISSUE THREAD

**Issue by 5lineofcode** [flutter/flutter#23203]
bro, please add this feature on next update :(

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
