### ISSUE TITLE
Can flutter provide tools to support the diagnosis of 'ANR' ?

### ISSUE THREAD

**Issue by kongshanshan33** [flutter/flutter#23209]
We know that all Dart code run on The UI task.Performing time-consuming operations in the dart code can cause the flutter app to become unresponsive for a long time.How I detect and diagnose this problem?

**Comment by zoechi** [comment]
Not sure what you mean by detect and diagnose. 

Perhaps
- https://flutter.io/debugging/#dart-observatory-statement-level-single-stepping-debugger-and-profiler
- https://flutter.io/ui-performance/

**Comment by zoechi** [comment]
You can also move code to a different thread using Isolate or the convenience method to do so https://docs.flutter.io/flutter/foundation/compute.html
but currently such code can't access plugins. This would need to be delegated to the UI thread.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
