### ISSUE TITLE
Flutter Doctor doesn't recognise installed Dart/Flutter IDEA/AS plugins

### ISSUE THREAD

**Issue by rock3r** [flutter/flutter#23204]
## Steps to Reproduce

1. Make sure Flutter is up to date: `$ flutter update` (on `master`)
2. Install Android Studio 3.3 canary 13, and/or IDEA 2018.3 AEP
3. Install the Dart and Flutter plugins in the IDE(s) and restart them
4. Run `flutter doctor`

Observe how the Dart and Flutter plugins aren't picked up by Doctor, that sees the IDEs as installed but doesn't pick up the plugins.

## Logs

```
flutter doctor -v
[✓] Flutter (Channel master, v0.10.1-pre.66, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 0.10.1-pre.66 at /Users/rock3r/src/flutter
    • Framework revision 936dea28da (4 hours ago), 2018-10-17 08:09:29 +0200
    • Engine revision 08272ee6aa
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/rock3r/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rock3r/android-sdk
    • Java binary at: /Applications/Android Studio 3.3 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3 EAP)
    • IntelliJ at /Users/rock3r/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Proof that the plugins are installed:

Android Studio 3.3 Canary 13 | IntelliJ IDEA 2018.3 (EAP)
--- | ---
![image](https://user-images.githubusercontent.com/153802/47080158-869f7000-d207-11e8-8f4a-b19f3589e44d.png) | ![image](https://user-images.githubusercontent.com/153802/47080168-8e5f1480-d207-11e8-832b-62cdd0f8cc82.png)

**Comment by zoechi** [comment]
Closing as dup of https://github.com/flutter/flutter-intellij/issues/2644

**Comment by rock3r** [comment]
@zoechi this is completely unrelated with the issue you linked. It's a `doctor` issue, not an IntelliJ plugin issue.

**Comment by zoechi** [comment]
> Install Android Studio 3.3 canary 13

flutter/flutter-intellij#2644 says Canary is not supported.

**Comment by rock3r** [comment]
AS 3.3 Canary is supported since v28.0 of the IntelliJ plugin and IDEA 2018.3 EAP since v29.0 — see the [changelog](https://github.com/flutter/flutter-intellij/blob/master/CHANGELOG.md#280). Regardless, this is not a "plugin not working/supported in an IDE". The issue is that `flutter doctor` detects the IDEs but does not seem to recognise that they have the plugins installed — both Dart and Flutter.

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by kangwang1988** [comment]
Maybe duple of: https://github.com/flutter/flutter/issues/26928 and fixed totally after https://github.com/flutter/flutter/pull/27687/files.

**Comment by ohir** [comment]
Please reopen - it resurrected.
Seeing the 35.0 plugin and Dart 2.3 I've switched to beta channel.
Now doctor sees no plugins in AS 3.4. Neither it sees installed NDK:
```
cat $NDK_HOME/source.properties
Pkg.Desc = Android NDK
Pkg.Revision = 19.2.5345600

Plugins:
Dart v183.6270
Flutter v35.0.1
```
I even did a reinstall plugins voodoo. To no avail.

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.5.4, on Linux, locale pl_PL.utf8)
    • Flutter version 1.5.4 at /testbed/flutter
    • Framework revision b593f5167b (7 days ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /testbed/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /testbed/Android/Sdk
    • Java binary at: /testbed/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152_testbed)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /testbed/Android/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /testbed/Android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152_testbed)

[!] Connected device

```

**Comment by ShayanSolid** [comment]
I am also facing the same issue with IntelliJ Ultimate and Android Studio.
✅ Android Studio Issue is solved
❌ IntelliJ Issue still exists

This ist What I have figured out till now:
I install IDEA products using IDEA Toolbox, that's why the plugins are not saved under:
1. ``` /Users/[USER]/Library/Application Support/IntelliJIdea2019.1 ```
but under 
2. ``` /Users/[USER]/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app.plugins ```
I assume, Flutter is looking for plugins in the first directory and cant find them.

ℹ️ To solve the issue with Android Studio I simply installed and updated the Flutter and dot plugins. The only difference between Android Studio and IntelliJ on my machine(macOS Mojave) is that the Android Studio's plugins are installed under:
``` /Users/[User]/Library/Application Support/AndroidStudio3.4``` and IntelliJ installs its plugins under:
 ```  /Users/[USER]/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98/IntelliJ IDEA.app.plugins```

**Comment by jerryzhoujw** [comment]
<img width="450" alt="Screen Shot 2020-04-24 at 6 47 38 PM" src="https://user-images.githubusercontent.com/6405390/80204816-21c6a080-865c-11ea-90cd-7848d1bae036.png">

```sh
[✗] Cannot determine if IntelliJ is installed
    ✗ Directory listing failed
```

**Comment by qntbkk** [comment]
https://qnttran.medium.com/flutter-in-multiple-ide-android-intellij-vscode-for-macos-ba928d58b4a4

hope this help
