### ISSUE TITLE
Is there any API similar to paint.getFillPath(Path src, Path dst) in java ( Android ) ?

### ISSUE THREAD

**Issue by SubramanianM** [flutter/flutter#23216]
I have an use case which was fulfilled by the api [paint.getFillPath(Path src, Path dst)](https://developer.android.com/reference/android/graphics/Paint#getFillPath(android.graphics.Path,%2520android.graphics.Path)) in android. Is there any API in dart:ui for doing the same?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by kf6gpe** [comment]
Closing thanks to @zoechi and @goderbauer's redirect to http://flutter.dev/support.
