### ISSUE TITLE
Unable to find a matching configuration of project :flutter: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by HaroonWasim** [flutter/flutter#23210]
## Steps to Reproduce

1. I have install flutter and it is running fine no issue.
      a. 'flutter doctor' => No Issue
      b. 'flutter device' => Detected
      c.  examples in flutter folder are running fine. 
2. Created new project using VS Code and pressed F5 key.
3. FAILURE: Build failed with an exception.
 
## Logs
```
Launching lib\main.dart on Redmi 4X in debug mode...

FAILURE: Build failed with an exception.

 What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :flutter.
     Required by:
         project :app
      > Unable to find a matching configuration of project :flutter: None of the consumable configurations have attributes.

 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 Get more help at https://help.gradle.org

BUILD FAILED in 1s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

```
```

```
```

```
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Sounds like https://github.com/flutter/flutter/issues/22614#issuecomment-430237654

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
