### ISSUE TITLE
Add instructions to firebase_admob for the AndroidManifest.xml meta-data requirements

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#23215]
## Steps to Reproduce

1. Include `firebase_admob:` in the pubspec.yaml dependencies.
2. Debug your application.
3. Crash immediately.
3. Remove `firebase_admob:` in the pubspec.yaml dependencies.
2. Debug your application.
3. Works.

## Logs

`flutter run --verbose` completes successfully, and stops on `Waiting for observatory port to be available...` assuming that means its waiting for the app to open, which it cant because it crashes.

`flutter analyze` finds no issues.

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Michael\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Michael\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.28.1)
    • VS Code at C:\Users\Michael\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • SM G900P • 7b11d89f • android-arm • Android 6.0.1 (API 23)
```

**Comment by zoechi** [comment]
Did you ensure you have the latest version of `firebase_admob`?
Did you test it in a newly created app (`flutter create foo`)?

**Comment by MichaelPriebe** [comment]
Yes using the latest version, and yes it has the same problem on a newly created app.
Logcat shows a error message about "The Google Mobile Ads SDK was initialized incorrectly." in which you need to add your AdMob App ID to your app's AndroidManifest.xml file by adding the <meta-data> tag. After doing this the application still crashes.

**Comment by ened** [comment]
@MichaelPriebe please post the contents of your `AndroidManifest.xml`. Admob will not work (and *expectedly* crash) unless you configured it correctly.

**Comment by MichaelPriebe** [comment]
@ened Thank you this tip solved my problem. I had it in the wrong spot.

Now this issue would be to add this documentation to the firebase_admob page. I had to go WAAY out of my way with logcat to figure out why the app just closes instantly.

**Comment by ened** [comment]
It would probably be good to add a link to the documentation in the admob README.md.

Would you be able to prepare a PR for the flutter/plugins project?

**Comment by ankit9607** [comment]
Dear Ened/ MichaelPriebe,

Kindly specify the Meta-Data Tags, a simple example.

**Comment by ankit9607** [comment]
PFB My AndroidManifest.xml File for reference : Where I added Meta-Data at specific location but still facing the same issue.

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.aiimage">

    
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="com.android.vending.BILLING" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="AI Image"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="com.google.android.gms.ads.com.ankit9607.ai.image"
            android:value="ca-app-pub-9606097937834582~6443108019"/>
    </application>
</manifest>
`

**Comment by AppleEducate** [comment]
Same for me, continues to crash. works perfectly on ios. I never saw I needed to put something in the android manifest

**Comment by ankit9607** [comment]
@smoothdvd  Thanks buddy! its work for me.

**Comment by figengungor** [comment]
Stole my time, too.

**Comment by shyjuzz** [comment]
> @MichaelPriebe @ened I changed firebase-ads to 16.0.1 to fix this issue.
> 
> in firebase_admob plugin's dependencies in build.gradle
> 
> ```
>     dependencies {
>         api 'com.google.firebase:firebase-ads:16.0.1'
>     }
> ```

Which file should I edit to fix the crash issue

**Comment by AppleEducate** [comment]
I was able to get the app to open by changing: `firebase_admob: ^0.5.5"

and:

```
    dependencies {
        api 'com.google.firebase:firebase-ads:15.0.1'
    }
```

And adding to the AndroidManifest.xml with my AdMob keys:
```

 </activity>
        <meta-data
            android:name="com.google.android.gms.ads.APP_ID_HERE"
            android:value="ca-app-pub-XXXXXXXXXXXXXXXX"/>
    </application>
```

**Comment by shyjuzz** [comment]
Thanks for the reply.

I have added the below item at the bottom of  the android/build.gradle file but got an exception

> dependencies {
        api 'com.google.firebase:firebase-ads:15.0.1'
    }

_Could not find method api() for arguments [com.google.firebase:firebase-ads:15.0.1]_

Am I doing it in the correct way

**Comment by AkramChauhan** [comment]
Can anyone explain what is difference in APP_ID and APPLICATION ID

```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="APP_ID"/>
```

**Comment by MichaelPriebe** [comment]
It's not really for you to fill out manually. Firebase gives you this line in the setup wizard online.

**Comment by kroikie** [comment]
@MichaelPriebe

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/606. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by BondarenkoStas** [comment]
I think it's safe to close as the instructions are added https://pub.dev/packages/firebase_admob. Please comment or re-open it if it's not enough.
