### ISSUE TITLE
Android onBackPressed overrides

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#23211]
I need to put my application in background (and not close it) when users click back. 
Currently we use something like: 

```java
@Override
public void onBackPressed() {
    moveTaskToBack(true);
}
```

The problem is by doing so the back event into the flutter app is broken. 
FlutterActivity already override this method to manage the back event.
```java
 public void onBackPressed() {
        if (!this.eventDelegate.onBackPressed()) {
            super.onBackPressed();
        }
    }
```
So I would like to do:
```java
@Override
public void onBackPressed() {
      if (!this.eventDelegate.onBackPressed()) {
            moveTaskToBack(true);
        }
}
```
but not possible as `this.eventDelegate` is only private. I have no way of doing this for now except copy/paste the `FlutterActivity` code.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Is this about adding Flutter to an existing Android app?

**Comment by nuc134r** [comment]
I had a similar requirement in my app and came up with following workaround.

I wrapped root Page of my app with `WillPopScope`:

```dart
Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: () async {
          NavigationChannel().minimize();
          return false;
        },
        child: Scaffold( /* ... */ ),
```

Before returning `false` from `onWillPop` I call platform method which only does following
```java
    @Override
    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
        if (call.method.equals("minimize")) {
            moveTaskToBack(true);
            result.success("success");
        }
    }
```
`MethodCallHandler` implemented by `MainActivity` and `this` passed as handler so that `moveTaskToBack` could be called.

After that my app keeps it's state after being reopened from home screen or Android recent apps screen.

**Comment by kangwang1988** [comment]
@jaumard 
You can also create your own activity to realize what you want.
FlutterActivity is quite simple, you can create your own activity(CustomActivity).
In CustomActivity, you can do your own logic to override what's designed in FlutterActivity, keep the unchanged part in  CustomActivity.

**Comment by jaumard** [comment]
@kangwang1988 I don't follow you, your suggest that I copy/paste flutterActivity code into my own CustomActivity to do what I want ? Sure I can ^^ but if at some point flutter update this class I'll have to think about doing too or deal with the consequences ect.... 
Why not just allowing us to overriding the onBackPressed like this for example: 
```
@Override public void onBackPressed() { 
    if (this.isFlutterStackEmpty()) { 
         moveTaskToBack(true); 
    } else {
        super.onBackPressed();
    }
}
``` 
I rather do @nuc134r solution instead of duplicating the activity code. 
If the team consider this will never happen that's probably what I'll do :)

**Comment by kangwang1988** [comment]
@jaumard 
Also sound good, if that(override onBackPressed)'s would resolve your issue..

**Comment by jaumard** [comment]
Yeah for me this kind of overrides would be good, at least if there no stack on the Flutter app I can do what I want, here just move to background. But as I'm aware we currently not know if the flutter stack is empty or not right ?

**Comment by CoreyCole** [comment]
I need this as well. `WillPopScope` does not solve my use case. When a user hits the back button, I need to release the focus on a `TextFormField`. Right now, the back button will minimize the keyboard, but the field will still be focused. Is there any way to subscribe to the back button event in flutter so I can unset the focus?
```dart
FocusScope.of(context).requestFocus(FocusNode());
```
I was trying to set up an `EventChannel` to subscribe to back button presses, but it looks like in `FlutterActivity` 'onBackButtonPressed' overrides nothing.

**Comment by pedromassangocode** [comment]
> Yeah for me this kind of overrides would be good, at least if there no stack on the Flutter app I can do what I want, here just move to background. But as I'm aware we currently not know if the flutter stack is empty or not right ?

I may be wrong but with [Navigator 2.0](https://github.com/flutter/flutter/issues/45938) by @chunhtai , there is a way to know if the navigation stack is empty.

Wondering if is there any considerations that we should be aware of before making [delegate](https://github.com/flutter/engine/blob/3b2da6be9f32e63c00252b31b3c9da1d6eeda60c/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L378) property public. This seems to be an easy fix.

**Comment by chunhtai** [comment]
If we want to fix this in engine side, we should make plugin to be able to listen to the back button event.

you can also solve this if you use [router api](https://api.flutter.dev/flutter/material/MaterialApp/MaterialApp.router.html). You can then use [popRoute](https://api.flutter.dev/flutter/widgets/RouterDelegate/popRoute.html) to decide what to do with the back button intent. If you use the Router api, you will be in charge to manage what pages are in the navigator, you should know whether the route stack is empty or not

**Comment by xster** [comment]
I'm closing this issue. While it doesn't do a fancy synchronous callback of whether to defer or not to flutter via platform channel, this is generally possible with v2 embedding where a) the FlutterActivity's onBackPressed is public and overridable and b) it doesn't super.onBackPress by default.

**Comment by xster** [comment]
Specifically see https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L632
