### ISSUE TITLE
ButtonBar children direction is not correct when RTL

### ISSUE THREAD

**Issue by FlutterIODev** [flutter/flutter#23217]
When the current local of the MaterialApp is set to RTL language like Arabic the children direction of the ButtonBar is not correct.

**Output:**

![Image](https://user-images.githubusercontent.com/42409569/47108279-ee7ba800-d253-11e8-87f5-8efa2a80d43c.png)

**Flutter Doctor:**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.8.2, on Microsoft Windows [Version 10.0.17134.345], locale ar-SA)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[!] VS Code, 64-bit edition (version 1.27.2)
[√] Connected devices (2 available)
```

**Code Sample:**

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      supportedLocales: [
        const Locale('ar', ''), // Arabic
      ],
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      locale: Locale('ar'),
      title: "RTL",
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: <Widget>[
            GridView.extent(
              maxCrossAxisExtent: 100.0,
              padding: const EdgeInsets.all(20.0),
              mainAxisSpacing: 10.0,
              crossAxisSpacing: 10.0,
              children: [
                Text("Correct Direction"),
                Text("Correct Direction")
              ],
              shrinkWrap: true,
            ),
            ButtonBar(
              children: <Widget>[
                Text("Wrong Direction 1"),
                Text("Wrong Direction 2"),
              ],
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by FlutterIODev** [comment]
Hello @justinmc 

It looks like you misunderstand my point, I'm **not** talking about the ordering of the items inside the ButtonBar.

The issue is with the starting position of the ButtonBar widget its self, it should start from the right edge not from the left (The parent widget not the ordering of the children).

![2018-11-13_1345](https://user-images.githubusercontent.com/42409569/48408738-1ecb3f00-e74b-11e8-83b1-63ef39ffb307.png)

**Comment by justinmc** [comment]
The intention is that the alignment defaults to `end` to cover the main use case of things like dialogs.  You can see where this is purposely done [in the code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/button_bar.dart#L29).

Maybe try changing the alignment to `start` for your case and it should do what you want for both LTR and RTL.  Or you can always look for another way to lay out your buttons if you need something significantly different.

**Comment by justinmc** [comment]
The docs should be a lot more clear on this now with that [PR](https://github.com/flutter/flutter/pull/24264/files).

**Comment by justinmc** [comment]
No problem, thanks for following up even though it took us awhile to get to your issue.  Another thing you might want to try if you haven't already is using a `Row` instead of `ButtonBar`.  It sounds like you could set it up to get the alignment right without having to check for locale in if statements like you are with `ButtonBar`.

I'll keep an eye out and see if this locale alignment thing is tripping up anyone else in the meantime.
