### ISSUE TITLE
No animations in page changes in gallery app

### ISSUE THREAD

**Issue by SUPERETDUPER** [flutter/flutter#23226]
When I open the gallery app and tap on Material, there is no animation to get to the the next page (the list of different widgets). This doesn't look great. It isn't a priority but it's something to be added at one point since this is kinda the demo app for flutter.

**Comment by jonahwilliams** [comment]
We definitely have animations - Do you have animations disabled on your phone (via accessibility settings, battery saver, or animation duration)?

**Comment by SUPERETDUPER** [comment]
I don't think so. I see the animation when tapping on the hamburger and the drop down settings menu shows up. I don't see animations when tapping on one of the 5 main categories.

**Comment by SUPERETDUPER** [comment]
Actually when I open I turn on the slow motion I see a simple cross fade animation. I guess that's enough. Maybe it's just lagging for me because it's in debug mode.
