### ISSUE TITLE
App crashes on click

### ISSUE THREAD

**Issue by griboue** [flutter/flutter#23220]
Hello,
I am having some troubles with the package.
I am able to compile my app (xcode 9 / swift 4) (it works fine) but when I click on a button that is supposed to launch an URL, my app crashes with the following message:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <FlutterViewController: 0x15baae00>.
```

Here is the error message in details:
```
You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <FlutterViewController: 0x171c8000>.'
	*** First throw call stack:
	(0x273180d7 0x359b4c77 0x2ac6734f 0x2ac68e27 0x2aa59a01 0x1859941 0x1859059 0x288159 0x2a16ab 0x2a2d3f 0x2dd13d 0x2acc75 0x2af053 0x272ddf3f 0x272ddac1 0x272dbd2b 0x272276d1 0x272274e3 0x2eb941a9 0x2a9d9445 0x1072cc 0x35f82aaf)
```

I already activated background mode fetch option to my project on xcode (thus I don't understand why I do still have the message "but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist." in the crash log ...

Thank you very much for any help !

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by griboue** [comment]
> Please add the output of `flutter doctor -v`.
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.5 17F77, locale fr-FR)
    • Flutter version 0.9.4 at /Users/jean/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jean/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • iPad of jean • 1fa16796f25e3bc15c1f4a14076 • ios • iOS 8.4.1

• No issues found!
```

**Comment by ened** [comment]
Please post the affected code (which is handling your click event).

**Comment by griboue** [comment]
@ened 
It is the example code of the url_launcher package (https://pub.dartlang.org/packages/url_launcher):

I have a button and the onPressed event is linked to the "_launchURL" function:

```
_launchURL() async {
  const url = 'https://flutter.io';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}
```

I highly doubt that the problem comes from the code because the same project works perfectly fine on Android. I think it has to be somehow related to xcode / swift. Maybe I did something wrong when I imported / configured the project on my Mac but I don't know what and I have no clue

**Comment by lesnitsky** [comment]
@griboue example you've provided seems to be copypasted from `url_launcher` docs package
Are you sure you have `await canLaunch(url)` in your code and you pass the same `url` to `canLaunch` and actual `launch`. High-level search with your error points that you probably try to open a url which couldn't be opened on device

**Comment by griboue** [comment]
@lesnitsky 
I kind of solved the issue. The app crashed only on the real device but not on emulator... weird ...
I'll publish the app soon. I'll see if it works.

Many thanks !

**Comment by surenyonjan** [comment]
I solved this issue by navigating to **Targets** -> **Your App** -> **Capabilities** -> **Background Modes** and checked **Background fetch** in XCode (10.2)

**Comment by kf6gpe** [comment]
Filer indicates issue solved; closing issue. Thanks!
