### ISSUE TITLE
SplashScreen Android placeholder UI 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#23238]
Material design offer two type of splash screen one that we all know about with just an image, but there also the possibility to do placeholder UI. It's the one I want to implement in my app Android side because our current native app doesn't have a splash screen.

Problem is that how am I suppose to implement a placeholder UI splash screen ? The Android side is using `windowBackground` drawable as splash screen. The capabilities of drawable doesn't allow to make placeholder UI easily (as there no way to use theme variable, eg action bar size, notification bar size...).

One way to solve this would be to have real views for the placeholder UI on top of the FlutterView, and once the first frame is here just fade out the native views. I didn't find any documentation/example on how to do this so might be possible already but not really easy to do.

**Comment by filleduchaos** [comment]
@jaumard Not sure if this would be sufficient for your case, but you can call `runApp` multiple times in your app's `main`. This means you can run a placeholder widget and then transition your actual main screen when e.g. network calls are complete and all.

Simple example:

```dart
import 'package:flutter/material.dart';
import 'src/some_service.dart' show someLongRunningStartup;
import 'src/my_app.dart';

void main() {
    runApp(Container(color: Colors.blue));
    someLongRunningStartup().then(() => runApp(MyApp());
}
```

**Comment by jaumard** [comment]
If I want to put a circle progress as splashscreen, is it safe to do so in the windowsbackground ? As if it continue the animation even when not on screen it will use resource for nothing all the time...

**Comment by xster** [comment]
I'm going to tentatively close this issue since we've done some extensive work on the Android splash screen including the ability to self-supply an arbitrary Android view in https://flutter.dev/docs/development/ui/advanced/splash-screen. Please re-open if it's not adequately addressed.
