### ISSUE TITLE
DateSymbols.FIRSTDAYOFWEEK property or documentation incorrect per ISO 8601

### ISSUE THREAD

**Issue by toddabel** [flutter/flutter#23235]
The ISO spec https://en.wikipedia.org/wiki/ISO_8601 states that Monday is 1 and Sunday is 7. This code returns 0 for Monday and 6 for Sunday, but is documented as following the ISO standard. Either the code should change to match the ISO standard or the docs should not state that this follows ISO 8601, but returns a zero based index that is different.

**Comment by zoechi** [comment]
Can you please post a link what `DateSymbols.FIRSTDAYOFWEEK` you are referring to and where it says ISO8601?

**Comment by zoechi** [comment]
@daanvandenhoek thanks!
I searched the Flutter source, but the source is actually in https://github.com/dart-lang/intl/blob/master/lib/date_symbols.dart
and the docs also don't hint at the `intl` package.

/cc @alan-knight

**Comment by toddabel** [comment]
Also looking at the implementation of DateSymbols (https://github.com/dart-lang/intl/blob/master/lib/date_symbol_data_local.dart) there seems to be a difference between the SHORTWEEKDAYS array (and variants) and FIRSTDAYOFWEEK. FIRSTDAYOFWEEK seems to vary by locale, 6 for en_US and 0 for en_SG, but the SHORTWEEKDAYS array for both starts on 'Sun'. This should be documented also to allow people to know they have to do a lookup correctly or the code could be changed to start the name arrays on the first day of the week for the locale.

**Comment by zoechi** [comment]
@alan-knight that sounds like there are no plans to change anything.
Should this issue be closed?

**Comment by toddabel** [comment]
No code needs to be changed, but a comment around FIRSTDAYOFWEEK should indicate that it is an index into the array and not the ISO weekday value. I suppose that should be clear, because the values are 0 to 6 rather than the 1 to 7, but it was easy to overlook. It's also important to understand that if you are trying to use FIRSTDAYOFWEEK you need to add 1 to get the ISO weekday value. I suppose this documents things.
