### ISSUE TITLE
Publishing a package with default description should be illegal

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#23240]
Many flutter packages published on pub have the description "A new flutter package project.". That's probably because that's the default description in the pubspec as generated by `flutter create`. There should be some kind of a way to remind users to change that to something more useful.

Maybe `pub publish` can warn if nothing meaningful has been provided?

/cc @kevmoo

**Comment by kevmoo** [comment]
A good issue to file https://github.com/dart-lang/pub

We could also file it at https://github.com/dart-lang/pub-dartlang-dart –
the site could prevent these default descriptions...

**Comment by christopherfujino** [comment]
@goderbauer do we still need to track this issue here, since the [dart-lang/pub issue](https://github.com/dart-lang/pub/issues/1992) exists?

**Comment by goderbauer** [comment]
Let's close it.
