### ISSUE TITLE
What widgets you need to use to implement chat bubble behavior

### ISSUE THREAD

**Issue by nailgilaziev** [flutter/flutter#23247]
We in t.me/rudart group trying to figure out how to implement chat bubble behaviour that described below:
videos:
multiline https://youtu.be/eigLIHWaub8
singleline https://youtu.be/9GMDFYwMqdU
screenshot:
![image](https://user-images.githubusercontent.com/2749021/47168455-a28b3a80-d309-11e8-9958-291dfb9408f3.png)

When time text approaching the message text additional bottom padding created. 
Is it possible to implement this behaviour in flutter?

----
video and screenshot from Telegram messenger
conversation thread https://t.me/rudart/18257

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

I think this would be a good question for StackOverflow.

**Comment by nailgilaziev** [comment]
it will be great if some of the flutter team members help with this, because it seems not so simple to implement it without deep diving to rendering.
https://stackoverflow.com/questions/52892288/how-to-implement-time-text-wrapping-behaviour-in-chat-bubble-on-flutter

**Comment by nailgilaziev** [comment]
@rlee1990 Try it yourself and you will see that it does not work as I described in this issue, when text becomes multiline.

**Comment by rlee1990** [comment]
@nailgilaziev I have it used in my applications already you may have to tweak it a little but it works.
The text is wrapped in a column and then a container

**Comment by rlee1990** [comment]
![screenshot_20181023-134804](https://user-images.githubusercontent.com/21372502/47379962-5bff5c80-d6ca-11e8-9f5e-54c8751c22e8.jpg)

**Comment by nailgilaziev** [comment]
I think that you did not fully understand what I want to achieve :)
compare this from your screenshot:
![screenshot 2018-10-23 at 20 50 10](https://user-images.githubusercontent.com/2749021/47380161-73a80680-d705-11e8-8713-1fc61054d683.png)
and this
![screenshot 2018-10-23 at 20 50 24](https://user-images.githubusercontent.com/2749021/47380171-7b67ab00-d705-11e8-864b-0dbb34b3447c.png)

last line text and time text almost in the same baseline without wrapping time text.

But when text trying to intersect, time text label goes below by increasing bubble size
![screenshot 2018-10-23 at 20 50 31](https://user-images.githubusercontent.com/2749021/47380370-f204a880-d705-11e8-87a7-f30f0ca7eb96.png)

**Comment by nailgilaziev** [comment]
this behaviour demonstrated on videos that I linked above
multiline https://youtu.be/eigLIHWaub8
singleline https://youtu.be/9GMDFYwMqdU

**Comment by rlee1990** [comment]
It can be done but you will have to play around with the code and the column and row widgets also try using a wrap widget. Or you can try resizing the time. Also there is package that will auto resize the text to fit a set space if that helps

**Comment by zoechi** [comment]
I put an example as answer to https://stackoverflow.com/questions/52659759/how-can-i-get-the-size-of-the-text-widget-in-flutter/52991124#52991124
