### ISSUE TITLE
Changing window size during "flutter run" doesn't update wrapping line length

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#23266]
When you change your terminal's size while running "flutter run", the new window width doesn't take effect and the wrapping continues to happen at the original size.

cc @gspencergoog

**Comment by Hixie** [comment]
Combined with https://github.com/flutter/flutter/issues/23267 this is particularly disruptive. A lot of people I see using flutter are frequently resizing the `flutter run` window, and this makes it so that even the non-log output (e.g. the help text) doesn't wrap correctly once you've resized the window once.

**Comment by gspencergoog** [comment]
Are you asking for historical output to be re-wrapped, or just new output?  Historical re-wrapping isn't possible unless we take control of the entire terminal and model the current text display internally a la curses (i.e. a lot of work).

If you're just talking new output, I think I know how to fix that.
