### ISSUE TITLE
Device logs in "flutter run" (et al) are word wrapped

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#23267]
When you do a tree dump from `flutter run` (e.g. press `t`), the output is word wrapped, which ends up making it unusable (since it doesn't rewrap in the terminal when you maximize your window, or when you copy and paste it into an editor).

We should not word-wrap the output of `adb logcat` (and the equivalent on iOS).

cc @gspencergoog

**Comment by Hixie** [comment]
This is really disruptive. For example, I typically have the `flutter run` console in a small window, and when a problem occurs, I maximize it. But now that no longer helps, because the text is still wrapped to the original tiny width.

**Comment by gspencergoog** [comment]
OK, I'll take a look.  In the meantime, you can specify `--no-wrap`, or pipe your run to `cat` and it should stop wrapping.
