### ISSUE TITLE
flutter D/libc-netbsd(20664): getaddrinfo: www.website.com get result from proxy

### ISSUE THREAD

**Issue by urmamb** [flutter/flutter#23262]
I am new to flutter and android. Created 2 apps, 1 is fully using REST Api and other not. The App that use REST data, I Tested on LG devices(android 7.0) and emulator works fine but recently i tested on 'alcatel one touch' using Jelly Beans 4.2.2 and strange thing happened.
The sample api fetch i am using is like so

```dart
  Future fetchNewsPreview() async {
    final response = await http.get(
        'https://www.mysite.com/admin/news_preview.php?token=ASKDGHFDSK4935345N4353N34KJ5H345');
    if (response.statusCode == 200) {
      setState(() {
        _data = json.decode(response.body);
        _loadingProgress = false;
      });
    } else {
      throw Exception('Failed to load post');
    }
  }
```
As you can see the logs

```
flutter run
Launching lib/main.dart on ALCATEL ONETOUCH 7041D in debug mode...
Initializing gradle...                      3.8s
Resolving dependencies...                      3.2s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                      3.2s
Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device ALCATEL ONE TOUCH 7041D...
D/libc-netbsd(21905): getaddrinfo: www.mysite.com get result from proxy >>
D/libc-netbsd(21905): getaddrinfo: www.mysite.com get result from proxy >>
3.9s
```

```
To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on ALCATEL ONE TOUCH 7041D is available at: http://127.0.0.1:58995/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/libc-netbsd(21905): getaddrinfo: www.mysite.com get result from proxy >>
D/libc-netbsd(21905): getaddrinfo: www.mysite.com get result from proxy >>
D/libc-netbsd(21905): getaddrinfo: www.mysite.com get result from proxy >>
D/libc-netbsd(21905): getaddrinfo: www.mysite.com get result from proxy >>
```

On the phone i see this message "Sorry AppName has stopped working"
However the other app without REST Api works fine.
I don't know whats happening.

**Comment by zoechi** [comment]
Are you still seeing this?

Please add the output of `flutter doctor -v`.

I can not make sense of this issue.
Is there any other log output together with 

> "Sorry AppName has stopped working"

(there is none in your comment above).

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
