### ISSUE TITLE
firebase_messaging onLaunch not triggered on iOS and Android

### ISSUE THREAD

**Issue by wwwdata** [flutter/flutter#23293]
## Steps to Reproduce

I am using the firebase_messaging plugin. The `onResume` and `onMessage` callbacks are working fine. However the `onLaunch` callback is never triggered. I was trying to look a bit into the source code and added some `NSLog` messages here: 

https://github.com/flutter/plugins/blob/39ba555c4ccf640b2b31943d7befc9b5cba5781d/packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m#L66

I could see my log output so I would assume that I correctly called the `configure` method from dart which is then triggering the check for a `launchNotification` and then calls the `onLaunch` channel. However, that does not trigger my registered method...

Made this default setup on the dart side. I have a print method in the `onLaunch` that never prints. 
So the setup looks something like this. The first `configuring notifications` print is always printing, just have that in there as a check to see if printing in general works.

```dart
  PushNotification() : _firebaseMessaging = FirebaseMessaging() {
    print('configuring notifications');
    _firebaseMessaging.configure(onMessage: (Map<String, dynamic> message) {
      print('onMessage: $message');
    }, onLaunch: (Map<String, dynamic> message) {
      print('onLaunch: $message');
    }, onResume: (Map<String, dynamic> message) {
      print('onResume: $message');
    });
```

I am using the latest release version `2.0.2` of `firebase_messaging`

Am I doing something wrong or is this a bug? At first I thought maybe there is some race condition but from looking at the code, I think that can be ruled out, right? Because after calling `configure` the objective c code is then pushing the initial notification in the `onLaunch` channel.

**Comment by wwwdata** [comment]
Debugged a bit more and I found out, that the `onLaunch` method after the configuration is never received on the dart side.. I don't know why.

However the `onToken` and `onIosSettingsRegistered` channel methods are correctly triggered and received.

I then experimented and added the `onLaunch` call at the same place where the `onToken` is send, and voila, it was working and correctly launched the `onLaunch` callback in dart..

So the problem is: Why does the channel call not work in the place where it currently is in the code?

Here is my new code that works:

```objc
- (void)application:(UIApplication *)application
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
#ifdef DEBUG
  [[FIRMessaging messaging] setAPNSToken:deviceToken type:FIRMessagingAPNSTokenTypeSandbox];
#else
  [[FIRMessaging messaging] setAPNSToken:deviceToken type:FIRMessagingAPNSTokenTypeProd];
#endif

  [_channel invokeMethod:@"onLaunch" arguments:_launchNotification];
  [_channel invokeMethod:@"onToken" arguments:[[FIRInstanceID instanceID] token]];
}
```

Where the `onLaunch` originally is and does not trigger anything in dart:

```objc
- (void)handleMethodCall:(FlutterMethodCall *)call result:(FlutterResult)result {
  NSString *method = call.method;
  if ([@"requestNotificationPermissions" isEqualToString:method]) {
    UIUserNotificationType notificationTypes = 0;
    NSDictionary *arguments = call.arguments;
    if ([arguments[@"sound"] boolValue]) {
      notificationTypes |= UIUserNotificationTypeSound;
    }
    if ([arguments[@"alert"] boolValue]) {
      notificationTypes |= UIUserNotificationTypeAlert;
    }
    if ([arguments[@"badge"] boolValue]) {
      notificationTypes |= UIUserNotificationTypeBadge;
    }
    UIUserNotificationSettings *settings =
        [UIUserNotificationSettings settingsForTypes:notificationTypes categories:nil];
    [[UIApplication sharedApplication] registerUserNotificationSettings:settings];

    result(nil);
  } else if ([@"configure" isEqualToString:method]) {
      NSLog(@"called configure in OBJC");
    [[UIApplication sharedApplication] registerForRemoteNotifications];
    if (_launchNotification != nil) {
        NSLog(@"got notification %@", _launchNotification);
        NSLog(@"the channel %@", _channel);
      [_channel invokeMethod:@"onLaunch" arguments:_launchNotification];
    }
    result(nil);
```

**Comment by zoechi** [comment]
Thanks for digging!
Looks like a dup of #21443.
Can we merge?

**Comment by wwwdata** [comment]
I don't know if it is the same issue. The other events trigger just fine for me under iOS. And I also don't have this flutter local notifications package installed.. It really just is the `onLaunch` that does not work for me.

**Comment by zoechi** [comment]
Ok, I leave it ope then.
Please add the output of `flutter doctor -v`.

**Comment by wwwdata** [comment]
```
╰─ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-DE)
    • Flutter version 0.9.4 at /Users/benbieker/Development/flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/benbieker/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/benbieker/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone 8 • 7A400BCD-BB17-4104-A8A6-506481AEE34D • ios • iOS 12.0 (simulator)

• No issues found!
```

**Comment by wwwdata** [comment]
Today I was also trying out everything for Android. And I am sorry to have to inform you that I got the same issues there. Everything works except the initial `onLaunch` call.. 

It must be some sort of race condition. When I added a Timer in the `FirebaseMessagingPlugin` to delay the call to `onLaunch` it went through. So I guess this is some channel registration related bug on the dart side? Because it happens on iOS and Android?

This is what I added into `FirebaseMessagingPlugin.java`

```java
  @Override
  public void onMethodCall(MethodCall call, Result result) {
    if ("configure".equals(call.method)) {
      FlutterFirebaseInstanceIDService.broadcastToken(registrar.context());
      if (registrar.activity() != null) {
        new Timer().schedule(new TimerTask() {
          @Override
          public void run() {
            sendMessageFromIntent("onLaunch", registrar.activity().getIntent());
          }
        }, 5000);
      }
      result.success(null);
```

**Comment by wwwdata** [comment]
Ok, I think I found the problem now. I was instantiating and calling the `configure` method of the `FirebaseMessaging` instance outside of a widget.

I instantiate all my services outside of widgets because I am using redux for state management.

So instantiating worked, and the `configure` call could be send over the channel to the native code. But it looks like `channel` messages can only be received once a widget was rendered? So I have to call `configure` inside `initState` and there is no other way?

I guess if it is intended to work like this, this should be mentioned in the readme of the `firebase_messaging` plugin. In there it just says I have to call it from somewhere of my dart code like it doesn't matter when it is called.

**Comment by zoechi** [comment]
Right, that cause me quite some troubles as well a while ago with Firebase Realtime Database.
It worked only when initialized inside `runApp(SomeWidget(...))`

**Comment by akeblom** [comment]
Did you guys get this to work? I am having the same problem. onLaunch does not seem to work. I am running configure() in initState() but onLaunch is never fired. Tried both ios and android. And I just tried the example code from the plugin repo with the same outcome.

**Comment by Atominac** [comment]
> Ok, I think I found the problem now. I was instantiating and calling the `configure` method of the `FirebaseMessaging` instance outside of a widget.
> 
> I instantiate all my services outside of widgets because I am using redux for state management.
> 
> So instantiating worked, and the `configure` call could be send over the channel to the native code. But it looks like `channel` messages can only be received once a widget was rendered? So I have to call `configure` inside `initState` and there is no other way?
> 
> I guess if it is intended to work like this, this should be mentioned in the readme of the `firebase_messaging` plugin. In there it just says I have to call it from somewhere of my dart code like it doesn't matter when it is called.

can you please attach some sample code

**Comment by akeblom** [comment]
I suppose it did work all the time. I just did a silly mistake!

**Comment by mleonhard** [comment]
If both onLaunch and onResume are not working, then make sure you are sending "click_action":"FLUTTER_NOTIFICATION_CLICK" in the notification payload.  See https://github.com/flutter/flutter/issues/32393#issuecomment-497726280 .

**Comment by kroikie** [comment]
@wwwdata

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/604. Any further collaboration will be done there.

**Comment by Nico04** [comment]
> 
> 
> Ok, I think I found the problem now. I was instantiating and calling the `configure` method of the `FirebaseMessaging` instance outside of a widget.
> 
> I instantiate all my services outside of widgets because I am using redux for state management.
> 
> So instantiating worked, and the `configure` call could be send over the channel to the native code. But it looks like `channel` messages can only be received once a widget was rendered? So I have to call `configure` inside `initState` and there is no other way?
> 
> I guess if it is intended to work like this, this should be mentioned in the readme of the `firebase_messaging` plugin. In there it just says I have to call it from somewhere of my dart code like it doesn't matter when it is called.

I had the same issue even though configure was called inside `initState`.
But it was inside a `WidgetsBinding.instance.addPostFrameCallback`.
Calling it directly from `initState `worked.

**Comment by raLaaaa** [comment]
> Ok, I think I found the problem now. I was instantiating and calling the `configure` method of the `FirebaseMessaging` instance outside of a widget.
> 
> I instantiate all my services outside of widgets because I am using redux for state management.
> 
> So instantiating worked, and the `configure` call could be send over the channel to the native code. But it looks like `channel` messages can only be received once a widget was rendered? So I have to call `configure` inside `initState` and there is no other way?
> 
> I guess if it is intended to work like this, this should be mentioned in the readme of the `firebase_messaging` plugin. In there it just says I have to call it from somewhere of my dart code like it doesn't matter when it is called.

Fixed it for me. This definitely should be stated somewhere in the docs.
