### ISSUE TITLE
Crash on start on Android tablet with Hello_World

### ISSUE THREAD

**Issue by jslavitz** [flutter/flutter#23302]
I'm having a weird issue on Galaxy tablet. When I run the command `flutter run` in the hello_world directory, the app crashes on start. Flutter_gallery works fine though. Seems to only happen on my tablet, tested on a phone, the app starts as expected. This is happening on the most recent build of flutter. The gist is here: https://gist.github.com/jslavitz/c5d9ad43b1332512a168522d14622617

Flutter doctor:
```
[✓] Flutter (Channel master, v0.10.1-pre.102, on Mac OS X 10.13.6 17G65,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[!] VS Code (version 1.27.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.```

**Comment by zoechi** [comment]
Did #6619 fix this issue?
