### ISSUE TITLE
  [Dart] The named parameter 'home' isn't defined

### ISSUE THREAD

**Issue by phfawzy** [flutter/flutter#23306]
Hey flutter developers...when i am trying to run an app in VS code, this message shows up "The named parameter 'home' isn't defined."..

It is a general problem for all flutter projects .flutter doctor says no issues.

 I also tried creating a new project from scratch using android studio and Intellij and no progress .it says (theme: and home:) are not identified as named parameters.before that everything was perfectly fine ..please help! :(

 

![flutter doctor](https://user-images.githubusercontent.com/39815901/47248564-ebc7b100-d413-11e8-80ce-fb08d9572ac9.png)
![main dart code](https://user-images.githubusercontent.com/39815901/47248565-ec604780-d413-11e8-9171-d74ab10e1504.png)
![problem](https://user-images.githubusercontent.com/39815901/47248566-ec604780-d413-11e8-92e1-d9806448ed57.png)

**Comment by zoechi** [comment]
I assume this is your related question on StackOverflow https://stackoverflow.com/questions/52901267/dart-the-named-parameter-home-isnt-defined

**Comment by zoechi** [comment]
I assume your Flutter installation is corrupted.
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
