### ISSUE TITLE
Bump sky_engine version for flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2331]
Hi, I'd like to generate docs for dart:* libs. sky_engine on master has the right _embedder.yaml , but flutter isn't yet pointing to the latest version of sky_engine. The master branch of flutter repo still pulls down a version of sky_engine with _sdkext file in it.

Thanks!

**Comment by sethladd** [comment]
cc @johnmccutchan @abarth

**Comment by Hixie** [comment]
Releasing the engine is easy: https://github.com/flutter/engine/wiki/Release-process :-)

**Comment by eseidelGoogle** [comment]
We've released the engine in the last 2 days.  Can we close this?

**Comment by abarth** [comment]
Yes, these docs are live.
