### ISSUE TITLE
GestureDetector apparently doesn't receive Drag events when it has a ListView in it.

### ISSUE THREAD

**Issue by Footurist** [flutter/flutter#23325]
Am I missing something? The documentation says that events bubble up from the innermost child to the ancestors, but below code will not print "dragged" to the console. It does print "tapped" though.
Applying NeverScrollablePhyiscs to the ListView does work, but i want to listen on the event on both levels. Applying HitTestBehavior.translucent to the GestureDetector doesn't change anything.

```dart
import "package:flutter/material.dart";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
      return MaterialApp(
        home: MyHomePage(),
      );
    }
}

class MyHomePage extends StatelessWidget {
  @override
    Widget build(BuildContext context) {
      return Scaffold(
        body: GestureDetector(
          onVerticalDragUpdate: (DragUpdateDetails details) {
            print("dragged");
          },
          onTap: () {
            print("tapped");
          },
          child: ListView.builder(
            itemBuilder: (context, index) {
              return Container(
                padding: EdgeInsets.all(20.0),
                child: Text(
                  "The GestureDetector above me does not react to drag events. Maybe my parent is at fault?"
                )
              );
            },
          )
        )
      );
    }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Got an answer in https://stackoverflow.com/questions/52910339/flutter-gesturedetector-apparently-doesnt-receive-drag-events-when-it-has-a-li?rq=1

**Comment by officer47p** [comment]
I'm reopening this issues since I have the same problem, it's a really annoying bug that's been around for more than 2 years(Happy new year everyone🎉🎉),  using Listener widget is a pain and you can't detect gestures with it and since it hasn't any threshold value, you can't differ a tap from a drag start.
PLEASE reopen this issue.
Thanks

**Comment by PieterPicup** [comment]
@officer47p I am having the same issue with the gesture not getting back up to the GestureDetector from the ListView, however if for some reason you do not need the listview to actually scroll you can set the physics of the listview to NeverScrollableScrollPhysics and it will get up to the detector. 
I have been trying all sorts of things to get the detector to get the scroll and this works but only half for me as I still need my listview to scroll once my detector scroll has reached a max scroll.
