### ISSUE TITLE
Scrollable TabBar display bug in --release build

### ISSUE THREAD

**Issue by Kapranov98** [flutter/flutter#23339]
Hello. There is a problem with the display of the Scrollable TabBar in --release assemblies. I took the sample code from the official documentation, made 5 tabs and got the result as in the screenshot. The first tab is partially outside the left edge of the screen. There is no problem in the --debug build.

Code [main.dart](https://gist.github.com/Kapranov98/ff62ee0929aa3037a370b7405525eb1e)

## Logs
```
Analyzing tabview_sample...

   info - Unused import: 'package:tabview_sample/main.dart' - test\widget_test.dart:11:8 - unused_import
  error - The constructor returns type 'dynamic' that isn't of expected type 'Widget' - test\widget_test.dart:16:29 -
         strong_mode_invalid_cast_new_expr
  error - Undefined class 'MyApp' - test\widget_test.dart:16:33 - undefined_class

3 issues found. (ran in 4.4s)
```

```
[√] Flutter (Channel master, v0.10.1-pre.108, on Microsoft Windows [Version 10.0.17763.104], locale ru-RU)
    • Flutter version 0.10.1-pre.108 at D:\Programs\flutter
    • Framework revision 8007e1bc2f (24 hours ago), 2018-10-19 14:18:47 -0700
    • Engine revision 2707b74338
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Programs\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Programs\Android_SDK
    • Java binary at: D:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Programs\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available
```
## Screenshot
![screenshot_2018-10-21-00-45-04-320_com example tabviewsample](https://user-images.githubusercontent.com/4894671/47260787-aa460d00-d4ca-11e8-88d2-40dd93aa8df5.png)

**Comment by jason-simmons** [comment]
This is a race between the embedder providing the viewport dimensions and the TabBar widget calculating the scroll offset.  The embedder may initially claim that the viewport has zero width/height, and if the TabBar framework code runs before the real values arrive then the resulting offset will be wrong.  The framework does not appear to recalculate the offset when the viewport metrics are updated.

@HansMuller

**Comment by jelly-cai** [comment]
how to solve this problem

**Comment by kunkun12** [comment]
this problem also happed to me,  not solved

**Comment by fengzhongyun1992** [comment]
我碰到这个bug, 思考了两个多星期，通过qq群问人，有人通过 添加动画来 规避 这个bug。
我是通过添加 启动页 来规避这个bug的。 启动页项目参考：https://github.com/bowen919446264/demowelcome.git

**Comment by kunkun12** [comment]
upgrade newest flutter sdk ,It is solved

**Comment by HansMuller** [comment]
Based on https://github.com/flutter/flutter/issues/23339#issuecomment-474646815 I'm going to close this issue. If there's still a problem, please reopen it.
