### ISSUE TITLE
Resuming accessibility while stocks is up crashes stocks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2333]
Run Stocks.
Go to settings.
Turn on Talkback.
Suspend it by doing the L gesture and choosing Suspend.
Go back to Stocks.
Unsespend Talkback from the notification tray.
Crash.

**Comment by goderbauer** [comment]
I can't reproduce this one and I assume it has been fixed with one of the recent changes to accessibility. Please re-open if you're still experiencing this problem.
