### ISSUE TITLE
Issue from website page 在Flutter中构建布局

### ISSUE THREAD

**Issue by lyb5215659** [flutter/flutter#23347]
From URL: https://www.flutterchina.club/tutorials/layout/index.md
在本也 此处 Note: If you have problems, you can check your code against lib/main.dart on GitHub.链接（https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/lakes/main.dart）
这个 访问不了，404: Not Found

**Comment by InMatrix** [comment]
This is an issue on the community-supported flutterchina.club site. It looks like this broken link has been reported on the translated page itself: https://flutterchina.club/tutorials/layout/. Please see the last comment on that page.
