### ISSUE TITLE
Unable to run flutter doctor upgrade WIN10

### ISSUE THREAD

**Issue by cfreemoser** [flutter/flutter#23353]
Running `flutter doctor upgrade` failes cause `Running pub upgrade` is unable to succeed. Here is the console output (My network works fine and I am not located in china):

Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Gewartet wird 0 Sekunden. Drücken Sie STRG+C, um den Vorgang zu beenden...
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)

Gewartet wird 0 Sekunden. Drücken Sie STRG+C, um den Vorgang zu beenden...
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)

Gewartet wird 0 Sekunden. Drücken Sie STRG+C, um den Vorgang zu beenden...
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

Gewartet wird 0 Sekunden. Drücken Sie STRG+C, um den Vorgang zu beenden...
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)

Gewartet wird 0 Sekunden. Drücken Sie STRG+C, um den Vorgang zu beenden...
Running pub upgrade...
Could not resolve URL "https://pub.dartlang.org".
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)

Gewartet wird 0 Sekunden. Drücken Sie STRG+C, um den Vorgang zu beenden...
Running pub upgrade...

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Is this on Windows?
What directory did you install Flutter to?
Is this behind a proxy/firewall (China)?

**Comment by cfreemoser** [comment]
Yes its a windows system. I actually found the issue: somehow I had a HTTP Proxy specified in the environment variable http_proxy. Removing it resolved the issue.
