### ISSUE TITLE
baby_names

### ISSUE THREAD

**Issue by gonzaloalonzo** [flutter/flutter#23354]
![image](https://user-images.githubusercontent.com/12562128/47272153-aad8b500-d557-11e8-8b16-234c34e790e4.png)

din`t work!!

**Comment by zoechi** [comment]
I think this is only a warning.

Please add the output of `flutter doctor -v`
and please also add the full console output as text.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
