### ISSUE TITLE
Gallery App, Scrollable Tabs, last tab (language) is truncated

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2335]
After swiping left all the way to the end, the top tab bar does not also scroll. Notice how the name for the last tab is truncated.

(I assume that the top tab bar should also scroll as the tabs in the body scrolls? Regardless, I can't manually scroll the tab bar itself. I'm on a Nexus 6.)

![screenshot_20160302-125540](https://cloud.githubusercontent.com/assets/5479/13475169/3affc7ec-e076-11e5-9af5-c5eef9c8f511.png)

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Fixed by https://github.com/flutter/flutter/pull/2350
