### ISSUE TITLE
Add some custom logic to launch screen

### ISSUE THREAD

**Issue by mahdizakizadeh** [flutter/flutter#23361]
Hi guys,
Is there any way to add some logic to flutter launch screen and use it as app loading screen?
For example set a stream to it to get user data from firebase first and then navigate to next page

**Comment by zoechi** [comment]
Not sure what you mean with "flutter launch screen". 
At first a native splash screen image is shown, there you can't use Flutter/Dart to customize.
After that the Flutter app is started and it's entirely up to you what you display there.
 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
