### ISSUE TITLE
StreamBuilder hangs when listening to Firestore snapshot

### ISSUE THREAD

**Issue by dooboolab** [flutter/flutter#23368]
## Steps to Reproduce
I am trying to use the bloc pattern with firebase and having hard time since there is not good tutorial out there which uses `firebase` and `bloc pattern`.

I've faced strange thing while doing this and worked hard to find out the problem but couldn't.

I've created `UserBloc` and tried to set `UserModel` after listening to `Firestore snapshot`.
```
class UserBloc extends Object {
  final _user = StreamController<UserModel>.broadcast();
  final _uid = StreamController<String>.broadcast();

  Stream<UserModel> get user => _user.stream;
  Stream<String> get uid => _uid.stream;

  Function(UserModel) get setUser => _user.sink.add;
  Function(String) get setUID => _uid.sink.add;

  Stream<DocumentSnapshot> userStream;

  UserBloc() {
    uid.listen((uid) {
      print('user : $uid');
      if (uid != null) {
        fromUID(uid);
      }
    });
  }

  fromUID(String uid) {
    print('fromUID');
    userStream = Firestore.instance.collection('users').document(uid).snapshots();

   /// works ok when I delete below subscription
    userStream.listen((data) {
    });
  }

  dispose() {
    _user.close();
    _uid.close();
  }
}
```

Then I used the `StreamBuilder` inside my widget like below.
```
  StreamBuilder(
    stream: userBloc.userStream,
    builder: (context, snapshot) {
      print(snapshot.connectionState);
      print(snapshot.data);
      return Text('testing');
    },
  );
```

The problem is the `snapshot.connectionState` is always `waiting`. However, when I delete the subscription code which is ` userStream.listen((data) {`, I was able to get this working. All the example do the listen and set the data in the constructor of `bloc`. I have no idea why this is happening.

## Logs

```
...
[  +12 ms] [DEVICE LOG] 2018-10-22 22:58:48.521384+0900  localhost Runner[27014]: (Flutter) flutter: isHost: false
[        ] flutter: isHost: false
[  +46 ms] [DEVICE LOG] 2018-10-22 22:58:48.567490+0900  localhost Runner[27014]: (Flutter) flutter: ConnectionState.waiting
[        ] [DEVICE LOG] 2018-10-22 22:58:48.567584+0900  localhost Runner[27014]: (Flutter) flutter: null
[        ] flutter: ConnectionState.waiting
[        ] flutter: null
[  +69 ms] [DEVICE LOG] 2018-10-22 22:58:48.636881+0900  localhost Runner[27014]: (Flutter) flutter: userId: 9xqbCzwstrOI7MVXW7cLG2KMP0u1
[        ] flutter: userId: 9xqbCzwstrOI7MVXW7cLG2KMP0u1
[   +1 ms] [DEVICE LOG] 2018-10-22 22:58:48.638997+0900  localhost Runner[27014]: (Flutter) flutter: documents: 1
[        ] [DEVICE LOG] 2018-10-22 22:58:48.639076+0900  localhost Runner[27014]: (Flutter) flutter: docChanges: 1
[        ] flutter: documents: 1
[        ] flutter: docChanges: 1
[   +2 ms] [DEVICE LOG] 2018-10-22 22:58:48.641936+0900  localhost Runner[27014]: (Flutter) flutter: change
[        ] [DEVICE LOG] {hostId: JtaSMOrZNlOlKQLPLCfDgWCglF93, guestId: 9xqbCzwstrOI7MVXW7cLG2KMP0u1, marketId: 9xqbCzwstrOI7MVXW7cLG2KMP0u1, title: My Market, lastMessage: test, updatedAt: 2018-10-10 10:29:24.710, createdAt: 2018-10-10 10:29:24.710}
[        ] flutter: change
[        ] {hostId: JtaSMOrZNlOlKQLPLCfDgWCglF93, guestId: 9xqbCzwstrOI7MVXW7cLG2KMP0u1, marketId: 9xqbCzwstrOI7MVXW7cLG2KMP0u1, title: My Market, lastMessage: test, updatedAt: 2018-10-10 10:29:24.710, createdAt: 2018-10-10 10:29:24.710}
[        ] [DEVICE LOG] 2018-10-22 22:58:48.643003+0900  localhost Runner[27014]: (Flutter) flutter: init
[        ] flutter: init
[  +12 ms] [DEVICE LOG] 2018-10-22 22:58:48.655261+0900  localhost Runner[27014]: (Flutter) flutter: ConnectionState.waiting
[        ] [DEVICE LOG] 2018-10-22 22:58:48.655327+0900  localhost Runner[27014]: (Flutter) flutter: null
[        ] flutter: ConnectionState.waiting
...
```

```
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-KR)
    • Flutter version 0.8.2 at /Users/hyochan/flutter/sdk
    • Framework revision 5ab9e70727 (6 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hyochan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/hyochan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone 6 • 1D1C8F6D-7C5E-46FC-B9E2-A9B69968979F • ios • iOS 12.0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
This looks like a support request.
Did you try asking on StackOverflow?

**Comment by dooboolab** [comment]
@zoechi Ok. I will. But this looks really weird to me.

**Comment by dooboolab** [comment]
@zoechi Yes. But then I am listening to `userBloc.userStream` which is stream from firestorm `DocumentSnapshot`.

**Comment by dooboolab** [comment]
@zoechi Thanks for the reply. I've done the firestorm subscription like below, then still the same.
```
userStream = Firestore.instance.collection('users').document(uid).snapshots().asBroadcastStream();
```
userStream.listen((snap) {
})l
```

The funny thing is that it works fine if I remove `userStream.listen`.

**Comment by zoechi** [comment]
What if you remove `asBroadcastStream()`. 
You shouldn't need that and it probably leads to behavior you don't expect.

**Comment by dooboolab** [comment]
@zoechi I've tried that too. I have added `asBroadcastStream` to try out for your answer. I've looked in the code in `firestore` plugin. There was already `StreamController` with `Broadcast`.
```
controller = StreamController<DocumentSnapshot>.broadcast(
```

I almost give up using `firestore stream` in my custom `bloc` object. No article helps to solve this problem. Is there any good tutorial that uses custom bloc listening to `firestore`'s `stream? I want to fetch the data from `firestore` first then assign to my custom model class.

Also I've posted this to [stackoverflow](https://stackoverflow.com/questions/52935452/streambuilder-hangs-when-listening-to-firestore-snapshot).

**Comment by dooboolab** [comment]
@zoechi I feel like this could be reopened because when I try to listen on my own `stream` object, it works fine. It hangs only when I try to listen to `firestore` stream. So I mean it works when I try to 
```
final _user = StreamController<UserModel>.broadcast();
Stream<UserModel> get user => _user.stream;
Function(UserModel) get setUser => _user.sink.add;

Stream<DocumentSnapshot> userStream = Firestore.instance.collection('users').document(uid).snapshots();

user.listen((data) {
});
```
instead
```
userStream.listen((data) {
});
```

**Comment by zoechi** [comment]
It probably "hangs" because it waits for an event that is never emitted.
I think this needs to be tracked down to something more concrete.
I don't see how the Flutter team could reproduce your current issue without your whole Firebase setup.
If it's an issue with bloc it shouldn't be hard to reproduce without Firebase.
If it's an issue with Firebase it shouldn't be easy to reproduce without bloc.

**Comment by dooboolab** [comment]
@zoechi Thank you. I will try to dig this more. One last question.

I want to prevent flutter from dropping broadcast stream event when no widget is listening. Because I want to listen to this in other page routes.

I have bloc object like below.

```
    class UserBloc extends Object {
        final _user = StreamController<UserModel>.broadcast();
        final _uid = StreamController<String>.broadcast();

        Stream<UserModel> get user => _user.stream;
        Stream<String> get uid => _uid.stream;

        Function(UserModel) get setUser => _user.sink.add;
        Function(String) get setUID => _uid.sink.add;
```
I am listening to those streams in my sub page route
```
    StreamBuilder(
        stream: userBloc.user,
        builder: (context, snapshot) {
        print(snapshot.connectionState);
        print(snapshot.data);
        return Text('hi');
        },
    ),
```
It works without using broadcast stream. However, no luck when I changed to broadcast.

The problem is broadcast streams drop events when no one is listening as you described but I want my widget to start listening when my other MaterialPage pops up.

Using broadcast stream, data is always null in stream when my widget started listening.

How can I achieve this?

**Comment by zoechi** [comment]
> What if you remove `asBroadcastStream()`.
You shouldn't need that and it probably leads to behavior you don't expect.

As I said, broadcast stream is probably not what you want. 
A BroadcastStream is for events like mousemove where you don't care events being dropped when nobody is listening. 
If you don't want to lose events, don't use BroadcastStream.

**Comment by dooboolab** [comment]
@zoechi Thanks again for clarifying this. Ok, then I may restructure my app to create `bloc` instance right after the `Widget` in my page route creates. I was trying to create one global `bloc` and subscribe them in multiple widgets.

**Comment by ianspryn** [comment]
I ran into this exact issue. I'm sharing my solution in hopes that some poor soul who stumbles upon this same thread may glean some insight from my findings.

My issue was this: I didn't want to have two streams listening to Firestore. I only wanted one stream to reduce Firebase costs. Here is how I solved the issue.

**Basically, create a new StreamController and pass every event received from your original stream to your stream controller**

This is an example of my class that retrieves Firebase content and sets up the streams.
```
class FirebaseStreams {
  StreamController<QuerySnapshot> _streamController = StreamController<QuerySnapshot>();

  // StreamBuilder widget will listen to this 
  Stream<QuerySnapshot> get stream => _streamController.stream;

  StreamSubscription<QuerySnapshot> _streamSubscription;

  // This is the Firestore query that is built to retrieve a stream of documents
  Stream<QuerySnapshot> get allUsers {} // TODO

  init() {
    _streamSubscription = allUsers.listen((event) {
      // Pass the event from the stream to your streamController so that you can listen to its own stream in your StreamBuilder widget
      _streamController.sink.add(event);
      
      // TODO do whatever else you would like with the event
    });
  }

  dispose() {
    _streamController.close();
    _streamSubscription.cancel();
  }
}
```

This is the StreamBuilder widget.
```
return StreamBuilder<QuerySnapshot>(
  stream: firebaseStreams.stream,
  builder: (context, snapshot) {
    /// TODO
  }
);
```

After doing this, I was able to listen to my stream and do what I please with that data, and then set up a StreamBuilder to show the data to the user.
