### ISSUE TITLE
AppBar height is not customizable

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#23373]
AppBar (or `RenderSliverAppBar`) use a static `kToolbarHeight` to set their height. That's great for most applications (i.e. anything that follows android & material design), but in the case where someone wants something different or more customized (but still using the very useful appbar) it's not possible to change it.

It would be great if this were instead possible to set using the Theme (or something like that), although looking at the code it appears that the constant is used in a few places where there is no context, so I could see a bit of refactoring needed.

I could also see this becoming useful for an application built for accessibility, as the sizes of everything could be increased for easier usage.

**Comment by zoechi** [comment]
#7330 looks related

**Comment by Briano99** [comment]
The AppBar maximum height for the toolbar is very restrictive. It would save a lot of work for a lot of people including me if this restriction is removed. I can make the toolbar height less than 56 by changing the height of its container, but by increasing the height of the AppBar does not allow the toolbar height to be increased. It would be great if this restriction could be removed. I need the toolbar height to be larger than 56 for my apps. Yes, #7330 looks related. Thanks.

**Comment by brianoh** [comment]
AppBar "flexibleSpace:" appears to solve this issue 100% for me. If this appears to be the case for other situations, perhaps this issue should be marked resolved.

**Comment by RaviKavaiya** [comment]
@brianoh I face the same issue. Basically, I want to show something DIFFERENT on the `title` property of the 'SliverAppBar`. 
flexibleSpace doesn't work for me.

So, the title of this issue is perfect. We should be able to customize the height.

**Comment by RaviKavaiya** [comment]
@rmtmckenzie I have created a modified version of `app_bar.dart`.
[https://gist.github.com/RaviKavaiya/aa93135a3aa407ae3ad885997640ec7c](https://gist.github.com/RaviKavaiya/aa93135a3aa407ae3ad885997640ec7c)

Can anybody please test it and create a pull request? (If anyone is interested in creating PR, link back to this issue, please).
