### ISSUE TITLE
Images scaled by device resolution have aliasing artifacts

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#2337]
Cloned from #2313.  That specific issue was fixed by switching to the icon font for Material icons. However, there's still something happening in the device resolution scaling logic that is causing extra artifacts.

**Comment by krisgiesing** [comment]
For the specific case of the material Send icon used in the code lab example, run on a Nexus 5X:

The device pixel ratio is 2.625; we're choosing the 3.0x asset, which is expected. However, something seems to be going on during the rendering that is causing some kind of extra aliasing artifacts. Below I have a side by side comparison of the original image along with its rendering, magnified for visibility.

![screenshot from 2016-03-02 13 25 26](https://cloud.githubusercontent.com/assets/13855787/13475944/53adf8be-e07a-11e5-8705-ce4fed13cd2f.png)

**Comment by krisgiesing** [comment]
@abarth, is the aliasing done during image paint dictated by SkPaint::getFilterQuality()?

**Comment by krisgiesing** [comment]
Seems so; same comparison with the filter quality set to high:

![screenshot from 2016-03-02 13 37 10](https://cloud.githubusercontent.com/assets/13855787/13476278/ebfdf082-e07b-11e5-9a74-1fab72ce3308.png)

**Comment by abarth** [comment]
Yes, that seems likely.

```
enum SkFilterQuality {
    kNone_SkFilterQuality,      //!< fastest but lowest quality, typically nearest-neighbor
    kLow_SkFilterQuality,       //!< typically bilerp
    kMedium_SkFilterQuality,    //!< typically bilerp + mipmaps for down-scaling
    kHigh_SkFilterQuality       //!< slowest but highest quality, typically bicubic or better
};
```

We should see what these map to in the GL backend.  I would have expected bilinear to look pretty good on this example, but my intuition might be off.  We might try experimenting with the different qualities and upscaling versus downscaling.

**Comment by krisgiesing** [comment]
Here's the same comparison with filter quality "low". Looks pretty reasonable to my eye.

![image](https://cloud.githubusercontent.com/assets/13855787/13477905/60307f90-e083-11e5-9f7b-99bc0eee3f95.png)
