### ISSUE TITLE
Error occurs with while trying to use image picker in my flutter app

### ISSUE THREAD

**Issue by NikolaTotev** [flutter/flutter#23378]
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-core-ui' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

**Comment by NikolaTotev** [comment]
Also this error occurs :
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:support-fragment' has different version for the compile (26.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

* Try:

**Comment by zoechi** [comment]
Merging with #20511
