### ISSUE TITLE
Request a video intro to key concepts in the Flutter framework

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#23383]
In our recent UX studies, we've observed a lot of initial difficulty for developers who came from other frameworks to realize UI programing in Flutter was reactive and UI changes should be done by changing the state of the UI instead of manipulating UI elements directly. Those developers could have benefited from a quick but upfront introduction to the key aspects of the framework, so they don't attempt to apply their existing UI programming knowledge inapplicable to Flutter. 

Here is my request: can we turn [A Tour of the Flutter Framework](https://flutter.io/widgets-intro/) into a short video and feature it prominently on our website? It could pair nicely with the more marketing-oriented [Introducing Flutter](https://www.youtube.com/watch?v=fq4N0hgOWzU) video.

Cc: @RedBrogdon, @galeyang, @jayoung-lee, @Sfshaza

**Comment by RedBrogdon** [comment]
Hmm. I'm not sure how short a video could be and still cover all of these topics:

* Introduction
* Hello World
* Basic widgets
* Using Material Components
* Handling gestures
* Changing widgets in response to input
* Bringing it all together
* Responding to widget lifecycle events
* Keys
* Global Keys

We do have videos in the pipeline for Stateful/Stateless/Inherited and Keys, which will go over some of this content.

If this is your primary concern:

> programing in Flutter [is] reactive and UI changes should be done by changing the state of the UI instead of manipulating UI elements directly

We could totally create a short video on that. I've done two recent conference talks about how the widget/element/render trees relate to one another and the motivation behind the way things work. They could probably be distilled into something short and straightforward. Would that help here?

**Comment by InMatrix** [comment]
The research question is what is the minimum amount of upfront learning required to get an experienced developer started on Flutter and continue with on-demand learning? 

> We could totally create a short video on that. I've done two recent conference talks about how the widget/element/render trees relate to one another and the motivation behind the way things work. They could probably be distilled into something short and straightforward. Would that help here?

Yes, totally. It doesn't even need to touch the three trees, IMO. The primary goal of this video is to quickly point out paradigm shifts to developers not familiar with reactive UI frameworks but otherwise proficient in programming, so they can make an informed decision on when they can learn by trial and error and when they do need to pause and read stuff. 

The research question, if I may frame it that way, is this: what is the minimum amount of upfront learning required to get an experienced developer started on Flutter and continue with on-demand learning? 

The goal is to answer this question:

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2009](https://github.com/flutter/website/issues/2009) via [**ZenHub**](https://www.zenhub.com/)
