### ISSUE TITLE
TextField has a ripple effect that seems to be outside of guidelines

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#23380]
@willlarche I may be wrong on this but the current TextField implementation has a ripple effect within the bounds of the text field and I couldn't see anywhere in the spec (or other examples) where this is defined. It feels a bit strange.

It would be awesome to be able to disable that particular aspect.

**Comment by willlarche** [comment]
Great catch. You're right. Ink ripples were cut from Outline and Filled text fields earlier this year.

For backwards compatibility, we should keep it (the old Underline styles had it.) But I would prefer it if the default was 'off'.

**Comment by brooth** [comment]
Any news?

**Comment by mo-ah-dawood** [comment]
Same here i need a solution

**Comment by willlarche** [comment]
There is no news here. We'd accept a good PR if anyone wanted to make a backwards compatible fix, though!

**Comment by ghostTing** [comment]
i have same problem
