### ISSUE TITLE
Changes to an Android view layout direction while it's being created are ignored

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#23386]
Calling `AndroidViewController.setLayoutDirection` while we are awaiting for the create system channel call to return (called from `AndriodViewController._create`) will have no effect.

**Comment by meggamind** [comment]
I would like to pick this one up. Can you please assign it to me

**Comment by amirh** [comment]
@meggamind thanks!
Feel free to use this issue to discuss a proposed solution or send a PR, your comment is enough to inform anyone coming to pick this issue that you've started looking at it.

**Comment by meggamind** [comment]
@amirh Can you provide me with source code or a direction to reproduce this issue?

**Comment by markusaksli-nc** [comment]
Hi @amirh 
Is this still a relevant issue?
Could you clarify what code this refers to exactly?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
