### ISSUE TITLE
Firebase Messaging does not work with Gradle 3.1.2

### ISSUE THREAD

**Issue by CrunchyFlannel** [flutter/flutter#23389]
Some of my dependencies can only be put into a release apk with Gradle 3.1.2, so whenever I revert back to that in my android build.gradle file, none of my push notifications are being received by users. I do not get any errors from this so I am wondering if the Firebase messaging package is only meant for gradle 3.2.1.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by CrunchyFlannel** [comment]
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at C:\Users\james\flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\james\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code, 64-bit edition (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Pixel • FA69R0314604 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by kroikie** [comment]
@CrunchyFlannel

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/602. Any further collaboration will be done there.
