### ISSUE TITLE
Flutter App crash on IPhone7 && iOS12, fatal error: "NVPR disabled"

### ISSUE THREAD

**Issue by CLARKYJ** [flutter/flutter#23390]
## Steps to Reproduce

1.compile engine as CONTRIBUTING.md said.
2.create a simple flutter project on AS and run, it's fine.
3. flutter run `--local-engine-src-path=/Users/yinjie/Documents/flutter/engine/src --local-engine=ios_debug_unopt`

## Logs

I will print the xcode log here. cause i think it's a runtime error rather then compile time error.
```
2018-10-23 10:25:20.733253+0800 Runner[914:388087] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2018-10-23 10:25:20.733332+0800 Runner[914:388087] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2018-10-23 10:25:20.770821+0800 Runner[914:388125] flutter: Observatory listening on http://127.0.0.1:52335/
../../third_party/skia/src/gpu/GrPathRendering_none.cpp:22: fatal error: "NVPR disabled"
```
```
JIEYIN-MB1:src yinjie$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.28.2)
[✓] Connected devices (1 available)
```
! Doctor found issues in 2 categories.

**Comment by CLARKYJ** [comment]
GrPathRendererChain::GrPathRendererChain(GrContext* context, const Options& options) {
    const GrCaps& caps = *context->contextPriv().caps();
    if (options.fGpuPathRenderers & GpuPathRenderers::kDashLine) {
        fChain.push_back(sk_make_sp<GrDashLinePathRenderer>());
    }
    if (options.fGpuPathRenderers & GpuPathRenderers::kStencilAndCover) {
        sk_sp<GrPathRenderer> pr(
           GrStencilAndCoverPathRenderer::Create(context->contextPriv().resourceProvider(), caps));
        if (pr) {
            fChain.push_back(std::move(pr));
        }
    }


GrPathRenderer* GrStencilAndCoverPathRenderer::Create(GrResourceProvider* resourceProvider,
                                                      const GrCaps& caps) {
    SkDEBUGFAIL("NVPR disabled");
    return nullptr;
}

i checked the soruce code, the create api just abort... so it's not implemented ?

**Comment by CLARKYJ** [comment]
and set breakpoint, it seems that 'options.fGpuPathRenderers' is kAll...

**Comment by wang542413041** [comment]
Hello, I have integrated flutter in existing projects today, but I have been stuck on one issue.

ld: '/Users/dp/Desktop/my_flutter/.ios/Flutter/engine/Flutter.framework/Flutter' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dp/Desktop/my_flutter/.ios/Flutter/engine/Flutter.framework/Flutter' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can you help me for some answers ?

**Comment by CLARKYJ** [comment]
@wang542413041 sorry， I didn't met this before. But integrate flutter in existing projects. I recmond you to have a look at https://pub.dartlang.org/packages/hybrid_stack_manager?spm=a2c4e.11153940.blogcont626069.12.315473b3FpkAXp#-versions-tab-

**Comment by chinmaygarde** [comment]
This is fixed with recent Skia rolls. Please reopen if you are still seeing this issue on tip-of-tree.
