### ISSUE TITLE
could not find package mockito at https://storage.flutter-io.cn

### ISSUE THREAD

**Issue by lyb5215659** [flutter/flutter#23399]
Flutter Doctor：
Running pub upgrade...
Because flutter_tools depends on mockito any which doesn't exist (could not find package mockito at https://storage.flutter-io.cn), version solving failed.

**Comment by rubensdemelo** [comment]
You should add mockito dependency to your pubspec.yaml

**Comment by zoechi** [comment]
https://storage.flutter-io.cn is not maintained by the Flutter team as far as I know.
Please look up the maintainers and report the issue there.
