### ISSUE TITLE
Text snaps to pixel grid, images don't

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#234]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Oct 26, 2015 at 22:35 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1811_

----

Set your timeDilation factor to 100, then run the card collection app and overscroll the drawer by a lot. Watch the text and images as they scroll back down. The text looks like it's shaking up and down compared to the smoothly moving images.

**Comment by abarth** [comment]
I have the repro.
