### ISSUE TITLE
Context passing around in StatelessWidget

### ISSUE THREAD

**Issue by GreenTigerEye** [flutter/flutter#23400]
Why do we have to pass the context around in a `StatelessWidget`?

**Improvement Question**: Wouldn't it be better to allow also in a `StatlessWidget` the `context` everywhere? Or do I miss some point?

Bad example!  Context needs to be passed around in a `StatelessWidget`.
```
class ContextPassingAroundNeeded extends StatelessWidget {
  @override
  Widget build(BuildContext context) => method1(context);

  Widget method1(BuildContext context) {
    context.inheritFromWidgetOfExactType(Type); // whatever
    
    return method2(context);
  }

  Widget method2(BuildContext context) {
    context.inheritFromWidgetOfExactType(Object); // whatever
    return Container();
  }
}
```

In a `StatefulWidget` it is also possible without passing the context around, because the context variable is accessable everywhere in the state. It's nice however why isn't it also possible in a `StatelessWidget`?

```
class ContextPassingAroundNotNeeded extends StatefulWidget {
  @override
  _ContextPassingAroundNotNeededState createState() => _ContextPassingAroundNotNeededState();
}

class _ContextPassingAroundNotNeededState extends State<ContextPassingAroundNotNeeded> {
  @override
  Widget build(BuildContext context) => method1();

  Widget method1() {
    context.inheritFromWidgetOfExactType(Type); // whatever

    return method2();
  }

  Widget method2() {
    context.inheritFromWidgetOfExactType(Object); // whatever
    return Container();
  }
}
```

**Comment by zoechi** [comment]
A stateless image is immutable, therefore no way to store the context anywhere when it becomes available.

**Comment by ForzaMark** [comment]
I guess you would point out a stateless widget is immutable instead of an stateless image
