### ISSUE TITLE
Facing issue while trying to connect spring websockets from flutter to receive broadcasted messages

### ISSUE THREAD

**Issue by srivanigorthi** [flutter/flutter#23406]
I have tried following the code snippet provided in flutter.io cookbook(https://flutter.io/cookbook/networking/web-sockets/)  to connect to websockets.

 It was working well for the test server "echo.websocket.org" provided in the code but same is not getting connected when trying with custom websocket server written in Spring. I have tried with multiple websockets which are working in other projects, even sample test websocket is also not getting connected.

Please help to resolve the issue or suggest steps to take to achieve successful connectivity to websockets.

I really appreciate any help you can provide.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

I'd first try with plain Dart to see if it is related to Flutter.
If it is try on a real device and emulator to check if it reproduces on both.
Check if there is any log output on the server.
With more concrete information this is a good question for StackOverflow.

**Comment by srivanigorthi** [comment]
There was no error observed. As per my websocket once connection is made, we need to subscribe to the URL pattern to listen/ receive the messages broadcasted by the WS server.

**Comment by srivanigorthi** [comment]
Its still not connect to websockets,  can someone help me

**Comment by iamgrf** [comment]
> Its still not connect to websockets, can someone help me
I have the same problem, have you solved it?
