### ISSUE TITLE
Graddle issue with test application

### ISSUE THREAD

**Issue by Parag2385** [flutter/flutter#23403]
## Steps to Reproduce

1. Install Flutter
2. Run the default app in Android Studio

## Logs

     Launching lib\main.dart on Pixel 2 XL in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: E:\Flutter Apps\hello_rectangle\flutter_app\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Flutter Apps\hello_rectangle\flutter_app\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Finished with error: Please review your Gradle project setup in the android/ folder.

```
```

```
```

**Comment by denzilferreira** [comment]
Same issue here, seems that lint-gradle-api 26.1.2 is gone from jcenter...

**Comment by alichur** [comment]
Looks like there is a fix happening here https://github.com/flutter/flutter/pull/23397

**Comment by zoechi** [comment]
Merging with 23404
