### ISSUE TITLE
Firebase Admob weird ad all of a sudden

### ISSUE THREAD

**Issue by Daibaku0615** [flutter/flutter#23408]
I've been testing Firebase Admob about two weeks. I haven't set any ad units or something. So, basically I had received test ad like "This is an interstitial test ad".  But since a couple of minutes ago, I sometimes receive video ad like youtube. You can pass after 5 seconds and it's always Turkish VISA.
Anyone know what's going on?  Am I being hacked or something?

**Comment by zoechi** [comment]
Sounds like a good question for StackOverflow. Perhaps with some more details.
