### ISSUE TITLE
How Do I render an image from the image data source

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#23418]
How Do I render an image from the image data source like the attached file here's a snippet of the data source

[img.txt](https://github.com/flutter/flutter/files/2507419/img.txt)

**Comment by zoechi** [comment]
I'd suggest you improve the question https://stackoverflow.com/questions/52955400/how-do-i-render-an-image-from-the-image-data-source-in-flutter
and you'll likely get a good answer.
