### ISSUE TITLE
confusion between the run button and the resume button

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2341]
They use similar icons, and the run icon looks like the resume icon from other debuggers. Users can hit the Run button - re-starting their app from scratch - when they mean to resume from a breakpoint.

We could fix this by changing the icon when an app is running (to a re-start icon), or by disabling the run button when an app is running. Disabling or changing the icon would mean that we could only support running one app at once.

**Comment by jimbeveridge** [comment]
I've always expected the "Play" button to be both Go/Resume, depending on state. If I want to restart, I click Stop, then Start, or I use the speed key.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
