### ISSUE TITLE
Video size or length limit

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#23414]
Would it be possible to add a time or size limit to the camera video plugin or the image picker video plugin? This is available in IOS.

**Comment by spagni** [comment]
Yes! That would be really useful! For now is there any way to calculate the size of the file being recorded and stop when it reaches certain size?

**Comment by jonataslaw** [comment]
I can implement this if someone helps me to do the tests with iOS.
I already made the code in objc and java, but my Macbook pro broke yesterday, and I can't do the tests on iOS. If anyone is interested, I can put the code here, or open a PR.
If someone is interested in doing this on their own, it is very simple.

Android side:
 Intent intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
 intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 10);
 boolean canTakePhotos = intentResolver.resolveActivity(intent);

IOS side:
[_imagePickerController setVideoMaximumDuration:10.0f];

Inserting this would limit the video recording to 10 seconds. It would be possible to pass this value through MethodChannel very easily.

**Comment by MuhammadAmin94** [comment]
> I can implement this if someone helps me to do the tests with iOS.
> I already made the code in objc and java, but my Macbook pro broke yesterday, and I can't do the tests on iOS. If anyone is interested, I can put the code here, or open a PR.
> If someone is interested in doing this on their own, it is very simple.
> 
> Android side:
> Intent intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
> intent.putExtra(MediaStore.EXTRA_DURATION_LIMIT, 10);
> boolean canTakePhotos = intentResolver.resolveActivity(intent);
> 
> IOS side:
> [_imagePickerController setVideoMaximumDuration:10.0f];
> 
> Inserting this would limit the video recording to 10 seconds. It would be possible to pass this value through MethodChannel very easily.

where exactly i have to insert this code ?

**Comment by rlee1990** [comment]
@jonataslaw Where would we put this?

**Comment by kadnan0900** [comment]
Any update about this feature in image_picker ?

**Comment by kiaxseventh** [comment]
how can i do it ?
how can use  camera_platform_interface ?!
can you share a simple code use from camera_platform_interface ?

thank you lot of
