### ISSUE TITLE
firebase_auth plugin does not send silent push notifications to iOS devices for phone authentication.  Always uses reCAPTCHA.

### ISSUE THREAD

**Issue by sbefort** [flutter/flutter#23429]
Phone authentication should send a silent push notification to the user whether or not the user has given permission for push notifications.  In reality, the user is prompted with reCAPTCHA every single time, even when on an actual iOS device.

I know my APN keys are setup correctly because when I grant permission for push notifications, all my push notifications from Firebase cloud messaging work fine.  The silent push notifications do not work to prevent reCAPTCHA if the user has not granted push notifications permission.  That is not how it's supposed to work [according to the docs](https://firebase.google.com/docs/auth/ios/phone-auth#start-receiving-silent-notifications).  Users should get silent push notifications regardless of their permissions.

```dart
final FirebaseAuth _auth = FirebaseAuth.instance;

await _auth.verifyPhoneNumber(
        phoneNumber: testPhoneNumber,
        timeout: const Duration(seconds: 5),
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout
);
```

After the above code is run on a physical iOS device, the user is sent to a reCAPTCHA verification.

But if later the user grants permission for push notifications, the user is never asked for reCAPTCHA verification.  Silent push notifications are not working as outlined in the docs:

https://firebase.google.com/docs/auth/ios/phone-auth#start-receiving-silent-notifications

**Comment by AlexandreRoba** [comment]
Any update on this?

**Comment by kroikie** [comment]
@sbefort

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/601. Any further collaboration will be done there.
