### ISSUE TITLE
Cannot move selection start handle when handle moved to beginning of text in Flutter Gallery

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#23432]
The left/top/first selection handle for adjusting highlighted edit text gets stuck at the beginning of the paragraph.

Repro:

- Navigate to Material > Text Fields > Life story
- Type text (preferably multiple lines)
- Long press to select text. Move the first handle to the beginning of your paragraph.
- The handle is now stuck there and you must cancel your selection and re-select to move it

I suspect it may not be general but rather caused by the textbox covering the selectable part of the handle when it gets too close to the edge, but have not tested this.

**Comment by goderbauer** [comment]
This still reproduces on Android and iOS.

**Comment by justinmc** [comment]
This was fixed in https://github.com/flutter/flutter/pull/31852 but I forgot to close this.  It's possible for the handle to go off of the screen, but as long as they're visible, it should be easy to interact with either handle now.
