### ISSUE TITLE
Unify flutter.yaml and pubspec.yaml by adding a 'flutter' section to pubspec.yaml for Flutter projects

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2343]
Is there any reason we couldn't have a flutter section in the pubspec.yaml file that contained what is now in flutter.yaml?

**Comment by abarth** [comment]
Sure, we could do that.

**Comment by sethladd** [comment]
I talked to the pub folks, and we can add new keys to pubspec.yaml and it won't blow up the world.

cc @munificent

**Comment by abarth** [comment]
Should we group our keys under a specific heading, like `flutter` ?  That way we won't conflict with future pubspec keys.

**Comment by Hixie** [comment]
Yeah, that was my thought too. Makes it clearer what's flutter-specific for people coming from the Dart world or otherwise interacting with the Dart world, too.

**Comment by munificent** [comment]
> Should we group our keys under a specific heading, like flutter ?

Yes please. Aside from that, you're more than welcome to put your stuff in the pubspec.yaml if it avoids cluttering the user's root directory with extra files. We picked YAML in part because it is open-ended and extensible, and pub's own pubspec parser is designed to ignore extra keys it doesn't care about.

**Comment by Hixie** [comment]
@danrubel This is the bug I was talking about.

**Comment by pq** [comment]
@danrubel: are you still looking at this?

**Comment by danrubel** [comment]
Nope. Not currently on my list anymore.

**Comment by pq** [comment]
Thanks!  FYI @mit-mit.
