### ISSUE TITLE
/packages/flutter_tools/lib/src/fuchsia/fuchsia_sdk.dart after show flutter doctor for win7e

### ISSUE THREAD

**Issue by lyb5215659** [flutter/flutter#23447]
file:///D:/Codes/flutter/packages/flutter_tools/lib/src/fuchsia/fuchsia_sdk.dart:48:22: Error: A value of type 'dart.core::String' can't be assigned to a variable of type 'dart.async::FutureOr<invalid-type>'.
Try changing the type of the left hand side, or casting the right hand side to 'dart.async::FutureOr<invalid-type>'.
      return process.stdout;

**Comment by jonahwilliams** [comment]
@lyb5215659 What version of Flutter are you getting this error on? Could you post the entire stack trace?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
