### ISSUE TITLE
Hot reload/hot restart not working

### ISSUE THREAD

**Issue by bang88** [flutter/flutter#23442]
## Steps to Reproduce

1. flutter create my_new_app
2. flutter run
3. 

## Logs

logs:
[new-log.txt](https://github.com/flutter/flutter/files/2508610/new-log.txt)

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.2-pre.21, on Mac OS X 10.14 18A389, locale
    en-CN)
    • Flutter version 0.10.2-pre.21 at /Users/bang/development/flutter
    • Framework revision 7aeb539da9 (3 days ago), 2018-10-21 05:47:10 +0200
    • Engine revision 58cdd53f90
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/bang/Library/Android/Sdk
    • Android NDK at /Users/bang/Library/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/bang/Library/Android/Sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (3 available)
    • Samsung Galaxy S6, 5 0 0, API 21, 1440x2560 • 192.168.58.101:5555
      • android-x86 • Android 5.0 (API 21)
    • bang                                        •
      xxxx • ios         • iOS 12.1
    • iPhone X                                    •
      57906EE0-7FEB-487A-8698-85E91AF8B004     • ios         • iOS 12.0
      (simulator)

• No issues found!

```

**Comment by zoechi** [comment]
What device did you run it with?
Is this with Android or iOS or both?

**Comment by bang88** [comment]
Both of them.

**Comment by bang88** [comment]
![log](https://user-images.githubusercontent.com/433259/47422660-bc1efd00-d7b5-11e8-89e9-887a600dfb69.gif)

**Comment by zoechi** [comment]
What about master or dev channel?

**Comment by bang88** [comment]
Both of them are not working

**Comment by aam** [comment]
Can you see if you get same problem when launching on phyiscal ios device, Android simulator or phyiscal device?

In other words, whether this is limited to ios sim.

**Comment by bang88** [comment]
@aam No. both IOS and Android simulator have the same problem.

The phyiscal IOS device have the same problem

![image](https://user-images.githubusercontent.com/433259/47489003-25ffdb00-d878-11e8-92d4-02e18d26acf8.png)

**Comment by jeffreyyoung** [comment]
I too am seeing this

**Comment by aam** [comment]
@jeffreyyoung can you do `flutter run -v` from command line, capture the output into a https://gist.github.com/ and link to the gist from here, please?

**Comment by aam** [comment]
thank you for the follow up @jeffreyyoung .

**Comment by yuyedaidao** [comment]
I have this issue, any branch can not work. I am dying

**Comment by zoechi** [comment]
@yuyedaidao what Flutter channel?

@bang88 are you still seeing this on `master` branch?

**Comment by bang88** [comment]
@zoechi No. Its not work after switch to master branch.

**Comment by yuyedaidao** [comment]
@zoechi  master beta  dev, both of them not work.

**Comment by yuyedaidao** [comment]
@zoechi I got it. I seted proxy for terminal, now I remove it, it`s ok

**Comment by bang88** [comment]
Remove  `https_proxy` and `http_proxy` fix this problem.

**Comment by bang88** [comment]
But can we fixes this using another way. because we need proxy setup sometimes.

**Comment by zoechi** [comment]
@bang88 perhaps https://github.com/flutter/flutter/issues/16875#issuecomment-384758566

**Comment by bang88** [comment]
Thanks.

**Comment by lkhgvsuren** [comment]
> Remove `https_proxy` and `http_proxy` fix this problem.

What does it mean?

**Comment by zoechi** [comment]
@lkhgvsuren they are environment variables to configure a proxy
https://www.dartlang.org/tools/pub/troubleshoot

**Comment by ahmedmirza994** [comment]
@zoechi  how to remove https_proxy and http_proxy?

**Comment by zoechi** [comment]
@ahmedmirza994 They are environment variables. It depends on your OS how to do that.

**Comment by alex9153** [comment]
Hi.
I have the same problem.
How to remove https_proxy and http_proxy?

**Comment by ollydixon** [comment]
I don't have 'https_proxy' or 'http_proxy' setup as environmental variables. Still seeing this issue.
As a side note setting up `export https_proxy=hostname:port` (127.0.0.1:3000) also does't work.

https://www.dartlang.org/tools/pub/troubleshoot

**Comment by jayanthsaikiran** [comment]
> 
> 
> I don't have 'https_proxy' or 'http_proxy' setup as environmental variables. Still seeing this issue.
> As a side note setting up `export https_proxy=hostname:port` (127.0.0.1:3000) also does't work.
> 
> https://www.dartlang.org/tools/pub/troubleshoot

I am facing the same issue. I am developing on Windows platform with a physical Android device.

**Comment by haohaozaici** [comment]
i added `no_proxy=127.0.0.1,localhost` and fixed problem
```bash
export http_proxy=http://127.0.0.1:your port
export https_proxy=http://127.0.0.1:your port
export no_proxy=127.0.0.1,localhost
```

**Comment by tudor07** [comment]
Not working.

```
http_proxy=http://127.0.0.1:1032;https_proxy=http://127.0.0.1:1032;no_proxy=127.0.0.1,localhost flutter run --observatory-port 1032
```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1032/R53dZ7jI-P0=/

```
http_proxy=http://127.0.0.1:1032;https_proxy=http://127.0.0.1:1032; flutter run --observatory-port 1032
```
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1032/JUBdHEwuWmw=/

**Comment by deeprodge** [comment]
> i added `no_proxy=127.0.0.1,localhost` and fixed problem
> 
> ```shell
> export http_proxy=http://127.0.0.1:your port
> export https_proxy=http://127.0.0.1:your port
> export no_proxy=127.0.0.1,localhost
> ```

how to find port?
