### ISSUE TITLE
Problems compiling Flutter Project Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).

### ISSUE THREAD

**Issue by pekretsc** [flutter/flutter#23459]
Hi, I am new to flutter and was working with it fine until an upgrade yesterday.
Now I can not compile anymore because Flutter has probplems using Gradle. I do not get the problem :/ can anybody please give me a clue??

Error Message:
* Error running Gradle:
ProcessException: Process "C:\Users\peter\AndroidStudioProjects\flutter_app\android\gradlew.bat" exited abnormally:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\peter\AndroidStudioProjects\flutter_app\android\app\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: C:\Users\peter\AndroidStudioProjects\flutter_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

## Steps to Reproduce

1. Update --> Fail
2. Reinstalling and creating a new Flutter project allways throws the same error
3. ...

## Logs
[idea.log](https://github.com/flutter/flutter/files/2510114/idea.log)

```
```

C:\Users\peter\AndroidStudioProjects\flutter_app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.10.0, on Microsoft Windows [Version 10.0.17134.345], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.2)
[√] VS Code, 64-bit edition (version 1.25.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```
```

**Comment by zoechi** [comment]
Merging with #23404

**Comment by djh2717** [comment]
I get this probplem too, how to fix it

**Comment by yash365** [comment]
Go to path where Flutter SDK is installed my Flutter SDK path                                                                   i.e : C:\Flutter SDK\flutter\packages\flutter_tools\gradle  
1. Edit the flutter.gradle file by moving                 
 maven {
    url 'https://dl.google.com/dl/android/maven2'
} 
in the top of jcenter()

2. i.e. flutter.gradle file buildscript section will look like this
buildscript {
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }

OR follow this link :
https://stackoverflow.com/questions/52945041/couldnt-locate-lint-gradle-api-26-1-2-jar-for-flutter-project

**Comment by kimbummen** [comment]
Or you can upgrade gradle in android with below steps: 
1. Edit android/gradle/wrapper/gradle-wrapper.properties and upgrade: 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
2. Edit android/build.gradle:
classpath 'com.android.tools.build:gradle:3.1.2'
![image](https://user-images.githubusercontent.com/13693453/47983007-6d9e2680-e104-11e8-8e03-213c73db71b1.png)

**Comment by pratikjain04** [comment]
> * distributionUrl=https://services.gradle.org/distributions/gradle-4.4-all.zip

You saved my day. Thanks a lot!

**Comment by mtellect** [comment]
this good also save someone else's day:
distributionUrl=https://services.gradle.org/distributions/gradle-4.6-all.zip
