### ISSUE TITLE
buildToolsVersion is not specified

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#23451]
Overnight, all our flutter product Android CI builds started failing with:

```
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:558)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
<<snip>>
```

This includes builds that worked just yesterday. I've checked and Bitrise (our CI) have not released anything. I've tried everything I can think of:

1. Using latest `beta` channel (ours was a couple of weeks old)
2. Using latest `dev` and `master` channels (fails for other reasons and I gave up on pursuing it because it shouldn't matter)
3. Changing my `compileSdkVersion` to `28` (was `25`) and `buildToolsVersion` to `28.0.3` (was `25.0.3`)

Nothing has worked.

## Steps to Reproduce

1. Build one day works fine.
2. Go home and have dinner, enjoy some time with the family.
3. Build exactly the same commit and now it fails.

## Logs

Command being executed:
```
flutter build apk
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✗] Android Studio (not installed)
[!] Connected devices
    ! No devices available
```

**Comment by ened** [comment]
> Using latest beta channel (ours was a couple of weeks old)

How did you switch? Did you `flutter clean` in between and remove any other cache files?

Please show the build.gradle files, especially the section on the gradle plugin version.

**Comment by zoechi** [comment]
> Using latest beta channel

> [✓] Flutter (Channel beta, v0.8.2,

0.9.4 is latest beta.

**Comment by kentcb** [comment]
@zoechi could you please tell me what it means to be in the "Goals" milestone? I've got a couple of issues there now, one of which has been there for a month. Given that this is a complete blocker, that worries me...

**Comment by zoechi** [comment]
@kentcb I only do some generic triage. I don't know about following priorization.

Can you reproduce with a new Flutter project?

**Comment by kentcb** [comment]
@zoechi I tried re-creating the project using beta, dev, and master channels. In all cases, the error has changed to:
```
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/vagrant/git/Src2/android/app/build.gradle' line: 25
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
```
Judging by the recent issues, other people are experiencing this too 🚨

**Comment by kentcb** [comment]
I noticed it's in the google repository [here](https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar) but I'm yet to dig into how to add this repository to maven.

**Comment by kentcb** [comment]
Ugh, seems like it's already added...?
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
I have no idea how `google()` translates into an actual URL to use, but it's clear that it's not even looking at the google repository from the error message.

**Comment by ened** [comment]
@kentcb please take a look here: https://github.com/flutter/flutter/pull/23397#issuecomment-432221044
