### ISSUE TITLE
Flutter plugin quick_actions crashes the app when running for the first time

### ISSUE THREAD

**Issue by emadomedher** [flutter/flutter#23450]
quick_actions plugin crashes the app on both iOS and Android. From the example there are 2 parts, adding the actions and capturing them:

Adding actions:
```dart
quickActions.setShortcutItems(<ShortcutItem>[
  new quickActions.ShortcutItem(type: 'action_main', localizedTitle: 'Main view', icon: 'icon_main'),
  new quickActions.ShortcutItem(type: 'action_help', localizedTitle: 'Help', icon: 'icon_help')
]);
```

Capturing the action:
```
quickActions.initialize((shortcutType) {
  if (shortcutType == 'action_main') {
    print('The user tapped on the "Main view" action.');
  }
  // More handling code...
});
```

If you application was running in the background already, quick_actions works just fine. If it was completely closed then starting the application from quick_actions crashes it. I have tried omitting the capturing part and just keep the creating part but still, it crashes.

regards,

**Comment by zoechi** [comment]
> quick_actions crashes it

any more details about that, like console output?

Please add the output of `flutter doctor -v`.

**Comment by emadomedher** [comment]
> > quick_actions crashes it
> 
> any more details about that, like console output?
> 
> Please add the output of `flutter doctor -v`.

I cannot produce it from flutter doctor as I must close the application in order to produce this, I will try via ADB and submit the logs

**Comment by emadomedher** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-SA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.28.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Alis-MacBook-Pro:labbiek emad$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-SA)
    • Flutter version 0.9.4 at /Users/emad/Documents/dev/flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/emad/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.28.1)
    • VS Code at /Users/emad/Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • SM G955F • ce051715b02dbc0501 • android-arm64 • Android 8.0.0 (API 26)

**Comment by zoechi** [comment]
Are you still seeing this with recent Flutter versions?
Can you please provide more details about

> crashes the app

Any console output?

**Comment by BearLesnick** [comment]
As i understood from code sources for Android, this behaviour is normal, because quick action only starts the actvity that will try to execute dart code using  channel.invokeMethod("launch", type);
Full code of this activity is:

 public static class ShortcutHandlerActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      // Get the Intent that started this activity and extract the string
      Intent intent = getIntent();
      String type = intent.getStringExtra("type");
      if (channel != null) {
        channel.invokeMethod("launch", type);
      }
      finish();
    }
  }

As i understood, the reason of this bug is that we only start this activity by quick action, and after it invoked method, activity is destroyed. But, to start our application we need to start our MainActivity that extends FlutterActivity.

**Comment by AndroidNils** [comment]
@BearLesnick I have the same problem. What do I have to do exactly?

**Comment by LesnickBear** [comment]
@AndroidNils, you should check if flutter activity in stack, if not, you should start it, and only after , send channel message.
