### ISSUE TITLE
Firebase In-App Messaging plugin

### ISSUE THREAD

**Issue by maxhelskens** [flutter/flutter#23463]
Hi,

Are there any plans to create a [Firebase In-App Messaging](https://firebase.google.com/products/in-app-messaging/) flutter plugin?

Could come in handy!

**Comment by zoechi** [comment]
Closing as duplicate of #24933

Please thumbs-up and subscribe there.

**Comment by kroikie** [comment]
@maxhelskens

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/598. Any further collaboration will be done there.
