### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code while trying to add Flutter to iOS app

### ISSUE THREAD

**Issue by anuranBarman** [flutter/flutter#23465]
I am trying to add flutter to existing app. So before doing on the production app I tried with brand new Xcode 10 Single View Application. I followed the tutorial here in https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps and got stuck after adding the run script in the build phase of my target. Its giving the error 
```
/Users/anuranbarman/Library/Developer/Xcode/DerivedData/FlutterApp-efmnjbfjqskykrgiqqksaqaeglti/Build/Intermediates.noindex/FlutterApp.build/Debug-iphonesimulator/FlutterApp.build/Script-354DA2FA2180BBA5007C8FEC.sh: line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
/Users/anuranbarman/Library/Developer/Xcode/DerivedData/FlutterApp-efmnjbfjqskykrgiqqksaqaeglti/Build/Intermediates.noindex/FlutterApp.build/Debug-iphonesimulator/FlutterApp.build/Script-354DA2FA2180BBA5007C8FEC.sh: line 4: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
I have created many fully flutter applications previously and successfully ran all of those in both android and iphones. But while adding it to existing code it's giving the error in the same **XCode Version 10.0 (10A255)**

This is how my podfile looks
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  flutter_application_path = '/Users/anuranbarman/Documents/iOS practice/FlutterApp/eglu_discover/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
  # Pods for FlutterApp

end
```

**Comment by anuranBarman** [comment]
Okay it seems $FLUTTER_ROOT was not set for me. but after setting it up another issue for linker error stating 
```
ld: warning: directory not found for option '-F/Users/anuranbarman/Library/Developer/Xcode/DerivedData/FlutterApp-efmnjbfjqskykrgiqqksaqaeglti/Build/Products/Debug-iphoneos/FlutterPluginRegistrant'
ld: framework not found FlutterPluginRegistrant
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
is coming

**Comment by jayjwarrick** [comment]
@anuranBarman Any luck? I'm having the same issue.

**Comment by BasanthVerma** [comment]
📌 Same issue.

- Android integration worked fine for me.
- I followed the wiki and I added the 2 lines in the Podfile with the flutter path. Then I ran pod install, here's the pod install output:

```
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `real_path' for nil:NilClass

/Users/basanthverma/ProjectName/Podfile:73:in `block (4 levels) in from_ruby'
/Users/basanthverma/ProjectName/Podfile:71:in `each'
/Users/basanthverma/ProjectName/Podfile:71:in `block (3 levels) in from_ruby'
/Users/basanthverma/ProjectName/Podfile:70:in `each'
/Users/basanthverma/ProjectName/Podfile:70:in `block (2 levels) in from_ruby'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:647:in `run_podfile_post_install_hook'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:635:in `block in run_podfile_post_install_hooks'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:634:in `run_podfile_post_install_hooks'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:186:in `block in generate_pods_project'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/basanthverma/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/basanthverma/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/basanthverma/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/basanthverma/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/basanthverma/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by anuranBarman** [comment]
> @anuranBarman Any luck? I'm having the same issue.

No. At first that was problem with the plugin. Then created my own plugin. same issue. no luck

**Comment by anuranBarman** [comment]
I dont know how did it do but this issue got resolved like magic without me trying anything. I started from scratch with fresh ios app and flutter module. That time it did not show this error. I will suggest create the flutter module again and copy the required files into the new project. Now I am able to integrate the flutter app but now another issue is coming for which I opened another issue some days back but that's not working till date. the issue is here [#23832](https://github.com/flutter/flutter/issues/23832)

**Comment by cocoayang** [comment]
The same compiling error occurred for me, so I added a user-defined variable named FLUTTER_ROOT. After that, this issue disappeared. But i had set the environment variable in the .bash_profile file as followed:
export FLUTTER_ROOT=~/development/flutter1.0
Can't Xcode read this? why it doesn't work?
What's worse, Although this error disappeared while another one was coming. Xcode tells me:
<img width="815" alt="11" src="https://user-images.githubusercontent.com/22711007/50549998-80ffe500-0ca2-11e9-9dec-f8395258c0df.png">
in the xcode_backend.sh file, there are some codes like:
```
BuildApp() {
  local project_path="${SOURCE_ROOT}/.."
  if [[ -n "$FLUTTER_APPLICATION_PATH" ]]; then
    project_path="${FLUTTER_APPLICATION_PATH}"
  fi

  local target_path="lib/main.dart"
  if [[ -n "$FLUTTER_TARGET" ]]; then
    target_path="${FLUTTER_TARGET}"
  fi

```
In fact the FLUTTER_ROOT and some other variable are set in the Generated.xcconfig file created by Flutter automatically like this:
```
FLUTTER_ROOT=/Users/yangbaocheng/development/flutter1.0
FLUTTER_APPLICATION_PATH=/work/client/bd/tb-ios/tb_flutter_module
FLUTTER_TARGET=lib/main.dart
FLUTTER_BUILD_DIR=build
SYMROOT=${SOURCE_ROOT}/../build/ios
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1

```
**But why Xcode can't recognize FLUTTER_ROOT? why can't xcode_backend.sh find lib/main.dart in the FLUTTER_APPLICATION_PATH?
Help me please! Than you a lot!**

**Comment by dangercheng** [comment]
The same compiling error occurred for me. 
But i solved it by switching channel to master.
>Flutter channel master

Then delete the old module and recreate it by 
>flutter create -t module my_flutter

Next 
>pod install

Finally, clean the xcode project, restart Xcode,  Cmd+B the error disappeared.

**Comment by fatihbalsoy** [comment]
Can confirm, switching flutter channel to master fixes issues with macOS Desktop Embedding. Never tried it for iOS development, but the master branch should fix the issue.

**Comment by zoechi** [comment]
@anuranBarman can you confirm?

**Comment by fatihbalsoy** [comment]
I tried recreating the issue by following the same guide for iOS apps, but it seems like the nonzero exit code doesn't occur on the stable channel for the time being. I even tried to add Flutter to new and existing iOS projects just to make sure. Nonetheless, I cannot be sure if it still persists on @anuranBarman 's project.

**Comment by poos** [comment]
I have a common problem.

1. The simulator is normal, but the real machine will have errors


`
Command PhaseScriptExecution failed with a nonzero exit code`



2. I commented out the embed element in Run Scriot in Xcode


```

"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
#"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

```


There is another error in the console when the machine is running:

```

2019-05-15 19:34:43.038873+0800 zhima[1354:88077] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2019-05-15 19:34:43.253524+0800 zhima[1354:88324] [VERBOSE-2:engine.cc(117)] Engine run configuration was invalid.
2019-05-15 19:34:43.253795+0800 zhima[1354:88324] [VERBOSE-2:FlutterEngine.mm(304)] Could not launch engine with configuration.
2019-05-15 19:34:43.426946+0800 zhima[1354:88331] flutter: Observatory listening on http://127.0.0.1:59545/xJdO9DgNi04=/

```

**Comment by poos** [comment]
```
[✓] Flutter (Channel master, v1.5.9-pre.202, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
    • Flutter version 1.5.9-pre.202 at /Applications/flutter
    • Framework revision 10922df68e (5 days ago), 2019-05-09 23:18:56 -0700
    • Engine revision d8646ed07c
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bieshixuan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • Cle 的 iPhone 6 • e6a545a6a7490d06e3f5eb32e6f3a6d843ac2d08 • ios • iOS 11.2.1
    • iPhone Xʀ      • C4EE1CAD-51A1-4F83-899F-338173968A16     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)


```

**Comment by poos** [comment]
I follow this tutorial, and when I create a new one, the problem persists.

[flutter/wiki/Add-Flutter-to-existing-apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps)

**Comment by WedgeSparda** [comment]
Followed the same steps. 
Tried changing to the master branch but the error is still there.
Any luck finding a solution?

**Comment by vilashraj** [comment]
> > The same compiling error occurred for me.
> > But i solved it by switching channel to master.
> > > Flutter channel master
> > 
> > 
> > Then delete the old module and recreate it by
> > > flutter create -t module my_flutter
> > 
> > 
> > Next
> > > pod install
> > 
> > 
> > Finally, clean the xcode project, restart Xcode, Cmd+B the error disappeared.
> 
> Hi All,
> 
> I tried this but still facing the same issue that @cocoayang has described above.
> 
> **Error:**
> 
> ```
> iphoneos/AFEiOS.build
>     export TEMP_ROOT=/Users/dhavalkansara/Library/Developer/Xcode/DerivedData/AFEiOS-gctxucyuhlhesnfkbuxfswkozboo/Build/Intermediates.noindex
>     export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
>     export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
>     export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
>     export TeamIdentifierPrefix=RQ9BPQCP49.
>     export UID=501
>     export UNLOCALIZED_RESOURCES_FOLDER_PATH=AFEiOS.app
>     export UNSTRIPPED_PRODUCT=NO
>     export USER=dhavalkansara
>     export USER_APPS_DIR=/Users/dhavalkansara/Applications
>     export USER_LIBRARY_DIR=/Users/dhavalkansara/Library
>     export USE_DYNAMIC_NO_PIC=YES
>     export USE_HEADERMAP=YES
>     export USE_HEADER_SYMLINKS=NO
>     export VALIDATE_PRODUCT=NO
>     export VALID_ARCHS="arm64 arm64e armv7 armv7s"
>     export VERBOSE_PBXCP=NO
>     export VERSIONPLIST_PATH=AFEiOS.app/version.plist
>     export VERSION_INFO_BUILDER=dhavalkansara
>     export VERSION_INFO_FILE=AFEiOS_vers.c
>     export VERSION_INFO_STRING=""@(#)PROGRAM:AFEiOS  PROJECT:AFEiOS-""
>     export WRAPPER_EXTENSION=app
>     export WRAPPER_NAME=AFEiOS.app
>     export WRAPPER_SUFFIX=.app
>     export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
>     export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
>     export XCODE_PRODUCT_BUILD_VERSION=10E1001
>     export XCODE_VERSION_ACTUAL=1020
>     export XCODE_VERSION_MAJOR=1000
>     export XCODE_VERSION_MINOR=1020
>     export XPCSERVICES_FOLDER_PATH=AFEiOS.app/XPCServices
>     export YACC=yacc
>     export arch=undefined_arch
>     export variant=normal
>     /bin/sh -c /Users/dhavalkansara/Library/Developer/Xcode/DerivedData/AFEiOS-gctxucyuhlhesnfkbuxfswkozboo/Build/Intermediates.noindex/AFEiOS.build/Debug-iphoneos/AFEiOS.build/Script-19DAA30A22C0FB0100A039E2.sh
> 
> The path lib/main.dart does not exist
> The path  does not exist
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> **My pod file:**
> 
> ```
> # Uncomment the next line to define a global platform for your project
> platform :ios, '10.0'
> 
> target 'AFEiOS' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for AFEiOS
> 
>   target 'AFEiOSTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
>   target 'AFEiOSUITests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
>     flutter_application_path = '/Users/dhavalkansara/FlutterToNative/AFE_flutter/'
>     eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
> 
> 
> end
> ```
> 
> * Already added **FLUTTER_ROOT** in my project.
> 
> Please help me out with this issue.

@anuranBarman @cocoayang and @zoechi  I also faced the same issue while I am trying to migrate my existing iOS app into a flutter.
please help me out with the above issue.

**Comment by hahazheng** [comment]
I also encountered the same problem. Please help me when I introduce Flutter.
-------->
The path lib/main.dart does not exist
The path  does not exist
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by hahazheng** [comment]
@vilashraj This problem has been solved. Can you help me? thankyou

**Comment by scut204** [comment]
Select "Run script only when installing" in Xcode Build Phase script.
Encountered and solved.
Tutorial update demanding.

**Comment by oneofai** [comment]
> Select "Run script only when installing" in Xcode Build Phase script.
> Encountered and solved.
> Tutorial update demanding.

**This is a correct solution!**
and **YES** It is not mentioned in the tutorial, it is strongly recommended that the tutorial update this point.

**Comment by fahjan** [comment]
Remove Pods folder and run:
`pod install`

**Comment by jmagman** [comment]
> Select "Run script only when installing" in Xcode Build Phase script.

Please don't do this--running only when installing means your dart code won't get compiled when you run, only when you archive your app.  I'm going to hide all suggestions to do this, I'm seeing references to this advice causing other bugs.

```
/packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
```
means your FLUTTER_ROOT isn't set up correctly.  Please see https://github.com/flutter/flutter/issues/56507#issuecomment-631773721.

Locking this issue.
