### ISSUE TITLE
Why don't all of the ADV devices work except Pixel XL device in android studio emulator?

### ISSUE THREAD

**Issue by farhadibehnam** [flutter/flutter#23477]
I'm new in flutter framework, and of course, in android programming. What I've tried to ran some devices use ADV in the android studio but unfortunately when I run most of them are stuck except Pixel XL device. I don't know why Pixel XL worked, but for example Pixel 2 XL doesn't work and it isn't just about Pixel 2 XL I have the same problem with nexus 6.and I also check this questions, but it didn't work for me.
[AVD Emulator stuck on the loading screen in Android Studio](https://stackoverflow.com/questions/36753354/avd-emulator-stuck-on-loading-screen-in-android-studio)

> my Laptop specification: OS : Windows 10 x64 / SSD : 512GB / HDD : 1TB 
> CPU : Core i7-7700HQ 2.80 / Memory : 24GB / Graphic: Geforece GTX 1050

![ymq4n](https://user-images.githubusercontent.com/15254482/47457483-1c2c9800-d7e4-11e8-817e-61c8466dd06e.png)

![pixel](https://user-images.githubusercontent.com/15254482/47457844-0ff50a80-d7e5-11e8-946c-156af5c621a7.PNG)

## Pixel_2_XL vs Pixel XL

> `Name: Pixel_2_XL_API_28
> 
> CPU/ABI: Google APIs Intel Atom (x86_64)
> 
> Path: C:\Users\Behnam.android\avd\Pixel_2_XL_API_28.avd
> 
> Target: google_apis [Google APIs] (API level 28)
> 
> Skin: pixel_2_xl
> 
> SD Card: 512 MB
> 
> fastboot.chosenSnapshotFile:
> 
> runtime.network.speed: full
> 
> hw.accelerometer: yes
> 
> hw.device.name: pixel_2_xl
> 
> hw.lcd.width: 1440
> 
> hw.initialOrientation: Portrait
> 
> image.androidVersion.api: 28
> 
> tag.id: google_apis
> 
> hw.mainKeys: no
> 
> hw.camera.front: emulated
> 
> avd.ini.displayname: Pixel 2 XL API 28
> 
> hw.gpu.mode: host
> 
> hw.ramSize: 1536
> 
> PlayStore.enabled: false
> 
> fastboot.forceColdBoot: no
> 
> hw.cpu.ncore: 4
> 
> hw.keyboard: yes
> 
> hw.sensors.proximity: yes
> 
> hw.dPad: no
> 
> hw.lcd.height: 2880
> 
> vm.heapSize: 384
> 
> skin.dynamic: yes
> 
> hw.device.manufacturer: Google
> 
> hw.gps: yes
> 
> hw.audioInput: yes
> 
> image.sysdir.1: system-images\android-28\google_apis\x86_64\
> 
> showDeviceFrame: yes
> 
> hw.camera.back: virtualscene
> 
> AvdId: Pixel_2_XL_API_28
> 
> hw.lcd.density: 560
> 
> hw.arc: false
> 
> hw.device.hash2: MD5:1a4fa6b2569f0b76bfb9824b6b6fc976
> 
> fastboot.forceChosenSnapshotBoot: no
> 
> fastboot.forceFastBoot: yes
> 
> hw.trackBall: no
> 
> hw.battery: yes
> 
> hw.sdCard: yes
> 
> tag.display: Google APIs
> 
> runtime.network.latency: none
> 
> disk.dataPartition.size: 800M
> 
> hw.sensors.orientation: yes
> 
> avd.ini.encoding: UTF-8
> 
> hw.gpu.enabled: yes

> Name: Pixel_XL_API_28
> 
> CPU/ABI: Google APIs Intel Atom (x86_64)
> 
> Path: C:\Users\Behnam.android\avd\Pixel_XL_API_28.avd
> 
> Target: google_apis [Google APIs] (API level 28)
> 
> Skin: pixel_xl_silver
> 
> SD Card: 512M
> 
> fastboot.chosenSnapshotFile:
> 
> runtime.network.speed: full
> 
> hw.accelerometer: yes
> 
> hw.device.name: pixel_xl
> 
> hw.lcd.width: 1440
> 
> hw.initialOrientation: Portrait
> 
> image.androidVersion.api: 28
> 
> tag.id: google_apis
> 
> hw.mainKeys: no
> 
> hw.camera.front: emulated
> 
> avd.ini.displayname: Pixel XL API 28
> 
> hw.gpu.mode: auto
> 
> hw.ramSize: 1536
> 
> PlayStore.enabled: false
> 
> fastboot.forceColdBoot: no
> 
> hw.cpu.ncore: 4
> 
> hw.keyboard: yes
> 
> hw.sensors.proximity: yes
> 
> hw.dPad: no
> 
> hw.lcd.height: 2560
> 
> vm.heapSize: 384
> 
> skin.dynamic: yes
> 
> hw.device.manufacturer: Google
> 
> hw.gps: yes
> 
> hw.audioInput: yes
> 
> image.sysdir.1: system-images\android-28\google_apis\x86_64\
> 
> showDeviceFrame: yes
> 
> hw.camera.back: virtualscene
> 
> AvdId: Pixel_XL_API_28
> 
> hw.lcd.density: 560
> 
> hw.arc: false
> 
> hw.device.hash2: MD5:984dbf66b1aaafcdb7e89573ffb74b46
> 
> fastboot.forceChosenSnapshotBoot: no
> 
> fastboot.forceFastBoot: yes
> 
> hw.trackBall: no
> 
> hw.battery: yes
> 
> hw.sdCard: yes
> 
> tag.display: Google APIs
> 
> runtime.network.latency: none
> 
> disk.dataPartition.size: 800M
> 
> hw.sensors.orientation: yes
> 
> avd.ini.encoding: UTF-8
> 
> hw.gpu.enabled: yes`
> 

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
    • Flutter version 0.9.4 at C:\src\flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Behnam\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Behnam\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.28.2)
    • VS Code at C:\Users\Behnam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Android Studio, the Android SDK, and the emulator are not maintained by the Flutter team.
You would need to report the issue there instead.
Perhaps https://source.android.com/setup/contribute/report-bugs
