### ISSUE TITLE
provide a way to pass objects between isolates cheaply

### ISSUE THREAD

**Issue by irfantusneem** [flutter/flutter#23473]
Right now the usage of isolate in Flutter is severely handicapped as objects cannot be transferred between isolates.  Although the underlying mobile platforms don't have this restriction.  This prevents work from being offload to isolates that fetch and process large amounts of data that take a couple of hundred milliseconds to process without blocking the app.  This is especially the case in enterprise apps such as some internal apps inside Google.

It would be good if an isolate can pass an object to the main thread when it is exiting.  This will avoid the issue of sharing memory between threads but reduce the cost of serializing and deserializing large amounts of data from an isolate.

**Comment by leafpetersen** [comment]
cc @aam Are you still exploring things in this space for the VM?

**Comment by yjbanov** [comment]
Chatted with @irfantusneem offline. The feature request is about passing objects between isolates _without copying_. I'd phrase the feature request as "provide a way to pass objects between isolates cheaply".

**Comment by yjbanov** [comment]
This is for Flutter apps.

**Comment by zoeyfan** [comment]
@yjbanov I am triaging our bug database, and noticed this issue from 2018. Is this still relevant or actionable? if not, can we close it?

**Comment by irfantusneem** [comment]
Yes it is.

**Comment by fzyzcjy** [comment]
Hi, is there any updates?

**Comment by aam** [comment]
With https://github.com/dart-lang/sdk/issues/46754 landed I think this can be closed.

**Comment by fzyzcjy** [comment]
@aam Thanks! I wonder when will it be launched in flutter?
