### ISSUE TITLE
BUILD FAILED error

### ISSUE THREAD

**Issue by bucc-sanyam** [flutter/flutter#23478]
I just installed the flutter and dart plugins to my android studio and am trying to start working on them. But when I try to run the very first program (example app already available) it gives me the below mentioned error. Same goes for any code I write. Please can anyone help me resolve this?

**Error Message Displayed :**

* Error running Gradle:
Exit code 1 from: C:\Users\Bucc\AndroidStudioProjects\flutter_app\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Bucc\AndroidStudioProjects\flutter_app\android\app\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by MR03web** [comment]
参考https://github.com/flutter/flutter/pull/23397#issuecomment-432221044

**Comment by zoechi** [comment]
Merging with #23397

**Comment by zoechi** [comment]
Merging with #23404
