### ISSUE TITLE
ToolBar has an LTR bias

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2348]
Maybe "label", "buttons", and "primaryButton" or something.

cc @HansMuller

**Comment by appsforartists** [comment]
"buttons" and "primaryButton" is still a bit problematic.  Here's [the relevant section](https://spec.googleplex.com/quantum/layout/structure.html#structure-app-bar) of Spec:

> The nav icon at the left side of the app bar can be:
> 
> - A control to open a navigation drawer.
> - An up arrow for navigating upward through your app’s hierarchy.
> - Omitted entirely if no navigation is required from this screen.

My recommendation is to rename `ToolBar` to `AppBar` and to give it `navButton`, `title`, and `actionButtons` properties in lieu of `left`, `center`, and `right`.  You could even eventually make the `…` overflow menu automatically if there are too many action buttons for a particular viewport, but that's not a blocker.

As for the distinction between a ToolBar and an AppBar, a ToolBar is essentially a bar with buttons on it and an AppBar is a ToolBar that has a nav button, title, and optional action buttons; and lives on the top of the screen.

**Comment by HansMuller** [comment]
Using names that imply the role of the toolbar (appbar) parts sounds good to me (too).  And avoiding names like "left" and "right" is probably a good idea since eventually we're going to want layouts to be sensitive to the writing direction.

**Comment by Hixie** [comment]
The problem with "navButton" is that it's got an abbreviation, which we've been trying to avoid. "navigationButton" might work but is a bit long. "actionButtons" also seems unnecessarily long, maybe just "actions"?

Filed https://github.com/flutter/flutter/issues/2390 for automatically making an overflow menu.

**Comment by abarth** [comment]
`actions` SGTM.  The left could be `primaryAction`

**Comment by appsforartists** [comment]
Back/cancel is unlikely to be the primary action, but that's what that button does.  Therefore, I discourage `primaryAction`.

I suspect as Flutter develops, something like [redux](https://github.com/gaearon/redux) will emerge to manage dataflow, where `action` is a well-understood thing (aka [events or messages](http://www.confluent.io/blog/making-sense-of-stream-processing/) in other contexts).  For that reason, I think `actionButtons` will ultimately be a less confusing name than `actions`.  Autocomplete can handle the extra characters.  :smile: 

Though I generally share your concern with abbreviations, `nav` is a common enough choice that is doesn't bother me (I hear "nav" discussed in design reviews; hell, it's even got its own HTML element).  But if you decide no abbreviations in the core API and `nav` counts as an abbreviation, that's certainly a decision I can respect.

**Comment by Hixie** [comment]
We already use "actions" to refer to things like this in the material library. It seems to be the material design term (for example the intro talks about "user actions"). There's no technical problem with clashes; Dart has good scoping features to avoid this. There could be a conceptual conflict, but I think that's going to happen regardless given how narrow the available vocabulary is. Autocomplete is fine for people who have it; not everyone likes to use an IDE that does.

Also, as the guy who invented the `<nav>` element, I think it counts as an abbreviation. :-)

**Comment by appsforartists** [comment]
Don't worry - nobody forgot that you're the guy who invented `<nav>`.  :wink:

**Comment by appsforartists** [comment]
As to `actions`, this is essentially bikeshedding, but `AppBar`s aren't things that are created often - I don't think typing 7 extra characters once per app is going to hurt anybody.  Then again, if `actions` is the name you've chosen for buttons in the other part of the app, so be it.

(On that note, what about `buttons` as a parameter name?  It's both descriptive and shortish.  Every button presumably triggers an action, so `actionButtons` may be a bit redundant anyway.)

**Comment by abarth** [comment]
The current proposal (in #2536) is `leading`, `title`, and `actions`.
