### ISSUE TITLE
unable to use Firebase re-authenticate method

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#23493]
In order to provide change password option, I'm unable to use Firebase re-authenticate method as in like android(JAVA).
I'm able to get the FirebaseUser Instance of current user, but can't find the reauthenticate method in there.

**Comment by ko2ic** [comment]
I added these methods.

flutter/plugins#907

**Comment by zoechi** [comment]
This has landed. @harshapulikollu can you please check the newest version?

**Comment by kroikie** [comment]
@harshapulikollu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/597. Any further collaboration will be done there.
