### ISSUE TITLE
flutter logs consumes 100% of cpu

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2349]
For a user working with an iOS simulator, there were ~a dozen orphaned processes pegged at 100%. They were all running `flutter logs`. It's not really clear what they could be doing. Mostly ios `logs` tail two ios log files, filter them by regex, and print the result to stdout. Perhaps some catastrophic backtracking in the regex?

**Comment by eseidelGoogle** [comment]
I've not seen this since.  Closing.
