### ISSUE TITLE
Only 24dp material design icons are included

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#235]
<a href="https://github.com/ianloic"><img src="https://avatars.githubusercontent.com/u/604?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ianloic](https://github.com/ianloic)**
_Monday Oct 26, 2015 at 23:02 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1817_

----

When I try to reference a material.Icon with a size of 18, 36 or 48 I get an error like:

    Requested asset 'toggle/drawable-xxhdpi/ic_star_black_18dp.png' does not exist.

even though those are legitimate material icon sizes.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Oct 27, 2015 at 04:04 GMT_

----

I think you can just add these sizes to this line of code:

https://github.com/flutter/tools/blob/master/lib/src/commands/build.dart#L20

We need a better system for determining which assets to include in your FLX.  At a minimum, we could make this configurable in the `flutter.yaml` file.  In the best case, we'd have a way to automatically detect which assets you needed by statically analyzing your code (e.g., by having a constant for each asset and applying tree shaking).

**Comment by FlutterIssues** [comment]
<a href="https://github.com/IvBaranov"><img src="https://avatars.githubusercontent.com/u/6000572?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [IvBaranov](https://github.com/IvBaranov)**
_Friday Nov 06, 2015 at 16:33 GMT_

----

I am not sure I should start new issue so:
Demo project _my_app_ prints: 
`[WARNING:asset_bundle_impl.cc(45)] Requested asset 'content/drawable-xxhdpi/ic_add_white_24dp.png' does not exist.`

**Comment by abarth** [comment]
Adding all the sizes makes the stocks FLX about 50KB bigger.  Probably the right trade-off for now.
