### ISSUE TITLE
Error running gradle

### ISSUE THREAD

**Issue by tomascmk** [flutter/flutter#23509]
I have some issues running the flutter proyect with genymotion or any other emulator. I have all installed and the "Flutter doctor" says thats all ok.

this is the error:

* Error running Gradle:
Exit code 1 from: C:\Users\Tomas\AndroidStudioProjects\mi_app\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Tomas\AndroidStudioProjects\mi_app\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by zoechi** [comment]
Merging with #23404

The first error looks like #19719 though.
