### ISSUE TITLE
compilation gradle error

### ISSUE THREAD

**Issue by namespace7** [flutter/flutter#23502]
trying running a simple application in vs code using flutter gives me the following error.
![image](https://user-images.githubusercontent.com/29954682/47489828-22af2400-d865-11e8-8d82-8b1721e7aa4c.png)

Even after flutter doctor has no error
![image](https://user-images.githubusercontent.com/29954682/47489988-6e61cd80-d865-11e8-9106-565748cfdebc.png)

help needed!

**Comment by zoechi** [comment]
Merging with #23404
