### ISSUE TITLE
Firebase Auth sendPasswordReset issue

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#23512]
Firebase Auth sendPasswordReset does not handle errors correctly when the email address does not exist. I receive this error:
```
W/BiChannelGoogleApi(15859): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@135ff7f
W/DynamiteModule(15859): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth(15859): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(15859): [FirebaseAuth:] Preparing to create service connection to gms implementation
E/flutter (15859): [ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
E/flutter (15859): 'dart:async/future_impl.dart': Failed assertion: line 146: '<optimized out>': is not true.
E/flutter (15859): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (15859): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (15859): #2      _FutureListener.handleError (dart:async/future_impl.dart:146:14)
E/flutter (15859): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
E/flutter (15859): #4      Future._propagateToListeners (dart:async/future_impl.dart:675:24)
E/flutter (15859): #5      Future._completeError (dart:async/future_impl.dart:494:5)
E/flutter (15859): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
E/flutter (15859): #7      _Completer.completeError (dart:async/future_impl.dart:27:5)
E/flutter (15859): #8      _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
E/flutter (15859): #9      FirebaseAuth.sendPasswordResetEmail (package:firebase_auth/firebase_auth.dart)
E/flutter (15859): <asynchronous suspension>
E/flutter (15859): #10     Auth.forgotPassword (file:///Volumes/drive/Flutter_Apps/flutter_crushn/lib/models/auth.dart:38:25)
E/flutter (15859): <asynchronous suspension>
E/flutter (15859): #11     _LoginState.forgotPasswordPressed (file:///Volumes/drive/Flutter_Apps/flutter_crushn/lib/pages/login.dart:382:42)
E/flutter (15859): <asynchronous suspension>
E/flutter (15859): #12     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (15859): #13     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (15859): #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (15859): #15     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (15859): #16     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (15859): #17     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (15859): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (15859): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (15859): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (15859): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (15859): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (15859): #23     _invoke1 (dart:ui/hooks.dart:153:13)
E/flutter (15859): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:107:5)
```

**Comment by Chronic788** [comment]
I am receiving the same type of exception for FirebaseAuth.signInWithEmailAndPassword():

> E/flutter (  852): [ERROR:flutter/shell/common/shell.cc(188)] Dart Error: Unhandled exception:
E/flutter (  852): 'dart:async/future_impl.dart': Failed assertion: line 146:  -optimized out- is not true.
E/flutter (  852): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (  852): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (  852): #2      _FutureListener.handleError (dart:async/future_impl.dart:146:14)
E/flutter (  852): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
E/flutter (  852): #4      Future._propagateToListeners (dart:async/future_impl.dart:675:24)
E/flutter (  852): #5      Future._completeError (dart:async/future_impl.dart:494:5)
E/flutter (  852): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
E/flutter (  852): #7      _Completer.completeError (dart:async/future_impl.dart:27:5)
E/flutter (  852): #8      _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
E/flutter (  852): #9      FirebaseAuth.signInWithEmailAndPassword (package:firebase_auth/firebase_auth.dart)
E/flutter (  852): <asynchronous suspension>
E/flutter (  852): #10     Session.login.<anonymous closure> (package:mood_map/utilities/session.dart:35:30)
E/flutter (  852): <asynchronous suspension>
E/flutter (  852): #11     _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (  852): #12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (  852): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (  852): #14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (  852): #15     Future._complete (dart:async/future_impl.dart:476:7)
E/flutter (  852): #16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (  852): #17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
E/flutter (  852): #18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
E/flutter (  852): #19     Session._checkUserAlreadyExists (package:mood_map/utilities/session.dart)
E/flutter (  852): <asynchronous suspension>
E/flutter (  852): #20     Session.login (package:mood_map/utilities/session.dart:31:11)
E/flutter (  852): <asynchronous suspension>
E/flutter (  852): #21     LoginScreenState._loginButtonBlock.<anonymous closure>
(package:mood_map/login/login_view.dart:312:27)
E/flutter (  852): #22     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (  852): #23     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (  852): #24     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (  852): #25     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)

**Comment by ffeu** [comment]
I think this is a general problem regarding error handling in `firebase_auth`.
As in #18312 and #20223 . So I believe it's a duplicate.

And if it is, there's a PR already for that. flutter/plugins#775 .

**Comment by rlee1990** [comment]
Its not @ffeu the issue is if an error has happened like no account exists it should give an error but its giving the above and sometimes crashing the app

**Comment by cyanglaz** [comment]
@rlee1990 Are you still experiencing the issue?

**Comment by rlee1990** [comment]
@cyanglaz i have not tried in awhile so I'm not sure.

**Comment by cyanglaz** [comment]
@rlee1990 Thank you for the quick response.  I would close the issue now since it seems to be being fixed https://github.com/flutter/plugins/pull/775. If you continue to experience the issue, please free feel to reopen or open another issue with details.

**Comment by kroikie** [comment]
@rlee1990

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/596. Any further collaboration will be done there.
