### ISSUE TITLE
"flutter start" doesn't rebuild apk when switching from --debug to official engine and back

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#2352]
Under some conditions the Android APK does not appear to rebuild when it should, causing the bits in it to look like slow mode components when they shouldn't be.

### Steps to Reproduce
* Download Flutter repo
* ```cd examples/material_gallery```
* Force a rebuild of the Material Gallery app, e.g. by touching android/AndroidManifest.xml
* ```flutter start --debug && flutter logs```
* Note slow mode banner
* ```flutter start --no-checked && flutter logs```
* Note slow mode banner still present, even though slow mode should have been disabled by --no-checked
* Force another rebuild
* ```flutter start --no-checked && flutter logs```
* Note slow mode is now properly disabled

### Flutter Version
My version of flutter doesn't seem to have a version command, but it's tip of tree as of March 1 (hash: 7a2d82d0af8e9c8cf3d27438ed62f30446270aec).

**Comment by Hixie** [comment]
It also doesn't get rebuilt if all that changed was the local engine (i.e. you rebuilt the local engine but did not touch anything in your repo, and run it with --debug both before and after rebuilding the engine).

**Comment by abarth** [comment]
@devoncarew Did you fixenate this?

**Comment by devoncarew** [comment]
Yup, in https://github.com/flutter/flutter/pull/4032.
