### ISSUE TITLE
Error in Google maps for flutter in gestureRecognizers in google_map.dart

### ISSUE THREAD

**Issue by mjserrato** [flutter/flutter#23524]
## Steps to Reproduce

1. I'm trying to use the plugin: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter
2. When I'm trying to run the example provided: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/map_ui.dart
3. I got the error:
```
Error: The argument type 'dart.core::Set' can't be assigned to the parameter type
in
final Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers;
in google_map.dart
```

## Logs

```
```

```
X:\_flutter_sdk>flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [VersiÃ³n 10.0.17134.345], locale es-ES)
    • Flutter version 0.9.4 at X:\_flutter_sdk
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at x:\_android_sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = x:\_android_sdk\
    • Java binary at: X:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at X:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at W:\Program Files\JetBrains\IntelliJ IDEA 2018.1.2
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.4668.60

[√] Connected devices (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```
[log_error.txt](https://github.com/flutter/flutter/files/2516253/log_error.txt)

[main.dart.txt](https://github.com/flutter/flutter/files/2516256/main.dart.txt)

```
```

```
```

**Comment by zoechi** [comment]
Can you please try `flutter channel master` and check if you can still reproduce?

**Comment by mjserrato** [comment]
Hi

Please find below the error I got trying to do flutter channel master in my computer:

Thank you.

X:\_flutter_sdk>flutter channel master
Switching to flutter channel 'master'...
git: error: The following untracked working tree files would be overwritten by checkout:
git:    dev/integration_tests/ios_host_app/Flutter/.gitkeep
git:    examples/flutter_gallery/test/demo/material/expansion_panels_demo_test.dart
git:    packages/flutter/lib/src/material/color_scheme.dart
git:    packages/flutter/lib/src/material/material_button.dart
git:    packages/flutter/lib/src/material/text_theme.dart
git:    packages/flutter/test/material/switch_list_tile_test.dart
git:    packages/flutter/test/material/text_theme_test.dart
git:    packages/flutter/test/material/theme_defaults_test.dart
git:    packages/flutter/test/painting/binding_test.dart
git:    packages/flutter_driver/lib/src/common/fuchsia_compat.dart
git:    packages/flutter_localizations/lib/src/l10n/material_km.arb
git:    packages/flutter_localizations/lib/src/l10n/material_mn.arb
git:    packages/flutter_tools/templates/app/.gitignore.tmpl
git:    packages/flutter_tools/templates/app/.metadata.tmpl
git:    packages/flutter_tools/templates/app/README.md.tmpl
git:    packages/flutter_tools/templates/app/android-java.tmpl/app/build.gradle.tmpl
git:    packages/flutter_tools/templates/app/android-java.tmpl/app/src/main/java/androidIdentifier/MainActivity.java.tmpl
git:    packages/flutter_tools/templates/app/android-java.tmpl/build.gradle
git:    packages/flutter_tools/templates/app/android-kotlin.tmpl/app/build.gradle.tmpl
git:    packages/flutter_tools/templates/app/android-kotlin.tmpl/app/src/main/kotlin/androidIdentifier/MainActivity.kt.tmpl
git:    packages/flutter_tools/templates/app/android-kotlin.tmpl/build.gradle
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/AndroidManifest.xml.tmpl
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/drawable/launch_background.xml
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/mipmap-hdpi/ic_launcher.png
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/mipmap-mdpi/ic_launcher.png
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/mipmap-xhdpi/ic_launcher.png
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
git:    packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/values/styles.xml
git:    packages/flutter_tools/templates/app/android.tmpl/gradle.properties
git:    packages/flutter_tools/templates/app/android.tmpl/gradle/wrapper/gradle-wrapper.properties
git:    packages/flutter_tools/templates/app/android.tmpl/settings.gradle
git:    packages/flutter_tools/templates/app/ios-objc.tmpl/Runner.xcodeproj/project.pbxproj.tmpl
git:    packages/flutter_tools/templates/app/ios-objc.tmpl/Runner/AppDelegate.h
git:    packages/flutter_tools/templates/app/ios-objc.tmpl/Runner/AppDelegate.m
git:    packages/flutter_tools/templates/app/ios-objc.tmpl/Runner/main.m
git:    packages/flutter_tools/templates/app/ios-swift.tmpl/Runner.xcodeproj/project.pbxproj.tmpl
git:    packages/flutter_tools/templates/app/ios-swift.tmpl/Runner/AppDelegate.swift
git:    packages/flutter_tools/templates/app/ios-swift.tmpl/Runner/Runner-Bridging-Header.h
git:    packages/flutter_tools/templates/app/ios.tmpl/Flutter/AppFrameworkInfo.plist
git:    packages/flutter_tools/templates/app/ios.tmpl/Flutter/Debug.xcconfig
git:    packages/flutter_tools/templates/app/ios.tmpl/Flutter/Release.xcconfig
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner.xcworkspace/contents.xcworkspacedata
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
git:    packages/flutter_tools/templates/app/ios.tmpl/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
git:    packages/flutter_t
git: Aborting
Switching channels failed with error code 1.

**Comment by zoechi** [comment]
Use
```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
```
in the Flutter install directory.

**Comment by zoechi** [comment]
Merging with #23253
