### ISSUE TITLE
Flutter run - is not work

### ISSUE THREAD

**Issue by OfficialSameer** [flutter/flutter#23522]
![error](https://user-images.githubusercontent.com/41697881/47519901-52354f00-d8ac-11e8-9bc6-9d7620d2cae4.PNG)

**Comment by her0satr** [comment]
This issue exist for fresh install flutter

**Comment by her0satr** [comment]
I am already update my build.gradle repository like this : 

    repositories {
        maven { url 'https://maven.fabric.io/public' }
        mavenCentral()
        jcenter()
        google()
    }

**Comment by hariprasadiit** [comment]
duplicate of #23404

**Comment by zoechi** [comment]
Thanks @hariprasadiit 
Merging with #23404
