### ISSUE TITLE
OneSignal notification to open certain activity on tap

### ISSUE THREAD

**Issue by eboye** [flutter/flutter#23549]
I'm making and app that uses OneSignal plugin.

I receive the notification and everything is working up until this point.

I'm trying to open certain activity on notification tap (click).

in my void main(){} I'm registering notification listeners, but here I'm out of context, so I can't use navigator etc.

```dart
void main() {
  OneSignal.shared.init("appid");
  OneSignal.shared.init("appid", iOSSettings: {
    OSiOSSettings.autoPrompt: false,
    OSiOSSettings.inAppLaunchUrl : true
  });
  OneSignal.shared.setSubscriptionObserver((OSSubscriptionStateChanges changes) {
    print(changes.to);
  });
  OneSignal.shared.setNotificationReceivedHandler((OSNotification notification) {
//    print(notification.payload.additionalData['catID']);
  });
  OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
    var catID = result.notification.payload.additionalData['catID'];
  });
  OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);
  runApp(
      MyApp()
  );
}
```

So in OneSignal.shared.setNotificationOpenedHandler I'm getting the value passed via notification (from backend app), but how do I create new activity here? Or is there a better approach to this?

**Comment by asrma7** [comment]
I am also stuck in this. If anyone knows how to please help...

**Comment by asrma7** [comment]
Hey there,
I found a fix but it is incomplete.
I used didChangeDependencies() for tracking context and it opens the desired activity(screen) but only when the app is open. 
setNotificationOpenedHandler() is not running in background thus it doesn't work if the app is close.
check this out...
@override
  void didChangeDependencies() {
    OneSignal.shared.setNotificationOpenedHandler((notification) {
      var notify = notification.notification.payload.additionalData;
      if (notify["type"] == "message") {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => DM(user: notify['id']),
          ),
        );
      }
      if (notify["type"] == "user") {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => Profileo(notify["id"]),
          ),
        );
      }
      if (notify["type"] == "post") {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => ViewPost(notify["id"]),
          ),
        );
      }
    });
    super.didChangeDependencies();
  }

**Comment by asrma7** [comment]
now I need a fix to run this in backround so that it can work even when app is closed.

**Comment by feriyalsusanto** [comment]
Hello, did you guys find the solution for this issue ?
I already try this solution below, but the problem is when i store the notification to local db (mobile), data is not saved. But it can goes to the specific page after tap notification (apps inactive). And can you please provide the code to try ? Thank you.

> 
> 
> @asrma7 I'll definitely try it out. For the background process I found this: https://stackoverflow.com/a/42041981/2403126

**Comment by goderbauer** [comment]
This sounds like an issue that should be raised with the OneSignal SDK: https://github.com/OneSignal/OneSignal-Flutter-SDK

**Comment by rabihmb** [comment]
I'm facing the same problem, the below code to open certain activity

```
OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      this.setState(() {
        print(
            "Opened notification: ${result.notification.jsonRepresentation().replaceAll("\\n", "\n")}");

        getJSONData(result.notification.payload.additionalData['id'])
            .then((result) async {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => ArticleDetails(result['body']),
            ),
          );
        });
      });
    });
```

it only open the app is running, so what shall I do in order to open the articleDetails when the app is closed?
