### ISSUE TITLE
Problem with debugging app

### ISSUE THREAD

**Issue by Tooxic** [flutter/flutter#23557]
When i am trying to debug my flutter app i get this error- "'package:flutter/src/widgets/framework.dart' Failed assertion line 3533 pos 14: 'owner.debugcurrentbuildtarget == this': is not true"

![capture](https://user-images.githubusercontent.com/33166817/47553582-c3eeb680-d907-11e8-911d-14031826e8bf.PNG)

**Comment by zoechi** [comment]
Can you please provide more information about how to reproduce?

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
