### ISSUE TITLE
shared_preferences Xcode BUILD FAILED

### ISSUE THREAD

**Issue by RobertYeYu** [flutter/flutter#23556]
```
...
Xcode build done.                                            4.9s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
Undefined symbols for architecture arm64:
"_OBJC_CLASS_$_FLTSharedPreferencesPlugin", referenced from:
objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the precompiled application for the device.
Error launching application on iPhone.
Exited (sigterm)
```
---------------------------
Xcode Version 10.0 (10A255)
shared_preferences: ^0.4.3

**Comment by RobertYeYu** [comment]
It's weird
I create a new flutter project and it's just fine
but in my project xcode have error:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLTSharedPreferencesPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--------------------
And flutter doctor -v:
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14.1 18B45d, locale zh-Hans-CN)
    • Flutter version 0.9.4 at /Users/yeyu/Documents/GitHub/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/yeyu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • iPhone • 509396f8b6f9ad5429e8c52c863407005b36c951 • ios • iOS 12.0.1

• No issues found!
--------------------
And instead, we create a method to call UserDefaults and SharedPreferences by MethodChannel, and it's ok.
Thank you and flutter is really awesome!

**Comment by zoechi** [comment]
If it works in a new project, then some files in `ios/` are not up-to-date.
Try deleting `ios/` and run `flutter create .` and re-apply manual changes you made before in that directory.

**Comment by RobertYeYu** [comment]
Awesome, it works!And thank you very much

**Comment by warriorCoder** [comment]
OH MY GOODNESS @zoechi, your suggestion saved my app and got me successful builds and archives again. I'm so happy to finally have a solution after **DAYS** of looking.

**Comment by mikah22** [comment]
I tried this but I am still having this issue. Just to give a little bit of a background, my iOS app is built using Swift and I am **using Flutter only for a couple of screens** (trying to integrate Flutter into existing iOS app). I use **Flutter library Shared_Preferences** to pass data between Swift and Flutter code. My app runs **absolutely fine** when deployed from Xcode in debug mode on a real device and simulator, but I am unable to create an archive. I get the following 2 errors when I try creating an archive from XCode 

**Undefined Symbol: _OBJC_CLASS_$_FlutterMethodChannel
Undefined Symbol: _FlutterMethodNotImplemented**

What am I doing wrong? It works on a real device and simulator, it's the archive that's failing. @zoechi or @warriorCoder I would highly appreciate if you can please help me with this, I have been pulling my hair with this issue the last couple of days and I am this short of giving it up :-(

**Comment by baoxu** [comment]
删除Podfile，Podfile.lock，Pods文件夹，Runner.xcworkspace，让flutter重新生成这几个文件，就好了

**Comment by warriorCoder** [comment]
Do you mean create an archive? Are you able to create a release build?
Bundles are only on Android iirc.

**Comment by youngtet** [comment]
facing same issue when Archiving in Xcode @zoechi how do i go about this?
![image](https://user-images.githubusercontent.com/60430933/78033992-cf9da280-736f-11ea-9d4c-b951a88658b7.jpg)
