### ISSUE TITLE
Url_launcher Camera access

### ISSUE THREAD

**Issue by sureshy02** [flutter/flutter#23554]
After setting the `forceWebView: true` and `enableJavaScript: true`, able to load the page but not able to access the camera. 
I am not getting error on click of a button.

If i set those two false url is launching in my browser with camera support on click of button.
 Is there any way to open camera by setting `forceWebView: true` and `enableJavaScript: true`.

**Comment by ShubhraDeshpande** [comment]
@sureshy02  can you please share the url for launching camera app?

**Comment by zoeyfan** [comment]
Looking at the history above, it seems that we have been waiting for customer response for more than 5 months. Closing this for now. Please feel free to reopen if you have additional information.

**Comment by Faiizii** [comment]
I am facing the same error. https://appr.tc/ check on this url. This url required microphone and camera permissions.
