### ISSUE TITLE
android studio   Running failed

### ISSUE THREAD

**Issue by 370966584** [flutter/flutter#23564]
I created a new Flutter project.  android studio  Console log:

* Error running Gradle:
Exit code 1 from: /Users/haoran1/Desktop/flutter_app/android/gradlew app:properties:
Download https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/haoran1/Desktop/flutter_app/android/app/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s

Finished with error: Please review your Gradle project setup in the android/ folder.
## Logs

```
```

Mmmmm-2:flutter_app haoran1$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    ✗ Android license status unknown.
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected devices (1 available)

! Doctor found issues in 2 categories.

How should I solve this problem?

**Comment by rexdarel** [comment]
I've got the same exact issue.

**Comment by 370966584** [comment]
> I've got the same exact issue.



I have solved it.#23404

**Comment by zoechi** [comment]
@370966584 thanks!
Merging with #23404
