### ISSUE TITLE
Centralise the exception reporting so that we coalesce widget exceptions also

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2356]
Rendering exceptions only show the first one, after that they're all coalesced. We should do the same for all exceptions by routing everything through a single exception processing function. This would also help with fixing #2323 and #2220.

**Comment by Hixie** [comment]
I have a local branch where I create a services/assertions.dart that contains a FlutterError (extends AssertionError) that's identical to RenderingError and WidgetError. I propose to fold the latter two into the former, and start centralising more logic into that file, such as having just one kind of callback, just one place that summarises exceptions, etc. (For the callbacks one of the arguments would presumably be an object that is specialised for each kind of exception; for the printing, there would presumably be a callback that is invoked to get the extra colour we sometimes include.)

**Comment by Hixie** [comment]
I've done the folding into FlutterError part.

**Comment by krisgiesing** [comment]
Does this also address assertions?

**Comment by Hixie** [comment]
Yes.

**Comment by Hixie** [comment]
(`FlutterError` is a subclass of `AssertionError`.)

**Comment by krisgiesing** [comment]
Ah right, I missed that part, thanks.

**Comment by krisgiesing** [comment]
Very nice, thanks :)
