### ISSUE TITLE
Provide a default list of locales for host platforms to match test behavior with platform behavior.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#23579]
Now that we provide null instead of a non-null locale when locale is not yet set by the platform, test environments will experience null locales while real devices and emulators will not.

To bring test environments into parity with the other production and emulator environments, we should detect this and set a list of default locales so tests can also make the assumption that locale does not provide null.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/6689 Implementation
https://github.com/flutter/flutter/pull/23596 Tests

**Comment by GaryQian** [comment]
This has landed for flutter_tester. Similar work still needs to be done with other platforms that do not support locales.

**Comment by zanderso** [comment]
@GaryQian Could you be more specific about what remains to be done here? If there is any work needed in the tool, please re-add the tool label.

**Comment by GaryQian** [comment]
So I just verified that the web does provide a non-null locale, as well as desktop and Fuchsia. I think we can close this for now. If we discover new inconsistencies around locales being null, then we can deal with it then. As far as I know, this should be resolved now.
