### ISSUE TITLE
Error while creating  new flutter project

### ISSUE THREAD

**Issue by harisumaid** [flutter/flutter#23571]
No new window is opened neither the file created with that application name contains any file .
one error is shown in event log.
'where' is not recognized as an internal or external command, operable program or batch file.

flutter doctor output
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.286], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected devices (1 available)

• No issues found!

**Comment by zoechi** [comment]
What do you get if you execute `where` in a terminal window?

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/10484#issuecomment-396484669

**Comment by zoechi** [comment]
This doesn't look like a Flutter issue.
I'm going to merge with #10484
