### ISSUE TITLE
problem of flutter toast

### ISSUE THREAD

**Issue by fe9lsh3ben** [flutter/flutter#23575]
this error always come to me once I try to debug flutter app .
```
* Error running Gradle:
Exit code 1 from: C:\Users\---\IdeaProjects\flutter_fix\android\gradlew.bat app:properties:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fluttertoast'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

Finished with error: Please review your Gradle project setup in the android/ folder.
```
this problem appare after I fixed the gradle.api issue  [gradel api issue](https://github.com/mrmitew/flutter/blob/6369f5481c08714b8a724a92dea2328d23d7bba3/packages/flutter_tools/gradle/flutter.gradle)

**Comment by hariprasadiit** [comment]
@fe9lsh3ben Please post contents of `android/gradle/wrapper/gradle-wrapper.properties` file

**Comment by Mahi-K** [comment]
update the flutter toast package's android/build.gradle file as 
```
group 'io.github.ponnamkarthik.toast.fluttertoast'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.2.51'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
}
```
and
gradle-wrapper.properties
``` 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```

then flutter clean and see if this solves the issue.

**Comment by fe9lsh3ben** [comment]
unfortunately got the same error since the jcenter get broken for same cause I don't know and most of developer facing same issue.

So I used to creat a fresh project then post the old lib int the new project.

**Comment by fe9lsh3ben** [comment]
unfortunately got the same error since the jcenter get broken ,don't know the cause, and alot of developer facing the same issue.
so I used to make a new project then post the old files in the new project.
this is the only way that I know so I would continue my developing in the next day.

**Comment by zoechi** [comment]
Lots of people were facing #23404 which sounds like what you are referring to. 
The error message in this issue looks different to me.
