### ISSUE TITLE
Would be nice to be able to break-on-exceptions from Atom

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2357]
I suspect Observatory already supports this? @johnmccutchan 

But when I'm hitting an exception in my flutter app it seems more useful to break at the stack than to see a huge stack dump in the logs.

@devoncarew ?

**Comment by Hixie** [comment]
You can do this in Observatory's debugger by typing "set break-on-exception All" in the input box.

**Comment by devoncarew** [comment]
We currently set the exception breaking behavior to breaking on uncaught exceptions. The Flutter framework catches and handles exceptions, so we don't break. We should add an option (in atom) to change the mode to break on all exceptions.

**Comment by Hixie** [comment]
We could also have flutter explicitly call debugger() when Atom has set a
flag. The Mojo Dart bindings in checked mode (only, IIRC?) throw and catch
an exception for every mojo message in order to remember the stack trace or
something, so breaking on all exceptions is expensive.

**Comment by abarth** [comment]
I wonder if they could use `StackTrace.current` instead of throwing and catching.

**Comment by Hixie** [comment]
That uses the same trick. But yeah, observatory (or whoever implements break-on-exception) needs some way to skip some of the caught exceptions if we don't want to go down the dart:developer debugger(when:atomRequestedBreak) route.

**Comment by jimbeveridge** [comment]
If Flutter calls debugger(), does that mean that the stack would already be unwound to that point? That makes it problematic to debug the failure site in terms of seeing local variables.

**Comment by Hixie** [comment]
yeah, good call.

**Comment by johnmccutchan** [comment]
> The Mojo Dart bindings in checked mode (only, IIRC?) throw and catch
an exception for every mojo message in order to remember the stack trace or
something, so breaking on all exceptions is expensive.

We switched to using `StackTrace.current` a month ago so this isn't an issue.

> If Flutter calls debugger(), does that mean that the stack would already be unwound to that point?

It depends on where the `debugger` call is made but, yeah, if it's at the `catch`, we've unwound the stack.

---

It would be good if we could come up with some specific cases and the behaviour we want during development / production. Then I can add support to the VM / service protocol.

**Comment by eseidelGoogle** [comment]
When I last desired this, it was that I had invalid constraints on a renderer (I was working on the game and turning it landscape) which caused an exception to be thrown in the rendering tree, which produced 85 yards of log messages for context.  The log messages are nice and all, but I would rather have just been able to automatically break deep in the framework where the assert() was failing.

**Comment by devoncarew** [comment]
It sounds like we may want either a break-on-assert mode in the runtime, or for it to be ~safe to run with break on all exceptions turned on. Given the change to using `StackTrace.current` that may be a pretty safe assumption.
