### ISSUE TITLE
-Wa,--noexecstack is not supported by the Mac toolchain when targeting Android.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#23606]
@kf6gpe: Please update the Mac toolchain before adding the flag. This flag was added in https://github.com/flutter/buildroot/pull/177 and is now causing the Mac bots to fail as they try to build any Android targets. The buildroot is being patched to remove this flag till the toolchain rolls forward.

**Comment by kf6gpe** [comment]
Will do -- thanks for catching this! I'll work with the team to update the bots, and we can reapply the patch. Thanks for catching this!

**Comment by pedromassangocode** [comment]
Is this still a valid issue? I'm not sure how to confirm that this was solved already.

**Comment by chinmaygarde** [comment]
> Is this still a valid issue?

No.

> I'm not sure how to confirm that this was solved already.

The flag is now [added conditionally in the buildroot](https://github.com/flutter/buildroot/blob/236a74613244aa98e45ea0e2bffd16d03adb9286/build/config/compiler/BUILD.gn#L379).
