### ISSUE TITLE
flutter run --no-resident

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#23605]
We should have a `--resident` option, defaulting to on, which keeps `flutter run` running once the app has started. Running with `--no-resident` should disable this, causing us to exit the tool as soon as the app is running, before showing the help screen, and not showing the logs.

This could then combine with `flutter attach` to later allow that app to be debugged.

See https://github.com/flutter/flutter/wiki/The-flutter-run-variants

cc @gspencergoog @tvolkert @dnfield

**Comment by jonahwilliams** [comment]
We currently have this option:

```
flutter run -h -v:
...
    --[no-]resident                                   Stay resident after launching the application. Not available with "--trace-startup".
                                                      (defaults to on)
```

The attaching after the fact should work too. Can this issue be closed @Hixie ?

**Comment by Hixie** [comment]
Yup!
