### ISSUE TITLE
flutter build ios failed with project on SD card

### ISSUE THREAD

**Issue by berialcheng** [flutter/flutter#23616]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

ArgumentError: Invalid argument(s)

```
#0      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:833:9)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:77:62)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:372:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-CN)
    • Flutter version 0.9.4 at /Users/zhongcheng/workingcopy/flutterworking/flutter
    • Framework revision f37c235c32 (4 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/zhongcheng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4127.31

[✓] VS Code (version 1.28.2)
    • VS Code at /Users/zhongcheng/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
> #1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:77:62)

That line isn't even that long https://github.com/flutter/flutter/blob/v0.9.4/packages/flutter_tools/lib/src/commands/build_ios.dart#L77

Can you please try
```
git clean -xfd
git pull
flutter doctor
```
in your Flutter install directory?

**Comment by berialcheng** [comment]
![image](https://user-images.githubusercontent.com/2362847/47603588-aeb97b00-da20-11e8-8dd0-10d4cfb8d910.png)
@zoechi thanks for ur reply, I think it might be the string substitution error

My working directory of installed flutter has not been changed.
![image](https://user-images.githubusercontent.com/2362847/47603601-08ba4080-da21-11e8-83c6-ad57c2f94ea5.png)

![image](https://user-images.githubusercontent.com/2362847/47603605-12dc3f00-da21-11e8-9fb3-0188991f3ae2.png)

**Comment by zoechi** [comment]
No idea what could cause 

> ArgumentError: Invalid argument(s)

at this line.

**Comment by berialcheng** [comment]
@zoechi 
any idea where could i fetch more logging information ?
I would like to add more diagnostic print into the build script to see what going on there.

**Comment by zoechi** [comment]
You could try to modify the file locally and add some print statements.
If you delete `flutter_install_dir/bin/cache` the executables should be rebuilt using the modified source.

**Comment by berialcheng** [comment]
Summary
---
@zoechi 
thanks, i think i found root cause.
In summary it was caused by my mounted SD card device, some configuration might lead some sort readability problem. when i checkout the project somewhere else , the build passed immediately.

Issue Execution Scenario
---
1. following execution is passed (line: 59)
![image](https://user-images.githubusercontent.com/2362847/47604527-b16e9d00-da2d-11e8-91d1-ccb1eafb67b2.png)
2. then the following eval is failed , due to the system could not open `<project_folder>/ios/Runner.xcodeproj/project.xcworkspace` (while trying resolve $app)
![image](https://user-images.githubusercontent.com/2362847/47607664-61a3cc00-da55-11e8-81d1-a8d7754d9b5f.png)
3. the system crashed immediately.

Suggestion
---
Although it will be better if we have this evaluation error hinted or wrapped , i do understand
the scenario in order to reproduce this issue is quite rare and limited, so feel free to close this issue. 
And thank you again for your support
