### ISSUE TITLE
running a service in background

### ISSUE THREAD

**Issue by asrma7** [flutter/flutter#23613]
I need to run certain tasks in background that work even when the app is closed. For example I wanna watch notification open handler, store data on notification received, open app after certain duration. Is there any way to run code in background in both IOS and Android?

**Comment by zoechi** [comment]
https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
