### ISSUE TITLE
Remove minimum size of IconButton widget

### ISSUE THREAD

**Issue by vmihalachi** [flutter/flutter#23619]
Hi, I am developing an application for a client and he designed the UI. Unfortunately many buttons are small or short in height. I already configured the theme of the app so the minimum height is not a problem for the majority of the buttons. 

IconButtons however have a private const called '_kMinButtonSize' set to 48, and that's too big for us. 

I would like to use the niceties of the IconButton (padding, tooltip, ripple effect) without having to clone that button and change this size.

One solution could be to use 'Theme.of(context).buttonTheme.minWidth' instead of the constant. 

I can make a pull request if you agree

**Comment by sergiuiacob1** [comment]
Hey! Any plans on solving this? It's been a while since this was issued and there's no feedback. I have just encountered the same problem as well
