### ISSUE TITLE
Cloud Firestore paging - StartAtDocument, internal methods

### ISSUE THREAD

**Issue by radvansky-tomas** [flutter/flutter#23618]
Existing version of Cloud Firestore plugin does not support essential methods such as:
`startAtDocument`, `startAfterDocument`, `endAtDocument` and `EndBeforeDocument`

I've tried to extend plugin to support them, but from my understanding to make it work, we have to pass `DocumentSnapshot` object to Query params. However this is impossible due to current access control settings in Firebase SDK, where `DocumentSnapshot` cannot be constructed, and constructor -> `snapshotWithFirestore` is hidden in internal header file `FIRDocumentSnapshot`+`Internal.h` like other internal methods.

I tried to follow pattern of serializing properties and pass them to platform dependent code, and even though dart side might be doable, I cannot create new DocumentSnapshot object from any serialized data.

I am not really looking for workarounds or hacks, so please do not suggest creating some properties inside Firestore db and passing their values to `startAt(values)` method, as this is not the case and plugin should reflect SDKs.

**Comment by radvansky-tomas** [comment]
` FIRQuery *next = [[[db collectionWithPath:@"cities"]
      queryOrderedByField:@"population"]
      queryStartingAfterDocument:lastSnapshot];`

**Comment by zoechi** [comment]
There is an interesting community approach that might be worth a closer look https://github.com/fluttercommunity/firebase_flutter_sdk (didn't have a chance myself yet)

**Comment by radvansky-tomas** [comment]
Thx but that project is miles away from real usage. But at least they think the same...that current approach is not really sustainable. So either as I said, do proper for and keep up with official firebase releases OR write RESTful client independent on SDK. As now I have no idea what next, I though that there is support for firebase, but without simple paging its not really ready to run on mobile

**Comment by ajonno** [comment]
Is paging for Cloud Firestore scheduled ? We're currently looking at 0.8.2 (```cloud_firestore```)

**Comment by kushvatsa** [comment]
any updates?

**Comment by radvansky-tomas** [comment]
Any update on this ? So We still cant use pagination ?

**Comment by radvansky-tomas** [comment]
Update here: https://github.com/firebase/firebase-ios-sdk/issues/2654

**Comment by radvansky-tomas** [comment]
Basically nothing changed since oct2018, and I really dont understand what is reasoning behind this.

**Comment by SogoGolf** [comment]
Check out CosmosDB as alternative

**Comment by radvansky-tomas** [comment]
Issue resolved, please if anyone can review changes, apply formatting you accept and merge it with master. thx @kroikie

**Comment by creativecreatorormaybenot** [comment]
This is implemented now.

**Comment by kroikie** [comment]
@radvansky-tomas

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/593. Any further collaboration will be done there.
