### ISSUE TITLE
希望提供一个Widget 类似Cavnas 能够让开发者自己实现2D/3D效果  或者提供渲染相关的更底层的API

### ISSUE THREAD

**Issue by yinxulai** [flutter/flutter#23622]

**Comment by zoechi** [comment]
Looks Chinese. What does it mean?

**Comment by yinxulai** [comment]
I hope to provide a Widget like Cavnas that allows developers to implement 2D/3D effects themselves or provide rendering-related lower-level APIs.

**Comment by zoechi** [comment]
What 2D/3D effects are you missing?

**Comment by yinxulai** [comment]
I seem to have found some of them in the ui library.
