### ISSUE TITLE
Automatic OTP verification in IOS?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#23620]
I use sms plugin to build an auto top verification in my flutter app. But it doesn't work on ios.

When I search I found that iOS 12 allows securely to read top. Do we have such a plugin for flutter?

https://stackoverflow.com/questions/39631168/automatic-otp-verification-in-ios

**Comment by zoechi** [comment]
Check on pub.dartlang.org or ask on StackOverflow.

You can always make native functionality available building your own plugin
https://flutter.io/developing-packages/#plugin

**Comment by fawazhussain** [comment]
checkout flutter_otp.
https://pub.dev/packages/flutter_otp
