### ISSUE TITLE
Bad state: No element warning when checking class != null

### ISSUE THREAD

**Issue by ronmany** [flutter/flutter#23623]
I'm getting a warning in flutter: **_Bad state: No element_** 
When checking if object  is null (or not null in my case)

```
if (batchInProgress != null)         <-------- here
      return;   //do not change selection if any batch is in progress
    this.selectedBatch = _batch;
```

Is there a better way to check if object initiated?
It is just a warning, my app runs ok after that, I just like to clean my log.

**Comment by zoechi** [comment]
> Is there a better way to check if object initiated?

To me it's entirely unclear what the question is about.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
And please add more information there when you ask.
