### ISSUE TITLE
I have been using flutter for a while but get this screenshot now on any project

### ISSUE THREAD

**Issue by Isonomic** [flutter/flutter#23624]
![screenshot 6](https://user-images.githubusercontent.com/37713396/47606947-5f9b2800-d9d7-11e8-8ee9-c7602f1f09cb.png)

**Comment by Isonomic** [comment]
I even started a brand new emulator and a brand new flutter create project. It started on another app that was using url_launcher in vscode.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by Rockvole** [comment]
Try pressing the power button on the phone emulator.
