### ISSUE TITLE
I am getting version mismatch error while using maps in my flutter app.

### ISSUE THREAD

**Issue by 91priyansh** [flutter/flutter#23626]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'map_view' is
using version 1.2.50.

**Comment by kunit1** [comment]
Seems like map_view has been abandoned. They refer to another plug in on their repo:  https://pub.dartlang.org/packages/flutter_map#-changelog-tab-

**Comment by jaiaswani10** [comment]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'map_view' is using version
1.2.50.
