### ISSUE TITLE
How to get all the images and video files from the user device storage.

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#23637]
I'm unable to find any relevant resources regarding, how we can get all images and video files from device storage show them to user from our app in a grid view(like gallery/photos app). My aim is to show all image and video files to user such user can pick images or video files to be uploaded into our server. but, Ican't find a way to get all images and video files from device.

**Comment by zoechi** [comment]
There might be plugins available on pub.dartlang.org that allow you to do that.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
