### ISSUE TITLE
 Android license status unknown

### ISSUE THREAD

**Issue by Mohammedsalah19** [flutter/flutter#23638]
I used this command "flutter doctor --android-licenses"
but it need sdk update which sdk version it nedd ?? 
any help
![screenshot 14](https://user-images.githubusercontent.com/29697786/47614391-f9320a80-daa7-11e8-81dc-b39af111873c.png)

then 
![screenshot 15](https://user-images.githubusercontent.com/29697786/47614436-8aa17c80-daa8-11e8-8409-f33212dbb385.png)

**Comment by zoechi** [comment]
Try `sdkmanager --update`
https://developer.android.com/studio/command-line/sdkmanager#update_all_installed_packages

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Hosar** [comment]
@zoechi doing **sdkmanager --update** does not fix the problem.
I have already tried that, and also **sdkmanager --licenses** and still the same error.

![flutter-doctor](https://user-images.githubusercontent.com/9598455/53293374-704a8780-3798-11e9-87f0-1e06d7a47ac5.png)
![android-licenses](https://user-images.githubusercontent.com/9598455/53293378-76406880-3798-11e9-9634-d4ea69794872.png)
