### ISSUE TITLE
How To Run A Background Service In Flutter?

### ISSUE THREAD

**Issue by MohAbdelhamed** [flutter/flutter#23635]
Hi,
I've developing a flutter app for Android an IOS mobiles.
I need to run a service like a battery state in the background and after the battery is fully charged a sound should be played. 
Please I need a plugin that supports both Android and IOS.

Regards,

**Comment by zoechi** [comment]
https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by geeekfa** [comment]
**_Create BroadcastReceiver java file  beside MainActivity in flutter android directory._**
> this is the content of BroadcastReceiver.

`package com.example.methodchanel;`

`import android.content.BroadcastReceiver;`
`import android.content.Context;`
`import android.content.Intent;`

`import io.flutter.app.FlutterActivity;`
`import io.flutter.plugin.common.MethodChannel;`


`public class MyReceiver extends BroadcastReceiver {`
`    MethodChannel methodChannel;`
`    MyReceiver(MethodChannel methodChannel){`
`        this.methodChannel=methodChannel;`
`    }`

`    @Override`
`    public void onReceive(final Context context, Intent intent) {`
`       methodChannel.invokeMethod("I say hello every minute!!","");`
`    }`
`}`

**_Add these codes  before `</application>` tag in AndroidManifest.xml._** 

`<receiver`
`            android:name=".MyReceiver"`
`            android:enabled="true"`
`            android:exported="true">`
`            <intent-filter >`
`                <action android:name="android.intent.action.TIME_TICK"/>`
`            </intent-filter>`
`        </receiver>`

**Comment by Denmal1982** [comment]
> android send signal every one minute to flutter . in other words , your flutter code execute every 1 minute . **Even You Minimize Your Flutter App Or Switch To Another Apps On Your Phone!!**

this is good, but how to make the signal to be sent more often, for example every 30 seconds

**Comment by bsoykal** [comment]
Hi what about if the receiver was registered by the manifest and the flutter app is killed. Even i set an instance of the MethodChannel to receiver, it gives null pointer exception when the receiver triggered on a killed app.

**Comment by timrijckaert** [comment]
You could try and see if [this plugin](https://github.com/vrtdev/flutter_workmanager/) fits your need

**Comment by patelkeval78** [comment]
Here Is Explained Your Solutions https://icetutor.com/question/how-do-i-run-code-in-the-background-even-with-the-screen-off/
