### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<Widget>'

### ISSUE THREAD

**Issue by sarmadhamza** [flutter/flutter#23636]
```dart
import 'package:flutter/material.dart ';

void main(){
runApp(new MaterialApp(
  home: MyApp(),
));
}
class MyApp extends StatefulWidget{
  @override
  _State createState() => new  _State();
}
class _State  extends State<MyApp> {
  int _value1 = 0;
  int _value2 = 0;

  void _setvalue1 (int value) => setState(() => _value1 = value);
  void _setvalue2 (int value) => setState(() => _value2 = value);


  Widget makeRadios()
  {
List list = new List();
    Column column = new Column(children: list,);
    return column;
  }
  @override
  Widget build(BuildContext context) {

    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Name Her'),
      ),
       body: new Container(
         padding: new EdgeInsets.all(32.0),
         child: new Center(
           child: new Column(
             children: <Widget>[
              makeRadios(),
             ],
           ),
         ),
       ),
    );
  }
}
```

**Comment by gordinmitya** [comment]
Hey, please insert your code inside \```dart *code here* \``` so it will well formatted.

In code below the problem is 
```dart
List list = new List();
Column column = new Column(children: list,);
```
Because `List()` is not list of widgets, you should specify generic type like this:
```dart 
List<Widget> list = [];
```

**Comment by zoechi** [comment]
@gordinmitya thanks for investigating.

@sarmadhamza 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by sarmadhamza** [comment]
thanks

**Comment by sarmadhamza** [comment]
> Hey, please insert your code inside ```dart _code here_ ``` so it will be well formatted.
> 
> In code below the problem is
> 
> ```dart
> List list = new List();
> Column column = new Column(children: list,);
> ```
> 
> Because `List()` is not list of widgets, you should specify generic type like this:
> 
> ```dart
> List<Widget> list = [];
> ```

it works

**Comment by flutterq** [comment]
All Possible solution added [How to Solve type ‘List<dynamic>’ is not a subtype of type ‘List<Widget>’ Error?](https://fluttercorner.com/type-listdynamic-is-not-a-subtype-of-type-listwidget/)
