### ISSUE TITLE
request getters for   _drawerOpened and _endDrawerOpened in Scaffold

### ISSUE THREAD

**Issue by morphiak** [flutter/flutter#23630]
So I have a use case for knowing when a drawer is open, and there are private scaffold variables that do what I need, seems a no brainer to add 
```dart
  bool isDrawerOpen(){
    return _drawerOpened;
  }
  bool isEndDrawerOpen(){
    return _endDrawerOpened;
  }
```
or getters or whatever format is preferred.
Seems like it should be harmless and add value, but maintainer knows best.
Please consider.

**Comment by zoechi** [comment]
Using a custom DrawerController should allow you to do that. 
See for example https://github.com/flutter/flutter/issues/21272#issuecomment-417643365

**Comment by morphiak** [comment]
Thanks for that, (I also bookmarked https://flutter.io/support/)

When I put 
` bool drawerOpen;
  void setDrawerOpened(bool isOpen) {
    drawerOpen = isOpen;
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      drawer: DrawerController(
          child: Drawer(
            child: Text("SS"),
          ),
          drawerCallback: setDrawerOpened,
          alignment: DrawerAlignment.start),
`
I get the same undesired tint screen, then drawer behavior as described above, hitting setDrawerOpen on the second swipe. (perhaps there are now two DrawerControllers?)
After a quick look at the scaffold.dart usage (line 1458), I tried
`    return new Scaffold(
//      drawer: 
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: DrawerController(
          child: Drawer(
            child: Text("SS"),
          ),
          drawerCallback: setDrawerOpened,
          alignment: DrawerAlignment.start),
`
which has the expected drawer behavior, and hits the callback,but you can't put anything on the screen :(
Put it inside a column widget and the drawer doesn't work.
Unless I'm missing some pattern for adding controllers to widget trees, this seems broken to me.
The normal pattern would be to have the controller as a named parameter to Drawer would it not ? Not to mention simple and intuitive (as too are getters ;).

**Comment by zoechi** [comment]
Sorry to hear. 
I'm merging with #21272 then.
Make sure you upvote to raise it's priority.

**Comment by rhymelph** [comment]
Hi,I want to you can try this.
`bool drawerOpen;

  void setDrawerOpened(bool isOpen) {
    drawerOpen = isOpen;
  }

  @override
  Widget build(BuildContext context) {
    return new DrawerWidget(
      callback: setDrawerOpened,
  );

class DrawerWidget extends StatefulWidget {
  DrawerCallback callback;
  DrawerWidget({this.callback});

  @override
  _DrawerWidgetState createState() => _DrawerWidgetState();
}

class _DrawerWidgetState extends State<DrawerWidget> {

  @override
  void initState() {
    widget.callback(true);
    super.initState();
  }
  @override
  void dispose() {
    widget.callback(false);
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Drawer(
            child: Text("SS"),
          );
  }
}
`

**Comment by rhymelph** [comment]
Hi,I want to you can try this.
```dart
  bool drawerOpen;

  void setDrawerOpened(bool isOpen) {
    drawerOpen = isOpen;
  }

  @override
  Widget build(BuildContext context) {
    return new DrawerWidget(
      callback: setDrawerOpened,
    );
  }


class DrawerWidget extends StatefulWidget {
  DrawerCallback callback;

  DrawerWidget({this.callback});

  @override
  _DrawerWidgetState createState() => _DrawerWidgetState();
}


class _DrawerWidgetState extends State<DrawerWidget> {

  @override
  void initState() {
    widget.callback(true);
    super.initState();
  }

  @override
  void dispose() {
    widget.callback(false);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: Text("SS"),
    );
  }
}

```
