### ISSUE TITLE
tab contanins Scaffold and textfield then page can not show correctly

### ISSUE THREAD

**Issue by JarVZhao** [flutter/flutter#23639]
my main page have  a Scaffold   with 3 tabs using bottomNavigationBar and PageView ,and one of my tab page have  Scaffold  too,but when i use textfield in my tab ,then when i enter something,the Android keyboard shows,then the page becomes unnormal,when i remove the Scaffold  in my tab ,it becomes normal.  so i am sure it is the two Scaffold  problem.  is it a bug or  any other solution?  I really have to use two Scaffold  .

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
