### ISSUE TITLE
'MySQL' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by dawningtruth** [flutter/flutter#23642]
This issue was closed but the zip file still reproduces the error. I don't think cloning a git is an adequate solution. And it fact it does not work on my windows installation. Please create the correct zip that works.

**Comment by zoechi** [comment]
Merging with #17907 
I don't see why this would be a Flutter issue.
If you can provide any information that would allow to diagnose the issue to #17907 I'll reopen.
