### ISSUE TITLE
Tooltips should not be obscured by the keyboard

### ISSUE THREAD

**Issue by stemarco** [flutter/flutter#23666]
Tooltips by default  appear below the child widget.  On mobile devices this location is often obscured by the users finger. Instead of the hardcoded preferBelow: true, can it be either false or obtained from the Theme? 

Edited by bleroux :
The P4 label for this issue is related to the [following comment](https://github.com/flutter/flutter/issues/23666#issuecomment-442104604) about tooltips being obscured by the keyboard.

**Comment by zoechi** [comment]
Is this about material or cupertino, or both?
Please add the output of `flutter doctor -v`.

**Comment by saurik** [comment]
FWIW, for a floating action button this tooltip is not only obscured by the user's finger, it is also obscured by the keyboard.

![img_0013](https://user-images.githubusercontent.com/36743/49092664-5b9d3880-f217-11e8-814d-4ce85bac3c50.jpg)

**Comment by eseidelGoogle** [comment]
Looks like the specs are silent on this:
https://material.io/components/tooltips/#

**Comment by bleroux** [comment]
This issue asks for a way to set `preferBelow` globally.
Since Flutter 1.9, this is possible using `TooltipThemeData` :

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark().copyWith(
        tooltipTheme: const TooltipThemeData(preferBelow: true),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const TextField(),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        tooltip: 'Addition',
        onPressed: _incrementCounter,
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

The second part of this issue is about tooltips being obscured by the keyboard.
This is still reproducible in Flutter 2.10.
