### ISSUE TITLE
Incorrect clippling while deleting multiple lines of TextField

### ISSUE THREAD

**Issue by julianstokkur** [flutter/flutter#23679]
While deleting multiple lines in a TextField at some point you can see that the TextField draws text lines on top of it instead of clipping them, this also happened with an older version of Flutter but in Mac OS X

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)

This is the behavior

![device-2018-10-29-121236](https://user-images.githubusercontent.com/33767663/47667689-395ac100-db6c-11e8-82fd-c06499f50f5d.gif)

And I construct the widget with this function (In this case maxLines is 6)

```
Widget _buildTextField(
          String hint, int maxLines, TextEditingController controller) =>
      TextField(
        maxLines: maxLines,
        controller: controller,
        decoration: InputDecoration(
          hintText: hint,
          border: OutlineInputBorder(
            borderSide: BorderSide(
              color: Colors.grey,
            ),
          ),
        ),
      );
```

The widget structure for the screen is

```
SafeArea
  Padding
    Column
      TextField
      SizedBox
      TextField (Description widget with behavior}
      SizedBox
      Container
        Text
      SizedBox
      Expanded
        Container
          ListView.builder
```

**Comment by zoechi** [comment]
I believe this is a dup of #14121
