### ISSUE TITLE
styling dropdown menu

### ISSUE THREAD

**Issue by CedSW** [flutter/flutter#23681]
Hello, I'm trying to figure out how to style a dropdown menu because I don't like the default behavior (menu appears over dropdown button on selected item position). Unfortunately, I didn't find any way how to change this. I would like to display the menu underneath the button. For example the bootstrap dropdown works like that. Thank you

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

If it turns out to be a Flutter bug or missing feature, please add a comment to get it reopened or create a new issue. Thanks!

**Comment by zoechi** [comment]
See also #23865
