### ISSUE TITLE
Device IMEI in flutter

### ISSUE THREAD

**Issue by MahmmoudSabri** [flutter/flutter#23694]
how can i get device IMEI in flutter

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by amreniouinnovent** [comment]
@zoechi I wonder why the flutter team merges all plugins into 1 repo and we could not be able to open issues there? 
Only for opening an issue related to a plugin we have to go to flutter repo itself!!!
