### ISSUE TITLE
Collapse long stack traces in the logs into a disclosure widget

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2370]
Sometimes Flutter exceptions are hundreds of stack frames deep. It'd be good if when Atom detected a stack trace was more than a few lines long, it hid the rest under a disclosure triangle or something.

**Comment by jimbeveridge** [comment]
Just to add some color, showing the first few (5?) stack frames is good. Everything after that would be better collapsed.

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin. Not sure how that will display long stack traces, but something to keep an eye on.

cc @devoncarew
