### ISSUE TITLE
Add Flutter-specific platform headers to requests sent to Firebase

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#23701]
@kroikie is tracking adding a way for us to separate requests generated from FlutterFire iOS/Android plugins from the ones made from unwrapped ObjC/Swift/Java/Kotlin Firebase SDKs.

**Comment by zoechi** [comment]
May I ask what what this is used for?
Should https://github.com/fluttercommunity/firebase_flutter_sdk do this as well which is Flutter but doesn't use native APIs?

**Comment by kroikie** [comment]
This has been implemented! :)

**Comment by kroikie** [comment]
@eseidelGoogle

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/590. Any further collaboration will be done there.
