### ISSUE TITLE
Using CupertinoTabScaffold without a TabBar

### ISSUE THREAD

**Issue by davbaron** [flutter/flutter#23703]
Hello, I would like to revisit parts of a prior case, [Using TabBar within CupertinoTabScaffold](https://github.com/flutter/flutter/issues/18275). Specifically, I would like to present a hybrid UI for my app, whereby I use a Material Drawer for navigation, though with the 'parallel navigation' benefits of a CupertinoTabScaffold, minus the actual TabBar at the bottom of the screen.  In other words, I do not really want to 'push' screens via the Drawer, but instead want to switch the current view of a tabBuilder's CupertinoTabViews. 

I have already done some of this, i.e., I have a CupertinoTabScaffold, with a tabBar and tabBuilder, with several tabs. Each tab contains a Material Scaffold, within which sits a Drawer.  Using the Drawer, I can programmatically set the 'current view' within the tabBar. All works fine, however I do not want to show a tabBar at all. I understand that might break with iOS design norms, however from a Material perspective, users can frequently navigate via a Drawer, without an accompanying tab bar. And I would like that navigation to be a 'view-switch', with parallel navigation stacks within each view, versus the 'push-to-screen' that is typically used, and which wipes out prior navigation history.

BTW - I did try wrapping the tabBar in an OffScreen widget, however the tabBar must be an actual CupertinoTabBar, not an OffScreen widget that contains that tab bar as a child.

The prior case, opened by @adriancmurray, was commented on several times by @xster and @Hixie . There seemed to be suggestions that there might be some way to gain the parallel nav aspects of the CupertinoTabScaffold, but without using it. Any guidance here would be appreciated.

In various web toolkits, there is usually some sort of widget called a 'multi-view', which is really just a collection of DIVs, one of which is visible. The API to the multi-view allows the user to set the current view (thus hiding the others). There is no reliance on having a visual 'tab' UI - the 'currentIndex' is part of the multi-view, not some tab bar. As I mentioned, comments in the prior case implied that one could use the parallel capabilities by embedding CupertinoTabViews within a standard Material Scaffold. What is not clear though is how to 'switch' between views [without having an explicit, visual tabBar to manage the currentIndex]. 

Is this something that can be done with what we have today? Or, is subclassing the CupertinoTabBar a better direction, adding the option to somehow hide the visual rendering of the bar (and would that still work with the CupertinoTabScaffold)? Or should there be some kind of generic 'MultiView' widget, containing a list of TabViews, each maintaining its own nav history, and with programmatic control over currentIndex?

Thank you!

**Comment by zoechi** [comment]
Have you tried to ask on StackOverflow. 
GitHub issues are for bug reports and feature requests. 
For support questions one of the other channels listed at http://flutter.io/support should be used.

**Comment by xster** [comment]
The CupertinoTabScaffold doesn't actually do that parallel navigation function. You can use a Material Scaffold with a Material TabBar. For content, you can use an IndexedStack with a CupertinoTabView inside. Then you'll have parallel navigators with different tabs.

**Comment by xster** [comment]
Please let me know too if reading the API docs, things are hard to figure out or if any other documentations could have made this easier.
