### ISSUE TITLE
Slide Transition from bottom to top Repainting systemNavigationBarColor

### ISSUE THREAD

**Issue by pczn0327** [flutter/flutter#23715]
This is my first time posting in Github, apologise if confusing content.

I have to my system navigation bar color set in main.dart as follow:
`SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(`
`        statusBarColor: Colors.white,`
`        systemNavigationBarColor: Colors.white,`
`        systemNavigationBarIconBrightness: Brightness.dark));`

However, when I tried to write my own transitionBuilder from bottom up for page route, I realised the System Navigation Bar Color changed back to default.
Widget Code as follow:
`        Navigator.push(context,`
`            PageRouteBuilder(`
`                opaque: false,`
`                pageBuilder: (BuildContext context, _, __) {`
`                  return FilterPage();`
`                },`
`                transitionsBuilder:`
`                    (___, Animation<double> animation, ____, Widget child) {`
`                  return SlideTransition(`
`                    position: Tween<Offset>(`
`                      begin: Offset(0.0, 1.0),`
`                      end: Offset(0.0, 0.0)`
`                    ).animate(animation),`
`                    child: child);`
`}));`

Flutter doctor as below: 
[✓] Flutter (Channel master, v0.10.2-pre.99, on Mac OS X 10.14 18A391, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (2 available)

The FAB will route trigger the page route animation:
![screenshot_1540874578](https://user-images.githubusercontent.com/23042145/47696352-60cf8d80-dc41-11e8-81b7-617aa6d2d4e5.png)

Once clicked, the System Navigation Bar color changed back to default (black):
![screenshot_1540874830](https://user-images.githubusercontent.com/23042145/47696487-eeab7880-dc41-11e8-86f7-dd1957c087d9.png)

**Comment by pczn0327** [comment]
Not sure if this is the way, but I solved with by added fade transition to the child of slide transition:
`return SlideTransition(`
`                    position: Tween<Offset>(`
`                      begin: Offset(0.0, 1.0),`
`                      end: Offset(0.0, 0.0)`
`                    ).animate(animation),`
`                    child: FadeTransition(`
`                      opacity: Tween<double>(`
`                        begin: 0.0,`
`                        end: 1.0`
`                      ).animate(animation),`
`                      child: child));`

**Comment by pablanka** [comment]
I'm facing the same issue and I can confirm this is the solution: https://github.com/flutter/flutter/issues/23715#issuecomment-434171893
