### ISSUE TITLE
 Get the display width of the Text before drawing.

### ISSUE THREAD

**Issue by nightwolf-chen** [flutter/flutter#23718]
Problem: How to get the display width of the Text before drawing

 Description: We have a requirement to not display a certain text when it's too long for text container.

 What we tried:

- Get the size of the Widget in the first frame callback (because the child widget size is larger than the parent widget, an exception will be reported)

- Obtaining the text's overflow field information (Text's overflow field is a private property which cannot be obtained directly; We tried to calculate the overflow value by ourselves but failed )

-  Put the target text widget inside a scrollView and then calculate the size of the corresponding widget in the first frame callback. (The solution works, but the hierarchical UI level becomes deeper and the implementation is complicated)
Expectations:
Can Flutter officially provide an API that calculates widget size in advance or an Open Overflow property to read.

**Comment by roychan2016** [comment]
I often encounter this kind of problem in the project.
I hope that Google can give an official solution as soon as possible.

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/52659759/how-can-i-get-the-size-of-the-text-widget-in-flutter/52991124#52991124 
  https://github.com/flutter/flutter/issues/18431#issuecomment-396990020
  https://github.com/flutter/flutter/issues/19264
  https://github.com/flutter/flutter/issues/21822

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
