### ISSUE TITLE
EditableText does not respond to the Enter key on Xiaomi 2s(Android Device)

### ISSUE THREAD

**Issue by nightwolf-chen** [flutter/flutter#23719]
Problem: On Android Xiaomi 2s, EditableText does not respond to the Enter key.

The inputConnectionAdaptor's `sendKeyEvent(KeyEvent event)` method will be called when the Enter key is pressed on a normal Android phone.

But when the Enter key is pressed on the Xiaomi 2s mobile phone, the `SendKeyEvent(KeyEvent event)` method of the `InputConnectionAdaptor` will not be called. Only the `PerformEditorAction(int actionCode)` method of the `InputConnectionAdaptor` is called, and the action code of the input parameter is 1. According to the current implementation of Flutter dart code, `EditableText` will not respond to this action which causes Flutter to fail to add a new line for text view when the Enter key is pressed.

Please check out the code below:

```dart
  @override
  Void performAction(TextInputAction action) {
    Switch (action) {
      Case TextInputAction.done:
......
        Break;
      Case TextInputAction.newline:
        // Do nothing for a "newline" action: the newline is already inserted.
        Break;
    }
  }
```

```
Building flutter tool...
[KWLM]:[doctor, -v]
[✓] Flutter (Channel xy_beta_v0.5.6, v0.5.7-pre.48, on Mac OS X 10.13.2 17C88, locale zh-Hans-CN)
    • Flutter version 0.5.7-pre.48 at /Users/user/Project/Flutter/copy/project/flutter
    • Framework revision ab64a539f0 (12 days ago), 2018-10-18 20:55:38 +0800
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by duyb** [comment]
部分Android机型失效

**Comment by GaryQian** [comment]
Do you know if this happens on other third party keyboards? Also, what keyboard are you using to reproduce this? We have seen cases where some keyboards do not trigger the SendKeyEvent code path, instead using an alternative way to trigger some keys.

**Comment by TahaTesser** [comment]
Hi @nightwolf-chen 
Please provide the details asked above and Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
