### ISSUE TITLE
When playing video with surfaceview,the problem has happened.

### ISSUE THREAD

**Issue by hschenzhimin** [flutter/flutter#23729]
I did not use PlatformView when playing videos on Android 4.4, as shown in the following code. 
```
ViewGroup parent = ((ViewGroup) mRegistrar.view().getParent());
parent.addView(surfaceView);
```

I want to draw some widgets developed with dart on the playback area. If the surfaceview is below the flutterview, the surfaceview cannot be displayed. 
As shown in the following code, if you are above the flutterview, the widget on the playback area cannot be displayed. Is there any good solution?
```
surfaceView.setZOrderMediaOverlay(true);
surfaceView.setZOrderOnTop(true);
parent.bringChildToFront(surfaceView);
```

**Comment by zoechi** [comment]
That looks like a how-to question that is better asked on StackOverflow.

**Comment by hschenzhimin** [comment]
Ok, I have already asked questions on stackoverflow.
https://stackoverflow.com/questions/53062062/when-playing-video-with-surfaceview-the-problem-has-happened


> 
> 
> That looks like a how-to question that is better asked on StackOverflow.

**Comment by hschenzhimin** [comment]
@zoechi I have solved this problem. If you use dart to draw widgets on SurfaceView, not only those widgets need to be transparent, but also FlutterView needs to be transparent so that the content of Surfaceview can be displayed. FlutterView needs to call enableTransparentBackground.

> 
> 
> Ok, I have already asked questions on stackoverflow.
> https://stackoverflow.com/questions/53062062/when-playing-video-with-surfaceview-the-problem-has-happened
> 
> > That looks like a how-to question that is better asked on StackOverflow.
