### ISSUE TITLE
The previous deleted code of the flutter project shows when it is run first time in my phone

### ISSUE THREAD

**Issue by yash365** [flutter/flutter#23724]
The previous deleted code of the flutter project shows when it is run first time in my phone

- I have to restart the app again then it works fine. 
- I don't know what the issue i tried deleted app cache and use again but nothing works.
- I run the flutter app is my smartphone having android version 7.0

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by yash365** [comment]
> Please add the output of `flutter doctor -v`.

C:\Users\sam>flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale en-IN)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (7 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\AndroidStudioSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\AndroidStudioSDK
    • Java binary at: C:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by zoechi** [comment]
Are you still seeing this?

**Comment by yash365** [comment]
Know doesn't the same issue...but when we run the app in flutter perform some changes and hot restart the  app and disconnect the phone i see the app without changes after disconnecting it

**Comment by zoechi** [comment]
I'm closing then. 

> perform some changes and hot restart the app and disconnect the phone i see the app without changes

This is a known limitation #12174
