### ISSUE TITLE
Flutter Build Apk: Build Failed to notify build completion listener. (com.android.tools.lint.LintCoreApplicationEnvironment)

### ISSUE THREAD

**Issue by mzage31** [flutter/flutter#23727]
Hi, I have flutter installed and working with no issues, I can code and build debug apk's and hot reload but I can't build a release version of my application.

Here is "flutter doctor -v" and "flutter build apk" information from CommandPrompt.
**C:\eew>flutter doctor -v**
```
**[√]** Flutter (Channel dev, v0.10.1, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 0.10.1 at C:\src\flutter
    • Framework revision 6a3ff018b1 (11 days ago), 2018-10-18 18:38:26 -0400
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

**[√]** Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Scott Robertson\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

**[√]** Android Studio (version 3.1)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

**[√]** VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.19.0

**[√]** Connected device (1 available)
    • SM G610F • 5203698b48575407 • android-arm • Android 7.0 (API 24)

• No issues found!
```

**C:\eew>flutter build apk**
```
Initializing gradle...                                       1.9s
Resolving dependencies...                                    4.5s
Gradle task 'assembleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build completion listener.
> com.android.tools.lint.LintCoreApplicationEnvironment

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Gradle task 'assembleRelease'... Done                       37.1s
Gradle task assembleRelease failed with exit code 1
```

**Comment by zoechi** [comment]
Is this also when you create a new app or only with an existing app?

**Comment by mzage31** [comment]
yes, it also happens when I create a new app using the following command
**C:\>flutter create \**

**Comment by mzage31** [comment]
**Here is "flutter build -v apk" information**

```
[        ] Gradle task 'assembleRelease'...
[   +3 ms] executing: [C:\eew\android\] C:\eew\android\gradlew.bat -Pverbose=true
-Ptarget=lib/main.dart -Ptrack-widget-creation=false -Ptarget-platform=android-arm assembleRelease
[+29288 ms] [  +10 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +119 ms] [ +148 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [   +1 ms] origin/dev
[        ] [        ] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +122 ms] [ +129 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] dev
[        ] [        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[ +126 ms] [ +119 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[        ] [        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[ +101 ms] [ +107 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] [        ] 6a3ff018b199a7febbe2b5adbb564081d8f49e2f
[        ] [        ] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%ar
[ +112 ms] [ +110 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] [        ] 12 days ago
[        ] [        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long
--tags
[ +103 ms] [ +110 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v0.10.1-0-g6a3ff018b
[+1452 ms] [+1451 ms] Building bundle
[   +2 ms] [        ] Writing asset files to
C:\eew\build\app\intermediates\flutter\release/flutter_assets
[ +173 ms] [ +179 ms] Wrote C:\eew\build\app\intermediates\flutter\release/flutter_assets
[  +10 ms] [  +10 ms] "flutter bundle" took 1,433ms.
[+1063 ms] 22 actionable tasks: 5 executed, 17 up-to-date
[ +201 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Failed to notify build completion listener.
[        ] > com.android.tools.lint.LintCoreApplicationEnvironment
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to
get more
           log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 32s
[ +554 ms] Gradle task 'assembleRelease'... (completed)
[  +31 ms] "flutter apk" took 44,753ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:399:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:300:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:41:10)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:44:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:383:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

**Comment by mzage31** [comment]
CAN ANYONE PLEASE HELP ME WITH THIS ?????

**Comment by zoechi** [comment]
What do you get when you execute 
```
C:\eew\android\gradlew.bat --version
```

**Comment by mzage31** [comment]
**C:\eew>C:\eew\android\gradlew.bat --version**

```

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Windows 10 10.0 amd64
```

**Comment by mzage31** [comment]
Where can i get Gradle 3.1.2 version? I searched for it in gradle.org site but i couldn't find this version.

**Comment by mzage31** [comment]
I tried to change classpath from
`com.android.tools.build:gradle:3.1.2`
to
`com.android.tools.build:gradle:3.2.1`

but i get another error :
`* Where:
Build file 'E:\flutter_android_studio\flutter_app\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.NoClassDefFoundError: com/android/tools/lint/gradle/api/ToolingRegistryProvider
`

**Comment by mzage31** [comment]
I created a new project, these are `build.gradle` files:

**android\build.gradle**
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**android\app\build.gradle**

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 27

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.mzage.englishessentialwords"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../../'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

**Comment by mzage31** [comment]
Can you share your own _flutter SDK_ or a _project_ that you have built using `flutter create` command?

**Comment by mzage31** [comment]
I found this file 
`https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/cli/src/main/java/com/android/tools/lint/LintCoreApplicationEnvironment.java`

is it the file i'm having problem with?
if so, where is it placed?
i can't find it in android sdk and android studio and gradle files.

**Comment by zoechi** [comment]
Can you please try
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
```
or
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```

in `android/gradle/wrapper/gradle-wrapper.properties`?

**Comment by mzage31** [comment]
Tried it, didn't make any difference.
i tried to change flutter to `master channel` and downloading everything with `flutter update` command, then changing back to `dev channel` and downloading everything again with the same command.
now it gives me this error:
`Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).`

**Comment by zoechi** [comment]
> now it gives me this error:

That's not too bad because that's a known problem and rather indicates that your project is good.
See #23404 for more details.

**Comment by mzage31** [comment]
Tried
```
flatDir{
	dirs 'C:/myrepo'
}
maven{
	url 'https://dl.google.com/dl/android/maven2'
}
google()
jcenter()
```
and all the combinations, but i get the same error over and over again

**Comment by mzage31** [comment]
after switching to master channel and back to dev channel and redownloading everything with flutter upgrade and changing `flutter.gradle` file repositories to:
```
repositories {
		maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
		google()
        jcenter()
        
    }
```
and `c:/eew/android/build.gradle` file content to:
```
buildscript {
    repositories {
		maven{
			url 'https://dl.google.com/dl/android/maven2'
		}
		google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

Me and @zoechi finally solved the problem.
now i can build release versions with no problem.

thank you very much my friend 👍 🥇

**Comment by sunderrrrrrrr345** [comment]
@zoechi i am facing same problem...

sunder@sunder-Vostro-14-3468:~/Android/petskart$ flutter clean
Deleting 'build/'.
Deleting '/home/sunder/Android/petskart/.dart_tool/'.
sunder@sunder-Vostro-14-3468:~/Android/petskart$ flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              8.3s
Resolving dependencies...                                          46.1s
Running Gradle task 'assembleRelease'...                                                                        /home/sunder/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:627: warning: [deprecation] setTimestampsInSnapshotsEnabled(boolean) in Builder has been deprecated
            builder.setTimestampsInSnapshotsEnabled(                                                               
                   ^                                                                                               
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
1 warning                                                                                                          
/home/sunder/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+7/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java:59: warning: [deprecation] CONNECTIVITY_ACTION in ConnectivityManager has been deprecated
        .registerReceiver(receiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));                    
                                                                        ^                                          
1 warning                                                                                                          
/home/sunder/.pub-cache/hosted/pub.dartlang.org/file_picker-1.3.8/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:53: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated
                    return Environment.getExternalStorageDirectory() + "/" + split[1];                             
                                      ^                                                                            
/home/sunder/.pub-cache/hosted/pub.dartlang.org/file_picker-1.3.8/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:186: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated
        Uri uri = Uri.parse(Environment.getExternalStorageDirectory().getPath() + File.separator);                 
                                       ^                                                                           
2 warnings                                                                                                         
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+3/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/flutter_multiple_image_picker-0.0.1/android/src/main/java/maugost/fluttermultipleimagepicker/FlutterMultipleImagePickerPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: Some input files use unchecked or unsafe operations.                                                         
Note: Recompile with -Xlint:unchecked for details.                                                                 
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     220.4s (!)
Gradle task assembleRelease failed with exit code 1
sunder@sunder-Vostro-14-3468:~/Android/petskart$ flutter clean
Deleting 'build/'.
Deleting '/home/sunder/Android/petskart/.dart_tool/'.
sunder@sunder-Vostro-14-3468:~/Android/petskart$ flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              1.7s
Resolving dependencies...                                           3.8s
Running Gradle task 'assembleRelease'...                                                                        /home/sunder/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+7/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java:59: warning: [deprecation] CONNECTIVITY_ACTION in ConnectivityManager has been deprecated
        .registerReceiver(receiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));                    
                                                                        ^                                          
1 warning                                                                                                          
/home/sunder/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:627: warning: [deprecation] setTimestampsInSnapshotsEnabled(boolean) in Builder has been deprecated
            builder.setTimestampsInSnapshotsEnabled(                                                               
                   ^                                                                                               
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
1 warning                                                                                                          
/home/sunder/.pub-cache/hosted/pub.dartlang.org/file_picker-1.3.8/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:53: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated
                    return Environment.getExternalStorageDirectory() + "/" + split[1];                             
                                      ^                                                                            
/home/sunder/.pub-cache/hosted/pub.dartlang.org/file_picker-1.3.8/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:186: warning: [deprecation] getExternalStorageDirectory() in Environment has been deprecated
        Uri uri = Uri.parse(Environment.getExternalStorageDirectory().getPath() + File.separator);                 
                                       ^                                                                           
2 warnings                                                                                                         
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+3/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/flutter_multiple_image_picker-0.0.1/android/src/main/java/maugost/fluttermultipleimagepicker/FlutterMultipleImagePickerPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: Some input files use unchecked or unsafe operations.                                                         
Note: Recompile with -Xlint:unchecked for details.                                                                 
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     168.3s (!)
Gradle task assembleRelease failed with exit code 1
sunder@sunder-Vostro-14-3468:~/Android/petskart$ flutter clean
Deleting 'build/'.
Deleting '/home/sunder/Android/petskart/.dart_tool/'.
sunder@sunder-Vostro-14-3468:~/Android/petskart$ flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0.9s
Resolving dependencies...                                           2.7s
Running Gradle task 'assembleRelease'...                                                                        Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.13+1/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+7/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.1.1+3/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.4/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: /home/sunder/.pub-cache/hosted/pub.dartlang.org/flutter_multiple_image_picker-0.0.1/android/src/main/java/maugost/fluttermultipleimagepicker/FlutterMultipleImagePickerPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                                                                 
Note: Some input files use unchecked or unsafe operations.                                                         
Note: Recompile with -Xlint:unchecked for details.                                                                 
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     219.9s (!)
Gradle task assembleRelease failed with exit code 1

**Comment by sunderrrrrrrr345** [comment]
How can i release apk file?

**Comment by Rajdeep100** [comment]
"flutter clean" worked for me, but this problem persists, what is the root problem?
