### ISSUE TITLE
FlutterViewController can't set defaultRouteName by calling setInitialRoute.

### ISSUE THREAD

**Issue by ryansong** [flutter/flutter#23736]
The APP want to get FlutterViewController instance by calling setInitialRoute: . But the flutter always get the window.defaultRouteName as "/".  How can I assign the defaultRouteName to fluter to get FlutterViewController with flutter widget.

## Steps to Reproduce

```dart
void main() => runApp(_widgetForRoute(window.defaultRouteName));

Widget _widgetForRoute(String route) {
  switch (route) {
    case '/followus':
      return new FollowUs();
    case '/feedback':
      return new FeedBackUs();
```
```
@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
    [button addTarget:self
               action:@selector(handleButtonAction)
     forControlEvents:UIControlEventTouchUpInside];
    [button setTitle:@"Press me" forState:UIControlStateNormal];
    [button setBackgroundColor:[UIColor blueColor]];
    button.frame = CGRectMake(80.0, 210.0, 160.0, 40.0);
    [self.view addSubview:button];
}

- (void)handleButtonAction  {
    FlutterViewController* flutterViewController = [[FlutterViewController alloc] init];
    [flutterViewController setInitialRoute:@"/feedback"];
    [self presentViewController:flutterViewController animated:false completion:nil];
}
```

```
flutter analyze
Analyzing tbj-flutter-plugin...
No issues found! (ran in 2.8s)
```

```
[✓] Flutter (Channel master, v0.10.2-pre.103, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.10.2-pre.103 at /usr/local/flutter
    • Framework revision 262faf906f (74 minutes ago), 2018-10-30 15:06:08 +0100
    • Engine revision 3a67757300
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ryan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected device (3 available)
    • iPhone 7      • 7e30d5cefe20e2e0d835de2261c15cbfea691252 • ios • iOS 11.3.1
    • iPhone 6      • 2BEB3B83-CFC4-4BFF-850D-D7FB9B019A2A     • ios • iOS 8.2 (simulator)
    • iPhone XS Max • FDFB6413-7D10-4BD5-82FA-B75AF90E9885     • ios • iOS 12.0 (simulator)
```

**Comment by zoechi** [comment]
Related #18500, #18411

**Comment by jamesderlin** [comment]
cc @dnfield

**Comment by ryansong** [comment]
I tried the way in #18411 , as the last comment says It may be fixed before.


Well, I fix it by reset the code to def1d8056,  so it seems some updating has broke it.

**Comment by dnfield** [comment]
Unfortunately, the commit that fixes this for you isn't ready for prime time - it breaks a couple things that we can't break just yet.

Chances are, if having the Xcode backend refactor fixes things it's because you're getting caught in one of the several bugs that the current implementation has.  Those are a little hard to diagnose and become environment specific (the order of commands you run from the CLI can change settings that end up impacting Add2App unintentionally).

I'm working to reland that, hopefully soon.

**Comment by ryansong** [comment]
Thank you for your reply, hope this isssue get fixed soon . 
And the commit https://github.com/flutter/flutter/commit/def1d80566024950f5e7aa748e5680e7f1480bcb may not refer to this issue, it just works when I revert code to it.

**Comment by dnfield** [comment]
Is this still an issue for you on master?

**Comment by dnfield** [comment]
I'm now reproducing this locally.. investigating.

**Comment by dnfield** [comment]
Landed in framework as of https://github.com/flutter/flutter/pull/24038

Note there's another issue that you may see now that this works, which will be resolved by https://github.com/flutter/flutter/pull/24039

**Comment by kidzss** [comment]
I solved the problem.
//=======================

@interface XXFlutterViewController : FlutterViewController

@EnD

(void)viewDidLoad {
[super viewDidLoad];
// Do any additional setup after loading the view.
FlutterEngine *flutterEngine = self.engine;

[GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
//custom futter plugin
[XXXFlutterBridge registerWithRegistry:flutterEngine];
}

//open flutter vc
XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
[flutterViewController setInitialRoute:@"xxxxx/xxxx"];

**Comment by ailic88** [comment]
> I solved the problem.
> //=======================
> 
> @interface XXFlutterViewController : FlutterViewController
> 
> @EnD
> 
> (void)viewDidLoad {
> [super viewDidLoad];
> // Do any additional setup after loading the view.
> FlutterEngine *flutterEngine = self.engine;
> 
> [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
> //custom futter plugin
> [XXXFlutterBridge registerWithRegistry:flutterEngine];
> }
> 
> //open flutter vc
> XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> [flutterViewController setInitialRoute:@"xxxxx/xxxx"];

This solution has very bad performance. App gets stuck few second until engine get initialized.

**Comment by joshuaton** [comment]
i get the same problem, how to fix?
