### ISSUE TITLE
Version Solving failed.

### ISSUE THREAD

**Issue by shahsalonee** [flutter/flutter#23731]
I'm new to Flutter and can't seem to understand what should I do for the following issue that I'm facing.

The error I'm getting is:
"The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044.

Because music_player depends on fluttery >=0.0.2 which requires SDK version >=1.0.0 <2.0.0, version solving failed.

pub upgrade failed (1)"

My pubspec.yaml file looks like this:

name: music_player
description: Flutter Challenge - Music Player

dependencies:
  flutter:
    sdk: flutter

  / The following adds the Cupertino Icons font to your application.
  / Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  fluttery: 0.0.5

  fluttery_audio: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

/ For information on the generic Dart part of this file, see the
/ following page: https://www.dartlang.org/tools/pub/pubspec

/ The following section is specific to Flutter.
flutter:

  / The following line ensures that the Material Icons font is
  / included with your application, so that you can use the icons in
  / the material Icons class.
  uses-material-design: true

  / To add assets to your application, add an assets section, like this:
  / assets:
  /  - images/a_dot_burr.jpeg
  /  - images/a_dot_ham.jpeg

  / An image asset can refer to one or more resolution-specific "variants", see
  / https://flutter.io/assets-and-images//resolution-aware.

  / For details regarding adding assets from package dependencies, see
  / https://flutter.io/assets-and-images//from-packages

  / To add custom fonts to your application, add a fonts section here,
  / in this "flutter" section. Each entry in this list should have a
  / "family" key with the font family name, and a "fonts" key with a
  / list giving the asset and other descriptors for the font. For
  / example:
  / fonts:
  /   - family: Schyler
  /     fonts:
  /       - asset: fonts/Schyler-Regular.ttf
  /       - asset: fonts/Schyler-Italic.ttf
  /         style: italic
  /   - family: Trajan Pro
  /     fonts:
  /       - asset: fonts/TrajanPro.ttf
  /       - asset: fonts/TrajanPro_Bold.ttf
  /         weight: 700
  /
  / For details regarding fonts from package dependencies,
  / see https://flutter.io/custom-fonts//from-packages

**Comment by zoechi** [comment]
> Because music_player depends on fluttery >=0.0.2 which requires SDK version >=1.0.0 <2.0.0, version solving failed.

says it all.
`music_player` depends on `fluttery` and `fluttery` depends on an old Dart version.
You need to raise the issue with `music_player` and `fluttery` to have them updated them to recent versions.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
