### ISSUE TITLE
Surprising behavior of maxLines: null, overflow:ellipsis in the Text widget

### ISSUE THREAD

**Issue by akireyev** [flutter/flutter#23733]
```
Text("<long text that spans many lines>", overflow: TextOverflow.ellipsis, maxLines: null)
```
Renders just a single line of text, and ellipsizes out the rest.
But
```
Text("<long text that spans many lines>", overflow: TextOverflow.ellipsis, maxLines: 1000)
```
Renders multiple lines.

**Comment by zoechi** [comment]
Perhaps

> If this is null, but there is an ambient DefaultTextStyle that specifies an explicit number for its DefaultTextStyle.maxLines, then the DefaultTextStyle value will take precedence.

https://docs.flutter.io/flutter/widgets/Text/maxLines.html

**Comment by akireyev** [comment]
There's no DefaultTextStyle override for maxLines, I have verified that in the debugger. `maxLines = null` goes all the way down to the TextPainter, which is actually the source of this behavior.

**Comment by zoechi** [comment]
@akireyev sorry, wasn't aware you're a Googler

**Comment by justinmc** [comment]
Here's what the current behavior is for all relevant combinations of `overflow` and `maxLines`:

|  | maxLines: null | maxLines: 1000 |
| ------------- | ------------- | ------------- |
| **overflow: null** | many lines | many lines |
| **overflow: ellipsis** | one line | many lines |

The surprising behavior is that one case where `Text` shows a single line.  I'll try to gauge whether or not that's expected and what it would take to change if not.

**Comment by justinmc** [comment]
This came up again in https://github.com/flutter/flutter/issues/33133.

Unassigning myself for the moment, but I'd like to get a solution for this.  I'm not sure if that's a breaking change or some other way to allow `maxLines: null` and multiline ellipsis.

For now as a workaround, if you specify the exact number of lines you can get an ellipsis and multiline.

**Comment by TahaTesser** [comment]
Hi @justinmc @akireyev  
You think this issue still valid?
if `maxLines: 1000` shouldn't render multiple lines?
On reproducing the issues, it makes sen to me
Thank you

**Comment by justinmc** [comment]
I think that considering this issue is so old and hasn't attracted a whole lot of attention, we can close it.  People seem to be figuring out how to get the behavior they want out of this.

I still think it's strange though, so if anyone has any ideas about this in the future, feel free to comment and ask me to reopen.  I think that it's strange that `maxLines: null` and `TextOverflow.ellipsis` renders only one line.  `TextOverflow.fade` correctly handles multiple lines.
