### ISSUE TITLE
regression in flutter run --profile mode

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#23748]
When running an app in profile mode (`flutter run --profile`), I now often see the message:

```
No Flutter views available on <device name>
```

And - from IntelliJ - we don't think we've successfully launched an application; we're never able to establish a service protocol connection to the running app. There's been some work in the code that lists Flutter views - have haven't bisected this issue, but that's a possible cause of the regression.

@aam

**Comment by devoncarew** [comment]
The app does come up on the device, we just don't get enough data to establish a connection to it.

**Comment by devoncarew** [comment]
And, from the cli:

```
flutter run --profile
Initializing gradle...                                       1.3s
Resolving dependencies...                                    1.7s
Launching lib/main.dart on Nokia 6 1 in profile mode...
Gradle task 'assembleProfile'...                                 
Gradle task 'assembleProfile'... Done                        1.7s
Built build/app/outputs/apk/profile/app-profile.apk (8.8MB).
No Flutter views available on Nokia 6 1
No Flutter view is available
<eom>
```

**Comment by devoncarew** [comment]
We're seeing this issue in regular (`--debug`) runs as well; we hit this during a user study.

**Comment by devoncarew** [comment]
It was running on a slow machine; perhaps a race condition which is more likely to happen on slow launches (slow machines or --profile mode).

**Comment by aam** [comment]
cc @mraleph who saw this in flutter test context on our head-head-head infratructure

**Comment by jonahwilliams** [comment]
Closing this issue since the fix has since landed
