### ISSUE TITLE
Consider removing profile()

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#23756]
We should consider removing[ profile()](https://master-docs-flutter-io.firebaseapp.com/flutter/foundation/profile.html) completely. This API is problematic because the code in the callback passed in to this function cannot be tree-shaken out currently. Even though the code will not execute in release builds it will still blow up your binary size.

We could fix this by providing a kernel extension to strip the call out in release mode. However, that seems kind of heavy to me for a problem that could easily be solved by replacing calls to profile with the following simple construct:

```dart
const bool isReleaseMode = const bool.fromEnvironment('dart.vm.product');

if (!isReleaseMode) {
  // do something here that only runs in profile and debug mode.
}
```

That seems as readable as

```dart
profile(() {
  // do something here that only runs in profile and debug mode.
});
```

The tree shaker does strip out the `if` as expected. 

/cc @Hixie @devoncarew

**Comment by devoncarew** [comment]
It looks like there are 11 call sites in the flutter framework right now.

What's the timeframe for improving tree-shaking? A kernel extension would have other nice properties - we could add a `debug()` call, similar to `profile()`, and we'd be able to remove fields as well (the `_debugFooBar` fields).

**Comment by goderbauer** [comment]
/cc @rmacnak-google for the question of improving Dart's tree-shaking above.

I did write an experimental kernel extension to strip out `_debug` fields. That one is not helping us with reducing app size (I saw reductions of just a couple of Bytes). It may help us with memory footprint, though.
