### ISSUE TITLE
measure text

### ISSUE THREAD

**Issue by htmldelivery** [flutter/flutter#23752]
I see that measure text is available in skin, but not accessible to flutter (yet?).
Is there any workaround - I need to draw rounded boxes around text for a flowcharter app.

**Comment by zoechi** [comment]
Not sure what you are missing.

A few hints

 https://stackoverflow.com/questions/52659759/how-can-i-get-the-size-of-the-text-widget-in-flutter/52991124#52991124 
  https://github.com/flutter/flutter/issues/18431#issuecomment-396990020
  https://github.com/flutter/flutter/issues/19264
  https://github.com/flutter/flutter/issues/21822

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
