### ISSUE TITLE
docs.flutter.io not updating

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2375]
http://docs.flutter.io/flutter/material/Icon-class.html doesn't match the dartdocs in the implementation https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icon.dart

Looks like they're actually uploaded to http://docs.flutter.io/packages/flutter/ rather than http://docs.flutter.io/flutter/

@eseidelGoogle @sethladd is the URL change intentional?  Should we updated all the links to use the "packages" version of the URLs or switch the bots to upload to the previous "non-packages" URLs?

**Comment by sethladd** [comment]
Closing the loop, we think packages/ was a bug. Thanks for noticing!

**Comment by abarth** [comment]
Fixed by https://codereview.chromium.org/1758393002
