### ISSUE TITLE
Support Hot Reload, Hot Restart and build without cleaning with projects built with Redux 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#23763]
From what I understand, the way hot reload works isn't built to work with the way redux manages state. This means a hot reload does nothing, and neither does a hot restart, (in my case at least) no matter what channel I'm on, I have to stop the application, run `flutter clean` and then build in order for any changes to show up.

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14.1 18B50c, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> [✓] Android Studio (version 3.2)
> [✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
> [✓] VS Code (version 1.28.2)
> [✓] Connected devices (1 available)
> 
> • No issues found!

**Comment by zoechi** [comment]
Hot reload works fine in my project with `built_redux`. I don't see why it wouldn't with `redux` as well.
You need to be more specific about what the current and expected behavior is and what exactly is not working as expected.

**Comment by ThinkDigitalRepair** [comment]
OK. The project I'm in uses flutter_redux I think it's called. I don't know
how to reproduce it. I don't know Redux well, so I can't reproduce it
myself. Is there anything else I can provide to give more details?

**Comment by zoechi** [comment]
> From what I understand, the way hot reload works isn't built to work with the way redux manages state. 

I'm pretty sure that is not true.

If you have to run `flutter clean` then it's not related to hot reload anyway.
There were some similar issues reported.

You could check if it works better with Flutter `master` channel.

**Comment by ThinkDigitalRepair** [comment]
I tried it on all channels and I had the same issue. I don’t see what the issue could be. I’d like to troubleshoot, but whatever the issue is is deep since only a clean fixes it

**Comment by ThinkDigitalRepair** [comment]
It works with the master channel now, thank you

**Comment by ThinkDigitalRepair** [comment]
But subsequent builds don't reflect changes made without a flutter clean

**Comment by zoechi** [comment]
I assume this is Android only, right? Or have you tried on iOS as well?
Is this the same with emulator and real device?

**Comment by ThinkDigitalRepair** [comment]
When running flutter run from the terminal, I'm already at 8 successful hot reloads without issue.
I also noticed this success when using the emulator and running the project from the terminal.

**Comment by ThinkDigitalRepair** [comment]
@zoechi, here's a new example project. Same issue. After hitting hot restart, it hangs and the crashes. (the debugger)
https://github.com/ThinkDigitalRepair/flutter_redux_example
Same on Android or iOS.


```
Unhandled exception:
TimeoutException: Request to Dart VM Service timed out: _flutter.runInView({viewId: _flutterView/0xafeb4f8c, mainScript: file:///data/user/0/software.thinkdigital.flutterreduxexample/cache/flutter_redux_examplePSRNNK/flutter_redux_example/lib/main.dart.dill, packagesFile: file:///data/user/0/software.thinkdigital.flutterreduxexample/cache/flutter_redux_examplePSRNNK/flutter_redux_example/.packages, assetDirectory: file:///data/user/0/software.thinkdigital.flutterreduxexample/cache/flutter_redux_examplePSRNNK/flutter_redux_example/build/flutter_assets})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:842:9)
<asynchronous suspension>
#1      VM.invokeRpc (package:flutter_tools/src/vmservice.dart:859:49)
<asynchronous suspension>
#2      VM.runInView (package:flutter_tools/src/vmservice.dart:925:12)
#3      FlutterView.runFromSource (package:flutter_tools/src/vmservice.dart:1425:20)
<asynchronous suspension>
#4      HotRunner._launchInView (package:flutter_tools/src/run_hot.dart:402:24)
#5      HotRunner._launchFromDevFS (package:flutter_tools/src/run_hot.dart:417:19)
<asynchronous suspension>
#6      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:483:11)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:546:46)
<asynchronous suspension>
#8      AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:812:19)
#9      AppDomain.restart.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:479:18)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
...
```

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v0.10.2-pre.121, on Mac OS X 10.14.1 18B75, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> [✓] Android Studio (version 3.2)
> [✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
> [✓] VS Code (version 1.28.2)
> [✓] Connected device (2 available)
> 
> • No issues found!

**Comment by ThinkDigitalRepair** [comment]
This same project is now running without a hitch. Maybe it's something in the code...

**Comment by ThinkDigitalRepair** [comment]
So this is still an issue. It's probably not redux related, as you've said, but it's with the same project. I get old code if I don't flutter clean in between builds. After a few hot reloads, it'll hang and if I don't clean, it won't show new changes. Not even changes done after the build and a subsequent hot reload.
> Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (5 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
