### ISSUE TITLE
android_alarm_manager 0.2.1

### ISSUE THREAD

**Issue by yueduz** [flutter/flutter#23766]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Finished with error: FormatException: Bad UTF-8 encoding 0xc3 (at offset 152)
timeout waiting for the application to start

As long as the installation is not used, it will go wrong.

**Comment by zoechi** [comment]
Merging with #15646
