### ISSUE TITLE
setState updating value but not rendering

### ISSUE THREAD

**Issue by ZeroCool00** [flutter/flutter#23768]
## Steps to Reproduce

I am conditionally rendering my gridview buttons. by default button color is white, but when i click on button i set color to red, and it succesfully updating value but in gridview there is no effect.

gridview card change  when reload emulator from cmd.  that meant state has no instant effect, is there any lifecycle method which is call every time when setState call. so i can rewrite gridview in it.

## Code snippet

```
class FilterDialog extends ModalRoute<void> {

   List<Grades> mGradeList = [];
   List<Styles> mStyleList = [];
   List<Types> mTypeList = [];
   List<Specials> mSpecialList = [];

   FilterDialog(this.mGradeList, this.mStyleList, this.mTypeList, this.mSpecialList);

  @override
  Duration get transitionDuration => Duration(milliseconds: 500);

  @override
  bool get opaque => false;

  @override
  bool get barrierDismissible => false;

  @override
  Color get barrierColor => Colors.black.withOpacity(0.9);

  @override
  String get barrierLabel => null;

  @override
  bool get maintainState => true;
  
  @override
  Widget buildPage(
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
  ) {
    // This makes sure that text and other content follows the material style
    return Material(
      type: MaterialType.transparency,
      // make sure that the overlay content is not cut off
      child: SafeArea(
        child: _buildOverlayContent(context),
      ),
    );
  }

  Widget _buildOverlayContent(BuildContext context) {
    return  Column(
                children: <Widget>[
                    titleWidget("Grade"),  
                    gridViewWidget(mGradeList, 3, 2.2),

                    spaceWidget(),
                    titleWidget("Style"),  
                    gridViewWidget(mStyleList, 2, 3.5),

                    spaceWidget(),
                    titleWidget("Type"),  
                    gridViewWidget(mTypeList, 2, 3.5),

                    spaceWidget(),
                    titleWidget("Special"),  
                    gridViewWidget(mSpecialList, 2, 3.5),
                ],
              )
      );
  }

  Widget gridViewWidget(list, int count, double ratio) {
    return GridView.count(
      shrinkWrap: true,
      crossAxisCount: count,
      mainAxisSpacing: 2.0,
      crossAxisSpacing: 1.0,
      childAspectRatio: ratio,
      physics: new NeverScrollableScrollPhysics(),
      children: _getTiles(list)
    );
  }

  void _onTileClicked(int index, value, list){
    assert(index != null);
    assert(value != null);
    setState(() {
        list[index].setSelected(!value);
    });
    debugPrint("You tapped on item $index with $value");
  }

  // Get grid tiles
List<Widget> _getTiles(list) {
  final List<Widget> tiles = <Widget>[];
  for (int i = 0; i < list.length; i++) {
    tiles.add(new GridTile(
          child: new Center(
            child: Container(
              height: 35.0,
              child: new RaisedButton(
                onPressed: () => _onTileClicked(i, list[i].selected, list),
                color: list[i].selected ? backgroundColor : white,
                shape: new RoundedRectangleBorder(
                    borderRadius:
                        new BorderRadius.circular(30.0)),
                child: new Text(
                  list[i].label,
                  textAlign: TextAlign.center,
                  style: new TextStyle(
                    fontSize: 14.0,
                    color: Colors.grey,
                  ),
                ),
              ),
            ),
          ),
    ));
  }
  return tiles;
}
}

 //clasees

 class Grades {
    String label;
    bool selected;

    Grades(this.label, this.selected);

    void setSelected(bool val) {
        this.selected = val;
    }
}

// some data that i m rendering

final specialList = [{"label":"Locals Recomments", "selected": true}, {"label":"New", "selected": false}];
```

![simulator screen shot - iphone x - 2018-10-29 at 18 48 57](https://user-images.githubusercontent.com/18139594/47780993-a7e17f80-dd22-11e8-84b4-6dc1ed0f322c.png)

## Version:
Flutter (Channel master, v0.10.2-pre.87, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.10.2-pre.87 at /MyDrive/flutter
    • Framework revision be86614198 (3 days ago), 2018-10-28 17:30:22 -0400
    • Engine revision a1d7cad70c
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)
```

**Comment by salihgueler** [comment]
I believe it's more of a StackOverflow question, because you are looking for an answer to your problem and doesn't seem to be an issue about Flutter.

**Comment by zoechi** [comment]
Already asked at https://stackoverflow.com/questions/53046355/setstate-not-changing-value-in-gridview-in-flutter

I'd suggest you try to simplify the code.
This will lead to more people having a closer look.

As mentioned support questions are better asked on StackOverflow.

**Comment by ZeroCool00** [comment]
@zoechi  @salihgueler i m newbie here, i m trying to understand how setState work.  as long as i know setState will have instant effect just like react-native has. right ?  and i did ask on SO first.. but no one answering that is why i ask here. thought i get answer here for sure because you guys are the one who actually working on flutter, this is my last hope. guess i just have to wait.  i m react-native developer, but i like flutter.

**Comment by ZeroCool00** [comment]
@zoechi @salihgueler now this is should be a flutter ModalRoute class bug, its working in statefulwidget class. but not working in ModalRoute class.. is there any way to update value in ModalRoute class. now plz open this issue. i m updating my title now.

**Comment by YasinEnu** [comment]
@ZeroCool00 Hi, Did you find any solution to the above problem? facing the same issue with ModalRoute<void> class.
