### ISSUE TITLE
Ability to send structured data to Flutter app at startup

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#23786]
[This is very similar to http://github.com/flutter/flutter/issues/15798]

I wanted to open a new issue for this because the issue above is quite generic. Our clients have been complaining that ability to only send strings down is too limiting from API point of view. They would love to have initialRoute (or some similar mechanism) to support protocol buffers.

**Comment by mehmetf** [comment]
Other add2app clients have also mentioned this so adding the existing-apps label.

**Comment by mehmetf** [comment]
This is neither a blocker nor critical. Two workarounds exist:
- Use platform channels. Downside is it gets a bit complicated to manage the lifecycle of it. You have to wait until Flutter app comes up and asks for the data.
- Convert protos to bytebuffer and then to base64 string and back. Downside is that it is cumbersome and potentially not needed. Platform channels can already communicate bytes directly.

**Comment by xster** [comment]
If I understand this issue correctly, this is specifically an issue when creating a Flutter UI using a constructor that makes an implicit FlutterEngine right? In those scenarios, there's no easy way of bundling in some sort of init data whereas if one pre-warms a FlutterEngine ahead of time, there are no real synchronization confusions. The user can use platform channels to send freeform data before the UI is meant to show. 

So is the fundamental issue that:

1. It's not clear that UI initialization can be split into more granular parts, leaving room in the middle to send init data.
2. There are enough valid circumstances where it's just not possible to pre-warm an engine? (I would then argue that pre-warming an engine is definitely not a single monolithic task and I'd love to find out how we can engineer things to make this have the right granularity)
3. Users conceptually disagree with the concept of entering a Dart VM entrypoint without a rich dynamic arg (I don't think this is what we're saying).

**Comment by mehmetf** [comment]
The fundamental issue is the perception of add-to-app. Most initial add-to-app users don't think of their flutter application as a separate `main()`. They think of it as an extension of their existing app, which is good. However, they get surprised when they cannot bundle data to pass to Flutter without doing a complicated dance. In iOS, you can initialize a viewcontroller with data, on Android you can bundle data as "extras" in an Intent.

Perhaps the new embedding will make it easier to prewarm the engine and will provide a way to send initialization data over which can be delivered to the UI isolate when it starts. I am not sure if that's currently possible (I thought isolates can't share data?). The point is users should not have to deal with platform channels, dart/engine lifecycle, writing their own Dart code to store initialization parameters to perform this fairly common add-to-app task.

**Comment by xster** [comment]
Got it. There's 2 separate points in there.

1- I shouldn't have to spend more than 2 seconds searching for docs to figure out how to send stuff to Flutter before drawing the first UI and how to get stuff back from Flutter when that screen pops.
2- "The point is users should not have to deal with platform channels, dart/engine lifecycle, writing their own Dart code to store initialization parameters". This point seems slightly orthogonal and I'm also not sure I agree. How should this be done without platform channels? Should there just be one static dynamic object that just exists in Dart because we special cased one under-the-hood usage of platform channel on the user's behalf? Then why is that one platform channel invocation of data sending more special? If I have a flutter view which shows UI that shares state with something else in the screen, I'd have one implicit platform channel invocation that sent some data for when the flutter view is first draw and other explicit platform channel invocations when that data needs to change again?

**Comment by mehmetf** [comment]
I gave the same kind of reasoning to users for (2). However, there are cases where the data is not expected to change so building a platform channel + data fetch layer in the Flutter app is unnecessary. A good example is a weather applet. You just provide some data to it and it renders an animated/pretty representation. Data remains static throughout the lifecycle of the UI.

This issue is about developer experience. Documentation is fine but we should align the framework behavior to user expectations to some degree so complex documentation is not necessary.

@matthew-carroll 's latest doc on plugin registration also touches this issue actually. The problem is that we expect Dart to be the master controller of platform channels whereas native channels simply register themselves and await commands. This use case breaks that assumption.  For instance, platform channel solution would be fine if we could cache data sent over a native channel and deliver it to Dart when that endpoint is connected. That way, they could build the FlutterView, send the data over a channel and expect that whenever the Flutter app is ready, it can read the data. This is not as simple as supporting a "parameterized main" but it is close enough.

**Comment by xster** [comment]
Ok, so this is mostly about special casing one invocation instance of a platform channel message in an implicit way for convenience? 

What about the return direction? Call some static thing with a dynamic arg right before SystemNavigator.pop and an id*/Object appears on the platform side?

(I'm not agreeing to any of this, I'm just trying to figure out what the ask is :D)

**Comment by mehmetf** [comment]
To be honest, I am not happy with the engineering implications of this request either. I simply think the use case is valid and if we can solve it in a way that makes sense, it would be swell :-).

I have not heard of a use case for a return value but that's an easier case to handle because you can guarantee that when Dart wants to send a value back, there's a listener on native side without doing any extra handshake.

**Comment by xster** [comment]
We'll need https://github.com/flutter/flutter/issues/32930 to be able to do this cleanly.

**Comment by pedromassangocode** [comment]
#32930 has landed!

**Comment by tvolkert** [comment]
Fixed by https://github.com/flutter/engine/pull/29096
