### ISSUE TITLE
Support creation of iOS platform views in headless mode

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#23787]
Right now we only allow creating UIViews when running with a FlutterView.

**Comment by jarrrgh** [comment]
This would be useful when taking screenshots with Flutter driver.

**Comment by sma** [comment]
We ran into this exception when trying to launch a Flutter app using the `video_player` plugin that was added to an existing Flutter app. The workaround seems to be to implicitly initialize the flutter engine when creating the `FlutterViewController`.

**Comment by dnfield** [comment]
This was actually fixed by some combination of work done by @cyanglaz and @blasten being done for other reasons. I'm removing the check/failure.
