### ISSUE TITLE
Allow TextFields to show a character counter even if there is no maxLength .. 

### ISSUE THREAD

**Issue by sjmcdowall** [flutter/flutter#23791]
I am not sure of the design reason why one must specify (and therefore show) a maxLength on a TextField if one wants to see a character counter.  My customers want to see a character counter even if there is no maximum.  

Why not either have a bool showCounter -- to show it -- or allow a maxLength of 0 to mean infinite length but show the character counter...  and maxLength == null to mean don't show it (if you want to keep the current sort of method and not introduce a new bool).

**Comment by HansMuller** [comment]
This is a reasonable request.

We've been planning to support custom character counter widgets, see https://github.com/flutter/flutter/issues/19193. That would be one way to enable this.

Using maxLength=0 to represent "no limit" sounds OK, although developers may already be using that value to temporarily disable input. We could also pick a very large int value and provide a `noMaxLength` constant.

**Comment by sjmcdowall** [comment]
I'd be more than willing to try a PR if you guys want to figure out which direction you want to go .. you are right about the maxLength = 0 maybe being used .. not sure how the noMaxLength would work... bool or ??

**Comment by HansMuller** [comment]
We could define noMaxLength with an unlikely to be used value, e.g.
```
const int noMaxLength  = 9007199254740992; // math.pow(2, 53);
```
And build a no-limits counter when maxLength == noMaxLength.

**Comment by HansMuller** [comment]
We welcome Flutter contributions! If you decide to try submitting a PR, check out the Flutter style guide:https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

**Comment by HansMuller** [comment]
Fixed in 24183
