### ISSUE TITLE
debugShowCheckedModeBanner in release mode on for iOS, off for Android

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#23814]
i just saw that the docs had "In release mode this has no effect" except that isn't true on iOS.  i've been using TestFlight for a couple iOS friends to debug a beta, one that was built with the '--release' flag.  the banner shows.  the same build specs on a Google Play alpha release channel don't show the banner, even though it's set, as per the docs.  

This should be consistent else someone will think there's something wrong with the flavors and/or build settings between Android and iOS.  i'd argue that it should render if it's set, regardless of whether it's release or debug.  leave it to the developer to manage his flavors.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Can you also reproduce if you call `flutter clean` before `flutter build ios --release`?

**Comment by blaneyneil** [comment]
my apologies, this is not actually showing on iOS release builds.  my release testers claimed they saw it, but i first asked them a couple months ago (i only use the debug version locally).  i have no idea whether they were wrong or whether it's changed in the meantime, but they just confirmed there's not a banner now.

**Comment by zoechi** [comment]
Great, thanks for the update
