### ISSUE TITLE
Flutter firestore onAuthStateChanged get triggered when tapped on a text field

### ISSUE THREAD

**Issue by praneethfdo** [flutter/flutter#23813]
I'm using the following handler to handle auth state change,

    Widget handleCurrentScreen() {
      return  StreamBuilder<FirebaseUser>(
          stream: FirebaseAuth.instance.onAuthStateChanged,
          builder: (BuildContext context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return  Scaffold(
                appBar: AppBar(
                  title: Text("Splash"),
                ),
                body: Text("Splash"),
              );
            } else {
              if (snapshot.hasData) {
                return HomePage(_auth,_googleSignIn);
              }
              return  LoginScreen3();
            }
          }
      );
    }
There's a text field in HomePage() and when I tap on it my screen is directed to Splash screen as this assertion becomes true snapshot.connectionState == ConnectionState.waiting. I can't think of any reason why connection state change to waiting? Anyone l

**Comment by zoechi** [comment]
When you tap on a text field the keyboard pops up and resizes the screen. 
This triggers a rebuild and `StreamBuilder` re-subscribes to the stream and is in `waiting` until the first event is emitted.

I think this is a good question for StackOverflow.

**Comment by henry000dev** [comment]
Hi @zoechi I posted a similar question on StackOverflow [here](https://stackoverflow.com/questions/56835372/flutter-stream-builder-triggered-when-navigator-pop-or-push-is-called). I'd love to know why and how it works behind the scene.
