### ISSUE TITLE
Flutter http post is Sending Empty body 

### ISSUE THREAD

**Issue by bennybat50** [flutter/flutter#23816]
Here is my code:
```
final Map<String,dynamic>userData={
      'firstname': _firstNameField,
      'lastname': _lastNameField,
      'display_name': _userNameField,
      'email': _emailField,
      'password': _passwordField
    };

    final response = await http.post(url, body:json.encode(userData) );
```
How do  resolve this

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by li2** [comment]
@bennybat50 How do you know `post request body is empty`, by logging the http request, or by chrome inspect with `Stetho`?

**Comment by bennybat50** [comment]
Logging the http request

**Comment by li2** [comment]
@bennybat50  Have you trid this?

    await http.post(
      headers: {
        HttpHeaders.contentTypeHeader: 'application/json',
      }

**Comment by neerajyadv** [comment]
> @bennybat50 Have you trid this?
> 
> ```
> await http.post(
>   headers: {
>     HttpHeaders.contentTypeHeader: 'application/json',
>   }
> ```

This is working but there is still an error -
 Error: Can't access platform private library.
import 'dart:_http';

So I don't know whether to use this solution or not.

**Comment by gilbertmpanga12** [comment]
@neerajyadv 
I fixed this by setting headers' content-type to application/json and accept to application/json. Here's the code snippet.
` await http.post('https://google.com/api/make-request',body: _payload,
        headers: {
      "accept": "application/json",
      "content-type": "application/json"
        });`

**Comment by sahalshn** [comment]
I am also facing the same issue .

final result = await http.post(
       "Url path",
        body: json.encode({"test":"test"}),
       headers: {"accept": "application/json", "content-type": "application/json"  },
       
      );

In the server request is hitting with req.body is empty.

**Comment by ioanmarianrusu** [comment]
> I am also facing the same issue .
> 
> final result = await http.post(
> "Url path",
> body: json.encode({"test":"test"}),
> headers: {"accept": "application/json", "content-type": "application/json" },
> 
> ```
>   );
> ```
> 
> In the server request is hitting with req.body is empty.

have you fixed this somehow? I have the same issue

**Comment by joaovictorpsantos** [comment]
> @bennybat50 Have you trid this?
> 
> ```
> await http.post(
>   headers: {
>     HttpHeaders.contentTypeHeader: 'application/json',
>   }
> ```

Thank you!!!!!

**Comment by mayankmikin** [comment]
if you are using Spring boot with HAL browser and HATEOAS  then Content-Type application/hal+json is causing problem .
so in flutter post request use below headers 
headers: {
        HttpHeaders.contentTypeHeader: 'application/json',
        HttpHeaders.acceptHeader: '*'},
