### ISSUE TITLE
Navigation popuntil method does't work in flutter

### ISSUE THREAD

**Issue by RajesMca008** [flutter/flutter#23815]
Navigation popuntil method doesn't work in the flutter
Give me the suggestions on this, how to handle back-stack clear and routing in the flutter.

Navigator.popUntil()// Doesn't work.

Navigator.popUntil(context, ModalRoute.withName(SortieList.routeName)) ;

Could you please help on this.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
