### ISSUE TITLE
[!] Android toolchain - develop for Android devices is partially installed; more components are available. (Android SDK 27.0.3)

### ISSUE THREAD

**Issue by imnick002** [flutter/flutter#23823]
[!] Android toolchain - develop for Android devices is partially installed; more components are available. (Android SDK 27.0.3)

what to do?

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/46557775/how-to-fix-partially-installed-sdk-android-studio

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by anirudhr95** [comment]
If this issue persists for you even after the recommended fix from StackOverflow ^, changing Java version to 8 worked solved this for me. (I was using JDK 11)
