### ISSUE TITLE
Please provide Autocomplete complete widget

### ISSUE THREAD

**Issue by sathishRA91** [flutter/flutter#23827]
Please suggest some Autocomplete complete widget ability to handle custom object list

**Comment by miguelpruivo** [comment]
You actually have this built-in either with VS Code or Intellij.

**Comment by zoechi** [comment]
Does https://docs.flutter.io/flutter/material/showSearch.html what you want?

See also this comment https://github.com/flutter/flutter/issues/8342#issuecomment-417116729

**Comment by zoechi** [comment]
There are also 
- #17119
- https://pub.dartlang.org/packages/simple_autocomplete_formfield
- https://pub.dartlang.org/packages/autocomplete_textfield

**Comment by sathishRA91** [comment]
https://github.com/felixlucien/flutter-autocomplete-textfield/issues/8

**Comment by zoechi** [comment]
The community seems to provide several packages for that.
The `showSearch` is the Material Design version provided by the Flutter team.
I don't think there is anything left to do for the Flutter team.

**Comment by sathishRA91** [comment]
ok thanks @zoechi

**Comment by Sp4Rx** [comment]
What about [MultiAutoCompleteTextView](https://developer.android.com/reference/android/widget/MultiAutoCompleteTextView) in flutter. @zoechi 

I feel these can be included in the flutter package.
