### ISSUE TITLE
Gradle configuration broken in flutter_tools

### ISSUE THREAD

**Issue by kmcnellis** [flutter/flutter#23820]
Error when building on new versions of Gradle
```
Could not resolve all files for configuration 'classpath'. Could not find lint-gradle-api.jar 
(com.android.tools.lint:lint-gradle-api:26.1.2). Searched in the following locations: 
https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar
```
Also recorded on stackoverflow:
https://stackoverflow.com/questions/52945041/couldnt-locate-lint-gradle-api-26-1-2-jar-for-flutter-project

The solution from stackoverflow:
Move
```
maven {
    url 'https://dl.google.com/dl/android/maven2'
}
```
on top of:
```
jcenter()
```
in the file: .flutter/packages/flutter_tools/gradle/flutter.gradle
So that it looks like
```
    buildscript {
    repositories {
        maven {
            url 'https://dl.google.com/dl/android/maven2'
        }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}
```

**Comment by kmcnellis** [comment]
During the codelab, we recorded this error on 10+ different computers

**Comment by miguelpruivo** [comment]
Dup of #23397 which is already merged into [master branch](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle). 

Waiting for a tag on dev branch too.

**Comment by zoechi** [comment]
Merging with #23404
