### ISSUE TITLE
Error running Gradle:  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by sumeetmthpt** [flutter/flutter#23829]
Hello. After creating flutter project when I try to run on android device I am getting error:

`Launching lib/main.dart on LG M700 in debug mode...
Initializing gradle...                                       0.5s
Resolving dependencies...                                        
* Error running Gradle:
Exit code 1 from: /home/sumeet/Projects/flutter_demo/android/gradlew app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sumeet/Projects/flutter_demo/android/app/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Please review your Gradle project setup in the android/ folder.
`

**Comment by miguelpruivo** [comment]
Dup of #23397 which is already merged into [master branch](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle). 

Waiting for a tag on dev branch too.

**Comment by zoechi** [comment]
Merging with #23404
