### ISSUE TITLE
`flutter_assets` should be embedded in App.framework

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#23839]
Currently, flutter_assets gets embedded directly into `Runner.app`.

For add to app, this creates additional work to embed resources into the target host app. 

It would be better if we could just embed `flutter_assets` into `App.framework` instead.

/cc @chinmaygarde @cbracken @xster @matthew-carroll

**Comment by dnfield** [comment]
Per Chinmay, this was intended as part of the shell refactor a while back and was just left as is.  The engine side should support it, but it'd be a matter of copying the file to the right place and potentially updating some templates/build steps.  It's also not 100% clear how this might affect a plugin that expects to find the folder in a specific location, which maybe we could solve with a symlink if needed.

**Comment by dodongo** [comment]
@dnfield Would this help make something like https://github.com/flutter/flutter/issues/24621 possible?
