### ISSUE TITLE
Error dependency firebase_database

### ISSUE THREAD

**Issue by thuansystemit** [flutter/flutter#23831]
1. flutter create a new app.
2. Add Firebase dependencies to pubspec.yaml:
          firebase_database: ^1.0.5
3. get package
          nothing@ubuntu:~/Android/projects/flutterexample/firebase_database$ flutter packages get
          Running "flutter packages get" in firebase_database...           
          Error on line 16, column 3 of pubspec.yaml: A package may not list itself as a dependency.
          firebase_database: ^1.0.5
          ^^^^^^^^^^^^^^^^^                                                                                                                   
          pub get failed (65)

**Comment by zoechi** [comment]
You can't name your project the same as a dependency you are using.
You need to change the `name: firebase_database` property in your `pubspec.yaml`
