### ISSUE TITLE
Please switch to new Wuffs decoder in Skia

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#23838]
@nigeltao tells me it's ready for us to try.

This is something @abarth has asked us for as well.

**Comment by eseidelGoogle** [comment]
@chinmaygarde or @jason-simmons would be the person to make the actual switch.  (FYI @cbracken)

**Comment by mklim** [comment]
Disabled in flutter/engine#7785 to fix flutter/flutter#27718.

**Comment by Hixie** [comment]
(Turns out Skia's implementation is not ready yet; we aren't sure exactly when this will be done.)

**Comment by LeonScroggins** [comment]
FYI: I've been updating [Skia bug: Replace GIF codec code with Wuffs version](https://bugs.chromium.org/p/skia/issues/detail?id=8235) to include more specific bugs that are currently blocking it. Sorry for the churn.

**Comment by nigeltao** [comment]
> Disabled in [flutter/engine#7785](https://github.com/flutter/engine/pull/7785) to fix #27718.

FWIW, #27718 looks like it's about PNG decoding, but Wuffs' enabled-ness shouldn't affect PNG decoding, only GIF decoding.

Hey, if the bisect fingers a Wuffs-related change, then it's hard to argue with that. It's just puzzling.

**Comment by eseidelGoogle** [comment]
My understanding is that with https://github.com/flutter/engine/pull/7991 customer: solaris is unblocked for now.  customer: fuchsia still requires this eventually.

**Comment by miguelcmedeiros** [comment]
@eseidelGoogle, customer:solaris is indeed unblocked (label can be removed). Thanks!

**Comment by LeonScroggins** [comment]
I think it'd be safe to try again. Here's the current status:
- we are uploading decoding results to gold.skia.org, so we'll know if the output changes
- likewise, we're uploading decoding times to perf.skia.org, so we'll know if there's a perf regression
- the windows build errors have been resolved
- we haven't seen any fuzzing bugs in a little while ([last one](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13020) fixed Feb 20)
- SkWuffsCodec handles color correction now
- there are still a couple of bugs blocking the [main one](https://bugs.chromium.org/p/skia/issues/detail?id=8235), but I think they're either not a big deal or shouldn't affect flutter (last I checked, flutter was calling SkCodec::getPixels, which is unaffected by [this bug](https://bugs.chromium.org/p/skia/issues/detail?id=8750))

**Comment by Hixie** [comment]
@LeonScroggins wonderful!

Since you mention you are tracking performance numbers, do you happen to have performance numbers of this codec relative to the previous one?

**Comment by LeonScroggins** [comment]
Perf is set up to alert us to regressions for running the same combination of parameters. There's probably a way to compare across configs, but I'm not sure how to do that. I don't have performance numbers handy, but it has generally been faster.

**Comment by cbracken** [comment]
@jason-simmons will take another look at this after our next stable build is out the door.
