### ISSUE TITLE
Clicking on the Flutter example "Posse" in the README.md leads to a 404

### ISSUE THREAD

**Issue by Blaxou** [flutter/flutter#23846]
Clicking on this image on the README.md opens a **404 error** in Github, probably because [this repo](https://github.com/flutter/posse_gallery) has moved away or been deleted ?

![image](https://github.com/flutter/website/raw/master/src/images/homepage/screenshot-2.png)

**Comment by zoechi** [comment]
This image is not shown at this page anymore.
I assume this issue is stale.

**Comment by Blaxou** [comment]
It is still in the [README](https://github.com/flutter/flutter/blob/master/README.md) file though 😉

**Comment by esarbanis** [comment]
I can confirm this is fixed now. Maybe we can close this issue again?

**Comment by zoechi** [comment]
@esarbanis thanks!
@Blaxou please let us know if you still see this with latest `master` channel.
