### ISSUE TITLE
Support for Background Update Notification in iOS

### ISSUE THREAD

**Issue by radvansky-tomas** [flutter/flutter#23842]
Hi, is there any current solution to handle silent messages correctly using cloud messaging plugin ? 

Native way is to use:

`func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void)`

Perform action and call completionHandler.

But plugin does not offer this solution, only wait till app is back in foreground (and then catch it in onLaunch/onResume) or use Notification

**Comment by radvansky-tomas** [comment]
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW1

->Configuring a Background Update Notification

**Comment by radvansky-tomas** [comment]
How it should be done from dart/flutter perspective 

https://github.com/transistorsoft/flutter_background_geolocation/blob/master/lib/background_geolocation.dart

**Comment by zoechi** [comment]
Looks like a  dup of #22305, #22197

**Comment by radvansky-tomas** [comment]
OK I see that there is not much will, so I will create PR to support headless event as suggested in other threads following pattern here: https://github.com/transistorsoft/flutter_background_geolocation

**Comment by zoechi** [comment]
> there is not much will

Please don't make such arbitrary assumptions
