### ISSUE TITLE
Flutter drive: Cannot set timeout on GetHealth command

### ISSUE THREAD

**Issue by mmcc007** [flutter/flutter#23857]
I am using the default counter app to set-up integration testing on TravisCI. I am running the android emulator on linux and the ios simulator on mac. The default integration test passes on mac/ios/simulator but fails on linux/android/emulator. 

The android emulator is getting a timeout on the driver's GetHealth command when running on Travis (no hardware acceleration, graphics in software). The weird thing is [tests](https://travis-ci.org/brianegan/flutter_architecture_samples/builds/448189417) from other projects are getting past this health check and completing successfully (when timeouts added where permitted). But when I run the default counter app integration test it times out on the GetHealth command. 

This is the test:
```dart
void main() {
  group('end-to-end test', () {
    FlutterDriver driver;
    final timeout = Duration(seconds: 20);

    setUpAll(() async {
      // Connect to a running Flutter application instance.
      driver = await FlutterDriver.connect(
        isolateReadyTimeout: timeout,
        printCommunication: true,
      );
    });

    tearDownAll(() async {
      if (driver != null) driver.close();
    });

    test('tap on the floating action button; verify counter', () async {
      // Finds the floating action button (fab) to tap on
      SerializableFinder fab = find.byTooltip('Increment');

      // Wait for the floating action button to appear
      await driver.waitFor(fab, timeout: timeout);

      // Tap on the fab
      await driver.tap(fab, timeout: timeout);

      // Wait for text to change to the desired value
      await driver.waitFor(find.text('1'), timeout: timeout);
    });
  });
}
```
and the resulting timeout:
```
[   +2 ms]   DriverError: Failed to fulfill GetHealth: Flutter application not responding
[        ]   Original error: TimeoutException after 0:00:07.500000: Future not completed
```

Here is the same [line](https://travis-ci.org/mmcc007/flutter_app/jobs/449653236#L3218) in the build on travis.

I tried increasing timeouts wherever I could, but the GetHealth time out is unaffected.
Is there a way to fix this? I suspect it would pass if I could add a timeout to GetHealth, but there might be another way.

```
[✓] Flutter (Channel unknown, v0.9.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.9.4 at /home/travis/build/mmcc007/flutter_app/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044
[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
    • All Android licenses accepted.
[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
[✓] Connected devices (1 available)
    • sdk phone armv7 • emulator-5554 • android-arm • Android 5.1.1 (API 22) (emulator)
! Doctor found issues in 1 category.
```

Here is the complete source code:
https://github.com/mmcc007/flutter_app/tree/f2738cfd44802e51ab2d47c0824b096ab57617f8
and the build on travis showing it working on ios but failing on android:
https://travis-ci.org/mmcc007/flutter_app/builds/449653234

**Comment by zoechi** [comment]
Does it work locally?

**Comment by mmcc007** [comment]
The global timeout multiplier proposed by @yjbanov in #14732 would be a good solution. This would allow developers to run their integration tests on the cloud in linux (and Mac/Windows). 

That would then make it possible to automate deployment to both stores from the cloud using something like Fastlane.  That would enable a very cost effective CICD solution for Flutter.

I was planning on setting up a demo of a complete CICD solution for Flutter on Travis (and maybe then on other CI vendors). Being able to manage all driver timeouts would make this possible.

**Comment by yjbanov** [comment]
PR is out for review https://github.com/flutter/flutter/pull/24066

**Comment by mmcc007** [comment]
PR #24066 fixed the timeout issue on GetHealth. [Here](https://travis-ci.org/mmcc007/flutter_app/jobs/455349576#L4943) is the build using master on travis showing the GetHealth command succeeding. The integration test should now passing on both ios and android in cloud 🎉

**Comment by mmcc007** [comment]
I'm now getting [timeouts](https://travis-ci.org/mmcc007/flutter_app/jobs/455368879#L3370) on ios (which I haven't seen before) even though it is [succeeding](https://travis-ci.org/mmcc007/flutter_app/jobs/455368878#L4962) on android. It may be an interim issue with master, or could be related to this fix. Not clear.
[src](https://github.com/mmcc007/flutter_app/tree/90b2f3cec429495653ac6a2bf8a51e5fb070f366)

**Comment by mmcc007** [comment]
Everything is working fine now on beta v0.11.7
https://travis-ci.org/mmcc007/flutter_app/builds/456715996
Thanks @yjbanov and all involved! 🎉
