### ISSUE TITLE
 firebase_storage: "1.0.3" upwards Error: 'UploadTaskSnapshot' isn't a type

### ISSUE THREAD

**Issue by LiveRock** [flutter/flutter#23855]
1.0.2 is ok but 1.0.3 onwards, cannot build because of the following errors:
```
Compiler message:
lib/index.dart:310:11: Error: 'UploadTaskSnapshot' isn't a type.
          UploadTaskSnapshot uploadSnapshot = await uploadTask.future;
          ^^^^^^^^^^^^^^^^^^
lib/Screens/Profile/index.dart:310:64: Error: The getter 'future' isn't defined for the class 'firebase_storage::StorageUploadTask'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'future'.
          UploadTaskSnapshot uploadSnapshot = await uploadTask.future;
```

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/52675651/why-uploadtasksnapshot-suddenly-becomes-an-compilation-error

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/50404310/how-to-get-full-downloadurl-from-uploadtasksnapshot-in-flutter/50404432#50404432 is a better link.
You need to modify your code a bit. to make it work with the new version.
