### ISSUE TITLE
in bloc pattern, should I always use stream as communication with widget

### ISSUE THREAD

**Issue by jiqimaogou** [flutter/flutter#23866]
in bloc pattern, should I always use stream as communication with widget

```
class ExampleBloc {

  final _objectsSubject = BehaviorSubject<UnmodifiableListView<Object>>();

  getObjectsAndUpdate() async {
    await _updateObjects();

    _objectsSubject.add(UnmodifiableListView(_objects));
  }
}
```

when I want to refresh the data, i call `bloc.getObjectsAndUpdate()` in the widget;

or

should i create a sink to listen the refresh action, and then call getObjectsAndUpdate in bloc object.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
