### ISSUE TITLE
Audio editing

### ISSUE THREAD

**Issue by hooramin** [flutter/flutter#23870]
Hello there
Before I explain long story of my need and several methods that I´d found to deal with it, I wanna ask a simple question:
**Is there any package or document about how to use _FFMPEG_ framework (or any similar tool) in Flutter ?**

I found an old Dart Package about that :  
https://pub.dartlang.org/packages/audio_transformer

But I have no idea how to do my "Audio editing" (In my case merging several audio clips) with Flutter.
I'm confused and need your guides.

Best regards

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
It will probably become easier to build plugins/Dart packages for that when we get #7053.
This is work in progress AFAIK but no promises for ETA.

**Comment by hooramin** [comment]
Dear @zoechi 

According to your mentioned link :
![show](https://user-images.githubusercontent.com/13273931/47917139-cf208400-debd-11e8-9dba-99493abf5b47.jpg)

I also **requested a Doc** about that, or at least it's a **feature request**.
Even if my issue was not any of them, your answer was not satisfying, Response of Flutter community was not like this ever ! 👎 
I hope instead of getting colder support, it will be better again... :(

**Comment by zoechi** [comment]
What do you mean with 

> converting Dart packages for flutter 

If packages don't depend on `dart:html` they should work fine in Flutter.

**Comment by hooramin** [comment]
I meant Using Dart packages in flutter

> If packages don't depend on dart:html they should work fine in Flutter.

I didn't know this before ! 
Thank you for your guide 🌹
