### ISSUE TITLE
Add support for "leading"

### ISSUE THREAD

**Issue by AlexTaran** [flutter/flutter#23875]
I've noticed that despite there's a `height` parameter in Flutter `TextStyle` class, there's no guarantee that it would be exact height - for some languages the interval is unpredictably increased.

Not sure this is a bug, but compared to Android - there's no such issues in `TextView`.

**Examples**

Look how the Arabic text is rendered compared to other languages (especially, line intervals).

Flutter
![screenshot from 2018-11-02 16-26-18](https://user-images.githubusercontent.com/479365/47924484-1c035b00-debc-11e8-8432-e85a11f2b750.png)

Android
![screenshot from 2018-11-02 16-26-33](https://user-images.githubusercontent.com/479365/47924490-1e65b500-debc-11e8-95c1-3a47091b6adc.png)

Flutter code:
```dart
class IneterlineExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final style = TextStyle(
        fontSize: 32.0, height: 1.0,);
    return Scaffold(
        appBar: AppBar(
          title: Text('Interline example'),
        ),
        body: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Container(
              width: 200.0,
              child: Text("This is a multiline text with English letters",
                  maxLines: 4,
                  overflow: TextOverflow.ellipsis,
                style: style,
              ),
            ),
            Container(
              width: 200.0,
              height: 100.0,
              child: Text("آموزش کامل طرز تهیه پودینگ شکلاتی موز دسر مجلسی",
                  maxLines: 4,
                  overflow: TextOverflow.ellipsis,

                style: style,
              ),
            ),
            Container(
              width: 200.0,
              child: Text("В русском языке интервалы тоже ок Russian",
                  maxLines: 4,
                  overflow: TextOverflow.ellipsis,
                style: style,
              ),
            ),
          ],
        ));
  }
}
```
Android code:

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ExampleActivity">

  <LinearLayout
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:layout_constraintBottom_toBottomOf="parent"
      app:layout_constraintLeft_toLeftOf="parent"
      app:layout_constraintRight_toRightOf="parent"
      app:layout_constraintTop_toTopOf="parent"
      >
    <TextView
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:text="This is a multiline text with English letters"
        android:textSize="32dp"
        android:maxLines="4"
        android:ellipsize="end"
        />
    <TextView
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:text="آموزش کامل طرز تهیه پودینگ شکلاتی موز دسر مجلسی"
        android:textSize="32dp"
        android:maxLines="4"
        android:ellipsize="end"
        />
    <TextView
        android:layout_width="200dp"
        android:layout_height="wrap_content"
        android:text="В русском языке интервалы тоже ок Russian"
        android:textSize="32dp"
        android:maxLines="4"
        android:ellipsize="end"
        />

  </LinearLayout>


</android.support.constraint.ConstraintLayout>
```

(Also, in Android the Arabic text is automatically aligned Right-To-Left.)

Unfortunately, I don't have beforehand knowledge of the language of data which I have to render, so I'm basically looking for a way to fit a text into some fixed size container and if it doesn't - ellipsize.
It works for horizontal dimension, but doesn't for vertical - because there's no way to have fixed line height.
Is it a solvable issue?

**Comment by HansMuller** [comment]
This appears to be related to https://github.com/flutter/flutter/issues/20829 and https://github.com/flutter/flutter/issues/20183

**Comment by najeira** [comment]
similar to #18473

**Comment by Hixie** [comment]
cc @GaryQian

**Comment by GaryQian** [comment]
There seems to be two primary ways arabic is spaced out from looking around the web. Sites that promote large blocks of text tend to render english-aligned lines, whereas sparser sites tend to use the full-line-height 'tall' spacing.

What we render seems to be consistent with the 'tall' arabic spacing. This is what we get when we lay out the characters in the same way as alphabetic characters. The dense version seems to be what is desired here. I will look into why we are using the tall version and if that is correct or not.

**Comment by GaryQian** [comment]
After more research, apparently, android does not respect the "Leading" (pronounced like the metal!) metric in fonts. In most languages, leading is 0. However in arabic (and some others), there is a non-zero leading to ensure the text is more generously spaced.

In LibTxt, we add the leading value to the line spacing, as defined by the font, and this should be proper behavior for LibTxt. I'm hesitant to modify LibTxt to not include leading.

However, what can be done is we can implement the TextStyle.height property (or something like it) as an override to allow for custom pixel-value leading, which users can set to 0 to obtain Android-style line spacing.

**Comment by GaryQian** [comment]
Adding TextStyle.leading to allow users to override the leading. To obtain the Android version of line spacing, simply provide a leading of '0'. Leading may be provided as a multiple of the font size.

**Comment by GaryQian** [comment]
Working with different Arabic fonts, it appears that many Arabic fonts (such as `Noto Sans Arabic` and `Noto Kufi Arabic`) do not include the increased line spacing in the leading, but rather in the ascent and descent. The addition of a leading property will not allow easy removal of additional line spacing in fonts without leading, but can still be used in a similar way to to the height property to adjust the line heights. as desired.

**Comment by mehmetf** [comment]
@AlexTaran Is this a blocker for your releases in Q1?

**Comment by GaryQian** [comment]
I am working on strut (https://github.com/flutter/flutter/issues/26085), which will allow finer control of line heights. With strut, is possible to force the alignment of any font with different metrics to be the same as the  layout of any other font using the `forceStrutHeight` property.

**Comment by Hixie** [comment]
@GaryQian and I will talk about this tomorrow. We may decide to not do this, in favour of the strut work.

**Comment by GaryQian** [comment]
Strut (https://github.com/flutter/flutter/commit/c6cc3cdedafee41822ce832d7d73000f2e77b183) has landed. To ensure that the text aligns, you can use Strut to force the vertical alignment to be the metrics of your english/russian font.

```dart
Text("آموزش کامل طرز تهیه پودینگ شکلاتی موز دسر مجلسی",
  maxLines: 4,
  overflow: TextOverflow.ellipsis,
  style: style,
  strutStyle: StrutStyle(
    fontFamily: 'YourEnglishFontName',
    forceStrutHeight: true,
    // Any other properties such as fontSize
  ),
)
```

This will force your text to take the vertical alignment of the english font. The `forceStrutHeight` property will cause it to ignore the arabic font's metrics.

**Comment by GaryQian** [comment]
So it seems the desired behavior is better achieved by Strut than by leading. Unless there is a specific use case for leading over strut, I will close this for now. Feel free to file a new issue or reopen this one if leading in TextStyle is required.

**Comment by UmerAayan** [comment]
it is possible to force arabic font to use the leading of the English font in ttf
