### ISSUE TITLE
Feature Request: Firebase Storage Upload Task add option to reduce chunk size

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/flutter#23871]
In my application Users can upload photos, the size of the file is very small, about 100KB, the problem with this code:

``` dart
(storageTaskEvent) {
                          progress =
                              storageTaskEvent.snapshot.bytesTransferred.toDouble() /
                                  storageTaskEvent.snapshot.totalByteCount.toDouble();
                        }
```

is, that the current chunk size of uploading is 256KB, so i cannot show any progress, if the internet speed is low.

Thanks, 
Niklas

**Comment by HerrNiklasRaab** [comment]
Probably relevant: https://github.com/flutter/flutter/issues/20803

**Comment by zoechi** [comment]
What is a typical duration the upload takes when internet is slow for such small files?
You know the file size in advance. Could you not just assume a duration it will probably take?
Reducing chunk size might make upload less efficient and take even longer.

**Comment by HerrNiklasRaab** [comment]
For example you want to upload a image with the size of 200KB, and your phone has EDGE, which allows about 110 Kbit/s of upload speed (with good connectivity, less upload speed possible), if you calculate this would be about 2 Seconds to upload, but i tried in a real environment, and it takes about 4-5s to upload. Showing progress for this task is in the current situation impossible. Let's assume, that before and after the upload some other stuff needs to be done, which takes about 2 seconds. In this scenario, i have 6-7s seconds wait time, without showing any progress to the user. 

Reducing chunk size should be an option, with a default value of 256KB.

**Comment by HerrNiklasRaab** [comment]
Yes but, what if the internetconnection is fast and it takes 1sec, or 10sec i don't know how long it will take.

**Comment by zoechi** [comment]
When upload is completed you can just remove the progressbar.

**Comment by kroikie** [comment]
@HerrNiklasRaab

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/588. Any further collaboration will be done there.
