### ISSUE TITLE
The flex red overflow box is very unclear when you first see it

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter#2387]
The reporting on issues in the visual tree with red highlighting is very useful. A few extra things could really help:
1. What does it mean? I haven't seen it in the docs (I may well have missed it). I spent a while trying to debug why a UI element was not blue (as I had set it) but was red, before guessing that it was actually a 'problem' indicator.

This could be addressed by putting a piece of text on the red area, or at adding to the tutorial doc a part where the user goes off the happy track, so we can show them what will happen and how to deal with it.
1. How to debug what it's complaining about? I've just spent ~ an hour trying to debug what was causing a layout problem that was resulting in a column coming out red. Having something that I could hold and shake the red part and Flutter would print to the log what the problem was would be great. 

For an amazing experience introducing a [WhyLine](http://www.cs.cmu.edu/~NatProg/whyline.html) like system would make debugging UI issues a pleasure.

**Comment by Hixie** [comment]
Did you see an exception in the logs?

See also https://github.com/flutter/flutter/issues/472

**Comment by lukechurch** [comment]
@Hixie No, there was no exception in the logs as far as I could see. Thanks for the cross-link, I looked around a bit for a dup. but didn't see that one.

**Comment by Hixie** [comment]
No exception is worrying. You should only see the WidgetError if there's an exception. Do you have the code that triggered this?

**Comment by lukechurch** [comment]
@Hixie The code isn't currently open source, I've sent you an email

**Comment by lukechurch** [comment]
@Hixie  Ahh, it seems that if there are two copies of Atom open the logs can end up in the wrong one. So there were exceptions, I just wasn't seeing them in the editor I was using to control the app.

(cc @devoncarew)

**Comment by Hixie** [comment]
Aha! This is actually a different red box that I had assumed. This is just telling you that your flex is overflowing. We should definitely make this much clearer.
