### ISSUE TITLE
Loop bug causes crash in release mode.

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#23879]
## Steps to Reproduce
I think I've stumbled across an AOT compiler bug. I'm seeing this in beta, dev, and master channels.

```
BlockReader nodeBlock;
int componentIndex = 1;
print("START LOOP $componentIndex");
while((nodeBlock=block.readNextBlock(BlockTypesMap)) != null)
{
	print("READ BLOCK ${nodeBlock.blockType} $componentIndex");
	// ...
	componentIndex++;
}
```

The log in debug:
```
flutter: START LOOP 1
flutter: READ BLOCK 100 1
```
The log in profile/release:
```
flutter: START LOOP 1
flutter: READ BLOCK 100 2
```

This causes a RangeError exception to be thrown as the index is always ahead by one in release mode. We can mitigate this by changing our loop logic, but I think this reproducible case may help fix an AOT logic error.

You can try this in any of the Nima examples in our repository. You can grab the v1.0.0 release here (note that we are mitigating it in later versions, so please use v1.0.0 if you are trying to repro this issue).
https://github.com/2d-inc/Nima-Flutter/releases/tag/v1.0.0

Once you've extracted that:
```
cd example/hop
flutter run --release
```

Code in the repository where the error manifests:
https://github.com/2d-inc/Nima-Flutter/blob/517e00128880d0fcf1d648850fdc6ed6021ed5aa/lib/nima/actor.dart#L487

The doctor says,
```
[✓] Flutter (Channel master, v0.10.3-pre.81, on Mac OS X 10.14.1 18B73a, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.20.1)
[✓] Connected device (1 available)
```

**Comment by jason-simmons** [comment]
This only appears to affect ARM64 AOT targets.

Looks like it started with this Dart roll: https://github.com/flutter/engine/commit/5903a08c8d777e5e8b0640c19334945a365e9de0

@a-siva

**Comment by aartbik** [comment]
Reproducible:
```

Installing build/app/outputs/apk/app.apk...                  2.2s

To quit, press "q".
E/flutter ( 4512): [ERROR:flutter/shell/common/shell.cc(182)] Dart Error: Unhandled exception:
E/flutter ( 4512): RangeError (length): Invalid value: Not in range 0..56, inclusive: 57
E/flutter ( 4512): #0      Actor.readComponentsBlock (package:nima/nima/actor.dart:0)
E/flutter ( 4512): #1      Actor.load (package:nima/nima/actor.dart:464)
E/flutter ( 4512): #2      FlutterActor.loadFromBundle (package:nima/nima.dart:195)

```

**Comment by aartbik** [comment]
With local engine and Dart ToT, the bug no longer reproduces. For peace of mind, we need to find out when this was fixed.

**Comment by aartbik** [comment]
Not much useful progress so far. I tried to do a bisection search on the Dart SDK version, but ToT of a local engine runs fine, and going back to the time frame of the failure is next to impossible since I need to keep patching the Dart SDK to stay in sync with Flutter. I also tried to make a small stand-alone Dart reproducer so we can do bisection without the dependence on the full Flutter framework, but no luck so far.

**Comment by aartbik** [comment]
Note, to reproduce this with local engine, explicitly specifying arm64 is essential (builds host_release_arm64 and android_release_arm64 and using "--target-platform=android-arm64" in the flutter run). With this the phi handling CL seems the culprit. Investigating....

**Comment by aartbik** [comment]
With bisection search on the optimization, we find that the 3284th occurrence of the phi handling breaks, not surprisingly in the method:
`package:nima/nima/actor.dart_Actor_readComponentsBlock`

Around a phi:
```
B64[join]:560 pred(B1, B62) {
     v23 <- phi(v7, v645) alive [1, 4611686018427387903] T{_Smi}
     ....
```
The transformation looks correct in itself, so perhaps it triggers something downstream.

For now we are going to revert the culprit CL and reland it when we get to the bottom of this.

**Comment by aartbik** [comment]
Note that  the *revert* introduced the following failure (windows only, but arm64 sim):

Unhandled exception:
Expect.equals(expected: <-30064771072>, actual: <0>) fails.
#0      Expect._fail (package:expect/expect.dart:651)
#1      Expect.equals (package:expect/expect.dart:124)
#2      doVars (file:///C:/b/s/w/ir/tests/language_2/vm/mult_int_test.dart:83)
#3      main (file:///C:/b/s/w/ir/tests/language_2/vm/mult_int_test.dart:97)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)

--- Re-run this test:
python tools/test.py -m release -a simarm64 -n dartkp-win-release-simarm64 language_2/vm/mult_int_test

**Comment by aartbik** [comment]
Spilling occurs for the induction variable and the parallel move resolver does not honor the boxed/unboxed property for the initial constant. Even though v23 is unboxed, the initial value stored is assumed to be tagged, causing it to be shifted by 1. Once the induction variable which is restored from stack during the while-loop, it remains seemingly off-by-one after that.

```
  ;; v691 <- UnboxedConstant(#1) [1, 1]
  ;; ParallelMove S-4 <- C, r14 <- C, r13 <- C, r12 <- C, r11 <- C, r10 <- C, r9 <- C, r8 <- C, r7 <- C, r6 <- C, r5 <- C, r3 <- C, r2 <- C, r1 <- C goto:566 B64
0x7f69203ac148    d2800041               movz r1, 0x2 
0x7f69203ac14c    f81e03a1               strx r1, [fp, #-32]

```

**Comment by aartbik** [comment]
Fix:

        ;; v661 <- UnboxedConstant(#1) [1, 1]
        ;; ParallelMove S-4 <- C, r14 <- C, r13 <- C, r12 <- C, r11 <- C, r10 <- C, r9 <- C, r8 <- C, r7 <- C, r6 <- C, r5 <- C, r3 <- C, r2 <- C, r1 <- C goto:556 B64
0x7f835c0ec148    d2800021               movz r1, 0x1 
0x7f835c0ec14c    f81e03a1               strx r1, [fp, #-32]

**Comment by aartbik** [comment]
\O/
