### ISSUE TITLE
Try introducing a TextureView variant of FlutterView, as opposed to the current base class of SurfaceView

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#23885]
Try introducing a TextureView variant of FlutterView, as opposed to the current base class of SurfaceView.  This new offering can exist alongside the existing SurfaceView based version.

**Comment by mklim** [comment]
There's some previous discussion on this in flutter/flutter#9627, starting with https://github.com/flutter/flutter/issues/9627#issuecomment-418566582. 

Other good sources of info:

- https://source.android.com/devices/graphics/architecture 
- https://source.android.com/devices/graphics/arch-tv#surface_or_texture

**Comment by mehmetf** [comment]
@matthew-carroll Is it possible for you to create a quick patch for `FlutterView` that converts it to a TextureView? The APIs should be largely similar. Dream wants to test their local implementation using that.

@amirh I am curious as to what, if any, effect this would have on platform views on Android.

**Comment by amirh** [comment]
The current platform views mechanism on Android should keep working as-is (other than the fact that a TextureView will be an additional thing that eats some of the performance budget).

**Comment by mehmetf** [comment]
@jason-simmons is prototyping a very simple solution to see if it works. Will post an update.

**Comment by Hixie** [comment]
We are not sure how to proceed with this. We think @matthew-carroll's work should in any case either inform or resolve this issue, so we are not planning on doing anything with it in the near future. Please let us know if this is more urgent than that. For now I'm putting this into the Declined milestone to make it clear that we are not working on it.

**Comment by mehmetf** [comment]
Customer: Dream is implementing nasty workarounds for this issue at the moment. The basic problem is that SurfaceView not playing nice with the rest of the views on screen.  I will cc you and @matthew-carroll on a doc with details. Since the UI does not behave as they want, it is a release blocker for them and their timeline is mid-Jan.

**Comment by Hixie** [comment]
Ok. Please cc @jason-simmons as well. We can get together and figure out how to resolve this to their satisfaction.

**Comment by Hixie** [comment]
My understanding is that a solution was provided to customer:dream so I'm taking this off the blocker list.

**Comment by matthew-carroll** [comment]
Both `SurfaceView` and `TextureView` are now supported in the new Android embedding (but still experimental until future notice).

https://github.com/flutter/engine/tree/master/shell/platform/android/io/flutter/embedding/engine/android
