### ISSUE TITLE
SingleChildScrollView + Column + Opacity bug

### ISSUE THREAD

**Issue by diegoveloper** [flutter/flutter#23890]
I'm facing a weird issue after update to dev channel v0.10.2
``` 
[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14 18A391, locale en-PE) 
```

When I use SingleChildScrollView + Column + Opacity ( different from 1.0) , some items are not visible.
This is code sample to recreate the bug.

Using opacity =  1.0 works fine:

```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("New issue"),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: List.generate(10, (index) {
            return Opacity(
              opacity: 1.0,
              child: Container(
                child: OutlineButton(
                  onPressed: () => null,
                  child: Text("hello : $index"),
                  borderSide: BorderSide(color: Colors.purple),
                ),
              ),
            );
          }),
        ),
      ),
    );
  }
```
Result : OK
![issue1](https://user-images.githubusercontent.com/4898256/47946091-08b0b980-ded5-11e8-88d8-3550c3805afa.png)

Now using opacity = 0.5    :

```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("New issue"),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: List.generate(10, (index) {
            return Opacity(
              opacity: 0.5,
              child: Container(
                child: OutlineButton(
                  onPressed: () => null,
                  child: Text("hello : $index"),
                  borderSide: BorderSide(color: Colors.purple),
                ),
              ),
            );
          }),
        ),
      ),
    );
  }
```

![real_issue](https://user-images.githubusercontent.com/4898256/47946099-1cf4b680-ded5-11e8-89e2-e4858d0f8cba.png)

As you can see only a portion of the list is visible, it only happens after upgrade to v.0.10.2

Toggle debug painting enabled:

![error3](https://user-images.githubusercontent.com/4898256/47959273-a1b30380-dfad-11e8-8a89-7e5dcf6c96cc.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by diegoveloper** [comment]
@zoechi 

```
flutter doctor -v
[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14 18A391, locale en-PE)
    • Flutter version 0.10.2 at /Users/diegoveloper/Development/SDKS/flutter
    • Framework revision d8cbb80206 (9 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/diegoveloper/Development/SDKS/Android/android-sdk/
    • Android NDK at /Users/diegoveloper/Development/SDKS/Android/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/diegoveloper/Development/SDKS/Android/android-sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone 8 • 033C921D-C0C4-412C-A564-8C95A46B5AE3 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by diegoveloper** [comment]
If at least the last element has opacity = 1.0 , if works fine:

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("New issue"),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          print("builder");
          return SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: List.generate(20, (index) {
                return Opacity(
                  opacity: index > 18 ? 1.0: 0.5,
                  child: Container(
                    child: OutlineButton(
                      onPressed: () => () {
                            setState(() {});
                          },
                      child: Text("hello : $index"),
                      borderSide: BorderSide(color: Colors.purple),
                    ),
                  ),
                );
              }),
            ),
          );
        },
      ),
    );
```

**Comment by szotp** [comment]
I had similiar problem with Opacity inside ClipRect. ClipRect inside Opacity worked fine.

**Comment by NathanAP** [comment]
I'm experiencing a similar problem too. I have some lists with Column -> Material -> InkWell -> Padding -> Opacity -> Row -> children. When I lose my app focus (minimize) and then go back (maximize), every item turns into a grey rectangle. Performing a setState seems to resolve the problem, but I'm sure this bug is from this patch.

**Comment by diegoveloper** [comment]
Hi @NathanAp , could you provide us a sample code to repo your issue?

**Comment by NathanAP** [comment]
@diegoveloper I can't provide the exact code since I have all the rules. Just FYI the list can have different structures, so I'm not using ListView to create it, instead, I'm using a function to return a list of Material inside my Column. Here's the base structure:

```
return new Scaffold(
   body: new SingleChildScrollView(
      child: new Column(
         children: [
            new Material( //Here is the function to return the List of Widgets
               color: Colors.white,
               child: new InkWell(
                  onTap: (){ }
                  child: new Padding(
                     padding: new EdgeInsets.all(10.0),
                     child: new Opacity(
                        opacity: 0.2,
                        child: new Row(
                           children: [
                              new Text('Test')
                           ]
                        )
                     )
                  )
               )
            )
         ]
      )
   ),
); 
```

Here is the result I'm getting both on iOS and Android:

![screenshot_20181109-133556](https://user-images.githubusercontent.com/12821171/48272092-f4b10e80-e424-11e8-8397-666d8dfba382.jpg)

**Comment by diegoveloper** [comment]
@NathanAP are you able to repo the issue using my code on the first post?

**Comment by NathanAP** [comment]
@diegoveloper Yea, got the same result as you. I notice that when I try to scroll the screen some of your List Items actually appears behind a "white screen" too...

**Comment by HansMuller** [comment]
I can confirm that the problem, as demo'd in the issue's description does not occur with v0.9.4 but does occur on v0.10.2

**Comment by diegoveloper** [comment]
Please vote up my first post to get more attention.

**Comment by HansMuller** [comment]
You have our attention :-)

**Comment by diegoveloper** [comment]
Oh sorry, you are from google

**Comment by jason-simmons** [comment]
This regressed during the change to retained layers: https://github.com/flutter/flutter/commit/883e2dc272984f60c94804ef08709fe137d0d26c

@liyuqian

**Comment by jason-simmons** [comment]
Specifically, it looks like this is related to how offsets are handled within `OpacityLayer`: https://github.com/flutter/engine/commit/e79d77f6e6cdcfedf6a01b2a44b00de0260b7ede

The example produces a `ClipRectLayer` containing 10 `OpacityLayer` instances with different offsets.

`OpacityLayer::Preroll` is not adjusting the `paint_bounds` rectangle by the opacity layer's offset.  When `ContainerLayer::PrerollChildren` tries to merge the child layers' bounds, this results in a clip rectangle that is only large enough to fit the first OpacityLayer (at offset zero).  The clip rect excludes the other OpacityLayers with nonzero offsets.
