### ISSUE TITLE
Merge PR in http_server

### ISSUE THREAD

**Issue by ngocdaothanh** [flutter/flutter#23892]
I have this PR:
https://github.com/dart-lang/http_server/pull/53

Can someone in the team merge it (or comment if there's anything to improve)?

**Comment by jonahwilliams** [comment]
Hi @ngocdaothanh, I'm sorry it's taken someone so long to get to your PR. I went ahead and cc'd an owner of that package (and I'll reach out on Monday to confirm). Since flutter team doesn't own that repo, there isn't much we can do here.

**Comment by jonahwilliams** [comment]
Looks like it has been taken care of!
