### ISSUE TITLE
problem with flutter -bash flutter -command not found

### ISSUE THREAD

**Issue by fastisaac** [flutter/flutter#23895]
I have created a profile called .bash-profile on osX. 
echo $PATH 
returns
/downloads/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

file .bash_profile has
PATH=/downloads/flutter/bin:$PATH
but when i type flutter doctor
it returns
-bash: flutter: command not found

**Comment by zoechi** [comment]
This question is better asked on StackOverflow.
