### ISSUE TITLE
arm64 targets don't use NEON optimizations

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#239]
<a href="https://github.com/chinmaygarde"><img src="https://avatars.githubusercontent.com/u/44085?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chinmaygarde](https://github.com/chinmaygarde)**
_Tuesday Oct 27, 2015 at 22:56 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1841_

---
- Needs updates to `skia/BUILD.gn`

**Comment by sethladd** [comment]
Do we plan to do this? Did we do this? (aka can we close, or shall we leave it open?)

**Comment by Hixie** [comment]
@chinmaygarde What's the status of this bug?

**Comment by eseidelGoogle** [comment]
@a-siva wasn't sure off the top of his head if these are turned on in the DartVM, but said he could find out.  I expect Skia already uses these.

**Comment by chinmaygarde** [comment]
I turned these on in Skia already.

**Comment by a-siva** [comment]
The Dart VM does use the Neon instructions when the Float32x4 and Int32x4 types are used.
