### ISSUE TITLE
video_player don't work normally in dev 0.10.2

### ISSUE THREAD

**Issue by hyz1992** [flutter/flutter#23930]
I upgrade from beta 0.7.3 to 0.10.2 today,and video_player can't work any more,
even when I use example in video_player plugin.
maybe there is something wrong with Texture rending in dev 0.10.2

**Comment by zoechi** [comment]
Do you see any error output in the console?
I remember I had to update the video initialization code a while ago after an update but I'm pretty sure I got some errors.

**Comment by hyz1992** [comment]
no,I did't see any error log, just rending a blinking texture.

**Comment by hyz1992** [comment]
in the version dev 0.11.6 ,this problem still exist

**Comment by hyz1992** [comment]
@recastrodiaz yes,they are maybe the same issue.my devices is Le X620
