### ISSUE TITLE
Creating a Flutter plugin generates a very long tree of folders under pod development, down to classes

### ISSUE THREAD

**Issue by JCzz** [flutter/flutter#23941]
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected devices (1 available)
```

<img width="395" alt="flutterpodfolder" src="https://user-images.githubusercontent.com/1861398/48003670-5f093c80-e10f-11e8-8273-29bb1ef3e7a0.png">

I have created a Flutter plugin package:

```
    flutter create --template=plugin -i swift hello
    cd hello
    cd example
    flutter build apk
    pod install
```

Opened `Runner.xcworkspace`

I know see a very long tree of folders down to the classes

**Comment by zoechi** [comment]
Is this a question, a bug report, a feature request, ...?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
