### ISSUE TITLE
timeout waiting for the application to start 

### ISSUE THREAD

**Issue by jayantakumar** [flutter/flutter#23947]
**Log:**
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
#timeout waiting for the application to start
#23861 
Syncing files to device GT I9300...
I/Process (27308): Sending signal. PID: 27308 SIG: 9
Lost connection to device.

**PLEASE HELP ME!!**

**Comment by DanTup** [comment]
This appears to be a duplicate of #23861 which is mentioned in your comment (and maybe #22338). If you think this is a different problem and needs its own issue, please add some additional info why.
