### ISSUE TITLE
AutomaticKeepAliveClientMixin issue

### ISSUE THREAD

**Issue by AllinGaming** [flutter/flutter#23940]
As i understand if i use AutomaticKeepAliveClientMixin i can save the state of a widget and it's list scroll position. So here is the code and would someone please explain why doesn't my list in scan_widget keep its scroll position when i change a part of the page body. thank you!
[main.txt](https://github.com/flutter/flutter/files/2548732/main.txt)
[placeholder_widget.txt](https://github.com/flutter/flutter/files/2548733/placeholder_widget.txt)
[scan_widget.txt](https://github.com/flutter/flutter/files/2548734/scan_widget.txt)
[tababar_widget.txt](https://github.com/flutter/flutter/files/2548735/tababar_widget.txt)
here are all my dart classes in .txt files

**Comment by AllinGaming** [comment]
Also any advice on how to use navigation and automatickeepaliveclientmixin with it to save states and scroll position would be greatly appreciated, thank you!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Perhaps mixed up with https://docs.flutter.io/flutter/widgets/PageStorageKey-class.html ?
I also found https://github.com/flutter/flutter/issues/10657#issuecomment-308235069 helpful.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
