### ISSUE TITLE
Flutter crashes without any error message

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#2395]
When creating a new EffectLine object Flutter crashes quietly without any stack trace or error message.

### Steps to Reproduce
To reproduce:
clone git@github.com:vlidholt/line_test.git
cd line_test
pub get
flutter run

**Comment by abarth** [comment]
The problem appears to be the `new ImageShader` call in textured_line.dart.  Not sure why that crashes yet.

**Comment by Hixie** [comment]
probably a dupe of https://github.com/flutter/flutter/issues/1159
