### ISSUE TITLE
`flutter make-host-app-editable` forces Cocoapods usage even if it's not already there

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#23956]
This seems like a decision that was made by design at one point, but may not work for some current needs.

The following series of commands will result in an app that depends on Cocoapods, even though no plugins have been added:

```
flutter create -t module test_module
cd test_module
flutter make-host-app-editable
```

This seems undesireable, especially in the context of the new work to make these templates the preferred default.

/cc @matthew-carroll @mit-mit  @xster 

@mravn if you have any additional context you could share on it that would be appreciated!  I have an old email on it, but it's missing some details I think.

**Comment by matthew-carroll** [comment]
To clarify the context:

Running the following used to be done independently, at will:
flutter create -t module my_module
flutter make-host-app-editable

Now, as we look at making project linking a standard feature for all projects, we thought why not just run those commands back-to-back under the hood to get the effect we want.

It's the latter decision that has made cocoapods an issue, not the earlier decision to automatically include cocoapods.  The earlier decision was the right decision for the use-case it was enabling.  The question is what should we do now?

**Comment by dnfield** [comment]
Deprioritizing this - it will require reworking a bit more around how we handle adding Cocoapods in general, and we're defering the need for this workflow to work for a little bit.

**Comment by jmagman** [comment]
We've been de-prioritizing `make-host-app-editable` workflows (it's not even mentioned in the new website guide).

The website documents two ways to embed a module.

[Option A](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk) leverages CocoaPods heavily, even without plugins.  All frameworks and the xcode_backend.sh script phase are added via generated podspecs.

[Option B](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode) does not require CocoaPods at all, assuming no plugins.

If they go Option A, they need CocoaPods regardless of whether the app uses plugins...

**Comment by jmagman** [comment]
This command has been deleted.  There's a [CocoaPods-free way to use add-to-app](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode).  Closing.

If there's more to track here, let me know @dnfield and I'll reopen.

**Comment by dnfield** [comment]
Yes, this is obsolete.
