### ISSUE TITLE
Flutter docs snippets don't show up in search results?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#23960]
https://www.google.com/search?q=flutter+container

https://support.google.com/webmasters/answer/7489871?hl=en

<img width="646" alt="screen shot 2018-11-05 at 2 17 48 pm" src="https://user-images.githubusercontent.com/11857803/48030374-b0acc980-e105-11e8-85e3-cfe957f848d9.png">

**Comment by eseidelGoogle** [comment]
Is this a dartdoc bug or something in the configuration of our docs site?  FYI @InMatrix @jcollins-g

**Comment by jcollins-g** [comment]
dartdoc itself just generates HTML, and doesn't create robots.txt.  My guess would be a configuration issue in the docs site.  This is backed up by other sites serving dartdoc output not having this problem in Google search.  (They don't generally have super-great descriptions, but they at least have something).

**Comment by InMatrix** [comment]
It would be really helpful to our users to fix this. Cc: @gspencergoog

**Comment by gspencergoog** [comment]
Yeah... I wonder where our robots.txt comes from...

**Comment by gspencergoog** [comment]
Well, <https://docs.flutter.io/robots.txt> doesn't appear to exist, so probably we need to create one, but I would think that the default was "full access", not "just the titles".

**Comment by gspencergoog** [comment]
Actually, that's really odd.  Google's explanation is "You are seeing this result because the page is blocked by a robots.txt file on your website. (robots.txt tells Google not to read your page; if you block the page to us, we can't create a page description in search results.)"

But we don't actually have a robots.txt on that site.  Flutter.io's robots.txt says "# All robots welcome!", and that's all.

I'll add one, and we'll see if it changes.

**Comment by gspencergoog** [comment]
Just as an aside, we should probably also create a custom 404.html file for the site for pages that aren't found...

**Comment by DanTup** [comment]
I'm not sure the robots.txt will help though, it seems to be specific to that (or at least, a subset) of pages?

![screen shot 2018-11-07 at 4 43 02 pm](https://user-images.githubusercontent.com/1078012/48146153-46825900-e2ac-11e8-855d-bb8c50489ce1.png)

**Comment by eseidelGoogle** [comment]
Might be getting copied over from master staging?
https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh#L78

https://docs.flutter.io/robots.txt

**Comment by gspencergoog** [comment]
No, the docs site for master is deployed only to master, and the beta one is freshly built and deployed when we roll beta.
