### ISSUE TITLE
在中国，为flutter开发的sdk比较匮乏

### ISSUE THREAD

**Issue by yigehaokanderen** [flutter/flutter#23968]
我是一名来自中国的开发者，在中国，为软件接入移动联广告盟创造收入是很普遍的盈利方式，但是目前中国市场上并不存在兼容flutter的相关广告sdk，Google ad也没有提供官方版本的支持，所以我的问题是，能否推动一些较大的互联网公司，例如腾讯，百度，阿里等等，为flutter开发者开发专用的相关sdk？

**Comment by zywj** [comment]
Your need is not the concern of flutter now.
You can write them by yourself and  then open source if you want.

**Comment by yigehaokanderen** [comment]
> Your need is not the concern of flutter now.
> You can write them by yourself and then open source if you want.

我认为我的问题跟flutter是息息相关的，一定要有人去推动一些大的厂商为flutter提供服务，这项工作和提升框架的性能、丰富框架的功能等等这些工作是同等重要的。
另外，对于即时通信、广告联盟等等大型的服务，我认为他们应该由专业的服务商来提供。我确实可以提供自己的解决方案，但是长远来看，这些较大的厂商是否提供官方的支持，是flutter生态的重要组成部分，也是开发者在选择框架时的重要指标。
所以我的目的是，希望有人重视这个问题，并且去推动这些工作的进行。
感谢你的回应，谢谢。

**Comment by HeathHsia** [comment]
Just do it !  Now!

**Comment by yigehaokanderen** [comment]
> Your need is not the concern of flutter now.
> You can write them by yourself and then open source if you want.

我认为我的问题和flutter现阶段的应该要做的工作是息息相关的。应该要有人去推动这些大的服务商为flutter提供支持。这些工作同丰富框架功能，提升框架性能等等是一样重要的。
我确实可以提出自己的解决方案，但是对于一些大型的服务，像即时通讯，或是广告联盟，我认为他们应该要由专业的服务供应商来提供，这些供应商是否提供官方支持，也是flutter生态的重要组成部分，更是开发者在选择框架时十分关心的。
所以我的问题是希望有些重视这样的工作，并能够推动这项工作的进行。
感谢你的回应，谢谢。

**Comment by lishuhao** [comment]
I don't think these jobs should be done by the flutter team, they have more important work to do. And manufacturers are willing to develop flutter plugin is determined by the market.

**Comment by zoechi** [comment]
I'm closing because I can't read Chinese and don't know what the issue is about.
Feel free to continue the discussion.
