### ISSUE TITLE
Support double-tap-drag on text fields

### ISSUE THREAD

**Issue by xster** [flutter/flutter#23973]
On Android, a double tap drag moves the cursor on first tap and the drag expands the selection through the drag.

On iOS, a double tap drag moves the cursor on the first tap but then just scrolls. However, a double tap hold drag has the same effect as Android with a text selection magnifier lens.

**Comment by xster** [comment]
on iOS, reminder to move the toolbar show from double-tap-hold-down to double-tap-hold-up

**Comment by S60bishoyhanna** [comment]
I can see CupertinoTextField missing main IOS textfield features
- where is the lens? it should appear when hold tapping
- In IOS, when u tab one tap on the cursor it, shows the buble (copy,paste,select,select all) but in flutter u have to hold taping a while to show that menu

**Comment by Renzo-Olivares** [comment]
Closed by #117502

**Comment by simplenotezy** [comment]
@Renzo-Olivares / @xster I've been reading a few different older issues on this, however, I cannot get consistent behaviour with the "double tap word to select it".

With a simple widget like this:

```dart
CupertinoTextField(
                    minLines: 1,
                    maxLines: 7,
                    keyboardType: TextInputType.multiline,
                  )
```

Nothing happens when double pressing a word. I cannot get the "Select" toolbar option. 

Not sure if I should create a new separate issue on this, or if I am misunderstanding something.

**Comment by Renzo-Olivares** [comment]
Hi @simplenotezy I tried this on the `master` branch and it works for me.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: CupertinoTextField(
            minLines: 1,
            maxLines: 7,
            keyboardType: TextInputType.multiline,
          ),
        ),
      ),
    );
  }
}
```

Using the `iOS` simulator. What device are you using?



https://user-images.githubusercontent.com/948037/221641927-97c84126-a91a-4b1f-8491-5b23fff5f085.mov

I think it might be better to create a new issue though.
