### ISSUE TITLE
Dynamically change thread configuration when a UIView is embedded

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#23975]
Embedding UIViews requires that the gpu and platform views are the same.
Currently apps that embed UIViews needs to statically choose a conforming thread configuration.
This is a little inefficient for apps that show embedded views some times but not always.

Once that engine supports that, we should merge the threads based on the presence of an platform view in the layer tree.

**Comment by amirh** [comment]
cc @chinmaygarde

**Comment by cyanglaz** [comment]
Reopen as the PR that closes this issue was reverted. We still see some problems enabling thread merging.

**Comment by cyanglaz** [comment]
Landed with https://github.com/flutter/engine/pull/19919, closing the issue.
