### ISSUE TITLE
vscode gradle error 

### ISSUE THREAD

**Issue by Sugarman49** [flutter/flutter#23981]
I'm trying to run the sample flutter app on vscode but it keeps giving me this error: 

```
 Could not find method ﻿import() for arguments [interface java.nio.file.Path] on project ':app' of type org.gradle.api.Project.
````

I also modified my gradle file as it was suggested here and there as follow: 

```
import java.nio.file.Path
import java.nio.file.Paths

import com.android.builder.model.AndroidProject
import org.apache.tools.ant.taskdefs.condition.Os
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.Task
import org.gradle.api.file.CopySpec
import org.gradle.api.file.FileCollection
import org.gradle.api.tasks.Copy
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.bundling.Jar

buildscript {
    repositories {

        google()
	    jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}
```

**Comment by zoechi** [comment]
> as it was suggested

Do you mean #23404 ?

Is this with a new project or an existing one?

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
