### ISSUE TITLE
iOS: Flutter not yet ready when called from outside (closed app)

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#23992]
1. call app via URL scheme
2. handle call in application:openURL (iOS)
3. trigger invokeMethod to call a function in Flutter
4. **Flutter function is not called if app was not yet open**

As soon as the app is opened (eg. in the background) it works fine. 

_I solved it over a delayed call (native) if the app state was inactive or inBackground - otherwise I call it directly. But I don't like this approach as it's not reliable.
Other possibility would be to save something in the store, read it in the (Flutter) application as soon as it started up and handle it that way. But I don't like this neither..._

**Is there a possibility to await until Flutter is loaded (application is ready to receive platform interactions)?**

**Comment by gaaclarke** [comment]
This should be fixed since the introduction of channel buffers.  The message should be stored until the engine is started.  See also: https://github.com/flutter/flutter/issues/38914.
