### ISSUE TITLE
Generate one top-level API docs page that shows everything we ship

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2399]
Talked to @Hixie and the conclusion was that we want to provide a unified top-level API docs page, with a flat list of every library we ship. Effectively, that means we want to put playfair, sprites, etc into the same list as material and dart:jni. This also means we get to stop maintaining a custom API docs homepage.

**Comment by sethladd** [comment]
cc @qchong

**Comment by Hixie** [comment]
I guess to do this we just create a main.dart file that we hand to the dartdoc tool and have that main.dart import all the things we want documented? Is that right?

**Comment by Hixie** [comment]
cc @qchong this is the bug about merging the docs.flutter.io homepage into one page that has all the packages listed, probably by moving what's at docs.flutter.io/flutter into docs.flutter.io and having that page list, the same way it today lists dart:core and company, all the packages that you get when you download the SDK.

**Comment by qchong** [comment]
@devoncarew As you suggested, can you please help put together a new, hidden, command in the flutter cli tool to generate our combined docs for us? 'flutter doc-repo' or 'flutter dartdoc --flutter-repo' or something that would create a (pretty small) synthetic project, then have dartdoc generate the combined reference docset.

**Comment by Hixie** [comment]
Might be better to have this be a separate script in the `dev/` directory rather than overloading `flutter`, unless there's a lot of code there to reuse.

**Comment by qchong** [comment]
Fix dependent on Devon's in-progress PR [#1132](https://github.com/dart-lang/dartdoc/pull/1132).

**Comment by devoncarew** [comment]
This has landed. There may be some cleanup w/ how the docs look.

@qchong, you change change the main page by editing this file: https://github.com/flutter/flutter/blob/master/dev/docs/README.md.

**Comment by Hixie** [comment]
Thanks devon!
