### ISSUE TITLE
Positioning Option for Raised Button's Icon

### ISSUE THREAD

**Issue by afnx** [flutter/flutter#23990]
`RaisedButton.icon()` helps us build a raised button which includes an icon without much effort. That's great; however, it doesn't let us to decide the position of the icon. Therefore, the icon always appears on the left side of the button. If there is a convenient way to determine the position of the icon, it would be perfect.

**Comment by lishuhao** [comment]
You can customize your own components，so easy!
``` dart
class MyIconButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RawMaterialButton(
      fillColor: Colors.red,
      splashColor: Colors.grey,
      textStyle: TextStyle(color: Colors.white),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[Text('BUTTON'), Icon(Icons.timer)],
      ),
      onPressed: () {},
    );
  }
}
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by chenna-reddy** [comment]
> You can customize your own components，so easy!
> 
> ```dart
> class MyIconButton extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return RawMaterialButton(
>       fillColor: Colors.red,
>       splashColor: Colors.grey,
>       textStyle: TextStyle(color: Colors.white),
>       child: Row(
>         mainAxisSize: MainAxisSize.min,
>         children: <Widget>[Text('BUTTON'), Icon(Icons.timer)],
>       ),
>       onPressed: () {},
>     );
>   }
> }
> ```


This will work for simple cases, but to take button state into consideration we would end-up copying all logic of `_RaisedButtonWithIcon` (same with `_FlatButtonWithIcon`)  just to re-position the icon. How about convinient Factory methods like `withPrefixIcon`, `withSuffixIcon` or better names??

**Comment by ogarvey** [comment]
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

@zoechi 

The first option on that page is a link to the issue tracker here on GitHub, which literally instructs you to "Tell us what you want to see", is that not the case?

I came here after a google search looking for a way to set the position of the icon in a RaisedButton.icon because the docs didn't seem to cover it, have I potentially missed something? 

While I realise as @lishuhao commented it's easy enough to create a custom component, it would to me at least seem logical to include something like @chenna-reddy suggestion which is what I'm guessing was @afnx original request.

Any response appreciated :)

**Comment by mdegenvathos** [comment]
@ogarvey @chenna-reddy @afnx 

I had trouble styling the solution of @lishuhao , consider my solution below (which uses a row), use a column for vertical alignment. Hope this solves the problem. 
```
                            RaisedButton(
                              onPressed: () {},
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: <Widget>[
                                  Text('Edit'),
                                  Icon(Icons.edit)
                                ],
                              ),
                              /*color: Colors.purple,*/
                            ),
```

**Comment by bagintz** [comment]
While it feels "wrong", if you are only wanting to right align the icon, you can switch the icon and label values since they are both just widgets.
