### ISSUE TITLE
Question about ListViews

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#24003]
Is there a way to know when a widget is in view. ex: Like in facebook when you scroll the feed the video starts playing when it is in view and stops when it is not

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/51069712/how-to-know-if-a-widget-is-visible-within-a-viewport/51071161#51071161 shows an approach

**Comment by rlee1990** [comment]
@zoechi i will give that a try

**Comment by rlee1990** [comment]
@zoechi That really wasn't much help. My issue is needing to know when something has come into view. For example say you have a social feed with tons of post and you use a list view to display each post. I would want to know when each post is currently being viewed. I tried with the scrollview option and tried using the listview index but didnt help.

**Comment by zoechi** [comment]
@rlee1990 I'd suggest you create a new question on StackOverflow that properly explains your concrete problem and why the linked SO question doesn't solve your problem.
