### ISSUE TITLE
Duration operator == doc isn't quite right

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#24006]
The doc for  Duration's `operator ==` overload says:
```
Returns true if this Duration is the same object as other.
```

Which sounds like an  `identical` comparison.  It should say something like "Returns true if the Durations represent the same time values".

**Comment by zoechi** [comment]
I think https://github.com/dart-lang/sdk/issues would be the right place to report that.

(https://api.dartlang.org/stable/2.1.0/dart-core/Duration/operator_equals.html)

**Comment by HansMuller** [comment]
OK, reported as a Dart issue: https://github.com/dart-lang/sdk/issues/35273
