### ISSUE TITLE
Android sign key is different at Playstore

### ISSUE THREAD

**Issue by sleith** [flutter/flutter#24000]
Hi,
I've followed the instruction on how to build release apk.
I make sure the apk's sha1 the same as the keystore has, by unzip the apk and 

> keytool -printcert -file CERT.RSA

the CERT.RSA file at META-INF.

I upload the apk to the playstore's alpha release.
I found out that the google map is not working. And I see the log, it's telling me the different sha1.
ANDROID_ID is also different. So I believe the sign key somehow different.
I already tried adb install directly the apk to my device, it works just fine.
I checked the debug.keystore has different sha1 too. So I'm not sure which key is being used.
 
Here's my flutter version:
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

Any idea what happened?
Thank you

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Please also add the full and exact log output related to 

> it's telling me the different sha1.
ANDROID_ID is also different.
