### ISSUE TITLE
Last update master channel have issue!

### ISSUE THREAD

**Issue by kalismeras61** [flutter/flutter#24010]
## Steps to Reproduce

1. I just update my master channel to last version after that it's look like normal but when i click somewhere on screent it's automaticly crashed!
2. After that i can not gesture on my app.
3. Log are below.

## Logs

```
Performing hot restart...
Syncing files to device iPhone 8...
Restarted application in 1.658ms.
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
'package:flutter/src/gestures/converter.dart': error: line 243 pos 33: file:///Users/macosx/flutter/packages/flutter/lib/src/gestures/converter.dart:243:33: Error: The getter 'platformData' isn't defined for the class 'dart.ui::PointerData'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'platformData'.
            platformData: datum.platformData,
                                ^^^^^^^^^^^^
            platformData: datum.platformData,
                                ^

#0      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#1      ListQueue.addAll (dart:collection/queue.dart:715:25)
#2      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#3      _invoke1 (dart:ui/hooks.dart:159:13)
#4      _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
'package:flutter/src/gestures/converter.dart': error: line 243 pos 33: file:///Users/macosx/flutter/packages/flutter/lib/src/gestures/converter.dart:243:33: Error: The getter 'platformData' isn't defined for the class 'dart.ui::PointerData'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'platformData'.
            platformData: datum.platformData,
                                ^^^^^^^^^^^^
            platformData: datum.platformData,
                                ^

#0      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#1      ListQueue.addAll (dart:collection/queue.dart:715:25)
#2      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#3      _invoke1 (dart:ui/hooks.dart:159:13)
#4      _dispatchPointerDataPacket (dart:ui/hooks.dart:113:5)
```

```
Analyzing dkvburs...                                             

   info • Name non-constant identifiers using lowerCamelCase • lib/src/models/announcement_model.dart:4:24 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/src/models/announcement_model.dart:7:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/src/models/announcement_model.dart:11:20 • non_constant_identifier_names
   info • Unused import: 'package:flutter_cache_manager/flutter_cache_manager.dart' • lib/src/screens/home_page.dart:14:8 • unused_import
   info • The value of the field '_isLoading' isn't used • lib/src/screens/login_page.dart:24:8 • unused_field
   info • The value of the field '_name' isn't used • lib/src/screens/profile_page.dart:20:10 • unused_field
   info • The value of the field '_lastName' isn't used • lib/src/screens/profile_page.dart:21:10 • unused_field
   info • The value of the field '_bornDate' isn't used • lib/src/screens/profile_page.dart:22:10 • unused_field
   info • The value of the field '_phone' isn't used • lib/src/screens/profile_page.dart:23:10 • unused_field
   info • The value of the field '_mensei' isn't used • lib/src/screens/profile_page.dart:24:10 • unused_field
   info • Cancel instances of dart.async.StreamSubscription • lib/src/utils/connect.dart:8:42 • cancel_subscriptions

```

```
Macosxs-iMac:dkvburs macosx$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.3-pre.109, on Mac OS X 10.14 18A391, locale tr-TR)
    • Flutter version 0.10.3-pre.109 at /Users/macosx/flutter
    • Framework revision 23a7535a39 (77 minutes ago), 2018-11-06 09:12:48 -0800
    • Engine revision fb5b097e5c
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/macosx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4999

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone 8 • F33B1D9A-89E8-42B7-91F4-02E458BCE376 • ios • iOS 11.2 (simulator)

```

**Comment by dnfield** [comment]
Tenatively marking TODAY, feel free to remove if this was an intended change.

**Comment by sbaranov** [comment]
Your hashes look correct. Please try flutter clean and report results.

**Comment by sbaranov** [comment]
If that doesn't help, please also try "flutter precache && flutter clean".

**Comment by MaxZeng** [comment]
same issue....

`[+3298 ms] 
                    Compiler message:
[   +2 ms] file:///Users/uc/development/flutter/packages/flutter/lib/src/gestures/converter.dart:243:33: Error: The getter 'platformData' isn't defined for the class
           'dart.ui::PointerData'.
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'platformData'.
[        ]             platformData: datum.platformData,
[        ]                                 ^^^^^^^^^^^^
[+1217 ms] "flutter bundle" took 4,849ms.
Compiler failed on /Users/uc/AndroidStudioProjects/newsflow/lib/main.dart

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      build (package:flutter_tools/src/bundle.dart:94:7)
<asynchronous suspension>
#2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:89:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:400:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:334:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:325:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:109:11)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#32     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#33     run (package:flutter_tools/runner.dart:51:10)
#34     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#35     main (file:///Users/uc/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#36     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

`

**Comment by MaxZeng** [comment]
I use the flutter v0.10.3-pre too, and I downgrade it to v0.10.2, everything works fine.

 @kalismeras61 you can try to downgrade flutter by :
```
 rm -rf flutter
git clone -b beta https://github.com/flutter/flutter.git
```

**Comment by kalismeras61** [comment]
I switch my channel to beta and after that again switch to back now working :) its bullshit but working now :)
