### ISSUE TITLE
Url_launcher - Launching URL despite bad status code

### ISSUE THREAD

**Issue by Jak3-02** [flutter/flutter#24012]
Using url_launcher I can launch a url, say [https://httpstat.us/200](url) which simulates status code 200: ok and url_launcher launches this url fine.

I'm looking for a way in which to force url_launcher to launch a different, often broken link such as 
[https://httpstat.us/204](url) which returns status code 204: no content.

In my code I launch run my specific launch_url algorithm on button press, but as I execute this nothing happens.

Over at https://stackoverflow.com/questions/53163110/flutter-how-to-launch-url-despite-bad-status-code I asked this question and I've been directed over here to either gain more insight into solving this or to issue a feature request.

Thanks, Jake

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

What is the exact behavior you are expecting?
Should the browser show the error message (204)?
Should the call to url_launcher throw an exception?
Others?
