### ISSUE TITLE
Have flutter doctor identify unpaired devices

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#24030]
When running `flutter doctor` with an unpaired iOS device attached to the host, the following error message is emitted:
```
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
```

libimobiledevice includes the tools to determine whether a device is paired, so it would be relatively straightforward to have `flutter doctor` and `flutter devices` detect and list unpaired devices (pairing state can be checked via `idevicepair -u DEVICE_UDID validate`) and suggest running a new command `flutter pair DEVICE_UDID` which would invoke `idevicepair -u DEVICE_UDID pair` to pop up the trust dialog on the phone and pair the device.

**Comment by iapicca** [comment]
Hi @cbracken  is this issue still meant to be open?

**Comment by zanderso** [comment]
@christopherfujino @jmagman Any thoughts on this? It seems like there might be two items:
1. A doctor validator or device discovery mechanism to list unpaired devices as part of `flutter doctor` or `flutter devices`.
2. Some way in the tool to trigger the pairing flow.

**Comment by jmagman** [comment]
I'd rather instruct the user how to trigger pairing rather than doing it automatically.  

I'd be okay with instructing them to run `idevicepair -u DEVICE_UDID pair` instead of wrapping it around a flutter command.  Though usage data might be interesting?

**Comment by zanderso** [comment]
If we add a new `DoctorValidator` that informs about unpaired devices, the result will get plumbed to analytics: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L284

**Comment by christopherfujino** [comment]
Yeah, adding a doctor validator and then checking the analytics after sounds good to me. It's not a big deal, but it will require editing the LUCI recipe to include `idevicepair` (which we build but don't bundle).

**Comment by jmagman** [comment]
This is partially done.  When there are no available devices, the diagnostic message says:

![Screen Shot 2020-02-19 at 1 09 03 PM](https://user-images.githubusercontent.com/682784/74876758-19c74900-5319-11ea-9ded-d8670eec0b9d.png)

However you attach another paired device or launch an emulator, it doesn't show any diagnostic messages.

**Comment by zanderso** [comment]
@jmagman Was there more progress on this recently?

**Comment by jmagman** [comment]
Yes indeed! https://github.com/flutter/flutter/pull/57532 will always show device errors in doctor, which include iOS pairing issues, even if other devices are successfully available.
```
$ flutter devices
1 connected device:

Pixel 4 • 98281FFAZ005T6 • android-arm64 • Android 10 (API 29)

• Error: Jenn's iPhone is not paired with your computer. To use Jenn's iPhone with Xcode, unlock it and choose to trust this computer when prompted. (code -9)
```
It doesn't say to run `idevicepair` but the error messages usually contain some recovery text like the above.

@cbracken let us know if there's more to do here.  Closing for now.
