### ISSUE TITLE
Skia Failure: App Fails to Display on Android 7

### ISSUE THREAD

**Issue by kunit1** [flutter/flutter#24035]
## Steps to Reproduce
- Same Exact Code, same exact device. Android 6.0.1 upgraded to Android 7.0
- App fails to display (only white screen)
- Skia log dump:

`D/skia    ( 3542): Program linking failed.
D/skia    ( 3542): L0001 Invalid shader type loaded
D/skia    ( 3542): Program linking failed.
D/skia    ( 3542): VS:
D/skia    ( 3542): SKSL:
D/skia    ( 3542):    1	#version 320 es
D/skia    ( 3542):    2	uniform float4 sk_RTAdjust;
D/skia    ( 3542):    3	in float2 inPosition;
D/skia    ( 3542):    4	in half4 inColor;
D/skia    ( 3542):    5	out half4 vcolor_Stage0;
D/skia    ( 3542):    6	void main()
D/skia    ( 3542):    7	{
D/skia    ( 3542):    8		// Primitive Processor DefaultGeometryProcessor
D/skia    ( 3542):    9		half4 color = inColor;
D/skia    ( 3542):   10		vcolor_Stage0 = color;
D/skia    ( 3542):   11		float2 pos2 = inPosition;
D/skia    ( 3542):   12		sk_Position = float4(pos2.x , pos2.y, 0, 1);
D/skia    ( 3542):   13	}
D/skia    ( 3542):   14
D/skia    ( 3542): GLSL:
D/skia    ( 3542):    1	#version 320 es
D/skia    ( 3542):    2
D/skia    ( 3542):    3	precision mediump float;
D/skia    ( 3542):    4	uniform highp vec4 sk_RTAdjust;
D/skia    ( 3542):    5	in highp vec2 inPosition;
D/skia    ( 3542):    6	in mediump vec4 inColor;
D/skia    ( 3542):    7	out mediump vec4 vcolor_Stage0;
D/skia    ( 3542):    8	void main() {
D/skia    ( 3542):    9	    mediump vec4 color = inColor;
D/skia    ( 3542):   10	    vcolor_Stage0 = color;
D/skia    ( 3542):   11	    highp vec2 pos2 = inPosition;
D/skia    ( 3542):   12	    gl_Position = vec4(pos2.x, pos2.y, 0.0, 1.0);
D/skia    ( 3542):   13	    gl_Position = vec4(gl_Position.xy * sk_RTAdjust.xz + gl_Position.ww * sk_RTAdjust.yw, 0.0, gl_Position.w);
D/skia    ( 3542):   14	}
D/skia    ( 3542):   15`

`[√] Flutter (Channel dev, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale en-CA)
    • Flutter version 0.10.2 at D:\flutter
    • Framework revision d8cbb80206 (12 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\kusay\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.28.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • SM G920W8 • 0216029abaa90a03 • android-arm64 • Android 7.0 (API 24)

• No issues found!`

**Comment by ITJammish** [comment]
Hi @kunit1, I am seeing the same issue with my app. How was this issue resolved in the end?

Any info would be awesome, thank you!

**Comment by kunit1** [comment]
Hi @ITJammish 
That's exactly what I had to do, the app had to be reinstalled. I had to uninstall the existing app off my test device and then build another copy to be deployed.

I am not sure if the issue I saw is the same as the one you referenced but it definitely looks similar.

**Comment by BruceHuang** [comment]
I use the google Launcher3 ，when i drag the icon ,the same issue ;
