### ISSUE TITLE
Add API to support fetching current notification setting

### ISSUE THREAD

**Issue by bood** [flutter/flutter#24047]
Current firebase_messaging package only support get the notification setting after client called `requestNotificationPermissions`. But our project wants to know the setting before the system prompt, so that we do not have to show the permission page if user already grant us the permission.

It looks like below API on iOS:
https://developer.apple.com/documentation/uikit/uiapplication/1623092-currentusernotificationsettings?language=objc

**Comment by kroikie** [comment]
@bood

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/584. Any further collaboration will be done there.
