### ISSUE TITLE
Version incompatibilities in 0.10.2

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#24040]
As reported [here](https://groups.google.com/forum/#!topic/flutter-dev/HcSRnNxj7Mo):

```
$ flutter upgrade
...


All good with no complaints until:

Running "flutter packages upgrade" in hoekapp...               
The current Dart SDK version is 2.1.0-dev.8.0.flutter-bf26f760b1.

Because build >=0.12.7+2 <1.0.1 depends on analyzer >=0.27.1 <0.33.0 and build >=0.0.1+1 <=0.12.7 requires SDK version <2.0.0 or >=2.0.0-dev.9 <2.0.0, build >=0.0.1+1 <1.0.1 requires analyzer >=0.27.1 <0.33.0.
And because every version of flutter_test from sdk depends on analyzer 0.33.0, flutter_test from sdk is incompatible with build >=0.0.1+1 <1.0.1.
And because build_runner >=0.9.1+1 <0.10.3 depends on build >=0.12.7 <0.12.8 and build_runner >=0.1.1 <=0.9.1 requires SDK version >=1.9.1 <2.0.0-∞, flutter_test from sdk is incompatible with build_runner >=0.1.1 <0.10.3.
So, because vollyapp depends on both build_runner ^0.9.0 and flutter_test any from sdk, version solving failed.
 
pub upgrade failed (1)


johan@beast:~/vz/vollyapp$ flutter doctor -v
[✓] Flutter (Channel beta, v0.10.2, on Linux, locale en_US.UTF-8)
    • Flutter version 0.10.2 at /home/johan/flutter
    • Framework revision d8cbb80206 (12 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /home/johan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```

Marking as a release blocker until we triage and see how prevalent it is.

**Comment by tvolkert** [comment]
@lonoami if you bump your version constraint on `build_runner` (the latest version is `1.1.1`, and you're specifying a constraint of `^0.9.0`), does this go away?

**Comment by grouma** [comment]
Jake want to take a look at this. Likely due to your recent changes?

**Comment by jonahwilliams** [comment]
Most likely the analyzer got bumped via normal `flutter update-packages --force-upgrade` sometime ~2 weeks ago, and this ends up running ahead of build releases. (hence why it was so important to remove the analyzer dep)

flutter_test doesn't depend on analyzer anymore so the problem is solved for future users. Otherwise I'm not sure what else we can do here, besides release new versions.

**Comment by lonoami** [comment]
@jonahwilliams 
One thing you can do is help me get it working.
I can still build with the previous version but sooner or later I will be hosed.
Please LMK if you have time and what file(s) you need.

**Comment by tvolkert** [comment]
@lonoami try `flutter channel master && flutter upgrade`, and see if it works on the master channel.  If so, then short of fiddling with version constraints, you just need to wait until tip-of-tree master makes its way to the `beta` channel (typically about 4 weeks).

**Comment by jonahwilliams** [comment]
@lonoami you will also need to bump the version of json_annotation to be compatible. I don't believe there have been any _real_ breaking changes in these packages so this should be safe to do. 

Something else you could try is to delete any pubspec.lock file and then replace all of your version constraints with `any`. Then see what versions pub gives you and fill them in afterwards. For example:

```
dev_dependencies:
  build_runner: any
  json_annotation: any
```
This is a bit of a scorched earth approach, but generally if you've pinned certain packages to a specific version you're going to have trouble upgrading only a subset of them

**Comment by lonoami** [comment]
Thanks for the help @jonahwilliams  and @tvolkert .
I'll wait 4 weeks like you suggest.
Here is my [pubspec.yaml](https://pastebin.com/03W09603)
No need to read just thought it may be interesting.

**Comment by zoechi** [comment]
I believe this to be solved.

**Comment by lonoami** [comment]
I think you are right.
No problem after updating.

**Comment by madeyinka007** [comment]
Thanks Guys
