### ISSUE TITLE
how to play a image frame animation?

### ISSUE THREAD

**Issue by hyz1992** [flutter/flutter#24046]
I tried to use a changed Image widget, I have 34 frames, so if I play this animation when there are not cached, It looks very hard.
Is there any other way to show a frame animation?

Or if I use gif image,hao can I close the animation when it completed instead of repeated forever?
And how to make sure gif play start with the frist frame when didUpdateWidget called?

**Comment by beckler** [comment]
I believe you may need to create your own [ImageProvider](https://docs.flutter.io/flutter/painting/ImageProvider-class.html). In your provider you'll need to override the `load()` method and then implement a [MultiFrameImageStreamCompleter](https://docs.flutter.io/flutter/painting/MultiFrameImageStreamCompleter-class.html). In that completer you'll need to attach a [ImageListener](https://docs.flutter.io/flutter/painting/ImageListener.html) to handle it from there.

I would recommend looking at the source for existing image providers first: [image_provider.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_provider.dart). Here's the specific implementation for [FileImage](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_provider.dart#L521-L575).

The simplest way to do this would be to extend an existing provider (like `FileImage`), override the `load()` method with your own completer, and then use your custom provider for those specific images.

Here's an example of what I'm talking about (**UNTESTED**):
```dart
class AnimatedFileImage extends FileImage {

  final ImageListener listener;
  final ImageErrorListener errorListener;

  const AnimatedFileImage(File file, {
    double scale = 1.0,
    this.listener,
    this.errorListener,
  }) : super(file, scale)

  // private method carried over from FileImage
  Future<ui.Codec> _loadAsync(FileImage key) async {
    assert(key == this);

    final Uint8List bytes = await file.readAsBytes();
    if (bytes.lengthInBytes == 0)
      return null;

    return await PaintingBinding.instance.instantiateImageCodec(bytes);
  }

  @override
  ImageStreamCompleter load(FileImage key) {
    final MultiFrameImageStreamCompleter completer = MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: key.scale,
      informationCollector: (StringBuffer information) {
        information.writeln('Path: ${file?.path}');
      }
    );
    if (this.listener) {
      completer.addListener(this.listener, onError: this.errorListener);
    }
    return completer;
  }
}

///
/// ...later on in your code...
///

final ImageErrorListener errorListener = (dynamic exception, StackTrace stackTrace) {
  // ... handle error ...
};
final ImageListener listener = (ImageInfo info, bool synchronous) {
  // ... do whatever ...
};
AnimatedFileImage myAnimatedImage = AnimatedFileImage(File, listener: listener, errorListener: errorListener);
```

**Comment by hyz1992** [comment]
thank you very much! I will hava a try!

**Comment by beckler** [comment]
I thought about this a little more, and there is an easier way to write that class.

```
class AnimatedFileImage extends FileImage {

  final ImageListener listener;
  final ImageErrorListener errorListener;

  const AnimatedFileImage(File file, {
    double scale = 1.0,
    this.listener,
    this.errorListener,
  }) : super(file, scale)

  @override
  ImageStreamCompleter load(FileImage key) {
    final MultiFrameImageStreamCompleter completer = super.load(key);
    if (this.listener) {
      completer.addListener(this.listener, onError: this.errorListener);
    }
    return completer;
  }
}
```

**Comment by hyz1992** [comment]
I haven't verified yet, but I think it will be perfect.
Thanks very much!

**Comment by hyz1992** [comment]
@beckler hello,I find a new way about this:

```
Future<List<ImageInfo>> preloadImage({
  @required ImageProvider provider,
  @required BuildContext context,
  int frameNum:1,
  Size size,
  ImageErrorListener onError,
}) {
  final ImageConfiguration config = createLocalImageConfiguration(context, size: size);
  final Completer<List<ImageInfo>> completer = new Completer<List<ImageInfo>>();
  final ImageStream stream = provider.resolve(config);
  List<ImageInfo> ret = [];
  void listener(ImageInfo image, bool sync) {
    print("$image");
    ret.add(image);
    if(ret.length==frameNum){
      completer.complete();
    }
  }
  void errorListener(dynamic exception, StackTrace stackTrace) {
    try{
      completer.complete();
    }catch(e){}
    if (onError != null) {
      onError(exception, stackTrace);
    } else {
      FlutterError.reportError(new FlutterErrorDetails(
        context: 'image failed to precache',
        library: 'image resource service',
        exception: exception,
        stack: stackTrace,
        silent: true,
      ));
    }
  }
  stream.addListener(listener, onError: errorListener);
  completer.future.then((List<ImageInfo> _) { stream.removeListener(listener); });
  return completer.future;
}
```

**Comment by q805699513** [comment]
@hyz1992你好，请问下怎么实现帧布局。preloadImage方法怎么使用。

**Comment by hyz1992** [comment]
@q805699513 不太明白你说的帧布局是什么意思，preloadImage的用法可以参考[gif_ani](https://github.com/hyz1992/gif_ani.git)

**Comment by q805699513** [comment]
@hyz1992请问下一组图片组合成的帧动画，你这个是加载gif好像。我已经用动画实现了，就是不停切换image控件上的图片资源达到效果。看下有没有更好的实现方式。
