### ISSUE TITLE
Card's API docs: move screenshots above the sample code

### ISSUE THREAD

**Issue by galeyang** [flutter/flutter#24079]
From a recent study, we found screenshots helped participants immediately determine if this is the right UI widget to use. Next, they looked for code samples to learn how to use a widget.

In the current [`Card` widget API doc](https://docs.flutter.io/flutter/material/Card-class.html), participants needed to scroll back and forth a couple of times to notice the screenshot which is displayed below the code. 

**Proposed order:**
1. (introduction)
2. screenshot
3. sample code

cc: @gspencergoog as you recently updated the sample code UI on this page.

**Comment by zoechi** [comment]
Seems this is fixed already. Can you please check?

**Comment by gspencergoog** [comment]
Yes, this is fixed.
