### ISSUE TITLE
Consolidating flutter.io and docs.flutter.io analytics

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#24072]
We'd like to consolidate analytics from both flutter.io and docs.flutter.io by using the same Google Analytics (GA) ID, and it should be doable since they are under the same domain.  

GA was initially added to docs.flutter.io in this PR https://github.com/flutter/flutter/pull/966, which was different from [the one used by flutter.io](https://github.com/flutter/website/blob/18f758d3b3251473d87dbf9b2003740f92283ec0/src/_includes/head.html#L47).

**Comment by InMatrix** [comment]
Cc: @gspencergoog 

Is this something you could help with? Thanks!

**Comment by gspencergoog** [comment]
So, you basically want me to change `UA-67589403-2` (docs analytics) to `UA-67589403-1` (flutter.io analytics), right?

**Comment by InMatrix** [comment]
Yes, that's it.
