### ISSUE TITLE
Flexible header height for expanded panels?

### ISSUE THREAD

**Issue by SkydiveMarius** [flutter/flutter#24071]
I noticed that the header height (edge insets)
https://github.com/flutter/flutter/blob/fbafe64fd7fa10d18375afeba954aea1e62a491e/packages/flutter/lib/src/material/expansion_panel.dart#L250
of an expanded expansion panel is fixed to 64
https://github.com/flutter/flutter/blob/fbafe64fd7fa10d18375afeba954aea1e62a491e/packages/flutter/lib/src/material/expansion_panel.dart#L13

Is there any special reason for this implementation (e.g. Material UI constraints)?
Or in other words: What about making this a dynamic property?

Thank you for your opinion!

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/expansion_panel.dart#L250

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/expansion_panel.dart#L13

**Comment by zgosalvez** [comment]
I wanted to use a different icon for ExpansionPanel but the property is not available. So I created my own using ListView and AnimatedContainer but I can't get it to expand without having a fixed height. What I want to happen is for the ExpansionPanel/AnimatedContainer to expand to fit the body/child's height. 

```dart
AnimatedContainer(
	duration: Duration(milliseconds: 300),
	child: Container(
		child: Text(widget.subtitle),
		padding: EdgeInsets.only(top: 8),
	),
	curve: Curves.easeInOut,
	// height: _isExpanded ? <cannot be determined> : 0,
);
```

**Comment by SkydiveMarius** [comment]
Closing issue, as pull request https://github.com/flutter/flutter/pull/47951 is merged.
