### ISSUE TITLE
Tapping items is not working in CupertinoPicker

### ISSUE THREAD

**Issue by rockingdice** [flutter/flutter#24089]
For native pickers in iOS, tapping an item will act like scrolling to it. I think the CupertinoPicker should work the same way.

**Comment by panuavakul** [comment]
I am also having problem with this.

I tried to scroll manually to the tapped cell by adding `GestureDector` to each of the item inside but the onTap gesture does not seems to get called, not sure but maybe something else is intercepting the touch event so it does not work.

**Comment by xster** [comment]
I didn't copy that interaction over initially because picker item tapping is such a wonky interaction in native iOS :)

Worth adding it in at some point.

**Comment by vanlooverenkoen** [comment]
I think this should be configurable.

**Comment by anhdhq** [comment]
**Have the problem resolved yet?**

**Comment by Kobreizhyashi** [comment]
Same question !

**Comment by michaelchevallier** [comment]
Same problem here, however awaiting possible resolution I have a quick fix with a gesture detector around your CupertinoPicker:

where:
- itemExtent is your CupertinoPicker itemExtent
- diameterRatio is your

GestureDetector(
        onTapDown: (details) {
        
          // position of the top most visible index converted to an offset
          final zeroPositionOffset =
              ((_diameterRatio * itemExtent / 2) / itemExtent).floor();
              
          // position of the selected index from the top of the screen converted to an index offset
          final selectedOffset = (details.localPosition.dy / _itemExtent).ceil();
          
          controller.animateToItem(
              controller.selectedItem - zeroPositionOffset + selectedOffset,
              duration: Duration(milliseconds: 500),
              curve: Curves.decelerate);
        },
        child: CupertinoPicker(....),
    )

**Comment by ziqq** [comment]
Same question!

**Comment by rockingdice** [comment]
Is this still on the track?

**Comment by nt4f04uNd** [comment]
Self assigning to fix it after https://github.com/flutter/flutter/issues/38803

**Comment by nt4f04uNd** [comment]
Unassigning, since I am currently not working on it.

For anyone interested in fixing it - it should be a relatively easy fix though, now that ListWheelScrollView actually registers taps :-)
