### ISSUE TITLE
Drop the chromium-specific stuff from our build bot pages

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2408]
All the stuff at the top of https://build.chromium.org/p/client.flutter/waterfall is irrelevant to us.

**Comment by abarth** [comment]
I attempted this in https://codereview.chromium.org/1695973002 but there was some magic pixie dust I was missing.

**Comment by eseidelGoogle** [comment]
These days we just have our own front-end instead.  But we could still do this if necessary.

**Comment by Hixie** [comment]
We're not going to worry about this.
