### ISSUE TITLE
Plugin Header file not found

### ISSUE THREAD

**Issue by Edward608** [flutter/flutter#24099]
Recently I developed a plugin [system_setting](https://pub.dartlang.org/packages/system_setting), while it works fine in the example app inside the plugin. It cannot compile when using in other projects. 

The problem is `system_setting/system_setting-Swift.h` not found. This header file seems to be generated. But I can't find any information about it. Most of the plugins on pub are written in obj-c, so can't really get any hints from them. 

Here's the result of `flutter doctor -v`:
```
[✓] Flutter (Channel master, v0.10.3-pre.90, on Mac OS X 10.14 18A391, locale en-HK)
    • Flutter version 0.10.3-pre.90 at /Users/edwardwong/flutter
    • Framework revision db9fe3f827 (4 days ago), 2018-11-04 03:20:44 +0100
    • Engine revision 88cb78cdf6
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/edwardwong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/edwardwong/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4999

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by zoechi** [comment]
> The problem is system_setting/system_setting-Swift.h

Please add the full and exact error output

**Comment by Edward608** [comment]
<img width="903" alt="screenshot 2018-11-14 at 16 16 45" src="https://user-images.githubusercontent.com/11601877/48469069-b94d8000-e828-11e8-9534-4c2a2767be57.png">
This is all I get when compiling. Later I found this is caused by missing `use_frameworks!` in the `Podfile`. Adding that line back to `Podfile` fixes the issue. 

However I don't know how to use this together with `firebase_messaging`, as the instructions said I need to remove the `use_frameworks!` from `Podfile`. This is a huge conflict.

**Comment by keithbhunter** [comment]
I see this same problem with other Swift plugins. It seems that a plugin created with the `-i swift` modifier can only be used in an app created with the `-i swift` modifier. If you just use `flutter create some_app`, it will create it with Objective-C in mind and will not allow you to use Swift plugins (showing the error `some_app-Swift.h not found`).

**Comment by zoechi** [comment]
Related to #16049

**Comment by neiljaywarner** [comment]
@zoechi  is there any update on this please?

**Comment by solaamy** [comment]
I have exactly the same issue as @keithbhunter  mentioned. Does anyone have any solutions on this?

**Comment by kroikie** [comment]
@Edward608

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/582. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since this is not a Firebase related issue I will reopen this issue here.

**Comment by lockelost** [comment]
Is this issue resolved?
I'm having the same problem.
Build for a physical or generic device for 'Run' succeeds 
but Archive fails with the error saying plug-in header not found.

$ flutter --version

> Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
> Engine • revision b863200c37
> 

$ flutter doctor -v

> [✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en)
>     • Flutter version 1.9.1+hotfix.6 at /Users/????/development/flutter
>     • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/????/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B500
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Connected device (1 available)
>     • ????s iPhone • ??????-????? • ios • iOS 13.1.3

**Comment by alex-misch** [comment]
I have same issue. All the plugins that I set in `pubspec.yaml` in `dependency` section fails when I try to archive product. The `GeneratedPluginRegistrant.m` has few imports like below
```
#if __has_include(<path_provider/PathProviderPlugin.h>)
#import <path_provider/PathProviderPlugin.h>
#else
@import path_provider;
#endif
```
It is fails on each with message `Module '<module name here>' not found`.
Little remark: we work on project in a team of 3 people and all can publish archive project besides me. `flutter upgrade` `flutter pub cache restore` did nothing. The command `flutter run build` and xcode build to simulator or physical device works fine.

**Comment by Garciconx** [comment]
> I have same issue. All the plugins that I set in `pubspec.yaml` in `dependency` section fails when I try to archive product. The `GeneratedPluginRegistrant.m` has few imports like below
> 
> ```
> #if __has_include(<path_provider/PathProviderPlugin.h>)
> #import <path_provider/PathProviderPlugin.h>
> #else
> @import path_provider;
> #endif
> ```
> 
> It is fails on each `@import` with message `Module '<module name here>' not found`.
> Little remark: we work on project in a team of 3 people and all can publish archive project besides me. `flutter upgrade` `flutter pub cache restore` did nothing. The command `flutter run build` and xcode build to simulator or physical device works fine.
> 
> `flutter doctor -v`:
> 
> ```
> [✓] Flutter (Channel dev, v1.12.11, on Mac OS X 10.15.1 19B88, locale en-RU)
>     • Flutter version 1.12.11 at /Users/alexandrmishchenko/development/flutter
>     • Framework revision f40dbf8ca0 (5 days ago), 2019-11-23 01:02:54 -0500
>     • Engine revision d1cac77d5a
>     • Dart version 2.7.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
>     • Android SDK at /Users/alexandrmishchenko/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling
>       support)
>     • Platform android-29, build-tools 29.0.1
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B500
>     • CocoaPods version 1.8.4
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 37.1.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1343-b01)
> 
> [✓] VS Code (version 1.40.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.6.0
> 
> [✓] Connected device (2 available)
>     • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
>     • Web Server • web-server • web-javascript • Flutter Tools
> ```

same issue here!

**Comment by noobiek** [comment]
Hi everyone.
Same issue here. Xcode complains about missing plugins headers (.h) when I try to archive the project.

I'd like to add that I did not change anything in dependencies/project config. All changes were made to lib/ and pubspec.yaml (version/build number) files only and still I started to get this error.

**Comment by noobiek** [comment]
Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/

**Comment by alex-misch** [comment]
> Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/

Thank you! It worked for me too. Saved a lot of my time. :)

**Comment by lockelost** [comment]
> Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/

OMG, it works for me too. Feeling so embarrassed. XD

**Comment by drexel-ue** [comment]
So i attempted 

>  Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/

And when i open the .workspace the option to archive is not available...just greyed out...

**Comment by alex-misch** [comment]
> So i attempted
> 
> > Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/
> 
> And when i open the .workspace the option to archive is not available...just greyed out...

Let you select "generic iOS device" in device selector (top right corner) and get a fun :)

**Comment by jmagman** [comment]
Closing as a combo of https://github.com/flutter/flutter/issues/25676 and https://github.com/flutter/flutter/issues/10770.
See also https://github.com/flutter/flutter/issues/16049#issuecomment-552060349

**Comment by konnect-ibbi** [comment]
> Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/

Not working with me. Is there anyone who has any idea how to solve this issue?

**Comment by WillianKirsch** [comment]
> Xcode

Thanks for the @konnect-ibbi contribution! It worked for me.

**Comment by WillianKirsch** [comment]
> Doh ... desculpe pessoal. Reiniciei o Xcode e reabri meu projeto pelo arquivo .workspace (não .project). Tudo começou a arquivar novamente. : - /

Thanks for the contribution @noobiek! It worked for me.

**Comment by zkhCreator** [comment]
Maybe remove `use_framework!` from Podfile. It worked for me.

**Comment by highdee11** [comment]
> > Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/
> 
> Not working with me. But after wasting two days looking for a solution, I found issue with pod target and project deployment target.
> Pod target platform: ios 11.0
> Project target: ios 8.0
> I changed the target to 11.0 and it worked.

I changed only my project target from 10.0 to 11.0
