### ISSUE TITLE
Optional to hide CupertinoTabBar

### ISSUE THREAD

**Issue by tungvn** [flutter/flutter#24095]
I'm not actually sure whether this is a flutter issue or a usage issue. Either way, I want to hide the CupertinoTabBar in some specific screens.
Imagine my app widget tree is:
```
MaterialApp
 - Login => To log in and navigate to Dashboard
 - Dashboard (is CupertinoTabScaffold with parallel bottom navigation bar by CupertinoTabBar)
  - A (a tab) => CameraPage => Submit Form (also have the bottom navigator bar)
  - B (a tab) => Foo
  - C (a tab) => Baa
```
Everything is work perfectly, exclude the Camera page always have the bottom navigation bar. I tried using the `Navigator.of(context, rootNavigator: true)` and the navigator bar is been hide, but when I press a button to navigate to Submit Form, this page will be lost the navigator too.
Reallity, I want the CupertinoTabBar have a property (let say `isShow`) and when isShow is false, the navigator will be move out the screen by transform, etc.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by xster** [comment]
What are you referring to as 'this page' in
> I press a button to navigate to Submit Form, this page will be lost the navigator too.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by jibiel** [comment]
@xster Considering the reactions here and in #55611 it may still be a desirable feature so I'll try to clarify.

The author wants to display `CupertinoTabBar` on pages `A`, `B`, `C` (tabs, that's a default); hide it on the `CameraPage`, and display it again (unhide it) on the `SubmitForm`, possibly, with transitions, like sliding the tab bar off the screen and back.

**Comment by tungvn** [comment]
> 
> 
> What are you referring to as 'this page' in
> 
> > I press a button to navigate to Submit Form, this page will be lost the navigator too.

Long time no see, 'this page` is the `SubmitForm`
