### ISSUE TITLE
App crashes in second time running in android after latest upgrade  0.10.2

### ISSUE THREAD

**Issue by aboda1986** [flutter/flutter#24092]
## Steps to Reproduce

1. after start debugging mode at emulator  the app working fine for the first time,
when i close the app and run app again app is crashes.

## Logs
 flutter doctor

[√] Flutter (Channel beta, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.1)
[√] VS Code (version 1.28.2)
[√] Connected device (2 available)

```
```
## Debug Console

Built build\app\outputs\apk\debug\app-debug.apk.
D/        ( 7355): HostConnection::get() New Host Connection established 0x9a1a1600, tid 7379
D/EGL_emulation( 7355): eglMakeCurrent: 0x9756fb20: ver 3 0 (tinfo 0x9a1831f0)
D/skia    ( 7355): Program linking failed.
E/emuglGLESv2_enc( 7355): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glLinkProgram:1310 GL error 0x501
E/eglCodecCommon( 7355): glUtilsParamSize: unknow param 0x00008741
E/emuglGLESv2_enc( 7355): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetProgramBinary:3785 GL error 0x502
F/libc    ( 7355): /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
F/libc    ( 7355): Fatal signal 6 (SIGABRT), code -6 in tid 7379 (1.gpu)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170720.005/4205617:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 7355, tid: 7379, name: 1.gpu  >>> com.example.amanacapitalapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed'
eax 00000000  ebx 00001cbb  ecx 00001cd3  edx 00000006
esi 00001cd3  edi 8719cfb8
xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
eip a7b8fac4  ebp 8719cfd8  esp 8719cf6c  flags 00000296
backtrace:
#00 pc 00000ac4  [vdso:a7b8f000] (__kernel_vsyscall+16)
#01 pc 00075b3c  /system/lib/libc.so (tgkill+28)
#02 pc 0001f04e  /system/lib/libc.so (abort+110)
#03 pc 0002720e  /system/lib/libc.so (__libc_fatal+46)
#04 pc 0001f4b0  /system/lib/libc.so (__assert2+48)
#05 pc 0062ef04  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#06 pc 0062f377  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#07 pc 0062f179  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#08 pc 0062e7be  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#09 pc 0062e713  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#10 pc 00631c48  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#11 pc 00631c80  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#12 pc 007ea473  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#13 pc 007e5d66  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#14 pc 007e747b  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#15 pc 00771588  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#16 pc 00773824  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#17 pc 007a5df1  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#18 pc 007802fd  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#19 pc 007801d0  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#20 pc 0076d297  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#21 pc 0076d7d8  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#22 pc 007fa23b  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#23 pc 007fa14b  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#24 pc 006bf399  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#25 pc 009ebcb0  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#26 pc 0069a281  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#27 pc 006a0c03  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#28 pc 006a1066  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#29 pc 006a1324  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#30 pc 006a0f15  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#31 pc 006a1256  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#32 pc 0066a615  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#33 pc 0066a560  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#34 pc 0066c6a0  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#35 pc 00014977  /system/lib/libutils.so (_ZN7android20SimpleLooperCallback11handleEventEiiPv+39)
#36 pc 000157ac  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+988)
#37 pc 00015346  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+118)
#38 pc 00010e1e  /system/lib/libandroid.so (ALooper_pollOnce+94)
#39 pc 0066c7a3  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#40 pc 00668d86  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#41 pc 0066ae7b  /data/app/com.example.amanacapitalapp-rwWT-7UKykp5d5XtdkOYEg==/lib/x86/libflutter.so (offset 0x5c7000)
#42 pc 000709b5  /system/lib/libc.so (_ZL15__pthread_startPv+53)
#43 pc 0002050b  /system/lib/libc.so (__start_thread+75)
#44 pc 0001eda6  /system/lib/libc.so (__bionic_clone+70)
Lost connection to device.
Exited (sigterm)

```
```

```
```

**Comment by aboda1986** [comment]
in addition, the default counter app same the problem, that not related to project code

**Comment by JoeyMontero** [comment]
Same issue as in #24058 #24093

**Comment by namaye** [comment]
Same here..really frustating

**Comment by zoechi** [comment]
Merging with #24093

**Comment by TheBlueFrog** [comment]
Me too, fresh install of Flutter, Android Studio, using demo flutter app
