### ISSUE TITLE
"drive sample_app" step is failing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2409]
cc @yjbanov @chinmaygarde @eseidelGoogle

**Comment by yjbanov** [comment]
I sent [a CL](https://codereview.chromium.org/1760903003/#) to disable this step but the commit-bot hasn't been able to commit it for some reason.

**Comment by yjbanov** [comment]
Quick update. This step is still failing due to inability to launch Xcode. Unfortunately, I have to keep it running on the bot as this is the only way to test it that I know of.

**Comment by eseidelGoogle** [comment]
I believe recipes_api.py has some ways to make step failures non-fatal if that's helpful to you.

**Comment by yjbanov** [comment]
`recipes_api.py` actually doesn't define the `step()` method. Do you know how it's defined? Must be some Python magic that I'm not aware of.

**Comment by yjbanov** [comment]
I _think_ I found it: `fail_build_on_failure`.

**Comment by yjbanov** [comment]
False alarm. That parameter is not exposed by the `step()` function (one can never tell for sure with all the `**kwargs`).

**Comment by eseidelGoogle** [comment]
Looks like ok_ret could do what you want:
https://github.com/luci/recipes-py/blob/master/recipe_modules/step/api.py#L93

But there are probably lots of other ways.  You can ask on the recipes list for suggestions if you like.

**Comment by yjbanov** [comment]
`ok_ret` seems to work. Thanks! If not, I'll try Robbie's suggestion and simply catch the exception.

**Comment by yjbanov** [comment]
Fixed
