### ISSUE TITLE
What is the difference between Icons.battery_std and Icons.battery_full

### ISSUE THREAD

**Issue by Blaxou** [flutter/flutter#24096]
As mentionned in the title, is there any kind of difference between `Icons.battery_srd` and `Icons.battery_full` ? I can't seem to find any ?

**Comment by zoechi** [comment]
They are just the icons from https://material.io/tools/icons/?search=battery&style=baseline
If you have related questions please raise them there.
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
