### ISSUE TITLE
Widget constructors expect children in inconsistent ways

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#241]
<a href="https://github.com/ianloic"><img src="https://avatars.githubusercontent.com/u/604?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ianloic](https://github.com/ianloic)**
_Thursday Oct 29, 2015 at 20:28 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1872_

----

Some widgets (eg: Container) require a name `child:` argument to specify their children. Others (eg: Flex) take their children as the first argument. This inconsistency is confusing - especially as I switch between different container widgets.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 29, 2015 at 20:48 GMT_

----

Yeah, the pattern we've been using is that if you take one widget as a child, you use the name `child`.  If you take a list, then you use a positional argument.  Are you suggesting that we make the list widgets use the name `child` too?  Maybe `children`?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/ianloic"><img src="https://avatars.githubusercontent.com/u/604?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ianloic](https://github.com/ianloic)**
_Monday Nov 02, 2015 at 18:21 GMT_

----

I don't have a concrete suggestion other than it's a little confusing. Perhaps make the list widgets use children so that I'm forced to be explicit everywhere.

**Comment by tvolkert** [comment]
I think we should just always use named arguments for children, since the children argument often takes up many lines of code and usually reads best when it's the last argument passed to a constructor.

**Comment by abarth** [comment]
Will do.
