### ISSUE TITLE
On Linux, problems building an Android app that uses flavor dimensions with uppercase characters

### ISSUE THREAD

**Issue by jorgecoca** [flutter/flutter#24106]
Happening on latest beta ([✓] Flutter (Channel master, v0.10.3-pre.145, on Mac OS X 10.13.6 17G3025, locale en-US))

I have a Flutter app that uses the following flavor dimensions scheme (Gradle):

```gradle
flavorDimensions "brand", "region"
    productFlavors {
        BRAND1 {
            dimension "brand"
            applicationIdSuffix ".brand1"
        }
        BRAND2 {
            dimension "brand"
            applicationIdSuffix ".brand2"
        }
        northAmerica {
            dimension "region"
            applicationIdSuffix ".northamerica"
        }
        spain {
            dimension "region"
            applicationIdSuffix ".spain"
        }
    }
```

When running the app, this is the run command that I use:
```
flutter run -t lib/main/main_brand1_north_america_debug.dart --flavor BRAND1NorthAmerica
```

While this works perfectly on iOS, on Android I get the following error:

```
➜  git:(master) flutter run -t lib/main/main_brand1_north_america_debug.dart --flavor BRAND1NorthAmerica
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main/main_brand1_north_america_debug.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    2.4s

The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file defines product flavors: brand1, brand1spain, brand1northamerica, brand2, brand2spain, brand2northamerica
You must specify a --flavor option to select one of them.
Gradle build aborted.
```

As you can see, there's a problem where the product flavors are lowercased, but those do not match the gradle tasks available.

If I follow the recommendation of the error message and try to lowercase the flavor, it still fails:

```
➜  mobile_connected git:(master) flutter run -t lib/main/main_brand1_north_america_debug.dart --flavor brand1northamerica
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main/main_brand1_north_america_debug.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    2.1s
Gradle task 'assembleBrand1northamericaDebug'...
Gradle task 'assembleBrand1northamericaDebug'... Done          3.7s
Gradle build failed to produce an Android package.
```

And it is because that gradle task does not exist.

**Comment by jorgecoca** [comment]
It is still an issue on:

```
➜  flutter git:(master) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.5-pre.29, on Mac OS X 10.13.6 17G3025, locale en-US)
```

The other linked issue has been marked as closed too when it shouldn't.

**Comment by jorgecoca** [comment]
any progress on this issue? is there anything that I can do to help?

**Comment by zoechi** [comment]
> The other linked issue has been marked as closed too when it shouldn't.

https://github.com/flutter/flutter/commit/422e56c29cb4b0feb7501aaa3cb68e0a3f4fe5c4 was supposed to fix #19507.

Is the issue still exactly the same as in the initial report?

**Comment by jorgecoca** [comment]
It is exactly the same issue, but the changes introduced did not completely fix the issue, and I think that's where the confusion is coming from.

**Comment by jorgecoca** [comment]
This is still an issue in `1.0.0`. Is there an ETA for this fix?

**Comment by truongsinh** [comment]
any update?

**Comment by iqbalmineraltown** [comment]
I'm also facing this problem on flutter 1.0.0 when using flavor dimensions scheme

here's the error log when running `flutter build apk --flavor <flavorName> --verbose`
```
[  +16 ms] "flutter apk" took 46,438ms.
Gradle build failed to produce an Android package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:403:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:300:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:44:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:401:18)
#6      _asyncThenWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by Moncader** [comment]
I found a workaround to build with these with any number of product flavors.
In the android section of your `app/build.gradle`, add the following.

```groovy
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "${project.archivesBaseName}-${variant.productFlavors.name.join()}-${variant.buildType.name}.apk"
        }
    }
```

Flutter is expecting the APK file name to be the same as the gradle task associated to build it, which is not what gradle does when making APK names.
Gradle uses `variant.baseName` which according to the gradle source code is a
> Full, unique name of the variant, including BuildType, flavors and test, dash separated.

This just forces the apk name to be what flutter expects.

**Comment by ddomingues** [comment]
Hi guys!

Thank you so much @Moncader. Your workaround works fine, but when I try to use just one flavor it still fails.

Ex. `--flavor abc`

My settings

```
flavorDimensions "flavor", "environment"

productFlavors {
        abc {
            dimension "flavor"
            applicationId 'com.abc'
        }

        def {
            dimension "flavor"
            applicationId "com.def"
        }

        production {
            dimension "environment"
        }   
 }
```

Any idea about how to fix it?

**Comment by iqbalmineraltown** [comment]
@ddomingues afaik when you use multiple dimensions, you have to specify flavor with combination of them, e.g. --flavor abcproduction

**Comment by PiotrWpl** [comment]
There is one more issue with multiple flavor dimensions. 
I used the fix from @Moncader and it was working fine for me on OSX, but turns out, that build was failing for one of my teammates, which was working on Linux. And the issue was, that Flutter is forcing us to use ONLY small letters on flavor names like "**abcproduction**", but in the end Gradle is automatically using uppercase for the second dimension in the output build path:
for example:
`my_project/build/app/outputs/apk/**abcProduction**/debug/apk-abcproduction-debug.apk`
and because Linux file system is case sensitive (and we were passed flavors as "abcproduction") he was expecting:
`my_project/build/app/outputs/apk/**abcproduction**/debug/apk-abcproduction-debug.apk`
And it fails in the end :/

so, for me the temporary workaround (which is workin on both OS) was:
```
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "../../${variant.productFlavors.name.join()}/${variant.buildType.name}/${project.archivesBaseName}-${variant.productFlavors.name.join()}-${variant.buildType.name}.apk"
        }
    }
```
thanks to above change, I'm creating an output directory using only small letters, and it's working fine on Linux and OSX.

But in my opinion this is something what should be definitely fixed in Flutter tools.

**Comment by blasten** [comment]
This is fixed on stable. However, the tool cannot find the APK.
```
$ flutter build apk --flavor BRAND1NorthAmerica --target-platform android-arm
Running Gradle task 'assembleBRAND1NorthAmericaRelease'...
Running Gradle task 'assembleBRAND1NorthAmericaRelease'... Done         3.3s
Gradle build failed to produce an .apk file. It's likely that this file was generated under .../app/build, but the tool couldn't find it.
```

The APK is generated under `/build/app/outputs/apk/BRAND1NorthAmerica/release/app-BRAND1-northAmerica-release.apk`.  We need to teach the tool how to find this file.
