### ISSUE TITLE
Obscured text field content is copy-able

### ISSUE THREAD

**Issue by blucell** [flutter/flutter#24100]
## Steps to Reproduce (tested on iOS only)

1. Create a TextField widget with obscureText set to true
2. Write some text in there and long-press it
3. Press copy and paste it anywhere else

## What Was Expected

Copy option not to even appear, and not to reveal any of the data

## What Happened

I could copy the obscured text

**Comment by justinmc** [comment]
You can work around this for now by using `enableInteractiveSelection`:

```
// Password field
TextField(
  obscureText: true,
  enableInteractiveSelection: false,
);
```

I think you're right that this is pretty nonintuitive for someone just looking to create a password field, though.  The PR above will change the defaults so that `enableInteractiveSelection` will default to `false` when `obscureText` is true.

**Comment by blucell** [comment]
I believe currently in Android and iOS, the interactive selection is not completely disabled, but repurposed by just not viewing the `Cut` and `Copy` buttons, or any other ones that may reveal its value one way or another. The ones that usually remain are `Paste`, `Select All`, and `Auto Fill`.

**Comment by justinmc** [comment]
@blucell Would you mind creating a new issue for these specific menu items?  Looking into it, it seems like there has already been some desire for improved long press menu controls.  This will give us some more reason to push for getting that right.

Meanwhile, I'll get the above PR over the finish line to at least fix the basic problem in this issue.  We're currently in code freeze for the Flutter Live event, but I should be able to merge that right afterwards (December 10th or so).

**Comment by justinmc** [comment]
Alright the quicker fix is shipped.  Thanks for opening the other issue.  Hoping to get some time to work on the long press menu.
