### ISSUE TITLE
Google  please help me !!!  I can not create flutter project @ AS/VSCode GUI & flutter run crash !!  

### ISSUE THREAD

**Issue by CMingTseng** [flutter/flutter#24103]
## Steps to Reproduce

Please  help me  

1. My OS  is  Windows 10 Pro 1703/1803 @ Lenovo P70

2.  My IDE is   Android Studio 3.2 & VSCode 

3.  I  install  flutter plugin over 30 times !!!!  

4.  I clean install  Windows  over 2 times 

_________________But ________  !!!!!_ _ ________________  
 The below is my step 

1.    i clean install Flutter plugin @AS 3.2  --follow this Doc https://flutter.io/docs/get-started/install/windows

![image](https://user-images.githubusercontent.com/7948140/48198620-63925700-e394-11e8-8474-97660ee86bb2.png)

![image](https://user-images.githubusercontent.com/7948140/48198602-54aba480-e394-11e8-972f-dc2137d2eb73.png)

2.   after installed Flutter plugin  --  the " Settings " --"Languages & Frameworks"  ---{Not Show  any Dart & Flutter } 
![image](https://user-images.githubusercontent.com/7948140/48198669-8cb2e780-e394-11e8-8f3f-b7abf5607a85.png)

![image](https://user-images.githubusercontent.com/7948140/48198705-a48a6b80-e394-11e8-9d0f-d35860ad7229.png)

![image](https://user-images.githubusercontent.com/7948140/48198727-b966ff00-e394-11e8-9aa2-b5985e7b6653.png)

![image](https://user-images.githubusercontent.com/7948140/48198765-d69bcd80-e394-11e8-830b-4572a91ab085.png)

3.  I try to create Flutter project  by Android Studio GUI ---> But get !!!
![image](https://user-images.githubusercontent.com/7948140/48198858-398d6480-e395-11e8-93c0-4288b61aef05.png)

Yes  !!!  I get   " Flutter create command was unsuccessful " &  a blank folder !!!!
![image](https://user-images.githubusercontent.com/7948140/48199020-c801e600-e395-11e8-9354-f85ec683ddd0.png)

4. But  But  But  I can create Flutter project  by command line !!!

![image](https://user-images.githubusercontent.com/7948140/48199302-a81ef200-e396-11e8-882a-809d752a68ca.png)

![image](https://user-images.githubusercontent.com/7948140/48199614-98ec7400-e397-11e8-8ba8-3ec03e2f1ef0.png)

5. When I open this flutter project by AS 3.2 !!!  { Dart & Flutter isVisible !!!! } --  the " Settings " --"Languages & Frameworks" 

![image](https://user-images.githubusercontent.com/7948140/48199661-c76a4f00-e397-11e8-82c5-78b2527e7f0f.png)

6. so  now  i want run flutter project   -- i use  "adb devices " & "flutter doctor "  
![image](https://user-images.githubusercontent.com/7948140/48199799-321b8a80-e398-11e8-8195-d985fe42afa1.png)

7. But But But  !!!!   I click  "run" !! it will show !!!!!!!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/7948140/48199866-6727dd00-e398-11e8-9c99-19215dc72587.png)

8. What's happen ????????

9. so  i change  IDE to  VScode !!!!!  (sorry   google  daddy )

10.  follow  this  https://flutter.io/docs/get-started/editor?ide=vscode#vscode

11.  I use  "Flutter :New Project "

![image](https://user-images.githubusercontent.com/7948140/48200107-1cf32b80-e399-11e8-8072-0796ec2fed2f.png)

![image](https://user-images.githubusercontent.com/7948140/48200185-5166e780-e399-11e8-97f7-96b7e875e284.png)

![image](https://user-images.githubusercontent.com/7948140/48200219-693e6b80-e399-11e8-8bfa-256f6841809b.png)

I  get !!!   {  Unable to open 'main.dart': File not found  }
![image](https://user-images.githubusercontent.com/7948140/48200252-82471c80-e399-11e8-8dd9-790d36600914.png)

![image](https://user-images.githubusercontent.com/7948140/48200587-8f184000-e39a-11e8-8f4b-99e2c0e8a848.png)

12.  I create new project by command again !!

![image](https://user-images.githubusercontent.com/7948140/48200766-2087b200-e39b-11e8-961b-61a45829d624.png)

13. i open the project by VScode   --- !!  no device !!!

![image](https://user-images.githubusercontent.com/7948140/48201008-cdfac580-e39b-11e8-83ee-5d185f837bac.png)

So ???

now   Google  &   Microsoft  do not let use flutter ????

THX

## Logs

```
```

```
```

**Comment by yaostyle** [comment]
I don't use AS to write Flutter so I can't comment on that. 
Did you install Flutter extension in your VSCode?
Usually, I would just create a Flutter project in command line then open the folder via VSCode (code .) and the VScode can launch any available emulator/devices for you.

**Comment by DanTup** [comment]
Would you mind enabling the [Dart Code extension log](https://dartcode.org/docs/logging/#extension) and repeating the `Flutter: New Project` command (and also the final screenshot where the device does not show in the status bar) and opening an issue in the Dart Code repo: https://github.com/Dart-Code/Dart-Code

I'm not sure about the other issues listed here, but those ones do seem like the VS Code plugin isn't doing something right, so I'd like to dig into them.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
