### ISSUE TITLE
LICENSE problem

### ISSUE THREAD

**Issue by michaellee8** [flutter/flutter#24104]
Why do all license text, including https://github.com/flutter/flutter/blob/master/LICENSE , says Chromium Authors instead of flutter or dart.

**Comment by zoechi** [comment]
How is that a problem?

**Comment by michaellee8** [comment]
Shouldn't it be writing Flutter Authors? This project has minimum relationship with Chrome/Chromium I guess.

**Comment by michaellee8** [comment]
Actually I found it quite interesting that most of the repo under flutter organization writes `Chromium Authors` in their LICENSE file, but only one https://github.com/flutter/engine/blob/master/LICENSE write `Flutter Authors`.

Could this be a result of copy and paste due to the early development of the framework?

**Comment by zoechi** [comment]
As far as I know this is just what they use for Google open source projects.

**Comment by michaellee8** [comment]
@zoechi I am not quite sure about that. Digging into [angular](https://github.com/angular/angular/blob/master/LICENSE) and [dart](https://github.com/dart-lang/sdk/blob/master/LICENSE) LICENSE I found that some google projects uses a different license (angular), while some uses the same format BUT they at least changed the author (dart).

I would suggest that `Chromium authors` field in the LICENSE refers to the copyright owners of these codes, which should be `Flutter authors`.

**Comment by michaellee8** [comment]
It will be bad if these kind of small errors somehow lead to a legal drama and destroy such a great project.

**Comment by michaellee8** [comment]
@eseidelGoogle Can you give some comments on this one?

**Comment by eseidelGoogle** [comment]
I'm not a lawyer. I have no legal opinion here.

Earlier versions of the Flutter engine started from a fork of Blink (part of Chromium), at which time we inherited the set of authors "The Chromium Authors" for that codebase.  These days the Flutter Engine and Chromium have little in common.  We could have a separate set of authors, I suspect, but that would be something I'd have to ask a lawyer.

@Hixie may have further comments here.  If you're concerned, I suspect we can update our FAQ somewhere with lawyer-approved explanations of our licensing setup. :)

**Comment by michaellee8** [comment]
Thank you for your explanation. I guess I understand this situation with those bits of historical context now.

**Comment by Hixie** [comment]
It does say Flutter authors for most of the code now. Some of our code is still actually maintained by Chromium though so it says Chromium authors. We also use code from many other sources.
