### ISSUE TITLE
A number of pages on the new infrastructure return 500s

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2410]
The following pages available from links from the new infrastructure's waterfall fail with 500s:
- [ ] Grid
- [ ] T-Grid
- [ ] Console (to which "Home" redirects)

**Comment by Hixie** [comment]
These don't seem particularly useful to me, by the way. I think we could easily decide to just hide the links and drop support for these features instead.

**Comment by eseidelGoogle** [comment]
Documentation on how to remove it from our buildbot templates is here:
https://github.com/flutter/flutter/tree/master/infra/README.md

**Comment by Hixie** [comment]
We're just avoiding those pages.
