### ISSUE TITLE
Missing Text outline / stroke / border feature

### ISSUE THREAD

**Issue by PieterAelse** [flutter/flutter#24108]
I was looking to outline/stroke/border some text in my app, but wasn't able to find any Widget or property of Text or TextStyle or TextDecoration for this. Example of white border:
![image](https://user-images.githubusercontent.com/6347879/48208742-c9221b80-e373-11e8-9452-46ba33de376c.png)

Did I overlook anything or could this be added to e.g. TextStyle or TextDecoration?

I'm currently working around this abusing the 'shadows' of TextStyle. EG:
```dart
Text("Border test",
  style: TextStyle(
    inherit: true,
    fontSize: 48.0,
    color: Colors.pink,
    shadows: [
      Shadow( // bottomLeft
	offset: Offset(-1.5, -1.5),
	color: Colors.white
      ),
      Shadow( // bottomRight
	offset: Offset(1.5, -1.5),
	color: Colors.white
      ),
      Shadow( // topRight
	offset: Offset(1.5, 1.5),
	color: Colors.white
      ),
      Shadow( // topLeft
	offset: Offset(-1.5, 1.5),
	color: Colors.white
      ),
  ],
  ),
);
```

**Comment by GaryQian** [comment]
You are correct in that there is currently no official API to add text borders. We can consider adding such an API, but this will likely not be adding in the very short term.

Your workaround is a fairly common way to get a similar effect ([similar issue in CSS](https://stackoverflow.com/questions/2570972/css-font-border))

**Comment by tewshi** [comment]
Check this https://tutorsvilla.blogspot.com/2019/06/how-to-add-text-border-or-text-stroke-flutter.html

https://github.com/tewshi/bordered-text

**Comment by maylortaylor** [comment]
This should be easier to do, right?

**Comment by rhalff** [comment]
I think @tewshi 's solution is pretty clean, perhaps include by default in flutter?

**Comment by GaryQian** [comment]
Adding Interesting new contributor project label, as I should be able to guide someone through the process of adding the changes in LibTxt and exposing the option in the framework.

It seems the bordered-text by @tewshi is sufficient for the short term.

A native Flutter fully implemented solution for this would preferably draw directly with skia through a simple TextStyle parameter, and support under/overstroke for the border, and possibly and inset border option as well. As your typography becomes more feature complete, I can start looking into adding this. No ETA still though.

**Comment by stephenfung98** [comment]
> Check this https://tutorsvilla.blogspot.com/2019/06/how-to-add-text-border-or-text-stroke-flutter.html
> 
> https://github.com/tewshi/bordered-text

Is it possible to use this inside a textfield?

**Comment by tewshi** [comment]
> Is it possible to use this inside a textfield?

Please explain what you mean

**Comment by shashank3107** [comment]
import 'package:bordered_text/bordered_text.dart';
does this import exists???

**Comment by stephenfung98** [comment]
> > Is it possible to use this inside a textfield?
> 
> Please explain what you mean

I want to have the text inside my textfield with the border

**Comment by stephenfung98** [comment]
> import 'package:bordered_text/bordered_text.dart';
> does this import exists???

That does not exist.

**Comment by tewshi** [comment]
> import 'package:bordered_text/bordered_text.dart';
> does this import exists???

it does if you install the [bordered_text](https://github.com/tewshi/bordered-text) package
https://github.com/tewshi/bordered-text

**Comment by tewshi** [comment]
> > > Is it possible to use this inside a textfield?
> > 
> > 
> > Please explain what you mean
> 
> I want to have the text inside my textfield with the border

A textfield accepts style property, if it accepts a widget, then this will work. But we can look into its implementation.

Also, since the Flutter team is working to add border to Text() widget, then it may be easier if they do so.

**Comment by GaryQian** [comment]
This is the engine half of the stroke feature: https://github.com/flutter/engine/pull/9861 (as of now it is still WIP)

**Comment by dnfield** [comment]
Can't you do this already by using the `foreground` property and applying a paint with its style set to stroke?

**Comment by dnfield** [comment]
See, for example, the sample in the PR that added `foreground`: https://github.com/flutter/engine/pull/5395

**Comment by GaryQian** [comment]
Update, this should already be possible with a foreground paint: https://github.com/flutter/engine/pull/5395

**Comment by GaryQian** [comment]
I have added a documentation example on how to add bordered text. To achieve fill over stroke, we recommend using a stack and stacking two Text widgets, one with stroke, and the other with fill. I will close this for now.

**Comment by PieterAelse** [comment]
Awesome guys, thanks! 😁

**Comment by maylortaylor** [comment]
> I have added a documentation example on how to add bordered text. To achieve fill over stroke, we recommend using a stack and stacking two Text widgets, one with stroke, and the other with fill. I will close this for now. Let me know if anyone has any additional questions!
> 
> We have purposefully (for now) not exposed SkPaint's kStrokeAndFill paint style due to discussions of the future of that particular style.

Got a link to that documentation?

**Comment by GaryQian** [comment]
https://master-api.flutter.dev/flutter/painting/TextStyle-class.html

I have also adding docs on how to achieve gradient text.

**Comment by ljmatan** [comment]
@GaryQian what if I want my TextField widget to have bordered text?
