### ISSUE TITLE
Crash in RenderViewportBase.visitChildrenForSemantics

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter#24109]
Our app is getting a NoSuchMethodError at package:flutter/src/rendering/viewport.dart:182
This is happening dozens of times a day (we have 90k daily actives)

The stack trace is not informative (the semantics engine is iterating through the render tree), but I can provide it if necessary.

**Comment by jonahwilliams** [comment]
Without a repro finding the underlying issue here is highly unlikely. The particular codepath is highly tested, which means this may only happen under very specific circumstances in very specific builds.
