### ISSUE TITLE
Android back button doesn't work correctly in CupertinoTabBar apps

### ISSUE THREAD

**Issue by REKURDennis** [flutter/flutter#24105]
The Android back button does not work correctly, if a widget is pushed from within a CupertinoTabBar.

1. Start the app on an Android Device
2. Tap the button "Tap me"
3. Try to go back with the Android back button.

Expected: The app shows the previous widget with the "Tap me" button again
Actual: The app is closed

```import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MaterialApp(home: CupertinoNavigationDemo()));

class CupertinoNavigationDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.home),
            title: Text('Home'),
          ),
          BottomNavigationBarItem(
            icon: Icon(CupertinoIcons.home),
            title: Text('Home'),
          )
        ],
      ),
      tabBuilder: (BuildContext context, int index) {
        return CupertinoTabView(
          builder: (BuildContext context) {
            return CupertinoDemoTab();
          },
        );
      },
    );
  }
}

class CupertinoDemoTab extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: FlatButton(
        onPressed: () {
          Navigator.of(context).push(CupertinoPageRoute<void>(
            builder: (BuildContext context) => DetailPage(),
          ));
        },
        child: Text("Tap me"),
      ),
    );
  }
}

class DetailPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
        navigationBar: const CupertinoNavigationBar(),
        child: Container(
          color: Colors.green,
        ));
  }
}
```

**Comment by flogh** [comment]
Looking for it too

**Comment by xster** [comment]
Deduping into #14083

**Comment by ViktorKirjanov** [comment]
> #14083

 #14083 is different, without CupertinoTabBar

**Comment by robin7331** [comment]
There is a solution for that.
Like said many times before the problem is that you have multiple navigators coming with your `CupertinoTabBar`. 

So what you want is a **gobal navigator key** for each tab. Chances are you probably need that anyway at some point in your app. So in my App I've created as much global keys as I have tabs in my tabbar. 

```
  final GlobalKey<NavigatorState> firstTabNavKey = GlobalKey<NavigatorState>();
  final GlobalKey<NavigatorState> secondTabNavKey = GlobalKey<NavigatorState>();
  ...
```

then set the according navigator key to the `CupertinoTabView()`:

```
CupertinoTabView(
   navigatorKey: firstTabNavKey,
   builder: (BuildContext context) {
      return MyWidget();
 );
```

So far so good. Now lets handle the android back button correctly. 
Wrap your `CupertinoTabScaffold` in a `WillPopScope()` widget just like that:

```
WillPopScope(
  onWillPop: () async {
    return !await currentNavigatorKey().currentState.maybePop();
  },                
  child: CupertinoTabScaffold(
    ...
  )
)
```

a little helper method ensures that it'll always call `maybePop()` on the current visible navigator by switching over the current tab index.

```
GlobalKey<NavigatorState> currentNavigatorKey() {
    switch (_tabController.index) {
      case 0:
        return firstTabNavKey;
        break;
      case 1:
        return secondTabNavKey;
        break;
      case 2:
        return thirdTabNavKey;
        break;
      case 3:
        return fourthTabNavKey;
        break;
      case 4:
        return fifthTabNavKey;
        break;
    }

    return null;
  }
```

Thats it. Works like charm 😊

**Comment by j-holub** [comment]
Thank you @robin7331 , this fixed the problem for me. It's noteworthy, that `_tabController` is a member variable of the tyoe `CupertinoTabController`, which has to be passed to the `CupertinoTabScaffold` for the `controller` property.

However, this introduced another problem for me, whenever I change code triggering a hot reload, my App completely crashes with the following error screen. Needless to say, this hinders development immensely, because we have to completely reload the app everytime we make a simple change. Did anybody experience the same issue?

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-03 at 12 14 17](https://user-images.githubusercontent.com/19982919/83625142-c6110080-a593-11ea-8caf-6ae5829f9343.png)

**Comment by hannukuk** [comment]
I ran into the same issue. Fixed by changing from StatelessWidget to StatefulWidget.

> 
> 
> Thank you @robin7331 , this fixed the problem for me. It's noteworthy, that `_tabController` is a member variable of the tyoe `CupertinoTabController`, which has to be passed to the `CupertinoTabScaffold` for the `controller` property.
> 
> However, this introduced another problem for me, whenever I change code triggering a hot reload, my App completely crashes with the following error screen. Needless to say, this hinders development immensely, because we have to completely reload the app everytime we make a simple change. Did anybody experience the same issue?

**Comment by j-holub** [comment]
You are the absolute MVP @hannukuk , thank you very much! A super simple fix that also explains why it worked for a lot of people, they were probably using a stateful widget in the first place.

**Comment by ASemeniuk** [comment]
@robin7331 
I suggest using `List<GlobalKey<NavigatorState>>` instead of creating individual keys.

    final tabNavKeys = List<GlobalKey<NavigatorState>>[
      GlobalKey<NavigatorState>();
      GlobalKey<NavigatorState>();
      ....
    ];

Then in your `CupertinoTabView`:

    CupertinoTabView(
       navigatorKey: tabNavKeys[0],
       builder: (BuildContext context) {
          return MyWidget();
     );

And finally, in `WillPopScope`:

    WillPopScope(
      onWillPop: () async {
        return !await tabNavKeys[_tabController.index].currentState.maybePop();
      },                
      child: CupertinoTabScaffold(
        ...
      )
    )

You absolutely don't need this monstrous `currentNavigatorKey()` method.

**Comment by tiklup11** [comment]
thanks @robin7331 , @hannukuk  , @j-holub , @REKURDennis ...after a lot of searching I find this page, It surely works like a charm. Thanks a ton again .

**Comment by jr00n** [comment]
Even after implementing this, my Android phone and simulator is crashing, or leaves the flutter app, will using the backbutton. Is there more i must do?

**Comment by J-Ridgwell** [comment]
@ASemeniuk 
> final tabNavKeys = List<GlobalKey<NavigatorState>>[
>   GlobalKey<NavigatorState>();
>   GlobalKey<NavigatorState>();
>   ....
> ];
> 
> 
> You absolutely don't need this monstrous `currentNavigatorKey()` method.

Adding to the succinctness of this, you can go a bit further and use `List.generate()` instead. For ex:
```
final List<GlobalKey<NavigatorState>> tabNavKeys = List.generate(num, (_) => GlobalKey<NavigatorState>());
```

**Comment by Rushil10** [comment]
> Even after implementing this, my Android phone and simulator is crashing, or leaves the flutter app, will using the backbutton. Is there more i must do?
> 
> Away from the CupertinoTabScaffold the back button works fine:
> 
> On the CupertinoPageScaffold which is open, i navigate to a new screen via
> 
> ```
> onTap: () { 
> Navigator.of(context, rootNavigator: true).push(
>        CupertinoPageRoute(
>               builder: (BuildContext context) => NewPage()),
> }
> ```
> 
> and on the NewPage()
> i have a button with:
> 
> ```
>  Navigator.of(context).pop();
> ```
> 
> And on that screen (NewPage()) the back button is working fine.

I am facing the same issue,did you find any solution ?
