### ISSUE TITLE
The URLs used on the JSON page of the new test infrastructure are bad

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2411]
This page: https://build.chromium.org/p/client.flutter/json/help
...has links to various pages, but they are wrong.

For example, the link labeled `/json` links to https://build.chromium.org/p/json?as_text=1 but should actually link to https://build.chromium.org/p/client.flutter/json?as_text=1 as far as I can tell.

**Comment by eseidelGoogle** [comment]
The code is here:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/masters/master.client.flutter/
Under `templates` with the main driving file being builders.pyl:
https://chromium.googlesource.com/chromium/tools/build.git/+/master/masters/master.client.flutter/builders.pyl
https://github.com/flutter/flutter/tree/master/infra/README.md has some documentation links.

**Comment by eseidelGoogle** [comment]
We don't really use these pages anymore, unclear if we need to track this.  @yjbanov wrote us an alternative front-end onto these bots.

**Comment by yjbanov** [comment]
Almost: https://github.com/flutter/cocoon/issues/84

**Comment by Hixie** [comment]
Not going to worry about these kinds of issues.
