### ISSUE TITLE
Add flutter-engine-build check to flutter/engine presubmit checks

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#24125]
We need a presubmit check (flutter-engine-build) in flutter/engine that's similar to the flutter-build check in flutter/flutter. It will prevent us (and the auto-roller) to merge commits when the tree is red.

After adding the check, we need to modify the skia-to-engine auto-roller (probably by the Skia team) config so it will wait for flutter-engine-build when it's not green.

**Comment by liyuqian** [comment]
CC @amirh @goderbauer @Hixie 

@yjbanov : is it easy to modify cocoon's code so it can have a flutter-engine-build check that's similar to flutter-build check?

**Comment by yjbanov** [comment]
I'm not sure how this can be implemented by modifying anything existing. I can see how this could be a new cron job in Cocoon that checks the Engine Chromebot status and pushes it to Github.

**Comment by liyuqian** [comment]
Will the new cron job be very similar to the old job (so we can either reuse or copy/paste a lot of things)?

**Comment by liyuqian** [comment]
Fixed by https://github.com/flutter/cocoon/pull/251
