### ISSUE TITLE
Locale resolution called before platform passes locale data.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#24121]
Apps tend to call locale resolution twice at startup: once before locales have been passed to Flutter by FlutterView.java or FlutterViewController.mm which causes the first attempt to fail, and a second time after it is passed, which succeeds.

Locale resolution should only need to be called once on initial startup, and the first call may cause issues with the locale being null.

I suspect resolution is being called too early, and the initial failure results in it needing to be called again. Otherwise, it is also possible there exists a race condition somewhere that results in locales not passed when they should have been already.

**Comment by GaryQian** [comment]
Putting this on hold as I can no longer repro. I suspect the issue still exists, so if anyone has any cases where this is still happening, please reopen/provide information and I will be glad to take another look at it.

**Comment by nhwilly** [comment]
I'm seeing it happen twice when the language is changed via the device language setting.  I figure it might be happening once when the setting is changed and again when the app comes from the background.  HTH, but it's not a show stopper, so I'm letting it ride.
