### ISSUE TITLE
Offline mode for cloud firestore inserts duplicate documents

### ISSUE THREAD

**Issue by MsXam** [flutter/flutter#24123]
We have an issue with Flutter connected to Cloud Firestore in offline mode.

Specifically, if you have a ListView builder that displays data from a **Firestore Collection**:

```dart

      StreamBuilder<QuerySnapshot>(
        stream: Firestore.instance.collection('flutter_data').snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData ||
              snapshot.connectionState == ConnectionState.waiting) {
            return CircularProgressIndicator();
          }
          
          return FirestoreListView(documents: snapshot.data.documents);
        },
      )
```

and you have a button that adds data to Firestore :

```dart

  void addTitle(String text) {
 
    Map<String, String> data = {'title': text};
    Firestore.instance.runTransaction((Transaction tx) async {
      var snapshot = await tx.get(Firestore.instance.document('flutter_data'));
      await tx.set(snapshot.reference, data);
    });
  }
```

Then assuming we have no network connection and add say the title -> test12345 , our listview builder will show the string **test12345** approx 5 times - we then turn on the connection, our app will then throw a PlatformException with the error :

```
**errorCode = 9**
**message = Transaction failed all retries**
```

And stack trace

```
> "LocalDownloadTask <3109D0D9-C5AA-456D-8A15-B6DFB23DA3B8>.<1>"
> ), NSLocalizedDescription=A server with the specified hostname could not be found., NSErrorFailingURLStringKey=https://app-measurement.com/config/app/1:841219028691:ios:4435fb28c55b69f4?platform=ios&app_instance_id=D2667171446D4FB3BBEDA454B4D5B89E&gmp_version=50200, NSErrorFailingURLKey=https://app-measurement.com/config/app/1:841219028691:ios:4435fb28c55b69f4?platform=ios&app_instance_id=D2667171446D4FB3BBEDA454B4D5B89E&gmp_version=50200, _kCFStream [<decode: missing data>]
> 5.9.0 - [Firebase/Analytics][I-ACS901017] Encounter network error. Code, error: -1003, Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x600001fdc180 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDownloadTask <3109D0D9-C5AA-456D-8A15-B6DFB23DA3B8>.<1>, _NSURLErrorRelatedURLSessionTaskError
```

More importantly, we now have '5' documents in Firestore - it appears that when in offline mode, for each retry that the local client sdk does, it stores the document that many times in Firestore and thus causes duplicates - we were only expecting **ONE** document to be added in Firestore.

**We therefore have two issues**

1. Our stream gets a new event from the client cache for each time it trys to add to cloud firestore
2. Cloud firestore incorrectly batches all the retries for the same document and duplicates the data on cloud firestore 

**For issue 1**
We are yet to find a workaround

**For issue 2** 
Ideally we would like to be able to interrogate something like a **_querysnapshot meta data_** and determine if the event that we receive from the stream is from the local cache , if so - we would check to see if we have already shown the new item in our listview and if so, just ignore the event., However - we cannot find anything that will give us access to this information.

![firestore](https://user-images.githubusercontent.com/18722796/48225805-cd5f3080-e395-11e8-9f20-3de2dda1da94.gif)

![image](https://user-images.githubusercontent.com/18722796/48225762-adc80800-e395-11e8-9198-fc3e14df58c2.png)

**Comment by MsXam** [comment]
A follow up to this that I forgot to mention in the initial issue - the issue we are seeing only happens when we try and use **Transactions**, if we change the **addTitle**  to :

      void addTitle(String text) async {
        Firestore.instance.collection('flutter_data').document().setData({'title':text});
    }

Then we do not appear to experience the points raised earlier.

**Comment by MsXam** [comment]
flutter doctor -v details
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 0.9.4 at /Users/flutterdev/workspace/sdk/flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/flutterdev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • AAD3EB22-DA16-42E7-A307-DFAC4AD032D8 • ios         • iOS 12.1 (simulator)

• No issues found!

```

**Comment by cyanglaz** [comment]
cc @collinjackson

**Comment by newtonmunene99** [comment]
Hi, sorry to bother. But is there any way to know when the data is saved to the cache i.e when the device is offline and I add some data I should get some response or error that the data has been cached and will be updated when the device goes online. Is this currently possible?

**Comment by verscph** [comment]
Hi, had the same issue and bumped into this post on [Stackoverflow](https://stackoverflow.com/questions/53746008/why-is-my-flutter-app-saves-twice-on-firestore-while-my-device-is-offline)

I removed the runTransaction and await in my app, and now it handles offline changes perfectly.

Hope this helps!

**Comment by kroikie** [comment]
@MsXam

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/580. Any further collaboration will be done there.
