### ISSUE TITLE
Add buildbot support to our PRs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2412]

**Comment by eseidelGoogle** [comment]
I don't forsee us doing this anytime soon.  Will require us writing our own WebHook for github which knows how to integrate with Chrome Infra.

The actual webhook for github is probably just a tiny appengine app:
https://developer.github.com/webhooks/

But getting that to talk correctly with Chrome Infra is harder.  We could file a bug at http://crbug.com/new under `Infra`.  Or ask @riannucci, but I suspect we'll end up writing the Chrome Infra integration ourselves.

**Comment by riannucci** [comment]
Right now we don't have the bandwidth to do this, but we would like to do this at some point. I've filed https://crbug.com/592138 as the megabug, in case you have specific requirements that you want to link off it (or in case you decide to do work to support it yourselves, you can reference that bug).

**Comment by eseidelGoogle** [comment]
We've been getting along with travis alright for now.

**Comment by Hixie** [comment]
Closing per last comment.
