### ISSUE TITLE
Platform views on iOS can be synchronized starting iOS 8.0

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#24132]
CAEAGLLayer only supports synchronizing the GL contents with CA contents starting iOS 9.0.
With metal this is supported starting iOS 8.0.

Once we migrate to Metal we should synchronize starting iOS 8.0.

**Comment by pedromassangocode** [comment]
Is this still a valid issue? I'm to sure how to check if this still valid today.

**Comment by jmagman** [comment]
@chinmaygarde @zanderso any idea if this is still outstanding?

**Comment by zanderso** [comment]
Skia only supports the Metal backend on iOS 11.0 and later: https://github.com/flutter/flutter/issues/18208, but as for whether this is done where we use Metal, @cyanglaz might be the best person to answer.

**Comment by chinmaygarde** [comment]
Metal is supported on iOS 10.0 and above. I don't think addressing this issue is going to be a priority given the discussions around raising the minimum supported iOS version.

**Comment by cyanglaz** [comment]
The current minimum support of the iOS version is 11. I'm closing this issue as it is obsolete.
