### ISSUE TITLE
didPopRoute didn't called

### ISSUE THREAD

**Issue by krmao** [flutter/flutter#24138]
## Steps to Reproduce
I want intercept android backPressed event, and find `didPopRoute` didn't work

1. dart code
```dart
  @override
  void initState() {
    super.initState();
    tag = this.toStringShort();
    print("[$tag] initSatte");
    WidgetsBinding.instance.addObserver(this);
    }

  @override
  Future<bool> didPopRoute() {
    debugPrint("$tag didPopRoute");
    return Future.value(true);
  }

  @override
  void dispose() {
    print("[$tag] dispose");
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
```
2. android code
```java
    override fun onBackPress(): Boolean {
        CXLogUtil.e(TAG, "onBackPress flutter/navigation ${this}:${Thread.currentThread().name}, PAGES_COUNT=$PAGES_COUNT")
        // if (!this.eventDelegate.onBackPressed()) super.onBackPressed()
        MethodChannel(mFlutterView, "flutter/navigation", JSONMethodCodec.INSTANCE).invokeMethod("popRoute", null)
        return true
    }
```
3. the bug is (binding.dart)
```dart
  @protected
  Future<void> handlePopRoute() async {
    for (WidgetsBindingObserver observer in List<WidgetsBindingObserver>.from(_observers)) {
      if (await observer.didPopRoute())
        return;
    }
    SystemNavigator.pop();
  }
```
the value '_observers' here should be **_observers.reverse**, it should be a stack not a list,  I may only want the top page of the screen call the popDidRoute, other pages below will not .

```
[✓] Flutter (Channel master, v0.10.3-pre.142, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
    • Flutter version 0.10.3-pre.142 at /Users/xxx/workspace/flutter
    • Framework revision 9d53d7f848 (25 hours ago), 2018-11-07 17:20:18 -0800
    • Engine revision 70a1106b50
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/maokangren/sdks/android/sdk
    • Android NDK at /Users/maokangren/sdks/android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/maokangren/sdks/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Pixel 2 XL • 801KPKN1364549 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

for optimized, it may don't need the code on android backPressed, it should be default
```java
// if (!this.eventDelegate.onBackPressed()) super.onBackPressed()
        MethodChannel(mFlutterView, "flutter/navigation", JSONMethodCodec.INSTANCE).invokeMethod("popRoute", null) // control the pop
```
if `this.eventDelegate.onBackPressed()` may call `didPopRoute`, I think it is a good idea.

and if have a callback after `Navigator.push` animation end is a good idea, I need animation end to finish activity

**Comment by zoechi** [comment]
Can you please post a runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce (incl `main() {...}` and imports, ...).

**Comment by parthgodhani** [comment]
### 
### mixin file`import 'package:flutter/material.dart';
import 'package:kharidbazaar/services/NetworkService.dart';

mixin backButtonHandler<T extends StatefulWidget> on State<T>, WidgetsBindingObserver {
  
  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    print("initState");
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    print("dispose");
    return super.dispose();
  }

  @override
  Future<bool> didPopRoute() {
    print("didPopRoute");
    return Future<bool>.value(false);
  }
}
`

statefull widget class
`import 'package:flutter/material.dart';
import 'package:kharidbazaar/mixins/backButtonHandler.dart';
import 'package:kharidbazaar/pages/seller/store/agentOrderList.dart';
import 'package:kharidbazaar/pages/seller/store/customerOrderList.dart';
import 'package:kharidbazaar/pages/seller/store/favorites.dart';
import 'package:kharidbazaar/pages/seller/store/shoppingCart.dart';
import 'package:kharidbazaar/pages/seller/store/store.dart';
import 'package:kharidbazaar/pages/seller/storeDetail.dart';
import 'package:kharidbazaar/pages/seller/userStoreDetails.dart';
import 'package:kharidbazaar/services/sqlLiteService.dart';
import 'package:kharidbazaar/theme/colors.dart';
import 'package:kharidbazaar/theme/typography/typography.dart';

class sellerHome extends StatefulWidget {
  
  @override
  _sellerHomeState createState() => _sellerHomeState();
}

class _sellerHomeState extends State<sellerHome> with TickerProviderStateMixin,WidgetsBindingObserver,backButtonHandler {
  TabController tabController;
  cartService  cs = new cartService();
  
  @override
  void initState() {
    super.initState();
    this.tabController = TabController(length: 4, vsync: this);
    this.fnLoadData();
  }
  
  fnLoadData() async {
    await cs.fnInitDataBase(storeDetail.storeId);
    int cartCount = await cs.fnGetCartCount();
    setState(() {
      cartService.cartItemCount = cartCount;
    });
    
  }
  
  
  @override
  Future<bool> didPopRoute() {
    
    print("didPopRoute");
    return Future<bool>.value(false);
  }
  
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4,
      child: Scaffold(
        appBar: AppBar(
          title: Text(storeDetail.storeName),
          actions: <Widget>[
            Stack(
              children: <Widget>[
                IconButton(
                  icon: Icon(Icons.search),
                  onPressed: () {},
                ),
              ],
            ),
            Stack(
              children: <Widget>[
                IconButton(
                  icon: Icon(Icons.notifications),
                  onPressed: () {},
                ),
                Positioned(
                  right: 11,
                  top: 11,
                  child: new Container(
                    padding: EdgeInsets.all(2),
                    decoration: new BoxDecoration(
                      color: Colors.red,
                      borderRadius: BorderRadius.circular(6),
                    ),
                    constraints: BoxConstraints(
                      minWidth: 14,
                      minHeight: 14,
                    ),
                    child: Text(
                      '10',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 8,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                )
              ],
            ),
            Stack(
              children: <Widget>[
                IconButton(
                  icon: Icon(Icons.shopping_cart),
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => shoppingCart(),
                      ),
                    );
                  },
                ),
                cartService.cartItemCount > 0 ? Positioned(
                  right: 11,
                  top: 11,
                  child: new Container(
                    padding: EdgeInsets.all(2),
                    decoration: new BoxDecoration(
                      color: Colors.red,
                      borderRadius: BorderRadius.circular(6),
                    ),
                    constraints: BoxConstraints(
                      minWidth: 14,
                      minHeight: 14,
                    ),
                    child: Text(
                      '${cartService.cartItemCount}',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 8,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                ):Container()
              ],
            ),
          ],
          automaticallyImplyLeading: false,elevation: 0.0,
        ),
        body: TabBarView(
          children: [
            store(),
            userStoreDetails.isAgent ? agentOrderList(): customerOrderList(),
            favorites(),
            Icon(Icons.call),
          ],
        ),
        bottomNavigationBar: Container(
          child: TabBar(
            tabs: [
              Tab(
                icon: Icon(Icons.home),
                text: "HOME",
              ),
              Tab(
                icon: Icon(Icons.archive),
                text: "Orders",
              ),
              Tab(
                icon: Icon(Icons.favorite),
                text: "Wishlist",
              ),
              Tab(
                icon: Icon(Icons.person),
                text: "Seller Profile",
              ),
            ],
            indicatorColor: colors.PRIMARY,
            labelColor: colors.BLACK_500,
          ),
          decoration: BoxDecoration(boxShadow: [
            BoxShadow(color: colors.BLACK_300, offset: Offset(0.0, 0.0), blurRadius: 6.0),
          ], color: colors.WHITE),
        ),primary: true,
      ),
    );
  }
}
`

in this code 
initState 
dispose
is triggered bt does not triggered a didPopRoute

**Comment by michcio53** [comment]
Any news?
