### ISSUE TITLE
flutter_tool should check for incompatible packages in pubspec

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#24136]
Since we no longer depend on test, we can't rely on version solving anymore. Instead we should perform a one time check during flutter upgrade to warn users.

**Comment by zoechi** [comment]
What are the criteria that make packages incompatible?

**Comment by jonahwilliams** [comment]
Essentially just any test version < 1.5.1 or any mockito version < 4.0.0. Normally we would have a pinned dependency which would cause a version solving concept. But we factored out most of the common dependencies into the [test_api](https://pub.dartlang.org/packages/test_api) package. This drastically reduced the dependencies of flutter_test.

Naturally, the old versions of test and mockito don't know about test api, and since we no longer depend on them pub is happy to give us an old version of test and a new test_api, which causes a conflict when the test itself is run.
