### ISSUE TITLE
Unable to build for iOS - flutter Hangs

### ISSUE THREAD

**Issue by pepie** [flutter/flutter#24139]
I am unable to build for ios, flutter always hang on the following step:
```flutter build ios --release```
will produce:
```LionO:kio_mobile monfort$ flutter build ios
Building ... for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: Y86N6AMP4Z
Running pod install...                                       1.7s
Starting Xcode build...                                          
 ├─Building Dart code...                             34.8s

```
The build process never pass this step.

Building for android seems to work fine.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zhoulujue** [comment]
Same with my situation. Always freezes at `Building Dart code...` after `flutter run --release`.
So I had to switch to `beta` branch and then everything seemed fine.
```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 0.10.2 at /Users/lujuezhou/Developer/flutter
    • Framework revision d8cbb80206 (2 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/lujuezhou/Library/Android/sdk
    • Android NDK at /Users/lujuezhou/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4999

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Michael’s iPhone⚒ • 48045b14eaa759e28dd6c1ffe6444ce94dcef4ed • ios • iOS 12.1

• No issues found!
```

**Comment by zoechi** [comment]
Did you try `flutter clean`?

**Comment by zhoulujue** [comment]
> Did you try `flutter clean`?

Tried for few times but it doesn't seem to work fo me.

```
$ flutter clean
Deleting 'build/'.
$ flutter run --release
Launching lib/main.dart on Michael’s iPhone⚒ in release mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXXX
Running pod install...                                       2.1s
Starting Xcode build...
 ├─Building Dart code...                             29.4s

```

**Comment by MaxZeng** [comment]
same issue after flutter upgrade... It is hung when executing the xcode_backend.sh script

**Comment by syntaxerro** [comment]
Same issue..

**Comment by shinyford** [comment]
Same here.

**Comment by amao** [comment]
Same issue

**Comment by neithern** [comment]
Same issue, but work fine with dev channel on mojave 10.14.1

**Comment by shinyford** [comment]
Yeah - can confirm it works fine on the dev channel.

**Comment by pepie** [comment]
@zoechi 
FYI: using Android Studio 3.2.1
XCode: Version 10.1 (10B61

```flutter doctor -v
[✓] Flutter (Channel master, v0.11.2-pre.10, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.11.2-pre.10 at /Users/.../sdks/flutter
    • Framework revision 563ceac8d4 (61 minutes ago), 2018-11-09 16:14:44 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/.../Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by neithern** [comment]
It seems the new "dev channel 0.11.1" doesn't work now, hangs after "Building Dart code...", but the previous dev version worked fine.

[✓] Flutter (Channel dev, v0.11.1, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 0.11.1 at /Users/Shared/Flutter
    • Framework revision 756d5938d4 (7 hours ago), 2018-11-09 13:35:15 -0500
    • Engine revision 59f79d0d64
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Shared/Android/sdk
    • Android NDK at /Users/Shared/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

**Comment by xster** [comment]
Can you guys `flutter build [...] -v` so we can see where it hung?

**Comment by MaxZeng** [comment]
hung in xcode_backend.h script，right after the “Building Dart code...” log，there is no further log output。。。

**Comment by santervo** [comment]
Confirming that build succeeds when piping output. "flutter build ios --release -v > build.log"

**Comment by ozc** [comment]
Same issue while updating a previously built project. It's not related to OS version. Still running High Sierra and XCode 10.0.

@santervo 's solution of piping output works.

**Comment by bjon** [comment]
I have the same issue with dev channel

**Comment by RonenR** [comment]
Same with Channel dev, v0.11.4, on Mac OS X 10.14.1
Works well with: 
`flutter build ios --release -v > build.log`
as posted by @santervo & @MaxZeng

**Comment by CaiJingLong** [comment]
If the console information is output to the log file, there will be no error. Instead, it will be stuck in the `build dart` step.

**Comment by An-uking** [comment]
same issues

**Comment by cseder** [comment]
Sounds like the easiest workaround for now is to switch to the dev channel. I use Mojave (10.14.1), Xcode 10.1 and Flutter dev channel without problems.

**Comment by heyabredda** [comment]
I am already on dev channel but I am still facing this issue.
Also when I run flutter build ios --release -v > build.log it does not do anything apart from going to next line.

**Comment by aam** [comment]
Should be fixed in master where  #24310 landed short time ago.

**Comment by pepie** [comment]
@aam fantastic!

**Comment by shinyford** [comment]
I am also now seeing this in the dev channel, FWIW
