### ISSUE TITLE
Many (all?) "stdio" links on the buildbot waterfall are 404

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2414]

**Comment by eseidelGoogle** [comment]
It's possible @riannucci has recommended workarounds, but I suspect this is just an expected quirk of how recipes works in Chrome Infra.

https://build.chromium.org/p/client.flutter/waterfall
e.g.
https://build.chromium.org/p/client.flutter/builders/Linux/builds/325/steps/flutter%20apk%20examples%2Fstocks/logs/stdio
https://build.chromium.org/p/client.flutter/builders/Linux/builds/325/steps/test%20examples%2Fstocks/logs/stdio

Some of them work:
https://build.chromium.org/p/client.flutter/builders/Linux/builds/325/steps/flutter%20analyze/logs/stdio

**Comment by riannucci** [comment]
urk, I think it's the slash in the step name being mangled by buildbot :(

**Comment by eseidelGoogle** [comment]
Oh?  @riannucci do you need a bug from us?  Should we just change our step names (or otherwise url encode them when passing them to html_name)?

**Comment by riannucci** [comment]
This is a very old known bug that's deep inside of buildbot: crbug.com/57553 . The new UI presentation stuff we're working on to replace buildbot does not have this bug. I would url encode them or otherwise change the names to be urlsafe.

**Comment by devoncarew** [comment]
Some links fixed here: https://codereview.chromium.org/1864223002/

**Comment by devoncarew** [comment]
Last ones fixed here: https://codereview.chromium.org/1922943002/.
