### ISSUE TITLE
the flutter command doesn't respond to anything

### ISSUE THREAD

**Issue by juliarnasution** [flutter/flutter#24148]
I just updated my flutter, from version 0.9.4 to 0.10.2,
and I get a problem, that is when I do commands via CMD, for example the "flutter doctor" command. I have waited for quite a long time but still did not give any response, whether it was a successful message or an error message
![image](https://user-images.githubusercontent.com/15206309/48247858-7bff8180-e427-11e8-955a-2b8cd130433a.png)

**Comment by zoechi** [comment]
Do you have an internet connection when you run the command? 
Are you behind a proxy?

**Comment by DanTup** [comment]
If anyone sees this again, it'd be worth taking a copy of the Flutter SDK before overwriting it - we may be able to figure out what went wrong by examining it.

**Comment by thecodingpapa** [comment]
It is happening to me right now

**Comment by DanTup** [comment]
@thecodingpapa Could you make a copy of your Flutter SDK folder, then re-download it and see if that fixes it? If so, we should then examine the differences between them.

**Comment by DanTup** [comment]
I missed this:

> I was running "flutter update-packages --force-upgrade".

What's the reason you were running this? This command is used for updating Flutter's internal dependencies and shouldn't generally be run by users of Flutter (there's no guarantee that Flutter will work with newer versions of packages than it shipped with).

> And It took so long and I just close the studio and restarted.

My  guess is that this terminated something in-progress and things in an inconsistent state.

I would delete the SDK and re-download it, and avoid running `flutter update-packages --force-upgrade` (and I think it's expected that it takes a while).

**Comment by ch-muhammad-adil** [comment]
I am facing this issue whenever i switch from stable channel to master first of all it deletes my dart SDK and automatically start downloading it. Then flutter channel commands never respond, even no flutter command responds. it happened with me twice and always i have to re-download dart SDK. 
Here you can see. 
<img width="1280" alt="Screenshot 2019-10-18 at 11 10 38 PM" src="https://user-images.githubusercontent.com/8264639/67117597-88c25300-f1fc-11e9-86f9-839de58c835f.png">

**Comment by ch-muhammad-adil** [comment]
Some by running kill commands restart android studio it has started working again, but yes right after switching back to Stable branch it has re-installed dart SDK.

**Comment by DanTup** [comment]
@ch-muhammad-adil It's expected behaviour for the SDK to be downloaded. Each version of Flutter may depend on a different version of the Dart SDK, so when you change channel, Flutter notices the local SDK does not match and fetches the correct one.

It's possible the other issues are related to Android Studio having Flutter processes running while you're switching channels, which might lock files. I would recommend closing any IDE/editor before changing channel to reduce the chance of it causing issues.

**Comment by redcodemohammed** [comment]
> It is happening to me right now
> I was running "flutter update-packages --force-upgrade".
> And It took so long and I just close the studio and restarted.
> And flutter command never triggers anything since then.
> 
> This is my [Flutter SDK](https://drive.google.com/file/d/1UnqPG9jvWvjnyLN0NfCKYCwQtNk_lqED/view?usp=sharing)

That exactly what happed to me, and I got the same problem

**Comment by DanTup** [comment]
> It is happening to me right now
> I was running "flutter update-packages --force-upgrade".

Out of interest - why are you using `--force-upgrade`? That's intended to be used by contributors to Flutter to upgrade packages (which then go through all of the automated tests). If you're just using Flutter to develop an app, I would avoid running it (the version of Flutter you have was only tested with the versions of packages it was locked to).

> And It took so long and I just close the studio and restarted.
> And flutter command never triggers anything since then.

My guess is that the Flutter process was terminated without removing its lock file. You could ensure there are no Flutter processes running in Task Manager and then manually delete the lock file from `<Flutter SDK> bin/cache/lockfile`.

**Comment by C-Zuge** [comment]
I'm having the same described problem w/ Flutter. As you suggested, i deleted the LockFile from the flutter folder and not worked. What can i do?

**Comment by sknaqvi70** [comment]
I had the same issue. Open CMD with Administrator's privileges. All commands started executing.

**Comment by DanTup** [comment]
> Open CMD with Administrator's privileges. All commands started executing.

This suggests you may have Flutter in a protected folder that requires elevated privileges. You should move it to somewhere that doesn't (and if required, reset the permissions to inherit from the new location).

There are some notes about this on the [Get the Flutter SDK notes](https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk):
> do not install Flutter in a directory like `C:\Program Files\` that requires elevated privileges
