### ISSUE TITLE
[Google Map Plugin] Need to apply customized style

### ISSUE THREAD

**Issue by dinhha** [flutter/flutter#24147]
Thanks for developing the Map Plugin.
Could you guys add the Styling feature to Google Map Plugin?
[https://developers.google.com/maps/documentation/android-sdk/styling](https://developers.google.com/maps/documentation/android-sdk/styling)

**Comment by andreabtis** [comment]
You can use a modal to customize the marker details. 
We are using showModalBottomSheet() method when a marker is tapped:

controller.onMarkerTapped.add((Marker marker){
showModalBottomSheet()
}

**Comment by dinhha** [comment]
No, I meant to customize the parts of Google Map such as color of roads, hide some feature (government places, schools, ...)

**Comment by AmeerTgh** [comment]
> You can use a modal to customize the marker details.
> We are using `showModalBottomSheet()` method when a marker is tapped:
> 
> ```dart
> controller.onMarkerTapped.add((Marker marker){
> showModalBottomSheet()
> }
> ```

we needs to styling map. more info: https://developers.google.com/maps/documentation/android-sdk/styling

**Comment by rahulmanthena** [comment]
I sent a pull request for this issue. Can someone please have a look. Thanks.
[https://github.com/flutter/plugins/pull/1143](url)

**Comment by talamaska** [comment]
Any ETA on this feature?

**Comment by J1GGZ** [comment]
Dying for this.... Please someone!

**Comment by Carvalho96v2** [comment]
Any updates here?

**Comment by rahulmanthena** [comment]
I pushed my latest changes. It's on Google's side to now

**Comment by EmmanuelOgbewe** [comment]
Thank you, Any Updates ?

**Comment by talamaska** [comment]
@rahulmanthena there are couple of comments unresolved, including tests. Please take a look at the PR

**Comment by J1GGZ** [comment]
> You can use a modal to customize the marker details.
> We are using `showModalBottomSheet()` method when a marker is tapped:
> 
> ```dart
> controller.onMarkerTapped.add((Marker marker){
> showModalBottomSheet()
> }
> ```

can you post your code? im trying to accomplish this but am having huge difficulty

**Comment by Zhanes** [comment]
Any update on this? When it will be ready? We are in a critic moment of deciding if Flutter or Ionic and this is the last milestone...

**Comment by lordmacu** [comment]
Please add style to google map, we need to  change the color but dont see that option, thanks and great work.
