### ISSUE TITLE
App not responding to landscape mode (android emulator)

### ISSUE THREAD

**Issue by Abdullah1353** [flutter/flutter#24150]
i am using flutter for the first time... issue i am having is that emulator or my app i dont know.. not responding to the landscape mode..Anyone know how to fix that?
<img width="209" alt="emu1" src="https://user-images.githubusercontent.com/44639133/48255651-2d55e580-e42f-11e8-97da-ef7d26b413a0.PNG">
<img width="406" alt="emu2" src="https://user-images.githubusercontent.com/44639133/48255652-2dee7c00-e42f-11e8-8dc7-784392347b6f.PNG">

**Comment by beckler** [comment]
Is rotation locked on your emulator?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Abdullah1353** [comment]
> e

@beckler i cant find anything like that kindly guide me through that
