### ISSUE TITLE
Building through gradlew does not produce an APK

### ISSUE THREAD

**Issue by Empty2k12** [flutter/flutter#24151]
I am trying to build my app from fastlane using Gradle.

My Gradle instruction in the fastfile looks like this
```
gradle(
  task: "assemble",
  build_type: "Release",
  flags: "-Pverbose=true -Ptarget=lib/main.dart -Ptrack-widget-creation=false -Ptarget-platform=android-arm",
)
```

It translates into this command
```
/Users/Empty2k12/my-app/android/gradlew -Pverbose=true -Ptarget=lib/main.dart
-Ptrack-widget-creation=false -Ptarget-platform=android-arm assembleRelease
```

The command does not produce an APK.

Running `flutter build apk --verbose`, I can see the command to build the APK is
```
[   +2 ms] Gradle task 'assembleRelease'...
[   +3 ms] executing: [/Users/Empty2k12/my-app/android/]
/Users/Empty2k12/my-app/android/gradlew -Pverbose=true -Ptarget=lib/main.dart
-Ptrack-widget-creation=false -Ptarget-platform=android-arm assembleRelease
```

What am I doing wrong? How can I build a Flutter APK using gradlew?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Is this still an issue?
