### ISSUE TITLE
iOS Plugins Fail with Objective C and Swift Channels 

### ISSUE THREAD

**Issue by jrmarkham** [flutter/flutter#24171]
iOS Plugins Fail with Objective C and Swift Channels 
// Rebuilds are here 
https://github.com/jrmarkham/flutter_plugins_objc
https://github.com/jrmarkham/flutter_plugins_swift 

```
Tech Specs: 
MacOS: 10.14.1
Flutter (Channel master, v0.11.1-pre.80, on Mac OS X 10.14.1 18B75, locale
    en-US)
    • Flutter version 0.11.1-pre.80 at /usr/local/lib/flutter
    • Framework revision 48c00dc7d7 (3 days ago), 2018-11-06 12:32:35 -0800
    • Engine revision fb5b097e5c
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)
```

IDEs: Intellij Ultimate 2018.2.5 

I have found that developing channels with Objective C and Swift that are using packages (that are object C) causes issues. I built 2 identical projects with 2 plugins (image picker and URL launcher) both projects work (plugins work as expected) before the channel is added. 

In the both Objective C and Swift app once the channel is added; the plugins fail but the channel does work— I have them just returning a boolean in both. 

IntelliJ
On builds from IntelliJ the following error freeze the app: 

// OBJECTIVE C
```objc
exception = {MissingPluginException} MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
 message = "No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher"
method = "canLaunch"
this = {MethodChannel} 
arguments = {_InternalLinkedHashMap} size = 1
result = null
```
```
exception = {MissingPluginException} MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
method = "pickImage"
this = {MethodChannel} 
arguments = {_InternalLinkedHashMap} size = 3
result = null
```

// SWIFT
```swift
exception = {MissingPluginException} MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
method = "canLaunch"
this = {MethodChannel} 
arguments = {_InternalLinkedHashMap} size = 1
result = null
```
```
exception = {MissingPluginException} MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
method = "pickImage"
this = {MethodChannel} 
arguments = {_InternalLinkedHashMap} size = 3
result = null
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by jrmarkham** [comment]
Well I have tried all channels: master/dev/beta -- I used dev the most so here that one: 

plugins_swift > flutter doctor -v
[✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.3 at /usr/local/lib/flutter
    • Framework revision 72bf075e8d (2 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/johnmarkham/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Users/johnmarkham/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (2 available)
    • JM iPhone X   • fb23caaec4bfc8e2ad73ab81cb5717a370687766 • ios • iOS 12.1.1
    • iPhone XS Max • 347C2D03-F79A-4C35-905A-6DBBE68871AB     • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by jrmarkham** [comment]
Let me know if you need others-- I happy to help you guys fix these channel / plugin conflicts.

**Comment by dnfield** [comment]
You removed this line from AppDelegate.m, which registers plugins:

```objc
  [GeneratedPluginRegistrant registerWithRegistry:self];
```

Add it back and everything's good, e.g.

```objc
- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    FlutterViewController* controller = (FlutterViewController*)self.window.rootViewController;

    FlutterMethodChannel* batteryChannel = [FlutterMethodChannel
                                           methodChannelWithName:@"com.channels/test"
                                           binaryMessenger:controller];

    [batteryChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result){
        if([@"test" isEqualToString:call.method]){
            BOOL res = [self channelTest];
            if(!res){
                result([FlutterError errorWithCode:@"UNAVAILABLE"
                                           message:@"test fail"
                                           details:nil]);
            }else{
                result(@"test worked");
            }

        }else{
            result(FlutterMethodNotImplemented);
        }
    }];
  [GeneratedPluginRegistrant registerWithRegistry:self];

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

**Comment by dnfield** [comment]
I'm going to close this for now - when I add this back on your demo repo, everything's working fine.  Please feel free to reopen if you feel like this hasn't addressed your issue, or open a new issue if there's some other problem at play here!

**Comment by jrmarkham** [comment]
Yup I see.....Thanks. Where/what would I add the for the swift build?


FYI: I copied that code block from the flutter channel so you may want to update that as well. 
https://flutter.io/docs/development/platform-integration/platform-channels

**Comment by dnfield** [comment]
I'll reopen this to track fixing the docs.

For Swift it should be `GeneratedPluginRegistrant.register(with: self)`

**Comment by jrmarkham** [comment]
Thanks Dan. I’ll test Swift later... ObjectiveC worked just fine.

**Comment by jrmarkham** [comment]
Swift verified to thanks
