### ISSUE TITLE
CupertinoTextField unable to override the default placeholder color.

### ISSUE THREAD

**Issue by ffimnsr** [flutter/flutter#24175]
I'm having problems on overriding the default color for `placeholder` in CupertinoTextField. As I'm trying to set it white it always turns to gray. I've inspected the flutter source base and found this:

https://github.com/flutter/flutter/blob/dfd022956044fe9e336eaa5b93e418befa1918ee/packages/flutter/lib/src/cupertino/text_field.dart#L541-L558

Is there any other way around this?
Here is my flutter installation details:
~~~
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (1 available)

• No issues found!
~~~

**Comment by xster** [comment]
Indeed it is static since it's not customizable on iOS either. https://developer.apple.com/documentation/uikit/uitextfield/1619621-placeholder?language=objc

Do you have a mock-up of the effects you're trying to achieve?

**Comment by ffimnsr** [comment]
Indeed @xster, but what do I override it? The default `placeholder` is just text in regards to that, developers given an option to customize it using `attributedPlaceholder` to set UIColor.
https://developer.apple.com/documentation/uikit/uitextfield/1619610-attributedplaceholder?language=objc

Well, what I'm trying to achieve is set the placeholder color similar to the text color of the `UITextField`.

```
                      child: CupertinoTextField(
                        style: TextStyle(color: CupertinoColors.white),
                        placeholder: "Email",
                        decoration: BoxDecoration(
                          border: Border.all(
                            width: 0.0,
                            color: Color(0x00FFFFFF),
                          ),
                        ),
                        controller: _emailController,
                        onChanged: (String value) {
                          _data.email = value.trim();
                        },
                      ),
```

**Comment by ffimnsr** [comment]
Hi @xster, I've submitted a minor update for the placeholder customization.

**Comment by patelkrunal78** [comment]
Maybe This Can Help You [Here](https://icetutor.com/question/flutter-how-to-change-textfield-hint-color)
