### ISSUE TITLE
RFE: add SwitchListTile.adaptive constructor

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter#24186]
https://github.com/flutter/flutter/pull/22688 added a constructor for Switch that adapts to the ambient platform (uses a material Switch for Android and a cupertino Switch for iOS).

SwitchListTile incorporates a Switch but there is no way to pass through the "adaptive" part.

Can we please have a SwitchListTile.adaptive constructor constructor that makes the tile use an adaptive Switch?

**Comment by HansMuller** [comment]
Good suggestion!

**Comment by justinmc** [comment]
Alright I implemented this over in the linked PR.  It should work just like `Switch.adaptive`.
