### ISSUE TITLE
API docs: update the Documentation link on the landing page

### ISSUE THREAD

**Issue by galeyang** [flutter/flutter#24185]
After setting up the accurate redirects on flutter.io ([issue filed](https://github.com/flutter/website/issues/1714)), "Install" and "Get Started" will be redirected to the same URL (https://flutter.io/docs/get-started/install). So, we only need to keep one.

![image](https://user-images.githubusercontent.com/5102864/48291873-d818d480-e42c-11e8-88b9-236d78dfa1be.png)

**Comment by zoechi** [comment]
I can't find the parts your screenshots show. Seems they were taken before the new UI update. 
Can you please update your issue.

**Comment by galeyang** [comment]
The screenshot I attached was captured on [the beta site](https://docs.flutter.io/). In the master site, this issue seems to be fixed by the new landing page update. Should I close this issue now? Or wait until this fix is released in the beta API site.

**Comment by zoechi** [comment]
Let's close for now.
Please reopen if you can reproduce after it landed in beta.
