### ISSUE TITLE
Scrollable's scrollTo/scrollBy Future behaviour needs to be reexamined and/or documented.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2419]
Currently if you:

``` dart
Future future1 = scrollable.scrollTo(100);
Future future2 = scrollable.scrollTo(-100);
```

It's not clear what to expect from future1.

I would suggest future1 should complete with error since it was unable to get where it wanted to go.

**Comment by abarth** [comment]
If you use async/await, completing with an error is modeled as throwing an exception.  We can certainly do that, but I'm worried that might not be what you want.

**Comment by apwilson** [comment]
Well, possibly the return value of the future is the current scroll value and/or an error flag?

**Comment by apwilson** [comment]
Also, we should document when the future completes vs the onScroll* events firing.  It appears the future completes after the onScrollEnd which is good and is what I want but without it being documented there's no contract so I can't depend on that behaviour.

**Comment by Hixie** [comment]
Behaviour is covered by other bugs; documentation will come later.

**Comment by apwilson** [comment]
Obsolete I think.
