### ISSUE TITLE
Request to document Material

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#242]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Thursday Oct 29, 2015 at 21:01 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1874_

----

Was looking at sample code in the Tutorial, and it used a Material class. I wanted to know what that was for, but didn't see docs for it in my editor (Atom)

![screen shot 2015-10-29 at 2 00 37 pm](https://cloud.githubusercontent.com/assets/5479/10831923/97f3ceb4-7e45-11e5-9c46-e88aecb155e9.png)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 29, 2015 at 21:32 GMT_

----

Yes, we need to add more dartdoc to the higher levels of the system.

**Comment by sethladd** [comment]
Going to close this issue, as it's too vague. Generally speaking API docs are good :)
