### ISSUE TITLE
Flutter: Build errors for cloud_firestore: above version “0.7.4”

### ISSUE THREAD

**Issue by LiveRock** [flutter/flutter#24201]
Flutter: Build errors for cloud_firestore: above version “0.7.4”

iOS build fine but Android build failed.
I have looked thru all similar cases but I still cannot resolve my Android build errors:

```

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
/Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:160: error: cannot find symbol
        query = query.whereArrayContains(fieldName, value);
                     ^
  symbol:   method whereArrayContains(String,Object)
  location: variable query of type Query
/Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:601: error: cannot find symbol
            builder.setTimestampsInSnapshotsEnabled(
                   ^
  symbol:   method setTimestampsInSnapshotsEnabled(Boolean)
  location: variable builder of type Builder
/Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:681: error: cannot find symbol
        return FieldValue.arrayUnion(toArray(readValue(buffer)));
  symbol:   method arrayUnion(Object[])
  location: class FieldValue
/Users/dev/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java:683: error: cannot find symbol
        return FieldValue.arrayRemove(toArray(readValue(buffer)));
                         ^
  symbol:   method arrayRemove(Object[])
  location: class FieldValue
4 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':cloud_firestore:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I tried for weeks and couldn't resolve it. To build Android, I need to specify cloud_firestore version 0.7.4
Anything above, the Android Build fails.

Any pointers?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by kitet** [comment]
Hey @zoechi .  I am getting the same error and this is my flutter doctor -v output

`[✓] Flutter (Channel master, v0.11.4-pre.30, on Mac OS X 10.14 18A391, locale en-KE)
    • Flutter version 0.11.4-pre.30 at /Users/htywidjf89/Development/flutter
    • Framework revision aa65fa2fa1 (13 minutes ago), 2018-11-12 23:47:16 -0800
    • Engine revision ea4bbbd440
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/htywidjf89/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!`

**Comment by kitet** [comment]
@LiveRock  I got rid of the error by updating the project level build.gradle on android as follows 

`classpath 'com.android.tools.build:gradle:3.2.1'
  classpath 'com.google.gms:google-services:4.1.0'`

Maybe you could try the same. 
However now running into another problem 

`Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50650/ws`

**Comment by kroikie** [comment]
@LiveRock

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/579. Any further collaboration will be done there.
