### ISSUE TITLE
Text selection handles display outside visible text region

### ISSUE THREAD

**Issue by sjindel-google** [flutter/flutter#24214]
This can be reproduced by selecting a word and scrolling so that the word is outside the visible area of the screen. These two screenshots demonstrate:

![before](https://user-images.githubusercontent.com/29863079/48304189-c2330e80-e515-11e8-8f0a-3a6e9da9d5a8.png)
![after](https://user-images.githubusercontent.com/29863079/48304190-c5c69580-e515-11e8-98eb-921f75ac8025.png)

On Android, the behavior is that the handles disappear (atomically) when the position they point to leaves view, and reappear (atomically) when the position re-enters view. The following screenshots demonstrate how that would look instead:

![left_hidden](https://user-images.githubusercontent.com/29863079/48304469-3a033800-e51a-11e8-874a-211715e32918.png)
![right_hidden](https://user-images.githubusercontent.com/29863079/48304471-4091af80-e51a-11e8-9340-849e67ee0a69.png)
![both_hidden](https://user-images.githubusercontent.com/29863079/48304472-42f40980-e51a-11e8-8f73-78ffe353260e.png)

In the last example, the right handle is completely invisible, even though it points to just after then "n" in "brown", which is barely off the screen. This illustrates the Android behavior that the handles are either completely visible or completely invisible (never clipped).

@GaryQian

**Comment by goderbauer** [comment]
This also happens on iOS.

**Comment by justinmc** [comment]
@goderbauer It seems like our text selection on iOS is slightly different than native.  In a native iOS app, I can't scroll unless I long press, and that clears the current selection, so the handles can never display outside of the field.

In a Flutter app on iOS it does allow me scroll, though, so this bug shows up.  Is our deviation from native intentional?

**Comment by goderbauer** [comment]
A deviation from the native behavior is probably unintentional in this case and we should fix that.

Having said that, I am not seeing the behavior you're describing on my iOS device: I can totally scroll in a native app when text is selected in a text field. So, I am not sure what you mean by that you have to log press it?

**Comment by justinmc** [comment]
You're right, it is possible in a native iOS app, not sure what I was trying before.  So this fix does need to happen in iOS as well.

**Comment by xster** [comment]
![](https://media.giphy.com/media/1Aj1n4YRz0BJmpLvqV/giphy.gif)

Made a video
