### ISSUE TITLE
Material clipping does not work correctly anymore

### ISSUE THREAD

**Issue by flschweiger** [flutter/flutter#24225]
When using a Material widget with a border radius or a custom shape, the child is not clipped correctly. E.g. InkWells will ripple in a square without rounded corners even when a BorderRadius is set on the Material. This also happens when using the diamond shaped FAB from the examples.

This behaviour occurs on all current channels (dev, beta and master). However, I have also added my current `flutter doctor` output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.3-pre.15, on Mac OS X 10.14 18A391, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by kunit1** [comment]
Did you specify the clip behavior on the widget?

**Comment by flschweiger** [comment]
@kunit1 Nope, a simple example would be:

```
Material(
  borderRadius: BorderRadius.circular(25.0),
  child: InkWell(
    onTap: () => print("Tap!"),
    child: SizedBox(
      width: 80.0,
      height: 80.0,
      child: Center(
        child: Text("Tap me!"),
      ),
    ),
  ),
);
```

In this sample the ripple effect would not get clipped and overlap the rounded corners of the Material.

**Comment by jason-simmons** [comment]
See https://docs.flutter.io/flutter/dart-ui/Clip-class.html

The widget's default behavior is `Clip.none`.  To get the desired effect, try a different `clipBehavior` such as `Clip.antiAlias`

**Comment by flschweiger** [comment]
@jason-simmons Also tried specifying the clipping behaviour before, it's not working. This also shouldn't be the issue because it behaved differently on earlier Flutter versions. It doesn't make any sense to me if you specify a border radius on a Material and then it's not clipping the children by default.

**Comment by flschweiger** [comment]
Fixed the issue, somehow my Flutter copy was messed up. Cloned the repo again and now it's working fine - sorry for the confusion everyone 🙈

**Comment by flschweiger** [comment]
This is still happening on the most recent version. However, as @slightfoot pointed out in the Flutter Study Group, there's already a fix for it which still needs to be merged: https://github.com/flutter/engine/pull/6923

**Comment by slightfoot** [comment]
@flschweiger please clarify with a new example. I assume you've specified `clipBehavior` now.

**Comment by zoechi** [comment]
> However, the explicit clipBehavior shouldn't even be needed when a borderRadius is specified, or? 

@flschweiger that's because of #18057
See also https://github.com/flutter/flutter/issues/25028#issuecomment-446388091

I'm going to close. Please add a comment to have it reopened if you disagree.

**Comment by The-five-stooges** [comment]
i found this issue too, how to get it work right?

**Comment by mahdizakizadeh** [comment]
I think I have the same issue now.
The problem is that ClipRRect widget does not affect ripple effect :/

**Comment by slightfoot** [comment]
@mahdizakizadeh It never has. Please read the docs. Ripple effects from InkWell and similar are painted on the ancestor Material widget.

**Comment by fluttercorner** [comment]
[How to Create a rounded button / button with border-radius in Flutter](https://fluttercorner.com/how-to-create-rounded-button-button-with-border-radius-in-flutter/)
