### ISSUE TITLE
Navigator operation requested with a context that does not include a Navigator.

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#24220]
```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  GlobalKey<ScaffoldState> globalKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    _appContext = NetWork.setContext(context);
    return MaterialApp(
```
```dart
Navigator.of(_appContext)
          .push(MaterialPageRoute(builder: (BuildContext context) {
        return Login();
      }));
```

```
Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
#0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1291:9)
#1      Navigator.of (package:flutter/src/widgets/navigator.dart:1298:6)
#2      NetWork.handleErrorCode (package:txx/utils/network.dart:168:17)
#3      _LoginState._sendHello (package:x_app/pages/find.dart:67:15)
<asynchronous suspension>
#4      _LoginState.build.<anonymous closure> (package:x_app/pages/find.dart:48:15)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#8      TapGestureRecogn<…>

```

so ,if I can push a new page with `context that does not include a Navigator`,How can I present a new page with `context that does not include a Navigator`.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by mehedi432** [comment]
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        home: new HomeScreen());
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Title"),
      ),
      body: new Center(child: new Text("Click Me")),
      floatingActionButton: new FloatingActionButton(
        child: new Icon(Icons.add),
        backgroundColor: Colors.orange,
        onPressed: () {
          print("Clicked");
          Navigator.push(
            context,
            new MaterialPageRoute(builder: (context) => new AddTaskScreen()),
          );
        },
      ),
    );
  }
}

This works for me..

**Comment by bekagaw653** [comment]
already solved at https://icetutor.com/question/navigator-operation-requested-with-a-context-that-does-not-include-a-navigator/
