### ISSUE TITLE
Track size of hello_world example on every build

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2423]
Ideally would like a unified [bloat diagram](http://neugierig.org/software/chromium/bloat/) which included compressed and uncompressed size information all the way up and down the stack (from image/font sizes all the way down to C++ symbol attribution).  But that's probably too much to ask.  Lets start by just tracking a single number.

**Comment by eseidelGoogle** [comment]
I think we track this size now, no?  @yjbanov

**Comment by abarth** [comment]
Done.

**Comment by yjbanov** [comment]
Yep. Done. We don't have a bloat diagram, but we do track the sizes of individual files produced by Dart's AOT compiler.
