### ISSUE TITLE
ProcessException: %1 is not a valid Win32 application. With git.exe

### ISSUE THREAD

**Issue by FogelAO** [flutter/flutter#24232]
I have got the problem with flutter, when I am trying to run any command in flutter shell it crashs. I think that problem is in space in `Program Files`. I've checked [This issue](https://github.com/flutter/flutter/issues/9976). But it didn't help me.  My flutter version is flutter_windows_v0.10.2-beta. I also can't run `flutter --verbose` and `flutter doctor -v`, because I have same error
Output:

```
Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:326:48)
#5      runSync (package:flutter_tools/src/base/process.dart:300:10)
#6      _runGit (package:flutter_tools/src/version.dart:501:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:16)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:70:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:170:48)
#14     new Usage (package:flutter_tools/src/usage.dart:27:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#21     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#22     _handleToolError (package:flutter_tools/runner.dart:106:7)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:63:20)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#31     run (package:flutter_tools/runner.dart:50:10)
#32     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#33     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#34     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by zoechi** [comment]
Can you please fix the error output so that the exception and the stack trace are combined in one output. Currently you have the exception only in the title. I find this confusing and it's unclear how the full error output looks like.

**Comment by FogelAO** [comment]
@zoechi 
This is the full output with the command. Hope it will help
![image](https://user-images.githubusercontent.com/24193116/48363178-605dda80-e6b6-11e8-91f2-be30b73989c2.png)

**Comment by zoechi** [comment]
Can you please add that as text instead of as screenshot? Screenshots are not searchable.

**Comment by FogelAO** [comment]
@zoechi , Yes, sure.

C:\Users\spam7>flutter doctor
CreateProcessW failed 193

CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Git\cmd\git.EXE rev-parse --abbrev-ref --symbolic @{u}
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:326:48)
#5      runSync (package:flutter_tools/src/base/process.dart:300:10)
#6      _runGit (package:flutter_tools/src/version.dart:501:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:16)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:70:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:170:48)
#14     new Usage (package:flutter_tools/src/usage.dart:27:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:83:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:53:39)
#21     flutterUsage (package:flutter_tools/src/usage.dart:21:33)
#22     _handleToolError (package:flutter_tools/runner.dart:106:7)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:63:20)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
<asynchronous suspension>
#31     run (package:flutter_tools/runner.dart:50:10)
#32     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#33     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#34     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by zoechi** [comment]
That looks exactly as #19359
I'll merge it with #19359
