### ISSUE TITLE
Error creating IOS version to upload to Testflight.

### ISSUE THREAD

**Issue by foosionsapps** [flutter/flutter#24239]
Hi, I want to upload a flutter app to apple store but when I go to Xcode and I make: Product -> Archive
After some minutes of Xcode process I get this error:
```
Could not find an option named "track-widget-creation".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Failed to build /Users/{"myUser"}/IdeaProjects/{"myProjectName"}.
Command /bin/sh failed with exit code 255
```

Here is my flutter doctor -v:
```
[✓] Flutter (Channel dev, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-AR)
    • Flutter version 0.11.3 at /Users/{"myUser"}/flutter
    • Framework revision 72bf075e8d (2 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/{"myUser"}/Library/Android/sdk
    • Android NDK at /Users/{"myUser"}/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • {"myUser"} Phone • af7486d829711c96bebd0ccdd8e2d281ebd4825b • ios • iOS 12.0

• No issues found!
```

Can someone help me?

Thanks!

**Comment by xster** [comment]
cc @jacob314

**Comment by FViscardi** [comment]
@foosionsapps

In the meantime, you can try and go to Runner -> Build Settings (Tab), scroll down and set "TRACK_WIDGET_CREATION" = false under "User-Defined"

I'm currently trying that approach myself, as I ran into the same issue today.

**Comment by zoechi** [comment]
```
flutter run --no-track-widget-creation
```
seems to work as well
https://github.com/flutter/flutter/issues/20260#issuecomment-439157377

**Comment by alann-maulana** [comment]
I got this **Could not find an option named "track-widget-creation"** error too when executing 
```
flutter build ios
```
Here is my `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.7-pre.47, on Mac OS X 10.14 18A391, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by freezestudio** [comment]
> I got this **Could not find an option named "track-widget-creation"** error too when executing
> 
> ```
> flutter build ios
> ```
> Here is my `flutter doctor`
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v0.11.7-pre.47, on Mac OS X 10.14 18A391, locale en-ID)
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> [✓] Android Studio (version 3.2)
> [✓] VS Code (version 1.28.2)
> [✓] Connected device (3 available)
> 
> • No issues found!
> ```

me too.

**Comment by wenerme** [comment]
> @foosionsapps
> 
> In the meantime (in XCode), you can try and go to Runner (Poject) -> Build Settings (Tab), scroll down and set "TRACK_WIDGET_CREATION" = false under "User-Defined"
> 
> I'm currently trying that approach myself, as I ran into the same issue today.

Not works.

**Comment by wenerme** [comment]
Work around

```bash
code $FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh
```

```bash
  local track_widget_creation_flag=""
  if [[ -n "$TRACK_WIDGET_CREATION" ]]; then
    # Remove the flag
    # track_widget_creation_flag="--track-widget-creation"
    track_widget_creation_flag=""
  fi
```

**Comment by kleyos** [comment]
> ```
> flutter run --no-track-widget-creation
> ```
> seems to work as well
> [#20260 (comment)](https://github.com/flutter/flutter/issues/20260#issuecomment-439157377)

how to create archive build with it?

**Comment by kleyos** [comment]
> Work around
> 
> ```shell
> code $FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh
> ```
> 
> ```shell
>   local track_widget_creation_flag=""
>   if [[ -n "$TRACK_WIDGET_CREATION" ]]; then
>     # Remove the flag
>     # track_widget_creation_flag="--track-widget-creation"
>     track_widget_creation_flag=""
>   fi
> ```

Permission denied

**Comment by calebisstupid** [comment]
This is a weird one that I have been facing for the past few days since updating Flutter.

For me, the solution is to run "flutter build ios --release" in the project directory, which will fail often times with several pod errors, but I just ignore those and re-archive in Xcode and it works.

I do not know enough about iOS build tools to know why these things fail. Just that before the newest beta branch version "flutter build ios --release" worked, now it fails but doesn't mean anything serious, and despite the flutter documentation, I still have to run this command before archiving in Xcode or I get strange errors like this one.

**Comment by albo1337** [comment]
This helped me a lot! I just got this strange error message out of no where. After releasing my app and updating it about 10 times this error now appears.... Thank you very much @calebisstupid

**Comment by abraar14** [comment]
Would having Xcode 9.3 have any effect on this error. I've tried almost all the steps I could find, but the archive was only built once successfully. Following which, the window to analyze and publish never opened, so I did the process again and back to the start with the same error listed above.

**Comment by Olb** [comment]
Show stopper for me. I cannot archive iOS to upload to iTunes Connect. "TRACK_WIDGET_CREATION" = false under "User-Defined" does not work. This started when I switched to 1.0 stable. I am not trying to run it but archive it so "flutter run --no-track-widget-creation" doesn't help me.

**Comment by abraar14** [comment]
> Show stopper for me. I cannot archive iOS to upload to iTunes Connect. "TRACK_WIDGET_CREATION" = false under "User-Defined" does not work. This started when I switched to 1.0 stable. I am not trying to run it but archive it so "flutter run --no-track-widget-creation" doesn't help me.

wenerme has posted a workaround for it above in this thread to edit the backend.sh, follow the steps and it should work succesfully. Worked in my case.

**Comment by neerajyadav** [comment]
`flutter` is in release 1.0 now. This issue should be fixed.

**Comment by zoechi** [comment]
Related #24641

**Comment by timbergus** [comment]
Probably relate with #25167 too.

**Comment by andrewzimmer906** [comment]
Man this issue is such a nightmare.  If I edit my flutter build to fix it I start getting other issues after a while.  Every time I get it working in one project it breaks in another.  Sorry I know this isn't helpful, I'll try to post a better report later, just frustrated.

**Comment by pinizhaninov** [comment]
Just add TRACK_WIDGET_CREATION= to Release.xcconfig

**Comment by SamuelRioTz** [comment]
i had the same problem and i fixed that, just removing the build folder from my project and try archive again

**Comment by zoechi** [comment]
> removing the build folder

```
flutter clean
```
does that

**Comment by Klauzt** [comment]
> Work around
> 
> ```shell
> code $FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh
> ```
> 
> ```shell
>   local track_widget_creation_flag=""
>   if [[ -n "$TRACK_WIDGET_CREATION" ]]; then
>     # Remove the flag
>     # track_widget_creation_flag="--track-widget-creation"
>     track_widget_creation_flag=""
>   fi
> ```

While doing this I lost all hot reload capabilities on iOS, so instead of removing completely the flag I tried to just use it on release mode

```shell
local track_widget_creation_flag=""
if [[ -n "$TRACK_WIDGET_CREATION" && "${build_mode}" == "debug" ]]; then
  track_widget_creation_flag="--track-widget-creation"
fi
```

It seems to work so far

**Comment by zoechi** [comment]
@Klauzt https://github.com/flutter/flutter/issues/24239#issuecomment-440739466 should do as well

**Comment by IAmKio** [comment]
XCode > Runner Target > Build Settings > Scroll down to `User-Defined` and deleted all three entries for `TRACK_WIDGET_CREATION`. Solved it (for me).

**Comment by campioncino** [comment]
@IAmKio Great!
It works for me too!

**Comment by moadqassem** [comment]
Well, I have encountered this issue and I didn't have to do anything either in `sh` scripts nor Xcode. The only thing I tried was: 

From the flutter project root directory, executed the following: 
`flutter clean`
`flutter build ios` 

So in other words don't build your flutter project using Xcode directly because your project might need some commands to be executed(preprocessing) which flutter is doing for you and then it uses Xcode build. 

After the build is done go to Xcode and try to Archive your project once again. 

**P.S: Flutter Version that I am running v1.4.8**

**Comment by mobilecheng** [comment]
XCode > Runner Target > Build Settings > Scroll down to User-Defined and deleted all three entries for TRACK_WIDGET_CREATION. Solved it (for me).

@IAmKio  Thank you, It works for me too!

**Comment by BRLOKESH** [comment]
iOS build Archiving but display white screen.

How to resolve this issue.

**Comment by mobilecheng** [comment]
Please install version 1.0.0 (8) from TestFlight.


Best.


Original Message
Sender:BRLOKESHnotifications@github.com
Recipient:flutter/flutterflutter@noreply.github.com
Cc:mobilechengmobilecheng@qq.com; Commentcomment@noreply.github.com
Date:Monday, Jul 8, 2019 14:35
Subject:Re: [flutter/flutter] Error creating IOS version to upload toTestflight. (#24239)


iOS build Archiving but display white screen.
How to resolve this issue.

**Comment by mobilecheng** [comment]
@BRLOKESH   Archiving for Generic iOS Device.

![image](https://user-images.githubusercontent.com/787620/60790964-40bf7900-a195-11e9-9904-4dde41aa6aee.png)

**Comment by MightyRai90** [comment]
> iOS build Archiving but display white screen.
> 
> How to resolve this issue.

Any success about fixing the white screen?

**Comment by BRLOKESH** [comment]
No Success .. 
![Screen Shot 2019-07-18 at 10 58 13 AM](https://user-images.githubusercontent.com/31733760/61432240-61ce5980-a94d-11e9-8d0c-130e31c42ce9.png)

**Comment by mobilecheng** [comment]
@BRLOKESH  Try running 'flutter build ios --release' before Archiving with XCode.

**Comment by BRLOKESH** [comment]
Now Working **Thanks @mobilecheng  **

LOKESH:~ LOKESH$ touch ~/.bash_profile
LOKESH:~ LOKESH$ open -e ~/.bash_profile
LOKESH:~ LOKESH$ source $HOME/.bash_profile
LOKESH:~ LOKESH$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/apple/Desktop/flutter V1.5.4/flutter/bin:/Users/apple/Desktop/flutter V1.5.4/bin
LOKESH:~ LOKESH$
