### ISSUE TITLE
After upgrading Error java invalid source release 11

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#24238]
When I try to build my Flutter project I get:

- Error java invalid source release 11 

I upgrade the Flutter today, rest of the details in below:

**OS:** macOS Mojave 10.14.1
**IDE:** IntelliJ IDEA Community 2018.2.5
        Build: #IC-182.4892.20, built on October 16, 2018
        JRE: 1.8.0_152-release-1248-b19 x86_64
        JVM: OpenJDK 64-Bit

**Terminal:** 
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by zoechi** [comment]
>  I install jdk 11 and re configure the IDE and its working now.

doesn't sound like a Flutter issue then.
I'm going to close.

**Comment by NTMS2017** [comment]
thanks
