### ISSUE TITLE
Making HTTPS request

### ISSUE THREAD

**Issue by karvendanKuppusamy** [flutter/flutter#24237]
POST(): https://example.com/endpoint
I/flutter (24515):       : {username: user, password: password, grant_type: password}
I/flutter (24515): POST():	Error
I/flutter (24515): 			HandshakeException: Handshake error in client (OS Error: 
I/flutter (24515): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:363))

how to handle the https requests in dart-flutter?

**Comment by pouledodue** [comment]
what is the fix?
