### ISSUE TITLE
Flutter crashes when displaying TextField

### ISSUE THREAD

**Issue by robinbakkerus** [flutter/flutter#24245]
Flutter crashes on this line:
 ```
new Row(
            children: <Widget>[
              **new TextField(),**  //line 95 in admin_page.dat
            ],
          ),
```

Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[ÔêÜ] Flutter (Channel beta, v0.10.2, on Microsoft Windows [Version 6.1.7601], locale nl-NL)
[ÔêÜ] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[ÔêÜ] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2017.1)
    X Flutter plugin version 15.1 - the recommended minimum version is 16.0.0
[ÔêÜ] IntelliJ IDEA Community Edition (version 2017.3)
[ÔêÜ] IntelliJ IDEA Community Edition (version 2018.1)
[ÔêÜ] Connected device (1 available)

The connected device is Samsung
[stacktrace.log](https://github.com/flutter/flutter/files/2572864/stacktrace.log)

In the zipfile below, is the entire flutter project. The crash can reproduced  by un-commenting **line 95** in **src/widget/admin_page.dat**
[mijn_italiaans-dart-bug.zip](https://github.com/flutter/flutter/files/2572871/mijn_italiaans-dart-bug.zip)

**Comment by miyoyo** [comment]
This is **not a crash**, but a runtime layout issue.
TextField will attempt to be as big as possible width-wise, and unless you constrain it, it will be infinitely large.
Read up on the [expanded widget.](https://docs.flutter.io/flutter/widgets/Expanded-class.html)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
