### ISSUE TITLE
Error for lack of code signing certs gets swallowed in 'flutter run'

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#2424]
### Steps to Reproduce
* Follow the steps on https://flutter.io/setup/, preparing for iOS dev
* Try to 'flutter run' one of the example apps

### Flutter Version
Flutter from git@github.com:tvolkert/flutter.git (on master)
Framework: 932b09c33a24a60b59ef2682e0b88e632acfc1e4 (24 hours ago)
Engine:    ad37a616354f143c7779dba7f51356f43181e3d6

### Logs
 656 ms • /usr/bin/env xcrun xcodebuild -target Runner -configuration Release -sdk iphoneos -arch arm64
   0 ms • Error code 65 returned when attempting to run command: /usr/bin/env xcrun xcodebuild -target Runner -configuration Release -sdk iphoneos -arch arm64
   0 ms • ** BUILD FAILED **

### Analysis
Running xcrun directly produces the following error, which is getting swallowed:
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

**Comment by devoncarew** [comment]
@tvolkert, does this repo with the latest on master? I landed a change yesterday that might fix this.

**Comment by devoncarew** [comment]
https://github.com/flutter/flutter/pull/2397

**Comment by tvolkert** [comment]
Yep - fixed.
