### ISSUE TITLE
Cursor always at the front when typing emojis

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#24266]
The cursor often is stuck at the beginning of the TextField when typing strings of emojis (as well as some other types of characters)

Repro:

- Open any flutter TextField (the one in flutter_gallery>material>text fields should do)
- Type emoji characters, preferably ones with zero-width-joiners such as nation flags
- Cursor is stuck at front, and tapping in the text works (new text shows up correctly, backspacing works) but the cursor does not appear in the right spot.

This sometimes goes away when there are other characters around the emoji string.

**Comment by GaryQian** [comment]
The cause is that emojis that make use of zero width joiners take up more than two positions of offset. We only support two 16-bit codepoints, and when there are more than two 16-bit data that define a glyph, the offset of 2 is not enough to draw a rectangle around the character, and so is omitted.

**Comment by GaryQian** [comment]
The fix is currently waiting for approval and landing #24797

**Comment by zoechi** [comment]
@GaryQian #21745 looks similar. Is it likely that is fixed as well?
Not sure whether #25530 could be related.

**Comment by GaryQian** [comment]
There are actually a few different causes for such behavior, but it is very possible that the fix for iterating grapheme clusters does fix those. They would need to be verified case-by-case though as I am not familiar with the exact UTF16 codepoints that those issues use.

**Comment by shaqima123** [comment]
hello~ I met a problem like this, but there are some differences from yours.Could you do me a favor?#50563
