### ISSUE TITLE
Make sure splash screen doesn't block supplying an engine to FlutterViewController.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#24260]
`FlutterViewController` will attempt to show a splash screen using the default one for the app if it can't find one.

This is undesirable in many Add2App use cases where someone wants to display a FlutterViewController as a child/sub view without using a splash screen, but still has a splash screen for their app.

The embedding API should offer some easier way to avoid this.

/cc @matthew-carroll @jamesderlin

**Comment by jamesderlin** [comment]
Why not use `-[FlutterViewController setSplashScreenView:]` with a blank `UIView`?

**Comment by dnfield** [comment]
Hmm.  That seems to work when I don't initialize with a running engine.  This bug might be slightly different than I thought - seems like it's only affecting the case of initWithEngine.  Checking further.
