### ISSUE TITLE
Failed to move away or delete existing target file

### ISSUE THREAD

**Issue by SEAbdulbasit** [flutter/flutter#24271]
Failed to move away or delete existing target file: C:\Android\sdk\tools
Move it away manually and try again..
i am getting this issue while trying to install flutter

**Comment by zoechi** [comment]
Have you tried the suggestion.

> i am getting this issue while trying to install flutter

We would need a bit more concrete information to be able to understand what is going on.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
