### ISSUE TITLE
showDialog without current route

### ISSUE THREAD

**Issue by szotp** [flutter/flutter#24281]
How do I show dialog from root of the app (the widget that created MaterialApp)? 

showGeneralDialog method takes context, and uses it to call `Navigator.of`. But I already have Navigator (from GlobalKey). 

My use case is showing alert after user opened app with URL. It must be globally accessible.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by szotp** [comment]
I asked here because it looks like shortcoming of the SDK and there is nothing that stackoverflow can provide aside from a workaround.

**Comment by zoechi** [comment]
I'd suggest to ask on StackOverflow and if it actually turns out to be a valid issue to reopen with a link to the SO question.
I'm pretty sure you'll get a good answer on SO.
