### ISSUE TITLE
GridView scroll direction misbehaves under certain circumstances

### ISSUE THREAD

**Issue by realvotum** [flutter/flutter#24299]
I am trying to scroll the `GridView` horizontally when screen orientation is portrait and vertically when the screen orientation is landscape. However, I noticed a very strange behavior. What I mean is that when I change device orientation the widget scrolls the way I want, however the touch input stays the same, e.g. I start the app in portrait mode and I scroll the grid from left to right. Then, I change the device orientation and I still have to scroll the grid from left to right instead of from top to bottom. 

Here's the code gist, if you run it you will get what I mean:

https://gist.github.com/realvotum/b72e03e909e5bf0b47a5cd11e53ef67a

My observation is that when you uncomment the Appbar line, it works like a charm. Also, when you comment out the padding inside `GridView.count`, it also works the way I expect. If you delete `ScrollController`, it works too, yet I want to have `GridView` scroll callbacks to measure the offset. 

Is it a bug or am I doing something wrong? If so, how can I swap the scroll direction of the `GridView` based on the device orientation preserving the given padding and keep the scroll offset between orientation changes (without Appbar) ? 

I also noticed that `ListView.builder` behaves the same.

Thank you in advance!

Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14 18A391, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] Connected device (1 available)
```

**Comment by zuyetawarmatik** [comment]
I also have the same problem, but when putting in a ListView inside a RotatedBox.

Constructing `ListView(scrollDirection: Axis.horizontal)`, and put it inside a `RotatedBox(quarterTurns: -1)`, I still have to flick my finger horizontally although visibly the list is vertical.

**Comment by VladyslavBondarenko** [comment]
Reproduced with `dev  1.16.4-pre.33`

**Comment by VladyslavBondarenko** [comment]
Duplicate of https://github.com/flutter/flutter/issues/41617
