### ISSUE TITLE
flutter doctor or flutter version should print path and version of android SDK

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2429]
I have many Android sdks installed.  Would like to know that I'm using the same one as flutter.

Maybe what I want is flutter doctor to warn if adb in my path is different from the adb it's using?

**Comment by eseidelGoogle** [comment]
The same problem exists for `dart` in path vs. the dart sdk that flutter uses.  @collinjackson just ran into that just now.

**Comment by devoncarew** [comment]
fixed by https://github.com/flutter/flutter/pull/2859
