### ISSUE TITLE
flutter upgrade in flutter_gallery fails

### ISSUE THREAD

**Issue by kilianovski** [flutter/flutter#24292]
Followed [this](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) instructions to install flutter_gallery demo app, but the `flutter upgrade` command fails with:
```
Upgrading Flutter from /home/kilianovski/Documents/flutter...












Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 0.11.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 72bf075e8d (4 days ago) • 2018-11-09 20:36:17 -0800
Engine • revision 5646e86a6f
Tools • Dart 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

Running "flutter packages upgrade" in flutter_gallery...         
Because flutter_gallery depends on flutter_driver any from sdk which depends on process 3.0.8, process 3.0.8 is required.
So, because flutter_gallery depends on process 3.0.9, version solving failed.
 
pub upgrade failed (1)

```

**Comment by dnfield** [comment]
Flutter pins its dependencies to avoid getting any surprises - and includes some strict checksum checking to make sure depdencies aren't accidentally added or removed or changed.

I suspect running upgrade in flutter_gallery ends up pulling in packages more recent than the pinned versions over time.  We should probably just remove that line from the readme in Flutter gallery.

/cc @xster  @HansMuller what do you think?

**Comment by dnfield** [comment]
I've updated the readme for this to have the correct instructions.  Closing for now.  We may need to examine how flutter upgrade is working, but that's a separate issue.
