### ISSUE TITLE
Documentation for Writing our own IconData and AnimatedIconData for the SVG or Animated Vector Drawables

### ISSUE THREAD

**Issue by rashedmyt** [flutter/flutter#24290]
I have read the issues related to integrating svg support into flutter.. but I thought if the material icons are animated in the flutter somehow, I dug deep into code and found out that the values of the AnimatedIconData for those are written.. so I thought if the developers who did that can provide some kind of documentation to enable other app developers to write their own data and can move forward instead of waiting for the svg support, it would just be a great help

**Comment by zoechi** [comment]
I think this is covered by #1831 and #15501.
There is currently no official support for automatically generating IconData from SVG and therefore no docs.
