### ISSUE TITLE
InheritedWidget gets removed in Nested MaterialApp - Navigator fails

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#24302]
I'm nesting 3 MaterialApp objects in such hierarchy:

```
   m1
m2    m3
```

I'm using InheritedWidget for app state in m2 and m3.

If the depth 0 is '/' then when the Navigator depth is > 1 the state.of(context) throws:
cannot get property of null

m2 and m3 are separate flutter projects,
m2 on the lib/main.dart uses **absolute imports**
m3 on the lib/main.dart uses **relative imports**

haven't tested > 1 depth on m3

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
