### ISSUE TITLE
[FR] Flutter as a Game Engine (low-level GPU access, interactive textures)

### ISSUE THREAD

**Issue by VladimirCores** [flutter/flutter#24305]
Hello Flutter team! : )

I have a feature proposal. In one of the talks from Firebase Summit 2018 Prague, I have heard how of the Google Flutter team member said that "Flutter is like Unity for mobile apps". So I come up with an idea why not to use it as a game engine with special API for entity and systems rendering (like Ash from Richard Lord) or maybe similar to Unity? So it would be great to be able to use Flutter as a Game Engine.

Thanks,
Vladimir

**Comment by miyoyo** [comment]
You can already use dart:ui for direct drawing, and using flutter as a game engine is not the current objective of the team. Some plugins (Ex: Flame) already provide a few bases to make a game, but flutter's widget system really isn't the best for games.

**Comment by DQvsRA** [comment]
Games extensively use scrolling list, buttons, grids, text fields, popups and a lot of UIs which Flutter do very well. All we need to have a "canvas" (WebGL canvas) as one of the UI components like it is in HTML.

**Comment by miyoyo** [comment]
Well if you want canvas, you can either use custom painters, or render to texture w/ Android or iOS

**Comment by jonahwilliams** [comment]
This is available via the flutter gpu preview
