### ISSUE TITLE
Fix vertical alignment of LibTxt layout of non-alphabetic scripts.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#24317]
There are an assortment of bugs regarding the vertical positioning of scripts such as Chinese, Arabic, and Persian being too low compared to alphabetic letters.

We should ensure that we are properly positioning these glyphs, since improperly positioned glyphs can cause strange visuals, inconsistent line heights, and textboxes that vary in height.

**Comment by jossef** [comment]
Is there a recommended workaround in the meanwhile?

**Comment by tigrenok00** [comment]
Following, still happens (Hebrew)

**Comment by GaryQian** [comment]
Related: https://github.com/flutter/flutter/issues/42925

**Comment by GaryQian** [comment]
Example of this happening in hebrew: https://github.com/flutter/flutter/issues/27033

**Comment by jossef** [comment]
@GaryQian 
did you close because it is now fixed?
if so - does https://github.com/flutter/flutter/issues/27033 should be also closed?
