### ISSUE TITLE
Simplified Chinese characters with background do not display properly in RichText.

### ISSUE THREAD

**Issue by yumi0629** [flutter/flutter#24337]
I want to add a background to text, here is my code:
```dart
RichText(
                text: TextSpan(
                        text: "不科学1111",
                        style: TextStyle(
                          color: Colors.black,
                          background: new Paint()..color = Colors.pinkAccent,
                        ),
                    children: [
                          TextSpan(
                            text: "不科学sdfsdfkd",
                            style: TextStyle(
                              color: Colors.lightGreenAccent,
                              background: new Paint()
                                ..color = Colors.pinkAccent,
                            ),
                          ),
                        ]),
                  ),
```
But the Simplified Chinese words do not display:
![image](https://user-images.githubusercontent.com/17703630/48473171-eacb4900-e832-11e8-9395-ac66c99cb3e9.png)

If I set the background color with opacity, it seems well:
```dart
RichText(
                text: TextSpan(
                      text: "不科学1111",
                      style: TextStyle(
                        color: Colors.black,
                        background: new Paint()..color = Colors.pinkAccent.withOpacity(0.5),
                      ),
                    children: [
                        TextSpan(
                          text: "不科学sdfsdfkd",
                          style: TextStyle(
                            color: Colors.lightGreenAccent,
                            background: new Paint()
                              ..color = Colors.pinkAccent,
                            ),
                          ),
                        ]),
                  )
```
![image](https://user-images.githubusercontent.com/17703630/48473353-3a117980-e833-11e8-859b-c8700ce5474c.png)
But it still doesn't meet my expectation:
![image](https://user-images.githubusercontent.com/17703630/48473394-56adb180-e833-11e8-8b71-203ba7d7416c.png)

I have added app locales supports like this:
```dart
supportedLocales: [
            const Locale('zh', 'CH'),
            const Locale('en', 'US'),
          ],

```
Still doesn't work.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by yumi0629** [comment]
> Please add the output of `flutter doctor -v`.

[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.2 17C205, locale
    zh-Hans-CN)
    • Flutter version 0.11.3 at /Users/yumi/Library/Android/flutter
    • Framework revision 72bf075e8d (4 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/yumi/Library/Android/sdk
    • Android NDK at /Users/yumi/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/yumi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • M5 Note • 621QECQP4P2HM • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by GaryQian** [comment]
Could be related to https://github.com/flutter/flutter/issues/24234?

**Comment by yumi0629** [comment]
> Could be related to #24234?

Thanks a lot. It is true that using multiple language styles will cause this problem. But I can't understand why when I set the background color with opacity, the characters will be seen?

**Comment by ozexpert** [comment]
Is there any workaround for this?

**Comment by GaryQian** [comment]
So the real bug here seems to be that the background width covers the entire span instead of just the run it is corresponding to. This is causing the widths to "overdraw" onto neighboring runs.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/7287 This should fix the background overlapping with the text, causing it to become invisible behind it.

The strange translucency behavior requires a more in-depth metrics revision to properly draw them.

**Comment by Hixie** [comment]
I would expect the parent TextSpan to paint behind the child TextSpan (even if both have a background).

**Comment by Hixie** [comment]
(and I would expect the backgrounds to paint in pre-order depth-first)

**Comment by GaryQian** [comment]
Yes, this should happen now with the PR above, it was not the case before. For example, the current order is for two runs: run1bg, run1text, run2bg, run2text
With the change, it becomes: run1bg, run2bg, run1text, run2text

**Comment by zmtzawqlp** [comment]
@yumi0629 @ozexpert @jason-simmons @zoechi hi gays, there is a [workaround](https://github.com/fluttercandies/extended_text) for this issue , see does it help for you.
