### ISSUE TITLE
The assets folder is missing in flutter module project's aar file when I upgraded to version 0.11.3

### ISSUE THREAD

**Issue by koudle** [flutter/flutter#24338]
## Steps to Reproduce
In the flutter module project

1. run `git checkout v0.11.3` upgrade the flutter to version 0.11.3
2. run `flutter doctor`
3. run `./gradlew flutter:assembleDebug`  in the `.android` directory
4. the `flutter-debug.aar` archive file in `.android/Flutter/build/outputs/aar/.` missed the assets folder

## flutter doctor -v
```
[✓] Flutter (Channel unknown, v0.11.3, on Mac OS X 10.13.6 17G2208, locale zh-Hans-CN)
    • Flutter version 0.11.3 at /Users/kk/flutter
    • Framework revision 72bf075e8d (4 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)
```

**Comment by zoechi** [comment]
@Hixie

**Comment by koudle** [comment]
@Hixie 
Can you reproduce it?

**Comment by xuehu54321** [comment]
Use './gradlew assemDebug' instead of './gradlew flutter:assembleDebug' in the .android directory.

**Comment by koudle** [comment]
It works
