### ISSUE TITLE
[cloud_functions] - region support

### ISSUE THREAD

**Issue by Knupper** [flutter/flutter#24333]
Hello, 

i am using the current version of the cloud functions plugin to call a cloud function inside my backend. The cloud functions are hosted in europe-west1. when i now call the function 

```dart
CloudFunctions.instance.call(
        functionName: 'functionName',
        parameters: {'data': ''}).then((resp) {
        // Do some stuff
 }).catchError((error) {
      print(error.toString());
 });
```

i get an error with "NOT FOUND". 

After that i was testing it with the cloud functions shell

```
dev@cloudshell:~ (project)$ gcloud functions call "functionName" --data '{"data":""}'
```
output:
```
ERROR: (gcloud.functions.call) ResponseError: status=[404], code=[Not Found], message=[Function getSwipePictures in region us-central1 in project does not exist]
```

when i give the correct region as parameter `--region eurpe-west1` it works correctly.

My question is now, have i missed the parameter to configure the cloud functions plugin for a other region then `us-central1` or is this configuration not implemented yet?

Many thanks in advance for your help

Max

```
flutter doctor -v
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17763.55], locale de-DE)
    • Flutter version 0.11.3
    • Framework revision 72bf075e8d (4 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at 
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary 
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.29.0)
    • VS Code at Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • Pixel 2 • code• android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by rogiervandenberg** [comment]
> My question is now, have i missed the parameter to configure the cloud functions plugin for a other region then us-central1 or is this configuration not implemented yet?

Hey Max, did you already found out a way to call cloud functions in a different region than `us-central1`? It is weird that the regular documention writes about it, but that Flutter ("first class citizen", "1.0", etc.) has no obvious way of specifying the location of the function that is called.

**Comment by Knupper** [comment]
Hey Rogier,

i have not found a way to call cloud functions in different regions. At the moment i deploy the function to my region and then copy it to the us-central to test it. But i am happy that i am not the only person who has this issue 💯 

I am working currently at a pull request. For Android the region support works, but i have never programmed with objective c. When you have any experience, i am happy for every help :)

[Link to the repro](https://github.com/Knupper/plugins)

**Comment by dshukertjr** [comment]
No progress on this?

**Comment by kroikie** [comment]
@Knupper

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/577. Any further collaboration will be done there.
