### ISSUE TITLE
[Doc] [cookbook] reading-writing-files useless async keyword

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#24331]
In the url https://flutter.io/docs/cookbook/persistence/reading-writing-files, 

It has the function:

```dart
Future<File> _incrementCounter() async {
    setState(() {
      _counter++;
    });

    // write the variable as a string to the file
    return widget.storage.writeCounter(_counter);
  }
```

(1) Since there is no `await` here, why do we have `async` keyword? Removing the keyword doesn't harm anything. 
(2) Why do we return a File here? It's kinda useless. but whatever, not very important.

**Comment by zoechi** [comment]
It in step 3 https://flutter.io/docs/cookbook/persistence/reading-writing-files#3-write-data-to-the-file

**Comment by sgon00** [comment]
@zoechi sorry, I don't get what you mean. Step 3 is about `writeCounter` function, But I am talking about `_incrementCounter`. `async` is useless here. There is also no need to return anything.

**Comment by zoechi** [comment]
Uh! You're right - fixed.

**Comment by sgon00** [comment]
@zoechi thanks for the reply. Since you said "fixed", should I close this issue now? I don't see any updates in that url yet. Btw, should I open doc issue here? or in flutter/website? thanks.

**Comment by zoechi** [comment]
Sorry again, I just tried to make the issue more clear but I messed up quite a bit here :-/
I meant I fixed my comment.
Thanks for reporting the issue!

**Comment by sgon00** [comment]
@zoechi no worries. get it. cheers. :)

**Comment by zoechi** [comment]
this one

![image](https://user-images.githubusercontent.com/405837/49819876-bb96f180-fd76-11e8-8ade-1fd785e35412.png)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2013](https://github.com/flutter/website/issues/2013) via [**ZenHub**](https://www.zenhub.com/)
