### ISSUE TITLE
I can't see  'Flutter's mode' wiki

### ISSUE THREAD

**Issue by mugku** [flutter/flutter#24340]
Hi~ 

I see a compiling the flutter engine for ios.
3rd - For a discussion on the various flags and modes, see Flutter's mode.
(https://github.com/flutter/flutter/wiki/Compiling-the-engine)

click Flutter's mode link but can' see and do not have permission. 

Would you give me view permission for Flutter's mode??

Thank you Flutter Team!

**Comment by kangwang1988** [comment]
You don't need permission to visit [this wiki](https://github.com/flutter/flutter/wiki/Flutter%27s-modes)
<img width="1254" alt="screen shot 2018-11-14 at 6 13 33 pm" src="https://user-images.githubusercontent.com/817851/48476087-12251480-e839-11e8-9d3f-f5a829a39863.png">

**Comment by mugku** [comment]
Thank you @kangwang1988  👍
