### ISSUE TITLE
Pod install error

### ISSUE THREAD

**Issue by hongruqi** [flutter/flutter#24342]
## Steps to Reproduce

1. pod install 

## Podfile
```
flutter_application_path = 'path/development/my_flutter'
    
target 'DiSpecialDriverHK' do
...

end
```

## Logs

```
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `real_path' for nil:NilClass

/Users/didi/DiSpecialDriverHK/Podfile:89:in `block (5 levels) in from_ruby'
/Users/didi/DiSpecialDriverHK/Podfile:87:in `each'
/Users/didi/DiSpecialDriverHK/Podfile:87:in `block (4 levels) in from_ruby'
/Users/didi/DiSpecialDriverHK/Podfile:86:in `each'
/Users/didi/DiSpecialDriverHK/Podfile:86:in `block (3 levels) in from_ruby'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:619:in `run_podfile_post_install_hook'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:607:in `block in run_podfile_post_install_hooks'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:606:in `run_podfile_post_install_hooks'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:185:in `block in generate_pods_project'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/didi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/didi/.rvm/gems/ruby-2.5.1@global/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/didi/.rvm/gems/ruby-2.5.1/bin/pod:23:in `load'
/Users/didi/.rvm/gems/ruby-2.5.1/bin/pod:23:in `<main>'
/Users/didi/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/Users/didi/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
-->

```
```
<!-- If possible, paste the output of running `flutter doctor -v` here. -->

[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14 18A389, locale zh-Hans-CN)
    • Flutter version 0.11.3 at /Users/didi/development/flutter/flutter
    • Framework revision 72bf075e8d (4 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/didi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode9.4.1.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 2.0.0
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by kangwang1988** [comment]
Paste the whole podfile especially the post-install part so that we might understand it better. Besides, it seems to be an iOS problem instead of a Flutter one.

**Comment by hongruqi** [comment]
platform :ios, '9.0'

inhibit_all_warnings!

flutter_application_path = 'path/development/my_flutter'
    
target 'DiSpecialDriverHK' do
    eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end

if If I remove  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)，
run pod install ,it's ok!

**Comment by kangwang1988** [comment]
I think the problem results from this statement:
<img width="793" alt="screen shot 2018-11-14 at 9 43 24 pm" src="https://user-images.githubusercontent.com/817851/48486386-55da4700-e856-11e8-8a1d-4f80f117dbbd.png">
```
xcconfig_path = config.base_configuration_reference.real_path
```
This statement is trying to read the xcconfig for your target's config(debug/release), in Flutter, it refers to Debug/Release.xcconfig which contains Pods-Runner.debug/Release.xcconfig(well known xcconfig from Cocoapods) && Generated.xcconfig(including Flutter related environment).

<img width="1069" alt="screen shot 2018-11-14 at 9 47 22 pm" src="https://user-images.githubusercontent.com/817851/48486577-e44ec880-e856-11e8-990e-316c25bd9a0f.png">


i.e., you have to make sure that the project's configuration is set properly as below:
<img width="679" alt="screen shot 2018-11-14 at 9 47 13 pm" src="https://user-images.githubusercontent.com/817851/48486620-07797800-e857-11e8-8002-dd0a69e446dc.png">

**Comment by buckcao** [comment]
if you have many target ，what should I do ？
post_install must in one pisce

```
targetArray = ['Vite', 'Vite-test', 'Vite-enterprise']
flutter_application_path = '../vite_flutter'
#targetArray.each do |t|
    target 'Vite' do
        use_frameworks!
        eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

    end

**Comment by alexanderkorus** [comment]
buckcao +1

**Comment by mcplectrum** [comment]
The reason is that GoogleTagManager is missing its xcconfig file, which. It only has a `ResourceBundle-TagManagerResources-Info.plist` file in the `Pods/Target Support Files/GoogleTagManager` folder. This is why` config.base_configuration_reference.real_path == nil` and the error: `undefined method `real_path' for nil:NilClass`.

**Comment by lihui2333** [comment]
alexanderkorus + 1 i met the same problem,I define my own post_install hook.then errors occured.

**Comment by lihui2333** [comment]
any solutions here？

**Comment by kangwang1988** [comment]
Till now, I think the workaround for multiple post-install hook issue would be edit podhelper.rb and remove the post_install hook in it. But doing this will require you to diasable BITCODE manually and make sure that the flutter_tools generated Generated.xcconfig(where there is the basic info for flutter environment) is included in your target's buidconfigation file.

**Comment by isfang** [comment]
I have fix this issue by edit this file: .ios/Flutter/podhelper.rb

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if config && config.base_configuration_reference
                xcconfig_path = config.base_configuration_reference.real_path
                puts "file path is: #{xcconfig_path}"
                File.open(xcconfig_path, 'a+') do |file|
                    file.puts "#include \"#{File.realpath(File.join(framework_dir, 'Generated.xcconfig'))}\""
                end
            end
        end
    end
end

**Comment by isfang** [comment]
I have fix this issue by edit this file: .ios/Flutter/podhelper.rb
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if config && config.base_configuration_reference
                xcconfig_path = config.base_configuration_reference.real_path
                puts "file path is: #{xcconfig_path}"
                File.open(xcconfig_path, 'a+') do |file|
                    file.puts "#include \"#{File.realpath(File.join(framework_dir, 'Generated.xcconfig'))}\""
                end
            end
        end
    end
end
```

**Comment by dnfield** [comment]
I believe this is fixed on master now - if that's not the case please reopen

**Comment by pejalo** [comment]
@isfang Thanks, this seems to be working for me too. What are the implications of this fix?

**Comment by mustafal** [comment]
Hello all,
I have this error while I run `flutter build ios` command in my flutter project,

`Running "flutter pub get" in fsm_osi_flutter-master...              1.6s
Building com.serpentcs.fsmOsi for device (ios-release)...
Found saved certificate choice "iPhone Developer: Husen Daudi (M3DDDNJC32)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Husen Daudi (M3DDDNJC32)"
Running pod install...                                              0.9s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `google_maps_flutter` from `.symlinks/plugins/google_maps_flutter/ios`
    -> Fetching podspec for `keyboard_visibility` from `.symlinks/plugins/keyboard_visibility/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `simple_permissions` from `.symlinks/plugins/simple_permissions/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "simple_permissions":
      In Podfile:
        simple_permissions (from `.symlinks/plugins/simple_permissions/ios`)

    Specs satisfying the `simple_permissions (from `.symlinks/plugins/simple_permissions/ios`)` dependency were
    found, but they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in
    `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in
    unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in
    `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in
    `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in
    `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in
    `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in
    `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in
    `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in
    `section'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was
    specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install`


Please Help me out in this. Thanks in advance.

**Comment by feudadrien** [comment]
Open Terminal
Go to "Project > ios" 
run "pod update"

**Comment by chakri3130** [comment]
Open terminal 
Go to your iOS project folder and Type " Sudo Gem install cocoapods", Enter Password and press Enter.
Pods will install after successful authentication.
Type "Pod install". pods will install without any errors.

**Comment by pkmangukiya** [comment]
Maybe it could work : https://stackoverflow.com/a/63504980/10563627
