### ISSUE TITLE
No code signature found - Add Flutter to existing apps, iOS real device issue, Xcode Version 10.1 

### ISSUE THREAD

**Issue by jelenacarnegie** [flutter/flutter#24343]
After doing everything listed here:
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

I get:

![screen shot 2018-11-14 at 12 48 13 pm](https://user-images.githubusercontent.com/17471080/48480720-9cef1a80-e80b-11e8-8ce1-24ba4a35669e.png)

when trying to run app on any real device. 

**On simulator, it all works as expected.**

**On Android side, everything goes smoothly, also!**

## Steps to Reproduce

1. Create simple iOS project(Swift) in the same folder where the flutter module is
2. Initialize CocoaPods and change Podfile to

```
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
# use_frameworks!

flutter_application_path = '../flutter_comment_wall/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'hostiosapp' do

end
```
3. pod install
![screen shot 2018-11-14 at 1 13 26 pm](https://user-images.githubusercontent.com/17471080/48481823-1f2d0e00-e80f-11e8-8964-2be325821591.png)

4. add those 
```
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
```
to BuildPhases Run Script
5. Make simple button and onClick listener to open FlutterViewController
6. Build successful, after I set:
![screen shot 2018-11-14 at 1 05 51 pm](https://user-images.githubusercontent.com/17471080/48481497-0c660980-e80e-11e8-87e6-4d6900430449.png)
without this, i get a linking error.
```
ld: '/Users/jelenalecic/Library/Developer/Xcode/DerivedData/hostiosapp-ahpyodppdcdpvkbrkpickvrsdqea/Build/Products/Debug-iphoneos/FlutterPluginRegistrant/libFlutterPluginRegistrant.a(GeneratedPluginRegistrant.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/jelenalecic/Library/Developer/Xcode/DerivedData/hostiosapp-ahpyodppdcdpvkbrkpickvrsdqea/Build/Products/Debug-iphoneos/FlutterPluginRegistrant/libFlutterPluginRegistrant.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
7. App installation failed, No code signature found

Signing is set to automatically

![screen shot 2018-11-14 at 1 17 40 pm](https://user-images.githubusercontent.com/17471080/48482002-b5613400-e80f-11e8-88f7-246480bac1c6.png)

Device that I'm currently using is an iphone 8, iOS 12.1

flutter doctor:

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.11.3 at /Users/jelenalecic/projects/flutter
    • Framework revision 72bf075e8d (4 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jelenalecic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (3 available)
    • SM C7010            • d571e02b                                 • android-arm64 • Android 8.0.0 (API 26)
    • Jelena’s iPhone (2) • ac1e7e4b9bc055e0c4ff05c3bcbe64e189b6480e • ios           • iOS 12.1
    • iPhone 7            • 9DC8517E-E336-4BF8-A2C6-9A65DC0DB063     • ios           • iOS 12.1 (simulator)

• No issues found!

```

I believe it must be some binding issue with podhelper.rb, 'cos i have to  switch off manually Enable Bitcode, to be able to build the app.

I have tried everything I could think of. Please help :)
Thanks!

@dnfield

**Comment by kangwang1988** [comment]
@jelenacarnegie 
Yes, as Flutter.framework doesn't contain bitcode, you have to disable the bitcode setting for the target's buildsetting.

**Comment by kangwang1988** [comment]
Besides, when you specified a DEVELOPMENT_TEAM in your build_settings, flutter will respect it.
If you specified one, can you make sure that the code-signing works fine from Xcode using your personal team?

**Comment by jelenacarnegie** [comment]
@kangwang1988 
It works fine for other apps(without flutter module). 
I haven't done anything different than usual.

**Comment by dnfield** [comment]
The process should have automatically disabled bitcode for you, but probably doesn't handle some situations.

Can you take a look at your .xcconfig files and make sure you have a line that says ENABLE_BITCODE=NO in the relevant one(s) for this target.

Alternatively go through all your targets and make sure that Iis set.  Right now that seems like your primary issue.  If that is done and you're still having signing issues there may be another issue, but hopefully you get better output once bitcode is disabled for all targets.

**Comment by jelenacarnegie** [comment]
@dnfield 

I've disabled it in Xcode

![screen shot 2018-11-14 at 4 31 23 pm](https://user-images.githubusercontent.com/17471080/48492752-c1a6ba80-e82a-11e8-8b69-2d54add5c5c1.png)

and in Android Studio in files:
![screen shot 2018-11-14 at 4 32 07 pm](https://user-images.githubusercontent.com/17471080/48492794-d97e3e80-e82a-11e8-8906-8bb326cd78ea.png)

but still the same :/

**Comment by dnfield** [comment]
Can you tell me the values of the `$EXPANDED_CODE_SIGN_IDENTITY_NAME` and `$CODE_SIGN_IDENTITY` for the run script build phase that runs `xcode_backend.sh`?

**Comment by jelenacarnegie** [comment]
@dnfield 

I'm sorry, but I don't know how to get those values.

I see them there(...flutter/packages/flutter_tools/bin/xcode_backend.sh):
<img width="819" alt="screen shot 2018-11-14 at 8 31 19 pm" src="https://user-images.githubusercontent.com/17471080/48507468-4f46d200-e84c-11e8-9018-100338e4d42d.png">

...but I'm not sure how to debug this file, cos it's outside of my ios project.

I'm an android developer and I would probably need some help from my iOS colleagues :)

**Comment by dnfield** [comment]
![image](https://user-images.githubusercontent.com/8620741/48511919-f1df6080-e80c-11e8-8218-ff12cfd2417c.png)


If you click on the small icon at the end of the highlighted line, it should expand and show you all the environment variables it's setting.  My suspicion is that these aren't getting set and so we're not signing App.framework/Flutter.framework for you, resulting in this error.

**Comment by dnfield** [comment]
Argh.  I'm reproducing this locally.

Temporarily, if you comment out lines 370 and 373, it should work again.

**Comment by jelenacarnegie** [comment]
@dnfield 

yay! it's working!
thanks for the quick response/fix.

**Comment by Allan-Nava** [comment]
I have this error: 
```
=== BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Release ===
    ld: '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/Reachability/libReachability.a(Reachability.o)' does not contain bitcode. You must
    rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file
    '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/Reachability/libReachability.a' for architecture arm64
    clang: error: unable to execute command: Segmentation fault: 11
    clang: error: linker command failed due to signal (use -v to see invocation)
```

How can I fix it?
