### ISSUE TITLE
Flutter codelab link to a doc is broken

### ISSUE THREAD

**Issue by atn832** [flutter/flutter#24351]
https://codelabs.developers.google.com/codelabs/flutter/#6
has a link to the documentation for TickerProviderStateMixin, but it returns error 404:
https://docs.flutter.io/flutter/widgets/TickerProviderStateMixin-class.html

**Comment by dnfield** [comment]
The correct link is now https://codelabs.developers.google.com/codelabs/flutter/#6

@sfshaza2 - do you know where this content lives?

**Comment by dnfield** [comment]
For more context - we refactored several mixin-like abstract classes to use a new syntax in Dart.  Apparently this means the API doc links for all of those has changed.  Some more details are in the linked issue.

Also @atn832 - I originally pasted the wrong link above, I've corrected it.

Thanks for the report!

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2078](https://github.com/flutter/website/issues/2078) via [**ZenHub**](https://www.zenhub.com/)
