### ISSUE TITLE
Add support for loading different Icons for highlight/disabled states of IconButton

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#24355]
While IconButton offers highlightColor and disabled color sometimes we need to replace the whole icons and not just change the tint onPressed/Disabled. 

This is specifically for supporting a non-trivial color shift on the icon (e.g. sometimes a blue icon needs to remain blue while the border is tinted gray).

**Comment by DaveShuckerow** [comment]
@HansMuller This is from the Dream team.  Please reach out for more details on their requirements when there is bandwidth to solve this.

**Comment by mehmetf** [comment]
I like Hans' solution. We can close this.
