### ISSUE TITLE
Output for building Android projects should show build time durations like Xcode builds do

### ISSUE THREAD

**Issue by aaronfg** [flutter/flutter#24362]
Currently there is no build time duration logged out when you build for Android but there is for XCode:

**Current iOS output:**
```
Launching lib/main.dart on iPhone XR in debug mode...
Starting Xcode build...
Xcode build done.                                           13.4s
Syncing files to device iPhone XR...
```

**Current Android output:**
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
```

It would be helpful if both platform build messages were somewhat consistent (and it's also just helpful info on how long builds are taking).

My suggestion would be to place the duration in seconds after the `Built build/app/outputs/apk/debug/app-debug.apk.`  line

**Comment by blasten** [comment]
We do print the time now days. `Running Gradle task 'assembleDebug'... Done                         4.8s`
