### ISSUE TITLE
Google Sign in returns null id token

### ISSUE THREAD

**Issue by sherrychhabra** [flutter/flutter#24378]
i am implementing google sign in using firebase in flutter. Following is the method i am using for sign in:-

```dart
GoogleSignIn googleSignIn = GoogleSignIn();
  FirebaseAuth auth = FirebaseAuth.instance;

_testGoogleSignIn() async{
    try{
      GoogleSignInAccount account = await googleSignIn.signIn();
      print(account.email);

      GoogleSignInAuthentication authentication = await account.authentication;
      FirebaseUser user = await auth.signInWithGoogle(idToken: authentication.idToken , accessToken: authentication.accessToken);
      print(user.email);
    }catch(Exception){
      print(Exception.toString());
    }
  }

```

```dart
GoogleSignInAuthentication authentication = await account.authentication;
```

The above line returns two params one is access token and other is id Token. 
I am getting the value of access token but id token value is null because of which `FirebaseUser` is throwing following exception:

```
package:firebase_auth/firebase_auth.dart': Failed assertion: line 310 pos 12: 'idToken != null': is not true.
```

**Comment by zoechi** [comment]
Sounds like #22784 which is fixed. Are you using the latest version?

Please add the output of `flutter doctor -v`.

**Comment by sherrychhabra** [comment]
Yes I am using the latest version. Please note one thing here as i have mentioned earlier that I am getting the access token but id token is null. 

Following are the packages that I am using for google sign in:-

firebase_auth: ^0.6.2+1
google_sign_in: ^3.2.4
firebase_core: ^0.2.5+1

And the output of `flutter doctor -v` is :-

`
Apples-iMac:flutter_wb apple$ flutter doctor -v
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.9.4 at /Users/apple/Downloads/Softwares/flutter
    • Framework revision f37c235c32 (7 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK at /Users/apple/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
`

**Comment by sherrychhabra** [comment]
Adding more on this issue.


 In firebase console, 
If I am creating a new project and add one android app in that new project, then google sign in is working fine.

But If it is existing project which is already having one android app and i am adding a new android app in that existing project , then google sign in returns null id token .

**Comment by clicksuku** [comment]
Hi,
I faced the same problem. I realised that I had removed from google-services.json the  "Web OAuth Client ID" part. After adding it back, I started receiving the id token. Please check if you had done the same.

**Comment by cyanglaz** [comment]
@clicksuku Thank you for providing this solution! 

@sherrychhabra Could you try what @clicksuku mentioned and see if it resolves your issue?

**Comment by emilioschepis** [comment]
Hi, I have the same problem. My `google-services.json` file is downloaded from the Google Cloud Platform website. Is it possible to access the `idToken` without adding Firebase to my project? The login works just fine, but I only get the `accessToken` back.

**Comment by emrahcetiner** [comment]
I have the same problem. i want to access the idToken without adding Firebase. i don't need use Firebase. is it possible?

**Comment by emrahcetiner** [comment]
@emilioschepis i found a solution. it is possible without adding firebase plugin! google sign in works well and idToken is not null.

you must to add a new app to Firebase console then download google-services.json and just put to android/app folder.

**Comment by emilioschepis** [comment]
> @emilioschepis i found a solution. it is possible without adding firebase plugin! google sign in works well and idToken is not null.
> 
> you must to add a new app to Firebase console then download google-services.json and just put to android/app folder.

Hey @emrahcetiner , thank you! I'm sure that works and will surely be helpful to many people.
I have, however, found a different solution that has worked well for me and that does not require a Firebase project. 
I manually created a `strings.xml` in the Android project and added a custom string. 
For anyone who needs it, I explained it in more detail in #33261 .

**Comment by jmeinlschmidt** [comment]
In order to get `idToken` you must download new `google-service.json` and replace the old one right after you add the `SHA-1` hash to your Firebase Console. Otherwise, `idToken` will return `null`.

**Comment by kroikie** [comment]
@sherrychhabra

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1120. Any further collaboration will be done there.

**Comment by tharindu** [comment]
You can get around the exception with following code, where it checks specifically null value for google user. This happened when user cancels google account selection dialog for me.
```dart
      final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        // cancelled login
        print('Google Signin ERROR! googleUser: null!');
        return null;
      }
      final GoogleSignInAuthentication googleAuth = await googleUser
          .authentication;
     // continue google sign-in
```
