### ISSUE TITLE
sqflite issue on Android

### ISSUE THREAD

**Issue by RajesMca008** [flutter/flutter#24383]
sqflite column not reflecting when upgrading/change database version.
Even I tried to uninstall app and install again. Same code working fine with iOS build.

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the issue.
It's not even clear to me what "not reflecting" means. 

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
