### ISSUE TITLE
Method validate was called on null!

### ISSUE THREAD

**Issue by Abdullah1353** [flutter/flutter#24382]
<img width="960" alt="validate" src="https://user-images.githubusercontent.com/44639133/48543495-78667180-e8e3-11e8-8264-6fdb073b8a59.PNG">
<img width="960" alt="code1" src="https://user-images.githubusercontent.com/44639133/48543504-7d2b2580-e8e3-11e8-8818-70af798c96b2.PNG">
<img width="960" alt="codevsss1" src="https://user-images.githubusercontent.com/44639133/48543508-80261600-e8e3-11e8-876a-de01a7de4116.PNG">

setting map items to empty strings wont work either... I would appreciate some help

**Comment by Abdullah1353** [comment]
what is wrong with this method of declaration is used? and i am using form key in submitForm and in the on pressed of my submit button i am calling SubmitForm...this must have worked

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
