### ISSUE TITLE
Different Maps style support like snazzy maps

### ISSUE THREAD

**Issue by gibbsvjy007** [flutter/flutter#24380]
I would like to add different styling of Map instead of normal style in my app. 
like snazzy maps

**Comment by zoechi** [comment]
I don't know what "snazzy maps" means (the plugin maintainer probably will) but perhaps you could add a link to where it is documented/explained what that means.

**Comment by gibbsvjy007** [comment]
Snazzymap provides a different map styles in the form of json format.

Here is the link

https://snazzymaps.com

I want add one of those style.

**Comment by zoechi** [comment]
Is this really a valid Flutter request or should this be a Google Maps feature request?

**Comment by YAPPDEF** [comment]
We would need that as well. 
@zoechi request to the plugin google_maps_flutter

**Comment by iskakaushik** [comment]
Is this the same as https://github.com/flutter/flutter/issues/24147 ?

**Comment by J1GGZ** [comment]
Any support for snazzy maps or google map styles?

https://mapstyle.withgoogle.com


Curious to know if support is even an option? It's a JSON file. Thanks in advance. Love you long time.
