### ISSUE TITLE
Video player does not work on Samsung Devices

### ISSUE THREAD

**Issue by davidgalarza** [flutter/flutter#24391]
Hello, I'm using the video_player 0.7.2 package in my app, it works perfectly on my device and other that I tested, but some of my users report that use Samsung Devices a something strange.

On my device:

![whatsapp image 2018-11-15 at 10 04 53 am](https://user-images.githubusercontent.com/20847597/48561565-3971f500-e8be-11e8-9c5d-eeac0fed7f20.jpeg)

On samsung devices:
![whatsapp image 2018-11-15 at 12 43 07 am](https://user-images.githubusercontent.com/20847597/48561575-3e36a900-e8be-11e8-9b31-a3dd3e110c47.jpeg)

## Steps to Reproduce

1. Here is my code: https://github.com/davidgalarza/Sounter/blob/master/lib/screens/Sync/sync.dart

## Logs
Yesterday I was able to get a samsung device and I got this log

```
I/ExoPlayerImpl(14044): Init 8f34063 [ExoPlayerLib/2.8.0] [j7elte, SM-J700M, samsung, 23]
I/System.out(14044): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(14044): (HTTPLog)-Static: isSBSettingEnabled false
W/AudioCapabilities(14044): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(14044): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(14044): Unsupported mime audio/x-ms-wma
W/AudioCapabilities(14044): Unsupported mime audio/x-ima
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(14044): Unsupported mime video/wvc1
W/VideoCapabilities(14044): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(14044): Unsupported mime video/wvc1
W/VideoCapabilities(14044): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(14044): Unsupported mime video/x-ms-wmv7
W/VideoCapabilities(14044): Unsupported mime video/x-ms-wmv8
W/VideoCapabilities(14044): Unsupported mime video/mp43
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile/level 32768/2 for video/mp4v-es
I/VideoCapabilities(14044): Unsupported profile 4 for video/mp4v-es
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(14044): Unrecognized profile 2130706434 for video/avc
I/ACodec  (14044):  [] Now uninitialized
I/ACodec  (14044): [] onAllocateComponent
I/OMXClient(14044): Using client-side OMX mux.
I/ACodec  (14044): [OMX.Exynos.avc.dec] Now Loaded
I/MediaCodec(14044): [OMX.Exynos.avc.dec] setting surface generation to 14381057
I/ACodec  (14044): can't find wfdsink-exynos-enable
I/ACodec  (14044): codec does not support config priority (err -1010)
I/ACodec  (14044): [OMX.Exynos.avc.dec] Now Loaded->Idle
D/SurfaceUtils(14044): set up nativeWindow 0xd1409008 for 640x360, color 0x105, rotation 0, usage 0x2900
I/ACodec  (14044): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 7, minUndequeuedBuffers : 5
I/ACodec  (14044):  [] Now uninitialized
I/ACodec  (14044): [] onAllocateComponent
I/OMXClient(14044): Using client-side OMX mux.
I/ACodec  (14044): [OMX.SEC.aac.dec] Now Loaded
I/ACodec  (14044): [OMX.Exynos.avc.dec] Now Idle->Executing
I/ACodec  (14044): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (14044): >>>UHQA ACodec::configureCodec : 0, 15000000
I/ACodec  (14044): >>> getPortFormat 16, OMX.SEC.aac.dec
I/ACodec  (14044): [OMX.SEC.aac.dec] Now Loaded->Idle
I/ACodec  (14044): [OMX.SEC.aac.dec] Now Idle->Executing
I/ACodec  (14044): [OMX.Exynos.avc.dec] Now handling output port settings change
W/AHierarchicalStateMachine(14044): Warning message AMessage(what = 'omxI') = {
W/AHierarchicalStateMachine(14044):   int32_t type = 0
W/AHierarchicalStateMachine(14044):   int32_t event = 3
W/AHierarchicalStateMachine(14044):   int32_t data1 = 1
W/AHierarchicalStateMachine(14044):   int32_t data2 = 117440527
W/AHierarchicalStateMachine(14044): } unhandled in root state.
I/ACodec  (14044): [OMX.SEC.aac.dec] Now Executing
D/SurfaceUtils(14044): set up nativeWindow 0xd1409008 for 640x368, color 0x105, rotation 0, usage 0x2900
I/ACodec  (14044): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 13, minUndequeuedBuffers : 5
I/ACodec  (14044): >>> getPortFormat 16, OMX.SEC.aac.dec
I/ACodec  (14044): [OMX.Exynos.avc.dec] Now Executing
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ac04
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/libEGL  (14044): eglInitialize EGLDisplay = 0xdf53ace4
D/ViewRootImpl(14044): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(14044): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(14044): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(14044): ViewPostImeInputStage processPointer 1
```

flutter doctor -v

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.5 17F77, locale es-EC)
    • Flutter version 0.11.3 at /Users/davidgalarza/development/flutter
    • Framework revision 72bf075e8d (5 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/davidgalarza/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

```

**Comment by lishuhao** [comment]
Same as #24402

**Comment by ened** [comment]
On Android, "video_player" is implemented using the *ExoPlayer* component.
Version 0.7.2 of the plugin ships with ExoPlayer 2.8.0, which is not the latest version and may not include all bug fixes.

Please upgrade to the (not yet on published on pub) video_player plugin 0.8.0: https://github.com/flutter/plugins/tree/master/packages/video_player

=> You may need to adjust your android/build.gradle files to activate Java 1.8 source compatibility, please let me know how that works.

If the issue still reproduces with version 0.8.0, please try to reproduce it using the ExoPlayer project itself & research on their issue list as well.

@zoechi CC you as there may a few video_player related issues coming up in the following days. :-)

**Comment by tvolkert** [comment]
Fixed by https://skia.googlesource.com/skia/+/a6dddeaac902114677b21cb39f423db0f5557b10 (as soon as that rolls into Flutter)

**Comment by tvolkert** [comment]
@davidgalarza this should be fixed in the latest release (`v0.11.10`, available on the dev and beta channels).  Can you please run `flutter upgrade` and then verify to see if it's fixed for you?

**Comment by tvolkert** [comment]
Ok, second take... can you please try `v0.11.11` (on the latest `dev` and `beta` channels - available via `flutter upgrade`)?  Thanks!

**Comment by davidgalarza** [comment]
@tvolkert Yes, I confirm that it works perfectly in version 0.11.11 .

**Comment by tvolkert** [comment]
Great!  I'll close this now, but feel free to reopen if you see it still happening.

**Comment by jigarfumakiya** [comment]
Hello @tvolkert 

I am getting the same issue video doesn't play in Samsung device.
i am using   **video_player: ^0.10.1+3**


Here is Log I got 



I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Executing->Idle
I/ExoPlayerImpl(24114): Release e5dbcc4 [ExoPlayerLib/2.9.6] [k3g, SM-G900H, samsung, 23] [goog.exo.core]
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(24114): [SurfaceTexture-0-24114-1] cancelBuffer: BufferQueue has been abandoned
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Idle->Loaded
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Loaded
I/ACodec  (24114):  [OMX.Exynos.avc.dec] Now kWhatShutdownCompleted event : 6948
I/MediaCodec(24114): Codec shutdown complete
I/ACodec  (24114):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (24114):  [] Now kWhatShutdownCompleted event : 6948
I/MediaCodec(24114): Codec shutdown complete
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Executing->Idle
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Idle->Loaded
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Loaded
I/ACodec  (24114):  [OMX.SEC.aac.dec] Now kWhatShutdownCompleted event : 6948
I/MediaCodec(24114): Codec shutdown complete
I/ACodec  (24114):  [OMX.SEC.aac.dec] Now uninitialized
I/ACodec  (24114):  [] Now kWhatShutdownCompleted event : 6948
I/MediaCodec(24114): Codec shutdown complete
I/ExoPlayerImpl(24114): Init 24a6643 [ExoPlayerLib/2.9.6] [k3g, SM-G900H, samsung, 23]
I/ACodec  (24114):  [] Now uninitialized
I/OMXClient(24114): Using client-side OMX mux.
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Loaded
I/MediaCodec(24114): [OMX.Exynos.avc.dec] setting surface generation to 24692739
I/ACodec  (24114): can't find wfdsink-exynos-enable
I/ACodec  (24114): codec does not support config priority (err -1010)
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Loaded->Idle
D/SurfaceUtils(24114): set up nativeWindow 0x8076d008 for 1920x1080, color 0x105, rotation 90, usage 0x2900
I/ACodec  (24114): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 7, minUndequeuedBuffers : 5
I/ACodec  (24114):  [] Now uninitialized
I/OMXClient(24114): Using client-side OMX mux.
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Loaded
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Idle->Executing
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Executing
I/ACodec  (24114): >>>UHQA ACodec::configureCodec : 0, 15000000
I/ACodec  (24114): codec does not support config operating rate (err -1010)
I/ACodec  (24114): >>> getPortFormat 16, OMX.SEC.aac.dec
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Loaded->Idle
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now handling output port settings change
W/AHierarchicalStateMachine(24114): Warning message AMessage(what = 'omxI') = {
W/AHierarchicalStateMachine(24114):   int32_t type = 0
W/AHierarchicalStateMachine(24114):   int32_t event = 3
W/AHierarchicalStateMachine(24114):   int32_t data1 = 1
W/AHierarchicalStateMachine(24114):   int32_t data2 = 117440527
W/AHierarchicalStateMachine(24114): } unhandled in root state.
D/SurfaceUtils(24114): set up nativeWindow 0x8076d008 for 1920x1088, color 0x105, rotation 90, usage 0x2900
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Idle->Executing
I/ACodec  (24114): [OMX.SEC.aac.dec] Now Executing
I/ACodec  (24114): [OMX.Exynos.avc.dec] configureOutputBuffersFromNativeWindow setBufferCount : 16, minUndequeuedBuffers : 5
I/ACodec  (24114): >>> getPortFormat 16, OMX.SEC.aac.dec
I/ACodec  (24114): [OMX.Exynos.avc.dec] Now Executing
I/flutter (24114): video is clicked 
D/SensorManager(24114): unregisterListener ::   
V/ActivityThread(24114): updateVisibility : ActivityRecord{f521876 token=android.os.BinderProxy@37f2849 {com.mobilefirst.myyoda/com.mobilefirst.myyoda.MainActivity}} show : true
W/ResourcesManager(24114): getTopLevelResources: /data/app/com.mobilefirst.myyoda-2/base.apk / 1.0 running in com.mobilefirst.myyoda rsrc of package null
W/ResourcesManager(24114): getTopLevelResources: /data/app/com.mobilefirst.myyoda-2/base.apk / 1.0 running in com.mobilefirst.myyoda rsrc of package null
D/SensorManager(24114): registerListener :: 0, MPU6500 Acceleration Sensor, 200000, 0,  
I/Timeline(24114): Timeline: Activity_idle id: android.os.BinderProxy@37f2849 time:61884310
D/ViewRootImpl(24114): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(24114): ViewPostImeInputStage processPointer 1



Here is device Info SS
![Screenshot_2019-07-10-10-34-00](https://user-images.githubusercontent.com/11865669/60942024-b72bba80-a2fe-11e9-81b5-9d67391379ac.png)


thanks
