### ISSUE TITLE
big_red_button.py should run the same tests as travis

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#244]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Oct 29, 2015 at 23:42 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1880_

----

Somehow we should verify that the release we're about to make will be analyzer-clean and pass the tests. This is complicated by the fact that during the release your tree is in a state where 'pub' won't be happy, of course.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Friday Oct 30, 2015 at 16:41 GMT_

----

I discussed this with @sethladd .  One idea is to be able to push a "beta" or "dev" version of the packages to pub that won't be visible to the public.  Then we could test them from pub and once they pass the test, we could flip the bit on the server and make them the production versions of the package.

**Comment by abarth** [comment]
We now release using git hashes.  We should check Travis before publishing a given git hash.
