### ISSUE TITLE
Allow more button options to the text selection toolbar

### ISSUE THREAD

**Issue by jslavitz** [flutter/flutter#24407]
Flutter's Cupertino:
Empty Selection: Paste, Select All
Filled Selection: Cut, Copy Paste 

Native iOS Apps:
Empty Selection: Select, Select All, Paste, Insert Photo
Filled Selection: Cut, Copy, Paste, Replace, Arrow, bold/italicized/underlined, Look Up, Share, Arrow, Strikethrough, Insert Photo.

**Comment by zoechi** [comment]
Looks related to #22674

**Comment by deandreamatias** [comment]
This is the same problem that issue #25632 ?
