### ISSUE TITLE
Ability to use custom/non-Ahem/CJK fonts in flutter_tester

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#24405]
Currently, Flutter tester seems to lack the ability to use custom fonts.

There are many situations where varied fonts are required (such as to test how flutter handles different types of glyphs in different combinations) that the uniform-ness of Ahem makes impossible or very difficult to test.

**Comment by zoechi** [comment]
#17700 looks related

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/17910#issuecomment-431884965

**Comment by jonahwilliams** [comment]
Though the functionality isn't documented well, flutter_tester can use the font loader API. Is that sufficient for this issue ?
