### ISSUE TITLE
Trivial SlideTransition does not animate

### ISSUE THREAD

**Issue by patientplatypus** [flutter/flutter#24408]
I have a boilerplate trivial example of a slideTransition and it doesn't appear to animate at all. It waits for the animation timer on the controller to time out, and then the component appears, but with no animation. It seems about as simple as it is possible to make a slideTransition, and I can't see what is wrong. Documentation on slideTransition is so-so, and I can't see either where I am going wrong or an example that works. I've made a stackoverflow question which can be viewed here: https://stackoverflow.com/questions/53328534/flutter-slidetransition-is-not-animating. Here is the code: 

```dart
class DeleteCheck extends StatefulWidget{

  final offsetBool;
  final double widthSlide;

  DeleteCheck({
    Key key, 
    this.offsetBool, 
    this.widthSlide
  }): super(key: key);

  @override 
  State<StatefulWidget> createState() {
    return new _MyDeleteCheck();
  }
}

class _MyDeleteCheck extends State<DeleteCheck> with TickerProviderStateMixin {
  AnimationController _controller;
  Animation<Offset> _offsetFloat; 

  @override
  void initState() {
    super.initState();

    _controller = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 1),
    );

    _offsetFloat = Tween<Offset>(begin: Offset(widget.widthSlide, 0.0), end: Offset.zero)
        .animate(_controller);

    _offsetFloat.addListener((){
      setState((){});
    });

    _controller.forward();

  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    double height100 = MediaQuery.of(context).size.height;
    double width100 = MediaQuery.of(context).size.width;
    return new SlideTransition(
      position: _offsetFloat,
      child: Container(
        color: Colors.cyan,
        width: 0.525*width100-3.0,
        child: Text("hello there sailor")
      )
    );
  }
}
```

As you can see this appears to be fairly standard. Why is this breaking?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Can you please make the example a self-containing runnable reproduction (including `main() {}`) in a single file `lib/main.dart`.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
