### ISSUE TITLE
Directories in bin/cache should have world read and executable bits set

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#24413]
Customer "amplify" reports trying to use a Flutter installation where it was installed as the root user, but they're running it as a non-root user.  When doing this, there are many problems caused by the fact that many directories in `bin/cache` are only readable or executable by the owning user.

e.g. they can't run the `dart` executable:

```
$ ll bin/cache/dart-sdk/
total 40
drwxr-xr-x  10 tvolkert  eng   320 Nov 11 22:42 .
drwxr-xr-x  16 tvolkert  eng   512 Nov 12 09:54 ..
-rw-r--r--   1 tvolkert  eng  2500 Nov  8 23:47 LICENSE
-rw-r--r--   1 tvolkert  eng   936 Nov  8 23:47 README
drwx------   8 tvolkert  eng   256 Nov  9 12:25 bin
-rw-r--r--   1 tvolkert  eng    47 Nov  8 23:47 dartdoc_options.yaml
drwxr-xr-x   5 tvolkert  eng   160 Nov  8 23:52 include
drwxr-xr-x  31 tvolkert  eng   992 Nov  8 23:52 lib
-rw-r--r--   1 tvolkert  eng    41 Nov  8 23:52 revision
-rw-r--r--   1 tvolkert  eng    14 Nov  8 23:52 version
```

We should consider making sure that all `bin/cache` directories are usable by all users (pending a more thorough analysis of any possible security issues there).

Moreover, however, `bin/cache` is populated on demand by the user running the `flutter` tool, so to facilitate this use case, users would need to make sure that they run `flutter precache` as the owning user to make the tool usable by other users.

**Comment by zanderso** [comment]
There is some prior art in `flutter_tools` that shells out to `chmod` to set the execute bit. See: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/os.dart#L82. But it looks like among the `bin/cache` files, `makeExecutable()` is only called on `flutter_tester`: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L560.

**Comment by tvolkert** [comment]
Yeah, I ran with that prior art in https://github.com/flutter/flutter/pull/24669

**Comment by dannyvalente** [comment]
Using the latest dev channel package, flutter_macos_v1.1.0-dev, there are still some issues remaining with this.
The first problem is that the "bin/cache/" directory itself does not have world write permissions.
drwxr-xr-x@ 16 root  root   512 Dec 11 16:30 cache

Once that has world write permissions, the following issues arise, one at a time after resolving each individually:

FileSystemException: FileSystemException: Cannot open file, path = '/path_to_flutter/bin/cache/lockfile' (OS Error: Permission denied, errno = 13)

FileSystemException: FileSystemException: Cannot open file, path = '/path_to_flutter/version' (OS Error: Permission denied, errno = 13)

FileSystemException: FileSystemException: Cannot open file, path = '/path_to_flutter/bin/cache/flutter_version_check.stamp' (OS Error: Permission denied, errno = 13)


Once those are all resolved, I then get:

Creation of temporary directory failed, path = '/path_to_flutter/.pub-cache/_temp/dir' (OS Error: Permission denied, errno = 13)
 
pub get failed (66)

Once that one is resolved, I get:

Could not find a file named "pubspec.yaml" in "/path_to_flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.7.2".
 
pub get failed (66)

listing out that directory, it shows
985aeb8ceee6:wizard_module danny.valente$ sudo ls -la ~/Downloads/flutter_2/.pub-cache/hosted/pub.dartlang.org/
total 0
drwxr-xr-x@ 84 root  admin  2688 Dec 11 16:30 .
drwxr-xr-x@  3 root  admin    96 Dec 11 16:27 ..
drwx------@ 14 root  admin   448 Dec 11 16:27 analyzer-0.33.3
drwx------@ 13 root  admin   416 Dec 11 16:27 archive-2.0.4
drwx------@ 14 root  admin   448 Dec 11 16:27 args-1.5.1
drwx------@ 15 root  admin   480 Dec 11 16:27 async-2.0.8
drwx------@ 13 root  admin   416 Dec 11 16:27 boolean_selector-1.0.4
drwx------@ 14 root  admin   448 Dec 11 16:27 charcode-1.1.2
drwx------@ 16 root  admin   512 Dec 11 16:27 cli_util-0.1.3+2
drwx------@ 17 root  admin   544 Dec 11 16:27 collection-1.14.11
drwx------@ 13 root  admin   416 Dec 11 16:27 completion-0.2.1+1
drwx------@ 12 root  admin   384 Dec 11 16:30 connectivity-0.3.2
drwx------@ 14 root  admin   448 Dec 11 16:27 convert-2.0.2
drwx------@ 16 root  admin   512 Dec 11 16:27 coverage-0.12.3
drwx------@ 15 root  admin   480 Dec 11 16:27 crypto-2.0.6
drwx------@ 14 root  admin   448 Dec 11 16:27 csslib-0.14.6
drwx------@ 10 root  admin   320 Dec 11 16:30 cupertino_icons-0.1.2
drwx------@ 13 root  admin   416 Dec 11 16:27 dart2_constant-1.0.2+dart2
drwx------@ 19 root  admin   608 Dec 11 16:28 dart_style-1.2.0
drwx------@ 12 root  admin   384 Dec 11 16:30 device_info-0.2.1
drwx------@ 10 root  admin   320 Dec 11 16:27 file-5.0.6
drwx------@  7 root  admin   224 Dec 11 16:27 file_testing-2.0.3
drwx------@  6 root  admin   192 Dec 11 16:28 flutter_gallery_assets-0.1.6
drwx------@ 15 root  admin   480 Dec 11 16:27 front_end-0.1.6+3
drwx------@ 12 root  admin   384 Dec 11 16:27 glob-1.1.7
drwx------@ 12 root  admin   384 Dec 11 16:27 html-0.13.3+3
drwx------@ 11 root  admin   352 Dec 11 16:27 http-0.12.0
drwx------@ 13 root  admin   416 Dec 11 16:27 http_multi_server-2.0.5
drwx------@ 12 root  admin   384 Dec 11 16:27 http_parser-3.1.3
drwx------@ 14 root  admin   448 Dec 11 16:29 image-2.0.4
drwx------@ 15 root  admin   480 Dec 11 16:27 intl-0.15.7
drwx------@ 15 root  admin   480 Dec 11 16:28 intl_translation-0.17.2
drwx------@ 13 root  admin   416 Dec 11 16:27 io-0.3.3
drwx------@ 16 root  admin   512 Dec 11 16:28 isolate-2.0.2
drwx------@ 10 root  admin   320 Dec 11 16:27 js-0.6.1+1
drwx------@ 12 root  admin   384 Dec 11 16:27 json_rpc_2-2.0.9
drwx------@ 18 root  admin   576 Dec 11 16:27 json_schema-1.0.10
drwx------@ 16 root  admin   512 Dec 11 16:27 kernel-0.3.6+3
drwx------@ 19 root  admin   608 Dec 11 16:27 linter-0.1.72
drwx------@ 14 root  admin   448 Dec 11 16:27 logging-0.11.3+2
drwx------@ 13 root  admin   416 Dec 11 16:27 matcher-0.12.3+1
drwx------@  8 root  admin   256 Dec 11 16:27 meta-1.1.6
drwx------@ 15 root  admin   480 Dec 11 16:27 mime-0.9.6+2
drwx------@ 15 root  admin   480 Dec 11 16:27 mockito-4.0.0
drwx------@ 10 root  admin   320 Dec 11 16:27 multi_server_socket-1.0.2
drwx------@ 12 root  admin   384 Dec 11 16:27 mustache-1.0.2
drwx------@ 10 root  admin   320 Dec 11 16:27 node_preamble-1.4.4
drwx------@ 13 root  admin   416 Dec 11 16:27 package_config-1.0.5
drwx------@ 15 root  admin   480 Dec 11 16:27 package_resolver-1.0.6
drwx------@ 13 root  admin   416 Dec 11 16:27 path-1.6.2
drwx------@ 11 root  admin   352 Dec 11 16:29 path_provider-0.4.1
drwx------@ 10 root  admin   320 Dec 11 16:27 petitparser-2.0.2
drwx------@ 14 root  admin   448 Dec 11 16:27 platform-2.2.0
drwx------@ 11 root  admin   352 Dec 11 16:27 plugin-0.2.0+3
drwx------@ 12 root  admin   384 Dec 11 16:27 pool-1.3.6
drwx------@ 14 root  admin   448 Dec 11 16:27 process-3.0.9
drwx------@ 12 root  admin   384 Dec 11 16:27 pub_semver-1.4.2
drwx------@ 17 root  admin   544 Dec 11 16:27 quiver-2.0.1
drwx------@ 14 root  admin   448 Dec 11 16:27 shelf-0.7.3+3
drwx------@ 15 root  admin   480 Dec 11 16:27 shelf_packages_handler-1.0.4
drwx------@ 14 root  admin   448 Dec 11 16:27 shelf_static-0.2.8
drwx------@ 12 root  admin   384 Dec 11 16:27 shelf_web_socket-0.2.2+4
drwx------@ 14 root  admin   448 Dec 11 16:27 source_map_stack_trace-1.1.5
drwx------@ 13 root  admin   416 Dec 11 16:27 source_maps-0.10.8
drwx------@ 12 root  admin   384 Dec 11 16:27 source_span-1.4.1
drwx------@ 12 root  admin   384 Dec 11 16:27 stack_trace-1.9.3
drwx------@ 15 root  admin   480 Dec 11 16:27 stream_channel-1.6.8
drwx------@ 12 root  admin   384 Dec 11 16:27 string_scanner-1.0.4
drwx------@ 14 root  admin   448 Dec 11 16:27 term_glyph-1.0.1
drwx------@ 16 root  admin   512 Dec 11 16:27 test-1.5.1
drwx------@ 11 root  admin   352 Dec 11 16:27 test_api-0.2.1
drwx------@  8 root  admin   256 Dec 11 16:27 test_core-0.2.0
drwx------@ 14 root  admin   448 Dec 11 16:27 typed_data-1.1.6
drwx------@ 11 root  admin   352 Dec 11 16:30 url_launcher-4.0.1
drwx------@ 15 root  admin   480 Dec 11 16:27 usage-3.4.1
drwx------@ 14 root  admin   448 Dec 11 16:27 utf-0.9.0+5
drwx------@ 16 root  admin   512 Dec 11 16:28 vector_math-2.0.8
drwx------@ 14 root  admin   448 Dec 11 16:30 video_player-0.7.2
drwx------@ 15 root  admin   480 Dec 11 16:27 vm_service_client-0.2.6
drwx------@ 13 root  admin   416 Dec 11 16:27 vm_service_lib-0.3.10
drwx------@ 14 root  admin   448 Dec 11 16:27 watcher-0.9.7+10
drwx------@ 14 root  admin   448 Dec 11 16:27 web_socket_channel-1.0.9
drwx------@ 13 root  admin   416 Dec 11 16:27 xml-3.2.3
drwx------@ 14 root  admin   448 Dec 11 16:27 yaml-2.1.15

After fixing all those permissions, a flutter build succeeded, however I don't know if there might be even other issues with permissions.

Thanks

**Comment by tvolkert** [comment]
#24669 was reverted, so re-opening this.

**Comment by dannyvalente** [comment]
I saw that a fix was potentially merged into the master channel, so I just pulled that down to verify and I still see the same problems.
The issue is that the bin/cache directory doesn't have write permissions among other directories as well, which I listed in my comment above.

Thanks.

**Comment by tvolkert** [comment]
@dannyvalente #28090 isn't merged yet.

**Comment by dannyvalente** [comment]
Ah, I didn't notice that @tvolkert . I saw that #26315 was merged, but I didn't realize there was another issue open too.
Thanks!

**Comment by tvolkert** [comment]
Re-application landed in https://github.com/flutter/flutter/pull/28090 - this should be fixed on master now.
