### ISSUE TITLE
about Flutter/flutter.h not found on ios

### ISSUE THREAD

**Issue by yxfmlbb** [flutter/flutter#24428]
/Users/yxfmlbb/.pub-cache/hosted/pub.flutter-io.cn/share-0.5.3/ios/Classes/SharePlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/yxfmlbb/.pub-cache/hosted/pub.flutter-io.cn/flutter_webview_plugin-0.3.0+2/ios/Classes/FlutterWebviewPlugin.m:1:
    /Users/yxfmlbb/.pub-cache/hosted/pub.flutter-io.cn/flutter_webview_plugin-0.3.0+2/ios/Classes/FlutterWebviewPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not
    found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

### I find that this problem may be the cause
Flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Headers
### If the contents are shortcuts instead of files, flutter.h not found appears

![1](https://user-images.githubusercontent.com/11440908/48606063-871f5800-e9b9-11e8-8ce3-35fd6d4a4d75.jpg)

### I tried to unzip Flutter. Framework. Zip and replace the Flutter. Framework, Then it worked??
![2](https://user-images.githubusercontent.com/11440908/48606295-43791e00-e9ba-11e8-8e08-94051db96a8c.jpg)
![3](https://user-images.githubusercontent.com/11440908/48606309-4a079580-e9ba-11e8-8d41-504b5fce9045.jpg)
![4](https://user-images.githubusercontent.com/11440908/48606502-b2ef0d80-e9ba-11e8-8c3f-99f87c23ee40.jpg)

### However, when I used android Studio again, it was the same
![5](https://user-images.githubusercontent.com/11440908/48607960-e2067e80-e9bc-11e8-9142-e7f575fbced0.png)

### And, when I try the terminal ‘flutter run ios’,The problem comes up again
Flutter/bin/cache/artifacts/engine/ios/Flutter. The framework/Headers
### The files inside also become shortcuts
![6](https://user-images.githubusercontent.com/11440908/48608636-bb951300-e9bd-11e8-97c1-46d250884548.png)

**Comment by zoechi** [comment]
See also #16036, #16049
Merging with #16036

**Comment by Pergius** [comment]
THANK YOU yxmflbb!! I've been pulling my hair out for this the last 2 days! your hotfix atleast got my flutter to work again to run the app in a simulator again!.. many thanx! This issue must be fixed.. I've tried everything up until this strange way.. but it worked.

**Comment by rgbinnovation** [comment]
This happens over and over. Is there any fix planned for this issue?

**Comment by MiYogurt** [comment]
cool!  🐂🍺，兄嘚。

**Comment by corymalcolmtaylor** [comment]
I am getting this error now too but the posted solution does no work for me.

Launching lib/main.dart on iPhone Xʀ in debug mode...
Xcode build done.                                            7.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from /Users/me/dev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.3+1/ios/Classes/SharedPreferencesPlugin.m:5:
    /Users/me/dev/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.3+1/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
Exited (sigterm)
