### ISSUE TITLE
FlutterViewController should not show the Launch storyboard in add2app scenarios

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#24420]
Even with https://github.com/flutter/engine/pull/6834, the following code will result in a flash of the launch storyboard. 

```objc
  FlutterViewController* flutterViewController =
      [[FullScreenViewController alloc] init];
  flutterViewController.splashScreenView = nil;
  [self.navigationController pushViewController:flutterViewController
                                       animated:NO];
```

 Pre-warming the engine makes it marginally better but not much, e.g.:

```objc
  // marginally better, but still flashes
  FlutterViewController* flutterViewController =
      [[FlutterViewController alloc] initWithEngine:[self engine]
                                            nibName:nil
                                             bundle:nil];
  flutterViewController.splashScreenView = nil;
  [self.navigationController pushViewController:flutterViewController
                                       animated:YES];
```

still flashes the launch screen.

/cc @jamesderlin

**Comment by xster** [comment]
Can't we derive the intent from the way it's initialized rather than having the user call 2 things? We should also make sure the Android API is consistent.

**Comment by dnfield** [comment]
I'm trying to re-test this right now - I'm pretty sure I had tested it with a regular flutter app and everything worked fine.  Verifying.
