### ISSUE TITLE
Hotreload is too slow with Channel dev, v0.11.6, on Mac OS X 10.14.1

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#24425]
Hot reload too slow

Hotreload is too slow. First run is okay, second run take ages. Using hot reload over a 8 months now.It doesn’t change the even widget text style as quick as before.

**Using macOS Mojave 16 GB memory with 512 SSD.
Here is a flutter doctor -v output**

```
Niyazi-MBP:cep niyazitoros$ flutter doctor -v
[✓] Flutter (Channel dev, v0.11.6, on Mac OS X 10.14.1 18B75, locale tr-CY)
    • Flutter version 0.11.6 at /users/niyazitoros/flutter
    • Framework revision d44aa57c12 (2 days ago), 2018-11-14 11:09:56 -0800
    • Engine revision 114d33d3ca
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK at /Users/niyazitoros/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by lifenautjoe** [comment]
For me, hot reload works a few time and then completely freezes.

**Comment by zoechi** [comment]
@NTMS2017 

> doesn’t change the even widget text style as quick as before.

What is "as before" referring to?

**Comment by NTMS2017** [comment]
"as before" the hot reload response very quickly, ex; If I try to change something in the widget and save same time I can see that hor reload response my action and see the changes.

When I make changes I can see the my intellij run editor shows 3 line information for hot reload. Now, It takes few second to start run, if I do make changes and save it the hot reload keeps waiting in second line. First few save changes response "seems" okay but after few changes I need to wait even more than 5 sec so I have to keep start run again.  I will try to post the run command editor and explain in details

**Comment by dnfield** [comment]
A patch was added a few days ago that may fix this - we had some synchronization issues around hot reload that have been fixed up.

Can you try again on the latest master or dev channel?

**Comment by NTMS2017** [comment]
Test it now;
- Performing hot reload...
- Syncing files to device Android SDK built x86...
- Reloaded 28 of 929 libraries in 5.453ms

**Comment by lifenautjoe** [comment]
I've tried on dev channel and works like a charm. 

Thanks flutter team!

**Comment by zoechi** [comment]
@NTMS2017 what about you? Does it work for you as well now?

**Comment by NTMS2017** [comment]
yes, I am on dev channel and its working now
