### ISSUE TITLE
ios crash

### ISSUE THREAD

**Issue by xanhf** [flutter/flutter#24430]
Hello, could you please take a look at this problem?

Use the select image, but open the ios page more than three times and it will crash without error message.

**Comment by salihgueler** [comment]
First of all, I would suggest you use stackoverflow.com for your problems first. And you should definitely share your code, the package or plugin you are using and last but not least please share your `flutter doctor` output.
Secondly when you create an issue please provide the wanted information from you on the new issue page.

**Comment by zoechi** [comment]
@salihgueler is right.
There is no way to diagnose the problem with the provided information.

**Comment by xanhf** [comment]
> 
> 
> @salihgueler is right.
> There is no way to diagnose the problem with the provided information.

Sorry, I was a little busy these days, but I did not reply to the email. Now it has been repaired.

I used image_picker to select the image to open more than three times and it crashed. The updated version of flutter will be fine.

Thank you very much for your reply. Next time I ask a question, try to describe it clearly. Thank you very much

**Comment by ldemyanenko** [comment]
Looks like this issue https://github.com/flutter/flutter/issues/24379
@xanhf how did you managed to fix this? what version of flutter did you use?
