### ISSUE TITLE
Non-visual crash ClassNotFoundException

### ISSUE THREAD

**Issue by KammererTob** [flutter/flutter#24435]
While looking through the ANRs & crashes in the Play Store vitals i noticed some crash reports in the most recent versions of my app (i would say around the update to 0.10.x or 0.11.x). Those crashes do not seem to affect the app itself since there is no visual indication of a crash: I released a new version and started it right away on my own phone. I did not notice any crash or closure of my app, but the report still popped up some minutes later.

I don't think this is a severe problem, but i wanted to bring it to your attention since it might be related to some other functionality.

## Steps to Reproduce

1. Install App from Play Store with newest flutter version
2. Check crash reports in Play Store

## Logs
This is the log given to me by the Play Store:
```
java.lang.NoClassDefFoundError: 
  at com.google.android.gms.internal.zzccn.<init> (Unknown Source:3)
  at com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver.onReceive (Unknown Source:6)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3507)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:207)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1759)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6863)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:537)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:169)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
```

```
$ flutter doctor -v
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.407], locale de-DE)
    • Flutter version 0.11.3 at C:\SDKs\flutter
    • Framework revision 72bf075e8d (6 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\SDKs\android
    • Java binary at: D:\Programme\JDK\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\puelo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by KammererTob** [comment]
Just want to point out that this does seem to be a visual crash on older devices/android versions.
This happens the first time you start the app after installing it from the app store. After that it runs fine. Does not happen on iOS and also does not happen when starting from an IDE (either emulator or real device), even with "--release".

**Comment by zoechi** [comment]
Looks similar to #23545

**Comment by KammererTob** [comment]
I already have the settings as suggested in this post, but the problem still persists. It also seems to be related to the download from the Play Store because i cannot reproduce this error when i start the app with "flutter run", or install the .apk directly.

**Comment by KammererTob** [comment]
I have analyzed old (affected) .apks and my current release build (after doing the steps mentioned below) and noticed that one reference changed which might be the culprit..

Old APK: 
```
com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver void onReceive(android.content.Context,android.content.Intent)
com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver com.google.android.gms.internal.zzccn zziks
```

New APK: 
```
com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver void onReceive(android.content.Context,android.content.Intent)
com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver com.google.android.gms.measurement.internal.zzbj zzadq
```

The minor difference is between gms.**internal** and gms.**measurement.internal**.
I will deploy this new release as soon as possible and will write again with my result.

Those were the changes made:
1. Updated classpath 'com.google.gms:google-services:4.2.0' inside the build.gradle file (from 3.2.1 to 4.2.0)
2. Updated firebase_auth package to 0.6.6 (not sure if related)
3. Deleted ./gradle folder & "flutter clean"

**Comment by KammererTob** [comment]
This seem to have disappeared as suggested above. Look into the other closed issue for more information what changed.

**Comment by MarceloPetrucio** [comment]
I'm also having the same problem, I'm going to take a test following in your footsteps.

**Comment by MarceloPetrucio** [comment]
Really, it was just update com.google.gms: google-services: 3.2.1 to com.google.gms: google-services: 4.2.0 that solved the problem.

Thank you.
