### ISSUE TITLE
I'm getting advertisement everytime I "flutter run"

### ISSUE THREAD

**Issue by joshjinlee** [flutter/flutter#24447]
I'm hoping to god this is a malware virus and not something I'll have to deal with everytime I restart my app...

**Comment by beckler** [comment]
@joshjinlee Do you see the advertisement on your mobile device or on your computer?

If your seeing an advertisement on your mobile device, and you have not explicitly setup ads on your project, could you post your `pubspec.yaml` file?

**Comment by joshjinlee** [comment]
Did a Google search and found that it's coming from an "airpush ad".  I suddenly started getting them once I started "flutter run", but then I started getting them everywhere.  It may not be from Flutter at all, but who knows I guess.

--------------------------------------------------------------------------------------------------

`flutter doctor -v`

[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-CA)
    • Flutter version 0.11.3 at /Users/joshlee/Tools/flutter
    • Framework revision 72bf075e8d (9 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/joshlee/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Moto E 4 Plus • ZY224XW2GZ • android-arm • Android 7.1.1 (API 25)

• No issues found!

----------------------------------------------------------------------------------------------

`pubspec.yaml`

...

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  query_params: 0.6.1  # 0.6.1
  http:  #0.12.0
  flutter_redux:    # 0.5.2
  shared_preferences:   # 0.4.3
  flutter_redux_dev_tools:  # 0.3.0
  redux_thunk:    # 0.2.0
  fluttertoast:   # 2.0.9
  uuid:   # 1.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
...

**Comment by beckler** [comment]
My current guess is that you either have an Android/iOS SDK installed that's injecting ads, or there's a dart dependency that's injecting them... or you have malware.

So let's pinpoint this down with a few more questions:

1. Are the ads you're seeing isolated to just your app? Like do you see them whenever you open any app, or just the ones launched from your Flutter project?

2. Have you added any SDKs to the Android/iOS specific projects in your Flutter project? If `yes`, can you list them?

3. Have you tried to launch your Flutter project from an simulator/emulator and see if ads are still being injected? 

4. Create a new Flutter project with `flutter create`, and run it without any modifications. Are you still seeing ads? Do you still see ads when you use a simulator/emulator instead of your mobile device?

**Comment by joshjinlee** [comment]
Looks like it was an app that I downloaded from the PlayStore.

Note to Self:
If your phone GPS sucks and you download a compass 'cause you don't know where you're looking, don't download ones that don't have an Ad free guarantee.

Embarassing, but thanks for the support anyway guys!  You guys are as quick as ever!

**Comment by beckler** [comment]
@joshjinlee Glad you were able to figure it out! 👍
