### ISSUE TITLE
Flutter Gallery flashes white then black on startup 

### ISSUE THREAD

**Issue by milesmajefski** [flutter/flutter#24461]
Hello,
The problem I see is that when I build and run the Gallery it flashes white then black on app startup.  There are a few old issues that are talking about this, but they are closed now.  Here's the Doctor output:  

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code, 64-bit edition (version 1.29.1)
[√] Connected device (2 available)

• No issues found!
```
I'm just researching what tools/platforms to use for a new (mainly iOS) app, and this flashy startup thing is a deal breaker. 
Thanks for your help everyone!

**Comment by nklayman** [comment]
Probably on Android as Windows does not support iOS.

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/24420

**Comment by dnfield** [comment]
I don't think this could be related to #24420 either - it's a windows bug, the patch there was iOS exclusive...

**Comment by TahaTesser** [comment]
Hi @milesmajefski 
Please try new. https://gallery.flutter.dev/#/ 
Closing `flutter_gallery` no longer maintained/available
Thank you
