### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by KendiJ** [flutter/flutter#24467]
```
D:\flutterApps\news\hey_flutter>flutter create hey_flutter
Creating project hey_flutter...
  hey_flutter\.gitignore (created)
  hey_flutter\.idea\libraries\Dart_SDK.xml (created)
  hey_flutter\.idea\libraries\Flutter_for_Android.xml (created)
  hey_flutter\.idea\modules.xml (created)
  hey_flutter\.idea\runConfigurations\main_dart.xml (created)
  hey_flutter\.idea\workspace.xml (created)
  hey_flutter\.metadata (created)
  hey_flutter\android\app\build.gradle (created)
  hey_flutter\android\app\src\main\java\com\example\heyflutter\MainActivity.java (created)
  hey_flutter\android\build.gradle (created)
  hey_flutter\android\app\src\main\AndroidManifest.xml (created)
  hey_flutter\android\app\src\main\res\drawable\launch_background.xml (created)
  hey_flutter\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: e58b8cad672fd221)
Crash report written to D:\flutterApps\news\hey_flutter\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Is there anything special about the `D:` drive? Does your user account have write permissions in the Flutter install directory?

**Comment by KendiJ** [comment]
The only error am getting is that of connecting my phone/emulator.
I am using Windows 8, could that be the issue? I installed the SDK on drive
D because I was trying everything possible to have it work
I have been having this issue for almost 2 months.

**Comment by KendiJ** [comment]
My user account doesn't have user permissions.

**Comment by zoechi** [comment]
Can you please try to answer my questions?

**Comment by KendiJ** [comment]
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version
6.3.9600], locale en-US)

    • Flutter version 0.11.3 at D:\flutter

    • Framework revision 72bf075e8d (10 days ago), 2018-11-09 20:36:17 -0800

    • Engine revision 5646e86a6f

    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)


[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)

    • Android SDK at C:\Users\kendi\AppData\Local\Android\sdk

    • Android NDK location not configured (optional; useful for native
profiling support)

    • Platform android-28, build-tools 28.0.2

    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java

    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1136-b06)

    • All Android licenses accepted.


[√] Android Studio (version 3.2)

    • Android Studio at C:\Program Files\Android\Android Studio

    • Flutter plugin version 30.0.1

    • Dart plugin version 181.5656

    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1136-b06)


[√] IntelliJ IDEA Community Edition (version 2018.2)

    • IntelliJ at C:\Users\kendi\AppData\Roaming\JetBrains\IntelliJ IDEA
Community Edition 2018.2

    • Flutter plugin version 29.1.2

    • Dart plugin version 182.3569.4


[√] VS Code, 64-bit edition (version 1.29.1)

    • VS Code at C:\Program Files\Microsoft VS Code

    • Flutter extension version 2.20.0


[!] Connected device

    ! No devices available


! Doctor found issues in 1 category.

**Comment by KendiJ** [comment]
Did I answer correctly?

**Comment by zoechi** [comment]
> Please add the output of flutter doctor -v.

done

> Is there anything special about the D: drive? 

Not yet answered

> Does your user account have write permissions in the Flutter install directory?

> My user account doesn't have user permissions.

I don't know what "account doesn't have user permissions" means.
So I'd say this also is not yet answered.

**Comment by KendiJ** [comment]
Now I get your question. my user account has write permissions in the
Flutter install directory

**Comment by zoechi** [comment]
Please post the content of 

> Crash report written to D:\flutterApps\news\hey_flutter\flutter_01.log;

**Comment by KendiJ** [comment]
D:\flutterApps\news\hey_flutter>flutter run hey_flutter
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

D:\flutterApps\news\hey_flutter>

**Comment by zoechi** [comment]
That doesn't look like the content of `D:\flutterApps\news\hey_flutter\flutter_01.log`

**Comment by KendiJ** [comment]
How do I go about it?

**Comment by zoechi** [comment]
When you reproduce the problem the log output contains

> Crash report written to D:\flutterApps\news\hey_flutter\flutter_01.log;

(2nd last line in your initial comment)
Please copy the file or it's content into a comment.

**Comment by KendiJ** [comment]
The problem was the antivirus, I disabled it and now it's working just
fine.
Thanks
