### ISSUE TITLE
Freezing at "flutter build ios"

### ISSUE THREAD

**Issue by atfa** [flutter/flutter#24464]
When I exec "flutter build ios", It is freezing after:

`Build Dart code...`

## Logs

```
Building xxx.xxx.xxx for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXXX
Running pod install...                                       2.0s
Starting Xcode build...
 ├─Building Dart code...                             53.2s
```
But if I use "flutter build ios --release -v > build.log" ( https://github.com/flutter/flutter/issues/24325 ), After about 30 seconds, it's done. The last two lines in the build.log are:
```
[ +504 ms] Built /Users/xxx/AndroidStudioProjects/xxx/build/ios/iphoneos/Runner.app.
[   +1 ms] "flutter ios" took 26,210ms.
```

## Steps to Reproduce

1. flutter clean
2. flutter build ios

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14 18A391, locale en-CN)
    • Flutter version 0.11.3 at /Users/atfa/flutter
    • Framework revision 72bf075e8d (7 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/atfa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone XR • 6B452F65-C40F-4E54-8205-58B4DEB656DD • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by leoneparise** [comment]
Same here, when I try to run flutter with `--release` flag, it gets stuck and never finishes.

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
```

**Comment by jodymac** [comment]
Also Happening to me.  Flutter 0.11.3 and updated to latest Dart.  Flutter doctor is unchanged, I haven't bothered to fix the android issues yet.  I'm only running ios builds and simulators currently.
✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.3 at /Users/jody/Flutter/flutter
    • Framework revision 72bf075e8d (8 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/jody/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPad Air • 4D490940-6E90-4EEA-996E-76A20786086B • ios • iOS 10.2
      (simulator)

**Comment by jodymac** [comment]
Latest version fixes this. run flutter upgrade.
