### ISSUE TITLE
Status bar icons color

### ISSUE THREAD

**Issue by shabib3** [flutter/flutter#24472]
I defined my status bar color to transparent (also try it with white color), but the icons on the status bar are also white...how can I set another color to them?

I also took a look on this issue https://github.com/flutter/flutter/issues/17231

Thanks a lot :)

**Comment by shabib3** [comment]
ok so:

*flutter doctor -v:*
```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.14.1 18B75, locale en-IL)
    • Flutter version 0.11.3 at /Users/barzaruk/development/flutter
    • Framework revision 72bf075e8d (8 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0
      (API 27) (emulator)

! Doctor found issues in 1 category.
```

*and a sample is:*
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
          statusBarColor: Colors.white,
          statusBarIconBrightness: Brightness.dark),
    );
    return MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          backgroundColor: Colors.white,
          title: new Container(
            child: new Card(
              margin: EdgeInsets.all(10.0),
              child: new Container(
                color: Colors.green,
              ),
            ),
          ),
        ),
        body: new Container(),
      ),
      debugShowCheckedModeBanner: false,
    );
  }
}
``` 

take a look (on Android - didn't try on IOS) that the icons is white like the status bar color so they are hidden... How can I change the icon and text color to be readable (black/grey)?

Thanks! :)

**Comment by bitweng** [comment]
@shabib3 
The AppBar widget automatically sets the system overlay style based on its `brightness`。So you can remove AppBar and try again. 
However it seems can't not change the statusbar color no matter what pass in.
`app_bar.dart/_AppBarState.build(..) `

<img width="784" alt="2018-11-19 9 26 52" src="https://user-images.githubusercontent.com/1287611/48710029-29517100-ec42-11e8-90af-5732e896299f.png">

**Comment by jonahwilliams** [comment]
You cannot provide a status bar color to the app bar, but you can create your own annotated region. It's not very intuitive right now, but you can use `sized: false` to override the child annotated region created by the app bar. 

Somewhere, perhaps as a child of the scaffold:

```dart
Scaffold(
  body: AnnotatedRegion<SystemUiOverlayStyle>(
    value: const SystemUiOverlayStyle(...),
    sized: false,
    child: ...
  )
);
```

Note that not all Android versions support status bar color or icon brightness. See the documentation on SystemUiOverlayStyle for the caveats.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by jayasio** [comment]
@shabib3 

Changing the brightness of Appbar to Brightness.light lets you have dark icons on white or transparent statusbar.

**Comment by patelkrunal78** [comment]
Works totally fine in my app

import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    FlutterStatusbarcolor.setStatusBarColor(Colors.white);
    return MaterialApp(
      title: app_title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(title: home_title),
    );
  }
}
UPD: Another solution

SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
  statusBarColor: Colors.white
));

Find Your Solution At [Here](https://icetutor.com/question/how-to-change-status-bar-color-in-flutter)

**Comment by maksymilianpi** [comment]
> @shabib3
> 
> Changing the brightness of Appbar to Brightness.light lets you have dark icons on white or transparent statusbar.

Great solution!

**Comment by tudor07** [comment]
> > @shabib3
> > Changing the brightness of Appbar to Brightness.light lets you have dark icons on white or transparent statusbar.
> 
> Great solution!

Does not work
