### ISSUE TITLE
Doc improvement Continuous Delivery wrong link

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/flutter#24471]
On this site: https://flutter.io/docs/deployment/fastlane-cd
The link in chapter "Cloud build and deploy setup" point 3 is linked to the page itself

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2024](https://github.com/flutter/website/issues/2024) via [**ZenHub**](https://www.zenhub.com/)
