### ISSUE TITLE
App shows a blank screen

### ISSUE THREAD

**Issue by satyasreem** [flutter/flutter#24479]
Issue:
App shows a blank screen with this error message:

```
2018-11-17 15:16:25.608249-0600 Runner[2038:719090] Failed to find snapshot: /var/containers/Bundle/Application/158AEB52-E221-441E-A7E5-B881D42A637E/Runner.app/flutter_assets/kernel_blob.bin
2018-11-17 15:16:25.700151-0600 Runner[2038:719090] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2018-11-17 15:16:25.700853-0600 Runner[2038:719090] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2018-11-17 15:16:25.834256-0600 Runner[2038:719158] [VERBOSE-2:engine.cc(112)] Engine run configuration was invalid.
2018-11-17 15:16:25.835331-0600 Runner[2038:719158] [VERBOSE-2:FlutterEngine.mm(261)] Could not launch engine with configuration.
```
## Steps to Reproduce

Running an existing flutter app on a ioS phone.

1) Flutter clean
2) Open Xcode clean, 
3) run pod install,
4)  run pod update, 
4) Xcode-> clean 
5) Xcode -> Build with Target as Generic iOS device
6) Xcode -> Run for a target ( with a phone attached) 

Trying with 
1) flutter clean
2) flutter build ios
3) flutter run
also results in the same issue

```
[✓] Flutter (Channel master, v0.11.7-pre.35, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.11.7-pre.35 at <App dir>flutter
    • Framework revision 0ce68412d9 (2 days ago), 2018-11-16 01:22:05 -0500
    • Engine revision d1ea3fe02f
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at <User home>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Satyasree’s iPhone • 74343db317379500de8ef2dcdae7e1a99858b124 • ios • iOS 10.3.3

• No issues found!
```
```
Xcode version: Version 10.1 (10B61)
```

I have referred to this issue: https://github.com/flutter/flutter/issues/20777 but no resolution seem to work.
A folder named: /var/containers/Bundle/Application/158AEB52-E221-441E-A7E5-B881D42A637E/Runner.app/flutter_assets/kernel_blob.bin does not exist.

**Comment by satyasreem** [comment]
Please let me if there is any update on this issue? Cannot build or run flutter app on iOS.
I tried using Stable Xcode version: 10 , and the issue still remains.

**Comment by zoechi** [comment]
@satyasreem can you please try with `master` channel. There was a similar issue fixed recently.

**Comment by satyasreem** [comment]
@zoechi I have tried on flutter channel master. This issue blocks any testing on iOS simulator or real device, and cannot create a build to push to TestFlight. So all iOS deployments are blocked.
Please see: 
`Flutter 0.11.10-pre.1 • channel master • https://github.com/flutter/flutter.git
`

**Comment by satyasreem** [comment]
@zoechi ,  By saying existing app , I meant, existing flutter app that was already created using flutter create. 
Is there any update on this issue, since it blocks any testing or release of iOS apps?

**Comment by zoechi** [comment]
With existing app I mean a native Android or iOS app where Flutter is used to implement additional functionality.

**Comment by zoechi** [comment]
#23390 shows a similar error but that's also about integrating with existing native app.
I think we need more information about how to reproduce.

**Comment by zoechi** [comment]
#23220 looks similar but not related to an existing native app.

**Comment by satyasreem** [comment]
I upgraded flutter and 
1) creates a new project: flutter create <ProjName> 
2) Made a copy of the icon and assets in the existing flutter project. 
3) and copied the ios folder from the new project  to the existing flutter app 
4) flutter run works now on iOS
I used the same project name and this works now.
`flutter --version
Flutter 0.11.14-pre.2 • channel master • https://github.com/flutter/flutter.git
Framework • revision a226c0f0d9 (18 hours ago) • 2018-11-30 16:18:18 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)`

**Comment by zoechi** [comment]
Great! I'm going to close then.
Feel free to add a comment to get it reopened if you disagree.

**Comment by andrewackerman** [comment]
I've had to do this with two separate projects now (one before the first release and one after a successful release and several patches). Something is causing the iOS project to get consistently messed up, and there needs to be a more permanent fix/solution. I can't just keep deleting `ios/` and rebuilding it every time it happens, as it requires a bunch of time spent restoring config files, iOS-specific code, and pod plugins afterwards.

**Comment by zoechi** [comment]
@andrewackerman I think the issues under "Related information" in https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated cover that.

**Comment by zoechi** [comment]
@andrewackerman I was referring to the sub-section "Related information" which links to several issues.

**Comment by ChekTek** [comment]
I resolved this issue by changing the flutter target runner in xcode -  build active architecture only: yes
![image](https://user-images.githubusercontent.com/6678919/53133126-0899ff80-3540-11e9-9339-584a73afcbdf.png)
then run flutter clean and flutter run! :)

**Comment by satyasreem** [comment]
I concur with @andrewackerman. Have to rebuild iOS. setting active architectures alone does not solve this problem. This is not a long term solution imo.

**Comment by zoechi** [comment]
This is covered by other issues already

https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

> Related information
https://github.com/flutter/flutter/issues/14974
https://github.com/flutter/flutter/issues/12573
https://github.com/flutter/flutter/issues/12983
https://github.com/flutter/flutter/issues/9827
