### ISSUE TITLE
ItemsSnapAlignment is misleading

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2448]
The enum name "ItemsSnapAlignment" and its corresponding property as well as the enum values have quite unintuitive names given what they actually do.

**Comment by abarth** [comment]
@Hixie Any suggestions for better names?

**Comment by Hixie** [comment]
I forget what they do. :-)

**Comment by Hixie** [comment]
Oh, right. They decide whether or not flings snap to the next item or if they just fling freely and then snap once they settle.

**Comment by Hixie** [comment]
How about:
```dart
PageableListFlingBehavior flingBehavior;

enum PageableListFlingBehavior {
  stopAtNextChild,
  canFlingAcrossMultiplePages
}
```

cc @HansMuller

**Comment by HansMuller** [comment]
Sounds good to me although I think we could be a little bit more consistent with "page": 

enum PageableListFlingBehavior {
  stopAtNextPage,
  canFlingAcrossMultiplePages
}
