### ISSUE TITLE
Firebase Facebook login internal error on iOS

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#24488]
I'm trying to implement Firebase Facebook login but it throws an error says like so.

> PlatformException(sign_in_failed, FIRAuthErrorDomain, An internal error has occurred, print and inspect the error details for more information.)

I enabled Facebook method and paste code in plist.  
What am I doing wrong?   
Anyone have an idea?

**Code**

```dart
    try {
      final FacebookLogin facebookLogin = FacebookLogin();
      final result = await facebookLogin.logInWithReadPermissions(['email']);
      switch (result.status) {
        case FacebookLoginStatus.loggedIn: 
          final FirebaseUser user = await FirebaseAuth.instance.signInWithFacebook(accessToken: result.accessToken.token);
          print(user.uid);
        break;
        case FacebookLoginStatus.error:
          print('ERROR');
          break;
        default:
          break;
      }
     } catch (e) {
        print(e);
    }
```

**Comment by Daibaku0615** [comment]
Sorry for late reply 
**Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.13.6 17G3025, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

• No issues found!
exit code 0
```

**Comment by Jackrac** [comment]
Hello @Daibaku0615 
Do you have another type of authentication in your app ? Like Google auth ?
If you have already been authenticated with Google and try to authenticate after with Facebook, you can get this issue.
Do you have more details about the Exception ?

**Comment by Daibaku0615** [comment]
Yes, I have google too.
I thought `plist` was the problem because if Facebook info on it, even google login crashed the app.
I removed facebook login so no problem now.
I guess what went wrong was I tested both login with same device.
Thank you for clearing things up!

**Comment by zoechi** [comment]
Might be #23049

**Comment by kalkotekedar** [comment]
Try this [link](https://stackoverflow.com/questions/50536306/flutter-google-sign-in-crash-exceptionpreprocess-294?answertab=active#tab-top). It works for me for facebook login crash

**Comment by kroikie** [comment]
@ghost

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1119. Any further collaboration will be done there.
