### ISSUE TITLE
[dart] Target of URI doesn't exist: 'package:connectivity/connectivity.dart'. [uri_does_not_exist]

### ISSUE THREAD

**Issue by pratiktimer** [flutter/flutter#24485]
in main.dart
               import 'package:connectivity/connectivity.dart';
in pubs.yaml
                 connectivity: ^0.3.2
editior vs code

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected devices (1 available)

• No issues found!

**Comment by pratiktimer** [comment]
just close and reopen the folder to solve.............................

**Comment by slabo** [comment]
Thanks. Works, but don't know why or how.
