### ISSUE TITLE
Stuck when building for ios after latest upgrade

### ISSUE THREAD

**Issue by taherkhalil** [flutter/flutter#24487]
I have a simple application to read the qr code to get a id and fetch data from calling a api - 
it was working fine up until i upgraded to v0.11.6 

now when trying to build for ios it gets stuck after building dart code after `flutter build ios `

`> Building bma.counterlinic for device (ios-release)...
> Automatically signing iOS for device deployment using specified development team in Xcode project: G68PXQT5YX
> Running pod install...                                       3.5s
> Starting Xcode build...                                          
>  ├─Building Dart code...                             45.1s
> 

after this it  never completes .
below is output of flutter doctor[✓] Flutter (Channel unknown, v0.11.4, on Mac OS X 10.13 17A365, 

> locale en-KW)
>     • Flutter version 0.11.6 at /Users/cv/Downloads/flutter
>     • Framework revision df57dc9da9 (6 days ago), 2018-11-11 22:36:47 -0800
>     • Engine revision 5646e86a6f
>     • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.io/setup/#android-setup for detailed instructions).
>       If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
>       You may also want to add it to your PATH environment variable.
> 
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 9.2, Build version 9C40b
>     • ios-deploy 2.0.0
>     • CocoaPods version 1.5.3
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.io/setup/#android-setup for detailed instructions).
> 
> [✓] Connected device (1 available)
>     • iPhone X • 4B0064FC-492C-48E9-9D95-4C7F4F3643F4 • ios • iOS 11.2 (simulator)
> 

Below is output for `flutter analyze`
 

>  info • Prefer using /// for doc comments • lib/appointment_queue_stats_screen.dart:11:1 • slash_for_doc_comments
>    info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
>           lib/appointment_queue_stats_screen.dart:16:7 • must_be_immutable
>    info • Prefer using /// for doc comments • lib/appointment_queue_stats_screen.dart:72:1 • slash_for_doc_comments
>    info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
>           lib/appointment_queue_stats_screen.dart:79:7 • must_be_immutable
>    info • Prefer using /// for doc comments • lib/appointment_queue_stats_screen.dart:94:1 • slash_for_doc_comments
>    info • The value of the field '_timeRemaining' isn't used • lib/appointment_queue_stats_screen.dart:99:7 • unused_field
>    info • Prefer using /// for doc comments • lib/appointment_queue_stats_screen.dart:120:3 • slash_for_doc_comments
>    info • Prefer using /// for doc comments • lib/appointment_queue_stats_screen.dart:187:1 • slash_for_doc_comments
>    info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
>           lib/appointment_queue_stats_screen.dart:190:7 • must_be_immutable
>    info • Avoid using braces in interpolation when not needed • lib/appointment_queue_stats_screen.dart:270:13 •
>           unnecessary_brace_in_string_interps
>    info • Avoid using braces in interpolation when not needed • lib/appointment_queue_stats_screen.dart:270:22 •
>           unnecessary_brace_in_string_interps
>    info • Avoid using braces in interpolation when not needed • lib/appointment_queue_stats_screen.dart:270:33 •
>           unnecessary_brace_in_string_interps
>    info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
>           lib/appointment_status_screen.dart:15:7 • must_be_immutable
>    info • Name non-constant identifiers using lowerCamelCase • lib/appointment_status_screen.dart:30:9 • non_constant_identifier_names
>    info • Name non-constant identifiers using lowerCamelCase • lib/appointment_status_screen.dart:31:9 • non_constant_identifier_names
>    info • Prefer using /// for doc comments • lib/appointment_status_screen.dart:85:3 • slash_for_doc_comments
>    info • Prefer using /// for doc comments • lib/appointment_status_screen.dart:129:3 • slash_for_doc_comments
>    info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
>           lib/appointment_status_screen.dart:329:7 • must_be_immutable
>    info • Prefer using /// for doc comments • lib/appointment_status_screen.dart:379:3 • slash_for_doc_comments
>    info • The value of the field '_contactEmail' isn't used • lib/contact_screen.dart:21:10 • unused_field
>    info • The value of the field '_isLoading' isn't used • lib/contact_screen.dart:23:8 • unused_field
>    info • The value of the field '_appointmentVO' isn't used • lib/main.dart:45:17 • unused_field
>    info • The value of the field '_counter' isn't used • lib/main.dart:46:7 • unused_field
>    info • The method '_incrementCounter' isn't used • lib/main.dart:48:8 • unused_element
>    info • Unused import: 'package:counter_clinic/appointment_queue_stats_screen.dart' • lib/offline_scan_screen.dart:4:8 • unused_import
>    info • Prefer using /// for doc comments • lib/offline_scan_screen.dart:65:3 • slash_for_doc_comments
>    info • Prefer using /// for doc comments • lib/offline_scan_screen.dart:75:3 • slash_for_doc_comments
>    info • Unused import: 'dart:convert' • lib/partials/view_components.dart:1:8 • unused_import
>    info • The value of the field '_contactEmail' isn't used • lib/support_screen.dart:20:10 • unused_field
>    info • The value of the field '_isLoading' isn't used • lib/support_screen.dart:22:8 • unused_field
>    info • Unused import: 'package:counter_clinic/vo/AppointmentStatus.dart' • lib/utils/RequestHandler.dart:4:8 • unused_import
>    info • Prefer using /// for doc comments • lib/utils/RequestHandler.dart:19:3 • slash_for_doc_comments
>    info • Prefer using /// for doc comments • lib/utils/StorageHandler.dart:3:1 • slash_for_doc_comments
>    info • Prefer using /// for doc comments • lib/utils/StorageHandler.dart:14:1 • slash_for_doc_comments

i tried downgrading the flutter version by checking out older version but same issue

**Comment by saurik** [comment]
I am getting the same behavior, and have tracked it down to the use of `StreamOutput "done"` in xcode_backend.sh: if I change "done" to any other string it works fine (I'm serious; I have tested this carefully back/forth and what is locking up is trying to output the word "done").

**Comment by taherkhalil** [comment]
@saurik , could you guide me from where i can locate and change the values of` StreamOutput` .

**Comment by nikosdouvlis** [comment]
Can confirm same behavior when running `flutter run --release` on version 0.11.3

**Comment by cujslive** [comment]
@nikosdouvlis ya. me too have the same issue

**Comment by Hacker-CB** [comment]
I have same situation after last upgade.

```
...
[   +1 ms]  ├─Building Dart code...
[+1973 ms]  ├─Building Dart code... (completed)
```

Stuck after this....

```
Flutter 0.11.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 72bf075e8d (10 days ago) • 2018-11-09 20:36:17 -0800
```

**Comment by rcagantas** [comment]
There seems to be an release last night that fixes the issue. Not sure if it will add introduce new ones. Run "flutter upgrade"

**Comment by tausiq** [comment]
`Flutter 0.11.7 • channel beta` has been released and it fixes the issue. Run `flutter upgrade`

**Comment by zoechi** [comment]
Merging with #24139
