### ISSUE TITLE
I just want to know flutter is not supported Android(PIE) 9.0?

### ISSUE THREAD

**Issue by lwsdegithub** [flutter/flutter#24491]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Triluminos** [comment]
Hi. Flutter supports android Pie as well. I run some apps on my android Pie device

**Comment by GaryQian** [comment]
Flutter definitely support Pie! Are you having trouble running on 9.0? Please provide details and re-open if you are. Thanks!

**Comment by lwsdegithub** [comment]
> Flutter definitely support Pie! Are you having trouble running on 9.0? Please provide details and re-open if you are. Thanks!

Thanks, I had handled it. Flutter is very nice!!

**Comment by sagarmittal78** [comment]
> > Flutter definitely support Pie! Are you having trouble running on 9.0? Please provide details and re-open if you are. Thanks!
> 
> Thanks, I had handled it. Flutter is very nice!!
Pls Tell me how you handle that problem, I am facing the same issue
