### ISSUE TITLE
How to scroll nested ListView, when the child listview scroll to the top, scroll the parent listview.

### ISSUE THREAD

**Issue by Hanggi** [flutter/flutter#24499]
I use a Listview.builder build a child listview, but when this listview scroll to the top of its boundary it stops scroll. I tried physisc: ScrollPhysiscs or any other, it not work. Thank you.

**Comment by zoechi** [comment]
How-to questions are better asked on StackOverflow.
Perhaps https://stackoverflow.com/questions/45270900/child-listview-within-listview-parent

Please create a new issue with full information (`flutter doctor -v` output, reproduction, ...) if it turns out to actually be a Flutter issue.
