### ISSUE TITLE
Raised button not enabling in ios, android is working

### ISSUE THREAD

**Issue by ZeroCool00** [flutter/flutter#24508]
when snapshot.hasData call RaisedButton disable by default but its never going to enable even it has data. This behaviour only in ios, in android its working.

```
StreamBuilder(
                        stream: bloc.submitValid,
                        builder: (context, snapshot) {
                          return Container(
                          padding: EdgeInsets.symmetric(horizontal: 100.0),
                          margin: EdgeInsets.only(bottom: 20.0),
                          child: RaisedButton(
                              color: grey,
                              onPressed: snapshot.hasData ? bloc.submit : null,
                              child: Text(
                                'LOGIN',
                                style: TextStyle(
                                  color: white
                                ),
                              ),
                          ),
                          );
                        },
)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-IN)
• Flutter version 0.11.3 at /MyDrive/flutter
• Framework revision 72bf075 (6 days ago), 2018-11-09 20:36:17 -0800
• Engine revision 5646e86a6f
• Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
• Android SDK at /Users/micra/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 9.4.1, Build version 9F2000
• ios-deploy 2.0.0
• CocoaPods version 1.5.3

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
What happens if you replace `snapshot.hasData ? bloc.submit : null` by `(){}`? Does it get enabled?

**Comment by ZeroCool00** [comment]
oops, its been 4 days, and i changed approach 2 days ago. i am not using bloc now..  i dont have code right now. but its bug in ios, i also did this: `snapshot.hasData ? bloc.submit : null by (){}` still no effect on ios. 
And another bug is when keyboard is close, bloc.email and bloc.password value become null, if i submit when keyboard is open i get email and password both value. but when keyboard is close, both value become null. thats is why i change approach.

**Comment by ZeroCool00** [comment]
i have bloc file code, if its help you.


[bloc.zip](https://github.com/flutter/flutter/files/2609708/bloc.zip)

**Comment by zoechi** [comment]
Can you please up a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce instead of a zip file.

**Comment by tunde-gabby** [comment]
Hello Sagar, how did you resolve this issue you raised on IOS?
It would be helpful if you share
Many thanks.
