### ISSUE TITLE
Startup  screen is difficult to use

### ISSUE THREAD

**Issue by shifeng1993** [flutter/flutter#24516]
The android section wants to add support for layout custom controls, not just drawable. 

The iOS section wants to add support for fixed pixels. such as 19.5: 9 iphoneX, instead of just 1x, 2x, 3x images. 

The current Startup screen layout is suitable for information in the center of the screen, but in China, there are a lot of apps that are at the bottom of the screen, such as alipay

**Comment by zoechi** [comment]
Sounds like you are referring to www.flutter.io
Can you please post a link to the concrete page you are referring to and a screenshot that shows the issue?

**Comment by yy1300326388** [comment]
@zoechi  I have the same problem, and now I use LaunchScreen.storyboard on iOS to implement the splash screen, but iPhone X doesn't fit well.

**Comment by shifeng1993** [comment]
@yy1300326388 @zoechi 

Yes, on android, I used custom layout to make a left and right automatic adaptation, bottom against bottom edge, upper cut image layout. But, I can't use this custom layout in drawer，

This layout can be adapted to a variety of sizes of profiled screen,

```java
package com.suninfo.sicap;

import android.content.Context;
import android.graphics.Matrix;
import android.graphics.RectF;
import android.util.AttributeSet;
import android.widget.ImageView;

public class BottomCropImageView extends ImageView {

    public BottomCropImageView(Context context) {
        super(context);
        setup();
    }

    public BottomCropImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
        setup();
    }

    public BottomCropImageView(Context context, AttributeSet attrs,
                               int defStyle) {
        super(context, attrs, defStyle);
        setup();
    }

    private void setup() {
        setScaleType(ScaleType.MATRIX);
    }

    @Override
    protected boolean setFrame(int l, int t, int r, int b) {
        if (getDrawable() == null)
            return super.setFrame(l, t, r, b);

        Matrix matrix = getImageMatrix();

        float scale;
        int viewWidth = getMeasuredWidth() - getPaddingLeft() - getPaddingRight();
        int viewHeight = getMeasuredHeight() - getPaddingTop() - getPaddingBottom();
        int drawableWidth = getDrawable().getIntrinsicWidth();
        int drawableHeight = getDrawable().getIntrinsicHeight();
        //Get the scale
        if (drawableWidth * viewHeight > drawableHeight * viewWidth) {
            scale = (float) viewHeight / (float) drawableHeight;
        } else {
            scale = (float) viewWidth / (float) drawableWidth;
        }

        //Define the rect to take image portion from
        RectF drawableRect = new RectF(0, drawableHeight - (viewHeight / scale), drawableWidth, drawableHeight);
        RectF viewRect = new RectF(0, 0, viewWidth, viewHeight);
        matrix.setRectToRect(drawableRect, viewRect, Matrix.ScaleToFit.FILL);

        setImageMatrix(matrix);

        return super.setFrame(l, t, r, b);
    }

}

```


On the ios, because of the fixed size of the ios device, a variety of resolutions are available for adaptation. 

But the 1x, 2x, 3x that flutter uses obliterates that advantage altogether.

**Comment by jmagman** [comment]
The [iOS launch screen documentation](https://flutter.dev/docs/development/ui/advanced/splash-screen#ios-launch-screen) was updated in https://github.com/flutter/website/pull/3927.  

> The iOS section wants to add support for fixed pixels. such as 19.5: 9 iphoneX, instead of just 1x, 2x, 3x images.

I created https://github.com/flutter/flutter/issues/57048 to track that the LaunchImage in `Runner/Assets.xcassets` should be a launch image instead of a universal set 1x, 2x, 3x.

**Comment by xster** [comment]
For Android, you can now provide any custom views as needed. 

Instructions at https://flutter.dev/docs/development/ui/advanced/splash-screen

**Comment by xster** [comment]
Closing this issue if https://github.com/flutter/flutter/issues/57048 is the only branch out task left.

**Comment by shifeng1993** [comment]
Thanks for the fix.
