### ISSUE TITLE
Google Maps map callbacks are not working on iOS

### ISSUE THREAD

**Issue by andreabtis** [flutter/flutter#24520]
I'm using this Google Maps plugin: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter

On Android it's working fine, but markers on iOS are not working properly. When a marker is tapped on iOS platform, camera moves a little bit and displays an InfoText, but my flutter code is the same for both platforms. I put breakpoints on methods: `onMarkerTapped()` and `onInfoWindowTapped()` and there are not called on iOS devices.

![captura de pantalla 2018-11-19 a les 15 32 19](https://user-images.githubusercontent.com/41053869/48713353-59801c00-ec10-11e8-929e-b732bcb70e10.png)

And marker icon with a `BitmapDescriptor` is not working on iOS too, but it's not as important as all I've mentioned before.

**- Someone knows how to call this methods on iOS?**

Please, I need to fix this on iOS platform and I don't know how.

Thanks!

**Comment by DCrow** [comment]
Might be connected to https://github.com/flutter/flutter/issues/24207#issuecomment-437963420

**Comment by bdeman** [comment]
Does it not focus on the marker you have tapped? I'm currently experiencing an issue with this myself.
I click the marker and instead of focusing/centering the marker/view, it shifts the view to the bottom right of the marker and nothing gets displayed.

**Comment by amirh** [comment]
https://github.com/flutter/plugins/pull/934 should fix this
