### ISSUE TITLE
bottomAppbar need 1 argument but 0 found

### ISSUE THREAD

**Issue by therichiekumar** [flutter/flutter#24524]
1 required argument(s) expected but 0 found' error

I'm trying my hand at building an app with flutter (which uses Dart 2). I'm getting an error which I cant figure out:

The error is at the bottomNavigationBar: new BottomAppBar(

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        floatingActionButton: new FloatingActionButton(
          child: new Icon(Icons.add),
          onPressed: (){},
        ),
        bottomNavigationBar: new BottomAppBar(
          color: Colors.amber,
          child : new Row(
            mainAxisSize: MainAxisSize.max, 
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              new IconButton(icon: new Icon(Icons.camera),onPressed: (){},),
              
              new IconButton(icon: new Icon(Icons.call),onPressed: (){},),

            ],
            )
        ),
      ),
    );
  }
}
```

**Comment by salihgueler** [comment]
First of all, Please ask your HOWTO questions on stackoverflow.com first. There you will get faster answer. 

If you think that Flutter has a bug and you need to file an issue, please provide the wanted information from you on the `New Issue` page including Steps to reproduce and `flutter doctor -v`.

**Comment by HansMuller** [comment]
Your app appears to compile and run correctly.

As @salihgueler mentioned, this isn't the best place to get help, ask questions, etc. See https://flutter.io/community

**Comment by zoechi** [comment]
Going to close as support request then that is better asked on StackOverflow or similar.
