### ISSUE TITLE
Can I put flutter_assets to Pod  resource_bundles?

### ISSUE THREAD

**Issue by xclee** [flutter/flutter#24525]
I have a Pod project, and I want to put flutter_assets to Pod resource_bundles for CI

**Comment by xclee** [comment]
use FlutterDartProject to solve it ~

**Comment by sdaduanbilei** [comment]
@xclee Is there a demo, the idea is not to publish Flutter.framework and App.framework flutter_assets products through Pod, then the new project to get flutter business through pod install, can see your podspec file
