### ISSUE TITLE
App crashes when ndk { abiFilter  } is present in Android Studio

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#24534]
Hey! I had some problem that my app was working flawlessly while running through my USB (Android Studio or `flutter run`, but when I uploaded it to Google Play, it was crashing instantly on startup for my users. I have resolved this issue with this solution: https://github.com/flutter/flutter/issues/18494#issuecomment-399155013 (OP also described my problem from that time).

But now, I want to continue developing my app on my PC, but this `ndk { abiFilters "armeabi-v7a" }` line prevents me from doing that. App crashes instantly on startup and there are no helpful logs. I can of course just comment out this line for the time of development. But that obviously is not a good solution. 

What's the good solution?

```
[        ] Installing build\app\outputs\apk\app.apk... (completed)
[   +1 ms] executing: C:\Users\walbe\AppData\Local\Android\sdk\platform-tools\adb -s 712KPED1275708 shell echo -n b8a45b6d6f73d64bfdcc0d066ab107dc52f63b23 > /data/local/tmp/sky.me.wolszon.lekbierz.sha1
[  +48 ms] Pixel 2 XL startApp
[   +1 ms] executing: C:\Users\walbe\AppData\Local\Android\sdk\platform-tools\adb -s 712KPED1275708 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true me.wolszon.lekbierz/me.[   +1 ms] executing: C:\Users\walbe\AppData\Local\Android\sdk\platform-tools\adb -s 712KPED1275708 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true me.wolszon.lekbier
z/me.wolszon.lekbierz.MainActivity
[  +96 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=me.wolszon.lekbierz/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```

##### My doctor

```[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.407], locale pl-PL)
    • Flutter version 0.9.4 at D:\flutter
    • Framework revision f37c235c32 (8 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\walbe\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • Pixel 2 XL • 712KPED1275708 • android-arm64 • Android 9 (API 28)
```

**Comment by hariprasadiit** [comment]
it works with `--target-platform android-arm`. But with `0.10.2`, it used work even without setting `--target-platform android-arm` with `abiFIlters` set.

has something changed in this regard in `0.11.7`?

**Comment by Albert221** [comment]
@jason-simmons yes, it indeed does work with `--target-platform android-arm`.

What annoys me the most is the _inconsistency_ when it comes to building the APK for Google Play, because I have to wait few hours for it to be published and I'm not sure whether this will be the instant-crashing version or not, it would be really helpful to have some kind of instructions about this topic in FAQ if fixing it is not that straight-forward :)

**Comment by Albert221** [comment]
I have narrowed the problem. I know, that it's because of the [firebase_ml_vision](https://pub.dartlang.org/packages/firebase_ml_vision). Problem from the initial post is gone when I removed it.

**Comment by hariprasadiit** [comment]
@Albert221 I don't use `firebase_ml_vision` plugin but i use package which depend on **ML Kit**. Perhaps this is an issue with **ML Kit** itself?

For me flutter always fails to add `libflutter.so` if i don't use workaround in debug.

**Comment by MichalMisiaszek** [comment]
You can always test if it crashes by installing directly on your phone via Google Drive. When it crashes you know it will not work via Google Play neither. I have same problem and this is VERY annoying. Why Flutter guys can't fix it ?

**Comment by MichalMisiaszek** [comment]
BTW. There is solution since 2 hours at the very bottom of https://github.com/flutter/flutter/issues/18494

**Comment by blasten** [comment]
I'm unable to reproduce this in the `master` channel. 

 Flavors with `abiFilters` work as expected.  Also, for anyone reading this thread, you may want to use `flutter build apk --split-per-abi`.  See: https://flutter.dev/docs/deployment/android#building-the-app-for-release
