### ISSUE TITLE
Document an updated playbook for Flutter to Fuchsia rolls.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#24543]
Rolls of Flutter into Fuchsia used to involve rolling the Flutter Framework, Engine and Dart repositories (colloquially called the triforce roll). After the [disabling of the Skia to Fuchsia autoroller](https://github.com/flutter/flutter/issues/24541), the version of Skia used by Fuchsia is tied to the version used by the Flutter engine. This means that the Fuchsia roll needs to take into account Skia as well. This change along with the cake to petal migration in Fuchsia means we need an updated playbook for Fuchsia rolls. @zanderso has been working on such rolls but we should document and setup a rotation for the same.

**Comment by kf6gpe** [comment]
Obsolete.
