### ISSUE TITLE
Disable the Skia to Fuchsia Autoroller.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#24541]
Currently, there are two auto-rollers that roll Skia in the [Fuchsia](https://autoroll-internal.skia.org/r/fuchsia-autoroll) and [Flutter](https://autoroll.skia.org/r/skia-flutter-autoroll) buildroots respectively. Consequently, the Flutter engine has to be compatible with two versions of Skia. Since this is not always possible, the version of Skia used by Fuchsia should be tied to the one referenced in [DEPS file in the Flutter engine buildroot](https://github.com/flutter/engine/blob/master/DEPS).

The side effect of this and the adherence to the "one version" dictum enforced in the Fuchsia buildroot is that existing targets in Fuchsia will be tied to the Skia version used by the Flutter. Such targets don't seem to be particularly common or complex but this may not be the case in the future.

**Comment by chinmaygarde** [comment]
Thanks, the link to the rollers in the wiki was old. Updated.

**Comment by chinmaygarde** [comment]
@rmistry: I think we are ready now. However, I am not able to disable the roller because of the following error `"Failed to change the mode: [object Object]"`. Can you disable / help me troubleshoot the same please? Once the roller is disabled, I can reconcile the Skia version in Fuchsia with the one currently used by Flutter. Once that is settled, we can remove the roller completely.

**Comment by chinmaygarde** [comment]
Thanks to @rmistry for the troubleshooting. The roller has been disabled. Reconciling the changes in Fuchsia.

**Comment by rmistry** [comment]
@chinmaygarde : Should I go ahead and delete the Skia->Fuchsia roller?

**Comment by chinmaygarde** [comment]
Can we wait till at least one roll has been completed into Fuchsia manually?

**Comment by rmistry** [comment]
Sure, no rush. I am OOO tomorrow so will probably do it on Monday (once I get confirmation).

**Comment by chinmaygarde** [comment]
We are rolling manually into Fuchsia now and the latest roll has landed. Please delete the roller when able. Thanks.

**Comment by rmistry** [comment]
Deleted the roller, Thanks.
