### ISSUE TITLE
Align and EdgeInsets use only "Left" and "Right", could also have "Start" and "End"

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#24546]
Currently `Align` and `EdgeInsets` and others use `left` and `right`, I think this is fine for most use cases, but sometimes we may want to flip things for RTL layouts, so it would be nice to also have `start` and `end`, which will dynamically map to `left` or `right` depending on the `locale` of the device, at runtime.

**Comment by HansMuller** [comment]
Flutter provides directional geometry types for just this reason. For example see
[EdgeInsetsDirectional](https://docs.flutter.io/flutter/painting/EdgeInsetsDirectional-class.html) and [AlignmentGeometry](https://docs.flutter.io/flutter/painting/AlignmentGeometry-class.html).

**Comment by feinstein** [comment]
Interesting... I went to try them out, trying to place a FAB on the left of the screen for LTR and on the right of the screen for RTL, but it didn't work. I forced RTL in the developer options, but the layout didn't change, even after restarting the App. Here's my code:

        child: Align(
            alignment: AlignmentDirectional.topStart,
            child: Padding(
              padding: EdgeInsetsDirectional.only(start: 8, top: 20.0),
              child: Builder(builder: (BuildContext context) {
                return FloatingActionButton(
                  onPressed: () => Scaffold.of(context)?.openDrawer(),
                  backgroundColor: Colors.white,
                  foregroundColor: Colors.black,
                  mini: true,
                  child: Icon(Icons.menu),
                );
              }),
            ),
          ),

**Comment by HansMuller** [comment]
Not sure what "developer options" you're referring to however that may just be my ignorance of the Flutter IDE. 

If you wrap the widgets you've created in a Directionality widget that specifies `textDirection: TextDirection.rtl` you'll see RTL layout.

**Comment by feinstein** [comment]
I mean the developer options on Android, where we can force the device to be RTL.

So Flutter doesn't automatically detect RTL? I have to inform if it's RTL or not with a Directionality widget?

**Comment by feinstein** [comment]
Interesting, thanks!
