### ISSUE TITLE
regression black screen before first screen only IOS

### ISSUE THREAD

**Issue by gimox** [flutter/flutter#24563]
With flutter 0.11.7 the first screen appear black for some second. no error, only on IOS

- Start flutter app
- first open splash (OK)
- black screen for 1 second (THE PROBLEM HERE)
- first flutter screen

```
[✓] Flutter (Channel beta, v0.11.7, on Mac OS X 10.13.6 17G3025, locale it-IT)
    • Flutter version 0.11.7 at /Users/giorgiomodoni/development/flutter
    • Framework revision 7a005e1dcd (18 hours ago), 2018-11-19 11:14:05 -0500
    • Engine revision 2e06da3df9
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/giorgiomodoni/Library/Android/sdk
    • Android NDK at /Users/giorgiomodoni/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/giorgiomodoni/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.29.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone XS • 0339A595-2304-4EF8-BC9E-39445E1C4783 • ios • iOS 12.1 (simulator)
```

**Comment by rickyazhari** [comment]
i've same issue.
my flutter doctor

[```
✓] Flutter (Channel beta, v0.11.8, on Mac OS X 10.14 18A391, locale en-ID)
    • Flutter version 0.11.8 at /Users/lumos/personal/sdk/flutter
    • Framework revision f5b02e3c05 (16 hours ago), 2018-11-20 07:49:29 -0800
    • Engine revision 1baf081343
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/lumos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Ricky’s iPhone • d6606fd561e978ea2dabc5a795b25a4af2a7d439 • ios • iOS 12.0
    • iPhone SE      • 16C15C6D-A2F2-4148-B3B6-19ED0E7DB10C     • ios • iOS 12.1 (simulator)
```

**Comment by zoechi** [comment]
Similar to #24461, #20827

**Comment by xster** [comment]
Looks like https://github.com/flutter/flutter/issues/24420

cc @dnfield

**Comment by emekalites** [comment]
could this be resolved, I'm having the same issue.

**Comment by dnfield** [comment]
Once https://github.com/flutter/flutter/pull/24659 lands it will be fixed on master.

**Comment by Sh1d0w** [comment]
@dnfield This PR was closed without merging? Any info when this will be fixed?

**Comment by dnfield** [comment]
It was reopened and should be good on master now.

**Comment by dnfield** [comment]
#24707 has it

**Comment by Sh1d0w** [comment]
Great, thanks!

**Comment by allandaleho** [comment]
I'm having this issue in beta... `Flutter (Channel beta, v1.1.8, on Mac OS X 10.14 18A391, locale en-SG)`.

I hope someone can give me instructions, it's happening only on my app and not on gallery.

It also on iOS only.

**Comment by Theunodb** [comment]
This issue was raised by the apple review team after i submitted my app. According to them they see a black screen when running the app on iPad iOS 12.4 on wifi. I cannot reproduce the issue in any simulator, but cant get my app past review.

Anyone have any suggestions?

`
[✓] Flutter (Channel master, v1.3.14-pre.7, on Mac OS X 10.14.3 18D109, locale
    en-ZA)
    • Flutter version 1.3.14-pre.7 at /Users/td0810/flutter
    • Framework revision ee3e621f02 (6 hours ago), 2019-03-18 21:40:21 -0700
    • Engine revision 5088735e5f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/td0810/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/td0810/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/td0810/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Users/td0810/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (2 available)
    • iPhone Xs Max                         •
      F162F6BE-6800-47E6-B704-7EE1C61045C5 • ios • iOS 12.1 (simulator)
    • iPad Pro (12.9-inch) (3rd generation) •
      7CD32CE3-DA53-4904-93E2-6FB153BC3D03 • ios • iOS 12.1 (simulator)

• No issues found!
`

**Comment by dnfield** [comment]
Do you have a splash screen set?  Are you adding a flutter view to an existing iOS app or is this a regular Flutter app?

**Comment by Theunodb** [comment]
Yes i do have it set in the storyboard, and it is visible to me when i start the app. This is a regular flutter app.

**Comment by su-khi** [comment]
Following helped me to solve this issue.

1. I logged pretty much every action along with the timestamp.
2. This helped in figuring out which actions are being performed in the black window. 
3. Observed around 6 different function calls (and associated processing in totally different areas). 
4. Used package **after_layout** to shift some of the functionality AFTER the screen load.
5. Step 4 reduced the black window but did not completely elimnate it. (Perhaps your's will do).
6. I added a splash screen (with .dart file) and routed the user to the main screen via .dart. So, now I've LaunchScreen.storyboard containing a splash image, exact splash image in the .dart and then the app's main screen.
7. This completely elimated the unwanted black-blank screen.

Perhaps, a little more fine tuning can be done in step 6 above. I'll work it out later tonight.

Just so you know, following did not help :
1. Upgrading Flutter
2. Re-creating iOS stuff (by "flutter create .") <-This is just a waste of time as lot of things needs to be set manually. Again.
3. Manipualting launch screen time via AppDelegate.m

**Comment by dkobia** [comment]
I am encountering this issue too. I cannot replicate on the simulator and only seems to happen with iPad running iOS 12.4 on Wi-Fi and cannot get past an app review.

```
[✓] Flutter (Channel master, v1.8.5-pre.131, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.8.5-pre.131 at /Users/david/Development/flutter
    • Framework revision 54439bf534 (3 days ago), 2019-08-13 05:12:53 -0400
    • Engine revision 7dfdfc6fae
    • Dart version 2.5.0 (build 2.5.0-dev.2.0 9aea1f3489)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/david/Development/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/david/Development/Android/sdk
    • Java binary at: /Users/david/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/david/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Users/david/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPad Pro (9.7-inch) • AD969F21-3216-4E5F-9BCF-8C6696AE2EB1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)

• No issues found!
```
