### ISSUE TITLE
 MissingPluginException(No implementation found for method close on channel flutter_webview_plugin)

### ISSUE THREAD

**Issue by manondidi** [flutter/flutter#24561]
it work fine in single flutter project,but not in a exiting project add into flutter
i can send you source code  by email

**Comment by manondidi** [comment]
https://github.com/fluttercommunity/flutter_webview_plugin/issues/244

**Comment by manondidi** [comment]
android

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by manondidi** [comment]
i fixed this problem,but ...
i  think it is maybe  a bug in a exiting project add into flutter
i add flutter into my project  by  https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
but i dont use flutterView or createFragment
i create a activity extand FlutterFragmentActivity
 MissingPluginException(No implementation found for method close on channel flutter_webview_plugin) 


i fixed it by 
1) app.gradle    
    implementation project(':flutter_webview_plugin')
2) my activity
```
class ShopActivity : FlutterFragmentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        GeneratedPluginRegistrant.registerWith(this)
        FlutterWebviewPlugin.registerWith(this.registrarFor("com.flutter_webview_plugin.FlutterWebviewPlugin"))
}
}```

why it happend?  can you fix it without  FlutterWebviewPlugin.registerWith???

because  i dont use flutterview or flutterfragment?

thanks

**Comment by giginho** [comment]
Sorry, but I'm not understanding your solution: can you explain it in other words? Thanks a lot. 

I have the same problem: I'm trying to include a flutter module into an existing app and when I connect the module with the app by means of Method Channel method I catch the exception: 

> MissingPluginException(No implementation found for method close on channel 'channel name') >

**Comment by xster** [comment]
The Android integration system has since been reworked. Please try again now with the new documentation https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar.
