### ISSUE TITLE
Pixel 2 doesn't successfully take photos with Camera plugin; no errors. 

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#24576]
## Steps to Reproduce

1. Run code here: https://github.com/efortuna/final_countdown (apologize in advance that this demo isn't smaller) on a physical Pixel 2. It will take a picture every 10 seconds.
2. All the camera code is in [photo_clock.dart](https://github.com/efortuna/final_countdown/blob/master/lib/clocks/photo_clock.dart).
3. You can see a path is created for an image, and the app reports no errors taking a photo, but no pictures appear. The ListView film-strip scrolls longer as "pictures" get added, but no actual images show up. 

This does _not_ happen with a Nexus 5. On a Nexus 5 everything works fine. Also interestingly, I tried the example in the camera plugin library on the Pixel 2 and it *does* work correctly, so something I guess is not properly being initialized in the photo_clock.dart use case? But it is unclear what is going wrong.

```
[✓] Flutter (Channel master, v0.11.8-pre.9, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 0.11.8-pre.9 at /Users/efortuna/flutter
    • Framework revision 921117f4d3 (20 hours ago), 2018-11-19 15:23:40 -0800
    • Engine revision 2f1b388f5a
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/efortuna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27)
      (emulator)

• No issues found!
```

^ Side note: I've also run this with the beta channel of Flutter; same thing happens.

**Comment by bparrishMines** [comment]
I was able to get images to show up by changing 
`await initializeCamera();` to `if (_camera == null) await initializeCamera();` at line
https://github.com/efortuna/final_countdown/blob/master/lib/clocks/photo_clock.dart#L81

I think there may be an issue with re-initializing for every image.

**Comment by efortuna** [comment]
Ah, thank you, Maurice! It's weird, I didn't have this issue with any of the other devices that I tested this on (including Pixel 3), but I'll add that line.
