### ISSUE TITLE
"google_sign_in" not working on an actual device but work only on emulators

### ISSUE THREAD

**Issue by kwaku96** [flutter/flutter#24573]
the "google_sign_in" plugin works only my emulator but then gives an error when I try it on an actual device
![photo_2018-11-20_22-35-03](https://user-images.githubusercontent.com/38118032/48797940-8ddd0080-ed14-11e8-8883-dc5939a6b7aa.jpg)

**Comment by kwaku96** [comment]
![screenshot 43](https://user-images.githubusercontent.com/38118032/48798204-283d4400-ed15-11e8-9b16-460abec6ebca.png)


and this is my code for google_sign_up

**Comment by kwaku96** [comment]
my device had active internet connection, as it was connected to my WIFI,
And the version of android on the emulator is android P while the actual device which I tested on was running android 7 (Nougat)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by diegoveloper** [comment]
Did you use the same apk file for emulator an device ?  or release mode for device?

**Comment by zoechi** [comment]
Looks like #24378, #22784
Can you please post the console output the error produces?

**Comment by kwaku96** [comment]
This is the output when I run flutter doctor -v


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kwaku96** [comment]
[cid:image003.png@01D4819F.C7FE4520]

This is the output from the console

________________________________

**Comment by kwaku96** [comment]
This when I used the emulator

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by zoechi** [comment]
@kwaku96 I can't see any actual content in your last 3 comments. 
Can you please use the web interface to add the content instead responding to the notification mail?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
