### ISSUE TITLE
Determin the size of placeholder to match the actual size of the image

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#24572]
"width": 5245, "height": 3497, "color": "#60544D"

 this is part of the API response, i want to know  how to use these values. i can set the width of all images to double.infinity but i need to calculate the height, so that i can put a placeholder color and when the image loaded it replaces it smoothly

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/53396921/flutter-determine-the-size-of-placeholder-to-match-the-actual-size-of-the-image is the right place for this kind of question.
