### ISSUE TITLE
RaisedButton not respecting clipBehavior

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#24583]
[✓] Flutter (Channel dev, v0.11.8, on Mac OS X 10.13.6 17G3025, locale en-US)

```dart
final button = RaisedButton(
  clipBehavior: Clip.hardEdge,
  animationDuration: puzzleAnimationDuration,
  child: SizedBox.expand(child: Container(color: Colors.white)),
  onPressed: tilePress(1),
  shape: RoundedRectangleBorder(
    side: const BorderSide(width: 2),
    borderRadius: BorderRadius.circular(40),
  ),
  padding: const EdgeInsets.symmetric(),
);
```

Would expect the corders outside the border to be clipped, but no.

![screen shot 2018-11-20 at 2 07 01 pm](https://user-images.githubusercontent.com/17034/48805912-92ca9180-eccd-11e8-85de-67ab0f9f2c7f.png)

**Comment by Hixie** [comment]
cc @liyuqian

**Comment by liyuqian** [comment]
I can't reproduce it using the following code on our master branch:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text("Test"),
        ),
        body: Container(
          color: Colors.blue,
          child: RaisedButton(
            clipBehavior: Clip.hardEdge,
            child: SizedBox.expand(child: Container(color: Colors.white)),
            onPressed: (){},
            shape: RoundedRectangleBorder(
              side: const BorderSide(width: 2),
              borderRadius: BorderRadius.circular(40),
            ),
            padding: const EdgeInsets.symmetric(),
          ), // This trailing comma makes auto-formatting nicer for build methods.
        ),
      ),
    );
  }
}
```
![flutter_01](https://user-images.githubusercontent.com/22987568/48807528-a75d5880-ecd2-11e8-8253-bc2a5a6b3680.png)

Can you please post a complete app that could reproduce your issue on our master branch?

**Comment by kevmoo** [comment]
On it...

**Comment by kevmoo** [comment]
Just tried here and couldn't get a repro. Possible I was in a weird state w/ all of this, but... 🤷‍♂️ 

Closing

Flutter 0.11.9 • channel dev • ssh://git@github.com/flutter/flutter
Framework • revision d48e6e433c (17 hours ago) • 2018-11-20 22:05:23 -0500
Engine • revision 5c8147450d
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
