### ISSUE TITLE
cant find any dart.exe file

### ISSUE THREAD

**Issue by owolabiezekiel** [flutter/flutter#24592]
I just finished all dart and flutter installation and setup with android studio.
When I try to run "flutter doctor",  I get the error "C:\flutter\bin\cache\dart-sdk\bin\dart.exe"' is not recognized as an internal or external command, operable program or batch file."

I have tried most of the solutions here but they are not working

**Comment by dnfield** [comment]
Does the file exist at that path?

Can you try running `flutter precache` if it doesn't?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by xylemrahul** [comment]
This issue will persist if we install flutter plugin from Android Studio or Intellij. Best way will be to download  [Dart-sdk](https://dart.dev/get-dart) and install it. Now copy the dart-sdk file from this installation directory and replace and paste under flutter ->bin ->cache. It works this way.

**Comment by SourabhSaha71** [comment]
I don't understand
