### ISSUE TITLE
I believe this was fixed.

### ISSUE THREAD

**Issue by owolabiezekiel** [flutter/flutter#24590]
Is this still an issue for you?

_Originally posted by @zoechi in https://github.com/flutter/flutter/issues/16410#issuecomment-404759307_

No this hasnt been fixed. I am having the same issue right now

**Comment by zoechi** [comment]
That's not enough information to diagnose the issue.
Try reinstalling Flutter.

**Comment by zoechi** [comment]
dup of #24592

**Comment by owolabiezekiel** [comment]
It works now thanks. Looks like my flutter installation was incomplete
