### ISSUE TITLE
Support for creating threads/isolates

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#246]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [collinjackson](https://github.com/collinjackson)**
_Monday Nov 02, 2015 at 21:55 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1902_

----

If apps need to do more than a few milliseconds of work they will want to do it on a background thread so that they don't miss the frame deadline.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [collinjackson](https://github.com/collinjackson)**
_Monday Nov 02, 2015 at 21:56 GMT_

----

/cc @abarth

**Comment by FlutterIssues** [comment]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Monday Nov 02, 2015 at 23:12 GMT_

----

yup! :)

**Comment by FlutterIssues** [comment]
<a href="https://github.com/eukreign"><img src="https://avatars.githubusercontent.com/u/69960?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eukreign](https://github.com/eukreign)**
_Tuesday Nov 03, 2015 at 04:03 GMT_

----

When implementing this feature keep in mind any implications it may have for this other feature:
https://github.com/flutter/engine/issues/130

**Comment by krisgiesing** [comment]
Jason has implemented this now, closing.
