### ISSUE TITLE
ideviceinfo returned an error: ERROR: Could not connect to lockdownd, error code -8

### ISSUE THREAD

**Issue by shashkiranr** [flutter/flutter#24600]
Hi I am getting this error every single time when running the flutter app using usb debugging almost all the time. running flutter clean works sometimes. I would have to reconnect the usb cable  for the app to run again.

```
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -8
```

```
flutter doctor -v

[✓] Flutter (Channel master, v0.11.7-pre.52, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.11.7-pre.52 at /Users/shashi/flutterNbeta
    • Framework revision 79b5e5bc8a (2 days ago), 2018-11-19 10:37:55 +0100
    • Engine revision cebde437a1
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/shashi/Library/Android/sdk
    • Android NDK at /Users/shashi/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel XL        • HT6AL0200842       • android-arm64 • Android 9 (API 28)

```

**Comment by SimpleMei** [comment]
"Xcode Command Line Tools" are installed?

**Comment by NemOry** [comment]
I'm having the same issue.

**Comment by wanghuajian620** [comment]
在项目目录下执行 flutter doctor -v，看有哪些出错了，该更新更新，该安装安装。详细[https://www.yuque.com/wanghuajian620/mnrxri/psp8te](url)

**Comment by Pretended** [comment]
应该是你之前开启的模拟器没有正常关机而是直接退出导致的，重启大法或者重开模拟器关机就行

**Comment by Changzw** [comment]
follow this, one by one
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.2)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/changzhongwei/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[!] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

**Comment by wonderLiu** [comment]
> I don't not why. But I solved it with restart Computer or run:
> 
> ```
> brew update
> brew uninstall --ignore-dependencies libimobiledevice
> brew uninstall --ignore-dependencies usbmuxd
> brew install --HEAD usbmuxd
> brew unlink usbmuxd
> brew link usbmuxd
> brew install --HEAD libimobiledevice
> brew install ideviceinstaller
> ```

it solved my problem.Thanks.

**Comment by sm9i** [comment]
> 我不是为什么。但我用重启计算机解决了它或运行：
> 
> ```
> brew update
> brew uninstall --ignore-dependencies libimobiledevice
> brew uninstall --ignore-dependencies usbmuxd
> brew install --HEAD usbmuxd
> brew unlink usbmuxd
> brew link usbmuxd
> brew install --HEAD libimobiledevice
> brew install ideviceinstaller
> ```

为什么 我的不行？已经试过好多次了

**Comment by DarranFan** [comment]
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17
Who can help me resolve this question

**Comment by LDKFighter** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.5 18F118d, locale zh-Hans-CN)
⣷Unhandled exception:
Exception: ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:141:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:156:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:110:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:171:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:99:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:694:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by LDKFighter** [comment]
> ideviceinfo returned an error:
> ERROR: Could not connect to lockdownd, error code -17
> ![image](https://user-images.githubusercontent.com/23433152/57368078-e1f17980-71bc-11e9-8f0a-58d4ba312186.png)
> 
> Who can help me resolve this question
> 
> I've reconfigured the environment twice

解决了吗？

**Comment by sm9i** [comment]
> > ideviceinfo returned an error:
> > ERROR: Could not connect to lockdownd, error code -17
> > ![image](https://user-images.githubusercontent.com/23433152/57368078-e1f17980-71bc-11e9-8f0a-58d4ba312186.png)
> > Who can help me resolve this question
> > I've reconfigured the environment twice
> 
> 解决了吗？

没解决，但是我删掉了flutter 环境 重新下载 就ok了

**Comment by DarranFan** [comment]
我现在不用安卓那个开发工具了直接用vscode了，现在没有这个问题了。谢谢了




| |
e1.inquiries@ef.com
邮箱：fanda918620986@126.com
|

Signature is customized by Netease Mail Master

On 05/17/2019 14:20, sm9i wrote:

ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17

Who can help me resolve this question
I've reconfigured the environment twice

解决了吗？

没解决，但是我删掉了flutter 环境 重新下载 就ok了

**Comment by Hamasn** [comment]
> > > ideviceinfo returned an error:
> > > ERROR: Could not connect to lockdownd, error code -17
> > > ![image](https://user-images.githubusercontent.com/23433152/57368078-e1f17980-71bc-11e9-8f0a-58d4ba312186.png)
> > > Who can help me resolve this question
> > > I've reconfigured the environment twice
> > 
> > 
> > 解决了吗？
> 
> 没解决，但是我删掉了flutter 环境 重新下载 就ok了

I have the same issue and didn't figure it out even reinstall the flutter environment.

**Comment by NadeemHakim** [comment]
On MacOS using Android Studio kept getting the same error, 

1. Removed the USB Device
2. Closed all Emulator and iOS Simulator 
3. Run Flutter Doctor 
4. Connected USB Device 

It started working, weird but It worked for me 

Same for working on Emulator
1. Removed the USB Device
2. Closed all Emulator and Simulator 
3. Run Flutter Doctor 
4. Open a new emulator or iOS Simulator

It will work. 

Please give it a try

**Comment by pradeep-wynk** [comment]
It 

> I don't not why. But I solved it with restart Computer or run:
> 
> ```
> brew update
> brew uninstall --ignore-dependencies libimobiledevice
> brew uninstall --ignore-dependencies usbmuxd
> brew install --HEAD usbmuxd
> brew unlink usbmuxd
> brew link usbmuxd
> brew install --HEAD libimobiledevice
> brew install ideviceinstaller
> ```

This worked flawlessly

**Comment by christopherfujino** [comment]
We should be handling this exception in the flutter tool

**Comment by Caponigri** [comment]
> I got this because I had an iPhone plugged into my laptop that was busy with a system update. When I unplugged the device, Flutter could see the simulator.
> 
> My error code was
> 
> > ideviceinfo returned an error:
> > ERROR: Could not connect to lockdownd, error code -21

I went crazy, thinking I did something wrong, turns out my iPad charging was the issue.

**Comment by christopherfujino** [comment]
This has been resolved with https://github.com/flutter/flutter/pull/38629

**Comment by dongzhixuanyuan** [comment]
> I got this because I had an iPhone plugged into my laptop that was busy with a system update. When I unplugged the device, Flutter could see the simulator.
> 
> My error code was
> 
> > ideviceinfo returned an error:
> > ERROR: Could not connect to lockdownd, error code -21

When I connected  my android phone and iphone meanwhile, this problem happened. So I disconnected my Iphone ,so this problem solved.

**Comment by samfrank** [comment]
So I had a similar error, and the previous solution unfortunately did not work for me. All I did was run the `flutter clean` command then, run `flutter build ios`. That started the debug mode for iOS simulator at is is working again.

Hope this helps people
