### ISSUE TITLE
Implement plain rendering of typical items for both the underflow case as well as scrolling case.

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#24604]
Implement plain rendering of typical items for both the underflow case as well as scrolling case.

**Comment by xster** [comment]
Sorry, I'm not sure I understood what this meant.

**Comment by matthew-carroll** [comment]
I think this was for a Flutter version of `UITableView` and it's for rendering typical table cells, both in the case where cells exceed available screen real estate, as well as fewer items than the screen, and also zero items.

**Comment by xster** [comment]
ah ok, I'm gonna merge it into https://github.com/flutter/flutter/issues/19228
