### ISSUE TITLE
How to prevent the children redraw when pop to a TabBarView?

### ISSUE THREAD

**Issue by DreamBuddy** [flutter/flutter#24602]
In a TabBarView,when navigate to a new view,then pop,the TabBarView will redraw the TabBarView's children and call initState function.

Here's my demo.
[flutter-zhihu_zhuanlan.zip](https://github.com/flutter/flutter/files/2603732/flutter-zhihu_zhuanlan.zip)

Thanks flutter,it's very wonderful

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Just cache the result of the code in `initState` so that it doesn't matter when `initState` is called again.

If you need more details I'd suggest you ask on StackOverflow.
