### ISSUE TITLE
Google Sign In Multiple Environments

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/flutter#24614]
I have seperated my environments like this: https://iirokrankka.com/2018/03/02/separating-build-environments/

For the `google-service.json` and `google-servicse.plist` files, this works great. But the Google Sign In plugin requires to set app the `REVERSED_CLIENT_ID` in the `info.plist` file. Like explained here:
https://pub.dartlang.org/packages/google_sign_in

Currently the Google Sign In Part of my info.plist file looks like this:
```xml
<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<!-- TODO Replace this value: -->
				<!-- Copied from GoogleServices-Info.plist key REVERSED_CLIENT_ID -->
				<string>com.googleusercontent.apps.91580493580-jog6r3obse3pel9su1npbb0tc8nkerfp</string>
				
				<string>fb1874940532597453</string>
			</array>
		</dict>
	</array>
```
But heres the problem, i have three environments in my app. How do i change the `REVERSED_CLIENT_ID` based on the environment I am currently using?

Cheers,

Niklas

**Comment by zoechi** [comment]
SEO: flavor, flavors

**Comment by sdstolworthy** [comment]
Has there been any resolution on this? I'm running into this same issue.

**Comment by sdstolworthy** [comment]
Okay, well, I had a "doh" moment. You can get around this issue by simply using a variable after the `CFBundleURLSchemes` key, like so: 
```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>$(GOOGLE_INFO_URL)</string>
			</array>
		</dict>
	</array>
```

Then, you just need to define the User Variable in xcode, and voila, dynamically updating sign in url.

**Comment by HerrNiklasRaab** [comment]
@sdstolworthy Just had the same scenario, with another project. I googled and found my question again and your answer. This is the correct solution. Thank you!

For everyone reading this. It only works if you set up flavors like this: https://medium.com/@matt.goodson.business/separating-build-environment-configurations-in-flutter-with-firebase-doing-it-the-right-way-c72c3ad3621f
