### ISSUE TITLE
TextField's IntrinsicWidth should take cursor into account

### ISSUE THREAD

**Issue by sma** [flutter/flutter#24612]
When computing the intrinsic size, I think, the cursor width should be taken into account so that the text field doesn't scroll if the cursor is at the end. I made the cursor very wide to illustrate the point. The text field below contains `12345` and is sized using an `InstrinsicWidth` widget. The `1` has been scrolled to the left to make room for the cursor. The same effect occurs with a "normal" cursor, but is barely visible.

![image](https://user-images.githubusercontent.com/14989/48845299-6d588900-ed9c-11e8-95e0-e4141d7935c9.png)

If you consider this behavior "by design", a way to add a width and/or height offset to the intrinsic widgets would be a workaround to get rid of the scrolling.

## Output of flutter doctor

```
[✓] Flutter (Channel master, v0.11.10-pre.1, on Mac OS X 10.14.1 18B75, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)
```

**Comment by HansMuller** [comment]
Sounds very reasonable, thanks for the report!

**Comment by justinmc** [comment]
Fixed with the above PR!  Thanks for filing this.
