### ISSUE TITLE
Create an iOS or Android library for native apps, that happens to use Flutter

### ISSUE THREAD

**Issue by dodongo** [flutter/flutter#24621]
Hoping to get more eyes on this question: https://stackoverflow.com/questions/53348524/integrate-flutter-into-cocoatouch-sdk. Does my approach seem ok here? Is the ability to integrate flutter into iOS or Android frameworks a goal of the project?

**Comment by zoechi** [comment]
@Hixie

**Comment by dnfield** [comment]
Is this the same as https://github.com/flutter/flutter/issues/26099?

**Comment by jmagman** [comment]
@xster This seems like a duplicate of https://github.com/flutter/flutter/issues/39027.

**Comment by xster** [comment]
It is. Let's dedup.
