### ISSUE TITLE
Firebase Dynamic Link doesn't clear the Link on Android

### ISSUE THREAD

**Issue by diegoveloper** [flutter/flutter#24629]
From stackoverflow by Dario : https://stackoverflow.com/questions/53418686/dynamic-link-is-not-cleared-after-retrieving

> In the main function the retrieveDynamicLink is called and the link is handled, as well as every time the app is resumed a lifecycle listener calls retrieveDynamicLink again and handles the link.
> 
> The plugin calls the android method: `getDynamicLink(registrar.activity().getIntent())`, and the documentation states that this method should clean the intent to make any other call return null until the app is open/resumed from another link.
> 
> But that's not what is happening, not always at least.
> 
> If I open the app from a dynamic link, switch to another app, and then go back to the app, the `retrieveDynamicLink` call returns the link again. If I originally open the app from its icon that does not happen.
> 
> Does anyone have any suggestion?
> 
> I'm using `firebase_dynamic_links: ^0.1.0+1` on Flutter `0.11.7`
>

**Comment by diegoveloper** [comment]
I can repo this issue, looks like it's an issue with the current Android Firebase Dynamic Library 
```
api 'com.google.firebase:firebase-dynamic-links:16.1.2'
```
This method specifically : https://github.com/flutter/plugins/blob/e96fb0c350328ff77baae758b6dc70797117ac98/packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java#L62

I tried to use a workaround saving the lastClickTimeStamp : 

https://github.com/diegoveloper/plugins/blob/master/packages/firebase_dynamic_links/android/src/main/java/io/flutter/plugins/firebasedynamiclinks/FirebaseDynamicLinksPlugin.java#L62

But the issue persist because  PendingDynamicLinkData data  always return the data of the first link clicked.
Event If I open a different dynamic link the result is always the first.

**Comment by ninnepinne** [comment]
Hello, not a proper solution, but I noticed that adding a delay between the resume event and actually getting the dynamic link seems to solve the problem.

I'm using 500ms.

Must be some kind of race condition involved.

The iOS implementation actually suffered from the same (similar) issue before:
[https://medium.com/@diegoveloper/flutter-firebase-dynamic-link-6f1b79278ce0](https://medium.com/@diegoveloper/flutter-firebase-dynamic-link-6f1b79278ce0)

Back then, the Android worked as expected.
A bit funny that the bug jumped the platform boundary.
Some bugs are not easily crushed...

**Comment by p02diada** [comment]
I am also facing the same issue. Anyone has a solution for this ???

**Comment by michealchow2324** [comment]
is there any updates now? I am still facing this even if i added a delay for 500ms for my android device

**Comment by kbrmimbyl** [comment]
Because of this problem I'm forced not to call `FirebaseDynamicLinks.instance.retrieveDynamicLink()` more than once in a session. With the app in the background, even if a new dynamic link is clicked, it's  stubbornly returning the one it fetched at app launch.

**Comment by vpramoth** [comment]
Is there a way to use native android libraries to retrieve dynamic links instead of this pugin in flutter?

**Comment by kbrmimbyl** [comment]
I guess that's what the plugin is supposed to do.

**Comment by jherencia** [comment]
Hello, we fixed this for android in this fork:
https://github.com/mrmilu/plugins/commit/81fd51cd6693fc98d69798839a5bb885ecf722aa

and we are going to work on this for iOS next week so we'll be able to do a PR.

**Comment by bparrishMines** [comment]
Closing this issue because it look like it has been fixed by https://github.com/flutter/plugins/pull/1569.
Lmk if you still run into this bug

**Comment by AndroidNils** [comment]
Still have this problem in 0.5.0+1 :/

**Comment by kroikie** [comment]
@diegoveloper

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/569. Any further collaboration will be done there.
