### ISSUE TITLE
Support desktop, already posible but not native in flutter

### ISSUE THREAD

**Issue by MendyMarcus** [flutter/flutter#24638]
Buy or partner with https://feather-apps.com/  to continue development and support it natively within Flutter

Progressive Web Apps would be nice too (with Dart Angular)

This would make flutter the place for one code base for all platforms

**Comment by sma** [comment]
FYI, there is also https://github.com/google/flutter-desktop-embedding and https://github.com/Drakirus/go-flutter-desktop-embedder

**Comment by zoechi** [comment]
Currently there are no plans to officially support desktops or browser besides the community initiative mentioned by @sma
