### ISSUE TITLE
scaffoldBackgroundColor ignores Colors.black12  - Colors.black87

### ISSUE THREAD

**Issue by volgin** [flutter/flutter#24630]
origin/master

This renders correctly:  
```dart
theme: new ThemeData.dark().copyWith(
        scaffoldBackgroundColor: Colors.red
),

```
Any value from `Colors.black12` to `Colors.black87` renders as black.

Workaround: use, for example, `Color.fromARGB(255, 34, 34, 34)`.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by volgin** [comment]
Ran doctor with no emulator:

[✓] Flutter (Channel master, v0.11.10-pre.2, on Mac OS X 10.14 18A391, locale
    en-US)
    • Flutter version 0.11.10-pre.2 at /Users/andreivolgin/flutter
    • Framework revision b55e52c6f7 (27 hours ago), 2018-11-21 15:48:23 -0500
    • Engine revision 1e37b99ac0
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/andreivolgin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by jason-simmons** [comment]
`Colors.black12`/`black87`/etc. are translucent colors.  A scaffold background using one of those colors will be blended with the opaque black background of the rendering surface, resulting in black output.

**Comment by zoechi** [comment]
Sounds like a support request that was answered.
