### ISSUE TITLE
cant run newest flutter code in a ios project add to flutter

### ISSUE THREAD

**Issue by manondidi** [flutter/flutter#24644]
i make a flutter module,
then add into a exiting android project ,it work fine
but i add into a exiting ios project,and run ios app
but it not the newest flutter module code,  about a week ago,
how can i get newest code? 
i try to run pod install in ios project
flutter clean in flutter module
delete flutterinstalldir/bin/cache?
how can i get newest flutter module code

**Comment by manondidi** [comment]
use  flutter create -t module flutter_module

i see in  .gitignore
.android/
.ios/

.ios and .android will be ignore  when i commit  
how can i generate   .ios and .android

**Comment by zoechi** [comment]
I saw it just mentioned on another issue that `flutter packages get` is supposed to recreate `.iso` and `.android`. Please check.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
