### ISSUE TITLE
How to do hot debug on my old project after importing flutter？

### ISSUE THREAD

**Issue by Yewenyu** [flutter/flutter#24646]
I have an old project and successfully imported flutter, but I can only do Hot reload on Runner. 
I want to do Hot reload on my old project. 
Could you please help me？
Thank you very much.

**Comment by zoechi** [comment]
With "old project" you mean a native Android project?
I don't think that is supposed to work. Hot reload is only supported for Dart code.

**Comment by YourMelody** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

**Comment by YourMelody** [comment]
flutter attach

**Comment by Yewenyu** [comment]
> With "old project" you mean a native Android project?
> I don't think that is supposed to work. Hot reload is only supported for Dart code.

Sorry, I'm not good at English, I mean that the existing project for ios.
I want to use Hot reload in this project.
Is flutter debug started from 'Runner. Xcodeproj'? If so,
I want to change this file to my existing project file 'myproject.xcodeproj'.

**Comment by Yewenyu** [comment]
> https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps flutter attach

Yes, I've done this, but what I want is that when I use flutter debug, I also want to debug with my existing projects, not just flutter projects

**Comment by YourMelody** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps  这篇文章最后有写如何在iOS中使用Flutter并且启动hot reload。在创建的flutter module目录下终端执行flutter attach，Xcode运行工程，就可以热加载了。想刷新直接在终端按r，想重载按R。不知道这是不是你想要的结果。

**Comment by Yewenyu** [comment]
> https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps 这篇文章最后有写如何在iOS中使用Flutter并且启动hot reload。在创建的flutter module目录下终端执行flutter attach，Xcode运行工程，就可以热加载了。想刷新直接在终端按r，想重载按R。不知道这是不是你想要的结果。

是的，这是我想要的，万分感谢
