### ISSUE TITLE
Flutter refresh map after come back from second screen

### ISSUE THREAD

**Issue by spartakos87** [flutter/flutter#24654]
I have a Flutter app which in home screen I use google map. At the begin, I call Firebase to take the places which I have already input. Then the user can add a new place if double in the map this lead him to SecondScreen. The user input title, story, and photo. I have and another screen where the user can view info for existing marker where can also delete it. My problem is when user input or delete marker and come back to the home page, in the map, the places are not refreshed and I see that the Firebase is not called again. How can I solve this problem? The Firebase is called in MapsDemo class My code:

https://gist.github.com/spartakos87/f6d472aef0146e2bb7d42b3ddb982fa0?fbclid=IwAR3jBDyIVF6RwP12URO4B2kAR3sBxMeZzBb9qgi0GYyUsgfHVPWECwmef0Q

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
