### ISSUE TITLE
Problem run with --release --no-track-widget-creation flags, android studio

### ISSUE THREAD

**Issue by Dn-a** [flutter/flutter#24655]
hi guys,
when run with `--release and --no-track-widget-creation flags` i have this result:
 
```
Initializing gradle...
Resolving dependencies...
Launching lib\main.dart on LG G2 in release mode...
Gradle task 'assembleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

_Originally posted by @Gyorgio88 in https://github.com/flutter/flutter/issues/20260#issuecomment-440898843_

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by Gyorgio88** [comment]
I solved thus https://github.com/flutter/flutter/issues/20260#issuecomment-410713323
However i will soon  add output of doctor -v

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by Dn-a** [comment]
@zoechi I have the same problem on stable version 1.0...I apply this fix [#20260 (comment)](https://github.com/flutter/flutter/issues/20260#issuecomment-440898843)

**Comment by zoechi** [comment]
@Dn-a 1.0 is quite old. It would be more interesting if you're still seeing this with latest `master`.

**Comment by Dn-a** [comment]
@zoechi ok, thanks.

**Comment by zoechi** [comment]
```
flutter channel master
flutter doctor
```

**Comment by Dn-a** [comment]
I switched to the version Channel master  v1.2.3-pre.21.
same problem
```
Could not find an option named "track-widget-creation".
Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Finished with error: Gradle task assembleRelease failed with exit code 1
```

**Comment by LaksamanaGuntur** [comment]
> @zoechi
> I switched to the version Channel master v1.2.3-pre.21.
> same problem
> 
> ```
> Could not find an option named "track-widget-creation".
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
> Finished with error: Gradle task assembleRelease failed with exit code 1
> ```

same problem here
