### ISSUE TITLE
`flutter run test/widget_test.dart` no longer works

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#24650]
(I discussed this with @jonahwilliams already, but I'm filing this to make sure we're tracking it.)

`flutter run test/widget_test.dart` is broken after the recent test_api changes.  Attempting it will hit various runtime exceptions such as:

> NoSuchMethodError: The method 'test' was called on null.
> NoSuchMethodError: The method 'setUp' was called on null.
> NoSuchMethodError: The method 'tearDown' was called on null.

[We document that people can use `flutter run` on their widget tests](https://flutter.io/docs/testing) to help debug widget tests, so this should be expected to work.

**Comment by jonahwilliams** [comment]
I'll put together documentation on how to make this work. In general:

```
import 'package:flutter_test/flutter_test.dart' hide group;
import 'package:test/test.dart' show group;

void main() {
  group('..', () {
    /// Tests
  });
}
```

**Comment by zoechi** [comment]
What is the reasoning behind that.
Does `group` from `flutter_test` not work when run on a device with `flutter run`?

**Comment by jonahwilliams** [comment]
Correct. The difference is the `group` method exposed by package test includes fallback logic to allow self-invoking tests. This also includes a larger set of dependencies, and isn't useful for "regular" flutter tests. 

Highly technical explanation:
```
group(...) {
  if (someEnvNotSetup) {
    setUpEnv();
  }
  real.group(...);
}
```

We could get around this by running the `flutter run testfile` through a test entry-point like we do for normal flutter tests. This _might_ require an additional flag or separate command, or it might not if setting up the test env has no side effects for a normal debug mode flutter run

**Comment by zoechi** [comment]
I think it's worth investigating to find a way so that imports don't need to be changed between `flutter run` and `flutter test` runs.

**Comment by jonahwilliams** [comment]
agreed. I think the problem isn't so much the imports, but that the solution is completely unintuitive.

**Comment by Hixie** [comment]
Why can't we just run the callbacks directly? I don't understand what needs to be set up.

**Comment by Hixie** [comment]
(I mean, in test_api, why can't `group('', foo)` just call `foo()`, at least if there's no test framework loaded.)

**Comment by jonahwilliams** [comment]
group/test and friends require a Declarer to set themselves up. This manages the current state of the tests and handles communication with the command line/tracks outstanding callbacks and such

 I think the solution is for `flutter_test` to provide the same capability as package:test, namely to handle setting up the Declarer when there isn't one in the current zone.

**Comment by jonahwilliams** [comment]
Update: I've found that it is possible to restore the ability to run tests directly without increasing dependency count or modifying the entrypoints. Working this into a small PR in the next few days

**Comment by adalberht** [comment]
hi @jonahwilliams, @jamesderlin, any news on this?
I tried running widget tests with `flutter run -t <path_to_file_name>` and got: 
```
E/flutter ( 4836): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 4836): #1      test (package:test_api/test_api.dart:101:13)
E/flutter ( 4836): #2      testWidgets (package:flutter_test/src/widget_tester.dart:66:3)
```

Is this expected?
