### ISSUE TITLE
Firebase Storage catch error when file that does not exist

### ISSUE THREAD

**Issue by kataklysmo** [flutter/flutter#24652]
Can not handle this error, just try to get some nonexistent image like this:

`  StorageReference ref =   FirebaseStorage.instance.ref().child("nothinghere.jpg");`

The triggered exception is 

> E/StorageException(26987): StorageException has occurred.
> E/StorageException(26987): Object does not exist at location.
> E/StorageException(26987):  Code: -13010 HttpResult: 404
> E/StorageException(26987): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object"  }}

Can't be handled using a "generic" try catch also.

**Comment by zoechi** [comment]
It looks like these exceptions are not forwarded to Dart yet in this plugin.
Merging with #18547
