### ISSUE TITLE
About Flutter Doc Support Chineses

### ISSUE THREAD

**Issue by VFiee** [flutter/flutter#24668]
I am a Chinese developer, just ask if there is any plan to support Chinese documents...
The address is as follows: https://docs.flutter.io/flutter/dart-ui/dart-ui-library.html

**Comment by Hanggi** [comment]
a big project, lol...

**Comment by lishuhao** [comment]
It’s better to learn English than to wait for someone else to translate.

**Comment by TyroneZeka** [comment]
can anyone tell me how to setup Flutter in China
