### ISSUE TITLE
`flutter doctor` fails with error `flutter/bin/cache/dart-sdk/bin/dart: No such file or directory` on Linux

### ISSUE THREAD

**Issue by sj4nes** [flutter/flutter#24666]
## Steps to Reproduce

I'm following the instructions detailed at https://flutter.io/docs/get-started/install/linux :

1. Downloaded the Linux flutter archive flutter_`linux_v0.11.9-beta.tar.xz` to NixOS 17.09 and unpacked it into `~/development`
2. added `~/development/flutter/bin` to the path with:
```
    cd ~/development
    export PATH=$PATH:`pwd`/flutter/bin
```
3. Tried to execute `flutter doctor` and it fails. No other progress or error messages are available.

## Logs

```
/home/sj4nes/development/flutter/bin/flutter: line 176: /home/sj4nes/development/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
```

So, is there some step completely missing from the Linux documentation?

**Comment by sj4nes** [comment]
Appears that there is going to be a long-term "impedance mismatch" with flutter tooling and NixOS:

https://github.com/NixOS/nixpkgs/issues/36759

**Comment by babariviere** [comment]
It's because you are using NixOS. The `dart` executable cannot find ld-linux, you will have to relink it with patchelf.
Here is some doc: https://nixos.org/patchelf.html

**Comment by jonahwilliams** [comment]
I'm not sure whether changes would need to be made to bin/flutter or whether there would have to be a special NixOS distribution of flutter. it doesn't seem that there is anything actionable for us here, and from the linked discussion it seems like this can be solved from the distribution itself.
