### ISSUE TITLE
Localizations no longer works after upgrade to the latest version of i18n plugin

### ISSUE THREAD

**Issue by LucioD** [flutter/flutter#24667]
Hi to all,
on a my Flutter app I use the **i18n plugin** for texts localizations, with two supported languages: Italian and English (the English is also the fallback language). **This localizations until a few days ago worked properly,** **but after the upgrade of the i18n plugin to the latest version 0.1.1 it stopped working**, and all the app's texts are now always displayed in English (the fallback language ) even if on my Android device the language is set to Italian ('it'), and before this upgrade the texts were correctly localized in Italian.

I did not change anything in the code, **but I realized that now the call `Localizations.localeOf (context)` always returns the 'en_' Locale**, even if on the device I set the French language or Italian language, or any other language other than English.

This is clearly a mistake. I'm not sure, but I think this error came out after upgrading to version 0.1.1 of the i18n plugin in my Android Studio (version 3.2.1) development environment.

## Steps to Reproduce

This is the interestings code:

```dart
@override
  Widget build(BuildContext context) {
    Locale currentLocale = Localizations.localeOf(context);
    String localizationLanguageCode = S.delegate.isSupported(currentLocale) ? currentLocale.languageCode : Config.defaultLanguageCode;
    print('currentLocale is: ${currentLocale.toString()}, currentLocale.languageCode is: ${currentLocale.languageCode}, localizationLanguageCode is: $localizationLanguageCode');
    return MaterialApp(
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(fallback: new Locale('${Config.defaultLanguageCode}', '')),
      home: Scaffold(
        appBar: _makeAppBar(context),
        body: FutureBuilder<List<Lesson>>(
          future: fetchLessons(http.Client(), selectedCourse, localizationLanguageCode),
          //future: listLessons,
          builder: (context, snapshot) {
            this.numBuild++;
            print('number of build of LessonsRoute: ${this.numBuild}...');
            if (snapshot.hasError)  {
              print('Snaphot has the following error: ${snapshot.error}');
              return Center(
                  child: Text('Snaphot has the following error: ${snapshot.error}')
              );
            } else {
              if (snapshot.hasData) {
                if (snapshot.data != null && courses != null) {
                  return ListViewLessons(lessons: snapshot.data, courses: courses);
                } else {
                  return Center(child: Text('snapshot.data is null or/and courses is null!'));
                }
              } else {
                return Center(child: CircularProgressIndicator());
              }
            }
          },
        ),
      ),
    );
  }
```
In the above code, the following instructions:
```
 Locale currentLocale = Localizations.localeOf(context);
 String localizationLanguageCode = S.delegate.isSupported(currentLocale) ? currentLocale.languageCode : Config.defaultLanguageCode;
 print('currentLocale is: ${currentLocale.toString()}, currentLocale.languageCode is: ${currentLocale.languageCode}, localizationLanguageCode is: $localizationLanguageCode');
```
Produces the following result:
`I/flutter ( 4432): currentLocale is: en_, currentLocale.languageCode is: en, localizationLanguageCode is: en

**But, on my device (Samsung Galaxy S5 with Android 6.0.1) the language is set to Italian, not to English!** See attached screenshots.

So, it seems clear that **the call to _Localizations.localeOf (context)_ returns a wrong result (always English Locale)**, which prevents localizations in other languages.

**What happened? How can I make the localizations of texts on my app work again?**

Thanks in advance for the help you want to give me.

## Flutter Doctor
```
[v] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Versione 10.0.17134.407], locale it-IT)
    • Flutter version 0.11.9 at c:\src\flutter
    • Framework revision d48e6e433c (2 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[v] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\lucio\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[v] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[v] Connected device (1 available)
    • SM G900F • 5fe4af7d • android-arm • Android 6.0.1 (API 23)

• No issues found!

```

![flutter_02](https://user-images.githubusercontent.com/6943849/48924494-3af07e00-eeb9-11e8-978b-1c6a51e8de53.png)

**Comment by zoechi** [comment]
There was a change in Flutter about how the locale is acquired but I think this should be reported in https://github.com/ilteoood/flutter_i18n/issues if this is the `i18n` plugin you are using.

**Comment by zoechi** [comment]
Can you please check with `master`. 
https://github.com/flutter/flutter/pull/24481 looks like it fixed something like that.

**Comment by rohan20** [comment]
I can no longer find the `flutter_localizations` package on pub. Has it been taken down?

**Comment by zoechi** [comment]
I don't think it ever was on `pub`. It's part of the Flutter SDK.
See https://flutter.io/docs/development/accessibility-and-localization/internationalization how to add it to `pubspec.yaml`.

**Comment by LucioD** [comment]
> There was a change in Flutter about how the locale is acquired but I think this should be reported in https://github.com/ilteoood/flutter_i18n/issues if this is the `i18n` plugin you are using.

No, I think there is a misunderstanding on the Flutter i18n plugin. I'm using this Flutter I18N plugin: https://plugins.jetbrains.com/plugin/10128-flutter-i18n, that does not seem the same of this https://github.com/ilteoood/flutter_i18n.
So, I think I'll have to move this issue here: https://github.com/long1eu/flutter_i18n/issues.
It's right?

**Comment by zoechi** [comment]
Yes, please move the issue there.
Referring to https://github.com/flutter/flutter/issues/24747 might help which probably explains what broke flutter_i18n
