### ISSUE TITLE
Displaying list of items, and at the bottom an input field

### ISSUE THREAD

**Issue by jelenacarnegie** [flutter/flutter#24662]
I'm trying to implement something like this:

<img width="360" alt="screen shot 2018-11-22 at 5 48 01 pm" src="https://user-images.githubusercontent.com/17471080/48915470-0c55b180-ee7f-11e8-8e7f-4402f483d118.png">

First element in Column is a list of comments, and second one is an input field.
List should be scrollable.

The problem is, that I can not achieve to move input field above keyboard, when user wants to type in a comment. Input field stays below keyboard.

Is there any guideline for problems like this(list + input field)?
I could not find any.

Thank you!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
