### ISSUE TITLE
need to get chrome powered webview inside flutter app?

### ISSUE THREAD

**Issue by iamprakash13** [flutter/flutter#24671]
i need chrome powered webview tab inside flutter app. 
have look at this link
[custom webview with action menus](https://stackoverflow.com/questions/53445003/how-to-get-chrome-powered-webview-in-flutter)
i need desktop version of particular webpage i tried with changing User Agent.

my flutter doctor:
``` Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] VS Code (version 1.29.1)
[√] VS Code, 64-bit edition (version 1.26.1)
[!] Connected device
    ! No devices available
```

help me find solution. Thanks in advance
@iampawan @tensor-programming @sgraham @ianloic @kevmoo @paulcbetts @PoojaB26

**Comment by awazgyawali** [comment]
Maybe this is what you want
https://pub.dartlang.org/packages/flutter_custom_tabs

**Comment by sma** [comment]
In a few days/weeks/months (I don't know) you'll officially get this: https://github.com/flutter/plugins/tree/master/packages/webview_flutter

**Comment by iamprakash13** [comment]
thanks

**Comment by thedejifab** [comment]
> In a few days/weeks/months (I don't know) you'll officially get this: https://github.com/flutter/plugins/tree/master/packages/webview_flutter

Is this available yet? @sma
