### ISSUE TITLE
we have one too many _embedder.yaml files

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2468]
There's one in the flutter package and one in the sky_engine one. We can only support one at a time - it's a first one wins situation.

We should delete one, and add it's info to the other. It'll need to define the embedder libraries and set up the analysis options (super mixins, and all the analysis options from the `flutter analyze` command). Possibly kill the sky_engine one?

/cc @pq

**Comment by devoncarew** [comment]
flutter: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/_embedder.yaml
sky_engine: https://github.com/flutter/engine/blob/master/sky/packages/sky_engine/lib/_embedder.yaml

**Comment by pq** [comment]
:+1: 

> Possibly kill the sky_engine one?

Seems reasonable to me but defer to @Hixie in case he feels otherwise.  (He reviewed @johnmccutchan 's change to land the sky_engine one.)

**Comment by johnmccutchan** [comment]
We cannot kill the sky_engine one because it is the package actually providing the SDK definition files.

**Comment by johnmccutchan** [comment]
@sethladd

**Comment by Hixie** [comment]
We're probably going to want per-package analysis options control eventually. In the meantime, though, it's fine to put the stuff in the sky_engine one.

**Comment by pq** [comment]
> We're probably going to want per-package analysis options control eventually. 

(Derail alert.)  Could you elaborate?  What packages will get different configurations?  And roughly how do you anticipate they'll differ?

**Comment by Hixie** [comment]
For example, some packages care about types a lot, and would want to get a lint for any case where `dynamic` was implied. Other packages are written by people who come from a more lax approach to types and would not want that lint.

**Comment by Hixie** [comment]
Or a more immediate one for Flutter: Some packages are near 100% dartdoc coverage, and we'd want to turn on the warning. Others are near 0%, and we'd want to wait.
