### ISSUE TITLE
BitmapDescriptor.fromAsset not working google maps flutter markeroptions

### ISSUE THREAD

**Issue by thebagchi** [flutter/flutter#24686]
`MarkerOptions` from `BitmapDescriptor.fromAsset` not working.

In `FLTGoogleMapController`'s `initWithFrame` `_registrar` is not set.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and more details about how to reproduce (minimal runnable reproduction).

**Comment by thebagchi** [comment]
`
flutter doctor -v
[✓] Flutter (Channel beta, v0.11.11, on Mac OS X 10.14.1 18B75, locale en-IN)
    • Flutter version 0.11.11 at /Users/sandeep/flutter
    • Framework revision e7680128af (16 hours ago), 2018-11-27 21:33:50 -0500
    • Engine revision be973ea196
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/sandeep/Library/Android/sdk
    • Android NDK at /Users/sandeep/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
`

Sample code:
`
class MapsDemoState extends State<MapsDemo> {
  GoogleMapController _controller;
  double _latitude;
  double _longitude;
  ...
  _display() async {
    
    await _controller.addMarker(new MarkerOptions(
      draggable: false,
      alpha: 1.0,
      icon: BitmapDescriptor.fromAsset("assets/marker.png"),
      position: new LatLng(_latitude, _longitude),
      visible: true
    ));
      
    await _controller.moveCamera(CameraUpdate.newLatLngZoom(
      new LatLng(_latitude, _longitude), 16
    ));
  }
}
`

Root cause:
File --> google_maps_flutter/ios/Classes/GoogleMapController.m

_registrar not set in FLTGoogleMapController in method initWithFrame

**Comment by kunit1** [comment]
I think this was already fixed [PR](https://github.com/flutter/plugins/pull/943)

**Comment by zoechi** [comment]
The PR was merged. So I assume this is fixed.
