### ISSUE TITLE
Keeping PageView index

### ISSUE THREAD

**Issue by pblinux** [flutter/flutter#24682]
Hi

I have a PageView to show 4 pages and a BottomNavigationBar to switch them. I'm having troubles with the PageController.

In any page, I navigate to a new Screen, but when get back, the PageView return to the initial page, no to the last page.

Here is how I using the PageView

https://gist.github.com/pblinux/e158151f4d8216acdbd482b2ba3ec8c4

In the DashboardScreen for example, I navigate to a new screen like:

`Navigator.of(context)
            .push(MaterialPageRoute(builder: (context) => CodeScreen()))`

This behaviour is normal? I need to use something like Redux or Bloc Pattern to achieve/fix this?

Thanks.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
