### ISSUE TITLE
Need support for android map utils library

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#24689]
Please provide features of following library - 
https://github.com/googlemaps/android-maps-utils

**Comment by ManojMM026** [comment]
any update on this? @zoechi

**Comment by KohlsAdrian** [comment]
there is this package https://pub.dev/packages/maps_toolkit
but it is incomplete, im creating a new and im going to provide it hear, as it going to be near to close this issue here soon

**Comment by KohlsAdrian** [comment]
https://pub.dev/packages/google_maps_utils

I made these package with official converted code from OP link

needing more features, request I'll do it the quickest possible

**Comment by pitgas** [comment]
can you add routeboxer?

**Comment by cyanglaz** [comment]
Closing as dup of https://github.com/flutter/flutter/issues/50636
