### ISSUE TITLE
Provide card details or make a transaction using NFC

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#24690]
Please provide a support to read card details or make a transaction using NFC

**Comment by kunit1** [comment]
This plugin might be a good starting point for you
[Flutter NFC Reader](https://pub.dartlang.org/packages/flutter_nfc_reader#-readme-tab-)

**Comment by viratshukla** [comment]
> This plugin might be a good starting point for you
> [Flutter NFC Reader](https://pub.dartlang.org/packages/flutter_nfc_reader#-readme-tab-)

From this, I will get data in Bytes, but how to deal with data, recognize if its a card, then getting corresponding data like card details. It would be better if a dedicated plugin would be available to use. Like following library - https://github.com/pro100svitlo/Credit-Card-NFC-Reader

**Comment by timsneath** [comment]
We don't plan to build a package like this ourselves, but there are some great third-party payment apps that support this. For example: https://developer.squareup.com/docs/reader-sdk/flutter

Thanks for your suggestion!
