### ISSUE TITLE
Unable to import alarm manager in Native android side

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#24691]
I imported android alarm manager plugin in dart and in dart side evrything is fine. But, when I tried application overrides for giving the AlarmService a callback to call in the application's onCreate method. I'm unable to import the required plugin in java side.
Here is my Application class in java from android app.
```dart
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.androidalarmmanager.AlarmService;//Here lies the issue unable to import.

public class Application extends FlutterApplication implements PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        AlarmService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```
The line `import io.flutter.plugins.androidalarmmanager.AlarmService` showing error as it doesn't have `androidalarmmanager.AlarmService `in `plugins` .Don't know what's the cause.

**Comment by zoechi** [comment]
#23822, #22117, #17914 might be related

**Comment by xster** [comment]
Application referencing plugins' Java code has been added in terms of support in 1.12.
