### ISSUE TITLE
Misleading in the firebase for flutter tutorial 

### ISSUE THREAD

**Issue by shia86** [flutter/flutter#24693]
There was a misleading in the step 5 of [firebase for flutter](https://codelabs.developers.google.com/codelabs/flutter-firebase/#4).

> Save the file, then hot-reload your app.
 You should see the following app

The application won't shown up and will crash. Firebase needs to be setup according to the step 6-7.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2034](https://github.com/flutter/website/issues/2034) via [**ZenHub**](https://www.zenhub.com/)
