### ISSUE TITLE
Installation issue and not able to build for ARM32 iOS

### ISSUE THREAD

**Issue by JohanManders** [flutter/flutter#24698]
## Thanks

First I want to thank the Flutter team! I am using Flutter now for over a month and I love working with it on Windows 10. Building an app is almost an easy task now and it runs really fast. Love the hot reload feature, and the VSCode support. Building and distributing for Android is just perfect. 

## Issues

I have a freshly installed Mac OS X 10.14 with Xcode 10.1 and after installing Flutter and running 'Flutter doctor -v' I get the 

```
    X Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
```

error. I have read the #6207 issue information, but I think it is not related to my issue, because I use Mac OS X and not Linux. I have tried to reinstall and upgrading Flutter, but nothing seems to fix this error.

The error didn't seem to interfere with my work, everything seemed to be working fine, including testing and building for iOS Simulator (iPhone XR). But now I ran into a problem and I think it is related to my bug, but I cannot figure it out.

I tried to build for release and I can build for arm64(e), but not for armv7(s), because I get the following error:
```
Built to build/aot/.
Snapshotting (IOSArch.armv7) exited with non-zero exit code: -4
Snapshotting (IOSArch.arm64) exited with non-zero exit code: 0
cp: build/aot/App.framework: No such file or directory
error: cannot parse the debug map for 'build/aot/App.framework/App': No such file or directory
Failed to generate debug symbols (dSYM) file for build/aot/App.framework/App.
```

I have read about this error and I don't think it is related to xconfig files settings, also because without the armv7, the project does build.

I ran `Flutter clean` and `pod install` many times, but that is not the issue.

I currently use xcode project settings with legacy build settings, proposed in comment regarding issue [#20685](https://github.com/flutter/flutter/issues/20685#issuecomment-421511890). Using the new build settings and deleting the `Flutter.framework` does not build for me at all.

## Questions

- How can I fix the first issue found in `Flutter doctor`?
- How can I fix building for armv7(s)?
- Are the two issues related?

## Flutter doctor -v log

```
[!] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 0.11.9 at /Users/jm/development/flutter
    • Framework revision d48e6e433c (4 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

## Thanks again!

😃

**Comment by zoechi** [comment]
Looks like https://github.com/flutter/flutter/issues/14998#issuecomment-418596260

Can you please run in the Flutter install directory

```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```

**Comment by JohanManders** [comment]
Running the commands in the Flutter directory gave me:

`git clean`
Removed some packages.

`git stash save --keep-index`
No local changes to save

`git stash drop`
No stash entries found.

`git pull`
Already up to date.

`flutter doctor -v`
Building flutter tool...
Downloading...

```
[!] Flutter (Channel beta, v0.11.9, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 0.11.9 at /Users/johanmanders/development/flutter
    • Framework revision d48e6e433c (5 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/johanmanders/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[!] Connected device
    ! No devices available
```

**Comment by JohanManders** [comment]
@zoechi Is there something else I can try or should I accept this error and the fact that I cannot build 32bit iOS?

**Comment by mmcc007** [comment]
flutter on 32-bit iOS is supported. See #2089

**Comment by timsneath** [comment]
Are you still experiencing this problem, @JohanManders?

**Comment by JohanManders** [comment]
@timsneath after I couldn't build for 32-bit, I never tried again and only build for 64-bit.

**Comment by timsneath** [comment]
No problem. I'm sorry about how long it's taken us to reply to this, but I think at this stage it probably makes sense to close the issue down given all the changes that have taken place since v0.11, coupled with the fact that there aren't a bunch of "me too" replies on this bug. 

We're trying to work through the backlog of open bugs generated during our explosive growth, so that we can hopefully respond faster to new incoming bugs. Thanks for your patience -- we appreciate it!
