### ISSUE TITLE
How can I detect tap event of drawRect on flutter canvas?

### ISSUE THREAD

**Issue by Hanggi** [flutter/flutter#24694]
I draw a rect on flutter canvas by using CoustomPainter. How can I add a onTap/onPress event to this rect?

Must I calculate the axis positions of every rect to get the object of drawRect in panUpdate?

**Comment by fujingjunben** [comment]
you can wrap CustomPaint with GestureDetector.

**Comment by Hanggi** [comment]
@fujingjunben I have many many rects, how can I detect which rect am I onTapping?

**Comment by sma** [comment]
You have to create something like this -> https://gist.github.com/sma/c6a9111d58c3deb83711106cec6152ee on your own.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by AvatarDevs** [comment]
the linked gist is great until you're using some transforms. I'm trying to create a similar feature to google maps pins, but using a static image.

I have a pannable and zoomable custom painter of size 4096x4096 by wrapping it in PhotoView.customChild from the PhotoView Package.

My problem comes when i need the circles drawn by  CustomPaint to be tappable.

using the example gist linked above my Offsets of box.localToGlobal is always a value between the width or height of the screen size. Any suggestions on how to go about doing what i need?

**Comment by Hu-Wentao** [comment]
> 除非您使用某些转换，否则链接的要旨是非常棒的。我正在尝试创建与Google Maps Pins类似的功能，但使用的是静态图片。
> 
> 通过将其包装在PhotoView包的PhotoView.customChild中，我具有大小为4096x4096的可缩放和缩放的自定义画家。
> 
> 当我需要CustomPaint绘制的圆可点击时，我的问题就来了。
> 
> 使用链接在我的box.offsets上方的示例要点，始终是屏幕尺寸的宽度或高度之间的值。关于如何去做我需要的任何建议？

Did you succeed? How do you do that?

**Comment by Hu-Wentao** [comment]
> the linked gist is great until you're using some transforms. I'm trying to create a similar feature to google maps pins, but using a static image.
> 
> I have a pannable and zoomable custom painter of size 4096x4096 by wrapping it in PhotoView.customChild from the PhotoView Package.
> 
> My problem comes when i need the circles drawn by CustomPaint to be tappable.
> 
> using the example gist linked above my Offsets of box.localToGlobal is always a value between the width or height of the screen size. Any suggestions on how to go about doing what i need?

Did you succeed? How do you do that?

**Comment by nateshmbhat** [comment]
The package `touchable` is the perfect choice for this. You can give all kinds of gesture callbacks to individual shapes you draw on the screen ✅ 

Check it out here : 
[touchable](https://github.com/nateshmbhat/touchable)
