### ISSUE TITLE
APIs that take List<X> should take Iterable<X>

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#247]
<a href="https://github.com/ianloic"><img src="https://avatars.githubusercontent.com/u/604?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ianloic](https://github.com/ianloic)**
_Monday Nov 02, 2015 at 22:34 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1903_

----

I'm often finding myself using List.map to turn a list of data objects into a list of widgets as children or menu items. Every time so far I've forgotten to .toList(). Is there a reason that the APIs that need a list of things don't just take an Iterable?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Monday Nov 02, 2015 at 23:56 GMT_

----

/cc @Hixie 

We tried using Iterable at one point, but I don't remember when we ended up going back to List.  Ian do you remember?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 00:09 GMT_

----

I forget the details, but it was in fn2, so it might no longer matter. We can try again.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Tuesday Nov 03, 2015 at 01:54 GMT_

----

Bonus: using Iterable means you can use `yield` :)

**Comment by Hixie** [comment]
Well, one reason is that we need to have a list we can iterate over. If all we were getting was an Iterable, then every time one was passed in, we'd have to call toList() on it, and that would basically double the number of copies of all the widget lists.

**Comment by Hixie** [comment]
I don't really see a way to do this unless there's a way to get from a `<Widget>[]` literal to a `List<Widget>` via an `Iterable<Widget>` argument without paying the cost of a copy.

**Comment by abarth** [comment]
We do this for ScrollableList now.  We actually can pull the iterator lazily in many cases too.

**Comment by abarth** [comment]
We've decided not to do this in general.  There are some specific places that accept Iterable because they can work lazily.  In the cases, however, we'd need to pull everything from the iterable anyhow and it's more efficient if we do that as early in the processing as possible (e.g., just after the iterable is created with something like map).
