### ISSUE TITLE
Github API provides empty releases list.

### ISSUE THREAD

**Issue by Antiarchitect** [flutter/flutter#24701]
Using Github API I want to fetch releases list of Flutter (as I'm writing installing plugin for ASDF package manager). By reaching https://api.github.com/repos/flutter/flutter/releases get empty JSON Array.
For example, see: https://api.github.com/repos/kubernetes/kubernetes/releases

**Comment by gspencergoog** [comment]
Right, we don't release Flutter using GitHub.  Someone could probably could write something that produces that JSON array from our own release process, however, pointing to the downloadable cloud storage packages, but I'm not sure what that gets you.

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/releases *does* list our releases (Git tags), however.  I wonder what the difference between that and the JSON API is?

**Comment by jonahwilliams** [comment]
I'm not sure how our releases are created, but I know in the manual process there is an option to create  a "prerelease" which doesn't show up in the releases API call.

**Comment by Antiarchitect** [comment]
So only manual download and installing by hand or you have some other place you publish your releases that have usable API to list and get them?

**Comment by Hixie** [comment]
It's not exactly "supported" but here's what we use:
https://github.com/flutter/website/blob/master/src/_assets/js/archive.js
It downloads a JSON file that describes all our releases.

HTH.
