### ISSUE TITLE
improve the wording for the error about running outside of a project root

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2470]
From here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L109, we warn if a command is run outside of a project root. The error also mentions to not run the command from the flutter repo. We should only print that 2nd part if running from the flutter repo.

**Comment by zoechi** [comment]
Updated link https://github.com/flutter/flutter/blob/e54e53c13b92b74fc907ffe6547ad1b07d83e15d/packages/flutter_tools/lib/src/runner/flutter_command.dart#L623-L624

**Comment by asashour** [comment]
This seems to be already done.

https://github.com/flutter/flutter/blob/de0a5e086d484bff42be812dfeeb6a8a5000f913/packages/flutter_tools/lib/src/base/user_messages.dart#L263-L265

**Comment by amanv8060** [comment]
this looks like already done, @devoncarew. 

cc @TahaTesser

**Comment by devoncarew** [comment]
Thanks! Closing...
