### ISSUE TITLE
Comma separator in TextFormField

### ISSUE THREAD

**Issue by Simpler1** [flutter/flutter#24706]
How can the flutter gallery Material Text Fields demo be enhance to show a comma separator for the Salary field?

`flutter/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart
`

I can't find any example for how to display a comma separator in a TextFormField.  I've tried creating a custom inputFormatter, but then I'm having problems removing the comma when trying to store the value as a double.

Thanks in advance

**Comment by apinprastya** [comment]
https://stackoverflow.com/questions/50395032/flutter-textfield-with-currency-format

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by superManhee** [comment]
onChange: (value){
     var price = int.parse(value);
     var comma = NumberFormat('###,###,###,###');
     TextController.text = comma.format(price).replaceAll(' ', '');
}
