### ISSUE TITLE
where to find the offical guide put flutter in existed iOS project

### ISSUE THREAD

**Issue by tangmengze** [flutter/flutter#24718]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by tangmengze** [comment]
can't find any doc about it

**Comment by YourMelody** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

**Comment by zoechi** [comment]
Thanks @YourMelody

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
