### ISSUE TITLE
Darwin flutter test failures

### ISSUE THREAD

**Issue by jxson** [flutter/flutter#2471]
I am trying to run "flutter test" on OS X using my own built version of the flutter engine. It is kind of working but I think I missed something when building. My current error is: 

```
[FATAL:FontPlatformDataApple.cpp(81)] Check failed: false. 
```
### Steps to Reproduce
- Build flutter/engine as detailed in [CONTRIBUTING.md](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md) for OS X/Darwin.
  - [Desktop (Mac and Linux), for tests](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#desktop-mac-and-linux-for-tests)
- Checkout [jxson/reader#add-flutter-ui-tests](git@github.com:jxson/reader.git):
  - git clone git@github.com:jxson/reader.git
  - cd reader/flutter
- Run `flutter test --engine-src-path <path to built engine>`
### Flutter Version

```
$ flutter --version
Flutter from https://github.com/flutter/flutter.git (on alpha)
Framework: 2fe456bf957d5df792b716599aa6f21d98997228 (5 days ago)
Engine:    d474e9d2b60a9cb111c09844c10081b68bde9252

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.
```
### Logs

Verbose output for `flutter test ...`: https://gist.github.com/jxson/380a29a2b8e67fe0c124
### Crash Reports

https://gist.github.com/jxson/4963fa75ac4853b19dc2

**Comment by eseidelGoogle** [comment]
Thank you very much for the report Jason.  https://github.com/flutter/flutter/issues/1707 will also make it so you don't have to build your own.

**Comment by eseidelGoogle** [comment]
@chinmaygarde @tvolkert If we can repro this, seems we'll need to fix it before we can publish official binaries.

**Comment by jxson** [comment]
@eseidel thanks, I'm tracking the issue now as well.

**Comment by eseidelGoogle** [comment]
My understanding is `flutter test` works on Macs just fine these days. (FYI @cbracken @tvolkert)
