### ISSUE TITLE
Scaffold having a decoration field instead of just a backgroundColor

### ISSUE THREAD

**Issue by solnsumei** [flutter/flutter#24717]
Nice job on the flutter platform.

I have a recommendation though.

It will be nice to set a decoration property on the `Scaffold` for an app to have a uniform gradient or image background instead of trying to set decoration on containers on each page or screen?

Just a suggestion.
Thanks.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
