### ISSUE TITLE
Failed to create dart projects in IntelliJ IDEA version 18.3

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#24727]
In IntelliJ IDEA version 18.3, after updating the plug-in of dart, the problem of creating projects on dart from scratch arose: the operation "Loading Dart project templates ..." begins and continues indefinitely. Apparently there are simply no templates. But also error messages are absent.

**Comment by zoechi** [comment]
Are you using a proxy or are you behind a firewall?
Do you have a working internet connection when you try to create a project?
Does `flutter create foo` work when you execute it in a terminal window?

Please add the output of `flutter doctor -v`.

**Comment by micrcx** [comment]
1. I use Linux Mint, so there have never been any problems with a proxy or firewall. Over the past couple of years, I've constantly updated both IntelliJ IDEA and dart, and flutter, and plugins, and there were no problems.
2. There is no problem with the internet connection. How could I've installed IntelliJ IDEA and update all plugins without internet?
3. With flutter there are no problems at all, the project is being created. Unable to create a **dart** project (web, angular dart or console application, as it was before the update)

```
/home/michael_k/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.9, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] Connected device (1 available)

• No issues found!
Process finished with exit code 0
```

**Comment by zoechi** [comment]
> Unable to create a **dart** project

Then this should be reported in https://youtrack.jetbrains.com or https://github.com/dart-lang/sdk/issues

There is something fishy going on because `flutter doctor` does not recognize the Dart plugin.
You could try removing and re-adding the plugin, 
but as mentioned the issues for the Dart plugin are maintained elsewhere.

**Comment by zoechi** [comment]
moved to https://github.com/dart-lang/sdk/issues/35256
