### ISSUE TITLE
[warning] The method 'call' is not defined for the class 'Function' 

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2473]
I run this program through `flutter analyze`:

```
typedef void CallMe();

void main() {
  CallMe callme = () => print("Called.");
  callme();
  callme.call();
}
```

I get this warning:
`[warning] The method 'call' is not defined for the class 'Function'`

However, when I run the same code through `dartanalyzer`, I do not get the warning,even with the --warnings command line option.

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: 9ce6bff558e5952a5787ab3293413b5e11ee2cff (7 days ago)
Engine:    006a702b30182b7622f54c30f538f70df4398614
```

**Comment by eseidelGoogle** [comment]
@pq would probably know what's up.

**Comment by pq** [comment]
Yeah.  That comes from the `--enable-strict-call-checks` we're passing into `dartanalyzer`.  You can find some context here https://github.com/dart-lang/sdk/issues/21938.   I bet @stereotype441 can chime in with more details.

**Comment by sethladd** [comment]
I talked to @gbracha and we don't think this issue should be entwined with https://github.com/dart-lang/sdk/issues/21938

We'd like to know what the `--enable-strict-call-checks` actually means. Maybe @leafpetersen or @bwilkerson knows what this flag means?

Note that the code in this issue's description is valid and runs.

**Comment by Hixie** [comment]
`.call()` isn't type-safe, so IMHO it makes sense that you should typecast your function reference to a `Function` to be able to use it.

**Comment by jimbeveridge** [comment]
In my case,I already have a pointer of the desired type and it can't be cast to anything more precise. I was using the `call()` syntax so I could say `myfuncptr?.call(param1)` instead of `if (myfuncptr != null) myfuncptr(param1)`.

If `call()` isn't typesafe, then it does makes sense to have a warning for that fact. However, the existing warning that `method 'call' is not defined` is not correct.

**Comment by sethladd** [comment]
`print(callme is Function)` prints `true`, so it's not clear to me why I would need to cast `callme` to a Function in order to call `.call()` here

**Comment by leafpetersen** [comment]
I don't know anything about the `--enable-strict-call-checks` flag.  It's not a strong mode thing.  The original example looks reasonable to me.

**Comment by sethladd** [comment]
Thanks for taking a look @leafpetersen

**Comment by sethladd** [comment]
I think we might want to close this, as it's not really an issue for Flutter. This sounds more like an issue for the analyzer and the semantics of `--enable-strict-call-checks`

**Comment by Hixie** [comment]
Closing based on last comment. Please feel free to reopen this on the dart-lang repo.
