### ISSUE TITLE
Flutter run fails with the error ' Too few positional arguments: 1 required, 0 given.'

### ISSUE THREAD

**Issue by JICA98** [flutter/flutter#24739]
flutter run gives a compiler error for the newly created flutter project.
I have tried running it on both VScode and Android Studio and the problem still persists. 
flutter doctor -v, flutter create project and flutter run outputs are attached.
Thanks in Advance.
[compiler error.txt](https://github.com/flutter/flutter/files/2615413/compiler.error.txt)
[flutter doctor -v.txt](https://github.com/flutter/flutter/files/2615414/flutter.doctor.-v.txt)
[flutter create.txt](https://github.com/flutter/flutter/files/2615415/flutter.create.txt)

```
[√] Flutter is fully installed. (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17763.55], locale
    en-US)
[√] Android toolchain - develop for Android devices is fully installed. (Android SDK 28.0.3)
[√] Android Studio is fully installed. (version 3.2)
[√] VS Code is fully installed. (version 1.29.1)
[!] Connected device is not available.
```

**Comment by JICA98** [comment]
Sorry, but I'm getting a totally different set of errors after executing the above mentioned commands.
Please find the attachments. Thanks.
[git clean -xfd.txt](https://github.com/flutter/flutter/files/2615725/git.clean.-xfd.txt)
[git stash drop  git pull.txt](https://github.com/flutter/flutter/files/2615726/git.stash.drop.git.pull.txt)
[git stash save --keep-index.txt](https://github.com/flutter/flutter/files/2615727/git.stash.save.--keep-index.txt)
[flutter doctor.txt](https://github.com/flutter/flutter/files/2615728/flutter.doctor.txt)
[flutter run.txt](https://github.com/flutter/flutter/files/2615729/flutter.run.txt)

**Comment by zoechi** [comment]
The first command `git clean -xfd` already wasn't successful.
The last log seems to indicate that there are files locked by another process.
I'd suggest to restart the computer and try above commands again.
If that doesn't help please purge the install directory and reinstall Flutter.

**Comment by JICA98** [comment]
Thank You. Deleting the directory, re-installing flutter and setting new ENV path really worked.
Does that mean, whenever this error arises, do i have to re-install flutter each and every time because flutter was working fine just before and this error came out of nowhere.

**Comment by zoechi** [comment]
> really worked.

Thanks for the update!

> do i have to re-install flutter each and every time

Hard to tell, but this seems to happen rarely, so I wouldn't worry too much about that before it actually happens ;-)

**Comment by JICA98** [comment]
Thank You for Helping me out.
