### ISSUE TITLE
ui.Image member var is set to null all by itself, then the code crashes as it tries to read the images's width

### ISSUE THREAD

**Issue by sanderAtMaxdoro** [flutter/flutter#24737]
For some reason a member var is set to null even though it is used after the crash spot in the code.

Fortunately the problem also happens when the offending code sitting in a separate project with just a unit test, so here you go.

To see the problem happening, just run the single unit test in ImagePainter_test. One expects the image to exist after the async save() call, being equal to the value that has been put in there. What happens is that the code inside save() crashes like this:

----

Testing started at 10:06 ...
/Users/sandervanderwal/Developer/flutter/bin/flutter --no-color test --machine --verbose test/ImagePainter_test.dart
[  +28 ms] executing: [/Users/sandervanderwal/Developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/sandervanderwal/Developer/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [/Users/sandervanderwal/Developer/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/sandervanderwal/Developer/flutter/] git log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b55e52c6f73e327b1f9c2b3848b1bc9318767733
[        ] executing: [/Users/sandervanderwal/Developer/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 days ago
[   +1 ms] executing: [/Users/sandervanderwal/Developer/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +26 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.11.9-2-gb55e52c6f
[ +403 ms] running test package with arguments: [--no-color, -r, json, --concurrency=2, --, /Users/sandervanderwal/Projects/maxdoro/broken_flutter_app/test/ImagePainter_test.dart][ +147 ms] test 0: starting test /Users/sandervanderwal/Projects/maxdoro/broken_flutter_app/test/ImagePainter_test.dart
[  +19 ms] test 0: starting shell process
[   +2 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/sandervanderwal/Projects/maxdoro/broken_flutter_app
[   +2 ms] Compiler will use the following file as its incremental dill file: /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_compiler.nmXvVj/output.dill
[        ] Listening to compiler controller...
[   +2 ms] Compiling /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_listener.FhY1xw/listener.dart
[   +7 ms] /Users/sandervanderwal/Developer/flutter/bin/cache/dart-sdk/bin/dart /Users/sandervanderwal/Developer/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/sandervanderwal/Developer/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_compiler.nmXvVj/output.dill --packages /Users/sandervanderwal/Projects/maxdoro/broken_flutter_app/.packages --initialize-from-dill /Users/sandervanderwal/Projects/maxdoro/broken_flutter_app/build/testfile.dill
[+1759 ms] Compiling /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_listener.FhY1xw/listener.dart took 1767ms
[   +1 ms] /Users/sandervanderwal/Developer/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --enable-checked-mode --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts --packages=/Users/sandervanderwal/Projects/maxdoro/broken_flutter_app/.packages /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_listener.FhY1xw/listener.dart.dill
[   +1 ms] Using this directory for fonts configuration: /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_fonts.tytYkP
[   +7 ms] test 0: awaiting initial result for pid 32755
[ +756 ms] test 0: process with pid 32755 connected to test harness
[        ] test 0: awaiting test result for pid 32755480

NoSuchMethodError: The getter 'width' was called on null.
Receiver: null
Tried calling: width

dart:ui                                             Offset.&
package:broken_flutter_app/ImagePainter.dart 63:41  ImagePainter.save
===== asynchronous gap ===========================
dart:async                                          _AsyncAwaitCompleter.completeError
package:broken_flutter_app/ImagePainter.dart        ImagePainter.save
===== asynchronous gap ===========================
dart:async                                          _asyncThenWrapperHelper
test/ImagePainter_test.dart                         main.<fn>.<fn>
[ +295 ms] test 0: process with pid 32755 no longer needed by test harness
[        ] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[  +16 ms] test 0: deleting temporary directory
[   +3 ms] test 0: shutting down test harness socket server
[   +5 ms] test 0: finished[  +44 ms] Deleting /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_compiler.nmXvVj...
[   +3 ms] Deleting /var/folders/_x/10yfn4t50h5bnlr5ys8b8tph0000gn/T/flutter_test_fonts.tytYkP...
[        ] test package returned with exit code 1
[   +9 ms] "flutter test" took 3,432ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:182:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///Users/sandervanderwal/Developer/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

[broken_flutter_app.zip](https://github.com/flutter/flutter/files/2614734/broken_flutter_app.zip)
[broken_flutter_app.zip](https://github.com/flutter/flutter/files/2614735/broken_flutter_app.zip)
---------
flutter doctor -v

Sanders-MacBook-Pro:waarnemingenapp sandervanderwal$ flutter doctor -v
[✓] Flutter (Channel master, v0.11.10-pre.2, on Mac OS X 10.14.1 18B75, locale en-NL)
    • Flutter version 0.11.10-pre.2 at /Users/sandervanderwal/Developer/flutter
    • Framework revision b55e52c6f7 (5 days ago), 2018-11-21 15:48:23 -0500
    • Engine revision 1e37b99ac0
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/sandervanderwal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Turminder Xuss • ca4f8a0ddd55132ab42c253d7496b90a38b6b53c • ios • iOS 12.1
    • iPhone 6       • F1C23CB3-7C89-416E-87D0-5CCDC2C89254     • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
@sanderAtMaxdoro that's unlikely and the issue doesn't contain a minimal self-contained runnable reproduction that would allow to investigate.

I'd suggest you ask on StackOverflow or one of the other channels mentioned in the link above and in case it actually turns out to be a Flutter or Dart issue add a comment to have the issue reopened or create a new issue with a link to the discussion.

**Comment by sanderAtMaxdoro** [comment]
[broken_flutter_app.zip](https://github.com/flutter/flutter/files/2618573/broken_flutter_app.zip)
 
I had uploaded a zip file that contains such an example app. AT least Github said it was uploaded. Apparently it lied, so here it is again

**Comment by zoechi** [comment]
When I run your code `save()` is executed and the exception above is thrown because `_canvasSize` is `null`. 
The only location where `_canvasSize` is assigned to is `paint()` (first line in `paint()`) but that wasn't yet called.

**Comment by sanderAtMaxdoro** [comment]
you can be right, but i cannot verify right now in the original code as the bloody ios debugger just doesn’t work

Met vriendelijke groet

Sander van der Wal

**Comment by daanvandenhoek** [comment]
After some testing we found that this was indeed the case.
