### ISSUE TITLE
Stylizing paragraphs is a pain.

### ISSUE THREAD

**Issue by yahiaboudah** [flutter/flutter#24740]
I have been struggling with this for a couple of days. I want to display a few university lessons in a flutter app. I used the Text widget, but it's not sufficiently customizable. If I want to make one single word bold in the entire paragraph, I can't do that. I tried the RichText widget, but that was a pain in the neck, I would have to create a new TextSpan everytime I want to customize a piece of the paragraph somehow.

Before you say markdown, I gave that a try too. But I can't change the font size, it's small and not so easy on the eyes. I did check the docs on Github, but there doesn't seem to be enough flexibility, you can't resize or align text.

I am left with one option, which is to use an HTML view plugin. I tried importing that, but now it's giving me an error.

If you know any tricks on how to customize text, hopefully within flutter, not using HTML/markdown, I would really appreciate it. Any suggestions on how to make my life easier are welcome!

**Comment by zoechi** [comment]
Also asked on https://stackoverflow.com/questions/53482057/why-is-customizing-paragraphs-in-flutter-a-pain

**Comment by Patte1808** [comment]
Never thought about this being an issue but I can see the possible value. 

What kind of API would you expect or how would you style custom text blocks within this widget?

**Comment by yahiaboudah** [comment]
I found a workaround. I basically used the markdown package. I figured how to stylize the markdown text.
`theme:new ThemeData(
  backgroundColor: Colors.black26,primarySwatch: Colors.grey,
  textTheme: TextTheme(body1: TextStyle(fontSize: 25.0),
  headline: TextStyle(fontSize: 25.0),title: TextStyle(fontSize: 30.0))
),`
headline and title are part of the markdown package. They represent h1 and h2 If I remember correctly.
Still, using markdown to display local images is a real pain. You can't import the image file directly from the your assets folder, you have to write it to the device and get its path through the path_provider package. I still don't know how to write an image. Other than that, Markdown is excellent.

**Comment by yahiaboudah** [comment]
Before I close this issue, can anyone show me how to write files to the device only once? I don't really know how to do that.

**Comment by yahiaboudah** [comment]
Got it! Finally. After hours of digging, someone filed a PR in the flutter_markdown package literally just a month ago to take care of importing images from the assets folder into markdown. I had to edit the builder.dart file of the package manually though. Apparently, it wasn't added to the latest version?

I am going to close this issue now.
