### ISSUE TITLE
Flutter URI dosen't work after upgrade

### ISSUE THREAD

**Issue by antoniokarlos** [flutter/flutter#24741]
import 'package:http/http.dart' as http; -> Line error 
[dart] Target of URI doesn't exist: 'package:http/http.dart'.

That library is in a package that is not known. Maybe you forgot to mention it in your pubspec.yaml file?

**Comment by kyleDEVV** [comment]
please include a `flutter doctor -v` so the staff can look into helping you.

**Comment by zoechi** [comment]
Flutter reduced the dependencies it ships with by default to reduce the surface for version conflicts.
You need to add packages like `http` and as far as I remember `test` yourself to `dependencies:` in `pubspec.yaml` if you want to use them in your code.

I'm going to close.
Please add a comment to reopen in case I'm mistaken and this doesn't solve the problem.

**Comment by antoniokarlos** [comment]
Yes, it's Work! add http: on pubspec.yaml.

Thank's!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
