### ISSUE TITLE
Make the Skia to Flutter Engine autoroller to use the skia-master branch.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#24756]

**Comment by chinmaygarde** [comment]
Note to self: Follow up with @rmistry once he is back.

**Comment by rmistry** [comment]
Tracking this on Skia side with [skbug/8574](https://bugs.chromium.org/p/skia/issues/detail?id=8574).

**Comment by rmistry** [comment]
The updated autoroller landed a roll into skia-master - https://github.com/flutter/engine/pull/6960
