### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#24757]
Unable to build and run any Flutter project.
### Error
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "D:\Development\FlutterGames\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: D:\Development\FlutterGames\android\gradlew.bat -v
```
# Flutter crash report
## command

flutter run

## exception
```
ProcessException: ProcessException: Process "D:\Development\FlutterGames\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: D:\Development\FlutterGames\android\gradlew.bat -v
```

## Logs
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:185:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:166:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._complete (dart:async/future_impl.dart:476:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v0.11.9, on Microsoft Windows [Version 10.0.17763.134], locale en-US)
    [32m•[39m Flutter version 0.11.9 at D:\Development\flutter-sdk
    [32m•[39m Framework revision d48e6e433c (6 days ago), 2018-11-20 22:05:23 -0500
    [32m•[39m Engine revision 5c8147450d
    [32m•[39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m•[39m Android SDK at D:\Development\android-sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = D:\Development\android-sdk
    [32m•[39m Java binary at: C:\Program Files\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at C:\Program Files\Android Studio
    [32m•[39m Flutter plugin version 30.0.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

[32m•[39m No issues found!
```

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/13517884/nullpointerexception-org-gradle-wrapper-bootstrapmainstarter-findlauncherjarboo

Perhaps updating `android/gradle/wrapper/gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`.
You could try to create a new project with `flutter project foo` and check what value is used there and copy it over to your existing project.

**Comment by zoechi** [comment]
> Is there anywhere to find the minimum Gradle version supported by Flutter

@tvolkert @gspencergoog

I would like to know as well.

**Comment by tvolkert** [comment]
Here's the version currently used in the tool: https://github.com/flutter/flutter/blob/5391447fae6209bb21a89e6a5a6583cac1af9b4b/packages/flutter_tools/lib/src/android/gradle.dart#L26

**Comment by tvolkert** [comment]
From this, I just filed https://github.com/flutter/flutter/issues/24884 -- I'm gonna close this issue in favor of that one.  Thanks for helping track down the issue @searchy2!

**Comment by searchy2** [comment]
Thanks @zoechi for the help and @tvolkert for closing this issue! Love that Flutter keeps up with the latest Gradle tooling :heart:

**Comment by crcaicedo** [comment]
I have the same problem and Doctor says me no problem too. Same Gradle version. Regular Android Studio Java development environment working fine and updated to the last version.

> Unable to run flutter project. Followed this thread and still could not build and run
> 
> **Error**
> 
> ```
> Launching lib\main.dart on ONEPLUS A3003 in debug mode...
> ProcessException: Process "C:\Users\ravi\FlutterProjects\baby_names\android\gradlew.bat" exited abnormally:
> Exception in thread "main" java.lang.NullPointerException
> 	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
> 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
>   Command: C:\Users\ravi\FlutterProjects\baby_names\android\gradlew.bat -v
> Exited (sigterm)
> ```
> 
> **Flutter doctor**
> 
> ```
> [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
>     • Flutter version 1.0.0 at C:\src\flutter
>     • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
>     • Engine revision 7375a0f414
>     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> 
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     • Android SDK at C:\Users\ravi\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = C:\Users\ravi\AppData\Local\Android\sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.2)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 31.3.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [√] VS Code, 64-bit edition (version 1.30.2)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 2.21.1
> 
> [√] Connected device (1 available)
>     • ONEPLUS A3003 • fa57e143 • android-arm64 • Android 8.0.0 (API 26)
> 
> • No issues found!
> ```
> 
> **My Gradle**
> `baby_names\android\gradle\wrappegradle-wrapper.properties`
> 
> ```
> #Fri Jun 23 08:50:38 CEST 2017
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
> ```

**Comment by thekingrenz23** [comment]
I change the  distributionUrl to

distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

but the problem didnt go away. Pls. help

**Comment by devld** [comment]
delete first folder and the `.ok` file in  `$HOME/.gradle/wrapper/dists/gradle-<version>/<hash>/` works for me.

**Comment by AxelRocha** [comment]
Same as @crcaicedo, all things seems to be perfectly okey, but I was getting error NPE when tried to run. @crcaicedo solution worked for me!

On the file gradle-wrapper.properties, I changed:

- distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
+ distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

Cause my gradle version is 5.6.2

**Comment by SVG21** [comment]
what you can do is , create a new random flutter project then open gradle-wrapper.properties , copy it and paste to the current project in which you have an error
this might help

**Comment by 1PeterKimani** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.lang.RuntimeException: Gradle distribution 'C:\Users\apple\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb' contains too many directories. Expected to find exactly 1 directory.
	at org.gradle.wrapper.Install.getAndVerifyDistributionRoot(Install.java:118)
	at org.gradle.wrapper.Install.access$000(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by 1PeterKimani** [comment]
having a problem launching my first flutter app.PLEASE HELP

**Comment by khushbuThakker** [comment]
Yes, @crcaicedo 's solution work for me..Thanks a lot

**Comment by 0re** [comment]
i can't run my flutter project after following this thread, it's been giving me the same error message, please help.
this is the error message i've been getting.
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Gradle task assembleDebug failed with exit code 1
