### ISSUE TITLE
Document that a CupertinoApp isn't necessary for an iOS app

### ISSUE THREAD

**Issue by xster** [flutter/flutter#24766]
From https://medium.com/asos-techblog/flutter-vs-react-native-for-ios-android-app-development-c41b4e038db9 it wasn't clear that CupertinoApp wasn't necessary to build an iOS app. Document and add an example.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2035](https://github.com/flutter/website/issues/2035) via [**ZenHub**](https://www.zenhub.com/)

**Comment by xster** [comment]
Sorry, I meant this should be documented in the API docs

**Comment by cbracken** [comment]
@xster @HansMuller is this still an issue?

**Comment by HansMuller** [comment]
Yes it is.

**Comment by Abhishek01039** [comment]
Hello @Hixie 
can you please review this PR?
Thanks
