### ISSUE TITLE
AppBar doesn't have the Lift on Scroll option of the Material Design guidelines 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#24762]
In the Material Design [guidelines](https://material.io/design/components/app-bars-top.html#behavior), one of the items for the `AppBar` is:

>Top app bars can be positioned at the same elevation as content. Upon scroll, they increase elevation and let content scroll behind them.

This has already been implemented in Android with `liftOnScroll`, but I can't find this on the Flutter `AppBar` docs yet.

**Comment by rahulupadhyay** [comment]
Do we have this feature now?

**Comment by willlarche** [comment]
@rahulupadhyay , This is still undone. We would welcome contribution if you felt like tackling it!

**Comment by HansMuller** [comment]
AppBars with `pinned:true` lift when content scrolls below. See https://docs.flutter.io/flutter/material/SliverAppBar-class.html

**Comment by willlarche** [comment]
Thanks @HansMuller ! I think this issue is safe to close. @feinstein , does that work for you?

**Comment by feinstein** [comment]
I didn't test it, but sounds good to me. 

I will close it then and reopen if necessary.

Thank you guys.

**Comment by feinstein** [comment]
@HansMuller just to clarify, `pinned:true` is only available to `SliverAppBar` and not a regular `AppBar` to be used inside `Scaffold`, right?

**Comment by softmarshmallow** [comment]
re open this issue, it violates material design guideline.
