### ISSUE TITLE
Firebase Auth not getting user email

### ISSUE THREAD

**Issue by Abdullah1353** [flutter/flutter#24769]
<img width="960" alt="fire" src="https://user-images.githubusercontent.com/44639133/49066683-be0c2e00-f243-11e8-824b-67c0de2d5588.PNG">
this is how m handling my POST request.

Error i am getting is following
```
I/flutter ( 7426): {error: {code: 400, message: INVALID_EMAIL, errors: [{message: INVALID_EMAIL, domain: global, reason: invalid}]}}
```

**Comment by zoechi** [comment]
This doesn't look Flutter related.

Looks like you are posting an invalid email address.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by mrcchef** [comment]
Hey, Have you solved this issue. If yes, then please help me. I am also facing the same issue.

**Comment by Deenanadh** [comment]
> Hey, Have you solved this issue. If yes, then please help me. I am also facing the same issue.

same here .anyone with a solution?

**Comment by vianeysistemas** [comment]
Mismo problema por favor alqguien ya lo resolvio ?por favor Abdullah1353

**Comment by madhura-sc** [comment]
you need to trim both email and password

**Comment by madura7** [comment]
You need to trim both email and password
