### ISSUE TITLE
Is there an editable textfield on canvas

### ISSUE THREAD

**Issue by Hanggi** [flutter/flutter#24778]
I need a editable textfield on canvas, and I tried to find the docs and other support, but no answers.

Does flutter support editable textfield on canvas?

**Comment by zoechi** [comment]
For how-to questions it's usually a good idea to start on StackOverflow.

**Comment by zoechi** [comment]
Cross-link https://stackoverflow.com/questions/53501979/is-there-an-editable-textfield-on-flutter-canvas

**Comment by zoechi** [comment]
I'm going to close here. Perhaps you can improve the SO question to make it more clear what you try to accomplish.
