### ISSUE TITLE
Surface didn't update when back into App from iPhone notification center

### ISSUE THREAD

**Issue by sundayman** [flutter/flutter#24771]
## Steps to Reproduce

1. Go to iPhone Notification Center  '[self surfaceUpdated:NO]'  was called; (From applicationWillResignActive)
2. Back to App '[self surfaceUpdated:YES]'  didn't called (applicationWillEnterForeground didn't called)

## Logs

```
```

```
```

```
```

**Comment by sundayman** [comment]
@cbracken have a look please

**Comment by kangwang1988** [comment]
Paster `flutter doctor -v` here.
And what's the problem if the surface not updated?

**Comment by sundayman** [comment]
That cause GPU thread have been paused
Means user interaction disabled、video paused、animation stop、everything wrong

**Comment by sundayman** [comment]
My fault
