### ISSUE TITLE
Unable to use custom fonts - pubspec.yaml file throws error || Flutter v0.11.10 with VSCode

### ISSUE THREAD

**Issue by anantakrroy** [flutter/flutter#24775]
I am trying to use the custom font Raleway on my raised button text. The issue is clearly with the pubspec.yaml file.

Firstly, when I modify and save it , it throws the error

> [widgets_fun]

 

> pub get Resolving dependencies... Because widgets_fun depends on flutter_test any from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

> Flutter users should run flutter packages get instead of pub get. exit code 69

Secondly, there is an exclamation mark on the pubspec.yaml filename tab on VSCode. I confirmed this by using Raleway-ExtraBoldItalic in the pubspec yaml file, assigning weight of 800 and then using it in my dart file with the FontWeight property and assigning it as w800. However, the text is just bold and not italicised.

Expected font style 👍 
![screen shot 2018-11-27 at 1 30 23 pm](https://user-images.githubusercontent.com/20229180/49078748-d8a2cf00-f264-11e8-82a6-7a853154b09f.png)

Actual font style 👎  
![screen shot 2018-11-27 at 1 30 33 pm](https://user-images.githubusercontent.com/20229180/49078758-e22c3700-f264-11e8-8bd8-5155ea6c8283.png)

Flutter doctor -v :
![screen shot 2018-11-27 at 2 00 17 pm](https://user-images.githubusercontent.com/20229180/49078832-17388980-f265-11e8-9b85-7b89235bbaf8.png)

pubspec yaml file link:
https://codeshare.io/5z43RE

**Comment by zoechi** [comment]
I think https://stackoverflow.com/questions/53495143/unable-to-use-custom-fonts-pubspec-yaml-file-throws-error-flutter-v0-11-10 was the right place to ask.

@DanTup could you have a look? 
I don't know where to looks for diagnose information in VSCode to give guidance (for example about the mentioned warning on `pubspec.yaml`)

**Comment by anantakrroy** [comment]
@DanTup Sorry for posting this as an issue here. I also posted the same question on Stackoverflow. I was wondering if I need to explicitly also specify the Dart:Flutter SDK path in the Dart extension settings of VS Code. Doesn't it automatically detect where the Flutter package is located locally?

**Comment by DanTup** [comment]
> Doesn't it automatically detect where the Flutter package is located locally?

It tries - however it'll only look for the Flutter SDK if it thinks your project is Flutter, otherwise it'll just look for a Dart SDK (these may be the same depending on your setup). The extension log mentioned above will write information on which project type it detected as well as all the locations that it's looking for SDKs, so hopefully it should explain what's going on if something isn't right.

**Comment by anantakrroy** [comment]
@DanTup Thanks for explaining this. The extension log unfortunately does not show anything weird.
[extension.txt](https://github.com/flutter/flutter/files/2621232/extension.txt)

**Comment by DanTup** [comment]
The environment path is just the `PATH` environment variable - it's not showing the folder you have open but the paths searched for executables (we search `PATH` to find your SDK).

The log looks good - it detected a Flutter project and found the SDK - could you open an issue at https://github.com/Dart-Code/Dart-Code with a screenshot of exactly what you're seeing, and I'm sure we can get to the bottom of it.
