### ISSUE TITLE
CupertinoPageScaffold status bar tap to scroll to top

### ISSUE THREAD

**Issue by florisvdg** [flutter/flutter#24777]
The Material `Scaffold` on iOS has the feature to animate the `primaryScrollController` to `0.0` when  a status bar tap is detected. However, the `CupertinoPageScaffold` ironically does not seem to have this feature. Is there a reason for this or is it just not implemented yet?

**Comment by xster** [comment]
Note to future: beware of #15569 when implementing

**Comment by xster** [comment]
I don't really understand what #19732 is requesting but we should account for it when implementing too
