### ISSUE TITLE
Regarding record video

### ISSUE THREAD

**Issue by sampathrajs** [flutter/flutter#24788]
How to record video  with set some custom 
1. Need take video 25 fps only
2. Need to set timer 
3. Camera page having layer with my graph sheet image for focus

**Comment by kyleDEVV** [comment]
I think you might have better luck asking in one of the forums listed on https://flutter.io/support/

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
