### ISSUE TITLE
GrContexts are getting out of sync in the engine

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#24798]
(this was split off from https://github.com/flutter/flutter/issues/10895#issuecomment-441959065 and is paraphrasing what has been said in side-conversations with @chinmaygarde and @dnfield)

As @dnfield points out in the comment referenced above, The `GrContext`s used in the engine are getting out of sync:

UIDartIsolate, DartIsolate, and IOManager want to get a GrContext in the constructor and they hold on to it in a read-only/private field. They all live potentially longer than the actual underlying GL Surface.

After the refactoring in https://github.com/flutter/engine/commit/2bfb893cf39ef8455bf5cb87fbf3e14c410ad71a some code paths may never get a GrContext. This may negatively impact performance (e.g. disables async texture uploads).

We should ensure that there is one clear owner (PlatformView?) of GrContext that can destroy and replace it without causing other parts of the engine to go out of sync. 

Related: In https://github.com/flutter/engine/blob/5bf4deb4353c1b25f9db8ded62207353040eb94f/lib/ui/painting/codec.cc#L69-L79 we are currently much more likely to go down the non-context path, which may come with a performance penalty (and also uncovered another bug https://github.com/flutter/flutter/issues/10895)

**Comment by dnfield** [comment]
To clarify, it's _references_ to the `GrContext`that is manged by the `PlatformView` - not to suggest that there are multiple `GrContext` instances getting out of sync.
