### ISSUE TITLE
ListView.builder builds unecessary items when using ScrollController

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#24791]
When calling the method "jumpTo" on the `ScrollController`, the `ListView` builds every item between the current position and the "scrollTo" position;

This code snippet shows the problem. In the log, it will print every item , from 0 to 10000, wich takes a loooong time to run and freezes the entire application. 

The desired behavior should be the list building only the last elements of the list.

```dart
class TestListViewBuilder extends StatelessWidget {
  final _values = List.generate(10000, (index) => index);
  final _controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        RaisedButton(
          child: Text("Go to bottom"),
          onPressed: () {
            _controller.jumpTo(_controller.position.maxScrollExtent);
          },
        ),
        Expanded(
          child: ListView.builder(
            controller: _controller,
            itemBuilder: (context, index) {
              print("Building index $index");
              return ListTile(title: Text("Index $index"));
            },
            itemCount: _values.length,
          ),
        ),
      ],
    );
  }
}

```

Flutter doctor:
```
[√] Flutter (Channel unknown, v0.11.9, on Microsoft Windows [versÃ£o 10.0.17134.407], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] Connected device (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
#21023 looks somewhat related.

**Comment by HansMuller** [comment]
The intermediate list items are built because ListView doesn't now how big they are; so to scroll to the end it needs to layout them all out, one at a time...

You can avoid the problem by specifying `itemExtent`, which means that all of the items have the same height.  In this case `itemExtent: 56.0` should DTRT.

**Comment by shinayser** [comment]
But some cases we can't specify the itemExtent, since the item iteself is dynamic. 
Think for example in a log list: a lot of lines of text are being added to it each second. Some lines of text are bigger than others.

**Comment by shinayser** [comment]
So, that mean that it is impossible to do it? There is not another workaround?

**Comment by HansMuller** [comment]
To display very large list of arbitrary sized items that supports scrolling to an arbitrary offset in something like constant time, you'd have to build a custom scrolling container that could take advantage of app-specific constraints that applied to the distribution of item sizes.

**Comment by zoechi** [comment]
#12319 is about scrolling to an index

**Comment by veenatic82** [comment]
I am even seeing this happen when you set a PageStorageKey to a CustomScrollView. Switch back to the same widget and when flutter tries to preserve the scroll position, it builds all the items from the beginning. So, if you had 5000 items in your ScrollView, and you are at 4998th one, for example, it is rebuilding all items from the beginning till 4998th item. Also, during that process, I am seeing an increased memory pressure, like its shoots memory usage from say 15mb to 400 mb and when you scroll up or down for some time, it comes back to normal. But I think on devices where memory is limited, you may see Out Of memory exception. I tested with very small items say 50 characters each. So, if you have images or more stuff on each item, surely memory can shoot event more. 
I think we need to have a solution for this. Any plans on fixing this?

**Comment by VladyslavBondarenko** [comment]
Persists with `dev v1.16.4-pre.33`

**Comment by esDotDev** [comment]
> To display very large list of arbitrary sized items that supports scrolling to an arbitrary offset in something like constant time, you'd have to build a custom scrolling container that could take advantage of app-specific constraints that applied to the distribution of item sizes.

It feels like there is a middle ground here, a non app-specific method where the app-developer could aid the list in it's calculations... Anything to avoid doing a full build and layout pass on each element.

Thinking something like a measure function we could provide. 
```
extentCalculator: (i) => return item.desc != null? 100 : 70;
```
We could then come up with novel ways of calculating our expected heights, without the list needing to actually lay everything out. 

Note that this will become more and more of an issue, ad Desktop and Web apps roll out, with scrollbars that use JumpTo constantly with very large delta's ( as opposed to finger scrolling )

**Comment by liyuqian** [comment]
This seems to be the same issue as https://github.com/flutter/flutter/issues/52207

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/flutter/flutter/issues/52207, 
closing current issue as duplicate,
if you disagree please write in the comments and I will reopen it
