### ISSUE TITLE
Caret is able to select within emoji characters on the second line of text with emojis

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#24802]
Type multiple lines of emojis.
The caret is able to go in between the emojis, but only on the second line and further.
The caret is unable to appear in the first line.

**Comment by dnfield** [comment]
This casues a crash on iOS.  Steps to reproduce:

enter multiple lines of emoji's
move carret to middle of emoji
type any letter

The cause of the crash is that the JSON going into and/or coming back from the engine becomes invalid UTF8, and we end up asserting that we didn't get a null return from the JSON routines.

I spent a while trying to see if I could make them tolerate this case, but it seems really difficult to get iOS to do that and would be best to just fix this bug instead.

See also #31468

**Comment by dnfield** [comment]
The linked engine patch makes this not be a crash.  I'll remove the label once that lands.

**Comment by GaryQian** [comment]
Should be fixed by https://github.com/flutter/engine/pull/10063
