### ISSUE TITLE
Writing DateTime to Firestore via Ipad produces incorrect server-side timestamp

### ISSUE THREAD

**Issue by mabinici** [flutter/flutter#24809]
I know this issue is solved for iPhones but on the iPad I still get the date as "January 17, 1970" when writing any date to Cloud Firestore.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v` and the version of the Firestore plugin you are using.

https://github.com/flutter/plugins/pull/765 was a recent change that should have fixed timestamps.

**Comment by kroikie** [comment]
@mabinici

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/566. Any further collaboration will be done there.
