### ISSUE TITLE
canvas draw an image and export it without image

### ISSUE THREAD

**Issue by lyqiai** [flutter/flutter#24818]
use image.memory widget load it just can see a rect

[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
• Flutter version 0.11.9 at F:\flutter\flutter
• Framework revision d48e6e4 (7 days ago), 2018-11-20 22:05:23 -0500
• Engine revision 5c81474
• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
• Android SDK at C:\Users\16329\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: F:\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
X Android license status unknown.

[√] Android Studio (version 3.2)
• Android Studio at F:\Android Studio
• Flutter plugin version 30.0.1
• Dart plugin version 181.5656
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
import 'dart:convert';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'dart:io';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
// This widget is the root of your application.
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
),
home: MyHomePage(title: 'Flutter Demo Home Page'),
);
}
}

class MyHomePage extends StatefulWidget {
MyHomePage({Key key, this.title}) : super(key: key);
final String title;

@override
_MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
var _imageUrl = 'https://cdn.jsdelivr.net/gh/flutterchina/website@1.0/images/flutter-mark-square-100.png';
var _img;

@override
Widget build(BuildContext context) {
var widget = _img != null ? Image.memory(_img) : Text('place click button');
return Scaffold(
appBar: AppBar(),
body: Center(
child: widget
),
floatingActionButton: FloatingActionButton(
onPressed: () async {
var uri = Uri.parse(_imageUrl);
var httpClient = HttpClient();
var request = await httpClient.getUrl(uri);
var response = await request.close();
response.listen((data) async {
ui.Image image = await decodeImageFromList(data);
var pictureRecorder = ui.PictureRecorder();
var canvas = Canvas(pictureRecorder);
var paint = Paint();
paint.isAntiAlias = true;
var src = Rect.fromLTWH(
0.0, 0.0, image.width.toDouble(), image.height.toDouble());
var dst =
Rect.fromLTWH(0.0, 0.0, image.width.toDouble(), image.height.toDouble());
canvas.drawRect(Rect.fromLTWH(0.0, 0.0, 100.0, 100.0), paint);
canvas.drawImageRect(image, src, dst, paint);
var pic = pictureRecorder.endRecording();
ui.Image img = pic.toImage(image.width, image.height);
var byteData = await img.toByteData(format: ui.ImageByteFormat.png);
var buffer = byteData.buffer.asUint8List();
setState((){
_img = buffer;
});
});
},
tooltip: 'Increment',
child: Icon(Icons.add),
), // This trailing comma makes auto-formatting nicer for build methods.
);
}
}

**Comment by zoechi** [comment]
Looks like a dup of #24814
