### ISSUE TITLE
CupertinoDatePicker Date mode should also use minimumDate maximumDate.

### ISSUE THREAD

**Issue by lifenautjoe** [flutter/flutter#24820]
The CupertinoDatePicker widget has 3 modes. time, date and dateAndTime.

When using the date mode, we can restrict the selection range across years provided as integers 

```dart
  CupertinoDatePicker(
      minimumYear: 1980,
      maximumYear: 2015,
      mode: CupertinoDatePickerMode.date,
      // ..),
```

This "year only limit" behaviour is quite strange as for example in limiting birth date ranges, it also should take months and days into consideration.

More specifically: 

We want to allow only birthdates where a user is 21 year old or older.

Meaning
```
int minimumYear = 2018 - 21; // 1997
```

But if the user was born in December and the current month is November the user can still select the under-21 birthdate.

The DatePicker should therefore use the `DateTime minimumDate` and `DateTime maximumDate` parameters ( which are used for the other 2 modes) to limit the range.

# Doctor output

````
[✓] Flutter (Channel dev, v0.11.9, on Mac OS X 10.14 18A391,
    locale en-NL)
    • Flutter version 0.11.9 at
      /Users/joelhernandez/Documents/code/flutter
    • Framework revision d48e6e433c (7 days ago), 2018-11-20
      22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK
    28.0.2)
    • Android SDK at /Users/joelhernandez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for
      native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4999

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Cod
      e.flutter

[✓] Connected device (1 available)
    • iPhone X • 8968109C-4432-45F0-A010-94DAC8575087 • ios • iOS
      12.1 (simulator)

! Doctor found issues in 1 category.
````

**Comment by lifenautjoe** [comment]
Also to point out, in the case of the Material date picker, this is the case.

````
showDatePicker( firstDate: minimumDate, lastDate: maximumDate);
````

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by lifenautjoe** [comment]
> Please add the output of `flutter doctor -v`.

Whoops, thought I did. Done now. Thanks!

**Comment by jaumard** [comment]
Also we can't really use `minimumYear` as there is this assertion ^^ `assert(minimumYear != null),` https://github.com/flutter/flutter/blob/e41f1463cd9a7237df89bdec920745c8f7d22b8d/packages/flutter/lib/src/cupertino/date_picker.dart#L191

**Comment by aleor** [comment]
Hi guys, would you have any updates on this one, please?..

**Comment by BurhanDewantara** [comment]
Yes, I also have same problem to limit the maximum date

**Comment by angel1st** [comment]
@zoechi - any updates on this one? As pointed out by @mleonhard this feature is quite critical for any iOS app, using this date picker...

**Comment by AmruthPillai** [comment]
Any updates on this?

**Comment by lifenautjoe** [comment]
Woah, it's been almost a year since I opened this... 😬

What we ended doing as a hotfix while the Flutter team resolved the issue was using the material component.

This has been the case for several widgets that were broken/buggy on iOS, so our app is currently a zombie made out of iOS and Material parts...

**Comment by RomanKapshuk** [comment]
Any updates?
