### ISSUE TITLE
[WebView] Provide a Dart<->Javascript communication channel

### ISSUE THREAD

**Issue by diegovar** [flutter/flutter#24837]
*Edited by amirh:*

This is a request for a communication mechanism between the Flutter app's Dart code, and Javascript code running in the WebView.

*Original description:*
Android allows specifying a Javascript interface to act as a bridge between the webview and Android code. Similarly, iOS provides the UiWebView stringByEvaluatingJavaScriptFromString method that allows communicating with the underlying webview. Flutter should support this.

Example use case: Embedding a rich text HTML editor to edit existing HTML.

**Comment by diegovar** [comment]
There's a similar request in the fluttercommunity/flutter_webview_plugin plugin: https://github.com/fluttercommunity/flutter_webview_plugin/issues/71

**Comment by amirh** [comment]
Do you mean an interface between the Flutter app's Dart code and Javascript code that's running in the WebView?

**Comment by diegovar** [comment]
Correct, for example being able to call a JS function in the webview from Dart code (as is allowed in both Android and iOS).

**Comment by diegovar** [comment]
Examples:
https://developer.android.com/guide/webapps/webview#BindingJavaScript
https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript

**Comment by amirh** [comment]
Thanks, I edited the description a bit.

**Comment by diegovar** [comment]
Hi Amir, would you be willing to accept contributions for this feature? This would be a feature we'd require to use Flutter in a new app.

**Comment by jesteracer** [comment]
It would be great to have a way to pass data to and from JS context that is running inside the WebView.  
On IOS it should be possible with postMessages: here are some examples https://nshipster.com/wkwebview/

It will be useful to report the DOM height, when it gets loaded, to update the container for the webview, if the dimensions are unknown. (Like for example to embed a tweet or some media inside the tree)

**Comment by gisngocthach** [comment]
A very Map-OpenLayer feature embedded into page having a need on communication between js and dart where dart can call js functions and vice versa. It is supported in the native languages on both platform.

**Comment by diegovar** [comment]
Can this be marked as closed now that https://github.com/flutter/plugins/pull/1021 is merged?

**Comment by amirh** [comment]
This issue is about 2 way communication, what we currently have allows for one way Dart->JS

**Comment by amirh** [comment]
Below is a proposal for the API to add:



## Background
The webview_flutter plugin currently embeds an Android WebView on Android, and a WkWebView on iOS.

The plugin currently only supports one way communication (Dart-->Javascript) with the evaluateJavascript method(which has an equivalent interface on both iOS and Android).

Android's WebView and iOS' WkWebView provide different APIs for sending messages from JavaScript code running in the webview to Java/ObjC code:

### Android/iOS WebView’s API for JS-->Java communication
**Android** models it as an injection of a proxy JS object for a provided Java object, e.g:

Java:

```java
public class Foo {
    @JavascriptInterface
    public String bar(String value) { return value + “ world!”;}
}
webView.addJavascriptInterface(new Foo(), "Foo");
```

JavaScript:

```javascript
Foo.bar(alert(“Hello”));
```

The WebView takes care of marshalling and unmarshalling the parameters, I couldn’t find an official documentation for supported types but it seems to support: String, int, float, and one dimensional arrays of these types.

Note that a synchronously returned value (by the Java object) is passed back to JS, this cannot be done with Flutter’s current architecture as communication between the platform and ui threads is async.

**iOS WkWebView** models it as a string message handler, e.g:

ObjC:
```objc
[controller addScriptMessageHandler:handler name:@"myMessageHandler"];

// this is in handler’s class implementation
- (void)userContentController:(WKUserContentController *)userContentController
      didReceiveScriptMessage:(WKScriptMessage *)message {

 // this is invoked with the message sent from JS

}
```

JavaScript:
```javascript
window.webkit.messageHandlers.myMessageHandler.postMessage(“hello”);
```
## Proposed APIs
I’m listing a few options for the JavaScript and Dart APIs.
My current preference is to go with a “String message channel”(JavaScript proposal 1).
I’m looking for feedback on whether a single channel is useful enough, or do we need to support multiple channels.
On the Dart side I feel like the difference between proposals 2 and 4 are mainly a matter of taste, I tend to go with 2, but happy to be convinced to go with 4 by any objective argument.

### JavaScript side API proposals
#### Proposal 1 - String message channel (consistent across platforms)
Javascript:
```javascript
MyChannel.postMessage(“Hello”);
```
Notes:
  * The name for “MyChannel” will provided by the Dart code as a string, similar to the way the Android WebView API gets the name for the proxy object.
  * On iOS this will require injecting a small JS abstraction layer on top of the window.webkit.messageHandlers.messageHandler.postMessage() call.

#### Proposal 2 - String message channel (with no platform abstraction)
Same as proposal 1, but without abstracting the `window.webkit.messageHandlers.messageHandler.postMessage()` on iOS, this will require the JS code to be aware of the platform.

Notes:
  * Developers can still inject (or include) their own abstraction layer on top of `window.webkit.messageHandlers.messageHandler.postMessage()`.

#### Proposal 3 - MethodChannel like API
JavaScript:
```javascript
MyChannel.invokeMethod(“methodName”, “param1”, 2, “param 3”);
```

Notes:
  * The name for “MyChannel” will provided by the Dart code as a string, similar to the way the Android WebView API gets the name for the proxy object.
  * This will require injecting non trivial javascript “codec” implementation for marshalling the arguments, we might be able to re-use Flutter’s codecs compiled with Dart2JS.
  * I’d really vote to avoid this kind of complexity unless required, and given a String message channel this kind of thing can be implemented as a third-party JS library.

Javascript:
```javascript
MyChannel.postMessage(“Hello”);
```

#### Proposal 4 - Injected JS proxy objects (similar to Android)
JavaScript:
```javascript
MyChannel.methodName(“param1”, 2, “param 3”);
```

Notes:
  * This can be built on-top of proposal 3 using ES6 Proxy where supported (need to research the portion of devices we support that don’t have Proxy and see if there’s a robust fallback).
  * I’d really vote to avoid this kind of complexity unless required, and given a String message channel this kind of thing can be implemented as a third-party JS library.

### Dart side API proposals

#### Proposal 1 - String message handler
Dart:
```dart
WebView(
  initialUrl: 'https://...',
  javascriptMode: JavascriptMode.unrestricted,
  javascriptMessageChannelName: ‘MyChannel’,
  onHandleJavascriptMessage: (String message) { print('$message'); },
)
```

#### Proposal 2 - Multiple String message handlers
Dart:
```dart
WebView(
  initialUrl: 'https://...',
  javascriptMode: JavascriptMode.unrestricted,
  javascriptMessageChannels: <JavascriptMessageHandler> [
    JavascriptMessageHandler(
      name: ‘MyChannel’,
      onHandleJavascriptMessage: (String message) { print('$message'); },
    ),
    JavascriptMessageHandler(
      name: ‘MyOtherChannel’,
      onHandleJavascriptMessage: (String message) { print('$message'); },
    ),
  ]
)
```

#### Proposed API 3 - MethodChannel like API (goes with JS proposal 3)
Dart:
```dart
WebView(
  initialUrl: 'https://...',
  javascriptMode: JavascriptMode.unrestricted,
  javascriptChannelName: ‘MyChannel’,
  onJavascriptMethodCall: handleMethodCal
)

// …

Future<dynamic> handleMethodCall(MethodCall call) {
  print(‘method: ${call.method} arguments: ${call.arguments}’);
}
```

#### Proposal 4 - Multiple string message channels with a single handler
Dart:
```dart
WebView(
  initialUrl: 'https://...',
  javascriptMode: JavascriptMode.unrestricted,
  javascriptMessageChannelName: ‘MyChannel’,
  onHandleJavascriptMessage: (String channel, String message) { print('$message'); },
)
```

**Comment by bagintz** [comment]
@amirh I am catching up to the changes here and it looks like they are really moving along.  Can you let me know what proposal from above that you ended up choosing?  Thanks!

**Comment by amirh** [comment]
@bagintz see the PR description for https://github.com/flutter/plugins/pull/1116 for the API I'm going with.

**Comment by bagintz** [comment]
@amirh Thank you!!!!

**Comment by amirh** [comment]
Published with webview_flutter 0.3.1

**Comment by Jaware** [comment]
> Published with webview_flutter 0.3.1
when 0.3.1 will be published ? now 0.3.0+2
https://pub.dartlang.org/packages/flutter_webview_plugin#-analysis-tab-

**Comment by amirh** [comment]
I believe you are looking at a different plugin, see: https://pub.dartlang.org/packages/webview_flutter

**Comment by Jaware** [comment]
额，sorry @amirh  and thanks

**Comment by mrgoonie** [comment]
Hi @amirh, just wondering if all proposals were implemented and pushed, or only one of them? Do you have any documentations for using these channel? I can't find it anywhere on the pub or github...

**Comment by amirh** [comment]
Check the API docs for what ended up landing: https://pub.dartlang.org/documentation/webview_flutter/latest/webview_flutter/WebView/javascriptChannels.html

**Comment by NewITCorp** [comment]
from the above link I can send my data from webview to flutter using javascript.

how can I send my data to webview using the same channel?

**Comment by heinzan** [comment]
javascriptMessageChannelNames still can not use at 0.3.6.
@NewITCorp  can u share code.Thanks

**Comment by Prashant-K-V** [comment]
Amirh you should help beginners too as
NewItCorp is right, there seems no way to do JavaScript-> dart. 
I am in an urgent need of that though.
Your support is truly admired.

**Comment by Prashant-K-V** [comment]
@heinzan you still need a working gist??

**Comment by heinzan** [comment]
> @heinzan you still need a working gist??

yes

**Comment by amirh** [comment]
JavaScriptChannel is the mechanism from sending messages from javascript code running in the webview to the Flutter app's Dart code. I'd suggest StackOverflow as a better form for support question (more people are looking for questions and answers there and will benefit from your questions).

Suggestion for improving the documentation/API are welcomed as well(probably best to start these as GitHub issues and followup with a PR after a proposal is finalized).

**Comment by NewITCorp** [comment]
@heinzan 

here is my implementation in Dart (your class that derived from State)

```
 final Completer<WebViewController> _controller = Completer<WebViewController>();
WebView getWebView() {
    return WebView(
      initialUrl: yourURL,
      javascriptMode: JavascriptMode.unrestricted,
      javascriptChannels: Set.from([
        JavascriptChannel(
            //my channel name is jsfunc1
            name: 'jsfunc1',
            onMessageReceived: (JavascriptMessage message) {
                print(message.message);
                //'hello' will be here
            }), 
       // we can have more than one channels
      ]),
      onWebViewCreated: (WebViewController webViewController) {
        _controller.complete(webViewController);
      },
    );
  }
//and then call getWebView() in your build() method where you want to display it in your screen
```

and in your html, call this with javascript
```
var x = 'hello';
try { jsfunc1.postMessage(x); } catch (err) {}
jsfunc1.postMessage(x);
```
we always need to wrap with try/catch block because postMessage() is not recognized by any browsers. so it will raise an error when you open it with browser


@Prashant-K-V  after research for a while, we can send from flutter to webView using either url parameters or headers (like usual). It is not possible to send without page reloading anyway.

@amirh  thanks for you great contribution.

**Comment by Prashant-K-V** [comment]
@NewITCorp  yes that feature is really a need. Can't proceed without it, for finalizing the webview implementation. 
Hope Google admires our request.

**Comment by amirh** [comment]
@NewITCorp  / @Prashant-K-V the way to send messages from the Flutter app's Dart code to JavaScript is to call [evaluateJavascript](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewController/evaluateJavascript.html).

**Comment by Prashant-K-V** [comment]
I was thinking like that, but that way only string can be passed, thats why I was not confident with that technique.
Although thanks Amirha. Tx all to be a great community. :) Viva de flutter.

**Comment by nateshmbhat** [comment]
any updates on this two way communication ?
