### ISSUE TITLE
flutter ListTile isThreeLine can not add

### ISSUE THREAD

**Issue by zhiyuanbuqiID** [flutter/flutter#24847]
I wrote `isThreeLine: true`, but I don't know how to write this third lines
```dart
ListTile(
       isThreeLine: true,
      leading: new Icon(
           imges
        ),
       title: new Text('关于'),
       trailing: Icon(Icons.arrow_forward),
)
```

I want to get like this
```
______________Title1
imges_______Title2 ______trailing.icons
_____________Title3
```

**Comment by zhiyuanbuqiID** [comment]
I want hwo to write the   Title3

**Comment by zhiyuanbuqiID** [comment]
![image](https://user-images.githubusercontent.com/36401045/49207447-e8025380-f3ef-11e8-8dbd-6ddb118802d0.png)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

`isThreeLine` seems to modify how `ListTile` is rendered when `subtitle` is set.

**Comment by zhiyuanbuqiID** [comment]
[this the detail & code ](https://stackoverflow.com/questions/53539523/flutter-how-to-use-listtile-threeline)
when i delete 'isThreeLines', the code is ok

![image](https://user-images.githubusercontent.com/36401045/49223594-2c0a4e00-f41a-11e8-81a3-f9df5f65b14e.png)

**Comment by zoechi** [comment]
Has already an accepted answered at https://stackoverflow.com/questions/53539523/flutter-how-to-use-listtile-threeline
