### ISSUE TITLE
How to pin keyboard when Popupmenu appears

### ISSUE THREAD

**Issue by zywj** [flutter/flutter#24843]
How can I hold the keyboard when click `PopupMenuButton`.
I have noticed that why the keyboard will disappear is  `PopupMenu` using `Navigation.push `
So, is there a workaournd to implement my require?

```dart
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Container(
              width: 150.0,
              child: TextField(
                autofocus: false,
                decoration: new InputDecoration(
                  hintStyle:
                      TextStyle(color: const Color(0xFFAAAAAA), fontSize: 15.0),
                  border: OutlineInputBorder(),
                ),
              ),
            ),
            PopupMenuButton<String>(
              onSelected: (String r) {},
              itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
                    const PopupMenuItem<String>(
                      value: "text",
                      child: const Text('Popup'),
                    ),
                  ],
            ),
          ],
        ),
      ),
    );
  }
```

Here is the `flutter doctor -v`
```
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.14.1 18B75, locale en-HK)
    • Flutter version 0.10.2 at /usr/local/flutter
    • Framework revision d8cbb80206 (5 weeks ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • iPhone 7 • 463B2CA4-5966-4EC8-B0BE-6A174EA45B7B • ios • iOS 12.1
      (simulator)

! Doctor found issues in 2 categories.
```

**Comment by HiroshiHorie** [comment]
This is bugging me also...

**Comment by Hixie** [comment]
cc @gspencergoog

**Comment by edwin-alvarez** [comment]
any workaround for this issue?

**Comment by edwin-alvarez** [comment]
Note: this is **only a workaround since I'm using a delay for 400 milliseconds,** but I noticed that's good enough time to allow redraw.

  Widget _offsetPopup2() {
    return GestureDetector(
          onTap: ()  {
            FocusScope.of(context).requestFocus(new FocusNode());
            WidgetsBinding.instance.addPostFrameCallback((_) async {
                await Future.delayed(Duration(milliseconds: 400));
                RenderBox box = _more_o.currentContext.findRenderObject();
                Offset position = box.localToGlobal(Offset.zero); //this is global position
                double y = position.dy; //this is y - I think it's what you want
                
                _showMenu(position);
            });

          },
          child: Icon(Icons.more_horiz, key: _more_o,)
    );
  }

  _showMenu(Offset offset) async {
    double left = offset.dx;
    double top = offset.dy;
    await showMenu(
      context: context,
      position: RelativeRect.fromLTRB(left, top, 0, 0),
      items: [
        PopupMenuItem(
          value: 1,
          child: Text(
            'Bible Study'.i18n,
            style: TextStyle(color: Colors.black),
          ),
        ),
        PopupMenuItem(
          value: 2,
          child: Text(
            'Return Visit'.i18n,
            style: TextStyle(color: Colors.black),
          ),
        ),
      ],
      elevation: 8.0,
    );
  }

some other links which could be useful
//https://stackoverflow.com/questions/43349013/how-to-open-a-popupmenubutton
//https://stackoverflow.com/questions/54291245/get-y-position-of-container-on-flutter

**Comment by Vitor-Bukovitz** [comment]
@zoechi any update to this issue?

**Comment by pabloserranof** [comment]
Any progress with this?

**Comment by PegasisForever** [comment]
I create a package [keep_keyboard_popup_menu](https://pub.dev/packages/keep_keyboard_popup_menu) to solve this issue:

<img src="https://raw.githubusercontent.com/PegasisForever/keep_keyboard_popup_menu/master/example/screenshots/1.gif" width="200"/>

**Comment by Vitor-Bukovitz** [comment]
This is the workaround I used:
  
```
  final _menuKey = GlobalKey<PopupMenuButtonState>();

  Widget _uploadButton() {
    return Listener(
      onPointerDown: (_) async {
        if (FocusScope.of(context).hasFocus) {
          FocusScope.of(context).unfocus();
          await Future.delayed(Duration(milliseconds: 400));
        }
        _menuKey.currentState.showButtonMenu();
      },
      child: PopupMenuButton(
        key: _menuKey,
        enabled: false,
        icon: Icon(
          Icons.add_circle_outline,
          color: Colors.black,
        ),
        offset: Offset(0, -120),
        onSelected: (value) async {},
        itemBuilder: (context) {
          return [
            PopupMenuItem(
              value: 'camera',
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(
                    Icons.camera_alt,
                    color: Theme.of(context).accentColor,
                  ),
                  Text(' Take a photo')
                ],
              ),
            ),
          ];
        },
      ),
    );
  }
```

Obs: The parent widget must be a stateful

**Comment by jangruenwaldt** [comment]
Pleaseeeee fix this! This is quite annoying

**Comment by NaikSoftware** [comment]
We really need way to show widgets over keyboard as Android AlertDialog, etc.

**Comment by kbanta11** [comment]
Any update on this? Not able to get either of the workarounds to work consistently, so my popupmenu ends up in the middle of the page if the keyboard is open

**Comment by SalishKumar** [comment]
any update??? stuck on same problem

**Comment by darshankawar** [comment]
This behavior still occurs using latest stable (2.5.1) and master version, as, a [new](https://github.com/flutter/flutter/issues/90726) issue was opened to report it. 

Added a `crowd` label after looking at comments in this thread. 

/cc: @gspencergoog for further insights on this issue.

**Comment by ivanchaukn** [comment]
Can't believe this problem is still not solve until now...

**Comment by zhangruiyu** [comment]
ny update on this?

**Comment by DanilKarasev** [comment]
It's 2024. We still waiting

**Comment by saif-ellafi** [comment]
Also interested in this!

**Comment by saif-ellafi** [comment]
The `MenuAnchor` class (as shown in the examples here: https://api.flutter.dev/flutter/material/PopupMenuButton-class.html) does respect the `TextField` focus.. but it has unfortunately another bug which is going under the keyboard (https://github.com/flutter/flutter/issues/142921), so also not usable.
