### ISSUE TITLE
Android "windowSoftInputMode" set to "adjustPan" does not work as expected

### ISSUE THREAD

**Issue by josvos** [flutter/flutter#24856]
In `AndroidManifest.xml` the default `activity` input mode attribute setting is `android:windowSoftInputMode="adjustResize"`.

When I change that to `android:windowSoftInputMode="adjustPan"`, I would expect that the keyboard appearance for text input fields does not resize the window, but that doesn't seem to work.  Is this a Flutter problem or do I misinterpret the way `adjustResize` should work?

I know of `SingleChildScrollView` to program workarounds for the keyboard-related resizing, but that doesn't help for all kinds of widgets with flexible elements. I would prefer some solution that just moves the full screen upwards (keeping its size), as far as needed to still show the part with input field above the keyboard.

**Comment by zoechi** [comment]
`android:windowSoftInputMode="adjustResize"` is for Android native. 
I doubt Flutter uses that at all. You'll need to find a Flutter way to deal with that. 

> doesn't help for all kinds of widgets with flexible elements

I'd suggest to ask on StackOverflow if you have concrete examples.

**Comment by josvos** [comment]
If you say *I doubt*, does that mean you are not sure?  The attribute is in the Manifest file, so I thought that would work on OS-level, independent of whether it is implemented natively or with Flutter.

W.r.t. examples... well, almost any composed screen (e.g. mix of `Row`s and `Column`s) and for example parts using `LayoutBuilder` (I draw a matrix of buttons where button size and number of rows and columns depend on the available container) end up in reshuffling/rearranging acttions that I don't want.  The `adjustPan` (if I interpret it correctly) is *exactly* what I need: the app should just not know about the keyboard and the panning, ideally that should be done transparently.

**Comment by zoechi** [comment]
Flutter doesn't use "OS-level" inputs, it implements its own.
Perhaps you're looking for https://docs.flutter.io/flutter/material/Scaffold/resizeToAvoidBottomPadding.html

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
If you wrap the area in a ListView, SingleChildScrollView or similar it will scroll into view.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by josvos** [comment]
> If you wrap the area in a ListView, SingleChildScrollView or similar it will scroll into view.

I tried, but this does not work for more complex layouts (it will result in different container sizes), see also my comment above: https://github.com/flutter/flutter/issues/24856#issuecomment-447103015

**Comment by zoechi** [comment]
> I tried, but this does not work for more complex layouts 

Then please provide a minimal reproduction that demonstrates that and how this approach doesn't work.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by craiglabenz** [comment]
For posterity, I recently ran into this with the following (incorrect) layout:

```
Column(
  children: <Widget>[
    BigHeaderArea(),
    Form(
      ListView(
        ...formFields,
      ),
    ),
  ],
)
```

And fixed it by swapping places with my `Column` and `ListView` widgets, aka:

```
ListView(
  children: <Widget>[
    BigHeaderArea(),
    Form(
      Column(
        ...formFields,
      ),
    ),
  ],
)
```

Hopefully one day someone benefits from this tidbit :smile:

**Comment by sinloss** [comment]
> For posterity, I recently ran into this with the following (incorrect) layout:
> 
> ```dart
> Column(
>   children: <Widget>[
>     BigHeaderArea(),
>     Form(
>       ListView(
>         ...formFields,
>       ),
>     ),
>   ],
> )
> ```
> 
> And fixed it by swapping places with my `Column` and `ListView` widgets, aka:
> 
> ```dart
> ListView(
>   children: <Widget>[
>     BigHeaderArea(),
>     Form(
>       Column(
>         ...formFields,
>       ),
>     ),
>   ],
> )
> ```
> 
> Hopefully one day someone benefits from this tidbit 😄

But why...

**Comment by andrespd99** [comment]
> For posterity, I recently ran into this with the following (incorrect) layout:
> 
> ```dart
> Column(
>   children: <Widget>[
>     BigHeaderArea(),
>     Form(
>       ListView(
>         ...formFields,
>       ),
>     ),
>   ],
> )
> ```
> 
> And fixed it by swapping places with my `Column` and `ListView` widgets, aka:
> 
> ```dart
> ListView(
>   children: <Widget>[
>     BigHeaderArea(),
>     Form(
>       Column(
>         ...formFields,
>       ),
>     ),
>   ],
> )
> ```
> 
> Hopefully one day someone benefits from this tidbit 😄

Incredible. Thank you so much. It worked like a charm.
