### ISSUE TITLE
Obscured text long-press menu controls

### ISSUE THREAD

**Issue by blucell** [flutter/flutter#24853]
Internal: b/140830033

As per #24100, long pressing obscured text fields shows menu controls that allow copying it, which makes it indirectly readable.

Because of the code freeze, #24100 focuses on temporarily disabling menu controls by default for obscured text fields, but for it to match the current experience, it should still appear but with the controls that can be used to access the data filtered out. For example, on Android, you may find the controls `Select All`, `Paste`, and `Auto Fill` there, because those ones do not leak the data already inside the field.

This is a request to implement such filters to the long-press menu controls based on the obscurity of the controlling text field.

**Comment by AndroidNils** [comment]
This would be awesome! We need it :)

**Comment by jkurtw** [comment]
b/140830033

**Comment by justinmc** [comment]
This appears fixed to me.  I can't copy from an obscured text field.  I think this was deliberately fixed in a PR awhile back, but I can't find the specific PR.

Anyway, if anyone is still able to copy text out of an obscured field, let me know and we can reopen this.
