### ISSUE TITLE
Document that Image.file() is caching images

### ISSUE THREAD

**Issue by daanvandenhoek** [flutter/flutter#24858]
When loading an image from a file the Image.file seems like it is keeping a cache of the file. I have an image that i save to a file. when i change this file with new content but the same name the image stays the same. If i load the image with **image.memory(file.reasAsBytesSync())** then it does work

## flutter doctor -v
```
[√] Flutter (Channel master, v0.11.13-pre.1, on Microsoft Windows [Version 10.0.17134.407], locale nl-NL)
    • Flutter version 0.11.13-pre.1 at D:\flutter
    • Framework revision c80244d1ca (10 hours ago), 2018-11-28 16:19:28 -0800
    • Engine revision 72c7a75672
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\SDK
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (2 available)
    • LYA L29                   • LHS7N18A04002770 • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
You should be able to remove it from cache using `https://docs.flutter.io/flutter/painting/ImageCache/evict.html` with the file path as key.

**Comment by ToxicAlex** [comment]
When I needed to do this, I found that using the file path as the key did not work, however, creating a new FileImage and using that as the key did.

    imageCache.evict(new FileImage(file));

**Comment by chornbe** [comment]
How about auto-evicting when the file fails certain "is this cached" checks in the cache manager - especially when the underlying file is different, but may use the same name to retain object<-->image file references without a database. Oy. Sure, allow manual evictions too, but this has pretty much stepped on my whole morning. I also have zero faith this works as expected; I have to revert my code and basically start from a clean slate. All the various permutations of this, imageCache.clear();, and PaintingBinding.instance.imageCache.clear(); have done exactly zero to help. The only thing I've been able to make work is to replace my local _img variable with a placeholder image.asset("") object, let setState run, then make the user select the image file after deleting the existing one.

**Comment by chornbe** [comment]
Follow up, Future.delay(...) like 10ms the save routing works, too, but feels hackey and unreliable. I guess spinning off the setState(...) on the new file helps force a re-read or re-write on the cache or something.

I dunno, this feels more buggy and missing doccy to me. $.02

**Comment by pdivita** [comment]
Using Image.memory(file.reasAsBytesSync()) worked for me.

**Comment by pedromassangocode** [comment]
Still valid since the documentation of `Image.file` constructor does not state that it does cache image.

https://api.flutter.dev/flutter/widgets/Image/Image.file.html

**Comment by EvGeniyLell** [comment]
for use DecorationImage you can tyr it
`      File file = File(avatarPath);
      Uint8List fileBytes = file.readAsBytesSync();
      ImageProvider image = MemoryImage(fileBytes);
`
