### ISSUE TITLE
Doctor should detect proxy issues that prevent debugging (eg. HTTP_PROXY set, NO_PROXY not set)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#24854]
There have been a lot of issues relating to not being able to debug Flutter apps that have been caused by proxies. Most common is that all connections are being proxied, including those to `localhost`.

The fix is usually as simple as adding `localhost,127.0.0.1` to the `NO_PROXY` environment variable.

If we could detect this in `flutter doctor` it would probably save on a lot of issues and troubleshooting. We could either try making connections to localhost/127.0.0.1 or check for the `HTTP_PROXY` and `NO_PROXY` env variables (or both!).

**Comment by irrigator** [comment]
I've added localhost,127.0.0.1 to the NO_PROXY environment variable, but hot reload still doesn't work. The only way is to remove PROXY environment variable.

**Comment by DanTup** [comment]
@irrigator Were you testing from the same terminal where you set the env variable? If you set it in a terminal startup script for example, it might not be visible to an IDE launched outside of the terminal.

Also - can you clarify exactly what you mean by hot reload doesn't work - the usual failure seen when this isn't working correctly is that the app launches with a white screen and never starts properly. Is that not what you're seeing?

**Comment by irrigator** [comment]
@DanTup I use zsh on macOS and set env variables in the ```.zshrc``` file.
```zsh
export HTTP_PROXY=http://127.0.0.1:1087
export HTTPS_PROXY=http://127.0.0.1:1087
export NO_PROXY=localhost,127.0.0.0
```
The app launches correctly but after I made some changes hot reload does not work, I have to rebuild the app.

If I remove the proxy env variables, hot reload works fine.

**Comment by irrigator** [comment]
Saddly ```flutter packages ``` needs proxy (I'm in China), so I have to change back and forth those env variables. 😭

**Comment by DanTup** [comment]
@irrigator Could you open a specific issue about this problem (if you haven't already), to avoid confusing this one (this has fixed it for many people so I think it's still something that should be added).

> but after I made some changes hot reload does not work

In the new issue, can you include whether you see any error, whether you're running from the command line or an IDE and if you run in verbose mode (`-v`) whether does it output anything interesting when you try to reload?Thanks!

**Comment by irrigator** [comment]
@DanTup No Problem!

**Comment by irrigator** [comment]
@DanTup Actually it's just a matter of typo ```127.0.0.1```. So sorry.

**Comment by benedicte69** [comment]
I comment here as if I use an android  emulator API 28, hot reload works fine, but if I use an Android emulator API Q, hot road does not work in Flutter be wise of a proxies.

**Comment by DanTup** [comment]
@benedicte69 there's an open issue about things not working on Q at https://github.com/flutter/flutter/issues/33050

**Comment by zhuliminl** [comment]
`export NO_PROXY=localhost,127.0.0.1` not work for me.

However!

```
export HTTP_PROXY=http://127.0.0.1:1087
export HTTPS_PROXY=http://127.0.0.1:1087
export NO_PROXY=localhost,127.0.0.1,LOCALHOST
```
try this. It works for me. kind weird

**Comment by pulller** [comment]
> `export NO_PROXY=localhost,127.0.0.1` not work for me.
> 
> However!
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:1087
> export HTTPS_PROXY=http://127.0.0.1:1087
> export NO_PROXY=localhost,127.0.0.1,LOCALHOST
> ```
> 
> try this. It works for me. kind weird

That works for me! Thanks

**Comment by matheusrocha89** [comment]
I tried all these exported variables but none of them worked with me.

**Comment by KenChoi1992** [comment]
@zhuliminl After trying all those ways this issue shows, only your comment works for me! Thanks a lot, this issue is been bothering me for a week!

**Comment by Lachyn811** [comment]
Hello everyone 
Ive used this way to solve question ...

export HTTP_PROXY=http://127.0.0.1:1087
export HTTPS_PROXY=http://127.0.0.1:1087
export NO_PROXY=localhost,127.0.0.1,LOCALHOST
But when I run flutter precache --all-platforms. It shows -

Failed to download
https://storage.googleapis.com/flutter_infra/flutter/05e680e202af9a92461070cb2d9
982acad46c83c/android-arm-profile/darwin-x64.zip. Ensure you have network
connectivity and then try again.
SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1,
port = 51838
How to solve this I\ve tried everything,
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    ru-TM)
    • Flutter version 2.0.6 at /Users/lacyn/FlutterSDK/flutter
    • Framework revision 1d9032c7e1 (11 дней назад), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lacyn/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,LOCALHOST
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
