### ISSUE TITLE
How to disable the dragging of the Switch ?

### ISSUE THREAD

**Issue by carlosbdw** [flutter/flutter#24857]
Now there is a switch in our app to show a shop is open or closed in my App,  it will show a dialog to confirm when I tap it , but if I drag the switch  from On to Off , and then I close the dialog ,the switch should remain On, but it becomes Off , so I want to disable the dragging ,is it possible?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

I'd suggest to ask on StackOverflow but please add some code that demonstrates what you try to accomplish.

**Comment by erdemyerebasmaz** [comment]
@carlosbdw Not sure if you still need this but you could remove onChanged of your Switch and wrap it with a GestureDetector.

```
bool _switchValue;
  @override
  initState() {
    super.initState();
   _switchValue = false;
  }

⋮
⋮
⋮

GestureDetector(
    onTap: () {
      if (this.mounted) {
        setState(() => _switchValue = !_switchValue);
      }
    },
    child: Switch(
      value: _switchValue,
      inactiveThumbColor: _switchValue
          ? Colors.white
          : Colors.grey.shade400,
      inactiveTrackColor: _switchValue
          ? Colors.white.withAlpha(0x80)
          : Colors.white30,
    ),
)

⋮
⋮
⋮

```
