### ISSUE TITLE
Was the name of the Flutter Gallery on the Play Store changed to Flutter Design Lab?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#24863]
If so we can run through and change the name in the code.
https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

**Comment by zoechi** [comment]
@ThinkDigitalRepair what are you referring to?
Can you post a link?

**Comment by ThinkDigitalRepair** [comment]
https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

**Comment by ThinkDigitalRepair** [comment]
Link added to post.

**Comment by BondarenkoStas** [comment]
Thank you @ThinkDigitalSoftware ! I checked, Flutter gallery is Flutter gallery, and there are no other Flutter Design Lab apps. Maybe I misunderstood the question, or it's fixed. Can you please clarify?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by ThinkDigitalSoftware** [comment]
No, it's not still an issue. Thanks
