### ISSUE TITLE
Markers on google maps need an id or tag set/get option

### ISSUE THREAD

**Issue by arnoraps** [flutter/flutter#24864]
Currently the marker id is generated and can change. I need to be able to set the id or a "tag" value on marker options to be able to see which marker is tapped.

**Comment by kjeremy** [comment]
Markers are pretty useless without this.

**Comment by frigopie99** [comment]
Meanwhile, you can wait for the Marker to be created and then use it as a key in a Map<Marker, <your_class>>. When an event is received just access to <your_class> instance using the Marker object included in the event.

**Comment by agustingp** [comment]
`//This is a hashmap used to store <id, information> of the markers.
  var map = <String, DocumentSnapshot> {};

  //This method is responsible for creating a new marker on the map and to link the generated ID to the proper data of the marker.
  // This hashmap will be used after by the onMarkerSelected function to retrieve the correct information about the selected marker.
  

  Future<Marker> addMarkerWrapper(MarkerOptions options, DocumentSnapshot ser) async {
   return mapController.addMarker(
      options
    ).then((marker){
        map[marker.id] = ser;
        return marker;
    });
  }


controller.onMarkerTapped.add((Marker marker){
      var selectedMarker = map[marker.id];
      print(selectedMarker.data['street']);
      print(selectedMarker.data['phone']);
      print(selectedMarker.data['www']);
    });

`

**Comment by ElHombreSinNombre** [comment]
Some update? Im trying similar in https://stackoverflow.com/questions/54790414/flutter-navigator-push-inside-infowindowtext/54790489 but doesn´t work.

**Comment by iskakaushik** [comment]
@arnoraps as of https://github.com/flutter/plugins/pull/1229 we added MarkerId to markers, that should solve your issue. Can you use `0.4.0` version of the plugin and let us know if it does not solve your use case?

**Comment by arnoraps** [comment]
Yes, markerId works as wanted/expected
