### ISSUE TITLE
hot reload does not reload when hit Cmd + Save in VSvode, Android Studio, Vim

### ISSUE THREAD

**Issue by LBroy** [flutter/flutter#24870]
## Steps to Reproduce

1. open a new flutter project in vscode, android studio or vim
2. flutter run
3. change the default main.dart line 21 from "primarySwatch: Colors.blue," to "primarySwatch: Colors.green,"
4, cmd + s => doesn't trigger the hot reload

## Logs

flutter run:
[flutterrunverbose.txt](https://github.com/flutter/flutter/files/2630872/flutterrunverbose.txt)

flutter analyze: no issues found

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.12, on Mac OS X 10.14 18A391, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)
```
• No issues found!

**Comment by robikovacs** [comment]
You have to run flutter from the debug menu in vs code.

<img width="249" alt="screenshot 2018-11-30 at 01 08 05" src="https://user-images.githubusercontent.com/5718030/49260132-77cdef00-f43c-11e8-9c97-ed27f211448f.png">

**Comment by zoechi** [comment]
@LBroy If you run it from terminal you need to press <kbd>r</kbd> in the terminal window.
If you run it as mentioned by @robikovacs and saving doesn't hot-reload 
please add a comment and I'll reopen the issue.

**Comment by LBroy** [comment]
@robikovacs @zoechi 
Thanks for the reply.
It does work now. Is there any ways I can use terminal as well as using the hot-reload?

**Comment by zoechi** [comment]
@LBroy 

> It does work now. Is there any ways I can use terminal as well as using the hot-reload?

I don't understand what you mean.
My suggestion was for the terminal.

Can you please rephrase your question?
