### ISSUE TITLE
Excessive slowdown in Material Gallery in checked mode

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2487]
The "List" demo in the Material Gallery takes almost a second to open and to update when changed (running on 1+1). Although this is checked mode and performance is expected to take a hit, this seems excessive.

### Steps to Reproduce
Open the Material Gallery
Tap Components
Tap List
Note the time it takes to open the list.
Tap menu in the top right (underneath the Slow Mode banner)
Tap Dense Layout, at the bottom of the screen
Note that it takes almost a second to update after you tap the checkbox.

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: a5887b6fb41c3a5e343c6132bb89cb1c10fafb95 (20 hours ago)
Engine:    70b92500df0006a9756fb9302a431322456a38fd
```

**Comment by abarth** [comment]
I think we have some O(n^2) asserts in checked mode.  That's probably too much asserting.

**Comment by abarth** [comment]
This affects the front page of the gallery now that we're using lists there too.

**Comment by eseidelGoogle** [comment]
customer: leafy uses a list in their app, and even in non-checked mode it drops a frame switching to it.  I'm happy to file a separate issue for that specific case if necessary. Checked mode drops several frames. :)

**Comment by abarth** [comment]
> even in non-checked mode it drops a frame switching to it

Please file a separate issue for that problem.  This issue is about unacceptable checked mode performance.

> Checked mode drops several frames.

Dropping several frames in checked mode is fine.  The performance goals for checked mode are "reasonably interactive".  The current behavior in checked mode of gallery app pauses for quite a while, which isn't very interactive.
