### ISSUE TITLE
White Screen - App content failed to load after launch released iOS app

### ISSUE THREAD

**Issue by geniecoder** [flutter/flutter#24887]
I was upload my new flutter app to AppStore and it's got rejected due to this problem...
"the app content failed to load after we launch. "

But it's working fine when I test it on Simulator and as well as connected real device. But problem has been arising when I export the ipa for internal testing. After installed the exported ipa, when I launch it nothing is loading, just white screen.

I am using Xcode 10.1 and my selected method of distributiontion is 'Development'

Then I decide to debug the project and for this I just created new flutter project (with default code, floating button and counter functionality). And export ipa by using same Bundle Id and certificate/provisioning and same method. It was working fine!

Then I added the dependencies in `.yaml` file for this project, and export again without added any other code. Then the same problem is came to new project also.

I am using for libraries:

`image_picker: ^0.4.10`. ----------- (white screen problem)
`path_provider: ^0.4.1` -------------(white screen problem)
`flutter_colorpicker: ^0.1.0` --------- (working fine)
`after_layout: ^1.0.7` ---------------- (working fine)

And the problem is with two libraries only, `image_picker` and `path_provider`. And `flutter_colorpicker` and `after_layout` working fine.

But don't know why all four libraries working fine when I test on connected iOS device and Simulator. problem is only arise when I export the ipa.

Please help me.

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 0.11.3 at /Users/mandeep/development/flutter
    • Framework revision 72bf075e8d (3 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/mandeep/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • iPhone XR • AA94ED49-A1D7-46B7-8FDB-696A8E2E68FC • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by ZeroCool00** [comment]
same problem here when test exported ipa..

**Comment by geniecoder** [comment]
My problem is solved. now let me solve yours

Did you run "flutter build ios --release" command before exporting ipa from Xcode?

if not then run this command in terminal and make sure you are in the project directory. I spend lots of time to find this problem, and this is happened because I miss that step when reading iOS release documentation.

You can read documentation on flutter.io, this step is under "Create a build archive" 
https://flutter.io/docs/deployment/ios

If you problem not fixed then let me know, or if you are now facing problem in release command then update your flutter.

**Comment by ZeroCool00** [comment]
@geniecoder  brilliant brother.. it worked. Thank you so much

**Comment by zoechi** [comment]
Probably related to #24641

**Comment by timbergus** [comment]
Probably relate with #25167 too.

**Comment by AndroidNils** [comment]
> @ZeroCool00 My problem is solved. now let me solve yours
> 
> Did you run `flutter build ios --release` command before exporting ipa from Xcode?
> 
> if not then run this command in terminal and make sure you are in the project directory. I spend lots of time to find this problem, and this is happened because I miss that step when reading iOS release documentation.
> 
> You can read documentation on flutter.io, this step is under "Create a build archive"
> https://flutter.io/docs/deployment/ios
> 
> If you problem not fixed then let me know, or if you are now facing problem in release command then update your flutter.

You are awesome!

**Comment by AizenSousek** [comment]
thx,fix it

**Comment by franzejr** [comment]
@geniecoder this would be the same thing if you're deploying it via fastlane, right ?

```desc "Push a new beta build to TestFlight"
  lane :beta do
    alphaBuild
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", configuration: 'Release')
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Increment the build number based on the number of commits"
  lane :alphaBuild do
    # Return the number of commits in current git branch
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios","--build-number=#{build_number}","--release" ,"lib/main_staging.dart")
    end
  end
```

I'm running the `beta` lane which does the `build ios --release` before deploying the app. Sometimes I still get blank screens :/

**Comment by Jartz** [comment]
try the next line
```
flutter clean
flutter build ios
flutter install
```

**Comment by leonardop21** [comment]
GoogleService-Info inside the runner / runner folder inserted through x-code, I followed all the recommended steps, even though the application when sent to production gets the white screen when starting.

Flutter clean
flutter build ios --release 

Xcode
Product -> Clean
                   Archive
                  Upload App Store


Any idea what that might be?

**Comment by juanjoserodrigolazaro97** [comment]
same problem this is terrible :/

**Comment by jaumard** [comment]
It work when I do:
```
flutter clean
flutter build ios --release
```
And after `Archive` in Xcode and it works. But if instead of using xcode I want to use fastlane my app get refused because it's empty. 
Here is my lane: 
```
lane :beta do
    sh "cd ../.. && flutter clean && flutter build ios --release --target=lib/main-prod.dart"
    get_certificates
    get_provisioning_profile
    build_app(scheme: "Runner",
                  export_method: "app-store",
                  workspace: "Runner.xcworkspace"
                 )

    upload_to_testflight {
        skip_waiting_for_build_processing
    }

  end
```
It was working for a while but I guess since the last stable it's not for some reason

**Comment by jaumard** [comment]
@franzejr unfortunately no :/ I just do manual release for now. Didn't have time to check what's wrong with fastlane build...

**Comment by consuelogranata** [comment]
> GoogleService-Info inside the runner / runner folder inserted through x-code, I followed all the recommended steps, even though the application when sent to production gets the white screen when starting.
> 
> Flutter clean
> flutter build ios --release
> 
> Xcode
> Product -> Clean
> Archive
> Upload App Store
> 
> Any idea what that might be?

Same problem here. Any solution found? This is very annoying!!

**Comment by GreenBayRules** [comment]
I'm getting the same problem ^

**Comment by GreenBayRules** [comment]
doing `pod update` worked for me

**Comment by feudadrien** [comment]
@consuelogranata follow the steps as written

### DO THIS BELOW

**Xcode** (Good to do)
Product -> Clean

**IDE/Command-line** (Must do to fix)
Flutter clean
flutter build ios --release

**Xcode** (Have to do anyways)
Archive
Upload App Store

### DO NOT DO THIS BELOW

Flutter clean (Cleans the build directory - where ipa file is)
flutter build ios --release (Builds the release ipa file and creates build directory)

Xcode
Product -> Clean (Cleans the build directory - deletes the ipa file) <--- ISSUE
Archive (Uses the build directory - but from above, ipa is deleted)
Upload App Store (Uploads empty build) :(

**Comment by jmagman** [comment]
I believe regenerating the Podfile as instructed with the new warning in https://github.com/flutter/flutter/pull/42029 (v1.10.15, so currently dev and beta channels) mitigates the ongoing issue where the wrong version of the Flutter.framework is embedded in the app.

**Comment by jmagman** [comment]
I'm going to close this as fixed with https://github.com/flutter/flutter/pull/42029.  That fix is on master, dev, and beta channels, but not yet on stable.

If you are on master, dev, or beta, follow the instructions you get in the warning by regenerating your Podfile via `rm ios/Podfile` then `flutter build ios` again.  You can switch back to stable once you get the updated Podfile.

Closing.  Please comment if anyone hits this issue after regenerating your Podfile on the master, dev, or beta channels.
