### ISSUE TITLE
Bad resource table: header size 0x4912 or total size 0xfc6a2e09 is larger than data size 0x3f4ec

### ISSUE THREAD

**Issue by salehzarei** [flutter/flutter#24888]
Hi 
I have new Problem after Update Flutter and Dart .

```
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.5s
Resolving dependencies...                                    7.2s
W/ResourceType( 2284): Bad resource table: header size 0x4912 or total size 0xfc6a2e09 is larger than data size 0x3f4ec
ERROR: dump failed because the resource table is invalid/corrupt.

Oops; flutter has exited unexpectedly: "Exit code 1 from: D:\SDK\build-tools\28.0.3\aapt dump xmltree C:\Users\...\....\scarlett\build\app\outputs\apk\app.apk AndroidManifest.xml".
```

**Comment by salehzarei** [comment]
> Please add the output of `flutter dictor -v`.
> Can you reproduce with a new project?
> What steps are necessary to reproduce?

Yes no problem to reproduce new project !
and result for doctor -v is :
PS C:\Users\Saleh\Documents\scarlett> flutter doctor -v
[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 0.11.13 at C:\Users\Saleh\flutter
    • Framework revision 58c8489fcd (35 hours ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\Saleh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.0

**Comment by zoechi** [comment]
Can you please run in the Flutter install directory

```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```
to ensure your Flutter installation is not corrupted.

**Comment by salehzarei** [comment]
> Can you please run in the Flutter install directory
> 
> ```
> git clean -xfd
> git stash save --keep-index
> git stash drop
> git pull
> flutter doctor
> ```
> to ensure your Flutter installation is not corrupted.

Excellent My friend , after the implementation of these commands, the problem was fixed !
Thank you
