### ISSUE TITLE
RenderParagraph.debugDescribeChildren broken

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2489]
03-08 10:35:01.964 E/flutter (18114): NoSuchMethodError: incorrect number of arguments passed to method named 'toString'
03-08 10:35:01.964 E/flutter (18114): Receiver: null
03-08 10:35:01.964 E/flutter (18114): Tried calling: toString("             │                 │       ║     ")
03-08 10:35:01.964 E/flutter (18114): Found: toString()
03-08 10:35:01.964 E/flutter (18114): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
03-08 10:35:01.964 E/flutter (18114): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
03-08 10:35:01.964 E/flutter (18114): #2      TextSpan.toString (packages/flutter/src/painting/text_painter.dart:116)
03-08 10:35:01.964 E/flutter (18114): #3      TextSpan.toString (packages/flutter/src/painting/text_painter.dart:121)
03-08 10:35:01.964 E/flutter (18114): #4      RenderParagraph.debugDescribeChildren (packages/flutter/src/rendering/paragraph.dart:121)
03-08 10:35:01.964 E/flutter (18114): #5      RenderObject.toStringDeep (packages/flutter/src/rendering/object.dart:1703)

**Comment by apwilson** [comment]
I don't really care about this other than debugDumpRenderTree was broken.

**Comment by Hixie** [comment]
I think this is actually a bug on your side, in that the only way I could find for this to happen is if you have a TextSpan whose children include a null value, which isn't valid. I'm going to assert the heck out of that particular case to try to catch it early. And then make the toString resilient against it.

**Comment by Hixie** [comment]
Oh, never mind. I see the problem.

**Comment by abarth** [comment]
Looks like this fix was merged already.
