### ISSUE TITLE
how can chinese user install Dart SDK

### ISSUE THREAD

**Issue by aboutmydreams** [flutter/flutter#24896]
when i run 
root@ncuhome-PC:/home/ncuhome/dwhkaifa# export PUB_HOSTED_URL=https://dart-pub.mirrors.sjtug.sjtu.edu.cn
root@ncuhome-PC:/home/ncuhome/dwhkaifa# flutter doctor

then:
'''
Downloading Dart SDK from Flutter engine 7375a0f414bde4bc941e623482221db2fc8c4ab5...
** Resuming transfer from byte position 51738550
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

Failed to retrieve the Dart SDK at https://mirrors.sjtug.sjtu.edu.cn//flutter_infra/flutter/7375a0f414bde4bc941e623482221db2fc8c4ab5/dart-sdk-linux-x64.zip
If you're located in China, please follow
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

'''

**Comment by lishuhao** [comment]
> If you're located in China, please follow
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
