### ISSUE TITLE
Automatically detect which assets are needed

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#249]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 18:14 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1914_

---

We should find a way to automatically determine what assets are needed. For instance, we could have constants for each material design icon, rather than using strings to identify them, and we could then determine, when the app is snapshotted, which of the constants get referred to.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/j9brown"><img src="https://avatars.githubusercontent.com/u/102276?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [j9brown](https://github.com/j9brown)**
_Tuesday Nov 03, 2015 at 18:57 GMT_

----

This sort of thing could be quite useful if developers ship multiple
versions of apps optimized for different targets by allowing unused assets
to be stripped out.

**Comment by Hixie** [comment]
We don't need this for the icons anymore now that we use a font and the font is small enough that we don't care. Still would be good to do this eventually.

**Comment by Hixie** [comment]
It's not clear how we would do this. We're going to close this for now and open a new bug when we have a clearer idea of how to address it.
