### ISSUE TITLE
gRPC takes forever to build after adding cloud firestore dependency 

### ISSUE THREAD

**Issue by JosephDunivan** [flutter/flutter#24909]

**Comment by JosephDunivan** [comment]
Adding gRCP as a dependency reduced build time for 200s to 57s. 
Has anyone else had this issue?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Which versions of grpc and cloud_firestore were added to `pubspec.lock`?

**Comment by JosephDunivan** [comment]
I actually leave them blank so the most up to date version. No issues with flutter doctor at all.

**Comment by zoechi** [comment]
> the most up to date version

That doesn't guarantee that you get the latest version. 

If for example grpc and cloud_firestore depend on the same transitive dependency B and latest grpc doesn't yet support the latest version of B, `flutter packages get` might end up fetching an older version of cloud_firestore that is compatible with the version of B grpc is compatible with.

So it's usually a good idea to occassionally check if `pubspec.lock` actually contains the version you expect. Especially if something is behaving weirdly.

**Comment by JosephDunivan** [comment]
Is there a way to find the recommended versions to use with Flutter so I can add them to my pubspec?

**Comment by zoechi** [comment]
That depends on the Flutter version you are using and how up-to-date your other dependencies are that you are using. Usually the latest available version is a good bet unless it introduced a bug and you want revert to a previous version. 

I'm just saying that you should check if you actually got what you expected.

When #12627 is fixed this will make this information available immediately when `flutter packages get` is run.

**Comment by zoechi** [comment]
>  No issues with flutter doctor at all.

that's the least relevant output of `flutter doctor -v` ;-) Please post the rest.

**Comment by JosephDunivan** [comment]
```terminal

[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.3 18D21c, locale en-US)
    • Flutter version 1.0.0 at /Users/josephdunivan/library/development/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/josephdunivan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/josephdunivan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1
```

**Comment by JosephDunivan** [comment]
To clarify, before adding any Firestore dependency I experienced normal build times under a min. After adding any Firestore dependecy I experienced build times that could take up to 200 seconds or longer, almost 4 min long(that's ridiculous). When I went into xcode during the build process I noticed that gRCP now wanted to download over 300 files, which was not the case before adding Firestore.

**Comment by orestesgaolin** [comment]
Do all versions of cloud_firestore cause this issue? On Bitrise CI after adding cloud_firestore dependency the build time increased from few minutes to about 20 minutes. More about similar [issue here](https://github.com/flutter/flutter/issues/27771#issuecomment-491541586) #27771

**Comment by fresswolf** [comment]
> Adding gRCP as a dependency reduced build time for 200s to 57s.
> Has anyone else had this issue?

Can you link to said gRCP dependency? I can't find it

**Comment by jmagman** [comment]
This is being tracked in FirebaseExtended.  See https://github.com/FirebaseExtended/flutterfire/issues/349.

**Comment by jimmont** [comment]
a working solution with more detail at https://github.com/flutter/flutter/issues/37582#issuecomment-667997839

**Comment by peternielsen112** [comment]
I have this issue. The build time is over 20 minutes after adding Firebase packages to `pubspec.yaml`. This is with adding a couple lines of code to the default app:
```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_analytics/firebase_analytics.dart';


Future main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();

  runApp(MyApp());
}
```
These are the only changed lines of code. Somehow the build time takes 15-20 minutes without exception. What's going on?
