### ISSUE TITLE
Unable connect to https://pub.dartlang.org from Brazil

### ISSUE THREAD

**Issue by AndrePech** [flutter/flutter#24904]
I am trying to start a new flutter project but it is now working because I cannot connect to https://pub.dartlang.org. Is it down or something?

I have tried pinging it with no success. Even the Browser cannot open the website.

Sorry if it is duplicate.

I will try to use a VPN. Thanks

**Comment by zoechi** [comment]
Probably just an intermittent issue
or an issue with your network.

**Comment by zoechi** [comment]
See also https://github.com/dart-lang/pub/issues/1989

**Comment by AndrePech** [comment]
I had to use a VPN in order to connect to it, my network was fine.

It is working fine already. Since this morning!. (Without vpn). Thanks!
