### ISSUE TITLE
Flutter Expansion Tile -- Header Color Change, and Trailing Animated Arrow Color Change

### ISSUE THREAD

**Issue by buddhika-ranasinghe** [flutter/flutter#24917]
I have used the Expansion Tile to generate a Expansion List View.
I'm facing some customization issues in Expansion Tile Header.

Below is my code.

```dart
ExpansionTile(           
    title: Container(
        child: Text(
            getCategory(i),
            style: TextStyle(
            color: Colors.white,
            ),
        ),
        color: Colors.black
    ),
    
    children: <Widget>[
        new Container(
            height: 60.0,
            margin: const EdgeInsets.only(top:10.0, left: 10.0, right:10.0, bottom: 10.0),
            decoration: BoxDecoration(                    
            color: Colors.blue,
            borderRadius: new BorderRadius.all(  Radius.circular(5.0) ),
            ),
        ),
        new Container(
            height: 60.0,
            margin: const EdgeInsets.only(top:10.0, left: 10.0, right:10.0, bottom: 0.0),
            decoration: BoxDecoration(                    
            color: Colors.green,
            borderRadius: new BorderRadius.all(  Radius.circular(5.0) ),
            ),
        )
    ],
    backgroundColor: Colors.white,
)
```

I'm getting below result.

![sample](https://user-images.githubusercontent.com/13096009/49344889-fcba4200-f6a2-11e8-9f8e-0ff7c0d32355.png)

What I'm expecting to have is below.

![req](https://user-images.githubusercontent.com/13096009/49344921-879b3c80-f6a3-11e8-8179-a6b018b6e64d.png)

If anyone know a workaround to customize the header color, please advice.

**Comment by diegoveloper** [comment]
First, this question is not a bug for Flutter, it should be in Stackoverflow.

If you check the source code of the ExpansionTitle , you will notice that the header item is a ListTile , so you can't change the background because it hasn't a parent with a color property. 
I modified a little the class to support what you need.

Add this file to your project: https://gist.github.com/diegoveloper/02424eebd4d6e06ae649b31e4ebcf53c

And import like this way to avoid conflicts because the same name.

```
import 'package:nameofyourapp/custom_expansion_tile.dart' as custom;
```
I put an alias 'custom' but you can change for any alias.

Usage: 

```
custom.ExpansionTile(
          headerBackgroundColor: Colors.black,
          iconColor: Colors.white,
          title: Container(
          ...

```

Remember, Flutter has a lot of Widgets out of the box, but If any of them fit what you need, you'll have to check the source code and create your own widget.

**Comment by buddhika-ranasinghe** [comment]
Thanks a lot Guys, @diegoveloper Thanks a lot for your support on this.
Happy to see this goes on as a milestone for next release.

**Comment by zoechi** [comment]
@diegoveloper see also https://stackoverflow.com/questions/53584678/flutter-expansion-tile-header-color-change-and-trailing-animated-arrow-color?noredirect=1#comment94227132_53584678

**Comment by zoechi** [comment]
Looks like this is answered. Thanks @diegoveloper

**Comment by KlubAndroid** [comment]
> First, this question is not a bug for Flutter, it should be in Stackoverflow.
> 
> If you check the source code of the ExpansionTitle , you will notice that the header item is a ListTile , so you can't change the background because it hasn't a parent with a color property.
> I modified a little the class to support what you need.
> 
> Add this file to your project: https://gist.github.com/diegoveloper/02424eebd4d6e06ae649b31e4ebcf53c
> 
> And import like this way to avoid conflicts because the same name.
> 
> ```
> import 'package:nameofyourapp/custom_expansion_tile.dart' as custom;
> ```
> 
> I put an alias 'custom' but you can change for any alias.
> 
> Usage:
> 
> ```dart
> custom.ExpansionTile(
>           headerBackgroundColor: Colors.black,
>           iconColor: Colors.white,
>           title: Container(
>           ...
> ```
> 
> Remember, Flutter has a lot of Widgets out of the box, but If any of them don't fit what you need, you'll have to check the source code and create your own widget.

Hi i know this is bit old, but is there a way to override gradient property instad solid color for the header in ExpandableTile? 
This is what im trying to do: [https://stackoverflow.com/questions/60409018/how-to-add-gradient-to-header-expansiontile-in-flutter](url)

**Comment by KlubAndroid** [comment]
> First, this question is not a bug for Flutter, it should be in Stackoverflow.
> 
> If you check the source code of the ExpansionTitle , you will notice that the header item is a ListTile , so you can't change the background because it hasn't a parent with a color property.
> I modified a little the class to support what you need.
> 
> Add this file to your project: https://gist.github.com/diegoveloper/02424eebd4d6e06ae649b31e4ebcf53c
> 
> And import like this way to avoid conflicts because the same name.
> 
> ```
> import 'package:nameofyourapp/custom_expansion_tile.dart' as custom;
> ```
> 
> I put an alias 'custom' but you can change for any alias.
> 
> Usage:
> 
> ```dart
> custom.ExpansionTile(
>           headerBackgroundColor: Colors.black,
>           iconColor: Colors.white,
>           title: Container(
>           ...
> ```
> 
> Remember, Flutter has a lot of Widgets out of the box, but If any of them don't fit what you need, you'll have to check the source code and create your own widget.

**Comment by EngrTAHAR-Noureddine** [comment]
thank you =)
