### ISSUE TITLE
android_alarm_manager 0.2.0 No implementation found for method AlarmService.initialized on channel plugins.flutter.io/android_alarm_manager_background 

### ISSUE THREAD

**Issue by Jobesco** [flutter/flutter#24915]
Hey,so...
Problem is as its described, I tried running the code on README, and I get this:

```
PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference, null)

MissingPluginException(No implementation found for method AlarmService.initialized on channel plugins.flutter.io/android_alarm_manager_background)
```
Code is flutter's basic initial template,adding the code given in README and following the implementation steps.

Also,on 
```
<service
            android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
            android:exported="false"/>
```
which you're supposed to insert in `AndroidManifest.xml`, I get the tooltip that "androidalarmanager" is an unresolved package(although i did everything i was told to in the package page.

Thanks in Advance, and sorry for the lack of Markdown in this Issue.

**Comment by Jobesco** [comment]
Also,here's flutter doctor -v:
`[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [Version 10.0.16299.492], locale pt-BR)
    • Flutter version 0.11.13 at D:\Users\ljba\Desktop\flutter
    • Framework revision 58c8489fcd (3 days ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Users\ljba\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected device (1 available)
    • Redmi 4X • 6ca0f9f7d440 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!`

**Comment by zoechi** [comment]
Looks similar to #24708, #22427, #5594
#https://github.com/flutter/flutter/issues/20697#issuecomment-413825700 also has some related discussion

Closing as dup of #21969
