### ISSUE TITLE
Error on starting app : Could not load source

### ISSUE THREAD

**Issue by jagdishjadeja** [flutter/flutter#24912]
After recently upgrading flutter i am facing this error and app runs but it misbehaves 
mishbehave means it doesnt do anything when pressed on buttons then suddenly app stops
now when i run same app 2nd time it works.

`Could not load source 'dart:core/runtime/liberrors_patch.dart': <source not available>.`

flutter version :

```
flutter 0.11.13 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 58c8489fcd (2 days ago) • 2018-11-29 19:20:18 -0500
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by chadidi** [comment]
@zoechi Same error here when using: [shared_preferences plugin](https://pub.dartlang.org/packages/shared_preferences)

like this:
```
final SharedPreferences prefs = await SharedPreferences.getInstance();
prefs.setString('api_token', resp.api_token);
```
after commenting out this 2 lines it works as expected.

**Comment by schrizzity** [comment]
I had this error as well. After looking in my call stack, the call prior to this error was noSuchMethod (https://docs.flutter.io/flutter/dart-core/Object/noSuchMethod.html)
I was trying to return a null object.

**Comment by zoechi** [comment]
Can you please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted to ensure the Flutter installation is ok?

**Comment by DanTup** [comment]
The error about source missing is because an assert has failed and VS Code wants to show you the source code, but the SDK doesn't include it. VS Code is intended to walk up the stack to source code that is available, but it's not working correctly (see https://github.com/Microsoft/vscode/issues/64193 - and add a 👍 while you're there!).

To understand why the assert failed, you should navigate up the call stack (using the Call Stack view on the Debug side bar) to the first (top-most) frame that has source, and review the condition in the `assert()` call.

It's also possible the exception is visible in the Variables view on the same Debug side bar that might contain a text description of the failure.

**Comment by jagdishjadeja** [comment]
resource is missing from flutter SDK ?

**Comment by DanTup** [comment]
> resource is missing from flutter SDK ?

The (Dart) SDK ships with pre-built snapshots for some of its internals, without the source code. I believe this may change in the future (sources may be included), but VS Code is also likely to get a fix that will allow us to take you to your code instead of the internal code.

For now, as a workaround, you can use the Call Stack to navigate up to your own code where the error occurred.

**Comment by asifMojtoba** [comment]
I faced this error too; then, I found a really easy solution: I've started using VPN before doing anything related to Flutter. Following that I don't face any problem now regarding to this topic.

**Comment by jagdishjadeja** [comment]
thats true sometimes my flutter project doesnt starts without internet

**Comment by chadidi** [comment]
> @zoechi Same error here when using: [shared_preferences plugin](https://pub.dartlang.org/packages/shared_preferences)
> 
> like this:
> 
> ```dart
> final SharedPreferences prefs = await SharedPreferences.getInstance();
> prefs.setString('api_token', resp.api_token);
> ```
> 
> after commenting out this 2 lines it works as expected.

@jagdishjadeja This problem in my case happened because of the variable `resp` was null.

**Comment by MaxZubko** [comment]
![image](https://user-images.githubusercontent.com/45923184/51679123-bcae7600-1fe6-11e9-88e1-dbb868e75c49.png)
I can not get rid of this error


```
Future<List<Widget>> getTeamPages(String idLeague) async {
    var data = await http.get(
        "https://www.thesportsdb.com/api/v1/json/1/lookup_all_teams.php?id=$idLeague");
    
    
    List<Widget> listTeamPages = [];
    
    var jsonData = json.decode(data.body);
    
    for (var s in jsonData["teams"]) {
```

**Comment by DanTup** [comment]
@MaxZubko on the left hand side under "Call Stack" click on the second line down (LeagueInfoState.getTeamPages) and it should show the exception popup.

**Comment by DanTup** [comment]
But also, from your screenshot I can see the exception text starts "Unexpected character" and that's because the response from your URL you're calling is outputting HTML messages in what you're expecting to be JSON:

```
<br />
<b>Warning</b>:  Unknown column xxx
```

**Comment by DanTup** [comment]
@MaxZubko If you hover your mouse over "data.body" on the highlighted line, you'll see that it's not valid JSON, which is why it's failing. Whether this is related to the value you're passing, or the API being broken I'm not sure.

**Comment by MaxZubko** [comment]
`Could not load source 'dart:core/runtime/liberrors_patch.dart': <source not available>.`

@DanTup I can not understand what is the error  ?


![default](https://user-images.githubusercontent.com/45923184/51756908-beea0080-20ca-11e9-8848-4e94d6d060e1.png)

**Comment by belichenk0andreyka** [comment]
![202](https://user-images.githubusercontent.com/46218433/51805723-d15a6a80-2281-11e9-8764-76974c1cf4a1.png)
![203](https://user-images.githubusercontent.com/46218433/51805724-d15a6a80-2281-11e9-9d95-5d8c885f87d1.png)
![201](https://user-images.githubusercontent.com/46218433/51805722-d15a6a80-2281-11e9-8f1b-5d40284e72af.png)

**Comment by MaxZubko** [comment]
![default](https://user-images.githubusercontent.com/45923184/51917951-52804180-23e9-11e9-9ec5-bc4a0299c089.png)

What could be the reason ?

**Comment by zoechi** [comment]
@MaxZubko I guess you copied code from a GitHub issue that only works with the maps package from GitHub because some changes are not yet published to pub.dartlang.org.

**Comment by MaxZubko** [comment]
@zoechi  Why not showing my location ?

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MyMap extends StatefulWidget {
  @override
  MyMapState createState() => MyMapState();
}

class MyMapState extends State<MyMap> {
  GoogleMapController mapController;

  final LatLng _center = const LatLng(50.006406, 36.236484);

  void _onMapCreated(GoogleMapController controller) {
    mapController = controller;
    mapController.addMarker(
      MarkerOptions(
        position: LatLng(50.006406, 36.236484),
        infoWindowText: InfoWindowText('My Location', 'Office'),
        icon: BitmapDescriptor.defaultMarker,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Map'),
          backgroundColor: Colors.green[700],
        ),
        body: GoogleMap(
          onMapCreated: _onMapCreated,
          options: GoogleMapOptions(
            scrollGesturesEnabled: true,
            tiltGesturesEnabled: true,
            rotateGesturesEnabled: true,
            myLocationEnabled: true,
            compassEnabled: true,
            cameraPosition: CameraPosition(
              target: _center,
              zoom: 11.0,
            ),
          ),
        ),
      );
  }
}
```

**Comment by zoechi** [comment]
@MaxZubko 

> Why not showing my location ?

Is this related to 

> Error on starting app : Could not load source

If not, then please lets stay focused at the issue topic.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by DanTup** [comment]
Are there still issues here? The issue with showing `<source not available>` should've been improved in the latest version of VS Code - it'll now jump to the correct stack frame with source instead of the top one. However, there were a number of different issues mixed up here.

**Comment by Annihilator708** [comment]
Bump.

I'm working on VSC with our private python application.
Out of no where a new tab opened up with the following text:
"Could not load source '<string>': Source unavailable."

My application is a python application existing out of
```
Package                  Version
------------------------ ---------
aiohttp                  3.5.2
alabaster                0.7.11
amqp                     1.4.9
anyjson                  0.3.3
appdirs                  1.4.0
astroid                  2.2.5
async-timeout            3.0.1
attrs                    18.2.0
Babel                    2.6.0
bcrypt                   3.1.0
billiard                 3.3.0.23
bleach                   3.0.2
blinker                  1.4
certifi                  2018.8.24
cffi                     1.11.5
chardet                  3.0.4
click                    6.7
colorama                 0.4.1
docutils                 0.14
factory-boy              2.11.1
Faker                    0.9.1
Flask                    0.12.2
Flask-Bcrypt             0.7.1
Flask-Cache              0.13.1
Flask-Classful           0.13.1
Flask-HTTPAuth           3.2.1
Flask-Login              0.4.0
Flask-Mail               0.9.1
Flask-Sessionstore       0.4.5
flask-swagger            0.2.13
flask-swagger-ui         3.6.0
Flask-WTF                0.12
gevent                   1.3.4
greenlet                 0.4.15
httpie                   1.0.2
huey                     1.2.3
idna                     2.7
idna-ssl                 1.1.0
imagesize                1.1.0
isort                    4.3.16
itsdangerous             0.24
Jinja2                   2.10
kombu                    3.0.37
lazy-object-proxy        1.3.1
lxml                     4.2.5
MarkupSafe               1.0
marshmallow              2.10.0
mccabe                   0.6.1
multidict                4.5.2
pip                      19.0.1
pipdeptree               0.10.1
pycparser                2.14
Pygments                 2.2.0
pylint                   2.3.1
pymssql                  2.1.3
pyodbc                   4.0.24
pyparsing                2.1.10
PyPDF2                   1.26.0
PyQRCode                 1.2.1
python-dateutil          2.6.0
pytz                     2016.7
PyYAML                   3.11
redis                    2.10.5
requests                 2.21.0
setuptools               40.6.2
six                      1.12.0
snowballstemmer          1.2.1
Sphinx                   1.6.5
sphinx-rtd-theme         0.2.4
sphinxcontrib-websupport 1.1.0
SQLAlchemy               1.0.14
suds-jurko               0.6
text-unidecode           1.2
typed-ast                1.3.1
typing-extensions        3.6.6
urllib3                  1.22
webargs                  1.3.4
webencodings             0.5.1
Werkzeug                 0.14.1
wfastcgi                 2.2.1
wheel                    0.32.3
wrapt                    1.11.1
WTForms                  2.1
yarl                     1.3.0
```
Very interesting this is happening, I expected my next view open up since i was working in breakpoint mode. Instead a new tab opened up with this message. This has never happend before.

**Comment by DanTup** [comment]
@Annihilator708 if you're seeing this message when debugging Python and not Dart/Flutter, you're best raising this against their extension. This error usually means the debugger failed to respond to VS Code's request for source code for the current location/frame. I can't guess why, as this is very language/debugger specific.

**Comment by Annihilator708** [comment]
@DanTup Yeah I do think you are right, This might be a more general issue which is not related to Flutter. I dont use Flutter at  all to my knowledge. I just experienced the exact same issue and started googling. Came out here.

> If you are using Dart/Flutter too, then we should open an issue in the Dart-Code repo and try to track it down.

Maybe this is a VSC related issue in general.  The weird part is after restating the debug mode everything works like it should work. I dont know if this workaround works for anyone here but it did do the trick for me. _So far_

**Comment by DanTup** [comment]
@Annihilator708 the error is fairly generic, so could happen for any language for many reasons. In Flutter/Dart it happened because the SDK stopped shipping source code for built-in libraries. This meant when an error occurred and the debugger tried to show the code that threw the error, it wasn't available.

There were a few fixes to address this, including:

1. When an error occurs, VS Code can now jump up the call stack instead of trying to show the top frame (this requires some work from the extension to mark which frames should be skipped)
2. The Dart SDK has started shipping sources for the SDK libraries again

I suspect your issue is entirely unrelated, but maybe this comes in handy if you see it again (if you do, I would recommend opening an issue against Python though for some investigation).
