### ISSUE TITLE
Missing onMapTapped in Google Maps Plugin

### ISSUE THREAD

**Issue by galebnas** [flutter/flutter#24919]
Thank you very much for your hard work on this plugin it is very important for us, I wish if you can add an onMapTapped Callback that returns the position where the user tapped.

I am working on a project where the user has to tap the map to select a location and I couldn't find the callback.

Thanks again

**Comment by iskakaushik** [comment]
https://github.com/flutter/plugins/pull/985 has merged, which adds support for onTap events for google map.
