### ISSUE TITLE
Unable to Launch app in iPhone device

### ISSUE THREAD

**Issue by ravi123saxena** [flutter/flutter#24929]
Hi All,

I am getting error while deploy app in iPhone device .
- Installed the app in device successfully but it is not launched by self.
- need to open the app manually .

Please check the below error , what i am missing ...

```
File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/FFA3CCBA-EF51-4680-B53F-8A33D17D754E/Runner.app"'
 
 2iPhone (ios)
Ln 8, Col 4Spaces: 4UTF-8LFJSON with Comments00
Flutter (hello_world)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Is `run_one_line` a name you introduced in your project or is it from Flutter?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
