### ISSUE TITLE
why my flutter plugin project is this in android studio?

### ISSUE THREAD

**Issue by s3hengwu** [flutter/flutter#24928]
![tim 20181203172157](https://user-images.githubusercontent.com/8500025/49364921-5ca2fe00-f720-11e8-8498-674294fa0f2a.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the steps that led to that result.
How did you create the project?

**Comment by s3hengwu** [comment]
![tim 20181204084136](https://user-images.githubusercontent.com/8500025/49410615-76842580-f7a0-11e8-891d-a32af10129e4.png)

**Comment by s3hengwu** [comment]
Android studio->new flutter project-> flutter plugin

**Comment by s3hengwu** [comment]
have already been solved.
![ok](https://user-images.githubusercontent.com/8500025/49412480-7b98a300-f7a7-11e8-9adb-e2052cec146f.png)
