### ISSUE TITLE
Unable to run test using firebase_auth

### ISSUE THREAD

**Issue by DanMossa** [flutter/flutter#24925]
## Steps to Reproduce

 I am attempting to run a test I created, this is the `unit_test.dart` 
```dart
import 'package:do_and_stuff/tools/auth.dart';
import 'package:test/test.dart';

void main() {
  test('No Username or Password', () async {
    final result = await Auth.signInEmailAndPassword("", "");
    expect("Missing", result);
  });
}
```

This is the code for `Auth.signInEmailAndPassword`
```dart
  static Future<dynamic> signInEmailAndPassword(
      String givenEmail, String givenPassword) async {
    try {
      FirebaseUser user = await _auth.signInWithEmailAndPassword(
          email: givenEmail, password: givenPassword);
      Auth.emailAddress = user.email;
      Auth.googleAccount = false;
      return true;
    } catch (error) {
      return "Missing";
    }
  }
```
## Logs

> Expected: 'Missing'
>   Actual: MissingPluginException:<MissingPluginException(No implementation found for method signInWithEmailAndPassword on channel plugins.flutter.io/firebase_auth)>
>    Which: not an <Instance of 'String'>
> 
> package:test             expect
> test\unit_test.dart 7:5  main.<fn>
> ===== asynchronous gap ===========================
> dart:async               _AsyncAwaitCompleter.completeError
> test\unit_test.dart      main.<fn>
> ===== asynchronous gap ===========================
> dart:async               _asyncThenWrapperHelper
> test\unit_test.dart      main.<fn>

```
flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 0.9.4 at C:\Users\Daniel\flutter
    • Framework revision f37c235c32 (10 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Daniel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • Pixel XL • HT73X0200063 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Native code of plugins can't run when launched with `flutter test`, only when the code runs on a device/emulator. 

You can try with `flutter run test/unit_test.dart`
(See also https://github.com/flutter/flutter/issues/24650#issuecomment-441692614)

See also https://docs.flutter.io/flutter/services/BasicMessageChannel/setMockMessageHandler.html

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by DanMossa** [comment]
Oh i see, yeah this seems to work when i run `flutter run test/unit_test.dart` .

I'm not gonna pretend I understand, this just seems a bit weird is all.

Any ideas on how to make this work when running on Android Studio?

**Comment by zoechi** [comment]
> Any ideas on how to make this work when running on Android Studio?

I assume you mean running tests with `flutter run` from IDE.
@DanTup ?

The suggestions to use `flutter run` was mostly to explain the reason you're running into this
and it can be convenient for debugging.

I doesn't work well with automated tests though.

`flutter test` runs a reduced environment and no native code that depends on iOS or Android SDK can be executed. You need to mock calls to MessageChannel (attempts to invoke native code) in your tests.

**Comment by DanTup** [comment]
> > Any ideas on how to make this work when running on Android Studio?
> 
> I assume you mean running tests with flutter run from IDE.
> @DanTup ?

I'm not very familiar with Android Studio but I would expect it knows when you're editing a Flutter project and will use `flutter run` automatically when you just the built-in run tests features.

**Comment by zoechi** [comment]
@DanTup sorry, I didn't read properly. I assumed VSCode otherwise I wouldn't have summoned you.

AS is the same as IDEA/WebStorm and you need to create a run configuration manually. 

![image](https://user-images.githubusercontent.com/405837/49368406-e76b0500-f6ee-11e8-9ebc-da3d041d26f4.png)

Open with `Edit configurations` and duplicate the configuration for `lib/main.dart` and edit the target file to make it point to `test/unit_test.dart`.
Then select the run configuration in above dropdown and click the run or debug toolbar icon.

**Comment by DanTup** [comment]
No worries - though tbh I wasn't sure where the quoted text came from, I couldn't see it in the messages above!

**Comment by zoechi** [comment]
@DanTup I might have even posted it on the wrong issue :D
Too many open windows I guess. Thanks anyway!
