### ISSUE TITLE
Support for Firebase In-App Messaging 

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#24933]
There needs to be some support for [Firebase In-App Messaging](https://firebase.google.com/products/in-app-messaging/) API in firebase_messaging package or for a new package to be created to support the API.

**Comment by filleduchaos** [comment]
The docs for In-App Messaging are pretty sparse at the moment, but it should be straightforward enough to write a plugin that displays messages using the views built into the Android/iOS SDKs. Having the message popup be completely customizable from Dart (i.e. displayed using Flutter widgets) might be a bit more complicated.

**Comment by filleduchaos** [comment]
(Also this probably should be a new plugin - they're separate APIs)

**Comment by zoechi** [comment]
Is this what https://pub.dartlang.org/packages/local_notifications, https://pub.dartlang.org/packages/flutter_local_notifications are providing?

**Comment by filleduchaos** [comment]
@zoechi 

No - it's a [new Firebase product](https://firebase.google.com/products/in-app-messaging/).

**Comment by ktomek** [comment]
@filleduchaos 
I think it doesn't require a plugin, just add dependencies as it is in firebase docs.

**Comment by EliasDeuss** [comment]
@ktomek I think that you might be right.

**Comment by NeroJz** [comment]
@ktomek @EliasDeuss  Can you share an example on how to process the in-coming message from In-App message?

**Comment by ktomek** [comment]
@NeroJz you don't have to process the message. What you have to do is just add dependencies on android(gradle) and iOS(pods) projects. No flutter/android/ios code is needed.
Then create a message in firebase console and run it.

**Comment by filleduchaos** [comment]
Yes that would work (and use the default message display for each platform). I think part of the request here is for a way to customize the way the message is displayed from Dart.

**Comment by EliasDeuss** [comment]
I don't think you can't customize the way it looks besides the Firebase website @filleduchaos

**Comment by filleduchaos** [comment]
@EliasDeuss The In-App Messaging docs are pretty clear about the fact that you can customize the way the message gets displayed.

**Comment by EliasDeuss** [comment]
@filleduchaos Those are only bools that change two things. Most of the customization is done on the Firebase website when you create a In-App Messaging campaign.

**Comment by filleduchaos** [comment]
@EliasDeuss I'm sorry, but did you bother reading the page at all? There's far more than "bools that change two things" on it - it even goes as far as laying out how to use the SDK in a headless manner (something I've done myself, so I hope you'll understand that I find your insistence a bit weird).

**Comment by Dnyaneshwar1926** [comment]
Question 1:-
In this popup the background color is not shown. It is always white (infact I changed the color on firebase console as per guidelines ). How can I change the background color?

Question 2:-
In this popup is always triggering in splash screen. I want it to trigger in main activity. How to do it?

**Comment by zukinaru** [comment]
> @filleduchaos
> I think it doesn't require a plugin, just add dependencies as it is in firebase docs.

but How to get `FirebaseInstanceId`, seems it different to FCM token ?

**Comment by a1lombx** [comment]
what is the dependencies to add?

**Comment by cimplesid** [comment]
> what is the dependencies to add?

https://www.youtube.com/watch?v=BwXmKuaZ45c

**Comment by cimplesid** [comment]
One who still have problem in setting up here is the video tutorial https://www.youtube.com/watch?v=BwXmKuaZ45c

**Comment by EliasDeuss** [comment]
what about iOS @cimplesid

**Comment by cimplesid** [comment]
> what about iOS @cimplesid

```
pod 'Firebase'
pod 'Firebase/InAppMessagingDisplay'
```
add these in pod file and then

`pod install`
in terminal
open YOUR-PROJECT.xcworkspace
Import the Firebase module in your UIApplicationDelegate, if you haven't yet:
`import Firebase`
Also configure a FirebaseApp shared instance, typically in your app's application:didFinishLaunchingWithOptions: method, if you haven't yet:
`FirebaseApp.configure()`
compile and run app and you are done

**Comment by yuwonom** [comment]
https://pub.dev/packages/firebase_in_app_messaging

**Comment by EliasDeuss** [comment]
Great to have a official way to add it now!

**Comment by kroikie** [comment]
@EliasDeuss

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/561. Any further collaboration will be done there.

**Comment by Abosrie** [comment]
I am getting this error in the IOS - Using latest version 

```
Xcode's output:
↳
    === BUILD TARGET firebase_storage OF PROJECT Pods WITH
    CONFIGURATION Debug ===
    /Users/ahmedabosrie/development/flutterSDK/.pub-cache/hosted/
    pub.dartlang.org/firebase_in_app_messaging-0.1.1+1/ios/Classe
    s/FirebaseInAppMessagingPlugin.m:33:5: error: unknown type
    name 'FIRInAppMessaging'; did you mean 'FIRMessaging'?
        FIRInAppMessaging *fiam = [FIRInAppMessaging
        inAppMessaging];
        ^~~~~~~~~~~~~~~~~
        FIRMessaging
    In module 'FirebaseMessaging' imported from
    /Users/ahmedabosrie/development/albyrakapp/ios/Pods/Headers/P
    ublic/Firebase/Firebase.h:72:
    /Users/ahmedabosrie/development/albyrakapp/ios/Pods/FirebaseM
    essaging/Firebase/Messaging/Public/FIRMessaging.h:270:12:
    note: 'FIRMessaging' declared here
    @interface FIRMessaging : NSObject
```
