### ISSUE TITLE
Clarify documentation for canTransitionFrom and To

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#24945]
Even with the following code, transitions between routes still execute:

```dart
class CustomPageRoute<T> extends MaterialPageRoute<T> {
  CustomPageRoute({
    @required WidgetBuilder builder,
    RouteSettings settings,
    bool fullscreenDialog = false,
  }) : super(
          builder: builder,
          settings: settings,
          fullscreenDialog: fullscreenDialog,
        );

  @override
  bool canTransitionTo(TransitionRoute<dynamic> nextRoute) => false;

  @override
  bool canTransitionFrom(TransitionRoute<dynamic> previousRoute) => false;
}
```

I also tried creating back-to-back full screen dialogs. According to source code comment here https://docs.flutter.io/flutter/material/MaterialPageRoute/canTransitionTo.html, that should cause exit animations not to execute but they still do.

**Comment by HansMuller** [comment]
The TransitionRoute canTransitionFrom() and canTransitionTo() methods are only used to configure the animation used for the route that's losing or gaining its place on the top of the navigator's stack of routes. If both methods return true and the new top route is a TransitionRoute then the new route's animation becomes the old route's "secondaryAnimation". A route that overrides buildTransitions() can use the secondaryAnimation parameter to customize the way it animates out of view. If the same route is exposed again, its secondary animation runs in reverse, to enable the route to define how it reappears.

For example this version of CustomPageRoute fades out when it another route is pushed on top of the navigator's stack. It fades back in when the route on top of it is popped off the navigator's stack.

```
class CustomPageRoute<T> extends MaterialPageRoute<T> {
  CustomPageRoute({
    @required WidgetBuilder builder,
    RouteSettings settings,
    bool fullscreenDialog = false,
  }) : super(builder: builder, settings: settings, fullscreenDialog: fullscreenDialog);

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
    return FadeTransition(
      opacity: Tween<double>(begin: 1.0, end: 0.0).animate(secondaryAnimation),
      child: child,
    );
  }
}
```

I apologize if you're already aware of all of this. The existing documentation for the two TransitionRoute methods isn't super helpful, I will be updating it.

The secondary animation does not run when a custom route's canTransitionTo() method returns false. Here's a complete app that demos as much.

https://gist.github.com/HansMuller/58fff6e2ff6bb6f7eb5615168bb24a75

So, all that to say that things are working as intended.  If your use case doesn't work this way, please help me understand what the use case is.

**Comment by mehmetf** [comment]
The documentation led me to believe that this is what we want for full screen dialogs when they are stacked (one dialog opens another one and so on).

The use case for Mulligan is to prevent route transition from happening upon exit given a route. They bring up a new page which may or may not launch a native controller on top. When the native controller goes away, they want to also pop the flutter page (at the same time) but they don't want it to execute its exit animation.
