### ISSUE TITLE
assertion failed: textDirection != null

### ISSUE THREAD

**Issue by leagmain** [flutter/flutter#24947]
I created a flutter module, and I want to use flutter create a card UI for my current APP.
But I always get an error for this, I can add the textDirection: TextDirection.ltr to fix this, but I dont want to do it.

Instead, after I changed it to MaterialApp, and use scaffold, I don't need to provide textDirection for my widget again.

How can I fix this issue?

**Comment by zoechi** [comment]
You can get the textDirection from the used locale from [GlobalWidgetsLocalizations](https://docs.flutter.io/flutter/flutter_localizations/GlobalWidgetsLocalizations-class.html) as `MaterialApp` does.

See also https://docs.flutter.io/flutter/widgets/WidgetsApp-class.html

**Comment by leagmain** [comment]
@zoechi thanks for your reply, I used MediaQuery and Directionaly wrapped my widget, and it works fine.
