### ISSUE TITLE
Show user-friendly error page instead of the exception

### ISSUE THREAD

**Issue by grandpa-guru** [flutter/flutter#24950]
Is it possible to make global error handling that will **show user-friendly error page instead of showing red exception**?

I already made error handling ([here](https://flutter.io/docs/cookbook/maintenance/error-reporting)) that will report exception to the backend but what I really would like to achieve is to hide red exception and show something a little bit friendlier.

I searched everywhere and I found literally nothing.

**Comment by wouterhardeman** [comment]
I believe the big red exception only appears in debug builds. Have you tried out a release build?

**Comment by grandpa-guru** [comment]
> 
> 
> I believe the big red exception only appears in debug builds. Have you tried out a release build?

Nope. I created a sample project and basically tried setting the property value of an uninstantiated object. 
```
MyClass myClass;
myClass.myProperty = "hey";
```

And I still got the red exception **in the release mode** saying:
```
The setter 'myProperty=' was called on null.
Receiver: null
Tried calling: myProperty="hey"
```

**Comment by zoechi** [comment]
You can register a custom error handler using
https://docs.flutter.io/flutter/foundation/FlutterError/onError.html
https://github.com/flutter/sentry has some tips for how to handle errors globally ("Tips for catching errors")

**Comment by zoechi** [comment]
> big red exception only appears in debug builds

I thought so as well but seems that only applies to layout issues like overflow

**Comment by wouterhardeman** [comment]
I digged around a bit and found out you can set the ErrorWidget builder. By using the builder you can implement a custom screen. I made a small example that you can find here: [https://gist.github.com/wouterhardeman/1f939e661e166a6ec119269c13bcbfba](https://gist.github.com/wouterhardeman/1f939e661e166a6ec119269c13bcbfba )

**Comment by grandpa-guru** [comment]
God bless you.

**Comment by zoechi** [comment]
@wouterhardeman nice one. Can't remember seeing that being mentioned.

**Comment by grandpa-guru** [comment]
@wouterhardeman To use those theme-defined styles I need to have the context object like this:

```
Widget getErrorWidget(BuildContext context, FlutterErrorDetails error) {
  return Center(
    child: Text(
      "Error appeared.",
      style: Theme.of(context).textTheme.title.copyWith(color: Colors.white),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ErrorWidget.builder = (FlutterErrorDetails errorDetails) {
      return getErrorWidget(context, errorDetails);
    };

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```
Any smarter way to do this?
