### ISSUE TITLE
RTSP (real time streaming) protocol in Flutter?

### ISSUE THREAD

**Issue by weekaung** [flutter/flutter#24960]
Hi Flutter Team,

Our company is developing an IoT Security solution which requires us to access live cameras using the rtsp protocol. On looking into the video_player plugin that you have developed, we realized that it does not support this protocol.

Will you be enabling this protocol in the near future? Or do you have a solution for our problem?
We would very much appreciate your help.

Thank you,
David Lee :>

**Comment by ened** [comment]
The video_player plugin will use https://github.com/google/ExoPlayer on Android and AVPlayer on iOS natively. Both don't support RTSP at the moment. 

For ExoPlayer, there is a open & actively developed pull request at https://github.com/google/ExoPlayer/pull/3854. If you want to support RTSP on Android in any way, this is the best place.

For iOS, things are a lot trickier. I have yet to encounter a open source, license-compatible RTSP implementation for iOS. `Live555` & `ffmpeg` ports usually work great, but can not legally be used in commercial projects - details here: http://www.live555.com/liveMedia/faq.html#copyright-and-license.

**Comment by incafox** [comment]
@weekaung opencv have rtsp support, there is a opencv package on the dartlang site

**Comment by weekaung** [comment]
Thank you, I will take a look into it.

**Comment by dazza5000** [comment]
How far did you get on this? Looking on how to add RTSP streaming video to a flutter app. Thank you!

**Comment by amadeu01** [comment]
With [FFI](https://dart.dev/server/c-interop) it could be possible to use some C/C++ library that supports RTSP and use it with Dart/Flutter. 
I guess it could be a workaround to not be limited by native implementations (iOS/Android)

**Comment by ZhuBoao** [comment]
There is a library called [`fijkplayer`](https://fijkplayer.befovy.com/docs/en/) which wraps the native [`ijkplayer`](https://github.com/Bilibili/ijkplayer) into flutter. It supports RTSP streaming.

**Comment by jsgalarraga** [comment]
Also `flutter_vlc_player` supports RTSP streaming

**Comment by Asncodes-80** [comment]
**fijkplayer plugin does not work in my project!!**
Hi there!
when i want to install dependency in pubspec.yaml i got error with `fijkplayer: ^0.8.7` or when i successed to install that i got 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fijkplayer:generateDebugRFile'.
> Could not resolve all files for configuration ':fijkplayer:debugRuntimeClasspath'.
   > Could not download fijkplayer-full.aar (com.befovy.fijkplayer:fijkplayer-full:0.7.6)
      > Could not get resource 'https://jcenter.bintray.com/com/befovy/fijkplayer/fijkplayer-full/0.7.6/fijkplayer-full-0.7.6.aar'.
         > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 14s
Exception: Gradle task assembleDebug failed with exit code 1

in continue:
and some problem with run in flutter, with difficult solution i will get :
`Unhandled Exception: MissingPluginException(No implementation found for method createPlayer on channel befovy.com/fijk)`
error in run time.
please help me to config and fix problem in flutter app.

**Comment by Asncodes-80** [comment]
I want to stream ip cameras with `rtsp` protocol, but i have used vlc_player and fijkplayer in my flutter app with **huge issues**, what plugin work well about that without any issues?? 
I'm in trouble in stream ip camera with rtsp protocol. Please help me for that my deadline is very close!

**Comment by Asncodes-80** [comment]
i have still that problem!! anyone can help me????

**Comment by AlaaEldeenYsr** [comment]
@Asncodes-80 This package supports RTMP urls and worked for me.
https://pub.dev/packages/ext_video_player
