### ISSUE TITLE
Problems with translation on flutter's official website

### ISSUE THREAD

**Issue by shifeng1993** [flutter/flutter#24962]
![flutter io](https://user-images.githubusercontent.com/20181287/49485867-6db25300-f877-11e8-858b-66b85a187d8a.png)

Flutter is out.

what？

In China, the word means to be eliminated.

**Comment by 39499740** [comment]
爱过，下一题

**Comment by chengenzhao** [comment]
用过，下一题

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1876](https://github.com/flutter/website/issues/1876) via [**ZenHub**](https://www.zenhub.com/)
