### ISSUE TITLE
 Can not open the Web page at the Observatory URL printed to the console

### ISSUE THREAD

**Issue by pukaicom** [flutter/flutter#24966]
flutter run Info
```
09:48:08.916 1 info flutter.tools Launching lib/main.dart on PH 1 in debug mode...
09:48:09.013 2 info flutter.tools Initializing gradle...
09:48:10.958 3 info flutter.tools Resolving dependencies...
09:48:17.091 4 info flutter.tools Gradle task 'assembleDebug'...
09:48:37.901 5 info flutter.tools Built build/app/outputs/apk/debug/app-debug.apk.
09:48:38.283 6 info flutter.tools Installing build/app/outputs/apk/app.apk...
```

Logcat

```
2018-12-05 08:25:24.620 12877-12877/? I/Adreno: QUALCOMM build                   : 5a7aebc, Ie87d5dfbba
    Build Date                       : 07/05/18
    OpenGL ES Shader Compiler Version: EV031.24.01.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2018-12-05 08:25:24.620 12877-12877/? I/Adreno: Build Config                     : S L 4.0.10 AArch64
2018-12-05 08:25:24.626 12877-12877/? I/Adreno: PFP: 0x005ff110, ME: 0x005ff066
2018-12-05 08:25:24.630 12877-12877/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2018-12-05 08:25:24.630 12877-12877/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2018-12-05 08:25:24.754 12877-12903/? I/flutter: Observatory listening on http://127.0.0.1:39073/
2018-12-05 08:25:24.760 12877-12904/? I/OpenGLRenderer: Initialized EGL, version 1.4
2018-12-05 08:25:24.761 12877-12904/? D/OpenGLRenderer: Swap behavior 2
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

> Can not open

What does that mean exactly?

**Comment by pukaicom** [comment]
output of flutter doctor -v

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale
    zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/xxxx/Library/flutter
    • Framework revision 5391447fae (5 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxxx/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • PH 1 • PM1LHMA7C1300391 • android-arm64 • Android 9 (API 28)

I can not open the Web page at the Observatory URL printed to the console
Dart Observatory (statement-level single-stepping debugger and profiler)link:
[https://flutter.io/docs/testing/debugging#dart-observatory-statement-level-single-stepping-debugger-and-profiler](url)

No Proxy
Hot reload doesn't works
I don't know why

**Comment by zoechi** [comment]
Can you please still try if setting the environment variable `no_proxy=127.0.0.1` changes anything.

**Comment by pukaicom** [comment]
I have tried, not works

**Comment by zoechi** [comment]
To me this looks like some network configuration issue on your machine.

**Comment by SupSaiYaJin** [comment]
Same for me, but flutter attach works.
The ip in flutter attach is diffrent from the logcat.
Then I found the port is forwarded.

adb forward --list
16fedaac0004 tcp:53368 tcp:46264

Why is that?

**Comment by zoechi** [comment]
@DanTup it's not VSCode related but you are quite good at diagnosing this kind of issues and might have suggestions what to check.

**Comment by DanTup** [comment]
> I can not open the Web page at the Observatory URL printed to the console

Can you provide more info on what type of issue you have when you try? What do you see in the browser?

> Then I found the port is forwarded.
> Why is that?

The flutter tools do forward a port to the device and the local tooling connects to that local port. I don't know the specific reasons for this but I guess it may be for simplicity (only needing to know a local port number to attach to a debugger rather than its IP and a port).

**Comment by shakib609** [comment]
I can open the Web Page but it is empty with a vague Js error in `Firefox`.
But works without any problem in `Google-Chrome`.

**Comment by DanTup** [comment]
Seems like there's an open issue about it not working in Firefox: https://github.com/dart-lang/sdk/issues/34107

@pukaicom is this the same issue you were hitting - which browser were you using?

**Comment by pukaicom** [comment]
It looks different.
macOs 10.13.6 
Chrome 71.0.3578.98
@DanTup 
I solve this problem reInstall  operating system. This problem Maybe caused by proxy or port taked up.

**Comment by zoechi** [comment]
Thanks for the update.
I assume it's ok to close.

**Comment by patelkrunal78** [comment]
This is now implemented as Plugin

https://pub.dartlang.org/packages/url_launcher

Example:

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(new Scaffold(
    body: new Center(
      child: new RaisedButton(
        onPressed: _launchURL,
        child: new Text('Show Flutter homepage'),
      ),
    ),
  ));
}

_launchURL() async {
  const url = 'https://flutter.io';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}
Special Characters:
If the url value contains spaces or other values that are now allowed in URLs, use

Uri.encodeFull(urlString) or Uri.encodeComponent(urlString) and pass the resulting value instead.

Find at [Here](https://icetutor.com/question/how-do-i-open-a-web-browser-url-from-my-flutter-code)
