### ISSUE TITLE
Firebase storage getdownloadurl doens't work on ios

### ISSUE THREAD

**Issue by thinkcsww** [flutter/flutter#24967]
```dart
StorageReference storageReference = storage.ref();
    final StorageReference imagesRef = storageReference.child('posters/$uuid');

    StorageUploadTask uploadTask = imagesRef.putFile(_imageFile);
    print(imagesRef.getDownloadURL());

    var imageURL = await (await uploadTask.onComplete).ref.getDownloadURL();
```

about await getDownloadURL works well on android but doesn't work on ios

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by thinkcsww** [comment]
Thanks for reply :) 
This is flutter doctor -v for my project
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-KR)
    • Flutter version 1.0.0 at /Users/sunwoongchoi/Library/Developer/flutter
    • Framework revision 5391447fae (5 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/sunwoongchoi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Sun • 97db955e69d9460de85749b37160b65e805d11ef • ios • iOS 12.1

**Comment by zoechi** [comment]
> doesn't work

what does that mean exactly? Do you get an error output or does execution hang at `await`?

**Comment by thinkcsww** [comment]
maybe execution hang at await could be a right expression.
`var imageURL = await (await uploadTask.onComplete).ref.getDownloadURL();`
i printed imageURL but there is no result and  i used .then(....) after this uploading image function 
it doesn't move over to next function
Maybe hang at await

**Comment by KevinRay** [comment]
I'm seeing the exact same issue. In fact I've seen that other methods. like updateMetadata(), also hang at await. In the case of updateMetadata(), it does complete the update to the file's metadata, which I can verify through the Firebase console, but it never returns so the app hangs at await.

**Comment by thinkcsww** [comment]
In getDownloadURL() case also can see the result  in firebase console but hang at await.. 
I asked my friends, only i have this problem. It is not that prevalent. Cannot find how to solve it

**Comment by KevinRay** [comment]
I got this to work by upgrading my pod install. Firebase went from 5.7.0 to 5.15.0 and then started working.

**Comment by thinkcsww** [comment]
I thought upgrading my pod install is Packages upgrade but it seems different. 
Can you explain how to do upgrading my pod install?? you are using flutter right?

> I got this to work by upgrading my pod install. Firebase went from 5.7.0 to 5.15.0 and then started working.

**Comment by kroikie** [comment]
@thinkcsww

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/560. Any further collaboration will be done there.
