### ISSUE TITLE
Cupertino Refresh

### ISSUE THREAD

**Issue by kevinwylder** [flutter/flutter#24970]
I am unable to "pull to refresh" in the Flutter Gallery app. This screen can be found under Cupertino -> Pull to Refresh. When I scroll past the end of the screen, there is no give. I see the default Android overscroll indicator, which covers the status bar. 

There is also an aliasing effect where 1pixel dividers between cells are not displayed unless scrolling.

Observed on Android 8.0.0. defualt app settings.

**Comment by xster** [comment]
We should probably force the iOS bouncing scroll physics for this demo

**Comment by shihaohong** [comment]
This has been fixed in the `master` branch with https://github.com/flutter/flutter/pull/30129.
