### ISSUE TITLE
Mixed http protocol: Failed to load webpage using webview plugin

### ISSUE THREAD

**Issue by 370966584** [flutter/flutter#24975]
There are different http protocols in the web link, the loading fails, the log is as follows:

Mixed Content: The page at 'https://qtwx.shaomi.net/02/?url=http://img1.bilekang.com/userpic/20170719/1500458799955722734.jpg' was loaded over HTTPS, but requested an insecure image 'http://img1.bilekang.com/userpic/20170719/1500458799955722734.jpg'. This request has been blocked; the content must be served over HTTPS."

**Comment by luckmlc** [comment]
@370966584  这个问题解决了么，我还有这个问题啊

**Comment by caoxingyu** [comment]
This request has been blocked; the content must be served over HTTPS.

**Comment by caoxingyu** [comment]
Is the problem still unresolved?

**Comment by LHMing01** [comment]
It still seems to exist In version 0.3.22+1.  but I need a solution urgently
