### ISSUE TITLE
widget.<object> modifying issue.

### ISSUE THREAD

**Issue by RajesMca008** [flutter/flutter#24982]
While passing an object from one class to another class by using Navigator.push(), the object does not get modifying even its declared as not final.

```
class FirstScreen extends StatefulWidget {
  UserBean userbean;

  FirstScreen({Key key, this.userbean}) : super(key: key);

  @override
  @override
  _FirstScreenState createState() => _FirstScreenState();
}
```
//trying to get modifying userBean, it’s not modifying.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

This would be a good question for StackOverflow.
GitHub issues are for bug reports and feature requests.
