### ISSUE TITLE
`flutter build` should warn when run on a master channel

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#24984]
We're observing that a good proportion of developers are on the `master` channel, which contains the very latest code that passes our tests. While `master` is viable (albeit aggressive) for development purposes, we would strongly recommend against using it for shipping production apps, yet we continue to see apps shipped to the store with it. 

We propose that when `flutter build apk` or `flutter build ios` are run from a Flutter SDK that is on the `master` channel, we should proceed with the build but emit a message to the console that warns that this is explicitly discouraged.

The message should also include the following ASCII art to warn of the presence of fire-breathing creatures:
```
                \||/
                |  @___oo
      /\  /\   / (__,,,,|
     ) /^\) ^\/ _)
     )   /^\/   _)
     )   _ /  / _)
 /\  )/\/ ||  | )_)
<  >      |(,,) )__)
 ||      /    \)___)\
 | \____(      )___) )___
  \______(_______;;; __;;;
```

(just kidding!)

**Comment by ram231** [comment]
(is this an out of season april fools joke?)[https://www.youtube.com/watch?v=C2KeEUhmwbg]

**Comment by zoechi** [comment]
I would always build from master just to see the graphic ;p

**Comment by GaryQian** [comment]
so... I'm implementing this as it seems like a quick fix... Do I put in the dragon?

**Comment by GaryQian** [comment]
The big dragon turns out to be too scary. With @Hixie 's suggestion, I'm putting in a red 🐉 (dragon) emoji to indicate the fire breathing dangers ahead.

**Comment by GaryQian** [comment]
Landed in https://github.com/flutter/flutter/pull/25007

**Comment by GaryQian** [comment]
Rolled back. Attempting again in https://github.com/flutter/flutter/pull/27324

**Comment by Hixie** [comment]
We tried to fix this, but it turned out to be more subtle than its value warrants. Closing.
