### ISSUE TITLE
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value error

### ISSUE THREAD

**Issue by JosephDunivan** [flutter/flutter#24988]
@DanTup 
I followed an [article](https://blog.gauravagarwalr.com/posts/2018-04-11-setting-up-flutter/) which instructed to try this and then perform an uninstall. I was able to catch that my java version was out of date. It's possible this step was completely unnecessary.
  
Tons of people are actually having the same issue as me over at #15114 .
Looks like everyone had to follow the `flutter config` fix.
I'm also still getting a `PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value` error when attempting to make a new Android Simulator in `VS Code`. That's why I set up a dummy flutter application via avd in `Android Studio`.

Also I set flutter config and pointed it to `$HOME/Library/Android/sdk`
My path variables are set as follows: 
```
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
```
```
echo $ANDROID_HOME && flutter doctor -v
/usr/local/share/android-sdk
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C52a, locale en-US)
    • Flutter version 1.0.0 at /Users/josephdunivan/library/development/flutter
    • Framework revision 5391447fae (6 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/josephdunivan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (2 available)
    • iPhone    • 45992a86e2624cf29e2b2876419e731cafe54671 • ios • iOS 12.1.1
    • iPhone XR • 5C7757A3-DB4F-4BD7-9331-47A9975D4371     • ios • iOS 12.1
      (simulator)

• No issues found!

```

_Originally posted by @JosephDunivan in https://github.com/flutter/flutter/issues/13379#issuecomment-444576096_

**Comment by DanTup** [comment]
@JosephDunivan Thanks - I presume the issue here is just the one in the title, and the detection of the SDK is fine - it's just emulators that are broken?

Can you try unsetting `ANDROID_SDK_ROOT`? I don't have that set and the error seems to be complaining about that.

**Comment by JosephDunivan** [comment]
Correct. I have to open up Android Studio and then create a new emulator with a dummy flutter application.

**Comment by JosephDunivan** [comment]
I think the issue is still that fact that it is looking for the sdk in` /usr/local/share/android-sdk`. That's why I had to set it in the first place.

**Comment by DanTup** [comment]
> I think the issue is still that fact that it is looking for the sdk in `/usr/local/share/android-sdk`

Your output above shows this:

```
echo $ANDROID_HOME && flutter doctor -v
/usr/local/share/android-sdk
```

This shows that the `ANDROID_HOME` env variable is set to `/usr/local/share/android-sdk` (for the current terminal session, at least). May there be somewhere else in one of your scripts setting it, or could you have no restarted your terminal session since modifying the `.bash_profile`?

You can confirm once it's sorted by just running `echo $ANDROID_HOME`. Hopefully then Flutter will do what you expect.

**Comment by JosephDunivan** [comment]
after creating a new terminal session output was as follows: 
```
echo $ANDROID_HOME && flutter doctor -v
/Users/josephdunivan/Library/Android/sdk
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C52a, locale en-US)
    • Flutter version 1.0.0 at /Users/josephdunivan/library/development/flutter
    • Framework revision 5391447fae (6 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/josephdunivan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/josephdunivan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • iPhone XR • 5C7757A3-DB4F-4BD7-9331-47A9975D4371 • ios • iOS 12.1
      (simulator)

• No issues found!

```

**Comment by JosephDunivan** [comment]
after creating a new terminal session output was as follows: 
```
echo $ANDROID_HOME && flutter doctor -v
/Users/josephdunivan/Library/Android/sdk
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C52a, locale en-US)
    • Flutter version 1.0.0 at /Users/josephdunivan/library/development/flutter
    • Framework revision 5391447fae (6 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/josephdunivan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/josephdunivan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

[✓] Connected device (1 available)
    • iPhone XR • ......• ios • iOS 12.1
      (simulator)

• No issues found!

```

**Comment by JosephDunivan** [comment]
```
flutter emulators --create --name Pixel-test
Emulator 'Pixel-test' created successfully.
flutter emulators --launch Pixel-test
```
Success. Closing out the issue. Hopefully this helps some other people it was a bit maddening.

**Comment by DanTup** [comment]
@JosephDunivan Great, glad it's all sorted! Hopefully if you need to set it up in future it'll much simpler - but if you do hit issues and it feels like you're having to do more than you should, please do post back.

**Comment by reppolice** [comment]
I "still" have this problem on 10.13, the download page for flutter shows something like "ERROR" for the binary, so I cloned from git, let the flutter binary do its job, having already had Android Studio 3 and the same directories shown here. Creating the emulators goes fine and leaves avds in a .android/avd directory, but launching gives this error message. The doctor says my Android side is perfectly set up.

**Comment by DrAchernar** [comment]
I checked my .bash_profile , I saw multiple JAVA, ANDROID_HOME and SDK paths. Then commented up wrong paths, fixed...

**Comment by HafizAhmerShahid** [comment]
Open your android studio then focus on the toolbar.

Goto tools > SDK manager then

Appearance & Behavior > Systems Settings > Android SDK

Now in the tab copy the Android SDK Location from here [Android SDK Location][1] 

then goto your environment variables and then set the path along with these variables

 1. ANDROID_HOME
 2. ANDROID_SDK_ROOT

[Environment Variables][2]

  [1]: https://i.stack.imgur.com/qK6PT.png
  [2]: https://i.stack.imgur.com/ynqTY.png

**Comment by AmanMandloi** [comment]
vhh
