### ISSUE TITLE
How to reload Webview?

### ISSUE THREAD

**Issue by chuongtrh** [flutter/flutter#24981]
I'm an iOS developer, I try to using webview_flutter: ^0.0.1+1, so I have 2 question:

1. How to reload WebView with other URL? [WKWebView reload](https://developer.apple.com/documentation/webkit/wkwebview/1414969-reload)
2. How to know WebView finish load or facing error?  [WKNavigationDelegate](https://developer.apple.com/documentation/webkit/wknavigationdelegate)

Thanks!

**Comment by amirh** [comment]
I split this into 2 separate feature requests: #25099 #25100.
