### ISSUE TITLE
Cloud functions plugin should throw correct exception on timeout

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#24997]
When there is a timeout in the call to a cloud function the plugin throws `FormatException: Invalid envelope`  exception which is misleading. Please see  [Timeout issue](https://github.com/pulyaevskiy/firebase-functions-interop/issues/43) which contains all the details.

**Comment by radvansky-tomas** [comment]
Still havent added this, have no idea why...anyone interested here is my FORK: 
https://github.com/radvansky-tomas/plugins

Really dont understand stupid reason behind placing all plugins into one repo.

**Comment by opringle** [comment]
This stumped me for a good few hours. V frustrating.

**Comment by kroikie** [comment]
@kostaa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/555. Any further collaboration will be done there.
