### ISSUE TITLE
[cloud_firestore] Batch and serverTimestamp error

### ISSUE THREAD

**Issue by renannprado** [flutter/flutter#24992]
I'm trying to insert multiple documents by using the `batch`, but when I try to use the `serverTimestamp`, I get the below error.

Tested with `cloud_firestore` version `0.8.2`.

The code:

```dart
final data = <String, dynamic>{
    "processed": false,
    "createdOn": FieldValue.serverTimestamp()
};

batch.setData(firestore.collection("theCollection").document(), data);
```

The error:

```
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): java.lang.RuntimeException: No properties to serialize found on class com.google.firebase.firestore.FieldValue$zzd
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo$zza.<init>(com.google.firebase:firebase-firestore@@17.1.1:659)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zza(com.google.firebase:firebase-firestore@@17.1.1:347)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zzb(com.google.firebase:firebase-firestore@@17.1.1:168)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zzb(com.google.firebase:firebase-firestore@@17.1.1:138)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zza(com.google.firebase:firebase-firestore@@17.1.1:1101)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.FirebaseFirestoreSettings$1.zzb(com.google.firebase:firebase-firestore@@17.1.1:1208)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.WriteBatch.set(com.google.firebase:firebase-firestore@@17.1.1:109)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:420)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

When I was using the regular insert by using the below code, everything went fine.

```dart
firestore
        .collection("theCollection")
        .document()
        .setData(data);
```

This seems to be the same as: https://stackoverflow.com/questions/52404620/flutter-firestore-batch-write-with-server-timestamp

**Comment by axross** [comment]
I've run into the same problem.

**Comment by scottdewald** [comment]
Having the same problem. Works fine on iOS but fails on Android.

**Comment by scottdewald** [comment]
There are multiple ways of setting document data in the database: 1) set single document, 2) set documents within a transaction, 3) set documents within a batch write. I have narrowed down when using a server timestamp is working and when it is not. It works when 1) setting a single document and 2) when setting a document within a transaction. It does not work when 3) setting a document within a batch write.

In the code below, `commentDocRef` and `updateDocRef` are Firestore `DocumentReference`s. `commentMap` is a map of data with one field being a `FieldValue.serverTimestamp()`.

**1) Setting Single Document (WORKS)**
```
await commentDocRef.setData(commentMap)
```

**2) Setting Documents in Transaction (WORKS)**
```
await _firestore.runTransaction((transaction) async {
    await transaction.set(commentDocRef, commentMap);
    await transaction.set(updateDocRef, updateMap);
});
```

**3) Setting Documents in Transaction (FAILS)**
```
var batch = _firestore.batch();
batch.setData(commentDocRef, commentMap);
batch.setData(updateDocRef, updateMap);
await batch.commit();
```

Option 3) is the only one that fails with the exception from the OP. I also verified that if I temporarily removed `FieldValue.serverTimestamp()` from Option 3) it works.

**Comment by HarishKanth** [comment]
Getting same error when using `FieldValue.arrayUnion`

**Comment by dshukertjr** [comment]
I also have issue not being able to post data with FieldValue.timestamp() with batched writes.

**Comment by theochampion** [comment]
Any updates on this? I'm still getting the same error as OP

**Comment by collinjackson** [comment]
this seems like the sort of thing that we would want to write a regression test for once #26080 is fixed.

**Comment by PandaGeek1024** [comment]
Im getting the same issue, any update on it?

**Comment by PandaGeek1024** [comment]
@scottdewald Im not able to work with Transaction, it will throw out this error "Transaction has already completed". Have you seen this?

**Comment by dshukertjr** [comment]
No update on this issue yet?

**Comment by kinex** [comment]
I cannot reproduce this issue anymore (cloud_firestore: ^0.12.1) so I guess it has been fixed.

**Comment by kroikie** [comment]
@renannprado

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/558. Any further collaboration will be done there.
