### ISSUE TITLE
Firebase_auth no passwordless signon method

### ISSUE THREAD

**Issue by JosephDunivan** [flutter/flutter#24995]
It would be great to have an implementation for passwordless signon. Its an option in firebase but not the plugin. Can we add a method and documentation for this?

**Comment by cbenhagen** [comment]
Duplicate of https://github.com/flutter/flutter/issues/22958.
Check out this PR: https://github.com/flutter/plugins/pull/1159

**Comment by JosephDunivan** [comment]
> Duplicate of #22958.
> Check out this PR: [flutter/plugins#1159](https://github.com/flutter/plugins/pull/1159)

Actually their's is a duplicate of mine. I submitted this last December. But good to know it's being worked on.

**Comment by kroikie** [comment]
@JosephDunivan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/557. Any further collaboration will be done there.
