### ISSUE TITLE
Codelab + iOS Simulator: giant white screen looks like app is broken?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2500]
Hi! Working with a new Flutter user here. We had the iOS simulator running, and then ran the codelab project. Our iOS simulator screen was all white, which lead us to think we ran into a bug of some sort. Turns out, everything was working just fine! However, the default iOS simulator runs at 100%, and the initial codelab code has nothing but white in the middle of the screen. So all we saw was white. :)

Workaround: shrink iOS simulator to 50%, so you can see the whole screen, and thus notice the app is working.

I don't think we can expect everyone to start with 50% on their iOS simulator, so I'm wondering if we can put something in the middle of the codelab app? Or, not sure if we can detect that the simulator is running at 100% and suggest the user scale their simulator. But, looking at a giant white screen is a little confusing. :)

Thanks!

**Comment by sethladd** [comment]
cc @qchong @collinjackson for ideas

**Comment by eseidelGoogle** [comment]
In at least one of our instructions we recommend the user scale the simulator.

**Comment by sethladd** [comment]
ah, good! Maybe we should bold it? :) To be fair, we weren't strictly looking at the codelab docs when we ran `flutter run`.

**Comment by qchong** [comment]
It's pretty clearly highlighted in a callout box in 'Step 4: Run your app'
<https://codelabs-preview.appspot.com/?file_id=1esS56X44Nfo5mfVHOkV9Xh5IWbOmfzS0CD59wnjquEc#3>
.

[image: Inline image 1]

On Tue, Mar 8, 2016 at 1:57 PM, Seth Ladd <notifications@github.com> wrote:

> ah, good! Maybe we should bold it? :) To be fair, we weren't strictly
> looking at the codelab docs when we ran flutter run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flutter/flutter/issues/2500#issuecomment-193985305>.
>



-- 

Quddus Chong | Technical Writer - Turquoise | quddusc@google.com

**Comment by sethladd** [comment]
Thanks for confirming. I'll close for now. We admittedly were not looking at the codelab docs at this point. We skipped ahead.
