### ISSUE TITLE
Weird Glitch when Navigating to a new Page

### ISSUE THREAD

**Issue by fabio-o0** [flutter/flutter#25010]
I'm trying to navigate from a login page to the home page of my app, without the user being able to go back to the login screen. To achieve this, I'm popping the login screen and then pushing the home screen but it creates a weird glitch where the screen goes back and then slides the new screen. I am using an animation but it happens without it as well. I've attached a gif of what's happening and below is my code.

![flutterissue](https://user-images.githubusercontent.com/33147563/49552278-d540c080-f8c0-11e8-86c4-464aaa3d662c.gif)

```
Future<void> signInWithEmail() async {
    final formState = _formKey.currentState;

    if (formState.validate()) {
      formState.save();
      try {
        FirebaseUser user = await FirebaseAuth.instance
            .signInWithEmailAndPassword(email: _email, password: _password);
        Navigator.of(context)
          ..pop()
          ..pushReplacement(SlideBottomRoute(widget: HomePage(user: user)));
      } catch (error) {
        _scaffoldKey.currentState.showSnackBar(new SnackBar(
          content: Padding(
            padding: const EdgeInsets.only(top: 10.0),
            child: new Text(
              "Sorry.\nThe email and password provided don't correspond to any account.",
              style: new TextStyle(
                fontSize: 16.0,
                color: Color.fromRGBO(248, 233, 228, 1.0),
              ),
            ),
          ),
          backgroundColor: Color.fromRGBO(183, 70, 95, 1.0),
        ));
      }
    }
  }

```

**Comment by rmtmckenzie** [comment]
I think it's doing what it should be there - you're telling it to pop and at the same time push a new item on top, so it doesn't really know what to do (pop and pushReplacement are both asynchronous functions and so run right away).

I assume what you're trying to do is a transition to a new screen (home) and then remove all previous routes (i.e. the login route). Would [Navigator.of(context).pushAndRemoveUntil()](https://docs.flutter.io/flutter/widgets/Navigator/pushReplacement.html) work instead?

**Comment by fabio-o0** [comment]
> I think it's doing what it should be there - you're telling it to pop and at the same time push a new item on top, so it doesn't really know what to do (pop and pushReplacement are both asynchronous functions and so run right away).
> 
> I assume what you're trying to do is a transition to a new screen (home) and then remove all previous routes (i.e. the login route). Would [Navigator.of(context).pushAndRemoveUntil()](https://docs.flutter.io/flutter/widgets/Navigator/pushReplacement.html) work instead?

Yep, that did it. Thank you so much. The specific line of how I fixed it if you're interested is:

`Navigator.of(context).pushAndRemoveUntil(SlideBottomRoute(widget: HomePage(user: user)), (Route<dynamic> route) => false);`
