### ISSUE TITLE
Does setState contains diff mechanism?

### ISSUE THREAD

**Issue by lzyy** [flutter/flutter#25017]
Suppose this is the Element Tree

```
Root
|-- ActionButton(someNumber)
|-- BodyWith100Widgets
```

if I `setState` on the Root Widget with a new `someNumber`, will `BodyWith100Widgets` 100 Widgets recreated and mark 100 elements dirty?

is there some diff mechanism to improve the performance?

**Comment by zoechi** [comment]
There are various optimizations Flutter is doing and it also depends on your code. For example if the `Root::build()` method returns the same of a new instance of `BodyWith100Widgets`. 
There are resources out that explain that in detail.
https://www.youtube.com/watch?v=UUfXWzp0-DU might provide some answers.

I think this is a good question for StackOverflow.
GitHub issues are for bug reports and feature requests.
