### ISSUE TITLE
我改改标题，喷子真多，我说的是是事实，MaterialDesign出来这么多年没几个用吧！要多出现iOS的控件风格

### ISSUE THREAD

**Issue by Siomt** [flutter/flutter#25012]

**Comment by itning** [comment]
interesting

**Comment by lishuhao** [comment]
Flutter has [Cupertino](https://flutter.io/docs/development/ui/widgets/cupertino) components

**Comment by fengchunsgit** [comment]
You love , or you don't love, it's there

**Comment by creatint** [comment]
When did you become the representative of the Chinese people?

**Comment by Siomt** [comment]
> When did you become the representative of the Chinese people?

难道不是吗？我开发4年多了，好几家公司都是设计的和苹果一样的，UI也是用苹果的，苹果的尺寸，看看国内的app 有几个用MaterialDesign

**Comment by creatint** [comment]
> > When did you become the representative of the Chinese people?
> 
> 难道不是吗？我开发4年多了，好几家公司都是设计的和苹果一样的，UI也是用苹果的，苹果的尺寸，看看国内的app 有几个用MaterialDesign

想想喜欢MD的人，有点同理心。
Think about people who like MD, have some empathy.

**Comment by kbz066** [comment]
你一个狗屎都吃不上的傻逼 还在这指指点点？

**Comment by ladder1984** [comment]
![img](https://3.bp.blogspot.com/-yHTJU3kqh18/V0z_JjJugeI/AAAAAAAB9jc/X5iPBYOZItMD6X6BD1MdSYMEcyoWPdcDQCLcB/s1600/k9hhhhhhhh.jpg)  你咋不代表亚洲呢？

**Comment by Lanvww** [comment]
That is why the UI/UX Design is so bad in China, because of the people like you.

**Comment by gengrui1983** [comment]
Please simply close this ticket.

**Comment by 1and1get2** [comment]
designers in question = dinosaurs

**Comment by ssfxz** [comment]
赶紧关了吧  别在这丢人现眼了

**Comment by mrldroid** [comment]
傻屌

**Comment by sunui** [comment]
你并不能代表中国人 别在这给中国人丢脸了

**Comment by Soulghost** [comment]
> > When did you become the representative of the Chinese people?
> 
> 难道不是吗？我开发4年多了，好几家公司都是设计的和苹果一样的，UI也是用苹果的，苹果的尺寸，看看国内的app 有几个用MaterialDesign

你的眼界太小了吧，是不是在小公司待傻了

**Comment by tao1991123** [comment]
人家说了大实话,为什么要喷人家。
国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也要做的想苹果。
无论你们怎么喷，以后终究会面临用flutter,做苹果风格安卓App。
不如在回复里面 给出解决方案。
软件届的何不食肉糜
---------
english translation

He just tell the truth，why most people diss him and this issue.

Now at China Mainliand,  A designer usually gives out a Apple style desgin paper.
No matter iOS or Android developers, the both use the same desgin paper. 
Andriod developer has to develop an Apple styled Android app.

It is better to give some suggest solution  rather than just diss him.

**Comment by SeanZom** [comment]
![go-home-youre-drunk](https://user-images.githubusercontent.com/12492306/49561804-0971bb00-f96d-11e8-9139-af8dc2cb9ceb.jpg)

**Comment by itning** [comment]
> 人家说了大实话,为什么要喷人家。
> 国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也要做的想苹果。
> 无论你们怎么喷，以后终究会面临用flutter,做苹果风格安卓App。
> 不如在回复里面 给出解决方案。
> 软件届的何不食肉糜
> 
> ## english translation
> He just tell the truth，why most people diss him and this issue.
> 
> Now at China Mainliand, A designer usually gives out a Apple style desgin paper.
> No matter iOS or Android developers, the both use the same desgin paper.
> Andriod developer has to develop an Apple styled Android app.
> 
> It is better to give some suggest solution rather than just diss him.

He said that Chinese designers don't like this design, but he can't represent all Chinese designers.

**Comment by lam-bun** [comment]
你凭什么代表中国人？
Can you represent all the Chinese?

**Comment by tao1991123** [comment]
> > 人家说了大实话,为什么要喷人家。
> > 国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也要做的想苹果。
> > 无论你们怎么喷，以后终究会面临用flutter,做苹果风格安卓App。
> > 不如在回复里面 给出解决方案。
> > 软件届的何不食肉糜
> > ## english translation
> > He just tell the truth，why most people diss him and this issue.
> > Now at China Mainliand, A designer usually gives out a Apple style desgin paper.
> > No matter iOS or Android developers, the both use the same desgin paper.
> > Andriod developer has to develop an Apple styled Android app.
> > It is better to give some suggest solution rather than just diss him.
> 
> He said that Chinese designers don't like this design, but he can't represent all Chinese designers.

So 
`Chinese UI designers don't like it. They prefer apple's design.`  -> wrong
`many Chinese UI designers don't like it. They prefer apple's design.`  -> right

????

@lam-bun

**Comment by caiyongji** [comment]
# Good boy. You must knowing that saying "Stay hungry, stay foolish". BUT, I can only see your foolish.
# Ignoring the market cap, Google is the most greatest company in the world. You may LIKE Apple, but we LOVE Google veeeeeeeeeery much. 
# Guys, double click :six: :six: :six:.

**Comment by lam-bun** [comment]
> > > 人家说了大实话,为什么要喷人家。
> > > 国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也要做的想苹果。
> > > 无论你们怎么喷，以后终究会面临用flutter,做苹果风格安卓App。
> > > 不如在回复里面 给出解决方案。
> > > 软件届的何不食肉糜
> > > ## english translation
> > > He just tell the truth，why most people diss him and this issue.
> > > Now at China Mainliand, A designer usually gives out a Apple style desgin paper.
> > > No matter iOS or Android developers, the both use the same desgin paper.
> > > Andriod developer has to develop an Apple styled Android app.
> > > It is better to give some suggest solution rather than just diss him.
> > 
> > 
> > He said that Chinese designers don't like this design, but he can't represent all Chinese designers.
> 
> So
> `Chinese UI designers don't like it. They prefer apple's design.` -> wrong
> `many Chinese UI designers don't like it. They prefer apple's design.` -> right
> 
> ????
> 
> @lam-bun

你用G家的东西，遵循MD规范有什么问题？而且那是设计师的问题，跟flutter有啥关系。还提这样智障的issue，这不是丢脸是什么？

**Comment by JeremyWuuuuu** [comment]
To whoever is watching this, this is totally a joke, shame on @Siomt. Haters can say whatever they want, but they just don't represent any group or community or country!

**Please close this issue, this is ridiculous.**

Peace & Love.

**Comment by geekplux** [comment]
please close and lock this issue. 🤟

**Comment by Sky24n** [comment]
@tao1991123    Google提供了iOS组件[Cupertino(https://flutter.io/docs/development/ui/widgets/cupertino)  ，没有强迫用MD！！！

**Comment by douyanlin** [comment]
LOL

**Comment by DachiCoding** [comment]
> 人家说了大实话,为什么要喷人家。
> 国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也被迫做的像苹果。
> 
> 各位在大公司的大佬,你们公司有足够多的设计师,甚至还有UED部门。给出两份风格的设计稿完全可以。
> 
> 无论你们怎么喷，他终究会面临用flutter,做苹果风格安卓App。
> 
> 有空回复”何不食肉糜“类言论。不如在回复中帮忙给出解决方案。
> 
> ## english translation
> He just tell the truth，why most people diss him and this issue.
> 
> Now at China Mainland, A designer usually gives out only one Apple style design.
> No matter iOS or Android developers, they both use the same design.
> Andriod developer has to develop an Apple styled Android app.
> 
> It is better to give some suggest solution rather than just diss him.

那只是他个人的审美观点, 不是什么"大实话", issue是用来表达审美风格/设计问题的吗? 即便是，也可以用更充分的观点和论据，随便甩这么一个topic出来，很没有水平也很不尊重别人。

**Comment by pk00789o** [comment]
dig for politeness.

**Comment by Caldis** [comment]
与审美无关，这种言论只能显出你眼界狭窄与无比的愚蠢，而且你也没有资格代表中国人

不用谢谢，你不配

**Comment by Levineet** [comment]
> > When did you become the representative of the Chinese people?
> 
> 难道不是吗？我开发4年多了，好几家公司都是设计的和苹果一样的，UI也是用苹果的，苹果的尺寸，看看国内的app 有几个用MaterialDesign

请你不要随便代表一个群体，谢谢。

设计师按照两种平台规范去做两套设计是完全没有问题的。问题在于工作中的决策出于什么样的考虑，大厂两个平台统一一套设计，两端一致后期迭代也更加统一。这跟设计师喜不喜欢和适否 prefer 没有任何关系。

在公共场合发表这种言论之前，请你仔细思考一下为什么，而不是把锅甩到设计师头上，何况你不是设计师。

**Comment by findeway** [comment]
This is ridiculous！‘Chinese UI designers don't like’ is just your opinion. I think maybe the reason why many companies only use apple's design for Android is they don't want to do two different designs for two platform, some of them even don't know what users really want.

**Comment by sisyphsu** [comment]
1. there isn't BBS! this isn't issue! you idiot!!!
2. maybe you are Chinese, but you should't say `Chinese`!!!

**Comment by yetone** [comment]
> 人家说了大实话,为什么要喷人家。
> 国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也被迫做的像苹果。
> 
> 各位在大公司的大佬,你们公司有足够多的设计师,甚至还有UED部门。给出两份风格的设计稿完全可以。
> 
> 无论你们怎么喷，他终究会面临用flutter,做苹果风格安卓App。
> 
> 有空回复”何不食肉糜“类言论。不如在回复中帮忙给出解决方案。
> 
> ## english translation
> He just tell the truth，why most people diss him and this issue.
> 
> Now at China Mainland, A designer usually gives out only one Apple style design.
> No matter iOS or Android developers, they both use the same design.
> Andriod developer has to develop an Apple styled Android app.
> 
> It is better to give some suggest solution rather than just diss him.

他有什么建设性疑问吗？凭什么要给他解决方案？

**Comment by appbeijing** [comment]
你们在说什么呢？what are you  talking about？

**Comment by myronliu347** [comment]
> > 人家说了大实话,为什么要喷人家。
> > 国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也被迫做的像苹果。
> > 各位在大公司的大佬,你们公司有足够多的设计师,甚至还有UED部门。给出两份风格的设计稿完全可以。
> > 无论你们怎么喷，他终究会面临用flutter,做苹果风格安卓App。
> > 有空回复”何不食肉糜“类言论。不如在回复中帮忙给出解决方案。
> > ## english translation
> > He just tell the truth，why most people diss him and this issue.
> > Now at China Mainland, A designer usually gives out only one Apple style design.
> > No matter iOS or Android developers, they both use the same design.
> > Andriod developer has to develop an Apple styled Android app.
> > It is better to give some suggest solution rather than just diss him.
> 
> 他有什么建设性疑问吗？凭什么要给他解决方案？

麻烦认真看文档，是有iOS 的 widgets 的
https://flutter.io/docs/development/ui/widgets/cupertino
flutter 本质上还是一个跨平台移动应用解决方案， UI 库这种东西，一旦flutter用的人多了，会出现好几百种不同的UI库的，作为不打算这么早吃螃蟹的，选择观望就好了

**Comment by Siomt** [comment]
> 技术同仁请都记住这个败类，这个厚颜无耻、堂而皇之地羞辱Chinese的败类。
> 这个败类叫做 **周察田**
请不要做人生攻击，我只是说了事实

**Comment by Siomt** [comment]
我是不是要改小标题

**Comment by cdswyda** [comment]
蹭热度，请不要带上所有中国人，你代表不了。

If you want to be fifteen minutes of fame, please don't take all of Chinese. 

You are just youself!

**Comment by Siomt** [comment]
> Flutter has [Cupertino](https://flutter.io/docs/development/ui/widgets/cupertino) components

谢谢，这个希望多出现iOS风格的，毕竟都学iOS

**Comment by Siomt** [comment]
> 想想喜欢MD的人，有点同理心。
> Think about people who like MD, have some empathy.
是的，很烦iOS风格，每个都要自定义，什么日历啊，各种弹窗啊，都要自己改成iOS样式的

**Comment by Siomt** [comment]
> That is why the UI/UX Design is so bad in China, because of the people like you.

不是我不想写，只是要按设计的做

**Comment by 18633847058** [comment]
用不用是一回事，喜不喜欢是另一回事
推广不推广是一回事，用的多和用的少是另一回事
你可以说中国MD用的少，但是你不能说中国开发者不喜欢MD
事情总是有缘由的

**Comment by 18633847058** [comment]
用不用是一回事，喜不喜欢是另一回事
推广不推广是一回事，用的多和用的少是另一回事
你可以说中国MD用的少，但是你不能说中国开发者不喜欢MD
事情总是有缘由的，你被喷也不是没有理由的

**Comment by hominthesky** [comment]
> > When did you become the representative of the Chinese people?
> 
> 难道不是吗？我开发4年多了，好几家公司都是设计的和苹果一样的，UI也是用苹果的，苹果的尺寸，看看国内的app 有几个用MaterialDesign

1. 你所在的公司用一套 UI，那是你所处环境的情况，不评价对错。我想说的是：Google 也不会强制你用 Google 产品的 UI 风格去设计，不会强制你用 MD。系统规范跟 UI 风格是两回事，MD 是一个开源的设计系统，并不会强制任何个人和公司用或不用，Google 以及专业设计师都只会希望自己遵循 Android / iOS 或任何其他所在系统的规范并以符合 UX 的方式做设计而已！

2. 你把 Flutter 跟 Material Design 等同起来，那说明你完全不懂 Flutter 的实现理念以及用途！

3. 既然不了解，就别代表中国的设计师在此发言，你可以发表自己的个人观点！别带上一个群体。

Translate into English for people who don't speak Chinese:
1. All China's professional designers don't wanna be represented by someone we don't know. 
2. There are still lots of great designers and developers trying to design and implement Android App in Android's way. And we know Android's way doesn't equal to some visual style & components.
3. This issue just means  the guy hadn't ever known anything about Flutter / Material Design or Android 
 or even iOS so that commented like this which is completely a bias.

**Comment by Siomt** [comment]
> > > When did you become the representative of the Chinese people?
> > 
> > 
> > 难道不是吗？我开发4年多了，好几家公司都是设计的和苹果一样的，UI也是用苹果的，苹果的尺寸，看看国内的app 有几个用MaterialDesign
> 
> 1. 你所在的公司用一套 UI，那是你所处环境的情况，不评价对错。我想说的是：Google 也不会强制你用 Google 产品的 UI 风格去设计，不会强制你用 MD。系统规范跟 UI 风格是两回事，MD 是一个开源的设计系统，并不会强制任何个人和公司用或不用，Google 以及专业设计师都只会希望自己遵循 Android / iOS 或任何其他所在系统的规范并以符合 UX 的方式做设计而已！
> 2. 你把 Flutter 跟 Material Design 等同起来，那说明你完全不懂 Flutter 的实现理念以及用途！
> 3. 既然不了解，就别代表中国的设计师在此发言，你可以发表自己的个人观点！别带上一个群体。
> 
> Translate into English for people who don't speak Chinese:
> 
> 1. All China's professional designers don't wanna be represented by someone we don't know.
> 2. There are still lots of great designers and developers trying to design and implement Android App in Android's way. And we know Android's way doesn't equal to some visual style & components.
> 3. This issue just means  the guy hadn't ever known anything about Flutter / Material Design or Android or even iOS so that commented like this which is completely a bias.

是的，我不能代表中国的设计师们，没写准确

**Comment by sp0cket** [comment]
@tao1991123 

> 人家说了大实话,为什么要喷人家。
国内的现状就是 很多设计师给App的设计稿就是按照苹果的设计风格做的，特别是中小型公司。安卓版本的App也被迫做的像苹果。

> 各位在大公司的大佬,你们公司有足够多的设计师,甚至还有UED部门。给出两份风格的设计稿完全可以。

> 无论你们怎么喷，他终究会面临用flutter,做苹果风格安卓App。

flutter完全可以无障碍在安卓上开发ios风格app，甚至两种风格混合也没有问题，没懂楼主到底说了啥大实话？

> 有空回复”何不食肉糜“类言论。不如在回复中帮忙给出解决方案。

三楼就有回复`Flutter has Cupertino components`，眼角膜没用就捐出去给有需要的人谢谢

**Comment by joesonw** [comment]
As much as I love Apple products and its UI, this is a Google's project. No matter how much you or whomever you imagined you could speak for, GO WRITE YOUR OWN WIDGETS !!! 

Ain't nobody stops from styling widgets.

**Comment by xiaojia21190** [comment]
厉害的狠
