### ISSUE TITLE
Add support for Ascender, Descender, XHeight alignment widgets.

### ISSUE THREAD

**Issue by GoldenJoe** [flutter/flutter#25018]
When laying out Text widgets, it is sometimes necessary to align them by the top of the capital letter or the bottom of lowercase letters like 'y'. There is a Baseline widget, but no way to align text by its ascender, descender, or x-height.

For a helpful diagram, see:
https://en.wikipedia.org/wiki/Ascender_(typography)

**Comment by GaryQian** [comment]
This could be extended to encompass providing all of the available metrics we possess about a run of text. The metrics we have are based off of SkFontMetrics from Skia, and Skia provides the following metrics:

- Flags
- Top
- Ascent
- Descent
- Bottom
- Leading
- AvgCharWidth
- MaxCharWidth
- XMin
- XMax
- XHeight
- CapHeight
- UnderlineThickness
- UnderlinePosition
- StrikeoutThickness
- StrikeoutPosition

We could potentially just provide a Dart API to obtain the full metrics at any text offset, maybe a method like `FontMetrics metricsAtOffset({int offset = 0})` in Paragraph that is only valid after layout.

**Comment by khalithartmann** [comment]
Hello you awesome people!
I just created a Let's Flutter Berlin group on Facebook to bring flutter developers in Berlin together to discuss problems, share ideas and create beautiful things together. If you live in Berlin, it would be awesome if you could join the group 😊! If you don't live in Berlin, feel free to join too! Im grateful for each and every supporter.  

Let's Flutter Berlin: https://www.facebook.com/groups/276520973054067/about/
Sorry for spamming.

**Comment by GoldenJoe** [comment]
@GaryQian Off the top of my head, the only reason I can think that exposing the metrics may be insufficient is that you can't have negative padding, so you couldn't align a Text object to the top of its container by simply knowing the ascent. Could this be achieved by tightening the constraints of the Text widget so that the upper bounds of the constraint is offset by the ascender?

PS can a mod please ban khalithartmann for spamming in open issues?

**Comment by Hixie** [comment]
If we exposed the metrics (which we'd probably do as part of #224) then you could then measure the text in a LayoutBuilder widget (or even any random build method) and position the text arbitrarily (e.g. using a stack or whatever).

**Comment by GoldenJoe** [comment]
IMO, that sounds like too much boilerplate and moving things around just to make a fine spacing adjustment, especially if you want to position the next Widget according to the baseline or something. Instead, could we handle the layout issue with a property? Something like:

```
Text(
  'Sample Text',
  upperConstraint: TextConstraint.CapHeight, // Ascent, XHeight, etc
  lowerConstraint: TextConstraint.Baseline, // Descent, Bottom, etc
)
```

That would convey intent instantly, and reduce the depth of the widget tree (a common complaint about flutter).

**Comment by GaryQian** [comment]
My recent work on Strut should actually provide tools to accomplish parts of what is desired here.

Tracking issue: https://github.com/flutter/flutter/issues/26085

By allowing more finely adjustable line heights as well as the capability to force the line heights, it should be easier to align the text as desired.

**Comment by GaryQian** [comment]
Once the fundamental implementation for strut has landed, I would like to expose a set of metrics regarding the strut. The strut metrics should be available before the layout has been done and does not require text to exist, only a StrutStyle needs to be specified. Strut metrics should further allow better alignment of text.

**Comment by tarobins** [comment]
Use case I ran into today:
Trying to position exponents and subscripts by looking at ascender, baselines, etc. https://en.wikipedia.org/wiki/Subscript_and_superscript#Alignment_examples

Still not 100% sure how I'd do it, but seems having those lines available could be useful.

**Comment by GaryQian** [comment]
We have since added the `computeLineMetrics` getter as well as `TextHeightBehavior` that allows adjustment of how height is applied to the first and last lines. I will close this for now, as it seems that more advanced alignment is now possible. Please feel free to reopen if you feel there is more work to be done. Thanks!

**Comment by GoldenJoe** [comment]
Do contributors get points for closing issues or something? Very disappointing. How is aligning Text by XHeight supported by `computeLineMetrics ` and `TextHeightBehavior`?
