### ISSUE TITLE
can I  call or use python library with flutter 

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [flutter/flutter#25020]
I  was wondering if I can call or use some python library with flutter to handle business logic .
In other word I want flutter to handle the UI and for python fir business logic without using http request to the server

**Comment by zoechi** [comment]
Currently you would need to make it available on your native platform (Java, Kotlin, Objective-C, Swift) and from there make it available to Flutter using https://flutter.io/docs/development/packages-and-plugins/developing-packages

https://github.com/flutter/flutter/issues/7053 might help as well, but I don't know if Python apps can expose its API to make it usable that way.

**Comment by Shu-Ji** [comment]
Can we call/use flutter engine directly by other c-serie languages(python etc.)?

**Comment by zoechi** [comment]
@Shu-Ji sorry, can't help you here. I'd suggest you ask on StackOverflow. You might get a quicker response there.

**Comment by ShubhraDeshpande** [comment]
is there an active support for integrating python with flutter, compatible with Dart2?

**Comment by jonahwilliams** [comment]
You cannot run python on mobile devices (it requires an interpreter), nor on the web. Its possible that a flutter for desktop application could callout to python in a plugin, but by design that is not a concern of the flutter framework

**Comment by sandybradley** [comment]
http://www.srplab.info/flutter/2018/07/29/flutter-and-python.html
