### ISSUE TITLE
google_maps_flutter demo: Authorization failure. 

### ISSUE THREAD

**Issue by manangatangy** [flutter/flutter#25021]
The instructions for using https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter#getting-started may possibly be  incomplete.
I used the simple flutter code on that page, and at runtime got this error :

    E/GoogleMapController( 1644): Cannot enable MyLocation layer as location permissions are not granted
    E/Google Maps Android API( 1644): Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
    E/Google Maps Android API( 1644): In the Google Developer Console (https://console.developers.google.com)
    E/Google Maps Android API( 1644): Ensure that the "Google Maps Android API v2" is enabled.
    E/Google Maps Android API( 1644): Ensure that the following Android Key exists:
    E/Google Maps Android API( 1644): 	API Key: [my-generated-api-key]
    E/Google Maps Android API( 1644): 	Android Application (<cert_fingerprint>;<package_name>): 08:82:BF:08:90:97:E0:94:27:A7:E0:9C:66:1A:43:7E:4A:E4:6E:A8;com.example.fluttercatalog
    W/DynamiteModule( 1644): Local module descriptor class for com.google.android.gms.googlecertificates not found.
    I/DynamiteModule( 1644): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
    I/DynamiteModule( 1644): Selected remote version of com.google.android.gms.googlecertificates, version >= 4

I generated an API key for Google Maps, at the Google Cloud Platform Console, which I placed in  the AndroidManifest.xml, and I have enabled the Maps SDK for Android.

The app error message (above) suggested that I should specify some Application Restriction on the API (although at that point there was no restriction).  So I went back to the Cloud Console and added an (Android) Application restriction to the API Key, entering the same package_name and cert_fingerprint that was printed in the error message.
Doing this made no change - the same error occurred.
Note that I'm running this in dev and haven't signed any APKs.

Is it possible that there is another step that is obvious to all experienced Flutter/Maps-API devs that needs to be performed to get the demo to run, but that wasn't explicitly stated?

**Comment by zoechi** [comment]
The first line seems to be about permissions you can request by a plugin like https://pub.dartlang.org/packages/permission (there are others) 

> specify some Application Restriction

from what part of the error message did you derive that?

**Comment by manangatangy** [comment]
> from what part of the error message did you derive that?

The line that says:
`    
E/Google Maps Android API( 1644): 	Android Application (<cert_fingerprint>;<package_name>):08:82:BF:08:90:97:E0:94:27:A7:E0:9C:66:1A:43:7E:4A:E4:6E:A8;com.example.fluttercatalog
`

I've just realised what I was doing wrong.  In the API Console, I had restricted access to some of the APIs because I thought they weren't being used.  The ones I had disabled were
- Roads API
- Service Usage API
- Service Management API
- Stackdriver * APIs
- Street View * APIs
- Timezone API

I just went back and enabled all the APIs and the app error was fixed.
This is a bit puzzling because I didn't think these APIs would be needed for Maps, but I was mistaken.
Oh well, live and learn.

Thanks anyway, for your fast response.

**Comment by manangatangy** [comment]
Interestingly enough, none of the APIs that I had disabled are actually being hit, as shown by the API dashboard.  Only the Maps SDK for Android records any requests against it, which is what I had expected.

**Comment by Soundbytes** [comment]
I just ran into the same problem building the place_tracker app on an android emulator. I was able to fix it just by uninstalling and rebuilding the app. The first build took a considerable time because I did it on a small laptop with another memory intense program running at the same time. 
On my main development machine I have never seen that error.

**Comment by temirfe** [comment]
I have no problem with authorization but map is not rendering, just white screen. 
I see this warning on terminal: `E/GoogleMapController( 7561): Cannot enable MyLocation layer as location permissions are not granted`

flutter doctor -v

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale ru-RU)
    • Flutter version 1.0.0 at C:\progs\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ProsoftPC\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\ProsoftPC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by charlybongo** [comment]
what error are you seeing

**Comment by Akshar-Patel** [comment]
I am facing the same issue. It has intermittent behaviour. Already tried different permissions library but it is not going away. Also tried putting permission directly in AndroidManifest.xml but still facing the same issue.

**Comment by alaksej** [comment]
In my case, the error was due to the Maps SDK for Android API being disabled. After enabling the API in the  [Google Cloud Platform Console](https://cloud.google.com/console/google/maps-apis/overview) the app started normally.

**Comment by Zeeshan0201** [comment]
![Screenshot from 2019-08-10 11-49-54](https://user-images.githubusercontent.com/45591301/62819086-dc198480-bb6d-11e9-9f70-5d453836c4c1.png)
@zoechi can you please check and help tried above methods but none of these worked for me !

**Comment by DenisBogatirov** [comment]
It seems like maps plugin using "internal" key for signing, I've restricted API_KEY for both my debug and release SHA1 and in the error message there are different, from my, SHA1

**Comment by kf6gpe** [comment]
Trying to clarify here --- it looks like some folks had problems with key provisioning, which are outside of flutter. @DenisBogatirov, are you indicating that there's a problem with the plugin itself as well?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
