### ISSUE TITLE
Occasionally Flutter Locks Up

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2502]
Attempted to debug with @abarth.

Observatory can't tell you anything.
Attempting a pause in Observatory locks up Observatory.

If we had debug symbols for production builds we could debug further.

I've seen similar lock ups about a handful of times over the last month or so.  Nothing before that.

**Comment by apwilson** [comment]
Happened again today:

```
$ flutter --version
Flutter from unknown source
Framework: 33d7d6dc98f7be14af7161154ad65c0777f3b521 (2 hours ago)
Engine:    dcbd64e460d922b9b7b86235db1472fef89933e7
```

**Comment by Hixie** [comment]
In the absence of release build symbols, if you still see this occasionally, would you be able to run with a local debug build? If you can, then when you hit this you could trigger a core dump (or attach a debugger) and then look at the stack to see where we might be going wrong.

**Comment by apwilson** [comment]
No longer seeing this.
