### ISSUE TITLE
Firebase Messaging is not clearing a notification tray

### ISSUE THREAD

**Issue by arsen** [flutter/flutter#25030]
Hello,
With firebase_messaging plugin, after receiving the notification if you open the app directly, instead of tapping on the notification (in a tray), the notification will stay there.

If you tap on the notification it will clear itself.

I was hoping that there would be a method to clear a system tray notification (or it will do it automatically).

**firebase_messaging: ^2.1.0**

flutter doctor -v.

```
[✓] Flutter (Channel master, v1.0.1-pre.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.0.1-pre.1 at /Users/user/flutter
    • Framework revision a226c0f0d9 (5 days ago), 2018-11-30 16:18:18 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Pixel 3                   • XXXXXXXXXX     • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)
```

**Comment by dspoonia7** [comment]
Facing the exact same issue. Any updates on this, please? Or any workaround to clear the notifications on app open? 
@zoechi

**Comment by TheJulianJES** [comment]
I think that it clears the notification on iOS, but not on Android.
As a workaround this could be used (in MainActivity.java of the Android app)
```
    @Override
    protected void onResume() {
        super.onResume();

        // Removing All Notifications
        cancelAllNotifications();
    }

    private void cancelAllNotifications() {
        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.cancelAll();
    }
```

**Comment by Nastya-Scherbakova** [comment]
> I think that it clears the notification on iOS, but not on Android.
> As a workaround this could be used (in MainActivity.java of the Android app)
> 
> ```
>     @Override
>     protected void onResume() {
>         super.onResume();
> 
>         // Removing All Notifications
>         cancelAllNotifications();
>     }
> 
>     private void cancelAllNotifications() {
>         NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
>         notificationManager.cancelAll();
>     }
> ```

after pasting your code and importing
```
import android.app.NotificationManager;
import android.content.Context;
```
everything worked fine! thank you!

**Comment by Gloumy** [comment]
I'm using the above code, my notification is cleared on app startup but it's coming back after a bit

**Comment by kroikie** [comment]
@arsen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/553. Any further collaboration will be done there.

**Comment by fenchai23** [comment]
How can this be done on Flutter?
