### ISSUE TITLE
debug 

### ISSUE THREAD

**Issue by shadowcz007** [flutter/flutter#25033]
flutter: #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #15     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #16     main (package:getgo/main.dart:3:16)
flutter: #17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════
════════════════════════════════════════════════════════════════════════════════════

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Unfortunately this issue doesn't provide enough information to diagnose the problem.
Please create a new issue with properly filled issue template.
