### ISSUE TITLE
<Tooling request> . Android Studio support for Add2App

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#25043]
I know this might be far off, but perhaps we could have an issue to track it or a card in Add2app project board - can we have Android Studio google support for Add2app.  file->Add Flutter or similar?

That would be really nice both in terms of 
a) automating the work
b) making sure it worked right
c) A general feeling of this being a well-supported mature procedure that existing large apps can feel more comfortable trying.

Huge Bonus points if it is bundled with Android Studio by default some day, even if a long time from now - giving the feeling that Flutter is a "first class citizen" for Android apps, as Kotlin support came after several years.

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2924](https://github.com/flutter/flutter-intellij/issues/2924) via [**ZenHub**](https://www.zenhub.com/)

**Comment by neiljaywarner** [comment]
Thanks. Sorry about that
