### ISSUE TITLE
Flutter Doctor brings only a blinking line when I run it

### ISSUE THREAD

**Issue by MrAppMachine** [flutter/flutter#25053]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the problem.
If this is still an issue please create a new issue with more information.

What steps did you take to install Flutter?
What directory did you install it to?
What OS (name, version) are you using?
What shell are you using (PowerShell, Command prompt, bash, ...)?
And any information that could help tracking the cause down.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
