### ISSUE TITLE
[google_maps_flutter] Google Map does not download image tiles if camera is moved every second

### ISSUE THREAD

**Issue by waynepiekarski** [flutter/flutter#25052]
I used the standard Google Maps Flutter sample at https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter and it seemed to work fine.

However, I added some code that moves the camera every second:
mapWidget.mapController.animateCamera(CameraUpdate.newLatLng(LatLng(latitude, longitude)));

With the camera constantly moving, it seems like the code which downloads the image tiles is stalled. If I pause my animation, any visible tiles download. If I restart the animation and change the map type, then the new tiles no longer download.

It seems like google_maps_flutter is unable to download anything while the map is moving, which could happen all the time if using GPS for positioning.

**Comment by jcowgar** [comment]
I can confirm this is occuring as well. I did find that it affects animateCamera only. Using moveCamera, tiles are downloaded no matter how often the camera moves. moveCamera, however, produces jerky movement of course so it is not preferred.

```
// controller.animateCamera(CameraUpdate.newCameraPosition(_movingMapBusinessObject.cameraPosition));
controller.moveCamera(CameraUpdate.newCameraPosition(_movingMapBusinessObject.cameraPosition));
```

These are my two lines of code. .animateCamera does not load tiles, .moveCamera does.

**Comment by csells** [comment]
@waynepiekarski or @jcowgar can you post a sample that demonstrates the behavior you're seeing? This sounds like an issue we'll want to dig into.

**Comment by hlongngo** [comment]
I am having the same issue. And it happens only in Android.

**Comment by fatalcaron** [comment]
I got the same issue. 
I use a geolocation pluggin (Location) and watch for the location change every seconds. At each change of location, I trigger the method animateCamera of GoogleMaps and the tiles is not loading.

If I change the interval of location at 1500 millisecondes everythings is fine.
