### ISSUE TITLE
firebase_analytics version solving failed.

### ISSUE THREAD

**Issue by BlankConan** [flutter/flutter#25059]
Running "flutter packages get" in FlutterWithFirebase...         
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because flutfire depends on firebase_analytics >=0.0.2 <0.3.0 which requires SDK version >=1.8.0 <2.0.0, version solving failed.
 
pub get failed (1)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

This just means your `pubspec.yaml` contains a dependency that is incompatible with another dependency or the Dart version you are using.

Recent `firebase_analytics` version is `1.0.6`, you project depends on `0.0.2` which is not compatible with Flutter/Dart2 (requires SDK version >=1.8.0 <2.0.0).  

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
