### ISSUE TITLE
flutter doctor: when XCode is installed, we show a Checkmark, even if version is wrong

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2505]
Was working with a new flutter developer, and we ran into a confusing output from `flutter doctor`. Please see this screenshot:

![screen shot 2016-03-08 at 12 47 53 pm](https://cloud.githubusercontent.com/assets/5479/13618511/652c7a34-e539-11e5-9271-53bb83f788ba.png)

Notice how XCode is checked, implying everything is good. However, the version is wrong, so the indented version check is unchecked. It's not clear that XCode is not correct.

Suggestion: show a `[-]` or `[x]` if XCode isn't the right version. We'd like checkmarks to indicate "good to go".

Thanks!

**Comment by devoncarew** [comment]
fixed by https://github.com/flutter/flutter/pull/2859

**Comment by sethladd** [comment]
Thanks!
