### ISSUE TITLE
get v4.app.FragmentManager from Flutter Plugin

### ISSUE THREAD

**Issue by rickyazhari** [flutter/flutter#25060]
i try to get `FragmentManager` in my Android Flutter plugin. In my case i need `v4.app.FragmentManager`.

but in `PluginRegistry` `Registrar`. i just get `app.FragmentManager` from `Registrar.activity().fragmentManager`

Since i use `FlutterFragmentActivity` which extend `v4.app.FragmentActivity`, So i think it's possible to get `v4.app.FragmentManager()`. anyone have idea how to reach that ?

**Comment by zoechi** [comment]
Cross-link https://stackoverflow.com/questions/53652167/get-v4-app-fragmentmanager-from-flutter-plugin

**Comment by rickyazhari** [comment]
thats me mr zoechi

**Comment by rickyazhari** [comment]
@zoechi  i think we can close this issue now. i found the way to get v4.app.fragmentmanager

thanks for your help

**Comment by zoechi** [comment]
Thanks for the update. Would be great if you could answer your StackOverflow question with your findings.
