### ISSUE TITLE
Why not use a thread pool for IO？Single thread has a performance bottleneck.

### ISSUE THREAD

**Issue by SupSaiYaJin** [flutter/flutter#25075]
We use a GridView to show a lot of pictures. When we scroll fast, the speed of decoding image won't catch up with the speed of scrolling causes worse experience than native. 
Compare to Fresco, it uses a thread pool to decode image.
So i suspect that a single thread for IO is enough?

**Comment by zoechi** [comment]
What is Fresco?
Are you sure the decoding is the bottleneck?
Can you provide a minimal reproduction?

Please add the output of `flutter doctor -v`.

**Comment by SupSaiYaJin** [comment]
https://github.com/facebook/fresco
Fresco is a system for displaying images in Android applications.
here is the trace.
The thing is even if the image is slide across the screen only a moment then disappeared, `PaintingBinding.instance.instantiateImageCodec(bytes)` will be called causes that images is currently showing must wait for the decoding of disappeared images.

[image_decode.txt](https://github.com/flutter/flutter/files/2657062/image_decode.txt)
![image](https://user-images.githubusercontent.com/10076965/49645773-18816780-fa58-11e8-8657-5520ee4e6ae3.png)

**Comment by SupSaiYaJin** [comment]
[✓] Flutter (Channel dev, v1.0.0, on Mac OS X 10.14.1 18B73a, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/SupSaiYaJin/Library/Android/flutter
    • Framework revision 5391447fae (7 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/SupSaiYaJin/Library/Android/sdk
    • Android NDK at /Users/SupSaiYaJin/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4892.25

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • Redmi Note 4X • 16fedaac0004 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by chinmaygarde** [comment]
This has been on my radar for a while and there is no reason we should not be attempting this already. I'll wire up the parallel task runners for known platforms.

**Comment by SupSaiYaJin** [comment]
> This has been on my radar for a while and there is no reason we should not be attempting this already. I'll wire up the parallel task runners for known platforms.

Thanks for focus on this issue.
We have tried to implement a IO task runnner pool for decoding image multi-threaded. For each thread, we created a GrContext and a SkiaUnrefQueue for it. It works well on decoding, but there is a problem on SkImage's deallocation. 
The thing is SkImage must be deallocated in the thread which created it, but I can't make sure the SkImage is unrefed by the new SkiaUnrefQueue we created. The reason is SkImage's reference is holded by Codec and SkPicture at the same time, it's uncertain of which one is the last one to unref it, so it might be unref in wrong SkiaUnrefQueue.
be eager for your help.

**Comment by chinmaygarde** [comment]
It may be easier to perform image decompression on a worker but still perform texture upload on the IO thread. I am prototyping something right now. Do you have a reduced test case for this?

**Comment by chinmaygarde** [comment]
Update: I pushed some WIP changes to prepare a concurrent message loop (Darwin is done, on Linux now). My approach is then to use the SkImageGenerator to first create the pixmap from encoded data on one thread and then perform the MakeCrossContextFromPixmap on the IO thread.

**Comment by SupSaiYaJin** [comment]
> It may be easier to perform image decompression on a worker but still perform texture upload on the IO thread. I am prototyping something right now. Do you have a reduced test case for this?

I have tried decoding 300 images asynchronously in 4 threads. It's more than 3 times faster than single IO thread for Android. For iOS, it's more than 2 times faster.

**Comment by dnfield** [comment]
I believe this would also fix https://github.com/flutter/flutter/issues/32143

**Comment by ened** [comment]
@chinmaygarde Hi Chinmay, did you get any closer to a multi-threaded image decoder in Flutter?

**Comment by sgldev** [comment]
Hi All, we have recently launched a flutter app and this issue is currently killing us on older iPhones and we are starting to attract negative reviews. Is there an ETA for this to be fixed?

**Comment by xster** [comment]
@chinmaygarde https://github.com/flutter/engine/pull/9486 is your solution for this right? @SupSaiYaJin can you check if that PR covers your concern or test it in your use case by applying the patch locally?

**Comment by SupSaiYaJin** [comment]
@xster I got a compile error for this patch.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/commit/ad582b5089256e56727b2d7306fb097078a3dcdc
