### ISSUE TITLE
Not able to exclude files in flutter test coverage

### ISSUE THREAD

**Issue by jakthegr8** [flutter/flutter#25077]
I am trying to exclude few `config files (constants/passwords/etc and also for translations) `from the test coverage results in the flutter test results. When I run `flutter test --coverage`, the output file `icov.info` is having information about the `config files` as well, which is affecting overall coverage percentage. I don't see an option to exclude that. Not sure it is a bug or feature request?

**Comment by Muldec** [comment]
That would be very useful to exclude generated code as well (*.g.dart)

**Comment by zoechi** [comment]
If you upload for example to codecov.io the upload script allows to exclude files or folders.
I agree it would be great to have that in Dart/Flutter as well.

**Comment by adalberht** [comment]
any news on this? this would be great!

**Comment by svprdga** [comment]
We're very interested in this feature!

**Comment by danwulff** [comment]
I specifically would like to be able to exclude l10n related files.

**Comment by starlitya** [comment]
Request this also, thanks

**Comment by AlienEngineer** [comment]
+1

**Comment by lawonga** [comment]
+1

**Comment by rubenramos4** [comment]
+1

**Comment by joaomaciel-toro** [comment]
+1

**Comment by isacjunior** [comment]
Some news about this?

**Comment by alexviquez** [comment]
+1

**Comment by ccfiel** [comment]
+1

**Comment by lucabarbi** [comment]
+1

**Comment by aBuder** [comment]
+1

**Comment by LeoMaldonado** [comment]
+1

**Comment by eibreans** [comment]
+1

**Comment by RashmiRanganathan** [comment]
+1

**Comment by devapalanisamy** [comment]
+1

**Comment by vargavince91** [comment]
As the "+1" comments keep coming in, I would recommend you "upvote" the original issue, so that the Flutter team can prioritize this issue accordingly (AFAIK, this is a metric they look at for prioritizing).

With that said, +1 🤪

**Comment by miguelslemos** [comment]
Workaround

```
lcov --remove 'raw.xml' -o 'coverage.xml' '**/lib/**/*.query.dart' '**/lib/**/*.mutation.dart' '**/lib/**/*.g.dart'
```

**Comment by vanlooverenkoen** [comment]
I wrote a dart program that can filter files, lines 

```
import 'dart:io';

main() {
  print('Start filtering the lcov.info file');
  final file = File('coverage/lcov.info');
  if (!file.existsSync()) {
    print('"lcov.info" does not exist');
    return;
  }
  const endOfRecord = 'end_of_record';
  final sections = List<LcovSection>();
  final lines = file.readAsLinesSync();
  LcovSection currentSection;
  lines.forEach((line) {
    if (line.endsWith('.dart')) {
      final filePath = line.replaceAll('SF:', '');
      currentSection = LcovSection()
        ..header = line
        ..filePath = filePath;
    } else if (line == endOfRecord) {
      currentSection.footer = line;
      sections.add(currentSection);
    } else {
      currentSection.body.add(line);
    }
  });
  final filteredSections = getFilteredSections(sections);
  final sb = StringBuffer();
  filteredSections.forEach((section) {
    sb.write(section.toString());
  });
  file.writeAsStringSync(sb.toString());
  print('Filtered the lcov.info file');
}

class LcovSection {
  String filePath;
  String header;
  final body = List<String>();
  String footer;

  String getBodyString() {
    final file = File(filePath);
    final content = file.readAsLinesSync();
    final sb = StringBuffer();
    getFilteredBody(body, content).forEach((item) => sb..write(item)..write('\n'));
    return sb.toString();
  }

  @override
  String toString() {
    return '$header\n${getBodyString()}$footer\n';
  }
}

List<LcovSection> getFilteredSections(List<LcovSection> sections) {
  return sections.where((section) {
    if (section.header.endsWith('.g.dart')) {
      return false;
    }
    return true;
  }).toList();
}

List<String> getFilteredBody(List<String> body, List<String> lines) {
  return body.where((line) {
    if (line.startsWith('DA:')) {
      final sections = line.split(',');
      final lineNr = int.parse(sections[0].replaceAll('DA:', ''));
      final callCount = int.parse(sections[1]);
      if (callCount == 0) {
        final fileLine = lines[lineNr - 1].trim();
        if (excludedLines.contains(fileLine)) {
          return false;
        }
      }
    }
    return true;
  }).toList();
}

const excludedLines = [
  'const Something();,
];

```

**Comment by tapizquent** [comment]
Is there a way now to exclude certain files from the generated `lcov.info` from `flutter test --coverage`? It's been almost 2 years since this issue was opened

**Comment by devmsh** [comment]
Any updates!

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/dart-lang/coverage/pull/302 and supported in flutter shortly after

**Comment by shouichi** [comment]
Hi, the meta-comment (e.g., `coverage:ignore-file `) does not fully cover our use case. We want to exclude generated files (e.g., `*.g.dart` generated by `built_value_generator`) from coverage but they do not contain the meta-comment. We could fix the generator to add the meta-comment but it might make more sense to let developers choose whether to include generated files from coverage or not.

See also https://github.com/dart-lang/coverage/issues/313.

Thank you.
