### ISSUE TITLE
Request to bump hackathon branch

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2507]
A lot has been fixed/updated. We'll also want to double-check the firechat app still works.

**Comment by sethladd** [comment]
cc @qchong because when we bump hackathon branch, the firechat app might break.

**Comment by abarth** [comment]
Certainly we'll need to change the icons from "content/send" to `Icons.send`

**Comment by abarth** [comment]
Updating example in https://github.com/flutter/firechat-flutter/pull/25

**Comment by abarth** [comment]
Done.
