### ISSUE TITLE
Using chips in cupertino app not work anymore

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25086]
Previous, in cupertino app, we wanna using chips, just wrap it inside Material componets. but now it will crash and error says:

```
 No MaterialLocalizations found.
I/flutter (29946): RawChip widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter (29946): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter (29946): by the material library.
```

But am already wrap it inside material components. I saw some hints on locales but I do not understand how to set it (I am using CupertinoApp both on android and ios)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/21872#issuecomment-421508939 should help

**Comment by zoechi** [comment]
Is this still an issue?
