### ISSUE TITLE
@mustCallSuper should work with inheritance hierarchies 

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#25097]
We ran into an issue with keep alives not working. We were using the `AutomaticKeepAliveClientMixin` in an abstract `State` class. Because of the `@mustCallSuper` annotation, we knew to call `super.build` in the `build` method of the abstract class. However, there was no warning for the fact that we weren't calling `super.build` in the concrete implementations of our abstract `State` class.

I can't envision a case where you wouldn't want the annotation to extend to all transitive subclasses.

**Comment by zoechi** [comment]
I think this should be reported in dart-lang/sdk or dart-lang/linter

**Comment by alanrussian** [comment]
Thanks. Filed https://github.com/dart-lang/sdk/issues/35372

**Comment by zoechi** [comment]
Duplicate of dart-lang/sdk#35372
