### ISSUE TITLE
error in url_launcher package

### ISSUE THREAD

**Issue by karan7701** [flutter/flutter#25098]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by karan7701** [comment]
![screenshot from 2018-12-08 02-13-54](https://user-images.githubusercontent.com/38702947/49672210-62863f80-fa90-11e8-9b3e-885b9980b268.png)
 please note i am using flutter beta 0.11.13 .

**Comment by diegoveloper** [comment]
Looks like you modified the url_launcher.dart file,  remove the first line or get the packages again from pubspec, check how it is in the repo:  https://github.com/flutter/plugins/blob/master/packages/url_launcher/lib/url_launcher.dart
