### ISSUE TITLE
App installation failed on iOS - Bundle identifiers must be unique.

### ISSUE THREAD

**Issue by Kigstom** [flutter/flutter#25090]
## Steps to Reproduce

Good evening, first of all I'm a noob on programming.
The problem that I had is not quite reproducible, because that appends only on the iOS part, the Android one solves it or for my perspective handles it better.
I cannot share the app source code (for legal reasons), because I'm a member of a bigger team of from a company and for my review in the code I don't seen the problem in it (its other).
The problem that a have is that when I try to launch the application to the device it shows the error:

>  This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.

![screenshot 2018-12-07 at 18 05 50](https://user-images.githubusercontent.com/45695568/49664826-e74e6a80-fa4a-11e8-9fc4-21f290f0d77d.png)

 I add already pushed one to the App Store Connect, and when a tried the second time it was rejected because of the error above (that I tried myself to test it on release mode). I already asked the iOS team and the support team, they redirect me to you (flutter HQ team).

 I have also an off topic question: - I launch an application on debug mode (actually 2) to an iOS device, and a found that after some time (like some days), if the apps are in the device and unplugged from the android Studio (platform that I use to work) they not even start, go down after trying to display the first screen. The apps that I used for this little experiment were the default app and one that a developed (actually a tutorial).

## Logs
```
[  +30 ms] executing: [/Users/daniel/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/daniel/Development/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Users/daniel/Development/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/daniel/Development/flutter/] git log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/daniel/Development/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 days ago
[        ] executing: [/Users/daniel/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +270 ms] executing: /Users/daniel/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/daniel/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ce061606357a663003     device usb:3145728X product:hero2ltexx model:SM_G935F device:hero2lte transport_id:176
[  +11 ms] executing: idevice_id -h
[  +67 ms] executing: which ideviceinstaller
[   +4 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +4 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +247 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +7 ms] /Users/daniel/Library/Android/sdk/platform-tools/adb -s ce061606357a663003 shell getprop
[  +79 ms] ro.hardware = samsungexynos8890
[   +4 ms] SM G935F • ce061606357a663003                       • android-arm64 • Android 8.0.0 (API 26)
[   +1 ms] Kingston • 04210186bc41a3571f6a719ead92f49b5f62e88c • ios           • iOS 12.1.1
[  +13 ms] "flutter run" took 664ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:249:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:379:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///Users/daniel/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```
```
No issues found! (ran in 1.5s)
```
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-PT)
    • Flutter version 1.0.0 at /Users/daniel/Development/flutter
    • Framework revision 5391447fae (8 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK at /Users/daniel/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/daniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • SM G935F • ce061606357a663003                       • android-arm64 • Android 8.0.0 (API 26)
    • Kingston • 04210186bc41a3571f6a719ead92f49b5f62e88c • ios           • iOS 12.1.1

• No issues found!
```

**Comment by zoechi** [comment]
> I have also an off topic question: - I launch an application on debug mode (actually 2) to an iOS device, and a found that after some time (like some days), if the apps are in the device and unplugged from the android Studio (platform that I use to work) they not even start, go down after trying to display the first screen. The apps that I used for this little experiment were the default app and one that a developed (actually a tutorial).

probably better to create a new issue for that

**Comment by ThinOfSnowDance** [comment]
你们用flutter开发什么类型的应用啊?是直接在生产环境用吗?

**Comment by Kigstom** [comment]
> 你们用flutter开发什么类型的应用啊?是直接在生产环境用吗?
Hi, if the translator is not tricking the answers for that questions are:
1- I'm developing an app with iap purchases included;
2- What you mean by the second question? "Is it used directly in the production environment?".

**Comment by Moukale** [comment]
I get the same issue and I solved it by changing the _CFBundleIdentifier_ in this file : 

_ios/Flutter/AppFrameworkInfo.plist_ 

I added **.app** to the flutter BundleId **XXX** :
`<key>CFBundleIdentifier</key>
	<string>XXX.app</string>`

**Comment by Kigstom** [comment]
> I get the same issue and I solved it by changing the _CFBundleIdentifier_ in this file :
> 
> _ios/Flutter/AppFrameworkInfo.plist_
> 
> I added **.app** to the flutter BundleId **XXX** :
> `<key>CFBundleIdentifier</key> <string>XXX.app</string>`

**Comment by Kigstom** [comment]
> I get the same issue and I solved it by changing the _CFBundleIdentifier_ in this file :
> 
> _ios/Flutter/AppFrameworkInfo.plist_
> 
> I added **.app** to the flutter BundleId **XXX** :
> `<key>CFBundleIdentifier</key> <string>XXX.app</string>`

Hi there, have to question:
1º- The "XXX" is my bundle identifier, correct?;
2º- Why the bundle id of the framework needs to be different?.

**Comment by Moukale** [comment]
I'm really not an expert on this but what I understand is : there is a subproject **_Flutter_** in the **_app_**. And the IOS failed because the two projects have **_the same bundleId_**.

In my case, I need my project to have the **_bundleId_** that I declare on **_firebase_**. That's why I changed the flutter one.

**Comment by Kigstom** [comment]
> I'm really not an expert on this but what I understand is : there is a subproject **_Flutter_** in the **_app_**. And the IOS failed because the two projects have **_the same bundleId_**.
> 
> In my case, I need my project to have the **_bundleId_** that I declare on **_firebase_**. That's why I changed the flutter one.

Hi, sorry for the late response, with your suggested changes its working now just fine.
I thank you for the answer.

**Comment by zoechi** [comment]
Sounds like a support request that got solved.
Thanks @Moukale

**Comment by JoseFMP** [comment]
> > I get the same issue and I solved it by changing the _CFBundleIdentifier_ in this file :
> > _ios/Flutter/AppFrameworkInfo.plist_
> > I added **.app** to the flutter BundleId **XXX** :
> > `<key>CFBundleIdentifier</key> <string>XXX.app</string>`
> 
> Hi there, have to question:
> 1º- The "XXX" is my bundle identifier, correct?;
> 2º- Why the bundle id of the framework needs to be different?.

This did not work for me.

**Comment by bm2ilabs** [comment]
@JoseFMP any luck with the issue ?
