### ISSUE TITLE
Skyshell crashed SIGSEGV

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2509]
```
03-08 16:24:47.386 23874 23883 E System  : Uncaught exception thrown by finalizer
03-08 16:24:47.386 23874 23883 E System  : java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
03-08 16:24:47.386 23874 23883 E System  : 	at org.chromium.mojo.bindings.AutoCloseableRouter.finalize(AutoCloseableRouter.java:111)
03-08 16:24:47.386 23874 23883 E System  : 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
03-08 16:24:47.386 23874 23883 E System  : 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
03-08 16:24:47.386 23874 23883 E System  : 	at java.lang.Thread.run(Thread.java:818)
03-08 16:24:49.343   173   226 E hwc-drm-compositor-worker: Failed to squash all -114
03-08 16:24:49.956  1339  1604 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 116] to 60
--------- beginning of crash
03-08 16:24:51.548 23874 23903 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe0083000 in tid 23903 (ui_thread)
03-08 16:24:51.654  1045  1045 E         : process stopped due to unexpected signal 27
```

**Comment by abarth** [comment]
How can I reproduce this issue?

**Comment by Hixie** [comment]
@apwilson Without steps to reproduce, a stack trace, or something, there's not much we can do here. Please reopen the bug (or file a new one) if you can give us something actionable. :-)

**Comment by jamesr** [comment]
I remember looking with @collinjackson a few months back at a number of places in flutter that have mojo or android objects owned by dart or java objects without an explicit teardown path.  In both cases this produces potentially pretty bad memory leaks as neither the Android runtime nor the Dart runtime promise to run finalizers promptly or even run them at all.  I don't remember if anything came of this.

In this case the Mojo bindings Java finalizer is the one complaining that some Java object was holding on to a Mojo handle when the finalizer ran, meaning it wasn't explicitly destroyed.

**Comment by Hixie** [comment]
Sounds like a dupe of #2950.
