### ISSUE TITLE
Can't set colour of raised button

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#251]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 18:37 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1918_

----

**Comment by abarth** [comment]
You can do this now.
