### ISSUE TITLE
Camera plugin: CameraException( Unsupported angle: 271 ) upon calling `cameraController.startVideoRecording`

### ISSUE THREAD

**Issue by mnazim** [flutter/flutter#25105]
Hi trying to record a camera results in exception. 

Calling code.

```dart
    try {
      await _cameraController.startVideoRecording(filePath);
    } on CameraException catch (e) {
      print("recording exception = $e");
    }
```

Exception.
```
[   +8 ms] E/MethodChannel#plugins.flutter.io/camera(20097): Failed to handle method call
[        ] E/MethodChannel#plugins.flutter.io/camera(20097): java.lang.IllegalArgumentException: Unsupported angle: 271
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at android.media.MediaRecorder.setOrientationHint(MediaRecorder.java:592)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at io.flutter.plugins.camera.CameraPlugin$Camera.prepareMediaRecorder(CameraPlugin.java:451)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at io.flutter.plugins.camera.CameraPlugin$Camera.startVideoRecording(CameraPlugin.java:619)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at io.flutter.plugins.camera.CameraPlugin$Camera.access$900(CameraPlugin.java:256)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:208)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at android.os.MessageQueue.next(MessageQueue.java:326)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at android.os.Looper.loop(Looper.java:160)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at android.app.ActivityThread.main(ActivityThread.java:6680)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/MethodChannel#plugins.flutter.io/camera(20097):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by wouterhardeman** [comment]
I've looked into this and I think I found the problem in the plugin.

In the plugin the `currentOrientation` property is set to the constant `ORIENTATION_UNKNOWN` by default, which results in -1. When your orientation updates, it is set to the actual value. The `setOrientationHint` function only accepts 0, 90, 180 and 270 as argument. When calculating the orientation it adds the 1 or -1 (depending on whether you are using the back or front camera). That resulted in 271, which isn't accepted and caused your error. I will make a pull request tomorrow to fix this.

**Comment by matte5031** [comment]
Did you guys solve it? I have the exact samt issue but with the camera, for example I get:

E/AndroidRuntime(18457): java.lang.IllegalArgumentException: Invalid rotation=89
E/AndroidRuntime(18457): 	at android.hardware.Camera$Parameters.setRotation(Camera.java:3241)
E/AndroidRuntime(18457): 	at android.hardware.camera2.legacy.LegacyRequestMapper.convertRequestMetadata(LegacyRequestMapper.java:405)
E/AndroidRuntime(18457): 	at android.hardware.camera2.legacy.LegacyMetadataMapper.convertRequestMetadata(LegacyMetadataMapper.java:1221)
E/AndroidRuntime(18457): 	at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:819)
E/AndroidRuntime(18457): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime(18457): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(18457): 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by matte5031** [comment]
Okay cool, good job! @wouterhardeman Sorry this might be a nooby question but, is there any way to use your code with the flutter camera even though it haven't been merged by a maintainer yet?

**Comment by wouterhardeman** [comment]
@matte5031 This should work!
```
camera:
    git:
      url: git://github.com/wouterhardeman/plugins.git
      path: packages/camera
```

**Comment by matte5031** [comment]
I've now tried it and can confirm that it is working, well done! and thanks! :) @wouterhardeman

**Comment by matte5031** [comment]
Ye I saw, thanks!
