### ISSUE TITLE
ios/Flutter/Flutter.framework/Flutter is 66.10Mb

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#25101]
## Steps to Reproduce

I've created a new Flutter application (`flutter create`) using the stable 1.0 channel/build. I've worked on it for a few days, and added a few plugins (namely `google_sign_in` and `firebase_auth`).

When I'm done working on a feature, I commit and push (`git push`) to GitHub:

> `git commit -am "Feature."`
> `git push`

... where it takes a few seconds, even on a very fast connection, and I get:

> "remote: warning: File ios/Flutter/Flutter.framework/Flutter is 66.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB"

Is this a file I should not be committing to Git? Should it be `.gitignore`'d?

## Logs

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Users/matan/git/flutter
    • Framework revision 5391447fae (8 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/matan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone SE • 7C5309DE-7F41-47E0-B11D-EBC3B8C5970F • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by matanlurey** [comment]
Oh, and to be clear, everything seems to work.

/cc @jonahwilliams 😛

**Comment by goderbauer** [comment]
The `.gitignore` that `flutter create` generates has an entry to ignore this file: https://github.com/flutter/flutter/blob/d927c9331005f81157fa39dff7b5dab415ad330b/packages/flutter_tools/templates/create/.gitignore.tmpl#L58

... and I just checked on my local 1.0.0 branch: it is ignored there by git.

What does your `.gitignore` file in your top level app directory look like? Is it missing that entry? Did you modify that file by any chance?

**Comment by matanlurey** [comment]
Ah I see. Funny enough, I created another sample project to try again, and the `.gitignore` seems to be working. I wonder if I either accidentally overwrote it or something else naughty. I'll re-open if it occurs again, thanks!
