### ISSUE TITLE
shared install not possible

### ISSUE THREAD

**Issue by heseremandmi** [flutter/flutter#25108]
when doing a shared install (one installation for many users to use) flutter 1.0 complains about not being able to write to the shared install location, in my case /opt/flutter/bin/cache/lockfile. Well, it shouldn't write in a shared install location...

**Comment by zoechi** [comment]
That's currently not supported. Flutter needs write access in its installation directory.

**Comment by zoechi** [comment]
Related to #4674

**Comment by christopherfujino** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/44526. Please follow there for discussion/updates!
