### ISSUE TITLE
Flutter Doctor crashes when tools/sdkmanager is not available

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#25119]
This has already been discussed in #16878, but it may have been closed prematurely.

The issue is still there (`flutter doctor` crashes without going further) when used e.g. on CI and [installing SDK via Gradle](https://developer.android.com/studio/intro/update#download-with-gradle). IIUC, this is a legitimate use case.

Here are the steps to reproduce:

1. Download Flutter via Git repository or archive
1. Set path to Flutter tool in Android application:
   ```shell
   $ echo "flutter.sdk=$FLUTTER_SDK_ROOT" > android/local.properties
   ```
   This is marginally legitimate, necessary step for bootstrapping :)
1. Copy license information from a developer's workstation
1. Run `flutter doctor`:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Linux, locale en_US.UTF-8)
Android sdkmanager tool not found (/home/travis/sdk/android/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.io/setup/#android-setup for detailed instructions.
```

I'd expect `flutter doctor` to go further and identify at least Dart SDK version etc.

**Comment by tvolkert** [comment]
Re-opening because the fix was reverted in https://github.com/flutter/flutter/pull/28295
