### ISSUE TITLE
"Oops; flutter has exited unexpectedly."

### ISSUE THREAD

**Issue by fontainearthur** [flutter/flutter#25110]
Hello,

After run `flutter doctor -v`, the results is this :

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Doctor summary (to see all details, run flutter doctor -v):
 
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to /Users/arthurfontaine/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

[flutter_01.log](https://github.com/flutter/flutter/files/2659497/flutter_01.log)

I make a `flutter upgrade` before.

Can you help me ?

**Comment by zoechi** [comment]
Sounds like https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path

**Comment by zoechi** [comment]
Could you make progress?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
