### ISSUE TITLE
PageView contain pageView ，when scroll child pageview finish ,parent not scroll to

### ISSUE THREAD

**Issue by rainmeterLotus** [flutter/flutter#25111]
I have a problem!
There is PageView contain 4 page(A,B,C,D)s,one of A page also is pageView,that have 2 page(X,Y)
when I at A page scroll X to Y,and scroll Y is can't scroll to B! I want can scroll to B.how can do

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
