### ISSUE TITLE
StreamBuilder always ConnectionState.waiting on iOS device, on Android device ConnectionState.active

### ISSUE THREAD

**Issue by Admokonugroho** [flutter/flutter#25129]
Connection state at function `submitButton` always wating on iOS Device.
```dart
Widget submitButton(LoginBloc bloc) {
    return StreamBuilder(
      stream: bloc.submitValid,
      builder: (context, snapshot) {
        return RaisedButton(
            child: Text('Login'),
            color: Colors.blue,
//          if one of the two streams has an error, or has no data, the button onPressed gives null to stay unclickable
            onPressed: snapshot.hasData ? null : null);
      },
    );
  }
```

this file for login Screen :
[login_screen.txt](https://github.com/flutter/flutter/files/2660377/login_screen.txt)

this file for login bloc
[login_bloc.txt](https://github.com/flutter/flutter/files/2660378/login_bloc.txt)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
