### ISSUE TITLE
Images not showing up in Gallery after being taken (Image Picker)

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#25124]
Currently using image_picker: ^0.4.10 and after taking a photo, the image shows up on the filesystem on Android, but it isn't seen by gallery apps like Google Photos or Flutter image pickers. I've tried using a Top Level directory on the internal storage, and even a directory inside the DCIM folder and it still doesn't show up. Photos from the device's camera do show up

**Comment by cyanglaz** [comment]
@ThinkDigitalRepair Did you mean the pick picked on image picker is not saved permanently? Right now the image picker doesn't save the photo taken permanently by intention. If you'd like this feature to be added into the image picker, could you please open a new ticket explain this feature in detail and explain why it should be in the plugin.

**Comment by kf6gpe** [comment]
Closing per @cyanglaz 's comment, as this is a stale issue.
