### ISSUE TITLE
Launching icon is not changing properly

### ISSUE THREAD

**Issue by hrwndr** [flutter/flutter#25136]
Launching icon of my flutter app is not changing properly. Flutter icon is still showing in some places after i changed the launching icon. Icon of the release apk is still flutter icon.

![img_20181209_203317](https://user-images.githubusercontent.com/27952903/49699011-b3fa1000-fbf1-11e8-81dd-f90820637f9a.jpg)

![img_20181209_203223](https://i.ibb.co/hDWLLHV/Screenshot-2018-12-09-20-39-33-805-com-android-systemui.jpg)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.
Did you follow the instructions in https://flutter.io/docs/deployment/android?
Please add the information about where you placed the icon file, the name you used and the configuration changes you made.

**Comment by zoechi** [comment]
Also try `flutter clean` and run again
and try `flutter build apk --release` and `flutter install` and check if any of these fix the issue.

**Comment by hrwndr** [comment]
Here is `flutter doctor` : 
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code (version 1.26.1)
[√] VS Code, 64-bit edition (version 1.29.1)
[√] Connected device (1 available)

• No issues found!`

And yes i tried all of the methods you mentioned.

**Comment by paulkastel** [comment]
I have also this issue. My flutter doctor: 
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale pl-PL)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\k\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.1)
    • VS Code at C:\Users\k\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • MI 6 • a0e46461 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
App in menu have new changed icon but in task menu or "detailed information" is still Flutter icon. Running solution in release mode does not help.

**Comment by paulkastel** [comment]
This problem happened to me also with my Xiaomi MI 6 with Android 8.0.0.
To solve it just reboot your phone.
Source: https://stackoverflow.com/questions/51569550/flutter-mini-icon-not-change

**Comment by daniel-krastev** [comment]
I have the same issue with _Redmi 5 Plus_ - Android 8.1.0. Even after a restart, the small icon is a Flutter one. Even not just that, in the Installed apps section in the settings, the app appears with the Flutter icon.

**Comment by paulkastel** [comment]
@daniel-krastev well for me that worked, steps I took: I used this package https://pub.dartlang.org/packages/flutter_launcher_icons to create icons, then the problem occured. Next I used commands which @zoechi proposed (clean and release), but they didnt worked. Then uninstalled application form MI6, rebooted phone, and install app again - and all icons on Android were correct. both debug and release mode.

**Comment by PonnamKarthik** [comment]
Clearing app cache fixed my issue

**Comment by scognito** [comment]
> @daniel-krastev well for me that worked, steps I took: I used this package https://pub.dartlang.org/packages/flutter_launcher_icons to create icons, then the problem occured. Next I used commands which @zoechi proposed (clean and release), but they didnt worked. Then uninstalled application form MI6, rebooted phone, and install app again - and all icons on Android were correct. both debug and release mode.

Didn't work on my Mi 9T. I think this is a device issue

**Comment by csells** [comment]
@hrwndr can you provide steps to reproduce this issue?

**Comment by halilkayaci** [comment]
Reboot your phone. It's solved.

**Comment by scognito** [comment]
It's clearly a phone cache problem. Same app on two device works differently. Even rebooting, clearing cache and such, still old icon. Not a problem for me though

**Comment by AlbertDavid94** [comment]
@paulkastel and @daniel-krastev both use a xiaomi phone, like myself. I've deleted all .png files from my project folder, cleaned my cache on my phone, rebooted, reinstalled, rebuilt and still I get the older version of my icon. I've been on this for hours and and I'm slowly losing my shit haha.

**Comment by campovski** [comment]
I had the same issue on iOS. All icons were changed but the one above the app when you can slide to close the apps. Deleting the app and reinstalling did not help. Rebooting the phone worked!
