### ISSUE TITLE
I have problem in linking with python files in starcore_for_ios directory.

### ISSUE THREAD

**Issue by Brijeshlakkad** [flutter/flutter#25139]
Please see this [problem](https://github.com/srplab/starcore_for_flutter/issues/4#issuecomment-445547245)

_Originally posted by @Brijeshlakkad in https://github.com/flutter/flutter/issues/13364#issuecomment-445553528_

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
