### ISSUE TITLE
Missing ability to use security code autofill in keyboard on iOS 12

### ISSUE THREAD

**Issue by nailgilaziev** [flutter/flutter#25135]
iOS 12 bring new keyboard functionality
* Password AutoFill 
* Automatic Strong Passwords 
* and **Security Code AutoFill** 

more info can be founded in [wwdc](https://developer.apple.com/videos/play/wwdc2018/204/) and in [docs](https://developer.apple.com/documentation/security/password_autofill/about_the_password_autofill_workflow)

![image](https://user-images.githubusercontent.com/2749021/49698246-307cf680-fbd2-11e8-8aad-ac655dad92a1.png)

Here digit code readed from messages app by OS and presented in keyboard.

This functionality not available in flutter by now and I can't find a way to workaround it with existing components

**Comment by nikhil-francium** [comment]
Any update ?

**Comment by skela** [comment]
Related to this here: https://github.com/flutter/flutter/issues/22858
I think it was implemented at some point, but has since stopped working. Hopefully they fix it soon.

**Comment by pedromassango** [comment]
Is there any update on this?

**Comment by jbrantl8** [comment]
Any updates here?

**Comment by pedromassango** [comment]
@jbrantl8 not yet. It seems that this feature doesn't take priority yet.

Anyway, I was able to do a workaround today, and got it working.

How my workaround was made:
 
1. Show a native TextField;
2. Use MethodChannel to retrieve the text in the native TextField every time the text changes;

Now when a OTP comes, the keyboard will show it and if you click on the code, it will be placed in the Native TextField.

This is the workaround that I find to implement it, and get things done.
Note: ignore the UI it was just for tests propose.

![IMG_20200312_152542](https://user-images.githubusercontent.com/33294549/76658491-89c19b80-6574-11ea-91bd-47fd8c661108.jpg)
![IMG_20200312_152548](https://user-images.githubusercontent.com/33294549/76658505-90501300-6574-11ea-9e2a-9773f6c09907.jpg)

**Comment by LongCatIsLooong** [comment]
You should be able to get one-time passwords on the master channel now. Please file new issues if autofill isn't working properly. For known issues see: https://github.com/flutter/flutter/issues/13015#issuecomment-624921951

**Comment by pedromassango** [comment]
Any docs on how to configure the TextField so that it receive the OTP from the keyboard?

**Comment by jbrantl8** [comment]
> @jbrantl8 not yet. It seems that this feature doesn't take priority yet.
> 
> Anyway, I was able to do a workaround today, and got it working.
> 
> How my workaround was made:
> 
> 1. Show a native TextField;
> 2. Use MethodChannel to retrieve the text in the native TextField every time the text changes;
> 
> Now when a OTP comes, the keyboard will show it and if you click on the code, it will be placed in the Native TextField.
> 
> This is the workaround that I find to implement it, and get things done.
> Note: ignore the UI it was just for tests propose.
> 
> ![IMG_20200312_152542](https://user-images.githubusercontent.com/33294549/76658491-89c19b80-6574-11ea-91bd-47fd8c661108.jpg)
> ![IMG_20200312_152548](https://user-images.githubusercontent.com/33294549/76658505-90501300-6574-11ea-9e2a-9773f6c09907.jpg)

Sorry for delay @pedromassango . Thanks for the workaround. It looks like it may be supported now per @LongCatIsLooong ?

**Comment by pedromassango** [comment]
Any instruction on how to implement it?

**Comment by LongCatIsLooong** [comment]
adding `autofillHints: const <String>[AutofillHints.oneTimeCode]` should do it: https://master-api.flutter.dev/flutter/material/TextField/autofillHints.html & https://master-api.flutter.dev/flutter/services/AutofillHints/oneTimeCode-constant.html (whoops looks like I messed up the doc).

**Comment by pedromassango** [comment]
"The input field expects a single-factor SMS login code"

What about removing the "login" word here? since we use OTP for many things, even payment validation?!

**Comment by koskimas** [comment]
@LongCatIsLooong This no longer works at least on iOS 14 and iPhone 8. `oneTimeCode` has no effect whatsoever.

**Comment by vladmazur** [comment]
AutofillHints.oneTimeCode works on flutter web in Safari
