### ISSUE TITLE
Unable to install correctly on Linux

### ISSUE THREAD

**Issue by labermt** [flutter/flutter#25148]
## Steps to Reproduce

Install according to directions on https://flutter.io/docs/get-started/install/linux

Note the owner and group are unknown (id is 1024). Changed them to root as they are in the standard android-studio install to attempt to fix. 

Problem still is there. Note the bin folder is not available to anyone but owner 1024 (or root if you attempt to fix install). 
```
bessermt@bessermt-Latitude-E6440 /opt/flutter/bin/cache/dart-sdk $ ls -al
total 40
drwxr-xr-x  5 root root 4096 Dec  4 09:32 .
drwxr-xr-x  6 root root 4096 Dec  4 09:33 ..
drwx------  3 root root 4096 Nov 29 14:16 bin
-rw-r--r--  1 root root   47 Nov 19 21:36 dartdoc_options.yaml
drwxr-xr-x  2 root root 4096 Nov 19 21:42 include
drwxr-xr-x 26 root root 4096 Nov 19 21:42 lib
-rw-r--r--  1 root root 2500 Nov 19 21:36 LICENSE
-rw-r--r--  1 root root  936 Nov 19 21:36 README
-rw-r--r--  1 root root   41 Nov 19 21:42 revision
-rw-r--r--  1 root root   14 Nov 19 21:42 version
bessermt@bessermt-Latitude-E6440 /opt/flutter/bin/cache/dart-sdk $
```

## Logs

bessermt@bessermt-Latitude-E6440 /opt/flutter $ flutter doctor -v
/opt/flutter/bin/flutter: line 177: /opt/flutter/bin/cache/dart-sdk/bin/dart: Permission denied
bessermt@bessermt-Latitude-E6440 /opt/flutter $

**Comment by zoechi** [comment]
The Flutter directory needs to be writeable for the users.
Install it into `cd ~/development` instead as suggested.

**Comment by zoechi** [comment]
Duplicate of #25108
