### ISSUE TITLE
Edit flutter_settings is not success. (I want to custom my android studio dir).

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#25149]
I have two android studio ,for some reason I want to keep them .  I need to use another Android Studio as an open tool in Android studio , not the one in the application.

I find it like to modify android studio dir config.
![图片](https://ws1.sinaimg.cn/large/844036b9ly1fy1qyu37rbj20um02cjrs.jpg)

So I edit the `~/.flutter_settings` file and add a android-studio-dir as json format.

![图片](https://ws1.sinaimg.cn/large/844036b9ly1fy1r0xxa79j20y80503z4.jpg)

and i run `flutter doctor -v` get it.
![image](https://user-images.githubusercontent.com/14145407/49721371-08a69500-fc9d-11e8-8102-f7f6b7b02102.png)

Is there any other way to modify this, or to make it easier to modify the lookup order so that configuration takes precedence over conventions?

----

flutter doctor -v
----
```
[✓] Flutter (Channel dev, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/cai/fluttersdk/flutter
    • Framework revision 5391447fae (10 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cai/Library/Android/sdk
    • Android NDK at /Users/cai/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```

**Comment by zoechi** [comment]
Sounds like you are looking for (` --android-studio-dir`)
```
 $ flutter config -h
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve Flutter tools over time. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Usage: flutter config [arguments]
-h, --help                      Print this usage information.
    --[no-]analytics            Enable or disable reporting anonymously tool usage statistics and crash reports.
    --clear-ios-signing-cert    Clear the saved development certificate choice used to sign apps for iOS device deployment.
    --gradle-dir                The gradle install directory.
    --android-sdk               The Android SDK directory.
    --android-studio-dir        The Android Studio install directory.

Run "flutter help" to see global options.

Settings:
  android-sdk: foo

Analytics reporting is currently enabled.
```

**Comment by CaiJingLong** [comment]
This method is more convenient to set up, but my problem has not been solved.
I mean, at present, it seems that customization has no precedence over default configuration in dart_tools processing.

![image](https://user-images.githubusercontent.com/14145407/49770683-8d86c280-fd20-11e8-8028-bd92ddaf3e76.png)
![image](https://user-images.githubusercontent.com/14145407/49770692-98415780-fd20-11e8-9f67-2b50e2480263.png)

**Comment by christopherfujino** [comment]
@CaiJingLong are you still experiencing this issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
