### ISSUE TITLE
Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.

### ISSUE THREAD

**Issue by Purlible** [flutter/flutter#25142]
```
I/flutter (10384): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10384): The following assertion was thrown while notifying listeners for AnimationController:
I/flutter (10384): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12:
I/flutter (10384): 'activity.isScrolling': is not true.
I/flutter (10384): 
I/flutter (10384): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10384): more information in this error message to help you determine and fix the underlying cause.
I/flutter (10384): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (10384):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (10384): 
I/flutter (10384): When the exception was thrown, this was the stack:
I/flutter (10384): #2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:670:12)
I/flutter (10384): #3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:222:9)
I/flutter (10384): #4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
I/flutter (10384): #5      DrivenScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:629:18)
I/flutter (10384): #6      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:124:19)
I/flutter (10384): #7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:697:5)
I/flutter (10384): #8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
I/flutter (10384): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (10384): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
I/flutter (10384): #11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
I/flutter (10384): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
I/flutter (10384): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
I/flutter (10384): #14     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter (10384): #15     _beginFrame (dart:ui/hooks.dart:138:3)
I/flutter (10384): (elided 2 frames from class _AssertionError)
I/flutter (10384): 
I/flutter (10384): The AnimationController notifying listeners was:
I/flutter (10384):   AnimationController#d3fe1(⏭ 1645.714; paused; DISPOSED; for DrivenScrollActivity)
I/flutter (10384): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
```

**Comment by Purlible** [comment]
The project was created in version 0.5.1 and iterated now. The main code(lib/main.dart) run on a new project  but does not exist. I wonder if it is caused by the version problem?

[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/……/Documents/flutter
    • Framework revision 5391447fae (12 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/……/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/……/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.1.3
    • Dart plugin version 182.5124

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.0

**Comment by zoechi** [comment]
We would need a minimal reproduction to be able to investigate.
Many things have changed since 0.5.1.

**Comment by zoechi** [comment]
Could you make any progress?

**Comment by CatEatFishs** [comment]
I have the same problem,how to solve this,

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/hongka-liming/Downloads/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hongka-liming/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • COR AL00 • 6EJ7N18526001222 • android-arm64 • Android 9 (API 28)

**Comment by biner88** [comment]
```
final controller = ScrollController();

  @override
  void initState() {
    super.initState();
    controller.addListener(onScroll);
  }

  onScroll() {
    setState(() {
     
    });
  }
@override
void dispose() {
  controller.removeListener(onScroll);
}
```

**Comment by insinfo** [comment]
I'm having this problem too


```dart
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:flutter_modular/flutter_modular.dart';
import 'package:riodasostrasapp/app/modules/jornal/components/jornal_widget.dart';
import 'package:riodasostrasapp/app/modules/jornal/jornal_controller.dart';

import 'package:riodasostrasapp/app/shared/enums/loading_state_enum.dart';
import 'package:riodasostrasapp/app/shared/theme/style.dart';

import '../../../shared/theme/style.dart';
import '../../../shared/models/jornal.dart';

class JornalPage extends StatefulWidget {
  @override
  _JornalPageState createState() => _JornalPageState();
}

class _JornalPageState extends ModularState<JornalPage, JornalController> {
  final _scrollController = ScrollController();
  ScrollController _nestedScrollViewController = ScrollController(); // To control scrolling
  final _scrollThreshold = 200; //200.0
  Size screenSize;

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(_onScroll);
  }

  _onScroll() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    screenSize = MediaQuery.of(context).size;
    return Scaffold(
      backgroundColor: scaffoldBackgroundColor,
      body: NestedScrollView(
        controller: _nestedScrollViewController,
        headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              backgroundColor: Colors.transparent,
              centerTitle: true,
              title: Text(
                'JORNAIS',
                style: appBarTitleTextStyle,
              ),
              floating: true, stretch: false,
              pinned: false,
              forceElevated: boxIsScrolled,
              expandedHeight: 80, elevation: 0, titleSpacing: 0,
              flexibleSpace: FlexibleSpaceBar(
                titlePadding: EdgeInsets.zero,
                centerTitle: false,
                title: Container(),
                background: Container(
                  alignment: Alignment.topCenter,
                  child: Container(
                    height: 100,
                    decoration: BoxDecoration(
                      color: Color(0xff2E363B),
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(30),
                        bottomRight: Radius.circular(30),
                      ),
                    ),
                  ),
                ),
              ),
              //snap: true,
            ),
          ];
        },
        //posts
        body: Observer(
          builder: (context) {
            if (controller.loadingState == LoadingState.error) {
              return Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Padding(
                    padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
                    child: Text('${controller.loadingState.value}'),
                  ),
                  RaisedButton(
                    onPressed: controller.getJornais(),
                    child: Text('Tentar Novamente?'),
                  ),
                ],
              );
            }
            if (controller.loadingState == LoadingState.success) {
              List<Jornal> list = controller.jornais;
              var jaFoi = false;
              return NotificationListener<OverscrollNotification>(
                onNotification: (OverscrollNotification scrollNotification) {
                  final maxScroll = scrollNotification.metrics.maxScrollExtent;
                  final currentScroll = scrollNotification.metrics.pixels;
                  if (maxScroll - currentScroll <= _scrollThreshold && jaFoi == false) {
                    controller.getJornaisNextPage();
                    jaFoi = true;
                  }
                  return true;
                },
                child: ListView.builder(
                  padding: EdgeInsets.zero,
                  itemBuilder: (BuildContext context, int index) {
                    return index >= list.length
                        ? BottomLoader()
                        : JornalWidget(
                            onTap: () {
                              Modular.to.pushNamed('/posts/detalhe', arguments: list[index]);
                            },
                            jornal: list[index]);
                  },
                  itemCount: controller.hasReachedMax ? list.length : list.length + 1,
                ),
              );
            }
            if (controller.loadingState == LoadingState.loading) {
              return Center(
                child: CircularProgressIndicator(),
              );
            }
            return Container();
          },
        ),
      ),
    );
  }

  @override
  void dispose() {
    _scrollController?.dispose();
    _nestedScrollViewController?.removeListener(_onScroll);
    _nestedScrollViewController?.dispose();
    super.dispose();
  }
}

class BottomLoader extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: Center(
        child: SizedBox(
          width: 33,
          height: 33,
          child: CircularProgressIndicator(
            strokeWidth: 1.5,
          ),
        ),
      ),
    );
  }
}

```

**Comment by insinfo** [comment]
Any solution ?

**Comment by omidraha** [comment]
I have the same issue.

**Comment by SmileJason** [comment]
> ```
> I/flutter (10384): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
> I/flutter (10384): The following assertion was thrown while notifying listeners for AnimationController:
> I/flutter (10384): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12:
> I/flutter (10384): 'activity.isScrolling': is not true.
> I/flutter (10384): 
> I/flutter (10384): Either the assertion indicates an error in the framework itself, or we should provide substantially
> I/flutter (10384): more information in this error message to help you determine and fix the underlying cause.
> I/flutter (10384): In either case, please report this assertion by filing a bug on GitHub:
> I/flutter (10384):   https://github.com/flutter/flutter/issues/new?template=BUG.md
> I/flutter (10384): 
> I/flutter (10384): When the exception was thrown, this was the stack:
> I/flutter (10384): #2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:670:12)
> I/flutter (10384): #3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:222:9)
> I/flutter (10384): #4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
> I/flutter (10384): #5      DrivenScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:629:18)
> I/flutter (10384): #6      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:124:19)
> I/flutter (10384): #7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:697:5)
> I/flutter (10384): #8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
> I/flutter (10384): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
> I/flutter (10384): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
> I/flutter (10384): #11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
> I/flutter (10384): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
> I/flutter (10384): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
> I/flutter (10384): #14     _invoke1 (dart:ui/hooks.dart:168:13)
> I/flutter (10384): #15     _beginFrame (dart:ui/hooks.dart:138:3)
> I/flutter (10384): (elided 2 frames from class _AssertionError)
> I/flutter (10384): 
> I/flutter (10384): The AnimationController notifying listeners was:
> I/flutter (10384):   AnimationController#d3fe1(⏭ 1645.714; paused; DISPOSED; for DrivenScrollActivity)
> I/flutter (10384): ════════════════════════════════════════════════════════════════════════════════════════════════════
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> I/flutter (10384): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 670 pos 12: 'activity.isScrolling': is not true.
> ```

I have the same issue.

**Comment by SmileJason** [comment]
> I have the same issue.

is it excute
