### ISSUE TITLE
DropDownButton is not customizable

### ISSUE THREAD

**Issue by therenca** [flutter/flutter#25151]
Hello guys,

How can we actively customize the DropDownButton. You find you cant change color of the dropdown icon, or its padding. There is no direct way to adjust space within or out of the DropDownButton widget, the only thing you can change is the text style, which is okay for most use cases, but you find if you want a finer control on the widget you have to murk around within the flutter source code. I find it does not directly adhere to the flutter design of other widgets...

I am thinking we should be able to change icon type as well as space between the dropdown text and the icon relatively easily as it is with the rest of the widgets

**Comment by taishi-h** [comment]
PR is out for review #25198

Would you be able to review this, please?

**Comment by aytunch** [comment]
To further add to this request, the Container that holds the DropDownItems list should be able to be customized as well. For instance when we customize the DropDownButton to have rounded corners, we would need the items List Container to have rounded corners as well in order to maintain the same look. So please whoever is elaborating, keep this in mind. To have different looks for DropDownButton in closed and opened states is a bad UI experience.

**Comment by mrRedSun** [comment]
Why is this closed? It seems like there still is no way to customize the style of the expanded list, for example.

**Comment by shihaohong** [comment]
Sorry, the PR description in #29572 caused the issue to close despite only addressing part of the problem. I'll reopen this.

**Comment by nmfisher** [comment]
Bumping this - any update on custom padding/border/etc?

**Comment by rpekarek-tc** [comment]
It would be great if we could also customize the orientation of the menu items so that we could consistently display the options above or below a DropDownButtonFormField

**Comment by gustav3d** [comment]
The enforced height of 48, is indeed very inconvenient. 
But this is a common problem in material widgets in Flutter.
They prevent configuration to differ from the material design size constraints.

Its one thing to have certain defaults.
Its not ok to prevent full customisations, it only makes people to copy pasting entire widgets and do the needed changes :(

**Comment by AhmedLSayed9** [comment]
[![Examples][1]][1]
[![DropdownButtonFormField2][2]][2]

I've created a custom `DropdownButton` from current version of Flutter's `DropdownButton` and made it more customizable. It's easy, simple and you can have steady dropdown menu below the button "As long as it's possible" and many other features described with the package. Also added the same functionality to `DropdownButtonFormField2` and added a feature of using the button as a popup menu button. I've tested it very well and it works like a charm!

You can use the package or use the source file on GitHub directly. Also, I've Added custom widget with the package you can customize default `DropdownButton2` widget for your entire app and use it with few lines as shown in the examples.

**Package:** [DropdownButton2][3]

**Repository (GitHub):** [DropdownButton2][4]


  [1]: https://i.stack.imgur.com/yw4gl.jpg
  [2]: https://i.stack.imgur.com/adoD0.jpg
  [3]: https://pub.dev/packages/dropdown_button2
  [4]: https://github.com/AhmedLSayed9/dropdown_button2

**Comment by ioantsaf** [comment]
`_kMenuItemPadding` in `dropdown.dart` is private, constant and has a value of `EdgeInsets.symmetric(horizontal: 16.0)`. It should be customizable, i.e. we should be able to have menu items without any horizontal padding, or set our own padding.

**Comment by Zarainia** [comment]
To add to this, currently you can change the `focusColor`, but not the text colour of the focused menu item, so if the `focusColor` is of a different brightness than the default menu background colour, the text is not readable when focused.

**Comment by rmahmadkhan** [comment]
In my use case, I want the space between value and trailer icon to be flexible.
For default, the dropdown button make that space according to the longest value in the list but I want it to be for selected value.

Any workaround this?

**Comment by gustav3d** [comment]
In most cases of all hardcoded widget limitations I end up making my own.
Either copy and change, or write something from scratch.

**Comment by rmahmadkhan** [comment]
Yeah, I also ended up making custom widget

**Comment by Piinks** [comment]
DropdownMenu is meant to replace DropdownButton, in the API docs there is a migration guide: https://api.flutter.dev/flutter/material/DropdownButton-class.html

If there are some properties that are not supported in the new widget, please file a new issue so we can take a look. Thank you!
