### ISSUE TITLE
Raster cache images may be much bigger than the visible/clipped area

### ISSUE THREAD

**Issue by d0bry** [flutter/flutter#25155]
The size of raster cache image is based only on drawing operations and may be unnecessarily big. This is particularly important for custom widgets with pinch-to-zoom functionality, where after zooming the painted area may be much bigger than the viewport. In my case it caused crashes (GPU memory issues?) on some devices. The only way to work around is to use _willChange_ hint to disable caching for such widget (even though it would benefit from caching).

I've found no way to limit the size to the clipped area.

Also, if this causes random issues, it is really hard to find the cause without using _checkerboardRasterCacheImages_. 

Example:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
      checkerboardRasterCacheImages: true,
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RepaintBoundary(
          child: Container(
            width: 100.0,
            height: 100.0,
            child: CustomPaint(
              painter: TestImagePainter(),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() {}),
        child: Icon(Icons.add),
      ),
    );
  }
}

class TestImagePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.clipRect(Offset.zero & size);
    for (int i = 0; i < 300; i++) {
      canvas.drawRect(Offset(10.0 * i, 10.0 * i) & Size(10.0, 10.0),
          Paint()..color = Colors.red);
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}
```

![screenshot_1544437474](https://user-images.githubusercontent.com/6552566/49726421-39bba100-fc6e-11e8-801e-4a31682a1d30.png)

**Comment by d0bry** [comment]
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.407],
    locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected device (2 available)

**Comment by pedromassangocode** [comment]
Hi @d0bry 
Are you still facing this issue? If yes, please provide your `flutter doctor -v`, your `flutter run --verbose`?
Thank you

**Comment by d0bry** [comment]
I forgot about this issue, but I just checked with the sample code above and it still exists in Flutter version 1.20.4.
Yet if no one else has complained in almost two years, then it's probably not that significant.

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
