### ISSUE TITLE
flutter analyze should support dartanalyzer's '--packages=' flag

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2515]
I've found a way to reduce our projects' analyze time in travis by over two minutes using that flag.  I might switch back to dartanalyzer until flutter analyze gets this flag.

**Comment by Hixie** [comment]
What would you put in the package resolution configuration file you want to point to?

**Comment by sethladd** [comment]
fyi @pq @bwilkerson @kevmoo for analyzer perf

**Comment by apwilson** [comment]
I put in all the projects that I'm analyzing dart files from.

**Comment by Hixie** [comment]
I don't understand. We use the --packages to provide our munged .packages file. What would it mean for the user to provide one?

**Comment by apwilson** [comment]
I do something similar for our project.  I have a .packages that lists all our packages.  I want to point flutter analyze to it.

**Comment by pq** [comment]
FYI @bwilkerson as this is another case where clients are getting heroic to set up analysis targets for the command-line analyzer.

**Comment by Hixie** [comment]
@apwilson do you include, like, the reflectables package and so on too?

How is the one you make different from the one flutter analyze makes for you when passed the same files?

**Comment by eseidelGoogle** [comment]
Is this still an issue @apwilson?  The analyzer team has been working on performance improvements which may have made this obsolete?

**Comment by Hixie** [comment]
This is WONTFIX for Flutter. The long-term plan is to make `flutter analyze` a trivial wrapper at which point we'll just pipe everything through. cc @danrubel
