### ISSUE TITLE
[WebView] Provide a way to load custom data into the WebView

### ISSUE THREAD

**Issue by e-adrien** [flutter/flutter#25162]
Hello,

I'am an Android developer.
I think it would be great if we can load custom string with base URL & scheme into the WebView, something like this method :
[WebView#loadDataWithBaseURL(String baseUrl, String data, String mimeType, String encoding, String historyUrl)](https://developer.android.com/reference/android/webkit/WebView#loadDataWithBaseURL(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String))

Thanks.

**Comment by e-adrien** [comment]
Thank you, but is "p: webview" not a better label than "p: maps" for this issue?

**Comment by zoechi** [comment]
@e-adrien thanks - fixed

**Comment by zoechi** [comment]
@e-adrien can you please elaborate more about concrete use cases?

You could do that by passing a data URL like shown in https://stackoverflow.com/questions/53831312/how-to-render-a-local-html-file-with-flutter-dart-webview
