### ISSUE TITLE
AboutListTile should provide a way to close the drawer

### ISSUE THREAD

**Issue by kjeremy** [flutter/flutter#25160]
Flutter recommends using an `AboutListTile` in drawers but the user cannot close the drawer. It would be nice if the `AboutListTile` provided a way to explicitly close the drawer.

**Comment by diegoveloper** [comment]
You can close the Drawer using a GlobalKey

**Comment by kjeremy** [comment]
I'm a little new to this. I can get the `GlobalKey` but I'm not sure where to make the `pop` call.

**Comment by diegoveloper** [comment]
well, I actually, I was wrong, you can open the drawer using GlobalKey, if you want to close the Drawer just call Navigation.pop:

https://flutter.io/docs/cookbook/design/drawer#4-close-the-drawer-programmatically

**Comment by diegoveloper** [comment]
If you check the source code of AboutListTile, this is just a StatelessWidget , so you can composite Widgets, add child , or wrap your AboutListTile with a GestureDetector and capture the tap Event , etc.

**Comment by zoechi** [comment]
This looks like a support request that should better be asked on StackOverflow.
Feel free to continue the discussion but I'm closing because I think there's nothing to do for the Flutter team.

**Comment by celesteking** [comment]
It's not a support request, it's a feature request. 
When you select an item in drawer, it is supposed to be closed.

AboutListTile doesn't support onTap callback and the suggestion in https://github.com/flutter/flutter/issues/25160#issuecomment-446653251 doesn't work. See https://dartpad.dev/f3322ab7c0e77d50693545ab6f2b3d4a . It doesn't fire.
