### ISSUE TITLE
Empty application after publishing it in iTunes Connect (Firebase related)

### ISSUE THREAD

**Issue by timbergus** [flutter/flutter#25167]
I'm pretty sorry for the lack of information, and I'm sure this is something I'm doing wrong, but I don't know where else I can ask. I have a pretty small application that shows a list of values from a static file. I uploaded it to iTunes Connect and downloaded it using TestFlight. Everything works just fine in my iPhone X.

I have modified the application to add a Firebase connection with a Firestore DDBB. If I run the application from Android Studio directly in my phone, it works, and it shows the data from the database. If I archive the app and upload it to iTunes Connect, and install it through TestFlight, when opening the application, it just appears as a white screen. The application works but shows nothing, but an empty white screen.

Do you know what is happening or how I can get information that can help to solve my problem?

Regards

**Comment by timbergus** [comment]
I've tried the full process. New project using Android Studio, install pods, update pods, clean, build, and archive. The app has been released for testing a couple of minutes ago, and I have download it using TestFlight. Same result. As white as ever. Weird thing is that the app is not crashing, but neither showing an empty result from Firebase. It shows no app at all.

**Comment by hartmannj** [comment]
Did you run `flutter build ios --release` before archiving?
Additionally, in the docs following is mentioned:

> To ensure that Xcode refreshes the release mode configuration, close and re-open your Xcode workspace. For Xcode 8.3 and later, this step is not required.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by timbergus** [comment]
Ok. This is my `flutter doctor -v`:

<img width="669" alt="screenshot 2018-12-11 09 44 10" src="https://user-images.githubusercontent.com/1750734/49788373-7a2c2500-fd29-11e8-9dd4-a7478b69767d.png">

And about `flutter build ios --release`, I was doing the process using only XCode, and building and archiving throw the XCode menu options.

This is the message after building:

<img width="454" alt="screenshot 2018-12-11 10 10 45" src="https://user-images.githubusercontent.com/1750734/49789799-21f72200-fd2d-11e8-98f3-775bfa0ba9d2.png">

This is the only message from XCode when archiving after `flutter build ios --release`:

<img width="889" alt="screenshot 2018-12-11 09 58 24" src="https://user-images.githubusercontent.com/1750734/49789092-64b7fa80-fd2b-11e8-86c1-df5e416adabf.png">

And this is the only different decision from Objective-C to Swift that I did during the process. I left it by default.

<img width="474" alt="screenshot 2018-12-11 09 57 41" src="https://user-images.githubusercontent.com/1750734/49789158-916c1200-fd2b-11e8-8e57-f521edf3c666.png">

And it's finally working 🎉It seems that the XCode process of __clean__, __build__ and __archive__ does not work properly. It is needed to run `flutter build ios --release`. Why is this? Could you tell me or point me to a reference where I can read about? I really want to understand the process.

It seems to work for the two apps I'm developing right now. Thanks.

**Comment by zoechi** [comment]
Might be related #24887

**Comment by timbergus** [comment]
Looks like. So for the moment, we should use the full command line process and only the XCode IDE to archive and publish?

**Comment by rcunning** [comment]
After banging my head against the same issue for a few hours, what seems to work every time is:
1. XCode Product -> Clean
2. `flutter build ios --release`
3. XCode Product -> Archive

One would think flutter could at least stop the archive with an error in one of its scripts in the case where you have not follow this undocumented procedure. Minimally, instructions at [https://flutter.io/docs/deployment/ios](url) really need to spell out that you must do the Clean step.
