### ISSUE TITLE
Listener leak when using Listenable.merge with an AnimationController

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#25163]
Example code looks something like this:

Widget:
```dart
final myAnimationController = AnimationController(...);

// in build: 
AnimatedBuilder(
  animation: Listenable.merge(
    <Listenable>[
      myAnimationController,
    ],
  ),
  builder: ... );
```

myAnimationController will get more and more listeners each time that AnimatedBuilder is added to the Widget tree and it will never go back down.

**Comment by Hixie** [comment]
Technically, `Listenable.merge` creates an object with a `dispose` method, but you're never calling it, so it's a bit like creating an `AnimationController` and never disposing of that.

**Comment by apwilson** [comment]
So this an issue in the implementation of Listenable.merge, right?  It needs to forward on dispose calls?

**Comment by apwilson** [comment]
So if I have multiple Listenables and I want to use a single AnimatedBuilder, what'st he proper procedure?  In the past I'd do the above witht he list of listenables merged but I see now that that's a really big problem.

**Comment by apwilson** [comment]
imo, I think the issue is that the implementation of the merged listenable isn't this:

``` dart
class Listenables extends Listenable {
  final List<Listenable> listenables;

  Listenables(this.listenables);

  @override
  void addListener(VoidCallback listener) {
    for (final listenable in listenables) {
      listenable.addListener(listener);
    }
  }

  @override
  void removeListener(VoidCallback listener) {
    for (final listenable in listenables) {
      listenable.removeListener(listener);
    }
  }
}
```

WHat do you think about changing it to this?

**Comment by Hixie** [comment]
I didn't realise, but `Listenable.merge` doesn't expose its `dispose` method. That makes it much more serious. I think we should reimplement it in terms of forwarding like the above.
