### ISSUE TITLE
[docs] firebase_messaging ios install guide remove step 4) Remove the use_frameworks! line from ios/Podfile

### ISSUE THREAD

**Issue by danwulff** [flutter/flutter#25172]
Since #9694 has been closed. The docs should be updated to remove step 4 of the iOS Integration section of the firebase_messaging readme (causes confusion).
> Remove the use_frameworks! line from ios/Podfile (workaround for flutter/flutter#9694).

Direct link to the README: https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/README.md

**Comment by cremor** [comment]
Fixed by flutter/plugins#1532

**Comment by kroikie** [comment]
@danwulff

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/550. Any further collaboration will be done there.
