### ISSUE TITLE
Odd behavior with resizeToAvoidBottomPadding and AlertDialog.

### ISSUE THREAD

**Issue by pranjalsatija** [flutter/flutter#25174]
## Steps to Reproduce
Show an `AlertDialog` in a `Scaffold` with `resizeToAvoidBottomPadding` left to its default value of `true`. I tried to reproduce it in a small sample for this issue, but I was unable to. This issue is present in a side project I'm working on, which is on GitHub [here](https://github.com/pranjalsatija/splitty_flutter). I'm 99% sure that this is happening because I have a scaffold nested within another. Within the linked project, there's one scaffold that sets up a bottom navigation bar, and its body is set to another scaffold that contains an app bar and an actual body. The outer scaffold's body is changed depending on which tab is selected. Here's a relevant snippet that shows how the scaffolds are structured:
```dart
// _tabs contains instances of `BottomNavigationBarScreen`, which is an interface that defines the `bottomNavigationBarItem(BuildContext context)` function.
// That function returns a `BottomNavigationBarItem` to represent each screen.

return Scaffold(
  bottomNavigationBar: BottomNavigationBar(
    currentIndex: _selectedIndex,
    onTap: _updateSelectedIndex,
    items: _tabs.map((s) => s.bottomNavigationBarItem(context)).toList(),
  ),
  body: _tabs[_selectedIndex],
);
```

You can take a look at [`lib/screens/main_tab`](https://github.com/pranjalsatija/splitty_flutter/blob/master/lib/screens/main_tab.dart) to see more.

Here's a snippet that shows how the alert is being presented:
```dart
showDialog(
  context: context,
  builder: (BuildContext context) {
    return AlertDialog(
      title: Text(Strings.of(context).addPersonPrompt),
      content: TextField(
        autofocus: true,
        decoration: InputDecoration(
          isDense: true,
          labelText: Strings.of(context).personName,
        ),
        onChanged: (value) => textFieldContents = value,
        onSubmitted: (_) => Navigator.pop(context, textFieldContents),
        textCapitalization: TextCapitalization.words,
      ),
      actions: <Widget>[
        FlatButton(
          onPressed: () => Navigator.pop(context, textFieldContents),
          child: Text(Strings.of(context).done),
        ),
      ],
    );
  },
);
```

And finally, here's a screenshot:
![simulator screen shot - iphone xr - 2018-12-10 at 16 54 51](https://user-images.githubusercontent.com/6324573/49766944-54a50a00-fc9c-11e8-9a3c-80c343a52cfe.png)

## Logs
`flutter run --verbose` and `flutter analyze` don't report any errors. Here's some of the output from `flutter doctor -v`:
```
pranjal:splitty $ flutter doctor -v
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-US)
    • Flutter version 1.0.0 at /Users/pranjal/flutter
    • Framework revision 5391447fae (11 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

## Workaround
For now, I've been able to fix this by setting `resizeToAvoidBottomPadding` to `false` on the inner scaffold, but that doesn't actually stop the scaffold from resizing to avoid bottom padding. It just makes it work the way it should:
![simulator screen shot - iphone xr - 2018-12-10 at 16 56 41](https://user-images.githubusercontent.com/6324573/49767031-96ce4b80-fc9c-11e8-8dea-bb49bfb9f1d7.png)

I think the fix to this is to add a check within `Scaffold` to ensure that it doesn't account for bottom padding more than once, just in case scaffolds are nested.

**Comment by pranjalsatija** [comment]
Also, if the fix here is for me to restructure my widget tree to avoid nesting scaffolds, could someone give me some insight on what they would do here to try and build something similar?

**Comment by zoechi** [comment]
> avoid nesting scaffolds

Right.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
