### ISSUE TITLE
There is some error in the Wiki doc "Add Flutter to existing apps”

### ISSUE THREAD

**Issue by liuxp988** [flutter/flutter#25185]
When i add Flutter to existing apps, the second step

```
$ cd .android/
$ ./gradlew flutter:assembleDebug
```

When I run this command, there is no flutter.so & flutter_assets in .aar file. And the main project will be crashed with no .so or "VM snapshot must be valid”.
I must run this command to compile the Flutter resources:

```
$ cd .android/
$ ./gradlew app:assembleDebug
```

And these command must be excuted before i run the main project. If I just run the main project’s run command, the Flutter resource will not be compiled or updated. If you do the clean command before you run the main project, the main project will be crashed with no .so or "VM snapshot must be valid”, too.
![image](https://user-images.githubusercontent.com/35795440/49775105-f7f42e80-fd31-11e8-878f-8826273f4458.png)

**Comment by SolveBugs** [comment]
me too! I have faced the err "VM snapshot must be valid",can you tell me how to solve this problem?

**Comment by Paulo988** [comment]
> me too! I have faced the err "VM snapshot must be valid",can you tell me how to solve this problem?

you `must` do these commands `before` you run the main project `every time`:
```
$ cd .android/
$ ./gradlew app:assembleDebug
```
I think there is missing some build options when you run your main project directly. Hope the official solutions!

**Comment by SolveBugs** [comment]
@Paulo988  thanks a lot.
i don`t use the .arr file,so i have`t run the comman "./gradlew app:assembleDebug",
but when i run my host android project, i found my host apk 
not have the flutter_assets floder,i  really do not what happens.

**Comment by Paulo988** [comment]
> @Paulo988 thanks a lot.
> i don`t use the .arr file,so i have`t run the comman "./gradlew app:assembleDebug",
> but when i run my host android project, i found my host apk
> not have the flutter_assets floder,i really do not what happens.

No matter what method you use, you `have to` compile it first in `.android`. Then you can run your host android project

**Comment by SolveBugs** [comment]
@Paulo988  Thank you very much again,I will have a try later on.

**Comment by SolveBugs** [comment]
@Paulo988 unfortunately，i still faced the error "VM snapshot must be valid."
First ,i cd .android and i haved runed the command `./gradlew app:assembleDebug`,and the i run my host android project,when i add a flutterview on my activity,the err "VM snapshot must be valid" still occurred。

**Comment by xster** [comment]
Flutter tools has a proper `flutter build aar` command now https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#1-depend-on-the-android-archive-aar so I'm closing this.
