### ISSUE TITLE
Unable To Install Flutter on Linux

### ISSUE THREAD

**Issue by labermt** [flutter/flutter#25191]
## Steps to Reproduce

Visit:

Using Android Studio on Linux

Perform the codelab steps in:

https://flutter.io/docs/get-started/codelab

Write your first Flutter app, part 1 

Plug in phone with USB cable.

Add Additional Arguments to Configuration:

```
--release --no-track-widget-creation flags
```
(This step was suggested due to another bug).

Got confusing message:
```
Target file "flags" not found.
```

## Logs

```
```

```
bessermt@bessermt-Latitude-E6440 ~ $ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /opt/flutter
    • Framework revision 5391447fae (11 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/bessermt/Android/Sdk
    • Android NDK at /home/bessermt/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • ONEPLUS A5000             • 31acfaea      • android-arm64 • Android 8.1.0
      (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API
      28) (emulator)

• No issues found!
bessermt@bessermt-Latitude-E6440 ~ $ 
```

**Comment by zoechi** [comment]
> Target file "flags" not found.

Can you please post the full console output.

**Comment by labermt** [comment]
Cut and pasted right from the console:

**Target file "flags" not found.**

**Comment by labermt** [comment]
Yes, that was all that was there. I did install into /opt/flutter since that's one of the two suggested locations according to the Android Studio install rules. I followed the suggested fix for that which was to make myself both owner and group for permissions. 

The suggestion of tar xf ~/Downloads/flutter_linux_v1.0.--stable.tar.xz isn't a good suggestion. Besides, the instructions don't actually say to extract there, it says "Extract the file in the desired location, for example:"... I don't have a development folder and my dev folder is only temporary. My install is for multiple users and so I chose the most standard way I could find. 

I don't see any path for the file "flags", so I'm extra confused.

**Comment by labermt** [comment]
Thanks. I think it should install like Android Studio as root, but for now the workaround seems to be making yourself the owner and group. BTW, tar isn't good for installs since my understanding is that it was designed to be a backup utility and therefore keeps the user id of the original owner. This user won't be on the install computer, so it defaulted to the id of 1024. Hope that helps.

**Comment by jonahwilliams** [comment]
The original issue for which this was filled is a confusing command in the code lab, which has since been fixed. In general, we need better installation instructions for our users but that is out of the scope of this bug
