### ISSUE TITLE
EReader app

### ISSUE THREAD

**Issue by felagund18** [flutter/flutter#25192]
Hello,
I am new to Flutter and I have no idea how to implement reading app.
Is it possible to implement something like this below?
![screen shot 2018-12-11 at 3 22 41 pm](https://user-images.githubusercontent.com/1384327/49784718-33562380-fd59-11e8-8698-b1644bf5432f.png)

I am using markdown as a book content. It converted from markdown -> html -> Widgets tree

Please please guide me through this.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
