### ISSUE TITLE
How to change CupertinoNavgationBar height?

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25190]
Hi, I wanna ask how to change the CupertinoNavBar height, I can not find any params to set this, BTW, I have a custom view in the middle of navbar, if I changed the height , how to make it align vertical middle?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by xster** [comment]
We're mostly producing cupertino widgets to follow Apple's UI guidelines. You cannot change the height of a UIKit navigation.
