### ISSUE TITLE
Path is missing a bunch of features one would expect

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#252]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 18:53 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1920_

----

Looking at existing Skia features in particular:
- [x] FillType
- [x] moveTo()
- [x] relativeMoveTo()
- [x] lineTo()
- [x] relativeLineTo()
- [x] quadraticBezierTo()
- [x] relativeQuadrativeBezierTo()
- [x] cubicBezierTo()
- [x] relativeCubicBezierTo()
- [x] conicSectionTo()
- [x] relativeConicSectionTo()
- [x] arcTo()
- [x] addRect()
- [x] addOval()
- [x] addArc()
- [x] addRoundedRect()
- [x] addPolygon() (see also issue https://github.com/flutter/engine/issues/85)
- [x] addPath() as extension of existing path
- [x] addPath() as new subpath
- [x] close the path
- [x] reset the path
- [x] create a path by offsetting another path
- [x] create a path by transforming another path

**Comment by abarth** [comment]
Progress in https://github.com/flutter/engine/pull/2146
