### ISSUE TITLE
is there a way to call plugin method from native code? 

### ISSUE THREAD

**Issue by ahmadmarafa** [flutter/flutter#25206]
while i was working with flutter i came across a situation that i want to access flutter plugin from my native code 
example 

> i set SharedPreferences using flutter code  and i want to access this
> prefs from java

i achieved that by reading plugin source code and get SharedPreferences name and how the plugin store keys and every thing worked as expected , but i wonder if there easier way that i can use ?

**Comment by zoechi** [comment]
Duplicate of #21925
