### ISSUE TITLE
fatal error: lipo: can't open input file:

### ISSUE THREAD

**Issue by chenparty** [flutter/flutter#25200]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

Logs:
![image](https://user-images.githubusercontent.com/16755257/49791650-e760aa00-fd6b-11e8-93d2-6e8a9d05fe62.png)
![image](https://user-images.githubusercontent.com/16755257/49791766-16771b80-fd6c-11e8-9551-318ed045b90e.png)

**Comment by zoechi** [comment]
Try running `pod install` in the `ios` directory and `flutter clean` in the project root directory.

**Comment by zoechi** [comment]
Is this a new project or a project you created with an older Flutter version?

**Comment by chenparty** [comment]
@zoechi The Flutter version was 0.9.6 or 0.10.0 when i created the project on 26 Oct.

**Comment by chenparty** [comment]
@zoechi I created a new project with flutter 1.0.0, ran migrated from the old project .
ran Xcode built success, and installed success, but launched failed without any error.
I feel confused.
![image](https://user-images.githubusercontent.com/16755257/49849192-65c45700-fe13-11e8-83fd-11c8052eb838.png)
