### ISSUE TITLE
MyLocation button doesn't work in google_maps_flutter/example/ios

### ISSUE THREAD

**Issue by admarwick** [flutter/flutter#25212]
Pressing the My Location button on the map shown in the 'User Interface' section of the example app on IOS does nothing, in that the map does not pan to my location. This is on a physical iPhone 5S. On Android this works fine.

As an experiment I modified the example by implementing the method -didTapMyLocationButtonForMapView in GoogleMapController.m, but the method was never called.

For comparison, the example app of the old map_view plugin does not suffer from this problem on IOS. The relevant code there seems to be essentially the same, so I'm not sure what is going on.

### Steps to Reproduce

1. Clone google_maps_flutter/example
2. Add map key to ios/Runner/AppDelegate.m
3. flutter run, with or without --release

### Flutter Doctor
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-US)
    • Flutter version 1.0.0 at /Users/alan/Documents/util/flutter
    • Framework revision 5391447fae (11 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/alan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/alan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio 3.2.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio 3.1.4.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Alan’s iPhone 5S • fb2c341f9cecedf031922c7a9f3977426a476bf6 • ios • iOS 12.1.1
    • iPhone XR        • 49782121-BDF3-4314-A844-E4EE5686DA29     • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by gimox** [comment]
+1

**Comment by darioxtx** [comment]
+1

**Comment by zoechi** [comment]
@gimox @darioxtx "me too" and "+1" comments are pointless. 
Instead use ![image](https://user-images.githubusercontent.com/405837/49718793-716d1d80-fc5b-11e8-8a7a-7288f578a66d.png) on the initial comment to upvote and increase priority.
Comments cause spammy notification mails sent to all subscribers.
If you want to get notified, use ![image](https://user-images.githubusercontent.com/405837/49718838-95306380-fc5b-11e8-8900-0d9173289cc8.png)

**Comment by timtraversy** [comment]
I believe this is related: https://github.com/flutter/flutter/issues/24207. Problems with gesture recognition within platform views prevent the location button tap from being recognized.

**Comment by DCrow** [comment]
I guess the main culprit for this issue and #24207 is #24076. 
As some of my apps gestures don't work when using `UiKitView`, but they do work when I use a native view(which is not integrated into flutter)

Sure hope it is fixed soon, since it makes native UI libraries useless...

**Comment by DCrow** [comment]
Should be fixed now

**Comment by amirh** [comment]
Yes, engine was rolled with the fix, this is now fixed in master, closing this issue.

**Comment by genjm** [comment]
Sorry if this is a stupid question, but this is still broken for me & I am running the latest version of google_maps_flutter & I've also upgraded my version of flutter to the latest release.

Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (9 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Should this be fixed, or do I need to wait for it to be added to the current release before it will work?

Thanks.

**Comment by zoechi** [comment]
@genjm 
```
Framework • revision 5391447 (9 weeks ago)
```
```
flutter channel master
flutter doctor -v
```

**Comment by zoechi** [comment]
@genjm `master` is not intended to be used for every-day work (prefer `stable` or `dev` instead) but it gets the latest changes first.
