### ISSUE TITLE
ImageProvider.resolve can throw synchronously 

### ISSUE THREAD

**Issue by aabdagic** [flutter/flutter#25227]
`instantiateImageCodec` from `dart:ui` returns a `Future` that doesn't conform to the `Future` contract as it's implemented using a `Completer<T>.sync`.

As a result of this, `ImageProvider.resolve` can end up throwing synchronously instead of invoking the `ImageErrorListener` of the `ImageStreamCompleter`. I suspect this happens because `_loadAsync` is an `async` function, which attempts to `await` on a `Future` from `instantiateImageCodec`.

From the `Completer<T>.sync` docs:

> For that reason, a synchronous completion must only occur at the very end (in "tail position") of another synchronous event [...]

`_loadAsync` is not a "synchronous event", so completing the "weird" future from `instantiateImageCodec` breaks the `async-await` contract, and instead propages the exception synchronously into the `_loadAsync` caller which is the `resolve`

This happens in cases when e.g. `Network.image` caches malformed binary data, in which case synchronous instantiation of the `Codec` ends up failing the `resolve` caller with an exception.

**Comment by jonahwilliams** [comment]
Presumibly this was safe before the sync async changes, we'll need to update this code

**Comment by jonahwilliams** [comment]
@aabdagic how were you using the ImageProvider that you were able to get a sync exception? I cannot reproduce using MemoryImage with malformed data

**Comment by aabdagic** [comment]
I used a Network.image that got cached, then shown again.

**Comment by jonahwilliams** [comment]
From internal discussion, it sounds like the cause of the bug is more complicated than the originally filled issue. I'll leave this open for tracking

See also: https://github.com/dart-lang/sdk/issues/35442

cc @zanderso

**Comment by mehmetf** [comment]
Customer feels very nervous about releasing with this issue open so adding blocker. We need to get to the bottom of this and recommend a solution.
