### ISSUE TITLE
i18n icelandic causes build issues

### ISSUE THREAD

**Issue by gardyna** [flutter/flutter#25223]
adding Icelandic to internationalization creates the class "is" in i18n.dart which conflicts with a reserved keyword an causes any build to fail. I suggest changing it to isl (if possible) to avoid name conflicts or making some "default addition" to class names in i18n like and underscore or "lang_" to avoid future name confilct in i18n.

**Comment by zoechi** [comment]
Where does the `i18n.dart` file come from? What method of adding i18n are you referring to?

**Comment by gardyna** [comment]
When opening the project in android studio on mac I was prompted whether I wanted to add internationalization to the project. I clicked "yes" which added "res/values/strings_en.arb" and "lib/generated/i18n.dart" and get the suggestion to extract string resource. That wizard also allows me to add languages/regions. after finding Icelandic and adding it "res/values/strings_is.arb" appears along with additional code in i18n.dart (which causes the error)

attached is image of the wizard. I was under the assumption that this was an official addition to the dev-kit
![image](https://user-images.githubusercontent.com/5694968/49819751-1b3ccf00-fd6e-11e8-90da-59546440993b.png)

**Comment by zoechi** [comment]
@gardyna thanks for the update. I never used this assistant and wasn't aware of this feature.

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #2945](https://github.com/flutter/flutter-intellij/issues/2945) via [**ZenHub**](https://www.zenhub.com/)
