### ISSUE TITLE
How to return to native code from flutter library

### ISSUE THREAD

**Issue by Arthur-Kamau** [flutter/flutter#25235]
based on [this article](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) it is easy to intergrate flutter to my android app,but it did not describe how to return to android from flutter code

**Comment by bthjonte** [comment]
This is no issue, The flutter.io has perfect examples of how to pass data to and from native functions and get return values . https://flutter.io/docs/development/platform-integration/platform-channels

**Comment by Arthur-Kamau** [comment]
its not about communicating between flutter and native code,rather returning to native code from my android code from my flutter code/view which was loaded as a library in my android project and the flutter page loaded into  a flutter view.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by cbracken** [comment]
Unfortunately we're not able to do support for individual questions on our issue tracker, but the good news is that asking on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) is likely to get answers quickly. The community support scales really well, and several Flutter committers keep an eye out for questions when they've got time as well. 

In any case where you encounter a reproducible bug, I'd encourage you to do a quick search of our issues, and add a thumbs-up to relevant issues or file a new one with repro steps if no one else has yet filed it.

In this case it sounds like what you _might_ want is either to author a plugin [these are some examples](https://github.com/flutter/plugins), or [dart:ffi](https://flutter.dev/docs/development/platform-integration/c-interop).
