### ISSUE TITLE
Provide a knob to control the budgeted GPU mem for Skia

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#25244]
Right now, max resource cache for Skia is defaulted to 512M which is too much for some apps/embedders. We should provide an engine flag for this. https://github.com/flutter/engine/blob/2f706bea076d75abc19090c8971c57f6db2f0025/shell/gpu/gpu_surface_gl.cc#L34

**Comment by mehmetf** [comment]
This is a release blocker as it is causing memory allocation problems for customer: dream.

**Comment by eseidelGoogle** [comment]
Fuchsia hit this too, just worked around it by changing C++ for now.  @chinmaygarde

**Comment by Hixie** [comment]
Proposal:

`window.graphicsCacheMemoryLimit` (exposing the memory aspect of `getResourceCacheLimits` and `setResourceCacheLimits`)
`window.graphicsCacheMemoryUsage` (exposing the memory aspect of `getResourceCacheUsage`)

**Comment by Hixie** [comment]
@jason-simmons points out this has to be async since it's on a different thread, so disregard proposal above.

**Comment by Hixie** [comment]
@jason-simmons will add documentation to the relevant channel property on SystemChannels on the Dart side.
