### ISSUE TITLE
The "History of Everything" app does not run well on my BlackBerry Priv

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#25245]
The "History of Everything" app does not run well on my BlackBerry Priv.  The animations aren't in stable locations as I scroll through the timeline, as shown in the following video.

https://photos.app.goo.gl/s4QUuSYGo2xfwvnZ9

(Also feel free to come by my desk to see it in person.)

I don't know if there's a performance issue on the Flutter side, if there's something the app is doing incorrectly, or if there's some animation curve that's being miscomputed somehow.

**Comment by byshy** [comment]
I don't guess this is device specific, it does this on my pixel 2 emulator as well as my galaxy a7 2016

**Comment by byshy** [comment]
I don't think this is device specific, it does this on my pixel 2 emulator as well as my galaxy a7 2016

**Comment by markusaksli-nc** [comment]
Hi @jamesderlin 
This no longer seeems to be an issue for me on the latest version of the app with my SM G950F.
Is this issue still relevant?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
