### ISSUE TITLE
Why 'Dart_NotifyLowMemory' was not called when memory warning

### ISSUE THREAD

**Issue by sundayman** [flutter/flutter#25247]
## Steps to Reproduce

1. It's easier get OOM after Flutter Add to exists App 
2. I found there is a API call 'Dart_NotifyLowMemory' , why not call it when memory warning
3. Any other way to avoid OOM ?
thanks

## Logs

```
```

```
```

```
```

**Comment by rickyazhari** [comment]
i have same issue about low memory either. actually i dont really know, is it low memory makes my app force close in ios. But i hope  there is notify about low memory

**Comment by zoechi** [comment]
Looks like a dup of #15479 and/or #3006

**Comment by dnfield** [comment]
Fixed by https://github.com/flutter/engine/pull/14517

**Comment by dnfield** [comment]
We now call Dart_NotifyLowMemory, but see https://github.com/flutter/flutter/issues/6500 for the broader issue.
