### ISSUE TITLE
Program work on android and iOS simulator but crashed on real android

### ISSUE THREAD

**Issue by hjlp20150803** [flutter/flutter#25254]
## Steps to Reproduce

1.I follow the guidance (https://flutter.io/docs/deployment/android) to build the release, and download to android phones(one android5.1, one android9),install and run, it flash and exit.
2. I used the channel and third part package (.aar),that need the permission read and write storage. 
3. I have no idea how to trace the bug, how and where,I need some log? any suggestion for me to start the work is appreciated. 

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Try to reduce the code to track down what causes the issue or
try with a new project and add stuff until you can reproduce.

**Comment by hjlp20150803** [comment]
longxhb:vanilla longxhb$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/longxhb/flutter
    • Framework revision 5391447fae (12 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/longxhb/Library/Android/sdk
    • Android NDK at /Users/longxhb/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/longxhb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by zoechi** [comment]
Do you get any related output if you run `flutter logs` in a terminal window before you run the app?

**Comment by hjlp20150803** [comment]
longxhb:vanilla longxhb$ flutter logs
Showing Android SDK built for x86 logs:
longxhb:vanilla longxhb$ flutter logs
Showing Android SDK built for x86 logs:
longxhb:vanilla longxhb$

**Comment by zoechi** [comment]
Unfortunately that's not enough information.

**Comment by hjlp20150803** [comment]
Yes, I should try something from easy and simple, any new will be reported here.

**Comment by zoechi** [comment]
Is this about adding Flutter to an existing Android app?

**Comment by hjlp20150803** [comment]
Right now, I basically believe the crash  caused by the .aar file, it put into the android/app/libs, yes it added into flutter/android/app/libs. The .aar  can build with 4 types(arm,arm64,386,amd386), vary on different android phone(android5.1,android9.0 on hand). I am still working on, sure thing is, almost none of  the combinations work for my project, I need to deep into the .aar.

**Comment by hjlp20150803** [comment]
Problem solved, .aar should be matched with real platform. I tried from simple, cause the simulator used in 386 and target with arm, not work on simulator but work on real phone, there are lots of combinations, I made a list, test one by one.All the tools need to be upgraded to latest. Thanks zoechi.
