### ISSUE TITLE
Hero animation not working with Navigator.pushNamed

### ISSUE THREAD

**Issue by ZhennanWu** [flutter/flutter#25261]
The Hero animation won't work when navigating using PageRouteBuilder+Navigator.pushNamed

# Demo Code
The following demo code wraps FAB in a hero widget
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final initialPath = '/';

  @override
  Widget build(BuildContext context) => MaterialApp(
      home: Navigator(
          initialRoute: initialPath,
          onGenerateRoute: (path) => PageRouteBuilder(
              pageBuilder: (context, _, __) => Scaffold(
                    appBar: AppBar(title: Text('test'),),
                    floatingActionButton: Hero(
                      tag: 'fab',
                      child: FloatingActionButton(onPressed: () {
                        Navigator.of(context).pushNamed('/new');
                      }),
                    ),
                  ),
            transitionsBuilder: (context, animation, secondaryAnimation, child) =>
                SlideTransition(
                  position: Tween<Offset>(
                    begin: Offset(1.0, 0),
                    end: Offset.zero,
                  ).animate(animation),
                  child: SlideTransition(
                    position: Tween<Offset>(
                      begin: Offset.zero,
                      end: Offset(-1.0, 0),
                    ).animate(secondaryAnimation),
                    child: child,
                  ),
                ),
            transitionDuration: Duration(seconds: 1)
          )
      )
  );
}
```

# Screenshot
The FAB performs no hero animation
![untitled](https://user-images.githubusercontent.com/38578020/49859529-b1d2c400-fe32-11e8-862f-82946486399f.gif)

# Edit
It turns out this is not the case. It seems that any Navigator other than the default navigator provided by `MaterialApp` fails to perform hero animation. Following code performs Hero animation well with a `Navigator.push()` + `MaterialPageRoute`, but if you uncomment the custom navigator, the hero animation cease to exist.
```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: HomePage()));

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
//    return Navigator(
//        onGenerateRoute: (path) =>
//            PageRouteBuilder(pageBuilder: (context, _, __) {
              return Scaffold(
                appBar: AppBar(title: Text('test')),
                floatingActionButton: Hero(
                  tag: 'fab',
                  child: FloatingActionButton(onPressed: () {
                    Navigator.push(context,
                        MaterialPageRoute(
                          builder: (context) => Scaffold(
                                appBar: AppBar(title: Text('test2'),),
                                floatingActionButton: Hero(
                                    tag: 'fab',
                                    child: FloatingActionButton(onPressed: null)),
                              ),
                        ));
                  }),
                ),
              );
//            }));
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ZhennanWu** [comment]
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.345], locale zh-CN)
    • Flutter version 1.0.0 at D:\Toolkits\flutter
    • Framework revision 5391447fae (12 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Program Files\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Program Files\Android\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

**Comment by ZhennanWu** [comment]
I have located the cause of this issue after thoroughly reading your docs
It appears Navigator needs to add a HeroController as an observer
[HeroController](https://docs.flutter.io/flutter/widgets/HeroController-class.html)

**Comment by moeiscool** [comment]
could you please elaborate? i've read the docs but never really understand :(

**Comment by abdullah432** [comment]
Did you find the solution?

**Comment by kkizlaitis** [comment]
In your `Navigator` widget, add `HeroController` to the `observers`. Like this:
```
Navigator(
  initialRoute: ...,
  onGenerateRoute: ...,
  observers: [
    HeroController(),
  ],
)
```

This solved non-working `Hero` animations, at least for me.

**Comment by rafid08** [comment]
But how can I implement Navigator.push() with this one?

**Comment by omidraha** [comment]
When I add `HeroController()` to `navigatorObservers` of `MaterialApp` as:

```dart
    final heroController = HeroController();
    return MaterialApp(
      navigatorObservers: [heroController],
...
)
```
It only works in back and pop and not works on `  Navigator.of(context).pushNamed`.
