### ISSUE TITLE
Flutter.framework in release build contains x86_64 architecture

### ISSUE THREAD

**Issue by tkYan** [flutter/flutter#25260]
When I archive my iOS application and upload to iTunes Connect.
An error occured as follow:
<img width="638" alt="2018-12-12 4 48 31" src="https://user-images.githubusercontent.com/9733923/49858802-e47bbd00-fe30-11e8-98c3-f099093b3cb0.png">

It seems Flutter.framework is copied from bin/cache/artifacts/engine/ios-release.
And Follow is Flutter.framework lipo info. 
You may notice it contains x86_64 architecture.
 I suppose it should be removed.

```
lipo -info Flutter 
Architectures in the fat file: Flutter are: x86_64 armv7 arm64
```
### Logs

```
flutter doctor --verbose
[✓] Flutter (Channel master, v1.0.1-pre.15, on Mac OS X 10.14.1 18B75, locale
    zh-Hans-CN)
    • Flutter version 1.0.1-pre.15 at
      /Users/yapeng/Desktop/work/JYWork/Flutter/flutter
    • Framework revision b023a57483 (25 hours ago), 2018-12-11 00:16:43 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/yapeng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[!] VS Code (version 1.29.1)
    • VS Code at /Users/yapeng/Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 6s • 7C4FBFFE-735A-4C06-96FC-58EE06E1FAA7 • ios • iOS 12.1
      (simulator)
    • iPhone XR • F97D51C5-B281-402B-A9BD-6D1C65C63A6A • ios • iOS 12.1
      (simulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Please try running `flutter build ios --release` first and then check again.

**Comment by tkYan** [comment]
I might be wrong. 
But After running `flutter build ios --release`, I still find Flutter.framework contains x86_64.
I have checked the framework under .ios/Flutter/engine/Flutter.framework.
Is this dirctory correct, or there is another Flutter.framework exist.

**Comment by tkYan** [comment]
By the way, I don't import Flutter with cocoapods, but as embed binary.

**Comment by goderbauer** [comment]
The xcode project that's generated with `flutter create` contains a Build Phase step to thin the frameworks to only include the architectures you're building for: https://github.com/flutter/flutter/blob/028087d0fc7aecf859614f841e2583d00c795269/packages/flutter_tools/templates/module/ios/host_app_ephemeral/Runner.xcodeproj.tmpl/project.pbxproj.tmpl#L201-L214

Did you accidentally remove that "Build Phase" step in your xcode project?

**Comment by tkYan** [comment]
And running `flutter build ios --release` does not help. You can see the image below:
<img width="591" alt="2018-12-13 9 35 43" src="https://user-images.githubusercontent.com/9733923/49909673-d1153400-feba-11e8-868a-7c962737dc6f.png">
I still find Flutter.framework under ".ios/Flutter/engine/" contains x86_64. 
Should I pick the framework somewhere else?

**Comment by goderbauer** [comment]
After you do a `flutter build ios --release` the file in `build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter` is properly thinned:

```
$ lipo -info build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
Architectures in the fat file: Flutter are: armv7 arm64 
```

This seems to be working as expected. Maybe I don't understand what you issue is?

**Comment by tkYan** [comment]
This solved my problem. Thanks!

**Comment by jue13** [comment]
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
