### ISSUE TITLE
I am unable to create a new app on flutter

### ISSUE THREAD

**Issue by DeepaVPanicker** [flutter/flutter#25270]
1. I have Android studio as well as flutter installed on my system
2. When I run `flutter create myapp` or create a new flutter application in Android Studio, I get the following error

## Logs

```flutter --verbose create mynewapp
[  +32 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic
@{u}
[ +233 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +174 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[   +1 ms] executing: [C:\src\flutter\] git ls-remote --get-url origin
[ +171 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%H
[ +176 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +1 ms] executing: [C:\src\flutter\] git log -n 1 --pretty=format:%ar
[ +175 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +2 ms] 12 days ago
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.*
--first-parent --long --tags
[ +177 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +2 ms] v1.0.0-0-g5391447fa
[ +574 ms] Creating project mynewapp...
[  +41 ms]   mynewapp\.gitignore (created)
[  +26 ms]   mynewapp\.idea\libraries\Dart_SDK.xml (created)
[  +23 ms] "flutter create" took 397ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sender itself crashed: HandshakeException: Connection terminated
during handshake
#0      IOClient.send (package:http/src/io_client.dart:33:23)
<asynchronous suspension>
#1      CrashReportSender.sendReport
(package:flutter_tools/src/crash_reporting.dart:118:56)
<asynchronous suspension>
#2      _handleToolError (package:flutter_tools/runner.dart:114:40)
#3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)#4      _handleToolError (package:flutter_tools/runner.dart:70:29)
#5      run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
#6      _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#7      _rootRunBinary (dart:async/zone.dart:1144:38)
#8      _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#9      _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#10     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#11     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#12     Future._completeError (dart:async/future_impl.dart:494:5)
#13     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#14     _Completer.completeError (dart:async/future_impl.dart:27:5)
#15     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#16     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart)
#17     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#18     _rootRunBinary (dart:async/zone.dart:1144:38)
#19     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#20     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#21     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#22     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#23     Future._completeError (dart:async/future_impl.dart:494:5)
#24     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#25     _Completer.completeError (dart:async/future_impl.dart:27:5)
#26     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#27     AppContext.run (package:flutter_tools/src/base/context.dart)
#28     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#29     _rootRunBinary (dart:async/zone.dart:1144:38)
#30     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#31     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#32     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#33     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#34     Future._completeError (dart:async/future_impl.dart:494:5)
#35     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#36     _Completer.completeError (dart:async/future_impl.dart:27:5)
#37     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#38     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart)
#39     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#40     _rootRunBinary (dart:async/zone.dart:1144:38)
#41     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#42     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#43     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#44     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#45     Future._completeError (dart:async/future_impl.dart:494:5)
#46     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#47     _Completer.completeError (dart:async/future_impl.dart:27:5)
#48     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#49     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart)
#50     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#51     _rootRunBinary (dart:async/zone.dart:1144:38)
#52     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#53     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#54     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#55     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#56     Future._completeError (dart:async/future_impl.dart:494:5)
#57     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#58     _Completer.completeError (dart:async/future_impl.dart:27:5)
#59     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#60     CommandRunner.runCommand (package:args/command_runner.dart)
#61     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#62     _rootRunBinary (dart:async/zone.dart:1144:38)
#63     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#64     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#65     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#66     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#67     Future._completeError (dart:async/future_impl.dart:494:5)
#68     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#69     _Completer.completeError (dart:async/future_impl.dart:27:5)
#70     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#71     AppContext.run (package:flutter_tools/src/base/context.dart)
#72     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#73     _rootRunBinary (dart:async/zone.dart:1144:38)
#74     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#75     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#76     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#77     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#78     Future._completeError (dart:async/future_impl.dart:494:5)
#79     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#80     _Completer.completeError (dart:async/future_impl.dart:27:5)
#81     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#82     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart)
#83     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#84     _rootRunBinary (dart:async/zone.dart:1144:38)
#85     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#86     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#87     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#88     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#89     Future._completeError (dart:async/future_impl.dart:494:5)
#90     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#91     _Completer.completeError (dart:async/future_impl.dart:27:5)
#92     _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#93     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart)
#94     _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#95     _rootRunBinary (dart:async/zone.dart:1144:38)
#96     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#97     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#98     Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#99     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#100    Future._completeError (dart:async/future_impl.dart:494:5)
#101    _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#102    _Completer.completeError (dart:async/future_impl.dart:27:5)
#103    _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#104    FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart)
#105    _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#106    _rootRunBinary (dart:async/zone.dart:1144:38)
#107    _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#108    _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#109    Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#110    Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#111    Future._completeError (dart:async/future_impl.dart:494:5)
#112    _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#113    _Completer.completeError (dart:async/future_impl.dart:27:5)
#114    _AsyncAwaitCompleter.completeError
(dart:async/runtime/libasync_patch.dart:40:18)
#115    CreateCommand.runCommand
(package:flutter_tools/src/commands/create.dart)
#116    _asyncErrorWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:84:45)
#117    _rootRunBinary (dart:async/zone.dart:1144:38)
#118    _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#119    _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#120    Future._propagateToListeners.handleError
(dart:async/future_impl.dart:654:47)
#121    Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#122    Future._completeError (dart:async/future_impl.dart:494:5)
#123    _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#124    _Completer.completeError (dart:async/future_impl.dart:27:5)
#125    _AsyncAwaitCompleter.completeError.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:43:20)
#126    _rootRun (dart:async/zone.dart:1124:13)
#127    _CustomZone.run (dart:async/zone.dart:1021:19)
#128    _CustomZone.bindCallback.<anonymous closure>
(dart:async/zone.dart:947:23)
#129    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#130    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#131    _runPendingImmediateCallback
(dart:isolate/runtime/libisolate_patch.dart:115:13)
#132    _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.14393], locale en-IN)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (12 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Deepa663180\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Deepa663180\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin installed
    • Dart plugin installed
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 32-bit edition (version 1.24.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

[flutter_01.log](https://github.com/flutter/flutter/files/2671753/flutter_01.log)


```

**Comment by davidmartos96** [comment]
Does it work the app creation if you do `flutter create myapp` in the console instead of creating it from Android Studio?

**Comment by DeepaVPanicker** [comment]
> Does it work the app creation if you do `flutter create myapp` in the console instead of creating it from Android Studio?

Nope. It throws the same error

**Comment by zoechi** [comment]
Does your user have write permissions in the Flutter install directory (`C:\src\flutter\`)?

**Comment by zoechi** [comment]
Are you behind a proxy?

**Comment by Bwolfnoob** [comment]
Did u install the last Android SDK 28(Pie)? Cuz i have this issue in the beginer and when i do this the flutter works cool '-'

**Comment by DeepaVPanicker** [comment]
> Does your user have write permissions in the Flutter install directory (`C:\src\flutter\`)?

I tried running the same command in another directory, The files and folders are getting created, but 'flutter packages get' is throwing error
Creating project D:\hellpaa...
  D:\hellpaa\.gitignore (created)
  D:\hellpaa\.idea\libraries\Dart_SDK.xml (created)
  D:\hellpaa\.idea\libraries\Flutter_for_Android.xml (created)
  D:\hellpaa\.idea\libraries\KotlinJavaRuntime.xml (created)
  D:\hellpaa\.idea\modules.xml (created)
  D:\hellpaa\.idea\runConfigurations\main_dart.xml (created)
  D:\hellpaa\.idea\workspace.xml (created)
  D:\hellpaa\.metadata (created)
  D:\hellpaa\android\app\build.gradle (created)
  D:\hellpaa\android\app\src\main\java\com\example\hellpaa\MainActivity.java (created)
  D:\hellpaa\android\build.gradle (created)
  D:\hellpaa\android\hellpaa_android.iml (created)
  D:\hellpaa\android\app\src\main\AndroidManifest.xml (created)
  D:\hellpaa\android\app\src\main\res\drawable\launch_background.xml (created)
  D:\hellpaa\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  D:\hellpaa\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  D:\hellpaa\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  D:\hellpaa\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  D:\hellpaa\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  D:\hellpaa\android\app\src\main\res\values\styles.xml (created)
  D:\hellpaa\android\gradle\wrapper\gradle-wrapper.properties (created)
  D:\hellpaa\android\gradle.properties (created)
  D:\hellpaa\android\settings.gradle (created)
  D:\hellpaa\ios\Runner\AppDelegate.h (created)
  D:\hellpaa\ios\Runner\AppDelegate.m (created)
  D:\hellpaa\ios\Runner\main.m (created)
  D:\hellpaa\ios\Runner.xcodeproj\project.pbxproj (created)
  D:\hellpaa\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  D:\hellpaa\ios\Flutter\AppFrameworkInfo.plist (created)
  D:\hellpaa\ios\Flutter\Debug.xcconfig (created)
  D:\hellpaa\ios\Flutter\Release.xcconfig (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  D:\hellpaa\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  D:\hellpaa\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  D:\hellpaa\ios\Runner\Base.lproj\Main.storyboard (created)
  D:\hellpaa\ios\Runner\Info.plist (created)
  D:\hellpaa\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  D:\hellpaa\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  D:\hellpaa\lib\main.dart (created)
  D:\hellpaa\hellpaa.iml (created)
  D:\hellpaa\pubspec.yaml (created)
  D:\hellpaa\README.md (created)
  D:\hellpaa\test\widget_test.dart (created)
Running "flutter packages get" in hellpaa...
Got TLS error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second...
Got TLS error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 2 in 2 seconds...

**Comment by DeepaVPanicker** [comment]
> Did u install the last Android SDK 28(Pie)? Cuz i have this issue in the beginer and when i do this the flutter works cool '-'

Yes. I've the latest Android SDK installed

**Comment by DeepaVPanicker** [comment]
> Are you behind a proxy?

Yes

**Comment by zoechi** [comment]
Looks like a 
Duplicate of #16505

**Comment by DeepaVPanicker** [comment]
> Looks like a
> Duplicate of #16505

My network was behind a proxy. when i tried to create the app without the proxy, the app was created. But i'm facing gradle error while running the app.

C:\Users\Deepa663180\myaphh>flutter run
Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                       1.5s
Resolving dependencies...                                    4.1s
Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
> Could not resolve com.android.tools.build:aapt2:3.2.1-4818971.
  Required by:
      project :app
   > Could not resolve com.android.tools.build:aapt2:3.2.1-4818971.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.2.1-4818971/aapt2-3.2.1-4818971.pom'.
            > Connect to dl.google.com:443 [dl.google.com/172.217.166.174] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
Gradle task 'assembleDebug'... Done                         47.9s
Gradle task assembleDebug failed with exit code 1

**Comment by zoechi** [comment]
You can configure a proxy for Flutter/Pub.

Did you create the app with the proxy enabled?

Could be https://stackoverflow.com/questions/49228261/how-to-disable-proxy-for-flutter

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/22470#issuecomment-428049724 seems also to point to Gradle proxy settings https://github.com/flutter/flutter/issues/22470#issuecomment-431797533

**Comment by DeepaVPanicker** [comment]
Thank you! It worked

**Comment by osunkoyadavid** [comment]
when i run flutter create app in the flutter console, it gives me an error like "Cannot create a project within the Flutter SDK. Target directory 'C:\Users\Tola.Osunkoya\Desktop\flutter_windows_v1.0.0-stable\flutter\packages\flutter_tools\app' is
within the Flutter SDK at 'C:\Users\Tola.Osunkoya\Desktop\flutter_windows_v1.0.0-stable\flutter'." 
and i have downloaded sdk in android studio

**Comment by osunkoyadavid** [comment]
Please i am fed up. please reply on time

**Comment by osunkoyadavid** [comment]
if you guys are not careful, i will stop and quit using flutter

**Comment by davidmartos96** [comment]
@osunkoyadavid Consider reading this https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

Also, I think the error message is somewhat descriptive on what is happening.

**Comment by osunkoyadavid** [comment]
So sorry for September 2 20199 message. I ran out of control.  The thing is i was eager to use flutter. I will control myself. I am a beginner in flutter seriously. Just seeing message in forum

**Comment by osunkoyadavid** [comment]
Also tried react didn't work. I'm eager to learn how to program on flutter. very sorry. Please accept my apologies. didn't know what i was doing. i was fed up. Please don't mind my usage of capital letters
