### ISSUE TITLE
about development plugin

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#25278]
I would like to ask, when writing the plugin, I can't get the flutter package in the native. So I introduced libs. Is it necessary to delete the libs and dependencies when I finally submit?

Android plug-in project is not introduced to the flutter library, so there will be an error prompt, I create a libs folder in the project root directory, used to store the flutter library

![image](https://user-images.githubusercontent.com/15923901/49879638-553ccc80-fe65-11e8-905c-c29dcb3aa061.png)
![image](https://user-images.githubusercontent.com/15923901/49879841-cc726080-fe65-11e8-88f5-0b268deabbf3.png)

Should I delete these?
I found that deleting these still works fine.

**Comment by zoechi** [comment]
> I can't get the flutter package in the native.

What does this mean?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by lizhuoyuan** [comment]
when I create flutter-plugin project , 
![image](https://user-images.githubusercontent.com/15923901/49880598-73a3c780-fe67-11e8-90ac-4a54ec95aa75.png)

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/53746559/when-i-create-a-flutter-plugin-project-i-cant-find-flutter is a better place for this question.
