### ISSUE TITLE
CircleAvatar animates on release launch iOS

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#25281]
Hi there,

I found a bug where a CircleAvatar animates to size when you launch it on iOS with `flutter run ios --release`

This commit shows the behavior.

https://github.com/lukepighetti/flutter-developers/commit/0d7b7d251e3edd19b4624f282fe0e59b9260cb4a

This commit fixes the behavior.

https://github.com/lukepighetti/flutter-developers/commit/41a04a4ced21019952b08f51b5aa5604bc48682c

Cheers

**Comment by lukepighetti** [comment]
```
[✓] Flutter (Channel dev, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.0.0 at .................
    • Framework revision 5391447fae (13 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

I haven't been able to reproduce this in an MCVE unfortunately, but I have a before and after in the two commits above. So if you find yourself needing to investigate in the future I hope it will be helpful.

Cheers

**Comment by TahaTesser** [comment]
Hi @lukepighetti 
Are you still experiencing  this issue on latest version of Flutter?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
