### ISSUE TITLE
Firestore plugin [0.8.2+1] online mode only does not work

### ISSUE THREAD

**Issue by diegolaballos** [flutter/flutter#25284]
I want to get results only from the server and not from the cache.

Apparently this setting should do what I want : 
`Firestore.instance.settings(persistenceEnabled: false)`

but I'm still getting results from queries when I turn airplane mode ON, at least for iOS (didn't test yet on Android).

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by ozomer** [comment]
I'm also cannot disable the "persistence". It is weird to see partial results when the device is offline - I want my users to see some "ProgressIndicator" if the information is not synced with the db.

**Comment by ozomer** [comment]
Hmmm.. it could be useful to handle `hasPendingWrites` and `isFromCache` from [here](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/lib/src/snapshot_metadata.dart). When any of them is true (i.e. data is not synced) we could handle the state as if `hasData` is false.
Apparently you need to configure `includeDocumentMetadataChanges` in some `QueryListenOptions`\`DocumentListenOptions`.
I hope [this issue](https://github.com/flutter/flutter/issues/16434) will not be a problem.

**Comment by kroikie** [comment]
@diegolaballos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/548. Any further collaboration will be done there.
