### ISSUE TITLE
Flutter PlatformView on iOS

### ISSUE THREAD

**Issue by yjoo9317** [flutter/flutter#25290]
I've found the usage of platform view for Android from [here.](https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6)

But I haven't found the one for iOS.
Do you have any plan to publish such tutorial for iOS or I am just missing it totally?

If I am missing it, then please let me where I should go.

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/tree/master/examples/platform_view might help

**Comment by xster** [comment]
See https://docs.flutter.io/flutter/widgets/UiKitView-class.html

**Comment by snntaylan** [comment]
I've found the usage of platform view for Android from lots of article.

But I haven't found to working code for the one for iOS with swift.
Do you have any plan to publish such tutorial for iOS with swift or I am just missing it totally?

If I am missing it, then please let me where I should go.
