### ISSUE TITLE
 Android toolchain - develop for Android devices (Android SDK 28.0.1)     X Android license status unknown.

### ISSUE THREAD

**Issue by mani4utech** [flutter/flutter#25297]
```
 Android toolchain - develop for Android devices (Android SDK 28.0.1)
    X Android license status unknown.
```
i'm getting this error message on running 'flutter doctor' command.
kindly help me out to fix this.

**Comment by mani4utech** [comment]
[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at C:\Users\23sma\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

https://stackoverflow.com/questions/49758849/flutter-io-android-license-status-unknown

**Comment by inversionesinformaticas** [comment]
Ni mierda respondieron!

**Comment by collinsbigomba** [comment]
Help plz
