### ISSUE TITLE
FirebaseAuth onAuthStateChanged not called after linkWithGoogleCredential succeeded

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter#25292]
Hi

it seems that `FirebaseAuth` `onAuthStateChanged` is not called after `linkWithGoogleCredential` succeeded.

I guess that's because the user is still the same and only its changing from anonymous to linked.

I still feel that `onAuthStateChanged` should be called, otherwise the program logic becomes really messy and newbies will fall into this trap all the time causing frustration and support requests.

## Logs

```yaml
  # Firebase
  firebase_auth: ^0.6.6
  firebase_core: ^0.2.5+1
  firebase_dynamic_links: ^0.1.0+1
  cloud_firestore: ^0.8.2+3

  # Social login providers
  flutter_facebook_login: ^1.1.1
  google_sign_in: ^3.2.4
```

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.407], locale en-NZ)
    • Flutter version 1.0.0 at C:\Users\b\git\flutter
    • Framework revision 5391447fae (12 days ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\b\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\b\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3
    • Flutter plugin version 19.1
    • Dart plugin version 173.3727.108

[√] Connected device (1 available)
    • Nexus 6P • ENU7N15A27004986 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

```gradle
buildscript {
    ext.kotlin_version = '1.3.11'
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
        maven {
            url 'https://dl.bintray.com/android/android-tools'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0' // Google Services plugin
    }
}
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by BerndWessels** [comment]
@zoechi This is pretty much it to repoduce the issue.

Ideally you would call `signInWithGoogle()` in a button click handler, but I think this is already enough to reproduce the problem.

```dart
final FirebaseAuth _auth = FirebaseAuth.instance;

void main() async {
  _auth.onAuthStateChanged.listen((FirebaseUser user) {
    ///////// notice that this is not called after linkWithGoogleCredential succeeded
    print(user);
  });

  await signInWithGoogle();

  runApp(MainPage());
}

signInWithGoogle() async {
  GoogleSignInAuthentication googleAuth;
  try {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    googleAuth = await googleUser.authentication;
    final FirebaseUser user = await _auth.linkWithGoogleCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
  } catch (err) {
    print(err);
  }
}

```

**Comment by dotdoom** [comment]
Looks like a dup of #25250. There's a workaround posted.

**Comment by dotdoom** [comment]
I find this confusing as well. In our app we had to implement this in a layer of abstraction.

This is not a problem with Flutter however. The behavior you observe is documented in [Firebase](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.AuthStateListener).

> This method gets invoked in the UI thread on changes in the authentication state:
> * Right after the listener has been registered
> * When a user is signed in
> * When the current user is signed out
> * When the current user changes

**Comment by mkhennoussi** [comment]
I am using a StreamBuilder with onAuthStateChanged as a stream. I also have this issue, onAuthStateChanged seems not to be always called after the authentication state is changed. Sometimes yes, sometimes no.

**Comment by eliezedeck** [comment]
This bug blew up on me. I never expected for that callback to not be fired! :-/

**Comment by JimmyRobz** [comment]
It seems like if I try to listen to the stream "too soon", nothing happens! When I wait 2 or 3 seconds and then start listening to the stream, everything is ok. Didn't have time to investigate why this happens.

**Comment by sudame** [comment]
same issue occurred when I try to sign in with `signInWithCredential` method.
(But I have no confidence in my code...... :( )

**Comment by Aljulanda9** [comment]
I have the same issue too. This is how I start my listener in the first widget of the app.
`  Widget build(BuildContext context) {
    return StreamBuilder<FirebaseUser>(
      stream: FirebaseAuth.instance.onAuthStateChanged,
      builder: (BuildContext context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return  SplashScreen();
        } else {
          if (snapshot.hasData) {
            return MainPage();
          }
          return WelcomePage();
        }
      }
    );
  }
`

I do get 
`D/FirebaseAuth(10648): Notifying id token listeners about a sign-out event.
D/FirebaseAuth(10648): Notifying auth state listeners about a sign-out event.
`

When I call the signOut method

**Comment by Jer0** [comment]
Until a while ago, I had the same problem as you, when I entered with a user and towards logout, the streambuilder did not work correctly, however, if I restarted the application after the logout and tried to log in, it worked, then I deduced that it was something of the SingOut

I have a page with the logout button

"myaccount.dart"
`Future signout() async {
    await Provider.of<Auth>(context).logout();
  }

  _logout() {
    signout();
    Navigator.of(context).pop();
  }`

This calls a function of the Provider to close the user's session

"provider/auth.dart"
`Future<void> logout() async {
    await storage.deleteAll();
    await FirebaseAuth.instance.signOut();
    await GoogleSignIn().signOut();
    // GoogleSignIn().disconnect(); <-- If you want to close the session completely and give the user the option to select another account
  }`

"Main.dart"

`home: StreamBuilder<FirebaseUser>(
              stream: FirebaseAuth.instance.onAuthStateChanged,
              builder: (BuildContext context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return new SplashScreen();
                } else {
                  if (snapshot.hasData) {
                    return MyHomePage(1);
                  }
                  return AuthScreen();
                }
              }),`

I hope it helps, if anyone has any questions, ask me =)

**Comment by dshukertjr** [comment]
Having the same issue. onAuthStateChanged is not being called after linking other authentication provider to an anonymous account.

**Comment by kroikie** [comment]
@BerndWessels

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/547. Any further collaboration will be done there.

**Comment by sutkarsh-s** [comment]
> I have the same issue too. This is how I start my listener in the first widget of the app.
> 
> ```
> Widget build(BuildContext context) {
>     return StreamBuilder<FirebaseUser>(
>       stream: FirebaseAuth.instance.onAuthStateChanged,
>       builder: (BuildContext context, snapshot) {
>         if (snapshot.connectionState == ConnectionState.waiting) {
>           return  SplashScreen();
>         } else {
>           if (snapshot.hasData) {
>             return MainPage();
>           }
>           return WelcomePage();
>         }
>       }
>     );
>   }
> ```
> 
> I do get
> `D/FirebaseAuth(10648): Notifying id token listeners about a sign-out event. D/FirebaseAuth(10648): Notifying auth state listeners about a sign-out event. `
> 
> When I call the signOut method

did u got the soln for signOut.....if yes please let me know the solution
