### ISSUE TITLE
Potential issue in flutter_attach_test.dart

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#25304]
flutter_attach_test.dart adds errors to stdout, not stderr, which could lead to a failure to catch an error.

https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flutter_attach_test.dart#L50

**Comment by timsneath** [comment]
@jonahwilliams Should this issue be retitled to focus on 'method not found'? Or is this fixed (and can be closed) now?

**Comment by markusaksli-nc** [comment]
Closing this as the original issue was addressed in the merged PR and I cannot find any stdout for "Method not found", or any open issues regarding that. Please open a new issue to track it if it still persists.
