### ISSUE TITLE
Image editing/manipulation (Adding Text, fliters to image) 

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#25315]
Hi, I want to know is it possible to edit images like **`rotating, Added fliter, adding texts over image, cropping, mirroring of image etc..`**
Are there any plugins or examples to learn/seek from!

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

- https://stackoverflow.com/questions/44665720/how-do-i-crop-an-image-in-flutter/44668386#44668386
- https://stackoverflow.com/questions/52253848/how-to-set-a-backdropfilter-using-dynamic-sized-widgets-in-flutter

You can always reach out to native libraries if you need features that are not (yet) available in Flutter directly.

https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages

**Comment by truongsinh** [comment]
@zoechi can we reopen this ticket and have the tag "good for plugin" instead?

**Comment by Joshua56** [comment]
I need that plugin i have a look at it it seems awesome and i would like to use the same

**Comment by Matzu89** [comment]
@zoechi please reopen!

**Comment by Joshua56** [comment]
Send me a link of the same

**Comment by isojtouano** [comment]
> Are there any updates on this?

**Comment by Jaimin-1998** [comment]
> Hi, I want to know is it possible to edit images like **`rotating, Added fliter, adding texts over image, cropping, mirroring of image etc..`**
> Are there any plugins or examples to learn/seek from!

> Is this possible or not?
