### ISSUE TITLE
Could not get cmap table size, while loading Iocons

### ISSUE THREAD

**Issue by Shoaibkhan786** [flutter/flutter#25319]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
Duplicate of #23645

**Comment by Shoaibkhan786** [comment]
> Duplicate of #23645

What was the solution because I did not get it?

**Comment by zoechi** [comment]
It's just the same issue as already reported. 
#23645 is still open.

**Comment by Shoaibkhan786** [comment]
Any idea why is it happening? I tried a lot to figure out the issues.

**Comment by ManuelWandeto** [comment]
I was getting the same problem when doing;
Icon(
                  Icons.add_alarm,
                  color: Colors.green,
                ),

after running 'flutter clean' on the root of the project folder i don't get this issue anymore,

**Comment by rajyadavnp** [comment]
Finally, I fixed my issue.
My asset names had spaces in their names. Renaming it by removing white spaces solved the problem

**Comment by kwent** [comment]
If your app rely on the use of default material fonts and your commented out `uses-material-design` in your `pubspec.yaml` then the app will crash. Solution is to set `uses-material-design: true` in `pubspec.yaml`
