### ISSUE TITLE
[WebView] Allow the webview to take control when a URL is about to be loaded

### ISSUE THREAD

**Issue by e-adrien** [flutter/flutter#25329]
Hello,

I think it would be great if we can take control on URL loading in the WebView.
I think about this method for the Android WebView :
[WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView, java.lang.String)](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String))

Thanks.

**Comment by amirh** [comment]
This has came up as a blocker for customer: dream.

Ideally we would delegate the decision to the Dart code, on iOS this seems to be do-able as [[WKNavigationDelegate webView:decidePolicyForNavigationAction:decisionHandler:]](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455641-webview?language=objc) provides a decision callback (so we can wait for the an async response from Dart).
On Android, [shouldOverrideUrlLoading](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String)), expect a synchronous response, the documentation does say that the "method is called on a thread other than the UI thread", need to figure out whether it is ok to block that thread.

**Comment by amirh** [comment]
On Android the need to make a decision synchronously on `shouldOverrideUrlLoading` complicates things a bit. `shouldOverrideUrlLoading` is called on the platform thread, if we block it then we won't get any following platform message as they are delivered by posting tasks to the platform thread task runner.

The workaround I'm going to try is to always return true in `shouldOverrideUrlLoading`, and allow the Dart code to followup with a `loadUrl` for the same URL.

I prototyped this and verified that a following `loadUrl` works properly including updating the location history. My gut feeling is that there may be other issues I'm missing where but didn't bump into any yet so I'm going to move forward with this approach. If someone thinks of a problem I'm overlooking please let me know.

The backup plan which I'd really prefer to avoid would be for the Dart side to pass a blacklist of URLs to override.

**Comment by amirh** [comment]
I checked with the Android WebView team regarding the following documentation note:

> Note: Do not call WebView.loadUrl(String) with the request's URL and then return true. This unnecessarily cancels the current load and starts a new load with the same URL. The correct way to continue loading a given URL is to simply return false, without calling WebView.loadUrl(String).

That note is referring to invoking loadUrl from within shouldOverideUrlLoading, we are not currently aware of a performance penalty for the suggested workaround. The one caveat we might have to live with is that it will trade "renderer-initated" navigations with "browser-initiated" navigations.

**Comment by amirh** [comment]
On Android we can currently only let navigationDelegates block navigations that are targeted to the main frame.

On Android API levels that are smaller than 24, the [shouldOverrideUrlLoading](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)) version that includes the information on whether the navigation is targeted to the main frame is not available.

According to the statistics in Android Studio, if we make the plugin require API 24 we lose 62.6% of users, so we probably don't want to go there.

This leaves us with 2 options:

#### On API levels < 24, Treat all navigations as targeted to the main frame
This will mean that prior to API 24 web pages with iframes/frames will just be broken: the iframe will immediately load in the main frame.

#### Only support navigation delegates starting API 24
We can either make them a no-op prior to API 24, or invoke them and crash/warn if the delegate asked to prevent the navigation.

*Would love to hear feedback of the preferred approach: specifically were you planning to block navigation from pages that use frames/iframes ?*

**Comment by amirh** [comment]
Turns out the compatibility library supports this and is available on most L+ devices.
I'm going to always make navigation delegates work, in rare cases where the device is using a webview version older than 67, it will still work, but pages with frames won't work.

So to hit the problem you will need to:
  1. Be on an Android devices with a webview version before 67.
  2. Have a navigation delegate set for your Flutter webview.
  3. Load a page with frames/iframes.

**Comment by amirh** [comment]
Landed with https://github.com/flutter/plugins/pull/1236 and https://github.com/flutter/plugins/pull/1323

Published with webview_flutter 0.3.4

**Comment by pedrosalesmiranda** [comment]
Hi there, i would like to know if there is a way to detect on the webview a post and get request in the same URL. At the moment I was using **NavigationRequest** request
and then **request.url.startsWith**('https://something').
But I need to catch only the post in this url.
Any ideas would be great.
Cheers
