### ISSUE TITLE
How to load the documents in Android using Flutter packages

### ISSUE THREAD

**Issue by smanojarun** [flutter/flutter#25327]
I’m developing the Flutter application to load the documents from other sources and cloud.

I have used “flutter_webview_plugin” for that and it’s working on iOS to view all the documents. But android is not supporting for view the documents using webview.

Is flutter has any package for load the documents such as .doc, .pdf, .ppt, .xls in the Android.

Please advise your thoughts. Thanks in advance.

**Comment by zoechi** [comment]
Flutter has no native support for these formats.
You can make native functionality available by building a plugin https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
