### ISSUE TITLE
list.forEach ignore return value

### ISSUE THREAD

**Issue by fady94** [flutter/flutter#25330]
I want to loop in forEach list to return value in json code

this is my code 
it continues to loop without stopping
```dart
if(offerCategories['id'] == 10){
        var a = offerCategories['productsOrOffers'];
        print(a);
        final parsed = a.cast<Map<String, dynamic>>();
        return parsed.map<Offer>((json) => Offer.fromJson(json)).toList();
      } 
```

**Comment by zoechi** [comment]
The code you posted doesn't contain `forEach`
https://api.dartlang.org/stable/2.1.0/dart-core/Iterable/forEach.html does have return type `void` so there is no return value to expect.

What you want is probably https://api.dartlang.org/stable/2.1.0/dart-core/Iterable/map.html

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
