### ISSUE TITLE
Plugin: Sensors

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2533]
We provide a sensors service, but there's no example of how to use it.

**Comment by mit-mit** [comment]
@abarth do we still have a sensors service? I don't see it in searches, or when looking in [`/src/services`](https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/services).

**Comment by sethladd** [comment]
I think we should close this issue. We don't have a sensors service, AFAICT.

We might want to open a new issue for a plugin for Accelerometer.

**Comment by sethladd** [comment]
Thanks!

**Comment by mit-mit** [comment]
Fixed in https://github.com/flutter/plugins/pull/121
