### ISSUE TITLE
Flutter google maps traffic layer

### ISSUE THREAD

**Issue by methmal59** [flutter/flutter#25334]
Why isn't the traffic layer of google maps plugin isn't installed yet? or am I missing something? I can't seem to find it, I mean it's a basic thing in a google map. Please consider about this

**Comment by darren-f5s** [comment]
Any update to the implementation of this?

**Comment by iskakaushik** [comment]
This should be addressed by flutter/plugins#1767

**Comment by solnsumei** [comment]
Is there a way or option to set the z-index for the traffic layer on google map flutter to show behind a polyline drawn instead of being overlayed over all polylines on android. On IOS it is perfect.
