### ISSUE TITLE
How do I animate a route on push but not animate it on pop?

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#25338]
Spawned from https://github.com/flutter/flutter/issues/24945

One of our customers have a use case where they want to push a route (with animation) and then return a value from this route via pop. However, they don't want the route to animate in reverse when popped.

**Comment by HansMuller** [comment]
A custom route can override its `buildTransitions` method and ignore requests to animate in reverse. For example:
```
  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation, Widget child) {
    final PageTransitionsTheme theme = Theme.of(context).pageTransitionsTheme;
    Animation<double> onlyForwardAnimation;
    switch (animation.status) {
      case AnimationStatus.reverse:
      case AnimationStatus.dismissed:
        onlyForwardAnimation = kAlwaysCompleteAnimation;
        break;
      case AnimationStatus.forward:
      case AnimationStatus.completed:
        onlyForwardAnimation = animation;
        break;
    }
    return theme.buildTransitions<T>(this, context, onlyForwardAnimation, secondaryAnimation, child);
  }
```

Here's a complete example app:
https://gist.github.com/HansMuller/dbcbec1962dd8d810279bad2f1fd8c3b

**Comment by mehmetf** [comment]
Nothing else to be done here.

**Comment by nt4f04uNd** [comment]
@HansMuller this creates a delay though and blocks user inputs, because the `transitionDuration` is still the same. How do we workaround that? In my case I have to disable the animation without blocking the UI when uses Telegram-like swipe to dismiss the route.
