### ISSUE TITLE
flutter_tool needs to use target platform to retrieve all artifacts

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#25343]
Internal: b/121220354

Fuchsia has different dart/kernel artifacts than iOS and Android. To ensure that we always use the correct platform dill, patched sdk, and more we need to pipe the targetPlatform through all requests for the current artifact.

**Comment by jonahwilliams** [comment]
To do so, we can make the targetPlatform argument of the Artifacts class required and update all locations. In places where the platform doesn't matter we can default to `targetPlatform: TargetPlatform.tester`

**Comment by keertip** [comment]
Thanks Jonah! This feels like the right approach.

**Comment by tvolkert** [comment]
Jonah, what's the visible effect of this not being done?

**Comment by jonahwilliams** [comment]
there is an additional flag in the internal blaze rules
