### ISSUE TITLE
Trouble setting example for my own flutter plugin in pub.dartlang.org

### ISSUE THREAD

**Issue by ahguerra93** [flutter/flutter#25340]
In the example tab it shows the README.md inside the example folder.

![screenshot from 2018-12-13 17-53-49](https://user-images.githubusercontent.com/45803597/49969989-61c23300-ff00-11e8-80df-25b3e2e43d9e.png)

How should I redirect it to my main.dart? 

Thanks in advance! loving Flutter so much.

**Comment by zoechi** [comment]
https://github.com/dart-lang/pub-dartlang-dart/issues/603 Might help. 
If it doesn't I suggest to report an issue there.
As far as I know it's quite limited what the Example tab can render currently.
