### ISSUE TITLE
Better sharing of cached artifacts across platforms

### ISSUE THREAD

**Issue by sbaranov** [flutter/flutter#25346]
One example is gen_snapshot, where:
- android_dynamic_profile/<host>/gen_snapshot can reuse android_profile/<host>/gen_snapshot
- android_dynamic_release/<host>/gen_snapshot can reuse android_release/<host>/gen_snapshot

It might be necessary to rethink the structure of the artifacts tree since such sharing wouldn't be very easy to create and maintain right now.

**Comment by jonahwilliams** [comment]
@sbaranov shall we close this issue for now?
