### ISSUE TITLE
flutter config

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2535]
This is a strawman of what a `flutter config` command might look like. For some of the motivation for this, see https://github.com/flutter/flutter/issues/2381. Comments welcome -

`flutter config`

- when starting up, if there's no config file, then the code behind `config detect` is called
- we want to try and keep the `config` commands clear and simple
- we should clearly indicate where the flutter config file is. Perhaps print the location for every invocation of `flutter config`; perhaps print it's location for some of the other commands (`--version`? `doctor`?)
- the file lives in the user's home dir
- it's named something like `.flutter.config`, `flutter.config`, or `flutter.yaml`
- the file format is either yaml based or a simple key-value file (a properties file - https://en.wikipedia.org/wiki/.properties). `=` separate key/values, comments as `#`'s, and blank lines are ignored
- git has a similar config mechanism (https://git-scm.com/docs/git-config)

`flutter config`
- list all current values; print file location
- `--list` is optional

`flutter config detect`
- auto-detect and set detected values
- or, `flutter config --detect`?

`flutter config detect --dry-run`
- auto-detect values; print what would change; don’t affect the changes

`flutter config android-home path/to/android`
- set the ‘android-home’ value
- also, can take ‘--set’, but that is optional (for symmetry with --clear)

`flutter config android-home`
- print the value for android-home

`flutter config --clear android-home`
- clear the value for ‘android-home’

**Comment by sethladd** [comment]
> the file lives in the user's home dir

There will come a day when I have multiple flutter apps in development, each of which needs a different version of Flutter. Can we build a configuration solution that supports this scenario?

This is similar to how we do the Atom plugin. The settings are Atom-wide (e.g. the Dart SDK) but over time, many settings should become per-project (e.g. the Dart SDK).

Thanks!

**Comment by devoncarew** [comment]
We did land a flutter config command as part of work to let the user configure where their android sdk and gradle binary are located.
