### ISSUE TITLE
Execute rename fixit

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2536]
We should execute the rename fixit.

 - [x] Audit all widgets for LTR basis.
 - [x] Audit the rename fixit label to generate a complete list of renames we're going to execute.
 - [x] Write the email we're going to send to flutter-dev that explains what we did.  (Don't send until later.)
 - [x] Land one pull request per rename.
 - [x] Update all documentation to match the new names.
 - [x] Update all sample code to match the new names.
 - [x] Email flutter-dev explaining what we did.
 - [x] Push the new names to alpha branch
 - [x] Update the codelab to match the new names.

**Comment by abarth** [comment]
@Hixie

**Comment by abarth** [comment]
- [ ] GestureArena -> GestureArenaManager
- [ ] Flex arguments
  - [ ] justifyContent -> mainAxisAlign
  - [ ] alignItems -> crossAxisAlign
  - [ ] FlexJustifyContent -> MainAxisAlign
  - [ ] FlexAlignItems -> CrossAxisAlign
 - [ ] MultiChildLayoutDelegate#isChild -> hasChild
 - [ ] Viewport#scrollDirection -> overflowDirection
 - [ ] Painter -> RenderObjectPainter
 - [ ] ThemeData#text -> textTheme
 - [ ] EdgeDims -> EdgeInsets
 - [ ] CustomOneChildLayout -> CustomSingleChildLayout
 - [ ] OneChildLayoutDelegate -> SingleChildLayoutDelegate
 - [ ] OneChildRenderObjectWidget -> SingleChildRenderObjectWidget
 - [ ] ScrollBehavior#createFlingScrollSimulation -> createScrollSimulation
 - [ ] StatefulComponent -> StatefulWidget
 - [ ] StatelessComponent -> StatelessWidget
 - [ ] RouteArguments -> BuildContext

Unresolved:
 - https://github.com/flutter/flutter/issues/2348
 - https://github.com/flutter/flutter/issues/2448
 - https://github.com/flutter/flutter/issues/2540
 - https://github.com/flutter/flutter/issues/2548
 - https://github.com/flutter/flutter/issues/2562

**Comment by Hixie** [comment]
- [ ] RenderCustomOneChildLayoutBox -> RenderCustomSingleChildLayoutBox

Should we rename OneChildRenderObjectWidget to SingleChildRenderObjectWidget and OneChildRenderObjectElement to SingleChildRenderObjectElement as well?

FWIW the render object mixin for the same concept is called "RenderObjectWithChildMixin".

**Comment by abarth** [comment]
> Should we rename OneChildRenderObjectWidget to SingleChildRenderObjectWidget and OneChildRenderObjectElement to SingleChildRenderObjectElement as well?

Yes.

**Comment by abarth** [comment]
I moved the checkbox from your comment up to my earlier comment.  Please feel free to edit that comment to add more checkboxes.  That way we can keep one clean list.

**Comment by qchong** [comment]
@abarth Adam, can you please explain the thinking for this renaming proposal?

RouteArguments -> BuildContext

Is the existing [`BuildContext`](http://docs.flutter.io/flutter/material/BuildContext-class.html) class going away, or is RouteArguments going to be a property of BuildContext?

**Comment by abarth** [comment]
Currently RouteArguments has a single member, which is a BuildContext.  The idea is to remove RouteArguments entirely and just pass the BuildContext directly.  The existing BuildContext class will remain as it is.

**Comment by appsforartists** [comment]
I know @Hixie dislikes `navButton`, but `leading` [already has a well-known definition in layout](https://en.wikipedia.org/wiki/Leading) and doesn't feel like a logical descriptor for "back or menu button".

I'm still a proponent of `navButton`, `title`, and `buttons` for `AppBar`, but I'll keep thinking of alternatives for `navButton`.

**Comment by abarth** [comment]
"Leading" has more meanings that just the one you've linked.  For example, https://developer.apple.com/library/ios/documentation/AppKit/Reference/NSLayoutConstraint_Class/ uses "leading" in the same sense as here: namely "prior in reading order".  It's not a descriptor for "back or menu button" but instead a description of where the widget appears visually, specifically that it's located logically prior to the other children.  That similar to the existing name, left, which is also a visual descriptor but a physical one.

**Comment by appsforartists** [comment]
Their inclusion of `trailing` as a parameter makes it a bit more clear which sense of the word `leading` they mean; still, what something does is a better naming formula than where something lives, and the other two items (`title` and `buttons`) both fall in the "what something does" category.

While I share your distaste for abbreviated property names, I'm having a hard time coming up with a better name than `navButton`.  Though names like `attr` make me cringe, "nav" doesn't bother me, perhaps because it's so ubiquitous in UI design (for instance, the [Material Spec](https://www.google.com/design/spec/layout/structure.html#structure-toolbars), [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav), and [Ionic](http://ionicframework.com/docs/api/directive/ionNavBar/) all use that shorthand).  Alternatively, `navigationButton` is more characters, but it's not like this is a component people are likely to use often.

**Comment by abarth** [comment]
Ultimately, it's a matter of taste.  In this instance, we're choosing to use a less prescriptive name for this slot in this widget.

**Comment by Hixie** [comment]
(In particular, the left slot could in some apps be used for an app branding icon.)

**Comment by abarth** [comment]
ToolBar -> AppBar

^^^ I'm confused about this change.  Previously we called this widget AppBar but I thought someone corrected us and convinced us to rename it to ToolBar.  Which is correct?  Is there some reference for this in the spec?

https://www.google.com/design/spec/components/toolbars.html seems to use the term "toolbar".
https://www.google.com/design/spec/layout/structure.html#structure-app-bar talks about an AppBar.

It looks like AppBar is a specific kind of ToolBar.  Sounds like AppBar is the correct name.

**Comment by appsforartists** [comment]
I believe AppBar is correct.  (In #2348, I proposed switching ToolBar to AppBar for precisely this reason - a ToolBar with a a nav button, title, and action buttons is an AppBar.  A ToolBar is a generic piece of material with buttons on it.  For instance, the bottom bar in Keep is a ToolBar but not an AppBar.)

I still think `buttons` and `navButton` (or perhaps `firstButton`) are better names than `actions` and `leading`, but I'm glad to see the move away from positional names towards semantic ones.

**Comment by abarth** [comment]
Thanks!

**Comment by Hixie** [comment]
I don't really understand the difference between AppBar and ToolBar in the material design spec:
https://www.google.com/design/spec/layout/structure.html#structure-app-bar
https://www.google.com/design/spec/components/toolbars.html#toolbars-usage

**Comment by appsforartists** [comment]
It would probably be more clear if the examples in Spec weren't all AppBars.

**Comment by abarth** [comment]
* Website: https://github.com/flutter/website/pull/199
* Game: https://github.com/flutter/game/pull/58
* Usage: https://github.com/dart-lang/usage/pull/65

**Comment by HansMuller** [comment]
According to the MD spec, App Bars have ToolBars: https://www.google.com/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-scrolling

I think what we'll want in the long run is a ToolBar class that manages its simple leading-title-actions row of widgets, and an AppBar that manages the layout of a toolbar, tab bar, and the "flexible space" that's stacked behind them.

**Comment by Hixie** [comment]
Are toolbars used anywhere outside app bars?

**Comment by appsforartists** [comment]
I just confirmed my understanding with Zach.  From [the Spec](https://www.google.com/design/spec/layout/structure.html#structure-app-bar):

> The app bar, formerly known as the action bar in Android, is a special kind of toolbar that’s used for branding, navigation, search, and actions.

The button bar at the bottom of the screen in Keep, or the buttons on the bottom of a card, can be considered a Tool Bar.  The (nav, title, action buttons) triplet is specifically an App Bar.
