### ISSUE TITLE
App crash on debug/release mode (after some time)

### ISSUE THREAD

**Issue by Kigstom** [flutter/flutter#25367]
## Steps to Reproduce

Hi, I'm running on a problem that only occurs when i (developer/user) try to launch the app days (for me was 1-2 weeks later) after installing it on iOS devices (eg.: my iPhone 7).
The first time that happens I thought that was an error/bug in the code, but then I made a little test and 
installed 2 apps, one default created when I create a new project and other by me, on my device in debugger mode and release mode, and the results were the same.

## Logs

The logs that I can get are the device (iPhone 7) logs retrieved by the Xcode.

1- Default App
```
Analyzing flutter_app...                                         
No issues found! (ran in 1.3s)
```
2- Developed App
```
Analyzing legislactionapp...                                     
No issues found! (ran in 1.6s)
```
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-PT)
    • Flutter version 1.0.0 at /Users/daniel/Development/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK at /Users/daniel/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/daniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Pixel • FA6C80302414 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
> The logs that I can get are the device (iPhone 7) logs retrieved by the Xcode.

Did you intend to add such logs?

**Comment by Kigstom** [comment]
Not sure if its crucial or if are readable, but here they are:
[ios_logs.zip](https://github.com/flutter/flutter/files/2680016/ios_logs.zip)

**Comment by opannapo** [comment]
UP

**Comment by zoechi** [comment]
Are you still seeing this with `dev` or `master` channel builds?

The files in the `ios_logs.zip` are 6-9 weeks older than when you posted the comment (2018-10-09 
 -2018-10-29). 
Are you sure they are even related?

**Comment by opannapo** [comment]
I have same problem on release mode app. Apps can't be open after more than (3 days).

**Comment by zoechi** [comment]
@opannapo can you provide information about how to reproduce?
How do you build? 
What plugins are you using?
What is the output of `flutter doctor -v` (on the machine where you built the app)?

**Comment by opannapo** [comment]
@zoechi & @Kigstom 

I've found best answers on apple developer forums.
That is because of Developer Certificate (Free - Valid for 7days).

check it out : https://forums.developer.apple.com/thread/51527

**Comment by Kigstom** [comment]
> @zoechi & @Kigstom
> 
> I've found best answers on apple developer forums.
> That is because of Developer Certificate (Free - Valid for 7days).
> 
> check it out : https://forums.developer.apple.com/thread/51527#157434

Good morning....,
that is what I'm facing..., and it must be the default specs for a 'free dev certificate'.
So i can conclude that the actual 'issue' was not the problem, but a, irresponsibility from my(dev) part not reading the notes properly.

I'm sorry and thank you all for your time and patience.

**Comment by zoechi** [comment]
Sounds like this is solved and can be closed.
Please just add a comment if you think it should be reopened.
