### ISSUE TITLE
Add-Flutter-to-existing-apps, and I want to upload the Flutter library to maven

### ISSUE THREAD

**Issue by Sherchen** [flutter/flutter#25361]
Hi, follow the artical [Add-Flutter-to-existing-apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps), then it's great, but when i want to upload the my_flutter/Flutter to then maven, it failed with the below log

```
15:39:25: Executing task 'uploadArchives'...

Executing tasks: [uploadArchives]


FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\code\meiyougit\MvpDemo\my_flutter\.android\settings.gradle' line: 6

* What went wrong:
A problem occurred evaluating settings 'android_generated'.
> D:\code\MvpDemo\my_flutter\.android\Flutter\include_flutter.groovy (D:\code\MvpDemo\my_flutter\.android\Flutter\include_flutter.groovy)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
15:39:25: Task execution finished 'uploadArchives'.
```

**Comment by Sherchen** [comment]
please help me ,thank you

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by Sherchen** [comment]
i type the command "gradle flutter:uploadArchieves" then it's ok.

**Comment by 26shruti** [comment]
Possible solution https://github.com/flutter/flutter/issues/31639. Worked for me.

**Comment by jinyulei0710** [comment]
jinyulei:.android jinyulei$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/jinyulei/development/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jinyulei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jinyulei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[!] Connected device
    ! No devices available

**Comment by jinyulei0710** [comment]
I try to export aar from Flutter module project, when I run assembleRelease  but failed with this error.
* Where:
Settings file '/Users/jinyulei/Desktop/SmartPark/park_flutter_module/.android/settings.gradle' line: 6

* What went wrong:
A problem occurred evaluating settings 'android_generated'.
> /Users/jinyulei/Desktop/SmartPark/park_flutter_module/.android/app/include_flutter.groovy (/Users/jinyulei/Desktop/SmartPark/park_flutter_module/.android/app/include_flutter.groovy)

It seemed like that, settings.gradle file can not find the include_flutter.groovy in the path. And it's under the .android not app. but with the command line , type gradle flutter:assembleRelease still works. it generate a aar file, but the file does not  contain any flutter assets, how can I solve  this problem.
@zoechi

**Comment by jinyulei0710** [comment]
I should choose the task in app not the task in flutter module.
![1559345813770](https://user-images.githubusercontent.com/3348074/58739979-19f87f00-8440-11e9-858e-3d6a495f6a47.jpg)

**Comment by xster** [comment]
@blasten this is fixed now right?

**Comment by xster** [comment]
The Flutter engine is now on maven in download.flutter.io. See https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar
