### ISSUE TITLE
Couldn't create circle images since the last Flutter version 1.0 update

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#25366]
note: The source IMga is in Square size

What didn't worked:
1) i tried to give the lik as Circleavatar 's background image,
2)gave image.Network as Circle avatars child
3)Iside a container with Boxshape.circle,i gave the url as decoration image as well as child of the same container,either way is not  working,
4)gave the image.Network as child of a cliprRect with a borderadius of 90.0 but nothing seems working

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Might be a case of #21094, #24225

**Comment by rajeshjeshar** [comment]
@zoechi  
flutter doctor -v
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.0.0 at C:\Program Files\Flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\RAJESH\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • SM J500F • c7139b71 • android-arm • Android null (API null)

• No issues found!

**Comment by rajeshjeshar** [comment]
@zoechi  my google user phot is circluar in youtube and other apps but in my flutter app its square,eve tried all the cliping methods and circluar avatr methods

**Comment by rajeshjeshar** [comment]
SOLVED BY USING AM ICON BUTTON 

`actions: <Widget>[
IconButton(
  onPressed: (){},  
  icon: Container(height: 24.0,width: 24.0,
  child: CircleAvatar(
    backgroundImage: NetworkImage('http://www.pantone.com/images/pages/20758/wallpaper/MIBwallpaper5-1280x1024.jpg'), 
  )
  )
)]`

**Comment by rajeshjeshar** [comment]
SOLVED BY USING AM ICON BUTTON 

`actions: <Widget>[
IconButton(
  onPressed: (){},  
  icon: Container(height: 24.0,width: 24.0,
  child: CircleAvatar(
    backgroundImage: NetworkImage('http://www.pantone.com/images/pages/20758/wallpaper/MIBwallpaper5-1280x1024.jpg'), 
  )
  )
)]`
