### ISSUE TITLE
ScrollView Rendering Performance Frameskip

### ISSUE THREAD

**Issue by simonepauro** [flutter/flutter#25372]
I noticed a difference between native and Flutter ScrollView performance on Flutter apps I installed from the App Store.

Here is what I see:
https://drive.google.com/file/d/1rgoIEn9TTA1UPRO-1fSjJz4P0geH6HNS/view?usp=sharing

## Steps to Reproduce

To reproduce you can install “The history of everything” from App Store and then:

- Launch the app
- Tap the search bar on top
- Slowly scroll up and down 
- You can notice some frameskip in scrollView rendering

I am using an iPhone 6s running iOS 12.1

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Did you run in debug mode (default) or profile/release mode?

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by eseidelGoogle** [comment]
I notice also the phone is in reserve power mode?  I wonder if Flutter doesn't play nice with the OS when that's the case.  I'm not aware of Flutter having any awareness of battery or power conservation modes.

**Comment by eseidelGoogle** [comment]
My understanding of the bug @zoechi is that he's just installing https://itunes.apple.com/us/app/the-history-of-everything/id1441257460 on his phone and running it?

**Comment by zoechi** [comment]
@eseidel I see. Didn't recognize. 
So release mode and reproduction is done.

**Comment by simonepauro** [comment]
@eseidelGoogle I confirm that I have the same result even if the iPhone is connected and the charge is at 74%

**Comment by numez** [comment]
@simonepauro and I have tested other apps from the stores including "[Flutter Gallery](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=it)", "[The History of everything](https://play.google.com/store/apps/details?id=com.twodimensions.timeline)".

I tested them on Android and I noticed that **scrolling** does not always feel as smooth as native. 

##### devices:

> Samsung - Galaxy s6 edge + running Android 7.0
> Samsung - Galaxy s8 running Android 8.0
> LG - G6 running Android 8.0

**Comment by zoechi** [comment]
@numez you are talking about release or profile builds, not debug builds, right?

**Comment by numez** [comment]
@zoechi I just downloaded those apps from Google PlayStore

**Comment by numez** [comment]
@zoechi <https://github.com/zoechi> I just downloaded those apps from
Google PlayStore

Il giorno gio 20 dic 2018 alle ore 15:39 Günter Zöchbauer <
notifications@github.com> ha scritto:

**Comment by zoechi** [comment]
@numez sorry, I recognized only later that these were play-store links and I deleted my comment shortly after I sent it.

**Comment by liyuqian** [comment]
It's slow because many widgets are unnecessarily rebuilt and repaint in each frame. Adding RepaintBoundary to the list item as shown below would drastically improve the scroll performance:

```
diff --git a/app/lib/main_menu/main_menu.dart b/app/lib/main_menu/main_menu.dart
index 3da7867..57cfa8a 100644
--- a/app/lib/main_menu/main_menu.dart
+++ b/app/lib/main_menu/main_menu.dart
@@ -120,8 +120,10 @@ class _MainMenuWidgetState extends State<MainMenuWidget>
     List<Widget> tail = [];
     if (_isSearching) {
       for (int i = 0; i < _searchResults.length; i++) {
-        tail.add(ThumbnailDetailWidget(_searchResults[i],
-            hasDivider: i != 0, tapSearchResult: _tapSearchResult));
+        tail.add(RepaintBoundary(child:
+            ThumbnailDetailWidget(_searchResults[i],
+            hasDivider: i != 0, tapSearchResult: _tapSearchResult)
+        ));
       }
     } else {
       tail
```

**Comment by liyuqian** [comment]
Close as the fix in https://github.com/flutter/flutter/issues/25372#issuecomment-449184785 has already been applied to "the history of everything" app.
