### ISSUE TITLE
translator lib some time work and some time not work

### ISSUE THREAD

**Issue by HoSheiMa** [flutter/flutter#25376]
### **some time function return to me words done translated and some time give me this** 

> I/flutter ( 4124): -//W3C//DTD HTML 4.01 Transitional//ENtext/html; charset=utf-8initial-scale=1e=document.getElementById('captcha');if(e){e.focus();}1captcha-formpostrecaptcha6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b2ShtjoBNc3yn_gjHu3-nKFLBdqVlsKgZEFFm5pZLyngdlowV0MRT-vfOoYCHuc7OON73OPD8iTYus-WJ7wZH3rUqNFg7CnnSogajoXeNJrcSzTe0ZYWzLzTYGMWiF4FFpVnYYMM2hFlFeD5yKSl17VhI12f87FM04BSLesNwDkdKSOR0FrlJfNilMz2s0xpky9YTHei49kooQ8JWvT77_HmI-1vU51gyWxpdhcrjAL8RvxI3m9kx0y4continue1font-size:13px;document.getElementById('infoDiv').style.display='block';display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`

and some information how to reproduce.

**Comment by HoSheiMa** [comment]
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.471], locale en-US)
    • Flutter version 1.0.0 at C:\flutter\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\HoSheiMa\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.30.0)
    • VS Code at C:\Users\HoSheiMa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

**Comment by HoSheiMa** [comment]
my code
![image](https://user-images.githubusercontent.com/31377696/50016277-6571ba80-ffd1-11e8-84bb-9b2c336dc1f3.png)

**Comment by zoechi** [comment]
What is `GoogleTranslator`? Where does it come from?

**Comment by HoSheiMa** [comment]
come from google api translating

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
