### ISSUE TITLE
Android Studio run window can not show flutter run info

### ISSUE THREAD

**Issue by itning** [flutter/flutter#25371]
My Android Studio Run and Debug Window Can not show info,
What should I do ?

![](https://github.com/itning/FilePool/blob/master/images/bug2.png?raw=true)

**Comment by zoechi** [comment]
Try Menu Window > Restore default layout.

This doesn't really look like a Flutter issue. Please report this with Android Studio.

**Comment by zoechi** [comment]
Do the other tool windows like `TODO` or `Terminal` show?
Ensure you don't have presentation mode active.

**Comment by zoechi** [comment]
Also try <kbd>Ctrl</kbd>+<kbd>Shipft</kbd>+<kbd>Arrow-up</kbd> when the `4: Run` tab is selected. https://blog.jetbrains.com/idea/2010/01/resize-tool-windows-with-keyboard/

I'm going to close. Feel free to add a comment to get it reopened if you still think this is a Flutter issue.

**Comment by itning** [comment]
> Also try Ctrl+Shipft+Arrow-up when the `4: Run` tab is selected. https://blog.jetbrains.com/idea/2010/01/resize-tool-windows-with-keyboard/
> 
> I'm going to close. Feel free to add a comment to get it reopened if you still think this is a Flutter issue.

I update a new image to explain my problem

**Comment by zoechi** [comment]
Did you try any of my suggestions?
The missing window seems to show in your new screenshot. 
What is the screenshot supposed to demonstrate?

**Comment by itning** [comment]
> Did you try any of my suggestions?
> The missing window seems to show in your new screenshot.
> What is the screenshot supposed to demonstrate?

I didn't make clear about my situation. The first picture is my current situation. The second picture is what I found online.

When I run the flutter program, the console of the run window does not display.

I don't know what I set up and I did it according to what you said and it didn't work.

**Comment by zoechi** [comment]
So which of my suggestions did you try and what was the result?

**Comment by itning** [comment]
> So which of my suggestions did you try and what was the result?

- Try Menu Window > Restore default layout.

- try Ctrl+Shipft+Arrow-up when the 4: Run tab is selected.

**Comment by lsp9876** [comment]
mac  as 3.2.1  same issue

**Comment by apm29** [comment]
I have the same issue on mac 3.2.1 and i close the run window and drag the other tool window around until that run icon disappear from ur tool bar, then  it work well again...

**Comment by itning** [comment]
> I have the same issue on mac 3.2.1 and i close the run window and drag the other tool window around until that run icon disappear from ur tool bar, then it work well again...

Suggest you delete `` .AndroidStudio3.2`` folder and restart Android Studio try again

**Comment by votruk** [comment]
I had the same issue but deleting the preference folder not helped. Only changing dart sdk and flutter sdk paths worked.
I described my approach with more details on stackoverflow: https://stackoverflow.com/a/55894953/4312184

**Comment by ravindragupta90** [comment]
i had the same issue in ubuntu 16.04. I just removed the run tab from sidebar and then remove the app from device and run the app now. my console started working

**Comment by nguyenphuc1995** [comment]
> i had the same issue in ubuntu 16.04. I just removed the run tab from sidebar and then remove the app from device and run the app now. my console started working

It work on MacOS

**Comment by HugoHeneault** [comment]
Thanks to @votruk answer I got a more detailed approach [here](https://stackoverflow.com/a/57495406/1847249)

**Comment by MahmoudMatar** [comment]
Try Menu Run > Flutter Run 'main.dart' in Profile Mode

**Comment by Qin0821** [comment]
I deleted the cache and Invalidate Caches / Restart as.
![image](https://user-images.githubusercontent.com/25655555/69125881-c9eea100-0ae1-11ea-9ca8-ccf2b72fa3ac.png)
It's work for me.

**Comment by NandanSatheesh** [comment]
This thing worked for me on Mac OS. 
Setup - Android Studio + iOS Emulator


1. Uninstalled the installed Flutter App on iOS Emulator. 
2. Restart the iOS Emulator 
3. Invalidate Caches and Restart Android Studio
4. Optional - If you are still not able to get a normal run view, try out this experimental feature - custom Flutter Logging View and restart your IDE again. You'll get the same run view in a neat and organized manner. Screenshot attached for the same. 

Hope this helps 😄 

![image](https://user-images.githubusercontent.com/22286630/70235786-a38b5f80-1789-11ea-8458-9b990c3ac2d6.png)

**Comment by Bhargav3132** [comment]
You might have mistakenly minimised the console output. But after you click it there is now way to restore it!

As said on flutter-intellij issues tracker and thanks to @sosite's answer, you will have to restore ~/Library/Preferences/AndroidStudio3.x/options/runner.layout.xml this lines: 

```
<ViewImpl>
     <option name="ID" value="ConsoleContent" />
     <option name="minimizedInGrid" value="false" />
     <option name="placeInGrid" value="bottom" />
     <option name="tabIndex" value="-1" />
     <option name="window" value="0" />
   </ViewImpl>
```
Replace
`<option name="minimizedInGrid" value="true" />`
by
`<option name="minimizedInGrid" value="false" />`
And it's back again!

**Comment by SeasonLeee** [comment]
I have tried every methods from above... none of them work!!! God!
