### ISSUE TITLE
TextField callback onChanged not fired when its controller.text is set

### ISSUE THREAD

**Issue by riccardoratta** [flutter/flutter#25373]
## Steps to Reproduce

Consider this example state of a widget

```dart
class _MyHomePageState extends State<MyHomePage> {
  final textEditingController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.all(15),
        child: Column(
          children: <Widget>[
            TextField(
              controller: textEditingController,
              onChanged: (String value) {
                // NEVER CALLED
                print('Changed: $value');
              },
            ),
            Row(
              children: <Widget>[
                RaisedButton(
                  child: Text('Add: hello'),
                  onPressed: () =>
                      setState(() => textEditingController.text += 'hello'),
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}
```
The text is successfully set, but the callback, and also any listener subscribed, is not called.

From the [TextEditingController documentation](https://docs.flutter.io/flutter/widgets/TextEditingController/text.html) I found

> Setting this will notify all the listeners of this TextEditingController that they need to update (it calls notifyListeners). For this reason, this value should only be set between frames, e.g. in response to user actions, not during the build, layout, or paint phases.

But actually this is a _response to user action_, so why the callback is not called? Also, sorry but I don't know explicitly what is the _build, layout, or paint phases_, but this seems to not be the case.

#### Flutter analyze

```
$ flutter analyze
Analyzing test_app...
No issues found! (ran in 1.9s)
```

#### Flutter doctor

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-GB)
    • Flutter version 1.0.0 at /Users/.../Library/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1
```

**Comment by zoechi** [comment]
> But actually this is a response to user action

user action on the text input field.

Why would you event want that. You can just put the code to `onPressed: ...` where you update the text. There is no point in having a text change event handler executed when text is updated by code.

**Comment by riccardoratta** [comment]
@zoechi I totally understand your point, but imagine if you have a lot of buttons. For example, if you are trying to build a custom keyboard. It implies that you have to attach the same callback on every button (plus the input). But ok, if it's a normal behavior, it's not a problem. Maybe it's possible to improve the `onChanged` documentation. Thanks for the reply.

**Comment by HansMuller** [comment]
I'm afraid that this may be a problem with the docs.  The TextField's onChanged callback is reporting user initiated changes that were handled by the device's input method. The TextField's editable does listen to the TextEditingController, but only to sync up the device's input method. I don't think you could infer any of this from the `TextField.onChanged` doc which just says: `Called when the text being edited changes.`

It is possible to get notified whenever the TextController's value is changed, programmatically or otherwise:
```
  @override
  void initState() {
    textEditingController.addListener(() {
      print("CONTROLLER: $textEditingController");
    });
    super.initState();
  }
```

**Comment by MohammadMobasher** [comment]
i need to call onChange when the textEditingController changed. for example consider this code:

`
 StreamBuilder(
    stream: this._saveSessionLogic.startTime,
    builder: (context, snapshot){
        return TextField(
            onChange:this._saveSessionLogic.startTimeChange,
            controller: this.startController,
            .
            .
            .
        );
    }
`
this code write for validate (using StreamBuilder for validate Time " 12:45:31 "), but when for init data i set " 12:45 " in the startController, onChange not called and the validation not worked.
so my question is how can i handle this situation?
tanks :)

**Comment by PriyaSindkar** [comment]
> @zoechi I totally understand your point, but imagine if you have a lot of buttons. For example, if you are trying to build a custom keyboard. It implies that you have to attach the same callback on every button (plus the input). But ok, if it's a normal behavior, it's not a problem. Maybe it's possible to improve the `onChanged` documentation. Thanks for the reply.

My requirement is just the same. I need to mask mobile number and I have custom keypad to insert the digits. Unable to find a solution for triggering `InputFormatter`.
