### ISSUE TITLE
Adding new value to Firestore database wrecks the item list in Google Map

### ISSUE THREAD

**Issue by usrdjan** [flutter/flutter#25386]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

If you think this is actually a Flutter issue, please create a new issue with the issue template properly filled.
