### ISSUE TITLE
Add debug log messages when the engine's run mode is exposed to the embedding

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#25391]
Add debug log messages when the engine's run mode is exposed to the embedding.

This ticket number will be referenced in TODO comments where such logs are desired.

**Comment by dnfield** [comment]
This is available in the `BuildConfig` class now.  Can we close this?

**Comment by dnfield** [comment]
(Closing this since I'm pretty sure it's fixed, feel free to reopen if it's for something else)

**Comment by matthew-carroll** [comment]
I believe this was about log statements in general, and the debug build config has not been integrated with those yet. They're all still `Log.d(TAG, ....)`. So I'm gonna re-open this.

**Comment by dnfield** [comment]
Ahh gotcha.  Sorry for the confusion.

**Comment by matthew-carroll** [comment]
I think the goal of this issue has been reasonably resolved with the Flutter `Log` proxy that was added recently. Closing.
