### ISSUE TITLE
No valid Android SDK platforms found in C:\Android\android-sdk\platforms. Directory was empty.

### ISSUE THREAD

**Issue by RukaiJohn** [flutter/flutter#25397]
when I first opened the adnroid-sdk folder, platforms wasn't there, but when I copied and paste from directory "C:\Android\android-sdk", I get this error.

No valid Android SDK platforms found in C:\Android\android-sdk\platforms. Candidates were:
        - android-22
        - android-23
        - android-24
        - android-25
        - android-26
        - android-27
        - android-28

I'm not sure what's wrong.

**Comment by zoechi** [comment]
Sounds like you didn't properly install it. You can either use Android Studio to install and update the Android SDK or use `sdkmanager`.
I don't think we want to support installations with manually copied directories.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Vivek-Raman** [comment]
I know that this is closed, but I had the same problem and I managed to figure out what was wrong. This is for OP or anyone else Googling their way to this thread. Using `sdkmanager "build-tools;28.0.3"` fixed the problem for me. I hadn't included this in the beginning. 

You may use the latest version of `build-tools` available.

**Comment by zoechi** [comment]
@Vivek-Raman you might want to add this as answer to https://stackoverflow.com/questions/53986067/no-valid-android-sdk-platforms (there might be other related SO questions, also not Flutter related ones)

**Comment by RukaiJohn** [comment]
Vivek, how did you use sdkmanager "build-tools;28.0.3" to fix this issue?

**Comment by ipereto** [comment]
I've set up my Android SDK manually with the command line, and I was able to solve this kind of errors while I tried to set up my development environment, if you want to solve it as I did, just follow the next steps:

**In my case I did the process in Windows 10.**

**1.** Download SDK here: [https://developer.android.com/studio](https://developer.android.com/studio)

![image](https://user-images.githubusercontent.com/14301820/55283693-718a4980-532e-11e9-8a9a-cd7a2f84f1bb.png)

**2.** Save and Unzip the file in a new folder, this will be your Android SDK folder, like this:

![image](https://user-images.githubusercontent.com/14301820/55283725-e2c9fc80-532e-11e9-9200-ee1ce73ff2ec.png)

**3.** In your new Android SDK folder go to -> tools -> bin. Open a command line here `Shift + Right-click`  and click to `Open PowerShell window here` and then ...

![image](https://user-images.githubusercontent.com/14301820/55283819-a26b7e00-5330-11e9-9a7e-ab491723f3f4.png)

... run this command: 
`.\sdkmanager.bat "platforms;android-28" "platform-tools" "build-tools;28.0.3"`

After that you will see these new folders and files:
![image](https://user-images.githubusercontent.com/14301820/55283823-cb8c0e80-5330-11e9-95e4-68c973fea770.png)

Now, you have the last version of build-tools, platform-tools, and a platform. If you want to download other available packages you can list them using `.\sdkmanager.bat --list`. For more information about this command go to [sdkmanager](https://developer.android.com/studio/command-line/sdkmanager).

**4.** Finally, set up your PATH variable adding this new packages:

![image](https://user-images.githubusercontent.com/14301820/55283806-3c7ef680-5330-11e9-9a3b-d31fb3803216.png)

**Now you can check your flutter running `flutter doctor` and you will see something like this!**

![image](https://user-images.githubusercontent.com/14301820/55283860-5f5dda80-5331-11e9-9af3-63d9d83831e1.png)

If this message appears, don't be panic!

![image](https://user-images.githubusercontent.com/14301820/55283926-3853d880-5332-11e9-9a10-5051a1be3caa.png)

Just run this command:

`flutter doctor --android-licenses`

**I hope this can help anyone need it! Bye!**

**Comment by ipereto** [comment]
> Vivek, how did you use sdkmanager "build-tools;28.0.3" to fix this issue?

Hi! Go to the answer I just wrote, maybe it can help you.
https://github.com/flutter/flutter/issues/25397#issuecomment-460216748

**Comment by jasson1010** [comment]
> He configurado mi SDK de Android manualmente con la línea de comandos, y pude resolver este tipo de errores mientras intentaba configurar mi entorno de desarrollo. Si quiere resolverlo como lo hice, siga los siguientes pasos:
> 
> **En mi caso hice el proceso en Windows 10.**
> 
> **1.** Descargue el SDK aquí: https://developer.android.com/studio
> 
> ![imagen](https://user-images.githubusercontent.com/14301820/55283693-718a4980-532e-11e9-8a9a-cd7a2f84f1bb.png)
> 
> **2.** Guarde y descomprima el archivo en una nueva carpeta, esta será su carpeta SDK de Android, como esta:
> 
> ![imagen](https://user-images.githubusercontent.com/14301820/55283725-e2c9fc80-532e-11e9-9200-ee1ce73ff2ec.png)
> 
> **3.** En su nueva carpeta de Android SDK vaya a -> herramientas -> bin. Abra una línea de comando aquí `Shift + Right-click` y haga clic para `Open PowerShell window here`y luego ...
> 
> ![imagen](https://user-images.githubusercontent.com/14301820/55283819-a26b7e00-5330-11e9-9a7e-ab491723f3f4.png)
> 
> ... ejecute este comando:
> `.\sdkmanager.bat "platforms;android-28" "platform-tools" "build-tools;28.0.3"`
> 
> Después de eso verás estas nuevas carpetas y archivos:
> ![imagen](https://user-images.githubusercontent.com/14301820/55283823-cb8c0e80-5330-11e9-95e4-68c973fea770.png)
> 
> Ahora, tiene la última versión de herramientas de construcción, herramientas de plataforma y una plataforma. Si desea descargar otros paquetes disponibles puede listarlos usando `.\sdkmanager.bat --list`. Para obtener más información sobre este comando, vaya a [sdkmanager](https://developer.android.com/studio/command-line/sdkmanager) .
> 
> **4.** Finalmente, configure su variable PATH agregando estos nuevos paquetes:
> 
> ![imagen](https://user-images.githubusercontent.com/14301820/55283806-3c7ef680-5330-11e9-9a3b-d31fb3803216.png)
> 
> **¡Ahora puedes revisar tu flutter `flutter doctor`y verás algo como esto!**
> 
> ![imagen](https://user-images.githubusercontent.com/14301820/55283860-5f5dda80-5331-11e9-9af3-63d9d83831e1.png)
> 
> Si aparece este mensaje, ¡no se asuste!
> 
> ![imagen](https://user-images.githubusercontent.com/14301820/55283926-3853d880-5332-11e9-9a10-5051a1be3caa.png)
> 
> Simplemente ejecuta este comando:
> 
> `flutter doctor --android-licenses`
> 
> **Espero que esto pueda ayudar a que alguien lo necesite! ¡Adiós!**

Funcionó perfectamente, muchas gracias.
