### ISSUE TITLE
Checkbox + label should be a widget

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#254]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 20:15 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1925_

---

Any time you add a checkbox, you end up having to add a label also, and then hooking up the event handlers on both, and it's a pain. We should just have one widget that has a checkbox and a label.

Same for radio buttons, switches, etc.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/HansMuller"><img src="https://avatars.githubusercontent.com/u/1377460?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [HansMuller](https://github.com/HansMuller)**
_Tuesday Nov 03, 2015 at 21:10 GMT_

----

Making it easy to funnel events from widgets (like labels) added to an event handling widget (like Checkbox) might be worth supporting.  See  https://github.com/flutter/engine/issues/1726

**Comment by eseidelGoogle** [comment]
This may need to move to an earlier milestone, given customer: leafy's increasing use of forms and the growing number of dups/references. :)

**Comment by sethladd** [comment]
Is this still a top request? If so, for which customer?

**Comment by Hixie** [comment]
IIRC, leafy was asking for it, but I don't know if it's critical. It's a common request from many people. It might fit in well with the FormField stuff and the InputContainer stuff. cc @mpcomplete @HansMuller

**Comment by sethladd** [comment]
Thanks. I feel like @mehmetf has probably worked around this for now. I'm tempted to move this to milestone 2.

**Comment by omidraha** [comment]
Result?
