### ISSUE TITLE
TextField: Cursor is placed incorrectly when brackets are autocompleted by input method

### ISSUE THREAD

**Issue by microdog** [flutter/flutter#25404]
## Steps to Reproduce

1. Select an input method with brackets autocompleting feature (Baidu, Sogou).
2. Enter a pair of brackets in a TextField by entering a left bracket, the right bracket will be autocompleted by the input method.
3. The cursor is expected to be placed at the middle of the pair of brackets, but it will be placed after the brackets or at the beginning of the TextField.

## Additional Information

* Entering other kinds of brackets also has this issue.
* The cursor can be placed correctly in Flutter running on iOS.

![ime](https://user-images.githubusercontent.com/4081579/50041363-a7ad0180-008e-11e9-9bd7-21742d8f0c8c.gif)

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel dev, v1.1.1, on Mac OS X 10.14.1 18B75, locale en-CN)
    • Flutter version 1.1.1 at /Users/microdog/bin/flutter
    • Framework revision 65df90d8b5 (3 days ago), 2018-12-11 19:29:13 -0800
    • Engine revision 25b58c0c67
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/microdog/Workspace/Android/SDK
    • Android NDK at /Users/microdog/Workspace/Android/SDK/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/microdog/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • ONEPLUS A6000        • a7403e37                  • android-arm64 • Android
      9 (API 28)
    • Kainan's iPhone 2018 • 00008020-001171A12642002E • ios           • iOS
      12.1.1

• No issues found!
```

**Comment by xster** [comment]
@GaryQian, do you want to give this a try too?

**Comment by zoeyfan** [comment]
I am triaging our bug database, and noticed this issue from 2018. @microdog is this still relevant in 1.12?

**Comment by microdog** [comment]
@zoeyfan I can confirm that this issue still exists on `v1.12.13+hotfix.5`.

**Comment by TahaTesser** [comment]
Hi @microdog 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
