### ISSUE TITLE
Adding a "visible" property to the widget class

### ISSUE THREAD

**Issue by Mikkelet** [flutter/flutter#25408]
I sometimes have overlapping widgets, and I would love to have a property that shows/hides a certain widget, so that i have more space for the widget that I'm currently working in.

I've read that I could wrap my widget in a an Opacity widget, but I feel that solution is too hot-fixy.

**Comment by dark-chocolate** [comment]
@Mikkelet  `Opacity` will take up the space, so you can use `Container()`. Now these types of questions are better suited to ask on Stackoverflow, not on Github. Thanks :)

**Comment by zoechi** [comment]
You can use `show ? MyWidget() : Container()` to conditionally show widgets when `show` is `false`.

I'm going to close. Feel free to add a comment to have it reopened if you disagree or still think there is something to do for the Flutter team..
