### ISSUE TITLE
android_alarm_manager 0.2.1 plugin not compatible with firebase_auth 0.6.6

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#25409]
I`m using firebase_auth v-0.6.6  and trying to install android_alarm_manager plugin version 0.2.1
this warning appears 

`android_alarm_manager ^0.2.1 which depends on firebase_auth ^0.5.18, firebase_auth ^0.5.18 is required.`

**Comment by zoechi** [comment]
Duplicate of #25417 

You can try `dependency_overrides:` to foce it to accept `firebase_auth: ^0.6.6`
