### ISSUE TITLE
Looking for desktop and WASM support to let people develop Desktop apps and web-apps using flutter code

### ISSUE THREAD

**Issue by anirudhagupta** [flutter/flutter#25406]
I have actually done a lot of programming on Windows platform (Windows, ASP.NET MVC for WEB). All the work I done in 2018 is depend on Winforms, WPF or Web browser control based Desktop apps (IE control).

None of them was impressive, Xamarin does helping making apps but taking too much time on debugging and compiling on a normal computer.

Flutter can be a good replacement for desktop apps programming, What I used that is from system is Web Browser Control, Which I think can be done with Chrome, Chrome will be used as Web Browser Control for browser embedded login.

Controls like rendered in Android can be used in Desktop environment, Actually I see a repos under Google organization but it say it's officially not supported.

If Flutter can be used on Windows, it can be used on Linux and Mac too. If this become reality people don't need to write apps in WPF, Winforms and limited to windows only.

If flutter can be deployed to WASM (Web Assembly).  This will be better solution than React. I can just use one framework that does it all.

This year I developed 15 apps in winforms ( I used framework that are on github but no one them supported, the person who make material winforms get job elsewhere). Everything regarding WPF and Winforms and Xamarin is so terrible. Even things are open-source now they are not getting community support.

I think it would be much better to use Skia for Desktop since It can be extend to multiple platform. For web I hear about Flutter few days ago that can be used for web too. If WASM kind of thing get supported in flutter, it would be great to make apps either native or PWA.

Is flutter team considering plan to make it work for web, Any unofficial repos who are trying to achieve it for Desktop or WASM.

**Comment by zoechi** [comment]
See
- https://github.com/google/flutter-desktop-embedding/notifications
- https://medium.com/flutter-io/hummingbird-building-flutter-for-the-web-e687c2a023a8

As far as I know WebAssembly is mostly for non-UI code and Flutter is mostly just UI code.
