### ISSUE TITLE
ListItem and an LTR bias

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2540]
ListItem has "left" and "right" properties.

**Comment by abarth** [comment]
TwoLevelListItem has one too.

**Comment by HansMuller** [comment]
The spec refers to the left and right parts of a list item as the primary and secondary action, or "most descriptive content" and "least descriptive content".  ListItem currently calls the main elements of the item (usually just lines of text) "primary" and "secondary", which is also consistent with the spec.

![list_item](https://cloud.githubusercontent.com/assets/1377460/13652643/349b4778-e602-11e5-9eb1-d50cfd6de75e.png)

**Comment by abarth** [comment]
Maybe "avatar" for the left and "secondaryAction" for the right?  It looks like the "primary action" includes both the avatar and the primary and secondary text.

**Comment by HansMuller** [comment]
You're right about "primary action", I guess that term makes sense when the list item responds directly to a tap.  

The thing on the right isn't necessarily an action and the what's on the left is necessarily an avatar.  We could use generic terms like leading/trailing, start/end, first/last but they don't seem to fit this situation very well. Names are hard.
