### ISSUE TITLE
Want to have an API visible to test to clean `SharedPreferences._instance`

### ISSUE THREAD

**Issue by timnew** [flutter/flutter#25407]
Propose to to add API for test in sharedPreferences:

```dart
 @visibleForTesting
  static void resetSharedPreferences() {
       _instance = null;
  }
```
I'm writing on some test around my code wrapped around  `SharedPreferences`.

I created a class that simulated the native side of the channel:

```dart
class FakeSharedPreferences {
  final Map<String, Object> data;

  FakeSharedPreferences(MethodChannel channel, this.data) {
    channel.setMockMethodCallHandler(handler);
  }

  Future<dynamic> handler(MethodCall methodCall) async {
    print("RPC: $methodCall");

    switch (methodCall.method) {
      case 'getAll':
        return data;
      case 'setString':
      case 'setStringList':
        data[methodCall.arguments['key']] = methodCall.arguments['value'];
        return true;
      case 'remove':
        data.remove(methodCall.arguments['key']);
        return true;
      case 'clear':
        data.clear();
        return true;
      default:
        print("Not implemented ${methodCall.method}");
    }
  }
}
```

I'll reset the fake class in every test, but I found my tests still failing due to the `_instance` singleton instance. It is so bad, that my different tests might heavily impact on each other. But it can be fixed quite easily

**Comment by adam7** [comment]
Is there any workaround available for this, I'm guessing not because that _instance singleton is inaccessible.

**Comment by stuartmorgan** [comment]
Closing as obsolete; `setMockInitialValues` addresses this use case.
