### ISSUE TITLE
cloud_firestore `setData` does not return future in offline mode

### ISSUE THREAD

**Issue by neerajyadav** [flutter/flutter#25415]
sdk versions:

```
dart: ">=2.1.0-dev.5.0 <=2.2.0"
flutter: ">=0.2.4 <2.0.0"
cloud_firestore: "0.8.2+3"
```
#### Summary:
Firestore `setData` does not return the `Future` or any kind of indication if device is offline. Code execution stops at
``` dart 
await _firestore.document("users/$userId").setData(data, merge: true);
``` 
It should return the `Future` with some additional information so that further code can execute and branch out based on that `Future` response.

#### Full Description:
I'm developing an app using `BLoC` pattern and using `firestore` with offline data mode enabled. As the `BLoC` pattern says, inputs are `sink` and outputs are `stream`.

I've a profile screen where I'm taking data from user, saving it to `firestore` and on successful save navigating user to main screen.

Using `BLoC` pattern, I've a sink `usernameUpdate` where I accept `ProfileNameModel`. On save button click, I add data to `usernameUpdate` sink. In `bloc`, I'm listening this incoming data and saving it to `firestore`. This is how my `bloc` looks like.
``` dart
final _usernameUpdate = PublishSubject<ProfileNameModel>();
  Sink<ProfileNameModel> get usernameUpdate => _usernameUpdate.sink;
  Observable<bool> get usernameUpdated =>
      _usernameUpdate.asyncMap((model) async {
        var updatedUser = user.value.rebuild((r) => r
          ..name = model.name
          ..username = model.username);
        await _repository.updateUser(updatedUser.toDocument(), updatedUser.id);
        return true;
      });
```
This is `repository` code.

``` dart
Future<void> updateUser(Map<String, dynamic> data, String userId) {
    return _firestore
        .document("$_userCollection/$userId")
        .setData(data, merge: true);
  }
```
On my widget screen I'm listening `usernameUpdated` `stream`. Once I receive data, I navigate user to main screen. 

The above setup works fine when working with active data connection. If the data connection is not available, `updateUser` function does not return `Future` and execution stuck at
``` dart
await _repository.updateUser(updatedUser.toDocument(), updatedUser.id);
``` 
Though the data is saved locally, it never executes `return true;` and UI screen does not get data from the `stream` it is listening and does not navigate to main screen.

Once device get data connection, `firestore` sdk internally writes data to server and then it returns the `future`.

#### Expected
`setData` should return the `Future` with additional information so that next code can execute and branch out based on the response from that `Future`.

**Comment by kinex** [comment]
Same problem with `DocumentData.updateData `and `DocumentData.delete`. None of those calls will return if device is offline. Anyway, otherwise they seem to work as expected (modifications are uploaded to server after device is back online).

My suggestion for the fix: just don't hang the calls even if device is offline. No other changes needed into these methods. There could be some other method for getting current sync status (info about modifications not yet uploaded to server).

One possible workaround: before each of those calls check if device if offline and if it is, call the method without `await`.

**Comment by dougsatch** [comment]
In Flutter logic such as this is common:

```
func(something) async {
  await firebase.update(something);
  showDialog("Good Stuff");
}
```

When the device is offline, no feedback will be given. The user will navigate away and forget about it. Then when the device comes back online, the dialog will show and the user will have no idea what that's about.

It would great to have an "online only" mode for CRUD operations, so that we get _immediate_ feedback when the network is offline, and we can choose which mode to use when sending requests.

**Comment by basketball-ico** [comment]
Any update of this?

**Comment by basketball-ico** [comment]
Any update of this?

**Comment by CoreyCole** [comment]
In my app, I'm defaulting to never `await` a `document.setData()` call because it never returns when the device is offline. But, even though I'm not awaiting it, code execution stops after the set call when my device is offline.
```dart
User setUserField(User user, String fieldName, data) {
  _firestore.setUserField(user.uid, fieldName, data); // no await in case offline
  final mappedUser = user.toMap();
  mappedUser['fieldName'] = data;
  final newUser = User.fromJson(mappedUser);
  print('[RepositoryService][setUserField]: newUser: $mappedUser'); // never reaches this print statement
  return newUser;
}
```

**Comment by CoreyCole** [comment]
So what I'm gathering from this thread is that we need to default to never awaiting for a set/update because, in the case the user is offline, it will never complete?

**Comment by ride4sun** [comment]
Can somebody point me to an flutter example which deals with the offline / online case. I try to get a responsive app since a week now and can not get it working for the offline case in a consistent manner. Listening to the cloud firebase videos it should be plug and play which is obviously false advertising and the flutter guys seems to be busy with the other 5000 defects. Sorry for the rant.

**Comment by neerajyadav** [comment]
@ride4sun You can use `timeout` as a workaround. Example: 

``` dart
_firestore
        .collection("users")
        .document("$id")
        .setData(data, merge: true)
        .timeout(Duration(seconds: 5));
```
On the outer side you can catch `TimeoutException` to assume device is offline and `setData` is timed out.
``` dart
try {
          await _repository.updateData(
              entity.toDocument(), entity.id);
        } catch (exception) {
          if (exception is TimeoutException)
            // operation is timed out. Device is offline. Take further steps.
          else
            // actual error occurred.
        }

**Comment by basketball-ico** [comment]
@neerajyadav This not have the expected behavior, because the update of the local database is immediate. If the timeout exception is throwed  the data is updated in the local database, and when have connection again it will sync. 🙁

**Comment by neerajyadav** [comment]
@basketball-ico What else you expect?

**Comment by basketball-ico** [comment]
@neerajyadav when you are offline, the data is saved in the local database without check any Security Rules, and when is online, this check the secure rules and if don't pass any security rule it will deleted.
In this way the backed in safe, but I show to user wrong data.
This is a special case, but if you don;t think this can happen is better to call  the methods without use `await / then`

**Comment by ride4sun** [comment]
@basketball-ico  I would expect that the call should be done always with a future and return immediately if there is no reliable connection, checked by another thread. The future helps to not block UI in the meantime even if there is a timeout. 

I must miss something ....

**Comment by sperochon** [comment]
Here is the official confirmation that this is the intended behavior (from 11:15) :
https://www.youtube.com/watch?v=XrltP8bOHT0

**Comment by kroikie** [comment]
@neerajyadav

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/542. Any further collaboration will be done there.
