### ISSUE TITLE
How to update all the dependency in pubspec.yaml file?

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25414]
Is there any way to update all your dependency in `pubspec.yaml` file to the latest version. 
I tried `pub upgrade` but it didn't work.

**Comment by dark-chocolate** [comment]
https://github.com/flutter/flutter/issues/17353#issuecomment-447644066

**Comment by sgehrman** [comment]
I see this question asked a bunch of places but no one answers it.  Is there a command to update the version numbers to the latest in pubspec.yaml?

**Comment by dan-r95** [comment]
Leaving the field empty bumps the package version to the latest available (as you can see in `pubspec.lock`.
like 
```
http:
```
