### ISSUE TITLE
Remove firebase dependency from android_alarm_manager 

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#25417]
I don`t know why alarm_manager depend on firebase auth !!!!

firebase dependency should be be removed.

**Comment by Timmmm** [comment]
Yes this is very weird and also leads to crashes!

```
12-15 17:57:14.664 11092 11092 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.quicktimer/com.example.quicktimer.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.example.quicktimer. Make sure to call FirebaseApp.initializeApp(Context) first.
12-15 17:57:14.664 11092 11092 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
12-15 17:57:14.664 11092 11092 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
12-15 17:57:14.664 11092 11092 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
12-15 17:57:14.664 11092 11092 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
12-15 17:57:14.664 11092 11092 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
1
```

Took me quite a long time to work out why the hell the alarm manager would have anything to do with Firebase! Even longer because when I added the alarm manager dependency and hot-reloaded it didn't crash, so I assumed it was ok.

**Comment by Timmmm** [comment]
There's a pull request to fix this, not yet merged: https://github.com/flutter/plugins/pull/926

**Comment by mohamed6996** [comment]
Yeah, very weird! 
You must have firebase project to use alarm manager🙄heh
I hope someone merge it soon.

**Comment by TahaTesser** [comment]
Hi @mohamed6996 
Given them mentioned PR suppose to fix this issue is merged [comment](https://github.com/flutter/flutter/issues/25417#issuecomment-447587623)

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
