### ISSUE TITLE
Flutter Doctor says CocoaPods out of date when it is not

### ISSUE THREAD

**Issue by RedQuark** [flutter/flutter#25411]
## Steps to Reproduce

1. Run flutter doctor

## Logs

```
```

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-US)
    • Flutter version 1.0.0 at /Users/redquark/development/flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/redquark/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Mark Durham's iPad Pro • 304eb3cb787e69ca8ad23a7bcdfde62d26b20785 • ios •
      iOS 12.1.1

! Doctor found issues in 1 category.
```

## Development Environment
macOS High Sierra Version 10.13.6 (17G4015)
bash shell and/or Visual Studio Code November 2018 (version 1.30)
Xcode Version 10.1 (10B61)

## Additional Information
I have followed the instructions to upgrade CocoaPods several times (each time I upgrade flutter and get the "CocoaPods out of date" message), and other than the first time, I always get this notification: `Error: cocoapods 1.5.3 already installed`.

I don't know if it matters, but I also have the CocoaPods app (in addition to the command line CocoaPods), and the app's version is 1.5.2 ("currently the newest version available").

Either "flutter doctor" is looking somewhere other than where CocoaPods is looking for its version number(s), or "flutter doctor" does not recognize that 1.5.x is greater than 1.5.0 for x > 0.

Note: My flutter-based iOS apps all appear to work properly with no issues so far, despite this error/warning in "flutter doctor".

**Comment by RedQuark** [comment]
Hmm, I may have found at least part of the problem. Running `pod --version` in a terminal window yields "1.3.1".

**Comment by RedQuark** [comment]
`sudo` cures all woes. In this case, running the following solved the problem:
```sudo gem install cocoapods```
`pod --version` now reports "1.5.3" and "flutter doctor" no longer complains about my version of CocoaPods. Not absolutely certain how or why I have/had three different versions of CocoaPods floating around my system, but the problem is solved.

**Comment by hanglearning** [comment]
`sudo gem install cocoapods` gives me this error 
```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.
```
tho. By referring to here [https://stackoverflow.com/questions/49213136/you-dont-have-write-permissions-for-the-usr-bin-directory-when-installing-s/49213584](stackoverflow)
I run `sudo gem install -n /usr/local/bin cocoapods` then flutter doctor wouldn't complain.

**Comment by netopaez97** [comment]
Go to iOS folde:

1. cd ios
2. Then, run pod update.
3. Go back to your main project with: cd ..
4. Run flutter run
