### ISSUE TITLE
Issues using cloud_firestore: ^0.8.2+3 & cloud_firestore: ^0.8.2

### ISSUE THREAD

**Issue by kentonraiford** [flutter/flutter#25427]
Hi,

I was following the`[ Firestore for Flutter tutorial (https://codelabs.developers.google.com/codelabs/flutter-firebase/#3)` and received an error when adding "cloud_firestore: 0.8.2+3" to my pubspec.yaml file. 

I've searched around but can't seem to find a solution.

**This is the error I receive:**

D8: Cannot fit requested classes in a single dex file (# methods: 69328 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/4.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/5.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/6.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/7.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/8.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/9.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/10.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/11.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/18.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/23.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/28.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/33.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/38.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/43.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/48.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/53.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/58.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/63.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/68.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/73.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/78.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/83.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/88.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/93.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/98.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/103.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/108.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/113.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/118.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/123.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/128.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/133.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/138.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/143.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/148.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/153.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/158.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/163.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/168.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/173.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/178.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/183.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/188.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/193.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/198.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/203.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/208.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/213.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/218.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/223.jar, /Users/Kenton/AndroidStudioProjects/baby_names/build/app/intermediates/transforms/dexBuilder/debug/228.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kentonraiford** [comment]
I found a solution:

https://stackoverflow.com/questions/51341627/android-gives-error-cannot-fit-requested-classes-in-a-single-dex-file

**Comment by RaphealToby** [comment]
> 
> 
> I found a solution:
> 
> https://stackoverflow.com/questions/51341627/android-gives-error-cannot-fit-requested-classes-in-a-single-dex-file

This also resolved my problem
