### ISSUE TITLE
PageView and maps - map caching

### ISSUE THREAD

**Issue by stubborncoder** [flutter/flutter#25422]
Hello I just wanted to know if there's any way to cache a map widget so it does not look laggy when it's inside a PageView. 

In the below image whenever I press back or forward button and then I get back to the page that has the map, it's always loading and looks pretty bad.

In this image I had to wrapp  it in a FutureBuilder to avoid a hard stop between pages that is taking allways when the flow is --> forward. If you go backwards the stop is sligthly smoother but still... 

![20181216_000301](https://user-images.githubusercontent.com/11727994/50048250-76045c80-00c7-11e9-99fd-5f332c4eda17.gif)

**Comment by kf6gpe** [comment]
cc @amirh, who was looking at the maps plugin a while ago. I'm moving this out to Stretch Goals, however, as we're pretty booked with other work.

**Comment by kf6gpe** [comment]
@bparrishMines with @amirh out right now, do you know who's looking at the maps plugin? I'm not sure who else to talk to about where this should land or where we should schedule it.

**Comment by bparrishMines** [comment]
cc @cyanglaz @blasten

@kf6gpe I don't believe we have anyone with cycles to look into this at the moment. We will keep it on our radar though

**Comment by darshankawar** [comment]
@stubborncoder 
Is this still an issue using latest framework version and plugin [version](https://pub.dev/packages/google_maps_flutter/install) ?
If so, can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
