### ISSUE TITLE
The following ArgumentError was thrown building Home(dirty, state: _HomeState#adf96): Invalid argument(s)

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [flutter/flutter#25428]
I am getting issue in flutter app when trying to get data from shared preference which I have already saved. 

```dart
class Home extends StatefulWidget{
  @override
  State<StatefulWidget> createState() => new _HomeState();
}

class _HomeState extends State<Home> {
  Drawer drawer = new Drawer();

  String strName, strEmail, strImageURL;
  int userId;
  Image imgProfile;

  @override
  void initState() {
    super.initState();
    _loadSharedPref();
  }

  //Loading Shared value on start
  _loadSharedPref() async {
    print('In Shared Profile');
    try{
      SharedPreferences prefs = await SharedPreferences.getInstance();
      strName = prefs.getString('name');
      print('Shared Profile Name '+strName);
      setState(() {
        strName = prefs.getString('name');
        userId = prefs.getInt('userId');
        strEmail = prefs.getString('email');
        strImageURL = prefs.getString('avatar');
        imgProfile = Image.network(Config.PROFILE_PIC+strImageURL);
        print('Image URL ---- '+Config.PROFILE_PIC+strImageURL);
      });
    }catch(exception){
      print('SharedProfile '+exception);
    }

  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: new Scaffold(
        backgroundColor: whiteColor,
        drawer: sideDrawer(),
        appBar: new AppBar(
          title: new Text('itsmee.'),
        ),
      ),
    );
  }
  
  //Profile Details
  Widget profileDetail() {
    return new DrawerHeader(
        child: new Column(
          children: <Widget>[
            new CircleAvatar(
              radius: 40,
              backgroundColor : blueColor,
              backgroundImage: new NetworkImage(Config.PROFILE_PIC+strImageURL),
            ),
          ],
        )
    );
  }

  //Side Drawer
  Widget sideDrawer(){
    return new Drawer(
      child: new ListView(
        children: <Widget>[
          new Center(
            child: profileDetail(),
          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('Requests'),
//          onTap: () => _onListTileTap(context),

          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('Reviews'),
//            onTap: () => _onListTileTap(context),
          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('Setting'),
//            onTap: () => _onListTileTap(context),
          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('Tip'),
//            onTap: () => _onListTileTap(context),
          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('Conditions'),
//            onTap: () => _onListTileTap(context),
          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('About Us'),
//            onTap: () => _onListTileTap(context),
          ),
          new ListTile(
            leading: new Icon(Icons.lightbulb_outline),
            title: new Text('Log Out'),
//            onTap: () => _onListTileTap(context),
          ),
        ],
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Cross-ref https://stackoverflow.com/questions/53799967/the-following-argumenterror-was-thrown-building-homedirty-state-homestate37?noredirect=1#comment94453513_53799967

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Bhavya-Budhia** [comment]
I am also facing same error. My console error output is 
```
Launching lib\main.dart on Nokia 5 1 Plus in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/GED     (22986): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
I/flutter (22986): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22986): The following ArgumentError was thrown building PriceScreen1(dirty, state: _PriceScreenState#94eab):
I/flutter (22986): Invalid argument(s)
I/flutter (22986):
I/flutter (22986): The relevant error-causing widget was:
I/flutter (22986):   PriceScreen1
[38;5;248mI/flutter (22986):[39;49m
I/flutter (22986):
I/flutter (22986): When the exception was thrown, this was the stack:
[38;5;244mI/flutter (22986): #0      List.[]  (dart:core-patch/array.dart:169:52)[39;49m
[38;5;248mI/flutter (22986): #1      _PriceScreenState.build[39;49m
[38;5;244mI/flutter (22986): #2      StatefulElement.build[39;49m
[38;5;244mI/flutter (22986): #3      ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter (22986): #4      StatefulElement.performRebuild[39;49m
[38;5;244mI/flutter (22986): #5      Element.rebuild[39;49m
[38;5;244mI/flutter (22986): #6      ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter (22986): #7      StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter (22986): #8      ComponentElement.mount[39;49m
I/flutter (22986): ...     Normal element mounting (115 frames)
[38;5;244mI/flutter (22986): #123    Element.inflateWidget[39;49m
[38;5;244mI/flutter (22986): #124    MultiChildRenderObjectElement.mount[39;49m
I/flutter (22986): ...     Normal element mounting (253 frames)
[38;5;244mI/flutter (22986): #377    Element.inflateWidget[39;49m
[38;5;244mI/flutter (22986): #378    Element.updateChild[39;49m
[38;5;244mI/flutter (22986): #379    RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mI/flutter (22986): #380    RenderObjectToWidgetElement.mount[39;49m
[38;5;244mI/flutter (22986): #381    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mI/flutter (22986): #382    BuildOwner.buildScope[39;49m
[38;5;244mI/flutter (22986): #383    RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mI/flutter (22986): #384    WidgetsBinding.attachRootWidget[39;49m
[38;5;244mI/flutter (22986): #385    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
I/flutter (22986): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

My file is also attached here which I am trying to run.
[price screen.txt](https://github.com/flutter/flutter/files/4690867/price.screen.txt)

This error happened quite suddenly. My file was running smoothly. I hot restart it and it started throwing this error.

**Comment by OmarYehiaDev** [comment]
> I am also facing same error. My console error output is
> 
> ```
> Launching lib\main.dart on Nokia 5 1 Plus in debug mode...
> √ Built build\app\outputs\apk\debug\app-debug.apk.
> I/GED     (22986): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 15, oppidx_max 15, oppidx_min 0
> I/flutter (22986): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter (22986): The following ArgumentError was thrown building PriceScreen1(dirty, state: _PriceScreenState#94eab):
> I/flutter (22986): Invalid argument(s)
> I/flutter (22986):
> I/flutter (22986): The relevant error-causing widget was:
> I/flutter (22986):   PriceScreen1
> �[38;5;248mI/flutter (22986):�[39;49m
> I/flutter (22986):
> I/flutter (22986): When the exception was thrown, this was the stack:
> �[38;5;244mI/flutter (22986): #0      List.[]  (dart:core-patch/array.dart:169:52)�[39;49m
> �[38;5;248mI/flutter (22986): #1      _PriceScreenState.build�[39;49m
> �[38;5;244mI/flutter (22986): #2      StatefulElement.build�[39;49m
> �[38;5;244mI/flutter (22986): #3      ComponentElement.performRebuild�[39;49m
> �[38;5;244mI/flutter (22986): #4      StatefulElement.performRebuild�[39;49m
> �[38;5;244mI/flutter (22986): #5      Element.rebuild�[39;49m
> �[38;5;244mI/flutter (22986): #6      ComponentElement._firstBuild�[39;49m
> �[38;5;244mI/flutter (22986): #7      StatefulElement._firstBuild�[39;49m
> �[38;5;244mI/flutter (22986): #8      ComponentElement.mount�[39;49m
> I/flutter (22986): ...     Normal element mounting (115 frames)
> �[38;5;244mI/flutter (22986): #123    Element.inflateWidget�[39;49m
> �[38;5;244mI/flutter (22986): #124    MultiChildRenderObjectElement.mount�[39;49m
> I/flutter (22986): ...     Normal element mounting (253 frames)
> �[38;5;244mI/flutter (22986): #377    Element.inflateWidget�[39;49m
> �[38;5;244mI/flutter (22986): #378    Element.updateChild�[39;49m
> �[38;5;244mI/flutter (22986): #379    RenderObjectToWidgetElement._rebuild�[39;49m
> �[38;5;244mI/flutter (22986): #380    RenderObjectToWidgetElement.mount�[39;49m
> �[38;5;244mI/flutter (22986): #381    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>�[39;49m
> �[38;5;244mI/flutter (22986): #382    BuildOwner.buildScope�[39;49m
> �[38;5;244mI/flutter (22986): #383    RenderObjectToWidgetAdapter.attachToRenderTree�[39;49m
> �[38;5;244mI/flutter (22986): #384    WidgetsBinding.attachRootWidget�[39;49m
> �[38;5;244mI/flutter (22986): #385    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>�[39;49m
> I/flutter (22986): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
> ```
> 
> My file is also attached here which I am trying to run.
> [price screen.txt](https://github.com/flutter/flutter/files/4690867/price.screen.txt)
> 
> This error happened quite suddenly. My file was running smoothly. I hot restart it and it started throwing this error.

Also me! I have the same issue and I can't fix it. If you fixed it please inform me ASAP
