### ISSUE TITLE
REQUEST: Flutter Cupertino Icon Source Files

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#25420]
The Cupertino icons library includes the icons as a font file. I would like to use the icons in SVG and PNG format. 

Is it possible for the source SVG files that were used to create the Cupertino font file to be made available?

https://github.com/flutter/cupertino_icons

**Comment by chunlea** [comment]
Maybe you can try https://geticonjar.com/, import this font and then you can export it to SVG or any other format you want.

**Comment by searchy2** [comment]
Thanks for the suggestion! Unfortunately, I'm on Windows and that software is only on Mac.
I do know how to export icons as SVGs but it would be nice to have access to the source files (and much easier!)

**Comment by searchy2** [comment]
Any update on where the source file is/if it can be made available?

**Comment by xster** [comment]
The ttf is just a selection from https://github.com/ionic-team/ionicons. You can likely find the source for individual icons there.

**Comment by searchy2** [comment]
Thank you very much!
