### ISSUE TITLE
PANIC: Broken AVD system path - incorrectly reporting when just one emulator is missing

### ISSUE THREAD

**Issue by anuhanovic** [flutter/flutter#25432]
@DanTup 
Danny,
Thank you for all your hard work. 
As you can see from the trace, one of my emulators is somehow messed up (problem for another day), but the error I got was very misleading. Just by chance I tried another emulator and it worked.

```
baseline$ flutter emulators
5 available emulators:

Android_ARMv7a
Android_Accelerated_x86
Nexus_5X_API_25_x86     • Nexus 5X      • Google • Nexus 5X API 25 x86
Pixel_2_XL_API_28       • pixel_2_xl    • Google • Pixel 2 XL API 28
apple_ios_simulator     • iOS Simulator • Apple

To run an emulator, run 'flutter emulators --launch <emulator id>'.
To create a new emulator, run 'flutter emulators --create [--name xyz]'.

You can find more information on managing emulators at the links below:
  https://developer.android.com/studio/run/managing-avds
  https://developer.android.com/studio/command-line/avdmanager

baseline$ flutter emulators --launch Android_Accelerated_x86

PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value
[/Users/baseline/Library/Android/sdk]!
baseline$ flutter emulators --launch Nexus_5X_API_25_x86
baseline$ WORKS!!
```

**Comment by DanTup** [comment]
@anuhanovic Unfortunately this message comes from the Android SDK so it's hard for us to provide a better one (we could easily detect it, but we don't know what to replace it with, because we don't know what the underlying issue is).

You can probably confirm this by calling `emulator` directly:

```
emulator -avd Android_Accelerated_x86
```

In which case, I think the message would really need improving in the Android SDK.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
