### ISSUE TITLE
Feature request: map taps listener and marker drag location update

### ISSUE THREAD

**Issue by AmitToren** [flutter/flutter#25439]
The plugin should listen to map clicks and send as a parameter to the listener the location tapped we can place a pin/marker there if wanted.

Also, the marker can be dragged but it doesn't update it's new location to the current placed one.

**Comment by ViniciusSossela** [comment]
There is some estimated date to has this done?

**Comment by lvlasuod** [comment]
still waiting for these feature, any news ?

**Comment by kiluange** [comment]
I need this feature to

**Comment by ferdigokdemir** [comment]
++

**Comment by Muhammad-saafan** [comment]
I need it badly :D

**Comment by nandymandy1** [comment]
I need it too i m in tight production schedule

**Comment by zoechi** [comment]
@nandymandy1 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by nandymandy1** [comment]
PR had just updated the Google maps flutter library but still unable to figure out how to use the onTap listener to place marker which is draggable.

**Comment by timtraversy** [comment]
This functionality was introduced in https://github.com/flutter/plugins/pull/985. Is there anything in this issue that hasn't been addressed?

**Comment by pedromassangocode** [comment]
Hi @AmitToren 
The "Map tap" feature is now implemented. 


> Also, the marker can be dragged but it doesn't update it's new location to the current placed one.

The Marker class has now a onDragEnd callback which provides you the latest position to where the marker was dragged, does that solves your issue?

Also that would be great to track the last one on a different issue as we don't track more that two problems in the same issue.

**Comment by AmitToren** [comment]
Yes, this does seem to solve the issue. I think the `onDragEnd` callback would be sufficient enough for solving the second issue. Appreciate it!

**Comment by pedromassangocode** [comment]
Hi @AmitToren 
Given your last message I feel safe to close this issue.
Thank you
