### ISSUE TITLE
Get Progress Event on Multipart Request

### ISSUE THREAD

**Issue by awazgyawali** [flutter/flutter#25444]
This might not be the right place to file this question but I searched answer in http package, asked a question on SO, added a bounty on it too, asked on gitter,  but sadly I got no reply. This might become a feature request. Of course, I should have filed this request on http package repository, but I found this there https://github.com/dart-lang/http/issues/153.

If it is possible to get a progress report now, please take a look at this question https://stackoverflow.com/questions/53727911/how-to-get-progress-event-while-uploading-file-on-http-multipartrequest-request.

Thanks in advance!!!

**Comment by zoechi** [comment]
Flutter and `http` depend on `dart:io` so https://github.com/dart-lang/sdk is the right place.

**Comment by awazgyawali** [comment]
Thanks @zoechi for the direction, I will file an issue there.

**Comment by awazgyawali** [comment]
After waiting for a week or soo for an answer, I created a plugin to get this behavior. Package https://pub.dartlang.org/packages/multipart_request.

Example to use it:

```
var request = MultipartRequest();

request.addFile("image", imagePath);

Response response = request.send();

response.onError = () {
  print("Error");
};

response.onComplete = (response) {
  print(response);
};

response.progress.listen((int progress) {
  print("progress from response object " + progress.toString());
});

```
Works only on android.

**Comment by ajayEtelligens** [comment]
@awazgyawali your package is having timeout issue for large file upload. Please see the below response.

`W/System.err(27293): javax.net.ssl.SSLException: Write error: ssl=0x76415dbe88: I/O error during system call, Connection reset by peer
W/System.err(27293): 	at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
W/System.err(27293): 	at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
W/System.err(27293): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:626)
W/System.err(27293): 	at okio.Okio$1.write(Okio.java:79)
W/System.err(27293): 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
W/System.err(27293): 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
W/System.err(27293): 	at okio.RealBufferedSink.write(RealBufferedSink.java:42)
W/System.err(27293): 	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
W/System.err(27293): 	at okio.ForwardingSink.write(ForwardingSink.java:35)
W/System.err(27293): 	at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
W/System.err(27293): 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
W/System.err(27293): 	at okio.RealBufferedSink.write(RealBufferedSink.java:42)
W/System.err(27293): 	at okio.ForwardingSink.write(ForwardingSink.java:35)
W/System.err(27293): 	at com.brainants.multipartrequest.ProgressRequestBody$CountingSink.write(ProgressRequestBody.java:55)
W/System.err(27293): 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
W/System.err(27293): 	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:107)
W/System.err(27293): 	at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
W/System.err(27293): 	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
W/System.err(27293): 	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
W/System.err(27293): 	at com.brainants.multipartrequest.ProgressRequestBody.writeTo(ProgressRequestBody.java:44)
W/System.err(27293): 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(27293): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(27293): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(27293): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(27293): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(27293): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(27293): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
W/System.err(27293): 	at okhttp3.RealCall.execute(RealCall.java:93)
W/System.err(27293): 	at com.brainants.multipartrequest.MultipartRequest.sendMultipartRequest(MultipartRequest.java:43)
W/System.err(27293): 	at com.brainants.multipartrequest.MultipartRequestPlugin$1.doInBackground(MultipartRequestPlugin.java:43)
W/System.err(27293): 	at com.brainants.multipartrequest.MultipartRequestPlugin$1.doInBackground(MultipartRequestPlugin.java:38)
W/System.err(27293): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err(27293): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(27293): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err(27293): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(27293): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(27293): 	at java.lang.Thread.run(Thread.java:919)`
