### ISSUE TITLE
FirebaseAdMobPlugin <warning> [FIRApp configure]

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25449]
### Warning

I am having this warning in my terminal when my app runs. 
`FirebaseAdMobPlugin <warning> [FIRApp configure]
`

### Crash
However, when I add following lines in my `AppDelegate.m` file

`    [FIRApp configure];  // added this 
`

Then the app crashes with the error
`Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'`

### PodFile
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/AdMob'	


# CocoaPods analytics sends network stats synchronously affecting flutter build latency. ...
```

After this, I did pod install, and the pods were installed successfully. 

### Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by dark-chocolate** [comment]
Here is the screenshot, now you can see warning and error both at the same time. This is very surprising. 

<img width="932" alt="screenshot 2018-12-18 at 8 29 41 am" src="https://user-images.githubusercontent.com/40364434/50168796-1b265d00-02a1-11e9-98da-f41b7c844808.png">

**Comment by SachinGanesh** [comment]
Remove **GoogleService-Info.plist** file from the project and add it through XCode (right click on Runner and then Add Files...)

Source: https://github.com/flutter/flutter/issues/16871#issuecomment-383512995

**Comment by dark-chocolate** [comment]
@SachinGanesh  Thanks but this is how I added it. But again I deleted the file and added it using Right click runner, add files ... but still it shows the same warning, and the link you mentioned is for the issue when the app is crashing, my app doesn't crash, it works fine, ads are also shown and everything is working as expected but still the warning persist.

**Comment by shadimac** [comment]
@dark-chocolate have you found any solution to this yet? Removing and adding GoogleService-Info.plist didn't work for me.

**Comment by shadimac** [comment]
So here is an update, I have used a default Info.plist file, but that didn't work for me, then I came to this recommended line to be added to AppDelegate.m and commented it out: 

`//[FIRApp configure];` 

that's it, the crash is gone, and still, I can use all the Firestore functions to access my Cloud Firestore collections and documents.

**Comment by dark-chocolate** [comment]
@shadimac Basically you simply commented out the line like this
```
//[FIRApp configure];
```

That actually means you are not configuring Firebase which docs suggest you to do by including above code. Sorry I didn't really get your solution.

**Comment by shadimac** [comment]
@dark-chocolate it is not a solution, I was just trying to see what would happen if I did that, but as I said I can use firebase libs and function to retrieve and post data to my cloud Firestore "after commenting that line", but still I need a solution.

**Comment by dark-chocolate** [comment]
Today I updated my Android Studio to 3.3.2 and it started showing 

```
Configuring the default Firebase app...
Configured the default Firebase app __FIRAPP_DEFAULT.
```

**Comment by kroikie** [comment]
@dark-chocolate

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/539. Any further collaboration will be done there.

**Comment by dark-chocolate** [comment]
@kroikie I don't understand why issues are moved to different thread.
