### ISSUE TITLE
keyboardType: TextInputType.number shows decimal

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25454]
### Bug

I am using `keyboardType: TextInputType.number`

And the docs say that it doesn't include decimal point. But I am seeing decimal, tested on emulator, simulator and iPhone 6s Real device. 

I even tried the other way

`keyboardType: TextInputType.numberWithOptions(decimal: false),`

That didn't help either. 

So, it's a bug that needs to be fixed. 

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

### Devices 
Simulator (12.1.0)
Emulator (API 27)
iPhone 6s (12.0.1)

All devices are using default keyboard app provided by their platform

**Comment by HansMuller** [comment]
The Android version of the gallery demos this problem as well. The Text fields demo includes a phone number field, for which `keyboardType` is `TextInputType.phone`: https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart#L210:

![screenshot](https://user-images.githubusercontent.com/1377460/50104947-32514600-01e0-11e9-94ad-0e06032410b1.png)

Here's the (Android) phone displaying the "phone number" keyboard from the native calling app:

![native](https://user-images.githubusercontent.com/1377460/50104960-39785400-01e0-11e9-81d9-9a68e1abb4c4.png)

**Comment by justinmc** [comment]
@HansMuller It looks like we're actually doing it right on Android.  The keyboard in your first screenshot is the native Android "phone" input according to the [Android input method docs](https://developer.android.com/training/keyboard-input/style).  I think the dialer in the phone app is using something custom.  See this StackOverflow question: https://stackoverflow.com/questions/33639853/how-to-show-phone-type-soft-keyboard-on-android

However, this definitely does appear to be a bug in the iOS part of the engine.  I'll put up a PR for that shortly.

**Comment by justinmc** [comment]
The iOS behavior with the above PR should match the docs and Android, so:

  * `keyboardType: TextInputType.number`
    - UIKeyboardTypeNumberPad
  * `keyboardType: TextInputType.numberWithOptions(decimal: true)`
    - UIKeyboardTypeDecimalPad
  * `keyboardType: TextInputType.numberWithOptions(signed: true)`
    - UIKeyboardTypeNumbersAndPunctuation

**Comment by goderbauer** [comment]
@justinmc We currently don't use UIKeyboardTypeNumberPad, but we should. See here:

https://github.com/flutter/engine/blob/1a2714bbefd3c7665258c20cbef7fe2f2a5805d9/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L13-L31

**Comment by silexcorp** [comment]
This code work for me: inputFormatters: [ BlacklistingTextInputFormatter(RegExp("[.]")) ],

**Comment by omidraha** [comment]
I have the same issue with:

`Emulator: Pixel 2 API 30 Android 11`

I also try this:

`inputFormatters: [FilteringTextInputFormatter.deny(RegExp("[.]"))],`

After deprecated this one:

`inputFormatters: [ BlacklistingTextInputFormatter(RegExp("[.]")) ],`


![flutter_25454](https://user-images.githubusercontent.com/397672/118598939-0dec6000-b7c4-11eb-9156-1bc7407a56e5.png)

Info:
```
$ flutter doctor --verbose
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.6 at /***/sdk/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /***/sdk/android/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /***/sdk/android/
    • Java binary at: /***/ide/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /***/ide/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /***/ide/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64   • Linux

! Doctor found issues in 1 category
```

**Comment by l-k22** [comment]
Would be very handy if you could also disable negative numbers too.
