### ISSUE TITLE
Flutter Driver - interacting with other apps (Safari as an example)

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#25465]
We would like to be able to interact with other apps (third party and system) with Flutter Driver so we can write end to end tests that involve other apps. The main use case for this being deep links from Safari or other apps on the device.

**Comment by abanv2** [comment]
Hello, does this also cover native UI system dialogs (for example, iOS Bluetooth Pairing alert dialog and Android Permissions dialog) ? 
Thank you.

**Comment by truongsinh** [comment]
related https://github.com/google/EarlGrey/issues/778

**Comment by MisterJimson** [comment]
@snickersv2 very related, not sure if it will end up being tacked in the same issue.

**Comment by jamesdixon** [comment]
Hi all, any update on this?

Our app utilizes a handful of packages that use native plugins (image_picker, etc) and at this point, we can't test those via `flutter_driver`. 

I was hoping for some sort of hack where we might just be able simulate a tap on screen at a specific location to interact with the native ui but haven't see a way to do that yet. Thoughts?

**Comment by MisterJimson** [comment]
@jamesdixon a simulated tap at specific locations would be a great simple fix to get around this issue. Would be great if Flutter Driver supported that.

**Comment by jamesdixon** [comment]
@jmagman I realize this isn't the same exact issue, but you ran into a similar problem in #65217. Any update on support for flutter driver tests to interact with system ui?

**Comment by jamesdixon** [comment]
also, related/unrelated, but what is the difference between Flutter's built-in integration tests using `flutter drive` and the `integration_test` package?

**Comment by jmagman** [comment]
`integration_test` is a UI testing plugin, and for iOS leverages `XCUITest`.  You can read about it at https://github.com/flutter/plugins/tree/master/packages/integration_test.

And you can indeed interact natively with other apps via `XCUIApplication(bundleIdentifier:)`

**Comment by MisterJimson** [comment]
@jmagman after reading that readme its not immediately clear the boundary of responsibility between integration_test and flutter driver.

Looking at that readme the small example code and setup seem similar to just using flutter driver. Is there somewhere I can read about the differences and when exactly I would need to use `integration_test.`?

**Comment by jmagman** [comment]
I'll let @dnfield field this as a request for documentation, I don't know the details of that plugin really, other than that it runs native UI tests, not just driving dart.

**Comment by jamesdixon** [comment]
@jmagman @dnfield yes, additional info would be amazing. In another thread, @Hixie had mentioned flutter driver being deprecated. Curious if this is the successor.

**Comment by dnfield** [comment]
Flutter driver does not directly support native UI interaction, and there are no plans to add that as a feature.

You can, in your host side part of the test, shell out commands to other things, e.g. running `adb` on Android or `xcrun` or some `libimobiledevice` command(s) for iOS.

EarlGrey for Flutter will also soon be an option - we have some engineers working on releasing that imminently.

The main problem here is, of course, synchronization. There are existing native testing frameworks that handle this synchronization; trying to make it part of flutter_driver would be a huge effort and likely not to really work all that well.

**Comment by dnfield** [comment]
The successor is `package:integration_test`.

However, support for native UI interaction is very limited there, and if you need to do more native UI interaction you should look at using `package:espresso` on Android or `package:early_grey` (to be published soon) on iOS.

**Comment by jamesdixon** [comment]
Thanks, @dnfield. Can you speak to the limitations of native UI interaction in the `integration_test` package?

**Comment by dnfield** [comment]
There is not really a good story around that right now - it should technically be possible, but would involve setting up your own message channels to talk back and forth. If you really want to do this kind of native UI testing, you'll want one of the native test platforms such as espresso or earl grey.

**Comment by andreashaese** [comment]
> EarlGrey for Flutter will also soon be an option - we have some engineers working on releasing that imminently.

@dnfield do you have any updates or ETA for this?

**Comment by pokapow** [comment]
I'm this feature is very import for integration testing (tap on absolute position of screen to interact with other apps).

@dnfield Could you please give an exemple to how do that with adb ?

**Comment by dnfield** [comment]
We do that in our driver tests in a few places, for example here: 

https://github.com/flutter/flutter/blob/3df0f931faf805c555dae2fb85bfe5aed0d6604b/dev/devicelab/bin/tasks/flutter_gallery__back_button_memory.dart#L35

Which is just doing `adb shell input keyevent KEYCODE_BACK`, but could just as easily be something like `adb shell input tap  50 100` (see also: https://stackoverflow.com/questions/3437686/how-to-use-adb-to-send-touch-events-to-device-using-sendevent-command).

**Comment by andreashaese** [comment]
Thanks @dnfield. We're also currently exploring the option to add new features to our existing iOS and Android apps using Flutter.

Full integration testability is a requirement, and I was happy to see that Espresso supports Flutter on Android, but now we're waiting on EarlGrey's Flutter integration to start our experiments. @AlbertWang0116 can you share when this will likely become available?
