### ISSUE TITLE
BottomNavigationBar does't not work with notched FloatingActionButton

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#25467]
When using a BottomNavigationBar inside a BottomAppBar, the notch does not work.

This is the code:

```dart
Scaffold(
        body: Container(),
        floatingActionButton: FloatingActionButton(
          onPressed: null,
          child: Icon(Icons.close),
        ),
        bottomNavigationBar: BottomAppBar(
          shape: CircularNotchedRectangle(),
          color: Colors.red,
          notchMargin: 4,
          child: BottomNavigationBar(items: [
            BottomNavigationBarItem(icon: Icon(Icons.cancel), title: Text("Title")),
            BottomNavigationBarItem(icon: Icon(Icons.cancel), title: Text("Title")),
            BottomNavigationBarItem(icon: Icon(Icons.cancel), title: Text("Title")),
          ]),
        ),
        floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      )

```

This is the result:

![image](https://user-images.githubusercontent.com/1146982/50101437-d4d1ef00-0209-11e9-9da0-37ee1faa2e62.png)

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17134.471], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] Connected device (1 available)

• No issues found!

```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by shinayser** [comment]
Hey Zoechi! Actually it is not a question. I am reporting this cuz I consider it a wrong behavior. But if you think this is the correct behavior, fell free to close the issue.

**Comment by zoechi** [comment]
Not my call, but it's usually a good idea to ask on StackOverflow first.
If it turns out to be a bug or missing feature it's fine of course to create an issue.
Response time here is usually longer though.

**Comment by johnsonmh** [comment]
Hi, you can get the shape of the `BottomAppBar` and it's children to be fully enforced by specifying `clipBehavior: Clip.antiAlias,` on the `BottomAppBar`.

For example, the sample you posted above:

```
Scaffold(
          body: Container(),
          floatingActionButton: FloatingActionButton(
            onPressed: null,
            child: Icon(Icons.close),
          ),
          bottomNavigationBar: BottomAppBar(
            shape: CircularNotchedRectangle(),
            color: Colors.red,
            notchMargin: 4,
            clipBehavior: Clip.antiAlias,
            child: BottomNavigationBar(items: [
              BottomNavigationBarItem(icon: Icon(Icons.cancel), title: Text("Title")),
              BottomNavigationBarItem(icon: Icon(Icons.cancel), title: Text("Title")),
              BottomNavigationBarItem(icon: Icon(Icons.cancel), title: Text("Title")),
            ]),
          ),
          floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
        )
```

Yields:

<img width="343" alt="Screen Shot 2019-04-17 at 11 46 59 PM" src="https://user-images.githubusercontent.com/4229329/56335607-2617ce00-616b-11e9-88e2-0aef5c8c889a.png">

I'm closing this issue, feel free to follow up/reopen if this does not work for you.

**Comment by jagomf** [comment]
@johnsonmh actually you cannot use a `BottonNavigationBar` as a child of `Scaffold`'s `BottomAppBar` unless you want a really ugly effect of such bar being somehow 'isolated' inside the other one due to `SafeArea` in a modern iPhone:

![wrongbar](https://user-images.githubusercontent.com/4032522/83561003-6543e280-a517-11ea-81a4-81d3523d52b8.png)

Which goes even worse in landscape:

![wrongbar2](https://user-images.githubusercontent.com/4032522/83561579-5ad61880-a518-11ea-8a98-2ba3a1094cdb.png)

So how to actually leverage a `BottomNavigationBar` with a `CircularNotchedRectangle()` at the bottom of a `Scaffold`?

**Comment by tonypottera24** [comment]
This does not work on iPhone 11 simulator.
There will be a gap between the screen and BottomNavigationBar

**Comment by AleksandarSavic95** [comment]
@johnsonmh's solution does get the notch displayed, but it has some nasty issues.
If you try adding one more item, it messes up, so you have to set color inside the `BottomNavigationBar` again.
Also, all navigation items except the first one are lower than the first one, and their labels are not inside the screen.
![image](https://user-images.githubusercontent.com/12213798/94682513-57676800-0325-11eb-953e-a481ae32bda0.png)

I suggest using a solution with a custom navbar items, such as [this one from Andrea Bizzotto on Medium](https://medium.com/coding-with-flutter/flutter-bottomappbar-navigation-with-fab-8b962bb55013).
