### ISSUE TITLE
Incorrect documentation for RewardedVideoAd (Syntax error)

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25464]
I am using firebase_admob for showing ads, both banner and interstitial worked but when I was implementing the RewardedVideoAds, I got syntax error. 

### Code (From Docs)
```dart
RewardedVideoAd.instance.listener =
    (RewardedVideoAdEvent event, [String rewardType, int rewardAmount]) {
  if (event == RewardedVideoAdEvent.rewarded) {
    setState(() {
      // Here, apps should update state to reflect the reward.
      _goldCoins += rewardAmount;
    });
  }
};
```

### Code (My own)
This minimises above code to reflect the error. (Both code shows syntax error)
```dart
void loadVideoAd() {
  RewardedVideoAd.instance.listener = (RewardedVideoAdEvent event, [String rewardType, int rewardAmount]) {
    if (event == RewardedVideoAdEvent.rewarded) {}
  };
}
```

### Syntax Error
A value of type `(RewardedVideoAdEvent, [String, int]) -> Null` can't be assigned to a variable of type `(RewardedVideoAdEvent, {rewardType: String, rewardAmount: int}) -> void`

<img width="1540" alt="screenshot 2018-12-17 at 9 45 08 pm" src="https://user-images.githubusercontent.com/40364434/50099851-116f0c00-0245-11e9-9d89-b3801d217054.png">

### Feedback
The documentation for RewardedVideoAd is very poor. They also have syntax error. Probably the docs have not been updated since long.

**Comment by zoechi** [comment]
I see. Then let's reopen so that it will be updated.

**Comment by kroikie** [comment]
@dark-chocolate

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/538. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
