### ISSUE TITLE
High dimension image in re-render in ListView while scroll up/down

### ISSUE THREAD

**Issue by nirav4273** [flutter/flutter#25469]
Inside `ListView` i am generated 10 widgets using builder.
 In `Image.asset` when scroll fast up/down image look wired for high dimension image. Like `1440*2560` dimension. Take some time to appear.
It's working fine with `603*328` dimension .

Dimension : 603*328
![ezgif com-resize 1](https://user-images.githubusercontent.com/22423754/50101735-60b73b80-0249-11e9-9e87-fa4d3c54ca74.gif)

Dimension : 1440*2560
![ezgif com-resize 2](https://user-images.githubusercontent.com/22423754/50101689-43826d00-0249-11e9-8503-f271008d5c53.gif)

>Here is my code : https://github.com/nirav4273/flutter-asset-image-issue
>Both type of images already inside code & `ListView.builder` as well.

>Flutter details.
```
Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.3.9600], locale en-IN)
    • Flutter version 1.0.0 at E:\Android\sdk\flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

```

**Comment by zoechi** [comment]
Seems related to #2848, #26194

**Comment by iskakaushik** [comment]
This can be addressed by https://github.com/flutter/flutter/issues/26194. For reasons why this is happening please look at https://github.com/flutter/flutter/issues/28682.
