### ISSUE TITLE
flutter_gallery__transition_perf and flutter_gallery__transition_perf_with_semantics are flaky

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#25481]
See flutter-dashboard.appspot.com/build.html

They became quite flaky at least since commit 46878d8. Maybe the flakiness is caused by some earlier commits.

**Comment by HansMuller** [comment]
One consistent source of flakiness in these benchmarks (at the moment)  is the gallery demo. Added some instrumentation to see if we can narrow down the source of the problem here: https://github.com/flutter/flutter/pull/25489

**Comment by dnfield** [comment]
This inexplicably resolved itself. 

Feel free to reopen if you think there's something we can follow up on here.
