### ISSUE TITLE
Error dialog on exit for all (?) Flutter apps

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2549]
### Steps to Reproduce

* Make an app with flutter create
* Launch app with flutter run
* Kill app using back button
* "Unfortunately, [app name] has stopped." dialog appears

![screen](https://cloud.githubusercontent.com/assets/394889/13652607/e69205a8-e601-11e5-9f44-971cf29f6c35.png)

### Flutter Version

Flutter from git@github.com:flutter/flutter (on master)
Framework: 778c3a05b177359068d851cc3a69c668f3311d6d (22 minutes ago)
Engine:    8514a14911269e405784ca90ba082407d260fbf3

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.

I tested on a Nexus 4 and a Nexus 9.

### Logs

    /Keyboard.Facilitator( 1266): onFinishInput()
    D/audio_hw_primary(  283): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
    D/CordovaActivity( 6913): Resuming the App
    D/CordovaLog( 6913): : Line 1 : exception firing resume event from native
    I/chromium( 6913): [INFO:CONSOLE(1)] "exception firing resume event from native", source:  (1)
    D/cr_Ime  ( 6913): [ImeAdapter.java:140] onCreateInputConnection returns null.
    W/InputMethodManagerService(  751): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@bc438a3 (uid=10117 pid=26691)
    I/Keyboard.Facilitator( 1266): onFinishInput()
    I/ActivityManager(  751): Killing 25603:com.google.android.apps.docs.editors.docs/u0a43 (adj 15): empty #17
    --------- beginning of crash
    F/libc    (26691): Fatal signal 6 (SIGABRT), code -6 in tid 26712 (ui_thread)
    I/DEBUG   (  280): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    I/DEBUG   (  280): Build fingerprint: 'google/hammerhead/hammerhead:5.1.1/LMY48E/1928976:userdebug/dev-keys'
    I/DEBUG   (  280): Revision: '11'
    I/DEBUG   (  280): ABI: 'arm'
    I/DEBUG   (  280): pid: 26691, tid: 26712, name: ui_thread  >>> com.yourcompany.foo <<<
    I/DEBUG   (  280): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    W/ResourceType( 1098): No package identifier when getting value for resource number 0x00000000
    W/PackageManager( 1098): Failure retrieving resources for com.yourcompany.foo: Resource ID #0x0
    I/DEBUG   (  280):     r0 00000000  r1 00006858  r2 00000006  r3 00000000
    I/DEBUG   (  280):     r4 af2bcdb8  r5 00000006  r6 00000002  r7 0000010c
    I/DEBUG   (  280):     r8 af2bb8dc  r9 000000b7  sl b4afaa01  fp af2bc9a4
    I/DEBUG   (  280):     ip 00006858  sp af2bb868  lr b6d883c5  pc b6dab770  cpsr 680b0010
    I/DEBUG   (  280): 
    I/DEBUG   (  280): backtrace:
    I/DEBUG   (  280):     #00 pc 0003a770  /system/lib/libc.so (tgkill+12)
    I/DEBUG   (  280):     #01 pc 000173c1  /system/lib/libc.so (pthread_kill+52)
    I/DEBUG   (  280):     #02 pc 00017fd3  /system/lib/libc.so (raise+10)
    I/DEBUG   (  280):     #03 pc 00014795  /system/lib/libc.so (__libc_android_abort+36)
    I/DEBUG   (  280):     #04 pc 00012f44  /system/lib/libc.so (abort+4)
    I/DEBUG   (  280):     #05 pc 000e5d27  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #06 pc 0053adf7  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #07 pc 00349a57  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so (Dart_DeletePersistentHandle+98)
    I/DEBUG   (  280):     #08 pc 00323603  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #09 pc 00323633  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #10 pc 003215d3  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #11 pc 00569e85  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #12 pc 00569ead  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #13 pc 00568093  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #14 pc 0030a965  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #15 pc 0030a9ad  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #16 pc 000b5ba1  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #17 pc 000b5c71  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #18 pc 000d4b4b  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #19 pc 000c46df  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #20 pc 000c4b79  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #21 pc 000c4f09  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #22 pc 000e4d8d  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #23 pc 000e4e63  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #24 pc 000c7a8d  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #25 pc 000c40e5  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #26 pc 000cf60d  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #27 pc 000ceaf5  /data/app/com.yourcompany.foo-1/lib/arm/libsky_shell.so
    I/DEBUG   (  280):     #28 pc 00016baf  /system/lib/libc.so (__pthread_start(void*)+30)
    I/DEBUG   (  280):     #29 pc 00014af3  /system/lib/libc.so (__start_thread+6)
    W/debuggerd(  280): type=1400 audit(0.0:11): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    W/debuggerd(  280): type=1400 audit(0.0:12): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    W/debuggerd(  280): type=1400 audit(0.0:13): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    W/debuggerd(  280): type=1400 audit(0.0:14): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    W/debuggerd(  280): type=1400 audit(0.0:15): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    W/debuggerd(  280): type=1400 audit(0.0:16): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    W/debuggerd(  280): type=1400 audit(0.0:17): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=6032 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
    I/DEBUG   (  280): 
    I/DEBUG   (  280): Tombstone written to: /data/tombstones/tombstone_07
    I/BootReceiver(  751): Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
    W/ActivityManager(  751): Process com.yourcompany.foo has crashed too many times: killing!
    I/ActivityManager(  751): Killing 26691:com.yourcompany.foo/u0a117 (adj 9): crash
    I/Zygote  (  295): Process 26691 exited due to signal (6)
    W/ActivityManager(  751): Spurious death for ProcessRecord{284d9815 26691:com.yourcompany.foo/u0a117}, curProc for 26691: null

**Comment by jason-simmons** [comment]
This is happening in the DartController destructor.  We shut down the Dart isolate and then delete UIDartState.

The UIDartState holds Dart persistent handles which are deleted at destruct time.  The deletion is failing an assertion because the isolate no longer exists.

I'm not sure if something changed recently or if this was always broken.

This state should be cleaned up before the isolate disappears.  Maybe in the isolate shutdown callback?

**Comment by abarth** [comment]
Probably caused by the factoring of FlutterDartState from UIDartState.  This class has some tricky shutdown logic.  The key is to clear the persistent handles before shutting down the isolate.  There used to be some mechanism for that.  If it was lost, we might need to resurrect it.
