### ISSUE TITLE
Re-enable gridpaper debug mode

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#255]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 22:10 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1931_

----

**Comment by Hixie** [comment]
Instead of a flag, I'm going to change GridPaper to a class that takes a child and draws the grid on top (defaulting it to slightly transparent). That way if you want to enable it you just wrap whatever you want the grid on with the widget and you're done.
