### ISSUE TITLE
Replace keyboardType to textInputType

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#25501]
When working with TextField and we need to define the input type the parameter name is different from the class name that we should pass.

My suggestion is that if we should pass a `TextInputType` value, the parameter name should be the same (`textInputType` or `inputType`).

Actual 
```dart
TextField(
    keyboardType: TextInputType.multiline,
)
```

**Should be something like:**
```dart
TextField( 
    inputType: TextInputType.multiline,
)
```
**Or:**
```dart
TextField( 
    textInputType: TextInputType.multiline,
)
```

This is to help us to remember the parameter values of a given class.

**Comment by justinmc** [comment]
@pedromassango I agree with you that this would make things a bit more intuitive, but unfortunately Flutter isn't open to breaking changes right now.  A significant goal of the project is backwards compatibility, so have to accept that we're going to run into naming problems like this occasionally.

I'm going to close this for now, but I'll add this to my list of issues to keep in mind for the future if we start considering breaking changes, and I promise to advocate for it.  Thanks for bringing attention to this and sorry for the disappointing answer!

**Comment by pedromassango** [comment]
Thank you for the answer. waiting to see the changes on te future versions of Flutter.
