### ISSUE TITLE
Firebase auth not retrieving displayName on iOS

### ISSUE THREAD

**Issue by DK15** [flutter/flutter#25504]
I recently implemented retrieving `displayName` using `firebase auth` which works perfectly on Android, but when I tried it on iOS, I observed that `displayName` disappears if I navigate back and forth in UI.

Example:  I've`edit profile` screen where user can edit / update their name and tapping on `save` button, `updateProfile()` is called and snackbar is displayed with confirmation message. If I go back to previous screen which is a read-only profile screen with edit button, it displays the `displayName` properly. When I hit edit button, the updated `displayName` is being fetched properly and displayed, but if I again go back to previous screen, then the `displayName` is gone. Tapping on edit button to go to edit profile screen also now doesn't retrieve and display the `displayName`.

**Steps to reproduce (iOS) :**

1. Edit profile screen, update display name and tap save.

![screen shot 2018-12-18 at 5 05 13 pm](https://user-images.githubusercontent.com/16548367/50151554-3d42ce00-02e7-11e9-80a3-bb5c9279151e.png)

2. Hit back button which opens `read-only profile screen` and shows the updated display name:

![screen shot 2018-12-18 at 5 08 39 pm](https://user-images.githubusercontent.com/16548367/50151685-99a5ed80-02e7-11e9-91a3-6dddefe4b876.png)

3. Hit `edit` button which takes user towards `edit profile` screen which shows the retrieved `display name` correctly.

![screen shot 2018-12-18 at 5 10 48 pm](https://user-images.githubusercontent.com/16548367/50151783-e7225a80-02e7-11e9-8ab3-f4cbaf4eea2b.png)

4. Hit back button again and observe that `displayName` is not coming up.

![screen shot 2018-12-18 at 5 12 21 pm](https://user-images.githubusercontent.com/16548367/50151858-218bf780-02e8-11e9-9938-7bd1894286cd.png)

5. Hit `edit` button again and observe that display name is not being fetched.

![screen shot 2018-12-18 at 5 13 19 pm](https://user-images.githubusercontent.com/16548367/50151903-3e282f80-02e8-11e9-8794-2bf249635516.png)

**Code:**

```dart
// load current displayname from firebase
  void _loadDisplayName() async {
    FirebaseAuth auth = FirebaseAuth.instance;

    FirebaseAuth.instance.currentUser().then((val) async {
      UserUpdateInfo updateUser = UserUpdateInfo();
      updateUser.displayName = _nameController.text;
      auth.updateProfile(updateUser);
      await val.reload();
      setState(() {
        _nameController.text = val.displayName;
      });
    });
  }
```

**Code `onTap` save button:**

 ```dart
         onTap: () {
            if (_formKey.currentState.validate()) {
              FirebaseAuth auth = FirebaseAuth.instance;

              FirebaseAuth.instance.currentUser().then((val) async {
                UserUpdateInfo updateUser = UserUpdateInfo();
                updateUser.displayName = _nameController.text;
                auth.updateProfile(updateUser);
                String name = await val.displayName;
                setState(() {
                  name = val.displayName;
                });
              });
              showConfirmation();
            } else {
              setState(() {
                _validate = true;
              });
            }
          },
```

Above behavior works properly on Android.

**Flutter Doctor:**
```
[✓] Flutter (Channel beta, v0.11.10, on Mac OS X 10.13.2 17C88, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

```
#Firebase authentication plugin
  firebase_auth: "^0.5.11"
```

**Comment by kroikie** [comment]
@DK15

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/536. Any further collaboration will be done there.
