### ISSUE TITLE
image_picker: add multiple images picking

### ISSUE THREAD

**Issue by I-am-original** [flutter/flutter#25508]
Hi guys.

One more option as a valuable update in image_picker plugin.
It would be cool to have multiple image picking option
For now - on long press we have selection of image and selected count in AppBar. Looks like default behavior. But multiple image picking disabled. 

Please let me know if it is possible.
Thanks

**Comment by zoechi** [comment]
There are several plugins available that seem to provide that functionality

https://pub.dartlang.org/packages?q=image+picker

- https://pub.dartlang.org/packages/multi_image_picker
- https://pub.dartlang.org/packages/flutter_multiple_image_picker
- https://pub.dartlang.org/packages/custom_multi_image_picker
- https://pub.dartlang.org/packages/multiple_image_picker
...

**Comment by I-am-original** [comment]
@zoechi usage of other packages - is an option, but I like your approach more )

**Comment by zoechi** [comment]
Duplicate of #16054

**Comment by lifenautjoe** [comment]
Tested all those pickers plus https://pub.dev/packages/photo_manager and https://pub.dev/packages/photo.

They're either incomplete (image only, no video) or buggy and created by uninterested maintainers. 

iOS and Android both natively support multi-media picking, is it really that hard to support it as part of the official media picking library?

The functionality is there already, just restricted to a single file...

![android-support](https://user-images.githubusercontent.com/12737509/63846950-1a47de00-c98d-11e9-9ee9-996ebf5967de.gif)

**Comment by rgodlontonshaw** [comment]
All the multi-picker libs are super buggy.

**Comment by zinwalin** [comment]
can't imagine flutter doesn't provide a decent multi image picker officially.
