### ISSUE TITLE
image_picker: Add Cancel option in iOS version 

### ISSUE THREAD

**Issue by I-am-original** [flutter/flutter#25502]
Hi guys. I have an issue with file picking on iOS.
Actually there is no way to Cancel image picking and close picker view. 
Is it possible to do that? Should not be so hard.

Thanks

**Comment by kika** [comment]
It has a Cancel button in both `ImageSource.gallery` and `ImageSource.camera` modes:

![img_0002](https://user-images.githubusercontent.com/207889/50405729-db161d00-076d-11e9-92c9-b10bb6961ba8.jpg)
![img_0001](https://user-images.githubusercontent.com/207889/50405732-dea9a400-076d-11e9-87da-5a37d43899b3.jpg)

**Comment by I-am-original** [comment]
@kika looks like it depends on theme configs. Because in my case it was not visible/absent

**Comment by kika** [comment]
My theme only customizes colors, I didn't do any other customizations.

**Comment by knaoe** [comment]
I got same situation in debug debug. But it resolved in release build. (iPhone-XS Max, iOS 12.1.2)

**Comment by callumclift** [comment]
I'm having a similar issue here also, when you first use the image picker and request permissions for the first time it does not allow the user to cancel from within the gallery on iOS. This only fixes when you manually go into the app settings and disable then re-enable the camera which isn't really ideal. Is anyone looking into a fix for this?

**Comment by cyanglaz** [comment]
This is fixed with https://github.com/flutter/plugins/pull/1372
Closing the issue.
