### ISSUE TITLE
video_player iOS file formats

### ISSUE THREAD

**Issue by I-am-original** [flutter/flutter#25503]
Hi guys. I have found, that not all video formats are used for iOS.
On Android I have checked .mp4 .mkv .flv video formats. While on iOS only .mp4 working fine.

Please let me know if it is an issue and If it is in plans.

Thanks

**Comment by zoechi** [comment]
#13909 might be related.

**Comment by zoechi** [comment]
I think the formats listed in

- iOS https://developer.apple.com/documentation/avfoundation/avfiletype should be supported
- Android https://google.github.io/ExoPlayer/supported-formats.html

should work with the plugin

**Comment by I-am-original** [comment]
Thanks @zoechi 
Got is

**Comment by zoechi** [comment]
@I-am-original can this issue be closed then or is there still anything left for the Flutter team to do?

**Comment by I-am-original** [comment]
@zoechi it is more clear for now. Thanks. It can be closed

**Comment by lucasromanojf** [comment]
So, HLS is not supported on iOS?
