### ISSUE TITLE
CustomScrollView and TextField issue

### ISSUE THREAD

**Issue by jogboms** [flutter/flutter#25507]
## Steps to Reproduce
So having a `TextField` within a `CustomScrollView` causes the entire view to scroll to the top once the keyboard comes up.

``` dart
Scaffold(
	body: CustomScrollView(
		slivers: <Widget>[
			SliverList(
				delegate: SliverChildListDelegate(
					<Widget>[
						Align(
							alignment: Alignment.topLeft,
							child: FlutterLogo(size: 64.0),
						),
						ListTile(
							title: Text('Some Text'),
						),
						ListTile(),
					],
				),
			),
			SliverAppBar(
				backgroundColor: Theme.of(context).scaffoldBackgroundColor,
				elevation: 0.0,
				automaticallyImplyLeading: false,
				pinned: true,
				floating: false,
				title: TextField(
					style: Theme.of(context).primaryTextTheme.title,
					decoration: InputDecoration(
						border: OutlineInputBorder(
								borderRadius: BorderRadius.all(Radius.circular(8.0))),
						suffixIcon: Icon(Icons.search),
						hintText: '검색',
					),
				),
			),
			SliverList(
				delegate: SliverChildListDelegate(List.generate(
						100,
						(i) => ListTile(
									title: Text('Scroll'),
								)).toList()),
			),
		],
	),
);
```

## Logs

```
[✓] Flutter (Channel master, v1.1.3-pre.11, on Mac OS X 10.14.2 18C54, locale en-NG)
    • Flutter version 1.1.3-pre.11 at /Users/apple/Desktop/flutter
    • Framework revision c5251cdc02 (4 days ago), 2018-12-14 16:09:17 -0800
    • Engine revision 101b27da7a
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK at /Users/apple/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • SM G955F • ce041714616c00130c • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

**Comment by zoechi** [comment]
I think this is a support question better asked on StackOverflow.

Don't nest Scaffold within another Scaffold. 
Check https://docs.flutter.io/flutter/material/Scaffold/resizeToAvoidBottomPadding.html

If you think this actually is a bug, please post minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce (incl `main() {..}`.

**Comment by jogboms** [comment]
@zoechi i created a gist repro [here](https://gist.github.com/jogboms/9aa3f86855b4d35c59f3c9f2cceaac1a)

**Comment by zoechi** [comment]
What exactly do you mean with the "entire view"?
I tried to reproduce and only the content of the lower `SliverList` scrolls up.
What is the desired behavior?

**Comment by zoechi** [comment]
I personally would also expect it to not scroll. Just wanted to be sure what the issue is about.

**Comment by zoechi** [comment]
I personally would also expect it to not scroll. 
I just wanted to be sure what the issue is about.

I find the title confusing because the issue is not related to `TextField` at all, 
except that the available space shrinks when the `TextField` gets the focus because the keyboard shows up.

**Comment by ahmetayrnc** [comment]
I am having the same problem when the TextField gets the focus, it scrolls the entire scroll view to the top.

**Comment by shamnex** [comment]
Having the same issue. Did anyone manage to solve this?

**Comment by localpcguy** [comment]
We are having a similar issue in our app. We have a structure like below, and a search bar in the `SliverPersistentHeader` section set to pin when at the top of the screen. 

When that pins, and the user scrolls farther down the page, and when the Search box (`TextField`) in the `SliverPersistentHeader` is focused by clicking on it, the page scrolls back to where it _would_ have been in view if it was not for it being pinned as part of the `SliverPersistentHeader`.

    CustomScrollView(
      controller: _scrollController,
        slivers: [
          SliverToBoxAdapter(...),
          SliverPersistentHeader(...),
          SliverToBoxAdapter(...),
        ],
    ),

Expected behavior would be that nothing scrolls automatically when the focused text field is in a `SliverPersistentHeader` or `SliverAppBar` and is pinned. 

The title isn't great, but I believe (could be wrong) it has to do with the logic put in place to scroll TextFields into view when they are focused. Potentially related to fixes from #10826?

**Comment by ookami-kb** [comment]
I guess it's related to the same issue: `CustomScrollView` scrolls to top automatically not only on text field focus, but on every consequent key press as well. It's reproducible on such code:

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            SliverToBoxAdapter(
              child: Column(
                children: <Widget>[
                  Container(height: 1000),
                  CupertinoTextField(),
                ],
              ),
            ),
          ],
        ),
      );
}
```

If you scroll to text field and tap on it, scroll view jumps to top. If you scroll again to the focused text field and press any key, it will jump again.

**Comment by jennymolske** [comment]
We've got the same problem in our app. Also a `CustomScrollView` with a `SliverAppBar` (with `CupertionTextField`) and a `SliverGrid` beneath. When clicking into the TextField the whole ScrollView jumps back to the top position. 

Any solutions or hints for this?

The trick from ookami-kb doesn't work in our case unfortunately. Our TextField isn't wrapped in a `Column`

**Comment by Gperez88** [comment]
i have same issues...

`
CustomScrollView(
    slivers: <Widget>[
        _buildSliverPersistentHeader(),
        _buildItemNotPushasedList(),
        _buildDividerLists(),
        _buildItemsPushasedList(),
    ],
),
`

**Comment by nhatnam240996** [comment]
I have same issues. any one solved the issue? Plz help me! Thanks a lot.

**Comment by nhatnam240996** [comment]
> We've got the same problem in our app. Also a `CustomScrollView` with a `SliverAppBar` (with `CupertionTextField`) and a `SliverGrid` beneath. When clicking into the TextField the whole ScrollView jumps back to the top position.
> 
> Any solutions or hints for this?
> 
> The trick from ookami-kb doesn't work in our case unfortunately. Our TextField isn't wrapped in a `Column`


Have you resolved the issue? I faced the same issue. Plz Help me!

**Comment by quanghoang0101** [comment]
I also have same issue.

**Comment by Stmol** [comment]
Hey! Same issue.

I found the place where that **_strange_** scroll happens:
https://github.com/flutter/flutter/blob/76b21d2867603f9b1889b3c24efeb66cdf702eac/packages/flutter/lib/src/widgets/editable_text.dart#L1600

```dart
_editableKey.currentContext.findRenderObject().showOnScreen(
    rect: inflatedRect,
    duration: _caretAnimationDuration,
    curve: _caretAnimationCurve,
);
```

I haven't found a solution to the problem yet, but I hope the information I found might be useful to someone.

**Comment by mlandry-devolutions** [comment]
Same issue here. If you set showCursor to false on the TextField there is no scroll issue.
It's only happening the first time you scroll but it's very annoying.

**Comment by SebAubin** [comment]
We have the issue as well!

**Comment by esDotDev** [comment]
Seeing this issue as well, NestedScrollbar, stick a TextField in the headerSliverBuilder:
http://screens.gskinner.com/shawn/2020-03-13_00-31-18.mp4

As a bonus you can see that the copy/paste/edit controls also scale up, which I'm sure is not desired... I'll log another bug on that.

**Comment by alexcostaluiz** [comment]
Experiencing the same issue!

**Comment by brenntech** [comment]
We're having the same issue? Any fix available? It's been more than a year.

**Comment by alguintu** [comment]
Getting the same issue. The behavior is jarring. Is there a work around?

**Comment by calvinlow18** [comment]
Same issue as well. Any alternative solution?

**Comment by sahharYoucef** [comment]
same issue

**Comment by binho** [comment]
bump

**Comment by shaileshmota** [comment]
+1

**Comment by binho** [comment]
Found a workaround here (worked for my scenario) → https://stackoverflow.com/a/57336943

And in the final code looks like this below. Wrapped around a `NestedScrollView` with `physics: const NeverScrollableScrollPhysics()`
```dart
return Scaffold(
  body: NestedScrollView(
    physics: const NeverScrollableScrollPhysics(),
    headerSliverBuilder: (context, innerBoxIsScrolled) {
      return <Widget>[
        SliverTopBar(...),
      ];
    },
    body: ListView.builder(
        itemCount: 50,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('Item ${index + 1}'),
          );
        }),
  ),
);
```

**Comment by LongCatIsLooong** [comment]
This is going to take a few more days because I'm planning to include a breaking change in the fix. Another workaround is to turn [`allowImplicitScrolling`](https://api.flutter.dev/flutter/widgets/ScrollPhysics/allowImplicitScrolling.html) off for the viewport.

**Comment by CaiJingLong** [comment]
> Found a workaround here (worked for my scenario) → https://stackoverflow.com/a/57336943
> 
> And in the final code looks like this below. Wrapped around a `NestedScrollView` with `physics: const NeverScrollableScrollPhysics()`
> 
> ```dart
> return Scaffold(
>   body: NestedScrollView(
>     physics: const NeverScrollableScrollPhysics(),
>     headerSliverBuilder: (context, innerBoxIsScrolled) {
>       return <Widget>[
>         SliverTopBar(...),
>       ];
>     },
>     body: ListView.builder(
>         itemCount: 50,
>         itemBuilder: (context, index) {
>           return ListTile(
>             title: Text('Item ${index + 1}'),
>           );
>         }),
>   ),
> );
> ```

This solved my problem briefly, but I still hope this issue can be resolved.

**Comment by abdullah432** [comment]
> This is going to take a few more days because I'm planning to include a breaking change in the fix. Another workaround is to turn [`allowImplicitScrolling`](https://api.flutter.dev/flutter/widgets/ScrollPhysics/allowImplicitScrolling.html) off for the viewport.

How to do that?

**Comment by LongCatIsLooong** [comment]
@abdullah432 it a configurable parameter in `ScrollPhysics`: https://api.flutter.dev/flutter/widgets/ScrollPhysics-class.html. You can make a scroll physics similar to this:
https://github.com/flutter/flutter/blob/a6ce2d4bc7490916a022e6a05af75a6ad0852e8d/packages/flutter/test/widgets/editable_text_test.dart#L5341-L5351

and wrap the physics you're currently using in the new physics, as parent: `NoImplicitScrollPhysics(parent: <originalPhysics>)`.

**Comment by abdullah432** [comment]
> @abdullah432 it a configurable parameter in `ScrollPhysics`: https://api.flutter.dev/flutter/widgets/ScrollPhysics-class.html. You can make a scroll physics similar to this:
> https://github.com/flutter/flutter/blob/a6ce2d4bc7490916a022e6a05af75a6ad0852e8d/packages/flutter/test/widgets/editable_text_test.dart#L5341-L5351
> 
> and wrap the physics you're currently using in the new physics, as parent: `NoImplicitScrollPhysics(parent: <originalPhysics>)`.

@LongCatIsLooong  Thanks. The issue for me was, the textfield/buttonpressed/GestureDetector not working inside FlexibleSpace. After `flutter upgrade`, everything starts working.

**Comment by adeolaex** [comment]
@LongCatIsLooong Thank you for that workaround.

**Comment by Hixie** [comment]
@LongCatIsLooong any updates here? (It's been on the "Overdue" milestone for a month.)

**Comment by LongCatIsLooong** [comment]
@Hixie just updated the PR and notified the reviewers.

**Comment by bereanu99** [comment]
I have the same problem with in a CustomScrollView with a sliverList and a SliverPersistentHeader that contains the plugin "flutter_typeahead" which extends the FormField, no clue how to fix it .

Tried with FocusNode but nothing works :(

**Comment by jonathananales** [comment]
This works for me:

```dart
  // Wrap flexibleSpace with layoutBuilder
  // and statefulbuilder if working on statelesswidget
  flexibleSpace: LayoutBuilder(
    builder: (BuildContext context, BoxConstraints constraints) {
      //always set to true on constraints change
      //happens when sliverappbar is opening or closing
      var searchBoxEnabled = true;
      return StatefulBuilder(
        builder: (BuildContext context, setState) {
          
          //if the constraints height is starting to fade its
          //flexiblespace, disable it, this forces the keyboard
          //to hide,  my expandedHeight is set to 120
          if (constraints.biggest.height < 115 && tex) {
            setState(() {
              searchBoxEnabled = false;
            });
          }
          return FlexibleSpaceBar(
            background: Container(
              child: TextFormField(
                enabled: searchBoxEnabled,
                initialValue: state.query,
                keyboardType: TextInputType.text,
                onChanged: (qry) => doSearch(context, qry),
              ),
            )
          );
        },
      );
    }
  ),
```

**Comment by piedcipher** [comment]
> Found a workaround here (worked for my scenario) → https://stackoverflow.com/a/57336943
> 
> And in the final code looks like this below. Wrapped around a `NestedScrollView` with `physics: const NeverScrollableScrollPhysics()`
> 
> ```dart
> return Scaffold(
>   body: NestedScrollView(
>     physics: const NeverScrollableScrollPhysics(),
>     headerSliverBuilder: (context, innerBoxIsScrolled) {
>       return <Widget>[
>         SliverTopBar(...),
>       ];
>     },
>     body: ListView.builder(
>         itemCount: 50,
>         itemBuilder: (context, index) {
>           return ListTile(
>             title: Text('Item ${index + 1}'),
>           );
>         }),
>   ),
> );
> ```

Thanks a lot! :heart:
