### ISSUE TITLE
Force-rerun engine license script whenever it changes

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#25519]
In flutter/engine#7179, we inadvertently landed a spelling correction to a licence-matching regex (for a licence found under `third_party`) in the licence script. Since no third_party code changed during this run, the signature for `third_party` didn't chance, and it was skipped. Had it run, we would have immediately spotted that the spelling correction introduced a bug. 

In our pre/post-submit we should force re-run the licence script over all components. One couple possible mechanism for this would be to use `git diff-tree --no-commit-id --name-only -r HEAD` to get a list of files modified in the current commit. I expect this should work for Cirrus, though on the chromebots, commits sometimes get aggregated, so really we'd want the union of files changed in all commits between the previous run and the current run.

**Comment by Hixie** [comment]
Easiest solution IMHO would be to just include the license directory in the computation of the hash of all the other directories. (e.g. compute it for the license directory, then xor the other signatures with it)
