### ISSUE TITLE
Stop using `assert` in Java code 

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#25517]
#### `assert` is like a compiled _comment_

Originally, the only option you really had was just to write an implementation comment like `// count must be <= length here.`

But since Java introduced the `assert` keyword in version 1.4, we now have two choices: a comment or an `assert` statement.

The two choices are actually relatively similar.
* An assert statement is unlike an implementation comment in that it is syntactically valid, it gets compiled, and it may be executed.
* But it's like an implementation comment in that you can never be sure that it is actually executed. Therefore it provides no actual protection against anything at runtime.

#### I can fix that with `-enableassertions`!

What you might do is resolve that you will steadfastly use `-enableassertions` in all your test targets.

This helps a bit, but it still only ensures they never failed in your tests, when run in certain ways.

Unfortunately, this well-intentioned remedy introduces a new and serious problem! You now have the risk that you might accidentally rely on side effects from an assert statement for correct program behavior! Those side effects will make your tests pass, but won't happen in production, and you can suffer mysterious bugs. The fix for this is to run all your tests twice (once with and without assertions enabled) regularly, which is generally impractical.

It's better to just explicitly check the condition you're asserting and explicitly throw if the condition fails.

**Comment by krisgiesing** [comment]
This seems like a style question rather than a correctness question. Is there a style guide for the Java part of the engine?

**Comment by tvolkert** [comment]
We've recently decided to adopt Google's Java style guide.

That said, I view this more of a correctness issue since we never run with a asserts enabled.

**Comment by Hixie** [comment]
We use asserts in Dart a lot. Is the main difference just that for Dart, we run the code live with assets more?

**Comment by tvolkert** [comment]
Basically.  Essentially, we never run with `-enableasserts` in our Java code, not in tests (which we don't have much of in the engine), nor in our prebuilts.  So they always amount to comments in our code right now.  Moreover, they're not doing any complex computations that we'd want to avoid in production code, so unlike our asserts in Dart, we're not really saving anything by skipping the checks in real code.

**Comment by tvolkert** [comment]
We no longer have any assert usage in the engine.
