### ISSUE TITLE
Multi-window API design proposal

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#25526]
We should provide an API with the following features:

* The embedder can ask an engine to render in a new location, and expose that location as a new window to an existing isolate. The engine would provide the embedder with a token representing that window.
* In dart:ui, the Window subclass would be split into two in a super/subclass relationship. Most things would be on the subclass, which we'd continue to use for the window global.
* In dart:ui, there'd be an API to obtain the Window for a particular token.
* All Windows would have a `render` method, much like today. We'd also need to do per-window hit testing, accessibility, and other such things.

cc @jason-simmons, @matthew-carroll, @cbracken

**Comment by xster** [comment]
I think we can merge this one into #60131. Please reopen if incorrect.
