### ISSUE TITLE
Scrollbar widget should support padding

### ISSUE THREAD

**Issue by maxlapides** [flutter/flutter#25524]
This is particularly an issue with Cupertino views where the top bar and the bottom bar are often partially translucent. In this case, we want the content to scroll behind those bars, but the scrollbar itself should stop outside the bars. For example, code like this:

```dart
class CupertinoDemoTab1 extends StatelessWidget {
  const CupertinoDemoTab1({this.colorItems, this.colorNameItems});

  final List<Color> colorItems;
  final List<String> colorNameItems;

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Scrollbar(
        child: CustomScrollView(
          semanticChildCount: _kChildCount,
          slivers: <Widget>[
            CupertinoSliverNavigationBar(
              trailing: trailingButtons,
            ),
            SliverPadding(
              // Top media padding consumed by CupertinoSliverNavigationBar.
              // Left/Right media padding consumed by Tab1RowItem.
              padding: padding,
              sliver: SliverList(
                delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) { ... },
                  childCount: _kChildCount,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

Will render like this:

![kapture 2018-12-18 at 15 05 29](https://user-images.githubusercontent.com/1874682/50188419-7e7eb200-02d6-11e9-9f87-e62a28d057a3.gif)

Notice how the scrollbars look like they outside the scroll view. It makes sense why this is happening, but as far as I know there's currently no easy way to get this quite right.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by xster** [comment]
Duping into #13253. Please 👍the issues you care about to help us prioritize.
