### ISSUE TITLE
Dragging speed reorderable_list

### ISSUE THREAD

**Issue by Dn-a** [flutter/flutter#25528]
Hi guys,
increase or decrease the dragging speed, is it possible?

**Comment by goderbauer** [comment]
What do you mean by this? Your finger controls the dragging speed, no?

**Comment by Dn-a** [comment]
it does not work well, sometimes it gets jammed ...
another problem I found is the excessive space at the bottom of the list, what is it due to?

**Comment by zoechi** [comment]
I think to investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
