### ISSUE TITLE
Invalid redirect on DayPicker class' docs

### ISSUE THREAD

**Issue by david145** [flutter/flutter#25532]
> See also:
> 
> - showDatePicker.
> - [material.google.com/components/pickers.html#pickers-date-pickers](http://material.google.com/components/pickers.html#pickers-date-pickers) // wrong redirect
> 

https://docs.flutter.io/flutter/material/DayPicker-class.html

The second link in the "see also" reference is invalid and redirects to the material design main page.

**Comment by HansMuller** [comment]
Thanks for the report! There were similar problems in the date picker and time picker sources; fixed those too.
