### ISSUE TITLE
RefreshIndicator does not disappear when refreshed in foreground

### ISSUE THREAD

**Issue by tmexcept** [flutter/flutter#25535]
There has no warning or error log, the code is:
```dart
return Container(

        child:RefreshIndicator(child: ListView.builder(
          itemCount: bidList.length,
          itemBuilder: (context, index) {
            if(index == bidList.length)
              return _buildProgressIndicator();
            else
              return listItem(context, index, bidList[index]);
          },
          controller: _scrollController,
          physics: BouncingScrollPhysics(),
        ),
        onRefresh: (){
          _page = 1;
          getDetailEntity(_page);
        },
      )
      );
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by tmexcept** [comment]
I made an example about RefreshIndicator, then i get an info level log :
`
══╡ EXCEPTION CAUGHT BY MATERIAL LIBRARY ╞══════════════════════════════════════════════════════════

12-19 14:58:24.100 18658-18676/kupai.flutterapp I/flutter: The following assertion was thrown when calling onRefresh:
    The onRefresh callback returned null.
    The RefreshIndicator onRefresh callback must return a Future.
    ════════════════════════════════════════════════════════════════════════════════════════════════════`

then i change the code like this:
`return Container(

        child:RefreshIndicator(child: ListView.builder(
          itemCount: bidList.length + 1,
          itemBuilder: (context, index) {
            if(index == bidList.length)
              return _buildProgressIndicator();
            else
              return listItem(context, index, bidList[index]);
          },
          controller: _scrollController,
          physics: BouncingScrollPhysics(),
        ),
        onRefresh: (){
          return getDetailEntityFirst();
        },
      )
      );
      Future<Null> getDetailEntityFirst() async {
    _page = 1;
    getDetailEntity(_page);
    return;
      }
  `
The RefreshIndicator disappeared, but i don't know why the old code  didn't have the info log on it.

**Comment by panchalAlpit** [comment]
> I made an example about RefreshIndicator, then i get an info level log :
> 
> ```
> ══╡ EXCEPTION CAUGHT BY MATERIAL LIBRARY ╞══════════════════════════════════════════════════════════
> 
> 12-19 14:58:24.100 18658-18676/kupai.flutterapp I/flutter: The following assertion was thrown when calling onRefresh:
>     The onRefresh callback returned null.
>     The RefreshIndicator onRefresh callback must return a Future.
>     ════════════════════════════════════════════════════════════════════════════════════════════════════`
> ```
> 
> then i change the code like this:
> 
> ```dart
> return Container(
> 
>         child:RefreshIndicator(child: ListView.builder(
>           itemCount: bidList.length + 1,
>           itemBuilder: (context, index) {
>             if(index == bidList.length)
>               return _buildProgressIndicator();
>             else
>               return listItem(context, index, bidList[index]);
>           },
>           controller: _scrollController,
>           physics: BouncingScrollPhysics(),
>         ),
>         onRefresh: (){
>           return getDetailEntityFirst();
>         },
>       )
>       );
>       Future<Null> getDetailEntityFirst() async {
>     _page = 1;
>     getDetailEntity(_page);
>     return;
>       }
> ```
> 
> The RefreshIndicator disappeared, but i don't know why the old code didn't have the info log on it.

It's working for me.
Thanks
