### ISSUE TITLE
Failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug' of flutter-x86.jar.

### ISSUE THREAD

**Issue by saguins** [flutter/flutter#25539]
I just normally set up my first Flutter app in Android Studio. and then this happen when I click Run.

## flutter run

```
C:\Users\lara_\AndroidStudioProjects\flutter_testfapp>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.1s
Resolving dependencies...                                    3.4s
Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> Internal error when trying to read zip file 'C:\Users\lara_\AndroidStudioProjects\flutter_testfapp\build\app\intermediates\flutter\flutter-x86.jar'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Gradle task 'assembleDebug'... Done                          7.3s
Gradle task assembleDebug failed with exit code 1
```

## flutter doctor -v

```
[√] Flutter (Channel master, v1.1.3-pre.40, on Microsoft Windows [Version 10.0.17134.471], locale th-TH)
    • Flutter version 1.1.3-pre.40 at C:\Users\lara_\flutter\flutter
    • Framework revision b8a035a3d4 (81 minutes ago), 2018-12-18 20:36:35 -0800
    • Engine revision 08465e8000
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\lara_\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

I don't know if I need to fix version of something.
also tried ```flutter clean``` but it doesn't help.

Thanks.

**Comment by zoechi** [comment]
Can you please execute these commands https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted, run `flutter clean` and try again?

**Comment by saguins** [comment]
I run the following commands in the Flutter install directory from [that site you give](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted) in my flutter install directory then `flutter clean` and `flutter run` my project but still get the same output as my **flutter run** above as well as my **flutter doctor**.

**Comment by zoechi** [comment]
Hard to tell. I guess is that you have a zip tool in your path that can't handle the mentioned flutter-x86.jar file.

**Comment by saguins** [comment]
I think so. 👍 because from the first time I set up and repeat my set up again, reinstall Flutter and Android Studio, create my new project and click Run. I only get the same output in my `flutter run`. but I still don't know what or where should I start to fix this.

**Comment by zoechi** [comment]
I searched https://www.google.at/search?q=%22Internal+error+when+trying+to+read+zip+file%22&oq=%22Internal+error+when+trying+to+read+zip+file%22+&aqs=chrome..69i57j0l5.25895j0j7&sourceid=chrome&ie=UTF-8 
and found one that might help
https://stackoverflow.com/a/37574473/217408
which indicates that some other process (perhaps AntiVirus?) has the file opened and prevents Flutter/Gradle to do it's job.

**Comment by saguins** [comment]
thanks for link! but I don't found `Java(TM) Platform SE binary` in Windows Task Manager after exit Android Studio, so I just end task of `OpenJDK Platform Binary` instead. maybe I have something wrong with Java?

After that I tried to `flutter clean` my project, open Android Studio and `File > Invalidate and Restart`, then run my project again but output still same. maybe I do something wrong, or my computer or my windows is wrong. (lol)

**Comment by zoechi** [comment]
Did you try excluding that directory from your virus scanner (if you use any)?

**Comment by saguins** [comment]
yep. I also try to disable my antivirus and even uninstall it. still same

**Comment by zoechi** [comment]
Sorry, I'm out of ideas. Perhaps someone else. 
I'd suggest to ask on StackOverflow to get the attention of more people.

**Comment by saguins** [comment]
ok. anyway, thanks for help. I really appreciated. 😄

**Comment by zoechi** [comment]
You could check if you can open the jar file with a zip util on your system and see if you get an error.
It looks like a Gradle issue, not a Flutter issue, but I wasn't able to find anything similar with Google seach.

**Comment by ashish9342** [comment]
A more detailed screenshot of error.


![image](https://user-images.githubusercontent.com/8640199/55074026-412d7b80-50a0-11e9-965f-9b175f41140e.png)

**Comment by blasten** [comment]
If this is still an issue, please provide the steps that will repro this issue. Consider creating a new issue or reopening this one with the minimal repro case. An attachment is preferred.
