### ISSUE TITLE
Document that TabController is a ChangeNotifier that notifies of tab changes

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#25542]
It would be great if TabBar could provide onIndexChanged(Int) callback. It's helpful for me to do some root UI changes based on the index.

**Comment by zoechi** [comment]
Currently I only found https://docs.flutter.io/flutter/material/TabController/animation.html
where you can add a listener to get notified when it's done 
and then check https://docs.flutter.io/flutter/material/TabController/index.html (and https://docs.flutter.io/flutter/material/TabController/previousIndex.html) to get the new (and old) index.

**Comment by anderscheow** [comment]
Well, that's the only workaround

**Comment by HansMuller** [comment]
TabController is a ChangeNotifier. Listeners added to a TabController will be notified when the index changes.

**Comment by darshankawar** [comment]
Considering the fact that `TabController` itself is a `ChangeNotifier`, there's no explicit need to document per the issue title.

<img width="316" alt="Screenshot 2021-02-02 at 4 01 59 PM" src="https://user-images.githubusercontent.com/67046386/106587828-1c45a180-6570-11eb-8e96-3fdd1a5e2864.png">

And listeners added to `TabController` will be notified per this comment, https://github.com/flutter/flutter/issues/25542#issuecomment-448701877, I believe this issue has already been resolved.

Going ahead and closing this. If anybody disagrees, write in comments and I'll reopen it.
