### ISSUE TITLE
need some location plugin which is not using FusedLocationProvider

### ISSUE THREAD

**Issue by somelikebit** [flutter/flutter#25540]
Hi.
I need to get current location in my application and i'm using flutter **location** plugin.
i just got this libraries for using location in flutter : 
  **_location , geolocator , geolocation , flutter_geolocation_**
all this libraries are using google fusedLocationProviderClient for getting current and last location updates.
the fused location provider client is not really good in my case because it will work if you have opened the google Maps once before.
check this for getting more details:
[Platform Exception With Error code 'ERROR' in getLocation() method](https://github.com/Lyokone/flutterlocation/issues/97)

my question is, is there some flutter plugin or library which is using android location provider instead of google fused location provider ?

sorry for my poor English language

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
