### ISSUE TITLE
Android Build fails due to minSdkVersion and targetSdkVersion in AndroidManifest instead of build.gradle.

### ISSUE THREAD

**Issue by SebastianEngel** [flutter/flutter#25549]
I use the webview_flutter plugin in my Flutter app. When I open the Android module of my app in Android Studio and try to build it, the build fails with:

`The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.`

The problematic part is in the webview_flutter's [AndroidManfest.xml](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/android/src/main/AndroidManifest.xml#L3).

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="io.flutter.plugins.webviewflutter">
    <uses-sdk android:minSdkVersion="20" android:targetSdkVersion="26"/>
</manifest>
```

As the error message says, these properties should be moved into the build.gradle.

**Comment by zoechi** [comment]
This sounds like https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

Can you reproduce with a newly created project (with `flutter create foo` with a recent Flutter version)?

**Comment by YotaVGA** [comment]
I have the same problem and I have regenerated the files with flutter create.
I tried with two different versions of flutter, same result:

```
$ flutter --version
Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (4 settimane fa) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

```
$ flutter --version
Flutter 1.1.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 3cca1a2ec3 (2 settimane fa) • 2018-12-11 18:50:51 +0000
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by zoechi** [comment]
Can you provide a complete but minimal project that allows to reproduce?
as zip archive or committed to GitHub
