### ISSUE TITLE
Run analyzer against (out-of-repo) Flutter examples so we remember to update them

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2554]
We should analyze the following first-party sample Flutter apps with Flutter's Travis to make sure they're up-to-date when Flutter APIs change.

example/flutter_example in http://github.com/dart-lang/usage/
all steps in http://github.com/flutter/firechat-flutter
https://github.com/flutter/game

**Comment by collinjackson** [comment]
@Hixie

**Comment by eseidelGoogle** [comment]
Might also be aided by us having a flutter travis template: https://github.com/flutter/flutter/issues/2267, presumably one which tracks head.

**Comment by kf6gpe** [comment]
@RedBrogdon Is this something that DevRel should consider? Or should we just close this?

**Comment by digiter** [comment]
Triage: closing because this is too old.
