### ISSUE TITLE
[help/improve] when i scoll, I wish could scroll SliverAppBar first, but ScrollBar first now.

### ISSUE THREAD

**Issue by fanybook** [flutter/flutter#25554]
when i scoll, I wish could scroll SliverAppBar first.
How can i do it? now sub_page first.

The expected effect:
In a scroll action, the preference is SliverAppBar . After the SliverAppBar is displayed/hidden, continue scrolling the sub_page.

demo image:
![bug_preferredSize](https://raw.githubusercontent.com/fanybook/cornerstone/master/_docs/flutter_improve_scroll_priority.jpg)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by fanybook** [comment]
Can current version flutter implement my requirement?

**Comment by zoechi** [comment]
There aren't many such requirements that you can't do with Flutter.
The question is how much you need to build yourself and what works out-of-the box.
I'd suggest to ask on StackOverflow.
