### ISSUE TITLE
Issue from website page 国际化Flutter App

### ISSUE THREAD

**Issue by virtualli** [flutter/flutter#25555]
From URL: https://www.flutterchina.club/tutorials/international/index.md
use zh_CN call fun showDatePicker,date_picker.dart file _kDatePickerHeaderPortraitHeight+10 show OK

**Comment by zoechi** [comment]
This site is not maintained by the Flutter team but by the community.
Please check the site or https://flutter.io/community/china#configuring-flutter-to-use-a-mirror-site for how to contact the maintainers to report the issue there.
