### ISSUE TITLE
Misleading assert with a FlexJustifyContent.collapse Row with Flexible children

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#2555]
I have the following in a build function:

      new Block(
        padding: const EdgeDims.all(8.0),
        children: <Widget>[
          new Row(
            justifyContent: FlexJustifyContent.collapse,
            alignItems: FlexAlignItems.start,
            children: <Widget>[
              new Flexible(
                child: new Input(
                  labelText: 'New Password',
                  hideText: true,
                )
              ),
              new Flexible(
                child: new Input(
                  labelText: 'Re-type Password',
                  hideText: true,
                )
              )
            ]
          )

---

Specifying  'collapse' with Flexible children is invalid, but the assert given is very misleading:

I/flutter : 'packages/flutter/src/rendering/flex.dart': Failed assertion: line 351: 'canFlex && "See https://flutter.io/layout/#flex" is String' is not true.

### Flutter Version
Flutter from git@github.com:flutter/flutter.git (on master)
Framework: e0a639c828e26cc3b148e83b70ab0250d834efe1 (2 hours ago)
Engine:    8514a14911269e405784ca90ba082407d260fbf3

[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.

**Comment by Hixie** [comment]
@mpcomplete Let me know if the updated exceptions are still unclear.
