### ISSUE TITLE
It is not possible to add a key to the Checkbox created by CheckboxListTile

### ISSUE THREAD

**Issue by jmdevin** [flutter/flutter#25561]
If it is possible and I just don't see it let me know, but I don't believe it is.

This might be a new feature request?

BACKGROUND:
This issue presented itself while I was trying to write an integration test. A user must tap several checkboxes on the same page to mark them "checked" before proceeding. Flutter driver, which is used to interact with the app during integration tests, needs to use a key to identify a widget (it can't use type when others of the same type are on the same page).

ISSUE:
The [CheckboxListTile](https://docs.flutter.io/flutter/material/CheckboxListTile-class.html) widget builds a [Checkbox](https://docs.flutter.io/flutter/material/Checkbox-class.html) underneath it by definition. However, because the Checkbox itself is not explicitly created, it cannot be given a key. This means that flutter driver will not be able to act on it.

There may be one reason that no one has cared about this: when you tap on the entire CheckboxListTile the checkbox is toggled. That would solve the issue for many people, but we constructed our CheckboxListTile with a RaisedButton as the title, like so:

```dart
new CheckboxListTile(
    title: new RaisedButton(
        onPressed: () {
            _launchInBrowser("example.com");
        },
        child: new Text("Button Text")
    ),
    onChanged: (bool val) {
        setState(() {
            do.something = val;
        });
    },
    value: do.something == true,
);
```

WORKAROUND:
We replaced all of our CheckboxListTiles with regular ListTiles and added Checkboxes, with keys, as their "trailing:" widgets. Flutter driver can now find and mark the checkboxes.

For Reference:

CheckboxListTile
```dart
const CheckboxListTile({
    Key key,
    @required this.value,
    @required this.onChanged,
    this.activeColor,
    this.title,
    this.subtitle,
    this.isThreeLine = false,
    this.dense,
    this.secondary,
    this.selected = false,
    this.controlAffinity = ListTileControlAffinity.platform,
  }) : assert(value != null),
       assert(isThreeLine != null),
       assert(!isThreeLine || subtitle != null),
       assert(selected != null),
       assert(controlAffinity != null),
       super(key: key);

Widget build(BuildContext context) {
    final Widget control = Checkbox(
      value: value,
      onChanged: onChanged,
      activeColor: activeColor,
      materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    );
    Widget leading, trailing;
    switch (controlAffinity) {
      case ListTileControlAffinity.leading:
        leading = control;
        trailing = secondary;
        break;
      case ListTileControlAffinity.trailing:
      case ListTileControlAffinity.platform:
        leading = secondary;
        trailing = control;
        break;
    }
    return MergeSemantics(
      child: ListTileTheme.merge(
        selectedColor: activeColor ?? Theme.of(context).accentColor,
        child: ListTile(
          leading: leading,
          title: title,
          subtitle: subtitle,
          trailing: trailing,
          isThreeLine: isThreeLine,
          dense: dense,
          enabled: onChanged != null,
          onTap: onChanged != null ? () { onChanged(!value); } : null,
          selected: selected,
```

Checkbox
```dart
const Checkbox({
    Key key,
    @required this.value,
    this.tristate = false,
    @required this.onChanged,
    this.activeColor,
    this.materialTapTargetSize,
  }) : assert(tristate != null),
       assert(tristate || value != null),
       super(key: key);
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by jmdevin** [comment]
I don't think the Flutter doctor output is relevant in this case, but here it is. There are no errors that appear when I attempt to run anything; the issue is writing something at all. It doesn't seem to be possible to put a key on the checkbox and only the checkbox. Adding a key to the entire CheckboxListTile runs fine; it just doesn't do what is needed.

[✓] Flutter (Channel dev, v1.1.1, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.1.1 at /Users/jdevin/flutter
    • Framework revision 65df90d8b5 (8 days ago), 2018-12-11 19:29:13 -0800
    • Engine revision 25b58c0c67
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jdevin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.

**Comment by HansMuller** [comment]
The key for a CheckboxListTile identifies the CheckboxListTile, not it's Checkbox (or any other descedant), just as you've observed. 

To identify a particular CheckboxlistTile checkbox in a test you can use `find.descendant:
```
find.descendant(of: find.byKey(MyCheckboxListTileKey), matching: find.byType(Checkbox))
```

**Comment by jmdevin** [comment]
@HansMuller Unless I'm mistaken, "find.descendant" isn't available in integration tests; from what I read (and when I tried to use it) the flutter_test library is restricted to unit and widget tests. The flutter _driver [finder](https://docs.flutter.io/flutter/flutter_driver/CommonFinders-class.html) for integration tests is much more limited and doesn't have a descendant method. It took me a while to accept that :(

**Comment by HansMuller** [comment]
Sorry, I overlooked the fact that you were writing a flutter driver test.

**Comment by HansMuller** [comment]
You can use [enableFluttterDriverExtention's](https://docs.flutter.io/flutter/flutter_driver_extension/enableFlutterDriverExtension.html) handler parameter to add a custom communication channel between the test driver and the app being tested.

**Comment by jmdevin** [comment]
@HansMuller Thanks for the help. For this specific case we will most likely continue to use the ListTile workaround, especially as it's already implemented; however I will definitely look into the extension DataHandler. In fact, part of the reason I raised this issue now, even if I had the workaround, is I wonder whether there are other widgets with children that can't be given keys which don't have an easy workaround. I figured I would rather discover a method of handling it now than later.

**Comment by HansMuller** [comment]
This was a reasonable request. We don't plan on addressing it because as noted [earlier](https://github.com/flutter/flutter/issues/25561#issuecomment-448791696), providing the obvious way to add keys to a composite widgets doesn't scale well.  If this issue crops up often enough, we'll have to look at approaches that would scale.
