### ISSUE TITLE
How to install both of flutter sdk and web sdk ?

### ISSUE THREAD

**Issue by goodforever** [flutter/flutter#25560]
How to install both of flutter sdk and web sdk ?

**Comment by zoechi** [comment]
Follow the instructions on 
flutter.io for Flutter SDK setup 
and dart-lang.org for Dart SDK setup ;-)

You'll need both. 
Flutter uses a customizes Dart SDK that can't be used for web development.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
