### ISSUE TITLE
ListView BouncingScrollPhysics for iOS stops working when list is small

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25566]
## Steps to Reproduce
```dart
@override
  Widget build(BuildContext context) {
    return ListView.builder(
      physics: BouncingScrollPhysics(), // deleting this solves the issue
      itemCount: 5,
      itemBuilder: (context, index) {
        return ListTile(title: Text("Index = ${index}"));
      },
    );
  }
```

You can see if the list is small (the user doesn't have to scroll anything to find more items, cause all are already visible on the screen), then `physics: BouncingScrollPhysics()` fails to show bounce effect in iOS however if you delete this line, list again gets capable of showing bouncing effect. 

### Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by dark-chocolate** [comment]
Thanks, it worked. So, @zoechi , will you guys add this feature in later updates or is it okay to have that behaviour. If that behaviour is intended then I will close this issue else will left it opened.

**Comment by zoechi** [comment]
Not my call. I'll leave that to the specialists to decide.

**Comment by dark-chocolate** [comment]
Specialists asking for specialist ?

**Comment by goderbauer** [comment]
@dark-chocolate What's the request here? Sounds like everything is working as intended. `BouncingScrollPhysics` only bounces if the scrollable has enough content to scroll. You can override this by wrapping it in `AlwaysScrollableScrollPhysics`. Can we close this?

**Comment by dark-chocolate** [comment]
Yes, I'm happy to close it. I too was in doubt, if it is how it is supposed to work ...

**Comment by vegetable88** [comment]
thanks a lot.this issue help me to fix my bug.

**Comment by shivasairam101** [comment]
I came across a similar issue. I solved it by wrapping my scroll-able widget with a sized box whose size is equal to the screen size. 

`                       SizedBox(
                              height: MediaQuery.of(context).size.height,
                              child: Container(
                                child: YourScrollableWidget(),
                              ),
                            )`

**Comment by RichieMcMullen** [comment]
To always have the Bouncing Scroll effect regardless of the size of your list, you can do this:

```physics: AlwaysScrollableScrollPhysics( parent: BouncingScrollPhysics() ),```
