### ISSUE TITLE
Disable Dynamic Type on iOS

### ISSUE THREAD

**Issue by maxlapides** [flutter/flutter#25587]
I saw support was added for Dynamic Type on iOS: https://github.com/flutter/flutter/issues/4815

But I can't find any way of disabling this across an application, or just for specific widgets. I think this would be very handy for cases where widgets can't support variable text sizes.

**Comment by knopp** [comment]
You can disable text scaling for any place in widget hierarchy using

```dart
    MediaQuery(
      data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
      child: <your-child>,
    );
```

**Comment by maxlapides** [comment]
Thanks @knopp! Perhaps there should be something about "iOS Dynamic Text" in the documentation for `MediaQuery`? I just couldn't find anything about this by searching around.

**Comment by Avatarchik** [comment]
Hi! How can I turn off dynamic fonts now, the option above does not work for me?
