### ISSUE TITLE
[path_provider] more directory options

### ISSUE THREAD

**Issue by thejacer87** [flutter/flutter#25588]
just curious if there are plans to add more robust file access to the rest of the system on both platforms.

in general, i think it would be nice to be able to access more files on the system (with the users permissions of course)

more specifically, for the app i am trying to create i want to have access to a users download directory, or where ever they store music files. similar to https://github.com/google/ringdroid being able to access all audio files to make custom ringtones. but for ios too

**Comment by zoechi** [comment]
Did you check pub.dartlang.org for similar community packages that provide more options?

**Comment by thejacer87** [comment]
yes i have.

although i have had a bit of a misunderstanding. it seems `getExternalStorageDirectory()` will work for what i want on android, and that apple/ios is just too restrictive. and even native apps don't have access to files from other apps/system files (ie audio files)

so for my use case, making ringtones, seems like it's impossible on ios in general, and not technically an issue with flutter. 

i assume if ios did open up a bit, path_provider would make it available pretty quickly

**Comment by zoechi** [comment]
> i assume if ios did open up a bit, path_provider would make it available pretty quickly

Probably. This only requires a pull request from the community to get added.

**Comment by rostopira** [comment]
I would like to have option to access sd card and usb storage devices on Android

**Comment by stuartmorgan** [comment]
Given how much the viability and utility of any given case depends a lot on the specifics, a catch-all bug for "more directories" isn't really actionable. Specific use cases should be filed as distinct issues for evaluation (and several directories have been added that way over time).
