### ISSUE TITLE
Image Picker - more file types desired

### ISSUE THREAD

**Issue by Caponigri** [flutter/flutter#25580]
Using Image Picker, I am able to view any file type on my device, or in linked cloud storage (In my example, Google Drive), but I am not able to actually select any non-image file type for upload. 
It would be great if it could select any file type (Even if only images would be displayed)

Thanks!

**Comment by zoechi** [comment]
There are several community packages in pub.dartlang.dart that provide additional features (select multiple images, ...). Worth checking for additional file types as well.

**Comment by cyanglaz** [comment]
@Caponigri We current don't have a plan to add features to picking files other than image/videos with the image_picker plugin. Did you end up finding a good plugin to pick files?
