### ISSUE TITLE
Material GridPaper

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#256]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Nov 03, 2015 at 22:11 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1933_

----

Once isue #255 is fixed, provide a way to verify that Material Apps are obeying the 8dp/4dp grid.

https://www.google.com/design/spec/layout/metrics-keylines.html#

**Comment by eseidel** [comment]
Is this the same as https://github.com/flutter/flutter/issues/797 ?

**Comment by eseidel** [comment]
Or is this covered by https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/gridpaper.dart ?

**Comment by Hixie** [comment]
nothing to do with 797. This depends on gridpaper being updated per #255.
