### ISSUE TITLE
Request IsolatePoolExecutor similar to ThreadPoolExecutor in Android

### ISSUE THREAD

**Issue by phucgaoxam** [flutter/flutter#25603]
Will Flutter or Dart team will create an IsolatePoolExecutor to manage spawned Isolate?

For example: 
I want to cache images, but using **cached_network_image** only cache a full size image. If my downloaded images's size is more than 5MB, it will affect my app performance.
So I have to write another library which have scale image function, but scale image fuction will block UI in Dart so I have to spawn Isolate. But when my app load a lot of images, it will spawn a lot of Isolates but there is no way to manage these isolates like ThreadPoolExecutor

**Comment by zoechi** [comment]
I think https://pub.dartlang.org/packages/isolate does most of that already.

**Comment by xster** [comment]
Doh, I can't move it. You'd have to create a feature request in https://github.com/dart-lang/sdk for this.
