### ISSUE TITLE
The method 'add' was called on null 

### ISSUE THREAD

**Issue by xyzbilal** [flutter/flutter#25617]
I want to add filepath to a  List<String> _filePaths =[]; variable. but I m getting error that 
`flutter: File path: /private/var/mobile/Containers/Data/Application/123CB9E9-9F07-4675-923D-A5F0629E1470/tmp/image_picker_05DB7840-8FD1-4B3E-81A8-64EAFE4866AD-953-0000018DAFEA92DA.jpg
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add("/private/var/mobile/Containers/Data/Application/123CB9E9-9F07-4675-923D-A5F0629E1470/tmp/image_picker_05DB7840-8FD1-4B3E-81A8-64EAFE4866AD-953-0000018DAFEA92DA.jpg")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _MyHomePageState._getFile.<anonymous closure> (package:resimyukleme_deneme/main.dart:68:19)
#2      State.setState (package:flutter/src/widgets/framework.dart:1130:30)
#3      _MyHomePageState._getFile (package:resimyukleme_deneme/main.dart:67:7)
<asynchronous suspension>
#4      _MyHomePageState.build.<anonymous closure> (package:resimyukleme_deneme/main.dart:171:16)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
#16     _invoke1 (dart:ui/hooks.dart:168:13)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
`
I m checking if the filePath string is null or not. printing the path shows exact path. and I choose image and image shown at screen. 

my code is  like this 
`_getFile(String file) async {
    FileType type;
    switch (file){
      case  "pdf":
        type = FileType.PDF;
        break;
      case "video":
        type = FileType.VIDEO;
        break;
      case "galeri":
        type = FileType.IMAGE;
        break;
      case "camera":
        type = FileType.CAPTURE;
        break;
    }
    try {
      String filePath = await FilePicker.getFilePath(type: type);
      if (filePath == '') {
        return;
      }
      print("File path: " + filePath);
      setState((){
        _filePath.add(filePath);
      _image = File(filePath);
      });

    } on PlatformException catch (e) {
      print("Error while picking the file: " + e.toString());
    }
  }`

any idea

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
