### ISSUE TITLE
Invaild constructor name

### ISSUE THREAD

**Issue by Jallvar** [flutter/flutter#25618]
Hello, i'm write simple class for work with api
i have problem, dart say me what i have wrote a wrong name for a constructor. but i haven't wrote the constructor 

```
import 'package:http/http.dart' as http;

class api_model {
  
  String base_url = 'http://*/Callback/';
  String api_key = '*';

  String getCodes()
  {
    this._request('getCodes');
  }

  String _request(String method, {Map<String, String> params})
  {

    http.post(base_url+'/'+method+'/'+api_key, body: params)
        .then((response) {
      print("Response status: ${response.statusCode}");
      print("Response body: ${response.body}");
    });

  }
}

```

This code in a main class:
```
api_model apiModel = new api_model();
apiModel.getCodes();

```

Error:
Invaild constructor name

**Comment by zoechi** [comment]
I can't reproduce. The error does not come from above code.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
