### ISSUE TITLE
why flutter create ignore these files

### ISSUE THREAD

**Issue by dfang** [flutter/flutter#25616]
why `flutter create` ignore these files 

```
**/android/**/gradle-wrapper.jar
**/android/.gradle
**/android/.gradlew
```

**Comment by zoechi** [comment]
Because they are machine-dependent and if committed would cause issues on another machine where for example install paths are not the same.

**Comment by dfang** [comment]
sorry, i'm not a java developer.

it seems there is benifit for check into source control as [stackoverflow](https://stackoverflow.com/questions/43954932/should-i-gitignore-my-gradlew) and [gradle doc](https://docs.gradle.org/current/userguide/gradle_wrapper.html). 

if it's ignored, how to keep everyone using same gradle version ?
