### ISSUE TITLE
Long press stop sending gesture callbacks

### ISSUE THREAD

**Issue by awoisoak** [flutter/flutter#25610]
## Steps to Reproduce
I can not detect any gesture events when the user moves the finger during a long press.
I run some code while the user make a long press on a button and detect when it's finishes.

As long as the finger does not move around everything works well as the widget receives the expected callbacks : _onLongPress_ & _onLongPressUp_.
However, if the user moves the finger while doing the long press, there won't be any other future callback at all.

Sample app: [main.dart](https://github.com/flutter/flutter/files/2697972/main.dart.txt)

If the finger doesn't reach the widget borders I'd expect the _onLongPressUp_ when the finger is up.
If the finger gets out of the widget layout I'd expect the widget to keep listening the gesture events OR receive a _onLongPressCanceled_ callback

````
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-JP)
    • Flutter version 1.0.0 at /Users/awo/Library/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/awo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • SM N950U1 • ce091719b066e07e0d7e • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

````

**Comment by zoechi** [comment]
Looks related to #11385

**Comment by xster** [comment]
We're talking about this behavior right? https://github.com/flutter/flutter/blob/e77237d6d392a4c31281bfc143dc222773f753bd/packages/flutter/test/gestures/long_press_test.dart#L329 

It should work. 

If you move before a long press is recognized, it's by definition not a long press :D

https://github.com/flutter/flutter/blob/e77237d6d392a4c31281bfc143dc222773f753bd/packages/flutter/test/gestures/long_press_test.dart#L310

**Comment by tapizquent** [comment]
Any updates on this? I really need an option to show a widget on long press and then hide it when they release

**Comment by marcglasberg** [comment]
I can not detect `onPanUpdate` while the user is doing a `LongPress`. Is that expected behavior?

**Comment by iapicca** [comment]
Hi @awoisoak 
I see there's an open [issue](https://github.com/flutter/flutter/issues/19783) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
