### ISSUE TITLE
error in flutter when I set some string data from Model Flutter class to text 

### ISSUE THREAD

**Issue by praveenbaskandi** [flutter/flutter#25614]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the problem.

Please create a new issue with properly filled issue template if you think this is actually a bug.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
