### ISSUE TITLE
Plugin: Contacts service

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2561]
Unclear exactly how we want to provide access to contacts for flutter app developers.  But at least one customer has asked for this.  Assuming this is high on the list of most-accessed services, we will need to provide example code.

**Comment by mit-mit** [comment]
We now have the contribution https://pub.dartlang.org/packages/contact_picker. Closing.

**Comment by zoechi** [comment]
@mit-mit that one is really limited and wasn't updated for 4 months
I think accessing contacts should be important enough to get better support.
I know, community contributions are welcome, but closing this as fixed seems a bit far-fetched to me.

**Comment by mit-mit** [comment]
This bug is already tagged 'self-service', i.e. community lead.

Are there concrete things missing in `contact_picker`?

**Comment by zoechi** [comment]
It only allows to pick, but not to get a list of contacts. 
It only provides the phone number of the picked contact.

(My current workaround, for Android only, is to use the Google cloud people API, which will of course break when offline)

**Comment by mit-mit** [comment]
Fair enough, reactivating

**Comment by clovisnicolas** [comment]
I've been working on this https://github.com/clovisnicolas/flutter_contacts 
As of now, you may only fetch/search contacts and add one, it's still missing features such as update/delete an existing contact.

**Comment by lukasgit** [comment]
@eseidelGoogle @mit-mit This is a pretty important need for flutter to be production-ready

**Comment by mit-mit** [comment]
If this is important to you, please hit the 'thumb up' button on the *top-most* comment of the bug. That is our main signal for gauging interest.

**Comment by korenzerah** [comment]
@clovisnicolas 
> I've been working on this https://github.com/clovisnicolas/flutter_contacts
> As of now, you may only fetch/search contacts and add one, it's still missing features such as update/delete an existing contact.


It's really good! but updating a contact/multiple contacts is necessary, any plans on implementing this functionality?
Thanks ahead.

**Comment by ericmand** [comment]
Another limited plugin: https://github.com/BaseflowIT/flutter-contacts-plugin
Last update was 3 months ago. I couldn't get it to work but also didn't try hard. Claims to do the following:
Done: Automatically check and request the necessary permissions to access the platform specific Done: address book;
Done: Read contacts from the address book;
[WIP] Store new contacts in the address book;
[WIP] Update details of existing contacts;
[WIP] Delete existing contacts from the address book.

**Comment by Hixie** [comment]
Realistically, we're not going to create a first-party plugin for this. This is the perfect kind of thing for a plugin from the wider community. I agree that attempts so far have not all been successful at addressing the full scope of the issue, but in that case, I can only recommend contributing to those packages.

**Comment by lukasgit** [comment]
@Hixie @zoechi @ericmand @korenzerah @mit-mit @eseidelGoogle 

I'm responsive to PR's for https://pub.dev/packages/contacts_service

Github repo @ https://github.com/lukasgit/flutter_contacts
