### ISSUE TITLE
FadeInImage is not clipped when BoxDecoration is applied

### ISSUE THREAD

**Issue by munukutla** [flutter/flutter#25615]
## Steps to Reproduce

1. Add a container with a box decoration and set decoration shape to circle.
2. Add a `FadeInImage` to the container as a child

## Expected
The `FadeInImage` is clipped as a circle.

## Observed
It appears in its original shape.

This was referenced in #7289 previously and marked as fixed. But it doesn't seem to work with `FadeInImage`

## Sample code
```dart
UserAccountsDrawerHeader(
      accountName: Text("James Watson"),
      accountEmail: Text("james@gmail.com"),
      currentAccountPicture: Container(
           decoration: BoxDecoration(
                  shape: BoxShape.circle,
           ),
           child: FadeInImage.memoryNetwork(
                  fit: BoxFit.cover,
                  placeholder: kTransparentImage,
                  image: 'https://github.com/flutter/website/blob/master/src/_includes/code/layout/lakes/images/lake.jpg?raw=true',
             )
      )
)
```
## Logs

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.0.0 at /Users/cm/apps/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/cm/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone XR • E85C316D-6121-4726-9D10-3333384BEF6E • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Sounds similar to https://stackoverflow.com/questions/53849631/flutter-imageasset-image-extending-outside-boxdecoration-container

**Comment by zoechi** [comment]
Probably related https://github.com/flutter/flutter/issues/25028#issuecomment-446388091
#24225

**Comment by zoechi** [comment]
```dart
    ClipRRect(
      borderRadius: BorderRadius.circular(35),
      child: FadeInImage(
```

**Comment by munukutla** [comment]
Oh damn, I missed that. Your sample works. Works without the decoration as well, btw.
```dart
UserAccountsDrawerHeader(
              accountName: Text("James Watson"),
              accountEmail: Text("james@gmail.com"),
              currentAccountPicture: Container(
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(35),
                  child: FadeInImage(
                    fit: BoxFit.cover,
                    placeholder: AssetImage(
                      'food/cherry_pie.png',
                      package: 'flutter_gallery_assets',
                    ),
                    image: NetworkImage(
                        'https://github.com/flutter/website/blob/master/src/_includes/code/layout/lakes/images/lake.jpg?raw=true'),
                  ),
                ),
              ),
            )
```

**Comment by amervelic** [comment]
same problem 

![Image Profile](https://i.imgur.com/Qc8AfCv.png)
![Image problem](https://i.imgur.com/30MwYtp.png)

**Comment by amervelic** [comment]
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G5019, locale en-BA)
    • Flutter version 1.0.0 at /Volumes/Backup/flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/amervelic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3  

 • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

**Comment by amervelic** [comment]
```
UserAccountsDrawerHeader(
              accountName: Text("James Watson"),
              accountEmail: Text("james@gmail.com"),
              currentAccountPicture: Container(
              
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(35),
                  child: FadeInImage(
                    fit: BoxFit.cover,
                    placeholder: AssetImage(
                      'images/profil.jpg',                      
                    ),
                    image: NetworkImage(
                        'https://github.com/flutter/website/blob/master/src/_includes/code/layout/lakes/images/lake.jpg?raw=true'),
                  ),
                ),
              ),
            ),
```

**Comment by Allan-Nava** [comment]
If I used inside a page more one FadeInImage, it freezes all interface. What can I fix this problem?

**Comment by chornbe** [comment]
Try wrapping it all in a Center(...). Fixed it for me with ZERO understanding why. :(
