### ISSUE TITLE
Trouble parsing Json Array 

### ISSUE THREAD

**Issue by lightyaer** [flutter/flutter#25627]
Here is my simple Todo App using Flutter and Node/Express API's and MongoDB
I am specifically having a problem with parsing json array of todo items.

[Todo App](https://github.com/lightyaer/Xmoov-Frontend)

First of all when ever I run this project.
I get this error
### **Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>.**
Nothing in the debug console.

After Reloading a few times, I land on Login Page,
Then enter credentials and login, 
Immediately, the app is frozen and I get the Above error.
If you look at lib/services/todoService.dart  => getAll() method.
Am I doing something wrong? 

Secondly,
The json returned from server is as below, and I need to parse it to a List<Todo> in Dart.
I tried following [this](https://flutter.io/docs/cookbook/networking/background-parsing)
I get the same error as above.
`[
    {
        "completed": true,
        "completedAt": 1545314655878,
        "_id": "5c0244d8ac3baf291808b03a",
        "text": "Shop some Groceries",
        "_author": "5c02449eac3baf291808b037",
        "__v": 0
    },
    {
        "completed": false,
        "completedAt": null,
        "_id": "5c1b9a14fe8f70360cd0a393",
        "text": "Eat before 12",
        "_author": "5c02449eac3baf291808b037",
        "__v": 0
    },
    {
        "completed": false,
        "completedAt": null,
        "_id": "5c1ba02efe8f70360cd0a394",
        "text": "Test todo",
        "_author": "5c02449eac3baf291808b037",
        "__v": 0
    }
]`

My Todo Class looks like this
```
class Todo {
  final String text;
  final String author;
  final bool completed;
  final DateTime completedAt;
  final String id;

  Todo(
      {this.author = "",
      this.id = "",
      this.completed = false,
      DateTime completedAt,
      this.text = ""})
      : completedAt = completedAt ?? DateTime.now();

  factory Todo.fromJson(Map<String, dynamic> json) {
    return Todo(
      text: json['text'],
      author: json['_author'],
      completed: json['completed'],
      completedAt: DateTime.fromMillisecondsSinceEpoch(json['completedAt']),
      id: json['_id'],
    );
  }
}
```
I cant find a good way to parse it into a List<Todo> and return it to a FutureBuilder.
## Logs

 I use VS Code, No Errors in the debug Console.

```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-IN)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\lightyaer\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\lightyaer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\lightyaer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by lightyaer** [comment]
Oops, Sorry, 
The Error was coming due to this line 
DateTime.fromMillisecondsSinceEpoch(json['completedAt'])
in the Todo Class,

Changed the completedAt to a String and 
replaced it with 
json['completedAt'] == null ? json['completedAt'].toString() : "",

It worked. Thanks.
