### ISSUE TITLE
Redundant Code in getting started

### ISSUE THREAD

**Issue by Isfaaq** [flutter/flutter#25625]
Hi all. Please see the attached capture. I believe that the modified line 10 in the diff is redundant. I am willing to change it, if someone could indicate the directory in which the docs are located.
![screenshot from 2018-12-20 20-22-51](https://user-images.githubusercontent.com/17203172/50296995-26da7500-0495-11e9-986a-12551336c7f5.png)

**Comment by zoechi** [comment]
What do you mean by redundant?
This diff shows the code before (red) and after (green) the change.
The line 10 was replaced by the first green line.

**Comment by Isfaaq** [comment]
@zoechi The line 10 which is in green may be replaced without affecting the final application, hence it is redundant.

**Comment by zoechi** [comment]
You mean because there is no AppBar to show it?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2102](https://github.com/flutter/website/issues/2102) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Isfaaq** [comment]
@zoechi I am quite new to this, but from what I gather _appBar_ title from here:
```@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text('Startup Name Generator'),
    ),
    body: _buildSuggestions(),
  );
}```

is rendered above the one here I initially mentioned.

**Comment by zoechi** [comment]
In the end result there will be only a single `title: ...` line because the red stuff is removed.

I still think I don't get what you are up to.
I moved the issue to https://github.com/flutter/website/issues/2102 and the discussion should be continued there as well otherwise this will be even more chaos.
