### ISSUE TITLE
 [improve] SliverAppBar should be more flexible

### ISSUE THREAD

**Issue by fanybook** [flutter/flutter#25629]
SliverAppBar should be more flexible. When scrolling more than half the height of SliverAppBar, it should be hidden or displayed, otherwise it should be back to its original position.

**Comment by fanybook** [comment]
another improve:
SliverAppBar's scrolling should have the highest priority when body(eg. sub_page) has scrolling.

expected effect:
In a scroll action, the preference is SliverAppBar . After the SliverAppBar was displayed/hidden, continue scrolling the body(eg. sub_page).

**Comment by goderbauer** [comment]
I do not understand what this feature request is for. Could you post some runnable example code that shows the current behavior and explain what behavior you would like to see on that example?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
