### ISSUE TITLE
Dismissable has an LTR bias

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2562]
DismissDirection has a left/right.  A similar API in Android is specified logically: http://developer.android.com/reference/android/support/design/widget/SwipeDismissBehavior.html

It's not completely obvious which way is better but we might want to try using a logical direction.

/cc @HansMuller @Hixie

**Comment by Hixie** [comment]
sgtm either way.

**Comment by HansMuller** [comment]
We could also use start and end to mean left and right for LTR locales and right, left for RTL locales.  Using start and end isn't as transparently obvious as left,right but we need the flexibility.
