### ISSUE TITLE
Flutter doctor never finishes

### ISSUE THREAD

**Issue by jimrome** [flutter/flutter#25624]
## Steps to Reproduce

1. ... `flutter -v doctor -v`
2. ...On MacOS Mojave
3. ... 
```
JARMAC:~jar$ cd /Volumes/macHD3/flutter
JARMAC:flutter jar$ flutter -v doctor -v
```
And there it sits

## Logs
```
JARMAC:~ jar$ cd /Volumes/macHD3/flutter
JARMAC:flutter jar$ flutter -v doctor -v
[  +29 ms] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Volumes/MacHD3/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[   +1 ms] executing: [/Volumes/MacHD3/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +21 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa

```

**Comment by jimrome** [comment]
JARMAC:flutter jar$ which git
/Applications/Xcode.app/Contents/Developer/usr/bin/git

**Comment by jimrome** [comment]
I downloaded the zip file, unzipped it, added the bin directory to my path, and ran flutter -v doctor -v from the main flutter directory.

**Comment by jimrome** [comment]
I downloaded the dmg in https://flutter.io/docs/get-started/install/macos
Clearly this dmg is damaged somehow.
Cloning the git directory seems to be working. 
Better fix the HowTo page.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2103](https://github.com/flutter/website/issues/2103) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jimrome** [comment]
It is just a suggested location. But I moved it to ~/development/flutter, and it stops at the same place:

> [  +10 ms] Downloading Gradle Wrapper...
[   +1 ms] Downloading:
https://storage.googleapis.com/flutter_infra/gradle-wrapper/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa
/gradle-wrapper.tgz
[ +357 ms] Received response from server, collecting bytes...
[  +96 ms] Downloading Gradle Wrapper... (completed)
[        ] executing: tar -xzf
/Users/jar/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/gradle-wrapp
er/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa/gradle-wrapper.tgz -C
/Users/jar/development/flutter/bin/cache/artifacts/gradle_wrapper
[  +13 ms] Exit code 0 from: tar -xzf
/Users/jar/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/gradle-wrapp
er/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa/gradle-wrapper.tgz -C
/Users/jar/development/flutter/bin/cache/artifacts/gradle_wrapper

 It did work building it on Linux.

**Comment by zoechi** [comment]
Perhaps related to your installed Java version

**Comment by jimrome** [comment]
I also carefully checked my Java version. Running Openjdk 11.0.1. But it still stops:
JARMAC:flutter jar$ flutter -v doctor -v
[  +27 ms] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Volumes/MacHD3/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[   +1 ms] executing: [/Volumes/MacHD3/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +18 ms] Exit code 0 from: gi

**Comment by zoechi** [comment]
What version do you have installed on the Linux system?

**Comment by zoechi** [comment]
I'd try JDK 8 instead of 11

**Comment by jimrome** [comment]
Also 11 on Linux. I do not have 8, but 9 gives the same results
JARMAC:flutter jar$ alias java9="export JAVA_HOME=`/usr/libexec/java_home -v 9` ; java -version"
JARMAC:flutter jar$ java9
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
JARMAC:flutter jar$ flutter -v doctor -v
[  +27 ms] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Volumes/MacHD3/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%H
[  +43 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[   +1 ms] executing: [/Volumes/MacHD3/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +19 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa

**Comment by jimrome** [comment]
How can we debug this?

**Comment by jimrome** [comment]
I still cannot get flutter to work on my Mac.:
JARMAC:bin jar$ pwd
/Volumes/MacHD3/flutter/bin
JARMAC:bin jar$ flutter -v doctor -v
[  +27 ms] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Volumes/MacHD3/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Volumes/MacHD3/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Volumes/MacHD3/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[   +1 ms] executing: [/Volumes/MacHD3/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
^C .... after a day...
JARMAC:bin jar$
So I tried the Android SDK, loading the flutter and Dash plugins. But when I go to create a flutter application, it hangs.

**Comment by jimrome** [comment]
I still cannot get flutter to work following the steps on https://flutter.io/docs/get-started/install/macos
flutter doctor hangs up as shown above. I have tried it in several directories, and always get the same results. Is there some way of knowing what flutter doctor is choking on.

**Comment by zoechi** [comment]
Perhaps you just need to wait longer. I have seen it mentioned that it can take up to 10 mins.

**Comment by jimrome** [comment]
I waited overnight!

**Comment by biscoe916** [comment]
I was using fish, and ran into this issue. By switching to bash, flutter doctor -v worked.

**Comment by ameennio** [comment]
i got a problem, flutter doctor is stuck, i was wait for more then 2 house i though is updating or something but still doesn't work.. any help plz
