### ISSUE TITLE
Let CupertinoNavigationBar Hero transition between Navigators

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25622]
Two ways to push to next screen in cupertino, which are:

```dart
Navigator.of(context, rootNavigator: true).push(
      new CupertinoPageRoute(
        builder: (c) {
          return new ChatPage(sess: session);
        },
      ),
    );
```

it will do something like this:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/21303438/50290570-0ca99280-04a7-11e9-9795-ad3b6e270c77.png">

But once disable the `root` option, there will have a nice transition animation between 2 screen titles.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/21303438/50290645-4a0e2000-04a7-11e9-895f-f2a5f2d81e5e.png">

**the question is, I want the second one animation, so I set root as false............ then problem comes, but first page has a bottombar, it can not be hide .................**

Is there anyway to make this?

**Comment by jinfagang** [comment]
@xster Just for our previous discussion, clarifying what I am chasing for....... if there is any help information about this, pls let me know

**Comment by xster** [comment]
Ah ok, I understand your question now. Thanks for the screenshots. 

So your request is basically:
1- Navigate through multiple navigators (to the navigator above the CupertinoTabBar)
2- and have the CupertinoNavigationBar between those screens do a Hero transition

That would be a new feature that isn't currently supported. 

In the meantime, an easy work around (I haven't tested it) is to not put a CupertinoTabView in the body of the first tab. Then the tab and your second page would all be in the same navigation stack. A normal `rootNavigator: false` will put the second page on top of the tab and you get the CupertinoNavigationBar transition.

**Comment by xster** [comment]
I looked at WeChat a bit and WeChat doesn't do parallel navigations at all. So you don't really need to have CupertinoTabViews in any tabs or use `rootNavigator: true` at all. Everything is just under one single navigator.

**Comment by jinfagang** [comment]
@xster Thanks, you finally understand what I mean, but, I need the transition animation above nav bar is right, it can be done by set `rootNavigator` as true, **but my first screen has a bottom tab, this tab can not be hide if rootNavigator is true**.

So, I wanna the animation as well as bottom bar hide which is exactly wechat does.

However, it sounds like not supported yet, but you now, iOS has a push method, which do the animation by default, but it supports hide bottom bar in inspects attributes or in code.

You can check XCode to see that if you have time. So I suppose Flutter can also support for this, cause without this animation, obsessive can not get live with that..............

**Comment by xster** [comment]
I'm changing this issue a bit. 

Your original request (of following WeChat's pattern) is already supported. You just need to use the same Navigator in all the tabs. https://stackoverflow.com/questions/53890280/using-flutters-cupertino-widgets-how-do-i-trigger-a-horizontal-page-transition.

What's not supported is mixing tabs where some tabs navigate horizontally above the tab bar and some navigate horizontally inside the tab. But that's a very confusing IA and likely a low priority for support. 

I'm not sure I understood your last reply. Feel free to comment in Chinese too.

**Comment by jinfagang** [comment]
@xster  Thanks, from the stackoverflow https://stackoverflow.com/questions/53890280/using-flutters-cupertino-widgets-how-do-i-trigger-a-horizontal-page-transition your answer seems is exactly what I want, I just need a CupertinoTableView widget to cupertino scaffold.
让我尝试一下看看，大佬居然能看懂中文，牛逼啊
