### ISSUE TITLE
webview_flutter ios disable native fullscreen video

### ISSUE THREAD

**Issue by lgArlequin** [flutter/flutter#25630]
Is there a way to disable the fullscreen of the videos in html5?
I do not know if it is already included in the plugin.
I know it has to do with the following parameter:
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614793-allowsinlinemediaplayback

**Comment by srbang** [comment]
Any update on this?

**Comment by lgArlequin** [comment]
Any news?

**Comment by Praveena0989** [comment]
Any update on this?

**Comment by SteadyAction** [comment]
any?

**Comment by lgArlequin** [comment]
Hi, if anyone is still interested, I could temporarily solve the problem with a fork of the plugin and editing only one line!

Add this:
`configuration.allowsInlineMediaPlayback = true;`

Approximately in this line:
https://github.com/flutter/plugins/blob/6deda07662e420d747896a886518fd2855451fde/packages/webview_flutter/ios/Classes/FlutterWebView.m#L71

**Comment by srbang** [comment]
I just returned to Swift. IMHO, Flutter isn't quite ready for prime time yet.

**Comment by alexmarkley** [comment]
I have been maintaining a (very simple) pull request to address this issue here: https://github.com/flutter/plugins/pull/2309

Just a quick note to indicate that my pull request could definitely use some care and attention from the package maintainers.

Thanks!

**Comment by zodiark23** [comment]
Hi any updates on this?

**Comment by zodiark23** [comment]
> Hi, if anyone is still interested, I could temporarily solve the problem with a fork of the plugin and editing only one line!
> 
> Add this:
> `configuration.allowsInlineMediaPlayback = true;`
> 
> Approximately in this line:
> https://github.com/flutter/plugins/blob/6deda07662e420d747896a886518fd2855451fde/packages/webview_flutter/ios/Classes/FlutterWebView.m#L71

@lgArlequin how did you include it in your project? Sorry just starting out with flutter

**Comment by lgArlequin** [comment]
@zodiark23 You can download the plugin repository, edit the file and install it from your machine.
In this link, look path dependency:
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by lgArlequin** [comment]
1 year and a half...

**Comment by montogeek** [comment]
Any update for this feature?

**Comment by lgArlequin** [comment]
Almost 2 years...

**Comment by LoShengMin** [comment]
> @zodiark23 You can download the plugin repository, edit the file and install it from your machine.
> In this link, look path dependency:
> https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

Hi @lgArlequin, @zodiark23 
Sorry, I'm also facing the same problem but I still on don't know how to add `configuration.allowsInlineMediaPlayback = true;
` to fix this problem. Can you let me know how to do it? Thank you very much.

**Comment by adeolaex** [comment]
@ShengMin88 This may vary according to your OS but generally, you have to navigate to your downloaded flutter folder called `flutter`. Go one folder into `flutter`, enable hidden files move one folder up into `.pub-cache`, another folder up into `hosted` and finally `pub.dartlang.org` 

The `webview` package should be there. Just follow the path @zodiark23 provided. Although it has changed slightly since then to https://github.com/flutter/plugins/blob/master/packages/webview_flutter/ios/Classes/FlutterWebView.m#L93

**Comment by ShengMin88** [comment]
> @ShengMin88 This may vary according to your OS but generally, you have to navigate to your downloaded flutter folder called `flutter`. Go one folder into `flutter`, enable hidden files move one folder up into `.pub-cache`, another folder up into `hosted` and finally `pub.dartlang.org`
> 
> The `webview` package should be there. Just follow the path @zodiark23 provided. Although it has changed slightly since then to https://github.com/flutter/plugins/blob/master/packages/webview_flutter/ios/Classes/FlutterWebView.m#L93

Hi @adeolaex 
Thank you very much. I fix this problem in my app. This time, I just modified one file to fix this problem
File name: Flutter Plugins => webview_flutter-1.0.7 => ios => Classes => FlutterWebView.m
Added `configuration.allowsInlineMediaPlayback = true`; ```
under the (void)updateAutoMediaPlaybackPolicy:(NSNumber*)policy
                      inConfiguration:(WKWebViewConfiguration*)configuration {
```

**Comment by lgArlequin** [comment]
I think this is solved, I close the issue.
