### ISSUE TITLE
flutter run -t lib/main_dev.dart failing for ios

### ISSUE THREAD

**Issue by z3nz** [flutter/flutter#25637]
## Steps to Reproduce

```bash
$ flutter run -t lib/main_dev.dart                      
Launching lib/main_dev.dart on Jennifer's iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: QLBPPZS6XY
Starting Xcode build...                                          
Xcode build done.                                            3.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc
    Inference" build setting to "Default" for the "Runner" target.
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc
    Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The path lib/main.dart does not exist
    Command /bin/sh failed with exit code 255

Could not build the precompiled application for the device.

Error launching application on Jennifer's iPhone.
```

The command does work as expected if the file is named `main.dart`
#9814 

## Logs

```
$ flutter run -t lib/main_dev.dart --verbose > build-log
[  +10 ms] Could not build the precompiled application for the device.
[   +6 ms] Error launching application on Jennifer's iPhone.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:404:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

[Here is the verbose log output](https://gist.github.com/z3nz/108a239e4a483f93c9dd846c90647e76)

```
$ flutter analyze 
Analyzing mobile...                                              
No issues found! (ran in 1.9s)
```

```
$ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
Can you please try to create the file `lib/main.dart`?
Then check if you use `-t lib/main_dev.dart` if it actually executes `lib/main_dev.dart` or `lib/main.dart`.

**Comment by zoechi** [comment]
Comments in #10199, #9814 suggest that it insistes of `lib/main.dart` to exist even when an alternative entry-point file is specified.

**Comment by z3nz** [comment]
@zoechi sorry, I should have mentioned that I did try that and it ends up using the `main.dart` instead of the one specified.

**Comment by shorben07** [comment]
I had a similar error with flavors in iOS project. But it turned out that it was an issue with configuration in my project. @z3nz if you don't use flavors then you can add them to workaround the problem 
Guide how to add flavors https://flutter.dev/docs/deployment/flavors

Here is my checklist:
1. Files in correct folder on disk ios/Flutter
<img width="687" alt="Снимок экрана 2019-04-18 в 22 24 43" src="https://user-images.githubusercontent.com/36268266/56385838-e1526c80-6228-11e9-9a33-e904261eb4a3.png">
2. xcconfig files assigned correctly to Configurations
<img width="733" alt="Снимок экрана 2019-04-18 в 22 24 15" src="https://user-images.githubusercontent.com/36268266/56385925-1a8adc80-6229-11e9-93ca-b9d05c6ee1b8.png">
3. Cocoa Pod xcconfig is included to you project xcconfig
<img width="734" alt="Снимок экрана 2019-04-18 в 22 25 09" src="https://user-images.githubusercontent.com/36268266/56385934-270f3500-6229-11e9-9ba8-34ba375d8d07.png">
After that you can remove lib/main.dart run 
`flutter run --flavor prod --target lib/main_prod.dart`

**Comment by Sonius94** [comment]
I have the same issue as @z3nz If I try to run my dev flavor with `flutter run -t lib/main_dev.dart --flavor main_dev` I get the following error output

```
Xcode build done.                                            1,8s
Failed to build iOS app
Error output from Xcode build:
↳
    2019-06-04 14:15:26.774 xcodebuild[36891:720800]  DTDeviceKit: deviceType from 048019512cd023c157b49ee9befb8f545258d8f4 was NULL
    2019-06-04 14:15:26.829 xcodebuild[36891:720793]  DTDeviceKit: deviceType from 048019512cd023c157b49ee9befb8f545258d8f4 was NULL
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION MYCONFIG ===
    The path lib/main.dart does not exist
    Command /bin/sh failed with exit code 255

Could not build the precompiled application for the device.

Error launching application on Toms iPhone.

```

If I try to run the app from XCode I get the following error in xcode: `/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory`

I also tried already to create a main.dart file. If I do so the runner starts that new file

**Comment by jiexunsee** [comment]
Hi, I was facing the same issue where I used run configurations to select a custom entry point, but xcode/flutter still looked for lib/main.dart. I was also using flavors/schemes in the project. 

Doing `pod install` generates a Flutter/Generated.xcconfig file, as well as any other config files for running the app in your various configurations. In the Generated.xcconfig file, the FLUTTER_TARGET gets set correctly, according to the run configuration used in Android Studio. Thus the issue was that my Pods-Runner-debug.xcconfig files did not include the Generated.xcconfig file that contained this correctly set FLUTTER_TARGET. After including the Generated.xcconfig file in my pods xcconfig files, this issue is fixed.

This was done by adding a line to the Pods-Runner-debug.xcconfig.
`#include "[path to flutter project]/ios/Flutter/Generated.xcconfig"`

**Comment by jmagman** [comment]
I just tested this and was able to `flutter run -t lib/main_dev.dart` without a `main.dart` file.  @z3nz  are you seeing this on recent Flutter builds?  Or were you hitting a flavor issue as @shorben07 @tomkastek and @jiexunsee suggested?

**Comment by z3nz** [comment]
Sorry, I don't have access to the repo I was working on anymore since it was at my previous job. This was submitted just over a year ago so I have no idea if it was fixed within that time frame. Probably is, but I just have no way of testing it. Thanks.

**Comment by lexyfeito** [comment]
Hello, i have kinda the same problem. For me running `flutter build ios -t ./lib/main_staging.dart` works. But, when i go and do archive xcode does its own build and uses `main.dart` when i really want to use `main_prod.dart` to release to production of cource. i think this needs to be setup at xcode level, but i dont know how. Any suggetions?

**Comment by jmagman** [comment]
@lexyfeito `ios/Flutter/Generated.xcconfig` (generated, don't edit) should set `FLUTTER_TARGET=lib/main_prod.dart` if you run `flutter build ios -t ./lib/main_prod.dart --release` first.  
This issue is closed.  Please file a new issue if that doesn't work.
