### ISSUE TITLE
Engine should be much more graceful about failing when snapshot version doesn't match

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2564]
If you try to use an engine version X with a snapshot version Y, we crash hard and display little to no useful information.
- [ ] We should not crash in that case. We should exit gracefully.
- [ ] We should dump substantial useful information to the console.
- [ ] We should make sure the flutter tool shows this information in the case of running `flutter run; flutter logs`, even if the exit happens before `flutter logs` has had a chance to start.
- [ ] We should probably also display a message on the device.

**Comment by chinmaygarde** [comment]
After the shell refactor, the engine wont crash but just not initialize the shell. It will print an error log says that launch failed because of snapshot versions mismatch (it will print both). We do not want to exit at all because there may be other shells waiting for launch.
