### ISSUE TITLE
How to release iOS package on Macbookpro without an iOS device?

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#25647]
Hi, I followed this ios guide https://flutter.io/docs/deployment/ios. but in my Xcode, it reports the error `Failed to create provisioning profile. There are no devices registered in your account on the developer website. Plug in and select a device to have Xcode register it.` in `Review Xcode project settings` section after choosing my `team`. 

But I don’t have any apple devices. How to fix it? I did google it. I don’t really find any solutions that work or I can understand.. such as [link1](https://stackoverflow.com/questions/39603667/failed-to-create-provisioning-profile) or [link2](https://stackoverflow.com/questions/45204842/xcode-8-asks-for-a-device-to-be-registered-to-create-provisioning-profile).

Are there any easy way to solve this error? Thanks a lot.

**Comment by peterlazar1993** [comment]
Have you selected `Product > Destination > Generic iOS Device` and then created an archive `Product > Archive`

**Comment by sgon00** [comment]
@peterlazar1993 thank you very much for the reply. Sorry, I haven't tried that. The Xcode UI completely confuses me. 
I can not test this anymore because I borrowed an iphone device from my friend and registered it in Xcode, and continued on next steps after searching for 2 hours without a clear help guide. 
I think I simply close this issue and assume the step you provided should work. I hope this can be documented in https://flutter.io/docs/deployment/ios. 
Thank you very much again for this help.
