### ISSUE TITLE
5 warnings in xcode

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#25648]
I am following this guide https://flutter.io/docs/deployment/ios and completed all sections before `Add an App Icon`. I have tested my app on android devices and this is the first time I am trying to make an iPhone build. Thus, I never run this app in any iPhone devices or Simulators before. Please check the following screenshot:

![screen shot 2018-12-21 at 14 19 32](https://user-images.githubusercontent.com/1555508/50327965-15907780-052c-11e9-9af0-ae9999ce79c3.png)

I followed the exact steps from the link I posted above. I haven't tried to run it on simulator and never run `flutter run` on iphone devices. I am not the kind of person who does not follow the documentation, so I don't want to try anything else before asking here. 

Can anyone please let me know the above screenshot and warnings are good and expected or not?

Because it does not look the same as ![](https://flutter.io/images/releaseguide/xcode_settings.png)

The above official screenshot does not show any warnings at all. 

I found those warning/error messages at this issue https://github.com/flutter/flutter/issues/12725, but I don't really understand it. It seems the person who reported that issue was trying to build the package and got those errors from `flutter build ios`. but I get these errors from Xcode window before building anything. 

Thank you very much for your help. 

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.0.1-pre.3, on Mac OS X 10.13.6 17G4015, locale en-CN)
    • Flutter version 1.0.1-pre.3 at /Users/user/opt/flutter
    • Framework revision d74b1c2051 (13 days ago), 2018-12-07 14:19:09 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available
```

**Edited:** One more screenshot:

![screen shot 2018-12-21 at 14 35 35](https://user-images.githubusercontent.com/1555508/50328379-d7945300-052d-11e9-92d4-fc71af6d735d.png)

**Comment by zoechi** [comment]
If you created the project with an older Flutter version, it could just be https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by sgon00** [comment]
@zoechi Thanks a lot for the quick reply. I did the following:

```
$ cd <prejctRoot>
$ rm -rf ios/
$ flutter create .

Recreating project ....
  .idea/libraries/KotlinJavaRuntime.xml (created)
  android/app_android.iml (created)
  ios/Runner/AppDelegate.h (created)
  ios/Runner/AppDelegate.m (created)
  ios/Runner/main.m (created)
  ios/Runner.xcodeproj/project.pbxproj (created)
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  ios/Flutter/AppFrameworkInfo.plist (created)
  ios/Flutter/Debug.xcconfig (created)
  ios/Flutter/Release.xcconfig (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  ios/Runner/Base.lproj/Main.storyboard (created)
  ios/Runner/Info.plist (created)
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  ios/Runner.xcworkspace/contents.xcworkspacedata (created)
Wrote 38 files.

All done!
[✓] Flutter is fully installed. (Channel master, v1.0.1-pre.3, on Mac OS X 10.13.6 17G4015, locale en-CN)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices is partially installed; more components are available. (Xcode 9.4.1)
[✓] Android Studio is fully installed. (version 3.1)
[✓] VS Code is fully installed. (version 1.30.1)
[!] Connected device is not available.

Run "flutter doctor" for information about installing additional components.
```

And then re-launch **Xcode.app**. The 5 warnings are still there. Anything else I should try? Thanks.

**Comment by zoechi** [comment]
I'd try running `flutter build --ios` from a terminal in the project directory.

**Comment by sgon00** [comment]
@zoechi Thank you very much to encourage me to build first. After running `flutter build ios`, the build is successful and 4 errors are gone in Xcode. There are only 1 warning left which is `Update to recommended settings` which I think I can simply ignore. I am the kind of person who never skip steps. Up to the end of section `Review Xcode project settings`, I don't see the requirement to run this build command. 😄 I hope the doc can be updated to make this clear. Otherwise the screenshot https://flutter.io/images/releaseguide/xcode_settings.png may confuse newbies like me. Thank you very much for your help and closing it.

**Comment by sgon00** [comment]
@zoechi maybe, no. I am new to Xcode and apple things. I am not sure if it's related. Because I only develop and test apps on Android. Today, it's the first time I try to build a package for iPhone. And followed the steps in the doc https://flutter.io/docs/deployment/ios. 

#12774 is talking about "running Archive from Xcode", but I don't run anything yet. I just opened the project in Xcode and followed that doc. That doc doesn't ask me to run anything up to the end of section **Review Xcode project settings**. Maybe this is not very important at all. People may find out they can get rid of those warnings after building the package. It just confuses me when I don't want to skip steps. People may not find these errors if they test apps in iPhone Simulator before too since I never run iPhone simulator before. Anyway. Thanks.

**Comment by zoechi** [comment]
As far as I know `flutter run ios --release` sets a flag to `release` in Xcode project config which causes issues in the release process if not set. But I don't have deep knowledge here either.
Glad to hear it worked for you ;-)

**Comment by sgon00** [comment]
@zoechi  oh, I never knew that. Thank you very much for your help.
