### ISSUE TITLE
[google_maps_flutter] Ability to add custom data to Marker object just as web javascript version

### ISSUE THREAD

**Issue by kaushiksamanta** [flutter/flutter#25641]
There is no way to attach custom ```map<string, dynamic>``` in the marker object. I want add custom data to marker object and on tap of that marker i want to extract the details.

**Comment by timtraversy** [comment]
Every marker can be given an `id` string, so you could map these to your custom data i.e. 
`Map<String,<Map<String, dynamic>>` and query that on taps.

**Comment by kaushiksamanta** [comment]
> Every marker can be given an `id` string, so you could map these to your custom data i.e.
> `Map<String,<Map<String, dynamic>>` and query that on taps.

How can I do that addMarker method takes only MarkerOptions object and marker options does not have any id field.

**Comment by timtraversy** [comment]
`addMarker` creates a unique ID when it is creating a new marker, and it asynchronously returns a `Marker` object with `id` and `options` parameters. I’m not at an IDE but I think you can do something like:
```
final marker = controller.addMarker(...)
final id = marker.id
```

**Comment by kaushiksamanta** [comment]
> `addMarker` creates a unique ID when it is creating a new marker, and it asynchronously returns a `Marker` object with `id` and `options` parameters. I’m not at an IDE but I think you can do something like:
> 
> ```
> final marker = await controller.addMarker(...)
> final id = marker.id
> ```

Got it. Thanks

**Comment by darshankawar** [comment]
@kaushiksamanta 
Did [above](https://github.com/flutter/flutter/issues/25641#issuecomment-449452824) solution help you to resolve your use case ? 
If so, can this issue be closed ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
