### ISSUE TITLE
platform exception with firebase google_sign_in

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#25640]
Trying to sign in with google but always get this exception:
`PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)`

- I have added SHA1 and SHA 256 to the project 

- I have enabled sign in with google in firebase console 

- I have updated version of `google_services.json` file 

**code to sign in:**
 ```dart
Future<FirebaseUser> _incrementCounter() async {
    
      GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
      GoogleSignInAuthentication gsa = await googleSignInAccount.authentication;

      FirebaseUser user = await _auth.signInWithGoogle(
          idToken: gsa.idToken, accessToken: gsa.accessToken);

      print("user name: ${user.displayName}");
      return user;

  }

```

**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.194], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.2)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = C:\Program
    X Android Studio not found at C:\Program
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] VS Code, 64-bit edition (version 1.29.1)
[!] Connected device
    ! No devices available

```

**Comment by zoechi** [comment]
I'd expect there to be more error output than the line you posted.

**Comment by zoechi** [comment]
Might be #23049

**Comment by mohamed6996** [comment]
I just used the template provided when you create a new project, just modified the _increamentCounter method to sign in with google instead of incrementing the counter.
```

import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:firebase_auth/firebase_auth.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  final GoogleSignIn _googleSignIn = GoogleSignIn();
  final FirebaseAuth _auth = FirebaseAuth.instance;

  Future<FirebaseUser> _incrementCounter() async {
    GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
    GoogleSignInAuthentication gsa = await googleSignInAccount.authentication;

    FirebaseUser user = await _auth.signInWithGoogle(
        idToken: gsa.idToken, accessToken: gsa.accessToken);

    print("user name: ${user.displayName}");
    return user;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),

            Text(
              '$_counter',
              style: Theme
                  .of(context)
                  .textTheme
                  .display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by zoechi** [comment]
I'd suggest you try with https://github.com/flutter/plugins/blob/master/packages/google_sign_in/example/lib/main.dart

**Comment by diegoveloper** [comment]
are you testing on your android device , or android emulator with google play services installed?

**Comment by mohamed6996** [comment]
my physical device
android Oreo

**Comment by diegoveloper** [comment]
what device is ? model/brand ?  do you have google play services updated?

**Comment by mohamed6996** [comment]
Honor 7c
have the latest update

**Comment by diegoveloper** [comment]
hmmm could you try using this code: 

```
Future<FirebaseUser> _incrementCounter() async {
    final GoogleSignIn _googleSignIn = GoogleSignIn();
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    if (googleUser == null) return null;
    final result = await googleUser.authentication;
     FirebaseUser user = await _auth.signInWithGoogle(
         idToken: result.idToken, accessToken: result.accessToken);  print("user name: 
     ${user.displayName}");
     return user;
 }
```

**Comment by mohamed6996** [comment]
same error appears

**Comment by diegoveloper** [comment]
Hmm it's working for me. Are you user your credentials are correct?

**Comment by mohamed6996** [comment]
I have noticed something weird!
i have created another two projects to test this problem and every time i generate the SHA 1 finger print 
i always get the same SHA 1 
is this behavior is correct?

i use the terminal to generate it using the following snippet 

**keytool -exportcert -list -v \
-alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore**

**Comment by diegoveloper** [comment]
Yes, because is the same keystore.

**Comment by zoechi** [comment]
@mohamed6996 https://developer.android.com/studio/publish/app-signing should explain it. I'm sure there is more available in the internet (StackOverflow, ...)

**Comment by zoechi** [comment]
@mohamed6996 glad to hear and thanks for the update.
I assume this issue can be closed. Feel free to add a comment to have it reopened if you disagree.

**Comment by MaxZubko** [comment]
**Do not tell me what the problem is. When I select my Google account, instead of going to the next page, this error appears**

![_google1](https://user-images.githubusercontent.com/45923184/52017503-2e5b5800-24f0-11e9-9fa3-048b3bc4b6f3.png)
![_google](https://user-images.githubusercontent.com/45923184/52017505-2e5b5800-24f0-11e9-8233-edd832d3f823.png)

My code:

```
Future<FirebaseUser> _signInGoogle() async {
    GoogleSignInAccount googleSignInAccount = await _gSignIn.signIn();
    GoogleSignInAuthentication authentication = await googleSignInAccount.authentication;

    FirebaseUser user = await _fAuth.signInWithGoogle(
      idToken: authentication.idToken,
      accessToken: authentication.accessToken
    );
    return user;
  }
```

**Comment by nemoryoliver** [comment]
I'm getting a similar error but only on Android and on Release Mode.

`PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null)`

**Comment by zoechi** [comment]
@nemoryoliver https://github.com/flutter/flutter/issues/27599#issuecomment-461482367 might help

**Comment by canewsin** [comment]
You have to use same sha1 of the key that used to sign your app to be in your firebase console otherwise sign will not work

if you dont modify build.gradle file while developing your app 
may be you forgot to add sha1 to firebase console

if you modify it 
maybe you forgot to add sha1 of changed/release key to console

**Comment by YulianD** [comment]
> -alias androiddebugkey -keystore %USERPROFILE%.android\debug.keystore

me funciono, gracias

**Comment by bradmuzza** [comment]
I have the same issue. Works in emulator but not device. I have added my SH1 to my firebase console.

**Comment by Mikkelet** [comment]
Still have the same problem. I feel like I've emptied all options online. I don't get how some guy on youtube can do a 10 min video and get it to work, while I'm stuck retrying the same things again and again. Im going insane.

**Comment by PramUkesh** [comment]
@Mikkelet 
Common Case for the error is :
if you created app first it uses debug key first so while having this case 
you have to upload debug key which you get from your console using below cmd

```
keytool -list -v \
-alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore
```

if you modify android/app/build.gradle file to use your own key you have to use release key, cmd to that is

```
keytool -exportcert -list -v \
-alias <your-key-name> -keystore <path-to-production-keystore>
```

to create a new key store

```
keytool -genkey -v -keystore [Your-Path]/key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key
```

**Comment by PramUkesh** [comment]
more docs are here
https://flutter.dev/docs/deployment/android

**Comment by Mikkelet** [comment]
Appreciate your time, but it still doesn't work, and I am still getting ApiException 16. The link you sent shows me how to generate a release-key, but I am not close to releasing, and just want a debug key. However, the debug key doesn't work either.

**Comment by PramUkesh** [comment]
did you try deleting and create a new key 

> Still have the same problem. I feel like I've emptied all options online. I don't get how some guy on youtube can do a 10 min video and get it to work, while I'm stuck retrying the same things again and again. Im going insane.

What you have tried, is stacktrace is same as above mentioned 
Have you read full thread and tried all solutions mentioned in this thread ?

**Comment by Mikkelet** [comment]
I think so yeah. I have a these files under "C:\Users\User\.android":
debug.keystore
debug.keystore.lock
key.jks
(and more of course)

key.jks is my newest key, that generated using:
`keytool -genkey -v -keystore .\key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias debug`

in my flutter app, I followed firestore's google-services.json guide, where I included my generated SHA1 fingerprint key as well as included the correct classpath and implementation in the gradle files.

From your link https://flutter.dev/docs/deployment/android, I added a `key.properties ` file that looks like this:
`storePassword=android
keyPassword=android
keyAlias=debug
storeFile=C:/Users/User/.android/key.jks`

(I dont mind sharing that "password")

and in my app-gradle file, I included all the code until "Enabling Proguard", as I don't think that's relevant yet, but I might be wrong?

my code looks like this:
`import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'dart:async';

class FBApi {
  static FirebaseAuth _auth = FirebaseAuth.instance;
  static GoogleSignIn _googleSignIn = GoogleSignIn();

  FirebaseUser firebaseUser;

  FBApi(FirebaseUser user) {
    this.firebaseUser = user;
  }

  static Future<FBApi> signInWithGoogle() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;
    final FirebaseUser user = await _auth.signInWithCredential(
        GoogleAuthProvider.getCredential(
            accessToken: googleAuth.accessToken, idToken: googleAuth.idToken));
    final FirebaseUser currentUser = await _auth.currentUser();
    return FBApi(user);
  }
}
`
Taken from [this video](https://www.youtube.com/watch?v=ZNt_e5ojGzQ)

Where it fails on the fails on `await _googleSignIn.signIn();` with error code 16

Futhermore, I have tried on multiple devices, physical and emulator.

More info:
app gradle file:
https://pastebin.com/4UY8C0wz
pubspec.yaml
https://pastebin.com/U3AE7snN

Again, thank you for you time! <3

**Comment by canewsin** [comment]
try with official example from here
https://github.com/flutter/plugins/blob/master/packages/google_sign_in/example/lib/main.dart
if there is an error make github repo with your code and reply so that i can run and test it pastebin is not useful for download and run type repos atleast in my case include all files you can create new project just include sign in part test your self and make sure sha1 is included in firebase console and download google-services.json file and run project

**Comment by Mikkelet** [comment]
Hi, thank you for helping!

I finally found the problem. Apparently, I have 2 .android folders...
C:\Users\User\.android
and
C:\Users\User\AppData\Local\Android\Sdk\.android

and my app was using the former latter location, while I was using the former.

**Comment by idealopamp** [comment]
FYI I ran into the same problem with error code 12500, but for me I also had to configure a support email per https://github.com/flutter/flutter/issues/25909#issuecomment-497378619 .

**Comment by mischkez** [comment]
if someone has also run into this problem and wasn't able to solve it, try updating google services.
check  you debug console where you should find the error like 'google services out of data'...
you can update google services by clicking more ( ... on emulator right panel) and then in you'll see google play icon and then click update... if you don't see that icon create new emulator that supports google services...

**Comment by nixoncode** [comment]
I was able to resolve the Issue I had by enabling the Sign in with Google under Auth option on firebase console

**Comment by xero88** [comment]
Not working for me. I think i will not migrate to flutter because of this bug. I tried everthing. 
-remove my debugkeystore, recreate one
-add support email
-change versions of plugin
-update google on my device

nothing is working, getting this shit error ApiException: 12500

**Comment by xero88** [comment]
if someone have the issue, see my answer https://github.com/flutter/flutter/issues/33393

**Comment by Hassain07** [comment]
> **Do not tell me what the problem is. When I select my Google account, instead of going to the next page, this error appears**
> 
> ![_google1](https://user-images.githubusercontent.com/45923184/52017503-2e5b5800-24f0-11e9-9fa3-048b3bc4b6f3.png)
> ![_google](https://user-images.githubusercontent.com/45923184/52017505-2e5b5800-24f0-11e9-8233-edd832d3f823.png)
> 
> My code:
> 
> ```
> Future<FirebaseUser> _signInGoogle() async {
>     GoogleSignInAccount googleSignInAccount = await _gSignIn.signIn();
>     GoogleSignInAuthentication authentication = await googleSignInAccount.authentication;
> 
>     FirebaseUser user = await _fAuth.signInWithGoogle(
>       idToken: authentication.idToken,
>       accessToken: authentication.accessToken
>     );
>     return user;
>   }
> ```

I have the same error I'd tried the following solutions : added all required and updated dependencies , migrated to Androidx, deleted old key and generated new key , and also updated same in firebase console, I had tried many suggestions from GitHub YouTube and from Google but nothing worked can anyone help me please.

**Comment by xero88** [comment]
@Hassain07 did you try this https://github.com/flutter/flutter/issues/33393#issuecomment-510395178

**Comment by rennay** [comment]
> @Hassain07 did you try this [#33393 (comment)](https://github.com/flutter/flutter/issues/33393#issuecomment-510395178)

Tried the above but setting Application Homepage Link in OAuth Consent Screen did the trick for me.

**Comment by Hassain07** [comment]
Yes may be it will work today itself in dart package site they had updated,
Thanks for your curiosity to help

**Comment by DhruvSingla007** [comment]
Try this, it will surely help :)
https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed

**Comment by luizvaz** [comment]
The KILLER tip is that:

Add two Android apps in Firebase:

- An app for our live product. Use your Application ID.

- An app for our product under development. Add a suffix to your original Application ID, for example “...debug”

https://medium.com/@MiBLT/multiple-build-types-in-firebase-on-android-6f6715f6dd83

[Flutter & Firebase — Configuring debug & release builds](https://medium.com/@rupam.poddar/flutter-firebase-configuring-debug-release-builds-75e60c97d064)

**Comment by elliottben** [comment]
@DhruvSingla007 that link provides fantastic documentation on how to solve this issue. Solved my reproduction of this issue.

**Comment by jhionan** [comment]
I have this same issue, everything was setup correctly. After almost going crazy I found out that the firebase auth policy changed and now we must submit a form <a href="https://console.developers.google.com/apis/credentials/consent?source=post_page---------------------------">here </a>

**Comment by thelazyindian** [comment]
> 
> 
> > @Hassain07 did you try this [#33393 (comment)](https://github.com/flutter/flutter/issues/33393#issuecomment-510395178)
> 
> Tried all the above suggestions but this one - setting Application Homepage Link in OAuth Consent Screen - did the trick for me.

In case you've tried everything and nothing works then this is the way to go.

**Comment by Aashay7** [comment]
I had the same issue. 
1. Go to https://console.developers.google.com/apis/credentials/consent
2. Updating the form. Just adding an Application Logo and Saving did the trick in my case.

Hope it helped.

**Comment by silexcorp** [comment]
Well, sometimes this happens because you have more than 1 SHA1 attached to your project **https://console.firebase.google.com/u/0/project/name** therefore Google Google automatically generate a new _API key and Client ID OAuth 2.0_ for your first SHA1 here **https://console.cloud.google.com/home/dashboard?authuser=0&project=name** First check if the 2 matches or are added to the **google-services.json** file generated by Firebase Console

**Comment by silexcorp** [comment]
I just had to add the SHA256 keys to [https://developers.google.com/android/guides/client-auth](url) and the problem was solved

**Comment by sachinPramodya** [comment]
make sure you have added

```
 dependencies {
    classpath 'com.google.gms:google-services:4.2.0'
}
```
in android/build.gradle and

`apply plugin: 'com.google.gms.google-services'`

in **android/app/build.gradle**. Also, make sure applicationId in **android/app/build.gradle** is the same as your package name in **AndroidManifest.xml**(You may forget to change applicationId after changing package name sometimes). This applicatioonId or package name in manifest file should be the name of your android package name in firebase app.

**Comment by silexcorp** [comment]
> 
> 
> make sure you have added
> 
> ```
>  dependencies {
>     classpath 'com.google.gms:google-services:4.2.0'
> }
> ```
> 
> in **android/build.gradle** and
> 
> `apply plugin: 'com.google.gms.google-services'`
> 
> in **android/app/build.gradle**.
> 
> Also, make sure applicationId in **android/app/build.gradle** is the same as your package name in **AndroidManifest.xml**(You may forget to change applicationId after changing package name sometimes). This applicatioonId or package name in manifest file should be the name of your android package name in firebase app.

Thank you, I have done all the steps, but still not work (when I release on Google Console)
I changed flutter dependencies to **[auth: ^3.2.0](https://pub.dev/packages/auth)** but only work on debug, this is my configuration:

**pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  barcode_scan: ^1.0.0

  #DB
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  firebase_messaging: ^5.1.5 # ^4.0.0+1
  flutter_local_notifications: ^0.8.2+1

  #Auth
  firebase_auth: ^0.14.0 
  google_sign_in: ^4.0.1+1 
  auth: ^3.2.0

  swipedetector: ^1.2.0
  image_picker: ^0.6.1+4  #NSPhotoLibraryUsageDescription NSCameraUsageDescription

  intl: ^0.16.0 #Data format
  image: ^2.1.4
  path_provider: ^1.3.0
  modal_progress_hud: ^0.1.3

  flutter_slidable: ^0.5.3 
  flutter_datetime_picker: ^1.2.6 

  photo_view: ^0.4.2 
  esys_flutter_share: ^1.0.2
```

**android/build.gradle**
```
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        jcenter { url "http://jcenter.bintray.com/" }
    }

    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.20'
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        jcenter { url "http://jcenter.bintray.com/" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }
        }
    }
}
```

**android/app/build.gradle**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.1.0"
            }
        }
    }

    defaultConfig {
        applicationId "com.alexandermateo.domy"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 9
        versionName "1.9.0"
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            
            minifyEnabled false
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-core:16.0.7'
}

apply plugin: 'com.google.gms.google-services'
```

Also, I thought that updating flutter could solve it
**flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.9.7, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Community Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```


**I'm not sure what I'm doing wrong**
```
print('Auth.init');
      auth = Auth.init(
          scopes: [
            'email',
            'https://www.googleapis.com/auth/contacts.readonly',
          ],
          listener: (user) {
            loggedIn = user != null;
            errorMessage = auth.message;
            setState(() {});
          },
          listen: (account) {
            loggedIn = account != null;
            errorMessage = auth.message;
            setState(() {});
          }
      );

      print('auth.signInSilently');
      auth.signInSilently(
        listen: (account) {
          loggedIn = account != null;
          errorMessage = auth.message;
          setState(() {});
        },
      );
```

**Comment by kroikie** [comment]
@mohamed6996

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/534. Any further collaboration will be done there.

**Comment by SeeraRama** [comment]
Did you set your login method in your firebase project?
