### ISSUE TITLE
Firebase cloud messaging notification object required on iOS

### ISSUE THREAD

**Issue by ZatacaSystems** [flutter/flutter#25650]
Hello,

I implemented cloud messaging in my app and everything works right beside the fact that you need to always put the 'notification' object inside the curl request data in order for ios to get the push message. 

I don't think this is working ok because you should decide wich push messages has notification on background and wich dont. In android everything works correctly (the notification object is not required in order to recieve the push message).

Thanks for the help in advance!

**Comment by koami** [comment]
Hi @zanderso. I got stuck with push notification on iOS, the notification from firebase messaging console work fine for both platform but not the automated notification for iOS. I don't get it "'notification' object inside the curl request data". Can you explain it, maybe it's what I'm looking for.

**Comment by ZatacaSystems** [comment]
hey @koami,

On the server side I just send a curl request with this structure:

`$fields = array("to" => "".$token."",

	            "data" => array(

	                "type"=>$eventType, //this is a variable of mine, not important
                    "click_action" => "FLUTTER_NOTIFICATION_CLICK"
	            ),
                "notification" => array(
                    "title" => $title,
                    "body" => $body,
                ),
                "priority" => "high"
                
	        );`

This way it works on both iOS and android. But the problems is that this curl shows a notification on the notification bar when the app is not on foreground. And if you want to use the firebase to just send data and not notify anything, it's a pain in the *ss >.<

**Comment by ZatacaSystems** [comment]
I think that you need to take out the token and put it here:

admin.messaging().sendToDevice(<TOKEN>, <fields>)

**Comment by koami** [comment]
The console give a timeout: Function execution took 60002 ms, finished with status: 'timeout'.

**Comment by koami** [comment]
It worked.  It was one of the iOS application that I had on the same project that was creating an interference. Once I delete the old application in the project it worked just fine.  Thanks again @ZatacaSystems & @zoechi.

**Comment by abogdanovich1994** [comment]
Any updates on this? I'm developing an app that sends a data-only notification as a message to the devices, but the iPhone does not receive it.

**Comment by zoechi** [comment]
@abogdanovich1994 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by hong-duc** [comment]
Hi the fix not work for me, using firebase_messaging: 5.0.2, send fcm without notification object on ios onMessage does not fire, background and foreground. What did I miss ?

**Comment by collinjackson** [comment]
@hong-duc Thanks for your feedback. If the functionality in 5.0.2 isn't working for you, it would be helpful if you could open a new issue referencing this one and mention @collinjackson so I can triage it appropriately. Any sample code or other information on the steps you're following would be helpful.

We don't have full integration testing for this plugin wired up yet; it still requires a manual test unfortunately.

**Comment by kroikie** [comment]
@ZatacaSystems

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/533. Any further collaboration will be done there.
