### ISSUE TITLE
Android support for content:// uri in the File class.

### ISSUE THREAD

**Issue by andyduke** [flutter/flutter#25659]
Flutter does not support content:// uri in Android. I cannot use such a uri in the File class to read the attached file in Gmail (for example, when opening an attached file from an email through a flutter application via deep linking).

You can write a plugin that will read files at such a URI, but this will not be a cross-platform code, since you will have to remember that in Android, content:// uri files must be read through the plugin, and in iOS via File class.

It would be nice to support this type of uri in the File class on Android.

**Comment by zoechi** [comment]
> You can write a plugin that will read files at such a URI, but this will not be a cross-platform code,

That's common that the platform implementation between Android and iOS are different.
Why do you think that would be a problem in this case?

**Comment by andyduke** [comment]
> > You can write a plugin that will read files at such a URI, but this will not be a cross-platform code,
> 
> That's common that the platform implementation between Android and iOS are different.
> Why do you think that would be a problem in this case?

Because you have to check the platform in the dart-code, and read the file differently on different platforms. What is the advantage of Flutter then? After all, this difference can be hidden inside the file management classes.

**Comment by zoechi** [comment]
@andyduke you can provide it the same way from native to Dart from iOS and Android so that you don't know the difference on the Dart side. 
I still don't see the problem.

**Comment by andyduke** [comment]
When a link to a file comes into my dart-code (via a deep link, from the document picker, etc), it is necessary to check if it is a content uri and read it either through the File class or through a plugin. Thus, it is necessary to think about how to read the link to the file in different ways, and only in Android. This kills all the benefits of Flutter as a cross-platform development tool.

**Comment by zoechi** [comment]
There won't be a `content://` uri on iOS, os is this even relevant, or would it?
You still can wrap different approaches behind a common API in Dart so that the user of a plugin doesn't need to know the difference. 
Some special behavior from the underlying platform will always leak through though.

**Comment by agnoam** [comment]
Someone has made this plugin ?

**Comment by KasemJaffer** [comment]
You can use this library to get the absolute path that will work with the dart class File

https://pub.dev/packages/flutter_absolute_path

**Comment by andyduke** [comment]
> 
> 
> You can use this library to get the absolute path that will work with the dart class File
> 
> https://pub.dev/packages/flutter_absolute_path

Good job.

Did I understand correctly that for some cases, the file is [copied](https://github.com/KasemJaffer/flutter_absolute_path/blob/master/android/src/main/kotlin/com/kasem/flutter_absolute_path/FileDirectory.kt#L93) to a directory within the application?
Will a copy of the file be deleted later?

**Comment by KasemJaffer** [comment]
> > You can use this library to get the absolute path that will work with the dart class File
> > https://pub.dev/packages/flutter_absolute_path
> 
> Good job.
> 
> Did I understand correctly that for some cases, the file is [copied](https://github.com/KasemJaffer/flutter_absolute_path/blob/master/android/src/main/kotlin/com/kasem/flutter_absolute_path/FileDirectory.kt#L93) to a directory within the application?
> Will a copy of the file be deleted later?

Yes, that was mainly added to support content URIs that are under the authority of other apps like google photos.

**Comment by agnoam** [comment]
What about Whatsapp URIs ?

**Comment by matheuscaldasrj** [comment]
Any suggestion on how to get WhatsApp file Audio having an URI like 'content://whatsapp.media.....'

I have opened this [issue](https://github.com/KasemJaffer/flutter_absolute_path/issues/2) in `flutter_absolute_path` but I am pretty sure there is another way to do it

**Comment by matthewwong525** [comment]
> A content URI allows you to grant read and write access using temporary access permissions... In comparison, to control access to a file:///[Uri](https://developer.android.com/reference/android/net/Uri.html) you have to modify the file system permissions of the underlying file.
- https://developer.android.com/reference/androidx/core/content/FileProvider

The `content://` uri's are also used to support temporary file permissions in Android. I feel like this should be bumped in priority. Personally, I'm trying to sync files from my flutter app to the local file storage but am unable to do so because of the file restrictions. I can solve this by requesting the `MANAGE_EXTERNAL_STORAGE` permission on android, but, my app isn't qualified for this permission.

**Comment by stuartmorgan** [comment]
Closing, since `File` is part of Dart, not Flutter, so this would need to be filed at `https://github.com/dart-lang/sdk/issues`.

I suspect it would be closed there as well though, since it's not at all clear how many of the APIs in `File` would work. `content` URIs aren't files, they are their own distinct concept; that's why they have a different scheme in the first place.
