### ISSUE TITLE
Allow to specify clear color for the surface view

### ISSUE THREAD

**Issue by nichtverstehen** [flutter/flutter#25667]
We see the screen flashing black when we add FlutterView onto our activity (that's the frame produced after SurfaceView is added but before Flutter had a chance to draw its first frame).

We believe Flutter could clear the surface with a user specified color in time to avoid the black frame ever appearing.

**Comment by mehmetf** [comment]
@nichtverstehen Could you please explain why you cannot use the transparent background option? I believe it has to do with the layering you do with SurfaceViews but it would be good to add that context here.

Also, if you switch to TextureViews, would this still be a problem?
