### ISSUE TITLE
video_player 0.7.2: disposing issue

### ISSUE THREAD

**Issue by I-am-original** [flutter/flutter#25661]
```
A VideoPlayerController was used after being disposed.
I/flutter (15861): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
I/flutter (15861): main: #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:108:9)
I/flutter (15861): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:114:6)
I/flutter (15861): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:202:12)
I/flutter (15861): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:264:5)
I/flutter (15861): #4      VideoPlayerController.pause (package:video_player/video_player.dart:303:5)
I/flutter (15861): <asynchronous suspension>
I/flutter (15861): #5      _VideoAppLifeCycleObserver.didChangeAppLifecycleState (package:video_player/video_player.dart:412:21)
```

Disposing in my code:
```
  @override
  void dispose() async {
    WidgetsBinding.instance.removeObserver(this);
    _controller.dispose();
    super.dispose();
  }
```

So after I have returned from video screen, disposed controller, or even collapsed app and returned to it - I have crash

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

But as mentioned above I think you should first try support channels and create an issue if it actually turns out to be a Flutter or plugin bug.

**Comment by I-am-original** [comment]
Hi @zoechi 
Here is output of flutter doctor
[✓] Flutter (Channel unknown, v1.1.1, on Mac OS X 10.14.2 18C54, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)

There is nothing special. Just creating controller and setting it to videoPlayer and disposing it in dispose

**Comment by zoechi** [comment]
> There is nothing special. Just creating controller and setting it to videoPlayer and disposing it in dispose

I believe it when I see it as  a minimal runnable reproduction
as a single file so that we can just copy your code into lib/main.dart of a new project and run to reproduce.

**Comment by I-am-original** [comment]
@zoechi please close this issue. It is appeared in other plugin. Not actually in this one. Sorry
