### ISSUE TITLE
Google Maps: no option for disabling the controls

### ISSUE THREAD

**Issue by Tblessin** [flutter/flutter#25660]
Hi I'm using your Google Maps plugin https://pub.dartlang.org/packages/google_maps_flutter. I dont want to see the controls view after i tapped on a marker. Is there a way to disable it just like the compass?

` options: GoogleMapOptions(
                compassEnabled: false,
                cameraPosition: const CameraPosition(
                  target: LatLng(-33.852, 151.211),
                  zoom: 11.0,
                ),
              )`

**Comment by von-maurus** [comment]
I need to do the exact same thing, I want to disable navigation options when I tap a marker. Any help?
Thank you in advance

**Comment by secretwpn** [comment]
When the map is taking the whole screen and there is a FAB in the default position, FAB overlays the directions controls.
So either there should be a way to detect if a marker is selected and deselected to hide the FAB (I couldn't find a way to catch the deselection event to achieve this) or a way to control the directions controls visibility. Or maybe even both.

**Comment by von-maurus** [comment]
> When the map is taking the whole screen and there is a FAB in the default position, FAB overlays the directions controls.
> So either there should be a way to detect if a marker is selected and deselected to hide the FAB (I couldn't find a way to catch the deselection event to achieve this) or a way to control the directions controls visibility. Or maybe even both.

Hi, unfortunately the boolean parameter to disabled the nav controls are not available in flutter I think. There is a documentation in Android for this: https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings#setMapToolbarEnabled(boolean)

Also a question in Stackoverflow about this: https://stackoverflow.com/questions/30354258/android-google-maps-marker-disable-navigation-option

The method is "public void setMapToolbarEnabled (boolean enabled)", you need to enter the API's configuration., I could not enter for myself.

**Comment by pepegich** [comment]
waiting for merge https://github.com/flutter/plugins/pull/851

**Comment by spiderion** [comment]
I guess we need to set the consumeTapEvents: true, and then add our custom event.
In this case it won't show the  map controls .

**Comment by otopba** [comment]
Already fixed
https://github.com/flutter/plugins/pull/1808

**Comment by pedromassangocode** [comment]
I can confirm that this was fixed by https://github.com/flutter/plugins/pull/1808.
