### ISSUE TITLE
Couldnt run codelabs project

### ISSUE THREAD

**Issue by DeepStyles** [flutter/flutter#25664]
[flutter_05.log](https://github.com/flutter/flutter/files/2703309/flutter_05.log)

**Comment by zoechi** [comment]
From the log
```
(OS Error: The filename or extension is too long
```

`C:\Users\prade\Documents\material-components-flutter-codelabs-104-starter_and_103-complete\material-components-flutter-codelabs-104-starter_and_103-complete\mdc_100_series\build\app\intermediates\flutter\debug/flutter_assets\packages/shrine_images/2.0x`

Please move the project to a higher folder or rename the long names like `material-components-flutter-codelabs-104-starter_and_103-complete` to shorter names.

**Comment by DeepStyles** [comment]
oh OK worked Thanks!!!
