### ISSUE TITLE
Allow to pre-cache as much Flutter common resources as possible before runApp

### ISSUE THREAD

**Issue by nichtverstehen** [flutter/flutter#25666]
We want to reduce the latency of the Flutter parts of the application appearing on the screen. To achieve this we prewarm FlutterNativeView and start executing initial Dart code (up until deciding with subapp to runApp) and pre-create a FlutterView. The initial runApp still takes 200-300ms.

We need to understand what common resources (fonts, textures, icons, code) could be eagerly prebuilt/precached/precompiled so that runApp in the hot path is fast.

**Comment by koudle** [comment]
I also want to know

**Comment by xster** [comment]
Precaching behaviors should now be documented in https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
