### ISSUE TITLE
[matarial] slider_theme.dart needs more consistent documentation

### ISSUE THREAD

**Issue by clocksmith** [flutter/flutter#25672]
-Should use templates for things like shapes
-Should have a diagram in the docs
-Should have overall consistency

**Comment by Gaurav-Punjabi** [comment]
Hey can i add documentation to slider_theme.dart ?

**Comment by clocksmith** [comment]
I made this issue as a follow up PR to a larger PR chain I am currently in the process of merging, but thanks for the offer!

**Comment by clocksmith** [comment]
Still does not have a diagram but closing this for consistency and templates which are now there.
