### ISSUE TITLE
A Stack widget with children at different elevations renders in painting order for 2D but will not do so for "3D"

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#25673]
The following simple case:

```dart
Stack(
  children: <Widget>[
    Material(elevation: 5.0, color: Colors.red),
    Material(elevation: 1.0, color: Colors.blue),
  ],
);
```

will render a blue color by painting order (which is followed on Android and iOS), but a red color if elevation is respected (which seems to be the direction Fuchsia wants to take).  This will cause confusing cross-platform inconsistencies that will be difficult for developers to test for - and could be particularly bad if a developer had sensitive information that was on the red square and expected it to be covered by the blue square until some other change was made.  We should do something about it.

We should have some way to lint or assert if a stack's children have elevations that could cause what gets painted to be different on a 3d or 2d platform.

Ceratin pathological cases make it challenging:

1. We don't currently have a good way to test the highest elevation of a child - and in fact, we might have a very confusing scenario where part of a child tree is higher than part of another child tree, but part of it is lower:

```dart
Stack(
  children: <Widget>[
    Material(elevation: 1.0, color: Colors.red, child: Stack(/* with more children that have different elevations */),
    Material(elevation: 1.0, color: Colors.blue, child: Stack(/* with  more children that have different elevations */),
  ],
);
```

2. Elevation may be dynamically driven by an animation. A lint for this probably couldn't catch that, and an `assert` that covers this properly might not ever be triggered.

Another possibility is to re-define elevation as being based on _painting_ order.  In that case, the blue square would have an elevation of 1.0 _on top of_ the red square's elevation of 5.0, giving it the potential to cast a shadow of 6.0 on something beneath the stack.  That seems like a more complicated fix, but would probably be more consistent across platforms.

/cc @Hixie @goderbauer @tvolkert @jonahwilliams @zanderso 

See https://github.com/flutter/flutter/pull/25670/files - specifically the changes made to the widgets there for some more context.

**Comment by dnfield** [comment]
One thought for this that isn't fully formed:

In debug mode only, we keep a matrix that contains information about the elevation of that pixel.  We start with all elevations at 0 We update the matrix as we paint, asserting that we're never decrementing from the previous value as we paint. This should be pretty fast, but might need to be done at the skia level.

Another idea discussed offline is to have something in the testing framework that does a DFS of the layer tree comparing it to everyone else afterwards in O(n^2) fashion.  This could catch the issue at test time but would make tests slower, and would miss some cases where interaction/animation invalidates it.

**Comment by Hixie** [comment]
Walk the layer tree to collect all the physical model layers, then for every such physical model layer, check that every later physical model layer either doesn't overlap or has an elevation that is equal or greater.

We could do this in tests only, the same way we do the intrinsic getter checks, if it's too slow to run on every frame of a debug build.

**Comment by eseidelGoogle** [comment]
This has been identified as the solution to a large pain point by customer: dream, marking as such.

**Comment by dnfield** [comment]
@Hixie I'm not sure the layer tree helps here - did you mean the render tree?

When I look at the layer tree for this example I only get a transform layer with a single picture layer:

```dart
 Directionality(
        textDirection: TextDirection.ltr,
        child: Column(
          children: [
            Stack(
              children: <Widget>[
                Container(
                  width: 300,
                  height: 300,
                  child: Material(
                    elevation: 1.0,
                    color: Colors.green,
                  ),
                ),
                Container(
                  width: 300,
                  height: 300,
                  child: Material(
                    elevation: 3.0,
                    color: Colors.blue,
                  ),
                ),
              ],
            ),
            Stack(
              children: <Widget>[
                Container(
                  width: 300,
                  height: 300,
                  child: Material(
                    elevation: 4.0,
                    color: Colors.red,
                  ),
                ),
                Container(
                  width: 300,
                  height: 300,
                  child: Material(
                    elevation: 3.0,
                    color: Colors.brown,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
```

**Comment by dnfield** [comment]
Another way this breaks:

```dart
Material(
  elevation: 24.0,
  child: Material() // with any elevation < 24, at any depth
);
```

I suspect this will be very confusing for developers, particularly when the first material is introduced by an underlying widget they didn't write.

**Comment by jonahwilliams** [comment]
@dnfield this might be relevant?
https://github.com/flutter/flutter/blob/66f424f0f8640234d93ab29e956b9e4491390c28/packages/flutter/lib/src/rendering/proxy_box.dart#L1702

**Comment by dnfield** [comment]
I've shifted to compositing physical layers on all platforms because without that this check doesn't make much sense.  Checking at paint time, for instance, won't work if there's a repaint boundary around a physical shape - so if a Material is scrolling across the screen in a RepaintBoundary, we'd need the layer tree to do the check.
