### ISSUE TITLE
How to hot fix my app

### ISSUE THREAD

**Issue by lucywhite168** [flutter/flutter#25689]
Now I have a app written using flutter,when it has a new version,I want distribute the new version to my customs,What should I do? The only way I have found is ask them delete the old version on their phone and download the new version. I want my customs update to the new version though hot fix,what should I do? Thanks very much.

**Comment by koudle** [comment]
That's not yet supported.

**Comment by lucywhite168** [comment]
So。。。what should i do？delete then download the new？

**Comment by koudle** [comment]
Yes, it is the only way

**Comment by lucywhite168** [comment]
中文测试~

**Comment by lucywhite168** [comment]
Does anybody have other way？

**Comment by zoechi** [comment]
Are Play Store and AppStore not doing that for you automatically if you publish a new version?

**Comment by zoechi** [comment]
Duplicate of #14330

**Comment by ahong222** [comment]
I also want to know

**Comment by zoechi** [comment]
@ahong222 Follow #14330
