### ISSUE TITLE
Corrupt graphics with Flare on Pixel devices in debug mode

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#25687]
## Steps to Reproduce

Certain Flare animations will render corrupt shapes on some Pixel devices, but only in debug mode. Not sure if this is all Pixel devices, but we've seen it on a Pixel 2 and we've had reports of it on a Pixel 3:
https://github.com/2d-inc/Flare-Flutter/issues/22

The issue isn't present in release builds, and it doesn't seem to occur on other non-Pixel devices. 
I've tested on iOS (6, 7 Plus, and X), a Samsung Galaxy Tablet, and a Nokia 6 phone in both debug and release mode.

We've seen both of these examples display the behavior, however the **simple** example shows it most clearly:
https://github.com/2d-inc/Flare-Flutter/tree/master/example/penguin_dance
https://github.com/2d-inc/Flare-Flutter/tree/master/example/simple

There are no errors reported in the terminal and the app is otherwise fully functional.

On a Pixel 2 with the **simple** example:
https://drive.google.com/open?id=1q0RPgCA8YWQ1nT3WDyFDTIwuYgc2h4ND

## Logs
Here's the doctor:
```
[✓] Flutter (Channel master, v1.1.5-pre.16, on Mac OS X 10.14.1 18B3094, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] Connected device (2 available)
```

**Comment by jason-simmons** [comment]
This was introduced when CCPR was enabled: https://github.com/google/skia/commit/a2b5b6467f347962e0d6942da0dff9148fbb3375

@csmartdalton86

**Comment by chinmaygarde** [comment]
CCPR has been disabled.
