### ISSUE TITLE
android studio do not highlight the flutter`s classes.

### ISSUE THREAD

**Issue by winner484** [flutter/flutter#25688]
![Image]
(https://i.stack.imgur.com/Uqz2Q.png)

this is a demo from flutter doc.
but my android studio can not highlight the flutter`s class. what i get is down below.

![Image]
(https://i.stack.imgur.com/iNRTU.png)

How can i do to highlight the flutter`s classes? thank you!

**Comment by zoechi** [comment]
You shouldn't need to do anything. 

Have you tried restarting Android Studio?
Have you tried creating a new project using `flutter create foo` and check if it happens there as well?

Please add the output of `flutter doctor -v`.

**Comment by winner484** [comment]
> You shouldn't need to do anything.
> 
> Have you tried restarting Android Studio?
> Have you tried creating a new project using `flutter create foo` and check if it happens there as well?
> 
> Please add the output of `flutter doctor -v`.

yes, tried restarting AS, tried using IJ, tried creating new project. flutter doctor -v looks good.

**Comment by zoechi** [comment]
> flutter doctor -v looks good.

is the least relevant part of the output

Please add the output of `flutter doctor -v`.

**Comment by AlexeyPoldeo** [comment]
Does not work for me as well

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-BY)
    • Flutter version 1.0.0 at /Users/a/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/a/Library/Android/sdk
    • Android NDK at /Users/a/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

**Comment by zoechi** [comment]
Try deleting `~/.dartServer/.analysis-driver/`

**Comment by AlexeyPoldeo** [comment]
No effect - still no highlighting

<img width="628" alt="screen shot 2019-01-15 at 09 44 27" src="https://user-images.githubusercontent.com/20498870/51163316-4acd8280-18aa-11e9-9aa2-c98458ec15a5.png">

**Comment by AlexeyPoldeo** [comment]
What does it mean? I've just provided more details.

**Comment by zoechi** [comment]
@AlexeyPoldeo no worries, just a bit an overzealous bot. The bot only considers responses of the original issue author.

Have you tried restarting the IDE or perhaps even the machine?

**Comment by AlexeyPoldeo** [comment]
Just restarted my mac - still does not work.

I've installed plugin on Android Studio and IntelliJ IDEA (both are recent version), it does highlight on both places.

**Comment by AlexeyPoldeo** [comment]
I can type and autocompletion works fine, including Flutter classes.
Outline works.

<img width="990" alt="screen shot 2019-01-15 at 10 06 18" src="https://user-images.githubusercontent.com/20498870/51164246-61290d80-18ad-11e9-8553-79c193b86027.png">

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3083](https://github.com/flutter/flutter-intellij/issues/3083) via [**ZenHub**](https://www.zenhub.com/)
