### ISSUE TITLE
Build failed for iOS: Cannot find entry point dart:ui

### ISSUE THREAD

**Issue by su27** [flutter/flutter#2569]
When I try to compile the example app "material_gallery" and run on my iPhone, it fails with `Error: Cannot find entry point dart:ui` error.

### Steps to Reproduce
flutter doctor; cd example/material_gallery; flutter -v start

### Flutter Version
```
flutter --version
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: b6ff67cc2cec4052eff16f011737c9989c9fcbca (3 hours ago)
Engine:    f2d8d75897a5aadcd9be0067a78fce1cea677fd6
```
Device: iPhone 5s with iOS 9.0.2

### Logs
```
          Resolving dependencies...
          Got dependencies!
          ~/dev/flutter/examples/material_gallery/ios/.generated

          PhaseScriptExecution Run\ FLX\ Packager\ +\ Optional\ Script\ Snapshotter build/FlutterApplication.build/Release-iphoneos/FlutterApplication.build/Script-9E07CFF21BEAB2E800BCD8DE.sh
              cd /Users/su27/dev/flutter/examples/material_gallery/ios/.generated
              /bin/sh -c /Users/su27/dev/flutter/examples/material_gallery/ios/.generated/build/FlutterApplication.build/Release-iphoneos/FlutterApplication.build/Script-9E07CFF21BEAB2E800BCD8DE.sh
          Project /Users/su27/dev/flutter/examples/material_gallery successfully packaged...

          PhaseScriptExecution Generate\ Precompiled\ Snapshot build/FlutterApplication.build/Release-iphoneos/FlutterApplication.build/Script-9E07CFCD1BE98FCD00BCD8DE.sh
              cd /Users/su27/dev/flutter/examples/material_gallery/ios/.generated
              /bin/sh -c /Users/su27/dev/flutter/examples/material_gallery/ios/.generated/build/FlutterApplication.build/Release-iphoneos/FlutterApplication.build/Script-9E07CFCD1BE98FCD00BCD8DE.sh
          Error: Cannot find entry point dart:ui :: _getCreateTimerClosureSnapshotter failed for /Users/su27/dev/flutter/examples/material_gallery ...
```
The complete log is here: https://gist.github.com/su27/fa6eb77dcb9b77b9f2cb

**Comment by eseidelGoogle** [comment]
I'm sure @chinmaygarde will know what's up when he wakes.

**Comment by abarth** [comment]
Looks like we forgot to remove this function from the entry_points.txt file.

**Comment by abarth** [comment]
I've fixed this in the engine.  I'll push the fix out to alpha as once it works its way through the buildbots.

**Comment by su27** [comment]
@abarth Now it works great on my phone, thanks! By the way, shouldn't there be some smoke testing on iOS, to avoid simple but severe problems like this?

**Comment by abarth** [comment]
Yes, definitely.  @yjbanov has been working on that.  I think he recently got the first such smoke test to be green on the bots.

**Comment by su27** [comment]
@abarth That's awesome :)

**Comment by yjbanov** [comment]
Yes, while we don't have test coverage for `material_gallery` and other example apps, we now have an end-to-end test that starts from `flutter create` and ends with a successful UI interaction. It should catch many of the core issues, such as a missing `dart:ui`.
