### ISSUE TITLE
UI glitches with CupertinoAlertDialog & CupertinoDialogAction on iOS

### ISSUE THREAD

**Issue by ilyasfoo** [flutter/flutter#25697]
## Steps to Reproduce

<img src="https://user-images.githubusercontent.com/3747241/50376036-000d7180-0642-11e9-8b24-23c996510b33.png" width="400">

1. Artifacts on `CupertinoDialogAction`
1. Ran on device, iPhone 8 with iOS 12.1 (16B92)
1. Code to reproduce:

```dart
void displayDialog() {
  showDialog(
    context: context,
    builder: (BuildContext context) => new CupertinoAlertDialog(
          title: new Text("Not implemented"),
          content: new Text("Just a dummy"),
          actions: [
            CupertinoDialogAction(
              isDefaultAction: true,
              child: new Text("Close"),
              onPressed: () => Navigator.pop(context, true),
            )
          ],
        ),
  );
}
```
4. Tested on physical android, bug did not occur.
5. Tested on physical iPad Mini 2, iOS 12.1, bug did not occur.
6. Tested on iOS simulator iPhone XS iOS 12.1, bug reproduced.
7. I've also noticed once you get the alert to show, and then switch app to background (without closing the alert), and then pop that app back in, the artifact disappears. 
<img src="https://user-images.githubusercontent.com/3747241/50376127-d8b7a400-0643-11e9-8ca3-80fe5f3f5e0c.png" width="100">

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] Connected device
    ! No devices available
```

**Comment by ilyasfoo** [comment]
Might be related to https://github.com/flutter/flutter/issues/20784

**Comment by zoechi** [comment]
Are you still seeing this with latest master?

**Comment by ilyasfoo** [comment]
Dont have access to my mac currently, will re test when I do.

**Comment by ilyasfoo** [comment]
![image](https://user-images.githubusercontent.com/3747241/52685629-6ef1b180-2f85-11e9-8341-0c786b4230fb.png)
@zoechi I confirm no longer happens with the latest master Framework: aa8f86135d, Engine: d48de7a3ec

Thanks!
