### ISSUE TITLE
Wrong incrementing of counter

### ISSUE THREAD

**Issue by Borduni** [flutter/flutter#25699]
I have a quiz app that needs to count++ if a question was solved. It starts with -1 as the first string already begins with zero. I have 50 questions in total on my other page but somehow the _currentIndex has always a higher value than _questions.length.

My Code:
```
class Quiz {
  List<Question> _questions;
  int _currentIndex = -1;
  int _score = 0;

  Quiz(this._questions) {
    _questions.shuffle();
  }

  List<Question> get questions => _questions;
  int get length => _questions.length;
  int get questionNumber => _currentIndex + 1;
  int get score => _score;

  Question get nextQuestion {
    _currentIndex++;
    if (_currentIndex >= length) return null;
    return _questions[_currentIndex];
  }

  void answer(bool isCorrect) {
    if (isCorrect) _score++;
  }
}
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Borduni** [comment]
Isn't this a bug?
