### ISSUE TITLE
How to share Fonts used in flutter with Native Code

### ISSUE THREAD

**Issue by PonnamKarthik** [flutter/flutter#25690]
I have a build a flutter plugin and I want to use the font used in the app to be applied within my plugin 

Is there a way to achieve this

**Comment by jonahwilliams** [comment]
I'm not quite sure what you're asking. Plugins/packages can include assets, and users can then choose to include those assets in their package?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Ham3D** [comment]
op is talking about this plugin
`https://github.com/PonnamKarthik/FlutterToast`
he wants to pass font as a style to fluttre.jar I suppose.
