### ISSUE TITLE
Flutter self signed certificate

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#25692]
Hi, tremulous team, you're just handsome, after flutter development on native platforms seems outdated. Flutter it's wonderful. In this regard, we want to transfer the current application to the flutter. We encountered a problem in the form of `CERTIFICATE_VERIFY_FAILED` when I connected to our servers (web_socket_channel) , I read similar problems, and the solution is to add a certificate to the application, but we have many servers and we can add new ones at any time, with  new certificate. Therefore, the solution `DART_VM_OPTIONS = - root-certs-file = some_file` pub get does not suit us.   
At the moment, as a solution, I see the entry kotlin / swift (channels) and sends answers from the server in the application, but it looks like a crutch. Even if it helps now, it turns out that in the future our application will not be able to work in Fuchsia?
Please tell me how you can solve this problem in other ways?
P.S.sorry for my bad english

**Comment by zoechi** [comment]
Is tis about the development environment, the mobile app, or both?

**Comment by 1AlexFix1** [comment]
> Is tis about the development environment, the mobile app, or both?

At the moment, only the development environment for mobile devices, but as soon as a stable version appears under the PC, then a PC will need some kind of solution.

**Comment by zoechi** [comment]
> but as soon as a stable version appears under the PC

You mean a desktop version when Fuchsia is released. So it's only about the application you are developing, not the development environment (`flutter upgrade`, `flutter packages get`, ...)

**Comment by 1AlexFix1** [comment]
> > but as soon as a stable version appears under the PC
> 
> You mean a desktop version when Fuchsia is released. So it's only about the application you are developing, not the development environment (`flutter upgrade`, `flutter packages get`, ...)

Probably we did not understand each other, i mean i do that on mobile
`
IOWebSocketChannel ws = IOWebSocketChannel.connect('wss://myserver.com');
    ws.stream.listen((data) {
      print('data = $data');
    });
`
and get an error
`
ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter (24337): WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
E/flutter (24337): 	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:363))
`
The solution that is offered here #24586 does not help, since we have a lot of servers, and each has its own self-signed certificate.

**Comment by 1AlexFix1** [comment]
Oh, sorry it's my fail!!! Very very sorry

**Comment by zoechi** [comment]
That's because that's for the development tools, not for the created app.

I guess this is a duplicate of https://github.com/dart-lang/sdk/issues/34284

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/dart-io/RawSecureSocket-class.html 
https://docs.flutter.io/flutter/dart-io/SecurityContext/setTrustedCertificates.html might help

**Comment by g-balas** [comment]
How did you fix that CERTIFICATE_VERIFY_FAILED with IOWebSocketChannel @1AlexFix1  ?

**Comment by 1AlexFix1** [comment]
> Как вы исправили это CERTIFICATE_VERIFY_FAILED с IOWebSocketChannel @ 1AlexFix1 ?

As a result, it was my mistake, I didn’t correctly indicate the address of the server, we had a complex redirection so it seemed that the problem was on the client, but in fact it’s most likely on the server, I don’t know about IO, I use WebSocket since it’s connected returns the future, using this you can determine the status of onConnected (conditionally)

**Comment by winter91** [comment]
> How did you fix that CERTIFICATE_VERIFY_FAILED with IOWebSocketChannel @1AlexFix1 ?
I want to know yet
