### ISSUE TITLE
Example using Google's Authentication/Login APIs

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#257]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Tuesday Nov 03, 2015 at 23:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1936_

----

For tracking.

**Comment by vlidholt** [comment]
Yes, this is required to connect with Google Play Game Services

**Comment by eseidelGoogle** [comment]
@collinjackson wanted this.

**Comment by sethladd** [comment]
The firebase example will have this. https://github.com/flutter/firechat-flutter

**Comment by kroikie** [comment]
@FlutterIssues

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1033. Any further collaboration will be done there.
