### ISSUE TITLE
flutter: The method 'validate' was called on null

### ISSUE THREAD

**Issue by Jaghadish** [flutter/flutter#25705]
Hi I am entirely new to flutter and I am in process of learning based on some youtube videos - I replicated the steps mentioned and I could see the above mentioned error (Please note that the previous fix suggested at did not work so raising this one)

My code is as follows:

import 'package:flutter/material.dart';

class MyLoginPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _LoginPageState();
}

class _LoginPageState extends State<MyLoginPage> {
  final formKey = new GlobalKey<FormState>();

  String email;
  String password;

  void validateAndSave() {
    final form = formKey.currentState;
    if (form.validate()) {
      print('form is valid');
    } else {
      print('form invalid');
    }
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text('Flutter Login Demo'),
        ),
        body: new Container(
            padding: EdgeInsets.all(16.0),
            child: new Form(
              child: new Column(
                children: <Widget>[
                  new TextFormField(
                    decoration: new InputDecoration(labelText: 'Email'),
                    validator: (value) =>
                        value.isEmpty? 'Email cannot be empty' : null,
                  ),
                  new TextFormField(
                    decoration: new InputDecoration(labelText: 'Password'),
                    obscureText: true,
                    validator: (value) =>
                        value.isEmpty? ' Password cannot be empty' : null,
                  ),
                  new RaisedButton(
                      child:
                          new Text('Login', style: new TextStyle(fontSize: 20)),
                      onPressed: validateAndSave)
                ],
              ),
            )));
  }
}

Please can someone help?

**Comment by Jaghadish** [comment]
Please note I have issues in updating I used:

formKey = new GlobalKey<FormState>() only and the same is not updated in markdown preview here somehow

**Comment by Jaghadish** [comment]
<FormState> is used in above code but is not shown

**Comment by Jaghadish** [comment]
missed initiating formKey - the issue can be closed now

**Comment by hurter8** [comment]
> missed initiating formKey - the issue can be closed now

Care to share how you initiated the formKey?

**Comment by 216071518** [comment]
import 'package:flutter/material.dart';

class MyLoginPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _LoginPageState();
}

class _LoginPageState extends State<MyLoginPage> {
  final formKey = new GlobalKey<FormState>();

  String email;
  String password;

  void validateAndSave() {
    final form = formKey.currentState;
    if (form.validate()) {
      print('form is valid');
    } else {
      print('form invalid');
    }
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text('Flutter Login Demo'),
        ),
        body: new Container(
            padding: EdgeInsets.all(16.0),
            child: new Form(
              key: _formKey,  // that should work just fine
              child: new Column(
                children: <Widget>[
                  new TextFormField(
                    decoration: new InputDecoration(labelText: 'Email'),
                    validator: (value) =>
                        value.isEmpty? 'Email cannot be empty' : null,
                  ),
                  new TextFormField(
                    decoration: new InputDecoration(labelText: 'Password'),
                    obscureText: true,
                    validator: (value) =>
                        value.isEmpty? ' Password cannot be empty' : null,
                  ),
                  new RaisedButton(
                      child:
                          new Text('Login', style: new TextStyle(fontSize: 20)),
                      onPressed: validateAndSave)
                ],
              ),
            )));
  }
}
