### ISSUE TITLE
Pop up dark keyboard on iOS

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#25709]
How popup dark keyboard on iOS specific platform? Is there any api on this?

**Comment by zoechi** [comment]
Follow-up to #18540

**Comment by zoechi** [comment]
Duplicate of #25658

**Comment by dark-chocolate** [comment]
@jinfagang Please don't ask questions on Github. Stackoverflow is better platform to ask. If some thing is not working as intended and you think it is a bug, or if you have any suggestion regarding this, you are most welcome on Github. Thanks
