### ISSUE TITLE
v1.1.4 broke proguard

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#25703]
I setup proguard using the flutter documentation. Upgraded to 1.1.4 and now it's broken. I have no idea how to use proguard and I have no idea how to troubleshoot it. I will be removing it from my project. Just wanted to post this here so someone knew that this happened.

Cheers

```
Warning: there were 2 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.13.6 17G4015, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.30.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by pamir72** [comment]
Same issue

**Comment by Galahand** [comment]
Same issue as well

**Comment by zoechi** [comment]
@pamir72 @Galahand Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by jason-simmons** [comment]
The Flutter libraries now reference some APIs that were added in Android P.

If you're seeing this error in Proguard, try changing the project's `android/app/build.gradle` to use `compileSdkVersion 28`
