### ISSUE TITLE
Flutter Development in android studio is extremely painful.

### ISSUE THREAD

**Issue by james-lawrence** [flutter/flutter#25711]
I've been developing a flutter app in android studio for about 4 months now. and more of my time is spent debugging why android studio is crashing/breaking than actually developing my application.

flutter needs a more stable environment.

things I've run into:
- android studio can't seem to remember that the project is a flutter app, requiring every startup to resync gradle files and re-enable dart support.
- flutter fails to properly build a release APK (see issues already filed around missing libflutter.so from APK)
- android studio marking files as read only, even when I created them inside android-studio (wtf?) I have yet to figure out how to fix this.
- android studio can't seem to handle the java aspects of the project simultaneously with the dart without opening a new window specifically for the java portion.

**Comment by zoechi** [comment]
Please create a new issues for every concrete problem.
If you create an issue, please provide as much information as possible that allows to reproduce that concrete problem.
IntelliJ/Android Studio integration is maintained in https://github.com/flutter/flutter-intellij. Please create related issues there.
Issues need to be about concrete problems. General rants are not actionable.

**Comment by james-lawrence** [comment]
its hard to give concrete details when there are so many continuous problems =) but I'll start over in the intellij repo.

**Comment by zoechi** [comment]
I fully understand that such issues are hard to reproduce and report accordingly
and we really appreciate your effort. 

> flutter fails to properly build a release APK (see issues already filed around missing libflutter.so from APK)

I'm pretty sure this is unrelated to AS/IntelliJ and will have the same behavior on command line as from within AS/IntelliJ.
