### ISSUE TITLE
MissingPluginException(No implementation found for method polyline#add on channel 

### ISSUE THREAD

**Issue by delphiy** [flutter/flutter#25720]
MissingPluginException(No implementation found for method polyline#add on channel plugins.flutter.io/google_maps_0)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the full error output and the steps how to reproduce.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by delphiy** [comment]
The result of flutter doctor -v as follows:

 
Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 1.0.0 at /Users/delphix/Documents/Sdk/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

⣷Unhandled exception:
Exception: adb not responding
#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:99:9)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:130:21)
<asynchronous suspension>
#3      Device.descriptions (package:flutter_tools/src/device.dart:309:58)
<asynchronous suspension>
#4      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:697:31)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#10     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#11     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._complete (dart:async/future_impl.dart:476:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Husams-MacBook-Air:flutter_app delphix$

**Comment by zoechi** [comment]
continued at #25804
