### ISSUE TITLE
url_launcher / iOS: closeWebView doesn't work on WebkitVC

### ISSUE THREAD

**Issue by MagicalTux** [flutter/flutter#25721]
## Steps to Reproduce

1. Open a url with launch()
2. attempt to close with closeWebView()
3. nothing happens

## Problem

In [UrlLauncherPlugin.m around line 133](https://github.com/flutter/plugins/blob/master/packages/url_launcher/ios/Classes/UrlLauncherPlugin.m#L133), a completion handler is set that resets _currentSession to nil, however completion of [presentViewController](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621380-presentviewcontroller) is called as completion of showing the viewcontroller, and not at the end of the web browsing.

As such, _currentSession is reset to nil almost immediately, and closeWebView() will do nothing.

I am guessing [safariViewControllerDidFinish](https://developer.apple.com/documentation/safariservices/sfsafariviewcontrollerdelegate/1621214-safariviewcontrollerdidfinish) in the delegate should instead be used.

**Comment by pd4d10** [comment]
For those who want to get this fixed before related PR merged, temporary walkthrough here:

```sh
cd /path/to/your/project # change this to your project path
mkdir vendor
git clone -b issue-25721-fix https://github.com/MagicalTux/plugins /tmp/flutter-plugins
cp -r /tmp/flutter-plugins/packages/url_launcher vendor
```

Script above will copy `url_launcher` plugin of @MagicalTux 's branch to vendor dir.

Then edit `pubspec.yaml` like this:
```yml
dependencies:
  ...
  url_launcher:
    path: vendor/url_launcher
  ...
```

It works for me in [my project](https://github.com/pd4d10/git-touch).

Thanks for your awesome work! @MagicalTux @timtraversy

**Comment by cyanglaz** [comment]
Seems fixed with https://github.com/flutter/plugins/pull/997. Closing the issue now. If any related issues have been found even with the patch, please feel free to reopen the issue with details.

**Comment by yohom** [comment]
When will a new version of `url_launcher` released with this bug fix? @cyanglaz

**Comment by cyanglaz** [comment]
@yohom This is already fixed with version 5.0.2, the fix was provided by flutter/plugins#997.

**Comment by AlexandreRoba** [comment]
@cyanglaz 5.0.2 is not available yet? I can't seem to find it.

**Comment by cyanglaz** [comment]
@yohom @AlexandreRoba Sorry I failed to publish the fix. It is published now and you should be able to update to 5.0.2

**Comment by AlexandreRoba** [comment]
Thanks @cyanglaz
