### ISSUE TITLE
how to draw over other apps in Flutter?

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [flutter/flutter#25732]
how to draw over other apps in Flutter?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by MichaelPriebe** [comment]
Would love to know if this is possible!

**Comment by MichaelPriebe** [comment]
How about this? This would be so cool!

**Comment by jckpn** [comment]
It is possible. See here: https://github.com/flutter/flutter/issues/28844#issuecomment-478939888

**Comment by leisim** [comment]
> It is possible.

But only with workaround. You cannot use `MaterialApp` which causes problems with navigation, material widgets etc.

**Comment by phanirithvij** [comment]
The solution described here https://github.com/flutter/flutter/issues/28844#issuecomment-478939888 is the way to go.
And flutter.dev suggests [this](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen?tab=transparent-activity-launch-kotlin-tab#add-a-translucent-flutter-screen) now under add-to-app section

**Comment by iso57** [comment]
It is a good idea like as Youtube Premium Video on background ;)

**Comment by jmagman** [comment]
The original request isn't very specific, and I'm not sure if the originator was requesting information about [SYSTEM_ALERT_WINDOW](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW), [translucent Flutter screen](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen?tab=transparent-activity-launch-kotlin-tab#add-a-translucent-flutter-screen), [iOS picture-in-picture](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player), etc.  There seems to be differences between what commenters think this is tracking as well.

If you have a specific feature or documentation request, please file a new issue and completely fill out the template.  Give us an example of what you would use it for, if it mimics existing features on a platform, and any other information we can use to make this actionable.  Thanks!

**Comment by djkskqyr3** [comment]
How to implement this feature using flutter?

https://www.youtube.com/watch?v=hBPd2q2dmXY&amp;feature=youtu.be

**Comment by jmagman** [comment]
@djkskqyr3 
> If you have a specific feature or documentation request, please file a new issue and completely fill out the template. Give us an example of what you would use it for, if it mimics existing features on a platform, and any other information we can use to make this actionable. Thanks!

**Comment by digvijayJUIT** [comment]
how to recoard youch in flutter anyone help me ?
