### ISSUE TITLE
Gallery demo needs a search feature

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#2573]
The list of component demos is long and will get longer.  A search button would be a worthy addition as a demo, and it's becoming a practical necessity as well.

**Comment by eseidelGoogle** [comment]
If we had this we could probably remove the stocks example.  Search is one of the few things which is still stocks-only (the other being a Settings page example).

**Comment by Hixie** [comment]
Closing. We don't need to track this as a bug. If we do it we do it.
