### ISSUE TITLE
flutter AndroidManifest warning - current min is 1

### ISSUE THREAD

**Issue by chaitanyabhardwaj** [flutter/flutter#25734]
_AndroidManifest.xml_ file gives warnings - 

`Attribute hardwareAccelerated is only used in API level 11 and higher(current min is 1)`
`Attribute windowSoftInputMode is only used in API level 3 and higher(current min is 1)`
And
`Should set android:versionCode to specify the application version`
`Should set android:versionName to specify the application version`
Also
`App is not indexable by Google Search;`

While the _app/build.gradle_ file reads - 

    compileSdkVersion 28
    minSdkVersion 16
    targetSdkVersion 28
    versionCode flutterVersionCode.toInteger() // 1
    versionName flutterVersionName // '1.0'

The warnings started occurring recently without any new upgrades. My older flutter projects never encountered these warnings and are still working fine.

**Things I've tried:**
1. File > Invalidate Caches / Restart.... > Invalidate And Restart
2. Just Restart
3. Create a different project from start

**What resolves the warnings:**

    <uses-sdk android:minSdkVersion="16"
     android:targetSdkVersion="28" />

Using the `<uses-sdk.../>` in _AndroidManifest.xml_ resolves the warning(current min is 1) but hence invalidating the use of `app/build.gradle` file.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please also try with `dev` channel `flutter channel dev`

**Comment by chaitanyabhardwaj** [comment]
**Output of flutter doctor -v**  `beta channel`

[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.0.0 at /Users/chaitanyabhardwaj/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chaitanyabhardwaj/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Moto G 4 • ZY223GVHZC • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.


**Output of flutter doctor -v**  `dev channel`

[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.1.4 at /Users/chaitanyabhardwaj/flutter
    • Framework revision 7a88fbc5fd (7 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chaitanyabhardwaj/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Moto G 4 • ZY223GVHZC • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by sayhell** [comment]
any update? I think edit `build.gradle` not work anymore?

**Comment by blasten** [comment]
Is this still an issue? I haven't heard this before. Please share the concrete steps to reproduce this issue.

**Comment by awaissaeed530** [comment]
I am running into same problem with flutter 1.12.13+hotfix.5.
`flutter doctor -v`

>  Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\awais\binaries\flutter
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\awais\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\awais\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.41.1)
    • VS Code at C:\Users\awais\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 2 categories.

**Comment by jonahwilliams** [comment]
We never received steps on how to reproduce the issue, so we were unable to determine if it was an app specific problem or a problem with flutter.

**Comment by awaissaeed530** [comment]
You just need to create an app and then go to Android manifest or app level build.gradle. There even if you change minSdkVersion it always says your current min sdk is 1.

**Comment by asidt** [comment]
Should be easy to reproduce, and it's still an issue, so maybe worth to reopen it:

![Screenshot 2020-06-23 at 13 02 11](https://user-images.githubusercontent.com/59609152/85390660-c9275d00-b551-11ea-9b1f-f9e6e1084a0c.png)
![Screenshot 2020-06-23 at 13 00 11](https://user-images.githubusercontent.com/59609152/85390664-c9bff380-b551-11ea-9ba5-81f13830afa1.png)
