### ISSUE TITLE
What is the reason for this data copy?

### ISSUE THREAD

**Issue by SupSaiYaJin** [flutter/flutter#25745]
platform_message_response_dart.cc
```
Dart_Handle WrapByteData(std::unique_ptr<fml::Mapping> mapping) {
  std::vector<uint8_t> data(mapping->GetSize());
  memcpy(data.data(), mapping->GetMapping(), mapping->GetSize());
  return WrapByteData(std::move(data));
}
```

Is that redundant?

**Comment by zoechi** [comment]
https://github.com/flutter/engine/blob/master/lib/ui/window/platform_message_response_dart.cc#L42

**Comment by TahaTesser** [comment]
Hi @SupSaiYaJin 
This doesn't seem to exist on the latest master channel of the engine repository 
https://github.com/flutter/engine/blob/master/lib/ui/window/platform_message_response_dart.cc
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
