### ISSUE TITLE
Passing null bytes to instantiateImageCodec crashes engine

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#25747]
I haven't verified that this is the actual cause, but I just got an engine crash in a test with the following final words:

```
Shell: ../../third_party/skia/src/core/SkData.cpp:104: fatal error: "assert(src)"
Shell subprocess crashed with unexpected exit code -5 after tests finished.
```

...and I suspect the cause is that I was passing null bytes to instantiateImageCodec.

We should make that throw an exception rather than crash.

**Comment by csells** [comment]
@Hixie can you post a repro project?
