### ISSUE TITLE
Some mistake within Wiki

### ISSUE THREAD

**Issue by WilliamZang** [flutter/flutter#25742]
See [here](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#write-code-to-use-flutterviewcontroller-from-your-host-app).
We try to add a flutter module into our existed app. PluginRegistrant won't work correctly because AppDelegate's root view controller isn't a flutterViewController. 
I saw [this part of wiki](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#write-code-to-use-flutterviewcontroller-from-your-host-app). But the wiki doesn't explained it clear.

**Comment by kangwang1988** [comment]
@WilliamZang 
Please create a github demo project which might help us to reproduce your issue and improve the wiki.

**Comment by kangwang1988** [comment]
Close #25742 as duple of: https://github.com/flutter/flutter/issues/25655
