### ISSUE TITLE
Get latlng bounds for google maps Plugin:google_maps_flutter

### ISSUE THREAD

**Issue by gurleensethi** [flutter/flutter#25755]
Add support in google_maps_flutter plugin to get the latlng bounds of the visible map area.
As in native : https://stackoverflow.com/questions/14700498/android-google-maps-get-boundary-co-ordinates

**Comment by daanvandenhoek** [comment]
@gurleensethi I dont know if this helps but I wanted the same thing and found your issue. I still needed the cords so I did some calculations and made this:

```
Size _widgetSize = globalKey.currentContext.size;
          LatLng _cameraPosition = this.controller.cameraPosition.target;
          double _mapZoom = this.controller.cameraPosition.zoom;

          var _correctZoom = math.pow(2, _mapZoom) * 2;
          var _width = _widgetSize.width.toInt() / _correctZoom;
          var _height = _widgetSize.height.toInt() / _correctZoom;

          double latFrom = _cameraPosition.latitude - _width;
          double latTo = _cameraPosition.latitude + _width;
          double longFrom = _cameraPosition.longitude + _height;
          double longTo = _cameraPosition.longitude - _height;
```
globalkey is the key of the map. I tested it and it works. let me know if this helped you

**Comment by gurleensethi** [comment]
@daanvandenhoek I am unable to add a key to `GoogleMap`. Could you provide a more complete code sample that includes the `GoogleMap` widget as well.

**Comment by daanvandenhoek** [comment]
```
Container(
        key: globalKey,
        child: GoogleMap(
          options: GoogleMapOptions(
              trackCameraPosition: true,
              compassEnabled: widget.compassEnabled,
              myLocationEnabled: true,
              ),
          onMapCreated: _onGoogleMapCreated,
          gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
            new Factory<OneSequenceGestureRecognizer>(
              () => new EagerGestureRecognizer(),
            ),
          ].toSet(),
        ))
```

**Comment by MrNicodemuz** [comment]
This would be an essential feature for most apps that want to load markers on the current viewpoint of the map screen.

The solution by @daanvandenhoek is a workaround, but the coordinates are not very accurate.

Are there any other solutions available at this point in time?

**Comment by gurleensethi** [comment]
The workaround in not scalable on different size devices, we need native implementation.

**Comment by erf** [comment]
We need access to a projection object as described [here](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_projection). So we can call `coordinateForPoint` on the `visibleRegion` to get the bounds.

**Comment by babenkovladimir-203** [comment]
I just recently dealt with version 0.3.0 + 2. Now the current version is 0.4.0. I see some changes.
Just can not figure out how to get access to the bounds

**Comment by babenkovladimir** [comment]
also ran into this problem. I need to implement a zoom callback and I need to get access to the bundles.

**Comment by myermukhanov** [comment]
In new version, there is no trackCameraPosition: true.
Instead you can define 
onCameraMove: (CameraPosition position) {
  _cameraPosition = position.target;
  _mapZoom = position.zoom;
}

**Comment by XinyueZ** [comment]
<img width="554" alt="Screenshot 2019-06-05 at 13 57 14" src="https://user-images.githubusercontent.com/7869833/58954587-e5672900-8799-11e9-83bd-abbcc57d03c3.png">

**Comment by danielrf121** [comment]
@myermukhanov Unfortunately this method only delivers LAT LONG. We really need the coordinates of the 4 corners of the map.

<img width="513" alt="Captura de Tela 2019-12-18 às 11 21 01" src="https://user-images.githubusercontent.com/15792968/71093896-cefa4b00-2188-11ea-8992-58999c9a9eea.png">

**Comment by danielrf121** [comment]
Searching here for available methods, I ended up finding this one, which can solve the problem:

onCameraMove: (CameraPosition position) {
   **_updateMap();**
}

void _updateMap() async {
    **LatLngBounds bounds = await this.mapController.getVisibleRegion();**
    print('#################################');
    print(bounds.northeast.toString());
    print(bounds.southwest.toString());
    print('#################################');
}

**Comment by tristanjules** [comment]
This solution will calculate the vertical and horizontal bounds, it's configured to work where the Map takes up the full size of the display, if the Map does not take up the whole display- then _screenSize will just need to be altered to represent the size of the widget that the Map is contained in.

    Size _screenSize = MediaQuery.of(context).size; //width and height of the device in pixels

    GoogleMapController controller = await _controller.future;
    ScreenCoordinate _screenCoordinate = await controller.getScreenCoordinate(_currentPosition); //returns the center of the map in screen pixels

    LatLng leftBound = await controller.getLatLng(new ScreenCoordinate(x: 0, y: _screenCoordinate.y)); //LatLng coordinates from screen pixel coordinates
    LatLng rightBound = await controller.getLatLng(new ScreenCoordinate(x: _screenSize.width.round(), y: _screenCoordinate.y)); //LatLng coordinates from screen pixel coordinates

    LatLng topBound = await controller.getLatLng(new ScreenCoordinate(x: _screenCoordinate.x, y: _screenSize.height.round())); //LatLng coordinates from screen pixel coordinates
    LatLng bottomBound = await controller.getLatLng(new ScreenCoordinate(x: _screenCoordinate.x, y: 0)); //LatLng coordinates from screen pixel coordinates

**Comment by giorgio79** [comment]
Even better https://github.com/flutter/flutter/issues/36653
