### ISSUE TITLE
New Keyword is optional now.

### ISSUE THREAD

**Issue by DhruvamSharma** [flutter/flutter#25750]
The Flutter Codelab 1 says: 

> If you didn't change Center to "new Center", the type system will warn that the Center object should not be typed as a constant (const), because its child Text object is no longer a constant. Therefore, both Center and Text must create instances using new.

As mentioned here: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

As of Dartlang 2.0, `new` keyword is optional. 

Please fix.

**Comment by zoechi** [comment]
Duplicate of flutter/website#1936
