### ISSUE TITLE
"API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device."

### ISSUE THREAD

**Issue by naclcaleb** [flutter/flutter#25768]
I tried to set up the firebase_auth plugin, but I get this error: 
```
API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
```
I included it in the pubspecs.yaml like so:
`firebase_auth: ^0.6.6`

I followed Google's instructions to set it up on the Firebase docs.

I am testing this app on a Kindle Fire HD.

Any help would be much appreciated!

**Comment by zoechi** [comment]
Perhaps https://stackoverflow.com/questions/41384895/firebase-10-0-internalfirebaseauth-firebase-auth-api-is-not-available-on-this

**Comment by naclcaleb** [comment]
Kindle Fire doesn't have the "Google Play Services" option in settings. Perhaps that's why it isn't working?

**Comment by zoechi** [comment]
`firebase_core` will be added as transitive dependency automatically.

**Comment by naclcaleb** [comment]
Oh, I see. So it seems that has nothing to do with it...

I wish I could try with a different Android device, but this is all I have.

The emulator doesn't run on my computer, so I can't try a different device there either.

**Comment by zoechi** [comment]
I don't know details here. We'd have to wait for Firebase specialists.
Please check for alternatives like what I found on a [quick search](https://www.google.at/search?q=kindle+firebase&oq=kindle+firebase&aqs=chrome..69i57j0l2.3800j0j7&sourceid=chrome&ie=UTF-8) https://blog.novoda.com/firebase-on-amazon-devices/
Such approaches might as well work with Flutter.

**Comment by naclcaleb** [comment]
Ah, I see. Ok, that makes a lot of sense.

Thanks for the help! I guess it just has to do with the device, like the error message indicated.

I'll try to get my hands on another Android device with Google Play Services. I wasn't planning on releasing to the Kindle App Store anyway, so that should be fine.

**Comment by cyanglaz** [comment]
@naclcaleb Seems this is something that we cannot fix at the moment. Are you ok if we close the issue?

**Comment by naclcaleb** [comment]
Sure, go ahead.

**Comment by kroikie** [comment]
@naclcaleb

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/528. Any further collaboration will be done there.
