### ISSUE TITLE
iPad split keyboard cause a blank space problem

### ISSUE THREAD

**Issue by TomassMaximum** [flutter/flutter#25766]
![img_0366](https://user-images.githubusercontent.com/14291993/50431068-fb2b1500-0902-11e9-943a-d8b11975de0f.PNG)
![img_0367](https://user-images.githubusercontent.com/14291993/50431073-ffefc900-0902-11e9-900e-563bb0048b6b.PNG)
![img_0368](https://user-images.githubusercontent.com/14291993/50431074-02eab980-0903-11e9-8e25-a4f47604643f.PNG)
1. Tap a Text Field in a flutter app, wait for the keyboard to pop up
2. Split the keyboard by swiping to both left and right sides
3. Release focus on the Text Field by tapping other elements
4. A Blank space appear at the bottom of the screen, it will stay there during the rest lifespan of the app no matter what you do

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by TomassMaximum** [comment]
> Please add the output of `flutter doctor -v`.

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G2208, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/chuangkegongchang/flutter/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chuangkegongchang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

• No issues found!

**Comment by chao2318** [comment]
I‘m boring to rebuild a engine frameword and include it in my project，so I use runtime hook to fix this issue。
[FixiPadSplitKeyboard.txt](https://github.com/flutter/flutter/files/3355084/FixiPadSplitKeyboard.txt)

**Comment by Frozmen** [comment]
puzzled the day why on the iPad half of the screen takes up empty space. Outside 2019 is coming to an end but the problem still remains

**Comment by eseidelGoogle** [comment]
This looks like an Engine bug not noticing when a split keyboard goes away and updating the safe area.
https://stackoverflow.com/questions/7842806/check-for-split-keyboard/8785494
has some interesting context on understanding where the split keyboard is.

This is likely the code in question:
https://github.com/flutter/engine/blob/23df3e6bcbcbbd4b475249f94978e66c6be127f5/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L812

It looks reasonable.  But maybe there is just a bug here somewhere.  Someone interested in solving this should build their own location version of the Engine and then debug what viewport metrics are being passed around in the engine in response to splitting the keyboard:
https://github.com/flutter/flutter/wiki/Compiling-the-engine

**Comment by pedromassangocode** [comment]
Hi @TomassMaximum 
Can you confirm that this still a valid issue?

**Comment by TahaTesser** [comment]
Just tried on the latest `master` channel, there is no space problem when using a split keyboard after releasing focus form a textfiekd 

![ezgif com-resize](https://user-images.githubusercontent.com/48603081/93328398-47d22480-f839-11ea-9288-ed00935a2876.gif)



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.176, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.176 at /Users/tahatesser/Code/flutter_master
    • Framework revision 96ca0e272b (27 hours ago), 2020-09-15 09:02:04 +0100
    • Engine revision 7e962ba911
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.7
    • iPad Air 2 (mobile)    • 9F661E6D-043C-49CE-94D1-B3E788EB8ACF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details> 


If you're still experiencing this issue, please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
Thank you
