### ISSUE TITLE
Since 1.0 or earlier, the performance of scroll view has not been very good.

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#25769]
## Steps to Reproduce

Since 1.0 or earlier, the performance of scrolling views has not been very good.
I see a issue #25372, But I'm not sure if it's the same cause?
I tried to build a simple demo to reproduce this problem.
I used release and profile modes to build apks,  the scrolling fps are very low, sometimes even below 20.

I record my screen . 
https://drive.google.com/file/d/1hZQT1hYruowcTQPYqcCIvLmyHdcg8pUM/view?usp=sharing

## Code

```dart

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemBuilder: _buildItem,
        itemCount: 5353,
      ),
    );
  }

  Widget _buildItem(BuildContext context, int index) {
    return Row(
      children: <Widget>[
        Image.network(
          "http://identicon.net/img/identicon.png",
          width: 40.0,
          height: 40.0,
        ),
        Text("index = $index"),
      ],
    );
  }
}
```

The ListView item is only a image and text.
In the process of project development, item will be more complex than this, and FPS will be lower.
When a real project of mine is in normal use, it could not reach an average of more than 35.

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.1.4, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.1.4 at /Users/cai/fluttersdk/flutter
    • Framework revision 7a88fbc5fd (6 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

...
[✓] Connected device (1 available)
    • MI 8 • b6ec3684 • android-arm64 • Android 9 (API 28)
```
My devices's cpu is Qualcomm 845. So it shouldn't be the hardware reason for the device.

**Comment by CaiJingLong** [comment]
This simple view, in version 0.9.0, is very smooth.
But I use mixin grammar a lot in my project and when I update to 1.0.0, it's hard to go back to 0.9.0 sdk.
Can you find out why the number of frames is different in 0.9.0 and 1.0.0 versions?

**Comment by zmtzawqlp** [comment]
you are not alone, guy

**Comment by zoechi** [comment]
Might be related to #12656, #22314, #20857

**Comment by quantosapplications** [comment]
HI, any update on this?

**Comment by VladyslavBondarenko** [comment]
Hi @CaiJingLong 
Please follow up on https://github.com/flutter/flutter/issues/52207
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
