### ISSUE TITLE
flutter crashes

### ISSUE THREAD

**Issue by dyasem** [flutter/flutter#25762]
This is the error I get when I run "flutter doctor"

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: fe217682b49678e5)
Crash report written to C:\Users\davea\flutter_23.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by zoechi** [comment]
Please post the full error output.

**Comment by zoechi** [comment]
Please post the content of the file `C:\Users\davea\flutter_23.log`

**Comment by zoechi** [comment]
Please post the output of `git --version`

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
