### ISSUE TITLE
There should be more easing functions provided by default

### ISSUE THREAD

**Issue by marcoms** [flutter/flutter#25761]
Currently the list of easing functions provided by Flutter are:

```dart
  static const Curve linear = _Linear._();

  static const Curve decelerate = _DecelerateCurve._();

  static const Cubic ease = Cubic(0.25, 0.1, 0.25, 1.0);

  static const Cubic easeIn = Cubic(0.42, 0.0, 1.0, 1.0);

  static const Cubic easeOut = Cubic(0.0, 0.0, 0.58, 1.0);

  static const Cubic easeInOut = Cubic(0.42, 0.0, 0.58, 1.0);

  static const Cubic fastOutSlowIn = Cubic(0.4, 0.0, 0.2, 1.0);

  static const Curve bounceIn = _BounceInCurve._();

  static const Curve bounceOut = _BounceOutCurve._();

  static const Curve bounceInOut = _BounceInOutCurve._();

  static const ElasticInCurve elasticIn = ElasticInCurve();

  static const ElasticOutCurve elasticOut = ElasticOutCurve();

  static const ElasticInOutCurve elasticInOut = ElasticInOutCurve();
```

Of the bread-and-butter ease in and ease out functions, which most animations are built with, only two are provided. Unfortunately they are both relatively subtle when used for shorter animations. Although they can be distinguished when compared with a linear animation, to the naked eye they are effectively linear.

This is most obvious when compared with Material spec.

### Standard Accelerate and Decelerate easing curves from [material.io](https://material.io/design/motion/speed.html#easing):

(Provided by default in the Android support lib)

![screenshot from 2018-12-26 00-15-30](https://user-images.githubusercontent.com/4211302/50427568-99878e00-08a3-11e9-9534-5b85bda28c13.png)

![screenshot from 2018-12-26 00-15-52](https://user-images.githubusercontent.com/4211302/50427569-9c827e80-08a3-11e9-87ba-e9b453730ac5.png)

### Flutter Curves.EaseOut and Curves.EaseIn:

![screenshot from 2018-12-26 00-11-12](https://user-images.githubusercontent.com/4211302/50427572-b2903f00-08a3-11e9-96f8-6ba7f988802e.png)

![screenshot from 2018-12-26 00-10-36](https://user-images.githubusercontent.com/4211302/50427573-b9b74d00-08a3-11e9-8571-e1a4708878d3.png)

---

If we are to encourage users to follow the Material spec when targeting Android and other platforms, we ought to provide the essential easing functions to handle the job. I'd suggest adding at least the two default Accelerate/Decelerate/Standard Easing functions from Material, as well as the various grades of `ease-out-{quad,cubic,quart,quint,expo}` from [easings.net](easings.net), which are standard in many animation libraries.

**Comment by dnfield** [comment]
Fixed by #25788
