### ISSUE TITLE
Shake gesture

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2576]
This might be crazy.

Can we implement a shake gesture for GestureDetector?

I'm thinking a pointer touches down then goes left to right (or vice versa or even up to down or vice versa) and back again several (three?) times in a short period of time.

**Comment by abarth** [comment]
You should be able to write your own gesture recognizer for that gesture.  That's a fairly uncommon gesture and so might be a good way to explore custom gesture recognizers.  We should probably create a widget that helps you use custom gesture recognizers.

/cc @Hixie

**Comment by Hixie** [comment]
Yeah. To do this, you'd implement a `GestureRecognizer` subclass, and then provide the right bits to `RawGestureDetector` to create and maintain one. See `GestureDetector`'s implementation for how to do that latter bit, and follow the breadcrumps to the existing gesture detectors for hints on how to write those.

**Comment by apwilson** [comment]
Okay, sounds good!
