### ISSUE TITLE
ReorderableListView is too limited to be (always) useful

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#25789]
(This is as-of `1.0.0` stable)

[`ReorderableListView`][1] is a really nice way to get preferred default drag-drop re-ordering capability instead of writing this yourself for a `ListView`. When it works, it works!

Unfortunately, compared to the original [`ListView`][2], it is lacking:

* The `.builder` constructor (all `children: [...]` must be pre-configured).
* The `.separated` constructor.
* Various useful options, such as:
  - `bool reverse`
  - `bool primary`
  - `bool shrinkWrap`

Specifically, without `primary` and `shrinkWrap`, it isn't obvious (to me) how to place a `ReorderableListView` inside another scrolling container (like a `SliverList`). I could copy-and-paste all the `ReorderableListView` code myself, but it is nice to have this provide by the Flutter team so it stays up to date to best practices/API of the order `*ListView` classes.

(Another option might be some sort of `ShrinkWrap(child: ...`) widget)

[1]: https://docs.flutter.io/flutter/material/ReorderableListView-class.html
[2]: https://docs.flutter.io/flutter/widgets/ListView-class.html

**Comment by jonahwilliams** [comment]
cc @DaveShuckerow

**Comment by Daniel-BD** [comment]
Also, ReorderableListView is missing other parameters that ListView has, that would be useful. 
Like being able to give a ScrollPhysics the parameter 'physics'.

**Comment by Furtim** [comment]
> Also, ReorderableListView is missing other parameters that ListView has, that would be useful.
> Like being able to give a ScrollPhysics with the parameter 'physics'.

This is needed if you want to place a ReorderableListView() inside a RefreshIndicator() for example, as unless the list is larger than a page, it won't trigger the scroll mechanism the RefreshIndicator() needs.

**Comment by APopatanasov** [comment]
I have absolutely the same scenario as @Furtim. 

The combination of features like reordering and pull to refresh is very common. Adding the physics functionally to the ReorderableListView I believe will be pretty straight forward as internally the widget is using SingleChildScrollView.

Can somebody from the flutter team confirm if adding ScrollPhysics will be a good addition to the ReorderableListView and if it makes sense? If it is ok I could try implementing it and to make a pull request.

**Comment by albertpeiro** [comment]
I have a use case where I need to have two lists of the same type of item rendered one immediately after another.
```
LISTVIEW -----
item1: ScrollableList
item2: ListView
---------------
```
And behave like one big list.
I need to clamp the scrollable list with physics so it all scrolls as a one list.
It sounds to me like the suggestion in this thread expressed would help my use case.

**Comment by SwissCheese5** [comment]
ReorderableListView still does not have a physics parameter.

**Comment by mohammadne** [comment]
any update ?

**Comment by talatkuyuk** [comment]
I have the same issue, waiting the features that mentioned above for ReorderableListView().

I need to use it in a SingleChildScrollView().

**Comment by aidanstay** [comment]
Same issue, need to use ReorderableListView inside SingleChildScrollView.

**Comment by pedez** [comment]
A ReorderableListView.builder would be extremely helpful on an app I'm creating. Any predictions on updates for this widget?

**Comment by darrenaustin** [comment]
Hey folks, we are ramping up a design to try to address these and other issues with `ReorderableListView`. We are tracking it with #66080 and in a [design doc](https://docs.google.com/document/d/1JzNtMQ-jnPnSHEBoi6IO0x2qMMylwhvRslEDcmqiwSs/edit#heading=h.pub7jnop54q0). Feedback welcome.

**Comment by darrenaustin** [comment]
With the recent refactoring (PRs: #74299 and #74697), I believe we have addressed most of these issues. The one exception is the `. separated` constructor which we have another issue tracking (#76706). I am going to close this issue. If there is something else still missing, please open a new issue for it.
