### ISSUE TITLE
I don't want to Install the flutter plugin on all IDE ☹️☹️😢

### ISSUE THREAD

**Issue by Liberxue** [flutter/flutter#25783]
## Steps to Reproduce

1.  Can I have the right to choose?
2. I don't want to install the flutter plugin on all IDE
3. Why do I need to install the flutter plugin on all IDE, How Many IDE do I need to install?
4.  I installed the flutter plugin in Android studio, I repeatedly installed it in VSCode, and then repeatedly installed it in IntelliJ............☹️☹️😢

**Comment by Sh1d0w** [comment]
Duplicate of https://github.com/flutter/flutter/issues/25719 ?
