### ISSUE TITLE
on deleting app from android settings, unable to install it back on the same device

### ISSUE THREAD

**Issue by braghome** [flutter/flutter#2579]
on an installed app delete it from android settings menu and try to run the same app with flutter up

### Steps to Reproduce
* on an installed app
* delete it from android settings > apps
* flutter run again shows error

### Flutter Version
flutter --version
Flutter from https://github.com/flutter/flutter.git (on alpha)
Framework: 2fe456bf957d5df792b716599aa6f21d98997228 (8 days ago)
Engine:    d474e9d2b60a9cb111c09844c10081b68bde9252

### Logs
flutter run --checked --debug-port=16228 --start-paused --device-id CB5A20N72H • flutter logs
flutter/examples/stocks • checked mode • debug
Starting lib/main.dart on D6503...
Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=org.domokit.stocks/org.domokit.sky.shell.SkyActivity (has extras) }
Error type 3
Error: Activity class {org.domokit.stocks/org.domokit.sky.shell.SkyActivity} does not exist.
Error starting application on D6503.
Unable to run application
exited with code 2

**Comment by eseidelGoogle** [comment]
Yup, easy to reproduce.  @abarth says this is due to our current hash checks.  We don't remove the sha file when uninstalling the app, and thus think the phone has a SkyShell when it doesn't.  @devoncarew

**Comment by abarth** [comment]
I can take a look at this issue.

**Comment by eseidelGoogle** [comment]
This happens to any apk we build, not just SkyShell, btw.

**Comment by eseidelGoogle** [comment]
To work around this:
```
flutter apk
adb install build/app.apk
```
Then `flutter start` should work again.  There is also probably a way to remove the sha file from the device, I just don't know the location of it offhand.
