### ISSUE TITLE
Fade through color transition

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#258]
<a href="https://github.com/vlidholt"><img src="https://avatars.githubusercontent.com/u/1539812?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vlidholt](https://github.com/vlidholt)**
_Wednesday Nov 04, 2015 at 00:17 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1940_

----

Add transition to fade a scene out to a solid color (e.g. black or white), then fade in the next scene.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Wednesday Nov 04, 2015 at 15:45 GMT_

----

What layer is this to be used at? Navigator push()? dart:ui layers?

**Comment by vlidholt** [comment]
I'm thinking Navigator push()

**Comment by Hixie** [comment]
So this is basically an exit transition over half the performance, followed by an entrance transition over half the performance. The first fades to a colour, the second fades from that colour.

**Comment by vlidholt** [comment]
@Hixie exactly

**Comment by Hixie** [comment]
I'm working on doing this, FWIW.

**Comment by Hixie** [comment]
https://github.com/vlidholt/game/pull/1
