### ISSUE TITLE
AutomaticKeepAliveClientMixin does not work in DefaultTabController With 3 tabs

### ISSUE THREAD

**Issue by cqhchan** [flutter/flutter#25807]
## Steps to Reproduce

1. Use the code Template found here -> https://flutter.io/docs/cookbook/design/tabs

```dart
class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Page1(),
              Page2(),
              Page3(),
            ],
          ),
        ),
      ),
    );
  }
}
```
2. Create 3 stateful widget with `AutomaticKeepAliveClientMixin` set to True and `super.build(context)` under build before the return statement.

3. Log the `initState()` function for each page. 
e.g
```dart
class Page1 extends StatefulWidget{
  
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState

    return _Page1State();
  }

class _Page1State extends State<Page1> with AutomaticKeepAliveClientMixin{ 
  @override
    void initState() {
      super.initState();
      print("Page 1 init");
    }
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Text("Page 1");
  }
  @override
  bool get wantKeepAlive => true;

}
```
4. When moving from tab 1->2->3 or reverse, it only calls initState() on each Page once as intended. 
When moving from tab 1 -> 3, it calls initState on tab 1 and 2 again. 
When moving from tab 3 -> 1, it initStates again for tab 2 and 3. 

`AutomaticKeepAliveClientMixin` doesn't seem to work when moving across tabs that are not next to each other.

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by 96506926** [comment]
+1,I have the same issue now

**Comment by zoechi** [comment]
@96506926 @pepegich
Using "add reaction" on the initial comment would increase priority while `+1`, `mee too` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by SteveAlexander** [comment]
I have a PR that is on the way to fixing this: https://github.com/flutter/flutter/pull/24821

What needs to happen is that each page needs to be given a unique Key. This is because internally, the TabView switches around the order of its children temporarily.

@zoechi I'd love to get my PR into a fit state to land. I need a conversation with someone from the Flutter team to agree the right way forward on this though. I'm happy to put in the time to get this bug fixes (it's been cropping up in a number of issues expressing related but distinct symptoms). I've had no engagement on the PR though. How can we move this forward?

**Comment by zoechi** [comment]
@goderbauer perhaps?

**Comment by gtupak** [comment]
I am facing the same problem with `BottomNavigationBar` and [others have that issue too](https://stackoverflow.com/questions/53011686/flutter-automatickeepaliveclientmixin-is-not-working-with-bottomnavigationbar). Is it related in any way, or does anyone have a fix?

**Comment by divan** [comment]
Using `PageView` helps as a workaround (found solution [here](https://stackoverflow.com/a/54999503/2739942))

**Comment by gtupak** [comment]
Thanks, I'll try and get back to you

**Comment by gtupak** [comment]
The IndexStack trick did it for me! :) Thanks

**Comment by withinoneyear** [comment]
IndexedStack works for me too. But anybody knows why it needs to be wrapped in such a widget? or can we make it work without IndexedStack?

**Comment by chunhtai** [comment]
change reverted, will reland once issue is fixed

**Comment by jazzbpn** [comment]
> Complete runnable example
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: TabBarDemo(),
>     );
>   }
> }
> 
> class TabBarDemo extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: DefaultTabController(
>         length: 3,
>         child: Scaffold(
>           appBar: AppBar(
>             bottom: TabBar(
>               tabs: [
>                 Tab(icon: Icon(Icons.directions_car)),
>                 Tab(icon: Icon(Icons.directions_transit)),
>                 Tab(icon: Icon(Icons.directions_bike)),
>               ],
>             ),
>             title: Text('Tabs Demo'),
>           ),
>           body: TabBarView(
>             children: [
>               Page1(),
>               Page2(),
>               Page3(),
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> 
> class Page1 extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() {
>     return _Page1State();
>   }
> }
> 
> class _Page1State extends State<Page1> with AutomaticKeepAliveClientMixin {
>   @override
>   void initState() {
>     super.initState();
>     print("Page 1 init");
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     super.build(context);
>     return Text("Page 1");
>   }
> 
>   @override
>   bool get wantKeepAlive => true;
> }
> 
> class Page2 extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() {
>     return _Page2State();
>   }
> }
> 
> class _Page2State extends State<Page2> with AutomaticKeepAliveClientMixin {
>   @override
>   void initState() {
>     super.initState();
>     print("Page 2 init");
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     super.build(context);
>     return Text("Page 2");
>   }
> 
>   @override
>   bool get wantKeepAlive => true;
> }
> 
> class Page3 extends StatefulWidget {
>   @override
>   State<StatefulWidget> createState() {
>     return _Page3State();
>   }
> }
> 
> class _Page3State extends State<Page3> with AutomaticKeepAliveClientMixin {
>   @override
>   void initState() {
>     super.initState();
>     print("Page 3 init");
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     super.build(context);
>     return Text("Page 3");
>   }
> 
>   @override
>   bool get wantKeepAlive => true;
> }
> ```

[Is it possible to update the widget that is preserved using AutomaticKeepAliveClientMixin in Flutter?](https://stackoverflow.com/questions/62498341/is-it-possible-to-update-the-widget-that-is-preserved-using-automatickeepalivecl)

**Comment by Rutbamir** [comment]
Thank you so much. It worked for me!
