### ISSUE TITLE
Flutter initialize gradle forever  

### ISSUE THREAD

**Issue by farhanrahmadi** [flutter/flutter#25808]
I start learning flutter on arch linux 
i follow the doc and make project using intelij idea
when i run the project it way too long on gradle initialize

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/15106#issuecomment-444755905
This might not apply if you created a new project with a recent Flutter version.

**Comment by jankalfus** [comment]
Not to take a pun here, but I would rename this issue to "Flutter onboarding experience is terrible" and link all the related issues here.

On top of the aforementioned issue, I also had a problem where I wasn't able to accept Android licenses when using JDK 10. It looks like the SDK manager works only with JDK 8. The docs fail to mention that. Well, they even fail to mention that you need to accept them to be able to run anything :/

Here's output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.195], locale cs-CZ)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\jankalfus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\jankalfus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • LG H815 • LGH815a26aab1a • android-arm64 • Android 6.0 (API 23)
```

I really wanted to like Flutter, but after spending 3 hours and getting nowhere near being able to run it on at least a real phone device (as stupid Android Emulator doesn't work with Hyper-V enabled - how am I supposed to use Docker and Android Emulator on Windows at the same time???), I'm giving up for now.

I'm pretty sure a lot of work has been put into this project, but I just don't understand how the Flutter team is planning to attract developers if the onboarding experience is this bad.

**Comment by zoechi** [comment]
@jankalfus There is always room for improvement and it's constantly being worked on, 
but Android SDK is not maintained by the Flutter team.

> they even fail to mention that you need to accept them to be able to run anything

`flutter doctor` shows it as issue though

Not even https://developer.android.com/studio/ mentions the required Java version or Java at all :-/

**Comment by jankalfus** [comment]
@zoechi Well, I just got a crash when running the command suggested by `flutter doctor --android-licenses`, I had to figure out what was going on by myself. The thing with Android Studio is that everything is baked in there, so you seldom run into issues like this. But I don't want to use the monstrous Android Studio as my _editor_... (Now that I'm thinking about it, a workaround might be to run the project in Android Studio first, and only open it in VS Code after that. I'll try that and report back.)

For me, it's difficult to tell if this "'initializing gradle' taking forever" is an issue with Flutter or the Android SDK. And frankly, I don't care. I just want to go into my favorite editor, and start coding and fiddling with an app on device, without having to spend many hours trying to figure out why even such a basic thing as deploying an app to a device is not working :/

The Flutter team has to realize that if they want to attract React Native or Xamarin or even native developers, they'll have to do better than that. My more than a year long experience with React Native hasn't been what I would exactly call great. Nonetheless, it seems like there still isn't anything better out there. Xamarin totally failed at that in my opinion (terrible experience) and it's starting to look like Flutter is just another Xamarin. I really really wanted to like Flutter, but right now, I just can't. Flutter can have a million amazing features, but if it fails at such a simple task as deploying an app to a device, it just isn't worth bothering with (sad face).

**Comment by zoechi** [comment]
> And frankly, I don't care

It's a bit difficult to support all scenarios. Every OS and package manager installs stuff differently,
and every developer follows install instructions more or less rigorously ;-)
The beaten path with using Android Studio obviously works best.

For the rest we need to fix one issue at a time 
(while daily new pop up after updates of any of the pieces contributing to the whole ecosystem)

Therefore please create one issue for one problem at a time and provide as much information as possible that allows us to reproduce.

**Comment by jankalfus** [comment]
Well, following the docs for running Flutter in VS Code on Windows step-by-step, having a clean install of Android Studio + Flutter, shouldn't result in these issues IMHO :)

Nonetheless, the workaround I mention (run it in Android Studio first) worked, so I might just give Flutter a chance :)

**Comment by zoechi** [comment]
@DanTup any thoughts?

**Comment by shubhamhackz** [comment]
@zoechi 
Experiencing the issue and can't able to resolve since 1 hour now.

**Comment by zoechi** [comment]
@shubhamhackz please post at least the output of `flutter doctor -v`.
Is this about a new project or an existing one?

**Comment by zoechi** [comment]
@shubhamhackz hard to tell. Perhaps just an intermittent network issue.

**Comment by jankalfus** [comment]
@shubhamhackz Where are you running the gradle command from? Android Studio / VS Code / Flutter CLI?

**Comment by shubhamhackz** [comment]
@zoechi I have manually downloaded `gradle-4.10.3-all.zip` from [here ](https://services.gradle.org/distributions/) and unziped the file into `.gradle/wrapper/dists` and that fixed my issue. My network speed is good don't know why it was happening.

@jankalfus I have First tried Flutter CLI and Vs Code after that I also tried using Android Studio. All of them raised same issue.

**Comment by DanTup** [comment]
@jankalfus 

> Well, following the docs for running Flutter in VS Code on Windows step-by-step, having a clean install of Android Studio + Flutter, shouldn't result in these issues IMHO :)

I don't think anybody here would disagree with this, but it's a very difficult thing to guarantee because there are so many variables involved (consider Windows, VS Code, the Dart plugin, Flutter, Gradle, Java, Git, ADB, and that each one has many versions, plus other factors like how users have set things up on their machine, the performance of their computer/network, proxy servers, etc.). Sometimes things are broken because of factors outside of Flutter's control, and sometimes they're just bugs that aren't discovered until someone hits them.

That said, I've seen reports that the first time running Gradle can take a really long time (> 10 minutes even on a great connection). If you haven't already left it that long, it's worth trying and posting back the results as it may be easier to figure out what's going on knowing if it's broken versus just incredibly slow.
