### ISSUE TITLE
Exceptions not propagated back to message channels on iOS

### ISSUE THREAD

**Issue by andreybutov** [flutter/flutter#25800]
In my Flutter app, I have **main()** set up to catch runtime errors, like this:
```dart
    void main() async
    {
        runZoned< Future<void> >(() async {
            runApp ( MyApp() );
        }, onError: ( error, stackTrace ) async {
            print("Got an error");
            // ...
        });
    }
```

This works fine for all Flutter-level errors, and also works fine for code that runs natively on Android, but the **onError:** handler is never called for iOS apps.

An example:

My Flutter app calls the following native method through a method channel:

```dart

    void _onButtonClick() async {
        final channel = const MethodChannel('my-custom-channel');
        await channel.invokeMethod('testMethod');
    }
```
Here's the Android implementation:
```java
	@Override
  	protected void onCreate(Bundle savedInstanceState)
	{
    	super.onCreate(savedInstanceState);
    	GeneratedPluginRegistrant.registerWith(this);

    	MethodChannel channel = new MethodChannel(getFlutterView(), "my-custom-channel");

		channel.setMethodCallHandler(new MethodCallHandler() {
			@Override
			public void onMethodCall(MethodCall call, Result result) {

				if ( call.method.equals("testMethod") ) {
					throw new IllegalStateException("This is a native Android exception.");
				} else {
					result.notImplemented();
				}

			}
		});

  	}
```
When this code executes, the **IllegalStateException** is "propagated" back up to the **onError:** handler in Flutter's **main()** function, and I get some info and a bit of a stack trace, as expected.

Here is the iOS implementation:
```objective-c
    - (BOOL) application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
    {
        FlutterViewController* controller = (FlutterViewController*)self.window.rootViewController;
    
        FlutterMethodChannel* channel = [FlutterMethodChannel
            methodChannelWithName:@"my-custom-channel"
            binaryMessenger:controller];
    
        [channel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
    
            if ( [call.method isEqualToString:@"testMethod"] )
            {
                @throw([NSException
                    exceptionWithName:@"iOS Exception"
                    reason:@"Testing native iOS exceptions"
                    userInfo:nil]);
    
                result(FlutterMethodNotImplemented);
            }
            else
            {
                result(FlutterMethodNotImplemented);
            }
    
        }];
    
        [GeneratedPluginRegistrant registerWithRegistry:self];
        return [super application:application didFinishLaunchingWithOptions:launchOptions];
    }
```

In this case, the **onError:** handler in Flutter's **main()** function is never called. The console output is the following:

    Lost connection to device.
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x00000001065cf1bb __exceptionPreprocess + 331
    	1   libobjc.A.dylib                     0x0000000105b6d735 objc_exception_throw + 48
    	2   Runner                              0x0000000103cd0772 __57-[AppDelegate application:didFinishLaunchingWithOptions:]_block_invoke + 226
    	3   Flutter                             0x0000000103d7b9a2 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
    	4   Flutter                             0x0000000103d98616 _ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
    	5   Flutter                             0x0000000103d9bfbe _ZN5shell15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 38
    	6   Flutter                             0x0000000103dec8e9 _ZNSt3__110__function6__funcIZN5shell5Shell29OnEngineHandle<…>

That looks like a bit of a stack trace output from iOS land, but nothing ever "propagates" back up to the Flutter **onError:** handler, like it does with Android.

It's worth mentioning that this only happens for native NSExceptions, and also happens if I force a crash with something like **assert(false)** (both in the simulator and on physical devices), but it does not happen if I use **[FlutterError errorWithCode: ... ]** instead of native NSExceptions on the iOS side.

So, is there a way to have native iOS exceptions and crashes propagate back up to the **onError:** handler in Flutter?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by andreybutov** [comment]
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/andreybutov/flutter_development/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/andreybutov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

```

**Comment by kbokarius** [comment]
Is this ever going to be addressed, or is there a workaround? It's certainly problematic that we can't catch native iOS errors in a Flutter app.

**Comment by gaaclarke** [comment]
Exceptions in Objective-C aren't used the same way as exceptions are in Java.  They are really used to crash an app and not meant to be caught and recovered from.

The correct way to report errors in Objective-C with method channels is to call the `FlutterReply` with a `FlutterError`.  See also the docstring for [FlutterMethodCallHandler](https://github.com/flutter/engine/blob/4b69cf2c49db43ec89bb5004d1f4b767194c4fea/shell/platform/darwin/common/framework/Headers/FlutterChannels.h#L141:L141)

**Comment by kbokarius** [comment]
@gaaclarke is there an example or some documentation for how to implement FlutterMethodCallHandler so that it catches unhandled iOS errors? We ultimately just want to report the error/crash to Sentry.io so that we can track it.
