### ISSUE TITLE
flutter -d could take shorter identifier

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2581]
Right now, `flutter -d ...` requires a complete/full identifier, like `2175d44c48c2ba9a5bbad10262cf8e7f04aab8e7` or `031462ee213e73b9`. This works, but it's a bit cumbersome.

I don't think of my devices as long IDs, nor do I know those long IDs off the time of my head. I need to run `flutter list` and then copy the long identifier, before I run with `flutter -d ...`

Suggestion: use a prefix to identify the device. For example, if the output of `flutter list` is:

```
~/flutter/testme3 $ flutter list
2 connected devices:

Nexus 5 (031462ee213e73b9)
iPod touch (2175d44c48c2ba9a5bbad10262cf8e7f04aab8e7)
```

Then maybe I could run:

```
flutter -d nexus run
flutter -d ipod run
flutter -d 031 run
flutter -d 2175 run
```

And the tool finds the first match.

Not sure if this is possible, but if we can use logical names or shorthand names for device identifiers, that would make it easier.

Thanks!

**Comment by devoncarew** [comment]
Yeah, we could look for exact matches, and then look to see if there was a (unique) prefix match.

**Comment by devoncarew** [comment]
fixed in https://github.com/flutter/flutter/pull/2612

**Comment by sethladd** [comment]
Thanks!
