### ISSUE TITLE
Long pause, wondering if anything is happening or crashed, from flutter run + ios

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2582]
```
flutter run --checked --debug-port=16230 --start-paused --device-id 2175d44c48c2ba9a5bbad10262cf8e7f04aab8e7 • flutter logs
mute_field_6440/ • checked mode • debug
Starting lib/main.dart on iPod touch...
Fetching the Xcode project archive from the cloud...
Downloading https://storage.googleapis.com/flutter_infra/flutter/d1515e676438d79046508ca009044df246564ced/ios/FlutterXcode.zip...
Unzipping Xcode project to local directory...
Xcode project created at /Users/sethladd/Code/mute_field_6440/ios/.generated/.
User editable settings are in /Users/sethladd/Code/mute_field_6440/ios/.
```

At this point, a long pause (10 secs ish?) before the next thing prints to my screen. I don't know: did it crash? Is anything happening? What should I expect? These long pauses make users wonder if they should Control-C and start over.

Could we print a spinner here? Or a progress bar? Thanks!

**Comment by sethladd** [comment]
There's also a long pause at:

```
~/Code/mute_field_6440 $ flutter -d 2175d44c48c2ba9a5bbad10262cf8e7f04aab8e7 run
Starting lib/main.dart on iPod touch...
```

Printing a spinner/progress bar here would be really helpful, too. Thanks!

**Comment by eseidelGoogle** [comment]
I'm not sure what to do here.  Xcode can take a while.  We could have a tools spinner I guess?

**Comment by sethladd** [comment]
A spinner would be helpful. Something to signal "we're working on it".

**Comment by xster** [comment]
I suspect it's a console output issue. @sethladd: did you run from the command line or from an IDE?

There's a spinner currently but I did notice instances of it not showing when running inside VSCode.

**Comment by xster** [comment]
This is done with https://github.com/flutter/flutter/pull/14715
