### ISSUE TITLE
Invalid file when installing on phone

### ISSUE THREAD

**Issue by Bonfra04** [flutter/flutter#25824]
Hi, i've been testing my app for a while in an emulator and everything went normal. Now i've exported the apk with `flutter build apk` but when i try to install it on my phone i recive" invalid file "error what is this caused by?

**Comment by kangwang1988** [comment]
Please paste `flutter doctor -v` result here. And if possible, can you give us a demo project to reproduce this problem, at least apk which reports this error.

**Comment by Bonfra04** [comment]
just tried on another phone and ther just say "app not installed" after installation
![5c467228-7781-4aa9-9423-c96872eb0612](https://user-images.githubusercontent.com/39456413/50499526-8bc03d00-0a4a-11e9-960d-ac5c7dbff361.jpg)




doctor output:
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Versione 10.0.17763.195], locale it-IT)
    • Flutter version 1.0.0 at C:\plugins\flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

\Unhandled exception:
Exception: adb not responding
#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:99:9)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:130:21)
<asynchronous suspension>
#3      Device.descriptions (package:flutter_tools/src/device.dart:309:58)
<asynchronous suspension>
#4      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:697:31)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#7      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#10     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#11     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#19     Future._complete (dart:async/future_impl.dart:476:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by Bonfra04** [comment]
> Please paste `flutter doctor -v` result here. And if possible, can you give us a demo project to reproduce this problem, at least apk which reports this error.

sorry totally beginenr how can i get a demo project? just send the code or the .apk file?

**Comment by Bonfra04** [comment]
> Got it. Please install the apk using adb install command directly to see if it works fine.
> Besides, please run `flutter run` command to build and install the apk on your devices. If it fails, paste the full log here.

on the emulator works perfectly with every configuration. but when i have to install in on proper device is the problem. with android java apps i just export the apk send it to the device via whatsap web and open it from there but with flutter it work on emu and on my cellphone. is there a way that i can run command line to install it directly on ?

**Comment by kangwang1988** [comment]
Steps:
1. Plug your android device into your computer
2 . Using `adb devices` to make sure that it exists
List of devices attached
xxxyyy	device 
PS. xxxyyy is your real device id.
3.flutter run -v -d  xxxyyy

It will build and install the apk on your device and print as much information as possible.

**Comment by Bonfra04** [comment]
the main error of this thread: "invalid file" occurs when i try to open the .apk file from huawei.
the error rapresented on the screenshot above occurs when i try to run the .apk file from samsung.
But, when i run it on a j5-2016 samsung it install and run perfectly.
another problem, but i think is just an old version, is that abd doesn't find any devices...

**Comment by Bonfra04** [comment]
PS.
i'm sorry for long time between two posts but i'm in italy and now here it's about 22:00.. i can code only during evening so sometimes i can be very slow to respond

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kazenokage** [comment]
Not having enough free space on the device can also result in the described error message.

**Comment by MykhIvanov** [comment]
I'd like to report the same issue on some devices. The same build has been installed on the Huawei and Xiaomi devices (android 9, 7) and runs successfully, but the installing process crashes on some other devices (like Meizu, runs android 5,6). Moreover after install try via terminal and adb commands the app tries to open and crashes forever (this 2 step process looped), but there was the "success" result in the terminal after installing process' finish.

**Comment by ThitSarNL** [comment]
I can pass this error now. 
1. Let it installable, (Setting->BIOMETRICS AND SECURITY->Installl unknown apps->My Files->Allow from this source)
2. Clear internal storage (good if u also clear sd card storage) more than ur app size.
3.  Android Studio->Terminal->Type "flutter build apk" and wait for a while and find the file in folder of YourAppFolder\build\app\outputs\apk\release\app-release.apk

**Comment by joandylevi** [comment]
https://icetutor.com/question/app-not-installed-error-on-android/
