### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 59451

### ISSUE THREAD

**Issue by cd89101112** [flutter/flutter#25834]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs
[flutter_01.log](https://github.com/flutter/flutter/files/2714159/flutter_01.log)

```
```

```
```

**Comment by kangwang1988** [comment]
It seems that `https://storage.googleapis.com/flutter_infra/flutter/220ea0e1ec2829064295766f41b768c39eaca643/android-arm-dynamic-release/artifacts.zip`
is not available from your machine.
Please check if you can download the uri from browser.
If you're in China, visit https://flutter.io/community/china for more.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by mzl1988** [comment]
I also met。
![image](https://user-images.githubusercontent.com/11645762/74127183-dda73080-4c14-11ea-8597-91584c523b8f.png)
