### ISSUE TITLE
When I insert new items into list inside setState method layout not reflect changes on the screen in flutter?

### ISSUE THREAD

**Issue by a7me63azzab** [flutter/flutter#25837]
I want to implement this layout in flutter
![screenshot from 2018-12-27 20-59-29](https://user-images.githubusercontent.com/13996786/50509171-9cde6d80-0a8d-11e9-86c7-157e6f764c99.png)

the problem:
the gridview widget not rerendere when the state changes inside setState method 
I did the following steps

1. I create a statefull widget.
2. Added a gridview.count widget to show selected images on the screen.
3. Added a widget that contain add button to the list that will be returned by gridview to ensure that it will be the last item in the list of images .
4. when i clicked on the add button i selected an image from gallery and insert it to the beginning of the list inside a setState methed to rerender the widget when the list changes.
5. images added to the list successfully but newly added images not appeared on the screen.

code

```dart
     class _AddScreenState extends State<AddScreen>{
        List<Widget> _images = [];


      void _getImage(BuildContext context, ImageSource source) {
          ImagePicker.pickImage(source: source, maxWidth: 
        400.0).then((File image) {
          print(image);
            setState(() {
              _images.insert(
                0,
                Container(
                    height: 80,
                    width: 80,
                    decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15),
                    image: DecorationImage(
                      image: FileImage(
                      image,
                      ),
                      fit: BoxFit.fill,
                    ),
                  ),
                ));
            });
          Navigator.pop(context);
        });
      }


        @override
        Widget build(BuildContext context) {
              return GridView.count(
                      padding: EdgeInsets.all(5),
                      mainAxisSpacing: 5,
                      crossAxisSpacing: 5,
                      shrinkWrap: true,
                      crossAxisCount: 3,
                      children: _images
                        ..add(
                          InkWell(
                            onTap: () {
                              _getImage(context,ImageSource.camera);
                            },
                            child: Container(
                              height: 80,
                              width: 80,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image:

                  AssetImage('assets/images/ic_add_pic.png'),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                          ),
                        ),
                      );
                    }
                   }
```
the expected result:
when the user click the add button, selected images must added to the beginning and the add button must moved to the end each time i added a new image.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by a7me63azzab** [comment]
Ok @zoechi , sorry

**Comment by Alfie705** [comment]
Hi Ahmed,
Did you find the solution for this problem? I'm looking also for that kind of UI layout except that I want the add button at the first of the list.
Thanks,
Al
