### ISSUE TITLE
Provide webview_flutter a way to set http headers

### ISSUE THREAD

**Issue by kitoko552** [flutter/flutter#25831]
I think webview_flutter should be added a feature to set http headers. 
In my project, we need headers to keep user logged in status in web view.

I'm a iOS developer so I don't know about Android web view but in iOS, you can use `NSMutableURLRequest` and `setAllHTTPHeaderFields` method to set headers, then give it to `WKWebview.loadRequest` in [loadUrl](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/ios/Classes/FlutterWebView.m#L158-L166) method like this.

```objc
NSURL* nsUrl = [NSURL URLWithString:url];
if (!nsUrl) {
    return false;
}
NSMutableURLRequest* req = [NSMutableURLRequest requestWithURL:nsUrl];
[req setAllHTTPHeaderFields:headers];
[_webView loadRequest:req];
return true;
```

I hope you will consider this proposal.
Thank you.

**Comment by Jasphere-Appsploration** [comment]
Would like to see this feature soon. Our project would like to present different behaviour based on HTTP header value. Looking forward to this!

**Comment by filly82** [comment]
Would alse appreciate the feature

**Comment by iskakaushik** [comment]
https://github.com/flutter/plugins/pull/1516 has just landed. It should address this use-case.

**Comment by NewITCorp** [comment]
Could you guys please also add headers property to WebView constructor too. Because I don't want to reload page twice.

**Comment by tal412** [comment]
> Could you guys please also add headers property to WebView constructor too. Because I don't want to reload page twice.

I would like to see this too.

**Comment by tal412** [comment]
> Could you guys please also add headers property to WebView constructor too. Because I don't want to reload page twice.

I would like this to be added too.
