### ISSUE TITLE
flutter_gallery__back_button_memory is flaky

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#25855]
Seems to have started being flaky around 19ce65eec923535d5d0daf580429a2d23596dffd

![image](https://user-images.githubusercontent.com/1024117/50526201-6278ce80-0a95-11e9-8b28-01cf8494da20.png)

**Comment by amirh** [comment]
Might be related to https://github.com/flutter/flutter/issues/25481

**Comment by dnfield** [comment]
Also has inexplicably resolved, maybe for same unknown reasons as #25481

**Comment by dnfield** [comment]
Reopening this.  It seems to flake out every few days now.  Rebooting the device seems to help.
