### ISSUE TITLE
Does package:http/http.dart support https request or not?

### ISSUE THREAD

**Issue by vanshu** [flutter/flutter#25877]
## Steps to Reproduce

I am using 'package:http/http.dart' as http, seems it doesn't support https request ,return the error.

## Logs
here is the  error log 
```
HandshakeException:Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED:certificate is not yet valid(handshake.cc 363))
```

```
```

```
```

```
```

**Comment by vanshu** [comment]
[same question with me ](https://github.com/flutter/flutter/issues/23045), but I typed 
```
flutter doctor --android-licenses
```
it doesn't works. Where is samle link to show https request of this library?

**Comment by zoechi** [comment]
> Where is samle link to show https request of this library?

There is no difference about how to make HTTP or HTTPS requests except the additional `s` in the URL. Your problem is somewhere else. You didn't respond to my comment above.

**Comment by vanshu** [comment]
It's my mistake, my android phone set wrong time and wrong timezone, then it will get CERTIFICATE problem
