### ISSUE TITLE
SweepGradient fails to apply if start angle greater than end angle

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#25882]
I am trying to implement a gradient Diagonally something like this https://uigradients.com/#HoneyDew
the only possible Option was sweep gradient but that doesn't seem to work,and I don;t find enough documenation is there any way How to implement a gradient diagonally,I would really appreciate you help thanks in advance

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by filleduchaos** [comment]
Perhaps I'm missing something, but I don't see how the linked example requires a Sweep gradient. Maybe a screenshot of the effect you're trying to help would work.

That aside, [linear gradients](https://docs.flutter.io/flutter/painting/LinearGradient-class.html) can very well be set at an angle if all you need is a gradient that runs diagonally.

**Comment by maheshmnj** [comment]
yes my problem is resolved using linear gradients but I see a issue with sweep gradient start and end angle

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
