### ISSUE TITLE
Flutter library firebase_auth iOS/Android decline to build

### ISSUE THREAD

**Issue by mitko9000** [flutter/flutter#25880]
Hello All 
`firebase_auth` cause Android and iOS project not to compile when added as dependency to the Flutter project.

iOS yield that 
`#import <firebase_auth/FirebaseAuthPlugin.h> is missing` 
and Android is telling me the same `import io.flutter.plugins.firebaseauth.FirebaseAuthPlugin;
import io.flutter.plugins.firebase.core.FirebaseCorePlugin;`

Is there any workaround to make it work ?

**Comment by zoechi** [comment]
`flutter clean` might be worth a try.
Could also be #16049
Please post the full error output.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kroikie** [comment]
@dimityrivanov

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/526. Any further collaboration will be done there.
