### ISSUE TITLE
CupertinoNavBar autosets an `AnnotatedRegion` and does not allow overriding `SystemUiOverlayStyle`

### ISSUE THREAD

**Issue by agrosner** [flutter/flutter#25886]
In `CupertinoNavBar`, there is a function [_wrapwithBackground](https://github.com/flutter/flutter/blob/b8a035a3d416a19756c60c4fcf2394b4af06740f/packages/flutter/lib/src/cupertino/nav_bar.dart#L85) which will compute the luminance of the background on the navigation bar and wrap it with `AnnotatedRegion<SystemUiOverlayStyle>`. There is no way to override this, and in my application, I am already setting an `AnnotatedRegion<SystemUiOverlayStyle>` of a different color. 
What ends up happening is that the screen enters with proper color (in my case white) and then ends with black once animation completes without any way to override or change this.

Flutter doctor:
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.2)
[✓] Connected device (1 available)
```

**Comment by agrosner** [comment]
here is what is happening:
![video](https://user-images.githubusercontent.com/2117859/50540048-ae407c00-0b58-11e9-9fb5-395ca8e1af1b.gif)

**Comment by zoechi** [comment]
Can you please add a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by xster** [comment]
Indeed, we need to add a public API to let people disable this.

**Comment by jonahwilliams** [comment]
the material AppBar has the same issue. Straw fix: add `bool autoTheme` to each widget, defaulting to true. If false, do not insert the annotation region widget into the tree.

**Comment by KeyZJ** [comment]
Hello, are there any progress on this issue?
Felt into this problem too, but this one seems easy to implement (provide flag for CupertinoAppBar to control this behaviour?).
Or maybe someone will suggest how to overwrite this?

**Comment by TahaTesser** [comment]
Hi @agrosner 
Are you still experiencing this issue latest stable?
If so,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
