### ISSUE TITLE
CONGRATULATIONS GOOGLE / FLUTTER TEAM

### ISSUE THREAD

**Issue by SogoGolf** [flutter/flutter#25898]
ok, i apologise for this post i know it's the wrong forum and not appropriate here.

**BUT**

i felt compelled to write it and i want to make sure at least some of Google's Flutter engineers get to see it.

Flutter 1.0 is to me, the cross-platform software equivalent of the _revolution_ that occurred when we moved from 'flip phones' to the iPhone. 

I've built production apps with Appcelerator and React Native over the years- they've tried this too and hats off to their efforts. HOWEVER IMHO Google's engineers have crafted an offering that takes this to a whole new level and is phenomenally productive. UN-FREAKING BELIEVABLE what can be done with Flutter in it's current (1.0) state. I'll say right here that we're moving from all native, to Flutter. Now. Viva (Flutter) Revolution!  

**WELL DONE GOOGLE AND CONGRATS TO ALL THE ENGINEERS BEHIND THIS PRODUCT.** 

There you go. Feel free to delete this post now. :-)

**Comment by zoechi** [comment]
Great to hear 👍 
Ideally you'd write a blog or Medium article about your experience and share it on Gitter, Twitter, ...
