### ISSUE TITLE
Plugin firebase_auth: ^0.6.6: Invalid signature (wrong jwt signing algo used)

### ISSUE THREAD

**Issue by QuentinG3** [flutter/flutter#25899]
Hi,

The idToken returned by the method getIdToken() in firebase_auth returns a jwt signed with the algorithm HS256 while the "alg" in the header section of the jwt is "RS256". 

In the documentation (https://firebase.google.com/docs/auth/admin/verify-id-tokens) in the last section (Verify ID tokens using a third-party JWT library) seems to indicate that the expected algorithm to use is well "RS256".

Thus the jwt should be signed with RS256 instead of HS256.

Thank you !

**Comment by MauriPastorini** [comment]
Is this error resolved? I keep getting invalid signature from` getIdToken()` function

**Comment by shahidhk** [comment]
@QuentinG3 Can you tell us how you solved the issue?

**Comment by luizpaulofranz** [comment]
Hey there, I'm facing this same issue, can you share with us how you solve it please @QuentinG3 ?

**Comment by luizpaulofranz** [comment]
Hey guys, in my case, what was the problem: I was generating token in my flutter app, and printing it in my log with: `print(token)`, and then testing my backend with postman requests, BUUUT, now I discovering that the flutter print method HAS LIMIT OF CHARACTERS, and it was cutting my token just in the signature part, so, I get this token value by debugging and all is magically working now! Maybe it can help someone.
