### ISSUE TITLE
Basic example doesn't compile properly

### ISSUE THREAD

**Issue by bordnul** [flutter/flutter#25903]
I'm trying to learn how to use this package and I found something odd. Using the given basic example with the line 

**controller?.dispose();**

doesn't compile properly (even for debug). But if you change it to 

**controller.dispose();**

it works just fine.

**Comment by zoechi** [comment]
> doesn't compile 

would at least need the exact error output.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
