### ISSUE TITLE
Locale always give en_US

### ISSUE THREAD

**Issue by ctrysbita** [flutter/flutter#25906]
Flutter locale always give `en_US` on iOS even when system language was set to `zh_CN`

Both following method give en_US:
1. `Platform.localeName`
2. `Localizations.localeOf(context)`

Locale works well on Android.
Locale works well on iOS with Flutter version before `v0.11.12`.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment]
Do you have the supported languages listed in `Info.plist`? https://github.com/flutter/flutter/issues/14128#issuecomment-401028142

**Comment by kangwang1988** [comment]
@ctrysbita 
It would be better if you can post a github project which may help us reproduce this issue.

**Comment by ctrysbita** [comment]
@zoechi @kangwang1988 Ok, it works well now after I add the localizations to Info.plist.
I think we may have a page for old projects to update when new version of framework have some breaking changes.
