### ISSUE TITLE
image_picker missing 0.4.11 release

### ISSUE THREAD

**Issue by james-lawrence** [flutter/flutter#25907]
latest package available is 0.4.10, but latest in repository seems to be 0.4.11.

in particular I ran into this [issue](https://github.com/flutter/plugins/pull/748) which was fixed months ago.

**Comment by zoechi** [comment]
You can use it as Git dependency 
https://www.dartlang.org/tools/pub/dependencies#git-packages
You need to pass the `path: packages/image_picker`

**Comment by cyanglaz** [comment]
Sorry for the late response. You should be able to update image_picker to a newer version now and the issue should be resolved. Closing this issue ticket.
