### ISSUE TITLE
I hope die out video_player, Switch to ijkplayer!

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#25910]
video_player has too much bug,

I hope video core Switch to ijkplayer!

current, Has been developed, but have some bug.

[https://github.com/An-uking/Flutter_IJKPlayer](url)

**Comment by zoechi** [comment]
Thanks for your contribution!
This is not the right place to advertise it though.

**Comment by 0-php** [comment]
@Seifon 兄弟又见到你了。。。
