### ISSUE TITLE
Flutter, top navigation bar

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#25919]
I wrote question on [StackOverflow](https://stackoverflow.com/questions/53985331/flutter-top-navigation-bar-with-10-entities).

How can I implement this kind of menu bar? I tried to implement by Column with ListView but I failed.

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.red,
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.refresh),
            onPressed: () => _getWebtoonData(),
          )
        ],
      ),
      body: Column(
        children: <Widget>[
          ListView(
            shrinkWrap: true,
            scrollDirection: Axis.horizontal,
            children: <Widget>[
              Container(width: 10.0,),
              Container(width: 10.0)
            ],
          ),
          _getWebtoonGridView(),
        ],
      ),
    );
  }
```

Error message

> I/flutter (10834): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
> I/flutter (10834): The following assertion was thrown during performLayout():
> I/flutter (10834): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1598 pos 16:
> I/flutter (10834): 'constraints.hasBoundedHeight': is not true.
> I/flutter (10834):
> I/flutter (10834): Either the assertion indicates an error in the framework itself, or we should provide substantially
> I/flutter (10834): more information in this error message to help you determine and fix the underlying cause.
> I/flutter (10834): In either case, please report this assertion by filing a bug on GitHub:
> I/flutter (10834):   https://github.com/flutter/flutter/issues/new?template=BUG.md

Flutter doctor

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale ko-KR)
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [√] Android Studio (version 3.2)
> [!] IntelliJ IDEA Community Edition (version 2018.2)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [!] VS Code, 64-bit edition (version 1.30.1)
> [√] Connected device (1 available)

**Comment by zoechi** [comment]
StackOverflow is the right place for this kind of question.
You should add the information you posted above to the SO question.
