### ISSUE TITLE
MarkdownStyleRaw optimisations

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2591]
Right now you can't create MarkdownStyleRaws on the fly (since that will force a reparse each time, since they have no operator==), and you can't create constants for them (since they don't have const constructors). We can't just give them operator==s, because then they'd do redundant creations of the map each time. Maybe we can have the map be provided by a function that the consumer calls once, and then turn the rest of the class into a normal const constructable object with operator==?

**Comment by eseidelGoogle** [comment]
@abarth has an in-progress rewrite of flutter_markdown which may obsolete this.
