### ISSUE TITLE
All switch nobs highlight when any one of them is animating

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2592]
Open Components > Selection Controls (actually named toggle_controls_demo.dart in the source) and click on any switch at the bottom.

All of the switches will expand while the first one is animating.
![screen](https://cloud.githubusercontent.com/assets/11857803/13687447/3493e608-e6d0-11e5-80d2-f841dcaa8a97.png)

**Comment by eseidelGoogle** [comment]
![screen](https://cloud.githubusercontent.com/assets/11857803/13687455/416fca4a-e6d0-11e5-8d6a-d6779a593f1e.png)

**Comment by abarth** [comment]
This is a duplicate of #2670.
