### ISSUE TITLE
Remove `new` keyword from style guide

### ISSUE THREAD

**Issue by suragch** [flutter/flutter#25924]
The [Flutter style guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) uses the `new` keyword in multiple code examples. It is my understanding that this is no longer needed as of Dart 2 ([source](https://medium.com/dartlang/announcing-dart-2-80ba01f43b6)).

I suggest that the `new` keyword can be removed from the code examples in the style guide. For example,

- `new ListView.builder(...);`
- `new EdgeInsets.TRBL(0.0, 8.0, 0.0, 8.0);`
- `Foo f = new Foo(...);`
- `new PopupMenuItem<String>(...)`

could be written as

- `ListView.builder(...);`
- `EdgeInsets.TRBL(0.0, 8.0, 0.0, 8.0);`
- `Foo f = Foo(...);`
- `PopupMenuItem<String>(...)`

**Comment by kangwang1988** [comment]
@Hixie 
What do you think of this proposal?

**Comment by xster** [comment]
Removed in https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo/5c279fe8d7b52d31ebcf05385f69c636a6b8e676
