### ISSUE TITLE
plugins/url_launcher: support ASWebAuthenticationSession on iOS

### ISSUE THREAD

**Issue by MagicalTux** [flutter/flutter#25928]
## Description

When using url_launcher on iOS 11+ to allow the user to login to a service, a safariVC is shown, but due to rules in iOS 11+ cookies are not shared, meaning the user has to go through the login process again.

Apple provides to solve this issue [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession), which will show the user an alert prior to opening the safariVC with the original Safari cookies.

Note: the object [can also be passed a custom scheme callback URL](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990952-init) and allowing this to be defined in the call to launch() would allow to fully prevent any risk of another application hijacking the custom protocol used to catch the token (RFC7636 helps rendering useless malicious attempts, but there are still risks of protocol collision/etc).

**Comment by LinusU** [comment]
Are you accepting pull requests for this? Need this in an app I'm currently working on ☺️

**Comment by MagicalTux** [comment]
It should be noted that another plugin now provides this feature: https://pub.dev/packages/flutter_web_auth

**Comment by LinusU** [comment]
Yeah, I ended up writing this since I didn't get any response here ☺️ 

Should have linked it before, thanks for doing it 👍

**Comment by stuartmorgan** [comment]
`url_launcher` is intended to be a simple, general purpose plugin. Specialized use cases like an authentication flow would best be served by a separate plugin, so closing.
