### ISSUE TITLE
Are we supposed to check "Contain encryption” in the app store?

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#25935]
Does flutter app requires to use `Contain encryption` when uploading the app to the app store, sorry if this questions sounds dumb. I am new on the app store, and not sure if flutter does some `https://,` sort of work behind the scene.  

PS: Let's assume the app built is just plain hello world.

**Comment by MichaelPriebe** [comment]
I did not even know that is an option, but I have never checked it for any of my apps.

**Comment by dark-chocolate** [comment]
@MichaelPriebe  When you hit `Submit for review` button then they ask you to fill this option, otherwise on the app store connect page, it is not visible.

**Comment by zoechi** [comment]
Related to https://flutter.io/docs/deployment/android

See also https://stackoverflow.com/questions/2135081/does-my-application-contain-encryption

> Using HTTPS is now exempt from the ERN as of late September, 2016]

So if you don't add a dependency for cryptography yourself you should be safe.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2149](https://github.com/flutter/website/issues/2149) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dark-chocolate** [comment]
@zoechi  

> See also https://stackoverflow.com/questions/2135081/does-my-application-contain-encryption

Before filing this issue I did read this answer and couple of more and somewhere (I don't remember) I found that from 2017, you need to put `YES` for that option. So that's why I opened issue here on Flutter. 

Anyways, glad to hear you created this issue again. Thank you :)
