### ISSUE TITLE
[Feature request] [google_maps_flutter] : Support for custom tiles

### ISSUE THREAD

**Issue by PerrchicK** [flutter/flutter#25942]
Hi,
My native app versions (iOS & Android) are using the tile overlay feature.

Android:
https://developers.google.com/maps/documentation/android-sdk/tileoverlay#add
iOS:
https://developers.google.com/maps/documentation/ios-sdk/tiles#use_gmsurltilelayer_to_fetch_tiles_from_urls

It would be great to use it from the Flutter side as well, simply call these native APIs.

**In case it's not too hard to say**, I'd like to know what is your estimation for this kind of feature to be production-ready (or shall I ask about _google_maps_flutter 1.0.0_ first), because it influences my production release timeline (I'm considering to rewrite these two apps in Flutter only).

Thanks!

**Comment by zoechi** [comment]
Looks like #25161

**Comment by PerrchicK** [comment]
Hi @zoechi, thank you for the reference.
Yes, almost. It does **look** like it but in #25161 the developer (@WoodenPC) wants to use [Leaflet](https://leafletjs.com) as a third party while I wish to use the original GoogleMaps's support for my custom tiles.

Many thanks for the labelling.

**Comment by Hixie** [comment]
Update from @cyanglaz: This is on his radar as per the milestone.

**Comment by mtan11** [comment]
Is any example to add wmts from geoserver to google map?
