### ISSUE TITLE
How to remove the gap above and below the text on flutter

### ISSUE THREAD

**Issue by Atteprojects** [flutter/flutter#25949]
I am trying to put the text "Hello" right below the "123", but the bigger the text is, the bigger the gap. How do I remove the gap??? Flutter images are added below.
Column(
    children: <Widget>[
        Text('test', style: TextStyle(fontSize: 144.0),),
        Text('hello', style: TextStyle(fontSize: 36.0),),
    ]
)

![screenshot from 2018-12-29 19-56-40](https://user-images.githubusercontent.com/38020025/50577269-c5da6780-0dd9-11e9-99b3-c6d5ea3c4932.png)

**Comment by Atteprojects** [comment]
Thank you for the response. 
But I tried adjusting the height, but when the height is less than 1.0, it just cuts the top part of the text.

**Comment by filleduchaos** [comment]
That's not what it does in my experience:

<img width="426" alt="screen shot 2019-01-02 at 2 27 50 am" src="https://user-images.githubusercontent.com/29291843/50578164-0d8edc80-0e36-11e9-96b3-9b7f1f00a509.png" />

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  title: 'Flutter Demo',
  theme: ThemeData(primarySwatch: Colors.blue),
  home: Demo(),
));

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Text height demo'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('0', style: Theme.of(context).textTheme.display4.copyWith(
              height: 0,
            )),
            Text('hello'),
          ],
        ),
      ),
    );
  }
}
```

What version of Flutter are you on?

**Comment by Atteprojects** [comment]
Flutter 1.1.5-pre.27 • channel master • https://github.com/flutter/flutter.git

**Comment by Atteprojects** [comment]
I fixed it, thanks for the help

**Comment by timsneath** [comment]
Glad you got your issue fixed, @Atteprojects. As a general note, the best place for Flutter technical questions is StackOverflow. The Github issues log is for filing bugs or feature requests.

**Comment by Atteprojects** [comment]
one more thing, if you remove the Center widget, you will only be able to see the text "hello" because, height:0 makes the above text seem as if it is not there
