### ISSUE TITLE
firebase_ml_vision: faceDetector detects faces on Android but not iOS

### ISSUE THREAD

**Issue by xipengshen** [flutter/flutter#25945]
## Steps to Reproduce

1. The attached flutter face detection app uses faceDetector in firebase_vision_ml. It works well on Android, detecting faces well. But on iOS, it runs but does not detect any face.  
2. The app code is here: https://gist.github.com/xipengshen/9685ef7a2e86f4b7ad9ed4cf1161d156

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by xipengshen** [comment]
Output of "flutter doctor -v":
=================
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/xshen/Programs/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/xshen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Xiaoyan’s iPad • aa52b074f8e8e389af1adce472327cfeac459602 • ios • iOS 12.1.1
=================

**Comment by xipengshen** [comment]
Hi Zoechi, any update on this? Please let me know if you need anything else. Thanks.

**Comment by javawolfpack** [comment]
I'm having an inability to detect faces in a selfie photo taken vertically on Android with:

firebase_ml_vision version 0.2.1
flutter version 1.0.0

My flutter doctor -v output:

**Comment by javawolfpack** [comment]
Just noted my issue might be tied to this existing one: https://github.com/flutter/flutter/issues/19000

**Comment by p30arena** [comment]
Same happening to me on iOS Emulator 8

**Comment by kroikie** [comment]
@xipengshen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/524. Any further collaboration will be done there.
