### ISSUE TITLE
Multiple widgets using TabController causes all of them to change selection when one is changed

### ISSUE THREAD

**Issue by dogganidhal** [flutter/flutter#25947]
I created a customizable AppBar that has a TabBar on Android and a CupertinoSegmentedControl on iOS at the bottom, and synchronized it with a TabBarView to change the selection on swipe / select using a single TabController instance.

So I create multiple instances of the class described above with different number of tabs and different widgets to display, the problem is, whenever I change on the instance's selection, it changes for every instance, and sometimes crashes the app for an OutOfRange exception.

So I was wondering if I am doing something wrong, is this behaviour expected ? Any ideas to resolve it?

Here is a gist with the widget I am trying to build :

https://gist.github.com/dogganidhal/a2c75d90ae2a9570edd632cf2dcaa8bb

**Comment by zoechi** [comment]
Did you check https://stackoverflow.com/questions/53674092/preserve-widget-state-in-pageview-while-enabling-navigation/53702330#53702330

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
