### ISSUE TITLE
Android release build crashes with proguard error

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#25951]
This appears to be new as I have changed no code and was working 2 weeks ago... All i did was flutter upgrade.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
Flutter version:
```
[✓] Flutter (Channel master, v1.1.5-pre.38, on Mac OS X 10.13.6
    17G65, locale en-US)
    • Flutter version 1.1.5-pre.38 at /Users/anton/flutter
    • Framework revision b9f9e384cb (9 hours ago), 2019-01-01
      11:47:29 -0500
    • Engine revision b1a9a6e794
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 88e6fe0f67)
```

**Comment by zoechi** [comment]
Can you reproduce in `dev` channel?

**Comment by ezraaaa** [comment]
I'm having the same problem too. I've tried dev channel and it I'd returning the same thing

**Comment by abacaj** [comment]
Yes tried all channels available, same result.

**Comment by remosingh** [comment]
same issue....

**Comment by zoechi** [comment]
As far as I understand Proguard is currently not fully supported.
I'm closing this as duplicate of #11099

**Comment by xiaoxiaocainiao** [comment]
try this one:
`minifyEnabled false`

**Comment by fleetcor** [comment]
@xiaoxiaocainiao thanks man, it works!

**Comment by fleetcor** [comment]
@xiaoxiaocainiao ， thanks  man, it works!

**Comment by cfguimaraes** [comment]
@xiaoxiaocainiao that work for me too. Thank you.

In case some face this problem, the path to setting is `android/app/build.gradle`

**Comment by muammarridho** [comment]
@xiaoxiaocainiao it works, thanks bro.

**Comment by dheeraj2dj** [comment]
If you are not intending to change `minifyEnabled false`, this worked fine for me - https://github.com/flutter/flutter/issues/19250#issuecomment-469416592

**Comment by gitaaron** [comment]
Does this increase the size of the final binary?

**Comment by TobiCrackIT** [comment]
**minifyEnabled false** worked

**Comment by Nisthar** [comment]
> Does this increase the size of the final binary?

Yes. i wish there was a way to fix this with minify enabled.

**Comment by WBlackstorm** [comment]
minifyEnabled false
shrinkResources false

Solved to me.
