### ISSUE TITLE
Anyone knows how to create Flutter project both Application mode and Module mode ?

### ISSUE THREAD

**Issue by abigpig** [flutter/flutter#25954]
![image](https://user-images.githubusercontent.com/11513312/50579920-8b79d480-0e84-11e9-9c5a-92e88320fe61.png)

I want a flutter project  that both  have  (android & iOS) folder and  (.android & .iOS) folder.
Anyone  knows  how to create it ?

flutter create ...  or  other command ?

thx.

**Comment by timsneath** [comment]
Hi there! The best place for asking Flutter questions is [StackOverflow](https://stackoverflow.com/questions/tagged/flutter). The Github issues log is for filing bugs or feature requests.
