### ISSUE TITLE
How to locate flutter crash when flutter is integrated into an existing project

### ISSUE THREAD

**Issue by lihui2333** [flutter/flutter#25952]
Is there any way to locate the crash in dart code?

**Comment by kangwang1988** [comment]
Flutter includes two parts:
For engine crashes: 
```
refer https://github.com/flutter/flutter/wiki/Crashes
```
Just catch them, report to the server and analyze(symbolicate) as what's done in ios and android native before.

For dart part exceptions: pay attention to three ways:
```
1.  runZoned((){
    runApp(MyApp());
  },onError: (Object o, StackTrace s){
    print("OnError1:"+o.toString()+" "+s.toString());
  });
2.oid onErrorOccured(FlutterErrorDetails details){
  print("OnError2:"+details.toString());
}

void main(){
  FlutterError.onError=onErrorOccured;
3.Isolate.current.addErrorListener(new RawReceivePort((dynamic pair) async
```
Visit the documentation for these function for more.
Just catch them(exceptions only, won't crash), report it to the server with callstack info.

Closing this issue now.

**Comment by lihui2333** [comment]
@kangwang1988 thanks for your help.
