### ISSUE TITLE
how to use font from sdcard

### ISSUE THREAD

**Issue by wilin52** [flutter/flutter#25960]
I met a problem. Fonts download from server and store in sdcard. Is there any way to access and used  in TextStyle? 
Maybe it is the same issue as https://github.com/flutter/flutter/issues/25690.

Thanks for replying.

From URL: https://www.flutterchina.club/custom-fonts.md

**Comment by zoechi** [comment]
See https://github.com/flutter/flutter/issues/17910#issuecomment-431882437

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by wilin52** [comment]
> See [#17910 (comment)](https://github.com/flutter/flutter/issues/17910#issuecomment-431882437)
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Thanks. Just because I am a beginner😊。

If any body meets the same problem, don't know how to load assets from sdcard,  you can use 
' rootBundle.load(path) '
