### ISSUE TITLE
UIKitView Scroll error

### ISSUE THREAD

**Issue by larrymryan** [flutter/flutter#25962]
The error happens When I put any UIKitView in ListView or PageView and Scroll 

Everything is fine when using AndroidView on android.

```
[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
'package:flutter/src/gestures/converter.dart': Failed assertion: line 143 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:143:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _invoke1 (dart:ui/hooks.dart:173:13)
#7      _dispatchPointerDataPacket (dart:ui/hooks.dart:127:5)
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.5-pre.38, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)
```

**Comment by zoechi** [comment]
Can you please provide a minimal reproduction?

**Comment by zoechi** [comment]
Might be related to #24207

**Comment by larrymryan** [comment]
> Can you please provide a minimal reproduction?


Widget ios = UiKitView(
        viewType: "hugo.com/videoplayer",
        onPlatformViewCreated: onPlatformViewCreated,
//        hitTestBehavior: PlatformViewHitTestBehavior.transparent,
        gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          Factory<OneSequenceGestureRecognizer>(
              () => EagerGestureRecognizer()),
        ].toSet(),
        creationParams: <String, Object>{
          "url": widget.url,
          "options": widget.options,
          "auto": widget.auto
        },
        creationParamsCodec: const StandardMessageCodec(),
      )


Widget body = ListView.builder(
      itemCount: videoList.length,
      controller: _scrollController,
      itemBuilder: (context, index) {
        return theNativeView;
      },
    );

in ios

@implementation VideoController{
    UIView* _playerContainer;
    int64_t _viewId;
    FlutterMethodChannel* _channel;
    //NSObject<FlutterPluginRegistrar>* _registrar;
    bool _isLive;
    bool _isLoop;
    UIView * _testView;
}

- (instancetype)initWithFrame:(CGRect)frame viewIdentifier:(int64_t)viewId arguments:(id _Nullable)args binaryMessenger:(NSObject<FlutterBinaryMessenger>*)messenger{
    if ([super init]) {
        _viewId = viewId;
       
        _testView = [[UIView alloc] initWithFrame:frame];
        
    }
    return self;
}
-(UIView *)view{
    return _testView;
}


then when i scroll the listview  
the error happen

**Comment by zoechi** [comment]
We would need a minimal runnable reproduction
as a single file (or 2 files in this case) so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce,
or a minimal GitHub repo.

**Comment by zoechi** [comment]
Same error as #11672

**Comment by AlexFox63** [comment]
I have the same problem. Pls solve this error.

**Comment by AlexFox63** [comment]
```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/fokin/tools/flutter
    • Framework revision 1aafb3a8b9 (6 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/fokin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone Александр) (mobile)  • 00008030-001D095C3ED2402E            • ios         • iOS 14.2
    • iPhone 11 (mobile)          • 80773A4C-7A78-4B3F-A174-827ED1227B7C • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
```

**Comment by AlexFox63** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33263736/103002752-ebbe2100-4548-11eb-9d67-8a68fc917d35.gif)

I have an Ads on ios making by UiKitView and when I scrolling from UiKitView the all of app elements is unfocus and I cant do anything. Pls help.
