### ISSUE TITLE
UiKitView doesn't support being clipped

### ISSUE THREAD

**Issue by jiangyue2780** [flutter/flutter#25965]
Can't clip NativeView(UIKitView) on iOS，Android is ok.
BorderRadius not work with ClipRRect、Card and so on.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by amirh** [comment]
Clipping PlatformView layers is not yet implemented, lets keep this as the tracking issue.

**Comment by cyanglaz** [comment]
Clipping on iOS webview is landed on master. I am going to relentlessly close this issue. Please feel free to open another issue with details if any bug is discovered.
