### ISSUE TITLE
flutter build crashes on too many assets

### ISSUE THREAD

**Issue by TechieOldFox** [flutter/flutter#25967]
Flutter crashed 3 times on run.
[flutter_03.log](https://github.com/flutter/flutter/files/2720501/flutter_03.log)

**Comment by kangwang1988** [comment]
@TechieOldFox 
```
FileSystemException: FileSystemException: Cannot open file, path = 'C:\Data\download\android-studio\flutter_app\assets\offlineMap\16\51692\32546.png' (OS Error: The operation completed successfully.
, errno = 0)
```
That's why it crashes.
Besides, please paste the content of crashlog and output for "flutter doctor -v" next time.

**Comment by TechieOldFox** [comment]
I could open the file manually. Moreover the file is shown in Android Studio assets directory.

C:\Data\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at C:\Data\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

**Comment by kangwang1988** [comment]
Try run "flutter packages get" in your project directory. If it still exists,
Paste the pubspec.yaml and pubspec.lock here.

@TechieOldFox

**Comment by TechieOldFox** [comment]
Same issue.

name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  geolocator: ^2.1.1
  flutter_map: ^0.4.0
  flutter_geofire: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/offlineMap/10/806/
    - assets/offlineMap/10/807/
    - assets/offlineMap/10/808/
    - assets/offlineMap/11/1612/
    - assets/offlineMap/11/1613/
    - assets/offlineMap/11/1614/
    - assets/offlineMap/11/1615/
    - assets/offlineMap/11/1616/
    - assets/offlineMap/12/3225/
    - assets/offlineMap/12/3226/
    - assets/offlineMap/12/3227/
    - assets/offlineMap/12/3228/
    - assets/offlineMap/12/3229/
    - assets/offlineMap/12/3230/
    - assets/offlineMap/12/3231/
    - assets/offlineMap/12/3232/
    - assets/offlineMap/12/3233/
    - assets/offlineMap/13/6450/
    - assets/offlineMap/13/6451/
    - assets/offlineMap/13/6452/
    - assets/offlineMap/13/6453/
    - assets/offlineMap/13/6454/
    - assets/offlineMap/13/6455/
    - assets/offlineMap/13/6456/
    - assets/offlineMap/13/6457/
    - assets/offlineMap/13/6458/
    - assets/offlineMap/13/6459/
    - assets/offlineMap/13/6460/
    - assets/offlineMap/13/6461/
    - assets/offlineMap/13/6462/
    - assets/offlineMap/13/6463/
    - assets/offlineMap/13/6464/
    - assets/offlineMap/13/6465/
    - assets/offlineMap/13/6466/
    - assets/offlineMap/14/12900/
    - assets/offlineMap/14/12901/
    - assets/offlineMap/14/12902/
    - assets/offlineMap/14/12903/
    - assets/offlineMap/14/12904/
    - assets/offlineMap/14/12905/
    - assets/offlineMap/14/12906/
    - assets/offlineMap/14/12907/
    - assets/offlineMap/14/12908/
    - assets/offlineMap/14/12909/
    - assets/offlineMap/14/12910/
    - assets/offlineMap/14/12911/
    - assets/offlineMap/14/12912/
    - assets/offlineMap/14/12913/
    - assets/offlineMap/14/12914/
    - assets/offlineMap/14/12915/
    - assets/offlineMap/14/12916/
    - assets/offlineMap/14/12917/
    - assets/offlineMap/14/12918/
    - assets/offlineMap/14/12919/
    - assets/offlineMap/14/12920/
    - assets/offlineMap/14/12921/
    - assets/offlineMap/14/12922/
    - assets/offlineMap/14/12923/
    - assets/offlineMap/14/12924/
    - assets/offlineMap/14/12925/
    - assets/offlineMap/14/12926/
    - assets/offlineMap/14/12927/
    - assets/offlineMap/14/12928/
    - assets/offlineMap/14/12929/
    - assets/offlineMap/14/12930/
    - assets/offlineMap/14/12931/
    - assets/offlineMap/14/12932/
    - assets/offlineMap/15/25801/
    - assets/offlineMap/15/25802/
    - assets/offlineMap/15/25803/
    - assets/offlineMap/15/25804/
    - assets/offlineMap/15/25805/
    - assets/offlineMap/15/25806/
    - assets/offlineMap/15/25807/
    - assets/offlineMap/15/25808/
    - assets/offlineMap/15/25809/
    - assets/offlineMap/15/25810/
    - assets/offlineMap/15/25811/
    - assets/offlineMap/15/25812/
    - assets/offlineMap/15/25813/
    - assets/offlineMap/15/25814/
    - assets/offlineMap/15/25815/
    - assets/offlineMap/15/25816/
    - assets/offlineMap/15/25817/
    - assets/offlineMap/15/25818/
    - assets/offlineMap/15/25819/
    - assets/offlineMap/15/25820/
    - assets/offlineMap/15/25821/
    - assets/offlineMap/15/25822/
    - assets/offlineMap/15/25823/
    - assets/offlineMap/15/25824/
    - assets/offlineMap/15/25825/
    - assets/offlineMap/15/25826/
    - assets/offlineMap/15/25827/
    - assets/offlineMap/15/25828/
    - assets/offlineMap/15/25829/
    - assets/offlineMap/15/25830/
    - assets/offlineMap/15/25831/
    - assets/offlineMap/15/25832/
    - assets/offlineMap/15/25833/
    - assets/offlineMap/15/25834/
    - assets/offlineMap/15/25835/
    - assets/offlineMap/15/25836/
    - assets/offlineMap/15/25837/
    - assets/offlineMap/15/25838/
    - assets/offlineMap/15/25839/
    - assets/offlineMap/15/25840/
    - assets/offlineMap/15/25841/
    - assets/offlineMap/15/25842/
    - assets/offlineMap/15/25843/
    - assets/offlineMap/15/25844/
    - assets/offlineMap/15/25845/
    - assets/offlineMap/15/25846/
    - assets/offlineMap/15/25847/
    - assets/offlineMap/15/25848/
    - assets/offlineMap/15/25849/
    - assets/offlineMap/15/25850/
    - assets/offlineMap/15/25851/
    - assets/offlineMap/15/25852/
    - assets/offlineMap/15/25853/
    - assets/offlineMap/15/25854/
    - assets/offlineMap/15/25855/
    - assets/offlineMap/15/25856/
    - assets/offlineMap/15/25857/
    - assets/offlineMap/15/25858/
    - assets/offlineMap/15/25859/
    - assets/offlineMap/15/25860/
    - assets/offlineMap/15/25861/
    - assets/offlineMap/15/25862/
    - assets/offlineMap/15/25863/
    - assets/offlineMap/15/25864/
    - assets/offlineMap/15/25865/
    - assets/offlineMap/16/51602/
    - assets/offlineMap/16/51603/
    - assets/offlineMap/16/51604/
    - assets/offlineMap/16/51605/
    - assets/offlineMap/16/51606/
    - assets/offlineMap/16/51607/
    - assets/offlineMap/16/51608/
    - assets/offlineMap/16/51609/
    - assets/offlineMap/16/51610/
    - assets/offlineMap/16/51621/
    - assets/offlineMap/16/51622/
    - assets/offlineMap/16/51623/
    - assets/offlineMap/16/51624/
    - assets/offlineMap/16/51625/
    - assets/offlineMap/16/51626/
    - assets/offlineMap/16/51627/
    - assets/offlineMap/16/51628/
    - assets/offlineMap/16/51629/
    - assets/offlineMap/16/51630/
    - assets/offlineMap/16/51631/
    - assets/offlineMap/16/51632/
    - assets/offlineMap/16/51633/
    - assets/offlineMap/16/51634/
    - assets/offlineMap/16/51635/
    - assets/offlineMap/16/51636/
    - assets/offlineMap/16/51637/
    - assets/offlineMap/16/51638/
    - assets/offlineMap/16/51639/
    - assets/offlineMap/16/51640/
    - assets/offlineMap/16/51641/
    - assets/offlineMap/16/51642/
    - assets/offlineMap/16/51643/
    - assets/offlineMap/16/51644/
    - assets/offlineMap/16/51645/
    - assets/offlineMap/16/51646/
    - assets/offlineMap/16/51647/
    - assets/offlineMap/16/51648/
    - assets/offlineMap/16/51649/
    - assets/offlineMap/16/51650/
    - assets/offlineMap/16/51651/
    - assets/offlineMap/16/51652/
    - assets/offlineMap/16/51653/
    - assets/offlineMap/16/51654/
    - assets/offlineMap/16/51655/
    - assets/offlineMap/16/51656/
    - assets/offlineMap/16/51657/
    - assets/offlineMap/16/51658/
    - assets/offlineMap/16/51659/
    - assets/offlineMap/16/51660/
    - assets/offlineMap/16/51661/
    - assets/offlineMap/16/51662/
    - assets/offlineMap/16/51663/
    - assets/offlineMap/16/51664/
    - assets/offlineMap/16/51665/
    - assets/offlineMap/16/51666/
    - assets/offlineMap/16/51667/
    - assets/offlineMap/16/51668/
    - assets/offlineMap/16/51669/
    - assets/offlineMap/16/51670/
    - assets/offlineMap/16/51671/
    - assets/offlineMap/16/51672/
    - assets/offlineMap/16/51673/
    - assets/offlineMap/16/51674/
    - assets/offlineMap/16/51675/
    - assets/offlineMap/16/51676/
    - assets/offlineMap/16/51677/
    - assets/offlineMap/16/51678/
    - assets/offlineMap/16/51679/
    - assets/offlineMap/16/51680/
    - assets/offlineMap/16/51681/
    - assets/offlineMap/16/51681/
    - assets/offlineMap/16/51683/
    - assets/offlineMap/16/51684/
    - assets/offlineMap/16/51685/
    - assets/offlineMap/16/51686/
    - assets/offlineMap/16/51687/
    - assets/offlineMap/16/51688/
    - assets/offlineMap/16/51689/
    - assets/offlineMap/16/51690/
    - assets/offlineMap/16/51691/
    - assets/offlineMap/16/51692/
    - assets/offlineMap/16/51693/
    - assets/offlineMap/16/51694/
    - assets/offlineMap/16/51695/
    - assets/offlineMap/16/51696/
    - assets/offlineMap/16/51697/
    - assets/offlineMap/16/51698/
    - assets/offlineMap/16/51699/
    - assets/offlineMap/16/51700/
    - assets/offlineMap/16/51701/
    - assets/offlineMap/16/51702/
    - assets/offlineMap/16/51703/
    - assets/offlineMap/16/51704/
    - assets/offlineMap/16/51705/
    - assets/offlineMap/16/51706/
    - assets/offlineMap/16/51707/
    - assets/offlineMap/16/51708/
    - assets/offlineMap/16/51709/
    - assets/offlineMap/16/51710/
    - assets/offlineMap/16/51711/
    - assets/offlineMap/16/51712/
    - assets/offlineMap/16/51713/
    - assets/offlineMap/16/51714/
    - assets/offlineMap/16/51715/
    - assets/offlineMap/16/51716/
    - assets/offlineMap/16/51717/
    - assets/offlineMap/16/51718/
    - assets/offlineMap/16/51719/
    - assets/offlineMap/16/51720/
    - assets/offlineMap/16/51721/
    - assets/offlineMap/16/51722/
    - assets/offlineMap/16/51723/
    - assets/offlineMap/16/51724/
    - assets/offlineMap/16/51725/
    - assets/offlineMap/16/51726/
    - assets/offlineMap/16/51727/
    - assets/offlineMap/16/51728/
    - assets/offlineMap/16/51729/
    - assets/offlineMap/16/51730/


# Generated by pub
# See https://www.dartlang.org/tools/pub/glossary#lockfile
packages:
  ansicolor:
    dependency: transitive
    description:
      name: ansicolor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.11"
  console_log_handler:
    dependency: transitive
    description:
      name: console_log_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_geofire:
    dependency: "direct main"
    description:
      name: flutter_geofire
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  flutter_image:
    dependency: transitive
    description:
      name: flutter_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  flutter_map:
    dependency: "direct main"
    description:
      name: flutter_map
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  google_api_availability:
    dependency: transitive
    description:
      name: google_api_availability
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.7"
  latlong:
    dependency: transitive
    description:
      name: latlong
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+2"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.3+1"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.2"
  permission_handler:
    dependency: transitive
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  positioned_tap_detector:
    dependency: transitive
    description:
      name: positioned_tap_detector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.8"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1"
  transparent_image:
    dependency: transitive
    description:
      name: transparent_image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  tuple:
    dependency: transitive
    description:
      name: tuple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  validate:
    dependency: transitive
    description:
      name: validate
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
sdks:
  dart: ">=2.0.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

**Comment by zoechi** [comment]
Does the file `assets\offlineMap\16\51692\32546.png` actually exist?

**Comment by TechieOldFox** [comment]
@zoechi I only define directory so the file must exists. Physically I did check that the file exists and readable.

**Comment by zoechi** [comment]
I see. 
Could be the equivalent Windows issue to this MacOS issue https://github.com/flutter/flutter/issues/20316
(https://stackoverflow.com/questions/870173/is-there-a-limit-on-number-of-open-files-in-windows)

**Comment by jonahwilliams** [comment]
I believe this is fixed in the latest dev. If you're able to switch and still have this issue please let me know
