### ISSUE TITLE
CameraPreview freezes during startVideoRecording on iOS

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#25961]
The `CameraPreview` view freezes momentarily while calling `CameraController.startVideoRecording()` on iOS devices.

This is caused by:
1. The calls to `stopRunning()` / `startRunning()` in `startVideoRecording()` (these seem unnecessary?).
2. and the call to `setUpCaptureSessionForAudio()`.

Both of these must be commented before the CameraPreview view will cease freezing for ~1 second.

**Comment by zoechi** [comment]
Looks similar or at least related to #25959

**Comment by cvolzke4** [comment]
I created this issue separately to #25959 as they will both need to be fixed in different ways.

For this problem, I would recommend:
a) Stop calling stopRunning / startRunning from within startVideoRecording, unless we need that
b) and create a new operation 'prepare:forVideoRecording' that does the heavy listing to prepare the audio for video/audio recording so it can be done early, or when the user say toggles a 'Video Recording' mode in their app.

**Comment by cvolzke4** [comment]
To reproduce, run the demo on an iOS device and press the videocam icon: https://pub.dartlang.org/packages/camera#-example-tab-

**Comment by cvolzke4** [comment]
[✓] Flutter (Channel beta, v0.11.9, on Mac OS X 10.13.6 17G3025, locale en-US)
• Flutter version 0.11.9 at /Users/cvolzke/development/flutter
• Framework revision d48e6e4 (6 weeks ago), 2018-11-20 22:05:23 -0500
• Engine revision 5c81474
• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
• Android SDK at /Users/cvolzke/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.0, Build version 10A255
• ios-deploy 1.9.4
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 31.3.1
• Dart plugin version 181.5656
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
• Guy Ronen’s iPhone • 7ddc980a43e74699578777e6435afcee2dd2d717 • ios • iOS 11.4.1

**Comment by cvolzke4** [comment]
I've added a pull request here: https://github.com/flutter/plugins/pull/1023

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue as the PR was merged already on March 13. Please comment if you encounter it again.
