### ISSUE TITLE
test internet Connectivity

### ISSUE THREAD

**Issue by mohamedHassanKa** [flutter/flutter#25968]
Basically i want to show a dialog about the internet connectivity when i launch the application but the dialog needs a context and if i want to show dialog in initstate  before MaterialApp  i dont have any context is there any turn around or solution for this

**Comment by mohamedHassanKa** [comment]
this is my flutter doctor -v

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [version 10.0.17134.472], locale fr-FR)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\mohamed-hassan.kadri\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\mohamed-hassan.kadri\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.4
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by kangwang1988** [comment]
Please consider asking support questions in one of the other channels listed at: http://flutter.io/support
