### ISSUE TITLE
Flutter Google Maps - maps-static

### ISSUE THREAD

**Issue by momoDragon** [flutter/flutter#25963]
Is there going to be a search function to search for addresses and then showing the location after the search? 
I totally think we need one right now because without it this plugin cant do much in my opinion

**Comment by hiddencaliber** [comment]
Hi @zoechi ,

Do you know if this google maps plugin is covering following features-

1. Geocoding and reverse Geocoding.
2. Google places search (auto complete/ type ahead)
3. Static maps with pins
4. Dynamic maps
 
Thanks in advance.

**Comment by zoechi** [comment]
@hiddencaliber I haven't used it but I assume 1. and 2. are not covered. There are APIs that you can use for that. See my links above. I don't even know what 3. and 4. means exactly.

**Comment by hiddencaliber** [comment]
@zoechi ,

Thanks for replying.

By 3 I mean - https://developers.google.com/maps/documentation/maps-static/intro **(I don't see this currently)**

and 4 is - https://developers.google.com/maps/documentation/javascript/adding-a-google-map **(This is available right now)**

**Comment by bhauj** [comment]
Is there any tentative deadline to have in this package?

**Comment by gonuit** [comment]
I know that this is an old issue, but for people who are still looking for google static maps in Flutter. I have created [google_static_maps_controller](https://pub.dev/packages/google_static_maps_controller) package that cover almost all google static maps functionality.

**Comment by darshankawar** [comment]
@momoDragon 
Can you try the [above](https://github.com/flutter/flutter/issues/25963#issuecomment-612543282) mentioned plugin and see if it answers your question ?

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
