### ISSUE TITLE
Consider additional sample rates for sensors

### ISSUE THREAD

**Issue by DrPaulT** [flutter/flutter#25971]
Looking at the sensors plugin it seems that the only available sensor sampling rate on Android devices is `SENSOR_DELAY_NORMAL` (https://github.com/flutter/plugins/blob/master/packages/sensors/android/src/main/java/io/flutter/plugins/sensors/SensorsPlugin.java, line 53).

Would it be possible to add a configuration option to the API so that we could sample more quickly?  In Java, I've been using `SENSOR_DELAY_GAME` with good results, seems to be around `50Hz` or even `100Hz` depending on the device.  I'm afraid I don't know how this all works on iOS, but I'd like to be able to sample at `50+Hz` on both platforms.

The application is motion tracking in sport, so ideally an option to use the fastest possible sample rate of the device would also be good.

Thanks.

**Comment by filleduchaos** [comment]
From what I remember of CoreMotion, you can set a sampling rate for sensors as well - it should be pretty straightforward to implement a Dart API that maps cleanly to both platforms.

**Comment by itsgk92** [comment]
+1

**Comment by thertzelle** [comment]
This would be great for my project as well. Is it on the immediate todo list?

**Comment by rostopira** [comment]
Trying to implement parallax effect, and current value makes it laggy as hell

**Comment by stuartmorgan** [comment]
Closing as `sensors` is deprecated in favor of [`sensors_plus`](https://pub.dev/packages/sensors_plus).
