### ISSUE TITLE
Horizontal Padding on CupertinoSegmentedControl

### ISSUE THREAD

**Issue by acahir** [flutter/flutter#25989]
The SegmentedControl has a hardcoded horizontal padding on line 16:

`const EdgeInsets _kHorizontalItemPadding = EdgeInsets.symmetric(horizontal: 16.0);`

While having a default value makes sense, is there any reason this is not customizable via a Padding as a param for that widget?

Unless there's another alternative that I'm missing.

**Comment by LongCatIsLooong** [comment]
@acahir  `_kHorizontalItemPadding` controls the padding around the entire segment control, not the padding around each segment, do you want to control the outer the padding around the entire segment control or the padding around each inner segment?

**Comment by vanlooverenkoen** [comment]
My PR includes outer padding. Because at this point it is set to 16 left and right. This should be configurable.

**Comment by vanlooverenkoen** [comment]
This should be fixed by pr #34555
