### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2598]
Our implementation of material design should support RTL.

**Comment by b-strauss** [comment]
How will this interact with code that has physical properties?

EdgeInsets for instance has left/right/top/bottom. Are there plans to refactor these into inlineStart/inlineEnd/blockStart/blockEnd (should probably be done sooner than later), or will left logically be right in RTL mode?

**Comment by Hixie** [comment]
That's one of the questions we will need to consider when we work on this.

**Comment by Hixie** [comment]
(We definitely won't make "left" mean "right" though.)

**Comment by Hixie** [comment]
I'm closing this as too general. Individual bugs have been filed and are tracked at https://github.com/flutter/flutter/projects/17.
