### ISSUE TITLE
Framework not found FlutterPluginRegistrant

### ISSUE THREAD

**Issue by wang542413041** [flutter/flutter#25997]
## Steps to Reproduce

1.change podfile
2.pod install
3.command + B

## Logs

```
ld: warning: directory not found for option '-F/Users/cpp/Library/Developer/Xcode/DerivedData/app-amulawjcjwafpbepvgjuwbrtqybh/Build/Products/Debug-iphoneos/FlutterPluginRegistrant'
ld: framework not found FlutterPluginRegistrant
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/cpp/Downloads/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cpp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)

**Comment by kangwang1988** [comment]
A minimal demo project would be helpful to help us reproduce this issue.
@wang542413041

**Comment by 2energycell** [comment]
found this issue in google search... it looks like new xcode build breaks this...

**Comment by vitor-gyant** [comment]
What was the fix for this ? I'm having the same issue after following https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

**Comment by deremakif** [comment]
@vitor-gyant You need to close the Xcode after the installation of Pods. And open your app.xcworkspace, not app.xcodeproj!
