### ISSUE TITLE
url_launcher deeplink opens Safari and not the app [iOS]

### ISSUE THREAD

**Issue by rgutner** [flutter/flutter#25991]
Hi all,

I'm working on an app that uses deeplinks navigating to another app if installed and if not it opens the browser. It works great on Android but not on iOS.
For example: https://hulu.com/shows/28927 on Android opens the Hulu app where on iOS always opens the browser. if I change the url to start with hulu:// it does open the app on iOS but to my best understanding this is an old format where the https:// should work on iOS as the new standard.

Any idea how to work around this issue?

Thanks,
Ronny

**Comment by wouterhardeman** [comment]
Does this happen with deeplinks of other applications? This is likely an issue with the Hulu app handling deeplinks with an URL scheme instead of a universal link.

The only way to work around this is using the Platform class to detect the current OS. Simple example:

```dart
if (Platform.isIOS) {
    launch('hulu://shows/28927');
} else {
    launch('https://hulu.com/shows/28927');
}
```

**Comment by jonahgreenthal** [comment]
This is also happening to me with Facebook, Twitter, and Instagram.

**Comment by cbracken** [comment]
Thanks for reporting!

/cc @cyanglaz to take a look.

**Comment by cyanglaz** [comment]
What is the IOS version of the phone that you were testing on? Universal link is only supported from IOS 9 and above.
I just tried twitter on my phone and it does open the app. 
I also tried Hulu and it does open the browser as you mentioned, so I would assume maybe Hulu did not handle universal links.

**Comment by jonahgreenthal** [comment]
iOS 12.1.3 (latest public beta)

**Comment by jonahgreenthal** [comment]
Using `forceSafariVC: false` makes it launch in app if available, at least on iOS. However, if the app is not installed, I would prefer the site launch in a webview. Is there a way to get both?

(I think this may nullify your request for my code; let me know if you still want it.)

**Comment by cyanglaz** [comment]
@jonahgreenthal Thank you for the feedback. And yes code is not required anymore. 
The workaround to do what you prefer would be manually checking the app is installed using the specific app scheme. And you would need to add the scheme to LSApplicationQueriesSchemes in the info.plist in your iOS app. Please find the code snippet for an example for Youtube.

```dart
if (await canLaunch('youtube://')) {
  await launch('https://www.youtube.com', forceSafariVC: false);
} else {
  await launch('https://www.youtube.com', forceSafariVC: true);
}
```

For adding scheme in you would need to find the info.plist file under your IOS package and add below snippet inside <dict>. Like below I have added youtube as one of the schemes.

```plist
<key>LSApplicationQueriesSchemes</key>
<array>
	<string>youtube</string>
</array>
```

**Comment by jonahgreenthal** [comment]
Thanks for the information and subsequent PR. It would be great to get the documentation improved.

**Comment by cyanglaz** [comment]
url_launcher is updated to version 4.1.0+1. We added the 'universalLinksOnly' setting to force url_launcher to only launch universal link if the other app is installed(only available on IOS); Besides, now the launch method returns a bool that indicates if the launch call is successful. You can utilize this to archive only launching universal links in app or fallback to safari without using the schemes, e.g. 
```dart
    if (await canLaunch('https://youtube.com')) {
      final bool nativeAppLaunchSucceeded = await launch(
        'https://youtube.com',
        forceSafariVC: false,
        universalLinksOnly: true,
      );
      if (!nativeAppLaunchSucceeded) {
        await launch(
          'https://youtube.com',
          forceSafariVC: true,
        );
      }
    }
```
Closing the issue now, please reopen with details if related issues are found.

**Comment by jonahgreenthal** [comment]
@cyanglaz Thanks, but when I do that (with a Facebook URL), `nativeAppLaunchSucceeded` ends up being null.

**Comment by cyanglaz** [comment]
The issue of returning a null has been fixed in https://github.com/flutter/plugins/pull/1124. Please update the url_launcher version to 4.2.0+2 and try again.
