### ISSUE TITLE
Backdrop filter is not blurring bottom pixels space on iPhone X and highter, Android is fine

### ISSUE THREAD

**Issue by Renesanse** [flutter/flutter#25990]
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.0.0 at /Users/daniel/crossplatform/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone XR • 0ED8A7F1-CE8A-4026-820D-1763AF319C68 • ios • iOS 12.1 (simulator)

if sigma more then 1 it looks like that: 
![2019-01-03 1 44 23](https://user-images.githubusercontent.com/42138594/50616953-d7b42b80-0efb-11e9-89c9-40c2317eb906.png)

But most be like : 
![2019-01-03 1 45 31](https://user-images.githubusercontent.com/42138594/50616954-dedb3980-0efb-11e9-96f8-3bab24c27c7f.png)

 Code:
`  build(context) {
    return Scaffold(
      body: Stack(
        children: [
          getTabBarViews([
            HotNewsScreen(),
            SearchNewsScreen(),
            HotNewsScreen(),
            HotNewsScreen()
          ]),
          Container(
            child: BackdropFilter(
                filter: ImageFilter.blur(sigmaY: 8.0, sigmaX: 8.0),
                child: getTabBar()),
            alignment: AlignmentDirectional.bottomEnd,
          )
        ]
      ),
    );
  }`

**Comment by Renesanse** [comment]
>   build(context) {
    return Scaffold(
      body: Stack(
        children: [
          getTabBarViews([
            HotNewsScreen(),
            SearchNewsScreen(),
            HotNewsScreen(),
            HotNewsScreen()
          ]),
          Container(
            child: BackdropFilter(
                filter: ImageFilter.blur(sigmaY: 8.0, sigmaX: 8.0),
                child: getTabBar()),
            alignment: AlignmentDirectional.bottomEnd,
          )
        ]
      ),
    );
  }

**Comment by Renesanse** [comment]
> This should only be a problem on the software rendered simulators. Can you confirm that it works right on a physical device?
> 
> cc @liyuqian

I have not a physical iPhone X, I am sorry.

**Comment by liyuqian** [comment]
Duplicate of https://github.com/flutter/flutter/issues/24946
