### ISSUE TITLE
Push notification support in widgets

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#260]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Wednesday Nov 04, 2015 at 19:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1945_

----

Push notifications is a popular feature of mobile platforms. This is a tracking issue to provide an example (and any necessary low-level features) to support this feature.

**Comment by HansMuller** [comment]
Creating Material compliant notification widgets is probably worth some explicit support.

http://www.google.com/design/spec/patterns/notifications.html

**Comment by abarth** [comment]
Probably a dup of #201

**Comment by sethladd** [comment]
Yup, a dupe. Thanks for the catch!
