### ISSUE TITLE
[firebase_messaging] FCM custom sound on Android API level >= 26 it seems it doesn't work

### ISSUE THREAD

**Issue by shadowsheep1** [flutter/flutter#26005]
Answering this [SO question](https://stackoverflow.com/questions/54002617/custom-sound-push-notification-does-not-work-flutter/54003722?noredirect=1#comment94867571_54003722) it came out that on devices running Android API level >= 26 push notification custom sounds it doesn't work, but the default sound it's played. All works fine on devices running Android API level < 26.

This the notification payload used during testing:

```json
{
 "to" : "my_device_token",
 "collapse_key" : "type_a",
 "priority" : "high",
 "notification" : {
     "body" : "Test Notification body for custom sound {{datestamp}}",
     "title": "Custom sound alert.mp3",
     "sound": "alert.mp3"
 }
}
```

This my `flutter doctor -v `

```
$ flutter doctor -v

[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-IT)
    • Flutter version 1.0.0 at /Users/shadowsheep/flutter/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/shadowsheep/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    [...]

• No issues found!
```

Had we missed something?

**Comment by josancamon19** [comment]
Is this solved, or there is a way where we can set a different sound in these API levels?

**Comment by uj** [comment]
You have to use Notification Channels on Api >= 26, you cannot specify a file in the payload.

**Comment by fpsColton** [comment]
This is related https://github.com/flutter/flutter/issues/16022

In the mean time, you can use https://pub.dartlang.org/packages/flutter_local_notifications to create a notification channel, but it will need to send one local notification as part of the setup.

**Comment by pacifire** [comment]
> This is related #16022
> 
> In the mean time, you can use https://pub.dartlang.org/packages/flutter_local_notifications to create a notification channel, but it will need to send one local notification as part of the setup.

@fpsColton : Does this work, in case app is in Background ?
Bcoz in Flutter we cannot control Notifications, when app is in background.

**Comment by OptivolveThiyraashDavid** [comment]
Still no work around?

**Comment by RaashVision** [comment]
I have found temporary workaround. The issue is because of notification channel after API>=26. I check the official Android notification channel page https://developer.android.com/training/notify-user/channels
, they mention that,

"When you target Android 8.0 (API level 26), you must implement one or more notification channels. If your targetSdkVersion is set to 25 or lower, when your app runs on Android 8.0 (API level 26) or higher, it behaves the same as it would on devices running Android 7.1 (API level 25) or lower."

So just go to your android/build.gradle , change the targetSdkversion to 25. Then clean the solution then rebuild it. Your custom sound for your notification will works now. The problem with FCM Custom sound after API> 26 is still exist so let this issue open. I really need to make this custom sound works that's why I come out with this hacky solution. Might be not a good solution but it solved the problem. Hope it helpful for you too.

**Comment by kroikie** [comment]
@shadowsheep1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/523. Any further collaboration will be done there.

**Comment by cargallo** [comment]
> I have found temporary workaround. The issue is because of notification channel after API>=26. I check the official Android notification channel page https://developer.android.com/training/notify-user/channels
> , they mention that,
> 
> "When you target Android 8.0 (API level 26), you must implement one or more notification channels. If your targetSdkVersion is set to 25 or lower, when your app runs on Android 8.0 (API level 26) or higher, it behaves the same as it would on devices running Android 7.1 (API level 25) or lower."
> 
> So just go to your android/build.gradle , change the targetSdkversion to 25. Then clean the solution then rebuild it. Your custom sound for your notification will works now. The problem with FCM Custom sound after API> 26 is still exist so let this issue open. I really need to make this custom sound works that's why I come out with this hacky solution. Might be not a good solution but it solved the problem. Hope it helpful for you too.

Nowdays Google forces to target API >= 28 in play store

![image](https://user-images.githubusercontent.com/13320290/72014632-023b7180-323f-11ea-9185-1e9b96bf2331.png)

https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by aldwnesx** [comment]
Does anyone have a solution?

@cargallo @kroikie @RaashVision

**Comment by geeraj** [comment]
you can try with below setup.. 

'CHANNEL_ID 1', 'CHANNEL_NAME 1', 'CHANNEL_DESCRIPTION 1',
        sound:RawResourceAndroidNotificationSound('test'),
        importance: Importance.Max,
        playSound: true,
        enableLights: true,

**Comment by geeraj** [comment]
test.mp3 should be added into res/raw folder under android folder

**Comment by saravananmnm** [comment]
create raw folder,
under raw folder below to be added

`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:notification="@drawable/*,@raw/new_auction_notification" />`

**Comment by saravananmnm** [comment]
2nd code is your notification view

**Comment by evripidesk** [comment]
hello any fix for this issue?

**Comment by cargallo** [comment]
> hello any fix for this issue?

It won't be a fix. Read my previous comment, Nowdays Google forces to target API >= 28 in play store

**Comment by evripidesk** [comment]
> > hello any fix for this issue?
> 
> It won't be a fix. Read my previous comment, Nowdays Google forces to target API >= 28 in play store

so we have to downgrade the targetSdkVersion?

**Comment by cargallo** [comment]
See this support article: https://support.google.com/googleplay/android-developer/answer/113469#targetsdk

It says "Once these requirements come into effect, the Play Console will prevent you from submitting new APKs using older target API levels."

So your app will not be removed from Play. You can leave your existing app version on Play with a targetSdkVersion of 27 without any worry.

However any future update to your app will need to have a targetSdkVersion of 28 or higher. You would not be able to upload a new APK that targets API level 27.

So, no you cant downgrade the targetSdkVersion.

**Comment by Bharavi26** [comment]
notification cusom sound not playing when app is in background, anyone have idea about it ?
show notification in **myBackgroundMessageHandler** with sound:RawResourceAndroidNotificationSound('ringtone') in AndroidNotificationDetails
