### ISSUE TITLE
dart-sdk-darwin-x64.zip

### ISSUE THREAD

**Issue by ygqwan** [flutter/flutter#26016]
flutter docker
Downloading Dart SDK from Flutter engine 7375a0f414bde4bc941e623482221db2fc8c4ab5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11692    0 11692    0     0  14120      0 --:--:-- --:--:-- --:--:-- 14120
[/Users/dragon/project/flutter/flutter/bin/cache/dart-sdk-darwin-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/dragon/project/flutter/flutter/bin/cache/dart-sdk-darwin-x64.zip or
        /Users/dragon/project/flutter/flutter/bin/cache/dart-sdk-darwin-x64.zip.zip, and cannot find /Users/dragon/project/flutter/flutter/bin/cache/dart-sdk-darwin-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try the operation again later.
If this problem persists, please report the problem at
https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by kangwang1988** [comment]
@ygqwan 
Please paste the original and full log result from `flutter -v doctor -v` so we may diagnose it better.

**Comment by ygqwan** [comment]
make sure env  PUB_HOSTED_URL、  FLUTTER_STORAGE_BASE_URL could use.

**Comment by glm-mawla** [comment]
> make sure env PUB_HOSTED_URL、 FLUTTER_STORAGE_BASE_URL could use.

export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
