### ISSUE TITLE
RawKeyboardListener doesn't receive any events from keyboard in ios simulator

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2601]
Maybe by design?  Is there anyway it can work?

**Comment by abarth** [comment]
It's just not implemented yet.  /cc @chinmaygarde @tvolkert

**Comment by chinmaygarde** [comment]
Didn't know there was another way to access the keyboard other than the keyboard service impl. Will hook this up as well.

**Comment by chinmaygarde** [comment]
Postponing this till after https://github.com/flutter/flutter/issues/2887

**Comment by abarth** [comment]
I'm not sure iOS has key events.  @chinmaygarde do you know where to get these events in UIKit?

**Comment by Hixie** [comment]
This presumably also applies to bluetooth keyboards, et al?

cc @cbracken who has worked on iOS text input.

**Comment by AppleEducate** [comment]
2 things about the keyboard on iOS in Flutter.

1. Keyboards do not respond to trackpad mode on the iPhone with 3D touch and iPad with 2 finger swipe. Cursor should move all around the text.

2. I have not found a way yet in flutter to implement keyboard carasoul (like picking a date or time by scrolling in the list in the keyboard)

Both of these are pretty well used on iOS as native functionality.

**Comment by goderbauer** [comment]
@AppleEducate If you haven't already you should file separate issues for those two concerns.

/cc @gspencergoog FYI for your keyboard work.

**Comment by gaaclarke** [comment]
I checked with @gspencergoog and this appears to be a duplicate of https://github.com/flutter/flutter/issues/31945
