### ISSUE TITLE
Flutter Doctor should report more fine-grained analytics

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#26029]
It occurred to me that we might be able to better optimize for some common setup pitfalls with a bit more analytics data from `flutter doctor`. As I understand it, right now the only thing it reports is that the command was run.  It should be straightforward to report very generic/non-personally-identifiable information about which classes of failures a given `fluter doctor` run hits.

This could tell us things such as:
- What % of Flutter users complete setup of iOS vs. Android.
- Total time from first run of Flutter doctor to zero errors (or a stable set of errors)
- Frequency of certain (possibly) common error conditions such as lacking 32-bit libraries on linux, or lacking brew on Mac, etc.
- Set of / # of outstanding issues on any given platform (windows, linux, mac), etc.
- Frequency of triggering of certain classes of doctor issue detectors.

Unclear if this is of use, just struck me the other day as a possible easy/safe/user-helpful thing to gather.

@InMatrix @mit-mit feel free to close if this does not strike you as immediately useful.

**Comment by mit-mit** [comment]
I really like the general idea. One complexity to run though is that a single particular user is likely to have many 'issues' early in the installation process, and then fewer as they work through the dependencies. Thus, we can't just reason about the fraction of failures from all sessions to determine how issue-free installations generally are.

**Comment by tvolkert** [comment]
This is done now, correct?

**Comment by blasten** [comment]
Yep!
