### ISSUE TITLE
iOS crash 

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#26028]
Hello, Team Flutter!.
I have a task to hide content in a trey, I chose a radical method, I do the following
```swift
override func applicationWillResignActive(_ application: UIApplication) {
        self.window.isHidden = true
    }
    
    override func applicationDidBecomeActive(_ application: UIApplication) {
        self.window.isHidden = false
    }
```

this code work, but if the textFormField is on the screen or appears, the application crashes, if tap on textFormField(keyboardShow) =>

```
019-01-03 23:01:14.433808+0300 Runner[30531:8999397] *** Assertion failure in -[FlutterTextInputPlugin showTextInput], ../../flutter/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm:703
2019-01-03 23:01:14.556435+0300 Runner[30531:8999397] 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The application must have a key window since the keyboard client must be part of the responder chain to function'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d16b1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010c709735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d16af42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010c10c877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Flutter                             0x000000010a924dec -[FlutterTextInputPlugin showTextInput] + 298
	5   Flutter                             0x000000010a924bda -[FlutterTextInputPlugin handleMethodCall:result:] + 149
	6   Flutter                             0x000000010a9137fa __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	7   Flutter                             0x000000010a92fdc8 _ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
	8   Flutter                             0x000000010a9337b8 _ZN5shell15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 38
	9   Flutter                             0x000000010a983d7d _ZNSt3__110__function6__funcIZN5shell5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEEE4$_26NS_9allocatorIS9_EEFvvEEclEv + 57
	10  Flutter                             0x000000010a93f13e _ZN3fml15MessageLoopImpl15RunExpiredTasksEv + 522
	11  Flutter                             0x000000010a9424bc _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	12  CoreFoundation                      0x000000010d0d0f34 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	13  CoreFoundation                      0x000000010d0d0b32 __CFRunLoopDoTimer + 1026
	14  CoreFoundation                      0x000000010d0d039a __CFRunLoopDoTimers + 266
	15  CoreFoundation                      0x000000010d0caa1c __CFRunLoopRun + 2252
	16  CoreFoundation                      0x000000010d0c9e11 CFRunLoopRunSpecific + 625
	17  GraphicsServices                    0x000000011196d1dd GSEventRunModal + 62
	18  UIKitCore                           0x0000000116c5b81d UIApplicationMain + 140
	19  Runner                              0x000000010a613314 main + 68
	20  libdyld.dylib                       0x0000000110bd9575 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

flutter doctor -v 

```
[✓] Flutter (Channel master, v1.1.6-pre.11, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.1.6-pre.11 at /Users/alexfix/Flutter/flutter
    • Framework revision 53727866e6 (15 hours ago), 2019-01-03 12:05:53 +0700
    • Engine revision 844c3274e6
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 88e6fe0f67)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexfix/Library/Android/sdk
    • Android NDK at /Users/alexfix/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment]
Are you adding Flutter to an existing project?

**Comment by 1AlexFix1** [comment]
> Are you adding Flutter to an existing iOS project?

No, this is a new project created with plugin 'flutter' in Android Studio with Swift / Kotlin support.

**Comment by kangwang1988** [comment]
Can you create a minimal sample project which can reproduce this problem?
@1AlexFix1

**Comment by 1AlexFix1** [comment]
> Can you create a minimal sample project which can reproduce this problem?
> @1AlexFix1

it is reproduced quite easily. Create a new project with this code.

### main.dart
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(),
        ),
      ),
    );
  }
}
```

### AppDelegate.swift

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  override func applicationWillResignActive(_ application: UIApplication) {
          self.window.isHidden = true
      }

      override func applicationDidBecomeActive(_ application: UIApplication) {
          self.window.isHidden = false
      }

}
```

1. run app
2. go in tray (app status = paused)
3. return app
4. tap on textFormField => app crash

**Comment by kangwang1988** [comment]
Fail to reproduce this issue:
![image](https://user-images.githubusercontent.com/817851/50691701-7790c700-106c-11e9-84a5-018deeddf816.png)

[✓] Flutter (Channel master, v1.1.6-pre.25, on Mac OS X 10.14.3 18D32a, locale
    en-CN)
    • Flutter version 1.1.6-pre.25 at
      /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision caf6027d81 (3 hours ago), 2019-01-04 05:38:28 -0500
    • Engine revision 83239e141b
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

@1AlexFix1

**Comment by 1AlexFix1** [comment]
I reinstalled the sdk flutter, took the project from the flutter folder / example /hello word added code to the object with
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (void)applicationWillResignActive:(UIApplication *)application {
    self.window.hidden = YES;
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
    self.window.hidden = NO;
}

@end
```

main.dart change to 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
	@override
	Widget build(BuildContext context) {
		return MaterialApp(
			home: Scaffold(
				body: Center(
					child: TextFormField(),
				),
			),
		);
	}
```

the effect is the same, the application falls

**Comment by kangwang1988** [comment]
@1AlexFix1 
Reproduced, thanks, I'll have a look at it soon.

**Comment by kangwang1988** [comment]
@1AlexFix1 
It's your custom code causing the crash.
```
- (void)applicationWillResignActive:(UIApplication *)application{
    [self.window resignKeyWindow];
    self.window.hidden = true;
}

- (void)applicationDidBecomeActive:(UIApplication *)application{
    [self.window makeKeyAndVisible];
    self.window.hidden = false;
}
```
This works fine.
Closing the issue.

**Comment by 1AlexFix1** [comment]
> @1AlexFix1
> It's your custom code causing the crash.
> 
> ```
> - (void)applicationWillResignActive:(UIApplication *)application{
>     [self.window resignKeyWindow];
>     self.window.hidden = true;
> }
> 
> - (void)applicationDidBecomeActive:(UIApplication *)application{
>     [self.window makeKeyAndVisible];
>     self.window.hidden = false;
> }
> ```
> This works fine.
> Closing the issue.

thanks

**Comment by MarkStepp** [comment]
Mine is doing the same thing with this code (swift) is there something I need to change - I was given this code by another user which knows swift...

`
override func applicationWillResignActive(_ application: UIApplication) {
        self.window.isHidden = true
  }
  override func applicationDidBecomeActive(_ application: UIApplication) {
        self.window.isHidden = false
  }

`

**Comment by MOOUDE** [comment]
+1 had the same issue after updating flutter version

**Comment by digibum** [comment]
@kangwang1988  can you please provide reason why @1AlexFix1 code is not working? I have same issu using swift. Thank you!

**Comment by kangwang1988** [comment]
@digibum 
As this issue is too old, I would recommend you to file a new issue, including a reproducible demo.
Thx

**Comment by Zeynal7** [comment]
To fix this issue, use         
`self.window.endEditing(true) ` before hiding the window. This way keyboard will close before text field gets hidden, and there won't be any crash.
