### ISSUE TITLE
Duplicate menu icon in the Scaffold

### ISSUE THREAD

**Issue by minh98** [flutter/flutter#26025]
I use AppBar () for appbar in scaffold and SliverAppBar for body, and I use in-scaffold drawer,
As a result, I get two identical menu icons and both have similar features.
I couldn't find a way to hide the menu icon in SliverAppBar
![screenshot_1546543354](https://user-images.githubusercontent.com/26597466/50657389-eae0fd00-0fc8-11e9-9499-4f7b869ab405.png)
![screenshot_1546543929](https://user-images.githubusercontent.com/26597466/50657401-f59b9200-0fc8-11e9-9adc-48185fb8983b.png)

**Comment by minh98** [comment]
i want to hide icon menu in SliverAppBar but seem has no option to hide it

**Comment by jonahwilliams** [comment]
I believe you want to set `automaticallyImplyLeading: false` in the SliverAppBar

**Comment by minh98** [comment]
> I believe you want to set `automaticallyImplyLeading: false` in the SliverAppBar

it worked. thank you ^_^
