### ISSUE TITLE
create new project flutter packages get cupertino_icons is very very slow

### ISSUE THREAD

**Issue by mrerhuo** [flutter/flutter#26038]
![image](https://user-images.githubusercontent.com/9547741/50665259-e75e6d80-0fea-11e9-8a03-0210a34196ee.png)
this is spend time，I have used vpn

**Comment by zoechi** [comment]
Are you in China?
This looks like a network problem.

**Comment by kangwang1988** [comment]
@mrerhuo 
Network issue.
If you're in China, refer : https://flutter.io/community/china.
