### ISSUE TITLE
Shrine Demo on iOS: Copy/Paste overlay doesn't show text

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#26032]
![img_0005](https://user-images.githubusercontent.com/1227763/50663878-02d06680-0f60-11e9-9402-681d98caf9ae.PNG)

**Comment by willlarche** [comment]
it's there. You just can't read it. The theming is making it dark.

**Comment by jonahwilliams** [comment]
It seems like the button theme is changing the text selection handles, maybe it should use a separate theme?

**Comment by rami-a** [comment]
This appears to be resolved and no longer reproducible.
