### ISSUE TITLE
Shrine app's search button should probably not open the log-in screen again

### ISSUE THREAD

**Issue by xster** [flutter/flutter#26035]
It's a bit more confusing because after going through the page sequence of
gallery home->vignette category->shrine login page->shrine main page->shrine login page (via the search button) and then pressing the back button, we're all the way back to the gallery vignette category page.

**Comment by xster** [comment]
cc @willlarche

**Comment by willlarche** [comment]
This was a hold over from the codelab where we wanted them to have some way to return to the login page. Def not needed as a study in the gallery.

**Comment by willlarche** [comment]
Let's make it just print to console "Search button  did touch"

**Comment by rami-a** [comment]
A problem with making this change would mean there isn't a way to leave the Shrine demo to go back to the gallery.

**Comment by Hixie** [comment]
This is specific to the old gallery, so closing. We're not going to fix bugs in the old gallery itself now that it's just a benchmarking target.
