### ISSUE TITLE
Provide a way to determine the Flutter version in Dart

### ISSUE THREAD

**Issue by xster** [flutter/flutter#26037]
Something in `import 'package:flutter/*'` should be able to give back the Flutter framework's current build version.

**Comment by chinmaygarde** [comment]
xref https://github.com/flutter/flutter/issues/26380 which is intends to expose the version on the engine and its major dependencies.

**Comment by Hixie** [comment]
What's the use case?

**Comment by xster** [comment]
For me, I was just trying to show it in the about page in apps like the gallery and realizing I can't unless I do it in tools rather than in the runtime.

**Comment by iskakaushik** [comment]
With https://github.com/flutter/engine/pull/7634, all that is remaining is the framework version.

**Comment by dodatw** [comment]
I have the same request.

**Comment by chinmaygarde** [comment]
This has come up multiple time before and there has [always been resistance](https://github.com/flutter/flutter/issues/26380#issuecomment-463005274) to exposing the version via an API. The engine has versioning information it uses for its persistent caches but a compelling use-case for applications to access this has never been detailed. From previous conversations, we are trying to avoid applications having to write version specific workarounds in Dart code. There were other concerns that @Hixie can perhaps elucidate. In the meantime, closing this as Wont-Fix.

**Comment by Hixie** [comment]
If anyone has a use case please don't hesitate to file a new bug describing what you would do with this information.
