### ISSUE TITLE
No ADB found but flutter doctor says all green checks. Android studio works fine.

### ISSUE THREAD

**Issue by TanzanianGem** [flutter/flutter#26046]

**Comment by TanzanianGem** [comment]
Android studio works fine with my note 8 bridging with USB. Flutter doctor is me all green check marks that everything is perfect. If I hook my note 8 up to download sample flutter app it shows up as no "ADB found"..

**Comment by kangwang1988** [comment]
@TanzanianGem 
Please paste full log for `flutter -v doctor -v` here.

**Comment by TanzanianGem** [comment]
First time user of GitHub..never had problems with Android studio. I'm pasting but please give some time to do it...and thanks for asking to look into it

**Comment by TanzanianGem** [comment]
F:\flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!

F:\flutter>

**Comment by TanzanianGem** [comment]
Launching lib\main.dart on SM J727P in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\mark\AndroidStudioProjects\flutter_app5\android\gradlew.bat" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip


Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\mark\AndroidStudioProjects\flutter_app5\android\gradlew.bat -v

**Comment by TanzanianGem** [comment]
I have gradle 4.10.2 already also

**Comment by kangwang1988** [comment]
In my macos:
`flutter -v doctor -v` outputs
```
KyleWongdeMacBook-Pro:flutter kylewong$ flutter -v doctor -v
[  +22 ms] executing: [/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/]
git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alf_master_fix_recursive_link_result_flutter_doctor_stuck
[        ] executing: [/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/]
git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alf_master_fix_recursive_link_result_flutter_doctor_stuck
[        ] executing: [/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/]
git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:alibaba-flutter/flutter.git
[        ] executing: [/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/]
git log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] ea57119ac3d9de06c05968be36d6ea12c2e2dacf
[        ] executing: [/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/]
git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 10 hours ago
[        ] executing: [/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/]
git describe --match v*.*.* --first-parent --long --tags
[  +29 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.1.5-12-gea57119ac
[+1207 ms] executing: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[  +70 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.2
[+1143 ms] executing: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[  +54 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.2
[  +81 ms] java -version
[+1188 ms] executing: idevice_id -h
[   +9 ms] executing: idevice_id -h
[  +10 ms] executing: ideviceinfo -u 00008020-001C2D903C42002E
[  +13 ms] executing: pod --version
[ +134 ms] [✓] Flutter (Channel alf_master_fix_recursive_link_result_flutter_doctor_stuck,
                        v1.1.6-pre.12, on Mac OS X 10.14.3 18D32a, locale en-CN)
[   +1 ms]     • Flutter version 1.1.6-pre.12 at
/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
[        ]     • Framework revision ea57119ac3 (10 hours ago), 2019-01-04 00:28:26 +0800
[        ]     • Engine revision 844c3274e6
[        ]     • Dart version 2.1.1 (build 2.1.1-dev.0.1 88e6fe0f67)
⣾[   +3 ms] executing: /Users/kylewong/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/kylewong/Library/Android/sdk/platform-tools/adb devices
-l
[        ] List of devices attached
[   +5 ms] executing: idevice_id -h
[  +68 ms] No device found with udid 00008020-001C2D903C42002E, is it plugged in?
[        ] executing: idevice_id -l
[   +5 ms] /usr/bin/xcrun simctl list --json devices
[ +276 ms] executing: /Users/kylewong/Library/Android/sdk/platform-tools/adb devices -l
⣽[  +11 ms] executing: /Users/kylewong/Library/Android/sdk/tools/bin/sdkmanager --licenses
[  +21 ms] executing: ideviceinstaller -h
⣻[  +13 ms] List of devices attached
[  +12 ms] executing: ios-deploy --version
[  +18 ms] executing: ios-deploy --version
[  +17 ms] 1.9.4
[   +1 ms] executing: ios-deploy --version
[  +16 ms] executing: ios-deploy --version
[  +13 ms] 1.9.4
⣽[ +608 ms] 1.2.0
[+5038 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[        ]     • Android SDK at /Users/kylewong/Library/Android/sdk
[        ]     • Android NDK at /Users/kylewong/Library/Android/sdk/ndk-bundle
[        ]     • Platform android-28, build-tools 28.0.3
[        ]     • Java binary at: /Applications/Android
                 Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ]     • All Android licenses accepted.
[        ] [!] iOS toolchain - develop for iOS devices (Xcode 10.1)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 10.1, Build version 10B61
[        ]     • ios-deploy 1.9.4
[        ]     ! CocoaPods out of date (1.5.0 is recommended).
[        ]         CocoaPods is used to retrieve the iOS platform side's plugin code that
responds to
                   your plugin usage on the Dart side.
[        ]         Without resolving iOS dependencies with CocoaPods, plugins will not work
on iOS.
[        ]         For more info, see https://flutter.io/platform-plugins
[        ]       To upgrade:
[        ]         brew upgrade cocoapods
[        ]         pod setup
[        ] [✓] Android Studio (version 3.2)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Flutter plugin version 31.3.1
[        ]     • Dart plugin version 181.5656
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ] [!] Connected device
[        ]     ! No devices available
[        ] ! Doctor found issues in 2 categories.
[  +11 ms] "flutter doctor" took 10,047ms.
```

**Comment by TanzanianGem** [comment]
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!

F:\flutter> flutter -v doctor -v
[  +26 ms] executing: [F:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [F:\flutter\] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [F:\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [F:\flutter\] git log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +3 ms] executing: [F:\flutter\] git log -n 1 --pretty=format:%ar
[  +43 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 5 weeks ago
[   +1 ms] executing: [F:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +81 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.0.0-0-g5391447fa
[ +518 ms] java -version
[ +171 ms] [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
[  +10 ms]     • Flutter version 1.0.0 at F:\flutter
[   +1 ms]     • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
[   +3 ms]     • Engine revision 7375a0f414
[   +1 ms]     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
-[   +5 ms] executing: C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +33 ms] Exit code 0 from: C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
[  +22 ms] executing: C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l                            \[ +143 ms] executing: C:\Users\mark\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses                          -[ +207 ms] List of devices attached                                                                                    [+5227 ms] [!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[        ]     • Android SDK at C:\Users\mark\AppData\Local\Android\sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-28, build-tools 28.0.2
[        ]     • Java binary at: F:\Program Files\Android\Android Studio\jre\bin\java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ]     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[  +12 ms] [√] Android Studio (version 3.2)
[   +3 ms]     • Android Studio at F:\Program Files\Android\Android Studio
[   +5 ms]     • Flutter plugin version 31.3.1
[   +7 ms]     • Dart plugin version 181.5656
[   +6 ms]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[   +2 ms] [!] Connected device
[   +5 ms]     ! No devices available
[   +8 ms] ! Doctor found issues in 2 categories.
[  +57 ms] "flutter doctor" took 6,301ms.

**Comment by TanzanianGem** [comment]
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!

F:\flutter> flutter -v doctor -v
[  +26 ms] executing: [F:\flutter\] git rev-parse --abbrev-ref --symbolic
@{u}
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [F:\flutter\] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [F:\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] executing: [F:\flutter\] git log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +3 ms] executing: [F:\flutter\] git log -n 1 --pretty=format:%ar
[  +43 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 5 weeks ago
[   +1 ms] executing: [F:\flutter\] git describe --match v*.*.*
--first-parent --long --tags
[  +81 ms] Exit code 0 from: git describe --match v*.*.* --first-parent
--long --tags
[   +2 ms] v1.0.0-0-g5391447fa
[ +518 ms] java -version
[ +171 ms] [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows
[Version 10.0.17134.472], locale en-US)
[  +10 ms]     • Flutter version 1.0.0 at F:\flutter
[   +1 ms]     • Framework revision 5391447fae (5 weeks ago), 2018-11-29
19:41:26 -0800
[   +3 ms]     • Engine revision 7375a0f414
[   +1 ms]     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
-[   +5 ms] executing:
C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +33 ms] Exit code 0 from:
C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
[  +22 ms] executing:
C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l
                      \[ +143 ms] executing:
C:\Users\mark\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
                      -[ +207 ms] List of devices attached
                                                                  [+5227
ms] [!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[        ]     • Android SDK at C:\Users\mark\AppData\Local\Android\sdk
[        ]     • Android NDK location not configured (optional; useful for
native profiling support)
[        ]     • Platform android-28, build-tools 28.0.2
[        ]     • Java binary at: F:\Program Files\Android\Android
Studio\jre\bin\java
[        ]     • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1136-b06)
[        ]     ! Some Android licenses not accepted.  To resolve this, run:
flutter doctor --android-licenses
[  +12 ms] [√] Android Studio (version 3.2)
[   +3 ms]     • Android Studio at F:\Program Files\Android\Android Studio
[   +5 ms]     • Flutter plugin version 31.3.1
[   +7 ms]     • Dart plugin version 181.5656
[   +6 ms]     • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1136-b06)
[   +2 ms] [!] Connected device
[   +5 ms]     ! No devices available
[   +8 ms] ! Doctor found issues in 2 categories.
[  +57 ms] "flutter doctor" took 6,301ms.

**Comment by kangwang1988** [comment]
`C:\Users\mark\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +33 ms] Exit code 0 from:`
adb seems fine.

Paste the log why you say `No ADB found but flutter doctor says all green checks. Android studio works fine.` please.

**Comment by TanzanianGem** [comment]
Sorry only using brief of doctor...but the flutter app trying to run is from flutter at start,the 1st of the 6?

**Comment by TanzanianGem** [comment]
In device file explorer, I hit that and...
"Error initializing ADB:Android debug bridge not found"

**Comment by TanzanianGem** [comment]
I did not change the code of the flutter app I'm using from the options in the start window.

**Comment by kangwang1988** [comment]
@TanzanianGem 
The flutter doctor works fine, it seems to be a pure android problem.
The best place for resolve this issue is [StackOverflow](https://stackoverflow.com/questions/tagged/flutter).
The Github issues log is for filing bugs or feature requests.
Closing this issue now.

**Comment by TanzanianGem** [comment]
And still the problem is flutter won't send app to note 8(Oreo 8.0).or my cheap j7 (Oreo 8.1)

**Comment by kangwang1988** [comment]
@TanzanianGem 
You can ask this question over stackoverflow, if it turns out to be a flutter resulted problem, please feel free to reopen this issue.

**Comment by TanzanianGem** [comment]
Thanks for no help!
