### ISSUE TITLE
Found Issue from website page Write Your First Flutter App

### ISSUE THREAD

**Issue by FreeLoopC** [flutter/flutter#26048]
When I use multiple fingers long press the listview items, there are background shadow with these items. 
But when I take off my fingers, thest items still with background shadow.
Is this a bug or some features?
![qq 20190104095548](https://user-images.githubusercontent.com/20551753/50670693-454d7e00-1008-11e9-8283-9d9965d92a37.png)

**Comment by kangwang1988** [comment]
@FreeLoopC 
The best place for asking Flutter questions is [StackOverflow](https://stackoverflow.com/questions/tagged/flutter).
The Github issues log is for filing bugs or feature requests.
