### ISSUE TITLE
Visual Code is unable to locate the Flutter SDK 

### ISSUE THREAD

**Issue by bpavan1** [flutter/flutter#26052]

**Comment by timsneath** [comment]
If Flutter is on the system path, Visual Studio Code can find it. If Flutter is not on the system path, you can point to it with the Visual Studio Code settings dialog.

**Comment by bpavan1** [comment]
Thanks for the reply 
But how to set a path 
Flutter is on system path

**Comment by timsneath** [comment]
Can you run `flutter` from a command prompt? Setting the PATH environment variable is out of scope for the Github issues log, I'm afraid -- but there are plenty of good guides that you can find by searching Google.

**Comment by zoechi** [comment]
https://flutter.io/docs/get-started/install/macos#update-your-path

If you are not using macOS start from https://flutter.io/docs/get-started/install and navigate to "Update your path" manually.
