### ISSUE TITLE
Cannot build a 32 bit version of gen_snapshot

### ISSUE THREAD

**Issue by jakesays** [flutter/flutter#26055]
I am targeting a 32 bit ARM device and I also need a 32 bit gen_snapshot. It appears there is support only for 64 bit. I cannot find anywhere under the source tree anything but x64 libraries (under buildtools/linux-x64.

Where can I find the proper x86 32 bit sysroot?

**Comment by kangwang1988** [comment]
Please paste flutter doctor -v first.
@jakesays

**Comment by jakesays** [comment]
I'm trying to build libflutter_engine.so - i don't have a flutter yet, do I?

**Comment by kangwang1988** [comment]
Please install flutter first:
[https://flutter.io/docs/get-started/instal](https://flutter.io/docs/get-started/instal)

Now, flutter engine products including support for arm32 android devices(including corresponding gen_snapshot), you don't need to recompile the engine to get one.

**Comment by jakesays** [comment]
I'll install it, but this isn't an android device. It's a handheld point of sale terminal with an armv6 w/o fpu. I have built an arm toolchain to build libflutter_engine.so

**Comment by kangwang1988** [comment]
@jakemac53 
See [https://github.com/flutter/flutter/wiki/Compiling-the-engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine)
for more.

**Comment by jakesays** [comment]
Come to think of it the bug/feature is there is no linux_x32 support.

**Comment by kangwang1988** [comment]
Have you successfully setup the engine environment in you computer?
In fact, gn --help could tell you more.
KyleWongdeMacBook-Pro:src kylewong$ cd /Users/kylewong/Codes/Flutter/alibaba-flutter/engine/src
```
KyleWongdeMacBook-Pro:src kylewong$ ./flutter/tools/gn --help
usage: gn [-h] [--unoptimized] [--runtime-mode {debug,profile,release}]
          [--dynamic] [--interpreter] [--dart-debug]
          [--target-os {android,ios,linux}] [--android]
          [--android-cpu {arm,x64,x86,arm64}] [--ios] [--ios-cpu {arm,arm64}]
          [--simulator] [--linux-cpu {x64,x86,arm64,arm}]
          [--arm-float-abi {hard,soft,softfp}] [--goma] [--no-goma] [--lto]
          [--no-lto] [--clang] [--no-clang] [--target-sysroot TARGET_SYSROOT]
          [--target-toolchain TARGET_TOOLCHAIN]
          [--target-triple TARGET_TRIPLE]
          [--toolchain-prefix TOOLCHAIN_PREFIX] [--enable-vulkan]
          [--embedder-for-target]

A script run` gn gen`.

optional arguments:
  -h, --help            show this help message and exit
  --unoptimized
  --runtime-mode {debug,profile,release}
  --dynamic
  --interpreter
  --dart-debug
  --target-os {android,ios,linux}
  --android
  --android-cpu {arm,x64,x86,arm64}
  --ios
  --ios-cpu {arm,arm64}
  --simulator
  --linux-cpu {x64,x86,arm64,arm}
  --arm-float-abi {hard,soft,softfp}
  --goma
  --no-goma
  --lto
  --no-lto
  --clang
  --no-clang
  --target-sysroot TARGET_SYSROOT
  --target-toolchain TARGET_TOOLCHAIN
  --target-triple TARGET_TRIPLE
  --toolchain-prefix TOOLCHAIN_PREFIX
  --enable-vulkan
  --embedder-for-target
KyleWongdeMacBook-Pro:src kylewong$
```

**Comment by jakesays** [comment]
Yes I am very familiar with gn. I've been using it to do custom builds of chromium for several years. The issue is simple. All I need is `./engine/src/buildtools/linux-x32` instead of `./engine/src/buildtools/linux-x64`

**Comment by jakesays** [comment]
@kangwang1988 Ugh. I just found the 32bit x86 sysroot. 

Thanks, and sorry for the trouble.

**Comment by kangwang1988** [comment]
Glad to hear that. If you meet other flutter/engine related questions, feel free to file new issues.
@jakesays
