### ISSUE TITLE
RenderObject/Box doesn't have any lifecycle methods for when it's no longer valid (ie. its associated widget has been disposed)

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2605]
I'm possibly wrong about this, but I couldn't find it.

What I'm trying to do in this case is "clean up" once the RenderBox/Object is no longer in use.

**Comment by abarth** [comment]
The lifecycle for render objects is a bit different from widgets.  The relevant methods are `attach()` and `detach()`.  `attach()` is called when you enter the tree (you must call super).  `detach()` is called when you leave the tree (you must call super).  There is no terminal state.  If you're detached, it's always possible for you to be attached again.  That's unlike State objects for widgets which are terminal after `dispose()`.

**Comment by apwilson** [comment]
ty, that worked perfectly.
