### ISSUE TITLE
No ADB found on flutter

### ISSUE THREAD

**Issue by TanzanianGem** [flutter/flutter#26056]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by TanzanianGem** [comment]
github sucks, third time trying for help and called dumb....what is a bug? flutter on andriod studio not sending a premade (by flutter) flutter app to note 8 with oreo 8.0(i have SDK 8.0)? I call it a elephant,but what do i know?
device file explorer says.."Error initializing ADB Android debug bridge not found"
but.... flutter doctor says... "No problems" all green check marks.
what is a bug again?

**Comment by AnMokoto** [comment]
@TanzanianGem  maybe u can use  `gradle assemble(Debug|Release)`  i think , and try to install the apk with the `adb install `

**Comment by AnMokoto** [comment]
@TanzanianGem 
Maybe u can use the gradle command to build an apk with `gradle assemble(Debug|Release)`,
and check the status with `adb devices`  to install the apk from the  command `adb install [apk name]`.
or check out u developer tools to enable the adb debug.

**Comment by TanzanianGem** [comment]
Tim smeath from flutter told me I need to learn how to use a computer and GitHub is for reporting bugs(I have a elephant). I'm making him a YouTube video how flutter doesn't work that covers my problem
So I'm good...

**Comment by TanzanianGem** [comment]
Sorry,this was the 3rd time asking for help...1st time guy from China closed it,2nd time Tim smeath closed it.
I never had a problem with Android studio and never had to ask for help for any program except for flutter and then I got closed out.

**Comment by AnMokoto** [comment]
@TanzanianGem 
or be a issues about android not `flutter` cause reject u.
finally,:smile:
`When the life gives you lemons,make lemonade.`

**Comment by TanzanianGem** [comment]
So...I closed out flutter and opened Android to show on video it works sending to my phone..guess what happened? Flutter was on my phone with Android app 'hello world' running on Android studio. Why? 
It will be a YouTube video.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
