### ISSUE TITLE
can't run the app on my android devices

### ISSUE THREAD

**Issue by shrimpairship** [flutter/flutter#26060]
Hey, guys!
I follow the guidance of the flutter website's Get Started.
Run command "flutter doctor", it shows that “No issues found”.
Bug when I run the app in android studio or command "flutter run", I got a error, here is the error log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "E:\demo\flutter_app_test\android\gradlew.bat" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 400 Bad Request"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2124)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Picked up _JAVA_OPTIONS: -Xmx1024M
  Command: E:\demo\flutter_app_test\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:185:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:166:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:95:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#7      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._complete (dart:async/future_impl.dart:476:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    • Flutter version 1.0.0 at E:\flutter_windows_v1.0.0-stable\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\BaiduNetdiskDownload\android-sdk-windows\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\BaiduNetdiskDownload\android-sdk-windows\sdk
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at E:\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • SM G9500 • 98899a364b46564953 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

here is the output of command "flutter doctor -v":
C:\Users\zhanlj>flutter doctor -v
[âˆš] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    â€¢ Flutter version 1.0.0 at E:\flutter_windows_v1.0.0-stable\flutter
    â€¢ Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    â€¢ Engine revision 7375a0f414
    â€¢ Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[âˆš] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    â€¢ Android SDK at D:\BaiduNetdiskDownload\android-sdk-windows\sdk
    â€¢ Android NDK location not configured (optional; useful for native profili
ng
      support)
    â€¢ Platform android-28, build-tools 28.0.3
    â€¢ ANDROID_HOME = D:\BaiduNetdiskDownload\android-sdk-windows\sdk
    â€¢ Java binary at: E:\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    â€¢ All Android licenses accepted.

[âˆš] Android Studio (version 3.2)
    â€¢ Android Studio at E:\Android Studio
    â€¢ Flutter plugin version 31.3.1
    â€¢ Dart plugin version 181.5656
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[âˆš] Connected device (1 available)
    â€¢ SM G9500 â€¢ 98899a364b46564953 â€¢ android-arm64 â€¢ Android 8.0.0 (API
 26)

â€¢ No issues found!

**Comment by kangwang1988** [comment]
It's a network resulted gradle problem.
Please don't use `flutter run`, instead open the android project as a pure android project, build it. I think you will face the same problem. Please try this way, if it still remains, I think Stackoverflow is a better place to ask those kind of flutter supported questions.
@shrimpairship

**Comment by shrimpairship** [comment]
@kangwang1988 
thanks for reply! I'll follow your advice! I close this issue.
