### ISSUE TITLE
Keyboard won't show up after tapping on firebase_admob ads

### ISSUE THREAD

**Issue by Maherr** [flutter/flutter#26064]
the complete example : https://github.com/Maherr/flutter_firebase_admob_bug

Keyboard won't show up after tapping on ad and returning back to the app but works fine before that. also, if the app has multiple screens it with multiple text fields they wont work either. the only way to make the keyboard show up again when pressing a text field is to force close the app and launch again.

**Comment by zoechi** [comment]
>  if the app has multiple screens it with multiple text fields they wont work either.

Can you please elaborate how the "don't work"?

Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Cross-link https://stackoverflow.com/questions/54024176/flutter-keyboard-wont-show-up-after-tapping-on-ad

**Comment by Maherr** [comment]
> Can you please elaborate how the "don't work"?

the keyboard won't show up when pressing on the `TextField` widget.

> Please add the output of flutter doctor -v.

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/maher/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/maher/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/69/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /snap/android-studio/69/android-studio
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Pixel 2 • HT7AJ1A01965 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by kroikie** [comment]
@Maherr

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/522. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
