### ISSUE TITLE
When use gradle plugin version 3.2.1, all assets are missing

### ISSUE THREAD

**Issue by sunjianshun** [flutter/flutter#26066]
## Steps to Reproduce
When i use flutter as a module in an exists app, found that gradle plugin version 3.2.1 leading to missing assets in flutter-debug.aar.
`build.gradle`
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
``` 

The _flutter-debug.aar_ results as follow:

- classpath 'com.android.tools.build:gradle:2.3.2'  IS CORRECT
```
├── AndroidManifest.xml
├── R.txt
├── aidl
├── assets
│   └── flutter_assets
│       ├── AssetManifest.json
│       ├── FontManifest.json
│       ├── LICENSE
│       ├── fonts
│       │   └── MaterialIcons-Regular.ttf
│       ├── images
│       │   ├── ic_arrow_back.png
│       │   ├── ic_arrow_gray.png
│       │   └── ic_logo.png
│       ├── isolate_snapshot_data
│       ├── kernel_blob.bin
│       └── vm_snapshot_data
├── classes (classes.jar)
│   ├── assets
│   │   └── flutter_shared
│   │       └── icudtl.dat
│   ├── com
│   │   └── netease
│   │       └── edu
│   │           └── flutter
│   │               └── BuildConfig.class
│   └── io
│       └── flutter
│           ├── facade
│           │   ├── Flutter$1.class
│           │   ├── Flutter$2.class
│           │   ├── Flutter.class
│           │   └── FlutterFragment.class
│           └── plugins
│               └── GeneratedPluginRegistrant.class
├── classes.jar
├── jni
│   ├── armeabi-v7a
│   │   └── libflutter.so
│   ├── x86
│   │   └── libflutter.so
│   └── x86_64
│       └── libflutter.so
├── libs
│   ├── flutter-x86.jar
│   └── flutter.jar
└── res
```
- classpath 'com.android.tools.build:gradle:3.2.1'  IS WRONG
```
├── AndroidManifest.xml
├── R.txt
├── armeabi-v7a
├── classes (classes.jar)
│   ├── com
│   │   └── netease
│   │       └── edu
│   │           └── flutter
│   │               └── BuildConfig.class
│   └── io
│       └── flutter
│           ├── facade
│           │   ├── Flutter$1.class
│           │   ├── Flutter$2.class
│           │   ├── Flutter.class
│           │   └── FlutterFragment.class
│           └── plugins
│               └── GeneratedPluginRegistrant.class
├── jni
│   ├── armeabi-v7a
│   │   └── libflutter.so
│   ├── x86
│   │   └── libflutter.so
│   └── x86_64
│       └── libflutter.so
├── libs
│   ├── flutter-x86.jar
│   └── flutter.jar
├── x86
└── x86_64
```

**When use gradle plugin version 3.2.1, all assets were missing**

## flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
• Flutter version 1.0.0 at /Users/hzsunjianshun/workspace/project/flutter
• Framework revision 5391447 (5 weeks ago), 2018-11-29 19:41:26 -0800
• Engine revision 7375a0f414
• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
• Android SDK at /Users/hzsunjianshun/Library/Android/sdk/
• Android NDK at /Users/hzsunjianshun/Library/Android/sdk/ndk-bundle
• Platform android-28, build-tools 28.0.3
• ANDROID_HOME = /Users/hzsunjianshun/Library/Android/sdk/
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
• All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.1, Build version 10B61
✗ Verify that all connected devices have been paired with this computer in Xcode.
If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
To update with Brew, run:
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
brew install ideviceinstaller
• ios-deploy 1.9.4
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 31.2.1
• Dart plugin version 181.5656
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
• IntelliJ at /Applications/IntelliJ IDEA.app
• Flutter plugin version 29.0.1
• Dart plugin version 173.4700

[✓] VS Code (version 1.21.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 2.19.0

[!] Connected device
! No devices available

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by sunjianshun** [comment]
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/hzsunjianshun/workspace/project/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/hzsunjianshun/Library/Android/sdk/
    • Android NDK at /Users/hzsunjianshun/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/hzsunjianshun/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by zcweng** [comment]
@zoechi 我也有这个问题，怎么解决呢

**Comment by duanju** [comment]
I have the same issue

**Comment by blasten** [comment]
This issue was fixed in the latest stable version. If it's still happening, please reopen.
