### ISSUE TITLE
app run crash after plugin image picker installed

### ISSUE THREAD

**Issue by mxdwjcty** [flutter/flutter#26063]
my device is Redmi note 5

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the full error output.

**Comment by mxdwjcty** [comment]
l have solved this problem after i build a new flutter project with old lib files.
seems to be some build setting errors.

**Comment by zoechi** [comment]
Could be https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

Thanks for the update.
