### ISSUE TITLE
Failed assertion: 'url != null': is not true.

### ISSUE THREAD

**Issue by rajanandroid** [flutter/flutter#26071]
```
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 451 pos 16: 'url != I/flutter ( 1542): null': is not true.
```
```
When the exception was thrown, this was the stack:
I/flutter ( 1542): #2      new NetworkImage (package:flutter/src/painting/image_provider.dart:451:16)
I/flutter ( 1542): #3      new Image.network (package:flutter/src/widgets/image.dart:213:16)
I/flutter ( 1542): #4      HomePage.image (package:news/main.dart:34:20)
I/flutter ( 1542): #5      HomePage.dataList.<anonymous closure> (package:news/main.dart:90:17)
I/flutter ( 1542): #6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:397:15)
I/flutter ( 1542): #7      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1000:67)
I/flutter ( 1542): #8      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter ( 1542): #9      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1000:26)
I/flutter ( 1542): #10     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:55)
I/flutter ( 1542): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 1542): #12     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter ( 1542): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter ( 1542): #14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter ( 1542): #15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter ( 1542): #16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter ( 1542): #17     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter ( 1542): #18     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:341:5)
I/flutter ( 1542): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter ( 1542): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 1542): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 1542): #24     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter ( 1542): #25     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter ( 1542): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter ( 1542): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 1542): #43     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 1542): #44     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter ( 1542): #45     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 1542): #46     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 1542): #47     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 1542): #48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 1542): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 1542): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 1542): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 1542): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 1542): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 1542): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 1542): #55     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 1542): #56     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 1542): (elided 2 frames from class _AssertionError)
I/flutter ( 1542): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
`NetworkImage` requires a non-Null URL to be passed.  
You can use something like `url != null ? Image.network(url) : Container()`

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by shivamkapasia0** [comment]
Just uninstall the app on emulator or real device.
Close IDE and restart then resync the project and then run your app.
This works for me.

**Comment by amitsingh6391** [comment]
> ```
> 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 451 pos 16: 'url != I/flutter ( 1542): null': is not true.
> ```
> 
> ```
> When the exception was thrown, this was the stack:
> I/flutter ( 1542): #2      new NetworkImage (package:flutter/src/painting/image_provider.dart:451:16)
> I/flutter ( 1542): #3      new Image.network (package:flutter/src/widgets/image.dart:213:16)
> I/flutter ( 1542): #4      HomePage.image (package:news/main.dart:34:20)
> I/flutter ( 1542): #5      HomePage.dataList.<anonymous closure> (package:news/main.dart:90:17)
> I/flutter ( 1542): #6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:397:15)
> I/flutter ( 1542): #7      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1000:67)
> I/flutter ( 1542): #8      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
> I/flutter ( 1542): #9      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1000:26)
> I/flutter ( 1542): #10     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:55)
> I/flutter ( 1542): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
> I/flutter ( 1542): #12     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
> I/flutter ( 1542): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
> I/flutter ( 1542): #14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
> I/flutter ( 1542): #15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
> I/flutter ( 1542): #16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
> I/flutter ( 1542): #17     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
> I/flutter ( 1542): #18     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:341:5)
> I/flutter ( 1542): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
> I/flutter ( 1542): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
> I/flutter ( 1542): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
> I/flutter ( 1542): #24     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
> I/flutter ( 1542): #25     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
> I/flutter ( 1542): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
> I/flutter ( 1542): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
> I/flutter ( 1542): #43     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
> I/flutter ( 1542): #44     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
> I/flutter ( 1542): #45     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
> I/flutter ( 1542): #46     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
> I/flutter ( 1542): #47     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
> I/flutter ( 1542): #48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
> I/flutter ( 1542): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
> I/flutter ( 1542): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
> I/flutter ( 1542): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
> I/flutter ( 1542): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
> I/flutter ( 1542): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
> I/flutter ( 1542): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
> I/flutter ( 1542): #55     _invoke (dart:ui/hooks.dart:154:13)
> I/flutter ( 1542): #56     _drawFrame (dart:ui/hooks.dart:143:3)
> I/flutter ( 1542): (elided 2 frames from class _AssertionError)
> I/flutter ( 1542): ════════════════════════════════════════════════════════════════════════════════════════════════════
> ```

Are u solve it

**Comment by rajngarg** [comment]
Sorry, Not working on this anymore

**Comment by angadhahaha** [comment]
did you find any solution?
