### ISSUE TITLE
Consider adding timestamps to sensor events

### ISSUE THREAD

**Issue by DrPaulT** [flutter/flutter#26078]
The sensor plugin sends an (x, y, z) vector for the linear accelerometer, for example, but there is no timestamp to say exactly when the event was sampled.

As I understand it, the stream returned by accelerometerEvents.listen() may be buffered in some situations, so it is not possible to use the time of day when the event is delivered.  Or at least there may be appreciable latency when doing so.

If adding a millisecond timestamp could be considered when sensors are next updated, that would be great---the application is sports performance monitoring so precision concerning when accelerations are sampled is essential for correct interpretation of the motion.

Thanks

**Comment by dannyalbuquerque** [comment]
https://github.com/dannyalbuquerque/plugins/tree/master/packages/sensors

**Comment by stuartmorgan** [comment]
Closing as `sensors` is deprecated in favor of [`sensors_plus`](https://pub.dev/packages/sensors_plus).
