### ISSUE TITLE
i have problem with textspan

### ISSUE THREAD

**Issue by HoSheiMa** [flutter/flutter#26076]
i think i line breakd is have available space to cover a word sendd to next line
if the breakd line start at start right
not start at center
but i don't know why it start at center and o
thers lines start at right
![image](https://user-images.githubusercontent.com/31377696/50697821-ffb2a480-104b-11e9-9edb-caec04985d81.png)

**Comment by HoSheiMa** [comment]
![image](https://user-images.githubusercontent.com/31377696/50697915-46a09a00-104c-11e9-9aae-3c64a027aef7.png)

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by HoSheiMa** [comment]
![image](https://user-images.githubusercontent.com/31377696/50704598-a143f100-1060-11e9-95c8-c2c72e54e453.png)

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
