### ISSUE TITLE
Inner ListView.builder with shrinkWrap as true builds all children at once  

### ISSUE THREAD

**Issue by davidmartos96** [flutter/flutter#26072]
Creating a scrollable layout like below does not allow the inner `ListView.builder` to call build as the user scrolls. 

![image](https://user-images.githubusercontent.com/22084723/50686795-142c7800-101f-11e9-9b85-3f840581fd27.png)

Yellow and blue blocks can be arbitrarily large, so I guess something along the lines of `ListView.builder` should be used.

It builds all children at once when the yellow block builds, causing performance issues when scrolling.

Is this a bug or expected behaviour?

The number of items and size of the children is known in advance. Could there be other alternatives? 

# Sample code
```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: ListView.builder(
          itemCount: 20,
          itemBuilder: (BuildContext context, int blockIdx) {
            print("Building block $blockIdx");
            return new Column(
              children: [
                Padding(
                  child: Text("Block $blockIdx"),
                  padding: EdgeInsets.all(8.0)
                ),
                ListView.builder(
                  shrinkWrap: true,
                  physics: ClampingScrollPhysics(),
                  itemCount: 30,
                  itemBuilder: (BuildContext context, int childIdx) {
                    print("Building block $blockIdx child $childIdx");
                    return Padding(
                      child: Text("Child $childIdx"),
                      padding: EdgeInsets.only(left: 20.0, right: 8.0, top: 8.0, bottom: 8.0),
                    );
                  },
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}
```
## Logs

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.195], locale en-US)
    • Flutter version 1.0.0 at C:\android\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
PS C:\Users\dheeraj> flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.195], locale en-US)
    • Flutter version 1.0.0 at C:\android\flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by vitor-gyant** [comment]
Is there any workaround for this problem ? Thanks

**Comment by makindotcc** [comment]
Any updates?

**Comment by nickdbush** [comment]
Removing ```itemCount``` means that nothing is rendered in the app (presumably as the GridView is trying to render an infinite amount of elements).

**Comment by VladyslavBondarenko** [comment]
Reproduced with `dev v1.16.4-pre.83`

**Comment by caseyryan** [comment]
The problem still exists

**Comment by msahmed1** [comment]
I had the same issue, I solved it by changing the "primary" property in the inner ListView.builder to false.

**Comment by davidmartos96** [comment]
@msahmed1 Are you sure that solves it? I've just tried it with the sample provided and I don't see any difference.

**Comment by msahmed1** [comment]
@davidmartos96 O sorry I mist interpreted the question, here is your solution.
[GitHubQuestion.txt](https://github.com/flutter/flutter/files/4673996/GitHubQuestion.txt)

**Comment by Ali1Ammar** [comment]
same problem here

**Comment by nmhernandez10** [comment]
same problem with 1.7.4 release flutter version

**Comment by toritroniks** [comment]
hi @davidmartos96 

I usually use CustomScrollView and Slivers for these cases.
With that, you can have multiple lists and not list elements inside the same scroll view.
Does the sample code below solve your problem?

```
      body: CustomScrollView(
        slivers: <Widget>[
          for (int blockIdx = 0; blockIdx < 20; blockIdx++) ...[
            SliverToBoxAdapter(
              child: Center(
                child: Padding(
                  child: Text('Block $blockIdx'),
                  padding: EdgeInsets.all(8.0),
                ),
              ),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int childIdx) {
                  print('Building block $blockIdx child $childIdx');
                  return Padding(
                    child: Text('Child $childIdx'),
                    padding: EdgeInsets.only(
                        left: 20.0, right: 8.0, top: 8.0, bottom: 8.0),
                  );
                },
                childCount: 30,
              ),
            ),
          ],
        ],
      ),
```

I used the spread operator(`...`) to pass the list elements of the for loop to the Widget list.
otherwise it would be like that: 
```
[[sliver, sliver],[sliver, sliver],[sliver, sliver],...]
```
when what we want is this:
```
[sliver, sliver, sliver, sliver, sliver, sliver,...]
```

Hope this helps!

**Comment by davidmartos96** [comment]
Hey @toritroniks , thanks for the suggestion. I was aware of this solution, but knowing that the list can be arbitrarily large (200 for example), I think that creating all the N slivers at once would not scale that well. 
Thanks for sharing, maybe it helps someone.

**Comment by toritroniks** [comment]
Oh! I see what you mean.
With this solution, the inner list elements would not be all loaded at once, but the outer slivers would.
so if you have a lot of slivers, it might get some performance issues.

**Comment by alissonflutter** [comment]
I have the same problem, any solution?

**Comment by anirudh-v2** [comment]
this is not that difficult . reply if you need help . 
thanks :)

**Comment by VladyslavBondarenko** [comment]
Persists with current master `1.21.0-6.0.pre.41`

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.41, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.41 at /Users/nevercode/dev/flutter
    • Framework revision 39fa00201d (3 hours ago), 2020-07-27 21:11:43 -0700
    • Engine revision f27729e97b
    • Dart version 2.10.0 (build 2.10.0-0.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (5 available)            
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by vinoopks** [comment]
I am also facing the same issue. Is there any workaround?

[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.19041.388], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

**Comment by mehrdad-shokri** [comment]
Is this a bug or intended behavior? @HansMuller can you guide us on this?

**Comment by pedromassangocode** [comment]
Still reproducible on latest `master` channel.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.22.0-10.0.pre.82 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 9248fda410 (13 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 Pro Max (mobile)  • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)            • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
pedromassango@MacBook-Pro-de-MacBook ~ % flutter doctor    
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
[✓] VS Code (version 1.48.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
</details>

**Comment by kasyrm** [comment]
I have similar issue when using ListView.builder in Column, StreamBuilder, Column, SingleChildScrollView, Scaffold. It loads all the items at once. Only when used directly in StreamBuilder, Scaffold it works correctly.

**Comment by alissonflutter** [comment]
suggestion that worked for me

_CustomScrollView (
slivers:[
SliverToBoxAdapter (
child: Column (
children: [
Container (),
Widget()...
Widget()...
],
 );
 ),
SliverList(
delegate: SliverChildBuilderDelegate(
(context, index) {
 return Widget() ....;
              },
            ), 
          )
        ],
      )_

**Comment by m-j-g** [comment]
After spending days trying to troubleshoot some performance issues - I discovered my shrink-wrapped listview.builder's were drawing all items.  I can't tell from the reading the responses what the best practices are to handle child shrink-wrapped listview.builder's

**Comment by MirzaBirds** [comment]
> Having a similar issue:
> 
> ```
> Flexible(
>           child: ListView.builder(
>             shrinkWrap: true,
>             itemCount: items.length,
>             itemBuilder: (BuildContext context, int index) {
>               return Container(
>                 decoration: BoxDecoration(
>                   border: BorderDirectional(
>                     bottom: BorderSide(color: Colors.white),
>                   ),
>                 ),
>                 child: FlatButton(
>                   onPressed: () => onSelected?.call(index),
>                   child: Row(
>                     children: <Widget>[
>                       Expanded(
>                         child: Text(
>                           items[index].name ?? '-',
>                           style: TextStyle(
>                             color: Colors.white,
>                           ),
>                         ),
>                       ),
>                       Flexible(
>                         child: items[index].isSelected
>                             ? Icon(
>                                 Icons.check,
>                                 color: Colors.lightBlue,
>                               )
>                             : Icon(
>                                 Icons.remove,
>                                 color: Colors.redAccent,
>                               ),
>                       ),
>                     ],
>                   ),
>                 ),
>               );
>             },
>           ),
>         ),
> ```
> 
> <img alt="Screen Shot 2020-08-21 at 7 29 15 PM" width="726" src="https://user-images.githubusercontent.com/237378/90946748-c8d9ff80-e3e4-11ea-9765-db4be0e1317e.png">

this is working for me

**Comment by rahuldange09** [comment]
I also came across this issue. This seems major issue as most of the time ListView is always combined with other widget and only way to use ListView with other widget is set 'shrinkWrap : true'.
I think this the main reason my app is slow in some screens when I need ListView with shrinkWrap.
I hope flutter team notices this issue and fixes it. It can really make so many apps more faster with this fix.

Anyways, does anyone has any other alternative?  As slivers are not helpful in my case only helps in some cases

**Comment by w4ll3** [comment]
Has anyone found a workaround this?

**Comment by Saifallak** [comment]
Sorry for the ping.. but is this issue on the road map? any solution so far?
I know it's hard to fix and but this issue since 4/1/2019

**Comment by SirusCodes** [comment]
Currently using Slivers is the only way to do it.

**Comment by davidmartos96** [comment]
Another solution is to use a single list/sliver and handle the nesting with the index, although simplicity wise, is not a really good solution.
I have the following helper class in my code to handle these situtations. With this you can have a single list and set the itemCount and itemBuilder based on the `flatMap.items`, which combines the keys and values from an arbitrary `Map<Key, List<Value>>`. Hope it helps someone.

```dart
import 'package:flutter/material.dart';

class FlatMap<Key, Value> {
  final List<FlatMapItem<Key, Value>> items = [];
  final Map<Key, Iterable<Value>> rawMap;

  FlatMap(this.rawMap) {
    _flattenMapInList(rawMap, items);
  }

  FlatMap.empty() : rawMap = {};
}

class FlatMapItem<MapKey, MapValue> {
  MapKey key;
  MapValue value;
  int index;

  FlatMapItem.value(this.value, {@required this.index}) : assert(value != null);
  FlatMapItem.key(this.key, {@required this.index}) : assert(key != null);

  bool get isKey => key != null;
}

void _flattenMapInList<Key, Value>(
    Map<Key, Iterable<Value>> map, List<FlatMapItem<Key, Value>> outList) {
  int keyIndex = 0;
  int valueIndex = 0;
  for (var entry in map.entries) {
    outList.add(FlatMapItem.key(entry.key, index: keyIndex));
    keyIndex++;
    for (var listItem in entry.value) {
      outList.add(FlatMapItem.value(listItem, index: valueIndex));
      valueIndex++;
    }
  }
}

```

**Comment by Piinks** [comment]
I believe this is working as intended, unless I am misunderstanding the OP. When `shrinkwrap` is true it will compute the size of the entire contents of the scrollable. That is why it is more expensive. From the docs:

> /// Shrink wrapping the content of the scroll view is significantly more
  /// expensive than expanding to the maximum allowed size because the content
  /// can expand and contract during scrolling, which means the size of the
  /// scroll view needs to be recomputed whenever the scroll position changes.

**Comment by 2shrestha22** [comment]
> I believe this is working as intended, unless I am misunderstanding the OP. When `shrinkwrap` is true it will compute the size of the entire contents of the scrollable. That is why it is more expensive. From the docs:
> 
> > /// Shrink wrapping the content of the scroll view is significantly more
> > /// expensive than expanding to the maximum allowed size because the content
> > /// can expand and contract during scrolling, which means the size of the
> > /// scroll view needs to be recomputed whenever the scroll position changes.

Is there any recommended approach for this type of situation?

**Comment by davidmartos96** [comment]
@Piinks It's true that is possible that it's working as intended. But the main idea behind the issue was to know a way to build that kind of UI. Using shrinkwrap in the inner scrollable was as closed as I got at the time.

**Comment by ShehanTreineticOfficial** [comment]
Does anyone solve this issue?  
I am using ListView.builder inside SliverList with shrinkWrap = true. But inside ListView builder build all children at once which is badly effective to app performance.

**Comment by SirusCodes** [comment]
> Does anyone solve this issue?
> I am using ListView.builder inside SliverList with shrinkWrap = true. But inside ListView builder build all children at once which is badly effective to app performance.

Maybe you can ask the question on stackoverflow with some code sample and I'm sure that someone would help you with it.

**Comment by mehrdad-shokri** [comment]
@ShehanTreineticOfficial why don't you use SliverList ChilldBuilderDelegate instead of ListView?

**Comment by jam33** [comment]
agreed that i wish the flutter team would have better explanation/solution around this.  i don't see another way to have an entire page as scrollable with a child element being a listview builder.  you have to use "shrinkwrap: true" or else it will complain about height constraints.  their documentation says:

> Shrink wrapping the content of the scroll view is significantly more expensive than expanding to the maximum allowed size because the content can expand and contract during scrolling, which means the size of the scroll view needs to be recomputed whenever the scroll position changes.

but that doesn't explain what "significantly more expensive" means.  I'm trying to create an infinite scroll, so it would be nice to have some way of monitoring when that "expensive" becomes too much (i realize that is somewhat dependent upon each users' device).  or better yet, provide a way that you can use a listview builder within a parent scrollable that isn't going to result in performance issues.  

OP didn't state how many objects were being added to their page before the issues were arising, so i hope it was a large amount and not 2 in the example shown since that would be very concerning!

**Comment by Piinks** [comment]
>  i don't see another way to have an entire page as scrollable with a child element being a listview builder. 

I think when a developer finds themselves nesting scrollables and shrink wrapping long lists, they should probably consider using slivers instead. That way you could have multiple SliverLists in a CustomScrollView, with other Slivers above, below, or in between. Maybe taking the OP and converting it to slivers as an example would be beneficial to add to the documentation as well. 

cc @craiglabenz we've been chatting about this recently

**Comment by jam33** [comment]
thanks @Piinks !

never worked with slivers before, but looking into them.

for me, it's not having nested scrollables.  i only want the whole page to scroll.  i do not want sections within the page to scroll.  i think OP and others are finding themselves in a situation where the easiest way to generate a list is to use listview.builder, however by default that comes with it's own scrolling.  you are able to disable that "inner" child scrolling with shrinkwrap:true and physics: const NeverScrollableScrollPhysics(), however flutter's documentation makes it seem dangerous to use this.

i think people default to using listview because (A) it's well covered in all tutorials and examples and (B) theoretically people want to be able to take advantage of the "only build what is going to be on the screen" (ie: some kind of on-demand rendering).  however, using shrinkwrap and physics actually gets rid of that on-demand rendering so the performance benefits are lost.

i'm guessing in my build() i could easily loop through my list of objects and return a widget (ex: card in a row) that would generate my "list" and fit well within the parent page's scroll.  however, i would think this would be ineffecient when compared to the listview's on-demand rendering.  however, when it comes down to it, i believe this option would be no better or worse than the listview with shrinkwrap:true (since that generates all items immediately anyway).  it's basically the same exact thing.  i just think most people get stuck here because the tutorials push them this way and it utilizes built-in functionality.

at least for me, what i would want is a way to create a vertical list of widgets (ex cards in rows) but not have it waste time generating/rendering anything that isn't immediately going to be on screen and only have it spend the resources calculating and rendering the widget when the user scrolls the parent page down.

does this make sense?  i'm not sure if sliverlists are the solution here.  do they have their own scrolling mechanism inside of the parent scroll view?  if so, that's not what i'm looking for.  if they can be "fixed" (not sure what you call a non-scrolling list), then it probably fits my needs.  I just don't necessarily understand why they can avoid the performance pitfalls of shrinkwrap but listview cannot?

lmk if i sound crazy and i can try to summary.  i believe what i'm describing is relevant to what the OP originally was having trouble with.  thanks!

**Comment by davidmartos96** [comment]
@Piinks OP here: 
The original intention was to build a scrollable UI, with a single scroll that grouped items by category. Some kind of 2 level treeview.
What I ended up doing to solve it is what's described here: https://github.com/flutter/flutter/issues/26072#issuecomment-847654101
It's solved with a single ListView, but working with it as a tree is not intuitive.

Slivers wouldn't work for this kind of UI because imagine you have 100 categories. You would need to create 100 different slivers, which is not performant either.

**Comment by Piinks** [comment]
>  Slivers wouldn't work for this kind of UI because imagine you have 100 categories. You would need to create 100 different slivers, which is not performant either.

I am not sure why the number of slivers would cause a performance issue, if they use builder delegates, the would all build their respective children lazily. No matter how many slivers there are.


> however by default that comes with it's own scrolling. you are able to disable that "inner" child scrolling with shrinkwrap:true and physics: const NeverScrollableScrollPhysics(),

^ This case is **_exactly_** what slivers will solve.
This [dartpad workshop](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbXhCZEtNaWxsRE1sdlJRYllsbjB6M0ZLZEZXUXxBQ3Jtc0trSmhmWXAzX2dWVUNKOHRaSTdPcWQxTUN2eERaNEFib3dTVFJQZDNnWEF4LXdZMjVlZGlhZE1fRjZqa0pKSHVTbmV3dkV2dXRpNWlFQWhFRFd4c3h3TzFtamFUWm1lVkVHcTVKN1RKOVoyS0V5ZHFtQQ&q=https%3A%2F%2Fgoo.gle%2F3oCRRTt) and [video](https://youtu.be/LUqDNnv_dh0) discussing this is available now, I highly recommend checking them out to understand lazy building slivers.

If you can give me a simple example of your ListViews I can probably convert them to slivers if the video and dartpad do not help Maybe then we can incorporate it into our documentation for everyone. :)

**Comment by davidmartos96** [comment]
@Piinks 
> I am not sure why the number of slivers would cause a performance issue, if they use builder delegates, the would all build their respective children lazily. No matter how many slivers there are.

This would be a simple example using slivers with the approach described in the workshop. [dartpad](https://dartpad.dev/?id=8811db2c38680835a929811cc12eaf29) The issue I was referring to when using too many slivers is that they still have some overhead when building, is not entirely lazy. If you take a look at the console in the dartpad, the first item in all slivers gets built, even though only the first few items in the first list are visible. Is this expected?

**Comment by Piinks** [comment]
Thank you very much for the dartpad! I can see what you mean.
There may be a bug here, I've filed https://github.com/flutter/flutter/issues/95028 for tracking.
While we look into it and see about fixing that case, it is still a lot more efficient building only the first item instead *all* of the items, so I hope it is a much better option than shrinkwrap for you. :)
Please follow the linked issue for the bug you identified, and thank you!

Since the shrinkwrap behavior is expected, is there any further action we can take on this bug (based on the title)?

**Comment by davidmartos96** [comment]
@Piinks Yes, I think your dartpad and workshop cover the original issue discussed here. I'll follow up the other issue.
Thanks for the support here!

As a side note, and somewhat related, it would be great some kind of arbitrarily nested Tree View widget with efficient scrolling, probably using slivers under the hood. But I believe there is already an issue opened for a Tree View widget. 😄

**Comment by Piinks** [comment]
> As a side note, and somewhat related, it would be great some kind of arbitrarily nested Tree View widget with efficient scrolling, probably using slivers under the hood. But I believe there is already an issue opened for a Tree View widget. 😄

I agree! I thought the same thing and tried looking for an issue requesting a tree widget, but could not find it. Feel free to file a new feature request issue, we have an excellent triage team, so if the issue does exist, they will find it and de-dupe. If not, we should definitely have that request filed. :)

**Comment by nt4f04uNd** [comment]
I think that's the issue requesting for a Tree widget https://github.com/flutter/flutter/issues/31606

**Comment by davidmartos96** [comment]
@Piinks The one I saw was this one https://github.com/flutter/flutter/issues/42332

**Comment by Piinks** [comment]
Ah!! Awesome thank you both!
