### ISSUE TITLE
E2E plugin testing in the flutter/plugins CI

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#26080]
This is a follow-up to #10824: once we have a good way to test plugins, we should have e2e testing set up in the CI for flutter/plugins.

**Comment by collinjackson** [comment]
I think this issue can be closed once we have our driver test ([shared_preferences](flutter/plugins#1285), [cloud_firestore](flutter/plugins#1345), [cloud_functions](flutter/plugins#1346)) running on CI (flutter/plugins#1342).

The main things that I think are out of scope for this issue (but can be filed as separate feature requests)

- Interaction with non-Flutter UI (see [os_tester](https://github.com/flutter/plugins/pull/1321))
- Running tests on hosts where Flutter SDK isn't available
- Running on non-simulator devices
