### ISSUE TITLE
Creating a new project targeting iOS, the default deployment target is iOS 8 

### ISSUE THREAD

**Issue by seamusmc** [flutter/flutter#26093]
## Steps to Reproduce

1. From VSCode use the Flutter: New Project command.
2. Enter myapp for the project name, let Flutter build the project files
3. Use XCode to open the project
4. Select the top level Runner node in the project tree view
5. Inspect the Deployment Target for the project, it will  be 8.0

<img width="563" alt="screen shot 2019-01-04 at 3 10 14 pm" src="https://user-images.githubusercontent.com/959232/50715592-e18c7a80-1032-11e9-9cd6-43f114d113a4.png">

Please update the default to iOS 11. As of April 2018 all new apps submitted to the App Store are required to target iOS 11, (requiring XCode 9), come March 2019 all new apps submitted to the App Store are are required to target iOS 12.1, (requiring XCode 10)

While updating the default would be a convenience, manually updating the Deployment Target to iOS 10 or newer reveals a bug: 'UILocalNotification' is deprecated

**Comment by kangwang1988** [comment]
@seamusmc 
I think there is some misunderstanding here.
```
You can now submit apps that take advantage of the powerful new capabilities in the next release of iOS, watchOS, and tvOS. Build your apps using Xcode 10 GM seed, test with the latest releases of iOS 12, watchOS 5, and tvOS 12, and submit them for review.
Starting March 2019, all new apps and app updates for iPhone, including universal apps, will need to be built with the iOS 12 SDK and support iPhone XS Max. All new apps and app updates for Apple Watch will need to be built with the watchOS 5 SDK and support Apple Watch Series 4.
```

Just build app with Xcode10, built with iOS12 SDK.
It doesn't mean to change your minimum iOS support(the deployment target).
