### ISSUE TITLE
XCode Project generated by Flutter

### ISSUE THREAD

**Issue by seamusmc** [flutter/flutter#26096]
## Steps to Reproduce

1. From VSCode use the Flutter: New Project command.
2. Enter myapp for the project name, let Flutter build the project files
3. Use XCode 10 to open the project
4. Press CMD+B to build the project - (Update, turns out this step is unnecessary. The warning is present the first time the workspace is opened in XCode 10.)
5. The following warning is generated:

<img width="331" alt="screen shot 2019-01-04 at 3 36 48 pm" src="https://user-images.githubusercontent.com/959232/50716464-91171c00-1036-11e9-84dc-b5287eb52c94.png">

Please update the generated project settings to conform with the recommended settings. 

While this would be a convenience, the validator fixes the problem, its annoying to have to update so many settings that just work if I create a new project with XCode. This kind of experience is not going to help with adoption. The experience needs to be as smooth and reliable as the behavior provided by XCode.

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/seamus_mcgowan/Flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/seamus_mcgowan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Seamus' iPhone • deb505af77f116bc6e4c38f89cbe5f3e1779bf58 • ios • iOS 12.1.2

• No issues found!
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by athornz** [comment]
I'm getting this warning as well, and all builds fails unless I apply the recommended settings.
