### ISSUE TITLE
Updated XCode project's Deployment Target to iOS 10+: 'UILocalNotification' is deprecated

### ISSUE THREAD

**Issue by seamusmc** [flutter/flutter#26094]
## Steps to Reproduce

1. From VSCode use the Flutter: New Project command.
2. Enter myapp for the project name, let Flutter build the project files
3. Use XCode to open the project
4. Select the top level Runner node in the project tree view
5. Change the Deployment Target to iOS 12.1
6. Use CMD+B to build

The following warnings are generated: 
<img width="592" alt="screen shot 2019-01-04 at 3 24 32 pm" src="https://user-images.githubusercontent.com/959232/50716104-daff0280-1034-11e9-82b2-7d02d89a245f.png">

Please update the deprecated code.

As of April 2018 all new apps submitted to the App Store are required to target iOS 11, (requiring XCode 9), come March 2019 all new apps submitted to the App Store are are required to target iOS 12.1, (requiring XCode 10)

**Comment by palmCoconuts** [comment]
This problem was happening on for me using image_picker_modern: ^0.4.12+2. 

I was on  a development target of 8.0. 
After reading this post and updating the development target to 12.2, the app allowed me request user permission and open the camera. 

This was a helpful post.

**Comment by jmagman** [comment]
I think the UILocalNotification APIs added in https://github.com/flutter/engine/pull/6858/ need to be updated with availability to match the API_DEPRECATED(..., ios(4.0, 10.0)) decorating UILocalNotification.
