### ISSUE TITLE
google_sign_in gives "mon.api.ApiException:12500" when I generate a signed apk

### ISSUE THREAD

**Issue by kwaku96** [flutter/flutter#26105]
before I signed the apk , everything was working perfectly but after I signed the apk , I started getting the error

**Comment by kyungjoongo** [comment]
same issue
==>com.google.android.gms.common.api.ApiException: 12500

PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 12500: , null)

**Comment by kwaku96** [comment]
I have been to resolve the issue… it had nothing to with the plugin.. Thank you for you immediate response

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by monxarat** [comment]
@kaiyuanw how to fix it?
