### ISSUE TITLE
How to add extra text into flutter google map custom marker or enable infowindow open always?

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#26109]
The problem is how to infuse text overlap on the custom google map marker with text which represents the vehicle registration number.

I have tried to use this method to have the text overlay on the icon builder: (context) =>() But is not recognized at all.
```dart
class MapsDemo extends StatefulWidget {
    @override
    State createState() => MapsDemoState();
  }

class MapsDemoState extends State<MapsDemo> {

  GoogleMapController mapController;
 //Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler().requestPermissions([PermissionGroup.contacts]);import 'package:permission_handler/permission_handler.dart';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
          body: Column(
            children: <Widget>[
            Container(
                height: MediaQuery.of(context).size.height,
                width: MediaQuery.of(context).size.width,
                child: GoogleMap(
                 onMapCreated: (GoogleMapController controller) {
                   mapController = controller;
                 },
                ),
            ),
           ],
         ),
         floatingActionButton: FloatingActionButton(onPressed: () {

          double mq1 = MediaQuery.of(context).devicePixelRatio;
          String icon = "images/car.png";
          if (mq1>1.5 && mq1<2.5) {icon = "images/car2.png";}
          else if(mq1 >= 2.5){icon = "images/car3.png";}
          print("Mq 1"+mq1.toStringAsFixed(5));
          String iconPath="lib/assets/move@3x.png";


         mapController.addMarker(
              MarkerOptions(
                position: LatLng(37.4219999, -122.0862462),
                infoWindowText: InfoWindowText("TEST","TEST"),
                icon: BitmapDescriptor.fromAsset(iconPath),
                consumeTapEvents: true,

                /*builder: (context) =>(

                )*/

                //icon:BitmapDescriptor.fromAsset(assetName)
              ),
         );

         mapController.addMarker(
              MarkerOptions(
                position: LatLng(38.4219999, -122.0862462),
                infoWindowText: InfoWindowText("tt","adfaf"),
                icon: BitmapDescriptor.fromAsset("lib/assets/logo.png"),
                anchor: Offset(100,160),

                //icon:BitmapDescriptor.fromAsset(assetName)
              ),
         );

         mapController.animateCamera(
            CameraUpdate.newCameraPosition(
              CameraPosition(
                target: LatLng(37.4219999, -122.0862462),

                zoom: 15.0,
              ),
            ),
          );

        })
      );

  }

}
```
I have attached the image. The only work around I thought of now is to enable the infowindow open when I added every new marker but even that does not work. 
![image](https://user-images.githubusercontent.com/46325541/50720206-7c449200-10e3-11e9-95a1-859fcfbc393f.png)

**Comment by ebastuart** [comment]
Yes it would be great, if there will be a possibility to create dynamic custom markes e.g. "price tags"

**Comment by von-maurus** [comment]
I have the same questions about the properties of the markers. I think the infowindow is not a flutter widget, so cannot be done. 

Also, i want to ask, i want to display custom nearby locations for the user, from custom i mean that i dont want to display ALL the places inside the API, just the places that I want. (For example: only museums), I need something else? like the routes API or the Distance Matrix API? hope to find anserws, Thank you in advance

**Comment by sindhukrothapalli** [comment]
Any idea to fetch this scenario?

**Comment by tek08** [comment]
I kludged/solved this by creating a function which returned a `Future<BitmapDescriptor>`, whose returned and resolved value (the `BitmapDescriptor`) I then passed in as the `icon` when initializing a `Marker`:

Sorry to say that I don't remember why I padded the toImage(...) method with the magic 40 and 20 constants.  Probably calculated by visual test with what I was rendering at the time.

```
Future<BitmapDescriptor> createCustomMarkerBitmap(/* your args here */) async {

    PictureRecorder recorder = new PictureRecorder();
    Canvas c = new Canvas(recorder);

    /* Do your painting of the custom icon here, including drawing text, shapes, etc. */

    Picture p = recorder.endRecording();
    ByteData pngBytes = await (await p.toImage(
        tp.width.toInt() + 40, tp.height.toInt() + 20))
        .toByteData(format: ImageByteFormat.png);

    Uint8List data = Uint8List.view(pngBytes.buffer);
    
    return BitmapDescriptor.fromBytes(data);
}
```

Then when creating the marker, you can pass in the BitmapDescriptor as the `icon`, like so:

```
createCustomMarkerBitmap(...).then((BitmapDescriptor bitmapDescriptor) {
  _markers.add(new Marker(
    /*  in addition to your other properties: */
    icon: bitmapDescriptor,
  ));
});
```

or:

```
BitmapDescriptor bitmapDescriptor = await createCustomMarkerBitmap(...);

Marker marker = Marker(
  /*  in addition to your other properties: */
  icon: bitmapDescriptor
);
```


Let me know if that helps.  Gl!

**Comment by sindhukrothapalli** [comment]
> I kludged/solved this by creating a function which returned a `Future<BitmapDescriptor>`, whose returned and resolved value (the `BitmapDescriptor`) I then passed in as the `icon` when initializing a `Marker`:
> 
> Sorry to say that I don't remember why I padded the toImage(...) method with the magic 40 and 20 constants. Probably calculated by visual test with what I was rendering at the time.
> 
> ```dart
> Future<BitmapDescriptor> createCustomMarkerBitmap(/* your args here */) async {
> 
>     PictureRecorder recorder = new PictureRecorder();
>     Canvas c = new Canvas(recorder);
> 
>     /* Do your painting of the custom icon here, including drawing text, shapes, etc. */
> 
>     Picture p = recorder.endRecording();
>     ByteData pngBytes = await (await p.toImage(
>         tp.width.toInt() + 40, tp.height.toInt() + 20))
>         .toByteData(format: ImageByteFormat.png);
> 
>     Uint8List data = Uint8List.view(pngBytes.buffer);
>     
>     return BitmapDescriptor.fromBytes(data);
> }
> ```
> 
> Then when creating the marker, you can pass in the BitmapDescriptor as the `icon`, like so:
> 
> ```dart
> createCustomMarkerBitmap(...).then((BitmapDescriptor bitmapDescriptor) {
>   _markers.add(new Marker(
>     /*  in addition to your other properties: */
>     icon: bitmapDescriptor,
>   ));
> });
> ```
> 
> or:
> 
> ```dart
> BitmapDescriptor bitmapDescriptor = await createCustomMarkerBitmap(...);
> 
> Marker marker = Marker(
>   /*  in addition to your other properties: */
>   icon: bitmapDescriptor
> );
> ```
> 
> Let me know if that helps. Gl!

Sorry actually No!. I want marker with text same like in the picture with rounded rectangle attached to icon and text will be dynamic text.

**Comment by sindhukrothapalli** [comment]
> My code sample above can help you do that, but you have to do the drawing of the rounded rectangle + icon + text yourself. You can look at Flutter documentation to learn how to paint on Bitmaps using Canvas.

What is tp here?

**Comment by tek08** [comment]
Uff, I'm sorry about that.  That's a `TextPainter` object whose code I stripped out when writing this example for you.  Here's its use in the code:
```dart
    TextSpan span = new TextSpan(style: new TextStyle(
      color: Colors.white,
      fontSize: 35.0,
      fontWeight: FontWeight.bold,
    ), text: "Example Text");

    TextPainter tp = new TextPainter(
      text: span,
      textAlign: TextAlign.center,
      textDirection: TextDirection.ltr,
    );
    tp.layout();
    tp.paint(c, new Offset(20.0, 10.0));
```

where `c` is the `Canvas` defined above.  

So in this case, I'm using the size of the TextPainter object to determine the size of the `Image` (and then later, `ByteData`).  Just a way of automagically sizing the annotation based on the text supplied to it.  

Lemme know if you have any other questions.  Here to help.

**Comment by Dn-a** [comment]
Is there an alternative way to create tiles?

**Comment by osmantuzcu2** [comment]
> Uff, I'm sorry about that. That's a `TextPainter` object whose code I stripped out when writing this example for you. Here's its use in the code:
> 
> ```dart
>     TextSpan span = new TextSpan(style: new TextStyle(
>       color: Colors.white,
>       fontSize: 35.0,
>       fontWeight: FontWeight.bold,
>     ), text: "Example Text");
> 
>     TextPainter tp = new TextPainter(
>       text: span,
>       textAlign: TextAlign.center,
>       textDirection: TextDirection.ltr,
>     );
>     tp.layout();
>     tp.paint(c, new Offset(20.0, 10.0));
> ```
> 
> where `c` is the `Canvas` defined above.
> 
> So in this case, I'm using the size of the TextPainter object to determine the size of the `Image` (and then later, `ByteData`). Just a way of automagically sizing the annotation based on the text supplied to it.
> 
> Lemme know if you have any other questions. Here to help.

Hi there, This is working for me but I can't add a png image behind the text. Please give an example. (My png is from asset)

**Comment by hussenIbrahim** [comment]
https://github.com/hussenIbrahim/Flutter_GoogleMap_customMarkerWindow


look at this example
![screenshoot](https://user-images.githubusercontent.com/62293873/83172944-00584900-a121-11ea-8cbe-81df7d8dd9a5.jpg)

**Comment by xOldeVx** [comment]
> I kludged/solved this by creating a function which returned a `Future<BitmapDescriptor>`, whose returned and resolved value (the `BitmapDescriptor`) I then passed in as the `icon` when initializing a `Marker`:
> 
> Sorry to say that I don't remember why I padded the toImage(...) method with the magic 40 and 20 constants. Probably calculated by visual test with what I was rendering at the time.
> 
> ```dart
> Future<BitmapDescriptor> createCustomMarkerBitmap(/* your args here */) async {
> 
>     PictureRecorder recorder = new PictureRecorder();
>     Canvas c = new Canvas(recorder);
> 
>     /* Do your painting of the custom icon here, including drawing text, shapes, etc. */
> 
>     Picture p = recorder.endRecording();
>     ByteData pngBytes = await (await p.toImage(
>         tp.width.toInt() + 40, tp.height.toInt() + 20))
>         .toByteData(format: ImageByteFormat.png);
> 
>     Uint8List data = Uint8List.view(pngBytes.buffer);
>     
>     return BitmapDescriptor.fromBytes(data);
> }
> ```
> 
> Then when creating the marker, you can pass in the BitmapDescriptor as the `icon`, like so:
> 
> ```dart
> createCustomMarkerBitmap(...).then((BitmapDescriptor bitmapDescriptor) {
>   _markers.add(new Marker(
>     /*  in addition to your other properties: */
>     icon: bitmapDescriptor,
>   ));
> });
> ```
> 
> or:
> 
> ```dart
> BitmapDescriptor bitmapDescriptor = await createCustomMarkerBitmap(...);
> 
> Marker marker = Marker(
>   /*  in addition to your other properties: */
>   icon: bitmapDescriptor
> );
> ```
> 
> Let me know if that helps. Gl!

Can you give a code example for:

**Do your painting of the custom icon here, including drawing text, shapes, etc..** ?

In my case i don't need to paint an icon with code, i have one simple icon (location icon), and i need to paint a number inside it

**Comment by tek08** [comment]
> Can you give a code example for:
> 
> **Do your painting of the custom icon here, including drawing text, shapes, etc..** ?
> 
> In my case i don't need to paint an icon with code, i have one simple icon (location icon), and i need to paint a number inside it

Sure thing.  For something similar to your case, I used `paintImage` and `TextPainter`, which I believe are both part of `package:flutter/widgets.dart`.  Example stripped from some old code I have:

```dart
 import 'dart:ui' as ui;

...

int IMAGE_WIDTH = 45;
int IMAGE_HEIGHT = 45;

AssetBundle bundle = DefaultAssetBundle.of(context);
ui.Image myImage = await Util.getUiImage(bundle, "assets/images/image.png", IMAGE_WIDTH, IMAGE_HEIGHT);

paintImage(
    canvas: c,  // c is the Canvas object in above code examples.
    image: myImage,
    rect: Rect.fromLTWH(0, 0, IMAGE_WIDTH, IMAGE_HEIGHT));

TextPainter textPainter = new TextPainter(
    text: TextSpan(
        style: new TextStyle(
          color: Colors.black,
          fontSize: 24.0,
          fontWeight: FontWeight.bold,
          fontFamily: "Helvetica Neue",
        ),
        text: "Number Can Go Here"),
    textDirection: TextDirection.ltr);

textPainter.layout();

textPainter.paint(c, Offset(0, 0));   // c is the Canvas object
```

Mess around with the offsets and sizes as need be.  Hope this helps.

-P

**Comment by pedromassangocode** [comment]
This is still a valid proposal as of:

```yaml
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
```

**Comment by NirmalScaria** [comment]
The (dirty, but right) way is to use Canvas and do the painting manually. But if you just want text on marker, as a label (or a tag), this should do the job.

[https://pub.dev/packages/label_marker](https://pub.dev/packages/label_marker)

Just go through the overview once and you can see if it is for you or not. I really hope it helps. And yeah. I made it :)

**Comment by stuartmorgan** [comment]
I don't think there's anything actionable at the package level here that's distinct from https://github.com/flutter/flutter/issues/24213, since being able to control layout, style, etc. requires arbitrary drawing, so closing as a duplicate.
