### ISSUE TITLE
RuntimeError: /usr/local/opt/libtool not present or broken

### ISSUE THREAD

**Issue by Alan201601** [flutter/flutter#26111]
when i run flutter doctor, then there is some error about iOS toolchain
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.0)

when i run brew install --HEAD usbmuxd ,there is error:

Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/libtool not present or broken
Please reinstall libtool. Sorry :(

**Comment by kangwang1988** [comment]
@Alan201601 
Sad to hear that, however, it seems to be a libimobiledevice related problem.
I think [https://stackoverflow.com/tags/flutter](https://stackoverflow.com/tags/flutter) should be a better place to ask this kind of flutter support questions.
Closing this issue now. Feel free to file new issues if you find other flutter problems.
