### ISSUE TITLE
NoSuchMethodError: The getter 'name' was called on null.

### ISSUE THREAD

**Issue by ChengPengGao** [flutter/flutter#26110]
```
chengpengdeMacBook-Pro:uniubi_cash_system chengpenggao$ flutter packages pub run build_runner clean
[INFO] Generating build script...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      _findBuilderApplications.<anonymous closure> (package:build_runner/src/build_script_generate/build_script_generate.dart:57:47)
#2      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:45:24)
#3      stronglyConnectedComponents.strongConnect (package:graphs/src/strongly_connected_components.dart:47:22)
#4      stronglyConnectedComponents (package:graphs/src/strongly_connected_components.dart:67:55)
#5      _findBuilderApplications (package:build_runner/src/build_script_generate/build_script_generate.dart:56:27)
<asynchronous suspension>
#6      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:28:26)
<asynchronous suspension>
#7      logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
<asynchronous suspension>
#8      generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:25:5)
#9      generateAndRun (package:build_runner/src/build_script_generate/bootstrap.dart:44:31)
<asynchronous suspension>
#10     main (file:///Users/chengpenggao/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.1.2/bin/build_runner.dart:61:28)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
pub finished with exit code 255
```

**Comment by kangwang1988** [comment]
Please paster full log for `flutter -v doctor -v`.
Besides, it would be helpful if you can create a minimal demo project which can reproduce this problem.

@ChengPengGao

**Comment by ChengPengGao** [comment]
chengpengdeMacBook-Pro:uniubi_cash_system chengpenggao$ flutter -v doctor -v
[  +30 ms] executing: [/Users/chengpenggao/Downloads/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/chengpenggao/Downloads/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] executing: [/Users/chengpenggao/Downloads/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/chengpenggao/Downloads/flutter/] git log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/chengpenggao/Downloads/flutter/] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 weeks ago
[        ] executing: [/Users/chengpenggao/Downloads/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +164 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +75 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.2
[ +210 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +57 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.2
[  +84 ms] java -version
[ +408 ms] executing: idevice_id -h
[   +8 ms] executing: idevice_id -h
[   +8 ms] executing: ideviceinfo -u 00008020-001C2D903C42002E
[   +8 ms] executing: pod --version
[ +122 ms] [✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[   +1 ms]     • Flutter version 1.0.0 at /Users/chengpenggao/Downloads/flutter
[        ]     • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
[        ]     • Engine revision 7375a0f414
[        ]     • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
⣾[   +2 ms] executing: /Users/chengpenggao/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/chengpenggao/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           TL0218AH00025          device usb:336592896X product:T2lite model:T2lite device:T2lite transport_id:3
[   +8 ms] executing: idevice_id -h
[  +63 ms] No device found with udid 00008020-001C2D903C42002E, is it plugged in?
[   +1 ms] executing: idevice_id -l
[  +10 ms] /usr/bin/xcrun simctl list --json devices
[ +282 ms] /Users/chengpenggao/Library/Android/sdk/platform-tools/adb -s TL0218AH00025 shell getprop                                                                                            ⣽[  +25 ms] executing: /Users/chengpenggao/Library/Android/sdk/tools/bin/sdkmanager --licenses
[   +7 ms] executing: ideviceinstaller -h                                                                                                                                                       ⣻[  +37 ms] executing: ios-deploy --version
[  +26 ms] ro.hardware = qcom
[   +4 ms] executing: ios-deploy --version                                                                                                                                                      ⢿[  +29 ms] 1.9.4
[   +1 ms] executing: ios-deploy --version
[  +26 ms] executing: ios-deploy --version
[  +20 ms] 1.9.4                                                                                                                                                                                ⡿[ +107 ms] 1.5.3                                                                                                                                                                                [+3013 ms] [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[        ]     • Android SDK at /Users/chengpenggao/Library/Android/sdk
[        ]     • Android NDK at /Users/chengpenggao/Library/Android/sdk/ndk-bundle
[        ]     • Platform android-28, build-tools 28.0.3
[        ]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ]     • All Android licenses accepted.
[        ] [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 10.1, Build version 10B61
[        ]     • ios-deploy 1.9.4
[        ]     • CocoaPods version 1.5.3
[        ] [✓] Android Studio (version 3.2)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Flutter plugin version 31.3.1
[        ]     • Dart plugin version 181.5656
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
[        ] [✓] Connected device (1 available)
[        ]     • T2lite • TL0218AH00025 • android-arm64 • Android 7.1.1 (API 25)
[        ] • No issues found!
[   +9 ms] "flutter doctor" took 4,781ms.
chengpengdeMacBook-Pro:uniubi_cash_system chengpenggao$ 
I don't have a clue.囧

**Comment by kangwang1988** [comment]
@ChengPengGao 

![image](https://user-images.githubusercontent.com/817851/50724109-de70b780-1122-11e9-91a5-7dc944554f1b.png)

The error seems resulting from this code.

You may need to create a minimal demo project which can help reproduce the issue.

**Comment by zoechi** [comment]
I think this should be reported on https://github.com/dart-lang/build
As a workaround it's probably enough to delete the `.dart-tool/build` directory in your project.
