### ISSUE TITLE
Strange behavior on flutter stable channel

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#26116]
Lately I am getting strange error on my project. Didn't get before on same project

**Error Lines:**

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/Choreographer( 8473): Skipped 104 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 8473): eglMakeCurrent: 0xf15b2120: ver 3 0 (tinfo 0xd1f1b050)
Syncing files to device Android SDK built for x86...
I/flutter ( 8473): en_US
D/        ( 8473): HostConnection::get() New Host Connection established 0xe9712b00, tid 8524
D/EGL_emulation( 8473): eglMakeCurrent: 0xf1665700: ver 3 0 (tinfo 0xe9703470)
I/zygote  ( 8473): Do partial code cache collection, code=30KB, data=25KB
I/zygote  ( 8473): After code cache collection, code=30KB, data=25KB
I/zygote  ( 8473): Increasing code cache capacity to 128KB
E/flutter ( 8473): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 8473): 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 683 pos 12: 'pixels != null': is not true.
E/flutter ( 8473): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter ( 8473): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter ( 8473): #2      ScrollPosition.dispose (package:flutter/src/widgets/scroll_position.dart:683:12)
E/flutter ( 8473): #3      ScrollPositionWithSingleContext.dispose (package:flutter/src/widgets/scroll_position_with_single_context.dart:255:11)
E/flutter ( 8473): #4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 8473): #5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Flutter Doctor -v**

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale tr-CY)
    • Flutter version 1.0.0 at /users/niyazitoros/flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK at /Users/niyazitoros/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

```

**Comment by kangwang1988** [comment]
@NTMS2017 
Please create a minimal demo project which can help reproduce this problem.

**Comment by zoechi** [comment]
Might be #18756, #21630

**Comment by NTMS2017** [comment]
I didn't check the other issues that you provided as a link. 

For demo app I modified the https://startflutter.com/themes/438/ Login page. When I tab the login button, I send my user credentials to server. And my credentials is true than I enter the home page. 

To enter home page I used Navigator.pushAndRemoveUntil. When I change that to Navigator.push then error is gone.

I am not sure what this happened suddenly but last 2 months it is working with Navigator.pushAndRemoveUntil.

**Comment by zoechi** [comment]
> I am not sure what this happened suddenly but last 2 months it is working with `Navigator.pushAndRemoveUntil`.

Does this mean you can't reproduce anymore?

**Comment by NTMS2017** [comment]
Hi zoechi,

Yes I can reproduce. All I have to do is (as in given example https://startflutter.com/themes/438/ Login page) replace the Navigator.push with Navigator.pushAndRemoveUntil.


**Works:**   onPressed: () => and use Navigator.push
**Error:** onPressed: () => and use Navigator.pushAndRemoveUntil.

```
child: MaterialButton(

                    highlightColor: Colors.transparent,

                    splashColor: Theme.Colors.loginGradientEnd,

                    //shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(5.0))),

                    child: Padding(

                      padding: const EdgeInsets.symmetric(

                          vertical: 10.0, horizontal: 42.0),

                      child: Text(

                        "LOGIN",

                        style: TextStyle(

                            color: Colors.white,

                            fontSize: 25.0,

                            fontFamily: "WorkSansBold"),

                      ),

                    ),

                    onPressed: () =>

                        showInSnackBar("Login button pressed")),

              ),
```

**Comment by NTMS2017** [comment]
I didn't close the issue because I am not sure might be my way of things is wrong or the actually some bug under it.

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by nemorystudios** [comment]
I am having the same exact issue when using pushNamedAndRemoveUntil()

**Comment by nemorystudios** [comment]
I believe this error happens if  Navigator.of(context).pop() was called before pushNamedAndRemoveUntil() 

I just fixed mine. so please check yours

**Comment by nemorystudios** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  How can I help you?                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: January 28, 2019 2:39 PMTo: flutter@noreply.github.comReply-to: reply@reply.github.comCc: nemorystudios@gmail.com; comment@noreply.github.comSubject: Re: [flutter/flutter] Strange behavior on flutter stable channel (#26116)  thanks, in my code I just call pushNamedAndRemoveUntil(). Should I call Navigator.of(context).pop() after that?
