### ISSUE TITLE
package for including open source notices

### ISSUE THREAD

**Issue by neerajyadav** [flutter/flutter#26112]
Is there any pub package which can pull out open source licenses of the packages used in flutter app and display them on a screen? Kind of building **Open source licenses** page in app. Android has [`oss-licenses-plugin`](https://developers.google.com/android/guides/opensource)

**Comment by kangwang1988** [comment]
@neerajyadav 
Please try [https://pub.dartlang.org](https://pub.dartlang.org/packages) 
and other channels available at [https://flutter.io/community](https://flutter.io/community)

Github issue is used to track bugs and file feature requests.

Closing this issue now.

**Comment by neerajyadav** [comment]
Tried pub.dartlang.org already. Didn't find anything like this. I think it will be a good to have package. Almost all the apps have Package License page.
