### ISSUE TITLE
Xcode codesigning error is not specific, always says "Try replacing 'com.example' with your signing id in Xcode"

### ISSUE THREAD

**Issue by seamusmc** [flutter/flutter#26123]
## Debug Console Output
```
Launching lib/main.dart on Seamus' iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: James McGowan (94DETY4LLB)"
Xcode build done.                                            4.4s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
/Users/seamus_mcgowan/Documents/Projects/Flutter/repro/build/ios/Debug-iphoneos/Runner.app: resource fork, Finder information, or similar detritus not allowed
Command /usr/bin/codesign failed with exit code 1
Could not build the precompiled application for the device.

It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace

Error launching application on Seamus' iPhone.
Exited (sigterm)
```
## Observations
VSCode 1.31 XCode 10.1

A couple issues with the output and flutter/dart's suggested fix:
1. I can't consistently reproduce this problem, the first 5 projects I created all exhibited this behavior, then when I tried creating projects to reproduce the problem to submit this, I couldn't reproduce. Now I am seeing it reproduced again. (Yay for the joys of build)
2. As far as I'm aware the default **bundle identifier**, ('com.example'), will never cause a build to break. My observation is that the
```
It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
```
message is used for any problems with code signing. As it happens the Team Id has not been set in the XCode project. Please display a more appropriate message, it'll just waste time especially since the misleading text is in bright red while the rest of the log is in grey.

3. As I mentioned this doesn't happen all the time, when the build succeeds, I open the XCode workspace and the Team is not set. No idea how this works ... yet.
4. The more important issue is: 

>/Users/seamus_mcgowan/Documents/Projects/Flutter/repro/build/ios/Debug-iphoneos/Runner.app: resource fork, Finder information, or similar detritus not allowed

This is a common problem and isn't a problem with flutter directly, but the image resources used in the generated project. This is a security hardening change that was introduced with iOS 10, macOS Sierra, watchOS 3, and tvOS 10.

Code signing no longer allows any file in an app bundle to have an extended attribute containing a resource fork or Finder info.

Please update the images used in the generated projects to not have attributes.

The work around is to run `xattr -cr <path_to_app_bundle>` from the root of the project.

Again this issue is not reproducible for all new projects. 

## Steps to Reproduce

0. Connect iPhone to Mac and login to prep for deployment
1. From VSCode use the Flutter: New Project command.
2. Enter myapp for the project name, let Flutter build the project files
3. Press F5 to build and deploy the project

## Work Around

1. Run `xattr -cr <path_to_app_bundle>` from the root of the project.
2. Open the project's workspace in XCode 10, set the Team in the projects signing section
3. Set the XCode project format to 10.0. I could not get flutter to build the project, for debug, in vscode without this step! The default is 3.2 so I'm not sure if setting it to 9.3 will work.
4. In XCode select the Product/Clean menu option to clean the XCode project
5. In VSCode's terminal type flutter clean to clean the flutter project
6. In VSCode press F5 to debug and deploy the app to an iOS device. 
7. I want to reiterate their are times I can create a new project in VSCode and hit F5 and it just works. I open the XCode workspace and all the defects I've listed above are still there. But when it doesn't work I have to do the above steps to get it to build and deploy with F5 from VSCode. 
8. To add to the confusion: I'm always able to run build and deploy from XCode without issue, making no changes to the project, (after building with flutter in VSCode). <boggle>

## Logs

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/seamus_mcgowan/Flutter
    • Framework revision 5391447fae (5 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/seamus_mcgowan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Seamus' iPhone • deb505af77f116bc6e4c38f89cbe5f3e1779bf58 • ios • iOS 12.1.2

• No issues found!
```

**Comment by aytunch** [comment]
@seamusmc I have got the same problem and I will try your work around but I don't know what you mean by <path_to_app_bundle>? Can you elaborate?

**Comment by LachlanGorst** [comment]
What worked for me was going to Target: Runner in Xcode,
![Screen Shot 2019-04-09 at 2 42 40 pm](https://user-images.githubusercontent.com/47423422/55773811-c28c0180-5ad5-11e9-9115-9a9c1c432c26.png)
And then replacing com.example in the Bundle Identifier with the email in my Signing Certificate.
![Screen Shot 2019-04-09 at 2 40 09 pm](https://user-images.githubusercontent.com/47423422/55773742-6cb75980-5ad5-11e9-99f0-dfb8d446a948.png)
Then building in Xcode. Hope this helps you too.

**Comment by Lwin-Ko** [comment]
How can I find Targets & Signing Certificate in Xcode?

**Comment by LachlanGorst** [comment]
> How can I find Targets & Signing Certificate in Xcode?

Click on the project navigator -> Runner -> Targets: Runner -> and then Signing Certificate is in the General tab.

**Comment by Lwin-Ko** [comment]
My Xcode Version is 10.1 and I couldn't find it.

**Comment by octaviou** [comment]
Type on the search field: certificate and you'll find it.

**Comment by octaviou** [comment]
> My Xcode Version is 10.1 and I couldn't find it.

Type on the search field: certificate and you'll find it

**Comment by ride4sun** [comment]
I have the same Issue: 
My build output in Android Studido is this:
```
Launching lib/main.dart on Jay’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8W3Z37J9J8
Running Xcode build...
Xcode build done.                                           10.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/jay/Desktop/Projects/license_test/build/ios/Debug-iphoneos/Runner.app/Frameworks/App.framework: errSecInternalComponent
    Command CodeSign failed with a nonzero exit code
    /Users/jay/Desktop/Projects/license_test/build/ios/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework: replacing existing signature
    /Users/jay/Desktop/Projects/license_test/build/ios/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework: errSecInternalComponent
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on Jay’s iPhone.
```

I followed the advise @LachlanGorst ```And then replacing com.example in the Bundle Identifier with the email in my Signing Certificate.```
In the case my email is myemail@whatever.com than the Bundle 
Identifier should be `ride4sun-gmail.com.licenseTest ` right?

**Comment by francomacri17** [comment]
> What worked for me was going to Target: Runner in Xcode,
> ![Screen Shot 2019-04-09 at 2 42 40 pm](https://user-images.githubusercontent.com/47423422/55773811-c28c0180-5ad5-11e9-9115-9a9c1c432c26.png)
> And then replacing com.example in the Bundle Identifier with the email in my Signing Certificate.
> ![Screen Shot 2019-04-09 at 2 40 09 pm](https://user-images.githubusercontent.com/47423422/55773742-6cb75980-5ad5-11e9-99f0-dfb8d446a948.png)
> Then building in Xcode. Hope this helps you too.

This working for me, Thanks!

**Comment by jmagman** [comment]
> As it happens the Team Id has not been set in the XCode project

That would matter running from Xcode, but not from `flutter run` since it was already using your Team ID: `iPhone Developer: James McGowan (94DETY4LLB)` from the `flutter config ios-signing-cert` you previously set.  You've hit a different codesigning issue.

> As far as I'm aware the default bundle identifier, ('com.example'), will never cause a build to break.

If the bundle identifier isn't associated with your Team ID 94DETY4LLB then you will see code-signing issues.  To debug what you were hitting, we would need to see the output Xcode error output of `flutter run -v` to know if it was "misleading" (unfortunately because of https://github.com/flutter/flutter/issues/22536).

> Runner.app: resource fork, Finder information, or similar detritus not allowed

We're tracking that with https://github.com/flutter/flutter/issues/49290 (you filed this one first, but that one is more targeted).

**Comment by 68strat** [comment]
here is my error.  its frustrating.  I don't know how to solve it, would love some help, thanks!

-iphoneos/Runner.app: resource fork, Finder information, or similar detritus not allowed
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on Chuck’s iPhone.

**Comment by 68strat** [comment]
<img width="912" alt="Screen Shot 2020-04-09 at 4 46 12 PM" src="https://user-images.githubusercontent.com/34894784/78949838-b7b9d300-7a81-11ea-9f85-89c696072b80.png">

**Comment by jmagman** [comment]
@68strat We're tracking that in #49290, not this issue.  Please refer to it for workarounds related to `xattr`.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
