### ISSUE TITLE
Add an api to release all memory allocated by Flutter

### ISSUE THREAD

**Issue by lext-7** [flutter/flutter#26122]
Is there an api to release all memory allocated by Flutter as my app only has a flutter view which is not frequently used ? 
I want to release these memory after this view is destroyed as Flutter takes up a lot of memory.

**Comment by kangwang1988** [comment]
@lext-7
It's supposed that the flutter related memory would be released if you‘ve released all flutter related instances. For example，FlutterViewController for iOS,FlutterView/FlutterNativeView
for android.If you’ve released all those instances, however the memory remains, please create a minimal demo to help reproduce it. thanks

Besides, paste full log for ‘flutter -v doctor -v’ here.

**Comment by lext-7** [comment]
You can create a demo following [this article](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) in iOS. Add some code at the end of the `handleButtonAction`  function: 

```objc
dispatch_time_t delay = dispatch_time(DISPATCH_TIME_NOW, NSEC_PER_SEC * 10);
dispatch_after(delay, dispatch_get_main_queue(), ^(void){
    [self dismissViewControllerAnimated:YES completion:^{
    }];
});
```

Then you can see: the memory is increasing a lot every time you enter the flutter view but doesn't reduce a lot after you exit the view.

As far as I know, the dart vm is a global singleton instance, there is no way to shutdown it. I try to call `minikin::Layout::purgeCaches()` which can reduce memory a lot. And there is no way to release the memory allocated for dart io and ui init.

I think there should be a more powerful api to release all memory allocated by Flutter. The memory both of before you enter flutter view and after you exit the view should be the same generally.

Flutter doctor log is as following:

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by eseidelGoogle** [comment]
This is very related to https://github.com/flutter/flutter/issues/16995, but I guess is a specific request for an API?

**Comment by kangwang1988** [comment]
Related to: https://github.com/flutter/flutter/issues/25255

**Comment by lext-7** [comment]
Close as there are already related issues. Thanks.
