### ISSUE TITLE
[plugin] firebase_messaging: onMessage, onResume and onLaunch should be Stream

### ISSUE THREAD

**Issue by axross** [flutter/flutter#26129]
📦 [firebase_messaging](https://pub.dartlang.org/packages/firebase_messaging) is really helpful to me. I'm grateful to the creator of this package, but I have more proper idea of API to receive/consume messages.

You know, there's Stream in Dart and almost all of similar things with these are made of Stream. I think `FirebaseMessaging#configure()` should be deleted and replaced with the API like following instead.

- `FirebaseMessaging`
    - `Stream<Map<String, dynamic>> get FirebaseMessaging.onMessage`
    - `Stream<Map<String, dynamic>> get FirebaseMessaging.onResume`
    - `Stream<Map<String, dynamic>> get FirebaseMessaging.onLaunch`

I just want to know what you think about this idea. Thank you for your reading.

Also here is wrapper to handle messages with Stream (for now): https://gist.github.com/axross/1f5129204ae9ab0b75e491ddf3702d90

**Comment by zoechi** [comment]
Flutter generally doesn't use Streams for callbacks because they are considered too expensive 
for framework code.
It should be easy enough to convert that to a `Stream` though.

**Comment by axross** [comment]
Thank you for the information.

But I don't think firebase_messaging package is low-layer library. It's SDK. And Flutter SDK is supposed to able to handle Stream well. There's various good APIs with Stream and BLoC patten in Flutter world.

**Comment by axross** [comment]
Thank you to add this matter to a milestone.

I think this thing still needs your opinions, for example what form of API is appropriate. Please tell us if someone has any opinion!

**Comment by kroikie** [comment]
@axross

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/520. Any further collaboration will be done there.
