### ISSUE TITLE
Allow dart:mirror for dev dependencies

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#26125]
Yet another issue about `dart:mirror`

While I understand that `dart:mirror` should stay disabled for everything that is shipped with the app; I think it would be interesting to allow it for _everything else_. 

For instance, a package of mine is stuck in a weird position:
- It uses `source_gen` and `build_runner` to generate sources, so depends on `dart:mirror`
- The generated sources depend on Flutter, so it needs a dependency on Flutter for tests. 

This is entirely fine, because the package is meant to be used as a dev dependency, and the generated sources do not use `dart:mirror`. 
But as of now, this is something not doable and I am forced to remove the Flutter dependency from the package. Which means that there's an entire set of features that I cannot cover with tests. 

A typical example of a feature I'm trying to test is https://github.com/rrousselGit/functional_widget generating an override of `debugFillProperties`.

**Comment by jonahwilliams** [comment]
>It uses build to generate sources, so depends on dart:mirror

build does not require a dependency on mirrors. In fact, it provides an analyzer based API for analysis and codegen.

**Comment by rrousselGit** [comment]
Overall this is not so much about _what_ package cause the issue, but where it is caused.

For instance `json_serializable` has an internal small testing framework, but it uses dart:mirror to get the location of the current file.


Another use-case is that it would allow using dart2json within tests on _any_ class. This can be very useful to implement something similar to jest snapshot testing.

**Comment by jonahwilliams** [comment]
There are many things that can be done with mirrors - they can also be done with scripts and the analyzer APIs provided by through the `build*` packages. Fundamentally this is the same issue as https://github.com/flutter/flutter/issues/1150, the fact that code is only intended to be run as a development dependency is only incidental.
