### ISSUE TITLE
Wrong spaceAround in a Row

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter#26121]
Hi everyone, why is spacearound spacing both between the childrens and out of the childrens ?
Wasn't just out of the childrens ?

## Steps to Reproduce

1. Create a new project with flutter 1.1.5
2. Insert a Row in a widget
3. Set mainAxisAlignment to spaceAround

```
[✓] Flutter (Channel dev, v1.1.5, on Mac OS X 10.14.2 18C54, locale it-IT)
    • Flutter version 1.1.5 at /Users/nicolas/dev/flutter_sdk/flutter
    • Framework revision 63b2daff7f (8 days ago), 2018-12-28 10:43:06 -0800
    • Engine revision f0a1d6f91d
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 d1817ddc91)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nicolas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    • IntelliJ at /Users/nicolas/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

A screenshot that demonstrates the behavior that you would like to have changed would be helpful as well.

**Comment by nicolasvac** [comment]
Example code: 
`import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: "Simple test",
    theme: ThemeData(
      brightness: Brightness.dark,
    ),
    home: Test(),
  ));
}

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: Container(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                Icon(Icons.shopping_cart),
                Text('spaceAround done by flutter'),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Icon(Icons.shopping_cart),
                Text('spaceAround that should be'),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                Icon(Icons.shopping_cart),
                Text('Between'),
              ],
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                Icon(Icons.shopping_cart),
                Text('Evenly'),
              ],
            )
          ],
        ),
      ),
    );
  }
}
`

Am i wrong or has the behavior changed ?

**Comment by Hixie** [comment]
This is working exactly as I would expect:
![Screenshot_20200109-121950](https://user-images.githubusercontent.com/551196/72101836-7e36c780-32da-11ea-9363-4bf9d79c3ace.png)
