### ISSUE TITLE
release mode

### ISSUE THREAD

**Issue by Avon98** [flutter/flutter#26138]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by anondev32** [comment]
This is an issue with your code not flutter. The log says everything you need to know to fix it.

**Comment by zoechi** [comment]
> flutter build apk --relase

It should be `flutter build apk --release` (missing e)

**Comment by Avon98** [comment]
no look at this again not solved
D:\release>flutter build apk --release
Initializing gradle...                                           2.2s
Resolving dependencies...                                        6.4s
Gradle task 'assembleRelease'...

Compiler message:
file:///C:/flutter/packages/flutter/lib/src/widgets/form.dart:125:8: Error:
The return type of the
method 'FormState::save' is void, which does not match the return type of
the overridden method (dart.core::String).
Change to a subtype of dart.core::String.
  void save() {
       ^
file:///C:/flutter/packages/flutter/lib/src/widgets/framework.dart:1337:10:
Context: This is the overridden method ('save').
  String save() {}
         ^
file:///C:/flutter/packages/flutter/lib/src/widgets/form.dart:289:8: Error:
The return type of the
method 'FormFieldState::save' is void, which does not match the return type
of the overridden method (dart.core::String).
Change to a subtype of dart.core::String.
  void save() {
       ^
file:///C:/flutter/packages/flutter/lib/src/widgets/framework.dart:1337:10:
Context: This is the overridden method ('save').
  String save() {}
         ^
Compiler terminated unexpectedly.
24.5s
Gradle task assembleRelease failed with exit code 1

D:\release>
