### ISSUE TITLE
Inaccurate translation

### ISSUE THREAD

**Issue by appoule** [flutter/flutter#26131]
Async UI
What is the equivalent of runOnUiThread() in Flutter?
Dart has a single-threaded execution model, with support for Isolates (a way to run Dart code on another thread), an event loop, and asynchronous programming. Unless you spawn an Isolate, your Dart code runs in the main UI thread and is driven by an event loop. Flutter’s event loop is equivalent to Android’s main Looper—that is, the Looper that is attached to the main thread.

**Comment by appoule** [comment]
想登录页面加评论，可半天也没登录上去，看到请给个别的联系方式。

**Comment by kangwang1988** [comment]
What's the original link you are talkinh about？

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
