### ISSUE TITLE
Add API to report missed frames

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#26154]
Production apps are interested in measuring jank in the field. I am opening a placeholder issue with the correct tags so we can discuss what metrics are requested and what can be provided.

So far we have heard:
- Average rendering time of frames.
- Number of missed frames (rendering time exceeded per-frame budget) in proportion to the total number of frames.

**Comment by hamiao123** [comment]
We use a rough way to measure fps in flutter release mode：
Calculate the interval between `handleBeginFrame` and `handleDrawFrame` （FrameCallback） , the frame will be considered drop if the interval exceeds 16.6ms.

**Comment by mehmetf** [comment]
@Hixie My understanding is that the most basic implementation needs to be based on sampling. Some API in the framework that developers can call periodically that reports missed frames *so far*:

```dart
int getMissedFrameCounter()
int getTotalFrameCounter()
void resetCounters()
```

These will satisfy the use cases I have heard. I guess this requires code?

**Comment by eseidelGoogle** [comment]
Do Android apps do this via the system or other mechanisms? Are there existing systems we can hook into instead of (in addition to?) building something custom for Flutter?

**Comment by nichtverstehen** [comment]
1. Primes implementation on Android uses FrameMetrics API:
https://developer.android.com/reference/android/view/FrameMetrics
See also primes/FrameMetricService.java file in G3 for the usage in Primes.

This should be usable, but I'm not 100% sure that it will correctly account the time to produce frames into SurfaceView.

2. `handleBeginFrame` and `handleDrawFrame` callbacks seem useful. We don't really need full timeline data for the missed frame measurement. Does `handleBeginFrame` effectively correspond to the vsync event coming from the system?

3. Is there anything in Flutter already calculating frame stats for any of build modes? What exactly is backing https://flutter-dashboard.appspot.com/?

**Comment by mehmetf** [comment]
This would be enough:

- \# of missed frames
- \# of total frames

**Comment by Hixie** [comment]
We track the total number of frames via `_profileFrameNumber` in SchedulerBinding (it's exported to the VM service but not to the API).

Can you define "missed frames"?

**Comment by mehmetf** [comment]
Client defined this as a frame whose "rendering time exceeded per-frame budget (I presume 16.67ms)".

Perhaps a more useful thing to keep track of would be a histogram of frame render times.

0-8ms
8-16ms
16-32ms
32-64ms
> 64ms

This also gives us a nice way of reporting missed frames if we were to target 120fps.

**Comment by liyuqian** [comment]
+1 for the histogram. Just measuring # of missed frames and # of total frames can sometimes be misleading: https://github.com/flutter/flutter/issues/18727

I also think that we can make the buckets more fine grained to get more information (16 buckets for 0-16ms, 8 buckets for 16-32ms, 4 buckets for 32-64ms, 2 buckets for 64-128ms, and 1 bucket for 128+ms). The update only takes O(1) time no matter how many buckets we have, and the space cost is quite low (e.g., 31 buckets only cost 31 ints).

**Comment by eseidelGoogle** [comment]
Reminds me of https://developer.mozilla.org/en-US/docs/Web/API/Performance

**Comment by Hixie** [comment]
Ok, tracking the time for each frame will have to be done in the engine since the framework doesn't have visibility into the time taken to actually render the frames.

The simplest API is probably a callback on `Window` that gets invoked every few frames with a `List<Duration>` giving the times each frame took since the last time the callback was invoked. Maybe `window.onFrameTimeReport`, with the signature `void Function(List<Duration> frameTimes)`. We can tune how often we call this to balance efficiency, memory usage for the buffer, and usefulness as a real-time metric; I'd probably fire it about once every 100 frames or so.

@mehmetf would that satisfy the needs of the customer?

@liyuqian is that something you would be willing to implement?

**Comment by mehmetf** [comment]
That sounds like a reasonable approach to collect the data.

I would still like the framework to deliver a histogram (Map<Bucket, int>) via an API rather than expecting consumers to subscribe to that callback directly. We should also give them an API to reset the histogram.

**Comment by liyuqian** [comment]
I can implement both the List frameTimes callback and the histogram API. According to our "[Lazy Programming Philosophy](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#lazy-programming)", should I only implement the histogram API first since no customers are asking or going to use the callback API yet?

**Comment by Hixie** [comment]
Our "[Layers](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#layers)" approach suggests we should do the callback API in the engine. We can then create a package (in our packages repo) that turns that into a histogram. (Doesn't have to be a part of the core framework.)

**Comment by mehmetf** [comment]
I wanted to give you all a heads up. I am talking to our performance monitoring infra team and they seem to believe that they can get jank monitoring for Flutter without Flutter having to expose any metrics. Their solution (on both iOS and Android) seem to operate on GPU buffer directly.

Pros of this approach as I see it: Consistent measurement infra (if it works) and a nice solution for add2app.

Cons: It only covers iOS and Android. I do think this is still important for Fuchsia and other targets but there's no request for it as far as I know.

**Comment by cbracken** [comment]
@liyuqian is this still planned for May 2019 release?

**Comment by liyuqian** [comment]
Good question! I'm trying to come up with a priority list today and see if it can be done in May (with the assumption that nothing more important will be inserted into the list before the end of May). My feeling is that there are many performance issues waiting (e.g., I just realized that there are [9 open performance regressions](https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22severe%3A+performance%22+label%3A%22severe%3A+regression%22+))...

**Comment by liyuqian** [comment]
Sorry, I have to extended the milestone as https://github.com/flutter/engine/pull/8983 still needs more reviews. I'll still aim for landing it as soon as possible so it should be done before the end of June.

**Comment by liyuqian** [comment]
Fixed by https://github.com/flutter/engine/pull/8983

**Comment by mehmetf** [comment]
@liyuqian quick question about this. Are these metrics available on release mode as well? I would image these are independent of the Dart VM and involve mostly Skia so I hope the answer is yes?

**Comment by liyuqian** [comment]
Yes
