### ISSUE TITLE
Add modifier functions to RawKeyEvent(Android)

### ISSUE THREAD

**Issue by JediBurrell** [flutter/flutter#26155]
`RawKeyEventAndroid` should have an equivalent function to `isCtrlPressed`, `isAltPressed`, and `isShiftPressed`.

**Comment by Hixie** [comment]
Why?

**Comment by JediBurrell** [comment]
@Hixie
For keyboard controls. The previous solution was not ideal, especially if you needed to check multiple keys.

If the “why’s” on the functions, I was  basing it off the current Android implementation. Greg’s solution (#26265) is much better.

**Comment by Hixie** [comment]
Got it. Thanks!
