### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by ChengPengGao** [flutter/flutter#26157]
```dart
 Column(
      children: <Widget>[
        Scaffold(
          
        appBar: AppBar(
          title: Text('TTTTTTTTtile'),
        ),
        ),
      Text('HHHHHHHHHHHHHHHHHHHHige')
      ],

    );
```
How should I write that Colmun can nest Scaffold

**Comment by zoechi** [comment]
`Scaffold` is not supposed to be nested.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
