### ISSUE TITLE
Can you develop a plugin that can use AE animation？

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#26156]
Can you develop a plugin that can use AE animation？

**Comment by zoechi** [comment]
I think you can create Lottie animations from After Effects 
https://pub.dartlang.org/packages?q=lottie

**Comment by 2534290808** [comment]
I checked that they are all platform plugins and it would be nice if they could render directly through SKIA

**Comment by zoechi** [comment]
@dnfield might be able to provide more insight

**Comment by dnfield** [comment]
Duplicate of https://github.com/flutter/flutter/issues/20438

There's definitely some interest in this, but it's likely a little ways out at this point.

**Comment by dnfield** [comment]
(Please upvote that issue if you'd like more attention paid to it)
