### ISSUE TITLE
The height of the AppBar is incorrect on IphoneX?

### ISSUE THREAD

**Issue by shingohu** [flutter/flutter#26163]
I want to use appbar anywhere, so I put the appbar in the body of the `Scaffold` instead of using the appbar property directly, but I find that the height of the appbar on IphoneX is not correct?

![1546838860565](https://user-images.githubusercontent.com/4944887/50750503-20fbd680-1280-11e9-8b8f-1244d7e7aaea.jpg)
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            AppBar(
              backgroundColor: Colors.amber,
              title: Text("Second AppBar"),
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by kyleDEVV** [comment]
How weird, care to add your `flutter doctor -v`?

**Comment by shingohu** [comment]
@zoechi @kyleDEVV 
the result of flutter doctor -v
[✓] Flutter (Channel master, v1.1.6-pre.11, on Mac OS X 10.14.1 18B75, locale
    zh-Hans-CN)
    • Flutter version 1.1.6-pre.11 at /Users/hujie/MEGA/Flutter/tool/flutter
    • Framework revision 53727866e6 (4 days ago), 2019-01-03 12:05:53 +0700
    • Engine revision 844c3274e6
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 88e6fe0f67)

**Comment by kyleDEVV** [comment]
Mind switching to the dev channel and reproducing?

**Comment by xster** [comment]
umm weird indeed. cc @HansMuller?

**Comment by shingohu** [comment]
@kyleDEVV Yes,The dev channel still has the same problem.You can try running the code above to reproduce this problem。
the dev channel version is 1.1.7

**Comment by wouterhardeman** [comment]
Not sure if this is intended but the AppBar should be specified in the `appBar` property of `Scaffold` not as a child in `Column`.

**Comment by tula-Intelads** [comment]
@shingohu I tried this and succeeded
`SafeArea(
                top: false,
                child: PreferredSize(
                  preferredSize: Size.fromHeight(kToolbarHeight),
                  child: AppBar(),
              ),
            ),`

**Comment by HansMuller** [comment]
@tula-Intelads that's a reasonable workaround. With the exception of the app bar's flexibleSpace, all of its content is wrapped in a SafeArea, which moves the content below the notch. 

This isn't documented and the appbar layout you're after should be straightforward. Sorry about all that.

**Comment by timsneath** [comment]
Can repro on the latest 1.12 build.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
@HansMuller How about something simple like this to fix it? https://github.com/flutter/flutter/pull/48761

Or maybe we're looking for a bigger fix or just a documentation change.

**Comment by Ahmadre** [comment]
I read the whole thread, but why would you want to use the appBar somewhere else? Have we any useful or productive use case? The question is: why don't you create your own custom widget? If you need same functionalities try Material as your parent widget and you should succeed :)

**Comment by volgin** [comment]
The difference is 24.0 pixels. Here is a workaround (hopefully, temporary):

double _appBarHeight =
        _appBar.preferredSize.height + MediaQuery.of(context).padding.top - 20;
