### ISSUE TITLE
Flutter & Flutter Engine run-time dependencies?

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#26168]
I'm working on a custom Flutter Embedder, and I'm seeing some odd things as I change between Flutter repo releases.  Launching a simple example bundle built with v1.1.2 I get:

`[ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!`

Launching the same example bundle built with v1.1.5 I get:

`[ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.`

This is running very near tip of master for Flutter Engine.

Are there run-time version dependencies between Flutter Flutter and Flutter Engine?

If so - in a nutshell, what are they?

Joel

**Comment by kangwang1988** [comment]
As to the `Could not get cmap table size!` problem, refer to: #26108 
As to the second one, In my understanding, it usually mean that the kernel-compiler's version doesn't match the dart jit interpreter version.
To solve this, make sure the compiler(with a version) and interpreter(with a version) match, and clean the intermediate products before rebuilding.
@jwinarske

**Comment by jwinarske** [comment]
I just figured out the solution for `Could not get cmap table size!` after single stepping through the Engine.  It's unrelated to your reference.  Also note this only works for me with v1.1.2, as I hit the kernel bin issue with v1.1.5.  Perhaps there is an internal Engine branch where mainline merges are lagging?  The correlation between Flutter release tags and Engine commits should be documented somewhere.  I would say this is an action item...

### ***Could not get cmap table size!***
**Problems**
1.  The Skia font manager points to /usr/local/fonts. See SkFontMgr::RefDefault() in src/third_party/skia/src/core/SkFontMgr.cpp.

2.  The default font for Linux is defined in src/flutter/third_party/txt/src/txt/platform.cc, which is selected in src/flutter/third_party/txt/BUILD.gn.

**Solution**
To avoid the below call stack, ensure /usr/local/fonts/Arial.ttf exists on the Linux target...

**Call stack**
```
Thread #6 [io.flutter.ui] 3285 [core: 3] (Suspended : Step)	
	minikin::FontFamily::computeCoverage() at FontFamily.cpp:184 0x7635104a	
	minikin::FontFamily::FontFamily() at FontFamily.cpp:112 0x76350f86	
	minikin::FontFamily::FontFamily() at FontFamily.cpp:103 0x76350f86	
	minikin::FontFamily::FontFamily() at FontFamily.cpp:100 0x76350f86	
	std::__1::__compressed_pair_elem<minikin::FontFamily, 1, false>::__compressed_pair_elem<std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> >&&, 0u>() at memory:2,148 0x76359f24	
	std::__1::__compressed_pair<std::__1::allocator<minikin::FontFamily>, minikin::FontFamily>::__compressed_pair<std::__1::allocator<minikin::FontFamily>&, std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> >&&>() at memory:2,251 0x76359f24	
	std::__1::__shared_ptr_emplace<minikin::FontFamily, std::__1::allocator<minikin::FontFamily> >::__shared_ptr_emplace<std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> > >() at memory:3,664 0x76359f24	
	std::__1::shared_ptr<minikin::FontFamily>::make_shared<std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> > >() at memory:4,323 0x76359f24	
	std::__1::make_shared<minikin::FontFamily, std::__1::vector<minikin::Font, std::__1::allocator<minikin::Font> > >() at memory:4,702 0x76359f24	
	txt::FontCollection::CreateMinikinFontFamily() at font_collection.cc:224 0x76359f24	
	txt::FontCollection::FindFontFamilyInManagers() at font_collection.cc:186 0x76359cb2	
	txt::FontCollection::GetMinikinFontCollectionForFamilies() at font_collection.cc:141 0x763598fa	
	txt::Paragraph::GetMinikinFontCollectionForStyle() at paragraph.cc:906 0x7635cdea	
	txt::Paragraph::ComputeLineBreaks() at paragraph.cc:290 0x7635c9d8	
	txt::Paragraph::Layout() at paragraph.cc:435 0x7635d4a2	
	blink::Paragraph::layout() at paragraph.cc:80 0x763814a2	
	tonic::DartDispatcher<tonic::IndicesHolder<0u>, void (blink::Paragraph::*)(double)>::Dispatch at dart_args.h:151 0x763814a2	
	tonic::DartCall<void (blink::Paragraph::*)(double)> at dart_args.h:204 0x763814a2	
	blink::Paragraph_layout() at paragraph.cc:36 0x763814a2	
	dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck() at native_entry.cc:197 0x764d4aec	
	0x713c0888	
```

**Comment by jwinarske** [comment]
Correct.  It boots to idle.

**Comment by kangwang1988** [comment]
In #26108 , GaryQian said:
```
I've seen that error before, but it usually ended up being an unrelated or non-flutter issue such as a corrupted font. I think that error occurs whenever a font is somehow improperly loaded and used. I can try to repro and look at it deeper.
```

I think it's a common issue when the font could be not loaded properly.
Just FYI.

**Comment by jwinarske** [comment]
Yes, and the default font varies depending on the platform.  

It would be a good thing to list these out in a platform section, of an Embedder FAQ...
