### ISSUE TITLE
Issue from website page JSON和序列化

### ISSUE THREAD

**Issue by jj89757hhb** [flutter/flutter#26166]
你好 我代码找不到 JSON类？String json = JSON.encode(user);

**Comment by zoechi** [comment]
You need to import `import 'dart:convert';`

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jj89757hhb** [comment]
没用呀 convert

**Comment by kangwang1988** [comment]
try "json" instead of "JSON".
Besides, use english (or a translator) please.

**Comment by jj89757hhb** [comment]
是的  小写就对了！ O(∩_∩)O谢谢
