### ISSUE TITLE
`flutter create` should set `sdk` version in `environment` to `>2.1.0`

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#26179]
`info: The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions. (sdk_version_async_exported_from_core at [flutter_25724_jumpto_0_refresh] lib/main.dart:26)`

![image](https://user-images.githubusercontent.com/405837/50770635-468cde00-1288-11e9-9daa-e974174c8036.png)

Currently created applications have
```
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
```
Changing it to 
```
environment:
  sdk: ">=2.1.0 <3.0.0"
```
would get rid of that hint.

```
[✓] Flutter (Channel master, v1.1.6-pre.37, on Mac OS X 10.14.1 18B75, locale en-AT)
```

See also https://github.com/dart-lang/sdk/issues/34978

**Comment by dnfield** [comment]
Fixed by #26235
