### ISSUE TITLE
flutter_webview plugin cannot use soft keyboard

### ISSUE THREAD

**Issue by taijuan** [flutter/flutter#26170]

**Comment by zoechi** [comment]
Can you please elaborate?

**Comment by zoechi** [comment]
Please also add the output of `flutter doctor -v`.

**Comment by taijuan** [comment]
> 
> 
> Please also add the output of `flutter doctor -v`.


$ flutter doctor -v                                                                                                                                                                                                [√] Flutter (Channel master, v1.1.6-pre.36, on Microsoft Windows [Version 10.0.17134.320], locale zh-CN)                                                                                                               • Flutter version 1.1.6-pre.36 at D:\flutter                                                                                                                                                                       • Framework revision 2e883f8552 (8 hours ago), 2019-01-06 16:38:13 -0800                                                                                                                                           • Engine revision 716185fb79                                                                                                                                                                                       • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)                                                                                                                                                                                                                                                                                                                                                                             [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)                                                                                                                                       • Android SDK at D:\android-SDK                                                                                                                                                                                    • Android NDK location not configured (optional; useful for native profiling support)                                                                                                                              • Platform android-28, build-tools 28.0.3                                                                                                                                                                          • ANDROID_HOME = D:\android-SDK                                                                                                                                                                                    • Java binary at: D:\Android Studio\jre\bin\java                                                                                                                                                                   • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)                                                                                                                                      • All Android licenses accepted.                                                                                                                                                                                                                                                                                                                                                                                                  [√] Android Studio (version 3.2)                                                                                                                                                                                       • Android Studio at D:\Android Studio                                                                                                                                                                              • Flutter plugin version 31.3.1                                                                                                                                                                                    • Dart plugin version 181.5656                                                                                                                                                                                     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)                                                                                                                                                                                                                                                                                                                                                     [√] Connected device (1 available)                                                                                                                                                                                     • HUAWEI VNS L31 • FUH7N16523001009 • android-arm64 • Android 7.0 (API 24)                                                                                                                                                                                                                                                                                                                                                        • No issues found!
--

**Comment by taijuan** [comment]
[√] Flutter (Channel master, v1.1.6-pre.36, on Microsoft Windows [Version 10.0.17134.320], locale zh-CN)
    ? Flutter version 1.1.6-pre.36 at D:\flutter
    ? Framework revision 2e883f8552 (8 hours ago), 2019-01-06 16:38:13 -0800
    ? Engine revision 716185fb79
    ? Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ? Android SDK at D:\android-SDK
    ? Android NDK location not configured (optional; useful for native profiling support)
    ? Platform android-28, build-tools 28.0.3
    ? ANDROID_HOME = D:\android-SDK
    ? Java binary at: D:\Android Studio\jre\bin\java
    ? Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ? All Android licenses accepted.

[√] Android Studio (version 3.2)
    ? Android Studio at D:\Android Studio
    ? Flutter plugin version 31.3.1
    ? Dart plugin version 181.5656
    ? Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    ? HUAWEI VNS L31 ? FUH7N16523001009 ? android-arm64 ? Android 7.0 (API 24) @zoechi

**Comment by taijuan** [comment]
> Can you please elaborate?

![default](https://user-images.githubusercontent.com/13415187/50944502-a32c0b00-14cb-11e9-827a-13baf00b44c7.gif)
**Click the input box in H5, the soft keyboard cannot be displayed**

**Comment by wouterhardeman** [comment]
@taijuan Just to check, is this on a live device or a simulator?

**Comment by taijuan** [comment]
@wouterhardeman 
Check on 2 devices.
HUAWEI VNS L31 • FUH7N16523001009 • android-arm64 • Android 7.0 (API 24)
HONOR LLD AL00 ? MKJNW18110002110 ? android-arm64 ? Android 8.0.0 (API 26)

**Comment by wouterhardeman** [comment]
@taijuan Which package are you using exactly? Any of these?

* [flutter_webview](https://pub.dartlang.org/packages/flutter_webview)
* [flutter_webview_plugin](https://pub.dartlang.org/packages/flutter_webview_plugin)
* [webview_flutter](https://pub.dartlang.org/packages/webview_flutter)

**Comment by taijuan** [comment]
@wouterhardeman I use webview_flutter: ^0.2.0

**Comment by mehmetf** [comment]
This is the same as https://github.com/flutter/flutter/issues/19718

**Comment by Steve-sy** [comment]
@taijuan its a bug in the official package, and we're waiting for update! you can use the community package for now " https://pub.dartlang.org/packages/flutter_webview_plugin "

**Comment by tidharnitzan** [comment]
@Steve-sy the community doesn't have javascriptChannels...which is a must in my scenario.
