### ISSUE TITLE
flutter format should support --line-length parameter

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#26175]
`dartfmt` supports it, `flutter format` should pass-through the value (if set).

**Comment by zoechi** [comment]
There's already a PR #23000

**Comment by hpoul** [comment]
fyi, i just thought about reopening this PR, just to discover it was already merged in another PR https://github.com/flutter/flutter/pull/36679 🎉️

**Comment by zanderso** [comment]
This looks done.
