### ISSUE TITLE
Stable and efficient API to have background isolates

### ISSUE THREAD

**Issue by joaoatgoogle** [flutter/flutter#26178]
We'd like to have the ability to efficiently run a "headless view" that just creates a Dart isolate in the Dart VM and runs non-Flutter code (but with support for plugins).

Motivation: we embed multiple FlutterViews in an existing app, that only run as long as their visual UI is being presented to the user. We'd like to leave some background, headless code running (e.g. for periodic background updates, etc). This isolate communicates with regular FlutterView isolates via a custom plugin.

We can achieve this today on Android by creating a FlutterNativeView, starting it up and never attaching it to a FlutterView. The request is to have a stable API to do this going forward, and to potentially make these isolates cheaper in their memory costs (e.g. by not having any Flutter bindings, for example).

**Comment by kangwang1988** [comment]
I think it's a common problem for flutter apps, no matter it's for a totally flutter application or "add to existing apps". @joaoatgoogle

**Comment by zoechi** [comment]
I think this is covered by #24278

**Comment by mehmetf** [comment]
@zoechi  You are right except for this point:

> to potentially make these isolates cheaper in their memory costs (e.g. by not having any Flutter bindings, for example).

#24278 is about out-of-box API support for background execution using a single isolate. Customer: dream wants to have a separate isolate and thus care about the overhead of each. I am not sure if we have any other issue that tracks that overhead.

**Comment by dnfield** [comment]
This should get better via the Android embedding refactor's @matthew-carroll  is working on

**Comment by xster** [comment]
I'm going to tentatively merge this into https://github.com/flutter/flutter/issues/32164. We're aware that this is a general theme we'll need to hash out.
