### ISSUE TITLE
How to detect scroll position of ListView in Flutter

### ISSUE THREAD

**Issue by majidfathi69** [flutter/flutter#26182]
I'm using _ListView_ widget to show items as a list. In a window three, items viewing must the middle item place in the middle.

So how can I detect position of _ListView_ when scrolling stop?

How to detect _ListView_ Scrolling stopped?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

#24347 shows an example with `NotificationListener`

**Comment by majidfathi69** [comment]
Of course. Before that, I put up another place, but nobody answered.
[stackoverflow.com](https://stackoverflow.com/questions/54065354/how-to-detect-scroll-position-of-listview-in-flutter)

**Comment by zoechi** [comment]
StackOverflow is quite silent the last few days. That's likely to change again soon.
