### ISSUE TITLE
Remove Dart SDK (the one with binaries) from the Engine repo dependencies

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2618]
Right now we pin the Dart SDK in the engine repo and in the flutter repo. We should remove the engine one, and change the travis scripts to clone flutter repo and use flutter analyze to analyze dart:ui.

**Comment by devoncarew** [comment]
It's on `1.14.1` currently; `1.16.0` is now stable, and we need at least `1.16.0-dev.5.5` since we've started using conditional imports (the `usage` library, used by flutter_tools).

**Comment by abarth** [comment]
Had to revert the patch.  We still need dart-sdk for building observatory.

**Comment by abarth** [comment]
We'll need to find some way of building observatory if we're going to remove this.

**Comment by Hixie** [comment]
The alternative is to change our tooling to make sure that the two Dart SDKs are the same version. Right now the problem is that we keep updating the SDK in one repo and never update the SDK in the other.

**Comment by Hixie** [comment]
cc @aam @a-siva do you know what the status of this is?

**Comment by aam** [comment]
Isn't it obsolete now? I thought we plan to maintain two independent Dart SDK dependencies - one(more frequently updated) for engine to compile the code on the workstation and run binaries on the device, another(more stable) for flutter tools to run analyzer on the workstation and drive command line interface there.

**Comment by Hixie** [comment]
I agree that that is what we want. Is it what we have? We used to have two in the engine, but I'm not sure if we still do.

**Comment by aam** [comment]
Oh, I didn't realize engine used to have two dart sdk. I don't think it's the case anymore, as 'dart sdk with binaries' seem to have been removed in 22f834e048ffc068934d035fb7767824926ca130.

**Comment by Hixie** [comment]
Removed, or moved to buildroot? I count buildroot as part of engine. :-)

**Comment by rmacnak-google** [comment]
Right, we need a pre-built VM to build Observatory et al in reasonable time.

**Comment by gspencergoog** [comment]
I'm going to close this, because from what I can tell the engine is only using one revision of the dart SDK these days, the one in `third_party/dart/tools/sdks`, which, according to the README there, is also the stable one used for the observatory. Please reopen if my understanding is incorrect.
