### ISSUE TITLE
[FeatureRequest] Possibility to get to know if widget has built

### ISSUE THREAD

**Issue by hjJunior** [flutter/flutter#26185]
I got the same problem of #20621, I was creating a `StatefulWidget` where on state class there is a getter where I access property `page` from `PageController`, but I use this variable on my build method, that results in this error

```dart
PageController.page cannot be accessed before a PageView is built with it.
```
I think maybe create a variable like `mounted` for this case `hasBuilt` could be useful, to fix it I used Try/Catch

```dart
  bool get isFirstPage {
    try {
      return _pageController.page.ceil() == 0;
    } catch (error) {
      return true;
    }
  }
```
## Wrap Up
I think if add more control to us with lifecycle, and add this variable will bring facility

```dart
  bool get isFirstPage {
    if (hasBuilt) {
      return _pageController.page.ceil() == 0;
    }
    return true;
  }
```

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/foundation/ChangeNotifier/addListener.html might do what you want

**Comment by hjJunior** [comment]
is there anyone working on this? if don't, maybe I could try to contribute for Flutter community

**Comment by zoechi** [comment]
Unlikely. First it needs to be checked if this change is worthwile.
You can add a listener and rebuild on page change.

**Comment by xster** [comment]
See the doc for [page](https://docs.flutter.io/flutter/widgets/PageController/page.html). You can use https://docs.flutter.io/flutter/widgets/ScrollController/hasClients.html

**Comment by hjJunior** [comment]
Thx, this is realy helpful, It should works on this context.
But anyway I think that PR could be helpful in another cases

**Comment by xster** [comment]
In general, it's not a very functional pattern. The idea here is to be as idempotent as possible while building and let the system be generally reactive. Injecting controllers to domain specific widgets is fine but letting the whole system be more stateful and inspecting the state is an anti-pattern.

**Comment by hjJunior** [comment]
Well, sory about it, I just thought to reproduce the basic same of `mounted` variable...
Anyway thanks again
