### ISSUE TITLE
Expose an API to resize an Image

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#26194]
This doesn't need to be done automatically, but adding the capability to resize a known large image into a fixed size could help memory usages and performance. In https://github.com/flutter/flutter/issues/21571, using the full size image returned from the image picker can result in OOM.

For example, in Android I can use [ThumbnailUtils](https://developer.android.com/reference/android/media/ThumbnailUtils) to create video or image thumbnails at a particular resolution. (Though this still requires loading the full image into memory).

Better yet, could we resize an image known to be too large to load fully into memory into a small thumbnail with going OOO?

cc @chinmaygarde @Hixie

**Comment by GaryQian** [comment]
For reference, https://github.com/flutter/flutter/pull/41415 is the PR that exposes the API for this feature.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/43286 Adds this for `FadeInImage`
