### ISSUE TITLE
Flutter should throw more specific error types for framework errors.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#26196]
For example, `AssetImageProvider` throws a `String` when an asset fails to load. This is wrapped up into a `FlutterError` eventually, but this is done so in a way that doesn't allow users to catch specific types of errors. Example:

```dart
try {
  AssetImageProvider.resolve(..);
} on AssetLoadError catch (err) {
  // do something
}
```

Furthermore, the `FlutterError` extends `AssertionError` while it should probably be a kind of `Exception` (since it is non-fatal).

cc @matanlurey

**Comment by goderbauer** [comment]
I don't see any cases in the framework anymore where we just throw strings.
