### ISSUE TITLE
Behavior of AspectRatio class is unexpected

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2620]
The AspectRatio class always infers the height from the width (see _applyAspectRatio). This can result in a height that can't fit within the constraints. When this happens, I expected that the behavior would invert to inferring width from height.

In my test, the parent box was 400 wide and 100 high. I expected the result size to be 100x100, but the actual result was 400x400 (with an aspect ratio of 1.0).

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: 335354d958f13d24229919c6782f78ef310099e9 (2 days ago)
Engine:    8514a14911269e405784ca90ba082407d260fbf3
```

**Comment by abarth** [comment]
We do something like this for images.

**Comment by abarth** [comment]
Looks like we can use the same algorithm as images for this use case.

**Comment by eseidelGoogle** [comment]
I wanted a Height-in-width-out AspectRatio the other day too:
https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/flex_test.dart#L78

**Comment by abarth** [comment]
@eseidelGoogle That pull request should address your use case too.
