### ISSUE TITLE
Help with external keyboard emulation with usb RFID Reader

### ISSUE THREAD

**Issue by charanjsingh29** [flutter/flutter#26218]
I have a RFID Reader which emulates keyboard input. I want get card number with it in my flutter application and then submit to api. I have tried onChanged Event but it fires before the reader could sent all the card numbers. If I try it with onSubmitted, this never fires because the Reader emulates Carriage Return after typing all card digits. Please help

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by kangwang1988** [comment]
@charanjsingh29 
You'd better make a minimal demo to reproduce your issue and cleanly describe what you want.
Besides, `flutter doctor -v` is always recommend.

**Comment by zoechi** [comment]
Also asked on https://stackoverflow.com/questions/54086878/issue-with-external-keyboard-emulation-with-usb-rfid-reader

**Comment by charanjsingh29** [comment]
> @charanjsingh29
> You'd better make a minimal demo to reproduce your issue and cleanly describe what you want.
> Besides, `flutter doctor -v` is always recommend.

https://stackoverflow.com/questions/54086878/issue-with-external-keyboard-emulation-with-usb-rfid-reader

I have added code and flutter doctor to stackoverflow
