### ISSUE TITLE
Allow to remove or customize the selection checkbox of DataRow

### ISSUE THREAD

**Issue by 370966584** [flutter/flutter#26211]
![image](https://user-images.githubusercontent.com/26058251/50805896-53184180-132f-11e9-8dcb-77bf48752e64.png)
The number of DataColumn is 14。

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by 370966584** [comment]
> Please add the output of `flutter doctor -v`.
> 
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

![image](https://user-images.githubusercontent.com/26058251/50823486-13714a00-136f-11e9-9b75-3098af42c669.png)




void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      // theme: new ThemeData.light(),
      theme: ThemeData(
        primaryColor: Colors.brown,
        
        // textTheme: TextTheme(t)
      ),
//      home: HeroDemo(),
//      home: HideBottomBarDemo(),
        // home: AudioScreen(),
        // home: MyHomePage(),
        // home: TabbedAppBarSample(),
        home: TestPage(),
    );
  }
}


class TableDataPage extends StatefulWidget {
  @override
  _TableDataPageState createState() => _TableDataPageState();
}

class _TableDataPageState extends State<TableDataPage> {

  List<DataColumn> dataColums;
  DataTable table = DataTable();

  @override
    void initState() {
       this.dataColums = [

        DataColumn(label: Text('日期',)),
        DataColumn(label: Text('渠道',)),
        DataColumn(label: Text('项目名称',),),
        DataColumn(label: Text('实际消费',),numeric: true),
        DataColumn(label: Text('账户消费',),numeric: true),
        DataColumn(label: Text('展现',),numeric: true),
        DataColumn(label: Text('点击',),numeric: true),

      ];
      super.initState();
    }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: PaginatedDataTable(
        rowsPerPage: 10,
        onPageChanged: ( page){
          print('当前页一个index=$page');
        },
        // onRowsPerPageChanged:(int value) { setState(() { _rowsPerPage = value; }); },
        source: this.table,
        header: Text('Data',textAlign: TextAlign.left, style: TextStyle(fontSize: 16),),
        columns: this.dataColums,
        ),
    );
  }
}



class DataTable extends DataTableSource{


  @override
  DataRow getRow(int index) {
   
    return DataRow.byIndex(
        cells: [
          DataCell(Text('1222'),),
          DataCell(Text('2')),
          DataCell(Text('33123123123')),
          DataCell(Text('d4')),
          DataCell(Text('53321312312')),
          DataCell(Text('6333')),
          DataCell(Text('7312312312312312312')),
        ],
        selected: false,
        index: index,
        onSelectChanged: (isSelected) {
          // print('index=>$index');
          
      });
  }
  @override
  bool get isRowCountApproximate => false;


  @override
  int get rowCount => 3;

  @override
  int get selectedRowCount => 0;

}

**Comment by kangwang1988** [comment]
@370966584 
Not a minimal and runnable demo, TestPage not found.

**Comment by kangwang1988** [comment]
@370966584 
```
    return DataRow.byIndex(
        cells: [
          DataCell(Text('1222'),),
          DataCell(Text('2')),
          DataCell(Text('33123123123')),
          DataCell(Text('d4')),
          DataCell(Text('53321312312')),
          DataCell(Text('6333')),
          DataCell(Text('7312312312312312312')),
        ],
        selected: false,
        index: index,
        onSelectChanged: null);
```
onSelectChanged: null will give what you want.

I recommend you to read the api and corresponding documentation to resolve this.

Github is to track bugs and feature requests.
Please consider asking support questions in one of the other channels listed at http://flutter.io/support
next time.

Closing it now.

**Comment by zoechi** [comment]
@HansMuller is this a viable feature request?
I have seen this being requested a few times already.

**Comment by ThitSarNyanLynn** [comment]
I just deleted these two of selected: and onSelectChanged: in DataRow.byIndex() and checkbox gone.

**Comment by jaredbaszler** [comment]
Doesn't seem to be a way to conditionally, per row, hide the check box.  As we need to do here on the last page when some rows have data and some don't.  The rows that don't have data should hide their checkbox based on the code below.  

![image](https://user-images.githubusercontent.com/9924084/95260782-e9241900-07ee-11eb-9887-19698984d1f0.png)

```
 @override
  DataRow getRow(int index) {
    final _row = _bigBoxDataTransferData.uploadErrors[index];

    return DataRow.byIndex(
      index: index,
      cells: [
        DataCell(Text(_row.corporateCustomerID)),
        DataCell(Text(_row.storeNumber)),
        DataCell(Text(_row.bigBoxSKU)),
        DataCell(Text(_row.importStartDate.toLocalIsoWithMeridian())),
        DataCell(Text(_row.importEndDate.toLocalIsoWithMeridian())),
        DataCell(Text(_row.errorDescription)),
        DataCell(Text(_row.quantitySold.toString())),
      ],
      selected: _row != null && _row.isSelected,
      onSelectChanged: _row == null
          ? null
          : (value) {
              _bigBoxDataTransferData.setIsSelected(value, index);
            },
    );
  }
```

**Comment by rockingdice** [comment]
> Doesn't seem to be a way to conditionally, per row, hide the check box. As we need to do here on the last page when some rows have data and some don't. The rows that don't have data should hide their checkbox based on the code below.
> 
> ![image](https://user-images.githubusercontent.com/9924084/95260782-e9241900-07ee-11eb-9887-19698984d1f0.png)
> 
> ```
>  @override
>   DataRow getRow(int index) {
>     final _row = _bigBoxDataTransferData.uploadErrors[index];
> 
>     return DataRow.byIndex(
>       index: index,
>       cells: [
>         DataCell(Text(_row.corporateCustomerID)),
>         DataCell(Text(_row.storeNumber)),
>         DataCell(Text(_row.bigBoxSKU)),
>         DataCell(Text(_row.importStartDate.toLocalIsoWithMeridian())),
>         DataCell(Text(_row.importEndDate.toLocalIsoWithMeridian())),
>         DataCell(Text(_row.errorDescription)),
>         DataCell(Text(_row.quantitySold.toString())),
>       ],
>       selected: _row != null && _row.isSelected,
>       onSelectChanged: _row == null
>           ? null
>           : (value) {
>               _bigBoxDataTransferData.setIsSelected(value, index);
>             },
>     );
>   }
> ```

This should be considered. There's no need to select a header row if you care about selecting data.

@kangwang1988 @zoechi
