### ISSUE TITLE
where is session initiation protocol sip in flutter ?

### ISSUE THREAD

**Issue by harpreetsingh3127** [flutter/flutter#26221]
how to make audio call application in flutter like whatsapp call,viber call. In android there is SIP (session initiation protocol ) but in flutter i could not find.

**Comment by zoechi** [comment]
You can make native functionality available using https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages

**Comment by kangwang1988** [comment]
@harpreetsingh3127 
Unless you can realize the sip stuff in flutter, you can't expect it works fine on both platforms while you only code on Android.
Now you need a plugin to develop features which will require some platform(hardware or software) specific codes.No matter you write it or import it from other developer's repo.
Closing it now.

**Comment by HerrNiklasRaab** [comment]
Any update on this? Would be needed desperatly

**Comment by cloudwebrtc** [comment]
@HerrNiklasRaab @harpreetsingh3127 
A dart-lang based sip stack is under development.
https://github.com/cloudwebrtc/dart-sip-ua

**Comment by HerrNiklasRaab** [comment]
Thanks :)

Am Sa., 31. Aug. 2019 um 10:47 Uhr schrieb CloudWebRTC <
notifications@github.com>:

**Comment by amadeu01** [comment]
@cloudwebrtc how did you manage to wake up the app when you receive an invite of SIP, and you app is killed ? Are you taking advantage of the SIP whitelist for keep a service awake for Android ?

**Comment by Priyasri1** [comment]
> @HerrNiklasRaab @harpreetsingh3127
> A dart-lang sip stack is coming soon, it will work with [flutter-webrtc](https://github.com/cloudwebrtc/flutter-webrtc) to become a cross-platform sip client.
> https://github.com/cloudwebrtc/dart-sip-ua

Is it for web only????
