### ISSUE TITLE
Flare Files as Markers in Google Maps Flutter PlugIn

### ISSUE THREAD

**Issue by sherff** [flutter/flutter#26225]
Hi,

I would like to user Flare Files/Animations as Markers in the Flutter Google Maps PlugIn. The deep Integration of Flare by 2Dimension in Flutter is superb to work with and create unique User Experiences. 

Enhancing the Google Maps PlugIn to also user Flare Files/Animations as markers would enhance it on many levels.

Greetings,

Sebastian

**Comment by pepealonso95** [comment]
any updates on this?

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/24213, which encompasses using arbitrary Flutter content for markers.
