### ISSUE TITLE
Keyboard is not opening in webview using flutter_native_web plugin

### ISSUE THREAD

**Issue by UwaisWisitech** [flutter/flutter#26226]
In my Flutter App, i am using [flutter_native_web](https://github.com/PonnamKarthik/FlutterWebView) for webview. But in webview keyboard is not opening on textfield.

**Comment by zoechi** [comment]
Might be #19718

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by UwaisWisitech** [comment]
[√] Flutter (Channel beta, v0.11.13, on Microsoft Windows [Version 10.0.17134.472], locale en-IN)
    • Flutter version 0.11.13 at C:\src\flutter
    • Framework revision 58c8489fcd (6 weeks ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by UwaisWisitech** [comment]
Its working in iOS but its not working in android. In android browse files is also not working.

**Comment by UwaisWisitech** [comment]
@zoechi is there any solution?

**Comment by abomber** [comment]
I have the same problem.

**Comment by ZBarbosa** [comment]
I have the same problem as well

**Comment by zoechi** [comment]
@abomber @ZBarbosa 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by mklim** [comment]
flutter/flutter#19718 used to be blocking this completely. It should be possible for `PonnamKarthik/FlutterWebView` to support this now, but this would require some extra work in the plugin itself to handle some issues with WebView on older issues of Android. The linked issue has a series of PRs for what `flutter_webview` has needed to do to add basic support on its end.

I'm closing this issue since the remaining work would be for `PonnamKarthik/FlutterWebView` at this point and not any of the `flutter/*` codebases.
