### ISSUE TITLE
"flutter create" is so slow

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2622]
Flutter create is slow. That's bad in general, but it's also bad specifically because it means the flutter create _test_ is slow, and that makes all our tests slow.

**Comment by Hixie** [comment]
It's not that bad these days.

**Comment by yassinya** [comment]
It really is, It took 15mins to create a project.

**Comment by Hixie** [comment]
@yassinya That is definitely not normal; please file a bug and provide as much information as you can (e.g. what your network speed is, what your device speed is, etc).

**Comment by jiyinyiyong** [comment]
Slow for me running command from Shanghai.
