### ISSUE TITLE
problem in project structure

### ISSUE THREAD

**Issue by OZEO-DOOZ** [flutter/flutter#26229]
My problem is this. I had run my Flutter project with no problem until i got this 
![flutter_problem](https://user-images.githubusercontent.com/46052659/50830321-c4fc8500-1347-11e9-8dbb-513d5a85c77f.PNG)
and this
![flutter_porblem1](https://user-images.githubusercontent.com/46052659/50830346-d2b20a80-1347-11e9-9ada-f9c761b63684.PNG)
 the confusing thing is that the problem had been solved magically and came back shockingly. I don't understand the root cause; I tried the fix recommended which is deleting the unused "Flutter plugins" but I knew that I still had plugin that I downloaded at the very first beginning of launching Flutter, and no results. What do you think ?

**Comment by OZEO-DOOZ** [comment]
![issue](https://user-images.githubusercontent.com/46052659/50831124-35a4a100-134a-11e9-850c-611654d60761.PNG)
i have no issue everything according to Flutter doctor

**Comment by zoechi** [comment]
> No issues found!

Actually the information I was after was the other part of the output ;-)

**Comment by OZEO-DOOZ** [comment]
in otherwords? can you explain more please?

**Comment by zoechi** [comment]
`flutter doctor -v` provides a lot of information that might be helpful when investigating.
`No issues found!` is the least interesting part of that output. I'd rather have the rest.

**Comment by OZEO-DOOZ** [comment]
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [version 10.0.17134.472], locale fr-FR)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Mélanie\Desktop\myfolder\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Mélanie\Desktop\myfolder\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • VTR L09 • 6PQ0217526002570 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by zoechi** [comment]
I'll move this over to flutter/flutter-intellij

The Bad UTF-8 exception should be covered by #15646

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3053](https://github.com/flutter/flutter-intellij/issues/3053) via [**ZenHub**](https://www.zenhub.com/)
