### ISSUE TITLE
How I can can add two flutter projects and core library (package dart plugin) at same windows

### ISSUE THREAD

**Issue by delphiy** [flutter/flutter#26233]
Hi,

How I can can add two flutter projects and core library (package dart plugin) at same window using Andriod studio.

Thanks

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
If this is a feature request for Android Studio please report in https://github.com/flutter/flutter-intellij
with more details.

**Comment by delphiy** [comment]
you sent me home page of flutter website .

You are amazing

**Comment by zoechi** [comment]
I sent you to 
![image](https://user-images.githubusercontent.com/405837/50847290-811e7580-1371-11e9-922a-a3c2cbff3649.png)

GitHub is for bug reports and feature requests. For support requests better use the other channels.
