### ISSUE TITLE
SliverAppBar will not collapse when ListView is scrolled

### ISSUE THREAD

**Issue by willladislaw** [flutter/flutter#26243]
SliverAppBar will not collapse when scrolling the ListView.

## Steps to Reproduce

1. Create `SliverAppBar` with background content

2. Add `TabView` to the `Scaffold` body property

3.  Create `ListView` inside a `Tab`

4. Scroll List

```dart
ScrollController _scrollController ;
  TabController tabContoller;

@override
  void initState() {
    _scrollController = new ScrollController();
    tabContoller = new TabController(
      vsync: this,
      length: 1,
    );

      @override
  Widget build(BuildContext context) {
    return new Scaffold(
                body: NestedScrollView(
                  controller:_scrollController ,
                  headerSliverBuilder:
                      (BuildContext contrxt, bool innerBoxIsScrolled) {
                    return <Widget>[
                      SliverAppBar(
                        backgroundColor: Colors.transparent,
                        automaticallyImplyLeading: false,
                        expandedHeight: 150.0,
                        pinned: true,
                        floating: true,
                        forceElevated: innerBoxIsScrolled,
                        flexibleSpace: FlexibleSpaceBar(
                          background: new Stack(
children: <Widget>[
                               
                                Container(
                                  color: Colors.blue,
                                  height: MediaQuery.of(context).size.height / 6,
                                  width: MediaQuery.of(context).size.width,
                                  child: Text("Container 2 Text", textAlign: TextAlign.center,),
                                ),
                          ]
),
                        ),
                      ),
                    ];
                  },

                  body: TabBarView(
                    controller: tabContoller,
                    children: <Widget>[
                    new TabOne()
                    ],
                  ),

                ));
  }

TabOne Class returns a ListView

class TabOne extends StatefulWidget {
  _TabOneState createState() => new _TabOneState();
}

class _TabOneState extends State<TabOne> {
  final ScrollController _scrollController = new ScrollController();

  @override
  Widget build(BuildContext context) {
    return Tab(
      child: RefreshIndicator(
        child: ListView.builder(
            shrinkWrap: false,
            controller: _scrollController,
            itemCount: aList.length,
            itemBuilder: (context, index) {
              //populate list
            }),
        onRefresh: _getMoreData,
      ),
    );
  }


   
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by willladislaw** [comment]
@Kartik1607 seems to work but not completely, run the above sample app to see what I mean.

**Comment by songxiaoliang** [comment]
@willladislaw Hello, how can I solve this problem?

**Comment by willladislaw** [comment]
@songxiaoliang  @Kartik1607 suggestion

**Comment by willladislaw** [comment]
@songxiaoliang  Do what @Kartik1607 suggestions - wrap with a CustomScrollView. See the updated sample app above.

**Comment by leo-jehmi** [comment]
remove scrollController which inside ListView.builder()

**Comment by Alekcei** [comment]
Hello, how can I solve this problem?
The solution above does not fit

**Comment by Alekcei** [comment]
I need fixed bottom.

**Comment by hiteshgarg002** [comment]
I had the same problem, i just removed scroll controller from listview and my problem was solved but i want to implement pagination and without scroll controller. it is not possible, so is there any alternate solution to this problem?

**Comment by iammart** [comment]
@hiteshgarg002 For an explanation on why you can not use a `ScrollController` within a `NestedScrollView` refer to the following comment on SO.

https://stackoverflow.com/questions/46817189/sliverappbar-and-listview-with-controller/46853315#46853315.

I resolved this issue by wrapping the `CustomScrollView` in a `NotificationListener`. You can then listen to the events via `onNotification`. Using the example above it would take the following structure.

```dart
class _TabOneState extends State<TabOne> {
  final ScrollController _scrollController = new ScrollController();

  @override
  Widget build(BuildContext context) {
    return Tab(
      child: RefreshIndicator(
        child: NotificationListener<ScrollNotification>(
          onNotification: (scrollNotification) {
            final maxScroll = scrollNotification.metrics.maxScrollExtent;
            final currentScroll = scrollNotification.metrics.pixels;

            if (maxScroll - currentScroll <= _scrollThreshold) {
              // fetch more data
            }
          },
          child: CustomScrollView(
            slivers: <Widget>[
              SliverList(
                delegate: SliverChildListDelegate(
                  List<Widget>.generate(50, (i) {
                    return ListTile(
                      title: Text('${widget.items[i]}'),
                    );
                  }),
                ),
              )
            ],
          ),
          onRefresh: () {},
        ),
      ),
    );
  }
}
```

**Comment by Alekcei** [comment]
that dont work.
Need transparent  pined TabBar.

**Comment by mrtian** [comment]
> @hiteshgarg002 For an explanation on why you can not use a `ScrollController` within a `NestedScrollView` refer to the following comment on SO.
> 
> https://stackoverflow.com/questions/46817189/sliverappbar-and-listview-with-controller/46853315#46853315.
> 
> I resolved this issue by wrapping the `CustomScrollView` in a `NotificationListener`. You can then listen to the events via `onNotification`. Using the example above it would take the following structure.
> 
> ```dart
> class _TabOneState extends State<TabOne> {
>   final ScrollController _scrollController = new ScrollController();
> 
>   @override
>   Widget build(BuildContext context) {
>     return Tab(
>       child: RefreshIndicator(
>         child: NotificationListener<ScrollNotification>(
>           onNotification: (scrollNotification) {
>             final maxScroll = scrollNotification.metrics.maxScrollExtent;
>             final currentScroll = scrollNotification.metrics.pixels;
> 
>             if (maxScroll - currentScroll <= _scrollThreshold) {
>               // fetch more data
>             }
>           },
>           child: CustomScrollView(
>             slivers: <Widget>[
>               SliverList(
>                 delegate: SliverChildListDelegate(
>                   List<Widget>.generate(50, (i) {
>                     return ListTile(
>                       title: Text('${widget.items[i]}'),
>                     );
>                   }),
>                 ),
>               )
>             ],
>           ),
>           onRefresh: () {},
>         ),
>       ),
>     );
>   }
> }
> ```

don't work!

**Comment by mrtian** [comment]
> that dont work.
> Need transparent pined TabBar.
fixed?

**Comment by mrtian** [comment]
> @songxiaoliang Do what @Kartik1607 suggests - wrap it with a CustomScrollView. See updated sample app above.

dont work!
i have 3 tab

**Comment by ysknsn** [comment]
I have same problem.
and I need ScrollController to store scroll position.

Is thre any solution?

**Comment by ysknsn** [comment]
I solved this problem.

Set PageStorageKey to child ListView,
then remove the child ListView's ScrollController and set it to NestedScrollView.
You have to handle child ListView's scroll event in NestedScrollView's ScrollController. 

In my situation,  it works.

**Comment by firatcetiner** [comment]
> I solved this problem.
> 
> Set PageStorageKey to child ListView and NestedScrollView,
> then remove the child ListView's ScrollController and set it to NestedScrollView.
> 
> In my situation, it works.

I don't understand the part where everyone say "just remove the ScrollController from ListView. That doesn't make any sense to me because every ListView has a default ScrollController assigned. If it is a solution then it's lazy one.

**Comment by gmaggio** [comment]
@firatcetiner: it means don't set the `controller` for the `ListView`. Use `NotificationListener` instead to detect the scrolling events as @iammart suggested. Setting `controller` in the `ListView` will override the `controller` in the `NestedScrollView`.

**Comment by gmaggio** [comment]
@ysknsn: Could tell us how you used `PageStorageKey` in your code, please.

**Comment by ysknsn** [comment]
@gmaggio 
I'm really sorry for the late reply
This is my code.
https://gist.github.com/ysknsn/d90a84a180e32de5b0691de874c65d55

But this code also has a problem,

Sometimes, the value of _scrollController in _didScroll becomes strange.
In my case, there was no problem, but it is impossible for this implementation to do complicated processing with ScrollController.

And I noticed after the last comment,
If you swipe up to the top, the next tab will also scroll to the top

**Comment by firatcetiner** [comment]
> @firatcetiner: it means don't set the `controller` for the `ListView`. Use `NotificationListener` instead to detect the scrolling events as @iammart suggested. Setting `controller` in the `ListView` will override the `controller` in the `NestedScrollView`.

Got it. Except removing ScrollController doesn't change much, thus the issue still exists. Using ListView as the child of a NestedScrollview or CustomScrollview is causes SliverAppBar to not to collaps when scrolling down.

**Comment by MaximusAshraf** [comment]
I have some problem and found that when use Scaffold as child of NestedScrollView, NestedScrollView  lost it's effect so the solution to avoid use Scaffold as child of NestedScrollView.
My page was like that: 
Scaffold -> NestedScrollView -> TabBarView -> Scaffold -> BottomNavigationBar -> ListView.
fix:
Scaffold -> NestedScrollView -> TabBarView -> Stack with Expanded for body and Row to act like BottomNavigationBar  -> ListView.
