### ISSUE TITLE
Issue for implementing experimental flags in Flutter

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#26240]
Reference:

[Dart SDK Process for changes behind experimental flags](https://github.com/dart-lang/sdk/blob/master/docs/process/experimental-flags.md)

[Dart Experimental Flags Implementation](https://docs.google.com/document/d/1pnaKiqxQqO0-tXhmkFh0lLhvhGTjaVlduDcGOdN1saY/edit)

This issue is opened to track the following

- implementing the experimental flags option in the command line VM
- hooking up the experimental flags options passed in to the CFE invoked in the kernel isolate
- reading the options embedded in the kernel file and appropriately setting the engine/VM flags

**Comment by a-siva** [comment]
why was this reopened?

**Comment by zoechi** [comment]
@a-siva looks like @liamappelbe re-opened it manually. No idea why.

**Comment by liamappelbe** [comment]
The hot reload CL was rolled back just before I went on vacation. Currently experimental flags don't work for hot reloading. I'm working on resubmitting the CL atm.

**Comment by liamappelbe** [comment]
Fixed by https://github.com/flutter/flutter/pull/27252
