### ISSUE TITLE
VM often crashes when a debugger disconnects

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#26241]
I see a consistent crash when a debugger disconnects from a running Flutter app. To repro:

- run a flutter app (`flutter run`)
- connect to the indicated url via the observatory (`An Observatory debugger and profiler on iPhone X is available at...`)
- refresh the page

The Flutter runtime will generally crash on the first page refresh (when the debugger client connection goes away). It will occasionally survive the first page refresh, but generally not more than that.

I've tested this against the iOS simulator. I don't see the same crash when run against the android emulator - I can refresh the observatory page ~12 times.

cc @a-siva @cbracken

**Comment by DanTup** [comment]
I closed the other one since this one is assigned! :)

**Comment by bkonyi** [comment]
Looks like there's a race where the Observatory tries to write to a socket after the browser has closed the connection on a refresh. This is raising SIGPIPE, which terminates the application. I have a fix that seems to work [here](https://dart-review.googlesource.com/c/sdk/+/89960). With that patch applied, I can basically spam refresh with Observatory open while flutter_gallery is running on an iOS simulator with no crashes.

**Comment by devoncarew** [comment]
👍, thanks much for the fix!
