### ISSUE TITLE
Engine dart changes require flutter clean

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26258]
@GaryQian reports that the `flutter` tool doesn't consider the engine version as something that should cause a rebuild.

**Comment by GaryQian** [comment]
Specifically, changes to dart:ui (or other engine repo dart code) requires a `flutter clean` or deletion of build folder to work.

**Comment by GaryQian** [comment]
This can cause apps to crash on run or build if there is a recent API-modifying change in dart:ui.

**Comment by GaryQian** [comment]
cc @cbracken You mentioned that this may stem from something not being included in snapshotting?

**Comment by zoechi** [comment]
Related to #16604
