### ISSUE TITLE
Default cursor color on iOS should match the theme

### ISSUE THREAD

**Issue by jslavitz** [flutter/flutter#26261]
As the title says, we want the cursor color to always be blue by default on iOS even when the theme is set to Material.

**Comment by xster** [comment]
More specifically, I think the ThemeData's cursorColor should be the iOS color (which should probably be in CupertinoColors if it's not activeBlue) when the platform is iOS.

**Comment by xster** [comment]
Correction: the cursor color should actually be the primaryColor or the Material or Cupertino theme. Consider the red cursor in the Health app or the orange cursor in the Clock app.

**Comment by xster** [comment]
Actually the Material TextField is fixed in #24876. We just need to make sure CupertinoTextField also reads from CupertinoTheme.

**Comment by DenisBarzanov** [comment]
**ARE YOU GUYS CRAZY?**

Why do you need to break everything nice? Nobody uses `CupertinoApp` and `Cupertino whatever` anyways

**Comment by xster** [comment]
@DenisBarzanov we encourage contribution and feedback from everyone in the community but please see https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md and make productive contributions.
