### ISSUE TITLE
[WebView]Get errors when puting a WebView inside a SingleChildScrollView

### ISSUE THREAD

**Issue by JamesChenX** [flutter/flutter#26268]
I have to put a WebView inside a SingleChildScrollView in my project, but I get the error:

> I/flutter ( 5795): RenderAndroidView object was given an infinite size during layout.
> I/flutter ( 5795): This probably means that it is a render object that tries to be as big as possible, but it was put
> I/flutter ( 5795): inside another render object that allows its children to pick their own size.

WebView tries to be as big as possible, while SingleChildScrollView allows its children to pick their own size. Because the height of the content is uncertain, I can't give a height to the WebView.
So I need a new feature that WebView can be put inside a SingleChildScrollView .
Thank you.

**Comment by Kartik1607** [comment]
Try wrapping *WebView* with an **Expanded** widget.

```dart
SingleChildScrollView(
    child:Expanded(
        child: WebView(...)
    )
)
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
