### ISSUE TITLE
 The method 'ancestorStateOfType' was called on null

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#26267]
I`m using local notification plugin and everything works fine except that when i tap on the notification....
i want to navigate to specific screen when the user tap the notification ```

```dart
Future onSelectNotification(String payload) async {
    //convert payload json to notification model object
    try{
    Map notificationModelMap = jsonDecode(payload);
    NotificationModel model = NotificationModel.fromJson(notificationModelMap);
  
    await Navigator.push(
        context,// it`s null!
        new MaterialPageRoute(
            builder: (context) => CommitmentPage(model)));}
            catch(e){print(e.toString());}
  }
```

but the context always null and gives me an exception 
`NoSuchMethodError: The method 'ancestorStateOfType' was called on null.`

the problem is not related to the plugin, so how should i solve it ?

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/52130648/nosuchmethoderror-the-method-ancestorstateoftype-was-called-on-null
https://stackoverflow.com/questions/49373774/inheritedwidget-with-scaffold-as-child-doesnt-seem-to-be-working

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jitendraAn** [comment]
I have a same issue.

**Comment by Tseso** [comment]
i have a same issue

**Comment by mahtab-ali** [comment]
having same issue .. ! any solutions ?

**Comment by rajeshzmoke** [comment]
the navigator problem can be solved by passing a  `GlobalKey<NavigatorState>()` to  `navigatorKey` property in the `MaterialApp`

```
final navigatorKey = GlobalKey<NavigatorState>();
MaterialApp(
            navigatorKey: navigatorKey,
            title: 'Flutter Demo',
            debugShowCheckedModeBanner: false,
            theme: snapshot.hasData ? snapshot.data : null,
            // theme: _themeData,
            routes: routes,
            home: MyHomePage(),
          );
```
my issue is that i cant access my Bloc with context from global keys... from a push notification onclick i need to a make an api call by fetching data from Bloc and  route to particular screen.. 

Any help regarding this ? i get this error when accessing the bloc `The method 'ancestorStateOfType' was called on null`

**Comment by sathishmscict** [comment]
> the navigator problem can be solved by passing a `GlobalKey<NavigatorState>()` to `navigatorKey` property in the `MaterialApp`
> 
> ```
> final navigatorKey = GlobalKey<NavigatorState>();
> MaterialApp(
>             navigatorKey: navigatorKey,
>             title: 'Flutter Demo',
>             debugShowCheckedModeBanner: false,
>             theme: snapshot.hasData ? snapshot.data : null,
>             // theme: _themeData,
>             routes: routes,
>             home: MyHomePage(),
>           );
> ```
> 
> my issue is that i cant access my Bloc with context from global keys... from a push notification onclick i need to a make an api call by fetching data from Bloc and route to particular screen..
> 
> Any help regarding this ? i get this error when accessing the bloc `The method 'ancestorStateOfType' was called on null`

Am also faced same issue, added 8 seconds of delay. Now screen navigation working fine without issue!

**Comment by kallakars** [comment]
> having same issue .. ! any solutions ?

Yeah i have
but I don't know english

**Comment by s15-coder** [comment]
Same issue. I don't know why is it closed.
