### ISSUE TITLE
 After the icon in the bottom navigation bar is replaced with a GIF image, click to display only one animation.

### ISSUE THREAD

**Issue by wuyuancai** [flutter/flutter#26278]
## Steps to Reproduce

After the icon in the bottom navigation bar is replaced with a GIF image, the switch only displays the animation once, and the GIF does not display the animation when you click again. 
Futter v1.0

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by wuyuancai** [comment]
> 请添加输出`flutter doctor -v`。
> 
> 研究为了我们需要将最小的柯林斯运行再现
> 作为单个文件，我们以便将可以您的代码复制到`lib/main.dart`一个新项目中并运行以重现。
> 
> 请在考虑http://flutter.io/support列出的其他渠道中提出请立即获取iTunes问题。
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale zh-CN)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at E:\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Android_SDK
    • Java binary at: E:\Android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\Android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

```
class BottomNavigationBarHome extends StatefulWidget {
@override
State createState() {
// TODO: implement createState
return _BottomNavigationBarHomeState();
}
}

class _BottomNavigationBarHomeState extends State{
int _currentIndex = 0;
var bottomTitle = ['home','menu','message','person'];
var bottomIcons = ['res/icon/home.png','res/icon/menu.png','res/icon/message.png','res/icon/person.png'];
var bottomIconsGif = ['res/icon/home.gif','res/icon/menu.gif','res/icon/message.gif','res/icon/person.gif'];

var pageList = [
new home(),
new location(),
new person(),
new person()
];

var title = '';
var iconGif = ['res/icon/home.png','res/icon/menu.png','res/icon/message.png','res/icon/person.png'];

void _onTapHandler(int index){
setState(() {
_currentIndex = index;
iconGif = ['res/icon/home.png','res/icon/menu.png','res/icon/message.png','res/icon/person.png'];
iconGif[index] = bottomIconsGif[index];
});
}

@override
Widget build(BuildContext context) {
// TODO: implement build
return MaterialApp(
debugShowCheckedModeBanner: false,
home: new Scaffold(
body: pageList[_currentIndex],
bottomNavigationBar: new BottomNavigationBar(items: [
BottomNavigationBarItem(
icon: new Image.asset(iconGif[0],height: 30.0,),
title: Text(bottomTitle[0],style: new TextStyle(color: Colors.black)),
),
BottomNavigationBarItem(
icon: new Image.asset(iconGif[1],height: 30.0,),
title: Text(bottomTitle[1],style: new TextStyle(color: Colors.black))
),
BottomNavigationBarItem(
icon: new Image.asset(iconGif[2],height: 30.0,gaplessPlayback: true,),
title: Text(bottomTitle[2],style: new TextStyle(color: Colors.black))
),
BottomNavigationBarItem(
icon: new Image.asset(iconGif[3],height: 30.0,),
title: Text(bottomTitle[3],style: new TextStyle(color: Colors.black),)
),
],
currentIndex: _currentIndex,
onTap: _onTapHandler,
),
),

);
}

}
```

**Comment by wuyuancai** [comment]
> Please add the output of `flutter doctor -v`.
> 
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale zh-CN)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at E:\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Android_SDK
    • Java binary at: E:\Android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\Android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

```
class BottomNavigationBarHome extends StatefulWidget {
@override
State createState() {
// TODO: implement createState
return _BottomNavigationBarHomeState();
}
}

class _BottomNavigationBarHomeState extends State{
int _currentIndex = 0;
var bottomTitle = ['home','menu','message','person'];
var bottomIcons = ['res/icon/home.png','res/icon/menu.png','res/icon/message.png','res/icon/person.png'];
var bottomIconsGif = ['res/icon/home.gif','res/icon/menu.gif','res/icon/message.gif','res/icon/person.gif'];

var pageList = [
new home(),
new location(),
new person(),
new person()
];

var title = '';
var iconGif = ['res/icon/home.png','res/icon/menu.png','res/icon/message.png','res/icon/person.png'];

void _onTapHandler(int index){
setState(() {
_currentIndex = index;
iconGif = ['res/icon/home.png','res/icon/menu.png','res/icon/message.png','res/icon/person.png'];
iconGif[index] = bottomIconsGif[index];
});
}

@override
Widget build(BuildContext context) {
// TODO: implement build
return MaterialApp(
debugShowCheckedModeBanner: false,
home: new Scaffold(
body: pageList[_currentIndex],
bottomNavigationBar: new BottomNavigationBar(items: [
BottomNavigationBarItem(
icon: new Image.asset(iconGif[0],height: 30.0,),
title: Text(bottomTitle[0],style: new TextStyle(color: Colors.black)),
),
BottomNavigationBarItem(
icon: new Image.asset(iconGif[1],height: 30.0,),
title: Text(bottomTitle[1],style: new TextStyle(color: Colors.black))
),
BottomNavigationBarItem(
icon: new Image.asset(iconGif[2],height: 30.0,gaplessPlayback: true,),
title: Text(bottomTitle[2],style: new TextStyle(color: Colors.black))
),
BottomNavigationBarItem(
icon: new Image.asset(iconGif[3],height: 30.0,),
title: Text(bottomTitle[3],style: new TextStyle(color: Colors.black),)
),
],
currentIndex: _currentIndex,
onTap: _onTapHandler,
),
),

);
}

}
```

**Comment by zoechi** [comment]
Please update the code to make it a 

> minimal *runnable* reproduction

including `main(){}`.

**Comment by zoechi** [comment]
We would probably also need the images to be able to reproduce.

**Comment by wuyuancai** [comment]
```
void main() => runApp(new MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new BottomNavigationBarHome();
  }
}
```
http://cdn.open-source.cn/app_icon/home.png
http://cdn.open-source.cn/app_icon/home.png
http://cdn.open-source.cn/app_icon/home.png
http://cdn.open-source.cn/app_icon/home.png
http://cdn.open-source.cn/app_icon/home.png
http://cdn.open-source.cn/app_icon/home.png

**Comment by wuyuancai** [comment]
> We would probably also need the images to be able to reproduce.
```
void main() => runApp(new MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new BottomNavigationBarHome();
  }
}
```
http://cdn.open-source.cn/app_icon/home.png
http://cdn.open-source.cn/app_icon/message.png
http://cdn.open-source.cn/app_icon/person.png
http://cdn.open-source.cn/app_icon/menu.png
http://cdn.open-source.cn/app_icon/home.gif
http://cdn.open-source.cn/app_icon/message.gif
http://cdn.open-source.cn/app_icon/person.gif
http://cdn.open-source.cn/app_icon/menu.gif

**Comment by kangwang1988** [comment]
@wuyuancai 
A minimum demo project which can reproduce what you said would be much appreciated.

**Comment by wuyuancai** [comment]
> @wuyuancai
> A minimum demo project which can reproduce what you said would be much appreciated.

https://github.com/wuyuancai/debug.git

**Comment by kangwang1988** [comment]
@wuyuancai 
It could be related with your git resource.
After I change gif you provided with:
![home](https://user-images.githubusercontent.com/817851/50908435-a9d36780-1464-11e9-9416-be462d1b0d96.gif)

It works fine.
Closing it now.

**Comment by zoechi** [comment]
It doesn't solve the actual problem but you might want to use `BottomNavigationBarItem.icon` and `BottomNavigationBarItem.activeIcon` instead of changing `BottomNavigationBarItem.icon` depending on the active state.

**Comment by wuyuancai** [comment]
> It doesn't solve the actual problem but you might want to use `BottomNavigationBarItem.icon` and `BottomNavigationBarItem.activeIcon` instead of changing `BottomNavigationBarItem.icon` depending on the active state.

Thank you very much

**Comment by wuyuancai** [comment]
> @wuyuancai
> It could be related with your gif resource.
> After I change gif you provided with:
> https://user-images.githubusercontent.com/817851/50908435-a9d36780-1464-11e9-9416-be462d1b0d96.gif
> 
> It works fine.
> Closing it now.

Thank you very much
