### ISSUE TITLE
Opening a FlutterViewController is Very Slow, Its take 4 to 5 seconds for the Dart View to Come in IOS

### ISSUE THREAD

**Issue by GuruprasathRamaprasath** [flutter/flutter#26282]

**Comment by gururit** [comment]
I am pushing to a FlutterViewController from my Native ViewController. It take 3- 4 seconds to navigate to FlutterViewController and 3-4seconds to load the Dart coded View. Please some one help me out?

**Comment by kangwang1988** [comment]
@gururit 
Make sure you measure the performance in release/profile mode.
If it's still a problem, please paste `flutter -v doctor -v` here.
And create a minimal demo project which can help to reproduce this issue.

**Comment by zoechi** [comment]
Common behavior is it that performance behavior differs notably between debug and profile/release builds. 3-4 seconds is not common at all but investigating performance with debug builds is mostly just pointless.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
