### ISSUE TITLE
The site don't work fine

### ISSUE THREAD

**Issue by OrionWambert** [flutter/flutter#26292]
Hi guys, it's normal for the mobile version of the site to show up like that in the widget catalog and the Widget index
![whatsapp image 2019-01-09 at 15 50 43](https://user-images.githubusercontent.com/31405783/50907390-86d69280-1427-11e9-8e4f-a06d64da4fed.jpeg)

**Comment by zoechi** [comment]
What device 
with what Android version
and what browser are you using to get this result?

**Comment by OrionWambert** [comment]
I use an iPhone 5C height: 124.4 mm width: 59.2 mm depth: 89 mm weight: 132g

for the browser is chrome but I encounter the same problem when I'm on safari

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/50916174-bd69d880-143a-11e9-8437-055e6acc1598.png)

Seems to be quite specific to your device.

**Comment by jcollins-g** [comment]
@zoechi  Reopening -- the Flutter widget index is not controlled by dartdoc.

**Comment by gaaclarke** [comment]
move to website: https://github.com/flutter/website/issues/3910
