### ISSUE TITLE
No notification from firebase messaging

### ISSUE THREAD

**Issue by sondresorbye0111** [flutter/flutter#26298]
I have added `implementation 'com.google.firebase:firebase-core:16.0.6'`  as a dependency in my app level build gradle. I also have the google-services.json file from firebase. But I still dont get notification when the app is in the background. It does not work in foreground either.

**Comment by zoechi** [comment]
When the app is in foreground the app should get notified but you'd need to show notifications yourself (using local_notifications package for example). When the app is in background notifications should be shown.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
