### ISSUE TITLE
Android back button does not do navigator.pop() when using run_mojo

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#263]
<a href="https://github.com/aghassemi"><img src="https://avatars.githubusercontent.com/u/2099009?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [aghassemi](https://github.com/aghassemi)**
_Thursday Nov 05, 2015 at 23:28 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1973_

----

I am running my MaterialApp in Mojo so it is using Mojo Shell instead of Sky Shell. This difference seems to be causing back button to exit the app rather than poping from navigator.

@abarth @Hixie

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Nov 05, 2015 at 23:36 GMT_

----

There's no back button integration in MojoShell on Android.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Friday Nov 06, 2015 at 04:50 GMT_

----

@jamesr @j9brown Who's the right person to handle feature requests for MojoShell on Android?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/jamesr"><img src="https://avatars.githubusercontent.com/u/7497301?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesr](https://github.com/jamesr)**
_Monday Nov 09, 2015 at 20:20 GMT_

----

@qsr is

**Comment by aghassemi** [comment]
@abarth Should  https://github.com/domokit/mojo/issues/361 get integrated with Flutter or should the app listen for that event and pop from nav?

**Comment by abarth** [comment]
@aghassemi It's the same code to write either way.  The simplest thing for the demo is to write the code in the app.

**Comment by aghassemi** [comment]
Thanks, SGTM.

**Comment by abarth** [comment]
I'm going to close this issue because the current plan is to do this in the slides app itself.
