### ISSUE TITLE
How To Pass MoPub Native Ad To Flutter?

### ISSUE THREAD

**Issue by AdamSHurwitz** [flutter/flutter#26301]
# Question

I'm researching how to integrate MoPub's Android and iOS native ads implementation over to Flutter. **What data from the native ad received from MoPub in the _onNativeLoad_ method below would need to be passed in order for Flutter to display properly?**

# Potential Solution

Based on MoPub's [documentation for manual native ads integration](https://developers.mopub.com/docs/android/native/#method-3-manual-integration) (on Android) the ad data can be received and passed via an [**EventChannel**](https://docs.flutter.io/flutter/services/EventChannel-class.html) in order to display in Flutter's UI. I'm not sure which information from the `NativeAd` object would need to be passed to Flutter.
```java
     moPubNativeNetworkListener = new MoPubNative.MoPubNativeNetworkListener() {
         @Override
         public void onNativeLoad(final NativeAd nativeAd) {
             Log.d("MoPub", "Native ad has loaded.");
         }
         @Override
         public void onNativeFail(NativeErrorCode errorCode) {
             Log.d("MoPub", "Native ad failed to load with error: " + errorCode.toString());
         }
     };
```
Developer's usage of MoPub on Flutter would key as it allows access to the major ad networks and thus provides effective monetization. I've created a corresponding [StackOverflow](https://stackoverflow.com/questions/54116035/how-to-pass-mopub-native-ad-to-flutter) post.

Thank you!

**Comment by kangwang1988** [comment]
@AdamSHurwitz 
Do you want to (to develop) a Flutter package/plugin which can use MoPub in Flutter side?
I don't have much information about MoPub, but If you can give more information about how MoPub works now in iOS/Android, we can discuss more.
For example, do you still need the native code to receive data from the remote server?
Can you fetch all data by http request(which can be done in pure dart code)?
Do you need some system related features(notification etc)?
...

**Comment by AdamSHurwitz** [comment]
@kangwang1988, Developing a Flutter package/plugin is the future goal. Currently, I'm still in alpha version of the Android news app I'm building. I am in the stage of scoping the feasibility of this package/plugin.

`For example, do you still need the native code to receive data from the remote server?`
 **Unfortunately, yes.**

`Can you fetch all data by http request(which can be done in pure dart code)?`
**No, just Android, iOS, and Unity implementations.**

Do you need some system related features(notification etc)?
**You need to handle the ads based on the lifecycle. I estimate this can be handled by Flutter passing messages back to the native client to handle this.**

The most customized version of MoPub is the [manual integration](https://developers.mopub.com/docs/android/native/#method-3-manual-integration). The manual integration allows loading of ads at any given point which are then bound to the specified view which is Android for this example. 

     ViewBinder viewBinder = new ViewBinder.Builder(R.layout.native_ad_layout)
        .mainImageId(R.id.native_ad_main_image)
        .iconImageId(R.id.native_ad_icon_image)
        .titleId(R.id.native_ad_title)
        .textId(R.id.native_ad_text)
        .privacyInformationIconImageId(R.id.native_ad_privacy_information_icon_image)
        .build();

The constraint here is not having direct access to the raw ad data. If that can be extracted from the native library then it can be passed to Flutter. I will attempt to get in touch with the MoPub development team once I am closer to building the cross-platform experience for the news app in order to explore extracting the ad data.

**Comment by charleshan** [comment]
@AdamSHurwitz Where are you with this?

**Comment by AdamSHurwitz** [comment]
@charleshan I have not pursued building out this package for MoPub on Android and iOS. However, based on the development of the rest of the Flutter technical ecosystem it may become a future focus. 

Currently, I'm creating an amazing Android experience for [Coinverse](https://play.google.com/store/apps/details?id=app.coinverse), the first crypto news app for audiocasts. Based on how Dart/Flutter develops it's ability to handle audio content with a library similar to ExoPlayer for Android, the YouTube library, and foreground services, I'll assess when to move forward with Flutter.

**Comment by AndreHaueisen** [comment]
Is there a timeline for this plugin?

**Comment by ammarhemani** [comment]
Hi,
Were you able to find a solution to integrating MoPub with Flutter?

**Comment by AdamSHurwitz** [comment]
@ammarhemani, I have not pursued this implementation strategy with Flutter. In addition to building a MoPub solution from the ground up, I also would need to bridge other libraries such as Android's ExoPlayer and YouTube API functionality.

Once Flutter offers rich media libraries I'm open to consider.

**Comment by stuartmorgan** [comment]
This sounds like a use case that's covered by platform views, so I don't think there's anything actionable here at this point. If at some point someone builds this plugin and finds that there is functionality they need in the plugin system in order to do so, please file an issue with the specific request.
