### ISSUE TITLE
While Coding with VS Code OpenJDK Platform Binary not closing even VSCode is Closed 

### ISSUE THREAD

**Issue by PramUkesh** [flutter/flutter#26308]
Hi Guys I was using VS Code to develop Android Apps because it is lightweight but there is a bug in vscode flutter plugin that causes OpenJDKPlatformBinary Still Loading in Background even when VSCode is Closed so 
- it sucks more than 500MB of RAM and it produces multiple copies of such running program when vscode is closed multiple times 
![2019-01-10_01-37-30](https://user-images.githubusercontent.com/26147066/50925475-713d8900-1478-11e9-93a4-1862a4c7e4a9.gif)
above screenshot is taken after closing vscode and its already 15 minutes from closing vscode its still running
- its also happens when we lost connection from android device

**Comment by DanTup** [comment]
@PramUkesh Are you able to get the command line for the processes that are still around? Right-click on the column headers and put a tick next to "Command Line" and it should add a new column that includes it.

**Comment by PramUkesh** [comment]
> flutter doctor -v
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale en-IN)
    • Flutter version 1.0.0 at C:\flutter\0.11.9
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\PramUkesh\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\PramUkesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.0

[√] Connected device (1 available)
    • Z2 Plus • 100.73.199.142:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by PramUkesh** [comment]
> @PramUkesh Are you able to get the command line for the processes that are still around? Right-click on the column headers and put a tick next to "Command Line" and it should add a new column that includes it.
@DanTup 
I don't what you are saying 
in VSCode ? i have to click and put tick mark but in case your are asking cmd line in VSCode it is accessible from VSCode

**Comment by DanTup** [comment]
@PramUkesh Sorry, I wasn't very clear. In your screenshot, it shows the Windows Task Manager showing the processes. If you right-click on the column headers in your screenshot (eg. "Name") you can enable the Command Line column.

Here's a screenshot showing where I mean:

https://thewindowsclub-thewindowsclubco.netdna-ssl.com/wp-content/uploads/2017/10/Display-Command-Line-in-Task-Manager.png

This will add a new column to task manager which shows the command line used to start a process, including all of the arguments. It would be useful to see the full command lines for the ADB and Java processes that are left when you close VS Code. This may help us identify what's not being cleaned up.

**Comment by PramUkesh** [comment]
![2019-01-10_23-50-26](https://user-images.githubusercontent.com/26147066/50989237-d0f96a00-1534-11e9-84c7-54d1a083d092.gif)

This is full cmd process running @DanTup

**Comment by DanTup** [comment]
Since this is expected behaviour, I don't think there's anything to do here. If you believe that's not the case, please shout!

**Comment by Andrew214-dot** [comment]
hello friends, i have an one doubt we are already know about how does work java and xml to develop android application but , how does work flutter and dart language  to develop android application?
