### ISSUE TITLE
[Material] Update FAB theme detaults elevations tests

### ISSUE THREAD

**Issue by willlarche** [flutter/flutter#26317]
When `FloatingActionButton` extends `MaterialButton` instead of just building one, remove any tests for the elevation of the `RawMaterialButton`'s `Material` class and just test the elevation of the `RawMaterialButton`. It will be accurate if the button is rebuilt a la `OutlineButton`. 

File: flutter/test/material/theme_defaults_test.dart

**Comment by HansMuller** [comment]
FloatingActionButton shouldn't extend RawMaterialButton. In the future it might extend MaterialButton.

**Comment by willlarche** [comment]
Obsolete.
