### ISSUE TITLE
flutter run

### ISSUE THREAD

**Issue by MohamedSamiKhiari** [flutter/flutter#26310]
Launching lib/main.dart on TRT L21A in debug mode...
Initializing gradle...                                          \
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: d4f0f9394ed92ade)
Crash report written to C:\Users\MSK\Desktop\MSK-WORKS\Flutter Works\app_name\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by JediBurrell** [comment]
Please include the log (`flutter_01.log`).

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Ej-leone** [comment]
am facing the same issue attached below is the log 

[flutter_01.log](https://github.com/flutter/flutter/files/2893592/flutter_01.log)

**Comment by zoechi** [comment]
```
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/ejleone/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip
```

Better to ask on StackOverflow or similar. 
I'd try to restart the computer
