### ISSUE TITLE
Shrine demo has some slow frames on old devices

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26320]
The flutter_gallery_ios32__transition_perf 99th_percentile_frame_build_time_millis benchmark shows that the Shrine demo has some pretty slow frames. We should see what we can do to get its performance back up to what it was before.

cc @willlarche

**Comment by rami-a** [comment]
Checked the benchmarks and it looks like this is no longer an issue. The benchmark went back to green around mid-Feb. Closing this

**Comment by Hixie** [comment]
It's still a few milliseconds slower overall than it was last year, but yeah, it's probably too late to figure out what the issue was. :-(

**Comment by willlarche** [comment]
It’s significantly more widgets than before so probably just expected cost,
no?
