### ISSUE TITLE
ThemeData Primary colour ignored with Brightness.dark

### ISSUE THREAD

**Issue by lucaslcode** [flutter/flutter#26323]
Due to [this line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L162), it's impossible to have a ThemeData that is dark and has a primaryColor. 

Not sure if this is intended behaviour?

This means widgets that use primaryColor are always grey.

**Comment by jonahwilliams** [comment]
primaryColor is initialized to grey with a dark theme only as a default value. `??=` means assign but only when the left-hand side is null. If you want a specific primary color, you can provide it to the ThemeData constructor or update an existing theme data using `ThemeData.copyWith`.

**Comment by lucaslcode** [comment]
Apologies, you're quite right. 

However there's still a problem in that some of the ThemeData values which in a light theme use the primarySwatch automatically when they're not provided, do not do so for a dark theme. 

For example, creating a ThemeData with Brightness.light and primarySwatch Colors.pink automatically sets primaryColor, primaryColorLight, primaryColorDark and accentColor to shades of pink. 

But if it's Brightness.dark, even with primarySwatch as Colors.pink, they'll all be shades of Grey, and the accentColor will be Teal!

Of course, the can all be set individually but it's handy not specifying everything in a simple theme.

**Comment by mattarau** [comment]
@jonahwilliams I think this is still valid and should be reopened.

Your explanation is clear, but that's not what this issue is about. What I think that's important to consider here is that the `primarySwatch` property is a 'shortcut' to set multiple other properties, but currently that's happening ONLY FOR LIGHT BRIGHTNESS. 

So either there's a lack of consistency and this property should be updated to work the same way with any Brightness or it should be renamed to `lightBrightnessPrimarySwatch`. Don't you agree?

**Comment by dancojocaru2000** [comment]
@jonahwilliams This issue is still unresolved despite it being closed. Then `brightness` is set to dark, the `primarySwatch` is ignored and it uses a teal color palette instead. This seems like a wrong behaviour.

**Comment by lrimkus** [comment]
Seems like this was by design:
https://github.com/flutter/flutter/pull/3002

Best quick workaroundu is to specify the following values explicitly:
`toggleableActiveColor` `textSelectionHandleColor` `accentColor` as they all default to teal at the moment.

**Comment by dancojocaru2000** [comment]
Well, I don't quite understand the design decision then.

**Comment by lrimkus** [comment]
cc @HansMuller 

What do you think about changing the following line
https://github.com/flutter/flutter/blob/bf8208cd14a89280676758ce9ddb8c45cb31a199/packages/flutter/lib/src/material/theme_data.dart#L283

    accentColor ??= isDark ? Colors.tealAccent[200] : primarySwatch[500];

to

    accentColor ??= primarySwatch[500];

**Comment by dancojocaru2000** [comment]
Or perhaps another colour based on the swatch but that is not teal.

**Comment by HansMuller** [comment]
@dancojocaru2000, @lrimkus, @mattarau, @lucaslcode  - I've opened a new issue that covers accentColor's future:  Remove accentColor and accentTextTheme from ThemeData et al. #56918.

Any change to the current definition of accentColor would "break" existing app's - typically by causing golden image tests to fail. The long-term plan is to abandon accentColor in favor of ColorScheme.secondaryColor, so rolling out accentColor updates isn't desirable at this time.

**Comment by bartekpacia** [comment]
Any progress on this? It's really annoying.

**Comment by markusaksli-nc** [comment]
Please comment on #19089 with your case as that issue is open and better describes the problem.
