### ISSUE TITLE
Command /bin/sh failed with exit code 255

### ISSUE THREAD

**Issue by pengshengsongcode** [flutter/flutter#26338]
I use Flutter demo HistoryOfEverything，but it can't run,I only add User-Defined - FLUTTER_ROOT,other don‘t change

flutter repositories branch is master

<img width="1440" alt="2019-01-10 11 09 36" src="https://user-images.githubusercontent.com/18256030/50943649-3cf1b900-14c8-11e9-9539-ed7a96bddd78.png">

<img width="1440" alt="2019-01-10 11 11 11" src="https://user-images.githubusercontent.com/18256030/50943709-79251980-14c8-11e9-9823-f7d9d91fc080.png">

**Comment by kangwang1988** [comment]
@pengshengsongcode 
Follow steps below:
```
cd your-flutter-project
flutter run //This will generate right Generated.xcconfig for you. FLUTTER_ROOT is not enough.
```

You don't need to do the custom define FLUTTER_ROOT, it's automatically controlled by flutter.
Closing it now.
Comment here if you think the problem remains after flutter run.

**Comment by sgehrman** [comment]
I'm stuck on this issue.  The Generated.xcconfig looks fine, but it still fails to run that backend script. Command /bin/sh failed with exit code 255

**Comment by hibbert-de** [comment]
> I'm stuck on this issue. The Generated.xcconfig looks fine, but it still fails to run that backend script. Command /bin/sh failed with exit code 255

i have the same issue. if i create a new project it could be build.
echo $FLUTTER_ROOT in terminal gives the correct path to the flutter sdk

the failing command is
`/Users/phil/Library/Developer/Xcode/DerivedData/Runner-foangrvaikzoicbtexjxtjbtzwyx/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh`
i have installed the current version of flutter and osX

any ideas?

**Comment by YogeshSinghNegi** [comment]
> > I'm stuck on this issue. The Generated.xcconfig looks fine, but it still fails to run that backend script. Command /bin/sh failed with exit code 255
> 
> i have the same issue. if i create a new project it could be build.
> echo $FLUTTER_ROOT in terminal gives the correct path to the flutter sdk
> 
> the failing command is
> `/Users/phil/Library/Developer/Xcode/DerivedData/Runner-foangrvaikzoicbtexjxtjbtzwyx/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh`
> i have installed the current version of flutter and osX
> 
> any ideas?

Can you try clearing your drive data folder? Clear project and clean build. I guess you have an issue with drive data.

**Comment by yogesh07-ios** [comment]
Just check  this i am also face this issue
**when we create a project or any other project create a checkout folder should be not a blank space after the folder name**

**Comment by suha-glal** [comment]
me too I am facing the exact same issue
