### ISSUE TITLE
firebase_auth: Unhandled exception in user.reload() if the user is disabled

### ISSUE THREAD

**Issue by kika** [flutter/flutter#26342]
```[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
'dart:async/future_impl.dart': Failed assertion: line 146: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      _FutureListener.handleError (dart:async/future_impl.dart:146:14)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#5      Future._completeError (dart:async/future_impl.dart:494:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#7      _Completer.completeError (dart:async/future_impl.dart:27:5)
#8      _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#9      FirebaseUser.reload (package:firebase_auth/firebase_auth.dart)
<asynchronous suspension>
#10     FireBackend._loadUser.<anonymous closure> (package:cuida/firebacke<…>
flutter: UserInfo change listener: null data
flutter: UserInfoRO change listener: null data
```

The title says it all. I call `reload()` on a user and everything works fine until I disable the user in the Firebase Authentication console. The next `reload()` call bombs out.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

There error output seems to be missing the information about the thrown exception (probably before the part that you posted.

Please also post the code that causes this exception.

**Comment by kika** [comment]
@zoechi Sorry the copy-paste got cut short. But there was only one more line of exception - I've added `#10` to the snippet above. And added two more lines of my own logging just to show that there was nothing else.

**Comment by kika** [comment]
code:

**Comment by kika** [comment]
Tried to upgrade to `firebase_auth` 0.7.0 (tip of the master, actually) which is not released yet. Same results.

**Comment by kroikie** [comment]
Hi @kika looks like on Android this exception is not caught. Did you try this on Android and iOS and if so what were the results? Did it fail on both?

**Comment by kika** [comment]
I'm no longer having this issue on iOS or Android. Instead of assert exception i'm getting correct `PlatformException(ERROR_USER_DISABLED, The user account has been disabled by an administrator., null)`

**Comment by kroikie** [comment]
@kika

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/515. Any further collaboration will be done there.
