### ISSUE TITLE
I had error when symbolicating Flutter engine crash.

### ISSUE THREAD

**Issue by lihui2333** [flutter/flutter#26353]
Integrating Flutter into an existing project, I encountered the Flutter engine crash, i tired to
 symbolize the crash stack according to WIKI (https://github.com/flutter/flutter/wiki/Crashes) 
but this did not work.
![image](https://user-images.githubusercontent.com/38032256/50955014-02514600-14f3-11e9-89c9-223b681d9fd5.png)
![image](https://user-images.githubusercontent.com/38032256/50955350-d8e4ea00-14f3-11e9-8e86-7ef519eabe42.png)

So,how to symbolize the crash correctly.Thanks for your help.

```
flutter doctor
[✓] Flutter (Channel unknown, v1.1.3, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
[✓] VS Code (version 1.30.2)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Looks related to #22313

**Comment by zoechi** [comment]
To investigate we would need a reproduction.

**Comment by kangwang1988** [comment]
Besides, `flutter doctor -v` please.
@lihui2333

**Comment by kangwang1988** [comment]
@lihui2333 
In [https://github.com/flutter/flutter/wiki/Crashes](https://github.com/flutter/flutter/wiki/Crashes)
```
Get the Engine revision from the Framework (this could be automated). https://github.com/flutter/flutter/blob/master/bin/internal/engine.version is the file which contains the information. Substitute the framework hash for master in that url.
```

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
