### ISSUE TITLE
how to implement screenshot method in flutter?

### ISSUE THREAD

**Issue by MistryHiral** [flutter/flutter#26356]
available on this link https://docs.flutter.io/flutter/flutter_driver/FlutterDriver/screenshot.html

**Comment by zoechi** [comment]
Adding an example would be great.

For a quick answer it's better to ask on StackOverflow.

**Comment by kangwang1988** [comment]
@MistryHiral 
If I understand correctly,you're asking how to implement screenshot in flutter code similar to that in `flutter driver`. 
In `flutter driver`, the screenshot is implemented by "shell/simctl/idevicescreenshot". 
In flutter, I think RepaintBoundary can do the trick for you.
For more, visit: [https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderRepaintBoundary/toImage.html](https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderRepaintBoundary/toImage.html)
