### ISSUE TITLE
Animated GIF stop playing after a few minutes

### ISSUE THREAD

**Issue by iptton** [flutter/flutter#26364]
crash with GIF but not JPG.

## Steps to Reproduce

1. run the code : a listview with many Gifs image(using a query to make the ImageCache identify they are different image).
2. scroll listview
3. wait image loaded and ran out the memory to cause **crash**.
4. tap title to make listview load JPG but not GIF, press floating button to add item to listview, scroll listview , **would not crash**

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 100;
  var _tips =  '';

  var _useGIF = true;
  void updateTips(){
    _tips = '''
      currentSize = ${imageCache.currentSizeBytes/1024} 
      maxSize      = ${imageCache.maximumSizeBytes/1024} 
      left            = ${(imageCache.maximumSizeBytes - imageCache.currentSizeBytes)/1024}
      ''';
  }
  void _updateSize() {
    setState(() {
      _counter += 10;
      updateTips();
    });
  }

  @override
  void initState() {
    super.initState();
    updateTips();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: GestureDetector(
            onTap: (){
              setState(() {
                _useGIF = !_useGIF;
              });
            },
            child: new Text('tap to switch ${_useGIF?"GIF":"JPG"} - $_counter (about:${_useGIF?954*_counter:158*_counter}kb)')
        ),
      ),
      body: Stack(
        children: <Widget>[
          Container(

            child:ListView.separated(
                itemCount:_counter,
                separatorBuilder: (_,__) => Container(height: 1,color: Colors.white,),
                itemBuilder: (context,index){
                  return _generateChild(index);
                },),
          ),
          Center(
              child: Container(
                  padding:EdgeInsets.all(10),
                  color: Colors.white,
                  child: Text('$_tips')
              )
          ),
        ],
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _updateSize,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  var _urlGif = 'https://gifimage.net/wp-content/uploads/2017/07/big-gif-15.gif?index=';//954k
  var _urlJPG = 'http://images.huffingtonpost.com/2014-05-26-internet2.jpg?index=';// 158k

  Widget _generateChild(int index){
    var url = '${_useGIF?_urlGif:_urlJPG}$index';
    var image = Image.network(url);
    return Container(child: image,height: 130,color: Colors.black,);
  }
}
```

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D32a, locale
    zh-Hans-HK)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.2)
```
-----------
update 1/11 : @zoechi  after switched to master channel , I cannot reproduce this now.

**Comment by zoechi** [comment]
#24835 might be related. Could you please check if you can reproduce with `dev` or `master` channel? `flutter channel dev;flutter doctor`

**Comment by iptton** [comment]
hi @zoechi good to see crash no happened again.
**But** new problem here :(  the GIF would be still (no animating) after minutes (do nothing for minutes) I don't know if it's relate to this issue.

**Comment by zoechi** [comment]
But the Gif was animating with `[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D32a, locale` on this device, right?

**Comment by iptton** [comment]
@zoechi no, **both** `[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D32a, ` and  master channel  have this problem. At the beginning  GIFs can animating and wait for minutes, items in screen will stop animating.

**Comment by zoechi** [comment]
Ok, I changed the title accordingly to repurpose this issue.

**Comment by bimaldave13** [comment]
HI, 
I am facing the same issue and my problem is a bit related to this.
I have added a gif image widget in listview its animating first time but when I did scroll. It stops animating. 
can anyone suggest me alternative for this?

**Comment by vvasc** [comment]
https://github.com/flutter/flutter/issues/26364#issuecomment-518105892 same here

**Comment by dnfield** [comment]
Is this that the gif stopped playing or that the whole application is OOM crashing?

I know at one point we were retaining _all_ the decoded frames of an animated GIF, and now we don't.  I would expect this not to crash anymore - when I run it on an iPhone 8 locally it does not crash (and iPhones are pretty aggressive about OOM killing you in this kind of scenario).  Going to close this one as not reproducible anymore.
