### ISSUE TITLE
Error opening emulator on Android Studio only for Flutter projects

### ISSUE THREAD

**Issue by d-apps** [flutter/flutter#26362]
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code (version 1.30.2)
[√] Connected device (3 available)
```
============================

I was trying to test my first flutter project on Android Studio, when I try to change the selected emulator I get this error.

![1](https://user-images.githubusercontent.com/20110433/50967823-6eff1d00-14c0-11e9-9fe5-906043e7249b.jpg)
![2](https://user-images.githubusercontent.com/20110433/50967824-6eff1d00-14c0-11e9-84a9-c130303c2f8f.png)

I already removed and created new emulators with different versions but no success.
I have no idea how to **use -read-only flag to enable this feature**, and I couldn't find anything on the internet about that error.

My emulators work fine for my Android projects.

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3064](https://github.com/flutter/flutter-intellij/issues/3064) via [**ZenHub**](https://www.zenhub.com/)
