### ISSUE TITLE
Minor issue with cloning instructions in the event someone downloaded the zip from the repo instead of cloning

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter#26368]
It's a minor thing but could cause a bad first impression for new Flutter users who are trying to install and want to use stable, not beta.

I decided to download the repo today instead of cloning it. When I ran Flutter doctor, I got the following error that I believe would set the channel to `beta`, which is probably not what we want considering 1.0 has already launched. Here is the command line error:
```
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b beta https://github.com/flutter/flutter.git
```
We just probably want to change that to stable. That's all.

**Comment by kangwang1988** [comment]
@ScottS2017 
> I decided to download the repo today instead of cloning it.
Can you explain your steps clear? for example, where and how did you download the repo?

**Comment by zoechi** [comment]
I think he means to replace `-b beta` by `-b stable` in https://github.com/flutter/flutter/blob/master/bin/flutter.bat#L43

**Comment by kangwang1988** [comment]
@Hixie 
What's your opinion towards this?
