### ISSUE TITLE
firebase_ml_vision example about processing byte stream from image

### ISSUE THREAD

**Issue by lewixlabs** [flutter/flutter#26361]
Hi,
in firebase_ml_vision example
https://github.com/flutter/plugins/blob/master/packages/firebase_ml_vision/example/lib/main.dart
i can't find an example to process text recognition from new method FirebaseVisionImage.fromBytes (not file path).

Please can you update this officiale example code to understand how to use
- method FirebaseVisionImage.fromBytes
- Uint8List param (maybe obtained by CameraPreview class of Camera package)
- FirebaseVisionImageMetadata

Thank you!
Lewix

**Comment by kroikie** [comment]
@lewixlabs

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/513. Any further collaboration will be done there.
