### ISSUE TITLE
Floating Button in Front of Other Apps

### ISSUE THREAD

**Issue by Ethermind** [flutter/flutter#26370]
Hi, I need to have a Floating Button in front of Other apps. I read that right now is not possible because iOS don't allow that. But in my case I need it for Android. Is it possible? How could I do that?

**Comment by zoechi** [comment]
You can always make native functionality available to Flutter using plugins https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
