### ISSUE TITLE
download files inside webview flutter

### ISSUE THREAD

**Issue by dineshsayana** [flutter/flutter#26373]
i have a webview (Flutter WebView Plugin) .when user goes to webview and click a link to download a file nothing is happening.
Flutter WebView Plugin : https://pub.dartlang.org/packages/flutter_webview_plugin
Could you please help me

**Comment by jmalickenexient** [comment]
Same here -- any updates?

**Comment by ControlTheBit** [comment]
Any updates on this?

**Comment by MrinalKantiGhosh2196** [comment]
Faced the same problem.
Any updates on this issue ???

**Comment by kw2019ltd** [comment]
same issue pls fix

**Comment by premy** [comment]
Same issue here

**Comment by anthonydonx** [comment]
same problem

**Comment by jomazao** [comment]
:'( same here

**Comment by whiteLT** [comment]
Still waiting :D

**Comment by rlechetaudemy** [comment]
waiting

**Comment by RPComputer** [comment]
Same here, hope it's solved soon

**Comment by alfaruqrizqi18** [comment]
any update?

**Comment by zhuliminl** [comment]
waiting!

**Comment by deandreamatias** [comment]
This package is not from the Flutter team, it is from the Flutter community. They cannot help you here.
The page to report or search for the error is this https://github.com/fluttercommunity/flutter_webview_plugin/issues

Package Flutter: [webview_flutter](https://pub.dev/packages/webview_flutter)
Package flutter community: [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin)

@BondarenkoStas if you can, close this issue please

**Comment by BondarenkoStas** [comment]
@dineshsayana thank you!

**Comment by johnny-stevie** [comment]
So is there any real solution yet to download files in a webview? I am currently using webview_flutter:^0.3.14+1.

**Comment by HassanDev13** [comment]
annyyy solutionnn ?????????

**Comment by ManuLpz4** [comment]
No, any solutions yet. Stop asking lol

**Comment by kamartem** [comment]
please check https://stackoverflow.com/a/59899281/808896 for possible workaround

**Comment by mahendrajmj** [comment]
> please check https://stackoverflow.com/a/59899281/808896 for possible workaround

yes it works but url must be public :)

**Comment by VarunM10** [comment]
I'm still facing this issue can anyone help me out
