### ISSUE TITLE
Cannot draw on top of a ChildView

### ISSUE THREAD

**Issue by ksimbili** [flutter/flutter#2637]
### Steps to Reproduce
- I had a build function returning something like
  new Stack(children: [ChildView, Container]);

This makes the childView to show on top of the container always.

It is reproducible at https://github.com/flutter/flutter/commit/91bcf66389071a6194c3b71431fd5c4dced0f63f

**Comment by abarth** [comment]
Yes, currently child views are drawn on top of everything else.  I need to do some more work in Flutter's compositor to make this work correctly.

**Comment by armansito** [comment]
Gentle ping

**Comment by abarth** [comment]
Thanks for the ping.  Fixing this bug properly is a big chunk of work.

**Comment by armansito** [comment]
Very gentle ping. Any idea for the time frame we can expect this to get fixed (not sure what Flutter 2.0 or later means wrt timing)?

**Comment by abarth** [comment]
I'm not currently working on this issue.  It needs to be prioritized along with the other Mozart/Mojo related work.  As I wrote above, it's a significant chunk of work and we need to make sure it gets scheduled accordingly.

**Comment by armansito** [comment]
Thanks, I can see us getting bit by this in the upcoming months, so please prioritize accordingly.

**Comment by abarth** [comment]
Done.
