### ISSUE TITLE
Put the commit hash in the uploaded artifacts so we can recognize them

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#26380]
These versions are known to the engine and accessible at `//flutter/shell/version/version.h`

**Comment by Hixie** [comment]
What's the use case?

**Comment by rami-a** [comment]
I was thinking similar to the use case for https://github.com/flutter/flutter/issues/26037 in that it would be nice to display it in an about page for the gallery app.

**Comment by dnfield** [comment]
The Java embedding also wants to be able to get this information from the shell.  However this is done, it should be done in such a way that it's exposed in the C++ headers.

/cc @matthew-carroll

**Comment by dnfield** [comment]
Hmm.  Sorry about that, I think I'm mixing something up here - the shell wants the runtime mode, not the version.

**Comment by Hixie** [comment]
I think we should revert this. My original comment never got a compelling answer and without a use case we shouldn't support something. Exposing versions in APIs is rarely a good idea.

**Comment by chinmaygarde** [comment]
We recently looked into using this to make sure the bots were uploading the right versions of engine artifacts to the cloud.

**Comment by Hixie** [comment]
I've been talking to @dnfield about that. I think we can solve that more effectively by just grepping the binary for the version string, no need to expose that to the API.

**Comment by chinmaygarde** [comment]
If you reverted the engine patch, the version strings wont be in the binary :/

**Comment by dnfield** [comment]
Wouldn't they still be there for embedder consumers?  Or they'd get stripped out because nothing actually needs them at runtime?

**Comment by Hixie** [comment]
We can force them to be there, that's not an issue. We don't need to expose the API to embed them.

**Comment by dnfield** [comment]
Reopening this, as it doesn't really seem resolved.

**Comment by chinmaygarde** [comment]
Closing. The hashes are in there because these are now used by the persistent caches to version artifacts. The request for an API to access the same is a Wont-Fix per @Hixie s [comment](https://github.com/flutter/flutter/issues/26380#issuecomment-463005274).

**Comment by dnfield** [comment]
I ended up adding this to the `flutter_test` binary, and it can be viewed via invoking the binary with the --help argument.
