### ISSUE TITLE
Request: Official Webview Widget Needed

### ISSUE THREAD

**Issue by jeffmikels** [flutter/flutter#26381]
A quick search for Flutter packages reveals a number of competing and out of date implementations of the native webview widget:

https://pub.dartlang.org/flutter/packages?q=webview&page=1

Clearly, it's possible to have a working webview, and it's an essential feature for any mobile app that wants to access web content, but the fragmentation isn't helping developers.

Can we have an officially supported WebView widget? Can it be part of the core Flutter widget library?

**Comment by DCrow** [comment]
Isn't [this](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) it?

**Comment by jeffmikels** [comment]
> Isn't [this](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) it?

Technically, yes. It is the official one in the sense that it is maintained in the Flutter plugins repo on github.

However, in practice, it did not appear "official" to me for the following reasons:

* It's only at version 0.2.0.
* The title of it's repo is still "WebView for Flutter (Developers Preview)"
* Searching "webview" on pub.dartlang.org and sorting by relevance puts this "official" plugin at spot  2 underneath "flutter_webview_plugin."

Still, I concede that I was wrong, and that my request is already being worked on by the Flutter Team, so I'll close this issue.
