### ISSUE TITLE
Long press drag on Android selects word and expands selection by words

### ISSUE THREAD

**Issue by xster** [flutter/flutter#26394]

**Comment by xster** [comment]
This is actually implemented in #26001 now but I didn't implement edge scrolling from the drag in that PR.

**Comment by Renzo-Olivares** [comment]
cc @xster what is missing to be able to close this issue? I think the behavior described in the issue is working as expected on master.

**Comment by justinmc** [comment]
It looks to me like long press + drag + edge scroll still doesn't work (there are more than 4 lines of text here):

https://user-images.githubusercontent.com/389558/192354969-dd6cc2d4-4612-461b-a997-9b1eaa46ea0a.mov
