### ISSUE TITLE
Canvas with Scale/Pan in list View. How to disable scroll

### ISSUE THREAD

**Issue by werytert** [flutter/flutter#26414]
Hello. Sorry for my English. Now I have a widget inside listView. Widget has Gesture detector with canvas inside. I catch Scale event with OnScaleStart and OnScaleUpdate, because i need to move image in my canvas. But I can do it only when i start from left or right move. When i start with move to top or buttom my listView is start scrolling. How I can do my task? Thanks

**Comment by JediBurrell** [comment]
Can you provide some code?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/rendering/HitTestBehavior-class.html might help

**Comment by werytert** [comment]
> https://docs.flutter.io/flutter/rendering/HitTestBehavior-class.html might help

So, I tried to set behavior: HitTestBehavior.opaque (and all another) to my GestureDetector, but nothing changes

**Comment by werytert** [comment]
@zoechi So, Summerize, i need to block hits on parent widget, not on child. Now I find solutions only for block hits on child

**Comment by werytert** [comment]
> @zoechi So, Summerize, i need to block hits on parent widget, not on child, and i need to do it from child widget. Now I find solutions only for block hits on child

**Comment by zoechi** [comment]
Please create a question on StackOverflow instead. 
If it actually turns out to be a missing Flutter feature or a bug, please create a new issue with more details.
