### ISSUE TITLE
Use Google and facebook sign in without using firebase

### ISSUE THREAD

**Issue by DeepaVPanicker** [flutter/flutter#26411]
I want to add Google and Facebook sign in without using firebase in my application. I tried but couldn't find any resource to do this.

-->

**Comment by ethanblake4** [comment]
https://pub.dartlang.org/packages/google_sign_in
https://pub.dartlang.org/packages/flutter_facebook_login

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
