### ISSUE TITLE
Keep the splash screen while loading up things in dart

### ISSUE THREAD

**Issue by johrpan** [flutter/flutter#26429]
While the Flutter engine is loading, the Android Activity is showing its background, which can be used for instantly showing a splash screen as indicated in the default project template. It would be strange to transition to a second splash screen for the loading of the actual application. Is there a way to keep the window background except from replicating it using Flutter widgets? Would it be too heavy to make the Flutter view transparent? You could use Container then while loading.

**Comment by degroote22** [comment]
If you load them on the main method before running Flutter then Flutter won't render the first frame and override the splash screen.

Have you tried this?

![captura de tela 2019-01-12 as 12 06 06](https://user-images.githubusercontent.com/12750442/51074134-7c540d00-1662-11e9-8323-fb20930b608d.png)
This is what I'm doing, for instance.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by johrpan** [comment]
@degroote22 This is a really good hint. I somehow thought that main couldn't be async. So I didn't come up with that. Thanks!

@zoechi I'm sorry. I thought this to be some kind of feature request to provide a way to keep the splash screen. So I posted it here.

**Comment by zoechi** [comment]
@johrpan it's fine but it's usually a good idea to ask on StackOverflow first and check community responses before posting as bug report or feature requests.
