### ISSUE TITLE
Can't connect to a device from vs code

### ISSUE THREAD

**Issue by yieniggu** [flutter/flutter#26421]
## Logs

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [VersiÃ³n 6.3.9600], locale es-CL)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.2)
[√] VS Code, 64-bit edition (version 1.29.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Hello, I'm trying to run the code template as my first attempt to work with flutter. I've setted a device with the android studio emulator with charasteristics as follows:

Nexus 5x - api 25 - Nougat 7.1 arm64

I'm working on an amd processor in windows 8.1 aswell. The main issue is when I try to run the emulator inside vs code. It launches the device but after a while it throws the next error:

+Failed to launch emulator: Error: Emulator didn't connected within 60 seconds
Origen: Dart

Even when I try to run the app from android studio it doesn't connect, and doesn't even gives some error message.

I would appreciate any help or recommendation to finally start working with flutter.

**Comment by kangwang1988** [comment]
Launch your emulator, ensure that "adb devices -l" works fine.
```
adb devices -l
List of devices attached
emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:8
```
then 
``` 
cd your-flutter-project
flutter run -v -d emulator-5554
```
Paste the full log if it fails.

@yieniggu

**Comment by yieniggu** [comment]
Hi, thanks for your answer. Here is the log from the cmd:

[ +102 ms] executing: [C:\Program Files\flutter\] git rev-parse --abbrev-ref
--symbolic @{u}
[ +170 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Program Files\flutter\] git rev-parse --abbrev-ref
HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +2 ms] executing: [C:\Program Files\flutter\] git ls-remote --get-url origin

[  +64 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [C:\Program Files\flutter\] git log -n 1
--pretty=format:%H
[  +63 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +2 ms] executing: [C:\Program Files\flutter\] git log -n 1
--pretty=format:%ar
[  +65 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 6 weeks ago
[   +2 ms] executing: [C:\Program Files\flutter\] git describe --match v*.*.*
--first-parent --long --tags
[  +62 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +2 ms] v1.0.0-0-g5391447fa
[ +347 ms] executing:
C:\Users\Bastolo\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +50 ms] Exit code 0 from:
C:\Users\Bastolo\AppData\Local\Android\sdk\platform-tools\adb devices -l
[   +3 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_arm64
           model:Android_SDK_built_for_arm64 device:generic_arm64 transport_id:7

[+1342 ms] C:\Users\Bastolo\AppData\Local\Android\sdk\platform-tools\adb -s
emulator-5554 shell getprop
[+5050 ms] "flutter run" took 6.572ms.
adb not responding

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      AndroidDevice._getProperty
(package:flutter_tools/src/android/android_device.dart:99:9)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform
(package:flutter_tools/src/android/android_device.dart:130:21)
<asynchronous suspension>
#3      RunCommand.usagePath
(package:flutter_tools/src/commands/run.dart:195:68)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:394:38)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:326:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:111:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:111:11)
#25     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#36     main
(file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packag

es/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure>
(dart:isolate/runtime/libisolate_patch.dart:287:32)
#38     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by yieniggu** [comment]
Still isn't working. Forgot to mention that am working offline, if it influences in some way.

**Comment by zoechi** [comment]
Would be great if you could check if online behaves differently.
There were some known issues when no internet was available. I don't know if all are solved.

**Comment by kangwang1988** [comment]
@yieniggu 
Please make sure that "C:\Users\Bastolo\AppData\Local\Android\sdk\platform-tools\adb -s
emulator-5554 shell getprop" can run properly independently(This is a pure adb problem,stackoverflow is a better place).
Then try `flutter run -v -d emulator-5554` again.

**Comment by yieniggu** [comment]
Seems to be connected now, but when running the app it now throws "adb not responding"

**Comment by yieniggu** [comment]
Finally decided to switch to ubuntu, now is working with no problem.

**Comment by sharebuddyapp** [comment]
https://stackoverflow.com/a/56857495/8350143

**Comment by sharebuddyapp** [comment]
https://stackoverflow.com/a/56857495/8350143

**Comment by AdamMusa** [comment]
voici pour moi c'est que s'affiche:
List of devices attached
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 6759
--- adb starting (pid 6759) ---
adb I 07-25 13:29:51  6759  6759 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 07-25 13:29:51  6759  6759 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 07-25 13:29:51  6759  6759 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 07-25 13:29:51  6759  6759 main.cpp:57] 
error: could not install *smartsocket* listener: Address already in use

* failed to start daemon
error: cannot connect to daemon

**Comment by kamleshwebtech** [comment]
is there anyone who solve this issue on MacOS? Please share your suggestion. Thanks al lot.

**Comment by harshvardhansinghgaharwar** [comment]
just create project offline
