### ISSUE TITLE
Read device sound preferences

### ISSUE THREAD

**Issue by I-am-original** [flutter/flutter#26423]
Hey people ) 
Is it possible to read sound preferences from device somehow?
I am not even asking for changing preferences. Just to know if device is in silent mode, if vibration enabled.
Thanks

**Comment by I-am-original** [comment]
@zoechi thank you.
I have found that it is not so important ) but would be cool to have ) 
Cheers

**Comment by zoechi** [comment]
It's not too difficult to create a plugin package https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages
and there are tons of examples

**Comment by I-am-original** [comment]
@zoechi as an option ) Maybe I will do that soon. For now was looking for fast solution.
Thanks one more time.

**Comment by Hixie** [comment]
I think this is something that would be best provided by someone from the community in a package or plugin. It doesn't make much sense for us to have support for this specifically built-in.
