### ISSUE TITLE
AlertDialog ListView docs

### ISSUE THREAD

**Issue by daanvandenhoek** [flutter/flutter#26424]
I found an error in the AlertDialog documentation.

In the code it says the following:
```
  /// The (optional) content of the dialog is displayed in the center of the
  /// dialog in a lighter font.
  ///
  /// Typically, this is a [ListView] containing the contents of the dialog.
  /// Using a [ListView] ensures that the contents can scroll if they are too
  /// big to fit on the display.
  final Widget content;
```

but on the docs page it says this:
```
If the content is too large to fit on the screen vertically, the dialog will display the title and the actions and let the content overflow, which is rarely desired. Consider using a scrolling widget for content, such as SingleChildScrollView, to avoid overflow. (However, be aware that since AlertDialog tries to size itself using the intrinsic dimensions of its children, widgets such as ListView, GridView, and CustomScrollView, which use lazy viewports, will not work. If this is a problem, consider using Dialog directly.)
```

So when I'm coding and reading the inline docs it says that i can use a ListView but on the docs site it says it doesn't

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/blob/6e15572867906bc6400c95baa8a931c6f9c17860/packages/flutter/lib/src/material/dialog.dart#L242

https://github.com/flutter/flutter/blob/e41f1463cd9a7237df89bdec920745c8f7d22b8d/packages/flutter/lib/src/cupertino/dialog.dart#L149

https://github.com/flutter/flutter/blob/6e15572867906bc6400c95baa8a931c6f9c17860/packages/flutter/lib/src/material/dialog.dart#L137
