### ISSUE TITLE
firebase_analytics not reporting in streaming on setCurrentScreen

### ISSUE THREAD

**Issue by RoughIndustries** [flutter/flutter#26432]
If I run the `setCurrentScreen` in the example app in flutter it doesn't show up in the StreamView of Firebase Analytics.  However, if I run `setCurrentScreen` and then I run test standard event types I get all the event types logged and I get the `setCurrentScreen` event.  Is this expected behaviour?  Should I be seeing the `setCurrentScreen` event in the StreamView after I click the button?

**Comment by vargavince91** [comment]
Is it only on iOS or also on Android? I only have this issue on iOS

**Comment by kroikie** [comment]
@RoughIndustries

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/511. Any further collaboration will be done there.
