### ISSUE TITLE
Add template type parameter to `invokeMethod` calls in the plugins repo

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#26431]
https://github.com/flutter/flutter/pull/26303 added a template argument to `invokeMethod`, which triggers the `strong_mode_implicit_dynamic_method` analyzer warning in many call sites in the plugins repo.

We should add the type parameter to all these call sites, but we can only do that after bumping the Flutter dependency constraint which we will only do once the `invokeMethod` change makes it to the stable release.

For now we're suppressing the warning in all call sites (we're not disabling the lint wholesale as we still want it for the rest of the code)

cc @jonahwilliams @Hixie

**Comment by Hixie** [comment]
Next stable release should be February or March; shall we assign this to someone and put it in the April or May milestones?

**Comment by amirh** [comment]
done

**Comment by cyanglaz** [comment]
This is currently blocked by `invokeMapMethod` and `invokeListMethod` crashes when returning value from platform is null. We need wait for that to be fixed to land this.

**Comment by lizhuoyuan** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
    <asynchronous suspension>
    #1      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:28:27)

```

**Comment by cyanglaz** [comment]
To fix this, we are required to bump flutter version to 1.5.0 for plugins that calling invokeMapMethod or invokeListMethod.

**Comment by cyanglaz** [comment]
This is completed, closing the issue.
