### ISSUE TITLE
Problem signing-out from Firebase

### ISSUE THREAD

**Issue by rma6** [flutter/flutter#26447]
I'm having troubble signing-out from Firebase. I'm calling `_signOut()` when I tap a button:
```dart
final GoogleSignIn _googleSignIn = GoogleSignIn();
final FirebaseAuth _auth = FirebaseAuth.instance;

static Future<void> _signOut() async {
    await _auth.signOut();
    await _googleSignIn.signOut();
  }
```
But when I call `googleUser.authentication` on my SignIn function it skips the google login page and returns a valid GoogleSignInAuthentication. It seems that the user is not properly signedOut therefore its data is used `googleUser.authentication`.
What could I do to fix this?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by rma6** [comment]
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.16299.125], locale pt-BR)
    • Flutter version 1.0.0 at C:\Users\Rafael Marinho\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\Rafael Marinho\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\Rafael Marinho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • SM G950F • ce10171a3146842304 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by kroikie** [comment]
@rma6

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/510. Any further collaboration will be done there.
