### ISSUE TITLE
How to use this Expandable search ?

### ISSUE THREAD

**Issue by jagdishjadeja** [flutter/flutter#26452]
I found that there is a expandable search available in material package
https://github.com/flutter/flutter/pull/17629
can someone tell me how to use it ?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
https://github.com/goderbauer/flutter/blob/6c9934d45a481244082e1ecebe267c6cbb98dc2d/examples/flutter_gallery/lib/demo/material/search_demo.dart
