### ISSUE TITLE
cached_network_image library should not be referenced as the way to work with cached images.

### ISSUE THREAD

**Issue by lifenautjoe** [flutter/flutter#26463]
The library [flutter_cached_network_image](https://github.com/renefloor/flutter_cached_network_image) employed in [the website tutorial on cached network images](https://flutter.io/docs/cookbook/images/cached-images) is semi-abandoned with [tons of bugs & missing features](https://github.com/renefloor/flutter_cached_network_image/issues?page=2&q=is%3Aissue+is%3Aopen) to work out.

Using it as part of the official flutter documentation is leading users straight into frustration and disappointment over Flutter.

Please explore alternative and reliable ways to showcase this behaviour or sponsoring the development of this much valued library.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2206](https://github.com/flutter/website/issues/2206) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zoechi** [comment]
Thanks for reporting!
