### ISSUE TITLE
Resolving dependencies... * Error running Gradle: ProcessException: Process

### ISSUE THREAD

**Issue by ehsanalizad** [flutter/flutter#26471]
Somebody help me
when I run command
`flutter run`

The following error occurred
```
-----------------------------------------------------------------------

Resolving dependencies...
* Error running Gradle:
ProcessException: Process "/Users/ehsanalizad/Desktop/cafekitab/android/gradlew"
exited abnormally:
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use
--status for details


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.2.1)
      > Could not get resource
      'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3
      .2.1/builder-3.2.1.jar'.
         > Premature end of Content-Length delimited message body (expected:
         28300680; received: 4456416
   > Could not download protos.jar
   (com.android.tools.analytics-library:protos:26.2.1)
      > Could not get resource
      'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-libra
      ry/protos/26.2.1/protos-26.2.1.jar'.
         > Read timed out
   > Could not download fastutil.jar (it.unimi.dsi:fastutil:7.2.0)
      > Could not get resource
      'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.2.0/fastutil-7.2.0.ja
      r'.
         > Read timed out
   > Could not download guava.jar (com.google.guava:guava:23.0)
      > Could not get resource
      'https://jcenter.bintray.com/com/google/guava/guava/23.0/guava-23.0.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 31s
  Command: /Users/ehsanalizad/Desktop/cafekitab/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
```
-----------------------------------------------------------------------

Flutter version 1.0.0

Gradle version 4.10.2

-----------------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
OS:           Mac OS X 10.12 x86_64

-----------------------------------------------------------------------

I tried the followings

-----------------------------------------------------------------------
```
repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
    }
```
-----------------------------------------------------------------------

and

-----------------------------------------------------------------------
```
 repositories {
        google()
        jcenter()
        movenCentral()
    }
```
-----------------------------------------------------------------------

and 

`./android/gradlew`

:(

**Comment by kangwang1988** [comment]
@ehsanalizad 
I believe it's probably a network problem.
You can open flutterproject/android as a normal android project and sync the gradle dependencies. 
After you resolve it, I think it will also disappear in flutter.
Stackoverflow is a better place to ask this kind of questions.
Closing this issue now.

**Comment by hamidpp** [comment]
go to this path :
'flutter_windows_v1.2.1-stable\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\android'
and open build.gradle file to edit:
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

replace with 👍 buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
this workerd for me
