### ISSUE TITLE
AndroidBuildVersionCodes doesn't exist.

### ISSUE THREAD

**Issue by colinrtwhite** [flutter/flutter#26476]
The documentation for `AndroidBuildVersion#sdkInt` in [device_info.dart](https://github.com/flutter/plugins/blob/master/packages/device_info/lib/device_info.dart#L196) references `AndroidBuildVersionCodes`, which doesn't exist.

**Comment by ened** [comment]
Fixed in https://github.com/flutter/plugins/pull/1092.
