### ISSUE TITLE
for some targets, we can speed up launch times by not checking to see if the app is installed first

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2647]
On android, it takes 400ms - 600ms to check to see if the app is installed. We currently check to see if its installed before running. If we instead try and run, fail, then do the install and re-run, we'll save that checking time for most launches.

Related to https://github.com/flutter/flutter/pull/2631.

**Comment by Hixie** [comment]
@devoncarew Is this still relevant? @jason-simmons was saying in the triage meeting that we might not do this any more?

**Comment by devoncarew** [comment]
I think this is out of date. This was from before we had hot reload, when I was trying to optimize the app install + start time.
