### ISSUE TITLE
Dart language and "code+pkce flow" Question

### ISSUE THREAD

**Issue by BenHayat** [flutter/flutter#26473]
@Flutter Team;
We plan to use Identity Server 4 (https://identityserver.io/) as out authentication server for our .Net REST server and we want to build our native client in Fullter.

I contacted the chief principle of Identity server and asked if they plan to have an client SDK for Flutter
https://github.com/IdentityServer/IdentityServer4/issues/2942#issuecomment-453755458

And he responded as following:

> It looks like Flutter is written in dart. I don't know of any reference implementation in dart for native apps to use code+pkce flow with the system browser, but the two reference implementations for android and iOS are here:

Could flutter team respond to his question either here or directly on the thread I provided above?

We really need a native SDK in Flutter to communicate with IS4.
Thanks in advance

**Comment by zoechi** [comment]
You can always make native functionality available to Flutter using https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages. 
I don't know what

>  code+pkce flow with the system browser

means exactly but I think I have seen authentication plugins that use the browser in https://pub.dartlang.org/.

**Comment by Lords08** [comment]
Yeah I think I need this feature too. Because in my organization, for authentication and authorization always using Identity Server 4. Please consider to make this package for Flutter too.
Thanks :D

**Comment by aaahrens** [comment]
you guys can just use appauth? you should not be using pkce flow natively.

**Comment by CesarD** [comment]
> Yeah I think I need this feature too. Because in my organization, for authentication and authorization always using Identity Server 4. Please consider to make this package for Flutter too.

> you guys can just use appauth? you should not be using pkce flow natively.

This should be the plugin needed for the implementation: https://pub.dev/packages/flutter_appauth
