### ISSUE TITLE
Q: Full Flutter integration with Firebase?

### ISSUE THREAD

**Issue by BenHayat** [flutter/flutter#26483]
Hello Flutter Team;

Since both Firabase & Flutter are owned by Google, Is there plan to integrate these two ends (Client & server), that many steps that we have to write become part of the framework and make the App less error prone and faster to deliver?

Secondly, part of our job to write server side cloud functions, can you allow us to write in Dart language than JS/TS?

Thanks
..Ben

**Comment by zoechi** [comment]
The Flutter team is of course constantly working on improving the experience.

> server side cloud functions, can you allow us to write in Dart language 

You would need to rise this in the Firebase issue tracker.

In the meantime you could use https://pub.dartlang.org/packages/firebase_functions_interop

I'm closing because there is nothing actionable in this issue.
