### ISSUE TITLE
Setting up flutter for contribution.

### ISSUE THREAD

**Issue by Kartik1607** [flutter/flutter#26484]
Hi, I was trying to set up flutter on my system. I followed the steps listed in [official guide here](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment)

The steps are not clear what and how to do after upgrading to latest version using `git pull upstream master`

Running `flutter update-packages` ends up in an error and stops 
```
E:\Personal\FlutterRepo\flutter\packages\flutter>flutter update-packages
Cloning goldens repository...
Running "flutter packages get" in automated_tests...         0.9s
Running "flutter packages get" in complex_layout...          1.0s
Running "flutter packages get" in macrobenchmarks...         0.8s
Running "flutter packages get" in microbenchmarks...         0.9s
Running "flutter packages get" in bots...                    0.8s
Running "flutter packages get" in devicelab...               0.9s
Running "flutter packages get" in android_semantics_testing...  1.0s
Running "flutter packages get" in android_views...           1.0s
Running "flutter packages get" in channels...                1.0s
Running "flutter packages get" in external_ui...             1.0s
Running "flutter packages get" in flavors...                 0.8s
Running "flutter packages get" in named_isolates...          0.5s
Running "flutter packages get" in platform_interaction...    0.8s
Running "flutter packages get" in ui...                      0.9s
Running "flutter packages get" in manual_tests...            0.7s
Running "flutter packages get" in snippets...                0.9s
Running "flutter packages get" in vitool...                  0.8s
Running "flutter packages get" in tools...                   0.7s
Running "flutter packages get" in catalog...                 0.9s
Running "flutter packages get" in flutter_gallery...
The current Flutter SDK version is 0.2.12-pre.2317.

Because flutter_gallery depends on url_launcher >=4.0.0 which requires Flutter SDK version >=0.5.6 <2.0.0, version solving failed.
pub get failed (1)
```

I tried `flutter upgrade` and got the following result

```
E:\Personal\FlutterRepo\flutter>git pull upstream master
From https://github.com/flutter/flutter
 * branch                master     -> FETCH_HEAD
Already up to date.

E:\Personal\FlutterRepo\flutter>flutter upgrade
Upgrading Flutter from E:\Personal\FlutterRepo\flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.2.12-pre.2317 • channel master • https://github.com/Kartik1607/flutter.git
Framework • revision 6c7fb88059 (25 hours ago) • 2019-01-11 23:18:48 -0500
Engine • revision 5722a9685e
Tools • Dart 2.1.1 (build 2.1.1-dev.1.0 f0c7d971c4)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.2.12-pre.2317, on Microsoft Windows [Version 10.0.16299.847], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

*Intellisense* is all broken up inside VS Code as well.

![image](https://user-images.githubusercontent.com/17377741/51081866-82a8be80-1720-11e9-9b6a-bbe40ccff4e5.png)

I would be grateful if someone could help me in upcoming steps.

**EDIT**

Running `flutter packages get` inside *packages/flutter* fixed us issue. There seems to be a problem in **flutter_gallery** It stalls the full packages get pipeline.

**Comment by anuragsanadi** [comment]
the command should have been `flutter packages upgrade`
you need to be in a flutter project directory while running this command and it upgrades any and all packages in your project

https://flutter.io/docs/development/tools/sdk/upgrading 

here are some useful upgrade commands

**Comment by Kartik1607** [comment]
@anuragsanadi that would upgrade packages to latest version and modify **pubspec.yaml** file. This suggests effect is not true required as it would cause merge conflicts to other developers.

**Comment by zoechi** [comment]
>  that would upgrade packages to latest version and modify `pubspec.yaml` file.

you seem to mix up `flutter packages upgrade` and `flutter update-packages`.

`flutter update-packages` is only for migrating examples in the Flutter repo to newer dependency versions, 
while `flutter packages upgrade` or `flutter packages get` do *not* update `pubspec.yaml`. They try to find the newest dependencies matching `pubspec.yaml` `dependencies:` constraints and update the **`pubspec.lock`** file.

**Comment by Kartik1607** [comment]
So `flutter update-packages` brings in packages *latest / newest* packages. (Something like `npm update`) . Does this mean, that `pubspec.yaml` will be updated? If this is case, why is it mentioned in 
[guide here](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment). Wouldn't this cause issues and force other members to update as well? Or is this something different case and I am missing something?

In case of `flutter packages upgrade`, they will try to find *latest* package such that downloaded package is ` <=  the one in pubspec.yaml`

**Comment by Hixie** [comment]
So the first thing we noticed here during the triage meeting looking at this is that somehow you've ended up in a weird state where you don't have all the tags locally. I recommend deleting everything and starting over. Make sure to fork the repo on GitHub, then clone the repo locally without doing anything to reduce how much is downloaded (i.e. just `git clone git@github.com:<your_name_here>/flutter.git` with no additional arguments).

`flutter packages upgrade` runs "pub upgrade" in the current directory. That brings in the packages that that pubspec.yaml uses. Since we pin all our dependencies, this is the same as `pub get`. You shouldn't have to do that for the Flutter repo.

`flutter update-packages` does this in all the directories in the Flutter repo that have a `pubspec.yaml`, and also downloads a couple of additional files (e.g. our lcov file). You should only have to do this occasionally in the Flutter repo, but you do indeed need to do it once you've first downloaded the repo.

`flutter update-packages --force-upgrade` changes all the dependencies to use the latest version, by unpinning them, upgrading everything in one big package, then using the result to update the `pubspec.yaml` files. You shouldn't have to do this unless you're trying to upgrade our dependencies.

`flutter upgrade` tries to update the repo itself to the latest version of Flutter. It doesn't work right for the Flutter repo when you've got a development fork/clone.

**Comment by Hixie** [comment]
@Kartik1607 If deleting everything and starting over doesn't work, I recommend deleting everything again, and then pasting the complete logs of what you're doing. Maybe there's some error message somewhere that can hint to us what the problem is.

**Comment by Kartik1607** [comment]
I got it to work last time. Just to confirm that the process runs smoothly I removed all references and started from scratch. Here is how the journey when

1. After forking the repo, run command `git clone https://github.com/Kartik1607/flutter.git`

```
Cloning into 'flutter'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 151504 (delta 12), reused 10 (delta 6), pack-reused 151478
Receiving objects: 100% (151504/151504), 49.76 MiB | 1.47 MiB/s, done.
Resolving deltas: 100% (115244/115244), done.
Checking out files: 100% (3029/3029), done.
```

2. `cd flutter`

3. Add the upstream pointing to *original flutter repo* 
`git remote add upstream https://github.com/flutter/flutter.git`
```
E:\Personal\FlutterContri\flutter>git remote
origin
upstream
```

4. Added *bin* to path

![image](https://user-images.githubusercontent.com/17377741/51259427-1fde4e00-19d2-11e9-8cd3-8fc6bc8613af.png)

5. Run `flutter doctor -v` for initial testing. It seems, flutter doctor automatically downloads some dependencies like Dart SDK, fonts and few others. Great !

```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine fdfb0e72f0af7b4de3f8cd04ca8519ba5acc12fe...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Downloading Material fonts...                                5.2s
Downloading package sky_engine...                            1.3s
Downloading common tools...                                  4.2s
Downloading windows-x64 tools...                             5.4s
Downloading android-arm-profile/windows-x64 tools...         1.6s
Downloading android-arm-release/windows-x64 tools...         1.8s
Downloading android-arm64-profile/windows-x64 tools...       1.6s
Downloading android-arm64-release/windows-x64 tools...       2.2s
Downloading android-arm-dynamic-profile/windows-x64 tools...  1.5s
Downloading android-arm-dynamic-release/windows-x64 tools...  1.3s
Downloading android-arm64-dynamic-profile/windows-x64 tools...  1.4s
Downloading android-arm64-dynamic-release/windows-x64 tools...  2.3s
Downloading android-x86 tools...                             7.5s
Downloading android-x64 tools...                             4.6s
Downloading android-arm tools...                             2.6s
Downloading android-arm-profile tools...                     6.0s
Downloading android-arm-release tools...                     3.0s
Downloading android-arm64 tools...                           4.8s
Downloading android-arm64-profile tools...                   2.6s
Downloading android-arm64-release tools...                   2.0s
Downloading android-arm-dynamic-profile tools...             5.2s
Downloading android-arm-dynamic-release tools...             2.5s
Downloading android-arm64-dynamic-profile tools...           3.0s
Downloading android-arm64-dynamic-release tools...           2.8s
Downloading Gradle Wrapper...                                0.9s
[√] Flutter (Channel master, v0.2.12-pre.2349, on Microsoft Windows [Version 10.0.16299.904], locale en-US)
    • Flutter version 0.2.12-pre.2349 at E:\Personal\FlutterContri\flutter
    • Framework revision 684d050791 (10 hours ago), 2019-01-16 01:01:51 -0500
    • Engine revision fdfb0e72f0
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 d9944433af)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\AndroidSDK
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at E:\IntelliJ
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

6. Run `flutter update-packages` This *failed* again as was previous case.

```
Cloning goldens repository...
Running "flutter packages get" in automated_tests...        18.8s
Running "flutter packages get" in complex_layout...         20.5s
Running "flutter packages get" in macrobenchmarks...        22.1s
Running "flutter packages get" in microbenchmarks...        21.6s
Running "flutter packages get" in bots...                   19.8s
Running "flutter packages get" in devicelab...              27.9s
Running "flutter packages get" in android_semantics_testing... 23.8s
Running "flutter packages get" in android_views...          29.0s
Running "flutter packages get" in channels...               23.0s
Running "flutter packages get" in external_ui...            19.4s
Running "flutter packages get" in flavors...                20.2s
Running "flutter packages get" in named_isolates...          2.1s
Running "flutter packages get" in platform_interaction...   22.3s
Running "flutter packages get" in ui...                     23.9s
Running "flutter packages get" in manual_tests...            8.0s
Running "flutter packages get" in snippets...               21.2s
Running "flutter packages get" in vitool...                  9.2s
Running "flutter packages get" in tools...                  10.9s
Running "flutter packages get" in catalog...                24.5s
Running "flutter packages get" in flutter_gallery...
The current Flutter SDK version is 0.2.12-pre.2349.

Because flutter_gallery depends on url_launcher >=4.0.0 which requires Flutter SDK version >=0.5.6 <2.0.0, version solving failed.
pub get failed (1)
```

7. Inside the *packages/flutter sub-directory* run `flutter packages upgrade`

```
E:\Personal\FlutterContri\flutter\packages\flutter>flutter packages upgrade
Running "flutter packages upgrade" in flutter...            10.0s
``` 

This fixed up packages problem for *flutter package*. I think I would need to run this command in all directories where there is *pubspec.yaml*. 

What I think is **flutter update-packages** purpose is to run *flutter packages upgrade* is all sub-directories which contain a *pubspec.yaml* file. However, the command **fails and exits even if a single sub-directory fails.** Because it was failing for *flutter_gallery*, the *flutter packages upgrade* was never run on the *packages/flutter sub-directory*. Instead the behavior of *flutter update-packages* should be updated to run until there are no sub-directories left and *not to exit on fail.* I may be wrong but I think it may be the case.

**Comment by anuragsanadi** [comment]
@Kartik1607 your flutter doctor shows that you are not using flutter 1.0 stable. I would recommend downloading the latest stable version from the flutter website

**Comment by Kartik1607** [comment]
This seemed to be some issue with my forked git going out of sync with flutter. The fix was to re-sync the git. This [article](https://stackoverflow.com/questions/15779740/how-to-update-my-fork-to-have-the-same-branches-and-tags-as-the-original-reposit) helped me a lot to get the fork in sync.
