### ISSUE TITLE
Error java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by yagoliveira92** [flutter/flutter#26480]
## Steps to Reproduce

I started the application and I showed this error
I think it's incompatibility with another plugin, the `audio_service`, in both have a call function `int get hashCode` and I don't know what change to repair this error.

## Logs

```
 E/AndroidRuntime( 4390): FATAL EXCEPTION: main
[        ] E/AndroidRuntime( 4390): Process: br.com.tecnocampinfo.radiobasic, PID: 4390
[        ] E/AndroidRuntime( 4390): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null
object reference
[        ] E/AndroidRuntime( 4390):     at io.flutter.plugins.googlemaps.GoogleMapsPlugin.<init>(GoogleMapsPlugin.java:90)
[        ] E/AndroidRuntime( 4390):     at io.flutter.plugins.googlemaps.GoogleMapsPlugin.registerWith(GoogleMapsPlugin.java:30)
[        ] E/AndroidRuntime( 4390):     at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
[        ] E/AndroidRuntime( 4390):     at br.com.tecnocampinfo.radiobasic.MainApplication.registerWith(MainApplication.java:18)
[        ] E/AndroidRuntime( 4390):     at com.ryanheise.audioservice.AudioServicePlugin$ClientHandler$4.onPlay(AudioServicePlugin.java:257)
[        ] E/AndroidRuntime( 4390):     at com.ryanheise.audioservice.AudioService$MediaSessionCallback$1.run(AudioService.java:518)
[        ] E/AndroidRuntime( 4390):     at com.ryanheise.audioservice.AudioService$MediaSessionCallback.play(AudioService.java:534)
[        ] E/AndroidRuntime( 4390):     at com.ryanheise.audioservice.AudioService$MediaSessionCallback.onPlay(AudioService.java:516)
[        ] E/AndroidRuntime( 4390):     at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlay(MediaSessionCompat.java:1259)
[        ] E/AndroidRuntime( 4390):     at
android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlay(MediaSessionCompatApi21.java:194)
[        ] E/AndroidRuntime( 4390):     at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1486)
[   +4 ms] E/AndroidRuntime( 4390):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 4390):     at android.os.Looper.loop(Looper.java:193)
[        ] E/AndroidRuntime( 4390):     at android.app.ActivityThread.main(ActivityThread.java:6669)
[        ] E/AndroidRuntime( 4390):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 4390):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/AndroidRuntime( 4390):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[   +6 ms] I/Process ( 4390): Sending signal. PID: 4390 SIG: 9
[  +66 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

```
flutter analyze
Analyzing radio_basic...                                         
No issues found! (ran in 2.1s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.0.0 at /opt/flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/yagoliveira92/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```

**Comment by Kartik1607** [comment]
The error is thrown at `GoogleMapsPlugin`, please share the code where you are using *Maps*

**Comment by yagoliveira92** [comment]
Of course. I use in page especific:

```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class Contact extends StatefulWidget {
  @override
  _ContactState createState() => _ContactState();
}

class _ContactState extends State<Contact> {
  GoogleMapController mapController;

  final LatLng _center = const LatLng(-10.902260, -37.057088);

  void _onMapCreated(GoogleMapController controller) {
    mapController = controller;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        color: Colors.black12,
        child: Column(
          children: <Widget>[
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                Image(
                  image: AssetImage('assets/logo.png'),
                  height: 130,
                  alignment: Alignment.center,
                ),
              ],
            ),
            Padding(
              padding: EdgeInsets.only(left: 25, bottom: 20),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Text(
                    "A rádio que não cansa você",
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontSize: 30,
                    ),
                  ),
                ],
              ),
            ),
            Column(
              children: <Widget>[
                Text(
                  "Rua Rosário, 425",
                  style: TextStyle(fontSize: 22, fontFamily: "Roboto"),
                ),
                Text(
                  "Santo Antônio, Aracaju/SE",
                  style: TextStyle(fontSize: 18, fontFamily: "Roboto"),
                ),
                InkWell(
                  child: Text(
                    "(79 99950-5505 / 79 3322-2233)",
                    style: TextStyle(fontSize: 18, fontFamily: "Roboto"),
                  ),
                  onTap: () async {
                    await launch("tel:+5579999505505");
                  },
                ),
                InkWell(
                  child: Text(
                    "contato@abcradio.com.br",
                    style: TextStyle(fontSize: 18, fontFamily: "Roboto"),
                  ),
                  onTap: () async {
                    await launch("mailto:contato@abcradio.com.br");
                  },
                ),
                SizedBox(
                  height: 200,
                  width: 200,
                  child: GoogleMap(
                      onMapCreated: _onMapCreated,
                      options: GoogleMapOptions(
                          cameraPosition: CameraPosition(
                        target: _center,
                        zoom: 11,
                      ))),
                )
              ],
            )
          ],
        ));
  }
}
```

**Comment by Kartik1607** [comment]
The code ran fine on my system. Just to make sure have you added a proper maps keys in your config

```XML
<meta-data android:name="com.google.android.geo.API_KEY"
            android:value="YOUR_KEY_HERE />
```

**Comment by yagoliveira92** [comment]
I'm using two plugins: `audio_service`  and `audioplayer` in my project. The audio is playing in background. For to use `audio_service` we need add code in Manifest. My manifest is that:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="br.com.tecnocampinfo.radiobasic">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>


    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->

    <application
        android:name=".MainApplication"
        android:label="radio_basic"
        android:icon="@mipmap/ic_launcher">
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="MY-KEY-HERE"/>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <service android:name="com.ryanheise.audioservice.AudioService">
            <intent-filter>
                <action android:name="android.media.browse.MediaBrowserService" />
            </intent-filter>
        </service>

        <receiver android:name="android.support.v4.media.session.MediaButtonReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>

    </application>
</manifest>
```
and add this class in `app/src/main/java/~package~/MainApplication.java`:

```
package br.com.tecnocampinfo.radiobasic;

import io.flutter.plugin.common.PluginRegistry;
import io.flutter.app.FlutterApplication;

import io.flutter.plugins.GeneratedPluginRegistrant;
import com.ryanheise.audioservice.AudioServicePlugin;

public class MainApplication extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    AudioServicePlugin.setPluginRegistrantCallback(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}

```
I think It's a incompatibility to `audio_service` or `audioplayer`, but where?

**Comment by Kartik1607** [comment]
You have not added an API key to use maps. You need to first register at gcp and get API key for maps, and add it to manifest.

**Comment by yagoliveira92** [comment]
I do It. I just not put my key here, but in my code is right.

**Comment by wouterhardeman** [comment]
Looks related to https://github.com/flutter/flutter/issues/26003. It fails at this line:
```java
this.registrarActivityHashCode = registrar.activity().hashCode();
```
The plugin assumes it has access to an activity, but it doesn't.

**Comment by yagoliveira92** [comment]
I looked for this line but I don't find him. In `audio_service` I found one line, but I commented and not resolved:

```
 @override
  int get hashCode => id.hashCode;
```

**Comment by wouterhardeman** [comment]
@yagoliveira92 The error is in the Google Maps Plugin, look at the stack trace. I meant this line: https://github.com/flutter/plugins/blob/fe03e4072cfb89b1fc0309bb2070a88ea02d4cde/packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapsPlugin.java#L90

**Comment by yagoliveira92** [comment]
Thanks @wouterhardeman , I resolve in this line, write this:

```java
this.registrarActivityHashCode = registrar.context().hashCode();
```
Like the exemple. It's work, but the error is other:

```
E/AndroidRuntime( 4733): FATAL EXCEPTION: main
E/AndroidRuntime( 4733): Process: br.com.tecnocampinfo.radiobasic, PID: 4733
E/AndroidRuntime( 4733): java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/AndroidRuntime( 4733): 	at io.flutter.plugins.googlemaps.GoogleMapsPlugin.registerWith(GoogleMapsPlugin.java:31)
E/AndroidRuntime( 4733): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
```
In code, we have:

```java
 public static void registerWith(Registrar registrar) {
    final GoogleMapsPlugin plugin = new GoogleMapsPlugin(registrar);
    registrar.activity().getApplication().registerActivityLifecycleCallbacks(plugin);
    registrar
        .platformViewRegistry()
        .registerViewFactory(
            "plugins.flutter.io/google_maps", new GoogleMapFactory(plugin.state, registrar));
  }
```
But I can't use `context()` in this case. You have any idea what I can to do?

**Comment by yagoliveira92** [comment]
I found the error. The Google Maps Plugin call the MainApplication for my `audio_service` for create a LifeCycle. Thanks for all support =)

**Comment by Kartik1607** [comment]
I don't get what maps have to do with audio_service.

**Comment by alexelisenko** [comment]
@yagoliveira92 Were you able to resolve the issue? What did you change to fix it?

**Comment by yagoma9** [comment]
@alexelisenko  I do not fixed, I no longer use GoogleMapsPlugin, I use an image when the user clicks, the URL opens the Google Maps application on the phone. It's a jerry-rig fix, but my PO accepted haha

**Comment by yagoliveira92** [comment]
@alexelisenko  I do not fixed, I no longer use GoogleMapsPlugin, I use an image when the user clicks, the URL opens the Google Maps application on the phone. It's a jerry-rig fix, but my PO accepted haha

**Comment by IsaaasI** [comment]
I ma facing the below similar issue...please help.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.beacon, PID: 3892
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
        at org.altbeacon.beacon.BeaconLocalBroadcastProcessor.unregister(BeaconLocalBroadcastProcessor.java:82)
        at org.altbeacon.beacon.BeaconLocalBroadcastProcessor.register(BeaconLocalBroadcastProcessor.java:74)
        at org.altbeacon.beacon.service.ScanJobScheduler.ensureNotificationProcessorSetup(ScanJobScheduler.java:70)
        at org.altbeacon.beacon.service.ScanJobScheduler.schedule(ScanJobScheduler.java:130)
        at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(ScanJobScheduler.java:85)
        at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(ScanJobScheduler.java:92)
        at org.altbeacon.beacon.BeaconManager.applyChangesToServices(BeaconManager.java:1008)
        at org.altbeacon.beacon.BeaconManager.startMonitoringBeaconsInRegion(BeaconManager.java:943)
        at com.example.beacon.MainActivity.startBeaconMonitoring(MainActivity.java:146)
        at com.example.beacon.MainActivity.access$000(MainActivity.java:28)
        at com.example.beacon.MainActivity$1.onClick(MainActivity.java:107)
        at android.view.View.performClick(View.java:6663)
        at android.view.View.performClickInternal(View.java:6635)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26199)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.example.beacon-RXMkf7t7j21H-tgL8nsP0g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.beacon-RXMkf7t7j21H-tgL8nsP0g==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.altbeacon.beacon.BeaconLocalBroadcastProcessor.unregister(BeaconLocalBroadcastProcessor.java:82) 
        at org.altbeacon.beacon.BeaconLocalBroadcastProcessor.register(BeaconLocalBroadcastProcessor.java:74) 
        at org.altbeacon.beacon.service.ScanJobScheduler.ensureNotificationProcessorSetup(ScanJobScheduler.java:70) 
        at org.altbeacon.beacon.service.ScanJobScheduler.schedule(ScanJobScheduler.java:130) 
        at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(ScanJobScheduler.java:85) 
        at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(ScanJobScheduler.java:92) 
        at org.altbeacon.beacon.BeaconManager.applyChangesToServices(BeaconManager.java:1008) 
        at org.altbeacon.beacon.BeaconManager.startMonitoringBeaconsInRegion(BeaconManager.java:943) 
        at com.example.beacon.MainActivity.startBeaconMonitoring(MainActivity.java:146) 
        at com.example.beacon.MainActivity.access$000(MainActivity.java:28) 
        at com.example.beacon.MainActivity$1.onClick(MainActivity.java:107) 
        at android.view.View.performClick(View.java:6663) 
        at android.view.View.performClickInternal(View.java:6635) 
        at android.view.View.access$3100(View.java:794) 
        at android.view.View$PerformClick.run(View.java:26199) 
        at android.os.Handler.handleCallback(Handler.java:907) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
I/Process: Sending signal. PID: 3892 SIG: 9
Disconnected from the target VM, address: 'localhost:8609', transport: 'socket'
