### ISSUE TITLE
How can I clear state after hotreload .Do you consider to offering some way to achive it ？

### ISSUE THREAD

**Issue by AlphaDu** [flutter/flutter#26481]
After hotreload, old state may cause some error. 
for Example: I use bottom tab and render It's child by index

`
child: _widgetOptions.elementAt(index);
`

I switch to last one,  and delete the last widget in array .It will cause error because the widget which corresponding to current index has been deleted.
and I don't know how to clear it except restart app. I don't find solution in doc~ can I clear state forcely in hotreload?

**Comment by kangwang1988** [comment]
Have you ever tried to edit your code to fix the error and rerun the hot-reload procedure?
@AlphaDu

**Comment by AlphaDu** [comment]
@kangwang1988 sorry,I don't undestand.. maybe I did't express clearly~ For example I have three widget . currentIndex  state  deside  which is display .but  I need to delete one of page which is just displaying，then it will cause error bacause hot reload will keep previous state ,but after updating the widget corresponding to the index is not exists. so I need a way to clear state in hotreload rather than restart app.I think keep state in hotreload is convenience in many scene but not all.
 (不好意思，我没有理解你的意思~比如我有三个widget，用index状态决定哪个显示，但是当我删除当前index状态对应的页面就会报错，因为那个页面不在了但是对应状态还是已保留的。所以我需要再hotreload时清除状态而不是重启app。现在在reload时保持状态我认为在很多场景的确很方便，但不是所有)

**Comment by kangwang1988** [comment]
@AlphaDu 
Got it.
hot reload is very useful, it also have some limitations.
If you want to change the default state preserving logic, restart is needed.
For more, refer to: https://flutter.io/docs/development/tools/hot-reload

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/widgets/State/reassemble.html might be what you're looking for.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
