### ISSUE TITLE
using device_info package throws this error file:///Users/usr/flutter/packages/flutter/lib/src/services/platform_messages.dart:7:8: Error: Not found: 'dart:ui' import 'dart:ui' as ui;

### ISSUE THREAD

**Issue by YAPSHUB** [flutter/flutter#26496]
included in `pubspec`: `device_info:  ^0.3.0`

file is imported into a test file located under `test_driver` for integration tests.

Could someone help? what am I doing wrong here?
```
file:///Users/sen/flutter/packages/flutter/lib/src/services/binding.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/font_loader.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/platform_messages.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/platform_views.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/system_channels.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/system_chrome.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/text_editing.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show hashValues, TextAffinity, TextPosition;
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/text_editing.dart:9:1: Error: Not found: 'dart:ui'
export 'dart:ui' show TextAffinity, TextPosition;
^
file:///Users/sen/flutter/packages/flutter/lib/src/services/text_input.dart:7:8: Error: Not found: 'dart:ui'
import 'dart:ui' show TextAffinity, hashValues;
       ^
file:///Users/sen/flutter/packages/flutter/lib/src/services/text_input.dart:16:1: Error: Not found: 'dart:ui'
export 'dart:ui' show TextAffinity;
```

**Comment by zoechi** [comment]
This looks like you are running with `dart ...` instead of with `flutter ...`

`dart:ui` is Flutter-only

**Comment by YAPSHUB** [comment]
I am running flutter integration test, and I have imported the package 'import 'package:device_info/device_info.dart'; into my testfile and acessing device info using this code sample

DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
print('Running on ${androidInfo.model}');  

IosDeviceInfo iosInfo = await deviceInfo.iosInfo;
print('Running on ${iosInfo.utsname.machine}')

**Comment by zoechi** [comment]
Sounds like you are using `dart:ui` or the plugin in the driver test code.
They can only be used in the driven apllucations code.

**Comment by zoechi** [comment]
You can register driver extensions to be able to communicate between driver and app.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
