### ISSUE TITLE
PLZ HELP NEED TO FLUTTER ASAP

### ISSUE THREAD

**Issue by DitoXD** [flutter/flutter#26497]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

flutter doctor
Downloading Dart SDK from Flutter engine e5ec3cf3ea5ce78c6c3116271601f60d30a799d4...
** Resuming transfer from byte position 28487680
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.2M  100 22.2M    0     0  3948k      0  0:00:05  0:00:05 --:--:-- 4228k
/home/reinaldo/flutter/bin/internal/update_dart_sdk.sh: line 63: unzip: command not found

It appears that the downloaded file is corrupt; please try again.
If this problem persists, please report the problem at:
  https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md

**Comment by kyleDEVV** [comment]
I can't see any logs, what version we're you on flutter before? Maybe try reinstalling the whole SDK?

**Comment by DitoXD** [comment]
flutter 1.0.1

**Comment by DitoXD** [comment]
how do i get the logs?
