### ISSUE TITLE
Items in a ListView will refresh when inserting an item to the top

### ISSUE THREAD

**Issue by hankchiutw** [flutter/flutter#26494]
## Steps to Reproduce

I have a `ListView` contains `ListItem` instances which are all stateful widgets. Whenever I press the `floatingActionButton`, a new `ListItem` will be inserted at list's top.

The insertion is ok, but all the other items will refresh(`initState` is called).

This is my [main.dart](https://gist.github.com/hankchiutw/304941ef2ef8c1333c7b6f01c64522ee).

If I add the item to the list end, all the other items will not refresh.

I suppose items should not refresh with insertion too, since each `ListItem` has a key. Am I wrong? or misunderstanding something?

## Logs

This is a sample log:
(`initState` of existing items will execute each time a new item inserted)
```
I/flutter (10880): ListItem initState: [#47a4d]
I/flutter (10880): button onPressed
I/flutter (10880): ListItem initState: [#21660]
I/flutter (10880): ListItem initState: [#47a4d]
I/flutter (10880): button onPressed
I/flutter (10880): ListItem initState: [#01755]
I/flutter (10880): ListItem initState: [#21660]
I/flutter (10880): ListItem initState: [#47a4d]
I/flutter (10880): button onPressed
I/flutter (10880): ListItem initState: [#7b24f]
I/flutter (10880): ListItem initState: [#01755]
I/flutter (10880): ListItem initState: [#21660]
I/flutter (10880): ListItem initState: [#47a4d]
```

No issues found with `flutter analyze`.

Output of running `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.12.6 16G29, locale zh-Hant-TW)
    • Flutter version 1.0.0 at /usr/local/flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/hankchiu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/hankchiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ Flutter requires a minimum Xcode version of 9.0.0.
      Download the latest version or update via the Mac App Store.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.
```

**Comment by Kartik1607** [comment]
> If I add the item to the list end, all the other items will not refresh.

Does the items **only refresh** when you add them to *top/front* ?

>  each ListItem has a key. 

A wild guess but is the *key* the index? If this is case, inserting element at top, would cause index of *each* element to change which would technically cause refresh.

**Comment by hankchiutw** [comment]
More specifically, only items after the inserted item will refresh.

I use `UniqueKey()` to generate the key.

**Comment by tudor07** [comment]
Any updates on this issue?
I struggle a lot with this, it's very common to do this and everytime I need it I have to find all kinds of hacks to make it work and it still doesn't work perfectly. A native solution would be great.

**Comment by zoeyfan** [comment]
https://github.com/flutter/flutter/issues/27057
Related issue seems to be closed in Nov. Please feel free to reopen if you see the issue again.

**Comment by BennyKirschner** [comment]
To anyone with this issue, try holding the stateful widgets outside of the listview or listviewBuilder. Something that keeps the state and actually instantiates them is a stack, you can then access any individual item inside the listview by accessing the widget within the stack.
