### ISSUE TITLE
Dark theme search demo

### ISSUE THREAD

**Issue by jackokring** [flutter/flutter#26501]
Text white in white box.

**Comment by JediBurrell** [comment]
What's the issue?

**Comment by zoechi** [comment]
Please add a link to make it more clear what you are referring to.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
