### ISSUE TITLE
The version configuration in pubspec.yaml is incorrect.

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#26507]
I configured the version in pubspec.yaml:`version: 1.0.1+6`.
But when I run the app to get the version information, Android can print the app version information normally, IOS always prints the version number of 1.0.0+1.
So，do I have to change the version number in xcode?
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.1.5-pre.3, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] IntelliJ IDEA Community Edition (version 2018.2.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by arsen** [comment]
Hi @hahafather007,
For iOS you need to run "flutter build ios" first (from the command line). 
That will update Xcode config.

**Comment by hahafather007** [comment]
> Hi @hahafather007,
> For iOS you need to run "flutter build ios" first (from the command line).
> That will update Xcode config.

Isn't `flutter build ios` use for create package?
Emmmm, I have found another way to solve it, thanks.

**Comment by zoechi** [comment]
Looks like a support request that was solved. Thanks @arsen !
