### ISSUE TITLE
There should be a setMockMethodCallHandler equivalent for EventChannel

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#26528]
I see that `setMockMethodCallHandler` is quite handy for `MethodChannel`, but found no equivalent for `EventChannel`. Here's the current way to mock and test `EventChannel` https://github.com/flutter/plugins/blob/master/packages/battery/test/battery_test.dart#L38

**Comment by ovidiu-anghelina** [comment]
Here is how to mock receiving a message on an EventChannel without actually creating a Mock channel and redirecting your implementation to it:

`defaultBinaryMessenger.handlePlatformMessage("your_event_channel_name", const StandardMethodCodec().encodeSuccessEnvelope(dynamic <your_mocked_message>), (ByteData data) {});`

**Comment by Rexios80** [comment]
I have published [mock_event_channel](https://pub.dev/packages/mock_event_channel) to use until that PR gets merged.

Here is an example of it being used: https://github.com/Rexios80/polar/blob/polar-sdk-5/test/mock_test.dart

**Comment by Rexios80** [comment]
Should this be closed since that PR was merged?
