### ISSUE TITLE
Card does not clip Container with Clip.antiAlias

### ISSUE THREAD

**Issue by matthiasbruns** [flutter/flutter#26523]
I want to build a card with two Containers in it, which have different colors. When doing so, the Card does not clip the corners anymore. I found out, that doing so even with one Container as a direct child will lead to this problem. Here is the code:

```dart
import 'package:flutter/material.dart';

class CardPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Card(
          elevation: 4,
          clipBehavior: Clip.antiAlias,
          child: Container(
            width: 300,
            height: 150,
            color: Colors.green,
            child: Text("TEST"),
          ),
        ),
      ),
    );
  }
}
```

As suggested in other issues, I've tried to use

> clipBehavior: Clip.antiAlias

which does not help. Here is the result of the code:
![wrong](https://user-images.githubusercontent.com/1906627/51114319-3be0c480-1805-11e9-8acc-b2cf5a5ff053.PNG)

And this is the result, when you remove the color from the Container:
![right](https://user-images.githubusercontent.com/1906627/51114334-48651d00-1805-11e9-9113-4d38152a0062.PNG)

Flutter doctor -v

```bash
 flutter.bat doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.16299.904], locale de-DE)
    • Flutter version 1.0.0 at C:\Tools\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\616007\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\616007\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code (version 1.30.2)
    • VS Code at C:\Users\616007\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Moto G 4 • ZY223VLVFW • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.
```

**Comment by Kartik1607** [comment]
Hi, the clipping is occurring. The corners are getting clipped, just that the radius by default is set to 4.0 To enhance the corner clipping effect, you can increase the radius by passing in `shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10.0)),`

**Comment by zoechi** [comment]
Closing as support request that was solved.
Thanks @Kartik1607 !

**Comment by smblee** [comment]
For people who has this issue, my issue was that I had to `Hot Restart`, not just `Hot Reload`.

**Comment by LinusU** [comment]
Hot Restart solved this for me as well, @zoechi do you think we can reopen this since I guess it's a bug that it doesn't show up until after a hot restart? 🤔
