### ISSUE TITLE
Can't run app in AVD emulator

### ISSUE THREAD

**Issue by paexthetiker** [flutter/flutter#26529]
Hi,

I tried the test drive setup from the flutter site but I can't run the app in the emulator.
I'm using Android Studio and got an AVD set up. Even when running, the AVD doesn't show up.
<img width="1338" alt="screenshot 2019-01-14 at 15 46 26" src="https://user-images.githubusercontent.com/1216793/51121362-9420c200-1817-11e9-9eae-64a72b2fc5b9.png">
console output gives me the following:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[!] Connected device

! Doctor found issues in 1 category.

$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to
diagnose potential issues, or visit https://flutter.io/setup/ for
troubleshooting tips.

• Device emulator-5554 is not authorized.
You might need to check your device for an authorization dialog.
```

I checked but can't find any "authorization dialog" as it is mentioned in the output.

It does work in the iOS Simulator, without hot reload however.
I've found the same issue on stackoverflow as well, with no solution so far: https://stackoverflow.com/questions/50336530/cannot-run-flutter-app-on-android-emulator

Help is greatly appreciated!
Thanks and best,
Pascal

**Comment by paexthetiker** [comment]
Here's the adb output:
```
$ adb devices
List of devices attached
emulator-5554	unauthorized
```

**Comment by zoechi** [comment]
Sounds lik https://stackoverflow.com/a/48722416/217408

**Comment by paexthetiker** [comment]
Thanks for your input!

Followed the instructions, but doesn't change anything.
Also deleting and setting up anew doesn't work unfortunately.

**Comment by zoechi** [comment]
Please try `adb kill-server; adb devices`

**Comment by paexthetiker** [comment]
No change also, same output
```
$ adb kill-server
$ adb devices
List of devices attached
emulator-5554	unauthorized
```

**Comment by zoechi** [comment]
It's obviously not a Flutter issue. I'd suggest to search the web for suggestions
instead of me doing the search and suggesting them here ;-)

**Comment by paexthetiker** [comment]
ok, thanks for your effort. 
Searched already and couldn't find anything to fix it, just one open issue with the same problem. That's how I got here. I'll keep on digging...

**Comment by zoechi** [comment]
Searching`emulator-5554	unauthorized` came up with quite a few.

**Comment by paexthetiker** [comment]
Great tip, thanks! :)

**Comment by kangwang1988** [comment]
@paexthetiker 
It seems a pure android problem. I think stackoverflow is a better place for this problem. 
Github issue for flutter is to track flutter bugs and feature requests.
Closing this issue now.

**Comment by Avishka-Shamendra** [comment]
Close and restart Android studio.

**Comment by ganeshp0001** [comment]
As per info given [here](https://stackoverflow.com/questions/46898322/emulator-5554-unauthorized-for-adb-devices/48722416#48722416)
The problem occurs the only emulator that runs on Android Pie others don't.

In Android Studio

Open an Android Virtual Device Manager.
Create a new Virtual Device.
Select any Hardware you want.
Select any System Image which the Target is "(Google APIs)" not "(Google Play)" (If you don't found. Try to look at "x86 Images" tab or "Other Images" tab)
Done!

**Comment by miloudi2439** [comment]
Just restart android studio.

**Comment by AmineBenaddiGitHub** [comment]
1. Exit all emulators
2. Delete ~/.android/adbkey and ~/.android/adbkey.pub
3. adb kill-server
4. adb devices Wipe data of AVD
5. Relaunch emulator

https://stackoverflow.com/questions/55208828/android-emulator-unauthorized/55472090
