### ISSUE TITLE
the color detected by FSCapture doesn't match the specified RGB value on Android emulator running on macOS

### ISSUE THREAD

**Issue by wwervin72** [flutter/flutter#26525]
hi, i have some problem in using colors, pls help me, my view's color is not same with my codes color. this is my code.

```dart
import "package:flutter/material.dart";

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'flutter app',
      home: Scaffold(
        body: Column(
          children: <Widget>[
            Container(
              width: 400.0,
              height: 500.0,
              color: Color.fromARGB(255, 19, 27, 45),
              child: Center(
                child: Container(
                  width: 200.0,
                  height: 200.0,
                  color: Color.fromARGB(255, 32, 45, 73),
                ),
              ), 
            )
          ]
        )
      ),
    );
  }
}
```

in my codes, outer container use color `Color.fromARGB(255, 19, 27, 45)`, inner container use `Color.fromARGB(255, 32, 45, 73)`.

this is view in my Simulator
![image](https://user-images.githubusercontent.com/17847729/51116922-563b9200-1847-11e9-9841-b990ff1c7f89.png)
i use FSCaputure to draw color, the outer's rgb result is `21,28,46`, the inner is `34,46,72`

The changes in this example are small, but sometimes they change a lot. how can i do?

 pls forgive my poor english. thanks very much.

**Comment by zoechi** [comment]
What is the expected behavior?
How is FSCapture involved? 
I found http://www.faststone.org/FSCapturerDownload.htm. Is this what you are referring to?

**Comment by wwervin72** [comment]
my designer gives me HEX color, i transform it into RGB, and set alpha value is 255 
example HEX color `#131B2D`, i transform to `Color.fromARGB(255, 19, 27, 45)`, bu the view real HEX color is `##151C2E`
![image](https://user-images.githubusercontent.com/17847729/51118123-94868080-184a-11e9-981e-9928e410c1d4.png)

**Comment by csells** [comment]
I've seen this, too. I'd like to know what's going on here as well.

**Comment by xster** [comment]
@jason-simmons might you know what's going on here?

**Comment by jason-simmons** [comment]
This may be happening because Android emulator configurations typically use a framebuffer with 16-bit color depth by default.

If the AVD virtual device config file specifies `hw.lcd.depth = 16` then try changing it to 32.
