### ISSUE TITLE
Selection Controls feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2652]
- [x] checkbox:  animation does not seem correct. box shrinks and grows, but I think it should maintain the same. No ripple?
- [x] radio: no ripple?
- [x] toggle: no ripple?

**Comment by abarth** [comment]
Does "no ripple" mean that we're missing some visual element from these?  If so, is there something in the spec or some example to show what this visual element is supposed to be?

**Comment by sethladd** [comment]
Have asked for clarification. On other apps, I see a ripple in the background when I tap a toggle, fwiw. (YouTube preferences, e.g.)

**Comment by abarth** [comment]
@sethladd I believe the checkbox is supposed to shrink and then grow.  At least, that's what the Java implementation in Android does if you record the screen and play it back in slow motion.  Are there any reference in the spec for how checkboxes should animate?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (412/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:55051 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMV-000ahl-UJ
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:09 +0100
Date: Mon, 14 Mar 2016 11:08:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457978885;
	bh=L1g8SbRyw9N9t9C5m+pD2BGYPSIb/vON6Y6csragJVE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jlSTH0k/JnUMtT7EaktwLUlaZjNJeBnGxKD2Ma8v6etOzqofIq2MgqexxPajfgTJy
	 tI5TysJDiWQNEzPFthzxZGv5tkiMzi0bxX/uPXK4f7Z8zVDmGwZPlTDzEFgd3J7SJ7
	 jkjf6t6w8TCuMA0l5nKt7Vtq/QaS98NlCfBY9//I=

**Comment by abarth** [comment]
I'm not sure precisely what animation the material spec wants here.  I've updated the selection controls to have a ripple that starts at the touch location: https://github.com/flutter/flutter/pull/3022

It would be very valuable to have a video of exactly what animation the material design team wants.  I'm happy to make the animation pixel perfect to whatever they want, but I need to know what that is.
