### ISSUE TITLE
Tabs feedback

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2653]
From an internal review.

- [ ] can tab bar be positioned bottom?
- [ ] follow spec type guidelines. 
- [ ] is the component flexible: i.e. icons only, text only, color changes to text/icons, color changes to tab indicator.

**Comment by HansMuller** [comment]
> can tab bar be positioned bottom?
A TabBar can appear anywhere, it's just a widget. Does the MD include examples of a tab bar outside of the "app bar"?

 > follow spec type guidelines.
Not entirely sure what this means. Currently we don't switch from 14 to 12 point for tab label text that wraps to a second line, so maybe that?

> is the component flexible: i.e. icons only, text only, color changes to text/icons, color changes to tab indicator.

We support all of listed combinations for TabLabels. Colors for text, icons, and the indicator can be overridden by wrapping the TabBar in a Theme and/or IconTheme widget. On can also specify a TabLabel iconBuilder function, which can be used to label the tab with an arbitrary widget.

**Comment by sethladd** [comment]
I'll open a specific bug for the "shrink label text when wrapping". Meanwhile, going to close and we can open any individual issues along the way.
