### ISSUE TITLE
firebase_messaging control on notification

### ISSUE THREAD

**Issue by 1abzar** [flutter/flutter#26531]
Hi,
In my app , I used FCM and have problem to control the notification (for example to remove/hide them programmatically), or use Vibration on recieve a notification or group messaging by tag of the message.
how can I do that ? I can't find any way!
thanks

**Comment by zoechi** [comment]
I think you need to use background execution to receive the messages and display them yourself like packages as `local_notifications` do.

Related #22072, #19076, #17482

**Comment by dspoonia7** [comment]
Any updates here?

**Comment by kroikie** [comment]
@1abzar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/508. Any further collaboration will be done there.
