### ISSUE TITLE
How to make kenburn effect

### ISSUE THREAD

**Issue by xesun** [flutter/flutter#26535]
Same like https://github.com/flavioarfaria/KenBurnsView/raw/master/anim.gif

**Comment by KevinTheGray** [comment]
@xesun here's a quick example of a kenburns like effect. 

https://gist.github.com/KevinTheGray/f1a5c71a6548154ba7fa98912183d75c

 The trick is to oversize the image using a Positioned widget in a Stack, then animate the position.  You could get a zooming effect by animating the width/height.

**Comment by zoechi** [comment]
@xesun Do you think there is still something that needs to be done by the Flutter team?
