### ISSUE TITLE
It's not always possible to know when a dialog is dismissed.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#26542]
When a dialog is dismissed, it must be possible to run a callback.

Consider this code:
```dart
    Future<T> showDialog <T>({
        @required BuildContext context,
        bool barrierDismissible: true,
        WidgetBuilder builder
        })
```

There are 3 ways to close a dialog:
    1) Pressing some button on the dialog that closes it.
    2) Tapping the barrier.
    3) Pressing the Android back button.

Currently only the first one allows us to fire a callback. That's very bad. 

Please, create a `onBarrierDismissed` callback field, like this:
```dart
    Future<T> showDialog <T>({
        @required BuildContext context,
        bool barrierDismissible: true,
        VoidCallback: onBarrierDismissed, 
        WidgetBuilder builder
        })
```

Then pass it down to `modal_barrier.dart`, where instead of this:

```dart
    onTapDown: (TapDownDetails details) {
            if (dismissible) Navigator.maybePop(context);
          },
```
It should do this:
```dart
    onTapDown: (TapDownDetails details) {
            if (dismissible) {
                Navigator.maybePop(context);
                if (onBarrierDismissed != null) onBarrierDismissed();
             }
          },
```

**Comment by ketchup208** [comment]
any news about this ?

**Comment by werainkhatri** [comment]
@marcglasberg
as you said: 

There are 3 ways to close a dialog:
1) Pressing some button on the dialog that closes it.
2) Tapping the barrier.
3) Pressing the Android back button.
Currently only the first one allows us to fire a callback. That's very bad.


I guess WillPopScope can be used to listen to the rest
although, it is not possible to distinguish b/w them, but i guess it is something.

    showDialog(
        context: context,
        child: WillPopScope(
            child: *required widget*,
            onWillPop: () {
              // listen Android Back Button Pressed
              return Future.value(true);
            }));

Cheers!

**Comment by Fleximex** [comment]
To add on this:

**1. Tapping some button**
Return data via Navigator.pop
**3. Android back button**
What @werainkhatri said. Use WillPopScope.

**2. So that leaves the barrier.**
If you have a confirmation dialog like this:
```
Future<bool> _showConfirmationDialog(BuildContext context, String action) {
  return showDialog<bool>(
    context: context,
    barrierDismissible: true,
    builder: (BuildContext context) {
      return AlertDialog(
        title: Text('Do you want to $action this item?'),
        actions: <Widget>[
          FlatButton(
            child: const Text('Yes'),
            onPressed: () {
              Navigator.pop(context, true); // showDialog() returns true
            },
          ),
          FlatButton(
            child: const Text('No'),
            onPressed: () {
              Navigator.pop(context, false); // showDialog() returns false
            },
          ),
        ],
      );
    },
  ) ?? false;
}
```
With the  `??` you check for the dialog to return null (so when the barrier is tapped) and for example return `false` if that's the case.

With these 3 methods of returning data you should write a custom class with which you determine the way of closing the dialog. When closing a dialog return an instance of that class:
```
enum DialogCloseMethod
{
  AndroidBack,
  Barrier,
  Button,
}

class DialogResult
{
  final bool hasConfirmed;
  final DialogCloseMethod dialogCloseMethod;
  
  DialogResult(
    this.hasConfirmed,
    this.dialogCloseMethod,
  );
}
```

Of course if you want to reuse this and/or don't only want boolean return results, it is best to create a generic type:
```
class DialogResult<T>
{
  final T result;
  final DialogCloseMethod dialogCloseMethod;
  
  DialogResult(
    this.result,
    this.dialogCloseMethod,
  );
}
```

**Comment by fluttercorner1** [comment]
Here is Step By Step Guide to [how to dismiss an alertdialog on a flatbutton click](https://flutterq.com/how-to-dismiss-an-alertdialog-on-a-flatbutton-click/)

**Comment by flutterq** [comment]
Step By Step Guide to [how to dismiss an alertdialog on a flatbutton click?](https://flutterq.com/wp-admin/post.php?post=253&action=edit)

**Comment by MehediEhteshum** [comment]
Correct me if I'm wrong.
Isn't it always possible to know when a `AlertDialog` is dismissed by using its `dispose()` method?
By simply doing the followings-

- Extract the `AlertDialog` widget and make it a `StatefulWidget`.

- A `StatefulWidget` always calls `dispose()` when it ends/pops. So you can do any specific actions inside that function that you wanna do when the `AlertDialog` is dismissed.

- It will help you when the `AlertDialog` is dismissed using Android back button or click on Barrier/outside. You might need to take extra precautions for any buttons used on the `AlertDialog` itself i.e. detecting that button click separately and thus avoiding any actions that you wanna do only when Android back button or click on Barrier/outside is used to dismiss the `AlertDialog`.

For example, say you are using a `TextButton` on `AlertDialog`.

```
TextButton(
      child: const Text(
        'Continue',
        softWrap: true,
      ),
      onPressed: () {
        setState(() {
          isContinueButtonPressed = true;
        });
        Navigator.of(context)
            .popAndPushNamed(SomeScreen.routeName);
      },
    )
```
Then in the `dispose()`, do something like this-

```
@override
void dispose() {
 if (!isContinueButtonPressed){
   // do your actions if 'continue' button on AlertDialog is not pressed
 } 
 super.dispose();
 }
```

**Comment by Qwampa** [comment]
Still waiting for a solution on this, as I want to implement different code on barrier dismiss and android back button events.

**Comment by marcglasberg** [comment]
Now, in `assorted_layout_widgets`, since version 4.0.9: 

## showDialogSuper

The `showDialogSuper` is identical to the native `showDialog`, except that it lets you define a callback for when the dialog is dismissed:

```
showDialogSuper(
   context: context,
   onDismissed: () { print("Dialog dismissed"); }
   builder: ...
} 
```

Usually there are 3 ways to close a dialog:

1) Pressing some button on the dialog that closes it (usually by calling `Navigator.pop(context)`).
2) Tapping the barrier.
3) Pressing the Android back button.

All three ways will result in the `onDismissed` callback being called.

Try running
the <a href="https://github.com/marcglasberg/assorted_layout_widgets/blob/master/example/lib/main_show_dialog_super.dart">
showDialogSuper Example</a>.

For those who don't want to include my package (shame on you!) here is the source-code: https://github.com/marcglasberg/assorted_layout_widgets/blob/master/lib/src/show_dialog_super.dart

**Comment by guidezpl** [comment]
Using `WillPopScope` works but is not necessary. Let illustrate @Fleximex's [comment](https://github.com/flutter/flutter/issues/26542#issuecomment-692053499). For all three cases, we can use the fact that `showDialog` returns a Future which:
- resolves to `null` if the dialog was dismissed
- will resolve to some value passed in to `Navigator.pop` (here, a `bool`).

```
TextButton(
  child: const Text('Press to open dialog'),
  onPressed: () async {
    bool? result = await showDialog<bool>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Accept terms'),
          actions: [
            TextButton(
              child: const Text('No'),
              onPressed: () {
                Navigator.pop(context, false);
              },
            ),
            ElevatedButton(
              child: const Text('Yes'),
              onPressed: () {
                Navigator.pop(context, true);
              },
            ),
          ],
        );
      },
    );
    if (result == null) {
      print('dialog dismissed (by tapping the modal barrier or Android back button)');
    } else {
      if (result == true) {
        print('terms accepted');
      } else {
        print('terms rejected');
      }
    }
  },
),
```

Therefore, I'm closing this issue.

As an aside, in my eyes, tapping the modal barrier or the Android back button are equivalent means of dismissing a dialog, so there is no need to distinguish between them.
