### ISSUE TITLE
Flushbar Package development issue

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#26540]
I have a Flutter package that is presenting some weird behavior on iOS but it is working fine on Android even though I have no distinct platform code inside. Please, take a look at the following [issue](https://github.com/AndreHaueisen/flushbar/issues/24#issuecomment-454133663).

This looks like a Flutter bug. If not, can someone shed some light over the issue, please?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
