### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by gaojuanjuan** [flutter/flutter#26555]
![image](https://user-images.githubusercontent.com/14133759/51153013-7865fc00-18a9-11e9-86e5-8651c9f42e21.png)
![image](https://user-images.githubusercontent.com/14133759/51153023-861b8180-18a9-11e9-93fd-b5fbc390d8d6.png)

**Comment by zoechi** [comment]
Can you please post the error output as text?

Please add the output of `flutter doctor -v`.

Please check also StackOverflow for similar errors.

To investigate we would need a minimal reproduction.
Can you share such a project on GitHub?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
