### ISSUE TITLE
FR: Receive mouse scroll wheel events

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2656]
I don't think this is currently possible but would be useful in some situations.

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/757

**Comment by eseidelGoogle** [comment]
This is not currently on our near-term horizon.  I recommend we close this and consider re-opening if needed sooner.

**Comment by eseidelGoogle** [comment]
Pink doesn't need this any time soon.  Closing (again).  Please re-open if needed.
