### ISSUE TITLE
Issue with creating sub-collection in Firestore from Flutter app.

### ISSUE THREAD

**Issue by ueabu** [flutter/flutter#26561]
Hi, 

I am trying to create a sub-collection in a document from my flutter app but everything I try keeps making the app to crash. So far, I have tried this 

`Firestore.instance
      .collection('/path')
      .document("documentPath")
      .collection('/subCollectionPath')
      .document()
      .setData({
    'TestData': "Data",
  }).then((onValue) {
    print('Created it in sub collection');
  }).catchError((e) {
    print('======Error======== ' + e);
  });`

and I have also tried this 
`Firestore.instance .collection('/path') .document("documentPath") .collection('/subCollectionPath').reference() .document() .setData({ 'TestData': "Data", }).then((onValue) { print('Created it in sub collection'); }).catchError((e) { print('======Error======== ' + e); });`

But Both seem to crash the app with the error message below

`*** First throw call stack:
(
        0   CoreFoundation                      0x0000000111ae01bb __exceptionPreprocess + 331
        1   libobjc.A.dylib                     0x000000011107e735 objc_exception_throw + 48
        2   Runner                              0x000000010ca9a7b1 -[FIRFirestore documentWithPath:] + 257
        3   Runner                              0x000000010cd3062c getDocumentReference + 124
        4   Runner                              0x000000010cd33879 -[FLTCloudFirestorePlugin handleMethodCall:result:] + 2665
        5   Flutter                             0x000000010e1e39a2 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
        6   Flutter                             0x000000010e200616 _ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
        7<…>
Lost connection to device.`

Flutter doctor -v output 

`[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/umaabu/Documents/Flutter/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/umaabu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • iPhone XS  • 40450D65-02DC-469E-A296-512F5E21F3A3     • ios • iOS 12.1 (simulator)

• No issues found!`

What is the right way to create sub-collections from the app

**Comment by flowhorn** [comment]
When you reference a (sub)-collection using the cloudfirestore Plugin, you don't need to use the '/'.
Therefore write instead: 
Firestore.instance 
.collection('path') .document("documentPath") .collection('subCollectionPath')

**Comment by ueabu** [comment]
That worked. Thank you very much

**Comment by VarthanV** [comment]
it didn't work

**Comment by islemkehoul** [comment]
when i try to create a collection it wont show on cloud firestore's database ? 

Firestore.instance.collection('users').add({
     'email' : user.email,
      'password' : user.uid
    }).then((value){
          
         Navigator.of(context).pushReplacementNamed('/Home');
          }).
         catchError((e){
            print(e);
          });
