### ISSUE TITLE
statusBarIconBrightness not working 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#26578]
## Steps to Reproduce

```dart
void main () => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("Appbar")),
        body: MyPage(),
      ),
    );
  }
}

class MyPage extends StatelessWidget {
  MyPage() {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.blue,
      statusBarIconBrightness: Brightness.dark, // not working
      systemNavigationBarColor: Colors.blue,
      systemNavigationBarIconBrightness: Brightness.dark, // works
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

`systemNavigationBarIconBrightness` seems to work for both `Brightness.dark` and `Brightness.light` but `statusBarIconBrightness` fails. 

## Screenshot
![image](https://user-images.githubusercontent.com/40364434/51170700-128f6980-18d5-11e9-94e5-7c5b8196cad8.png)

## Flutter Doctor
```
✓] Flutter (Channel beta, v1.0.1-pre.1, on Mac OS X 10.14 18A389, locale en-GB)
    • Flutter version 1.0.1-pre.1 at /flutter
    • Framework revision 2f60afca7a (2 weeks ago), 2018-12-29 14:11:09 +0530
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chocolate/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.blue,
      statusBarIconBrightness: Brightness.dark, // not working
      systemNavigationBarColor: Colors.blue,
      systemNavigationBarIconBrightness: Brightness.dark, // works
    ));

    return MaterialApp(
      home: Scaffold(
//        appBar: AppBar(title: Text("Appbar")),
        body: MyPage(),
      ),
    );
  }
}

class MyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Comment by dark-chocolate** [comment]
@zoechi  Thanks it worked, but why do we need to exclude `AppBar`, does docs somewhere mention to exclude it then only `statusBarIconBrightness` would work? I think it is a bug, or what do you say is it expected behavior?

**Comment by zoechi** [comment]
https://stackoverflow.com/a/51013116/217408

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by dark-chocolate** [comment]
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
I thought it's a bug, because in the same thread (of stackoverflow) I had also provided the solution, so it is not like I didn't search it. 

I request Flutter team to mention that in docs too.

**Comment by zoechi** [comment]
Fair enough.

However

> However, the AppBar widget automatically sets the system overlay style based on its AppBar.brightness, so configure that instead of calling this method directly. Likewise, do the same for CupertinoNavigationBar via CupertinoNavigationBar.backgroundColor.

https://docs.flutter.io/flutter/services/SystemChrome/setSystemUIOverlayStyle.html

**Comment by dark-chocolate** [comment]
Sorry, it was my mistake, docs did mention that. I missed it. 

But one more thing, docs tells you to use the AppBar's brightness instead, so if I use 

```
appBar: AppBar(title: Text("Appbar"), brightness: Brightness.dark),
```
with/without including `statusBarIconBrightness: Brightness.dark`, it is still not working.

**Comment by dark-chocolate** [comment]
@zoechi Could you please reopen this issue?

**Comment by ishaanbahal** [comment]
@dark-chocolate Hoping you've solved it by now, but if you haven't, you gotta use the other brightness in case of appBar. If you want the status bar icons dark, then choose `Brightness.light` for app bar brightness and vice versa.

https://github.com/flutter/flutter/blob/9f35f6c3a69263266d4db5acfb3eb95fac08e7bd/packages/flutter/lib/src/material/app_bar.dart#L578#L580

This is the code:

    final SystemUiOverlayStyle overlayStyle = brightness == Brightness.dark
      ? SystemUiOverlayStyle.light
      : SystemUiOverlayStyle.dark;

Hope this is helpful.

**Comment by dark-chocolate** [comment]
@ishaanbahal  Interesting, last time when I checked this code, it wasn't working but after updating to the latest Flutter version, the `AppBar` `brightness` started working, and not to mention following has no effect on the brightness. 

```
 SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        statusBarBrightness: Brightness.dark // no effect as long as you are using standard AppBar
    ));
```

**Comment by ariefwijaya** [comment]
@zoechi I've tried the solution but still doesnt work on my emulator :

- Device: Android Emulator NEXUS_5X_API_22 API 22
- OS: Android 5.1.1

**Comment by abusaadp** [comment]
@dark-chocolate  Please re-open this issue. statusBarIconBrightness for Brightness.light is not working in Android. The status bar icon always remain white in color.

**Comment by Lppapineau** [comment]
Yo, you can wrap your Scaffold with SafeArea Widget and keep your AppBar :) ! Thank zoechi.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.blue,
      statusBarIconBrightness: Brightness.dark, // not working
      systemNavigationBarColor: Colors.blue,
      systemNavigationBarIconBrightness: Brightness.dark, // works
    ));

    return MaterialApp(
      home: SafeArea(
                    child: Scaffold(
                      appBar: AppBar(title: Text("Appbar")),
                      body: MyPage(),
                    ),
                  )
    );
  }
}

class MyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
