### ISSUE TITLE
Firebase ML kit operation progress

### ISSUE THREAD

**Issue by thedejifab** [flutter/flutter#26576]
As at the time of creating this issue, there's no way to monitor the progress of a Firebase ML kit operation such as text recognition performed over a network. 

It's possible that I just use a CircularProgressIndicator until the Future in which I'm running the operation is complete but I think this would make for a good UX since users can now know how far their ML recognition process has gone in percentage.

Something like this is possible in Firebase Storage Upload, but I've scratched through the ML kit docs and found nothing like it.

**Comment by kroikie** [comment]
@thedejifab

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/507. Any further collaboration will be done there.
