### ISSUE TITLE
Flutter Plugins import critical bug (along with my hacky fix)

### ISSUE THREAD

**Issue by function1983** [flutter/flutter#26573]
## Steps to Reproduce

1. Import
```
dependencies:
   shared_preferences: ^0.4.3
```

2. Flutter will complain
`Cannot resolve import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin`
in GeneratedPluginRegistrant.java and just stop compiling

3. Remove `shared_preferences: ^0.4.3` in pubspec.yaml and `flutter clean` doesn't help. Flutter still produce the same error.
Notice that `shared_preferences` is still listed under `External Libraries/Flutter Plugins` for some reasons.

4. I then import `shared_preferences` using `path`
```
shared_preferences:
   path: ../shared_preferences
```
`shared_preferences` is still listed under `External Libraries/Flutter Plugins`. Same error.

5. Then I remove `shared_preferences` in pubspec.yaml and manually imported `shared_preferences` inside android gradle.
`shared_preferences` is still listed under `External Libraries/Flutter Plugins`. Same error.

6. Now I remove `shared_preferences` in android gradle and DELETE `shared_preferences` inside `External Libraries/Flutter Plugins` (using the delete on the keyboard). `shared_preferences` is no longer listed
Run `flutter clean`
Run `flutter run`
Now here is the strange part: `shared_preferences` will come back under `External Libraries/Flutter Plugins` and I am able to use it inside flutter without problem (program works fine).
Notice that `shared_preferences` is not in `pubspec.yaml`

I am glad that it works out in the end but this is a very strange bug.
## Logs

```
```

```
Analyzing camera_app...                                           

   info • Unused import: 'package:camera_app/videoplayer.dart' • lib/main.dart:2:8 • unused_import

1 issue found. (ran in 2.6s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.8-pre.13, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.30.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Please add the full error output.

**Comment by zoechi** [comment]
This looks like it is related to your attempt to work around.
I'd be more interested in the original error before you started to work around.

**Comment by function1983** [comment]
Hi @zoechi , I understand.

This error happened to me before in another project. Now it comes back so I think it worth a bug report. I will try to recreate the error in a clean project (I have deadline so maybe later on). The console error is very short and simple (only the `cannot resolve symbol` part is significant, wish I had taken a screenshot). Please mark as **waiting for customer response** again.

Thank you.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
