### ISSUE TITLE
Add IPv6 loopback address to Doctor's proxy check if localhost resolves to it

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#26587]
If `HTTP_PROXY` is set we currently check that `127.0.0.1` and `localhost` are in `NO_PROXY` but we don't check for the IPv6 loopback (`::1`). Since `localhost` may resolve to it, we should check it too, but in order to avoid showing warnings to lots of people that may not be using IPv6 we should first check if `localhost` resolves to it.

(see https://github.com/flutter/flutter/issues/14991#issuecomment-454428345).

**Comment by MrBirb** [comment]
@DanTup #95159 was recently merged. Do you think this issue can be closed now?

**Comment by DanTup** [comment]
Looks like it, thanks!
