### ISSUE TITLE
about license

### ISSUE THREAD

**Issue by wellorange** [flutter/flutter#26584]
```
orange@orange:~$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/orange/work/flutter/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/orange/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/70/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/70/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[!] Connected device
    • Device 91QEBN237NDU is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 2 categories.
```
```
orange@orange:~$ flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
/home/orange/Android/Sdk/tools/bin/sdkmanager --update


orange@orange:~$ /home/orange/Android/Sdk/tools/bin/sdkmanager --update
Warning: java.net.ConnectException: Connection timed out (Connection timed out) 
[                                       ] 3% Fetch remote repository...        
==========Stop here===========
system：ubuuntu18
```

**Comment by zoechi** [comment]
Have you tried `/home/orange/Android/Sdk/tools/bin/sdkmanager --update`?

**Comment by zoechi** [comment]
Can you please post the output of `echo $JAVA_HOME`

See also https://github.com/flutter/flutter/issues/16025#issuecomment-377122502 and the discussion below

**Comment by wellorange** [comment]
I tried “/home/orange/Android/Sdk/tools/bin/sdkmanager --update” the same result.

orange@orange:~$ echo $JAVA_HOME


orange@orange:~$

**Comment by wellorange** [comment]
orange@orange:~$ /home/orange/Android/Sdk/tools/bin/sdkmanager --update --verbose
Info: Parsing /home/orange/Android/Sdk/build-tools/28.0.3/package.xml           
Info: Parsing /home/orange/Android/Sdk/emulator/package.xml
Info: Parsing /home/orange/Android/Sdk/extras/android/m2repository/package.xml
Info: Parsing /home/orange/Android/Sdk/extras/google/m2repository/package.xml
Info: Parsing /home/orange/Android/Sdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/package.xml
Info: Parsing /home/orange/Android/Sdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/package.xml
Info: Parsing /home/orange/Android/Sdk/patcher/v4/package.xml
Info: Parsing /home/orange/Android/Sdk/platform-tools/package.xml
Info: Parsing /home/orange/Android/Sdk/platforms/android-28/package.xml
Info: Parsing /home/orange/Android/Sdk/sources/android-28/package.xml
Info: Parsing /home/orange/Android/Sdk/tools/package.xml
[                                       ] 3% Fetch remote repository...

**Comment by zoechi** [comment]
Looks like it's just stuck downloading. Perhaps a network issue.
Perhaps https://forums.fusetools.com/t/fail-to-install-android-maybe-proxy-problem/5448

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
