### ISSUE TITLE
Errors when closing a flutter app running via mojoshell

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2659]
Looks like mojo errors... anything flutter specific here?
```
[0314/095328:ERROR:launcher_app.cc(87)] Exiting due to viewport connection error.
[0314/095328:ERROR:gpu_rasterizer.cc(114)] Context provider connection lost.
[0314/095328:ERROR:launcher_app.cc(57)] Exiting due to compositor connection error.
[0314/095328:ERROR:launcher_app.cc(62)] Exiting due to view manager connection error.
[0314/095328:ERROR:compositor_engine.cc(424)] Renderer encountered a fatal error: renderer=<1:Launcher>
[0314/095328:WARNING:launcher_view_tree.cc(82)] Input dispatcher connection error, input will not work.
[0314/095328:ERROR:launcher_view_tree.cc(75)] View tree connection error.
```

**Comment by abarth** [comment]
Dunno.  I'd file in the mojo.git issue tracker and use the label "mozart"

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (439/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:59707 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNi-000azj-Qk
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:28 +0100
Date: Mon, 14 Mar 2016 11:10:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457979034;
	bh=lbWdsjZjs8SxXtX8/14t4SV6gmotU1ExvbYbqWGVmRo=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=sav69vzWFNBdJSgjwBZZa7Cn5YzxTrXJKN3x+mAwvlHb+bqfUjR3GvJTwykUtM0bS
	 L6d5thGJi7+MqqE8HQ6ssOrlVdFCzu5nO2KDZU/ZifC4zzYS6WzzbTuMuOV5zUdm6+
	 yhCNxPHg+KAEWlbhtCnV2Npbf1G7DX4nKgq96KvE=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (442/400 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:59984 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNm-000b0V-6I
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:33 +0100
Date: Mon, 14 Mar 2016 11:10:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457979035;
	bh=KMz4qOObIP4EhlKnyEquispKpuYc3KT9FgMqzAQojMU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ks3+0f9K8zDAQ0OYCfNqLqa17z+MWJMpI4xdq/jNG4+5JRZFvHJO81hU/sLm7CLb4
	 ZwAux8tstz/FORf+N1hOn9RU2bpCkC31iiIWU9L9qet65NGTCTr66YlMVSZJY43DTz
	 D+hJQchddYtxLjuY+Ytk8JNKZh1RTKERqC7VMsWQ=
