### ISSUE TITLE
Expose AOT snapshot size profiler in flutter tool

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26609]
It'd be nice if there was a way to trigger https://github.com/dart-lang/sdk/blob/master/runtime/docs/snapshot_profiling.md from the `flutter` command.

**Comment by Hixie** [comment]
(In the meantime, you can use `--extra-gen-snapshot-options` to use it.)

**Comment by dnfield** [comment]
#51594 is a dupe of this but has more details
