### ISSUE TITLE
Compilation error google_maps_flutter: ^0.0.3+3 package doesn't compile!

### ISSUE THREAD

**Issue by Robofolk** [flutter/flutter#26607]
I added google_maps_flutter: ^0.0.3+3 package to my pubspec.yaml and now I get compilation errors on 

![image](https://user-images.githubusercontent.com/14302406/51212671-00cbb780-1911-11e9-9635-8eaa8cac8ba8.png)

```
Compiler message:
lib/map/widgets/map-ui.dart:173:7: Error: No named parameter with the name 'initialCameraPosition'.
      initialCameraPosition: _kInitialPosition,
      ^^^^^^^^^^^^^^^^^^^^^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.0.3+3/lib/src/google_map.dart:10:3: Context: Found this candidate, but the arguments don't match.
  GoogleMap({
  ^
Compiler failed on C:\Mobilsoft\Smart\cashex\lib\main.dart
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

Why is the installed package different from what's in the source code on Github?

![image](https://user-images.githubusercontent.com/14302406/51213786-ce6f8980-1913-11e9-8946-6c5e76ac3ccd.png)

**Comment by zoechi** [comment]
Please try running `flutter packages pub cache repair`

**Comment by Robofolk** [comment]
> Please try running `flutter packages pub cache repair`

Sorry it didn't make any changes. Same issue.

Does it matter which channel you are on? I was on Channel 'beta' when I hit this problem, then I switched to Channel 'dev'. It didn't help either. To be honest I'm reluctant to switch to channel master.

**Comment by wouterhardeman** [comment]
@Robofolk You didn't use the GoogleMaps widget properly. Check the API docs: https://pub.dartlang.org/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMap-class.html

You need to wrap those options in a [GoogleMapOptions](https://pub.dartlang.org/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMapOptions-class.html) object.

**Comment by Robofolk** [comment]
> @Robofolk You didn't use the GoogleMap widget properly. Check the API docs: https://pub.dartlang.org/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMap-class.html
> 
> You need to wrap those options in a [GoogleMapOptions](https://pub.dartlang.org/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMapOptions-class.html) object.
> 
> Edit: Just checked and the code in the repo indeed does not correspond to the published package. This is likely because the plugin is now being developed privately in-house at Google.

That was my suspicion too. Anyway this means I cannot take advantage of package 0.0.3+3 for now. I'm still confused why the installed package has different code!!!

**Comment by zoechi** [comment]
> Edit: Just checked and the code in the repo indeed does not correspond to the published package. This is likely because the plugin is now being developed privately in-house at Google.

This just means that the latest changes in the GitHub repo are not yet published to pub.dartlang.org.
There might be some additional work that needs to be done before publishing an update.

You can use a git dependency to use the version on Git instead of from pub.dartlang.org
```yml
dependencies:
  kittens:
    git:
      url: git@github.com:flutter/plugins.git
      path: packages/google_maps_flutter
```

**Comment by wouterhardeman** [comment]
@Robofolk Sure you can use 0.0.3+3. If you need documentation, you can use: https://pub.dartlang.org/documentation/google_maps_flutter/latest/

**Comment by Robofolk** [comment]
> This just means that the latest changes in the GitHub repo are not yet published to pub.dartlang.org.
> There might be some additional work that needs to be done before publishing an update.
> 
> You can use a git dependency to use the version on Git instead of from pub.dartlang.org

Thanks, I didn't know about that. I will give it a go

**Comment by zoechi** [comment]
I'm going to close because I don't think there is anything actionable left.
A plugin update will be published when the maintainer considers it ready anyway.
