### ISSUE TITLE
Problem with MacOS and xcode

### ISSUE THREAD

**Issue by iManolin** [flutter/flutter#26601]
Hello

I have mac os yosmite and latest version of xcode for me is 6.4 
and flutter required xcode 9 or newer and i'm working with ios 8 simulator 
can i install flutter and test with xcode 6 
waiting for help

** i can't update for higher version of mac os for  a newer version **

**Comment by zoechi** [comment]
From https://flutter.io/docs/get-started/install/macos

> To develop Flutter apps for iOS, you need a Mac with Xcode 9.0 or newer:

So, no, you can't use older versions.

**Comment by iManolin** [comment]
thank you for reply i have to find any way to update my macos
