### ISSUE TITLE
IAP: Expose the whole NSLocale object

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#26610]
Background: 
`NSLocale` is one of the property in the `SKProduct` and `SKProductDiscount` class in StoreKit. `NSLocale` itself does not have a simple way to be converted to a properly list map and thus cannot be passed back to Dart code directly. It seems to me that most of the properties in `NSLocale` are not particularly too useful to IAP and we could just expose the `countrySymbol` which seems matching the android IAP API.

* I would like to gather more use case information to see how many people do need the detailed `NSLocale` information thats only related to IOS.

**Comment by catacs** [comment]
Any update on this issue? I found the necessity of using the currencyCode from the NsLocale, which is not exposed. In android the currency code is exposed over the productDetails.skuDetail.priceCurrencyCode, so would be great to have the same properties available to both ios and android platforms.

**Comment by mklim** [comment]
Fixed by flutter/plugins#1888

**Comment by cyanglaz** [comment]
Reopen as the `NSLocale` is not entirely exposed yet.

**Comment by BeMacized** [comment]
All other values of `NSLocale`, aside from `NSLocaleExemplarCharacterSet` and `NSLocaleCalendar`, have been exposed now as well. 

I'm not entirely sure if there is anything more to expose about these two values. If what's currently exposed is considered sufficient I would propose closing this issue.

**Comment by stuartmorgan** [comment]
> All other values of `NSLocale`, aside from `NSLocaleExemplarCharacterSet` and `NSLocaleCalendar`, have been exposed now as well.

This is being reverted; given that in almost two years it doesn't appear that anyone has actually wanted this (based on votes), wrapping all of it adds a lot of API for potentially no benefit.

If anyone has specific fields they want access to, please file a new issue and describe the field(s) and the use case, and we can evaluate exposing more pieces as needed.
