### ISSUE TITLE
P2: Make --track-widget-creation widget transformer generate package: uris

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#26615]
Currently it generates absolute paths which complicates things by making the paths returned by --track-widget-creation diverge from those returned by the VMService.
Normalize to package: paths.
For backwards compatibility we will briefly want to support both kinds of paths in package:flutter.

**Comment by terrylucas** [comment]
Talked to Peter and created [issue](https://github.com/dart-lang/sdk/issues/35794) for front-end to create an API to do this mapping.

**Comment by terrylucas** [comment]
Talked to Peter the mapping should be easy just need an API to do the mapping created a front-end [issue](https://github.com/dart-lang/sdk/issues/35794) for the front-end track.
