### ISSUE TITLE
tar: Failed to set default locale

### ISSUE THREAD

**Issue by SilmeLyy** [flutter/flutter#26617]
```
[flutter-go-master] flutter packages get
Running "flutter packages get" in flutter-go-master...          
tar: Failed to set default locale
tar: Failed to set default locale
```

**Comment by SilmeLyy** [comment]
$flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (7 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

**Comment by SilmeLyy** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by kangwang1988** [comment]
@SilmeLyy 
Run `flutter packages get -v` please.

**Comment by SilmeLyy** [comment]
lyy:myapp-$flutter packages get -v
[  +36 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/usr/local/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%ar
[  +22 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 7 weeks ago
[   +1 ms] executing: [/usr/local/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +252 ms] Running "flutter packages get" in myapp...
[   +8 ms] Using /usr/local/flutter/.pub-cache for the pub cache.
[   +3 ms] executing: [/Users/mihisao/Desktop/HTML5/Flutter/myapp/] /usr/local/flutter/bin/cache/dart-sdk/bin/pub
--verbosity=warning --verbose get --no-precompile
[+5505 ms] tar: Failed to set default locale
[ +182 ms] Could not find a file named "pubspec.yaml" in
"/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.3".
[  +60 ms] Running "flutter packages get" in myapp... (completed)
[  +10 ms] "flutter get" took 5,924ms.
pub get failed (66)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:82:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#12     Future._complete (dart:async/future_impl.dart:476:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)



lyy:myapp-$ls
README.md       build           lib             pubspec.lock    test
android         ios             myapp.iml       pubspec.yaml
lyy:myapp-$

@kangwang1988

**Comment by SilmeLyy** [comment]
name: myapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  event_bus: ^1.0.1
  fluro: ^1.3.4
  image_picker: ^0.4.10
  sqflite: ^0.12.1
  flutter_markdown: ^0.2.0
  url_launcher: ^4.0.1
  fluttertoast: ^2.2.2
  shared_preferences: ^0.4.3
  dio: ^1.0.6

pubspec.yaml

**Comment by kangwang1988** [comment]
> [ +182 ms] Could not find a file named "pubspec.yaml" in
"/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.3".

This might be the cause, delete `/usr/local/flutter/.pub-cache/hosted/pub.dartlang.org` and try again.

**Comment by SilmeLyy** [comment]
lyy:myapp-$flutter packages get -v
[  +35 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/usr/local/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%ar
[  +24 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 7 weeks ago
[   +2 ms] executing: [/usr/local/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +42 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.0.0-0-g5391447fa
[ +316 ms] Running "flutter packages get" in myapp...
[  +13 ms] Using /usr/local/flutter/.pub-cache for the pub cache.
[   +3 ms] executing: [/Users/mihisao/Desktop/HTML5/Flutter/myapp/] /usr/local/flutter/bin/cache/dart-sdk/bin/pub
--verbosity=warning --verbose get --no-precompile
[ +890 ms] Running "flutter packages get" in myapp... (completed)
[ +207 ms] Found plugin fluttertoast at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.2.6/
[   +3 ms] Found plugin image_picker at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.4.12/
[  +18 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[   +8 ms] Found plugin sqflite at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/
[  +35 ms] Found plugin url_launcher at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.3/
[  +61 ms] Unable to locate an Android SDK.
[ +132 ms] Found plugin fluttertoast at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-2.2.6/
[   +3 ms] Found plugin image_picker at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.4.12/
[  +22 ms] Found plugin shared_preferences at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +28 ms] Found plugin sqflite at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-0.12.2+1/
[  +17 ms] Found plugin url_launcher at /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.0.3/
[ +338 ms] "flutter get" took 1,995ms.




lyy:myapp-$flutter packages get
Running "flutter packages get" in myapp...
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
tar: Failed to set default locale
463.0s


@kangwang1988

**Comment by zoechi** [comment]
https://stackoverflow.com/questions/3907719/how-to-fix-tar-failed-to-set-default-locale-error

**Comment by kangwang1988** [comment]
@SilmeLyy 
> tar: Failed to set default locale

Can you figure out whether your project `myapp` can run normally or not?
It seems `tar: Failed to set default locale` doesn't fail the `flutter package get` process.

**Comment by SilmeLyy** [comment]
successful , thank @kangwang1988  @zoechi

**Comment by mgblackwater** [comment]
It happened to me also. Mine was resolved after deleting the pubspec.lock file.

**Comment by vimanshu** [comment]
Try deleting the pod file and pod.lock file. It worked out for me.

**Comment by ElLocoNutz** [comment]
> https://stackoverflow.com/questions/3907719/how-to-fix-tar-failed-to-set-default-locale-error

I'm having the same issue and I dont have R installed, though it doesn't break my app, it's just annoying

**Comment by AnshadV** [comment]
> successful , thank @kangwang1988 @zoechi

how

**Comment by anshulkataria4** [comment]
> Try deleting the pod file and pod.lock file. It worked out for me.

where is the pod file ?
@vimanshu
