### ISSUE TITLE
"flutter run" hangs waiting for observatory port

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26623]
Ever since I started using the alarm manager plugin (though that might be a coincidence, I haven't tested this yet), "flutter run" has frequently just hung after installation, waiting for the observatory port, with the app not starting and nothing happening. I have to both uninstall the app and "flutter clean" to get it running again.

I need to investigate further.

**Comment by Hixie** [comment]
When I patch my app to not call `AndroidAlarmManager.initialize()` on startup, this problem goes away.

cc @bkonyi @amirh

**Comment by Hixie** [comment]
Specifically, the relevant code does:

```dart
import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:flutter/foundation.dart';

void runBackground() async { // this is called from `main` before `runApp`
  return; // this line makes the problem go away
  if (!await AndroidAlarmManager.initialize()) {
    FlutterError.reportError(FlutterErrorDetails(
      exception: Exception('Android Alarm Manager failed to start up.'),
      library: 'Cruisemonkey',
      context: 'during startup',
    ));
    return;
  }
  await AndroidAlarmManager.periodic(const Duration(minutes: 2), 0, _update);
}

void _update() async {
  print('background update...');
}
```

**Comment by bkonyi** [comment]
@Hixie are you still seeing this issue? I'm unable to reproduce locally.

**Comment by bkonyi** [comment]
Closing for now. Feel free to reopen if you're still seeing this issue.
