### ISSUE TITLE
Pixel 2 reports touch event pressures above pressureMax

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26628]
On my Pixel 2 XL, I see touch events with pressures like 1.087499976158142, even though the min and max are reported as 0.0 and 1.0 respectively.

**Comment by Hixie** [comment]
cc @xster @jason-simmons @jslavitz

**Comment by jslavitz** [comment]
Hahahahhaa, where can I file a bug for the pixel 2?

**Comment by xster** [comment]
We missed this in the engine T.T https://github.com/flutter/engine/blob/b058920cab5be328295f72d8af66461ade161e7d/shell/platform/android/io/flutter/view/FlutterView.java#L477

Duping into https://github.com/flutter/flutter/issues/26563#issuecomment-454935759
