### ISSUE TITLE
Invalid bundle identifier io.flutter.flutter_embedder

### ISSUE THREAD

**Issue by jbg** [flutter/flutter#26625]
The Flutter Embedder framework on Mac has a bundle identifier of `io.flutter.flutter_embedder` which **isn't valid** for use within Mac App Store apps **due to the underscore**. Removing the underscore allows an app using this framework to be uploaded to the Mac App Store.

See https://github.com/google/flutter-desktop-embedding/issues/234

**Comment by kangwang1988** [comment]
Please provide detailed information that `io.flutter.flutter_embedder` is why your app is rejected.
@jbg

**Comment by jbg** [comment]
The app doesn't get rejected by review (I've not submitted it for review, and likely will not until desktop embedding is more featureful and stable). Rather, it's not possible to upload it at all without modifying the bundle ID of FlutterEmbedder.framework.

When attempting to upload an app containing that framework via Xcode or Transporter, App Store Connect responds with an error that the Bundle ID of the embedded framework `FlutterEmbedder.framework` is invalid. As soon as the underscore is removed from the bundle ID in the `Info.plist` of that framework, the upload succeeds.

**Comment by kangwang1988** [comment]
@jbg 
Got it. Thanks for your feedback.
