### ISSUE TITLE
Flutter build/run should be able to accept compile-time arguments

### ISSUE THREAD

**Issue by c16a** [flutter/flutter#26638]
Consider the below scenario.

I am developing a global application with strikingly different **feature sets across countries**. So it is no more sensible to package all features into one app and enable or disable (with a flag, say) at runtime, as this would bloat up the app rapidly.

Also while development, I have my **development, staging and production environments** for which I would need to package and distribute the apps appropriately.

Something along the lines of the following would make sense

```bash
country=US env=DEV flutter build apk
country=UK env=STAGING flutter build ios
```

Currently, the multiple entry point approach suggested in https://github.com/flutter/flutter/issues/18377#issuecomment-415056377 won't scale when you have increasing number of dimensions (similar to a build matrix in CI/CD systems)

Are there any plans of implementing this? It is obvious that Flutter already supports having build-time flags (like `--release` etc). I have never contributed to Flutter as such (an avid user, though), but if add support for custom flags is something I can take up, I can do it.

**Comment by zoechi** [comment]
Sounds like you are looking for flavors 
https://flutter.io/docs/deployment/flavors

Support is not perfect yet but usable with some tweaking here and there.

**Comment by munukutla** [comment]
I am looking for a more "pure Dart" approach to doing this. I've come across the flavoring articles you that page mentions, and both of them require some tinkering with Xcode schemas and Android Gradle flavors.

I don't honestly think this is something that even needs to be offloaded to iOS and Android configurations.

```bash
country=US env=DEV flutter build apk
country=UK env=STAGING flutter build ios
```

We'll need to have a way to make them accessible to the Dart byte code.

The below works on DartVM (server side Dart), but would obviously not work when the app is deployed on iOS or Android.
```dart
var country = const System.fromEnvironment("country", default: "US")
```

Currently, achieving this would require a context switch from the Dart experience, go backward in time, deal with the Xcode/AndroidStudio hoolapalooza.

**Comment by wintersandroid** [comment]
What we need is something like the androids "BuildConfig" class which can be set from the command line or/and from the pubspec.yaml. I would be keen on this.

**Comment by Feenposhleen** [comment]
It would be nice to at least have some sort of build hook, where we could trigger an arbitrary Dart script before the app is compiled. Most issues could probably be worked around if this existed. 

Being forced to use platform-specific flavoring is unnecessary cognitive load.

**Comment by jonahwilliams** [comment]
Would be solved via https://github.com/flutter/flutter/issues/44483 , though this has more history so I'm leaving it open

**Comment by zoechi** [comment]
`--dart-define` is available in `flutter run`, `flutter build apk`, `flutter build ios`, `flutter drive`. Can this be closed?

**Comment by jonahwilliams** [comment]
Yes! Thanks for the heads up @zoechi
