### ISSUE TITLE
ListView not be bouncing and no longer responding to click events after I changed to another page in iOS

### ISSUE THREAD

**Issue by Huanhoo** [flutter/flutter#26637]
I have added a Flutter Module to an existing iOS apps, but I found my ListView not bouncing and no longer responding to click events after I changed to another iOS native page.

## Steps to Reproduce

1. Open a Flutter page that contains a `ListView` in an iOS native app.
2. Drag and scroll the `ListView`.
3. Keep your finger on the screen and click a button to push to another page.
4. return back to the flutter page.

The ListView will not be bouncing and no longer responding to click events.

```
[✓] Flutter (Channel master, v1.1.10-pre.2, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.1.10-pre.2 at /Users/huanhu/Desktop/flutter
    • Framework revision ae310298f6 (9 days ago), 2019-01-07 18:38:11 +0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/huanhu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • “apple”的 iPhone • ff863c55a6506f0e8dg532f4738725d300e50741 • ios • iOS 11.1.2

• No issues found!
```

**Comment by Huanhoo** [comment]
I wrote a demo and upload it to my GitHub, you can download and run it.

https://github.com/Huanhoo/flutter_scroll_demo.git

you should run it on an iOS device and check my problem.

**Comment by Huanhoo** [comment]
Hi, 
Can I reset the status of `ListView` or use any other method to avoid this problem?

**Comment by lihui2333** [comment]
@Huanhoo @zoechi i met the same problem，is there any Solution？

**Comment by Huanhoo** [comment]
@lihui2333 I have no idea, I'm also waiting for the author to sort things out.

**Comment by msw333** [comment]
Same

**Comment by TahaTesser** [comment]
Hi @Huanhoo 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with the latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), sample you provided is outdated and doesn't run 
Thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
