### ISSUE TITLE
[Plugins android_alarm_manager] developer option is set to destroy every activity after leaving the app

### ISSUE THREAD

**Issue by hanj315** [flutter/flutter#26639]
The Android phone developer option is set to destroy every activity after leaving the app. Reopening the app after exiting the app will not be able to call the `android_alarm_manager` callback method.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
