### ISSUE TITLE
flutter test should default to a --debug or --release setting

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2663]
When running `flutter test`, it fails with this message:

```
At least one of --debug or --release must be set, to specify the local build products to test.
```

It should default to a setting (`--debug`) and use that.

The command should also probably fast-fail on non-linux platforms, until those are supported.

**Comment by Hixie** [comment]
This seems to be the exact opposite of https://github.com/flutter/flutter/issues/2613 ...

**Comment by devoncarew** [comment]
Hopefully the user won't need to specify a `--engine-src-path`? It sounds like the testing artifacts are only available if you have an engine checkout. Perhaps this bug is more about having the testing artifacts being something the flutter tool downloads w/ the rest of the engine libraries (into `bin/cache/artifacts/` or `bin/cache/artifacts/engine/`).

**Comment by Hixie** [comment]
Oh, I see. Sorry, I misunderstood.

`flutter test` shouldn't require a local checkout. Are you on Mac? We don't yet have mac binaries for `flutter test`. It should work on Linux.

**Comment by abarth** [comment]
IMHO, the right way to fix this issue is to make it possible to run tests with prebuilt binaries on mac.

**Comment by abarth** [comment]
i.e., a dup of #1707

**Comment by devoncarew** [comment]
OK, closing as a dup.
