### ISSUE TITLE
text-form-field 输入汉字，光标错位

### ISSUE THREAD

**Issue by wangyankun33** [flutter/flutter#26640]
TextFormField输入汉字时，出现光标位置不正确，输入字母或数字没有影响！

(Google translate: When TextFormField inputs Chinese characters, the cursor position is incorrect. Entering letters or numbers has no effect!)

![c xp gn t52f9 muw yeh3t](https://user-images.githubusercontent.com/19883375/51239937-9f115900-19b5-11e9-966f-3de01c580c37.png)

**Comment by kangwang1988** [comment]
@wangyankun33 
English please.
Besides, flutter doctor -v.

**Comment by wangyankun33** [comment]
This my flutter doctor -v!
I am using Visual Code
![image](https://user-images.githubusercontent.com/19883375/51240540-dfbda200-19b6-11e9-97a2-edcec3d6e45d.png)

**Comment by wangyankun33** [comment]
> @wangyankun33
> English please.
> Besides, flutter doctor -v.

**Comment by zoechi** [comment]
@wangyankun33 did you close intentionally?

**Comment by zoechi** [comment]
Is this a regression or did you not try with previous Flutter versions like `stable` channel?

**Comment by zoechi** [comment]
Looks similar to #24182
