### ISSUE TITLE
TextField cursor moving outside

### ISSUE THREAD

**Issue by I-am-original** [flutter/flutter#26646]
Hey guys.

I have found strange issue. And cant actually find reason of it, or proper solution.
Can you take a look on this?

Here is an issue - as you can see - cursor is outside of TextField:
<img width="463" alt="screen shot 2019-01-16 at 4 58 38 pm" src="https://user-images.githubusercontent.com/9134717/51257473-5c994d80-19b0-11e9-9c73-acbed85ff795.png">

Here is my code:
![screen shot 2019-01-16 at 5 01 12 pm](https://user-images.githubusercontent.com/9134717/51257480-60c56b00-19b0-11e9-9e7d-c9620425db0f.png)

Will appreciate you help.
Thank you in advance

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Code and log output as text please. Screenshots are not searchable or copy-paste-able.

**Comment by I-am-original** [comment]
1. `Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.77, on Mac OS X 10.14.2 18C54, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (1 available)
`

2. `class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Row(children: <Widget>[
          Container(
            height: 32,
            width: 32,
          ),
          Flexible(
            child: TextField(
              controller: TextEditingController(),
              autofocus: true,
              maxLines: null,
            ),
          ),
          Container(
            height: 32,
            child: Text("button"),
          ),
        ]),
      ),
    );
  }
}
`

**Comment by justinmc** [comment]
This should be fixed with https://github.com/flutter/flutter/pull/30525

**Comment by mahdinazmi** [comment]
I have same issues now !

**Comment by justinmc** [comment]
@mahdinazmi If you're still seeing this, can you open a new issue with a full reproduction case and tag me?
