### ISSUE TITLE
FirebaseAnimatedList sort function is triggered only once when the application starts

### ISSUE THREAD

**Issue by amervelic** [flutter/flutter#26656]
```dart
body: FirebaseAnimatedList(
            padding: EdgeInsets.all(8),
            query: FirebaseDatabase.instance
                .reference()
                .child('latest-messages')
                .child(currentUID),
            sort: (a, b) {
              return b.value['timestamp']
                  .toString()
                  .compareTo(a.value['timestamp'].toString());
            },
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please add the output of `flutter doctor -v`.

**Comment by amervelic** [comment]
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-BA)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.1.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

**Comment by zoechi** [comment]
Please also provide a minimal, but complete and runnable reproduction as mentioned above.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by kroikie** [comment]
@amervelic

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/505. Any further collaboration will be done there.
