### ISSUE TITLE
suddenly READ_PHONE_STATE is added to my application

### ISSUE THREAD

**Issue by PeterPan3D** [flutter/flutter#26651]
Hi, I recompiled my application with a newer flutter version. I might have added another flutter module to my app in-between but I can't tell anymore for sure. My problem is that all of the sudden READ_PHONE_STATE got added to the required permissions although I don't need them. I can't find this flag in any module, only in the build output. Does anyone know where this could come from?

Edit: What is merged_manifests? Why does this request READ_PHONE_STATE?

`./android/.idea/workspace.xml:      <find>READ_PHONE_STATE</find>
./build/app/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/universal/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/armeabi-v7a/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/x86/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/arm64-v8a/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/bundle_manifest/release/processReleaseManifest/bundle-manifest/x86_64/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/merged_manifests/release/universal/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/merged_manifests/release/armeabi-v7a/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/merged_manifests/release/x86/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/merged_manifests/release/arm64-v8a/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/merged_manifests/release/x86_64/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/instant_app_manifest/release/processReleaseManifest/instant-app-manifest/universal/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/instant_app_manifest/release/processReleaseManifest/instant-app-manifest/armeabi-v7a/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/instant_app_manifest/release/processReleaseManifest/instant-app-manifest/x86/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/instant_app_manifest/release/processReleaseManifest/instant-app-manifest/arm64-v8a/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/intermediates/instant_app_manifest/release/processReleaseManifest/instant-app-manifest/x86_64/AndroidManifest.xml:    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
./build/app/outputs/logs/manifest-merger-release-report.txt:uses-permission#android.permission.READ_PHONE_STATE`

**Comment by PeterPan3D** [comment]
The issue was a package that added it without my knowledge. I fixed it

**Comment by minwook-shin** [comment]
hello @avbk ... I had the same problem.
And I found out why this permission was added.
In my case, WebView was a problem.
This is "flutter_webview_plugin"!
So I changed it to the official WebView widget packages.

https://pub.dartlang.org/packages/webview_flutter

**Comment by Sarmed-armis** [comment]
Dears i'm face this case also when i upload my app in google play
