### ISSUE TITLE
Add space tracking metrics to LibTxt to properly include end-of-line spaces in bounding rects.

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#26658]
Currently, we truncate white space at the end of lines when the text is centered.

Correct behavior should be that the white space still adds metrics but does not contribute to the centering or width of the text. This way, when spaces are typed, they still appear and the centering is not skewed.

This is extracted from https://github.com/flutter/flutter/issues/25312

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/7791 fixes this.

**Comment by Hixie** [comment]
There's an argument to be made that we shouldn't even trim the spaces in rendering, but I'm not sure if it's a valid argument or not.

**Comment by GaryQian** [comment]
The main goal of this is to achieve the same behavior that is present in android and iOS. It is straightforward to expose properties to toggle this, although I don't expect many people to ever use it.

**Comment by GaryQian** [comment]
The changes in the engine to fix this should be rolled by https://github.com/flutter/flutter/pull/27808

**Comment by GaryQian** [comment]
The fix has landed in the engine, but is on hold before it is rolled into flutter/flutter.

**Comment by GaryQian** [comment]
The roll has landed!
