### ISSUE TITLE
Wire in Skia's new http-based debugger

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2665]
https://github.com/google/skia/tree/master/tools/skiaserve

We should be able to wire this in a very similar way to how observatory works (fyi @johnmccutchan). Build their server into our debug builds, forward the port over to the host, and possibly even expose a 'skia debugger' button in Atom (fyi @devoncarew).  This would make it so that we don't need to pull down skp's off the device to debug slow frames @chinmaygarde.

@jcgregorio can answer Skia questions.  We'll have to write our own GN integration of course.

**Comment by devoncarew** [comment]
Is there a link available or a screenshot for what skiaserve looks like?

**Comment by jcgregorio** [comment]
You can see an annotated screenshot in the Feb 16th Skia Update:

  https://docs.google.com/document/d/16zjq59_xhfgZ6-brfR2-jHNc2wocNYajlmv6Y8fXz4Q/edit

**Comment by jcgregorio** [comment]
Back from travel. 

I realized I didn't give you pointers to all the code, the link above to skiaserve is just for the C++ side of the application, the Polymer side of the code is here:

  https://github.com/google/skia-buildbot/tree/master/debugger 

Right now skiaserve runs by default with the assumption that all of the Polymer assets will be loaded off of https://debugger.skia.org, which you may not want to do when running Flutter.

**Comment by Hixie** [comment]
@jason-simmons Is this what you're looking at?

**Comment by jason-simmons** [comment]
I spent some time on this.

I did some refactoring of skiaserve to abstract the dependency on libmicrohttpd and then tried to link the skiaserve code into Flutter.  However, skiaserve brought in some Skia debug tool code that required EGL APIs that weren't exported by the Android NDK.

We could probably work around that, but at this point I felt that running skiaserve on the device wasn't the best approach.  I'm now looking at adding a way for the Flutter tools to capture a Skia picture from the Flutter engine and then upload it to a skiaserve running on the host.

**Comment by chinmaygarde** [comment]
> to capture a Skia picture from the Flutter engine

We already have this wired up. The tracing controller can specify a frame threshold. Once it trips, an SkPicture for the offending frame is captured and saved to a platform specified location. https://github.com/flutter/engine/blob/b8151a8d9bb2fd2c1d67e8007a53eba5489f3d0d/sky/shell/gpu/direct/rasterizer_direct.cc#L112

Maybe the tools can look at this location for new traces.

**Comment by ethannicholas** [comment]
I was able to get it working on my Nexus 10. microhttpd was not excited about building on Android, but with some gentle massaging I convinced it to stop complaining. Other than that everything worked perfectly. Can you be more specific about the EGL problems you encountered?

**Comment by jason-simmons** [comment]
I don't have this code handy, but I did an experiment where I tried to embed skiaserve into the Flutter engine using the version of the NDK in the Flutter source tree.

skiaserve brought in a dependency on SkCreatePlatformGLContext.  There was no implementation of SkCreatePlatformGLContext in src/gpu/gl/android, so I tried using the one from src/gpu/gl/egl.  This code called eglCreateSyncKHR/eglClientWaitSyncKHR/eglDestroySyncKHR, which were not exported from the EGL libraries in that NDK.

In Flutter, we're now providing a tool that can grab an SkPicture from the device through a debug interface and then upload it to a skiaserve running on the host.

**Comment by ethannicholas** [comment]
Interesting. Looks like those are only referenced in EGLGLTestContext, and everything still seems to work fine for me when I completely comment that class out. Might be worth seeing if that gets you past this problem. Or are you guys happy enough with your current approach that you no longer care about this?

**Comment by jason-simmons** [comment]
Downloading the SkPicture to the host is working well.  We aren't planning to run skiaserve on the device.

**Comment by eseidelGoogle** [comment]
@vlidholt asked about how to use this this afternoon.

I presume it's something like this:
```
flutter run --no-checked
flutter skia --output-file=foo.skp
// Somehow get skiaserve running on your machine?
flutter skia --skiaserve="http://localhost:1234"
```

@jason-simmons are there instructions somewhere I should point viktor to?  Thanks!

**Comment by jason-simmons** [comment]
That's basically it:
  * get the Skia sources, build, and run skiaserve
  * run "flutter skia --skiaserve=http://localhost:[port]" while a Flutter app is running
  * go to Skiaserve in a browser

**Comment by eseidelGoogle** [comment]
Curious if skiaserve is built as part of flutter/engine's skia build?  If so, I could trivially update our bots to send a binary to google storage that the flutter tool could know how to download and run for you.

**Comment by jason-simmons** [comment]
No, we don't build it from Flutter's skia build scripts

**Comment by sethladd** [comment]
Did we do this?

**Comment by jason-simmons** [comment]
Yes - the flutter tool can capture a Skia picture from the engine and send it to an instance of skiaserve
