### ISSUE TITLE
Picture.toImage breaks backwards compatibility

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#26655]
On `master`, `Picture.toImage` in `dart:ui` now returns a `Future` (so is async) where it used to be sync. This creates an issue with libraries that use this call (like https://github.com/lukef/qr.flutter). 

I'm going to assume that there are going to be some assurances around backwards compatibility moving forward? If not, we will need a way to isolate platform version specific code so that developers (like me) don't have to maintain a bunch of different library versions whenever the underlying platform changes.

For now, I can bump the version and direct developers to use a lower version for 1.0 and a higher version for master (and beyond) however, should we trust that decisions like this one that are made (and pushed) to master are going to be in constant flux? i.e: tell developers to not use master?

Also, there is no mechanism to peg the library to specific Flutter versions (right?). So it's still highly possible that developers will use the wrong version regardless.

**Comment by GaryQian** [comment]
cc @jason-simmons

**Comment by zoechi** [comment]
As far as I know this was to fix #23621 by #7442 to make `Picture.toImage` work.

**Comment by lukef** [comment]
I have to assume that this fix wont be rolled back at this point?

**Comment by jason-simmons** [comment]
This is an intentional change to the API.  Fixing https://github.com/flutter/flutter/issues/23621 required making this method asynchronous

**Comment by zoechi** [comment]
> decisions like this one that are made (and pushed) to master are going to be in constant flux?

From what I have seen the Flutter team avoids any breaking change, but in this case it was necessary to make a broken feature work.

I don't think there is anything actionable left and therefore closing.
