### ISSUE TITLE
How the Flutter Gallery `Force RTL` option works

### ISSUE THREAD

**Issue by majidfathi69** [flutter/flutter#26666]
I am reviewing the [Flutter Gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery) app. What is still unclear to me is how the `Force RTL` option works.

In fact, I want to put the `Force RTL` option on my program and I do not realize that after activating the attachment, which part of the code will make everything right to the left.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
It is used here https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/app.dart#L145-L146

See also https://docs.flutter.io/flutter/widgets/Directionality-class.html
