### ISSUE TITLE
Cupertino text selection controls's GestureDetection is incorrect

### ISSUE THREAD

**Issue by ttlg** [flutter/flutter#26678]
Cupertino text selection controls's Handle is upside down if `TextSelectionHandleType.left`, However its `GestureDetection` is not upside down.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/text_selection.dart

**Comment by ttlg** [comment]
Cupertino text selection controls
![Cupertino text selection controls](https://i.stack.imgur.com/27Mde.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by justinmc** [comment]
I did a deep dive on making sure that the handles are always interactive when they should be in https://github.com/flutter/flutter/pull/31852.  This seems to be fixed with that PR.  Let me know if anyone still runs into this though.  The fix should be in v1.7.0 and above.
