### ISSUE TITLE
Clean up activity.dart

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2668]
Right now there's no good way to document stuff in this file, and the members all end up at the top level in the services dartdocs which is confusing.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (441/400 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:59780 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNj-000azs-PE
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:30 +0100
Date: Mon, 14 Mar 2016 12:18:18 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457983098;
	bh=h/454h2PEkn6O/VZ+9CLHwzkFVsPm+sl0opzBaHUZ18=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=JZwVTnfUxYOKXGanBWZI4jy43GsUln1s+Paml4CJtRH9Zd2d6sdbQ4Uhbzroxnwu7
	 c+VRWRrfV2rROAo5/nVjG2xS1d3iYcYMjmEW/09FvSBJMZqv/JhcOChz4R0RL+V9Hb
	 KOheoCs9mx4LixcLySOhRnjGufx18l9189WW0JCI=

**Comment by abarth** [comment]
Not a thing anymore.
