### ISSUE TITLE
How to make artifacts of own engine build？

### ISSUE THREAD

**Issue by SupSaiYaJin** [flutter/flutter#26682]
Are there readily available scripts or tools make those artifacts conveniently? Either zips or folders. It is too cumbersome to manually make them from engine build.
![image](https://user-images.githubusercontent.com/10076965/51293377-a84c0580-1a49-11e9-83f6-28ff224a9c75.png)

**Comment by kangwang1988** [comment]
@SupSaiYaJin 
Refer to: https://github.com/flutter/flutter/wiki/Compiling-the-engine
After you've fetched the engine, `cd engine/src && ./flutter/tools/gn --help` will give you a lot of available flags to get a customized engine. Then ninja command will do the rest.
The artifacts contained in flutter repo is just part of the engine products.

**Comment by SupSaiYaJin** [comment]
I know how to compile the engine. What I need is a simple way to get all artifacts in screenshot with same file structure. For now, I could only copy them one by one from engine products.

**Comment by xster** [comment]
I'm not too sure I understand the issue. You're saying instead of having the framework depend on a commit SHA from a hosted engine build, you want to always manually build the engine locally and have your framework easily retrieve all the architectures of your locally built engines?

(As a side note, also please file bugs or send us PRs if you feel the need to locally modify the engine due to bugs or such :D)

**Comment by SupSaiYaJin** [comment]
> you want to always manually build the engine locally and have your framework easily retrieve all the architectures of your locally built engines?

That's right. The locally built engines are not only used for myself, so there should be a way of being easily used for other developers too.

**Comment by dnfield** [comment]
Our engine packaging scripts are a bit convoluted.  You can see how a lot of it works here: https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py

I'm working to simplify some of that logic, but a lot of it is very specific to infrastructure set up for Flutter.  We're not quite set up right now to be able to upload arbitrary engine artifacts for someone else to be able to download.

It sounds to me like what you want is some kind of "publish" script for a local engine build, and a way for the framework to pull down a published engine bundle from somewhere other than our existing infrastructure for this (or at least using a different tag/prefix/folder or somesuch).

I think it should be _possible_ to do that, but I'd wonder about managing security for it.  @cbracken @Hixie

**Comment by huangchuqiang** [comment]
> Our engine packaging scripts are a bit convoluted. You can see how a lot of it works here: https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py
> 
> I'm working to simplify some of that logic, but a lot of it is very specific to infrastructure set up for the current path from our infra to roll into the Flutter framework. We're not quite set up right now to be able to upload arbitrary engine artifacts for someone else to be able to download.
> 
> It sounds to me like what you want is some kind of "publish" script for a local engine build, and a way for the framework to pull down a published engine bundle from somewhere other than our existing infrastructure for this (or at least using a different tag/prefix/folder or somesuch).
> 
> I think it should be _possible_ to do that, but I'd wonder about managing security for it. @cbracken @Hixie

hi dnfield, https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/engine.py  is an error url.  Can you tell me where is the script of engine.py file ? 
Thanks.

**Comment by dnfield** [comment]
It was recently moved to https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine.py
