### ISSUE TITLE
I am not getting notification in my flutter app when app is closed.

### ISSUE THREAD

**Issue by 91priyansh** [flutter/flutter#26692]
I am not getting notification in my flutter app when app is closed, i am using `c103 mobile`. I am using `firebase_messaging` plugin. I am getting result when app is background or foreground but when app is closed at that time I am not getting notifications. I am sending notifications from firebase console. Anyone know how to solve this problem?

here is my code
```dart
import 'package:flutter/material.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

void main(){
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
    State<StatefulWidget> createState() {
      return MyAppState();
    }
}

class MyAppState extends State<MyApp> {
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  @override
  void initState(){
    super.initState();
    _firebaseMessaging.configure(
      onLaunch: (data){
         showDialog(
           context: context,
           builder: (BuildContext context){
             return AlertDialog(
               title: Text(data.toString()),
             );
           }
         ); 
      },
      onMessage: (data){
        showDialog(
           context: context,
           builder: (BuildContext context){
             return AlertDialog(
               title: Text(data.toString()),
             );
           }
         );
      },
      onResume: (data){
        showDialog(
           context: context,
           builder: (BuildContext context){
             return AlertDialog(
               title: Text(data.toString()),
             );
           }
         );
      }
    );
    _firebaseMessaging.getToken().then((token){
      print(token);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Text("data"),
      ),
    );
  }
}
```

**Comment by 91priyansh** [comment]
I am testing on android.
here is output of flutter doctor -v 
[√] Flutter (Channel dev, v1.1.9, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.1.9 at E:\flutter
    • Framework revision 1407091bfb (8 days ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • C103 • 27f7a407 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!

**Comment by JonathanJude** [comment]
I have same issue here. When app is closed, "swiped off recent list", no notifications..

**Comment by kroikie** [comment]
@91priyansh

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/503. Any further collaboration will be done there.
