### ISSUE TITLE
Switches often don't have shadows

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2670]
e.g. look at the settings page in stocks. Note that it fixes itself if you toggle any switch.

**Comment by abarth** [comment]
Something similar happens in the tabs demo in the components section of the gallery app.  /cc @HansMuller

**Comment by abarth** [comment]
It's a Skia bug similar to the previous shadow dropping bug.  Creating a patch for Skia.

**Comment by abarth** [comment]
https://codereview.chromium.org/1824693003 should fix it on the skia side.
