### ISSUE TITLE
Flutter packages get error after adding new dependencies

### ISSUE THREAD

**Issue by NocturnScholar** [flutter/flutter#26703]
Hello, 

I'm new to flutter/dart and trying to follow tutorial from https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

after adding english_words: ^3.1.0 below cupertino_icons," flutter packages get" command failed.
but if i delete it, everything went normal.

I'm using macOS Sierra, and running everything from Terminal.

pubspec.yaml:
name: startup_namer
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

logs:
Running "flutter packages get" in startup_namer...              
gzip: (stdin): trailing garbage ignored
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to extract .tar.gz stream to /Volumes/Data/flutter/.pub-cache/_temp/dirTtw75b (exit code 2).
package:pub/src/io.dart 874:5               extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 302:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48      Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                  runZoned
package:pub/src/http.dart 272:10            withDependencyType
package:pub/src/entrypoint.dart 367:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 228:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run
 
    pub --trace --verbosity=warning get --no-precompile
 
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
 
pub get failed (1)

detailed logs:
https://pastebin.com/frDyBCmf

**Comment by wouterhardeman** [comment]
The error is the detailed logs is because `pub get` is used instead of `flutter packages get`. Can you run `flutter packages get -v`?

**Comment by NocturnScholar** [comment]
sure,

https://pastebin.com/idbu4803

**Comment by wouterhardeman** [comment]
@NocturnScholar Then try these options: https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#corrupted-cache

It is attempting to extract cached packages, but it looks like it's corrupted.

**Comment by NocturnScholar** [comment]
@wouterhardeman turns out it was OS related problems.
i'm using gtar version from Brew while using native gzip binary, so after installing gzip version from Brew, `flutter packages get` command run successfully.

Sorry about that, and thanks for everything.
