### ISSUE TITLE
Platform.numberOfProcessors on Mediatek

### ISSUE THREAD

**Issue by jow-ct** [flutter/flutter#26709]
I've seen this on a Nokia 3.1 and a Cubot P20, both have the Mediatek MT6750 with 8 cores.

It seems that their power management shows only the CPU cores which are not in sleep mode. Thus in Flutter, Platform.numberOfProcessors just gives "2". Some weeks ago, the Nokia 3.1 had the correct "8". So maybe this behaviour changed with some Flutter updates? I did not update the Nokia 3.1 since then. 

Maybe it's not related to Flutter only: My Flutter app does also read the /proc/cpuinfo and saves them in an database. When numberOfProcessors were "8", this file was also ok. But now, when Cubot and Nokia just report 2 cores, this file also has less than 8 cores. Interestingly, not necessarily 2 cores, but sometimes three, sometimes four, and they always start with "processor: 4", not "processor: 0" as you would expect.

(Maybe the new behaviour came with the January Security Update. I had one correct reading since then, but this was directly after the update when maybe all 8 cores were working...  Unfortunately, we got the Cubot not with an older Update, just January, so no crosscheck possible here.)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by jow-ct** [comment]
Sorry, here it is: 

                            flutter doctor -v
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale de-DE)
    • Flutter version 1.0.0 at c:\data\flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at c:\data\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = c:\data\sdk
    • Java binary at: C:\data\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\data\android-studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (2 available)
    • ONEPLUS A6013 • 851d1e21         • android-arm64 • Android 9 (API 28)
    • Nokia 3 1     • ES2BA80519007287 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

**Comment by jow-ct** [comment]
This is interesting: 

```
      print("numberOfCores:");
      print("A) ${Platform.numberOfProcessors}");
      try {
        var possible = File("/sys/devices/system/cpu/possible")
            .readAsStringSync();
        var n = int.parse(possible.substring(possible.indexOf("-")+1))+1;
        print("B) $n");
      } catch (e) {
        print("B) -");
      }
      int i = 0;
      while (Directory("/sys/devices/system/cpu/cpu$i").existsSync()) i++;
      print("C) $i");

```

This code on the Nokia 3.1 gives for B) and C) the same number of real cores, e.g. 8 on the Nokia 3.1, but for A) I get 2 or 5.

**Comment by darshankawar** [comment]
@jow-ct 
Is this still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
