### ISSUE TITLE
flutter attach to profile build should work

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#26711]
Currently trying to use flutter attach on a running profile build results in an exception when the DevFS cannot be setup:

```
Error -32603 received from application: Internal error
Error initializing DevFS: JSON-RPC error -32603 (internal error): Internal error
```

At the very least we should throw a better exception here.

**Comment by jonahwilliams** [comment]
This is actually required to setup forwarding for the observatory port used to debug profile builds

**Comment by balvares** [comment]
how did u solve the issue?
