### ISSUE TITLE
List with Blocs error, logs told me to file.

### ISSUE THREAD

**Issue by joaoritter** [flutter/flutter#26729]
## Steps to Reproduce

I'm working on abstracting a List Widget and the logs told me to report this!
## Logs

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building RoofUIList<AuthBloc, PublicActivityData>(dirty):
flutter: type '_ControllerStream<List<RoofUIStreamableData>>' is not a subtype of type
flutter: 'Stream<List<PublicActivityData>>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RoofUIList.build (package:roofui_kit/list/roofui_list.dart:18:26)
flutter: #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
flutter: #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #4      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #8      StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #22     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
flutter: #23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #33     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4585:32)
flutter: #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
Reloaded 0 of 671 libraries in 831ms.
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #54     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #68     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #80     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #84     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #91     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #92     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #93     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

No issues found! (ran in 1.9s)

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/joao/.flutter_build
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/joao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Muffie • 5db49d4dfec797ca1c3512f9b14c76e6bffcc6bc • ios • iOS 12.1.2

• No issues found!

**Comment by jonahwilliams** [comment]
The first stack frame is pointing to the source of the error: flutter: #0 RoofUIList.build (package:roofui_kit/list/roofui_list.dart:18:26):


 '_ControllerStream<List>' is not a subtype of type Stream<List>'.

This is a type error in your code and not flutter, so there isn't anything for us to do. That said if you need help consider asking  in one of the other channels listed at http://flutter.io/support
