### ISSUE TITLE
Test that putting app in background and bringing to foreground works

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#26728]
We need a test to help with https://github.com/flutter/flutter/pull/26727

Should be enough to start app, take screen shot, background app, go back to app, take screen shot again, and make sure that the app works.

App would need images/text

**Comment by henlamk** [comment]
Has there been any update on this?

**Comment by dnfield** [comment]
We still could use this kind of test.

Ideally, we'd run it on all the rendering backends we support (Vulkan, GL, Metal) and on all platforms we support.

One slightly challenging part of it is synchronization - I guess we could have some kind of service extension reporting the state the app thinks it is in.

**Comment by dnfield** [comment]
This test now happens for at least one application in the engine, called `android_background_image`.
