### ISSUE TITLE
Better Firabase & Flutter integration both ways for 2019 Please!

### ISSUE THREAD

**Issue by BenHayat** [flutter/flutter#26738]
I was just reading Tim Sneath's great 2019 roadmap for Flutter, one thing I didn't see mentioned, is a better integration of Flutter with Firebase and vice versa.
For all Firebase services, I only see iOS, Anrdoid, Web and unity. Nothing directly for Flutter/Dart.

We have decided for our next/new project to stay fully with Goolgle's products and services and Firebase is at the center of this big circle.

Please provide better integration, resources and examples in building seamless Flutter apps with FB.
Thanks!

**Comment by zoechi** [comment]
> Make sure that Flutter applications can take advantage of Google services, including in-app payments and YouTube.

> Google will also spend some time contributing plugins and tooling that you expect from Google.

> Bring Flutter’s first-party plugins and packages up to the same quality and completeness level as the core framework.

So this is currently high priority anyway.

I'm going to close this issue because it doesn't contain anything actionable that is not already covered by the general roadmap or other issues.

**Comment by BenHayat** [comment]
So, are you saying Firebase & Flutter (both ways integration) is high on the list?

**Comment by zoechi** [comment]
Yes, not sure what 

> and vice versa.

means exactly.

**Comment by BenHayat** [comment]
> a) can you refer to something specific?
Sure, just for someone who is starting Firebase setup to register his app, you see only the above apps with instructions how to register. If I select Android, the help instruction referes to Java solution and nothing related to Flutter. In Firebase, they have not done any direct support for Flutter

![app types](https://user-images.githubusercontent.com/7861196/51371963-a9247c00-1ac9-11e9-9738-828e1c0d9540.jpg)

**Comment by zoechi** [comment]
The Flutter Firebase plugins are wrappers over the native platform Firebase functionality.
So in regard to Firebase Flutter apps are iOS or Android applications (depending on what device they are running). 
I don't think there is anything to do except fixing known issues and implementing missing features in the existing plugins (wrappers).

**Comment by BenHayat** [comment]
Thanks for clarification. I'm VERY excited by the Flutter work.

Tim Sneath is a great PM. I used to work with him closely when he headed Silverlight at Microsoft back in 2007-2010.

**Comment by zoechi** [comment]
Yup he gave the community quite a boost ✨ ✨ 

Firebase is used a lot already with Flutter already. There are just some known bugs and recurring version conflicts with native libraries that currently need some manual intervention.
I did a bigger Flutter project myself with lots of Firebase integration last year.
