### ISSUE TITLE
Add an animation curve that is straight in the middle

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26743]
It would be nice to have a curve that starts going up fast, then flattens out, is flat at 0.5 for most of the interval, then speeds up and goes to 1.0 near the end in a mirror of what it does at the start. Sort of the same as inOut curves, but with the gradient starting at >1 instead of <1. An inverse S shape on its side.

cc @marcoms in case you're interested in doing that. :-)

**Comment by Kartik1607** [comment]
Something like this ? 
![image](https://user-images.githubusercontent.com/17377741/51378856-1a007e00-1b34-11e9-8f52-bc24ef526c82.png)

**Comment by marcoms** [comment]
Perhaps we could have an [`easeInOut` version](http://cubic-bezier.com/#0,1,1,0) as well for consistency

Now what could we name them? :thinking:

**Comment by Kartik1607** [comment]
fastInfastOut
slowInslowOut
?
