### ISSUE TITLE
How can I get a Flutter's texture from native plugin? (flutter => native. Not native => flutter)

### ISSUE THREAD

**Issue by bugttle** [flutter/flutter#26740]
Hi, I'd like to use a Flutter's texture by native plugin on Android/iOS. So, I'd like to pass a Flutter's texture to native plugin. (flutter => native)

My first plan is:

1. Use the camera plugin to get a previewed image.
    * https://github.com/flutter/plugins/tree/master/packages/camera
2. Pass the image(textureId or byte array) to native plugin.
3. Use the image in native code. (I'll create this plugin.)

But, I couldn't pass the image to native easily.

1. I didn't know how to get an image in native code by Flutter's textureId.
    * I know a texture will be able to passed to Flutter code from native code. (native => flutter)
2. I know I can take a screenshot and pass the byte array to native image.
    * But I think it is not effective.

I already checked the issue. But I think it is good to combine some plugins. So, I think use camera plugin to get an image and pass it to another plugin if it is possible.
> Using a live camera view with ML Kit plugin #19274

Could you please give me ideas?

Thank you.

**Comment by zoechi** [comment]
> But, I couldn't pass the image to native easily.

What have you tried where did you fail?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by reedom** [comment]
It's a good topic. Same thing I'm thinking these days how native-to-native API should be looked.

FYI, I've already made a  texture image data pipeline library in iOS. In Android, it is a bridge code between camera/texture, camera/visionML.

Currently it is in a large library that contains all customized code of camera/texture/visionML for my own product. Once I can find any good native-to-native API design, I can publish the library.
So I want to discuss about it.

----

In iOS, a texture data is a CVPixelBuffer, a Core Video pixel buffer. In a form of a pointer, not of NSObject.
To pass it to another native library, I think there are some ways:
a.

**Comment by bugttle** [comment]
@zoechi Thank you for your reply. I couldn't get a Flutter'a texture from native code by Flutter's textureId. Because of optimization. I think it is difficult, but I'd like to try it.

**Comment by bparrishMines** [comment]
Hi @bugttle, you can get a native camera image buffer by using a method called [startImageStream](https://pub.dartlang.org/documentation/camera/latest/camera/CameraController/startImageStream.html) in the camera plugin. 

You can see an example of passing an image byte data (CVPixelBuffer on iOS and byte[] on Android) from the camera to the [firebase_ml_vision](https://pub.dartlang.org/packages/firebase_ml_vision) plugin by taking a look at the [mlkit_demo](https://github.com/bparrishMines/mlkit_demo) project.

The only current limitation is that you can't change what the format will be without creating a fork of the camera plugin. The possible formats of the image buffers are described [here](https://pub.dartlang.org/documentation/camera/latest/camera/ImageFormatGroup-class.html).

**Comment by bparrishMines** [comment]
I suppose another limitation is that the image buffer has to pass to the dart side and then back to the native side. This has performance limitations.

**Comment by csells** [comment]
@bugttle hopefully the suggested solution solves your problem. If not, please follow up on Stackoverflow.
