### ISSUE TITLE
how to hide the bottom sheet

### ISSUE THREAD

**Issue by layou1989** [flutter/flutter#26747]
when i use a listview in bottom sheet and the listview can scroll,it can't hide when i scroll to the top of the listview

**Comment by zoechi** [comment]
Perhaps https://stackoverflow.com/questions/49778866/close-modal-bottom-sheet-programmatically-in-flutter combined with some scroll listener that detects when scrolled to top.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by layou1989** [comment]
not click，i want it close when pull down

**Comment by layou1989** [comment]
ok,thanks
