### ISSUE TITLE
but Android SDK not found at this location.

### ISSUE THREAD

**Issue by xssICE** [flutter/flutter#26746]
![832f72c3970fd583e8ac819b0f743eac](https://user-images.githubusercontent.com/21155133/51374403-ddd21b00-1b3d-11e9-9614-a70dbbd85ba1.jpg)

 ANDROID_HOME = /Users/*****/⁨Downloads⁩/android-sdk-macosx
but Android SDK not found at this location.

![qq20190118-162803](https://user-images.githubusercontent.com/21155133/51374458-0d812300-1b3e-11e9-8163-19dcfcadaa28.png)
![qq20190118-162839](https://user-images.githubusercontent.com/21155133/51374484-238ee380-1b3e-11e9-882e-9d10933113e8.png)

**Comment by zoechi** [comment]
Duplicate of #18593

**Comment by zoechi** [comment]
Please try the commands listed in the initial comment.

**Comment by xssICE** [comment]
> 请尝试初始评论中列出的命令。

Thank you for your guidance. The problem has been solved

**Comment by illidantao** [comment]
not work anymore
