### ISSUE TITLE
Document that SearchDelegate.buildResults can be called multiple times

### ISSUE THREAD

**Issue by guojiex** [flutter/flutter#26759]
## Steps to Reproduce

Edit the buildResults function in search_demo.dart in flutter gallery
```dart
  int count = 0;
  @override
  Widget buildResults(BuildContext context) {
    final int searched = int.tryParse(query);
    if (searched == null || !_data.contains(searched)) {
      return Center(
        child: Text(
          '"$query"\n is not a valid integer between 0 and 100,000.\nTry again.',
          textAlign: TextAlign.center,
        ),
      );
    }
    count += 1;
    print('count: $count');
    return ListView(
      children: <Widget>[
        _ResultCard(
          title: 'This integer',
          integer: searched,
          searchDelegate: this,
        ),
        _ResultCard(
          title: 'Next integer',
          integer: searched + 1,
          searchDelegate: this,
        ),
        _ResultCard(
          title: 'Previous integer',
          integer: searched - 1,
          searchDelegate: this,
        ),
      ],
    );
  }
```
Then run the flutter gallery example app and go to the material/search_demo page, search for any number. You can see that added print statement is called twice:
```bash
[+6761 ms] I/flutter (10784): count: 1
[  +35 ms] I/flutter (10784): count: 2
```

## Logs

```
```

```
```

[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /usr/local/google/home/jiexinguo/flutter/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/google/home/jiexinguo/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /usr/local/google/home/jiexinguo/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /usr/local/google/home/jiexinguo/Android/android-studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] VS Code (version 1.30.2)
    • VS Code at /usr/share/code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.

```
```

**Comment by HansMuller** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
This is probably a dup of https://github.com/flutter/flutter/issues/11655.

Also take note of https://github.com/flutter/flutter/issues/11655#issuecomment-412413030 in that issue. The fact that build is not called for every frame is basically just an optimization.

**Comment by goderbauer** [comment]
I understand a little better what you mean now.

`buildResults` is essentially just like any other `build` function in Flutter and subject to what's outlined in https://github.com/flutter/flutter/issues/11655#issuecomment-412413030. It is up to the implementor to cache search results if the query hasn't changed. That's something you should be able to do easily within the search delegate. 

I agree, we should point this out explicitly in the documentation for [buildResults](https://master-docs.flutter.io/flutter/material/SearchDelegate/buildResults.html). I am going to turn this into an api doc bug to fix that. Feel free to send a PR our way to address that :)
