### ISSUE TITLE
Gallery, selection controls, toggles all shadow when I tap the activated toggle

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2675]
Go to Gallery, Components, Selection Controls. Tap the toggle at the bottom.

Expected:

* only the toggle that I tap is shadowed

Actual:

* All three toggles are shadowed on tap

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (404/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:47575 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLg-000aXR-7h
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:37:22 +0100
Date: Mon, 14 Mar 2016 13:28:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987320;
	bh=arHyZIbgpXDeoLihw2FklzBo64nIxkzW19XB1omFh+w=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Aodc0rjriDA6Uq3uxeg+N8sYOBlYvcrDtoTU3CwpnjmSwV+DI/+SOfYaoEV7qtkL2
	 Ccg/pr1S5xoiuaLy/PL1QZeruRel9xwnGwjjG/6OWrLajkNxoooFdCAxMHtb0CkzD0
	 bHHBN4EH10fPCYUBX99DYwRFCqa2PjmORkkTiDz4=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (434/400 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:58815 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNY-000axA-Dj
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:14 +0100
Date: Mon, 14 Mar 2016 13:28:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987314;
	bh=MGN7Bi8MbxgU55QNNHPxuc+uZ39tgh3kjv7ijJoDFPw=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=czUPFE/Q18DDSqxR0Ci56BN4GLquNy/U44YeFXbpWcBV2zP9nj2VGmAFLEfOKN1Hv
	 dBiwt+RVl/tgjXHUEKyT0KEUZ+HWPf61xnV7gaqo9k+g2CCOuXVU5KxfJrQjTIMUPN
	 dHjzSfgutnVxHQH4cyZj3t2sifWT9ftYR+oepvs0=

**Comment by abarth** [comment]
Should be fixed now.
