### ISSUE TITLE
License scripts failing

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#26753]
Found the errors in the Skia->Flutter autoroller: https://autoroll.skia.org/r/skia-flutter-autoroll
It appears to be unrelated to Skia.
```
I0118 12:39:04.647987       1 pre_upload_steps.go:146] pre_upload_steps.go:146 Running [/data/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart lib/main.dart --release --src ../../.. --out /data/engine/src/out/licenses]
I0118 12:39:04.659762       1 exec.go:219] exec.go:219 Executing '/data/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart lib/main.dart --release --src ../../.. --out /data/engine/src/out/licenses' (where /data/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart is /data/engine/src/third_party/dart/tools/sdks/dart-sdk/bin/dart) with CWD /data/engine/src/flutter/tools/licenses
lib/main.dart:1: Warning: Interpreting this as package URI, 'package:licenses/main.dart'.
Finding files...
Collecting licenses...
      2626 of 10539 ██░░░░░░░░ 25% (0 missing licenses)  .../third_party/dart/runtime/vm/instructions_x64_test.ccerror searching for copyright in: ../../../third_party/dart/runtime/vm/intrusive_dlist.h
failed to find template LICENSE.md in ../../../third_party/dart/runtime/vm (authors=the dart project authors)


error searching for copyright in: ../../../third_party/dart/runtime/vm/intrusive_dlist_test.cc
failed to find template LICENSE.md in ../../../third_party/dart/runtime/vm (authors=the dart project authors)
```

**Comment by rmistry** [comment]
@liyuqian

**Comment by liyuqian** [comment]
@bkonyi @a-siva : this seems to be caused by https://github.com/flutter/engine/pull/7527

https://github.com/flutter/engine/pull/7527 passed the license test because it updates the third party license hash so the test skips third_party entirely. (See https://github.com/flutter/flutter/issues/25679#issuecomment-449511685)

CC @goderbauer

**Comment by bkonyi** [comment]
Working on a new roll with [this CL](https://dart-review.googlesource.com/c/sdk/+/90301) to fix hopefully the license issues.

**Comment by bkonyi** [comment]
Roll uploaded: flutter/engine#7534. Just waiting on checks to pass.

**Comment by liyuqian** [comment]
Thank you Ben for the quick fix!

**Comment by bkonyi** [comment]
No problem! The roll has landed, so this issue should be resolved now.

**Comment by rmistry** [comment]
Thanks! The Skia roll succeeded: https://github.com/flutter/flutter/issues/26753

Is there an open bug for the issue described in https://github.com/flutter/flutter/issues/25679#issuecomment-449511988 ?

**Comment by liyuqian** [comment]
@rmistry : I haven't found any so I creted https://github.com/flutter/flutter/issues/26899
