### ISSUE TITLE
How to encode image from dart that is decodable by python and viceversa

### ISSUE THREAD

**Issue by mabdullahrafique** [flutter/flutter#26755]
I am actually working to connect my flutter application with google virtual machine instance. I have set the python socket server ( code down below ) at vm instance that can take up an image, decode it and then call my machine learning model. Moreover after processing it should encode the image and send it back to my flutter application.

I previously tested my vm instance by writing up client code also in python where I used ** jsonpickle ** module, that encode and decode the image in a very good way ( Like I just have to do jsonpickle.decode(encoded_image) to get back numpy array of image ). Now I want my flutter application to connect to vm instance. 

Please tell me, which dart module should I use that can encode my images and can be sent over IOWebSocketChannel module in dart, and when received over python server at vm instance it is decodable to numpy array. Also, I can encode the output image at python server which when sent over to flutter can be decodable into an image. 

Here is my implemented client.py ( My program which successfully send, images to server )

    from autobahn.twisted.websocket import WebSocketClientProtocol, \
                                       WebSocketClientFactory
    import main
    import jsonpickle
    import base64
    import matplotlib.pyplot as plt
    import time
    class MyClientProtocol(WebSocketClientProtocol):

    def onConnect(self, response):
      print("Server connected: {0}".format(response.peer))

    def onOpen(self):
      print("WebSocket connection open.")

      def hello():

         # opening the image file and encoding in base64
         path = "/home/abdullah/Desktop /Clocktower_Panorama_20080622_20mb.jpg"
         image = main.load_image(path)
         encoded = jsonpickle.encode(image)
         # printing the size of the encoded image which is sent
         # print("Encoded size of the sent image: {0} bytes".format(len(encoded_string)))

         # sending the encoded image
         self.sendMessage(encoded.encode('utf-8'))

      hello()

     def onMessage(self, payload, isBinary):
      print("Output processed image received")
      output = main.image_post_process(payload)
      plt.imshow(output)
      plt.show()
      print("Done")
      reactor.stop()

        # plt.show()
       def onClose(self, wasClean, code, reason):
          print("WebSocket connection closed: {0}".format(reason))

     if __name__ == '__main__':
       time1 = time.time()

       import sys

       from twisted.python import log
       from twisted.internet import reactor

       # log.startLogging(sys.stdout)

       factory = WebSocketClientFactory()
       factory.protocol = MyClientProtocol

       reactor.connectTCP("34.73.158.146", 5903, factory)
       # reactor.connectTCP("localhost", 9933, factory)

       reactor.run()
       time2 = time.time()
       print("Total time is ", time2-time1)
  

Here is my server.py implemented at vm instance.

     rom autobahn.twisted.websocket import WebSocketServerProtocol, \
                                      WebSocketServerFactory

     # import the base64 module
     import base64
     import jsonpickle
     import time

     import main

     class MyServerProtocol(WebSocketServerProtocol):

       def onConnect(self, request):
          print("Client connecting: {0}".format(request.peer))

       def onOpen(self):
          print("WebSocket connection open.")

       def onMessage(self, payload, isBinary):
          print("Message received")
          time1_total = time.time()
          #output = main.main_function(payload)
          #time1 = time.time()
          #encoded = main.send_image_server(output)
          #time2 = time.time()

          #print("Total time to process image is ", time2-time1)

          # echo back message verbatim
          time1 = time.time()
          self.sendMessage(encoded)
          time2 = time.time()
          print("Total time taken to do everything is  ", time2-time1_total)
       def onClose(self, wasClean, code, reason):
          print("WebSocket connection closed: {0}".format(reason))

     if __name__ == '__main__':

       import sys
          
       from twisted.python import log
       from twisted.internet import reactor

       log.startLogging(sys.stdout)

       factory = WebSocketServerFactory()
       factory.protocol = MyServerProtocol

       reactor.listenTCP(5903, factory)
       reactor.run()

Here is what I am trying at my flutter code, to send image over socket, but the connection at server close immediately after opening:

    File imageFile = new File(imageFilePath);
    List<int> imageBytes = imageFile.readAsBytesSync();
    String base64Image = BASE64.encode(imageBytes);

Please, tell me how can I overcome it or is there any way in which I can use my above client.py code in flutter to avoid the complexities.

Thanks

**Comment by zoechi** [comment]
Also asked on https://stackoverflow.com/questions/54254659/how-to-encode-image-from-dart-that-is-decodable-by-python-and-viceversa which is the right place.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by mabdullahrafique** [comment]
Ok, but no one is answering the question
Thanks

**Comment by zoechi** [comment]
@mabdullahrafique be patient. You asked 1h ago. Friday is usually a quite day with few people answering. You could try to improve your question.  The question contains a lot of text and code while it looks like the main issue is that you can create a stable websocket connection to your Python server, but most of the question (title/content) seems to indicate that it's about image en/decoding. Questions that cause confusion are much less likely to be answered.
Check if there is some error output on client or server. Error message are usually a great help for diagnosing issues.

**Comment by Cristeen20** [comment]
@mabdullahrafique Please share if you got any solution. I am trying to pass image from flutter to python api.

Have already tried
-List<int> imageBytes = imageFile.readAsBytesSync();
-        List<int> imageBytes = await file.readAsBytes();
        String base64Image = base64Encode(imageBytes);
