### ISSUE TITLE
Chinese Font is render weird with FontWidget

### ISSUE THREAD

**Issue by a396901990** [flutter/flutter#26752]
## Steps to Reproduce
![screen shot 2019-01-18 at 7 51 45 pm](https://user-images.githubusercontent.com/8385255/51387232-4631f400-1b60-11e9-9819-6114d6a770a2.png)
![screen shot 2019-01-18 at 7 54 46 pm](https://user-images.githubusercontent.com/8385255/51387235-46ca8a80-1b60-11e9-8044-4de051482f2b.png)
![screen shot 2019-01-18 at 7 55 12 pm](https://user-images.githubusercontent.com/8385255/51387236-47632100-1b60-11e9-9795-2177dbc55cf1.png)

code:
```dart
child: Text(
            team.destination,
            style: Theme.of(context).textTheme.title,
            overflow: TextOverflow.fade,
            softWrap: false,
            maxLines: 1,
          ),

// title style is redefined in custom theme using FontWeight.w500:
title: base.title.copyWith(
      fontSize: 18.0,
      fontWeight: FontWeight.w500,
      color: TColors.kTextPrimary,
    )
```

## Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.117, on Mac OS X 10.14.1 18B75, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.2)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.30.1)
[✓] Connected device (2 available)
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by kangwang1988** [comment]
@a396901990 
Try set a fontFamily for MaterialApp, e.g., "PingFang SC"(>=iOS9) or "STHeiti SC"(<iOS9).

**Comment by kangwang1988** [comment]
Close #26752 as duple of https://github.com/flutter/flutter/issues/25726

**Comment by a396901990** [comment]
> Close #26752 as duple of #25726

Thanks @kangwang1988, set PingFang SC working for me.

**Comment by kangwang1988** [comment]
@a396901990 
Remember to set fontfamily for iOS9+ and below iOS8 seperately.
PingFang SC doesn't exist in iOS8.
