### ISSUE TITLE
Gallery's time dialog is larger than other apps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2676]
We seem to be drawing the time dialog with a larger width than other apps. One side effect of this is that the circle for the clock is larger, and the space between the numbers is larger, so it makes our numbers look smaller.

Calendar app:

![screenshot_20160314-134017](https://cloud.githubusercontent.com/assets/5479/13759248/a9ba67c8-e9ea-11e5-8cbc-3ce6aebfeba2.png)

Gallery, Components, Dialog, Confirmation:

![screenshot_20160314-134021](https://cloud.githubusercontent.com/assets/5479/13759249/a9bb3b80-e9ea-11e5-99ef-fc8b5a9b0652.png)

**Comment by sethladd** [comment]
I think @abarth did some work on this recently?

**Comment by abarth** [comment]
Yes, we now match the spec, which is different than the OEM widget.

**Comment by sethladd** [comment]
Thanks for the help!
