### ISSUE TITLE
We should provide a way to detect whether frames are rendering or have rendered

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#26760]
For testing frameworks, we want to know when we've reached the second frame so we can start interacting with the app.

It would be good if we could also know when rendering has resumed, e.g. after the app has been put in the background and resumed.

It would be ideal if this information could be published in a cross platform way, e.g. over the vm service protocol.

**Comment by xster** [comment]
@matthew-carroll @dnfield we fixed this now right?

**Comment by dnfield** [comment]
Yes.
