### ISSUE TITLE
complex_layout_scroll_perf__memory regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26768]
`complex_layout_scroll_perf__memory end-max` has regressed. It's especially noticeable in the `diff-median` graph.

The potential candidate commits are:
- https://github.com/flutter/flutter/commit/29928a46ed240bc78e9d3d6e203f9993d3dd5c3e
- https://github.com/flutter/flutter/commit/fc779c69a728796b62544bf2aa9b2753531759ce
- https://github.com/flutter/flutter/commit/e8bfa81b707d68e58e82f6d1e3a17a5e5831bf38
- https://github.com/flutter/flutter/commit/f3f2d5a1bd89884072a547ec3a3de6d8d9fa7743
- https://github.com/flutter/flutter/commit/71a15896d8f473331061f1e564bf7f3770d73e8d
- https://github.com/flutter/flutter/commit/584ef083c7db55397108ff5aedc7a320a41b23f2
- https://github.com/flutter/flutter/commit/684d0507911ab08ccbd20280f6fa418ad517b0ab

Due to noise it's hard to say exactly which is to blame.

cc @goderbauer @jason-simmons

**Comment by cbracken** [comment]
I've updated the manual engine roll in there (e8bfa81) with the full commit list to make tracking this down simpler.

The above roll seems more likely to contain the culprit than 684d050, which is limited to a Skia roll, and some dynamic-mode validation patches.

**Comment by liyuqian** [comment]
Close this as everything seems to be back to normal.
