### ISSUE TITLE
PlatformView has black background when being loaded

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#26771]
I just followed this tutorial (https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6) to embeded a TextView (android) into my Flutter app. But I noticed that when it is being loaded up , it renders over a black background container. I believe it occurs because PlatformView is heavy a lot and the framework needs some time to load it up. 

But instead of black background, shouldn't it be transparent? It causes some pretty ugly effect when the screen is being loaded.

I've run the app into a Motogola G5 Plus smartphone and the problem occurs in debug and also release versions.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17763.253], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code (version 1.30.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by buaashuai** [comment]
this problem can also reproduce in OPPO A73, OPPO R15 et devices.

**Comment by yohom** [comment]
Is there any workaround to avoid this bug? Something like `FutureBuilder` to wait `PlatformView`s initialization completed? @amirh

**Comment by The-Redhat** [comment]
This [issue](#39797) might be related.

**Comment by knissophiliac** [comment]
I'm using Google Maps Package. After several times "minimizing the app by home button then opening again from app manager", GoogleMap widget goes black and user cannot play with it anymore. I guess it's related to this issue. Is there a workaround?

**Comment by darshankawar** [comment]
@shinayser 
Is this still a valid issue using latest Flutter version ?

**Comment by Sunbreak** [comment]
On latest stable version, i.e. flutter-1.22.4, `webview_flutter` with default virtual-display reproduces the problem while hybrid-composition works fine

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by bdlukaa** [comment]
I can still see this issue. It happens for a few milliseconds while the platform view is loading. Steps to reproduce:

1. Create a Platform View
2. Add it to the widget tree

You should see a black object before the platform view is completely loaded. It only happens when using `VirtualDisplay`

<details>
  <summary>Flutter doctor</summary>

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versÃ£o 10.0.19041.804], locale pt-BR)
    • Flutter version 1.22.6 at C:\Users\bruno\Documents\flutter\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\bruno\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • moto x4 (mobile) • 0040962706 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
</details>

**Comment by Sunbreak** [comment]
Yep. [hybrid-composition](https://github.com/flutter/flutter/wiki/Hybrid-Composition) is supposed to fix that.

And I don't think Flutter team would invesitage more into `VirstualDisplay` ever further

**Comment by bdlukaa** [comment]
@Sunbreak 
> Yep. hybrid-composition is supposed to fix that.

When I tried to use hybrid composition inside of a `ListView` ([project](https://github.com/bdlukaa/native_admob_flutter/tree/master/example)), it came with some rendering issues. And as said in the flutter docs ([platform-views/performance](https://flutter.dev/docs/development/platform-integration/platform-views#performance)), it has some performance inssues on Android 10 or above.

> Prior to Android 10, Hybrid composition copies each Flutter frame out of the graphic memory into main memory, and then copies it back to a GPU texture. In Android 10 or above, the graphics memory is copied twice. As this copy happens per frame, the performance of the entire Flutter UI may be impacted.

**Comment by Sunbreak** [comment]
They would probably improve hybrid-composition intead of improving `VisualDisplay`
