### ISSUE TITLE
Fix coveralls

### ISSUE THREAD

**Issue by xster** [flutter/flutter#26791]
https://coveralls.io/github/flutter/flutter is showing random repos' contents. We're still clearly correctly uploading the data by POSTing to https://coveralls.io/api/v1/jobs directly in upload_to_coveralls.py but it's failing to reference various meta. 

It seems like it's generally retrieved from a CI system but Cirrus isn't supported. https://docs.coveralls.io/api-introduction. Either get it supported on Cirrus (then use https://coveralls.io/webhook?repo_token= since we're not actually mapping the coverage on Cirrus) or figure out the equivalent needed APIs https://docs.coveralls.io/api-reference

**Comment by godofredoc** [comment]
Obsolete. Please reopen if this is still necessary.
