### ISSUE TITLE
About Separation of concerns

### ISSUE THREAD

**Issue by binggg** [flutter/flutter#26794]
Everything in Flutter is a Widget and it looks cool. 

I have a problem. In the W3 web standard, I will use "HTML + CSS + JavaScript" to develop a web page. The standard consideration is the separation of structure and style from behavior, so that you can get better code maintainability and more. Good accessibility and many other advantages, development efficiency is also very high, and even the style can be done by a dedicated UI development engineer.

Will Flutter's current way of doing all things with Widgets lead to bloated code that is more difficult to develop and maintain? Why not learn from the web side of the idea, such as separating the style and structure? Is it possible in the future?

**Comment by Kartik1607** [comment]
There are different architectural patterns you can use to separate styling, structure, data models etc. Have a look at [this](https://github.com/brianegan/flutter_architecture_samples) repo. It shows great patterns which can lead to easier to maintain code with better efficienct.

**Comment by binggg** [comment]
@Kartik1607 
Thank you. I will take a closer look, I see a lot of examples.
