### ISSUE TITLE
screen video recording in flutter

### ISSUE THREAD

**Issue by mostafa5731** [flutter/flutter#26805]
Is there any way of screen video recording using flutter? if yes, how? if no 😭😢.

**Comment by kangwang1988** [comment]
I think you need a Flutter Plugin to do this.
@mostafa5731 
But I don't any existing plugin from: https://pub.dartlang.org/packages?q=screen+record

**Comment by Kartik1607** [comment]
I don't know if this is even possible. Can flutter render transparent widget at the root? (Such that home screen is visible). Can flutter create widgets like Facebook Messenger chat popups? I haven't seen any such code till now

**Comment by dariotrombello** [comment]
Why would someone need such a package? I dont know any apps where screen video recording is used as a by-the-way feature. What I do know is that there are some kind of screen recording apps available but that's all what they do (their main feature). I don't think that a package should represent the main feature in the app. That's not the purpose of packages in my opinion.

**Comment by zoechi** [comment]
Similar to #8245

**Comment by Hixie** [comment]
@mostafa5731 do you mean screen recording from an app recording itself, or during development from the `flutter` tool?

**Comment by salime45** [comment]
i am searching for a way to screen recording my app and save the video in  gallery user. Any advance in achieve this?

**Comment by sunjianan9900** [comment]
> Why would someone need such a package? I dont know any apps where screen video recording is used as a by-the-way feature. What I do know is that there are some kind of screen recording apps available but that's all what they do (their main feature). I don't think that a package should represent the main feature in the app. That's not the purpose of packages in my opinion.

I make an LED scroller App with many animation
and my user asking me how to save video/GIF to their album
my app really need record screen ，it is even better that can record the widget！

**Comment by salime45** [comment]
https://pub.dev/packages/flutter_screen_recording

**Comment by faizanrafiq7** [comment]
Yes got it but how to save that video in mobile storage?

**Comment by faizanrafiq7** [comment]
> https://pub.dev/packages/flutter_screen_recording

Yes got it but how to save that video in mobile storage

**Comment by kamleshwebtech** [comment]
I am looking solution of Stream Screen Recording in flutter, is there any suggestion?? Thanks in advance.

**Comment by kamleshwebtech** [comment]
Friends, did you find any solution? I am looking solution of Stream Screen Recording in flutter, is there any suggestion?? Thanks.
