### ISSUE TITLE
[Solved] Flutter runs hang at install after uninstalling the app manually from phone

### ISSUE THREAD

**Issue by ghirlekar** [flutter/flutter#26806]
### Problem
Uninstalling the app from the home page would cause subsequent `flutter run` commands to hang at the installing stage.

Running with `flutter run -v` showed that it installed successfully but the activity would not run when adb tried to run it.

### Error output
The error message was class 3 `${packageName}/${packagName}.MainActivity` not found.

### Hacky fix
Changing the android app package name would cause it to work again until I uninstalled it manually from the phone.

### Steps that did not work
1. Rebooting the phone multiple times
1. `flutter clean` didn't solve it
1. Restarting Android studio
1. Restarting my computer
1. Re-enabling USB debugging
1. Revoking and authorizing my computer from USB debugging
1. Re-enabling developer mode
1. adb shell pm list package ${packageName} didn't show it in the list so there was nothing to clean through there

### Permanent fix
`adb uninstall ${packageName}` output `Success`. 
Now subsequent flutter runs work perfectly.

It seems uninstalling apps from the home screen does leave some intent or activities in some cache somewhere.

**Comment by dariotrombello** [comment]
Can be closed now.

**Comment by KieranSteyn** [comment]
This is still an issue...
It happens with my phone (OnePlus 6) but not with my colleague's (OnePlus 6T). 
It an issue with any flutter app that I've deployed to my phone. The only solution I've found is to adb uninstall. Which is often not viable if you're out and about and need to install the prod version of your app.
