### ISSUE TITLE
video_player plugin: Duration sometimes reported as 0 on iOS

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#26817]
```dart
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    Demo(),
  );
}

class Demo extends StatefulWidget {
  Demo();

  @override
  State<StatefulWidget> createState() {
    return _DemoState();
  }
}

class _DemoState extends State<Demo> {
  void test() async {
    VideoPlayerController controller;

    while (true) {
      controller = VideoPlayerController.network(
          'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4');
      await controller.initialize();
      print(controller.value.duration);
      if (controller.value.duration == Duration()) {
        print('!!!! DURATION WRONG !!!!');
      }
      await controller.dispose();
      await Future<void>.delayed(Duration(milliseconds: 200));
    }
  }

  @override
  void initState() {
    super.initState();
    test();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale de-CH)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by cbenhagen** [comment]
Can't reproduce the issue with the current plugin version.

**Comment by cbenhagen** [comment]
Sorry I need to reopen this. While in the test code I was not being able to reproduce, in a full app I was. Need to check why.

**Comment by mattkj** [comment]
I'm having the same issue. Duration is sometimes reported as 0 on iOS. It's very noticeable when it happens because the VideoProgressIndicator widget will throw an exception:

`flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following UnsupportedError was thrown building LinearProgressIndicator(100.0%, dirty,
flutter: dependencies: [Directionality], state: _LinearProgressIndicatorState#12843(ticker inactive)):
flutter: Unsupported operation: Infinity or NaN toInt`

**Comment by cbenhagen** [comment]
@mattkj while the fix I proposed in https://github.com/flutter/plugins/pull/1094 might not be ideal, it fixes the issue reliably for us.

**Comment by mattkj** [comment]
Thanks, I'll take a look.

**Comment by cbenhagen** [comment]
Fixed in https://github.com/flutter/plugins/pull/1554/files#diff-e534c460662d39cc715c4eed77a31c3fR308
