### ISSUE TITLE
Create unique names for simulator executables and update tooling to check that the correct one is running

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2681]
`flutter -d iPhone run` to my Simulator shows a white screen on the Simulator for ~2 seconds, and then the Flutter apps quits.

When I try to manually run the app in my Simulator, I get this error:

![screen shot 2016-03-14 at 2 21 16 pm](https://cloud.githubusercontent.com/assets/5479/13760399/33ccc7bc-e9f0-11e5-9210-13689ba57f9d.png)

**Comment by sethladd** [comment]
cc @chinmaygarde

**Comment by sethladd** [comment]
We think this is because I had multiple apps named "runner" installed on my simulator. Once I cleaned the simulator and reset its data, `flutter run` started to work just fine.

**Comment by eseidelGoogle** [comment]
Could this be causing https://github.com/flutter/flutter/issues/3360 ?

**Comment by chinmaygarde** [comment]
I am redoing the Xcode projects for the different buckets anyway. Will take a stab at fixing this while I am at it.

**Comment by Hixie** [comment]
This isn't really actionable any more. If you see this again please file a new bug with more specifics.
