### ISSUE TITLE
firebase_admob should treat app installation as reward

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#26828]
I'm not sure if it should work this way by design, but IMO if user already had an interaction with rewarding ad (clicked on install), plugin should emit `rewarded` event

**Comment by lesnitsky** [comment]
Is there a way to know that user actually clicked on the install button? So that this behaviour could be handled on app side, not on a library side?

**Comment by kroikie** [comment]
@lesnitsky

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/500. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
