### ISSUE TITLE
App Icon looks different on some devices

### ISSUE THREAD

**Issue by CubE135** [flutter/flutter#26824]
## Steps to Reproduce

1. Add the flutter_launcher_icons package to pubspec.yaml
2. Add the following configuration to the pubspec.yaml file:
```
flutter_icons:
  android: true 
  ios: true
  image_path_android: "assets/img/icon/ic_launcher_xxxhdpi.png"
  image_path_ios: "assets/img/icon/ios.png"
  adaptive_icon_background: "assets/img/icon/ic_background.png"
  adaptive_icon_foreground: "assets/img/icon/ic_foreground.png"
```
Images used: [Icons](https://puu.sh/CzM5U/7da74dc7cf.zip)

3. Run `flutter packages pub run flutter_launcher_icons:main`.
4. Build the app and install it on different devices. In my case i used a Honor 8, Samsung Galaxy J3 and a Samsung Galaxy Tab.
5. Watch the result:
![Image of the Problem](https://cdn.discordapp.com/attachments/421445316617961502/536651141774180352/compare_1.png)
6. As you can see on the Screenshot above, the App Icon looks different on those two devices. The left device is the Galaxy J3, the right one is the Honor 8. I've let several people test it on their phones with different results. Some get the "zoomed in" ugly looking version (left image), some get the normal (right image).

I really dont know what the issue is. As you can see above, im even using adaptive icons, so i really dont know what to do.

## Logs

**Flutter Analyze**
```
No issues found! (ran in 2.6s)
```

**Flutter Doctor**
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale de-DE)
    • Flutter version 1.0.0 at D:\CubE\Desktop\Programme\flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\CubE\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\CubE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 32-bit edition (version 1.29.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by dnfield** [comment]
I'd recommend opening an issue at the flutter_launcher_icons repo (https://github.com/fluttercommunity/flutter_launcher_icons/issues).  It seems likely that something is going wrong for specific device resolutions/android versions with that package - or perhaps something in the tool isn't getting invoked the way you expect.

As that project is not part of this organization, I'm going to close this issue for now - if you find that your configuration for that is correct and it is in fact a bug in the Flutter framework or tooling, please feel free to open with more details!

**Comment by thomphow** [comment]
I faced the same problem. While it is a problem with flutter_launcher_icons, or maybe simply the default settings aren't turning out so great.... a work around is just to use Image Asset Studio (part of Android Studio) to create the desired icons for your Android app. Change your android/app/main/AndroidManifest.xml  android:icon="@mipmap/ic_launcher"> to point to your generated icon file. You may have to copy your icon files from their mipmap folders up to their drawable folder(s) pending how they are referenced.  Here is a nice link to a video on how to use Image Asset Studio. https://youtu.be/Q27hBWQpV-8
