### ISSUE TITLE
Difficult to determine number of documents fetched by StreamBuilder

### ISSUE THREAD

**Issue by kbrmimbyl** [flutter/flutter#26821]
I'm using StreamBuilder in a real-time chat app using Firestore. To pull old chat messages from Firestore when the user scrolls to the top, I'm just incrementing `_queryLimit` in the following code:
```dart
            StreamBuilder(
              stream: Firestore.instance
                  .collection('messages')
                  .document(groupChatId)
                  .collection(groupChatId)
                  .orderBy('timestamp', descending: true)
                  .limit(_queryLimit)
                  .snapshots(),
              builder: (context, snapshot) {...
```
If Flutter is doing what I think it's doing, only one document read should happen when `_queryLimit` is incremented by one.

While debugging, I could see that  `snapshot.data.documentChanges` contains only one document, viz., the new one visible on the screen.

But that doesn't tell me that only one document was actually fetched from Firestore. _If a document doesn't change, is it _never_ downloaded? What if the local snapshot had to be removed for memory reasons?_ Although I expect the answer is 'no' in most cases, I'd like to see it while running my code... so that my Firebase charges are predictable.

Put differently, the parameter `documentChanges` doesn't tell the whole story. Maybe a `documentsFetched` will remove (at least) my confusion...

**Comment by zoechi** [comment]
Is there any similar functionality in native (Android/iOS) firebase?
Flutter is only a wrapper over native Firebase libs and it can't provide anything the underlying system doesn't provide.

**Comment by zoechi** [comment]
If it's not specific to Firebase it would be very helpful if you could post a minimal reproduction that demonstrates the issue (without any Firebase dependency in the code)

**Comment by kbrmimbyl** [comment]
There's no Firebase dependency in the code snippet above... ?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
