### ISSUE TITLE
RSA decryption with pointycastle library

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#26823]
Hello, on the physical device (iOS), on android it fast, wild slow work with rsa, decryption with a private key on average 6 seconds, generation of keys with such parameters RSAKeyGeneratorParameters (BigInt.from (65537), 2048, 12);

iOS debug (iPad Pro 10,5 Wi-Fi + Cellular 256GB )
Flutter: start time 42:48
Flutter: time is the end 46:10

which is very long.
At the moment there is no possibility to collect the release version, so the question with the release version somehow helps or the problem lies deeper?
```dart
Tuple2<RSAPublicKey, RSAPrivateKey> generateKeyPair() {
    var random = Random.secure();
    var key = Uint8List.fromList(List.generate(32, (_) => random.nextInt(255)));
    var secureRandom = FortunaRandom()..seed(KeyParameter(key));
    var rsaParams = RSAKeyGeneratorParameters(BigInt.from(65537), 2048, 12);
    var keyGenerator = RSAKeyGenerator()
      ..init(ParametersWithRandom(rsaParams, secureRandom));
    AsymmetricKeyPair keys = keyGenerator.generateKeyPair();
    return Tuple2(keys.publicKey, keys.privateKey);
  }

```

```
[✓] Flutter (Channel master, v1.1.10-pre.135, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.1.10-pre.135 at /Users/alexfix/Flutter/flutter
    • Framework revision d8d36bc7e8 (2 days ago), 2019-01-19 11:59:42 -0800
    • Engine revision 898b4f8da4
    • Dart version 2.1.1 (build 2.1.1-dev.2.0 2e5453ddb4)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexfix/Library/Android/sdk
    • Android NDK at /Users/alexfix/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPad (Vlad) • 72adb92946d0dd4d658c5fe474d4141196138bcf • ios • iOS 12.0.1

• No issues found!
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please add more details about your devices and what mode (debug/profile/release) you used to get the numbers you posted.

**Comment by 1AlexFix1** [comment]
> вы

**Comment by 1AlexFix1** [comment]
> There were some performance issues fixed recently
> [dart-lang/sdk#35619](https://github.com/dart-lang/sdk/issues/35619), [dart-lang/sdk#34960](https://github.com/dart-lang/sdk/issues/34960)
> Ensure you are using a recent Flutter version that contains these fixes (`dev` or `master` channel).

I fixed the issue, I can’t collect the release build at the moment, so I’m very worried about the question, is this slow speed related to the debug version or will the same be in the release version?

**Comment by zoechi** [comment]
I can't tell. 
If there are actually performance issues in release mode, please create an issue and the specialists will investigate.

**Comment by 1AlexFix1** [comment]
> Я не могу сказать. 
> Если в режиме выпуска действительно есть проблемы с производительностью, создайте проблему, и специалисты проведут расследование.

Understood thanks.
