### ISSUE TITLE
firebase_admob pauses video when app goes to background

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#26829]
When user switches app during rewarding video playback and brings it back to active state, video is paused. Yes, if user clicks on "close" button he/she is prompted to resume the video, but it would be nice to have an API to automatically continue playing video

**Comment by kroikie** [comment]
@lesnitsky

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/499. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by stuartmorgan** [comment]
Closing, as `firebase_admob` is [now deprecated](https://pub.dev/packages/firebase_admob/versions/0.11.0+2).
