### ISSUE TITLE
Share image with social media then Security Exception: Permission Denial: occur  

### ISSUE THREAD

**Issue by MistryHiral** [flutter/flutter#26836]
```
 Writing exception to parcel
E/DatabaseUtils(28334): java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://com.example.wordguess.adv_provider/cache_files/1548049461.png from pid=29230, uid=10202 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils(28334): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:646)
E/DatabaseUtils(28334): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:493)
E/DatabaseUtils(28334): 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:484)
E/DatabaseUtils(28334): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:429)
E/DatabaseUtils(28334): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
E/DatabaseUtils(28334): 	at android.os.Binder.execTransact(Binder.java:453)

```

**Comment by kangwang1988** [comment]
@MistryHiral 
`flutter doctor -v`
and a minimal project(or main.dart) to help reproduce this issue would be more helpful.

**Comment by zoechi** [comment]
This doesn't look Flutter related.
https://stackoverflow.com/questions/50090394/securityexception-on-granturipermissions might help.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by MistryHiral** [comment]
> This doesn't look Flutter related.
> https://stackoverflow.com/questions/50090394/securityexception-on-granturipermissions or https://stackoverflow.com/questions/30572261/using-data-from-context-providers-or-requesting-google-photos-read-permission/30909105#30909105 might help.
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
I find its solution but not understand how is implement and where to write code in this given link (https://github.com/mrtcndnlr/Flutter-Advanced-Share/issues/2)
