### ISSUE TITLE
Issue from website page 起步: 体验

### ISSUE THREAD

**Issue by XiaoYun** [flutter/flutter#26831]
From URL: https://www.flutterchina.club/get-started/test-drive.md

**Comment by kangwang1988** [comment]
The repo you mentioned is not maintained by flutter team.
See https://flutter.io for more.

**Comment by kangwang1988** [comment]
Close #26831

**Comment by zoechi** [comment]
@kangwang1988 I find it a bit confusing when you link to the current issue when closing.
Mentioning the issue number is mostly for linking to duplicates or in PR commit messages. 

If you don't see value in mentioning a specific close reason, I think you can just close without comment. (usually it's better to mention some reason even if it's a simple or obvious one).
