### ISSUE TITLE
Cannot reduce graphics memory leak of my android app

### ISSUE THREAD

**Issue by yashwanthBhargav** [flutter/flutter#26837]
![capture](https://user-images.githubusercontent.com/33343424/51457078-f4fb4d80-1d75-11e9-9e17-2c984153d931.PNG)
![capture2](https://user-images.githubusercontent.com/33343424/51457079-f4fb4d80-1d75-11e9-8c30-7cb5d2a4a0bf.PNG)

I am using ImageProvider in 2 parts of my code 
1.getting bytes from a file in system
2. drawing image on canvas
And i guess this is the reason for the memory leak 
I tried clearing the imageCache of the PaintingBinding but didnot solve my problem

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by yashwanthBhargav** [comment]
Output of flutter doctor

[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\Users\USER\Desktop\flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Redmi 6A • 47c6067e7d29 • android-arm • Android 8.1.0 (API 27)

• No issues found!

**Comment by yashwanthBhargav** [comment]
It's in general with any canvas, here run this app : [DrawApp](https://github.com/SnakeyHips/drawapp)

Steps : 
 - Run any flutter canvas app
 - Run the Profiler in android studio
 - Check for graphics memory
 - Doodle a lot on the canvas using 2 finger touch gesture, I mean a lot please
 - Graphic memory will be like 1GB or more
 - Clear canvas and wait
 - Memory won't come down, won't free memory (Manual System GC on native java using method channel won't work either)

I am trying to make the same app like that one.

**Comment by yashwanthBhargav** [comment]
@zoechi It would help us if we have a work around or something to clear graphics memory, cuz we will be using our application in production. Right now it takes around 0.7-1GB which isn't good for our app.

**Comment by zoechi** [comment]
Have you also tried if you can still reproduce with `master` or `dev` channel?

**Comment by yashwanthBhargav** [comment]
Isn't latest stable is on Master? I haven't tried with dev channel

**Comment by zoechi** [comment]
Latest `stable` is from about December 1st and `master` is from yesterday and `dev` is usually about 1-5 days old.

**Comment by yashwanthBhargav** [comment]
Master goes to 3.1GB Peak and 1.1GB constant. I am gonna try Dev as well

**Comment by hey24sheep** [comment]
I am facing this same issue. Also if you put the app in the background, GC will run but Graphic Memory won't get freed. How can we solve this issue for the time being?

**Comment by jason-simmons** [comment]
This started when CCPR was enabled in Skia: https://github.com/google/skia/commit/a2b5b6467f347962e0d6942da0dff9148fbb3375

@csmartdalton86

**Comment by chinmaygarde** [comment]
CCPR has been disabled.
