### ISSUE TITLE
Gallery, Drop-down buttons have different top and bottom paddings

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2683]
Notice how, in Flutter's drop-down, the padding at the top and bottom seem to be different. There seems to be more space in the top padding. Also, notice how there is a lot of left-padding in Flutter's drop-down, where in a Google app's drop-down we see left-justified text with minimal left-padding (not sure if either or both are correct here).

From the Gallery:

![simulator screen shot mar 14 2016 2 31 36 pm](https://cloud.githubusercontent.com/assets/5479/13760735/d78b5ec6-e9f1-11e5-9cd6-a92be50efa36.png)

From a Google app:

![screenshot_20160314-140745](https://cloud.githubusercontent.com/assets/5479/13760742/e228128e-e9f1-11e5-896e-b6c9fdc75442.png)

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by Hixie** [comment]
Notice how the text is offset a bit in the "SLOW MODE" banner too. My guess is the bug here is with the placement of the text, not the padding.
