### ISSUE TITLE
Stocks, Setting, bottom toggles blend with background

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2684]
Please see the screenshot. Notice how the bottom two toggles have white circles that blend with the background. (they still work)

![screenshot_20160314-144412](https://cloud.githubusercontent.com/assets/5479/13761031/6bc1bf1c-e9f3-11e5-95e0-209e986d14a3.png)

**Comment by sethladd** [comment]
cc @Hixie

**Comment by abarth** [comment]
They're missing the shadows.  There's a bug on file about that.

**Comment by abarth** [comment]
#2670

**Comment by sethladd** [comment]
Thanks! Will close this as a dupe.
