### ISSUE TITLE
window.devicePixelRatio changes in same mobile.

### ISSUE THREAD

**Issue by wilin52** [flutter/flutter#26841]
I import Flutter as a module into an app. The first time flutterActivity started, the value of `window.devicePixelRatio` is correct. But then finish the activity, and restart( one time or more than one, different mobile differs.)  `window.devicePixelRatio` is `1.0` the default value. 
I use `window.devicePixelRatio` in  `Widget build(BuildContext context)`

Thank you for replying.😊

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please share a minimal reproduction project ideally published to GitHub.

**Comment by wilin52** [comment]
I'm sorry so late to reply. Too busy to reply.😊

$ flutter doctor -v
[✓] Flutter (Channel dev, v0.11.13, on Mac OS X 10.13.6 17G4015, locale zh-Hans-CN)
    • Flutter version 0.11.13 at /Users/linwenlong/Documents/flutter
    • Framework revision 58c8489fcd (9 weeks ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/linwenlong/Library/Android/sdk
    • Android NDK at /Users/linwenlong/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/linwenlong/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616

[✓] Connected device (1 available)
    • LON AL00 • TEV0217A18000224 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.

I create a project: [](https://github.com/wilin52/FlutterInAndroid)
debug or profile mode is ok, but release not works.
the problem is:
values of window.physicalSize.width/height and window.devicePixelRatio are wrong.
see screenshot

**Comment by zoechi** [comment]
> see screenshot

did you want to add one?

**Comment by wilin52** [comment]
> > see screenshot
> 
> did you want to add one?

I added screenshot : https://github.com/wilin52/FlutterInAndroid/blob/master/screenshot/Screenshot_20190129-110744.jpg

**Comment by zoechi** [comment]
Does it update to the proper value in release if you rotate the screen?

**Comment by wilin52** [comment]
> Does it update to the proper value in release if you rotate the screen?

nope, it's still a wrong value.
width is 0, height is 0, and devicePixelRatio is 1.0

**Comment by zoechi** [comment]
Does it update if you replace `lib/main.dart` with 
```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ScreenSizeWidget(),
            Container(
              color: Colors.greenAccent,
              width: window.physicalSize.width / (4 * window.devicePixelRatio),
              height:
                  window.physicalSize.height / (4 * window.devicePixelRatio),
            )
          ],
        ),
      ),
    );
  }
}

class ScreenSizeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final mq = MediaQuery.of(context);
    print('window.physicalSize.width: ${window.physicalSize.width}\n'
        'window.physicalSize.height: ${window.physicalSize.height}\n'
        'window.devicePixelRatio: ${window.devicePixelRatio}');
    return Text(
      'window.physicalSize.width: ${window.physicalSize.width}\n'
          'window.physicalSize.height: ${window.physicalSize.height}\n'
          'window.devicePixelRatio: ${window.devicePixelRatio}',
    );
  }
}
```

**Comment by wilin52** [comment]
> Does it update if you replace `lib/main.dart` with
> 
> ```dart
> import 'dart:ui';
> 
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key key, this.title}) : super(key: key);
> 
>   final String title;
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text(widget.title),
>       ),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             ScreenSizeWidget(),
>             Container(
>               color: Colors.greenAccent,
>               width: window.physicalSize.width / (4 * window.devicePixelRatio),
>               height:
>                   window.physicalSize.height / (4 * window.devicePixelRatio),
>             )
>           ],
>         ),
>       ),
>     );
>   }
> }
> 
> class ScreenSizeWidget extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     final mq = MediaQuery.of(context);
>     print('window.physicalSize.width: ${window.physicalSize.width}\n'
>         'window.physicalSize.height: ${window.physicalSize.height}\n'
>         'window.devicePixelRatio: ${window.devicePixelRatio}');
>     return Text(
>       'window.physicalSize.width: ${window.physicalSize.width}\n'
>           'window.physicalSize.height: ${window.physicalSize.height}\n'
>           'window.devicePixelRatio: ${window.devicePixelRatio}',
>     );
>   }
> }
> ```

Thanks. It works.  😊😊
