### ISSUE TITLE
Sort cannot be disabled on DataTable

### ISSUE THREAD

**Issue by fhuonder** [flutter/flutter#26845]
According to the documentation, setting `onSort` to null on a `DataColumn` disables sorting for this column.
The implementation has a bug there:
`onSort` is passed with `onSort: () => column.onSort(...)` to the `_buildHeadingCell` method. Within `_buildHeadingCell` it is checked for null but it never can be.
So clicking a headinig cell leads to a "The method 'call' was called on null." error.

Am I missing something or is this a bug?

**Comment by willlarche** [comment]
Thanks for doing so much work to identify the problem! Would you be willing to put in a pull request with your solution?

**Comment by andermoran** [comment]
> Thanks for doing so much work to identify the problem! Would you be willing to put in a pull request with your solution?

Done!

**Comment by TahaTesser** [comment]
Hi @andermoran @fhuonder 
Do you think this issue still valid?
If not, i can close the issue
thank you

**Comment by andermoran** [comment]
@TahaTesser im not sure. I didn’t think this would ever get fixed so I gave up on it.

**Comment by andermoran** [comment]
I haven’t used flutter in a few months. I’m not sure if they have fixed this bug.

**Comment by darshankawar** [comment]
Hi @fhuonder,
Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master) ?
Thanks.

**Comment by fhuonder** [comment]
Hi @darshankawar 

I am sorry, I cannot verify that at the moment.

**Comment by pedromassangocode** [comment]
Closing this because https://github.com/flutter/flutter/pull/51667 has landed and it fixes this issue.

Please feel free to comment and I will reopen it if neccessary.
