### ISSUE TITLE
Adding shape for bottom sheet

### ISSUE THREAD

**Issue by Karthick-Ramanathan** [flutter/flutter#26854]
Could't able to add shape to bottom sheet, bottom sheet background takes canvas color. Unable to set transparent color.

![screenshot_2019-01-21-19-01-26-815_com vishwak vpflite](https://user-images.githubusercontent.com/30870272/51478013-2c86eb80-1db0-11e9-8a21-48a41a94637c.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by Karthick-Ramanathan** [comment]
> Please add the output of `flutter doctor -v`.
> 
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

As this
```
ThemeData _appTheme() {
    final ThemeData base = ThemeData.light();
    return base.copyWith(
      canvasColor: Colors.blue,
    );
  }
}
```

canvas color is used to set background color for bottom navigation bar and bottom sheet, unable to set transparent background color for bottom sheet. Code file is attached

[bottom sheet.txt](https://github.com/flutter/flutter/files/2781421/bottom.sheet.txt)

my flutter doctor

E:\Project\flutter_sample>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] VS Code (version 1.28.2)
[√] Connected device (1 available)

• No issues found!

**Comment by zoechi** [comment]
> To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into lib/main.dart of a new project and run to reproduce.

A complete runnable example please where copy-paste into `lib/main.dart` results in a runnable app that allows to reproduce.

**Comment by Karthick-Ramanathan** [comment]
> > To investigate we would need a minimal runnable reproduction
> > as a single file so that we can just copy your code into lib/main.dart of a new project and run to reproduce.
> 
> A complete runnable example please where copy-paste into `lib/main.dart` results in a runnable app that allows to reproduce.

This is my main.dart file. It is a complete file with main method

[main.txt](https://github.com/flutter/flutter/files/2782781/main.txt)

**Comment by monisnap-julien** [comment]
Adding a transparency parameter and modifying the theme accordingly inside the "showModalBottomSheet" function can do the trick i think, like in this example : 

```dart
Future<T> showModalBottomSheet<T>({
  @required BuildContext context,
  @required WidgetBuilder builder,
  bool isTransparent,
}) {
  assert(context != null);
  assert(builder != null);
  assert(debugCheckHasMaterialLocalizations(context));
  return Navigator.push(
      context,
      _ModalBottomSheetRoute<T>(
        builder: builder,
        theme: isTransparent
            ? Theme.of(context, shadowThemeOnly: true)
            : Theme.of(context, shadowThemeOnly: true)
                .copyWith(canvasColor: Colors.transparent),
        barrierLabel:
            MaterialLocalizations.of(context).modalBarrierDismissLabel,
      ));
}
```

Do you think it can be implemented ?

Thanks in advance !
