### ISSUE TITLE
[google_maps_flutter] Support marker clustering

### ISSUE THREAD

**Issue by m7amdElberawy** [flutter/flutter#26863]
*Edited by amirh:*

This is a request to  support marker clustering similarly to https://developers.google.com/maps/documentation/android-sdk/utility/marker-clustering

**Comment by zoechi** [comment]
Is this about https://pub.dartlang.org/packages/google_maps_flutter 
Please provide more information.

**Comment by m7amdElberawy** [comment]
Yes this about google maps flutter plugin.
There is any option for displaying images from the internet inside marker as shown in the image below.
![online images](https://user-images.githubusercontent.com/15971429/51504534-33caeb00-1dea-11e9-876f-266ccbeeaf1e.jpg).
And Google Maps Marker Clustering for putting a large number of markers on a map without making the map hard to read as shown in the image below.
![marker cluster](https://user-images.githubusercontent.com/15971429/51504685-eb5ffd00-1dea-11e9-8646-f1549657680a.png)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by aytunch** [comment]
Is any progress being made in this issue? Thanks

**Comment by Gavmcdonald** [comment]
I think the marker cluster feature would be a fantastic addition

**Comment by zoechi** [comment]
@Gavmcdonald 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by amirh** [comment]
Marker clustering, and loading marker images from the network are separate issues.
The later is tracked in: https://github.com/flutter/flutter/issues/28140

Lets use this issue to only track marker clustering (I'm editing this issue to reflect that)

**Comment by lpongetti** [comment]
+1

**Comment by XinyueZ** [comment]
+1

**Comment by lpongetti** [comment]
I've done this plugin for flutter_map.
https://github.com/lpongetti/flutter_map_marker_cluster

Its not google maps but works very well

**Comment by alfonsocejudo** [comment]
Hey gang, I needed clustering for my Flutter app with Google Maps as well, so until the feature gets built-in support, perhaps see if you can get by with this: [https://pub.dev/packages/fluster](https://pub.dev/packages/fluster)

Cheers

**Comment by biklas7** [comment]
> Hey gang, I needed clustering for my Flutter app with Google Maps as well, so until the feature gets built-in support, perhaps see if you can get by with this: https://pub.dev/packages/fluster
> 
> Cheers

@alfonsocejudo can you provide an example of that package working with google maps plugin in flutter?

**Comment by joserocha3** [comment]
@biklas7 there is a demo repo at https://github.com/alfonsocejudo/fluster_demo

**Comment by kroikie** [comment]
@m7amdElberawy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/497. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Reopening this issue here, it was marked closed (in error) due to Firebase label.

**Comment by lapadev** [comment]
Any news? This is something very important.

**Comment by BqvXHXoVN6cu** [comment]
Looking to port native apps to flutter and need this functionality.

**Comment by biklas7** [comment]
Hi everyone :wave: Until we have official support for marker clustering, this might be useful to some of you: https://github.com/coletiv/flutter_google_maps_clusters. Hope it helps :smile:

**Comment by danielrf121** [comment]
@biklas7 

Hello, this solution will work with the recently made **Markers** change? We are no longer using markers.add. The marker structure is being **Map <MarkerId, Marker> markers = <MarkerId, Marker> {};** and **markers: Set <Marker> .of (markers.values)**.

Using google_maps_flutter 0.5.21+15

**Comment by biklas7** [comment]
> @biklas7
> 
> Hello, this solution will work with the recently made **Markers** change? We are no longer using markers.add. The marker structure is being **Map <MarkerId, Marker> markers = <MarkerId, Marker> {};** and **markers: Set .of (markers.values)**.
> 
> Using google_maps_flutter 0.5.21+15

You can convert a list of markers to a set. That's what I'm doing, but you check the example and refactor the code to always use a Set or a Map.

**Comment by charleshan** [comment]
Thanks for sharing @biklas7. Is there any reason why you decided to roll out your own solution instead of using [clustering_google_maps](https://github.com/giandifra/clustering_google_maps)?

**Comment by biklas7** [comment]
@charleshan I tried to use that, but when I did it felt pretty rough and didn't solve my problem. But, maybe the package is better now. I don't know. I don't have a specific reason to be honest with you :smile:  I recommend that you try both solutions and see what's better for your use case :rocket:

**Comment by cyanglaz** [comment]
After looking into the `google-maps-utils` repo, I want to experiment to have a separate flutter plugin to handle all the features in the `google-maps-utils`. I will set up the new plugin and add some minimum code. After that, we can work together to add these new features.

**Comment by Marek00Malik** [comment]
What is the progress on this issue? I will go with the workaround plugin flutter_google_maps_clusters or fluster. But it would be nice to make use of the officinal tools.

**Comment by mubasshir** [comment]
any update on it? Its quite basic utility to have while adding markers

**Comment by cyanglaz** [comment]
Un-assign myself from this issue as I don't have cycles to actively working on it.

**Comment by FacuRossi** [comment]
any update on it??

**Comment by mrhmamun** [comment]
any update???

**Comment by cyanglaz** [comment]
@FacuRossi @mrhmamun We (the flutter plugin team) don't expect to actively work on this for the current quarter. I will make sure to update this thread as soon as possible when this feature is in our priority. 

A PR has opened to add this feature https://github.com/flutter/plugins/pull/1480. One way to accelerate the process could be to help reviewing the PR. :)

**Comment by Walid8581** [comment]
I wanna assign different colors to markers for different user's location points stored in firebase, I actually fetched all the location points based on Device_id, and want to show on map in a way that people can distinguish between users based on marker's color. can you guide me on how to do that? thanks

**Comment by alexeynobody** [comment]
Any news? This is very important.

**Comment by maheshmnj** [comment]
any update on this flutter team?

**Comment by tieorange** [comment]
Any news guys? We thinking about porting a native production app to Flutter.
And the only thing that blocks us - OFFICIAL google maps flutter cluster library.

Guys, please keep upvoting the issue above. It's very important!

**Comment by SuMitVayuz** [comment]
When are we getting this features, any update??

**Comment by BrutalCoding** [comment]
> I wanna assign different colors to markers for different user's location points stored in firebase, I actually fetched all the location points based on Device_id, and want to show on map in a way that people can distinguish between users based on marker's color. can you guide me on how to do that? thanks

Don't quote me on this but I believe it is possible to draw custom markers (painting it), or else static images would work too but then you need to generate (a lot?) of images for each different colour you want.

Converting a widget to an image (bitmapdescriptor) seems a bit tricky to me, but it is certainly doable. This article might help you: https://infinum.com/the-capsized-eight/creating-custom-markers-on-google-maps-in-flutter-apps

**Comment by TeemuSo** [comment]
This is great, Flutter is really missing this one.

**Comment by VadimZhuk0v** [comment]
This is 'must have' feature. It's disappointing

**Comment by idohertyr** [comment]
Then make it.

**Comment by ksu-lovetravelling** [comment]
For everyone who is looking for a solution https://pub.dev/packages/google_maps_cluster_manager this might help.

**Comment by a1tem** [comment]
For everyone who is looking for a solution https://pub.dev/packages/google_maps_cluster_manager this might help.

**Comment by biklas7** [comment]
We've implemented clusters on one of our projects and published an article about it. If you're interested you can check it [here](https://coletiv.com/blog/how-to-cluster-markers-on-google-maps-using-flutter/).

It was done using the [Fluster package](https://pub.dev/packages/fluster).

**Comment by maheshmnj** [comment]
> For everyone who is looking for a solution https://pub.dev/packages/google_maps_cluster_manager this might help.

Yes This does work fine

**Comment by zs-dima** [comment]
all current clustering libraries have no any clustering animations at all
Clustering quite critical functionality - hope it appear very soon
![masc](https://user-images.githubusercontent.com/25195453/116998676-40d42580-ace7-11eb-903f-bbd5f58b2679.gif)

**Comment by dayron9110** [comment]
News?

**Comment by dayron9110** [comment]
Any update?

**Comment by hiteshgarg002** [comment]
It's been a long time, will this feature be ever added?

**Comment by vasilevzhivko** [comment]
I guess this feature won't be implemented any time soon?

**Comment by cedvdb** [comment]
> I guess this feature won't be implemented any time soon?

Looks like it. On the flip side there the libraries are already written in js and mobile platforms. So it's just a matter of someone creating the plugin to do the plumbing. 

We are currently using the cluster_manager but it has its quirks.  It would be nice if google libraries were supported by google employees though, or if they could contract people to do exactly that. For this reason we are reconsidering mapbox but it has the same problem of not officially supporting flutter yet..

**Comment by a7mad911** [comment]
any updates?

**Comment by troy379** [comment]
such a trivial feature isn't implemented for 3.5 years since the issue has been created.

another ticket that proves how google developers "care" about their solutions and community in general.

**Comment by mufaddalhamidofficial** [comment]
Any updates on this?

**Comment by MatijaNovosel** [comment]
> Any updates on this?

Nope. You'll either have to write your own implementation or use one of the two related packages that haven't been updated for years.

**Comment by ShvetsovZE** [comment]
@joellurcook 🤞  you would be able to get this pr across!

**Comment by mikejones3** [comment]
Fingers crossed this gets implemented as a Christmas Present for all of us!

**Comment by bifrostyyy** [comment]
If anyone wants to take this on, a PR was made in November 2022 (https://github.com/flutter/plugins/pull/6752). Unfortunately, it was not merged/approved before migrating from `flutter/plugins` to `flutter/packages`. I don't think the original author has re-introduced the PR to `flutter/packages`. So if someone else wanted to submit it, it should be ready to review/approval.

**Comment by Zazo032** [comment]
> If anyone wants to take this on, a PR was made in November 2022 ([flutter/plugins#6752](https://github.com/flutter/plugins/pull/6752)). Unfortunately, it was not merged/approved before migrating from `flutter/plugins` to `flutter/packages`. I don't think the original author has re-introduced the PR to `flutter/packages`. So if someone else wanted to submit it, it should be ready to review/approval.

PR available here: https://github.com/flutter/packages/pull/4319

**Comment by RoarGronmo** [comment]
Could anyone add documentation with examples on how to use Clustering and ClusterManager in google_maps_flutter ?

**Comment by mattiagualtieri** [comment]
Hi @jokerttu, any updates on when this PR [4319](https://github.com/flutter/packages/pull/4319) will be merged?

**Comment by CristovoXDGM** [comment]
Any updates on that ? we currently need to use this in a project

**Comment by aelahmar** [comment]
Any update on this?

**Comment by cedvdb** [comment]
@aelahmar It is waiting for https://github.com/googlemaps/google-maps-ios-utils/issues/456 to be merged. Unfortunately the repository maintainer seems to have abandoned that repository.

**Comment by vincent-hoodoo** [comment]
At the time of this comment, this issue has 271 upvotes 👍 .

But the [blocking issue](https://github.com/googlemaps/google-maps-ios-utils/issues/456) only has 55. If everyone who cares about this feature could go to the issue https://github.com/googlemaps/google-maps-ios-utils/issues/456 and upvote it 👍, it could probably help prioritize it.

**Comment by esodot** [comment]
So it has been merged for Android and Web but iOS is still open due to the blocking utils issue? People are waiting years for this feature

**Comment by Rishyash** [comment]
So guys it is live now.
 
https://medium.com/@rishyash8/clustering-support-in-google-map-flutter-2024-d8b1c68e515b

Basic implementation as example code is not updated in google_map_flutter on pub.dev

**Comment by AlexMoumou** [comment]
Its nice that this is finally merged!!

Only issue i have is i dont see a way to create custom Cluster icons with this. Anyone know a way i could try other than using cluster packages?

**Comment by Rishyash** [comment]
> Its nice that this is finally merged!!
> 
> Only issue i have is i dont see a way to create custom Cluster icons with this. Anyone know a way i could try other than using cluster packages?

https://github.com/flutter/flutter/issues/153092

**Comment by wangela** [comment]
Marker clustering has been released for Android, iOS, and web in google_maps_flutter [v2.9.0](https://pub.dev/packages/google_maps_flutter/changelog#290). 🚀

**Comment by kaj777** [comment]
Nice release, needed a way to create custom cluster icon. Is that possible?
