### ISSUE TITLE
getting the correct version ^0.16.0 (whatever) is way to difficult for many of the packages

### ISSUE THREAD

**Issue by mudgesteve** [flutter/flutter#26869]
hello all

I am a newbie again (20 years experance programming, been away for the last 5 retired, and getting back into it)
1 of my biggest time comsumtions has been tracking down the correct version for these VERY USEFUL packages.

for example i have been trying to find the correct version of rxdart.dart (this time) i am old but i think 1.5 HOURS of googleing is enough.. (OUCH)

such a simple question and yet cant seem to find the one that will allow the flutter get command to work( as it is trying each WRONG version hangs my computer at flutter get is busy trying that version you just got from goolge. [then i reboot and try another]

please help this OLD man understand how to get simple answer NOT PAGES and PAGES to browse thru

THanks

**Comment by zoechi** [comment]
Here is the result page for `rxdart` https://pub.dartlang.org/packages/rxdart
At the top it shows the latest release version `0.20.0`. If there were a newer pre-release version it would look like `0.20.0 (0.21.0-dev)` or similar.
If you switch to the `Versions` tab, you get a list of all available versions (newer pre-release versions listed **after** released versions).

I don't think there is a way around diving into some topics and asking on support channels for directions. There are a lot of topics that should be easy to find but not all of them can be the first link on the home page.

http://flutter.io/support lists known Flutter community channels.

**Comment by mudgesteve** [comment]
I am sorry to be so unclear.

I have been trying to learn this stuff following dated video tutorials, as
a result (being very new to this) i am lost many times due to dated video
training.

I will try to learn faster

Thanks for your help
