### ISSUE TITLE
can not run iOS

### ISSUE THREAD

**Issue by icepy** [flutter/flutter#26878]
## Steps to Reproduce

1. open Xcode
2. Runing 
3. Xcode error message: line 3: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory

## Logs

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

## Other

![image](https://user-images.githubusercontent.com/3321837/51519707-bd1b0580-1e5c-11e9-9ed3-a697fb385d75.png)

my flutter env :  export PATH="$HOME/flutter/bin:$PATH"

![image](https://user-images.githubusercontent.com/3321837/51519856-12efad80-1e5d-11e9-8704-dfeca856843f.png)

**Comment by zoechi** [comment]
Looks like https://github.com/flutter/flutter/issues/8011#issuecomment-279555055

Try running `flutter run` from a terminal and then again try running from XCode

**Comment by icepy** [comment]
@zoechi thanks;
