### ISSUE TITLE
flutter analyze should use the same .analysis-options file as Atom

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2687]
cc @devoncarew, @pq

**Comment by Hixie** [comment]
...which I'm told is the _embedder.yaml file found in the sky_engine package.

(Where that package is depends on which engine we're using, e.g. consider how `--debug` affects this.)

The analyzer already knows exactly where sky_engine is so it should be easy to find.

**Comment by Hixie** [comment]
As a side-effect, this will enforce the new lints on dart:ui, which I'd previously forgotten to do.

**Comment by devoncarew** [comment]
We should be able to add a dev_dependency from flutter_tools to flutter; that will cause the analyzer to pick up the _embedder.yaml and its associated analysis config.

**Comment by abarth** [comment]
Should be possible after https://github.com/flutter/flutter/pull/2965

**Comment by abarth** [comment]
This is now done.
