### ISSUE TITLE
TextField cursor height cannot be changed

### ISSUE THREAD

**Issue by BumsuKimBding** [flutter/flutter#26870]
Hi,

I'm making a platform application with Flutter and it's going quite well until now. But since I wanted to make the cursor of Textfield taller(not thicker, I know 'cursorWidth' option already exists), I have no way to do this without any customization of original material class. Anybody has made this before? It would be very cool if anybody has an example/solution.

**Comment by justinmc** [comment]
As of now you're right, there is only a way to adjust the cursor width, not height.  I think this is a reasonable request though.  I'm gathering a list of improvements for TextField, so I'll add this.

**Comment by sgon00** [comment]
Currently, the cursor's height is smaller than the Text height and top aligned. Is this expected?

**Comment by justinmc** [comment]
@sgon00 I'm not sure, can you post a screenshot?  There are some issues that might be similar to what you're seeing.

https://github.com/flutter/flutter/issues/30771 (recently fixed)
https://github.com/flutter/flutter/issues/31661 (open)

**Comment by GaryQian** [comment]
Try dev or master channels, as we have recently landed a fix that centers the caret with the text.

**Comment by sgon00** [comment]
@justinmc @GaryQian Thanks a lot for the quick reply. My previous comment was based on "4 weeks ago" dev build. I just tried the latest dev build. The caret looks much better now. I am ok with the current behavior. Cheers. 😀👍

**Comment by elileinkram** [comment]
Has there been any progress towards solving this problem?

**Comment by justinmc** [comment]
No one has worked on a way to set the cursor height yet as far as I know.  PRs are welcome though if anyone wants to pick this up!

**Comment by eliwowlol123** [comment]
Okay no problemo!

**Comment by aneeshjose** [comment]
https://github.com/flutter/flutter/issues/24182#issuecomment-478869981
Hope this helps.

**Comment by patelkrunal78** [comment]
To adjust the width, you could wrap your TextField with a Container widget, like so:

new Container(
width: 100.0,
child: new TextField()
)

Find Full Code At [Here](https://icetutor.com/question/how-to-update-flutter-textfields-height-and-width)

**Comment by rahulsinghk** [comment]
and one more problem, cursor height decreases when using contentPadding in the input. plz provide a way to change the cursor height
