### ISSUE TITLE
 Difference in AppLifecycleState android / ios

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#26886]
Hi, I have an application that should display an authorization screen when I deploy an application. All is well until the moment comes when the user must select a file.

On iOS, there were no problems with this, since the file selection screen (gallery, documents) does not cause the application to be minimized (`applicationDidEnterBackground`).
With the help of which we determined whether the application was minimized completely, on the choice of files or elsewhere, therefore, when returning from the file selection screen on iOS, the authorization screen was not called.

On Android, everything is clear with android, it won't work, so this problem is solved there by its own file manager.

On Flutter, `AppLifecycleState` does not allow, to understand on iOS, what the application had minimized.

In the process of testing `AppLifecycleState`, I found out the following.

- Android  minimized the application, maximized the application.

1. minimized the application
```
AppLifecycleState.inactive
AppLifecycleState.paused
```

2. maximized the application.
```
AppLifecycleState.inactive
AppLifecycleState.resumed
```

- iOS minimized the application, maximized the application.

1. minimized the application
```
AppLifecycleState.inactive
AppLifecycleState.paused
```

2. maximized the application.

```
AppLifecycleState.inactive
AppLifecycleState.resumed
```

- Android open FileExplorer then minimized the application, maximized the application, close openFileExplorer

1. openFileExplorer
```
AppLifecycleState.inactive
AppLifecycleState.paused
```

2. minimized the application
```
no Reaction
```

3. maximized the application.
```
no Reaction
```

4. close openFileExplorer
```
AppLifecycleState.inactive
AppLifecycleState.resumed
```

- iOS open FileExplorer then minimized the application, maximized the application, close openFileExplorer

1. openFileExplorer
```
AppLifecycleState.inactive
AppLifecycleState.paused
```

2. minimized the application
```
AppLifecycleState.inactive
AppLifecycleState.paused
```

3. maximized the application.
```
AppLifecycleState.inactive
AppLifecycleState.resumed
```

4. close openFileExplorer
```
AppLifecycleState.inactive
AppLifecycleState.resumed
```

note that when we are in the gallery, life-cycle callbacks are different

`AppLifecycleState` android / iOS is different,
In iOS, it works differently and is more expanded in my opinion, what is missing in callbacks for Flutter

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.1.9 at /Users/alexfix/Flutter/flutter
    • Framework revision 1407091bfb (13 days ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alexfix/Library/Android/sdk
    • Android NDK at /Users/alexfix/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone XR                 • 0AB397AD-D503-4882-8849-B6F3229D2B23 • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/dart-ui/AppLifecycleState-class.html

points out that there are differences between iOS and Android for `inactive` and `suspending`.

> On Flutter, AppLifecycleState does not allow, to understand on iOS, what the application had minimized.

Is this the actual bug report/feature request?

**Comment by 1AlexFix1** [comment]
> https://docs.flutter.io/flutter/dart-ui/AppLifecycleState-class.html
> 
> points out that there are differences between iOS and Android for `inactive` and `suspending`.
> 
> > On Flutter, AppLifecycleState does not allow, to understand on iOS, what the application had minimized.
> 
> Is this the actual bug report/feature request?

suspending no work presently, 
a) it is rather a function request
b) for iOS, the life cycle works, as you can see, is not very clear, since onPause and onResume are called twice if we are on the gallery screen, how is it?

**Comment by zoechi** [comment]
> a) it is rather a function request

What exactly is the function request?

**Comment by 1AlexFix1** [comment]
> > а) это скорее запрос функции
> 
> Что именно является запросом функции? Можете ли вы попытаться прояснить это?

Add differences didEnterBackground and suspend for iOS, or I think it is enabled to suspend

**Comment by diegoveloper** [comment]
I found a difference using AppLifecycleState.resumed , on Android it doesn't work when the State is created, only works on iOS.

After the State is created , if you press home to leave the app and enter again, AppLifecycleState.resumed is working on both.

**Comment by xster** [comment]
I'm gonna dedup this into https://github.com/flutter/flutter/issues/21985
