### ISSUE TITLE
App crashes on https call when on release mode using Android 19

### ISSUE THREAD

**Issue by IsaNascimento** [flutter/flutter#26887]
## Steps to Reproduce
1. Create a release apk and install on Android 19 (KitKat, 4.4).
2. Make a https call.

https://gist.github.com/IsaNascimento/ee9ceb743748079c43a6900c05abb211

Problem only happens on release mode and on Android 19 device (not sure if it happens on older versions of android, but it works fine on newer versions)

## Logs

```
Analyzing https_test...                                          
No issues found! (ran in 64.1s)
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale pt-BR)
    • Flutter version 1.0.0 at /Users/isadora_maria/Downloads/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/isadora_maria/Library/Android/sdk
    • Android NDK at /Users/isadora_maria/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!

```

**Comment by zoechi** [comment]
The emulator you have connected says API 24

>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

Is there any error output in the console?

**Comment by IsaNascimento** [comment]
Hey, sorry, I have a Android 19 device that wasn't connected. But the console doesn't show any errors. The app just closes

**Comment by mraleph** [comment]
@IsaNascimento you would need to look through output from `adb logcat` to see if there are any errors associated with your application.

**Comment by IsaNascimento** [comment]
@mraleph going to do that now. What level should I use, verbose or error or warnings?

**Comment by mraleph** [comment]
@IsaNascimento verbose you will need to see all messages and search for identifier associated with your application.

**Comment by IsaNascimento** [comment]
@mraleph, link to the complete logcat on verbose: https://gist.github.com/IsaNascimento/01ce96759b457f2cc7430a71a674fc2b

I just opened the app and clicked to make a https call and it crashed. I believe the identifier for the application is: 6217-6232.

**Comment by jason-simmons** [comment]
Note that the device used in this log is a Motorola XT890 using an x86 processor with an ARM emulation library

**Comment by mraleph** [comment]
Can it be the same issue as https://github.com/flutter/flutter/issues/19390? 

@IsaNascimento mentions that application crashes when trying to issue https request - which probably involves openssl. 

Unfortunately the stack from the logcat is useless because it just contains libhoudini which handles the emulation.

**Comment by darshankawar** [comment]
Since I don't have Android KitKat device to retest this, although I created an emulator with api 19 (x86) and release mode isn't supported built for x86, I am unable to replicate this to check if issue persists or is resolved.
@IsaNascimento Is there a way for you to check if this is still an issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
