### ISSUE TITLE
Firestore runTransaction throws isolate errors!

### ISSUE THREAD

**Issue by PandaGeek1024** [flutter/flutter#26885]
Im trying to use transaction to get multiple `DocumentSnapshot` and update them afterward, but it just keeps reporting isolate related errors. Someone please help me with it. 

Please check the detail below, basically it works fine when you only try to get/update one `DocumentSnapshot`, but in the case of multiple `get`/`update` things gets nasty. I have already been stuck for multiple days. 

I have even encountered cases that when it reach `await transaction.get(itemReferences[i]); `, it jumps to `print("complete");` immediately and then come back to get another snapshot then update action, which throws error as well. To be honest, I did not expect transaction to be this hard to use.
 Please can someone take a look at it.

iOS simulator
```yml
cloud_firestore: ^0.8.2+3
```

```dart
Future<String> postOrder(List<DocumentReference> itemReferences) {
  final TransactionHandler updateTransaction = (Transaction transaction)async {
    List<DocumentSnapshot> fetchedDocs = [];
    for (int i = 0; i < itemReferences.length; i++) {
      DocumentSnapshot fetchedDoc = await transaction.get(itemReferences[i]);
      fetchedDocs.add(fetchedDoc);
    }
    for (int i = 0; i < fetchedDocs.length; i++) {
      await transaction.update(itemReferences[i], fetchedDocs[i].data);
    }
  };

  return Firestore.instance.runTransaction(updateTransaction).then((response){
    print("complete");
  });
}
```
Error ouput:
```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c5231bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010bac1735 objc_exception_throw + 48
	2   Runner                              0x00000001077b409e -[FSTTransaction lookupDocumentsForKeys:completion:] + 238
	3   Runner                              0x000000010767c5d7 -[FIRTransaction getDocument:completion:] + 951
	4   Runner                              0x000000010767cf3e -[FIRTransaction getDocument:error:] + 414
	5   Runner                              0x00000001078c6c9b __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.458 + 347
	6   libdispatch.dylib                   0x000000010dce94e1 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010dcea54b _dispatch_client_callout + 8
	8   libdisp<…>
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"440","method":"resume","params":{"isolateId":"isolates/408554185"}}
Failed to send request: {"jsonrpc":"2.0","id":"441","method":"getStack","params":{"isolateId":"isolates/408554185"}}
```

btw, just caught the error output of the rare case where it jumps to print("complete") immediately
```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001126351bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000111bd3735 objc_exception_throw + 48
	2   Runner                              0x000000010d8c84ff -[FSTTransaction ensureCommitNotCalled] + 111
	3   Runner                              0x000000010d8c5fef -[FSTTransaction lookupDocumentsForKeys:completion:] + 63
	4   Runner                              0x000000010d78e5d7 -[FIRTransaction getDocument:completion:] + 951
	5   Runner                              0x000000010d78ef3e -[FIRTransaction getDocument:error:] + 414
	6   Runner                              0x000000010d9d8c9b __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.458 + 347
	7   libdispatch.dylib                   0x0000000113ede4e1 _dispatch_call_bloc<…>
Lost connection to device.
```

**Comment by zoechi** [comment]
#18923 looks a bit similar

**Comment by gagaJay** [comment]
> #18923 looks a bit similar

thasks for your quick reply zoechi. I have actually checked that thread already but unfortunately it did not help. I have got the await in front of all transaction calls but still fail to the above errors.

**Comment by gagaJay** [comment]
New find, It looks like when the first transaction.get() is finished, Before it reach to next get(), the second try jump in to rerun the code while the execution is still ongoing. I have no idea how this happened.

**Comment by benji-bou** [comment]
It seems I have the same problem, @gagaJay were you able to solve the problem somehow?

**Comment by gagaJay** [comment]
unfortunately no, I decided to use Google function to take care of it. Not sure if 0.9.0+2 has fixed it, but that version is also buggy.

**Comment by pookzzz** [comment]
I had the same problem for some time where my app will fatally crash whenever I try to run a transaction.

I initiated my app with in main.dart as such:
`final FirebaseApp app =
      await FirebaseApp.configure(options: _options(), name: 'testauth');
final Firestore firestore = Firestore(app: app);
  await firestore.settings(timestampsInSnapshotsEnabled: true);
`
after authentication I direct to homescreen.dart, which was using new Firestore.instance... completely unrelated to the one in main. 

I traced my problem from an error that says `Caused by: java.lang.IllegalArgumentException: Provided document reference is from a different Firestore instance.` 

 So I removed the lines
**final Firestore firestore = Firestore(app: app);
  await firestore.settings(timestampsInSnapshotsEnabled: true);,** 
and finally got the transaction to run as expected. I think the idea is to not have multiple instances happening at the same time.

Hope this is of help.

**Comment by PandaGeek1024** [comment]
@pookzzz thanks for your info. In my case, I only got the below line in my code
`await firestore.settings(timestampsInSnapshotsEnabled: true);`
Haven't tried to remove it since it will pops up another timestamp related warning.

Would you mind to share your firestore version with me?

**Comment by kroikie** [comment]
@PandaGeek1024

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/495. Any further collaboration will be done there.
