### ISSUE TITLE
CupertinoActionSheet Layout issues iPhone X

### ISSUE THREAD

**Issue by eikebartels** [flutter/flutter#26888]
## Steps to Reproduce

1. Use a iPhone X device 
2. install App 

## Issue 

Flutter apps running on iPhone X having strange layout issues within the CupertinoActionSheet

Issues I noticed: 
- CupertinoActionSheet looks totally different. The CupertinoActionSheetAction having half transparent backgrounds. 

## Doctor 

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.2 18C54, locale en-DE)
    • Flutter version 1.1.9 at /Users/eikebartels/Applications/flutter
    • Framework revision 1407091bfb (13 days ago), 2019-01-08 20:40:19 -0800
    • Engine revision e5ec3cf3ea
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/eikebartels/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

iOS 12 | iOS 12.1.3
------------ | -------------
![img_7178](https://user-images.githubusercontent.com/767979/51530163-a5328a00-1e3a-11e9-9e66-2479dfcc1e45.PNG) | ![simulator screen shot - iphone x - 2019-01-22 at 11 46 47](https://user-images.githubusercontent.com/767979/51530521-6cdf7b80-1e3b-11e9-9631-fcaf1cf01d08.png)

**Comment by zoechi** [comment]
> latest beta 12.1.3

beta `12.1.3` of what?

Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by eikebartels** [comment]
@zoechi issue and name is updated. Ill create a reproducible snipped

**Comment by eikebartels** [comment]
Sample Code to reproduce it. 

Fonts used: SourceSansPro & Roboto

Snippet: https://gist.github.com/eikebartels/0b7db59d4f41e05fd030ab23f0e445e4

iPhone X iOS 12.1 | iPhone X iOS 12.1.3 Beta | iPhone X 12.1 Simulator  
------------ | ------------- | -------------
![iphone_x_beta](https://user-images.githubusercontent.com/767979/51544171-98745d00-1e5f-11e9-8a7d-10fa4eecd9e8.png)|![iphone_x_normal](https://user-images.githubusercontent.com/767979/51544185-a0cc9800-1e5f-11e9-84de-46d04b9cc1dc.png)|![iphone_x_simulator](https://user-images.githubusercontent.com/767979/51544202-a7f3a600-1e5f-11e9-975c-ea6411e5f27c.png)

**Comment by eikebartels** [comment]
Hey @zoechi I updated this issue. The text scaling works fine. The only issue what is still persist, is the transparent background from the `CupertinoActionSheetAction`. This happens only on real devices and not on the simulator

**Comment by eikebartels** [comment]
This issue also exist on some Android devices

 1 | 2  | 3
------------ | ------------- | -------------
![img_7507](https://user-images.githubusercontent.com/767979/52397766-fb4c3200-2ab6-11e9-8c23-3831ab71cb96.JPG)|![img_7502](https://user-images.githubusercontent.com/767979/52397740-e079bd80-2ab6-11e9-845d-025b06d11971.JPG)|![img_7508](https://user-images.githubusercontent.com/767979/52397744-e66f9e80-2ab6-11e9-88be-d7fb178b7418.JPG)

**Comment by zoechi** [comment]
Can you still reproduce with latest master?

**Comment by zoechi** [comment]
Looks a bit like #20784

**Comment by Xgamefactory** [comment]
same here 

![IMG_27E68956B9E8-1](https://user-images.githubusercontent.com/22529051/73654132-5a319080-46a4-11ea-8a37-2f853a50ba55.jpeg)

**Comment by darshankawar** [comment]
Although I don't have iPhoneX device, I tried it on iPhone 11 simulator, iphone 6s device and iphone SE simulator on which the `CupertinoActionSheet` is displayed properly, but unable to confirm the issue on specific device using latest Flutter version.

@eikebartels Is there a way for you to check if you still encounter this issue using latest Flutter version on same device ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
