### ISSUE TITLE
Plugin Documentation Update Required

### ISSUE THREAD

**Issue by agreensh** [flutter/flutter#26892]
I've written a Flutter plugin in Swift, but it needs to access some objective-c code. I don't understand how to add a bridging header file to access the class defined in the objective-c in my Swift code.
The plugin documentation doesn't explain how to do this.

**Comment by agreensh** [comment]
@kaiyuanw Yes, I've read that thanks. I have successfully created several plugins, but because of this issue (http://www.openradar.me/45397675) I am trying to do a workaround, which has to be written in Objective-C (because the enum is - incorrectly - not available in Swift 4.2). Now, I know how to create a bridging-header file in XCode, and have successfully worked around the problem there in a nativer iOS application, but in my Swift plugin I don't know how to call Objective-C code. I know this is a "false" example (because I'm trying to fix an error in the latest version of Swift), but I'm sure many people already do this (call Objective-C code from within a Swift plugin), or need to do this, and I think it would be useful to have it documented.

**Comment by shinayser** [comment]
I am interested on this issue. I am trying to develop a VLC plugin using Swift, but the MobileVLCKit library is written in Object-C.
There is any way to do this or at the moment this is impossible? Please any help would be welcome!

**Comment by shyandsy** [comment]
so any solution for this?

**Comment by zmasinelli** [comment]
Any solution?

**Comment by soleverlee** [comment]
Any solution?

**Comment by SieC** [comment]
Any solution for this?

**Comment by xuzhengquan** [comment]
Any solution for this?

**Comment by cswxzx** [comment]
Any solution for this?

**Comment by dokinkon** [comment]
Any solution?

**Comment by alvinthen** [comment]
Is there any update on this? Specifically, how to refer to an Objective C framework from Swift if we can’t have a bridging header?

My use case is I’m trying to wrap a third party framework written in Objective C as a Flutter plugin in Swift. Now that I can import in MyPlugin.h, but I don’t understand how to access the classes from Swift.

More details in SO https://stackoverflow.com/q/64766362/410487

**Comment by stuartmorgan** [comment]
Per the answer to the linked SO question above, a module map is the documented way to do this:
https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift#3024316

We could potentially link to that from [the plugin docs](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm)

**Comment by stuartmorgan** [comment]
Since we've been setting plugins to use module builds but default in the template for several years, which essentially eliminates this issue, I don't think adding docs is necessary at this point.
