### ISSUE TITLE
iOS project doesn't build after doing a "pod init" and "pod install"

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#26890]
_First I would like to say that I am not a iOS Developer, I am just following the docs and some tutorials._

I just created a new project. After going into the "iOS" folder and performing a "pod init" and "pod install", the project shows me those erros:

![image](https://user-images.githubusercontent.com/1146982/51538886-90a1c200-1e39-11e9-8137-c8dcda4ff1f2.png)

If I change the iOS project build system to the "Legacy build system" the error changes to:
![image](https://user-images.githubusercontent.com/1146982/51538933-aadba000-1e39-11e9-8e66-a8efb7c1cf75.png)

I keep doing **pod install** but nothing changes.

This is the PodFile generated by the pod commands:
```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment]
Try running `flutter run` once.

**Comment by shinayser** [comment]
I just did it, still getting the same error.

**Comment by kangwang1988** [comment]
@shinayser 
Can you paste the result for `flutter -v run -v`?
It seems that `PODS_ROOT`  is missing.
```
diff "${PODS_ROOT}/../Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
if [ $? != 0 ] ; then
    # print error to STDERR
    echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." >&2
    exit 1
fi
```
Besides, `cd to flutter-project/ios` and run `pod install` directly.
If `pod install` run successfully, flutter-project/ios/Podfile.lock and flutter-project/ios/Pods/Manifest.lock should exist and be exactly the same.

You can also upload the demo flutter project you are using so that I can have a look at it.

**Comment by shinayser** [comment]
I've run the pod install command directly inside the iOS folder. This is the project I am trying to run:
https://drive.google.com/file/d/1Fck6j7f73t4FzISPQxNe1ks2c2-uzEzn/view?usp=sharing
It is just a standard project created by the `flutter create` command, I've not edited a single line of code.

This is the ending of the output:


```
               === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
           
               Check dependencies
               The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3
@objc
               Inference" build setting to "Default" for the "Runner" target.
               The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3
@objc
               Inference" build setting to "Default" for the "Runner" target.
           
               Remove stale build products
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/AppFrameworkInfo.plist
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/Debug.xcconfig
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/flutter_assets
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/Base.lproj/Main.storyboardc
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/Frameworks/App.framework
                   /bin/rm -rf /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Products/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework
           
               PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-30E93508FB01D6F61577CE6F.sh
                   cd /Users/danieloliveira/Documents/flutter_projects/masqfdp/ios
                   /bin/sh -c /Users/danieloliveira/Library/Developer/Xcode/DerivedData/Runner-cpbdjwebgpwhkyfvmczvlpnsvxom/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Script-30E93508FB01D6F61577CE6F.sh
               diff: /Podfile.lock: No such file or directory
               diff: /Manifest.lock: No such file or directory
               error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
           
           
[  +11 ms] Could not build the precompiled application for the device.
[   +8 ms] Error launching application on iPhone de Gabriel.
[  +10 ms] "flutter run" took 14,579ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:404:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#20     Future._complete (dart:async/future_impl.dart:476:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by kangwang1988** [comment]
<img width="1143" alt="screen shot 2019-01-24 at 12 20 28 am" src="https://user-images.githubusercontent.com/817851/51620832-2fc7d600-1f6e-11e9-90c8-4809d18a9850.png">
<img width="1143" alt="screen shot 2019-01-24 at 12 20 50 am" src="https://user-images.githubusercontent.com/817851/51620834-2fc7d600-1f6e-11e9-8e37-f6068b16e0e6.png">
<img width="1139" alt="screen shot 2019-01-24 at 12 22 15 am" src="https://user-images.githubusercontent.com/817851/51620836-30606c80-1f6e-11e9-9ef4-14a4da6157c1.png">
@shinayser 
Your Debug/Release.xcconfig lacks of the pod-debug/release.xcconfig, henceforth, the PODS_PODFILE_DIR_PATH&PODS_ROOT definition is lost.
<img width="1144" alt="screen shot 2019-01-24 at 12 24 29 am" src="https://user-images.githubusercontent.com/817851/51620945-73224480-1f6e-11e9-9bfc-8c4f40e7428a.png">

**Comment by shinayser** [comment]
Ok, I just did the following:

* flutter channel master
* flutter upgrade
* flutter run

The result stills the same. There is someting else can I try ?

**Comment by zoechi** [comment]
@shinayser perhaps https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated (or just create a new project)

**Comment by shinayser** [comment]
I just deleted the iOS folder and regenerated it with `flutter create .`
After that, I went into the iOS folder and did it:

- pod init
- pod install

After that I changed the project bundle id to a different one and then did a `flutter run`

It still generating the xconfig without the Pods references...

**Comment by kangwang1988** [comment]
Reproduced this issue using your example.
@shinayser 
I will create a fix soon.

**Comment by zoechi** [comment]
As a workaround you could try instead of `pod init` 
to add `shared_preferences: ^0.4.3` to `dependencies:` in `pubspec.yaml` 
and run `flutter packages get`.

(You can then remove it again and run `flutter packages get` again.)

**Comment by shinayser** [comment]
Ok I could made the project run now.
Seems all this problem was caused by my "pod init" and "pod install" manually after the project creation and before anything else.

To fix this on my other project (wich I could not delete the iOS folder) I deleted the **Podfile.lock**, **Podfile** and the **Pods** folder.
Then I added **shared_preferences: ^0.4.3** to my pubspec.yaml and did a flutter run command.
I believe this forced the framework to generate all the Pod files automatically.

Pehaps a way to detect if the user did a manual "pod init" and add the missing files and instructions would solve the problem.

**Comment by kangwang1988** [comment]
Will keep this issue until a final fix is landed.

**Comment by kangwang1988** [comment]
@shinayser 
Another workaround is to add the Pods-Runner-Debug/Release.xcconfig into Debug/Release.xcconfig, as shown in my screenshot.

**Comment by shinayser** [comment]
@kangwang1988 
Are you sure about that? Have you see the Podfile? Its pretty different from the one generated by the framework Vs the one generated by me (using manual "pod install").

**Comment by kangwang1988** [comment]
@shinayser 
Try to add it into your Debug/Release.xcconfig and rerun it, I think your issue will disappear.

**Comment by kangwang1988** [comment]
@shinayser 
I believe this issue is resolved after: https://github.com/flutter/flutter/pull/26970 is landed.

**Comment by shinayser** [comment]
Nice work @kangwang1988 ! Thank you for your support on this.

**Comment by abhi143u11** [comment]
> * flutter channel master
> * flutter upgrade
> * flutter run

I was not receiving any notifications on My IOS 13.4 But once I followed above lines it worked like charm. I would recommend trying the above method my almost 1 week wasted in getting notifications.
