### ISSUE TITLE
License hash is not reliable

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#26899]
One can update the hash to skip our license check. Later when an unrelated change happens, the license check will then fail. It's misleading as we expect the test to always fail for the change responsible for the failure.

See https://github.com/flutter/flutter/issues/25679#issuecomment-449511685, https://github.com/flutter/flutter/issues/25679#issuecomment-449511988, and https://github.com/flutter/flutter/issues/26753

**Comment by liyuqian** [comment]
CC @goderbauer @rmistry

**Comment by goderbauer** [comment]
The hash was added so we wouldn't have to run the entire script all the time, which is kinda slow. Maybe we should always re-generate the license in the post-submit run ignoring hashes to ensure that nobody is gaming the system?

**Comment by Hixie** [comment]
We definitely shouldn't have scripts that ignore errors from the license script. I agree that the license script should fail hard if it fails at all, it certainly shouldn't update the goldens if it had any bugs.

My bigger concern is that it's possible these scripts are also not updating the actual LICENSE file? If the golden files change, then it's often the case that we have to regenerate the LICENSE file too.

**Comment by rmistry** [comment]
The Skia roller uses this code: https://skia.googlesource.com/buildbot/+/master/autoroll/go/repo_manager/pre_upload_steps.go#88
It appears to be working correctly.

What does the Dart roller use? I suspect it is not updating sky_engine/LICENSE when license_third_party changes? (Eg: https://github.com/flutter/engine/pull/7286/files)

**Comment by goderbauer** [comment]
@bkonyi, who I believe may be able to answer the question about the Dart roller.

**Comment by bkonyi** [comment]
The Dart roller runs `licenses.sh` and then copies all the files (except for the Skia licenses, which shouldn't update as part of a Dart SDK roll) from $ENGINE_SRC/out/licenses_golden/ to $ENGINE_SRC/flutter/ci/licenses_golden/. I've never had to update sky_engine/LICENSE before. Is this not something the license script handles?

**Comment by bkonyi** [comment]
> > The sky/packages/sky_engine/LICENSE file is included in product releases and **should be updated any time the golden file changes in a way that involves changes to anything other than the FILE lines**. To update this file, run:
> 
> (from https://github.com/flutter/engine/blob/master/tools/licenses/README.md)
> 
> Probably a good idea to update the dart roller to re-generate that file as well. Commads are in the link above.

Thanks for the reference. The Dart autoroller should perform that step now if I did everything correctly. Will know in the next hour or so.

**Comment by Hixie** [comment]
I closed this since it's not really actionable in its current state. Please don't hesitate to file a new bug if there's a more concrete thing we can do.
