### ISSUE TITLE
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding

### ISSUE THREAD

**Issue by AndroidEngineerChenXiaoshuang** [flutter/flutter#26893]
Hello, I have been reporting such an anomaly:
![image](https://user-images.githubusercontent.com/22950417/51549096-ac8e7d80-1ea4-11e9-996e-6561101baf53.png)

This is AppDelegate:
```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    IOSTextViewPlugin.registerWith(pluginRegistrar: registrar(forPlugin: "IOSTextViewPlugin"))
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

This is IOSTextViewPlugin:
```
import Flutter

class IOSTextViewPlugin{
    
    public static func registerWith(pluginRegistrar: FlutterPluginRegistrar){
        let factory = IOSTextViewPlatformTextViewFactory.init(messenger: pluginRegistrar.messenger())
        pluginRegistrar.register(factory, withId: "IOSTextViewPlugin")
    }
}
```

This is IOSTextViewPlatformTextViewFactory:
```swift
import Flutter

class IOSTextViewPlatformTextViewFactory:NSObject,FlutterPlatformViewFactory{
    
    private let messenger: FlutterBinaryMessenger
    
    init(messenger: FlutterBinaryMessenger){
        self.messenger = messenger
    }
    
    func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
        return IOSTextView.init(messenger: messenger, frame: frame, viewId: viewId, args: args)
    }
}
```

This is IOSTextView:
```swift
import Flutter

class IOSTextView :NSObject,FlutterPlatformView{
    
    private let frame: CGRect
    private let viewId: Int64
    private let messenger: FlutterBinaryMessenger
    private var uiLabel: UILabel
    
    init(messenger: FlutterBinaryMessenger,frame: CGRect, viewId: Int64, args: Any?){
        self.messenger = messenger
        self.frame = frame
        self.viewId = viewId
        
        uiLabel = UILabel.init(frame: frame)
        uiLabel.text = "UILabel"
    }
    
    func view() -> UIView {
        return uiLabel
    }
    
}
```

This is Dart:
```dart
class BaiduMapAppState extends State<BaiduMapApp> {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      title: "Platform View Test",
      home: Scaffold(
        appBar: AppBar(
          title: Text('Platform View Test'),
        ),
        body: Center(
            child: SizedBox(
                width: 100,
                height: 100,
                child: defaultTargetPlatform == TargetPlatform.android
                    ? AndroidView(
                  viewType: 'AndroidTextViewPlugin',
                  creationParams: {"content": "通过参数传入的文本内容"},
                  creationParamsCodec: const StandardMessageCodec(),
                  onPlatformViewCreated: onMyViewCreated,
                )
                    : UiKitView(viewType: 'IOSTextViewPlugin',)
            )),
      ),
    );
  }
```
This is Info.plist:
![image](https://user-images.githubusercontent.com/22950417/51549226-f4ada000-1ea4-11e9-8f42-111ee6bc5fce.png)

It’s normal on Android!
I am using the simulator!

**Comment by AndroidEngineerChenXiaoshuang** [comment]
Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/chenshuang/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chenshuang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/chenshuang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] Connected device (2 available)
    • ONEPLUS A5010 • c738aafb                             • android-arm64 •
      Android 8.1.0 (API 27)
    • iPhone XR     • B71D8D5A-DA38-46DC-8AD7-82089D51C356 • ios           • iOS
      12.1 (simulator)

! Doctor found issues in 2 categories.

**Comment by AndroidEngineerChenXiaoshuang** [comment]
I have posted this project on my github, the project name is called IOSTextView.

**Comment by zoechi** [comment]
Also asked on #24434 

Did you try the suggestion from https://github.com/flutter/flutter/issues/24434#issuecomment-456440296

> Hi, check the README file for instructions on how to enable the developers preview(and the implications of doing so).
I'd suggest trying StackOverflow for support questions.

**Comment by AndroidEngineerChenXiaoshuang** [comment]
I wrote it completely in accordance with the logic of [this article](https://medium.com/@phoomparin/how-to-use-native-uis-in-flutter-with-swift-platform-view-8b4dc7f833d8), but there is still a problem, I also added io.flutter.embedded_views_previewvalue to the Info.plist file.

**Comment by ened** [comment]
The same problem was resolved for me after I added 

```
	<key>io.flutter.embedded_views_preview</key>
	<true/>
```

To my `Info.plist` file. Please double check on your end and close the issue if it's resolved.

**Comment by coretimes** [comment]
@ened thanks very much!!!!!

**Comment by tri-nhan-nguyen** [comment]
> I wrote it completely in accordance with the logic of [this article](https://medium.com/@phoomparin/how-to-use-native-uis-in-flutter-with-swift-platform-view-8b4dc7f833d8), but there is still a problem, I also added io.flutter.embedded_views_previewvalue to the Info.plist file.

I have tried turning every thing off (All simulators and Android Studio) and it worked.

**Comment by melvinsalas** [comment]
Somebody found a fix? :(

**Comment by mmahkamov** [comment]
> ```
> <key>io.flutter.embedded_views_preview</key>
> <true/>
> ```

I added this to Info.plist, the platform views started working (using admob_flutter plugin) but the debug console is still bombarded with the message from the subject.

**Comment by chenshipeng** [comment]
`
<key>io.flutter.embedded_views_preview</key>
<true/>
`
i added this to Info.plist,but still do not work.

**Comment by alessandrochetta** [comment]
> i added this to Info.plist,but still do not work.

I had the same problem. I added that manually in Xcode by opening the ios project.

I suggest to hav the same keys of this project: https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/ios/Runner/Info.plist

**Comment by bdezso** [comment]
Same issue here

**Comment by bdezso** [comment]
I had exactly same problem.
I manually add key to info.plist but debug still flooding verbose message.

**Comment by hasen6** [comment]
I had the problem on another app with admob_flutter and the key added to info.plist solved it...but I have another app where if I add it to the plist it makes my app freeze. If I don't add it I get that error message over and over.

**Comment by sam0829** [comment]
@hasen6 Did you find anything for this? I am also facing this with admob_flutter plugin but with BannerAd. After adding the suggested key in info.plist, the app hangs. From the logs I think the page is internally re-creating it self continuously and that leads to the app getting stuck.

**Comment by hasen6** [comment]
@sam0829 I ended up using `firebase_admob` in the end. I don't think I was able to solve certain problems with `admob_flutter` so in the end gave up on it.

**Comment by sam0829** [comment]
@hasen6 That plugin doesn't support placing an ad in between Widgets like in `ScrollView` so unfortunately that's not an option for me. But my workaround is working fine for now at least.

**Comment by gaiousantonio0909** [comment]
> The same problem was resolved for me after I added
> 
> ```
> <key>io.flutter.embedded_views_preview</key>
> <true/>
> ```
> 
> To my `Info.plist` file. Please double check on your end and close the issue if it's resolved.

This works on me😁

**Comment by Foxtrail815** [comment]
`<key>io.flutter.embedded_views_preview</key><string>yes</string>`

Add the above line to **app/ios/info.plist** right under the LANGUAGE_DEVELOPMENT line.

**Comment by abdulllrashid** [comment]
add this line to your info.plist in Xcode
![Screenshot 2019-12-10 at 12 13 11 PM](https://user-images.githubusercontent.com/28691569/70502359-8d452100-1b46-11ea-83ec-7646f97bcb98.png)

worked for Embedding Youtube Videos

**Comment by syahrinseth** [comment]
> > The same problem was resolved for me after I added
> > ```
> > <key>io.flutter.embedded_views_preview</key>
> > <true/>
> > ```
> > 
> > 
> > To my `Info.plist` file. Please double check on your end and close the issue if it's resolved.
> 
> This works on me😁



> `<key>io.flutter.embedded_views_preview</key> <true/>`
> i added this to Info.plist,but still do not work.

I add that to my info.plist but still did not work for me. Later I stop and re-run the `flutter run` command, And it manages to solve my problem.

**Comment by Charuwaka** [comment]
> The same problem was resolved for me after I added
> 
> ```
> <key>io.flutter.embedded_views_preview</key>
> <true/>
> ```
> 
> To my `Info.plist` file. Please double check on your end and close the issue if it's resolved.

Charm !!!

**Comment by ajatsoft** [comment]
> The same problem was resolved for me after I added
> 
> ```
> <key>io.flutter.embedded_views_preview</key>
> <true/>
> ```
> 
> To my `Info.plist` file. Please double check on your end and close the issue if it's resolved.

solved my problem¡¡¡ thank you¡¡¡¡

**Comment by ened** [comment]
We are going to close this issue as it is configuration related. Please see the solution in https://github.com/flutter/flutter/issues/26893#issuecomment-474725615 and open a new ticket if you encounter issues in the future. Thank you.
