### ISSUE TITLE
setBackgroundFlutterView tried to overwrite an existing FlutterNativeView

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26897]
I run my Flutter app. It uses android_alarm_manager. I have Android set to close activities immediately.

I hit the Android "home" button. This is output to the console:

```
I/AlarmService(21236): setBackgroundFlutterView tried to overwrite an existing FlutterNativeView
W/System  (21236): A resource failed to call close. 
D/FlutterNativeView(21236): FlutterView.send called on a detached view, channel=plugins.flutter.io/android_alarm_manager_background
```

Weirdly, if I hit "w", it responds, but says no tree is mounted. If I hit "t" it dumps a single RenderView with size 0x0 and no child. This means that the binding somehow got initialized in the isolate that I'm hitting, but either `runApp` was never called, or somehow the tree got unmounted (not sure we even have code to do that). I don't understand how that is possible.

cc @bkonyi

**Comment by Hixie** [comment]
Ok well part of the problem seems to be that `_alarmManagerCallbackDispatcher (package:android_alarm_manager/android_alarm_manager.dart:25:25)` itself calls `WidgetsFlutterBinding.ensureInitialized`. Not sure why that's happening.

**Comment by Hixie** [comment]
This may be a dupe of https://github.com/flutter/flutter/issues/26073

**Comment by lohanidamodar** [comment]
@Hixie was this ever solved for you? I am having the similar issue when I press back button the app, that schedules notifications using android alarm manager?

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
