### ISSUE TITLE
worst_frame_build_time_millis regressed around flutter/flutter#25674 

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#26907]
flutter_gallery__transition_perf worst_frame_build_time_millis regressed from ~90ms to ~120ms around flutter/flutter#25674

**Comment by liyuqian** [comment]
@HansMuller: any suggestion how we should handle this regression? It may be possible that the worst frame is just more complex so we can just update the baseline.

**Comment by liyuqian** [comment]
Ping @HansMuller

**Comment by HansMuller** [comment]
I think we need to change the benchmark's baseline. The new Shrine demo is nothing like the old one.

**Comment by liyuqian** [comment]
Rebaselined.
