### ISSUE TITLE
Writing a pluginbased app.

### ISSUE THREAD

**Issue by HerrNiklasRaab** [flutter/flutter#26903]
Hello,

our current project is programming a chat app. The special thing is: The chat app should be extensible by third-party programmers. We would like to create something like a little marketplace where third-party developers can put their extensions for our chat app. Every user can then download these extensions and run it inside the chat app.

These extensions will come in the type of games mostly who can be played with a friend or with multiple friends in the chat window.

How do I set something like this up in Flutter? Or is this not possible?

Thanks,

Niklas

**Comment by kangwang1988** [comment]
Is it like a mini program (which is usually written by javascript). 
Developers can write their own mini program(conforming to your host app's api requirement )and upload it to your host app's appstore?\
@HerrNiklasRaab

**Comment by zoechi** [comment]
I think this is covered by #14330 
See especially this comment https://github.com/flutter/flutter/issues/14330#issuecomment-442274897
