### ISSUE TITLE
Flutter Have Not Persian Calendar & DatePicker Api

### ISSUE THREAD

**Issue by aliedp** [flutter/flutter#26919]
Hello Fluttery Developer Friends...

Please Give Us Official PersianCalendar Api in Dart Like C# PersianCalendar Dotnet Api

PersianCalendarWidget And PersianDatePickerWidget is Very Needed too !!!

This is very important for developers like me and Others

We Want Official Apis , Please

Please Develope Persian Parts Of FrameWork

Thank You !

**Comment by Kartik1607** [comment]
Looks like would be a nice package to have.

**Comment by navidshad** [comment]
over a 150 m people in all around the world need to use PersianCalendar.

**Comment by csells** [comment]
@aliedp is there some reason to make this an integrated part of Flutter or would a package suffice?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
