### ISSUE TITLE
firebase_storage event updates

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#26916]
are too infrequent.  using this:

```dart
final StorageReference _taskRef = FirebaseStorage.instance.ref().child(_fileName);

    final StorageUploadTask _task = _taskRef.putFile(
      attachment,
      metadata,
    );
```

and then listening to the stream:

```dart
StreamBuilder<StorageTaskEvent>(
  stream: _task.events,
  builder: (context, AsyncSnapshot<StorageTaskEvent> snapshot) {

    final StorageTaskSnapshot _data = snapshot.data.snapshot;
    print('progress = ${_data.bytesTransferred} / ${_data.totalByteCount}');
```

results in updates maybe once every M.  in repeated trials with a 3.2M file, i get roughly the same thing every time:
```
progress = 133 / 3178281
progress = 8325 / 3178281
progress = 1106053 / 3178281
progress = 1949829 / 3178281
progress = 3178281 / 3178281
```
i understand the need for large-ish chunk sizes, but gaps this large make it effectively impossible to render progress.

**Comment by zoechi** [comment]
The Flutter plugin only wraps the native API. If it doesn't provide more updates there is nothing the Flutter plugin can do. Have you checked if this is different on native?

**Comment by blaneyneil** [comment]
i can't find an entry in the docs for chunk updates and/or the frequency, and i've never used the native.  so i just don't know.  though another thread seems to think it's 256K.  regardless, if there's only an update once every M then it should probably be in the queue somewhere.  whether that's in the flutter port or not i can't say.

**Comment by kroikie** [comment]
@blaneyneil

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/493. Any further collaboration will be done there.
