### ISSUE TITLE
Extraneous blank lines in `flutter` output while there's a timer running

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26922]
When TERM is not `xterm`, and startProgress() is called, and then printStatus() is called, we print out extraneous blank lines.

I expect I broke this during my recent jaunts in this code.

**Comment by jason-simmons** [comment]
How is `spinnerIndent` intended to work in `AnsiSpinner`/`AnsiStatus`?

I'm seeing a lot of extra newlines when the slow warning is active because `_clear` (including the `_slowWarning` length) is being duplicated `spinnerIndent` times

**Comment by HansMuller** [comment]
I'm also seeing many "... taking an unexpectedly long time" messages. They don't seem to correlate with taking an unexpectedly long time. They do correlate with restarting when incremental compilation is needed.
