### ISSUE TITLE
flutter packages get pub get failed (5)

### ISSUE THREAD

**Issue by DylanZhuang** [flutter/flutter#26924]
```
D:\flutter\workspace\flutter_app>flutter packages get -v
[  +31 ms] executing: [D:\flutter\flutter_0.5.6\] git rev-parse --abbrev-ref --symbolic @{u}
[ +228 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/dev
[        ] executing: [D:\flutter\flutter_0.5.6\] git rev-parse --abbrev-ref HEAD
[ +205 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] executing: [D:\flutter\flutter_0.5.6\] git ls-remote --get-url origin
[ +208 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [D:\flutter\flutter_0.5.6\] git log -n 1 --pretty=format:%H
[ +220 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 1407091bfb5bb535630d4d596541817737da8412
[        ] executing: [D:\flutter\flutter_0.5.6\] git log -n 1 --pretty=format:%ar
[ +208 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 weeks ago
[   +1 ms] executing: [D:\flutter\flutter_0.5.6\] git describe --match v*.*.* --first-parent --long --tags
[ +254 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.1.9-0-g1407091bf
[ +643 ms] Running "flutter packages get" in flutter_app...
[   +2 ms] Using D:\flutter\flutter_0.5.6\.pub-cache for the pub cache.
[   +1 ms] executing: [D:\flutter\workspace\flutter_app\] D:\flutter\flutter_0.5.6\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose get
--no-precompile
[ +791 ms] Access is denied.
[  +52 ms] Running "flutter packages get" in flutter_app... (completed)
[   +9 ms] "flutter get" took 1,246ms.
pub get failed (5)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:82:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
Can you please post the output of `flutter packages -v pub get -v`

**Comment by zoechi** [comment]
Might be https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/how-to-fix-error-5-access-is-denied-in-windows-10/8a4069ea-4b0e-4517-9d7a-62c44b4d6e7d?page=1

**Comment by DylanZhuang** [comment]
> Can you please post the output of `flutter packages -v pub get -v`

D:\flutter\workspace\flutter_app>flutter packages -v pub get -v
[  +60 ms] [D:\flutter\flutter_0.5.6\] git rev-parse --abbrev-ref --symbolic @{u}
[ +250 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[        ] [D:\flutter\flutter_0.5.6\] git rev-parse --abbrev-ref HEAD
[ +247 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[        ] [D:\flutter\flutter_0.5.6\] git ls-remote --get-url origin
[ +248 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [D:\flutter\flutter_0.5.6\] git log -n 1 --pretty=format:%H
[ +254 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 472bbccf756e7954af2a81d2c8abc46d65a570af
[        ] [D:\flutter\flutter_0.5.6\] git log -n 1 --pretty=format:%ar
[ +168 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 7 months ago
[        ] [D:\flutter\flutter_0.5.6\] git describe --match v*.*.* --first-parent --long --tags
[ +270 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.6-0-g472bbccf7
[ +765 ms] Using D:\flutter\flutter_0.5.6\.pub-cache for the pub cache.
[   +2 ms] D:\flutter\flutter_0.5.6\bin\cache\dart-sdk\bin\pub.bat get -v
Access is denied.
[+1025 ms] "flutter pub" took 1,490ms.
pub finished with exit code 5

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:183)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:143)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#9      Future._propagateToListeners (dart:async/future_impl.dart:667)
#10     Future._complete (dart:async/future_impl.dart:472)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:33)
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#18     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

**Comment by zoechi** [comment]
Also doesn't provide more information. It seems to be an issue with permissions on your system.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
