### ISSUE TITLE
Implement material icon toggles

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#2693]
Icon and IconButton doesn't use colors from the current theme, it should probably read them from the primaryIconTheme property of the ThemeData. Also, by default the theme uses black and white colors while the material design spec says they should be gray.

**Comment by abarth** [comment]
Looks like this is what we do currently:

```
  Color _getDefaultColorForThemeBrightness(ThemeBrightness brightness) {
    switch (brightness) {
      case ThemeBrightness.dark:
        return Colors.white;
      case ThemeBrightness.light:
        return Colors.black;
    }
  }

  Color _getDefaultColor(BuildContext context) {
    return IconTheme.of(context)?.color ?? _getDefaultColorForThemeBrightness(Theme.of(context).brightness);
  }
```

Would we get rid of IconTheme or would we use Theme.of(context).primaryIconTheme as a fallback?

**Comment by Hixie** [comment]
@vlidholt Can you give an example where this doesn't work? I couldn't figure out what you mean. The code certainly tries pretty hard to honor the current theme (either specifically the current IconTheme, if any, or the current Theme, if not).

**Comment by Hixie** [comment]
@abarth Do you understand the issue here?

**Comment by abarth** [comment]
I think he's looking for toggle buttons.

**Comment by Hixie** [comment]
https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons

**Comment by abarth** [comment]
Icon toggles specifically.

**Comment by YeungKC** [comment]
ToggleButtons was added at #34599 and last updated at #70656.

I will close the issue.
