### ISSUE TITLE
"flutter packages get" error：pub get failed (69) 

### ISSUE THREAD

**Issue by AndrLin** [flutter/flutter#26935]
I have cloned a project：https://github.com/Sky24n/flutter_wanandroid
when I run `flutter packages get`:
```
Running "flutter packages get" in flutter_wanandroid...     
Git error. Command: git rev-list --max-count=1 HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
pub get failed (69) -- attempting retry 1 in 1 second...
Git error. Command: git rev-list --max-count=1 HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```

### **My environment**
I have update `~/.bash_profile`
```
export PUB_HOSTED_URL=https://pub.flutter-io.cn 
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Android Studio (version 2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.29.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

> git --version
git version 2.20.1
```
### **I did try the following：**
1. Switch branch from `beta` to `dev`
2. 
```
git clean -xfd
git pull
flutter doctor
```
3. delete local Flutter SDK  and extract it again.
4. 
Try `https://github.com/flutterchina/flukit.git` as `url` instead of `git://github.com/flutterchina/flukit.git`

Try `https://github.com/Sky24n/plugins.git` as `url` instead of `git://github.com/Sky24n/plugins.git`

They don't work.

How can I get more info about error, to determine where is wrong. I don't know `flutter packages get` will perform what specific operation.

`My other projects can work normally.`

**Comment by zoechi** [comment]
Please check
https://github.com/dart-lang/pub/issues/2015, https://github.com/flutter/flutter/issues/22470#issuecomment-428049724, https://github.com/flutter/flutter/issues/22470#issuecomment-431797533, https://github.com/flutter/flutter/issues/21565#issuecomment-419639851
or these similar issues https://github.com/flutter/flutter/issues?q=is%3Aissue+%22pub+get+failed+%2869%29%22+is%3Aclosed

**Comment by AndrLin** [comment]
I built a new project to test the third-party packages reference, discovery is ` flukit ` problem.Then Cloning it to local references，it success.

**Comment by maheshmnj** [comment]
if you are on Ubuntu

see if ```ifconfig```  works for me it was
```
Command 'ifconfig' not found, but can be installed with:
sudo apt install net-tools
```

so when I installed it everything worked perfectly
