### ISSUE TITLE
Ping command in flutter

### ISSUE THREAD

**Issue by VladimirLuzhin** [flutter/flutter#26939]
Hello. I wanted to know if there is an opportunity to execute the "ping" (like ping google.com) command from a mobile application written in flutter?

Thanks in advance for the answer!

**Comment by kangwang1988** [comment]
https://pub.dartlang.org/packages/dart_ping

**Comment by VladimirLuzhin** [comment]
I tried to use this package, but it does not work, because apparently uses the capabilities of the OS (Windows, Linux, etc.).

**Comment by zoechi** [comment]
I don't think you can do this in pure Dart. 
For Flutter you can build a plugin https://flutter.io/docs/development/packages-and-plugins/developing-packages#developing-plugin-packages
that calls code on native like https://stackoverflow.com/a/37868059/217408 (Android) and I assume something similar is available for iOS with Swift/Objective-C

**Comment by VladimirLuzhin** [comment]
@zoechi Thanks for your answer, I will try to do so.
