### ISSUE TITLE
retainFlutterNativeView should not clear FlutterJNI state

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#26931]
If `retainFlutterNativeView` returns true, then `FlutterActivityDelegate` should ensure that the `FlutterNativeView` remains active and can later be attached to another `FlutterView` instance.

However, currently `FlutterView.detach` results in a call to `FlutterJNI.detachFromNativeAndReleaseResources`, which drops the `nativePlatformViewId` within `FlutterJNI`.  After that the `FlutterNativeView` will fail when it calls a `FlutterJNI` API.

I think `detachFromNativeButKeepNativeResources` should be removed.  `nativeDetach` is a no-op, and in this scenario `FlutterJNI` should continue to use the `nativePlatformViewId`

@matthew-carroll

**Comment by matthew-carroll** [comment]
Is this the issue that @DaveShuckerow is investigating?

**Comment by DaveShuckerow** [comment]
Correct, @matthew-carroll

**Comment by voiddog** [comment]
The same problem I found when I upgraded to v1.1.8

**Comment by dguralnick** [comment]
We're doing another release and this bug is still happening. Going to edit our release branch manually again.

Can this fix be prioritized?

**Comment by AnhDTN** [comment]
Hello everybody. i'm have problem. i'm working with flugin flutter and when using result.success(data), i get error for first run like below, but second run it work success
Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 5
Disconnected from the target VM, address: 'localhost:8614', transport: 'socket'

**Comment by matthew-carroll** [comment]
Hi @AnhDTN would you mind filing a new issue, including your Flutter doctor output, and providing a minimal set of reproduction steps?

**Comment by huuang** [comment]
@AnhDTN 

I ran into the same problem, have you fixed it?
