### ISSUE TITLE
Flutter app spawns with two isolates, hot reload fails with Error 105: Isolate must be runnable

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#26953]
Moving this from https://github.com/Dart-Code/Dart-Code/issues/1365

I don't have a repro I can run locally (but trying to get one). The issue was reported some time ago by a user and then again to me this week. The user launches a Flutter app and receives "Isolate must be runnable" when trying to Hot Reload. It happens both in VS Code and from the command line.

I believe it's related to there being two isolates when the app starts up (I've only ever seen this in these logs). In VS Code we assume the first isolate is the one we want to use, but when Flutter hot reloads it seems to pick the other one (which has a `pauseEvent.kind` of `None` and is not runnable - it also has no `rootLib`).

The app is started **paused** so we can send breakpoints before resuming, so at this point I believe no user code has run. Here are responses for `getVM` and `getIsolate`.

https://gist.github.com/DanTup/25c9032fd7f1c6606b1d7c807d55cf54#file-vm-js
https://gist.github.com/DanTup/25c9032fd7f1c6606b1d7c807d55cf54#file-first_isolate-js
https://gist.github.com/DanTup/25c9032fd7f1c6606b1d7c807d55cf54#file-second_isolate-js

This only happens for a specific project so may be related to dependencies or plugins. Here's the deps:

![unnamed](https://user-images.githubusercontent.com/1078012/51607548-dda29880-1f0c-11e9-9a91-9b9477859198.png)

I don't think the user is on GitHub, but I'll post more info as I can get it (I'm trying to get a minimal repro that can be shared).

**Comment by zoechi** [comment]
Could be the same cause as #26842, #20743, #18600

**Comment by DanTup** [comment]
Yeah, this is the same error as #26842, though the alarm manager isn't in this project. I wonder if there's something similar in this project that's the cause. Hoping to get a small repro.

**Comment by zoechi** [comment]
I think the android_alarm_manger plugin also works with isolates.

**Comment by AlexKel** [comment]
I'm experiencing the same issue. Everything was fine previously and not quite sure what's changed before it stopped working. Tried pretty much everything now. Rolling back flutter, changing to master branch, etc..

Here is the error message I'm having:
```sh
Initializing hot reload...                                             ⣽Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: false, rootLibUri: file:///Users/aleksandrkelbas/Library/Developer/CoreSimulator/Devices/1DA3FEDA-995B-4872-B1EE-7C5169030DEE/data/Containers/Data/Application/114D81FC-E9BC-4828-9DBB-25991AEB7398/tmp/fastbook_flutterQT2pVw/fastbook_flutter/lib/main.dart.incremental.dill, packagesUri: file:///Users/aleksandrkelbas/Library/Developer/CoreSimulator/Devices/1DA3FEDA-995B-4872-B1EE-7C5169030DEE/data/Containers/Data/Application/114D81FC-E9BC-4828-9DBB-25991AEB7398/tmp/fastbook_flutterQT2pVw/fastbook_flutter/.packages, isolateId: isolates/964972142}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

And here is my dependency list:
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.3.0
  cloud_firestore: ^0.9.13+1
  cloud_functions: ^0.1.2+1
  intl: ^0.15.8
  flutter_emoji: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Comment by AlexKel** [comment]
Also, I'm attaching to an existing native project. Was working just fine before, but now flutter view isn't loading at all and trying to refresh produces this error.

**Comment by AlexKel** [comment]
I've actually just managed to fix it for my project.

Just some additional information about my circumstances for the issues:
1. I've had latest flutter version crashing on me. So, I've tried different ways to fix this by switching between branches and in the end settled for older version (on beta branch). I've used beta branch from the start.
2. I've run `flutter clean` as well before as someone suggested doing so. This didn't help and removed my `build` folder. This build folder didn't autogenerate (I'm using `flutter attach` as this is existing native project). 
3. This resulted in another issue where flutter was complainging that `app.dill` isn't found as there were no `build` folder anymore.
4. I've tried to re-create build folder by running `flutter build bundle`. Don't know what this exactly does, but seemed to re-create folder.
5. After this flutter was attaching but this seemed to result in this Isolate issue.

I also noticed that flutter itself works just fine in other projects, so it was definitely something wrong with this project only and not flutter itself.

### My fix
1. I've run `flutter clean` once again to get rid of the `build` folder.
2. I've now run `flutter run` which did a few things... created a build folder but then eventually failed as my project is only suppose to attach to another native one and missing native files in flutter folder.
3. As this created a build folder anyway, I've tried running `flutter attach` once again, run my project and omfg! It's now working just as before!

Hope this helps someone else. I've spent 2 days trying to resolve this.

**Comment by testing2007** [comment]
I had encounter this issue recently, there was two FlutterViewController in my project and call registerPlugin, By vscode IDE, when you open the debug tab, which shows two main.dart Running , when i delete each FlutterViewController one of them, this error didn't happen again, I don't know if you are same question.

**Comment by lucien-theron** [comment]
Our app constantly fails with this error when hot reloading.

**Comment by ened** [comment]
I believe we have a similar issue and it is shown in the AS logs as follows:

```
2 isolates are paused.
Reloaded 0 of 1651 libraries in 2,312ms.
```

This happens when spawning a separate isolate in a Android `Service`.

**Comment by shashikantshaale** [comment]
I'm facing the same issue in android.

**Comment by prgwar** [comment]
Any updates on the issue

**Comment by lucas-sesti** [comment]
got the same error in ios... any update?

**Comment by AllNamesAreTakn** [comment]
Any fix in the works for this yet?

**Comment by lucas-sesti** [comment]
When i change to flutter master, my errors stop, but in stable not works

**Comment by hazelf42** [comment]
Having this problem as well on flutter master.

**Comment by owenkealey** [comment]
Problem persists, only on Android for me though.

**Comment by AllNamesAreTakn** [comment]
With Flutter 1.17.1 and firebase_messaging 6.0.15 this no longer seems to occur.

**Comment by Omaryasirm** [comment]
> With Flutter 1.17.1 and firebase_messaging 6.0.15 this no longer seems to occur.

Thank you so much, wasted my whole day trying to figure this thing out.

**Comment by supratikkoley** [comment]
having same issue....any update?? i have also tried flutter v1.17.1,  but it didn;t work...

**Comment by firatcetiner** [comment]
> When i change to flutter master, my errors stop, but in stable not works
May I ask what specific version did you test? I'm already on 1.20.3 and this issue still raising. Since I'm using cloud_messaging and some other plugins that utilize background executions, I can't be sure which plugin is responsible for this behavior.

**Comment by AllNamesRTakn** [comment]
I'm only getting this error using flutter embedding v2. Not sure how much info there is on downgrading but basically remove the flutter embedding meta-data from your Manifest file. 
The MainActivity using FlutterActivity instead of FlutterEngine looks like this:

```
public class MainActivity extends FlutterActivity{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);   
    }
}
```

**Comment by KirillBorodin** [comment]
Fix the issue by changing `MainActivity.kt` from: 
`
import io.flutter.embedding.android.FlutterEngineConfigurator
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import android.os.Bundle
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(FlutterEngine(applicationContext))
    }
}
`

to: 
`
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity : FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
`

**Comment by mkustermann** [comment]
As part of https://github.com/dart-lang/sdk/issues/36097 we have fixed issues with hot-reload and isolates (e.g. https://github.com/dart-lang/sdk/issues/36648). That work should also have fixed `Isolate is not runnable` problems reported on helper isolates.

If this is still an issue for anyone **on master branch**, please file a new issue and CC me.
