### ISSUE TITLE
Should have TabBarView.builder() constructor

### ISSUE THREAD

**Issue by trinhtuanvu** [flutter/flutter#26957]
I want to have a `PageView` with a very large number of pages.

`TabBarView` should have `TabBarView.builder()` constructor (similar to `ListView.builder()`) which build its children on demand.

**Comment by zoechi** [comment]
How large is the number of pages appx in your case?

**Comment by trinhtuanvu** [comment]
Sorry! I can achieve it with PageView.builder().

**Comment by zoechi** [comment]
Was just about to post that :D

**Comment by oligazar** [comment]
Kind of same problem here. I have about 10 tabs. Each runs network request and precaches images in its initState. So I'd like to have ability to build them lazily, instead of doing all this work simultaneously.
PageView.builder() would work, if there was a way to connect it to TabBar.

**Comment by minanayernia** [comment]
I have this problem too...because number of tabs are not specified and i want to make them from a list so i need something like TabBarViewBuilder()...

**Comment by symplrr** [comment]
Similar Problem. Is there any update on this feature?

**Comment by lukaszciastko** [comment]
> Similar Problem. Is there any update on this feature?
> 
> Till then,
> I found this StackOverflow thread, that tries to solve the dynamic tab issue. It has a workaround for Tab Builder.
> 
> Here's the link: https://stackoverflow.com/questions/59753664/how-i-can-handle-nested-tabbar-with-dynamic-length-in-flutter
> 
> Hope it's helpful, Thanks!

I really don't like this solution, because it's recreating some logic that already exists in the framework. I think it's best to try and reuse what's in the framework already as this way we can minimise bugs but also stay up to date with any changes to the Flutter `TabBarView`.

The easiest way to approach this problem is to wrap each child in a `Builder` widget. That's it.
