### ISSUE TITLE
ListView.Builder not iteract with itemCount attributed value number times

### ISSUE THREAD

**Issue by augustocadini** [flutter/flutter#26955]
I'am implementing a list using `ListView.builder` to show some components' form and I've difficulties to do this. To test my code I'am just printing the index value to check if everything is correct, but the problem is that I set a value to `itemCount` attribute but the `itemBuilder` not interact the times number that I want. 

```dart
 Widget getBody(BuildContext context) {
    return Container(
      color: Color(0xFFF9F9F9),
      padding: EdgeInsets.all(8.0),
      child: Card(
        elevation: 2.0,
        child: Container(
          padding: EdgeInsets.all(12.0),
    
          // HERE
          child: ListView.builder(
              itemCount: 9,
              itemBuilder: (BuildContext context, int index) {
              print('Index: $index');
 
              // below I load my components...
              }),
          )
      ),
    );
}
```

And the output is:
```
flutter: Index: 0
flutter: Index: 1
flutter: Index: 2
flutter: Index: 3
flutter: Index: 4
flutter: Index: 5
```

But, according that I've attributed to `itemCount` it must up until Index: 8. I don't know what I doing wrong.

**Comment by zoechi** [comment]
Perhaps there is not enough space to show all items. `ListView.builder()` renders only what needs to be drawn on the screen.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
