### ISSUE TITLE
add HTTPS to Flutter's dart:io using native secure sockets

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2696]
Right now, to make HTTPS network connections you need to import package:flutter/http.dart and use the [http](https://pub.dartlang.org/packages/http) package API. There are a number of Dart packages (e.g. [usage](https://github.com/dart-lang/usage)) that use dart:io directly, and these packages will work only for insecure connections.

Including our own BoringSSL and root certificate store will bloat Flutter apps, so instead I think we should add HTTPS support to Flutter's dart:io by implementing dart:io's [SecureSocket interface](https://api.dartlang.org/1.14.2/dart-io/SecureSocket-class.html) using [Android SSLSocket](http://developer.android.com/reference/javax/net/ssl/SSLSocket.html) as the backing implementation on Android and NSStream with NSStreamSocketSecurityLevelNegotiatedSSL on iOS.

This will save us work porting third-party Dart packages, and avoid a situation where authors are connecting to insecure URLs for Flutter compatibility.

@abarth @johnmccutchan

**Comment by johnmccutchan** [comment]
I believe @zanderso is making progress on this front.

**Comment by zanderso** [comment]
I've got a CL under review here https://codereview.chromium.org/1721283002/ that uses the SecureTransport API on Mac, and implements the full dart:io secure sockets API. The API on iOS is a little narrower*, but should still work well for client-side apps. On Android, I was planning to keep BoringSSL (maybe not compiled in though? maybe dynamically linked using the libssl.so on the devices?), but use the root certs already on the device under /system/etc/security/cacerts instead of compiling them in.

* SecureTransport on iOS only supports PKCS12 certificates and doesn't support pulling fields (e.g. subject, issuer, begin and end validity, etc.) out of the certificate objects.

**Comment by abarth** [comment]
That plan on Android sounds reasonable.  The main thing we'd like to avoid is bloating the binary by statically linking lbssl and having to manage the root certificate store.

**Comment by collinjackson** [comment]
Thanks! This sounds like a good approach.

**Comment by eseidelGoogle** [comment]
FYI @yjbanov (who just was helping a customer to move their usage of package:streamy from dart:io over to package:flutter/http.dart to enable https in flutter).

**Comment by zanderso** [comment]
Status update:
* iOS: The change to switch Mac OS to SecureTransport landed last week: https://github.com/dart-lang/sdk/commit/e900b1b94417a4fe46467f80ee6fec118a779c5d. The change to switch iOS to SecureTransport is in progress here: https://codereview.chromium.org/1839123003/. The iOS API is mostly the same, but with a narrower API around adding and inspecting certificates. However making simple https requests using the built-in trusted certs is working.
* Android: As of https://github.com/dart-lang/sdk/commit/27f5c1f81cd0b8a30da5be821caa871bf5c18bd0 we no longer compile in the trusted certs, instead using the trusted certs on the device. Unfortunately, there are two problems with using the on-device libssl.so. First, it is not part of the NDK, meaning that to use it we'd have to DEPS in the Android openssl source repo to get the right headers, and then dlsym in all 60+ calls that we use. Second, the OpenSSL API version it implements is quite old, so we'd have to rewrite a bunch of our secure sockets code to match. Despite these problems, I've sketched out what it might look like here: https://codereview.chromium.org/1815143005/. I expect it would take a week or two more to put that into a working state, but I think we should consider a different approach, and switch to the on-device libssl.so when Android updates or adds to the NDK. I will get an exact number for how much our BoringSSL adds to an apk and report back.

**Comment by zanderso** [comment]
/cc @iposva-google

SkyShell.apk:
current: 7901 KB
w/ BoringSSL:  8177 KB

So, BoringSSL adds ~270KB or ~3.5%, on Android. I think we should go ahead and just statically link it in. Thoughts?

**Comment by abarth** [comment]
270KB is a lot of space to spend in the compressed binary.  Using the system libssl.so also means it's the OS's job to maintain/update the security of the SSL implementation.

**Comment by zanderso** [comment]
Sorry for taking so long to update this. dart:io secure sockets are currently enabled in Flutter on Android and iOS. The iOS implementation uses the native SecureTransport API. While continuing to investigate using Android's builtin libssl.so, the Android implementation uses BoringSSL.

**Comment by abarth** [comment]
This works now.
