### ISSUE TITLE
how does one change the border color of a checkbox

### ISSUE THREAD

**Issue by fritz-playmaker** [flutter/flutter#26961]

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by fritz-playmaker** [comment]
how do i join the flutter study group on slack then. Who do I contact?

**Comment by kendji** [comment]
Here it is.

Checkbox(value: false, tristate: false, onChanged: (_) {});
　　↓
Theme(
        data: ThemeData(unselectedWidgetColor: Colors,red),
        child: Checkbox(value: false, tristate: false, onChanged: (_) {}));

No onChanged, then the border will be grey(disabled).

**Comment by ThinkDigitalRepair** [comment]
Thanks for the above solution. It should be a parameter of the widget though.

**Comment by KingIdee** [comment]
How about customizing the border width?

**Comment by thanhbinh84** [comment]
I tried many ways, eventually wrap it in container. 
```
Container(
                              decoration: BoxDecoration(
                                  border: Border.all(
                                    color: Colors.white,
                                    width: 2
                                  ),
                                  borderRadius: BorderRadius.all(Radius.circular(5))
                              ),
                                width: 24,
                                height: 24,
                                child: Checkbox(
                                  value: _isChecked,
                                  tristate: false,
                                  onChanged: (bool isChecked) {
                                    setState(() {
                                      _isChecked = isChecked;
                                    });
                                  },
                                ),
                                ),
```

**Comment by iamsandeepsk** [comment]
Theme(
    data: ThemeData(unselectedWidgetColor: Colors.white),
    child:Checkbox(
                                  value: _isChecked,
                                  tristate: false,
                                  onChanged: (bool isChecked) {
                                    setState(() {
                                      _isChecked = isChecked;
                                    });
                                  },
                                ),

)

**Comment by Abhishek01039** [comment]
Hello @Hixie 
do we need to add an example of this?

**Comment by Hixie** [comment]
Adding examples of how to use Theme to change things like checkbox color seems useful, sure.

**Comment by Abhishek01039** [comment]
Where we should add it? @Hixie 

Here
<img width="937" alt="image" src="https://user-images.githubusercontent.com/56479665/107636645-f1a3c900-6c92-11eb-8381-a1b7f00691db.png">

**Comment by Hixie** [comment]
That seems like a good place to start.
