### ISSUE TITLE
Feature for Disabling Camera Shutter Sound 

### ISSUE THREAD

**Issue by xipengshen** [flutter/flutter#26960]
I don't see the feature in Camera plugin for disabling the picture taking sound (the shutter sound). In apps that use camera to continuously taking pictures, the shutter sound is very annoying. Can the feature be added?

**Comment by tigrenok00** [comment]
Any news?

**Comment by tuanha2000vn** [comment]
Taking picture every second for face detecting and the Shutter Sound kill it.

Please add option disable sound. Thank you.

**Comment by kentcb** [comment]
I can't see this ever being added because iOS simply doesn't support it - it _always_ plays the camera shutter sound and has no API to turn it off. The going workaround is to start a video stream and capture an image from that instead.

**Comment by tatashidayat** [comment]
Does it happen on iOS only?
Because I have tried on Android, it doesn't play the shutter sound.

**Comment by stefanodecillis** [comment]
Is there any news regarding this problem? Is there a way to fix it or a workaround?

**Comment by ElochukwuPrince** [comment]
How can I enable the shutter sound in android? Mine doesn't play any sound when taking pictures. Any solution?

**Comment by Nguyen-Thanh-Tung** [comment]
> Taking picture every second for face detecting and the Shutter Sound kill it.
> 
> Please add option disable sound. Thank you.

Do you have any idea? I'm facing this problem

**Comment by Nguyen-Thanh-Tung** [comment]
Using record video for replacing method. Set timer to stop recording. Then using export_video_frame plugin to get image

**Comment by Komal-Khairnar** [comment]
Any update on this?

**Comment by tp-coderbabu** [comment]
Any update? please!!

**Comment by ljmatan** [comment]
Don't quote me on Apple guidelines, but what you can do while taking a photo is play a blank sound, and the shutter sound will be off. Blank sound file: https://d1sz9tkli0lfjq.cloudfront.net/items/0Y3Z0A1j1H2r1c0z3n3t/blank.wav

**Comment by luomo-pro** [comment]
Is this making any progress?
I'm writing a 1 second snapshot application and the shutter sound is awful.
@ljmatan
I've tried using audio_plays to play this blank sound, but it doesn't seem to mask the camera shutter sound.
Is there anything else I can do?

**Comment by ljmatan** [comment]
@luomo-pro blank sound worked for me, if it doesn't work for you, I'd advise you use startImageStream method and go from there (please keep in mind it crashes the app after flutter v2.5.3 -> https://github.com/flutter/flutter/issues/94723)

**Comment by luomo-pro** [comment]
hi
@ljmatan
Thanks for your reply.
My application needs to use image data in jpg format, and there seems to be no way to convert image stream directly to normal image.
Do you know of a way to convert it?
Also what method are you using to play blank audio? Can you provide the code snippet?
I'm using the audioPlays package, but it doesn't seem to work, so I don't know if I'm playing at the wrong time.
Thank you very much!

**Comment by panksi** [comment]
> Don't quote me on Apple guidelines, but what you can do while taking a photo is play a blank sound, and the shutter sound will be off. Blank sound file: https://d1sz9tkli0lfjq.cloudfront.net/items/0Y3Z0A1j1H2r1c0z3n3t/blank.wav

Can you explain how you implemented this? I want to try it out! thanks

**Comment by stuartmorgan** [comment]
Closing, since this is not supported by the underlying SDK, and thus not something that can be implemented in the plugin wrapping it.
