### ISSUE TITLE
frontend_server should not match by file name for platform libraries

### ISSUE THREAD

**Issue by keertip** [flutter/flutter#26973]
Currently the frontend_server looks for a file named platform_strong.dill for the library. So if it does not find a file platform_strong.dill in the sdk directory, it does not compile. There should not be such a hard requirement when passing in the library files.

With Dart 2, there is only strong mode, but it appears that the frontend_server has support for legacy mode, which necessitates the need for matching by file name.

This should be cleaned up.

**Comment by zoechi** [comment]
I think this should be reported in dart-lang/sdk instead.

**Comment by darshankawar** [comment]
Hi @keertip 
Is this still a valid issue or can this be closed ?

**Comment by kf6gpe** [comment]
I believe this is still valid. Assigning a priority, though.

**Comment by aam** [comment]
I think this is obsolete now. Closing.
