### ISSUE TITLE
Flutter firebase-admob check if rewarded video is loading

### ISSUE THREAD

**Issue by Jhon2524** [flutter/flutter#26971]
Using flutter and this plugin (https://pub.dartlang.org/packages/firebase_admob),

**How can I check if the Rewarded video is load?** 

I received this Exception :

`PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)`

I can not find methods to check if the video is loaded.

Thank you.

**Comment by kleinpetr** [comment]
something news?

**Comment by kroikie** [comment]
@Jhon2524

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/492. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment]
Hi @Jhon2524
does this [solution ](https://github.com/FirebaseExtended/flutterfire/issues/1300#issuecomment-545422948)fix the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
