### ISSUE TITLE
Cutting, copying and pasting don't call onSelectionChanged

### ISSUE THREAD

**Issue by jslavitz** [flutter/flutter#26975]
As the title says, cutting, copying and pasting do not call the onSelectionChanged callback of the text field or editable_text like they ought to.

**Comment by Hixie** [comment]
Based on the labels I assume this is specifically only for the CupertinoTextField?

**Comment by TahaTesser** [comment]
Hi @jslavitz 
Are you still experiencing this issue?
if so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @jslavitz 
Looks like there is no `onSelectionChanged` in [CupertinoTextField](https://api.flutter.dev/flutter/cupertino/CupertinoTextField/CupertinoTextField.html) anymore

if you disagree please write in the comments and I will reopen it 
Thank you
