### ISSUE TITLE
Need a way to change cursor pointer colour for TextFields in InputDecoration/ThemeData

### ISSUE THREAD

**Issue by vemarav** [flutter/flutter#26979]
![cursor-pointer](https://user-images.githubusercontent.com/17309962/51629561-f1321b80-1f6d-11e9-8ee8-4e71e9bf0e2f.png)

**Comment by vemarav** [comment]
Thanks @zoechi. But I have already tried with `cursorColor: Colors.black` still the pointer color is blue.

> You can notice the cursor color in screenshot provided

**Comment by zoechi** [comment]
Now I get it. You want to change the color for the selection handle. 
The "cursor" is the blinking vertical bar.

**Comment by vemarav** [comment]
Thanks @zoechi. It's worked
