### ISSUE TITLE
"flutter run" sometimes fails when using android alarm manager (resolved by "flutter clean")

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26974]
For some reason, if I use Android Alarm Manager, then sometimes subsequent runs of "flutter run" hang after the "Installing" step, waiting for the observatory port. I sometimes see a flash of white on the device around the time it's trying to launch the app, then it goes back to the home screen. Maybe the app is already running because a timer fired or something, and we don't have a way to shut down the app fully?

Running "flutter clean" for some reason fixes it. Running "flutter run" many times in a row seems to work fine, I think it probably only fails if it's been a while since the last "flutter run" (which is why I suspect it has something to do with the timers firing in the first place).

cc @bkonyi

**Comment by bkonyi** [comment]
@Hixie, have you encountered this lately?

**Comment by jonahwilliams** [comment]
I suspect this is related to https://github.com/flutter/flutter/issues/16604

**Comment by bkonyi** [comment]
> I suspect this is related to #16604

You're probably right. I don't think this is alarm manager specific. Closing as a duplicate for now.
