### ISSUE TITLE
Flutter StreamBuilder Controls and Firestore 

### ISSUE THREAD

**Issue by ueabu** [flutter/flutter#26982]
I have a two-part question/ problem. After reading through Firestore pricing, it says that you are charged based on the number of documents you read and write and the operations you perform such as deleting and some other factors. With that being said, I am using a StreamBuilder that continually refreshes itself whenever the list is scrolled whether there is new data in the database or not. Right now, the builder is fetching from a collection with very little data but that collect can grow to be bigger. With that being said, my questions are:

1.  Each time the StreamBuilder refreshes itself to show new data, is it actually fetching all the documents again from the Firestore collection or is it only looking for changes and updating them? If it is fetching the documents again from Firestore, does Firestore consider this as downloading multiple documents each time it refreshes or does it count it only once and if there are updates to any new document fetched, those are counted separately?

2. If it fetches all the documents over and over again every 2 seconds or even less as in the current behavior, is there a way to limit this say to every 30 seconds or to when every a RefreshIndicator is used so as to avoid multiple unnecessary reads? I tried using a StreamController but the stream still refreshes every time the list is touched or every second.

**Comment by zoechi** [comment]
That depends on your code and your settings.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by ueabu** [comment]
I asked the question on the other support channels about one week ago but there have been no answers. Can you tell me the specific settings you are talking about?

**Comment by zoechi** [comment]
That's probably because it's difficult to understand. If you asked on StackOverflow please post the link

**Comment by ueabu** [comment]
This is the link. 
https://stackoverflow.com/questions/54323540/streambuilder-controls-and-firestore-pricing
