### ISSUE TITLE
You probably have to install the development version of the Python package    for your distribution.

### ISSUE THREAD

**Issue by conan51551** [flutter/flutter#26999]
When i run `brew install --HEAD libimobiledevice`.It call me 
`Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.`
I have delete my system Python,but i install a new python.What should i do

**Comment by kangwang1988** [comment]
@conan51551 
This is a brew related issue instead of flutter one. A better place to track it is under homebrew, e.g., https://github.com/Homebrew/homebrew-science/issues/6461 
Hope it might help.
