### ISSUE TITLE
Modal Bottom Sheet should be sorted after Menus in the Gallery Components

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2699]
Modal Bottom Sheet should be sorted _after_ Menus in the Components list.

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: a5887b6fb41c3a5e343c6132bb89cb1c10fafb95 (2 days ago)
Engine:    70b92500df0006a9756fb9302a431322456a38fd
```

**Comment by eseidelGoogle** [comment]
My understanding is @vlidholt is working on a re-design of the app, now that it has so much content it's hard to get around.  For this specific bug, it should be easy enough to either fix the manual sort order:
https://github.com/flutter/flutter/blob/master/examples/material_gallery/lib/gallery/home.dart#L103
Or teach GallerySection how to sort:
https://github.com/flutter/flutter/blob/master/examples/material_gallery/lib/gallery/section.dart

**Comment by abarth** [comment]
This is done now.
