### ISSUE TITLE
Unit test the starter app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#270]
Protecting against regressions, we can analyze _and_ unit test the starter app in our CI system.

**Comment by eseidelGoogle** [comment]
It appears the starter app is here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/init.dart

**Comment by abarth** [comment]
We now analyze the starter app on every commit.

**Comment by Hixie** [comment]
Is analyzing it sufficient? Or should we do more?

**Comment by abarth** [comment]
Seems sufficient for now.  It's caught a bunch of problems.
