### ISSUE TITLE
Blend mode `screen` doesn't work well on background color `white`.

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter#27000]
I tried to run this demo: https://gist.github.com/brianegan/3cecbfc5fa688b4de3c574ed82942c4e
(source: https://www.reddit.com/r/FlutterDev/comments/aiaxzw/how_do_i_create_this_animation_using_flutter/)

The result is the color looks almost transparent on white background screen.
I can make it shown on white background by change blend mode to modula. But the color doesn't look good as blend mode `screen`.

![modular](https://user-images.githubusercontent.com/6185205/51650763-12b9f400-1fbc-11e9-9d20-ba85a4145e2c.png)

My question: is there something wrong ? anyway to make blend mode `screen` works well on white background ?

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.0.0 at /Users/sondq/Software/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.5153.38

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by sergeyv** [comment]
This is how screen blend mode works - the formula is 1 - (1 - a) * (1 - b), which, in case of white, always results in white: 1 - (1 - 1)*(1 - b) = 1 - 0 * (1 - b) = 1 - 0 = 1 

https://en.wikipedia.org/wiki/Blend_modes#Screen

**Comment by kangwang1988** [comment]
@quangson91 
Can we close this issue based on comments by @sergeyv  above?

**Comment by quangson91** [comment]
@sergeyv , @kangwang1988 Thank all you for fast reply.
But in my understand:

<img width="382" alt="screen shot 2019-01-24 at 4 28 23 pm" src="https://user-images.githubusercontent.com/6185205/51668642-406f5f00-1ff5-11e9-8d74-145f2292324e.png">

when I set blend mode to `screen`. this should only affect to the custom widget / custom painter, right ?

![modular](https://user-images.githubusercontent.com/6185205/51668963-f9359e00-1ff5-11e9-9b50-cece67e9571d.png)


In my case I really want to display this one without black color in background.
If there is a way, please help me with a suggestion.

Otherwise, we can close this issue.

Thank you so much!

**Comment by quangson91** [comment]
I close this issue because it is my misunderstood.
We have to separate  layer for the custom canvas.
Brianegan already update the example:
https://gist.github.com/brianegan/3a6b16e5f39a6e69f730140760c697b4
