### ISSUE TITLE
how to draw a small image to filled a large container by canvas

### ISSUE THREAD

**Issue by hanxu317317** [flutter/flutter#27001]
i want to use a Image, size[100, 100] to filled Screen, 
it's my way:

```dart
canvas.save();
canvas.scale(screenWidth / image.width,  screenHeight / image.height);
canvas.drawImage(image, Offset(0, 0), new Paint());
canvas.restore();
```
are there  have better ways to do this?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
