### ISSUE TITLE
Persistent Bottom Sheet reopens, but probably shouldn't

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2700]
In the Gallery Components, the sample for the Persistent Bottom Sheet reopens the bottom sheet every time you tap the "Show" rectangle. In other words, the bottom sheet closes and then reopens. While not wrong, strictly speaking, a different behavior could be a better example of how such functionality should work in the wild.

Maybe remove the tappable rectangle and replace it with static text saying "The bottom sheet is visible", then change back to a tappable rect when the bottom sheet is closed?

### Steps to Reproduce
1. Open the Persistent Bottom Sheet component in the Gallery
1. Tap "Show the persistent bottom sheet."
1. Again tap "Show the persistent bottom sheet." Note that the bottom sheet closes and opens again.
1. Do number 3 again.
1. Do number 3 again.

### Flutter Version
```
Flutter from https://github.com/flutter/flutter.git (on master)
Framework: 229253f43e222de4dd91813779a1a9d4ff22e9f8 (2 days ago)
Engine:    787e69fc453787089140b3b031ada932d7dad38e
```

**Comment by Hixie** [comment]
Or use a button and disable it while the sheet is visible?
