### ISSUE TITLE
Combining testWidgets and rendering_tester.dart produces obscure errors

### ISSUE THREAD

**Issue by xster** [flutter/flutter#27002]
We should produce a clearer error. Otherwise, the `test` alphabetically following `testWidgets` that attempts to use things like `layout` or `pumpFrame` from `rendering_tester.dart` will produce obscure binding not initialized errors.

**Comment by Abhishek01039** [comment]
@pedromassangocode 
I think PR is landed to the repo
can you please close this?

**Comment by pedromassangocode** [comment]
I'm not really sure if that PR fixes this. @xster can you please confirm?
Thank you
