### ISSUE TITLE
Error connecting to the service protocol when running on physical iOS Device

### ISSUE THREAD

**Issue by robin7331** [flutter/flutter#27019]
Hey guys!

I am facing this consistent problem when I run my Flutter App on a real iOS Device.
Its connected via USB but the problem only occurs when the device is also within a wireless network. When I turn off wifi everything works just fine.

The app is successfully building and also installing on my iPhone. The only thing that does not work is hotreloading. But I assume that is what the websocket is for.

Here's the actual error in my IntelliJ Console: 
`info flutter.tools Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/ws`

I am not behind any proxy. At least not that I am aware of.
When I run `echo $HTTP_PROXY` I get an empty response. So no proxy defined?

`echo $NO_PROXY` returns `localhost,127.0.0.1,*.local`

Btw. I am using `zsh` and `iTerm` on my mac.

Any ideas?
Thanks!

## Flutter doctor

```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-DE)
    • Flutter version 1.0.0 at /usr/local/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/robin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.5153.38

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone • 94f4ad73a193a1d907c6da1ce01ce052221e347d • ios • iOS 12.1.2

• No issues found!
```

**Comment by zoechi** [comment]
Did you check the discussions in #14991 and #13747 ?

**Comment by robin7331** [comment]
Thank you @zoechi the second link had the needed clue to solve this problem.

It turned out to be an iTunes problem. 
When disabling `Sync with this iPhone over Wi-Fi` it suddenly works.

Here are my other settings in case someone else is running into a similar problem:

I do have `Connect via Network` **disabled**  in Xcode.
Also, `Personal Hotspot` is not active on my iPhone.


Here's the output of @DanTup `s [websocket testscript](https://gist.github.com/DanTup/47da0c085fcfdf00bdbce02cce229e7e):
```
HTTP_PROXY: null
NO_PROXY: localhost,127.0.0.1,*.local

Connecting to ws://echo.websocket.org
SEND: TEST STRING
RCV: TEST STRING

Connecting to wss://echo.websocket.org
SEND: TEST STRING
RCV: TEST STRING

Server listening at ::1:3457
Connecting to ws://localhost:3457
SEND: TEST STRING
RCV: TEST STRING

Server listening at 127.0.0.1:3458
Connecting to ws://127.0.0.1:3458
SEND: TEST STRING
RCV: TEST STRING

Completed!
```

**Comment by sc956156617** [comment]
restart my mac ,the issue is gone. i don't what happen

**Comment by alexxgarci** [comment]
@robin7331 If you have your iOS device paired to Xcode you have to go to `Windows -> Devices and Simulators` and uncheck `Connect via network`.
