### ISSUE TITLE
TextField has a lot of bugs when input chinese

### ISSUE THREAD

**Issue by jeckbjy** [flutter/flutter#27012]
## Steps to Reproduce

![flutter-bug](https://user-images.githubusercontent.com/1024038/51659866-d5b72700-1fe6-11e9-8634-38fbe365dd38.jpeg)

in ios(my phone6 ios12.0,)
1.  cannot input chinese in simulator,just can input english
2.  crash in flutter 1.0.0 channel beta
3. then i upgrade to flutter 1.1.9, channel dev,  it not crash but not show correct,
   i input '中国', but i get 'zzhzzhozzhonzzhong.....' like above image. and the cursor not at the last, the keyboard not auto hide.

in android:
1:cursor donot show correct,always back to head aftet input  or delete some chinese characters

## Logs

```
```

```
```

```
```

**Comment by kangwang1988** [comment]
@jeckbjy 
Please separate the problems you mentioned in this issue in several ones so that we can track/solve it better and have more concrete information.
Besides, `flutter doctor -v` and a demo project which can help to reproduce will be more helpful.

**Comment by jeckbjy** [comment]
thank you for your reply!
i maybe found the problem!
i add a TextEditingController to init value, and set onChange to listen value change, i remove onChange,  so all problem is  solved

**Comment by FrunkPiano** [comment]
try my flutter textfield plugin [custom_text_field](https://github.com/FrunkPiano/CustomTextField.git)
soleve the problem
