### ISSUE TITLE
Location Background Service 

### ISSUE THREAD

**Issue by tegarkurniawan** [flutter/flutter#27015]
I want to run tracking when the application exits or runs in the background service
I have read this tutorial and I am still confused,
is there a sample project?
https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124
or is there a plugin for this?
and most plugins don't support Android Oreo

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
