### ISSUE TITLE
i get this error when run flutter doctor

### ISSUE THREAD

**Issue by Mahmoud767** [flutter/flutter#27024]
Downloading windows-x64 tools...
Download failed.
URL:
https://storage.googleapis.com/flutter_infra/flutter/1c26bf8c4b55f4fa5f0d175768a1a0cc115c70b2/windows-x64/artifacts.zip
Error: 403 Forbidden

**Comment by zoechi** [comment]
Did it work before or is this the first install attempt?

**Comment by kangwang1988** [comment]
It seems a pure connection issue.
I can download it successfully.

**Comment by zoechi** [comment]
`403 Forbidden` is a bit weird but it might be a response from a proxy or similar, not from the storage.googleapis.com server itself

**Comment by Mahmoud767** [comment]
i use a proxy because im from a country where google is blocked

**Comment by zoechi** [comment]
Also asked on https://stackoverflow.com/questions/54343994/diffeculty-when-error-when-run-flutter-doctor

I'm closing in favor of the SO question.

**Comment by pooyanism** [comment]
> i use a proxy because im from a country where google is blocked

I have a same issue, and also i'm using proxy cause Google banned some feature from developer in my country! :| 

Anyway, I Can't download Web SDK from command line in Terminal, but i have try to download manually from: https://storage.googleapis.com/flutter_infra/flutter/2c956a31c0a3d350827aee6c56bb63337c5b4e6e/flutter-web-sdk-windows-x64.zip and it was possible!

The question is that, is there anyway to do "flutter build web" manually?!
