### ISSUE TITLE
Flutter run not handle key press when, you press any key at non-english layout.

### ISSUE THREAD

**Issue by akkolyasnikov** [flutter/flutter#27021]
Flutter run not handle key press when, you press any key at non-english layout.

## Steps to Reproduce

1. Use `flutter run` in command line
2. Press any key in non english keyboard layout
3. It stop to handle any key press

## Flutter doctor
```
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.14393], locale ru-RU)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\yona\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\yona\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • TIT L01 • 8PY9KA9661801046 • android-arm64 • Android 5.1 (API 22)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Please provide more information about how to reproduce.

- the output of `flutter doctor -v`
- the crash log
- a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce
- is it the on-screen keyboard or the computer keyboard with the emulator
- iOS or Android (or both)?

**Comment by akkolyasnikov** [comment]
1. Updated 
2. No crash messages
3. It happens in any project
4. It not about on device keyboard. I tell about press any non-english keys on PC in CLI mode. For example when i press key R in cyrillic layout it's just stop react for any other keys.
5. It's about PC keyboard in debug mode
6. On windows and Linux

**Comment by zoechi** [comment]
I can't reproduce with german keyboard layout and characters like `ÜÄ?`, but I haven't trie cyrillic.

**Comment by akkolyasnikov** [comment]
It seems like only cyriilic layout call this bug.

**Comment by zoeyfan** [comment]
Just stumbled upon on this bug, is this still repro'ing in latest 1.12?

**Comment by akkolyasnikov** [comment]
in latest 1.12 all works correct. Thank you.
