### ISSUE TITLE
Not sufficient ram

### ISSUE THREAD

**Issue by behradkhadem** [flutter/flutter#27022]
Hello again! My laptop has 8GB of DDR4 ram but turns around it's not sufficient for developing. I use VSCODE and Genymotion and they get along just fine but when I open some tabs in Firefox, everything crashes. I've searched the internet and found nothing that could solve this problem. Do you have any suggestions or ideas in mind? Is there a solution?

**Comment by kangwang1988** [comment]
@behradkhadem 
I suggest you to ask support this kind of support questions in one of the other channels listed at http://flutter.io/support .
Feel free to comment if you think it's flutter related.
