### ISSUE TITLE
Check failed: vm. Must be able to initialize the VM

### ISSUE THREAD

**Issue by caocaocao** [flutter/flutter#27028]
Add Flutter to existing app issue

```
Check failed: vm. Must be able to initialize the VM.
```
caused by `productFlavors`.

**Comment by kangwang1988** [comment]
@caocaocao 
Please provide more information to investigate.
For example:
`flutter doctor -v`
minimal project(or main.dart) which can reproduce this issue.
And your commands to build the app, please add the verbose flag.

**Comment by kangwang1988** [comment]
Duple of: https://github.com/flutter/flutter/issues/24641

**Comment by caocaocao** [comment]
flutter混合开发，新建了一个空的Android的工程，按照“Add Flutter to existing apps”步骤，debug模式是可以成功的。但是在现有项目中，debug模式一直失败。调试后发现因为现有工程添加了渠道，导致flutter_assets拷贝到build目录失败。不加渠道包时，flutter_assets可以正常拷贝到（app\build\intermediates\assets\debug）目录下；添加了渠道包时，目录变成了（app\build\intermediates\渠道名\assets\debug），flutter_assets没有拷贝到相应目录。

**Comment by kangwang1988** [comment]
@caocaocao 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by JaydenHoFly** [comment]
It's still a problem in android. Our project has used gradle's productFlavors attr. When we add flutter to our exist android project, "Must be able to initialize the VM" has occurred. Because there is no flutter_assets directory in apk's assets directory. The workaround is remove productFlavors attr. Hope it will be solve.

**Comment by kangwang1988** [comment]
> It's still a problem in android. Our project has used gradle's productFlavors attr. When we add flutter to our exist android project, "Must be able to initialize the VM" has occurred. Because there is no flutter_assets directory in apk's assets directory. The workaround is remove productFlavors attr. Hope it will be solve.

Can you create a minimal demo to help to reproduce this problem?

**Comment by kangwang1988** [comment]
> flutter混合开发，新建了一个空的Android的工程，按照“Add Flutter to existing apps”步骤，debug模式是可以成功的。但是在现有项目中，debug模式一直失败。调试后发现因为现有工程添加了渠道，导致flutter_assets拷贝到build目录失败。不加渠道包时，flutter_assets可以正常拷贝到（app\build\intermediates\assets\debug）目录下；添加了渠道包时，目录变成了（app\build\intermediates\渠道名\assets\debug），flutter_assets没有拷贝到相应目录。

Can you create a minimal demo to help to reproduce this problem?
@caocaocao

**Comment by caocaocao** [comment]
最小的工程也是，一样的，原因是在flutter.gradle。        
if (project.android.hasProperty("applicationVariants")) {
            project.android.applicationVariants.all addFlutterDeps
        } else {
            project.android.libraryVariants.all addFlutterDeps
        }

project.android.hasProperty("applicationVariants")总是false。

**Comment by kangwang1988** [comment]
Reopen this issue as I think the 'Must be able to initialize the VM' problem could be resulted from different reasons in Android, especially related to the `resource copy` procedure.

**Comment by caocaocao** [comment]
我的理解是app工程依赖lib，flutter.gradle执行的时候，app还没有编译，所以applicationVariants没有值

**Comment by kangwang1988** [comment]
@caocaocao 
I can't make further progress before a minimal concrete reproducible project is provided.

**Comment by caocaocao** [comment]
我给你发一个最小工程

**Comment by caocaocao** [comment]
@kangwang1988 最小工程邮件被判断为垃圾邮件了。

**Comment by kangwang1988** [comment]
@caocaocao 
Just create a github project and paste the reproduce procedure in README will also be fine.

**Comment by caocaocao** [comment]
我刚才试了下，是正常的，非常感谢！！！
另外第一个问题，我一直以为my_flutter是要放在MyApplication目录下的，英文不好，理解有误，我之前还一直以为是settings.gradle文档写错了。

**Comment by kangwang1988** [comment]
@caocaocao 
Glad to hear that. 
Thanks for your feedback. We may need to update the wiki to provide more concrete information.

**Comment by LinHuanTanLy** [comment]
@kangwang1988  thx
