### ISSUE TITLE
Cannot run flutter app on 10 inch tablet

### ISSUE THREAD

**Issue by THEJDEEP1** [flutter/flutter#27026]
I am getting this error
```
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
```

**Comment by zoechi** [comment]
Please post details about the tablet. The 10 inch size is the least relevant part.

**Comment by THEJDEEP1** [comment]
Hi, I can run my app successfully on 7 inch amazon fire tablet but when I use 10 inch amazon fire tablet I am getting this error
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

**Comment by jason-simmons** [comment]
This usually happens if the target platform of the APK does not match the architecture of the device.  For example, an APK containing a 64-bit ARM version of Flutter can not be installed on a 32-bit device.

Try explicitly specifying a `--target-platform` that matches the device.

**Comment by dariotrombello** [comment]
Try ´´´flutter build apk --target-platform=android-arm64´´´

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
