### ISSUE TITLE
Command to create plugin projects  doesn't generate Podfile for iOS

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#27035]
_First, I would like to say that I am not a iOS developer_.

I am trying to develop a VLC plugin for Flutter. For so, I need to add its pod (pod "MobileVlcKit") to a podfile. But when I create the project (via the command flutter create -t plugin flutter_vlc_kit), the iOS folder inside the project has no podfile.
![image](https://user-images.githubusercontent.com/1146982/51691182-760a4d00-1fe1-11e9-8fd9-6b1fc37c5e38.png)

I am digging the documentation but can't find a way to add pods to the plugin ios folder. 
Is something I am missing here or it is a problem with the generated folder?

**Comment by shinayser** [comment]
Thanks @wouterhardeman for the answer. I did this, but still cant "see" the library inside my swift class. I try to import it (import MobileVLCKit) but doens't compile.
There is anything else I should do here? There is any pod command I am missing, like the "pod install"?
(sorry this noob questions, I amnot an iOS dev...)

**Comment by wouterhardeman** [comment]
Try running `flutter build ios --no-codesign` in the example folder. That should resolve the dependency.

**Comment by shinayser** [comment]
@wouterhardeman I tried it for multiple times but the command hangs on the **"Compiling, linking and signing ..."** Any clue about that?

**Comment by shinayser** [comment]
Seems the problem of the pod importing was solved. Now the problem is other: communication between a swift plugin and a objective-c library.

**Comment by kangwang1988** [comment]
Related to: #26892

**Comment by reniclin** [comment]
@shinayser Can you share how do you solve the  

> hangs on the **"Compiling, linking and signing ..."** ?

 I have the same problem, too.

Thank you!

**Comment by shinayser** [comment]
> @shinayser Can you share how do you solve the
> 
> > hangs on the **"Compiling, linking and signing ..."** ?
> 
> I have the same problem, too.
> 
> Thank you!

My problem was with MobileVLCKit. It was hanging the compiling, but upgrading to Xcode 10 (beta) solves the problem for the VLC. I don't know if that is your issue.

**Comment by zoechi** [comment]
#9827 might be related

**Comment by reniclin** [comment]
> My problem was with MobileVLCKit. It was hanging the compiling, but upgrading to Xcode 10 (beta) solves the problem for the VLC. I don't know if that is your issue.

@shinayser Thank you! I upgrade my Xcode to 10.2 beta (10P99q) and the MobileVLCKit compile problem was solved.

**Comment by Hixie** [comment]
@shinayser Did your original problem get resolved? Can you document what was needed to deal with this?

**Comment by shinayser** [comment]
Sorry @Hixie, it has been so long that I completly forgot what I had to do to fix it. My bad =(

**Comment by jmagman** [comment]
Closing.
