### ISSUE TITLE
Need a scroll controller that when scroll to the top(or the bottom), the scroll view can't complete the drag event

### ISSUE THREAD

**Issue by layou1989** [flutter/flutter#27030]
I need a scroll controller that when scroll to the top(or the bottom), the scroll view can't complete the drag event

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction that demonstrates the problem

as a single file 
so that we can just copy your code into `lib/main.dart` of a new project 
and run to reproduce.

**Comment by SirLYC** [comment]
I may find the problem too...Just like in Android, you can use NestedScrollXXX to intercept a scroll event or consume scroll event that holder doesn’t consume ...But in flutter, the widget seems to hold all the scroll event until your fingers up.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by layou1989** [comment]
just like:

showModalBottomSheet(context: context, builder: (BuildContext context) {
      return new Scaffold(
        body: new Column(
          children: <Widget>[
            new Container(
              height: 40,
              width: MediaQuery.of(context).size.width,
              color: Colors.red,
            ),
            /*ListView.builder(
              itemCount: 20,
              itemBuilder: (context, i) {return new Text("this is $i");}
            ),*/
            new Flexible(
                child: ListView.builder(
                    itemCount: 20,
                    itemBuilder: (context, i) {return new Text("this is $i");}
                ),
            ),

            new Container(
              height: 40,
              width: MediaQuery.of(context).size.width,
              color: Colors.black,
            )
          ],
        ),
      );
    });

when the listview scroll to the top,when continue scroll up, i want the listview complete the scroll event and the modal bottom sheet can drag down

**Comment by zoechi** [comment]
@layou1989 thanks. Can you make it a complete example incl `main(){}` so that copy-past is enough to run and reproduce?

**Comment by patelkrunal78** [comment]
if you would like to immediately scroll to the bottom of the list on start (in the initState()), you can place the following code chunk from Collin’s solution before the first time you call setState().

This Can Help Chek It [Here ](https://icetutor.com/question/how-to-get-full-size-of-a-scrollcontroller)

**Comment by Piinks** [comment]
I am not sure I know what the issue is requesting. Do you want gesture handling to be disabled during scrolling events from a scroll controller? Can the IgnorePointer widget serve that purpose here?
