### ISSUE TITLE
Local_auth Has No Haptic Feedback on iOS

### ISSUE THREAD

**Issue by yekta** [flutter/flutter#27036]
local_auth has no haptic feedback on iOS, as far as I know, this is almost a default behavior on iOS. If this is not the case, can you at least add an option to add a haptic feedback to it (touch id and face id haptic feedback).

**Comment by TahaTesser** [comment]
Hi @yekta 
Are you still experiencing this issue with latest stable `Local_auth`?
Thank you

**Comment by stuartmorgan** [comment]
Closing as out of scope; the UX of authenticating is provided by the system, and anything additional behaviors would need to be provided by the plugin client.
