### ISSUE TITLE
didUpdateWidget can dirty previous siblings without triggering an assert

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#2704]
In setState, we check that (if we're building) we're building one of this nodes ancestors, but didUpdateConfig is called outside of the "rebuild" function, which means we think we're currently building the parent.  That means siblings (particularly previous siblings) can pass the check in setState and they won't be cleaned during this build phase.

**Comment by pedromassangocode** [comment]
Does this still a valid issue?
