### ISSUE TITLE
TextFormField converting single/double quotes characters

### ISSUE THREAD

**Issue by WChoy** [flutter/flutter#27047]
Bug 1) `'` => `‘` or `’`   
description:
     single quote (`\u0027`) get converted to open/close single quote (`\u2018`-`\u2019`)

Bug `"` =>  `“` or `‘’`  
description:
      double quote (`\u0021`) get converted to open/close double quotes (`\u201c`-`\u201d`) 

You only get the open quotes if the char is the first character in the string (very weird).
`'''` => `\u2018` `\u2019` `\u2019`
`"""` => `\u201c` `\u201d` `\u201d`
`A"""` => `\u0041` `\u201d` `\u201d` `\u201d`

## Steps to Reproduce

I am trying to write a password validator for AWS (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html)

1. ...  Description of allowed passwords. 
```dart
                  Text('Must be at least 6 characters'),
                  Text('Require uppercase letters'),
                  Text('Require lowercase letters'),
                  Text('Require numbers'),
                  Text('Require a special character from this set:'),
                  Text(
                      '\t ^ \$ * . [ ] { } ( ) ? - " ! @ # % & / \\ , > < \' : ; | _ ~ `'),
```
2. ...    Using a TextEditingController, because I never save the password to my state.
 ```dart
                final myController = TextEditingController();
 ```
.. In the build method, 
 ```dart
                   child: TextFormField(
                      controller: myController,
                      obscureText: true, // Use secure text for passwords.
                      validator: validatePassword,
                      decoration: new InputDecoration(
                          hintText: 'Password', labelText: 'Enter your password'
                      )
                    ),
```
3. ...

```dart
String validatePassword(String value) {

  print(value.codeUnits);
  print(value.codeUnitAt(0).toRadixString(16));
  print(value.codeUnitAt(1).toRadixString(16));
  print(value.codeUnitAt(2).toRadixString(16));
  print(value.codeUnitAt(3).toRadixString(16));
  

  // String allowedChar = r'^[\u0009\u000A\u000D\u0020-\u00FF\u2018-\u2019]{6,99}$';
  // if (!RegExp(allowedChar).hasMatch(value))
  //  return 'Length: 6-99 characters';
  if (!RegExp(r'\d').hasMatch(value))
    return 'Require numbers';
  // ^$*.[]{}()?-"!@#%&/\,><':;|_~`
  String specialChar = r'[\u0021-\u002A\u002C-\u002F\u003A-\u003C\u003E-\u0040\u005B-\u0060\u007B-\u007E\u2018-\u2019]';
  if (!RegExp(specialChar).hasMatch(value))
    return 'Require a special character';
  if (!RegExp(r'[A-Z]').hasMatch(value))
    return 'Require uppercase letters';
  if (!RegExp(r'[a-z]').hasMatch(value))
    return 'Require lowercase letters';
  return null;
}
```
3. ...

## Logs

```dart
  print(value.codeUnits);
  print(value.codeUnitAt(0).toRadixString(16));
  print(value.codeUnitAt(1).toRadixString(16));
  print(value.codeUnitAt(2).toRadixString(16));
```
results in 
```dart
flutter: [8220, 8221, 8221]
flutter: 201c
flutter: 201d
flutter: 201d
```

**Comment by zoechi** [comment]
Is this a support request, feature request, bug report?
What is the question or problem?
Is the expected behavior different than the actual behavior?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Is this about RegExp not working as expected?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
