### ISSUE TITLE
ListView (and company) don't handle children with LocalKeys moving around

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27057]
If you have a ListView with two stateful children, each with a key, and then you switch the order of the children, both of them get disposed and rebuilt. We should make the sliver widget logic handle LocalKeys just like we do for regular multichild render object widgets.

**Comment by zoechi** [comment]
#26494 #21023 look related

**Comment by sir-boformer** [comment]
Yes, it's the same as #21023

This is a very serious issue for me.

**Comment by goderbauer** [comment]
We believe that this one is fixed now. Please re-open with sample code if it's still not working for you.
