### ISSUE TITLE
Flutter Refactor->extract->flutter widget

### ISSUE THREAD

**Issue by tpackard1** [flutter/flutter#27050]
I am getting this error: reference to an enclosing class method cannot be extracted. I have included the Flutter doctor results down below. And I have put an example of the code I've written in my repository and at line 98 I'm trying to refactor RadialDragGestureDetector. You can also go to youtube.com and type in fluttery challenge music player then go to 1:11:42ish and that is the part in the video that I am having difficulty with. If you would like anymore information just let me know. Any help will be greatly appreciated!
```
C:\src\flutter> flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
• Flutter version 1.0.0 at C:\src\flutter\flutter
• Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
• Engine revision 7375a0f414
• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
• Android SDK at C:\Users\Taylor\AppData\Local\Android\sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[√] Android Studio (version 3.3)
• Android Studio at C:\Program Files\Android\Android Studio1
• Flutter plugin version 31.3.3
• Dart plugin version 182.5124
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)
```

**Comment by zoechi** [comment]
Would you mind posting the links to your repository and the youtube video?

**Comment by zoechi** [comment]
Please report the issue in https://github.com/dart-lang/sdk/issues instead. This feature is driven by the DartAnalyzer and that is maintained in the dart-lang/sdk repo. Thanks

**Comment by Flutey** [comment]
You can create a class called RadialSeekBar and then reference it in Extended.
