### ISSUE TITLE
Text Widget break work is abnormal

### ISSUE THREAD

**Issue by wonderful89** [flutter/flutter#27064]
This is the abnormal phenomena.
![image](https://user-images.githubusercontent.com/44089389/51724930-96e2a900-209a-11e9-9edb-a9bcc6520f63.png)

The word 'visit' needs to show in next line. 

## Steps to Reproduce

the code page.
https://github.com/qqzhao/flutterDemos/blob/master/lib/home/base/fitText/baseText.dart

## Logs

I update to the flutter tag 1.1.9 version now . There are the same problems in preview version.
```
➜  flutterDemos git:(master) ✗ flutter --version
Flutter 1.1.9 • channel unknown • unknown source
Framework • revision 1407091bfb (2 weeks ago) • 2019-01-08 20:40:19 -0800
Engine • revision e5ec3cf3ea
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)
```

**Comment by zoechi** [comment]
Might be relate to #16450

**Comment by wonderful89** [comment]
[It is proved that the string is not valid](https://github.com/qqzhao/flutterDemos/blob/master/docs/issue_27064.md).  

This problem does not exist now.
