### ISSUE TITLE
google_maps example not working

### ISSUE THREAD

**Issue by cosminstoinescu** [flutter/flutter#27075]
I have an app that is composed from:
- BottomNavigation
- RubberBottomSheet
- GoogleMap

Please see the attached image:
![image](https://user-images.githubusercontent.com/36987703/51734657-dc4ca980-208d-11e9-9214-41d6f9da1c2c.png)

I tested the app on following:
- Emulator with Android 9 - success
[Emulator (Android 9) - Maps working.txt](https://github.com/flutter/flutter/files/2795272/Emulator.Android.9.-.Maps.working.txt)
- Huawei P8 Lite - success
[Huawei P 8 Lite - Maps working.txt](https://github.com/flutter/flutter/files/2795275/Huawei.P.8.Lite.-.Maps.working.txt)
- Huawei P Smart 2019 with Android 9 - failed
[Huawei P Smart 2019 (Android 9)- Maps not working.txt](https://github.com/flutter/flutter/files/2795280/Huawei.P.Smart.2019.Android.9.-.Maps.not.working.txt)

On Huawei P Smart 2019 GoogleMaps is not loading.
![image](https://user-images.githubusercontent.com/36987703/51735362-ebccf200-208f-11e9-9688-c0c492207bdd.png)

Is there a known issue about this behavior?

**Comment by chadidi** [comment]
@zoechi Same issue here in some devices the map doesn't load at all and in other devices the map loads with just google logo and no maps.

I also noticed in some device that the map works in debug mode and when doing 
`flutter build apk`
`flutter install`

but not in production after uploading to play store!!!

**Comment by zoechi** [comment]
Can you please post some examples what the devices are that work and that do not?
