### ISSUE TITLE
when use 'flutter doctor'   alert  env: bash\r: No such file or directory

### ISSUE THREAD

**Issue by hatjs880328s** [flutter/flutter#27076]
## Steps to Reproduce

1. follow your doc download flutter.zip
2. unzip
3. run 

```
flutter doctor
```
then alert 
```
bash\r: No such file or directory
```

## Logs

bash\r: No such file or directory

**Comment by zoechi** [comment]
Can you please post the full output.

**Comment by dariotrombello** [comment]
From where did you execute ´flutter doctor´? Did you add flutter to path?

**Comment by zoechi** [comment]
Thanks @dariotrombello 

See (depending on your OS)
https://flutter.io/docs/get-started/install/windows#update-your-path
https://flutter.io/docs/get-started/install/macos#update-your-path
https://flutter.io/docs/get-started/install/linux#update-your-path

**Comment by zoechi** [comment]
perhaps you need to restart your machine so they take effect or run `source ~/base_profile`

**Comment by hatjs880328s** [comment]
can't work . run  'source ~/base_profile' already...

**Comment by hatjs880328s** [comment]
echo $PATH
/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/shanwz/development/flutter/bin

**Comment by dariotrombello** [comment]
If you are on linux there is no /Users folder by default. Try this:
`export PATH=/home/yourname/flutter/bin:$PATH`
 
Where `yourname` is you need to replace it of course with your linux username

**Comment by hatjs880328s** [comment]
sovle it...
redownload the zip file then use shell unzip it.

**Comment by MoacirSchmidt** [comment]
1) This error occurs if you download and unzip the WINDOWS version into MAC or UNIX!

2) Please make sure you have download for the RIGHT operating system!

**Comment by morningstarwang** [comment]
> 1. This error occurs if you download and unzip the WINDOWS version into MAC or UNIX!
> 2. Please make sure you have download for the RIGHT operating system!

thanks... make such an idiot mistake...

**Comment by evilarceus** [comment]
I downloaded the Linux version (v1.9.1) and I still get the error "/usr/bin/env: ‘bash\r’: No such file or directory" :/

**Comment by aislanmaia** [comment]
I'm getting a similar error, but when trying to run `flutter run` inside `spacemacs` editor. 
And this is important, I'm using `zsh` not `bash` and it returns this message making reference to `bash` for no reason I know. :( 

This is my PATH in a Linux machine:
```
/home/aislan/Development/flutter/bin/cache/dart-sdk/bin:/usr/local/android-studio/bin:/home/aislan/Development/flutter/bin:/home/aislan/.asdf/shims:/home/aislan/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/path/to/elixir/bin:/home/aislan/.asdf/installs/nodejs/10.8.0/.npm/bin:/usr/lib/dart/bin:/home/aislan/.pub-cache/bin:/home/aislan/.pub-cache/bin/dart_language_server
```

**Comment by DEXIT33** [comment]
Got this error today. I googled and found that it is probably related to line endings in the flutter script. Haven't found a solution yet.

**Comment by asmodeoux** [comment]
> I'm getting a similar error, but when trying to run `flutter run` inside `spacemacs` editor.
> And this is important, I'm using `zsh` not `bash` and it returns this message making reference to `bash` for no reason I know. :(
> 
> This is my PATH in a Linux machine:
> 
> ```
> /home/aislan/Development/flutter/bin/cache/dart-sdk/bin:/usr/local/android-studio/bin:/home/aislan/Development/flutter/bin:/home/aislan/.asdf/shims:/home/aislan/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/path/to/elixir/bin:/home/aislan/.asdf/installs/nodejs/10.8.0/.npm/bin:/usr/lib/dart/bin:/home/aislan/.pub-cache/bin:/home/aislan/.pub-cache/bin/dart_language_server
> ```

I use zsh on macOS Catalina and was confused by that as well. Although I fixed it by editing the gradlew file in an android folder:

vim gradlew
:set fileformat=unix
:wq

**Comment by robinjohn** [comment]
Faced the same issue. Tried the below and that fixed it:  

1. Clean build
``` 
flutter clean
```
2. Make the gradlew bin runnable in unix.
```
vim gradlew
:set fileformat=unix
:wq
```
3. Fix the flutter pub packages cache built from earlier session in windows
```
flutter pub cache repair
```

**Comment by kaan35** [comment]
When I changed android folder and inside files line separator to CRLF, again get bash\r error. When android folder line separator is LF, its fixes problem. In windows there is no problem, project working fine but in Mac or Linux android folder line separator should be LF.

**Comment by kaan35** [comment]
For fix problem just change line separator to LF this file :  project_folder/android/gradlew

**Comment by mapadj** [comment]
I had the same issue, because my PATH included
`/mnt/c/src/flutter/flutter/bin`
 before my manual include at the end of  PATH like this:
`export PATH=$PATH:$FLUTTER_HOME/bin`

I fixed the issue, by adding it to the front of PATH like that:
`export PATH=$FLUTTER_HOME/bin:$PATH`
Now my flutter path is called before the other path is reached.

I am not sure thow, where the other include is coming from.

**Comment by crimsonvspurple** [comment]
If anyone else is having this issue even though you followed the official guide here: https://flutter.dev/docs/get-started/install/linux#update-your-path

This is how you fix it:
```
rm -rf flutter
git config --global core.autocrlf false
git clone git@github.com:flutter/flutter.git
```

For whatever reason, I got windows `crlf` in linux (wsl2). Git is installed and run from WSL2; not windows.

**Comment by thanura-rashmika** [comment]
> 1. This error occurs if you download and unzip the WINDOWS version into MAC or UNIX!
> 2. Please make sure you have download for the RIGHT operating system!

100% True

**Comment by hyoretsu** [comment]
Here to post my 2 cents. Since I'm using WSL, when I try to create a Flutter project on VSCode I get "display size is bogus" message, so I had to install it on Windows too to create projects from there. Doing that messed up my path, so I was actually running flutter from Windows instead of Ubuntu. Running `which flutter` showed the windows path, and what solved it was adding this to `~/.bash_aliases`:
```
alias flutter=~/flutter/bin/flutter
```

**Comment by hyoretsu** [comment]
Weirdly enough, I'm here again giving it another try. This time, I also had to add this to `~/.bash_aliases`:
```
alias dart=~/flutter/bin/dart
```
