### ISSUE TITLE
Local file into webview_flutter

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#27078]
Hello, 

Is it possible to load a local HTML using WebView from plugins/packages/webview_flutter?

**Comment by dariotrombello** [comment]
Shouldn't it work by just adding the HTML file to your pubspec.yml assets and do it like this then?
```
      WebView(
        initialUrl: 'assets/test.html',
        javascriptMode: JavascriptMode.unrestricted,
      ),
```

**Comment by durduman** [comment]
I tried exactly that and it did not load.

**Comment by dariotrombello** [comment]
Maybe you can try using this package https://pub.dartlang.org/packages/flutter_webview_plugin
It's the community version of webview_flutter and should support loading local html files.

**Comment by zoechi** [comment]
Things mentioned in https://github.com/fluttercommunity/flutter_webview_plugin/issues/23 should work in both plugins

**Comment by dariotrombello** [comment]
Try using `file:///assets/test.html`

**Comment by durduman** [comment]
@dariotrombello 
I do not wish to have the webivew occupy the whole screena and I didn't manage to make flutter_webview_plugin do this. Otherwise, it loaded the local file.

**Comment by dariotrombello** [comment]
`file:///assets/test.html` should work aswell in webview_flutter

**Comment by durduman** [comment]
Not working with `file:///assets/test.html.`

**Comment by durduman** [comment]
@zoechi using:


> WebView(
>                         initialUrl: new Uri.dataFromString('<html><body><h1>hello world</h1></body></html>', mimeType: 'text/html').toString(),
>                         javascriptMode: JavascriptMode.unrestricted,
>                       )

worked well, BUT I will check in the following minutes to see if it reacts well to the CSS and the JS from the files after I load the text from them. 
Thanks!

**Comment by zoechi** [comment]
You will need to include the CSS inline. A data URI can not load CSS or other resources from a local path. Loading from a network URL might work though.

**Comment by durduman** [comment]
@zoechi figured this after a some tryouts ... and what about images?

**Comment by zoechi** [comment]
That's the same. 
Either you can make them available on a web server
or you use another approach mentioned in the issue linked above.
If you have multiple files, just implement a web server within your app and point webview to that IP/Port. You can do that with a few lines of code. The issue even contains a link to a Medium article where this is explained in more details.

**Comment by durduman** [comment]
Ok thank you

**Comment by TheKonnectApp** [comment]
Here's how you can load a local HTML file for both iOS and Android without the need for web server:
**Import Requirements:**
```
import 'package:webview_flutter/webview_flutter.dart';
import 'package:flutter/services.dart'; //Needed for rootBundle.loadString
```
**#1 Initialize a WebViewController at the top of your class:**
`class PrivacyPolicyState extends State<PrivacyPolicy> {`
`WebViewController _controller;`
`...`

**#2 Load your HTML file in as a string like so:**

```
@override
  void initState() {
    super.initState();
    _loadHtmlFromAssets();
  }
```
```
Future<void> _loadHtmlFromAssets() async {
    String fileText = await rootBundle.loadString('assets/konnect_privacy_policy.html');
    theURI = Uri.dataFromString(
        fileText,
        mimeType: 'text/html',
        encoding: Encoding.getByName('utf-8')
    ).toString();

    setState(() {
      _controller.loadUrl(theURI);
    });
  }
```

**#3 Then in your WebView widget:**
```
WebView(
          initialUrl: '',
          onWebViewCreated: (WebViewController webViewController){
            _controller = webViewController;
          },
        ),
```

**Comment by bmbariah** [comment]
In case anyone finds a null error with @TheKonnectApp solution, try this...

https://github.com/suragch/iv_interlinear_kjv/blob/eac8434d00ab70a9161155a7364ace798d65e08a/lib/help_screen.dart

Credits to @suragch

**Comment by j796160836** [comment]
Here is the full example,

```
import 'dart:async';
import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:webview_flutter/webview_flutter.dart';

class BrowserPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _BrowserPageState();
}

class _BrowserPageState extends State<BrowserPage> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(middle: Text("Browser")),
        child: SafeArea(
          child: WebView(
              initialUrl: "",
              onWebViewCreated: (WebViewController webViewController) {
                _controller.complete(webViewController);
              },
              javascriptMode: JavascriptMode.unrestricted),
        ));
  }

  @override
  void initState() {
    super.initState();
    _controller.future.then((controller) {
      _loadHtmlFromAssets(controller);
    });
  }

  Future<void> _loadHtmlFromAssets(WebViewController controller) async {
    String fileText = await rootBundle.loadString('assets/index.html');
    String theURI = Uri.dataFromString(fileText,
            mimeType: 'text/html', encoding: Encoding.getByName('utf-8'))
        .toString();

    setState(() {
      print(theURI);
      controller.loadUrl(theURI);
    });
  }
}
```

As you see, I create a WebView and use TheKonnectApp's answers: load the html strings from assets.
It only work with single page because it loads only html strings. 

Don't forget to declare your assets at **pubspec.yaml**

```
flutter:
  assets:
    - assets/index.html
```

Have fun. 🙂

**Comment by kakyoism** [comment]
I opened #65379. Although somewhat related to this issue, it is more serious than I had thought. Please see below.

## Attempt

To work around #65379 and #27086, I thought about merging `help_en.html` and `help_fr.html` into a single html file and turn the href's into anchors so that I can bypass the local assets reference issue by jumping within the same html file. 

In theory, this would work. 

## Trouble

However, to my surprise, this didn't work either! This time, instead of going blank, webview gives no response when trying to go to the anchors. The same anchors work fine in an Electron test app and in the browsers.

This time I got an error in Android Studio's console

```sh
E/InputMethodManager(28987): b/117267690: Failed to get fallback IMM with expected displayId=259 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b193667 VFEDHVC.. .F...... 0,0-2075,706}
I/chromium(28987): [INFO:CONSOLE(0)] "Not allowed to navigate top frame to data URL: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%0A%3Chtml%20xmlns=%22http://www.w3.org/1999/xhtml%22%20lang=%22%22%20xml:lang=%22%22%3E%0A%3Chead%3E%0A%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%0A%20%20%3Cmeta%20name=%22generator%22%20content=%22pandoc%22%20/%3E%0A%20%20%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0,%20user-scalable=yes%22%20/%3E%0A%20%20%3Ctitle%3E%20%3C/title%3E%0A%20%20%3Cstyle%3E%0A%20%20%20%20code%7Bwhite-space:%20pre-wrap;%7D%0A%20%20%20%20span....E4%BA%8E%3C/h1%3E%0A%3Ch3%20id=%22section%22%3E%3C/h3%3E%0A%3Ch2%20id=%22%E5%8A%A8%E5%90%AC-version-1.0%22%3E%E5%8A%A8%E5%90%AC%20version%201.0%3C/h2%3E%0A%3Cp%3ECopyright%C2%A9%202020%20NExT%20%E5%B7%A5%E4%BD%9C%E5%AE%A4%E7%BE%A4%3C/p%3E%0A%3Cp%3E%E7%89%88%E6%9D%83%E6%89%80%E6%9C%89%3C/p%3E%0A%3Cp%3E%E9%9A%90%E7%A7%81%E6%94%BF%E7%AD%96%3Cspan%20class=%22math%20inline%22%3E%C2%A0%C2%A0%C2%A0%C2%A0%3C/span%3E%E7%94%A8%E6%88%B7%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE%3C/p%3E%0A%3C/body%3E%0A%3C/html%3E%0A#helpen", source: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%0A%3Chtml%20xmlns=%22http://www.w3.org/1999/xhtml%22%20lang=%22%22%20xml:lang=%22%22%3E%0A%3Chead%3E%0A%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%0A%20%20%3Cmeta%20name=%22generator%22%20content=%22pandoc%22%20/%3E%0A%20%20%3Cmeta%20name=%22viewport%22%20content=%22width=device-width,%20initial-scale=1.0,%20user-scalable=yes%22%20/%3E%0A%20%20%3Ctitle%3E%20%3C/title%3E%0A%20%20%3Cstyle%3E%0A%20%20%20%20code%7Bwhite-space:%20pre-wrap;%7D%0A%20%20%20%20span.smallcaps%7Bfont-variant:%20small-caps;%7D%0A%20%20%20%20span.underline%7Btext-decoration:%20underline;%7D%0A%20%20%20%20div.column%7Bdisplay:%20inline-block;%20vertical-align:%20top;%20width:%2050%25;%7D%0A%20%20%20%20div.hanging-indent%7Bmargin-left:%201.5em;%20text-indent:%20-1.5em;%7D%0A%20%20%3C/style%3E%0A%20%20%3C!--%5Bif%20lt%20IE%209%5D%3E%0A%20%20%20%20%3Cscript%20src=%22//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js%22%3E%3C/script%3E%0A%20%20%3C!%5Bendif%5D--%3E%0A%20%20%3Cscript%20type=%22text/javascript%22%20src=%22help_lang.js%22%20type=%22module%22%3E%3C/script%3E%0A%20%20%3Cstyle%3E%0A%20%20/*%0A%20%20%20%20CAUTION:%20must%20use%20embedded%20style%20for%20standalone%20html%20with%20-s%0A%20%20*/%0A%20%20/***************%0A%20%20Global%0A%20%20***************/%0A%20%20/*%0A%20%20%20*%20I%20add%20this%20to%20html%20files%20generated%20with%20pandoc.%0A%20%20%20*/%0A%20%20html%20%7B%0A%20%20font-size:%20100%25;%0A%20%20overflow-y:%20scroll;%0A%20%20-webkit-text-size-adjust:%20100%25;%0A%20%20-ms-text-size-adjust:%20100%25;%0A%0A%20%20/*--scrollbarBG:%20%23CFD8DC;*/%0A%20%20--scrollbarBG:%20%232a2f39;%0A%20%20--thumbBG:%20%2390a4ae;%0A%20%20/*CAUTION:%20required%20for%20background%20parallax%20*/%0A%20%20height:%20100%25;%0A%20%20/*CAUTION%20end:%20required%20for%20background%20parallax%20*/%0A%20%20%7D%0A%20%20body%20%7B%0A%20%20color:%20%23e5e5e5;%0A%20%20font-family:%20Arial,%20Helvetica,%20sans-serif;%0A%20%20font-size:%2012px;%0A%20%20line-height:%201.7;%0A%20%20padding:%201em;%0A%20%20margin:%20auto;%0A%20%20max-width:%2042em;%0A%20%20/*CAUTION:%20required%20for%20background%20parallax%20*/%0A%20%20background:%20url('images/bg-logo.png')%20no-repeat%20top%20right,%20%232a2f39;%0A%20%20height:%20100%25;%0A%20%20background-attachment:%20fixed;%0A%20%20background-position:%20center;%0A%20%20background-repeat:%20no-repeat;%0A%20%20background-size:%20cover;%0A%20%20/*CAUTION%20end:%20required%20for%20background%20parallax*/%0A%20%20%7D%0A%20%20a%20%7B%0A%20%20color:%20%237c8694;%0A%20%20text-decoration:%20none;%0A%20%20%7D%0A%20%20a:visited%20%7B%0A%20%20color:%20%230072ae;%0A%20%20%7D%0A%20%20a:hover%20%7B%0A%20%20color:%20%2306e;%0A%20%20%7D%0A%20%20a:active%20%7B%0A%20%20color:%20%23faa700;%0A%20%20%7D%0A%20%20a:focus%20%7B%0A%20%20outline:%20thin%20dotted;%0A%20%20%7D%0A%20%20*::-moz-selection%20%7B%0A%20%20background:%20rgba(255,%20255,%200,%200.3);%
E/InputMethodManager(28987): b/117267690: Failed to get fallback IMM with expected displayId=259 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{b193667 VFEDHVC.. .F...... 0,0-2075,706}

```

## Verdict 

So to me this is beyond the fuss of running an http server to work around a very simple webpage doc. It is actually a much more serious bug to me.

@zoechi I don't think the immediate webserver workaround could solve this problem.

**Comment by uc-dve** [comment]
> @zoechi using:
> 
> ```
> WebView( 
>     initialUrl: new Uri.dataFromString( '<html><body><h1>hello world</h1></body></html>', 
>                                         mimeType: 'text/html')
>                     .toString(),
>     javascriptMode: JavascriptMode.unrestricted)
> ```
> 
> worked well, BUT I will check in the following minutes to see if it reacts well to the CSS and the JS from the files after I load the text from them.
> Thanks!

This is the right way to implement webview if HTML changes multiple times.
I just need to load files from assets folder, is there any way to do it in this format?
