### ISSUE TITLE
Store the last run app (during development) on the device

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#271]
From a recent hackathon: it would be nice to store the last-run app locally on the device. This way, if you disconnect your phone, and the app stops/closes for some reason, you can re-launch your app and show your friends.

**Comment by abarth** [comment]
Do we still want this feature if its easy to create APKs?

**Comment by abarth** [comment]
Closing this issue now that `flutter apk` can make APKs.  If you still want this "sticky" development mode, please re-open this issue.

**Comment by eseidelGoogle** [comment]
The original comment from the hackaton appears to have assumed Atom.  Perhaps we need to expose `flutter apk` in Atom? @devoncarew

**Comment by devoncarew** [comment]
Sounds good; tracked here: https://github.com/flutter/atom-flutter/issues/23.

**Comment by sethladd** [comment]
sgtm! Making an APK is easy now.
