### ISSUE TITLE
WidgetsApp shouldn't require a TextStyle.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2710]

**Comment by Hixie** [comment]
What text style should we use by default then?

**Comment by apwilson** [comment]
The default?  new TextStyle()?

**Comment by Hixie** [comment]
Text defaults to whatever the WidgetsApp provides. :-)

But ok, I guess if white 10px sans-serif or whatever it is the engine defaults to is good enough for the engine, it can be good enough for the widgets layer too.
