### ISSUE TITLE
android_alarm_manager should support specifying own triggerAtMillis time

### ISSUE THREAD

**Issue by CDDelta** [flutter/flutter#27115]
The `AlarmManager` allows users to specify when the timer should first trigger with the `triggerAtMillis` param but this is not exposed in the Flutter package. Exposing this would allow users to register more complex alarms such as run every day at 8:00 A.M.

**Comment by CDDelta** [comment]
I have added a PR for this, please provide your feedback.

**Comment by gabrc52** [comment]
Selecting an arbitrary `DateTime` should also be allowed in AndroidAlarmManager.oneShot()

**Comment by bkonyi** [comment]
This has been added to `periodic`. I'll look into adding this to `oneShot` as well.
