### ISSUE TITLE
flutter/plugins CI should test `flutter create` on stable

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#27110]
This would have caught #27106 and seems feasible to automate. The app produced by `flutter create` on stable should be able to include any of the flutter/plugins as a dependency in its `pubspec.yaml` and still compile. Right now the flutter/plugins CI is only ever testing that the example apps within each repo build, but they're custom written for each plugin so can be working when `flutter create` is not.

/cc @cbracken @collinjackson, this is tangentially related to the other flutter/plugins testing work.

**Comment by bparrishMines** [comment]
Finished by https://github.com/flutter/plugins/pull/2004
