### ISSUE TITLE
doctor: "Unable to find bundled Java version" for Android Studio 3.3 (JetBrains)

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#27136]
## Steps to Reproduce

1. Run `flutter doctor`
2. Get `Unable to find bundled Java version` with Android Studio 3.3 installed by JetBrains Toolbox: https://www.jetbrains.com/toolbox/

I've seen bugs like #15514 and #14846, but this seems distinct since those indicate it happened with older versions of Android Studio that aren't supported.

Android Studio 3.3 is the latest version, so it seems like this is potentially a different issue?

Let me know if there's any more logs that I can provide.

## Logs

```
[!] Android Studio (version 3.3)
    • Android Studio at /Users/chris/Applications/JetBrains Toolbox/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
```

**Comment by cpboyd** [comment]
As an aside, I just tried with the standard Android Studio macOS app:
```
[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by caseylau** [comment]
Some problem happens to me: 

Os: macOS Mojave 10.14.2
Android studio: 3.3
Java version: 11.0.1
![image](https://user-images.githubusercontent.com/20714821/52273085-ab208300-2983-11e9-86de-2297a17c4405.png)

**Comment by dashmug** [comment]
The fix that worked for me was to uninstall the Android Studio version that came with Jetbrains Toolbox. Then, I had to delete all traces of it.

    $ rm -rf ~/Android
    $ # Check the actual directories
    $ rm -rf ~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio

Then, I installed Android Studio from https://developer.android.com/studio/, did `flutter doctor` and followed all steps. It is properly working now with no errors when I run `flutter doctor`.

I have to keep in mind NOT to update Android Studio through JetBrains Toolbox.

**Comment by kangwang1988** [comment]
@cpboyd 
Can you try the latest master?
I guess it has been also resolved by https://github.com/flutter/flutter/pull/27687

**Comment by cpboyd** [comment]
@kangwang1988 It seems to work, with one caveat:
JetBrains Toolbox provides and "Update" button if you're using the Google-provided version of Android Studio.  For me, this downloaded a their version to `~/Library/Application Support/JetBrains/Toolbox/apps` but didn't create the launcher app in `~/Applications/JetBrains Toolbox`.

Since there was no launcher app, `flutter doctor` reported that Android Studio wasn't available after I deleted the Google one.

However, after uninstalling/reinstalling Android Studio in the JetBrains Toolbox (which created the launcher app), it worked perfectly.

The above situation seems like more of a bug with the JetBrains Toolbox than anything.

**Comment by linnuo12** [comment]
Running "flutter pub get" in flutter_tools...                       4.2s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Unable to find bundled Java version.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)

**Comment by linnuo12** [comment]
`Running "flutter pub get" in flutter_tools...                       4.2s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Android Studio (version 3.5)
    X Unable to find bundled Java version.
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)`

**Comment by samridhgupta** [comment]
Having similar issue 

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-IN)
    • Flutter version 2.2.1 at /Users/samridhgupta/Library/Flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/samridhgupta/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/samridhgupta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

```

**Comment by crinai** [comment]
just delete the "jre" dir onder ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085 and create a link from you external jdk or jre with name "jre".
I used this 2 command:
rm -r -f ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre
ln -s ~/.jdk/jdk1.8.0_291 ~/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre

**Comment by belveder79** [comment]
Just wanted to mention that the problem also occured on recent Arctic Fox 2020.3.1 together with 2.2.3 stable flutter toolchain.

I resolved it on my side by creating a symbolic link:
```
   cd /Applications/Android\ Studio.app/Contents/jre
   ln -s ../jre jdk
```

Not the most elegant solution, but works...

**Comment by sandercoffee** [comment]
> Just wanted to mention that the problem also occured on recent Arctic Fox 2020.3.1 together with 2.2.3 stable flutter toolchain.
> 
> I resolved it on my side by creating a symbolic link:
> 
> ```
>    cd /Applications/Android\ Studio.app/Contents/jre
>    ln -s ../jre jdk
> ```
> 
> Not the most elegant solution, but worked partially... the problem is that the system finds two java versions, and either the android licenses are not accepted, or the bundled version is not found. So instead I removed the link and added an other one:
> 
> ```
>   ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" jdk
> ```


Worked, lol!

**Comment by LeoBorquez** [comment]
> Just wanted to mention that the problem also occured on recent Arctic Fox 2020.3.1 together with 2.2.3 stable flutter toolchain.
> 
> I resolved it on my side by creating a symbolic link:
> 
> ```
>    cd /Applications/Android\ Studio.app/Contents/jre
>    ln -s ../jre jdk
> ```
> 
> Not the most elegant solution, but worked partially... the problem is that the system finds two java versions, and either the android licenses are not accepted, or the bundled version is not found. So instead I removed the link and added an other one:
> 
> ```
>   ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" jdk
> ```
> 
> and that one finally did the trick:
> 
> ```
> flutter % flutter doctor -v
> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-US)
>     • Flutter version 2.2.3 at /Users/arth/Development/AR4/TESTING/flutter
>     • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/arth/Library/Android/sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5.1, Build version 12E507
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
> 
> • No issues found!
> ```

works for me too.

Thank you!

**Comment by RobertoEMG** [comment]
> Just wanted to mention that the problem also occured on recent Arctic Fox 2020.3.1 together with 2.2.3 stable flutter toolchain.
> 
> I resolved it on my side by creating a symbolic link:
> 
> ```
>    cd /Applications/Android\ Studio.app/Contents/jre
>    ln -s ../jre jdk
> ```
> 
> Not the most elegant solution, but worked partially... the problem is that the system finds two java versions, and either the android licenses are not accepted, or the bundled version is not found. So instead I removed the link and added an other one:
> 
> ```
>   ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" jdk
> ```
> 
> and that one finally did the trick:
> 
> ```
> flutter % flutter doctor -v
> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-US)
>     • Flutter version 2.2.3 at /Users/arth/Development/AR4/TESTING/flutter
>     • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/arth/Library/Android/sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5.1, Build version 12E507
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
> 
> • No issues found!
> ```

Thank youuuuuuuuuu, ... works for me tooooo.

**Comment by yfer** [comment]
Recent update to Arctic Fox lead me here, for me best solution was to uninstall and install previous version from https://developer.android.com/studio/archive

**Comment by yfer** [comment]
it is fixed on master channel so you can do:

```
flutter channel master
flutter upgrade
```

and change back when fix in stable

**Comment by karlito40** [comment]
If you won't go on the master channel, you can fix this issue with these steps:
- copy/pasta the changes from this [pull request](https://github.com/flutter/flutter/pull/87267/files) in your flutter sdk. 
- remove `bin/cache/flutter_tools.stamp` and `bin/cache/flutter_tools.snapshot` from your flutter sdk . 
- flutter doctor

_It worked for me._

**Comment by vivekspanicker** [comment]
> Just wanted to mention that the problem also occured on recent Arctic Fox 2020.3.1 together with 2.2.3 stable flutter toolchain.
> 
> I resolved it on my side by creating a symbolic link:
> 
> ```
>    cd /Applications/Android\ Studio.app/Contents/jre
>    ln -s ../jre jdk
> ```
> 
> Not the most elegant solution, but worked partially... the problem is that the system finds two java versions, and either the android licenses are not accepted, or the bundled version is not found. So instead I removed the link and added an other one:
> 
> ```
>   ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" jdk
> ```
> 
> and that one finally did the trick:
> 
> ```
> flutter % flutter doctor -v
> [✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-US)
>     • Flutter version 2.2.3 at /Users/arth/Development/AR4/TESTING/flutter
>     • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
>     • Engine revision 241c87ad80
>     • Dart version 2.13.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/arth/Library/Android/sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.5.1, Build version 12E507
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
> 
> • No issues found!
> ```

It worked! Thank you for ending my hours of troubleshooting.
