### ISSUE TITLE
`PathMetric` can get ripped out from under you.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#27139]
The following code leads to a surprise:

```dart
  final Path path = Path()..lineTo(10, 0);
  final PathMetrics metrics = path.computeMetrics();
  final PathMetric metric = metrics.first;
  print(metric.length); // 10.0
  metrics.iterator.moveNext();
  print(metric.length); // 0.0 !!
```

This means things like `metrics.toList()` are very confusing. The `length` getter can probably be pretty easily fixed by making it less lazy (maybe force it to instantiate and store it on the Dart side at least when the iterator moves).  The methods might be a bit more tricky - I think we'd need to expand out the full iteration on the C++ side and cache them for the lifetime of the object (if we should fix them at all).

At the very least, I think we should fix length (it's very confusing for a property to change like that) and document how the methods will work (if at all).

**Comment by dnfield** [comment]
Related: https://bugs.chromium.org/p/skia/issues/detail?id=8721

**Comment by dnfield** [comment]
Hmm.  Apparently I documented this when I wrote the class and forgot about it.

Either way it can be improved for now, regardless of whether the Skia API can add a feature for it.

**Comment by dnfield** [comment]
The code raised in this issue now works.

However, we can keep this open to see if we can get the methods on `PathMetric` to work as well.

**Comment by dnfield** [comment]
As of https://skia-review.googlesource.com/c/skia/+/187922 this should be resolvable.

**Comment by zbarryte-luminopia** [comment]
This issue is marked as closed, but this appears to still be an issue.

**Comment by dnfield** [comment]
@zbarryte-luminopia it should be fixed on both stable and master at this point, and there are tests asserting so.  What version of Flutter are you using?  

It may be better to just open a new bug with a reproduction and the output of `flutter doctor`.  Feel free to tag me in it.

**Comment by zbarryte-luminopia** [comment]
@dnfield - I'm running version 1.13.3-pre.31 (my `flutter doctor -v` output is included in issue [48980](https://github.com/flutter/flutter/issues/48980))

**Comment by eckhartcke** [comment]
I'm happy that these conversations are public. This one is an object lesson in the difference between an iterable collection and an actual list. I was having the same issue with PathMetrics and this dialog gave me my solution.
