### ISSUE TITLE
Firebase PhoneAuth - signInWithCredential returns null reference

### ISSUE THREAD

**Issue by ebastuart** [flutter/flutter#27132]
I have updated to `firebase_auth: ^0.8.0+1` and some other google related dependencies today.
Lots of breaking changes, like it was told in the changelogs. To solve that I did:
- migrated my Flutter project to AndroidX
- replaced `signInWithPhoneNumber`, which is not available anymore,  with the new methode using the `AuthCredential`

Now I facing a new issue. I do the following request.
```dart
FirebaseUser user;
final AuthCredential credential = PhoneAuthProvider.getCredential(
  verificationId: _verificationId,
  smsCode: _smsCode,
);
try {
  user = await _auth.signInWithCredential(credential);
} catch (e) {
  print(e.message);
}
```
`signInWithCredential` returns an error with the message 
```
null reference
```
It happens always when I try to signup with a test number as well with a real number.
The strangest thing is, when I am using a real number, that after stopping the app and restart debugging it, I get a `FirebaseUser` from my `onAuthStateChanged` listener. No clue why. Please help!!

Here is the log from the debug console:

```
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): java.lang.NullPointerException: null reference
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.google.firebase.auth.FirebaseAuth.signInWithCredential(Unknown Source:137)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:398)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:107)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at android.app.ActivityThread.main(ActivityThread.java:7470)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#plugins.flutter.io/firebase_auth(30922): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**UPDATE**
I have modified my code to 
```
user = await _auth.signInWithCredential(credential);
user = await _state.auth.currentUser();
```
Still, if I am using a test number I get **null reference** twice.
If I am using a real number I get **null reference** from `auth.signInWithCredential(credential)`
But `state.auth.currentUser();` returns a valid `FirebaseUser`

**Comment by ronaldG19** [comment]
Same here

**Comment by ketulrastogi** [comment]
Same here

**Comment by fyzuladzwan** [comment]
Same here

**Comment by zoechi** [comment]
@ketulrastogi @fyzuladzwan 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by zoechi** [comment]
@HunRex I'd say it's definitely worth a new issue.

**Comment by zoechi** [comment]
I raised priority because it looks a lot are affected (many upvotes in short time).

**Comment by HunRex** [comment]
After work, i try to push a pull request, the problem is not in the firebase_auth libary but in the flutter auth package, in the android codebase. But first i want to test, if it works with real phone numbers too, beause I didn't have a lot of time in the past days, to check it out, but with my fix, the whitelisted numbers works great

**Comment by HunRex** [comment]
@shinyford yeah, now i checked it, and the real time phone authentication throw an sms code expired Platformexception when i try to sign in with the code, but the whitelisted phonenumbers are working for me after the fix. I leave the pull request, because clearly there is something other problem behind this, but I don't think a package with 100% score should work like this. I need the phone auth for my project, and i don't want to make a backend, just because of this

**Comment by shinyford** [comment]
Ah, that's interesting and unexpected. Thanks for the work on this - I need it too.

**Comment by ebastuart** [comment]
@HunRex doesn't work for me. Still have the problem as described.

**Comment by kostasoft** [comment]
Oh no, I was wrong, on one real phone number it works fine, on the other the same error comes out

Made changes to the file FirebaseAuthPlugin.java, as suggested by @HunRex, it all worked.

**Comment by jefioliveira** [comment]
This new version is really flawed. After successfully passing through the flaws mentioned in issue #27128 , I tried to adopt the contour changes suggested here to solve the problems with the signInWithPhoneNumber and even then it did not work properly in my case, I am using a phone Moto Z2 play and a Samsung J7 PRO.

Error Log:
`? E/MethodChannel#plugins.flutter.io/firebase_auth: Failed to handle method call
    java.lang.NullPointerException: null reference
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
        at com.google.firebase.auth.FirebaseAuth.signInWithCredential(Unknown Source:137)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:398)
        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:107)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
        at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
2019-02-05 23:51:45.114 14066-14239/? A/libc: Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 14239 (1.ui)
2019-02-05 23:51:45.226 14721-14721/? A/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
2019-02-05 23:51:46.688 2568-5094/? V/WindowManager: `

Grateful for any suggestions.

**Comment by kostasoft** [comment]
Still not working.
In the FirebaseAuthPlugin.java file there is no code (fix by @HunRex):
```
case PhoneAuthProvider.PROVIDER_ID:
      {
        String accessToken = data.get("verificationId");
        String smsCode = data.get("smsCode");
        credential = PhoneAuthProvider.getCredential(accessToken, smsCode);
        break;
      }
```
Add it there, please!

**Comment by HunRex** [comment]
I commited a pull request with my fix. If anybody have problem after my solution, please check the `getCredentials()` method in Android Studio (you can attach the debugger to a process for breakpoint debugging in studio). See, if the process flow is going into the _PhoneAuthProvider_ case, if not, check the problem

**Comment by jefioliveira** [comment]
> Still not working.
> In the `FirebaseAuthPlugin.java` file there is no code (fix by @HunRex):
> 
> ```java
> case PhoneAuthProvider.PROVIDER_ID:
>       {
>         String accessToken = data.get("verificationId");
>         String smsCode = data.get("smsCode");
>         credential = PhoneAuthProvider.getCredential(accessToken, smsCode);
>         break;
>       }
> ```
> 
> Add it there, please!



> Still not working.
> In the `FirebaseAuthPlugin.java` file there is no code (fix by @HunRex):
> 
> ```java
> case PhoneAuthProvider.PROVIDER_ID:
>       {
>         String accessToken = data.get("verificationId");
>         String smsCode = data.get("smsCode");
>         credential = PhoneAuthProvider.getCredential(accessToken, smsCode);
>         break;
>       }
> ```
> 
> Add it there, please!

@kostasoft try change in pubspec.yaml
this:
`firebase_auth: ^0.8.0+3 `
to
 ` firebase_auth:
    git:
      url: git://github.com/flutter/plugins.git
      ref: b5c224f501357805ce397fb4a883f028ee28b643
      path: packages/firebase_auth/
`
hope it helps

**Comment by marscj** [comment]
I have same problem,  how to fixed?

**Comment by canewsin** [comment]
`firebase_auth: 0.7.0
`
This comment is helpful for people who want to use above version or don't want to use androidX libs(so above is major version available to you for use)
the above version also misses and switch case code so add 

```
case PhoneAuthProvider.PROVIDER_ID:
      {
        String accessToken = data.get("verificationId");
        String smsCode = data.get("smsCode");
        credential = PhoneAuthProvider.getCredential(accessToken, smsCode);
        break;
      }
```
to getCredential method in your FirebaseAuthPlugin.java file
which resides in .pubcache folder and save it
if you dont know where your plugins are stored just open .flutter-plugins file in your project repository and search path for your plugin with it

**Comment by zoechi** [comment]
> if you don't know where your plugins are stored

The easiest way IMHO is to look it up in the `.packages` file in your project directory after running `flutter packages get`/`flutter packages upgrade`

**Comment by AmitJoki** [comment]
@zoechi @canewsin does that solution persist? I do not know if the pub packages will be refreshed from source again during app release and the fix will have been gone.

**Comment by canewsin** [comment]
@AmitJoki since you're modifying low level packages this will persist, if you deleted local cache of packages on .pub folder in flutter you have to modify another time until then, there will be no problem

**Comment by AmitJoki** [comment]
@canewsin I am from the web background, and mostly the packages are downloaded during deployment in the server side (say Heroku). So, I was thinking if that's the way it is done during release and deployment to the store, then the packages will be freshly downloaded, and the fix will be overwritten (since it is only in my local machine).

**Comment by canewsin** [comment]
@AmitJoki 
Then use local package instead of pub package that will suit your need 
```
dependencies:
  plugin1:
    path: ../plugin1/
```

**Comment by anandguptanits** [comment]
setting timeout time to 0 worked for me. thanx @HunRex , i have literally wasted my one day solving this issue, this is a blunder by firebase_auth team.

**Comment by Timbabs** [comment]
For anyone still having this issue do the following:

**Comment by kroikie** [comment]
@ebastuart

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/485. Any further collaboration will be done there.

**Comment by AyushRai3096** [comment]
Has this issue been resolved ?
I'm facing this issue and tried many different things as discussed on this platform. But still I'm facing the same issue.
The signInWithCredential() is not working and returning an error which says:
PlatformException(error, null reference, null)
If anybody has a fix, please provide it here.
Thanks.

**Comment by PriyaSindkar** [comment]
I am surprised that this issue is still unresolved.
Meanwhile, if it's any help to others like me, I found a workaround. If for the said flow, `AuthResult == null`, then I am calling `FirebaseAuth.currentUser()` to recheck signin status, get user details and move ahead.
