### ISSUE TITLE
Changing primarySwatch to Color.black throws exception

### ISSUE THREAD

**Issue by ACFred** [flutter/flutter#27147]
## Steps to Reproduce

1. In VS Code, create a new project
2. Open up an emulator (I'm using Pixel 2 emulator) and 'flutter run'.
3. In the ThemeData widget, change the primarySwatch property from Colors.blue to Colors.black

## Logs

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +4 ms] I/flutter (14913): The following assertion was thrown building MyApp(dirty):
[   +1 ms] I/flutter (14913): type 'Color' is not a subtype of type 'MaterialColor'
[  +20 ms] I/flutter (14913):
[        ] I/flutter (14913): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (14913): more information in this error message to help you determine and fix the underlying cause.
[   +1 ms] I/flutter (14913): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter (14913):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (14913):
[        ] I/flutter (14913): When the exception was thrown, this was the stack:
[   +4 ms] I/flutter (14913): #0      MyApp.build (package:science_mag/main.dart:21:31)
[        ] I/flutter (14913): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
[        ] I/flutter (14913): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
[        ] I/flutter (14913): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[   +1 ms] I/flutter (14913): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] I/flutter (14913): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
[        ] I/flutter (14913): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] I/flutter (14913): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[   +7 ms] I/flutter (14913): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
[   +1 ms] I/flutter (14913): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
[        ] I/flutter (14913): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
[        ] I/flutter (14913): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
[   +1 ms] I/flutter (14913): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
[        ] I/flutter (14913): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
[        ] I/flutter (14913): #14     runApp (package:flutter/src/widgets/binding.dart:756:7)
[        ] I/flutter (14913): #15     main (package:science_mag/main.dart:3:16)
[        ] I/flutter (14913): #16     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
[        ] I/flutter (14913): #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[        ] I/flutter (14913): ════════════════════════════════════════════════════════════════════════════════════════════════════

No issues found.

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.556], locale en-US)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Alec\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

**Comment by jonahwilliams** [comment]
>  type 'Color' is not a subtype of type 'MaterialColor'

What you are looking for a is [MaterialColor](https://docs.flutter.io/flutter/material/MaterialColor-class.html) which includes multiple shades. There are some example palettes on the [Colors](https://docs.flutter.io/flutter/material/Colors-class.html) class, including a grey palette which is probably what you are looking for.
