### ISSUE TITLE
iOS Build Failure - Mac OS 10.13.6 / Xcode 10.1 (10B61) - code shared between windows and mac os via shared folder

### ISSUE THREAD

**Issue by miahcode** [flutter/flutter#27142]
Works fine in Windows with command line tool build but when using the Mac, immediately fails. I tried replacing "c:/Flutter" with my mac install path on one build attempt in there but that didn't work (used Notepad++ in Windows to do the replacement to all files *.*)

Also, after failing initial attempt, I updated to latest flutter on mac, then i tried the doctor, another build but verbosely all down below. My Windows 10 (w/ latest big-ass update, another creative pack or something I had no idea was coming, etc) and Mac flutter versions are identical and most recent.

Thanks,
Miah

[iOS Build Issue - MacOS 10.13.6  Xcode 10.1 (10B61) - Miahcode.pdf](https://github.com/flutter/flutter/files/2799676/iOS.Build.Issue.-.MacOS.10.13.6.Xcode.10.1.10B61.-.Miahcode.pdf)

**Comment by miahcode** [comment]
Oops, I forgot to throw the crash report in there, here it is...
[crash report.pdf](https://github.com/flutter/flutter/files/2799677/crash.report.pdf)

**Comment by zoechi** [comment]
See https://stackoverflow.com/questions/53015610/copy-project-folder-flutter-to-another-computer/53015971#53015971
