### ISSUE TITLE
Why SDK version "2.1.0-dev.9.4.flutter-f9ebf21297" dosen't match required ">=2.1.0 <3.0.0"

### ISSUE THREAD

**Issue by entronad** [flutter/flutter#27148]
## Steps to Reproduce

1. run `flutter packages get` in the `flutter\examples\flutter_gallery` .

## Logs

```
Running "flutter packages get" in flutter_gallery...            
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because flutter_gallery depends on test_core >=0.2.1 which requires SDK version >=2.1.0 <3.0.0, version solving failed.
```

Why the SDK version **"2.1.0-dev.9.4.flutter-f9ebf21297"** dosent match the required **">=2.1.0 <3.0.0"**, since they are both some kind of **2.1.0**?

**Comment by misolab** [comment]
I happened too!

I tried flutter upgrade
**` flutter channel master`
` flutter upgrade`**

flutter version is 'Flutter 1.1.10-pre.197'
I can flutter run

**Comment by entronad** [comment]
@zoechi 
Got it. Thanks!

**Comment by lgfranco** [comment]
> Versions with `-` after the build number (`2.1.0-...`) are pre-release versions and considered lower than the versions without a `-` or with a `+` at this position.
> This conforms with Semantic Versioning.
> 
> You should probably upgrade to a newer Flutter version.

Sorry, but if I am not wrong, this is the newest version of flutter.

**Comment by zoechi** [comment]
@lgfranco 
> Sorry, but if I am not wrong, this is the newest version of flutter.

What do you mean exactly with "this"?

**Comment by shixiaoquan** [comment]
> I happened too!
> 
> I tried flutter upgrade
> **` flutter channel master` ` flutter upgrade`**
> 
> flutter version is 'Flutter 1.1.10-pre.197'
> I can flutter run

Yes I tried, it worked for me
