### ISSUE TITLE
flutter packages pub publish --dry-run giving wrong warning 

### ISSUE THREAD

**Issue by aman-malhotra-1999** [flutter/flutter#27152]
I have already published two plugins for flutter with 100 health so i know what i am asking.
I made the following import in my_plugin.dart file 
`import 'package:meta/meta.dart' `
and i am using `@required` notation for my parameters .
```
BassBoost({@required int audioSessionId}) {
   _initAudioSessionId(audioSessionId);
}
```
```
setEnabled({@required bool enabled}) async {
    Map<String, bool> map = <String, bool>{};
    map.putIfAbsent("enable", () => enabled);
    await _channel.invokeMethod('setEnabled', map);
  }
```
`@required` notation is included in meta.dart file so i have to import it 
because i have some named parameters that are compulsory for the function call to work.
when i am done making the plugin and dry running the plugin for any errors .
it is giving me this warning 
```
Suggestions:
 * line 3, column 1 of lib\bass_boost.dart: This package doesn't depend on meta.
  import 'package:meta/meta.dart';
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Package has 1 warning.
```

if i remove the import of course i am getting compile time error which are not letting me run my app.
because i still have the `@required` notation in my plugin which is required.

why is this happening ??

**Comment by wouterhardeman** [comment]
The `@required` annotation is included in Flutter. ([Required class](https://docs.flutter.io/flutter/meta/Required-class.html)) According to [this StackOverflow post](https://stackoverflow.com/a/49884464) you can use `import 'package:flutter/foundation.dart';`.

**Comment by aman-malhotra-1999** [comment]
It solved the issue . Thanks.

**Comment by zoechi** [comment]
For platform-independent packages add https://pub.dartlang.org/packages/meta to `dependencies` and import `import 'package:meta/meta.dart';`
