### ISSUE TITLE
Enabling platform views on iOS causes image rendering to malfunction

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#27158]
Internal: b/123259425

Steps to reproduce:

Enable platform views on iOS by adding the following to `Info.plist` of a sample app.
```xml
  <key>io.flutter.embedded_views_preview</key>
  <true/>
```

Create a simple app that loads a network image:

```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: ImageWidget(),
    );
  }
}

class ImageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: SafeArea(child: Image.network(<some random image url>)));
  }
}
```

and deploy to an iOS device (it works on the simulator). Most often (but not 100% of the time), you will see garbled pixels similar to this: 

![img_0827](https://user-images.githubusercontent.com/6687929/51807427-70a83f00-223b-11e9-8280-c6381df124a8.jpg)

**Comment by mehmetf** [comment]
[✓] Flutter (Channel master, v1.1.10-pre.177, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.10-pre.177 at /Users/mehmetf/github/flutter
    • Framework revision b028ee142c (3 days ago), 2019-01-24 21:37:56 -0500
    • Engine revision 31c7917179
    • Dart version 2.1.1 (build 2.1.1-dev.2.0 27316cc97b)

**Comment by lukepighetti** [comment]
related? https://github.com/flutter/flutter/issues/27561

**Comment by windvip** [comment]
![image](https://user-images.githubusercontent.com/11665737/52722154-05ee5600-2fe6-11e9-922e-049d9f8c80b8.png)

**Comment by zoechi** [comment]
#21403 looks similar

**Comment by darshankawar** [comment]
Tested this on iPhone 6s (iOS 14) using latest stable version and didn't see the image rendering problem. 

![IMG-0323](https://user-images.githubusercontent.com/67046386/96581552-99b61080-12f7-11eb-924e-2ec2993714e2.PNG)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0

• No issues found!

```

</details>

Closing this as resolved. If you think this was closed by mistake and should've been kept open, please write in comments and I'll reopen.
