### ISSUE TITLE
Implement RenderFractionallyConstrainedBox

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2715]
Please create a widget for RenderFractionallySizedBox. I need to create a Block that takes up no more than 50% of its parent.

**Comment by Hixie** [comment]
There's a FractionallySizedBox already. What you want is a FractionallyConstrainedBox.

**Comment by abarth** [comment]
The current thought is to use CustomSingleChildLayout rather than making dedicated widgets for each permutation.
