### ISSUE TITLE
FirebaseAuth issue

### ISSUE THREAD

**Issue by NightFury0126** [flutter/flutter#27166]
I have upgrade packages to 0.8.0+1 and appeared error message signInWithFacebook and signInWithGoogle is undefined.
How can I solve it?
I have implemented like this
FirebaseUser _fireBaseUser = await _fireBaseAuth.signInWithGoogle(
        idToken: _googleSignInAuth.idToken,
        accessToken: _googleSignInAuth.accessToken);

**Comment by ThinkDigitalRepair** [comment]
@NightFury0126 so what was the solution?
