### ISSUE TITLE
/bin/sh: dart: command not found

### ISSUE THREAD

**Issue by hatjs880328s** [flutter/flutter#27162]
## Steps to Reproduce

1. use flutter v1.0
2. progress PATH 
3. sometimes alert me '/bin/sh: dart: command not found'  sometimes no problem...why ? 

## Logs

[Running] dart "/Users/shanwz/Desktop/Flutters/flutterv1demo/lib/Personcenter/PersonCenterUIV3.dart"
/bin/sh: dart: command not found

[Done] exited with code=127 in 0.006 seconds

```
```

**Comment by kangwang1988** [comment]
In flutter, dart is located in your-flutter-dir/flutter/bin/cache/dart-sdk/bin and you don't need to use it directly, instead, use `flutter command` directly.
If you want to use the dart corresponding to your flutter environment, add `your-flutter-dir/flutter/bin/cache/dart-sdk/bin` to your PATH.

**Comment by mikealfandre** [comment]
This is PATH and I get the same error: /bin/sh: dart: command not found

export PATH="$PATH:/Users/michaelalfandre/Flutter/flutter/bin/cache/dart-sdk/bin"

**Comment by 13104495959** [comment]
if you use macOS Catalina, you must set .zshrc.
@mikealfandre

**Comment by munashe04** [comment]
if on Mac , you can try this
$ brew tap dart-lang/dart
$ brew install dart

**Comment by tjalilpour** [comment]
i add this path,  mypath\flutter\bin\cache\dart-sdk\bin to path of environment variables but still i have same error

**Comment by ALittleNasty** [comment]
if your macOS is 10.15 Catalina, you must set flutter path and  dart path in your .zshrc file, this works for me!

**Comment by rojan108** [comment]
<img width="596" alt="Screen Shot 2020-06-29 at 11 46 01 pm" src="https://user-images.githubusercontent.com/56614817/86013683-c00f2200-ba62-11ea-90c3-ceae5d9a4ec7.png">

can someone help with this, please?

**Comment by ALittleNasty** [comment]
> <img alt="Screen Shot 2020-06-29 at 11 46 01 pm" width="596" src="https://user-images.githubusercontent.com/56614817/86013683-c00f2200-ba62-11ea-90c3-ceae5d9a4ec7.png">
> 
> can someone help with this, please?

you should set dart path in your .bash_profile file like this "export PATH=/Users/ALittleNasty/flutterDevelopment/flutter/bin/cache/dart-sdk/bin:$PATH", if your macOS is 10.15, you also set the dart path in the .zshrc file too!

**Comment by sandeepbol** [comment]
I think you need to update your documentation:

https://flutter.dev/docs/get-started/install/macos

This is confusing for a new user. `flutter doctor` says `Downloading Dart SDK from Flutter engine ...` but it's not found in flutter/bin folder. The master branch does have dart executable inside flutter/bin folder while the stable branch doesn't. This along with the documentation, that suggests us to make sure that flutter and dart executables should be from the same folder by running `which`, leads to a feeling that, may be, setup missed out something.

**Comment by ankush981** [comment]
Exactly as @sandeepbol says, the docs are misleading. `which flutter dart` is supposed to output two different paths but for me, there's only one (the main path where Flutter was installed). I'm hoping this won't cause any problems; for now I'm just on the setup.
