### ISSUE TITLE
Connected Device(No Device Avaliable)

### ISSUE THREAD

**Issue by FurkanAydgan** [flutter/flutter#27175]
Hi Github !
I have a problem with Flutter installing
When I run to `flutter doctor` in Flutter console, I'm getting with this problem.
Can Someone help me about this problem.
```
C:\Users\User>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.30.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by cbenhagen** [comment]
Did you follow the steps described [here](https://flutter.io/docs/get-started/install/windows#android-setup)?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by GreenOpposite** [comment]
I had the same Problem and got it fixed by revoking the USB debugging authorizations in the developer options of my andriod phone.

**Comment by dujianchi** [comment]
got same issue, and my device is avaliable in xcode.and I can not fix it.
![屏幕快照 2019-09-23 上午7 43 06](https://user-images.githubusercontent.com/7309424/65396176-1feee300-ddd6-11e9-9045-fa78062688d6.png)
<img width="887" alt="屏幕快照 2019-09-23 上午7 44 00" src="https://user-images.githubusercontent.com/7309424/65396181-2bdaa500-ddd6-11e9-8b59-eacaa1d32d77.png">
<img width="438" alt="屏幕快照 2019-09-23 上午7 44 35" src="https://user-images.githubusercontent.com/7309424/65396182-2c733b80-ddd6-11e9-9fab-7e4fe8b37896.png">
![屏幕快照 2019-09-23 上午7 44 53](https://user-images.githubusercontent.com/7309424/65396183-2c733b80-ddd6-11e9-8c52-11a4a91916b9.png)

**Comment by dujianchi** [comment]
I got same problem and fixed by this:
rm -rf <flutter_repo_directory>/bin/cache && flutter doctor -v

**Comment by patelkrunal78** [comment]
Maybe [Here](https://icetutor.com/question/flutter-run-no-connected-devices/) You Can Get Your Solution

**Comment by Krunal79-flutter** [comment]
Do You Setup This ?

Set up your Android device
To prepare to run and test your Flutter app on an Android device, you’ll need an Android device running Android 4.1 (API level 16) or higher.

Enable Developer options and USB debugging on your device. Detailed instructions are available in the Android documentation.
Using a USB cable, plug your phone into your computer. If prompted on your device, authorize your computer to access your device.
In the terminal, run the flutter devices command to verify that Flutter recognizes your connected Android device.
Start your app by running flutter run.
By default, Flutter uses the version of the Android SDK where your adb tool is based. If you want Flutter to use a different installation of the Android SDK, you must set the ANDROID_HOME environment variable to that installation directory

Founded At [Here](https://icetutor.com/question/flutter-run-no-connected-devices/)

**Comment by collinsbigomba** [comment]
![1585249370626132333935725138727](https://user-images.githubusercontent.com/49558020/77686171-92bb5f80-6fad-11ea-9248-bb015bc17a07.jpg)
Help please

**Comment by GreenOpposite** [comment]
Could you run `flutter doctor -v` and paste the result here?

**Comment by aramachandran7** [comment]
Hi guys-  I'm also having trouble setting up flutter for vscode for Windows 10. 

I followed all the official flutter documentation instructions on the windows setup for flutter (and android studio SDKs) to be used with vscode (wasn't able to choose hardware acceleration option for the Android Virtual Device emulator, but otherwise all other steps were followed to the T). **I am getting the same results  as in the post all the way at the top** when running `flutter doctor` , and also tried deleting all the cache in the bin in the flutter directory and rerunning `flutter doctor -v` as well, to no avail.  

result of `flutter doctor -v`
![image](https://user-images.githubusercontent.com/31751624/77726162-454aec80-6fc5-11ea-80ae-9266549443b4.png)

image of Android Studio Android Virtual Device Manager
![image](https://user-images.githubusercontent.com/31751624/77726280-8fcc6900-6fc5-11ea-89eb-810646b23185.png)

Anyone got any ideas? Do I even need to have a connected device? 
Thanks! :)

**Comment by collinsbigomba** [comment]
![15853816535615049196862143558789](https://user-images.githubusercontent.com/49558020/77818194-9a7c2080-70e1-11ea-8b0c-ccf8e7794b93.jpg)
@GreenOpposite

**Comment by aramachandran7** [comment]
resolved! I had everything setup correctly - however, I just needed to have the AVD Pixel emulator up and running while running the `flutter doctor` command - then, it recognized that it was a connected device. :)

However, soon after, it crashed my computer - any tips on getting the device emulator to run more smoothly /  not take up too much ram / processing power?
