### ISSUE TITLE
I want video clips

### ISSUE THREAD

**Issue by wz1228556153** [flutter/flutter#27172]
I want to edit videos. For example, my videos are one minute long. I want to edit 10 seconds of them. Thank you

**Comment by zoechi** [comment]
This is unlikely to be added as core Flutter feature.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

You can upvote https://stackoverflow.com/questions/54018792/video-editor-in-flutter-using-dart for it to get more attention.

**Comment by zoechi** [comment]
Duplicate of #27171
