### ISSUE TITLE
SliverAppBar loses elevation at top of scroll?

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#27203]
At top of scroll, there is no elevation for SliverAppBar

![img_8cab0c27cfaa-1](https://user-images.githubusercontent.com/666539/51869864-e2f24f80-231f-11e9-99ef-bfe5db50b236.jpeg)

During scroll progress, there is elevation for SliverAppBar

![img_8cab0c27cfaa-2](https://user-images.githubusercontent.com/666539/51869875-ef76a800-231f-11e9-8825-f88d2cedf82d.jpeg)

It does not look correct to me, perhaps someone can confirm.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by Nico04** [comment]
I've got the extact same issue

**Comment by georgeherby** [comment]
I had this but realised there is a flag that needs to be set `forceElevated: true` as this defaults to false
https://api.flutter.dev/flutter/material/SliverAppBar/forceElevated.html

```
SliverAppBar(
                  forceElevated: true,
                  title: Text(state.title),
                  elevation: Theme.of(context).appBarTheme.elevation,
                  backgroundColor: Theme.of(context).appBarTheme.color,
                ),
```

**Comment by TahaTesser** [comment]
Hi @lukepighetti 
Does this [comment](https://github.com/flutter/flutter/issues/27203#issuecomment-587545287) resolves this issue? 
Thank you

**Comment by VladyslavBondarenko** [comment]
@lukepighetti 
I hope it's solved, closing,
comment please if it's not so and I'll reopen the issue
Thank you
