### ISSUE TITLE
Camera Plugin Record Video orientation issue

### ISSUE THREAD

**Issue by magnocasmor** [flutter/flutter#27201]
I have an application that uses the `camera` and `video_player` for taking pictures/record videos and upload to firebase storage. Then, I download from firebase and reproduce by using `Image.file` or `VideoPlayer`, depending on the file. My application have screen orientation locked by the setting `SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])`. But, I have some issues:

- Recording a video from Iphone in portrait or landscape, generates a mp4 file that follows the lock orientation config, playing in Android and Iphone correctly.
- Recording a video from Android in portrait mode, generates a mp4 file that plays in the correctly orientation on Android. But, rotates 90 CCW on Iphone.
- Recording a video from Android in landscape mode, generates a mp4 file that plays 90 CCW in both Android and Iphone.

I've researched in many issues of GitHub and many of this relate some EXIF issue. Then, I use this site [https://www.get-metadata.com](url) to extract the metadata of each mp4 file and I've gotten this results:

- Video from Iphone in portrait:

![image](https://user-images.githubusercontent.com/45497497/51863778-b0952200-2320-11e9-93ce-fe5d2e35f230.png)

- Video from Iphone in landscape:

![image](https://user-images.githubusercontent.com/45497497/51863838-d8848580-2320-11e9-9c61-8e2baafc650d.png)

- Video from Android portrait:

![image](https://user-images.githubusercontent.com/45497497/51863900-036ed980-2321-11e9-88ca-a6f9a799eaeb.png)

![image](https://user-images.githubusercontent.com/45497497/51863933-1da8b780-2321-11e9-9c01-1635dbd5825a.png)

- Video from Android landscape:

![image](https://user-images.githubusercontent.com/45497497/51863999-416bfd80-2321-11e9-943f-5a38bfc2b735.png)

I noticed that Iphone's video files contains `Rotation 0` and the same width and height (height > width) in both modes. In Android's video files, landscape mode contains `Rotation 0` but width and height different of the portrait mode being width > height. In portrait mode the result contains `Rotation 90`. This mode is the only one that have TAGS and SIDE DATA LIST sessions having `Rotate 90` and `Rotation -90`, respectively.

Taking pictures with the camera and showing with `Image.file` using both devices, in portrait mode, the picture always comes with the correct orientation. However, in landscape mode the picture comes rotated in 90 CCW.

This is my `flutter doctor -v`
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G4015, locale pt-US)
    • Flutter version 1.0.0 at /Users/workeduc/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/workeduc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/workeduc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Moto G                  • 0423012922                               • android-arm • Android 7.1.2 (API 25)
    • iPhone de Desenvolvedor • 4346ae62097024ea99d0bfbee86b849efdc5fdab • ios         • iOS 12.1.3
```
I'm using the `camera` plugin `0.3.0` and `video_player` `0.8.0`, any ideas for solving this issue?

**Comment by wouterhardeman** [comment]
It seems this is because `SystemChrome.setPreferredOrientations` sets the preferred orientation on the Android `Activity`. In Flutter there only is one `Activity` because Flutter renders the app in one view. 

The camera service that is launched does not know the preferred orientation that was set earlier. Instead it uses the actual rotation of the device.

**Comment by magnocasmor** [comment]
I believe that the orientation (locked or not) arent the problem, because if I remove `SystemChrome.setPreferredOrientations` line, the Camera Preview rotates if I change the orientation, and taking a picture on this orientation. But I don't want this, I want to take or record image like is showing in the Camera Preview.

**Comment by wouterhardeman** [comment]
@magnocasmor Try taking a picture in landscape on Android, but turn your screen to the right instead of the left and check what rotation appears in the meta. Does it still say 90CCW or is it 90CW now?

**Comment by magnocasmor** [comment]
@wouterhardeman rotate information don't appears in pictures, this is a problem?
![image](https://user-images.githubusercontent.com/45497497/51914196-0916fe80-23b7-11e9-84e8-ff23ce6c01fc.png)

**Comment by wouterhardeman** [comment]
@magnocasmor Sorry, I meant a video.

**Comment by magnocasmor** [comment]
@wouterhardeman This is the result of the videos recorded in landscape:
- To right
![image](https://user-images.githubusercontent.com/45497497/51929812-dfba9a80-23d7-11e9-8a8c-f73d0d3ffe9c.png)

![image](https://user-images.githubusercontent.com/45497497/51929839-ec3ef300-23d7-11e9-90bd-492d6fa41c5d.png)
- To left
![image](https://user-images.githubusercontent.com/45497497/51929794-d3364200-23d7-11e9-90a1-16f14d841fc2.png)

In the case "Video from Android landscape" mentioned above, I recorded video rotated to left and the values don't changed

**Comment by quentinleguennec** [comment]
Hi @magnocasmor .
I added a fix for video orientation metadata when recording a video with the camera plugin. The PR is this one: https://github.com/flutter/plugins/pull/1452
I also added a fix to the video_player. The PR is here: https://github.com/flutter/plugins/pull/1451
Please don't hesitate to have a look at the PRs and leave comments or suggestions to push the review process.

**Comment by AbhishekDoshi26** [comment]
I feel this can be related to #80881 and will be solved in PR: https://github.com/flutter/plugins/pull/3970

**Comment by navaronbracke** [comment]
It seems that it also has the wrong orientation on landscape left. The video is rotated 180° less than it should be.

**Comment by navaronbracke** [comment]
I had a quick look at the bug itself. Apparently the switch case for `LANDSCAPE_LEFT` and `LANDSCAPE_RIGHT` are flipped? The angle for `LANDSCAPE_LEFT` should be 270 and for `LANDSCAPE_RIGHT` it should be 90. Then the source video has the correct orientation.
