### ISSUE TITLE
* Error running Gradle:

### ISSUE THREAD

**Issue by eddyizm** [flutter/flutter#27213]
## Steps to Reproduce

1. create flutter hello_world app
2. tried to run - flutter -d MYDEVICEID run
3. Resolving dependencies

## Logs

```
flutter -d ZY224KSLJJ run
Launching lib/main.dart on moto x4 in debug mode...
Initializing gradle...                                       0.7s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\eddyizm\Source\Repos\flutter_app\hello_world_flutter\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)


FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.10.2/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
  Command: C:\Users\eddyizm\Source\Repos\flutter_app\hello_world_flutter\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.
```

```
flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\eddyizm\AppData\Local\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\eddyizm\AppData\Local\Android
    • Java binary at: C:\Program Files (x86)\Java\jdk1.8.0_101\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.27.0)
    • VS Code at C:\Users\eddyizm\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] Connected device (2 available)
    • moto x4                   • ZY224KSLJJ    • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 8.1.0 (API 27) (emulator)

Flutter config 

Settings:
  gradle-dir: C:\src\Gradle\bin
  android-sdk: C:\Users\eddyizm\AppData\Local\Android\sdk

```

**Comment by Luqman2088** [comment]
M having the same issue.What should I do?

**Comment by smchinna** [comment]
@Luqman2088 and @eddyizm, Might be this issue occur gradle installation problem. To install android studio and  gradle. May be it will resolve your problem.

**Comment by zoechi** [comment]
> Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

Seems to be caused by not enough memory.

**Comment by rakeshlanjewarwork** [comment]
try this solution

https://stackoverflow.com/a/31760855/7416454

**Comment by eddyizm** [comment]
@smchinna Not a very thoughtful response. If you looked at the logs you could see that flutter doctor showed everything in working order and my flutter config pointing to the gradle install. You also do not need to install Android Studio in order to run and build flutter apps. 

@zoechi Thanks for pointing that out. That helped isolate the problem even though that was not truly the issue. 

@rakeshlanjewarwork stackoverflow for the win. Thanks!
 My issue was in 

/hello_world_flutter/android/gradle.properties
`#org.gradle.jvmargs=-Xmx1536M`

Added the pound thanks to the link comments stating that one user had to just delete the line altogether. 

[https://stackoverflow.com/a/41426252](url)

**Comment by Luqman2088** [comment]
After flutter reinstallation my issue was resolved.

**Comment by AndyKgotatso** [comment]
1. one solution that worked for me was to remove from 
in gradle.properties, you can even delete

`org.gradle.jvmargs=-Xmx1536m`

such lines or comment them out. Let android studio decide for it. When I ran into this same problem, none of above solutions worked for me. Commenting out this line in gradle.properties helped in solving that error.

2. And then ensure **JDK1.8.0_261** 
 - is installed on your machine , Otherwise it will use the JRE to run Gradle(which is wrong)

**Comment by sandigul** [comment]
> `#org.gradle.jvmargs=-Xmx1536M`
> 
> Added the pound thanks to the link comments stating that one user had to just delete the line altogether.
It fixed the issue for me.
https://github.com/eddyizm
