### ISSUE TITLE
Android X Migration changes wasn't reverted for firebase_auth ^0.8.0

### ISSUE THREAD

**Issue by dev-whiteflag** [flutter/flutter#27210]
## Main
Migrate to AndroidX broke firebase_auth for older versions of Android (ex. 6.0);
"Revert AndroidX changes for 1.0.0 plugins (flutter/plugins#1127)" didn't include firebase_auth.
I can't migrate to Android X, because it doesn't support older android versions.

1. Update firebase_auth to ^0.8.0.
2. Gradle fails to compile.

## Logs
Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
```
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:638: error: cannot find symbol
  private void reportException(Result result, @Nullable Exception exception) {
                                               ^
  symbol:   class Nullable
  location: class FirebaseAuthPlugin
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:550: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:569: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:587: error: cannot find symbol
    public void onComplete(@NonNull Task<SignInMethodQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.GetSignInMethodsCompleteListener
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:186: error: cannot find symbol
                      public void onComplete(@NonNull Task<AuthResult> task) {
                                              ^
  symbol: class NonNull
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:445: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:499: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
Note: C:\Google\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.0\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by zoechi** [comment]
I didn't closely follow the AndroidX migration issue but I think you need to remove `^` because of plugins published with wrong version numbers

```yml
  firebase_auth: 0.8.0
```
(`0.8.0` or whatever the last version was working without AndroidX) to prevent getting newer versions that are considered non-breaking but break because of mentioned mistake.

**Comment by dev-whiteflag** [comment]
```
name: preciso_tecnologia_mobile
description: Aplicativo Oficial da Preciso Tecnologia para uso em Campo.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
Before posting this Issue, I read about the migration issue and changed the version to 0.8.0; But this version is also affected by the Android X Issue.

**Comment by zoechi** [comment]
Then use the last working version. Probably `0.7.0`

**Comment by dev-whiteflag** [comment]
Okay, I thought there was no such version as it is quoted only in the changelog and not in the versions tab of pub.dartlang.org. I hope this issue is resolved soon.

**Comment by zoechi** [comment]
I see what you mean. I only checked in the changelog.
I guess you need to use `0.6.6` then.
`0.6.7` and `0.7.0` were never published to pub.dartlang.org.

@mklim can you please fix the changelog to combine the entries of `0.6.7` `0.7.0` and `0.8.0` under `0.8.0`

**Comment by zoechi** [comment]
@dev-whiteflag 

> I'm hesitant in using 0.6.6 because of the breaking changes introduced in the 0.7.0.

Did you use a Git dependency previously?
If not `0.6.6` should be safe, because there was no later version published that does not depend on AndroidX

**Comment by dev-whiteflag** [comment]
In the old code of the same project, I had a git dependency but the new design doesn't need it any more.
I'm going to stick with `0.6.6`, because Android X does not support older versions of Android, `6.0 Marshmallow` for example, the most used in my country. Thanks for the help with this Issue.

**Comment by zoechi** [comment]
Thanks for the update!

**Comment by mklim** [comment]
I've uploaded `0.7.0`, that should have been published already. However it looks like the `pubspec.yaml` was never updated for `0.6.7`, so there's no way to publish that. Filed #27247 to update the changelog.

@dev-whiteflag No pressure to migrate, but AndroidX does provide backwards compatibility with all the same versions of Android as the equivalent Android support libraries. It requires a compile time SDK of 28, but you should be able to build apps for the exact same minimum runtime sdk versions as before. [More info here](https://developer.android.com/jetpack/androidx/). 

> Like the Support Library, AndroidX ships separately from the Android OS and provides backwards-compatibility across Android releases. AndroidX fully replaces the Support Library by providing feature parity and new libraries.

**Comment by kroikie** [comment]
@dev-whiteflag

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1118. Any further collaboration will be done there.
