### ISSUE TITLE
firebase_analytics 2.0.0 analytics.logEvent() Not showing up in Dashboard

### ISSUE THREAD

**Issue by sunojvijayan** [flutter/flutter#27229]
## Steps to Reproduce

1. Added the plugin.
2. called this - 
```dart
await analytics.logEvent(name: "Home Page Loaded", parameters: <String, dynamic>{});
```
3. It shows no errors. But I don't see the event in dashboard.
4. However `analytics.setCurrentScreen()` works fine and I am able to see in in dashboard.

## Logs

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-MY)
    • Flutter version 1.0.0 at /Users/sunojvijayan/Documents/Flutter/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sunojvijayan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
```

**Comment by sunojvijayan** [comment]
I don't think thats the problem because I have already waited 4 days.

**Comment by sunojvijayan** [comment]
Really Sorry About this. I found the Issue. 

`await analytics.logEvent(name: "Home Page Loaded", parameters: <String, dynamic>{});`

There cannot be any space in the name. So changed it to "Home_Page_Loaded" and everything worked just fine. 

For those interested I ran the application on an Android device and checked the Logcat in Android studio. It clearly showed that there cannot be any space and that the event was not logged. 

Just a suggestion. Maybe it would be nice if flutter also showed that the event was not logged and the reason.

**Comment by rakeshlanjewarwork** [comment]
@zoechi ,Please close the issue.

**Comment by kroikie** [comment]
@sunojvijayan

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/481. Any further collaboration will be done there.

**Comment by aeoriwnd** [comment]
Still an issue for me, using analytics 5.0.2. Any updates?
