### ISSUE TITLE
Consider hoisting MaskFilter up to being VM-only objects

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2722]
Right now ColorFilter and MaskFilter are relatively simple objects in terms of how we create them (e.g. ColorFilter is just two ints), but they are currently C++-hosted objects. We could move them to pure-Dart objects and then use the technique we have for e.g. TextStyle or Paint to transfer the data to C++.

**Comment by abarth** [comment]
ColorFilter is done.
