### ISSUE TITLE
Support for running manual layout passes

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#2723]
There are now (at least) two experimental efforts going on that depend on analyzing the results of a layout pass. Currently the most straightforward way to do this is to run the whole rendering pipeline and then look at the results afterwards. This means pushing pixels to the screen.

It would be more efficient if we had a way to run the layout pass manually, perhaps by using some kind of offscreen context to prevent screen artifacts. If the layout pass is expensive we might also want to run it asynchronously, although that is a somewhat lesser requirement.

This request doesn't necessarily mean adding more public API to support this use case; if there is a recipe for doing this using the current APIs (e.g. by creating a custom WidgetFlutterBinding), that could be sufficient, even if the process is complex or cumbersome.

**Comment by krisgiesing** [comment]
CC @rtsuk

**Comment by krisgiesing** [comment]
@Hixie since you helped me do this sort of thing for unit tests, is there a similar process we could use in a full app?

**Comment by abarth** [comment]
We chatted about this in person and I think we have a plan forward here.  The idea is to turn `AbstractNode`'s `attached` boolean into an "owner" pointer and have that owner accumulate the layer/painting/etc dirty lists.  Then we can flush the layout for those render object separately from the layout of all the on-screen render objects.

**Comment by krisgiesing** [comment]
@emshack

**Comment by krisgiesing** [comment]
I've made the changes we discussed, but there's one sticky point here:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/box.dart#L394

This assertion doesn't have any obvious mapping in the world where there's more than one layout pipeline. The enclosing class doesn't have any context that I can use to establish which layout pipeline should be in progress. I don't want to add a field to that class since it's used a lot, but the alternatives also seem awkward: 1) move the assert into the calling code; 2) pass a context down into the method that's only used for the assert; 3) remove the assert

Any opinions?

**Comment by abarth** [comment]
That assert is meant to be just a rough "is this sane" check.  Maybe we should have a debug bool for whether we're doing layout anywhere in the system?

**Comment by Hixie** [comment]
I wouldn't worry too much about that assert.

**Comment by krisgiesing** [comment]
#2839 was only part 1 of the set of changes needed - reopening.
