### ISSUE TITLE
error when building release apk ( debug works fine )

### ISSUE THREAD

**Issue by genjm** [flutter/flutter#27239]
When trying to build a 'release apk' for my application, the build process crashes, as below:

**> flutter build apk --release
> Initializing gradle...                                       1.4s
> Resolving dependencies...                                    1.7s
> Gradle task 'assembleRelease'...
> registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
> registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
> ../../third_party/dart/runtime/vm/compiler/frontend/kernel_translation_helper.cc: 1475: error: vm.inferred-type.metadata metadata is allowed in precompiled mode only
> Dart snapshot generator failed with exit code -6
> Snapshotting exited with non-zero exit code: -6
> 
> Gradle task 'assembleRelease'... Done                        3.1s
> Gradle task assembleRelease failed with exit code 1**

I have followed the instructions for 'Preparing an Android App for Release'.

I have tried cleaning & re-running but the error is always the same, the application works perfectly fine for debug or when running on a connected physical device.

I have been searching for the past half hour & can't find any issues related to the above error.

Any pointers would be greatly appreciated?

Thanks

**Comment by jelenalecic** [comment]
proguard?

**Comment by genjm** [comment]
Yes, but when I removed the references to proguard, it still resulted in the same error.

Although for peace of mind, I'll try it again now.

**Comment by genjm** [comment]
Although it wasn't proguard, the comment did remind me that I enabled obfuscation a few days ago so I checked the 'gradle.properties' file & I'd missed one of the '-' from the setting!

So I had:

extra-gen-snapshot-options=-obfuscate

When it should have been:

extra-gen-snapshot-options=--obfuscate

Although I've basically fixed it myself, I would never have thought to check that without the reply above, so huge thanks. :)
