### ISSUE TITLE
setPreferredOrientations not working in iPad 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#27235]
### Steps to reproduce:

```dart
void main() => runApp(MyPage());

class MyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]); // doesn't seem to work in iPad
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("AppBar")),
        body: Text("Text"),
      ),
    );
  }
}
```
You can still rotate your iPad. However it works fine in iPhone. 

----

### Flutter Doctor 
```
[✓] Flutter (Channel beta, v1.0.1-pre.1, on Mac OS X 10.14 18A389, locale en-GB)
    • Flutter version 1.0.1-pre.1 at /flutter
    • Framework revision 2f60afca7a (4 weeks ago), 2018-12-29 14:11:09 +0530
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/chocolate/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPad Pro • b1910da0802b3d6e38b23a455f95878f0ca87733 • ios • iOS 12.0.1
```

**Comment by dark-chocolate** [comment]
Thanks @zoechi , I did read that thread before creating a new issue here. However that is related to automatically setting orientation and mine one is a bug which only occurs in iPad.

**Comment by zoechi** [comment]
Rotating like mentioned in #13238 also does not fix the orientation on your iPad?

**Comment by dark-chocolate** [comment]
@zoechi Yes, it doesn't lock the orientation. I can rotate from landscape to portrait and vice versa for the whole day. As I said before, it works as expected in iPhone.

**Comment by SergioBernal8** [comment]
I manage to fix that problem with this:

**First**, add this code to the appDelegate.swift in the Runner project

`override func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask(arrayLiteral: [UIInterfaceOrientationMask.landscapeLeft,UIInterfaceOrientationMask.landscapeRight]);
    }`

**Second** Check that  "Requires full screen"  is enabled under Targets->Runner->Deployment info

![Screen](https://user-images.githubusercontent.com/41064984/58715489-96318a80-838c-11e9-975d-9a87d17426e5.png)

> Please, take into account that I'm not deploying for iPhone and I have not tested that in iPhone, even though, I think it also should work in iPhone.

**Comment by dark-chocolate** [comment]
@SergioBernal8 Thanks for your solution, I haven't tried it yet though, but I want Flutter team to solve the bug instead of any workaround.

**Comment by sjoenk** [comment]
+1
I'm having the exact same issue. It's working fine on iPhone but on iPad you can rotate in all directions.

**Comment by dark-chocolate** [comment]
@sjoenk Please show your +1 support by putting a thumbs up to the issue, that adds more priority to the issue.

**Comment by 0xVesion** [comment]
> I manage to fix that problem with this:
> 
> **First**, add this code to the appDelegate.swift in the Runner project
> 
> `override func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask { return UIInterfaceOrientationMask(arrayLiteral: [UIInterfaceOrientationMask.landscapeLeft,UIInterfaceOrientationMask.landscapeRight]); }`
> 
> **Second** Check that "Requires full screen" is enabled under Targets->Runner->Deployment info
> 
> ![Screen](https://user-images.githubusercontent.com/41064984/58715489-96318a80-838c-11e9-975d-9a87d17426e5.png)
> 
> > Please, take into account that I'm not deploying for iPhone and I have not tested that in iPhone, even though, I think it also should work in iPhone.

That actually fixed it for me. Only thing is that i now have to run my app in fullscreen. That's fine for my use case but could be annoying for others.

**Comment by lwky** [comment]
We fixed it by setting UISupportedInterfaceOrientations in Info.plist
this value is set by the DeviceOrientation checkbox in your xcode project, but beneath it is:
<key>UISupportedInterfaceOrientations~ipad</key>
with separate values for iPad.

in our case, setting both to
<array>
	<string>UIInterfaceOrientationPortrait</string>
</array>
resulted in all iOS devices remaining in portrait mode.

**Comment by DanTup** [comment]
Docs were updated by #40743.

**Comment by renanyoy** [comment]
just need to check "full screen" option after
```
SystemChrome.setPreferredOrientations();
```
works as expected, and can be dynamically changed.

**Comment by SinoMiles** [comment]
@dark-chocolate  did you fix  the problem?i'm using  ipad too,can't lock orientation.

**Comment by matpag** [comment]
I've finally fixed it by manually editing the `info.plist` file.

Open it with a text editor and change the supported orientation values you find with those:
```
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
```
The first block is for IPhone, the second one for IPad
