### ISSUE TITLE
VScode auto import

### ISSUE THREAD

**Issue by lkhgvsuren** [flutter/flutter#27230]
I am using vscode and I can't find a way to auto import packages and classes. For example, If I need to use http get request do I only have to type import 'package:http/http.dart' manually?

**Comment by zoechi** [comment]
Duplicate of https://github.com/dart-lang/sdk/issues/25820

**Comment by lkhgvsuren** [comment]
@zoechi but I can't find the answer.

**Comment by zoechi** [comment]
The answer is that this currently does not work as you want and you can subscribe to the linked issue to get updates.
