### ISSUE TITLE
Build a simple pub-sub API (streams?) for communicating with the platform

### ISSUE THREAD

**Issue by bbozo** [flutter/flutter#27232]
A pub-sub pattern is currently possible to implement via a combination of `MethodChannel` & `EventChannel` as demonstrated in [the platform_channel example](https://github.com/flutter/flutter/blob/master/examples/platform_channel/android/app/src/main/java/com/example/platformchannel/MainActivity.java), but the API results in a bit of a messy code base - both in the platform and in the Flutter code - you create multiple objects in both platforms and catch events in anonymous classes living in different scopes.

Would it be possible to implement, for example, [a 2-way stream-based API](https://www.dartlang.org/tutorials/language/streams#receiving-stream-events) for communicating with the platform?

Streams/event buses are well understood and provenly result in elegant manageable code, there are also multiple libs to lean on both in the platform world and in the Flutter space to make this experience really nice (RxJava, RxDart, RxSwift, ...) - it'd literally allow the same patterns to be used on both sides of the fence making matters very easy to compare & understand.

Feature request inspired by investigation following my [SO question on the subject](https://stackoverflow.com/questions/54418677/how-to-set-up-a-publish-subscribe-channel-between-a-flutter-app-and-its-android)

**Comment by jonahwilliams** [comment]
We're not going to do this. Instead we're investing in ffi/jni as the future of platform interop, removing the need for async messages
