### ISSUE TITLE
The codec API should report better errors.

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#27249]
Currently any error that happens while decoding an image in `codec.cc` is reported back to the Framework as a null return value, which is translated to an `operation failed` exception by [_futurize](https://github.com/flutter/engine/blob/57b0afaf374326a856183f1866ddacc4af0a7d6d/lib/ui/painting.dart#L3967). This isn't very useful when debugging image decoding issues (e.g #26757).

We should refactor the Codec API to report back meaningful errors.

**Comment by jonahwilliams** [comment]
We did this
