### ISSUE TITLE
'FlutterPlatfomView' on iOS don't have a 'dispose' method

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#27240]
On Android you must inherit the `PlatformView` interface, which has a `dispose` method that is called when the `AndroidView` is destroyed on the Dart side.

```java
public interface PlatformView {
    View getView();

    void dispose();
}
```

But on the iOS part, you must inherit `FlutterPlatformView` that has **no** `dispose` method.
This method is important for us developers to release some unnecessary resources when the view is destroyed. 

```objective-c
@protocol FlutterPlatformView <NSObject>
/**
 * Returns a reference to the UIView that is wrapped by this FlutterPlatformView.
 */
- (UIView*)view;
@end
```

-> A Workaround for now is to use the `MethodChannel` to tell the iOS platform that the view is no longer needed.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment]
Looks related to #25828

**Comment by shinayser** [comment]
@zoechi Actually the #25828 is related to the Dart side. The issue I am reporting is just a problem with the FlutterPlatformView protocol for iOS. 
But if you think they are related feel free to close this issue.

**Comment by zoechi** [comment]
@shinayser they are linked now. I'll leave it to the maintainer to close.

**Comment by hoanglm4** [comment]
When FlutterPlatformView support 'dispose' method ?

**Comment by amirh** [comment]
On iOS you can do the same by overriding the object's dealloc method.

**Comment by ruirodrigues-eyenov** [comment]
`dealloc` or `deinit` does not really work. Any alternative?
