### ISSUE TITLE
firebase_auth 0.6.7 doesn't exist

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#27247]
The changelog was updated to include a 0.6.7 version in flutter/plugins#775, but the `pubspec.yaml` was never updated to match so no 0.6.7 version can ever be published onto pub. `0.6.7` and `0.7.0` should probably be combined in `CHANGELOG.md`.

/cc @collinjackson

**Comment by kroikie** [comment]
@mklim

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/477. Any further collaboration will be done there.
