### ISSUE TITLE
crashy doesn't build - gives version solving error re: dart SDK

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#27248]
Crashy's readme.md links to file the bug here.
Gives error 
```
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because crashy depends on test >=0.12.0-beta.3 <1.3.0 which requires SDK version >=1.8.0 <2.0.0-∞, version solving failed.
```

**Comment by zoechi** [comment]
What is "Crashy"?
Looks like you need to update `pubspec.yaml` to something like

```yml
environment:
  sdk: ">=2.1.0-dev <3.0.0"
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Can you please elaborate what steps exactly lead to this error?

**Comment by neiljaywarner** [comment]
@zoechi Crashy is here
https://github.com/flutter/crashy and it's readme.md sent me to file issue here; i realize the fix is probably easy exactly as you put above, but i felt it might be helpful that i filed the bug.

crashy gets referred to from many other places so it should probably be solid.
I'm really just trying to figure out how to get to flutter-crashlytics-good-enough-for-production-simple-use-case. (add2app scenario, but i'm not sure yet if that matters)
Thanks

**Comment by zoechi** [comment]
> Because crashy depends on test >=0.12.0-beta.3 <1.3.0

Confused me because https://github.com/flutter/crashy/blob/master/pubspec.yaml#L10
says different.

Definitely a valid issue. Thanks for reporting.

**Comment by TahaTesser** [comment]
Hi @neiljaywarner 
Given the mentioned issue is closed
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
