### ISSUE TITLE
iOS app are alway in low fps

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#27244]
Does there any plan to optimize on iOS platform? now I creating a simple chat app, but the animation between swipe back and forth are not fluent as native one. it's really bad at user experiences.

**Comment by zoechi** [comment]
Can you elaborate? Perhaps capture a video that demonstrates the issue?
is this with your custom code or also with the Gallery?
I assume you tested with a release (or profile) build?

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by jinfagang** [comment]
Here is the full:

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.3 18D32a, locale en-CN)
    • Flutter version 1.0.0 at /Users/jintian/development/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/jintian/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Volumes/xs/MacApps/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10L176w
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Tian’s iPhoneX • 1705b000797409b9241042214b01b7f1db2d5228 • ios • iOS 12.1.2
    • iPhone 5s      • B4C39936-46A1-47B3-886A-1181FEC209F9     • ios • iOS 12.0 (simulator)
```

**Comment by zoechi** [comment]
What about release/profile build and reproduction?
Is this only the first time or also on subsequent swipes?

**Comment by jinfagang** [comment]
@zoechi  It's sometime happen, but most of time can not notice the tiny loss of fps. I think the flutter engine on iOS is not as fluent as android. Still some improvement?

BTW, why the textfield can not change height?

<img width="309" alt="image" src="https://user-images.githubusercontent.com/21303438/51921412-541a2b80-2422-11e9-8b31-ed101f81a110.png">
I can change the width but not the height.

Which means the touch area are small, hard to make keyboard pop out

**Comment by jinfagang** [comment]
<img width="231" alt="image" src="https://user-images.githubusercontent.com/21303438/51921537-8fb4f580-2422-11e9-9644-2878ada46a62.png">

**Comment by zoechi** [comment]
> BTW, why the textfield can not change height?

Is this in any way related to this issue?

**Comment by zoechi** [comment]
> @zoechi It's sometime happen, but most of time can not notice the tiny loss of fps. I think the flutter engine on iOS is not as fluent as android. Still some improvement?

It's good that you created the issue but without a way for us to have a measurement point that allows us to validate that the issue is fixed, there is not much anybody can do.

**Comment by jinfagang** [comment]
All right... always meaningless answer, nothing help with my question

**Comment by AtixD** [comment]
@kangwang1988  
It feels like ios platform does not work as smoothly as an android, as I understand it is the specificity of flutter engine?

**Comment by jinfagang** [comment]
@kangwang1988 @AtixD  iOS legging are happend when quick move forward and back between pages. But native does not, I will update a video to show this legging
