### ISSUE TITLE
flutter/plugins needs a better releasing process

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#27258]
Releasing plugin updates has a few surprise gotchas right now. We could use at least some docs on it, maybe a better process.

- [x] ~~No docs or formalized sanity checks on when the packages should be released. (Presumably after CI runs on the squashed master commit and it's green? Should there be any other manual checks run, ie to make sure the version bump matches the scale of the change?) See #27106.~~
- [ ] No automated reminders to publish a package, so it's possible to forget to publish a package entirely. See #27247 and #26374. 
- [x] ~~pub publish publishes literally everything in the directory, not just what's tracked in git, so maintainers need to make sure their local directory is completely clear. (There are some cases where this is *especially* dangerous. `in_app_purchase` has an example app that needs unique release signing information stored locally to work. This is added to the `.gitignore` but would still be uploaded by pub if present.)~~
- [X] ~~Sometimes plugins are in a state where they should not be published (`in_app_purchase` is currently in this state while it's under intense development), and right now there's no clear way that these are marked.~~
- [x] ~~We probably should warn against releasing things closer to the weekend and have some suggested manual steps on how to monitor the plugin after rollout.~~

_ETA 11/25/19_: 

- [ ] No form of error monitoring, so it's possible to push a release and realize belatedly that it had some critical bug.

**Comment by amirh** [comment]
One thing I would like to include in such a process, for breaking changes, is a step where we evaluate what the breakage would look like for an app developer. Maybe we should paste a sample error in the PR description.

We should then evaluate whether the error is informative enough, or do we want to take some extra steps to make sure a better error message is provided (e.g for upgrades that result in a vague Gradle error).

https://github.com/dart-lang/pub/issues/2038 might be a good tool for us to make up for bad error messages.

**Comment by zoechi** [comment]
> No docs or formalized sanity checks

Is there a test that plugins can be used together, so that one plugin doesn't depend on different versions of libraries than other published plugins? Users tend to use the latest version and 2 plugins of latest version should work together. This of course complicates releasing a lot.

> pub publish publishes literally everything in the directory

perhaps worth raising an issue in dart-lang/pub

> Sometimes plugins are in a state where they should not be published

adding `publish_to: none # do ready to be published` to `pubspec.yaml` would prevent accidental publishing

**Comment by mklim** [comment]
> Is there a test that plugins can be used together, so that one plugin doesn't depend on different versions of libraries than other published plugins? Users tend to use the latest version and 2 plugins of latest version should work together. This of course complicates releasing a lot.

There's nothing like this right now. The main catch I can think of with adding it into our CI is that by definition our CI needs to run before any new changes are published to pub. So the test would need to always be behind whatever is actually being updated in the tree. Maybe it could exist as a manual check before everything is published, or an alert after publishing?

> perhaps worth raising an issue in dart-lang/pub

Makes sense. Filed dart-lang/pub#2040
 
> adding `publish_to: none # do ready to be published` to `pubspec.yaml` would prevent accidental publishing

This would be ideal, but we have a presubmit check that verifies that all our packages could be published and it fails on this. https://github.com/flutter/plugins/blob/master/script/check_publish.sh We should probably update our presubmit to ignore failures based on this.

**Comment by zoechi** [comment]
> This would be ideal, but we have a presubmit check that verifies

https://github.com/dart-lang/pub/issues/2004

Perhaps explaining the problem this causes here might help to convince that this is a necessary thing and/or raise the priority.

**Comment by dnfield** [comment]
We missed publishing video_player 0.9.0 - this would have helped that.

**Comment by rodydavis** [comment]
Can we also get support for releasing updates to packages with a --token? Even if it is just for verified publishers. for example i have 20 flutter plugins and every update i need to download or locate the folder and submit the update 1 by 1.

By using a token i could set up GitHub Actions CI on a linux machine to automate my releases and testing for packages. 

It would dramatically  improve how fast i can go.

**Comment by mklim** [comment]
@rodydavis I think that sounds like a good feature request for [dart-lang/pub](https://github.com/dart-lang/pub). This issue is just tracking how the maintainers of [flutter/plugins](https://github.com/flutter/plugins) handle publishing releases to our packages given the existing pub tooling.

**Comment by mklim** [comment]
Created a wrapper for `pub publish` and added some documentation to [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-release-process). That addresses a lot of the points in the original issue.

The CONTRIBUTING has full information, but in summary plugins can now be released with:

```terminal
$ pub global run flutter_plugin_tools publish-plugin --package $package
```

**Comment by stuartmorgan** [comment]
Closing as we have auto-publish now.
