### ISSUE TITLE
pubspec version regex does not match prerelease versions

### ISSUE THREAD

**Issue by valkum** [flutter/flutter#27251]
## Steps to Reproduce

1. Edit your pubspec.yml to contain `version: 2.0.0-alpha.1`
2. run `flutter build apk`
3. local.properties file is missing the versionName field
4. apk file has default versionName of 1.

## What to expect
As the [pubspec doc ](https://www.dartlang.org/tools/pub/pubspec#version) allows prerelease notations I assumed at least the command will return an apk with the matching version. Like 2.0.0

The matching regex is here: [packages/flutter_tools/lib/src/flutter_manifest.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flutter_manifest.dart#L17)

**Comment by kangwang1988** [comment]
@valkum 
Thanks for your feedback.
I think this mainly comes from restrictions for CFBundleShortVersionString from the iOS side.
See: 
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349

**Comment by zoechi** [comment]
@kangwang1988 what about throwing an exception in case of a version string that can't be used as `CFBundleShortVersionString` value?

**Comment by kangwang1988** [comment]
@zoechi 
You mean that when the regex match fails, flutter_tools throw an exception so force users to conform the versionCode/versionName requirement?

**Comment by zoechi** [comment]
Yes, I think it would be better than silently dropping the version, 
or alternatively drop the part after `x.y.z`... and print a warning

**Comment by kangwang1988** [comment]
@zoechi 
Good point, I will follow on it.
