### ISSUE TITLE
Regression: hello_world snapshot size

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#27250]
The following engine rolls all have contributed to increase the snapshot size of our hello_world app (benchmark: hello_world_android__compile/snapshot_compressed_bytes):

* https://github.com/flutter/flutter/pull/25815
* https://github.com/flutter/flutter/pull/26792
* https://github.com/flutter/flutter/pull/27056 (cc @chinmaygarde)
* https://github.com/flutter/flutter/pull/27104

Overall, the snapshot went from 840,622 Bytes to 914,895 Bytes (compressed).

/cc @a-siva A Dart roll was included in most of these changes.

**Comment by jason-simmons** [comment]
1) There was an increase in the size of `isolate_snapshot_data` and `isolate_snapshot_instr` due to https://github.com/flutter/engine/commit/23b7e29f043fbf69c175450a21b81028deffa470

2) `isolate_snapshot_instr` has a worse compression ratio in the APK zip file starting with https://github.com/flutter/engine/commit/9b6d5031a3c0a4a6b1b5bd66a8e6a7c3c2c7ea0b

**Comment by jason-simmons** [comment]
The change in the compression ratio started with https://github.com/dart-lang/sdk/commit/8c439c7e841d04d2f05b963fe54457be526ac3d0

**Comment by chinmaygarde** [comment]
The compressibility of the generated instructions doesn't seem like we can realistically optimize for right? @jason-simmons mentioned that the size of the uncompressed instructions was actually smaller than with the previous VM.

**Comment by Hixie** [comment]
This is blocking our release. The cumulative regressions have brought us back as far as where we were in October last year, way above our 1.0.0 minimum footprint.

**Comment by mkustermann** [comment]
Before enabling the bare instructions support in https://github.com/dart-lang/sdk/commit/8c439c7e841d04d2f05b963fe54457be526ac3d0 I have measured the impact on flutter gallery. The **total size impact on gallery** (i.e. instructions + isolate snapshots sizes) was negligable (slightly smaller on arm, slightly bigger on arm64), though the relative sizes changed: isolate snapshots became smaller and instructions became bigger (to be more precise the actual machine code shrank by 9% but we de-duplicate less instructions objects).

The main purpose of the change was actually performance. It should have had a 10%+ performance (up to 20%) improvement on various flutter benchmarks (including build, layout and some animation benchmarks).

Do you think this change should be reverted?

**Comment by a-siva** [comment]
Let us revert it to unblock the release and then discuss again with @Hixie on how to proceed on this.

**Comment by Hixie** [comment]
Does this revert all the regressions? There were three or four places where it got worse in the last few weeks.

**Comment by mkustermann** [comment]
The two Dart VM changes I could find which changed the sizes were a) bare instruction support and b) changes to inlining heuristics.

I've tried to see what would happen if we revert either of those (using flutter/flutter@496ddc580, flutter/engine@0a9dadb04, dart-lang/sdk@71bee8f05e).

Here are the results (if I measured it correctly):

|                                                                | snapshot_compressed | snapshot_uncompressed | Perf Impact                             |
|----------------------------------------------------------------|---------------------------|-----------------------------|-----------------------------------------|
| Currently                                                       | 919468                    | 2758432                     |                                         |
| Disable Bare Instructions (dart-lang/sdk@8c439c7e84)           | 893149 (-2.86%)           | 2829456 (+2.57%)            | -10% to -20% in flutter microbenchmarks |
| Revert Inlining heuristics (dart-lang/sdk@6b5e8603d5)          | 908391 (-1.20%)           | 2728256 (-1.09%)            | ???                                     |


We see that the bare instructions support improved the uncompressed size but regressed the compressed size for the hello world app.

> Overall, the snapshot went from 840,622 Bytes to ...

If we want to get back to this, we need 9.14% size reduction. So even if we did these two reverts we wouldn't even be close to the original 840kb size.

**Comment by Hixie** [comment]
Small increments over time are ok, even expected, as we add code. Our concern is with unexpected regressions of hundreds of kilobytes.

I like the improvements to performance, but the unexpected regressions to footprint are concerning. I recommend that we revert the regressions, then reconsider them in context (maybe we are ok with the footprint regressions in exchange for the performance gains, but we should do this intentionally, not accidentally).

> even if we did these two reverts we wouldn't even be close to the original 840kb size

Then we should find out what other reverts we need to do as well.

**Comment by a-siva** [comment]
https://github.com/flutter/flutter/pull/27410 has been merged and the hello_world snapshot_compressed size is at 891600 bytes down from 918666 bytes.

**Comment by a-siva** [comment]
As expected we have lost the performance gains that this option got for us in the micro benchmarks (stock layout, stock animation etc.)

**Comment by Hixie** [comment]
Ok, thanks to everyone who has been trying to track these things down. The tree is now in a state where all the increases have been considered and justified. For the things that were reverted, let's look at them in detail in the coming days and decide which should be included by default and which should be considered special cases of optimisation for size vs performance.
