### ISSUE TITLE
about MediaQueryData padding in android app 

### ISSUE THREAD

**Issue by smilewant** [flutter/flutter#27268]
Platform： android

1 step : add Flutter to existing app

2 step : get `MediaQuery.of(context).padding.top` 

it will shows `MediaQueryData(... padding: EdgeInsets.zero ...)`
but in flutter app returns `[MediaQueryData(... padding:  EdgeInsets(0.0, 25.0, 0.0, 0.0))]`

is this a problem , how should i solve it only in Dart class

**Comment by zoechi** [comment]
Sounds a bit like #26841 but hard to tell without more information.

 > 2 step : get MediaQuery.of(context).padding.top

> but in flutter app returns [MediaQueryData(... padding: EdgeInsets(0.0, 25.0, 0.0, 0.0))]

Is "2 step" not from the Flutter app?

Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
If this is not possible to reproduce in a single `main.dart` file, please share a minimal reproduction as Flutter project, ideally shared as GitHub repo.

**Comment by smilewant** [comment]
> Sounds a bit like #26841 but hard to tell without more information.
> 
> > 2 step : get MediaQuery.of(context).padding.top
> 
> > but in flutter app returns [MediaQueryData(... padding: EdgeInsets(0.0, 25.0, 0.0, 0.0))]
> 
> Is "2 step" not from the Flutter app?
> 
> Please add the output of `flutter doctor -v`.
> 
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
> If this is not possible to reproduce in a single `main.dart` file, please share a minimal reproduction as Flutter project, ideally shared as GitHub repo.

it nearly same
but i want get statusbar's height 
and i use MediaQuery.of(context).padding to get height

i just add one line in your main.dart at last , it shows  'window.physicalSize.padding:0.0'

 return Text(
      'window.physicalSize.width: ${window.physicalSize.width}\n'
          'window.physicalSize.height: ${window.physicalSize.height}\n'
          'window.devicePixelRatio: ${window.devicePixelRatio}\n'
          'window.physicalSize.padding: ${mq.padding.top}\n',//This is i add
    );

**Comment by smilewant** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
