### ISSUE TITLE
something is goes wrong when run setState

### ISSUE THREAD

**Issue by hotakutsuki** [flutter/flutter#27262]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the issue.
If you are still seeing this and think this is a bug, please create a new issue with properly filled issue template. Thanks.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
