### ISSUE TITLE
Convert run_tests.sh to Python and make all bots run the same.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#27267]
Currently, only the Cirrus bots run this script. The Chromium infra bots run each step manually. We should make it so that this is only script that all bots (and humans) use to test all available unittest targets in the engine (and with the correct flags).

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/9818
