### ISSUE TITLE
Flutter doctor: Unable to download dart sdk,BITS service failed in windows 

### ISSUE THREAD

**Issue by abhimamk** [flutter/flutter#27276]
## Steps to Reproduce

1. Unable to runthe flutter command in windows. its trying to download dart sdk but bits service failed to download that dart sdk.
2. ...
3. ...

## Logs

```

```

```Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 9b6d5031a3c0a4a6b1b5bd66a8e6a7c3c2c7ea0b...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
```

**Comment by zoechi** [comment]
Can you please post the whole error output?
What happens with the attempted WebRequest?

Check the BITS service is running https://answers.microsoft.com/en-us/windows/forum/all/how-to-enable-background-intelligent-transfer/a8cc8a7f-0c82-4fa6-968d-de26605e37f2

**Comment by smartcodeboy** [comment]
.\flutter\bin\internal\update_dart_sdk.psl:53 字符：22
+ Invoke-WebRequest <<<< -uri $dartsdkUrl -OutFile $dartSdkZip
+ CategoryInfo : ObjectNotFound:(Invoke-WebRequest: Strg)[], P
+ FullyQualifiedErrorId : CommandNotFoundException
Error: Unable to update Dart SDK. Retrying...

**Comment by bonzinho** [comment]
> .\flutter\bin\internal\update_dart_sdk.psl:53 字符：22
> 
> * Invoke-WebRequest <<<< -uri $dartsdkUrl -OutFile $dartSdkZip
> * CategoryInfo : ObjectNotFound:(Invoke-WebRequest: Strg)[], P
> * FullyQualifiedErrorId : CommandNotFoundException
>   Error: Unable to update Dart SDK. Retrying...

Same problem

**Comment by kangwang1988** [comment]
It seems probably a powershell version issue.

https://flutter.io/docs/get-started/install/windows
```
Windows PowerShell 5.0 or newer (this is pre-installed with Windows 10)
```

https://stackoverflow.com/questions/53035692/invoke-webrequest-is-not-recognized-as-the-name-of-a-cmdlet-windows-7-powershell
```
By default Windows 7 comes with PowerShell version 2.0 installed. The Invoke-WebRequest cmdlet was introduced in PowerShell version 3.0.

The simplest solution is to upgrade your version of PowerShell to 3 or greater (I recommend just installing the latest version: 5.1). You can do that by downloading the Windows Management Framework:
```

@bonzinho 
Can you have a check by adding the check logic in update_dart_sdk.ps1
```
New-Item $dartSdkPath -force -type directory | Out-Null
$dartSdkZip = "$cachePath\$dartZipName"
Write-Host $PSVersionTable.PSVersion
Try {
    Import-Module BitsTransfer
    Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip
}
Catch {
    Write-Host "Downloading the Dart SDK using the BITS service failed, retrying with WebRequest..."
    Write-Host "-Uri $dartSdkUrl"
    Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
}
```

**Comment by kangwang1988** [comment]
Closed https://github.com/flutter/flutter/issues/27276 via https://github.com/flutter/flutter/pull/27596.

**Comment by matanshukry** [comment]
Just happened to me now, same output as above. Using windows 10, flutter channel master.
verified BITS service is running. Powershell version:

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316

**Comment by jobic10** [comment]
Try with a VPN

**Comment by OmkarSsawant** [comment]
When I run any flutter command 
Then in blue band BITS transferring.
Process starts and never actually ends.

**Comment by aamirahmednoor** [comment]
Hi,

If anyone is still facing this issue please follow the below steps:

1. Go into the directory where flutter SDK is installed
2. Go inside this path - \flutter\bin\internal
3. Open the file named update_dart_sdk.ps1

and add the below code after 'Import-Module BitsTransfer' inside the Try block

```
If($httpProxy = ([System.Uri] $env:http_proxy)){
    $proxyUserInfo = $httpProxy.UserInfo.Split(":")
    $proxyPass = ConvertTo-SecureString $proxyUserInfo[1] -AsPlainText -Force
    $proxyCredential = New-Object System.Management.Automation.PSCredential ($proxyUserInfo[0], $proxyPass)
    Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip -ProxyUsage Override -ProxyList ($httpProxy.Host + ":" + $httpProxy.Port) -ProxyCredential $proxyCredential -ProxyAuthentication Basic    
    }Else{
    Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip
    }

```

4. Try running the flutter command again

This solved the issue for me.

**Comment by ratulbside** [comment]
My problem is solved just by running a VPN.

**Comment by harikanani** [comment]
i have steal getting problems can anyone send some other solutions

**Comment by sagarvd01** [comment]
Flutter worked fine for me. I then run flutter upgrade from cmd as normal user and it failed with permission error. Now if I run flutter upgrade or any flutter command, even as admin, getting the following

```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine                                           ...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : NoSuchKeyThe specified key does not exist.No such object:
flutter_infra/flutter/������������������������������������������/dart-sdk-windows-x64.zip
At C:\src\flutter\bin\internal\update_dart_sdk.ps1:77 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Error: Unable to update Dart SDK. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
Checking Dart SDK version...
```

The blue BITS transfer window appear and disappear within 2 seconds. Fyi, BITS transfer downloading was completed when I run flutter upgrade for the first time.

**Comment by syfulsharif** [comment]
> 
> 
> Hi,
> 
> If anyone is still facing this issue please follow the below steps:
> 
>     1. Go into the directory where flutter SDK is installed
> 
>     2. Go inside this path - \flutter\bin\internal
> 
>     3. Open the file named update_dart_sdk.ps1
> 
> 
> and add the below code after 'Import-Module BitsTransfer' inside the Try block
> 
> ```
> If($httpProxy = ([System.Uri] $env:http_proxy)){
>     $proxyUserInfo = $httpProxy.UserInfo.Split(":")
>     $proxyPass = ConvertTo-SecureString $proxyUserInfo[1] -AsPlainText -Force
>     $proxyCredential = New-Object System.Management.Automation.PSCredential ($proxyUserInfo[0], $proxyPass)
>     Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip -ProxyUsage Override -ProxyList ($httpProxy.Host + ":" + $httpProxy.Port) -ProxyCredential $proxyCredential -ProxyAuthentication Basic    
>     }Else{
>     Start-BitsTransfer -Source $dartSdkUrl -Destination $dartSdkZip
>     }
> ```
> 
>     1. Try running the flutter command again
> 
> 
> This solved the issue for me.

The problem still persists

**Comment by sagarvd01** [comment]
Forgot to add, I solved the issue in that day itself. Here's the steps I followed.

Checked where the error message is coming from, `C:\src\flutter\bin\internal\update_dart_sdk.ps1:77`, from the variable `$dartSdkUrl`. I went to top line by line to check where the variable is declared and found out that it's importing a part from _engine.version_. I checked the file and found that **it contains non visible unicode string** and that's why it's shown as `������������������������������������������` in error message. I then visited _github.com/flutter/flutter/bin/internal/engine.version_ and it contains a hash. I copied the hash and replaced the contents in my local engine.version with the copied one. Then again I executed `flutter upgrade` and it worked fine.

**Comment by AMHRAKIB** [comment]
> i have steal getting problems can anyone send some other solutions

change the  dartSdkBaseUrl into this 
             $dartSdkBaseUrl = "https://storage.flutter-io.cn"

**Comment by sadeqmonoj** [comment]
> > i have steal getting problems can anyone send some other solutions
> 
> change the dartSdkBaseUrl into this
> $dartSdkBaseUrl = "https://storage.flutter-io.cn"

It worked for me. Thank you...

**Comment by AMHRAKIB** [comment]
Welcome

**Comment by xzhan96** [comment]
> Forgot to add, I solved the issue in that day itself. Here's the steps I followed.
> 
> Checked where the error message is coming from, `C:\src\flutter\bin\internal\update_dart_sdk.ps1:77`, from the variable `$dartSdkUrl`. I went to top line by line to check where the variable is declared and found out that it's importing a part from _engine.version_. I checked the file and found that **it contains non visible unicode string** and that's why it's shown as `������������������������������������������` in error message. I then visited _github.com/flutter/flutter/bin/internal/engine.version_ and it contains a hash. I copied the hash and replaced the contents in my local engine.version with the copied one. Then again I executed `flutter upgrade` and it worked fine.

Thanks a lot, this solve my issue.

**Comment by ikays97** [comment]
I had the same issue
Invoke-WebRequest : Unable to connect to the remote server
At C:\src\flutter\bin\internal\update_dart_sdk.ps1:70 char:5
+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
....
but at last resolved it by deleting env path (src/flutter/bin/) and src/flutter/bin itself. And unzipped using default compress/winrar (making workspace manually for flutter caused the error for me) and added env path as usual case. now I can get doctor logs.

**Comment by sernocturno** [comment]
before the try sentence you have to put 
`[Net.ServicePointManager]::SecurityProtocol +='tls12'`

**Comment by kidussc** [comment]
> > i have steal getting problems can anyone send some other solutions
> 
> change the dartSdkBaseUrl into this
> $dartSdkBaseUrl = "https://storage.flutter-io.cn"

you mean the $dartSdkBaseUrl in the if-block of the one in line 40
