### ISSUE TITLE
How to address a Pod version mismatch in the dependency flow?

### ISSUE THREAD

**Issue by shadowsheep1** [flutter/flutter#27288]
If I use `firebase_ml_vision` plugin  version > `0.1.2` I get this error

Google Analytics for Firebase version (50300000) does not match with Google App Measurement (50400000) version. Please update.

The error is addressed also here (but the error message is quite explicit):
https://github.com/firebase/firebase-ios-sdk/issues/2151

My question is, in a flutter project how to force the version of Google App Measurement to 5.3.0 so that avoiding using 5.4.0 that is taken from the dependency flow?

In a regular Xcode project I would play with Podfile, but here Podfile is built in such a way to get dependency from `pubspec.yaml `. 

Is there a best practice for that?

**Comment by zoechi** [comment]
You might get quicker response on StackOverflow. If you do ask there as well, please post the link to the question here.

**Comment by shadowsheep1** [comment]
Here my SO question too: https://stackoverflow.com/questions/54441539/how-to-address-a-pod-version-mismatch-in-the-dependency-flow

**Comment by shadowsheep1** [comment]
![screenshot 2019-01-30 at 18 25 05](https://user-images.githubusercontent.com/16268789/52000521-9d6b8900-24bd-11e9-8ba8-a400ef58d418.png)

For example modifying the plugin `podspec` it will work but I don't wanna do that for obvious reasons.

I'm looking for an "_update safe_" way to do that.

**Comment by rubenvde** [comment]
I got the same error too. Please fix this

**Comment by xperiafan13-rom** [comment]
Some error

**Comment by shadowsheep1** [comment]
@rubenvde @xperiafan13-rom They have solved the specific problem of version mismatch [here](https://github.com/flutter/flutter/issues/23259) today. This issue instead is asking for a standard way to address Pod dependency flow, when similar issues come.

**Comment by jmagman** [comment]
This is more of a CocoaPods/dependency management question than a Flutter question.  https://stackoverflow.com/a/45322760 suggests to specify the dependency version in your own Podfile.

I'm going to close this since there's nothing Flutter's tooling can really do to automatically handle dependency resolution issues with CocoaPods, any more than it can for pub or gradle.

**Comment by shadowsheep1** [comment]
@jmagman It's the solution I've addressed in the issue massage. I was hoping I had not to change a plugin podspec... but if there's no other solution it's okay anyway.

**Comment by jmagman** [comment]
> I was hoping I had not to change a plugin podspec... 

Yes, I meant specify the dependency version in your app's Podfile, not the plugin's podspec.  See the accepted answer: https://stackoverflow.com/a/45322760
