### ISSUE TITLE
The Android project introduces flutter in the form of a submodule. Before using flutter_macos_v0.9.4-beta in debug mode, it can be compiled and used normally, but after replacing it with the official version of flutter_macos_v1.0.0-stable, the code in the modified flutter project does not take effect.

### ISSUE THREAD

**Issue by Liujingguang** [flutter/flutter#27282]
The Android project introduces flutter in the form of a submodule. Before using flutter_macos_v0.9.4-beta in debug mode, it can be compiled and used normally, but after replacing it with the official version of flutter_macos_v1.0.0-stable, the code in the modified flutter project does not take effect.

**Comment by kangwang1988** [comment]
@Liujingguang 
A  minimal demo project which can reproduce this issue would be helpful.
