### ISSUE TITLE
Need onPageChanging(int index) for PageableList

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2729]
I need to synchronize a second animation to happen in the toolbar while the page change animation is happening. The `onPageChanged` notification is too late and `onScrollStart` doesn't provide any information about the target page.

I propose a callback named `onPageChanging(int index)` that fires before the animation begins.

**Comment by abarth** [comment]
We should look at how TabBarView does this.  It coordinates the page change with animating a tab indicator in the tab bar, which sounds similar to what you want to do.  Rather than adding a new callback, I wonder if we can hook you into that same mechanism.

**Comment by abarth** [comment]
The key is the TabBarSelection widget, which sits above these widgets in the tree and coordinates the selection between the tab bar and the tab bar view.  It has registerAnimationListener/unregisterAnimationListener, which you can hook into to get notified when the selection is changing.

**Comment by HansMuller** [comment]
PageableList has a scrollListener which may be enough for this use case. The only trick in using it is figuring out the page size.

**Comment by Hixie** [comment]
You definitely just want to use the existing animation rather than trying to keep two separate animations in sync, btw. (That is, you only want there to be a single AnimationController/Ticker running the whole thing, you just hook into the chain of animations that the TabBarSelection exposes.)

**Comment by jimbeveridge** [comment]
Thank you everyone. I will do as recommended.
