### ISSUE TITLE
Install required Atom plugins for new user

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#273]
When we init a new developer's copy of the Flutter code, we can also install all the appropriate Atom plugins (if the user has Atom installed).

We probably also want to check if Atom is installed, and if not, prompt the user to download it (or, if we can, install it for them).

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
For info:

`apm list -b` will show what's already installed, like:

```
atom-toolbar@0.1.0
dartlang@0.4.15
flutter@0.1.0
linter@1.11.2
monokai@0.18.0
```

`apm install dartlang` will install the plugin.

And `apm --version` will print the current tool version, and fail nicely if apm is not installed.

**Comment by danrubel** [comment]
We show IDE plugin information in `flutter doctor`. I don't think this feature is planned. Please reopen if we want to tackle this.
