### ISSUE TITLE
Flutter gallery

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#27307]
Please consider updating flutter gallery on Google play store and replying to reviews as such; it says last updated August and top reviews are negative, including "Nice that it exists. But it has many small bugs, and after five minutes it crashed into a terminal (yellow text on red background). Flutter is supposedly at 1.0, but this app suggests something like 0.1." and a snarky one.

you can't help negative reviews of course in many ways, we all know that, but if they are for an old version and there's a response indicating that than a potential user/evaluator can dismiss the negative review as "might be fixed"
thanks

**Comment by zoechi** [comment]
@xster was the update not published after #15533

**Comment by zoechi** [comment]
The crash could be related to #14935 Can you provide details about what device the app crashed on?

**Comment by timsneath** [comment]
Adding @mit-mit -- I wonder if there's an old version still languishing. I thought we'd cleared up the old ones, but it's also possible that someone from outside the Flutter team has uploaded an old version of the gallery.

**Comment by mit-mit** [comment]
The one published by the Flutter team should not be stale; it was last updated on January 31st, 2019, and has version 1.1.9:
https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

In the app itself, "hamburger" menu > About Flutter Gallery should show 'January 2019'.

@neiljaywarner can you link to the one you are referring to?

**Comment by neiljaywarner** [comment]
Someone fixed recently. Sorry I forgot to close
