### ISSUE TITLE
Add2app: app bar back button scenario

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#27318]
I am trying to account for back button in the embedded app to return to host app, to 'exit' the flutter portion of the app, so i have three thoughts on this
1) I notice there's a `BackButton` widget, which does work some but has some issues, most notable of which is that quite understandably when `initialRoute` is blank, `canPop=false`, so `maybePop` does nothing.  So in this case, hardware back button returns to Android app as expected, but visible "back" button does nothing . What's the best way to fix this?
2) Could we please consider exposing `onPressed` as an optional parameter that normally we do not expect to be passed, but could be used?  
3) nevertheless, i did copy the entire code into my project and change `maybePop` to `pop` and of course all that did is give me the blank black screen, which i suppose also makes sense.

I accept this might be more of an EBKAC/onboarding/flutter newbie issues, thereby making it a docuemntation/cookbook/samples issue as well?

I kinda hate to make a platform call for this, but that seems like OK workaround maybe...for now...

Thanks

**Comment by neiljaywarner** [comment]
https://stackoverflow.com/questions/54450436/in-flutter-add2app-scenario-how-do-i-get-the-app-back-button-to-return-to-host-a

**Comment by neiljaywarner** [comment]
flutter doctor -v output
--
✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.0.0 at /Users/warnene/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/neil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio3.2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio3.1FromSelfService.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio3.2.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[!] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 3 categories.
(sorry so long)

**Comment by zoechi** [comment]
@neiljaywarner I don't understand what the issue is about but I haven't tried integrating with an existing app. A minimal reproduction would definitely much easier to understand and to investigate.
