### ISSUE TITLE
MediaQueryData fields should be non-nullable

### ISSUE THREAD

**Issue by xster** [flutter/flutter#27311]
Nothing prevents users from creating MediaQuery with MediaQueryData with null fields and the field docs don't say how nulls should be interpreted.

**Comment by goderbauer** [comment]
Yes, we should just add asserts in the MediaQueryData constructor.

**Comment by AyushBherwani1998** [comment]
@goderbauer I would like to work on this issue.

**Comment by AyushBherwani1998** [comment]
@shihaohong, I would like to work on this issue. How can I write a test case to check whether the assertions made are correct or not?

**Comment by shihaohong** [comment]
@AyushBherwani1998  Depending on where the assert is (in the constructor, in a method, etc), there will be a different approach.

This [test DropdownButton test](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/dropdown_form_field_test.dart#L567) should work in the constructor, which seems like what you might be looking for.

Some like [this hero test](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/heroes_test.dart#L1910) would work for asserts that occur in a method.

Let me know if those ideas don't work! We can continue brainstorming ways to move forward!

**Comment by AyushBherwani1998** [comment]
@shihaohong the examples you gave were great refrence. I have submitted a PR. Looking forward to your reviews :)
