### ISSUE TITLE
"this is taking an unexpectedly long time"

### ISSUE THREAD

**Issue by hamidabdulmalik** [flutter/flutter#27310]
I keep getting "this is taking an unexpectedly long time" message on terminal when i run the "flutter run" command. Whats your take on this? Nothing is working.

**Comment by zoechi** [comment]
Please provide more context.

**Comment by hamidabdulmalik** [comment]
Thanks for your response. When I hook up my mobile device, and run the "flutter run" command, after a few minutes waiting, I get the message "this is taking an unexpectedly long time" and that's it. It just remains that way.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by hamidabdulmalik** [comment]
![flutter2](https://user-images.githubusercontent.com/340532/52005656-496f9d00-24db-11e9-91fe-66e0357340b7.png)
This is the flutter doctor -v output

**Comment by hamidabdulmalik** [comment]
![flutter](https://user-images.githubusercontent.com/340532/52005718-686e2f00-24db-11e9-8848-28324870726d.png)
And this is the issue I am having

**Comment by kangwang1988** [comment]
@hamidabdulmalik 
Are you saying that it works fine in `flutter doctor` but will get stuck when `flutter run`?

**Comment by hamidabdulmalik** [comment]
@kangwang1988 exactly, at the moment, only "flutter doctor" works. Please, how do I revert to a later master?

**Comment by kangwang1988** [comment]
@dnfield 
Do you have more context towards AnsiSpinner's timer-callback behavior?

**Comment by dnfield** [comment]
No, @hixie may

**Comment by kangwang1988** [comment]
cc @Hixie

**Comment by hamidabdulmalik** [comment]
I am making a fresh install. Will let you know when I am done

**Comment by hamidabdulmalik** [comment]
@zoechi after fresh installation, even "flutter doctor -v" command stopped working. Just displaying the same message on the terminal.

**Comment by kangwang1988** [comment]
@hamidabdulmalik 
Paste full result(text instead of screenshot) for `flutter -v doctor -v` please.

**Comment by hamidabdulmalik** [comment]
@kangwang1988 

![flutter one](https://user-images.githubusercontent.com/340532/52039378-680a7e00-2545-11e9-8ca2-e22afdf78e06.png)
![flutter two](https://user-images.githubusercontent.com/340532/52039394-76589a00-2545-11e9-8e56-384aa7cf660c.png)

**Comment by kangwang1988** [comment]
> after fresh installation, even "flutter doctor -v" command stopped working. Just displaying the same message on the terminal.

`flutter doctor` seems fine based on your screenshot above.

**Comment by hamidabdulmalik** [comment]
> > after fresh installation, even "flutter doctor -v" command stopped working. Just displaying the same message on the terminal.
> 
> `flutter doctor` seems fine based on your screenshot above.

Yes, everything seems fine, except I cannot run "flutter run" successfully

**Comment by hamidabdulmalik** [comment]
anything? anybody?

**Comment by josvos** [comment]
I have the same error messages (since 1.2.0 ?) on both emulator and real devices (running debug versions), many, many messages (30, 40, 50, I can't count), but after that the app runs normally.

After a hot reload ('r') 7 of these messages appear, after a hot restart ('R') many more messages appear,. but not as many as with app start.  In all cases, the app seems to work ok afterwards.

All the messages start with about 75 spaces and the messages are cut off after 5 chars or so (no newline wrapping etc.), it all looks very weird...

**Comment by josvos** [comment]
OK, flutter doctor seems to complain about the required SDK version and not accepted licenses.  Has something changed since 1.2.0 ?

**Comment by Hixie** [comment]
If `flutter doctor` works but `flutter run` doesn't, try `flutter run -v` and paste the text of the resulting logs here (not a screenshot please).

@hamidabdulmalik just out of interest, what link did you follow to file this bug? (Nomally when filing a bug we give you a template that specifies what information we need, but it looks like you didn't go through that flow?)

**Comment by htueko** [comment]
I get this error too, after that I switched to cmder and flutter run, still got the error, but after a while (long while) It's fixed.

**Comment by hamidabdulmalik** [comment]
What I did was download the compressed stable flutter sdk from the flutter website. I think if your version of flutter is from github repository directly, you may be a victim. But I am good now. If you are having this problem, download the stable build zipped from the flutter website and replace with the one you have.

**Comment by tsangint** [comment]
I met the same error messages, and I'm install from github.anybody know how to resolve it if I don't want to installed from zipped.

**Comment by tsangint** [comment]
I found the reason.It's because of network problem, "flutter packages get" can't run successfully.

**Comment by khalithartmann** [comment]
did anybody solve the problem ?

**Comment by xonexx** [comment]
This issue is causing for gradle version. Go to "C:\Users\{username}\.gradle\wrapper\dists" and see which which gradle versions are available. Now open "yourproject\android\gradle\wrapper\gradle-wrapper.properties" file , on last line you will find something this [ distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip ] 
now download that gradle version and install on "C:\Users\{username}\.gradle\wrapper\dists". Restart android studio and try to build again , Boom ! Your Problem is solved.

**Comment by kararsaadkd** [comment]
Is there someone close to solving the problem. I have encountered the same problem

**Comment by temirfe** [comment]
after recent flutter upgrade this is happening almost always, and terminal (Windows PowerShell) is behaving strangely.

**Comment by vargavince91** [comment]
I had the same issue while developing a [platform channel](https://flutter.dev/docs/development/platform-integration/platform-channels) for iOS. As I didn't have much experience with iOS development, I didn't know how to debug the issue. My issue was that I called this line twice...

```obj-c
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [GeneratedPluginRegistrant registerWithRegistry:self];
    // code...
    // Called it for a second time which caused the app to crash
    [GeneratedPluginRegistrant registerWithRegistry:self];
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

```

**Comment by tanmaysri** [comment]
Facing same issue... did anyone solve?

**Comment by gremlin97** [comment]
Any solution for this issue?

**Comment by Maxxoto** [comment]
In my case the problem is about to be "Android License" because when i running `flutter doctor -v `, it showing "Checking Android License is taking unexpected long time".

**Comment by tanmaysri** [comment]
Guys, It worked for me:

1. Created a fresh project
2. Temp files were causing the trouble with android licenses (a restart did the trick)
3. Java version was also causing trouble so changed the build.gradle file
  // Added by me for solving java version error
     compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

Hope this helps!

**Comment by Maxxoto** [comment]
Great :) .

**Comment by minhlong** [comment]
Same with me.

**Comment by rivertiger** [comment]
stopped working for me after i upgraded to High Sierra 10.13.4 to Mojave 10.14.3

**Comment by YDJSZY** [comment]
anybody can solve it?

**Comment by JTNCGCG** [comment]
I did run on command line flutter clean and re-ran and it worked for me.

**Comment by leodavinci1** [comment]
I was having the same issues when i ran the command **flutter create app_name** or **flutter run**.
Here in Brazil the website [](https://pub.dartlang.org/) that flutter uses to get the packages **with flutter packages get** isn't reachable. I tried using TunnelBear VPN connecting to a USA network and it all worked fine. I think thats why people here from certain countries can't debug or even reproduce this issue.

**Comment by earyzhe** [comment]
Also having the same issue here.

**Comment by minhlong** [comment]
Please reopen this issue

Thanks,

**Comment by dnfield** [comment]
In general, if you are getting this problem you should try the same command with the verbose option, i.e. `flutter run -v`.  That should show where the tool is getting hung up more explicitly.

There are a lot of possible causes for this.  The only way to clear it up is to look at the verbose logs.

**Comment by minhlong** [comment]
Thank so much @dnfield 

I tried `flutter run -v` 

- My system info

```
Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
OS:           Windows 10 10.0 amd64
```

- And below block repeated
```
[   +5 ms] Installing build\app\outputs\apk\app.apk... (completed in 4.0s)
[   +4 ms] executing: C:\Users\homin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell echo -n a035babf1012c70edcb5e053005b13fb313f5293 >/data/local/tmp/sky.com.example.demo_flutter.sha1
[  +94 ms] Android SDK built for x86 64 startApp
[   +6 ms] executing: C:\Users\homin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.demo_flutter/com.example.demo_flutter.MainActivity
[ +500 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.demo_flutter/.MainActivity (has extras) }
[   +5 ms] Waiting for observatory port to be available...
[+2885 ms] Observatory URL on device: http://127.0.0.1:37032/
[  +26 ms] executing: C:\Users\homin\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 forward tcp:0 tcp:37032
[  +56 ms] 51933
[   +3 ms] Forwarded host port 51933 to device port 37032 for Observatory
[  +18 ms] Connecting to service protocol: http://127.0.0.1:51933/
[+1361 ms] Successfully connected to service protocol: http://127.0.0.1:51933/
[   +8 ms] Sending to VM service: getVM({})
[  +16 ms] Result: {type: VM, name: vm, architectureBits: 64, targetCPU: x64, hostCPU: Virtual CPU, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_x64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 7520, startTime: 15537...
[  +17 ms] Sending to VM service: _flutter.listViews({})
[  +12 ms] Result: {type: FlutterViewList, views: []}
[  +57 ms] Sending to VM service: getVM({})
[  +19 ms] Result: {type: VM, name: vm, architectureBits: 64, targetCPU: x64, hostCPU: Virtual CPU, version: 2.1.2-dev.0.0.flutter-0a7dcf17eb (Tue Feb 12 01:59:15 2019 +0000) on "android_x64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 7520, startTime: 15537...
[  +10 ms] Sending to VM service: _flutter.listViews({})
[  +27 ms] Result: {type: FlutterViewList, views: []}
.
.
.
```

**Comment by dnfield** [comment]
@minhlong can you open a new bug for that?

**Comment by minhlong** [comment]
SOLVED

@dnfield and All ,
After updating the android sdk, it has been solved.

![update-abd](https://user-images.githubusercontent.com/6802727/55129304-2e22b600-5149-11e9-9066-32a463cccd17.png)

- Check `Android SDK Build-Tools`
- Apply and OK
- Restart my laptop

- Go to the project, and run below command lines
```
flutter clean
flutter emulators --launch my-machine-id
flutter run
```

Thank all,

**Comment by Aajat** [comment]
Compiler message:
file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:996:66: Error: Getter not found: 'extChildStyle'.
          final String childPrefixOtherLines ='$prefixChildren${~extChildStyle.linkCharacter}${childConfig.prefixOtherLines}';
                                                                 ^^^^^^^^^^^^^
file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:996:66: Error: The getter 'extChildStyle' isn't defined for the class 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'extChildStyle'.
          final String childPrefixOtherLines ='$prefixChildren${~extChildStyle.linkCharacter}${childConfig.prefixOtherLines}';
                                                                 ^^^^^^^^^^^^^
Compiler failed on C:\Users\nepal\AndroidStudioProjects\flutter_app\lib/main.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        24.9s
Gradle task assembleDebug failed with exit code 1

C:\Users\nepal\AndroidStudioProjects\flutter_app>

**Comment by khalithartmann** [comment]
please reopen. im having the same issue for ios and android. none of the above workarounds worked ...

**Comment by dnfield** [comment]
@khalithartmann Please consider opening a new bug, along with the output of the command that's timing out run with the `--verbose` (or `-v`) flag.  The original author of this bug closed it as resolved, and it there are many, many possible causes for this behavior.

**Comment by xai1983kbu** [comment]
thank you @minhlong, your solution works for me
but I didn't realize it at first. after I read
https://stackoverflow.com/a/51387250/9783262
https://stackoverflow.com/a/54723296/9783262

I run -> "flutter run -v" instead of just "flutter run"
I was waiting near 20 minutes but, in the end, it got working

**Comment by khalithartmann** [comment]
i got android working too . but does anyone have a solution for IOS ??

**Comment by Iampato** [comment]
Same issue any fix ?

**Comment by Iampato** [comment]
## command

flutter build apk

## exception

ProcessException: ProcessException: Process "C:\Users\User\Documents\Flutter\mbunge\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\User\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\User\Documents\Flutter\mbunge\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:250:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:210:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:191:37)
<asynchronous suspension>
#3      buildGradleProject (package:flutter_tools/src/android/gradle.dart:321:31)
<asynchronous suspension>
#4      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:45:11)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    [32m•[39m Flutter version 1.2.1 at C:\flutter
    [32m•[39m Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = C:\Users\User\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code, 64-bit edition (version 1.32.3)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 2.25.0

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by newtonmunene99** [comment]
Anyone find a solution?

**Comment by Iampato** [comment]
Fixed this by:

 download gradle 4.10.1 all zip extracted to a more accessible dir e.g ( C:\ )
![Annotation (1)](https://user-images.githubusercontent.com/32388339/55755143-fecc4d00-5a56-11e9-8e90-f824a2b7a025.png

then updated my system variables 
![Annotation](https://user-images.githubusercontent.com/32388339/55755156-0855b500-5a57-11e9-95ed-c51e43694e4e.png)

and now
 flutter run/build works

**Comment by VikoVoila** [comment]
have anyone solved this problem

**Comment by newtonmunene99** [comment]
@Iampato tried it. But didn't quite solve the issue.

**Comment by MeshkaniMohammad** [comment]
I had the same problem even in running `flutter doctor` but it just takes more time and workes after 3-4 minutes later. and none of the mentioned ways couldn't solve my problem.

**Comment by BriedaAbdul** [comment]
i had almost the same issue by running **flutter build apk --release** it was given nothing but when i tried to simply run flutter build i have got the **apk-release**

**Comment by TheKetan2** [comment]
> In my case the problem is about to be "Android License" because when i running `flutter doctor -v `, it showing "Checking Android License is taking unexpected long time".

you can resolve issues related to Android License by running command  `flutter doctor --android-licenses`

**Comment by TheKetan2** [comment]
Hi there, after updating Android SDK build tools and restarting PC flutter started working again.

**Comment by egorges** [comment]
I have the same issue without Android SDK.
I use VSCode on Mac, and when I build for ios (either simulator or device), I receive lots of:
(This is taking an unexpectedly long time.)

On simulator, 'only' around 20 of them.
But on device it keeps scrolling screen for several minutes.

**Comment by BriedaAbdul** [comment]
For my side it was about the updating sdk when i downgraded everything and run Flutter clean then Flutter build everything works perfectly

**Comment by AkashRajpurohit** [comment]
Same issue here.
The output of ```flutter doctor -v```

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_IN)
    • Flutter version 1.2.1 at /home/akash/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/akash/Android
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/akash/Android
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2-b11)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[✓] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Redmi Note 4 • f6c2c2929804 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

and output of ```flutter run -v```

```
[  +64 ms] executing: [/home/akash/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +84 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/akash/flutter/] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/home/akash/flutter/] git ls-remote --get-url origin
[  +19 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +1 ms] executing: [/home/akash/flutter/] git log -n 1 --pretty=format:%H
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/home/akash/flutter/] git log -n 1 --pretty=format:%ar
[  +20 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[   +1 ms] executing: [/home/akash/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +23 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +2 ms] v1.2.1-0-g8661d8aec
[ +191 ms] executing: /home/akash/Android/platform-tools/adb devices -l
[  +27 ms] Exit code 0 from: /home/akash/Android/platform-tools/adb devices -l
[        ] List of devices attached
           f6c2c2929804           device usb:1-1.1 product:mido
           model:Redmi_Note_4 device:mido transport_id:2
[ +515 ms] /home/akash/Android/platform-tools/adb -s f6c2c2929804 shell getprop
[ +110 ms] ro.hardware = qcom
[+1449 ms] Launching lib/main.dart on Redmi Note 4 in debug mode...
[  +48 ms] Initializing gradle...
[  +32 ms] Using gradle from
/home/akash/Documents/testing_stuff/flutter/demo/android/gradlew.
[  +15 ms] executing:
/home/akash/Documents/testing_stuff/flutter/demo/android/gradlew -v
```
And it just stops there.

PS: I don't have android studio but android sdk tools as well as gradle are all properly configured as i have build projects with Ionic and React Native. Trying flutter out but stuck in the very first step.

**Comment by khalithartmann** [comment]
so i realized that every once in a while you have to delete the ios and android files and rebuild them. You have to constantly keep those up to date . I created a flutter project when flutter was still in beta and i was frequently running into very weird issues (one of them was this one). 
When i deleted the ios and android files and ran "flutter create . " it solved a lot of my problems . Note that this will delete all gradle , manifest , plist. .. configs so i would save those . Hope it helps . You can also check out this link : https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by BriedaAbdul** [comment]
Try to clean by running flutter clean then run flutter run -v

**Comment by AkashRajpurohit** [comment]
Tried flutter clean and flutter run..still no luck...

and yes I'll try the method khalithartmann have suggested.. upgrade flutter sdk and delete the iOS android folders and do flutter create .

**Comment by BriedaAbdul** [comment]
Where are you running your command? I'll suggest you to run your code in the CLI not in the IDE terminal. Because it looks like your app is updating your gradle it'll take a bit of time

**Comment by AkashRajpurohit** [comment]
I'm running the command on Terminal. not Integrated Terminal of Visual Studio Code that I'm using for development

**Comment by nandkk05** [comment]
Recently I was suffering from the same issue but now it is solved as I **updated with the latest Dart SDK and reboot my laptop.** 

(In my case) 👍 
If again it appears **"taking too much time"** then turn on your internet connection and wait for **10 to 15 minutes.** It will start working automatically.

This problem mainly occurs when you import other projects so they require **different Gradle version** to build the apk.

Hope this will help

**Comment by AkashRajpurohit** [comment]
Great to hear that.
Few questions for clarification
1. Update dart Sdk == updating the flutter sdk which is to be installed right?
2. You tried running you app through emulator or real device?
3. Explain a little better what you mean different gradle version

**Comment by nandkk05** [comment]
1. Install the **latest [Flutter SDK v1.5.4-hotfix.2-stable.zip]**(https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.5.4-hotfix.2-stable.zip)
In my case, I have **flutter_windows_v1.2.1-stable**

2. I'm running my app on the real device_(Redmi 4x)_ 

3. You can check the **Gradle version** in **build.gradle file** under Android folder. 

I mean that if you are using Gradle 5.3.1 to build your project and then you share that file with any other developer. So he/she has to download the same Gradle version or above to work with your code...
Download Gradle files from here [https://gradle.org/](url)

Hope this will help!

**Comment by nandkk05** [comment]
1.Install the latest [Flutter SDK v1.5.4-hotfix.2-stable.zip](https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_v1.5.4-hotfix.2-stable.zip)
In my case, I have **flutter_windows_v1.2.1-stable**

2. I'm running my app on the **real device**_(Redmi 4x)_

3. You can check the Gradle version in build.gradle file under Android folder.

I mean that if you are using Gradle 5.3.1 to build your project and then you share that file with any other developer. So he/she has to download the same Gradle version 5.3.1 or above to work with your code...
Download Gradle files from here [https://gradle.org/](url)

Hope this will help!

**Comment by MisterAwesome23** [comment]
I understand this might be noob answer, but might want to give it a try.
I was using actual android device to "flutter run" command which initially yielded -- "this is taking an unexpectedly long time"
I simply terminated that process.
Moved on to disconnect the phone.
Switch usb port.
Redo.
It worked :)
And like we say, "somehow it did :)"

**Comment by Alfapalooza** [comment]
I had a similar issue, in my case I had a dependency that required iOS 11 that I no longer needed and removed from my `pubspec.yaml`. I think when I did that my iOS target dropped to iOS 8 instead of 11, but due to a leftover dependency that still required iOS 11 target, it was causing my build to fail.

I fixed this by running:
```
flutter clean && \
  cd ios && \
  rm -rf Pods && \
  rm -rf .symlinks && \
  pod install && \
  cd ..
```

**Comment by JohnnyLuv** [comment]
1.delete your flutter `lockfile`
path like this: ` /Users/xxx/Desktop/flutter/bin/cache`

2.remove your `App.framework`
path like this: `/my-app/ios/Flutter/App.framework`

3.restart your IDE

4.`flutter clean`

5.`flutter run`

**Comment by jbetts80** [comment]
> I had a similar issue, in my case I had a dependency that required iOS 11 that I no longer needed and removed from my `pubspec.yaml`. I think when I did that my iOS target dropped to iOS 8 instead of 11, but due to a leftover dependency that still required iOS 11 target, it was causing my build to fail.
> 
> I fixed this by running:
> 
> ```
> flutter clean && \
>   cd ios && \
>   rm -rf Pods && \
>   rm -rf .symlinks && \
>   pod install && \
>   cd ..
> ```

This worked!

**Comment by raghavendra905** [comment]
use flutter doctor -v
it usually download gradle(which is a large file) for the first time you run a flutter program.The above will help you to see the message that its downloading gradle/dist.It wont happen from the next program

**Comment by shakilur157** [comment]
i turned on VPN before running the command "flutter build apk" and it worked tho idk why.

**Comment by sathwikdoddi** [comment]
None of these solutions have worked for me.

output of flutter -v doctor -v:
```
[+1165 ms] [✓] Android toolchain - develop for Android devices (Android SDK
version 29.0.3)
[        ]     • Android SDK at /Users/sathwikdoddi/Library/Android/sdk
[        ]     • Platform android-29, build-tools 29.0.3
[        ]     • Java binary at: /Applications/Android
                 Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build
                 1.8.0_242-release-1644-b3-6222593)
[        ]     • All Android licenses accepted.
[   +4 ms] [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 11.5, Build version 11E608c
[        ]     • CocoaPods version 1.9.1
[   +1 ms] [✓] Android Studio (version 4.0)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Flutter plugin version 46.0.2
[        ]     • Dart plugin version 193.7361
[        ]     • Java version OpenJDK Runtime Environment (build
                 1.8.0_242-release-1644-b3-6222593)
[   +3 ms] [✓] VS Code (version 1.46.1)
[        ]     • VS Code at /Applications/Visual Studio Code.app/Contents
[        ]     • Flutter extension version 3.12.1
[   +1 ms] [✓] Connected device (1 available)
[        ]     • iPhone 11 • 0B932A3D-FFE3-4A4A-947F-EE67AF8DC6F9 • ios •
                 com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
[        ] • No issues found!
[  +16 ms] "flutter doctor" took 8,452ms.
[ +202 ms] ensureAnalyticsSent: 194ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

Every time I run a project, It takes "an unexpectedly long time..." and half of the time, I get an error saying "Could not build the application for the simulator. Error launching application on iPhone 11." The only way to fix the launch error is by removing the Pods folder from the ios directory and rerunning. But the unexpectedly long time error is not going away no matter what I try to do.

If anyone has a solution for either of my problems, it would be much appreciated

**Comment by sathwikdoddi** [comment]
Here is the could not build error with flutter run -v:
```
[+1680 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 11.
[  +11 ms] "flutter run" took 144,131ms.
[  +14 ms]
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:578:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:844:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues
(package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback
           (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by psc215** [comment]
Update your `dependencies` before running and try running by commenting out `dependency_overrides`

**Comment by nomicool** [comment]
I have fixed that issue with installing latest jdk and jre and added both path to environment variables. it fixes my all flutter issues now flutter is working on its speed.
