### ISSUE TITLE
[PR] add Android support to location_background package

### ISSUE THREAD

**Issue by angel1st** [flutter/flutter#27317]
I would really appreciate if you guys can put [location_background](https://github.com/flutter/plugins/tree/master/packages/location_background) Android support on the roadmap. TBH - it seems a bit funny lack of Android version in Flutter.
Any thoughts on this one would be greatly appreciated...

**Comment by zoechi** [comment]
As far as I know this package is supposed to provide similar functionality as https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager which obviously is for Android only. The underlying platforms provide very different ways for background execution and therefore the different approaches.  

You might want to follow #24278

**Comment by angel1st** [comment]
Thanks, @zoechi for pointing out #24278, it seems however, [android alarm manger](https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager) falls into category 2  (periodically updates), while [location background](https://github.com/flutter/plugins/tree/master/packages/location_background) is into category 3 (platform driven events), which seems to me as entirely different use case. Anyway - looking at the above mentioned by you issue, seems to be the place for general inquiry re dart / flutter background execution.

**Comment by TahaTesser** [comment]
Closing since this package doesn't exist anymore in plugins repo
Thank you
