### ISSUE TITLE
Dart Analyzer Error In Flutter Using IntelliJ

### ISSUE THREAD

**Issue by psycry** [flutter/flutter#27312]
See https://github.com/dart-lang/sdk/issues/35810, essentially it's throwing this randomly and code completion/analysis is running slower than normal after updating both flutter and the plugins possibly (I ran updates but I don't remember if the flutter plugin was included in them, I believe it may have been):

13:24	Dart Analyzer Error
			Encountered a Dart Analysis Server error.
			Open issue submission form?

For further details and stack trace see #35810, I filed it there as that's where IntelliJ took me but I'm not sure that it's a dart error and suspect it to be related to Flutter or the plugin.  let me know if you need more details.  Steps for reproducing it are in the other ticket:

https://github.com/dart-lang/sdk/issues/35810

**Comment by zoechi** [comment]
dart-lang/sdk is the right place for Analyzer errors. 
So I'm closing here.

**Comment by psycry** [comment]
Ok thanks zoechi, just wasn't sure if it was plugin related rather than Analyzer itself.
