### ISSUE TITLE
Hero animation causes overflow

### ISSUE THREAD

**Issue by JssDWt** [flutter/flutter#27320]
When a Hero contains a Column with mainAxisSize: MainAxisSize.min, on navigating to a new page, the content overflows (by 0.0000172 pixels) (only during the navigation). This even happens when navigating to the exact same page with the same widgets. 
My guess is the Hero is not calculating the size of the RenderFlex properly during flight.

## Steps to Reproduce

1. Create a flutter project using `flutter create hero_overflow`
2. Replace the contents of main.dart with the following gist: https://gist.github.com/JssDWt/98c01b5fa29d389409010cefa881d091
3. Run the app and press the 'button'.

## Logs

Useful part of the logs:
```
[        ] Syncing files to device Android SDK built for x86... (completed)
[        ] Synced 0.8MB.
[        ] Sending to VM service: _flutter.listViews({})
[   +6 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0xe523760c, isolate: {type: @Isolate, fixedId: true, id: isolates/316462981, name: main.dart$main-316462981, number: 316462981}}]}
[        ] Connected to _flutterView/0xe523760c.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:64614/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[ +140 ms] D/        (22909): HostConnection::get() New Host Connection established 0xc5dc6100, tid 22929
[        ] D/EGL_emulation(22909): eglMakeCurrent: 0xe47dc2a0: ver 3 0 (tinfo 0xcae7f080)
[+4656 ms] I/flutter (22909): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[   +3 ms] I/flutter (22909): The following message was thrown during layout:
[        ] I/flutter (22909): A RenderFlex overflowed by 0.0000172 pixels on the bottom.
[  +16 ms] I/flutter (22909): 
[        ] I/flutter (22909): The overflowing RenderFlex has an orientation of Axis.vertical.
[        ] I/flutter (22909): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
[        ] I/flutter (22909): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
[   +6 ms] I/flutter (22909): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
[        ] I/flutter (22909): RenderFlex to fit within the available space instead of being sized to their natural size.
[        ] I/flutter (22909): This is considered an error condition because it indicates that there is content that cannot be
[        ] I/flutter (22909): seen. If the content is legitimately bigger than the available space, consider clipping it with a
[        ] I/flutter (22909): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
[        ] I/flutter (22909): like a ListView.
[        ] I/flutter (22909): The specific RenderFlex in question is:
[        ] I/flutter (22909):   RenderFlex#856db OVERFLOWING
[        ] I/flutter (22909):   creator: Column ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← InkWell ←
[        ] I/flutter (22909):   DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#6fb53 ink renderer] ←
[        ] I/flutter (22909):   NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← ⋯
[        ] I/flutter (22909):   parentData: <none> (can use size)
[        ] I/flutter (22909):   constraints: BoxConstraints(w=71.0, h=16.0)
[        ] I/flutter (22909):   size: Size(71.0, 16.0)
[        ] I/flutter (22909):   direction: vertical
[        ] I/flutter (22909):   mainAxisAlignment: start
[        ] I/flutter (22909):   mainAxisSize: min
[        ] I/flutter (22909):   crossAxisAlignment: center
[        ] I/flutter (22909):   verticalDirection: down
[        ] I/flutter (22909): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
[        ] I/flutter (22909): ════════════════════════════════════════════════════════════════════════════════════════════════════
[+4449 ms] Application finished.

```

Flutter analyze
```
Analyzing hero_overflow...
No issues found! (ran in 1.4s)
```

Flutter doctor:
```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale nl-NL)
    • Flutter version 1.1.8 at /Users/jessedewit/Documents/Programmeren/flutter
    • Framework revision 985ccb6d14 (3 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jessedewit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)

• No issues found!
```

**Comment by JssDWt** [comment]
Removed screenshot (turned into png instead of gif)

**Comment by pat64j** [comment]
@JssDWt.. I faced this same problem but the overflow error was logged only when I was navigating back to the source Hero widget. I did an override of the **flightShuttleBuilder** property of both Heros and placed the widget in a **SingleChildScrollView** widget like so:

`                          


                            Hero(
                            tag: widget.propertyId,
                            flightShuttleBuilder: (BuildContext flightContext,
                                Animation<double> animation,
                                HeroFlightDirection flightDirection,
                                BuildContext fromHeroContext,
                                BuildContext toHeroContext,){

                              return SingleChildScrollView(
                                child: fromHeroContext.widget,
                              );
                            },

                            child: Material(....))


`

And the error went off. It might not be the perfect answer but it fixed my error and I hope it helps you.

**Comment by JssDWt** [comment]
I did a little digging, and I'm assuming rounding errors occur when `MaterialRectArcTween` calculates the corners using a diagonal. More specifically in the function `_diagonalSupport`.

Perhaps these rounding errors can be avoided. And if not, if these rounding errors seem unavoidable, perhaps the overflow should not be reported when less than a very small amount of pixels (say 0.0001 or so).

@pat64j: thanks for the workaround. I'll stick with yellow banners in debug mode for now.

**Comment by JssDWt** [comment]
I retract my previous statement. Further research made me find that the problem lies in the following situation:
- `MaterialRectArcTween` inherits `RectTween`
- When `RectTween` lerps, it calls `Rect.lerp()`
- `Rect.lerp()` does the following to recalculate the sides:
```dart
return new Rect.fromLTRB(
      lerpDouble(a.left, b.left, t),
      lerpDouble(a.top, b.top, t),
      lerpDouble(a.right, b.right, t),
      lerpDouble(a.bottom, b.bottom, t),
);
```
- Now, `Rect` stores the sides in a `Float32List`, which will slightly change the double precision numbers, as can be seen in the following conversation: https://github.com/dart-lang/sdk/issues/26951
- This probably (?) means the resulting corners are not completely accurate and may cause height differences?

Since the rounding errors are so small, I don't think they themselves are an issue. Just the debug yellow striped debug banner should be shown only when the overflow is 'significant'.

**Comment by JssDWt** [comment]
Another example, the following assertion fails:
```dart
const double LEFT = 2 + 1/3;
const double TOP = 2 - 1/3;
const double RIGHT = 152 + 1/3;
const double BOTTOM = 67 - 1/3;
Rect rect = Rect.fromLTRB(LEFT, TOP, RIGHT, BOTTOM);
print(rect.top - rect.bottom); // prints -64.99999749660492
assert(rect.top - rect.bottom == -65.0);
```

**Comment by HansMuller** [comment]
[Sorry that it's taken so long to get to this issue.]

I was able to reproduce the problem with a slightly simplified version of the test case: https://gist.github.com/HansMuller/9e854ca429eff9ee8296e41f038dcc8f

The error is introduced in the Hero implementation when a [Size is effectively copied into a Rect](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/heroes.dart#L60). Interestingly it's not the matrix transform that causes the problem, it's just a side effect of copying the width/height into a Rect. Which is effectively just as [@JssDWt pointed out earlier](https://github.com/flutter/flutter/issues/27320#issuecomment-462127692).

**Comment by dnfield** [comment]
The upstream change that fixes this is getting reverted - needs some more investigation.

**Comment by wilburt** [comment]
I am still experiencing this in **Flutter 1.7.8+hotfix.4 • channel stable**.

**Comment by marcmarder** [comment]
Still in 1.9.1+5

**Comment by pacifio** [comment]
Still in 1.9.1+6

**Comment by Pebsie** [comment]
Why is this closed? It's still an issue.

**Comment by ramtinq** [comment]
I'm still having this issue in Flutter 1.12.13 ! It only happens in taller phones like Pixel Xl
