### ISSUE TITLE
we need get location official package

### ISSUE THREAD

**Issue by aboda1986** [flutter/flutter#27341]
i want to say many thanks to flutter team for hard work, it's good to create official flutter team package to fetch current location for Android & IOS. the current packages (geolocator, location) is not working well, and need to update.

**Comment by kangwang1988** [comment]
I think it's a feature request for plugin.
@aboda1986 
Please provide more information/details about this, including but not limited to:
What do you expect the plugin to provide?
Why the plugin you mentioned is not working well?
etc.
Besides, now flutter provide official plugins including: google_maps_flutter & location_background, you can also have a look.

**Comment by aboda1986** [comment]
@kangwang1988 
thanks for replying.
1-  the plugin should request location permission and fetch current location in Android & IOS
2- geolocator & location currently not supporting AndroidX, 
geoLocator plugins : return NULL when try to fetch position
Location plugins working well in Android But crashes in IOS!

i see location_background plugins, i thinks this is what we need but not support Android for now.

**Comment by kangwang1988** [comment]
cc @cyanglaz

**Comment by DebkanchanSamadder** [comment]
As my flutter app heavily relies on location and mapping, from my perspective these features should be extremely helpful in an official location plugin.

0. **Background location tracking** (Very Important)
1. Exposing permission as both a return value of a callable method and a stream.
2. A distance and time filter like [Geolocator](https://pub.dev/packages/geolocator)
3. Straightforward geofencing.
4. `accuracy`, `altitude`, `speed`, `heading`,`speedAccuracy` properties of the `position` object just like [Geolocator](https://pub.dev/packages/geolocator).

**Comment by kf6gpe** [comment]
geolocator isn't supported by the Flutter team; I'd suggest filing issues for geolocator [here](https://github.com/Baseflow/flutter-geolocator).
