### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Panapandorama** [flutter/flutter#27342]
I can't get past the install steps.  Git is installed and running.  It is unbelievable poor technology that there is no Install Tool and users have to contend with errors like these that originates deep within DOS BAT and ENV file and settings.

```
C:\Users\Dang>flutter doctor -v
fatal: not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to C:\Users\Dang\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by kangwang1988** [comment]
@Panapandorama 
paste content: C:\Users\Dang\flutter_07.log please.
@zoechi  Maybe a broken installation?

**Comment by zoechi** [comment]
Which directory did you install Flutter to?
Please post the output of `git --version`

**Comment by Panapandorama** [comment]
Installed to C:\Dev\Flutter

C:\Users\Daang>git --version
git version 2.20.1.windows.1

I have deleted all installation and is downloading the giant ZIP again...it's past midnight and I'll get few coffees in the early morning and try again.

**Comment by zoechi** [comment]
Another way to install would be to delete `C:\Dev\flutter` and in `C:\Dev` run `git clone git@github.com:flutter/flutter.git` and `flutter doctor`

**Comment by zoechi** [comment]
> paste content: C:\Users\Dang\flutter_07.log please.

Would still be interesting to see

**Comment by Panapandorama** [comment]
Tried the good suggestion from Zoechi, it does not resolve the issue but provided some assistance towards the possible cause.  Below is the CMD commands and results.  I tried a different install folder of C:\Temp\Flutter and got the same results as below...going to try a different computer and see...this appears to be a permission issue either on Git or my computer.

Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Dang>cd\dev

C:\Dev>rd flutter/s
flutter, Are you sure (Y/N)? y

C:\Dev>git clone git@github.com:flutter/flutter.git
Cloning into 'flutter'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Dev>

**Comment by zoechi** [comment]
@Panapandorama are you behind a proxy or do you use self-signed certificates in your network?

**Comment by Panapandorama** [comment]
Solved it.  Visited https://github.com/flutter/flutter and found the Clone Command.

C:\Dev\Flutter>git clone https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 154268, done.
remote: Total 154268 (delta 0), reused 0 (delta 0), pack-reused 154268
Receiving objects: 100% (154268/154268), 51.35 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (116942/116942), done.
Checking out files: 100% (3048/3048), done.
