### ISSUE TITLE
'NSMachErrorDomain' error happens when running `flutter run `

### ISSUE THREAD

**Issue by genglei01** [flutter/flutter#27347]
'NSMachErrorDomain' error happens when running `flutter run `

THe log as the following:

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=NSMachErrorDomain, code=-308):
The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)
  Command: /usr/bin/xcrun simctl install D6C4D318-AF08-4DBB-8576-A68F63AD4F99

**Comment by kangwang1988** [comment]
@genglei01 
I'm sure it's a iOS(Simulator) problem instead of flutter one.
Please consider asking support questions in one of the other channels listed at http://flutter.io/support
