### ISSUE TITLE
Center Floating Label for Highlighted TextField

### ISSUE THREAD

**Issue by raveesh-me** [flutter/flutter#27357]
What I want to implement:

![screenshot 30](https://user-images.githubusercontent.com/15698263/52057021-f1dc3a80-2589-11e9-8bc4-9d86a9309c74.png)

I want to implement a textfeild whose floating label is horizontally centered.
What I am able to implement:

![screenshot from 2019-01-31 19-03-54](https://user-images.githubusercontent.com/15698263/52057438-01a84e80-258b-11e9-880d-0e053f55d687.png)

my code:
```dart
TextField(
                textAlign: TextAlign.center,
                controller: emailController,
                decoration: InputDecoration(
                  labelText: "Email ID",
                  labelStyle: TextStyle(
                    color: Colors.grey,
                  ),
                  border: OutlineInputBorder(),
                  focusedBorder: OutlineInputBorder(),
                ),
              ),
```

Can't find a way to center the floating label. Any help?

**Comment by fateh491989** [comment]
Just Go in TextField.dart and make the required changes

**Comment by 420907** [comment]
Can we make label float upward even if it is not having any text and focus on it

**Comment by Neuromancer93** [comment]
Is there a solution to this yet? running into a similar issue. I simply want to make sure the floating label does not go outside the textfield border.

**Comment by GopiTheLegend** [comment]
Directionality(
textDirection : TextDirection.rtl //this change both hint label text to right to left 
TextFormField(
TextDirection : TextDirection.ltr // this change text from left to right 
)
)
//use both property to handle multiple type Decoration ...

**Comment by AxesandGrinds** [comment]
Any solution to this? 1 year later, no news?

**Comment by ben04** [comment]
That would be a great extension for the textfield! I'm waiting for it as well.

**Comment by alejo9719** [comment]
I need it too. Or at least, move the label a little bit to the right as it doesn't look good with the border radius I'm using.

**Comment by bionara** [comment]
I'd like to be able to do a label that is always fixed above the input - no float animation. All options seem to either destroy it, or have it move up to the top on focus. Any idea?

like this, on load, blur, focus, error - everything
![image](https://user-images.githubusercontent.com/3264113/77950263-251a7680-72c0-11ea-9a9a-f30350527084.png)

**Comment by Royal777** [comment]
Hello everyone! I need this solution too! But I have not fund this yet.
So i changed my code back to ` textAlign: TextAlign.start` and added this to InputDecoration of TextFormField (it should work in TextForm either) :
```
decoration: InputDecoration(
        isDense: true,
        contentPadding: EdgeInsets.symmetric(horizontal: 30),
      )
``` 
so label and text moved closer to center.

I know that it looks not so right, but I have not found a better decision.

**Comment by italo-medeiros11** [comment]
> I'd like to be able to do a label that is always fixed above the input - no float animation. All options seem to either destroy it, or have it move up to the top on focus. Any idea?
> 
> like this, on load, blur, focus, error - everything
> ![image](https://user-images.githubusercontent.com/3264113/77950263-251a7680-72c0-11ea-9a9a-f30350527084.png)

______________________________________________________________________________________

You could use a TextFormFied like so:

TextFormField( 
decoration: InputDecoration(floatingLabelBehavior:FloatingLabelBehavior.always),
 ),

**Comment by guidezpl** [comment]
I can look at adding this

@raveesh-me (and anyone interested) please chime in. If you were able to center the floating label, would it 

a) always be centered?
b) only be centered when it was floating

**Comment by MagedRefaatM** [comment]
I found this solution online : 
  
try this --
        
FocusNode focusNode = FocusNode();
bool isFocused = false;

  @override
  void initState() {
    focusNode.addListener(_onFocusChange);
    super.initState();
  }

  void _onFocusChange() {
    setState(() => isFocused = !isFocused);
  }

here's your widget

                Stack(
                  children: <Widget>[
                    Container(
                      padding: const EdgeInsets.only(top: 10),
                      child: TextFormField(
                        focusNode: focusNode,
                        decoration: InputDecoration(
                          border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(5)),
                        ),
                      ),
                    ),
                    Align(
                      alignment: Alignment.topCenter,
                      child: Container(
                        color: Colors.white,
                        child: Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 8.0),
                          child: Text(
                            'Address',
                            style:
                            isFocused ? TextStyle(color: Colors.blue[800]) : null,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),

**Comment by GGotha** [comment]
Someone found the solution?

**Comment by justinmc** [comment]
Please take a look at https://github.com/flutter/flutter/pull/90157 and its design doc https://docs.google.com/document/d/1sxP91vZiY7McmSMmzrboklIJWQ_6pSS9MBSCrQq016M/edit?pli=1# if you're interested in this feature!

**Comment by werainkhatri** [comment]
> I need it too. Or at least, move the label a little bit to the right as it doesn't look good with the border radius I'm using.

@alejo9719 You can fix that by adding an appropriate `InputDecoration.contentPadding`, so that the start of the label and the text align with the right end of the border curve.
