### ISSUE TITLE
App gets crashed on launch in physical device

### ISSUE THREAD

**Issue by fayaz07** [flutter/flutter#27359]
I am facing the same issue, the app crashes when I launch it on physical device. Can I have a solution for this, I have stated the log below
```
F/libc ( 5082): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 5133 (.vritgroup.vrit)

Build fingerprint: 'samsung/j6ltedx/j6lte:8.0.0/R16NW/J600GDXU3ARL1:user/release-keys'
Revision: '2'
ABI: 'arm'
pid: 5082, tid: 5133, name: .vritgroup.vrit >>> com.vritgroup.vrit <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
r0 c5bfdaa4 r1 c5bfdaf0 r2 b985dd06 r3 00000008
r4 00000000 r5 c5bfda98 r6 c8c3e3ec r7 7c3a3d12
r8 b985dd06 r9 b0406162 sl 71463ef2 fp 7c3a3f36
ip c5bfe014 sp 7c3a0796 lr 71200e7b pc ea71bc00 cpsr 60070010
backtrace:
#00 pc 00018c00 /system/lib/libc.so (sigsetjmp+136)
#1 pc 0050ce79 /system/framework/arm/boot-framework.oat
Lost connection to device.
```

**Comment by zoechi** [comment]
Is this a release or a debug build?

Can you please post `flutter doctor -v`

**Comment by fayaz07** [comment]
debug build
root@fayaz:~/AndroidStudioProjects/FlutterProjects/vr_it# flutter doctor -v
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[✓] Flutter (Channel master, v1.2.1-pre.50, on Linux, locale C.UTF-8)
    • Flutter version 1.2.1-pre.50 at /usr/local/flutter
    • Framework revision dbd1b317ff (15 hours ago), 2019-01-30 21:31:44 -0500
    • Engine revision 15f2b92cce
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 71bee8f05e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /root/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
root@fayaz:~/AndroidStudioProjects/FlutterProjects/vr_it#

**Comment by fayaz07** [comment]
@zoechi is this issue resolved?

**Comment by kangwang1988** [comment]
@fayaz07 
Can you provide a demo to reproduce this issue?
Besides, I can't find any hint that flutter is the cause for the crash given the stack you provided.

**Comment by fayaz07** [comment]
@kangwang1988 do you mean a demo video or the code?

**Comment by kangwang1988** [comment]
@fayaz07 
Code

**Comment by fayaz07** [comment]
import 'package:flutter/material.dart';
void main(){
  runApp(new MaterialApp(
    home: Splash(),
  ));
}
class Splash extends StatelessWidget{
  
  @override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;

    return Scaffold(
      body: Column(
        children: <Widget>[
          SizedBox(height: height*1/10,),
          SizedBox(child: Image.asset('assets/first_screen.png'),height: height*4/10,width: width*8/10,),
          SizedBox(height: height*2/10,),
          Center(child: CircularProgressIndicator(),)
        ],
      ),
    );
  }
}

**Comment by fayaz07** [comment]
I observed that this happens only in linux operating system, but when I tried in windows it worked fine. Even I have re-installed flutter, android dependencies but the result is same

**Comment by fayaz07** [comment]
it happened because of facebook login package

**Comment by REX51** [comment]
Is there any solution to this issue? I am also facing the same situation and ya I am using linux(ubuntu 18.04) too.

**Comment by REX51** [comment]
> it happened because of facebook login package

Can you explain more?

**Comment by dogukankse** [comment]
I have the same issue but I didn't use facebook login package. 
I use those:
> flutter_auth_buttons: ^0.5.0
  flutter_svg:
  firebase_core: ^0.4.0+6
  firebase_analytics: ^3.0.3
  cloud_firestore: ^0.12.5+2
  firebase_auth: ^0.11.1+7
  google_sign_in: ^4.0.2
  uuid:

My os is Win10 1903.
The only similarity between this issue and mine is I also use assets(a PNG and an SVG).
flutter doctor -v :

> [√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18362.175], locale tr-TR)                  
• Flutter version 1.5.4-hotfix.2 at C:\flutter
• Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700                                                • Engine revision 52c7a1e849                                                                                            
• Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)                                     
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at C:\Users\nerod\AppData\Local\Android\sdk                                                               
• Android NDK location not configured (optional; useful for native profiling support)                                   • Platform android-28, build-tools 28.0.3                                                                               
• Java binary at: C:\Users\nerod\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156\jre\bin\java       
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
• All Android licenses accepted.                                                                                    
[√] Android Studio (version 3.4)                                                                                            
• Android Studio at C:\Users\nerod\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156                  
• Flutter plugin version 36.1.1                                                                                         
• Dart plugin version 183.6270                                                                                          
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)                                       
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
• IntelliJ at C:\Users\nerod\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7141.44                               • Flutter plugin version 36.0.7                                                                                         
• Dart plugin version 191.7830                                                                                      
[√] VS Code (version 1.35.1)                                                                                                
• VS Code at C:\Users\nerod\AppData\Local\Programs\Microsoft VS Code                                                    • Flutter extension version 3.1.0                                                                                   
[√] Connected device (1 available)
• SM J710FQ • 192.168.1.5:5555 • android-arm • Android 8.1.0 (API 27)                                               
• No issues found!  


Also, this issue occurs randomly. I started to debug process couple times on IntelliJ and its randomly solved by itself.

**Comment by Loopex2019** [comment]
This happens to me in Windows too .

**Comment by mraleph** [comment]
Duplicate of #27077
