### ISSUE TITLE
TextFormField forces whole screen rebuild method on focus change.

### ISSUE THREAD

**Issue by jozzi05** [flutter/flutter#27351]
I tried to implement a simple form with 2 text inputs, but I encountered a weird problem. When the form is displayed on the next page opened via 
```Dart
 Navigator.of(context).pushReplacement(...)
```
 every time when inputs change focus the whole screen rebuilds. Below I added simple example to reproduce this issue. 

## Code to reproduce issue

```Dart
import 'package:flutter/material.dart';
 
void main() => runApp(MyApp());
 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Form Validation Demo',
      home: MyCustomForm(),
    );
  }
}
 
class MyCustomForm extends StatefulWidget {
  @override
  MyCustomFormState createState() {
    return MyCustomFormState();
  }
}
 
class MyCustomFormState extends State<MyCustomForm> {
  final _formKey = GlobalKey<FormState>();
 
  @override
  Widget build(BuildContext context) {
    print('REBUILD MyCustomFormState');
    return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.arrow_forward),
        onPressed: () {
          Navigator.of(context).pushReplacement(
              MaterialPageRoute(builder: (BuildContext context) => MyCustomForm()));
        },
      ),
      body: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextFormField(),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: TextFormField(),
            ),
          ],
        ),
      ),
    );
  }
}
```
## Steps to Reproduce issue

1. Open app
2. Change focus from first to second input
* 'REBUILD MyCustomFormState' is printed once on app start
3. Click on FAB
4. Change focus from first to second input
* 'REBUILD MyCustomFormState' is printed everytime focus is changed

## Enviroment

iOS simulator -> iPhone XR - 12.1

**Comment by zoechi** [comment]
This is because the screen size changes when the keyboard appears.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by jozzi05** [comment]
@zoechi I changed my example. Could you please explain me why widget is being recreated (not rebuild) on TextFormField focus lost? If you run my example you will see that this happens only when a new widget is being displayed via Navigator. If Widget is displayed as `home` everything works as expected. I don't think this is related to screen size change when the keyboard appears.

**Comment by zoechi** [comment]
Pages added by the router are re-created when another route is added. This is known and working as intended.

**Comment by jozzi05** [comment]
So how should I keep my state if my Widget is re-created and previous data is erased whenever I click on TextFormField? Am I doing something wrong?

**Comment by zoechi** [comment]
I'd suggest to ask on StackOverflow how others dealt with it. It's a common question.

**Comment by behnam-lum** [comment]
Although it is closed, still the root cause of it is something else which I think should be fixed.
Take a look at this issue: https://github.com/flutter/flutter/issues/37878

**Comment by amirtabasi** [comment]
> @zoechi thanks for your responses :) For people encountering the same issue. Just put your initial state in `initState`. I know, it makes sense, right? Even though the widget is re-created, initState is fired only once, so you will not encounter problems with a re-created state. :)
> 
> Should be:
> 
> ```dart
> class ExampleWidget extends StatefulWidget {
>   final initialData;
> 
>   ExampleWidget({this.initialData, Key key}) : super(key: key);
> 
>   @override
>   ExampleWidgetState createState() {
>     return ExampleWidgetState();
>   }
> }
> 
> class ExampleWidgetState extends State<ExampleWidget> {
>   ViewModel _viewModel;
> 
>   @override
>   void initState() {
>     super.initState();
>     _viewModel = ViewModel(
>       initialData = widget.initialData,
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Text(_viewModel.initialData.toString());
>   }
> }
> ```
> 
> instead of:
> 
> ```dart
> class ExampleWidget extends StatefulWidget {
>   final ViewModel viewModel;
> 
>   ExampleWidget(this.initialData, {Key key})
>       : viewModel = ViewModel(
>           initialData = initialData,
>         ),
>         super(key: key);
> 
>   @override
>   ExampleWidgetState createState() {
>     return ExampleWidgetState();
>   }
> }
> 
> class ExampleWidgetState extends State<ExampleWidget> {
>   @override
>   Widget build(BuildContext context) {
>     return Text(widget.viewModel.initialData.toString());
>   }
> }
> ```

a lot of thanks ! this solve my problem !! :) 👍

**Comment by sayami007** [comment]
> @zoechi thanks for your responses :) For people encountering the same issue. Just put your initial state in `initState`. I know, it makes sense, right? Even though the widget is re-created, initState is fired only once, so you will not encounter problems with a re-created state. :)
> 
> Should be:
> 
> ```dart
> class ExampleWidget extends StatefulWidget {
>   final initialData;
> 
>   ExampleWidget({this.initialData, Key key}) : super(key: key);
> 
>   @override
>   ExampleWidgetState createState() {
>     return ExampleWidgetState();
>   }
> }
> 
> class ExampleWidgetState extends State<ExampleWidget> {
>   ViewModel _viewModel;
> 
>   @override
>   void initState() {
>     super.initState();
>     _viewModel = ViewModel(
>       initialData = widget.initialData,
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Text(_viewModel.initialData.toString());
>   }
> }
> ```
> 
> instead of:
> 
> ```dart
> class ExampleWidget extends StatefulWidget {
>   final ViewModel viewModel;
> 
>   ExampleWidget(this.initialData, {Key key})
>       : viewModel = ViewModel(
>           initialData = initialData,
>         ),
>         super(key: key);
> 
>   @override
>   ExampleWidgetState createState() {
>     return ExampleWidgetState();
>   }
> }
> 
> class ExampleWidgetState extends State<ExampleWidget> {
>   @override
>   Widget build(BuildContext context) {
>     return Text(widget.viewModel.initialData.toString());
>   }
> }
> ```

It is for the case of StatefulWidget but what about stateless widget. 
Whenever the onscreen keyboard pops up, my whole screen is refreshed.

![image](https://user-images.githubusercontent.com/12579109/66805866-d2cddf00-ef45-11e9-8755-48d5102e0665.png)

**Comment by toando0612** [comment]
> > @zoechi thanks for your responses :) For people encountering the same issue. Just put your initial state in `initState`. I know, it makes sense, right? Even though the widget is re-created, initState is fired only once, so you will not encounter problems with a re-created state. :)
> > Should be:
> > ```dart
> > class ExampleWidget extends StatefulWidget {
> >   final initialData;
> > 
> >   ExampleWidget({this.initialData, Key key}) : super(key: key);
> > 
> >   @override
> >   ExampleWidgetState createState() {
> >     return ExampleWidgetState();
> >   }
> > }
> > 
> > class ExampleWidgetState extends State<ExampleWidget> {
> >   ViewModel _viewModel;
> > 
> >   @override
> >   void initState() {
> >     super.initState();
> >     _viewModel = ViewModel(
> >       initialData = widget.initialData,
> >     );
> >   }
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     return Text(_viewModel.initialData.toString());
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead of:
> > ```dart
> > class ExampleWidget extends StatefulWidget {
> >   final ViewModel viewModel;
> > 
> >   ExampleWidget(this.initialData, {Key key})
> >       : viewModel = ViewModel(
> >           initialData = initialData,
> >         ),
> >         super(key: key);
> > 
> >   @override
> >   ExampleWidgetState createState() {
> >     return ExampleWidgetState();
> >   }
> > }
> > 
> > class ExampleWidgetState extends State<ExampleWidget> {
> >   @override
> >   Widget build(BuildContext context) {
> >     return Text(widget.viewModel.initialData.toString());
> >   }
> > }
> > ```
> 
> It is for the case of StatefulWidget but what about stateless widget.
> Whenever the onscreen keyboard pops up, my whole screen is refreshed.
> 
> ![image](https://user-images.githubusercontent.com/12579109/66805866-d2cddf00-ef45-11e9-8755-48d5102e0665.png)

You have to put it as Stateful Widget. Otherwise, Stateless will create new instance each time TextField is focused
