### ISSUE TITLE
Conflicting category definitions for `+[NSError flutterError]`

### ISSUE THREAD

**Issue by nickolas-pohilets** [flutter/flutter#27361]
Every plugin defines it's own category for `NSError` with `+[NSError flutterError]`. If app uses multiple plugins, these categories will compete in ObjC runtime and only one of the method implementations will be used by all the plugins. Most of them seem to be implemented identically, so some combinations of plugin may work correctly, for example Google Sign-in has a different implementation.

In my specific case, I've got a Firestore error, which was interpreted as Google Sign-in error, which is pretty confusing.

Few possible solutions:

* each plugin should use unique prefix for all category methods
* don't use ObjC categories, just static C functions.
* move category to common dependency for all the plugins, maybe to the `Flatter.framework` itself.
* get rid of `FlutterError` altogether and use `NSError`.

Examples:
https://github.com/flutter/plugins/blob/master/packages/google_sign_in/ios/Classes/GoogleSignInPlugin.m#L23
https://github.com/flutter/plugins/blob/master/packages/firebase_ml_vision/ios/Classes/FirebaseMlVisionPlugin.m#L8
https://github.com/flutter/plugins/blob/eaa1388b11ac3ee6143ad782e573b9b9e314bc4b/packages/firebase_database/ios/Classes/FirebaseDatabasePlugin.m#L18
https://github.com/flutter/plugins/blob/eaa1388b11ac3ee6143ad782e573b9b9e314bc4b/packages/firebase_storage/ios/Classes/FirebaseStoragePlugin.m#L14

**Comment by kangwang1988** [comment]
@nickolas-pohilets 
Good point, I will prefer the static Function approach as it's just a simple logic now.

**Comment by kangwang1988** [comment]
@nickolas-pohilets 
Good point, I think the prefix approach would be better.

**Comment by cyanglaz** [comment]
@cbracken Do we have any guideline for category naming convention in flutter plugins?

**Comment by cyanglaz** [comment]
Fixed with https://github.com/flutter/plugins/pull/1226

**Comment by kroikie** [comment]
@nickolas-pohilets

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/471. Any further collaboration will be done there.
