### ISSUE TITLE
Webview Content Security Policy

### ISSUE THREAD

**Issue by skjagini** [flutter/flutter#27372]
How do I pass Content Security Polity meta tags to WebView.   I am getting an error similar to https://stackoverflow.com/questions/38277526/webview-content-security-policy  when launching an Youtube URL, just wondering how to pass meta tags to the webview. And also is it possible to pass an IFrame?

               Container(                
                    child: WebView(
                      initialUrl: 'https://www.youtube.com/embed/abc',
                      javaScriptMode: JavaScriptMode.unrestricted,
                    )),

Any ideas?

**Comment by Papashkin** [comment]
@skjagini  how did you solve the problem?
Because I have the same error in webView.
