### ISSUE TITLE
Speed up 'pub get' in bots

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2737]
We could speed things up by prefilling our cache with the version data of the packages we know we use:
- Run `pub cache add <pkg>` for each package in the transitive closure of every package possibly used by the packages in Flutter.
- Run `pub get --offline` on each package.

This would have the added advantage of adding friction to adding new dependencies.

**Comment by Hixie** [comment]
This wasn't super successful but maybe https://github.com/dart-lang/pub/issues/1396 will provide a new path.

**Comment by eseidelGoogle** [comment]
In case you're curious as to current speed of "flutter update-packages" (which just calls pub get) it's ~75s on our Linux flutter/flutter bot:
https://build.chromium.org/p/client.flutter/stats/Linux
And 90s on our Mac flutter/flutter bot:
https://build.chromium.org/p/client.flutter/stats/Mac

**Comment by matanlurey** [comment]
FWIW, I hit 134s locally on my Macbook:

```
flutter update-packages
Running "flutter packages get" in automated_tests...  5.5s
Running "flutter packages get" in complex_layout...  11.6s
Running "flutter packages get" in microbenchmarks...  5.4s
Running "flutter packages get" in bots...             3.5s
Running "flutter packages get" in devicelab...        6.3s
Running "flutter packages get" in channels...         5.3s
Running "flutter packages get" in flavors...          5.5s
Running "flutter packages get" in platform_interaction...  5.3s
Running "flutter packages get" in ui...               5.4s
Running "flutter packages get" in manual_tests...     5.5s
Running "flutter packages get" in tools...            4.1s
Running "flutter packages get" in catalog...          5.3s
Running "flutter packages get" in flutter_gallery...  6.1s
Running "flutter packages get" in flutter_view...     3.5s
Running "flutter packages get" in hello_world...      5.1s
Running "flutter packages get" in layers...           5.1s
Running "flutter packages get" in platform_channel...  5.4s
Running "flutter packages get" in platform_channel_swift...  5.5s
Running "flutter packages get" in platform_view...    3.8s
Running "flutter packages get" in stocks...           5.8s
Running "flutter packages get" in flutter...          5.2s
Running "flutter packages get" in flutter_driver...   8.0s
Running "flutter packages get" in flutter_localizations...  5.6s
Running "flutter packages get" in flutter_test...     5.3s
Running "flutter packages get" in flutter_tools...    0.6s
Downloading lcov data for package:flutter...          0.3s

Ran 'pub' 25 times and fetched coverage data in 134.0s.
```

It would be nice to get some parallelism/caching here

**Comment by DanTup** [comment]
I was trying to speed this up in the Dart Code builds on Travis/AppVeyor too.. I noticed if I make it run these in parallel it takes about half the time (Travis Linux):

Before:
```dart
for (Directory dir in packages) {
  await pubGet(context: PubContext.updatePackages, directory: dir.path, checkLastModified: false);
  count += 1;
}
```
```
Downloading Material fonts...
Ran 'pub' 31 times and fetched coverage data in 127.1s.
```

After:
```dart
await Future.wait(
   packages.map((Directory dir) => pubGet(context: PubContext.updatePackages, directory: dir.path, checkLastModified: false))
);
```
```
Downloading Material fonts...
Ran 'pub' 31 times in 55.6s.
Ran 'pub' and fetched coverage data in 55.7s.
```

@Hixie is it worth adding a `--concurrent` flag or something and using it on the bots?

I think there are other things that are taking time that may be addressable too - like I think there are snapshots being written into the `.dart_tool` folder inside each package, so although we're caching the pub-cache folder, this may be happening on every build.

**Comment by DanTup** [comment]
Ug, that sounds kinda scary (esp. if it doesn't write any errors when doing that). In VS Code we run `pub get` when you save `pubspec.yaml` so if you modified multiple and hit `Save All` we'll do exactly this.

I checked my logs again, and I did have a hang towards the end of the run (this isn't unusual - I have an open VS Code bug about it hanging outside of my Code frequently on Travis - however I now see there were Dart processes still running in the background (I run `ps` and fail builds on this so maybe it's related).

I'll abort this for now then but might see if I can find any open issues on `pub`'s concurrency. Even if I handled `Save All` better when there are multiple pubspecs, it's easy for users to have multiple editors, run commands in their own terminals, etc.. If this corrupts things with no obvious output, it could result in hard-to-repro/track-down bugs.

**Comment by eseidelGoogle** [comment]
@munificent should be able to tell us if concurrency is supported or not. :)

**Comment by munificent** [comment]
No, as far as I know, pub doesn't do any locking to manage concurrent access to its central cache.

Do you have a good sense of where the time is going? I wouldn't be surprised if most of the time was in generating snapshots like @DanTup says. Concurrency might not the best path to improve this. If it is, it's possible to add locking to pub when it updates its cache.

**Comment by DanTup** [comment]
I tried turning on the verbose output, but it didn't include timings so it was hard to know specifically where the time went. I'll try putting timestamps on the output lines to see if it helps. I think we use --`no-precompile` for the update-packages step.

Although concurrency might not be the only/best fix here, it does still seem a bit risky not supporting it generally as it's easy for multiple editors/terminals/whatever to end up running it (especially if the failure is silent corruption).

**Comment by DanTup** [comment]
I've been looking at a few things on the bots to see if we can speed them up (https://github.com/flutter/flutter/issues/20036). I noticed a huge discrepancy in timings for the setup across OSes. The Linux ones are several times faster than macOS and Windows (Windows is often 5x as slow as Linux just on the first invocation of `flutter` which fetches packages, compiles them, etc.).

![screen shot 2018-08-02 at 10 01 21 am](https://user-images.githubusercontent.com/1078012/43574505-45e75002-963c-11e8-8b65-9d18adac89cc.png)

I can't been able to get good timestamps for everything yet, but in the default trace output from Pub I'm seeing things like this:

<img width="1233" alt="screen shot 2018-08-02 at 10 11 09 am" src="https://user-images.githubusercontent.com/1078012/43574570-6f8fa576-963c-11e8-89f4-c98f00f60057.png">

The HTTP requests from Windows are much slower than Linux (this one is particularly bad - 1.7s for Windows, 0.009s for Linux, but they're all a lot slower). There are a *lot* of HTTP requests happening and if they're sequential (I don't know if they are, they're logged like they are, but this is inside pub) so it's possible this is all adding up.

I think the extra latency is likely where the VMs are running (I think Linux are running on Google Cloud, so probably very close to pub, whereas Windows may be on Azure?) which isn't Pub's fault, but it may suggest that doing some of this concurrently (or having some way to reduce the number of round trips, such as a bulk download) may have a big impact.

**Comment by DanTup** [comment]
I tried running a few different configurations of Windows in case we just had skimpy boxes, but it had no real impact on the overall time (these builds are only running the setup code, no tests; so it's almost exclusively cloning/downloading packages/snapshotting/etc.).

![screen shot 2018-08-02 at 10 16 33 am](https://user-images.githubusercontent.com/1078012/43574902-44d72dc6-963d-11e8-9d5d-7b88300d7bc1.png)

**Comment by DanTup** [comment]
Looking at this log again - biggest culprits are:

> Version solving took 0:00:46.837103 seconds

And then downloads of some packages:

```
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/packages/convert/versions/2.0.2.tar.gz
    | took 0:00:12.962220
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/packages/shelf_packages_handler/versions/1.0.4.tar.gz
    | took 0:00:18.026729
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/packages/csslib/versions/0.14.4+1.tar.gz
    | took 0:00:16.033047
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/packages/source_maps/versions/0.10.7.tar.gz
    | took 0:00:09.082112
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/packages/string_scanner/versions/1.0.3.tar.gz
    | took 0:00:07.985422
```

I don't know if this issue is specific to Cirrus or not (or maybe just locations far from the pub servers), but I'll do some timing on my Windows machine from here shortly. I might also see if I can find out where these boxes are running. If they're on Azure, I wonder if we can have them spawned in a data centre close to pub?

**Comment by DanTup** [comment]
On my Windows box (which is in the UK, and on WiFi), if I clear Flutter's cache folder and also my whole Pub Cache folder, I get times of around 90 seconds for the first Flutter run (downloading/unzipping SDK, getting flutter_tools ready to use) and then around 75 seconds for update-packages.

That's a total of about 3 minutes. That's not great, but it's nothing like the 10 mins seen on Cirrus. So, I think Cirrus has additional issues beyond what this issue was about. I'll see if I can track that down first and then come back to this.

**Comment by munificent** [comment]
> Although concurrency might not be the only/best fix here, it does still seem a bit risky not supporting it generally as it's easy for multiple editors/terminals/whatever to end up running it (especially if the failure is silent corruption).

> Yeah we had to add pretty comprehensive concurrency protection to Flutter pretty early on because of that kind of thing.

Yeah, I'm with you. It's mostly a question of priority and time. Pub doesn't have a lot of resources allocated to it right now.

**Comment by gspencergoog** [comment]
FYI, the Windows boxes on Cirrus are hosted on Azure.
I have no idea why they would be that much slower, but maybe we're sharing hardware with another virtual instance, slowing us down.  Perhaps when we start paying Cirrus it'll get better, as we'll get scheduled with higher priority.

**Comment by dnfield** [comment]
On Azure I'd be willing to bet almost anything that the bottleneck is disk IO.

Adding more CPU to it won't really help things. If you're sharing a spinning disk on a VM, you're going to be slow.  And unfortunately, the Azure VM classes where you get to better quality storage involve bigger jumps in price.  If we could look at getting Cirrus builds to run on VMs with SSDs, we'd probably see a big jump in performance.

**Comment by DanTup** [comment]
@fkorotkov see above - can you confirm what disks are being used (and whether we have options to change them)?

**Comment by fkorotkov** [comment]
As far as I know there is not way to use SSDs with Azure Container Instances 😥Will add `gcp2016` os type to run windows containers on GCP with it's [limitations](https://cloud.google.com/compute/docs/containers/#mtu_failures).

**Comment by DanTup** [comment]
> Will add `gcp2016` os type to run windows containers on GCP

Let us know if you want us to try enabling it on a branch for testing (though those documented limitations aren't filling me with confidence!)

**Comment by godofredoc** [comment]
After migration to LUCI we will be running pub get once, isolate and then run multiple subbuilds.

**Comment by godofredoc** [comment]
pub_cache is being cached in all the bots.
