### ISSUE TITLE
Text should take a width beyond which it doesn't perform calculations because we know they won't be visible

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2738]
I suspect this is covered by https://github.com/flutter/flutter/issues/224 (which is a huge meta bug) and related to https://github.com/flutter/flutter/issues/162 and could be used to solve https://github.com/flutter/flutter/issues/2677

But as far as I can tell there is no way in our system to tell a Text Widget not to wrap (and say clip instead).

Maybe I'm supposed to wrap my Text widget in a Viewport?

**Comment by Hixie** [comment]
Putting it in a Viewport is the current expected solution. Medium-term, the text API should grow features to control where text will wrap, but even then, you still have to worry about where to put the overflow.

**Comment by abarth** [comment]
> Maybe I'm supposed to wrap my Text widget in a Viewport?

It depends what visual effect you're looking for.  Do you want to be able to scroll to reveal the rest of the text?  Do you have to have some indicator that there's more text (e.g., ellipsis)?  (We don't yet support ellipsis)

**Comment by Hixie** [comment]
@eseidelGoogle Do you have a specific fix in mind here other than using Viewport? I'm not sure what should change for this bug to be resolved.

**Comment by eseidelGoogle** [comment]
Is a viewport efficient?  Will it tell the engine to not bother drawing the rest of the text beyond the clip region?  Maybe I'm asking the wrong question.  I guess I expected Text to do some of this for me, but maybe that's not the flutter way?

**Comment by Hixie** [comment]
Oh, you are asking how to tell Text to stop painting after a certain width. I see. Yeah, that's makes sense.

**Comment by DaveShuckerow** [comment]
From my experience, it's cleanest from a UX perspective to ellipsize text that's limited to a single line, preferrably in either the beginning, middle, or end of the string depending on the use case.  This removes the extra interaction of trying to scroll text while it's also obscurred by your thumb.

**Comment by HansMuller** [comment]
The Material Design spec includes a few examples of two lines of text truncated with an ellipsis.  In real apps with "three-line" lists, I think this would come up a lot.

![components_lists_keylines6](https://cloud.githubusercontent.com/assets/1377460/14467229/29202236-008f-11e6-8a2c-e89fff12adf4.png)

**Comment by Hixie** [comment]
We do ellipsising now, not sure what else to do here.
