### ISSUE TITLE
Version solving failed - doesn't see flutter dart 2.1.0 as actually being >=2.10

### ISSUE THREAD

**Issue by stephenjtyler2** [flutter/flutter#27382]
I don't understand why this fails to version solve....

Output from packages get...

The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because lmp2 depends on flutter_midi >=0.1.0 which requires SDK version >=2.1.0 <3.0.0, version solving failed.

Is 2.1.0 not >= 2.1.0 in the flutterverse?   Ideas other than fork flutter-midi and hack it's pubspec ?

**Comment by jonahwilliams** [comment]
You can use a dependency_override to force a specific package version: https://www.dartlang.org/tools/pub/dependencies#dependency-overrides.

**Comment by stephenjtyler2** [comment]
I am not sure I follow why you say that is pre-release?  It is the version installed by the flutter 1.0.0 win stable installer.    Is there some way to get some version of flutter/dart sdk installed that will meet the condition of requiring sdk >=2.10 ?

**Comment by jonahwilliams** [comment]
I mean pre-release only in the sense of what semver considers in the version string.  That sounds like the correct version from flutter stable.

If you need a newer version of Dart/Flutter you can always switch to the dev or master channels, however those are by nature less stable than the stable branch. If you only need the newer version of a particular package and the dependency override works you might consider holding off until the next stable release.

We do guarantee that our 1st party plugins in packages will continue to work with the current flutter stable until the next stable release. In general though, nothing stops a package author from specifying an overly conservative constraint. That is the case that dependency overrides are for.

**Comment by stephenjtyler2** [comment]
Ok, so I used the dependency overrides successfully by creating a local copy of the package, editing its pubspec to relax its sdk requirement, and using overrides in my consuming project's pubspec to tell it to use the local copy.   Which is ok anyway for me as it turned out the package I wanted to use needed to be enhanced significantly to actually do what I needed.   But I also had to do the same thing with another package purely to edit its its pubspec to relax it's overly conservative dependency constraints to not conflict with other packages I am using.   So it works, but it could get very messy very quickly.   

Would be better I think if there was a way of not having to copy the overly conservative packages and use the local edited copy, but instead to simply say in my pubspec "I depend on package X that thinks it needs Y ver n but it doesn't really, ver m will do just fine, so can you please just pretend it said it only needed m and proceed on that basis?".
