### ISSUE TITLE
Stream and Future error on newest Dart

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#27396]
I upgraded my flutter version, but I'm suffering horrible problems on Stream and Future class.

![image](https://user-images.githubusercontent.com/35518072/52125924-4d352800-2671-11e9-9345-67c1eabb0671.png)

What is the problem and How can I solve it?

**Comment by tb2761** [comment]
For me it works, to go to one of this error. Press ctrl + . and choose the default option. Don't know the specific name.

**Comment by wouterhardeman** [comment]
This is a warning from the analyzer tool. You probably need to update you Flutter SDK version to `sdk: ">=2.1.0 <3.0.0"` in `pubspec.yaml`.

**Comment by baeharam** [comment]
@wouterhardeman  Solved, thanks!
