### ISSUE TITLE
Using double text decoration stikethrough on some devices

### ISSUE THREAD

**Issue by 229106948** [flutter/flutter#27392]
I use Text for example:
```dart
new Text(
                                miaoSha.price,
                                style: new TextStyle(
                                    color: new Color(0xff999999),
                                    decoration: TextDecoration.lineThrough,                                  
                                    decorationStyle: TextDecorationStyle.solid,
                                    fontSize: 14),
                              ),
```
but the line is double in my phone, other's phone is single.

**Comment by Kartik1607** [comment]
Which phone are you using? Can you post a screenshot.

**Comment by 229106948** [comment]
> Which phone are you using? Can you post a screenshot?

oppo and htc also has the problem,xiaomi is normal.

**Comment by darshankawar** [comment]
@229106948 
Is this still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
