### ISSUE TITLE
Weird issue with Flutter Update

### ISSUE THREAD

**Issue by loushou** [flutter/flutter#27403]
I am not sure this is the correct place to bring this up. I have created an SO post about it too, but I dont think it belongs there either. The basic problem is that there seems to be an issue with the updater on the stable branch, when determining the version of dependencies inside of dependencies:

## How to Reproduce / Setup

The project I am working on, up to this point has been using a rather basic, home-brewed model system. We have some functions to consume data, and without much validation, assign it to object keys inside immutable objects. It is rather crude, and we want to standardize on something more widely used, and hopefully robust.

Some recent research has pointed us to the built_value package, because it seems to offer not only a more standard way of defining models, but also can cut down on boiler plate that we have been writing over and over. We found some instructions online for adding this to our project. Essentially, we have to add two dependencies and two dev_dependencies. Here is what the basis pubspec.yaml looks like:

```
name: projectname
description: my project rocks!

version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: 'flutter'
  built_collection: '^4.1.0'
  built_value: '^6.3.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '^1.2.1'
  built_value_generator: '^6.3.0'
```

And this is what flutter doctor says:

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at c:\flutter\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\MYUSER\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • MY PHONE

• No issues found!
```

## Logs / The Issue

On the surface, it looks like everything is ok. But then, in Intellij (where all this above was copied from), I use the flutter 'Packages get' command (even using the commandline version inside the project dir, I get the same results):

```
Running "flutter packages get" in projectname...
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because build_runner >=1.2.0 depends on build_daemon >=0.2.0 which requires SDK version >=2.1.0 <3.0.0, build_runner >=1.2.0 is forbidden.
So, because projectname depends on build_runner ^1.2.1, version solving failed.

pub get failed (1)
Process finished with exit code 1
```

Now, the interesting part is that I have it set to use the 'stable' branch of flutter, which is currently at version `2.1.0-dev.9.4.flutter-f9ebf21297` which flutter doctor is registering as version `2.1.0`. However, when trying to do the packages get command flutter seems to think that `2.1.0-dev.9.4.flutter-f9ebf21297` is not `>=2.1.0 <3.0.0`.

All of the versions for the packages are the latest versions, according to their git repos. Flutter is up to date with the latest stable branch (I have redone this twice now to make sure). Flutter doctor command seems to think that everything is correct... and yet I cannot complete the 'packages get' command because build_daemon (a dep of build_runner) requires `>=2.1.0 <3.0.0` and the flutter script is not recognizing that version `2.1.0-dev.9.4.flutter-f9ebf21297` >= `2.1.0`, which by it's own admission in flutter doctor, it is.

## What I am asking

I have been racking my brain for solutions. I have tried switching to the master branch for flutter manually, but when I run it from Intellij, it switches right back to stable. I have tried a complete reinstall of flutter, and that did not help. I have been fighting with these things for a while now, thinking that I am doing something wrong, and have not made any headway. I have read every piece of documentation I can find on the topic, and nothing seems to indicate that anyone other than me is having this issue. So I am at a loss.

I am reaching out to the community, in an attempt to get this working. I feel like I am missing something glaringly obvious here, and I think having your eyes look at this in addition to mine, will help solve the issue. What do you suggest I do to resolve this issue?

Thanks in advance,
Loushou

**Comment by GaryQian** [comment]
Have you tried a `flutter clean`? Sometimes nuking the /build directory can solve strange dependency issues.

**Comment by jonahwilliams** [comment]
This is working as intended, since according to semvar `2.1.0-anything` is actually `< 2.1.0`.

> I have tried switching to the master branch for flutter manually, but when I run it from Intellij, it switches right back to stable

How did you switch branches? There might be a bug here.

> I am not sure either of those actually solve this issue. We want the latest version of built_value, which requires the latest version of build_runner, which requires the latest version of build_daemon, which requires dart 2.1.0.

Have you tried it? This is exactly what dependency overrides is designed to do, you can point at an older version of any package you depend on transitively. Now, that may not work because build_runner and friends may actually need a very slightly newer version of Dart - but that seems unlikely in this case

**Comment by zoechi** [comment]
Alternatively you can use older versions of the *build* packages that are compatible with `2.1.0-...` packages.
