### ISSUE TITLE
Observatory timeline no longer works with Recorded Streams Profile "All"

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#27408]
To reproduce the issue:
1. `cd examples/flutter_gallery`
2. `flutter run`
3. Open observatory following the link
4. Click timeline link
5. Click "All" in Recorded Streams Profile

It was working fine in v1.2.0 but broken in ToT (af3cdb33dab6092c47453b6cdcb790514caf8e6b)

**Comment by jason-simmons** [comment]
The fix for this has landed in Dart (https://github.com/dart-lang/sdk/commit/aaf97448b0fa67d7eaa701ff20e59cd873e1bf6e) but hasn't yet rolled into the framework

As a workaround, you can select all streams except for "CompilerVerbose"

**Comment by liyuqian** [comment]
Thanks! Added "waiting for PR to land"
