### ISSUE TITLE
Custom service registration works on simulator but not on device

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2740]
This originally came up in https://github.com/flutter/firechat-flutter/issues/28 where Firebase works on the simulator but not the device (since the Firebase simulator dylib doesn't run on physical iOS devices).

### Steps to Reproduce
* Build firechat-flutter step_5

### Flutter Version

Flutter from git@github.com:flutter/flutter (on hackathon)
Framework: e1f0d8c974a58977e19ab685d2eb323d2d9becd4 (16 hours ago)
Engine:    5e68565d713cbb89e0d60e4c635cf7a9e4b2b855

[✓] The iOS toolchain is fully installed.
[✓] The Android toolchain is fully installed.
[✓] The Atom development environment is fully installed.

### Logs

Simulator:
Mar 16 12:43:10 jackson-macpro Runner[57947]: [INFO:FlutterDynamicServiceLoader.mm(106)] 1 custom service definitions registered

Device:
Mar 16 13:31:37 Collins-iPhone Runner[12771] <Notice>: [INFO:FlutterDynamicServiceLoader.mm(106)] 0 custom service definitions registered

**Comment by collinjackson** [comment]
@chinmaygarde

**Comment by mpcomplete** [comment]
I wonder if we'd also need separate versions for different device versions (iphone 4 vs 5, android K vs M, android simulator, etc).

**Comment by collinjackson** [comment]
That seems like a good idea, although I think we may be able to live without iphone 4 support in the short term.

**Comment by chinmaygarde** [comment]
This is already supported since the dylib is a fat Mach binary. There is no simulator and device dylib variants. If the custom service definition registration is failing, it could be a packaging issue. I can investigate the same.

For now, the fat binary only contains aarch64 and amd64 variants. For older iPhones, we would also need to pack in the armv7 code. But even that would go inside one single dylib.

**Comment by collinjackson** [comment]
The custom service definition registration is failing on devices, but works fine on the simulator.

Here's the sample app that's failing: https://github.com/flutter/firechat-flutter/tree/master/step_5

**Comment by collinjackson** [comment]
#2769 is higher priority than this right now

**Comment by collinjackson** [comment]
this needs to be fixed before we can do login on an actual iOS device

**Comment by collinjackson** [comment]
@eseidel

**Comment by eseidelGoogle** [comment]
@chinmaygarde does this work now?

**Comment by qchong** [comment]
@chinmaygarde Would be good to have support for iOS devices in time for our I/O'16 codelab release (May 18). How soon do you think this will be implemented?

**Comment by chinmaygarde** [comment]
Fixed on master. Also requires the simulator fix that has landed also.
