### ISSUE TITLE
`flutter run` should fail better if iOS project files are missing

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#27417]
Steps to reproduce:
1. Create a directory with a legitimate `pubspec.yaml` file and with a `lib/main.dart` file.
2. From that directory, do `flutter run`.

Result:
```
Running "flutter packages get" in foo...                         5.5s
Launching lib/main.dart on iPhone 6 in debug mode...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 6caa219ecb139eb5)
Crash report written to /Users/jamesdlin/foo/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

The relevant part of the log file has:
```
FileSystemException: FileSystemException: Cannot open file, path = '/Users/jamesdlin/foo/ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)
```

This is unfriendly and confusing (see https://github.com/google/flutter.widgets/issues/13), especially since it is described as a crash.  The same reproduction steps for Android (from a Linux development environment) *does* catch this situation and provides a friendlier failure mode:

```
Running "flutter packages get" in foo...                            2.9s
Using hardware rendering with device Android SDK built for x86. If you get
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
No application found for TargetPlatform.android_x86.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

We should do the same for iOS.

**Comment by kangwang1988** [comment]
@jamesderlin 
Can we suppose that "Developers should ensure that they are running 'flutter run' in a flutter project created by flutter command"?

**Comment by jamesderlin** [comment]
@kangwang1988 No, people could download Dart packages that provide `lib/` but that don't provide the generated Android and iOS project files. In such cases, I think it's reasonable to require using `flutter create .` first.  See the referenced issue for an example.

Also, if nothing else, this is a parity issue between Android and iOS.
