### ISSUE TITLE
Impossible to change child width inside Expanded()

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#27418]
Hi,

I created a custom bottom nav bar consisting of a Row rendering 3 Expanded children representing tabs (blue in the pic).
![dessin sans titre 1](https://user-images.githubusercontent.com/14275989/52157884-de92b180-26e6-11e9-9b9a-6fddd3072586.png)

Now, I'm trying to render a Container in the middle tab (red in the pic) but I run into a weird problem, I'm able to set the height of this container but when I try to set a custom width for it, it doesn't change anything, the container width stay equal to it's parent's (the Expanded class).

The only way I managed to reduce the container width is by applying a horizontal margin to it but this is not what I want as I need a fixed width.

```
import 'fab_bottom_app_bar.dart';
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(),
    );
  }
}

class TabItem extends StatelessWidget {
  TabItem({this.color});

  final Color color;
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        color: color,
        height: 60,
        child: Container(
          margin: EdgeInsets.symmetric(horizontal: 40),
          color: Colors.purple,
        ),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(color: Colors.orangeAccent),
        bottomNavigationBar: BottomAppBar(
          child: Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              TabItem(color: Colors.blue),
              TabItem(color: Colors.green),
              TabItem(color: Colors.red)
            ],
          ),
          color: Colors.white,
        ));
  }
}

```

This should render something like this:
<img width="383" alt="screen shot 2019-02-02 at 12 28 22 pm" src="https://user-images.githubusercontent.com/14275989/52157892-f0745480-26e6-11e9-854e-6ecc2980197c.png">

But instead render this:
<img width="383" alt="screen shot 2019-02-02 at 12 27 34 pm" src="https://user-images.githubusercontent.com/14275989/52157900-01bd6100-26e7-11e9-9925-81296a169225.png">

Any idea of what's going on ?

Thanks !

```
Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-AU)
    • Flutter version 1.0.0 at /Users/theo/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by Kartik1607** [comment]
Use a `SizedBox` with `Alignment` 
```dart
class TabItem extends StatelessWidget {
  TabItem({this.color});

  final Color color;
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
          height: 60,
          color: color,
          child: Align(
            alignment: Alignment.center,
            child: SizedBox(
              width: 40,
              height: 20,
              child: Container(color: Colors.pink),
            ),
          )),
    );
  }
}
```

**Comment by theochampion** [comment]
@Kartik1607 It worked, thanks ! But can I get more explanation about why the `Align` is needed in that case ?

**Comment by GaryQian** [comment]
Thanks for answering @Kartik1607 , if there is nothing to do on the Flutter-side of the issue, I will close the issue. Please feel free to continue your discussion though!

**Comment by gicocoro** [comment]
use Row
```

class TabItem extends StatelessWidget {
  TabItem({this.color});

  final Color color;
  @override
  Widget build(BuildContext context) {
    return Expanded(

child: Row(
                  children: [
 Container(
          height: 60,
          color: color,
          child: Align(
            alignment: Alignment.center,
            child: SizedBox(
              width: 40,
              height: 20,
              child: Container(color: Colors.pink),
            ),
          )),
],
),

    );
  }
}

```

**Comment by hacker1024** [comment]
@theochampion

It's been a while, but I figured I may as well share this here.
There's some really well-written [documentation](https://flutter.dev/docs/development/ui/layout/constraints) on the subject.

Specifically, this "limitation" is relevant:

> If a child wants a different size from its parent and the parent doesn’t have enough information to align it, then the child’s size might be ignored. Be specific when defining alignment.
