### ISSUE TITLE
re-work flutter build

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2741]
This is related to https://github.com/flutter/flutter/issues/1690, https://github.com/flutter/flutter/issues/1687, and https://github.com/flutter/flutter/issues/1417.

I'd like to rename the current `build` command (for creating flx files) to `build_flx` and make the command hidden. We use it from the xcode project - and for some internal development tasks - but I don't think it needs to be generally visible.

I'd like to then create a new flutter `build` command, which takes some subcommands. The first one would be `apk`, which would be the current `flutter apk` command. So the new cli would be `flutter build apk` (and at some future point we'd get a corresponding `flutter build ipa`). Build might also take a `--clean` option, which would nuke the `build/` dir.

Thoughts?

**Comment by abarth** [comment]
Sounds good.  Why not make "flutter build flx" be a subcommand of build rather than a separate build_flx ?

**Comment by devoncarew** [comment]
That works too, and we'd end up with fewer top-level commands.

**Comment by pylaligand** [comment]
Building an flx file is useful to run an app on Mojo.

**Comment by devoncarew** [comment]
This has landed - the former `flutter build` command is now available at `flutter build flx`.
