### ISSUE TITLE
Reconsider BottomNavigationBar API given updated spec?

### ISSUE THREAD

**Issue by marcoms** [flutter/flutter#27414]
With #27008, the two bar types look more similar (besides the color), and AFAICT the spec doesn't seem to make a distinction between 'shifting' and 'fixed' bottom navigation bars. I also don't know if changing the bottom nav color used to be on the spec, but it's not as of reading today.

Reading through the section on material.io, we see a mixture of different styles and behaviors not necessarily put into certain buckets. For example, the following is the first image on the bottom nav section:

![mio-design_assets_1h5m0bgm_lfxii-6ho4jisem0bcwvg0gl_bottomnav-usage-1](https://user-images.githubusercontent.com/4211302/52151654-c3369080-266b-11e9-8a4e-6c5dd7d05db3.png)

Which currently isn't possible with Flutter since elements of this design are split betwen fixed and shifting modes. See also:

![mio-design_assets_0b6xusjjsulxcavpemk5tz2rgz3c_bottomnav-badging-1](https://user-images.githubusercontent.com/4211302/52151783-1c9ebf80-266c-11e9-905d-0d3b1fdf1a57.png)

We have the same problem here: our shifting mode renders icons and text in white, since it assumes the background will be a contrasting color.

Seems to me like it makes sense to update the API to allow users to control each of these aspects (shifting, inactive labels hidden, inactive opacity, background color, foreground color, etc.) individually.

Thoughts?

**Comment by HansMuller** [comment]
cc @johnsonmh
