### ISSUE TITLE
Different transform behaviour when using AnimatedContainer and Transform.rotate

### ISSUE THREAD

**Issue by rhydiant** [flutter/flutter#27419]
`Transform.rotate` within an `AnimatedContainer` produces a different effect to using it directly. 

In the example below, `Transform.rotate` rotates the container 40 degrees around its centre, whereas the same code within an `AnimatedContainer` appears to rotate it around the top left point.

```
import 'package:flutter/material.dart';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: MyScreen());
}

class MyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: _buildTransformedContainer()),
      // body: Center(child: _buildAnimatedContainer()),
    );
  }

  Widget _buildTransformedContainer() {
    return Transform.rotate(
      angle: 40 * (pi / 180),
      child: _buildContainer(),
    );
  }

  Widget _buildAnimatedContainer() {
    return AnimatedContainer(
        duration: Duration(milliseconds: 300),
        transform: Matrix4.rotationZ((40 * (pi / 180))),
        child: _buildContainer());
  }

  Container _buildContainer() =>
      Container(width: 100, height: 100, color: Colors.blue);
}
```
produces ...

![Outside AnimatedContainer](https://i.stack.imgur.com/EHsg1.png)

replace `// body: Center(child: _buildAnimatedContainer()),` to get ...

![Outside AnimatedContainer](https://i.stack.imgur.com/MWCon.png)

Unsure if this is a bug or my misunderstanding of the API?

## Logs

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-AU)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by jsroest** [comment]
@rhydiant Did you solve your own question? I have exactly the same question. Please let me know if you were able to rotate around the center while using the AnimatedContainer.

**Comment by tp** [comment]
@jsroest If the size of the child widget is know I can get it into the desired final state with the following `transform`:

```dart
    return AnimatedContainer(
      duration: Duration(milliseconds: 200),
      transform: Matrix4.identity()
        ..translate(s, s, 0)
        ..rotateZ((widget.pointingUpwards ? 1 : 0) * pi)
        ..translate(-s, -s, 0),
      child: Container(
        child: Icon(
          Icons.keyboard_arrow_down,
        ),
        width: 20,
        height: 20,
        color: Colors.blue,
      ),
    );
```

Though the in-between animation looks of, it's not properly rotating around the center visually.

So far I wasn't able to figure `Transform.rotate` and its usage of `SingleChildRenderObjectWidget` in how I would be able to build an animated rotation widget myself.

**Comment by rockingdice** [comment]
@rhydiant @jsroest do you have any solution about this issue? I want to scale the AnimatedContainer around the center but with no luck. The transform will apply around the top left corner.  And I cannot find an offset to it as Transform did.
@zoechi should I open a new issue about this?

**Comment by aytunch** [comment]
@rhydiant @rockingdice @tp Why is this issue closed? Is there a reason why only `Rotation` is excluded from the `ImplicitlyAnimatedWidget` series? There are methods for everything else like scale, position, etc..

**Comment by MikaelHermansson** [comment]
tp is on the right way. To get a proper rotating behaviour, you need to divide the widget into a tree with three widgets.the lowest having the translate(-s,-s,0) transform. The widget in the middle having the rotateZ transform, and the upper widget having the translate(s,s,0) transform.  This is because the rotation is around the point (0,0,0). And before rotation, you need to translate the desired center of rotation, to (0,0,0).
