### ISSUE TITLE
When a field type is a class named `Locale`, the intellisense tips would got wrong.

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [flutter/flutter#27428]
## Steps to Reproduce

Here a class named `Locale` like this:
![image](https://user-images.githubusercontent.com/12682063/52163394-634bf280-271c-11e9-9ef9-34821b5e23ea.png)

Then both in VSCode and IDEA, the `Locale` field would got the `dynamic` typehint:
![image](https://user-images.githubusercontent.com/12682063/52163470-73180680-271d-11e9-8deb-30ddee467c6a.png)
![image](https://user-images.githubusercontent.com/12682063/52163487-bbcfbf80-271d-11e9-94f9-03fed067b10d.png)

But the strange thing is that if I just renamed the class, everything works well:
![image](https://user-images.githubusercontent.com/12682063/52163455-292f2080-271d-11e9-86e6-912187817da9.png)

![image](https://user-images.githubusercontent.com/12682063/52163464-57146500-271d-11e9-9aac-83b19eadf937.png)

> flutter analyze
![image](https://user-images.githubusercontent.com/12682063/52163505-f46f9900-271d-11e9-8f1e-a26a1784fa58.png)

> flutter doctor -v
![image](https://user-images.githubusercontent.com/12682063/52163516-1406c180-271e-11e9-9a34-335ddaebd330.png)

**Comment by wouterhardeman** [comment]
Maybe rename your `Locale` object to something else? There is a `Locale` class in Flutter: https://docs.flutter.io/flutter/dart-ui/Locale-class.html

That could be the reason your IDE marks it as dynamic, because it has multiple definitions.

**Comment by GaryQian** [comment]
The dart:intl package and flutter's dart:ui package both include Locale classes. The name is already taken, so we recommend you name it something else. Otherwise, you may also choose to only 'show' the classes and symbols you need like such: `import 'dart:ui' show Blah1, Blah2;` to avoid using up the name.

**Comment by zhengxiaoyao0716** [comment]
Thanks for your suggestions @wouterhardeman @GaryQian , I tried to add the line `import 'dart:ui' hide Locale;` above my code but it didn't work, just got a new warning told me the import is unused.

Anyway, I think that is not the best way to resolve the problem. In my opinion, since the syntax allow me to `override` the built-in class, the syntax-lint should works too. Or maybe it should explicit throw the `ambiguous import` error(warning)?

**Comment by zoechi** [comment]
@zhengxiaoyao0716 this is not a Flutter issue. If you think a language change should be discussed it's better to report it in https://github.com/dart-lang/sdk

**Comment by zhengxiaoyao0716** [comment]
@zoechi  Thanks, I will.
