### ISSUE TITLE
Firebase_auth Docs Error

### ISSUE THREAD

**Issue by Arkangel12** [flutter/flutter#27431]
The method provided in the ReadMe that use `signInWithGoogle` does not exist/work anymore.

I use the one: 

```dart
  Future<String> _testSignInWithGoogle() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth =
        await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    final FirebaseUser user = await _auth.signInWithCredential(credential);
    assert(user.email != null);
    assert(user.displayName != null);
    assert(!user.isAnonymous);
    assert(await user.getIdToken() != null);

    final FirebaseUser currentUser = await _auth.currentUser();
    assert(user.uid == currentUser.uid);

    return 'signInWithGoogle succeeded: $user';
  }
```

Maybe you need to make the change un the [plugin](https://pub.dartlang.org/packages/firebase_auth)

**Comment by Toubap** [comment]
Check their own example which seems to be updated : [Example](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/example/lib/main.dart#L74)

**Comment by rubensdemelo** [comment]
It looks fixed, right?

**Comment by kroikie** [comment]
@Arkangel12

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/469. Any further collaboration will be done there.
