### ISSUE TITLE
Canvas drawImage not working on andriod

### ISSUE THREAD

**Issue by Apurv2017** [flutter/flutter#27438]
Canvas drawImage not working on andriod

drawImage works fine on ios, and on android with `flutter run --enable-software-rendering`

`c.drawImage(lImage, offset, paint);` 

related issue but closed [#22137](https://github.com/flutter/flutter/issues/22137)
SO [question](https://stackoverflow.com/questions/54481978/flutter-canvas-drawimage-returns-blank) 

`flutter doctor -v`

[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-IN)
• Flutter version 1.1.8 at /Users/apurvb/dev/flutter
• Framework revision 985ccb6 (4 weeks ago), 2019-01-08 13:45:55 -0800
• Engine revision 7112b72cc2
• Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/apurvb/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.1, Build version 10B61
• ios-deploy 1.9.4
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 32.0.1
• Dart plugin version 182.5124
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
• iPhone X • 6071A27C-A56B-4ABE-8898-09E25DC9C205 • ios • iOS 12.1 (simulator)

**Comment by wouterhardeman** [comment]
@Apurv2017 Your Flutter version is quite outdated. Can you confirm it occurs on the dev channel as well after you've ran `flutter upgrade`?

**Comment by Apurv2017** [comment]
@wouterhardeman 
upgraded to latest dev and its working fine.

Due to some reason flutter, v1.0.0 was being shown as "up to date" after running "flutter upgrade"
