### ISSUE TITLE
App works in debug mode but does not work in release mode

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#27436]
## Steps to Reproduce

 [https://github.com/windrunner414/reader](https://github.com/windrunner414/reader)
this app works in debug mode.but in release mode,it only show a green background without any text.

## Logs

```
```

```
```

```
```

**Comment by wouterhardeman** [comment]
Can you post the output of `flutter doctor -v`?

**Comment by windrunner414** [comment]
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.18290.1000], locale zh-CN)
    • Flutter version 1.0.0 at E:\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at E:\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = E:\android-sdk
    • Java binary at: E:\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at E:\android studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] VS Code, 64-bit edition (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by windrunner414** [comment]
release or profile mode
![image](https://user-images.githubusercontent.com/31621968/52172112-e5cbc500-27a3-11e9-9604-617672dea27c.png)

debug mode
![image](https://user-images.githubusercontent.com/31621968/52172113-f845fe80-27a3-11e9-93cb-50de9d6e7d4c.png)

**Comment by windrunner414** [comment]
MediaQuery.of(context).size.width return 0.0

**Comment by windrunner414** [comment]
only need check the size,if is zero, don't build.
close this issue

**Comment by zoechi** [comment]
This is because in release mode the app starts faster and the native platform delivers the real display size only with a delay. In debug this is usually before the first build, in release often after the first build.

**Comment by lizhuoyuan** [comment]
@windrunner414  遇到了同样的问题 请问能具体说一下或放一下代码吗?

**Comment by kangwang1988** [comment]
@lizhuoyuan 
See https://github.com/flutter/flutter/issues/32541 for more.

**Comment by lizhuoyuan** [comment]
Thank you for your help, but an hour has passed, I still haven't got it.

**Comment by vipuluthaiah** [comment]
Hey..I am Facing same issue ..I am making a chat app..with firebase and CloudFirestore...in debug mode the app is working fine ..the chat and all is loading but ..When after building a apk the chat and the users are not loading..I Gave all the permision like:    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
Its working on debug:
![Screenshot_1592149602](https://user-images.githubusercontent.com/45168922/84597949-d921ab80-ae84-11ea-9dcb-f5e473c168d3.png)
![Screenshot_1592149614](https://user-images.githubusercontent.com/45168922/84597952-dd4dc900-ae84-11ea-9beb-a78cb5acd0a4.png)
its working perfectly fine..but in build apk its not loading the users:
![WhatsApp Image 2020-06-12 at 3 46 24 PM](https://user-images.githubusercontent.com/45168922/84597965-f6ef1080-ae84-11ea-8162-d42aeba69f40.jpeg)
![WhatsApp Image 2020-06-13 at 5 35 12 PM](https://user-images.githubusercontent.com/45168922/84597967-f8203d80-ae84-11ea-8e89-1e5676c5bf01.jpeg)

**Comment by vipuluthaiah** [comment]
$ flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
    • Flutter version 1.17.1 at D:\Flutter\flutter
    • Framework revision f7a6a7906b (5 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\welcome\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\welcome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Moto E 4 Plus             • ZH33L37CXJ    • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.



And my android permission are:
$ flutter doctor -v
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
    • Flutter version 1.17.1 at D:\Flutter\flutter
    • Framework revision f7a6a7906b (5 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\welcome\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\welcome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Moto E 4 Plus             • ZH33L37CXJ    • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.

**Comment by Dinesh41** [comment]
> Hey..I am Facing same issue ..I am making a chat app..with firebase and CloudFirestore...in debug mode the app is working fine ..the chat and all is loading but ..When after building a apk the chat and the users are not loading..I Gave all the permision like:
> 
> 
> 
> 
> Its working on debug:
> ![Screenshot_1592149602](https://user-images.githubusercontent.com/45168922/84597949-d921ab80-ae84-11ea-9dcb-f5e473c168d3.png)
> ![Screenshot_1592149614](https://user-images.githubusercontent.com/45168922/84597952-dd4dc900-ae84-11ea-9beb-a78cb5acd0a4.png)
> its working perfectly fine..but in build apk its not loading the users:
> ![WhatsApp Image 2020-06-12 at 3 46 24 PM](https://user-images.githubusercontent.com/45168922/84597965-f6ef1080-ae84-11ea-8162-d42aeba69f40.jpeg)
> ![WhatsApp Image 2020-06-13 at 5 35 12 PM](https://user-images.githubusercontent.com/45168922/84597967-f8203d80-ae84-11ea-8e89-1e5676c5bf01.jpeg)

Found any work around?  Same happening for me too.
