### ISSUE TITLE
FirebaseDynamicLinks retrieveDynamicLink() only retrieves the links in Firebase, not the link that opened the app

### ISSUE THREAD

**Issue by Daniel-WM-Roy** [flutter/flutter#27439]
I've followed Diego's [Flutter : Firebase Dynamic Link](https://medium.com/@diegoveloper/flutter-firebase-dynamic-link-6f1b79278ce0) tutorial but the method FirebaseDynamicLinks.instance.retrieveDynamicLink() doesn't return the link that opened the app. To quote Diego's article:

> FirebaseDynamicLinks.instance.retrieveDynamicLink() is the call that is responsible for obtaining the deep link in the case our application was opened from the dynamic link.

But it doesn't. Instead it just pulls the dynamic links that exist in the Firebase dynamic links console. I have one link there that I initially created for testing purposes. This method always returns that link, even when opening the app using a link I created using DynamicLinkParameters.

Is there another way to get the link that opened the app? The [current documentation](https://firebase.google.com/docs/dynamic-links/android/receive?authuser=0) from Firebase doesn't mention how to do it in Flutter.

I'm using Flutter version 1.1.8 and firebase_dynamic_links 0.1.0+1 (as 0.2.0 seems to be broken at the moment)

**Comment by kroikie** [comment]
@Daniel-WM-Roy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/468. Any further collaboration will be done there.
