### ISSUE TITLE
showDialog not showing after FutureBuilder

### ISSUE THREAD

**Issue by irwinOT** [flutter/flutter#27442]
sorry for my English....

## Steps to Reproduce

In onTap of a FirebaseAnimatedList's item i want display a dialog after FutureBuilder`s firebase result:

Flexible(
          child: FirebaseAnimatedList(
            key: new ValueKey<bool>(false),
            query: _representantesAlumnosFRef,
            reverse: false,
            sort: null,
            itemBuilder: (BuildContext context, DataSnapshot snapshot,
                Animation<double> animation, int index) {
              return SizeTransition(
                  sizeFactor: animation,
                  child: ListTile(
                      title: Text(snapshot.value),
                      subtitle: Text(snapshot.key),
                      onTap: () {
                        _muestraInfoAlumno(snapshot.key, snapshot.value, 'F');
                      }));
            },
          ),
        ),

_muestraInfoAlumno(String idAlumno, nombreAlumno, codigoColegio) {
      var _consulta = FirebaseDatabase.instance
          .reference()
          .child('produccion')
          .child("alumnos")
          .child(codigoColegio)
          .child(idAlumno)
          .once();
      FutureBuilder(
        future: _consulta,
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          showDialog<String>(
              context: context,
              builder: (BuildContext context) {
                return CupertinoAlertDialog(
                  title: Text(
                    nombreAlumno,
                    style: TextStyle(
                        color: Colors.yellow[800], fontWeight: FontWeight.bold),
                  ),
                  content: Text("\nCodigo: $idAlumno"),
                  actions: <Widget>[
                    new FlatButton(
                      child: new Text("Ver Mapa Entrada",
                          style: new TextStyle(color: Colors.yellow[800])),
                      onPressed: () {
                        //verMapaTracking(context, idAlumno, idRutaEntrada, true);
                      },
                    ),
                    new FlatButton(
                      child: new Text("Ver Mapa Salida",
                          style: new TextStyle(color: Colors.yellow[800])),
                      onPressed: () {
                        //verMapaTracking(context, idAlumno, idRutaSalidada, false);
                      },
                    ),
                    new FlatButton(
                      child: new Text("Reportar Inasistencia",
                          style: new TextStyle(color: Colors.yellow[800])),
                      onPressed: () {},
                    ),
                    new FlatButton(
                      child: new Text("Cerrar",
                          style: new TextStyle(color: Colors.yellow[800])),
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                    ),
                  ],
                );
              });
        },
      );
    }

nothing happens even with a simple print instead of the dialog

Nothing happens
nothing is shown
I have nothing in log

Flutter doctor:

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale es-EC)
    • Flutter version 1.0.0 at /Users/irwinortiz/Documents/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/irwinortiz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • BLL L23 • 9DLDU17214008625 • android-arm64 • Android 6.0 (API 23)

• No issues found!

**Comment by wouterhardeman** [comment]
Can you wrap your code in code blocks so it's easier to read? You can do it like this:

>  \`\`\`dart
> (your code)
> \`\`\`

**Comment by dcov** [comment]
It's because you never insert `FutureBuilder` into the `Widget` tree so the `FutureBuilder.builder` method is never called. Try this:

```dart
_muestraInfoAlumno(BuildContext context, String idAlumno, nombreAlumno, codigoColegio) {
  var _consulta = FirebaseDatabase.instance
    .reference()
    .child('produccion')
    .child("alumnos")
    .child(codigoColegio)
    .child(idAlumno)
    .once();
  _consulta.then((data) {
    showDialog(
      context,
      ///everything else
  });
```

Also, I think they recommend that you ask questions like these on StackOverflow instead of on here.

**Comment by kangwang1988** [comment]
@irwinOT 
It seems that this issue is resolved and I will close it now.
Feel free to comment below and we would like to reopen it when needed.
