### ISSUE TITLE
Named SharedPreferences

### ISSUE THREAD

**Issue by ronshapiro** [flutter/flutter#27451]
The `shared_preferences` package only allows for a single SharedPreferences file, but both [Android](https://developer.android.com/reference/android/content/Context#getSharedPreferences(java.lang.String,%20int)) and [iOS]https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename?language=objc allow for multiple shared preferences/NSUserDefaults files.

It would be good to add this functionality to the Flutter package so that content can be properly sectioned by different packages/use cases. It would also allow use of the package without requiring a singleton instance, which is good for testability.

**Comment by kangwang1988** [comment]
@cyanglaz 
Any comments on this suggestion?

**Comment by zoechi** [comment]
Looks like a duplicate of #14337
