### ISSUE TITLE
error: device still authorizing

### ISSUE THREAD

**Issue by ChangWenWu** [flutter/flutter#27456]
## Steps to Reproduce

In android studio , i met this error when i tried to run the flutter project on my android phone（android 8.0）.

I'm sure that I have:
1.  installed android 8.0 SDK  from Android Studio.
2. set the USB config to MTP in debug setting.
3. restart android studio/restart computer/reconnect device

all of these didn't work.  

## Logs

```
Error retrieving device properties for ro.product.cpu.abi:
error: device still authorizing

Launching lib\main.dart on 3949363555493098 in debug mode...
Initializing gradle...
Resolving dependencies...
error: device still authorizing
Unhandled exception:
Exit code 1 from: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb -s 3949363555493098 shell -x logcat -v time -t 1
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:353:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:284:10)
#2      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:504:27)
#3      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:678:41)
#4      _runGuarded (dart:async/stream_controller.dart:804:24)
#5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217:7)
#6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:817:19)
#7      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#8      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:242:71)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:285:5)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#11     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:387:62)
#12     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:438:26)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:820:20)
#20     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:436:15)
<asynchronous suspension>
#21     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:384:12)
<asynchronous suspension>
#22     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:289:38)
<asynchronous suspension>
#23     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#30     Future._complete (dart:async/future_impl.dart:476:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#33     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#34     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#41     Future._complete (dart:async/future_impl.dart:476:7)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#43     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#44     _rootRun (dart:async/zone.dart:1124:13)
#45     _CustomZone.run (dart:async/zone.dart:1021:19)
#46     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

```
D:\Development\flutter_windows_v1.0.0-stable\flutter>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.16299.431], locale zh-CN)
    • Flutter version 1.0.0 at D:\Development\flutter_windows_v1.0.0-stable\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

\Error retrieving device properties for ro.product.cpu.abi:
error: device still authorizing

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • SM G9600 • 3949363555493098 • android-arm • Android null (API null)

• No issues found!

```

**Comment by jonahwilliams** [comment]
This is an error that happens in adb, possibly due to insufficient permissions. See https://github.com/flutter/flutter/issues/10330.

What does `adb devices` return ?

**Comment by ChangWenWu** [comment]
> This is an error that happens in adb, possibly due to insufficient permissions. See #10330.
> 
> What does `adb devices` return ?

```
C:\windows\system32>adb devices
List of devices attached
3949363555493098        offline
```

**Comment by ChangWenWu** [comment]
> This is an error that happens in adb, possibly due to insufficient permissions. See #10330.
> 
> What does `adb devices` return ?

```
C:\windows\system32>adb devices
List of devices attached
3949363555493098        authorizing
```

The result change from ''offline'' to ''authorizing''

**Comment by ChangWenWu** [comment]
> This is an error that happens in adb, possibly due to insufficient permissions. See #10330.
> 
> What does `adb devices` return ?

I re-install the whole develop tools(include Android Studio and SDK)，the problem is gone，thank for your effort.

**Comment by vishvadeepaktripathi** [comment]
For me it's not working i reinstall it again but it's not working 
when i am running flutter doctor 
Output: ******************************************************

C:\Users\z003n0dt>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.3.8, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
\ Checking Android licenses is taking an unexpectedly long time...Error retrieving device properties for ro.product.cpu.abi:
                                                      [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.32.1)
[√] Connected device (1 available)

• No issues found!
***********************************************************************
You can see here **Error retrieving device properties for ro.product.cpu.abi:** Error and my device is connected with Andriod studio. 
Currently i am using adb version 1.0.39 and 

Following the Error from Android studio : 
************************************

Error retrieving device properties for ro.hardware:

Launching lib\main.dart on ONEPLUS A6000 in debug mode...
Initializing gradle...
Resolving dependencies...
--------- beginning of main
03-10 18:14:09.910 D/vendor.qti.bluetooth@1.0-wake_lock(  691): Release wakelock is released
Unhandled exception:
Exit code -1073740940 from: D:/Mobile-Dev/src/Andriod/SDK\platform-tools\adb -s 5df11745 shell -x logcat -v time -t 1
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:352:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:283:10)
#2      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:507:27)
#3      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:681:41)
#4      _runGuarded (dart:async/stream_controller.dart:805:24)
#5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#7      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#8      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:261:71)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:304:5)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#11     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:393:23)
#12     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:452:26)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:835:20)
#20     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:450:15)
<asynchronous suspension>
#21     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:387:12)
<asynchronous suspension>
#22     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:281:38)
<asynchronous suspension>
#23     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#33     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#34     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#41     Future._complete (dart:async/future_impl.dart:473:7)
#42     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#43     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#44     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#45     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#46     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#52     Future._complete (dart:async/future_impl.dart:473:7)
#53     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#54     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#55     _rootRun (dart:async/zone.dart:1124:13)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#60     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**************************************************************************

**Comment by GuilhermeVendramini** [comment]
Reinstall Android and SDK don't work for me.

**Comment by Tomucha** [comment]
I revoked "USB debugging authorizations" in developer options on the phone a than reconnected the phone to the computer and allowed debugging on that device once again. Now it's working again.

**Comment by waghcwb** [comment]
For me, disconnecting the phone from the USB, and the running those commands solved the issue

```sh
adb kill-server
adb start-server
```
