### ISSUE TITLE
Move tonic into the Flutter engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#27452]
Tonic was moved into its own repository because it is used by some Fuchsia targets. However, it seems to have no current owner. Also, because of its location outside of the Flutter buildroot, none of the test harnesses in Flutter can be used to test Tonic. Due to this and the lack of clear ownership of the codebase, all current test targets are disabled. Existing files in tonic containing a few tests are never compiled and contain references to code that has long gone away or been refactored. This lack of clarity has also made it so that new code that ought to go into tonic has found its way in other targets that have clearer code ownership and well defined test harnesses (usually `//flutter/runtime` and includes stuff like launching the VM and interacting with isolates).

We should consider moving Tonic back into Flutter and make `//flutter/runtime` deal with just the specific Flutter bits of interacting with Dart. Existing targets in Fuchsia can use tonic from Flutter. If this is not desirable, Tonic can remain as is and the Flutter engine can fork it (`//flutter/tunic`?)

**Comment by chinmaygarde** [comment]
@jason-simmons, @cbracken, @zanderso, @abarth: Thoughts, go/no-go?

**Comment by dnfield** [comment]
What about moving it into the Dart VM?

**Comment by abarth** [comment]
Putting it in Dart VM would work for all the scenarios we are currently considering for Flutter-related code in Fuchsia.

**Comment by a-siva** [comment]
I am assuming the premise here is that all embedders of the Dart VM would need a library like this to access to the Dart API surface area. Does it have to be tonic or is it just sufficient to have a C++ library that exposes the Dart API surface? We can discuss this offline.

**Comment by abarth** [comment]
From my perspective, it wouldn't need to be tonic.  It would just need to be sufficient to satisfy all current clients of tonic so that we could delete tonic in favor of it.

**Comment by mdempsky** [comment]
Has there been any progress on this issue either way? I think I found an issue in tonic, but the lack of a clear home for it means I'm not sure what issue tracker to file it under.

My 2c: I think moving tonic into Dart makes sense.

(FWIW, issue is that I think the memmove call in `DartConverter<Uint16List>::ToDart` is mixing up element counts with byte counts, because it was copied from the `Uint8List` implementation that didn't have to distinguish that.)

**Comment by Sunbreak** [comment]
https://github.com/flutter/engine/pull/15895

Looks like we could close this issue?

**Comment by cbracken** [comment]
Indeed we can. Thanks!
