### ISSUE TITLE
IconButton should set color to disabledColor automatically if onPressed is null

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2745]
This comes up in step_2 of https://github.com/flutter/firechat-flutter

**Comment by Hixie** [comment]
As far as I can tell, we already do this. But I'm going to clean it up a bit and document it.

**Comment by Hixie** [comment]
I think this is done, but please reopen or file a new bug if I misunderstood what the bug was about.

**Comment by collinjackson** [comment]
I can't repro the issue any more. I'll update the codelab to use automatic color disabling. Thanks.
