### ISSUE TITLE
Trouble with running and hot reloading flutter in Android studio (Bad state: Future already completed)

### ISSUE THREAD

**Issue by Drkstr** [flutter/flutter#27450]
I am having some trouble with running and hot reloading flutter apps in Android studio. 

When I run an app in Android studio, I get the following message every now and again(2 out of 3 runs) and the build fails. 

    Launching lib/main.dart on iPhone XR in debug mode...
    Unhandled exception:
    Bad state: Future already completed
    #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
    #1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:490:23)
    #2      _NativeSocket.issueWriteEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
    #3      _NativeSocket.issueWriteEvent (dart:io/runtime/binsocket_patch.dart:851:12)
    #4      _NativeSocket.multiplex (dart:io/runtime/binsocket_patch.dart:872:11)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

I have not been able to get hot reload to work at all

    Performing hot reload...
    Syncing files to device iPhone XR...
    Unhandled exception:
    Bad state: Future already completed
    #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
    #1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:490:23)
    #2      _NativeSocket.issueWriteEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
    #3      _NativeSocket.issueWriteEvent (dart:io/runtime/binsocket_patch.dart:851:12)
    #4      _NativeSocket.multiplex (dart:io/runtime/binsocket_patch.dart:872:11)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

I am working on the stable channel. Here is my output of flutter doctor: 

    [✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-AU)
    • Flutter version 1.0.0 at /Users/rakshak/flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

    ⣽Unhandled exception:
    Bad state: Future already completed
    #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
    #1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:490:23)
    #2      _NativeSocket.issueWriteEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
    #3      _NativeSocket.issueWriteEvent (dart:io/runtime/binsocket_patch.dart:851:12)
    #4      _NativeSocket.multiplex (dart:io/runtime/binsocket_patch.dart:872:11)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

I am working from China at the moment, I have implemented the changes mentioned here: https://flutter.io/community/china. Here are the relevant parts of my .bash_profile file

    export PUB_HOSTED_URL=https://pub.flutter-io.cn
    export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
    export PATH=$PATH:/Users/rakshak/flutter/bin

I am working on a Mac.

**Comment by kangwang1988** [comment]
@Drkstr 
Can you create a minimal demo project which can reproduce this issue?

**Comment by Drkstr** [comment]
@kangwang1988 I'm not sure what you mean by a "minimal demo project". 

I get the above results when I create a new flutter project in Android Studio and try to run it without any modifications to the generated boilerplate code

**Comment by kangwang1988** [comment]
@Drkstr 
Got it, I will check if I can reproduce it on my mac.

**Comment by zoechi** [comment]
Might be https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#hot-reload-not-working

**Comment by Drkstr** [comment]
@zoechi I am not using a proxy.

**Comment by zoechi** [comment]
Can you please check if you can reproduce in `master` channel?

**Comment by kangwang1988** [comment]
I fail to reproduce this issue using the latest master.
Besides, another issue resulted from network reports the same callstack.
See: https://github.com/flutter/flutter/issues/27696

**Comment by Drkstr** [comment]
@kangwang1988 thanks for the link to the issue. 

I think I might be facing the same issue. 

I have removed PUB_HOSTED_URL and FLUTTER_STORAGE_BASE_URL from my .bash_profile file and turned on my VPN. This seems to have fixed it the issue. 

Thanks for your help.

**Comment by kangwang1988** [comment]
This problem seems to be mainly resulted from a network problem, such as VPN,etc.

@Drkstr 
> Question to the flutter team: Why would flutter need an active internet connection to build or hot reload an app?

When `flutter run` or `hot reload`, flutter needs an active connection to local observatory port(on you desktop) so that those assets needed(for example, dill files) can be synced to the vm-service(in your phone). There is a port forwarding between the observatory port and vm-service port.
