### ISSUE TITLE
Couldnt let me use Navigator within Streambuilder????

### ISSUE THREAD

**Issue by DeepStyles** [flutter/flutter#27460]
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22281): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter (22281): _WidgetsAppState#fd507](dirty, state: NavigatorState#5fe1b(tickers: tracking 2 tickers)):
I/flutter (22281): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1995 pos 12: '!_debugLocked':
I/flutter (22281): is not true.
```

I m returning Empty `Container()`,

**Comment by DeepStyles** [comment]
First Exception: 
I/flutter (22586):   maintainState: true), OverlayEntry#c0497(opaque: false; maintainState: false),
I/flutter (22586):   OverlayEntry#b1faa(opaque: false; maintainState: true)]))
I/flutter (22586): The widget which was currently being built when the offending call was made was:
I/flutter (22586):   StreamBuilder<String>(dirty, state: _StreamBuilderBaseState<String, AsyncSnapshot<String>>#466ab)

**Comment by zoechi** [comment]
Unfortunately this is not sufficient information to diagnose the problem.
It looks like a support request anyway.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

If you think this is a bug or missing feature in Flutter, please create a new issue with properly filled issue template. Thanks!
