### ISSUE TITLE
how to exit from app where there are more than one widget in widget stack

### ISSUE THREAD

**Issue by Atominac** [flutter/flutter#27465]
widget stack
splashscreeen>>homepage

i need to exit my app from homepage

**Comment by zarszz** [comment]
same here, i need solution

**Comment by tb2761** [comment]
Think you can use SystemNavigator.pop() or create a MethodChannel and implement the platform specific closing in there.

**Comment by Atominac** [comment]
can you please attach link or code about the process?

**Comment by zoechi** [comment]
See also https://stackoverflow.com/questions/45109557/flutter-programmatically-closing-the-app

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Atominac** [comment]
> ```java
> private static final String CHANNEL = "choose a name for the MethodChannel";
> 
> new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(new MethodCallHandler() {
>       @Override
>       public void onMethodCall(MethodCall call, Result result) {
>         if (call.method.equals("closeApp")) {
>             MainActivity.this.finishAffinity();
>         }
>       }
>     });
> ```

where i need to put this code

**Comment by patelkrunal78** [comment]
Preferable solution is:

SystemChannels.platform.invokeMethod('SystemNavigator.pop');
As described [here](https://icetutor.com/question/flutter-how-to-programmatically-exit-the-app/)
