### ISSUE TITLE
Roadmap - prioritise flutter on desktop

### ISSUE THREAD

**Issue by deanchalk** [flutter/flutter#27467]
Your flutter roadmap page suggests that you might be bringing flutter to other platforms.

I am a Windows native developer (WPF, Winforms) and I have spent a lot of time fighting Microsoft's ambivalence to this technology. According to Microsoft everything should be a web app, but life isn't that simple, and as they've pretty much abandoned the native desktop, I believe flutter would be a brilliant fit for this scenario. I build high -perfornance trading apps for large banks and utility companies. These apps have to be desktop and native, and the banks have no option but to continue with the only option available - Microsoft. If the flutter team could bring flutter performance to windows, then it could be a big game changer. Also, I know that some car racing teams (Formula 1) in the UK are using WPF for car telemetry apps, and are desperate to move away from an abandoned platform (they are considering Qt for goodness sakes). Any comment on this part of your roadmap would be most interesting - thanks.

**Comment by kangwang1988** [comment]
@deanchalk 
I would suggest you to have a look at: https://github.com/google/flutter-desktop-embedding
And roadmap for flutter 2019: https://github.com/flutter/flutter/wiki/Roadmap

**Comment by kangwang1988** [comment]
cc @timsneath

**Comment by walter211** [comment]
Agreed!

**Comment by timsneath** [comment]
See also https://github.com/flutter/flutter/issues/14967, which is the primary issue we're tracking on this front: feel free to give it your thumbs up. We hear this request loud and clear. We talked a little about [Flutter on the desktop at Flutter Live](https://www.youtube.com/watch?v=5SZZfpkVhwk&feature=youtu.be&list=PLOU2XLYxmsILq4ysYNWXq5TOGLgYDJgVD&t=37), and we'll have more to say in the next months.
