### ISSUE TITLE
using firebase_core: D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

### ISSUE THREAD

**Issue by Atominac** [flutter/flutter#27464]

**Comment by Atominac** [comment]
adding to this
error is only there when using both
image_picker:
firebase_core:

both works well separately.

**Comment by redvg** [comment]
im having exactly the same, image_picker + firebase_core

**Comment by redvg** [comment]
solved by downgrading to image_picker: ^0.4.12 as per #27194

**Comment by zoechi** [comment]
Duplicate of #27194

**Comment by michelengelen** [comment]
For anyone still experiencing it even with all those fixes applied:

I did fix it by updating the Gradle version in `<your-app>/android/gradle/wrapper/gradle-wrapper.properties` from `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

After that all builds run smoothly
