### ISSUE TITLE
Flutter run fails with error - Gradle build failed to produce an Android package

### ISSUE THREAD

**Issue by vladaman** [flutter/flutter#27462]
After an update to flutter 1.1.8 the run command fails with an error which does not indicate were to look for problems.

The project is broken now without clear guideline where to look and how to problem.

By the way, when I open this in Android Studio and I build Android APK it compiles the project. This is only when I run the "flutter run" command.

```
Gradle build failed to produce an Android package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:423:7)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:310:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:379:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:292:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:275:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:378:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.1.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[!] VS Code (version 1.27.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by vladaman** [comment]
Found the error. In build.gradle we used custom .apk name. Flutter failed to locate the apk and deploy it to the Android phone. 

```
setProperty("archivesBaseName", "app-" + versionName)
````

**Comment by sabbir420** [comment]
@vladaman  I also got the same issue when I run `flutter build apk --release` this command. But if I run `flutter run` command, it runs and it builds the apk and install to the phone. I used this code to build.gradle:

`buildscript {
 repositories {
    google()
    jcenter()
    maven {
        url "https://maven.google.com"
    }
}
dependencies {
    // Google Auth
    classpath 'com.android.tools.build:gradle:3.1.2'
    // Firebase Auth
    classpath 'com.google.gms:google-services:3.2.1'
}
}`

And it ended with an error. I run flutter doctor. There is no issue with version or any other thing. I have updated all.  This is the result I have got in terminal:

`Initializing gradle...                                             12.4s
Resolving dependencies...                                          11.2s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      43.1s
Gradle build failed to produce an Android package.`

At last it ended with an error.

**Comment by suesitran** [comment]
> @vladaman I also got the same issue when I run `flutter build apk --release` this command. But if I run `flutter run` command, it runs and it builds the apk and install to the phone. I used this code to build.gradle:
> 
> `buildscript { repositories { google() jcenter() maven { url "https://maven.google.com" } } dependencies { // Google Auth classpath 'com.android.tools.build:gradle:3.1.2' // Firebase Auth classpath 'com.google.gms:google-services:3.2.1' } }`
> 
> And it ended with an error. I run flutter doctor. There is no issue with version or any other thing. I have updated all. This is the result I have got in terminal:
> 
> `Initializing gradle... 12.4s Resolving dependencies... 11.2s registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) Running Gradle task 'assembleRelease'... Running Gradle task 'assembleRelease'... Done 43.1s Gradle build failed to produce an Android package.`
> 
> At last it ended with an error.

I'm having same problem

**Comment by sabbir420** [comment]
@suesitran I solved that problem. In my case, it failed because of `keystoreProperties.` I used  `keystoreProperties` because to save the keys. But later I did not use that function but code was there. That `keystoreProperties` code never used as a function and that made gradle failed to produce and showed that error. When I commented that code and generated the apk. gradle generated the apk without any issue.

In your case, can I see your terminal?

**Comment by fritz-playmaker** [comment]
Any solution here?

**Comment by ArtfulDodgerB92** [comment]
Also need a solution for this one, or some sort of hint in the error log about what is actually happening.   Or just... something.   Come on guys, this is not an isolated incident.   The documentation from Flutter for publishing to the store it utter trash.

**Comment by glennmichaelmejias** [comment]
got the same error, what i did is commented this line from app/build.gradle
// splits {
//         // Configures multiple APKs based on ABI.
//         abi {
//             // Enables building multiple APKs per ABI.
//             enable true
//             // By default all ABIs are included, so use reset() and include to specify that we only
//             // want APKs for armeabi-v7a and arm64-v8a.

//             // Resets the list of ABIs that Gradle should create APKs for to none.
//             reset()

//             // Specifies a list of ABIs that Gradle should create APKs for.
//             include "armeabi-v7a", "arm64-v8a"

//             // Specifies that we do not want to also generate a universal APK that includes all ABIs.
//             universalApk false
//         }
//     }

**Comment by efroim102** [comment]
@glennmichaelmejias This resolved the issue for me too, I can now debug properly.

Was just wondering does disabling abi splits still allow me to build & release app bundles for the Google Play Store?

**Comment by luccastanan** [comment]
I commented this line `include "armeabi-v7a", "arm64-v8a"` from app/build.gradle
```gradle
splits {
        // Configures multiple APKs based on ABI.
        abi {
            // Enables building multiple APKs per ABI.
            enable true
            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for armeabi-v7a and arm64-v8a.

            // Resets the list of ABIs that Gradle should create APKs for to none.
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for.
            //include "armeabi-v7a", "arm64-v8a"

            // Specifies that we do not want to also generate a universal APK that includes all ABIs.
            universalApk false
        }
    }
```

**Comment by efroim102** [comment]
> build

Dude, this was literally posted 2 comments prior by @glennmichaelmejias.

**Comment by MJames007** [comment]
> I commented this line `include "armeabi-v7a", "arm64-v8a"` from app/build.gradle
> 
> ```groovy-gradle
> splits {
>         // Configures multiple APKs based on ABI.
>         abi {
>             // Enables building multiple APKs per ABI.
>             enable true
>             // By default all ABIs are included, so use reset() and include to specify that we only
>             // want APKs for armeabi-v7a and arm64-v8a.
> 
>             // Resets the list of ABIs that Gradle should create APKs for to none.
>             reset()
> 
>             // Specifies a list of ABIs that Gradle should create APKs for.
>             //include "armeabi-v7a", "arm64-v8a"
> 
>             // Specifies that we do not want to also generate a universal APK that includes all ABIs.
>             universalApk false
>         }
>     }
> ```
this one solves it

**Comment by luccastanan** [comment]
> > I commented this line `include "armeabi-v7a", "arm64-v8a"` from app/build.gradle
> > ```
> > splits {
> >         // Configures multiple APKs based on ABI.
> >         abi {
> >             // Enables building multiple APKs per ABI.
> >             enable true
> >             // By default all ABIs are included, so use reset() and include to specify that we only
> >             // want APKs for armeabi-v7a and arm64-v8a.
> > 
> >             // Resets the list of ABIs that Gradle should create APKs for to none.
> >             reset()
> > 
> >             // Specifies a list of ABIs that Gradle should create APKs for.
> >             //include "armeabi-v7a", "arm64-v8a"
> > 
> >             // Specifies that we do not want to also generate a universal APK that includes all ABIs.
> >             universalApk false
> >         }
> >     }
> > ```
> 
> Dude, this was literally posted 2 comments prior by @glennmichaelmejias.

He did not say which line he commented

**Comment by efroim102** [comment]
@luccastanan It was quite obvious he commented all of them since none of them were commented, but I guess what's obvious to me might not be to someone else. -Cheers

**Comment by enzoftware** [comment]
> @vladaman I also got the same issue when I run `flutter build apk --release` this command. But if I run `flutter run` command, it runs and it builds the apk and install to the phone. I used this code to build.gradle:
> 
> `buildscript { repositories { google() jcenter() maven { url "https://maven.google.com" } } dependencies { // Google Auth classpath 'com.android.tools.build:gradle:3.1.2' // Firebase Auth classpath 'com.google.gms:google-services:3.2.1' } }`
> 
> And it ended with an error. I run flutter doctor. There is no issue with version or any other thing. I have updated all. This is the result I have got in terminal:
> 
> `Initializing gradle... 12.4s Resolving dependencies... 11.2s registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection) Running Gradle task 'assembleRelease'... Running Gradle task 'assembleRelease'... Done 43.1s Gradle build failed to produce an Android package.`
> 
> At last it ended with an error.

Same error here.

**Comment by kosalgeek** [comment]
make sure: 
1. gradle-wrapper.properties, you have this version 4.10.2:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
2. in android/build.gradle, you have version 3.3.0:
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
3.  you need ```flutter clean```
4. finally, ```flutter build apk --split-per-abi --release```

**Comment by CocoaZX** [comment]
Now I need to build .apk , not .aab, but I found can use Android Studio build success, VSCode will fail
