### ISSUE TITLE
ThemeData.toString() is way too verbose

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27478]
We need to mark most of ThemeData's diagnostics as hidden by default, and we should add a test that verifies that no lines in the output of the default app are longer than a hundred or two hundred characters.

cc @gspencergoog @jacob314 @justinmc

**Comment by jacob314** [comment]
Instead of Using `DiagnosticsLevel.hidden` I would propose using `DiagnosticsLevel.debug` which is a good fit for just this case. The diagnostics won't show up in text output but will show up in GUI tools.
 ```dart
  /// Diagnostics that should only be shown when performing fine grained
  /// debugging of an object.
  ///
  /// Unlike a [fine] diagnostic, these diagnostics provide important
  /// information about the object that is likely to be needed to debug. Used by
  /// properties that are important but where the property value is too verbose
  /// (e.g. 300+ characters long) to show with a higher diagnostic level.
  debug,
```
