### ISSUE TITLE
Move Brightness to dart:ui

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#27479]
`Brightness` is currently defined within system_chrome.dart, which is part of services in the framework.

`Brightness` is needed for reporting `platformBrightness` from the platform, which requires the definition of `Brightness` to be available within the engine.

This ticket is to move the definition of `Brightness` to dart:ui within the engine and then add an export back to system_chrome.dart to stay backward compatible.

**Comment by goderbauer** [comment]
Looks like this was completed? Can we close it?

**Comment by matthew-carroll** [comment]
Yep!
