### ISSUE TITLE
Bug with the Switch Widget

### ISSUE THREAD

**Issue by strangerweather** [flutter/flutter#27474]
## Steps to Reproduce

when I toggle the switch on it prints "allowed" but when I toggle it back off, it prints nothing: 
```
bool val = false;

    onSwitchValueChanged(bool newValue) {
      setState(() {
        val = newValue;

        if (val == false) {
          print('disallowed');
        } else {
          print('allowed');
        }
      });
    }
```
and 

 ```
Switch(
                  activeColor: Colors.green,
                  value: val,
                  onChanged: (newValue) {
                    onSwitchValueChanged(newValue);
                  },
                ),
```

No errors are thrown. It just does not yield the expected result.

**Comment by jonahwilliams** [comment]
Please include a minimum runnable example that reproduces the issue and the output of `flutter doctor -v`.

**Comment by strangerweather** [comment]
Please disregard. It works well with my minimum runnable example. Sorry for the inconvenience.
