### ISSUE TITLE
Automatically do required platform-specific changes when adding plugins

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#27473]
Flutter plugins should have a format where they specify what platform-specific changes need to be made, so when they're added to `pubspec.yaml`, running `flutter packages get` does the required changes automatically.

Adding a plugin may require doing changes to `.gradle`, `AndroidManifest.xml` and `.java` files. There should be an option to have Flutter automatically generate these. Package name, version code, version string, etc. could be added to a `.yaml` file where they are automatically added to Android and iOS-specific files.

For instance:

*  `android_alarm_manager` says some lines need to be added to `AndroidManifest.xml`. For Android developers, it might be obvious where to add that, us non-Android developers may have to check the example to see where it's added. The part where `FlutterApplication` has to be overriden also could be done by the `flutter` tool.

* Hidden in changelogs is an instruction to migrate to AndroidX, but there's no warning when updating packages or adding new versions. This happens even with a newly created package. The `flutter` tool should do this migration, or at least show useful error messages with Flutter-specific instructions on how to do this.

While this is done, documentation and error messages should be improved to be made clearer to non-Android and non-iOS developers.

**Comment by kangwang1988** [comment]
cc @Hixie

**Comment by zoechi** [comment]
> * Hidden in changelogs is an instruction to migrate to AndroidX

https://github.com/flutter/plugins/pull/1138

**Comment by mklim** [comment]
This is also tangentially related to dart-lang/pub#2038.

**Comment by stuartmorgan** [comment]
I'm going to close this as too open-ended; bring able to to do arbitrary transformations anywhere in the project isn't feasible.

There are specific cases where an abstraction might be possible (e.g., there's an issue where something for permissions/entitlements has been discussed), but those should each be filed for individual consideration.
