### ISSUE TITLE
initState, didUpdateWidget, and dispose docs have super long confusing sentence.

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#27480]
The [current docs for initState](https://docs.flutter.io/flutter/widgets/State/initState.html) (and didUpdateWidget and dispose) have an incredibly long sentence, with a confusing reference to "old object" before it is initialized:

> If a [State](https://docs.flutter.io/flutter/widgets/State-class.html)'s [build](https://docs.flutter.io/flutter/widgets/State/build.html) method depends on an object that can itself change state, for example a [ChangeNotifier](https://docs.flutter.io/flutter/foundation/ChangeNotifier-class.html) or [Stream](https://docs.flutter.io/flutter/dart-async/Stream-class.html), or some other object to which one can subscribe to receive notifications, then the State should subscribe to that object during [initState](https://docs.flutter.io/flutter/widgets/State/initState.html), unsubscribe from the old object and subscribe to the new object when it changes in [didUpdateWidget](https://docs.flutter.io/flutter/widgets/State/didUpdateWidget.html), and then unsubscribe from the object in [dispose](https://docs.flutter.io/flutter/widgets/State/dispose.html).

Yes, that is one sentence. I started reading it several times, trying to figure out what "the old object" was, before realizing it is probably referencing something in the didUpdateWidget API. I'd suggest starting each clause with the method with which that clause concerns itself. Something like:

> If a [State](https://docs.flutter.io/flutter/widgets/State-class.html)'s [build](https://docs.flutter.io/flutter/widgets/State/build.html) method depends on an object that can itself change state, for example a [ChangeNotifier](https://docs.flutter.io/flutter/foundation/ChangeNotifier-class.html) or [Stream](https://docs.flutter.io/flutter/dart-async/Stream-class.html), or some other object to which one can subscribe to receive notifications, then be sure to subscribe and unsubscribe properly in [initState](https://docs.flutter.io/flutter/widgets/State/initState.html), [didUpdateWidget](https://docs.flutter.io/flutter/widgets/State/didUpdateWidget.html), and [dispose](https://docs.flutter.io/flutter/widgets/State/dispose.html):
>
> * In [initState](https://docs.flutter.io/flutter/widgets/State/initState.html), subscribe to the object.
> * In [didUpdateWidget](https://docs.flutter.io/flutter/widgets/State/didUpdateWidget.html), unsubscribe from the old object, and subscribe to the new object when it changes.
> * In [dispose](https://docs.flutter.io/flutter/widgets/State/dispose.html), unsubscribe from the object.

I'm actually really not convinced that the bit about didUpdateWidget is even correct...

**Comment by HansMuller** [comment]
Thanks for pointing this out and for the alternative wording suggestion. The docs for essential parts of the API like this definitely need to be easy to read and understand.

**Comment by srawlins** [comment]
Thanks for the quick fix!
