### ISSUE TITLE
Not able to read data from Firebase

### ISSUE THREAD

**Issue by spinny007** [flutter/flutter#27485]
I am trying to read and print data from Firebase collection. I have given read permission on Firebase DB.
I am trying to print Document ID and it's fields. Here is the code:
```dart
    readData() {
        DocumentReference documentReference =
            Firestore.instance.collection("topVideos").document();
        documentReference.get().then((datasnapshot) {
          print(datasnapshot.documentID.toString());
          print(datasnapshot.data["description"]);
          print(datasnapshot.data["link"]);
        });
        print('Read');
      }
```

I am getting below debug logs:

    I/flutter (10527): Read
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): Failed to handle method call
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:274)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getFirestore(CloudFirestorePlugin.java:82)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:92)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:539)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at android.os.MessageQueue.nativePollOnce(Native Method)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at android.os.MessageQueue.next(MessageQueue.java:325)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at android.os.Looper.loop(Looper.java:142)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at java.lang.reflect.Method.invoke(Native Method)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    E/MethodChannel#plugins.flutter.io/cloud_firestore(10527): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    E/flutter (10527): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    E/flutter (10527): PlatformException(error, FirebaseApp with name [DEFAULT] doesn't exist. , null)
    E/flutter (10527): #0      StandardMethodCodec.decodeEnvelope 
    E/flutter (10527): #1      MethodChannel.invokeMethod 
    E/flutter (10527): <asynchronous suspension>
    E/flutter (10527): #2      DocumentReference.get 
    E/flutter (10527): <asynchronous suspension>
    E/flutter (10527): #3      EditorsPicState.readData 
    E/flutter (10527): #4      EditorsPicState.build.<anonymous closure> 
    E/flutter (10527): #5      _InkResponseState._handleTap 
    E/flutter (10527): #6      _InkResponseState.build.<anonymous closure> 
    E/flutter (10527): #7      GestureRecognizer.invokeCallback 
    E/flutter (10527): #8      TapGestureRecognizer._checkUp 
    E/flutter (10527): #9      TapGestureRecognizer.handlePrimaryPointer 
    E/flutter (10527): #10     PrimaryPointerGestureRecognizer.handleEvent 
    E/flutter (10527): #11     PointerRouter._dispatch 
    E/flutter (10527): #12     PointerRouter.route 
    E/flutter (10527): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
    E/flutter (10527): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
    E/flutter (10527): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
    E/flutter (10527): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
    E/flutter (10527): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
    E/flutter (10527): #18     _invoke1 (dart:ui/hooks.dart:168:13)
    E/flutter (10527): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)

I kept code on a button. I am assuming it will take first available document and shall print it on console with information.

**Comment by spinny007** [comment]
Anyone please

**Comment by zoechi** [comment]
I think the issue is caused by the way you acquire the Firebase instance, but this code is missing in your issue.
See also #23049, #18075

**Comment by spinny007** [comment]
The Error is gone, as @nemoryoliver pointed it right , I missed basic config

**Comment by kangwang1988** [comment]
@spinny007 
I think this issue is resolved and not a flutter bug.
Comment below if you want to reopen it.

**Comment by kroikie** [comment]
@spinny007

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/466. Any further collaboration will be done there.
