### ISSUE TITLE
firebase_auth signInWithFacebook no longer exists?

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#27486]
I have an existing Flutter app that I have recently gone through and updated it's packages now that Flutter is 1.0.

What I have noticed is that the firebase_auth plugin no longer supports signInWithFacebook method. Was this removed? Can we still use Firebase and register/sign in with Facebook?

This seem to have happened when upgrading from package version ^0.5.20 to ^0.8.0+1 (latest)

**Comment by asyrafsalim** [comment]
@vagrantrobbie you'll have to exchange for an AuthCredential with the FacebookAccessToken. 

Then, with the AuthCredential, use it with the signInWithCredential method.

`
FacebookLoginResult result = await _facebookSignIn.logInWithReadPermissions(['email']);

final FacebookAccessToken accessToken = result.accessToken;
          
AuthCredential credential = FacebookAuthProvider.getCredential(accessToken: accessToken.token);

FirebaseUser user = await _firebaseAuth.signInWithCredential(credential);
`

**Comment by robindijkhof** [comment]
@asyrafsalim can this be put in the docs? Currently the docs contain `await _auth.signInWithGoogle` which isn't working anymore. I'd like to d this myself, but I can't find anything on `AuthCredential`

**Comment by wouterhardeman** [comment]
@robindijkhof You can find the API documentation here: https://pub.dartlang.org/documentation/firebase_auth/0.8.0+1/

**Comment by robindijkhof** [comment]
@wouterhardeman those are outdated. The example uses `signInWithGoogle` which has been replaced with AuthCredential. Unfortunately I can't find any documentation on that.

**Comment by psygo** [comment]
@asyrafsalim I think that nowadays you would have to add a `.user` at the end:

```dart
FirebaseUser fbUser = (await _auth.signInWithCredential(credential)).user;
```
