### ISSUE TITLE
Draggable should provide a mechanism to change child when entering/leaving a DragTarget.

### ISSUE THREAD

**Issue by janniklind** [flutter/flutter#27488]
Simple scenario:

1. I have a Draggable, when it is not being dragged it is blue.
2. I now begin to drag the Draggable, hence it change it's color to red.
3. When entering a DragTarget I want the child of the Draggable to be green.

I am aware of the DragTarget.OnWillAccept, but it doesn't seems that this can trigger an update of the draggable layout. I have tried to set a callback on the data of the Draggable, so I could execute that and trigger setState from within the Widget building the Draggable, but that didn't work.

I want something similar to this:

Draggable.onEnteringDragTarget
Draggable.onLeavingDragTarget

**Comment by kangwang1988** [comment]
@janniklind 
Please paste "flutter doctor -v" here.
Besides, a minimal demo project which can reproduce your issue would be helpful.
