### ISSUE TITLE
Add shared_preferences sync method

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#27490]
I have sometimes the problem that SharedPreferences `preferenceCache` isn't in sync with the device prefs. To handle this error it would be nice to have a function to updated (or sync) the `preferenceCache`.

**Comment by wouterhardeman** [comment]
Had this issue myself as well. This is especially an issue in Add2App use cases when the host platform changes to shared preferences.

I've implemented a `refreshCache()` function locally. I'll make a pull request somewhere this week after I've added tests.

**Comment by The-Redhat** [comment]
Ok thanks !

**Comment by zoechi** [comment]
Looks like a duplicate of #22016
