### ISSUE TITLE
[Google Maps Plugin] myLocationButton enable/disable

### ISSUE THREAD

**Issue by KlausJokinen** [flutter/flutter#27492]
Currently if you use MyLocation feature from Google Maps plugin it will also show MyLocationButton. Would be great if that button were optional.

**Comment by kangwang1988** [comment]
cc @cyanglaz

**Comment by Toolenaar** [comment]
Changing the position would be nice aswell!

**Comment by cyanglaz** [comment]
@iskakaushik

**Comment by ebastuart** [comment]
Yes it would be great to change the position of the button and to style it as well.

**Comment by marinat** [comment]
It would be great to make identical design and position for location button on android and ios

**Comment by pkhivesara** [comment]
@iskakaushik Is there any update on making the design and position for location button on both platforms identical?
