### ISSUE TITLE
Feature Request: Navigator.pop() to return Future

### ISSUE THREAD

**Issue by stevenspiel** [flutter/flutter#27495]
`Navigator.push()` [returns a Future](https://github.com/flutter/flutter/blob/6d20ff244650ffc94761eefb3a4f93a6186c3e65/packages/flutter/lib/src/widgets/navigator.dart#L1009), but `Navigator().pop()` [returns a boolean](https://github.com/flutter/flutter/blob/6d20ff244650ffc94761eefb3a4f93a6186c3e65/packages/flutter/lib/src/widgets/navigator.dart#L1269). What is the reason for that? It would be helpful to be able to wait for `pop` to finish before calling push especially in a case like waiting for a bottom or side drawer animation to complete.

**Comment by stevenspiel** [comment]
Oh, I see now. `push` returns a Future containing a value for after that route is popped. It's not just indicating when the transition is complete, although that would be helpful.

**Comment by Koshub** [comment]
When you are using Drawer widget it is not possible to use push Future ))
