### ISSUE TITLE
Performance regression on flutter_gallery_ios32__transition_perf

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#27508]
The regression seems to start on https://github.com/flutter/flutter/commit/c6cc3cdedafee41822ce832d7d73000f2e77b183

CC @GaryQian

**Comment by GaryQian** [comment]
Possible engine commits:
e7eb1c8bf Update the verify_exported script to include the symbols for ICU data (#7647)
b032bbd0c Roll src/third_party/skia 70ebd9ca0616..9c8ad0316147 (9 commits) (#7646)
2c610bfec Fix dynamic array -> vector (#7645)
09a3735ea Respect default goma path on Windows (#7643)
050dcaad6 Embed ICU data inside libflutter.so on Android (#7588)
c92df428e Strut implementation (#7414)
15f2b92cc Roll src/third_party/skia 673a048b209c..70ebd9ca0616 (8 commits) (#7641)

**Comment by GaryQian** [comment]
Fixed. Caused by an Amber alert on the devicelab mac5 iphone 4s.
