### ISSUE TITLE
How do I route to a specific tab?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2750]
One of the apps I'm working on has a set of tabs and separate (complicated) views on each tab.  I'd like to be able to quickly relaunch my app (from Atom) and have it open in the tab I'm iterating on.

I know it's possible to set a default route in Atom's launch file, but I don't know how I would set up routes to point to a specific TabView?

I suspect either @Hixie or @HansMuller would know. :)

**Comment by devoncarew** [comment]
@yjbanov, I don't know if this feeds into your work on testing, but it would be great to be able to set and get the current route as a service protocol extension, and receive events when the route changes. We could then display that in atom, which would make discovering routes in your app easier.

**Comment by sethladd** [comment]
This is definitely part of the fast edit/refresh cycle. +1 for this feature :)

**Comment by yjbanov** [comment]
Definitely affects tests too. An end-to-end test will almost always need to navigate to a specific location in the app before performing a test. It is also useful for "resetting" the location if a series of steps need to start in the same place but end up somewhere else.

**Comment by Hixie** [comment]
This is especially interesting on iOS where tabs are above the navigator in many ways.

**Comment by Hixie** [comment]
We'll probably need a way to intercept incoming route requests and decide to pass them along to existing routes instead of creating new routes.

**Comment by Hixie** [comment]
maybe routes should be able to subscribe to messages in some way...

**Comment by Hixie** [comment]
We could do this using route arguments...

**Comment by Hixie** [comment]
Router does this now.
