### ISSUE TITLE
[google_maps_flutter] dynamic marker clustering feature

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#27512]
Since Flutter is very promising tech and maps/markers in some sort are in nearly most of the modern apps, I do believe marker clustering should be implemented in google_maps_flutter asap. Can a pull request be made by an experienced developer? I am not sure if I should write this request here but i searched and did't come up with anywhere else.

**Comment by zoechi** [comment]
Looks like a duplicate of #26863
