### ISSUE TITLE
Non-obvious error when pub.dartlang.org isn't reachable

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2752]
From a user in a codelab: "I seem to be stuck at 'Building Flutter tool...'"

After diving in, we determined this is because the script couldn't reach pub.dartlang.org.

```
I have two pub processes that appear stuck?
13626 ?        Sl     0:04 /foo/tmp/flutter/bin/cache/dart-sdk/bin/dart /foo/tmp/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot get
15996 pts/39   Sl+    0:01 /foo/tmp/flutter/bin/cache/dart-sdk/bin/dart /foo/tmp/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot get
```

```
perhaps invoked from here: https://github.com/flutter/flutter/blob/master/bin/flutter#L25
```

Perhaps we could fail better here?

**Comment by sethladd** [comment]
Addressed by https://github.com/flutter/flutter/pull/2751 ?  @devoncarew

**Comment by devoncarew** [comment]
We should definitely be printing out errors from pub (#2751). I don't know if in this situation pub would have printed out a warning.

**Comment by Hixie** [comment]
This will probably be handled by https://github.com/flutter/flutter/issues/9898.
