### ISSUE TITLE
Flutter Gallery Sample Cupertino Enabled switch is shown as disabled. 

### ISSUE THREAD

**Issue by Kartik1607** [flutter/flutter#27527]
Bug Line : https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/cupertino/cupertino_switch_demo.dart#L65

**Comment by xster** [comment]
enabled here means interactive, which is orthogonal to it having a true or false value. Are there elements of the doc we should improve on?

**Comment by Kartik1607** [comment]
Hm.. it's confusing. The top most switch says active which means it can be changed. The second and third says disabled. I inferred that it meant the state of switch and thought the second one should have been enabled. Anyhow, if enabled means interactive shouldn't the first switch specify enabled and next two disables or the first should say active and next two inactive.

**Comment by xster** [comment]
You're right. It could be clearer. Commented on your PR. Thanks for your contribution
