### ISSUE TITLE
platform_view with support for SurfaceView in android

### ISSUE THREAD

**Issue by kartdroid** [flutter/flutter#27537]
As per documentation of platform_view ,  The embedded Android view is painted just like any other Flutter widget. 
Does that mean,  we don't get surface callbacks for SurfaceView ?
 
We are playing DRM contents on ExoPlayer and we need SurfaceView for that . 
Will flutter's platform_view help us in this regard .
If not , is there any alternate approach ?  
I would like to use flutter for rendering all other UI and use native SurfaceView only for Video rendering.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by ckarthickit** [comment]
ok will do thanks !

**Comment by ckarthickit** [comment]
I have posted this question in flutter-dev google groups as well .
https://groups.google.com/forum/#!topic/flutter-dev/ZZadkHOfXfM
Still no luck !

**Comment by BondarenkoStas** [comment]
@ckarthickit did you find a solution?

**Comment by darshankawar** [comment]
@kartdroid 
Flutter now support Hybrid composition which enables Android native views to be rendered as an independent View and composed along with Flutter UI and gives access to `SurfaceView`. Read [this](https://github.com/flutter/flutter/issues/55270) issue for more details.

Closing this.
