### ISSUE TITLE
How to get the image path in iOS

### ISSUE THREAD

**Issue by RayZhao1998** [flutter/flutter#27533]
I use method `getApplicationDocumentsDirectory()` in `path_provider` to get the image path.

However, when I `flutter run` or update my app in AppStore, the path got by `getApplicationDocumentDirectory()` will change and I can't get the image by the path stored before.

**Comment by mcplectrum** [comment]
This is probably a duplicate of: https://github.com/flutter/flutter/issues/23957

**Comment by GaryQian** [comment]
Closing, as is duplicate. See #23957 for further details.

**Comment by RayZhao1998** [comment]
Thanks.
