### ISSUE TITLE
SSL - SecurityContext - Unhandled Exception: FileSystemException: Cannot open file - Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by jelenalecic** [flutter/flutter#27536]
<img width="945" alt="screen shot 2019-02-05 at 10 07 52 am" src="https://user-images.githubusercontent.com/17471080/52262953-3707c000-292e-11e9-9eab-e6f0d643445d.png">

When I try to set certificate, I get an error:
```
E/flutter ( 7195): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Cannot open file, path = 'assets/ssl/STAR_octopusspace_com.crt' (OS Error: No such file or directory, errno = 2)
E/flutter ( 7195): #0      _File.throwIfError (dart:io/file_impl.dart:643:7)
E/flutter ( 7195): #1      _File.openSync (dart:io/file_impl.dart:487:5)
E/flutter ( 7195): #2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
E/flutter ( 7195): #3      _SecurityContext.useCertificateChain (dart:io/runtime/binsecure_socket_patch.dart:175:40)
```
... and this is my yaml file:
<img width="379" alt="screen shot 2019-02-05 at 10 13 59 am" src="https://user-images.githubusercontent.com/17471080/52266525-e9dc1c00-2936-11e9-969c-136e9cd9a724.png">

```
Jelenas-MacBook-Pro:flutter-comment-wall jelenalecic$ flutter doctor -v
[✓] Flutter (Channel master, v1.2.1-pre.66, on Mac OS X 10.13.6 17G4015, locale en-US)
    • Flutter version 1.2.1-pre.66 at /Users/jelenalecic/projects/flutter
    • Framework revision 496ddc580c (2 days ago), 2019-02-02 16:23:39 -0800
    • Engine revision 15f2b92cce
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 71bee8f05e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jelenalecic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • 5B28E6C4-2F19-4FA4-B3E9-AA64830E1B75 • ios         • iOS 12.1 (simulator)

• No issues found!

```

**Comment by wouterhardeman** [comment]
You probably need to load the file using [AssetBundle](https://docs.flutter.io/flutter/services/AssetBundle-class.html).

**Comment by jelenalecic** [comment]
@wouterhardeman hm.. not sure.. I need to provide only path(String) and not a file.

**Comment by wouterhardeman** [comment]
Instead of `useCertificateChain` and `usePrivateKey` you can use `useCertificateChainBytes` and `usePrivateKeyBytes` with the bytes loaded from AssetBundle. Here's a possible working example:

```dart
final List<int> certificateChainBytes = (await AssetBundle.load('your asset url')).buffer.asInt8List();
context.useCertificateChainBytes(certificateChainBytes);
```

Not sure if this will work, I just typed this in here.

**Comment by jelenalecic** [comment]
@wouterhardeman 

yup, I get to read them like this:

```
final List<int> certificateChainBytes =
        (await rootBundle.load('assets/ssl/STAR_octopusspace_com.crt')).buffer.asInt8List();
    context.useCertificateChainBytes(certificateChainBytes);
    final List<int> keyBytes =
    (await rootBundle.load('assets/ssl/client_octopusspace.key')).buffer.asInt8List();
    context.usePrivateKeyBytes(keyBytes);

    httpClient = HttpClient(context: context);
```

but now I get this exception:
`
E/flutter (11733): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: TlsException: Failure in usePrivateKeyBytes (OS Error: 
E/flutter (11733): 	KEY_VALUES_MISMATCH(ssl_cert.cc:494), errno = 0)
E/flutter (11733): #0      _SecurityContext.usePrivateKeyBytes (dart:io/runtime/binsecure_socket_patch.dart:164:50)`

so it must be somethin key-related.

**Comment by wouterhardeman** [comment]
Maybe you forgot to add the password of the key? Or maybe it doesn't match the public key in the certificate? It does seem related to your keys.

**Comment by jelenalecic** [comment]
@wouterhardeman  
this is what worked for me:
`
    final SecurityContext context = SecurityContext.defaultContext;

    final ByteData crtData = await rootBundle.load('assets/ssl/STAR_octopusspace_com.crt');
    context.setTrustedCertificatesBytes(crtData.buffer.asUint8List());

    final ByteData authoritiesBytes = await rootBundle.load('assets/ssl/STAR_octopusspace_com.ca-bundle');
    context.setClientAuthoritiesBytes(authoritiesBytes.buffer.asUint8List());

    final ByteData keyBytes = await rootBundle.load('assets/ssl/client_octopusspace.key');
    context.usePrivateKeyBytes(keyBytes.buffer.asUint8List());

    httpClient = HttpClient(context: context);
`

thanks a lot for your help :)

**Comment by wouterhardeman** [comment]
@jelenalecic No problem! Could you please close the issue?

**Comment by AugustusLi** [comment]
@wouterhardeman Hi, I am seeing the same issue, it wasted me a few hours until I saw this page. I think this is a walk-around, not a fix. 

I use File(), it doesn't throw error "no such file or directory"
`File file = File(path) `
then a few lines below, I am using following it throw error "no such file or directory"
`context.setClientAuthorities(path)`

Why one throw the error but the other doesn't??

At least, we should change the error message to let user knows they need to load the bytes instead.
