### ISSUE TITLE
camera permission not working for flashlight , Have to restart app to make it work for flashlight using lamp 0.0.6 plugin 

### ISSUE THREAD

**Issue by Shavneet** [flutter/flutter#27540]
I am using this code :

getCameraPermissionStatus() async {
var get = '';
List permissions = await Permission.getPermissionsStatus(
[PermissionName.Camera,]);
permissions.forEach((permission) {
get += '${permission.permissionName}: ${permission.permissionStatus}';
if (get != "PermissionName.Camera: PermissionStatus.allow") {
requestCameraPermission();
} else {
Lamp.turnOn();
}
});
}

requestCameraPermission() async {
final res = await Permission.requestPermissions([PermissionName.Camera,]);
res.forEach((permission) {
String a = '${permission.permissionStatus}';
setState(() {
if (a == 'PermissionStatus.allow') {
Lamp.turnOn();
}
else {
Permission.openSettings;
}
});
});
}

So with this code I am successfully turning On the camera permission but ''Lamp.turnOn()'' is not turning on the flash in first attempt . Has to restart the app to turn it on . Permission gets turned on in first attempt (can be checked in app info ) but starts working after killing app and restarting app .

Packages I am using :
permission: ^0.1.1
lamp: ^0.0.6 .

Please help if anyone knows anything about this or any other ideas will be appreciated . Thanks .

**Comment by wouterhardeman** [comment]
These are not first-party plugins supported by the Flutter team.

Please file your issue in the GitHub repositories of [permission](https://github.com/once10301/permission) or [lamp](https://github.com/clovisnicolas/flutter_lamp).

**Comment by GaryQian** [comment]
Closing as there isn't anything we can do here. Feel free to reopen if there are any directly related Flutter problems!

**Comment by Shavneet** [comment]
> These are not first-party plugins supported by the Flutter team.
> 
> Please file your issue in the GitHub repositories of [permission](https://github.com/once10301/permission) or [lamp](https://github.com/clovisnicolas/flutter_lamp).

@wouterhardeman   ok sir, Can you please tell me that how to check a plugin, if it is a first party supported by flutter team or any other third party plugin ??

@wouterhardeman  sir please also refer me to official documentation for "permissions in flutter" . 

Thanks.

**Comment by Shavneet** [comment]
> Closing as there isn't anything we can do here. Feel free to reopen if there are any directly related Flutter problems!

Thanks for your reply .
May i know the reason that why you can't do anything here ??

**Comment by zoechi** [comment]
@Shavneet look it up on the package page https://pub.dartlang.org/packages/url_launcher

![image](https://user-images.githubusercontent.com/405837/52574841-6c744800-2e1d-11e9-8fb3-21c0f7cef0a2.png)

or if the repository link 

![image](https://user-images.githubusercontent.com/405837/52574884-831a9f00-2e1d-11e9-862f-680a445f2f8e.png)

points to http://github.com/flutter/...

**Comment by zoechi** [comment]
> May i know the reason that why you can't do anything here ??

These issues are for Flutter bugs and feature request and your issue is about a 3rd party issue that should be reported with this 3rd party.
