### ISSUE TITLE
API for string collation (locale-aware string comparison)

### ISSUE THREAD

**Issue by nickolas-pohilets** [flutter/flutter#27549]
Flutter uses ICU under the hood which implements all the necessary collation algorithms, but does not expose any API to use them.

**Comment by zoechi** [comment]
Can you please file in https://github.com/dart-lang/sdk
These existing feature requests might cover your request partially or be related.
https://github.com/dart-lang/sdk/issues/28404
https://github.com/dart-lang/sdk/issues/3174
https://github.com/dart-lang/language/issues/49
