### ISSUE TITLE
Fab stays above drawer

### ISSUE THREAD

**Issue by ardacebi** [flutter/flutter#27543]
I have a working bottom navigation bar with fab  work a completely fine. Recently I inserted a navigation drawer and I’m having an issue. When the drawer is open, the fab orante hide with the other elementary instead, stays on the drawer without a color change. See gif below.

![4c0c0a13-9c05-4878-b39d-683fa34f7c38](https://user-images.githubusercontent.com/17576065/52272178-05efb580-2957-11e9-834f-9639d7b8851e.gif)

**Comment by wouterhardeman** [comment]
Please provide a minimal, reproducible example and the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
@ardacebi can you please make the code need a self-contained **minimal** **runnable** reproduction
as **a single file** so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by dekadevelop** [comment]
Any solution?

**Comment by pedromassangocode** [comment]
Hi @ardacebi 
Can you confirm that this still a valid issue?
Thank you

**Comment by ardacebi** [comment]
Hey @pedromassangocode,

That code is totally lost atm and I don't know where it is anymore, I left that project. So I can't have the same environment I got that error.
