### ISSUE TITLE
Atom flutter version... doesn't work

### ISSUE THREAD

**Issue by ferhatb** [flutter/flutter#2756]
### Steps to Reproduce
To file bug, selected Packages/Flutter/Flutter Version...  it didn't do anything.

### Flutter Version
0.2.1

**Comment by devoncarew** [comment]
Hmm, perhaps it wasn't able to locate the flutter sdk? That needs to be manually configured in Settings > Packages > flutter (if it is not able to auto-detect the location).

**Comment by ferhatb** [comment]
Correct. It shows SDK not configured now. On fresh install it was silent with no popup. Can't repro. Please closing issue.
