### ISSUE TITLE
Dio package throwing http status 500 error if version was not changed from 1.0.x to 2.0.0

### ISSUE THREAD

**Issue by nikhil-francium** [flutter/flutter#27583]
`flutter packages upgrade` command is not upgrading my `dio package` version from 1.0.x to 2.0.0.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by kangwang1988** [comment]
See: https://www.dartlang.org/tools/pub/dependencies#caret-syntax for more.
