### ISSUE TITLE
LocalAuthentication throwing Platfrom exception error

### ISSUE THREAD

**Issue by DeepaVPanicker** [flutter/flutter#27584]
When i run this, I'm getting a platform exception error:
```
PlatformException(auth_in_progress, Authentication in progress, null)
```

```dart
Future<bool> biometrics() async {
    final LocalAuthentication _localAuth = LocalAuthentication();
    bool authenticated = false;
    try {
      authenticated = await _localAuth.authenticateWithBiometrics(
        localizedReason: 'Scan your fingerprint to authenticate',
        useErrorDialogs: true,
        stickyAuth: false
      );
    } on PlatformException
    catch(e) {
      print(e);
    }
    return authenticated;
  }
```

**Comment by kangwang1988** [comment]
@DeepaVPanicker 
Paste "flutter doctor -v" and create a minimal demo project which can reproduce this issue if possible.

**Comment by DeepaVPanicker** [comment]
output of flutter doctor::
````[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.14393], locale en-IN)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Deepa663180\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 32-bit edition (version 1.30.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • LLD AL20 • BRB3Y18614008282 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by DeepaVPanicker** [comment]
Steps to reproduce the error:

````import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  State<StatefulWidget> createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {

  Future<bool> biometrics() async {
    final LocalAuthentication _localAuth = LocalAuthentication();
    bool authenticated = false;
    try {
      authenticated = await _localAuth.authenticateWithBiometrics(
        localizedReason: 'Scan Your fingerprint to authenticate',
        useErrorDialogs: true,
        stickyAuth: false
      );
    } on PlatformException
    catch (e) {
      print(e);
    }
    return authenticated;
  }

  loginWithBio() async {
    bool login = false;
    try {
      login = await biometrics();
      if (login) {
        print("logged in successfully");
      }
    }
    catch(e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {

    return new MaterialApp(
      home: new Scaffold(
        body: new Center(
          child: new RaisedButton(onPressed: (){loginWithBio();}, child: Text('login'),),
        ),
      ),
    );
  }
}

**Comment by kangwang1988** [comment]
@DeepaVPanicker 
It's not a bug, just to avoid multiple calls.
```
      if (!authInProgress.compareAndSet(false, true)) {
        // Apps should not invoke another authentication request while one is in progress,
        // so we classify this as an error condition. If we ever find a legitimate use case for
        // this, we can try to cancel the ongoing auth and start a new one but for now, not worth
        // the complexity.
        result.error("auth_in_progress", "Authentication in progress", null);
        return;
      }
```

**Comment by crcaicedo** [comment]
Sorry, is a bug! The same code runs perfect on iOS but fails on Android. How to avoid local_auth library calls twice or more of their routines? Seems that it is what happens

**Comment by crcaicedo** [comment]
https://stackoverflow.com/questions/54554053/how-to-fix-platform-exception-error-auth-in-progress-for-flutter-local-authent

--- BEGIN QUOTE ---

This happens on Android. You have to modify your MainActivity to implement FlutterFragmentActivity to use local_auth plugin. Change your code from this (Kotlin on my example):

``
import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
``

To this:

``
import android.os.Bundle

import io.flutter.app.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterFragmentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
``

Also you need to add this two lines to your gradle.properties file.

android.useAndroidX=true
android.enableJetifier=true

This error is hard to find since version 0.5.1, because the plugin doesn't throw the right exception, and the documentation doesn't tell you to implement this base class.

--- END OF QUOTE ---

**Comment by ReneRamos76** [comment]
I had the same problem, leave everything as at the beginning but I followed the official androidx documentation and it worked with the latest versions of the local_auth 0.5.2 + 3 plugin and it worked as expected. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by ReneRamos76** [comment]
I had the same problem, leave everything as in the beginning, without changing to FlutterFragmentActivity, but I followed the official androidx documentation and it worked with the latest versions of the local_auth 0.5.2 + 3 plugin and it worked as expected. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility...

**Comment by mbikt** [comment]
The actual bug is, `auth_in_progress` state never finished. The error can be reproduced sometimes  canceling _the auth dialog_. Calling `authenticateWithBiometrics` *quickly* did not bring up _the auth dialog_ again. Calling `authenticateWithBiometrics` *after a while* may _the auth dialog_ again. 

Previously call  `authenticateWithBiometrics` in `initState` with `stickyAuth` to `true` and get done. Now need to handle extra cases.

**Comment by wahyusidik** [comment]
> The actual bug is, `auth_in_progress` state never finished. The error can be reproduced sometimes canceling _the auth dialog_. Calling `authenticateWithBiometrics` _quickly_ did not bring up _the auth dialog_ again. Calling `authenticateWithBiometrics` _after a while_ may _the auth dialog_ again.
> 
> Previously call `authenticateWithBiometrics` in `initState` with `stickyAuth` to `true` and get done. Now need to handle extra cases.

hi, can you help to solve the problem? I have the same problem, the auth_in_progress  is taking forever and the authentication dialog won't show up.

**Comment by mbikt** [comment]
@wahyusidik I am still figuring out the issue. I found that I have being invoking `authenticateWithBiometrics` from two different places. After refactoring into one centralized call to `authenticateWithBiometrics`, it seems no more `auth_in_progress` error so far tested.

**Comment by CoderJava** [comment]
> https://stackoverflow.com/questions/54554053/how-to-fix-platform-exception-error-auth-in-progress-for-flutter-local-authent
> 
> --- BEGIN QUOTE ---
> 
> This happens on Android. You have to modify your MainActivity to implement FlutterFragmentActivity to use local_auth plugin. Change your code from this (Kotlin on my example):
> 
> ```
> import android.os.Bundle
> 
> import io.flutter.app.FlutterActivity
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     GeneratedPluginRegistrant.registerWith(this)
>   }
> }
> ```
> 
> To this:
> 
> ```
> import android.os.Bundle
> 
> import io.flutter.app.FlutterFragmentActivity
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     GeneratedPluginRegistrant.registerWith(this)
>   }
> }
> ```
> 
> Also you need to add this two lines to your gradle.properties file.
> 
> android.useAndroidX=true
> android.enableJetifier=true
> 
> This error is hard to find since version 0.5.1, because the plugin doesn't throw the right exception, and the documentation doesn't tell you to implement this base class.
> 
> --- END OF QUOTE ---

Thanks. It's worked

**Comment by rajeshzmoke** [comment]
Why is this issue closed ? 
I'm facing this issue now.

```[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at /Users/rajeshkumar/Desktop/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshkumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rajeshkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • HighPeaksw iPhone X • 76fd22d0d6fe8432a90a895351b60bd1d159e8ef • ios • iOS 12.3.1

• No issues found!
```

Error
`PlatformException(auth_in_progress, Authentication in progress, null)`

Local_auth plugin version 

`local_auth: ^0.5.2+4`

**Comment by Deepavsp** [comment]
@rajeshzmoke- I changed stickauth to true and it worked properly. Check if you're able to get the list to available biometrics with getAvailableBiometrics() method

**Comment by nonoyek** [comment]
The error still there after i change the MainActivity.... how to make it work? need help guysss....

**Comment by CoderJava** [comment]
> The error still there after i change the MainActivity.... how to make it work? need help guysss....

Try run command `flutter clean`

**Comment by prasanth8** [comment]
bool canCheckBiometrics =
    await localAuth.canCheckBiometrics;
    List<BiometricType> availableBiometrics =
    await localAuth.getAvailableBiometrics();
    print("checkBiometric");
    print((canCheckBiometrics));
    print("List");
    print(availableBiometrics);

    bool authenticated = false;
    try {
      authenticated = await localAuth.authenticateWithBiometrics(
          localizedReason: 'Scan your fingerprint to authenticate',
          useErrorDialogs: true,
          stickyAuth: false);
    } on PlatformException catch (e) {
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _authorized = authenticated ? 'Authorized' : 'Not Authorized';
    });



  local_auth: ^0.5.2


I/flutter ( 5922): PlatformException(auth_in_progress, Authentication in progress, null)


i m still facing this issue some one help to resolve it

**Comment by cutzmf** [comment]
Same with local_auth: ^0.6.0
MainActivity extends FlutterFragmentActivity
Migrated to AndroidX

Is next maybe an issue?
Possible fixes?

`E/MethodChannel#plugins.flutter.io/local_auth: Failed to handle method call
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

**Comment by nonoyek** [comment]
How to change the user interface of the finger print prompt, now I able to make it but it's so ugly with some black color design. How to change it to another design?

**Comment by enricobenedos** [comment]
> How to change the user interface of the finger print prompt, now I able to make it but it's so ugly with some black color design. How to change it to another design?

There is an already opened issue for this problem [#35724](https://github.com/flutter/flutter/issues/35724). For now it is better to use `local_auth: ^0.4.0+1`

**Comment by chriswellingsfairsailcom** [comment]
Yeah I had to go back to v0.0.4+1 as 0.6.0+1 just does not work on old Androids and has the error: 

PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null)

This is with all the FlutterFragmentActivity changes and running lovely AndroidX code etc etc

**Comment by nonoyek** [comment]
Ah... Sad.. hopefully can fix asap

**Comment by Sepehr13** [comment]
> Yeah I had to go back to v0.0.4+1 as 0.6.0+1 just does not work on old Androids and has the error:
> 
> PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null)
> 
> This is with all the FlutterFragmentActivity changes and running lovely AndroidX code etc etc

i'm getting the same error.
Any fix for this? i really need this plugin

**Comment by chriswellingsfairsailcom** [comment]
Yes - see the comment in https://github.com/flutter/flutter/issues/35724:

The fix is changing the parent style of the theme of the MainActivity from @android:style/Theme.Black.NoTitleBar to Theme.AppCompat.Light.NoActionBar.

**Comment by Sepehr13** [comment]
> Theme.AppCompat.Light.NoActionBar

it fixed the problem but now i can't use the onResume in my kotlin file. i guess this plugin has some serious implementation problem :|

**Comment by liutaodev** [comment]
> https://stackoverflow.com/questions/54554053/how-to-fix-platform-exception-error-auth-in-progress-for-flutter-local-authent
> 
> --- BEGIN QUOTE ---
> 
> This happens on Android. You have to modify your MainActivity to implement FlutterFragmentActivity to use local_auth plugin. Change your code from this (Kotlin on my example):
> 
> ```
> import android.os.Bundle
> 
> import io.flutter.app.FlutterActivity
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterActivity() {
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     GeneratedPluginRegistrant.registerWith(this)
>   }
> }
> ```
> 
> To this:
> 
> ```
> import android.os.Bundle
> 
> import io.flutter.app.FlutterFragmentActivity
> import io.flutter.plugins.GeneratedPluginRegistrant
> 
> class MainActivity: FlutterFragmentActivity() {
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(savedInstanceState)
>     GeneratedPluginRegistrant.registerWith(this)
>   }
> }
> ```
> 
> Also you need to add this two lines to your gradle.properties file.
> 
> android.useAndroidX=true
> android.enableJetifier=true
> 
> This error is hard to find since version 0.5.1, because the plugin doesn't throw the right exception, and the documentation doesn't tell you to implement this base class.
> 
> --- END OF QUOTE ---

thank you very much!

**Comment by zgramming** [comment]
> Yes - see the comment in #35724:
> 
> The fix is changing the parent style of the theme of the MainActivity from @android:style/Theme.Black.NoTitleBar to Theme.AppCompat.Light.NoActionBar.


After add this  `<style name="LaunchTheme" parent="@android:style/Theme.AppCompat.Light.NoActionBar">`
I'm getting this error : 
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource android:style/Theme.AppCompat.Light.NoActionBar not found.
     error: failed linking references.
```

**Comment by alevittoria** [comment]
I solved changed from 
<style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
to
<style name="LaunchTheme" parent="Theme.AppCompat.NoActionBar">

**Comment by caseyryan** [comment]
The bug still exists. 
Authentication works for the first time. Then you minimize the app and maximize again, try to authenticate with a fingerprint and the app crashes with "PlatformException(auth_in_progress, Authentication in progress, null)"

**Comment by talatkuyuk** [comment]
I have the same issue.
I use local_auth: ^0.6.2+1, and try ^0.6.1+3,
the same I receive "PlatformException(auth_in_progress, Authentication in progress, null)" message, it didnt work at all.
I set all things on android build that document says. Can't figure out the problem.

**Comment by Muniru0** [comment]
But where are they developers

**Comment by Muniru0** [comment]
They should say something
