### ISSUE TITLE
type 'Future<dynamic>' is not a subtype of type '() => void'

### ISSUE THREAD

**Issue by Yogita75** [flutter/flutter#27582]
here is my new.dart file:
import 'dart:io';
import 'dart:math';
import 'package:arluchat3/home_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:path/path.dart';
import 'package:arluchat3/myData.dart';

class ChannelPage2 extends StatefulWidget{

  @override
  ChannelPage2State createState() => ChannelPage2State();
}

enum values {one, two}

class ChannelPage2State extends State<ChannelPage2> {
  int groupvalue;

  values _character = values.one;

  final _formKey = GlobalKey<FormState>();
  bool _autovalidate = false;

  String channeltype, link, u_id;
  TextEditingController chlink = new TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.lightBlue,
          leading: new IconButton(
              icon: Icon(Icons.arrow_back, color: Colors.white,),
              onPressed: () {
                Navigator.of(context).pop();
                Navigator.push(context,
                    new MaterialPageRoute(
                        builder: (BuildContext context) => new HomeScreen()));
              }
          ),
          title: Text("Settings"),
          actions: <Widget>[

            new IconButton(icon: Icon(Icons.done, color: Colors.white,),
              onPressed: savechannels(),
            )
          ],
        ),

        body:
        SafeArea(
          child: SingleChildScrollView(
            child: new Container(
              padding: EdgeInsets.only(top: 16.0),
              child: Form(
                key: _formKey,
                autovalidate: true,

                child: Column(
                    children: <Widget>[

                      RadioListTile<values>(
                        title: const Text('Public Channel'),
                        subtitle: Text(
                            "Public channels can be found in search, anyone can join them."),
                        value: values.one,
                        groupValue: _character,
                        onChanged: (values value) {
                          setState(() {
                            _character = value;
                          });
                        },
                      ),
                      RadioListTile<values>(
                        title: const Text('Private Channel'),
                        subtitle: const Text(
                            "Private channels can only be join via an invite link."),
                        value: values.two,
                        groupValue: _character,
                        onChanged: (values value) {
                          setState(() {
                            _character = value;
                          });
                        },
                      ),

                      Divider(height: 30.0, color: Colors.white,),
                      Container(
                        height: 10.0,
                        color: Colors.blueGrey[50],
                      ),
                      Divider(height: 5.0, color: Colors.white,),
                      ListTile(
                        leading: Text("Permanent link",
                          style: TextStyle(color: Colors.blue,
                              fontWeight: FontWeight.bold),),
                      ),

                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 11.0),
                        child: TextFormField(
                          initialValue: '/t.me',
                          //controller: chlink,
                          autovalidate: true,
                          validator: validateLink,
                          onSaved: (String value) {
                            link = value;
                            //chlink.clear();
                          },

                        ),
                      ),
                      Divider(height: 30.0, color: Colors.white,),
                      Container(
                        height: 10.0,
                        color: Colors.blueGrey[50],
                      ),
                      Divider(height: 6.0, color: Colors.white,),

                      ListTile(
                        leading: Text(
                          "If you set a permanent link, other people will be able to find and join your channel.",
                          style: TextStyle(color: Colors.grey),),
                      ),
                      Divider(height: 0.0, color: Colors.white,),
                      ListTile(
                        leading:
                        Text(
                            " You can use a-z, 0-9 and underscores.\n Minimum length is 5 characters.",
                            style: TextStyle(color: Colors.grey)),

                      )

                    ]
                ),
              ),
            ),
          ),
        )

    );
  }

  String validateLink(String value) {
    String patttern = r'(^[a-zA-Z ]*$)';
    RegExp regExp = new RegExp(patttern);
    if (value.length == 0) {
      return "Name is Required";
    } else if (!regExp.hasMatch(value)) {
      return "Name must be a-z and A-Z";
    }
    return null;
  }

  savechannels() async {
    if (_formKey.currentState.validate()) {
      _formKey.currentState.save();

    DatabaseReference ref = FirebaseDatabase.instance.reference();

    var data = {
      "channeltype": _character,
      "link": link,

    };
    ref.child('NewChannels/').push().set(data).then((v) {
      _formKey.currentState.reset();
    });
    } else {
      setState(() {
        _autovalidate = true;
      });
    }
    }
  }
## Steps to Reproduce

1. whenever i click on tick icon it throws the exception and app gets stuck in that exception.

## Logs

I/flutter (22805): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22805): The following assertion was thrown building ChannelPage2(dirty, state: ChannelPage2State#e8103):
I/flutter (22805): type 'Future<dynamic>' is not a subtype of type '() => void'
I/flutter (22805): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22805): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22805): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22805):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22805): When the exception was thrown, this was the stack:
I/flutter (22805): #0      ChannelPage2State.build (package:arluchat3/drawer/new.dart:51:26)
I/flutter (22805): #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (22805): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (22805): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (22805): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #10     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (22805): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (22805): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #26     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (22805): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (22805): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #36     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (22805): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (22805): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
I/flutter (22805): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (22805): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter (22805): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (22805): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (22805): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (22805): #56     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (22805): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (22805): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (22805): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22805): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (22805): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (22805): #63     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (22805): #64     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (22805): #65     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (22805): (elided one frame from package dart:async)
I/flutter (22805): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (22805): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (22805): Invalid argument: Instance of 'values'
E/flutter (22805): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:353:7)
E/flutter (22805): #1      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:350:9)
E/flutter (22805): #2      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
E/flutter (22805): #3      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:348:13)
E/flutter (22805): #4      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:350:9)
E/flutter (22805): #5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
E/flutter (22805): #6      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:348:13)
E/flutter (22805): #7      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:506:18)
E/flutter (22805): #8      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:288:13)
E/flutter (22805): <asynchronous suspension>
E/flutter (22805): #9      DatabaseReference.set (file:///home/yogita/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-1.0.5/lib/src/database_reference.dart:73:31)
E/flutter (22805): #10     ChannelPage2State.savechannels (package:arluchat3/drawer/new.dart:176:38)
E/flutter (22805): <asynchronous suspension>
E/flutter (22805): #11     ChannelPage2State.build (package:arluchat3/drawer/new.dart:51:26)
E/flutter (22805): #12     StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
E/flutter (22805): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
E/flutter (22805): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (22805): #15     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
E/flutter (22805): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
E/flutter (22805): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (22805): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (22805): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
E/flutter (22805): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
E/flutter (22805): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
E/flutter (22805): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
E/flutter (22805): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
E/flutter (22805): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (22805): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (22805): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
E/flutter (22805): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (22805): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (22805): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3781:5)
E/flutter (22805): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
E/flutter (22805): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (22805): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (22805): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
E/flutter (22805): #42     Elemen
I/FirebaseAuth(22805): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(22805): [FirebaseAuth:] Preparing to create service connection to gms implementation

**Comment by Kartik1607** [comment]
Change
```dart
 new IconButton(icon: Icon(Icons.done, color: Colors.white,),
          onPressed: savechannels(),
        )
```

to 

```dart
 new IconButton(icon: Icon(Icons.done, color: Colors.white,),
          onPressed: savechannels,
        )
```

**Comment by GaryQian** [comment]
Thanks for answering! Closing as there doesn't seem like anything we need to do here!

**Comment by jain-shreyansh** [comment]
I need to call a function after an on tap is detected and the for the function a variable needs to be passed

so something like this is required

```
new IconButton(icon: Icon(Icons.done, color: Colors.white,),
          onPressed: savechannels(variable),
        )
```
What can I do to implement this?

**Comment by leslielyj** [comment]
> 
> 
> I need to call a function after an on tap is detected and the for the function a variable needs to be passed
> 
> so something like this is required
> 
> ```
> new IconButton(icon: Icon(Icons.done, color: Colors.white,),
>           onPressed: savechannels(variable),
>         )
> ```
> 
> What can I do to implement this?

You can store variable in a setState and call it in savechannels.

**Comment by garmashev** [comment]
try with `() => savechannels(variable)`

**Comment by KCIV** [comment]
Just to be clear for future googles. if you have existing code that looks like this
`onPressed: _launchURL,`
You would want to change it to this below.
`onPressed: () => _launchURL(variable),`

**Comment by Nyarko** [comment]
> Just to be clear for future googles. if you have existing code that looks like this
> `onPressed: _launchURL,`
> You would want to change it to this below.
> `onPressed: () => _launchURL(variable),`

Thanks sooo very much... this really helped me a lot!!!

**Comment by lyj0309** [comment]
li's work ,but why?

**Comment by KrzysztofJozefowicz** [comment]
> onPressed: () => _launchURL(variable),
Thank you!
