### ISSUE TITLE
TextField documentation should say the order in which onSubmitted vs onEditingComplete vs onChanged happens

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27581]
The documentation for each of these events doesn't mention the others.

**Comment by Hixie** [comment]
Looks like we document it at https://master-docs.flutter.io/flutter/widgets/EditableText-class.html

**Comment by zoeyfan** [comment]
@Hixie if I understand correctly, the lifecycle section in the above documentation did document the order, so we can close this now? Or anything else needs to be documented?

**Comment by Hixie** [comment]
The original description still applies, e.g. see https://api.flutter.dev/flutter/cupertino/CupertinoTextField/onEditingComplete.html

**Comment by pedromassangocode** [comment]
I was able to reproduce this in `1.21.0-1.0.pre`. According to the `TextField` widget's docs there is no information related to the order in which those callbacks are executed.

https://github.com/flutter/flutter/blob/1840b7121a6a721484afca300265c7866e82dc77/packages/flutter/lib/src/material/text_field.dart#L133-L258


<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (2 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by feinstein** [comment]
As far as I understand, the default behavior of [onEditingComplete](https://api.flutter.dev/flutter/cupertino/CupertinoTextField/onEditingComplete.html) is not what I see with a `TextFormField`.

The docs say:

>* When a non-completion action is pressed, such as "next" or "previous", the user's content is submitted to the controller, but focus is not given up because developers may want to immediately move focus to another input widget within onSubmitted.

But if don't define any `onEditingComplete` (which means it will use the default behavior) and set a keyboard with a `next` button, it does give up focus and goes to the next form field.

The differences of each of the callbacks should be better explained, with examples preferably, and the lifecycle section should be expanded.
