### ISSUE TITLE
Flutter Build Error: Process 'command 'E:\Flutter Apps\flutter\bin\flutter.bat'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by dheerajbred** [flutter/flutter#27593]
I got this error when I try to generate a signed apk in the android studio of my flutter app -
` _Process 'command 'E:\Flutter Apps\flutter\bin\flutter.bat'' finished with non-zero exit value 1_`

I am able to run the app in both emulator and on my device but this error shows up only when I try to build a signed apk.

```
flutter doctor
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17763.253], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.30.2)
[√] Connected device (1 available)

• No issues found!
```
Any way to fix this?

Tried` flutter clean`
and android studio `Build > clean project and rebuild project`(same error)

I am doing Build > Generated signed apk > apk > release > V1(Jar signature) > Finish to build the app

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please add the full build log output.

**Comment by kangwang1988** [comment]
@dheerajbred 
Try
```
flutter build apk --release -vv 
```
And paste result here.

**Comment by gauseen** [comment]
@zoechi 
I have the same problem.
```sh
$ flutter doctor -v                                                                                   
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.16299.847], locale   
    zh-CN)                                                                                            
    • Flutter version 1.7.8+hotfix.3 at E:\flutter-space\flutter                                      
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700                           
    • Engine revision 54ad777fd2                                                                      
    • Dart version 2.4.0                                                                              
                                                                                                      
                                                                                                      
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)                      
    • Android SDK at C:\Users\18110026\AppData\Local\Android\sdk                                      
    • Android NDK location not configured (optional; useful for native profiling support)             
    • Platform android-29, build-tools 29.0.0                                                         
    • Java binary at: D:\application\Android-Studio\jre\bin\java                                      
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)                     
    • All Android licenses accepted.                                                                  
                                                                                                      
[√] Android Studio (version 3.4)                                                                      
    • Android Studio at D:\application\Android-Studio                                                 
    • Flutter plugin version 37.0.1                                                                   
    • Dart plugin version 183.6270                                                                    
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)                     
                                                                                                      
[√] Connected device (1 available)                                                                    
    • DUK AL20 • FFKDU17320004487 • android-arm64 • Android 9 (API 28)                                
                                                                                                      
• No issues found!                                                                                    
```

**Comment by mcxinyu** [comment]
I also encountered this problem.

**Comment by takhello** [comment]
/flare.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
[   +1 ms]  - 'Int32List' is from 'dart:typed_data'.
[        ]  - 'Uint16List' is from 'dart:typed_data'.
[        ] Try changing the type of the parameter, or casting the argument to 'Uint16List'.
[   +1 ms]         indices: _indices, textureCoordinates: _uvBuffer);
[        ]                  ^
[+3566 ms] Compiler terminated unexpectedly.
[ +106 ms] > Task :app:compileflutterBuildReleaseArm FAILED
[   +1 ms] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'D:\userTool\flutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 638
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileflutterBuildReleaseArm'.
[        ] > Process 'command 'D:\userTool\flutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 13s
[ +444 ms] Running Gradle task 'assembleRelease'... (completed in 14.4s)
[   +3 ms] "flutter apk" took 36,843ms.
[        ] "flutter apk" took 36,843ms.
Gradle task assembleRelease failed with exit code 1

**Comment by William-HL1991** [comment]
the same problem
`[  +20 ms] Resolving dependencies... (completed in 3.7s)
[   +3 ms] Running Gradle task 'assembleRelease'...
[   +5 ms] executing: [/home/android/agile-note/workspace/master/note/android/] /home/android/agile-note/workspace/master/note/android/gradlew -Pverbose=true
-Ptarget=lib/main.dart -Ptrack-widget-creation=false -Ptarget-platform=android-arm,android-arm64 assembleRelease
[+4301 ms] > Task :app:compileflutterBuildReleaseArm
[   +7 ms] Setting VM flags failed: Unrecognized flags: sim-use-hardfp, use-integer-division
[  +22 ms] Dart snapshot generator failed with exit code 255
[        ] Snapshotting exited with non-zero exit code: 255
[  +31 ms] > Task :app:compileflutterBuildReleaseArm FAILED
[        ] 1 actionable task: 1 executed
[        ]          *********************************************************
[        ] WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/home/android/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 638
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileflutterBuildReleaseArm'.
[        ] > Process 'command '/home/android/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 4s
[ +367 ms] Running Gradle task 'assembleRelease'... (completed in 4.7s)
[   +9 ms] "flutter apk" took 10,476ms.
[        ] "flutter apk" took 10,476ms.
Gradle task assembleRelease failed with exit code 1`

**Comment by anonmanx** [comment]
Same here

**Comment by mehdok** [comment]
I have the same error but with different way to produce it, if I open my project as `flutter` project everything is fine and I can build the app, but if I open the `android` project separately Gradle sync will fail with the same error.

**Comment by amjadsh97** [comment]
same problem

**Comment by octaplexsys** [comment]
same issue

**Comment by Gmlogy** [comment]
same here

**Comment by bgrgv** [comment]
same here

**Comment by x1200085** [comment]
今天我遇到了这个问题，是因为pubspec.yaml这个配置文件中有数据格式写错了，如果大家遇到这个问题，可以先检查一下这个配置文件中是否有错误。如图
![1](https://user-images.githubusercontent.com/16258293/65492005-b90b2000-dee2-11e9-8399-c5b5bab656db.png)

**Comment by shravyamachanna** [comment]
I had the same issue when I opened the android project and I removed "android.enableR8=true" line from android project's gradle.properties file and it worked.

**Comment by michcio53** [comment]
I had also the same issue. I have two main files one called main_prod and one called main_dev. When I was compiling my project on VS Code everything worked fine (because of lanuch.json config), but when I was compiling it with android studio there was an error. 
I solved that issue by changing one on my main files to just "main.dart"

**Comment by Coronel125** [comment]
I just use: `flutter clean` and it works.

**Comment by eduribas** [comment]
@michcio53 I have the same issue and the same environment (3 main files: main_dev, main_alpha and main_prod). Your solution solved my issue, after creating a dummy main.dart with an empty `main() {}` method it compiled. So looks like the graddle plugin needs a default main.dart with a main() method.

**Comment by zayngdev** [comment]
Usual because there is a compiling error in the code

**Comment by MarFry** [comment]
In my case it was wrong import path. I drag a file from one package and drop it into another. The IDE generated some wierd import path and after I fixed it everything went back to normal.
![obraz](https://user-images.githubusercontent.com/23052996/75521389-eca92380-5a07-11ea-9148-e0ffbe7d53b0.png)

**Comment by ahmedfayed29** [comment]
same here

**Comment by vanlalruata** [comment]
I get the same error.

Here is my Log file.

[+6800 ms] [+6755 ms] 
[   +2 ms]            Compiler message:
[   +1 ms] [   +1 ms] /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
[   +1 ms] [        ]         animation: animation,
[   +1 ms] [        ]         ^^^^^^^^^
[        ] [        ] /C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   CupertinoFullscreenDialogTransition({
[        ] [        ]   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+4488 ms] [+4576 ms] Persisting file store
[   +1 ms] [  +14 ms] Done persisting file store
[   +1 ms] [        ] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[ +101 ms] [   +9 ms] "flutter assemble" took 13,250ms.
[   +5 ms] build failed.
[   +3 ms] #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[   +1 ms] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:197:7)
[   +4 ms] #2      _rootRunUnary (dart:async/zone.dart:1192:38)
[   +6 ms] #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +3 ms] #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +1 ms] #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +1 ms] #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #10     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms] #11     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +1 ms] #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ] #20     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +1 ms] #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #26     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
[   +1 ms] #27     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #29     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ] #36     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #37     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #38     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #40     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #41     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #42     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
[        ] #43     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #44     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #45     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #47     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #48     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #51     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms] #52     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #53     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #54     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #55     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #56     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #57     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #58     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
[        ] #59     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #60     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #61     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #62     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #63     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #64     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] #65     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] #66     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #67     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[        ] #68     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
[        ] #69     _rootRunBinary (dart:async/zone.dart:1204:38)
[        ] #70     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[        ] #71     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
[        ] #72     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
[        ] #73     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
[        ] #74     Future._completeError (dart:async/future_impl.dart:534:5)
[        ] #75     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
[        ] #76     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart)
[        ] #77     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #78     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #79     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #80     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #81     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #82     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #83     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] #84     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +2 ms] #85     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[   +3 ms] #86     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #87     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #88     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #89     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #90     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #91     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] #92     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
[   +1 ms] #93     _rootRun (dart:async/zone.dart:1184:13)
[   +1 ms] #94     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] #95     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] #96     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[        ] #97     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[   +1 ms] #98     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] #99     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ] #100    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[   +1 ms] > Task :app:compileFlutterBuildRelease FAILED
[  +16 ms] FAILURE: Build failed with an exception.
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 1 actionable task: 1 executed
[        ] * Where:
[        ] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 840
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2m 22s
[ +373 ms] Running Gradle task 'assembleRelease'... (completed in 142.9s, longer than expected)
[   +5 ms] "flutter apk" took 1,43,628ms.
Gradle task assembleRelease failed with exit code 1

**Comment by Ccalary** [comment]
flutter clean

**Comment by jeeali** [comment]
> I get the same error.
> 
> Here is my Log file.
> 
> [+6800 ms] [+6755 ms]
> [ +2 ms] Compiler message:
> [ +1 ms] [ +1 ms] /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.1/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
> [ +1 ms] [ ] animation: animation,
> [ +1 ms] [ ] ^^^^^^^^^
> [ ] [ ] /C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
> [ ] [ ] CupertinoFullscreenDialogTransition({
> [ ] [ ] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [+4488 ms] [+4576 ms] Persisting file store
> [ +1 ms] [ +14 ms] Done persisting file store
> [ +1 ms] [ ] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> [ +101 ms] [ +9 ms] "flutter assemble" took 13,250ms.
> [ +5 ms] build failed.
> [ +3 ms] #0 throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
> [ +1 ms] #1 AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:197:7)
> [ +4 ms] #2 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ +6 ms] #3 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ +3 ms] #4 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ +1 ms] #5 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ +1 ms] #6 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ +1 ms] #7 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ +1 ms] #8 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> [ +1 ms] #9 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> [ +1 ms] #10 BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
> [ +1 ms] #11 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ +1 ms] #12 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ +1 ms] #13 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ +1 ms] #14 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ +1 ms] #15 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ +1 ms] #16 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #17 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> [ ] #18 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> [ ] #19 _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
> [ ] #20 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ +1 ms] #21 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ +1 ms] #22 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ +1 ms] #23 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ +1 ms] #24 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ +1 ms] #25 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #26 Future.wait. (dart:async/future.dart:402:22)
> [ +1 ms] #27 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ ] #28 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ ] #29 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #30 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ ] #31 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ +1 ms] #32 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #33 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> [ ] #34 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> [ ] #35 _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
> [ ] #36 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ ] #37 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ ] #38 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #39 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ ] #40 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ ] #41 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #42 Future.wait. (dart:async/future.dart:402:22)
> [ ] #43 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ ] #44 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ +1 ms] #45 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #46 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ ] #47 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ ] #48 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #49 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> [ ] #50 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> [ ] #51 _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
> [ +1 ms] #52 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ +1 ms] #53 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ +1 ms] #54 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #55 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ ] #56 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ ] #57 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #58 Future.wait. (dart:async/future.dart:402:22)
> [ ] #59 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ ] #60 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ ] #61 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #62 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ ] #63 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ ] #64 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ +1 ms] #65 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> [ ] #66 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> [ ] #67 _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
> [ ] #68 _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
> [ ] #69 _rootRunBinary (dart:async/zone.dart:1204:38)
> [ ] #70 _CustomZone.runBinary (dart:async/zone.dart:1093:19)
> [ ] #71 _FutureListener.handleError (dart:async/future_impl.dart:155:20)
> [ ] #72 Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
> [ ] #73 Future._propagateToListeners (dart:async/future_impl.dart:715:24)
> [ ] #74 Future._completeError (dart:async/future_impl.dart:534:5)
> [ ] #75 _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
> [ ] #76 KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart)
> [ ] #77 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ +1 ms] #78 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ ] #79 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #80 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ ] #81 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ ] #82 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ ] #83 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> [ ] #84 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> [ +2 ms] #85 KernelCompiler.compile (package:flutter_tools/src/compile.dart)
> [ +3 ms] #86 _rootRunUnary (dart:async/zone.dart:1192:38)
> [ ] #87 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> [ ] #88 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> [ ] #89 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> [ +1 ms] #90 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> [ ] #91 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> [ +1 ms] #92 Future._asyncComplete. (dart:async/future_impl.dart:556:7)
> [ +1 ms] #93 _rootRun (dart:async/zone.dart:1184:13)
> [ +1 ms] #94 _CustomZone.run (dart:async/zone.dart:1077:19)
> [ ] #95 _CustomZone.runGuarded (dart:async/zone.dart:979:7)
> [ ] #96 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:1019:23)
> [ ] #97 _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
> [ +1 ms] #98 _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
> [ ] #99 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
> [ ] #100 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
> [ +1 ms] > Task :app:compileFlutterBuildRelease FAILED
> [ +16 ms] FAILURE: Build failed with an exception.
> [ +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> [ ] Use '--warning-mode all' to show the individual deprecation warnings.
> [ +1 ms] See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings
> [ +1 ms] 1 actionable task: 1 executed
> [ ] * Where:
> [ ] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 840
> [ ] * What went wrong:
> [ ] Execution failed for task ':app:compileFlutterBuildRelease'.
> [ ] > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> [ ] * Try:
> [ ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> [ ] * Get more help at https://help.gradle.org
> [ ] BUILD FAILED in 2m 22s
> [ +373 ms] Running Gradle task 'assembleRelease'... (completed in 142.9s, longer than expected)
> [ +5 ms] "flutter apk" took 1,43,628ms.
> Gradle task assembleRelease failed with exit code 1

I have the same issue. No Solution found yet.

**Comment by vanlalruata** [comment]
I had solved the problems by following below step:

1. flutter clean
2. flutter downgrade 1.6.3     or (1.6.6)
3. flutter channel stable
4. flutter upgrade

And try to run it once again.

flutter run   

I assume that you are running emulator already at the same time.
