### ISSUE TITLE
[WebView] Provide a way to set cookies

### ISSUE THREAD

**Issue by amourinho** [flutter/flutter#27597]
I attempted to set cookies with the `evaluateJavascript` function, but inspecting the webview from Google chrome shows that neither the cookie or sessionStorage item has been set.

The application has a login screen, which communicates with the server and receives a authentication token which we (in our current native applications) push to the webviews as a cookie; as our web portal applications use cookie based authentication. Some newer apps use sessionStorage, but that's another issue.

It would be nice to have this feature implemented.

Below is a the code used to display the webview in my application.
```dart
WebView(
          initialUrl: model.getUser.landingPage,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController wvc) {
            wvc.evaluateJavascript('document.cookie = "SESSION-${model.getUser.client}=${model.getUser.token}"; path=/');
            wvc.evaluateJavascript('sessionStorage.setItem("${model.getUser.client}_live_token", "${model.getUser.token}")');
          },
        )
```

**Comment by kangwang1988** [comment]
cc @cyanglaz

**Comment by cyanglaz** [comment]
@amirh

**Comment by cnlpj** [comment]
when the session is http-only； “evaluateJavascript('document.cookie = "SESSION-${model.getUser.client}=${model.getUser.token}"; path=/');” it do not work

**Comment by cnlpj** [comment]
when the cookie is http-only； “evaluateJavascript('document.cookie = "SESSION-${model.getUser.client}=${model.getUser.token}"; path=/');” it do not work

**Comment by jiechic** [comment]
CookieManager can be not in webview_flutter

see https://github.com/v7lin/fake_cookie_manager

**Comment by wbingz0719** [comment]
Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by cnlpj** [comment]
very sorry! I didn't solve it, but I didn't use cookies; I used the token to solve it, and I took the token every time I requested it.


------------------ 原始邮件 ------------------
发件人: "wbingz0719"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午2:51
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "lpj_qq"<707673970@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [flutter/flutter] [WebView] Provide webview_flutter a way to setcookies (#27597)




Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by wbingz0719** [comment]
I'm a flutter novice. How to set token?






------------------ 原始邮件 ------------------
发件人: "cnlpj"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午3:14
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "上善若水"<545928499@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [flutter/flutter] [WebView] Provide webview_flutter a way to setcookies (#27597)



very sorry! I didn't solve it, but I didn't use cookies; I used the token to solve it, and I took the token every time I requested it. 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "wbingz0719"<notifications@github.com>; 
 发送时间: 2019年10月11日(星期五) 下午2:51 
 收件人: "flutter/flutter"<flutter@noreply.github.com>; 
 抄送: "lpj_qq"<707673970@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [flutter/flutter] [WebView] Provide webview_flutter a way to setcookies (#27597) 
 
 
 
 
 Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by VadimOsovsky** [comment]
Failed to set the 'cookie' property on 'Document': Access is denied for this document."

**Comment by bingzhao0719** [comment]
Is there no official solution to this problem？

**Comment by ManuLpz4** [comment]
I have the same problem, I want to keep the session in WebView like Chrome web apps :(

**Comment by dylan-dinh** [comment]
You can use this plugin : https://pub.flutter-io.cn/packages/flutter_webview_plugin

It worked for myself, I refreshed my token and set them like that (using same function as @amourinho) : 
```
flutterWebViewPlugin
            .evalJavascript('document.cookie = "accessToken=$accesToken"')
```
It didn't work when I tried to set 2 tokens in the same `evalJavascript()` function so just call it twice or any times you want with the different token you want to set.

How to check your tokens on the WebView of a emulator or physical device : https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by wawoon** [comment]
If you are going to set cookies to your website, I find a workaround.
In short, define `setCookie` function in your website's `window` object, and call this `setCookie` function from dart.

Your website html
```
<head>
  <script>
    function setCookie(cookieStr) {
      document.cookie = cookieStr;
    }
  </script>
</head>
```

Flutter code
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class BrowserPage extends StatefulWidget {
  BrowserPage({ Key key, this.url }) : super(key: key);
  final String url;

  BrowserPageState createState() => BrowserPageState();
}

class BrowserPageState extends State<BrowserPage> {
  String url = "";
  String title = "Browser";
  WebViewController _wvc;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Text(title)
      ),
      body: WebView(
        initialUrl: widget.url,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController wvc) {
          this._wvc = wvc;
        },
        onPageFinished: (_) {
          _wvc.evaluateJavascript('setCookie("in_app=true; path=/");');
        },
      ),
    );
  }
}
```

**Comment by deepakrajv** [comment]
Check this answer [https://stackoverflow.com/questions/57751391/how-to-set-cookies-in-webview-flutter/60389501#60389501](url)

**Comment by teejayhh** [comment]
@wawoon I tested this and indeed this works. As of now the webview is not usable without being able to set cookies on the target url. This is something the native components (ios, android) definitely support in one way or another.

**Comment by teejayhh** [comment]
At anyone who needs this features and got stuck on the official webview, here is webview which has this inbuild and much more -> https://github.com/pichillilorenzo/flutter_inappwebview

**Comment by wbingz0719** [comment]
Aren't the authorities going to come up with a solution? The project is about to abort because of this problem

**Comment by wawoon** [comment]
I tried `flutter_inappwebview` and `flutter_webview_plugin` to set cookies, but they couldn't execute the my target website properly. So I had to use this `flutter_webview` instead.

I believe that there is no way to set cookies to any websites while using this `flutter_webview` plugin. In this case, we should use 3rd party plugins like `flutter_inappwebview` and `flutter_webview_plugin`.

**Comment by teejayhh** [comment]
`flutter_inappwebview`  works 100% just use the `CookieManager` to set the cookie. @wawoon

**Comment by wbingz0719** [comment]
> `flutter_inappwebview` works 100% just use the `CookieManager` to set the cookie, dont try to set them in the headers object. @wawoon

Could you tell me if this method works in IOS？

**Comment by wbingz0719** [comment]
> I tried `flutter_inappwebview` and `flutter_webview_plugin` to set cookies, but they couldn't execute my target website properly. So I had to use this `webview_flutter` instead.
> 
> I believe that there is no way to set cookies to any websites while using this `webview_flutter` plugin. In this case, we should use 3rd party plugins like `flutter_inappwebview` and `flutter_webview_plugin`.

My English is not very good. I don't understand what you are trying to express. Do you mean these plugins can't solve the cookie problem？

**Comment by wawoon** [comment]
Sorry, what I mean is that:

- both of `flutter_inappwebview` and `flutter_webview_plugin` could set cookies properly.
- however, they doesn't render my website. It's another problem.
  - issues
    -  `flutter_inappwebview `: it doesn't start JS on my website.
    -  `flutter_webview_plugin`: it starts JS, but it doesn't finish rendering.
  - my website is
    - created by react, typescript.
    - it is createdd for internal use, so I couldn't share url

**Comment by wbingz0719** [comment]
> Sorry, what I mean is that:
> 
> * both of `flutter_inappwebview` and `flutter_webview_plugin` could set cookies properly.
> * however, they didn't render my website. It's another problem.
>   
>   * issues
>     
>     * `flutter_inappwebview `: it doesn't start JS on my website.
>     * `flutter_webview_plugin`: it starts JS, but it doesn't finish rendering.
>   * my website is
>     
>     * created by react, typescript.
>     * it is created for internal use, so I couldn't share url

How can I set the cookie through the flutter_inappwebview? Can you show me the code?

**Comment by dylan-dinh** [comment]
> You can use this plugin : https://pub.flutter-io.cn/packages/flutter_webview_plugin
> 
> It worked for myself, I refreshed my token and set them like that (using same function as @amourinho) :
> 
> ```
> flutterWebViewPlugin
>             .evalJavascript('document.cookie = "accessToken=$accesToken"')
> ```
> 
> It didn't work when I tried to set 2 tokens in the same `evalJavascript()` function so just call it twice or any times you want with the different token you want to set.
> 
> How to check your cookies on the WebView of a emulator or physical device : https://developers.google.com/web/tools/chrome-devtools/remote-debugging

this is working tho guys :)

**Comment by wbingz0719** [comment]
> `flutter_inappwebview` works 100% just use the `CookieManager` to set the cookie, dont try to set them in the headers object. @wawoon

but CookieManager is available from iOS 11.0+

**Comment by nemoryoliver** [comment]
Still waiting for a way to set cookies properly

**Comment by MeherBa** [comment]
Still waiting for a new method to set cookies properly too

**Comment by Dhamarice** [comment]
this worked for me for webview_flutter plugin:

 onPageStarted: (_){
                SampleMenu(_controller.future).clearCookies(_myController, context);
                _myController.evaluateJavascript('document.cookie = "PHPSESSID=$sessionId; path=/";');
                _myController.evaluateJavascript('document.cookie = "sess_salt=$see_salt; path=/";');
              },

**Comment by fryette** [comment]
Implemented library to do it, now you can use lib together with different webview_plugins
https://pub.dev/packages/webview_cookie_manager

**Comment by rodruiz** [comment]
> Implemented library to do it, now you can use WebviewCookieManager with flutter_webview
> https://pub.dev/packages/webview_cookie_manager

Confirming this package works.

**Comment by shinriyo** [comment]
can you fix it?

**Comment by rrarey02** [comment]
Am I understanding this correctly? Flutter 1.22 has a "production ready" webview implementation, but still can't fully handle cookies?

**Comment by harsh2338** [comment]
> Implemented library to do it, now you can use WebviewCookieManager with flutter_webview
> https://pub.dev/packages/webview_cookie_manager

@fryette 
The cookies can be set only by action once the page is set. Like my clicking a button. The page does not load with the cookies by default. It's there a solution for that?

**Comment by fryette** [comment]
@harsh2338 This package provides a posibility to set cookies before you start opening the page via webivew.

For example, you need to open a profile page of some site. You can set cookies with authToken and the page will be opened. Without setting a cookie before -> you will see a login page.

**Comment by wonsuyon** [comment]
> @fryette
> The cookies can be set only by action once the page is set. Like my clicking a button. The page does not load with the cookies by default. It's there a solution for that?

```
    return WebView(
      // initialUrl: '',
      onWebViewCreated: (WebViewController controller) async {
        await cookieManager.setCookies([
          Cookie('JSESSIONID', '67862FB61104EA5CF4D431F87C.............')
            ..domain = 'www.example.com'
            ..expires = DateTime.now().add(Duration(days: ...))
            ..httpOnly = false
        ]);

        controller.loadUrl('https://www.example.com/member/memberInfo.do');
      },
```

It works.

**Comment by tazik561** [comment]
This is a problem because WebviewCookieManager just work on IOS 11+ !!! If user ios be 10, It is not work. What can I do? I want to set cookie on Android and Ios ?

**Comment by tazik561** [comment]
> `flutter_inappwebview` works 100% just use the `CookieManager` to set the cookie, dont try to set them in the headers object. @wawoon

 just work on IOS 11+ !!! If user ios be 10, It is not work. What can I do? I want to set cookie on Android and Ios ?

**Comment by rekire** [comment]
When you use secure cookies (aka https only) then you cannot use WebviewCookieManager at least on Android 10 since it will almost silently fail. There is just a hint in the logcat as mentioned in the bug above.

Just as reference I opened a bug there too: [Secure cookies cannot be set on Android 10](https://github.com/fryette/webview_cookie_manager/issues/52)

Using JavaScript for injecting cookies is out of my view no workaround too. You cannot set http only cookies with this method.
