### ISSUE TITLE
Flutter and google_sign_in 4.0.0 plugin: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)

### ISSUE THREAD

**Issue by bbozhidarov** [flutter/flutter#27599]
The dialog (Google form) for the credentials is opened successfully, but after I fill my credentials I'm getting this error. I followed the instructions from [here](https://pub.dartlang.org/packages/google_sign_in). Created a Firebase project, enabled the Google Drive API (that's what I need for now) from the Google APIs Console.

The code throwing the exception:

```dart
final GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: [
    'https://www.googleapis.com/auth/drive',
  ],
);

await _googleSignIn.signIn();
```

That's the stack trace:

```
E/flutter ( 5068): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5068): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter ( 5068): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 5068): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter ( 5068): <asynchronous suspension>
E/flutter ( 5068): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:226:58)
E/flutter ( 5068): <asynchronous suspension>
E/flutter ( 5068): #3      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:268:20)
E/flutter ( 5068): #4      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:339:48)
E/flutter ( 5068): #5      ThatsMyComponentState.theSignInFuction.<anonymous closure> (package:my_app/widgets/my_file.dart:666:45)
E/flutter ( 5068): <asynchronous suspension>
E/flutter ( 5068): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 5068): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 5068): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 5068): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 5068): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter ( 5068): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 5068): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
E/flutter ( 5068): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 5068): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 5068): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 5068): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 5068): #17     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5068): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

The version of the google_sign_in plugin is 4.0.0.

That's the output of **flutter doctot -v**:

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.253], locale en-US)
• Flutter version 1.0.0 at C:\src\flutter-0.7.3\flutter
• Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
• Engine revision 7375a0f414
• Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
• Android SDK at C:\Users\myuser\AppData\Local\Android\Sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• ANDROID_HOME = C:\Users\myuser\AppData\Local\Android\Sdk
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[√] Android Studio (version 3.3)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 32.0.1
• Dart plugin version 182.5124
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
• IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6
X Flutter plugin not installed; this adds Flutter specific functionality.
X Dart plugin not installed; this adds Dart specific functionality.
• For information about installing plugins, see
  https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code, 64-bit edition (version 1.30.2)
• VS Code at C:\Program Files\Microsoft VS Code
• Flutter extension not installed; install from
  https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

Any help will be much appreciated. Thanks!

**Comment by zoechi** [comment]
You need to pass the authHeaders like explained in https://stackoverflow.com/questions/48477625/how-to-use-google-api-in-flutter/48485898#48485898

**Comment by bbozhidarov** [comment]
@zoechi But where do I get the headers from if I cannot sign in?

`await _googleSignIn.signIn();`

That's the line throwing the exception. I input my credentials in the form and after that when the screen returns to my app, it throws the error.

I'm trying this on emulator by the way - Nexus 5X API 27 with Google Play services enabled and updated.

**Comment by bbozhidarov** [comment]
In **android/app/build.gradle** I changed the dependencies from **com.android.tools.build:gradle:3.1.3**/**com.google.gms:google-services:3.2.1** to **com.android.tools.build:gradle:3.2.1**/**com.google.gms:google-services:4.2.0**. And it worked.

**Comment by nemoryoliver** [comment]
> **com.android.tools.build:gradle:3.2.1**/**com.google.gms:google-services:4.2.0**



> In **android/app/build.gradle** I changed the dependencies from **com.android.tools.build:gradle:3.1.3**/**com.google.gms:google-services:3.2.1** to **com.android.tools.build:gradle:3.2.1**/**com.google.gms:google-services:4.2.0**. And it worked.

you mean from android/build.gradle not from android/app/build.gradle?

**Comment by bbozhidarov** [comment]
@nemoryoliver Sorry, my bad. Yes, it's **android/build.gradle**.

**Comment by nemoryoliver** [comment]
> @nemoryoliver Sorry, my bad. Yes, it's **android/build.gradle**.

No problem. did you try yours in release mode? mine only occurs when run in release mode.

**Comment by bbozhidarov** [comment]
I haven't yet. I've tested only in debug.

**Comment by nemoryoliver** [comment]
> I haven't yet. I've tested only in debug.

I see.. Maybe it's the same as mine. I don't get this error on debug, but on release it occurs.

**Comment by tolotrasamuel** [comment]
I had the same issue just now. This might happens if you are running on debug and you did not register a sha fingerprint in firebase see here: https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google/54696963#54696963

**Comment by Livinglist** [comment]
> > I haven't yet. I've tested only in debug.
> 
> I see.. Maybe it's the same as mine. I don't get this error on debug, but on release it occurs.

I encountered the issue same as yours. The `PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null) ` only comes up in release mode. However, this issue does not always come up, sometimes the sign-in is successful, I'm guessing that this is a server-side issue.

**Comment by Livinglist** [comment]
> > I haven't yet. I've tested only in debug.
> 
> I see.. Maybe it's the same as mine. I don't get this error on debug, but on release it occurs.

I seem to find the solution. The problem for me is that I only have a debug SHA1 in the Firebase. For the release mode, you need a release SHA1 which you can get after you published your app onto Google Play. Everything works perfectly fine after I added to firebase two SHA1 from `Upload certificate` and `App signing certificate` sections in Google Play Console.

For details, see https://stackoverflow.com/questions/53630123/flutter-generate-release-sha1-fingerprint

**Comment by srini85** [comment]
> I had the same issue just now. This might happens if you are running on debug and you did not register a sha fingerprint in firebase see here: https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google/54696963#54696963

Thanks! that did the trick for me. Had to add both the SHA1 and SHA256 Keys for the sign in to work.

**Comment by stevenspiel** [comment]
I was struggling with this for a few days. I was only running into this issue on release apps. Tried everything listed here, without any luck. I finally found this answer that helped me: 

https://stackoverflow.com/a/47620437/1411004

Basically, I just needed to go to Firebase and link to the Google Play store.

<img width="1413" alt="Screen Shot 2019-03-14 at 5 57 46 PM" src="https://user-images.githubusercontent.com/1630091/54394309-e26d0880-4682-11e9-9283-cb77db1594f4.png">

**Comment by vinayjaiswal** [comment]
Add SHA1 and SHA256 on firebase console

**Comment by dolanmiu** [comment]
> Add SHA1 and SHA256 on firebase console, It has resolved in android.


Yes I had to add BOTH `SHA1` and `SHA256` for it to work. Adding a single one wouldn't work for me

Thanks!

**Comment by bradmuzza** [comment]
when I change  classpath 'com.android.tools.build:gradle:3.3.1' to classpath 'com.android.tools.build:gradle:3.2.1' i get this build error 
 Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.2) classpath. You should manually set the same version via DependencyResolution

**Comment by waldandrade** [comment]
God! Just add the suport email to the app. That's a severe doc mistake!

**Comment by Pankaj-Sakariya** [comment]
> > Add SHA1 and SHA256 on firebase console, It has resolved in android.
> 
> Yes I had to add **BOTH** `SHA1` and `SHA256` for it to work. Adding a single one wouldn't work for me
> 
> Thanks!

In my case, I've added SHA1 Only and it works for me.

**Comment by thejacer87** [comment]
adding both sha1 and sha256 worked for me for whats it's worth. sha1 ONLY wasnt enough

**Comment by elliottben** [comment]
Please note that there are new OAuth consent forms that need to be filled out as detailed midway in the following article:

https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed

**Comment by bubunyo** [comment]
for anybody who gets here and is still not able to solve this issue here is what I found out:
Platform Exception, ApiException 10 has something to do with SHA certificate fingerprints. For me, this issue happened because I added firebase auth to my app before I generated the release. So I had added the SHA1 fingerprint for the debug version and I didn't generate the fingerprint for when I created the release key. Once I did that it worked.

To create the release fingerprints follow this(the first part): https://developers.google.com/android/guides/client-auth 

if you followed [this](https://flutter.dev/docs/deployment/android) to sign you up. the command you will have to run will most likely be `keytool -list -v -alias key -keystore ~/key.jks`. Bear in mind the password is the password you used to create the keystore in the first place.

**Comment by DhruvSingla007** [comment]
Try this, it will surely help :)
https://medium.com/flutter-community/flutter-implementing-google-sign-in-71888bca24ed

**Comment by ThembaniFubesi** [comment]
@DhruvSingla007 Thanks for recommending this article. It really helped.

I was missing the `OAuth consent screen` step.

**Comment by srinivasPaidisetti** [comment]
Yes I had to add BOTH SHA1 and SHA256 for it to work. Adding a single one wouldn't work for me

Thanks!

**Comment by sachinPramodya** [comment]
make sure you have added

 dependencies {
    classpath 'com.google.gms:google-services:4.2.0'
}
in android/build.gradle and

apply plugin: 'com.google.gms.google-services'
in android/app/build.gradle. Also, make sure applicationId in android/app/build.gradle is the same as your package name in AndroidManifest.xml(You may forget to change applicationId after changing package name sometimes). This applicatioonId or package name in manifest file should be the name of your android package name in firebase app.

**Comment by nemoryoliver** [comment]
What if we want to use a different FirebaseApp for google_sign_in programmatically (like the FirebaseOptions)? Is there a way?

**Comment by dcchristopher** [comment]
For those just playing around with Flutter and Google OAuth (regardless of Firebase, which you really don't need), @sachinPramodya already pointed out something I found too late (and was about to post here): the package name has to match. Despite setting the package name initially correctly in Flutter, it didn't propagate to the rest of the places in the project (iOS plist, Android Manifest, etc.). With just the debug SHA-1 (for emulator-only use, of course) and the correct package name, I was able to get off the ground. Good luck!

**Comment by nemoryoliver** [comment]
> For those just playing around with Flutter and Google OAuth (regardless of Firebase, which you really don't need), @sachinPramodya already pointed out something I found too late (and was about to post here): the package name has to match. Despite setting the package name initially correctly in Flutter, it didn't propagate to the rest of the places in the project (iOS plist, Android Manifest, etc.). With just the debug SHA-1 (for emulator-only use, of course) and the correct package name, I was able to get off the ground. Good luck!

How exactly you did it? Can you share?

**Comment by dcchristopher** [comment]
> > For those just playing around with Flutter and Google OAuth (regardless of Firebase, which you really don't need), @sachinPramodya already pointed out something I found too late (and was about to post here): the package name has to match. Despite setting the package name initially correctly in Flutter, it didn't propagate to the rest of the places in the project (iOS plist, Android Manifest, etc.). With just the debug SHA-1 (for emulator-only use, of course) and the correct package name, I was able to get off the ground. Good luck!
> 
> How exactly you did it? Can you share?

The default flutter package name is "com.example.YOUR_PROJECT_NAME". You just need to set that to the package name that you want going forward (assume production namespace or reverse web URL) and make sure it matches what is in Google Developers Console -> APIs & Services -> Credentials -> [your platform OAuth client ID entry]. If using Firebase, there's an equivalent location (they actually see each other's data because it wouldn't let me populate the same SHA1 in both places): Firebase Console -> [your project] -> Settings (gear icon) -> (General tab) -> [your platform app, e.g. "Android apps"] -> Package name.

**Comment by dcchristopher** [comment]
So, another tidbit of information for folks who may go down this path. I ended up integrating with AWS Cognito and I had to switch to Firebase. Google OAuth only gave me an auth token, not an identity token. I ended up removing the SHA-1 fingerprint from Google's Developer Console (effectively deleting the API key and all that) and adding it to Firebase Console. You'll have to download the google-services.json, add the dependency to google-services (Android), etc.

**Comment by benjaminhorner** [comment]
Non of the above worked for me. I found this thread that REALLY helped me: [https://stackoverflow.com/a/56091158/1897596](url)

**Comment by elliott-io** [comment]
If you are using **Internal App Sharing** to test Flutter builds on actual Android devices (like I am), there is **another App Signing certificate fingerprint** you need to add.

Find it using the left navigation of Google Play Console go to: **Developer Tools -> Internal App Sharing**

Select the **App Certificate** tab. Should look something like this:

[Google Play - Internal App Sharing - Certificate][1]

Copy the SHA1 key for your Internal test certificate and add it to the Firebase Console -> Project Settings -> [your Android app] -> SHA certificate fingerprints (use the button to Add fingerprint)

Download your updated google-services.json and update/add it in your android/app folder of your project.

This works with new users and existing users. I built the an appbundle (not APK) using `flutter build appbundle`

The above solution isn't documented anywhere by Google and I have not seen this solution elsewhere in the Flutter community. I came across this solution while poking around in the Google Play console after trying dozens of suggested fixes that didn't work for me.


  [1]: https://i.stack.imgur.com/1XaXr.png

**Comment by AirborneEagle** [comment]
After hours of trying various things. I found my solution:
Using the steps listed here:
https://stackoverflow.com/a/34223470/10575896
1. Open Android Studio
2. Open your Project
3. Click on Gradle (From Right Side Panel, you will see Gradle Bar)
4. Click on Refresh (Click on Refresh from Gradle Bar, you will see List Gradle scripts of your Project)
5. Click on Your Project (Your Project Name form List (root))
6. Click on Tasks
7. Click on Android
8. Double Click on signingReport (You will get SHA1 and MD5 in Run Bar(Sometimes it will be in Gradle Console))

The console will print out the SHA keys for both debug and release.  I had added the debug keys to firebase, but i had not added the release keys.

I simply added the SHA1 and SHA256 keys to firebase, and I was good to go.

**Comment by okpatil4u** [comment]
Yes @AirborneEagle, your solution worked for me. Thank you !

**Comment by JanMate** [comment]
> > > I haven't yet. I've tested only in debug.
> > 
> > 
> > I see.. Maybe it's the same as mine. I don't get this error on debug, but on release it occurs.
> 
> I seem to find the solution. The problem for me is that I only have a debug SHA1 in the Firebase. For the release mode, you need a release SHA1 which you can get after you published your app onto Google Play. Everything works perfectly fine after I added to firebase two SHA1 from `Upload certificate` and `App signing certificate` sections in Google Play Console.
> 
> Remember to update your `google-services.json`
> 
> For details, see https://stackoverflow.com/questions/53630123/flutter-generate-release-sha1-fingerprint

Thanks a lot for hint! I have forgotten to generate release private key and add SHA1 key and this really helped me!

**Comment by hstevemcdonald** [comment]
@AirborneEagle - After 3 days of trying to figure this out, stumbled upon your instructions and it worked great.  Thank you!

**Comment by GaetanLhoest** [comment]
> If you are using **Internal App Sharing** to test Flutter builds on actual Android devices (like I am), there is **another App Signing certificate fingerprint** you need to add.
> 
> Find it using the left navigation of Google Play Console go to: **Developer Tools -> Internal App Sharing**
> 
> Select the **App Certificate** tab. Should look something like this:
> 
> [Google Play - Internal App Sharing - Certificate](https://i.stack.imgur.com/1XaXr.png)
> 
> Copy the SHA1 key for your Internal test certificate and add it to the Firebase Console -> Project Settings -> [your Android app] -> SHA certificate fingerprints (use the button to Add fingerprint)
> 
> Download your updated google-services.json and update/add it in your android/app folder of your project.
> 
> This works with new users and existing users. I built the an appbundle (not APK) using `flutter build appbundle`
> 
> The above solution isn't documented anywhere by Google and I have not seen this solution elsewhere in the Flutter community. I came across this solution while poking around in the Google Play console after trying dozens of suggested fixes that didn't work for me.

You saved me, thank you so much

**Comment by marchacio** [comment]
After some days, i found my problem:

First, i wrote in /android/build.grandle (below code is not correct)
```
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.google.gms:google-services:4.3.3'
        ...
    }
}
```

After, i changed the "classpath" line to: `classpath 'com.google.gms:google-services:4.2.0'`

I hope this could help everyone
