### ISSUE TITLE
Circle image problem

### ISSUE THREAD

**Issue by amervelic** [flutter/flutter#27590]
I try "zillion" combination , but fail every time.

**Comment by amervelic** [comment]
I try CircleAvatar with backgroundImage property - fail , ClipRRect - fail, ClipOval - fail

**Comment by Kartik1607** [comment]
Could you paste some code which you have tried. Also what are you trying to achieve?

**Comment by amervelic** [comment]
[https://github.com/amervelic/avatar_demo](url)

**Comment by amervelic** [comment]
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/amervelic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (2 available)
    • HTC Desire EYE • FA4CJY801847                         • android-arm • Android 6.0.1 (API 23)
    • iPhone 6s      • 9298E5D8-B14E-4A5A-B9FA-33E6810D50A2 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

**Comment by amervelic** [comment]
[source](https://github.com/amervelic/avatar_demo)

**Comment by Kartik1607** [comment]
Please share the issue you are having. Current output

![image](https://user-images.githubusercontent.com/17377741/52349462-9a880f80-2a4c-11e9-8fdc-63420e1daaa3.png)

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by amervelic** [comment]
The problem is only on the Android emulator. On the real android device the problem did not appear.
![prototype](https://i.imgur.com/KwNeP95.png)

**Comment by Kartik1607** [comment]
What emulator configuration are you using?
