### ISSUE TITLE
Flutter application not running

### ISSUE THREAD

**Issue by demiscology** [flutter/flutter#27605]
I just download the android studio and installed the dart and flutter plugin, but while trying to run the program to test the host reload, my program runs into an error.
![screenshot 23](https://user-images.githubusercontent.com/39691155/52362354-b1c10000-2a40-11e9-827f-da6d87245e2b.png)

**Comment by wouterhardeman** [comment]
You have not yet accepted all Android licenses.

Try running `flutter doctor --android-licenses`

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
