### ISSUE TITLE
Request to preserve Timeline event names

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#27609]
For the [DevTools](https://github.com/flutter/devtools) web tooling application, we are depending on the following timeline event names:
"MessageLoop::RunExpiredTasks"
"VSYNC"
"Engine::BeginFrame"
"GPURasterizer::Draw"
"PipelineItem"
"PipelineConsume"

Changing these names will break our Timeline code, so if we can avoid changing them that would be ideal. However, if for some reason the event names do need to change, please reach out and we can make the necessary changes to our tool. Thank you.

@chinmaygarde

**Comment by zoechi** [comment]
devtools/#235 was merged. Did this PR fix this issue?

**Comment by kenzieschmoll** [comment]
This is more of a long standing request. Our tool now depends on these event names being stable.

**Comment by kenzieschmoll** [comment]
Would it be possible to add some comments in the code where these event names are defined? That would make it less likely that a change to these event names slips through the cracks.

**Comment by jmagman** [comment]
Could this be accomplished with tests that check the event names and a comment describing the dependency?
This issue alone hanging out open may not be enough visibility to prevent the name change.

**Comment by jmagman** [comment]
Removing tool label, the TRACE_EVENT0 strings live in the engine.

**Comment by kenzieschmoll** [comment]
Revisiting this issue. Could we get a test that verifies these event names are stable? Looks like the VSYNC event has now changed to VsyncProcessCallback and broke our Flutter frame detection logic in DevTools.

**Comment by kenzieschmoll** [comment]
Our timeline code was broken again by an event name change from the framework. Can we get a test to prevent name changes or at least notify our team in the future? cc @chinmaygarde @iskakaushik 

This time it had to do with removing / renaming the following two events: 
"PipelineItem"
"PipelineConsume"

**Comment by iskakaushik** [comment]
@kenzieschmoll what does devtools use these events for? I am wondering if we can expose these as a flutter framework or engine APIs.

**Comment by kenzieschmoll** [comment]
We use the "PipelineItem" flow events to determine the start of the frame (the start of the UI portion) and end of the frame (the end of the Raster portion).

We use "PipelineConsume" to determine whether a group of events on the raster thread belongs to a flutter frame.

We use "Engine::BeginFrame" to determine whether a group of events on the UI thread belong to a flutter frame.

We use "Vsync" (old) and "VsyncProcessCallback" (new) to determine which thread is the UI thread.

We use "GPURasterizer::Draw" to determine which thread is the Raster thread.

It comes down to this. We need to know:
- when a frame starts
- when a frame ends
- which set of UI timeline events belong to a frame
- which set of Raster timeline events belong to a frame
- the UI thread ID
- the Raster thread ID

Right now we gather all UI events that we know belong to flutter frames (based on the presence of the "Engine::BeginFrame" event), and we gather all Raster events that we know belong to flutter frames (based on the presence of the "PipelineConsume" event). Then for every pair of start/end PipelineItem events, we assign a single UI event group and Raster event group (based on the timestamps) to form a single FlutterFrame for use in the DevTools timeline.

**Comment by iskakaushik** [comment]
> * when a frame starts
> * when a frame ends

For these we could probably add these to the [FrameTiming](https://api.flutter.dev/flutter/dart-ui/FrameTiming-class.html) apis.

> * which set of UI timeline events belong to a frame
> * which set of Raster timeline events belong to a frame

Once we have the timestamps are available through the FrameTiming's api, would it be possible to associate these events based on the time stamps?

> * the UI thread ID
> * the Raster thread ID

I am not sure if they are exposed to the Framework. @chinmaygarde for thoughts on the best way to expose them. Maybe adding a trace-event when we create the task runners. It doesn't seem elegant.

**Comment by kenzieschmoll** [comment]
> > which set of UI timeline events belong to a frame
> > which set of Raster timeline events belong to a frame
> 
> Once we have the timestamps are available through the FrameTiming's api, would it be possible to associate these events based on the time stamps?

Not exactly because there are more events that come on the UI / Raster threads than the ones that belong to a flutter frame. If we have several synchronous events coming over the UI thread for example, we need to be able to show which ones belong to the actual dart portion of a flutter frame and which are just "other" events on the thread.

**Comment by iskakaushik** [comment]
> If we have several synchronous events coming over the UI thread for example, we need to be able to show which ones belong to the actual dart portion of a flutter frame and which are just "other" events on the thread.

Is this a problem only with the UI thread? Do you have any examples for the "other" trace events on the thread. Given that we control the trace events that get posted on any of the engine controlled threads, i'm surprised that there are events that the engine specifically doesn't record.

**Comment by kenzieschmoll** [comment]
You are correct. This is only an issue for the UI thread. It appears that all events on the Raster thread are ones specific to flutter frames.

**Comment by jonahwilliams** [comment]
Closing based on the assumption that this has been delt with via test coverage and/or frame timings. If we've broken it again, hopefully you'll file a new bug and we can go from there.
