### ISSUE TITLE
Hot reload should report a compiler error during reload as a failure in the flutter daemon

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#27618]
Currently, if you try a hot reload and an error is picked up in compilation, we go straight to a red screen of death.

We can know ahead of time if the reloaded code doesn't compile and alert that the hot reload failed as well.

**Comment by jonahwilliams** [comment]
We now stop all hot reloads on compilation failures: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devfs.dart#L498
