### ISSUE TITLE
Flutter StreamBuilder Jerks on Scrolling Up

### ISSUE THREAD

**Issue by GraceWayDCDevelopment** [flutter/flutter#27611]
Essentially, the `StreamBuilder` works fine scrolling down, but when I scroll up, it jumps jerkily to the top.
Here's a video https://www.youtube.com/watch?v=SrW7Q4yDMjc

## Steps to Reproduce

// Code
```dart
return StreamBuilder<QuerySnapshot>(
        // Create a stream listening to the posts collection
        stream: widget.firestore
            .collection('posts')
            .orderBy('sequence', descending: false)
            .snapshots(),
        builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
          // When we don't have data yet (!...hasData), display the text "Loading..."
          if (!snapshot.hasData) return const Text('Loading...');
          final int messageCount = snapshot.data.documents.length;

          // When data is availible, load
          return new ListView.builder(
            itemCount: messageCount,
            addAutomaticKeepAlives: true,
            itemBuilder: (_, int index) {
              final DocumentSnapshot document = snapshot.data.documents[index];
              if (document["type"] == "memory")
                return MemoryVerseCard(
                    widget.firestore, int.parse(document["week"]));
              else if (document["type"] == "standard")
                return StandardCard(widget.firestore, document.documentID);
              else if (document["type"] == "text")
                return TextCard(widget.firestore, document.documentID);
              else if (document["type"] == "video")
                return VideoCard(widget.firestore, document.documentID);
              else if (document["type"] == "streaks")
                return StreaksCard(widget.firestore, false);
              else
                return Card(
                  // Database is incorrect
                  child: Center(
                    child: Text("[Missing sufficient information]"),
                  ),
                );
            },
          );
        },
      );
```
## Logs

There are no error logs or analysis issues whatsoever.
```
flutter doctor -v:
[✓] Flutter (Channel master, v1.2.1-pre.99, on Mac OS X 10.14.3 18D42, locale en-US)
    • Flutter version 1.2.1-pre.99 at /Users/nathan/flutter
    • Framework revision 7765dd4c3c (19 hours ago), 2019-02-06 08:48:14 +0800
    • Engine revision cc27cafb84
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 5823be65af)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nathan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[✓] Connected device (1 available)
    • Nathan’s iPhone • 7325ceb33c6fd2495af5c37c485fb8583ab977cd • ios • iOS 12.1.3

• No issues found!
```

**Comment by kangwang1988** [comment]
cc @liyuqian

**Comment by zoechi** [comment]
Can you reproduce without Firebase?

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce or in this case ideally a GitHub project including used example assets.

**Comment by GraceWayDCDevelopment** [comment]
Yes, it does still happen.  I believe it has something to do with Futures and Streams.  I replicated the model of Firebase locally with the attached code.

import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ListView Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'ListView Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  stream() async* {
    yield ObjectHasFuture();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: StreamBuilder(
            stream: stream(),
            builder: (BuildContext context, snapshot) {
              if (!snapshot.hasData) return const Text('Loading...');
              return ListView.builder(
                itemBuilder: (_, int index) {
                  return Card(
                    child: snapshot.data,
                  );
                },
              );
            }));
  }
}

class ObjectHasFuture extends StatelessWidget {
  data() async {
    await Future.delayed(Duration(seconds: Random().nextInt(2)));
    return Container(
      height: 250,
      color: Colors.green,
      child: Center(
        child: Text(Random().nextInt(10000).toString()),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: data(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return const Text("Loading");

          return snapshot.data;
        });
  }
}

**Comment by GraceWayDCDevelopment** [comment]
@zoechi Here's a video of it.  
https://youtu.be/_kqk9vjMtFY

If we can't determine where the problem lies from the example above, I can duplicate the Firebase setup and share the private GitHub repository.

**Comment by zoechi** [comment]
I don't think this is supposed to work this way. Collect the data from the stream outside of build and use this data in `build()`. Just because you work with a `Stream`, doesn't mean you should use `StreamBuilder` (similar with `FutureBuilder`).

**Comment by GraceWayDCDevelopment** [comment]
Okay, so use a Stateful Widget and fetch the data in initState?

Can I still listen for DB changes that way?

**Comment by zoechi** [comment]
What do you mean with "that way"? You can listen in `initState()` to the stream and update the local data whenever there are updates. Better than `initState()` would be to do that outside of widgets entirely. If a widget is removed and re-added `initState()` is executed again and all you get is the same problem less frequently.

If you need more details I'd suggest to ask in one of the other channels listed at http://flutter.io/support .

**Comment by GraceWayDCDevelopment** [comment]
Thanks.  I think I see where my code is going wrong now.

**Comment by joanpuigsanz** [comment]
I'm experiencing the same issue. @GraceWayDCDevelopment what did you do to fix it?

**Comment by CoreyCole** [comment]
@joanpuigsanz I found [this article](https://medium.com/saugo360/flutter-creating-a-listview-that-loads-one-page-at-a-time-c5c91b6fabd3#a358) on medium.
> The explanation of this behavior is a bit complicated: `ListView`, and `ScrollViews` in general, tend to dispose of the children that are not currently visible on the screen. When we try to scroll back to the child, the child is reinitialized from scratch. But in this case, our child is a `FutureBuilder`; re-initializing it creates a progress indicator again just for a part of a second, then creates the page once again. This confuses the scrolling mechanism, throwing us around in non-deterministic ways.

To solve this, you can either make sure the **height** of the "no data" state of your widget is the same as the height of your "loaded" widget. But, this is pretty impractical for most scenarios. An alternative is to have the ListViews children use the `AutomaticKeepAliveClientMixin` and set "wantKeepAlive" to true. You can get more info about this in the article I linked.

**Comment by Arthur-Kamau** [comment]
This might help.
In the list view set the property `physics` to `NeverScrollableScrollPhysics()`, then wrap your  `StreamBuilder` in `SingleChildScrollView`.
The list view will build but you will not be able to rebuild as its not scrollable the SingleChildScrollView will take care of the scrolling.
