### ISSUE TITLE
'flutter' tool doesn't lock its cache dir when updating

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2762]
If you run multiple copies of flutter simultaneously (e.g. because you're running it under `watch` in another window) and upgrade, all instances will try to download the new toolchain at once.

**Comment by Hixie** [comment]
...and it can result in really ugly inexplicable errors that can only be solved by cleaning the whole shebang and whose source is really unclear.

**Comment by Hixie** [comment]
On Linux we can use "flock".

**Comment by abarth** [comment]
shlock is a possibility on mac, but some random web site had bad things to say about it.

**Comment by Hixie** [comment]
Is `mkdir` atomic enough?

**Comment by abarth** [comment]
http://wiki.bash-hackers.org/howto/mutex seems positive on it.

**Comment by abarth** [comment]
Seems tricky if your shell script can terminate before removing the directory.

**Comment by Hixie** [comment]
I guess we can use flock on linux, and shlock on mac. Better than nothing.

**Comment by devoncarew** [comment]
We'd likely need to lock around:
- cache updates / update checks
- the update-packages call
