### ISSUE TITLE
Material TextField's cursor seems off

### ISSUE THREAD

**Issue by xster** [flutter/flutter#27626]
I think we got the CupertinoTextField right. Though the offset seems off for the Material TextField

![flutter_05](https://user-images.githubusercontent.com/156888/52384656-4886c000-2a33-11e9-89c8-9724e42fd213.png)

![flutter_02](https://user-images.githubusercontent.com/156888/52384663-4de40a80-2a33-11e9-9f45-0190cc413b2b.png)

cc @jslavitz

**Comment by HansMuller** [comment]
I'm looking into this. Apparently we (also) need more tests!

**Comment by xster** [comment]
We should add a golden for these

**Comment by HansMuller** [comment]
Part of the problem appears have been introduced in #24876: https://github.com/flutter/flutter/pull/24876/files#r254837712

That PR unconditionally introduced a "cursor offset" that was supposed to be iOS-specific.

![screenshot0](https://user-images.githubusercontent.com/1377460/52440859-08c3e500-2ad4-11e9-9334-b0feb24bf615.png)

Without the iOS-specific cursor offset:

![screenshot1](https://user-images.githubusercontent.com/1377460/52440867-0feaf300-2ad4-11e9-9a1a-6dfec1775bea.png)

The remaining misalignment between the cursor (aka the "caret") and the floating cursor has been around for a while. It's still wrong, but it's not new.

**Comment by HansMuller** [comment]
It turns out that we have tests to check for the text caret's X offset, but they were all changed to accommodate the bug - https://github.com/flutter/flutter/pull/24876/files#r254837712

**Comment by jslavitz** [comment]
I just realized that I somehow specified the material cursor offset as 2px instead of -2px. :/ I'll land something really quick to change that.
