### ISSUE TITLE
[Plugin]Add support for clearing cookies and cache in IOS 8 in webview plugin.

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#27624]

**Comment by zoechi** [comment]
Looks similar to #27321

**Comment by iskakaushik** [comment]
@zoechi We've added support for deleting cookies for Android and IOS version >= 9.0. This is to track request for IOS 8.

**Comment by jmagman** [comment]
iOS 8 is no longer supported, this will be closed by https://github.com/flutter/plugins/pull/4361, which makes the minimum version iOS 9.0.
