### ISSUE TITLE
Tab bar on on ios causing wrong CameraUpdate.newLatLngBounds

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#27631]
I am using map on both application. Currently there is not function to set boundary based on the all the relevant markers. So what I did I find the minimum lat,long and max lat,long of the marker. Then I run this function.
E.g.
```dart
 mapController.animateCamera(
      CameraUpdate.newLatLngBounds(
        LatLngBounds(
          southwest: LatLng(1.71266305, 100.40908813),
          northeast: LatLng(5.42847109, 103.44187164),
        ),
        0.0,
      ),
    );
```
What I notice on android it works fine. On ios when there is not tab bar in the app bar above it works fine. But the moment I add tab bar I get wrong lat long bound. How do I overcome this issue on ios specifically? 

Below is two screen shots without the tab bar
![without](https://user-images.githubusercontent.com/46325541/52400989-9f57cc80-2afb-11e9-875c-f4234b13f7b2.png)
with tab bar
![withtabbar](https://user-images.githubusercontent.com/46325541/52401018-b1d20600-2afb-11e9-98d3-4cbc2d2ac974.png)

What is the best workaround for temporary maybe I have to tweak and play the max and min lat long value for platform ios? But I think is not a good solution either.

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by newbieflutter** [comment]
Ok where should I provide the codes ? Here or some other repository?

**Comment by zoechi** [comment]
If it's minimal (as it should be) it shouldn't be a problem to just post it as comment. Otherwise please create a [Gist](https://gist.github.com) and post the link.
