### ISSUE TITLE
NestedScrollView/SliverAppBar - unwanted bottom margin

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#27636]
StackOverflow question: https://stackoverflow.com/questions/54553278/flutter-nestedscrollview-sliverappbar-unwanted-bottom-margin

To build appbar:

```dart
@override
  Widget build(BuildContext context) {
    var drawerOptions = <Widget>[];
    for (var i = 0; i < widget.drawerItems.length; i++) {
      var d = widget.drawerItems[i];
      drawerOptions.add(new ListTile(
        leading: new Icon(d.icon),
        title: new Text(d.title),
        selected: i == _selectedDrawerIndex,
        onTap: () => _onSelectItem(i),
      ));
    }
    drawerOptions.add(
        new RaisedButton(onPressed: () => {}, child: new Text("Ustawienia")));

    return new Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverAppBar(
                expandedHeight: 130.0,
                floating: false,
                pinned: true,
                flexibleSpace: FlexibleSpaceBar(
                  title:
                      new Text(widget.drawerItems[_selectedDrawerIndex].title),
                ),
              ),
            ];
          },
          body: _getDrawerItemWidget(_selectedDrawerIndex),
        ),
        drawer: new Drawer(
          child: new Column(
            children: <Widget>[
              new UserAccountsDrawerHeader(
                  accountName: new Text("Gość"), accountEmail: null),
              new Column(children: drawerOptions)
            ],
          ),
        ));

```
Result:

![image](https://user-images.githubusercontent.com/26817206/52407779-77ec0a00-2ad1-11e9-9313-3e58961c76e4.png)

As you can see, there is weird blank space, wchich should not be there. Without using collapsing toolbar:

```dart
return new Scaffold(
      appBar: new AppBar(
        // here we display the title corresponding to the fragment
        // you can instead choose to have a static title
        title: new Text(widget.drawerItems[_selectedDrawerIndex].title),
      ),
      drawer: new Drawer(
        child: new Column(
          children: <Widget>[
            new UserAccountsDrawerHeader(
                accountName: new Text("Gość"), accountEmail: null),
            new Column(children: drawerOptions)
          ],
        ),
      ),
      body: _getDrawerItemWidget(_selectedDrawerIndex),
    );`

```
Result is as expected:

![image](https://user-images.githubusercontent.com/26817206/52407853-ad90f300-2ad1-11e9-865c-0664b7b0577e.png)

Any ideas what's wrong?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

https://stackoverflow.com/questions/54553278/flutter-nestedscrollview-sliverappbar-unwanted-bottom-margin is the right place.

**Comment by giaur500** [comment]
@zoechi is that not Flutter bug for sure? It looks like I did not do anything wrong.

**Comment by zoechi** [comment]
You already created a StackOverflow question. In case it turns out to be a Flutter bug we can reopen.
First please try to improve the StackOverflow question to ensure people can investigate.
Ideally post a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
