### ISSUE TITLE
WebViewScaffold not loading circular progress indicator 

### ISSUE THREAD

**Issue by nikhil-francium** [flutter/flutter#27637]
While building state for first time,**WebViewScaffold not loading circular progress indicator** even after `hidden` is set to `true`. But it is showing circular progress indicator after performing hot restart.

**Comment by kangwang1988** [comment]
cc @cyanglaz

**Comment by cyanglaz** [comment]
`WebViewScaffold` doesn't seem to be from first party plugins. For 3rd party plugins, please open an issue on the 3rd party plugin GitHub page, maybe this one is what you are looking for? https://github.com/fluttercommunity/flutter_webview_plugin
We also have a first party web view plugin that can be found here https://pub.dartlang.org/packages/webview_flutter

Closing the issue for now. Please feel free to open another issue if any first party plugins issues is found.
