### ISSUE TITLE
[add-to-app] Support flavors in module assemble

### ISSUE THREAD

**Issue by jelenalecic** [flutter/flutter#27639]
So, as suggested here:
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
we have added our Flutter module in existing apps(both android and iOS).
It works good, ATM :D 

And now, I have added targets in my flutter module(to support different ssl certificates for different environments), as suggested here:
https://iirokrankka.com/2018/03/02/separating-build-environments/

Currently, we're building flutter module like this(from host Jenkins script):

```
cd flutter_module
cd .android
./gradlew clean
./gradlew assembleRelease
 ./gradlew assembleDebug
```

**My question is, how can I assemble certain flutter target?**

In example listed above, they're using:
```
flutter run -t lib/main_dev.dart
flutter run -t lib/main_prod.dart
```

...but how can I build this target from host app?

```
Jelenas-MacBook-Pro:flutter-comment-wall jelenalecic$ flutter doctor -v
[✓] Flutter (Channel master, v1.2.1-pre.66, on Mac OS X 10.13.6 17G4015, locale en-US)
    • Flutter version 1.2.1-pre.66 at /Users/jelenalecic/projects/flutter
    • Framework revision 496ddc580c (5 days ago), 2019-02-02 16:23:39 -0800
    • Engine revision 15f2b92cce
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 71bee8f05e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jelenalecic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

@dnfield

**Comment by wouterhardeman** [comment]
Based on [this line](https://github.com/flutter/flutter/blob/2aad59314fb98f29a4dcdcacda77c0926418ea95/packages/flutter_tools/gradle/flutter.gradle#L313) I think this can be done by setting the target in `.android/Flutter/build.gradle` like this:

```gradle
flutter {
    source '../..' // this line should already be there
    target 'lib/main_prod.dart'
}
```

You would have to do that manually. It would be nice to be able to easily configure this in the build types in the `build.gradle` of the existing Android app.

**Comment by dnfield** [comment]
I'm not as sure about how this works on the Android side, @matthew-carroll or @xster  might know

**Comment by blasten** [comment]
This already supported in add-to-app. You can add flavors to your host app.  From the host app, you can use Android studio to pick the flavor of your preference: https://developer.android.com/studio/build
