### ISSUE TITLE
Firestore packages doesn't work 

### ISSUE THREAD

**Issue by thonwhal** [flutter/flutter#27638]
I tried this on my working application. I didnt add even library, just dependicies. Unfortunately some of flutter packages doesn't work. So before i use a package i try like this. I tried to add dependicies `cloud_firestore: ^0.9.0` . It didnt work. Only working version of me `cloud_firestore: ^0.6.3` . 
My question , is this only happening to me ? Because why developers add an useless package

**Comment by mossplix** [comment]
What error did you get?

**Comment by thonwhal** [comment]
> 
> 
> What error did you get?

bad format , like all the other errors

**Comment by mossplix** [comment]
Can you post the  pubspec.yaml file?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
> Because why developers add an useless package

The packages are working for many. There can be some version conflicts or incompatibilities. Not all are yet reported clearly. Improvements are planned or work-in-progress.
