### ISSUE TITLE
Isolates are not spawned 

### ISSUE THREAD

**Issue by Thetyne** [flutter/flutter#27630]
I have a problem with flutter release 1.0, randomly isolate are not spawned with debug attached.

i don't understand the problem.

i think it's a similar problem at https://github.com/dart-lang/sdk/issues/26689

## Steps to Reproduce
Start application with debugger,  i spawn 3 times quickly the same isolate entry code.
Randomly, one isolate are not spawned.
Inside vscode, the debug window show isolate line in call stack, but it seem not executed and  in this case breakpoint is not fire inside isolate.

![2019-02-07_10h19_38](https://user-images.githubusercontent.com/11698693/52401454-f6d94680-2ac1-11e9-9f1f-b23eb393c1f5.png)

It work perfectly without debugger.

code of isolate:
https://gist.github.com/Thetyne/a421731eaf8d712fe22634aa352e8839#file-isolate-fail-with-debug-attached

## Flutter doctor
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [version 10.0.17134.523], locale fr-FR)
    • Flutter version 1.0.0 at C:\flutter_sdk\flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • COL L29 • CLCDU18425007412 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment]
To investigate we would need a minimal **runnable** reproduction
**as a single file** so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by DanTup** [comment]
Also, when this happens could you try running the **Dart: Open Observatory** command from the VS Code command palette, then in the Observatory UI see whether all three isolates are listed? It's possible this is a bug in the VS Code plugin that isn't updating the threads list correctly.

If that seems to be the case (Observatory lists 3, but VS Code only shows two) then run the **Dart: Capture Logs** command and tick only the **Observatory** option, then repro the issue. Then click Stop Logging and provide the log.
