### ISSUE TITLE
Image streaming issue using camera app

### ISSUE THREAD

**Issue by sathiez** [flutter/flutter#27644]
`controller.startImageStream((CameraImage availableImage){
        var framesY = availableImage.planes[0].bytes;
        var framesU = availableImage.planes[1].bytes;
        var framesV = availableImage.planes[2].bytes;
        var lenU = framesU.length;
        var lenV = framesV.length;
        var lenY = framesY.length;
        print('$lenU'+' '+'$lenV'+' '+'$lenY');
      });`

where, lenU = 460799
            lenV = 460799
            lenY = 921600
I con't  convert YUV_420 to BGR. I hope lenU & lenV should be 460800, if not, can you suggest me best way to convert YUV_240 to BGR.

**Comment by kangwang1988** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
