### ISSUE TITLE
Invoking a method on channel after startup fails

### ISSUE THREAD

**Issue by enyo** [flutter/flutter#27642]
## Steps to Reproduce

1. Setup a plugin, and a channel to communicate.
2. Setup a call handler in dart with `setMethodCallHandler()`
3. Call `invokeMethod` from iOS or Android right after initialisation (in our case, it's the InApp Purchase Transaction callback that iOS triggers)
4. The call never reaches dart, and on iOS / Android the callback is invoked with `FlutterMethodNotImplemented`

After some time passes (I wasn't able to pinpoint an exact moment), the call goes through as expected.

* * *

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C38b, locale en-AT)
    • Flutter version 1.0.0 at /Users/enyo/local/flutter
    • Framework revision 5391447fae (10 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/enyo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by kangwang1988** [comment]
@enyo 
Can you create a demo project which can reproduce this issue?

**Comment by enyo** [comment]
I've created a test case and after some trial and error was able to pinpoint the problem:

Although the plugin can already send calls **to** native code, `invokeMethod`s **from** native code gets lost **until `runApp()` is called, even though `setMethodCallHandler()` has already been invoked**.

In our flutter `main()` we do some initialisation, and we want to splash screen to remain, until it's done. That's why we added some `await` code in the main and only call `runApp()` when it's done. This has been suggested to me on a stackoverflow question as a recommended way to delay the startup of the app until initialisation has finished.

So there are two possible solutions for this issue:

1. It's a flutter bug, and will be fixed, in which case we can wait for a fix.
2. We remove the initialisation code from `main()` and add our own `SplashScreenWidget` that will be shown until the app is initialised

@kangwang1988 might this get "fixed" in a future release or is this intended behaviour?

**Comment by kangwang1988** [comment]
@enyo 
It seems not a bug, but I can't make it for sure before I reproduce your problem.

**Comment by martflu** [comment]
@kangwang1988 Here is a [demo](https://gitlab.com/martflu/plugin-channel-test) that shows that callbacks work only after running `runApp`.

**Comment by enyo** [comment]
See above `no-response` bot ;)

**Comment by LinusU** [comment]
I think I'm running into this as well, finding this issue wasn't easy 😄 

I'm developing a Flutter Plugin and am trying to use this functionality in my tests, which I run by doing `flutter run -t test/foobar.dart` in my `example` app.

I'm not sure when, if at all `runApp()` is being called in this case.

Is there any technical reason that the plugin cannot send a message before `runApp` has been called. It seems like there shouldn't be since the Flutter side can send messages to the native end just fine.

Any help on how to work around this would be much appreciated!

**Comment by LinusU** [comment]
If anyone else is running into this problem in connection with testing; making the test a `testWidgets` test instead of just `test` worked around this issue for me.

It also have the added benefit of `R` actually working for running the tests again 😁

**Comment by Hixie** [comment]
You need to make sure the binding is initialized (that's what runApp does, that's why it works after you call runApp). See WidgetsFlutterBinding.ensureInitialized.
