### ISSUE TITLE
Image.network is not working ---> SocketException

### ISSUE THREAD

**Issue by bigbl** [flutter/flutter#27652]
## Steps to Reproduce

<!--
using iOS simulator

Hello I'm trying to use Image.network to display an image from the internet 
and getting a timeout error. however, I can access the same image from the  browser no issues.
here is my code
------------------
class TestImage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return 
      Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'https://static.pexels.com/photos/596940/pexels-photo-596940.jpeg',
        ),
      );
   
  }
}
-----

## Logs

Launching lib/main.dart on iPad Pro (12.9-inch) (3rd generation) in debug mode...
Xcode build done.
flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following SocketException was thrown resolving an image codec:
flutter: OS Error: Operation timed out, errno = 60, address = static.pexels.com, port = 52660
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      NetworkImage._loadAsync 
flutter: <asynchronous suspension>
flutter: #1      NetworkImage.load 
flutter: #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> 
flutter: #3      ImageCache.putIfAbsent 
flutter: #4      ImageProvider.resolve.<anonymous closure> 
flutter: #5      SynchronousFuture.then 
flutter: #6      ImageProvider.resolve 
flutter: #7      _ImageState._resolveImage 
flutter: #8      _ImageState.didChangeDependencies 
flutter: #9      StatefulElement._firstBuild 
flutter: #10     ComponentElement.mount 
flutter: #11     Element.inflateWidget 
flutter: #12     Element.updateChild 
flutter: #13     ComponentElement.performRebuild 
flutter: #14     Element.rebuild 
flutter: #15     ComponentElement._firstBuild 
flutter: #16     ComponentElement.mount 
flutter: #17     Element.inflateWidget 
flutter: #18     Element.updateChild 
flutter: #19     ComponentElement.performRebuild 
flutter: #20     Element.rebuild 
flutter: #21     ComponentElement._firstBuild 
flutter: #22     ComponentElement.mount 
flutter: #23     ParentDataElement.mount 
flutter: #24     Element.inflateWidget 
flutter: #25     MultiChildRenderObjectElement.mount 
flutter: #26     Element.inflateWidget 
flutter: #27     Element.updateChild 
flutter: #28     ComponentElement.performRebuild 
flutter: #29     Element.rebuild 
flutter: #30     ComponentElement._firstBuild 
flutter: #31     StatefulElement._firstBuild 
flutter: #32     ComponentElement.mount 
flutter: #33     Element.inflateWidget 
flutter: #34     Element.updateChild 
flutter: #35     ComponentElement.performRebuild 
flutter: #36     Element.rebuild 
flutter: #37     ComponentElement._firstBuild 
flutter: #38     ComponentElement.mount 
flutter: #39     Element.inflateWidget 
flutter: #40     Element.updateChild 
flutter: #41     ComponentElement.performRebuild 
flutter: #42     Element.rebuild 
flutter: #43     ComponentElement._firstBuild 
flutter: #44     StatefulElement._firstBuild 
flutter: #45     ComponentElement.mount 
flutter: #46     Element.inflateWidget 
flutter: #47     Element.updateChild 
flutter: #48     SingleChildRenderObjectElement.mount 
flutter: #49     Element.inflateWidget 
flutter: #50     Element.updateChild 
flutter: #51     ComponentElement.performRebuild 
flutter: #52     Element.rebuild 
flutter: #53     ComponentElement._firstBuild 
flutter: #54     ComponentElement.mount 
flutter: #55     Element.inflateWidget 
flutter: #56     Element.updateChild 
flutter: #57     SingleChildRenderObjectElement.mount 
flutter: #58     Element.inflateWidget 
flutter: #59     Element.updateChild 
flutter: #60     ComponentElement.performRebuild 
flutter: #61     Element.rebuild 
flutter: #62     ComponentElement._firstBuild 
flutter: #63     StatefulElement._firstBuild 
flutter: #64     ComponentElement.mount 
flutter: #65     Element.inflateWidget 
flutter: #66     Element.updateChild 
flutter: #67     ComponentElement.performRebuild 
flutter: #68     Element.rebuild 
flutter: #69     ComponentElement._firstBuild 
flutter: #70     StatefulElement._firstBuild 
flutter: #71     ComponentElement.mount 
flutter: #72     Element.inflateWidget 
flutter: #73     Element.updateChild 
flutter: #74     ComponentElement.performRebuild 
flutter: #75     Element.rebuild 
flutter: #76     ComponentElement._firstBuild 
flutter: #77     ComponentElement.mount 
flutter: #78     Element.inflateWidget 
flutter: #79     Element.updateChild 
flutter: #80     ComponentElement.performRebuild 
flutter: #81     Element.rebuild 
flutter: #82     ComponentElement._firstBuild 
flutter: #83     ComponentElement.mount 
flutter: #84     Element.inflateWidget 
flutter: #85     Element.updateChild 
flutter: #86     ComponentElement.performRebuild 
flutter: #87     Element.rebuild 
flutter: #88     ComponentElement._firstBuild 
flutter: #89     StatefulElement._firstBuild 
flutter: #90     ComponentElement.mount 
flutter: #91     Element.inflateWidget 
flutter: #92     Element.updateChild 
flutter: #93     ComponentElement.performRebuild 
flutter: #94     Element.rebuild 
flutter: #95     ComponentElement._firstBuild 
flutter: #96     ComponentElement.mount 
flutter: #97     Element.inflateWidget 
flutter: #98     Element.updateChild 
flutter: #99     SingleChildRenderObjectElement.mount 
flutter: #100    Element.inflateWidget 
flutter: #101    Element.updateChild 
flutter: #102    ComponentElement.performRebuild 
flutter: #103    Element.rebuild 
flutter: #104    ComponentElement._firstBuild 
flutter: #105    ComponentElement.mount 
flutter: #106    Element.inflateWidget 
flutter: #107    Element.updateChild 
flutter: #108    SingleChildRenderObjectElement.mount 
flutter: #109    Element.inflateWidget 
flutter: #110    Element.updateChild 
flutter: #111    SingleChildRenderObjectElement.mount 
flutter: #112    Element.inflateWidget 
flutter: #113    MultiChildRenderObjectElement.mount 
flutter: #114    Element.inflateWidget 
flutter: #115    Element.updateChild 
flutter: #116    ComponentElement.performRebuild 
flutter: #117    Element.rebuild 
flutter: #118    ComponentElement._firstBuild 
flutter: #119    StatefulElement._firstBuild 
flutter: #120    ComponentElement.mount 
flutter: #121    Element.inflateWidget 
flutter: #122    Element.updateChild 
flutter: #123    SingleChildRenderObjectElement.mount 
flutter: #124    Element.inflateWidget 
flutter: #125    Element.updateChild 
flutter: #126    ComponentElement.performRebuild 
flutter: #127    Element.rebuild 
flutter: #128    ComponentElement._firstBuild 
flutter: #129    StatefulElement._firstBuild 
flutter: #130    ComponentElement.mount 
flutter: #131    Element.inflateWidget 
flutter: #132    Element.updateChild 
flutter: #133    SingleChildRenderObjectElement.mount 
flutter: #134    Element.inflateWidget 
flutter: #135    Element.updateChild 
flutter: #136    ComponentElement.performRebuild 
flutter: #137    Element.rebuild 
flutter: #138    ComponentElement._firstBuild 
flutter: #139    StatefulElement._firstBuild 
flutter: #140    ComponentElement.mount 
flutter: #141    Element.inflateWidget 
flutter: #142    Element.updateChild 
flutter: #143    SingleChildRenderObjectElement.mount 
flutter: #144    Element.inflateWidget 
flutter: #145    Element.updateChild 
flutter: #146    ComponentElement.performRebuild 
flutter: #147    Element.rebuild 
flutter: #148    ComponentElement._firstBuild 
flutter: #149    StatefulElement._firstBuild 
flutter: #150    ComponentElement.mount 
flutter: #151    Element.inflateWidget 
flutter: #152    Element.updateChild 
flutter: #153    ComponentElement.performRebuild 
flutter: #154    Element.rebuild 
flutter: #155    ComponentElement._firstBuild 
flutter: #156    ComponentElement.mount 
flutter: #157    Element.inflateWidget 
flutter: #158    Element.updateChild 
flutter: #159    ComponentElement.performRebuild 
flutter: #160    Element.rebuild 
flutter: #161    ComponentElement._firstBuild 
flutter: #162    StatefulElement._firstBuild 
flutter: #163    ComponentElement.mount 
flutter: #164    Element.inflateWidget 
flutter: #165    Element.updateChild 
flutter: #166    SingleChildRenderObjectElement.mount 
flutter: #167    Element.inflateWidget 
flutter: #168    Element.updateChild 
flutter: #169    ComponentElement.performRebuild 
flutter: #170    Element.rebuild 
flutter: #171    ComponentElement._firstBuild 
flutter: #172    ComponentElement.mount 
flutter: #173    Element.inflateWidget 
flutter: #174    Element.updateChild 
flutter: #175    SingleChildRenderObjectElement.mount 
flutter: #176    Element.inflateWidget 
flutter: #177    Element.updateChild 
flutter: #178    ComponentElement.performRebuild 
flutter: #179    Element.rebuild 
flutter: #180    ComponentElement._firstBuild 
flutter: #181    StatefulElement._firstBuild 
flutter: #182    ComponentElement.mount 
flutter: #183    Element.inflateWidget 
flutter: #184    Element.updateChild 
flutter: #185    ComponentElement.performRebuild 
flutter: #186    Element.rebuild 
flutter: #187    ComponentElement._firstBuild 
flutter: #188    ComponentElement.mount 
flutter: #189    Element.inflateWidget 
flutter: #190    Element.updateChild 
flutter: #191    SingleChildRenderObjectElement.mount 
flutter: #192    Element.inflateWidget 
flutter: #193    Element.updateChild 
flutter: #194    ComponentElement.performRebuild 
flutter: #195    Element.rebuild 
flutter: #196    ComponentElement._firstBuild 
flutter: #197    ComponentElement.mount 
flutter: #198    Element.inflateWidget 
flutter: #199    Element.updateChild 
flutter: #200    ComponentElement.performRebuild 
flutter: #201    Element.rebuild 
flutter: #202    ComponentElement._firstBuild 
flutter: #203    StatefulElement._firstBuild 
flutter: #204    ComponentElement.mount 
flutter: #205    Element.inflateWidget 
flutter: #206    Element.updateChild 
flutter: #207    ComponentElement.performRebuild 
flutter: #208    Element.rebuild 
flutter: #209    ComponentElement._firstBuild 
flutter: #210    StatefulElement._firstBuild 
flutter: #211    ComponentElement.mount 
flutter: #212    Element.inflateWidget 
flutter: #213    Element.updateChild 
flutter: #214    RenderObjectElement.updateChildren 
flutter: #215    MultiChildRenderObjectElement.update 
flutter: #216    Element.updateChild 
flutter: #217    _TheatreElement.update 
flutter: #218    Element.updateChild 
flutter: #219    ComponentElement.performRebuild 
flutter: #220    Element.rebuild 
flutter: #221    StatefulElement.update 
flutter: #222    Element.updateChild 
flutter: #223    ComponentElement.performRebuild 
flutter: #224    Element.rebuild 
flutter: #225    ProxyElement.update 
flutter: #226    Element.updateChild 
flutter: #227    SingleChildRenderObjectElement.update 
flutter: #228    Element.updateChild 
flutter: #229    ComponentElement.performRebuild 
flutter: #230    Element.rebuild 
flutter: #231    StatefulElement.update 
flutter: #232    Element.updateChild 
flutter: #233    SingleChildRenderObjectElement.update 
flutter: #234    Element.updateChild 
flutter: #235    SingleChildRenderObjectElement.update 
flutter: #236    Element.updateChild 
flutter: #237    ComponentElement.performRebuild 
flutter: #238    Element.rebuild 
flutter: #239    BuildOwner.buildScope 
flutter: #240    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
flutter: #241    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
flutter: #242    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
flutter: #243    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
flutter: #244    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
flutter: #245    _invoke (dart:ui/hooks.dart:128:13)
flutter: #246    _drawFrame (dart:ui/hooks.dart:117:3)
flutter:
flutter: Image provider: NetworkImage("https://static.pexels.com/photos/596940/pexels-photo-596940.jpeg",
flutter: scale: 1.0)
flutter: Image key: NetworkImage("https://static.pexels.com/photos/596940/pexels-photo-596940.jpeg", scale:
flutter: 1.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Sh1d0w** [comment]
I doubt anyone can help you without providing more info, or example code that can reproduce this.

**Comment by kangwang1988** [comment]
Thanks for filing an issue, but I’m going to close it for lack of a description. If you add a comment with details, we’ll reopen the issue.
@bigbl

**Comment by bigbl** [comment]
here is my code, I'm testing to use Image.network---->class TestImage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return 
      Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'https://static.pexels.com/photos/596940/pexels-photo-596940.jpeg',
        ),
      );
   
  }
}

**Comment by bigbl** [comment]
and here is the error trace---->
lutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following SocketException was thrown resolving an image codec:
flutter: OS Error: Operation timed out, errno = 60, address = static.pexels.com, port = 52660
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      NetworkImage._loadAsync 
flutter: <asynchronous suspension>
flutter: #1      NetworkImage.load 
flutter: #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure> 
flutter: #3      ImageCache.putIfAbsent 
flutter: #4      ImageProvider.resolve.<anonymous closure> 
flutter: #5      SynchronousFuture.then 
flutter: #6      ImageProvider.resolve 
flutter: #7      _ImageState._resolveImage 
flutter: #8      _ImageState.didChangeDependencies 
flutter: #9      StatefulElement._firstBuild 
flutter: #10     ComponentElement.mount 
flutter: #11     Element.inflateWidget 
flutter: #12     Element.updateChild 
flutter: #13     ComponentElement.performRebuild 
flutter: #14     Element.rebuild 
flutter: #15     ComponentElement._firstBuild 
flutter: #16     ComponentElement.mount 
flutter: #17     Element.inflateWidget 
flutter: #18     Element.updateChild 
flutter: #19     ComponentElement.performRebuild 
flutter: #20     Element.rebuild 
flutter: #21     ComponentElement._firstBuild 
flutter: #22     ComponentElement.mount 
flutter: #23     ParentDataElement.mount 
flutter: #24     Element.inflateWidget 
flutter: #25     MultiChildRenderObjectElement.mount 
flutter: #26     Element.inflateWidget 
flutter: #27     Element.updateChild 
flutter: #28     ComponentElement.performRebuild 
flutter: #29     Element.rebuild 
flutter: #30     ComponentElement._firstBuild 
flutter: #31     StatefulElement._firstBuild 
flutter: #32     ComponentElement.mount 
flutter: #33     Element.inflateWidget 
flutter: #34     Element.updateChild 
flutter: #35     ComponentElement.performRebuild 
flutter: #36     Element.rebuild 
flutter: #37     ComponentElement._firstBuild 
flutter: #38     ComponentElement.mount 
flutter: #39     Element.inflateWidget 
flutter: #40     Element.updateChild 
flutter: #41     ComponentElement.performRebuild 
flutter: #42     Element.rebuild 
flutter: #43     ComponentElement._firstBuild 
flutter: #44     StatefulElement._firstBuild 
flutter: #45     ComponentElement.mount 
flutter: #46     Element.inflateWidget 
flutter: #47     Element.updateChild 
flutter: #48     SingleChildRenderObjectElement.mount 
flutter: #49     Element.inflateWidget 
flutter: #50     Element.updateChild 
flutter: #51     ComponentElement.performRebuild 
flutter: #52     Element.rebuild 
flutter: #53     ComponentElement._firstBuild 
flutter: #54     ComponentElement.mount 
flutter: #55     Element.inflateWidget 
flutter: #56     Element.updateChild 
flutter: #57     SingleChildRenderObjectElement.mount 
flutter: #58     Element.inflateWidget 
flutter: #59     Element.updateChild 
flutter: #60     ComponentElement.performRebuild 
flutter: #61     Element.rebuild 
flutter: #62     ComponentElement._firstBuild 
flutter: #63     StatefulElement._firstBuild 
flutter: #64     ComponentElement.mount 
flutter: #65     Element.inflateWidget 
flutter: #66     Element.updateChild 
flutter: #67     ComponentElement.performRebuild 
flutter: #68     Element.rebuild 
flutter: #69     ComponentElement._firstBuild 
flutter: #70     StatefulElement._firstBuild 
flutter: #71     ComponentElement.mount 
flutter: #72     Element.inflateWidget 
flutter: #73     Element.updateChild 
flutter: #74     ComponentElement.performRebuild 
flutter: #75     Element.rebuild 
flutter: #76     ComponentElement._firstBuild 
flutter: #77     ComponentElement.mount 
flutter: #78     Element.inflateWidget 
flutter: #79     Element.updateChild 
flutter: #80     ComponentElement.performRebuild 
flutter: #81     Element.rebuild 
flutter: #82     ComponentElement._firstBuild 
flutter: #83     ComponentElement.mount 
flutter: #84     Element.inflateWidget 
flutter: #85     Element.updateChild 
flutter: #86     ComponentElement.performRebuild 
flutter: #87     Element.rebuild 
flutter: #88     ComponentElement._firstBuild 
flutter: #89     StatefulElement._firstBuild 
flutter: #90     ComponentElement.mount 
flutter: #91     Element.inflateWidget 
flutter: #92     Element.updateChild 
flutter: #93     ComponentElement.performRebuild 
flutter: #94     Element.rebuild 
flutter: #95     ComponentElement._firstBuild 
flutter: #96     ComponentElement.mount 
flutter: #97     Element.inflateWidget 
flutter: #98     Element.updateChild 
flutter: #99     SingleChildRenderObjectElement.mount 
flutter: #100    Element.inflateWidget 
flutter: #101    Element.updateChild 
flutter: #102    ComponentElement.performRebuild 
flutter: #103    Element.rebuild 
flutter: #104    ComponentElement._firstBuild 
flutter: #105    ComponentElement.mount 
flutter: #106    Element.inflateWidget 
flutter: #107    Element.updateChild 
flutter: #108    SingleChildRenderObjectElement.mount 
flutter: #109    Element.inflateWidget 
flutter: #110    Element.updateChild 
flutter: #111    SingleChildRenderObjectElement.mount 
flutter: #112    Element.inflateWidget 
flutter: #113    MultiChildRenderObjectElement.mount 
flutter: #114    Element.inflateWidget 
flutter: #115    Element.updateChild 
flutter: #116    ComponentElement.performRebuild 
flutter: #117    Element.rebuild 
flutter: #118    ComponentElement._firstBuild 
flutter: #119    StatefulElement._firstBuild 
flutter: #120    ComponentElement.mount 
flutter: #121    Element.inflateWidget 
flutter: #122    Element.updateChild 
flutter: #123    SingleChildRenderObjectElement.mount 
flutter: #124    Element.inflateWidget 
flutter: #125    Element.updateChild 
flutter: #126    ComponentElement.performRebuild 
flutter: #127    Element.rebuild 
flutter: #128    ComponentElement._firstBuild 
flutter: #129    StatefulElement._firstBuild 
flutter: #130    ComponentElement.mount 
flutter: #131    Element.inflateWidget 
flutter: #132    Element.updateChild 
flutter: #133    SingleChildRenderObjectElement.mount 
flutter: #134    Element.inflateWidget 
flutter: #135    Element.updateChild 
flutter: #136    ComponentElement.performRebuild 
flutter: #137    Element.rebuild 
flutter: #138    ComponentElement._firstBuild 
flutter: #139    StatefulElement._firstBuild 
flutter: #140    ComponentElement.mount 
flutter: #141    Element.inflateWidget 
flutter: #142    Element.updateChild 
flutter: #143    SingleChildRenderObjectElement.mount 
flutter: #144    Element.inflateWidget 
flutter: #145    Element.updateChild 
flutter: #146    ComponentElement.performRebuild 
flutter: #147    Element.rebuild 
flutter: #148    ComponentElement._firstBuild 
flutter: #149    StatefulElement._firstBuild 
flutter: #150    ComponentElement.mount 
flutter: #151    Element.inflateWidget 
flutter: #152    Element.updateChild 
flutter: #153    ComponentElement.performRebuild 
flutter: #154    Element.rebuild 
flutter: #155    ComponentElement._firstBuild 
flutter: #156    ComponentElement.mount 
flutter: #157    Element.inflateWidget 
flutter: #158    Element.updateChild 
flutter: #159    ComponentElement.performRebuild 
flutter: #160    Element.rebuild 
flutter: #161    ComponentElement._firstBuild 
flutter: #162    StatefulElement._firstBuild 
flutter: #163    ComponentElement.mount 
flutter: #164    Element.inflateWidget 
flutter: #165    Element.updateChild 
flutter: #166    SingleChildRenderObjectElement.mount 
flutter: #167    Element.inflateWidget 
flutter: #168    Element.updateChild 
flutter: #169    ComponentElement.performRebuild 
flutter: #170    Element.rebuild 
flutter: #171    ComponentElement._firstBuild 
flutter: #172    ComponentElement.mount 
flutter: #173    Element.inflateWidget 
flutter: #174    Element.updateChild 
flutter: #175    SingleChildRenderObjectElement.mount 
flutter: #176    Element.inflateWidget 
flutter: #177    Element.updateChild 
flutter: #178    ComponentElement.performRebuild 
flutter: #179    Element.rebuild 
flutter: #180    ComponentElement._firstBuild 
flutter: #181    StatefulElement._firstBuild 
flutter: #182    ComponentElement.mount 
flutter: #183    Element.inflateWidget 
flutter: #184    Element.updateChild 
flutter: #185    ComponentElement.performRebuild 
flutter: #186    Element.rebuild 
flutter: #187    ComponentElement._firstBuild 
flutter: #188    ComponentElement.mount 
flutter: #189    Element.inflateWidget 
flutter: #190    Element.updateChild 
flutter: #191    SingleChildRenderObjectElement.mount 
flutter: #192    Element.inflateWidget 
flutter: #193    Element.updateChild 
flutter: #194    ComponentElement.performRebuild 
flutter: #195    Element.rebuild 
flutter: #196    ComponentElement._firstBuild 
flutter: #197    ComponentElement.mount 
flutter: #198    Element.inflateWidget 
flutter: #199    Element.updateChild 
flutter: #200    ComponentElement.performRebuild 
flutter: #201    Element.rebuild 
flutter: #202    ComponentElement._firstBuild 
flutter: #203    StatefulElement._firstBuild 
flutter: #204    ComponentElement.mount 
flutter: #205    Element.inflateWidget 
flutter: #206    Element.updateChild 
flutter: #207    ComponentElement.performRebuild 
flutter: #208    Element.rebuild 
flutter: #209    ComponentElement._firstBuild 
flutter: #210    StatefulElement._firstBuild 
flutter: #211    ComponentElement.mount 
flutter: #212    Element.inflateWidget 
flutter: #213    Element.updateChild 
flutter: #214    RenderObjectElement.updateChildren 
flutter: #215    MultiChildRenderObjectElement.update 
flutter: #216    Element.updateChild 
flutter: #217    _TheatreElement.update 
flutter: #218    Element.updateChild 
flutter: #219    ComponentElement.performRebuild 
flutter: #220    Element.rebuild 
flutter: #221    StatefulElement.update 
flutter: #222    Element.updateChild 
flutter: #223    ComponentElement.performRebuild 
flutter: #224    Element.rebuild 
flutter: #225    ProxyElement.update 
flutter: #226    Element.updateChild 
flutter: #227    SingleChildRenderObjectElement.update 
flutter: #228    Element.updateChild 
flutter: #229    ComponentElement.performRebuild 
flutter: #230    Element.rebuild 
flutter: #231    StatefulElement.update 
flutter: #232    Element.updateChild 
flutter: #233    SingleChildRenderObjectElement.update 
flutter: #234    Element.updateChild 
flutter: #235    SingleChildRenderObjectElement.update 
flutter: #236    Element.updateChild 
flutter: #237    ComponentElement.performRebuild 
flutter: #238    Element.rebuild 
flutter: #239    BuildOwner.buildScope 
flutter: #240    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
flutter: #241    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
flutter: #242    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
flutter: #243    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
flutter: #244    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
flutter: #245    _invoke (dart:ui/hooks.dart:128:13)
flutter: #246    _drawFrame (dart:ui/hooks.dart:117:3)
flutter:
flutter: Image provider: NetworkImage("https://static.pexels.com/photos/596940/pexels-photo-596940.jpeg",
flutter: scale: 1.0)
flutter: Image key: NetworkImage("https://static.pexels.com/photos/596940/pexels-photo-596940.jpeg", scale:
flutter: 1.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by bigbl** [comment]
I'm very new to this. I'm thinking it could be a proxy issue with the simulator that I'm using.

**Comment by bigbl** [comment]
I just answered my own question, it was a proxy issue after all! closing this issue

**Comment by tandnd** [comment]
Hi, I knew it was a proxy issue, but how could you fix it?
