### ISSUE TITLE
Docset no longer shows classes

### ISSUE THREAD

**Issue by xster** [flutter/flutter#27654]
https://master-docs.flutter.io/offline/flutter.docset.tar.gz regressed at some point since 1.0 and only shows Exception and Method types but don't show others like Class etc

**Comment by gspencergoog** [comment]
The problem is that dartdoc changed the css classes it draws class names with. The `dev/docs/dashing.json` just needs to be updated to match the new classes.

**Comment by gspencergoog** [comment]
Actually, not quite that simple: dartdoc now uses the same CSS class for Library as it does for Class, so a dartdoc change will be needed.

**Comment by xster** [comment]
This was since solved.
