### ISSUE TITLE
BottomNavigationBar elevation

### ISSUE THREAD

**Issue by PrimankaDEN** [flutter/flutter#27651]
I try to create a transparent `BottomNavigationBar` that has the same color as entire page. But navigation bar has non-switchable shadow effect. In sources I see that navigation bar layout has elevation is setted 8.0. Can you add constructor argument to change elevation value?

![device-2019-02-07-233506](https://user-images.githubusercontent.com/7315001/52438156-14de8f80-2b32-11e9-9d4c-c4f7585ed482.png)

**Comment by HansMuller** [comment]
That's a reasonable request, will do.
