### ISSUE TITLE
Firebase Deeplinks not returned after first install in release mode - iOS

### ISSUE THREAD

**Issue by KarthikSCP** [flutter/flutter#27658]
## Steps to Reproduce

1. Create a deeplink using Firebase console.
2. Make sure app is not installed.
3. Tap on deeplink, navigates to App Store, download the app.
4. App opens after install.
5. Deeplink is null in _retrieveDynamicLink().

Please note this happens only in AppStore (release builds), when I do the same steps in debug mode I get the deeplink tapped.

I am using https://pub.dartlang.org/packages/firebase_dynamic_links.

## Logs

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Users/user/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] VS Code (version 1.31.0)
    • VS Code at /Users/karthiksa/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone X • 9389873 • ios • iOS 12.1.3

• No issues found!

```

**Comment by tapkain** [comment]
will this be fixed? this is crucial for my app with invite codes, it's horrible that such a foundational bug is here in open for such a long time...

**Comment by dhanrajvermaRepo** [comment]
I am using firebase_dynamic_links ^0.5.0 . This plugin is working fine in android but in ios it is not working when app is in running/background state. when link is clicked in running/background state on ios device it does not open specified location in the app the application. If link is clicked in killed state then it works fine.(opens the specified location in application).
I have no idea why it is behaving like this.
should I use one of the old versions?

**Comment by kroikie** [comment]
@KarthikSCP

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/459. Any further collaboration will be done there.
