### ISSUE TITLE
Flutter build crashes if Android Studio is downloaded from JetBrains Toolbox

### ISSUE THREAD

**Issue by timtraversy** [flutter/flutter#27670]
I believe this is related to #27136. If I install Android Studio from the JetBrains Toolbox, the Flutter build process crashes with this error:
```
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 570340d63911285d)
Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("=")
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:57:85)
#2      AndroidStudio._allMacOS.<anonymous closure (package:flutter_tools/src/android/android_studio.dart:200:67)
```
The error causing snippets in android_studio:
```
final RegExp _pathsSelectorMatcher =
    RegExp(r'"idea.paths.selector" = "AndroidStudio[^;]+"');
....
final String plistFile = fs.path.join(studioPath, 'Info.plist');
...
final String pathsSelectorValue = 
    _pathsSelectorMatcher.stringMatch(plistValue).split('=').last.trim().replaceAll('"', '');
```
If Android Studio is downloaded normally from the web, the Info.plist file contained a section that looks like this:
```
        Properties =         {
            "idea.executable" = studio;
            "idea.home.path" = "$APP_PACKAGE/Contents";
            "idea.java.redist" = Bundled;
            "idea.paths.selector" = "AndroidStudio3.3";
            "idea.platform.prefix" = AndroidStudio;
        };
```
So the Regex can find and parse the `idea.paths.selector` line. But when it is downloaded from the Toolbox, the Info.plist consists of just this:
```
{
    CFBundleDevelopmentRegion = English;
    CFBundleExecutable = "jetbrains-toolbox-launcher";
    CFBundleGetInfoString = "";
    CFBundleIconFile = "icon.icns";
    CFBundleIdentifier = "com.jetbrains.apps.activator.linkapp.pcom.jetbrains.apps.activator__ndroid_tudio_3_3_1";
    CFBundleInfoDictionaryVersion = "6.0";
    CFBundleLongVersionString = "3.3.1";
    CFBundleName = "Android Studio";
    CFBundlePackageType = APPL;
    CFBundleShortVersionString = "3.3.1";
    CFBundleSignature = "????";
    CFBundleVersion = "3.3.1";
    JetBrainsToolboxApp = "/Users/timtraversy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app";
    LSUIElement = 1;
    NSHighResolutionCapable = 1;
    NSHumanReadableCopyright = "Copyright (c) JetBrains s.r.o.";
    NSUIElement = 0;
}
```
So the Regex returns null and `split` causes a crash.

This seems new, maybe related to release of AS 3.3? Because I believe I've gotten my version from the Toolbox for the past year. Would like to see if someone else can replicate. I wiped Flutter and AS from my computer before testing this so I think it should happen on anyone's computer.

**Comment by kangwang1988** [comment]
@timtraversy 
This is introduced in https://github.com/flutter/flutter/pull/26964
I will have a look at this case soon. Thanks for your feedback.

**Comment by tvolkert** [comment]
Is there any reason we can't revert #26964 while this is being fixed to unblock releases to the dev channel?

**Comment by kangwang1988** [comment]
@tvolkert 
https://github.com/flutter/flutter/pull/27687 will land when the tree is green
This issue would also be resolved.

**Comment by msobocin** [comment]
resolved with last update of flutter

**Comment by trevburley** [comment]
Can confirm this has fixed things for me - thanks!
