### ISSUE TITLE
[google_map_flutter] Offline maps

### ISSUE THREAD

**Issue by samycodes** [flutter/flutter#27678]
Does flutter provides any plugin which can offer Offline Maps, Like user request for specific area in map and it provides that which is saved and can be used anytime later?

Thanks

**Comment by amreniouinnovent** [comment]
Google map plugin now is supporting polylines.
The missing features are just offline support and a widget marker

**Comment by ThinkDigitalSoftware** [comment]
I'm looking for the ability to download certain areas offline like the official Google Maps as well. Or caching or something. If I hot reload an app but turn on Airplane Mode, the map won't load.

**Comment by sudangrg** [comment]
any updates on this issue?

**Comment by stuartmorgan** [comment]
Since the SDK doesn't support this, the plugin can't either. Closing as infeasible.
