### ISSUE TITLE
firebase_auth SHA-1 fingerprint issue

### ISSUE THREAD

**Issue by easeccy** [flutter/flutter#27684]
I get SHA-1 from `debug.keystore` using this code

```sh
keytool -list -v -keystore "%USERPROFILE%\.android\debug.keystore" -alias androiddebugkey -storepass android -keypass android
``` 

I've succesfully created Firebase project and used the SHA-1 fingerprint from `debug.keystore`. Then downloaded `google-services.json` and put it into the project. Everything (email auth, anonymous auth etc.) works fine but when I try to verify phone number it gives error.

```dart
final FirebaseAuth _auth = FirebaseAuth.instance;

Future<void> _testPhone() async {
    _auth.verifyPhoneNumber(
        phoneNumber: "xxxxx", //I use my personal phone number here
        timeout: Duration(seconds: 5),
        verificationCompleted: (d) {
          print(d);
        },
        verificationFailed: (d) {
          print(d.code + ": " + d.message);
        },
        codeSent: (d, [d2]) {
          print(d);
        },
        codeAutoRetrievalTimeout: (d) {
          print(d);
        });
}
```

This is the simple code which gives this error:
```
firebaseAuth: This app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed. Is app running on a physical device? ]
```

I'm testing this on the real device. Version of `firebase_auth` plugin is `0.8.0`. I've tried with the version `0.7.0` (last version that is pre AndroidX) and still gives the same error. Since my package name is correct and I'm using a real device, I guess it's a  SHA-1 fingerprint issue.

```
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
[√] VS Code, 64-bit edition (version 1.27.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by wouterhardeman** [comment]
You might have forgotten to add `-exportcert` when getting the fingerprint. See: https://developers.google.com/android/guides/client-auth

**Comment by easeccy** [comment]
> You might have forgotten to add `-exportcert` when getting the fingerprint. See: https://developers.google.com/android/guides/client-auth

Gives the same output. I've also used [this](https://stackoverflow.com/questions/11331469/how-do-i-find-out-which-keystore-was-used-to-sign-an-app) method to get SHA-1 from generated apk. They are all same and correct.

**Comment by KooliFab** [comment]
Same error for me, using `firebase_auth: ^0.8.1+1`. Google sign in works fine

**Comment by MrAlek** [comment]
Same problem here using `firebase_auth: 0.8.4+4`. Debug keys are working but not release.

**Comment by emekalites** [comment]
Same problem here using `firebase_auth: ^0.11.1+5`. I tried testing the debug version with a real device but then i get 

`I/flutter (21369): exception: This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]`

I built a release version and uploaded to the app store, then added the SHA's from the play store into firebase and it works for the production app. 

Please help. I need to test that this feature works before building a release version.

**Comment by MazEbeid** [comment]
Ok but how would you test this integration with your UI during debug stage?

**Comment by kroikie** [comment]
@easeccy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/456. Any further collaboration will be done there.
