### ISSUE TITLE
Flutter freeze my system

### ISSUE THREAD

**Issue by KaoutharAsma** [flutter/flutter#27681]
When i've installed flutter on my pc 
And when i've tried to excute flutter doctor my system freeze complety , and i was obliged to force it to shutdiwn by clicking on the button.  
The same thing happen when i was trying to create a flutter project ( i skipped flutter doctor on this try) 
PS: i'm using ubuntu 

What should I do?!

**Comment by kangwang1988** [comment]
@KaoutharAsma 
Paste 'flutter doctor -vv' please.

**Comment by zoechi** [comment]
Perhaps better `flutter doctor -vv &>flutter_doctor.txt` so that the output is available after restart after the machine freezes and then post the output of `flutter_doctor.txt`.
