### ISSUE TITLE
flutter showdatepicker changing language problem.

### ISSUE THREAD

**Issue by MrFane** [flutter/flutter#27694]
Hi all, I'm new in flutter and I'm writing an app which uses a showdatepicker, the problem is that I want to set it in italian but when I try to change its locale I get the following error : The method 'formatFullDate' was called on null.

this is the code :  
final DateTime picked = await showDatePicker(
      context: context,
      initialDate: prova,
      firstDate: prova,
      locale : const Locale("it","IT"),
      lastDate: data.add(new Duration(days: 45)),
      selectableDayPredicate: (DateTime val) =>
      (val.weekday == DateTime.sunday  ) || val.weekday == DateTime.monday || val.weekday == DateTime.saturday|| val.weekday == DateTime.tuesday  ? false : true,

    );

I would be very very very grateful if someone could help me, thank you all.

**Comment by HansMuller** [comment]
This problem has come up quite a bit, e.g. see https://github.com/flutter/flutter/issues/16304

To get flutter's localizations, including the ones for the date picker, you need to set up your app for internationalization and import the flutter_localizations package. Doing that is described here: https://flutter.io/docs/development/accessibility-and-localization/internationalization

**Comment by MrFane** [comment]
Hi, can you explain me why if I start an activity with a statelesswidged it
hasn't the back arrow button?

Il giorno ven 8 feb 2019 alle ore 23:39 Hans Muller <
notifications@github.com> ha scritto:

**Comment by ChowDavid** [comment]
https://github.com/ChowDavid/flutter_tutorial/blob/1.17.DatePicker/lib/main.dart
