### ISSUE TITLE
Deprecate or delete unused FlutterErrorDetails subclasses

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#27695]
`FlutterErrorDetailsForPointerRouter` and `FlutterErrorDetailsForRendering` aren't currently providing real value as the extra fields stored with the classes appear to always be ignored.

These two classes are only used in a few spots in the framework and the additional fields of these classes are never read anywhere in `package:flutter` or in other places I can locate.

As far as I can tell, these classes were intended to store extra metadata about where certain types of  errors occurred but due to layering, it is impossible to read those fields from `dumpErrorToConsole` in `assertions.dart`. Once `FlutterError` and `FlutterErrorDetails` are refactored to use `DiagnosticsNode` objects there is no real need to introduce extra subclasses for this sort of case.

For example:
`FlutterErrorDetailsForPointerRouter` contains useful information on the router, route, and event
that occurred but it appears we just drop that information on the ground as it isn't possible to use it
from assert.dart as part of `dumpErrorToConsole` due to layering and I can't find any uses of the class outside of `package:flutter`. The simplest solution would be to eliminate these classes and switch the few uses to use `FlutterErrorDetails` adding `DiagnosticsProperty` object describing the extra information.

`FlutterErrorDetailsForPointerRouter` unused fields:
```dart

  /// The pointer router that caught the exception.
  ///
  /// In a typical application, this is the value of [GestureBinding.pointerRouter] on
  /// the binding ([GestureBinding.instance]).
  final PointerRouter router;

  /// The callback that threw the exception.
  final PointerRoute route;

  /// The pointer event that was being routed when the exception was raised.
  final PointerEvent event;

**Comment by goderbauer** [comment]
> Once FlutterError and FlutterErrorDetails are refactored to use DiagnosticsNode objects there is no real need to introduce extra subclasses for this sort of case.

@jacob314 This refactoring is done, right? We should be bale to just remove these extra classes now?

**Comment by jacob314** [comment]
Yeah you should be able to remove them and switch the existing uses to just add DiagnosticsProperty as needed.
