### ISSUE TITLE
Build system requirements for iOS Google Sign-In SDK

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2769]
I'm following the [instructions](https://developers.google.com/identity/sign-in/ios/sdk/) to add the Google Sign-In SDK without CocoaPods and ran into a few steps that I'm not sure are possible with the current build system:
- Add GoogleSignIn.bundle to your Xcode project's Copy Bundle Resources build phase.
- In the Project > Target > Info > URL Types panel, create a new item and paste your REVERSED_CLIENT_ID into the URL Schemes field. You can find your REVERSED_CLIENT_ID in the GoogleService-Info.plist file.
- Also in the Project > Target > Info > URL Types panel, create a new item and type your bundle identifier in the URL Schemes field.

**Comment by chinmaygarde** [comment]
@collinjackson The URL types stuff that the user edits in Xcode ends up in the project Info.plist. We already allow that to be editable. So it shouldn't be a problem to edit that file either directly or via the Xcode UI :+1:

**Comment by collinjackson** [comment]
Excellent.

**Comment by chinmaygarde** [comment]
Are there mojo bindings for this? I will package this up.

**Comment by collinjackson** [comment]
https://github.com/flutter/engine/pull/2524/files though it's probably best if you show me how to do it since I'm still working on the implementation

**Comment by collinjackson** [comment]
assigning this to myself as I've taken over on it

**Comment by mit-mit** [comment]
@collinjackson are you still working on this?

**Comment by collinjackson** [comment]
I think the issue can be closed; it does not apply to https://github.com/flutter/google_sign_in
