### ISSUE TITLE
Including multiple plugins in an empty app exceeds the Android dex limit

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#27702]
Including multiple firebase_ plugins simultaneously in a `pubspec.yaml` file is enough to [exceed the amount of Java methods that can be included in an Android APK by default, so compilation breaks](https://developer.android.com/studio/build/multidex).

## Repro steps

1. `flutter create foo`
2. Edit the `pubspec.yaml` to add the extra deps below.

```yml
dependencies:
  cloud_firestore: any
  firebase_core: any
  firebase_database: any
  firebase_ml_vision: any
  firebase_performance: any
  firebase_remote_config: any
  firebase_storage: any
```

3. `flutter build apk`

## Error output

```
flutter build apk
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.4s
D8: Cannot fit requested classes in a single dex file (# methods: 76505 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
```

## Fix for affected apps

This can be addressed in affected apps using the plugins by [turning on multidexing](https://developer.android.com/studio/build/multidex#mdex-gradle) in their build following the same steps as a typical Android app.

## Fix for the plugins?

It's not clear to me what should be done about this. It ties into wider ongoing discussions about abstracting underlying platform code.

1. We could grep or lint for this error in `flutter tool` and print out a log pointing users to something explaining this error, what multidexing is, how to turn it on.
2. We could warn for this in the README of the firebase plugins themselves since they're likely to be used in combination.
3. There may be a way to turn on multidexing for an app within a plugin? I'm not sure if this is actually preferable here even if it's possible. Multidexing has [downsides](https://developer.android.com/studio/build/multidex#dev-build).
4. Could we proguard the plugins without turning proguard on for entire apps that include them? This would prune unused methods and make it a lot harder to hit this error, but wouldn't totally prevent it.

/cc @Sun3
/cc @dnfield @Hixie @amirh

**Comment by dnfield** [comment]
There's some discussion of this at https://github.com/flutter/flutter/issues/21009

**Comment by wtoalabi** [comment]
Turning multi-indexing on works for sdk >21
But the app auto closes in any device running lower api.
In my use-case I wanted to support at least Lollypop.
So, I just made use of Proguard to help shrink the method counts.
I wrote about my experience here: https://medium.com/@wtoalabi/android-flutter-64k-methods-dex-limit-how-to-use-proguard-in-development-29da38970737
Would love to know if there is a better approach, especially for my use-case.

**Comment by mklim** [comment]
Apparently it's possible to hit this basic error even from just one plugin: #20747.

**Comment by jackyq2015** [comment]
@wtoalabi Your link has gone. I cannot have the Proguard work even under sdk 28.

**Comment by wtoalabi** [comment]
@jackyq2015 Sorry about that...
I changed the username:
[Here it is](https://medium.com/@olawale_alabi/android-flutter-64k-methods-dex-limit-how-to-use-proguard-in-development-728af11a4e22)

**Comment by kroikie** [comment]
@mklim

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/455. Any further collaboration will be done there.
