### ISSUE TITLE
Extended FABs don’t require an icon

### ISSUE THREAD

**Issue by ocavue** [flutter/flutter#27710]
*This issue is a **bug report**.*

## Description

In Material design, an extended FAB doesn’t require an icon.

https://material.io/design/components/buttons-floating-action-button.html#extended-fab

![image](https://user-images.githubusercontent.com/24715727/52516117-6ab15580-2c60-11e9-9a25-54b9c167814d.png)

So, I think the `@required` below should be removed.

https://github.com/flutter/flutter/blob/216a65b6697f2ca5cf3501e50c3f9592334fbe4b/packages/flutter/lib/src/material/floating_action_button.dart#L116

If you guys agree, I can create a pull request to fix it.

## Steps to Reproduce

null

## Logs

null

**Comment by HansMuller** [comment]
Good point, will fix this.

**Comment by zoechi** [comment]
@HansMuller you saw that there is already a PR? #27711

**Comment by HansMuller** [comment]
@zoechi I have seen #27711, thanks for the reminder
