### ISSUE TITLE
Some PNGs no longer render

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27718]
```bash
flutter create dummy
cd dummy
echo "  assets:" >> pubspec.yaml
echo "    - test.png" >> pubspec.yaml
echo "import 'package:flutter/material.dart';" > lib/main.dart
echo "void main() => runApp(Image.asset('test.png'));" >> lib/main.dart
curl https://raw.githubusercontent.com/seamonkeysocial/cruisemonkey/master/images/deck_1.png > test.png
flutter run
```

The image doesn't render if you are using cd9a0037b077eef108850646078a32917f24f327 or later.
It renders fine in 99497dc2d97ac3efdfe933fd16a22bf1b3946730 (the previous commit).

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by mklim** [comment]
Bisected the problem commit in the engine to flutter/engine@d292ed6c235d538dc7b84463696db0201fab9590.

When the PNG renders in its broken form it looks like it may be a cropping issue. Can't tell for sure but it almost looks like it's rendering a very tiny subset of the larger image.

**Comment by mklim** [comment]
I checked out flutter/engine@473097b5 and manually tried the Skia revisions in our `DEPS` file. It looks like [`699d41e`](https://skia.googlesource.com/skia.git/+/699d41e4bd527585693ed086064baf839b65cbad) is the first problem commit. From talking to the Skia team it sounds like we shouldn't be relying on Wuffs yet.
