### ISSUE TITLE
Camera Lag on FirebaseVision.instance.textRecognizer().processImage

### ISSUE THREAD

**Issue by pmcarlos** [flutter/flutter#27716]
## Steps to Reproduce
I am using this code https://github.com/bparrishMines/mlkit_demo
Everything works fine but sincerely the firebase_ml_vision looks like a lag when its processing? Is it normal or is there a better implementation?
I have disabled almost everything from the app and its the processImage what its taking the processing time FirebaseVision.instance.textRecognizer().processImage

**Comment by jaumard** [comment]
Did you test on debug or release mode ? because there is a huge differences

**Comment by kroikie** [comment]
@pmcarlos

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/454. Any further collaboration will be done there.
