### ISSUE TITLE
Flutter firestore platform exception

### ISSUE THREAD

**Issue by drumsapkota** [flutter/flutter#27719]
When trying to access cloud firestore using emulator/other phones I get the following error:
```
W/DynamiteModule( 4277): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 4277): Considering local module com.google.android.gms.flags:3 and remote module com.google.android.gms.flags:0
I/DynamiteModule( 4277): Selected local version of com.google.android.gms.flags
I/DynamiteModule( 4277): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 4277): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
W/System  ( 4277): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86_64
W/System  ( 4277): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86_64
W/System  ( 4277): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86_64
W/System  ( 4277): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86_64
W/System  ( 4277): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86_64
W/linker  ( 4277): /data/data/com.google.android.gms/app_extracted_libs/x86_64/libconscrypt_gmscore_jni.so: unused DT entry: type 0xf arg 0x12a
V/NativeCrypto( 4277): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 276 native methods...
I/art     ( 4277): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.DelegatingExtendedSSLSession>
I/art     ( 4277): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.DelegatingExtendedSSLSession>
I/art     ( 4277): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.DelegatingExtendedSSLSession>
I/ProviderInstaller( 4277): Installed default security provider GmsCore_OpenSSL
I/flutter ( 4277): Inside
W/ManagedChannelImpl( 4277): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl( 4277): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl( 4277): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl( 4277): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl( 4277): [{0}] Failed to resolve name. status={1}
```

Although when I use my phone via USB works fine.

![flutter](https://user-images.githubusercontent.com/22440538/52519279-d5718980-2c7e-11e9-81a0-ec027e3e7e24.PNG)

Here's my `flutter doctor -v`
```
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.523], locale en-IN)
    • Flutter version 1.1.8 at C:\flutter\flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\adity\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

• No issues found!
```
@zoechi Please help

**Comment by zoechi** [comment]
Is this with a new project or did you update dependencies of an existing project?

**Comment by crzdg** [comment]
Similiar Issue at our project.
`

W/DynamiteModule(17338): Local module descriptor class for providerinstaller not found.
I/flutter (17338): cards
I/DynamiteModule(17338): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(17338): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/screenhamsters(17338): The ClassLoaderContext is a special shared library.
I/chatty  (17338): uid=10085(com.example.loginscreenhamstersm) FirestoreWorker identical 1 line
I/screenhamsters(17338): The ClassLoaderContext is a special shared library.
I/flutter (17338): Instance of 'Future<List<QuerySnapshot>>'
I/screenhamsters(17338): The ClassLoaderContext is a special shared library.
`
Code we tried.

`    Firestore firestore = Firestore.instance;
    firestore.settings(timestampsInSnapshotsEnabled: true);
    print(firestore);
    print(firestore.collection('cards'));
    print(firestore.collection('cards').path);
    print(firestore.collection('cards').snapshots().toList());
    var snapshotList = await firestore.collection('cards').snapshots().toList();
    print(snapshotList);`

Output

`I/flutter (17338): Instance of 'Firestore'
I/flutter (17338): Instance of 'CollectionReference'
W/DynamiteModule(17338): Local module descriptor class for providerinstaller not found.
I/flutter (17338): cards`

**Comment by zoechi** [comment]
You might need to update the Play service on your phone/emulator.

**Comment by zoechi** [comment]
or ensure the emulator/device has play service installed

**Comment by drumsapkota** [comment]
Hello all, I was able to solve the issue using the permission: ACCESS_NETWORK_STATE in my manifest file. Don't know if it actually is the solution but worked for me, initially, the problem was such that, after deploying the app in the play store, no user across the country was able to sign up, but when i connected my phone and tested tried it worked. 

Also updating the play services in emulator is an essential step if you are testing on an emulator.

Thanks @zoechi

**Comment by drumsapkota** [comment]
> Is this with a new project or did you update dependencies of an existing project?

I migrated my project to Android X

**Comment by zoechi** [comment]
Thanks for the update!
Sounds weird. I'm going to close. Feel free to add a comment to have it reopened if you see this again.

**Comment by namnh06** [comment]
I still got this error when run on my Samsung Note 9 or on simulator
`W/DynamiteModule(24562): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(24562): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(24562): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.`

**Comment by egarson** [comment]
Hi @namnh06 , are "we" sure that those debug messages (which I get as well) are a definitive indicator that there is something amiss with respect to Firebase Analytics Debug View? 
I am also not seeing any output in Debug View - nor do I see my device listed. I have tried with both an emulator and attached device.

**Comment by kroikie** [comment]
@drumsapkota

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/453. Any further collaboration will be done there.

**Comment by neo-xy** [comment]
In my case I was reading data from friestore incorrecly.
Had a document with property "gpsLocation" that was a map with {lon:number,lat:number} values.

correct way:
`data["gpsLocation"]["lon"];`
instead of:
`data["gpsLocation"].lon;`

in case someone the made same misstake.

**Comment by nitinAct** [comment]
> I still got this error when run on my Samsung Note 9 or on simulator
> `W/DynamiteModule(24562): Local module descriptor class for providerinstaller not found. I/DynamiteModule(24562): Considering local module providerinstaller:0 and remote module providerinstaller:0 W/ProviderInstaller(24562): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.`

Please solve this solution

**Comment by 01FC** [comment]
try upgrading the min supported android version in build.gradle
