### ISSUE TITLE
writing about 31M of data to a file crashes the app

### ISSUE THREAD

**Issue by freemant2000** [flutter/flutter#27724]
Keep writing data to a file (in an isolated but tried it with async with the same result). It is reproducible: it crashes every time. Please find a simple test app that demonstrates the problem. Just run it and click the Start button.

Below is the output of "flutter doctor":
```
./flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.1.8, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```
There is nothing special in the log: it only says "application finished":
```
...
I/flutter ( 5028): 31689728 (<=== these are the byte counts output by my test app)
I/flutter ( 5028): 31690752
I/flutter ( 5028): 31691776
I/flutter ( 5028): 31692800
I/flutter ( 5028): 31693824
Application finished.
```
There is no exception.

**Comment by freemant2000** [comment]
[file_writing_crash.zip](https://github.com/flutter/flutter/files/2847944/file_writing_crash.zip)

**Comment by kangwang1988** [comment]
@freemant2000 
Can you run `flutter run -v` and paste the crash related log here?

**Comment by freemant2000** [comment]
I guess only the last portion of the log is useful:
...
[        ] I/flutter ( 6017): 31798272 (<== my byte counts)
[        ] I/flutter ( 6017): 31799296
[        ] I/flutter ( 6017): 31800320
[  +78 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/com.example.filewritingcrash/cache/file_writing_crashDFCSKQ
/file_writing_crash/)
[        ] Sending to VM service: _deleteDevFS({fsName: file_writing_crash})
[ +252 ms] TimeoutException after 0:00:00.250000: Future not completed
[   +9 ms] "flutter run" took 57,608ms.

**Comment by minh98** [comment]
it seems to be issue of future

**Comment by zoechi** [comment]
Have you tried with a different device or emulator?

**Comment by zoechi** [comment]
Does it behave differently with a smaller file?

**Comment by jason-simmons** [comment]
In the attached app, the `IOSink` is buffering all the data until `flush` is called.  Eventually the Android out-of-memory killer shuts down the process.

The app could call `flush` more frequently during the loop.  But this will work more efficiently with the `RandomAccessFile` API:

```
    RandomAccessFile f = await File("$app_data_directory/test_file").open(mode: FileMode.write);
    var n = 0;
    Uint8List bs = Uint8List(1024);
    for (int i = 0; i < 100000; i++) {
      await f.writeFrom(bs);
      n += bs.length;
      print(n);
    }
    await f.close();
```
