### ISSUE TITLE
"flutter build apk" doesn't always update LICENSE file

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27720]
Steps to reproduce:

1. `flutter create dummy; cd dummy`
2. `flutter build apk`
3. Check that `LICENSE` file does not contain "android_alarm_manager": `grep android_alarm_manager build/app/intermediates/flutter/release/flutter_assets/LICENSE`
4. Add `android_alarm_manager: any` to the pubspec.yaml file's `dependencies` section.
5. `flutter build apk`
6. Check that `build/app/intermediates/flutter/release/flutter_assets/LICENSE` now does contain "android_alarm_manager".
7. Check that `LICENSE` file does not contain "Bui": `grep Bui build/app/intermediates/flutter/release/flutter_assets/LICENSE`
8. Add `flutter_local_notifications: any` to the pubspec.yaml file's `dependencies` section.
9. `flutter build apk`
10. Check that `build/app/intermediates/flutter/release/flutter_assets/LICENSE` now does contain "Bui".
11. Run `flutter clean; flutter build apk;
12. Check that `build/app/intermediates/flutter/release/flutter_assets/LICENSE` now does contain "Bui".

For some reason, steps 10 and 12 give different results.

**Comment by jonahwilliams** [comment]
I think this is another manifestation of https://github.com/flutter/flutter/issues/16604. let me double check that disabling all of the build caching fixes it.
