### ISSUE TITLE
fontvariatiomsettings not found , ttc index not found

### ISSUE THREAD

**Issue by Atominac** [flutter/flutter#27726]
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  D:\my work space\Flutter\conexo\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/fontVariationSettings not found.
  D:\my work space\Flutter\conexo\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:101: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by zoechi** [comment]
Duplicate of #27106

**Comment by Atominac** [comment]
flutter_local_notifications:
this was creating the issue
i used the older version and it worked fine

older version
  flutter_local_notifications: 0.4.4+1
