### ISSUE TITLE
WebView for Flutter - Allow the POST of data on initial URL (instead of a GET)

### ISSUE THREAD

**Issue by alsocalledchris** [flutter/flutter#27730]
Allow the initial URL to be a POST request instead of a GET request.

Should accept POST data.

**Comment by zoechi** [comment]
Can you elaborate on the use case?
Why not just sending the POST request from dart code without WebView?

**Comment by alsocalledchris** [comment]
This is useful when sending sensitive information to a website that responds with a web page that the user then may interact with - e.g. when bridging a session from between a flutter app and the main website shown in the webview to perform other operations.

Apps do something like this to allow the user to manage additional settings in the main website not offered in their mobile app. 

A GET request limits you to passing parameters in the query string which is not as secure as via a POST body request (GET request with params could be stored in various logs).

**Comment by gitanjal** [comment]
In our case , we need to authenticate the user before presenting some content in the WebView. The postUrl() of WebView was being used in Android.

**Comment by luckmlc** [comment]
@amirh @mklim .

I also have this requirement in my project.  I want to set the parameters of the Post data when I open the webview request url.  
I hope that the flutter development team can consider adding this feature. thanks.

**Comment by mapacheverdugo** [comment]
Same here, I need this feature.

This is my actual (and improvised) solution:

```dart
  @override
  Widget build(BuildContext context) {
    return WebviewScaffold(
      withJavascript: true,
      appCacheEnabled: true,
      url: new Uri.dataFromString(_loadHTML(), mimeType: 'text/html').toString(),
    );
  }

  String _loadHTML() {
    return r'''
      <html>
        <body onload="document.f.submit();">
          <form id="f" name="f" method="post" action="YOUR_POST_URL">
            <input type="hidden" name="PARAMETER" value="VALUE" />
          </form>
        </body>
      </html>
    ''';
  }
```

**Comment by BryanNeuberger** [comment]
Is there an update on if or when this feature will be implemented? I too am needing this feature.

**Comment by omarhuss** [comment]
> Same here, I need this feature.
> 
> This is my current temporary (and improvised) solution:
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     return WebviewScaffold(
>       withJavascript: true,
>       appCacheEnabled: true,
>       url: new Uri.dataFromString(_loadHTML(), mimeType: 'text/html').toString(),
>     );
>   }
> 
>   String _loadHTML() {
>     return r'''
>       <html>
>         <body onload="document.f.submit();">
>           <form id="f" name="f" method="post" action="YOUR_POST_URL">
>             <input type="hidden" name="PARAMETER" value="VALUE" />
>           </form>
>         </body>
>       </html>
>     ''';
>   }
> ```

Any idea on how to pass headers in the post request?

**Comment by marinat** [comment]
Any workaround?

**Comment by marinat** [comment]
@omarhuss maybe use https://pub.dev/packages/html?

**Comment by arnaudelub** [comment]
Meanwhile, you can try [flutter_inappwebview](https://github.com/pichillilorenzo/flutter_inappwebview),

**Comment by magicleon94** [comment]
Thank you. This workaround saved my life!

**Comment by mikylucky** [comment]
I'd like this feature too!

**Comment by alwaysadapa** [comment]
In security stand point this is very essential feature where application transition into webview for additional functionality while maintaining state.Initial GET request, would always need to carry sensitive information and token in such cases which are logged and cached as a result of this.I see this is opened for more than a year, please take it on priority.

**Comment by satishsoni777** [comment]
is anyone has implemented this feature I also need to implement this, please help

**Comment by atta1234** [comment]
> Same here, I need this feature.
> 
> This is my current temporary (and improvised) solution:
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     return WebviewScaffold(
>       withJavascript: true,
>       appCacheEnabled: true,
>       url: new Uri.dataFromString(_loadHTML(), mimeType: 'text/html').toString(),
>     );
>   }
> 
>   String _loadHTML() {
>     return r'''
>       <html>
>         <body onload="document.f.submit();">
>           <form id="f" name="f" method="post" action="YOUR_POST_URL">
>             <input type="hidden" name="PARAMETER" value="VALUE" />
>           </form>
>         </body>
>       </html>
>     ''';
>   }
> ```

Hello can you please help me , i have web view and that has only  paypal pay now button, so i want to pas the price from flutter to paypal amount value,,,but i m not sure please help

**Comment by rlechetaudemy** [comment]
Google, I need this too. And it so simple to do, why don't you guys add the postUrl?

**Comment by dicroce** [comment]
I need this too. Please do this.

**Comment by chakAs3** [comment]
> Thank you. This workaround saved my life!

Hi magicleon94, how this workaround saved your life, i tried InAppWebview.postUrl(url , datalist ) 
but i get now post on the server the request is empty, can give me an example how you implemented it  Thanks

**Comment by MuthuSubramaniam** [comment]
> > Thank you. This workaround saved my life!
> 
> Hi magicleon94, how this workaround saved your life, i tried InAppWebview.postUrl(url , datalist )
> but i get no post on the server the request is empty, can give me an example how you implemented it Thanks

same for me too :-(

if you get any solution kindly assist me.Thanks

**Comment by wersa** [comment]
Hi, after some reviews for this problem on my app, I thought that I can send my data with Header. The Webview and Inappwebview plugins have an optional set header parameter, so we can set the header on Inappwebview plugin like this:
`initialHeaders: {
      //'Authorization': 'Basic ' + base64Encode(utf8.encode('$username:$password')),
      'mydata': '$mydata'
},`
Then get the header data and retrieve "mydata" value on my webpage.

**Comment by colabra1000** [comment]
I am also in need of the webview post request in my app. it would be very helpful if this feature can be added asap.

**Comment by srockytfl** [comment]
Also need this for more than 2,5 years and nothing until now. A lot of companies use webview post for security and Flutter doesn't implement this simple functionality until now, it's a shame, sorry.

**Comment by mustafaersoyer** [comment]
I need this too. Please do this.

**Comment by Melak12** [comment]
I need this tooooo. pls!

**Comment by yashwp** [comment]
Any update tick-tick December is here?

**Comment by Melak12** [comment]
I managed it by using another package called Flutter In-App View: https://pub.dev/packages/flutter_inappwebview

**Comment by wahidanvary** [comment]
> I managed it by using another package called Flutter In-App View: https://pub.dev/packages/flutter_inappwebview

how? can you explain please?

**Comment by yashwp** [comment]
My application is using webview_flutter heavily for all of it. Now of this missing functionality, I have to install this package!

**Comment by Melak12** [comment]
![image](https://user-images.githubusercontent.com/45941116/103003684-456f1d00-4542-11eb-95eb-c772ce234df6.png)

**Comment by osmanrami** [comment]
Hello, this feature is important, It can help me implement 3ds payment security layer in order to prevent fraudulent payments, I need to redirect users to the bank website with data.

**Comment by akyazilim61** [comment]
@Melak12  is not working .. you share please fullcoded(toUtfEncoded)

**Comment by ischyron** [comment]
Need this one.

**Comment by demchiva** [comment]
Need this feature.

**Comment by gururajahegde** [comment]
Need this feature, even in flutter web

**Comment by srockytfl** [comment]
neet this too.

**Comment by rirjkl19** [comment]
I need this too. Allowing Post data upon app start in `void main()` when using a flutter web

**Comment by snghnishant** [comment]
> This is useful when sending sensitive information to a website that responds with a web page that the user then may interact with - e.g. when bridging a session from between a flutter app and the main website shown in the webview to perform other operations.
> 
> Apps do something like this to allow the user to manage additional settings in the main website not offered in their mobile app.
> 
> A GET request limits you to passing parameters in the query string which is not as secure as via a POST body request (GET request with params could be stored in various logs).

Yup I also need this for our company's mobile app where we have to redirect the users to a webpage with some encrypted data as a post request and the response will be an HTML page that's to be loaded in webview from the other service that we are integrating for further authorization that can only happen in that previously loaded HTML from our post request data.

**Comment by Enlacecode** [comment]
We also need this in one of our apps.

Hey Flutter team, please implement this, this feature was requested more than 2 years ago.

**Comment by nicol-ograve** [comment]
Same here

**Comment by ifin2000** [comment]
> > I managed it by using another package called Flutter In-App View: https://pub.dev/packages/flutter_inappwebview
> 
> how? can you explain please?

https://stackoverflow.com/questions/66396219/how-to-post-data-to-url-in-flutter-webview

**Comment by stuartmorgan** [comment]
This is fixed by the PRs above.
