### ISSUE TITLE
Is it possible to disable text scaling in BottomNavigationBar?

### ISSUE THREAD

**Issue by mattermoran** [flutter/flutter#27739]
So I'm using BottomNavigationBar in my app but I would like to not have text scaled on selected tabs. Is there a way to do that?
![image](https://user-images.githubusercontent.com/29712386/52529876-5f7c2980-2d35-11e9-8595-32ad506872f4.png)

**Comment by DogeAmazed** [comment]
There is no built-in way to do that. You only can edit `bottom_navigation_bar.dart` by yourself and set it to an static font size.
