### ISSUE TITLE
Add capability to build third-party interfaces outside the engine repo

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#2773]
In sky/BUILD.gn there's a comment:

    # TODO(mpcomplete): These are temporary until we move
    # third-party interfaces out of the engine repo.

These interfaces aren't included in apps unless the appropriate gn flags is passed when building engine, but they're still adding complexity to the main engine repo, and it would be better to be able to build them out of a separate repo somehow.

**Comment by Hixie** [comment]
This is fixed now right?
