### ISSUE TITLE
ShaderMask unexpected positioning behaviour

### ISSUE THREAD

**Issue by gabrielhuff** [flutter/flutter#27741]
Might be related to #10424, but I'm getting a weird behaviour when using `ShaderMask`.

I'd expect the following code to render a red square masked by a radial gradient centered on its top left corner:

```dart
void main() => runApp(
  Center(
    child: SizedBox(
      width: 250,
      height: 250,
      child: ShaderMask(
        blendMode: BlendMode.dstIn,
        shaderCallback: (Rect r) =>
            RadialGradient(
                center: Alignment.topLeft,
                colors: [Colors.black, Colors.black38]
            ).createShader(r),
        child: Container(color: Colors.red,),
      ),
    ),
  ),
);
```

However this is what I'm getting:

<img width="286" alt="screen shot 2019-02-10 at 11 21 00" src="https://user-images.githubusercontent.com/19377340/52532500-7e26f400-2d26-11e9-8c40-2b4099d685d3.png">

It looks like the distance between the **gradient center and the top left corner of the square** is the same as the distance between the **top left corner of the square and the top left corner of the screen**.

With such hypothesis in mind, modifying the previous code to:

```dart
void main() => runApp(
  Center(
    child: SizedBox(
      width: 250,
      height: 250,
      child: ShaderMask(
        blendMode: BlendMode.dstIn,
        shaderCallback: (Rect r) =>
            RadialGradient(
                center: Alignment.topLeft,
                colors: [Colors.black, Colors.black38]
            ).createShader(r.translate(-r.left, -r.top)), // CHANGE: move to origin
        child: Container(color: Colors.red,),
      ),
    ),
  ),
);
```

Results in:

<img width="284" alt="screen shot 2019-02-10 at 11 20 11" src="https://user-images.githubusercontent.com/19377340/52532552-8cc1db00-2d27-11e9-920b-05cc3f87c5ad.png">

Which looks like what I'd be expecting. It seems like the `Rect` instances passed to `shaderCallback` are not relative to its enclosing `ShaderMask` widget.

**Comment by sir-boformer** [comment]
I can confirm this issue. Problem is, if you change it now, you will break code that depends on this broken behavior, though I'm all for it!

**Comment by vitor-gyant** [comment]
Just hit on this wall too. I'd go for a break change but make the behaviour inline with the remaining apis.

**Comment by danieldai** [comment]
This problem still exists in version 1.7.8, my approach to transforming the coordinate relative to the target object

``` dart
              shaderCallback: (Rect bounds) {
               // transfrom coordinate manually 
                var right = bounds.right - bounds.left;
                bounds = Rect.fromLTRB(0, bounds.top, right, bounds.bottom);

                return LinearGradient(
                      begin: Alignment.centerLeft,
                      end: Alignment.centerRight,
                    tileMode:TileMode.repeated,
                      stops: [
                    0,
                    0.1,
                    0.9,
                        1
                  ],
                      colors: [
                    Colors.white.withAlpha(0),
                    Colors.white,
                        Colors.white,
                        Colors.white.withAlpha(0),
                  ]).createShader(bounds);},
```

**Comment by darshankawar** [comment]
Tested code sample on latest Stable on Android device and confirmed that I get below positioning behavior, which is what was expected mentioned [here](https://github.com/flutter/flutter/issues/27741#issue-408522322).

![27741](https://user-images.githubusercontent.com/67046386/96586351-7e9acf00-12fe-11eb-812b-af0b63b9308c.png)

Closing this as fixed. If you think this was closed by mistake or should be kept open, please write in comments and I'll reopen.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 84f3d28555 (4 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0

• No issues found!

```

</details>
