### ISSUE TITLE
Incompatible dependencies and abandoned projects problem

### ISSUE THREAD

**Issue by audkar** [flutter/flutter#27748]
### Problem ###
Most open source Flutter libraries are created and maintained by single individuals. Often these libs are born as side projects, experiments etc. After some time their dependencies needs to be updated, but that requires periodical manual work. As result a lot of libraries regularly becomes incompatible.

Android support library (now AndroidX), Android Play services and Dart itself. Most applications and libraries depends on them. And after every major release all flutter libraries becomes incompatible. Even library implementation code would work by itself, dependency versions need to be bumped.
### Suggestion ###
1. Collaborate with existing dependency management service (e.g. https://dependabot.com/) or create similar automation tool for open source flutter libraries.
2. Teach developers how releases can be automated. codemagic.io is nice collaboration. For releasing applications... Maybe that can also be adapted for releasing libraries. A lot of devs don't know how CI/CD could reduce amount of work on maintaining projects.

Current situation is so bad that we have to fork almost every our projects' dependency repository and bump versions our-self.

**Comment by Hixie** [comment]
In principle, Dart's `pub` package system supports this out of the box: you specify your version constraints as "anything from this version and up until a breaking change release", and `pub` solves all the constraints for you.

I guess you're saying that actually it's possible to upgrade even through "breaking changes" without actually breaking, usually?

**Comment by audkar** [comment]
> I guess you're saying that actually it's possible to upgrade even through "breaking changes" without actually breaking, usually?

Partially... 

> Dart's `pub` package system supports this out of the box

Flutter also includes Android&iOS native dependencies (e.g. Google services). Major versions of these libraries have to match too. So work required for bumping versions of 3 platforms adds up.

npm/yarn cli commands for updating dependencies are quite good. It would be nice to have something similar with `pub`. ([script for pub](https://github.com/holyspidoo/PubSpecCheck)) exists. That can be improved. But even that is manual and tedious work to re-release flutter package every time Google service library updates.

Concept of https://dependabot.com is cool. It would be great if similar tool would exist which could auto create PRs for all three package systems (pub, gradle, cacaopods).

**Comment by mklim** [comment]
@talamaska requested something similar in [another comment](https://github.com/flutter/flutter/issues/27128#issuecomment-462926345):

> Just my 2 cents after reading the guide for migration. It would be nice if pub.dartlang showed the supported android and ios version of the plugin. I expect similar issues to happen when ios 13 comes out.

**Comment by Hixie** [comment]
cc @mit-mit @kevmoo

**Comment by kf6gpe** [comment]
cc @csells Chris, what do you think about this as far as the ecosystem work we're doing is concerned? I'm tagging this "plugin", because it's loosely related to plugins, although it's as much a process thing as it is a code thing, probably, in the long run.

**Comment by stuartmorgan** [comment]
Since Dart dependabot support has been implemented, and `pub.dev` supports automated releases now, I think that to the extent that this is actionable its's complete. Given that, closing.
