### ISSUE TITLE
PageView doesn't do hit testing right with padding (SliverFillViewport hit test issue?)

### ISSUE THREAD

**Issue by Suraj-Tiwari** [flutter/flutter#27744]
`InkWell` will not work if `_file.length` is 1;
but it will work if length is greater than or equal to 2; 
```dart
  Container(
    height: 200,
    child: PageView.builder(
      itemCount: _file.length,
      controller: PageController(viewportFraction: 0.4),
      itemBuilder: (context, index) {
        return Card(
          child: InkWell(
            onTap: () => _picImage(),
            child: Center(
              child: Icon(
                Icons.add,
                size: 40,
              ),
            ),
          ),
        );
      },
    ),
  )
```

```
flutter doctor -v

[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17758.1], locale en-AS)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Suraj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
```

PS: Using Android Studio Not Intellij for Flutter

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
> not working properly

Please elaborate what that means.

**Comment by Suraj-Tiwari** [comment]
@zoechi  Sorry for incomplete code. 
Here are the following point to test in code: 

- if _data.length = 1 Inkwell will not work (first only card with + sign)
- in that case you can use button `Add` to add element
- after that _data.length > 1 then after that Inkwell (first card with + sign) will start working. 

[please check this gist for complete code](https://gist.github.com/Suraj-Tiwari/2320e3ff973bab0cbbe3ec3b9498b3ef)

**Comment by zoechi** [comment]
@Suraj-Tiwari can you please make it a self-contained runnable example, incl imports and `main() {}` so that all I need to do is copy past in a new project and run.
Making assumptions what the missing code might look at your site is cumbersome and often leads to us testing different stuff than what causes errors for you.

**Comment by Suraj-Tiwari** [comment]
@zoechi  gist is updated https://gist.github.com/Suraj-Tiwari/2320e3ff973bab0cbbe3ec3b9498b3ef Please replace this code in main.dart

**Comment by zoechi** [comment]
Thanks for the reproduction!

Seems to be related to `viewportFraction`

`InkWell` only works in the area with the green arrows 

![image](https://user-images.githubusercontent.com/405837/52571129-434fb980-2e15-11e9-8d6f-f8a1f94a3692.png)

When I remove `viewportFraction` then it looks like

![image](https://user-images.githubusercontent.com/405837/52571098-33d07080-2e15-11e9-944b-079afcf55373.png)

and the tap will be recognized in the whole row.

Sorry, don't know how to fix or work around.

**Comment by Suraj-Tiwari** [comment]
Yes you are right. 
I'll try to have a look at source code if i found something i'll submit a PR

**Comment by Suraj-Tiwari** [comment]
@zoechi I found what is causing this issue but I'm not sure if this is right  (I've tested but no issue for me)

Here is a detailed reason why this was happening: 

![image](https://user-images.githubusercontent.com/22210490/52812708-1eca3a80-30be-11e9-8727-85574aabed02.png)

as you can see the SilverFillViewport width is 40% of screen width because view port fraction is 0.4
so it did it's job. and that area is clickable

Width of card is equal to view port but it's in center instead of left side of the screen where is SilverFillViewport 

so i investigated and found this line which gives padding to that card 

https://github.com/flutter/flutter/blob/e99c881f8d0e63042af6e2a3f6182c3ca6967442/packages/flutter/lib/src/rendering/sliver_fill.dart#L60

if i replace that code with following line 
`double get _padding => (1.0 - 1.0) * constraints.viewportMainAxisExtent * 0.5;`
which is equal to:
`double get _padding => 0`

This is how it looks after that, and this works perfectly. 

![image](https://user-images.githubusercontent.com/22210490/52813372-a49ab580-30bf-11e9-8c29-5d8499696d9d.png)

I can submit a pr with more accurate solution if this is correct and will not cause any issue.

**Comment by zoechi** [comment]
PRs get more attention than issues. I'd suggest you create one and wait for feedback.

**Comment by Suraj-Tiwari** [comment]
#27958

**Comment by eagle-design** [comment]
I have the same issue only for first Slide, 
inkwell is not clickable while first slide is active.

**Comment by Hixie** [comment]
@LongCatIsLooong I hear you have a PR that will fix this?

@mjohnsullivan which customer is this for?
