### ISSUE TITLE
can I change indicator's color in GoogleMap? 

### ISSUE THREAD

**Issue by inthewalter** [flutter/flutter#27745]
I'm using `google_maps_flutter: ^0.0.3+3`.
And now, my code
```dart
GoogleMap(
  options: GoogleMapOptions(
    trackCameraPosition: true,
    myLocationEnabled: true,
  )
)
```
I've coded `myLocationEnable` option into `true`. 
So, I can watch my location as blue indicator.

Can I change the blue indicator to another color or shape?

**Comment by DogeAmazed** [comment]
Google Map`s built in indicator cannot be changed (also not on native, so thats not the Flutter library fault). The only option for you is to listen to position changes and place your own marker on the users position.

**Comment by inthewalter** [comment]
@DogeAmazed Thank you :D
