### ISSUE TITLE
How to disable multi-touch

### ISSUE THREAD

**Issue by hahafather007** [flutter/flutter#27758]
Is there any way to disable multi-touch globally?

**Comment by kangwang1988** [comment]
@hahafather007 
I think it should be done in the native side.
In iOS, See: https://developer.apple.com/documentation/uikit/uiview/1622519-multipletouchenabled
In Android, maybe: https://stackoverflow.com/questions/8570982/disable-or-prevent-multitouch-in-activity

**Comment by wuxuan2811** [comment]
@kangwang1988 in Android,din't work

**Comment by wuxuan2811** [comment]
@kangwang1988 In Android,didn't work

**Comment by tboyce021** [comment]
Same issue. Doesn't seem to work on Android.
