### ISSUE TITLE
Flutter API usage problem

### ISSUE THREAD

**Issue by Rickyballs** [flutter/flutter#27756]
1.How to use `.9` image adaptation screen？It alaways shows the black lines in picture border.
2.How to set the line spacing of text？
3.How to scroll to precise position in listview without calculating pixel offset?
4.As long as edittext specifies the maximum height, it will reach that height immediately, instead of the text entered by the user reaching that height.We hope to have the same effect as the Android native edittext.
5.Flutter's silver appbar assembly needs to specify the height of the folded area, but many times we don't know how high it is.
6.Flutter's text component is easy to overflow, especially between two components.My calculator is going to break because of frequent calculations.

**Comment by zoechi** [comment]
Please create one issue per topic. Multi-topic can't be maintained in GitHub.

To investigate an issue we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
