### ISSUE TITLE
google_maps_flutter into existing project

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#27760]
Hello, I am trying to integrate [google_maps_flutter](https://pub.dartlang.org/packages/google_maps_flutter) into an existing project.

The maps component works only when running directly the `my_flutter` project on the device.
When I try to run the flutter module from an existing app, the maps component is empty and no logs are available (or usable). 

(Flutter doctor does not output any errors).

I've followed the steps for both the `my_flutter/.iOS` and `my_flutter/.android` projects and I also followed them for the projects that integrate `my_flutter`.

 
```
Android #
Specify your API key in the application manifest android/app/src/main/AndroidManifest.xml:

<manifest ...
  <application ...
    <meta-data android:name="com.google.android.geo.API_KEY"
               android:value="YOUR KEY HERE"/>
iOS #
Specify your API key in the application delegate ios/Runner/AppDelegate.m:

#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
#import "GoogleMaps/GoogleMaps.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GMSServices provideAPIKey:@"YOUR KEY HERE"];
  [GeneratedPluginRegistrant registerWithRegistry:self];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
@end
Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.
```

 

I suspect that I what I am trying is not possible yet with the current version on the library and it may come as a new feature when the library is not in "developer preview".

**Comment by kangwang1988** [comment]
@durduman 
Can you try the latest master?
If you can reproduce this issue using the latest master, a minimal demo project which can reproduce this issue would be helpful.

**Comment by durduman** [comment]
@kangwang1988 
- I have _pulled from master_ to be up to date, 
- ran _flutter clean_,
- ran _packages upgrade_,
- redid the steps of integrating **google_maps_flutter** (manifest + InfoPlist & GSMKeyCall + pod install)

The result hasn't changed:
- maps is not visible when using **my_flutter** as an integrated part a previous existing project;
- Other widgets behave as expected;
- When building & running the **my_flutter** directly (not through a iOS/Android project) **google_maps_flutter** works as expected.

**Comment by durduman** [comment]
Found that I had to:

`    GeneratedPluginRegistrant.register(with: flutterViewController.pluginRegistry());`
