### ISSUE TITLE
Flutter app giving errors during build saying that - Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by aditya234** [flutter/flutter#27766]
Following is the full error messages that I receive on app crash.
```
/Users/adityas/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/ebc616362c7a8fb07eb4795d71e6ed37/res/values/values.xml:133:5-70: **AAPT: error: resource android:attr/fontVariationSettings not found**.

/Users/adityas/.gradle/caches/transforms-1/files-1.1/core-1.0.1.aar/ebc616362c7a8fb07eb4795d71e6ed37/res/values/values.xml:133:5-70: **AAPT: error: resource android:attr/ttcIndex not found.**

         *********************************************************
WARNING: This version of firebase_messaging will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

Please help me debug this issue. I am not able to build my app, not even for once.
I happened suddenly around 1 week ago. 
Please suggest me a workaround or a reason as to why it may be happening.

**Comment by jaiswalshubham84** [comment]
i am facing the same issue, i have tried changing compileSdkVersion to 28 also minSdkVersion to 21.
but nothing work.

**Comment by zoechi** [comment]
Changing `compileSdkVersion` and `minSdkVersion` is not enough. 
See the link for example in https://pub.dartlang.org/packages/firebase_core#030 [also migrate](https://developer.android.com/jetpack/androidx/migrate)

**Comment by aditya234** [comment]
Nope, still giving errors.
I by the link mentioned by @zoechi I have added these lines to my gradle.properties file

```
android.useAndroidX=true
android.enableJetifier=true
```
I am also using version 2.4 of the firebase_core plugin.
But still, the error is intact.
Can you please suggest something else, which could work.
Any help would be appreciated.

**Comment by zoechi** [comment]
@aditya234 

> I am also using version 2.4

what for?

The latest version is `0.3.0+1`. Versions before `0.3.0` do not support AndroidX.

**Comment by aditya234** [comment]
@zoechi 
I am now using the latest version 0.3.0+1 of firebase_core plugin. 
But the issue is still intact.
Can you please give me an insight into "Why this error keeps coming?"

**Comment by zoechi** [comment]
You need to upgrade all your plugins.
Did you check the link printed in the error message? (https://goo.gl/CP92wY)?

I'm going to close because this is essentially a support request that should be asked in one of the other channels listed in http://flutter.io/support .

**Comment by aditya234** [comment]
Okay 
Thanks for your cooperation
