### ISSUE TITLE
Build times really long when adding cloud_firestore to dependencies

### ISSUE THREAD

**Issue by jrm2k6** [flutter/flutter#27771]
Hi,

When integrating some firebase related plugins, I can see that my build times become very long.

For example:

```
  cupertino_icons: ^0.1.2
  flutter_svg: 0.8.2
  rxdart: 0.20.0
  firebase_messaging: ^2.0.0
```

XCode build time is: 16482ms

After adding `cloud_firestore: ^0.9.0` to my pubspec.yaml file, it becomes: 196667ms.

Any ideas why/what I need to do to go back to build times making the experience nicer?

flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.0.0 at /Users/jrm2k6/Workspace/Perso/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jrm2k6/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • Jeremy Dagorn’s iPhone • fb37863e6935c2a64a521a29906cd82a98e3846b • ios • iOS 12.1.2

• No issues found!
```

**Comment by jrm2k6** [comment]
@zoechi I see that you applied some labels to it. Should I just suck it for now and deal with the long build times or there is a workaround I can use?

**Comment by zoechi** [comment]
I don't know if the increase is expected or not or how to fix or work around.
I have no influence when a specialist will have a closer look.
There are a lot of open issue so I wouldn't expect an immediate response.

**Comment by jrm2k6** [comment]
Sounds good, thanks for the answer 👍

**Comment by jonahwilliams** [comment]
I think this is the same issue as https://github.com/flutter/flutter/issues/29562

**Comment by orestesgaolin** [comment]
I have similar issue. My iOS build time on Bitrise CI increased after adding cloud_firestore from 16 minutes to over 45 minutes because first there's a flutter build and then Xcode build&archive required. Is there any solution to this?

**Comment by Hixie** [comment]
45 minutes seems excessive, certainly. (So does 16 minutes.)

Do we have any idea what's happening during those 45 minutes? e.g. does Xcode report what it's doing? Can you enable a verbose mode?

**Comment by orestesgaolin** [comment]
Seems like the main reason is pod installation and compilation, especially of the cloud_firestore. Potential explanation and solution was posted in [this PR](https://github.com/FirebaseExtended/flutterfire/pull/1563) in FirebaseExtended. [This issue](https://github.com/FirebaseExtended/flutterfire/issues/349) also discusses the problem.

This long build times is one of the most serious problems right now. It costs a lot of time and nerves.

**Comment by Coltuxumab** [comment]
Any progress on this? My build time went from 48s with the following:

  sqflite: ^1.1.6
  path_provider: ^1.2.0
  flutter_slidable: "^0.5.3"
  shared_preferences: ^0.5.6+3
  csv: ^4.0.3
  auto_size_text: ^2.1.0
  flutter_speed_dial: ^1.2.5
  pdf: ^1.6.0
  printing: ^3.3.0
  intl: ^0.16.1
  in_app_purchase: ^0.3.1+2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3

To 351.5s when I added firestore:
  cloud_firestore: ^0.13.4+2

Just updated to the latest flutter earlier this AM and it cut the time down by a bit, but 351s is a long time to wait every time I want to rebuild.

**Comment by nohli** [comment]
It seems they‘ve found a workaround in:

https://github.com/FirebaseExtended/flutterfire/issues/349

**Comment by Coltuxumab** [comment]
Thanks! Just because people may find this and not that link:

BEFORE:
Running pod install...                                             20.3s
Running Xcode build...
Xcode build done.                                           266.1s

AFTER:
Running Xcode build...
Xcode build done.                                           34.7s

Went to ios/Podfile, found the bottom most block and changed it to this (only one line is different, see comment ##):

```
post_install do |installer|
  installer.generated_projects.each do |target| ## Must use `installer.generated_projects` instead of `installer.pods_project.targets`
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Then, just BEFORE that, I added this:

```
# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true
```

**Comment by vspiridonov** [comment]
From the official docs:
# ...
target 'Runner' do
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.26.0'
# ...
end

**Comment by Hesamedin** [comment]
I don't have a noticeable problem when I build on my laptop. However, the situation on CI is different for iOS.
I am using the Azure platform for CI/CD stuff.

I have/had these dependencies in my pubspec.yaml file:
```
firebase_auth: ^0.18.4+1      # https://pub.dev/packages/firebase_auth
cloud_firestore: ^0.14.4      # https://pub.dev/packages/cloud_firestore
firebase_storage: ^5.2.0      # https://pub.dev/packages/firebase_storage
```

**Android** 
It takes around 4 minutes on Azure with or without the above dependencies to build apk file. On my laptop, it is much faster, around 1 minute.

**iOS**
It takes around 4 minutes on my laptop to build for ios. My MacBook is the latest one with 64GB of RAM, Processor 2.4GHz 8-core, intel core i9. The fan of the laptop works hard in this period

It takes around 25 minutes on Azure to build for iOS with the above dependencies.
It takes around 10 minutes on Azure to build for iOS without the above dependencies.

I have a task to export ipa after the build.
It takes around 25 minutes on Azure to export ipa with the above dependencies.
It takes around 5 minutes on Azure to export ipa without the above dependencies.

**Comment by Hesamedin** [comment]
This issue is probably similar to https://github.com/FirebaseExtended/flutterfire/issues/2751.

**Comment by stuartmorgan** [comment]
Closing as out of scope; long build times with a specific third-party plugin would need to be resolved by the plugin's developers.
