### ISSUE TITLE
Previously selected tab cannot be deselected after resuming an app

### ISSUE THREAD

**Issue by akozin** [flutter/flutter#27770]
Reproduced in Android. 
### Description
Using  **BottomNavigationBar** example code from https://docs.flutter.io/flutter/material/BottomNavigationBar-class.html leads to unexpected behaviour in Android simulator. 

### How to reproduce

1. Tap and hold any tab.
2. While holding the tab press CMD-Shift-H while using an emulator.
3. Get back to the application.
4. Make sure that the tab is looking like it is still being tapped on.
5. Try to select another tab. Previously selected tab should be still selected. 

### Flutter doctor
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (2 available)
```

### Screenshot
![screenshot_1549895517](https://user-images.githubusercontent.com/3602990/52569790-0ab6dc80-2e23-11e9-987e-0a9f7c7543be.png)

**Comment by TahaTesser** [comment]
Hi @akozin 
Are you still experiencing this issue? 

If yes, Can you please provide your `flutter doctor -v` with latest `stable` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by akozin** [comment]
Hi @TahaTesser .
Thanks for you comment. 
I have just checked and I can state there are no any problems.
Everything works. Thanks!

**Comment by TahaTesser** [comment]
Hi @akozin 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
