### ISSUE TITLE
text_painter: NoSuchMethodError: The getter 'offset' was called on null.

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#27772]
Flutter doctor

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14 18A391, locale en-BY)
    • Flutter version 1.1.8 at /Users/r1zzu/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/r1zzu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/r1zzu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/r1zzu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone 6 • D5B9AE18-0DA0-4F13-8CAA-10CB70DAD228 • ios • iOS 12.1 (simulator)
```

Error

```
text_painter.dart in TextPainter.getOffsetForCaret at line 545
editable.dart in RenderEditable.getLocalRectForCaret at line 1050
editable_text.dart in EditableTextState._onFloatingCursorResetTick at line 683
listener_helpers.dart in _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners at line 124
animation_controller.dart in AnimationController._tick at line 697
ticker.dart in Ticker._tick at line 228
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback at line 990
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<fn> at line 906
Called from: libcompact_hash.dart in __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame at line 904
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame at line 834
```

Got this error in sentry, however can't reproduce it locally

I'm calling `setState` when user submits content of `TextField` with consecutive `textInputController.clear();`

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by lesnitsky** [comment]
@zoechi I'd love to provide runnable reproduction, but I can't reproduce it locally myself :) But anyways bugs have to be fixed 😏 

I dived into flutter source code, and seems like `updateFloatingCursor` of `EditableText` isn't called with `FloatingCursorDragState.Update` state, so `_lastTextPosition` stays uninitialized. Maybe it worth initializing it with some default `TextPosition`?

**Comment by zoechi** [comment]
> But anyways bugs have to be fixed

It's just much more difficult to find a proper fix if it is not clear how to reproduce.

If you can come up with a minimal reproduction, that would be very helpful.

**Comment by mulderpf** [comment]
I have seen the same error being logged in Sentry with no way to currently reproduce this locally.  Due to the failure happening completely outside my code (my stack trace is 100% the same), I wouldn't even know where to begin to recreate.  However...I can help with some other information which may be helpful:

1. This issue only happened to two (different) users.
2. For both users, the exception was thrown 10 times each (all at the same time for each)
3. Both users were iPhone users - considering that I have fewer than 100 iPhone users a day and more than 2500 Android users a day, this suggests to me that this might be an iPhone only problem
4. Both users were using iOS 12.1.2

I last saw this issue occur on about 14 days ago.  I believe that after this point I switched from dev channel to beta, but due to the low occurrence, it might just not have happened again, rather than having been fixed.

Hopefully some of this could be helpful.

**Comment by nashfive** [comment]
Ouch...
I've got the exact same error in my sentry report too. 
I can't really pinpoint what's causing this and how and I can't really reproduce it (yet).

```
NoSuchMethodError: NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
  File "text_painter.dart", line 572, in TextPainter.getOffsetForCaret
  File "editable.dart", line 1126, in RenderEditable.getLocalRectForCaret
  File "editable_text.dart", line 839, in EditableTextState._onFloatingCursorResetTick
  File "listener_helpers.dart", line 126, in _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners
  File "animation_controller.dart", line 751, in AnimationController._tick
  File "ticker.dart", line 228, in Ticker._tick
  File "binding.dart", line 990, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 906, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<fn>
  File "compact_hash.dart", line 367, in __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
  File "binding.dart", line 904, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame
  File "binding.dart", line 834, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame
  File "zone.dart", line 1136, in _rootRunUnary
  File "zone.dart", line 1029, in _CustomZone.runUnary
  File "zone.dart", line 931, in _CustomZone.runUnaryGuarded
  File "hooks.dart", line 223, in _invoke1
  File "hooks.dart", line 162, in _beginFrame
```

**Comment by Maleandr** [comment]
Same for us. It is happening in production and we cannot reproduce it locally.

**Comment by matthewlloyd** [comment]
Another of the same reported by Crashlytics. I see 78 of these affecting 12 users, all iOS 12, all iPhones. For those users who are affected it seems that it may be repeatable, so perhaps it is related to some display or accessibility settings.

```
The following NoSuchMethodError was thrown while notifying listeners for AnimationController:
The getter 'offset' was called on null.
Receiver: null
Tried calling: offset

When the exception was thrown, this was the stack:
#0      TextPainter._computeCaretMetrics (package:flutter/src/painting/text_painter.dart:642)
#1      TextPainter.getOffsetForCaret (package:flutter/src/painting/text_painter.dart:613)
#2      RenderEditable.getLocalRectForCaret (package:flutter/src/rendering/editable.dart:1215)
#3      EditableTextState._onFloatingCursorResetTick (package:flutter/src/widgets/editable_text.dart:966)
#4      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:750)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228)
#7      _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012)
#8      _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928)
#9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367)
#10     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926)
#11     _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856)
#15     _invoke1 (dart:ui/hooks.dart:234)
#16     _beginFrame (dart:ui/hooks.dart:172)
(elided 3 frames from package dart:async)
```

**Comment by flenairMacif** [comment]
Same error for me:

Error caught by animation library, thrown while notifying listeners for AnimationController. NoSuchMethodError: The getter 'offset' was called on null. Receiver: null Tried calling: offset The AnimationController notifying listeners was:   AnimationController#5261a(▶ 0.144)
0      TextPainter._computeCaretMetrics (package:flutter/src/painting/text_painter.dart:610) 
1      TextPainter.getOffsetForCaret (package:flutter/src/painting/text_painter.dart:581) #34040 
2      RenderEditable.getLocalRectForCaret (package:flutter/src/rendering/editable.dart:1215) #3      EditableTextState._onFloatingCursorResetTick (package:flutter/src/widgets/editable_text.dart:957) 
4      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126) 
5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:750) 
6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228) 
7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012) 
8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928) 
9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367) 
10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926) 
11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856) 
15     _invoke1 (dart:ui/hooks.dart:233) 
16     _beginFrame (dart:ui/hooks.dart:172) (elided 3 frames from package dart:async)

**Comment by msangals** [comment]
We report our exceptions via Crashlytics and we faced the same exception:

`Non-fatal Exception: NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
0  ???                            0x0 _computeCaretMetrics + 768 (text_painter.dart:768)
1  ???                            0x0 getOffsetForCaret + 739 (text_painter.dart:739)
2  ???                            0x0 getLocalRectForCaret + 1228 (editable.dart:1228)
3  ???                            0x0 _onFloatingCursorResetTick + 1054 (editable_text.dart:1054)
4  ???                            0x0 notifyListeners + 124 (listener_helpers.dart:124)
5  ???                            0x0 _tick + 768 (animation_controller.dart:768)
6  ???                            0x0 _tick + 228 (ticker.dart:228)
7  ???                            0x0 _invokeFrameCallback + 1016 (binding.dart:1016)
8  ???                            0x0 handleBeginFrame.<fn> + 934 (binding.dart:934)
9  ???                            0x0 handleBeginFrame + 932 (binding.dart:932)
10 ???                            0x0 _handleBeginFrame + 866 (binding.dart:866)`

**Comment by chunhtai** [comment]
This updateFloatingCursor is only triggered when https://developer.apple.com/documentation/uikit/uitextinput/1614557-beginfloatingcursoratpoint?language=objc this set of callback are called.

I am not sure how to trigger those callbacks yet. I will keep digging

**Comment by danwulff** [comment]
@chunhtai I don't see this mentioned in the [Changelog](https://github.com/flutter/flutter/wiki/Changelog). Do you know if the fix has been released / what version it is in?
