### ISSUE TITLE
flutter has exited unexpectedly

### ISSUE THREAD

**Issue by MonaAhmed1** [flutter/flutter#27782]
C:\Users\MONA\Desktop\m\fapp>flutter run --verbose
[  +41 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +1 ms] executing: [C:\src\flutter\flutter\] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +2 ms] executing: [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +36 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 months ago
[   +1 ms] executing: [C:\src\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +39 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.0.0-0-g5391447fa
[ +164 ms] executing: C:\Users\MONA\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +27 ms] Exit code 0 from: C:\Users\MONA\AppData\Local\Android\sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:3
[ +290 ms] C:\Users\MONA\AppData\Local\Android\sdk\platform-tools\adb -s emulator-5554 shell getprop
[  +59 ms] ro.hardware = ranchu
[  +33 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[ +664 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +30 ms] Initializing gradle...
[   +2 ms] Using gradle from C:\Users\MONA\Desktop\m\fapp\android\gradlew.bat.
[  +94 ms] executing: C:\Users\MONA\Desktop\m\fapp\android\gradlew.bat -v
[+120429 ms] Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive
access to file: C:\Users\MONA\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip
                        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
                        at org.gradle.wrapper.Install.createDist(Install.java:48)
                        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
                        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +16 ms] "flutter run" took ١٢١٬٧٠٦ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: e0df5088ad2ec4be)
Crash report written to C:\Users\MONA\Desktop\m\fapp\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by kangwang1988** [comment]
```
[ +664 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[ +30 ms] Initializing gradle...
[ +2 ms] Using gradle from C:\Users\MONA\Desktop\m\fapp\android\gradlew.bat.
[ +94 ms] executing: C:\Users\MONA\Desktop\m\fapp\android\gradlew.bat -v
[+120429 ms] Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive
access to file: C:\Users\MONA.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip
at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
at org.gradle.wrapper.Install.createDist(Install.java:48)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```
It seems a pure gradle(network) problem.

**Comment by kangwang1988** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
