### ISSUE TITLE
Collect the number of clients opting out from Analytics

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/flutter#27786]
We currently do not know how many users opt out from the Analytics data collection, while it is important for us to understand how representative the sampled data we analyze is (to better interpret feature usage stats). 

Can we log those opt-out events?

Cc: @jonahwilliams

**Comment by InMatrix** [comment]
Cc: @blasten

**Comment by jonahwilliams** [comment]
This is done, right @zanderso ?

**Comment by zanderso** [comment]
Yes, this is done.
