### ISSUE TITLE
Re-enable "bare"-instructions dart vm optimization.

### ISSUE THREAD

**Issue by aam** [flutter/flutter#27787]
This issue tracks reenabling of dart vm bare instructions optimization.

It was originally disabled in https://github.com/flutter/flutter/pull/27410 when impact on apk size was noticed(https://github.com/flutter/flutter/issues/27250).

https://github.com/flutter/flutter/issues/27250#issuecomment-460082941 hopefully provides enough information about apk size vs performance trade-off that warrants re-enabling of that optimization.

**Comment by aam** [comment]
@Hixie @mkustermann @a-siva

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/27250#issuecomment-460082941 is a bit confusing in that it lists several possible changes.

Can we summarize the exact commit we want to land, what the performance impact is, and what the expected effect on footprint is? The goal is to make sure we are making an informed decision. I expect that the trade-off is worth it. If so, then we can land it and look at the benchmark numbers and make sure that they do change the way that we expect.

**Comment by aam** [comment]
https://github.com/flutter/flutter/pull/27789 is the change. With it, compressed hello_world apk goes up from 893,149 to 919,468, uncompressed goes down from 2,829,456 to 2,758,432. Microbenchmarks performance improve by 10-20%.

**Comment by Hixie** [comment]
25KB for a 15% improvement in performance seems worth it. Let's try it, and verify that the effect is as expected. (I recommend making an engine roll that only contains this change, to help isolate the effect.)

**Comment by aam** [comment]
The #27789 change is really just a flutter/flutter change that enables the default 'bare'-instruction behavior via options-passing
