### ISSUE TITLE
Run Flutter devicelab integration tests on Android API 16 (lowest supported) device

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#27790]
Add an Android API level 16 device (Android 4.1 Jelly Bean) to the devicelab to ensure we don't regress support for this platform. This is our [lowest-supported Android API level](https://flutter.io/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on).

Note: the devicelab already includes a lowest-supported iOS device (iPhone 4S).

**Comment by Hixie** [comment]
cc @godofredoc

**Comment by godofredoc** [comment]
Emulator support is now ready in the infrastructure. Adding a test for api 16 now only requires writing no test and configuring it in .ci.yaml.
