### ISSUE TITLE
How to the filter list data based on distance and showing nearest location?

### ISSUE THREAD

**Issue by mimdudin** [flutter/flutter#27799]
Hi, I have a case about show `Food` based on `Nearby Location`. On the` List<Food>` I save `LatLong` which will be used to compare the distance of the user. So when it's run, the application takes `LatLong` users and compares the food distance, after that sorting the `List` based on the nearest location, how to code about this? |

I see [geolocator](https://pub.dartlang.org/packages/geolocator) plugin can be relied upon to get a distance between.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
