### ISSUE TITLE
Flutter tools should pass information about launch,  run vs attach to daemon

### ISSUE THREAD

**Issue by keertip** [flutter/flutter#27807]
Sometimes calling` app.stop` after attaching to flutter application via the IDE causes the app to crash. This can be prevented by calling `app.detach` instead. Currently the daemon has no way of knowing if the app was started by flutter run or it was an attach. So enhance flutter_tools  

* such that the flutter attach command passes the fact that we connected to the app via attach to the daemon library
* when the daemon app start event is sent to the IDE, it includes the launch mode (in this case, something like `"attach"`)

This information can then be used by the IDE -  if we determine that it had been started via flutter attach (based on the daemon info), we call the detach command instead of stop

**Comment by DaveShuckerow** [comment]
g3 issue#123943661 provides context here.

Dream has an issue where their editor is trying to stop apps (Daemon API call `app.stop`) they've attached to, but they require that the editor only disconnect (Daemon API call `app.detach`).

If the Daemon API included a field "invocationSource": "run"/"attach", then we would be able to decide if the appropriate way for the IDE to disconnect is with stop or detach.

**Comment by jonahwilliams** [comment]
Opened: https://github.com/flutter/flutter/pull/27812
