### ISSUE TITLE
更新时错误

### ISSUE THREAD

**Issue by kongxiaoan** [flutter/flutter#27814]
```
Upgrading Flutter from /Users/flutterProject/flutter...
From https://github.com/flutter/flutter
   b47da6c2b..23d38901e  master     -> origin/master
Updating b47da6c2b..23d38901e
 4 files changed, 24 insertions(+), 3 deletions(-)

Upgrading engine...
Building flutter tool...
Already up-to-date.

Flutter 1.2.1-pre.153 • channel master • https://github.com/flutter/flutter.git
Framework • revision b47da6c2b7 (76 minutes ago) • 2019-02-11 18:05:23 -0800
Engine • revision 3a1a604d71
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 fdfe40ea95)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
```

**Comment by kangwang1988** [comment]
@kongxiaoan 
run 'flutter doctor -vv' and paste the result here.

**Comment by wxFlymes** [comment]
> @kongxiaoan
> run 'flutter doctor -vv' and paste the result here.

when i upgrade the flutter ,it offen exit unexpected.then ,i run 'flutter doctor -vv':
[  +18 ms] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/usr/local/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/usr/local/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[        ] executing: [/usr/local/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.2.1-0-g8661d8aec
[ +104 ms] Flutter assets will be downloaded from :https://mirrors.sjtu.edu.cn/.
Make sure
                    you trust this source!
[  +17 ms] "flutter doctor" took 64ms.
[        ] "flutter doctor" took 64ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
