### ISSUE TITLE
[firebase_dynamic_links]  sometimes got error NSPOSIXErrorDomain Code=53 "Software caused connection abort"

### ISSUE THREAD

**Issue by ko2ic** [flutter/flutter#27810]
As in link, there is a case of error at the completion of handleUniversalLink.
[firebase/firebase-ios-sdk#2303](https://github.com/firebase/firebase-ios-sdk/issues/2303)

**Comment by ko2ic** [comment]
I issued a pull request

https://github.com/flutter/plugins/pull/1182

**Comment by kroikie** [comment]
@ko2ic

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/450. Any further collaboration will be done there.
