### ISSUE TITLE
AndroidX guide needs more work

### ISSUE THREAD

**Issue by krngd2** [flutter/flutter#27829]
Okay so my project is completely broken, tried so many suggestions and solution nothing worked. Started a new project and only used non androidx supporting plugins as suggested in [here](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility) but still getting error with android.support.annotations tried some solutions on it and nothing worked. 
Just need the configuration or step procedure for creating a firebase plugin compatible project either with Androidx or without it.

**Comment by betoflakes** [comment]
Same here, I had create the third project hopping this gonna work. We need the magic combination of libraries to work.

**Comment by inventvictor** [comment]
Hello guys

You would have to migrate your newly created flutter project to AndroidX using Android Studio

Watch this 2minute video;
https://youtu.be/VXHbpeCiffA

Best,
Victor

**Comment by krngd2** [comment]
> Hello guys
> 
> You would have to migrate your newly created flutter project to AndroidX using Android Studio
> 
> Watch this 2minute video;
> https://youtu.be/VXHbpeCiffA
> 
> Best,
> Victor

Actually the problem arrive when you try to integrate Firebase plugins

**Comment by mklim** [comment]
Thanks for filing an issue.

It sounds like it would be useful to have a step by step guide or a codelab on how to bring in the AndroidX plugins to a completely new template just from `flutter create` on the stable channel. 

@krngd2 just to make sure I'm understanding right, you're saying that right now you're including just [the deprecated support library plugins](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx) and you're still seeing gradle errors? Did you also try migrating before downgrading their versions? Would you mind posting your `pubspec.yaml` dependencies, plus any dependencies and your `compileSdkVersion` from your `android/build.gradle`? I'm asking because I think what may have happened is something in your gradle files might have been migrated to AndroidX, but then if you went back and included the old versions of the plugins again it would break based on the new gradle migration not being compatible with the old versions of the plugins. Can't say for sure without more information though.

**Comment by krngd2** [comment]
> Thanks for filing an issue.
> 
> It sounds like it would be useful to have a step by step guide or a codelab on how to bring in the AndroidX plugins to a completely new template just from `flutter create` on the stable channel.
> 
> @krngd2 just to make sure I'm understanding right, you're saying that right now you're including just [the deprecated support library plugins](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx) and you're still seeing gradle errors? Did you also try migrating before downgrading their versions? Would you mind posting your `pubspec.yaml` dependencies, plus any dependencies and your `compileSdkVersion` from your `android/build.gradle`? I'm asking because I think what may have happened is something in your gradle files might have been migrated to AndroidX, but then if you went back and included the old versions of the plugins again it would break based on the new gradle migration not being compatible with the old versions of the plugins. Can't say for sure without more information though.

Sorry for the late reply,
I was trying to install firebase messaging plugin and saw its updated to latest version, so I migrated my project to androidX following a guide. Then the errors started popping up, i cant provide the original configuration files as i have made so many changes following solutions to the problems and changing the plugins version back and forth and i haven't even git initialized it. I have tried using all the latest versions of plugins after migrating but no use. Created an entirely new project and used only old versions of the plugins as recommended in [here](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility), still the same `error: resource android:attr/fontVariationSettings not found.` and trying to solve it giving android.support.annotations issue. 
I can provide you the new project `pubspec.yaml` file

``` 
environment:
   sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
   flutter:
     sdk: flutter 
  cloud_firestore: 0.8.2+3
  # cloud_functions: 0.0.5
  firebase_analytics: 1.1.0
  firebase_auth: 0.7.0
  firebase_core: 0.2.5+1 
  # firebase_dynamic_links: 0.1.1
  firebase_messaging: 2.1.0 
  firebase_performance: 0.0.8+1 
  firebase_storage: 1.0.4 
  google_sign_in: 3.2.4
  
  image_picker: 0.4.12+1
  url_launcher: 4.1.0+1
  shared_preferences: 0.4.3 ```

and in gradle build file I tried compiledSDK version 27 and 28 still the issues comes down to `android.support.annotations `
Any help is appreciated 
Thank you

**Comment by zoechi** [comment]
@krngd2 please follow #27901

**Comment by tudor07** [comment]
For me it only worked with
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`
in `gradle-wrapper.properties`

**Comment by jmagman** [comment]
Check out recent [AndroidX migration page](https://flutter.dev/docs/development/androidx-migration).  AndroidX is also the default for new projects.

**Comment by mklim** [comment]
I'm going to close this based on the changes @jmagman mentioned above. I think the original problem described by the issue has been addressed at this point.
