### ISSUE TITLE
image_picker plugin causes Android app to crash

### ISSUE THREAD

**Issue by vikdenic** [flutter/flutter#27830]
I installed the image_picker plugin into my project, and it works with iOS, But now the Android build crashes with the error:

FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.
```

Any idea why the Android build crashes when using this plugin?

**Comment by zoechi** [comment]
Duplicate of #23929

**Comment by phodonou** [comment]
Using image picker 0.4.6: https://pub.dartlang.org/packages/image_picker/versions/0.4.6#-readme-tab- solves this
