### ISSUE TITLE
Flutter webview scaffold 

### ISSUE THREAD

**Issue by samjoe5** [flutter/flutter#27834]
My flutter web-view scaffold URL is working but the default color of the web page is not working.
![screenshot from 2019-02-12 16-01-05](https://user-images.githubusercontent.com/43204242/52629317-7199cb80-2edf-11e9-9a9d-e14280ec60d4.png)
![screenshot_1549967372](https://user-images.githubusercontent.com/43204242/52629337-7a8a9d00-2edf-11e9-883a-377b2bb17bf8.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by samjoe5** [comment]
![screenshot from 2019-02-12 ``16-12-49](https://user-images.githubusercontent.com/43204242/52630046-1ff24080-2ee1-11e9-8112-4c4dc37369bd.png)

`import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
import 'package:system_shortcuts/system_shortcuts.dart';
import 'package:splashscreen/splashscreen.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MaterialApp(
    home: MyApp(),
    debugShowCheckedModeBanner: false,
    theme: ThemeData(
      primaryColor: Colors.blueGrey[900],
      brightness:Brightness.light,
      fontFamily: 'Bungee',
      primaryTextTheme: TextTheme(
        title: TextStyle(color: Colors.yellow),
      ),
    )));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return new SplashScreen(
      seconds: 2,
      navigateAfterSeconds: AfterSplash(),
      image: new Image.asset(
        'assets/images/icon.png',
        width: 100,
        height: 100,
      ),
      backgroundColor: Colors.blueGrey[800],
      photoSize: 100.0,
      loaderColor: Colors.yellow[300],
    );
  }
}

class AfterSplash extends StatefulWidget {
  @override
  _MyAppsState createState() => _MyAppsState();
}

class _MyAppsState extends State<AfterSplash> {
  @override
  Widget build(BuildContext context) {
    return WebviewScaffold(
      appBar: AppBar(title: Text("Crypto Signals"), 
      actions: <Widget>[
        // action button
        IconButton(
            icon: Icon(Icons.screen_rotation),
            onPressed: () async {
              await SystemShortcuts.orientLandscape();

            }),
      ]),
      url: "http://crypto.slamtrade.com/",
      withJavascript: true,
      withZoom: true,
      withLocalStorage: true,
      enableAppScheme: true,
      hidden: true,
      userAgent: 'https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=966276189940-1k54igc67tmva1i1tbodfmt3k5kf3e1i.apps.googleusercontent.com&as=bZHn1GRLkEC4_cjzG36PNg&destination=https%3A%2F%2Fslamtrade-ui.firebaseapp.com&approval_state=!ChRHRkRjRUhfeFhDZFMtM3ZQNzZychIfMDZJb0UtTWF2bE1ROEhuU1JuY2dubXFPaVNZSWpoWQ%E2%88%99AJDr988AAAAAXGPAtfiv-BKiA0Kd25fHIHc156Jb1sJX&oauthgdpr=1&xsrfsig=ChkAeAh8TyMGfEj66DNTFSmu0TeDs_vg-UHBEg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow',
    );
  }
}

`

**Comment by zoechi** [comment]
This plugin is maintained in https://github.com/fluttercommunity/flutter_webview_plugin.
Please report there instead.
