### ISSUE TITLE
how can i control textfield height?

### ISSUE THREAD

**Issue by jeckbjy** [flutter/flutter#27838]
![textfield](https://user-images.githubusercontent.com/1024038/52637332-ef72cc80-2f09-11e9-8a61-0b9c67da56dd.jpg)
![textfield1](https://user-images.githubusercontent.com/1024038/52637337-f26dbd00-2f09-11e9-8a8c-9a89e0c3e671.jpg)

the default textfield height is too big(the padding of top and bottom too big), i want little size, how can i implementation it?
i known InputDecoration.collapsed can remove the space, but it can't use prefix and suffix.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by rkishan516** [comment]
Add it to a Container and adjust the height of Container according to Your requirement

**Comment by HansMuller** [comment]
There's work underway to make textfield height more configurable: https://github.com/flutter/flutter/pull/27205

**Comment by chetan2469** [comment]
TextField(
                  maxLines: 5,
                ),

**Comment by josquared** [comment]
Container(
Width:32,
child:textfield(
)
)

**Comment by freesailor** [comment]
Use contentPadding:
TextField(
            decoration: InputDecoration(
contentPadding: EdgeInsets.all(8.0),//here your padding
                  border: OutlineInputBorder(............

**Comment by skysukai** [comment]
> Add it to a Container and adjust the height of Container according to Your requirement

It's not work

**Comment by mudi256** [comment]
Inside the TextFormField

decoration: InputDecoration(
      hintText: 'Email',
      contentPadding: new EdgeInsets.symmetric(vertical: 25.0, horizontal: 10.0),
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(32.0)),
    ),

**Comment by edihasaj** [comment]
Just increase the fontSize and you'll be fine.

TextFormField(
// other code 
style: TextStyle(fontSize: 18.0),
// ...
),

**Comment by patelkrunal78** [comment]
To adjust the width, you could wrap your TextField with a Container widget, like so:

new Container(
width: 100.0,
child: new TextField()
)

Find Full Code At [Here](https://icetutor.com/question/how-to-update-flutter-textfields-height-and-width)

**Comment by caseyryan** [comment]
> Use contentPadding:
> TextField(
> decoration: InputDecoration(
> contentPadding: EdgeInsets.all(8.0),//here your padding
> border: OutlineInputBorder(............

This is actually a working solution, thanks! 
Restricting a TextField with a container (as a couple of commenters advised before) has a huge drawback in case of TextFormField with validation, the textfield won't grow if validation fails and that will look really ugly. But using decoration is the correct way to do it

**Comment by milanpatel18** [comment]
To adjust the width, you could wrap your TextField with a Container widget, like so:

new Container(
width: 100.0,
child: new TextField()
)
I’m not really sure what you’re after when it comes to the height of the TextField but you could definitely have a look at the TextStyle widget, with which you can manipulate the fontSize and/or height

new Container(
width: 100.0,
child: new TextField(
style: new TextStyle(
fontSize: 40.0,
height: 2.0,
color: Colors.black
)
)
)

Findout More At [Here](https://icetutor.com/question/how-to-update-flutter-textfields-height-and-width/)

**Comment by orourkedd** [comment]
You can control the height using these two properties together in your `InputDecoration`.  For example, if `contentPadding` is set to `EdgeInsets.all(0)`, the `TextField` will have no padding at all around the text.

```
InputDecoration(   
  isDense: true, 
  contentPadding: EdgeInsets.all(10) 
)
```

**Comment by mahmoud-eslami** [comment]
> You can control the height using these two properties together in your `InputDecoration`. For example, if `contentPadding` is set to `EdgeInsets.all(0)`, the `TextField` will have no padding at all around the text and will be "short".
> 
> ```
> InputDecoration(   
>   isDense: true, 
>   contentPadding: EdgeInsets.all(10) 
> )
> ```

it worked thx

**Comment by WasimAndroidIvan** [comment]
TextField(
                        expands: true,

will expand the textField to its Container Height
