### ISSUE TITLE
ios. Could not create database  queue for path in device

### ISSUE THREAD

**Issue by MangoRabbin** [flutter/flutter#27844]
When I run flutter of iOS in my iPhone, it could not create local db queue and not open db.
I used sqfilte, path_provider to make local db.

I tried to solve it, but I couldn't solve.

this is the result in terminal

> error opening!: 14
> Could not create database queue for path /var/mobile/Containers/Data/Application/8181CA0B-D056-4A89-9A22-EC89C63CE9FA/Documentsuser.db
> Could not open db.

```
```

```
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by ZeroCool00** [comment]
@MangoRabbin  same problem, database is not creating, i m testing in simulator. when i goto actual path. nothings there. did you figure out yet?

**Comment by MangoRabbin** [comment]
@ZeroCool00. My problem is database's path. 

before 
```
 Future<Database> _initializeDatabase() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = directory.path + userDB;
    Database database = await openDatabase(path, version: 1, onCreate: _createDB);
    return database;
  }
```

after 


```
import 'package:path/path.dart' as p;
  Future<Database> _initializeDatabase() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = directory.path + userDB;
    // String path = p.join(directory.toString(),userDB);

    Database database = await openDatabase(path, version: 1, onCreate: _createDB);
    return database;
  }
```

**Comment by PawanVijay** [comment]
I I was getting same issue when i was running app in iOS device even though it was running in iOS simulators but not even my iPhone.

 solved this issues using below code :


import 'package:path/path.dart' as p;

Future<Database> initializeDatabase() async {
    //Get path of the directory for android and iOS.
 
    var databasesPath = await getDatabasesPath();
    String path = p.join(databasesPath, 'cards.db');

    //open/create database at a given path
    var cardDatabase = await openDatabase(path, version: 1, onCreate: _createDb);

    return cardDatabase;

  }

**Comment by SumitShukla007** [comment]
@ZeroCool00 Do we have to use both **path** and **path_provider** as dependencies?
