### ISSUE TITLE
BottomNavigationBar - Tapping on active tab should take the user back to root of the navigation stack

### ISSUE THREAD

**Issue by brucevang** [flutter/flutter#27859]
Tapping on the active tab should take the user back to root of the navigation stack.

This behavior follows the iOS design pattern for bottom nav.

**Expected:** 
![flutter_bottom_nav](https://user-images.githubusercontent.com/1462815/52670000-2a124000-2edd-11e9-9e08-af18fd1ddf2d.png)

**Actual:**
![flutter_bottom_nav_actual](https://user-images.githubusercontent.com/1462815/52670032-3b5b4c80-2edd-11e9-97f4-9609455e457f.png)
 

```

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A336e, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by brucevang** [comment]
I'm following this example where the bottom nav has its own navigators.
https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

https://github.com/bizz84/nested-navigation-demo-flutter
