### ISSUE TITLE
url_launcher plugin requires Android minSdkVersion 21

### ISSUE THREAD

**Issue by mockturtl** [flutter/flutter#27852]
```bash
$ ./gradlew lint

Errors found:
/path/to/my/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.0.1/android/src/main/java/
io/flutter/plugins/urllauncher/UrlLauncherPlugin.java:117:
Error: Call requires API level 21 (current min is 16):
android.webkit.WebResourceRequest#getUrl [NewApi]
                view.loadUrl(request.getUrl().toString());
```
Affects `url_launcher >= 1.0.2`.

[plugin source](https://github.com/flutter/plugins/blob/877429ae6070a795d2595955d37280c653999609/packages/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java#L117)
[Android reference](https://developer.android.com/reference/android/webkit/WebResourceRequest.html#getUrl())

similar: #19083

**Comment by ragnor-rs** [comment]
5.0.2 here. the problem still persists

**Comment by stuartmorgan** [comment]
This was fixed in https://github.com/flutter/plugins/pull/3008
