### ISSUE TITLE
OutlineInputBorder has no color property

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#27862]
Would be cool to have a color property in the OutlineInputBorder class so that we can change the outline color.

**Comment by HansMuller** [comment]
The borderSide parameter can be used to configure the outline color

**Comment by ldwonday** [comment]
@HansMuller It does not work when used the borderSide property! Flutter version is 1.2.1

**Comment by HansMuller** [comment]
If you have a small (complete app) test case that demonstrates the problem please open a new issue. Will be happy to look into it.
