### ISSUE TITLE
flutter doctor crash 

### ISSUE THREAD

**Issue by whj768702** [flutter/flutter#27872]
[flutter_05.log](https://github.com/flutter/flutter/files/2858739/flutter_05.log)

**Comment by kangwang1988** [comment]
Can you confirm that it's a duple of: https://github.com/flutter/flutter/issues/27670 ?
@whj768702

**Comment by whj768702** [comment]
yes.

**Comment by kangwang1988** [comment]
Duple of: https://github.com/flutter/flutter/issues/27670
Will resolve when https://github.com/flutter/flutter/pull/27687 is finally landed.
