### ISSUE TITLE
dosent load

### ISSUE THREAD

**Issue by Avon98** [flutter/flutter#27879]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by Avon98** [comment]
[undefined] flutter create .
The system cannot find the path specified.
Unable to find package:flutter in C:\flutter\packages\flutter
exit code 2

**Comment by kangwang1988** [comment]
@Avon98 
Run `flutter doctor -v` and paste the result please.
Besides,`flutter create --verbose hello_flutter` please.

**Comment by Avon98** [comment]
D:\apple>flutter doctor -v
The system cannot find the path specified.
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version
6.1.7601], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26
-0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\pc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific
functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • Lenovo K50a40 • SGLN5LVKSKIRY5ZL • android-arm • Android null (API
null)

• No issues found!

D:\apple>flutter create --verbose hello_world
The system cannot find the path specified.
[  +64 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic
@{u}
[ +266 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] origin/stable
[   +1 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +109 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +1 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[   +7 ms] https://github.com/flutter/flutter.git
[   +7 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[  +64 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +1 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%ar
[ +112 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 3 months ago
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.*
--first-parent --long --tags
[ +103 ms] Exit code 0 from: git describe --match v*.*.* --first-parent
--long --tags
[   +1 ms] v1.0.0-0-g5391447fa
[ +607 ms] "flutter create" took 272ms.
Unable to find package:flutter in C:\flutter\packages\flutter

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      CreateCommand.runCommand
(package:flutter_tools/src/commands/create.dart:221:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:401:18)
#3      _asyncThenWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#7      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:642:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#9      Future._complete (dart:async/future_impl.dart:476:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure>
(dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback
(dart:isolate/runtime/libisolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by zoechi** [comment]
What does `git --version` print?

**Comment by Avon98** [comment]
git version 2.20.1.windows.1

**Comment by zoechi** [comment]
Please try https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by Avon98** [comment]
I am tired man

**Comment by kangwang1988** [comment]
@Avon98 
Using flutter master, I found 
```
    final String flutterRoot = fs.path.absolute(Cache.flutterRoot);

    final String flutterPackagesDirectory = fs.path.join(flutterRoot, 'packages');
    final String flutterPackagePath = fs.path.join(flutterPackagesDirectory, 'flutter');
    if (!fs.isFileSync(fs.path.join(flutterPackagePath, 'pubspec.yaml')))
      throwToolExit('Unable to find package:flutter in $flutterPackagePath', exitCode: 2);
```
Seems the reason.
Your flutter installation seems broken.
There should be a  'your-flutter-path/packages/flutter/pubspec.yaml'
