### ISSUE TITLE
FlutterViewController can't set defaultRouteName by calling setInitialRoute

### ISSUE THREAD

**Issue by lupeihong** [flutter/flutter#27882]
```objective-c
//AppDelegate
self.flutterEngine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil];
[self.flutterEngine runWithEntrypoint:nil];
[GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];

//ViewController
FlutterViewController *flutterViewController = [FlutterViewController new];
[flutterViewController setInitialRoute:@"myApp"];

//main.dart
window.defaultRouteName Is always ‘/’
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
Is this about adding Flutter to an existing project?

**Comment by lupeihong** [comment]
yes，I add Flutter to an existing project .

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/luph/Documents/luph/flutter/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 9.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4, Build version 9F1027a
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone X • 3AA655F2-8BA5-42C9-AE14-A2CA805A760D • ios • iOS 11.4 (simulator)

**Comment by lupeihong** [comment]
Sorry, I posted the wrong code
 [FlutterViewController new]  is ok，but  [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil] it can't, like this:

//AppDelegate
self.flutterEngine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil];
[self.flutterEngine runWithEntrypoint:nil];
[GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];

//ViewController
FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] flutterEngine];
    FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
    [flutterViewController setInitialRoute:@"myApp"];

//main.dart
window.defaultRouteName Is always ‘/’

**Comment by neiljaywarner** [comment]
We also are having this problem with iOS only; is there anyone that has used initialRoute with iOS in add2app?

**Comment by kidzss** [comment]
I solved the problem.
//=======================

@interface XXFlutterViewController : FlutterViewController

@end

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    FlutterEngine *flutterEngine = self.engine;

    [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
    //custom  futter plugin
    [XXXFlutterBridge registerWithRegistry:flutterEngine];
}

//open flutter vc
XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
[flutterViewController setInitialRoute:@"xxxxx/xxxx"];

**Comment by csjlengxiang** [comment]
look this: https://github.com/flutter/flutter/issues/29554

**Comment by OmgKevin** [comment]
这个问题有比较好的解决办法吗

**Comment by softmarshmallow** [comment]
Any updates for this?

**Comment by softmarshmallow** [comment]
> I solved the problem.
> //=======================
> 
> @interface XXFlutterViewController : FlutterViewController
> 
> @EnD
> 
> * (void)viewDidLoad {
>   [super viewDidLoad];
>   // Do any additional setup after loading the view.
>   FlutterEngine *flutterEngine = self.engine;
>   [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
>   //custom  futter plugin
>   [XXXFlutterBridge registerWithRegistry:flutterEngine];
>   }
> 
> //open flutter vc
> XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> [flutterViewController setInitialRoute:@"xxxxx/xxxx"];

mind a swift version?

**Comment by hllGitHub** [comment]
> I solved the problem.
> //=======================
> 
> @interface XXFlutterViewController : FlutterViewController
> 
> @EnD
> 
> * (void)viewDidLoad {
>   [super viewDidLoad];
>   // Do any additional setup after loading the view.
>   FlutterEngine *flutterEngine = self.engine;
>   [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
>   //custom  futter plugin
>   [XXXFlutterBridge registerWithRegistry:flutterEngine];
>   }
> 
> //open flutter vc
> XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> [flutterViewController setInitialRoute:@"xxxxx/xxxx"];

It can not working. You just use other initial method. If `    FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
` it will can not working.

**Comment by alvnly** [comment]
> I solved the problem.
> //=======================
> 
> @interface XXFlutterViewController : FlutterViewController
> 
> @EnD
> 
> * (void)viewDidLoad {
>   [super viewDidLoad];
>   // Do any additional setup after loading the view.
>   FlutterEngine *flutterEngine = self.engine;
>   [GeneratedPluginRegistrant registerWithRegistry:flutterEngine];
>   //custom  futter plugin
>   [XXXFlutterBridge registerWithRegistry:flutterEngine];
>   }
> 
> //open flutter vc
> XXFlutterViewController *flutterViewController = [[XXFlutterViewController alloc] init];
> [flutterViewController setInitialRoute:@"xxxxx/xxxx"];

but you just new a flutterVC to setRoute, you didn't use the flutterEngine to manager it.

**Comment by binjiayou66** [comment]
Creating a new FlutterViewController in the new or alloc init way does deliver routeName, but this way creates multiple flutter.io/gpu/ui threads over and over again.

**Comment by zyg1982527** [comment]
I have solve the problem , it is truth , work well


let flutterViewController = FlutterProjectListViewController.init(project: nil  , nibName: nil, bundle: nil)!;
        flutterViewController.splashScreenView =  FlutterSplashViewController().view
        GeneratedPluginRegistrant.register(with: flutterViewController)
        flutterViewController.setModel(model: FLUTTER_PROJECT_LIST);
        flutterViewController.view.frame = UIScreen.main.bounds;
        self.navigationController?.pushViewController(flutterViewController, animated: true)
                 
        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
        self.flutterEngine?.run(withEntrypoint: nil)
        GeneratedPluginRegistrant.register(with: self.flutterEngine)

**Comment by zyg1982527** [comment]
I have solve the problem , it is truth , work well

        let flutterViewController = FlutterProjectListViewController.init(project: nil  , nibName: nil, bundle: nil)!;
        flutterViewController.splashScreenView =  FlutterSplashViewController().view
        GeneratedPluginRegistrant.register(with: flutterViewController)
        flutterViewController.setModel(model: FLUTTER_PROJECT_LIST);
        flutterViewController.view.frame = UIScreen.main.bounds;
        self.navigationController?.pushViewController(flutterViewController, animated: true)
        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
        self.flutterEngine?.run(withEntrypoint: nil)
        GeneratedPluginRegistrant.register(with: self.flutterEngine)

**Comment by zyg1982527** [comment]
I have solve the problem , it is truth , work well  

           let flutterViewController = FlutterViewController.init(project: nil  , nibName: nil, bundle: nil)!;
           flutterViewController.splashScreenView =  FlutterSplashViewController().view
           GeneratedPluginRegistrant.register(with: flutterViewController)
           flutterViewController.setInitialRoute("test1");
           flutterViewController.view.frame = UIScreen.main.bounds;
           self.navigationController?.pushViewController(flutterViewController, animated: true)
           self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
           self.flutterEngine?.run(withEntrypoint: nil)
           GeneratedPluginRegistrant.register(with: self.flutterEngine)

**Comment by hllGitHub** [comment]
I have two methods.
1. Use channel to set route
2. Call the flutter private method that can set route

zhangyonggang <notifications@github.com>于2019年11月1日 周五17:11写道：

**Comment by zyg1982527** [comment]
i have update the code ,you can see




| |
自己
|
|
邮箱：zyg1982527@126.com
|

签名由 网易邮箱大师 定制

On 11/01/2019 17:16, Jeffrey wrote:
I have two methods.
1. Use channel to set route
2. Call the flutter private method that can set route

zhangyonggang <notifications@github.com>于2019年11月1日 周五17:11写道：

**Comment by kikuchy** [comment]
I have similar problem.
Following this tutorial https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen?tab=initial-route-swift-tab#route , `WidgetsBinding.instance.window.defaultRouteName` is always "/". I expect the value of it changes to the given argument for `setInitialRoute`.

This problem seems relating this issue https://github.com/flutter/flutter/issues/31185 .

Is there any way to set initialRoute on Add2App for iOS?

<details>
<summary>`flutter doctor -v`</summary>
```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale ja-JP)
    • Flutter version 1.12.13+hotfix.8 at /Users/kikuchy/SDK/flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kikuchy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[!] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 3           • 8CDX1MTHU                            • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max • 1F4FCAF3-8258-46DD-BAAD-E6B9D03F12FE • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by z234009184** [comment]
I had the same problem.

**Comment by myseven** [comment]
I had the same problem too

**Comment by myseven** [comment]
> I have solve the problem , it is truth , work well
> 
> ```
>        let flutterViewController = FlutterViewController.init(project: nil  , nibName: nil, bundle: nil)!;
>        flutterViewController.splashScreenView =  FlutterSplashViewController().view
>        GeneratedPluginRegistrant.register(with: flutterViewController)
>        flutterViewController.setInitialRoute("test1");
>        flutterViewController.view.frame = UIScreen.main.bounds;
>        self.navigationController?.pushViewController(flutterViewController, animated: true)
>        self.flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
>        self.flutterEngine?.run(withEntrypoint: nil)
>        GeneratedPluginRegistrant.register(with: self.flutterEngine)
> ```

I think this method does not resolve problem, its just use other initial method to avoid this issue

**Comment by jmagman** [comment]
The [documentation](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#route) now says:
```
 Warning: "setInitialRoute" on the navigationChannel must be called before running your FlutterEngine in order for Flutter’s first frame to use the desired route.

Specifically, this must be called before running the Dart entrypoint. The entrypoint may lead to a series of events where runApp builds a Material/Cupertino/WidgetsApp that implicitly creates a Navigator that might window.defaultRouteName when the NavigatorState is first initialized.

Setting the initial route after running the engine doesn’t have an effect.
```

Closing.

**Comment by krmao** [comment]
> The [documentation](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#route) now says:
> 
> ```objc
> FlutterEngine *flutterEngine =
>     [[FlutterEngine alloc] initWithName:@"my flutter engine"];
> [[flutterEngine navigationChannel] invokeMethod:@"setInitialRoute"
>                                       arguments:@"/onboarding"];
> [flutterEngine run];
> ```
> 
> ```
>  Warning: "setInitialRoute" on the navigationChannel must be called before running your FlutterEngine in order for Flutter’s first frame to use the desired route.
> 
> Specifically, this must be called before running the Dart entrypoint. The entrypoint may lead to a series of events where runApp builds a Material/Cupertino/WidgetsApp that implicitly creates a Navigator that might window.defaultRouteName when the NavigatorState is first initialized.
> 
> Setting the initial route after running the engine doesn’t have an effect.
> ```
> 
> Closing.

### ios use cacheEngine with setInitRoute still not work, but android is ok!

- flutter doctor -v
```
[✓] Flutter (Channel unknown, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/krmao/workspace/flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/krmao/sdks/android/sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /Users/krmao/sdks/android/sdk
    • Java binary at: /Applications/Android Studio 3.4.1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.4.1.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • CLT AL01          • AKC7N19118000852                     • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro Max • DA7463AE-EFD1-4242-961E-D58A3E2657C4 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

- ios code
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> *)launchOptions {
  
    self.flutterEngine = [[FlutterEngine alloc] initWithName:@"my flutter engine"];
    [[self.flutterEngine navigationChannel] invokeMethod:@"setInitialRoute" arguments:@"smart://template/flutter?page=bridge&params="];
    [self.flutterEngine run];
    [GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];
  
    FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:self.flutterEngine nibName:nil bundle:nil];
    
    // FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithProject:nil nibName:nil bundle:nil];
    // [GeneratedPluginRegistrant registerWithRegistry:flutterViewController];
    // [flutterViewController setInitialRoute:@"smart://template/flutter?page=bridge&params="];
    
    FlutterMethodChannel* methodChannel = [FlutterMethodChannel methodChannelWithName:@"smart.template.flutter/method"
                                            binaryMessenger:flutterViewController.binaryMessenger];

    [methodChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
        NSLog(@"method=%@, arguments=%@",call.method, call.arguments);
    }];
    
    STNavigationController *rootViewNavigationController = [[STNavigationController alloc] initWithRootViewController:flutterViewController];
    rootViewNavigationController.navigationBarHidden = YES;
    
    self.uiWindow = [[UIWindow alloc] initWithFrame: [UIScreen mainScreen].bounds];
    [self.uiWindow setBackgroundColor:[UIColor whiteColor]];
    [self.uiWindow makeKeyAndVisible];
    [self.uiWindow setRootViewController:rootViewNavigationController];
    
    [[[UIApplication sharedApplication] delegate] setWindow:self.uiWindow];
    return YES;
}
```
- dart
```
void main() => runApp(_widgetForRoute(window.defaultRouteName));

/// smart://template/flutter?page=order&params=jsonString"
Widget _widgetForRoute(String route) {
  debugPaintSizeEnabled = false;

  Uri uri = Uri.parse(route);
  String page = uri.queryParameters['page'];
  String params = uri.queryParameters['params'];

  debugPrint("flutter main route=$route");
  debugPrint("flutter main page=$page, params=$params");

  switch (page) {
    case 'demo':
      return MyApp(homeWidget: MyHomePage(title: "Flutter PAGE DEMO"));
    case 'bridge':
      return STBaseStatefulWidget(state: BridgeState());
    case 'order':
      return MyApp(homeWidget: OrderWidget());
    default:
      return MyApp(homeWidget: NotFoundWidget(route: route));
  }
}
```

- xcode console log
```
2020-05-21 15:26:47.014264+0800 App[37918:218686] [VERBOSE-1:callback_cache.cc(132)] Could not parse callback cache, aborting restore
2020-05-21 15:26:47.233717+0800 App[37918:218866] flutter: Observatory listening on http://127.0.0.1:55102/hQTvvv7yDnA=/
2020-05-21 15:26:47.385279+0800 App[37918:218856] flutter: flutter main route=/
2020-05-21 15:26:47.386014+0800 App[37918:218856] flutter: flutter main page=null, params=null
2020-05-21 15:26:47.565483+0800 App[37918:218686] applicationDidBecomeActive
2020-05-21 15:26:47.834132+0800 App[37918:218856] flutter: SettingsWidget build

```

- preview
![image](https://user-images.githubusercontent.com/7344437/82534532-df6b8300-9b77-11ea-8196-8cf4828fe0a7.png)

**Comment by Zheng-Shuo** [comment]
Any updates for this?

**Comment by OmgKevin** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.17.0, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)



After the xcode and flutter SDK upgrade, the flutter page loaded by the iOS project through the module method is blank

**Comment by OmgKevin** [comment]
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.17.0, on Mac OS X 10.15.4 19E287, locale
> zh-Hans-CN)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.45.1)
> [✓] Connected device (1 available)
> 
> After the xcode and flutter SDK upgrade, the flutter page loaded by the iOS project through the module method is blank

Use the implicit flutterengine to load flutter pages,
Natively passed route name: [self setInitialRoute: @ "flutterHomeVC"];
Route name received by flutter: /
