### ISSUE TITLE
Making Network http error SocketException: Failed host lookup

### ISSUE THREAD

**Issue by hoc081098** [flutter/flutter#27883]
## Steps to Reproduce

Making Network http error when build release, even having internet connection
When build debug having no error
```
Error: SocketException: Failed host lookup: 'jsonplaceholder.typicode' (OS  Error No address associated with hostname, error = 7)
```
# Code: <br>
`main.dart`:
```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const url = 'https://jsonplaceholder.typicode.com/users';

  Future<List<Map<String, dynamic>>> _future;

  @override
  void initState() {
    super.initState();
    _future = fetch();
  }

  Future<List<Map<String, dynamic>>> fetch() {
    return http
        .get(url)
        .then((response) {
          return response.statusCode == 200
              ? response.body
              : throw 'Error when getting data';
        })
        .then((body) => json.decode(body))
        .then((list) => (list as List).cast<Map<String, dynamic>>());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: RefreshIndicator(
        onRefresh: () async {
          _future = fetch();
          setState(() {});
          return _future;
        },
        child: FutureBuilder<List<Map<String, dynamic>>>(
          future: _future,
          builder: (context, snapshot) {
            if (snapshot.hasError) {
              return Center(
                child: Container(
                  constraints: BoxConstraints.expand(),
                  child: SingleChildScrollView(
                    physics: AlwaysScrollableScrollPhysics(),
                    child: Text(snapshot.error.toString()),
                  ),
                ),
              );
            }

            if (!snapshot.hasData) {
              return Center(
                child: CircularProgressIndicator(),
              );
            }
            return ListView.builder(
              itemCount: snapshot.data.length,
              itemBuilder: (BuildContext context, int index) {
                final item = snapshot.data[index];
                return ListTile(
                  title: Text(item['name']),
                  subtitle: Text(item['email']),
                );
              },
            );
          },
        ),
      ),
    );
  }
}

```
Screenshots: <br>
Lenovo a2010: android 5.1
<img  src = "https://imgbbb.com/images/2019/02/13/52013983_2249012302092200_5907266970599817216_n.png" width="480">

Philips S337: android 5.1:
<img  src = "https://imgbbb.com/images/2019/02/13/51863834_1668949006594156_1865294890674421760_n.jpg">

## Logs

`flutter analyze`
```
Analyzing test_http...
No issues found! (ran in 3.5s)
```

`flutter doctor -v`
```
[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.2.0 at C:\flutter\flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: E:\Admin\Other\android-preview\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at E:\Admin\Other\android-preview\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5153.38

[√] VS Code (version 1.31.0)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • Philips S337 • FS011641B06736 • android-arm • Android 5.1 (API 22)
```

**Comment by zoechi** [comment]
Are you using a proxy?

**Comment by hoc081098** [comment]
No. I don't use proxy

**Comment by zoechi** [comment]
Hard to tell. Looks like a network issue.
Do other remote or local network adresses work?

**Comment by hoc081098** [comment]
I tried many network but still not working

**Comment by zoechi** [comment]
Shouldn't this be `jsonplaceholder.typicode.com` instead of `jsonplaceholder.typicode`?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by hoc081098** [comment]
i think that url is not a problem.
paste url ```https://jsonplaceholder.typicode.com/users``` in browser working well
``` static const url = 'https://jsonplaceholder.typicode.com/users';``` in class `_MyHomePageState`

**Comment by zoechi** [comment]
Where would the invalid URL (`jsonplaceholder.typicode`) from the error message come from then?
Can you provide a minimal reproduction?

**Comment by zoechi** [comment]
@mraleph could this be a tree-shaking issue or something like that?
(sorry, don't know whom else to summon)

**Comment by hoc081098** [comment]
i rebuild release app and this is error:
```
E/flutter (11529): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
E/flutter (11529):      BAD_SIGNATURE(ecdsa.c:247)
E/flutter (11529):      BAD_SIGNATURE(handshake_client.cc:1060))
E/flutter (11529): #0      IOClient.send (package:http/src/io_client.dart:33:23)
E/flutter (11529): <asynchronous suspension>
E/flutter (11529): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter (11529): <asynchronous suspension>
E/flutter (11529): #2      BaseClient.get (package:http/src/base_client.dart:32:7)
E/flutter (11529): #3      get.<anonymous closure> (package:http/http.dart:46:36)
E/flutter (11529): #4      _withClient (package:http/http.dart:166:20)
E/flutter (11529): <asynchronous suspension>
E/flutter (11529): #5      get (package:http/http.dart:46:5)
E/flutter (11529): #6      _MyHomePageState.fetch (package:test_http/main.dart:37:12)
E/flutter (11529): #7      _MyHomePageState.build.<anonymous closure> (package:test_http/main.dart:56:21)
E/flutter (11529): <asynchronous suspension>
E/flutter (11529): #8      RefreshIndicatorState._show.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:357:53)
E/flutter (11529): #9      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (11529): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (11529): #11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (11529): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)

E/flutter (11529): #13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (11529): #14     Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (11529): #15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (11529): #16     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (11529): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (11529): #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (11529): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (11529): #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (11529): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (11529):
```

**Comment by hoc081098** [comment]
same problem in stackoverflow: [https://stackoverflow.com/questions/54728717/error-when-using-https-with-flutter-http-dart-package](url)

**Comment by zarko-tg** [comment]
@hoc081098 Double-check / make sure you have
`<uses-permission android:name="android.permission.INTERNET" /> `
in your app's **android/app/src/main/AndroidManifest.xml**

**Comment by hoc081098** [comment]
Thank @zarko-tg. Solve: <uses-permission android:name="android.permission.INTERNET" />
in your app's android/app/src/main/AndroidManifest.xml

**Comment by ferso** [comment]
> Thank @zarko-tg.
> 
> Solve: add `<uses-permission android:name="android.permission.INTERNET" />` to android/app/src/main/AndroidManifest.xml

This saves me, Why this is not in the documentation ?

**Comment by zarko-tg** [comment]
@ferso It'd be less to worry about or consult documentation if they'd make it a default (in templates/starters) since most apps connect online. I spent like a day on a silly little thing.

**Comment by xai1983kbu** [comment]
I had that error even in Debug mode (android/app/src/debug/AndroidManifest.xml  has 
` <uses-permission android:name="android.permission.INTERNET" />`)

> Adding internet permission is not only a solution, 
> You also have to make sure that you are online whether it is mobile or emulator (c)
> https://stackoverflow.com/a/55548864

I wiped data 
C:\Users\UN\AppData\Local\Android\Sdk\emulator> .\emulator -avd Nexus_5X_API_28 -wipe-data
(or via Android Studio)
and run main.dart 

It works!

**Comment by RobertB4** [comment]
Adding `<uses-permission android:name="android.permission.INTERNET" />` solved this issue for me.

The documentation is out of date and should be updated. Since Flutter uses the internet permission internally in development mode it is always active when developing. When deploying the app to the play store, it is not active by default.

The documentation currently says:
```
uses-permission: Remove the android.permission.INTERNET permission if your application code does not need Internet access. The standard template includes this tag to enable communication between Flutter tools and a running app.
```

Which is misleading since the internet permission isn't in the production manifest (apparently it was in earlier flutter versions?). Please add a note to this so the documentation accurately explains that the internet permission has to be added to the production manifest in case it is needed.

**Comment by atapas** [comment]
> @hoc081098 Double-check / make sure you have
> `<uses-permission android:name="android.permission.INTERNET" /> `
> in your app's **android/app/src/main/AndroidManifest.xml**

Great Info. This helped me. 

As I was wondering a bit that, where to add this line in that file... figured it out to be at the end like:

![image](https://user-images.githubusercontent.com/3633137/58368679-e7b1c380-7f0d-11e9-8a27-3958bdc68394.png)

**Comment by kondasoft** [comment]
This line used to be there on default on previous version of Flutter. It seems that they have removed on the recent updates.

**Comment by abhisawesome** [comment]
Make sure the debugging device internet is turned on , if you use localhost try changing it into 10.0.2.2

**Comment by Emyboy** [comment]
> Thank @zarko-tg.
> 
> Solve: add `<uses-permission android:name="android.permission.INTERNET" />` to android/app/src/main/AndroidManifest.xml

would I have to restart the app before it works? Mine isn't working.

**Comment by zarko-tg** [comment]
@Emyboy yes, it means building and starting the app again. If it isn't working that your are likely having some other problem, unrelated to this Github issue.

**Comment by Abdusin** [comment]
> @hoc081098 Double-check / make sure you have
> `<uses-permission android:name="android.permission.INTERNET" /> `
> in your app's **android/app/src/main/AndroidManifest.xml**

@zarko-tg  pls help me this way dont solve my problem
[flutter/flutter/#43357](https://github.com/flutter/flutter/issues/43357)

**Comment by tonysader** [comment]
@zarko-tg thanks man that saved me too!

**Comment by tonysader** [comment]
> @hoc081098 Double-check / make sure you have
> `<uses-permission android:name="android.permission.INTERNET" /> `
> in your app's **android/app/src/main/AndroidManifest.xml**

@zarko-tg  Thanks man that saved me too!

**Comment by SuperManHa** [comment]
> @hoc081098 Double-check / make sure you have
> `<uses-permission android:name="android.permission.INTERNET" /> `
> in your app's **android/app/src/main/AndroidManifest.xml**

great! works for me!!

**Comment by bismarkstoney** [comment]
After trying all the steps. if You are running the server locally. In my case Strapi. Replace the localhost with http://localhost:1337/auth/local/register to http://10.0.2.2:1337/auth/local/register

**Comment by ph55** [comment]
I get this error on IOS.
```
SocketException: Failed host lookup: 'locallhost'
```

The solution listed here is for Android though ?
Anyone managed to fix it for iPhone simulator ?

**Comment by Purvik** [comment]
@ph55 Hey, having same issue on iOS. Did you manage to solve it?

**Comment by cahyowhy** [comment]
already set permission but still got that err
```
environment:
  sdk: ">=2.3.0 <3.0.0"
  ....
..
flutter_svg: ^0.14.0
```

**Comment by xRose1** [comment]
I cant display my api pictures due to this

**Comment by ericchuawc** [comment]
i tried and can't work too..

then realised my android simulator wifi is off... need to enable it ya :)

**Comment by SumonHub** [comment]
make sure your device has internet connection.

**Comment by akadatsky** [comment]
I have this issue on release build, but debug build works ok. 
Manual adding <uses-permission android:name="android.permission.INTERNET" />
works, but its waird why it works on debug build

**Comment by enasellithy** [comment]
> @hoc081098 Double-check / make sure you have
> `<uses-permission android:name="android.permission.INTERNET" /> `
> in your app's **android/app/src/main/AndroidManifest.xml**

please help my i have same isuee and i try your way not working with me i use this this endpoint 
https://yts.mx/api/v2/list_movies.json
![Screenshot from 2020-04-10 17-21-51](https://user-images.githubusercontent.com/17440978/79003784-91646800-7b53-11ea-87a3-6e1c4395c65a.png)
![Screenshot from 2020-04-10 17-21-38](https://user-images.githubusercontent.com/17440978/79003794-99240c80-7b53-11ea-922d-4a65eeae2722.png)
