### ISSUE TITLE
FirebaseAuth crashes on iOS when setting photoURL to null

### ISSUE THREAD

**Issue by nickolas-pohilets** [flutter/flutter#27897]
https://github.com/flutter/plugins/blob/a444ad120418d622c4dea2882190968722abbcfe/packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m#L190
crashes if `photoUrl` is `NSNull.null`.

**Comment by kroikie** [comment]
@nickolas-pohilets

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/447. Any further collaboration will be done there.
