### ISSUE TITLE
Composite physical layers on all platforms

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#27891]
Related: https://github.com/flutter/flutter/issues/25673, https://github.com/flutter/flutter/issues/25226

We should investigate compositing physical layers on all platforms.  Today, we only do it for Fuchsia.

A quick test suggests that turning off the check "just works", but it does throw an assert.  Compositing physical layers on all platforms should make checking elevations and getting thicknesses more consistent and performant.

/cc @jason-simmons @mklim @goderbauer @Hixie

**Comment by Hixie** [comment]
We should check what this does to release mode performance on Android and iOS. The theory is that not having layers gives us better performance, but we never tested that for this case. We have several devicelab benchmarks that you could run locally to test this, e.g. the gallery transitions one.

**Comment by dnfield** [comment]
Worst case scenario we should be able to limit this to if asserts are enabled, if it does really turn out to help our check.

**Comment by dnfield** [comment]
This is a breaking change - for instance, framework tests currently track today whether `drawShadow` or `clip*` was called on a Canvas.  With this change, those calls will no longer be there, and the test would instead have to validate whether the appropriate layer was added to the layer tree.

**Comment by dnfield** [comment]
We could, of course, avoid the breakage by making it opt in.  I still have to check more performance data though - if this improves performance I'd rather not make it opt in.

**Comment by dnfield** [comment]
This had to be reverted because of anti-aliasing issues.

**Comment by dnfield** [comment]
On non-Fuchsia, we definitely need to composite physical layers even if the elevation == 0 - I need to track down whether that's acceptable for Fuchsia.

In the mean time, I'm going to revert this again so it doesn't hold up the google3 roll.

/cc @j9brown who added that test

**Comment by dnfield** [comment]
This has landed.
