### ISSUE TITLE
Theme cleanup

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#27909]
It would be good for @HansMuller and I's sanity to clean up ThemeData a bit. Here are some thoughts on how to do this in an almost entirely non-breaking manner so that we don't disturb people while we make ourselves feel better:

- Add a new constructor that takes far fewer arguments, mostly focusing on taking the composite FooTheme objects rather than individual colours and callbacks.

- Group some of the individual things we have now into new FooTheme objects, e.g. putting the splashColor and ink splash factory into a SplashTheme.

- Have the default constructor use the arguments to construct FooTheme objects and store those, rather than having lots of fields on the ThemeData directly.

- Have the getters on ThemeData return values from subobjects.

- In particular, avoid duplication (e.g. we have two places with the BottomAppBar color).

- Reorder the fields in the existing constructor to make more sense. For example, group colours together, or group arguments that turn into one FooTheme together.

**Comment by xster** [comment]
Adding to this list (that Hans and I discussed previously):

- Letting the various null defaulting happen on getters rather than materializing the defaults right in the factory because then it's no longer possible to figure out whether they're user specified or default fallbacks when we do copyWith on them etc.

**Comment by zoechi** [comment]
#15546 might be related

**Comment by guidezpl** [comment]
Since pretty much all of this is covered in more detail by https://github.com/flutter/flutter/issues/91772 and https://flutter.dev/go/material-theme-system-updates, I'm going to close this.
