### ISSUE TITLE
error message displayed when trying to run 'flutter packages pub global activate <tool>'

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#27911]
When trying to use the pub global activate via the flutter packages pub pass-through, I see an error:

```
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

However, the `pub global activate` does not require a pubspec; it can be run from anywhere.

I believe the `PackagesPassthroughCommand` class in commands/packages.dart should be updated tp not require a pubspec.

**Comment by zoechi** [comment]
Might be related to #21305
