### ISSUE TITLE
Several devicelab tests should be running elsewhere.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#27917]
Several devicelab tests don't actually use a physical device (or even a simulator/emulator) at all and should be moved to other infrastructure (e.g. Cirrus or LUCI).  Most of them could be run as presubmit tests as well (although without reporting benchmarks if they currently do).  We should focus on the devicelab doing tests that require a physical device, which would reduce the time it takes for a red tree to go green again and allow us to free up capacity.

### Any platform:
- [ ] `analyzer_benchmark`: runs `flutter analyze --benchmark --flutter-repo` and similar commands
- [ ] `flutter_test_performance`: just needs `flutter test`

### Linux (Android SDK)
- [ ] `basic_material_app_android__compile`
- [ ] `complex_layout_android__compile`
- [ ] `flutter_gallery_android__compile`
- [ ] `hello_world_android__compile`

### macOS/iOS
- [ ] `hello_world_ios__compile`
- [ ] `basic_material_app_ios__compile`
- [ ] `complex_layout_ios__compile`
- [ ] `flutter_gallery_ios__compile` 

### Windows (Android SDK)
- [ ] `basic_material_app_win__compile`
- [ ] `complex_layout_win__compile`
- [ ] `flutter_gallery_win__compile`

### Any Platform:

- [x] `dartdocs`: mainly just `flutter analyze` commands.
- [x] `technical_debt__cost`: static analysis on Flutter repo. Maybe good to run as presubmit with a warning if something increases the debt.

### Linux (Android SDK)
- [x] `gradle_plugin_test`: just needs gradle/Android SDK - only does builds
- [x] `module_test`: just tests `flutter create -t module` and build commands.
- [x] `plugin_test`: Needs Android SDK, only builds project
- [x] `flutter_create_offline_test_linux`: tests running flutter create, no device required

### macOS/iOS
- [x] `module_test_ios`: similar to module_test, but needs Xcode SDK.
- [x] `plugin_test_ios`: plugin_test but on macOS
- [x] `flutter_create_offline_test_mac`: ditto

### Windows (Android SDK) 
- [x] `plugin_test_win`: plugin_test but on Windows
- [x] `flutter_create_offline_test_windows`: ditto

**Comment by Hixie** [comment]
The performance ones (*_compile, *_benchmark) need to run on dedicated hardware.
The others I agree though.

**Comment by dnfield** [comment]
I've updated the list to indicate which ones would need to stay on dedicated hardware and which ones could run in a container.

**Comment by dnfield** [comment]
For technical_debt__cost, are we ok with losing it in the benchmarks page?  It may be possible to have it post back something to the GH pull request page instead.

**Comment by Hixie** [comment]
The `technical_debt__cost` one must be a benchmark, that's its whole purpose. Where the data ends up I don't care, but it should be included on the same page as any other benchmarks we have. The release_size_bytes benchmarks are similar (might not need to be done on devicelab but definitely need to be shown on the same dashboard).

**Comment by godofredoc** [comment]
@Hixie  @dnfield do we actually need physical hardware for *__compile tests or we can just run on the cloud? are expecting a lot of variation on metrics if we run them in the cloud?

**Comment by dnfield** [comment]
They need to run on consistent hardware.

**Comment by liyuqian** [comment]
Cloud can provide consistent hardware:
> GCE allows us to pick the exact CPU type, memory, disk, and OS version so I'd say its consistency should satisfy our need. Skia has been collecting its Linux/Windows metrics from GCE instances and they seem to be quite consistent.

**Comment by godofredoc** [comment]
We created a Linux VM and added it to the devicelab we will be moving some tests to it next week.

**Comment by godofredoc** [comment]
Closing as complete, now tests can be easily moved from devicelab to vms just by moving them to different configuration files and most of the tests have already been moved.
