### ISSUE TITLE
TextFormField Error Text Alignment

### ISSUE THREAD

**Issue by eikebartels** [flutter/flutter#27926]
Hey, 

I'm having a `TextFormField` inside a form, which works fine. The text inside the `TextFormField` is aligned right via `textAlign: TextAlign.right,`

The problem which I have is, that I can not set the error text to align right.
 <img width="317" alt="image" src="https://user-images.githubusercontent.com/767979/52772222-3b239400-3038-11e9-9797-5359ebf89845.png">

 Actually the inspector tells me, that the alignment is set correct. Instead the field it self does not fill the whole width of the `TextFormField` widget and therefor it does not align correctly inside its parent.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/767979/52772360-99e90d80-3038-11e9-8202-716d43144198.png">

## Steps to Reproduce

1. Create a simple form 
2. Align the `TextFormField` right via `textAlign: TextAlign.right`
3. Add a validator which returns an error text
4. Notice the alignment. Should be wrong

## Logs

```
Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale en-DE)
    • Flutter version 1.1.8 at /Users/eikebartels/Applications/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)
```

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by panthe** [comment]
I think that you can reproduce this error with this snippet of code:

`
TextFormField(      
      textAlign: TextAlign.end,      
      validator: (val) {
        if (val.isEmpty) {
          return 'NickName is necessary.';
        }
        if (val.length < 2) {
          return 'NickName too short..';
        }
        return null;
      },
      onSaved: (String val) {
        setState(() {
          _nickName = val;
        });
      },      
      keyboardType: TextInputType.text,      
      decoration: InputDecoration(
        border: InputBorder.none,
        hintText: "NickName",
        hintStyle: TextStyle(
            fontSize: 17.0),
        helperText: "",
        helperStyle: TextStyle(
            fontFamily: 'SF-Pro-Display',
            fontSize: 14.0,
            fontWeight: FontWeight.bold
        ),
        errorStyle: TextStyle(
            fontFamily: 'SF-Pro-Display',
            fontSize: 14.0,
            fontWeight: FontWeight.bold,
        ),

      ),
    );
`

this is the output (NickName field only) of this code:

![Screenshot_1568712583](https://user-images.githubusercontent.com/250296/65029682-77a4ce80-d93e-11e9-9ab3-5aebd7c316f4.png)

**Comment by md-weber** [comment]
It would be great if we reopen this bug again 👍

**Comment by tapizquent** [comment]
Can we revisit this? There should be a way to align the validation text differently from textformfield text

**Comment by LockedThread** [comment]
@tapizquent I absolutely agree with that. I'm currently gonna edit the src of the TextFormField class so I am able to.

**Comment by SzeMeiTan** [comment]
> @tapizquent I absolutely agree with that. I'm currently gonna edit the src of the TextFormField class so I am able to.

May I know how you do that?

**Comment by dewa1993** [comment]
Wrapping your `TextFormField` with `Directionality` should solve this.

`Directionality(
                textDirection: TextDirection.rtl,
                child: TextFormField());`

However, This approach breaks the cursor position when there is any special symbol is input through keyboard, which is weird.
