### ISSUE TITLE
[questions] Some question about writing flutter plugins

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#27934]
Why FlutterActivity extends android.app.Activity and not [AppCompatActivity](https://developer.android.com/reference/android/support/v7/app/AppCompatActivity)
Is there some plan to use it one day ?
And if not why ?

My goal is to access getSupportFragmentManager (cf. https://developer.android.com/reference/android/support/v4/app/FragmentActivity#getSupportFragmentManager()) in order to add v4 Fragment.

**Comment by robsonfingo** [comment]
I read somewhere that they did it to save on binary size. You can change your MainActivity to inherit from io.flutter.app.FlutterFragmentActivity to use fragments.

**Comment by darshankawar** [comment]
@Kleak 
Is this still a valid question or has it been resolved ?
Can this issue be closed ?

**Comment by Kleak** [comment]
i think you can close it
