### ISSUE TITLE
Flutter | The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#27939]
I am trying to add firebase dependencies. When I run `flutter run` I get

    The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
    The following dependencies do not satisfy the required version:
    project ':google_api_availability' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

Pubscec.yaml

    dependencies:
      flutter:
        sdk: flutter
      firebase_auth: ^0.8.1
      google_sign_in: ^4.0.1
      cloud_firestore: ^0.9.0+1
      firebase_core: ^0.3.0+1
      firebase_storage: ^2.0.1
      cupertino_icons: ^0.1.2
      font_awesome_flutter: ^8.0.1
      country_code_picker: ^1.1.0
      fluttertoast: ^2.0.7
      image_picker: ^0.4.6
      shared_preferences: ^0.4.2
      cached_network_image: ^0.4.1
      intl: ^0.15.7
      geolocator: ^2.1.1
      http: ^0.11.3+14
      flutter_google_places: ^0.1.4+1
      location: ^1.1.6
      uuid: ^1.0.3
      auto_size_text: 0.3.0

build.gradle

    buildscript {
        repositories {
            google()
            jcenter()
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:3.3.1'
            classpath 'com.google.gms:google-services:4.2.0'
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(':app')
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }

app/build.gradle

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }
    
    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }
    
    apply plugin: 'com.android.application'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    
    android {
        compileSdkVersion 28
    
        lintOptions {
            disable 'InvalidPackage'
        }
    
        defaultConfig {
            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "com.example.myapp"
            minSdkVersion 16
            targetSdkVersion 28
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
    
        buildTypes {
            release {
                // TODO: Add your own signing config for the release build.
                // Signing with the debug keys for now, so `flutter run --release` works.
                signingConfig signingConfigs.debug
            }
        }
    }
    
    flutter {
        source '../..'
    }
    
    dependencies {
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    }
    apply plugin: 'com.google.gms.google-services'  // Gradle plugin

flutter doctor

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale en-MU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)
```

**Comment by zoechi** [comment]
I think https://stackoverflow.com/questions/54693595/flutter-the-android-gradle-plugin-supports-only-kotlin-gradle-plugin-version-1 is the right place to ask support questions.
Please create a new issue if it turns out to be a Flutter bug.

**Comment by zoechi** [comment]
There are similar issues where the discussions might help #26889, #26145, #23626

**Comment by tarun57** [comment]
I am using map view in flutter app it gives error on run  build  "Gradle and kotlin version mismatch".

**Comment by vargavince91** [comment]
I didn't use any plugin package from pub, I just had to change the `kotlin_version` in `android/build.gradle` file:

```gradle
buildscript {
    // change here:
    ext.kotlin_version = '1.3.0'
    dependencies {
        // kotlin version is used here:
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

**Comment by jaiaswani10** [comment]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'map_view' is using version
1.2.50.

**Comment by MichaelM97** [comment]
Upgrading the kotlin version should probably be included in the flutter tutorial for upgrading to AndroidX [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)

**Comment by samcharles93** [comment]
> Upgrading the kotlin version should probably be included in the flutter tutorial for upgrading to AndroidX [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)

agree, this was my issue after upgrading to AndroidX

**Comment by deepakkumawat1** [comment]
yeah...it works for me . the error is because i trying to going in android x without android studio(trying vs code) so i decreased my kotlin vesrion like this
buildscript {
    // change here:
    ext.kotlin_version = '1.3.21'
    dependencies {
        // kotlin version is used here:
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
previosly it was higher...

**Comment by kusman28** [comment]
> I am using map view in flutter app it gives error on run build "Gradle and kotlin version mismatch".

Did u solve it? I getting the same error.

**Comment by kusman28** [comment]
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'map_view' is using version
> 1.2.50.

Up

**Comment by jorgerpo** [comment]
I am having the same problem
help

**Comment by MichaelM97** [comment]
> > The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'map_view' is using version
> > 1.2.50.
> 
> Up

I doubt that any issues with [map_view](https://pub.dev/packages/map_view) will be resolved seeing as it’s marked as “discontinued”. I guess you’ll have to use an alternative map package if you want to update to AndroidX.

**Comment by ReemTaha-sw** [comment]
i am getting this error too :

Launching lib\main.dart on Infinix X5010 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':google_api_availability' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by uzairleo** [comment]
get same error while using map view without enabling android x support in flutter. I try to decreased the version manually but it didnt work can any one plz guide me its really irritating 
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher`
