### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by isoos** [flutter/flutter#27930]
_From @AakashGautam007 on February 14, 2019 11:46_

URL: https://pub.dartlang.org/packages/cloud_firestore#-readme-tab-

<Describe your issue or suggestion here>

.snapshop();    

this is not a function please use instead 
stream: Firestore.instance.collection('books').snapshots,

_Copied from original issue: dart-lang/pub-dartlang-dart#2051_

**Comment by isoos** [comment]
@AakashGautam007 this repository is for the pub site, for package issues, please file issues into the package's repository. I'm moving this issue now.

**Comment by zoechi** [comment]
@AakashGautam007 can you please provide more information.
It's unclear what the issue is about or how to reproduce.
