### ISSUE TITLE
Exception when moving camera with Google Maps plugin

### ISSUE THREAD

**Issue by irevans** [flutter/flutter#27936]
My application is creating a map and waiting for the `onMapCreated` callback before trying to move the camera e.g.

```dart
void onMapCreated(GoogleMapController controller) {
    controller.moveCamera(
      CameraUpdate.newLatLngBounds(
        LatLngBounds(
          southwest: LatLng(...),
          northeast: LatLng(...),
        ),
        mapPadding,
      ),
    );
  }
```

The majority of the time this works. However, maybe 1 times in 5, this fails with the following error message:
```
E/MethodChannel#plugins.flutter.io/google_maps_12: Failed to handle method call
    com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
        at com.google.maps.api.android.lib6.common.n.b(:com.google.android.gms.dynamite_mapsdynamite@15090029@15.0.90 (020306-231259764):6)
...
```
```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D42, locale en-GB)
    • Flutter version 1.1.8 at /Users/foobar/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/foobar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by GabrielMoreyra** [comment]
I'm having exactly the same issue, and it's pretty frequent.

**Comment by GabrielMoreyra** [comment]
It seems it's working fine for now. I was adding some markers before animating the camera, and if I await them is working as expected (at least for now, after testing several times).

void onMapCreated(GoogleMapController mapController) async {
    _mapController = mapController;
    await _mapController.addMarker(MarkerOptions(
        position: _origin,
        icon: BitmapDescriptor.defaultMarkerWithHue(
            BitmapDescriptor.hueGreen)));
    await _mapController.addMarker(MarkerOptions(position: _destination));

    _mapController.animateCamera(CameraUpdate.newLatLngBounds(
        LatLngBounds(
            southwest: LatLng(
                _origin.latitude <= _destination.latitude
                    ? _origin.latitude
                    : _destination.latitude,
                _origin.longitude <= _destination.longitude
                    ? _origin.longitude
                    : _destination.longitude),
            northeast: LatLng(
                _origin.latitude <= _destination.latitude
                    ? _destination.latitude
                    : _origin.latitude,
                _origin.longitude <= _destination.longitude
                    ? _destination.longitude
                    : _origin.longitude)),
        45.0));
  }

**Comment by irevans** [comment]
The only way I found to avoid this problem was to add a delay between the onMapCreated callback and the camera move.

**Comment by Alqueraf** [comment]
Same situation here, both for Android & iOS. Ended up using
`Future.delayed(const Duration(milliseconds: 100), () {...}`
and adding the camera updates inside the callback.

**Comment by d3xt3r2909** [comment]
Do you have any plan to fix this or ? For now delayed is working but it is not great solution.

**Comment by Hannah-Alto** [comment]
I did the following:
```
setTimeout(()=>this.animateToRegion(region,500),0)
```
Worked for me.

**Comment by lumogox** [comment]
Any news about this issue? still present, the Future.delayed workaround doesn't always work.

**Comment by adrianmoneta** [comment]
I'm calling async getVisibleRegion() before accessing my map controller:
`await _mapController.getVisibleRegion();
      _mapController.moveCamera(cu);`

**Comment by kroikie** [comment]
@irevans

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/445. Any further collaboration will be done there.

**Comment by eyewritecode** [comment]
If you end up here with this same error, here's how i fixed it. Note that the issue comes from trying to draw markers, polylines, etc... on the map before it has "fully loaded"

```dart
GoogleMap(
  onMapCreated: (mapCon) {
    WidgetsBinding.instance.addPostFrameCallback((_) {
         // your code that moves the camera
     });
  }
)
```
