### ISSUE TITLE
Random exception error when initialising app: JSON-RPC error -32000: Server error

### ISSUE THREAD

**Issue by joaowd** [flutter/flutter#27943]
Sometimes when I start debugging I get this error:
```
Error -32000 received from application: Server error
JSON-RPC error -32000: Server error
```
I can't find where it comes from. Any idea?

Regards.

**Comment by zoechi** [comment]
I see this sometimes after several hot restarts.
I have to rebuild and then it works again for a while.

**Comment by joaowd** [comment]
Exactly, it only happens sometimes, I'm not sure if its a problem in my code, or some random flutter bug.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by joaowd** [comment]
> [✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.3 18D109, locale en-PT)
    • Flutter version 1.2.0 at /Users/joaopalma/Development/flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/joaopalma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone 8 Plus • 1A16E5D9-C50F-4552-ABFC-662A377F26FE • ios • iOS 12.1 (simulator)

**Comment by shashkiranr** [comment]
Hi Team,

I am getting the error message when debugging my flutter application and even though the app runs fine on my physical device there will be no connection to the app and the Android studio IDE and hot restart, hot reload or any other debugging functions will not work. I would need to re run the app over again.

I have been receiving this error message a lot. this occurs when i run the app and is not related to any code in the app.

```
Syncing files to device Pixel XL...
I/om.shaaleabhya( 1172): Background concurrent copying GC freed 20354(1482KB) AllocSpace objects, 8(160KB) LOS objects, 49% free, 2MB/5MB, paused 50us total 103.302ms
W/om.shaaleabhya( 1172): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
I/om.shaaleabhya( 1172): Background concurrent copying GC freed 91816(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4MB/8MB, paused 67us total 105.633ms
Error -32000 received from application: Server error
Error -32000 received from application: Server error
Error -32000 received from application: Server error
Error -32000 received from application: Server error
I/om.shaaleabhya( 1172): Background concurrent copying GC freed 103030(2MB) AllocSpace objects, 5(516KB) LOS objects, 49% free, 8MB/16MB, paused 610us total 128.261ms
```

Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.3-pre.2, on Mac OS X 10.14.2 18C54, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2017.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.32.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

flutter --version
```
Flutter 1.3.3-pre.2 • channel master • https://github.com/flutter/flutter.git
Framework • revision cccf44faa6 (12 days ago) • 2019-02-28 23:53:32 -0800
Engine • revision 99f3f7a9c2
Tools • Dart 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)
```
