### ISSUE TITLE
Flutter admob integration keeps getting me disabled from AdSense/Admob

### ISSUE THREAD

**Issue by mjaffa-figure** [flutter/flutter#27947]
## Steps to Reproduce

I am initializing admob as so:
```dart
await FirebaseAdMob.instance.initialize(analyticsEnabled: true, appId: Application.isInDebugMode ? FirebaseAdMob.testAppId : defaultTargetPlatform == TargetPlatform.android ? 'ca-app-pub-androidid' : 'ca-app-pub-iosid');
```
And then I show a `RewardedVideoAd` as so:
```dart
RewardedVideoAd.instance.load(
        adUnitId: Application.isInDebugMode
            ? RewardedVideoAd.testAdUnitId
            : defaultTargetPlatform == TargetPlatform.android
                ? androidAdIdentifier
                : iosAdIdentifier,
        targetingInfo: new MobileAdTargetingInfo(
            testDevices: ["deviceid1", "deviceid2"],
            nonPersonalizedAds: true,
            childDirected: false));
```
I get this warning when I load/show the ad in the console log:
```
<Google:HTML> You are currently using version 7.36.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from https://goo.gl/UoiJ8F. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.
<Google> To get test ads on this device, call: request.testDevices = @[ @"deviceid2" ];
```

I keep getting disabled on the admob network. I am not doing any fraudulent ad showing or clicking activity. 

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.0 at /Users/matthewjaffa/flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/matthewjaffa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Matt’s iPhone (2) • deviceid • ios • iOS 12.1.4
    • iPhone XR         • simulatorid     • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by mjaffa-figure** [comment]
@zoechi Please help me get this resolved. We want to release our flutter app/game in 1.5 weeks. I wish there was a way I could talk to the admob team face to face or on the phone. I would be willing to fly out to Google Head quarters to have a sit down. 

I shouldn't be banned from showing ads, because I am trying everything to show test ads in development. We have a public beta of our game out there and it is not debug mode so it is showing real ads to real people, shouldn't be banned for that either.

**Comment by zoechi** [comment]
@mklim ?

**Comment by mklim** [comment]
I'm sorry, I don't have any context on this error. I haven't worked with the `firebase_admob` plugin in detail. @HansMuller do you have any ideas?

**Comment by RedBrogdon** [comment]
@mjaffa-figure, I don't believe the warnings you're seeing about SDK versions are a problem. Because the AdMob SDK is released in two different places (both as part of Firebase and as a standalone SDK), it's possible for a new version to be released a few days earlier in one place than the other. Right now, the Firebase release of the SDK is behind, which is the reason for the warnings you see. If you update your Cocoapods in a few days, that issue should go away. In the meantime, you aren't doing anything wrong by using the version of SDK you're using, and it shouldn't affect your ability to load and show ads.

You also mentioned this:

> I keep getting disabled on the admob network. I am not doing any fraudulent ad showing or clicking activity.

Can you give me a little more information about what you mean? Is your account suspended (you should get an email from AdMob listing the reasons if that's the case) or are ads just not showing up for you?

**Comment by mjaffa-figure** [comment]
@RedBrogdon 
I am not too worried about the SDK version warning. 

My account was suspended the first time due to me not showing test ads while I was testing things. I quickly fixed that by putting that if debug use the test app id and test unit ids. And I added my device to the testDeviceIds in the RewardedVideoAd request.

30 days later ads were restored. So When debugging our app we display test ads. We compiled a release version for Google Beta and TestFlight for friends to begin testing the release candidates for the game. Those are legitimate people seeing real ads. 

And then just yesterday I got an email again from GoogleAds saying my account has been disabled and I need to appeal to get it restored.


Does this isInDebug only get true while debugging and hooked up to a debugger?

class Application {
  static bool get isInDebugMode {
    bool inDebugMode = false;
    assert(inDebugMode = true);
    return inDebugMode;
  }
}

Cause if I run the app that was compiled as debug, but not in a debugger maybe it is showing real ads while I am testing on my test device?


I have carefully viewed the Adsense traffic from the mobile app, and since being restored we have barely showed any ads to anyone. I don't get how I can be doing fraudulent ad clicking or viewing. 

Just trying to get our game out there.

**Comment by mjaffa-figure** [comment]
@RedBrogdon Awesome got an email from the appeal of my disabled AdMob account. They are not going to re-enable it.

**Comment by zoechi** [comment]
@mjaffa-figure 

> Does this isInDebug only get true while debugging

That returns true in `--debug` builds and `false` in `--profile` or `--release` builds.

**Comment by mjaffa-figure** [comment]
@zoechi @RedBrogdon 
I guess this isn't an issue for me anymore right?
They rejected my appeal to enable my Google AdSense account and so I have to rip this out and do Facebook ads directly now without going through admob.

**Comment by RedBrogdon** [comment]
I don't believe this is an issue relating to the plugin, no.

I'm not on the AdMob policy team, and without knowing more of the specifics, I really wouldn't want to guess at the exact reason for the suspension. That said, testing a release build containing live ads with beta users or other early adopters is not normally a problem as long as they are using the app the way a normal user would. If one of them were to repeatedly tap on ads (either to test/demonstrate the integration or in a misguided attempt to earn revenue), though, that could cause a suspension.

Whatever the reason, I hope your account is reinstated soon. If you have any other questions, the AdMob support team responds to posts on their SDK forum, and will have more info on these types of issues than we do:

https://groups.google.com/forum/#!forum/google-admob-ads-sdk

**Comment by kroikie** [comment]
@mjaffa-figure

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/444. Any further collaboration will be done there.

**Comment by aidanm1999** [comment]
Hi, I have also been blocked from Adsense and there was no reason given. Does anyone know if this is a repeating issue or a freak case?
