### ISSUE TITLE
flutter build appbundle includes unselected .so files

### ISSUE THREAD

**Issue by ened** [flutter/flutter#27940]
Issue #18494 already touched the build behavior for 32/64 bit binaries, however there seems to be a further bug.

First, here is a set of commands to create a `.aab` in my project:

```
$ flutter clean
Deleting 'build/'.
Deleting '/Users/ened/git/com.company.project/packages/part1/example/.dart_tool/'.
$ flutter build appbundle --release --target-platform=android-arm
Initializing gradle...                                              1.6s
Resolving dependencies...                                           1.8s
...
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        49.6s
Built build/app/outputs/bundle/release/app.aab (31.6MB).
$ unzip -l build/app/outputs/bundle/release/app.aab | grep libflutter
 11308576  02-14-2019 23:39   base/lib/armeabi-v7a/libflutter.so
 15197732  02-14-2019 23:39   base/lib/x86/libflutter.so
 16373160  02-14-2019 23:39   base/lib/x86_64/libflutter.so
```

The AAB includes 3 versions of `libflutter.so`, however the *x86* & *x86_64* versions are odd and not requested. The AAB should not contain them.

Let's look at `android/app/build.gradle`:

```gradle
android {
    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        profile {
            signingConfig signingConfigs.release
        }
        release {
            signingConfig signingConfigs.release
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
    }
}
```

This explicitly filters to armeabi-v7a.

It seems that flutter injects the .so files in the wrong moment of the build process. I would expect this to happen early enough so that the Android gradle plugin ABI filter logic works and developers can fine-tune which ABIs they want to support. This may lead to bigger AABs if more platforms are supported but will not affect end-users as the Play Store will re-create optimized installation files.

flutter doctor -v:

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.3 18D42, locale en-US)
    • Flutter version 1.2.0 at /Users/ened/dev/flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio3.2.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3
```

**Comment by ened** [comment]
Basically, the flutter engine builds a platform-specifc `flutter.jar` which contains the .so files.

Instead, it should generate:
 - A generic .AAR , android application library, which contains
   - flutter.jar (only compile java code)
   - .so files for every supported platform

Then, the Android build process has a chance to select & filter (`abiFilters`) the correct .so files. This will also improve initial APK deployment times to development devices.

**Comment by dnfield** [comment]
Actually isn't this intended?  I believe the build process will select the correct .so when it builds the final apk right?

**Comment by ened** [comment]
@dnfield It really depends on what the developer tries to build.

In general, android build.gradle files have a option to limit supported ABI's, the option is called 'abiFilters'. 
If it's not set, no filters are applied.

You can install a single APK which supports multiple ABIs on your Android phone, and the Android runtime will select the current .so files to be loaded. The limitation is that once a ABI has been selected buy the runtime, only .so files from that ABI will be loaded. An issue I have encountered frequently about Flutter with my Apps is that a plugin contains .so dependencies for all ABIs (armeabi, arm64, x64..), but the flutter build system only includes arm64 .so files. Thus, rendering the API useless on armeabi phones.
The solution to this, and translated to AAB, is that the flutter build system includes all .so file ABI variants by default in the APK/AAB output and the developer, can choose which ABIs they actually want to support in the production release.
On a sidenote, such deployments will create rather large files during development but again, using the `abiFilter` option in build.gradle, the size can be reduced significantly. At the moment the option does not have the effect as desired.

**Comment by blasten** [comment]
`flutter build appbundle` takes a `--target-platform` flag. Please try again and reopen if this Is this still an issue.
