### ISSUE TITLE
Can't select text after scrolling

### ISSUE THREAD

**Issue by sjindel-google** [flutter/flutter#27948]
This can be reproduced by typing a long sentence into a `TextField`, scrolling to the start, and then back to the end. The last word in the sentence is now difficult to select -- long-pressing on the word will sometimes select the text, and sometimes not. Also, taps appear to be artificially shifted to the right -- so that tapping in the middle appears to be interpreted as a tap on the end.

This video illustrates the issue:

![text_selection](https://user-images.githubusercontent.com/29863079/52808420-24a82780-308e-11e9-9a9c-a1293223589c.gif)

The video was taken on Linux because it was easier, but I reproduced the issue on Android as well.

**Comment by nesscx** [comment]
GIF file didn't load correctly, you may want to upload it again.

**Comment by sjindel-google** [comment]
I think I fixed it... it loads for me now.

**Comment by zoechi** [comment]
Does this still reproduce with latest master?

**Comment by sjindel-google** [comment]
Yes, I pulled a few hours ago.

**Comment by sjindel-google** [comment]
Fixing this in https://github.com/flutter/flutter/pull/24476/files

**Comment by sjindel-google** [comment]
This issue was fixed in ec00e974d.
