### ISSUE TITLE
Widgets lack preview images on widget catalog

### ISSUE THREAD

**Issue by whhone** [flutter/flutter#27951]
## Steps to Reproduce

1. Go to [Widget Catalog](https://flutter.io/docs/development/ui/widgets) 
2. Choose a group. e.g., [Input](https://flutter.io/docs/development/ui/widgets/input)

Expected: See the preview image of the widgets.
Actual: Many preview images are missing.

**Comment by InMatrix** [comment]
Thank you for bringing this up. This is a long-standing problem. A couple of ideas to add preview images to the catalog:
* Some widget's API docs have screenshots or diagram, we can use them in the widget's catalog entry as well. 
* We can try to crowdsource widget preview images from the Flutter community. 

Cc: @chalin @sfshaza2

**Comment by Kartik1607** [comment]
Also, I believe where ever there is some code provided ( in documentation sample ) there should be an image of the end result output as well to help user visualize. Although, docs can add image by markdown but it would be nice if somehow the team is able to automate generating images from sample doc code at run time

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2383](https://github.com/flutter/website/issues/2383) via [**ZenHub**](https://www.zenhub.com/)

**Comment by InMatrix** [comment]
@Kartik1607 We do have an image generator tool for that purpose: https://github.com/flutter/assets-for-api-docs/tree/master/packages/diagrams

However, it still requires some work to augment existing sample code. The best way you can help here is to file bugs against individual API reference pages where you think having images will be helpful.

**Comment by zoechi** [comment]
@InMatrix I hope it's fine that I moved the issue to flutter/website.

**Comment by InMatrix** [comment]
@zoechi It's fine. Thanks!
