### ISSUE TITLE
firebase_ml_vision: iOS crash when QR Code is URL

### ISSUE THREAD

**Issue by gi097** [flutter/flutter#27959]
I am running an application which scans camera images in realtime, and shows a box around QR-codes. Example: 

![download](https://user-images.githubusercontent.com/18169417/52818758-e61f6680-30a7-11e9-834e-26ce73cc7d6a.gif)

On Android this works fine, but on iOS the app just crashes (`SIGTERM`).

```
2019-02-14 22:30:33.948053+0100 Runner[45321:2290998] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
```

Is there anyone else who can reproduce and fix this? This really only happens when scanning a full URL (starting with `http://`). One can use this test project: https://github.com/bparrishMines/mlkit_demo

This gets resolved by removing the following line: https://github.com/flutter/plugins/blob/edc81910c5e9465335c3b171bb7e26fd3d6ccb9b/packages/firebase_ml_vision/ios/Classes/BarcodeDetector.m#L52

**Comment by gi097** [comment]
Added PR: https://github.com/flutter/plugins/pull/1223

**Comment by gi097** [comment]
Merged in commit https://github.com/flutter/plugins/commit/f2b1e696eb1391fa734090faaac66b46057a0d38

**Comment by kroikie** [comment]
@gi097

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/443. Any further collaboration will be done there.
