### ISSUE TITLE
"gclient sync" of flutter/engine failing

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#27963]
Happening on the Skia->Flutter/Engine roller. Also reproduced it locally.

Steps:
- git clone https://github.com/flutter/engine
- cd engine
- echo """ solutions = [ { ‘managed’: False, ‘name’: ‘src/flutter’, ‘url’: ‘git@github.com:flutter/engine.git’, ‘custom_deps’: {}, ‘deps_file’: ‘DEPS’, ‘safesync_url’: '', }, ] """ > .gclient
- gclient sync

Error:
```
SDK Platform 28: 100% SDK Build-Tools 28.0.3: 100% SDK Platform-Tools: 100% SDK Tools: 100% 
Downloads complete.
Unhandled exception:
Bad state: Could not find package matching arguments: Instance of 'OptionsRevision', OSType.linux, null
#0      downloadArchive (package:android_sdk_downloader/src/http.dart:94:5)
<asynchronous suspension>
#1      main (package:android_sdk_downloader/main.dart:191:15)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._complete (dart:async/future_impl.dart:476:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Error: Command 'src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts src/tools/android/android_sdk_downloader/lib/main.dart -y --out=src/third_party/android_tools --platform=28 --platform-revision=6 --build-tools-version=28.0.3 --platform-tools-version=28.0.1 --tools-version=26.1.1 --ndk-version=19.0.5232133' returned non-zero exit status 255 in /repos/flutter-rmistry/engine
Hook 'src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts src/tools/android/android_sdk_downloader/lib/main.dart -y --out=src/third_party/android_tools --platform=28 --platform-revision=6 --build-tools-version=28.0.3 --platform-tools-version=28.0.1 --tools-version=26.1.1 --ndk-version=19.0.5232133' took 11.92 secs
```

**Comment by liyuqian** [comment]
It's happening for all of us. @GaryQian and @dnfield are investigating it.

**Comment by aam** [comment]
Should be fixed by https://github.com/flutter/engine/pull/7830

**Comment by dnfield** [comment]
Yes - see #27967 for discussion of how to deal with this moving forward

**Comment by wangqianjun** [comment]
1

**Comment by AidenCang** [comment]
modify:src/flutter/DEPS
{
  'name': 'download_android_tools',
  'pattern': '.',
  'condition': 'host_os == "mac" or host_os == "linux"',
  'action': [
      'src/third_party/dart/tools/sdks/dart-sdk/bin/dart', # this hook _must_ be run _after_ the dart hook.
      '--enable-asserts',
      'src/tools/android/android_sdk_downloader/lib/main.dart',
      '-y', # Accept licenses
      '--out=src/third_party/android_tools',
      '--platform=28',
      '--platform-revision=6',
      '--build-tools-version=28.0.3',
      '--platform-tools-version=29.0.5',
      '--tools-version=25.2.5',
      '--ndk-version=21.0.5935234'
  ],
},
android other Version: ttps://dl.google.com/android/repository/repository2-1.xml,find your version,modify src/flutter/DEPS ,  gclient sync is ok?
