### ISSUE TITLE
flutter_tools tests need to move all work into setUp methods

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#27965]
Code in main will be invoked even when the test is not run as a part of sharding.

cc @dnfield

**Comment by zanderso** [comment]
@jonahwilliams could you elaborate a bit on why we want this and/or what this will help with?

**Comment by jonahwilliams** [comment]
This was part of a general testing cleanup I wanted to do. In spirit, this is succeeded by Dan's change to randomize test order. Closing!
