### ISSUE TITLE
Selected text disappears on iOS

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#27961]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: Foo(),
  ));
}

class Foo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(),
      )
    );
  }
}
```

1. run above on iOS
2. type "Hello World" into textfield
3. select text
4. See this:

![img_0009](https://user-images.githubusercontent.com/1227763/52821843-efd3aa80-3064-11e9-8f55-1b6facc9b74b.PNG)

**Comment by goderbauer** [comment]
It works okay on Android.

**Comment by GaryQian** [comment]
That looks like it is rendering the selected text in white?

**Comment by xster** [comment]
https://github.com/flutter/flutter/pull/24876 is putting the opaque selection over the text too instead of just the cursor. I'm working on a fix.
