### ISSUE TITLE
If Android Repository removes an older version of the NDK, gclient sync breaks on engine.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#27967]
I was aware this could happen, but assumed it would not happen often and that it might be a good thing.  Looking back, I'm not sure that was the best choice and want to discuss how we can do better here.

The android_sdk_downloader tool uses https://dl.google.com/android/repository/repository2-1.xml to determine what packages are actually available and where it can download them from.  If a package disappears from that list, we will fail.  On the one hand that can be good - it forces us to stay up to date on the Android NDK.  On the other, it can be bad if a developer or bot suddenly can't build the engine because the Android NDK version is no longer available (even though the NDK might still be available locally in third_party).

I would like to see us at least get a warning if a newer NDK is available.  Supporting downloading older versions though may not be a trivial refactor short of us going back to maintaining a CIPD-like (or actual CIPD) bundle of Android artifacts.

/cc @cbracken @jason-simmons @chinmaygarde @liyuqian @GaryQian @Hixie 

related: https://github.com/flutter/flutter/issues/27963

**Comment by dnfield** [comment]
This could also happen in theory for platform tools, platforms, and platform build tools - but those tend not to get removed as much it seems.  NDK does.

**Comment by dnfield** [comment]
Another problem with this is that it may make it impossible to build older revisions of the engine hermetically.

**Comment by wangqianjun** [comment]
@dnfield Hello, I have encountered the same problem. How can I solve it? The error message is as follows:

============================
Syncing projects: 100% (85/85), done.
Running hooks:  40% ( 4/10) prepare_android_downloader
________ running '../../../third_party/dart/tools/sdks/dart-sdk/bin/pub get' in '/Users/arthur/work/study/engine/src/tools/android/android_sdk_downloader'
Resolving dependencies...
* args 1.5.1 (was 1.5.1)
+ charcode 1.1.2
* collection 1.14.11 (was 1.14.11)
+ convert 2.1.1
* meta 1.1.7 (was 1.1.6)
* path 1.6.2 (was 1.6.2)
* petitparser 2.1.1 (was 2.0.2) (2.2.0 available)
+ typed_data 1.1.6
* xml 3.3.1 (was 3.2.3) (3.4.0 available)
Changed 9 dependencies!
Running hooks:  50% ( 5/10) download_android_tools
________ running 'src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts src/tools/android/android_sdk_downloader/lib/main.dart -y --out=src/third_party/android_tools --platform=28 --platform-revision=6 --build-tools-version=28.0.3 --platform-tools-version=28.0.1 --tools-version=26.1.1 --ndk-version=19.0.5232133' in '/Users/arthur/work/study/engine'
src/tools/android/android_sdk_downloader/lib/main.dart:1: Warning: Interpreting this as package URI, 'package:android_sdk_downloader/main.dart'.
Downloading Android SDK and NDK artifacts...
Skipping Android SDK Platform 28, checksum matches current asset.
Skipping Android SDK Build-Tools 28.0.3, checksum matches current asset.
Skipping Android SDK Platform-Tools, checksum matches current asset.
Skipping Android SDK Tools, checksum matches current asset.
Unhandled exception:
Bad state: Could not find package matching arguments: Instance of 'OptionsRevision', OSType.mac, null
#0      downloadArchive (package:android_sdk_downloader/src/http.dart:94:5)
<asynchronous suspension>
#1      main (package:android_sdk_downloader/main.dart:191:15)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._complete (dart:async/future_impl.dart:476:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#9      _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#10     loadChecksums (package:android_sdk_downloader/src/checksums.dart)
#11     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Error: Command 'src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts src/tools/android/android_sdk_downloader/lib/main.dart -y --out=src/third_party/android_tools --platform=28 --platform-revision=6 --build-tools-version=28.0.3 --platform-tools-version=28.0.1 --tools-version=26.1.1 --ndk-version=19.0.5232133' returned non-zero exit status 255 in /Users/arthur/work/study/engine

**Comment by dnfield** [comment]
Are you merged up to the HEAD of master?

**Comment by dnfield** [comment]
It's been requested that the tool that does this be rewritten to not use Dart.  That's fine with me, although it'd still be good to know whether we should be allowing the Android repo force us to update our NDK or not.  @chinmaygarde @cbracken @jason-simmons  any thoughts on that?

**Comment by jason-simmons** [comment]
I would prefer to have the ability to reconstruct old commits of the engine using the toolchain that was current as of that commit.  This is useful for bisecting where bugs and changes to Dart/Skia/etc. behavior started happening.

**Comment by dnfield** [comment]
In that case, I think we should split out our NDk downloading logic to something using CIPD.  I'd rather leave the SDK as is, as that doesn't seem to get removed the way the NDK packages do.
