### ISSUE TITLE
My simple flutter app returns an incorrect error and won't run correctly

### ISSUE THREAD

**Issue by brian-dunn** [flutter/flutter#27975]
I am following a basic class on Udemy and getting an error when I run a simple application to display the values in a List variable. From `main()`, I call a Widget called `MyApp` that extends `StatefulWidget`. The compiler returns an error 
```
"MyApp" is not a subtype of type 'StatelessWidget'. 
```
The error message further states that this is a bug in the Flutter framework that should be reported.

Here the definition of the MyApp class which, as you can see, is a StatefulWidget. 
```dart
class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    return _MyAppState();
  }
}
```
The app used to work until I added a line to add an item to the List variable using the `.add` method. The code is 100% identical to the code in the instructional video, but the instructor was using a beta version of Flutter from December 2018.

**Comment by Kartik1607** [comment]
Can you post your code including `main` method, `MyApp` class as well as `_MpAppState`
