### ISSUE TITLE
firebase_auth plugin Docs need reference on how to setup Federeated Id Providers.

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#27978]
The firebase_auth plugin docs don't make it clear how we should configure our Federated identity provider integrations. The Firebase docs show options for  iOS, Android, Web, C++ and Unity, but not for Flutter.

For example, right now I am looking at the Facebook developers page, trying to setup Facebook login, and those are my options:

![image](https://user-images.githubusercontent.com/8120472/52828368-af4d4e80-30af-11e9-99fb-82cd1b34c07a.png)

Should I follow the iOS and Android steps, or should I go to "Other"? Or maybe firebase_auth was implemented as Web?

I think this is missing from the docs and it's an important information for people not used with Federated Identity providers.

**Comment by yhua537** [comment]
Flutter current supports both ios and android so needs to do both.

**Comment by kroikie** [comment]
@feinstein

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/442. Any further collaboration will be done there.
