### ISSUE TITLE
colors in compare to android material design

### ISSUE THREAD

**Issue by DJafari** [flutter/flutter#27979]
i'm not sure this is bug or changing behavior

as i'm a android developer, in android and material design theme, all control default colors is `colorAccent`

but in flutter for example highlight border color of OutlineInput is `colorPrimary`, or color of RaisedButton is grey,

i want to know this is normal ?
since i was a android developer, I made it a bit confusing

p.s: i know we can change all colors, but my talk is about defaults

**Comment by Kartik1607** [comment]
In flutter, most of widgets default color is controller by [ThemeData](https://docs.flutter.io/flutter/material/ThemeData-class.html). But to check if it follows material design theme, would need to go through each Material Widget and check specs.

**Comment by DJafari** [comment]
@Kartik1607 thanks for your reply
my question is which one is incorrect ?
if default hightlight border color of InputText in android is `accentColor`, why in flutter isn't ?

**Comment by zoechi** [comment]
@HansMuller ?

**Comment by DJafari** [comment]
@zoechi i check updated material design that introduced in `AndroidX`
in new material design introduced a new color with : `colorSecondary` name
some control color such as `checkBox`, `radioButton`, `floatingActionButton` is `colorSecondary`
and some (`TextInputLayout`, `Button`) color is `colorPrimary`

![screenshot_1550225817](https://user-images.githubusercontent.com/1963047/52850363-861cd480-3128-11e9-96a4-37733877a987.png)

according to this :
1. in flutter there is no color customization with `colorSecondary` name
2. default color of button is incorrect
3. colorAccent must be deprecated

and others that i have not found yet

**Comment by erikkubica** [comment]
@DJafari this and what I have noticed today #28138 are maybe related.

**Comment by HansMuller** [comment]
@DJafari it's been a long time since you opened this issue and I apologize for the lack of activity. If you're still interested in the topic, there's a wide-ranging proposal for updating the button widgets and their themes in #54776. The new proposal does bind the default button colors to the overall theme's ColorSchme, per the Material Design spec.

I'm going to close this issue in favor of #54776.
