### ISSUE TITLE
get a list of all image and video files in a directory to display in app

### ISSUE THREAD

**Issue by JideGuru** [flutter/flutter#27974]
Hello, am looking for a way to get all image and video files in a particular directory in the mobile phone of a user to display in my app.

What i want to achieve is: i want an app like a gallery that will display all pictures in that in a folder in listview so users can choose one and do what ever they want with it. 

Thanks

**Comment by Kartik1607** [comment]
You would need to use [MethodChannels](https://flutter.io/docs/development/platform-integration/platform-channels) for this issue. For starting see if [file_picker package](https://pub.dartlang.org/packages/file_picker) would fit your needs.

**Comment by kangwang1988** [comment]
dart:io also would be helpful.

**Comment by kangwang1988** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
