### ISSUE TITLE
[firebase_auth] inconsistency in reporting user metadata

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#27986]
The firebase user data that I get from `FirebaseAuth.instance.currentUser()` is inconsistent. Here is the result that I get:

```json
{
  "android": {
    "uid": "ZyGkKQalyleXQiNqDyNMjlk8E4U2",
    "isAnonymous": false,
    "phoneNumber": "+498531790054",
    "providerData": [
      {
        "uid": "ZyGkKQalyleXQiNqDyNMjlk8E4U2",
        "phoneNumber": "+498531790054",
        "providerId": "firebase",
        "displayName": "Răzvan Lung"
      }
    ],
    "providerId": "firebase",
    "displayName": "Răzvan Lung",
    "creationTimestamp": 1550206057352,
    "lastSignInTimestamp": 1550206057352,
    "isEmailVerified": false
  },
  "ios": {
    "uid": "ZyGkKQalyleXQiNqDyNMjlk8E4U2",
    "isAnonymous": false,
    "phoneNumber": "+498531790054",
    "providerData": [
      {
        "email": null,
        "providerId": "phone",
        "photoUrl": null,
        "displayName": null,
        "uid": null,
        "phoneNumber": "+498531790054"
      }
    ],
    "providerId": "Firebase",
    "displayName": "Răzvan Lung",
    "email": "email@gmail.com",
    "photoUrl": null,
    "lastSignInTimestamp": 1550207896,
    "creationTimestamp": 1550206057,
    "isEmailVerified": false
  }
}
```

The timestamps are a big issue. Also on android the provider is different.

**Comment by zoechi** [comment]
With inconsistent you mean different between iOS and Android?

**Comment by long1eu** [comment]
yes

**Comment by nemoryoliver** [comment]
I second this... Timestamp values are different on each platform and the providerId character case.

**Comment by gisinator** [comment]
Yes, I can confirm this behaviour. On iOS, timestamps are returned as seconds, while on Android they're returned as miliseconds. Any chance this can be fixed?

**Comment by dcoleyoung** [comment]
In the javascript API, the photoUrl is retrieved as "photoURL" and in the firebase_auth it is "photoUrl".  Separate issue?

**Comment by long1eu** [comment]
I don't think this is an inconsistency. If you look at the C++ SDK you will
see the name is different there also. Then naming can follow the
conversation of the  language. The issue here is the value it contains.

**Comment by dcoleyoung** [comment]
Got it; thanks for the clarification.  I guess when I google firebase docs JavaScript is the first result and I should rely on dart and flutter official.

**Comment by long1eu** [comment]
@collinjackson Can you please assign this to me?

**Comment by kroikie** [comment]
@long1eu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/440. Any further collaboration will be done there.
