### ISSUE TITLE
Unwanted 1 pixel gap between expanded widgets.

### ISSUE THREAD

**Issue by glennmichaelmejias** [flutter/flutter#27991]
need help with my design. there is always unwanted gap between widgets with the same color.

[https://i.stack.imgur.com/li68E.png](https://i.stack.imgur.com/li68E.png)

**Comment by kangwang1988** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
Duplicate of #14288
