### ISSUE TITLE
How do I create a missing Info.plist?

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#2799]
I don't think we should spend a ton of time on this case, but fixing the error message to provide a suggestion would be nice.  I have an older flutter project on my personal machine which I was trying to run with the latest flutter just now.

```
2016-03-19 08:24:37.543 defaults[21404:941524] 
The domain/default pair of (/Stuff/Projects/bridge/dist/flx/ios/Info, CFBundleIdentifier) does not exist
2016-03-19 08:24:37.646 defaults[21405:941531] 
The domain/default pair of (/Stuff/Projects/bridge/dist/flx/ios/Info, CFBundleIdentifier) does not exist
No application found for TargetPlatform.ios_x64.
Is your project missing an ios/Info.plist?
```

**Comment by eseidel** [comment]
I just did a flutter create of a new project and copied out the ios directory.  Maybe that's the right solution.

**Comment by chinmaygarde** [comment]
You can also just `flutter create` an existing project. It will fill out the missing files.
