### ISSUE TITLE
Flutter + Firebase | java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist

### ISSUE THREAD

**Issue by santjosie** [flutter/flutter#28003]
I am trying to complete a very simple exercise by **connecting** my basic **Flutter** app **to Cloud Firestore** (in Firebase).

I have followed the instructions with regards to setup from codelab and Youtube videos from the Google Developers channel. However, I am getting the following error.
```
E/MethodChannel#plugins.flutter.io/cloud_firestore(13217): Failed to handle method call E/MethodChannel#plugins.flutter.io/cloud_firestore(13217): java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist.
```
I have added the detailed info in SO thread [https://stackoverflow.com/questions/54707794/flutter-firebase-java-lang-illegalstateexception-firebaseapp-with-name-def](https://stackoverflow.com/questions/54707794/flutter-firebase-java-lang-illegalstateexception-firebaseapp-with-name-def)

High level config done
1. Updated the android build.gradle file
2. Updated the android\app build.gradle file
3. Added dependency to pubspec.yaml
4. Placed the google-services.json file

Am I missing something in the steps? Please advise

## Logs

**Output of flutter run -verbose**
Attaching as a file
[flutter run --verbose.txt](https://github.com/flutter/flutter/files/2869678/flutter.run.--verbose.txt)

**Output of flutter analyze**
```
playground>flutter analyze
Analyzing playground...
No issues found! (ran in 4.4s)
```
**Output of flutter doctor -v**
```
playground>flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-GB)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\sanjose\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    X Android license status unknown.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
#27485, #18405 are similar but no feedback what fixed it for them. 
All others are just about ensuring the steps in the README were followed correctly.
You could try `flutter clean`, but not too optimistic this changes anything.

**Comment by santjosie** [comment]
@zoechi Thank you so much! Actually flutter clean and then re-running did help!

**Comment by hamza-sabri** [comment]
> #27485, #18405 are similar but no feedback what fixed it for them.
> All others are just about ensuring the steps in the README were followed correctly.
> You could try `flutter clean`, but not too optimistic this changes anything.

brooooo thank u very much 
I tried flutter clean and it worked like magic

**Comment by YazeedAlKhalaf** [comment]
flutter clean did not work for me

PlatformException (PlatformException(error, FirebaseApp with name [DEFAULT] doesn't exist. , null))

**Comment by theastronomer123** [comment]
I tried flutter clean and it didn't work for me.

**Comment by sunaarun** [comment]
@zoechi thank you .. I faced the same problem , and I did clean for project  flutter clean ,the error gone  .
Thank you

**Comment by siliosffreitas** [comment]
I fix this problem, in my case I open the folder android in Android Studio. He download any libs.

**Comment by anranj** [comment]
Flutter clean didn't solved the problem

**Comment by HariProtosem** [comment]
fsef

**Comment by HariProtosem** [comment]
Step 1 : Close the android emulator or disconnect the device.
Step 2 : Run flutter clean in the terminal.
Step 3 : Connect the device.
Step 4 : Run your app.

Worked for me :)
