### ISSUE TITLE
I want to connect my app with a backend via ddp

### ISSUE THREAD

**Issue by villalobosleandro** [flutter/flutter#28005]
I have managed to consume data from an http backend but now I am looking to connect to a supported meteor that its connection type is ddp and I can not perform the queries in the same way as http, someone has managed to implement the plugin that comes out on the official flutter website ? https://pub.dartlang.org/packages/ddp? or managed to connect in some other way to a backend via ddp?

**Comment by zoechi** [comment]
If pub.dartlang.org doesn't provide such a package, there probably isn't one yet. 
Doesn't Meteor also support GraphQL? (never tried Meteor myself and have no related knowledge)

**Comment by villalobosleandro** [comment]
I have never used graphql but I will investigate a little

**Comment by BugsBunnyBR** [comment]
So.. there is this package https://pub.dev/packages/ddp from https://github.com/haoguo/ddp
That claims to be a ddp package for dart/flutter. have you tried it?

**Comment by ivanesi** [comment]
This package has issues and It looks like author don't use github anymore.

**Comment by stuartmorgan** [comment]
Closing as this appears to be a request for help with project-level code rather than a feature request, so would be suited for one of the resources at https://flutter.dev/community#community-grid rather than the issue tracker.
