### ISSUE TITLE
Shared Preferences - Storing mutable lists results in wierd behavior

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#28015]
This example sums up the problem -

```dart
  var prefs = await SharedPreferences.getInstance();
  var myList = <String>[];

  await prefs.setStringList("myList", myList);

  myList.add("foobar");

  print(prefs.getStringList("myList")); // [foobar]
```

I expected to get an empty list back, but it was susceptible to the mutation!

I am aware that the solution is to use `.toList()` before calling `setStringList` , but shouldn't that be the default behaviour? I found this incredibly hard to debug..

**Comment by kangwang1988** [comment]
Because myList is stored as object in share_preference, 
```

  /// Saves a list of strings [value] to persistent storage in the background.
  ///
  /// If [value] is null, this is equivalent to calling [remove()] on the [key].
  Future<bool> setStringList(String key, List<String> value) =>
      _setValue('StringList', key, value);

  /// Removes an entry from persistent storage.
  Future<bool> remove(String key) => _setValue(null, key, null);

  Future<bool> _setValue(String valueType, String key, Object value) {
    final Map<String, dynamic> params = <String, dynamic>{
      'key': '$_prefix$key',
    };
    if (value == null) {
      _preferenceCache.remove(key);
      return _kChannel
          // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
          // https://github.com/flutter/flutter/issues/26431
          // ignore: strong_mode_implicit_dynamic_method
          .invokeMethod('remove', params)
          .then<bool>((dynamic result) => result);
    } else {
      _preferenceCache[key] = value;
      params['value'] = value;
      return _kChannel
          // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
          // https://github.com/flutter/flutter/issues/26431
          // ignore: strong_mode_implicit_dynamic_method
          .invokeMethod('set$valueType', params)
          .then<bool>((dynamic result) => result);
    }
  }

  /// Reads a set of string values from persistent storage, throwing an
  /// exception if it's not a string set.
  List<String> getStringList(String key) {
    List<Object> list = _preferenceCache[key];
    if (list != null && list is! List<String>) {
      list = list.cast<String>().toList();
      _preferenceCache[key] = list;
    }
    return list;
  }
```
I think it works as designed.

**Comment by zoechi** [comment]
I also think this is counterintuitive if not a bug.

**Comment by kangwang1988** [comment]
cc @mehmetf 
Should a copy of the object stored when using setValue?

**Comment by devxpy** [comment]
Yes. A `List<String>.from()` call while both `set` and `get` operations would be great!

I think that It is also required while doing a get request. Or else user can mutate the list inside shared preferences after doing a get..

**Comment by mehmetf** [comment]
Yes, we should not be giving you mutable data structures from the plugin.

Not only this is counterintuitive, it is also semantically wrong as the mutated object is not stored in the file system at all so it leads to a mismatch between the Dart cache and the FS.

Please feel free to send a PR to fix this, I am happy to review!

**Comment by patelkrunal78** [comment]
If you convert it to a string, you can store it

import 'dart:convert';
...
var s = json.encode(myMap);
// or var s = jsonEncode(myMap);
json.decode(...)/jsonDecode(...) makes a map from a string when you load it.

Find at [Here](https://icetutor.com/question/can-i-store-a-map-inside-a-shared-preferences-in-dart/)
