### ISSUE TITLE
firebase_admob 0.8.0+1 overrides a deprecated API

### ISSUE THREAD

**Issue by IAmHasanHabib** [flutter/flutter#28025]
getting this error.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.8.0+1\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by MatiDeve** [comment]
I have the same problem

**Comment by zoechi** [comment]
It's just a "Note"

**Comment by eladcandroid** [comment]
Any news?

**Comment by Sheharyar566** [comment]
I have just updated to 0.9.0+7, and the note is still there.

**Comment by heinzan** [comment]
same too

**Comment by Row7** [comment]
Same here. Is this related with [https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html](url)?

**Comment by kroikie** [comment]
@IAmHasanHabib

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/438. Any further collaboration will be done there.

**Comment by kroikie** [comment]
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by tiago-meurer** [comment]
I'm still getting this error. Any news?

**Comment by uzumaki258** [comment]
Still getting this error.

**Comment by nmnclk** [comment]
i heve same problem

**Comment by kw2019ltd** [comment]
still same
 Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.9.0+10/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.

flutter doctor -v
09:07
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)

**Comment by iapicca** [comment]
Hi @IAmHasanHabib 
are you still experiencing this issue?
@kw2019ltd 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
