### ISSUE TITLE
Make onCameraIdle return CameraPositionCallback

### ISSUE THREAD

**Issue by erf** [flutter/flutter#28043]
I need to detect when the camera stops moving / panning in GoogleMap like the `OnCameraChangeListener` described [here](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraChangeListener). 

Per now i can only find one `addListener` method in `GoogleMapController`, which detects all kinds of events. 

I also need to get the camera/map boundaries ( SW, NE ) from the `GoogleMapController` and pass it to a function. ( maybe i should create a new issue for this ).

I'm using `google_maps_flutter: ^0.2.0+3` on an iOS simulator.

`flutter doctor -v`:

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale en-NO)
    • Flutter version 1.1.8 at /Users/erlend/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/erlend/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by pepegich** [comment]
@erf Can you clarify exactly what events are needed? onMoveStarted, onMove and onIdle already implemented in plugin

**Comment by erf** [comment]
@pepegich you are correct. this was fixed in `0.4.0`.

**Comment by erf** [comment]
@pepegich i would like to see `onMoveEnded` event, when camera stopped moving.

**Comment by erf** [comment]
@pepegich forget it i see the `onCameraIdle` implement this..

**Comment by erf** [comment]
@pepegich i would like to see `onCameraIdle` return a `CameraPositionCallback`.

**Comment by Yaffar** [comment]
Did you ever find an approach to this? I have been bangin my head trying to figure it out :C

**Comment by erf** [comment]
@Yaffar Yes. I use `onCameraIdle` to do requests when camera stops moving, and i'm using `_mapController.getVisibleRegion()` to get the lat lng bounds. The `_mapController` i set in `onMapCreated`. Hope this helps. I forgot about this issue, will close it now.
