### ISSUE TITLE
add equivalent to andoroid's getActionBar()

### ISSUE THREAD

**Issue by The-Redhat** [flutter/flutter#28048]
Hey, when using a drawer as your main app navigation, you cannot change the AppBar from a drawer page. It would be nice if there's a possibility to call AppBar.of(context) to change the title and the actions of the AppBar like on android with getActionBar().

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by The-Redhat** [comment]
I don't quite understand your answer. I requesting a feature that in my opinion is missing. On which platform should I do this?

**Comment by zoechi** [comment]
I'd suggest to ask on StackOverflow and if it turns out a missing feature prevents you from achieving this, then please add a comment with a link to the SO question to have the issue reopened or create a new issue.

**Comment by The-Redhat** [comment]
I have a solution for my problem, but I think that should provide this feature out of the box.
