### ISSUE TITLE
Hero animation not triggered with Navigator.pushReplacement

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#28041]
Hero animations are not triggered when replacing a route. I'd like to use that for example at the end of an on-boarding flow where the 'main' page replaces the `on-boarding` page.

~It can be easily fixed by implementing `HeroController.didReplace` but it's probably good to discuss here whether it is desired.~

Minimal example:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Page1(),
      );
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () => Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (context) => Page2())),
          child: Hero(
            tag: "superman",
            child: Container(
              width: 40,
              height: 40,
              color: Colors.red,
            ),
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Hero(tag: "superman", child: Container(width: 60, height: 60, color: Colors.red)),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.2.2-pre.21 at /Users/spkersten/Development/flutter
    • Framework revision 035e0765cc (3 hours ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
```

**Comment by spkersten** [comment]
My initial thought of implementing `didReplace` in `HeroController` isn't good as `NavigatorObserver.didReplace` is also called for replacements somewhere down the stack that are invisible and should not trigger animations.

Some options:
- Add a `didPushReplacement` to `NavigationObserver` and call that instead of `didReplace` from `NavigatorState.pushReplacement`;
- Call `NavigationObserver.didPush` instead of `didReplace` from `NavigatorState.pushReplacement`;
- Add a parameter to `NavigationObserver.didReplace` that indicates whether it was a push.

All are breaking changes, however the first two potentially break user code silently, while the last causes an analyser issue that is trivial to solve.

**Comment by goderbauer** [comment]
In NavigationObserver.didReplace you get the new route that replaced the old. On that new route you could call Route.isCurrent and only trigger Hero transitions if that returns true, which means the topmost route got replaced.

**Comment by AlexVincent525** [comment]
@goderbauer Hi! Is this truly solved? Using the latest dev version of flutter still has no transition for hero replacement.

Sample code: (`pushReplacement` from splash to login)
`SplashPage route`:
```
Hero buildLogo() {
  return new Hero(
    tag: "Logo",
    child: Container(
      margin: EdgeInsets.all(30.0),
      child: new Image.asset(
        'images/logo.png',
        width: 120.0,
        height: 120.0,
      )
    )
  );
}
```
`LoginPage route`:
```
Hero buildLogo() {
  return new Hero(
    tag: "Logo",
    child: Container(
      margin: EdgeInsets.only(bottom: 10.0),
      child: new Image.asset(
        'images/logo.png',
        width: 100.0,
        height: 100.0,
      )
    )
  );
}

```
```
[√] Flutter (Channel master, v1.5.6-pre.8, on Microsoft Windows [Version 10.0.17763.437], locale zh-CN)
    • Flutter version 1.5.6-pre.8 at H:\Android\flutter-dev
    • Framework revision e4a1913e01 (8 hours ago), 2019-04-23 17:20:22 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\AlexV\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

**Comment by goderbauer** [comment]
Can you post a fully runnable code example that I can just copy and run?

**Comment by AlexVincent525** [comment]
> Can you post a fully runnable code example that I can just copy and run?

Thank you for your reply, it seems that the default navigator duration was too fast that the hero can't animated so smooth, and debug mode made it harder to figure. It's now normal in release and with 5 seconds duration, everything was fine. 😄

**Comment by ghprod** [comment]
> > Can you post a fully runnable code example that I can just copy and run?
> 
> Thank you for your reply, it seems that the default navigator duration was too fast that the hero can't animated so smooth, and debug mode made it harder to figure. It's now normal in release and with 5 seconds duration, everything was fine.

Hi

Could you post full code? I'm having same problem

Thanks

**Comment by LiveLikeCounter** [comment]
@ghprod Thanks for you post. 
I applied your suggestion, but the Hero-animation didn't went so well, here is my result:
![HeroAnimation](https://user-images.githubusercontent.com/24720382/64616319-a3730200-d3dc-11e9-94a7-fdb3dffa3277.gif)

What do I have to fillin here:

`Navigator.of(context).pushReplacement(
                        PageRouteBuilder(
                          transitionDuration: Duration(seconds: 1),
                          pageBuilder: (_, __, ___) => Empty(),
                        ),
                      );`
?
