### ISSUE TITLE
primaryColorBrightness: Brightness.light - Brightness is not defined?

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#28049]
Brightness seems to be not defined when I upgraded today from stable to master. Hence, keyboard is dark now on iOS.

**Comment by jonahwilliams** [comment]
Please include `flutter doctor -v`.

> Brightness seems to be not defined

How are you using it? We did move brightness to the engine, but we re-exported it from everywhere that it is used including foundation, material, and cupertino libraries.

**Comment by msw333** [comment]
You could test with the code of the official friendlychat - not working for me...

https://github.com/flutter/friendlychat-steps/blob/master/full_steps/step_6_image_support/lib/main.dart

**Comment by jonahwilliams** [comment]
What part of friendlychat isn't working - I tried the offline portion and it seems to running correctly? Do you have error messages or stack traces you could post?

**Comment by msw333** [comment]
Unfortunately, I already switched back to stable, since I had a more severe error message (see other issue with navigator.dart). 

When I was defining theme data (analog to friendlychat), in this part ‚primaryColorBrightness: Brightness.ligh’ the IDE tells me that Brightness is unknown and marks it red. I don’t have this issue when switching to stable with the exact same code.

**Comment by zoechi** [comment]
Could be https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

I'm going to close because it can't be reproduced.
Please add a comment if you see this again to have it reopened or create a new issue.

**Comment by PiotrWpl** [comment]
I had the same problem, but workaround mentioned by @zoechi  and IDE restart helped me. Thanks!
