### ISSUE TITLE
Crash on Navigator.push when current route has nested Navigator containing pages with Heros

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#28042]
Minimal example:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Root());
}

class Root extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Navigator(
        onGenerateRoute: (settings) => MaterialPageRoute(builder: (context) => Page1()),
      );
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (context) => Page2())),
          child: Hero(
            tag: "superman",
            child: Container(width: 40, height: 40, color: Colors.red),
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Hero(
            tag: "superman",
            child: GestureDetector(
                onTap: () => Navigator.of(context, rootNavigator: true)
                    .push(MaterialPageRoute(fullscreenDialog: true, builder: (context) => Modal())),
                child: Container(width: 60, height: 60, color: Colors.red))),
      ),
    );
  }
}

class Modal extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(backgroundColor: Colors.purple);
}
```

Tapping the red square twice results in:

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: There are multiple heroes that share the same tag within a subtree.
flutter: Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
flutter: must have a unique non-null tag.
flutter: In this case, multiple heroes had the following tag: superman
flutter: Here is the subtree for one of the offending heroes:
flutter: # Hero(tag: superman, state: _HeroState#0b567)
flutter: # └KeyedSubtree-[GlobalKey#5c93c]
flutter: #  └Container(bg: BoxDecoration(color: MaterialColor(primary value: Color(0xfff44336))), constraints: BoxConstraints(w=40.0, h=40.0))
flutter: #   └ConstrainedBox(BoxConstraints(w=40.0, h=40.0), renderObject: RenderConstrainedBox#48feb relayoutBoundary=up4)
flutter: #    └DecoratedBox(bg: BoxDecoration(color: MaterialColor(primary value: Color(0xfff44336))), dependencies: [_LocalizationsScope-[GlobalKey#91878], Directionality, MediaQuery], renderObject: RenderDecoratedBox#7672f)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:210:15)
flutter: #1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:220:12)
```

In our case `Root` is a widget having several tabs, each with their own Navigator, while the root Navigator is used to (among other things) show modals route on (which should cover the tabbar).

This seems to be the cause of #25362 and #25218, but the issue is more generic.

```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.2.2-pre.21 at /Users/spkersten/Development/flutter
    • Framework revision 035e0765cc (3 hours ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)
```

**Comment by spkersten** [comment]
Possible solutions:
1. Associate each `Hero` with a specific `HeroController`. 
  a. `HeroController` gets an optional list of `Hero` tags it should animate. That list would have to be injected through `MaterialApp`. Or;
  b. `Hero` and `HeroController` share some common "controller tag". In this case the `MaterialApp` could use a default controller tag that is used by default by `Hero`s as well. `HeroController` only animates Heros with a controller tag equal this its controller tag. (Instead of a default controller tag, the absence of a controller tag could be used.)
2. When searching for `Hero`s (`Hero._allHeroesFor`), always use the last found `Hero` for a tag, assuming that earlier found `Hero`s are for routes further down the stack.

For 1a, one of the top-level widgets (whoever creates the `HeroController`) gets knowledge of widgets further down the tree (`Hero`s). That sounds like bad design. 

For 2, we lose the useful diagnostic warning about multiple `Hero`s with the same tag. And the logic of finding the only visible `Hero` with a certain tag seems fragile/too implicit. 

Option 1b sounds quit good though. It is entirely backwards compatible and it feel like a natural way to group `Hero`s. A downside I see is that won't support using one `Hero` to fly on transition of more than one `Navigator`. I don't think that is a common use case though (certainly not one of ours) and can easily be solved by use two `Hero`s (one for each `Navigator`). It also introduces a way of making mistakes: using mismatching controller tags. That is of a similar nature as the current `Hero` tags and is only relevant when actually using the controller tag.

**Comment by Hixie** [comment]
The simplest solution here seems to be to just have Navigators not walk into nested Navigators when looking for heroes. I think that's a reasonable behaviour, because heroes are intended to work at a route level, and what would it even mean to transition a hero from a nested route?

**Comment by spkersten** [comment]
@Hixie I'm not sure that solution would work for our case (or maybe only on the very short term). We have something like this:

- Navigator:
  - Onboarding with Hero A
  - Post-onboarding, tab controller: (should replace previous page but not possible yet #28041)
    - Navigator:
      - First daily UI page with Hero A
    - Navigator:
      - Settings page 1 with Hero B
      - Settings page 2 with Hero B

The issue appears when showing a modal route on the root navigator from "Settings page 2".

Having a hero transition from an onboarding page to the first page of a daily UI doesn't strike me as unreasonable.

**Comment by goderbauer** [comment]
@spkersten I am not sure I understand the use cause you pointed out in your last comment. You have the root navigator, which shows your onboarding page with Hero A. From there, you want to push a new page with a tab bar onto the root navigator and animate that Hero A into a place in the first tab. Each tab here has there own nested navigator, so the hero ends up in nested navigator. Is this what you want?

**Comment by spkersten** [comment]
@goderbauer Yes, that's what I meant.

To be fair, the first tab currently doesn't have a nested `Navigator` yet in our case. So what @Hixie proposed would work in the short term. But our app will eventually get that Navigator.

**Comment by goderbauer** [comment]
Understood. I am currently prototyping a fix for the crash that would still allow for the nested navigator case and is also transparent to the user (e.g. it doesn't require additional tags supplied by the user). Stay tuned.
