### ISSUE TITLE
Firebase_auth 0.8.1+1 crashes application

### ISSUE THREAD

**Issue by solanm3** [flutter/flutter#28050]
When I update Firebase_auth to use Android X it crashes my app, firebase_auth 0.7.0 works fine but I need to update it so I can work with other packages.

Below is the errors I am getting, no errors in Flutter Doctor.

```
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:645: error: cannot find symbol
  private void reportException(Result result, @Nullable Exception exception) {
                                               ^
  symbol:   class Nullable
  location: class FirebaseAuthPlugin
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:557: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:576: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:594: error: cannot find symbol
    public void onComplete(@NonNull Task<SignInMethodQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.GetSignInMethodsCompleteListener
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:186: error: cannot find symbol
                      public void onComplete(@NonNull Task<AuthResult> task) {
                                              ^
  symbol: class NonNull
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:452: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java:506: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
Note: C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by solanm3** [comment]
In the `android/gradle.properties:` file I added
`android.useAndroidX=true`
`android.enableJetifier=true`

I also changed the TargetSDK to 28 and set multiDexEnabled true in the  app\build.gradle file
Here are my new errors

`C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:14: error: package android.support.annotation does not exist
import android.support.annotation.MainThread;
                                 ^
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:15: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:16: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:17: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:18: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:193: error: cannot find symbol
        int permissionState = ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION);
                              ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:198: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
        ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:203: error: cannot find symbol
        return ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.ACCESS_FINE_LOCATION);
               ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\src\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:296: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {
                                   ^
  symbol: class NonNull`

and my pubspec.yaml dependencies

`dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.8.1+1
  firebase_core: 0.3.0+2
  cloud_firestore: 0.9.0+2

  geoflutterfire: 2.0.2
  location: 1.4.1

  google_sign_in: 3.2.2
  google_maps_flutter: 0.2.0+2
`

**Comment by zoechi** [comment]
I'd suggest to ask on StackOverflow.

**Comment by micajuine-ho** [comment]
Had the same error messages. Changed my `gradle.properties` file to include:
`android.useAndroidX=true
android.enableJetifier=true`

Was able to build after that, 
Now i'm just getting: 
`Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.8.1+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.0+2\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.`

**Comment by kangwang1988** [comment]
Android X issue.
See more at: https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility
