### ISSUE TITLE
Navigator.dart: failed assertion on master 

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#28058]
Error on master : In every Listview.builder (either wrapped in Streambuilder or Futurebuilder), I keep continuously clicking and after some time, the tap on the Listtiles is not possible anymore. If I continue clicking, the error pops up. No error on latest stable.

![c65a1ba4-d7ea-4cf7-9cd5-5b490ec776f7](https://user-images.githubusercontent.com/46572127/52905376-bd2edb00-3239-11e9-917e-ccaa89087ca0.png)

**Comment by zoechi** [comment]
Unfortunately this is not enough information to diagnose the problem.

Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by AkioSarkiz** [comment]
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.657], locale ru-RU)
    • Flutter version 1.17.1 at E:\Programs\flutterSDK
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: E:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at E:\Programs\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)
