### ISSUE TITLE
video_player mixWithOthers option for iOS?

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#28059]
I'm using the video_player package. The videos I wan't to play have no sound. I want to make it possible to listen to music while watching the videos. I have set the volume to 0.0 however on iOS it stops the background music whenever I play a video. On android it works. The plugin uses the AVPlayer for iOS. As far as I know this player has a option `mixWithOthers` that should make it possible to play videos with background music. Is there an option to set this behavior for the video_player?

**Comment by recastrodiaz** [comment]
Is this issue fixed in https://github.com/flutter/plugins/pull/2939/files ?

**Comment by stuartmorgan** [comment]
Closing as fixed
