### ISSUE TITLE
firebase_auth signInWithEmailAndPassword NullPointerException

### ISSUE THREAD

**Issue by CaptMustache** [flutter/flutter#28057]
Hi,

i fail to signin users in my sample app. I activated the auth method email in firebase and also imported the services json (working already perfect with firestore)  

Calling this firebase method returns the exception you can see below:
`await FirebaseAuth.instance.signInWithEmailAndPassword(email: _email, password: _password);`

Exception:
```
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:405)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:107)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (12545): Error: PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference, null)
W/IInputConnectionWrapper(12545): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(12545): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(12545): getTextAfterCursor on inactive InputConnection
```
```yml
google_sign_in: ^4.0.1+1
firebase_auth: ^0.8.1+1
```
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-DE)
    • Flutter version 1.0.0 at /Users/cm/flutter/sdk
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cm/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)


```

**Comment by damccoy1** [comment]
I'm experiencing the same problem using the same version of firebase_auth. Like the user in this new StackOverflow thread, I'm able to use the function in iOS, but not in Android (it throws the Java null exception): https://stackoverflow.com/questions/54553913/flutter-firebase-auth-signinwithcredential-is-not-working-on-android

**Comment by damccoy1** [comment]
After doing the following, I don't get this error anymore, so whatever fix that needs to occur is likely related to these changes:

In pubspec.yaml: updated my sdk version from ">=2.0.0-dev.68.0 <3.0.0" to ">=2.1.0 <3.0.0"

In android/build.gradle: updated the dependency for com.android.tools.build:gradle:3.3.1 to use version 3.2.1 updated the dependency for com.google.gms:google-services:4.0.1 to use version 4.2.0

Also, since there ended up being a gradle issue with multidexing after these changes, I updated the android/app/build.gradle file to have a "multiDexEnabled true" property under defaultConfig and added "implementation 'com.android.support:multidex:1.0.3'" to the buildTypes

**Comment by anbarasuthresnathan** [comment]
> ```yaml
> google_sign_in: ^4.0.1+1
> firebase_auth: ^0.8.1+1
> ```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:429)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:108)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (11436): Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
W/IInputConnectionWrapper(11436): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11436): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11436): getTextAfterCursor on inactive InputConnection
E/FA      (11436): Task exception on worker thread: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />: com.google.android.gms.measurement.internal.zzgd.zzd(Unknown Source:601)
E/FA      (11436): Failed to load metadata: Metadata bundle is null
E/FA      (11436): Failed to load metadata: Metadata bundle is null

**Comment by anbarasuthresnathan** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.

Hi ,

 I tried to do firebase Authentication , I activated the auth method email in firebase and also imported the google services json.

Followed the tutorial 
``` https://github.com/RobertBrunhage/Youtube-Tutorials/tree/master/firebase_showcase ```
 but  i am getting the below error 
```java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:429)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:108)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(11436): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (11436): Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
W/IInputConnectionWrapper(11436): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(11436): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(11436): getTextAfterCursor on inactive InputConnection
E/FA      (11436): Task exception on worker thread: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />: com.google.android.gms.measurement.internal.zzgd.zzd(Unknown Source:601)
E/FA      (11436): Failed to load metadata: Metadata bundle is null
E/FA      (11436): Failed to load metadata: Metadata bundle is null ```

Please find my dependencies in ```pubspec.yaml``` file, I added 
```google_sign_in: ^4.0.1+1
     firebase_auth: ^0.8.1+4```
and also I have done the below steps

```Project-level build.gradle (<project>/build.gradle):

Copied

buildscript {
  dependencies {
    // Add this line
    classpath 'com.google.gms:google-services:4.0.1'
  }
}
App-level build.gradle (<project>/<app-module>/build.gradle):

Copied


Copied

dependencies {
  // Add this line
  implementation 'com.google.firebase:firebase-core:16.0.1'
}
...
// Add to the bottom of the file
apply plugin: 'com.google.gms.google-services'
```

but no luck, Please help to fix this issue

**Comment by alfredoqt** [comment]
Please help fix this issue @FlutterIssues

**Comment by Effizjens** [comment]
I had the same issue on my laptop, but not on my PC, so it had to be device specific.
I ran "flutter clean" and now it works fine!

My Firebase versions are.
`firebase_core: ^0.4.0+3
  firebase_auth: ^0.11.1+5
  cloud_firestore: ^0.12.2`

**Comment by kroikie** [comment]
@CaptMustache

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/436. Any further collaboration will be done there.
