### ISSUE TITLE
Enabling dart flags when running with debug dart built from source

### ISSUE THREAD

**Issue by john-reid-1000** [flutter/flutter#28060]
I have built flutter from source as per the instructions, but adding --debug-dart to the flutter/tools/gn invocation, to build with a debug dart. I am able to debug with GDB fine, but I am wondering how exactly I can pass the dart flags listed [here](https://github.com/dart-lang/sdk/blob/master/runtime/vm/flag_list.h) to the dart vm to have it output the various trace prints that are throughout the vm source. And if its possible to get this to output though logcat on android.

Thanks!

**Comment by pedromassangocode** [comment]
Hi @john-reid-1000 
Are you still facing this issue?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
