### ISSUE TITLE
webview_flutter ,please add “setWebViewClient” "setWebChromeClient"

### ISSUE THREAD

**Issue by gongxingg** [flutter/flutter#28063]
in Android Platform,please add such code ,else it may let you choose browser to open website

```
webView.setWebViewClient(new WebViewClient());
webView.setWebChromeClient(new WebChromeClient());
```

**Comment by samuelprogmattic** [comment]
where to add this please tell..in breif an new here

**Comment by stuartmorgan** [comment]
Closing as it's not clear what feature is actually being requested here; this describes an implementation rather than a goal.
