### ISSUE TITLE
latest flutter dev breaking firestore add/update on iOS

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#28065]
just upgraded the dev channel last night:

```
[✓] Flutter (Channel dev, v1.2.1, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.2.1 at /Users/neil/flutter
    • Framework revision 8661d8aecd (2 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

and all firestore updates and adds, inside and outside of transactions, are throwing an error of:

`PlatformException(Error 0, null, null)
`

the add/update was actually successfully executed, but it's triggering the catchError.  so this:

DocumentReference _someRef = await dbTable.add(_someObj).catchError((e) {
    print(e);
});

will trigger even though the data was written.  i'd test it on android too but i'm currently wrestling with cascading failures from the androidX upgrades.

**Comment by blaneyneil** [comment]
closing this since after reverting to flutter stable, and bumping cloud_firestore, firebase_storage, firebase_auth down minor versions, then gradually bumping all of them back up, then bumping from flutter stable to beta, where the problem reoccurred, where i then repeated the above package reversion and then subsequently upgraded, there's no longer a problem.  i can't explain it.

**Comment by sensuikan1973** [comment]
i have same problem...

**Comment by blaneyneil** [comment]
i think it's a firebase_core problem, but it's impossible to tell because the error message provides no clue.  what worked for me was the following:

1) remove everything in your flutter .pub-cache/ 
2) revert to the following in pubspec:
firebase_auth: "^0.7.0"
cloud_firestore: "^0.8.2+3"
firebase_storage: "^1.1.0+1"
3) flutter packages get (your build should work after this)
4) now this should work as a normal update:
  firebase_auth: "^0.8.1+1"
  cloud_firestore: "^0.9.0+2"
  firebase_storage: "^2.0.1+1"

**Comment by andreidiaconu** [comment]
I think this should be reopened. I'm getting the same error

**Comment by andreidiaconu** [comment]
The latest version `0.9.0+2` is the one causing issues. The commit is 
https://github.com/flutter/plugins/commit/0a923c1fb7cec424e273585e6164eb5173d496c7 - going to the previous version (`0.9.0+1`) fixed it for me.

About these `+1`, `+2` versions: I'm not sure if the `+2` is supposed to mean "This is basically the same code, we're just changing some pub metadata, but if that is what it's supposed to do, then this version should have been `0.9.1` and not `0.9.0+2`. The reason I say this is that if I use `0.9.0+2` right now and want to start using `0.9.0+1`, `flutter packages get` or `update` seems to completely ignore what I want and just uses `0.9.0+2` anyway. If someone can shed some light on how these versions work and what their purpose is, I would appreciate it. Thanks

Here is the workaround in case anyone needs it.
```
  cloud_firestore:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/cloud_firestore
      ref: 51696552700af8692fd7d595237fc9c4e273de93
```

Which is using the github version directly, from the previous commit, 
https://github.com/flutter/plugins/commit/51696552700af8692fd7d595237fc9c4e273de93

The PR for 0.9.0+2 is 
https://github.com/flutter/plugins/pull/1226

Also, I may be jumping to conclusions, so @sensuikan1973 can you confirm the workaround works for you? 

@blaneyneil I am curios to know what actual version your build is using, if you don't mind taking a look. I'm thinking that maybe by downgrading and upgrading back, you somehow ended up with `0.9.0` and not `0.9.0+2`. You can check by looking in the `ios/.symlinks/plugins/cloud_firestore` folder, and opening `pubspec.yaml`. Thanks!

**Comment by blaneyneil** [comment]
nope, it's indeed 0.9.0+2.  yeah, ignoring the +1 was why i reverted to a lower minor version.   the reason i think it's a firebase_core issue is because the only way i got it to work was by downgrading and then upgrading auth and storage along with firestore.

**Comment by sensuikan1973** [comment]
@andreidiaconu @blaneyneil 
Thanks. it wroks.
```
  cloud_firestore:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/cloud_firestore
      ref: 51696552700af8692fd7d595237fc9c4e273de93
```

**Comment by msw333** [comment]
It doesn't solve it for me. I am getting `[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
PlatformException(Error 0, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
<asynchronous suspension>
#2      DatabaseReference.set (file:///Users/matthiaswolff/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_database-2.0.1+1/lib/src/database_reference.dart:76:31)
#3      ChatScreenState._handleSubmitted (package:first_app/chats/group_chats/chat_screen.dart:637:24)
#4      ChatScreenState._buildTextComposer.<anonymous closure> (package:first_app/chats/group_chats/chat_screen.dart:529:37)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
` etc...

**Comment by cyanglaz** [comment]
This issue was fixed by https://github.com/flutter/plugins/pull/1274. If any related issue is found, please feel free to reopen the issue ticket with more details.
