### ISSUE TITLE
DataTable max column length

### ISSUE THREAD

**Issue by wws19125** [flutter/flutter#28066]
I want to display calendar view on my app, i decided to use datatable for this purpose. when the length of the columns beyond five, datatable not working

```dart
return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: <Widget>[
        Container(
          padding: const EdgeInsets.fromLTRB(13, 13, 13, 20),
          child: DataTable(
            columns: <DataColumn>[
              DataColumn(label: Text("1")),
              DataColumn(label: Text("1")),
              DataColumn(label: Text("1")),
              DataColumn(label: Text("1")),
              DataColumn(label: Text("1")),
              DataColumn(label: Text("1")),
            ],
            rows: <DataRow>[
              DataRow(
                cells: dayNames.map((String dayName){
                  return DataCell(Text(dayName));
                }).toList(),
              )
            ],
          )
        ),
        Text("bbcc")
      ],
    );
  }
```
```dart
List<String> dayNames = [
  "一","二","三","四","五","六","日"
];
```

![image](https://user-images.githubusercontent.com/3598933/52907828-68747a00-32a4-11e9-9a05-0120e71d17d8.png)

I also found another problem, the text in cells is not centered correctly

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
