### ISSUE TITLE
First deeplink is opened all the time

### ISSUE THREAD

**Issue by teshlya** [flutter/flutter#28062]
I use firebase_dynamic_links 0.2.0 in my application. Opening a deeplink is all right, but when I open another link again, the first deeplink opens.

**Comment by zoechi** [comment]
Might be #24629

**Comment by bparrishMines** [comment]
Closing this since it seems to be a dup of https://github.com/flutter/flutter/issues/24629

**Comment by kroikie** [comment]
@teshlya

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/435. Any further collaboration will be done there.
