### ISSUE TITLE
iOS devices , crashed on 'flutter run'

### ISSUE THREAD

**Issue by MangoRabbin** [flutter/flutter#28068]
When I run flutter of iOS version, it crashes with fatal error, I tried to solve for a long time but I couldn't solve. How can I fix it?

## Logs

> Launching lib/main.dart on iPhone XR in debug mode...
> Running pod install...
> Starting Xcode build...
> Xcode build done.                                           19.0s
> 5.16.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
> 5.16.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50500000 started
> 5.16.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x000000010da8a1bb __exceptionPreprocess + 331
> 	1   libobjc.A.dylib                     0x000000010d030735 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010d9d64ec _CFThrowFormattedException + 194
> 	3   CoreFoundation                      0x000000010daf9541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
> 	4   CoreFoundation                      0x000000010da85c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
> 	5   Runner                              0x000000010906f849 getDictionaryFromFIRApp + 217
> 	6   Runner                              0x000000010906f691 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 4225
> 	7   Flutter                             0x000000010abb85fa __45-[Flutt<…>
> Lost connection to device.
> Syncing files to device iPhone XR...

## flutter doctor -v

> [✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale ko-KR)
>     • Flutter version 1.1.8 at /Users/mine/development/flutter
>     • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
>     • Engine revision 7112b72cc2
>     • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/mine/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio
>       2.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.6.0
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio 2.app/Contents
>     • Flutter plugin version 33.0.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] Connected device (1 available)
>     • iPhone XR • 4D76FF85-05A0-47D3-A824-F2D2EA50EAB2 • ios • iOS 12.1 (simulator)
> 
> • No issues found!

**Comment by MangoRabbin** [comment]
## flutter doctor -v

> [✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale ko-KR)
>     • Flutter version 1.1.8 at /Users/mine/development/flutter
>     • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
>     • Engine revision 7112b72cc2
>     • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/mine/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.6.0
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio 2.app/Contents
>     • Flutter plugin version 33.0.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] Connected device (1 available)
>     • iPhone XR • 4D76FF85-05A0-47D3-A824-F2D2EA50EAB2 • ios • iOS 12.1 (simulator)
> 
> • No issues found!

**Comment by kangwang1988** [comment]
Duple of: https://github.com/flutter/flutter/issues/25759

**Comment by zoechi** [comment]
Duplicate of #16534
(this one is still open)

**Comment by MangoRabbin** [comment]
I follow the solution(#25759), but It's not work ... I think It has problems in FirebaseApp.configure..(firebase_core)
```
  Future<void> appInitialize() async {
    final FirebaseApp app = await FirebaseApp.configure(
      name: 'PrivacyofAnimal',
      options: const FirebaseOptions(
        googleAppID: iosAppID,
        apiKey: appAPIKey,
        projectID: projectID
      )
    );
```

**Comment by ffeu** [comment]
This issue is solved by this [PR](https://github.com/flutter/plugins/pull/1279) and `firebase_core` version `0.3.1+1`.

**Comment by zoechi** [comment]
@MangoRabbin the issue should be fixed. Please let us know if you are still seeing this.

**Comment by MangoRabbin** [comment]
@ffeu @zoechi  Thank you. I change the version and It is working !!!.
