### ISSUE TITLE
get error when turn to stable1.0.0 from beta 0.10.12

### ISSUE THREAD

**Issue by hyz1992** [flutter/flutter#28070]
rect is null.there will be a exception

![The screen shot](https://s2.ax1x.com/2019/02/17/kymTP0.png)

**Comment by ened** [comment]
Please post output if `flutter doctor -v`. Also, can you confirm your flutter versions? 
Are you trying to use a older version or something newer?

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
