### ISSUE TITLE
CI: Circular dependency between self-installing Android SDK and Flutter build

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#28076]
Would it be possible to let Gradle download Android SDK packages as explained in https://developer.android.com/studio/intro/update#download-with-gradle, instead of requiring an existing Android SDK to be installed?

## Steps to Reproduce

Running on CI:

1. Download Flutter SDK **only**, per instructions at https://flutter.io/docs/get-started/install
1. Clone an existing Flutter application from GitHub
1. Set `ANDROID_HOME` and copy accepted licenses hashes from developer workstation into `$ANDROID_HOME/licenses/`
1. Run `flutter build apk --debug` within the cloned application directory

To fix:

1. Change directory to `android` within the cloned application
1. Create `local.properties` containing `flutter.sdk=<flutter sdk path>`
1. Run `./gradlew build`, which will install necessary Android SDK packages
1. Re-run `flutter build` successfully

Note that running `./gradlew build` before `flutter build` fails for the lack of `local.properties`, i.e. these steps rely on an undocumented property to be set.

## Logs

Without an Android SDK:

```shell
$ flutter build apk --debug
No Android SDK found. Try setting the ANDROID_SDK_ROOT environment variable.
```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.1.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.8 at /home/artem/pkg/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)
```

**Comment by dnfield** [comment]
Gradle doesn't work that way - as mentioned in your link, it requires that at least an initial install is done for the SDK.  That said, we do have some CI scripts for downloading the Android SDK and could probably look to make that something we do in a more automated fashion.

Would you mind if I repurpose the bug for that?

**Comment by dnfield** [comment]
Actually, looking at your bug, it seems like there are a few issues going on here. If you want this for CI, you can take additional steps to ensure the Android SDK is available, depending on your CI provider.  Many provide pre-built environments with the Android SDK.  And if they don't, you should be able to script out a hook to download and unpack (and accept licenses for) the Android SDK.  It's a little more challenging on Windows than Mac or Linux, but entirely doable.

**Comment by dotdoom** [comment]
@dnfield can you point out for me where it mentions a requirement for initial install? The only thing I found is "as long as the corresponding SDK license agreements have already been accepted", which is what step 3 in the original post is. Besides, I am using this feature in multiple projects now, and can confirm that Gradle indeed works this way.

I'd like to avoid scripting Android SDK download if it's already done by Gradle. In my experience it is rather fragile, and becomes cumbersome to support for multiple projects especially when a new SDK is released, because it needs an update on developers' workstations, Gradle, and CI.

**Comment by dnfield** [comment]
Ahh, I see, I missed part of what you wrote there.

This sounds like our check for the Android SDK might be too strict in the tool.  I'll take a look.

**Comment by dnfield** [comment]
It looks like gradle has supported this since we added support for gradle - but for whatever reason we just never updated the tool to allow gradle to do this.  PR incoming.

**Comment by tvolkert** [comment]
Re-opening because the fix was reverted in https://github.com/flutter/flutter/pull/28295
