### ISSUE TITLE
What is the difference between flutter plugin and flutter module?

### ISSUE THREAD

**Issue by shahzadakram67** [flutter/flutter#28074]
I am new to flutter plugin development, I have read  [Developing packages & plugins](https://flutter.io/docs/development/packages-and-plugins/developing-packages) and [Writing a good Flutter plugin](https://medium.com/flutter-io/writing-a-good-flutter-plugin-1a561b986c9c), but I am confused as a beginner, I have developed Flutter Application based on [webview_flutter](https://pub.dartlang.org/packages/webview_flutter) and a JavaScript library to work offline. I want to extend it as a module or a plugin.

Webview renders some stuff.
JavaScript library is being attached from assets.

I am not calling any Platform API directly from my code but my code depends on another plugin.

How do I proceed this? As a plugin or as a module?

**Comment by zoechi** [comment]
Answered on https://stackoverflow.com/questions/54731733/what-is-the-difference-between-flutter-plugin-and-flutter-module/54733856#54733856
