### ISSUE TITLE
bottomNavigationBar doesn't work well.

### ISSUE THREAD

**Issue by inthewalter** [flutter/flutter#28080]
![image](https://user-images.githubusercontent.com/28642472/52914187-c0dd6300-3308-11e9-8209-5d5d2e30635d.png)

```dart
      bottomNavigationBar: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            // Where the linear gradient begins and ends
            begin: Alignment(0.7, 1.0),
            end: Alignment(-0.7, -1.0),
            // Add one stop for each color. Stops should increase from 0 to 1
            // stops: [0.6, 0.7],
            colors: [
              // Colors are easy thanks to Flutter's Colors class.
              Color.fromRGBO(245, 243, 106, 1.0),
              Color.fromRGBO(177, 238, 111, 1.0),
            ],
          ),
        ),
        child:  FlatButton(
          child: Text(
            "TEST",
            style: TextStyle(color:Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
          ),
          onPressed: () {
            Navigator.pop(context);
            _tabBloc.changeBottomTab(2);
          },
        )
      )
```

I've used `bottomNavigationBar` in `Scaffold`.
However, like the picture, iPhoneX's bottom bar's overlapped my `bottomNavigationBar`.
I want to it never overlap mine. 
Can I do automatically?

![image](https://user-images.githubusercontent.com/28642472/52914246-7dcfbf80-3309-11e9-89bf-016c22f5d8a8.png)

the code is
```dart
bottomNavigationBar: BottomNavigationBar(...)
```
And, other usage do work well...`

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Kartik1607** [comment]
You can add the Scaffold inside a SafeArea

**Comment by inthewalter** [comment]
> You can add the Scaffold inside a SafeArea

![image](https://user-images.githubusercontent.com/28642472/52929416-af876b80-3387-11e9-879f-8883dfcb212a.png)


I did add SafeArea()... but haha :0

**Comment by zoechi** [comment]
Thanks @Kartik1607 !

**Comment by anderscheow** [comment]
@inthewalter Perhaps you can add Padding bottom to your Container with the value of `MediaQuery.of(context).padding.bottom`
