### ISSUE TITLE
How can I set the background color of gridview

### ISSUE THREAD

**Issue by sp0cket** [flutter/flutter#28083]
Example Code:
```
GridView.builder(
            itemCount: 7,
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 3, mainAxisSpacing: 2.0, crossAxisSpacing: 2.0),
            itemBuilder: (ctx, idx) {
              return Card();   // or any other Widget
            },
          )
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

For example https://stackoverflow.com/questions/49267239/how-to-fill-background-colour-with-fixed-sized-grid

**Comment by sp0cket** [comment]
Just wrapper this Gridview into a Container with color is a simple solution.
Otherwise I must fill the last two item at the end of grid in this case

**Comment by tomasbaran** [comment]
Wrapping it in a container doesn't always make it, especially for SliverGrid. Look for the workaround in the meantime here: https://github.com/flutter/flutter/issues/62818
