### ISSUE TITLE
flutter doctor behaves differently from terminal to editor extension

### ISSUE THREAD

**Issue by albertoxamin** [flutter/flutter#28084]
## Steps to Reproduce

If I run `flutter doctor -v` from my terminal I get 
```
→ flutter doctor -v                                                                                                                             [6795bbb]
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-IT)
    • Flutter version 1.0.0 at /Users/alberto/Development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/alberto/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
    • IntelliJ at /Users/alberto/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • Alberto’s iPhone • 1453609438ec5c49fa4974995b76380e88349ced • ios • iOS 12.1.2

• No issues found!
```
but if I try to run it from the official editor extensions (both in vscode and intellij) i get
```
/Users/alberto/Development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-IT)
    • Flutter version 1.0.0 at /Users/alberto/Development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/alberto/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
    • IntelliJ at /Users/alberto/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
There are probably differences in environment variables.
What "editor extensions" are you talking about?
Have you tried restarting the IDE or the machine?

**Comment by albertoxamin** [comment]
@zoechi I'm talking about the official VSCode extension and intellij extension.
Restarting my machine and IDEs didn't fix the problem

**Comment by kangwang1988** [comment]
Here, there is only two difference, 
```
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.
```
```
[!] Connected device
    ! No devices available
```

They are in fact one issue, in other words, the libimobiledevice thing.
@albertoxamin 
When you get 
```
[!] Connected device
    ! No devices available"
```
from the extension, can you run `flutter doctor -vv` to get the full details from the terminal?

**Comment by zoechi** [comment]
@DanTup might know how to efficiently diagnose

**Comment by albertoxamin** [comment]
@kangwang1988 running `flutter doctor -vv` from terminal outputs

```
→ flutter doctor -vv
[  +15 ms] executing: [/Users/alberto/Development/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/alberto/Development/flutter/] git rev-parse
--abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/alberto/Development/flutter/] git ls-remote
--get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/alberto/Development/flutter/] git log -n 1
--pretty=format:%H
[  +56 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +1 ms] executing: [/Users/alberto/Development/flutter/] git log -n 1
--pretty=format:%ar
[  +19 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[        ] executing: [/Users/alberto/Development/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +27 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.0.0-0-g5391447
[ +152 ms] Doctor summary (to see all details, run flutter doctor -v):
[+3003 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
CFBundleShortVersionString
[ +241 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android
Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.2
[+1764 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +89 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
CFBundleShortVersionString
[        ] 3.2
[  +83 ms] java -version
[ +509 ms] executing: idevice_id -h
[  +38 ms] executing: idevice_id -h
[  +11 ms] executing: ideviceinfo -u 00008020-001C2D903C42002E
[  +22 ms] executing: pod --version
[ +173 ms] executing: /usr/bin/defaults read /Users/alberto/Applications/JetBrains Toolbox/IntelliJ IDEA
Ultimate.app/Contents/Info CFBundleShortVersionString
[  +73 ms] Exit code 0 from: /usr/bin/defaults read /Users/alberto/Applications/JetBrains Toolbox/IntelliJ IDEA
Ultimate.app/Contents/Info CFBundleShortVersionString
[        ] 2018.3.3
[  +96 ms] [✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-IT)
⣾[   +2 ms] executing: /Users/alberto/Library/Android/sdk/platform-tools/adb devices -l
[  +30 ms] Exit code 0 from: /Users/alberto/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +4 ms] executing: idevice_id -h
[  +66 ms] No device found with udid 00008020-001C2D903C42002E, is it plugged in?
[        ] executing: idevice_id -l
[   +5 ms] /usr/bin/xcrun simctl list --json devices
[ +269 ms] executing: /Users/alberto/Library/Android/sdk/platform-tools/adb devices -l
⣽[  +17 ms] executing: /Users/alberto/Library/Android/sdk/tools/bin/sdkmanager --licenses
[  +12 ms] executing: ideviceinstaller -h
⣻[  +22 ms] List of devices attached
[   +6 ms] executing: ios-deploy --version
[  +28 ms] executing: ios-deploy --version
[  +17 ms] 1.9.4
[   +1 ms] executing: ios-deploy --version
⢿[  +19 ms] executing: ios-deploy --version
[  +22 ms] 1.9.4
⢿[ +842 ms] 1.6.0

                    Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
                    Ignoring iStats-1.5.2 because its extensions are not built.  Try: gem pristine iStats --version 1.5.2
[+3757 ms] [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[        ] [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[        ] [✓] Android Studio (version 3.2)
[        ] [✓] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
[        ] [✓] VS Code (version 1.31.1)
[        ] [!] Connected device
[        ]     ! No devices available
[        ] ! Doctor found issues in 1 category.
[   +8 ms] "flutter doctor" took 11,342ms.
```

**Comment by kangwang1988** [comment]
@albertoxamin 
The corresponding output for `flutter doctor -vv` from the IDE extension is?

**Comment by albertoxamin** [comment]
@kangwang1988 I can't run that from the IDE extension

**Comment by kangwang1988** [comment]
> but if I try to run it from the official editor extensions (both in vscode and intellij) i get
/Users/alberto/Development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-IT)
    • Flutter version 1.0.0 at /Users/alberto/Development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

This action.

**Comment by DanTup** [comment]
There are two ways to run `flutter doctor` in VS Code though it's not clear which you're using:

1. Using the `Run Flutter Doctor` command in the VS Code command palette
2. Running from the built-in terminal

The likely cause for any differences is environment variables. If running in the built-in terminal, you could run `printenv` and compare it to the same in your normal terminal and see if there are differences. (Note: The Dart/Flutter extensions don't participate in the terminal in any way, so the results here will be the same even without them - though it's worth noting that VS Code will try to run some of your bash startup scripts to get a similar environment here).

If running the `Run Flutter Doctor` command from the command palette (which is the best way to run if trying to diagnose Flutter-related issues in VS Code, since it'll run with the same environment as things like the Flutter daemon and `flutter run` when debugging) then it's not so easy to get at the full environment, but we do log `PATH` if you enable the [Extension log](https://dartcode.org/docs/logging/#extension) which you could compare to `echo $PATH` in your terminal to see if there are things missing.

A common issue here is that people set `PATH` in terminal scripts that only run at terminal startup and don't affect the system (so VS Code doesn't have all the paths) so the first thing I'd do is compare the `PATHs` in an external terminal to the extension log.

**Comment by kangwang1988** [comment]
@DanTup 
In other words, there might be this case:
idevice_id is available using terminal while unavailable using the ide extension.
Right?
Henceforth, the iOS device detection differ.

**Comment by DanTup** [comment]
If `idevice_id` is at `/some/path/homebrew/bin/idevice_id` and `/some/path/homebrew/bin` is added to `PATH` in a terminal startup script that is *not* run for the environment VS Code spawns in, then I guess that could cause this (assuming `doctor` is looking for it on `PATH`).

Another way to confirm is to launch VS Code from the same terminal that "works" (if it's on `PATH` you can just run `code .`) - though be sure to close all Code instances first. That way VS Code will inherit the same environment that the terminal had, so if it works, it does confirm it's likely environment-related.

In that case, the best fix would be to move the setting of `PATH` to somewhere that applies globally (outside of the terminal) - for ex. on macOS I add all my paths into the `/etc/paths.d/` directory.

**Comment by albertoxamin** [comment]
> There are two ways to run `flutter doctor` in VS Code though it's not clear which you're using:

I tried both from VS Code the first one is from the integrated terminal, the second is from the `Run Flutter Doctor action`

> Another way to confirm is to launch VS Code from the same terminal that "works" (if it's on `PATH` you can just run `code .`) - though be sure to close all Code instances first. That way VS Code will inherit the same environment that the terminal had, so if it works, it does confirm it's likely environment-related.

It does work by starting the editor from the terminal, what are the PATH variables that i must add?
this is my current /etc/paths/ 
```
λ alberto [~] → cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/alberto/Development/flutter/bin
```
but `idevice_id` is in the path without terminal startup scripts
```
λ alberto [~] → which idevice_id
/usr/local/bin/idevice_id

λ alberto [~] → which ideviceinstaller
/usr/local/bin/ideviceinstaller

λ alberto [~] → which ios-deploy
/usr/local/bin/ios-deploy
```

**Comment by kangwang1988** [comment]
Just FYI:
```dart
✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
```
=>
```
bool get isInstalled => exitsHappy(<String>['idevice_id', '-h']);
```
fails.

```dart
✗ ios-deploy not installed. To install with Brew:
```
=>   Future<bool> get hasIosDeploy => exitsHappyAsync(<String>['ios-deploy', '--version']); 
fails

```
✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.
```dart

```
=>   bool get hasHomebrew => os.which('brew') != null;

**Comment by albertoxamin** [comment]
@kangwang1988 brew is located ad `/usr/local/bin/brew`, and I installed everything with homebrew

**Comment by DanTup** [comment]
> but `idevice_id` is in the path without terminal startup scripts

That's strange - if it's at `/usr/local/bin/idevice_id` and `/usr/local/bin` is in `/etc/paths` then I would expect this to work. Could you enable the [extension log](https://dartcode.org/docs/logging/#extension) then restart VS Code, open a Flutter project and then review the log? It should print the full `PATH` that was available to VS Code at the top.

**Comment by kangwang1988** [comment]
@albertoxamin 

You can also 
1. Modify "/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart"
to 
```dart
import 'package:flutter_tools/executable.dart' as executable;
import "dart:io";

void main(List<String> args) {
  Map<String, String> env = Platform.environment;
  print(env);
  executable.main(args);
}
```
2. delete flutter/bin/cache/flutter_tools.stamp (so that the flutter_tools will rebuild and your changes will take effect then).
3. run `flutter doctor -v` and i think all the environment info will be output.

**Comment by albertoxamin** [comment]
Terminal env
```
{
	TERM_PROGRAM: iTerm.app, 
	NVM_CD_FLAGS: -q, 
	SHELL: /usr/local/bin/zsh, 
	TERM: xterm-256color, 
	TMPDIR: /var/folders/qs/tth160ws3yj1d7dj_32rjmhr0000gn/T/, 
	Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.lDgKCwo7Yt/Render, 
	TERM_PROGRAM_VERSION: 3.2.7, 
	TERM_SESSION_ID: w0t0p0:528B2DB6-BF18-4151-8B79-3924708C97EA, 
	ZSH: /Users/alberto/.oh-my-zsh, 
	NVM_DIR: /Users/alberto/.nvm, 
	USER: alberto, 
	FLUTTER_ROOT: /Users/alberto/Development/flutter, 
	SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.Km2QIvpqE6/Listeners, 
	__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0, 
	PAGER: less, 
	LSCOLORS: Gxfxcxdxbxegedabagacad, 
	PATH: /usr/local/opt/libxml2/bin:/Users/alberto/.pyenv/shims:/Users/alberto/.nvm/versions/node/v10.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alberto/Development/flutter/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Applications/Wireshark.app/Contents/MacOS, 
	PWD: /Users/alberto, 
	ITERM_PROFILE: Default, 
	XPC_FLAGS: 0x0, 
	XPC_SERVICE_NAME: 0, 
	PYENV_SHELL: zsh, 
	COLORFGBG: 15;0, 
	HOME: /Users/alberto, 
	SHLVL: 2, 
	ITERM_SESSION_ID: w0t0p0:528B2DB6-BF18-4151-8B79-3924708C97EA, 
	LESS: -R, 
	LOGNAME: alberto, 
	LC_CTYPE: UTF-8, 
	NVM_BIN: /Users/alberto/.nvm/versions/node/v10.10.0/bin, 
	COLORTERM: truecolor, _: /Users/alberto/Development/flutter/bin/cache/dart-sdk/bin/dart
}
```

extension env
```
{
	SHELL: /bin/bash,
	TMPDIR: /var/folders/qs/tth160ws3yj1d7dj_32rjmhr0000gn/T/,
	Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.lDgKCwo7Yt/Render,
	FLUTTER_HOST: IntelliJ-IDEA,
	USER: alberto,
	COMMAND_MODE: unix2003,
	FLUTTER_ROOT: /Users/alberto/Development/flutter,
	SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.Km2QIvpqE6/Listeners,
	__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0,
	PATH: /usr/bin:/bin:/usr/sbin:/sbin,
	PWD: /Users/alberto/Development/flutter,
	XPC_FLAGS: 0x0,
	XPC_SERVICE_NAME: 0,
	SHLVL: 1,
	HOME: /Users/alberto,
	LOGNAME: alberto,
	_: /Users/alberto/Development/flutter/bin/cache/dart-sdk/bin/dart
}```

**Comment by DanTup** [comment]
> extension env
> PATH: /usr/bin:/bin:/usr/sbin:/sbin,

The problem seems to be that there's no `/usr/local/bin` in there. I just checked mine, and it does seem like things from my `/etc/paths` (as well as `/etc/paths.d`) are loaded when I open VS Code from the dock, so I'm not sure what that isn't happening for you 🤔

**Comment by albertoxamin** [comment]
Same problem with vscode
```
{
VSCODE_NODE_CACHED_DATA_DIR: /Users/alberto/Library/Application Support/Code/CachedData/1b8e8302e405050205e69b59abb3559592bb9e60, SHELL: /bin/bash, 
[...]
PATH: /usr/bin:/bin:/usr/sbin:/sbin
[...]
}
```

**Comment by DanTup** [comment]
Could you try using `/etc/paths.d/` and rebooting to see if that helps? (it's where most of my paths are, and is mentioned on that page). Just create a file at `/etc/paths.d/any-name` that contains `/usr/local/bin` and reboot and tests again.

Looking online, making paths apply globally on macOS is a minefield - I'm somewhat surprised it's all working for me (I do remember I had some issues using `/etc/paths`, but I think that was down to corp scripts overwriting it on every boot).

**Comment by albertoxamin** [comment]
@DanTup 
just restarted and it doesn't work
![image](https://user-images.githubusercontent.com/6067659/53015957-98f71800-344c-11e9-95d4-9b7b05b916b2.jpeg)
still outputs `PATH: /usr/bin:/bin:/usr/sbin:/sbin` on vscode

**Comment by DanTup** [comment]
@albertoxamin I'm not sure which way you're testing, but it's best to test with the Dart-Code extension log to avoid any possible interference with other scripts of VS Code's terminal (which seems to have weird quirks, as you've found in my issue 😕)

> also i found your issue [Microsoft/vscode#46693](https://github.com/Microsoft/vscode/issues/46693), how did you fix it?

I never got to the bottom of it (though as seen at the end, disabling the profile scripts seemed to fix it). It wasn't critical to me, as it was just for an idea I had (to try and get `flutter` into `PATH` for the built-in terminal based on the SDK that Dart Code detected). I figured even if I got to the bottom of it on my machines, loads of other people probably have the same so it probably wasn't usable for what I wanted.

**Comment by DanTup** [comment]
In the latest version of the Dart plugin for VS Code there's a `dart.env` setting which lets you override the environment for the Dart/pub/Flutter spawned processes. It's not really designed for this, but it may work as a workaround if you don't mind duplicating your PATH into it:

```
"dart.env": {
  "PATH": "put;your;full;path;here"
}
```

(if that doesn't work, file a bug at https://github.com/Dart-Code/Dart-Code)

I'm not sure what else we can do with this. The underlying issue seems to be that we can't get VS Code to launch with the `PATH` set by the system. I'm not sure if that's a VS Code quirk or a macOS one 🤔

**Comment by albertoxamin** [comment]
This actually works thanks!

**Comment by DanTup** [comment]
Great! Sorry it's not a particularly elegant fix, but I'm not really sure what else we can (easily) do from the extension side. If this turns out to be a problem that affects a lot of people, maybe we can revisit it and see if we can come up with something better.

Thanks!
