### ISSUE TITLE
veryfyPhoneNumber timeout not working

### ISSUE THREAD

**Issue by Zhengyangma** [flutter/flutter#28089]
It's not working,
I used the latest version of firebase_auth,
I want to disable auto retrieve feature by making the timeout duration 0 and it doesn't work at all.

Which makes my UX logic a mess.

Please fix it and give out a disabled auto retrieve code example.

My users feedbacked to me they don't like the auto retrieve SMS code features at all...

**Comment by kangwang1988** [comment]
cc @cyanglaz

**Comment by cyanglaz** [comment]
@collinjackson might be able to give more inputs on this.

**Comment by gayanpathirage** [comment]
This issue is fixed via PR https://github.com/flutter/plugins/pull/1396

**Comment by Zhengyangma** [comment]
> This issue is fixed via PR [flutter/plugins#1396](https://github.com/flutter/plugins/pull/1396)

Thanks for the update.

**Comment by kroikie** [comment]
@Zhengyangma

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/434. Any further collaboration will be done there.
