### ISSUE TITLE
fatal: Not possible to fast-forward, aborting. on windows

### ISSUE THREAD

**Issue by wangyankun33** [flutter/flutter#28091]
Steps to Reproduce
`  flutter upgrade`
Logs
```
Upgrading Flutter from D:\flutter...
fatal: Not possible to fast-forward, aborting.
```
Flutter Doctor
```
[√] Flutter (Channel dev, v1.2.1-pre.1, on Microsoft Windows [Version 10.0.16299.967], locale zh-CN)
    • Flutter version 1.2.1-pre.1 at D:\flutter
    • Framework revision 0245695186 (3 weeks ago), 2019-01-31 17:01:59 +0800
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidStudio\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidStudio\SDK
    • Java binary at: D:\AndroidStudio\AndroidStudio3.2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\AndroidStudio\AndroidStudio3.2
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\softword\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[√] Connected device (1 available)
    • vivo x6d • emulator-5554 • android-x86 • Android 5.1.1 (API 22)

• No issues found!
```

**Comment by dnfield** [comment]
Have you made changes to your flutter repo?

You could try going to `D:\flutter` and typing `git status` to see - it should end with the message `nothing to commit, working tree clean`.  If not, you need to figure out what you changed, whether you want to keep it (commit it to a different branch or stash it), or get rid of it (`git reset --hard` should do the trick, perhaps with a `git clean -xfd` if the reset isn't cutting it).

**Comment by zoechi** [comment]
Instructions how to get Flutter installation back to a clean state 
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by wangyankun33** [comment]
With your help, the problem has been solved! Thank you!


2603109625@qq.com
 
From: Dan Field
Date: 2019-02-18 15:16
To: flutter/flutter
CC: wangyankun33; Author
Subject: Re: [flutter/flutter] fatal: Not possible to fast-forward, aborting. on windows (#28091)
Have you made changes to your flutter repo?
You could try going to D:\flutter and typing git status to see - it should end with the message nothing to commit, working tree clean. If not, you need to figure out what you changed, whether you want to keep it (commit it to a different branch or stash it), or get rid of it (git reset --hard should do the trick, perhaps with a git clean -xfd if the reset isn't cutting it).
