### ISSUE TITLE
Resetting badge number on applicationDidBecomeActive creates strange behavior for the user

### ISSUE THREAD

**Issue by grundid** [flutter/flutter#28093]
I'm using the `firebase_messaging` plugin for push notifications. On iOS this plugins resets the badge number on each `applicationDidBecomeActive` in the `AppDelegate`. This also clears all notifications in the notifications center.

This creates unexpected behavior for the user in several cases:
1. if the user receives several notifications at once he is only able to click on one notification since the other notifications are deleted after the app is opened
2. if the user opens the app directly after receiving a notification the notifications are also lost
3. if we show a local notification using the flutter_local_notifications plugin while the app is the foreground the notification disappears once the user tries to open the notification center.

Please fix this behavior like described in the TODO or make it configurable so the badge number is not reset. In our case we are not sending a badge number with the push notification so resetting it is not needed.

**Comment by DarshanGowda0** [comment]
Hey @zoechi! Any updates on this?

**Comment by kroikie** [comment]
@grundid

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/433. Any further collaboration will be done there.
