### ISSUE TITLE
Failed to Download https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-measurement-connector-impl/17.0.5/firebase-measurement-connector-impl-17.0.5-javadoc.jar

### ISSUE THREAD

**Issue by haikalpe123** [flutter/flutter#28095]
When I sync the gradle, this warning keep appear on the terminal...
![error](https://user-images.githubusercontent.com/43090718/52937787-a780f900-3392-11e9-820b-9a3ebb565501.png)

even though it (maybe) doesn't affect my project, but this warning really annonying because i don't know the reason -_-  I dont remember using plugin/lib named **firebase-measurement** at all. 
Do you guys know how to fix it?

Btw this is my app&android/gradle

**app/gradle**

```
dependencies {

      implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
      implementation 'com.google.firebase:firebase-core:16.0.7'
      implementation 'com.google.android.gms:play-services-ads:17.1.3'
      testImplementation 'junit:junit:4.12'
      androidTestImplementation 'com.android.support.test:runner:1.0.2'
      androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
 apply plugin: 'com.google.gms.google-services'
```

**android/gradle**
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        maven { url 'https://maven.google.com' }
        jcenter()
    }
}
```

**Comment by zoechi** [comment]
Please post the error output as text instead of as screenshot.

**Comment by zoechi** [comment]
Perhaps https://stackoverflow.com/questions/54601501/could-not-get-resource-http-firebase-measurement-connector-impl-17-0-5-jav

**Comment by haikalpe123** [comment]
whoa... it works, the warning sign is gone! I'm changing the gradle.wrapper to "distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-bin.zip"

 but it throws another exception, why is that?

> org.gradle.internal.exceptions.LocationAwareException: New Gradle Sync is not supported due to containing Kotlin modules
>   Caused by: com.android.tools.idea.gradle.project.sync.ng.NewGradleSyncNotSupportedException: New Gradle Sync is not supported due to containing Kotlin modules

**Comment by zoechi** [comment]
A comment on https://stackoverflow.com/questions/54201216/android-studio-3-3-new-gradle-sync-is-not-supported-due-to-containing-kotlin-mo 

> I did the exact same steps, twice. It works. The first gradle sync it does do raise a warning but that's it. It compiles and runs fine. Kotlin 1.3.11, Gradle 4.10.1.. You're issue is * StreamCorruptedException*. –

Please try

**Comment by haikalpe123** [comment]
thanks, it works!

**Comment by kroikie** [comment]
@haikalpe123

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/432. Any further collaboration will be done there.
