### ISSUE TITLE
PageView on Page Change with FlareBackgound and Flare Icons on Stack, it's splashing white color.

### ISSUE THREAD

**Issue by satish754ss** [flutter/flutter#28099]
When I am rendering Two or more than tow flare animation as a background theme and some flare icons are there . So giving white splash colour in the right and left. The video is given in this link (https://www.dropbox.com/s/c2x6ytgbbcyoobv/2019_02_18_15_54_42_trim.mp4?dl=0)

**Comment by zoechi** [comment]
Perhaps better to report with flare.
https://github.com/2d-inc/Flare-Flutter/issues

**Comment by satish754ss** [comment]
Thanks,
But I resolve the issue, I converted ListView physics as PageView.
