### ISSUE TITLE
Profile setState() callers

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#281]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Nov 06, 2015 at 18:59 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1993_

---

We should have a mode where we track all the stack frames that end up calling setState() / markNeedsBuild(), and spit out a histogram of the main responsible parties.

**Comment by Hixie** [comment]
We'll close this and address this if we run into an actual case where this is an issue.
