### ISSUE TITLE
Flutter tool does not fully support custom local builds

### ISSUE THREAD

**Issue by jakesays-old** [flutter/flutter#28107]
The flutter tool only supports local builds with specific named output directories.

Given: `flutter build bundle --local-engine=dev-debug`
I get the following error: `No Flutter engine build found at flutter/engine/src/out/host_dev-debug`
My build is in `flutter/engine/src/out/dev-debug`

**Comment by kangwang1988** [comment]
How did you build your local engine?
@jakesays

**Comment by jakesays** [comment]
I started with the standard build instructions then tailored the args.gn to fit my needs.

Note my target device is running linux and isn't a phone.

**Comment by kangwang1988** [comment]
It would be a feature request. Now there are some assumptions in the "build engine&flutter run --local" logic.

**Comment by jakesays** [comment]
That works. My sort term fix is just a symlink.

**Comment by dnfield** [comment]
You need to have both a host and a platform related engine build.  Right now the way we look for that is assume that your host engine is prefixed with `host_`.  You could get around this with a symlin, or you could make sure your GN wiring outputs the relevant host engine there.

**Comment by dnfield** [comment]
Could you speak a bit more about the actual use case here?  What led you to customize the GN rules and output to a different directory?  It'd help determine where and how to fix this.

Right now, I suspect this is just WAI and we'd expect you to create the symlink you have (or create GN rules to create the host_custom_platform directory as well).

**Comment by jakesays** [comment]
@dnfield gn.py isn't flexible enough for one of our use cases. We have an embedded device that requires custom toolchains and custom sysroots both for the host tools and the target runtimes. 

Also I much prefer using args.gn directly as this is how I use it on several other projects. the gn python wrapper is great for generating the initial args.gn though.

The reasoning behind the different output names is the default ones are misleading. For example, `out/linux_arm_debug` - is that a debug build of the flutter engine or the flutter engine compiled in release mode for a developer/jit runtime?

Are you saying I need two flutter builds - one for the host, and one for the target? I was under the impression the target build also compiled it's host tools in out/*/clang_x86.

**Comment by dnfield** [comment]
I'm unfortunately not entirely sure about all the details, but I believe the host build has something more than just what's in the clang_x86 (or x64) dir.

@chinmaygarde or @jason-simmons or @cbracken  would know more.

**Comment by jason-simmons** [comment]
`linux_arm_debug` would be a build of the engine in debug/JIT mode.  The `--unoptimized` flag (and the corresponding `unopt` suffix on the build output directory name) indicate that the build was made using debug-style compilation flags.

Both a target build and a host build are required for using Flutter with `--local-engine`.  The `clang_x86` directory is not sufficient.

**Comment by zanderso** [comment]
@jakesays-old Could you be a bit more specific about the workflow that you're looking for? Based on the discussion here, I'm not really sure what new functionality is being proposed.

**Comment by JakeSays** [comment]
@zanderso Actually I don't think this is still an issue for me. I would be fine if you closed it.

**Comment by dnfield** [comment]
Related: https://github.com/flutter/flutter/issues/47550 - but there it's different because the fuchsia build target actually builds host dart as well.
