### ISSUE TITLE
cloud_firestore throwing PlatformException(Error 0, null, null) when calling setData()

### ISSUE THREAD

**Issue by nemoryoliver** [flutter/flutter#28103]
I am getting a weird and uninformative error. Also if I don't wrap setData() in a try catch it doesn't log the error to the console at all. Maybe caused by the updated Dart Code v2.23.0 VS Code extension?

## Steps to Reproduce

1. Using **cloud_firestore 0.9.0+2**
2. Update an existing document 

```dart
var document = firestore.collection("users").document("example_user_id");
  try {
    await document.setData({"test": "value"}, merge: true);
    print("successfully updated user");
  } on PlatformException catch (error) {
    print("error updating user: $error");
  }
```

## Logs

```
flutter: error updating user: PlatformException(Error 0, null, null)
```

## Flutter Doctor

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.8 at /Users/nemorystudios/Development/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nemorystudios/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • iPhone XS Max • 83E6CC4C-43C6-4E0F-99BA-CEDA1B336107 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by nemoryoliver** [comment]
I just discovered if I remove the await keyword on setData function it works.

**Working code:**

```
var document = firestore.collection("users").document("the_user_id_example");
  try {
    document.setData({"test": "value"}, merge: true);
    print("successfully updated user");
  } on PlatformException catch (error) {
    print("error updating user: $error");
  }
```

**Comment by gagaJay** [comment]
I found the same issue as well. Any update on this?

```
Future<void> updateOrderAsPaid(Order order) {
  return Firestore.instance
      .collection(COLLECTION_ORDERS)
      .document(order.id)
      .setData({'status': 'paid'}, merge: true);
}
```

Error: PlatformException(Error 0, null, null)

**Comment by gagaJay** [comment]
roll back to 0.8.2+3 and it works fine....

**Comment by tomalabaster** [comment]
Rolling back to 0.9.0 works fine as well.

**Comment by shawnchan2014** [comment]
Same here. All the versions `>=0.9.0` do not work for me on iOS.

**Comment by Isaiaher** [comment]
I am also getting the error and cannot role back to `0.8.2+3` because I am getting the error
```
Because mobile_hiking_app depends on cloud_firestore ^0.8.2+3 which depends on firebase_core ^0.2.5+1, firebase_core ^0.2.5+1 is required.
So, because mobile_hiking_app depends on firebase_core ^0.3.0, version solving failed.
```

But if I roll back on firebase_core then 

```
Running "flutter packages get" in mobile_hiking_app...          
Because firebase_auth >=0.8.0+1 depends on firebase_core ^0.3.0 and mobile_hiking_app depends on firebase_core ^0.2.5+1, firebase_auth >=0.8.0+1 is forbidden.
So, because mobile_hiking_app depends on firebase_auth ^0.8.1+1, version solving failed.
```

And I get into an endless cycle of different methods not working. Any idea when >=0.9.0 will work again without these errors?

**Comment by TheHistoryMajor** [comment]
**HELP!!** Urgent. Strict project deadline and I have this same issue... My project requires versions `>=0.9.0. Issue is only on iOS!

Please let me know if anyone has any ideas/workarounds/thoughts!

**Comment by shawnchan2014** [comment]
For those who can not on versions `>=0.9.0`, I think I just got this solved.

1. Remove the `~/.pub-cache` folder (and probably the `<YOUR_FLUTTER_DIRECTORY>/.pub-cache` folder).

2. Change the `cloud_firestore` version in `pubspec.yaml` to 
` cloud_firestore:`
`    git:`
`       url: git://github.com/flutter/plugins.git`
`       path: packages/cloud_firestore`
`       ref: 51696552700af8692fd7d595237fc9c4e273de93`

3. Run `flutter packages get` again. Problem should be resolved now.

**Comment by Isaiaher** [comment]
I am getting this error when trying the above 

```
Running "flutter packages get" in mobile_hiking_app...          
Error on line 26, column 8 of pubspec.yaml: Invalid version constraint: Could not parse version "git://github.com/flutter/plugins.git". Unknown text at "git://github.com/flutter/plugins.git".
  url: git://github.com/flutter/plugins.git
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

pub get failed (65)
exit code 65
```
But I also am unable to do part 1 due to not being able to find the .pub-cache folder. I use VS code and I run an ls in the flutter folder and don't see it in my file explorer or command line.

```
isaiahscheel$ ls
README.md                       ios                             pubspec.lock
android                         lib                             pubspec.yaml
assets                          mobile_hiking_app.iml           test
build                           mobile_hiking_app_android.iml

```

Thanks for any help!

**Comment by shawnchan2014** [comment]
@Isaiaher 
You should copy it like this:
![image](https://user-images.githubusercontent.com/32021781/53265857-3d779500-36ad-11e9-8037-356133ae74f4.png)

Additionally, the `<FLUTTER_DIRECTORY>` in part 1 is the place where you install your flutter, not your project directory.

Please let me know if you still have any questions.

**Comment by bgetsug** [comment]
I was able to rollback to `cloud_firestore: 0.9.0+1` (using the version number, not the commit ref), but not without fighting a Cocoapods conflict with `firebase_ml_vision` (#28054).

**Comment by blaneyneil** [comment]
rolling back to 0.9.0 breaks it for me on iOS.  i have to revert to 0.8.2+3 to get my to stop crashing.  except that i just checked my repo from 10 days ago, when i know for certain this problem didn't exist, and i had 0.9.0 in there.  makes me think the root problem is coming from firebase_core.

**Comment by nemoryoliver** [comment]
Have you guys tried the latest 0.9.5?

**Comment by radvansky-tomas** [comment]
@nemoryoliver Just tried 0.9.5+1, same thing.

**Comment by blaneyneil** [comment]
this is bonkers.  i now have it working with:

  cloud_firestore: 0.9.5+1
  firebase_auth: ^0.8.1+3

i started by dropping down to:

firebase_auth: "^0.7.0"
cloud_firestore: "^0.8.2+3"

and stepwise upgrading each new version, cleaning my build and removing .pub-cache/ every time, hoping to nail down to the breaking change (and calling flutter packages get, not upgrade, so it didn't jump a + version).  for reasons i can't explain, it finally failed when i went from cloud_firestore 0.9.0+1 to +2.  i then dropped down to 0.9.0, and worked up to 0.9.0+2 again, which shockingly worked.  

i then bumped right to 0.9.5+1 on a lark and it worked.  each time i was clearing .pub-cache to make sure i wasn't getting a false positive.

**Comment by msw333** [comment]
Can you elaborate on 'clearing .pub-cache'? Where do you clean it ;-)?

**Comment by tomalabaster** [comment]
I've submitted a [PR](https://github.com/flutter/plugins/pull/1267) with a fix. The issue was that a `FlutterError` was always returning even if the `error` was `null` in the move from categories to a static method.

**Comment by cyanglaz** [comment]
This issue was fixed by https://github.com/flutter/plugins/pull/1274. If any related issue is found, please feel free to reopen the issue ticket with more details.

**Comment by kroikie** [comment]
@nemoryoliver

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/431. Any further collaboration will be done there.
