### ISSUE TITLE
Unexpected isolate_snapshot files in release APK

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#28104]
Flutter build command produces weird artifacts inside apk assets 
Command:
```
flutter build apk --target-platform=android-arm
```
Result apk 
<img width="1018" alt="screen shot 2019-02-18 at 16 03 39" src="https://user-images.githubusercontent.com/16724952/52953028-5de6dd00-3397-11e9-9a3e-b2b5907ade52.png">
Files `isolate_snapshot_instr` and `isolate_snapshot_data` takes more than 20% of whole apk

I don't think they should be here

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.1 18B75, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
[!] VS Code (version 1.31.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
P.S.: I don't use VSCode for flutter development
P.S.S.: `vm_snapshot_*` files shouldn't be there as well

**Comment by dnfield** [comment]
Those are needed to start up the Dart isolate(s) involved in running Flutter.  Depending on whether this is a JIT or AOT build should impact which files are there and what they contain.  This is expected though, and you'll find that removing those files will result in cryptic errors from the shell.

You can read more about this here:

https://github.com/flutter/flutter/wiki/Flutter-engine-operation-in-AOT-Mode

https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode
