### ISSUE TITLE
Game engine and hot update and reflect

### ISSUE THREAD

**Issue by wildfire810** [flutter/flutter#28108]
I think flutter can be a good 2D/3D(use raw texture in weight tree) game engine.
Skia is cross platforms 2d renderer.

So, I think there is some important important.
Hot update, I read the source code, in android, there is a view as flutter surface, it can load bytecode(jni) or machine code(aot) at run time. If it can set in api，that is perfect.
Dart is a good script, but there is not reflecting in flutter. I think ,if it can reflect, it can be edit game object in app. Just like this.
![Example](https://docs.unity3d.com/uploads/Main/GameObjectCubeExample.png)
![Example](https://docs.unity3d.com/uploads/Main/GameObject-maincamera.png)
![Example](https://docs.unity3d.com/uploads/Main/AudioReference.png)

**Comment by kangwang1988** [comment]
@wildfire810 
Is https://github.com/flutter/flutter/issues/14330 what you want?

**Comment by zoechi** [comment]
Hot-update is covered by #14330   
Reflection is not planned. https://github.com/dart-lang/reflectable provides this functionality to some degree.
