### ISSUE TITLE
FutureBuilder does not respect changes to initialData

### ISSUE THREAD

**Issue by ArcticZeroo** [flutter/flutter#28118]
The `FutureBuilder` widget does not respect changes to `initialData`, even if the future is changed after `initialData` is. Here's a slightly pseudo-code-y way of describing what I mean:

```dart
String _myData = 'something';
Future _myFuture = getSomeFuture();

build(ctx) {
    return FutureBuilder(
        initialData: _myData,
        future: _myFuture
    );
}

// ...

someMethod() {
    setState(() { 
        _myData = 'something else';
        _myFuture =  getSomeOtherFuture();
    });
}
```

When the setState on the bottom is called, the future that is newly loading uses the old initialData still! I can provide a more complete, runnable example if needed -- I don't have Android Studio installed on the computer I am reporting this from (and only discovered it when attempting to port `FutureBuilder` to React).

This behavior is clear looking [at the source](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/async.dart#L591), since `AsyncSnapshot#inState` only changes state, not the data. It's a pretty simple fix, but I am unsure if this behavior is intended or not as-is. I'll make the change if anyone can confirm that this is not intended behavior

I assume this behavior is in case a future has completed already and that data wants to persist until the next future has _completed_, which I suppose is a logical use case, but it also seems weird that you cannot force a value to use as initialData when changing properties.

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.
