### ISSUE TITLE
Update firebase_dynamic_links android dependencies

### ISSUE THREAD

**Issue by Signez** [flutter/flutter#28119]
In the `firebase_dynamic_links` Firebase Flutter plugin, the reference to Android library `firebase-dynamic-links` in `build.gradle` is currently:

```
        api 'com.google.firebase:firebase-dynamic-links:16.1.2'
```

This version, 16.1.2, broke my build when I updated all my project with AndroidX and up-to-date Firebase library versions. Moreover, it is breaking with a difficult error message:

```
D8: Type com.google.android.gms.internal.measurement.zztk is referenced as an interface from `com.google.android.gms.internal.measurement.zztp`
```

It is quite hard to troubleshoot, as you have to think to open the dependencies of each flutter plugin (3 hours lost here 😅) to find that a minor version is the root of all the problems.

Replacing the obsolete dependency with an updated reference fixes it:

```
        api 'com.google.firebase:firebase-dynamic-links:16.1.7'
```

**Comment by leoafarias** [comment]
Have the same issue, but having a problem with the CI since its grabbing a fresh version from pubdart

**Comment by qazimusab** [comment]
Having the same issue... any update on when this will be fixed?

**Comment by aqibgatoo** [comment]
Same Issue.

**Comment by MustansirZia** [comment]
It's definitely breaking our builds too since we use newer versions of the other firebase plugins and this one hasn't yet updated its dependencies.

Here's what we have currently.
```yaml
  firebase_core: ^0.3.1+1
  firebase_messaging: ^4.0.0+1
  firebase_analytics: ^2.1.0
  firebase_crashlytics: ^0.0.2
  firebase_dynamic_links: ^0.2.0+3
```

**Comment by kroikie** [comment]
@Signez

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/430. Any further collaboration will be done there.
