### ISSUE TITLE
Add DocumentSnapshot().exists getter to cloud_firestore plugin to match the sdk

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#28129]
It seems like most of the other supported languages support an "exists" getter based on the example here. Can we have one too?
https://firebase.google.com/docs/firestore/query-data/get-data

**Comment by kroikie** [comment]
@ThinkDigitalSoftware

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/429. Any further collaboration will be done there.
