### ISSUE TITLE
FlutterView will leak activity when detach from FlutterNativeView

### ISSUE THREAD

**Issue by voiddog** [flutter/flutter#28128]
Flutter version: v1.0.0
In `FlutterView.java`'s constructor, `flutterPlatformChannel` will hold the instance of `platformPlugin` and `platformPlugin` will hold the instance of **activity**. The same as `TextInputPlugin`, it's holding by channel("flutter/textinput").

If I detach `FlutterView` from `FlutterNativeView` and the `FlutterNativeView` is a singleton. `FlutterView` will be leak, the context(activity) in `FlutterView` will leak too.

**Comment by kangwang1988** [comment]
@voiddog 
Can you verify this issue using the latest master?

**Comment by voiddog** [comment]
I looked at the code of the FlutterEngine at master branch and found that the problem still exists.

I also used the flutter sdk of the master branch to reproduce the problem.

![](https://i.imgur.com/V7SdOms.png)
> you can see the code above. `FlutterNativeView` holds `mFlutterChannel`, and `mFlutterChannel` holds current this object(TextInputPlugin)

Here is the leak reference list:
![](https://i.imgur.com/OW2hA6J.png)

**Comment by TahaTesser** [comment]
Hi @voiddog 
Did you experience this issue recently?
Thank you

**Comment by voiddog** [comment]
No It's fine

**Comment by TahaTesser** [comment]
Hi @voiddog 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
Thank you
