### ISSUE TITLE
No application found for TargetPlatform.android_x86.

### ISSUE THREAD

**Issue by brainwave0** [flutter/flutter#28122]
I'm writing this just in case anyone else runs into this problem.

I had this error a moment ago, and it took me a while to figure it out. I had an `AndroidManifest.xml`, yet Flutter apparently couldn't find it. It turned out that in my case my manifest was missing the following from the intent filter section:

```xml
<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.LAUNCHER" />
```

Adding the above lines resolved the issue.

**Comment by kangwang1988** [comment]
@brainwave0 
`flutter doctor -v` please.
Besides, is this project created by 'flutter create' or 'Add to existing app'?

**Comment by randikap** [comment]
Same issue here.

**Comment by randikap** [comment]
Resolved issue after deleting android's build folder

**Comment by Hamvorinf** [comment]
<intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                
                
                <category android:name="android.intent.category.LAUNCHER" />
                
</intent-filter>
