### ISSUE TITLE
Google Maps: Blank space on top

### ISSUE THREAD

**Issue by devfelipereis** [flutter/flutter#28120]
I have a details page with a button that goes to a map. When clicked, the map opens but I see a blank space on top.

It's the second time I try to build the map. Last one was weeks ago and I had the same problem.
I could not find a solution for this.

![image](https://user-images.githubusercontent.com/5348752/52980962-98fb0780-33bb-11e9-8e0e-6bf0426c0c7b.png)

## Steps to Reproduce

This is my map page.

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapPage extends StatefulWidget {
  final LatLng latLng;

  MapPage({Key key, this.latLng}) : super(key: key);

  @override
  _MapPageState createState() => _MapPageState();
}

class _MapPageState extends State<MapPage> {
  GoogleMapController mapController;

  void _onMapCreated(GoogleMapController controller) {
    setState(() {
      mapController = controller;
      mapController.addMarker(
        MarkerOptions(
          position: widget.latLng,
          infoWindowText: InfoWindowText('Sitio X', '5 Star Rating'),
          icon: BitmapDescriptor.defaultMarker,
        ),
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.grey.shade100,
        appBar: AppBar(
          backgroundColor: Colors.green[900],
          title: Text('Mapa'),
        ),
        body: GoogleMap(
          initialCameraPosition:
              CameraPosition(target: widget.latLng, zoom: 11.0),
          onMapCreated: _onMapCreated,
        ));
  }
}

```

## Logs
No error.

```
```

google_maps_flutter 0.2.0+3

![image](https://user-images.githubusercontent.com/5348752/52980869-0eb2a380-33bb-11e9-97da-30baa94bd20c.png)

**Comment by lucasfacchini** [comment]
I'm having the same issue #28121, I opened my issue a few minutes after.
In my case, the problem is also happening with a Xiaomi device.

**Comment by keshava19** [comment]
I'm also having the same issue, the root cause for me is that i'm handling the safe area and the google_maps widget is also handling the safe area the top space appears. It'd be nice if we had some way to control the maps safe area because not every time it'll in full screen.

**Comment by lucasfacchini** [comment]
This problem disappeared when I updated my device to MIUI 10.3.

**Comment by devfelipereis** [comment]
@lucasfacchini same here. Using MIUI Global 10.3 Stable - Android 9
