### ISSUE TITLE
Flutter google map on release mode not work

### ISSUE THREAD

**Issue by lovemoon** [flutter/flutter#28133]
hi to all flutter developer

my question: when I use flutter google map and when I build final and release app for android the map is not working

how I can fix this problem please look at below image

https://i.stack.imgur.com/8tGfv.png

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

Please publish a minimal reproduction project to GitHub.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by zoechi** [comment]
... and please add the output of `flutter doctor -v`.

**Comment by lovemoon** [comment]
https://i.imgur.com/eBN1E6h.jpg

> 
> 
> Please add the output of `flutter doctor -v`.
> 
> Please publish a minimal reproduction project to GitHub.
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

this my console image

https://i.imgur.com/eBN1E6h.jpg

**Comment by zoechi** [comment]
Please post as text instead of screenshots.

**Comment by lovemoon** [comment]
> 
> 
> Please post as text instead of screenshots.

[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.1.8 at C:\src\flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\Afra_SDK\AndroidFullSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.5153.38

[√] VS Code, 64-bit edition (version 1.29.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.20.0

[√] Connected device (1 available)
    • SM A605FN • 3dfd0603 • android-arm • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by zoechi** [comment]
Is there any log output (logcat) from the crash?

**Comment by lovemoon** [comment]
> 
> 
> Is there any log output (logcat) from the crash?

problem is here. it's just in release mode don't work, but in debug mode it's work without problem
and in release mode i don't have any logcat 

i tested it on huawei Honor and samsung device

**Comment by m7amdElberawy** [comment]
I'm already having the same problem...
In release mode don't work, but in debug mode it's work without a problem.

**Comment by zoechi** [comment]
@m7amdElberawy can you provide crash log output?

**Comment by Seven7up** [comment]
Problem resolved, I must enter the SHA-1 when i creating API key

**Comment by BondarenkoStas** [comment]
@lovemoon is the issue still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by IntegroInfotech** [comment]
The same issue in debug mode maps works without any problem. but when in release mode it will not work even it will not ask permission

**Comment by phuntshoWangdi** [comment]
I had same issue, added below line in android/app/build.gradle. Got the answer from [here](https://stackoverflow.com/a/67244406/11384036)
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            shrinkResources false // <--
            minifyEnabled false //<--
        }
    }
```
