### ISSUE TITLE
Could not get unknown property 'flutter' for project ':app' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by DeckeDeng** [flutter/flutter#28132]
* What went wrong:
A problem occurred evaluating project ':app'.
 Could not get unknown property 'flutter' for project ':app' of type org.gradle.api.Project.

**Comment by zoechi** [comment]
Please provide exact steps how to reproduce.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by DeckeDeng** [comment]
This problem suddenly appeared when I packed it. I used：【flutter  build apk】

**Comment by zoechi** [comment]
Try running `flutter packages pub cache repair`

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted
and https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated might be also worth a try.

**Comment by zoechi** [comment]
... and of course `flutter clean` if you haven't tried yet.

**Comment by lucaszanella** [comment]
I had this problem and my build.gradle file was missing in the plugin directory
