### ISSUE TITLE
SSL Public key Pinning support in flutter.

### ISSUE THREAD

**Issue by sandeepcmsm** [flutter/flutter#28137]
Support for pinning base64 SHA-256 hashes as in HTTP Public Key Pinning (HPKP) or SHA-1 base64 hashes in SecurityContext.
normally in native android and ios apps key pinning done similar like this https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html

**Comment by sandeepcmsm** [comment]
issue has been raised in dart sdk for support of this. https://github.com/dart-lang/sdk/issues/35981

**Comment by zoechi** [comment]
I think dart-lang/sdk#35981 is enough. No need to track it here as well.
