### ISSUE TITLE
google_sign_in: ^4.0.1+1 doesn't work on iOS 10 

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#28146]
I'm using `google_sign_in: ^4.0.1+1` and have no problem on an iPhone 5s and iOS 12. But on an iPhone 5 which is blocked at iOS 10 google sign in doesn't work, it open safari and log into google without problem but never go back to the app :/ and clicking on "Ok" to go back to the app is considered as a fail.

Any way to have it working on iOS 10 ?  

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale fr-FR)
    • Flutter version 1.1.8 at /Users/jaumard/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25
```

**Comment by zoechi** [comment]
Any crash log output?

Please add the output of `flutter doctor -v`.

**Comment by jaumard** [comment]
No crash or anything, it just stay on the google search page after login. But it look like it doesn't open the same things under iOS 10 and 11+ to handle the web part (on iOS11+ it show a popup and then open the webview from below, but iOS 10 open from the side directly with no popup, if it can help)... 

It's simply reproducible on any simulator with iOS 10, but there no error message at all. For iOS 11 and more no problem.

**Comment by jaumard** [comment]
I've create a small video of the problem here :) 
[appVideo.mov.zip](https://github.com/flutter/flutter/files/2882118/appVideo.mov.zip)

**Comment by jaumard** [comment]
I've test the example app of the google_sign_in plugin directly and it works on iOS 10. So I dig a bit deeper and the problem was on my side ! 
I override `override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {` and didn't call super so the return was ignored. 

Maybe it will help somebody else ^^
Sorry for the noise
