### ISSUE TITLE
Get camera FOV

### ISSUE THREAD

**Issue by dbech** [flutter/flutter#28143]
Being able to FOV the horizontal and vertical resolution of a camera would be great.

**Comment by zoechi** [comment]
Sounds like a great idea of a plugin package. Did you check pub.dartlang.org if one exists?

**Comment by dbech** [comment]
camera is an existing package this would just be an addition to it.

**Comment by zoechi** [comment]
fair enough

**Comment by dbech** [comment]
> Being able to FOV the horizontal and vertical resolution of a camera would be great.

**Comment by RobertApikyan** [comment]
Are there any news about this topic? Do we have access to field of view property?

**Comment by dbech** [comment]
Personally I moved on from the need that generated this issue initially.

I've unsubscribed but will leave this open, maintainers feel free to close if not planned etc.
