### ISSUE TITLE
StreamBuilder only updates last item - when adding multiple items to stream

### ISSUE THREAD

**Issue by JCzz** [flutter/flutter#28144]
StreamBuilder` is only receiving last added item to stream(PublishSubject)
But if listening to the stream(PublishSubject) all items goes through?

Adding multiple items to stream:
```dart
  void _onPresseAddMore() {
    for (var i = 0; i <= 5; i++) {
      items.add("event:" + count.toString());
      count++;
    }
  }
```

Listener gets all:
```dart
    sub = items.listen((item) {
      print(item + ":listener");
    });

```

StreamBuilder only gets called for last item:
```dart
 builder: ((BuildContext context, AsyncSnapshot snapshot) {  
                    String dataString = snapshot.data ?? "Initial no events...";
                    list.add(dataString);
                    ...
```

Code for listener and StreamBuilder:

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:rxdart/rxdart.dart';

class BugStreamBuilder extends StatefulWidget {
  @override
  _BugStreamBuilder createState() => _BugStreamBuilder();
}

class _BugStreamBuilder extends State<BugStreamBuilder> {
  PublishSubject<String> items = new PublishSubject<String>();
  StreamSubscription<String> sub;
  final List<String> list = List<String>();
  int count = 0;

  @override
  void initState() {
    items.drain();
    sub = items.listen((item) {
      print(item + ":listener");
    });

    super.initState();
  }

  @override
  void dispose() {
    items.close();
    sub.cancel();
    super.dispose();
  }

  void _onPresseAddOne() {
    items.add("event:" + count.toString());
    count++;
  }

  void _onPresseAddMore() {
    for (var i = 0; i <= 5; i++) {
      items.add("event:" + count.toString());
      count++;
    }
  }

  @override
  Widget build(BuildContext pageContext) {
    return MaterialApp(
        title: 'Welcome to Flutter',
        home: Scaffold(
          appBar: AppBar(
            title: Text('Testing base button'),
          ),
          body:
              Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
            FlatButton(onPressed: _onPresseAddOne, child: new Text('Add')),
            FlatButton(
                onPressed: _onPresseAddMore, child: new Text('Add more')),
            Expanded(
              child: new StreamBuilder(
                  stream: items,
                  builder: ((BuildContext context, AsyncSnapshot snapshot) {  
                    String dataString = snapshot.data ?? "Initial no events...";
                    list.add(dataString);
                    ListView listView = ListView.builder(
                      reverse: true,
                      shrinkWrap: true,
                      itemCount: list.length,
                      itemBuilder: (context, index) {
                        return ListTile(
                          title: Text(list[index]),
                        );
                      },
                    );
                    return listView;
                  })),
            ),
          ]),
        ));
  }
}

```

**Comment by zoechi** [comment]
That's working as intended. There is no point update rendering x times between two frames when only the last one will be actually rendered.
If you add a delay between the events, you'll see that every one is rendered.

Perhaps you're trying to use `StreamBuilder` (or `build()` for something it is not supposed to be used.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by JCzz** [comment]
Thanks

I believe it is a valid scenario to update a list?

Regards

**Comment by zoechi** [comment]
```
list.add(dataString);
```
inside a `build` function or inside a builder is not valid at all.

The build function should build the widget tree but should not have any other side effects.

**Comment by zoechi** [comment]
For this case read the stream in `initState` or `didChangeDependencies` and use `setState` to initiate a rebuild.

**Comment by JCzz** [comment]
Thanks

I see and agree.

Good idea thanks, I think I will:
1. listen to the data stream
2. update the local list
3. then add/sink to another stream to update and use StreamBuilder.

That way, I will save rebuilds as you pointed out - and still get an updated list.

Regards

**Comment by zoechi** [comment]
Yup.

Prefer `forEach` instead of `listen` if you do not want to explicitly unsubscribe.

**Comment by JCzz** [comment]
Right, that solves two of my "need to figure out" issues, with the one you also answered, for pause and cancel :-)

Thanks man

**Comment by zoechi** [comment]
Glad to hear.

Please in the future try to get an answer on StackOverflow or similar first before creating an issue.
GitHub is for bug reports and feature request. Thanks!

**Comment by JCzz** [comment]
Thanks, will do
