### ISSUE TITLE
Gradle 5 migration

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#28151]
Gradle 5.3 contains a fix for a bug that causes our CI to crash whenever a git commit includes emoji, flutter/flutter#24935. However upgrading to 5 does look like it contains some breaking changes from 4.x, so we should evaluate any potential breakages before to make sure it's worth it if and when we do upgrade. We already have a rough workaround in place for the emoji bug.

https://docs.gradle.org/5.0/userguide/upgrading_version_4.html

/cc @dnfield @amirh

**Comment by blasten** [comment]
This is fixed 🎉

**Comment by stuartmorgan** [comment]
I noticed we still have the workaround for this in our .cirrus.yml and found this. @blasten Is this actually fixed for flutter/plugins? All the `com.android.tools.build:gradle` dependency entries in the plugins repo are using 3.x or a few 4.x; am I looking at the wrong thing?

**Comment by blasten** [comment]
@stuartmorgan I added an item to your OKRs doc
