### ISSUE TITLE
Flutter cannot pass BuildContext parameters from invokeMethod

### ISSUE THREAD

**Issue by juansapr** [flutter/flutter#28154]
I am trying to build an application that interact with an Android SDK. Some of the libraries require that I supply an argument Context type to work. The problem that I am having is that when I try to pass this parameter I get the next error back:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument: Instance of 'StatefulElement'
```

I believe that is the fact that I am trying to use a StatefulElement in a Stateless function. I really would like that someone that help me to fix it or top work around to supply the context argument need for the SDK, here is the sample of my code:

**Flutter code:**
```dart
Future<void> demoFunction(BuildContext context) async {
    String stringObj;
    try {
      final result = await platform.invokeMethod('getInfo',<String,dynamic>{'data':context});
      stringObj = 'Battery level at $result % .';
    } on PlatformException catch (e) {
      stringObj = "Failed to get battery level: '${e.message}'.";
    }

    setState(() {
      _stringObj = stringObj;
    });
  }
```

**Android code:**
```java
@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);

    new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
            new MethodCallHandler() {
              @Override
              public void onMethodCall(MethodCall call, Result result) {
                Context context = call.argument("data");
                if (call.method.equals("geInfo")) {
                  JSONObject obj = getJsonTermInfo(context);

                  if (obj == null) {
                    result.error("UNAVAILABLE", "information is not available!", null);
                  } else {
                    result.success(obj);
                  }
                } else {
                  result.notImplemented();
                }
              }
            });
  }
```

Please, if someone can help me, I will appreciate it.

**Comment by zoechi** [comment]
> I believe that is the fact that I am trying to use a StatefulElement in a Stateless function.

I don't think so.

The context is a pure Dart class instance and `MethodChannel` requires values to be serializable to be passed which `BuildContext` is not.

As a workaround you could maintain a map from IDs to context instances and pass the ID along. 

I don't think this will be changed in Flutter.

Perhaps you can elaborate on the concrete use case where and why this is required.

**Comment by juansapr** [comment]
Hi Zoechi

Thank you for your quick answer. I actually already tried the map IDs and value and when I get the context out of the map the error still happening, the code sample is the next:

**Dart Code:**
```dart
Future<void> demoFunction(BuildContext context) async {
    String stringObj;
    var parameters = new Map();
    parameters['context'] = context;

    try {
      final result = await platform.invokeMethod('getSimInfo',<String,dynamic>{'data':parameters});
      stringObj = jsonEncode(result) ;
    } on PlatformException catch (e) {
      stringObj = "Failed to get battery level: '${e.message}'.";
    }

    setState(() {
      _stringObj = stringObj;
    });
  }
```
**Android Code:**
```java
@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);

    new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
            new MethodCallHandler() {
              @Override
              public void onMethodCall(MethodCall call, Result result) {
                context = (Context)call.argument("data");
                Map parameters = call.argument("data");
                if (call.method.equals("getSimInfo")) {
                  JSONObject obj = getJsonTermInfo((Context)parameters.get("context"));

                  if (obj == null) {
                    result.error("UNAVAILABLE", "SIM information is not available!", null);
                  } else {
                    result.success(obj);
                  }
                } else {
                  result.notImplemented();
                }
              }
            });
  }
```
To give you some context of the the reason that the library needs the Context type. The library provide information the sim card very similar to what TelephonyManager do. However, the library provide more information than TelephonyManager and is required for the specific sim card brand that I am working with. It look like Context type can't be use in Android "FlutterActivity", do you have another suggestion?

**Comment by zoechi** [comment]
Your explanation somehow didn't help me understand why you think you need Flutters `BuildContext` and what you intend to do with it on the native side.
I assumed all you can do is pass it back to know what context was related to the original call from the Dart side. But your explanation makes me doubt that assumption.

**Comment by ethanblake4** [comment]
Yes @juansapr you are using the wrong type of Context. The Flutter `BuildContext` is unrelated to the Android `Context`. Instead you should pass in `ActivityName::this` to the getJsonTermInfo function ( where ActivityName is the class name of the activity)

**Comment by juansapr** [comment]
> Yes @juansapr you are using the wrong type of Context. The Flutter `BuildContext` is unrelated to the Android `Context`. Instead you should pass in `ActivityName::this` to the getJsonTermInfo function ( where ActivityName is the class name of the activity)

Hi ethanblake4

Actually, your suggestion made sense and I was doing that context part wrong. However, I still having compilation errors here and I believe I still doing something wrong because I get this error:

> error: as of release 8, 'this' is allowed as the parameter name for the receiver type only, which has to be the first parameter

The code that display that error is this:

```java
new MethodChannel(getFlutterView(), CHANNEL).setMethodCallHandler(
            new MethodCallHandler() {
              @Override
              public void onMethodCall(MethodCall call, Result result) {
                if (call.method.equals("getSimInfo")) {
                  boolean stat = simManager(MainActivity::this);

                  if (stat == false) {
                    result.error("UNAVAILABLE", "SIM information is not available!", null);
                  } else {
                    result.success(stat);
                  }
                } else {
                  result.notImplemented();
                }
              }
            });
  }

  public boolean simManager(Context context){
    MCard card = new MCard();
    card.openSEService(context);

    return true;
  }
``` 
Do you have another suggestion for me here, please?

**Comment by ethanblake4** [comment]
Oh sorry, you're actually supposed to use `MainActivity.this`. My Java's a bit rusty.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

Feel free to continue the discussion, but I'll close because I don't think there is anything for the Flutter team to do.

**Comment by ArafatAbsi** [comment]
> Yes @juansapr you are using the wrong type of Context. The Flutter `BuildContext` is unrelated to the Android `Context`. Instead you should pass in `ActivityName::this` to the getJsonTermInfo function ( where ActivityName is the class name of the activity)

this.context worked thank you
