### ISSUE TITLE
Remove computeDartDependencies from flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#28150]
This accounts for 75% of hot reload execution time.

With computeDartDependencies
```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone XS Max is available at: http://127.0.0.1:55965/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                              
Reloaded 0 of 435 libraries in 1,255ms.

Performing hot reload...                                                
Reloaded 0 of 435 libraries in 936ms.

Performing hot reload...                                                
Reloaded 2 of 435 libraries in 990ms.

Performing hot reload...                                                
Reloaded 0 of 435 libraries in 964ms.

```

Without computeDartDependencies
```
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone XS Max is available at: http://127.0.0.1:56425/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                              
Reloaded 0 of 435 libraries in 384ms.

Performing hot reload...                                                
Reloaded 0 of 435 libraries in 296ms.

Performing hot reload...                                                
Reloaded 0 of 435 libraries in 285ms.

```

**Comment by Hixie** [comment]
Don't we need to compute the dependencies to make hot reload work?

**Comment by jonahwilliams** [comment]
We might have needed to at one point, but I believe the only use this serves now is nicer error message for missing dependencies, which we can regain by wrapping the FE server output.

**Comment by aam** [comment]
There is https://github.com/flutter/flutter/issues/12745 about moving away from analyzer to frontend for file-dependency analysis.

When you use frontend compiler you need to know which files you need to track and report changes in - this is what dependency analysis is doing.

**Comment by jonahwilliams** [comment]
We already do that via the devfs classes. Currently both google3 and fuchsia-source run with this option disabled.

**Comment by aam** [comment]
Not sure I understand - during dev session as you hot reload you add new file and add import statement that incorporates the file into the app - how will flutter know that it needs to start tracking changes in that file? Same goes for removing file and import statement.
