### ISSUE TITLE
framework.dart bug

### ISSUE THREAD

**Issue by tomwalsh96** [flutter/flutter#28179]
the error is thrown on line 4122 on `framework.dart` file. I have not edited this file so don't know how or why an error could occur. the code shows where the error is located.
```dart
  void _updateInheritance() {
    assert(_active);
    final Map<Type, InheritedElement> incomingWidgets = _parent?._inheritedWidgets;
    if (incomingWidgets != null)
      _inheritedWidgets = HashMap<Type, InheritedElement>.from(incomingWidgets);
    else
      _inheritedWidgets = HashMap<Type, InheritedElement>();
    _inheritedWidgets[widget.runtimeType] = this;
  }
```

on the line `_inheritedWidgets = HashMap<Type, InheritedElement>.from(incomingWidgets);`
the error states that the ',' after Type should be a ';', however changing this just throws more errors.

**Comment by zoechi** [comment]
Please run https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted and tell if the error is still shown.

**Comment by tomwalsh96** [comment]
Thank you the above suggestion seems to have fixed the issue.
