### ISSUE TITLE
Update @pragma vm:entrypoints

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#28176]
https://github.com/flutter/engine/pull/7827 should be relanded once the Dart SDK in the engine catches up to https://github.com/dart-lang/sdk/commit/ae7bf9e999b09efc45d87a4f6f01f11832b2d442

/cc @chinmaygarde @sjindel-google @bkonyi @jason-simmons

**Comment by chinmaygarde** [comment]
xref https://github.com/flutter/flutter/issues/28184
