### ISSUE TITLE
Cannot route new screen when click appBar action

### ISSUE THREAD

**Issue by hanjt** [flutter/flutter#28186]
Hi, this is my code
```dart
class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => new MyAppState();
}

class MyAppState extends State<MyApp> {  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Share Book',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('MY Book'),
          actions: <Widget>[
            IconButton(
              icon: Icon(
                Icons.add
              ),
              onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => SecondScreen()),
                    ); 
              },
            )
          ],
        ),
        body: Text('I am content'),
      ),
    );
  }
```

But when I click the button, can not push new screen. This is error log
```Navigator operation requested with a context that does not include a Navigator.```
I don't know how to show new screen, when click the button on AppBar.

**Comment by Kartik1607** [comment]
Hey, please go through the flutter [docs for navigation here](https://flutter.io/docs/cookbook/navigation/named-routes) first and try running the provided code. If you are still stuck, let us know and someone would help you.

**Comment by hanjt** [comment]
@Kartik1607 I have read the flutter [docs for navigation here](https://flutter.io/docs/cookbook/navigation/named-routes).But it can not tell me why the code is error. When I build a native app,  the button on the navigationBar can click and push or present a new screen. So I think flutter should support it as a native app.

**Comment by zoechi** [comment]
@hanjt this is a frequently asked question.
The context you pass to `MaterialPageRoute(...)` is the context of `MyAppState`, not the context of `Scaffold` that contains the `Navigator`.
I'd suggest you create custom widgets for each action.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
