### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by aboubackr** [flutter/flutter#28185]
## Steps to Reproduce

1. flutter: 'package:flutter/src/widgets/text.dart': Failed assertion: line 235 pos 15: 'data != null': is not
flutter: true.
2. [VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
'package:flutter/src/widgets/page_view.dart': Failed assertion: line 96 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.

## Logs

```
```

```
```

```
```

**Comment by zoechi** [comment]
Do not pass `null` to `Text(...)`

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
