### ISSUE TITLE
What is the width height units of widgets?

### ISSUE THREAD

**Issue by donadoo** [flutter/flutter#28188]
```dart
new Container(
    width:200.0,
    height:200.0
)
```

what is the width height units?

for example, I want to draw width with 200px and height 200px, how to transform 200px here?

many thanks

**Comment by Kartik1607** [comment]
Flutter uses [device independent pixels](https://docs.flutter.io/flutter/dart-ui/Window/devicePixelRatio.html) as default. 

For your Container to be of 200px
```dart
Container(
    width:200.0/MediaQuery.of(context).devicePixelRatio,
    height:200.0/MediaQuery.of(context).devicePixelRatio,
)
```

**Comment by jonahwilliams** [comment]
If you do this you will find that your container is quite small on high DPI screens. It is best to design your application around device independent pixels and trust device manufactures to adjust the dpr appropriately based on screen size and resolution

**Comment by Kartik1607** [comment]
> If you do this you will find that your container is quite small on high DPI screens. It is best to design your application around device independent pixels and trust device manufactures to adjust the dpr appropriately based on screen size and resolution

No offence, but I like memes and this meme seemed perfect fort the scenario. 
![GIF](https://i.imgur.com/q2N7RCX.gif)

**Comment by jonahwilliams** [comment]
Spicy!

**Comment by zoechi** [comment]
😄 

Anything planned to do? Update docs, ...?

**Comment by donadoo** [comment]
> If you do this you will find that your container is quite small on high DPI screens. It is best to design your application around device independent pixels and trust device manufactures to adjust the dpr appropriately based on screen size and resolution

we can design design draft with 720p，for 200px width, translate this

**Comment by saraspaudel** [comment]
Please provide updated docs, the above link doesn't work.
