### ISSUE TITLE
Android camera library does not capture orientation correctly for exif data the first time the camera is used

### ISSUE THREAD

**Issue by idealopamp** [flutter/flutter#28180]
## Steps to Reproduce

1. Run a clean installation of the full camera example from the camera plugin https://pub.dartlang.org/packages/camera#-example-tab-
2. Select a camera e.g. the back camera
3. You should be prompted to allow camera and audio access -- accept those permission requests
4. Turn the phone in landscape and take a picture (the camera preview is sideways, which is itself a different issue)
5.  You can observe in the small camera preview that the exif data for the captured image is incorrect -- it is turned sideways.

This issue happens only for the first time the camera is used, or any time the user is prompted for permissions to use the camera.  If you close the app and repeat the same steps, you will see proper orientation of any subsequently captured images.

## Logs

```
N/A -- This is unnecessary, as the issue is not captured in logging, and issue is already identified in a pull request that will be uploaded shortly. 
```

```
N/A
```

```
N/A
```

**Comment by zoechi** [comment]
#25232 might be related
Thanks for the PR!
