### ISSUE TITLE
Inline conditional rendering in list

### ISSUE THREAD

**Issue by theochampion** [flutter/flutter#28181]
Hi everyone,

I have a list of widget (`Column` widget) and I would like to render one of them only on condition.
I tried achieving that using a ternary operator but flutter complains about rendering a null widget.
```dart
    return Column(children: <Widget>[
      Text("hello"),
      condition ? Text("should not render if false") : null,
      Text("world")
    ],);
```

My question is therefore, is there a way to do inline conditional rendering in Flutter like it is possible to do in React using the logical && operator ? 

Thanks :)

**Comment by Kartik1607** [comment]
This has been discussed before in https://github.com/flutter/flutter/issues/3783 issue.

For now , the **optimal** way is 
```dart
bool notNull(Object o) => o != null;
Widget build() {
  return new Column(
    children: <Widget>[
      new Title(),
      new Body(),
      shouldShowFooter ? new Footer() : null
    ].where(notNull).toList(),
  );
}
```

**Comment by zoechi** [comment]
Better language support for that is work in progress https://github.com/dart-lang/language/issues/47

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by theochampion** [comment]
For the record, Dart `2.3` added the ability to use if/else statements in Collection literals. This is now done the following way:

```dart

    return Column(children: <Widget>[
      Text("hello"),
      if (condition)
         Text("should not render if false"),
      Text("world")
    ],);
```

**Comment by oli06** [comment]
@theochampion and the best thing about this is, that you can use it as a appending list:
```
    return Column(children: <Widget>[
      Text("hello"),
      if (condition) ...[
         Text("should not render if false"),
         Text("This should not render as well"),
         Text("Same for me"),
      ],
      Text("world")
    ],);
```

**Comment by princebillyGK** [comment]
@theochampion  is there any feature to add for loop in list like this if statement?

**Comment by anik786** [comment]
@princebillyGK Yes.

```
var listOfInts = [1, 2, 3];
var listOfStrings = [
  '#0',
  for (var i in listOfInts) '#$i'
];
assert(listOfStrings[1] == '#1');
```

See: https://dart.dev/guides/language/language-tour#lists
