### ISSUE TITLE
Publish some example apps in the Play Store and in the App Store

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#282]
<a href="https://github.com/trusktr"><img src="https://avatars.githubusercontent.com/u/297678?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [trusktr](https://github.com/trusktr)**
_Friday Nov 06, 2015 at 21:22 GMT_
_Originally opened as https://github.com/flutter/engine/issues/2000_

---

Got any links?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Friday Nov 06, 2015 at 21:26 GMT_

----

We don't have any examples published in Android Play or in the App Store yet.  That's something we'll certainly do.  It's just a question of when.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/mscheel"><img src="https://avatars.githubusercontent.com/u/654527?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mscheel](https://github.com/mscheel)**
_Friday Nov 06, 2015 at 22:41 GMT_

----

At the bottom of this page (http://flutter.io/getting-started/) it says the Stocks.apk is available here: https://github.com/flutter/engine/tree/master/examples/stocks but the APK folder does not have an APK.  Either the web page needs to be corrected or the APK should be added.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Friday Nov 06, 2015 at 23:03 GMT_

----

If you follow the instructions for contributing to engine.git and run the build, you'll produce a Stocks.apk.  We should make the docs clearer in that regard.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Tuesday Nov 10, 2015 at 02:33 GMT_

----

cc @vlidholt

**Comment by sethladd** [comment]
We're working on it :)

**Comment by sethladd** [comment]
Sorry for the delay here. The Gallery is now available in the Play Store: https://play.google.com/store/apps/details?id=io.flutter.gallery&hl=en

**Comment by sethladd** [comment]
Apps are appearing in the stores. For example, Newsvoice is in both iOS and Android stores. Gallery is in the Play Store.

**Comment by sunglim** [comment]
@sethladd Can I ask that why Gallery is not on App store?

**Comment by sethladd** [comment]
Hi @sunglim , thanks for the question. We're working through some issues and features for the Gallery app specifically on iOS. Until those issues and features are addressed, we don't plan to publish to the App Store. However, we've pushed the Gallery app to the App Store via TestFlight, to ensure it's possible.

**Comment by sunglim** [comment]
@sethladd  OK got it. thanks for the answer.

**Comment by candidosales** [comment]
Can I ask that why Gallery is not on App store?

**Comment by sethladd** [comment]
We have a version in TestFlight and we're polishing it up before we try to make it public. Stay tuned!

**Comment by wcandillon** [comment]
@sethladd can I get access to the gallery app via test flight?
William Candillon wcandillon@gmail.com

**Comment by wcandillon** [comment]
Gang, not sure if you will find this relevant but I loved the animation demo so much that I cloned it in React Native: https://www.youtube.com/watch?v=JkbC9niXfH0 Thanks for the amazing work 👍🏻
