### ISSUE TITLE
Drop-down not working with Stream builder and BLoC pattern

### ISSUE THREAD

**Issue by sripre** [flutter/flutter#28200]
Drop-down not showing anything when the data is coming from api is broadcasted with the help of stream builder and also I am using BLoC pattern

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by Rostanxd** [comment]
I'm having problem with the drop down item too. I'm using a stream builder to load the response from the same, but the value property on the dropdown it's ever empty.

(I tried to use other stream builder inside to control the stream who have the "value" in the bloc, but it gives me a error... Apparently there is no article with such value.)

That's my code...

`Widget _holdingDropDown() {
    return StreamBuilder(
        stream: bloc.holding,
        builder: (BuildContext context, AsyncSnapshot<Holding> snapshot) {
          print(snapshot.data.id);
          return Container(
            child: Center(
              child: snapshot.hasData
                  ? StreamBuilder(
                      stream: bloc.obsHoldingList,
                      builder: (BuildContext context,
                          AsyncSnapshot<List<Holding>> holdingListSnapshot) {

                        holdingListSnapshot.data.map((h){
                          print(h.id);
                        }).toList();

                        return holdingListSnapshot.hasData ?
                        DropdownButton<Holding>(
                          value: snapshot.data,
                          items: _listDropDownHoldings,
                          onChanged: (Holding h) {
//                            _changeDropDownItemHolding(h);
                          },
                        ): CircularProgressIndicator();
                      },
                    )
                  : CircularProgressIndicator(),
            ),
          );
        });
  }`
