### ISSUE TITLE
flutter --version needs write permission to read the version-file

### ISSUE THREAD

**Issue by tvw** [flutter/flutter#28212]
Seems to be an error when opening the file with the wrong mode.

**Comment by zoechi** [comment]
Might be that it needs to update the cache first when it is not up-to-date.
Flutter is not expected to work without write permissions in the install directory anyway.

**Comment by zoechi** [comment]
Related to #28210 I guess

**Comment by tvw** [comment]
I gave to the bin/cache-directory write permissions. It still breaks. Giving write permissions to the version file too makes flutter work. But it does not change the version file.

So I still do not get the point, why a file must have write permissions, when it is only read and a change makes no sense, since the file contains the flutter version, which is static with the install.

**Comment by kf6gpe** [comment]
This is no longer an issue; I just re-tested.
