### ISSUE TITLE
TextFieldDecoration - prefixIcon changeColor

### ISSUE THREAD

**Issue by DeRealMorgan** [flutter/flutter#28228]
I cant find anything on how to change the color of a prefixIcon attached to a TextField.

Goal: The standard icon color is blue when a TextField is selected. How do I change this color ? It seems like there is no option for it.

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by TahaTesser** [comment]
Hi @DeRealMorgan 

### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(
            obscureText: true,
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              labelText: 'Contact',
              prefixIcon: Icon(Icons.contact_mail, color: Colors.orange),
            ),
          ),
        ),
      ),
    );
  }
}

```

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
