### ISSUE TITLE
google_sign_in 3.2.4 crash on signin

### ISSUE THREAD

**Issue by NickvanZanten** [flutter/flutter#28225]
Following this tutorial https://fireship.io/lessons/flutter-firebase-google-oauth-firestore/ I'm having problems signing up with Google.

After performing a google sign in like so:
```dart
Future<FirebaseUser> googleSignIn() async {
    loading.add(true);
    GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    GoogleSignInAuthentication googleAuth = await googleUser.authentication;

    FirebaseUser user = await _auth.signInWithGoogle(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken
    );

    updateUserData(user);

    loading.add(false);
    return user;
  }
```

It takes a few seconds after throwing the following stack error:

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001087541bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000107cf2735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108754015 +[NSException raise:format:] + 197
	3   Runner                              0x00000001014538c5 -[GIDSignIn signInWithOptions:] + 242
	4   Runner                              0x000000010144feb9 -[GIDSignIn signIn] + 64
	5   Runner                              0x000000010147af5c -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2236
	6   Flutter                             0x000000010448d5fa __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	7   Flutter                             0x00000001044a9bc8 _ZNK5shel<…>
Lost connection to device.
```

This is the `flutter doctor -v` output:
```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.1.8 at /Users/nickvanzanten/Projects/Library/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nickvanzanten/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • iPhone XS • C65D1887-725F-4729-B6A5-BC7C3203BFE7 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by Faisalkc4u** [comment]
Hi,
I'm facing the same issue. At the initial stage, it was working fine. when I added facebook authentication after it started throwing this error for me.

**Comment by nikith050** [comment]
Add below code to **[my_project]/ios/Runner/Info.plist file**

<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLSchemes</key>
		<array>
			
			
			<string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
		</array>
	</dict>
</array>

**Comment by zilijonas** [comment]
> Hi,
> I'm facing the same issue. At the initial stage, it was working fine. when I added facebook authentication after it started throwing this error for me.
> 
> In my case, I was using Facebook and Google Auth.
> There was a conflict happen in Info.plist
> 
> ```
> <key>CFBundleURLTypes</key>
> <array>
>     <dict>
>         <key>CFBundleURLSchemes</key>
>         <array>
>             <string>fbxxxxxxxxxxxxx</string>
>         </array>
>     </dict>
> 	<dict>
>             <key>CFBundleTypeRole</key>
>             <string>Editor</string>
>             <key>CFBundleURLSchemes</key>
>             <array>
>               <string>com.google.xxxxxxxxxxx</string>
>             </array>
>           </dict>
> </array>
> 
> <key>FacebookAppID</key>
> <string>xxxxxxxxxx</string>
> <key>FacebookDisplayName</key>
> <string>Name</string>
> ```
> 
> This made it works perfectly.
> Try to place this code after
> 
> ```
> 
> 	<key>LSRequiresIPhoneOS</key>
> 	<true/>
> ```
> 
> [for more](https://stackoverflow.com/questions/18695764/how-to-set-many-url-schemes-in-info-plist)
> 
> #27422

This helped me. Thank you very much.

However, it did not matter if I add it after `LSRequiresIPhoneOS` or not in my case.

**Comment by ControlAdad** [comment]
There is a funny thing, I am using flutter_downloader too.
If I remove this line from main.dart, google_sign_in works and there is no crash:

await FlutterDownloader.initialize();

Any explanation?

**Comment by harish6471** [comment]
I got the same issue but when I migrated to androidx library the problem solved.
