### ISSUE TITLE
android.intent.category.DEFAULT in AndroidManifest causing Dream client to fail to run

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#28223]
Dream has `android.intent.category.DEFAULT` in their `AndroidManifest.xml`.

Excerpt:
```xml
  <intent-filter>
    <action android:name="android.intent.action.MAIN"/>

    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.LAUNCHER"/>
  </intent-filter>
```

With this line, they can build an app, then install it with adb, but they cannot run it with their `flutter run` command.

Message me or Alvin for the detailed logs.

**Comment by dnfield** [comment]
Seems related to https://github.com/flutter/flutter/issues/21382
