### ISSUE TITLE
Android Studion 3.3( windows(10)  no connected devices found , or see the flutter.io

### ISSUE THREAD

**Issue by RashidIshaque** [flutter/flutter#28221]
i am using the Android Studion 3.3 on Windows 10. i have created a emulator and it is running manually for the AVD manager but when i Click on Run Button the fallowing messageBox sappers

> **No connected devices found; please connect a device, or see flutter.io/setup for getting started instructions.**
i use the terminal for Run the App the terminal Run the app but it is not showing the hot-reload option.or any other options. i edited the main.dart but it show the same no chages will shown , i use the VS code but it also show nothing to display

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3217](https://github.com/flutter/flutter-intellij/issues/3217) via [**ZenHub**](https://www.zenhub.com/)
