### ISSUE TITLE
ipa file size with fastlane (80Mb yikes!)

### ISSUE THREAD

**Issue by logemann** [flutter/flutter#28226]
Hi,

i am playing around with the flutter example application (counter) and a fastlane build pipeline. Right now i am just following the docs more or less. So i do:

$> `flutter build ios`
$> `fastlane beta`

my fastfile looks like this:

```
lane :beta do
    get_certificates
    get_provisioning_profile
    build_ios_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  end
```

The resulting IPA is a wooping 80 Mb. Cant figure out why. I am just using defaults everywhere which should be "release".

Thanks for infos.

**Comment by felangel** [comment]
Seeing the same issue here when running `flutter run --release` on iOS (~78mb)

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.12.6 16G1710, locale en-US)
    • Flutter version 1.0.0
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by logemann** [comment]
My ipa file contains a "SwiftSupport/iphoneos" folder with massive dylib libararies like libswiftCore.dylib and libswiftFoundation.dylib. Furthermore those same libraries are also under Payload/Runner.app/Frameworks folder.

So somehow the packaging seems odd.

**Comment by dnfield** [comment]
Do you see the same size concerns if you use Objective C?

**Comment by dnfield** [comment]
(And yes, Flutter does ship fat IPAs.  But we don't know how exactly the AppStore thins things - presumably, if you just lipo the binaries out you should have a closer idea)

**Comment by szotp** [comment]
This may be related: We sent 9,5MB ipa to the AppStore, but AppStore reported the size to be 30MB. 

I wondered why, so I did some research. Apperently Apple is doing some kind of DRM encryption of binaries: https://stackoverflow.com/a/42481125/1981314

I checked this by downloading the package from AppStore and manually compressing the binaries, the results are below:
![Screenshot 2019-08-14 at 14 08 33](https://user-images.githubusercontent.com/19707261/63020135-8e6a8800-be9d-11e9-89d6-381dbf3e4910.png)

Compressed App.framework is 3x times larger. 
I'm wondering why unecrypted binaries are so easy to compress? They must have a lot of contiguous zeros or something.

**Comment by Hixie** [comment]
This may be the same as https://github.com/flutter/flutter/issues/36611.

**Comment by dnfield** [comment]
I don't think there's any action to take at this point. 

You can't really trust the size of an IPA on disk. You really have to look at the final result that comes from the app store.  There are many factors that can make the IPA seem unexpectedly large:

- Bitcode, a huge blob of IR data that will be stripped away by Apple
- Fat IPAs, containing multiple architectures that will be stripped away before reaching your target device
- Encryption - Apple appears to encrypt before compressing, which lowers compression ratios.

This bug isn't really actionable in its current state.  I'm going to close it - please feel free to add more details if you think I'm missing something!
