### ISSUE TITLE
flutter has exited unexpectedly, during flutter packages get, after including Firebase in pubspec.yaml

### ISSUE THREAD

**Issue by egorges** [flutter/flutter#28239]
## Steps to Reproduce

1. include `firebase_analytics: ^1.0.6` in the `pubspec.yaml` dependencies and save
a)The _same bug happens with several other plugins_, like `flutter_web_browser: ^0.9.0` or `firebase_core: ^0.2.5`
b) _It doesn't happen with_: `cupertino_icons: ^0.1.2`, neither `font_awesome_flutter: ^8.4.0`, neither `http: any`
2. Saving automatically runs `flutter package get`, in which Flutter crashes.

## History:
```
I've been working OK with Flutter until last weekend, when it started to give me some weird problems like:
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/egr/OneDrive/Games/TioDudaFlu/tioduda/ios/Runner/GeneratedPluginRegistrant.m:6:9:
    fatal error: 'firebase_analytics/FirebaseAnalyticsPlugin.h' file not found
    #import <firebase_analytics/FirebaseAnalyticsPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```
Browsing forums, I did several steps trying to solve it, including downgrade Cocoa Pods to 1.4, tried 1.5 and upgraded again to 1.6 - all with the same problem.

Then I tried deleting some Firebase plugins from my project, but Flutter failed to build anyway - the same fatal error in a different plugin.

Then I tried to "restart": brew update & reinstall, then pod setup.

Then I created a new project from scratch, and only included dependencies on it, but then Flutter crashed unexpectedly.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter packages get
```

## exception
```
FileSystemException: FileSystemException: Cannot copy file to '/Users/egr/OneDrive/Games/TioDudaFlu/tioduda02/ios/Podfile', path = '/Users/Shared/flutter/packages/flutter_tools/templates/cocoapods/Podfile-objc' (OS Error: No such file or directory, errno = 2)
```

```
#0      _File.throwIfError (dart:io/file_impl.dart:647:7)
#1      _File.copySync (dart:io/file_impl.dart:352:5)
#2      _LocalFile&LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:29:50)
#3      CocoaPods.setupPodfile (package:flutter_tools/src/ios/cocoapods.dart:177:23)
#4      injectPlugins (package:flutter_tools/src/plugins.dart:303:17)
<asynchronous suspension>
#5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:142:11)
<asynchronous suspension>
#6      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:84:23)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._complete (dart:async/future_impl.dart:476:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale pt-BR)
    • Flutter version 1.0.0 at /Users/Shared/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • iPhone XR • 9B868665-2269-4DE8-9B33-98BA81D77838 • ios • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.
```

see flutter doctor above.

**Comment by zoechi** [comment]
1. a) vs b) 
This is because a) are plugin packages with native code and b) a pure Dart packages without any native code.

First I'd suggest you use the latest versions of the plugins

```yml
firebase_analytics: ^2.0.1
flutter_web_browser: ^0.10.0
firebase_core: ^0.3.0 # shouldn't be necessary to add this explicitely, it's just used by other firebase plugins
```
https://pub.dartlang.org/packages/firebase_analytics#-versions-tab-

If this does not help, try to switch to `dev` channel and start again with a new project.
(creating a new project should not be necessary, I just think it might help at this point with diagnosing the cause)

```
flutter channel dev
flutter doctor
```

**Comment by egorges** [comment]
Thank you for the suggestions.

Upgrading versions of the plugins ended with the same crash after saving pubspec.yaml - which started packages get & crashed.

flutter channel dev ended with the following:

Switching to flutter channel 'dev'...
git: From https://github.com/flutter/flutter
git:    2c558fdb2..74a908603  master              -> origin/master
git:  * [new branch]          revert-28101-master -> origin/revert-28101-master
git: error: Your local changes to the following files would be overwritten by checkout:
git:    .cirrus.yml
git:    .github/no-response.yml
git:    .gitignore
git:    AUTHORS
git:    CODE_OF_CONDUCT.md
git:    LICENSE
git:    README.md
git:    analysis_options.yaml
git:    bin/flutter.bat
git:    bin/internal/engine.version
git:    bin/internal/goldens.version
git:    bin/internal/update_dart_sdk.ps1
git:    dev/automated_tests/pubspec.yaml
git:    dev/benchmarks/complex_layout/android/app/build.gradle
git:    dev/benchmarks/complex_layout/android/app/src/main/AndroidManifest.xml
git:    dev/benchmarks/complex_layout/ios/Runner.xcodeproj/project.pbxproj
git:    dev/benchmarks/complex_layout/lib/main.dart
git:    dev/benchmarks/complex_layout/pubspec.yaml
git:    dev/benchmarks/microbenchmarks/android/app/build.gradle
git:    dev/benchmarks/microbenchmarks/android/app/src/main/AndroidManifest.xml
git:    dev/benchmarks/microbenchmarks/ios/Runner.xcodeproj/project.pbxproj
git:    dev/benchmarks/microbenchmarks/lib/stocks/build_bench.dart
git:    dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart
git:    dev/benchmarks/microbenchmarks/pubspec.yaml
git:    dev/bots/README.md
git:    dev/bots/VERSION_LINUX_SDK
git:    dev/bots/VERSION_MACOSX_SDK
git:    dev/bots/VERSION_WIN_SDK
git:    dev/bots/analyze-sample-code.dart
git:    dev/bots/analyze.dart
git:    dev/bots/prepare_package.dart
git:    dev/bots/pubspec.yaml
git:    dev/bots/test.dart
git:    dev/bots/test/analyze-sample-code-test-input/known_broken_documentation.dart
git:    dev/bots/test/prepare_package_test.dart
git:    dev/devicelab/README.md
git:    dev/devicelab/bin/tasks/commands_test.dart
git:    dev/devicelab/bin/tasks/run_machine_concurrent_hot_reload.dart
git:    dev/devicelab/bin/tasks/run_release_test.dart
git:    dev/devicelab/lib/framework/adb.dart
git:    dev/devicelab/lib/tasks/microbenchmarks.dart
git:    dev/devicelab/lib/tasks/perf_tests.dart
git:    dev/devicelab/manifest.yaml
git:    dev/devicelab/pubspec.yaml
git:    dev/docs/assets/overrides.css
git:    dev/integration_tests/android_host_app/app/build.gradle
git:    dev/integration_tests/android_semantics_testing/android/app/build.gradle
git:    dev/integration_tests/android_semantics_testing/lib/main.dart
git:    dev/integration_tests/android_semantics_testing/pubspec.yaml
git:    dev/integration_tests/android_semantics_testing/test_driver/main_test.dart
git:    dev/integration_tests/android_views/android/app/build.gradle
git:    dev/integration_tests/android_views/ios/Runner.xcodeproj/project.pbxproj
git:    dev/integration_tests/android_views/lib/main.dart
git:    dev/integration_tests/android_views/pubspec.yaml
git:    dev/integration_tests/android_views/test_driver/main_test.dart
git:    dev/integration_tests/channels/android/app/build.gradle
git:    dev/integration_tests/channels/android/app/src/main/AndroidManifest.xml
git:    dev/integration_tests/channels/ios/Runner.xcodeproj/project.pbxproj
git:    dev/integration_tests/channels/lib/src/method_calls.dart
git:    dev/integration_tests/channels/pubspec.yaml
git:    dev/integration_tests/external_ui/android/app/build.gradle
git:    dev/integration_tests/external_ui/android/app/src/main/AndroidManifest.xml
git:    dev/integration_tests/external_ui/ios/Runner.xcodeproj/project.pbxproj
git:    dev/integration_tests/external_ui/lib/main.dart
git:    dev/integration_tests/external_ui/pubspec.yaml
git:    dev/integration_tests/external_ui/test_driver/main_test.dart
git:    dev/integration_tests/flavors/android/app/build.gradle
git:    dev/integration_tests/flavors/android/app/src/main/AndroidManifest.xml
git:    dev/integration_tests/flavors/ios/Runner.xcodeproj/project.pbxproj
git:    dev/integration_tests/flavors/lib/main.dart
git:    dev/integration_tests/flavors/pubspec.yaml
git:    dev/integration_tests/ios_host_app/Host.xcodeproj/project.pbxproj
git:    dev/integration_tests/named_isolates/android/app/build.gradle
git:    dev/integration_tests/named_isolates/android/app/src/main/AndroidManifest.xml
git:    dev/integration_tests/platform_interaction/android/app/build.gradle
git:    dev/integration_tests/platform_interaction/ios/Runner.xcodeproj/project.pbxproj
git:    dev/integration_tests/platform_interaction/pubspec.yaml
git:    dev/integration_tests/ui/android/app/build.gradle
git:    dev/integration_tests/ui/ios/Runner.xcodeproj/project.pbxproj
git:    dev/integration_tests/ui/pubspec.yaml
git:    dev/manual_tests/android/app/build.gradle
git:    dev/manual_tests/android/app/src/main/AndroidManifest.xml
git:    dev/manual_tests/ios/Runner.xcodeproj/project.pbxproj
git:    dev/manual_tests/lib/main.dart
git:    dev/manual
git: Aborting
Switching channels failed with error code 1.

I though it might be a kind of permission in directories, but moving flutter from a shared directory to a private one, then chmod -R 777 so everybody have read/write. But still same crash.

**Comment by zoechi** [comment]
Somehow you got files in your Flutter install modified. 
Follow https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted to clean that up

**Comment by egorges** [comment]
> Somehow you got files in your Flutter install modified.
> Follow https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted to clean that up

Problem solved!

I made a backup of the corrupted directory and it's available for further analysis.

Thank you!

**Comment by liumin1128** [comment]
@egorges I have the same problem
