### ISSUE TITLE
firebase_ml_vision GS1 Databar Expanded Stacked

### ISSUE THREAD

**Issue by phasee** [flutter/flutter#28236]
Hello,

I am trying to scan a barcode of type "Databar Expanded Stacked" from GS1:

![image](https://user-images.githubusercontent.com/9054058/53134653-00dd5980-3546-11e9-9d27-a08f58ea8a05.png)

This is an example barcode which encodes "011234567890123-ABCabc"

When I scan for this type of barcode I get nothing back

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by kroikie** [comment]
@phasee

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/425. Any further collaboration will be done there.
