### ISSUE TITLE
Error with FirebaseApp.appNamed after update to newest firebase_auth

### ISSUE THREAD

**Issue by zhesha** [flutter/flutter#28248]
I have error after update to newest `firebase_auth` version.
Here is minimal code to reproduce:
`main.dart`:

```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  final FirebaseApp existingApp = await FirebaseApp.appNamed('test');
  print(existingApp);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Text('test'),
      ),
    );
  }
}
```

`pubspec.yaml`

```yml
name: auth_test
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.1+1


flutter:
  uses-material-design: true
```

I get `GoogleService-Info.plist` from example add it using Xcode and update Info.plist with:

```xml
<key>CFBundleURLTypes</key>
  <array>
  	<dict>
  		<key>CFBundleTypeRole</key>
  		<string>Editor</string>
  		<key>CFBundleURLSchemes</key>
  		<array>
  			<string>com.googleusercontent.apps.466218294969-5mdmh6opkqd87a5m81nm83u4eqd3bvgk</string>
  		</array>
  	</dict>
  </array>
```

The problem is: if I add `firebase_auth` version `0.6.6` to this app everything works. But after update to `0.8.1+1` it stop work with error:

```
Launching lib/main.dart on iPhone XR in debug mode...
Starting Xcode build...
Xcode build done.                                           11,2s
5.10.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.10.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50200000 started
5.10.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
5.10.0 - [Firebase/Core][I-COR000004] App with name test does not exist.
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108a1e1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000107fbc735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010896a4ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000108a8d541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x0000000108a19c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x000000010595c389 getDictionaryFromFIRApp + 217
	6   Runner                              0x000000010595c1d1 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 4225
	7   Flutter                             0x0000000105ec59a2 __45-[Flutt<…>
Application finished.
```

with this error impossible to understand what goes wrong, so even if problem with my setup, I think, error handling and message need to be updated. Even if I change version back to `0.6.6` it fires same error.
flutter doctor:

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale uk-UA)
    • Flutter version 1.0.0 at /Users/sashaz/development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/sashaz/Library/Android/sdk
    • Android NDK at /Users/sashaz/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • 711C6B31-EF3A-455C-B25B-211CAD2905F7 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Can you please try executing `pod update` in `ios/`?

**Comment by zoechi** [comment]
#17678 looks similar but not clear what the solution was exactly.

**Comment by Theunodb** [comment]
#28199

**Comment by Theunodb** [comment]
similar to this #28199

**Comment by zhesha** [comment]
> similar to this #28199

Yes, this is same issue, but app crash exactly on "FirebaseApp.appNamed" just "FirebaseApp.configure" call it.

**Comment by zhesha** [comment]
> pod update

'pod update' did not help.

**Comment by zhesha** [comment]
I think I found the problem. plugin firebase_core file FirebaseCorePlugin.m
on block
```
  } else if ([@"FirebaseApp#appNamed" isEqualToString:call.method]) {
    NSString *name = call.arguments;
    FIRApp *app = [FIRApp appNamed:name];
    result(getDictionaryFromFIRApp(app));
  }
```

"FIRApp appNamed" can return `nil`, but getDictionaryFromFIRApp do not handle it.
so 
`result(getDictionaryFromFIRApp(app));`
must be change to
`result(app == nil ? nil : getDictionaryFromFIRApp(app));`

in dart code comments over appNamed says  "Returns a previously created FirebaseApp instance with the given name, or null if no such app exists." so I think it's a good solution.

I am do not know objective-c, so may be there is better way to handle nil.

**Comment by joshuaferguson** [comment]
getDictionaryFromFIRApp looks like it should always return an empty configuration even if the appName is not found, so getDictionaryFromFIRApp should probably be modified to handle a nil "app" object. The actual call to create the configuration dictionary handles a null app (If you look in FirebasePluginCore.m), it's just trying to create a dictionary with a nil key that fails. But I could be totally off.

**Comment by zhesha** [comment]
> `getDictionaryFromFIRApp` looks like it should always return an empty configuration even if the appName is not found, so `getDictionaryFromFIRApp` should probably be modified to handle a `nil` "app" object. The actual call to create the configuration dictionary handles a null app (If you look in `FirebasePluginCore.m`), it's just trying to create a dictionary with a nil key that fails. But I could be totally off.

may be `getDictionaryFromFIRApp` should be modified, but `FirebaseApp#appNamed` should  return nil if app did not found, as some code depends on that.

**Comment by joshuaferguson** [comment]
Ah, excellent, that's what I needed to know. The way the code is written it looks like it's supposed to return a configuration of nulls no matter what, and I wasn't sure if the default app name (__FIRAPP_DEFAULT) should be returned. Of course, I know nothing about what the other frameworks expect so I defer to your assertions.

**Comment by ffeu** [comment]
This issue is solved by this [PR](https://github.com/flutter/plugins/pull/1279) and `firebase_core` version `0.3.1+1`. It may be closed now.

**Comment by zoechi** [comment]
@zhesha the issue should be fixed. Please let us know if you are still seeing this.

**Comment by Arno-Z** [comment]
It may be fixed in firebase_core version 0.3.1+1, but that is not compatible with AndroidX (https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility), leaving with the choice to either support iOS or Android?

**Comment by ffeu** [comment]
Looks like the last comment was deleted, but I use both firebase core and Auth in my app with their latest versions and AndroidX - it works!

**Comment by Arno-Z** [comment]
Yes, I deleted it. How did you get rid of the AndroidX errors?

Arno

arno@zwaag.net
+31648780789

**Comment by ffeu** [comment]
(if I could, I would reply privately)
https://stackoverflow.com/a/54857699/796963

**Comment by kroikie** [comment]
@zhesha

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/424. Any further collaboration will be done there.
