### ISSUE TITLE
Android SDK Licensing issues

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [flutter/flutter#28243]
While installing Flutter, I ran into the SDK licenses issue, and I’ve tried to patch sdkmanager’s JAVAOPTS, and nothing seems to be working. I’ve laid out more in my logs, and feel free to ask me to elaborate on unclear things.

## Steps to Reproduce

1. Run flutter doctor -v and/or flutter run
2. See error

## Logs

https://del.dog/fawepamaha.coffeescript

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
