### ISSUE TITLE
The following NoSuchMethodError was thrown building

### ISSUE THREAD

**Issue by ushang000** [flutter/flutter#28247]
I/flutter ( 2078): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2078): The following NoSuchMethodError was thrown building PhonePage(dirty, state: _PhonePageState#a46a4):
I/flutter ( 2078): The getter 'data' was called on null.
I/flutter ( 2078): Receiver: null
I/flutter ( 2078): Tried calling: data
I/flutter ( 2078): 
I/flutter ( 2078): When the exception was thrown, this was the stack:
I/flutter ( 2078): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 2078): #1      _PhonePageState.build (package:demo03/ui/phone_page.dart:44:30)
I/flutter ( 2078): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 2078): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 2078): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2078): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2078): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2078): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2078): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2078): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2078): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 2078): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2078): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2078): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 2078): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2078): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2078): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2078): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2078): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2078): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2078): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2078): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2078): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2078): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2078): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2078): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2078): #26     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter ( 2078): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2078): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2078): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 2078): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 2078): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 2078): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 2078): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 2078): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 2078): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 2078): #36     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1028:36)
I/flutter ( 2078): #37     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:20)
I/flutter ( 2078): #38     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter ( 2078): #39     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter ( 2078): #40     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter ( 2078): #41     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter ( 2078): #42     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter ( 2078): #43     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter ( 2078): #44     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter ( 2078): #45     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:341:5)
I/flutter ( 2078): #46     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:169:12)
I/flutter ( 2078): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter ( 2078): #48     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 2078): #49     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter ( 2078): #50     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter ( 2078): #51     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter ( 2078): #52     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter ( 2078): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter ( 2078): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter ( 2078): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 2078): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 2078): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 2078): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 2078): #59     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 2078): #60     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 2078): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 2078): {"code":200,"msg":"成功!","data":[{"createdAt":"2017-08-13T23:43:02.253Z","publishedAt":"2017-08-14T17:04:50.266Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fiiiyfcjdoj20u00u0ju0.jpg"},{"createdAt":"2017-08-10T09:37:52.684Z","publishedAt":"2017-08-11T14:05:53.749Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fiednrydq8j20u011itfz.jpg"},{"createdAt":"2017-08-09T08:16:56.373Z","publishedAt":"2017-08-09T13:49:27.260Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fid5poqfznj20u011imzm.jpg"},{"createdAt":"2017-08-07T23:27:21.296Z","publishedAt":"2017-08-08T11:34:20.37Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fibksd2mbmj20u011iacx.jpg"},{"createdAt":"2017-08-03T07:51:00.249Z","publishedAt":"2017-08-03T12:08:07.258Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034gy1fi678xgq1ij20pa0vlgo4.jpg"},{"createdAt":"2017-08-02T06:57:11.207Z","publishedAt":"2017-08-02T12:21:45.220Z","type":"美图","url":"https://ws1.sinaimg.cn/l
V/AudioManager( 2078): playSoundEffect   effectType: 0
V/AudioManager( 2078): querySoundEffectsEnabled...
I/flutter ( 2078): Another exception was thrown: NoSuchMethodError: The getter 'data' was called on null.
I/flutter ( 2078): {"code":200,"msg":"成功!","data":[{"createdAt":"2017-08-13T23:43:02.253Z","publishedAt":"2017-08-14T17:04:50.266Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fiiiyfcjdoj20u00u0ju0.jpg"},{"createdAt":"2017-08-10T09:37:52.684Z","publishedAt":"2017-08-11T14:05:53.749Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fiednrydq8j20u011itfz.jpg"},{"createdAt":"2017-08-09T08:16:56.373Z","publishedAt":"2017-08-09T13:49:27.260Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fid5poqfznj20u011imzm.jpg"},{"createdAt":"2017-08-07T23:27:21.296Z","publishedAt":"2017-08-08T11:34:20.37Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034ly1fibksd2mbmj20u011iacx.jpg"},{"createdAt":"2017-08-03T07:51:00.249Z","publishedAt":"2017-08-03T12:08:07.258Z","type":"美图","url":"https://ws1.sinaimg.cn/large/610dc034gy1fi678xgq1ij20pa0vlgo4.jpg"},{"createdAt":"2017-08-02T06:57:11.207Z","publishedAt":"2017-08-02T12:21:45.220Z","type":"美图","url":"https://ws1.sinaimg.cn/l
W/InputMethodManager( 2078): startInputReason = 8
D/ZrHung.AppEyeUiProbe( 2078): stop checker.
W/libEGL  ( 2078): EGLNativeWindowType 0x76b1a81010 disconnect failed
D/ViewRootImpl[MainActivity]( 2078): surface should not be released
W/libEGL  ( 2078): EGLNativeWindowType 0x76b1a82010 disconnect failed
V/ActivityThread( 2078): Handle window ActivityRecord{f21b6d9 token=android.os.BinderProxy@372eb25 {com.example.demo03/com.example.demo03.MainActivity}} visibility: false
D/ZrHung.AppEyeUiProbe( 2078): Current Activity:false
D/ZrHung.AppEyeUiProbe( 2078): not watching, wait.

get the picture url from json ,sometimes it work,sometimes it doesn't work like above error.

**Comment by pengfei923** [comment]
我也遇到了，这个问题你处理了吗，这个问题是首次加载的时候报这个错误，之后请求网络就好了
