### ISSUE TITLE
How to get data from sqlite and assign to variable?

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#28249]
I stored data on cache using sqflite(sqlite). only one data store in cache. I want to get this data and assign to variable. I didn't want to display this data. How do I do it? I it possible to do without FutureBuilder?
Please answer with code
Thank you
can to read data without FutureBuilder?

**DatabaseHandler.dart**
  ```
Future<List<Url>> getUrl() async{
    var db_connection = await db;
    List<Map> list = await db_connection.rawQuery("SELECT uniform_resource_locator FROM Url Limit 1");

   // print('start');
   // print(list[0]['uniform_resource_locator']);
//    List<Url> urls = List();
//    for(int i = 0; i < list.length; i++){
//      Url url = Url();
//    //  url.id = list[i]['id'];
//      url.uniform_resource_locator = list[i]['uniform_resource_locator'];
//      urls.add(url);
//    }
    return list[0]['uniform_resource_locator'];
  }

```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
