### ISSUE TITLE
Web view Download listener 

### ISSUE THREAD

**Issue by asarkar1990** [flutter/flutter#28257]
is there any way to use download listener with web view ?

**Comment by MilloshFey** [comment]
That would be very helpfull

**Comment by MilloshFey** [comment]
I am really newbie but I kind of got it working (for me, at least).
open FlutterWebviewPlugin.java located at: <flutter directory>\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.0+2\android\src\main\java\com\flutter_webview_plugin.
Then add :
``` java
import android.webkit.DownloadListener;
```
you can add it at line 18.

and 
``` java
webView.setDownloadListener(new DownloadListener() {
            public void onDownloadStart(String url, String userAgent,
                                        String contentDisposition, String mimetype,
                                        long contentLength) {
                Intent i = new Intent(Intent.ACTION_VIEW);
                i.setData(Uri.parse(url));
                activity.startActivity(i);
            }
			});
```
right bellow  "webView.setWebViewClient(webViewClient);" or something.
That worked for me. Hope it work for you too.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/39321

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/39321, since that's where most of the discussion and voting has happened.
