### ISSUE TITLE
Flutter Background color change during Future-Builder waiting state

### ISSUE THREAD

**Issue by iKK001** [flutter/flutter#28255]
I really like Flutter.

However, there is one thing that I observe in my Flutter apps (or trials since I am a newbie):

I get white-screen flickering's all over the place - mostly when setState() is invoked and any kind of Future data takes its sweet time until presented.

I can live with a flicker - but why does it need to be a "white" screen.

How do you change the "flicker" screen color in Flutter when setState() is invoked ?

Is there even a way to prevent the flicker at all ??

Here is an example: 

- My App shows a list with trains departing from Zurich (see gif below).
- for demonstration purposes, I created a timer that calls setState() frequently
- on every setState, the list is queried in an sqflite DB and this takes a wee-moment
- during this short moment, the screen goes "white"
  (how could I change or prevent this white background color during setState flickers ??

![flicker01](https://user-images.githubusercontent.com/8404556/53167060-32523580-35d7-11e9-8693-104b761c7389.gif)

In this particular case, the loading-time is coming from a Future-Builder that does the  SQFLite query. But how do I change the background-colour in there ??

```dart
    return FutureBuilder<List<DepartureModel>>(
      future: getDeparture(container),
      builder:
          (BuildContext context, AsyncSnapshot<List<DepartureModel>> snapshot) {
        switch (snapshot.connectionState) {
          case ConnectionState.none:
            return Text('Press button to start.');
          case ConnectionState.active:
          case ConnectionState.waiting:
            // HERE IS WHERE YOU COULD CHANGE YOUR SCREEN-COLOR - BUT HOW ????
            return Text('Awaiting result...');
          case ConnectionState.done:
            // real code taken out since too long and not relevant for this demo...
            return Text('Success');
        }
        return null; // unreachable
      },
    );
```

Is there a general recommendation on how to set a background that is shown when setState makes an update ?

**Comment by iKK001** [comment]
I think, I've found a solution: The white screen is under my control inside Future-Builder:

```dart
    return FutureBuilder<List<DepartureModel>>(
      future: getDeparture(container),
      builder:
          (BuildContext context, AsyncSnapshot<List<DepartureModel>> snapshot) {
        switch (snapshot.connectionState) {
          case ConnectionState.none:
            return Text('Press button to start.');
          case ConnectionState.active:
          case ConnectionState.waiting:
            // HERE IS WHERE YOU CAN CHANGE YOUR SCREEN-COLOR
            return Text('Awaiting result...');
          case ConnectionState.done:
            return Text('Success');
        }
        return null; // unreachable
      },
    );
```

**Comment by zoechi** [comment]
Please check the 2nd paragraph in https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html

> The future must have been obtained earlier,  ...

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
