### ISSUE TITLE
webview_flutter-0.3.3.1 user-agent missing 

### ISSUE THREAD

**Issue by skmishu** [flutter/flutter#28256]
i wanted to change user agent for a site i need to load in my app and i can't find any possible way to change user agent.

**Comment by 5hanth** [comment]
do we have a solution here yet? 🙏

**Comment by skmishu** [comment]
No, not yet.

**Comment by AresVampire** [comment]
Is there any way to set useragent of webview?

**Comment by BerndWessels** [comment]
@zoechi Yes, definitely a must to be able to do OAuth and Google Sign In - otherwise we get errors like `Google 403 disallowed_useragent`

**Comment by amirh** [comment]
The feature was added by https://github.com/flutter/plugins/pull/1920 available starting version 0.3.13.

Thanks @LuisThein and @YukiOya for working on this!
