### ISSUE TITLE
cloud_functions uses KVC methods unnecessarily

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#28271]
@cyanglaz wrote:

>>> Did you intend to use NSMutableDictionary and setObject:forKey instead of using the KVC method setValue:forKey? Same for below. If the intention is to actually use the KVC, please ignore this comment.

https://github.com/flutter/flutter/issues/28271#issue-413066060

Could potentially lead to bugs, see https://stackoverflow.com/questions/1249634/wheres-the-difference-between-setobjectforkey-and-setvalueforkey-in-nsmutab

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1195. Any further collaboration will be done there.
