### ISSUE TITLE
Manually changing PlatformBrightness

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#28284]
Edited Issue (matthew-carroll):
This issue is a feature request to allow `MaterialApp`'s auto theme switching between `theme` and `darkTheme` to facilitate an explicit override of the `platformBrightness`.  The purpose of this override is to allow users to explicitly select a light mode or dark mode while re-using the automatic theme switching between `theme` and `darkTheme` within `MaterialApp`.

Original Issue:
@matthew-carroll https://github.com/flutter/flutter/pull/26605#issuecomment-466204529

```dart
class ExampleWidget extends StatefulWidget {
  @override
  createState() => _ExampleWidgetState();
}

class _ExampleWidgetState extends State<ExampleWidget> {
  @override
  build(_) => MaterialApp(builder: (context, child) => 
      MediaQuery(data: MediaQuery.of(context).copyWith(platformBrightness: Brightness.dark), 
          child: child), theme: theme, darkTheme: darkTheme, ...);
}
```

I tried to enforce a specific `platformBrightness` this way, but it is not working. Calling `MediaQuery.of(context).platformBrightness` from any route, i.e. child widgets of the `MaterialApp` **will** correctly return the brightness that I specified in the custom `MediaQuery`. However, the theme of the app *does not adjust* to this. It will remain adjusting to the device mode.
I also tried rebuilding the `_ExampleWidgetState` with `Window.onPlatformBrightnessChanged` using `WidgetBindingsObserver` (manually called `handlePlatformBrightnessChanged`).

The obvious takeaway from this is that the brightness cannot be controlled using `MediaQuery`. Hence, I am wondering how I could go about manually enforcing a `platformBrightness` so that the `MaterialApp` adjusts it theme accordingly.

**Comment by matthew-carroll** [comment]
`MediaQuery#platformBrightness` is processed within `MaterialApp` itself.  Please see `app.dart` line 458:

```dart
        // Use a light theme, dark theme, or fallback theme.
        ThemeData theme;
        final ui.Brightness platformBrightness = MediaQuery.platformBrightnessOf(context);
        if (platformBrightness == ui.Brightness.dark && widget.darkTheme != null) {
          theme = widget.darkTheme;
        } else if (widget.theme != null) {
          theme = widget.theme;
        } else {
          theme = ThemeData.fallback();
        }

        return AnimatedTheme(
          data: theme,
          ....
        );
```

You are trying to change theme details as a child of `AnimatedTheme`, but notice that `MaterialApp`'s decision about which theme to use is determined before the build process ever gets there.

There are probably a few ways to get the effect you want, but I'm not clear why you're attempting to utilize `platformBrightness` in this case.  `platformBrightness` exists specifically to connect the host platform, e.g., Android to Flutter and support the platform's preference.  The `darkTheme` property in `MaterialApp` also only exists to connect to `platformBrightness`.

If all you want is runtime control over brightness then you can simply rebuild your MaterialApp with a different `theme` that goes from light to dark or dark to light.  Would that work for you?

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll I would like to have both work dynamically and it is a bit cumbersome to have it seperated in that case, which is why I thought that this should work. I forgot to mention that what I actually tried using `WidgetBindingsObserver` was the the following:

```dart
MediaQuery(
      data: MediaQueryData(platformBrightness: Brightness.dark),
      child: MaterialApp(...))
```

However, this does also not apply the `darkTheme`. Why is that?

**Comment by matthew-carroll** [comment]
The particular approach doesn't work because `MaterialApp` internally contains a `WidgetsApp` which, itself, has a `MediaQuery`.  The code I referenced in my previous post invoked `MediaQuery.platformBrightnessOf()` which resolves to the `MediaQuery` within `WidgetsApp`.  It never makes it all the way up to yours.

But I'm still having trouble understanding exactly what your use-case is.  So far I've gathered you would like your app to automatically switch themes when Android's battery saver or dark mode dev option is enabled.  That works out of the box with `darkTheme`.

However, it seems like you also want some other related behavior that is not entirely based on the platform value.  Can you elaborate on those specific use-cases?  Can you describe the effect that you're going for without mentioning code?  I'm trying to understand the objective.

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll It is pretty simple. By default it should listen to your `platformBrightness` implementation, but the user can dynamically enforce to use the bright or dark theme and then it should not listen to `platformBrightness` anymore.

**Comment by matthew-carroll** [comment]
It may be simple, but what you mean by "dynamically enforce to use the bright or dark theme" does not clearly articulate what is desired.  Can you describe an individual situation that epitomizes the functionality you want?

**Comment by matthew-carroll** [comment]
Are you looking for the ability to forcefully override the platform's preference with your own Brightness preference and still utilize the `theme`/`darkTheme` switching?

**Comment by creativecreatorormaybenot** [comment]
@matthew-carroll Yes, exactly. I am also not sure how to smoothly integrate both options the way you mentioned overriding the `theme`. I feel like I would rebuild too often. I know that the following implementation would work, however, it seems really ugly (just a sketch below):

```
TopWidget -> MaterialApp -> ...

default: MaterialApp(theme: theme, darkTheme: darkTheme)

TopWidget.setState for light theme all the time: MaterialApp(theme: theme, darkTheme: null)

TopWidget.setState for dark theme: MaterialApp(theme: darkTheme, darkTheme: null)
```

**Comment by matthew-carroll** [comment]
If you're looking to override the `platformBrightness` reported by the platform then in which situations would your app actually use the real `platformBrightness`?

**Comment by creativecreatorormaybenot** [comment]
Default behavior uses the real `platformBrightness`, but users might want to manually choose and can opt-in to overriding `platformBrightness`.

**Comment by matthew-carroll** [comment]
Ok.  I'll need to chat about this use-case with @HansMuller and @xster.

I was thinking that you might be able to wrap the `Window` with a proxy but it looks like Flutter's bindings are not setup to facilitate that.  So at the moment you're limited to the situation at-hand.  You should use `theme` for what you want to control and `darkTheme` only for real platform preferences.

I'm going to change this ticket to a feature request and we'll see if we come up with a way to facilitate this.

**Comment by creativecreatorormaybenot** [comment]
I presented the little sketch. Code-wise, how would you go about changing the theme, i.e. is there any way to avoid rebuilding the entire widget tree, i.e. `setState` in `TopWidget`?

**Comment by matthew-carroll** [comment]
I'm not aware of any other way off-hand.  Consider that the `Theme` in your `MaterialApp` might be used any other widget all the way down your tree.  As a result, I think you fundamentally have to rebuild `MaterialApp` with the desired theme changes.

**Comment by matthew-carroll** [comment]
Here is how I did it in a recent presentation (before Dark Mode was available):
https://github.com/matthew-carroll/presentation_materially_better/blob/master/lib/demo_tools/theme_switcher.dart

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/28284#issuecomment-466218089

> So at the moment you're limited to the situation at-hand. You should use `theme` for what you want to control and `darkTheme` only for real platform preferences.

This sounds reasonable to me. Does that cause issues for you @creativecreatorormaybenot?

**Comment by creativecreatorormaybenot** [comment]
@xster No, it is fine. I solved it by using the following:

> ```dart
> MediaQuery(
>       data: MediaQueryData(platformBrightness: Brightness.dark),
>       child: MaterialApp(...))
> ```

By passing a new `Theme` whenever I want to change it. Basically `!forceBrightness ? child : Theme(...)`/

**Comment by matthew-carroll** [comment]
@xster I think this confusion may become common.  We should chat about the possibility of auto switching based on brightness even when it comes from places other than the platform/window.

**Comment by ElderiedGlenvilleState2013** [comment]
> `MediaQuery#platformBrightness` is processed within `MaterialApp` itself. Please see `app.dart` line 458:
> 
> ```dart
>         // Use a light theme, dark theme, or fallback theme.
>         ThemeData theme;
>         final ui.Brightness platformBrightness = MediaQuery.platformBrightnessOf(context);
>         if (platformBrightness == ui.Brightness.dark && widget.darkTheme != null) {
>           theme = widget.darkTheme;
>         } else if (widget.theme != null) {
>           theme = widget.theme;
>         } else {
>           theme = ThemeData.fallback();
>         }
> 
>         return AnimatedTheme(
>           data: theme,
>           ....
>         );
> ```
> 
> You are trying to change theme details as a child of `AnimatedTheme`, but notice that `MaterialApp`'s decision about which theme to use is determined before the build process ever gets there.
> 
> There are probably a few ways to get the effect you want, but I'm not clear why you're attempting to utilize `platformBrightness` in this case. `platformBrightness` exists specifically to connect the host platform, e.g., Android to Flutter and support the platform's preference. The `darkTheme` property in `MaterialApp` also only exists to connect to `platformBrightness`.
> 
> If all you want is runtime control over brightness then you can simply rebuild your MaterialApp with a different `theme` that goes from light to dark or dark to light. Would that work for you?

Hi Matthew, 
where can I find the source code this.

**Comment by matthew-carroll** [comment]
@ElderiedGlenvilleState2013 the source code has changed a bit since this thread, but you can see it here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app.dart#L629
