### ISSUE TITLE
google_sign_in package: EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE

### ISSUE THREAD

**Issue by footurist** [flutter/flutter#28299]
The exception occurs after a first successful login and weirdly seems not to have any noticeable consequences. However, since it's an exception, i thought i'd better open an issue for this.

Exception when running in debug mode:
```
Restarted application in 2.736ms.
E/flutter ( 8274): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 8274): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 8274): The following _Exception was thrown resolving an image codec:
I/flutter ( 8274): Exception: operation failed
I/flutter ( 8274): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter ( 8274): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 8274): Another exception was thrown: Exception: operation failed
```

**Comment by zoechi** [comment]
Seems you are loading a corrupted image file or a image format that is not supported.

**Comment by Footurist** [comment]
> 
> 
> Seems you are loading a corrupted image file or a image format that is not supported.

Well, the weird thing is that I haven't specified any assets. And the exception only occurs after then first successful login with the google_sign_in package.The profile image of the used google account is in a valid format.

**Comment by zoechi** [comment]
The profile image from the google account is the only image you are showing?

**Comment by Footurist** [comment]
> The profile image from the google account is the only image you are showing?

Yes, I made a minimal build that uses the google_sign _in package. So the profile picture, which is implicitly loaded by the avatar class of the package, is literally the only image in the whole app.

**Comment by cyanglaz** [comment]
@footurist could you provide a mini example app to reproduce the issue?
