### ISSUE TITLE
seg fault if icons are missing

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#283]
<a href="https://github.com/devoncarew"><img src="https://avatars.githubusercontent.com/u/1269969?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [devoncarew](https://github.com/devoncarew)**
_Saturday Nov 07, 2015 at 07:23 GMT_
_Originally opened as https://github.com/flutter/engine/issues/2006_

----

From https://github.com/flutter/tools/issues/177, we seg fault if we have trouble finding icons. The tracking issue to update the tutorial is here: https://github.com/flutter/flutter.github.io/issues/71 - to list the icons in a flutter.yaml file - but we should also fix the seg fault.

**Comment by abarth** [comment]
I wasn't able to reproduce this issue.  I tried deleting the `flutter.yaml` file from Stocks and running the app using `flutter start`, but it worked fine (albeit without icons)....  Please re-open if this issue recurs.
