### ISSUE TITLE
Error: No named parameter with the name 'lineHeight'

### ISSUE THREAD

**Issue by qinkangwu** [flutter/flutter#28314]
## Steps to Reproduce

1. flutter run 

## Logs
```
Compiler message:
file:///Users/qkw/Desktop/flutter/packages/flutter/lib/src/rendering/error.dart:96:5: Error: No named parameter with the name 'lineHeight'.
    lineHeight: 1.0,
    ^^^^^^^^^^
org-dartlang-sdk:///flutter/lib/ui/text.dart:635:3: Context: Found this candidate, but the arguments don't match.
  ParagraphStyle({
  ^
Compiler failed on /Users/qkw/Downloads/my_app/lib/main.dart
Error launching application on iPhone 7.
```
```
 [✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/qkw/Desktop/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/qkw/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/qkw/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • iPhone 7 • 6342B8E6-A3CB-4878-8858-31FEE60F3217 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by qinkangwu** [comment]
help me plz.

**Comment by zoechi** [comment]
You might have accidentally modified a Flutter file.
Follow https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted to fix

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by qinkangwu** [comment]
@zoechi Thank you  very much ! it's fixed .

**Comment by qinkangwu** [comment]
> ## Steps to Reproduce
> 1. flutter run
> 
> ## Logs
> ```
> Compiler message:
> file:///Users/qkw/Desktop/flutter/packages/flutter/lib/src/rendering/error.dart:96:5: Error: No named parameter with the name 'lineHeight'.
>     lineHeight: 1.0,
>     ^^^^^^^^^^
> org-dartlang-sdk:///flutter/lib/ui/text.dart:635:3: Context: Found this candidate, but the arguments don't match.
>   ParagraphStyle({
>   ^
> Compiler failed on /Users/qkw/Downloads/my_app/lib/main.dart
> Error launching application on iPhone 7.
> ```
> ```
>  [✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
>     • Flutter version 1.0.0 at /Users/qkw/Desktop/flutter
>     • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
>     • Android SDK at /Users/qkw/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/qkw/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.6.0
> 
> [✓] Android Studio (version 3.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 31.3.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [✓] VS Code (version 1.31.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.23.1
> 
> [✓] Connected device (1 available)
>     • iPhone 7 • 6342B8E6-A3CB-4878-8858-31FEE60F3217 • ios • iOS 12.1 (simulator)
> 
> • No issues found!
> ```

**Comment by qinkangwu** [comment]
fi
