### ISSUE TITLE
Flutter in an existing project

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#28317]
I have integrated a flutter module into an existing native project (iOS / Android).

I want to attach the debugger or the console log to the flutter module when running the native project.

I don't know how or even if it is possible.
To replace this inconvenience so far I have used the hot reload feature and made some additional workarounds for it (I have a text widget to display my prints).

**Comment by neiljaywarner** [comment]
on Android flutter/dart "print" statements do show up.. on iOS I don't find them easily..

**Comment by durduman** [comment]
print statements from flutter appear in the console of xcode as well as android studio but you cannot attach flutter to existing process.

I would be a nice to have in the future.
