### ISSUE TITLE
android app crash at FlutterView.sendLocalesToDart

### ISSUE THREAD

**Issue by hyiso** [flutter/flutter#28321]
## Steps to Reproduce

1. flutter create -t module flutter_lib
2. flutter run to install app on Android device
3. open and crash

## Logs

```
com.example.flutter_lib.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.flutter_lib.host, PID: 21080
    java.lang.NoSuchMethodError: No virtual method getLocales()Landroid/os/LocaleList; in class Landroid/content/res/Configuration; or its super classes (declaration of 'android.content.res.Configuration' appears in /system/framework/framework.jar)
        at io.flutter.view.FlutterView.sendLocalesToDart(FlutterView.java:322)
        at io.flutter.view.FlutterView.<init>(FlutterView.java:186)
        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:161)
        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:89)
        at com.example.flutter_lib.host.MainActivity.onCreate(MainActivity.java:10)
        at android.app.Activity.performCreate(Activity.java:6497)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
        at android.app.ActivityThread.access$1100(ActivityThread.java:170)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
```

flutter doctor -v
```
[✓] Flutter (Channel master, v1.2.2-pre.22, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.2.2-pre.22 at /Users/xxx/Workspace/Flutter/flutter
    • Framework revision dd23be3936 (2 days ago), 2019-02-19 21:35:31 -0800
    • Engine revision f45572e95f
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK at /Users/xxx/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • OPPO A57 • 6491277 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by ifanfaizal** [comment]
I got this problem too after upgrading flutter

> Flutter 1.2.2-pre.37 • channel master • https://github.com/flutter/flutter.git
> Framework • revision 2c558fdb21 (2 days ago) • 2019-02-22 17:51:05 -0800
> Engine • revision f80928a9e4
> Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

> Running  "flutter packages upgrade" in sdm_mobile2...               11.9s

> Running flutter doctor...
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.2.3-pre.15, on Mac OS X 10.13.6 17G65, locale en-ID)
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
> [✓] Android Studio (version 3.3)
> [✓] VS Code (version 1.31.0)
> [✓] Connected device (1 available)

> • No issues found!

**Comment by YangCheung** [comment]
https://developer.android.com/reference/android/content/res/Configuration#getLocales()
Configuration#getLocales() added in API level 24

**Comment by p30arena** [comment]
Same Here

```
[ΓêÜ] Flutter (Channel master, v1.2.3-pre.26, on Microsoft Windows [Version 6.3.9600], locale en-US)
    ΓÇó Flutter version 1.2.3-pre.26 at M:\flutter
    ΓÇó Framework revision 0e984fb237 (86 minutes ago), 2019-02-23 10:08:53 -0800
    ΓÇó Engine revision 0d777b947e
    ΓÇó Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)
```

**Comment by brramos** [comment]
Switching to `stable` channel, fixed my issue. This PR looks like it will fix master https://github.com/flutter/engine/pull/7937

**Comment by cbracken** [comment]
Fixed via flutter/engine#7937 (and flutter/engine#7938). Thanks to those who reported this and to @pepegich and @p30arena for their fix PRs.

**Comment by cbracken** [comment]
This was introduced in flutter/engine#7892 and included in `v1.2.2` which is the current `dev` channel release. Looks like `beta` is still at `v1.1.8`. I've marked 1.2.2 as bad on the [wiki](https://github.com/flutter/flutter/wiki/Bad-Builds).

**Comment by ifanfaizal** [comment]
after running 'flutter upgrade', I still got the crash

**Comment by zoechi** [comment]
@ifanfaizal The fix was in the engine. It might take a while until a new Flutter master channel build becomes available that contains the fixed engine build.

**Comment by ifanfaizal** [comment]
@Günter Zöchbauer ahh I see, thanks for telling me

**Comment by zubroid** [comment]
Hi all! I believe I have the latest release and still my app crashes on OnePlus One, but works fine on simulator. 

Flutter 1.2.3-pre.32 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1a182bf7bf (4 hours ago) • 2019-02-25 02:40:28 -0500
Engine • revision 502c9c4002
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

**Comment by ifanfaizal** [comment]
@zubroid like the @zoechi said, we need to wait till the master channel got updated with the fixed engine build. I believe that ur simulator running Android above API 23, but not with ur device.

**Comment by cbracken** [comment]
This should now have rolled to Flutter `master` branch.

/cc @ifanfaizal @zubroid
