### ISSUE TITLE
all examples fail with "version solving failed"

### ISSUE THREAD

**Issue by logemann** [flutter/flutter#28322]
there were already a few posts about this but honestly i dont get them. For a simple person like me, i would expect that when installing a 1.0 Flutter SDK, all the examples from flutter.io would work. So i checked out the examples and tried to run them via:

flutter run

All i get is:

**The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.
Because hello_world depends on test_api >=0.2.2 which requires SDK version >=2.1.0 <3.0.0, version solving failed.**

Below the doctor output. So there shouldnt be a problem when running the examples with a 1.0 Release of the framework right?

```

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale de-DE)
    • Flutter version 1.0.0 at /Users/ml/development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ml/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/ml/software/editor/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/ml/software/editor/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

```

**Comment by zoechi** [comment]
Can you please link to a concrete example that does not work?

**Comment by logemann** [comment]
As seen above i tested it with:
https://github.com/flutter/flutter/tree/master/examples/hello_world

same results with:
https://github.com/flutter/flutter/tree/master/examples/flutter_gallery

**Comment by zoechi** [comment]
- https://github.com/flutter/flutter/tree/master/examples/hello_world can not reproduce
- https://github.com/flutter/flutter/tree/master/examples/flutter_gallery can not reproduce
- https://github.com/flutter/samples/tree/master/place_tracker

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by logemann** [comment]
Dont know what i can do more to help on this one. I even reinstalled flutter with the exact same results.

**Comment by zoechi** [comment]
I think I understand the error message, but I do not understand why it happens to you, but not to me.

I'd expect the simplest fix for you to switch to `beta` channel

```
flutter channel beta
flutter doctor
```
and then try to run the examples again.

**Comment by logemann** [comment]
here we go. Fails with slightly different message:

```
Loge-MacBook-Pro:hello_world ml$ flutter run
Running "flutter packages get" in hello_world...                 
Because hello_world depends on flutter_test any from sdk which depends on test_api 0.2.1, test_api 0.2.1 is required.
So, because hello_world depends on test_api 0.2.2, version solving failed.
 
pub get failed (1)
Loge-MacBook-Pro:hello_world ml$ flutter channel
Flutter channels:
* beta
  dev
  master
  stable
```

**Comment by zoechi** [comment]
Sorry my bad, it should have been `dev` instead of `beta`. I think the last `beta` version is as old as the last `stable`.
````
flutter channel dev
flutter doctor
```

**Comment by logemann** [comment]
This in fact works. Now the question is why doesnt it work while being on "stable" channel. Am i the only one who has problems with that? Were you on "stable" channel when you tested it?

**Comment by zoechi** [comment]
@logemann yes, I tested it with `stable`

> `[✓] Flutter (Channel stable, v1.0.0, ...`

Sorry, I have no idea what could have caused your problem. It's a bit weird.

**Comment by zoechi** [comment]
I hope it's ok to close. It's hard to look for a solution when it's not clear how to reproduce.
I assume you are unblocked.
Just add a comment if you find out more and we can reopen.
