### ISSUE TITLE
Double shadow flash when moving component list underneath app bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2832]
Scrolling the component list up under the app bar flashes the shadow at the border between the app bar and the component list.

Movie:  https://dl.dropboxusercontent.com/u/316685/RECORDING.mp4

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by sethladd** [comment]
FWIW, this is still happening, using a build from April 4th.

**Comment by abarth** [comment]
It looks like the bug is in the lerping for the box shadow.
