### ISSUE TITLE
ValueChanged<String> is successfull but show error mesage.

### ISSUE THREAD

**Issue by faisalramdan17** [flutter/flutter#28324]
## Steps to Reproduce

1.  Make Class by ValueChanged<String> parameters :
```
    class ChatMessage extends StatelessWidget {
        final ValueChanged<String> onClickedButton;

```
2. Use class :
   ```
       setState(() {
            _messages.insert(
              0,
              ChatMessage(
                message: message,
                username: username,
                isButton: true,
                onClickedButton: _handleSubmitted,
              ));
          }); 

```

## Logs

I/flutter ( 4397): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 4397): The following ArgumentError was thrown while handling a gesture:
I/flutter ( 4397): Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as
I/flutter ( 4397): arguments, and return a a valid result: Closure: (Exception) => void
I/flutter ( 4397): 
I/flutter ( 4397): When the exception was thrown, this was the stack:
I/flutter ( 4397): #2      ChatScreenPresenter.sendMessage 
package:opet_flutter/…/Chat/chat_screen_presenter.dart:99
I/flutter ( 4397): #3      ChatScreenState._handleSubmitted 
package:opet_flutter/…/Chat/chat_screen.dart:717
I/flutter ( 4397): #4      ChatScreenState.onLoadMessageSuccess.<anonymous closure>.<anonymous closure> 
```


End :

```
I/flutter ( 4397): Handler: onTap
I/flutter ( 4397): Recognizer:
I/flutter ( 4397):   TapGestureRecognizer#3fc3f(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
I/flutter ( 4397):   Offset(215.6, 342.1), sent tap down)
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
