### ISSUE TITLE
http POST 404

### ISSUE THREAD

**Issue by quangas** [flutter/flutter#28329]
Is there a problem with http.post or some configuration that needs to be set to allow this to hit an API endpoint?

I'm trying to hit a simple POST /sign_in endpoint and via Postman, it works fine. However, if I do it through flutter, it's always returning a 404. Any idea why this would be the case?

```dart
Future<User> requestSignIn(String username, String password) async {
    final url = "https://sample.domain/sign_in";

    Map<String, String> data = {
      "username": username,
      "password": password
    };

    final response = await http.post(
      url,
      body: data
    );

    print(response.body); // just returns 404

    return null;
  }
```

Also tried sending in a header with `application/json` content type. Tried on both iphone and android.

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.0.0
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by zoechi** [comment]
Is this on a 
- real device or an emulator/simulator
- Android or iOS
- debug build or release build
?

Postman runs on your development machine, but Flutter code runs on the device/emulator
so the network settings of the device/emulator are relevant.
Does the device/emulator have a WiFi connection?

**Comment by quangas** [comment]
Hi Zoechi,

Yes, it's running from an emulator (both ios & android) - debug mode. I've tried some GET requests also and they seem to be working. Not sure why a POST is not coming through.

**Comment by zoechi** [comment]
Actually 404 is a response from the server. This means the server tells you that the URL you requested does not exist. 

https://en.wikipedia.org/wiki/HTTP_404

> to indicate that the client was able to communicate with a given server, but the server could not find what was requested.

I don't see how this could be related to Flutter at all.

Is there a proxy involved somehow?

**Comment by quangas** [comment]
Is there any way to monitor the http network request? I think i saw another issue somewhere that perhaps the body is not being sent through to the payload.

**Comment by zoechi** [comment]
@quangas perhaps https://github.com/flutter/flutter/issues/20376#issuecomment-439223882

**Comment by quangas** [comment]
`body: data`

should be

`body: json.encode(data)`

and don't forget to import

`import 'dart:convert';`
