### ISSUE TITLE
iPad Pro: Display Issue in Release Build

### ISSUE THREAD

**Issue by ened** [flutter/flutter#28330]
When navigating through the app, or tapping certain elements a few times in a row, the iPad Pro (12.9") will render the following:

![img_4ca74bb3fa56-1](https://user-images.githubusercontent.com/269860/53246301-4a1ade00-36eb-11e9-9cf9-91379b354ca1.jpeg)

I would love to get feedback where this may come from.

Also, there are visible screen artifacts when throughout the app and when when touching various elements. See the video:

https://www.dropbox.com/s/nuqpgnjat3dj4bw/IMG_5421.MOV?dl=0

## Steps to Reproduce

1. Build iOS App in release mode
2. Distribute via Testflight

## Logs

The issue was seen on iOS 12.2beta3, but also occurred on a earlier iOS version (12.1.4), both running in iPad Pro 12.9" (second generation)./

The flutter version which build the iOS APP:

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/ened/dev/flutter
    • Framework revision 8661d8aecd (7 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Can you provide a minimal reproduction?

**Comment by ened** [comment]
@zoechi I'll try to create a sample flutter app (Github repo) with sufficient complexity to trigger the issue.
