### ISSUE TITLE
How to set an element to bottom of SingleCildScrollView?

### ISSUE THREAD

**Issue by FogelAO** [flutter/flutter#28331]
I have created a screen that works well with the columns, but I needed to scroll because of the keyboard. I am using SingleChildScrollView, but Column's MainAxisAligment doesn't work inside of Scrollable.

I have googled this problem and found this: [Flutter - SingleChildScrollView interfering in columns](https://stackoverflow.com/questions/45982176/flutter-singlechildscrollview-interfering-in-columns) But there are no solution for this concrete problem. Also I've created [question ](https://stackoverflow.com/questions/54762606/how-to-set-an-element-to-bottom-of-singlecildscrollview)at StackOverFlow, but no results. So, I have to ask here, because no one.
**Main problem is - I need to set Widget at bottom of Scrollable**

_I want something like_ 
![image](https://user-images.githubusercontent.com/24193116/53247573-c2ba7400-36c4-11e9-934b-307f6ae98b76.png)
 with scrollable content beacuse of keyboard.

_But I have this_
![image](https://user-images.githubusercontent.com/24193116/53247608-d665da80-36c4-11e9-8509-cfb7ca71a013.png)

**My code:**
```dart
SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Form(
              child: Column(
                children: <Widget>[
                  buildTextField(
                    'E-mail',
                    (text) {},
                    controller: _loginController,
                    textColor: Theme.of(context).buttonColor,
                    hintColor: Theme.of(context).hintColor,
                    margin: EdgeInsets.only(top: 16),
                  ),
                  buildTextField(
                    'Password',
                    (text) {},
                    focus: _textSecondFocusNode,
                    controller: _passwordController,
                    onSubmit: (_) => presenter.login(_loginController.text, _passwordController.text),
                    textColor: Theme.of(context).buttonColor,
                    hintColor: Theme.of(context).hintColor,
                    letterSpacing: 15,
                    icon: InkWell(
                      onTap: () {
                      },
                      child: Image.asset('assets/ic_eye.png'),
                    ),
                    margin: const EdgeInsets.only(top: 16),
                    padding: const EdgeInsets.only(left: 16, top: 4, bottom: 4),
                    obscureText: true,
                  ),
                ],
              ),
            ),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.only(top: 0),
                  child: InkWell(
                    child: Text(
                      'Registration',
                      style: TextStyle(color: Theme.of(context).buttonColor, decoration: TextDecoration.underline),
                    ),
                    onTap: () =>
                        Navigator.push(context, CupertinoPageRoute(builder: (context) => StartRegistrationScreen())),
                  ),
                ),
                Buttons.buildRaisedButton(
                  Text(
                    'Login',
                    style: TextStyle(color: Colors.white, fontSize: 17, fontFamily: 'SFUIDisplay'),
                  ),
                  (){},
                  color: Theme.of(context).buttonColor,
                  disabledColor: Theme.of(context).disabledColor,
                  margin: const EdgeInsets.only(top: 16),
                ),
                Padding(
                  padding: const EdgeInsets.only(top: 16, bottom: 16),
                  child: Text(
                    'Forgot password',
                    style: TextStyle(
                      color: Theme.of(context).buttonColor,
                      decoration: TextDecoration.underline,
                    ),
                  ),
                )
              ],
            )
          ],
        ),
      );
```

**Comment by Kartik1607** [comment]
Is there a particular reason you need a `SingleChildScrollView` ? For your particular need, a `Column` would suffice. Try running below code and see if it helps.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("App"),
        ),
        body: Column(
          children: <Widget>[
            TextField(
              decoration: InputDecoration(helperText: "Text 1"),
            ),
            TextField(
              decoration: InputDecoration(helperText: "Text 2"),
            ),
            Expanded(child: Container()),
            RaisedButton(
              onPressed: () {},
              child: Text("Submit"),
            )
          ],
        ));
  }
}
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by FogelAO** [comment]
@Kartik1607 I need `SingleChildScrollView` because of keyboard, it will overflow bottom.

**Comment by tieorange** [comment]
Sounds like Stackoverflow question. Not an issue.
I have the same question now

**Comment by resfandiari** [comment]
I think this is a better way، if all item size be lower than page height size

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  var appBar = AppBar(
    title: Text("App"),
  );

  @override
  Widget build(BuildContext context) {
    var _pageSize = MediaQuery.of(context).size.height;
    var _notifySize = MediaQuery.of(context).padding.top;
    var _appBarSize = appBar.preferredSize.height;

    return Scaffold(
        appBar: appBar,
        body: SingleChildScrollView(
          child: Container(

            height: _pageSize - (_appBarSize + _notifySize),

            child: Column(
              children: <Widget>[
                TextField(
                  decoration: InputDecoration(helperText: "Text 1"),
                ),
                TextField(
                  decoration: InputDecoration(helperText: "Text 2"),
                ),
                TextField(
                  decoration: InputDecoration(helperText: "Text 3"),
                ),
                TextField(
                  decoration: InputDecoration(helperText: "Text 4"),
                ),


                Expanded(child: Container()),
                RaisedButton(
                  onPressed: () {},
                  child: Text("Submit"),
                )
              ],
            ),
          ),
        ));
  }
}
```

**Comment by neemosh** [comment]
> I think this is a better way، if all item size be lower than page height size
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
> 
>   var appBar = AppBar(
>     title: Text("App"),
>   );
> 
>   @override
>   Widget build(BuildContext context) {
>     var _pageSize = MediaQuery.of(context).size.height;
>     var _notifySize = MediaQuery.of(context).padding.top;
>     var _appBarSize = appBar.preferredSize.height;
> 
>     return Scaffold(
>         appBar: appBar,
>         body: SingleChildScrollView(
>           child: Container(
> 
>             height: _pageSize - (_appBarSize + _notifySize),
> 
>             child: Column(
>               children: <Widget>[
>                 TextField(
>                   decoration: InputDecoration(helperText: "Text 1"),
>                 ),
>                 TextField(
>                   decoration: InputDecoration(helperText: "Text 2"),
>                 ),
>                 TextField(
>                   decoration: InputDecoration(helperText: "Text 3"),
>                 ),
>                 TextField(
>                   decoration: InputDecoration(helperText: "Text 4"),
>                 ),
> 
> 
>                 Expanded(child: Container()),
>                 RaisedButton(
>                   onPressed: () {},
>                   child: Text("Submit"),
>                 )
>               ],
>             ),
>           ),
>         ));
>   }
> }
> ```

it works fine but when i rotate the device the overflow error appear

**Comment by rin0o1** [comment]
I have the same problem, with a Column within a SIngleChilScrollView

**Comment by dozykeys** [comment]
Found a solution
Create a column, and have SingleChildScrollView as one of its children....and then the other Widget that should be at the bottom as a second child of that column.You can go ahead to input all the other children of the SingleChildScrollView.i hope this helps...if it does not.You can write me a mail for further help.. chidozieduru@gmal.com

**Comment by dozykeys** [comment]
Here is an example
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:vecteezy/Login.dart';
import 'package:flutter/services.dart';
import 'package:vecteezy/SmallCircle.dart';
import 'package:vecteezy/my_flutter_app_icons.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion(
      value: SystemUiOverlayStyle.light.copyWith(
        statusBarColor: Colors.red[900],
      ),
      child: Scaffold(
        backgroundColor: Colors.red[300],
        body: Padding(
          padding: EdgeInsets.only(top: 2.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              SingleChildScrollView(
                child: Container(
                  width: double.infinity,
                  decoration: BoxDecoration(
                    border: Border(
                        top: BorderSide(
                      color: Colors.white,
                      width: 10.0,
                    )),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      Container(
                        padding: EdgeInsets.symmetric(
                            horizontal: 30.0, vertical: 50.0),
                        child: TextField(
                          style: TextStyle(
                            color: Colors.white,
                          ),
                          keyboardType: TextInputType.text,
                          cursorColor: Colors.white,
                          decoration: InputDecoration(
                              prefixIcon:
                                  Icon(Icons.search, color: Colors.white),
                              contentPadding: EdgeInsets.symmetric(
                                  vertical: 10.0, horizontal: 20.0),
                              focusedBorder: OutlineInputBorder(
                                borderSide: BorderSide(
                                  style: BorderStyle.solid,
                                  color: Colors.white,
                                  width: 1.0,
                                ),
                                borderRadius: BorderRadius.circular(20.0),
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderSide: BorderSide(
                                  style: BorderStyle.solid,
                                  color: Colors.white,
                                  width: 1.0,
                                ),
                                borderRadius: BorderRadius.circular(20.0),
                              ),
                              hintText: 'Search',
                              hintStyle: TextStyle(
                                fontFamily: 'ssp',
                                color: Colors.white,
                              )),
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: <Widget>[
                            SmallCircle(icon: Icons.settings, text: 'Settings'),
                            SmallCircle(
                                icon: MyFlutterApp.heart_filled,
                                text: 'Favourite'),
                            SmallCircle(
                                icon: Icons.location_on, text: 'Location'),
                          ],
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: <Widget>[
                            SmallCircle(icon: Icons.info_outline, text: 'Info'),
                            SmallCircle(icon: Icons.music_note, text: 'Songs'),
                            SmallCircle(
                                icon: Icons.cast_connected,
                                text: 'Connections'),
                          ],
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: <Widget>[
                            SmallCircle(icon: Icons.chat, text: 'Chat'),
                            SmallCircle(icon: Icons.access_time, text: 'Time'),
                            SmallCircle(
                                icon: Icons.record_voice_over, text: 'Growth'),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.symmetric(vertical: 30.0),
                color: Colors.red[900],
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: <Widget>[
                    SmallCircle(icon: Icons.home, text: 'Home'),
                    SmallCircle(icon: Icons.plus_one, text: 'Points'),
                    SmallCircle(
                        icon: Icons.supervisor_account, text: 'Accounts'),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by dozykeys** [comment]
```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion(
      value: SystemUiOverlayStyle.light.copyWith(
        statusBarColor: Colors.red[900],
      ),
      child: Scaffold(
        backgroundColor: Colors.red[300],
        body: Padding(
          padding: EdgeInsets.only(top: 2.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              SingleChildScrollView(
                child: Container(
                  width: double.infinity,
                  decoration: BoxDecoration(
                    border: Border(
                        top: BorderSide(
                      color: Colors.white,
                      width: 10.0,
                    )),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      Container(
                        padding: EdgeInsets.symmetric(
                            horizontal: 30.0, vertical: 50.0),
                        child: TextField(
                          style: TextStyle(
                            color: Colors.white,
                          ),
                          keyboardType: TextInputType.text,
                          cursorColor: Colors.white,
                          decoration: InputDecoration(
                              prefixIcon:
                                  Icon(Icons.search, color: Colors.white),
                              contentPadding: EdgeInsets.symmetric(
                                  vertical: 10.0, horizontal: 20.0),
                              focusedBorder: OutlineInputBorder(
                                borderSide: BorderSide(
                                  style: BorderStyle.solid,
                                  color: Colors.white,
                                  width: 1.0,
                                ),
                                borderRadius: BorderRadius.circular(20.0),
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderSide: BorderSide(
                                  style: BorderStyle.solid,
                                  color: Colors.white,
                                  width: 1.0,
                                ),
                                borderRadius: BorderRadius.circular(20.0),
                              ),
                              hintText: 'Search',
                              hintStyle: TextStyle(
                                fontFamily: 'ssp',
                                color: Colors.white,
                              )),
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: <Widget>[
                            SmallCircle(icon: Icons.settings, text: 'Settings'),
                            SmallCircle(
                                icon: MyFlutterApp.heart_filled,
                                text: 'Favourite'),
                            SmallCircle(
                                icon: Icons.location_on, text: 'Location'),
                          ],
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: <Widget>[
                            SmallCircle(icon: Icons.info_outline, text: 'Info'),
                            SmallCircle(icon: Icons.music_note, text: 'Songs'),
                            SmallCircle(
                                icon: Icons.cast_connected,
                                text: 'Connections'),
                          ],
                        ),
                      ),
                      Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceAround,
                          children: <Widget>[
                            SmallCircle(icon: Icons.chat, text: 'Chat'),
                            SmallCircle(icon: Icons.access_time, text: 'Time'),
                            SmallCircle(
                                icon: Icons.record_voice_over, text: 'Growth'),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Container(
                padding: EdgeInsets.symmetric(vertical: 30.0),
                color: Colors.red[900],
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: <Widget>[
                    SmallCircle(icon: Icons.home, text: 'Home'),
                    SmallCircle(icon: Icons.plus_one, text: 'Points'),
                    SmallCircle(
                        icon: Icons.supervisor_account, text: 'Accounts'),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by kasvith** [comment]
having the same issue

**Comment by LabN36** [comment]
for those looking for answer, you can look this answer [from Stackoverflow](https://stackoverflow.com/a/56327933/2850120)
