### ISSUE TITLE
Can't run app after installing built release/debug apk when on master branch

### ISSUE THREAD

**Issue by worldofsites** [flutter/flutter#28336]
The problem is reproduced within a day after updating the latest packages from the master branch.
Before that, everything was working well.

Steps to reproduce:
1) terminal -> flutter channel master
2) terminal -> flutter upgrade
3) create new project
4) run project on emulator, all should works
5) terminal -> flutter build apk
6) manual copy apk to android physical device, install, try to run, fail
9) terminal -> flutter channel stable
10) terminal -> flutter upgrade
11) change pubsbec.yaml:
sdk: "> = 2.1.0-dev.9.4.flutter-f9ebf21297 <3.0.0"
12) terminal -> flutter clean
13) run project on emulator, all should works
14) terminal -> flutter build apk
15) manual copy apk to android physical device, install, try to run, all ok

Thus, it turns out that this was influenced by one of the latest changes in the master branch.

![image](https://user-images.githubusercontent.com/23352829/53254910-029a4f00-36f7-11e9-9acb-ba8668069955.png)

Master:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.2.3-pre.5, on Microsoft Windows [Version 10.0.17763.316], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)
• No issues found!
```
Stable:
```
Doctor summary (to see all details, run flutter doctor -v):
 [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version
     10.0.17763.316], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)
• No issues found!
```

**Comment by zoechi** [comment]
`flutter logs` does not provide any related output?

**Comment by worldofsites** [comment]
@zoechi 
> `flutter logs` does not provide any related output?

No related output info when running on emulators or via pc connecting device:
```
Showing Android SDK built for x86 logs:
I/flutter ( 5756): Observatory listening on http://127.0.0.1:40678/
```

Currently I'm trying to run an application without pc connecting. That is, I manually shared this file to device, successfully installed it, and then I try to run it.
Is it possible in that way to get the run logs on the device?

**Comment by worldofsites** [comment]
@zoechi 
Debug console (when run with pc connecting device):
```
Launching lib\main.dart on Easy S Pro in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/Process (23897): Sending signal. PID: 23897 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Comment by worldofsites** [comment]
@zoechi 
Please close that issue.
Not reproduced after upgrading to last state of master branch.
