### ISSUE TITLE
 Wrong Unit Flutter performance

### ISSUE THREAD

**Issue by minamorcose** [flutter/flutter#28357]
Build: 3.3.1, AI-182.5107.16.33.5264788, 201901282352, AI-182.5107.16.33.5264788, JRE 1.8.0_152-release-1248-b01x64 JetBrains s.r.o, OS Linux(amd64) v4.20.8-200.fc29.x86_64 unknown, screens 1920x1080, 1366x768Android Gradle Plugin: 3.3.1Gradle: (gradle version information not found)NDK: from local.properties: UNKNOWN; latest from SDK: 19.1.5304403; LLDB: pinned revision 3.1 not found; latest from SDK: (package not found); CMake: from local.properties: (not specified); latest from SDK: 3.6.0-rc2; from PATH: (not found); Source: user_sentiment_feedback IMPORTANT: Please read https://developer.android.com/studio/report-bugs.html carefully and supply all required information.
in Flutter Performance Moniter it show to me that my programe using 30.3 GB But i think it means it uses 30.3 MB
![screenshot from 2019-02-17 17-05-54](https://user-images.githubusercontent.com/1900104/53274105-b18e5900-36fe-11e9-88a5-9cea401e7f04.png)

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3229](https://github.com/flutter/flutter-intellij/issues/3229) via [**ZenHub**](https://www.zenhub.com/)
