### ISSUE TITLE
Build fails when using firebase-auth plugin

### ISSUE THREAD

**Issue by sidprice** [flutter/flutter#28358]
I am using Android Studio 3.3.1, Flutter (Channel master, v1.2.2-pre.44, on Microsoft Windows [Version 10.0.17134.590], locale en-US), and firebase-auth 0.8.1+3.

I am just starting to build my project by building the authentication classes and using the above code I get the following - "error: cannot find symbol import androidx.annotation.NonNull;" output many times.

I have tried the process of migrating the project to AndroidX, this results in a message box that says "No Usages Found in the Project".

Other than down-grading the firebase-auth plugin, is there a way to resolve this please?
Sid

**Comment by sid19991** [comment]
Same error here as well

**Comment by sidprice** [comment]
@sid19991 This may be an issue with the Android Studio "Migrate to AndroidX" feature. I added the the following lines to the "gradle.properties" file and now my build owrks.

android.useAndroidX=true
android.enableJetifier=true

Sid

**Comment by sid19991** [comment]
thanks for the suggestion. I already did that and it worked.

**Comment by zoechi** [comment]
Sounds like this can be closed then.
