### ISSUE TITLE
Camera Orientation / ImageRotation Firebase Vision

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#28350]
I'm using this plugin to detect faces:
https://pub.dartlang.org/packages/firebase_ml_vision

and this plugin to provide live camera images to the prev one:
https://pub.dartlang.org/packages/camera

the problem is, I need to know the Camera's Orientation to provide it to the FirebaseVisionImageMetadata
but it seems that Camera plugin doesn't provide that.

whats your suggestion?

Its a Feature Request, so I thought I should not ask on StackOverflow.

**Comment by p30arena** [comment]
https://github.com/flutter/flutter/issues/19274#issuecomment-465747841

> However, there is still one limitation in the [camera plugin](https://github.com/flutter/plugins/tree/master/packages/camera) that are needed to complete this.
> 
>     * Access to the rotation of the physical camera. This would help the implementation work with landscape mode and various devices with less common camera rotation, such as tablets.

**Comment by athornz** [comment]
This is a blocker for any processing of the camera stream as different devices have different camera sensor orientations.

**Comment by p30arena** [comment]
@Hixie @bparrishMines 
This PR may help:
https://github.com/flutter/plugins/pull/1261

**Comment by bparrishMines** [comment]
Closing due to fix from https://github.com/flutter/plugins/pull/1261

**Comment by p30arena** [comment]
example usage

```
availableCameras().then((List<CameraDescription> camerasList) {

...

camera.sensorOrientation
```
