### ISSUE TITLE
We don't exercise enough Windows specific tests for the Android SDK

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#28354]
For example, they create executable files without the ".exe" extension.  

We should create a set of tests for a Windows based Android SDK.

**Comment by dnfield** [comment]
This is partially addressed by https://github.com/flutter/flutter/pull/28355

We still should test some more things around aapt being available and other windows-specific things where the .exe or the .bat matters.

**Comment by blasten** [comment]
This is fixed  🎉
