### ISSUE TITLE
Sample code does not provide same context clues as IDE

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#28364]
Sample code in both api docs and on flutter.dev does not contain the same context clues to identify closing brackets, braces, and parentheses. This can be a bit frustrating when just starting out, especially when trying to debug and compare to a sample snippet. 
Illustrated below:

### Sample Code from Flutter Cookbook
![screen shot 2019-02-22 at 2 22 40 pm](https://user-images.githubusercontent.com/16964204/53275138-cc38e180-36ae-11e9-8190-e03b8da4cb1d.png)

### Code Reproduced in VSCode
![screen shot 2019-02-22 at 2 23 47 pm](https://user-images.githubusercontent.com/16964204/53275140-cc38e180-36ae-11e9-8734-481873c74a32.png)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2445](https://github.com/flutter/website/issues/2445) via [**ZenHub**](https://www.zenhub.com/)
