### ISSUE TITLE
[google_maps_flutter] Refactor serialization methods in Covert.java to make them better.

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#28363]
https://github.com/flutter/plugins/pull/1229#discussion_r259530087

**Comment by TahaTesser** [comment]
Hi @iskakaushik 
Is this issue still valid?
Thank you

**Comment by iskakaushik** [comment]
It is still valid.

**Comment by stuartmorgan** [comment]
Since we plan to migrate all plugins to Pigeon, I don't think refactoring the method channel conversation code is still worthwhile.
