### ISSUE TITLE
[Testing] Gallery smoke tests timing out while still running

### ISSUE THREAD

**Issue by willlarche** [flutter/flutter#28365]
I added another study to the gallery and now that takes too long to smoke test. It just gets to starting the a11y smoke tests and it times out.

PR:
https://github.com/flutter/flutter/pull/28125

Failed test:
https://cirrus-ci.com/task/4997614274609152

CC: @jonahwilliams @HansMuller

**Comment by jonahwilliams** [comment]
cc @dnfield could we shard out the smoke tests from the other gallery tests?

**Comment by dnfield** [comment]
My understanding is that the smoke tests run on every PR so that we can be sure that the test setup is working for that environment.  

I think for this we really just need to split up how much we're testing in a single run.

**Comment by dnfield** [comment]
Also, the tests don't normally take anywhere near this long to run.  I'm also seeing crashes in another Mac builder that I hadn't seen before today.  It's possible the provider is just under heavy load right now.  However, we should look at sharding out our tests a bit, or improving the performance of them so it doesn't take as long as it does.

**Comment by willlarche** [comment]
I think everyone did rush to get things in while the tree was green. Maybe
I had bad luck with resourcing.

**Comment by goderbauer** [comment]
Closing this one since there haven't been any recent reports. Please feel free to reopen if this is still happening.
