### ISSUE TITLE
Weird behaviour after drawing arc in canvas

### ISSUE THREAD

**Issue by MandelWarrior** [flutter/flutter#28375]
### Issue
When I draw an arc with a paint that has its style argument set to PaintingStyle.stroke and then I try to draw several circles with a paint that has its style argument set to PaintingStyle.fill, only the first one is drawn

### Steps to Reproduce
Create a Paint with style set to PaintingStyle.stroke.
Draw arc in canvas with that paint.
Create a Paint with style set to PaintingStyle.fill.
Draw circle in canvas with that paint.
Draw another circle with the same paint.

The last circle is not going to be drawn.

## Sample code without drawing arc (two circles being drawn correctly)
```dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

void main()
=> runApp(MyApp());

class MyApp extends StatelessWidget
{

	@override
	Widget build(BuildContext context)
	{
		return MaterialApp(
			title: 'Flutter Demo',
			theme: ThemeData(
				primarySwatch: Colors.blue,
			),

			home: Scaffold(
					body: Center(
						child: CustomPaint(
							painter: PickerPainter(),
							size: Size(300, 300),
						),
					)
			),
		);
	}
}


class PickerPainter extends CustomPainter
{
	double smallCircleRadius = 10;
	double bigCircleRadius = 100;

	@override
	void paint(Canvas canvas, Size size)
	{
		Offset screenCenter = size.center(Offset.zero);
		
		Paint fractionCirclePaint = Paint()
			..strokeCap = StrokeCap.round
			..style = PaintingStyle.stroke
			..strokeWidth = 5;

		Paint smallCirclePaint = Paint()
			..style = PaintingStyle.fill;

		canvas.drawCircle(
				Offset(100, 0) + screenCenter,
				smallCircleRadius,
				smallCirclePaint);

		canvas.drawCircle(
				Offset(-100, 0) + screenCenter,
				smallCircleRadius,
				smallCirclePaint);
	}

	@override
	bool shouldRepaint(PickerPainter oldDelegate) => true;
}
```

![image](https://user-images.githubusercontent.com/47906325/53279532-0d9db100-36f0-11e9-8e56-e96b13ccd6e3.png)

## Sample drawing arc (only one circle being drawn)
```dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

void main()
=> runApp(MyApp());

class MyApp extends StatelessWidget
{

	@override
	Widget build(BuildContext context)
	{
		return MaterialApp(
			title: 'Flutter Demo',
			theme: ThemeData(
				primarySwatch: Colors.blue,
			),

			home: Scaffold(
					body: Center(
						child: CustomPaint(
							painter: PickerPainter(),
							size: Size(300, 300),
						),
					)
			),
		);
	}
}


class PickerPainter extends CustomPainter
{
	double smallCircleRadius = 10;
	double bigCircleRadius = 100;

	@override
	void paint(Canvas canvas, Size size)
	{
		Offset screenCenter = size.center(Offset.zero);
		
		Paint fractionCirclePaint = Paint()
			..strokeCap = StrokeCap.round
			..style = PaintingStyle.stroke
			..strokeWidth = 5;

		Paint smallCirclePaint = Paint()
			..style = PaintingStyle.fill;

    canvas.drawArc(
        Rect.fromCircle(center: screenCenter, radius: bigCircleRadius),
        0, math.pi, false, fractionCirclePaint);


		canvas.drawCircle(
				Offset(100, 0) + screenCenter,
				smallCircleRadius,
				smallCirclePaint);

		canvas.drawCircle(
				Offset(-100, 0) + screenCenter,
				smallCircleRadius,
				smallCirclePaint);
	}

	@override
	bool shouldRepaint(PickerPainter oldDelegate) => true;
}
```

![image](https://user-images.githubusercontent.com/47906325/53279524-f8288700-36ef-11e9-961d-9a5f0126462d.png)

**Comment by dnfield** [comment]
I'm not able to reproduce this on master.  Can you include the output of `flutter doctor -v`?

**Comment by MandelWarrior** [comment]
### flutter doctor -v:
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [VersiÃ³n 10.0.17134.590], locale es-AR)
    • Flutter version 1.0.0 at C:\Users\alan\Downloads\flutter_windows_v1.0.0-stable\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\alan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: G:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at G:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Redmi Note 4 • b374d7ab9904 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by dnfield** [comment]
Good news:

- This doesn't reproduce after 1.1.0

Bad news:

- It does reproduce on stable (1.0).

@MandelWarrior is it possible for you to upgrade to at least v1.1.0?  Alternatively you could consider using the latest beta channel.

@Hixie - what do we do about a bug like this?  Find the commit that fixed it and patch it into stable?

**Comment by dnfield** [comment]
It works as of at least 1.2.0.  There may be a 1.1.x version that it works in too, haven't bisected that far.

**Comment by MandelWarrior** [comment]
You're right, it works on beta.
Thanks for your help!

**Comment by Hixie** [comment]
@dnfield  If it's fixed on master, we close the issue.
