### ISSUE TITLE
start_up tests in our post-submit bots seem to become flaky

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#28374]
The flakiness seems to start from  after https://github.com/flutter/flutter/pull/27660

**Comment by xster** [comment]
LGTM

**Comment by liyuqian** [comment]
Some example logs:

https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9hNDRmMTc0ZWZjMjE4YWMxYjRiOTRiOWQ3N2RhZmRiNWRmZWExNDMyDAsSBFRhc2sYgICAgICA6AkM

https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9hNDRmMTc0ZWZjMjE4YWMxYjRiOTRiOWQ3N2RhZmRiNWRmZWExNDMyDAsSBFRhc2sYgICAgICA5AoM

**Comment by liyuqian** [comment]
Interestingly, the flaky start_up test after the shader warm up often triggers "(This is taking an unexpectedly long time)" for a very long time and it gives me a nice bug production to get a fix in https://github.com/flutter/flutter/pull/28477
