### ISSUE TITLE
Firebase Storage Download progress

### ISSUE THREAD

**Issue by ethael** [flutter/flutter#28389]
Hello,

file upload progress was implemented in version 1.0.3, but download progress is still missing. 
there is already a TODO in filrebase_storage.dart at line 146:

/// TODO: Move into own file and build out progress functionality

https://github.com/flutter/plugins/blob/master/packages/firebase_storage/lib/src/firebase_storage.dart

**Comment by ShadyBoshra2012** [comment]
Is there update for it ? 🤔

**Comment by IreshMM** [comment]
any update?

**Comment by kroikie** [comment]
@ethael

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/420. Any further collaboration will be done there.
