### ISSUE TITLE
iOS buildbot breakage related to lipo.py

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#2838]
The ios_sim_Release build is currently broken:
    https://build.chromium.org/p/client.flutter/builders/Mac%20Engine/builds/224/steps/build%20ios_sim_Release/logs/stdio

fatal error: /Applications/Xcode7.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /b/build/slave/Mac_Engine/build/src/out/ios_sim_Release/obj/sky/services/dynamic/libFlutterServices.a and /b/build/slave/Mac_Engine/build/src/out/ios_sim_Release/clang_x64/obj/sky/services/dynamic/libFlutterServices.a have the same architectures (x86_64) and can't be in the same fat output file

**Comment by Hixie** [comment]
This seems to be fixed now? (Waterfall is green.)

**Comment by chinmaygarde** [comment]
Yeah, this was fixed yesterday.
