### ISSUE TITLE
Feature request: choose download directory for flutter packages

### ISSUE THREAD

**Issue by Poohblah** [flutter/flutter#28382]
I'm developing on Linux.  I downloaded flutter through my distro's package manager, which installed flutter to `/opt`, which is normal practice on Linux.  Then I ran `flutter doctor`, which failed because it didn't have write permissions to the package cache directory:

```
FileSystemException: FileSystemException: Cannot open file, path = '/opt/flutter/bin/cache/flutter_version_check.stamp' (OS Error: Permission denied, errno = 13)
```

And then when running `flutter packages get`:

```
Creation failed, path = '/opt/flutter/.pub-cache/_temp' (OS Error: Permission denied, errno = 13)
```

As far as I can tell, there is no way to change the package cache/download directories.  The only way to fix this error is to adjust filesystem permissions.  There have been [several](https://github.com/flutter/flutter/issues/28210) [other](https://github.com/flutter/flutter/issues/26834) [issues](https://github.com/flutter/flutter/issues/24413) filed about this problem.

IMHO, this is not ideal practice.  Every other SDK/language-specific package manager that I am aware of - such as Anaconda's conda, Python's pip, Ruby's bundler, Ruby's gem, and so on - have a feature that allow the user to choose where to download packages.  Many package managers default to downloading packages to the user's home directory (regardless of where the SDK/language/package manager is installed), and some even default to downloading packages to the project directory (which IME is often best practice).  I believe flutter would greatly benefit from this feature as well.

**Comment by zoechi** [comment]
Flutter currently does not support being installed in a directory where the current user does not have write permissions.
This is a known limitation.

**Comment by Poohblah** [comment]
@zoechi  Yes.  I am aware of that.  I'm not asking about that.  I'm asking for a feature to change where packages downloaded with `flutter get` are installed.

**Comment by zoechi** [comment]
I got that. I don't think keeping an issue open for that fulfills a purpose though.
