### ISSUE TITLE
palette_generator block UI thread

### ISSUE THREAD

**Issue by KagurazakaHanabi** [flutter/flutter#28383]
When I select a color from the image, the UI is blocked.

![untitled.gif](https://i.loli.net/2019/02/23/5c70fa81ba045.gif)

```dart
PaletteGenerator.fromImageProvider(
  CachedNetworkImageProvider(url),
).then((generator) {
  Color color = generator.mutedColor.color;
  ThemeModel.of(context).theme = ThemeData(
    primaryColor: color,
    primaryColorDark: color,
    accentColor: color,
  );
});
```

flutter doctor -v

```
[√] Flutter (Channel master, v1.2.2-pre.43, on Microsoft Windows [Version 10.0.18277.1000], locale zh-CN)
    • Flutter version 1.2.2-pre.43 at D:\Flutter
    • Framework revision 5169ab5974 (2 days ago), 2019-02-21 09:27:07 +0100
    • Engine revision 6d7eb52185
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.4892.1

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\Yaerin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Comment by 2534290808** [comment]
The same thing happened to me

**Comment by Maistho** [comment]
I tried moving it into an isolate, but since it requires `dart:ui` it's not possible.

See https://github.com/flutter/flutter/issues/10647

**Comment by liaobushi520** [comment]
> I tried moving it into an isolate, but since it requires `dart:ui` it's not possible.
> 
> See #10647
Future<PaletteGenerator> exactColors(String imageURL) async {
  ///  very serious   *****
  // return await PaletteGenerator.fromImageProvider(NetworkImage(imageURL));

  
 ReceivePort receivePort = ReceivePort();
  await Isolate.spawn(entryPoint, receivePort.sendPort);
  SendPort sendPort = await receivePort.first;
  Uint8List bytes = await sendReceive(sendPort, imageURL);
  var image =
      (await (await ui.instantiateImageCodec(bytes)).getNextFrame()).image;
  return await PaletteGenerator.fromImage(image);
}

///you can add cache
if (paletteCache.containsKey(widget.song.cover)) {
      _paletteGenerator = paletteCache[widget.song.cover];
    } else {
      exactColors(widget.song.cover).then((v) {
        paletteCache[widget.song.cover] = v;
        setState(() {
          _paletteGenerator = v;
        });
      });
    }

demo : https://github.com/liaobushi520/fake_wechat/blob/master/lib/page/qqmusic/music_player_page.dart

hi ，maybe help you

**Comment by behnamsattar** [comment]
Same here, I'm experiencing a bad jank using pallete_generator.

**Comment by FelixMittermeier** [comment]
Over one year later and still no solution for the same problem :-(

**Comment by hacker1024** [comment]
@liaobushi520 Your code only downloads the image in a separate isolate which doesn't help as the calculations are still causing UI jank.

(It's also unnecessary, network requests do not block the UI.)

**Comment by hacker1024** [comment]
It's been a while, has there been any progress on this?

**Comment by rocboronat** [comment]
+1 ... 😢

**Comment by LiquidatorCoder** [comment]
One hack I found to improve palette loading times is by using ResizeImage along with CachedNetworkImageProvider.
```
final paletteGenerator = await PaletteGenerator.fromImageProvider(
        ResizeImage(
            CachedNetworkImageProvider(
              image,
            ),
            height: 10,
            width: 10),
      );
```
This drastically reduced UI block and sometimes it wasn't even noticeable in production.

**Comment by nt4f04uNd** [comment]
In the new version of the package new constructor was added `fromByteData`, which can be used in spawned isolates. Unfortunately, unless #10647 is resolved, there isn't anything better that can be used, other than this new constructor.

If you feel confused how you should use it, you can look at the internals of the `fromImageProvider`, which gets the `ui.Image`, then calls `fromImage`, which converts it to bytes, which then calls `fromByteData`. You should get the `EncodedImage` in the root isolate and then send it to spawned, where you would call to `fromByteData`.

We have considered an option to automatically spawn a new isolate within constructors, so you wouldn't need to be bothered to do this yourself, but because constructors involve `filters` which is a list of closures, they can't be passed to other isolates until https://github.com/dart-lang/sdk/issues/46623 is resolved
