### ISSUE TITLE
Flutter  iOS White Screen

### ISSUE THREAD

**Issue by MrReN** [flutter/flutter#28390]
Hi，
I use the iOS native code pushController flutter component, which will display the startup page or white screen.
How should I solve this problem?

 FlutterViewController* flutterViewController = [[FlutterViewController alloc] initWithProject:nil nibName:nil bundle:nil];
    [self.navigationController pushViewController:flutterViewController animated:YES];

**Comment by irwinOT** [comment]
> Hi，
> I use the iOS native code `pushController` flutter component, which will display the startup page or white screen.
> How should I solve this problem?
> 
> ```objc
>  FlutterViewController* flutterViewController = [[FlutterViewController alloc] initWithProject:nil nibName:nil bundle:nil];
>     [self.navigationController pushViewController:flutterViewController animated:YES];
> ```

Hey,
Could you solve it?
