### ISSUE TITLE
Will migrating flutter- android project to Android X when few dependecies are not yet migrated?

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#28393]
I have flutter project and now I want to migrate it to `android X` but few on my dependencies are not yet migrated to android X. **So Will migrating flutter- android project to Android X when few dependencies are not yet migrated cause any problems?**
Do I have to wait till they update the plugin or can I just migrate my flutter app?

**Comment by zoechi** [comment]
Basically yes, you have to wait.

https://github.com/flutter/flutter/issues/28207#issuecomment-465600796 seems to indicate that you can manually fix it though.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
