### ISSUE TITLE
Version solving failed due to dart SDK 

### ISSUE THREAD

**Issue by solanm3** [flutter/flutter#28396]
I'm trying to install the stripe_payment package when I use the most recent version (stripe_payment: 0.1.0) I get the following error

![stripe_pay0 0 9](https://user-images.githubusercontent.com/26803676/53288906-746da980-3786-11e9-8570-6306deacb577.JPG)

When trying to get stripe_payments(0.0.8) I get an unresolved reference error 

![stripe_pay0 0 8](https://user-images.githubusercontent.com/26803676/53288878-32dcfe80-3786-11e9-8a49-285cf16b3214.JPG)

Flutter Doctor

![flutterdoctor](https://user-images.githubusercontent.com/26803676/53289703-4e013b80-3791-11e9-8d83-ca69c1491e7a.JPG)

**Comment by jonahwilliams** [comment]
The version of the Dart SDK in the stable release of flutter is 2.1.0-dev.9.4 which is technically not >= 2.1.0. I do not know if it was the intention of the stripe_payment package to restrict usage of the package from the stable release, but it should be raised on https://github.com/jonasbark/flutter_stripe_payment.
