### ISSUE TITLE
video_player not always working on iOS

### ISSUE THREAD

**Issue by devansh-ramen** [flutter/flutter#28405]
## Steps to Reproduce

1. I have installed video_player plugin https://pub.dartlang.org/packages/video_player
2. Stream the following network link https://trafficwatch.myt.mu/terrerouge/terrerougeexch.stream/playlist.m3u8

3. The video takes around 20 seconds to start streaming. I can see a still image for first 20s, then the video plays fine. This only occur for some video urls. These are actually live streaming.

## Logs

```
```

```
Analyzing flutter_app_test...                                    
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.1.8 at /Users/devanshramen/flutter
    • Framework revision 985ccb6d14 (7 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)



```

**Comment by TahaTesser** [comment]
Hi @devansh-ramen 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
