### ISSUE TITLE
Calling setState() during build without user interaction

### ISSUE THREAD

**Issue by Khalilbz** [flutter/flutter#28407]
## Steps to Reproduce
1. Integrate FCM (Firebase Cloud Messaging) in the app.
2. Share the `context` and the `setState()` of each page in static variables with these two lines by calling them in all the build functions of all the pages :

>     @override
>     Widget build(BuildContext context) {
>         StaticClass.currentContext = context;
>         StaticClass.currentSetState = this.setState;
>         return ... ;
>     }

3. Create a callback to handle the coming notifications when the app is running

>     fcm.configure( onMessage: (){
>         StaticClass.currentSetState((){
>             Navigator.pushNamed(StaticClass.currentContext, "/notifications");
>       });
>     });

## Logs

```
I/flutter (31385): onMessage Fired
I/flutter (31385): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31385): The following assertion was thrown building MainPage(dirty, state: _MainPage#f9b84):
I/flutter (31385): setState() or markNeedsBuild() called during build.
I/flutter (31385): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (31385): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter (31385): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (31385): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (31385): Otherwise, the framework might not visit this widget during this build phase.
I/flutter (31385): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (31385):   Overlay-[LabeledGlobalKey<OverlayState>#78a15](state: OverlayState#54ba6(entries:
I/flutter (31385):   [OverlayEntry#a97c0(opaque: false; maintainState: false), OverlayEntry#bb499(opaque: false;
I/flutter (31385):   maintainState: true), OverlayEntry#267ab(opaque: true; maintainState: false),
I/flutter (31385):   OverlayEntry#cbb6e(opaque: false; maintainState: true), OverlayEntry#25923(opaque: false;
I/flutter (31385):   maintainState: false), OverlayEntry#8f9f9(opaque: false; maintainState: true),
I/flutter (31385):   OverlayEntry#ff888(opaque: false; maintainState: false), OverlayEntry#fb1a4(opaque: false;
I/flutter (31385):   maintainState: true)]))
I/flutter (31385): The widget which was currently being built when the offending call was made was:
I/flutter (31385):   MainPage(dirty, state: _MainPage#f9b84)
I/flutter (31385): 
I/flutter (31385): When the exception was thrown, this was the stack:
I/flutter (31385): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3485:11)
I/flutter (31385): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
I/flutter (31385): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
I/flutter (31385): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:301:5)
I/flutter (31385): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
I/flutter (31385): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:185:11)
I/flutter (31385): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:861:11)
I/flutter (31385): #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1560:11)
I/flutter (31385): #8      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:1473:12)
I/flutter (31385): #9      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:740:34)
I/flutter (31385): #10     _MainPage.build (package:mcom/Pages/HomePage.dart:32:17)
I/flutter (31385): #11     StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (31385): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (31385): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (31385): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (31385): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (31385): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (31385): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (31385): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (31385): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (31385): #20     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (31385): #21     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (31385): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
**Explanations :**

 - I can't update the page (by using context or calling setState()) when the framework is building
 - This problem doesn't happen when this function is called with a user interaction

**What I want :**

- Is there a way to repair my code or am I doing something wrong ?

**OR**

- Is there any other solution to go to another Page when onMessage() is triggered ?

**OR**

- Is there a way to know when the build function completes, to setState() without any problem ?

-------
Please Help I'm stuck here

**Comment by Khalilbz** [comment]
**Solution from [StackOverflow by (miguelpruivo):](https://stackoverflow.com/questions/54846280/calling-setstate-during-build-without-user-interaction)**

You can call `setState` after rendering is done by adding a post frame callback with [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) method. This will be called only **once** and after build process is done.  

    import 'package:flutter/scheduler.dart'
    
    SchedulerBinding.instance.addPostFrameCallback((_) => setState(() {}));

**Comment by jeeali** [comment]
> **Solution from [StackOverflow by (miguelpruivo):](https://stackoverflow.com/questions/54846280/calling-setstate-during-build-without-user-interaction)**
> 
> You can call `setState` after rendering is done by adding a post frame callback with [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) method. This will be called only **once** and after build process is done.
> 
> ```
> import 'package:flutter/scheduler.dart'
> 
> SchedulerBinding.instance.addPostFrameCallback((_) => setState(() {}));
> ```

This Worked for me.
Thank you @Khalilbz

**Comment by wslaimin** [comment]
> **Solution from [StackOverflow by (miguelpruivo):](https://stackoverflow.com/questions/54846280/calling-setstate-during-build-without-user-interaction)**
> 
> You can call `setState` after rendering is done by adding a post frame callback with [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) method. This will be called only **once** and after build process is done.
> 
> ```
> import 'package:flutter/scheduler.dart'
> 
> SchedulerBinding.instance.addPostFrameCallback((_) => setState(() {}));
> ```

thank you

**Comment by patelkrunal78** [comment]
Similar To [Is there any callback to tell me when “build” function is done in Flutter?](https://icetutor.com/question/is-there-any-callback-to-tell-me-when-build-function-is-done-in-flutter)

**Comment by PeterPoll** [comment]
@Khalilbz Hey! This doesn't work for me.. When I'm calling it and use setState.. the program never stops and running for ever..

Please if you have any suggestion please inform me :)
