### ISSUE TITLE
SharedPreferences on update an Android App from google play data lost

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#28421]
I've stored user settings in the SharedPreferences in my App, when I update the App via Google Play Store to a new version of the App data getting lost.

but if i store user settings in the SharedPreferences and then run google backup and then update the app via google play data getting restored and user setting updated in UI

why its only working if i do auto backup..

**Comment by PieterAelse** [comment]
According to https://developer.android.com/guide/topics/data/autobackup#BackupSchedule the auto backup runs the backup 

> when all of the following conditions are met:
> 
> - The user has enabled backup on the device. In Android 9, this setting is in Settings > System > Backup.
> - At least 24 hours have elapsed since the last backup.
> - The device is idle.
> - The device is connected to a Wi-Fi network (if the device user hasn't opted in to mobile-data backups).

So maybe the backup wasn't made yet?

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
Are you still experiencing this issue?
Thank you

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
