### ISSUE TITLE
cloud_functions 0.1.1+1 crashing iOS

### ISSUE THREAD

**Issue by blaneyneil** [flutter/flutter#28433]
this appears to be the same problem that these cloud_firestore PR's handle:

https://github.com/flutter/plugins/pull/1274
https://github.com/flutter/plugins/pull/1267 

once i revert to 0.1.0 then it's fine.

**Comment by blaneyneil** [comment]
correction - i have to revert to 0.0.5 for it to work on iOS.

**Comment by zoechi** [comment]
Can you please provide more details? 
`flutter doctor -v` output, error output, minimal reproduction, ...

**Comment by cyanglaz** [comment]
I did not see any static C functions in cloud_functions, the crash might not be related to [flutter/plugins#1274](https://github.com/flutter/plugins/pull/1274) and [flutter/plugins#1267](https://github.com/flutter/plugins/pull/1267).

**Comment by tomalabaster** [comment]
@blaneyneil have you tried updating to 0.9.5+2?

**Comment by blaneyneil** [comment]
on firestore, yes.  works perfectly.  on this, apologies for the delay - it was the production release build of iOS that it was affecting, and i can't test that out again until tomorrow.

**Comment by siyarcoder** [comment]
I upgraded flutter to 1.2.1

cloud_functions: ^0.1.1+1 doesn't work
cloud_functions: 0.1.0+1 working

**Comment by collinjackson** [comment]
Seems likely to be a regression in 0.1.1. I am investigating

**Comment by jacob-hutchings** [comment]
In CloudFunctionsPlugin.m line 44:
`if (region != nil)`
does not correctly detect [NSNull null]
maybe something like 
`if (region != nil && region != [NSNull null])`

**Comment by happyharis** [comment]
I don't know if it is related but I have a similar problem:
`error: no visible @interface for 'FIRFunctions' declares the selector 'callFunction:withObject:completion:'
        [functions callFunction:functionName`.
Anyone have an idea to fix this?

**Comment by kroikie** [comment]
@blaneyneil

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/417. Any further collaboration will be done there.
