### ISSUE TITLE
iPhone 12.1.4 - EXC_BAD_ACCESS latest flutter

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#28437]
App is constantly crashing when putting it in background on physical device.

No code change only flutter upgrade.

Flutter doctor -v
```
[✓] Flutter (Channel master, v1.2.3-pre.26, on Mac OS X 10.14 18A391, locale
    en-US)
    • Flutter version 1.2.3-pre.26 at /Users/anton/flutter
    • Framework revision 0e984fb237 (30 hours ago), 2019-02-23 10:08:53 -0800
    • Engine revision 0d777b947e
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)
```

Here is the xcode runtime error:
![screen shot 2019-02-24 at 7 08 30 pm](https://user-images.githubusercontent.com/7272343/53307537-a30f8100-3867-11e9-8b89-4bef9e5cb6b4.png)
![screen shot 2019-02-24 at 7 08 38 pm](https://user-images.githubusercontent.com/7272343/53307539-a4d94480-3867-11e9-86f2-92b77fe6ae50.png)

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the crash output as text.
Can you provide a minimal reproduction project that would allow us to reproduce?
