### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by skytz** [flutter/flutter#2844]
Not exactly an issue but a question.

Im working for a small dev company and we're talking about using flutter in production.
There is no deadline in the next 6 months.
Will it be an arm version by then?
And as a secondary question, will it be stable enough?

Thank you

**Comment by sethladd** [comment]
Thanks for reaching out! We'd love to hear more. In short, Flutter is in technology preview today, supports ARM today (majority of phones/tablets run ARM), and we don't have a timetable for "stable enough to run in production" release, unfortunately.

We'd love to know what features you'll need for your app.

Could you reach out to flutter-dev@googlegroups.com to discuss further?

Appreciate the interest!
