### ISSUE TITLE
Error 105 received from application: Isolate must be runnable

### ISSUE THREAD

**Issue by isfang** [flutter/flutter#28449]
This happened every time when I tried hot reload. This makes me very confused,  Is anyone can help me?

Here is the log

```
Waiting for a connection from Flutter on iPhone 6s...
Done.
Syncing files to device iPhone 6s...                         1.3s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone 6s is available at: http://127.0.0.1:57473/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                      ⣻Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: false, rootLibUri: file:///Users/dong/Library/Developer/CoreSimulator/Devices/37ED2873-6101-4E5B-9B73-859BBE38BBB7/data/Containers/Data/Application/F1D26F82-375A-436A-851B-A5A6933EA94E/tmp/flutter_modulebphYsB/flutter_module/lib/main.dart.incremental.dill, packagesUri: file:///Users/dong/Library/Developer/CoreSimulator/Devices/37ED2873-6101-4E5B-9B73-859BBE38BBB7/data/Containers/Data/Application/F1D26F82-375A-436A-851B-A5A6933EA94E/tmp/flutter_modulebphYsB/flutter_module/.packages, isolateId: isolates/1030413993}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment]
There was such an issue a while ago when there was no `main() {}` in the entry-point Dart file (`lib/main.dart`). 
Do you have the `main() {}` method at the beginning or the end of `lib/main.dart`?

**Comment by zoechi** [comment]
You could try switching to the `dev` channel
```
flutter channel dev
flutter doctor
```
and check if this still reproduces.

**Comment by isfang** [comment]
> Please add the output of `flutter doctor -v`.

Here is the doctor log
```
$ flutter doctor -v                                                                                                          
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale en-CN)
    • Flutter version 1.0.0 at /Users/dong/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/dong/Library/Android/sdk
    • Android NDK at /Users/dong/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by isfang** [comment]
> You could try switching to the `dev` channel
> 
> ```
> flutter channel dev
> flutter doctor
> ```
> and check if this still reproduces.

Thank you. I will have a try.

**Comment by isfang** [comment]
> > You could try switching to the `dev` channel
> > ```
> > flutter channel dev
> > flutter doctor
> > ```
> > and check if this still reproduces.
> 
> Thank you. I will have a try.

Sorry , I have not yet switching to `dev` channel , it’s working normally to restart the computer. I don't know what happed[Facepalm]

**Comment by zoechi** [comment]
Sounds like this is solved.

**Comment by Shafiwardak** [comment]
Hey, I have the same issue and it shows a blank page with the following error message: 
[VERBOSE-2:engine.cc(176)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(123)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterEngine.mm(294)] Could not launch engine with configuration.
Error 105 received from application: Isolate must be runnable

**Comment by testing2007** [comment]
I had encounter this issue recently, there was two FlutterViewController in my project and call registerPlugin, By vscode IDE, when you open the debug tab, which shows two main.dart Running , when i delete each FlutterViewController one of them, this error didn't happen again, I don't know if you are same question.

**Comment by HadiSDev** [comment]
@Shafiwardak I also have your issue. White page, and : 

E/flutter ( 8096): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: error: import of dart:mirrors with --enable-mirrors=false
E/flutter ( 8096): [ERROR:flutter/shell/common/engine.cc(175)] Could not prepare to run the isolate.
E/flutter ( 8096): [ERROR:flutter/shell/common/engine.cc(122)] Engine not prepare and launch isolate.
E/flutter ( 8096): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(167)] Could not 
launch engine in configuration.
Syncing files to device Android SDK built for x86...                    
 3,048ms (!)

�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press  
"R".
An Observatory debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:64458/s21oWyZ2dlU=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

Initializing hot reload...                                             |Error 105 received from application: Isolate must be runnable
Unhandled exception:
{code: 105, message: Isolate must be runnable, data: {request: {method: _reloadSources, params: {pause: false, rootLibUri: file:///data/user/0/com.hubly.hublyapp/code_cache/hubly_appBGYDHN/hubly_app/lib/main.dart.incremental.dill, packagesUri: file:///data/user/0/com.hubly.hublyapp/code_cache/hubly_appBGYDHN/hubly_app/.packages, isolateId: isolates/986896951}}, details: Isolate must be runnable before this request is made.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

**Comment by rtessler** [comment]
I had the same problem on a pc with android emulator. restarting visual studio seem to fix it.

**Comment by adityasharmaa** [comment]
> I had encounter this issue recently, there was two FlutterViewController in my project and call registerPlugin, By vscode IDE, when you open the debug tab, which shows two main.dart Running , when i delete each FlutterViewController one of them, this error didn't happen again, I don't know if you are same question.

@testing2007 where to find FlutterViewController in the project?

**Comment by AndrsDev** [comment]
I'm having the same issue!!! I've restarted my computer, cleaned the project... Everything and the error still happens on ios!
