### ISSUE TITLE
How to upgrade dark sdk?

### ISSUE THREAD

**Issue by wyxcoder** [flutter/flutter#28448]
The dart sdk included in flutter is 2.1.0-dev.9.4.flutter-f9ebf21297. A plugin stripe_payment need version 2.1.1, I tried to upgrade it but could not find a way. Any idea?

**Comment by zoechi** [comment]
The way to update the Flutter-included Dart SDK is to update Flutter.
There is no way to update the Dart SDK individually.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
