### ISSUE TITLE
My camera crash on release mode

### ISSUE THREAD

**Issue by fmmalta** [flutter/flutter#28453]
## Steps to Reproduce

I'm writing an application which makes use of the android's native camera (QR Code Scanner), so far so good, when I run flutter on debug mode, it works fine, no problem with that. But, when I try to open it on release mode, the app simply crash when I try to open the camera and I can't figure it out how to solve this.

**EDIT: This is not a camera plugin, I wrote it from scratch and calling from channel method**

I've this problem for at least 3 months now, I first solved this after a lot of headaches by creating a new flutter project and replace the original `lib` folder, `android` folder and `pubspec.yaml` with my old one, with the project itself. And now, I've tried the same solution but doesn't work anymore and I have to publish the app.

Here's my [Main Activity](https://gist.github.com/fmmalta/8d1c8db71dc86da10bba91e0c6da60ad) which the channels and permission

Here's my [Scan Activity](https://gist.github.com/fmmalta/d1c28fe44165572b305e6d0c7913f392) that loads the camera

## Logs

```
[  +16 ms] E/flutter ( 4581): [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)]
Could not make the context current
[   +1 ms] E/flutter ( 4581): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)]
EGL Error: EGL_BAD_ACCESS (12290)
```
That's the only logs referred to the camera which appears on the console

My `app/build.gradle`'s buildTypes:

```gradle
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            //minifyEnabled true
            //useProguard true
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

And my Flutter doctor -v: 

```
[✓] Flutter (Channel dev, v1.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.2 at /home/fellipe/Documents/Flutter
    • Framework revision 007a415c2a (3 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/fellipe/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/fellipe/Android/Sdk
    • Java binary at: /home/fellipe/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/fellipe/Documents/android-studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • Moto G 5 • 0032184578 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @fmmalta 
Since this isn't plugin issue as stated "EDIT: This is not a camera plugin, I wrote it from scratch and calling from channel method"
I am closing as such 
if you're still experiencing problem related, please create a new issue and provide the information required in the template.
Thank you

Thank you
