### ISSUE TITLE
Add SHA checksum for downloadable archives

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#28465]
When we generate downloadable archives, we should have a SHA checksum (probably SHA256) for each archive available for checking the validity of the archive.

This will involve adding code to the package generation script to generate the checksum, and then we'll need to generate a checksum for each package already stored on the storage server.

All the SHA values should be added to the releases JSON file, and the website will need to add code to display the checksum.

**Comment by zoechi** [comment]
Should this be moved to the flutter/website repo?

**Comment by gspencergoog** [comment]
No, it's mostly on the packaging script. We could open a separate website issue for adding the SHA display to the website, but I figured I'd wait to do that once the packaging script was doing what it needed to and the data was there to be displayed.
