### ISSUE TITLE
Background process when app is closed

### ISSUE THREAD

**Issue by theshivamlko** [flutter/flutter#28467]
I tried plugin 
flutter_background_fetch
and   android_alarm_manager: ^0.4.1+3
but background process is  not executing even app is opened,no error
I want to check API in background when app is closed, n show Notification when revcieve data,
How to work on Background process? any way without writing Native Code.
Any dart functionality for this?

**Comment by zoechi** [comment]
android_alarm_manager should allow you to do that. 
There is still ongoing work so it might not work perfectly in all situations yet.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
