### ISSUE TITLE
google maps flutter error

### ISSUE THREAD

**Issue by dvdghe** [flutter/flutter#28461]
when i use google_map_flutter i can't build my project correctly.
i use flutter clean command but nothing not changed.
error : 
*********************************************************
WARNING: This version of google_maps_flutter will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

**Comment by zoechi** [comment]
As the message says you need to switch to AndroidX.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by iOShuyang** [comment]
> 正如消息所示，您需要切换到AndroidX。
> 
> 请考虑在http://flutter.io/support列出的其他渠道中提出支持问题。
i have switch to AndroidX. but it not work

**Comment by ejulfaey** [comment]
Happened to me.
Just resolved this by migrate to AndroidX.
Follow the steps from here https://goo.gl/CP92wY
