### ISSUE TITLE
Unclear how to use --sample arg to `flutter create`

### ISSUE THREAD

**Issue by waded** [flutter/flutter#28474]
## Steps to Reproduce

1. Run `flutter create --help`
2. Read the bit about the -s/--sample arg. It suggests there are samples at http[s]://docs.flutter.io that can be pulled directly as starting points using this arg. Go look around at that URL to see if you can figure out what value you might use here. Try searching for "sample" there, but you don't find anything.
3. Not having found any information about how to use this, try `flutter create -s hello-world .` on a whim. This just results in:

```
Download failed.
URL: https://docs.flutter.io/snippets/hello-world.dart
Error: 404 Not Found
```

Googled a bit too. Did not find any good example of use of this arg.

Perhaps this is an obsolete rabbit hole of an argument that should be removed? Or, is there a more specific docs URL that could be used in --help to get new users directly to list of values that would work?

## Logs

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale en-US)
    • Flutter version 1.0.0 at C:\Users\wade\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
...
```

**Comment by goderbauer** [comment]
These samples are sprinkled thought the API docs. You can see one example when you switch to the "Sample in an app" tab on https://master-docs.flutter.io/flutter/widgets/SingleChildScrollView-class.html:

![image](https://user-images.githubusercontent.com/1227763/53380875-c3047a80-3923-11e9-81f6-853650b45c81.png)


@gspencergoog Should we maybe hide the --sample option from `flutter create --help`? On its own it may be confusing what you can do with it and it's probably only useful when you find the command via the docs page?

**Comment by waded** [comment]
I understand the use case now! Thanks for the example. I think it's a neat feature as long as users diving in CLI-first don't get mislead more often than it's used! You'll have to weigh judgement on that.

Another option may be to mention in `flutter create --help` a more specific docs URL as an example, as you did here, rather than the top level docs URL. That would've set me straight, anyway... rather than looking for some top level list of samples to start with, I would've seen the "Sample in an App" in this one case, then moved on w/ other CLI investigation.

**Comment by waded** [comment]
Thanks!
