### ISSUE TITLE
video player version 0.8.0 or higher not working with Android

### ISSUE THREAD

**Issue by rgoodwin16** [flutter/flutter#28476]
My team and I are working on an application and we were using the `0.7.2` version of the plugin and while it worked to play the video, the aspect ratio was not correct.  We then saw that version `0.9.0` fixes this issue and while it does on iOS, we are seeing issues with Android. When we tried running the `0.10.0+2` version, the app crashes saying:
```
ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.BootstrapMethodError: Exception from call site #68 bootstrap method
....
Caused by: java.lang.ClassCastException: Bootstrap method returned null
```

My flutter doctor says:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)
```
Other than downgrading back to 0.7.2, is there something that I'm missing?

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/25294#issuecomment-449044307 mentions the same exception

**Comment by TahaTesser** [comment]
Hi @rgoodwin16 
Are you still experiencing this issue with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
@rgoodwin16 
please follow up on https://github.com/flutter/flutter/issues/25294, closing as duplicate
