### ISSUE TITLE
Unnecessary Flutter / Dart code inteli-sense or suggestions when adding documentation or TODOs.

### ISSUE THREAD

**Issue by SV27** [flutter/flutter#28483]
Hi Team,

   Whenever I put a fullstop/period (.) in my code documentation or todo comments, android studio unnecessarily showing Dart code suggestions. It is very frustrating. I need to press escape key immediately after typing Period sign (.) every time.

Attached the screenshot for your reference. I was coding for a flutter application on Mac when taking this screen shot.

<img width="639" alt="android_studio_unnecessary_suggestion" src="https://user-images.githubusercontent.com/34560264/53381587-3c5d9680-393f-11e9-8838-71520045c530.png">

_Additional Notes:_ I reported this issue in Google Issues tracker for Android Studio. But, they asked me to report this in Flutter. Here is the Google issues tracker Link : https://issuetracker.google.com/125088418

**Comment by jonahwilliams** [comment]
cc @devoncarew

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3231](https://github.com/flutter/flutter-intellij/issues/3231) via [**ZenHub**](https://www.zenhub.com/)
