### ISSUE TITLE
Big images shown in small widgets reduce performance.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2848]
Maybe this is expected and I shouldn't put big images in small widgets but I'd expect the performance of showing the image would be relative to the size of the widget showing that image (if that widget is equal to or smaller than the image).

**Comment by abarth** [comment]
We can probably improve performance here by caching the resampled image at the lower resolution.

**Comment by eseidelGoogle** [comment]
This sounds like a simple perf win.  Pink doesn't know if this is affecting them, but probably is. :)

**Comment by mohith7548** [comment]
How to reduce the image size and store it as Thumbnail in Firebase Storage?? Please provide solution

**Comment by zoechi** [comment]
@mohith7548 please follow #26194
There are also suggestions out there how to use Firebase Cloud Functions to create thumbnails for Firebase Storage after upload.

**Comment by zoechi** [comment]
Similar #21571

**Comment by kf6gpe** [comment]
cc @iskakaushik does this get covered by your PR for caching widget size and image size?

**Comment by iskakaushik** [comment]
@kf6gpe , I'm working on this, the status is:

1. Engine side of the changes required for this have landed. https://github.com/flutter/engine/pull/8596
2. I've added benchmarks for us to track the performance.  https://github.com/flutter/flutter/pull/33814
3. I've staged a commit that addresses this issue, need to revive it https://github.com/flutter/flutter/pull/31164

**Comment by orestesgaolin** [comment]
Could you please give us another update on the issue? We sometimes have problems with showing multiple images and have to resize them to improve performance or even show images at all.

**Comment by iskakaushik** [comment]
cc: @GaryQian who landed a fix for this recently.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/42785 adds capability to specify how big to decode and cache images. You can now cache large images as much smaller resampled versions.

See the `cacheWidth` and `cacheHeight` parameters in `Image`.

**Comment by NayanBigscal** [comment]
5
