### ISSUE TITLE
iOS FLAVORS Issue when adding additional dependencies and fails to builds on iOS

### ISSUE THREAD

**Issue by natezhengbne** [flutter/flutter#28481]
I am following the [Creating flavors for Flutter](https://flutter.dev/docs/deployment/flavors)->[Flavoring Flutter](https://medium.com/@salvatoregiordanoo/flavoring-flutter-392aaa875f36) on iOS.
But building failed when just only adding a dependency like "sqflite: ^1.1.1" clone from [flutter_flavors](https://github.com/iakta/flutter_flavors).
The error message is "The sandbox is not in sync with the Podfile.lock".
I tried "pod reintegrate, pod install" but the issue still exist until remove the dependency.
My project is building well without any flavors support.

**Comment by natezhengbne** [comment]
same issue as [here](https://github.com/iakta/flutter_flavors/issues/3)

**Comment by zoechi** [comment]
Similar #19252 #1842 #15567 #14648

**Comment by natezhengbne** [comment]
[answer](https://github.com/iakta/flutter_flavors/issues/3#issuecomment-488104601)
