### ISSUE TITLE
update_dart_sdk.ps1:62 字符: 5

### ISSUE THREAD

**Issue by wangyankun33** [flutter/flutter#28486]
PS C:\Users\liqin> flutter
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine f7306394e303a210a9971acb60f9ba11d7c64ec8...
Downloading the Dart SDK using the BITS service failed, retrying with WebRequest...
Invoke-WebRequest : 请求被中止: 未能创建 SSL/TLS 安全通道。
所在位置 D:\flutter\bin\internal\update_dart_sdk.ps1:62 字符: 5
`+     Invoke-WebRequest -Uri $dartSdkUrl -OutFile $dartSdkZip`
`+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException`
`+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

Error: Unable to update Dart SDK. Retrying..

**Comment by chenglu** [comment]
Please follow this guide and set up the environment variables and then try it again, thanks!
https://flutter.dev/community/china
