### ISSUE TITLE
For ios, the textfield input field will be occluded

### ISSUE THREAD

**Issue by guoqn** [flutter/flutter#28488]
## Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/10399955/53385449-65bb0880-39b9-11e9-931c-3e11088254b2.png)

2. 
![image](https://user-images.githubusercontent.com/10399955/53385442-605dbe00-39b9-11e9-94d2-0de6a2fa0f0d.png)
3. my code
![image](https://user-images.githubusercontent.com/10399955/53385526-a286ff80-39b9-11e9-87dd-44d1ec672b6f.png)

## Logs

```
```

```
```

```
```

**Comment by xster** [comment]
Can you paste your `flutter doctor -v` output?

cc @GaryQian who looked at this recently.

**Comment by zoechi** [comment]
Looks like https://github.com/flutter/flutter/pull/26259
Switching to `dev` channel should fix that (`beta` channel as well).
```
flutter channel dev
flutter doctor
```
