### ISSUE TITLE
IndexedStack How to change index

### ISSUE THREAD

**Issue by ParryGao** [flutter/flutter#28492]
I find that the index attribute of IndexedStack is final and cannot be modified. How to change the index property to switch pages

**Comment by Kartik1607** [comment]
Just keep the index in state and use setstate.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.refresh),
        onPressed: () {
          setState(() {
            _currentIndex = (_currentIndex + 1) % 3;
          });
        },
      ),
      body: Center(
        child: IndexedStack(
          index: _currentIndex,
          children: <Widget>[
            Container(height: 100, width: 100, color: Colors.red),
            Container(height: 100, width: 100, color: Colors.green),
            Container(height: 100, width: 100, color: Colors.blue),
          ],
        ),
      ),
    );
  }
}
```

**Comment by ParryGao** [comment]
> Just keep the index in state and use setstate.
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   int _currentIndex = 0;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       floatingActionButton: FloatingActionButton(
>         child: Icon(Icons.refresh),
>         onPressed: () {
>           setState(() {
>             _currentIndex = (_currentIndex + 1) % 3;
>           });
>         },
>       ),
>       body: Center(
>         child: IndexedStack(
>           index: _currentIndex,
>           children: <Widget>[
>             Container(height: 100, width: 100, color: Colors.red),
>             Container(height: 100, width: 100, color: Colors.green),
>             Container(height: 100, width: 100, color: Colors.blue),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

It will show error: "Only static members can be accessed in initializers"

**Comment by Kartik1607** [comment]
> It will show error: "Only static members can be accessed in initializers"

Please post code which is throwing the error.

**Comment by zoechi** [comment]
> "Only static members can be accessed in initializers"

indicates that you reference the variable that you are trying to initialize, which is invalid in Dart.

```dart
class Foo {
  var bar = Button(Text('click me'), onPressed: () => onButtonPressed(bar)); // referencing `bar` here is invalid
}
```
You would need to change that to something like 
```dart
class Foo {
  Foo() { // this could also be done in `initState() { ... }` if `Foo` is a `StatefulWidget`
    bar = Button(Text('click me'), onPressed: () => onButtonPressed(bar));
  }
  var bar;
}
```

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
