### ISSUE TITLE
Error starting app while both emulator is running and real device is connected

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#285]
<a href="https://github.com/nalkon"><img src="https://avatars.githubusercontent.com/u/12300955?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nalkon](https://github.com/nalkon)**
_Saturday Nov 07, 2015 at 18:22 GMT_
_Originally opened as https://github.com/flutter/engine/issues/2011_

----

If you try to install flutter app (flutter start) while both Android emulator is running and real device is connected, you get an error:

Unable to run on Android.
Unable to run application - no connected devices.

OS: Ubuntu 14.04

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Saturday Nov 07, 2015 at 22:27 GMT_

----

I suspect @jason-simmons fixed this recently.  (At least he fixed a similar issue with multiple physical devices.)  We need to publish a new release with the fix.

**Comment by shalindalal** [comment]
Receiving following output when trying to run example stocks app on emulator
```
warning: Unexpected failure parsing device information from adb output:
emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
Please report a bug at http://flutter.io/
severe: Unable to run application - no connected devices.
```

**Comment by sethladd** [comment]
Closing because we've made a bunch of changes in the tools here. Please reopen if you notice something we can do better. Thanks for the report!
