### ISSUE TITLE
depends on shared_preferences >=0.4.0 which requires Flutter SDK version >=0.1.4 <2.0.0, version solving failed.

### ISSUE THREAD

**Issue by lsh1023** [flutter/flutter#28503]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by lsh1023** [comment]
depends on shared_preferences >=0.4.0 which requires Flutter SDK version >=0.1.4 <2.0.0, version solving failed.

**Comment by zoechi** [comment]
Try changing the dependency to `shared_preferences: ^5.0.0`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by lsh1023** [comment]
OK ,Thanks.
