### ISSUE TITLE
Android license status unknown

### ISSUE THREAD

**Issue by leapit** [flutter/flutter#28504]
The issue which closed can't sovle my problem [https://github.com/flutter/flutter/issues/22361](https://github.com/flutter/flutter/issues/22361)

My env,lastest mac os,the latest flutter,the latest android studio,and java 11,when i run `flutter doctor`,console
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G5019, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.31.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
and try with this `flutter doctor --android-licenses`,console

```
A newer version of the Android SDK is required. To update, run:
/Users/tam/Library/Android/sdk/tools/bin/sdkmanager --update
```
and try above command,console
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
    at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
    at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
    at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
    at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
    at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 5 more
```
after search stackoverflow,[https://stackoverflow.com/questions/47150410/failed-to-run-sdkmanager-list-android-sdk-with-java-9](https://stackoverflow.com/questions/47150410/failed-to-run-sdkmanager-list-android-sdk-with-java-9) try to modify sdkmanager with `DEFAULT_JVM_OPTS='"-Dcom.android.sdklib.toolsdir=$APP_HOME" -XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'`,and run command again,console

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found
```
and search this,return to[https://github.com/flutter/flutter/issues/22361](https://github.com/flutter/flutter/issues/22361)

but,after double checked and tried,can't solve my problem.

wait online for help

**Comment by zoechi** [comment]
See https://stackoverflow.com/questions/49758849/flutter-io-android-license-status-unknown

> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema

Indicates and issue with your Android SDK setup which is not maintained by Flutter.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by mycodingstudio** [comment]
<img width="980" alt="license error solution" src="https://user-images.githubusercontent.com/86642688/123735251-79504400-d8d1-11eb-935c-341adcf9c4c1.png">
My issue was resolved after installing Android SDK Command-line Tools on android studio sdk
