### ISSUE TITLE
Flutter too many GIFs cause the app to crash on startup

### ISSUE THREAD

**Issue by griboue** [flutter/flutter#28500]
I have developed a Flutter app with 18 GIFs on one page (welcome page) (about 1 Mb each GIF and a resolution of 600x600).

It works perfectly on all android devices (even with old smartphones).

Nonetheless my app crashes on start up on some IOS devices (iPad2 for example).

When I use "flutter run", the welcome page appears on my iPad2 but the gif slow down (drop framerate) and 2sec later the app shut down.

On the MAC, the last logs I have are the following:

"LaunchService: disconnect event received for service com.apple.lsd.advertisingidentifiers"
"LaunchService: disconnect event received for service com.apple.lsd.mapdb"
"Lost connection to device"
(sometime I also have a "memory warning" in the log just before the crash)

Hence, I was suspecting that my iPad was to old (only 512Mb DDR2) to display all the GIFs (especially because If I put only 1 GIF on the page, the app works (but still slow so it is weird)). However My app works fine on an iPhone 5s (emulator).

I am a bit lost and any help would be appreciated.

(My flutter doctor tells me that everything is ok)

**Comment by zoechi** [comment]
Have you tried with release builds on iOS devices?

Please add the output of `flutter doctor -v`.

Any chance you could publish a minimal reproduction project with such gif files that cause the crash?
