### ISSUE TITLE
Run flutter from Android Studio

### ISSUE THREAD

**Issue by ilyasdirin** [flutter/flutter#28516]
I can run flutter project from terminal but not from Android Studio.
Everything about Android environment is ok because I am actively developing Android Apps with Android Studio.
```
user-MacBook-Pro:first_app user$ $flutter run
Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                        
* Error running Gradle:
ProcessException: Process "/Users/user/Projects/Flutter/first_app/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /Users/user/Projects/Flutter/first_app/android/gradlew app:properties

Please review your Gradle project setup in the android/ folder.
```

**Comment by ilyasdirin** [comment]
This is the verbose log of the error


user-MacBook-Pro:first_app user$ $flutter --verbose run
[  +29 ms] executing: [/Users/user/Library/Flutter/sdk/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/user/Library/Flutter/sdk/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/user/Library/Flutter/sdk/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/user/Library/Flutter/sdk/flutter/] git log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/user/Library/Flutter/sdk/flutter/] git log -n 1 --pretty=format:%ar
[   +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[        ] executing: [/Users/user/Library/Flutter/sdk/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +7 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +253 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb devices -l
[  +12 ms] Exit code 0 from: /Users/user/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:1
[  +10 ms] executing: idevice_id -h
[  +32 ms] /usr/bin/xcrun simctl list --json devices
[ +542 ms] /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +34 ms] ro.hardware = ranchu
[  +18 ms] Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[ +861 ms] Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
[  +18 ms] Initializing gradle...
[   +6 ms] Using gradle from /Users/user/Projects/Flutter/first_app/android/gradlew.
[ +129 ms] executing: /usr/bin/defaults read /Applications/Android Studio Beta.app/Contents/Info CFBundleShortVersionString
[  +42 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio Beta.app/Contents/Info CFBundleShortVersionString
[        ] 3.3
[  +80 ms] executing: /Users/user/Projects/Flutter/first_app/android/gradlew -v
[ +625 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.14.3 x86_64
[        ] Initializing gradle... (completed)
[   +1 ms] Resolving dependencies...
[        ] executing: [/Users/user/Projects/Flutter/first_app/android/] /Users/user/Projects/Flutter/first_app/android/gradlew app:properties
[ +613 ms] 
                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
                    > Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 0s
[   +4 ms] Resolving dependencies... (completed)
[   +3 ms] * Error running Gradle:
           ProcessException: Process "/Users/user/Projects/Flutter/first_app/android/gradlew" exited abnormally:
           
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
           > Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 0s
             Command: /Users/user/Projects/Flutter/first_app/android/gradlew app:properties
           
[  +11 ms] "flutter run" took 3,250ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:87:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:81:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:96:23)
<asynchronous suspension>
#5      getApplicationPackageForPlatform (package:flutter_tools/src/application_package.dart:283:30)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:269:21)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:272:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:398:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#16     Future._complete (dart:async/future_impl.dart:476:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#27     Future._complete (dart:async/future_impl.dart:476:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by lucasnsa** [comment]
Hey, try provisionally exchanging version of gradle in build.gradle of app(version < 3.3.0)
>classpath 'com.android.tools.build:gradle:3.2.1'

**Comment by blasten** [comment]
We have updated to Gradle 5.6.  Please create a new project and try again.
