### ISSUE TITLE
Documentation / API for camera

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#28515]
Ref:
- https://stackoverflow.com/questions/51085201/how-to-access-camera-frames-in-flutter-quickly/54888943#54888943
- https://github.com/flutter/plugins/pull/965
- https://github.com/flutter/plugins/tree/master/packages/camera

**Comment by zoechi** [comment]
Looks like a duplicate of #26348

**Comment by truongsinh** [comment]
close as duplicate of #26348
