### ISSUE TITLE
google_sign_in: missing debug keystore config leads to error in emulator

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#28513]
I've encountered an emulator-only problem with `google_sign_in`.

I managed to resolve the issue, basically, there are some missing configurations in the default template about debug keystore.

So I'll just note the solution here and let you guys decide if this is a flutter issue.

# re-pro:

1. create a new app
2. import and config google_sign_in by following the docs
3. test the app in an AVD

# what would happen

```
Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 7: , null)
```

# how to resolve

add the following in `/android/app/build.gradle`

```
 android {
+    signingConfigs {
+        debug {
+            storeFile file('/Users/username/.android/debug.keystore')
+        }
+    }
```

**Comment by zoechi** [comment]
Interesting. This change doesn't seem necessary for others. 
Any idea why this could be special in your case?

**Comment by namiwang** [comment]
IDK, somehow my AVD doesn't load the default debug keystore?

BTW, I'm using CLI tools (sdkmanager/avdmanager) only (withoug android studio), maybe that's related.

**Comment by namiwang** [comment]
`com.google.android.gms.common.api.ApiException: 7` is a network issue. I am not sure this is actually related. I'm closing this for now.
