### ISSUE TITLE
TextField doesn't call onChanged when obscureText is true

### ISSUE THREAD

**Issue by RussellZornes** [flutter/flutter#28518]
## Steps to Reproduce
When you set `obscureText` to `true` on a `TextField` its `onChanged` callback is never called and nothing is rendered in the text field.

```dart
TextController controller = TextController();
TextField(
          controller: controller,
          obscureText: true, // <--- when true onChanged is not called. false works.
          onChanged: (text) => print(text),
        )
```
Expected:
`onChanged` should be called.

Results:
`onChanged` is not called.

Notes:
It works if you set `obscureText` to `false`.
This worked recently so its a regression.

## Version info
```
[√] Flutter (Channel dev, v1.2.2, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.2.2 at C:\dev\libraries\flutter2\flutter
    • Framework revision 007a415c2a (5 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\dev\libraries\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\dev\libraries\android-sdk
    • Java binary at: C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

• No issues found!
```

**Comment by goderbauer** [comment]
The following code works as expected and the callback fires on the latest master.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    TextEditingController controller = TextEditingController();
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextField(
          controller: controller,
          obscureText: true,
          onChanged: (text) => print(text),
        )
      ),
    );
  }
}
```

Can you post a fully runnable example where it doesn't work for you?

**Comment by RussellZornes** [comment]
OK this is weird. I pasted your code as is into a new flutter project and it doesn't work. I have to set the flag to false for it to work. I forgot to mention one piece of info. I am running this on the android emulator and typing with the keyboard. On an actual device it works fine.

With the flag set to false it works fine on emulator with keyboard. Very odd.

**Comment by zoechi** [comment]
> Framework revision 007a415c2a (5 days ago)

Can you please try with `master` channel? 
```
flutter channel master
flutter doctor
```

**Comment by RussellZornes** [comment]
Works on master.

[√] Flutter (Channel master, v1.2.3-pre.67, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.2.3-pre.67 at C:\dev\libraries\flutter2\flutter
    • Framework revision e50ebfc6fa (12 hours ago), 2019-02-26 19:25:35 -0800
    • Engine revision 113b91fe82
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 0f9a5198bd)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\dev\libraries\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\dev\libraries\android-sdk
    • Java binary at: C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

• No issues found!
