### ISSUE TITLE
Weird error being reported after updating to 1.2.1

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#28519]
I just updated to 1.2.1 and now everytime I hit CTRL + S on intellij, the **FIRST** time it gives this error:

![image](https://user-images.githubusercontent.com/1146982/53435171-f6eca800-39d6-11e9-896b-1b324754a426.png)

But after I click on any of those errors and it opens the target file, **immediatly after that** the erros goes away and I am able to hit CTRL + S a **SECOND TIME**. Then the apps hot reloads properly on the device. WTF?

If you check the error above you will realize that it points to line 1 of my code wich makes no sense, since there are onlye imports on that line.

Just for clarification, this is the top code on that file:

![image](https://user-images.githubusercontent.com/1146982/53435402-7aa69480-39d7-11e9-98b3-43fa194f3599.png)

If you need any more information please fell free to ask

**Comment by zoechi** [comment]
Try deleting ` ~/.dartServer/.analysis-driver/`

**Comment by maxlapides** [comment]
I'm having the same issue, with errors that look like this:

<img width="862" alt="screen shot 2019-02-26 at 11 44 07 pm" src="https://user-images.githubusercontent.com/1874682/53473882-78b4f380-3a20-11e9-87af-82a532d1dfb0.png">

```
❯ flutter doctor -v
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/maxlapides/flutter
    • Framework revision 8661d8aecd (12 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/maxlapides/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (2 available)
    • Max's iPhone • 65760f04a8cdf8dc55bf798b8cf0ab5cf488674c • ios • iOS 12.1.4
    • iPhone XS    • 9CFC4B23-BE03-4DC9-B1CD-5E1226F5A183     • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by maxlapides** [comment]
My temporary fix is to disable the offending rules:

```
analyzer:
  errors:
    const_constructor_param_type_mismatch: ignore
    const_constructor_field_type_mismatch: ignore
    variable_type_mismatch: ignore
```

This issue seems related to https://github.com/dart-lang/sdk/issues/36013 but I'm not totally sure.

**Comment by shinayser** [comment]
> Try deleting ` ~/.dartServer/.analysis-driver/`

Sorry I couldn't find this folder. Can you give more details from where it is located? I am on WINDOWS 10.

**Comment by jonahwilliams** [comment]
There are currently some issues with const evaluation and implicit double conversion. Defining it as `const Radius.circular(20.0)` should help.

**Comment by lukef** [comment]
@shinayser - it should probably be in `AppData\Local\.dartServer\.analysis-driver`

**Comment by maxlapides** [comment]
> My temporary fix is to disable the offending rules:
> 
> ```
> analyzer:
>   errors:
>     const_constructor_param_type_mismatch: ignore
>     const_constructor_field_type_mismatch: ignore
>     variable_type_mismatch: ignore
> ```
> This issue seems related to [dart-lang/sdk#36013](https://github.com/dart-lang/sdk/issues/36013) but I'm not totally sure.

Updated suggestion from me: don't disable those analyzer rules. Instead, I think it's better to use double literals (as recommended by @jonahwilliams) and ignore the `prefer_int_literals` lint rule on a case-by-case basis if you have it enabled. This will also make it easy to go back and replace these double literals with int literals once the analyzer bug is fixed. For example:

```
// ignore: prefer_int_literals
static const double defaultSize = 60.0;
```
