### ISSUE TITLE
Pointer*Event constructors are missing assertions

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#28539]
The Pointer*Event classes all have comments on their constructors that say:
```
/// All of the arguments must be non-null.
```

None of the constructors actually assert this though, as is common elsewhere in the Flutter codebase for comments like that.

**Comment by pedromassangocode** [comment]
Still valid for most of the classes at:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/events.dart

https://github.com/flutter/flutter/blob/cba91c97d03ac8aae66317097f9e8aeade86257f/packages/flutter/lib/src/gestures/events.dart#L897-L922

**Comment by darshankawar** [comment]
Still is the case using latest master version.

**Comment by stuartmorgan** [comment]
I don't think this is worth fixing at this point; Dart 3 will render this irrelevant since assertions like that will all be removed once null-safety is the only mode.
