### ISSUE TITLE
json_rpc_2 is swallowing vmservice's exceptions

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#28531]
See https://github.com/flutter/flutter/pull/28530 and https://github.com/flutter/flutter/issues/28374

The exceptions are currently swallowed in https://github.com/dart-lang/json_rpc_2/blob/master/lib/src/server.dart#L178

**Comment by dnfield** [comment]
json_rpc_2 v 2.1.0 has been published and should enable us to fail on these exceptions now (or at least print an error about them).
