### ISSUE TITLE
android logging is verbose

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2853]
From a customer report:

```
"W/ActivityManager: getTasks: caller 10208 does not hold GET_TASKS; limiting output"
```

We could filter the adb logcat output a bit more, to reduce noise to the user.

**Comment by Hixie** [comment]
Should we should ActivityManager at all?

FWIW, the ones I personally show are `AndroidHandler MojoMain MojoShellActivity MojoShellApplication flutter System.err libc DEBUG`

**Comment by devoncarew** [comment]
Good question; here's what we currently filter on:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L536

I'm not sure if `ActivityManager` was cargo-culted from somewhere else or if we aware of potential flutter issues that might surface on it (issue launching the android app?).
