### ISSUE TITLE
Separate change of font size of emojis within a Text / Textfield widget

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#28548]
Currently, it seems not possible to change the size of emojis within Flutter separately from the text size, when talking about user generated input where we can not pre-format via R
richtext (controller.text). This is especially problematic on iOS where emojis are very small. Also, they change the line break within a text input field on iOS.

So why not add a parameter to a Text / Textfield widget, which allows to change the font size of emojis separately from the text font size?

**Comment by GaryQian** [comment]
Related issue: https://github.com/flutter/flutter/issues/28894

Emojis are treated as being rendered as a separate font. Internally, there is no particular distinction between how we treat emojis vs regular glyphs. Thus, it is unlikely we would add a separate emoji scaling property, but if you wish, you can try to split emojis out and add them separately in a TextSpan with a different sized font.

I'm going to close this now, but happy to answer questions. We should fix the size disparity on iOS.
