### ISSUE TITLE
"flutter run && flutter logs" misses messages printed on startup

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2854]
e.g. try running a trivial app that compiles and runs and crashes really quickly, like "void main() { print('test'); }" or "void main();".

Run "flutter run && flutter logs --clear". You sometimes miss the message because we clear the logs after the message is shown.

**Comment by abarth** [comment]
Try without the `--clear`

flutter logs just shows the messages since it was started.  If we integrated it with run, we could set the start time for the logs to just before sending the intent to start the app.  As long as they're separate commands, we'll have a startup race.

**Comment by Hixie** [comment]
Ah, yeah, the clear is a distraction here.

**Comment by Hixie** [comment]
Obsolete now that run shows logs.
