### ISSUE TITLE
Attempt to invoke virtual method android.content.res.XmlResourceParser with image_picker

### ISSUE THREAD

**Issue by signshah** [flutter/flutter#28550]
## Steps to Reproduce

1. .Create new project
2. Add all the latest dependencies of firebase and `image_picker`
3. Try to select image either by camera or gallery

## Logs
```
Exception PlatformException(already_active, Image picker is already active, null)
```

**Comment by signshah** [comment]
I migrated to **AndroidX** and trying to use image_picker plugin. As and wen I try to open camera for the first time the application crashes and close.. after that every try it shows error PlatformException(already_active image picker is already active, null)

image_picker: ^0.5.0+3

Anybody faced this issue?

**Comment by devilishWei** [comment]
PlatformException (PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null))

**Comment by ovaldi** [comment]
+1

**Comment by Aricii** [comment]
+1

**Comment by cyanglaz** [comment]
@ovaldi @Aricii Could you please add a thumbs up emoji to the original post, it helps us to triage the issues and set the priorities. In general, the more thumbs up an issue has, the more we prioritize it.

**Comment by DuskMount** [comment]
+1

**Comment by DuskMount** [comment]
After I use "flutter clean" to delete the "build" folder, it works.

**Comment by cyanglaz** [comment]
Does @DuskMount 's suggestion work for everyone?

**Comment by lupming** [comment]
@DuskMount I have no effect.

**Comment by signshah** [comment]
@DuskMount Hey it looks like it got fixed for me as well. Now I am not seeing the issue.

**Comment by liu1023953303** [comment]
> After I use "flutter clean" to delete the "build" folder, it works.

It's word for me

**Comment by abdelhamid22** [comment]
> 
> 
> After I use "flutter clean" to delete the "build" folder, it works.

thanks, its work

**Comment by wslaimin** [comment]
+1
