### ISSUE TITLE
TextFormField loses focus in pages pushed to Navigator

### ISSUE THREAD

**Issue by williamdias** [flutter/flutter#28551]
As suggested by @zoechi in #9282, I am opening this issue to address the Form and GlobalKey problem I am facing.

I have a page which contains a `Form` with a `GlobalKey`. When this page is pushed to the `Navigator` and I try to click on the TextFormField, keyboard shows up and then immediately hides. I noticed that the problem only happens if the widget pushed to the navigator is a `StatelessWidget`. In my case, I was using a BLoC (from flutter_bloc package) to handle state so I used a `StatelessWidget`. Should I make this widget a `StatefulWidget` to prevent this issue? 

I came up with a possible solution when using a `StatelessWidget`, but I am not sure it's the right way to go. Instead of instantiating a new page each time, I declared the page as final variable in the beginning of my class.

```dart
final _mockPage = MockPage();

...

Navigator.push(context, MaterialPageRoute(builder: (context) => _mockPage));
```

Another thing I noticed is that the widget is recreated every time  the `TextFormField` is focused, but only if it has been pushed to the `Navigator`. I created a [repo](https://github.com/williamdias/flutter_textformfield_issue) to test these behaviours. My `PageMain` has a `Form` with a `GlobalKey`, but it's not recreated when the `TextFormField` gains focus. On the other hand, all the other pages, which are pushed to the `Navigator`, are recreated once the `TextFormField` is focused. Is this an expected behaviour? 

```
[✓] Flutter (Channel master, v1.2.3-pre.31, on Mac OS X 10.13.6 17G65, locale en-BR)
    • Flutter version 1.2.3-pre.31 at 
    • Framework revision 3423c831b9 (21 hours ago), 2019-02-24 21:48:50 +0100
    • Engine revision 0546e1e5e9
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by HansMuller** [comment]
Can you provide a small (smallish) complete sample app that demonstrates this problem?

**Comment by williamdias** [comment]
@HansMuller check this [repo](https://github.com/williamdias/flutter_textformfield_issue).

**Comment by HansMuller** [comment]
I was able to reproduce the "PageStateless" version of the problem with your code.

The original version of PageStateless created a different GlobalKey() for its Form each time it was constructed. When the Form gets the focus, the PageStateless widget is constructed again - along with its Form and a new Key. The new Form doesn't have the focus.

The lifetime GlobalKeys should correspond to the lifetime you want their widget's state to have. I updated your example with a stateful PageMain which creates the app's global keys: https://gist.github.com/HansMuller/7d616f5629640efcebad425387bd9e2a. Although the PageStateless widget is still constructed again when the PageStateless form gets the focus, the state of its Form is preserved because it still has the same key.

I have it on good authority that this video is an excellent introduction to keys in Flutter: https://www.youtube.com/watch?v=kn0EOS-ZiIc.

**Comment by williamdias** [comment]
Thanks for your reply @HansMuller. 

In my example, why does Flutter reconstruct PageStateless and PageStatefull when the Form gets the focus but doesn't do the same with PageMain when its Form gets the focus? Does it have to do with the page being pushed to the Navigator?

Is it a better approach to use PageStatefull or make PageMain stateful as you did?

**Comment by HansMuller** [comment]
Where you store a Form's key will probably depend on where you're going to need access to the Form's state. Typically it's easier to manage state like that higher up in the tree; passing it downwards to widgets that need it.

**Comment by williamdias** [comment]
Ok. What about the first question?

> In my example, why does Flutter reconstruct PageStateless and PageStatefull when the Form gets the focus but doesn't do the same with PageMain when its Form gets the focus? Does it have to do with the page being pushed to the Navigator?

**Comment by pedromassangocode** [comment]
Hi @williamdias 
Are you still facing this issue? if yes, then please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample and clear steps to reproduce the issue?
Thank you

**Comment by williamdias** [comment]
Hi @pedromassangocode 

It's been a while since opened this issue. As I'm not currently working with flutter, I did not have the chance to test if it is still present in newer releases. However, in my original post you can find `flutter doctor -v` output and a [repo](https://github.com/williamdias/flutter_textformfield_issue) with a reproducible code sample.

Feel free to close the issue if needed.

Thanks!

**Comment by pedromassangocode** [comment]
Hi @williamdias 
Can you confirm if the code shared on https://github.com/flutter/flutter/issues/28551#issuecomment-468487942 reproduces the issue?

**Comment by williamdias** [comment]
Hi @pedromassangocode 

Yes, it does.

**Comment by pedromassangocode** [comment]
Hi @williamdias 
I ran the code on https://github.com/flutter/flutter/issues/28551#issuecomment-468487942 using the latest `stable` channel and the keyboard did not closed automatically and the page is not recreated when the text field gains focus, so I can consider this issue as fixed.

For anyone facing the same issue, please fill a new issue providing the things in the issue template.
Thank you

<details><summary>Logs</summary>

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
I/flutter_exampl(29056): Not late-enabling -Xcheck:jni (already on)
I/flutter_exampl(29056): Unquickening 12 vdex files!
W/flutter_exampl(29056): Unexpected CPU variant for X86 using defaults: x86
W/flutter_exampl(29056): Verification of boolean io.flutter.embedding.engine.loader.ResourceExtractor$1.accept(java.io.File, java.lang.String) took 136.236ms (51.38 bytecodes/s) (800B approximate peak alloc)
W/flutter_exampl(29056): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_exampl(29056): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl(29056): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_exampl(29056): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Waiting for sdk gphone x86 arm to report its views...
Debug service listening on ws://127.0.0.1:58530/vAQvdpKeI8A=/ws
Syncing files to device sdk gphone x86 arm...
I/flutter (29056): -> PageMain created
I/flutter (29056): -> PageMain built
W/IInputConnectionWrapper(29056): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(29056): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(29056): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(29056): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(29056): endBatchEdit on inactive InputConnection
I/flutter (29056): -> PageStateless created
I/flutter (29056): -> PageStateless built
W/IInputConnectionWrapper(29056): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(29056): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(29056): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(29056): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(29056): setComposingRegion on inactive InputConnection
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision fba99f6cf9 (3 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>
