### ISSUE TITLE
Top and bottom margins on menus do not match OEM toolkit

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2856]
Not sure which is more spec-compliant, but here's what I see (flutter on the left, android on the right).

![screenshot_20160324-165604_png_and_screenshot_20160324-164859_png_and_screenshot_20160324-165117_png_and_screenshot_20160324-164852_png](https://cloud.githubusercontent.com/assets/5479/14034670/963c9b58-f1e2-11e5-9629-da0fbf4bf8fa.png)

Here's the spec: https://www.google.com/design/spec/components/menus.html#menus-specs

**Comment by sethladd** [comment]
@HansMuller it also appears that our shadow is darker (?)

**Comment by eseidelGoogle** [comment]
I think we'd need to have the exact same text to know, but it's also not clear if the font weight is identical.  The left one also looks slightly blurry as though the characters might not be pixel aligned.

**Comment by sethladd** [comment]
Agreed, we need to take new screenshots with the same words and fonts. I believe/guess the right-side is Roboto Condensed.

**Comment by sethladd** [comment]
I've updated the screenshot with the same words (though, I'm playing with font weights). Looks like our menu's top and bottom padding/margin is different. (e.g. more bottom padding under "Help")

**Comment by abarth** [comment]
It looks like we match the spec on the top but have too much space on the bottom:

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B_udO5B8pzrzdmJrQUk3aXd0RTg/components_menus_usage2.png

**Comment by abarth** [comment]
Marking as WONTFIX.  We're doing exactly what the spec says to the pixel:

https://www.google.com/design/spec/components/menus.html#menus-specs

The Java implementation is pretty far off-spect.  Not sure why the spec doesn't want to center the text in the item's rectangle, but it's pretty explicit about what it wants.

**Comment by sethladd** [comment]
Thanks a lot for double checking!
