### ISSUE TITLE
How to set sliver list view scroll direction ?

### ISSUE THREAD

**Issue by mazeediquantum** [flutter/flutter#28573]

**Comment by mazeediquantum** [comment]
Hi,
   I need the sliverlist view  in horizontal direction scroll. so please help me how to fix horizontal scroll in sliverlist ?

 SliverList(

              delegate: SliverChildListDelegate(
                  [
                  Column(

                    children: <Widget>[
                      Stack(
                        children: <Widget>[
                          Image.network("https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",fit: BoxFit.fill,),
                        ],
                      )
                    ],
                  ),
                  Column(
                    children: <Widget>[
                      Stack(
                        children: <Widget>[
                          Image.network("https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",fit: BoxFit.fill,),
                        ],
                      )
                    ],
                  ),
                  Column(
                    children: <Widget>[
                      Stack(
                        children: <Widget>[
                          Image.network("https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",fit: BoxFit.fill,),
                        ],
                      )
                    ],
                  ),
                ]
              ),
              )

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
