### ISSUE TITLE
Unable to start my flutter application in iOS simulator. 

### ISSUE THREAD

**Issue by amsmu** [flutter/flutter#28572]
I'm getting this error. I've already tried deleting, installing and updating pods.

```

Launching lib/main_dev.dart on iPhone XR in debug mode...
Xcode build done.                                            3.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET FBSDKLoginKit OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.m:201:29: error: use of undeclared identifier 'FBSDKAccessTokenDidChangeUserIDKey'; did you mean 'FBSDKAccessTokenDidChangeUserID'?
      if (notification.userInfo[FBSDKAccessTokenDidChangeUserIDKey] || notification.userInfo[FBSDKAccessTokenDidExpireKey]) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                FBSDKAccessTokenDidChangeUserID
    In file included from /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.m:21:
    In file included from /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:21:
    In file included from /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit.h:21:
    /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKAccessToken.h:61:35: note: 'FBSDKAccessTokenDidChangeUserID' declared here
    FOUNDATION_EXPORT NSString *const FBSDKAccessTokenDidChangeUserID;
                                      ^
    /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.m:201:90: error: use of undeclared identifier 'FBSDKAccessTokenDidExpireKey'; did you mean 'FBSDKAccessTokenDidExpire'?
      if (notification.userInfo[FBSDKAccessTokenDidChangeUserIDKey] || notification.userInfo[FBSDKAccessTokenDidExpireKey]) {
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                             FBSDKAccessTokenDidExpire
    In file included from /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.m:21:
    In file included from /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:21:
    In file included from /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit.h:21:
    /Users/amarjeetsinghmudhar/Development/klassroom-student-app/ios/Pods/Headers/Private/FBSDKCoreKit/FBSDKAccessToken.h:81:35: note: 'FBSDKAccessTokenDidExpire' declared here
    FOUNDATION_EXPORT NSString *const FBSDKAccessTokenDidExpire;
                                      ^
    2 errors generated.
Could not build the application for the simulator.
Error launching application on iPhone XR.


```

**Comment by zoechi** [comment]
What plugins are you using? 
Please add the output of `flutter doctor -v`.

**Comment by amsmu** [comment]
Plugins:   
rxdart: ^0.18.0
  json_annotation: ^2.0.0
  shared_preferences: ^0.4.3
  http: ^0.12.0
  flutter_facebook_login: ^1.2.0
  google_sign_in: ^4.0.1+1
  flutter_signin_button: ^0.2.5
  webview_flutter: ^0.3.3+1



Output of flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-IN)
    • Flutter version 1.2.1 at /Users/amarjeetsinghmudhar/Development/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/amarjeetsinghmudhar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone XR • 94C8CBB0-F33B-4219-B3EA-3025876454F8 • ios • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.

**Comment by dmvvilela** [comment]
I am having this problem too.. In xCode the FBSDKLoginKit is not compiling.. What can be done?

**Comment by juliengit2** [comment]
same issue for me

**Comment by VladyslavBondarenko** [comment]
It seems to be an issue with [flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login).
Even if no, I hope it's fixed already. The flutter version and plugins versions are outdated.
Could everyone who still has this problem please file a new issue with logs and the output of `flutter doctor -v` please.
