### ISSUE TITLE
problem in flutter Firebase messaging

### ISSUE THREAD

**Issue by aboda1986** [flutter/flutter#28581]
## Steps to Reproduce

`onLaunch` event always run when use `Navigator.of(context).pushReplacementNamed`

for example: when i sent notification and the app in background, and go to another screen and go back by using `pushReplacementNamed`, `onLaunch`  will run again

**Comment by aboda1986** [comment]
flutter doctor:

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

**Comment by aboda1986** [comment]
im using  firebase_messaging: ^4.0.0+1

**Comment by zoechi** [comment]
Can you please post a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by aboda1986** [comment]
this is simple code in one screen, you can try it with two screen, when push a new screen and call pushReplacementNamed to replace second screen with first, onLaunch call again!

@override
  void initState() {
    super.initState();
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
       
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
       
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
       
      },
    );


    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      print(token);
    });
  }
  
  
   @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Push Messaging Demo'),
        ),
		  body:Container(
		  
		  child:RaisedButton(
                  
                    onPressed: backToHome,
                   
                    child: Text(
                      'Reload me',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                          color: Colors.white,
                          fontSize: 18.0,
                          fontWeight: FontWeight.bold),
                    ))
		  
		  )
		
		
		
  }
  
  
  backToHome()
  {
       
//here when call pushReplacementNamed the screen reload and call onLaunch again!
// every click on Reload me button, onLaunch call again
            Navigator.of(context)
                .pushReplacementNamed('/me');

     
    
      
  }

**Comment by kroikie** [comment]
@aboda1986

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/410. Any further collaboration will be done there.
