### ISSUE TITLE
Clicking on one Push Notification on iOS opens multiple ones (FCM)

### ISSUE THREAD

**Issue by IsaNascimento** [flutter/flutter#28580]
## Steps to Reproduce
Receive multiple push notifications. 
User taps to open one notification.
onResume triggers for all notifications received and redirects to a specific page for each one. 
Once the user tries to return (back button) from a notification page, instead of going to home page, it goes to the other notification page. 
The user has to click on the back button for each notification page to return to the home page. 

Is this the expected behavior? I thought that onResume should be triggered only for the notification that the user tapped and not for each notification received. Or is the way I am implementing this wrong?

## Logs
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale pt-BR)
    • Flutter version 1.0.0 at /Users/isadora_maria/Downloads/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/isadora_maria/Library/Android/sdk
    • Android NDK at /Users/isadora_maria/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • Isadora • 7388be6c205ef382341a23c03c4a62834feb61ea • ios • iOS 12.1

• No issues found!
```

**Comment by kmusham** [comment]
We're also having the same issue. 
Is there a plan in place to fix the issue? Thanks.

**Comment by kroikie** [comment]
@IsaNascimento

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/411. Any further collaboration will be done there.
