### ISSUE TITLE
App showing messed up widgets -  flutter 1.2.1

### ISSUE THREAD

**Issue by ahasnaini** [flutter/flutter#28591]
![weirdbug](https://user-images.githubusercontent.com/7255590/53505609-1570a300-3aac-11e9-9f2f-a566ba1f66dc.png)

When I open the app, I see the above, widgets are messed up, when I touch the screen it fixes it self and works fine.
Initial thought was because I was google_map_flutter which is in preview, as when I was using that the entire screen would blink when switching to that screen, I removed the plugin and still have this issue.

Started soon after I started using 1.2.1 but can't be sure if that is the main culprit

Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.2.1 at /Users/asadali/Documents/flutter
    • Framework revision 8661d8aecd (13 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/asadali/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Users/asadali/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

**Comment by dnfield** [comment]
What platform is this happening on, Android or iOS?

Can you share a screenshot of what it looks like when it's right?  Are the messed up parts all text and images, or are there other things getting messed up that are not text or images?

**Comment by ahasnaini** [comment]
This was on iOS, I also have the bottom tab bar which was fine.
Sometimes it shows like the image or it turns the entire background block with widget still messed up but a bit less.

I am not sure if I can share the design, I removed io.flutter.embedded_views_preview from info.plist which I had due to google_maps_flutter. after that tried once or twice and didn't get the issue.

Will try again tomorrow. might just be google_maps_flutter causing the issue. If I don't see it again will close and wait for google_maps to get out of preview

**Comment by amirh** [comment]
The effect of just enabling the `embedded_views_preview` flag is that the engine is running with a single thread. @chinmaygarde might have further insight for how the single threaded configuration might be causing this?

**Comment by ahasnaini** [comment]
same as https://github.com/flutter/flutter/issues/27561

**Comment by dnfield** [comment]
Good catch.  I'm going to close this as a duplicate of #27561

**Comment by prabhuk56** [comment]
Still facing this issue in Flutter v1.5 for iOS.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.1)
[✓] Connected device (3 available)

• No issues found!

I am using google_maps, so I have included  io.flutter.embedded_views_preview in info.plist.
