### ISSUE TITLE
My flutter app cannot launch when I build for AdHoc Distribution

### ISSUE THREAD

**Issue by iyl2uw** [flutter/flutter#28596]
My application is a pure flutter app, it work well when I run it on Android Studio or Xcode, but when I build for AdHoc Distribution, it cannot launch with a white screen.

And occasionally I can encounter the error below, and I run it again the error will gone.

Runner[1379:732086] [VERBOSE-2:engine.cc(116)] Engine run configuration was invalid.
 Runner[1379:732086] [VERBOSE-2:FlutterEngine.mm(294)] Could not launch engine with configuration.
Runner[1379:732092] flutter: Observatory listening on http://127.0.0.1:58930/

`flutter analyze`  output:
Analyzing isss...                                                       

   info • Unused import: 'dart:ui' • lib/common/utils/deviceInfoUtils.dart:1:8 • unused_import
   info • The method '_generateDivider' isn't used • lib/detail/view/sampleDetail.dart:59:10 • unused_element
   info • The method '_generateItem' isn't used • lib/detail/view/sampleDetail.dart:67:10 • unused_element
   info • The method '_generateButton' isn't used • lib/detail/view/sampleDetail.dart:96:10 • unused_element
   info • The value of the local variable 'a' isn't used • lib/mappage/mapPage.dart:55:15 •
          unused_local_variable
   info • The function '_$SurveyStatusFromJson' isn't used • lib/repository/bean/survey.g.dart:360:14 •
          unused_element
   info • The function '_$SurveyStatusToJson' isn't used • lib/repository/bean/survey.g.dart:368:22 •
          unused_element
   info • The value of the field '_viewModel' isn't used • lib/samplepage/model/sampleModel.dart:9:30 •
          unused_field
   info • Unused import: 'package:isss/common/utils/logger.dart' •
          lib/samplepage/viewmodel/samplePageViewModel.dart:4:8 • unused_import

9 issues found. (ran in 2.8s)

`flutter doctor -v` output:
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/iyl2uw/flutter
    • Framework revision 8661d8aecd (13 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 26.0.2)
    • Android SDK at /Users/iyl2uw/Library/Android/sdk
    • Android NDK at /Users/iyl2uw/Library/Android/sdk/ndk-bundle
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /Users/iyl2uw/Library/Android/sdk/tools/bin/sdkmanager
        "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed
      instructions.
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

**Comment by g-balas** [comment]
How did you resolve this ?

**Comment by recvec** [comment]
> How did you resolve this ?

for me only release buid helps (flutter build ios --release)
