### ISSUE TITLE
Opening file '/data/data/org.domokit.sky.shell/dev.flx' failed

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#286]
<a href="https://github.com/josephburnett"><img src="https://avatars.githubusercontent.com/u/1103629?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josephburnett](https://github.com/josephburnett)**
_Monday Nov 09, 2015 at 07:06 GMT_
_Originally opened as https://github.com/flutter/engine/issues/2014_

----

When running `flutter start` I see this in the logs.  The app starts but it is just a black screen.

android: E/chromium: [ERROR:data_pipe_file_utils.cc(233)] Opening file '/data/data/org.domokit.sky.shell/dev.flx' failed in CopyFromFileHandler::OpenFile

Ubuntu 14.04 running in VMWare connected to a Samsung Galaxy SIII with Flutter 0.0.18

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Nov 10, 2015 at 15:46 GMT_

----

We've published a new version that should hopefully fix this issue.  The new version has different setup instructions, so you might need to run `pub global deactivate flutter` and follow the new instructions to get this working.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Nov 10, 2015 at 15:46 GMT_

----

http://flutter.io/getting-started/ has the new instructions.

**Comment by abarth** [comment]
This should be fixed now in the latest version.
