### ISSUE TITLE
android_alarm_manager should use exceptions instead of booleans

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#28600]
`AndroidAlarmManager`'s static methods return a `Future<bool>`. 

Wouldn't it be better for them to throw Exceptions (or Errors) when something is wrong?

And I have a question: are there any known cases where it may fail and return `false`?

**Comment by gabrc52** [comment]
For example, here if `handle == null`, it should throw an `Error` informing that `callback` is not a top-level or static function. 

```
final CallbackHandle handle = PluginUtilities.getCallbackHandle(callback);
if (handle == null) {
  return false;
}
```

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
