### ISSUE TITLE
Add better instructions for migrating to AndroidX

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#28601]
The previous Gradle/Android-specific breaking change had some nice instructions on migrating manually: https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1

I had some trouble migrating manually by following the instructions on the offical Android website since they are intended for experienced Android developers, and Android Studio uses a lot of RAM and tries to migrate plugins instead of upgrading them.

I did the migration by looking at https://github.com/flutter/plugins/commit/94f432f09820b680e93cbaee2abc6671b5a4030d

**Comment by gabrc52** [comment]
Something like this: https://medium.com/@gabrc52/how-to-migrate-your-flutter-app-to-androidx-1202ad43c8c8

**Comment by zoechi** [comment]
There is https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
You could make suggestions for improvement or a PR with suggested changes.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2452](https://github.com/flutter/website/issues/2452) via [**ZenHub**](https://www.zenhub.com/)
