### ISSUE TITLE
Cannot resolve symbol 'Binding' on Android project's file settings.gradle to add Flutter module

### ISSUE THREAD

**Issue by augustocadini** [flutter/flutter#28605]
I'm follow this tutorial to add a Flutter module to my Android project: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

The problem is to setup `settings.gradle` file, when I type the code, the `Binding` object isn't found, AndroidStudio let me some options of import, but nothing works.

```
setBinding(new Binding([gradle: this]))                                 // new
evaluate(new File(                                                      // new
  settingsDir.parentFile,                                               // new
  'my_flutter/.android/include_flutter.groovy'                          // new
))
```

![screen shot 2019-02-27 at 16 51 06](https://user-images.githubusercontent.com/18659348/53521328-9a60ba00-3ab6-11e9-9404-9bf98920c862.png)

**Comment by freshedgarT** [comment]
@augustocadini Have you tried ignoring the resolution error of the IDE and just going ahead with the gradle sync without importing anything? Seems to have worked for me.

**Comment by augustocadini** [comment]
> @augustocadini Have you tried ignoring the resolution error of the IDE and just going ahead with the gradle sync without importing anything? Seems to have worked for me.

Not works. With `Try again` or `Sync now` options, the result is the same.

**Comment by luoyushouchai** [comment]
@augustocadini  You miss a folder!
```
setBinding(new Binding([gradle: this]))                                 // new
evaluate(new File(                                                      // new
  settingsDir.parentFile,                                               // new
  '**YourProjectName**/my_flutter/.android/include_flutter.groovy'                          // new
))
```

**Comment by larrySmile02** [comment]
You need not resolve 。just leave it and click "Sync Now" and it will sync success. 
By the way , the class "Binding" comes from package groovy.lang; You need not import the package .

**Comment by 985211yyg** [comment]
> @augustocadini You miss a folder!
> 
> ```
> setBinding(new Binding([gradle: this]))                                 // new
> evaluate(new File(                                                      // new
>   settingsDir.parentFile,                                               // new
>   'YourProjectName/my_flutter/.android/include_flutter.groovy'                          // new
> ))
> ```
@luoyushouchai  which floder ?

**Comment by lingyfh** [comment]
'**YourProjectName**/my_flutter/.android/include_flutter.groovy' 

this path you need add YourProjectName before my_flutter

**Comment by wuyahui0124505** [comment]
@augustocadini Did you solved it？I have the same issue

**Comment by nishant-thite** [comment]
Did anyone try updating the `app/build.gradle`  with dataBinding? Solved my issue.

 `android { `

	dataBinding {
		enabled = true
	}
`} `

**Comment by blasten** [comment]
Make sure the host app is using Gradle 5.6 or greater and the Android Gradle plugin 3.5.0 or greater. We don't set `dataBinding` in the host app that the Flutter tool generates, so I suspect the version of Gradle/Android plugin may be the culprit. 

Please reopen if this is still an issue.

**Comment by lironiz** [comment]
running into the exact same issue...did anyone find the solution?
