### ISSUE TITLE
EdgeInsets constructor is annoyingly different than, say, Rect's constructor

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2860]
EdgeInserts.TRBL vs Rect.fromLTRB

**Comment by abarth** [comment]
Yeah, one is CSS convention and the other is Skia convention.  Which do you prefer?

**Comment by Hixie** [comment]
I think if forced to chose I would go with XY order, so LTRB.

The missing "from" also threw me, FWIW.
