### ISSUE TITLE
The video_player plugin flashes a white screen in video initialization.

### ISSUE THREAD

**Issue by jamiegau** [flutter/flutter#28613]
Coming of the bug fix of reliable playback of video player over days of playing 2min videos. #24565

One very annoying issues still exists.
When the next video initializes and loads..  The screen goes WHITE for a short time.
As a screen is typically BLACK, having a white flash is very annoying.

I tried baking in a BLACK Background etc, but this has no effect, and appears to be in the plugin itself in how it initializes the video container.

If possible, passing it a colour as the default colour it displays when in initialization would be best.  Or transparent would be even better.

The version in use are current against channel MASTER (master needed to fix #24565) as of the date I write this.   Or for more detail, check out #24565

**Comment by iapicca** [comment]
Hi @jamiegau 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
