### ISSUE TITLE
Provide a StadiumInputBorder

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28611]
If we want a rounded `TextFormField` we have to do something like:

```dart
border: OutlineInputBorder(borderRadius: BorderRadius.circular(100))
```

It would be nice to have a quick way to do it, like the `StadiumBorder` does it.

**Comment by Hixie** [comment]
This is something I would recommend providing as a package on pub. If we start providing every last possible shape in the core framework we'll be here forever. :-)

**Comment by feinstein** [comment]
I understand your point, but there's `StadiumBorder`	already for buttons, so I thought this would be a natural addition.
