### ISSUE TITLE
SliverFixedExtentList background color

### ISSUE THREAD

**Issue by maxlapides** [flutter/flutter#28615]
I'm trying to create a scrollable view where a section has a special background color. It would be nice if `SliverFixedExtentList` offered an easy way for me to do this. I could set the background color on each item individually, but then I sometimes end up with weird little colored lines in between each item in the color of the Scaffold background. To work around this right now, I've converted the `SliverFixedExtentList` into a `Container` wrapped in a `SliverToBoxAdapter` so I can apply the color on the `Container`.

**Comment by sergiofraile** [comment]
Another option is to wrap the CustomScrollView into a container and apply a color. Then set a transparent color to your items.

**Comment by Piinks** [comment]
I am going to close this to refer to https://github.com/flutter/flutter/issues/107498. The SliverDecoration widget is currently planned and will allow individual slivers to have a background color.
