### ISSUE TITLE
[LUCI] We should test packaging on master without uploading

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#28618]
Today we only run packaging on dev/beta/stable.  We should test it on master to make sure the script gets exercised.

/cc @gspencergoog

**Comment by godofredoc** [comment]
@christopherfujino is it possible to run the packaging script in dry-run mode?

**Comment by christopherfujino** [comment]
@dnfield what exactly would you like to catch? regressions in the script?

Sort of related:
 - https://github.com/flutter/flutter/issues/61751 (open)
 - https://github.com/flutter/flutter/issues/64209 (closed)

**Comment by christopherfujino** [comment]
Oh, I see that this was opened a while ago. My current plans are to migrate this script into the conductor, and then add integration tests there.

**Comment by godofredoc** [comment]
@christopherfujino can we close this issue now that we have the conductor tool ready?

**Comment by godofredoc** [comment]
\cc @sealesj this is related to the work being done with packages.
