### ISSUE TITLE
[webview_flutter][CookieManager] Provide a way to fetch cookies

### ISSUE THREAD

**Issue by fadhlisulaimi** [flutter/flutter#28617]
I have an app that fetches cookies when user login to a forum using webview, which I store locally and use it for authentication later on. I would like to know if you could bring this over to this plugin? Thanks!

**Comment by zoechi** [comment]
Cookies are just headers, you can read them from responses and pass them with requests.
Some frameworks provide special support for handling cookies. Dart does not out-of-the box. 
There might be packages on pub.dartlang.org that make that easier.
