### ISSUE TITLE
tiles_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#28616]
tiles_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis regressed around `dd23be3936272b974709222af1a8309ab65244cc` (engine roll, https://github.com/flutter/flutter/pull/28178).

cc @liyuqian @jason-simmons

**Comment by liyuqian** [comment]
It's an expected regression that trades off worst_frame_time (still in 16ms with high probability) with average_frame_time (most noticeably in home_scroll_perf__timeline_summary average_frame_rasterizer_time_millis. I rebased the 
tiles_scroll_perf__timeline_summary worst_frame_rasterizer_time_millis
