### ISSUE TITLE
i update to verison 1.2.1 find that i can't find Matrix4 class?

### ISSUE THREAD

**Issue by wtus** [flutter/flutter#28624]
how should i solve this?

![](http://ww1.sinaimg.cn/large/006rV8gJgy1g0lwril6esj30c0034a9w.jpg)

![](http://ww1.sinaimg.cn/large/006rV8gJgy1g0lwtb1rakj30fi041jr9.jpg)

in version 1.0.0,it works fine.

**Comment by jonahwilliams** [comment]
Hi @wtus, If you haven't reset your IDE after updating I would recommend trying that first. We haven't moved/removed Matrix4

**Comment by wtus** [comment]
@jonahwilliams thanks,i restart my computer, it's fine now.

**Comment by jonahwilliams** [comment]
Glad to hear it is resolved!
