### ISSUE TITLE
Notify widget or hold the build before fetching date from web service in StatelessPage

### ISSUE THREAD

**Issue by xlyasdasd** [flutter/flutter#28626]
Many thanks for reading. I have some StatefulWidget in a StatelessWidget. After fetching data from web service in StatelessPage, I need to notify every StatefulWidget that their state has been changed. Is there any functions to deal with this except setting the StatelessWidget to a StatefulWidget?

**Comment by jonahwilliams** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support.
