### ISSUE TITLE
Add (numeric) keyboard support for the TimePicker

### ISSUE THREAD

**Issue by robinbonnes** [flutter/flutter#28633]
We use the TimePicker a lot. It would be great if the Cupertino TimePicker could support numeric keyboard input to type a specific `HH:mm` time faster.

**Comment by jslavitz** [comment]
We're currently working on adding the ability to directly set the value of a time picker. (https://github.com/flutter/flutter/pull/27345). Would that be sufficient in solving this use case? (Requiring the developer to pull up a numpad, save the value, and send it to the picker).

**Comment by xster** [comment]
Is there an UIKit API or control you're referencing here?

**Comment by robinbonnes** [comment]
For example when setting your phones alarm clock. Unfortunately I can't do this with my phone, but many phones can. Here is an example:

![image](https://user-images.githubusercontent.com/5117166/53923431-9d404980-4078-11e9-8a23-7f45c11f4c24.png)

It would make selecting a time even faster.

**Comment by xster** [comment]
The Cupertino widget set is specifically meant to reproduce designs that can be accomplished on iOS devices via UIKit however. Is this an iOS feature?

**Comment by xster** [comment]
We're still not too clear about the spec on iOS that you'd like us to follow. We're going to close this bug for now. Feel free to open a new bug on this if there are Apple specs that we can reference for this issue.
