### ISSUE TITLE
Flutter command should be running as admin (Windows)

### ISSUE THREAD

**Issue by pr0ph0z** [flutter/flutter#28634]
Hi there.
This is not a bug that produce an errors anyway. This is just an odd event that happened to me.
First when I trying to install Flutter at 25 Feb (it's my first time), the flutter command was hanging. I don't have any idea. Today, i found an issue by @sandeepreddy-vinta at #11698. He mentioned about Permission, so i trying to open Command Prompt as Administrator, and it works.
Then i'm create a new project via Visual Studio Code, but again, the flutter command is hanging. I tried run the Visual Studio Code as Administrator, it's still hanging. So the solution is open the Command Prompt as Administrator again, and run the `flutter create` command.

![image](https://user-images.githubusercontent.com/17337978/53548664-a440f680-3b64-11e9-8130-ac0ceeb2e044.png)

EDIT:

I don't know if this is relate with the case i facing about, but there's no device selector as mentioned [here](https://flutter.dev/docs/get-started/test-drive?tab=vscode#create-app). So i must run (the `flutter devices` and `flutter run` command) it at Command Prompt as Administrator (again).

![image](https://user-images.githubusercontent.com/17337978/53549129-00584a80-3b66-11e9-87f5-bf383ccb7f2c.png)

**Comment by zoechi** [comment]
>  do not install Flutter in a directory like C:\Program Files\ 

I suspect you did not follow this advice from https://flutter.dev/docs/get-started/install/windows#get-the-flutter-sdk

Flutter needs to be installed in a directory where the current user has write permissions.

**Comment by pr0ph0z** [comment]
@zoechi I'm very sorry for my negligence. I thought the Flutter teams were recommend me to instal Flutter in C:\Program Files\.

**Comment by zoechi** [comment]
Duplicate of https://github.com/flutter/website/issues/1988
