### ISSUE TITLE
cloud_firestore setData crashes application.

### ISSUE THREAD

**Issue by abhi12299** [flutter/flutter#28642]
My pubspec.yaml file dependencies are as follows:

    dependencies:
      flutter:
        sdk: flutter
      google_sign_in: ^4.0.1+1
      scoped_model: ^1.0.1
      http: ^0.12.0+1
      shared_preferences: ^0.4.2
      rxdart: ^0.20.0
      file_picker: ^1.2.0
      flutter_pdf_viewer: ^0.2.0
      firebase_auth: ^0.8.1+4
      firebase_core: ^0.3.1+1
      firebase_messaging: ^4.0.0+1
      firebase_storage: ^2.1.0+1
      cloud_firestore: ^0.9.5+2
      cupertino_icons: ^0.1.2

Code that produces error:

    Future<bool> storeStudentData(Map<String, dynamic> data) async {
        String uid = authenticatedUser.id;

        DocumentReference docRef = db.collection('users').document(uid);

        try {

          await docRef.setData({
            'email': data['email'].toString(),
            'course': data['course'].toString(),
            'year': int.parse(data['year'].toString()),
            'semester': int.parse(data['semester'].toString()),
            'timestamp': FieldValue.serverTimestamp()
          });
      return true;
      } catch (err) {
        return false;
      }
    }

Error:
`[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: No virtual method set(Ljava/util/Map;)Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/firestore/DocumentReference; or its super classes (declaration of 'com.google.firebase.firestore.DocumentReference' appears in /data/app/com.example.rla_official-2/base.apk:classes2.dex)
E/flutter (28140):      at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:523)
E/flutter (28140):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter (28140):      at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/flutter (28140):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/flutter (28140):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (28140):      at android.os.MessageQueue.next(MessageQueue.java:328)
E/flutter (28140):      at android.os.Looper.loop(Looper.java:148)
E/flutter (28140):      at android.app.ActivityThread.main(ActivityThread.java:6339)
E/flutter (28140):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (28140):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
E/flutter (28140):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
E/flutter (28140):
F/flutter (28140): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
F/libc    (28140): Fatal signal 6 (SIGABRT), code -6 in tid 28140 (le.rla_official)
Lost connection to device.`

What should I do?

Additional: I have migrated my project to androidX.

**Comment by jul1u5** [comment]
I have this issue too. I have created a pull request with a possible solution: https://github.com/flutter/plugins/pull/1306. However, the CI fails to build.

**Comment by abhi12299** [comment]
What I did to work around this issue is that I made a cloud function (https.onRequest) and invoked it from my flutter app and from there I stored data in firestore using admin SDK.

**Comment by jul1u5** [comment]
This can be closed as https://github.com/flutter/plugins/pull/1306 has been merged.

**Comment by kroikie** [comment]
@abhi12299

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/405. Any further collaboration will be done there.
