### ISSUE TITLE
missing lines in coverage report flutter test --coverage

### ISSUE THREAD

**Issue by jonnytest1** [flutter/flutter#28643]
## Steps to Reproduce
     1. run flutter test --coverage
     2. open coverage/lcov.info
     3. observe missing lines( not just marked as 0 coverages )

## Logs

example file:

[Localization.dart.txt](https://github.com/flutter/flutter/files/2914818/Localization.dart.txt)

reported lcov.info part for file:

SF:lib\Localization.dart
DA:9,0
DA:16,0
DA:22,3
DA:23,3
DA:26,0
DA:27,0
DA:28,0
DA:29,0
DA:30,0
DA:34,0
DA:35,0
DA:36,0
DA:38,0
DA:40,0
DA:43,0
DA:47,0
DA:48,0
DA:52,0
DA:53,0
DA:55,0
DA:58,0
DA:70,1
DA:71,3
DA:73,2
DA:74,4
DA:76,6
DA:77,2
DA:78,4
DA:83,4
DA:87,4
DA:89,4
DA:90,12
DA:94,0
DA:95,0
DA:96,0
DA:100,0
LF:36
LH:13
end_of_record

converted as html for visualizing:
![2019-02-28 12_53_11-lcov - localization dart](https://user-images.githubusercontent.com/13507796/53564834-2b3ba200-3b58-11e9-9afc-74c20214b2f0.png)

Analyzing flutter_frontend...
No issues found! (ran in 11.4s)

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale de-DE)
    • Flutter version 1.0.0 at C:\Users\jonathan.heindl.BRAND-AD\Documents\flutter\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\jonathan.heindl.BRAND-AD\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\jonathan.heindl.BRAND-AD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by goderbauer** [comment]
This looks like a dup of https://github.com/flutter/flutter/issues/28542.
