### ISSUE TITLE
NoSuchMethodError: android.view.MotionEvent.isFromSource

### ISSUE THREAD

**Issue by KamilT** [flutter/flutter#28640]
## Steps to Reproduce

1. Run app on device with Android API 17
2. Tap on any place on the screen.

## Logs

E/MessageQueue-JNI( 3207): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI( 3207): java.lang.NoSuchMethodError: android.view.MotionEvent.isFromSource
E/MessageQueue-JNI( 3207): 	at io.flutter.view.FlutterView.onGenericMotionEvent(FlutterView.java:590)
E/MessageQueue-JNI( 3207): 	at android.view.View.dispatchGenericMotionEventInternal(View.java:7358)
E/MessageQueue-JNI( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7339)
E/MessageQueue-JNI( 3207): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
E/MessageQueue-JNI( 3207): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1488)
E/MessageQueue-JNI( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7329)
E/MessageQueue-JNI( 3207): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
E/MessageQueue-JNI( 3207): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1488)
E/MessageQueue-JNI( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7329)
E/MessageQueue-JNI( 3207): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
E/MessageQueue-JNI( 3207): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1488)
E/MessageQueue-JNI( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7329)
E/MessageQueue-JNI( 3207): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2171)
E/MessageQueue-JNI( 3207): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1453)
E/MessageQueue-JNI( 3207): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2464)
E/MessageQueue-JNI( 3207): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2125)
E/MessageQueue-JNI( 3207): 	at android.view.View.dispatchPointerEvent(View.java:7445)
E/MessageQueue-JNI( 3207): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3603)
E/MessageQueue-JNI( 3207): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3531)
E/MessageQueue-JNI( 3207): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4783)
E/MessageQueue-JNI( 3207): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4743)
E/MessageQueue-JNI( 3207): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4895)
E/MessageQueue-JNI( 3207): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
E/MessageQueue-JNI( 3207): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI( 3207): 	at android.os.MessageQueue.next(MessageQueue.java:128)
E/MessageQueue-JNI( 3207): 	at android.os.Looper.loop(Looper.java:151)
E/MessageQueue-JNI( 3207): 	at android.app.ActivityThread.main(ActivityThread.java:5400)
E/MessageQueue-JNI( 3207): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/MessageQueue-JNI( 3207): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/MessageQueue-JNI( 3207): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/MessageQueue-JNI( 3207): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
E/MessageQueue-JNI( 3207): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime( 3207): Shutting down VM
W/dalvikvm( 3207): threadid=1: thread exiting with uncaught exception (group=0x40f029a8)
E/AndroidRuntime( 3207): FATAL EXCEPTION: main
E/AndroidRuntime( 3207): java.lang.NoSuchMethodError: android.view.MotionEvent.isFromSource
E/AndroidRuntime( 3207): 	at io.flutter.view.FlutterView.onGenericMotionEvent(FlutterView.java:590)
E/AndroidRuntime( 3207): 	at android.view.View.dispatchGenericMotionEventInternal(View.java:7358)
E/AndroidRuntime( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7339)
E/AndroidRuntime( 3207): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
E/AndroidRuntime( 3207): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1488)
E/AndroidRuntime( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7329)
E/AndroidRuntime( 3207): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
E/AndroidRuntime( 3207): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1488)
E/AndroidRuntime( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7329)
E/AndroidRuntime( 3207): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
E/AndroidRuntime( 3207): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1488)
E/AndroidRuntime( 3207): 	at android.view.View.dispatchGenericMotionEvent(View.java:7329)
E/AndroidRuntime( 3207): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2171)
E/AndroidRuntime( 3207): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1453)
E/AndroidRuntime( 3207): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2464)
E/AndroidRuntime( 3207): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2125)
E/AndroidRuntime( 3207): 	at android.view.View.dispatchPointerEvent(View.java:7445)
E/AndroidRuntime( 3207): 	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3603)
E/AndroidRuntime( 3207): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3531)
E/AndroidRuntime( 3207): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4783)
E/AndroidRuntime( 3207): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4743)
E/AndroidRuntime( 3207): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4895)
E/AndroidRuntime( 3207): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
E/AndroidRuntime( 3207): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 3207): 	at android.os.MessageQueue.next(MessageQueue.java:128)
E/AndroidRuntime( 3207): 	at android.os.Looper.loop(Looper.java:151)
E/AndroidRuntime( 3207): 	at android.app.ActivityThread.main(ActivityThread.java:5400)
E/AndroidRuntime( 3207): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3207): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 3207): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/AndroidRuntime( 3207): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
E/AndroidRuntime( 3207): 	at dalvik.system.NativeStart.main(Native Method)

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.292], locale en-US)
    • Flutter version 1.2.1 at C:\dev\flutter
    • Framework revision 8661d8aecd (13 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kamil.toszek\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901

[!] VS Code (version 1.31.1)
    • VS Code at C:\Users\kamil.toszek\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • ONE TOUCH 4033X • 0123456789ABCDEF • android-arm • Android 4.2.2 (API 17)

! Doctor found issues in 3 categories.

**Comment by KamilT** [comment]
@gspencergoog Your change (based on git blame) from "Implement hover support for mouse pointers. #24830" is using Android API not existing on older devices, 

line 573: 
if (!event.isFromSource(InputDevice.SOURCE_CLASS_POINTER) ||

**Comment by gspencergoog** [comment]
Thank you for reporting this.  We're working on a fix.

**Comment by gspencergoog** [comment]
Reopening this until we get the engine rolled into the flutter repo.

**Comment by gspencergoog** [comment]
Reopening this (again) until we get the engine rolled into the flutter repo.

**Comment by gspencergoog** [comment]
This landed in flutter/flutter with the engine auto-roll at hash 778e95a39b82688662e8be7cbe2deb31cad33203
