### ISSUE TITLE
flutter test cannot test plugins

### ISSUE THREAD

**Issue by Rockvole** [flutter/flutter#28652]
I have written a unit test (in the test directory). It uses the <b>sqflite: ^1.1.1</b> library to run some database tests.
If I try to run the tests with :

    flutter run test/test_sqflite.dart

They run just fine, when I try to run them with :

    flutter test test/test_sqflite.dart

I just get a bunch of errors.

	Failed to load "/work/projects/flutter/rockvole_replicator_todo/test/test_sqflite.dart": MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

	package:flutter/src/services/platform_channel.dart 300:7  MethodChannel.invokeMethod
	===== asynchronous gap ===========================
	package:sqflite/src/sqflite_impl.dart 18:34               invokeMethod
	===== asynchronous gap ===========================
	package:sqflite/src/factory_impl.dart 33:7                SqfliteDatabaseFactoryImpl.invokeMethod
	package:sqflite/src/factory_mixin.dart 22:35              _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod.<fn>
	package:sqflite/src/exception_impl.dart 7:34              wrapDatabaseException
	===== asynchronous gap ===========================
	package:sqflite/src/factory_impl.dart 29:7                SqfliteDatabaseFactoryImpl.wrapDatabaseException
	package:sqflite/src/factory_mixin.dart 22:7               _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod
	package:sqflite/src/factory_mixin.dart 126:17             _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.getDatabasesPath
	===== asynchronous gap ===========================
	package:sqflite/sqflite.dart 162:54                       getDatabasesPath
	test/test_sqflite.dart 13:29                              main
	===== asynchronous gap ===========================
	package:test_api                                          RemoteListener.start
	/tmp/flutter_test_listener.JBLGNV/listener.dart 16:25     serializeSuite
	/tmp/flutter_test_listener.JBLGNV/listener.dart 42:27     main

**Comment by Rockvole** [comment]
Flutter 1.2.3-pre.69 • channel master • https://github.com/flutter/flutter.git
Framework • revision 90d090e366 (23 hours ago) • 2019-02-27 21:15:19 +0330
Engine • revision 113b91fe82
Tools • Dart 2.2.0 (build 2.2.0-dev.2.1 0f9a5198bd)

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by ride4sun** [comment]
I have ther same problem with firebase. I don't want to mock all firebase call instead I would like to setup a db just for testing purposes.

**Comment by stuartmorgan** [comment]
Since plugins are fundamentally a Flutter-level concept there's no way for them to work in Dart unit tests. This is documented now on https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests, along with strategies for handling it.
