### ISSUE TITLE
Flutter attach seems unreliable/intermittent

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#28654]
I think flutter attach works intermittently or unreliably or perhaps right now or something. I thought it was user error,but it definitely is not working right now.

Also - should you run flutter attach WHILE flutter view is running or right before your trigger the flutter view?  while it's running right?

either way, it gets stuck on the "Waiting for a connection from Flutter on Pixel 2..." screen

right now i can't get it to work at all within existing project.
        classpath 'com.android.tools.build:gradle:3.0.1'
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.2.1 at /flutter/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/neiljaywarner/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.4 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b22)
    • All Android licenses accepted.

    • Pixel 2 • FA7BS1A04165 • android-arm64 • Android 9 (API 28)

i will try to see if i can get more details later with fresh project, and/or emulator/iOS because I really want this to work :)

**Comment by jonahwilliams** [comment]
`flutter attach` on Android must be started before the flutter view is created. If you start it immediately after the flutter view is created or too soon before you will likely have a connection issue

**Comment by neiljaywarner** [comment]
My apologies. Error on my part. Thank you
