### ISSUE TITLE
flutter_driver does not support running a test on a pre-installed app

### ISSUE THREAD

**Issue by mmcc007** [flutter/flutter#28662]
This presents a problem in cases when you want to test for an app that saves data on device (like to a database) and this data is expected to be available after restarting the app. AFAIK, flutter_driver will always re-install the app which will generally clear the data saved by the app.

I went thru flutter_tools and wrote a script that handles this problem. It may be reasonable to consider integrating this feature into flutter_driver:
```
#!/usr/bin/env bash
# Originally written by Maurice McCabe <mmcc007@gmail.com>, but placed in the public domain.

# Run Flutter integration tests on android device (or emulator)

show_help() {
    printf "\n\nusage: $0 package test

Utility for running integration tests for pre-installed flutter app on android device.
(app must be built in debug mode with 'enableFlutterDriverExtension()')

where:
    package
        name of package to run, eg, com.example.flutterapp
    test
        path of test to run, eg, test_driver/main_test.dart
"
    exit 1
}

run_test() {
    # note: assumes debug apk installed on device
    package_name=$1
    test_path=$2

    echo Starting Flutter app $package_name in debug mode...

    # stop app on device
    # (if running locally or started incorrectly by CI/CD)
    adb shell am force-stop $package_name

    # clear log (to avoid picking up any earlier observatory announcements on local re-runs)
    # (could comment out if running in CI/CD)
    adb logcat -c

    # start app on device
    adb shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true $package_name/$package_name.MainActivity

    # wait for observatory startup on device and get port number
    obs_str=`adb logcat -e "Observatory listening on" -m 1`
    obs_port=`echo $obs_str | grep -Eo '([0-9]+)/$'`
    obs_port=${obs_port%?}
    echo Observatory on port $obs_port

    # forward a local port to observatory port on device
    forwarded_port=`adb forward tcp:0 tcp:$obs_port`
#    forwarded_port=4723 # re-use appium server port for now
#    adb forward tcp:$forwarded_port tcp:$obs_port
    echo Local port $forwarded_port forwarded to observatory port $obs_port

    # run test
    echo Running integration test $test_path on app $package_name ...
    pub get # may be required when running in CI/CD
    export VM_SERVICE_URL=http://127.0.0.1:$forwarded_port
    dart $test_path
#    flutter driver --use-existing-app=http://127.0.0.1:$forwarded_port --no-keep-app-running lib/main.dart

}

# if no arguments passed
if [[ -z $1  || -z $2 ]]; then show_help; fi

run_test $1 $2
```
Should be possible to do something similar for iOS, just haven't got it working yet...

**Comment by mmcc007** [comment]
Here is an example of it running:
```
./script/test_android.sh com.example.flutterapp test_driver/main_test.dart
Starting Flutter app com.example.flutterapp in debug mode...
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.flutterapp/.MainActivity (has extras) }
Observatory on port 39720
Local port 62829 forwarded to observatory port 39720
Running integration test test_driver/main_test.dart on app com.example.flutterapp ...
Resolving dependencies...
Got dependencies!
00:00 +0: end-to-end test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:62829
[trace] FlutterDriver: Isolate found with number: 834239778
[trace] FlutterDriver: Isolate is not paused. Assuming application is ready.
[info ] FlutterDriver: Connected to Flutter application.
00:00 +0: end-to-end test tap on the floating action button; verify counter
00:04 +1: end-to-end test (tearDownAll)
00:04 +1: All tests passed!
```

**Comment by mmcc007** [comment]
This is also useful for running integration tests in real devices in cloud such as AWS Device Farm

**Comment by Hixie** [comment]
We should be able to make `flutter drive` not blow away the data on the device (for example, this works fine with `flutter run`). We should also be able to make `flutter drive` work similarly to `flutter attach` so that it doesn't have to run the app.

**Comment by mmcc007** [comment]
@Hixie btw: I imagine most device farms, in particular AWS Device Farms, start-up an apk in the default manner. So, in my experience, the app has to be restarted to run with `flutter drive` (as shown in script). The same thing probably applies to apps running on iOS devices in device Farms.

FYI: here is a video of running `flutter drive` on AWS Device Farms using above script:
https://drive.google.com/file/d/0B3rPyH_-r9OwanJ0V2MzYjRtNzBodUdrN2tIaG5Na2lOS0JR/view?usp=sharing

**Comment by christopherfujino** [comment]
Fixed in [30818](https://github.com/flutter/flutter/pull/30818), you can now call `flutter drive --no-build` and it will use pre-built application if it exists, else it will build and install like before.

**Comment by mmcc007** [comment]
Thnx @christopherfujino... and @Hixie !
I will give it a shot.

**Comment by mmcc007** [comment]
I've been using the `--no-build` option on several iOS devices on AWS Device Farm using https://pub.dev/packages/sylph and it works great. 

However, for Android devices it has a dependency on the Android SDK to get the app id. This requires installing the Android SDK. For the environment on Device Farm this is a big inconvenience (eats into your billing and time waiting for test to finish). 

Instead I wrote a one-liner to grep for the app id in the gradle file and used a script to approximate what `--no-build` does. 

Might open an new issue for the Device Farm use case.

**Comment by stone20130104** [comment]
how to run a test on a pre-installed app on iOS, i can see the script is for android. is there the same solution for iOS?

**Comment by stone20130104** [comment]
there is the (flutter run --no-build --target="test_driver/app.dart" ) --no-build seems could start app without re-build the package, but actually it does build the app again.

**Comment by juanduarte1927** [comment]
Always that test finish sucessfully, the app is uninstalled... Is there some way to keep installed on the phone?
