### ISSUE TITLE
Change TabBar on scrolling ListView

### ISSUE THREAD

**Issue by orazz** [flutter/flutter#28664]
I have TabBar and TabView, separated ListView inside Tabview, GridView inside ListView and I want change my selected TabBar when scrolling ListView down to the next section, how can i achieve this?

```
return Scaffold(
      appBar:
      ...
      body:
      TabBarView(controller: tabController, children: <Widget>[
        ListView.separated(
          controller: _controller,
          separatorBuilder: (context, int index) {
            return Container(
              height: 50,
              color: Colors.cyan,
              child: Center(child: Text(index.toString(),
                style: TextStyle(color: Colors.white, fontSize: 18,),)),
            );
          },
          // shrinkWrap: true,
          itemBuilder: (BuildContext context, int index) {
            return GridView.count(
              shrinkWrap: true,
              crossAxisCount: 3,
              childAspectRatio: 2.0,
              physics: NeverScrollableScrollPhysics(),
              children:
              List.generate(6, (index) {
                return
                  Center(
                    child: RaisedButton(
                      onPressed: () {},
                      color: Colors.greenAccent,
                      child: Text(
                        '$index AM',
                      ),
                    ),
                  );
              }),
            );
          },
          itemCount: 8,
        ),
      ]),
    );
```

![simulator screen shot - iphone xr - 2019-02-28 at 13 53 33](https://user-images.githubusercontent.com/8214953/53595103-33c6c380-3bbe-11e9-879e-c7740ea79cd8.png)

**Comment by Hixie** [comment]
I recommend looking at CustomScrollView to do the grids+lists combination. GridView is itself scrollable, you don't really want to put it in a ListView. You lose all the benefits of the lazy loading.

That said, that isn't the issue here.

If I understand what you're saying correctly, the way to do it would be to not have a TabBarView, but instead watch the scrollPosition of the scroll view (via the scrollController), and update the tabController appropriately.

If that isn't clear, I recommend posting to StackOverflow or some other help forum.

**Comment by prismcloudalen** [comment]
is there any solution for achieving this?

**Comment by Hiteshc29** [comment]
> I have TabBar and TabView, separated ListView inside Tabview, GridView inside ListView and I want change my selected TabBar when scrolling ListView down to the next section, how can i achieve this?
> 
> ```
> return Scaffold(
>       appBar:
>       ...
>       body:
>       TabBarView(controller: tabController, children: <Widget>[
>         ListView.separated(
>           controller: _controller,
>           separatorBuilder: (context, int index) {
>             return Container(
>               height: 50,
>               color: Colors.cyan,
>               child: Center(child: Text(index.toString(),
>                 style: TextStyle(color: Colors.white, fontSize: 18,),)),
>             );
>           },
>           // shrinkWrap: true,
>           itemBuilder: (BuildContext context, int index) {
>             return GridView.count(
>               shrinkWrap: true,
>               crossAxisCount: 3,
>               childAspectRatio: 2.0,
>               physics: NeverScrollableScrollPhysics(),
>               children:
>               List.generate(6, (index) {
>                 return
>                   Center(
>                     child: RaisedButton(
>                       onPressed: () {},
>                       color: Colors.greenAccent,
>                       child: Text(
>                         '$index AM',
>                       ),
>                     ),
>                   );
>               }),
>             );
>           },
>           itemCount: 8,
>         ),
>       ]),
>     );
> ```
> 
> ![simulator screen shot - iphone xr - 2019-02-28 at 13 53 33](https://user-images.githubusercontent.com/8214953/53595103-33c6c380-3bbe-11e9-879e-c7740ea79cd8.png)

Try this package https://pub.dev/packages/scrollable_list_tabview. It is maybe exactly what you are looking for but it does not have smooth transitions between the tabs
