### ISSUE TITLE
Set backgroundColor Transparent for webview_flutter.

### ISSUE THREAD

**Issue by mlanteigne** [flutter/flutter#28674]
Hi, is it possible to set the backgroundColor of the webview window to be transparent? Thanks

**Comment by Hixie** [comment]
cc @amirh

**Comment by insinfo** [comment]
Is there a workaround for this issue?
To get a transparent background without your changes?

**Comment by mlanteigne** [comment]
@insinfo I had to use https://pub.dev/packages/flutter_webview_plugin. The problem with this one is that it's making a layer on top of your flutter app instead of being inside.
This might help: https://github.com/fluttercommunity/flutter_webview_plugin/issues/113

**Comment by deandreamatias** [comment]
This bug exists and is tracked here #29300 . There have a discussion about this and possible solutions.
Please close this problem if it is duplicated.
@mlanteigne @amirh

**Comment by stuartmorgan** [comment]
Closing as a duplicate.
