### ISSUE TITLE
uses-material-design should include/imply Roboto and Roboto Condensed

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2867]
If the flutter.yaml file as `uses-material-design: true`, this makes Roboto easily available. We should also make Roboto Condensed available.

**Comment by abarth** [comment]
It doesn't yet make Roboto available.  We'll need to add these it to the `_getMaterialFonts` function in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flx.dart#L41

**Comment by abarth** [comment]
For completeness, we need:

```
Roboto-Thin.ttf
Roboto-ThinItalic.ttf
Roboto-Light.ttf
Roboto-LightItalic.ttf
Roboto-Regular.ttf
Roboto-Italic.ttf
Roboto-Medium.ttf
Roboto-MediumItalic.ttf
Roboto-Black.ttf
Roboto-BlackItalic.ttf
Roboto-Bold.ttf
Roboto-BoldItalic.ttf
RobotoCondensed-Light.ttf
RobotoCondensed-LightItalic.ttf
RobotoCondensed-Regular.ttf
RobotoCondensed-Italic.ttf
RobotoCondensed-Bold.ttf
RobotoCondensed-BoldItalic.ttf
```

We'll also need to teach the custom font resolver about weights and styles so it can pick the right ttf file.  /cc @jason-simmons

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/2902
