### ISSUE TITLE
FutureBuilder + ListView.builder Reversed but on top

### ISSUE THREAD

**Issue by FlutterAddict** [flutter/flutter#28678]
This is my code:
```dart
  FutureBuilder(
    future: getItems(),
    builder: (BuildContext context, AsyncSnapshot snapshot) {
      switch (snapshot.connectionState) {
        case ConnectionState.none:
        case ConnectionState.waiting:
        case ConnectionState.active:
          return Center(child: CircularProgressIndicator());
        case ConnectionState.done:
          return ListView.builder(
            itemCount: snapshot.data.length,
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                title: Text(snapshot.data[index].title),
                subtitle: Text(snapshot.data[index].description),
              );
            },
          );
      }
    },
  ),
```

I want this to be reversed ListView, but not start from the bottom (that happens if I add reversed:true to ListView builder), but from the top - for example when I have only 2 items on list - it look like messeges on facebook messenger - items are on the bottom

I can't reverse the List because I have no list - data comes from the FutureBuilder and it doesnt have an option to stream reversed data.

What would you suggest?

**Comment by kudokk** [comment]
i suggest by primitive way

> title: Text(snapshot.data[index].title),
subtitle: Text(snapshot.data[index].description)

```
title: Text(snapshot.data[snapshot.data.length - index].title),
subtitle: Text(snapshot.data[snapshot.data.length - index].description)
```

**Comment by FlutterAddict** [comment]
Yeah that is a solution.

I solved it by modyfuing the query so it fetches results in reverse and it works too.

It would be cool if that property existed but it's not necessity so I'm closing.

**Comment by chankongching** [comment]
shld it be snapshot.data.length - index - 1 ??

**Comment by ipolx** [comment]
> shld it be snapshot.data.length - index - 1 ??

Yes. it should be index -1, i tested right now
