### ISSUE TITLE
Vertical dragging to select text

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#28676]
[This PR](https://github.com/flutter/flutter/pull/28290) adds support for text selection by dragging with a mouse. The current implementation only supports horizontal dragging since vertical dragging will most likely conflict with scrolling.

The solution is to make it so that scrolling is only triggered when initiated by touch events, and vertical text selection is only triggered by a mouse. No conflicts!

But with the current state of Flutter, we can't disable mouse-drag-to-scroll yet because there is no other way to scroll on desktop. Once wheel scrolling is fully implemented, we can revisit this.

- [x] wheel scroll.
- [x] scroll bars.
- [ ] disable drag-to-scroll when the device is a mouse.
- [ ] enable text selection by dragging in any direction.

**Comment by stuartmorgan** [comment]
Is there work remaining here?

**Comment by xxgreg** [comment]
I've run into a similar issue where I'd like to handle a vertical drag, but this isn't possible inside a Scrollable widget as far as I can tell.

One possible solution is to add an option to Scrollable to disable tap&drag scrolling. Two-finger trackpad and mouse-wheel scrolling would continue to work when this is set. 

My current use case is desktop only. But there's probably a more general solution here, which would set the Scrollable option automatically based on the current platform.

**Comment by timsneath** [comment]
Pinging @mdebbar to check whether this issue is still relevant?

**Comment by mdebbar** [comment]
@timsneath I added checkboxes in the issue description to clarify which parts are done and which ones are still missing.

**Comment by timsneath** [comment]
Great - thanks!

**Comment by mdebbar** [comment]
The only piece of work left here is tracked in: https://github.com/flutter/flutter/issues/71322

**Comment by kevlar700** [comment]
I don't feel this is right. Selecting text and dragging above the screen should cause scrolling and more selection?
