### ISSUE TITLE
Image Cache - Image Dimensions

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#28682]
One thing i noticed that the way we calculate image size is `height * width * 4`, which is correct given that on the engine side we decode images on `initCodec`, is there a reason to decode on `init` rather than decode when paint gets called?

The reason i bring this up is if we have 1 PNG of ~2MB it can decode to 78 MB, so even with 100MB limit the cache becomes unusable. As I understand it we moved the decoding to IO thread so GPU does is not blocked during paint. Is there a reason to not clip the image to screen dimensions?

cc: @Hixie , @chinmaygarde

**Comment by dnfield** [comment]
> is there a reason to decode on `init` rather than decode when paint gets called?

Decoding is slow.  Doing it during painting would slow down an operation that's supposed to be as fast as possible.

> Is there a reason to not clip the image to screen dimensions?

A user might be scaling the image to the size of the screen. If we clipped it, they couldn't do that.

**Comment by iskakaushik** [comment]
> A user might be scaling the image to the size of the screen. If we clipped it, they couldn't do that.

I meant downsampling the image the screen resolution. One scenario this would not account for is if the user tries to zoom-in on a portion of the image.

**Comment by jonahwilliams** [comment]
The problem with automatically downscaling, at least for network images, is that the user still pays the cost of downloading the large image and we still, depending on format, have to hold the full image in memory for a while anyway. It is better in many cases to reduce the image size.

Another approach would be for us to provide an API to do this similar to android, which attempted to only load part of the image into memory. https://github.com/flutter/flutter/issues/26194

**Comment by iskakaushik** [comment]
I ran an experiment with both `Asset` and `Network` images. 10 png files 2 MB each, no 2 images ever fit in the cache. [Docs](https://docs.flutter.io/flutter/painting/ImageCache-class.html) specify the cache as "Implements a least-recently-used cache of up to 1000 images, and up to 100 MB.", I think we should specify that it is 100MB decoded.

> The problem with automatically downscaling, at least for network images, is that the user still pays the cost of downloading the large image and we still, depending on format, have to hold the full image in memory for a while anyway. It is better in many cases to reduce the image size.

@jonahwilliams what are your thoughts on changing `ImageStreamCompleter load(T key);`  on `ImageProvider` to `ImageStreamCompleter load(T key, ImageConfiguration config);` and propagate the image size to the engine?

**Comment by jonahwilliams** [comment]
You can configure the cache size, but of course we only care about decoded size. It is an in-memory cache!

**Comment by iskakaushik** [comment]
Closing this thread:

1. ImageCache is primarily to only hold images in memory while widgets are being recreated/shuffled. It's not meant to be persistent.
2. Most of the issues to deal with high dimension images can be addressed with https://github.com/flutter/flutter/issues/26194.

**Comment by dnfield** [comment]
Do you think it'd be a good idea to create an API to help users with this?  E.g. wrapper around image that automatically downsamples it if it's large?

**Comment by iskakaushik** [comment]
@dnfield, me and @jonahwilliams were talking about this offline. It would be useful to potentially have a `DownsamplingImageProvider` that could wrap any `ImageProvider` and downsamples to the desired size. Skia has APIs to do this, we might need to add additional ones to `dart:ui`.
