### ISSUE TITLE
Support camera zoom feature

### ISSUE THREAD

**Issue by tungvn** [flutter/flutter#28694]
I am building an application with Flutter and use plugin camera as a key feature. Now everything works well, but I cannot see anything about the zoom feature of the plugin.
Now I can zoom the camera' preview on the application, but the photo is taken by the application cannot zoom as the preview.
Anything idea for this situation?

**Comment by naveenjujaray** [comment]
i'm looking forward for this feature

**Comment by mvanbeusekom** [comment]
The PR flutter/plugins#3315 containing support for zoom on Android and iOS just got merged to master. Closing this issue now.
