### ISSUE TITLE
Flutter Screen Navigation issue

### ISSUE THREAD

**Issue by sarvaiyajai** [flutter/flutter#28696]
Hello Guys

I have created one application using flutter. I an facing screen navigation stuck issue.
When i click on button and open new screen using below code
Navigator.push(
      context,
      new MaterialPageRoute(builder: (context) => ForgotPassword())

but when i click on first time screen are not loaded smoothly it stuck. When i click on second time it will work smooth. Same issue happened when i kill app and open it again.

Even i have created simple demo with one button and open new screen in this only one button still it is not work smooth. I have follow same instruction which is provided in flutter documentation. I am using flutter 1.0 version.

Can anyone help me on this?

**Comment by Hixie** [comment]
This should be fixed now with @liyuqian's shader warmup work.

**Comment by Hixie** [comment]
@sarvaiyajai please try again on the latest master build and let us know if you still see this problem!
Make sure you are testing with `--release` mode.
