### ISSUE TITLE
pluginization

### ISSUE THREAD

**Issue by sdgtwsf0115** [flutter/flutter#28691]
Does flutter support pluginization?How to do?

**Comment by dnfield** [comment]
Flutter has a rich plugin system - https://flutter.dev/docs/development/packages-and-plugins/developing-packages

I'm going to close this as it's not really a feature request or a bug report.

For general support questions like this, please consider using one of the other channels at https://flutter.dev/community.

**Comment by sdgtwsf0115** [comment]
I will pay attention later, thank you!
