### ISSUE TITLE
Disabling a button is non-obvious

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#287]
<a href="https://github.com/ianloic"><img src="https://avatars.githubusercontent.com/u/604?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ianloic](https://github.com/ianloic)**
_Monday Nov 09, 2015 at 20:35 GMT_
_Originally opened as https://github.com/flutter/engine/issues/2017_

----

It's not obvious from the API or docs that the way to disable a button is to pass a null onPressed. In retrospect it's kinds of obvious, but I ended up reading the source to work it out.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sethladd](https://github.com/sethladd)**
_Tuesday Nov 10, 2015 at 02:32 GMT_

----

Thanks for the feedback!

**Comment by abarth** [comment]
@alhaad ran into this issue too.  He wanted to set the color of the button, but it wasn't working because the button was disabled.

**Comment by Hixie** [comment]
We're going to try making onPressed @required. cc @pq.

**Comment by devxpy** [comment]
How to do this on-the-fly, like programatically?

trying to replicate [this](formDisabled) login form.

**Comment by feinstein** [comment]
I think this should be reopened.

Buttons should have a more clear way to be enabled/disabled, like a `isEnabled` flag (and also staying disabled if `onPressed` is null).

Here's my reasoning:

```
RaisedButton(
  child: Text('Register'),
  onPressed: (snapshot.hasData && snapshot.data == true)
    ? () {
      // launch the registration process
    }
    : null,
);
```

The `onPressed` parameter is hard to read, it's doing 2 roles at the same time: setting a callback function and controlling the enabled state. This is not only hard to read, but also not a good programming practice.

Doesn't this looks a lot more clean, clear and concise? 

```
RaisedButton(
  child: Text('Register'),
  onPressed: () {
      // launch the registration process
    }, 
  isEnabled: snapshot.hasData && snapshot.data, 
);
```

**Comment by hacker1024** [comment]
> ```dart
> RaisedButton(
>   child: Text('Register'),
>   onPressed: (snapshot.hasData && snapshot.data == true)
>     ? () {
>       // launch the registration process
>     }
>     : null,
> );
> ```
> 
> The `onPressed` parameter is hard to read, it's doing 2 roles at the same time: setting a callback function and controlling the enabled state. This is not only hard to read, but also not a good programming practice.

This is exactly what I'm doing to, in a `StreamBuilder`. It's not nice.

**Comment by feinstein** [comment]
@hixie @zoechi may I present a PR with the modifications I presented before?

**Comment by Hixie** [comment]
We would rather not have multiple ways to control if something is enabled. That said, you are welcome to create a package that provides alternative widgets that have the API you'd like.

**Comment by feinstein** [comment]
I don't think a simple change as a `isEnabled` justifies a whole package.

I honestly don't see much confusion on this. We are talking about only 2 ways of disabling a button (if we aim for a no-breaking change). 

Currently IMHO the whole "give it a null `onPressed` to disable" is a confusion on itself for many beginners (not mentioning readability issues), this would simplify things. Specially as creating a Button with a `null` `onPressed` is something almost no one desires when creating a Button, the goal of a Button is to have a `onPressed` delegate.

**Comment by Hixie** [comment]
We have to look at it holistically. It's not just this widget. If we aren't strict about it, we end up bloating the API across the board.

Packages are cheap. You should totally feel free to create a package. And hey, if it proves popular that would be a good way to signal to us that I'm wrong about this.

**Comment by feinstein** [comment]
I understand your point, it makes perfect sense, but if I create a package I would have to update it all the time with the latest releases of the Flutter Widgets. Also, I would have to make wrappers for all the current Widgets, which will be a lot more work than just adding a simple `isEnabled` here and there. So not wanting to sound selfish but this would be a lot of work on my side just to have a simpler API for a button, which I can't justify right now with my current schedule.

Would you mind if I create a new issue with my proposal, to see if it gathers support from the community (through 👍), instead of basing on package popularity? It has already 9 votes, but I think many people don't see it as it's lost in the middle of the original post.

**Comment by Hixie** [comment]
You are welcome to file a bug. I don't know if thumbs up will really help here though because people in general like features like this in theory and then report a general dissatisfaction with the platform, they don't realize that the dissatisfaction comes from the feature.

Re the package, I guess the difficulty would by adding constructor arguments when we add features to these widgets?

**Comment by feinstein** [comment]
Yes, and having to check at each new release of Flutter all the constructors to see if they changed at all.

**Comment by Hixie** [comment]
Might be worth filing a bug on the Dart SDK asking for a feature that would let you extend a class and add a constructor that forwards all the arguments from the superclass except those you explicitly override.

**Comment by feinstein** [comment]
I don't feel comfortable filling a feature request like this because I am kinda new to Dart, I don't feel confident enough to discuss this, as other advanced language topics might show up. Would you mind filling it yourself if you think it could be helpful and send me the link?

**Comment by Hixie** [comment]
https://github.com/dart-lang/sdk/issues/37736

**Comment by feinstein** [comment]
Thanks @hixie.

**Comment by patelkrunal78** [comment]
I think you may want to introduce some helper functions to build your button as well as a Stateful widget along with some property to key off of.

Use a StatefulWidget/State and create a variable to hold your condition (e.g. isButtonDisabled)
Set this to true initially (if that’s what you desire)
When rendering the button, don’t directly set the onPressed value to either null or some function onPressed: () {}
Instead, conditionally set it using a ternary or a helper function (example below)
Check the isButtonDisabled as part of this conditional and return either null or some function.
When the button is pressed (or whenever you want to disable the button) use setState(() => isButtonDisabled = true) to flip the conditional variable.
Flutter will call the build() method again with the new state and the button will be rendered with a null press handler and be disabled.
Here’s is some more context using the Flutter counter project

Find Code At [Here](https://icetutor.com/question/how-do-i-disable-a-button-in-flutter-2)
