### ISSUE TITLE
Slider thumb label is unreadable if accent color is bright and primary color is dark

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#28706]
Slider.label's docs say that the label is painted using ThemeData.accentTextTheme.body2, which appears to be correct (I didn't check), but unfortunately the thumb itself is painted using the primary color, which is not guaranteed to contrast well with the accentTextTheme.

I assume it's supposed to be using the primaryTextTheme? Or the thumb should use the accent color?

cc @HansMuller @gspencergoog

**Comment by HansMuller** [comment]
cc @clocksmith

**Comment by clocksmith** [comment]
Slider thumb color as primary is correct. Value indicator is also primary color, but the text should be onPrimary from the color scheme.

**Comment by clocksmith** [comment]
I am working on a few updates that are awaiting verification from design that will be done in a single breaking change (thumb size, thumb gap color, etc)
