### ISSUE TITLE
Feature Request: Nested Navigation within Tabs

### ISSUE THREAD

**Issue by kingsleykbc** [flutter/flutter#28716]
Hi @eseidelGoogle , navigation is really great and flexible in flutter. However, tab navigation isn't. You can't navigate within tabs (like many apps do). Only a few inefficient workarounds allow this. It would be great if we had nested navigation. Screens and/or routes that will render a widget within a parent widget. Something like this:
![whatsapp image 2019-03-01 at 11 10 30 am](https://user-images.githubusercontent.com/34620098/53631789-9e561e80-3c13-11e9-9a04-9cf7e8f7f288.jpeg)
that would work with named routes.

**Comment by eseidelGoogle** [comment]
Thank you for filing an issue. I believe this is already possible?  Cupertino for example uses a nested navigator pattern for something similar:
https://www.youtube.com/watch?v=3PdUaidHc-E

See nesting navigators:
https://docs.flutter.io/flutter/widgets/Navigator-class.html

Or did I mis-understand your request?

**Comment by kingsleykbc** [comment]
yh i guess that's it. my bad. Thanks
