### ISSUE TITLE
firebase Cloud 

### ISSUE THREAD

**Issue by matom666** [flutter/flutter#28711]
i could not link my flutter application with firebase Cloud 
i have installed the dependencies for the cloud firebase in pubspec 
and in android grade and this error is there i could not resolve it   

## Error

<!--
  my dart code is :

import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'package:flutter/material.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key, @required this.user}) : super(key: key);
  final FirebaseUser user;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          '${widget.user.email}',
        ),
        centerTitle: true,
      ),
      body: StreamBuilder<DocumentSnapshot>(
        stream: Firestore.instance
            .collection('users')
            .document(widget.user.uid)
            .snapshots(),
        builder: (BuildContext context,AsyncSnapshot<DocumentSnapshot> snapshot){
          if(snapshot.hasError){
            return Text('Error: ${snapshot.error}');
          }
          switch(snapshot.connectionState){
            case ConnectionState.waiting : return Text('Loading ... ');
            default:
              return Text(snapshot.data['name']);

          }
        },
      ),
    );
  }
}

**Comment by matom666** [comment]
Launching lib\main.dart on DUB LX1 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:checkDebugClasspath' property 'compileClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Telthem89** [comment]
Launching lib/main.dart on SM G3556D in debug mode...
Initializing gradle...                                              9.3s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\Telthem\Desktop\telthem\vtsapp\android\gradlew.bat" exited abnormally:

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :firebase_auth

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterE                                                                              valuate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_auth'.
> Could not resolve all artifacts for configuration ':firebase_auth:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.3.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.1/bui                                                                              lder-3.3.1.jar'.
         > Read timed out
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.3.20)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.20/kotlin-ref                                                                              lect-1.3.20.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.20/kotlin-reflect-1                                                                              .3.20.jar'.
            > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Ru                                                                              n with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 27s
  Command: C:\Users\Telthem\Desktop\telthem\vtsapp\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.

Telthem@Telthem MINGW64 ~/Desktop/telthem/vtsapp
$ ^C

Telthem@Telthem MINGW64 ~/Desktop/telthem/vtsapp
$


Same issue

**Comment by matom666** [comment]
I solved mine, 
By trying other Firebase_auth edition and cloud_firebase edition, then I got other error which was Enabling multi dex 
If some one got the exact the same error contact me and I will help him to solve it. 
Regards
