### ISSUE TITLE
Unable to maintain zoom on Transform.scale widget

### ISSUE THREAD

**Issue by callumclift** [flutter/flutter#28717]
I'm trying to build some zoom functionality into the flutter camera package for my app. Currently I am able to use the zoom feature by wrapping the CameraPreview widget in a Transform.scale and a GestureDetector. However whenever I am zooming in it is not maintaining the zoom. Currently it is snapping back to 1.0 scale when letting go after pinching and zooming.

Is there something I am doing wrong here? I am able to maintain the scale using the onDoubleTap function but not using the onScaleUpdate function.

Here is my code:

````
ClipRect(
                    child: AspectRatio(
                      aspectRatio: controller.value.aspectRatio,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        return GestureDetector(
                          onDoubleTap: () {
                            setState(() {
                              scale = 4.0;
                            });
                          },
                          onScaleUpdate: (ScaleUpdateDetails details) {
                            print(details.scale);

                            setState(() {
                              scale = details.scale;
                            });
                          },
                          child: Transform.scale(
                            scale: scale,
                            child: AspectRatio(
                              aspectRatio: controller.value.aspectRatio,
                              child: CameraPreview(controller),
                            ),
                          ),
                        );
                      }),
                    ),
                  )
````

**Comment by Hixie** [comment]
I recommend asking on a help site like stackoverflow or in our gitter channel.

When you filed this bug, did you end up going through https://github.com/flutter/flutter/issues/new/choose? If not, do you know where you followed a link to file a bug?
