### ISSUE TITLE
 Cannot reuse a MaterialPageRoute<dynamic> after disposing it.

### ISSUE THREAD

**Issue by hl198181** [flutter/flutter#28718]
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
flutter: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 217 pos 12:
flutter: '!_transitionCompleter.isCompleted'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute.didPopNext 
package:flutter/…/widgets/routes.dart:217
flutter: #3      NavigatorState.pop 
package:flutter/…/widgets/navigator.dart:1944
flutter: #4      _CupertinoBackGestureController._handleStatusChanged 
package:flutter/…/cupertino/route.dart:655
flutter: #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners 
package:flutter/…/animation/listener_helpers.dart:192
flutter: #6      AnimationController._checkStatusChanged 
package:flutter/…/animation/animation_controller.dart:736
flutter: #7      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:752
flutter: #8      Ticker._tick 
package:flutter/…/scheduler/ticker.dart:228
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:988
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:904
flutter: #11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame 
package:flutter/…/scheduler/binding.dart:902
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame 
package:flutter/…/scheduler/binding.dart:832
flutter: #17     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #18     _beginFrame (dart:ui/hooks.dart:162:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#68348(⏮ 0.000; paused; DISPOSED; for MaterialPageRoute<dynamic>(null))
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by YangCheung** [comment]
https://github.com/flutter/flutter/issues/27334

**Comment by xster** [comment]
This is fixed on head in #28756.
