### ISSUE TITLE
Dart 2 Incompatible issue with orderable_stack 0.1.3

### ISSUE THREAD

**Issue by Laxman007** [flutter/flutter#28710]
pubspec.yaml

name: orderable_stack_example
description: An orderable container widget example

dependencies:
  flutter:
    sdk: flutter
  orderable_stack: ^0.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/girafe1.png
    - assets/girafe2.png
    - assets/girafe3.png

  environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"

error

/Users/Documents/Flutter/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in orderable_stack_example...     
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because orderable_stack_example depends on orderable_stack >=0.1.0+1 which requires SDK version >=1.20.1 <2.0.0, version solving failed.

pub get failed (1)
Process finished with exit code 1

**Comment by Laxman007** [comment]
I am trying to add orderable stack lib into my flutter application but it is giving an error of the version.

**Comment by kangwang1988** [comment]
I would recommend you to file a issue under: https://github.com/rxlabz/orderable_stack
According to: https://pub.dartlang.org/packages/orderable_stack
orderable_stack 0.1.3(latest version) is not compatible with Dart2(The dart sdk used in your flutter environment).
@Laxman007
