### ISSUE TITLE
Text not rendered in test when using CustomPainter/Canvas.drawParagraph

### ISSUE THREAD

**Issue by apaatsio** [flutter/flutter#28729]
Text drawn in `CustomPainter` with `Canvas.drawParagraph()` does not show up in the golden file. The test renders only a square box instead.

## Steps to Reproduce
```dart
// text_paint_test.dart
import 'dart:ui';
import 'package:flutter/material.dart' hide TextStyle;
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('text rendering', (tester) async {
    final widget = Center(
      child: SizedBox(
        width: 100,
        height: 100,
        child: RepaintBoundary(child: CustomPaint(painter: MyPainter())),
      ),
    );
    await tester.pumpWidget(widget);
    await expectLater(
      find.byType(RepaintBoundary),
      matchesGoldenFile('text_paint.text_rendering.png'),
    );
  });
}

class MyWidget extends StatelessWidget {
  Widget build(BuildContext context) {
    return CustomPaint(painter: MyPainter());
  }
}

class MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    // draw circle
    canvas.drawCircle(Offset(50, 50), 50, Paint()..color = Colors.blue);

    // draw text
    final paragraphStyle = ParagraphStyle(textAlign: TextAlign.center);
    final textStyle = TextStyle(color: Colors.white);
    final paragraphBuilder = ParagraphBuilder(paragraphStyle)
      ..pushStyle(textStyle)
      ..addText('Hello');
    final paragraph = paragraphBuilder.build()
      ..layout(ParagraphConstraints(width: 100));
    canvas.drawParagraph(paragraph, Offset(0, 50 - paragraph.height / 2));
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}
```

## Expected output
This is how it appears on a device.
![flutter_01](https://user-images.githubusercontent.com/195210/53648137-741a5600-3c3f-11e9-8273-2750e3c2061e.png)

## Actual output
This is the golden file generated by `flutter test --update-goldens test/text_paint_test.dart`.
![text_paint text_rendering](https://user-images.githubusercontent.com/195210/53648178-8ac0ad00-3c3f-11e9-978e-9dab32b3b64e.png)

## flutter doctor -v 
```
[✓] Flutter (Channel beta, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/antti/tools/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/antti/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.31.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • F5321 • BH9035L55P • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by jason-simmons** [comment]
Tests use the "Ahem" font, which renders every character as a box.  This is intended to produce consistent results on all platforms.

**Comment by apaatsio** [comment]
@jason-simmons I see. Is there a way to enable the default font (Roboto) in tests? I tried to search but couldn't find a solution.

Anyway, I will close this issue since it's not a bug but works as expected.

**Comment by apaatsio** [comment]
**Solved.**

For someone else tackling with this here's what to do:

1. Copy Roboto font to `assets/fonts` (or any folder in the project directory, doesn't really matter). Roboto font can be found in `/path/to/flutter/bin/cache/artifacts/material_fonts/`.
2. Load font in your test with
```dart
void main() async {
  final fontData = File('assets/fonts/Roboto-Regular.ttf')
      .readAsBytes()
      .then((bytes) => ByteData.view(Uint8List.fromList(bytes).buffer));

  FontLoader('Roboto')
    ..addFont(fontData)
    ..load();

  // tests here
}
```
3. Define Roboto font explicitly in your code, e.g. `ParagraphStyle(fontFamily: 'Roboto', ...)`

**Comment by TodorGinchev** [comment]
Would you mind sharing the text_paint_test.dart after the fix? I am trying to get custom fonts running in my golden tests and my test hangs on ```await fontLoader.load();```

**Comment by Abhilash-Chandran** [comment]
Here is how I solved this based on @apaatsio comment. 
1. Create directory called fonts in root of test directory or anywhere, as long as the path to the font file is correct in the following code snippet.
2. Create a file called `flutter_test_config.dart` file in the root of the test directory with following snippet. Should be exact same name.
     * why should it be same name > [check here](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html).
```dart
import 'dart:typed_data';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

Future<void> main(FutureOr<void> testMain()) async {
  await loadAppFonts();
  return testMain();
}

Future<void> loadAppFonts() async {
  TestWidgetsFlutterBinding.ensureInitialized();
  final fontLoader = FontLoader('Roboto');
  final fontData = File('fonts/Roboto-Regular.ttf')
      .readAsBytes()
      .then((bytes) => ByteData.view(Uint8List.fromList(bytes).buffer));
  fontLoader.addFont(fontData);
  await fontLoader.load();
}
```
3. Pass your fontfamily to `MaterialApp`'s `theme` property like this.
```dart
MaterialApp(
 theme: ThemeData(fontFamily: 'Roboto'),
)
```

> I didn't do step 3 because Roboto is the default text theme for Flutter apps 😄 .
