### ISSUE TITLE
Add Flutter to existing iOS apps + GIT

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#28725]
Adding flutter to existing iOS apps requires to run the following command (among others):

    $ flutter create -t module my_flutter

My question is regarding that:

 - in the pipline/job in CI/CD we would be required to save the files from the flutter folder, create the flutter module, add the previously saved flutter files and only then it can run the tests or continue the next scripts

 - adding a new member to the team (new environment to setup) will require for that person to run the flutter integration/setup steps and then to add the previous flutter project files from the git on top of the new module created (same as above).

In my situation this is due to local paths that are generated from the flutter scripts.

I would appreciate some input.

**Comment by neiljaywarner** [comment]
@durduman  I am running into similar problem with Android app; I landed for now on including the flutter_sdk as submodule so the only step they have to run is ../flutter_sdk/flutter packages get...

It would be great to improve this even more, but this seems like it might work

**Comment by durduman** [comment]
Before moving this feature out of beta it would be nice to have an "elegant" solution to this situation.

**Comment by neiljaywarner** [comment]
I am seriously considering finding a way to eliminate that step with sertings.Gradle. Does anyone know how to do it on iOS?

**Comment by durduman** [comment]
Well yes, the solution is to add it as a script - either by gradle (for android) or as build phase script (iOS) or a standard script in your CD/CI.

 I would expect this to out of the box behaviour (when they pull it out of beta)

**Comment by jmagman** [comment]
Check out the new add-to-app commands to generate the Flutter artifacts that can be used in existing apps.
[`flutter build ios-framework`](https://flutter.dev/docs/development/add-to-app/ios/project-setup#option-b---embed-frameworks-in-xcode)
[`flutter build aar`](https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar)

**Comment by timsneath** [comment]
Does this answer your question, @durduman?

**Comment by durduman** [comment]
The combination of `build` command (maybe also `clean`) with .git submodules resolved my concern.
