### ISSUE TITLE
[webview_flutter] HTML5 video not working

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#28722]
WebView doesn't show video on iOS
I've created and hosted page to help you reproduce the problem
```html
<html>
<head>
    <meta name="viewport" content="width=device-width">
</head>
<body>
<video controls="" autoplay="" name="media">
    <source src="http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4"
            type="video/mp4">
</video>
</body>
</html>
```
Code to reproduce:
```dart
WebView(initialUrl: "https://camy.cam/video_test.html")
```
I've tested this page in Safari and it works 
Reproduced on iPhone 6 with iOS 11.4.1
Version of `webview_flutter` is 0.3.3+1
Flutter version I've tried is current beta and current master
Result: video stuck on first frame and play button is missing

**Comment by Kartik1607** [comment]
Can you update the hosted page and add a static video instead of referring to sample-videos? It's down for me as of now. Was it down when you tried using it on flutter web-view?

![image](https://user-images.githubusercontent.com/17377741/53642185-31647800-3c57-11e9-9e54-a9080f8590bb.png)

**Comment by rostopira** [comment]
It wasn't down when I tried, that's strange
I will try to find some video to host

**Comment by rostopira** [comment]
I've replaced link with working one

**Comment by rostopira** [comment]
closing as outdated
