### ISSUE TITLE
Support configurable hit test behavior on Draggable

### ISSUE THREAD

**Issue by shyndman** [flutter/flutter#28737]
Hi,

It'd be helpful if Draggable could expose the ability to set the hit test behavior of the underlying GestureDetector. I ran into a situation where I needed a container and its margin to be draggable, and found that the margin was not. I had to work around by using a wrapper container with a transparent background (ie. "opaque" in hit test behavior) to represent margin.

Thanks!

**Comment by wuilmerj24** [comment]
@shamrin 
Hi, have you been able to make a callback when doing drag?

**Comment by adabru** [comment]
Based on your use case, wouldn't it make more sense to make the Container's hit test behaviour configurable instead so that margin returns true in hitTest?

**Comment by shyndman** [comment]
Hard for me to be precise about this, because it was almost two years ago, and I'm not even sure if this is still the case...but let me give it a shot. 

> Based on your use case, wouldn't it make more sense to make the Container's hit test behaviour configurable instead so that margin returns true in hitTest?

I don't believe so, because it would add the requirement that I had control over the container's construction. What if the container was being created deep in a third party library? Should that prevent the draggable from hit testing its margins?

Existing hit testing concepts appear well-suited to this task, where the listener/detector can define what hits it cares about across its entire subtree. If I was allowed to set the hit test behavior of the `Draggable` to `HitTestBehavior.translucent`, it would become capable of registering hits against the space introduced by `Padding` (the widget being used for the Container's margin and padding).

Take a look at [`Dismissible`](https://api.flutter.dev/flutter/widgets/Dismissible-class.html), which is similar in utility to `Draggable` (sets up gestures for an arbitrary child). It supports `behavior` in exactly the way I think `Draggable` should.

**Comment by adabru** [comment]
Now I think I see what you mean. If I understand correctly, for version 1.26 the solution to this issue would probably mean adding the code (untested):

```dart
      behaviour: widget.behaviour,
```

to <https://github.com/flutter/flutter/blob/1.26.0-1.0.pre/packages/flutter/lib/src/widgets/drag_target.dart#L529>.

**Comment by shyndman** [comment]
@adabru Yup, pretty sure that'll do it.
