### ISSUE TITLE
cloud_firestore 0.9.5+2 throws exception (Firestore component is not present)

### ISSUE THREAD

**Issue by AndrsDev** [flutter/flutter#28745]
# PlatformException(error, Firestore component is not present., null)

Trying to perform a simple update action on firestore (according to documentation) throws error. 

### Code
```
import 'package:cloud_firestore/cloud_firestore.dart';

void main() {
  Firestore.instance.collection('books').document().setData({ 'title': 'title', 'author': 'author' });
} 

```

### Error
E/flutter (31782): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Firestore component is not present., null)
E/flutter (31782): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (31782): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (31782): <asynchronous suspension>
E/flutter (31782): #2      DocumentReference.setData (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.9.5+2/lib/src/document_reference.dart:46:30)
E/flutter (31782): #3      main (package:tutting/main.dart:11:53)
E/flutter (31782): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
E/flutter (31782): #5      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (31782): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (31782): #7      _runZoned (dart:async/zone.dart:1516:10)
E/flutter (31782): #8      runZoned (dart:async/zone.dart:1500:12)
E/flutter (31782): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
E/flutter (31782): #10     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
E/flutter (31782): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter (31782):

### Flutter doctor
[√] Flutter (Channel beta, v1.2.2-pre.1, on Microsoft Windows [VersiÃ³n 10.0.17134.590], locale es-GT)
    • Flutter version 1.2.2-pre.1 at C:\src\flutter
    • Framework revision c509a6eb4e (7 days ago), 2019-02-22 21:17:38 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Developer\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Developer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • ANE LX3 • 6NUDU18605002140 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

### pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^0.8.1+4
  cloud_firestore: ^0.9.5+2

```

**Comment by AndrsDev** [comment]
I have successfully implemented firebase_auth, but cloud_firestore throws error.

**Comment by TimonBozzApps** [comment]
same

**Comment by TimonBozzApps** [comment]
I asked the firebase support directly. Maybe this repository isn't the right place for Firebase issues.
It turns out that `cloud_firestore: ^0.9.5` is only compatible with **version 3.2.1 of the Google Services plugin**.
Hence your `android/build.gradle` has to include
`classpath 'com.google.gms:google-services:3.2.1`
But this approach doesn't seem to work either.... 😢

**Comment by TimonBozzApps** [comment]
This gradle works for me!
[android_level_gradle.txt](https://github.com/flutter/flutter/files/2952795/android_level_gradle.txt)

**Comment by AndrsDev** [comment]
@TimonBozzApps  This solution works for me too!!! how did you figured it out? I guess this exception was caused because of the new AndroidX transition

**Comment by AndrsDev** [comment]
I also deleted `/android `and` /ios` directories of the flutter application and followed the steps described here:
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

Documentations says that currently, Flutter is compatible with version 3.2.1 of the Google Services add-on but works well with version 4.2.0

**Comment by cristoferfb** [comment]
I have this issue and how you say is for the transision of the new AndroidX, I manually migrate my flutter app to AndroidX [following this guide](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#how-to-migrate-a-flutter-app-to-androidx) and solve this problem only run flutter clean.

**Comment by Rostanxd** [comment]
The same issue when I tried to run an app from a recently pull from the repo. Just run `flutter clean` and then get the dependencies and tried out. It works for me!

**Comment by buster95** [comment]
> I have this issue and how you say is for the transition of the new AndroidX. I manually migrate my flutter app to AndroidX following [this guide](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#how-to-migrate-a-flutter-app-to-androidx) and solved this problem only running `flutter clean`.

Work for me thanks
