### ISSUE TITLE
Flutter arm64 binary(compiler)

### ISSUE THREAD

**Issue by Barterio** [flutter/flutter#28744]
Can flutter be run on arm64 machines?

I'm trying to figure out is it possible to build flutter application on RasbperryPi or Android device. Since samsung Dex and Linux on Dex feature become available it will be a good feature to compile and run application on android device. 

I've made an investigation and foud that I can compile dart sdk for arm64 architecture. 

Thank you in advance for any ideas.

**Comment by Hixie** [comment]
Does this answer your question?
https://medium.com/flutter-io/flutter-on-raspberry-pi-mostly-from-scratch-2824c5e7dcb1

**Comment by matlab30** [comment]
I want to develop flutter apps on my chromebook with arm64 processor. But I am having a problem when installing latest flutter sdk linux version.
The error is: ( can not execute binary file exec format error) so apparently the sdk version is x86-64 and not for arm architecture. 

So is there a version for arm64 ? How to install flutter sdk on linux with arm64 ? Am I missing something here ?

**Comment by mukhtharcm** [comment]
Is there any updates on this?
Can flutter sdk be installed in arm64 processors?
