### ISSUE TITLE
Licenses check in tools produces cryptic error message

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#28741]
If Android license check fails, users see:

```
Unable to locate the Android SDK; please run 'flutter doctor'.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

None of these directions are applicable. They should be running `<ANDROID_HOME>/tools/bin/sdkmanager --licenses`.

Let's fix this messaging.

**Comment by dnfield** [comment]
The first message is because we're not finding AAPT: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/application_package.dart#L97

Which can happen if you don't have licenses accepted but you do have the binary available.

**Comment by jonahwilliams** [comment]
Can we assume that the cause is always licenses here, or do we need a more generic message?

https://github.com/flutter/flutter/pull/28742

**Comment by jonahwilliams** [comment]
Assigning back to dnfield. From discussion:

> @Dan Field The error is shown when it was looking for aapt, but the reason it couldn't find aapt is because androidSdk was null at that time
androidSdk wasn't initialized in the first place because validSdkDirectory returns false here
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L319
