### ISSUE TITLE
I cannot find PagerTabStrip

### ISSUE THREAD

**Issue by danieldaeschle** [flutter/flutter#28750]
On Android programming i loved PagerTabStrip for many ViewPager pages.

But on flutter i can't find anything which is like this.
Can someone implement this?

My use case is an endlress PageView with title in tab style.

**Comment by Hixie** [comment]
Do you mean `TabBar`?
https://master-api.flutter.dev/flutter/material/TabBar-class.html

**Comment by danieldaeschle** [comment]
No, i mean `PagerTabStrip`   
https://developer.android.com/reference/android/support/v4/view/PagerTabStrip

**Comment by Hixie** [comment]
I don't understand what a PagerTabStrip is as opposed to a TabBar.

**Comment by Hixie** [comment]
(When I search Google Images for "PagerTabStrip" I get pictures of tab bars.)
