### ISSUE TITLE
No "." (extension separator) in image filename that i pick with image_picker when i use android studio emulator

### ISSUE THREAD

**Issue by BobyKurniawan** [flutter/flutter#28761]
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.0.0 at D:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\boby\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (2 available)
    • Redmi 3                   • a2c2a445      • android-arm64 • Android 5.1.1 (API 22)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!

```
  Future getImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() {
      _image = image;
    });
    print(_image);
  }
```

when i run on real device

03-02 09:56:39.620 1698-1763/com.tukangaplikasi.taskmanagement I/flutter: File: '/storage/emulated/0/DCIM/Camera/IMG_20190228_110738_HDR.jpg'

when i run on my emulator

2019-03-02 09:58:09.138 5819-5846/com.tukangaplikasi.taskmanagement I/flutter: /data/user/0/com.tukangaplikasi.taskmanagement/cache/image_picker6345208298100576042jpg

**Comment by Hixie** [comment]
What do you get if you print `_image.path`?

**Comment by amirfeqhi** [comment]
> [√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
> • Flutter version 1.0.0 at D:\flutter
> • Framework revision [5391447](https://github.com/flutter/flutter/commit/5391447fae6209bb21a89e6a5a6583cac1af9b4b) (3 months ago), 2018-11-29 19:41:26 -0800
> • Engine revision [7375a0f](https://github.com/flutter/flutter/commit/7375a0f414bde4bc941e623482221db2fc8c4ab5)
> • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
> 
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> • Android SDK at C:\Users\boby\AppData\Local\Android\sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-28, build-tools 28.0.3
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 3.3)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 33.3.1
> • Dart plugin version 182.5215
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [√] Connected device (2 available)
> • Redmi 3 • a2c2a445 • android-arm64 • Android 5.1.1 (API 22)
> • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> • No issues found!
> 
> ```
>   Future getImage() async {
>     var image = await ImagePicker.pickImage(source: ImageSource.gallery);
>     setState(() {
>       _image = image;
>     });
>     print(_image);
>   }
> ```
> 
> when i run on real device
> 
> 03-02 09:56:39.620 1698-1763/com.tukangaplikasi.taskmanagement I/flutter: File: '/storage/emulated/0/DCIM/Camera/IMG_20190228_110738_HDR.jpg'
> 
> when i run on my emulator
> 
> 2019-03-02 09:58:09.138 5819-5846/com.tukangaplikasi.taskmanagement I/flutter: /data/user/0/com.tukangaplikasi.taskmanagement/cache/image_picker6345208298100576042jpg

@BobyKurniawan , @Hixie Did you find any solution for this problem? It's happening to me only when I choose image from downloads directory.

**Comment by cyanglaz** [comment]
@BobyKurniawan @amirfeqhi https://github.com/flutter/plugins/pull/1541 should have fixed the issue. Could you try with 0.6.0+1 to see if it fixed the issue?

**Comment by cyanglaz** [comment]
i have confirmed that it is fixed, I will close this issue. If you find it is still not fixed, please reopen the issue or open another one with details.
