### ISSUE TITLE
VeggieSeasons sample app design question

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#28763]
In the [VeggieSeasons](https://github.com/flutter/samples/tree/master/veggieseasons) sample app, there is a time display at the top of the list of cards on the home screen. I'm curious what the design intent of the this widget is?

<img width="523" alt="screen shot 2019-03-02 at 12 51 48 pm" src="https://user-images.githubusercontent.com/30503/53676172-830a1280-3cea-11e9-88c6-558c7b3498b9.png">

I find it disconcerting to have a frozen time. I'd vote for either taking it out or making it live update. Thoughts?

**Comment by RedBrogdon** [comment]
This has been changed to a month/year display.

https://github.com/flutter/samples/blame/master/veggieseasons/lib/screens/list.dart#L38
