### ISSUE TITLE
ListTile "leading" parameter stopped working

### ISSUE THREAD

**Issue by brian-dunn** [flutter/flutter#28765]
Before the update, I had a ListView with a set of ListTiles that rendered an image on the left side of each tile with the "leading" parameter and a title on the right using the "title" parameter. Now, the image is stretched across the entire tile, and the title value is not displayed on the screen.

## Steps to Reproduce

Here is my code. The products variable contains a list of maps with the following structure:
"image" : (name of image file in assets folder)
"title": title of item

import 'package:flutter/material.dart';

class ProductListPage extends StatelessWidget{

  final List<Map<String, dynamic>> products;

  ProductListPage (this.products);

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (BuildContext context, int index) {
        return ListTile(
          leading: Image.asset(products[index]['image']),
          title: Text(products[index]['title']),
          // title: Text('test')
        );
      },
      itemCount: products.length,
    );
  }
}
Attached screen shots show how the program ran before and after the version 1.2 upgrade.

![afterupgrade](https://user-images.githubusercontent.com/19672862/53676346-e1d17c80-3c55-11e9-984f-5196b4329fa2.png)
![beforeupgrade](https://user-images.githubusercontent.com/19672862/53676347-e1d17c80-3c55-11e9-8353-5d4854b4a74f.png)

**Comment by brian-dunn** [comment]
The screen that shows the big image and no title is after upgrading to version 1.2. The screen with the missing title and the stretched out image is how it looks after upgrading to version 1.2. There are no differences in the app source code.

**Comment by shihaohong** [comment]
This seems to be the result of https://github.com/flutter/flutter/pull/17496/. I've noticed two behaviors:

1) If leading widget's height is too tall with an appropriate width, the widgets seem to stretch vertically beyond the boundaries of the `ListTile`.
<img src="https://user-images.githubusercontent.com/27032613/54775815-ff965f80-4bcb-11e9-8db8-723819acd6f7.png" height="300px"  />

2) There are no horizontal limits for the leading widget. This causes the ListTile widget to stretch vertically _if_ the title/subtitle text starts to wrap, which occurs regardless of whether there is a leading widget.
<img src="https://user-images.githubusercontent.com/27032613/54775821-045b1380-4bcc-11e9-818a-d8f4bb8f9af7.png" height="300px"  />

I think there could be something could be done to limit the height of the leading widget to prevent the first case from happening, but I think having a flexible width size is fine.

cc/ @HansMuller

**Comment by shihaohong** [comment]
Just noticed that the same behavior also affects `trailing` widgets.
