### ISSUE TITLE
I cannot scroll webview_flutter on Android

### ISSUE THREAD

**Issue by sageata** [flutter/flutter#28769]
I have created a WebView widget as following:

``` dart
WebViewController _controller;

  void initState() {
    _webView = WebView(
      onWebViewCreated: (WebViewController wvc) {
        _controller = wvc;
      },
      javascriptMode: JavascriptMode.unrestricted,
      initialUrl: 'http://localhost:8080',
    );
    super.initState();
  }

```

(If you are asking yourself why I load from localhost, is because I need to load a string into the WebView and this is not supported yet. The local host is returning my html string. However, I achieved the same non-scaling result on google.com as well)

Then I placed this into a Scaffold as the only Widget.

Everything works fine, except with the Scaling on Android Devices only. 

I tried the following:

1.  Modified the Meta Tag inside the HTML as following:

`<meta id="viewport" name="viewport" content="width=device-width, initial-scale=0.9, minimum-scale=0.1, maximum-scale=3.0, user-scalable=yes">`

2. Added the gesture for scaling directly to the WebView through the constructor of the WebView.

Still no, luck.

[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/baloo/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/baloo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • SM G930F  • 9885e6473439505554                   • android-arm64 • Android 8.0.0 (API 26)
    • iPhone XR • 65E40063-C482-48D2-996A-C1812D764ED9 • ios           • iOS 12.1 (simulator)

• No issues found!
-->

**Comment by TahaTesser** [comment]
Hi @sageata 

Are you still experiencing this issue?

### Please try this code sample
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  WebViewController _controller;
  WebView _webView;

  void initState() {
    _webView = WebView(
      onWebViewCreated: (WebViewController wvc) {
        _controller = wvc;
      },
      javascriptMode: JavascriptMode.unrestricted,
      initialUrl: 'https://flutter.dev/',
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: _webView,
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

Thank you

**Comment by TahaTesser** [comment]
Hi @sageata 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
