### ISSUE TITLE
debugCheckHasMaterial assert should just show the entire ancestor chain, one to a line

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2877]
`debugGetOwnershipChain` takes a parameter indicating how many layers to dump. This means that every call site separately codes the dump depth, which is hard to modify.

It would be better if there were a global default value that could be set, then add an optional positional parameter to allow the caller to override the default if desired.

**Comment by Hixie** [comment]
The depth is intentionally different in different call sites. The call is quite expensive, and O(N). Call sites that happen a lot have to make it shorter to save time. Call sites that only trigger on error can give a much bigger number to aid debugging.

**Comment by jimbeveridge** [comment]
The use case I'm debugging is the lack of a Material widget. I need a depth much higher than 10 to figure it out.

**Comment by Hixie** [comment]
I discussed this with Jim and we concluded we should just have the assert show the entire ancestor chain, as a list, one to a line.
