### ISSUE TITLE
fluttor doctor crash

### ISSUE THREAD

**Issue by Teemo2018** [flutter/flutter#28773]
## Steps to Reproduce
 run fluttor doctor

## Logs

Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 49316
⣾Unhandled exception:
NoSuchMethodError: The method '<' was called on null.
Receiver: null
Tried calling: <(Instance of 'Version')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      CocoaPods.evaluateCocoaPodsInstallation (package:flutter_tools/src/ios/cocoapods.dart:69:28)
<asynchronous suspension>
#2      CocoaPodsValidator.validate (package:flutter_tools/src/ios/ios_workflow.dart:231:12)
<asynchronous suspension>
#3      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:304:52)
#4      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#5      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:301:36)
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#10     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#12     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#19     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#21     _doctorText (package:flutter_tools/runner.dart:187:19)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     _doctorText (package:flutter_tools/runner.dart:183:27)
#24     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#25     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#26     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#27     _handleToolError (package:flutter_tools/runner.dart:120:33)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#34     Future._complete (dart:async/future_impl.dart:476:7)
#35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#36     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#37     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#38     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#39     _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)
#40     _rootRunBinary (dart:async/zone.dart:1144:38)
#41     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#42     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#43     Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#44     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#45     Future._completeError (dart:async/future_impl.dart:494:5)
#46     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#47     _Completer.completeError (dart:async/future_impl.dart:27:5)
#48     _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#49     IOClient.send (package:http/src/io_client.dart)
#50     _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)
#51     _rootRunBinary (dart:async/zone.dart:1144:38)
#52     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#53     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
#54     Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
#55     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
#56     Future._completeError (dart:async/future_impl.dart:494:5)
#57     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:542:7)
#58     _rootRun (dart:async/zone.dart:1124:13)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by jonahwilliams** [comment]
This was fixed in https://github.com/flutter/flutter/pull/25872
