### ISSUE TITLE
TabBarView nested problem

### ISSUE THREAD

**Issue by YWD** [flutter/flutter#28777]
[https://github.com/flutter/flutter/issues/17718](url)
I find another problem,I have three tab in outer TabBarView, my inner TabBarView is in the second tab, If I selected third tab ,then select the first tab, the second tab was recreate! It doesn't keep alive, I have choose inner TabBarView's third tab, but it now shows first tab!

**Comment by MrReN** [comment]
You can try to use AutomaticKeepAliveClientMixin or browse the flutter of the sample

**Comment by HansMuller** [comment]
It would help if you could provide a small (smallish) self contained app that demonstrated the problem you've run into.

**Comment by YWD** [comment]
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {

  var tabController;
  @override
  void initState() {
    super.initState();

    tabController = TabController(length: 3,vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: CustomAppBar(),
        body: TabBarView(children: [
          First(),
          Second(),
          Third(),
        ],
          controller: tabController,physics: NeverScrollableScrollPhysics()),
        bottomNavigationBar: TabBar(tabs: [
          Text('first',style: TextStyle(fontSize: 25,color: Colors.black),),
          Text('second',style: TextStyle(fontSize: 25,color: Colors.black),),
          Text('third',style: TextStyle(fontSize: 25,color: Colors.black),),
        ],
          controller: tabController,),
      ),
    );
  }
}

class First extends StatefulWidget {
  @override
  FirstState createState() => FirstState();
}

class FirstState extends State<First> {

  @override
  void initState() {
    super.initState();
    print('first init');
  }

  @override
  void dispose() {
    print('first dispose');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Third extends StatefulWidget {
  @override
  _ThirdState createState() => _ThirdState();
}

class _ThirdState extends State<Third> {

  @override
  void initState() {
    super.initState();
    print('third init');
  }

  @override
  void dispose() {
    print('third dispose');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class Second extends StatefulWidget {
  @override
  _SecondState createState() => _SecondState();
}

class _SecondState extends State<Second> with SingleTickerProviderStateMixin, AutomaticKeepAliveClientMixin<Second> {

  @override
  bool get wantKeepAlive => true;

  var innerTabController;
  GlobalKey<_SecondState> key = GlobalKey<_SecondState>();
  @override
  void initState() {
    super.initState();
    print('second initState');
    innerTabController = TabController(length: 3,vsync: this,);
  }

  @override
  void dispose() {
    print('second dispose');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(),
      body: TabBarView(children: [
        Container(color: Colors.red,),
        Container(color: Colors.yellow,),
        Container(color: Colors.blue,),
      ],
        controller: innerTabController,physics: NeverScrollableScrollPhysics(),key: key,),

      bottomNavigationBar: TabBar(tabs: [
        Text('A',style: TextStyle(fontSize: 25,color: Colors.black),),
        Text('B',style: TextStyle(fontSize: 25,color: Colors.black),),
        Text('C',style: TextStyle(fontSize: 25,color: Colors.black),),
      ],
        controller: innerTabController,),
    );
  }
}

class CustomAppBar extends StatefulWidget implements PreferredSizeWidget {
  @override
  _CustomAppBarState createState() => _CustomAppBarState();

  @override
  Size get preferredSize => Size.fromHeight(kToolbarHeight);
}

class _CustomAppBarState extends State<CustomAppBar> {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.yellow,
      child: SizedBox(
        height: 0,
      ),
    );
  }
}

**Comment by YWD** [comment]
the simple app code is above there. I switch in 'first'/'second' tab or 'second'/'third' tab, second tab keeps alive, but if I switch 'first'/'third' tab, the second page always 'init'(I choose in tab c, it shows tab a), the initState method invoked.

**Comment by YWD** [comment]
> It would help if you could provide a small (smallish) self contained app that demonstrated the problem you've run into.

I don't know how to deal with "waiting for customer response", but comment below the replay.
