### ISSUE TITLE
[package_info] PackageInfoPlugin.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#28772]
Note: C:\Tools\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+1\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Anyoks** [comment]
I have the same warning too:

`
Note: ~/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+1/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
`

**Comment by duzenko** [comment]
I would appreciate a comment from Flutter team on how to deal with these deprecated warnings

**Comment by kw2019ltd** [comment]
still same issue with latest version

**Comment by jmagman** [comment]
\cc @cyanglaz

**Comment by cyanglaz** [comment]
We recently deprecated an API in Android embedder. It shouldn't prevent people from using the plugin though. cc @matthew-carroll  for more details about the deprecated APIs.

**Comment by jmagman** [comment]
> We recently deprecated an API in Android embedder. It shouldn't prevent people from using the plugin though. cc @matthew-carroll for more details about the deprecated APIs.

I'm not sure this is related to https://github.com/flutter/flutter/issues/44070#issuecomment-549947493.  This report is from March.

**Comment by cyanglaz** [comment]
@jmagman oops. Please ignore my last comment. It seems that this issue has been fixed by https://github.com/flutter/plugins/pull/1884
@kw2019ltd Are you still experiencing the issue with the latest version of the plugin?

**Comment by kw2019ltd** [comment]
no issue is fixed now

**Comment by cyanglaz** [comment]
Thank you:) i'm going to close this issue. Please feel free to leave a comment here if you still see the same issue.

**Comment by jonhunterking** [comment]
I am having a similar issue. 

"Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_ble-0.5.3\android\src\main\java\ai\longev\flutter\flutter_ble\FlutterBlePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details."

I went to flutter/plugins#1884 but I do not understand how I can fix this issue locally. I am new to flutter xD What do I have to do to fix this?

**Comment by wcomartin** [comment]
I am having the same issue with the latest version of device_info `v0.4.1+4` if I update my flutter SDK from `>=2.1.0 <3.0.0` to `>=2.2.0 <3.0.0`

```
Note: C:\SDKs\Flutter\.pub-cache\hosted\pub.dartlang.org\device_info-0.4.1+4\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by RollyPeres** [comment]
Same warning for ` sdk: '>=2.6.0 <3.0.0'` using `^0.4.0+13`.

**Comment by mdrideout** [comment]
Same warning 

```
permission_handler: ^4.2.0+hotfix.3

sdk: ">=2.3.0 <3.0.0"
```

**Comment by Zenahr** [comment]
is this warning something that could introduce instabilities in our applications?
