### ISSUE TITLE
[Question] Drawer

### ISSUE THREAD

**Issue by shindakioku** [flutter/flutter#28788]
Is it works with the gesture control?
I can't open drawer by swipe when gesture control is active for phone. (Real device)

**Comment by jonahwilliams** [comment]
HI @shindakioku , the Drawer does work with gesture controls. For an example, see the flutter gallery's "navigation drawer" demo: https://github.com/flutter/flutter/blob/57a8b03c5e7b5a14ba4648e209bece3c4173a83c/examples/flutter_gallery/lib/demo/material/drawer_demo.dart#L97

To debug any further, we would need the output of `flutter doctor -v` as well as a minimal example which reproduces the problem.

**Comment by shindakioku** [comment]
@jonahwilliams hi! Thanks.
I did mean the system with native gesture control (IOS for example)
So, when i use left swipe - my phone will close the app

**Comment by Hixie** [comment]
I'm not sure I understand. Can you attach a small demo app (a small `main.dart` file showing the problem) so we can see what you mean?
