### ISSUE TITLE
Flutter renders animated gif with a black border when resizing

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#28785]
Here is the .gif in question

![gargron](https://user-images.githubusercontent.com/666539/53685056-9b2a6380-3ce3-11e9-9a6f-7528aaeb6db0.gif)

```dart
import 'package:flutter/material.dart';

class Loading extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: CircleAvatar(
        backgroundColor: Colors.white30,
        radius: 48,
        backgroundImage: AssetImage("assets/gargron.gif"),
      ),
    );
  }
}
```

How it renders:

![img_2167](https://user-images.githubusercontent.com/666539/53685071-d62c9700-3ce3-11e9-9ee6-17ede0346210.jpg)

**Comment by lukepighetti** [comment]
After further inspection it appears to add this black border when reducing the size of the gif

**Comment by lukepighetti** [comment]
I don't see any way to select resizing method, nearest neighbor etc.

**Comment by jason-simmons** [comment]
This behavior started with https://github.com/google/skia/commit/21fc5ce7f86d7979df50d34ea53ee5da347c8b08
