### ISSUE TITLE
Widgets get scrambled

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#28786]
Using **Flutter stable 1.2**, in release mode, we're getting strange scrambled images in some devices:

![scrambled](https://user-images.githubusercontent.com/13332110/53684963-fca5fe80-3cf2-11e9-8d76-a3afe543d27f.png)

To the left you see SVG icons, created with `flutter_svg`, inside of a `ListView`. As you scroll the list and new icons come to view, the ones already in the screen get garbled. As if they are being drawn inside of the image buffer of the other one. You can even see parts of one icon inside of the other.

We make heavy use of `flutter_svg` (version 0.11.0+1), but we don't know if there's any relation to that package.

The screenshots above are from a Galaxy S7. Testing in a Galaxy S4 it's more difficult to reproduce it, but it occasionally happens. We have also tested in some other device where we couldn't reproduce it at all. All this happens installing via `flutter build apk`+`adb -d install -r app-release.apk`. If I install via `flutter install` I can't reproduce it, as of now. But it also happens less frequently in the emulator.

I don't know if that's related to issues https://github.com/flutter/flutter/issues/28484, and https://github.com/flutter/flutter/issues/22546, and https://github.com/flutter/flutter/issues/28227, and https://github.com/dnfield/flutter_svg/issues/115, but I would assume so.

> [√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale pt-BR)
>     • Flutter version 1.2.1 at c:\flutter
>     • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\Marcelo\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.2)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 28.0.2
>     • Dart plugin version 181.5616
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2018.3)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
>     • Flutter plugin version 33.3.2
>     • Dart plugin version 183.5912.23
> 
> [√] Connected device (1 available)
>     • SM G930F • 874556d84d7f4d5231 • android-arm64 • Android 8.0.0 (API 26)

**Comment by tvolkert** [comment]
@marcglasberg is the issue fixed when you run against an updated master channel?

**Comment by allandaleho** [comment]
Hello @tvolkert , also having this issue with latest master channel.

**Comment by marcglasberg** [comment]
@tvolkert Yes, unfortunately the issue is not fixed.

**Comment by liyuqian** [comment]
This is probably a duplicate of https://github.com/flutter/flutter/issues/28227
