### ISSUE TITLE
Replace the legacy pointer input event handling with PointerPackets

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#288]
<a href="https://github.com/jason-simmons"><img src="https://avatars.githubusercontent.com/u/14226037?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jason-simmons](https://github.com/jason-simmons)**
_Tuesday Nov 10, 2015 at 00:33 GMT_
_Originally opened as https://github.com/flutter/engine/pull/2021_

----

With this change we no longer need engine/core/events and its IDL bindings.

----

_**[jason-simmons](https://github.com/jason-simmons)** included the following code: https://github.com/flutter/engine/pull/2021/commits_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/chinmaygarde"><img src="https://avatars.githubusercontent.com/u/44085?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chinmaygarde](https://github.com/chinmaygarde)**
_Tuesday Nov 10, 2015 at 01:18 GMT_

----

lgtm. I really like flushing all pending pointer events in one go.

I will update the iOS platform stuff once this lands.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Nov 10, 2015 at 02:42 GMT_

----

LGTM

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Nov 10, 2015 at 02:49 GMT_

----

You'll also need to update `//services/sky`, which is what builds the `sky_viewer.mojo` app that runs inside MojoShell.  It's still using the legacy view manager, so you'll probably need to create pointer packets out of whatever input events the legacy view manager is using.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/jamesr"><img src="https://avatars.githubusercontent.com/u/7497301?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jamesr](https://github.com/jamesr)**
_Tuesday Nov 10, 2015 at 05:32 GMT_

----

sky_viewer.mojo doesn't talk to the legacy view manager (or any other view manager), it talks to native viewport.  The input events it gets are https://github.com/domokit/mojo/blob/master/mojo/services/input_events/interfaces/input_events.mojom instances from the NativeViewportEventDispatcher interface: https://github.com/domokit/mojo/blob/master/mojo/services/native_viewport/interfaces/native_viewport.mojom#L50

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Nov 10, 2015 at 14:43 GMT_

----

@jamesr Yes, you're right.  At some point, we should probably teach NativeViewportEventDispatcher (and eventually Mozart) about pointer packets.

**Comment by Hixie** [comment]
@jason-simmons This is done now right?

**Comment by jason-simmons** [comment]
This has landed.
