### ISSUE TITLE
Android licences not accepted

### ISSUE THREAD

**Issue by sagarsamantaa** [flutter/flutter#28800]
C:\Users\user>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

**Comment by gopi-hl** [comment]
By running flutter doctor --android-licenses, you should be able to accept the licenses pressing "y" key.

For installing the Flutter and Dart plugins, go through this: https://flutter.dev/docs/get-started/editor?tab=androidstudio

**Comment by Hixie** [comment]
@sagarsamantaa What could we have done to solve this problem more effectively for you? Did `To resolve this, run: flutter doctor --android-licenses` not solve the problem?
