### ISSUE TITLE
TextField setState on onChanges curser problem. onEditingComplete not working as expected.

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#28803]
I need to update a text value whenever the value of a TextField changes. 

    onChanged: (String value) {
      setState(() {
        // update some value                
      });
    },

onChanged like this isn't woking because on every `setState()`call, the curser gets placed at another place.

I tried to atleast get a callback, when the user finished editing the TextField like this:

    onEditingComplete: () {
      setState(() { 
        //...
      });
    },

But it seems like `onEditingComplete` is working just like `onSubmitted` meaning it fires whenever a user hits the submit button on the keyboard. But I also need to be notified when the user focuses on another TextField.

```
[✓] Flutter (Channel dev, v1.3.2, on Mac OS X 10.14.3 18D109, locale de-DE)
    • Flutter version 1.3.2 at /Users/jonas/flutter
    • Framework revision 046f960ae2 (2 days ago), 2019-02-28 23:05:45 -0800
    • Engine revision 99f3f7a9c2
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jonas/Library/Android/sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone 6s                 • 02D269B2-8C29-42E8-AE0C-1A990FC79E29 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by tobytraylor** [comment]
Yes.  I've run into this issue `onEditingComplete ` and `onSubmitted` (`onFieldSubmitted`) don't get fired on focus changes.  But if you then use `onSave` you would get the values that were there before focus was lost.

**Comment by I-am-original** [comment]
Hi @tobytraylor Are there any updates on this issue? Thanks

**Comment by TahaTesser** [comment]
Hi @JonasJW 
Are you still experiencing with issue with latest `stable` flutter?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by JonasJW** [comment]
Hi @TahaTesser,

It seems like the first issue I described is fixed meanwhile.

The other issue about `onEditingComplete` seems to be still relevant.

Here is a code sample:

    class TextFieldTest extends StatefulWidget {
      const TextFieldTest({Key key}) : super(key: key);

      @override
      _TextFieldTestState createState() => _TextFieldTestState();
    }

    class _TextFieldTestState extends State<TextFieldTest> {
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(title: Text("Test")),
          body: Column(
            children: <Widget>[
              TextField(
                onEditingComplete: () => print("complete"),
              ),
              TextField(
                onEditingComplete: () => print("complete"),
              )
            ],
          )
        );
      }
    }


I would expect the TextField to fire `onEditingComplete`, when I change focus to the other TextField. When I'm typing in the first TextField, then click on the second TextField, `onEditingComplete` from the first TextField is not called.

Thanks for liking into this issue!

**Comment by TahaTesser** [comment]
Hi @JonasJW 
Please checkout this code sample, `onEditingComplete` is properly called when you switch focus from first `TextField` to another `TextField` 
 
### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final FocusNode fnOne = FocusNode();
    final FocusNode fnTwo = FocusNode();

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter demo'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                textInputAction: TextInputAction.next,
                focusNode: fnOne,
                onEditingComplete: () => print("complete"),
                onSubmitted: (term) {
                  fnOne.unfocus();
                  FocusScope.of(context).requestFocus(fnTwo);
                },
              ),
              TextField(
                focusNode: fnTwo,
                onEditingComplete: () => print("complete"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}


```

Please let me if this resoles your `onEditingComplete` issue
Thank you

**Comment by VladyslavBondarenko** [comment]
I hope it's fixed.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of `flutter doctor -v`  please.
