### ISSUE TITLE
NoSuchMethodError: NoSuchMethodError: The getter 'name' was called on null. on Flutter 1.2 Stable release

### ISSUE THREAD

**Issue by khalithartmann** [flutter/flutter#28806]
Hey guys, so I upgraded Flutter to 1.2 and this is happening... please help me.... 
## command

flutter run

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name

```
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:388:41)
<asynchronous suspension>
#2      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:308:54)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#27     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#34     Future._complete (dart:async/future_impl.dart:473:7)
#35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#36     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G5019, locale en-DE)
    [32m•[39m Flutter version 1.2.1 at /Library/flutter
    [32m•[39m Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/khaledah/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 2.0.0
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 30.0.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.31.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.23.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m POCOPHONE F1 • 6d56c9ac • android-arm64 • Android 9 (API 28)

[32m•[39m No issues found!
```

**Comment by khalithartmann** [comment]
When i ran it using flutter run -v it gave me this error: 
Error running com.peqas.peqas. Manifest versionCode not found
Unable to read manifest info from
/Users/...../peqas_app/build/app/outputs/apk/app.apk.

**Comment by Hixie** [comment]
The stack trace in the first comment implies that `package` is null on this line:
```dart
    printTrace("Stopping app '${package.name}' on $name.");
```

**Comment by Hixie** [comment]
That could be null if `package = await AndroidApk.fromAndroidProject(project.android);` returns null, which presumably is not what happened when it was run the second time (with `-v`), presumably it failed before returning null.

**Comment by Hixie** [comment]
Or maybe it was null when the method was called?

**Comment by iamshm** [comment]
@khalithartmann did you got any solution for this ?

**Comment by jonahwilliams** [comment]
The cause of the NPE is that we return early from `await AndroidApk.fromAndroidProject(project.android)` when we fail to parse the AndroidManifest. Only some of these branches include the appropriate error messages, which we should fix and then ensure that we exit the tool gracefully.

It sounds like there might be a problem in your AndroidManifest.xml, either it is malformed or missing in someway.

**Comment by serhii-k** [comment]
Hello @jonahwilliams

Sorry, but the #31400 solution has introduced an issue for my app.
In my AndroidManifest.xml I have "activity-alias" (with the ...MAIN action and the ...LAUNCHER category) instead of the "activity" xml entity. This alias points to the new .MainActivity.
The name of this alias is the old name for the launcher activity that existed several years ago. This alias is used so that people with old versions of the app don't loose the app icon after upgrading the app.

The code should also take into account 'activity-alias' tags (not just 'activity') to find out the launchActivity:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/application_package.dart#L214
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/application_package.dart#L547

Otherwise I receive this error when trying to execute "flutter run" (after "flutter clean"):

> package identifier or launch activity not found.
> Please check .../android/app/src/main/AndroidManifest.xml for errors.
> No application found for TargetPlatform.android_x86.
> Is your project missing an android/app/src/main/AndroidManifest.xml?
> Consider running "flutter create ." to create one.

Could you please take a look at this issue? Thank you!

**Comment by jaumzera** [comment]
I was getting the same error because my delete query was returning `Future<int>` instead of `Future<void>`.

Not working:
```java
@Query("delete from Product")
Future<int> deleteAll();
```
working:
```java
@Query("delete from Product")
Future<void> deleteAll();
```

**Comment by Marflage** [comment]
> I was getting the same error because my delete query was returning `Future<int>` instead of `Future<void>`.
> 
> Not working:
> 
> ```java
> @Query("delete from Product")
> Future<int> deleteAll();
> ```
> 
> working:
> 
> ```java
> @Query("delete from Product")
> Future<void> deleteAll();
> ```

Thank you so very much

**Comment by Fejick** [comment]
Make sure the Android tools of the correct version in available

For example:
![image](https://user-images.githubusercontent.com/74570905/102075357-2b815c00-3e17-11eb-9407-4608204de8b7.png)

**_How to upgrade your tools_**

1. **Start Android Studio.**
2. **To open SDK Manager, do any of the these:**
   - On Android Studio landing page, select Configure > SDK Manager.
![image](https://user-images.githubusercontent.com/74570905/102075520-684d5300-3e17-11eb-996e-cf1758824bd3.png)
   - From your Android Studio application toolbar, select Tools > Android > SDK Manager.
![image](https://user-images.githubusercontent.com/74570905/102075816-e3166e00-3e17-11eb-8b62-d92d80159743.png)
  - From your Android Studio application toolbar, click SDK Manager.
![image](https://user-images.githubusercontent.com/74570905/102076061-325c9e80-3e18-11eb-9c24-a37481247cf2.png)

3. **In the Default Settings dialog box, click these tabs to install Android SDK platform packages and developer tools.**

    a. SDK Platforms: Select the latest Android SDK package.

    b. SDK Tools: Select these Android SDK tools:
             - Android SDK Build-Tools
             - NDK (Side by side)
             - Android SDK Platform-Tools
             - Android SDK Tools

![image](https://user-images.githubusercontent.com/74570905/102076418-b6168b00-3e18-11eb-819f-71bbf0c5fda3.png)

**Comment by AH-Shawn** [comment]
Thanks a lot.
