### ISSUE TITLE
Flutter_driver timer inconsistency

### ISSUE THREAD

**Issue by mmcc007** [flutter/flutter#28811]
The timeoutMultiplier feature added to flutter driver is missing. Can I get some clarification on that? Is this a permanent removal?
For issue that resulted in adding the timeoutMultiplier feature see #23857

**Comment by jonahwilliams** [comment]
I believe we removed all of the timeouts instead, cc @Hixie.

**Comment by mmcc007** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Yes, this was a permanent removal. @Hixie removed the feature in https://github.com/flutter/flutter/pull/26736 in favor of better logging.

**Comment by mmcc007** [comment]
I have not had a chance to look into this. Any recommendation on how we should proceed in dealing with timeouts for (slow running) emulators in the cloud?

There appears to be no workaround for timeouts in this use case without being able to configure timeout duration.. I believe the default timeout is something like 5 to 7.5 seconds?

**Comment by mmcc007** [comment]
Here is the same example that was used in #23857, now with the timeoutMultiplier removed and timeouts added to each individual driver command (running on Flutter v1.2.1).
https://travis-ci.com/mmcc007/flutter_app/builds/103160948

It shows the counter app integration test succeeding on both iOS simulator and on (slow running) android emulator (wow -- that's great!).

Based on this result, I would like to close this issue for now.

There may well be use cases that run into timeouts on driver commands that apparently do not have configurable timeouts like the GetHealth command (remains to be seen).

In the event the issue re-occurs, I would like to re-open.

😀👍

...
For the record (in case it comes up again):

Source code is:
https://github.com/mmcc007/flutter_app/tree/3926c7dddf95112e16307bd8dcc13e67fb1ad8bc

Relevant flutter driver -v is:
```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/travis/build/mmcc007/flutter_app/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
[!] Android toolchain - develop for Android devices (Android SDK version 25.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling
      support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /opt/android-sdk-linux/tools/bin/sdkmanager "platforms;android-28"
        "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed
      instructions.
    • All Android licenses accepted.
[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
[✓] Connected device (1 available)
    • sdk phone armv7 • emulator-5554 • android-arm • Android 5.1.1 (API 22)
      (emulator)
! Doctor found issues in 2 categories.
```

**Comment by mmcc007** [comment]
Looks like the timeouts on driver calls (especially on slow running emulators in cloud) are not necessary either. Nice!

https://travis-ci.com/mmcc007/flutter_app/builds/103455249
https://github.com/mmcc007/flutter_app/tree/4805282e4756b2cdbf46427cee7f6925dbeb4f81

**Comment by Hixie** [comment]
yeah we removed basically all the timeouts, so even really slow devices should be fine.

**Comment by mmcc007** [comment]
Ah, there may be a hiccup here. The following tests fail with test timeouts, but succeed on retry. Results are reproducible. Any idea why it should succeed on retry? (note: running on slow emulator)
https://travis-ci.org/brianegan/flutter_architecture_samples/jobs/505581787#L1440
https://travis-ci.org/mmcc007/flutter_architecture_samples/jobs/505580681#L1417

**Comment by Hixie** [comment]
@mmcc007 I would remove the 2 minute timeout. Timeouts are race conditions. Race conditions are flaky.

More generally, there's not really a good way for us to tell you what's going on in your specific case. I would recommend adding more logging to try to figure out what your app is doing.

I'm going to close this bug since it's not really actionable from our end.
