### ISSUE TITLE
Flutter packages get

### ISSUE THREAD

**Issue by LucasVillarinho** [flutter/flutter#28812]
This error happens when i use "Flutter: Get Packages" in VS Code Windows 10

### Logs
```
flutter packages get
Running "flutter packages get" in ola_mundo...                  

Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 1 in 1 second...
Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry 2 in 2 seconds...
```

```
ping pub.dartlang.org
Disparando ghs.googlehosted.com [172.217.29.115] com 32 bytes de dados:
Esgotado o tempo limite do pedido. 
```

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [versÃ£o 10.0.17134.590], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.31.1)
[!] Connected device
    ! No devices available
```

### Flutter Version

```
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (2 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

```

**Comment by LucasVillarinho** [comment]
Solution: https://www.wiknix.com/how-to-fix-err_connection_timed_out-error/#Solution_1_Reset_Your_Internet_Connection

**Comment by Amospikins** [comment]
try this in your terminal (mac)
   export PUB_HOSTED_URL=https://pub.flutter-io.cn
   export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

**Comment by FuturetheCoder** [comment]
![error](https://user-images.githubusercontent.com/53884470/66622382-43d86400-ebdf-11e9-95dc-82f5bd107722.png)

**Comment by maheshmnj** [comment]
I had a freshly installed ubuntu and I installed flutter and added to path but it showed 
```flutter pub get failed(69)``` 
whenever it tried to get some files from the internet probably I am not sure

so I checked ```ifconfig``` and found out 

```
Command 'ifconfig' not found, but can be installed with:

sudo apt install net-tools
```

so when I installed it everything worked perfectly

**Comment by jpainam** [comment]
This comment from SO solved the issue

I would advice anyone that might still be having this problem to TRY the following simply steps: 1) Open environment variable settings 2)create a new variable with the name: PUB_HOSTED_URL and its value: https://pub.flutter-io.cn 3)create a new variable with the name: FLUTTER_STORAGE_BASE_URL and its value: https://storage.flutter-io.cn
https://stackoverflow.com/questions/52158282/got-socket-error-trying-to-find-package-cupertino-icons-at-https-pub-dartlang

**Comment by mazmazigh** [comment]
> Solution: https://www.wiknix.com/how-to-fix-err_connection_timed_out-error/#Solution_1_Reset_Your_Internet_Connection

The link is dead, i tried the solution of Environement variables, but it didn't work out

**Comment by Emred360** [comment]
> Solution: https://www.wiknix.com/how-to-fix-err_connection_timed_out-error/#Solution_1_Reset_Your_Internet_Connection

Page not found
