### ISSUE TITLE
flutter output adds too many blank lines

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#28810]
It would be nice if sharing flutter output did not result in so many extraneous blank lines. For example,

```
$ flutter run
Launching lib/main.dart on <an android> in debug mode...
Initializing gradle...                                              1.3s
Resolving dependencies...                                           2.2s
Running Gradle task 'assembleDebug'...                          
/Users/<user>/opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.0.1/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java:72: error: incompatible types: Activity cannot be converted to AppCompatActivity

    AppCompatActivity activity = mRegistrar.activity();

                                                    ^

1 error



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':url_launcher:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 1s
Running Gradle task 'assembleDebug'...                              2.5s
Gradle task assembleDebug failed with exit code 1
```

**Comment by christopherfujino** [comment]
Hi @bradyt,

Could you provide the output of `flutter doctor -v` and sample source code so we can reproduce?

**Comment by bradyt** [comment]
@christopherfujino, I can no longer reproduce that particular issue, at https://github.com/flutter/flutter/issues/28813. But if I understand correctly, it would not be hard to provoke an error by mixing something up on an a migration to AndroidX. I expect you'll see the similar line spacing as I described above.

**Comment by bradyt** [comment]
Perhaps the only thing unusual in my environment is that I'm not in an IDE. Have you tried experiencing such errors in for example `bash` in a dedicated terminal emulator, like `Terminal.app` or similar?

**Comment by christopherfujino** [comment]
@bradyt thanks for the link to #28813, I'll try playing around with that. And likewise, I'll test it from the command-line.

**Comment by csells** [comment]
closed due to inability to reproduce
