### ISSUE TITLE
This version of firebase_auth will break your Android build if it or its dependencies aren't compatible with AndroidX

### ISSUE THREAD

**Issue by manthan37** [flutter/flutter#28822]
Manthans-MacBook-Air:ioregister Manthan$ flutter run -d e2f3aa94
Launching lib/main.dart on vivo 1716 in debug mode...
Initializing gradle...                                       8.5s
Resolving dependencies...                                    5.4s
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:9: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:10: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:706: error: cannot find symbol
  private void reportException(Result result, @Nullable Exception exception) {
                                               ^
  symbol:   class Nullable
  location: class FirebaseAuthPlugin
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:610: error: cannot find symbol
    public void onComplete(@NonNull Task<AuthResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.SignInCompleteListener
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:629: error: cannot find symbol
    public void onComplete(@NonNull Task<Void> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.TaskVoidCompleteListener
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:647: error: cannot find symbol
    public void onComplete(@NonNull Task<SignInMethodQueryResult> task) {
                            ^
  symbol:   class NonNull
  location: class FirebaseAuthPlugin.GetSignInMethodsCompleteListener
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:187: error: cannot find symbol
                      public void onComplete(@NonNull Task<AuthResult> task) {
                                              ^
  symbol: class NonNull
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:492: error: cannot find symbol
              public void onComplete(@NonNull Task<GetTokenResult> task) {
                                      ^
  symbol: class NonNull
/Users/apple/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java:559: error: cannot find symbol
          public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                                          ^
  symbol: class NonNull
9 errors
         *********************************************************
WARNING: This version of firebase_auth will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firebase_auth:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

Gradle task 'assembleDebug'... Done                          4.8s
Gradle task assembleDebug failed with exit code 1

**Comment by manthan37** [comment]
it's work fine in ios but can's install in an android simulator. Please help me with this : )

**Comment by imatok** [comment]
@manthan37 
This just means that your flutter project, more specifically its android part, needs to be upgraded to use androidx.support instead of deprecated android.support library. 
Just check the page on that link in the warning section to learn how.

**Comment by manthan37** [comment]
@imatok , I tried, but nothing works. can u please help me to sort out all of this??

**Comment by imatok** [comment]
So, if your project doesn't use any of 'blacklisted' plugins on that page and your android/app/build.gradle has 'compileSdkVersion 28', then as first step you can try to add to your android/gradle.properties: 
```
android.enableJetifier=true
android.useAndroidX=true
```
(Btw. this step can be found just one click away from that initial page, named: Migrating to AndroidX.)
I just tried this on newly created flutter project with that firebase_auth as dependency and it successfully builds and runs on simulator (one remark thou, I'm using Flutter 1.3.2 from dev channel).

**Comment by manthan37** [comment]
@imatok still don't work, please have a look at https://github.com/manthan37/flutter-ioregister try to run on an Android device. :'(

**Comment by imatok** [comment]
> your android/app/build.gradle has 'compileSdkVersion 28'
This part you simply ignored. Your gradle file has 'compileSdkVersion 27'. You could try changing it to 28 and see what happens.

**Comment by manthan37** [comment]
@imatok i tried

**Comment by manthan37** [comment]
@imatok done. 

**Thank You so much**

 for you help.

**Comment by piyushsinha24** [comment]
@manthan37 facing same error...followed above steps still not working...help pls

**Comment by BarbaricGamester** [comment]
I also need help

**Comment by hanihashemi** [comment]
@piyushsinha24 @BarbaricGamester 
please check the log, if you see below error:
android.arch.lifecycle.DefaultLifecycleObserver -> androidx.lifecycle.DefaultLifecycleObserver

then you have to add this dependency:
implementation "androidx.lifecycle:lifecycle-common-java8:$

**Comment by vigneshwaranvelmurugan** [comment]
i think your network is slow. please connect good internet.me face the same error. i connect good internet this working fine.
