### ISSUE TITLE
Xamarin vs Flutter vs ASP.Net vs .net core, and 3rd party vendors

### ISSUE THREAD

**Issue by reader-man** [flutter/flutter#28820]
This is a suggestion to MS/Google, and all 3rd party vendors.
https://readerman1.wordpress.com/2019/03/04/xamarin-vs-flutter-3rd-party/

Xamarin while has a lot of nice features, it just still takes all the heavy load of the OS original UI.
Its advances depend on the pace of the OS UI developers.
IT still needs to have several programming models depending on each platform.
And its very difficult to move it to other domains, e.g. Web/desktop/VR/Holo/Console/Smart IoT
 
Flutter, and its dependency on Skia, benefits:
1.	Can mature very fast independent from the OS UI developers, in features.
2.	Normal developers, can extend it, without repeating their work for each platform.
3.	Its fast(60+ fps) is not a small feat for a UI kit.
4.	Its easily can be ported to other platforms like Web/desktop/VR/Holo/Console/Smart IoT
5.	Can easily adapt to new platforms UI, or make its own themes.
6.	UI code sharing for all platforms.
7.	Easily can have its own themes, so we can have one app, that have one look, on all platforms, which eases the learning curve on the user.
8.	Animation/effects that need to skip the platform old UI, and go directly to hardware.
9.	making new UI controls/widgets is very easy, fast, powerfull, and runs on all platforms.
 
What flutter needs:
1.	To be independent from Dart, to ease its use in other languages, like c# from .net core, that google itself is using and developing, java, kotlin, and other main stream languages.
2.	Initiate the port to Web/desktop/VR/Holo/Console/Smart IoT, and the open source community will help in that.
 
What Xamarin needs to do:
1.	Use either skia, or other alternative GPU portable engines, that are very fast, and easily portable to any OS.
2.	Make it the .net core UI.
3.	Initiate multiple targeted platforms from the start: Web/desktop/VR/Holo/Console/Smart IoT, and not forgetting the Phone.
4.	Stop the old "java-awt" style, and consider the "java-swing" style.
5.	Maybe have a way to connect the xaml standard.
 
 
What 3rd party companies need to address:
1.	Help in connecting other languages to flutter, like .net.
2.	Have their own native flutter UI components/widgets, which will give flutter the fast momentum that .net 3rd party companies gave.
3.	As they have their own javascript UI components, they should not be afraid to add to their wagon, another toolkit, that is not an MS based one.
4.	remember that this will ease their interance to new platforms: Consols/VRs/Holos/Smart IoT
and thats a call to all 3rd parties:
ALL .NET Control Suites
•	Telerik DevCraft Ultimate
•	DevExpress Universal 
•	ComponentOne Studio Enterprise
•	Intersoft Premier Studio
•	Karamasoft UISuite 
•	Xceed Ultimate Suite
•	Nevron Vision for .NET
•	Aspose.Total for .NET
•	Peter Blum Data Entry Suite
•	Mindscape Mega Pack
•	FusionCharts Suite XT
•	Telerik RadControls for ASP.NET AJAX
•	Kendo UI Web
•	Kendo UI for ASP.NET MVC
•	DevExpress ASP.NET
•	Essential Studio for ASP.NET MVC
•	Infragistics NetAdvantage for ASP.NET
•	WebUI Studio 2013 for ASP.NET
•	LiveControls - AJAX Toolkit for ASP.NET
•	Gaia Ajax
•	obout Suite for ASP.NET
•	EmailVerify.NET
•	Keyoti Search for ASP.NET
•	Visual Studio 2013 Toolbox Controls
•	DevExpress WinForms
•	Infragistics NetAdvantage for Windows Forms
•	Essential Studio for Windows Forms
•	Xceed Grid for .NET
•	RapidSpell for .NET
•	Toolkit Pro 2013 for Visual C++ MFC

**Comment by jonahwilliams** [comment]
Hi @reader-man, I think a better forum for a discussion like this would be on the flutter-dev group (https://groups.google.com/forum/#!forum/flutter-dev) or in a community channel. Github issues are more for resolving bug reports.
