### ISSUE TITLE
Detect keyboard visibility

### ISSUE THREAD

**Issue by YAPPDEF** [flutter/flutter#28839]
```
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale de-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)
```

Until v1.2.1 I checked the visibility of the keyboard with `MediaQuery.of(context).viewInsets.bottom` (not recommended). _The keyboard_visibility plugin was not working for me._

Since v1.2.1 it's not working anymore. 
If I set `resizeToAvoidBottomPadding: false` on my Scaffold, it works somehow, bot the keyboard is then overlapping the content (eg. buttons at the end of the page are not visible anymore).

Is there any possibility to detect if the keyboard is opened or not?

**Comment by Eimji** [comment]
Hello, I can confirm, MediaQuery.of(context).viewInsets.bottom always gives 0.0 (even if the keyboard is visible)

**Comment by YAPPDEF** [comment]
> EDIT: Sorry, I found my error. MediaQuery.of(context).viewInsets.bottom still works. I just have a mismatch between different contexts (BuildContext context have the same in the build fct and in a builder inside this). The same code worked before v 1.2.1, but it seems Flutter is now more strict when naming the variable context.

What did you exactly need to change that it still works in v1.2.1?

**Comment by zaubererty** [comment]
I'm facing kind the same problem. I did a lot of investigation and think the rerender is started to early, cause the keyboard is still in animation and there for the insert is 0.0 and i use a save area which has the full screen size. When I force a rerender when the animation has finished then are the values correct.

**Comment by iapicca** [comment]
Hi @YAPPDEF 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Comment by kendall-lu** [comment]
After changing the MainActivity.kt file from FlutterActivity to FlutterFragmentActivity, the keyboard listener breaks on android but works on iOS. FlutterFragmentActivity was used to enable biometric auth. Anyone have any tips for this?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
