### ISSUE TITLE
Augment Forms so that they can be used to have selections survive build structure changes without needing global keys everywhere

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2883]
Follow-up to https://github.com/flutter/flutter/pull/2850.

Previously, if you had Input widgets, you had to maintain their InputValue. This did two things, it made them mutable and it made their selections survive build structure changes.

With Form, we now no longer need to do this to make them mutable, but we've lost the resiliency against build structure changes. There's a workaround for now, which is to put GlobalKeys on each Input, but that's pretty verbose.

We should have the Inputs register their InputValues with the Form, then have the Form put those values into an opaque object which the app can maintain across builds, handing it to the Form each time. That way the Inputs will be safe from structure changes.

The problem is how to do this without having the Inputs needing to be given unique keys (which wouldn't be any better than the current situation).

**Comment by mpcomplete** [comment]
I believe the new Form widget fixes this issue, but I'm not sure how to tell.

**Comment by Hixie** [comment]
have a build function return the structure Form-Container-InputTextField in one case, and Form-Container-Container-InputTextField in another, with no global keys anywhere.

Select text in the text field, cause it to switch to the other build pattern. Does the selection survive?

**Comment by mpcomplete** [comment]
OK, still not fixed. With that example, the entire contents of the InputFormField are blown away.

**Comment by Hixie** [comment]
Now that we have a `controller` field, this should just work.
