### ISSUE TITLE
setMockInitialValues on SharedPreferences only works once

### ISSUE THREAD

**Issue by dav1dev** [flutter/flutter#28837]
Hi there!

The testing method to setup initial values on shared preferences `SharedPreferences.setMockInitialValues(<String, dynamic>{...})` can only be used once. It is not possible to setup new values after the first usage. I can reproduce this issue when executing the following two tests in a single test run. Both tests pass when run separately. 
```
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {

  const String _key = 'dummy';
  const String _prefixedKey = 'flutter.' + _key;

  test('test 1', () async {
    SharedPreferences.setMockInitialValues(<String, dynamic>{_prefixedKey: 'my string'});
    final prefs = await SharedPreferences.getInstance();
    final value = prefs.getString(_key);
    expect(value, 'my string');
  });

  test('test 2', () async {
    SharedPreferences.setMockInitialValues(<String, dynamic>{_prefixedKey: 'my other string'});
    final prefs = await SharedPreferences.getInstance();
    final value = prefs.getString(_key);
    expect(value, 'my other string');
  });
}
```

Development environment:
* shared_preferences ^0.5.1+1
* flutter 1.2.1
* dart 2.1.2
* android studio 3.3.1 on windows 10

As `SharedPreferences` makes use of a static singleton, I guess the instance persists between tests.

Thanks for looking into this!

**Comment by mulderpf** [comment]
This issue has left me so incredibly frustrated.

**Comment by itamus1** [comment]
I'm also stuck with this issue. As dav1dev mentions, this behaviour occurs if you use
`SharedPreferences.setMockInitialValues(<String, dynamic>{...})`
but it also occurs setting shared preferences like this:
`SharedPreferences prefs = await SharedPreferences.getInstance();
 await prefs.setString("key", value);`
so the `SharedPreferences` instance seems to persist between tests regardless of how it is set up.

If anyone can suggests a work around that would be really helpful.
Cheers.

**Comment by dav1dev** [comment]
hi @itamus1,
to work around this issue, I manually reset instance values in each test that depends on shared preferences using a shared setup method:

```
Future setupSomePreferences(String value) async {
  SharedPreferences.setMockInitialValues(<String, dynamic>{'flutter.some.preferences': value});
  final preferences'= await SharedPreferences.getInstance();
  // TODO this should not be necessary
  // reported issue: https://github.com/flutter/flutter/issues/28837
  preferences'.setString('some.preferences', value);
}
```
Hopefully I can remove this TODO some day. Hope this helps.

**Comment by dav1dev** [comment]
Closed issue by mistake, sorry!

**Comment by itamus1** [comment]
Thanks dav1dev. I'll get chance to try that out next week.

**Comment by itamus1** [comment]
Hi @dav1dev,

I'm getting the same issue even when using a shared setup method. I suspect I'm being dense... could you please show me how you incorporate your shared setup method into the example code you wrote to describe the issue so that it passes those two tests when they are executed as a single run?

Much appreciated, thanks.

**Comment by dav1dev** [comment]
hi @itamus1,
incorporated into example tests above:

```
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {

  const String _key = 'dummy';

  test('test 1', () async {
    await setupPreferences(_key, 'my string');
    final prefs = await SharedPreferences.getInstance();
    final value = prefs.getString(_key);
    expect(value, 'my string');
  });

  test('test 2', () async {
    await setupPreferences(_key, 'my other string');
    final prefs = await SharedPreferences.getInstance();
    final value = prefs.getString(_key);
    expect(value, 'my other string');
  });
}

Future setupPreferences(String key, String value) async {
  SharedPreferences.setMockInitialValues(<String, dynamic>{'flutter.' + key: value});
  final preferences = await SharedPreferences.getInstance();
  await preferences.setString(key, value);
}
```
and the tests pass.

**Comment by itamus1** [comment]
Hi @dav1dev ,

Many thanks for taking the time to post the above code. As you say, it does pass.

Unfortunately, I still have a problem. If shared preferences are setup within the tests as above, everything works fine. However, a couple of my tests run parts of my app which set shared preferences. When shared preferences are set in this manner, the above code then seems unable to reset them again.

Thanks anyway for your time and effort. I need to press on with some other development and I hope this bug will be ironed out at some point in the future. I can work around it for now by running all the tests that need to set up shared preferences (as above) first and then all those that run code in the app that set shared preferences second.

**Comment by dipendra-sharma** [comment]
I'm still facing this issue.

**Comment by subzero911** [comment]
me too
