### ISSUE TITLE
Debugging the native android doesn't work

### ISSUE THREAD

**Issue by s-bhat99** [flutter/flutter#28841]
I have been trying to debug the platform_channel sample project in the flutter and the debugging is only in the flutter side. The execution doesn't hit the breakpoint in the native android. The application is working as expected but the debugging doesn't. I am using Android studio. Can some one please tell me how to debug the native android code ?

**Comment by manthan37** [comment]
u can try with adding debugDumpApp(); function to you main.dar, simply add flatbutton and add onPressed:( ){ debugMyApp();}

**Comment by Hixie** [comment]
cc @devoncarew Do we have documentation about how to debug the OEM side?

**Comment by escamoteur** [comment]
@manthan37 Where you able to solve your problem? If yes I can close this issue.

**Comment by iapicca** [comment]
Hi @s-bhat99 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you
