### ISSUE TITLE
the tearDownAll test callback should provide a configurable timeout

### ISSUE THREAD

**Issue by dustin-graham** [flutter/flutter#28840]
I have a case where I need to do a bit of heavy lifting after my integration test finishes. While doing this heavy lifting I have run up against the 30 second timeout provided by the framework for these callbacks. 

I would like to be able to configure a custom timeout similar to the one available in the `test` method.

**Comment by jonahwilliams** [comment]
cc @grouma - I don't believe test has a configurable timeout for these callbacks?

**Comment by mmcc007** [comment]
This may be related to #28811

**Comment by jonahwilliams** [comment]
> This may be related to #28811
tester and driver callbacks are unrelated

**Comment by mmcc007** [comment]
I may be mistaken, but the issue appears to be in regard to a timeout during tear-down after an integration test. If so it is related as mentioned (and to the general removal of timeouts altogether -- in flutter/flutter/pull/26736).

**Comment by grouma** [comment]
The `test` timeout includes the `tearDown` execution time. I don't think this is an issue. You should be able to simply extend the timeout of your tests that make use of the long `tearDown`.

**Comment by dustin-graham** [comment]
@grouma I don't believe this is true. For example, I have set an arbitrarily large 30 minute timeout on my test. My test ran (takes about a minute) and finished and my `tearDownAll` gets called. Then, in my `tearDownAll`, I placed a `Future.delayed(Duration(seconds: 40))` and it throws a timeout error 30 seconds after `tearDownAll` starts to run.

**Comment by dustin-graham** [comment]
@grouma I readjusted my test case to use `tearDown` instead of `tearDownAll` and it does indeed appear to use the timeout from the test that I provided. However, this is not true for `tearDownAll` which has its own 30 second timeout. So the case for having this functionality in `tearDownAll` still remains I'd like to reopen the ticket and change the description to match the desired functionality.

**Comment by grouma** [comment]
Thanks for the clarification. I just tested `tearDown` but not `tearDownAll`.

**Comment by grouma** [comment]
I looked at this a bit further. The test runner creates a synthetic test here: https://github.com/dart-lang/test/blob/master/pkgs/test_api/lib/src/backend/declarer.dart#L304. It uses the default metadata for timeout. Thus you can actually configure it by changing your default timeout, e.g. through an annotation `@Timeout()`.

Supporting an optional argument to the `tearDownAll` method seems a little tricky. You can make a couple calls to `tearDownAll`. These callbacks are run sequentially inside of a single synthetic test. It isn't clear to me what we would do with the timeouts. Would the timeout be the summation of all the provided arguments?

I'm thinking a better alternative is to just up the default timeout for the synthetic `tearDownAll` test to be 12 minutes. We do something similar for our synthetic load tests: https://github.com/dart-lang/test/blob/master/pkgs/test_core/lib/src/runner/load_suite.dart#L37
