### ISSUE TITLE
Adding a new flutter module app to existing iOS app complains about missing FlutterPluginRegistrant

### ISSUE THREAD

**Issue by yujingz** [flutter/flutter#28849]
As the title suggests, I was trying to add a flutter module app to an existing app following the official guide https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

Everything runs fine up to the final point where I try to build the iOS app and it complains about 

```
ld: warning: directory not found for option '-F/some/path/flutter/build/ios/Debug-iphonesimulator/FlutterPluginRegistrant'
```

I checked the intermediary build folder and wasn't able to find `FlutterPluginRegistrant`, my guess is the `FlutterPluginRegistrant` pod wasn't updated to have the right build settings?

It's really too big of a file to upload for a minimal demo setup. But happy to if its needed for further discussions. What I did was really just following the guide. 

Running softwares are:
XCode: 10.0 and 10.1 both failed
CocoaPods: 1.6.1
Flutter: 1.2.1
OSX: 10.14.2

**Comment by Hixie** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@dnfield would you mind looking into this?

**Comment by dnfield** [comment]
What happens if you do a `pod install` in your .ios folder?

**Comment by yujingz** [comment]
@dnfield i just ran the guide again and pod install in the .ios folder gives me 
`No `Podfile' found in the project directory.`

**Comment by Lolingew** [comment]
I don't know if my case works for you. I meet almost the same problem.
All for mistaking xcodeproj file and xcworkspace file...
I should have double clicked and opened MyProject.xcworkspace, not MyProject.xcodeproj.
After I opened the right file, it works.

**Comment by ryansong** [comment]
Have the same issue when following the [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](guide) cocoapods  in this phase "You should now be able to build the project using ⌘B."
And I can see the libFlutterPluginRegistrant.a is integrated in project, there is maybe something wrong with the configuration.

**Comment by wickedman1976** [comment]
With the flutter integration into an existing iOS app, are you meant to only have the one project (existing main native app) or are you effectively having two apps.  As I can see there is a project in the .ios folder?

**Comment by jmagman** [comment]
@wickedman1976 There are two Xcode projects, but everything you need should be embedded in the existing host app.  The one in .ios is essentially a test app that lets you call whatever Flutter views you need without navigating through the existing host app.

@yujingz can you confirm you were running from the xcworkspace and not the xcproject?

**Comment by wickedman1976** [comment]
Thanks. Each time I test though I have to change the workspace settings in test project to legacy build settings for ios. Is this expected behaviour?

**Comment by jmagman** [comment]
That's https://github.com/flutter/flutter/issues/20685. Are you still seeing the FlutterPluginRegistrant issue?

**Comment by jmagman** [comment]
@yujingz Can you try deleting your .ios directory and letting it get re-generated?
```
cd /path/to/HostApp/flutter_module
rm -rf .ios
flutter build ios
cd .. 
pod install
```
Then try building your existing app again.

**Comment by jmagman** [comment]
Is anyone still seeing this issue?  I've not been able to reproduce on the master channel.

**Comment by jmagman** [comment]
This could have been fixed with a few changes to add-to-app in the last few months.  If anyone is still seeing this, please comment here or file a new issue.  Thanks!

**Comment by gvenkat62** [comment]
install flutter 1.12 or above & install xcode 10.2 then "Missing plugin" issue will be solved.
As of Flutter v1.12, add-to-app is supported for the basic scenario of integrating one full-screen Flutter instance at a time per app.
https://flutter.dev/docs/development/add-to-app
