### ISSUE TITLE
flutter doctor should do some checks of the current project

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#2885]
If `flutter doctor` is run in a directory containing a project, it should run checks for that project. Things like verifying the engine version, that some dirs exist (android/AndroidManifest.xml, android/res/, ios/), that pub has been run, ...

**Comment by jmagman** [comment]
I had some ideas in duplicate https://github.com/flutter/flutter/issues/37041:
 
> * App name
> * Build name
> * Build number
> * Uses material design
> * Uses Android X
> * is module
> * is plugin
> * Android package
> * iOS bundle identifier
> * Supported platforms (if plugin)

From that issue, @jonahwilliams said:
> I don't want to add anymore flags to the doctor command, because it's not obvious how we would surface that in the context of an IDE. We've talked about a `flutter check` command, or attaching more diagnostics to `flutter analyze`

See also https://github.com/flutter/flutter/issues/1657.

**Comment by christopherfujino** [comment]
From [#36496](https://github.com/flutter/flutter/issues/36496) (which I closed in favor of this issue), list which plugins a project is using.

**Comment by Jasguerrero** [comment]
@jonahwilliams Is the stand of not making doctor contextual (run inside the app folder) still in place? The main problem I see that we are trying to solve is when a user tries to create a new issue it would be helpful to have more details about the app so as @jmagman mentioned on https://github.com/flutter/flutter/issues/37041 we could instruct the user to run the doctor in the context of an app.

**Comment by christopherfujino** [comment]
> @jonahwilliams Is the stand of not making doctor contextual (run inside the app folder) still in place? The main problem I see that we are trying to solve is when a user tries to create a new issue it would be helpful to have more details about the app, so as @jmagman mentioned on #37041 we could instruct the user to run the doctor in the context of an app.

I think it makes sense to make this a new command.

**Comment by jonahwilliams** [comment]
flutter doctor already does a ton. I'm a little concerned too that it would be "mysterious" if a command behaved differently based on whether or not it is in a project folder. I agree with @christopherfujino that it would be simpler for all if it were a different command.

**Comment by Jasguerrero** [comment]
Alright. Any suggestion on the command name? I like "appnalyze" but I don't know if is intuitive enough

**Comment by christopherfujino** [comment]
> Alright. Any suggestion on the command name? I like "appnalyze" but I don't know if is intuitive enough

I don't think that's intuitive enough :)

**Comment by christopherfujino** [comment]
This was completed with the `flutter analyze --suggestions` flag.
