### ISSUE TITLE
frontend_server support for modular kernel

### ISSUE THREAD

**Issue by keertip** [flutter/flutter#28858]
Currently, the frontend_server does not have support for modular kernel compilation in the similar fashion to the bazel kernel worker https://github.com/dart-lang/sdk/blob/master/utils/bazel/kernel_worker.dart. This kernel generator can generate kernel files for packages, does not have to be whole program.

The frontend_server has support for passing in an dill file for initialization, but this is not sufficient.  

Modular compile can be used in the test framework to cache artifacts and speed up test iterations, by doing an incremental compile of only the changed sources.

**Comment by keertip** [comment]
/ cc @mehmetf, @gamebox

**Comment by jonahwilliams** [comment]
Why not add flutter support to the kernel worker and use that instead?

I'm curious about the performance (especially for ci) of the frontend server approach vs a build_runner approach, but I don't know what the performance impact would be of precompilation vs initialize from dill

**Comment by keertip** [comment]
For the internal code base, going modular will make iterative development much faster, build times will be greatly reduced due to compilation of only the changed packages and not the whole program. Not sure how much of an impact this would be in the external workflow.

/cc @aam would be the best person to answer on build_runner vs forntend_server.

**Comment by aam** [comment]
> Why not add flutter support to the kernel worker and use that instead?

Can yo clarify what kernel worker is? I assume that kernel worker is pub-integrated component that wraps frontend compiler and supports modular compilation of packages.

From batch-run perspective it seems that making kernel worker flutter-aware should be simple - that aspect of frontend=server is nothing but thin wrapper over the compiler that passes few configuration options that point to flutter-enriched dart sdk.
frontend-server stdin/stdout-driven incremental compilation that supports hot reload is different story. Not sure what the flow would look like with kernel worker in place.

**Comment by jonahwilliams** [comment]
kernel_worker is a wrapper for the compiler that is aware of the blaze worker protocol:

https://github.com/dart-lang/sdk/blob/master/utils/bazel/kernel_worker.dart

It would need support for the flutter and flutter_runner targets, I don't think the target is configurable for now. It also would need option for kernel-transforms, if that is compatible with the modular compilation.

**Comment by keertip** [comment]
What we need is a batch mode kernel compiler that can generate modular kernel for flutter. If we can add that support to bazel worker, that should be good enough. Then we can use the bazel worker to produce the initial dill and use the front end server for the hot reload.

**Comment by Hixie** [comment]
Closing as obsolete per @keertip.
