### ISSUE TITLE
Appears that our menu is lower than the OEM toolkit's menu

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2886]
![screen shot 2016-03-24 at 5 02 53 pm](https://cloud.githubusercontent.com/assets/5479/14034693/bf4fd9c4-f1e2-11e5-895f-413b63857770.png)

I see more space between the system's bar and our menu, on the left, compared to the right.

**Comment by abarth** [comment]
I believe our menu placement is correct according to the spec and the Java implementation is off-spec:

https://www.google.com/design/spec/components/menus.html

**Comment by sethladd** [comment]
Thanks for taking a look!

![screen shot 2016-03-25 at 8 55 26 am](https://cloud.githubusercontent.com/assets/5479/14047822/628cd054-f267-11e5-949d-9b0df7b1d26b.png)
