### ISSUE TITLE
DropdownButton decoration / underline is not customizable

### ISSUE THREAD

**Issue by shaynekellyii** [flutter/flutter#28861]
I want to customize the colour of a `DropdownButton` but the widget's decoration is hard-coded: 

```dart
if (!DropdownButtonHideUnderline.at(context)) {
      final double bottom = widget.isDense ? 0.0 : 8.0;
      result = Stack(
        children: <Widget>[
          result,
          Positioned(
            left: 0.0,
            right: 0.0,
            bottom: bottom,
            child: Container(
              height: 1.0,
              decoration: const BoxDecoration(
                border: Border(bottom: BorderSide(color: Color(0xFFBDBDBD), width: 0.0))
              ),
            ),
          ),
        ],
      );
    }
```

There is a similar issue with a PR https://github.com/flutter/flutter/issues/25151 but doesn't make any changes to allow customizing the decoration. A parameter could be added to the `DropdownButton` constructor to change the border.

Can't find anything in the material spec to suggest that the border should always be styled as `BorderSide(color: Color(0xFFBDBDBD), width: 0.0)`. I could add a PR for this.

**Comment by AlbertKamau** [comment]
The underline property requires a widget. You can customize by adding a Container(color:Colors.red, height:1.0)

**Comment by shaynekellyii** [comment]
Yes, I added that functionality in the pull request references above. :)
