### ISSUE TITLE
Improve ThemeData colors docs

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28865]
There are several parameters inside of `ThemeData` and it's complicated to understand how they will be used by the `Widgets`.

For example, I want to define a `primarySwatch` using `Colors.blue`, but this will get `Colors.blue[500]` and the `primaryColor` and I want in fact `Colors.blue[300]` to be the primary color.... how will then `primaryColorLight` behave? Will it stay at 0x6ec6ff as defined by `Colors.blue[500]` and I have to change it manually? Or will it go automatically to 0x9be7ff as defined by the Material Specs? I can't know because the whole process isn't explained at the docs.

**Comment by feinstein** [comment]
As far as I understand from the `ThemeData` code, the swatch values are hard coded, so there's no automatic way to "shift" the center of the swatch.

I think there should be a way to "bias" the color swatch, using an algorithm equal to the one [here](https://material.io/tools/color/#!/?view.left=0&view.right=0&primary.color=64B5F6) provided by the Material specs Color Tool. This way we can define many different color pallets easily, and not only the ones provided by the [500] weight.

**Comment by Piinks** [comment]
I've come across this in reviewing older issues in the backlog. I am going to de-dupe it to https://github.com/flutter/flutter/issues/36624.
Please let us know if you feel that issue does not reflect this one. Thank you!
