### ISSUE TITLE
No implementation found for method signInWithCredential on channel plugins.flutter.io/firebase_auth

### ISSUE THREAD

**Issue by manthan37** [flutter/flutter#28874]
I got this issue while sign in on ios device. Please help to sort out this one.

**Comment by Piinks** [comment]
Hi @manthan37,
Thanks for reaching out! 
To look into this issue, we would need the output of `flutter doctor -v` as well as a minimal code example that reproduces the problem.

**Comment by applehong5013** [comment]
@manthan37 Same with me

**Comment by silaspedrosa** [comment]
@manthan37 try using this code for the `AppDelegate.m` file for iOS:

```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"

@import UIKit;
@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure];
  [GeneratedPluginRegistrant registerWithRegistry:self];
  return [super application:application didFinishLaunchingWithOptions:launchOptions]; // YES;
}
@end
```

**Comment by Selo4J** [comment]
well done, this solved my problem.

**Comment by SherifElNayad** [comment]
> @manthan37 try using this code for the `AppDelegate.m` file for iOS:
> 
> ```
> #include "AppDelegate.h"
> #include "GeneratedPluginRegistrant.h"
> 
> @import UIKit;
> @import Firebase;
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application
> didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>   [FIRApp configure];
>   [GeneratedPluginRegistrant registerWithRegistry:self];
>   return [super application:application didFinishLaunchingWithOptions:launchOptions]; // YES;
> }
> @end
> ```
My file is a swift type not .m

**Comment by Nturibi** [comment]
@SherifElNayad did you get a solution?

**Comment by SherifElNayad** [comment]
Oh Yes i did , thank you

**Comment by scorchy38** [comment]
> @manthan37 try using this code for the `AppDelegate.m` file for iOS:
> 
> ```
> #include "AppDelegate.h"
> #include "GeneratedPluginRegistrant.h"
> 
> @import UIKit;
> @import Firebase;
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application
> didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>   [FIRApp configure];
>   [GeneratedPluginRegistrant registerWithRegistry:self];
>   return [super application:application didFinishLaunchingWithOptions:launchOptions]; // YES;
> }
> @end
> ```

There is no such file. There is AppDelegate.swift. Can u tell what changes are to be made there?
or any other method to solve this problem. I am new to flutter and this is really frustrating me.
