### ISSUE TITLE
webview_flutter target _blank is not working

### ISSUE THREAD

**Issue by RazaGR** [flutter/flutter#28875]
I am using `webview_flutter 0.3.3+1`, my initialUrl loads fine, It contains various links, when clicking on a link it navigates properly but if a link has target set to _BLANK,  it doesn't do anything.

    WebView(
          initialUrl: 'https://SOME_URL',
          javascriptMode: JavascriptMode.unrestricted,
    )

This Works

    <a href="http://example.com">Link A</a>

below doesn't work, it should open external browser but click doesn't take anywhere

    <a href="http://example.com" target="_BLANK">Link B</a>

**Comment by TigPT** [comment]
I also have this problem.

**Comment by SachaHerszkorn** [comment]
Any update on this ?

**Comment by jyp334** [comment]
I have same question.

**Comment by rnitta** [comment]
I have encountered this problem too.

FYI: https://github.com/fluttercommunity/flutter_webview_plugin/pull/276

**Comment by sibe7691** [comment]
I have solved this in https://github.com/sibe7691/plugins/commit/92732f37949101e50796fb047c9c77a4cf5986c7

Please let me know if it works for you and ill send a PR.

**Comment by rodruiz** [comment]
@sibe7691, did you submit a PR with your code? How can we use that code?
Thanks.

**Comment by rodruiz** [comment]
@sibe7691, confirmed your code is working as expected.
Thanks!

**Comment by amirh** [comment]
Fixed in flutter/plugins#2500 which is available on webview_flutter v0.3.19+6

**Comment by h2jose** [comment]
In my fresh instalation:
**flutter 2.0.4**
 **webview_flutter: ^2.0.3** 
 The _blank target attribute links stopped working, open right the link but in mode _self. Any reason?
