### ISSUE TITLE
Rename KeyboardService and RawKeyboardService

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#2887]
The current names are confusingly similar.  I would suggest the following replacements:

KeyboardService => TextInputService
RawKeyboardService => KeyEventService

The distinction is that the first service provides a high level API for acquiring chunks of text from the user, which might not come from a literal keyboard (e.g. voice input). The second service provides an API for routing key events, which also might not come from a literal keyboard (e.g. remote controls, or dashboard panels).

**Comment by abarth** [comment]
I've stuck with RawKeyboard for the low-level key events.  The slightly pejorative name is to nudge people towards the text input service.

I'll probably do the KeyboardService => TextInput rename when I get to that point through.

**Comment by krisgiesing** [comment]
I still think it shouldn't be Keyboard though since events won't necessarily come from a keyboard. How about RawKeyEventService?

**Comment by abarth** [comment]
> I still think it shouldn't be Keyboard though since events won't necessarily come from a keyboard. How about RawKeyEventService?

Yeah, keyboard is a bit of a misnomer, but I'm not sure that subtly is worth uglifying the name over.

**Comment by abarth** [comment]
TextInput is in https://github.com/flutter/flutter/commit/2cfc040572c9dbc075ab037b6d04f9699b099d75

Still need to migrate clients and remove the old interface.

**Comment by abarth** [comment]
Done.
