### ISSUE TITLE
Flutter does not call `dispose` after android application exit

### ISSUE THREAD

**Issue by guzishiwo** [flutter/flutter#28879]
Hello I just found that Flutter will not call widget's `dispose` method after android application exit. So I can not cancel the `Timer` object I created, If I quit and re-enter the application again, there will be another `Timer` object created.

Now both `Timer` object are running, and I can not do anything on it.

## Steps to Reproduce

1. use codes bellow
2. build and run the app
3. press `back` button on android phone
4. re-enter the app
5. see the log, it will show both `Timer` object are running.

``` dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Demo(),
      ),
    );
  }
}

class Demo extends StatefulWidget {
  @override
  _DemoState createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  Timer _timer;
  int _count = 0;
  
  @override
  void initState() {
    _timer = Timer.periodic(Duration(seconds: 1), (timer) {
      debugPrint('tick. timer id: ${_timer.hashCode} count: $_count');
      setState(() {
        _count++;
      });
    });
    super.initState();
  }
  
  @override
  void dispose() {
    debugPrint('disposed...');
    _timer?.cancel();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Container(child: Text('$_count seconds.'));
  }
}

```

## Logs

```
Launching lib/main.dart on A0001 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device A0001...
I/Choreographer(26990): Skipped 82 frames!  The application may be doing too much work on its main thread.
D/FA      (26990): Connected to remote service
V/FA      (26990): Processing queued up service tasks: 4
I/flutter (26990): tick. timer id: 709499887 count: 0
I/flutter (26990): tick. timer id: 709499887 count: 1
I/flutter (26990): tick. timer id: 709499887 count: 2
I/flutter (26990): tick. timer id: 709499887 count: 3
I/flutter (26990): tick. timer id: 709499887 count: 4
V/FA      (26990): Inactivity, disconnecting from the service
I/flutter (26990): tick. timer id: 709499887 count: 5
I/flutter (26990): tick. timer id: 709499887 count: 6
I/flutter (26990): tick. timer id: 709499887 count: 7
I/flutter (26990): tick. timer id: 709499887 count: 8
I/flutter (26990): tick. timer id: 709499887 count: 9
I/flutter (26990): tick. timer id: 709499887 count: 10
I/flutter (26990): tick. timer id: 709499887 count: 11
I/flutter (26990): tick. timer id: 709499887 count: 12
I/flutter (26990): tick. timer id: 709499887 count: 13
V/FA      (26990): Recording user engagement, ms: 15764
V/FA      (26990): Connecting to remote service
V/FA      (26990): Activity paused, time: 592445181
D/FA      (26990): Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=15764, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=8511900614029532923}]
V/FA      (26990): Connection attempt already in progress
D/FA      (26990): Connected to remote service
V/FA      (26990): Processing queued up service tasks: 2
I/flutter (26990): tick. timer id: 709499887 count: 14
I/flutter (26990): tick. timer id: 709499887 count: 15
I/flutter (26990): tick. timer id: 709499887 count: 16
V/FA      (26990): onActivityCreated
E/flutter (26990): [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
E/flutter (26990): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
V/FA      (26990): Activity resumed, time: 592448104
I/flutter (26990): tick. timer id: 709499887 count: 17
I/flutter (26990): tick. timer id: 709499887 count: 18
I/flutter (26990): tick. timer id: 709499887 count: 19
I/flutter (26990): tick. timer id: 366485841 count: 0    !!!! new timer created !!!!
I/flutter (26990): tick. timer id: 709499887 count: 20   !!!!! and old one still alive !!!!!
I/flutter (26990): tick. timer id: 366485841 count: 1
I/flutter (26990): tick. timer id: 709499887 count: 21
I/flutter (26990): tick. timer id: 366485841 count: 2
V/FA      (26990): Inactivity, disconnecting from the service
I/flutter (26990): tick. timer id: 709499887 count: 22
I/flutter (26990): tick. timer id: 366485841 count: 3
I/flutter (26990): tick. timer id: 709499887 count: 23
I/flutter (26990): tick. timer id: 366485841 count: 4
I/flutter (26990): tick. timer id: 709499887 count: 24
I/flutter (26990): tick. timer id: 366485841 count: 5
I/flutter (26990): tick. timer id: 709499887 count: 25
I/flutter (26990): tick. timer id: 366485841 count: 6
I/flutter (26990): tick. timer id: 709499887 count: 26
I/flutter (26990): tick. timer id: 366485841 count: 7
I/flutter (26990): tick. timer id: 709499887 count: 27
I/flutter (26990): tick. timer id: 366485841 count: 8
I/flutter (26990): tick. timer id: 709499887 count: 28
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-CN)
    • Flutter version 1.2.1 at /Users/xxxx/Library/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • ONEPLUS A3010 • 3460a357 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 4 categories.

```

**Comment by anderha** [comment]
Same problem for me. I'd like to close my database on exiting the app. Unfortunately dispose() is not called.

**Comment by surrenderios** [comment]
Add FlutterViewController to iOS  app, When enter in flutter page and back. FlutterViewController called dealloc but flutter page do not call dispose.

**Comment by EdwynZN** [comment]
I'm facing the same issue when trying to close my database. As the sqflite method close() is a future I think it doesn't wait it to close and retrieve an error log after I exit my app "a resource failed to close".

**Comment by melwinlobo18** [comment]
I guess I'm a bit late for answering this. Even I was facing the same issue when I created a normal constructor. So I created a Singleton and now it works fine. I've included the code snippet below.

```dart
import 'dart:async';

class MySingleton {
  static final MySingleton _instance = MySingleton._internal();
  factory MySingleton() => _instance;

  MySingleton._internal() {
    // init things inside this
    int counter = 0;
    Timer.periodic(Duration(seconds: 1), (timer) {
      counter++;
      print(counter);
    });
  }
}
```

**Comment by devhci** [comment]
@guzishiwo have you found any solution ?

**Comment by zhouyangyng** [comment]
> Add FlutterViewController to iOS app, When enter in flutter page and back. FlutterViewController called dealloc but flutter page do not call dispose.

I have the same proble with you on iOS app.

**Comment by zhouyangyng** [comment]
> I guess I'm a bit late for answering this. Even I was facing the same issue when I created a normal constructor. So I created a Singleton and now it works fine. I've included the code snippet below.
> 
> ```dart
> import 'dart:async';
> 
> class MySingleton {
>   static final MySingleton _instance = MySingleton._internal();
>   factory MySingleton() => _instance;
> 
>   MySingleton._internal() {
>     // init things inside this
>     int counter = 0;
>     Timer.periodic(Duration(seconds: 1), (timer) {
>       counter++;
>       print(counter);
>     });
>   }
> }
> ```

Have you solve the dispose problem by Singleton ?

**Comment by zhouyangyng** [comment]
> > I guess I'm a bit late for answering this. Even I was facing the same issue when I created a normal constructor. So I created a Singleton and now it works fine. I've included the code snippet below.
> > ```dart
> > import 'dart:async';
> > 
> > class MySingleton {
> >   static final MySingleton _instance = MySingleton._internal();
> >   factory MySingleton() => _instance;
> > 
> >   MySingleton._internal() {
> >     // init things inside this
> >     int counter = 0;
> >     Timer.periodic(Duration(seconds: 1), (timer) {
> >       counter++;
> >       print(counter);
> >     });
> >   }
> > }
> > ```
> 
> Have you solved the dispose problem by Singleton ?

**Comment by Hixie** [comment]
I don't understand how this is possible. initState shouldn't get called again when you come back.

**Comment by niceguy1** [comment]
for me ever since i used the timer without disposing it in a specific app, every app i run i get all previous build logs printed out, currently i need to type "flutter logs -c" before every build in order to clean the logs. @Hixie does it even make sense?

**Comment by tomasbaran** [comment]
Hey @guzishiwo You closed the issue but I don't know how you solved the issue. Can you please share?

**Comment by tomasbaran** [comment]
I have a slightly different problem but it may be related:



```
Timer _checkNewMinute;

checkAndUpdateCurrentAngle() {
    DateTime lastLoadingTime = DateTime.now();
    Duration checkingFrequency = Duration(seconds: 1);

    _checkNewMinute.periodic(checkingFrequency, (timer) {
      //print(DateTime.now());
      if (DateTime.now().minute != lastLoadingTime.minute) {
        lastLoadingTime = DateTime.now();
        //print('updating...');
        setState(() {
          currentCity.computeCurrentAngle();
        });
      }
    });
  }
```


And it gives me this error:
<img width="1307" alt="Captura de pantalla 2020-04-27 a las 16 20 34" src="https://user-images.githubusercontent.com/25743901/80389615-3052c900-88a3-11ea-8457-0a7b1267e80c.png">

**Comment by tomasbaran** [comment]
Sorry, my bad. I got the error now.

I should have written 

`_checkNewMinute = Timer.periodic`

instead of 

`_checkNewMinute`

But that still doesn't answer my question. Is this issue really closed? Does Dart disposes the Flutter now? How can I double-check on my end? Can anyone give a novice developer some easy steps to follow on how to check whether my functions have been disposed?

Thanks :)

**Comment by pav3lo** [comment]
> > I guess I'm a bit late for answering this. Even I was facing the same issue when I created a normal constructor. So I created a Singleton and now it works fine. I've included the code snippet below.
> > ```dart
> > import 'dart:async';
> > 
> > class MySingleton {
> >   static final MySingleton _instance = MySingleton._internal();
> >   factory MySingleton() => _instance;
> > 
> >   MySingleton._internal() {
> >     // init things inside this
> >     int counter = 0;
> >     Timer.periodic(Duration(seconds: 1), (timer) {
> >       counter++;
> >       print(counter);
> >     });
> >   }
> > }
> > ```
> 
> Have you solved the dispose problem by creating Singleton ?

Yep, you can call singleton().dispose()

`import 'dart:async';

class MySingleton {
  Timer _timer;
  get timer=>_timer;
  dispose() => _timer.dispose();

  static final MySingleton _instance = MySingleton._internal();
  factory MySingleton() => _instance;

  MySingleton._internal() {
    // init things inside this
    int counter = 0;
    _timer = Timer.periodic(Duration(seconds: 1), (timer) {
      counter++;
      print(counter);
    });
  }
}`
and you can call MySingleton.dispose() from main dispose() widget method.
