### ISSUE TITLE
flutter.io ==> flutter.dev

### ISSUE THREAD

**Issue by awazgyawali** [flutter/flutter#28887]
This might not be important but felt it needs a change. The url of the main site on the github repo description.
<img width="889" alt="screen shot 2019-03-05 at 7 58 36 pm" src="https://user-images.githubusercontent.com/10810343/53811383-59b6e400-3f81-11e9-88c8-c48b65d4e20b.png">

**Comment by Piinks** [comment]
Thanks for pointing this out! I am going to close this issue as it has been resolved. 😊
