### ISSUE TITLE
flutter webview keyboard cannot show up

### ISSUE THREAD

**Issue by sinpobox** [flutter/flutter#28883]
I tried to integrate the webview plugin in the flutter app. After adding the code in the example, the page loads normally, but when I click on the input box in the page, no soft keyboard pops up, who can help me?

**Comment by yb1994917** [comment]
i have the same question

**Comment by videoBroadcasting** [comment]
I have the same solution now.
Do you have got any solution?

**Comment by gdamjan** [comment]
duplicate of https://github.com/flutter/flutter/issues/19718?

**Comment by sinpobox** [comment]
Use flutter_webview_plugin plugin instead, it work

**Comment by vivekanandasuggu** [comment]
WebView(
          initialUrl: url,
          onWebViewCreated: (WebViewController webViewController) {
         
  },

          javascriptMode: JavascriptMode.unrestricted,
          onPageFinished: (currentUrlloading){
       },
));

I am using the latest flutter webview 0.3.4 but not able to open the keyboard for the input.Please let me know anyone have a solution for the issue.

**Comment by Swooshhh** [comment]
@vivekanandasuggu it's something to do with flutter, WebView is not a viable option until it's fixed(works fine in iOS). Recommend you to use flutter_ webview_pluggin.

**Comment by vivekanandasuggu** [comment]
Hey Thankyou Swooshhh I was actually trying to catch certain url and after getting the matching url I want to move, to another screen but that's not happening this is my code 

flutterWebviewPlugin.onUrlChanged.listen((String urlUpdated){
             changedurl=urlUpdated;
             print(changedurl);
             if(changedurl.contains("?code"))
               {
                 flutterWebviewPlugin.stopLoading();
                 flutterWebviewPlugin.close();
                 Navigator.push(context, MaterialPageRoute(builder: (context) => ServiceLogs()));
               }
    });

**Comment by Swooshhh** [comment]
Sorry for the late reply, did you figure it out? If not could you please state the error you get when executing the code.

**Comment by vivekanandasuggu** [comment]
Not getting any specific error but my debugger is going to the line  Navigator.push(context, MaterialPageRoute(builder: (context) => ServiceLogs())) but not able to render that screen.

**Comment by Swooshhh** [comment]
Make sure you use your plugins in the initState and I recommend you to handle the conditions in your build method.
initstate:
flutterWebviewPlugin.onUrlChanged.listen((String urlUpdated){
setState((){
changedurl=urlUpdated;
print(changedurl);
});
});

build:
if(changedurl.contains("?code"))
{
Navigator.push(context, MaterialPageRoute(builder: (context) => ServiceLogs()));
}
