### ISSUE TITLE
Problems with graphics 

### ISSUE THREAD

**Issue by janfryauf** [flutter/flutter#28889]
Hello,

We deployed our app to TestFlight and this is what happend when opened for the first time:
![53385634_2070445526376740_6396405450023108608_n](https://user-images.githubusercontent.com/26898549/53813232-6fb2ad80-3f5d-11e9-9d29-1d12696c1d42.jpg)
I only saw this issue on **iPhone X** for now (two different phones though)
This never happened while programming locally (simulator or real device) so I can't give you any steps to reproduce it.
It's happening only when the app is opened for the first time (also when the app is killed and run again). Sometimes it stays like this and then it's enough to touch/swipe screen and everything is normal and sometimes it just flashes for like half a second and then everything is alright.

## Logs

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
```

**Comment by caffo** [comment]
Having the same problem here.

**Comment by caffo** [comment]
@janfryauf seems to be solved on beta channel.

**Comment by iapicca** [comment]
Hi @janfryauf 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/21403)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
