### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

### ISSUE THREAD

**Issue by yash365** [flutter/flutter#28880]
Getting the below error :
	PS E:\PROJECTS\Flutter Projects\Signature\signature_view_new> flutter run
	Launching lib/main.dart on Nokia 8 1 in debug mode...             162.4s (!)
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
	registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
	D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\2.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\3.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\4.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\5.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\6.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\7.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\8.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\9.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\10.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\11.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\12.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\13.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\14.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\15.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\16.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\17.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\18.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\19.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\20.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\21.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\22.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\23.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\24.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\25.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\26.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\27.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\28.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\29.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\30.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\31.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\32.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\33.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\34.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\35.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\36.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\37.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\38.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\39.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\40.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\41.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\42.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\43.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\44.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\45.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\46.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\47.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\48.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\49.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\50.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\51.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\52.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\53.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\54.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\55.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\56.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\57.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\58.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\59.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\60.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\61.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\62.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\63.jar, E:\PROJECTS\Flutter Projects\Signature\signature_view_new\build\app\intermediates\transforms\dexBuilder\debug\64.jar
	  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
	  Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 1m 51s
	Running Gradle task 'assembleDebug'...
	Running Gradle task 'assembleDebug'... Done                       113.8s
	*******************************************************************************************
	The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
	See https://goo.gl/CP92wY for more information on the problem and how to fix it.
	*******************************************************************************************
	Gradle task assembleDebug failed with exit code 1

**pubspec.yaml(dependencies)**
	dependencies:
	  flutter:
		sdk: flutter

	  cupertino_icons: ^0.1.2
	  image_picker_saver: ^0.1.0
	  fluttertoast: ^2.0.0
	  flutter_colorpicker: 
	  firebase_storage: ^1.0.4
	  esys_flutter_share: ^0.0.9

	dev_dependencies:
	  flutter_test:
		sdk: flutter

**build.gradle(android module)**
	buildscript {
		repositories {
			google()
			jcenter()
		}

		dependencies {
			classpath 'com.android.tools.build:gradle:3.2.1'
			classpath 'com.google.gms:google-services:4.0.1'
		}
	}

	allprojects {
		repositories {
			google()
			jcenter()
		}
	}

	rootProject.buildDir = '../build'
	subprojects {
		project.buildDir = "${rootProject.buildDir}/${project.name}"
	}
	subprojects {
		project.evaluationDependsOn(':app')
	}

	task clean(type: Delete) {
		delete rootProject.buildDir
	}
	// solving error
	// subprojects {
	//     project.configurations.all {
	//         resolutionStrategy.eachDependency { details ->
	//             if (details.requested.group == 'com.android.support'
	//                     && !details.requested.name.contains('multidex') ) {
	//                 details.useVersion "27.1.0"
	//             }
	//         }
	//     }
	// }

	configurations.all {
		resolutionStrategy.eachDependency { DependencyResolveDetails details ->
			def requested = details.requested
			if (requested.group == 'com.android.support' && requested.name != 'multidex') {
				details.useVersion "${rootProject.ext.supportLibVersion}"
			}
		}
	}

**build.gradle(app module):**
	def localProperties = new Properties()
	def localPropertiesFile = rootProject.file('local.properties')
	if (localPropertiesFile.exists()) {
		localPropertiesFile.withReader('UTF-8') { reader ->
			localProperties.load(reader)
		}
	}

	def flutterRoot = localProperties.getProperty('flutter.sdk')
	if (flutterRoot == null) {
		throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
	}

	def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
	if (flutterVersionCode == null) {
		flutterVersionCode = '1'
	}

	def flutterVersionName = localProperties.getProperty('flutter.versionName')
	if (flutterVersionName == null) {
		flutterVersionName = '1.0'
	}

	apply plugin: 'com.android.application'
	apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

	android {
		compileSdkVersion 28

		lintOptions {
			disable 'InvalidPackage'
		}

		configurations.all {
			resolutionStrategy.force 'com.android.support:support-compat:27.1.0'
			resolutionStrategy.force 'com.android.support:appcompat-v7:27.1.0'
			resolutionStrategy.force 'com.android.support:support-v4:27.1.0'
		}

		defaultConfig {
			// TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
			applicationId "com.example.signatureviewnew"
			minSdkVersion 21
			targetSdkVersion 28
			versionCode flutterVersionCode.toInteger()
			versionName flutterVersionName
			testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
			multiDexEnabled true
		}

		buildTypes {
			release {
				// TODO: Add your own signing config for the release build.
				// Signing with the debug keys for now, so `flutter run --release` works.
				signingConfig signingConfigs.debug
			}
		}
	}

	flutter {
		source '../..'
	}

	dependencies {
		testImplementation 'junit:junit:4.12'
		androidTestImplementation 'com.android.support.test:runner:1.0.2'
		androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
		implementation 'com.android.support:multidex:1.0.3'
		//implementation 'com.google.firebase:firebase-core:16.0.1'   // firebase
	}

	apply plugin: 'com.google.gms.google-services'

**gradle.properties:**
	org.gradle.jvmargs=-Xmx1536M
	android.useAndroidX = true
	android.enableJetifier = false

**My code 
main.dart:**
	import 'dart:async';
	import 'dart:io';
	import 'dart:typed_data';
	import 'dart:ui' as ui;
	import 'package:flutter/material.dart';
	import 'package:flutter/rendering.dart';
	import 'package:signature_view_new/signature.dart';
	import 'package:image_picker_saver/image_picker_saver.dart';
	import "package:fluttertoast/fluttertoast.dart";

	import 'package:flutter_colorpicker/flutter_colorpicker.dart';
	import 'package:firebase_storage/firebase_storage.dart';
	import 'package:esys_flutter_share/esys_flutter_share.dart';

	void main() => runApp(MaterialApp(
		  home: SignatureView(),
		  debugShowCheckedModeBanner: false,
		));

	Color _currentColor = Color(0xff443a49);

	ValueChanged<Color> onColorChanged;

	class SignatureView extends StatefulWidget {
	  _SignatureViewState createState() => _SignatureViewState();
	}

	class _SignatureViewState extends State<SignatureView> {
	  static GlobalKey previewContainer = new GlobalKey();
	  List<Offset> _points = <Offset>[];
	  var filePath;
	  String downloadPath;

	  // set the changed color to a variable
	  changeColor(Color color) => setState(() => _currentColor = color);

	  @override
	  Widget build(BuildContext context) {
		return Scaffold(
		  body: RepaintBoundary(
			key: previewContainer,
			child: Container(
			  //width: double.infinity,
			  //color: Colors.white,
			  decoration: BoxDecoration(
				  image: DecorationImage(
					  image: AssetImage("assets/angry.png"), fit: BoxFit.cover)),
			  child: GestureDetector(
				onPanUpdate: (DragUpdateDetails details) {
				  setState(() {
					RenderBox object = context.findRenderObject();
					Offset _localPosition =
						object.globalToLocal(details.globalPosition);
					_points = List.from(_points)..add(_localPosition);
				  });
				},
				onPanEnd: (DragEndDetails details) => _points.add(null),
				child: CustomPaint(
				  painter: Signature(points: _points, changedColor: _currentColor),
				  size: Size.infinite,
				),
			  ),
			),
		  ),
		  floatingActionButton: Wrap(
			children: <Widget>[
			  Stack(
				children: <Widget>[
				  Row(
					mainAxisAlignment: MainAxisAlignment.end,
					children: <Widget>[
					  //share txt
					  FloatingActionButton(
						tooltip: "Share button",
						child: Icon(Icons.share),
						onPressed: _shareText,
					  ),
					  Padding(
						padding: const EdgeInsets.all(5.0),
					  ),
					  // screen-shot and upload image
					  FloatingActionButton(
						tooltip: "Take the screenshot and upload it",
						child: Icon(Icons.file_upload),
						onPressed: _takeScreenShot,
					  ),
					  Padding(
						padding: const EdgeInsets.all(5.0),
					  ),
					  // clear icon
					  FloatingActionButton(
						  tooltip: "Clear the drawing",
						  child: Image.asset(
							"assets/eraser.png",
							width: 70.0,
							height: 70.0,
						  ),
						  onPressed: () {
							_points.clear();
							toastMsg("Tap on the screen to clear");
						  }),
					  Padding(
						padding: const EdgeInsets.all(5.0),
					  ),
					  FloatingActionButton(
						tooltip: "Choose your color",
						child: Icon(Icons.brush),
						onPressed: colorPickerDialog,
					  ),
					],
				  ),
				],
			  )
			],
		  ),
		);
	  }

	  Future colorPickerDialog() {
		var colorPicker;

		colorPicker = showDialog(
		  context: context,
		  builder: (BuildContext context) {
			return AlertDialog(
			  titlePadding: const EdgeInsets.all(0.0),
			  contentPadding: const EdgeInsets.all(0.0),
			  content: SingleChildScrollView(
				child: ColorPicker(
				  pickerColor: _currentColor,
				  onColorChanged: changeColor,
				  colorPickerWidth: 1000.0,
				  pickerAreaHeightPercent: 0.7,
				  enableAlpha: true,
				),
			  ),
			);
		  },
		);

		print("inside colorPickerDialog");
		return colorPicker;
	  }

	  Future _takeScreenShot() async {
		RenderRepaintBoundary boundary =
			previewContainer.currentContext.findRenderObject();
		ui.Image image = await boundary.toImage();
		ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
		Uint8List pngBytes = byteData.buffer.asUint8List();
		print(pngBytes);

		// upload to firebase storage
		final StorageReference firebaseStorageRef =
		  FirebaseStorage.instance.ref().child('1122/screenshot.jpg');
		final StorageUploadTask uploadTask =
		  firebaseStorageRef.putData(pngBytes);

		String downloadUrl = await (await uploadTask.onComplete).ref.getDownloadURL();
		String url = downloadUrl.toString();
		print(url);

		setState(() {
		  downloadPath = url;
		});

		filePath = await ImagePickerSaver.saveFile(fileData: pngBytes);
		toastMsg("Saved on ${filePath.toString()}");
		print(filePath);

		print("inside _takeScreenShot");
	  }

	  toastMsg(String msg) {
		var toast = Fluttertoast.showToast(
			msg: "$msg",
			toastLength: Toast.LENGTH_SHORT,
			gravity: ToastGravity.BOTTOM,
			timeInSecForIos: 3,
			backgroundColor: Colors.red,
			textColor: Colors.white,
			fontSize: 16.0);

		print("inside toastMsg");
		return toast;
	  }

	  Future _shareText() async {
		try {
		  await EsysFlutterShare.shareText(
			  downloadPath, 'ScreenShot');
		} catch (e) {
		  print('error: $e');
		}
	  }
	}

signature.dart:
	import 'package:flutter/material.dart';

	class Signature extends CustomPainter{
	  List<Offset> points;
	  Color changedColor;

	  Signature({this.points, this.changedColor});

	  @override
	  void paint(Canvas canvas, Size size) {
		Paint paint = Paint()
		  ..color = changedColor
		  ..strokeCap = StrokeCap.round
		  ..strokeWidth = 10.0;

		  for(int i = 0; i < points.length -1; i++){
			if(points[i] != null && points[i+1] != null){
			  canvas.drawLine(points[i], points[i+1], paint);
			}
		  }
	  }

	  @override
	  bool shouldRepaint(Signature oldDelegate) => oldDelegate.points != points;
	}

**Comment by NeroJz** [comment]
Same here.  For my case, it works after I commenting out permission_handler (^3.0.0) and
  imei_plugin (1.1.0) plugin. Any suggestion?

**Comment by yash365** [comment]
i have not used permission_handler and imei_plugin plugin in my project

**Comment by iapicca** [comment]
Hi @yash365 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you
