### ISSUE TITLE
url_launcher: canLaunch / launch don't work on iOS for simple URL scheme

### ISSUE THREAD

**Issue by zarko-tg** [flutter/flutter#28885]
url_launcher is basically not working at all in the iOS simulator (12.1 for example) for simple URL schemes.

## Steps to Reproduce

1. Create project using "Flutter: New Project" in VS Code.
2. Installed plugin following https://pub.dartlang.org/packages/url_launcher#-installing-tab-
3. Hook any button to call:
```
const url = 'contacts://';
if (await canLaunch(url)) {
  await launch(url);
} else {
  print('Could not launch $url');
}
```
4. Run it in an iOS simulator.

## Logs

```
flutter: Could not launch contacts://
```

[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-NO)
    • Flutter version 1.2.1 at /Users/batman/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/batman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/batman/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone 6 • 64E6EFDE-B6C1-43A2-A58E-9F9FD417C69F • ios • iOS 12.1 (simulator)

**Comment by zarko-tg** [comment]
It turned out to be a simple configuration case, applicable to both iOS simulator and real device. One needs to specify which schemes the app can query/launch, such as:
```
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>youtube</string>
  <string>...</string>
</array>
```
**Sadly this crucial guidance is missing in the plugin documentation afaik.**

**Comment by ArtfulDodgerB92** [comment]
What does this even mean?    Where do you add this code?

**Comment by ArtfulDodgerB92** [comment]
> It turned out to be a simple configuration case, applicable to both iOS simulator and real device. One needs to specify which schemes the app can query/launch, such as:
> 
> ```
> <key>LSApplicationQueriesSchemes</key>
> <array>
>   <string>youtube</string>
>   <string>...</string>
> </array>
> ```
> 
> **Sadly this crucial guidance is missing in the plugin documentation afaik.**

What does this even mean? Where do you add this code?

**Comment by zarko-tg** [comment]
@ArtfulDodgerB92 In Info.plist.

**Comment by Marwan-Mostafa7** [comment]
> @ArtfulDodgerB92 In Info.plist.

What to write then to make a call
`<string>call</string>` ??

**Comment by hectorvillag** [comment]
> > @ArtfulDodgerB92 In Info.plist.
> 
> What to write then to make a call
> `<string>call</string>` ??
> for `launch("tel://" + phoneNum);`
> 
> it turned out to be `tel`

I think that instead of tel you should use call

**Comment by andersonmendesdev** [comment]
Even with this setting in info.plist my whatsapp does not open on iOS (physical device, production version), but also does not return any error messages.

url_lancher: 5.2.5

**Comment by andersonmendesdev** [comment]
> Acabou sendo um caso de configuração simples, aplicável ao simulador iOS e ao dispositivo real. É necessário especificar quais esquemas o aplicativo pode consultar / iniciar, como:
> 
> ```
> <key>LSApplicationQueriesSchemes</key>
> <array>
>   <string>youtube</string>
>   <string>...</string>
> </array>
> ```
> 
> **Infelizmente, esta orientação crucial está ausente na documentação do plugin.**

Even with this setting in info.plist my whatsapp does not open on iOS (physical device, production version), but also does not return any error messages.
url_lancher: 5.2.5

**Comment by jcsena** [comment]
@andersonmendesdev did you find any solutions ?

**Comment by andersonmendesdev** [comment]
> @andersonmendesdev did you find any solutions ?

@jcsena  With the official plugin I have not found a solution yet.

**Comment by jcsena** [comment]
I found a solution here  https://github.com/flutter/flutter/issues/45156#issuecomment-557058460 
@andersonmendesdev, thanks.

**Comment by Simon-the-Shark** [comment]
I had similar problem and it turned out, that on iOS  can't be space between 'tel:' and the number. 
e.g. "tel: 123456789" is working on android, but it doesn't working on iOS. Using "tel:123456789" fixed the issue.
