### ISSUE TITLE
flutter:services/fetch and flutter:http are redundant with each other

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2889]

**Comment by abarth** [comment]
Yeah, I tried to remove fetch but it gives you the underlying data pipe, which you can't get from http.dart yet.

**Comment by Hixie** [comment]
The funniest part is that fetch uses http's networkService...

**Comment by sethladd** [comment]
Thank you for cleaning this up! :)

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/3163
