### ISSUE TITLE
Make flutter upgrade handle hotfixes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#28898]
We believe (though this is untested) that `flutter upgrade` will fail if it's not possible to fast-forward to the new state. This means it'll fail if we ever do a hot fix.

This is complicated by the way that we want to encourage people to make local changes to debug or work around bugs.

Proposed changes:

`flutter upgrade` should check to see if the current commit is a tag. If so, it should stash local changes (with a name like "flutter-upgrade-v1.1.1-to-v1.8.2), reset to the new state, and attempt to pop the stash. If the pop fails it should report it. If it's not a tagged commit it should fail. The failure should check the channel. If the channel is `master` or not a recognized branch name, then it should explain that to avoid the risk of destroying commits it has done nothing, and should encourage using `git` directly. If it's one of the recognized branch names it should explain that it is avoiding doing any damage but that if it's ok to remove local changes `flutter upgrade --force` can work around the issue.

`flutter upgrade --force` would bypass the check for a tag but otherwise work the same way. It would be documented as being dangerous if you have local commits.

cc @jonahwilliams @tvolkert @kf6gpe

**Comment by Hixie** [comment]
Since it looks like you're working on this now, I'm going to put it in the April milestone. Thanks!!

**Comment by jonahwilliams** [comment]
This was reverted because not all of the git versions on cirrus support stash pop

**Comment by jonahwilliams** [comment]
We've confirmed that the tool changes are sufficient to upgrade to/through hotfixes. The changes to the process to accommodate the required force-pushing are being tracked by @kf6gpe

**Comment by kf6gpe** [comment]
The process documentation has been updated with the necessary steps.
