### ISSUE TITLE
please update crashy; update sentry or better yet remove sentry dependence.

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#28890]
* https://github.com/flutter/crashy
* Sentry last updated Sep 2017, since that is before Flutter beta, flutter 1.0 and flutter 1.2 it is a 'turn-off' or concern.
* it uses sentry v 0.06 from sep 2017, current is jan 2019, past 1.0 to 2.2, mentions dart 1.0 past it, etc
* Making a sample of sentry and crashlytics at the same time is a bit confusing.
i thought it was referenced on flutter.io ...
Thanks

**Comment by bruno-garcia** [comment]
IMO this issue is resolved since both [sentry](https://github.com/flutter/sentry) plugin and [crashy](https://github.com/flutter/crashy) are up to date. I agree it's better not to have a sample at all if it's outdated but we'll commit into making sure it'll stay up to date from now on.

**Comment by bruno-garcia** [comment]
This issue is a year old and we're keeping things up-to-date now so closing this.
