### ISSUE TITLE
Explain what the engine is, in the README

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#289]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Tuesday Nov 10, 2015 at 02:35 GMT_
_Originally opened as https://github.com/flutter/engine/issues/2023_

----

It might help to use the README to explain what the engine is. That way, people filing issues might be better able to tell if they should file the issue in engine, or the repo named flutter.

Thanks!

**Comment by Hixie** [comment]
The repo named "engine" has no issues any more, so that problem is gone. But we should still probably do this.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/engine/blob/master/README.md is the file in question, and yes it probably wants to direct people to flutter/flutter since it's an implementation detail.
