### ISSUE TITLE
path_provider 0.5.0+1  Target of URI doesn't exist: 'package:path_provider/path_provider.dart'

### ISSUE THREAD

**Issue by BirdyF** [flutter/flutter#28902]
I used path_provider plugin since 2 weeks without problem.
I upgraded flutter today and now path_provider is not found anymore.

Target of URI doesn't exist: 'package:path_provider/path_provider.dart'

I ran flutter get packages after the upgrade with no success.

Please see below flutter doctor answer:
Flutter (Channel stable, v1.0.1-pre.2, on Mac OS X 10.13.6 17G3025, locale
    en-BE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

I am new to Flutter so maybe I am missing some commands after the flutter upgrade?

**Comment by BirdyF** [comment]
After flutter packages upgrade, I closed Visual Studio and opened it again and now the package can be seen!

Not sure what was the problem.
You can close the issue, as I have not found a way to reproduce it

**Comment by ClaudineiOlSantos** [comment]
I get same issue, the package can't be imported.

**Comment by ohjinjin** [comment]
Hi, Did you add path_provider in dependencies of pubspec.yaml?
