### ISSUE TITLE
Cant connect to storage.googleapis.com

### ISSUE THREAD

**Issue by davide1998** [flutter/flutter#28906]
When I run flutter packages get, I get the following output on the terminal:
ALSO: When I go to the flutter installation page, the link to the flutter sdk (MacOS) fails.

/../Desktop/code/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in spot-buddy...                 
OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50438
pub get failed (69) -- attempting retry 1 in 1 second...
OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50526
pub get failed (69) -- attempting retry 2 in 2 seconds...
OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50624
pub get failed (69) -- attempting retry 3 in 4 seconds...
OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50701
pub get failed (69) -- attempting retry 4 in 8 seconds...
OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50812
pub get failed (69) -- attempting retry 5 in 16 seconds...
OS Error: Operation timed out, errno = 60, address = storage.googleapis.com, port = 50906
pub get failed (69) -- attempting retry 6 in 32 seconds...

After running flutter analyze: 
Waiting for another flutter command to release the startup lock...

After running flutter doctor -v: 
Waiting for another flutter command to release the startup lock...

**Comment by jmagman** [comment]
Are you able to reach http://storage.googleapis.com/ in a browser?

**Comment by iapicca** [comment]
Hi @davide1998 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you
