### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by vijayredme** [flutter/flutter#28903]
Currently Tablet support is not acknowledged by Flutter. What is the reason behind it ? and are there any plans to do so in near future ?

**Comment by goderbauer** [comment]
Please follow https://github.com/flutter/flutter/issues/12310.

**Comment by vijayredme** [comment]
@goderbauer : Does that mean Tablet aware UI is supported by Flutter and if we find any issues during development those would be addressed by flutter team ?

**Comment by vijayredme** [comment]
@goderbauer : Can you please update me on my counter query ?
