### ISSUE TITLE
Add onChanged to TextFormField 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28914]
`TextFormField` doesn't have the `onChanged` that `TextField` has, using a `TextEditingController` can be much more complicated, specially when using the BLoC pattern, so adding a `onChanged` callback could simplify this a lot.

**Comment by gagaJay** [comment]
Agreed.

**Comment by feinstein** [comment]
They search for votes, not comments, so if you like this, give it a thumbs up 👍🏻

**Comment by NindoK** [comment]
Please make this!

**Comment by PoojaB26** [comment]
Any workaround around this for now?

**Comment by feinstein** [comment]
Yes, look into the docs, specially the cookbooks, you can use a controller and get the text from there.

(sorry if I don't provide any links, but I am at my phone and this should be easy to find out, if you can't, please let me know)

**Comment by PoojaB26** [comment]
Yes I understand about `controller.text` but I am trying to get the current value of TextFormField to use in my inputFormatters, and `controller.text` always shows blank there

**Comment by feinstein** [comment]
You can subscribe to text updates on the controller.
