### ISSUE TITLE
firebase_admob: ^0.8.0+3 crashes on app launch (Android). OS version 7.0

### ISSUE THREAD

**Issue by PreciousGabriel** [flutter/flutter#28913]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Purus** [comment]
Can you add more details on this issue? May be your logs, exception details and your doctor -v info.

**Comment by matte5031** [comment]
firebase_admob crashes on my android device aswell

**Comment by kf6gpe** [comment]
@PreciousGabriel @matte5031 Can you provide logs or other debugging information for us to root-cause this? Thanks!

**Comment by kroikie** [comment]
@PreciousGabriel

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1184. Any further collaboration will be done there.
