### ISSUE TITLE
Firestore write when app isn't at foreground

### ISSUE THREAD

**Issue by just-peteking** [flutter/flutter#28917]
I have an issue when updating data in Firestore, I have the latest version, all working great until the App is not in the foreground; i.e. not the current app displayed, it could be hidden by another app or the app (task switcher) is now open, waiting for the user to select another app that is open.

My periodic timer fires which is fantastic, I get the users location using the Geolocater plugin, all great, until the update to firestore. All works perfectly when the app is the current app the user is looking at, but if it isn't, the Firestore API refuses to do anything and throws no error that I can see.

```
         if (documentSnapshot.exists) {
            //compute(callback, message)
            Firestore.instance.runTransaction((transaction) async {
              await transaction.update(documentSnapshot.reference, dataArray);
            }).catchError((e) => print('error: ${e.error}'));
          } else {
            Firestore.instance.runTransaction((transaction) async {
              await transaction.set(documentSnapshot.reference, dataArray);
            }).catchError((e) => print('error: ${e.error}'));
          }
```

It's basic stuff like above, just in a timer, as above, works fine when the app is the current app, if not, code executes but doesn't update Firestore.

Are then any special permissions for this to work in Android and iOS, I'm just testing on an emulator at the moment, API 28.

**Comment by just-peteking** [comment]
In addition to this Firestore issue, I'm now using this package to spawn a real background task instead of a timer itself, as I thought perhaps the timer had any bearing on the Firestore package.

The background package I'm using is: https://pub.dartlang.org/packages/background_fetch

This is great, it fires and I get easily get the device location like I was previously via the Geolocater plugin, however, the same issue occurs. Firestore code I've mentioned in the previous post runs fine, no error, but no data is added.

It really does appear to be a massive issue with the Firestore plugin, it refuses to update if the app is either in the foreground or a background task. I'm guessing this is either very deliberate or a real bug.

**Comment by larssn** [comment]
There seems to be a lot of issues with `runTransaction`. We also ran into a situation where data didn't get updated: https://github.com/flutter/flutter/issues/28714

Pretty serious stuff.

**Comment by gustavobrian** [comment]
yes, is terrible... and restore for foregraund delay more 30seg... to recovery state proxy...

**Comment by escamoteur** [comment]
Hi, if thi still makes you problems, please file a new issue at the new home of all Firebase https://github.com/FirebaseExtended/flutterfire
