### ISSUE TITLE
Persian calendar

### ISSUE THREAD

**Issue by aminj4** [flutter/flutter#28926]
Hi guys 
I want a persian calendar 
but I want that calendar has week mood
I'll pleasure to help me
سلام دوستان من یک تقویمی میخوام که حالتی داشته باشه که بتونم به صورت هفتگی اون تقویم رو نمایش بدم
ممنون میشم کمکم کنین

**Comment by HansMuller** [comment]
Google translate says that the second half of your description is:

> Hi, my friends, I want a calendar that has a chance to show it on a weekly basis.
> Thank you for helping me

I'm afraid I'm not completely sure what you're asking for.  Are there Farsi translation mistakes for dates in https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/date_localizations.dart#L3842 ?

**Comment by aminj4** [comment]
> Google translate says that the second half of your description is:
> 
> > Hi, my friends, I want a calendar that has a chance to show it on a weekly basis.
> > Thank you for helping me
> 
> I'm afraid I'm not completely sure what you're asking for. Are there Farsi translation mistakes for dates in https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/lib/src/l10n/date_localizations.dart#L3842 ?

Hi friend, this package is good, but this package's not support shamsi date.
and thoese month not persian

**Comment by HansMuller** [comment]
Thanks for your feedback! I will forward your message to the localization team.

**Comment by aminj4** [comment]
Hi
Your welcome.
Excuse me  where are you from?

**Comment by HansMuller** [comment]
I'm part of the Flutter engineering team and we're in Mountain View, California.

**Comment by aminj4** [comment]
Very good
Nice to meet you
This package very useful for Persians but I have a problem
This package don’t support week mood

Sent from Mail for Windows 10

**Comment by HansMuller** [comment]
I've submitted an issue against the Dart intl package, which is where Flutter gets localizations related to dates: https://github.com/dart-lang/intl/issues/206

I'm going to close this issue. When https://github.com/dart-lang/intl/issues/206 is resolved the flutter_localization will pick up the changes automatically.
