### ISSUE TITLE
Add a GitHub presubmit that the flutter/plugins CI is green

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#28921]
Similar to the "flutter-build" indication we have on framework PRs.
It's too easy to not notice that the build is red when landing a PR.

**Comment by collinjackson** [comment]
I have a WIP change to do this (on cocoon).

**Comment by dotdoom** [comment]
Is this implemented already? I see PRs get red status if the dashboard on appengine is red (and it includes plugins).

**Comment by godofredoc** [comment]
@stuartmorgan is this something we still want to implement?

**Comment by stuartmorgan** [comment]
This was added at some point via https://github.com/apps/submit-queue.
