### ISSUE TITLE
We need clearer error message on production

### ISSUE THREAD

**Issue by kokizzu** [flutter/flutter#28923]
Instead of this, it would be nicer if the stack trace printed there just like on the log.
This error only happened on production, and we didn't know where's the view/code that causes this '__')
![image](https://user-images.githubusercontent.com/1061610/53856263-cecafd80-4003-11e9-8e68-aa7274a1de0a.png)

**Comment by escamoteur** [comment]
I recommend using something like Crashalytics or Sentry to get information from Apps in release.

**Comment by Hixie** [comment]
You can now override this widget to provide whatever effect you like.
