### ISSUE TITLE
Drag marker and get new position

### ISSUE THREAD

**Issue by ElHombreSinNombre** [flutter/flutter#28929]
In Flutter I have a map that take the device position with help of location plugin. Then i use this position to show marker in Google map with help of Google Maps Flutter plugin.

The code is similar to

```
child: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: CameraPosition(
          target: LatLng(lat, lng),
          zoom: 5,
        ),
        markers: Set<Marker>.of(
          <Marker>[
            Marker(
              draggable: true,
              markerId: MarkerId("1"),
              position: LatLng(lat, lng),
              icon: BitmapDescriptor.defaultMarker,
              infoWindow: const InfoWindow(
                title: 'Usted está aquí',
              ),
            )
          ],
        ),
        onMapCreated: (GoogleMapController controller) {
          mapController = controller;
        },
      ))
```

If _location_ plugin fails or take wrong data i need to have the option to reposition this marker. I use draggable: true to drag marker, but i need to take the new latitude and longitude for save it in database.

So the question is: Using the draggable how can i get the new latitude and longitude?

**Comment by wuilmerj24** [comment]
@ElHombreSinNombre 
Hi, have you been able to make a callback when doing drag?

**Comment by ElHombreSinNombre** [comment]
Yes, but take _old_  latitude and longitude. Doesn´t update update.

**Comment by wuilmerj24** [comment]
Como lo resolviste?

**Comment by ElHombreSinNombre** [comment]
No lo resolví aún

**Comment by xesun** [comment]
Hope it helps
`void _updatePosition(CameraPosition _position) {
    Position newMarkerPosition = Position(
        latitude: _position.target.latitude,
        longitude: _position.target.longitude);
    Marker marker = markers["1"];

    setState(() {
      markers["1"] = marker.copyWith(
          positionParam: LatLng(newMarkerPosition.latitude, newMarkerPosition.longitude));
    });
  }`

**Comment by duzenko** [comment]
Not good. We need a bridge to setOnMarkerDragListener

**Comment by duzenko** [comment]
When can we expect this PR to be reviewed?

**Comment by brux88** [comment]
are there any news?

**Comment by duzenko** [comment]
> 
> 
> are there any news?

Please consider starring the PR to hopefully expedite the process

**Comment by jawand** [comment]
for time being you guys can use this solution.
https://github.com/flutter/flutter/issues/26117#issuecomment-511723276

**Comment by DANIEL-ASHRAF** [comment]
just create variable and save the position in it 
in my case I need lng and lat only .
double lng;
  double lat;
  _handleTap(LatLng argument) {
    setState(() {
      myMarker=[];
      myMarker.add(
          Marker(
            markerId: MarkerId(argument.toString()),
            position: argument,
            draggable: true,
            onDragEnd: (dragEndPosition){
              lng=dragEndPosition.longitude;
              lat=dragEndPosition.latitude;
            }
          ));
      lng=argument.longitude;
      lat=argument.latitude;
    });
  }


GoogleMap(      markers:Set.from(myMarker),
                onTap: _handleTap,
              ),
