### ISSUE TITLE
ListTile leading width

### ISSUE THREAD

**Issue by ronniechew** [flutter/flutter#28924]
I'm trying to reduce the gap between leading and title, the leading width that I need is only about 10, but there seems to be no way for me to change this.

Tracing to the code in list_tile.dart, I can see this line:
`static const double _minLeadingWidth = 40.0;`

which seems to be what I wanted to change, but how do I change it without modifying the material source code?

**Comment by HansMuller** [comment]
When ListTile doesn't do exactly what you want it's usually easiest just to create your own similar widget based on Row, etc.  Would that work in this case?

**Comment by ronniechew** [comment]
I've uploaded an image to demonstrate my problem:
https://i.ibb.co/zf86xPQ/IMG-20190307-011102.jpg

I'm having a thin container (width: 8) within leading to show colours indicating the status of the list item. (Pretty common design in to-do apps or email client etc.) But once I use leading, it forcefully pushed the title to the right,  leaving quite a large empty area between them as seen in the screenshot. 

Maybe I can make do with Row widget like you suggested, but that's gonna change quite a bit of code here. Unfortunately I don't have the time to rework this part due to tight deadline. 

If there's a way to fix the gap for ListTile I'd really appreciate it. Otherwise I will have to leave it as is and perhaps rework using Row widget in future when time allows. Cheers.

**Comment by shihaohong** [comment]
As @HansMuller has suggested, I think the best course of action is to create your own implementation using a `Row` widget or something similar. `ListTile` is meant to adhere to the [material implemetation](https://material.io/design/components/lists.html#specs), and at a glance, your intended implementation differs from the intended use case for `ListTile`. 

I'll close this issue for now, but feel free to reach out if you have any other concerns!
