### ISSUE TITLE
Connectivity plugin: Potential memory leak on Android 6 and lower

### ISSUE THREAD

**Issue by hacker1024** [flutter/flutter#28928]
The problem is in `ConnectivityPlugin.java`, lines 119 and 104.

![Lint message](https://user-images.githubusercontent.com/20849728/53864240-1a9b9800-4040-11e9-8c6c-07ba39b76c1b.png)

**Comment by athornz** [comment]
I'm getting this as well. Lint is failing on release builds due to the connectivity plugin.

<img width="842" alt="Screen Shot 2019-04-17 at 8 59 39 AM" src="https://user-images.githubusercontent.com/848767/56243626-28d4dd80-60ef-11e9-9e6c-5572d1b8c2cf.png">

**Comment by hacker1024** [comment]
Since that PR is merged (thanks), I'm closing this issue.
