### ISSUE TITLE
Flutter firestore slow speed when query two collections

### ISSUE THREAD

**Issue by matteus911** [flutter/flutter#28937]
I should show two related collections data in one page 
e.g There is 'AssignedVehicles' collection with vehicle column and 'Vehicles' collection, 
show document of 'AssignedVehicles' with info of 'Vehicles' document

Future<List<AssignedVehicles>> getAssignedVehicles() async {
    final assignedVehicles = <AssignedVehicles>[];
    QuerySnapshot snapshots = await assignedVehiclesDB.where('user', isEqualTo: userEmail).getDocuments();
    if(snapshots != null && snapshots.documents != null){
      for (dynamic d in snapshots.documents) {
        final v = new AssignedVehicles.fromMap(d);
        final vehicle = await getVehicle(v.vehicle);
        v.type =vehicle.type;
        v.department = vehicle.department;
        v.vehicleLong = vehicle.vehicleLong;
        assignedVehicles.add(v);
      }
    }else{
      return null;
    }
    return assignedVehicles;
  }

  Future<Vehicles> getVehicle(String vehicle) async {
    final vehicles = <Vehicles>[];
    QuerySnapshot snapshots = await vehiclesDB.where('vehicle', isEqualTo: vehicle).getDocuments();
    if(snapshots != null && snapshots.documents != null){
      for (dynamic d in snapshots.documents) {
        final v = new Vehicles.fromMap(d);
        vehicles.add(v);
      }
    }else{
      return null;
    }
    return vehicles[0];
  }

This needs double query to get related data
This also slow down my app's speed much
Who can help me?

**Comment by Vaann00** [comment]
Hi,
Did you find a solution to this please ?
