### ISSUE TITLE
Global fontFamily settting property does not work in TextSpan of RichText 

### ISSUE THREAD

**Issue by wonderful89** [flutter/flutter#28931]
I  have found that global fontFamily settings(in theme) do not work in RichText. If I set the fontFamily in 
TextStyle of TextSpan, it works (like string 'innerText2: aaabbccc\n'). 

![image](https://user-images.githubusercontent.com/44089389/53867519-01d6b680-402f-11e9-8abf-f81757bff116.png)

## Steps to Reproduce

```dart
@override
  Widget build(BuildContext context) {
    Brightness curBright = Brightness.light;
    return new MaterialApp(
      title: 'Flutter demo1',
      navigatorObservers: <NavigatorObserver>[new CustomNavObserver()],
      theme: new ThemeData(
        primaryColorLight: Colors.green,
        brightness: curBright,
        primaryColorBrightness: curBright,
        accentColorBrightness: curBright,
        fontFamily: 'rokkittFamily', //PingFang SC
      ),
      home: new RouterPage(
        routerList: globalRouters,
      ),
    );
  }

// 
class TextFontFamilyPage extends StatefulWidget {
  @override
  _TextFontFamilyPageState createState() => _TextFontFamilyPageState();
}

class _TextFontFamilyPageState extends State<TextFontFamilyPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('aaa'),
      ),
      body: Container(
        child: Column(
          children: <Widget>[
            Text(
              'aaabbccc',
              style: TextStyle(fontSize: 20.0),
            ),
            RichText(
              text: TextSpan(
                text: 'outText: aaabbccc\n',
                style: TextStyle(
                  fontSize: 20.0,
                  color: Colors.red[300],
                ),
                children: [
                  TextSpan(
                    text: 'innerText1: aaabbccc\n',
                    style: TextStyle(
                      fontSize: 20.0,
                      color: Colors.blue[300],
                    ),
                  ),
                  TextSpan(
                    text: 'innerText2: aaabbccc\n',
                    style: TextStyle(fontSize: 20.0, color: Colors.green[300], fontFamily: 'rokkittFamily'),
                  ),
                  TextSpan(
                    text: 'innerText3：aaabbccc\n',
                    style: TextStyle(
                      fontSize: 20.0,
                      color: Colors.purple[300],
                    ),
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
## env.
```
➜  flutterDemos git:(master) ✗ flutter --version
Flutter 1.2.1 • channel unknown • unknown source
Framework • revision 8661d8aecd (3 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

Who can give some suggestions?

**Comment by HansMuller** [comment]
The material library's theme is only supported by the material library widgets and not by RichText. You should be able to get the result you want by specifying the outer TextSpan style with:

```
Theme.of(context).textTheme.body1.merge(<your text style here>)
```

**Comment by TahaTesser** [comment]
Hi @HansMuller 
Is this issue still valid?
Thank you

**Comment by basnetjiten** [comment]
@HansMuller That did not solve in my case;
     RichText(text: TextSpan(
                                    /*style: AinAppTheme.messageBody*/
                                style: Theme.of(context).textTheme.display2.merge( Theme.of(context).textTheme.display2),
                                    children: <TextSpan>[
                                      HTML.toTextSpan(context, thread.lastBody),
                                    ],
                                  ),
                                  overflow: TextOverflow.ellipsis,
                                  maxLines: 2,
                                )

**Comment by TahaTesser** [comment]
Hi @wonderful89 
As mentioned by HansMuller, material theme is only support material widgets and provided solution should solve you issue

if you disagree please write in the comments and I will reopen it. 
Thank you"

**Comment by RohitSharma5** [comment]
What you can do now is much simpler.

If you want to create a RichText with default TextStyle, just use Text.rich:

Text.rich(
  TextSpan(
    children: [
      TextSpan(text: 'Hello '),
      TextSpan(
        text: 'bold',
        style: TextStyle(fontWeight: FontWeight.bold),
      ),
      TextSpan(text: ' world!'),
    ],
  ),
)

**Comment by GRyabkin** [comment]
It doesn't work for me either. How it was resolved??

Currently, I use the workaround by forcefully setting `TextStyle` with `fontFamily` on `RichText` widget

Any hints or suggestions? It can't be specified in ThemeData at all?
