### ISSUE TITLE
Need an easy MediaQuery widget for testing

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#2894]
Any code that uses a MediaQuery needs to have a MediaQuery widget in its parent hierarchy. This requires the developer to understand details that are normally hidden by MaterialApp, which seems like an unnecessary road block.

I propose a subclass of MediaQuery that does the right thing in a test environment, at least for the "screen size".

**Comment by abarth** [comment]
Maybe the widget tester should have an option that defaults to true which adds a MediaQuery to the hierarchy.  /cc @Hixie

**Comment by Hixie** [comment]
What's the "right thing"? Just return defaults? We could probably do that easily enough.

**Comment by abarth** [comment]
The widget tester has an opinion about how big its fake window is.  It could reflect that in the media query, probably with a device pixel ratio of 1.0 and zero padding.

**Comment by Hixie** [comment]
That's just what the engine gives us. I think the solution is just to make MediaQuery default to querying dart:ui if it can't find a MediaQuery.
