### ISSUE TITLE
Using webview_flutter in a StatelessWidget?

### ISSUE THREAD

**Issue by seenickcode** [flutter/flutter#28942]
It looks like when you present a `WebView` in a `Scaffold` widget and that `Scaffold` widget is part of a `StatelessWidget`, the `build` method seems to constantly execute, thus never loading the actual web page you want to load. 

```
class WebViewContainer extends StatelessWidget {
  final url;
  final _key = UniqueKey();

  WebViewContainer(this.url);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Column(children: [
          Expanded(
              child: WebView(
                  key: _key,
                  javascriptMode: JavascriptMode.unrestricted,
                  initialUrl: url))
        ]));
  }
}
```

Yet if you put the whole thing in a `StatefulWidget` instead, it properly loads only once. In my stateful widget I have a `_url` value so it seems like only then it renders when this `_url` is updated. 

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewContainer extends StatefulWidget {
  final url;

  WebViewContainer(this.url);

  @override
  createState() => _WebViewContainerState(this.url);
}

class _WebViewContainerState extends State<WebViewContainer> {
  var _url;
  final _key = UniqueKey();

  _WebViewContainerState(this._url);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            Expanded(
                child: WebView(
                    key: _key,
                    javascriptMode: JavascriptMode.unrestricted,
                    initialUrl: _url))
          ],
        ));
  }
}
```

Does that make sense or maybe I’m doing something wrong when using a `StatelessWidget`?

**Comment by tb2761** [comment]
If you look at the Example Application, you need to add
'''
final Completer<WebViewController> _controller =
      Completer<WebViewController>();
'''
and im the WebView add this:
onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
Then it should work.

**Comment by seenickcode** [comment]
Ok, thank you @tb2761
