### ISSUE TITLE
xcodebuild error: The workspace named "Runner" does not contain a scheme named "Runner"

### ISSUE THREAD

**Issue by KatsuShooter** [flutter/flutter#28940]
Trying to build IOS app. It works brilliantly on Android, but when i tried to build it for iOS i had an error.

Why can it be?

```
Building com.example.cctrack for device (ios-release)...
Automatically signing iOS for device deployment using specified development team
in Xcode project: 2SLBG8E2Y6
Running Xcode build...                                                  
Xcode build done.                                            0,7s
xcodebuild: error: The workspace named "Runner" does not contain a scheme named
"Runner". The "-list" option can be used to find the names of the schemes in the
workspace.

Oops; flutter has exited unexpectedly: "Exit code 65 from: /usr/bin/env xcrun xcodebuild -configuration Release -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/daniilkikimov/Downloads/cctrack/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/v4/0l22rds905zfxkzdzdsj7v2m0000gn/T/flutter_build_log_pipe.HtRYCe/pipe_to_stdout -showBuildSettings".
Sending crash report to Google.
Crash report sent (report ID: cbf3b982a89494d6)
Crash report written to /Users/daniilkikimov/Downloads/cctrack/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```
Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.12.6 16G1314, locale ru-KZ)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
[!] Android Studio (not installed)
[!] VS Code (version 1.27.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available
```

**Comment by Allan-Nava** [comment]
I got this erorr:
```
 === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Release ===
    ld: '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/FMDB/libFMDB.a(FMDatabasePool.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated
    library from the vendor, or disable bitcode for this target. file '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/FMDB/libFMDB.a' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

How can I fix it?

**Comment by lanxuexing** [comment]
I had the same problem

```bash
ld: framework not found App
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MauroNavaDOS** [comment]
Same error :V dammmn

**Comment by oufle** [comment]
xcodebuild: error: The workspace named "Runner" does not contain a scheme named "Runner". The "-list" option can be used to find the names of the schemes in the workspace.

Oops; flutter has exited unexpectedly: "Exit code 65 from: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/oulfe/project/sheger/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true -showBuildSettings".

**Comment by McLarenCollege** [comment]
> I got this erorr:
> 
> ```
>  === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Release ===
>     ld: '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/FMDB/libFMDB.a(FMDatabasePool.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated
>     library from the vendor, or disable bitcode for this target. file '/Users/ies/Desktop/work/ntop/ivo_lite/build/ios/Release-iphoneos/FMDB/libFMDB.a' for architecture arm64
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> How can I fix it?

For me the solution was to go to the build settings in Xcode and set 'Enable bitcode' to No (under 'Build Options)

**Comment by blackbeario** [comment]
Same here. 
```
xcodebuild: error: The workspace named "Runner" does not contain a scheme named "Runner"
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.8-pre.11, on Mac OS X 10.14.6 18G103, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (3 available)
```

**Comment by Cameron-keith** [comment]
> Same here.
> 
> ```
> xcodebuild: error: The workspace named "Runner" does not contain a scheme named "Runner"
> ```
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v1.12.8-pre.11, on Mac OS X 10.14.6 18G103, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.40.1)
> [✓] Connected device (3 available)
> ```

I am having this same issue,

Does anyone have an update on the fix?

**Comment by jmagman** [comment]
@Allan-Nava @McLarenCollege the bitcode issue seems unrelated.  Please file a new issue.

@lanxuexing That one is definitely unrelated.  Please file a new issue.

**Comment by jmagman** [comment]
@KatsuShooter @Cameron-keith @blackbeario Can one of you open `ios/Runner.xcworkspace` in Xcode and attach a screenshot of Product > Scheme > Edit Scheme to see what you have?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by guihackmann** [comment]
> open `ios/Runner.xcworkspace`

Hi, I have the same issue. Following the above steps, when I click "Edit Schemes" it doesn't show anything, it seems there are no schemes created. What should I do?

**Comment by jmagman** [comment]
@guihackmann That's different from the Xcode project that gets generated by `flutter`. Do you know how you got into that state?  Did you edit it at some point?  Do you see any schemes in `ios/Runner.xcodeproj`?

**Comment by sscast** [comment]
> @guihackmann That's different from the Xcode project that gets generated by `flutter`. Do you know how you got into that state? Did you edit it at some point? Do you see any schemes in `ios/Runner.xcodeproj`?

I think I just come across the same issue, and before that I clicked "Localize". It appeared on the right hand side column if you `open -a ios/Runner.xcodeproj` Not sure if it's the same as what others experience, but hope it gives you some clue! And I'm curious for an answer too. My fix was to rebuild the app, but I know there should be another way! Thanks.
<img width="263" alt="Screen Shot 2020-08-03 at 7 26 08 PM" src="https://user-images.githubusercontent.com/33290647/89236728-5b923600-d5bf-11ea-892f-6694f0be9978.png">
`

**Comment by jmagman** [comment]
@sscast @guihackmann 
> Can one of you open `ios/Runner.xcworkspace` in Xcode and attach a screenshot of Product > Scheme > Edit Scheme to see what you have?

**Comment by sscast** [comment]
> @sscast @guihackmann
> 
> > Can one of you open `ios/Runner.xcworkspace` in Xcode and attach a screenshot of Product > Scheme > Edit Scheme to see what you have?

I don't have screenshot as I have rebuilt it. I remember if i open `ios/Runner.xcworkspace` it's empty, but I can open the Runner with `ios/Runner.xcodeproj/`

**Comment by jmagman** [comment]
I'm not sure how these workspace/project files were corrupted, but a newly created `flutter create` app isn't.  If you see this, please file a new issue and completely fill out the template.  Check your source control and see if you have any stray edits to `ios/Runner*` files.  

Closing, I don't think this is actionable.
