### ISSUE TITLE
add2app: doc: references merged PR 23387 as not landed

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#28950]
Existing add2app documentation says " It also attempt to respect your build configuration setting once this pull request lands." referencing 23387 but

but https://github.com/flutter/flutter/pull/23387 says merged

**Comment by xster** [comment]
@dnfield you know any background on this?

**Comment by dnfield** [comment]
I think the wiki just needs to be updated now that that PR has landed.

**Comment by dnfield** [comment]
I don't see this text in the wiki anymore. Closing.
