### ISSUE TITLE
Bottom appBar with fab and listview problem

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#28954]
# Link to project
https://github.com/ferraridamiano/demobugflutter

# The problem

In the case of a scaffold with a listview of textfield as body and a bottomAppBar with center docked FAB
<img src="https://raw.githubusercontent.com/ferraridamiano/demobugflutter/master/photo_2019-03-05_21-30-24.jpg" width="250">

There is this problem:

1. If resizeToAvoidBottomInset property in scaffold is set to true:
   - 1a) if you click on a textfield under the height of the keyboard then the interface is traslated and you are able to see what you type
   - 1b) The FAB is been traslated with the interface

<img src="https://raw.githubusercontent.com/ferraridamiano/demobugflutter/master/photo_2019-03-05_21-31-37.jpg" width="250">

2. If resizeToAvoidBottomInset property in scaffold is set to false:
   - 2a) if you click on a textfield under the height of the keyboard then you don't see what you are typing
   - 2b) you don't see the FAB

<img src="https://raw.githubusercontent.com/ferraridamiano/demobugflutter/master/photo_2019-03-05_21-31-43.jpg" width="250">

There's no way to combine 1a and 2b (I can see what I type and the FAB is not visible)

The line which i'm refering is https://github.com/ferraridamiano/demobugflutter/blob/edb69a3ce806e47fe6f1eaa009ac23cde05ad1e1/lib/main.dart#L29

**Comment by ferraridamiano** [comment]
Can't anyone help me?

**Comment by chinajuns** [comment]
Container(
padding: EdgeInsets.only(bottom: MediaQuery.of(context).padding.bottom+MediaQuery.of(context).viewInsets.bottom),
child:ListView(children：<Widget>[ //your widget])
)

**Comment by ferraridamiano** [comment]
Good workaround, it works, thanks!

**Comment by TahaTesser** [comment]
Hi @ferraridamiano 
It's a particular situation, i think workaround is the only solution for this
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
