### ISSUE TITLE
[plugins] Pod deps api breaks can cause plugins to stop working

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#28957]
Look at https://github.com/flutter/plugins/commit/f8078a5ed134a175ad8422c79e05d6d310df4138 for an example of such a break.

One possible solution for this is to have all out plugins specify the dependency version in the podspec file.

cc: @collinjackson

**Comment by stuartmorgan** [comment]
Our only plugin left with an unpinned dependency is maps, and we have a specific bug discussing that (there are significant version support downsides to pinning it which we have to weigh against the risk of API breaks), so closing this as resolved.
