### ISSUE TITLE
Unexpected notch behavior

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#28956]
Here's a sample app: https://gist.github.com/mehmetf/0bae55d83574e378705174bd9fec012b

When SafeArea is not used, in landscape:
- there is padding added in at the start and end of the ListViews
- the FAB is also offset
- the padding is larger than the actual notch (see screenshots 1, 2, 3, and 4).

When SafeArea is used, in landscape:
- there is padding added on both ends
- the padding is larger than the actual notch (see screenshots 5 and 6)

iPhone X screenshots:

1. Portrait, without SafeArea, ListViews scrolled to start
![image](https://user-images.githubusercontent.com/6687929/53909988-b0670100-4007-11e9-8021-12d2a3f8d04f.png)

2. Portrait, without SafeArea, ListViews scrolled to end
![image](https://user-images.githubusercontent.com/6687929/53910016-b957d280-4007-11e9-8465-c1b4679a630a.png)

3. Landscape, without SafeArea, ListViews scrolled to start
![image](https://user-images.githubusercontent.com/6687929/53910026-c1177700-4007-11e9-86b5-b710e9ad7d26.png)

4. Landscape, without SafeArea, ListViews scrolled to end
![image](https://user-images.githubusercontent.com/6687929/53910037-c8d71b80-4007-11e9-8e7b-11d596d06a90.png)

5. Portrait, with SafeArea
![image](https://user-images.githubusercontent.com/6687929/53910059-d096c000-4007-11e9-892d-78ab93243851.png)

6. Landscape, with SafeArea
![image](https://user-images.githubusercontent.com/6687929/53910072-d7bdce00-4007-11e9-8293-c46e9e198a99.png)

iPhone X/without SafeArea/Portrait: padding=EdgeInsets(0.0, 44.0, 0.0, 34.0) : viewInsets=EdgeInsets.zero
iPhone X/without SafeArea/Landscape: padding=EdgeInsets(44.0, 0.0, 44.0, 21.0) : viewInsets=EdgeInsets.zero
iPhone X/with SafeArea/Portrait: padding=EdgeInsets(0.0, 44.0, 0.0, 34.0) : viewInsets=EdgeInsets.zero
iPhone X/with SafeArea/Landscape: padding=EdgeInsets(44.0, 0.0, 44.0, 21.0) : viewInsets=EdgeInsets.zero

**Comment by mehmetf** [comment]
@HansMuller How many of these behaviors are expected and what is their rationale? I am posting this on behalf of a team in Google. If you want to look at the internal entry (which has additional use cases), please ping me.

**Comment by HansMuller** [comment]
As far as I can tell SafeArea and ListView are working as intended given the window padding values reported by the engine.  I tested the material/framework aspects of this issue with a version of the original app: https://gist.github.com/HansMuller/ccec021e75ca9adb1dbaae83efedfecd 

I agree that the portrait MediaQuery value looks wrong, not clear why there's  bottom padding. The landscape simulator screenshot doesn't look right either: what's the microphone doing at the bottom (screenshot 6)?

**Comment by mehmetf** [comment]
Thanks Hans. Who should this be routed to? I am not sure who handles MediaQuery in the engine?

**Comment by HansMuller** [comment]
cc @cbracken It looks like there's a problem here, maybe with the iPhoneX emulator, maybe with the way the engine is computing the window's padding.

**Comment by talbog** [comment]
Hi All,
Thanks to Mehmet for posting this for me.  I am the engineer that originally reported this problem, and want to clarify that this behaviour was observed on both the emulator, and on a physical device.

Another note, unlike what Hans reported, I don't think that the bottom padding is wrong, it is there for the bottom button (which looks like a speaker cutout).  The landscape MediaQuery padding is what looks wrong to me as it has padding on both the left and right when the notch is only on one end (not both).

**Comment by HansMuller** [comment]
@talbog - The ListView in  https://gist.github.com/HansMuller/ccec021e75ca9adb1dbaae83efedfecd pads its content on the left and right because the Flutter engine (ui.window) reports 44.0 of padding and both the left and right.

**Comment by talbog** [comment]
@HansMuller - That's interesting, on the project I'm working on there are two ListViews stacked vertically much like what I put together for the example shown in this issue, but only one of the ListViews was getting padded.

**Comment by cbracken** [comment]
Unless I'm misunderstanding this request, this looks like Flutter's insets are working as intended. On iPhone X class devices in horizontal layout mode, the expectation is that the safe area insets are symmetric on either side of the display.

Apple used to have a very nice [introductory page](https://web.archive.org/web/20180824112038/https://developer.apple.com/design/human-interface-guidelines/ios/overview/iphone-x/) (Wayback Machine link) that covers designing for the iPhone X, but it appears to have been replaced by more generic content in the _Layout Guides and Safe Area_ section of the [Adaptivity and Layout](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/) chapter of Apple's Human Interface Guidelines.

Implementation-wise, the engine currently just [passes through](https://github.com/flutter/engine/blob/d87d29054dd83c02757206c045e84e59b526b909/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L649-L659) the safe area insets reported by iOS. 

If you do want to override the default behaviour, you should be able to do so either by using the [SafeArea](https://docs.flutter.io/flutter/widgets/SafeArea/SafeArea.html) boolean parameters or through [MediaQuery.removePadding](https://docs.flutter.io/flutter/widgets/MediaQuery/MediaQuery.removePadding.html)

**Comment by HansMuller** [comment]
The  designing for the iPhone X [introductory page](https://web.archive.org/web/20180824112038/https://developer.apple.com/design/human-interface-guidelines/ios/overview/iphone-x/) (Wayback Machine link) that @cbracken mentioned includes an illustration that highlights the portrait and landscape safe areas:
![safe_area](https://user-images.githubusercontent.com/1377460/54237208-ab57f500-44d2-11e9-80f1-26668c6d03f5.png)

Hopefully it's clear that (for whatever reason), in landscape mode the horizontal safe area insets are symmetrical,  larger than the notch on the left, and exist even though there's no notch on the right.

**Comment by talbog** [comment]
Hi Chris,
Thanks for all the information, and digging up all those pages. 

That seems like an odd choice on Apple's part as it's basically throwing away perfectly usable screen real estate, but I'm guessing it probably has to do with the fact that in landscape there is padding at the bottom but not at the top, and as a result the top could be clipped by the rounded corner.

When in landscape is there a way to know on which side the notch actually is?

**Comment by cbracken** [comment]
As far as I'm aware, Apple doesn't provide a public API specifically for looking up which side the notch is on, but if you were willing to make assumptions about the set of known devices, [DeviceOrientation](https://docs.flutter.io/flutter/services/DeviceOrientation-class.html) would basically provide the info you need.

**Comment by talbog** [comment]
Great, thanks Chris and Hans for all your help on this!

I think it's safe to mark this as "working as intended".

**Comment by cbracken** [comment]
Thanks @talbog for confirming. 

Do you think there's anywhere in the docs that we could be clearer about the expected behaviour? More specifically, do you remember where you first looked to see what the expected behaviour was to determine if this was intended behaviour or a bug? It may be worth us augmenting the docs there.

**Comment by talbog** [comment]
I think what I've learnt from playing with the SafeArea widget is:
1. It looks like Android pads apps on phones with notches, and so when using the SafeArea widget, the MediaQueryData should be expected to have 0 padding and viewInsets (at least that has been my experience).
2. For iOS, it might be worth linking to the Apple documentation to set expectations on how the SafeArea widget will affect the MediaQueryData as before reading said documentation I had different expectations and wrongly thought that something was wrong.

Again thanks a bunch to Chris and Hans for taking the time to look into this!
