### ISSUE TITLE
[plugins] Get notified when a one of our pod deps have api breaks

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#28959]
If we do end up specifying the deps to address https://github.com/flutter/flutter/issues/28957, we will need a mechanism to know if we need to update the cocoa pod dep version and update our plugin.

**Comment by stuartmorgan** [comment]
https://github.com/dependabot/dependabot-core/issues/416 would be ideal, as that's how we're now managing Android dependencies, but since it's not implemented, for now I suspect it best option is to just keep doing it ad hoc based on reports. That's not ideal, but it's been workable.

**Comment by stuartmorgan** [comment]
Closing since there isn't a system available for this in general, and it's not something that has caused problems, so isn't worth is building and maintaining something ourselves.
