### ISSUE TITLE
Typography alignment in Gallery on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2895]
From the Typography section of the Gallery:

![screenshot_20160325-094418](https://cloud.githubusercontent.com/assets/5479/14048867/603ab2ba-f26e-11e5-97b7-797f8d8ade7d.png)

(Notice how the text in "display3" isn't aligned vertically with "Regular 56sp".)

Here's what the spec shows:

![screen shot 2016-03-25 at 9 46 54 am](https://cloud.githubusercontent.com/assets/5479/14048893/887c2696-f26e-11e5-983a-915f473d9685.png)

https://www.google.com/design/spec/style/typography.html#typography-styles

**Comment by sethladd** [comment]
Looks like when we run on the iOS simulator (iPhone 6S) then the alignment looks pretty good:

![screen shot 2016-03-25 at 10 53 38 am](https://cloud.githubusercontent.com/assets/5479/14050247/d9e7c694-f277-11e5-9082-45fc349004d4.png)

**Comment by Hixie** [comment]
We align with the top of the em box. Where that ends up depends on the font. In the two screenshots above there are different fonts being used, hence the different results.

Until we get much more in the way of metrics (#224), there's not much more we can do short of faking it.

**Comment by Hixie** [comment]
@sethladd I'm going to close this bug on the basis that it's not critical, but please reopen it if you think it's something we should look at.
