### ISSUE TITLE
Ensure Thai input works correctly on iOS

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#28962]
Issues with Thai input were reported in flutter/flutter#24203 and flutter/flutter#21745 regarding vowel input handling.

https://github.com/flutter/engine/pull/7982 proposes a fix that resolves this issue, but I suspect a deeper issue with how we deal with Thai and how we manage the mark region (iOS)/composing region (Android). In testing on Android in particular it looks like the composing region extends for the entire duration of input until the region is committed, which seems suspicious based on the default behaviour observed in apps that ship with the OS (e.g. Notes on iOS).

We should spend a few days understanding how Thai input is expected to work in core iOS and Android apps, and ensure that we've implemented things right on both platforms.

**Comment by criticalx7** [comment]
So is that fix about Thai vowel input handling available in stable channel now or all us Thai folk need to wait ?

**Comment by kf6gpe** [comment]
@criticalx7 that fix has been in the stable channel since this summer! We're always looking to improve our localization more generally, though, which is what this issue is about.

**Comment by GaryQian** [comment]
@criticalx7 Since the team directly working on typography does not speak Thai, can you provide feedback as to whether Thai is working on iOS properly or not? Thanks!

**Comment by criticalx7** [comment]
Yes I had my fellow dev tested the update and he said it is fine now, no more shaking and overflowing of sound vovel. Good job guys.

**Comment by GaryQian** [comment]
Great! Thanks for verifying!
