### ISSUE TITLE
Slider onChangedEnd called multiple times and before user "stopped" (released)

### ISSUE THREAD

**Issue by sjmcdowall** [flutter/flutter#28961]
## Steps to Reproduce

1. ... Create application with a Slider
2. ...Put in debugging (print) within an onChangedEnd
3. ...Slick on the slider and start moving it .. see onChangedEnd fired .. then fired again once the slider is released ..

The expected behavior (at least to me) is that the onChangedEnd would not be called until the user releases (lifts up) on the slider .. and that it would be called once per "transaction". 

I think the issue maybe its being called because of the "click" to start moving the slider.

This is in the iOS Emulator .. 

If this is expected behavior because it looks the same as if I just click somewhere on the slider bar and it moves to that position .. so this is basically clicking to where the Handle (?) is .. causing the onChangedEnd even though it hasn't actually changed and no onChange event has fired yet either... ?

I wouldn't expect an onChangeEnd event to fire before ANY onChange events to fire? 

I.e. if I DO click somewhere on the slider to move it .. I would still have expected an onChange event but no such event fires .. ?

## Logs

Really not useful or applicable IMHO since I can show the debug message but it's rather hard to know what the screen was doing at the time? 

```
```

```
 …/mms4/mobile     f62ccd74  master  2  flutter analyze                                                                                                             ✔  10428  16:13:21
Analyzing mobile...
No issues found! (ran in 39.4s)
```

```
✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en)
    • Flutter version 1.2.1 at /Users/sjm/Development/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sjm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Users/sjm/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • SJM iPad Pro              • 026945135686a30604aca9996a8fc8df3554b726 • ios         • iOS 12.1.4
    • iPhone XR                 • 4491738F-0E7C-4813-B6CA-4733F89678CB     • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by HansMuller** [comment]
cc @clocksmith

**Comment by clocksmith** [comment]
I am unable to reproduce on the flutter gallery slider on an iPhone XS Max simulator and pixel 3 physical device.

Could you post the source code (or an isolated piece of it) that produces the issue?

**Comment by sjmcdowall** [comment]
@clocksmith -- Ok I updated the "bug" report .. as now the behavior is more .. ah ..well not what I first thought anyway .. however, I still think something "wrong" not expected is happened .. please read and comment. 

If nothing else the documentation should probably be enhanced to tell people of this behavior if its WAD. 

Cheers!

**Comment by clocksmith** [comment]
Thanks for the update. I still cannot reproduce. In the flutter gallery slider demo, the onChangeEnd only gets called after the thumb is depressed. It may be rebuilding at the wrong time from a setState call? If you could post some source code, I can try to reproduce it locally and investigate further.

**Comment by sjmcdowall** [comment]
@clocksmith -- I will need to run the gallery myself.  However, my issue is that onChangeEnd *IS* called when I depress the "thumbtack" initially even if I didn't change the value (i.e. I depress the thumb at the same location it current is, not an empty place on the slider).

 Should the initial depression of the thumbtack cause an initial onChangeEnd to be called and then another onChangeEnd called when I release the thumbtack? 

If you can't reproduce the initial onChangeEnd on thumbtack depression is what you are saying, I will grab the flutter gallery and check it out myself.  But again, this may all be WAD and just a confusing (to me) expectation.

**Comment by marcglasberg** [comment]
https://github.com/flutter/flutter/issues/28115

**Comment by sjmcdowall** [comment]
Yes saw that @marcglasberg -- thanks!  I'll close this as that is tracked there
