### ISSUE TITLE
Cannot pan a google_maps_flutter inside of a scrolling widget

### ISSUE THREAD

**Issue by davbaron** [flutter/flutter#28969]
If you put a google_maps_flutter inside of a scrolling widget, any pan (touch-drag) events performed within the bounds of the map seem to be consumed by the scrolling widget, and so it scrolls instead of the map moving around.

I have seen this behavior with web (html/js) apps and typically there is a way to set the map so that it either pans locally, or drags/scrolls the container.

I have tried setting 'scrollGesturesEnabled' to both true and false, as I am not sure if 'scrolling' means 'scroll the container' or 'pan the map'. Either way did not affect the behavior, i.e., touch-dragging within the map always scrolls the container, versus panning the map.

**Comment by Kartik1607** [comment]
Could you please post minimal code to test.

**Comment by moonvader** [comment]
https://stackoverflow.com/questions/54280541/google-map-in-flutter-not-responding-to-touch-events

**Comment by davbaron** [comment]
Thanks @moonvader!  That did the trick... I added Pan and VerticalDrag gesture recognizers and now all works as expected.  @Kartik1607 :  I fully understand that this plug-in is in very early stages of dev, but I do think that some additional documentation might be needed and/or a re-think of some basic API offerings. What I mean by that is that I am not so sure how 'intuitive' it is to ask devs to realize that they need to add gestureRecognizers in certain use-cases but not others. It seems that a higher-level property specific to child-of-scroller situations might be a bit better.

Thanks again!
