### ISSUE TITLE
UniqueKey documentation is broken

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#28965]
For some reason these docs are from some other widget:

https://docs.flutter.io/flutter/widgets/UniqueKey-class.html

cc @goderbauer

**Comment by goderbauer** [comment]
Lol. I'll take a look.

**Comment by krisgiesing** [comment]
UniqueKey is the first declared class in that file. The comment block in question is at the top of that file but appears not to be intended as class comments. I think it's just a matter of separating the top comment block from the UniqueKey class.

**Comment by goderbauer** [comment]
@jcollins-g Is it expected that dartdocs things all of this is the doc comment for unique key"

https://github.com/flutter/flutter/blob/64d31016ed1e14809c6c20eaaf6445cffdc1a473/packages/flutter/lib/src/widgets/framework.dart#L39-L64

Or is it a bug that dartdoc ignores the blank lines?
