### ISSUE TITLE
Give full control of persistent cache to embedders

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#28967]
Dream embedder would like to control the contents of persistent cache. Some of the environments they run on are sandboxed with read-only FS (and writable /tmp that gets blown away on restart). 

There should be a way to:
- Disable the cache (and any disk io for that matter)
- Clear the cache
- Selectively remove files from the cache (for surgical cleanup for instance).

**Comment by Hixie** [comment]
Can you elaborate on what you mean by "persistent cache"? Do you mean the Skia shader cache?

**Comment by mehmetf** [comment]
This one: https://github.com/flutter/engine/blob/015c0246aebc6fc23f30004e3319b6d1e85a885a/shell/common/persistent_cache.cc

**Comment by Hixie** [comment]
This is a cache managed by the engine to store Skia resources.

cc @liyuqian @chinmaygarde @cbracken

**Comment by liyuqian** [comment]
Jason and I recently added https://github.com/flutter/engine/pull/7915 and https://github.com/flutter/engine/pull/8049 which allows specifying the persistent cache path and whether it's read-only.

Therefore:
1. Disabling it should be easy. Points the path to an invalid position would disable it. Now you can also point it to somewhere readonly and only copy the shader caches you needed (which are probably generated during the development on the **exact same device and GPU driver**) there.
2. Clear the cache is also easy. Set the path to a position where you have full control. Then clear it any time you want.
3. We probably won't support "Selectively remove files from the cache" unless there's a legit and critical use case. So far, the only use case that's close to this is to clear the cache of the old engine version when the app is upgraded to a new engine version. This can be done by 2. We can also do this by default and provide an option for opt out the clear-old-version-by-default behavior.

Please let me know if this solves all the concern so we can close this issue.

**Comment by mehmetf** [comment]
I believe the APIs you have added are enough. @joaoatgoogle could you please close if this is good enough for Cristi (his github handle is not registered).

**Comment by joaoatgoogle** [comment]
Cristi acks that this covers our needs. Thanks!
