### ISSUE TITLE
path_provider getApplicationDocumentsDirectory is broken in isolate

### ISSUE THREAD

**Issue by ytxDaXiong** [flutter/flutter#28981]
## Steps to Reproduce

1. I want to create a isolate to deal with dowload img and video  for great user experience
2. for download then save local dict I use path_provider but it does't work and have any returns in  isolate.
3.  if i have any mistakes please tell me thanks! 

await Isolate.spawn(dataLoader, receivePort.sendPort);
    SendPort sendPort = await receivePort.first;

  static dataLoader(SendPort sendPort) async {
    ReceivePort port = new ReceivePort();
    sendPort.send(port.sendPort);
    var appDocDir = await getApplicationDocumentsDirectory();
    String appDocPath = appDocDir.path;
   print(appDocPath);
    }
## Logs

```
```

```
```

```
```

**Comment by apaatsio** [comment]
I can't help with the exact issue but as a side note, downloading is not a CPU-intensive task. It doesn't make sense to use isolates for that. Using isolates probably only adds some overhead and makes your downloads slightly slower if anything.

**Comment by jmagman** [comment]
Is this still an issue on the latest version of path_provider? See https://github.com/flutter/flutter/issues/38529

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by Drkstr** [comment]
@iapicca I am facing this issue right now. I am using getApplicationDocumentsDirectory() to  create my DB using the [sqflite](https://pub.dev/packages/sqflite) package. Here is some code. 

This is called from an isolate that is spawned using the [flutter_isolate](https://pub.dev/packages/flutter_isolate) package. 

Future<Database> get database async {
    if (_databases == null) {await initDB();}

 return _databases;
  }

  initDB() async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory(); 
    String path = join(documentsDirectory.path, DATABASE_NAME);
    _databases = await openDatabase(path, version: CURRENT_DB_VERSION,
        onCreate: (Database db, int version) async {
      await db.execute(CREATE_LOG_TABLE_QUERY);
    });
  }

This is the stack trace : 

> E/FlutterIsolate(32616): NoSuchMethodException: io.flutter.plugins.GeneratedPluginRegistrant.registerWith [interface io.flutter.plugin.common.PluginRegistry]
E/FlutterIsolate(32616): The plugin registrant must provide a static registerWith(FlutterPluginRegistry) method
I/flutter (32616): I am isolate 1
E/flutter (32616): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (32616): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (32616): <asynchronous suspension>
E/flutter (32616): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (32616): #2      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:92:22)
E/flutter (32616): #3      DatabaseSingleton.initDB (package:tablet_tests/singletons/DatabaseSingleton.dart:31:42)
E/flutter (32616): #4      DatabaseSingleton.database (package:tablet_tests/singletons/DatabaseSingleton.dart:25:36)
E/flutter (32616): #5      DatabaseSingleton.insertLog (package:tablet_tests/singletons/DatabaseSingleton.dart:40:22)
E/flutter (32616): #6      connectToDevice (package:tablet_tests/background_processes/USBSerialBackground.dart:14:28)
E/flutter (32616): #7      isolate1 (package:tablet_tests/main.dart:8:3)
E/flutter (32616): #8      FlutterIsolate._isolateInitialize.<anonymous closure>.<anonymous closure> (package:flutter_isolate/flutter_isolate.dart:128:23)
E/flutter (32616): #9      _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (32616): #10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (32616): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (32616): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (32616): #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter (32616): #14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
E/flutter (32616): #15     _StreamController._add (dart:async/stream_controller.dart:649:7)
E/flutter (32616): #16     _StreamController.add (dart:async/stream_controller.dart:595:5)
E/flutter (32616): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (32616):

**Comment by iapicca** [comment]
Hi @Drkstr 
the issue you are describing might be related to present,
nevertheless different in its elements;

you may want to open a new issue providing
your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml`
and if possible a reproducible minimal code sample.
Thank you

**Comment by Drkstr** [comment]
Thanks for the reply,  creating anew issue now.
