### ISSUE TITLE
TextDirection should support vertical texts

### ISSUE THREAD

**Issue by JUSTIVE** [flutter/flutter#28989]
While I was doing my own version of 'flutter challenge' of [this](https://dribbble.com/shots/4514354-Sign-up) design, which is from Dribbble, I thought that TextDirection class had some sort of vertically-written text support property that should help me easy to implement word `ウェルカム` . 
So I just ran to my IDE, and I realized that TextDirection class has only rtl and non-rtl supports. I'm not Japanese but I heard they use a lot of vertically-written texts in many situations, so I think that the Flutter should support these features. 
thank you for read my 'first' issue to other's repository, and my mother language isn't english, so there could be a lot of broken expressions. sorry for that too.

**Comment by Kartik1607** [comment]
Vertical text is not supported for now and possible implementation (Transform, Rotate, SubStr ) would be sketchy and hacky at best.
https://github.com/flutter/flutter/issues/15710

**Comment by JUSTIVE** [comment]
Duplicate of #14262.
