### ISSUE TITLE
'String isn't a type' and 'Future isn't a type' errors

### ISSUE THREAD

**Issue by NathanAP** [flutter/flutter#28995]
Hi! I'm trying to make a merge in my project, but when I do it I keep getting the errors 'String isn't a type' and 'Future isn't a type'. Both my projects work on their own and are in the same version and channel, but when I merge them, my files keep getting these errors. 

I did try to restart Android Studio, VSCode and PC, reinstall Flutter, revert and merge again, every step in #24279, changing Flutter channels, search in Flutter and Dart support, but nothing worked so far. The only thing I did that "worked" was importing dart:core as core and addressing Strings as core.String, which worked, but this is not correct.

My flutter doctor:
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14 18A391, locale pt-BR)
    • Flutter version 1.2.1 at /Users/nats/frameworks/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nats/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/nats/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by NathanAP** [comment]
I can't even create a new String in any file, so anything like
final String test = '';
gets me an error in "String" saying "String isn't a type". It might be related to my own files, but I don't know a way to find where is the problem...

**Comment by NathanAP** [comment]
Oh, okay, I found out, I was having a problem with a dependency and a file which I had some Strings manipulation. I believe Futures have the same problem, so I will try to figure it out. Sorry for useless post and thanks for all effort!

**Comment by jonahwilliams** [comment]
Sounds like this was resolved

**Comment by lamatatwany** [comment]
@NathanAP hello .. am facing the same exact problem .. how did you manage to solve it?

**Comment by yringler** [comment]
Yes, very strange.
I'm currently using code like this
`
import 'dart:core' as hack;

class SiteSection {
  final hack.String ID;
  final hack.String Title;
  final hack.String Description;
  final hack.List<hack.String> Sections;
  final hack.bool IsTopLevel;

  SiteSection({this.ID, this.Title, this.Description, this.Sections, this.IsTopLevel});

}`

Pretty bizarre.

**Comment by yringler** [comment]
Update: It seems like after I did that weirdness, I was able to drop the hack part, and everything works. Seems to be a bug in the vs code language server? 🤷‍♂

**Comment by natgross** [comment]
Can reproduce this bug 100%. I stumbled upon it when I copied older Java code to .dart file in order to edit and transform it to Dart. Java getters can be declared 'public', for example Java's toString() is:
**public String toString(){return 'whatever'}**
Of course in Dart, no such a declaration as 'public'. But here is the thing, as long as any method returning a String is erroneously marked public, Dart won't let you declare a String in the class, with the aforementioned error.

**Comment by h8hawk** [comment]
I have same problem on Vscode. Vscode doesn't recognize any reserved types (Future, String, int, ...). Removing `.dartServer/.analysis-driver/` doesn't work either.

flutter doctor -v:
```
Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/howard/programs/flutter
    • Framework revision 20e59316b8 (8 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
```

**Comment by dreyZZ** [comment]
I have same problem, how can i fix it?

![image](https://user-images.githubusercontent.com/26909815/67165206-116ef980-f38b-11e9-9c46-ae088dc8492b.png)

**Comment by natgross** [comment]
@dreyZZ In your case, you have a Java String[] array, experiences, defined. Dart does not recognize this. Define it as a List<String> and that should cause the error message to disappear.

**Comment by mindplay-dk** [comment]
I have this problem as well - all `String`, `Future` and `FutureOr` type-hints get highlighted with an error message saying they're not types.

![image](https://user-images.githubusercontent.com/103348/69005565-30c65b80-0924-11ea-9b35-eb191aae0004.png)

I cloned [this project](https://github.com/Jaguar-dart/jaguar_hotreload) and ran `pub get`, and that's all. My Dart installation is just a few days old, and I haven't had this problem with my own projects, so maybe there's something specific about this project that triggers the problem?

Either way, @jonahwilliams, please reopen - looks like there's enough people having this problem?

**Comment by mindplay-dk** [comment]
For the record, steps I tried:

* Copied the `environment.sdk` setting from a healthy project.
* Copied `analysis_options.yaml` from a healthy project.
* Wiped out `.dart_tool` and `.packages` and re-ran `pub get`.
* Restarted VS Code.

Same same.

**Comment by mindplay-dk** [comment]
Okay, solved!

This was a problem with a source file after all - I somehow managed to leave the word `String` dangling at the end of a file, and for some reason this causes the language service to go apeshit:

![wtf](https://user-images.githubusercontent.com/103348/69005717-4dfc2980-0926-11ea-88fc-bf9252c6e7dc.gif)

This ought to be a completely common issue, as most function definitions are going to start with a valid type-hint, and apparently the entire file will be seen as invalid for a moment while you're typing.

So this probably should be re-filed as an issue with the language service, which I think ought to be a lot more error tolerant in this very common case?

**Comment by ghunkins** [comment]
Take a glance at your file and clean-up any unfinished lines. This fixed this issue for me. 

(Strange error though on behalf of Dart / Flutter).

**Comment by mindplay-dk** [comment]
> Take a glance at your file and clean-up any unfinished lines.

Of course, yeah - but most language services for IDE support use a more error-tolerant parser, so that IDE support doesn't completely break down if you leave something temporary somewhere while working on something else. (Maybe this is harder to implement for Dart because there aren't many keywords like `function`, `var`, etc. to help it figure out how to resume after a parse error...)

**Comment by varshneypragyan** [comment]
Thanx for the help.

**Comment by gsouf** [comment]
The is a bug with jetbrain ide, it also occurs with their other products from time to time. Sometimes it's just a matter of closing the ide and openning it again.

**Comment by Sanjivanee93** [comment]
![image](https://user-images.githubusercontent.com/73022345/96335937-a9d0b480-1099-11eb-8f4d-ed9569daf3d0.png)


Getting this issue in some files for "String" type

**Comment by Sanjivanee93** [comment]
![Uploading image.png…]()

**Comment by Sanjivanee93** [comment]
![Uploading image.png…]()

**Comment by Sanjivanee93** [comment]
![image](https://user-images.githubusercontent.com/73022345/96337525-83187b00-10a5-11eb-8288-30ea7e0acbe7.png)

**Comment by Selecao** [comment]
I have the same issue with "The name 'String' isn't a type so it can't be used as a type argument." after i added an extension to String.
So my steps to fix that problem was:
1. update pubspec.yaml with minimal Environment sdk 2.8.0
2. clear cache
3. restart Android Studio

**Comment by DannyJoinedApps** [comment]
@Selecao I had 14400 errors after cloning a repo working perfectly on another machine, including string not a type - I had same issue, I had extensions by the dozen on half of the common types... hence the many issues across large project. Your fix worked, I guess 2.8.0 is when extension support was brought in or something.

**Comment by Sanjivanee93** [comment]
> 
> 
> @Selecao I had 14400 errors after cloning a repo working perfectly on another machine, including string not a type - I had same issue, I had extensions by the dozen on half of the common types... hence the many issues across large project. Your fix worked, I guess 2.8.0 is when extension support was brought in or something.

Yes it worked by changing environment sdk 2.8.4. Now project is running but still have errors in Android Studio. Might be i need to reinstall flutter in it. Thanks for this @Selecao

**Comment by willherr** [comment]
I had this same issue and wanted to offer my solution as none of the comments here helped. 
I deleted the following folders from the root of my project
- .idea
- .dart_tool

And voila! No more errors.

**Comment by stuz5000** [comment]
I also get "Future isn't a type"... without much explanation.

![image](https://user-images.githubusercontent.com/7799980/107285438-032b6d80-6a14-11eb-8ec6-f6da3c140c0f.png)

... triggered by some recent upgrade.

```
/home/sir/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.3.pre at /home/sir/development/flutter
    • Framework revision 4b50ca7f7f (4 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sir/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/lib/jvm/java-8-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/269
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
Process finished with exit code 0
```
