### ISSUE TITLE
Issue from website page Widgets 目录

### ISSUE THREAD

**Issue by lifetin** [flutter/flutter#28997]
From URL: https://www.flutterchina.club/widgets.md
什么时候增加中文翻译呢?

**Comment by chenglu** [comment]
Hi @lifetin, there will be a community translated CN documents [here](https://debug.flutter.cn), may release the 1st translation version before May, more details about this project [here](https://github.com/cfug/flutter.cn), thanks!

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
