### ISSUE TITLE
FadeInImage support for filterQuality

### ISSUE THREAD

**Issue by cmkweber** [flutter/flutter#28993]
Currently the FadeInImage constructor doesn't provide the ability to pass filterQuality on to the RawImage it creates in build.

**Comment by cmkweber** [comment]
AA which was added in [https://github.com/flutter/flutter/pull/51656](https://github.com/flutter/flutter/pull/51656) could also be added at the same time...

**Comment by SahajRana** [comment]
@cmkweber, I just ended up copying the whole FadeInImage class and make changes in it, like this
```
Image _image({
    @required ImageProvider image,
    ImageErrorWidgetBuilder errorBuilder,
    ImageFrameBuilder frameBuilder,
  }) {
    assert(image != null);
    return Image(
      image: image,
      errorBuilder: errorBuilder,
      frameBuilder: frameBuilder,
      width: width,
      height: height,
      fit: fit,
      alignment: alignment,
      repeat: repeat,
      matchTextDirection: matchTextDirection,
      gaplessPlayback: true,
      excludeFromSemantics: true,
      filterQuality: FilterQuality.medium,
    );
  }
```

**Comment by cmkweber** [comment]
Yep, that works too. I think FadeInImage should be able to pass all the relevant parameters to RawImage though.

**Comment by christophemacabiau** [comment]
useful because of https://github.com/flutter/flutter/issues/60120

**Comment by goderbauer** [comment]
This was added in https://github.com/flutter/flutter/pull/110096.
