### ISSUE TITLE
Error in image_picker 0.5.0+3

### ISSUE THREAD

**Issue by MVelascoFlores** [flutter/flutter#29003]
## Steps to Reproduce

Using image_picker: ^0.5.0+3 in android when i hit the button to open the camera or gallery this appear in the console:
I/Timeline(16086): Timeline: Activity_launch_request time:948458985 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }

I the androidManifest i got this
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
`

```
```

```
```

```
```

**Comment by ened** [comment]
Please share the output of `flutter doctor -v` and further logs.

**Comment by MVelascoFlores** [comment]
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale es_MX.UTF-8)
    • Flutter version 1.2.1 at /home/mvelasco/.desarrollo/flutter
    • Framework revision 8661d8aecd (hace 4 semanas), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/mvelasco/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/mvelasco/.desarrollo/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.3)
    • Android Studio at /home/mvelasco/.desarrollo/android-studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Redmi Note 4 • 33d299210104 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by cyanglaz** [comment]
Should be fixed by https://github.com/flutter/plugins/pull/1519. Closing this issue now. If any related issue has been found after applying using the newest Image_picker, please open another issue with details.
