### ISSUE TITLE
Simple FadeTransition between two Widgets are laggy. 

### ISSUE THREAD

**Issue by smholsen** [flutter/flutter#29009]
A simpe transition between two Widgets lags in the start of the playback. 
See Video here: https://giphy.com/gifs/5dWEJgbgZYrVGL9121/html5
(Run on Samsung Galaxy S8+)

## Steps to Reproduce

https://gist.github.com/smholsen/42ca0aac6df63fd4b793f3781c166371

This gist contains three files. main.dart initializes the app with a SplashScreen widget which shows a text. After 3 seconds a fade transitions is played, transitioning to the Home Screen. [(See  here)](https://gist.github.com/smholsen/42ca0aac6df63fd4b793f3781c166371#file-screens-splashscreen-index-dart-L23)

The transition is laggy, Please see [this video](https://giphy.com/gifs/5dWEJgbgZYrVGL9121/html5). It shows how the transition is laggy the first time, and smooth when going back. 

To reproduce: 
1. Start a new Flutter project and copy-paste the files from the gist to the project. 
2. Start the app and watch the transitions.

```
Analyzing test...
No issues found! (ran in 2.4s)

```

```
√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale en-US)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\...\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G955F • ce05171563dd00930d • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

```

**Comment by TahaTesser** [comment]
Hi @smholsen 
Testing your code `Flutter 1.12.13+hotfix.8`, doesn't seem to be laggy.
If you're still experiencing this issue, please create a new issue and provide the information required in the template.
Thank you
