### ISSUE TITLE
gradlew crashes on the Cirrus Windows images

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#29017]
This is preventing us from running, e.g., the gradle_plugin_test on Windows.

/cc @fkorotkov fyi

**Comment by fkorotkov** [comment]
Do you have a link to a crash?

**Comment by dnfield** [comment]
https://cirrus-ci.com/task/5098787207905280

In that one I printed out gradlew.bat to make sure I had the right one.  The next line after that is 

> [gradle_plugin_test] [STDERR] CreateProcessW failed 2
[gradle_plugin_test] [STDOUT] Cleaning up after task...

Which is coming from the invocation of `gradlew.bat`.

**Comment by Hixie** [comment]
Looks like we run Gradle on Windows on Cirrus fine now.

**Comment by Hixie** [comment]
e.g. https://cirrus-ci.com/task/5095302038290432
