### ISSUE TITLE
Different notification format for Android and iOS

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#29027]
firebase_messaging: 4.0.0+1

There is a different notification format for iOS and Android - parameter for onMessage callback.

iOS:
{google.c.a.c_l: 20190226 - en, google.c.a.c_id: 2741820249588377404, gcm.n.e: 1, google.c.a.e: 1, count: 2, gcm.message_id: 0:1552019268226658%929750ef929750ef, path: lists_custom/2019-02-26/list, action: list, google.c.a.udt: 0, google.c.a.ts: 1552019268, aps: {alert: 2 new flowers were added to the herbary}, click_action: FLUTTER_NOTIFICATION_CLICK}

Android:
{notification: {title: null, body: 2 new flowers were added to the herbary}, data: {action: list, path: lists_custom/2019-02-26/list, count: 2, click_action: FLUTTER_NOTIFICATION_CLICK}}

**Comment by collinjackson** [comment]
I'm not sure if we should try to unify these automatically or just document the format.

**Comment by miquelbeltran** [comment]
I faced the same issue today, to bypass it I use this snippet here:

```
    var data = message['data'];
    if (Platform.isIOS) {
      data = message;
    }
```

That way I can later parse the `data` as I will do both on Android and iOS.

For example doing:
```
    final customValue = data['my_custom_value'];
```

I guess this is a problem on FCM side and not a Flutter problem, but would be good if the Flutter plugin documentation was more complete.

**Comment by kroikie** [comment]
@benadrasni

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1065. Any further collaboration will be done there.
