### ISSUE TITLE
══╡ EXCEPTION CAUGHT BY GESTURE  I/flutter ( 5507): The following assertion was thrown while handling a gesture: I/flutter ( 5507): type '_InternalLinkedHashMap<String, List<dynamic>>' is not a subtype of type 'Map<String,  List<Map<String, dynamic>>>' :( please tell me why ? i'm a newbie with flutter so i'm understanding issue :'( 

### ISSUE THREAD

**Issue by namanh007** [flutter/flutter#29026]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by namanh007** [comment]
define data    
 Map<String,List<dynamic>> data={};
                Map<String, String> clientId= Map();
                Map<String, String> storeId= Map();
                Map<String, int> finalPrice= Map();
                Map<String, int> totalPrice= Map();
                Map<String, String> userId= Map();
                Map<String, List<PreOrderProductInfo>> products= Map();
                Map<String, int> discount= Map();
                clientId["client_id"]=accountInfo.clientId;
                storeId["store_id"]="598c24d680fa54192752fb6c";
                userId["user_id"]="598c0e8aac74da151fbf97c6";
                finalPrice["final_price"]=total;
                totalPrice["total_price"]=total;
                discount["discount"]=0;
                products["products"]=listPreProductInfo;
                data["data"]= [clientId,storeId,finalPrice,totalPrice,userId,products,discount];
                _orderProductBloc.requestOrderCommand.execute(data);
                  showOrderSuccessDialog(context,title: "ORDER SUCCESS");
                },
when i add command(
requestOrderCommand= RxCommand.createAsync((preOrder) async{
      if (preOrder != null) {
        var authInfo = await RequestOrderApi().requestOrder(preOrder);
        resultOrderCommand.execute(authInfo);
      }
    });
)

**Comment by namanh007** [comment]
class parse data
class RequestOrderApi extends BaseApi<Map<String,List<Map<String,dynamic>>> >{

  Future<Map<String,List<Map<String,dynamic>>>> requestOrder(Map<String,List<Map<String,dynamic>>> preOrder) {
    var body = preOrder;
    return post(body: body,needToken: true);
  }
  @override
  String apiUrl() {
    // TODO: implement apiUrl
    return "order";
  }

  @override
  Future<Map<String,List<Map<String,dynamic>>> > responseParse(String body) {
    // TODO: implement responseParse
    return compute<String, Map<String,List<Map<String,dynamic>>> >(_orderParse, body);
  }
  Map<String,List<Map<String,dynamic>>>  _orderParse(String body) {
    var map = json.decode(body);
    return map;
  }
}

**Comment by namanh007** [comment]
please help me :(

**Comment by namanh007** [comment]
i'm work it,Please disregard

**Comment by Piinks** [comment]
> i'm work it,Please disregard

Hi @namanh007, does this mean your issue has been resolved?
