### ISSUE TITLE
fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by joeythomaschaske** [flutter/flutter#29028]
I'm trying to include the [secure storage package](https://github.com/mogol/flutter_secure_storage) but after adding the package I always end up getting the error Flutter/Flutter.h file not found.

If I delete the flutter SDK and reinstall it everything works fine until I close my application and need to run it again.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.9-pre.18, on Mac OS X 10.14.3 18D109, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.32.1)
[✓] Connected device (1 available)
```

```
Macbook-pro:app joseph$ flutter run
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...                                              1.0s
Running Xcode build...                                                  
Xcode build done.                                            0.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET flutter_secure_storage OF PROJECT Pods WITH CONFIGURATION Debug ===
    In file included from
    /Users/joseph/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.2.0/ios/Classes/FlutterSecureStoragePlug
    in.m:1:
    /Users/joseph/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.2.0/ios/Classes/FlutterSecureStoragePlug
    in.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
```

Whats weird is even if I create a new flutter project after running `flutter create newone` and `flutter run` the new project doesn't work either. 

```
Macbook-pro:newone joseph$ flutter run
Launching lib/main.dart on iPhone XR in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           1.2s
 └─Compiling, linking and signing...                         0.1s
Xcode build done.                                            2.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/joseph/PantryPal2/newone/ios/Runner/GeneratedPluginRegistrant.m:5:
    /Users/joseph/PantryPal2/newone/ios/Runner/GeneratedPluginRegistrant.h:8:9: fatal error: 'Flutter/Flutter.h' file
    not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone XR
```

I've seen plenty of other Flutter.h file missing errors but none of their solutions seem to work except for uninstalling the sdk and reinstalling. It seems as if installing that package corrupts the entire sdk.

**Comment by mboeddeker** [comment]
Same Issue here. Looks like a bug, since last Flutter Update ?

**Comment by joeythomaschaske** [comment]
@mboeddeker I downgraded cocoa pods to 1.4 and it seems to work fine now

Check this out and see if that also does the trick for you.
https://stackoverflow.com/questions/20487849/how-to-downgrade-or-install-an-older-version-of-cocoapods

This begs the question if this is a flutter issue, or is it a package issue?

**Comment by joeythomaschaske** [comment]
Update:
I tried editing my pubspec.yml outside of vscode and manually ran `flutter packages get` inside my app folder. Normally I would let the vscode extension handle getting the packages after saving the file.

Then I ran the app running `flutter run`. With the app running I imported the package into my dart code and hot reloaded. Then I used the package in my dart code and again ran hot reload and everything is still working. I've stopped the app and restarted and it's persistent. 

I'm not sure if this is maybe a vscode extension issue with `flutter packages get`?

**Comment by mboeddeker** [comment]
@joeythomaschaske Ok thank you! I will try it.

**Comment by mboeddeker** [comment]
Yeah same here. Worked one time only. No solutions helps.

**Comment by joeythomaschaske** [comment]
Interesting. My second solution hasn't failed me yet 🤞

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
