### ISSUE TITLE
Double tapping on a back button can lead to a crash

### ISSUE THREAD

**Issue by grundid** [flutter/flutter#29037]
Some of my users managed to double tap on a back button. This then leads to a blank screen and the following exception.

You can easily reproduce it when you introduce a WillPopScope widget with some delay in it:

```dart
WillPopScope(
  onWillPop: () async {
    await Future.delayed(Duration(seconds: 5));
    return true;
}
```

Now tap multiple times on the back button. The navigator then closes all of the screens and the app crashes.

I'm using 
[✓] Flutter (Channel dev, v1.3.4, on Mac OS X 10.14.3 18D109, locale de-DE)

> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
> #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
> #1      Route.didComplete 
> package:flutter/…/widgets/navigator.dart:187
> #2      Route.didPop 
> package:flutter/…/widgets/navigator.dart:175
> #3      OverlayRoute.didPop 
> package:flutter/…/widgets/routes.dart:61
> #4      TransitionRoute.didPop 
> package:flutter/…/widgets/routes.dart:207
> #5      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop 
> package:flutter/…/widgets/routes.dart:523
> #6      NavigatorState.pop 
> package:flutter/…/widgets/navigator.dart:2005
> #7      NavigatorState.maybePop 
> package:flutter/…/widgets/navigator.dart:1967
> <asynchronous suspension>
> #8      Navigator.maybePop 
> package:flutter/…/widgets/navigator.dart:1291
> #9      BackButton.build.<anonymous closure> 
> package:flutter/…/material/back_button.dart:91
> #10     _InkResponseState._handleTap (package:flutter/src/material/ink<…>
>

**Comment by HansMuller** [comment]
Thanks for the report!

It would help if you could provide a small self-contained app that demonstrates the problem you've run into.

Also: what's the reason for adding the delay in `onWillPop()`? If it's just there to expose a bug that occurs in a more complex scenario that's OK, and thanks for simplifying things.

**Comment by grundid** [comment]
Well, basically you can add the above widget in any scaffold and the error should be visible.

The error occurred in a settings view where we save the modified settings to Firestore in the onWillPop method. The method returns always true, but also awaits the save result. This led to a delay and some really fast testers managed to bring the app down. We could skip the `await` so the delay would not occur.

**Comment by HansMuller** [comment]
I haven't seen the error you reported with this simple app: https://gist.github.com/HansMuller/327c73cf2e229aac439fe295811b00ec

However back twice (Android) exits the app after the first back gesture's 5 second delay has expired.  I believe that we process the back button that way because in a deeply nested app users assume that quickly tapping the back button N times will pop N levels of the app.

**Comment by HansMuller** [comment]
I think what you want to do is to veto pop requests while the app is waiting. Here's an example: https://gist.github.com/HansMuller/16ed23ef6feb4fd27c3fa47ad94fff53

**Comment by grundid** [comment]
Here is an example that creates the error:
https://gist.github.com/grundid/59a7987d8662f22439183cffaff1ec11

Just tap back multiple times to see the above exception. If you just press back twice, the app is "somehow" closed, but the user sees a black screen.

**Comment by HansMuller** [comment]
To inhibit the back button while a WillPopScope callback is sleeping please use the approach in https://gist.github.com/HansMuller/16ed23ef6feb4fd27c3fa47ad94fff53

**Comment by TahaTesser** [comment]
Hi @grundid 
If you're still experiencing this issue, please try [solution](https://github.com/flutter/flutter/issues/29037#issuecomment-472575571)
If it doesn't solve your issue, please a create a new issue and provide necessary details
Thank you
