### ISSUE TITLE
About flutter/video_player some question

### ISSUE THREAD

**Issue by inixue** [flutter/flutter#29034]
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter.io/videoPlayer)
```
please answer me quickly.

**Comment by ozzy1873** [comment]
Same problem here

**Comment by inixue** [comment]
I did the same. It didn't work. Interaction between native and Flutte, android is OK, ios have this problem.

**Comment by hubcarl** [comment]
I had the same problem on ios device, andriod is OK.

**Comment by iapicca** [comment]
Hi @inixue 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
