### ISSUE TITLE
The parameter 'options' isnt defined and the method GoogleMapOptions isnt define for class

### ISSUE THREAD

**Issue by SuriahKamaruddin** [flutter/flutter#29031]
I have problem with the "options: GoogleMapOptions" part, where the options is not define. Am i missing something? Im new with flutter.  

This is my main.dart

**import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'dart:async';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Google Map',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Google Map'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
          GoogleMap(
            onMapCreated: (GoogleMapController controller) {},
            options: GoogleMapOptions(
              cameraPosition: CameraPosition(
                target: LatLng(37.4219999, -122.0862462),
              ),
            ), initialCameraPosition: null,
          ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}**

where the pubspec i had include

google_maps_flutter:
    git:
      url: git://github.com/flutter/plugins
      path: packages/google_maps_flutter

**Comment by jatinmadaan8** [comment]
I'm getting the same problem.

**Comment by SuriahKamaruddin** [comment]
Well i change the version of google_maps_flutter and its work already

**Comment by jatinmadaan8** [comment]
@SuriahKamaruddin Which version are you using ?

**Comment by changstagangsta** [comment]
was this ever resolved?

**Comment by SuriahKamaruddin** [comment]
Yes, I change the class name.

**Comment by changstagangsta** [comment]
could you be more specific?

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by Jessicatcheyanou** [comment]
Facin this same issue with the latest version of google_flutter_maps ..Please help!

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by Ankitrao91** [comment]
First create CameraPosition _kGooglePlex = .....//  then use in GoogleMap( initialCameraPosition: _kGooglePlex). as it shows here [https://pub.dev/packages/google_maps_flutter](url). Don't know if I am correct.
