### ISSUE TITLE
Exception using EditableText

### ISSUE THREAD

**Issue by derekdreery** [flutter/flutter#29046]
The program output asked me to submit this bug report. I'm pretty sure I'm using the widgets incorrectly.

My heierarchy is

```
ListView -> [Card] -> ExpansionTile -> [ListTile] -> (title: EditableText) -> (controller: TextEditiongController) -> (text: "Test")
```

And the output that asked me to report this is

<details>
<summary>Exception output</summary>
<pre>
Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 9154): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9154): The following assertion was thrown building PatientCard(dirty):
I/flutter ( 9154): 'package:flutter/src/widgets/editable_text.dart': Failed assertion: line 234 pos 15: 'focusNode !=
I/flutter ( 9154): null': is not truetext: "Test".
I/flutter ( 9154): 
I/flutter ( 9154): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9154): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9154): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9154):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9154): 
I/flutter ( 9154): When the exception was thrown, this was the stack:
I/flutter ( 9154): #2      new EditableText (package:flutter/src/widgets/editable_text.dart:234:15)
I/flutter ( 9154): #3      PatientCard.build (package:patient_notes/main.dart:63:20)
I/flutter ( 9154): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter ( 9154): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter ( 9154): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #7      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #25     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
I/flutter ( 9154): #26     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:980:34)
I/flutter ( 9154): #27     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter ( 9154): #28     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:991:36)
I/flutter ( 9154): #29     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:957:7)
I/flutter ( 9154): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #33     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #37     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9154): #38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9154): #39     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter ( 9154): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #79     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #83     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #87     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #91     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #93     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter ( 9154): #94     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter ( 9154): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #112    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #126    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #130    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #134    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #138    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
Reloaded 1 of 471 libraries in 390ms.
I/flutter ( 9154): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #144    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #150    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #152    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #156    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #160    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #163    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #164    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #170    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #172    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #175    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #176    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 9154): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #180    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 9154): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 9154): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #186    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 9154): #187    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter ( 9154): #188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter ( 9154): #189    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 9154): #190    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter ( 9154): #191    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 9154): #192    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 9154): #193    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 9154): #194    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 9154): #195    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter ( 9154): #197    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter ( 9154): #198    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter ( 9154): #199    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 9154): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 9154): ════════════════════════════════════════════════════════════════════════════════════════════════════
</pre>
</details>

**Comment by derekdreery** [comment]
If you would like any other details just let me know.

**Comment by HansMuller** [comment]
Please submit a small (smallish) self-contained app that demonstrates the problem and we'll look into it.

Note also: I assume that by "I'm pretty sure I'm using the widgets incorrectly" you meant that you're pretty sure you're using the widgets correctly?

**Comment by derekdreery** [comment]
Hehe - no I mean I'm using the widgets incorrectly. I've switched to a `TextField` and it works fine (I'm using  material design). I'll have a go at a MRE.

**Comment by derekdreery** [comment]
Update: here is a minimal-reproducing-example

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("Bug Test"),
        ),
        body: ListView.builder(itemBuilder: (context, idx) {
          return Card(
            child: ExpansionTile(
              title: Text("Test"),
              children: <Widget>[
                ListTile(
                  title: EditableText(
                    controller: TextEditingController(
                      text: "Test"
                    ),
                  )
                )
              ],
            ),
          );
        }),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          tooltip: 'Test',
          child: Icon(Icons.add)
        )
      ),
    );
  }
}
```

**Comment by HansMuller** [comment]
I think that test case is a little too simplified to demonstrate the problem you ran into originally. To use EditableText directly you need to provide its [required parameters ](https://docs.flutter.io/flutter/widgets/EditableText/EditableText.html) and it should be the descendant of a WidgetsApp or a MaterialApp.

**Comment by derekdreery** [comment]
So yeah the issue I had was that I hadn't supplied all the required parameters - namely focusNode.

**Comment by derekdreery** [comment]
I could close this, or maybe there could be improvements in error diagnostics to close it.

**Comment by HansMuller** [comment]
Currently the failure is:
```
I/flutter (22230): 'package:flutter/src/widgets/editable_text.dart': Failed assertion: line 305 pos 15: 'focusNode !=
I/flutter (22230): null': is not true.
I/flutter (22230): 
```
In cases like this it would probably be a little more helpful to say that "required EditableText parameter focusNode cannot be null". We could even provide a pointer to the parameter's API doc.

I'll open a Dart SDK issue about this.
