### ISSUE TITLE
 MIssue from website page Flutter Widget框架概述

### ISSUE THREAD

**Issue by qingxo** [flutter/flutter#29044]
From URL: https://www.flutterchina.club/widgets-intro.md

**Comment by chenglu** [comment]
Hi @qingxo, there will be a community translated CN documents [here](https://debug.flutter.cn), may release the 1st translation version before May, more details about this project [here](https://github.com/cfug/flutter.cn), thanks!

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
