### ISSUE TITLE
Implement statfs - Filesystem Information

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#29042]
### file system statistics
which plugin should implement statfs?
**path_provider** or **device_info**?

- https://developer.android.com/reference/android/os/StatFs
- https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/statfs.2.html

**Comment by p30arena** [comment]
It appears that Directory has a stat method which represents the os's stat method.

> Calls the operating system's stat() function on the [path] of this [FileSystemEntity].

**Comment by p30arena** [comment]
Unfortunately, Dart's stat function doesn't give info about free space.

**Comment by p30arena** [comment]
Where are you @zoechi ?
I miss your labels :smile:

**Comment by p30arena** [comment]
@escamoteur 
Hi Thomas,
I wanted to manage my app's file cache,
So I needed to know how much space is left on the disk.

**Comment by escamoteur** [comment]
If you know how do do this on the native side any PR would expedite this issue :-)

**Comment by stuartmorgan** [comment]
Closing as `device_info` is deprecated in favor of [`device_info_plus`](https://pub.dev/packages/device_info_plus).
