### ISSUE TITLE
FlatButton and OutlineButton do not follow ambient theme as docs describe

### ISSUE THREAD

**Issue by nhwilly** [flutter/flutter#29050]
In the [docs here](https://docs.flutter.io/flutter/material/ButtonTheme-class.html) (and quoted below) it seems like the button theme specified in `ThemeData.buttonTheme` for the app should apply to `FlatButton` and `OutlineButton` as well as `RaisedButton`, but it's not.  

Side by side, raised buttons are showing the theme set in  `ThemeData.buttonTheme` and the others are ignoring it.

Is that the plan, a feature or a problem?  I know I can override it all, I'm just trying to make sure I'm not making some simple mistake.

`ButtonTheme class 

Used with ButtonThemeData to configure the color and geometry of buttons.
A button theme can be specified as part of the overall Material theme using ThemeData.buttonTheme. The Material theme's button theme data can be overridden with ButtonTheme.
The actual appearance of buttons depends on the button theme, the button's enabled state, its elevation (if any), and the overall Theme.
See also:
FlatButton RaisedButton, and OutlineButton, which are styled based on the ambient button theme.
RawMaterialButton, which can be used to configure a button that doesn't depend on any inherited themes.`

**Comment by HansMuller** [comment]
The way the material buttons depend on the theme's buttonTheme and some of the theme's generic properties is complicated (sorry) in part for the sake of backwards compatibility. The API docs for [ButtonThemeData ](https://docs.flutter.io/flutter/material/ButtonThemeData-class.html) try to expose all of the dependencies (again: sorry). If there are specific examples where you'd expect an OutlineButton or FlatButton to respect the ButtonTheme and it doesn't please list them here.

Inside an app you may find it easier to create app-specific buttons. This kind of thing:
```
class MyButton extends StatelessWidget {
  const MyButton({ Key key, this.onPressed, this.child }) : super(key: key);

  final VoidCallback onPressed;
  final Widget child;

  @override build(BuildContext context) {
    return OutlineButton(
      // your configuration here
      onPressed: onPressed,
      child: child,
    );
  }
}
```

**Comment by nhwilly** [comment]
Thanks for responding.

I'm interested supplying user selectable themes and allowing them to change dynamically.  

I'll probably do some combination of my own theme class which has themeData and other properties to be able to get what I want.  I also expect to have some of my own button classes as well.

I was actually more concerned that the documentation didn't match.  When that happens, you end up doing lots of experimentation to find out what really works and then you wonder what will change in some future update when you're not looking.  🙂
