### ISSUE TITLE
Move all version and upgrading logic to a secondary tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29063]
Currently the flutter tool that most people use does not have the capability to handle a hotfix upgrade. Even if we added this today, it would not exist on the previous stable releases, any of the beta releases. Because of how we ship the flutter_tool with the flutter sdk, it is impossible to hot fix the tool that people are using to ... add support for hot fixing the tool.

Instead we should publish a minimal secondary program who's sole purpose is to upgrade/downgrade flutter versions. This could just be a thin wrapper over some git commands. We could publish this via pub such that `pub global activate flutter_upgrade` installs the command, which would in turn be usable via `flutter` today.

All flutter users, regardless of their flutter version would always be able to use the most up to date version of this tool, since it does not have any flutter related logic and does not effect their sdk version.

cc @tvolkert @kf6gpe @zanderso

**Comment by tvolkert** [comment]
So the UX would still flow through the tool, but the de-coupling allows for us to issue fixes without having a chicken-and-egg problem of delivering those fixes to users?

**Comment by jonahwilliams** [comment]
Yes, behind the scenes the tool would essential call `pub global activate <<name>>``. Older versions of the tool wouldn't support this, but we could always direct users to install and run manually

**Comment by jonahwilliams** [comment]
Discussed offline, we're not going to do this and just concentrate on landing these efforts in the tool itself
