### ISSUE TITLE
[firebase_messaging] Please add all fields to FCM message (Android)

### ISSUE THREAD

**Issue by Alezhka** [flutter/flutter#29066]
Now [firebase_messaging](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging) provide to onMessage only two parameters inside notification map: 'title' and 'body'.  [FirebaseMessagingPlugin.java](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java#L82)

Please add also other parameters from docs:
icon
color
sound
tag
click_action
body_loc_key
body_loc_args[]
title_loc_key
title_loc_args[]
channel_id

[Firebase docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)
[Android docs](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification)

**Comment by kroikie** [comment]
@Alezhka

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1064. Any further collaboration will be done there.
