### ISSUE TITLE
No shrinking for BackdropFilter's cull rect

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#29070]
Currently, it's easy to misunderstand how `BackdropFilter` works because its area of effect depends on Skia's cull rect. Skia views that cull rect only as a performance optimization hint so it can freely modify it to any rect that encloses the child. Therefore it's hard to predict the cull rect's exact size.

One example of such confusion is
```
BackdropFilter(
  child: Container(width: 200, height: 200, child: Text('Hello')),
  ...
);
```

Many expect the filter to be applied to the full container of size 200x200. Instead, Skia only sees a `drawText` call which has an small area of 'Hello', so it reduces the filter area to just around that 'Hello' text.

By fixing this this issue, Flutter will always set `BackdropFilter`'s area of effect to fill its parent/ancestor clip (full screen if unclipped). This is more in line with our clip behaviors (no clip by default), but it doesn't directly achieve a 200x200 filtered area using the code above.

In order to get the filtered area of 200x200 when this issue is fixed, one has to write the following code

```
ClipRect(
  child: BackdropFilter(
    child: Container(width: 200, height: 200, child: Text('Hello')),
  )
);
```

If this breaks your app, wrap the `BackdropFilter` with a `ClipRect`  (or some other clip of your choice).

Related issues: https://github.com/flutter/flutter/issues/10148 (BackdropFilter only shrinks when there's a child text widget), https://github.com/flutter/flutter/issues/16148 (BackdropFilter doesn't match the size of of its child).

To fully fix this issue, we have a 3-step plan to accommodate our golden tests infrastructure.

1. Land https://github.com/flutter/flutter/pull/28174 with the transparent paint hack to change the behavior with pure framework (flutter/flutter) changes.
2. Modify `BackdropFilterLayer` in flutter/engine to send a nullptr bounds (instead of `paint_bounds`) to `SaveLayerRec` in https://github.com/flutter/engine/blob/master/flow/layers/backdrop_filter_layer.cc#L19
3. Wait for the engine change to roll into the framework; then remove the transparent paint hack.

Such plan ensures that our engine roll won't be blocked by a golden image mismatch.

**Comment by xster** [comment]
I'm a bit confused by the terminology used. Isn't the example above better explained by saying the BackdropFilter's area of effect fills its child's size rather than its parent's clip?

**Comment by liyuqian** [comment]
Currently, the area is the text. After the change, the area will be the whole screen if no clip is added. In order to match its child's size, a `ClipRect` needs to be added to wrap the `BackdropFilter`.

**Comment by xster** [comment]
Ah I see. We should clarify the wording a bit and point out that while "Many expect the filter to be applied to the full container of size 200x200.", the new behavior also doesn't do that :D

**Comment by liyuqian** [comment]
Done. Thanks!

**Comment by liyuqian** [comment]
Oops, it seems that Skia has fixed this several weeks ago by ignoring the bounds when there's a backdrop filter: https://skia-review.googlesource.com/c/skia/+/194601 . Because of this, we no longer have to set the bounds to nullptr (see the step 2 above). Skia will set it to nullptr internally.

In the engine, however, we're clipping to paint_bounds instead of clip_rect in ClipRectLayer. Fixing it in  https://github.com/flutter/engine/pull/8183
