### ISSUE TITLE
Improve stacktrace for EXCEPTION CAUGHT BY RENDERING LIBRARY

### ISSUE THREAD

**Issue by ricardobrg** [flutter/flutter#29075]
The rendering library gives really good output on exceptions. It explains what the error is and what is causing it. I believe that it could be improved in the stack trace, because it doesn't show the part of my code that is causing the exception. 

Let me try to make it more clear. Let's say that I nest a scrollview inside another in main.dart. It will throw a Rendering Library exception because the height is unbounded, but in the stacktrace it will not mention main.dart, just the libraries' and Flutter's core code. Sometimes it is possible to figure out wich widget caused the error, because it gives the RenderObject, but when the layout gets a little bit more complex, most of the time I just get myself trying to guess wich part of my code is causing the error. 

I was thinking if it is possible to have the rendering library exception to trace the error back to the code that the user is writing, making it even easier to debug the error, based on the exception thrown by rendering library.

**Comment by ricardobrg** [comment]
This is the kind of output that Rendering Library gives on exception

    I/flutter ( 7671): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
    I/flutter ( 7671): The following assertion was thrown during performResize():
    I/flutter ( 7671): Vertical viewport was given unbounded height.
    I/flutter ( 7671): Viewports expand in the scrolling direction to fill their container.In this case, a vertical
    I/flutter ( 7671): viewport was given an unlimited amount of vertical space in which to expand. This situation
    I/flutter ( 7671): typically happens when a scrollable widget is nested inside another scrollable widget.
    I/flutter ( 7671): If this widget is always nested in a scrollable widget there is no need to use a viewport because
    I/flutter ( 7671): there will always be enough vertical space for the children. In this case, consider using a Column
    I/flutter ( 7671): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
    I/flutter ( 7671): the height of the viewport to the sum of the heights of its children.
    I/flutter ( 7671):
    I/flutter ( 7671): When the exception was thrown, this was the stack:
    I/flutter ( 7671): #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1135:15)
    I/flutter ( 7671): #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1188:6)
    I/flutter ( 7671): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1617:9)
    I/flutter ( 7671): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #21     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
    I/flutter ( 7671): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #23     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
    I/flutter ( 7671): #24     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
    I/flutter ( 7671): #25     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
    I/flutter ( 7671): #26     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
    I/flutter ( 7671): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #31     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
    I/flutter ( 7671): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
    I/flutter ( 7671): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #47     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3030:14)
    I/flutter ( 7671): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
    I/flutter ( 7671): #49     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
    I/flutter ( 7671): #50     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
    I/flutter ( 7671): #51     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
    I/flutter ( 7671): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
    I/flutter ( 7671): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
    I/flutter ( 7671): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
    I/flutter ( 7671): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
    I/flutter ( 7671): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
    I/flutter ( 7671): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
    I/flutter ( 7671): #61     _invoke (dart:ui/hooks.dart:209:10)
    I/flutter ( 7671): #62     _drawFrame (dart:ui/hooks.dart:168:3)
    I/flutter ( 7671): (elided 3 frames from package dart:async)
    I/flutter ( 7671):
    I/flutter ( 7671): The following RenderObject was being processed when the exception was fired:
    I/flutter ( 7671):   RenderViewport#60404 NEEDS-LAYOUT NEEDS-PAINT
    I/flutter ( 7671):   creator: Viewport ← IgnorePointer-[GlobalKey#9176f] ← Semantics ← Listener ← _GestureSemantics ←
    I/flutter ( 7671):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#5008f] ← _ScrollableScope ←
    I/flutter ( 7671):   _ScrollSemantics-[GlobalKey#77cff] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
    I/flutter ( 7671):   NotificationListener<ScrollNotification> ← ⋯
    I/flutter ( 7671):   parentData: <none> (can use size)
    I/flutter ( 7671):   constraints: BoxConstraints(0.0<=w<=320.0, 0.0<=h<=Infinity)
    I/flutter ( 7671):   size: MISSING
    I/flutter ( 7671):   axisDirection: down
    I/flutter ( 7671):   crossAxisDirection: right
    I/flutter ( 7671):   offset: ScrollPositionWithSingleContext#8bebe(offset: 0.0, range: null..null, viewport: null,
    I/flutter ( 7671):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#69dcb,
    I/flutter ( 7671):   ScrollDirection.idle)
    I/flutter ( 7671):   anchor: 0.0
    I/flutter ( 7671): This RenderObject had the following descendants (showing up to depth 5):
    I/flutter ( 7671):   RenderSliverPadding#f46d1 NEEDS-LAYOUT NEEDS-PAINT
    I/flutter ( 7671):     RenderSliverList#b5c4d NEEDS-LAYOUT NEEDS-PAINT
    I/flutter ( 7671): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jonahwilliams** [comment]
> I was thinking if it is possible to have the rendering library exception to trace the error back to the code that the user is writing, making it even easier to debug the error, based on the exception thrown by rendering library.

It would be very nice, but it isn't always possible if user code isn't in the stack somewhere. There is some good news, we are working on better formatting/hints/descriptions: https://github.com/flutter/flutter/issues/27327 which should help, especially for the rendering exceptions.

**Comment by ricardobrg** [comment]
The Error Messages are very clear now, tracing all the way back to the original file. Could not find wich commit did that, if anyone find it, please comment. Nice job!

**Comment by jorwan** [comment]
How do you guys catch this kind of error to them log it or something else ?
