### ISSUE TITLE
FlutterActivity cannot click into

### ISSUE THREAD

**Issue by songsh** [flutter/flutter#29083]
my project can run, but FlutterActivity can not click into,

like this:
<img width="425" alt="屏幕快照 2019-03-09 上午11 55 09" src="https://user-images.githubusercontent.com/2272252/54065940-7b0a1f80-4262-11e9-9430-de23674ee078.png">

**Comment by dnfield** [comment]
Can you add some context to this?  Are you trying to add to an existing app?  Are you trying to modify the Runner template?  What does your dart code look like?

**Comment by songsh** [comment]
FlutterActivity is red,  -- Cannot find declaration to go to,    studio cannot find the file
i cannot modify the project, i download the project from the internet

**Comment by dnfield** [comment]
Please read through https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

You are likely missing references to the module.  However, this isn't really a bug either, please consider one of the other channels listed at https://flutter.dev/community for this kind of request.
