### ISSUE TITLE
Hot Reload/Restart not working at all !!

### ISSUE THREAD

**Issue by rohansohonee** [flutter/flutter#29087]
# Hot reload/restart does not work by doing the following in vscode:
- Ctrl-F5 (for hot restart)
- Ctrl-s (for reload and saving the file)
- Ctrl-Shift-F5

I  have to quit the entire application by pressing the stop icon in vscode, just to make a change to a Text Widget that is centered in the Scaffold body !!
Please fix ASAP.

## Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.348], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.32.1)
[√] Connected device (1 available)

• No issues found!

**Comment by CrazyCoderShi** [comment]
i had the same problem

**Comment by CrazyCoderShi** [comment]
but, android studio is still working

**Comment by CrazyCoderShi** [comment]
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tiannan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tiannan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone XR • 718E3213-BF17-438B-B1BA-D87E8348E8F7     • ios • iOS 12.1 (simulator)

**Comment by 7uthaifah** [comment]
Same problem here, after updating flutter to version 1.2.1.

**Comment by udiedrichsen** [comment]
I guess it's a VSCODE bug in 1.32.1 not a flutter issues:
https://stackoverflow.com/questions/55060461/vs-code-osx-flutter-hot-reload-is-not-triggered-by-save

**Comment by 7uthaifah** [comment]
Thanks @udiedrichsen, I actually update VSCode and Flutter at the same time so it might be VSCode problem as you mentioned.

**Comment by jonahwilliams** [comment]
Tracked here: Dart-Code/Dart-Code#1518

**Comment by DanTup** [comment]
(v1.32.2 of VS Code is live and contains the fix)

**Comment by CrazyCoderShi** [comment]
thx

**Comment by lifenduwi** [comment]
> (v1.32.2 of VS Code is live and contains the fix)

I'm having the same issue and the last release of VS Code (1.34.0) 
 didn't fix it!

**Comment by DanTup** [comment]
@lifenduwi please open a new issue with concrete details and a log - the issue you're hitting is likely different - this was a VS Code bug and was fixed. Thanks!

**Comment by cimplesid** [comment]
Facing same issue on flutter 1.19.0-4.1.pre on vs-code  1.46.1 windows 10

**Comment by soham1sawant** [comment]
Facing same issue on VS Code version 1.49.0

**Comment by DanTup** [comment]
Please file an issue at https://github.com/Dart-Code/Dart-Code with concrete details of what you're doing and what you're seeing. It's difficult to track problems tagged onto the end of old/closed bugs. Thanks!
