### ISSUE TITLE
Icon widget should appear white applying CupertinoTheme with dark brightness 

### ISSUE THREAD

**Issue by parsodyl** [flutter/flutter#29099]
- SDK version: Channel beta, v1.2.1.
- How to reproduce it:
1) Create a new CupertinoApp
2) Apply CupertinoTheme with dark brightness
3) Insert an Icon somewhere in the tree

Example:

```dart
class FCEApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'FCE App',
      theme: CupertinoThemeData(
        brightness: Brightness.dark,
      ),
      home: CupertinoPageScaffold(
        child: Center(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              const Icon(CupertinoIcons.profile_circled, size: 36),
              const SizedBox(width: 12),
              Expanded(
                child: Text('John Doe'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Result:

![Screen Shot 2019-03-09 at 16 25 21](https://user-images.githubusercontent.com/7900616/54073492-0649dc00-4288-11e9-9843-7ff23b5fb4fe.png)

=> The txt color becomes white but the icon's color remains black and that seems inconsistent.

**Comment by hyjfine** [comment]
The root case is icon in CupertinoApp can‘t get the right IconTheme. because there is no TYPE named IconTheme in map _inheritedWidgets(framework.dart).

**Comment by xster** [comment]
CupertinoTheme should also insert an IconTheme under it like the Material Theme widget does.
