### ISSUE TITLE
TextStyle.button is not in all caps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2909]
(not sure if this is something we want to do, but...)

The material design spec says that buttons should be all caps.

![screen shot 2016-03-25 at 1 03 59 pm](https://cloud.githubusercontent.com/assets/5479/14052815/2f4b0008-f28a-11e5-9617-60539cb4c251.png)

From https://www.google.com/design/spec/style/typography.html#typography-styles

However, when I use TextStyle.button, my text is not rendered in all caps:

![screen](https://cloud.githubusercontent.com/assets/5479/14052913/0e4ef886-f28b-11e5-9f70-ae12c395b94b.png)

Should using the button style be sufficient to get all caps?

**Comment by sethladd** [comment]
@HansMuller thoughts on if the "button" style should also capitalize?

**Comment by sethladd** [comment]
FWIW, Android auto-caps when using button style:

```
    <TextView
        android:id="@+id/button"
        android:layout_below="@id/caption"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        style="@style/Base.TextAppearance.AppCompat.Button"
        android:text="Subheader" />
```

Renders as:

![screen shot 2016-03-25 at 1 13 20 pm](https://cloud.githubusercontent.com/assets/5479/14052953/5de490ea-f28b-11e5-9070-a768ec58272b.png)

**Comment by abarth** [comment]
At some point in the past, we decide not to implement text-transform and related properties.  They cause a bunch of performance problems, especially if you support things like sentence case which are non-local transformations.

**Comment by sethladd** [comment]
Fair enough. Please close if we don't intend to change the behavior here.

**Comment by abarth** [comment]
We might want do so something with asserts or some other way of guiding the developer to do the right thing.

**Comment by Hixie** [comment]
Consider a button with the text 'çevirmek'. What should we display?

Consider a button with the text 'SOLVE FOR θ'. How should we know to not assert?

**Comment by abarth** [comment]
I'm going to close this issue as WONTFIX.  We've decided not to implement text-transform.  It's possible we should add an assert to help developers us all-caps in buttons but it's tricky to do case transformations accurately enough not to have false positives.
