### ISSUE TITLE
Make _DialogRoute part of the public API

### ISSUE THREAD

**Issue by dalewking** [flutter/flutter#29106]
The situation I have faced in multiple projects now is the desire to push a named route to a Navigator that pops up an AlertDialog. There is PopupRoute, but that is abstract and requires implementing multiple abstract methods.

There is showDialog, but that doesn't use a named route. The other problem is that showDialog requires a context, but I don't actually have a context at the point I am trying to push the route (my Redux Middleware is actually asking for the dialog to be shown). showDialog only uses the context to find the Navigator in order to push the route, but I already have the NavigatorState via a GlobalKey<NavigatorState>.

There is a class internally called _DialogRoute that is the concrete implementation of PopupRoute that is used by ShowDialog that does exactly what I need, but of course it is private.

So I end up on every project making a copy of that class in my own app, which tells me that this class should really be promoted to public. Another alternative that would satisfy my current project is if there were a variant of showDialog that accepted a NavigatorState instead of a BuildContext.

**Comment by dnfield** [comment]
Is there some reason you can't just call `showDialog(context: navigatorState.context, ...)`?

**Comment by dalewking** [comment]
> Is there some reason you can't just call showDialog(context: navigatorState.context, ...)?

Guess not on my current project, but not sure that satisfies the desire to use a named route unless there is an easy way to take care of that.

**Comment by dnfield** [comment]
AFAIK named routes are mainly just a convenience that points to a named route table.  Goderbauer is doing some work around that stuff that may or may not make this easier.

I can't think of a reason we shouldn't support looking up a named dialog route via `showDialog`, although he might be able to.

That said, you could probably just roll your own here pretty easily by having a `Map<String, WidgetBuilder>` somewhere with your named dialogs.

**Comment by dalewking** [comment]
Yes, you have a map. What I have done in a previous project that is a `Map<String, Widget Function(RouteSettings settings)>` and in my onGenerateRoute method something like this:

      final dialogBuilder = dialogMap[settings.name];

      if (dialogBuilder != null) {
        return DialogRoute<void>(pageBuilder: (context, anim, anim2) => dialogBuilder(settings));
      }

But that is relying on my copy of the DialogRoute class.

**Comment by dalewking** [comment]
> > Is there some reason you can't just call showDialog(context: navigatorState.context, ...)?
> 
> Guess not on my current project, but not sure that satisfies the desire to use a named route unless there is an easy way to take care of that.

Actually, doesn't work:

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
```

**Comment by tom95** [comment]
To add some use cases:
- displaying a dialog in response to  receiving a push notification
- displaying a dialog when an app link was opened

In both cases, the callbacks are registered on the app-level, where you do have access to a shiny Navigator, but `Navigator.of(context)` or `Navigator.of(navigator.context)` won't get `showDialog` that same Navigator, as these contexts are too high up in the hierarchy, as @dalewking pointed out.

The only workaround I found was, here too, to copy DialogRoute to my own project, so I can just my Navigator instance directly.

**Comment by tom95** [comment]
Turns out, I just stumbled over one more (risky?) workaround:
```dart
BuildContext anyChildContext(NavigatorState navigator) {
  BuildContext firstChild;
  navigator.context.visitChildElements((e) {
    if (firstChild == null)
      firstChild = e;
  });
  return firstChild;
}
```

**Comment by andywolff** [comment]
> Turns out, I just stumbled over one more (risky?) workaround:
> 
> ```dart
> BuildContext anyChildContext(NavigatorState navigator) {
>   BuildContext firstChild;
>   navigator.context.visitChildElements((e) {
>     if (firstChild == null)
>       firstChild = e;
>   });
>   return firstChild;
> }
> ```

Someone has suggested that this is better (especially if you have a global navigator key):
```
navigator.currentState.overlay.context
```

**Comment by Albert221** [comment]
Let me paste here my duplicate issue why I think `DialogRoute` should be public.

---

### Make `_DialogRoute` a public class
https://github.com/flutter/flutter/blob/7891006299/packages/flutter/lib/src/widgets/routes.dart#L1697-L1756

`_DialogRoute` is used in `showGeneralDialog` which is used in `showDialog`. Today, in the era of Navigator 2.0 it would be _really_ handy to have the ability of showing a material dialog in a declarative, not imperative way. 

## Use case

My specific use case uses declarative routes for deeplinks and "global" handlers. So that whenever user clicks on a specific deeplink he may be shown a dialog. I know I can do it the other way. I'm asking for the declarative approach.

## Proposal

My proposal is to make the `_DialogRoute` class a public one and prospectively make it viable to use in the userspace, not only inside the Flutter framework.

**Comment by TahaTesser** [comment]
This seems to be fixed, closing
https://master-api.flutter.dev/flutter/material/DialogRoute-class.html
https://master-api.flutter.dev/flutter/widgets/RawDialogRoute-class.html

cc: @chunhtai in case it is not
