### ISSUE TITLE
gitignore template should exclude android local.properties

### ISSUE THREAD

**Issue by shareme** [flutter/flutter#29109]
the missing item is this

# Local configuration file (sdk path, etc)
**/android/local.properties

almost made the mistake of not having that line before my git commits

**Comment by dnfield** [comment]
Would you be willing to open a pull request to make this change?

**Comment by rubensdemelo** [comment]
Where can I find this template? Im able to make a PR to fix it.

**Comment by dnfield** [comment]
Hmm.  It looks like this is already in place on master: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/.gitignore.tmpl#L36

@shareme can you share the .gitignore template you have?

**Comment by dnfield** [comment]
That item has been there since August of last year, so it should be available on stable...
