### ISSUE TITLE
flutter packages get Handshake error in client CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jt274** [flutter/flutter#29101]
I am following this tutorial and using Android Studio: https://flutter.dev/docs/get-started/codelab

I am at Step 2, and executing "flutter packages get" after adding a package to pubspec.yaml. I get the following error when running the command in Android Studio, or flutter packages get from CLI.

**Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))
pub get failed (69) -- attempting retry 1 in 1 second...**

Here is my flutter doctor -v output:

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Me\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Me\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!

I have disabled Windows Defender (no other antivirus) and no change. I've also set these environment variables with no change:

PUB_HOSTED_URL=https://pub.flutter-io.cn
FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

I can access https://pub.dartlang.org/flutter in Chrome with no security warnings. I also had no issues updating SDK packages from within Android Studio.

**Comment by dnfield** [comment]
Are you behind a proxy?  I'm pretty sure this is https://github.com/dart-lang/sdk/issues/25615


Please feel free to reopen if that doesn't resolve your issue.

**Comment by jt274** [comment]
I am not behind a proxy, but there may be some software configured on the computer that is acting as such. I am not sure how to get around it. I have tried all the proxy workarounds I can find, but can't make sense of how to setup a proxy server when I don't have a proxy...

I've tried setting https_proxy environment variable to localhost:8080, 127.0.0.1:8080, 127.0.0.1:443, etc. etc.

set https_proxy=127.0.0.1:8080 gives this error: Got socket error trying to find package english_words at https://pub.dartlang.org

Same result for localhost. I have no problem using npm, git, etc. from the same CLI.

**Comment by jt274** [comment]
It seems to me like it may be possible to resolve using the environment variable: DART_VM_OPTIONS=--root-certs-file=some_file

But in this case I'm not sure what certificate to use. I did install android studio and flutter on another computer on the same network with an identical setup and it worked perfectly out of the box with no changes. But I can't figure out why, and that isn't the computer I need to use for development.

**Comment by Aaron009** [comment]
@dnfield
 I have this problem too.
```dart
import 'dart:io';

main() async {
  HttpClient client = new HttpClient();
  var request = await client.getUrl(Uri.parse('https://shop.io.mi-img.com/app/shop/img?id=shop_88f929c5731967cbc8339cfae1f5f0ec.jpeg'));
  var response = await request.close();
  print(response.headers);
  client.close(force: true);
}
```

I found that if the link is `www.baidu.com`, it will not report an error. What is the reason and how can I solve it?
