### ISSUE TITLE
error, Attempt to invoke virtual method 'void I/flutter ( 2174): android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListener, I/flutter ( 2174): android.os.Handler

### ISSUE THREAD

**Issue by YuzhouZhang** [flutter/flutter#29116]
## Steps to Reproduce

This is a Camera plugin bug:
1. startImageStream at initState():
```
@override
  void initState() {
    print('camera page InitState');
    super.initState();
    _cameraController =
        new CameraController(cameras[0], ResolutionPreset.medium);
    _cameraController.initialize().then((_) {
      if (!mounted) {
        return;
      } else {
        _cameraController.startImageStream(onAvailable);
      }

      setState(() {
//        _cameraController.startImageStream(onAvailable);
      });
  }
```

2. stopImageStream at deactivate() or dispose(),
```
@override
  void deactivate() {
    print('camera page deactivate');
//    if (_cameraController != null &&
//        _cameraController.value.isStreamingImages &&
//        _cameraController.value.isInitialized &&
//        mounted) {
//      _cameraController?.stopImageStream();
//    }
    super.deactivate();
  }

  @override
  void dispose() {
    print('camera page dispose');
    if (mounted &&
        _cameraController.value.isStreamingImages &&
        _cameraController != null) {
      _cameraController?.stopImageStream();
    }
    _cameraController?.dispose();
    super.dispose();
  }
```

3. Everytime navigate to another page, exception raises.

## Logs

> [ +341 ms] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934): Failed to close event stream
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934): java.lang.NullPointerException: Attempt to invoke virtual method 'void
android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListener, android.os.Handler)' on a null object reference
[   +1 ms] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at io.flutter.plugins.camera.CameraPlugin$Camera$9.onCancel(CameraPlugin.java:822)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:194)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:162)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at
io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
[   +1 ms] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at android.os.MessageQueue.next(MessageQueue.java:326)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at android.os.Looper.loop(Looper.java:160)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at android.app.ActivityThread.main(ActivityThread.java:6718)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at java.lang.reflect.Method.invoke(Native Method)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/EventChannel#plugins.flutter.io/camera/imageStream( 4934):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[        ] I/flutter ( 4934): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
[        ] I/flutter ( 4934): The following PlatformException was thrown while de-activating platform stream on channel
[        ] I/flutter ( 4934): plugins.flutter.io/camera/imageStream:
[        ] I/flutter ( 4934): PlatformException(error, Attempt to invoke virtual method 'void
[   +1 ms] I/flutter ( 4934): android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListener,
[        ] I/flutter ( 4934): android.os.Handler)' on a null object reference, null)
[        ] I/flutter ( 4934): 
[        ] I/flutter ( 4934): When the exception was thrown, this was the stack:
[   +2 ms] I/flutter ( 4934): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
[        ] I/flutter ( 4934): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
[        ] I/flutter ( 4934): <asynchronous suspension>
[        ] I/flutter ( 4934): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:502:29)
[        ] I/flutter ( 4934): <asynchronous suspension>
[        ] I/flutter ( 4934): #9      CameraController.stopImageStream (package:camera/camera.dart:402:30)
[        ] I/flutter ( 4934): <asynchronous suspension>
[        ] I/flutter ( 4934): #10     _CameraPageState.dispose (package:quick_learners_dictionary/pages/camera_body.dart:97:26)
[        ] I/flutter ( 4934): #11     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3916:12)
[        ] I/flutter ( 4934): #12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1696:13)
[   +3 ms] I/flutter ( 4934): #13     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
[        ] I/flutter ( 4934): #14     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1705:25)
[        ] I/flutter ( 4934): #15     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2359:27)
[        ] I/flutter ( 4934): #16     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2191:15)
[        ] I/flutter ( 4934): #17     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2358:7)
[        ] I/flutter ( 4934): #18
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:702:18)
[        ] I/flutter ( 4934): #19
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:268:5)
[        ] I/flutter ( 4934): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:988:15)
[        ] I/flutter ( 4934): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:928:9)
[        ] I/flutter ( 4934): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:840:5)
[        ] I/flutter ( 4934): #26     _invoke (dart:ui/hooks.dart:209:10)
[        ] I/flutter ( 4934): #27     _drawFrame (dart:ui/hooks.dart:168:3)
[        ] I/flutter ( 4934): (elided 9 frames from package dart:async)
[        ] I/flutter ( 4934): ════════════════════════════════════════════════════════════════════════════════════════════════════

`No issues found! (ran in 20.5s)
`

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/zhangyuzhou/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/zhangyuzhou/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/zhangyuzhou/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/zhangyuzhou/android-studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/zhangyuzhou/Downloads/idea-IC-181.4892.42
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.32.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Pixel 2 XL • 805KPYR1822994 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

**Comment by dnfield** [comment]
I don't think this is the root cause, but at the very least your code here is out of order:

``` 
_cameraController.value.isStreamingImages &&
        _cameraController != null
```

You're trying to access the `_cameraController` before checking if it's null..  If it ever is null you'll get an exception there.  Swap those two.

**Comment by YuzhouZhang** [comment]
> two

Thank you for your reply.

I swapped and got the same exception. : )

**Comment by bparrishMines** [comment]
Hi @YuzhouZhang 

I think you may need an `await` for `controller.stopImageStream()`. It's asynchronous so this may be a race condition.

You could try

```
if (controller != null) {
  controller.stopImageStream().then((_) {
    controller.dispose();
  });
}
```

**Comment by bparrishMines** [comment]
You could also just call `controller?.dispose()`. This method should also stop all image streaming.

**Comment by YuzhouZhang** [comment]
> You could also just call `controller?.dispose()`. This method should also stop all image streaming.

Thanks a lot.
```
if (controller != null) {
  controller.stopImageStream().then((_) {
    controller.dispose();
  });
}
```
or
```
controller?.dispose()
```
both work fine for me.

**Comment by jasxir** [comment]
> > You could also just call `controller?.dispose()`. This method should also stop all image streaming.
> 
> Thanks a lot.
> 
> ```
> if (controller != null) {
>   controller.stopImageStream().then((_) {
>     controller.dispose();
>   });
> }
> ```
> 
> or
> 
> ```
> controller?.dispose()
> ```
> 
> both work fine for me.

Sorry, old question, but I'm a little confused after reading. You say `controller?.dispose()` is working for you.
But you already had `controller?.dispose()` in your question.
What did you change to make it work?

Thanks.
