### ISSUE TITLE
Docs edit for Tab Label Color

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter#29113]
```
  /// The color of selected tab labels.
  ///
  /// Unselected tab labels are rendered with the same color rendered at 70%
  /// opacity unless [unselectedLabelColor] is non-null.
  ///
  /// If this parameter is null then the color of the theme's body2 text color
  /// is used.
  final Color labelColor;
```
should be changed to 

  /// The color of selected tab labels.
  ///
  /// Unselected tab labels are rendered with the same color rendered at 70%
  /// opacity unless [unselectedLabelColor] is non-null.
  ///
  /// If this parameter is null then the color of the **_primaryTextTheme's_** body2 text color
  /// is used.
  final Color labelColor;

**Comment by dnfield** [comment]
That sounds reasonable - would you be able to open a pull request with that change?

**Comment by seendsouza** [comment]
Opening a pull request now

**Comment by ThinkDigitalRepair** [comment]
Thanks @seendsouza
