### ISSUE TITLE
How to parse model data to listview 

### ISSUE THREAD

**Issue by asfos22** [flutter/flutter#29135]

**Comment by asfos22** [comment]
Having challenges parsing this model data to listview , any recommendation ? i have got stuck now .


// To parse this JSON data, do
//
//     final deliveryCategory = deliveryCategoryFromJson(jsonString);

import 'dart:convert';

// The base class for the different types of items the List can contain
abstract class ListItem {}

DeliveryCategory deliveryCategoryFromJson(String str) {
  final jsonData = json.decode(str);
  print("API 2 Asante" + str);
  return DeliveryCategory.fromJson(jsonData);
}

String deliveryCategoryToJson(DeliveryCategory data) {
  final dyn = data.toJson();
  return json.encode(dyn);
}

class DeliveryCategory implements ListItem {
  int code;
  String message;
  Payload payload;

  DeliveryCategory({
    this.code,
    this.message,
    this.payload,
  });

  factory DeliveryCategory.fromJson(Map<String, dynamic> json) =>
      new DeliveryCategory(
        code: json["code"],
        message: json["message"],
        payload: Payload.fromJson(json["payload"]),
      );

  Map<String, dynamic> toJson() => {
        "code": code,
        "message": message,
        "payload": payload.toJson(),
      };
}

class Payload implements ListItem {
  List<Item> items;
  int total;
  int offset;

  Payload({
    this.items,
    this.total,
    this.offset,
  });

  factory Payload.fromJson(Map<String, dynamic> json) => new Payload(
        items: new List<Item>.from(json["items"].map((x) => Item.fromJson(x))),
        total: json["total"],
        offset: json["offset"],
      );

  Map<String, dynamic> toJson() => {
        "items": new List<dynamic>.from(items.map((x) => x.toJson())),
        "total": total,
        "offset": offset,
      };
}

class Item implements ListItem {
  String name;
  Image image;
  BaseFare baseFare;
  List<Pricing> pricing;
  int id;
  String createdAt;
  String updatedAt;

  Item({
    this.name,
    this.image,
    this.baseFare,
    this.pricing,
    this.id,
    this.createdAt,
    this.updatedAt,
  });

  factory Item.fromJson(Map<String, dynamic> json) => new Item(
        name: json["name"],
        image: Image.fromJson(json["image"]),
        baseFare: BaseFare.fromJson(json["base_fare"]),
        pricing: new List<Pricing>.from(
            json["pricing"].map((x) => Pricing.fromJson(x))),
        id: json["id"],
        createdAt: json["created_at"],
        updatedAt: json["updated_at"],
      );

  Map<String, dynamic> toJson() => {
        "name": name,
        "image": image.toJson(),
        "base_fare": baseFare.toJson(),
        "pricing": new List<dynamic>.from(pricing.map((x) => x.toJson())),
        "id": id,
        "created_at": createdAt,
        "updated_at": updatedAt,
      };
}

class BaseFare {
  String amount;
  Currency currency;

  BaseFare({
    this.amount,
    this.currency,
  });

  factory BaseFare.fromJson(Map<String, dynamic> json) => new BaseFare(
        amount: json["amount"],
        currency: Currency.fromJson(json["currency"]),
      );

  Map<String, dynamic> toJson() => {
        "amount": amount,
        "currency": currency.toJson(),
      };
}

class Currency {
  String code;
  String name;
  String symbol;
  String createdAt;

  Currency({
    this.code,
    this.name,
    this.symbol,
    this.createdAt,
  });

  factory Currency.fromJson(Map<String, dynamic> json) => new Currency(
        code: json["code"],
        name: json["name"],
        symbol: json["symbol"],
        createdAt: json["created_at"],
      );

  Map<String, dynamic> toJson() => {
        "code": code,
        "name": name,
        "symbol": symbol,
        "created_at": createdAt,
      };
}

class Image {
  String name;
  String originalName;
  int size;
  String src;
  String mimeType;
  int id;
  String createdAt;

  Image({
    this.name,
    this.originalName,
    this.size,
    this.src,
    this.mimeType,
    this.id,
    this.createdAt,
  });

  factory Image.fromJson(Map<String, dynamic> json) => new Image(
        name: json["name"],
        originalName: json["original_name"],
        size: json["size"],
        src: json["src"],
        mimeType: json["mime_type"],
        id: json["id"],
        createdAt: json["created_at"],
      );

  Map<String, dynamic> toJson() => {
        "name": name,
        "original_name": originalName,
        "size": size,
        "src": src,
        "mime_type": mimeType,
        "id": id,
        "created_at": createdAt,
      };
}

class Pricing {
  String minDistance;
  String maxDistance;
  String rate;
  int id;
  String createdAt;
  String updatedAt;

  Pricing({
    this.minDistance,
    this.maxDistance,
    this.rate,
    this.id,
    this.createdAt,
    this.updatedAt,
  });

  factory Pricing.fromJson(Map<String, dynamic> json) => new Pricing(
        minDistance: json["min_distance"],
        maxDistance: json["max_distance"],
        rate: json["rate"],
        id: json["id"],
        createdAt: json["created_at"],
        updatedAt: json["updated_at"] == null ? null : json["updated_at"],
      );

  Map<String, dynamic> toJson() => {
        "min_distance": minDistance,
        "max_distance": maxDistance,
        "rate": rate,
        "id": id,
        "created_at": createdAt,
        "updated_at": updatedAt == null ? null : updatedAt,
      };
}

l have  got stuck here at parsing payload to listview

**Comment by jonahwilliams** [comment]
Please consider asking support questions on one of the channels in https://flutter.dev/support .
