### ISSUE TITLE
Android SDK Manager path in error message is not properly escaped

### ISSUE THREAD

**Issue by wenz** [flutter/flutter#29133]
The user message when "flutter doctor" does not find the required version of Android SDK (currently: 28) does not put the path to sdkmanager in double quotes. Since a common Android SDK location under Windows is "C:\Program Files (x64)\Android\android-sdk", the resulting command cannot be directly pasted in a command window, due to the missing quotes. Here is a typical output; I added "*****" to denote the line with the missing quotes:

--START--
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version
    10.0.17763.348], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 23.0.1)
    X Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
*****        C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager
        "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed
      instructions.
    X Android license status unknown.
[!] Android Studio (not installed)
[√] VS Code (version 1.32.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
--END--

I am sending a trivial PR right now.

**Comment by stuartmorgan** [comment]
Looks like this was fixed by the PR above.

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/flutter-does-not-find-android-sdk-2
