### ISSUE TITLE
I can't use flutter run properly to start projects

### ISSUE THREAD

**Issue by aikefang** [flutter/flutter#29149]
iOS Mobile phone

flutter doctor
![image](https://user-images.githubusercontent.com/21077842/54110557-a46eab00-441c-11e9-833b-926a7c816883.png)

flutter run
![image](https://user-images.githubusercontent.com/21077842/54110693-0cbd8c80-441d-11e9-9113-82c81c2d1cc1.png)

**Comment by tomalabaster** [comment]
Have you opened up the project in Xcode and running it?

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
