### ISSUE TITLE
Android EditText didn't popup Input Keyboard

### ISSUE THREAD

**Issue by wuxuan2811** [flutter/flutter#29140]
I use Android Native EditText in project through AndroidView widget.But,the Input keyboard didn't popup when the EditText have focus
Next is my Android Code:
public class TestView implements PlatformView, MethodChannel.MethodCallHandler
{
    private final View testView;
    private final MethodChannel methodChannel;

    TestView(Context context, BinaryMessenger messenger, int id)
    {

        methodChannel = new MethodChannel(messenger, "plugins.spaceon/testview_" + id);
        methodChannel.setMethodCallHandler(this);

        testView = LayoutInflater.from(context).inflate(R.layout.test_view, null);
    }

    @Override
    public View getView()
    {
        return testView;
    }
}

Next is my Flutter Code:
class TestView extends StatefulWidget {
  const TestView({
    Key key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return _TestViewState();
  }
}

class _TestViewState extends State<TestView> {

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return AndroidView(
        viewType: 'plugins.spaceon/testview',
      );
    }
    return Text(
        '$defaultTargetPlatform is not yet supported by the chat_view plugin');
  }
}

**Comment by wuxuan2811** [comment]
R.layout.test_view code:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical"
>
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="EditText Text"/>
    <EditText
        android:imeOptions="flagNoFullscreen"
        android:id="@+id/etTextInAct"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:ems="10">
        <requestFocus/>
    </EditText>

</LinearLayout>

**Comment by sp0cket** [comment]
#19718

**Comment by wuxuan2811** [comment]
Wish Flutter team can solve as quickly as possibile. close it due to same with #19718

**Comment by jlcool** [comment]
@wuxuan2811 请问你是否实现了安卓原生文本框的使用？flutter的textfield体验不是很好。

**Comment by keepfocusontechnology** [comment]
@wuxuan2811  I have the same problem ... can u tell me what`s ur solution?
