### ISSUE TITLE
TimeOfDay class should also be in the cupertino package

### ISSUE THREAD

**Issue by DevNico** [flutter/flutter#29147]
I would like to use the TimeOfDay class without having to import the material dart file. The class currently sits in `flutter/lib/src/material/time.dart`. In my opinion it should be moved to a place that is covered by the cupertino file as well. (No idea where that is since I don't really know how the internals work)

Thanks in advance for any feedback as well as wether or not this Issue is written "correctly" haven't written that many issues yet.

**Comment by gazialankus** [comment]
Actually, this should be a Dart SDK class so that we can use it in non-Flutter Dart code.
