### ISSUE TITLE
jenkins package Flutter project  open(/opt/flutter/bin/cache/shlock29694): Permission denied

### ISSUE THREAD

**Issue by codesourse** [flutter/flutter#29148]
1、shell package  flutter
`#bin/bsah - l
export LANG=en_US.UTF-8

export LANGUAGE=en_US.UTF-8

export LC_ALL=en_US.UTF-8

#更新timeout
export FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=120

echo "==========================================="
echo "scriptPath1: "$(cd `dirname $0`; pwd)
echo "scriptPath2: "$(pwd)

echo "==========================================="
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export PATH=/opt/flutter/bin:$PATH
flutter_path=$(pwd)
ls
#
flutter clean
flutter packages get
flutter build ios --release`

error as 
[CRM_iOS] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/jenkins4075036103437921557.sh
+ ls
README.md
android
assets
build.yaml
flutterbuild.sh
ios
lib
pubspec.lock
pubspec.yaml
test
+ security unlock-keychain -p meilici /Users/Shared/Jenkins/Library/Keychains/login.keychain
+ security set-keychain-settings -t 3600 -l /Users/Shared/Jenkins/Library/Keychains/login.keychain
+ sh flutterbuild.sh
===========================================
scriptPath1: /Users/Shared/Jenkins/Home/workspace/CRM_iOS
scriptPath2: /Users/Shared/Jenkins/Home/workspace/CRM_iOS
===========================================
README.md
android
assets
build.yaml
flutterbuild.sh
ios
lib
pubspec.lock
pubspec.yaml
test
shlock: open(/opt/flutter/bin/cache/shlock29694): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29699): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29703): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29706): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29710): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29715): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29719): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29723): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29728): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29732): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29734): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29739): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29742): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29746): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29751): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29754): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29759): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29762): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29767): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29770): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29774): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29778): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29782): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29787): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29790): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29794): Permission denied
shlock: open(/opt/flutter/bin/cache/shlock29798): Permission denied

**Comment by escamoteur** [comment]
Hi, if you still have this problem, please ask on stackoverflow. Thanks

**Comment by doveampli** [comment]
I cant even fix this on my end please the help

**Comment by acegg** [comment]
> I cant even fix this on my end please the help

keywords：Permission denied
So try this：
`sudo chown -R jenkins $(flutter_install_dir)`
