### ISSUE TITLE
when install libimobiledevice, show me:  Library/Logs/Homebrew/libimobiledevice/03.make:

### ISSUE THREAD

**Issue by QinKingHan** [flutter/flutter#29145]
## Steps to Reproduce

1. brew install --HEAD libimobiledevice  

## Logs
error Log

==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libimobiledevice/HEAD-0584aa9_3 --without-cyth
==> make install
Last 15 lines from /Users/zhangxinxin/Library/Logs/Homebrew/libimobiledevice/03.make:
                                         ^
thread.c:52:23: error: use of undeclared identifier 'NULL'
        pthread_join(thread, NULL);
                             ^
thread.c:61:28: error: use of undeclared identifier 'NULL'
        pthread_mutex_init(mutex, NULL);
                                  ^
7 errors generated.
make[1]: *** [thread.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I.. -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -fsigned-char -fvisibility=hidden -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/usbmuxd/HEAD-c75605d_1/include -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/openssl/1.0.2q/include -D_LARGE_FILES=1 -g -O2 -c socket.c -o socket.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I.. -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -fsigned-char -fvisibility=hidden -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/usbmuxd/HEAD-c75605d_1/include -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/openssl/1.0.2q/include -D_LARGE_FILES=1 -g -O2 -c utils.c -o utils.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I.. -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -fsigned-char -fvisibility=hidden -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/usbmuxd/HEAD-c75605d_1/include -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/openssl/1.0.2q/include -D_LARGE_FILES=1 -g -O2 -c debug.c -o debug.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../include -I.. -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter -fsigned-char -fvisibility=hidden -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/usbmuxd/HEAD-c75605d_1/include -I/usr/local/Cellar/libplist/2.0.0_1/include -I/usr/local/Cellar/openssl/1.0.2q/include -D_LARGE_FILES=1 -g -O2 -c userpref.c -o userpref.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

```
```

```
```

**Comment by JCCP3** [comment]
same problem

**Comment by waltcow** [comment]
me too

**Comment by waltcow** [comment]
You'll need to:
1. install Xcode
2. start Xcode and agree to it's license
3. install Xcode command line tools (Start Xcode, Go to Preferences -> Downloads tab)
4. install homebrew by this command (sudo password will be prompted)

```sh
brew install automake autoconf libtool wget libimobiledevice
```

**Comment by christopherfujino** [comment]
The need to install libimobiledevice via homebrew has been removed with https://github.com/flutter/flutter/pull/36093.
