### ISSUE TITLE
Ability to remove the Debug Banner

### ISSUE THREAD

**Issue by msmshazan** [flutter/flutter#29142]
Would it be possible to remove the default debug banner showing up when embedding flutter ? If so how ?
I'm embedding Flutter in windows using SDL2 onto an GLES context using ANGLE
![54089214-98d3a380-438c-11e9-912a-ba4219f2708e](https://user-images.githubusercontent.com/20334207/54101919-20043400-43ec-11e9-98e6-9d829b8c5285.png)

**Comment by ened** [comment]
In your `MaterialApp` call, set the following:

```
MaterialApp(
      debugShowCheckedModeBanner: false,
);
```

Please consider asking support questions in one of the other channels listed at https://flutter.io/support.

**Comment by rakeshlanjewarwork** [comment]
@msmshazan Please close the issue if your issue is resolved

**Comment by mohammad97mha** [comment]
> MaterialApp(
>       debugShowCheckedModeBanner: false,
> );

you mean in the main file or in the any materialapps that we called?

**Comment by mohammad97mha** [comment]
MaterialApp(
      debugShowCheckedModeBanner: false,
);

@ened 
your mean is in main function or in any materialapps that we called?
