### ISSUE TITLE
Line spacing with Display 3, Subheader, Body 2 in Flutter seems different than on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2915]
![screen shot 2016-03-25 at 2 00 13 pm](https://cloud.githubusercontent.com/assets/5479/14053904/ecab3b98-f291-11e5-8aa9-f329ca638777.png)

Left if Flutter, Right is Android. Notice that on Android, Display 3 has more line spacing than on Flutter.

As far as I can tell, I didn't explicitly set or change any line spacing in either the Flutter or the Android code. Both of these were created by starting with the default starter templates from Flutter and Android Studio.

On Flutter:

```
class _FlutterDemoState extends State<FlutterDemo> {
  @override
  Widget build(BuildContext context) {
    final TextTheme textTheme = Theme.of(context).textTheme;
    final styleItems = [
      new Text('Display 3', style: textTheme.display3),
      new Text('Display 2', style: textTheme.display2),
      new Text('Display 1', style: textTheme.display1),
      new Text('Headline', style: textTheme.headline),
      new Text('Title', style: textTheme.title),
      new Text('Subheading', style: textTheme.subhead),
      new Text('Body 2', style: textTheme.body2),
      new Text('Body 1', style: textTheme.body1),
      new Text('Caption', style: textTheme.caption),
      new Text('BUTTON', style: textTheme.button),
    ];
    return new Scaffold(
        appBar: new AppBar(title: new Text('My Application')),
        body: new Padding(
            padding:
                const EdgeInsets.symmetric(horizontal: 8.0, vertical: 16.0),
            child: new Block(children: styleItems)));
  }
```

From Android:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.example.sethladd.myapplication.MainActivity"
    tools:showIn="@layout/activity_main">

    <TextView
        android:id="@+id/display3"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        style="@style/Base.TextAppearance.AppCompat.Display3"
        android:text="Display 3" />
```

**Comment by abarth** [comment]
I think what's happening here is that the height of a single-line Text widget doesn't include the line spacing that would be applied if it were multiple lines.  I'm not sure that it's important to match Android's behavior here.  You won't be able to use identical layouts on Android and Flutter anyway, so I'm not sure how important it is to make Android's RelativeLayout match our Column layout.

**Comment by sethladd** [comment]
I'm trying to confirm if this is an artifact of the layout engine, or an artifact of the Display3 style. If it's the layout engine, then I'm also not worried about it. But, there are different line spaces, depending on the style, so not sure what is governing that.

**Comment by sethladd** [comment]
I tried LinearLayout, orientation vertical, and looks like I see the same line spacing:

![android](https://cloud.githubusercontent.com/assets/5479/14054300/720aaab4-f295-11e5-99be-a02deb35d9e4.png)

Will continue to dig.

**Comment by abarth** [comment]
I think this issue is WONTFIX.  The goal isn't to mirror the OEM layout primitives but instead create the proper material design effects.  If this issue results in incorrect rendering of material design elements, we should fix it at that level instead of trying to make Column match LinearLayout.

**Comment by sethladd** [comment]
There's no Column in our code. I am curious why our line heights are so different (is that an effect of our layout code, or from the default configurations of our text styles from material?)

**Comment by abarth** [comment]
Sorry, `Block` rather than `Column`.

**Comment by sethladd** [comment]
There are some definitions of line heights here: https://www.google.com/design/spec/style/typography.html#typography-line-height

**Comment by sethladd** [comment]
Here's a side-by-side:

![screen shot 2016-03-28 at 9 29 40 am](https://cloud.githubusercontent.com/assets/5479/14154125/c61b0d32-f66f-11e5-82d2-339db2b0f3c2.png)

**Comment by Hixie** [comment]
I've no idea where android is getting its line heights. It might just have different defaults; maybe it doesn't look at the font data?

This defines display3 in android:
<https://android.googlesource.com/platform/frameworks/base/+/marshmallow-release/core/res/res/values/styles_material.xml>

These are the attributes you'd need to set to get a non-default line height:
<http://developer.android.com/reference/android/widget/TextView.html#attr_android:lineSpacingExtra>
<http://developer.android.com/reference/android/widget/TextView.html#attr_android:lineSpacingMultiplier>
It doesn't appear either is set anywhere. The defaults appear to be 0.0f and 1.0f respectively which doesn't track with what we're seeing.

**Comment by Hixie** [comment]
I don't know how to make progress on this bug at this time. I tend to agree with @abarth's conclusion that this is WONTFIX unless we get additional information.

**Comment by sethladd** [comment]
Closing as WONTFIX until we get more guidance here.
