### ISSUE TITLE
flutter plugin xcode build

### ISSUE THREAD

**Issue by nobewp** [flutter/flutter#29153]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Jensen615** [comment]
I have the same exact problem!! Have you solved it yet? Can anyone help PLEASE!

**Comment by nobewp** [comment]
reinstall the flutter sdk

**Comment by Jensen615** [comment]
yup, I did that already and it worked. thanks!
