### ISSUE TITLE
How does the flutter determine a TV device？

### ISSUE THREAD

**Issue by 2015-lizaiyang** [flutter/flutter#29155]
**How does the flutter determine a TV device？**

**Comment by escamoteur** [comment]
Could you explain what you mean by this pleas?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by malviyaritesh** [comment]
Get device current UI mode and match if its a TV.
https://github.com/malviyaritesh/device_ui_mode
