### ISSUE TITLE
[Cupertino] Disabled Switches do not change opacity

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#29164]
On iOS, the switches reduce capacity when they are disabled. Currently, the Cupertino switches do not change appearance when disabled.

### Disabled Switches

||Off|On|
|--|--|--|
|Flutter (Cupertino)|<img width="103" alt="Screen Shot 2019-03-11 at 1 32 54 PM" src="https://user-images.githubusercontent.com/4229329/54144886-1508ce00-4403-11e9-97a6-a1c134c1b9b4.png">|<img width="96" alt="Screen Shot 2019-03-11 at 1 32 44 PM" src="https://user-images.githubusercontent.com/4229329/54144846-f9052c80-4402-11e9-95c4-93dd98a12c3a.png">|
||||
|Native iOS|![Screen Shot 2019-03-11 at 1 29 34 PM](https://user-images.githubusercontent.com/4229329/54144941-3964aa80-4403-11e9-906c-d1f49d2b07a2.png)|![Screen Shot 2019-03-11 at 1 30 01 PM](https://user-images.githubusercontent.com/4229329/54144952-41244f00-4403-11e9-9028-5c6c1b60be7e.png)|

**Comment by xster** [comment]
🤦🏻‍♀️

Thanks for catching

**Comment by Robiquet** [comment]
I would like to start contributing to Flutter and I think this issue would be a good one to start with. I have already submitted a pull request to wrap the widget in an opacity widget though it seems tests have failed and the bot doesn't seem able to pick up my CLA. Would anyone be able to check the code in the PR and let me know if it is the right approach?

**Comment by xster** [comment]
Your approach in the PR is ok. Though it would need new tests in https://github.com/flutter/flutter/blob/master/packages/flutter/test/cupertino/switch_test.dart to make sure we don't regress on this added behavior. 

See something like https://github.com/flutter/flutter/blob/275769b89d2aad157e9097d1271d917a98582072/packages/flutter/test/material/bottom_navigation_bar_test.dart#L1207 for asserting against opacity.

**Comment by johnsonmh** [comment]
Closing because this was fixed in https://github.com/flutter/flutter/pull/29451,  thanks for the fix @Robiquet !
