### ISSUE TITLE
Investigate frontend_server driven dependency analysis for hot reload

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29173]
Once we've removed the analyzer driven dependency analysis, we should investigate having the frontend server provide the sources used in the hot reload. This could allow us to further subset the files that we check on each hot reload. To do so we should establish:

  - Does adding this capability regress any hot reload performance?
  - Can this be used with multiroot schemes such as codegen or inside of google3?

**Comment by aam** [comment]
dup of #12745
