### ISSUE TITLE
technical_debt__cost/dependencies_count regression

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#29176]
https://github.com/flutter/flutter/commit/ec93468a14ecd6039e4c40bed31131e3e4967bf1 Increased the dependency count by 3 and made the benchmark red.

https://github.com/flutter/flutter/commit/20e0f13cc97ed55ad0db93c7195f78dd889992f5 increased the dependency count further

/cc @jonahwilliams @dnfield

**Comment by jonahwilliams** [comment]
build_runner dependencies are expected and required for web compilation and for build_runner driven flutter test. 

infra changes that dan landed are really critical for code health, and we'll be worse off without them.

I'm going to re-baseline the benchmark

**Comment by jonahwilliams** [comment]
benchmarks updated

**Comment by dnfield** [comment]
New dependencies from mine are for googleapis.
