### ISSUE TITLE
Subclassing FlutterActivity

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#29170]
I'm looking at https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Activity#subclassing-flutteractivity and it says file an issue if you need to subclass flutter activity.

I apologize if it's my error, but isn't a subclassed flutteractivity a reasonable place to put platform calls?   
Is a custom plugin better for stability's sake?

1) How do I find the part of the surface area likely to be most stable, and 2) What are good places to put platform calls that need to be add2app but don't need to be  published as a plugin

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
