### ISSUE TITLE
Determine usefulness of explicit frame schedule in hot reload

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29182]
The following lines of run_hot code don't appear to serve any purpose, the act of reassembling already schedules a frame. It's possible this is vestigial, or checks for an error condition that we don't have coverage for. 

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L830-L833

**Comment by aam** [comment]
I believe https://github.com/flutter/flutter/commit/24ab8372402dfb74b30075612e7b1738be92b321 where it originated from assumed that  reassemble doesn't necessary schedule a frame. Do we know if that is not the case anymore?

**Comment by jonahwilliams** [comment]
It looks like this was added specifically to facilitate usage of hot reload without using the framework. However the corresponding `frameworkPresent` service extension has since been removed.

For flutter, we always schedule a frame, so the extra frame schedule is not necessary.

https://github.com/flutter/flutter/blob/262f12b4a9269a77bce499926afa681b20790d6c/packages/flutter/lib/src/rendering/binding.dart#L344-L353
