### ISSUE TITLE
API docs: mention that TextStyle's height is the same as ui.TextStyle's lineHeight?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2918]
I saw that rendering's TextStyle has a height, and I was curious if that was the same thing as "lineHeight". I also saw that ui's TextStyle has a lineHeight. And then I saw that rendering.TextStyle's getter for textStyle returns a ui.TextStyle and sets the lineHeight to height.

I went through this process because I searched for "line height" on flutter.io to learn how Flutter does line height.

Could we say something like "Also known as _line height_." in rendering.TextStyle's dartdoc comments?

(if that is indeed accurate...)

**Comment by sethladd** [comment]
cc @Hixie thoughts?

**Comment by Hixie** [comment]
Certainly. The more information the better.

**Comment by abarth** [comment]
https://github.com/flutter/engine/pull/2563

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/3000
