### ISSUE TITLE
How to get deviceInfo in flutter test dart?

### ISSUE THREAD

**Issue by AshokGanta** [flutter/flutter#29199]
Hi Team,

I am trying to run functional automation in multiple devices(iPhones X, iPhones XR, etc...) for my application using flutter driver and I am trying to get the deviceInfo in my test class or test main() using DeviceInfoPlugin() package, But it's giving me below error:

flutter/lib/src/se
_rvices/font_loader.dart:7:8: Error: Not found: 'dart:ui'
[   +2 ms] import 'dart:ui';_

I think DeviceInfoPlugin will work only in UI dart file not in test dart file. So, is there any way to get device info in test dart file?

Thanks & Regards,
Ashok Ganta.

**Comment by escamoteur** [comment]
Hi, just want to catch up if you were able to solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
