### ISSUE TITLE
[New Feature] Microphone Streams?

### ISSUE THREAD

**Issue by rishab2113** [flutter/flutter#29197]
It doesn't look like there's any support for microphone streams as yet, is there any work on this as yet/any future plans?

**Comment by rishab2113** [comment]
I've in the process of writing a package, some help/review would be great! [Link](https://github.com/rishab2113/cloud_speech)

**Comment by yassinecc** [comment]
@rishab2113 I saw that https://github.com/anarchuser/mic_stream has an Android implementation, maybe you could coordinate with @anarchuser to publish a package that supports both iOS and Android?

**Comment by anarchuser** [comment]
Thanks @yassinecc for mentioning this, I originally planned on doing iOS support.
But due to the need of XCode I dropped the idea (since I couldn't test the code).

If I can be of help creating an android backend let me know, though.
