### ISSUE TITLE
Navigation View

### ISSUE THREAD

**Issue by azhagarsparks** [flutter/flutter#29204]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

D/        (25621): HostConnection::get() New Host Connection established 0xa9317480, tid 25640
D/EGL_emulation(25621): eglMakeCurrent: 0xa6931040: ver 2 0 (tinfo 0xa9303200)
I/flutter (25621): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (25621): The following assertion was thrown while handling a gesture:
I/flutter (25621): Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
I/flutter (25621): 'package:flutter/src/widgets/routes.dart': Failed assertion: line 217 pos 12:
I/flutter (25621): '!_transitionCompleter.isCompleted'
I/flutter (25621): 
I/flutter (25621): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25621): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25621): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25621):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (25621): 
I/flutter (25621): When the exception was thrown, this was the stack:
I/flutter (25621): #2      TransitionRoute.didPopNext (package:flutter/src/widgets/routes.dart:217:12)
I/flutter (25621): #3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1944:23)
I/flutter (25621): #4      Navigator.pop (package:flutter/src/widgets/navigator.dart:1271:34)
I/flutter (25621): #5      ChatSingleRoute.build.<anonymous closure> (package:chat_bottom/InsideView/chatsingleview.dart:22:23)
I/flutter (25621): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
I/flutter (25621): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
I/flutter (25621): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
I/flutter (25621): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (25621): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (25621): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
I/flutter (25621): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (25621): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (25621): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
I/flutter (25621): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
I/flutter (25621): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
I/flutter (25621): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (25621): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (25621): #22     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter (25621): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
I/flutter (25621): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (25621): 
I/flutter (25621): Handler: onTap
I/flutter (25621): Recognizer:
I/flutter (25621):   TapGestureRecognizer#81044(debugOwner: GestureDetector, state: accepted, won arena, finalPosition:
I/flutter (25621):   Offset(187.0, 346.0), sent tap down)
I/flutter (25621): ════

```
```

**Comment by TahaTesser** [comment]
Hi @azhagarsparks 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you
