### ISSUE TITLE
webview_flutter 0.3.4 Get body contents

### ISSUE THREAD

**Issue by calvinmuller** [flutter/flutter#29206]
Ability to get body contents for 3D secure implementation. 

I’m assuming this is not possible as i’ve tried all advenues, could you confirm so I can try a different plugin? 

There is no means to access the body in here, given it's just the request:
```
navigationDelegate: (NavigationRequest request) {
              print(request.toString());
              if (request.url.contains("payments/webhook")) {
                Navigator.pop(context);
              }
              return NavigationDecision.navigate;
            },
```

The `webViewController` also does not seem to have this functionality
webview_flutter 0.3.4

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
