### ISSUE TITLE
The FluterView must be created from Activity in Android ?

### ISSUE THREAD

**Issue by LNeway** [flutter/flutter#29208]
Activity activity = (Activity)this.getContext();
        if (nativeView == null) {
            this.mNativeView = new FlutterNativeView(activity.getApplicationContext());
        } else {
            this.mNativeView = nativeView;
        }
        this.mNativeView.attachViewAndActivity(this, activity);

the code copied from FlutterView. 

it is seems that the view must work with Activity.  

And now I  want to add a flutter view in the  input method , is there any way to make it ?

**Comment by matthew-carroll** [comment]
`FlutterView` does require an `Activity`.  #18115 will remove that requirement in a new version of `FlutterView`.

Can you describe what you mean by "I want to add a flutter view in the input method"?

**Comment by LNeway** [comment]
Thanks for your reply.  “I want to add a flutter view in the input method” means that I want add the FlutterView in the android keyboard view. May I cloud make it in the new version of FlutterView
