### ISSUE TITLE
Apk installation on phone only works the first time

### ISSUE THREAD

**Issue by miguellamas28** [flutter/flutter#29213]
Hello, i built an application with flutter and everything works with "flutter run" and shows no errors. But when i install the apk in release mode it works the first time but when i install any update it shows an "app not installed" window. 

To install any update i must uninstall the old version manually, also if i try to install the same version after removing the existing installation it shows the same error. 

Have anyone stepped in this same error before?

[√] Flutter (Channel unknown, v1.2.0, on Microsoft Windows [VersiÃ³n 10.0.17763.348], locale es-ES)
    • Flutter version 1.2.0 at C:\Users\Miguel\flutter
    • Framework revision 06b979c4d5 (7 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Miguel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\Miguel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\182.5314842\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Users\Miguel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\182.5314842
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Redmi 4X • ba59ec6b7d74 • android-arm64 • Android 7.1.2 (API 25)

**Comment by miguellamas28** [comment]
Hello, I forgot to write this but found a solution. Disabling "Play Protect" on the app store fix this issue for me.

**Comment by santiagohdzb** [comment]
@miguellamas28 not really a solution here tho. Think about enterprise apps, that "solution" does not work

**Comment by lunwhl** [comment]
hi @miguellamas28 have you found a solution to install the app without disable the play protect?

**Comment by miguellamas28** [comment]
Looks like a problem with the apk signature, didn't have the same problem since then but it was weird since I was using the same key.
