### ISSUE TITLE
Listview/Gridview does not recycle item when put inside SingleChildScrollView

### ISSUE THREAD

**Issue by DavidSonNguyen** [flutter/flutter#29214]
It crashes when i load to page 60 (page size: 20). But when i use just Listview or Gridview i can load infinite.
```
SingleChildScrollView(
              controller: _scrollController,
              physics: ClampingScrollPhysics(),
              child: Column(
                children: <Widget>[
                  Container(...),
                  Container(...),
                  Container(
                    margin: EdgeInsets.all(5.0),
                    child: FutureBuilder<...>(
                      future: ...,
                      builder: (context, snapshot) {
                       ...
                        return GridView.builder(
                          cacheExtent: 0.0,
                          itemCount: length,
                          shrinkWrap: true,
                          physics: ClampingScrollPhysics(),
                          gridDelegate:
                          new SliverGridDelegateWithFixedCrossAxisCount(
                            mainAxisSpacing: 5.0,
                            crossAxisSpacing: 5.0,
                            crossAxisCount: 2,
                          ),
                          itemBuilder: (context, index) {
                            return ...,
                        );
                      },
                    ),
                  ),
                ],
              ),
            )
```

**Comment by DavidSonNguyen** [comment]
I tried with Listview inside Listview, but it does not work

**Comment by HansMuller** [comment]
If you can provide a small self-contained app that demonstrates the problem you've run into we'll be happy to look into it.

**Comment by DavidSonNguyen** [comment]
The ScrollView is slower and slower when i load more, and it will lag, and crash when the limit is reached (code likes above). But if i use only Gridview (not inside ScrollView), it has no limit
```
GridView.builder(
                          cacheExtent: 0.0,
                          itemCount: length,
                          shrinkWrap: true,
                          physics: ClampingScrollPhysics(),
                          gridDelegate:
                          new SliverGridDelegateWithFixedCrossAxisCount(
                            mainAxisSpacing: 5.0,
                            crossAxisSpacing: 5.0,
                            crossAxisCount: 2,
                          ),
                          itemBuilder: (context, index) {
                            return ...,
                        )
```
Sorry, this is a project of my company, i can only show you a part of my code

**Comment by Kartik1607** [comment]
I think (may be wrong) that the issue is that *SingleChildScrollView* does not perform recycling widget, while ListView and GridView (something like *RecyclerView* in android).

**Comment by nickdbush** [comment]
I'm running into a similar issue when using a non-primary gridview in a scrolling listview (getting some serious jank with only twelve elements on a Pixel 2 XL). Wil look at putting something together.

**Comment by davidmartos96** [comment]
Related?

https://github.com/flutter/flutter/issues/26072

https://stackoverflow.com/questions/54034978/can-flutter-efficiently-layout-nested-lists

**Comment by nickdbush** [comment]
Think so, as removing ```itemCount``` means that nothing is rendered in the app (presumably as it is trying to render an infinite amount of elements). Cheers.

**Comment by DavidSonNguyen** [comment]
I think i found problem is we cannot put listview/gridview inside singlechildscrollview, let use CustomScroll instead of

**Comment by pawangjain** [comment]
You may try the solution given at-

https://github.com/flutter/flutter/issues/26072#issuecomment-652156339
