### ISSUE TITLE
TabBarView blink reloads previous tab during animation when switching from 1st tab to 3rd for example.

### ISSUE THREAD

**Issue by ziggycrane** [flutter/flutter#29225]
As you can see in this gif - https://giphy.com/gifs/7XmgfbnHDdYlQSFXki

When switching from first to third tab, previous tab blinks and gets rebuilt during animation which results in very unpleasant look. 

The line that is causing this issue is here - https://github.com/flutter/flutter/blob/dev/packages/flutter/lib/src/material/tabs.dart#L1183

If current/previous tab difference is more than 1, then flutter takes tab from an array index 3, and puts it in index 2 so animation looks like it would go from 3 -> 1 instead of 3 -> 2 -> 1. I can understand the reasoning for this code, but the way it is implemented right now causes the tab widget to rebuild/blink during the animation. 

I have added AutomaticKeepAliveClientMixin for every tab widget, but it still does not work in this situation, it only works if I got back to that tab, then the state is saved. 

I don't have any other suggestion for solution here other than letting this line (https://github.com/flutter/flutter/blob/dev/packages/flutter/lib/src/material/tabs.dart#L1175) execute in every stituation, because then there are no blinking since no widgets are bing reordered in the array and getting rebuilt. This solution would work for me and looks smooth.

Can I do anything else besides AutomaticKeepAliveClientMixin to prevent initState() being called on tab widgets in this situation when tab is being reordered in the array?

Edited:
The problematic line looks like to be this - https://github.com/flutter/flutter/blob/dev/packages/flutter/lib/src/material/tabs.dart#L1181

It makes a copy of widget list, and in this case there are no state for new widgets and they show up as new during animation.

**Comment by orischwartz** [comment]
Here's a minimal runnable reproduction of the problem described above, and why it is an issue for tabs that load their contents (e.g., using `FutureBuilder`).

This `MaterialApp` creates 7 tabs whose body is a `StatefulWidget` that uses a `FutureBuilder` and an `async` method to simulate a remote operation. When the async method executes it prints `LOADING contents of tab $index`.

![image](https://user-images.githubusercontent.com/16327036/55490797-5ce5d400-5602-11e9-9686-a6acfeb6e831.png)

### Expected Behavior
The app should print `LOADING contents of tab $index` exactly once every time a tab's body is shown.

### Actual Behavior
Works as expected *only* when navigating from first tab to second tab. When skipping e.g., from first tab at index `0` to third tab at index `2`, the output is as follows:

```
I/flutter ( 5693): LOADING contents of tab #0
I/flutter ( 5693): LOADING contents of tab #2
```

There's an extra call to the async method for the source tab at index `0`.

The behavior is even worse when jumping from the first tab at index `0` to the fifth at index `6`:

```
I/flutter ( 5693): LOADING contents of tab #0
I/flutter ( 5693): LOADING contents of tab #5
I/flutter ( 5693): LOADING contents of tab #6
```

```dart
import 'package:flutter/material.dart';

class TabBody extends StatefulWidget {
  final int index;

  TabBody(this.index);

  @override
  State<StatefulWidget> createState() {
    return TabBodyState();
  }
}

class TabBodyState extends State<TabBody> {
  Future<String> _future;

  @override
  initState() {
    super.initState();
    _future = remoteOperation(widget.index);
  }

  static Future<String> remoteOperation(int index) async {
    print("LOADING contents of tab #$index");
    return "Contents of tab #$index!";
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<String>(future: _future, builder: buildSnapshot);
  }

  Widget buildSnapshot(BuildContext context, AsyncSnapshot<String> snapshot) {
    if (snapshot.hasData) {
      return Text(snapshot.data);
    }

    if (snapshot.hasError) {
      return Text("will never happen, Future.value can't have an error");
    }

    return CircularProgressIndicator();
  }
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Map<Tab, Widget> tabs = Map.fromIterable(
        List.generate(7, (i) => TabBody(i)),
        key: (tabBody) => Tab(text: "Tab #${tabBody.index}"));

    return MaterialApp(
        home: DefaultTabController(
            length: tabs.length,
            child: Scaffold(
                appBar: AppBar(
                  title: Text("Tabs Test"),
                  bottom: TabBar(tabs: tabs.keys.toList(), isScrollable: true),
                ),
                body: TabBarView(children: tabs.values.toList()))));
  }
}

void main() {
  runApp(App());
}
```

```bash
$ flutter doctor -v
[v] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.2.1 at ...
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[v] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[v] Android Studio (version 3.2)
    • Android Studio at ...
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[v] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by xb284524239** [comment]
Have you solved this problem?

**Comment by xb284524239** [comment]
I found a way to solve this problem. Here's my code below, you can try it:

https://github.com/flutter/flutter/issues/14316#issuecomment-504354349

**Comment by TahaTesser** [comment]
hI @ziggycrane 
[Solution](https://github.com/flutter/flutter/issues/14316#issuecomment-504354349)  from above comment seems to solve this issue of rebuilding tab.

f you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
