### ISSUE TITLE
barcode_scan xcode build fails because of GULAppDelegateSwizzler

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#29227]
When I run `flutter build ios` sometimes I get this error,
It's very random, sometimes I get it, sometimes I don't.

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET MTBBarcodeScanner OF PROJECT Pods WITH CONFIGURATION Release ===
    In file included from
    {app_path}/app/mobile/ios/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m:24:
    {app_path}/app/mobile/ios/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h:26:1: error:
    duplicate interface definition for class 'GULAppDelegateSwizzler'
    @interface GULAppDelegateSwizzler : NSProxy
    ^
    In file included from
    {app_path}/app/mobile/ios/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m:23:
    In file included from
    {app_path}/app/mobile/ios/Pods/GoogleUtilities/GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h:17:
    {app_path}/app/mobile/build/ios/Release-iphoneos/GoogleUtilities/GoogleUtilities.framework/PrivateHeaders/GULAppDelegateSwizzler.h:2
    6:12: note: previous definition is here
    @interface GULAppDelegateSwizzler : NSProxy
               ^
    1 error generated.
```

`flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.2.1 at /Users/tudor/dev/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5199772/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5199772/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Tudor’s iPhone 7 • 6c6f39c58d86256962f6a336f8ebef46f202225e • ios • iOS 12.1.4

• No issues found!
```

**Comment by AddzMDev** [comment]
I've run
```
flutter clean
```
once and the problem gone.

**Comment by Addzero** [comment]
I've face this issue before then
1. ```flutter clean``` and then run ```flutter build ios``` if not solved then try.
2. ```rm -rf build/ios``` and ```cd ios && pod repo update``` and then run ```flutter build ios``` if not solved then try.
3. open Xcode and in File>Workspace Settings under <b>Build System select New Build System(Default)</b> but (some say select <b>Legacy Build System </b>instead but for me New Build System work fine) and then run ```flutter build ios```

Hope this help.

**Comment by woshitom** [comment]
> I've face this issue before then
> 
> 1. `flutter clean` and then run `flutter build ios` if not solved then try.
> 2. `rm -rf build/ios` and `cd ios && pod repo update` and then run `flutter build ios` if not solved then try.
> 3. open Xcode and in File>Workspace Settings under Build System select New Build System(Default) but (some say select Legacy Build System instead but for me New Build System work fine) and then run `flutter build ios`
> 
> Hope this help.

Second worked for me, many thanks!

**Comment by jmagman** [comment]
> 3. open Xcode and in File>Workspace Settings under Build System select New Build System(Default) but (some say select Legacy Build System instead but for me New Build System work fine) and then run `flutter build ios`

This is no longer recommended.  See https://github.com/flutter/flutter/issues/42437#issuecomment-542323456.

**Comment by jmagman** [comment]
Not sure what's going on here.
@tudor07  can we get your `pubspec.yaml`, `pubspec.lock`, `ios/Podfile`, and `ios/Podfile.lock`?

**Comment by tudor07** [comment]
I haven't seen this issue in a while (it was opened almost 2 years ago), I will close issue for now, if it happens again I will re-open.
