### ISSUE TITLE
How to assemble arm64-v8a architecture for android

### ISSUE THREAD

**Issue by Zo2m4bie** [flutter/flutter#29224]
Hello. I did some flutter app and when I build my release android app, I see that there's only armeabi-v7a architecture. As I understand from [9253](https://github.com/flutter/flutter/issues/9253) x86 is not supported now. However according to[ this link](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) all apps should have support of 64-bit in the app. 
According to [Ensure that your app supports 64-bit devices](https://developer.android.com/distribute/best-practices/develop/64-bit) with armeabi-v7a we should have arm64-v8a as well. How can I assemble arm64-v8a architecture to meet this requirement?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
