### ISSUE TITLE
Single source of `analysis_options.yaml`

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#29228]
In https://github.com/flutter/flutter/blob/master/analysis_options.yaml, it says "There are other similar analysis options files in the flutter repos, which should be kept in sync with this file:", but In https://github.com/flutter/flutter/blob/master/analysis_options.yaml is last updated 6 days ago, while for example https://github.com/flutter/plugins/blob/master/analysis_options.yaml is last updated Oct 19, 2018 .

What we should do is create a new repo, say `https://github.com/flutter/analysis_options`, similar to https://github.com/dart-lang/pedantic, and use `include: package:pedantic/analysis_options.yaml` instead. Having done this, other Flutter app developers and plugin developers can also use `include: package:pedantic/analysis_options.yaml` , or better yet, it is generated by `flutter tool`

I ran into a run-time problem with https://www.dartlang.org/guides/language/sound-problems#invalid-casts while I expected Dart to catch it at compile-time.

**Comment by jonahwilliams** [comment]
Removing from tool designation as this is not a flutter_tool issue

**Comment by darshankawar** [comment]
Added `will need additional triage` label as I am not sure which team this issue belongs to.

**Comment by Hixie** [comment]
There are some tricky practical problems to having a single source of truth here unfortunately. I think the upshot is that this is WONTFIX. That said, it would be nice to have a regular process whereby we try to get these more aligned.
