### ISSUE TITLE
Getting error message while using multiple scrolling widgets inside nested scroll view

### ISSUE THREAD

**Issue by adar2378** [flutter/flutter#29221]
I'm using nested scroll view and inside that I also have one image carousel and a gridview! whenever I scroll down to the point where my carousel begins, I am getting the following error in the terminal

     [   +6 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +4 ms] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:4017/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+5237 ms] I/flutter (18497): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +13 ms] I/flutter (18497): The following assertion was thrown building IconTheme(IconThemeData#4acc4(color: Color(0xffffffff),
[        ] I/flutter (18497): opacity: 0.0)):
[        ] I/flutter (18497): Failed assertion: boolean expression must not be null
[  +13 ms] I/flutter (18497): 
[        ] I/flutter (18497): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (18497): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (18497): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter (18497):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (18497): 
[        ] I/flutter (18497): When the exception was thrown, this was the stack:
[  +28 ms] I/flutter (18497): #0      _RenderCustomClip.clipper= (package:flutter/src/rendering/proxy_box.dart:1171:20)
[   +1 ms] I/flutter (18497): #1      ClipRRect.updateRenderObject (package:flutter/src/widgets/basic.dart:654:9)
[   +3 ms] I/flutter (18497): #2      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4515:12)
[   +1 ms] I/flutter (18497): #3      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4886:11)
[        ] I/flutter (18497): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #5      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4606:32)
[   +6 ms] I/flutter (18497): #6      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4997:17)
[        ] I/flutter (18497): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +1 ms] I/flutter (18497): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[        ] I/flutter (18497): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +8 ms] I/flutter (18497): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +1 ms] I/flutter (18497): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[   +1 ms] I/flutter (18497): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:3801:5)
[   +1 ms] I/flutter (18497): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +2 ms] I/flutter (18497): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +4 ms] I/flutter (18497): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[  +13 ms] I/flutter (18497): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[        ] I/flutter (18497): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #20     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4606:32)
[   +3 ms] I/flutter (18497): #21     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4997:17)
[        ] I/flutter (18497): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +2 ms] I/flutter (18497): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[        ] I/flutter (18497): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:3801:5)
[        ] I/flutter (18497): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +3 ms] I/flutter (18497): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[   +1 ms] I/flutter (18497): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[        ] I/flutter (18497): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #33     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[        ] I/flutter (18497): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +5 ms] I/flutter (18497): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +7 ms] I/flutter (18497): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[  +29 ms] I/flutter (18497): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3801:5)
[        ] I/flutter (18497): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[   +6 ms] I/flutter (18497): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[        ] I/flutter (18497): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +1 ms] I/flutter (18497): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #45     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[   +2 ms] I/flutter (18497): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[   +5 ms] I/flutter (18497): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +2 ms] I/flutter (18497): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +1 ms] I/flutter (18497): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[   +1 ms] I/flutter (18497): #51     StatelessElement.update (package:flutter/src/widgets/framework.dart:3801:5)
[        ] I/flutter (18497): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[   +3 ms] I/flutter (18497): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[  +10 ms] I/flutter (18497): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[        ] I/flutter (18497): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +2 ms] I/flutter (18497): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[   +1 ms] I/flutter (18497): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +3 ms] I/flutter (18497): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[   +7 ms] I/flutter (18497): #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3899:5)
[        ] I/flutter (18497): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #65     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[   +1 ms] I/flutter (18497): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[  +14 ms] I/flutter (18497): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[        ] I/flutter (18497): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #69     StatelessElement.update (package:flutter/src/widgets/framework.dart:3801:5)
[        ] I/flutter (18497): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[        ] I/flutter (18497): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[        ] I/flutter (18497): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3899:5)
[        ] I/flutter (18497): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +1 ms] I/flutter (18497): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[  +11 ms] I/flutter (18497): #79     StatefulElement.update (package:flutter/src/widgets/framework.dart:3899:5)
[   +1 ms] I/flutter (18497): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #81     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[        ] I/flutter (18497): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #83     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4888:14)
[        ] I/flutter (18497): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[   +1 ms] I/flutter (18497): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[   +2 ms] I/flutter (18497): #87     StatefulElement.update (package:flutter/src/widgets/framework.dart:3899:5)
[  +36 ms] I/flutter (18497): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[   +1 ms] I/flutter (18497): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[        ] I/flutter (18497): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #91     ProxyElement.update (package:flutter/src/widgets/framework.dart:4011:5)
[        ] I/flutter (18497): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
[        ] I/flutter (18497): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
[        ] I/flutter (18497): #95     StatefulElement.update (package:flutter/src/widgets/framework.dart:3899:5)
[        ] I/flutter (18497): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
[        ] I/flutter (18497): #97     _SliverPersistentHeaderElement._build.<anonymous closure> (package:flutter/src/widgets/sliver_persistent_header.dart:199:15)
[        ] I/flutter (18497): #98     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2257:19)
[   +2 ms] I/flutter (18497): #99     _SliverPersistentHeaderElement._build (package:flutter/src/widgets/sliver_persistent_header.dart:198:11)
[        ] I/flutter (18497): #100
__RenderSliverFloatingPersistentHeaderForWidgets&_RenderSliverFloatingPersistentHeader&_RenderSliverPersistentHeaderForWidgetsMixin.updateChild
(package:flutter/src/widgets/sliver_persistent_header.dart:266:14)
[   +3 ms] I/flutter (18497): #101    RenderSliverPersistentHeader.layoutChild.<anonymous closure> (package:flutter/src/rendering/sliver_persistent_header.dart:126:9)
[        ] I/flutter (18497): #102    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1728:58)
[   +1 ms] I/flutter (18497): #103    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
[        ] I/flutter (18497): #104    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1728:13)
[        ] I/flutter (18497): #105    RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:124:7)
[        ] I/flutter (18497): #106    RenderSliverFloatingPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:482:5)
[        ] I/flutter (18497): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[   +2 ms] I/flutter (18497): #108    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
[   +1 ms] I/flutter (18497): #109    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
[        ] I/flutter (18497): #110    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
[        ] I/flutter (18497): #111    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
[        ] I/flutter (18497): #112    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
[        ] I/flutter (18497): #113
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:336:19)
[   +6 ms] I/flutter (18497): #114
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:701:13)
[   +4 ms] I/flutter (18497): #115
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:275:5)
[   +3 ms] I/flutter (18497): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1008:15)
[   +2 ms] I/flutter (18497): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:948:9)
[   +1 ms] I/flutter (18497): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:860:5)
[   +1 ms] I/flutter (18497): #122    _invoke (dart:ui/hooks.dart:216:10)
[   +5 ms] I/flutter (18497): #123    _drawFrame (dart:ui/hooks.dart:175:3)
[   +1 ms] I/flutter (18497): (elided 3 frames from package dart:async)
[   +2 ms] I/flutter (18497): ════════════════════════════════════════════════════════════════════════════════════════════════════

[√] Flutter (Channel dev, v1.3.9, on Microsoft Windows [Version 10.0.17763.316], locale en-US)
    • Flutter version 1.3.9 at E:\Adar\Flutter\flutter_windows_v1.0.0-stable\flutter
    • Framework revision f91df4abe1 (2 days ago), 2019-03-09 21:19:28 -0500
    • Engine revision 4e54bc93ca
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Adar\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.1)
    • VS Code at C:\Users\Adar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

Code:
main.dart
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'ui/movies_ui.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: new ThemeData(
        fontFamily: 'Sofia Pro',
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  final Widget svg = SvgPicture.asset(
    'assets/search.svg',
  );
  @override
  Widget build(BuildContext context) {
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarBrightness: Brightness.dark,
        statusBarIconBrightness: Brightness.dark));
    return Scaffold(
      body: DefaultTabController(
        length: 3,
        child: Container(
          color: Colors.white,
          margin: EdgeInsets.only(top: 20),
          child: NestedScrollView(
              headerSliverBuilder:
                  (BuildContext context, bool innerBoxIsScrolled) {
                return <Widget>[
                  SliverAppBar(
                    forceElevated: false,
                    snap: true,
                    floating: true,
                    elevation: 0,
                    backgroundColor: Colors.white,
                    actions: <Widget>[
                      Spacer(),
                      ClipRRect(
                        clipper: RectangleClipper(),
                        borderRadius: BorderRadius.circular(25),
                        child: Container(
                            padding: EdgeInsets.only(top: 5),
                            decoration: BoxDecoration(color: Color(0xFFE9E9E9)),
                            width: MediaQuery.of(context).size.width -
                                MediaQuery.of(context).size.width / 5,
                            child: TextField(
                              style: TextStyle(fontSize: 18, height: 1),
                              maxLines: 1,
                              decoration: InputDecoration(
                                border: InputBorder.none,
                                contentPadding: null,
                                prefixIcon: Icon(Icons.search),
                              ),
                            )),
                      ),
                      Spacer(),
                      Container(
                        child: CircleAvatar(
                          backgroundColor: Colors.green.shade300,
                        ),
                      ),
                      Spacer(),
                    ],
                  ),
                  SliverPadding(
                    padding: EdgeInsets.only(bottom: 15),
                  ),
                  SliverPersistentHeader(
                    delegate: _SliverAppBarDelegate(
                      TabBar(
                        indicatorColor: Color(0xFF69CB6F),
                        labelColor: Colors.black87,
                        unselectedLabelColor: Colors.grey,
                        tabs: [
                          Tab(
                            child: Container(
                              child: Center(
                                child: Text("Movies",style: TextStyle(fontSize: 18),),
                              ),
                            ),
                          ),
                          Tab(
                            child: Container(
                              child: Center(
                                child: Text("Tv Series",style: TextStyle(fontSize: 18)),
                              ),
                            ),
                          ),
                          Tab(
                            child: Container(
                              child: Center(
                                child: Text("Cartoon",style: TextStyle(fontSize: 18)),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    pinned: true,
                  ),
                ];
              },
              body: TabBarView(
                physics: NeverScrollableScrollPhysics(),
                children: <Widget>[MovieUi(), Text("PAge 2"), Text("PAge 3")],
              )),
        ),
      ),
    );
  }
}

class RectangleClipper extends CustomClipper<RRect> {
  @override
  RRect getClip(Size size) {
    // TODO: implement getClip
    return null;
  }

  @override
  bool shouldReclip(CustomClipper<RRect> oldClipper) {
    // TODO: implement shouldReclip
    return null;
  }
}

class _SliverAppBarDelegate extends SliverPersistentHeaderDelegate {
  _SliverAppBarDelegate(this._tabBar);

  final TabBar _tabBar;

  @override
  double get minExtent => _tabBar.preferredSize.height;
  @override
  double get maxExtent => _tabBar.preferredSize.height;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return new Container(
      color: Colors.white,
      child: _tabBar,
    );
  }

  @override
  bool shouldRebuild(_SliverAppBarDelegate oldDelegate) {
    return false;
  }
}
`
movie_ui.dart
`import 'package:flutter/material.dart';
import 'package:flutter_swiper/flutter_swiper.dart';

class MovieUi extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: false,
      children: <Widget>[
        Container(
          width: MediaQuery.of(context).size.width,
          height: 170,
          padding: EdgeInsets.symmetric(vertical: 8),
          child: Swiper(
            layout: SwiperLayout.STACK,

            itemBuilder: (BuildContext context, int index) {
              return Stack(
                alignment: Alignment.topLeft,
                children: <Widget>[
                  Container(
                    height: 140,
                    width: 350,
                    decoration: BoxDecoration(
                        color: Colors.transparent,
                        boxShadow: [
                          BoxShadow(
                              color: Colors.black12,
                              offset: Offset(2, 5),
                              blurRadius: 8)
                        ]),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(15),
                      child: Image.network(
                        "http://via.placeholder.com/350x150",
                        fit: BoxFit.fill,
                        height: 140,
                      ),
                    ),
                  ),
                  Text(
                    index.toString(),
                    style: TextStyle(fontSize: 20),
                  )
                ],
              );
            },
            itemCount: 10,
            itemWidth: 300.0,
            // viewportFraction: 0.85,
            // scale: 0.9,
          ),
        ),
        Padding(
          padding: EdgeInsets.all(15),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Text(
                "English Movie",
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.w500),
              ),
              Text(
                "See All",
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
              )
            ],
          ),
        ),
        GridView.count(
          physics: ScrollPhysics(), // to disable GridView's scrolling
          shrinkWrap: true,
          crossAxisCount: 3,
          children: List.generate(20, (index) {
            return Center(
              child: Text("item $index"),
            );
          }),
        )
      ],
    );
  }
}
`

**Comment by phelipepalte** [comment]
Same problem here!

**Comment by larssn** [comment]
It happens when you have multiple scroll views on the same screen/page.

**Comment by lucaslalago** [comment]
Yes, it is still happening... at least in Android.

**Comment by escamoteur** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
