### ISSUE TITLE
Gettting error only on iOS devices: " Looking up a deactivated widget's ancestor is unsafe."

### ISSUE THREAD

**Issue by earyzhe** [flutter/flutter#29226]
Hey guys,

I have a very strange error that only occurs when I'm using IOS device.
Android devices work just fine.
Both devices are using the exact same dart code.

I use a show dialogue function to go to a menu where there is an option to use the image picker from the camera or from the photos library.

When the option is selected, the image picker opens with the relative option. Then you can select image. Once an image is selected the navigator pops the previous menu and then tries to upload the file to firebase to use as a Cached Network Image.

Also this log is appearing sometimes:
NoSuchMethodError: The method 'ancestorStateOfType' was called on null.

Too see Android screen recording( working ): https://youtu.be/L6JKH5AAYBg
And iOS Screen recording( not working ):  https://youtu.be/xNKIdKGh69A

## Steps to Reproduce

    
1. Show dialog Image picker options menu  => 
2. Show image picker => 
3. Select Image =>
4. await Upload image to firestore and return url =>
5. App Crashes with Error:

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Builder(dirty):
flutter: Looking up a deactivated widget's ancestor is unsafe.
flutter: At this point the state of the widget's element tree is no longer stable. To safely refer to a
flutter: widget's ancestor in its dispose() method, save a reference to the ancestor by calling
flutter: inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.

## Logs

      Andrews-MBP:dial_in_v1 earyzhe$ flutter run --verbose
[  +31 ms] executing: [/Users/earyzhe/dev/SDKs/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git log -n 1 --pretty=format:%H
[  +19 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] d166f4df3eebc084b9343c64ba9e6407120e765c
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 days ago
[        ] executing: [/Users/earyzhe/dev/SDKs/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +60 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-1-gd166f4df3
[ +392 ms] executing: /Users/earyzhe/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/earyzhe/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ZY3229ZJWW             device usb:336855040X product:nicklaus_fn model:Moto_E__4__Plus device:nicklaus_fn transport_id:3
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +14 ms] executing: idevice_id -h
[ +216 ms] executing: which ideviceinstaller
[   +5 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +195 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +5 ms] /Users/earyzhe/Library/Android/sdk/platform-tools/adb -s ZY3229ZJWW shell getprop
[  +80 ms] ro.hardware = mt6735
[        ] ro.build.characteristics = default
[   +1 ms] /Users/earyzhe/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +27 ms] ro.hardware = ranchu
[   +7 ms] Moto E 4 Plus             • ZY3229ZJWW                               • android-arm • Android 7.1.1 (API 25)
[   +1 ms] Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
[        ] Andrew's iPhone           • 6aa0c9719a85c174869a09656237b42f23701a91 • ios         • iOS 12.1.4
[        ] iPhone XR                 • B44465DC-EB35-43E8-99A0-B1C3765DAD86     • ios         • iOS 12.1 (simulator)
[  +14 ms] "flutter run" took 929ms.
[        ] "flutter run" took 929ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Users/earyzhe/dev/SDKs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
```

     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.

info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/repos/flutter_country_picker.dart:20:33 •
          unused_catch_clause
   info • The value of the field '_animation' isn't used • lib/widgets/custom_widgets.dart:587:27 • unused_field
   info • 'CupertinoDialog' is deprecated and shouldn't be used • lib/widgets/popups_widgets.dart:104:16 • deprecated_member_use

```
```

Andrews-MBP:dial_in_v1 earyzhe$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.2-pre.1, on Mac OS X 10.14.3 18D42, locale en-GB)
    • Flutter version 1.2.2-pre.1 at /Users/earyzhe/dev/SDKs/flutter
    • Framework revision d166f4df3e (12 days ago), 2019-02-28 07:52:52 +0000
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/earyzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (4 available)
    • Moto E 4 Plus             • ZY3229ZJWW                               • android-arm • Android 7.1.1 (API 25)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • Andrew's iPhone           • 6aa0c9719a85c174869a09656237b42f23701a91 • ios         • iOS 12.1.4
    • iPhone XR                 • B44465DC-EB35-43E8-99A0-B1C3765DAD86     • ios         • iOS 12.1 (simulator)

• No issues found!
```
```

**Comment by tomalabaster** [comment]
Are you able to provide the minimum code required to reproduce?

**Comment by earyzhe** [comment]
Hey Tom .

Here is what i think is relevant. Thanks for taking a look.

```
class ProfilePageState extends State<ProfilePage> {
  List<Widget> _appBarActions = [Container()];
  AssetImage _background;

  void initState() {
    _background = new AssetImage(
        Images.getProFileTypeBackgroundPhoto(widget._model.type));
    assert(widget._model.isFromUserFeed != null, 'isFromUserFeed is null');
    super.initState();
  }

  @override
  Widget build(BuildContext context) => ScopedModel<ProfilePageModel>(
      model: widget._model,
      child: StreamBuilder<bool>(
          stream: widget._model.isEditingStream,
          initialData: false,
          builder: (BuildContext context, AsyncSnapshot<bool> isEditing) =>
              Scaffold(
                appBar: PreferredSize(
                    preferredSize: Size.fromHeight(50),
                    child: ProfilePageAppBar()),
                body: ListView(children: <Widget>[
                  ProfileHeaderWidget(key: UniqueKey(), backround: _background),
                  ProfilePageBody(),
                ]),
                bottomNavigationBar: ProfilePageBottomBar(),
              )));
}
```

```

class ProfileHeaderWidget extends StatelessWidget {
  final AssetImage backround;

  ProfileHeaderWidget({@required Key key, @required this.backround})
      : super(key: key);

  @override
  Widget build(BuildContext context) => ScopedModelDescendant<ProfilePageModel>(
      builder: (BuildContext modelContext, _, ProfilePageModel model) =>
          StreamBuilder<bool>(
              stream: model.isEditingStream,
              initialData: false,
              builder: (BuildContext context, AsyncSnapshot<bool> isEditing) {
                return Container(
                  decoration: BoxDecoration(
                      image:
                          DecorationImage(image: backround, fit: BoxFit.cover)),
                  child: Container(
                      decoration: new BoxDecoration(
                          color: AppColors.getColor(ColorType.lightBackground)
                              .withAlpha(200)),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Expanded(
                            child: Container(),
                          ),

                          // Profile Image
                          ProfilePageImage(),

                          !model.isFromUserFeed &&
                                  ProfilePageModel.of(context) != null
                              ? isEditing.data
                                  ? PublicProfileSwitch()
                                  : Expanded(
                                      child: Container(),
                                    )
                              : Expanded(
                                  child: Container(),
                                ),
                        ],
                      )),
                );
              }));
}

```

```
class ProfilePageImage extends StatelessWidget {

  Future _getimage(BuildContext context, ProfilePageModel model) async {
    PopUps.showCircularProgressIndicator(context);

    var filePath = await PopUps.getimageFromCameraOrGallery(context)
        .catchError(Sentry.report);

    if (filePath != null || filePath is String) {
      String url = await Dbf.upLoadFileReturnUrl(File(filePath), [
        DatabaseIds.user,
        model.userId,
        DatabaseIds.images,
        model.databaseId
      ])
          .timeout(Duration(seconds: 16),
              onTimeout: () =>
                  throw (TimeoutException('Upload is taking too long')))
          .catchError((error) {
        if (error is TimeoutException) {
          onImageTimeout(context);
        } else {
          Sentry.report(error);
        }
      });

      /// Wait until image has saved
      if (model.imageUrl != null && model.imageUrl != '') {
        MainBloc.of(context).cache.setFile(url, File(filePath));
      }
      model.profileImageUrl = url;
      Navigator.pop(context);
    } else if (filePath is ResetImageRequest) {
      model.profileImageUrl = null;
      Navigator.pop(context);
    } else {
      Navigator.pop(context);
    }
  }

  void onImageTimeout(BuildContext context) {
    Navigator.pop(context);
    PopUps.showAlert(
        'Warning',
        "The picture is taking too long to upload. Maybe it's your internet connection ",
        'ok',
        () => Navigator.pop(context),
        context);
  }


  @override
  Widget build(BuildContext context) =>

      /// Profile Image

      ScopedModelDescendant(
          builder: (BuildContext modelContext, _, ProfilePageModel model) =>
              StreamBuilder<Profile>(
                  stream: model.profileStream,
                  builder:
                      (BuildContext context, AsyncSnapshot<Profile> snapshot) {
                    String placeholder = snapshot.hasData
                        ? snapshot.data.placeholder
                        : model.placeholder;
                    String imageUrl = snapshot.hasData
                        ? snapshot.data.imageUrl
                        : model.imageUrl;
                    String objectId = snapshot.hasData
                        ? snapshot.data.objectId
                        : model.objectId;

                    return Container(
                        padding: EdgeInsets.all(20.0),
                        child: InkWell(
                            child: CircularCachedProfileImage(
                                placeholder, imageUrl, 200, objectId),
                            onTap: () {
                              if (model.isEditing) {
                                _getimage(context, model);
                              }
                            }));
                  }));
}

```

```
 static Future<dynamic>getimageFromCameraOrGallery(BuildContext contextIn)async{

    var result = await showDialog(context: contextIn, builder: (BuildContext context){
      return CupertinoImagePicker() ;})
    .catchError(Sentry.report);
    
    return result;
  }
```

```
class CupertinoImagePicker extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Center(
            child: Container(
                width: 300,
                child: CupertinoActionSheet(
                  title: Text(
                    StringLabels.photoSource,
                    style: Theme.of(context).textTheme.subtitle,
                  ),
                  actions: <Widget>[
                    CupertinoImagePickerDiolog(ImageSource.camera),
                    CupertinoImagePickerDiolog(ImageSource.gallery),
                    CupertinoDialogAction(
                      isDestructiveAction: true,
                      child: Text('Reset to default', style: Theme.of(context).textTheme.display1),
                      onPressed: () { 
                        PopUps.showTwoOptionsDiolog(
                        context,
                        title:'Warning',
                        message:' Are you sure you want to delete this image and reset it to default',
                        actionOneTitle: 'Yes',
                        actionOne: () { Navigator.pop(context, ResetImageRequest);},
                        actionTwoTitle: 'No',
                        actionTwo: () { Navigator.pop(context);},);})
                  ],
                )));
  }
}
```

```
class CupertinoImagePickerDiolog extends StatelessWidget {
  final ImageSource _imageSource;

  CupertinoImagePickerDiolog(this._imageSource);

  @override
  Widget build(BuildContext context) {
    String _title = '';

    if (_imageSource == ImageSource.camera) {
      _title = StringLabels.camera;
    } else {
      _title = StringLabels.photoLibrary;
    }

    return CupertinoDialogAction(
        child: Text(_title, style: Theme.of(context).textTheme.display1),
        isDestructiveAction: false,
        onPressed: () =>  showImagePicker(context));
  }

  void showImagePicker(BuildContext context) {
    ImagePicker.pickImage(
            maxWidth: 512.0, maxHeight: 384.0, source: _imageSource)
        .then((image) => handleImagePickerReturn(image, context))
        .catchError((error) => print(error));
  }

  void handleImagePickerReturn(
      dynamic image, BuildContext context) async {
    if (image != null) {
      ///Image is a File
      String filePath = (image as File).path;
      Navigator.pop(context, filePath);
    }
  }
}
```

**Comment by iapicca** [comment]
Hi @earyzhe 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Hi @earyzhe 
the code you kindly provided seems to partially rely on fluttefire plugins;
if you are still experiencing the issue with the latest stable (or above)
could you please provide a **runnable** minimal code sample
that use only first party plugins together 
with your updated `flutter doctor -v`
and your `pubspec.yaml`
thank you

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
