### ISSUE TITLE
Having a way to hide overflow rendering in release mode

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#29233]
We already have a way to replace the red screen of the dead by something more ergonomic for end users. But as I know we can't do the same for overflow rendering problem. It's quite problematic to have those on release mode, I'll probably want to log those but definitely not show them to the end users.  

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale fr-FR)
    • Flutter version 1.2.1 at /Users/jaumard/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[✓] Connected device (1 available)
    • iPhone 6 • 76669055-742B-42A3-A9B1-4EA489698F2D • ios • iOS 10.3 (simulator)

• No issues found!
```

**Comment by Kartik1607** [comment]
> In flutter, overflow is considered as an error. And should be fixed, not ignored - by [Rémi Rousselet](https://stackoverflow.com/users/8394265/r%C3%A9mi-rousselet)

**Comment by jaumard** [comment]
Like red screen... But even if you're not ignoring them doesn't mean you'll not miss some for some devices/ screen factors... And end users shouldn't see those. That why I said I want log and crash report them but not show them to users

**Comment by Kartik1607** [comment]
The overflow is painted using `paintOverflowIndicator`  method at [this](https://github.com/flutter/flutter/blob/e41f1463cd9a7237df89bdec920745c8f7d22b8d/packages/flutter/lib/src/rendering/debug_overflow_indicator.dart#L257)

You can clone the flutter repo, update the method and then build using the local flutter repo.

**Comment by Liuzhiyang94** [comment]
And now , I meet some problems.I find the `overflow` will not appear in release mode.And it not call the `FlutterError.onError` ,Is there any ways to report overflow in release mode?

**Comment by SotoArmando** [comment]
what if i want to make a collapsible AnimatedContainer i need to know if there is a workaround using flutter and solving the issue.

**Comment by SotoArmando** [comment]
> what if i want to make a collapsible AnimatedContainer i need to know if there is a workaround using flutter and solving the issue.

I made something *clipping the collapsed content inside a ListView.

**Comment by goderbauer** [comment]
As far as I can tell we do not render the overflow markings (yellow/back strips) produced by `DebugOverflowIndicatorMixin.paintOverflowIndicator` in release mode. All calls to that method are happening in asserts, which are disabled in release mode. I verified this with the following example:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyWidget());
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        height: 100,
        width: 100,
        color: Colors.green,
        child: UnconstrainedBox(
          child: Container(
            color: Colors.yellow,
            height: 50,
            width: 300,
          )
        ),
      ),
    );
  }
}
```

When run with `flutter run --release` it does not render any yellow/black strips to indicate overflow. However, when you remove the `--release` flag (to run in debug mode), it does show the strips. This all seems to work as expected (and as requested in this bug).

Can somebody post some minimal, but runnable example code where we do render the overflow warning in release mode? Otherwise I intend to close this bug.
