### ISSUE TITLE
I setup android studio, flutter, etc on a new laptop running Window 10. but it is not working Following is the Log :

### ISSUE THREAD

**Issue by vishvadeepaktripathi** [flutter/flutter#29237]
## Steps to Reproduce

1. Flutter Doctor Output
C:\Users\username>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.3.8, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
\ Checking Android licenses is taking an unexpectedly long time...Error retrieving device properties for ro.product.cpu.abi:
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.32.1)
[√] Connected device (1 available)

• No issues found!
2.
You can see here Error retrieving device properties for ro.product.cpu.abi: Error and my device is connected with Andriod studio.
You can see here Error retrieving device properties for ro.product.cpu.abi: Error and my device is connected with Andriod studio.
Currently i am using adb version 1.0.39 and
## Logs

Following the Error from Android studio :
Error retrieving device properties for ro.hardware:

Launching lib\main.dart on <
mobile varsion> in debug mode...
Initializing gradle...
Resolving dependencies...
--------- beginning of main
03-10 18:14:09.910 D/vendor.qti.bluetooth@1.0-wake_lock( 691): Release wakelock is released
Unhandled exception:
Exit code -1073740940 from: D:/Mobile-Dev/src/Andriod/SDK\platform-tools\adb -s 5df11745 shell -x logcat -v time -t 1
#0 _runWithLoggingSync (package:flutter_tools/src/base/process.dart:352:7)
#1 runCheckedSync (package:flutter_tools/src/base/process.dart:283:10)
#2 AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:507:27)
#3 _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:681:41)
#4 _runGuarded (dart:async/stream_controller.dart:805:24)
#5 _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#6 _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#7 _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#8 FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:261:71)
#9 FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:304:5)

#10 HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)

#11 AppDomain.startApp. (package:flutter_tools/src/commands/daemon.dart:393:23)
#12 AppDomain.launch. (package:flutter_tools/src/commands/daemon.dart:452:26)

#13 AppContext.run. (package:flutter_tools/src/base/context.dart:142:29)

#14 _rootRun (dart:async/zone.dart:1124:13)
#15 _CustomZone.run (dart:async/zone.dart:1021:19)
#16 _runZoned (dart:async/zone.dart:1516:10)
#17 runZoned (dart:async/zone.dart:1463:12)
#18 AppContext.run (package:flutter_tools/src/base/context.dart:141:18)

#19 AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:835:20)
#20 AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:450:15)

#21 AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:387:12)

#22 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:281:38)

#23 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#24 _asyncThenWrapperHelper. (dart:async/runtime/libasync_patch.dart:77:64)
#25 _rootRunUnary (dart:async/zone.dart:1132:38)
#26 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27 _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29 Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30 Future._complete (dart:async/future_impl.dart:473:7)
#31 _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32 _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#33 _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#34 RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#35 _asyncThenWrapperHelper. (dart:async/runtime/libasync_patch.dart:77:64)
#36 _rootRunUnary (dart:async/zone.dart:1132:38)
#37 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38 _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#39 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#40 Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#41 Future._complete (dart:async/future_impl.dart:473:7)
#42 _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#43 _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#44 _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#45 AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#46 _asyncThenWrapperHelper. (dart:async/runtime/libasync_patch.dart:77:64)
#47 _rootRunUnary (dart:async/zone.dart:1132:38)
#48 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49 _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#50 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#51 Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#52 Future._complete (dart:async/future_impl.dart:473:7)
#53 _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#54 _AsyncAwaitCompleter.complete. (dart:async/runtime/libasync_patch.dart:33:20)
#55 _rootRun (dart:async/zone.dart:1124:13)
#56 _CustomZone.run (dart:async/zone.dart:1021:19)
#57 _CustomZone.bindCallback. (dart:async/zone.dart:947:23)
#58 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#59 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#60 _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#61 _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```
```

```
```

**Comment by vishvadeepaktripathi** [comment]
Dear All 
    This problem is related with ro.hardware or adb server couldn't get access on 
     Emulator or Mobile devices. 
    Now you can follow the bellow instruction : 
    [https://stackoverflow.com/questions/53429152/exception-while-running-flutter- 
   application-error-retrieving-device-properties/54164463#54164463][1]

   https://stackoverflow.com/questions/55117492/i-setup-android-studio-flutter-etc-on-a-new-laptop- 
   running-window-10-but-it-i/55217309#55217309
   For me this was the solution. 

   Thank you for your support and reading


  [1]: https://stackoverflow.com/questions/53429152/exception-while-running-flutter-application-error-retrieving-device-properties/54164463#54164463

**Comment by DanTup** [comment]
This looks like the same issue as https://github.com/flutter/flutter/issues/33938. There's a PR at https://github.com/flutter/flutter/pull/33951 that should fix this.
