### ISSUE TITLE
about android with Flutter Mixture develop

### ISSUE THREAD

**Issue by moonway0127** [flutter/flutter#29244]
When I only run flutter module , pick image very fast and nice.

But when android with flutter mixture develop ：  

    print('start');      ✅
    var image = await ImagePicker.pickImage(source: style);    ❌ 
    print('111111111111111');     ❌

or

    print('start');      ✅
    ImagePicker.pickImage(source: style).then((file){ doSomething...});    ❌ 
    print('111111111111111');     ✅

logcat:

I/flutter: start
I/Timeline: Timeline: Activity_launch_request time:94986931 intent:Intent {act=android.intent.action.GET_CONTENT typ=image/* }
D/LogServer: foreground switch background
D/LogServer: background to foreground

and no other error

**Comment by moonway0127** [comment]
use image_picker: ^0.4.12+1  
because AndroidX need 28 ,but 28 have a bug about edit

**Comment by iapicca** [comment]
Hi @moonway0127 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
