### ISSUE TITLE
Fail to migrate to AndroidX from my flutter app project

### ISSUE THREAD

**Issue by goldenhuang** [flutter/flutter#29249]
Hello,

    I want to migrate my flutter app project into AndroidX. 
    I follow the formal released instruction by modifying the build.gradle from my project as below.
    Also modify my gradle.properties as :
       org.gradle.jvmargs=-Xmx1536M
       android.useAndroidX=true
       android.enableJetifier=true
    Unfortunately after clicking Refactor=>Migrating to AndroidX ..., I got the following error message:
    Unable to migrate to AndroidX...
    You need to have compileSdk set to at least 28 in your module build.gradle to migrate to AndroidX
    Right now I have no clue of how I can continue to do the migration further. 
    Some plugins I am using do not support AndroidX. 
    I assume that with the setting of "android.enableJetifier=true" the system will migrate those plugins automatically? Or it won't and causes the issue?

    Please help how I can fix this?

=> my build.gradle

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    android {
        compileOptions {
            sourceCompatibility 1.8
            targetCompatibility 1.8
        }
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.0.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.0.2'
}

apply plugin: 'com.google.gms.google-services'

=> End of my build.gradle

=> flutter doctor -v
C:\Projects\Flutter\Backup\release\1.7\funtour7777>flutter doctor -v
[√] Flutter (Channel beta, v1.2.1, on Microsoft Windows [Version 10.0.18342.8], locale en-US)
    • Flutter version 1.2.1 at C:\Projects\Flutter\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Golden\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Golden\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4892.25

[√] VS Code
    • VS Code at C:\Users\Golden\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] Connected device (1 available)
    • LG H830 • LGH830b443707e • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by goldenhuang** [comment]
I cannot refactor it by migrating to AndroidX even from the initial flutter app created by Android Studio 3.3.2... It always complains "unable to migrate to AndroidX", "You need to have compileSdk set to at least 28 in your module build.gradle to migrate to AndroidX" even I saw that build.gradle has set compileSdkVersion to be 28 already! 
Please exactly tell the steps to migrate to AndroidX from a scratch flutter app created by Android Studio 3.3.2.

**Comment by jonneymendoza** [comment]
Guys come on any help here from the flutter devs? Having same issues too

**Comment by goldenhuang** [comment]
It seems that the issue can be resolved like this : 
=> First of all instead of refactoring the flutter app project from the menu of Android Studio, just open the app project's android folder with Android Studio and then do the refactoring for the migration to AndroidX. Just follow the instructions from the Android Studio and the migration can be done!! 
=> Then open the flutter app project, build.gradle and gradle.properties need to be modified as the formal instruction provided by flutter. After the modification, then I can build the project successfully and supposed that the app has included AndroidX support already!!
If someone thinks that my instruction for that migration is wrong, just let me know. Thanks!

**Comment by goldenhuang** [comment]
More comments on this : 
(1) before refactoring from android folder, make sure that no changes on build.gradle and gradle.properties in the formal instruction have been done till the migration to AndroidX on android folder has been completed.
(2) Maybe system requesting some updates, just go ahead to complete it.
(3) Do the refactoring just after the indexing process has been completed successfully

**Comment by goldenhuang** [comment]
More comments on this : 
(4) And make sure that all used plugins have been migrated to AndroidX. Some plugins' latest versions have been migrated. I tried this already and the test flutter app can be built successfully.

**Comment by jonneymendoza** [comment]
@goldenhuang what instructions are you referring to? can you give a detailed step by step on how you got this to work on a flutter module thats included on an android project?

**Comment by goldenhuang** [comment]
=> Open that android folder of your flutter app from Android Studio's initial bring-up screen.
=> Then Android Studio will build the android project.
=> This may ask some updates such as gradle version, etc... and complete those updates.
=> Till the indexing process is completed, you can do the refactoring and migrate to AndroidX from the menu of Android Studio.
=> Once this migration is done, close the project and reopen your flutter app project.
=> Make sure build.gradle and gradle.properties have been modified in order to support AndroidX.
=> Then you can build your flutter app successfully. 
=> Once you complete the build and run, you can continue to upgrade your plugins which have the versions to support AndroidX.

**Comment by HamzataBarrie** [comment]
Hello gurs, I had the same problem it's 3 days ago, who for help us please??

**Comment by titusfrezer** [comment]
Same problem still now
