### ISSUE TITLE
Linter for ARC++ on Chromebooks should provide feedback about unsupported features

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#29240]
The linter should provide errors when developers targeting ARC++ on Chromebooks specify needing one of the following devices:

- android.hardware.camera – Back-facing camera
- android.hardware.camera.autofocus – Camera that uses autofocus
- android.hardware.camera.capability.manual_post_processing  – Camera that uses the MANUAL_POST_PROCESSING feature, including functionality for overriding auto white balance
- android.hardware.camera.capability.manual_sensor – Camera that uses the MANUAL_SENSOR feature, including auto-exposure locking support
- android.hardware.camera.capability.raw – Camera that uses the RAW feature, including the ability to save DNG (raw) files and provide DNG-related metadata
- android.hardware.camera.flash – Camera that uses flash
- android.hardware.camera.level.full – Camera that uses FULL-level image-capturing support
- android.hardware.consumerir – Infrared (IR)
- android.hardware.location.gps – GPS
- android.hardware.nfc – Near-Field Communication (NFC)
- android.hardware.nfc.hce – NFC card emulation (deprecated)
- android.hardware.sensor.barometer – Barometer (air pressure)
- android.hardware.telephony – Telephony, including radio with data communication services
- android.hardware.telephony.cdma – Telephony Code Division Multiple Access (CDMA) network support
- android.hardware.telephony.gsm – Telephony Global System for Mobile Communications (GSM) network support
- android.hardware.type.automotive – Android Auto user interface
- android.hardware.type.television – Television (deprecated)
- android.hardware.usb.accessory – USB accessory mode
- android.hardware.usb.host – USB host mode

The linter should provide warnings when the application under development specifies access to the following hardware devices, as they _may_ not be supported on some Chromebooks.

- android.hardware.sensor.accelerometer – Accelerometer (device orientation)
- android.hardware.sensor.compass – Compass
- android.hardware.sensor.gyroscope – Gyroscope (device rotation and twist)
- android.hardware.sensor.light – Light
- android.hardware.sensor.proximity – Proximity (to user)
- android.hardware.sensor.stepcounter – Step counter
- android.hardware.sensor.stepdetector – Step detector

**Comment by kf6gpe** [comment]
We should also provide warnings about software features not currently supported:

- android.software.app_widgets – App Widgets on the Home screen
- android.software.device_admin – Device policy administration
- android.software.home_screen – Replaces device's Home screen
- android.software.input_methods – Custom input methods (instances of InputMethodService)
- android.software.leanback – UI designed for large-screen viewing
- android.software.live_wallpaper – Animated wallpapers
- android.software.live_tv – Streaming live TV programs
- android.software.managed_users – Secondary users and managed profiles
- android.software.midi – Musical Instrument Digital Interface (MIDI) protocol, which supports connecting to musical instruments and providing sound
- android.software.sip – Session Initiation Protocol (SIP) service, which supports video conferencing and instant messaging
- android.software.sip.voip – Voice Over Internet Protocol (VoIP) service based on SIP, which supports two-way video conferencing

**Comment by devoncarew** [comment]
closing in favor of #29239
