### ISSUE TITLE
Homepage toolbar's flexible space in gallery app fades in when going back

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2924]
Every time you go back to the home page, the toolbar's flexible space fades in. Notice the moving pieces of construction paper fade in when the user returns back to the homepage. That feels weird; going back should act as if the page had been behind the whole time (that's why the page slides down), so the animation should just be ongoing already.

cc @vlidholt, @HansMuller

**Comment by abarth** [comment]
Fixed by removing animation from the homepage header.
