### ISSUE TITLE
Linter should guard against asserting privileges not supported on ARC++ for Chromebooks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#29241]
The ARC++ runtime for Chromebooks does not support all of the permissions used by standard Android. We should provide errors when the user attempts to require one of the following permissions:

Subsystem | Operation | Privilege
-- | -- | --
Camera | CAMERA | android.hardware.camera andandroid.hardware.camera.autofocus
Telephony | CALL_PHONE | android.hardware.telephony
Telephony  | CALL_PRIVILEGED | android.hardware.telephony
Telephony  | MODIFY_PHONE_STATE | android.hardware.telephony
Telephony  | PROCESS_OUTGOING_CALLS | android.hardware.telephony
Telephony  | READ_SMSREAD_SMS | android.hardware.telephony
Telephony  | RECEIVE_SMS | android.hardware.telephony
Telephony  | RECEIVE_MMS | android.hardware.telephony
Telephony  | RECEIVE_WAP_PUSH | android.hardware.telephony
Telephony  | SEND_SMS | android.hardware.telephony
Telephony  | WRITE_APN_SETTINGS | android.hardware.telephony
Telephony  | WRITE_SMS | Android.hardware.telephony

**Comment by devoncarew** [comment]
closing in favor of https://github.com/flutter/flutter/issues/29239
