### ISSUE TITLE
Lint reliance on NDK libraries for ARC++ on Chromebooks

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#29242]
Chromebook ARC++ targeted applications using the Android NDK libraries with a target SDK version is 23 or higher must ensure that text relocations are removed from both the ARM and x86 versions of your NDK libraries, as they're not compatible in Android 6.0 (API level 23) and higher.

We should provide lint messages if we see text relocations in linked libraries on Chromebooks.

**Comment by devoncarew** [comment]
closing in favor of #29239
