### ISSUE TITLE
webview_flutter 0.3.4 Flutter: Web view application only a particular website(main url) run in the application, others open in local browser of phone

### ISSUE THREAD

**Issue by amankataria** [flutter/flutter#29251]
I have a web view application in Flutter. The plugin/package is "flutter_webview_plugin". In Webview Scaffold, I have url= 'www.google.com'. Now I want that any URL which doesn't contain "google.com" opens in the local browser of the phone.

Maybe if I can restrict the Web view plugin if URL doesn't contain "google.com"

Please let me know how can I achieve this.

Here is my code:

```
 WebviewScaffold(
    url: "http://www.google.com")
```
**Further Clarification**: I have a web view application. So the website that I have, has a lot of links in it. I don't want links other than my domain links to load in webview app. I want it to open externally.

Link to issue first reported: https://stackoverflow.com/questions/55125577/flutter-web-view-application-only-a-particular-website-run-in-the-application

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
