### ISSUE TITLE
Links in sample code descriptions are hard to read

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#29261]
Hyperlinks in sample code descriptions are hard to read.  The documentation links are blue... against a blue background.  For example, see https://docs.flutter.io/flutter/material/Scaffold-class.html:

![Screenshot from 2019-03-12 17-42-28](https://user-images.githubusercontent.com/17391434/54245525-490ced80-44ee-11e9-8cc9-29cb7b7e1070.png)

**Comment by shihaohong** [comment]
I think the hyperlinks are easier to read now, so I'll close this issue out.

<img width="1143" alt="Screen Shot 2020-11-02 at 5 57 07 PM" src="https://user-images.githubusercontent.com/27032613/97854742-d5f46280-1d34-11eb-8a36-a8bf72b66c4d.png">
