### ISSUE TITLE
Flutter Doc License

### ISSUE THREAD

**Issue by SoA-YD** [flutter/flutter#29263]
Hello, I am a student majoring in computer engineering in Korea. 

I am a student at Handong Global University and I would like to produce an online lecture course on developing mobile apps using Flutter and Firebase.

I'd like to ask if it's okay to use the following for making training material.
- Official website contents
- Official GitHub contents
- Downloadable files from the official site

The lecture I'm going to produce is an open-type lecture that anyone can see, not for profit.
I will look forward to the response from flutter team.

**Comment by escamoteur** [comment]
Hi, is this question still important for you?

**Comment by NoCapDeveloper** [comment]
@escamoteur  it is for me :)

**Comment by escamoteur** [comment]
@timsneath I guess this is a call for you or @csells

**Comment by timsneath** [comment]
Flutter content is licensed under the terms of use (https://flutter.dev/tos). Flutter code is licensed under a BSD-style license (https://github.com/flutter/flutter/blob/master/LICENSE).
