### ISSUE TITLE
fatal error: 'cstddef' file not found

### ISSUE THREAD

**Issue by ikonan** [flutter/flutter#29280]
zdsoft@looxoojoo:~$ brew install --HEAD usbmuxd
==> Cloning https://git.sukimashita.com/libusbmuxd.git
Updating /Users/zdsoft/Library/Caches/Homebrew/usbmuxd--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at c75605d Return meaningful error codes from usbmuxd_connect()
==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/usbmuxd/HEAD-c75605d_1
==> make install
Last 15 lines from /Users/zdsoft/Library/Logs/Homebrew/usbmuxd/03.make:
In file included from /usr/local/include/string.h:25:
/usr/local/include/plist/Node.h:26:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
make[1]: *** [collection.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from socket.c:28:
In file included from /usr/local/include/string.h:25:
/usr/local/include/plist/Node.h:26:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
make[1]: *** [socket.lo] Error 1
make: *** [install-recursive] Error 1

**Comment by guodunsong** [comment]
这问题是是brew 环境的问题 
用命令: brew doctor 诊断一下，
然后根据提示把没有作用的头文件全部删除掉，在重新安装应该就没问题了。
原因： 很可能是其他无用的库和头文件导致了cstddef 这个文件的冲突。

**Comment by jaiswalshubham84** [comment]
currently, i am facing the same issue.
can anybody suggest me how to fix it.

**Comment by badhabitustc** [comment]
> currently, i am facing the same issue.
> can anybody suggest me how to fix it.

Wrong header file was placed at /usr/local/include .
run _**brew doctor**_  and delete Unexpected header files

for this case just remove 
/usr/local/include/string.h

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
