### ISSUE TITLE
I am having difficulty getting it to work

### ISSUE THREAD

**Issue by AlaaDz31** [flutter/flutter#29285]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

C:\Windows\System32>flutter --verbose create
[  +26 ms] executing: [D:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +1 ms] executing: [D:\flutter\] git rev-parse --abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[   +1 ms] executing: [D:\flutter\] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[   +2 ms] executing: [D:\flutter\] git log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[   +2 ms] executing: [D:\flutter\] git log -n 1 --pretty=format:%ar
[  +40 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 4 weeks ago
[   +1 ms] executing: [D:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +44 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.2.1-0-g8661d8aec
[ +232 ms] "flutter create" took 130ms.
[  +97 ms] "flutter create" took 130ms.
No option specified for the output directory.
Create a new Flutter project.

If run on a project that already exists, this will repair the project, recreating any files that are missing.

Usage: flutter create <output directory>
-h, --help                                                                                                        Print
this usage information.
    --[no-]pub
    Whether to run "flutter packages get" after the project has been created.
                                                                                                                  (defaults
                                                                                                                  to on)

    --[no-]offline                                                                                                When
    "flutter packages get" is run by the create command, this indicates whether to run it in offline mode or not. In
    offline mode, it will need to have all dependencies already available in the pub cache to succeed.
    --[no-]with-driver-test                                                                                       Also
    add a flutter_driver dependency and generate a sample 'flutter drive' test.
-t, --template=<type>
Specify the type of project to create.

          [app]
          (default) Generate a Flutter application.
          [package]
          Generate a shareable Flutter project containing modular Dart code.
          [plugin]
          Generate a shareable Flutter project containing an API in Dart code with a platform-specific implementation
          for Android, for iOS code, or for both.

-s, --sample=<the sample ID of the desired sample from the API documentation website (http://docs.flutter.io)>
Specifies the Flutter code sample to use as the main.dart for an application. Implies --template=app.
    --[no-]overwrite                                                                                              When
    performing operations, overwrite existing files.
    --description                                                                                                 The
    description to use for your new Flutter project. This string ends up in the pubspec.yaml file.
                                                                                                                  (defaults
                                                                                                                  to "A new
                                                                                                                  Flutter
                                                                                                                  project.")

    --org                                                                                                         The
    organization responsible for your new Flutter project, in reverse domain name notation. This string is used in Java
    package names and as prefix in the iOS bundle identifier.
                                                                                                                  (defaults
                                                                                                                  to
                                                                                                                  "com.examp
                                                                                                                  le")

    --project-name                                                                                                The
    project name for this new Flutter project. This must be a valid dart package name.
-i, --ios-language                                                                                                [objc
(default), swift]
-a, --android-language                                                                                            [java
(default), kotlin]

Run "flutter help" to see global options.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:197:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

C:\Windows\System32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: acdb2626437b9b85)
Unhandled exception:
Invalid argument(s): Cannot find executable for where.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#2      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:164:49)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:41:43)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:309:38)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:331:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#11     androidSdk (package:flutter_tools/src/android/android_sdk.dart:20:37)
#12     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:9)
<asynchronous suspension>
#13     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#14     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#15     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#16     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#17     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#20     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#29     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#31     _doctorText (package:flutter_tools/runner.dart:187:19)
#32     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#33     _doctorText (package:flutter_tools/runner.dart:183:27)
#34     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#35     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#36     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#37     _handleToolError (package:flutter_tools/runner.dart:120:33)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._complete (dart:async/future_impl.dart:473:7)
#45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#46     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#47     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#48     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#49     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#55     Future._complete (dart:async/future_impl.dart:473:7)
#56     Stream.fold.<anonymous closure> (dart:async/stream.dart:724:18)
#57     _rootRun (dart:async/zone.dart:1120:38)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#60     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#61     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#62     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#63     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#64     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#65     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#66     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#67     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#68     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#69     _rootRun (dart:async/zone.dart:1120:38)
#70     _CustomZone.run (dart:async/zone.dart:1021:19)
#71     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#72     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#73     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#74     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#75     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#76     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#77     _rootRun (dart:async/zone.dart:1120:38)
#78     _CustomZone.run (dart:async/zone.dart:1021:19)
#79     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#80     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#81     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#82     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#83     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#84     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#85     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#86     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#87     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#88     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#89     _rootRun (dart:async/zone.dart:1120:38)
#90     _CustomZone.run (dart:async/zone.dart:1021:19)
#91     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#92     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#93     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#94     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#95     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#96     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#97     _rootRun (dart:async/zone.dart:1120:38)
#98     _CustomZone.run (dart:async/zone.dart:1021:19)
#99     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#100    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#101    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#102    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#103    _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#104    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#105    _StreamController.close (dart:async/stream_controller.dart:622:5)
#106    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#107    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#108    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#109    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#110    _rootRunUnary (dart:async/zone.dart:1132:38)
#111    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#112    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#113    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#114    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#115    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#116    _StreamController._add (dart:async/stream_controller.dart:640:7)
#117    _StreamController.add (dart:async/stream_controller.dart:586:5)
#118    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#119    _rootRunUnary (dart:async/zone.dart:1132:38)
#120    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#121    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#122    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#123    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#124    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#125    _StreamController._add (dart:async/stream_controller.dart:640:7)
#126    _StreamController.add (dart:async/stream_controller.dart:586:5)
#127    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#128    _rootRun (dart:async/zone.dart:1120:38)
#129    _CustomZone.run (dart:async/zone.dart:1021:19)
#130    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#131    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#132    _rootRun (dart:async/zone.dart:1124:13)
#133    _CustomZone.run (dart:async/zone.dart:1021:19)
#134    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#135    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#136    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#137    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#138    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

C:\Windows\System32>flutter doctor -v

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 0052fcb418430464)
Unhandled exception:
Invalid argument(s): Cannot find executable for where.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#2      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:164:49)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:41:43)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:309:38)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:331:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#11     androidSdk (package:flutter_tools/src/android/android_sdk.dart:20:37)
#12     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:9)
<asynchronous suspension>
#13     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#14     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#15     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#16     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#17     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#20     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#29     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#31     _doctorText (package:flutter_tools/runner.dart:187:19)
#32     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#33     _doctorText (package:flutter_tools/runner.dart:183:27)
#34     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#35     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#36     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#37     _handleToolError (package:flutter_tools/runner.dart:120:33)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._complete (dart:async/future_impl.dart:473:7)
#45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#46     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#47     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#48     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#49     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#55     Future._complete (dart:async/future_impl.dart:473:7)
#56     Stream.fold.<anonymous closure> (dart:async/stream.dart:724:18)
#57     _rootRun (dart:async/zone.dart:1120:38)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#60     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#61     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#62     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#63     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#64     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#65     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#66     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#67     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#68     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#69     _rootRun (dart:async/zone.dart:1120:38)
#70     _CustomZone.run (dart:async/zone.dart:1021:19)
#71     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#72     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#73     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#74     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#75     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#76     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#77     _rootRun (dart:async/zone.dart:1120:38)
#78     _CustomZone.run (dart:async/zone.dart:1021:19)
#79     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#80     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#81     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#82     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#83     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#84     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#85     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#86     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#87     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#88     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#89     _rootRun (dart:async/zone.dart:1120:38)
#90     _CustomZone.run (dart:async/zone.dart:1021:19)
#91     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#92     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#93     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#94     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#95     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#96     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#97     _rootRun (dart:async/zone.dart:1120:38)
#98     _CustomZone.run (dart:async/zone.dart:1021:19)
#99     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#100    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#101    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#102    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#103    _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#104    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#105    _StreamController.close (dart:async/stream_controller.dart:622:5)
#106    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#107    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#108    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#109    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#110    _rootRunUnary (dart:async/zone.dart:1132:38)
#111    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#112    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#113    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#114    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#115    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#116    _StreamController._add (dart:async/stream_controller.dart:640:7)
#117    _StreamController.add (dart:async/stream_controller.dart:586:5)
#118    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#119    _rootRunUnary (dart:async/zone.dart:1132:38)
#120    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#121    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#122    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#123    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#124    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#125    _StreamController._add (dart:async/stream_controller.dart:640:7)
#126    _StreamController.add (dart:async/stream_controller.dart:586:5)
#127    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#128    _rootRun (dart:async/zone.dart:1120:38)
#129    _CustomZone.run (dart:async/zone.dart:1021:19)
#130    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#131    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#132    _rootRun (dart:async/zone.dart:1124:13)
#133    _CustomZone.run (dart:async/zone.dart:1021:19)
#134    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#135    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#136    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#137    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#138    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by rubensdemelo** [comment]
Use StackOverflow for this, use #flutter tag. Post and format your your code and log.

**Comment by stuartmorgan** [comment]
> C:\Windows\System32>flutter --verbose create

As it said in the error message and help output that was displayed, you need to provide an output directory for this command.
