### ISSUE TITLE
[channel dev / Android only] FloatingActionButton does not show its child if it is an Icon or a Text widget, after a dynamic rebuild.

### ISSUE THREAD

**Issue by parsodyl** [flutter/flutter#29291]
- SDK version: Channel dev, v1.3.9
- How to reproduce it:
1. Create a new Material App
2. Set a stateful widget as the home with scaffold and fab.
3. Set an icon or a text as the fab's child.
4. Show or hide the fab according to the state.

Example:

```dart
class FMEApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FME App',
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  bool _showFab = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: MaterialButton(
          child: Text("Hit me!"),
          onPressed: () {
            setState(() {
              _showFab = !_showFab;
            });
          },
        ),
      ),
      floatingActionButton: _showFab
          ? FloatingActionButton(child: Text('X'), onPressed: () {})
          : null,
    );
  }
}
```
Result after hitting the button:
![Screen Shot 2019-03-13 at 13 42 28](https://user-images.githubusercontent.com/7900616/54279674-f71fa280-4595-11e9-9283-e69b8cb78d1f.png)

=> The previous screenshot is taken from an actual device [STV100 4 • 1163084731 • android-arm64 • Android 6.0.1 (API 23)]. Same result with all the build modes.
I tried on iOS simulator and I don't see the issue.
Everything works fine with SDK version 1.2.1.

**Comment by jason-simmons** [comment]
This started with a Skia change: https://github.com/google/skia/commit/c72594a1cf39eaf47a76fa8d95ef1c990d286368

Interestingly, the FAB renders correctly when this change affecting PhysicalModels is applied to the framework: https://github.com/flutter/flutter/commit/58fb183298643bb0c57acd0b50b2480e9d1d5779

However, we may need to alter or revert the PhysicalModel patch.  I'd like to investigate why the Skia change had this effect.

**Comment by parsodyl** [comment]
Well, I am not an expert, but it looks clear that the issue is related to font rendering.
It is also independent of the fab widget because this one elsewhere works fine, and I can see the same problem if a substitute the fab with a simple button or just a container.
So, in this particular case, I suppose the issue occurs when flutter rebuilds  the_FloatingActionButtonTransition widget (inside the Scaffold) or something else on top of it.

**Comment by chinmaygarde** [comment]
This has been fixed on ToT. We are waiting on a comment from the Skia folks regarding the underlying issue.

**Comment by parsodyl** [comment]
> This has been fixed on ToT. We are waiting on a comment from the Skia folks regarding the underlying issue.

Sorry @chinmaygarde, what does ToT mean?

**Comment by chinmaygarde** [comment]
Tip of tree. My bad. Should have been clearer.
