### ISSUE TITLE
[webview_flutter] Webview should have transparent background

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#29300]
Showing a web view inside an iOS popup looks weird because popup is semi transparent and web view background is white opaque. 

By default the plugin should have a transparent background. 

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale fr-FR)
    • Flutter version 1.2.1 at /Users/jaumard/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

• No issues found!

```

**Comment by IchordeDionysos** [comment]
Is there a workaround to this issue?

**Comment by jaumard** [comment]
No workaround @IchordeDionysos :(

**Comment by IonelLupu** [comment]
@IchordeDionysos can you make the same pull-request on [flutter/plugins](https://github.com/flutter/plugins), please ?

**Comment by insinfo** [comment]
Is there a workaround for this issue?
To get a transparent background without your changes?

**Comment by IonelLupu** [comment]
We needed this so badly that we forked the webview package and change the Java code to show a transparent background

**Comment by jaumard** [comment]
@IonelLupu can you tell me what did you change and where please ? I've made a fork and did it for the iOS side but wasn't able to make it work for android :)

**Comment by IonelLupu** [comment]
@jaumard Unfortunately, I don't have access to the project anymore but as far as I remember I forked this project [packages/webview_flutter](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) and added the below code somewhere on [this line](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java#L52):
```java
webview.setBackgroundColor(0);
```

**Comment by jaumard** [comment]
Ok I think that's what I tried but it didn't work, I'll give it another try then :) thanks @IonelLupu

**Comment by entronad** [comment]
We have a flutter charting library based on webview_flutter: https://github.com/entronad/flutter_echarts ,
We really need this feature(transparent background) very much.
Transparent background is very important when using html contents as "inline" widgets, please do consider this request.

**Comment by takuro-kira** [comment]
If around webview color white.
In iOS sometimes flickering occurs due to light / dark mode display settings,
in Android always black background cause flickering.
During 'load content', 'flick scroll in', etc.
I expect these to be resolved in connection with this issue.

**Comment by juanpujol** [comment]
It will be nice if at least the background adapted to the light / dark settings of the device if setting a custom color is not possible.

**Comment by yangjm** [comment]
WebView doesn't support transparent background color, but I managed to set the background color to a non-transparent color that matches the webpage to be loaded:

`
class WebViewWithBgColor extends StatefulWidget {
  final Color bgColor;
  final String url;

  WebViewWithBgColor(this.bgColor, this.url);

  @override
  _WebViewWithBgColorState createState() => _WebViewWithBgColorState();
}

class _WebViewWithBgColorState extends State<WebViewWithBgColor> {
  bool showWebView = false;
  bool loading = true;
  WebViewController controller;

  String get colorStr {
    var color = widget.bgColor;
    return '#${color.red.toRadixString(16).padLeft(2, '0')}${color.green.toRadixString(16).padLeft(2, '0')}${color.blue.toRadixString(16).padLeft(2, '0')}';
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        SizedBox(
          height: showWebView ? double.infinity : 0,
          child: WebView(
            initialUrl: 'about:blank',
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController controller) {
              this.controller = controller;
              controller.loadUrl(Uri.dataFromString(
                      '<html><body style="background-color: $colorStr"></body></html>',
                      mimeType: 'text/html',
                      encoding: Encoding.getByName('utf-8'))
                  .toString());
            },
            onPageFinished: (String value) {
              if (value.startsWith('data:')) {
                setState(() {
                  showWebView = true;
                });

                controller.loadUrl(widget.url);
              } else if (value.startsWith('http')) {
                setState(() {
                  loading = false;
                });
              }
            },
          ),
        ),
        loading
            ? Container(
                alignment: FractionalOffset.center,
                child: CircularProgressIndicator(),
              )
            : Container(
                color: Colors.transparent,
              )
      ],
    );
  }
}
`

The idea is:
1) Set the height of the WebView to zero so it's invisible in the beginning
2) Use inline HTML with expected background color to render the WebView
3) When step 2 is done, change the size of WebView to full height, now the WebView is visible with the expected background color
4) Start loading the URL

**Comment by crizant** [comment]
Since the original author didn't fix it for months, I decided to create another PR: #2895

**Comment by e-adrien** [comment]
Hi, does anyone know when this PR will land ?

**Comment by yangjm** [comment]
This works for me:

`
class WebViewWithBgColor extends StatefulWidget {
  final Color bgColor;
  final String url;
  final Function(WebViewController) onWebViewCreated;

  WebViewWithBgColor(this.bgColor, this.url, {this.onWebViewCreated});

  @override
  _WebViewWithBgColorState createState() => _WebViewWithBgColorState();
}

class _WebViewWithBgColorState extends State<WebViewWithBgColor> {
  WebViewController controller;
  bool show = false;
  WebView webView;

  String get colorStr {
    var color = widget.bgColor;
    return '#${color.red.toRadixString(16).padLeft(2, '0')}${color.green.toRadixString(16).padLeft(2, '0')}${color.blue.toRadixString(16).padLeft(2, '0')}';
  }

  @override
  void initState() {
    super.initState();

    webView = WebView(
      initialUrl: Uri.dataFromString(
              '<html><body style="background-color: $colorStr"></body></html>',
              mimeType: 'text/html',
              encoding: Encoding.getByName('utf-8'))
          .toString(),
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController controller) {
        this.controller = controller;

        if (widget.onWebViewCreated != null)
          widget.onWebViewCreated(controller);
      },
      onPageFinished: (String value) {
        if (value.startsWith("data:")) {
          setState(() {
            show = true;
          });

          if (widget.url != null)
            WidgetsBinding.instance
                .addPostFrameCallback((_) => controller.loadUrl(widget.url));
        }
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Opacity(opacity: show ? 1 : 0.001, child: webView);
  }
}
`

**Comment by softkot** [comment]
Instead of Opacity i would recoomend to use IndexedStack container and switch an index of active widget.

**Comment by salehahmedZ** [comment]
So this still not fixed?

**Comment by volser** [comment]
omg, so easy fix and still is not fixed :-(

**Comment by pzc666** [comment]
So this still not fixed?

**Comment by long1eu** [comment]
I've created a patch if anyone want to create a pr.

```diff
Index: packages/webview_flutter/webview_flutter/CHANGELOG.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/CHANGELOG.md b/packages/webview_flutter/webview_flutter/CHANGELOG.md
--- a/packages/webview_flutter/webview_flutter/CHANGELOG.md	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/CHANGELOG.md	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -1,6 +1,7 @@
-## NEXT
+## 2.0.13
 
 * Updated Android lint settings.
+* add opacity param
 
 ## 2.0.12
 
Index: packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java b/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java
--- a/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -93,10 +93,11 @@
     DisplayManager displayManager =
         (DisplayManager) context.getSystemService(Context.DISPLAY_SERVICE);
     displayListenerProxy.onPreWebViewInitialization(displayManager);
+    boolean opaque = (boolean) params.get("opaque");
 
     webView =
         createWebView(
-            new WebViewBuilder(context, containerView), params, new FlutterWebChromeClient());
+            new WebViewBuilder(context, containerView, opaque), params, new FlutterWebChromeClient());
 
     displayListenerProxy.onPostWebViewInitialization(displayManager);
 
Index: packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java b/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java
--- a/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/android/src/main/java/io/flutter/plugins/webviewflutter/WebViewBuilder.java	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -38,6 +38,7 @@
 
   private final Context context;
   private final View containerView;
+  private final boolean opaque;
 
   private boolean enableDomStorage;
   private boolean javaScriptCanOpenWindowsAutomatically;
@@ -54,9 +55,10 @@
    *     {@code false}. Used to create an InputConnection on the WebView's dedicated input, or IME,
    *     thread (see also {@link InputAwareWebView})
    */
-  WebViewBuilder(@NonNull final Context context, View containerView) {
+  WebViewBuilder(@NonNull final Context context, View containerView, boolean opaque) {
     this.context = context;
     this.containerView = containerView;
+    this.opaque = opaque;
   }
 
   /**
@@ -129,6 +131,9 @@
    */
   public WebView build() {
     WebView webView = WebViewFactory.create(context, usesHybridComposition, containerView);
+    if (!opaque) {
+      webView.setBackgroundColor(0x00000000);
+    }
 
     WebSettings webSettings = webView.getSettings();
     webSettings.setDomStorageEnabled(enableDomStorage);
Index: packages/webview_flutter/webview_flutter/example/lib/main.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/example/lib/main.dart b/packages/webview_flutter/webview_flutter/example/lib/main.dart
--- a/packages/webview_flutter/webview_flutter/example/lib/main.dart	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/example/lib/main.dart	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -55,8 +55,10 @@
       ),
       // We're using a Builder here so we have a context that is below the Scaffold
       // to allow calling Scaffold.of(context) so we can show a snackbar.
+      backgroundColor: Colors.red,
       body: Builder(builder: (BuildContext context) {
         return WebView(
+          opaque: false,
           initialUrl: 'https://flutter.dev',
           javascriptMode: JavascriptMode.unrestricted,
           onWebViewCreated: (WebViewController webViewController) {
Index: packages/webview_flutter/webview_flutter/ios/Classes/FlutterWebView.m
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/ios/Classes/FlutterWebView.m b/packages/webview_flutter/webview_flutter/ios/Classes/FlutterWebView.m
--- a/packages/webview_flutter/webview_flutter/ios/Classes/FlutterWebView.m	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/ios/Classes/FlutterWebView.m	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -95,6 +95,11 @@
                         inConfiguration:configuration];
 
     _webView = [[FLTWKWebView alloc] initWithFrame:frame configuration:configuration];
+    if (![args[@"opaque"] boolValue]) {
+      _webView.opaque = NO;
+      _webView.backgroundColor = UIColor.clearColor;
+      _webView.scrollView.backgroundColor = UIColor.clearColor;
+    }
     _navigationDelegate = [[FLTWKNavigationDelegate alloc] initWithChannel:_channel];
     _webView.UIDelegate = self;
     _webView.navigationDelegate = _navigationDelegate;
Index: packages/webview_flutter/webview_flutter/lib/platform_interface.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/lib/platform_interface.dart b/packages/webview_flutter/webview_flutter/lib/platform_interface.dart
--- a/packages/webview_flutter/webview_flutter/lib/platform_interface.dart	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/lib/platform_interface.dart	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -455,6 +455,7 @@
     this.userAgent,
     this.autoMediaPlaybackPolicy =
         AutoMediaPlaybackPolicy.require_user_action_for_all_media_types,
+    this.opaque = true,
   }) : assert(autoMediaPlaybackPolicy != null);
 
   /// The initialUrl to load in the webview.
@@ -488,6 +489,9 @@
   /// Which restrictions apply on automatic media playback.
   final AutoMediaPlaybackPolicy autoMediaPlaybackPolicy;
 
+  /// If set to `false`, the webview background will be transparent.
+  final bool opaque;
+
   @override
   String toString() {
     return '$runtimeType(initialUrl: $initialUrl, settings: $webSettings, javascriptChannelNames: $javascriptChannelNames, UserAgent: $userAgent)';
Index: packages/webview_flutter/webview_flutter/lib/src/webview_method_channel.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/lib/src/webview_method_channel.dart b/packages/webview_flutter/webview_flutter/lib/src/webview_method_channel.dart
--- a/packages/webview_flutter/webview_flutter/lib/src/webview_method_channel.dart	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/lib/src/webview_method_channel.dart	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -210,6 +210,7 @@
       'javascriptChannelNames': creationParams.javascriptChannelNames.toList(),
       'userAgent': creationParams.userAgent,
       'autoMediaPlaybackPolicy': creationParams.autoMediaPlaybackPolicy.index,
+      'opaque': creationParams.opaque,
       'usesHybridComposition': usesHybridComposition,
     };
   }
Index: packages/webview_flutter/webview_flutter/lib/webview_flutter.dart
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/lib/webview_flutter.dart b/packages/webview_flutter/webview_flutter/lib/webview_flutter.dart
--- a/packages/webview_flutter/webview_flutter/lib/webview_flutter.dart	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/lib/webview_flutter.dart	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -230,6 +230,7 @@
     this.userAgent,
     this.initialMediaPlaybackPolicy =
         AutoMediaPlaybackPolicy.require_user_action_for_all_media_types,
+    this.opaque = true,
     this.allowsInlineMediaPlayback = false,
   })  : assert(javascriptMode != null),
         assert(initialMediaPlaybackPolicy != null),
@@ -414,6 +415,9 @@
   /// The default policy is [AutoMediaPlaybackPolicy.require_user_action_for_all_media_types].
   final AutoMediaPlaybackPolicy initialMediaPlaybackPolicy;
 
+  /// If set to `false`, the webview background will be transparent.
+  final bool opaque;
+
   @override
   State<StatefulWidget> createState() => _WebViewState();
 }
@@ -478,6 +482,7 @@
     javascriptChannelNames: _extractChannelNames(widget.javascriptChannels),
     userAgent: widget.userAgent,
     autoMediaPlaybackPolicy: widget.initialMediaPlaybackPolicy,
+    opaque: widget.opaque,
   );
 }
 
Index: packages/webview_flutter/webview_flutter/pubspec.yaml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/webview_flutter/webview_flutter/pubspec.yaml b/packages/webview_flutter/webview_flutter/pubspec.yaml
--- a/packages/webview_flutter/webview_flutter/pubspec.yaml	(revision 200b66f77f5b9cadb5c9445e51a60fbaaf0da4ad)
+++ b/packages/webview_flutter/webview_flutter/pubspec.yaml	(revision e8cfbbabae7c5c4b7fd6b9a1176a097457b0731c)
@@ -2,7 +2,7 @@
 description: A Flutter plugin that provides a WebView widget on Android and iOS.
 repository: https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
 issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+webview%22
-version: 2.0.12
+version: 2.0.13
 
 environment:
   sdk: ">=2.12.0 <3.0.0"
```

**Comment by aleripe** [comment]
@long1eu I implemented your PR locally but I still see a white background flickerling while loading a black page... is it possible?

**Comment by long1eu** [comment]
Might be, for my usecase work well

**Comment by VictorLekweuwa** [comment]
> bool show = false;

This didn't work. It loaded the background color of choice briefly then overwrote it with white background right after.

**Comment by VictorLekweuwa** [comment]
> class WebViewWithBgColor extends StatefulWidget {
>   final Color bgColor;
>   final String url;
>   final Function(WebViewController) onWebViewCreated;
> 
>   WebViewWithBgColor(this.bgColor, this.url, {this.onWebViewCreated});
> 
>   @override
>   _WebViewWithBgColorState createState() => _WebViewWithBgColorState();
> }
> 
> class _WebViewWithBgColorState extends State<WebViewWithBgColor> {
>   WebViewController controller;
>   bool show = false;
>   WebView webView;
> 
>   String get colorStr {
>     var color = widget.bgColor;
>     return '#${color.red.toRadixString(16).padLeft(2, '0')}${color.green.toRadixString(16).padLeft(2, '0')}${color.blue.toRadixString(16).padLeft(2, '0')}';
>   }
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     webView = WebView(
>       initialUrl: Uri.dataFromString(
>               '<html><body style="background-color: $colorStr"></body></html>',
>               mimeType: 'text/html',
>               encoding: Encoding.getByName('utf-8'))
>           .toString(),
>       javascriptMode: JavascriptMode.unrestricted,
>       onWebViewCreated: (WebViewController controller) {
>         this.controller = controller;
> 
>         if (widget.onWebViewCreated != null)
>           widget.onWebViewCreated(controller);
>       },
>       onPageFinished: (String value) {
>         if (value.startsWith("data:")) {
>           setState(() {
>             show = true;
>           });
> 
>           if (widget.url != null)
>             WidgetsBinding.instance
>                 .addPostFrameCallback((_) => controller.loadUrl(widget.url));
>         }
>       },
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Opacity(opacity: show ? 1 : 0.001, child: webView);
>   }
> }

This didn't work. It loaded the background color of choice briefly then overwrote it with white background right after.
