### ISSUE TITLE
Hot reload stopped working with most recent update to VS Code

### ISSUE THREAD

**Issue by brian-dunn** [flutter/flutter#29306]
Starting with the most recent update to the Flutter/Dart plugin for VS Code (released I think in March 2019), hot reload completely stopped working. The only way to test my app is to complete stop and restart debugging which requires the app to be rebuilt. The problem occurs on all projects. If I create a new project, I see the problem. I also downloaded and reinstalled a fresh new copy of the VS Code dart/flutter plugins and got the same problem.

Does anyone else have this problem? It seems like a pretty fundamental bug.

Flutter doctor reports everything ok.

**Comment by DevonteDC** [comment]
Same Issue, everything was reloading fine before I decided to upgrade everything (flutter 1.2, dart, VS Code). But it definitely seems like a VS Code plugin issue as even manually clicking the command 'Flutter: hot reload' from the command drop-down is unresponsive.

Flutter 1.3.9
Dart 2
VS Code Flutter Plugin 2.24.0

**Comment by rubensdemelo** [comment]
Look this: https://github.com/Dart-Code/Dart-Code/issues/1518

And comment by @DanTup : https://github.com/Dart-Code/Dart-Code/issues/1518#issuecomment-470983039

**Comment by DanTup** [comment]
Unfortunately this is a regression in VS Code (not the plugins) and there is no workaround. The VS Code team are preparing a recovery release with a fix, but in the meantime you should downgrade to VS Code 1.31 or use the Insiders builds which already have the fix.

**Comment by zeh** [comment]
For the record, everything's working fine again on VSC 1.32.2.

**Comment by DevonteDC** [comment]
> For the record, everything's working fine again on VSC 1.32.2.

Confirmed working with 1.32.2 update. Thanks!

**Comment by brian-dunn** [comment]
It looks like version 1.32.3 regressed and it is no longer working. I reported this bug to Google but received no response or status updates.

**Comment by DanTup** [comment]
@brian-dunn Do you mean Microsoft? VS Code is not a Google project.

Could you open a new issue at https://github.com/Dart-Code/Dart-Code with details of what you're seeing? I can't run an app from this machine to test hot reload, but it's definitely detecting the debug sessions correctly as launching Dev Tools works.

If you open issue with details of what's not working (and ideally, a log file collected with the **Dart: Capture Logs** command) I'll take a look when I can get to another machine.
