### ISSUE TITLE
Git error. Command: git fetch / fatal: not a git repository

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#29310]
Hello,

I have a weird problem with my Flutter application.
In my pubspec.yaml, I have a few dependencies linked to some public and private git repos.

For example, this one: 

```
permission:
    git: 'git@github.com:g123k/permission.git'
```

If I git clone this repo, it works just fine.
However with the `flutter packages get`, it will fail:

```
flutter packages get
Git error. Command: git fetch                                           
fatal: not a git repository (or any of the parent directories): .git    
pub get failed (69) -- attempting retry 1 in 1 second...                
Git error. Command: git fetch                                           
fatal: not a git repository (or any of the parent directories): .git    
pub get failed (69) -- attempting retry 2 in 2 seconds...
```

Is-there a way to debug this issue?

**Comment by g123k** [comment]
It seems I have finally found the solution.
Delete the `~/.pub-cache` folder and retry the command.

**Comment by MattIn603** [comment]
> It seems I have finally found the solution.
> Delete the `~/.pub-cache` folder and retry the command.

Dude....I have been looking for HOURS trying to fix a problem that all of sudden started today. This is the only things that fixed it.  Thanks!

**Comment by zsirfs** [comment]
@g123k The `.pub-cache` can't impact the diffenerce flutter project ?

**Comment by g123k** [comment]
This folder is, as its name suggests, the cache used by pub/flutter. So it will impact all your projects.

**Comment by yxwandroid** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/9635493/59565238-4557ac80-9083-11e9-935b-71c855871092.png)

my   flutter  doctor

![image](https://user-images.githubusercontent.com/9635493/59565250-6f10d380-9083-11e9-8458-b34eec2ea894.png)

**Comment by g123k** [comment]
@yxwandroid Have you tried to remove your `.pub-cache` folder?

**Comment by bradypodest** [comment]
I deleted this ： C:\Users\Karl\AppData\Roaming\Pub\Cache，    How did it not work?
