### ISSUE TITLE
TextEditingController docs should remember user to call dispose()

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#29324]
The docs don't say that we should call `dispose()` on the `TextEditingController`. I just found out we have to call it, by reading some examples.

**Comment by hpoul** [comment]
maybe a stupid question, but i was just looking at the `TextFormField` about how it handles the default controller when none is provided and i couldn't find where it's calling `dispose()`? https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_form_field.dart#L206 Is there a reason it doesn't do that?

**Comment by feinstein** [comment]
@hpoul I am not sure, please open your question as a new Issue and please post the link here.

(Maybe if a controller is created inside a `TextFormField` it doesn't have to the disposed? I am not sure either.)
