### ISSUE TITLE
Bugs: Path Changes Outcome Drastically

### ISSUE THREAD

**Issue by DeRealMorgan** [flutter/flutter#29326]
I am using a `CustomPainter` to let the user put his sign under some docs. 

If you draw small `Paths `sometimes the `Paths `change their appereance drastically after a few seconds. 
- This means that the Path gets a different shape, segments are rotated or shortened. 
- There are some artifacts in the shape of very small lines (1px) sometimes.
(I assume that happens at the moment the path is being "optimized").

I simply capture the `Points` in a `Path` object and draw them by calling 
`canvas.drawPath(path, pencil);`

The necessary code:

CustomPainter
```
@override
  void paint(Canvas canvas, Size size) {
      canvas.drawPath(path, pencil);
    });
  }
```

Where I add and capture the `Points`:
```
GestureDetector(
            onPanStart: (DragStartDetails dragStart) {
              RenderBox box = context.findRenderObject();
              Offset pos = box.globalToLocal(dragStart.globalPosition);
              setState(() {
                path.moveTo(pos.dx, pos.dy);
              });
            },
            onPanUpdate: (DragUpdateDetails dragUpdate) {
                setState(() {
                 path.lineTo(pos.dx, pos.dy);
                });
            },
```

I changed to code for simplicity. I am actually creating a new `Path` object each time a `panStart `event happens as each `Path` can have different properties.

After drawing the `Paths `- that is the actual drawing!:
![Expected](https://user-images.githubusercontent.com/34401569/54319383-b8b3d300-45e9-11e9-98b8-d8b59cd5f4c4.png)

After one second (after the optimization?):
![Result](https://user-images.githubusercontent.com/34401569/54319415-c79a8580-45e9-11e9-9f28-1d5f001d68d2.png)

**Comment by DeRealMorgan** [comment]
@dnfield Can you take a look at this as you seem very familiar and experienced with this topic!

**Comment by dnfield** [comment]
Can you share the output of `flutter doctor -v`?  I'm not quite sure what 33.4 refers to, but if this is on a version >= 1.1.9 there's a known issue with the CCPR cache that might be causing this.

**Comment by DeRealMorgan** [comment]
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648],
    locale de-DE)
    • Flutter version 1.2.1 at G:\Flutter\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at G:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = G:\AndroidSDK
    • Java binary at: G:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

**Comment by dnfield** [comment]
Can you see if this reproduces on Flutter v 1.1.8?

**Comment by dnfield** [comment]
And could you open a separate bug for the path.combine issue?  Please tag me in it so we cna discuss further there :)

**Comment by DeRealMorgan** [comment]
I downgraded flutter and I could not reproduce this bug - It probably is the cache issue you were talking about.

And sure I will  separate the bugs.

**Comment by dnfield** [comment]
Thanks for this case - I'm going to close this as a dupliate of #28227 

Just to be clear - your second issue still happens on 1.1.8 right?

**Comment by DeRealMorgan** [comment]
> Just to be clear - your second issue still happens on 1.1.8 right?
