### ISSUE TITLE
`flutter run --verbose` should send `--verbose-logging` to the engine

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#29320]
Without `--verbose-logging`, the engine will hide all INFO level log which is the default level of logging. I think it defeats the purpose of `--verbose` from engine's perspective.

**Comment by liyuqian** [comment]
CC @chinmaygarde @jonahwilliams

**Comment by jonahwilliams** [comment]
That might be a bit overloaded with verbose tool output, should we have a separate debugging option for verbose system logs?

**Comment by chinmaygarde** [comment]
@liyuqian: Does Android pick up the flag from the intent and forward it to the shell? If not, we should wire that up at least. iOS forwards args to the shell so I just add it as an extra command line option in the Xcode scheme and bypass the tools completely for system logs.

**Comment by jonahwilliams** [comment]
> Does Android pick up the flag from the intent and forward it to the shell?

Yes,  https://github.com/flutter/engine/blob/cc27cafb840f6fd57b86a36a3e7ed5461575f10a/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java#L318.

**Comment by jonahwilliams** [comment]
cc @liyuqian I landed the flag change, the tool should pass this to the intent on Android now

**Comment by liyuqian** [comment]
Verified that this has been fixed.
