### ISSUE TITLE
Duplicate GlobalKey when using MaterialApp(builder) on Hot Restart

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#29322]
Suddenly, (only) hot restarting causes this issue.

```dart
runApp(MaterialApp(builder: (_, child) => AnyBuilder(builder: (_) => AnyWidget(child: child)), ...)) // app contains functionality
```

```
Multiple widgets used the same GlobalKey.
The key [GlobalObjectKey<NavigatorState> _WidgetsAppState#bd478] was used by multiple widgets. The
parents of those widgets were:
- AnyBuilder
- AnyWidget
A GlobalKey can only be specified on one widget at a time in the widget tree.
```

In this case I tested `AnyBuilder` with `FutureBuilder` and `ValueListenableBuilder` and `AnyWidget` can even be a `Container`.

This always happens when hot restarting the application and only then. I looked at the Android Studio `Local History` of my project from before this behavior occured and after it occured and the `builder` in the `MaterialApp` has been unchanged. Having said that, there are many other widgets included in the actual code, e.g. `InheritedWidget`'s before `MaterialApp` etc.

It is just really weird that this happens because I am not using any `GlobalKey`'s that could cause this and the exception is just really weird because neither `AnyBuilder` nor `AnyWidget` was ever supplied with any `Key` by me. I tried to change the `builder` in `MaterialApp` in many different ways but this bug (?) remains.

Oh, and since this issue has been around my workflow is `Hot Restart -> Hot Reload` because a hot reload will fix it (otherwise the application is unusable because this `builder` sits at the top of the widget tree).

`Channel master, v1.3.10-pre.27`

**Comment by HansMuller** [comment]
Thanks for the report, will check this out.

**Comment by HansMuller** [comment]
I was unable to reproduce the problem, via hot restart or reload, with this small app based on your report:  https://gist.github.com/HansMuller/df052c4aaa4506d7f110995eff54b246

If you can provide a similar test app that demonstrates the problem we can look into it further.

**Comment by creativecreatorormaybenot** [comment]
So, I finally have a test app that demonstrates it.  
A few things that were required to achieve it: Use a route instead of the `home` parameter. The surrounding `InheritedWidget` and a `ValueListenableBuilder` listening to data inside of the `InheritedWidget`. 
The `InheritedWidget` has to have a specific name, in this case I only found `PlatformBrightness` to cause this issue and the `ValueListenableBuilder` has to return two different widgets in the lifecycle, i.e. the `ValueNotifier` should change and then the builder should return a different widget.
Also I could not find any way to reproduce it without having a call to `SharedPreferences`, I know it is really weird. I tried `await Future.delayed(Duration(milliseconds: 481));` instead of the `SharedPreferences` line because that was the time that `await` took, but that would resolve the issue.
Having said that, you will need to have `shared_preferences` in order to reproduce my Gist: https://gist.github.com/creativecreatorormaybenot/b3653a3dba6517e24f0716825013d1ab

This is really weird to me, but *exactly* that setup produces the issue for me.

Steps:
  1. Open the application on an Android emulator running API 28 (in my case).
  1. Perform a hot restart.

This actually seems like I was kidding but this is how it is for me.

**Comment by creativecreatorormaybenot** [comment]
I am unable to provide a test app that will work reproduce the issue in any workspace, however, it occurs in our workspace and is extremely disruptive. Is there a hint of some kind @HansMuller? 

The behavior is extremely weird. It is currently happening with a `ValueListenableBuilder` -> `Theme` tree in the `MaterialApp` `builder` function. When trying to reproduce the issue in the same Flutter project, it only happens with specific class names of `InheritedWidget`'s that are above the `MaterialApp` in the widget tree, however, changing the class name does strangely not solve the issue when starting the real application.
