### ISSUE TITLE
flutter_tool should never sync full dill to fuchsia device

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29327]
This needs more investigation to determine the cause.  This may have been causing filesystem exceptions on fuchsia that are not surfaced due to https://github.com/dart-lang/sdk/issues/36202. 

For now we should disable any asset syncing and ensure that we never send a full dill file. Going forward, we should have a better understanding of the tmp dir policy on fuchsia

cc @chingjun @MaxBittker

**Comment by zanderso** [comment]
@jonahwilliams was there ever any follow-up on this? @iskakaushik @kf6gpe Some of the memory issues that David Murphy is running into might be alleviated if this issue was not addressed since the full dill file would be stored in /tmp, which is a memfs in the flutter_runner.

**Comment by jonahwilliams** [comment]
Yes, at the time we worked around the issue by increasing the size of the available temp space to several MB, from a previously very low value.

We still sync the full dill at startup during attach for all platforms. I _think_ that it is unnecessary and could be removed.

**Comment by jonahwilliams** [comment]
This might have been fixed during the last vm service refactor. Currently attaching on android does not sync a new dill:

```
Application finished.
PS C:\Users\Jonah\flutter\examples\hello_world> flutter attach
Waiting for a connection from Flutter on Pixel 4...
Waiting for Pixel 4 to report its views...                          20ms
Syncing files to device Pixel 4...                                     \uploading {build/flutter_assets/AssetManifest.json: Instance of 'DevFSStringContent', build/flutter_assets/FontManifest.json: Instance of 'DevFSStringContent', build/flutter_assets/NOTICES: Instance of 'DevFSStringContent'}
   522ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Pixel 4 is available at: http://127.0.0.1:62246/5gqogku6pJI=/
```

**Comment by jonahwilliams** [comment]
I don't have access to a fuchsia device, but this could be verified by adding a print around here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devfs.dart#L493

**Comment by jonahwilliams** [comment]
We should be able to cut down on the memory usage of development mode for applications with a lot of assets by following something like https://github.com/flutter/engine/pull/21436
