### ISSUE TITLE
Crash while running Flutter run in the terminal

### ISSUE THREAD

**Issue by Naw-alhmw** [flutter/flutter#29349]
[flutter_10.log](https://github.com/flutter/flutter/files/2966783/flutter_10.log)
 ### Steps to Reproduce

It all started when I updated my Flutter plugin and changed its channel from `stable `to `dev`. I'm no longer able to run any Flutter program on any kind of emulator nor on a real device. In fact, running `Flutter run` yields to a crash every single time.

### When running Flutter run in the project's terminal, I get this kind of an output
```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                                 /
Oops; flutter has exited unexpectedly.                                                                                                    Sending crash report to Google.
Crash report sent (report ID: 2f37491f98712877)
Initializing gradle...                                                  Crash report written to C:\Users\deviceName\Desktop\project\app\flutter_10.log;
please let us know at https://github.com/flutter/flutter/issues.

```

###  The output of running `flutter doctor -v` 

`[√] Flutter (Channel dev, v1.3.9, on Microsoft Windows [Version 10.0.17134.648], locale en-US)`
`    • Flutter version 1.3.9 at C:\src\flutter`
   ` • Framework revision f91df4abe1 (4 days ago), 2019-03-09 21:19:28 -0500`
 `   • Engine revision 4e54bc93ca`
 `   • Dart version 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)`

`[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)`
    `• Android SDK at C:\Users\deviceName\AppData\Local\Android\Sdk`
    `• Android NDK location not configured (optional; useful for native profiling support)`
  `  • Platform android-28, build-tools 28.0.3`
    `• ANDROID_HOME = C:\Users\deviceName\AppData\Local\Android\Sdk`
    `• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java`
   ` • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)`
`    • All Android licenses accepted.`

`[√] Android Studio (version 3.3)`
`    • Android Studio at C:\Program Files\Android\Android Studio`
`    • Flutter plugin version 31.3.3
` `   • Dart plugin version 182.5124`
`    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)`

`[√] IntelliJ IDEA Community Edition (version 2018.3)`
  `  • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.3`
    •` Flutter plugin version 31.3.4`
 `   • Dart plugin version 183.5153.38`

`[√] VS Code (version 1.32.1)`
`    • VS Code at C:\Users\deviceName\AppData\Local\Programs\Microsoft VS Code`
   ` • Flutter extension version 2.24.0`

`[√] Connected device (1 available)`
`    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)`

`• No issues found!`
`

**Comment by jonahwilliams** [comment]
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "C:\Users\nonna\Desktop\EZYGO\app\android\gradlew.bat" exited abnormally:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
  Command: C:\Users\nonna\Desktop\EZYGO\app\android\gradlew.bat -v
```

**Comment by BondarenkoStas** [comment]
@Naw-alhmw can you try the solution proposed here https://github.com/flutter/flutter/issues/17280#issue-320202856?

**Comment by blasten** [comment]
Do you have a android/gradle/wrapper/gradle-wrapper.jar file?  I remember fixing an issue where this file wasn't being generated in some cases. Please try again and reopen if this is still an issue.
