### ISSUE TITLE
package:flutter/src/painting/image_provider.dart': Failed assertion: line 532 pos 14: 'file != null': is not true.

### ISSUE THREAD

**Issue by hrishikeshd10** [flutter/flutter#29343]
Hi, I am trying to implement Flutter FireBaseMlLVision to detect face coordinates and I am getting this error on capturing the image.
Here is my error stack:
`I/flutter ( 3735): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:928
I/flutter ( 3735): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:840
I/flutter ( 3735): #78     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 3735): #79     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 3735): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 3735): ════════════════════════════════════════════════════════════════════════════════════════════════════
`
and here goes my Page where I have implemeted the logic:
 `import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_ml_vision/firebase_ml_vision.dart';
import 'dart:async';

class FaceDetection extends StatefulWidget {
  @override
  _FaceDetectionState createState() => _FaceDetectionState();
}

class _FaceDetectionState extends State<FaceDetection> {

File _imageFile;
List<Face> _faces;

void _getImageAndDetectFaces() async{
  File pickedImage = await ImagePicker.pickImage(source: ImageSource.camera);
final image = FirebaseVisionImage.fromFile(pickedImage);
final FaceDetector  faceDetector = FirebaseVision.instance.faceDetector(
  FaceDetectorOptions(
    enableLandmarks: true,
    mode:FaceDetectorMode.accurate,
  )
);

final faces = await faceDetector.detectInImage(image);
//_imageFile = pickedImage;

if(mounted){
  setState(() {
  _imageFile = pickedImage;
  _faces = faces;
});
}

}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: (_imageFile!=null)? Container(
        child: PlaceHolder(),
      ):Container(),
      floatingActionButton: FloatingActionButton(
        onPressed:  _getImageAndDetectFaces,
        backgroundColor: Colors.green,
        child: Icon(Icons.add_a_photo),
      )
      
    );
  }
}

class PlaceHolder extends StatelessWidget {
    File image ;
  List<Face> faces;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Flexible(
          
          flex: 2,
          child:Container(
            constraints: BoxConstraints.expand(),
            child: Image.file(
              image,
              fit:BoxFit.cover
            ),
          )
        ),
        Flexible(
          flex: 1,
          child:ListView(
                        children:  faces.map<Widget>((f) => FaceCoordinates(f)).toList(),
          )
        )
      ],
      
    );
  }
}

class FaceCoordinates extends StatelessWidget{
 final Face faces;
 
  FaceCoordinates(this.faces);

  @override
  Widget build(BuildContext context) {
    
final pos = faces.boundingBox;

    return ListTile
    (
      title: Text('(${pos.top}, ${pos.left}, ${pos.bottom}, ${pos.right})'),
    );
  }

}`

Please Help, thank you in advance!

**Comment by hrishikeshd10** [comment]
I am still getting this issue please help.....urgent

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by arkadiuszpalka** [comment]
I've got this problem on iOS 8.0, after select cancel from gallery.

**Comment by sedhha** [comment]
I just switched the body statement and apparently it worked.

`ImageLabelled()!=null?Container():_ImageFile,`

But now I am facing another error which is something like this:

```
E/MethodChannel#plugins.flutter.io/image_picker( 8998): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker( 8998): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithError(ImagePickerDelegate.java:490)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithAlreadyActiveError(ImagePickerDelegate.java:486)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.chooseImageFromGallery(ImagePickerDelegate.java:245)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:56)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/image_picker( 8998): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 8998): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Reply already submitted, null)
E/flutter ( 8998): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 8998): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter ( 8998): <asynchronous suspension>
E/flutter ( 8998): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:50:40)
E/flutter ( 8998): <asynchronous suspension>
E/flutter ( 8998): #3      _FacePageState._getImagesAndDetectLabels (package:carryon/scannerscreen.dart:16:39)
E/flutter ( 8998): <asynchronous suspension>
E/flutter ( 8998): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter ( 8998): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter ( 8998): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 8998): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 8998): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter ( 8998): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 8998): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 8998): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 8998): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8998): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8998): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8998): #15     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 8998): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 8998): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 8998): #18     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 8998): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter ( 8998): 
```
