### ISSUE TITLE
Issue with iOS signin

### ISSUE THREAD

**Issue by crimsonsuv** [flutter/flutter#29347]
In Android, I don't have to log in every time with google but with iOS every time I do google sign in, I need to log in again and enter my email and password. Kindly let me know if this is an issue or I am missing something here.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
