### ISSUE TITLE
Feature Request : Firebase Auth Update Phone method

### ISSUE THREAD

**Issue by jawand** [flutter/flutter#29355]
we want to update phone number for a firebase user  there is a method `updatePhoneNumber()` in native android packages but i still wonder why this method was left out in flutter packages?

[This](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#updatePhoneNumber(com.google.firebase.auth.PhoneAuthCredential)) is android documentation link for the `updatePhoneNumber()`.

**Comment by escamoteur** [comment]
Hi, if you have further questions on this problem, please open a new issue at Firebase's new home at https://github.com/FirebaseExtended/flutterfire
