### ISSUE TITLE
ClipRect doesn't work with Column inside it

### ISSUE THREAD

**Issue by Pavel-Sulimau** [flutter/flutter#29357]
I'm trying to use `ClipRect` with a `Column` inside it, but it doesn't seem to work well together. 

Here is a small demo showing the problem:

```dart
import 'package:flutter/material.dart';

void main() => runApp(ContentOverflowDetectionApp());

class ContentOverflowDetectionApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Overflow demo"),
        ),
        body: ClipRect(
          child: Column(
            children: [
              Container(
                width: 300,
                height: 400,
                color: Colors.green[200],
                child: Text('first widget'),
              ),
              Container(
                width: 450,
                height: 450,
                color: Colors.yellow[200],
                child: Text('overflowed widget'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

<img src="https://user-images.githubusercontent.com/8143332/54362966-01679c80-467b-11e9-953e-7b7a6e4a6a70.png" height="700" />

**What I'd like to achieve** is to have the content clipped. Please note, that I don't need scrolling here. I suppose I could've used a ListView and turn off the scrolling but it doesn't seem logical to me to use the ListView when I know I'll never need scrolling.
It would be also great if I could detect a situation when there is an overflow and show, for example, some text only for this case.

Any suggestion?

**Comment by forresthopkinsa** [comment]
Did you ever figure out a solution to this problem? Running into the same thing.

**Comment by Pavel-Sulimau** [comment]
You can take a look at the answer I received for this question at [stackoverflow](https://stackoverflow.com/questions/55091863/flutter-detect-content-overflow-and-clip-it), it solves the issue in this particular example, but it didn't help me in another similar case. So, I ended up having a ListView with turned off scrolling.

**Comment by forresthopkinsa** [comment]
My [question](https://stackoverflow.com/questions/55884026) ended up getting a great answer.

**Comment by VladyslavBondarenko** [comment]
Closing since solved
