### ISSUE TITLE
video player package doesn't support the armv7 chipset

### ISSUE THREAD

**Issue by unalone** [flutter/flutter#29354]
The error message is:
 === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Non-fat binary /Users/unalone/projects/showme/showme/build/ios/Debug-iphoneos/Runner.app/Frameworks/video_player.framework/video_player is not armv7. Running lipo -info:
    Non-fat file: /Users/unalone/projects/showme/showme/build/ios/Debug-iphoneos/Runner.app/Frameworks/video_player.framework/video_player is architecture: arm64

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
