### ISSUE TITLE
shared_preferences package, MissingPluginException for getAll method

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#29356]
Hello, I am using the shared_preferences package (version  0.5.1+1) to store/retrieve data.
I initialize the lib as the doc says:

`SharedPreferences prefs = await SharedPreferences.getInstance();`

But as soon as the build does that, a MissingPluginException is thrown: 

> MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

My flutter doctor output:

> [✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.2.1 at /home/dserrano/opt/flutter
>     • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /home/dserrano/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /opt/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /opt/android-studio
>     • Flutter plugin version 33.3.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] IntelliJ IDEA Community Edition (version 2018.3)
>     • IntelliJ at /opt/idea
>     • Flutter plugin version 31.3.4
>     • Dart plugin version 183.5153.38
> 
> [✓] VS Code (version 1.32.1)
>     • VS Code at /usr/share/code
>     • Flutter extension version 2.24.0
> 
> [✓] Connected device (1 available)
>     • SM G930F • ad051602392a4a8260 • android-arm64 • Android 7.0 (API 24)
> 
> • No issues found!

Any help? Thanks in advance.

**Comment by JCCP3** [comment]
same problem do you solve this problem ?

**Comment by svprdga** [comment]
No @JJCP3, I didn't tried again but if the issue continues I will implement the preferences system in the native side.

**Comment by svprdga** [comment]
Tried new 0.5.1+2 version and it's working.

**Comment by victor-osf** [comment]
same issue here. Any one know how to solve this?

**Comment by gzlock** [comment]
Sorry about I not good at English.
Same issue:  
`'MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)'`

I solved this issue at my project.
The problem is the SharedPreferences plugin unregistered at the Android native code.
1, Check the GeneratedPluginRegistrant.java file (Automatic generated, path: android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java) had the content like that:
```java
public final class GeneratedPluginRegistrant {
  public static void registerWith(PluginRegistry registry) {
    if (alreadyRegisteredWith(registry)) {
      return;
    }
    // ... other plugins
    SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
  }
  // ... other codes
}
```
If it dose not has, make sure your pubspec.yaml file include the 'shared_preferences' plugin at the 'dependencies' field, and run `flutter pub get` or `flutter pub upgrade`.
2, Check the Android entry file(the first activity has the 'MAIN' and the 'LAUNCHER' properties at the AndroidManifest.xml) had call the GeneratedPluginRegistrant.registerWith method like that:
```java
// java
public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```
Then solved this issue at my project.

**Comment by raydl007** [comment]
> Sorry about I not good at English.
> Same issue:
> `'MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)'`
> 
> The problem is the SharedPreferences plugin unregistered at the Android native code.
> 1, Check the GeneratedPluginRegistrant.java file (Automatic generated, path: android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java) had the content like that:
> 
> ```java
> public final class GeneratedPluginRegistrant {
>   public static void registerWith(PluginRegistry registry) {
>     if (alreadyRegisteredWith(registry)) {
>       return;
>     }
>     // ... other plugins
>     SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
>   }
>   // ... other codes
> }
> ```
> 
> If it dose not has, **don't edit this file directly.**
> Make sure your pubspec.yaml file include the 'shared_preferences' plugin at the 'dependencies' field, and run `flutter pub get` or `flutter pub upgrade`.
> 
> 2, Check the Android entry file(the first activity has the 'MAIN' and the 'LAUNCHER' properties at the AndroidManifest.xml) had call the GeneratedPluginRegistrant.registerWith method like that:
> 
> ```java
> // java
> public class MainActivity extends FlutterActivity {
>   @Override
>   protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     GeneratedPluginRegistrant.registerWith(this);
>   }
> }
> ```
> 
> Then solved this issue in my project.

thank you very much

**Comment by Xgamefactory** [comment]
we got same issue but we did migration as described here 
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

there is no MainActivity.java class anymore.
any solutions ?

**Comment by gzlock** [comment]
> we got same issue but we did migration as described here
> https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
> 
> there is no MainActivity.java class anymore.
> any solutions ?
If dose not has the MainActivity.java file it means you use the kotlin language.
Check this file
```
/android/app/src/main/kotlin/your/package/name/MainActivity.kt
```
Had the content like the following
```kotlin
class MainActivity: FlutterActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)
  }
}
```

**Comment by Xgamefactory** [comment]
there are no Mainactivity java or kotlin file
we have created new project from scratch using latest stable flutter sdk
and there are no MainActivity file either.

**Comment by gzlock** [comment]
> there are no Mainactivity java or kotlin file
> we have created new project from scratch using latest stable flutter sdk
> and there are no MainActivity file either.

Do you run `flutter pub get` or `flutter pub upgrade`?

**Comment by Xgamefactory** [comment]
you kotling file is old it is different on lates stable flutter sdk.
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-TR)
    • Flutter version 1.12.13+hotfix.5 at /Users/fersmart/SDK_all/flutter
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

```

**Comment by Xgamefactory** [comment]
> > there are no Mainactivity java or kotlin file
> > we have created new project from scratch using latest stable flutter sdk
> > and there are no MainActivity file either.
> 
> Do you run `flutter pub get` or `flutter pub upgrade`?

we have edited our answer there is kotlin file but different from yours.

**Comment by Xgamefactory** [comment]
we have removed preferences plugin from pubspec.yaml and issue has gone.
preferences: ^5.0.2 uses older shared_preferences package and conflicts.

**Comment by Xgamefactory** [comment]
we got another error now
```

hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
```

**Comment by mhabashy** [comment]
Solved this by deleting the shared_preference from the build directory and then run `flutter run`
