### ISSUE TITLE
flutter_gallery__transition_perf worst_frame_rasterizer_time_millis regressed about 10%

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#29365]
The metric increases from ~110ms to ~120ms during the following commits:

https://github.com/flutter/flutter/commit/d9096a42263881ad53890bf774328c2c6f101d67
https://github.com/flutter/flutter/commit/854d8bb0d96d218308745f5d97c5677360f71c70
https://github.com/flutter/flutter/commit/47f56712cc0797a455eb4e70f48df267b6f1e450

The dashboard didn't turn red because we forget to rebaseline the metric. It might be worth investigating whether the regression is expected or not.

**Comment by liyuqian** [comment]
CC @HansMuller @goderbauer : is the regression expected for your commits?

**Comment by HansMuller** [comment]
I wouldn't have expected either of these Material PRs to cause significant (any) performance regressions.

MaterialButton shape should override ButtonTheme shape #29189
Ensure that animated pairs of Tabs TextStyles have matching inherited values #29175

**Comment by goderbauer** [comment]
I didn't expect it, but it is possible that #29069 is to blame if the benchmark includes a lot of transition with heros. For every hero we are doing an extra `Navigator.of` lookup and comparison - and in the case of nested navigators we are doing an extra `ModalRoute.of` lookup and some more comparisons.

**Comment by liyuqian** [comment]
Never mind, I did a bisection locally and found that the regression is actually caused by 8915cad44, which is 2 commits after 47f5671. The regression from 8915cad44 is expected as a tradeoff between time and space.

So this is another confusion caused by https://github.com/flutter/flutter/issues/27574.

Close this issue as the regression is expected.
