### ISSUE TITLE
Edit recipe doc seems to be outdated

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#29362]
I tried to trigger a build to test a recipe change. But it seems that the instruction item 3 of https://github.com/flutter/flutter/blob/master/dev/bots/README.md#editing-a-recipe is no longer working in our new LUCI build system?

**Comment by liyuqian** [comment]
@dnfield : how did you test a recipe change in our new LUCI build?

**Comment by dnfield** [comment]
Ahhh the correct command is now 
```
led get-builder 'luci.flutter.prod:BUILDER_NAME' | led edit -p 'revision="GIT_HASH"' | led edit-recipe-bundle | led launch
```

I'll update the doc
