### ISSUE TITLE
Some iOS widgets rendering incorrectly in stable with no hotfix available

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#29360]
#28484 Widget rendering strange since Flutter update  can cause rendering issues when loading certain images on physical iOS devices. This issue appears in stable, and thanks to other problems, we have no way to hotfix stable. A workaround is to pick up a beta channel release. If this does not work for you, please comment here. If enough people are blocked by this, we'll consider rolling another stable more quickly than scheduled.

**Comment by xster** [comment]
Doesn't seem like a cupertino related issue

**Comment by Hixie** [comment]
What is this bug requesting?

**Comment by kf6gpe** [comment]
It’s a tracking bug we link to in the release notes document for people affected by this problem to weigh in on whether they need us to consider rollining another stable release ahead of schedule. @csells and I are monitoring it for feedback.

**Comment by Hixie** [comment]
Fixed in v1.5.4.
