### ISSUE TITLE
settings.gradle.kts

### ISSUE THREAD

**Issue by timrijckaert** [flutter/flutter#29366]
Currently I'm looking into including a Flutter module into an existing Android Application.
Therefore I decided to take a look at [add Flutter to an existing apps guide](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#make-the-host-app-depend-on-the-flutter-module) here.

The guide assumes a Gradle settings file.
While we have converted to Kotlin settings file.

```
include ':app'                                          // assumed existing content
setBinding(new Binding([gradle: this]))                 // new
evaluate(new File(                                      // new
        settingsDir.parentFile,                         // new
        'my_flutter/.android/include_flutter.groovy'    // new
))  
```                                                                   

Does anyone know the equivalent Kotlin configuration?

Thanks in advance.

**Comment by tarek360** [comment]
I'm also looking for the kts equivalent but try this as a temporary solution, sometimes works.
```gradle
include(":flutter")
project(":flutter").projectDir = File(settingsDir, "my_flutter/.android/Flutter")
```
make sure your path is correct: `File(settingsDir, "my_flutter/.android/Flutter")`

**Comment by tarek360** [comment]
As a temporary solution, you can add your groovy code in a separated groovy file **`flutter_settings.gradle`**
```gradle
setBinding(new Binding([gradle: this, mainModuleName: 'app']))
evaluate(new File(                                                      
        settingsDir.parentFile,
        'my_flutter/.android/include_flutter.groovy'
))
```

then include it in **`settings.gradle.kts`**
```gradle
apply { from("flutter_settings.gradle") }
```

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?


Thanks a lot

**Comment by wuseal** [comment]
@escamoteur  Then, what's the equivalent Kotlin configuration in `settings.gradle.kts`?

**Comment by escamoteur** [comment]
@wuseal please open a new ticket and describe your problem. Thanks
