### ISSUE TITLE
Provide top, right, left and bottom constructors to Positioned

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#29372]
I think it would be useful to have `top`, `right`, `left` and `bottom` constructors to `Positoned`, they will fill the `child` to take that particular portion of the screen, for example, `Positioned.top()` would be the same as `Positioned.fill(bottom: null);`, which will set `top`, `right` and `left` to `0.0`.

This is a simple change, I think I can do that modification myself, I just want to see what you guys think of it before I submit a pull request.

**Comment by rostopira** [comment]
IMHO: If I would see `Positioned.top()` anywhere, I would think about `Positioned(top: 0)` only

**Comment by feinstein** [comment]
Maybe a better name? Suggestions?

**Comment by rostopira** [comment]
Maybe `Positioned.fillTop()`
But with this logic you can write a lot more custom constructors like that, `Positioned.topCenter()` for example

**Comment by feinstein** [comment]
I was just about to suggest `fillTop` 😂

Yes, other constructors would be nice too, what about this list:

- `fillTop`
- `fillBottom`
- `fillLeft`
- `fillRight`
- `topLeft`
- `topRight`
- `bottomLeft`
- `bottomRight`
- `centerTop`
- `centerBottom`
- `centerLeft`
- `centerRight`

Am I forgetting something? Will this polute the `Positioned` API?

**Comment by rostopira** [comment]
Actually, I'm developing my new project with Flutter for a few months, and I'm sometime amused with all of that
I was completely fine with `Positioned(top:0,left:0,right:0,bottom:0)` and then find out that `Positioned.fill()` exists
I was completely fine with `Stack(children:[Container(align:Alignment.center) more containers here` and then find out, that stack has `alignment` parameter
I was fine with `Container(child:Padding(...` and then find out, that `Container` actually has `padding` param

So yet again, will this make code more readable? Will this change allow developers to write code faster? Maybe?

I would say, that all of you suggestion would make sense, except those `fillSomePart`

But again, I'm just some noob here and this is totally IMHO

**Comment by feinstein** [comment]
Try using a `SizedBox` instead of `Padding` if you just want to give a space between `Widgets`.

@HansMuller any thoughts on this? Go or no-go?

**Comment by HansMuller** [comment]
This seems like a nice idea, although it's a lot of API for cases that aren't that common. To make it beneficial for readability the new constructors would have to come up often enough for developers to internalize what they mean. 

Personally I'm leery of the perils of handy dandy. More API, more tests, more documentation, and some opportunity for developers to misunderstand the meaning of a handy API extension can really the diminish the extension's value.

Maybe I'm mistaken about how often these constructors might be used. Will take another look next week, when it's not Friday afternoon :-).

**Comment by Hixie** [comment]
I think I agree with Hans, the benefits seem small and the potential cost (bigger API surface, more tests, more documentation) seem high. Also it's a bit weird like @rostopira says that `.top()` would only set `bottom`. :-)

I'm going to close this for now but thanks for the proposal!

**Comment by feinstein** [comment]
Thank you for taking the time, your feedback was very insightful and I agree this shouldn't move forward.
