### ISSUE TITLE
material/text_field_focus_test.dart is incredibly flakey on mac bot

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29384]
We'll need to investigate what changed to start triggering the intrinsic width bugs.

**Comment by dnfield** [comment]
LGTM

Should we just disable this on all platforms until we can figure out why it's flaky?

**Comment by dnfield** [comment]
Just a little more context - this test has been flaky for a long time on Windows.

- Recently (not sure when), it's become more flaky on Linux.
- Today, it's been very flaky on macOS - but it's not reproducing for me locally on macOS, only on the LUCI builder.
- Some people seem to have better luck reproducing this (claims as high as 1:2 or 1:4 runs).
- It doesn't seem to ever be flaky in google3 (and I've run 10s of thousands of tests in google3 without failure for this specific test).
- People who report it's more flaky have a harder time reproducing it if there's any code added to the test (even, e.g. `if (false) {}`).
- When it fails, it fails on the testing intrinsic width for `double.infinity`, in which min returns greater than max.
- Dialogs specify a hard coded constant that matches one of the values reported in the failure (?)

**Comment by dnfield** [comment]
Right now my strongest suspicion is it is related to however we're instrumenting the test in flutter_tools vs how we do it in google3.

**Comment by jonahwilliams** [comment]
This was fixed by moving the test to the top of the file

**Comment by gspencergoog** [comment]
@jonahwilliams should [this test](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/text_field_focus_test.dart#L133) also have been re-enabled? It's tagged with the URL to this issue.
