### ISSUE TITLE
Phone auth bug in Android

### ISSUE THREAD

**Issue by anand-a6** [flutter/flutter#29392]
Recently we made our app public and we are using only firebase phone auth to log in, now we are getting reports from Android users that they are getting "Sign in failed" toast which we are displaying only when

`final FirebaseUser user = await FirebaseAuth.instance.signInWithCredential(credential);`

this throws an error

but the strangest thing is when they reopen the app, where am checking for firebase instance at startup they are successfully logged in

it's hard to recreate this issue because it's happening truly randomly.

`try {
      final AuthCredential credential = PhoneAuthProvider.getCredential(
        verificationId: _verificationId,
        smsCode: otp,
      );
      final FirebaseUser user =
          await FirebaseAuth.instance.signInWithCredential(credential);
      if (user != null) {
        createSnackBar(context, "Sign in successful.");
        Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) {
          return MyApp();
        }));
        return true;
      } else {
        createSnackBar(context, "Sign in failed.");
        return false;
      }
    } catch (e) {
      createSnackBar(context, "Sign in failed");
      return false;
    }`

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.1)
[✓] Connected device (1 available)

**Comment by kalkotekedar** [comment]
I have the same problem but the only thing is it is working in case of auto verification and in case if I enter the OTP manually  validation it fails and gives me below error 

`E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/firebase_auth( 7721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/flutter ( 7721): PlatformException(error, null reference, null)
D/EGL_emulation( 7721): eglMakeCurrent: 0xafd8dd40: ver 3 0 (tinfo 0xa647fec0)`

I am using the **firebase_auth  ^0.7.0**

**Comment by kalkotekedar** [comment]
I have upgraded my flutter project to AndroidX and the firebase **firebase_auth ^0.8.1** and it works fine

**Comment by prabhuk56** [comment]
No it is not i am using firebase_auth: 0.8.4+5. Still same issue

**Comment by escamoteur** [comment]
Hi, if you have further questions on this problem, please open a new issue at Firebase's new home at https://github.com/FirebaseExtended/flutterfire
