### ISSUE TITLE
Material borderRadius parameter not working

### ISSUE THREAD

**Issue by fx1422** [flutter/flutter#29409]
Material( borderRadius: BorderRadius.circular(10.0)) ;
 BorderRadius is not working

**Comment by HansMuller** [comment]
Here's a simple test case that demonstrate BorderRadius.circular() working correctly: https://gist.github.com/HansMuller/2d3f76fa7308f6be9854d4b1e24e9501

If you can provide a version of the test case that fails, we'll be happy to look into it.
