### ISSUE TITLE
Flutter Tools - Could not find a file named "pubspec.yaml" 

### ISSUE THREAD

**Issue by rubensdemelo** [flutter/flutter#29405]
Im following this guide: https://github.com/flutter/flutter/wiki/The-flutter-tool

And when run `../../bin/cache/dart-sdk/bin/pub run test` is got this message .

Is that path correct ?
![flutter-tools](https://user-images.githubusercontent.com/1351177/54405944-f3d00800-46b6-11e9-9d50-5ca1b15391f3.png)

**Comment by rubensdemelo** [comment]
On Mac, it works. Instructions are correct.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
