### ISSUE TITLE
flutter version 1.2 has issue with firebase_admob 0.8.0+3

### ISSUE THREAD

**Issue by IAmHasanHabib** [flutter/flutter#29418]
Using flutter V1.0.0 I can successfully build my flutter app. After upgrading my flutter to v1.2 I can not build my flutter app. Every time I try it gives me an error.

**Comment by jonahwilliams** [comment]
> Every time I try it gives me an error.

You'll need to include some information on what that error is so we can help you. Please also include the output of `flutter doctor -v`.

**Comment by IAmHasanHabib** [comment]
BUILD FAILED in 2m 50s
Running Gradle task 'assembleRelease'...




Running Gradle task 'assembleRelease'... Done                     176.8s (!)
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1

**Comment by IAmHasanHabib** [comment]
[error.txt](https://github.com/flutter/flutter/files/3054760/error.txt)

**Comment by escamoteur** [comment]
Hi, if you have further questions on this problem, please open a new issue at Firebase's new home at https://github.com/FirebaseExtended/flutterfire
