### ISSUE TITLE
How to run shell/Command Line Program/Unix Executable  in my Flutter app？

### ISSUE THREAD

**Issue by hugetiny** [flutter/flutter#29411]
Can I  run a  background Command Line Program（like unix executable）in my Flutter app?

**Comment by hugetiny** [comment]
@zoechi How to run shell/Command Line Program/Unix Executable in my Flutter app？
such as node
![image](https://user-images.githubusercontent.com/19659202/56096552-4271fb80-5f1c-11e9-9fbb-13f6b67fd6b0.png)

**Comment by imshashank** [comment]
Any update on this? I want to run simple commands like "ping".

**Comment by escamoteur** [comment]
I would say its not possible but perhaps @tvolkert corrects me.

**Comment by tvolkert** [comment]
The [`dart:io Process`](https://api.dartlang.org/stable/2.5.0/dart-io/Process-class.html) API runs/works in Flutter apps, but it'll tie your app to platform-specific things like executables on disk.

**Comment by cybrknife** [comment]
any updates on this i need command execution in flutter with the linux app
