### ISSUE TITLE
App crashes in android 9 devices

### ISSUE THREAD

**Issue by prateek-hegde** [flutter/flutter#29428]
Map view crashes in android 9 devices.

**Comment by rostopira** [comment]
Please, provide more information about this issue
LogCat of crash, minimal code to reproduce, exact device and firmware version
I have no issues on OnePlus 5T and Samsung Galaxy S8+

**Comment by kf6gpe** [comment]
@prateek-hegde Were you able to get a logcat of this behavior? Which device did you see this on?
