### ISSUE TITLE
Ubuntu : Unable to locate a development device; 

### ISSUE THREAD

**Issue by OnlyYouMyLove** [flutter/flutter#29425]
I input “adb devices",it is OK!
List of devices attached
b237447	device

But I input "flutter devices",it is not Ok!
No devices detected

So,I change another devices! I input "flutter doctor"! All is OK!

$flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

In this state! I run the flutter app in ths AndroidStudio, but is shows the following error:
`
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
`
I uses the operating system of Ubuntu.

**Comment by jonahwilliams** [comment]
@OnlyYouMyLove is the Android sdk that flutter is using the same as the command line adb you are using? `flutter doctor -v` will show more details here.
