### ISSUE TITLE
Flutter camera plugin error : startVideoRecording crash in iOS

### ISSUE THREAD

**Issue by dsa28s** [flutter/flutter#29421]
Hi. I'm using flutter `camera` official plugin.
But, call method `startVideoRecording`, crashing app.

The video is a record of this issue.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10934461/54420913-9c7d7680-474e-11e9-863d-392d28df49de.gif)

I tested `official camera example app`, but crashed.

**Tested `camera` plugin version:**
**0.4.2 > crash
0.4.1 > crash
0.4.0 ~ - 0.4.0+3 > crash**

**Tested Device:**
iPhone Xs (64GB) : iOS 12.1.4 > No reproduced
iPhone X (64GB) : iOS 12.1.4 > No reproduced
**iPhone 8 (64GB) : iOS 12.1.4 > Crash
iPhone 7 (16GB) : iOS 11.4.1 > Crash**

**Flutter Version:**

```
[✓] Flutter (Channel master, v1.3.11-pre.8, on Mac OS X 10.14.3 18D109, locale en-KR)
    • Flutter version 1.3.11-pre.8 at /Users/dsa28s/flutter
    • Framework revision 6d8f539971 (8 hours ago), 2019-03-14 18:01:11 -0700
    • Engine revision 8b1a299ed5
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)
```

**Crash log:**

```
2019-03-15 17:58:16.733211+0900 Runner[1218:23853] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x104c15da0] get output frames failed, state 8196
2019-03-15 17:58:16.734103+0900 Runner[1218:23853] TIC Read Status [1:0x0]: 1:57
2019-03-15 17:58:16.734131+0900 Runner[1218:23853] TIC Read Status [1:0x0]: 1:57
2019-03-15 17:58:16.958329+0900 Runner[1218:23588] flutter: false
2019-03-15 17:58:29.041894+0900 Runner[1218:23588] flutter: false
2019-03-15 17:58:29.084513+0900 Runner[1218:23588] flutter: false
2019-03-15 17:58:29.578568+0900 Runner[1218:23588] flutter: true
2019-03-15 17:58:30.126456+0900 Runner[1218:23812] [GatekeeperXPC] Connection to assetsd was interrupted or assetsd died

Message from debugger: Terminated due to memory issue
```

**Comment by cheneyjuu** [comment]
I have the same error on my iPhone.
Device Info:
**iPhone 8(64GB): IOS 12.3.1**

**Comment by ShubhraDeshpande** [comment]
Any solution for the same? My app is crashing in the same way even with camera. Device is iPad Air2. How to solve it?

**Comment by VladyslavBondarenko** [comment]
Hi @dsa28s 
is it still an issue when using the last version of camera plugin? (with current stable)

**Comment by spiderion** [comment]
Same problem

**Comment by spiderion** [comment]
Found the solution to my problem. 
I had to add this to the info.plist
<key>NSMicrophoneUsageDescription</key>
<string>Can I use the mic please?</string>

**Comment by iapicca** [comment]
Hi @spiderion 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
