### ISSUE TITLE
FlatButton onPressed have not executed 

### ISSUE THREAD

**Issue by shingohu** [flutter/flutter#29433]
in some cases FlatButton onPressed have not executed 

1.Long Pressed
2. release 

![2ce3a8827bc9e5e5cba2401141aecc8](https://user-images.githubusercontent.com/4944887/54438273-54238000-4771-11e9-8af3-f264c0f5e1ae.jpg)

```
C:\Users\Administrator>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.3.9, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)
```

**Comment by tomalabaster** [comment]
Can you provide your minimum code required to replicate the issue?

**Comment by HansMuller** [comment]
Here's a trivial test case that does not fail: https://gist.github.com/HansMuller/1a5720ce1ff8b9ea1761650c3fd43b4c

If you could provide a version that does fail, we'd be happy to look into this.

**Comment by shingohu** [comment]
@tomalabaster @HansMuller  I can't reproduce this problem, there are some probabilities that this problem will occur。


Code in question
```
FlatButton(
      onPressed: () {
        Navigator.of(context).pushNamed(RouterName.editPassword);
      },
      padding: EdgeInsets.all(0),
      color: Colors.white,
      child: Container(
        padding: EdgeInsets.symmetric(vertical: 15, horizontal: 15),
        child: Row(
          children: <Widget>[
            ClipRRect(
              borderRadius: BorderRadius.all(Radius.circular(5)),
              child: Container(
                height: 60,
                width: 60,
                color: Colors.red,
                child: CachedNetworkImage(
                   imageUrl:                    "https://gss0.bdstatic.com/6LZ1dD3d1sgCo2Kml5_Y_D3/sys/portrait/item/fc47b5c8d2bbb8f6c8cbbbd2bfa7b7c81710?t=1427966310",
               
                  placeholder: (context, str) {
                    return Image.asset(R.headDefalut);
                  },
                ),
              ),
            ),
            SizedBox(
              width: 15,
            ),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                 Text("libai" ),
                  SizedBox(
                    height: 10,
                  ),
                  SimpleText(
                    "账号:  libai",
                    color: Colors.grey,
                  )
                ],
              ),
            ),
            Icon(
              Icons.arrow_forward_ios,
              color: Color(0xffcccccc),
            ),
          ],
        ),
      ),
    )
```

**Comment by TahaTesser** [comment]
Hi @shingohu 

After testing your [code](https://github.com/flutter/flutter/issues/29433#issuecomment-473487745), couldn't reproduce any issue with `FlatButton`
If you're still experiencing this issue, please create a new issue and provide necessary detaiils
Thank you

**Comment by abdelrahmanbonna** [comment]
I have the same Issue here. The button works just fine one the debug mode but when I run it in release mode it just don't do anything!! I tried to change the widget even to GestureDetector or RasiedButton but same Issue nothing happens in the release.

**The Button code:**
` FlatButton(
                  onPressed: messageButton,
                  child: Container(
                    width: 325.0,
                    height: 52.0,
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(26.0),
                      color: const Color(0x80ffffff),
                      boxShadow: [
                        BoxShadow(
                          color: const Color(0x15000000),
                          blurRadius: 6,
                        ),
                      ],
                    ),
                    child: Text(
                      'Show Message',
                      style: TextStyle(
                        fontFamily: 'KaushanScript',
                        fontSize: 20,
                        color: Colors.white,
                        fontWeight: FontWeight.w600,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                ),
`

**The onPressed Function:**
`
                        if (remaining.inDays == 0) {
                          happyBirthday = "Happy Birth day";
                          messageButton = () {
                            Navigator.pushNamed(context, MessageScreen.id);
                          };
                        } else {
                          messageButton = () {
                            showBottomSheet(
                                context: context, builder: getAlert);
                          };
                        }
`

**Comment by TahaTesser** [comment]
@abdelrahmanbonna 
button is working in release mode 


```
tahatesser@MacBook-Pro dev_flutter % flutterd run --release -d SM
Launching lib/main.dart on SM M305F in release mode...
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      43.1s
✓ Built build/app/outputs/flutter-apk/app-release.apk (6.3MB).
Installing build/app/outputs/flutter-apk/app.apk...                 4.3s

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (13843): test
I/flutter (13843): test
I/flutter (13843): test
I/flutter (13843): test
I/flutter (13843): test

```

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
          child: FlatButton(
        onPressed: () {
          print("test");
        },
        child: Container(
          width: 325.0,
          height: 52.0,
          alignment: Alignment.center,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(26.0),
            color: const Color(0x80ffffff),
            boxShadow: [
              BoxShadow(
                color: const Color(0x15000000),
                blurRadius: 6,
              ),
            ],
          ),
          child: Text(
            'Show Message',
            style: TextStyle(
              fontFamily: 'KaushanScript',
              fontSize: 20,
              color: Colors.white,
              fontWeight: FontWeight.w600,
            ),
            textAlign: TextAlign.center,
          ),
        ),
      )),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

**Comment by abdelrahmanbonna** [comment]
It's not working after I unplug my phone or my IOS simulator from the project or I use the APK file and not run it directly from my computer. It's like it misses something when I run it on my phone without connecting it to the project. The strange thing is that onPressed function works fine on other parts of the project.

**Full file code:**
`import 'package:adobe_xd/blend_mask.dart';
import 'package:birthdaya/screens/ContactMe.dart';
import 'package:birthdaya/utilities/constants.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:intl/intl.dart';
import '../utilities/xmV_LEii.dart';
import 'Message.dart';

class Home extends StatefulWidget {
  static String id = "home";

  Home({
    Key key,
  }) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  static int nowYear = DateTime.now().year;
  static int nowMonth = DateTime.now().month;
  static int nowDay = DateTime.now().day;
  static int estm = DateTime(nowYear, 10, 25, 1, 0, 0).month;
  static int estd = DateTime(nowYear, 10, 25, 1, 0, 0).day;

  int estimateTs;
  Function messageButton;

  @override
  void initState() {
    super.initState();
    if (nowMonth > estm || (nowDay > estd && nowMonth == estm)) {
      nowYear = nowYear + 1;
      print(nowYear);
    }
    estimateTs = DateTime(nowYear, 10, 25, 1, 0, 0).millisecondsSinceEpoch;
  }

  Widget getAlert(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height * 0.4,
      width: MediaQuery.of(context).size.width,
      color: Colors.white,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "Message",
              style: kTheme.textTheme.headline2,
              textAlign: TextAlign.center,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Text(
              "\nIt will open on your Birthday.",
              style: kTheme.textTheme.headline3,
              textAlign: TextAlign.center,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(10.0),
            child: FlatButton(
              onPressed: () {
                Navigator.pop(context);
              },
              color: kTheme.primaryColor,
              child: Text(
                "Ok",
                style: kTheme.textTheme.headline2
                    .merge(TextStyle(color: Colors.white)),
              ),
            ),
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    var screenHieght = MediaQuery.of(context).size.height;
    var screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      backgroundColor: const Color(0xff4b0082),
      body: Stack(
        children: <Widget>[
          BlendMask(
            blendMode: BlendMode.lighten,
            opacity: 1,
            child: XmV_LEii(),
          ),
          SafeArea(
            child: Column(
              children: [
                SizedBox(
                  height: screenHieght * 0.009,
                ),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Container(
                      width: 54.0,
                      height: 52.0,
                      child: IconButton(
                          icon: Icon(
                            FontAwesomeIcons.bars,
                            color: kTheme.primaryColor,
                          ),
                          onPressed: () {
                            Navigator.pushNamed(context, ContactMe.id);
                          }),
                      decoration: BoxDecoration(
                        borderRadius:
                            BorderRadius.all(Radius.elliptical(27.0, 26.0)),
                        color: const Color(0xccffffff),
                      ),
                    ),
                    SizedBox(
                      width: screenWidth * 0.07,
                    ),
                    Container(
                      width: screenWidth * 0.7,
                      height: 52.0,
                      child: Text(
                        'User Name',
                        style: TextStyle(
                          fontFamily: 'GreatVibes',
                          fontSize: 32,
                          color: const Color(0xff4b0082),
                          fontWeight: FontWeight.w600,
                        ),
                        textAlign: TextAlign.center,
                      ),
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(26.0),
                        color: const Color(0xccffffff),
                        boxShadow: [
                          BoxShadow(
                            color: const Color(0x21000000),
                            blurRadius: 6,
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                SizedBox(
                  height: screenHieght * 0.25,
                ),
                Container(
                  alignment: Alignment.center,
                  child: StreamBuilder(
                      stream: Stream.periodic(Duration(seconds: 1), (i) => i),
                      builder:
                          (BuildContext context, AsyncSnapshot<int> snapshot) {
                        String happyBirthday = "";
                        DateFormat format = DateFormat("hh:mm:ss");
                        int now = DateTime.now().millisecondsSinceEpoch;
                        Duration remaining =
                            Duration(milliseconds: estimateTs - now);
                        var dateString =
                            '${remaining.inDays} days : ${format.format(DateTime.fromMillisecondsSinceEpoch(remaining.inMilliseconds))} ';

                        if (remaining.inDays == 0) {
                          happyBirthday = "Happy Birth day";
                          messageButton = () {
                            Navigator.pushNamed(context, MessageScreen.id);
                          };
                        } else {
                          messageButton = () {
                            showBottomSheet(
                                context: context, builder: getAlert);
                          };
                        }
                        return Container(
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(26.0),
                            color: const Color(0x80d5d5d5),
                          ),
                          alignment: Alignment.center,
                          child: Text(
                            "${remaining.inDays == 0 ? happyBirthday : "Still\n"}" +
                                dateString,
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontFamily: 'KaushanScript',
                              fontSize: 20,
                              color: Colors.white,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        );
                      }),
                  width: screenWidth * 0.9,
                  height: screenHieght * 0.4,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(26.0),
                    color: const Color(0x80d5d5d5),
                  ),
                ),
                SizedBox(
                  height: screenHieght * 0.11,
                ),
                FlatButton(
                  onPressed: messageButton,
                  child: Container(
                    width: 325.0,
                    height: 52.0,
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(26.0),
                      color: const Color(0x80ffffff),
                      boxShadow: [
                        BoxShadow(
                          color: const Color(0x15000000),
                          blurRadius: 6,
                        ),
                      ],
                    ),
                    child: Text(
                      'Show Message',
                      style: TextStyle(
                        fontFamily: 'KaushanScript',
                        fontSize: 20,
                        color: Colors.white,
                        fontWeight: FontWeight.w600,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(9.0),
                  child: SizedBox(
                    width: 337.0,
                    height: 27.0,
                    child: Text(
                      'Made with Love ',
                      style: TextStyle(
                        fontFamily: 'GreatVibes',
                        fontSize: 23,
                        color: const Color(0xffffffff),
                        fontWeight: FontWeight.w600,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                )
              ],
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by abdelrahmanbonna** [comment]
I figured out where the problem was It was due to this part: 
```
if (remaining.inDays == 0) {
                          happyBirthday = "Happy Birth day";
                          messageButton = () {
                            Navigator.pushNamed(context, MessageScreen.id);
                          };
                        } else {
                          messageButton = () {
                            showBottomSheet(
                                context: context, builder: getAlert);
                          };
                        }
```

I think flutter don't get it when you use multiple initialisations for a function and when I changed this code it started to work fine on both release and debug and even when i disconnect my phone from my computer it works fine.
