### ISSUE TITLE
Android NullPointerException: FlutterView.getAccessibilityNodeProvider

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#29435]
My application crashed on `Android 8.0` with the following exception:

```
java.lang.NullPointerException: 
  at io.flutter.view.FlutterView.getAccessibilityNodeProvider (Unknown Source:2)
```

([full stack trace](https://gist.github.com/creativecreatorormaybenot/4bf9aca26e0ef2c7a6bf941207c0c216))

The Flutter version should be `v1.3.10-pre.2x`.

Sadly, I do not have any further insight. Hence, I would just like to know if this is a known issue and how I could prevent it since it occured multiple times.

**Comment by smiLLe** [comment]
https://github.com/flutter/flutter/issues/29203 might be the same?
