### ISSUE TITLE
Changing mouse buttons is incorrectly reported as PointerMoveEvent

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#29448]
- Environment:
  - Flutter revision c942ed481360d5eef0e8d45b3036c9c7f0d6cb0b
  - Running Gallery on Pixelbook

I added a log statement at the beginning of `PrimaryPointerGestureRecognizer.handleEvent` to print the target event, 
```dart
    print('${event.pointer} ${event.toStringShort()} ${event.buttons}');
```
then perform the following operation using a mouse over any button:
- Press RMB and hold
- Press LMB and hold
- Release RMB
- Release LMB

And this is the log printed:
```
I/flutter ( 5111): 24 PointerDownEvent#adf1a 2
I/flutter ( 5111): 24 PointerMoveEvent#93ff8 3
I/flutter ( 5111): 24 PointerMoveEvent#735c8 1
I/flutter ( 5111): 24 PointerUpEvent#522ea 0
```

The middle 2 events are `PointerMoveEvent`, although there were only button changes and no movement. I kind of understand why this is the case, but maybe we want to distinguish the 2 cases or rename the event.

**Comment by chunhtai** [comment]
As framework point of view, a move event without actual change in position is acceptable. Not sure about button change.

**Comment by dkwingsmt** [comment]
I'll take this as a design choice.
