### ISSUE TITLE
How do I manually trigger a material to splash?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#2944]
I'd like to build a UI whereby I press a button on one part of my app and it causes a material in another part to run its inksplash animation (repeatedly).  I'd like some pointers (@abarth, @Hixie) on how I might find the other Material and then how I might tell it to splash.  I'm happy to build the example myself.

**Comment by abarth** [comment]
If you have the `BuildContext` for the other location (which you can get from a GlobalKey), you can try:

```Material.of(context).splashAt(...)```

See ink_well.dart to see how this is normally done.

**Comment by eseidelGoogle** [comment]
Thank you!

**Comment by Hixie** [comment]
Sounds like this is resolved; please reopen if there's still something to do here.
