### ISSUE TITLE
Keep track of the cursor position in TextSelection

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#29449]
When a `TextSelection` is collapsed (i.e. `baseOffset == extentOffset`) then it represents a cursor position. When it's not collapsed, it represents a selection range.

In the selection range state, we don't have the following piece of info:
* On which end of the range is the cursor supposed to be?

This becomes handy when a piece of text is selected and the user hits `Shift+LeftArrow`. If we don't know which end the cursor is on, we can't decide whether to expand the selection to the left, or shrink it from the right.

cc @gspencergoog @yjbanov

**Comment by shyndman** [comment]
The cursor sits at base offset. Extent offset is the value that changes while selection is ongoing.

**Comment by shyndman** [comment]
From the docs for [TextSelection.extentOffset](https://api.flutter.dev/flutter/services/TextSelection/extentOffset.html)

> The offset at which the selection terminates.
>
> When the user uses the arrow keys to adjust the selection, this is the value that changes. Similarly, if the current theme paints a caret on one side of the selection, this is the location at which to paint the caret.
>
> Might be larger than, smaller than, or equal to base.

**Comment by escamoteur** [comment]
I guess this was solved with the reply from @shyndman. So I close this now.
