### ISSUE TITLE
Add pubspec line to each Flutter plugin README

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#29459]
Each Flutter plugin README should include a section that demonstrates how it should be added to a pubspec file for easy reference.  For example, notice how the README for this Android library shows how to include it in the build.gradle file:

https://github.com/square/picasso

This is useful for people who go straight to GitHub instead of dart pub.

**Comment by matthew-carroll** [comment]
CC @amirh @mklim @bparrishMines

**Comment by stuartmorgan** [comment]
We have this for a number of plugins (we need to audit to see if it's all of them), but they get stale. We should also ensure that the breaking version (major for 1.0+, minor for <1.0) matched what's in the pubspec.
