### ISSUE TITLE
flutter gallery app repo this page and the buttons in the about dialog are not in the code

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#29455]
Where do I find this page in the flutter gallery app repo
![Screenshot_20190315-221340](https://user-images.githubusercontent.com/24699905/54465292-5e924980-4772-11e9-9b47-b7acb84b58c4.png)

the buttons in the about dialog are not in the code
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/about.dart
![Screenshot_20190315-223547](https://user-images.githubusercontent.com/24699905/54465398-db252800-4772-11e9-93b2-36b0937897f3.png)

**Comment by HansMuller** [comment]
It's part of the Dialog generated by showAboutDialog, see: https://docs.flutter.io/flutter/material/LicensePage-class.html

If you're curious about the implementation, start with [showLicensePage()](https://docs.flutter.io/flutter/material/showLicensePage.html): https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/about.dart#L183
