### ISSUE TITLE
Suggestion: flutter.io's Flutter header should link to https://github.com/flutter/flutter

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2945]
I find I often go to flutter.io when I really want to go to the flutter github due to chrome autocomplete - it'd be nice if the link tot he github repo was up from and center (I realize it's lower down on the page).

**Comment by Hixie** [comment]
@sethladd Not sure how we feel about this. On the long run we probably want to leave it where it is; do we want to make it more obvious on the short run?

Personally I just have a bookmark in my bookmark bar...

**Comment by sethladd** [comment]
Maybe it's worth asking "why do you need to go to flutter's github?" -- that is, should we link to something specific?

Also, chrome's location bar is pretty smart. You can type "flutter/flutter" and it will present a selection option for "github.com/flutter/flutter/..."

We are going to revisit the nav and site over time, but not going to take action on this one now. Thanks for the feedback, though!
