### ISSUE TITLE
[Flutter Tools] Debug options in flutter.bat dont working

### ISSUE THREAD

**Issue by rubensdemelo** [flutter/flutter#29466]
I'm on windows, following this guide: https://github.com/flutter/flutter/wiki/The-flutter-tool  

If only uncommented one of these lines, I got an error : 
`REM SET FLUTTER_TOOL_ARGS="--checked %FLUTTER_TOOL_ARGS%"`
Error: Error when reading '': The system cannot find the path specified.

`REM SET FLUTTER_TOOL_ARGS="%FLUTTER_TOOL_ARGS% --observe=65432"`
Error: Error when reading '%20--observe=65432': The system cannot find the file specified.

Is there any other thing I need to do to debug locally "my own" flutter cli ?

**Comment by jonahwilliams** [comment]
Change the second line to:

REM SET FLUTTER_TOOL_ARGS="--observe=65432"

**Comment by rubensdemelo** [comment]
> Change the second line to:
> 
> REM SET FLUTTER_TOOL_ARGS="--observe=65432"

It works. Thanks. Can I make a PR to change it ?

**Comment by jonahwilliams** [comment]
The first line seems wrong, it shouldn't reference FLUTTER_TOOL_ARGS since it hasn't been defined yet. We could put a comment before the second line containing the advice to remove the interpolation though
