### ISSUE TITLE
Hot reload stopped working in Visual Studio Code 1.32.3

### ISSUE THREAD

**Issue by brian-dunn** [flutter/flutter#29465]
This is a recurrence of a bug that was introduced in VSC 1.32.1 which caused hot reload to stop working. It was fixed in 1.32.2 and then broke again in 1.32.3. In the latest Visual Studio Code version of the Dart/Flutter plugin, nothing happens when you try to hot reload or even restart a Flutter app. The only way to run or test an app is to manually stop and restart the debugger which causes a full app rebuild and, of course, drops all state data.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
