### ISSUE TITLE
Google play license verification

### ISSUE THREAD

**Issue by deepss1** [flutter/flutter#29470]
So guys, I am new to flutter and app development as well. So I am developing a paid app in which I want to verify license. So I that I can stop illegal distribution of the app. And I have searched a lot on Google only to find nothing 😅

Please help me as without this, I can't proceed to publish on play store.

Thank you in advance for your time. ✌️

**Comment by jonahwilliams** [comment]
Hi @deepss1, this isn't really a question anyone on flutter can help you with.  For support questions, please check out one of the channels in https://flutter.dev/support
