### ISSUE TITLE
Flutter background service on Android

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#29473]
Hi, this is not really a problem, but this is one of the flaws that I found in flutter, I would like to get an answer from the flutter developers to solve this problem in the best possible way.
The essence of the problem lies in the following, flutter lives in the Android operating system in action, which imposes some restrictions on working in the background.
For example, the next task is to make calls using WebRTC, to establish a connection, a second communication channel is required for the exchange of SDP and IceCandidate. As we all know, when a user minimizes an application or, even worse, an application dies, activation dies, and on some phones, folding all means immediate death activation, and for calls via WebRTC, the solution is the foregroundservice in which WebRTC and WebSocket live for sharing sdp and IceCandidate. But in the case of the thrill, when WebSocket lives in a dart, it turns out that when a user throws calls to WebRTC, it will work until one of the users changes the ip or simply moves to the other, in which case the call may deteriorate or break down . Tell me what solution, except how to transfer WebSocket to the native android code, this solution is not very good, because for the secure transfer of sdp they need to be encrypted, which also adds cryptography to the native android code, and since much is transferred to the native android code. The best solution seems to be to simply create a second activation specifically for the call, but based on the advice on the flutter, it is better not to touch the native code at all.

**Comment by rebootcode** [comment]
@1AlexFix1 - Did you find any solution?

**Comment by 1AlexFix1** [comment]
> @1AlexFix1 - Did you find any solution?

https://github.com/flutter/flutter/issues/30332
and https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124
