### ISSUE TITLE
TextStyle.height behavior

### ISSUE THREAD

**Issue by t-artikov** [flutter/flutter#29479]
When it is 1, shouldn't the text height be equal to TextStyle.textSize?
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Text Height')),
        body: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Column(
              children: List<Widget>.generate(7, (index) {
                return Container(
                  child: Text(
                    '$index. Hello world',
                    textScaleFactor: 1,
                    style: TextStyle(fontSize: 14, height: 1),
                  ),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.black, width: 0),
                  ),
                );
              }),
            ),
            Column(
              children: List<Widget>.generate(7, (_) {
                return Container(
                  height: 14,
                  width: 100,
                  decoration: BoxDecoration(
                    color: Colors.red,
                    border: Border.all(color: Colors.black, width: 0),
                  ),
                );
              }),
            )
          ],
        ),
      ),
    );
  }
}
```
![Screenshot_1552719426](https://user-images.githubusercontent.com/1927992/54473201-1f620800-4807-11e9-83bc-5f474c542034.png)

I expect that the height of the Column with the Text will be equal to the height of the Column with Containers.

```
[✓] Flutter (Channel master, v1.3.11-pre.34, on Linux, locale en_US.UTF-8)
    • Flutter version 1.3.11-pre.34 at /opt/flutter
    • Framework revision 0bf0f5c1da (2 hours ago), 2019-03-15 22:03:13 -0700
    • Engine revision 015c0246ae
    • Dart version 2.2.1 (build 2.2.1-dev.1.1 None)
```

**Comment by ZoomZhao** [comment]
+1

**Comment by t-artikov** [comment]
@GaryQian FYI

**Comment by GaryQian** [comment]
We have confirmed that the height of the text we provide is consistent with the web if the same height is passed in pixels. However, after measuring the final resulting height and accounting for device pixel ratio, the height does seem to be taller than 14 pixels. Specifically, in your example, `Hello world` is actually 16 logical pixels tall empirically while the red boxes are indeed 14 logical pixels tall. Similarly, the web seems to produce the same result.

Although I am not yet completely clear on the exact cause of this, I will see if I can figure out why this is the case.

**Comment by ZoomZhao** [comment]
@GaryQian 

the web seems work as expect.
here is the demo: [https://codepen.io/ZoomZhao/project/full/DzonQg](https://codepen.io/ZoomZhao/project/full/DzonQg)

`Hello word` is 14 logical pixels tall.

**Comment by ZoomZhao** [comment]
@GaryQian 

i found an article [http://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align](http://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align)

it seems we set `the em-square`，but computed height is `the ascender` + `the descender`.

![Simulator Screen Shot - iPhone 8 Plus - 2019-04-23 at 11 35 33](https://user-images.githubusercontent.com/716935/56551982-5c66aa80-65bc-11e9-85ac-0d72ef5ae841.png)

**Comment by GaryQian** [comment]
Yes, we are indeed using the ascender+descender+leading as the height of the line. It is also seems to be the case that fontSize is setting the em square.

There is a problem with using the em-square as the height of the text, as the glyphs are able to draw outside of the em square. Also, in the case of multi-line text, it would not be clear how to consolidate what the site linked above describes as the content-area with the em square since the multiple lines are laid out based solely on the content-area.

I am curious about how the html/css is achieving a em square height and not risking overflow of text and multi-line handling (or maybe it does take these risks) to get a better idea of if/how to proceed with this.

**Comment by ZoomZhao** [comment]
@GaryQian 

I have updated the demo: https://codepen.io/ZoomZhao/project/full/DzonQg

in html/css:
- if line-height is not set, it will be the ascender+descender by default, there is no risk here.
- if developer set line-height, risks take by developer

so , I don't think we should `using the em-square as the height of the text`, just make height work as  a multiple of the font size when we set it.

**Comment by GaryQian** [comment]
The conceptual equivalent of css line-height in Flutter is Strut (`StrutStyle`). Our `TextStyle.height` property functions more like a scaling factor than css `line-height`

**Comment by ZoomZhao** [comment]
height in Strut seems no different with height in TextStyle.

I don't think ` Our TextStyle.height property functions more like a scaling factor than css line-height` is a good idea.  for `TextStyle.height`, different fontFamily lead to different result.

by the way, doc of `TextStyle.height` say `as a multiple of the font size`.

**Comment by GaryQian** [comment]
Strut is the minimum. When strut is the same as TextStyle, then there is little impact. When strut is set and a particularly small font is used, then the heights of the line are those of the strut, not the small text. It also gives the option to lock lines to the strut metrics.

The height property in TextStyle is literally just a coefficient multiplied against the metrics of the font. Our API does not necessarily mirror that of CSS, and the same effect can be achieved as css line-height, just differently.

**Comment by ZoomZhao** [comment]
> Our API does not necessarily mirror that of CSS, and the same effect can be achieved as css line-height, just differently.

yes, Flutter does not necessarily mirror API of CSS.
but the problem is **we are out of control of the final resulting height of text**, it depend on fontFamily.

for example:
![Simulator Screen Shot - iPhone 8 Plus - 2019-04-25 at 16 45 42](https://user-images.githubusercontent.com/716935/56723001-b3b27980-677a-11e9-950d-fb31229a28f7.png)

how can i set the text to 40 logical pixels tall?
>  just set line-height to 2 in CSS.

**Comment by ZoomZhao** [comment]
@justinmc @Hixie

**Comment by GaryQian** [comment]
We could potentially add an `absoluteLineHeight` property to StrutStyle, and LibTxt would force the full line box height to be exactly the number of logical pixels specified tall, with ascent, descent, leading all scaled proportional to the absolute height. This would definitely add a good amount of direct explicit control of vertical layout. We would want to warn that overlapping of text is likely in this scenario and many font metrics would be completely ignored. This should add the same capability that CSS provides.

In general, we have erred towards providing layouts base solely on the metrics of fonts, and a feature like this would be a slight departure from this concept, though there are plenty of legitimate uses for something like this that may be difficult to achieve any other way.

Until that is implemented though, it should be possible to achieve the same effect by creating a dummy font with all reported metrics scaled such that the sum is the height of the em box. The font would not need any glyphs and can be very lightweight. This dummy font could then be used in a strut style to guarantee the heights are exactly as desired.

**Comment by t-artikov** [comment]
I would prefer if 'absoluteLineHeight` will be added to TextStyle, not only to StrutStyle, which will allow setting it once for multiple texts through TextTheme.

Another solution is an `lineHeightMode` property like in QML
https://doc.qt.io/qt-5/qml-qtquick-text.html#lineHeightMode-prop

**Comment by Hixie** [comment]
> Yes, we are indeed using the ascender+descender+leading as the height of the line.

That number should equal the em square height plus the leading. I don't understand why it doesn't?

**Comment by Hixie** [comment]
![Drawing](https://user-images.githubusercontent.com/551196/56984849-db6b5e00-6b3b-11e9-8d8f-1eb9d88e0bac.png)

**Comment by GaryQian** [comment]
Here are some examples of what a current app would look like if we forced lines to em square height:
![pjimage (2)](https://user-images.githubusercontent.com/1887398/57110735-6a1fdc80-6cee-11e9-8446-a946c442579e.jpg)

![pjimage (1)](https://user-images.githubusercontent.com/1887398/57110705-4d83a480-6cee-11e9-8f76-e9639ee5e43f.jpg)

Left is current, right is the forced em-height

**Comment by GaryQian** [comment]
Changing from what we have now to em square rendering would be a massive breaking change. Most layouts would look too cramped, or at least more cramped than originally meant to be, and it would likely be a pain for devs to restore to their previous look.

This would need to sit behind a flag. We should discuss if this is best kept in StrutStyle or TextStyle. I can see arguments for either choice. It would likely just need to be a boolean flag.

**Comment by GaryQian** [comment]
If a large breaking change were made, it would probably be beneficial to do it together with a fix for https://github.com/flutter/flutter/issues/31707, which will require almost all text to shift slightly anyways. This way, we would only have to break devs once instead of multiple times.

**Comment by ZoomZhao** [comment]
I don't think forced em-height is a good choose.

why not like css:
- if height not set, default to `(ascender+descender)/em-height`
- if user set height，make height `as a multiple of the font size`

As a result，maybe we don't need a breaking change.


> The height of this text span, as a multiple of the font size.
>If applied to the root TextSpan, this value sets the line height, which is the minimum distance > between subsequent text baselines, as multiple of the font size.

we just make height as expect as the TextStyle's document.

**Comment by Hixie** [comment]
That's an interesting idea. Basically, if we set an explicit height, do the em-size scaling of ascent+descent, and apply leading equally to both sides based on the specified height; but if there's no explicit height, then use the given ascent+descent and don't put any additional space between lines.

**Comment by GaryQian** [comment]
How should we handle cases where the behavior changes which will break people, but the change technically does not break the docs description? I don't think we explicitly specified the difference between omitting height and specifying it in the docs here.

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/9041 Implements the behavior @ZoomZhao described. This is technically more accurate to what our docs describe. It seems that the framework tests pass without issue in response to this change.

**Comment by GaryQian** [comment]
The PRs for this change are currently waiting to land due to tree stability.

**Comment by GaryQian** [comment]
This height change is in the master channel, and will not be in 1.7 stable.
