### ISSUE TITLE
Bad UTF-8 encoding 0xff Error  (at offset 0)

### ISSUE THREAD

**Issue by krngd2** [flutter/flutter#29477]
I am getting this error while trying to open a .json file.
So my application downloada zip file and extracts it with the [archive ](https://pub.dartlang.org/packages/archive)module 
```
extractFiles() async{
    final dir = await Storage().localPath;
    final _directory = Directory(dir+"/bizzapp");
    List<FileSystemEntity> _files;
    _files  = _directory.listSync(recursive: true, followLinks: false);  
    // Read the Zip file from disk.
    List<int> bytes = new File(_files[0].path).readAsBytesSync();

    // Decode the Zip file
    Archive archive = new ZipDecoder().decodeBytes(bytes);

    // Extract the contents of the Zip archive to disk.
    for (ArchiveFile file in archive) {
      String filename = file.name;
      if (file.isFile) {
        List<int> data = file.content;
        new File(dir+'/bizzapp/' + filename)
          ..createSync(recursive: true)
          ..writeAsBytesSync(data);
      } else {
        new Directory(dir+'/bizzapp/' + filename)
          ..create(recursive: true);
      }
    }
  }
````

then trying to open the file 

```
getFilesFromDevices() async {
    final dir = await Storage().localPath;
    final _directory = Directory(dir+"/bizzapp/MData");
    setState(() {
      _files = _directory.listSync(recursive: true, followLinks: false);
      print({"File Path ",_files.map((f)=>f.path)}); 
    });
  } 

 //on button click calling this method 
 Future<String> loadAssetFromJson(path) async {
    return await rootBundle.loadString(path);
  }
```

After clicking on the button i am getting this error 

> E/flutter ( 3141): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: FormatException: Bad UTF-8 encoding 0xff (at offset 0)
> E/flutter ( 3141): # 0      _Utf8Decoder.convert (dart:convert/utf.dart:518:13)
> E/flutter ( 3141): # 1      Utf8Decoder.convert (dart:convert/utf.dart:311:13)
> E/flutter ( 3141): # 2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
> E/flutter ( 3141): # 3      AssetBundle._utf8decode 
> package:flutter/…/services/asset_bundle.dart:79
> E/flutter ( 3141): # 4      _IsolateConfiguration.apply 
> E/flutter ( 3141): # 5      _spawn.<anonymous closure> 
> package:flutter/…/foundation/isolates.dart:115
> E/flutter ( 3141): # 6      Timeline.timeSync (dart:developer/timeline.dart:161:22)
> E/flutter ( 3141): # 7      _spawn 
> package:flutter/…/foundation/isolates.dart:113
> E/flutter ( 3141): # 8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:303:17)
> E/flutter ( 3141): # 9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

I tried opening the extracted file from another json application and it failed, 
I tried connecting phone to the pc and checked storage and there is no bizzapp folder in the local storage while its clearly visible in the mobile's file manager. i sent the file from another medium to the pc and opened it and it opened correctly 

This is really weird, Is there anything wrong with the way i am extracting the files?

**Comment by cbracken** [comment]
It looks like the file is not a valid UTF-8 file and so the codec is choking on it. UTF-8 supports an optional [byte-order mark](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of the file which can help with endianness and signalling whether a byte stream is utf-8, utf-16, etc.

UTF-8 files that include this mark should begin with the (hex) bytes `fe bb bf`. Note that there's no `ff` byte there. The optional UTF-16 BOM looks like `fe ff`, which would come in as `ff fe` if the consuming system has the opposite endianness of the producing system. Are you sure your file isn't UTF-16?

As a fix, I'd suggest opening the file in a hex editor and just removing the leading 0xff 0xfe bytes.
