### ISSUE TITLE
Having trouble in showing Notifications, when app is closed

### ISSUE THREAD

**Issue by prkhrv** [flutter/flutter#29480]
Hi, I have created a Chat App using Flutter and I am successfully showing incoming message notification when the app is running, but I want to show the notifications when the app is closed.

How can I do that, please Help !

**Comment by TatsuUkraine** [comment]
If talk about native code you have 2 option at least for android:
- register notification listener
- use Firebase keys that will force to show notification message

as for flutter - I think you can try to find answer here
https://stackoverflow.com/questions/53572110/flutter-push-notifications-even-if-the-app-is-closed

**Comment by prkhrv** [comment]
@TatsuUkraine Thanks, I achieved this by using Firebase Cloud Messaging.

**Comment by Moizsohail** [comment]
> @TatsuUkraine Thanks, I achieved this by using Firebase Cloud Messaging.

Hey can you highlight how did you achieve this. I have been trying to get this done since the past 3 days.
