### ISSUE TITLE
'Dart' & 'Android' is not recognized as an internal or external command - Android studio

### ISSUE THREAD

**Issue by Davee-io** [flutter/flutter#29482]
When i try to run my flutter app, i throw in this error:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\Admin\Videos\Udemy\Programming\Learn Flutter & Dart to Build iOS & Android Apps\NOTES\1. Introduction\first_app\android\gradlew.bat" exited abnormally:
'Dart' is not recognized as an internal or external command,
operable program or batch file.
'Android' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
  Command: C:\Users\Admin\Videos\Udemy\Programming\Learn Flutter & Dart to Build iOS & Android Apps\NOTES\1. Introduction\first_app\android\gradlew.bat -v

![1](https://user-images.githubusercontent.com/43140394/54473238-3ee03d00-47d5-11e9-972f-08de901d5a03.png)
![2](https://user-images.githubusercontent.com/43140394/54473239-3f78d380-47d5-11e9-828b-780c0752d1b9.png)
![3](https://user-images.githubusercontent.com/43140394/54473240-3f78d380-47d5-11e9-98a9-06ba7286b846.png)

**Comment by Davee-io** [comment]
I checked this notification on my emulator:

![1](https://user-images.githubusercontent.com/43140394/54473889-245e9180-47de-11e9-9bd6-d5ef64926a93.png)


After waiting a little bit nothing happens..
So i try some other solution, finally i switched to the guest user :

- From the top of any Home screen, the lock screen, and many app screens, swipe down with 2 fingers. This opens your Quick Settings.
- Tap Switch user Signed in as.
- Tap a different user. That user can now sign in.


![2](https://user-images.githubusercontent.com/43140394/54473955-1fe6a880-47df-11e9-9bdc-9bd7530b63cd.png)


Finally, it started correctly!


![3](https://user-images.githubusercontent.com/43140394/54473991-853a9980-47df-11e9-9df3-1bf9201824f5.png)

**Comment by gratefulgirl** [comment]
great
