### ISSUE TITLE
Floating action button on top of google map plugin is repositioned and resized fast at startup

### ISSUE THREAD

**Issue by bogdannedelcu** [flutter/flutter#29492]
## Steps to Reproduce

The app contains a `StatefulWidget` with `Scaffold` having `Drawer` and `GoogleMap` plugin.

Steps to reproduce:
1. Open the built sample app
2. Look how the blue floatingActionButton gets resized when starting app. Normally should be centered, but moves on the right size and is resized as is seems a bit larger.
3. Kill app and start again
4. Observer again, it happens very fast only when starting app.

See movie floating resized.mp4

I see it happen only on iOS. 

link to source code and recorded video: https://drive.google.com/drive/folders/1_oaZLIAqFQ82Eg_Gcn9X0I59Vto3TR5k?usp=sharing

## Logs

`flutter run --verbose` 
does not produce any logs after starting the app on iPhone

`flutter analyze` 
does not return any  issues

Thank you for helping with this issue. 

`flutter doctor -v`
```
```

[✓] Flutter (Channel master, v1.3.11-pre.34, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.3.11-pre.34 at /Users/bogdannedelcu/Developpment/flutter
    • Framework revision 0bf0f5c1da (in the future), 2019-03-15 22:03:13 -0700
    • Engine revision 015c0246ae
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bogdannedelcu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

main file is bellow:

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:maps_testing/new_screen.dart';

class MapScreen extends StatefulWidget {
  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  GoogleMapController mapController;
  var _scaffoldKey = GlobalKey<ScaffoldState>();

  bool markersVisible = true;

  String error;

  Map<MarkerId, Marker> markers = <MarkerId, Marker>{};

  @override
  Widget build(BuildContext context) {
    double _screenWidth = MediaQuery.of(context).size.width;
    double _screenHeight = MediaQuery.of(context).size.height;
    return Scaffold(
        key: _scaffoldKey,
        drawer: Drawer(
          child: GestureDetector(
            behavior: HitTestBehavior.opaque,
            child: Center(
              child: Text('Press anywhere to test the bug'),
            ),
            onTap: () {
              Navigator.pop(context);
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => NewScreen(),
                ),
              );
            },
          ),
        ),
        body: Stack(children: <Widget>[
          Center(
              child: GoogleMap(
                initialCameraPosition: CameraPosition(
                  bearing: 0.0,
                  target: LatLng(48.8566,2.3522),
                  tilt: 0.0,
                  zoom: 18.0,
                ),
                mapType: MapType.normal,
                onMapCreated: _onMapCreated,
                tiltGesturesEnabled: false,
                myLocationEnabled: true,
                compassEnabled: false,
                markers:  Set<Marker>.of(markers.values)



              ),
          ),

        ]),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton:
      Column(mainAxisAlignment: MainAxisAlignment.end, children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Stack(
              alignment: Alignment.bottomCenter,
              children: <Widget>[
                Container(
                  height: 100.0,
                  width: 100.0,
                  child: FloatingActionButton(
                    heroTag: 'call',
                    shape: CircleBorder(
                      side: BorderSide(
                        color: Colors.white24,
                        width: 4.0,
                      ),
                    ),
                    tooltip: 'Call',
                  ),
                ),
              ],
            ),
          ],
        )
      ]),
    );
  }

  void _onMapCreated(GoogleMapController controller) {

    mapController = controller;

    final Marker marker2 =  Marker(
          markerId: MarkerId('2233'),
          position: LatLng(44.4110224, 26.0712143),

          infoWindow: InfoWindow(title: "Mega Image", snippet: "Bulevardul Lacul Tei"),
          icon: BitmapDescriptor.defaultMarkerWithHue(
              BitmapDescriptor.hueGreen),
          consumeTapEvents: false);

  markers[MarkerId('2233')] = marker2;


//    setState(() {});
  }



  void _showMarkers(bool flag, GoogleMapController controller) {
    if (flag == true) {
      setState(() {


      });
    }
  }
}

```
```

**Comment by bogdannedelcu** [comment]
cc @dnfield

**Comment by dnfield** [comment]
@amirh knows more about this one.

**Comment by amirh** [comment]
This might be the same issue as https://github.com/flutter/flutter/issues/28918 which was just fixed, could you try again with latest master?

**Comment by bogdannedelcu** [comment]
I confirm. Closing. Thank you!
