### ISSUE TITLE
code does not compile 

### ISSUE THREAD

**Issue by nourmad** [flutter/flutter#29501]
Hello there I was following the tutorial for flutter offered by code labs and if you copy the code step by stem it would not compile due to a missing '}' at the last line of code as for the code included at the end it works perfectly

**Comment by timsneath** [comment]
Unfortunately there isn't enough information on this bug to reproduce the issue. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. In particular, please include the specific code lab that you're using and the step that gave you the error. 

Thank you for using Flutter!
