### ISSUE TITLE
video player dismiss when there is a iOS platform view

### ISSUE THREAD

**Issue by Qxyat** [flutter/flutter#29503]
I build a page view. In page 1 & 3, I build a iOS platform view in the page. In page 2, I build a video player. When I scroll the page view, the video player dismiss. Please take a look at the gif.

![1](https://user-images.githubusercontent.com/11627283/54486365-5d703200-48c2-11e9-81c9-e54ed369dc7a.gif)

And the demo is here.
https://github.com/Qxyat/Flutter-demo/tree/master/video_player

flutter doctor -v
[✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.14.1 18B75, locale zh-Hans-CN)
    • Flutter version 1.3.10 at /Users/qiuxinyue/Documents/flutter
    • Framework revision 4feefa3c9a (3 days ago), 2019-03-14 10:21:03 -0400
    • Engine revision 8b1a299ed5
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/qiuxinyue/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone • 00008020-000568E83698002E • ios • iOS 12.1.4

• No issues found!

**Comment by Qxyat** [comment]
@amirh Would you please do me a favor?

**Comment by arkivika** [comment]
Also having this issue. The video disappears consistently after opening the platform view with ImagePicker.pickVideo() to open a second video next to the original. The video comes back after calling the first videoPlayerController's .seekTo().

> [✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14.3 18D109, locale en-FI)
>     • Flutter version 1.3.13 at /Users/arkivika/Development/flutter
>     • Framework revision 59ce7d6bff (2 days ago), 2019-03-18 11:20:10 -0700
>     • Engine revision e75f6de01f
>     • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/arkivika/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 33.3.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] VS Code (version 1.32.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.24.0
> 
> [✓] Connected device (1 available)
>     • iPhone (-) • c3e954267f3f2d620b9fe9e95a455fb30aaf651f • ios • iOS 12.1.4
> 
> • No issues found!

**Comment by xster** [comment]
@dnfield is this the same issue you're fixing?

**Comment by dnfield** [comment]
The issue I was working on has landed as of https://github.com/flutter/flutter/commit/99f1e507c9fe198fbdccdf8a2b6af63dc010736c - it may be worth checking to see if this one is still a problem at that commit.

**Comment by Qxyat** [comment]
@dnfield I have run the demo at that commit, and still have the problem. The demo is https://github.com/Qxyat/Flutter-demo/tree/master/video_player.
