### ISSUE TITLE
Finalizer exception when using NetworkImage.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2950]
Test app:
```
void main() {
  runApp(new Row(children:[new NetworkImage(src:'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg')]));
}
```

Exception:
```
03-28 10:26:27.462 E/System  (17062): Uncaught exception thrown by finalizer
03-28 10:26:27.463 E/System  (17062): java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
03-28 10:26:27.463 E/System  (17062): 	at org.chromium.mojo.bindings.AutoCloseableRouter.finalize(AutoCloseableRouter.java:111)
03-28 10:26:27.463 E/System  (17062): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
03-28 10:26:27.463 E/System  (17062): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
03-28 10:26:27.463 E/System  (17062): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/2509#issuecomment-204604837 from @jamesr:
> I remember looking with @collinjackson a few months back at a number of places in flutter that have mojo or android objects owned by dart or java objects without an explicit teardown path. In both cases this produces potentially pretty bad memory leaks as neither the Android runtime nor the Dart runtime promise to run finalizers promptly or even run them at all. I don't remember if anything came of this.
> 
> In this case the Mojo bindings Java finalizer is the one complaining that some Java object was holding on to a Mojo handle when the finalizer ran, meaning it wasn't explicitly destroyed.

**Comment by Hixie** [comment]
this sounds like the kind of thing @jason-simmons finds oddly irresistible. :-)

**Comment by Hixie** [comment]
We're probably leaking all the mojo objects on the Java side of things when accessibility is enabled, too.

**Comment by jimbeveridge** [comment]
+1 for this bug. Seeing it whenever I use `FlutterView`.
