### ISSUE TITLE
video_player can't load and play video from the network from http requests, only https are working

### ISSUE THREAD

**Issue by roischr** [flutter/flutter#29502]
i'm trying to create new video player app that load vast xml and and extract the data from it.
one item in the data  is video file, it can be http or https and i can't know in advance, 
i can't just replace http to https because then i can be wrong domain name.
is there a why to stream the video file with http?
Thaks.

**Comment by LinusU** [comment]
As stated in the readme you need to add `NSAppTransportSecurity -> NSAllowsArbitraryLoads` to your `Info.plist` in order to load things over http on the iOS platform...

**Comment by recastrodiaz** [comment]
@roischr if the feedback above helped, could you close this issue?

**Comment by escamoteur** [comment]
As no reply came till now I close this issue
