### ISSUE TITLE
Better persistent database support on flutter (Eg: A Stable ORM for sqlite or something equivalent)

### ISSUE THREAD

**Issue by ishaan1995** [flutter/flutter#29512]
I am using flutter now from past few months and overall the impression is good. The widget library is extensive and I find it easy to find my way around.

One think that's stoping me from using flutter for a production application is the plugin support.
I see there is [sqflite](https://pub.dartlang.org/packages/sqflite) for a persistent database but no better/ reliable ORM like the native platforms have (Room, sqlbrite on Android; sharkOrm for iOS).

There is not even a reliable nosql database (There is realm on iOS, Android and also React-Native).

Creating an issue in hope of finding better support for offline database in the upcoming Google IO 209 to use flutter without a doubt for my next store app.

**Comment by ishaan1995** [comment]
Although I am happy to see all these mentioned in the flutter [roadmap](https://github.com/flutter/flutter/wiki/Roadmap), some estimate timelines are going to be really good.

**Comment by ishaan1995** [comment]
Any updates on this?

**Comment by ishaan1995** [comment]
@eseidel @sethladd Will this be a priority for 2019 or later?

**Comment by ishaan1995** [comment]
My current solution relies on using sqflite and jaguar orm to generate simpler data access layer for me, but still it does not cover all aspects and makes working with database a pain.

**Comment by PrakashNaidu2662** [comment]
Hi Ishaan, Even I am looking for the stable ORM for SQLite with flutter.

**Comment by newtonmunene99** [comment]
I'm not sure what exactly you are all looking for but try [Floor](https://pub.dev/packages/floor) and [Moor](https://pub.dev/packages/moor)

**Comment by aleksamagicka** [comment]
Maybe [Jaguar](https://github.com/Jaguar-dart/jaguar_orm) can help?

**Comment by omtodkar** [comment]
> Hi I'm not sure what exactly you are looking for but try [Floor](https://pub.dev/packages/floor) and [Moor](https://pub.dev/packages/moor)

+1 for [floor](https://pub.dev/packages/floor)

**Comment by escamoteur** [comment]
@csells are there any plans to provide such a database package from the flutter team?

**Comment by MrNinja** [comment]
Hope that we have an official ORM are supported for SQLite in Flutter.

**Comment by csells** [comment]
@MrNinja have you given [moor](https://pub.dev/packages/moor) a try? I've heard good things.

**Comment by Khalid-Nowaf** [comment]
try [Hive]( https://pub.dev/packages/hive)

**Comment by stuartmorgan** [comment]
Closing, as there are a variety of options in the ecosystem, and we don't feel that having the Flutter team pick a single arbitrary solution to support as a first-party plugin would be the best option.
