### ISSUE TITLE
Unexpected error in flutter run‍‍‍

### ISSUE THREAD

**Issue by oky2abbas** [flutter/flutter#29517]
Hi, I ‍`created` a project, but I'm going to `run` an error to run the app.

**OS** :`macOS Mojave`
**Flutter** : `v1.2.2`

##### Details of the flutter doctor's command
```
$lab > flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

##### Steps to Reproduce
```
$lab > flutter create sample
$lab > cd sample
$lab > flutter run
```
Then I received a lot of messages in batch with this text: **This is taking an unexpectedly long time.**

**Comment by jonahwilliams** [comment]
@oky2abbas are you developing for iOS? If so the errors raised under flutter doctor's iOS toolchain section need to be addressed.

Please also include the verbose logs of the run command.

**Comment by oky2abbas** [comment]
I am an Android developer and `do not need iOS`. Log does not give me More than 1 hour. This message is displayed to me **This is taking an unexpectedly long time**.

**Comment by DanTup** [comment]
@oky2abbas Can you please include the exact output of the `flutter run -v` command. The text **This is taking an unexpectedly long time** can appear for many different operations but it's not clear which one it's getting stuck on. Please run `flutter run` with the `-v` switch and attach the full output here.

Thanks!

**Comment by KEVINAMAYI** [comment]
I had this same error for three days, and no one was able to address the issue?  only bugs closed...

**Comment by DanTup** [comment]
@KEVINAMAYI this issue was closed because there was not enough information and no response to the requests for a full verbose log. It's very difficult to debug issues without the error messages or output being shown. If you're having an issue that there isn't an open issue for, please open a new one and include a full verbose log if relevant. Thanks!

**Comment by KEVINAMAYI** [comment]
Thanks you for the info

**Comment by oky2abbas** [comment]
To fix this, you need to delete the `~/Users/username/.gradle` folder and download it again. Then wait for the download to finish.

**Comment by KEVINAMAYI** [comment]
thak you so much
