### ISSUE TITLE
Stuck at "installing and launching" after setting up firebase_messaging

### ISSUE THREAD

**Issue by eduardmo** [flutter/flutter#29519]
Following the readme provided on the firebase_messaging github page, I set up everything for IOS and Android and works for Android. On the IOS side it's getting stuck at the "Installation and launching" part. I can notice that at some point during this part, the app tried to open but closes immediately. Is this a crash? How can I see a log of it?

I tried removing the pod master and setting it up back and I uninstalled the app from the phone. 

This is the terminal where it gets stuck: https://imgur.com/a/R3QmUa5

Flutter doctor:

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.1 18B75, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2018.2.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.

**Comment by jonahwilliams** [comment]
@eduardmo can you re-run the command in verbose mode? that should tell us what it is getting stuck on:

```
flutter run -v
```

**Comment by eduardmo** [comment]
I figured it out. The mistake was on my end. I started the project using XCode and a simulator and the logs told me that I didn't put the GoogleServices-Info.plist. When I downloaded it, I only pasted it and it looks like I should've add it using Xcode. Thank you very much!
