### ISSUE TITLE
how to set background for a sliverlist

### ISSUE THREAD

**Issue by skysukai** [flutter/flutter#29524]
I've develop an app. There is a page like this:
[https://stackoverflow.com/questions/55194972/flutter-how-to-set-background-for-a-sliverlist](url)
The question is I just need set background for a sliverlist not the CustomScrollView.And the backgound is a png picture.
How can I do?

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We cannot provide personal support here. Thanks!
