### ISSUE TITLE
type 'DefaultWidgetsLocalizations' is not a subtype of type 'S'

### ISSUE THREAD

**Issue by fengmnegchang** [flutter/flutter#29525]
1.I user flutter_localizations plugin apply i18n for multi len
2.user resource S.of(context).home_borrow_login_card_app to AppBar no problem
3.But i apply S.of(context).home_borrow_login_card_app to ListTile's  title: new Text(_title),subtitle: new Text(_subtitle), the exception was thrown, this was the stack.

## Logs

Syncing files to device Android SDK built for x86...
I/flutter (10311): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10311): The following assertion was thrown building HeadingItemWidget(dirty, dependencies:
I/flutter (10311): [_LocalizationsScope-[GlobalKey#cf8dd]]):
I/flutter (10311): type 'DefaultWidgetsLocalizations' is not a subtype of type 'S'
I/flutter (10311): 
I/flutter (10311): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10311): more information in this error message to help you determine and fix the underlying cause.
I/flutter (10311): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (10311):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (10311): 
I/flutter (10311): When the exception was thrown, this was the stack:
I/flutter (10311): #0      _LocalizationsState.resourcesFor (package:flutter/src/widgets/localizations.dart:537:13)
I/flutter (10311): #1      Localizations.of (package:flutter/src/widgets/localizations.dart:449:39)
I/flutter (10311): #2      S.of (package:flutter_app/generated/i18n.dart:19:21)
I/flutter (10311): #3      HeadingItemWidget.build (package:flutter_app/borrow/home_borrow.dart:89:10)
I/flutter (10311): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (10311): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (10311): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #7      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #25     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
I/flutter (10311): #26     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:980:34)
I/flutter (10311): #27     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter (10311): #28     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:991:36)
I/flutter (10311): #29     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:957:7)
I/flutter (10311): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #33     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #37     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (10311): #38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (10311): #39     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
I/flutter (10311): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #75     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #79     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #83     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #87     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #91     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #93     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (10311): #94     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (10311): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #102    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #112    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #126    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #130    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #134    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
Reloaded 4 of 449 libraries in 1,020ms.
I/flutter (10311): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #140    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #144    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #146    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #152    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #155    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #156    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #160    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #161    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #162    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #165    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #166    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #168    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #172    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (10311): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #175    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #176    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (10311): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #178    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (10311): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #182    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (10311): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (10311): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (10311): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (10311): #186    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (10311): #187    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (10311): #188    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (10311): #189    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (10311): #190    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (10311): #191    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter (10311): #193    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (10311): #194    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (10311): #195    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (10311): (elided one frame from package dart:async)
I/flutter (10311): ═══════════════════════════════════════════════════════════════

**Comment by fengmnegchang** [comment]
The full code as :

import 'package:flutter/material.dart';
import '../generated/i18n.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class HomeBorrowApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return MaterialApp(
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      supportedLocales: S.delegate.supportedLocales,
      localeResolutionCallback: S.delegate.resolution(
          fallback: Locale("en", "")),
      theme: ThemeData(primaryColorBrightness: Brightness.light),
      home: HomeBorrowPage(),
    );
  }
}


class HomeBorrowPage extends StatefulWidget {

  @override
  State<StatefulWidget> createState() {
    return _HomeBorrowPageState();
  }
}

class _HomeBorrowPageState extends State<HomeBorrowPage> {
  List<ListItem> _list = new List<ListItem>();

  _HomeBorrowPageState() {
    _list.add(new HeadingItem());
    _list.add(new HeadingItem());
    _list.add(new HeadingItem());
    _list.add(new HeadingItem());
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar:
        new AppBar(
          title: new Text(S
              .of(context)
              .home_borrow_login_card_app),
          centerTitle: true,
        ),
        body: new ListView.builder(
          // Let the ListView know how many items it needs to build
          itemCount: _list.length,
          // Provide a builder function. This is where the magic happens! We'll
          // convert each item into a Widget based on the type of item it is.
          itemBuilder: (context, index) {
            final item = _list[index];
            if (item is HeadingItem) {
              return new HeadingItemWidget();
            }
          },
        ),
      ),
    );
  }

}

// The base class for the different types of items the List can contain
abstract class ListItem {
}

class HeadingItem implements ListItem {
  HeadingItem();
}

class HeadingItemWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    String _title = "";
    String _subtitle = "";

    _title = S
        .of(context)
        .home_borrow_login_card_app;
    _subtitle = S
        .of(context)
        .home_borrow_login_card_app_desc;


    return new ListTile(
      leading: new Icon(Icons.album),
      title: new Text(_title),
      subtitle: new Text(_subtitle),
    );
  }
}

**Comment by Tridie2000** [comment]
This is a serious issue because it seems impossible to localize to title and subtitle of a ListTile. I'm using the I18n extension in VSCode and I'm facing the same issue.

**Comment by TahaTesser** [comment]
Hi @fengmnegchang 
If you're still experiencing this issue, please follow this [Internationalizing Flutter apps](https://flutter.dev/docs/development/accessibility-and-localization/internationalization)

Your sample code is incomplete. 
If the doc doesn't help, please create a new issue and provide necessary details
Thank you
