### ISSUE TITLE
can not  set the global `$PATH` of flutter, what should I do?

### ISSUE THREAD

**Issue by xgqfrms** [flutter/flutter#29539]
# can not set the global `$PATH` of flutter, what should I do?

![image](https://user-images.githubusercontent.com/7291672/54514138-47cb3d00-4994-11e9-82f1-35d3fd5de7c9.png)

## Steps to Reproduce

I following the `https://flutter.dev/docs/get-started/install/macos` guide, but still can set the  global `$PATH` of flutter.

1. edit `.bash_profile` isn't work, 
2. execute `export PATH="$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin"` is ok, but only work for current terminal window
3. after close terminal and re-open one terminal, I lose  the `$PATH` again, as following image shows

![image](https://user-images.githubusercontent.com/7291672/54515641-a0500980-4997-11e9-8c69-b93b5838af45.png)

**Comment by xgqfrms** [comment]
https://stackoverflow.com/search?q=%5Bflutter%5D+%24PATH

**Comment by lihui2333** [comment]
add to your flutter bin path to the ~/.zshrc file or add source ~/.bash_profile to the ~/.zshrc

**Comment by xgqfrms** [comment]
@lihui2333 thanks a lot!

> zsh !== native terminal

> `.zshrc` !== `.bash_profile`

```sh

$ cat .zshrc
$ vim .zshrc

# flutter PATH & zsh
export PATH="$PATH:/Users/xgqfrms-mbp/Documents/Flutter/flutter/bin"

$ source $HOME/.zshrc

```

![image](https://user-images.githubusercontent.com/7291672/54518663-d09ba600-499f-11e9-9885-0a89010487a4.png)

**Comment by xgqfrms** [comment]
# `.zshrc` path

![image](https://user-images.githubusercontent.com/7291672/68672412-89949d80-058c-11ea-9122-4947c43dd23f.png)
