### ISSUE TITLE
Adding today extension target to xCode project causes an Apple Mach-O linker error for a library not found.

### ISSUE THREAD

**Issue by NickM-27** [flutter/flutter#29531]
## Steps to Reproduce

Trying to add a native today extension target to my flutter app but its build fails

1. Create Flutter project
2. Add today extension target to project in xCode
3. Try to build

## Logs

xCode exception:
```
ld: warning: directory not found for option '-F/Users/nickmowen/Library/Developer/Xcode/DerivedData/Runner-egikkgpuyfdkbcconodjborapzme/Build/Products/Debug-iphoneos/share'
ld: warning: directory not found for option '-F/Users/nickmowen/Library/Developer/Xcode/DerivedData/Runner-egikkgpuyfdkbcconodjborapzme/Build/Products/Debug-iphoneos/shared_preferences'
ld: warning: directory not found for option '-F/Users/nickmowen/Library/Developer/Xcode/DerivedData/Runner-egikkgpuyfdkbcconodjborapzme/Build/Products/Debug-iphoneos/sqflite'
ld: warning: directory not found for option '-F/Users/nickmowen/Library/Developer/Xcode/DerivedData/Runner-egikkgpuyfdkbcconodjborapzme/Build/Products/Debug-iphoneos/url_launcher'
ld: framework not found FMDB
clang: error: linker command failed with exit c
```

```
Analyzing friend_zones_ios...                                           
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.4 18E215a, locale en-US)
    • Flutter version 1.3.8 at /Users/nickmowen/Library/Android/flutter
    • Framework revision e5b1ed7a7f (11 days ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nickmowen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Nicolas’s iPhone • 437cee40358e29ea41f23d0192c3713c29e87bc1 • ios • iOS 12.1.4

! Doctor found issues in 1 category.
```

**Comment by NickM-27** [comment]
Edit: If I include FMDB.framework with the Today Extension target then the new error is:

```
ld: '/Users/nickmowen/Library/Android/flutter/bin/cache/artifacts/engine/ios/Flutter.framework/Flutter' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/nickmowen/Library/Android/flutter/bin/cache/artifacts/engine/ios/Flutter.framework/Flutter' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I know that flutter does not support bitcode but I wouldn't think that this should be a problem since I am trying to build the today extension which is separate from the flutter app.

Perhaps there is a way to make it so that the today extension stops trying to include the flutter framework? (Not sure why it is in the first place)

**Comment by magnatronus** [comment]
@NickM-27 May need a bit more detail on what you have done for this to fail. I have had a quick go and the Flutter app still works. My exact steps were:

1. Generate a new Flutter app.
2. Run in emulator to make sure it works.
3. Open the ios project( Runner.xcworkspace)
4. Select File->New->Target
5. Add a Today Extension (using Objective-c) 
6. Run up app again - for me this works fine

In fact if I run it on a device I can then add the default generated widget to my Notification Center screen.

**Comment by NickM-27** [comment]
@magnatronus My bad I should have specified, I selected today extension as Swift

**Comment by magnatronus** [comment]
@NickM-27 I have also tested this using Swift rather than Objective-c . and this seems to work as well.  I guess that my tests are just default Flutter and iOS Today extensions with no extra code or packages (which may be causing the actual issue). But I have uploaded the test project [here](https://github.com/magnatronus/flutter-today-swift)

**Comment by NickM-27** [comment]
@magnatronus Okay, so it seems to be the sqflite package that is causing this error, since it includes another framework (FMDB). Any advice on how to fix this?

I tried creating a blank project and added all other dependencies and it seems to work fine, not sure what to do since I pretty much need the database

**Comment by NickM-27** [comment]
@magnatronus When you created the flutter project did you include swift support for the iOS portion? I am starting to wonder if maybe that is the issue and I shouldn't have (is there any way to undo that without creating a fresh project?)

**Comment by magnatronus** [comment]
@NickM-27  I have updated my simple example with the sqflite package and a bit of test code which seems to work fine. As for the *include Swift support*, I assume you mean you are trying to add some native code to the Flutter project to send data to Today extension using a channel? if so no I did not try this.

**Comment by NickM-27** [comment]
@magnatronus I don't actually need Swift code in my project, I only added it because I wasn't sure how today extension worked at that point. So perhaps I can just recreate the project without Swift integration (is there anyway to undo it without recreating?) and perhaps it will work

**Comment by magnatronus** [comment]
@NickM-27 That would be how I would do it, and actually have when I had an issue with Swift and a package I created.  I don't know what steps would be required to re-build/re-factor the iOS part of the project and remove Swift support (Im sure someone else probably does though) but it should not be too difficult to create a new Flutter project and copy across the lib dir etc.

Would be nice though to try and find a solution to the issue - maybe ask the author of the sqflite package if they have any ideas.

**Comment by NickM-27** [comment]
Thanks for this, seem to have gotten past that issue but now am dealing with a different one (thanks for all the help). 

`I am getting this error: flutter_inapp_purchase/FlutterInappPurchasePlugin.h file not found`

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?


Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
