### ISSUE TITLE
`flutter upgrade` needed twice if sky_services dependencies change

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#2953]
## Steps to Reproduce

I just upgraded flutter and tried running my code in the Atom editor, but received this bug:

error: Unable to find Dart library 'packages/mojo_services/mojo/ui/view_containers.mojom.dart'.
Failed to run the Flutter compiler. Exit code: 1

Oops; flutter has exited unexpectedly: "1"

Not sure where the problem is, hello world example app is running fine. I also received the same bug on my Linux desktop.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/vanadium/flutter
    • Framework revision 0eab5e6 (26 hours ago), engine revision f790903

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1

## Logs and Crash Reports

[flutter_01.log.zip](https://github.com/flutter/flutter/files/192282/flutter_01.log.zip)

**Comment by abarth** [comment]
You might need to run "pub upgrade" on your app.  If you right-click on your main.dart file in Atom, that should be an option in the context menu.

**Comment by eseidelGoogle** [comment]
I had this same problem this morning, but was able to fix it by running `flutter upgrade` a second time.  I suspect that we `pub update` in the wrong order relative to fetching flutter? @devoncarew

**Comment by eseidelGoogle** [comment]
We appear to `pub upgrade` right after updating the flutter sdk.  So I'm not sure why I had to run it twice to get the latest mojo_services package:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart

**Comment by eseidelGoogle** [comment]
Here is the transcript from my terminal when I hit this: https://gist.github.com/eseidelGoogle/3569de4dc06a106b5d0b

**Comment by eseidelGoogle** [comment]
It may be related to how those two packages come in through dependencies:

```
|-- flutter 0.0.21
|   |-- sky_services 0.0.99
|   |   '-- mojo_sdk 0.2.20
|   |       |-- mojo 0.4.17
|   |       '-- mojo_services 0.4.23
|   |           '-- mojo...
```

**Comment by eseidelGoogle** [comment]
Ahha!  From `flutter/pubspec.yaml`:

```
deps:
  sky_engine:
    path: ../../bin/cache/pkg/sky_engine
  sky_services:
    path: ../../bin/cache/pkg/sky_services
```

I suspect that we need to populate the flutter cache *after* syncing the flutter sdk before we run pub upgrade!  @devoncarew @abarth

**Comment by abarth** [comment]
Yeah, makes sense.  /me will fix.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/2955
