### ISSUE TITLE
Switch button

### ISSUE THREAD

**Issue by mishubham** [flutter/flutter#29548]
my switch button value is not set stable when i clicking on it , the button value is true but when i'm going on back page and return on same page the value is false then how to solve this issue..!!

**Comment by tomalabaster** [comment]
Can you provide the minimum code required to recreate the issue please?

**Comment by mishubham** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_app_arlu/notification_sound.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(
          // Column is also layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: RaisedButton(
        onPressed:(){

          Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => NotificationAndSound()),
          );
        },
        child: Icon(Icons.add),
      ),
    );
  }
}

**Comment by mishubham** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_app_arlu/privateChatNotifi.dart';

class NotificationAndSound extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _NotificationAndSoundState();
}

class _NotificationAndSoundState extends State<NotificationAndSound> {

  bool _privatechat = true;
  void _privateChat(bool privatechat) {
    setState(() {
      _privatechat = privatechat;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Notification And Sounds"),
        backgroundColor: Colors.lightBlue,
      ),
      body: new Padding(
        padding: new EdgeInsets.symmetric(vertical: 0.0, horizontal: 0.0),
        child: new ListView(
          children: <Widget>[
            new ListTile(
              title: new Text(
                "Notification for chat",
                style: TextStyle(
                    color: Colors.lightBlue, fontWeight: FontWeight.bold),
              ),
            ),
            new ListTile(
              title: new Text(
                "Private Chats",
              ),
              subtitle: new Text("Tap to change"),
              onTap: () {
                Navigator.push(
                    context,
                    new MaterialPageRoute(
                        builder: (context) => privateChatNotifi()));
              },
              trailing: new Switch(
                  value: _privatechat,
                  onChanged: _privateChat
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by mishubham** [comment]
when i navigate from main page to notification page and set switch button off and after goto back page and then return to the notification page the switch is on

**Comment by anticafe** [comment]
Hmm, I notice when initialize `NotificationAndSound` widge then you set `bool _privatechat = true;`. Should it cause next time you open that widget, the Switch is on by default?

**Comment by mishubham** [comment]
but when i set only _privatechat only as bool _privatechat ; then it will gives error

**Comment by mishubham** [comment]
@tomalabaster @anticafe  i solve that issue by using this logic


import 'package:flutter/material.dart';
import 'package:flutter_app_arlu/privateChatNotifi.dart';
import 'package:shared_preferences/shared_preferences.dart';

class NotificationAndSound extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _NotificationAndSoundState();
}

class _NotificationAndSoundState extends State < NotificationAndSound > {

  bool _privatechat = true;

  @override
  void initState() {
    _loadswitchValue();
    super.initState();
  }


  _loadswitchValue() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      _privatechat =(prefs.getBool('counter10')) ??false;
    });
  }

  Future<bool> _savenswitchValue() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    setState(() {
      prefs.setBool('counter10', _privatechat);
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("Notification And Sounds"),
        backgroundColor: Colors.lightBlue,
      ),
      body: new Padding(
        padding: new EdgeInsets.symmetric(vertical: 0.0, horizontal: 0.0),
        child: new ListView(
          children: <Widget>[
            new ListTile(
              title: new Text(
                "Notification for chat",
                style: TextStyle(
                    color: Colors.lightBlue, fontWeight: FontWeight.bold),
              ),
            ),
            new ListTile(
              title: new Text(
                "Private Chats",
              ),
              subtitle: new Text("Tap to change"),
              onTap: () {
                Navigator.push(
                    context,
                    new MaterialPageRoute(
                        builder: (context) => privateChatNotifi()));
              },
              trailing: new Switch(
                  value: _privatechat,
                  onChanged: (bool value) {
                    setState(() {
                      _privatechat = value;
                      _savenswitchValue();
                    });
                  }),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by tomalabaster** [comment]
@mishubham cool. It looks like the issue was that you weren't persisting the value of the Switch when it changes. I reckon this issue could be closed now.

**Comment by mishubham** [comment]
@tomalabaster yes please **Closed** **now** this issue

**Comment by mishubham** [comment]
but i have same problem with the radio button can you please help mi

**Comment by tomalabaster** [comment]
This isn't a problem with Flutter. You need to be persisting your value for the radio button like you did with the switch button.

**Comment by saravananmnm** [comment]
`@override
  void initState() {
    super.initState();
    getStatus(true);
    // WidgetsBinding.instance.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
        initialData: false,
        stream: switchStatus.stream,
        builder: (context, snapShot) {
          if (snapShot.data) {
            startLocationUpdates();
          } else {
            stopLocationUpdates();
          }
          return Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              getStatusText(snapShot.data),
              getStatusSwitch(snapShot.data)
            ],
          );
        });
  }

  Widget getStatusText(bool status) {
    return Container(
      alignment: Alignment.center,
      child: Text(
        status ? StringConstant.Available : StringConstant.Offline,
        style: TextStyle(
            fontSize: 18.0,
            color:
                status ? ColourConstant.COLOR_BLUE : ColourConstant.COLOR_GREY),
      ),
    );
  }

  Widget getStatusSwitch(bool status) {
    return Container(
      child: Switch.adaptive(
          value: status,
          onChanged: (val) {
            getStatus(val);
          }),
    );
  }
`

**Comment by saravananmnm** [comment]
when i implemented switch button from tabbar. 
switch button is not working, while include above tabbar
