### ISSUE TITLE
The debug image in the upper right corner is misplaced when the app is launched.

### ISSUE THREAD

**Issue by LeesimEverglow** [flutter/flutter#29541]
![image](https://user-images.githubusercontent.com/13388550/54515546-50714280-4997-11e9-8280-2de2aa2309e1.png)

just like this image。

i make my luanch image by using a widget without set luanch image in both iOS and Android native，but recently there has been such a problem。

**Comment by LeesimEverglow** [comment]
this only happen on iOS ，Android is right

**Comment by HansMuller** [comment]
Please provide a small self-contained app that demonstrates the problem and we'll look into it. Note also:
https://gist.github.com/ is a useful way to share the code.
