### ISSUE TITLE
ListTile has problematic height adjustment when subtitle word-wraps

### ISSUE THREAD

**Issue by timm-gatg** [flutter/flutter#29549]
This is related to:

[https://stackoverflow.com/questions/55198848/card-element-shrinks-height-when-text-is-too-long/](url)

If using ListTile with a subtitle that wraps to a third line in some cases it appears that flutter actually shrinks the ListTile. The problem is in list_tile.dart (Line 980)

`if (titleY < _minVerticalPadding ||
          (subtitleY + subtitleSize.height + _minVerticalPadding) > tileHeight) {
        tileHeight = titleSize.height + subtitleSize.height + 2.0 * _minVerticalPadding;
        titleY = _minVerticalPadding;
        subtitleY = titleSize.height + _minVerticalPadding;
      }`

In this case the tileHeight before executing this block is 72, but gets reduced to 59. While I guess for subtitle text that wraps to more than 2 lines the above code will be fine - as it guarantees to contain the text - in the case for 2 lines it reduces it to a smaller box than the default height causing an unpleasant display. I propose to include this as a special case, in which the spare space (in this case 13) gets distributed evenly on top and bottom.

**Comment by shihaohong** [comment]
@timm-gatg This happens if you do not set `ListTile`'s `isThreeLine` property to `true`. 

See the [List tile docs](https://docs.flutter.io/flutter/material/ListTile-class.html) for more info
Otherwise, see the [Material spec](https://material.io/design/components/lists.html#) for how `ListTile`s are intended to be used.

Please let me know if I misinterpreted your issue.

**Comment by timm-gatg** [comment]
If I set `isThreeLine` to `true` indeed the middle ListTile looks better, but the other two look worse. 
a) Which would indicate I would have to check beforehand - in some way - whether the layout would let the text overflow and depending on that set this property. I am not sure how this can be easily done.
b) Yes I read the part of the docs

> It is the responsibility of the caller to ensure that title does not wrap, and to ensure that subtitle doesn't wrap (if isThreeLine is false) or wraps to two lines (if it is true).

But that still doesn't suggest that _if_ your subtitle wraps, then the tile gets even reduced in size. I still have the opinion that this is a kind of bug, due to the fact that the ListTile height gets reduced to below the internal default height in such a case.

**Comment by rgisi** [comment]
I agree that this should be regarded as a bug.

In the meantime, you can workaround with `AutoSizeText` instead of `Text`.

**Comment by aponty** [comment]
+1 for listTiles getting smaller on subtitle wrapping being a bug. isThreeLine uses more space than I have to spare unfortunately. 

Broken line wrapping aside, how about a way to specify no wrapping? I know we can do that in the text widget but it's kinda implied that the listTile does it. A subtitle wrapping to any number of lines by default seems at odds with isThreeLine = false. A line that wraps to 2+ lines might not technically be a new line (?) but it's a natural presumption. 

Here's a fix to disable line wrapping and save future googlers a second; didn't actually need to specify maxLines, just an overflow handler in the Text widget

```
ListTile(
    leading: yourLeading,
    title: yourTitle,
    onTap: (){},
    subtitle: Text(
        someLongString,
        overflow: TextOverflow.ellipsis,
    ),
);
```
