### ISSUE TITLE
After flutter's page is clicked faster, it will not respond to click events and not be bouncing.

### ISSUE THREAD

**Issue by dacaiguoguogmail** [flutter/flutter#29547]
After flutter's page is clicked faster, it will not respond to click events.

**Comment by dacaiguoguogmail** [comment]
flutter --version
```
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (5 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by dacaiguoguogmail** [comment]
A bit similar to this issue https://github.com/flutter/flutter/issues/26637

**Comment by dacaiguoguogmail** [comment]
**trigger is:**
Click the button (jump to the native page) while scrolling flutter page

**Comment by iapicca** [comment]
Hi @dacaiguoguogmail 
the issue you linked [above](https://github.com/flutter/flutter/issues/29547#issuecomment-474168942) is related to a platform view.

If you are still experiencing the issue with the latest stable (or above)
Can you please provide your `flutter doctor -v`
and a minimal complete reproducible code sample.
Thank you

**Comment by darshankawar** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
