### ISSUE TITLE
how do i draw area using postal code in android map

### ISSUE THREAD

**Issue by FlutterForefront** [flutter/flutter#29550]

**Comment by FlutterForefront** [comment]
![Untitled](https://user-images.githubusercontent.com/47133806/54531405-34779c00-49ab-11e9-98e5-d949e456cddb.png)

**Comment by FlutterForefront** [comment]
like this

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We cannot provide personal support here. Thanks!
