### ISSUE TITLE
Live Text Recognition

### ISSUE THREAD

**Issue by BasedMusa** [flutter/flutter#29559]
Haven't found anything for live text recognition yet, so I thought I'd drop in with my idea to achieve Live Text Recognition, we could use the [camera](https://pub.dartlang.org/packages/camera) plugin to get a stream of image bytes, convert it to image file and send it to [firebase_ml_vision](https://pub.dartlang.org/packages/firebase_ml_vision) to process text.

This article on [Real-time Object Detection](https://blog.usejournal.com/real-time-object-detection-in-flutter-b31c7ff9ef96) will help in understanding the approach.

**Comment by abigbro** [comment]
Byte streaming capability for the camera was added in flutter/plugins#965 by @bparrishMines .
And the demo made by @bparrishMines [here](https://github.com/bparrishMines/mlkit_demo)
 Related issue #25087 and answer https://github.com/flutter/flutter/issues/25087#issuecomment-445394130

**Comment by BasedMusa** [comment]
This seems to be the best [solution](https://github.com/bparrishMines/mlkit_demo).
