### ISSUE TITLE
App Freeze in Release Build, works perfectly in Debug 

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#29555]
Hello everyone,
I'm iterating an app I'm working on from a while;
I had several release version that always worked,
but after updating to flutter (I curse myself every day for that)
the app works perfectly in debug, but freeze in release build
(although it loads the 'homemade' splash screen)
no errors in compile time,
flutter doctor says ok,
I've pin my dependencies and added this to prevent androidX issues

```
 rootProject.allprojects {
    project.configurations.all {
         resolutionStrategy.eachDependency { details ->
             if (details.requested.group == 'androidx.core') {
                 details.useVersion "1.0.1"
             }
             if (details.requested.group == 'androidx.lifecycle') {
                 details.useVersion "2.0.0"
             }
             if (details.requested.group == 'androidx.versionedparcelable') {
                 details.useVersion "1.0.0"
             }
         }
     }
 }
```

I've tried: flutter clean,
flutter build apk --target-platform=android-arm64,
flutter build --release... nothing works
I would appreciate if you could point me in the right direction
here you can find the results of

[flutter run --verbose
flutter analyze
flutter doctor -v](url
[flutter run --verbose.txt](https://github.com/flutter/flutter/files/2978643/flutter.run.--verbose.txt)
[flutter analyze&flutter doctor -v.txt](https://github.com/flutter/flutter/files/2978644/flutter.analyze.flutter.doctor.-v.txt)
)

I also wrote on [Stackoverflow](https://stackoverflow.com/questions/55223002/flutter-app-freeze-in-build-release-work-properly-in-debug-androidx) in case you want to check it out.

thanks in advance for your help

**Comment by iapicca** [comment]
[update 19/3/2019]:
Facebook user "Momo Roro" described a similar behavior of its own app

asserting that it was caused by the inability of the app

to contact the API, it actually matches my situation,

in fact right after the splash screen my stream should receive

data from an API and route to a specific screen accordingly.

Any idea why it works in debug and not in release build?

**Comment by iapicca** [comment]
update: now everything works;
while before I was not adding internet permission and the app worked perfectly
(contacting API and everything), since the update I have to explicitly modify the manifest.
Easy fix actually:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xxx.xxx">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="xxx"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity" [...]`

Maybe notifying this change of behavior would be useful to other
developers that might experience the same unexpected changes in their app.
Thank you for your attention.

**Comment by VladyslavBondarenko** [comment]
Hi @iapicca 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
