### ISSUE TITLE
HttpServer.bind throws SocketException 

### ISSUE THREAD

**Issue by arefay** [flutter/flutter#29557]
## Steps to Reproduce

1. Attempting to launch a webview using FlutterWebviewPlugin
2. creating a "server" using

``
final StreamController<String> onCode = new StreamController();
HttpServer server =
        await HttpServer.bind(InternetAddress.loopbackIPv4, 8585);``

3. This works fine on Android Simulator, but throws the following exception when running on iOS Emulator:

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = 127.0.0.1, port = 8585`

## Logs

#0      _NativeSocket.bind (dart:io/runtime/binsocket_patch.dart:591:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1206:26)
#2      _ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1466:29)
#3      ServerSocket.bind (dart:io/runtime/binsocket_patch.dart:1457:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2520:25)
#5      HttpServer.bind (dart:_http:227:19)

flutter analyze did not produce any meaningful or related output

```
andres-mbp:rydrapp a$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.2.1 at /Users/a/documents/dev/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/a/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • Andre’s iPhone            • f97cb257a4e56c65c2245f14bb9a4e3393829154 • ios         • iOS 12.1.4
    • iPhone XR                 • 5A9700CE-BC5E-443F-AFA0-88F10F11B795     • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by AndroidMing** [comment]
this issue still exists on Channel stable, v1.9.1+hotfix.4
Where is the shared flag?
