### ISSUE TITLE
‘setInitialRoute:’ method does not work and neither flutterViewController nor flutterEngine can be released

### ISSUE THREAD

**Issue by michealstrong** [flutter/flutter#29554]
I have some problems when i add Flutter to my iOS project :
1. `setInitialRoute:` method does not work when i create flutterViewController instance with the method `initWithEngine: nibName: bundle:`.
2. To solve problem 1, create flutterViewController directly with `[FlutterViewController alloc] init]`, then `setInitialRoute:` works. In this case flutter internally automatically creates a new flutterEngine itself for every flutterViewController instance, and neither flutterViewController nor flutterEngine can be released. Although in the flutter1.2.1 version, the FlutterEngine opens a `destroyContext` method that could be used to free some of the resources held by the engine, including the flutterViewController bound to it. 

Therefore, based on question 2, I would try to  use `destroyContext` to free the resource after vc is poped, but more times, it would crash. crash log just like this:

```
(malloc: Heap corruption detected, free list is damaged at 0x60000308d0a0
*** Incorrect guard value: 61678249889951). 
```

While flutter allows multiple instances of flutterEngine to exist simultaneously, it does not seem to allow them all to call their `destroyContext`. So ,I guess that `destroyContext` would be appropriate only for a single global flutterEngine in the process, and would be called only if all of the flutter scene were removed and completely returned to native. But  I got some complicated scene transform just like:flutterVC->nativeVC->flutterVC->nativeVC… So there is: either memory does not free; Either setInitialRoute does not take effect, resulting in multiple vc rendering is the same dart page. Based on this, I understand that flutter seems to be more suitable for iOS to have only one flutterViewController, and then immerse in flutter scene after entering, and only use the pushRoute and popRoute provided by flutter for page jumping, and then pop all flutter page return to native page at once when popViewController, and then use ‘destroyContext’ method to free resource.

**Comment by xster** [comment]
Not sure I fully understood the question. @dnfield likely knows

**Comment by dnfield** [comment]
@michealstrong  - I took some liberty to reformat your content to make it a little easier to read - I hope I didn't change your intent.

I have a few comments here that I hope will help, although I'm not sure I fully understand your issue.

1. The `setInitialRoute` API is really hard to use correctly.  If we could, I would remove it - but we can't because it'd be too hard of a breaking change.  In the use case you're talking about, _you would be better off creating a custom channel to handle setting the route you want to show the next time the VC becomes visible_.  There are several reasons for this, including that it would allow you to properly set or reset other states (including the navigation stack).
2. The `destroyContext` api is dangerous.  I was reluctant to add it, because it's very easy to misuse.  You should almost never need to call it.  Unfortunately, there was some case where it needed to be called to actually release the engine.  But once `destroyContext` has been called, the Engine object should not be used anymore for any purpose.

**Comment by michealstrong** [comment]
> @michealstrong - I took some liberty to reformat your content to make it a little easier to read - I hope I didn't change your intent.
> 
> I have a few comments here that I hope will help, although I'm not sure I fully understand your issue.
> 
> 1. The `setInitialRoute` API is really hard to use correctly.  If we could, I would remove it - but we can't because it'd be too hard of a breaking change.  In the use case you're talking about, _you would be better off creating a custom channel to handle setting the route you want to show the next time the VC becomes visible_.  There are several reasons for this, including that it would allow you to properly set or reset other states (including the navigation stack).
> 2. The `destroyContext` api is dangerous.  I was reluctant to add it, because it's very easy to misuse.  You should almost never need to call it.  Unfortunately, there was some case where it needed to be called to actually release the engine.  But once `destroyContext` has been called, the Engine object should not be used anymore for any purpose.

**Comment by michealstrong** [comment]
> @michealstrong - I took some liberty to reformat your content to make it a little easier to read - I hope I didn't change your intent.
> 
> I have a few comments here that I hope will help, although I'm not sure I fully understand your issue.
> 
> 1. The `setInitialRoute` API is really hard to use correctly.  If we could, I would remove it - but we can't because it'd be too hard of a breaking change.  In the use case you're talking about, _you would be better off creating a custom channel to handle setting the route you want to show the next time the VC becomes visible_.  There are several reasons for this, including that it would allow you to properly set or reset other states (including the navigation stack).
> 2. The `destroyContext` api is dangerous.  I was reluctant to add it, because it's very easy to misuse.  You should almost never need to call it.  Unfortunately, there was some case where it needed to be called to actually release the engine.  But once `destroyContext` has been called, the Engine object should not be used anymore for any purpose.

Sorry, I didn't make myself clear. Thank you for your reply.  i wonder how i can perfectly handle memory issues and make different flutterVC show different 'Route' in the case like that nativeVC1 [pushViewController:]-to flutterVC1 [pushViewController:]-to nativeVC2 [pushViewController:]-to flutterVC2... because of the existing problems that flutterVC doesn't release and `setInitialRoute` doesn't work.

**Comment by michealstrong** [comment]
> /cc @kangwang1988 who may have some additional thoughts on this.

Sorry, I didn't make myself clear. Thank you for your reply. i wonder how i can perfectly handle memory issues and make different flutterVC show different 'Route' in the case like that nativeVC1 [pushViewController:]-to flutterVC1 [pushViewController:]-to nativeVC2 [pushViewController:]-to flutterVC2... because of the existing problems that flutterVC doesn't release and setInitialRoute doesn't work.

**Comment by michealstrong** [comment]
> @michealstrong - I took some liberty to reformat your content to make it a little easier to read - I hope I didn't change your intent.
> 
> I have a few comments here that I hope will help, although I'm not sure I fully understand your issue.
> 
> 1. The `setInitialRoute` API is really hard to use correctly.  If we could, I would remove it - but we can't because it'd be too hard of a breaking change.  In the use case you're talking about, _you would be better off creating a custom channel to handle setting the route you want to show the next time the VC becomes visible_.  There are several reasons for this, including that it would allow you to properly set or reset other states (including the navigation stack).
> 2. The `destroyContext` api is dangerous.  I was reluctant to add it, because it's very easy to misuse.  You should almost never need to call it.  Unfortunately, there was some case where it needed to be called to actually release the engine.  But once `destroyContext` has been called, the Engine object should not be used anymore for any purpose.

Sorry, I didn't make myself clear. Thank you for your reply. i wonder how i can perfectly handle memory issues and make different flutterVC show different 'Route' in the case like that nativeVC1 [pushViewController:]-to flutterVC1 [pushViewController:]-to nativeVC2 [pushViewController:]-to flutterVC2... because of the existing problems that flutterVC doesn't release and setInitialRoute doesn't work.

**Comment by dnfield** [comment]
You should be able to release the FlutterViewController, but if you fully release it and the engine you'll lose whatever state it had (and I'm not sure you can release it when you do Native->Flutter->Native->Flutter).

In this case though, you don't want setInitialRoute - you almost definitely want a custom MessageChannel to tell Flutter what it should be displaying before you show the ViewController.  See an example of that https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_add2app/ios_add2app/MainViewController.m#L79 and https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_add2app/flutterapp/lib/main.dart#L30

**Comment by michealstrong** [comment]
> You should be able to release the FlutterViewController, but if you fully release it and the engine you'll lose whatever state it had (and I'm not sure you can release it when you do Native->Flutter->Native->Flutter).
> 
> In this case though, you don't want setInitialRoute - you almost definitely want a custom MessageChannel to tell Flutter what it should be displaying before you show the ViewController. See an example of that https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_add2app/ios_add2app/MainViewController.m#L79 and https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_add2app/flutterapp/lib/main.dart#L30

ok, Thank u very much!

**Comment by monzy613** [comment]
@dnfield  Hi, I got a similar situation. When I pop back from FlutterViewController to native, FlutterViewController and FlutterEngine just wont release, and when I call destroyContext, app will crash with EXC_BAD_ACCESS on the line I call destroyContext. I wonder how can I release FlutterEngine when I will not use it any more, it has about 70m memory usage.

**Comment by monzy613** [comment]
@dnfield Thanks! I will have a try

**Comment by monzy613** [comment]
@dnfield The problem is, how can I call destroyContext when I even dont have a reference on FlutterEngine? I want to call destroyContext is just because I want to release FlutterEngine and FlutterViewController, neither engine nor controller is released after I dismiss flutterViewController.

**Comment by leonlu** [comment]
@monzy613 Please try
```let flutterEngine = FlutterEngine(name: "engine.flutter.vira", project: nil, allowHeadlessExecution: false)!
    let flutterVC = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)!
```
Presenting the vc then dismiss it, and you will find the flutterVC is deallocated, and you do not need to call destroyContext any more.

**Comment by monzy613** [comment]
@leonlu it really works! Thanks!

**Comment by xujunquan** [comment]
> I have some problems when i add Flutter to my iOS project :
> 
> 1. `setInitialRoute:` method does not work when i create flutterViewController instance with the method `initWithEngine: nibName: bundle:`.
> 2. To solve problem 1, create flutterViewController directly with `[FlutterViewController alloc] init]`, then `setInitialRoute:` works. In this case flutter internally automatically creates a new flutterEngine itself for every flutterViewController instance, and neither flutterViewController nor flutterEngine can be released. Although in the flutter1.2.1 version, the FlutterEngine opens a `destroyContext` method that could be used to free some of the resources held by the engine, including the flutterViewController bound to it.
> 
> Therefore, based on question 2, I would try to use `destroyContext` to free the resource after vc is poped, but more times, it would crash. crash log just like this:
> 
> ```
> (malloc: Heap corruption detected, free list is damaged at 0x60000308d0a0
> *** Incorrect guard value: 61678249889951). 
> ```
> 
> While flutter allows multiple instances of flutterEngine to exist simultaneously, it does not seem to allow them all to call their `destroyContext`. So ,I guess that `destroyContext` would be appropriate only for a single global flutterEngine in the process, and would be called only if all of the flutter scene were removed and completely returned to native. But I got some complicated scene transform just like:flutterVC->nativeVC->flutterVC->nativeVC… So there is: either memory does not free; Either setInitialRoute does not take effect, resulting in multiple vc rendering is the same dart page. Based on this, I understand that flutter seems to be more suitable for iOS to have only one flutterViewController, and then immerse in flutter scene after entering, and only use the pushRoute and popRoute provided by flutter for page jumping, and then pop all flutter page return to native page at once when popViewController, and then use ‘destroyContext’ method to free resource.

一模一样的问题，老哥解决了吗

**Comment by wys619** [comment]
> @leonlu it really works! Thanks!

Hi ! iTry this but got the same error result as using "destroyContext", did it really work for you or I miss something? thanks!
