### ISSUE TITLE
I want Keep my TabPage status. 

### ISSUE THREAD

**Issue by 96Rick** [flutter/flutter#29553]
- My app has three TabPages. 

-  I have already kept the page state by add the AutomaticKeepAliveClientMixin. 
- when the page is swiped, but when I push a new page on one of the pages and pop back to the current TabPage, 
- then i slide to the other TabPage again and the page will re-init. AutomaticKeepAliveClientMixin will be invalid, this is my issue.
- Is there any way to keep my three TabPages in a state, only init once? Thank a lot

**Comment by msw333** [comment]
I can confirm it within my app and have the exact same request.

**Comment by 96Rick** [comment]
> 我可以在我的应用程序中确认它并具有完全相同的请求。
Do you have any solution of this issue ?

**Comment by msw333** [comment]
No - no chance to stop the rebuild for me.

**Comment by shuicheng** [comment]
我也遇到同样的问题。。。

**Comment by msw333** [comment]
Superclass has no method named 'build'.
        super.build(context);

**Comment by lifetin** [comment]
我也遇到同样的问题,
PageView中有a,b,c,d子页面,已经加了AutomaticKeepAliveClientMixin,
我依次点击abcd没有问题,
当我在d页面Navigator.push新页面后,马上abc页面全都dispose了,
当我返回d后,再点击abc,全都是重新initState了

这个问题问了一些人,有不少人遇到,望flutter团队进行检测,谢谢
---------------------------------------------------------------------------------
I have the same problem.
PageView has a, b, c, D sub-pages, and AutomaticKeepAliveClient Mixin has been added.
I click ABCD one by one, no problem.
When I got a new page on Navigator. push, all the ABC pages were dispose D.
When I return to D and click on abc, it's all initState again.
This question has been asked by some people. Many people have encountered it. I hope the flutter team will test it. Thank you.

**Comment by lifetin** [comment]
我看了,用了AutomaticKeepAliveClientMixin原来必须要加super.build(context);才行
![44](https://user-images.githubusercontent.com/10474968/59259961-46e13900-8c6d-11e9-84be-84be5873178d.png)

**Comment by 96Rick** [comment]
我已经解决了这个问题，如果需要使用AutomaticKeepAliveClientMixin确实需要加super.build(context); 
谢谢各位

————————————————————

I have solved this problem, if you need to use AutomaticKeepAliveClientMixin, you really need to add super.build (context); 
Thank you all
