### ISSUE TITLE
First frame with a platform view on iOS is janky

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#29573]
On iOS with GL rendering there's jank in the first frame a platform view is added, screen recording: https://photos.app.goo.gl/TUm6nSiENM2WT1ED6

The following minimal might help debugging with a simple layer tree:

```dart
class Glitch extends StatefulWidget {
  @override
  State<Glitch> createState() => GlitchState();
}

class GlitchState extends State<Glitch> {
  bool showMap = false;

  @override
  Widget build(BuildContext context) {
   return Column(
     children: <Widget>[
       Text('Hello'),
       Container(
         width: 300,
         height: 300,
         child: showMap ?
         GoogleMap(
           initialCameraPosition: CameraPosition(target: LatLng(0, 0)),
         )
             : null,
       ),
       GestureDetector(
         onTap: () {
           setState(() {
             showMap = !showMap;
           });
         },
         child: Text('TOGGLE SHOW MAP'),
       ),
     ],
   );
  }
}
```

The following engine patch prevents a second frame from being pumped right after a platform view is attached: https://github.com/amirh/engine/commit/ee9ebb20f60737f70749bd962368eeb08cd10459

With that patch and the sample code above the bad frame remains stable on the screen, hopefully that makes debugging easier.

**Comment by iskakaushik** [comment]
Should be fixed by #8218
