### ISSUE TITLE
Path serialization

### ISSUE THREAD

**Issue by DeRealMorgan** [flutter/flutter#29570]
I do have (yet another) issue with Paths.

My goal: I am trying to serialize my Path objects and send them to another client so that the client can display exactly the same Path.

This seems not doable at the moment as I cant access anything from the Path object.

I need a Path object instead of a plain array of captured points as this will decrease the packet size a lot - which is a lot of money I dont have to spend for a more powerful server.
Also there will be some interaction on the other client (like Path.combine()) which is not (easily ?) achievable without having the actuall Path object.

**Comment by dnfield** [comment]
Related: #18458 

Can you explain a bit how you end up with a `Path` that you don't know anything else about?

Where I ended up arriving at with this previously is that whatever I use to create the path can just as easily create a serialization object.  You could achieve that with a decorator around path.

A major challenge to making paths serializable out of the box is how to do it in a stable way that we won't break as we optimize things - and that will have enough information for other consumers of your serialized version to deserialize the path properly.

**Comment by DeRealMorgan** [comment]
What do you mean by 
> decorator around path
?

**Comment by dnfield** [comment]
Instead of working directly with a Path, work with a class that wraps the methods of Path and stores the numbers you pass in to your preferred serrialization format.

**Comment by csells** [comment]
@DeRealMorgan did you have any luck with this work-around?

**Comment by DeRealMorgan** [comment]
@csells Flutter isnt providing a way to steeam audio so we paused the project / moved it to a better framework.
