### ISSUE TITLE
Make thickness of ScrollBar customable

### ISSUE THREAD

**Issue by danieldai** [flutter/flutter#29576]
The thickness of ScrollBar is too big for some cases, I noticed the thickness it's an internal property of ScrollBar, can flutter expose that property through ScrollBar parameter?

**Comment by tudor07** [comment]
We should be able to customize the `Scrollbar` more. (thickness, color, etc.)

**Comment by kinex** [comment]
I agree the fixed thickness of 6 pixels looks ugly especially if the scrolled content is short. Here is one  [workaround](https://stackoverflow.com/questions/56135015/how-to-change-scrollbars-thickness/56135730#56135730), but it is not perfect (it will hide content in the right edge of the screen).

I would like to customize also the Scrollbar's margin from the right edge of the ListView (Scrollbar's child). For an example see Android OS settings app which has a small margin (maybe 3 pixels) between the scrollbar and the right edge of the screen.
