### ISSUE TITLE
Some classes in the docs don't list their subclasses

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2958]
For example, the widgets version of RenderObjectWidget doesn't have subclasses, but the material version does?:
http://docs.flutter.io/flutter/widgets/RenderObjectWidget-class.html
http://docs.flutter.io/flutter/material/RenderObjectWidget-class.html

**Comment by eseidelGoogle** [comment]
FYI @keertip, @Hixie do you suspect this is our usage of dartdoc, or a bug in dartdoc?

**Comment by Hixie** [comment]
Not sure. I don't really see what we could be doing to make this go wrong, though.

**Comment by keertip** [comment]
Not sure. Will have to take a look at the flutter library to figure out if it is an issue with dartdoc.

**Comment by eseidelGoogle** [comment]
@Hixie is this still an issue?  If so, we should probably move it to the dartdoc repo. :)

**Comment by Hixie** [comment]
This is actually worse now because we only have the version that doesn't list the inheritance.

Filed https://github.com/dart-lang/dartdoc/issues/1334
