### ISSUE TITLE
API doc is so less

### ISSUE THREAD

**Issue by toberole** [flutter/flutter#29588]
API doc is so less and API sample，but flutter is so good

**Comment by goderbauer** [comment]
Can you list some specific widgets for which you'd like to see API examples? What kind of examples would you like to see there? That would make this report more actionable for us.

**Comment by kabyanil** [comment]
one thing I struggle the most is dealing with multiDex issue. It's not exactly the right place to put it in the API docs, but a workaround, if provided in the flutter docs, could help a lot of developers solve this common issue!
