### ISSUE TITLE
Error: Error when reading 'bin/main.dart': The system cannot find the path specified.

### ISSUE THREAD

**Issue by RashidIshaque** [flutter/flutter#29589]
Error: Error when reading 'bin/main.dart': The system cannot find the path specified.
i am using the windows 10 , the vs code shows the above results when i debug the code, one thing that i have used to terminal in the vs Code, when i hit the "flutter run" the emulators show the app but it did not show the hot reload and and other options, terminal show that it may take unsuspected long time 
these are the output 
`rror: Error when reading 'bin/main.dart': The system cannot find the path specified.
Ignoring error posting over WebSocket.
Bad state: StreamSink is closed
#0      _StreamSinkImpl.add (dart:_http/http_impl.dart:536:7)
#1      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1213:11)
#2      WebSocketClient.post (dart:vmservice_io/server.dart:78:18)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
`

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
@RashidIshaque is your `main.dart` file in `bin/` or is it under `lib/`?

**Comment by RashidIshaque** [comment]
main.dart is in the lib/ folder

**Comment by YuriiChornyi** [comment]
The solution is to delete .**vscode** folder inside your project

**Comment by DanTup** [comment]
Can you post the contents of your `.vscode/launch.json` file here? Unless you need to customise something, it's best *not* to have a `launch.json` (deleting your `.vscode` may be safe if it doesn't have other things in it, like tasks or settings you've configured).

I tried to repro this, but if I open a Flutter app and set `program` to `bin/main.dart` in `launch.json` I actually get a slightly different message:

```
Error: Error when reading 'bin/main.dart': No such file or directory
Exited (sigint)
```

So I'd be interested to know exactly how you're set up. It might be something I can improve handling of in the VS Code extension.

**Comment by YuriiChornyi** [comment]
@DanTup after that error and deleting .vscode folder all works pretty fine, now there is no .vscode folder. I suspect that steps to repro are next:

- debug flutter app on device
- unplug device
- plug device and start debug again

**Comment by DanTup** [comment]
@YuriiChornyi can you reproduce the issue with those steps?

**Comment by khalchev91** [comment]
@RashidIshaque @YuriiChornyi in launch.json under .vscode in your project, changing it from "bin/main.dart" to "lib/main.dart" fixed it for me 
![image](https://user-images.githubusercontent.com/22421233/55268668-f0618280-5259-11e9-89b5-10fb2620d58c.png)

**Comment by DanTup** [comment]
If that's all that's in your `launch.json` you should also be able to just delete the whole file, as those are all the default settings (`program` will default differently depending on whether you have a Flutter or Dart project open though).

**Comment by FranceGuedal** [comment]
Hi thanks, this solution helped me!

**Comment by allenjohnson8** [comment]
how to know where is main.dart located,it is neither in bin nor lib .when i search main.dart so many file are coming ,they are from the apps that i created.dart is installed properly ,dart command is running in terminal as it should be.

**Comment by DanTup** [comment]
@allenjohnson8 `main.dart` is usually the entry point for your project. If you create a Flutter app using `flutter create` then it will create a `lib/main.dart` file.

If you're having issues launching projects from VS Code, please open an issue in the [Dart-Code](https://github.com/Dart-Code/Dart-Code) describing the problem you're having and including some details of the project you have open.

Thanks!

**Comment by codeniklabs** [comment]
@YuriiChornyi Thank you, thank you, thank you!!!!

**Comment by mohammad97mha** [comment]
> The solution is to delete .**vscode** folder inside your project

thanks bro.it was really **_helpfull_**
@YuriiChornyi

**Comment by jordanvr** [comment]
I found that if I opened the folder above the Flutter root in VS Code, any launch,json created for Flutter would default to "bin/main.dart", rather than finding main where it actually is in "appname/lib/main.dart".

So make sure you have the root folder as the open folder. The plugin should probably find where main.dart is rather than hard coding it, unless VS code is only supposed to work in the root folder, but in that case it should probably refuse to build on a non-configured attempt as well.

**Comment by DanTup** [comment]
> I found that if I opened the folder above the Flutter root in VS Code, any launch,json created for Flutter would default to "bin/main.dart", rather than finding main where it actually is in "appname/lib/main.dart".

The issue when it's in a sub-folder, is that there could be any number of projects and we wouldn't know which to launch. The value inserted into the `launch.json` is intended to be customised to match your entry point if you have a multi-project folder (if you're opening a single project, you generally shouldn't need a `launch.json` at all).

**Comment by LucheGames** [comment]
Thanks DanTup. Can confirm, only opening the specific flutter project folder in VS Code fixed debug problems for me. I was having trouble when opening a global folder of many flutter projects. Not an obvious bug to squash, VS error message only flashed for a milisecond.

**Comment by benCaoili** [comment]
Error: Error when reading 'lib/main.dart': The system cannot find the path specified.
Exited (254) pls help me about this issue thanks am appreciated =).......>

**Comment by DanTup** [comment]
@benCaoili it sounds like your `launch.json` may have a bad path in the `program` field. Try removing it (if you haven't customised it, you shouldn't need a launch.json at all). If you still can't make it work, please open an issue at https://github.com/Dart-Code/Dart-Code or ping on [the Dart-Code discord server](https://discord.gg/xSTPEqm) for troubleshooting.

**Comment by naseerdeveloper** [comment]
By deleting .vscode in my flutter project folder ,it is recovered to its normal state and solved my problem.
thanks bro.....

**Comment by bl4ckck** [comment]
I don't know if this is a bug or not, I have 2 projects in the same workspace, when I debug on main dart the vscode automatically create .vscode folder on my another project. Try close your another project from your workspace.

**Comment by DanTup** [comment]
@bl4ckck it's hard to say without more info, but generally if something seems unexpected then it's probably a bug (or at least something we may be able to improve). If you can open a new issue with more details of what you're seeing (screenshots are often a big help) I can take a look. Thanks!

**Comment by bl4ckck** [comment]
@DanTup This is the screenshot. When I press F5 and there are 2 project folders in my workspace, launch.json is automatically created in my other project, not in my flutter project. Is this my own fault or what? I don't really understand about this.

![Screenshot_2020-01-31_00-30-20](https://user-images.githubusercontent.com/25675947/73474893-3a753200-435d-11ea-8a3d-45369b08249a.png)

**Comment by DanTup** [comment]
@bl4ckck Looks like you deleted your comment, but FWIW from your screenshot it looks like a multi-root workspace. For a single-root workspace, everything is handled by the extension, but with multi-root you need to select which root to launch for on the Debug side bar. If you're still having issues, please file a bug in the [Dart-Code](https://github.com/Dart-Code/Dart-Code) repo. Thanks!

**Comment by Hannyul** [comment]
Hello, 
I faced this error many times but i'm interested to know what is the cause of this error? 
Thanks.

**Comment by DanTup** [comment]
@Hannyul if you're on the latest version of the VS Code plugin, it should show this warning:

> Your launch config references a program that does not exist. If you have problems launching, check the "program" field in your ".vscode/launch.json" file.

You should modify your `.vscode/launch.json` to correct the `program` field (probably `lib/main.dart`) or if you have not customised the file, you may be able to just delete the `launch.json` entirely, and then hit `F5` and it'll automatically find the right file.

If this still doesn't help, please open an issue at https://github.com/Dart-Code/Dart-Code, since comments on closed issues are easily missed. Thanks!

**Comment by carb0nknight** [comment]
Does VS Code generate the launch.json file automatically? If so what triggers the creation? I've been working on a project for the past few weeks with no issues, then when I opened it today got this error. I hadn't noticed the .vscode folder nor the launch.json file before today.

**Comment by DanTup** [comment]
VS Code can auto-generate the file under some circumstances - it used to do it a lot, but now it mostly should only happen if you:

- Explicitly run the command to edit the launch config
- Click the "create launch.json" link on the debug side bar
- Try to run a project that the Dart extension is unable to find an entry point for (it'll be generated and a notification telling you to customise the `program` part). This could be from opening a *parent* folder of your app, and trying to launch without a project file open

Usually when it is generated, it would have `lib/main.dart` if we correctly detected your project as Flutter though.

**Comment by Areeb786123** [comment]
"appname/lib/main.dart".

**Comment by Areeb786123** [comment]
use this  "appname/lib/main.dart".

**Comment by Areeb786123** [comment]
use this  "appname/lib/main.dart". in your launch.json file program

**Comment by prateeklovely** [comment]
delete the .vscode folder

**Comment by DanTup** [comment]
If people are frequently seeing a `.vscode/launch.json` file being created for a Flutter project that contains `bin/main.dart` (causing issues when trying to run), please do file an issue at https://github.com/Dart-Code/Dart-Code so I can try to get to the bottom of it. Thanks!

**Comment by Stephyo** [comment]
> The solution is to delete .**vscode** folder inside your project

Need do both. 
delete .**vscode** folder
and change config file name to : lib/main.dart

It works. Thanks everyone.

**Comment by Sp4Rx** [comment]
How to configure separate entry point for android studio? I'm running from the android folder.
```
Error when reading 'lib/main.dart': No such file or directory
```
I dont have `'main.dart` file we renamed it to different one for better understanding of our project.

**Comment by DanTup** [comment]
@Sp4Rx this repository is for the VS Code extensions. Unfortunately I'm not familiar enough with Android Studio to know how to configure its entry points.

**Comment by DanTup** [comment]
Oops, too many tabs open 🙈

**Comment by praveensick** [comment]
yeah! deleting .vscode folder....worked for me ...thanks btw

**Comment by juanlealpe** [comment]
Elimine la carpeta y de doy F5 y vuelve y se restablece la misma que debo hacer para que no me pase mas ??

**Comment by robertlml** [comment]
-Right click your main.dart then click copy path in launch.json
- In "program": paste your full path.

For example
"program": 
C:/Users/Usuario/Desktop/.../flutter/project name/lib/main.dart

**Comment by mamadOuologuem** [comment]
No need to provide an absolute path. That will be hard to maintain if you are with a team.

For a monorepo, you use:
```
"program": "packages/mobile/lib/main.dart",
```

**Comment by kaksv** [comment]
For me instead of clicking on run, then start debugging, i instead click on terminal, then cd "root directory" and use flutter run command

**Comment by AnmolkumarShah** [comment]
Hello Everyone, if you are facing this problem kindly check the following steps
1. Try to give a perfect path to your main.dart file in flutter app from  launch.json file
   if it does not work then from the terminal type
    1. flutter clean
    2.flutter run

**Comment by Brownpinger97** [comment]
Hi guys , Im new to flutter i have found this exception while im runnng main.dart file how can i get rid of these

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:177)        
        at java.net.Socket.connect(Socket.java:507)                          
        at java.net.Socket.connect(Socket.java:457)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:365)  
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:477)  
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:280)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:337)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:176)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:736)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:162)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:905)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
