### ISSUE TITLE
flutter 中文 两端对齐无效 textAlign: TextAlign.justify, 对于中文无效

### ISSUE THREAD

**Issue by clagla** [flutter/flutter#29583]
From URL: https://www.flutterchina.club/get-started/install.md

**Comment by YuzhouZhang** [comment]
烦请按照模板反馈问题。

**Comment by ssddi456** [comment]
same problem 

```dart
 Text( '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？', textAlign: TextAlign.justify)
```

expect
![图片](https://user-images.githubusercontent.com/997812/56895294-47f24880-6abb-11e9-8356-e18d6ab721d5.png)

actually 
![图片](https://user-images.githubusercontent.com/997812/56895238-124d5f80-6abb-11e9-8390-8c698b535a7f.png)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.9-pre.44, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.0)
[√] VS Code, 32-bit edition
[√] Connected device (2 available)

• No issues found!

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues

**Comment by onlyloveyd** [comment]
请问下这个问题解决了嘛？

**Comment by guojiahying** [comment]
麻烦一下，现在遇到了一样的问题，求解决方法

**Comment by guojiahying** [comment]
> same problem
> 
> ```dart
>  Text( '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？', textAlign: TextAlign.justify)
> ```
> 
> expect
> ![图片](https://user-images.githubusercontent.com/997812/56895294-47f24880-6abb-11e9-8356-e18d6ab721d5.png)
> 
> actually
> ![图片](https://user-images.githubusercontent.com/997812/56895238-124d5f80-6abb-11e9-8390-8c698b535a7f.png)
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel master, v1.5.9-pre.44, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.0)
> [√] VS Code, 32-bit edition
> [√] Connected device (2 available)
> 
> • No issues found!

现在这边你处理好了吗，请教下

**Comment by Sing1** [comment]
如果只是简单的注册页面的固定文案的话，可以用这种方法曲线救国，设置文字间间距

Text('身份证号',style: TextStyle(fontSize: 18.0)),
Text('注册',style: TextStyle(fontSize: 18.0, letterSpacing: 18.0 * 2)),
Text('手机号',style: TextStyle(fontSize: 18.0, letterSpacing: 18.0 / 2)),

**Comment by fzyzcjy** [comment]
Any updates?
