### ISSUE TITLE
I'm having issue creating ios app from xcode

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#29599]
I have a developed app but when I'm creating ios archive it creates the ipa but when I transfer it to my iPhone it comes up with no icon and doesn't open.
This happens when I choose "iOS app store" option but ipa created by "development" option works fine. Is this suppose to not work or am I doing something wrong?

Doctor: ```

[✓] Flutter (Channel master, v1.3.12, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
To run an IPA on an iphone it needs to be signed and uploaded through the app store. There are exceptions for local development, which only needs to be signed locally.

**Comment by Sarthaktydy** [comment]
So I must upload the ipa to the app store in order to use it?
