### ISSUE TITLE
flutter: EXCEPTION CAUGHT BY GESTURE

### ISSUE THREAD

**Issue by dizhanbin** [flutter/flutter#29595]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
@dizhanbin we need the stack trace produced by the exception to help you, as well as the output of `flutter doctor -v`. In this case though, it is likely due to passing `null` to something that expects only `true` or `false`.

**Comment by dizhanbin** [comment]
Thank you.
I solved it because the buildcontext expired.
