### ISSUE TITLE
Underlines in tab titles can set themselves to an incorrect width, do not initially smoothly animate

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2959]
They start off correct, but if I start swiping to the side, the underline _jumps_ to its target width (it doesn't smoothly animate), and then if I don't complete the swipe, and let the current view/panel fall back into place, the underline stays too wide.

Here's a picture of the app "resting":

![img_20160328_141919](https://cloud.githubusercontent.com/assets/5479/14090613/42f169f4-f4f0-11e5-8e4f-8ea90727017c.jpg)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by sethladd** [comment]
```
~/Code/flutter/examples/material_gallery[master*] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision cc9b140 (4 hours ago); engine revision f790903
```

**Comment by mpcomplete** [comment]
I spent some time looking at this, and I think it has to do with an inconsistency with how we treat the animation's completion value. Some places define the range as "0.0 = tab to left of selected tab, 0.5 = selected tab, 1.0 = tab to right of selected tab", while others define "0.0 = selected tab, 1.0 = next tab in whichever direction the animation is headed". I got confused about why we have this distinction and gave up. @HansMuller might remember why we did it this way.

**Comment by HansMuller** [comment]
I believe that if you're dragging the TabBarView then you are varying the animation value between 0.0 - 0.5 - 1.0, which implies moving the indicator to the left and right of the selected tab. When we're animating to a new selected tab, then the animation goes from 0.0 to 1.0 and that implies moving the indicator and scrolling (if necessary).

It's been a while so I'll check to see what I remember matches the current implementation.

**Comment by mpcomplete** [comment]
Yeah, I think you're right. It seems unnecessarily confusing to me, since the code has to understand the two different states. Would it make sense if the TabBarView varied from 0.0 to 1.0 as well, where 0.0 is always "selected tab", and 1.0 changes based on the direction of the scroll?

**Comment by HansMuller** [comment]
I'm not sure. If we have tabs A B C D and is B currently selected then dragging from B towards C means varying the animation value from 0.0 to 1.0. Changing direction just reduces the animation value towards 0.0.  Dragging between B and A would be similar. So to interpret the animation's value you need to know that you're dragging and which side of the selected tab you're on.

**Comment by sethladd** [comment]
Updated _slow-mo_ movies:

Gallery app: https://dl.dropboxusercontent.com/u/316685/for-github-issues/IMG_0008.MOV

(notice the quick jump of the underline)

Play News app: https://dl.dropboxusercontent.com/u/316685/for-github-issues/IMG_0009.MOV

(notice the underline smoothly animates to its final length)
