### ISSUE TITLE
TextField's cursor with Japanese character

### ISSUE THREAD

**Issue by LouisShark** [flutter/flutter#29592]
![%XL}72%NC91X17E$7((J03Y](https://user-images.githubusercontent.com/18005609/54590923-1fab0f00-4a64-11e9-93e4-4de6120fd3b0.jpg)
![{JQXMTWU~O17}F`Y335JHQB](https://user-images.githubusercontent.com/18005609/54590926-220d6900-4a64-11e9-806c-93b64e305e12.jpg)

**I think my textField's cursor behavior are strange and are not alignment**

**below is my flutter doctor**

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
    • Flutter version 1.2.1 at F:\flutter\flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\sdk
    • Java binary at: D:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\as
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • SM G9350 • 58fee7c4 • android-arm64 • Android 8.0.0 (API 26)

**Comment by jonahwilliams** [comment]
I think @GaryQian has recently done some work on cursor height, though I don't believe it has landed in stable yet.

**Comment by justinmc** [comment]
Gary has put in several fixes for caret height and position in the last year of this issue's life.  I'm going to close this as fixed, but if anyone still seems the problem, please comment with reproduction steps and I'll reopen.
