### ISSUE TITLE
Call State's method when widget reappears in viewport

### ISSUE THREAD

**Issue by vanelizarov** [flutter/flutter#29597]
Saying, I have a `SliverList` widget with `SliverChildBuilderDelegate`, which produces a card with custom image widget inside of it for each index. By custom image widget I mean widget that is kind of `NetworkImage`, but with support for custom caching technology. It's similar to [cached_network_image](https://pub.dartlang.org/packages/cached_network_image). 

So, the problem I'm trying to solve is that when some image fails to load and user scrolls it out from the screen, I need to retry loading this image when user for example scrolls back to it or in general when this image appears in viewport again.

Is it possible to e.g. re-call image loading function in some of the `State`'s lifecycle methods or in delegate's `builder`? Or which technique should I use in this case?

**Comment by vanelizarov** [comment]
Created question on [StackOverflow](https://stackoverflow.com/questions/55259807/flutter-call-states-method-when-widget-reappears-in-viewport)

**Comment by Hixie** [comment]
The widget will be recreated entirely when it goes outside the screen (plus a little buffer for accessibility). So the callback you're looking for is basically "initState".
