### ISSUE TITLE
Default behavior of showTimePicker is different than usual

### ISSUE THREAD

**Issue by friebetill** [flutter/flutter#29600]
## The Problem
If one compares the behavior of the time picker of different apps, for example the app [Clock](https://play.google.com/store/apps/details?id=com.google.android.deskclock&hl=en_US) or the app [Google Calendar](https://play.google.com/store/apps/details?id=com.google.android.calendar&hl=en_US) with the dialog `showTimePicker` by Flutter, one notices that they behave differently. With these apps you get directly to the minutes selection after clicking the hour. Instead, in the Flutter dialog, after clicking the hour, you have to select the minute mode in the time above and only then can you select the minute. Since the behavior does not correspond to the standard of many apps, I think it is an error of the widget. 

Now I have the option to reprogram the widget myself or create an issue. But since I suspect that many developers have the problem and it can be solved centrally by the flutter team, I decided to create an issue. 

## Steps to Reproduce

I have created a [small program](https://gist.github.com/friebetill/8afc5523962461a42d52eb220c2bd397) that lets one watch the behavior of the showTimePicker.

**Comment by HansMuller** [comment]
A change like the one you're requesting has been proposed; although the work has been deferred for a bit: https://github.com/flutter/flutter/pull/24677

**Comment by friebetill** [comment]
Thank you very much for the reference, this PR solves really exactly my request. 

I'm really looking forward to the update.
I guess the issue can then be closed.

**Comment by HansMuller** [comment]
Thanks for the report! We do pay attention to thumbs-up votes, so you may want vote for #24677.

We'll leave this open until #24677 or something similar lands.

**Comment by SwissCheese5** [comment]
This can be closed now

**Comment by HansMuller** [comment]
@SwissCheese5 Thanks for the reminder, closing this now.

CC @darrenaustin
