### ISSUE TITLE
Firebase Remote Config iOS Readme Documentation missing

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#29605]
The readme for the Flutter Firebase Remote Config Plugin has instructions for Android but not for iOS.

https://github.com/flutter/plugins/tree/master/packages/firebase_remote_config

**Comment by KeshavAdityaRP** [comment]
Yes I'm having the same issue as well

**Comment by fellow7000** [comment]
Same stuff :-/ Any roadmap on that?..

**Comment by kroikie** [comment]
@MisterJimson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1134. Any further collaboration will be done there.
