### ISSUE TITLE
Add the ability to customize the color of the checkmark in FilterChips

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#29626]
<img width="370" alt="Screen Shot 2019-03-19 at 1 36 35 PM" src="https://user-images.githubusercontent.com/23037821/54640450-0b0f4c80-4a4d-11e9-9019-5975874554c1.png">
I'd like to make it white, seeing as black doesn't always match with any color chip we choose.
Like in cases like this, where the same chip is selected
<img width="350" alt="Screen Shot 2019-03-19 at 1 45 05 PM" src="https://user-images.githubusercontent.com/23037821/54640528-41e56280-4a4d-11e9-916e-121a2c6f01a0.png">

**Comment by HansMuller** [comment]
cc @gspencergoog

**Comment by jonahwilliams** [comment]
Currently it looks like we select the checkmark color based on the theme brightness. We could allow customization of the checkmark color, or of the brightness of the checkmark, but probably not both. 

Another approach might be to use the brightness of the chip's color instead of the theme. That might be possible...

**Comment by ThinkDigitalRepair** [comment]
@jonahwilliams Why can't both be done? If the color is null, then use the brightness.

**Comment by JamesMcIntosh** [comment]
@jonahwilliams There is a similar issue with not being able to change the selected label color, it's stuck as what you supply for the labelStyle.

**Comment by SoftWyer** [comment]
You can work around this by using an Avatar and customising this to represent the tick mark, e.g. 

```
FilterChip(
   label: Text(
      "label text",
         style: TextStyle(color: Colors.red),
      ),
      avatar: isSelected ? Icon(Icons.check, color: contrastColor(Colors.red)) : null,
      // selected: isSelected,
   },
)
```

The function ```contrastColor``` just looks at the supplied colour and chooses white or black depending upon its luminescence.
