### ISSUE TITLE
Refactor Channel and Codec to be usable by platform side

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#29629]
There are already [Java](https://github.com/flutter/engine/blob/211adeac3a400d33ea2cbd9f26f809a38ff3584e/shell/platform/android/io/flutter/plugin/common/MethodChannel.java#L29) and [Objective-C](https://github.com/flutter/engine/blob/93452747fcb791d73c9c548e74db382fcc39d772/shell/platform/darwin/ios/framework/Headers/FlutterChannels.h#L157) implementations of [MethodChannel](https://github.com/flutter/flutter/blob/5169ab5974571918121fa8a7ddb0d3e0623bc987/packages/flutter/lib/src/services/platform_channel.dart#L109) and the various other Channel and Codec classes for message passing. For plugins for the web platform and Fuchsia, Dart implementations of these classes are needed to decode messages from the client side, but these classes are in `package:flutter` and so are inaccessible from the platform side.

I suggest splitting these classes out into another package, say `package:flutter_channels`, and exporting most of the classes from `package:flutter/services.dart`. Some of the classes directly use `BinaryMessages` to communicate with the platform side, these can be refactored so that the `BinaryMessages` dependency is factored out, and in `package:flutter` we can have implementations `MethodChannel` in `package:flutter` which extends a `BaseMethodChannel` from `package:flutter_channels` by using `BinaryMessages` for passing binary messages.

Once we refactor the platform channels code into a platform-independent package, we'll be able to use the same Codec code for Flutter web plugins as in the Flutter framework.

**Comment by hterkelsen** [comment]
Ping @jonahwilliams . What should I do to get this landed?

**Comment by dnfield** [comment]
See also https://github.com/flutter/flutter/issues/29230

My preference would be to split out all (or as much of) foundation as possible to avoid proliferation of lots of small packages.

**Comment by jonahwilliams** [comment]
What are the current assumptions about dart library availability in plugin code? 
Does dart:ui exists because we're compiling plugins and the application together into a single entry-point?  Or are we compiling two dart sdks and bridging them with JSON?

**Comment by Hixie** [comment]
For Web, dart:ui will be available. So this isn't necessary for Web.
For Fuchsia, this isn't necessary at all, just use FIDL directly.

I don't think we should do this.

**Comment by hterkelsen** [comment]
We discussed this last week and decided not to split the classes out to a separate package, but to instead just add the superclasses in package:flutter.

**Comment by hterkelsen** [comment]
This was closed by https://github.com/flutter/flutter/pull/30406
