### ISSUE TITLE
Hi how I can fix this problem with googlePlaces AutoComplete Api 

### ISSUE THREAD

**Issue by rostomy** [flutter/flutter#29639]
I/flutter (12407): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12407): The following assertion was thrown building Builder:
I/flutter (12407): 'package:google_maps_webservice/src/utils.dart': Failed assertion: line 30 pos 16: 'url != null': is
I/flutter (12407): not true.
I/flutter (12407): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12407): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12407): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12407):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12407): When the exception was thrown, this was the stack:
I/flutter (12407): #2      new GoogleWebService 
I/flutter (12407): #3      new GoogleMapsPlaces 
I/flutter (12407): #4      GooglePlacesAutocompleteState.initState 
I/flutter (12407): #5      StatefulElement._firstBuild 
I/flutter (12407): #6      ComponentElement.mount 
I/flutter (12407): #7      Element.inflateWidget 
I/flutter (12407): #8      Element.updateChild 
I/flutter (12407): #9      ComponentElement.performRebuild 
I/flutter (12407): #10     Element.rebuild 
I/flutter (12407): #11     StatelessElement.update 
I/flutter (12407): #12     Element.updateChild 
I/flutter (12407): #13     ComponentElement.performRebuild 
I/flutter (12407): #14     Element.rebuild 
I/flutter (12407): #15     StatelessElement.update 
I/flutter (12407): #16     Element.updateChild 
I/flutter (12407): #17     ComponentElement.performRebuild 
I/flutter (12407): #18     Element.rebuild 
I/flutter (12407): #19     ProxyElement.update 
I/flutter (12407): #20     Element.updateChild 
I/flutter (12407): #21     SingleChildRenderObjectElement.update 
I/flutter (12407): #22     Element.updateChild 
I/flutter (12407): #23     ComponentElement.performRebuild 
I/flutter (12407): #24     Element.rebuild 
I/flutter (12407): #25     StatelessElement.update 
I/flutter (12407): #26     Element.updateChild 
I/flutter (12407): #27     SingleChildRenderObjectElement.update 
I/flutter (12407): #28     Element.updateChild 
I/flutter (12407): #29     ComponentElement.performRebuild 
I/flutter (12407): #30     Element.rebuild 
I/flutter (12407): #31     StatelessElement.update 
I/flutter (12407): #32     Element.updateChild 
I/flutter (12407): #33     SingleChildRenderObjectElement.update 
I/flutter (12407): #34     Element.updateChild 
I/flutter (12407): #35     SingleChildRenderObjectElement.update 
I/flutter (12407): #36     Element.updateChild 
I/flutter (12407): #37     SingleChildRenderObjectElement.update 
I/flutter (12407): #38     Element.updateChild 
I/flutter (12407): #39     ComponentElement.performRebuild 
I/flutter (12407): #40     Element.rebuild 
I/flutter (12407): #41     StatefulElement.update 
I/flutter (12407): #42     Element.updateChild 
I/flutter (12407): #43     SingleChildRenderObjectElement.update 
I/flutter (12407): #44     Element.updateChild 
I/flutter (12407): #45     ComponentElement.performRebuild 
I/flutter (12407): #46     Element.rebuild 
I/flutter (12407): #47     ProxyElement.update 
I/flutter (12407): #48     Element.updateChild 
I/flutter (12407): #49     SingleChildRenderObjectElement.update 
I/flutter (12407): #50     Element.updateChild 
I/flutter (12407): #51     ComponentElement.performRebuild 
I/flutter (12407): #52     Element.rebuild 
I/flutter (12407): #53     StatefulElement.update 
I/flutter (12407): #54     Element.updateChild 
I/flutter (12407): #55     ComponentElement.performRebuild 
I/flutter (12407): #56     Element.rebuild 
I/flutter (12407): #57     StatelessElement.update 
I/flutter (12407): #58     Element.updateChild 
I/flutter (12407): #59     SingleChildRenderObjectElement.update 
I/flutter (12407): #60     Element.updateChild 
I/flutter (12407): #61     ComponentElement.performRebuild 
I/flutter (12407): #62     Element.rebuild 
I/flutter (12407): #63     ProxyElement.update 
I/flutter (12407): #64     Element.updateChild 
I/flutter (12407): #65     ComponentElement.performRebuild 
I/flutter (12407): #66     Element.rebuild 
I/flutter (12407): #67     BuildOwner.buildScope 
I/flutter (12407): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter (12407): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter (12407): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter (12407): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter (12407): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
I/flutter (12407): #74     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (12407): #75     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (12407): #76     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (12407): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (12407): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 620 libraries in 2,033ms.

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We cannot provide personal support here. Thanks!
