### ISSUE TITLE
image_picker causing error in building

### ISSUE THREAD

**Issue by ish12321** [flutter/flutter#29634]
Hello,
I am new to asking questions on github so please don't forgive me if I provide insufficient information. In my flutter app, as soon as I install image_picker's latest version (image_picker: ^0.5.0+9), my app doesn't build anymore with the following error logs: 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Android resource linking failed
>   C:\Users\dell\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\4748a5abe71d30e00fe374ffc6530c20\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.
> 
>   C:\Users\dell\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\4748a5abe71d30e00fe374ffc6530c20\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.
> 
>   error: failed linking references.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 12s
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                        74.0s
> *******************************************************************************************
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> *******************************************************************************************
> Gradle task assembleDebug failed with exit code 1

**Comment by mrcoalp** [comment]
You need to migrate your app to the android x library. See: [AndroidX compatibility](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)
