### ISSUE TITLE
Callback on hot reload and hot restart

### ISSUE THREAD

**Issue by CaiJingLong** [flutter/flutter#29647]
I developed a plugin that needed to call native system resources (playing sound and ffmpeg decode or encode video), but when I hot reload / hot restart, native resources were not released because they were not involved in hot overload. 

It is well known that the coding and decoding process takes up a lot of system resources, so I need to release these resources.

Is there a callback on hot restart so that I can release system resources when triggering hot restart? And this method may need to be able to distinguish hot reload from hot restart.

` $ flutter --version`

```bash
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (5 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by NearHuscarl** [comment]
You can detect hot reload by overriding `reassemble`

Full answer here: https://stackoverflow.com/a/55282550/9449426

**Comment by fzyzcjy** [comment]
Hi I wonder how to detect hot *restart*? Thanks!

**Comment by brenzi** [comment]
Any update on this? I need a callback *before* hot-restart

**Comment by raphael-bmec-co** [comment]
+1
