### ISSUE TITLE
Possible to achieve pushing effects with flutter?

### ISSUE THREAD

**Issue by hgl** [flutter/flutter#29645]
I [asked this question on stackoverflow](https://stackoverflow.com/questions/55236435/how-to-animation-a-panel-so-that-it-has-pushing-effect), but got no response. I figure it might be something that is really difficult to do or even not possible. So posting again in flutter issue tracker partially as a question and partially as a feature request. Hope that's ok.

I have a simple chat app like layout like this:

![](https://i.stack.imgur.com/u3zsl.png)
Upon tapping the plus sign, a panel should slide in from the bottom: 
![](https://i.stack.imgur.com/jCvrI.png)
The problem is obvious, the safe area padding above the panel didn't get removed.

I wonder how I could animate the panel sliding, so that the panel appears to first cover the safe area padding and then push the text field up.

The current layout constitutes a column widget containing the top white area, the text field and the bottom panel. Both the text field and the panel contains a SafeArea. The panel is animated with SizeTransition.

I find covering the safe area padding to be the most tricky part. Because I can't simply animate its size. The animation has to synchronize with the panel sliding.

Is there any way to achieve that?

Thanks

**Comment by Piinks** [comment]
Hi @hgl, Would you be able to provide a minimal code sample to reproduce this issue?
