### ISSUE TITLE
registrarForPlugin  return nil

### ISSUE THREAD

**Issue by taojigu** [flutter/flutter#29668]
1. I create a PipeLine Plugin, registered at AppDelegate of Runner.xcproject. It works fine.
2. In Main.story board. I  change the Initia ViewController to a UINavigationController, whose rootViewController is FlutterViewController.
3. Then the plugin register failed.   
In Appelegate.m
```
NSObject<FlutterPluginRegistrar> *strar = [self registrarForPlugin:@"PipePlugin"];

//strar is nil
```
I upload the demo :  https://github.com/taojigu/learn_plujgin

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D42, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.32.3)
[✓] Connected device (2 available)

```

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
