### ISSUE TITLE
[image_picker] Pick image from Google Photos cause application crash

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#29667]
When you pick photo from Gallery/Photos
It appears in version image_picker 0.5.0+9. Version 0.5.0+3 is working fine.

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
io.flutter.plugins.imagepicker.ImageResizer.resizedImage (ImageResizer.java:48)
io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded (ImageResizer.java:37)
io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult (ImagePickerDelegate.java:430)
io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult (ImagePickerDelegate.java:372)
io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult (ImagePickerDelegate.java:351)
io.flutter.app.FlutterPluginRegistry.onActivityResult (FlutterPluginRegistry.java:218)
io.flutter.app.FlutterActivityDelegate.onActivityResult (FlutterActivityDelegate.java:143)
io.flutter.app.FlutterActivity.onActivityResult (FlutterActivity.java:142)
android.app.Activity.dispatchActivityResult (Activity.java:6937)
android.app.ActivityThread.deliverResults (ActivityThread.java:4122)
android.app.ActivityThread.handleSendResult (ActivityThread.java:4169)
android.app.ActivityThread.-wrap20 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1552)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6186)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:889)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:779)

**Comment by benadrasni** [comment]
After deleting these lines (96-99) from FileUtils.java, it seems to be working. 

      // Return the remote address
      if (isGooglePhotosUri(uri)) {
        return uri.getLastPathSegment();
      }

**Comment by ivanchaukn** [comment]
It's not working for me on 0.5.0+3 either.

**Comment by masewo** [comment]
Same problem over here. I only get an integer back as path:

`var image = await ImagePicker.pickImage(source: ImageSource.gallery);
print(image.path); // prints 1480780288` 

Following exception is thrown:

The following FileSystemException was thrown resolving an image codec:
Cannot open file, path = '1480780288' (OS Error: No such file or directory, errno = 2)

If you try to scale the image by providing width or heigth then the app crashes with NullPointerException (see first comment) respectively FileNotFoundException:

Unable to decode stream: java.io.FileNotFoundException: 1480780288 (No such file or directory)

**Comment by boskokg** [comment]
I fixed the issue by changing mentioned code: (96-99) from FileUtils.java to:
`
if (isGooglePhotosUri(uri)) {
return null;
}
`

Null is handled in the parent method FileUtils::getPathFromUri where null result from the FileUtils::getPathFromLocalUri continues processing uri with method FileUtils::getPathFromRemoteUri.

**Comment by masewo** [comment]
Thank you. Just a newbie question: How did you modify FileUtils.java locally? Just by Ctrl clicking the dependency in den pubspec and modify it directly? Will it be overwritten with the next update? Or did you make a local copy?

**Comment by benadrasni** [comment]
Fork "plugins" into your github, clone it to your local, replace reference in pubspec to 

  image_picker:
    path: ../plugins/packages/image_picker
