### ISSUE TITLE
[image_picker] image file in gallery is deleted by image_picker if it was scaled

### ISSUE THREAD

**Issue by microdog** [flutter/flutter#29664]
When picking an image from the gallery using the image_picker plugin, the image file in the gallery is deleted by image_picker if the image is scaled(exceeds the `maxWidth` or `maxHeight` limit).

It seems that this issue was introduced in https://github.com/flutter/plugins/pull/1288 which was intended to delete the original image captured from the camera(https://github.com/flutter/flutter/issues/23500), but the patch forgot to check the image source.

## Steps to Reproduce

1. use the image_picker plugin: `0.5.0+9` (issue introduced in `0.5.0+6`)
2. just write a simple demo to pick an image from the gallery with `maxWidth` and `maxHeight` set.
3. pick an image from the gallery which exceeds the `maxWidth` and `maxHeight` limit.
4. Boom. The original image file just vanished.

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14.3 18D109, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] VS Code (version 1.32.3)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by microdog** [comment]
Not all devices are affected by this issue. If the resolved file path is scoped in the Android app package, it is ok to delete the file. But the resolved file path on many of our test devices points to the original image file, for example, in `/storage/emulated/0/DCIM/Camera`.

Some of our devices affected:

* OnePlus 6(A6000) - Android 9(OP6_H2_BETA_17, A6000_22_190309)
* Xiaomi MI 8 - Android 9(MIUI 10.2.2.0)

Some of our devices NOT affected:

* Pixel 2 XL - Android 9(PQ1A.190105.004)
* Xiaomi MI 5s Plus - Android 8(MIUI 10.2.1.0)

**Comment by kamalzakaria** [comment]
having the same issue here.

**Comment by tlcheah2** [comment]
I forked the plugins and did a temporary fix. You can use my fork temporary

```
image_picker:
    git:
      url: git://github.com/tlcheah2/plugins.git
      path: packages/image_picker
```

**Comment by microdog** [comment]
Any update on this? The PR was created a week ago but no feedback was received.

Some other image_picker issues caused by "file not found" error may also be caused by this issue because the user can select an image from gallery which file has already been deleted.

**Comment by microdog** [comment]
This should be fixed in https://github.com/flutter/plugins/pull/1445.
