### ISSUE TITLE
Image_picker - Camera is not Open

### ISSUE THREAD

**Issue by prasant10050** [flutter/flutter#29662]
## Steps to Reproduce

Image_picker - 0.5.0+9
1. ...I have two popupmenu item for Camera and Gallery in popupmenu button
2. ...When i press gallery button, gallery will open i select any image and its working fine
3. ...but when i press camera button , then my app will crash and it will throw error, 

Future getCameraImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    setState(() {
      _image = image;
    });
    print(_image);
    print(basename(_image.path));
  }

Future getGalleryImage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() {
      _image = image;
    });
    print(_image);
    print(basename(_image.path));
  }
i have mention my log file.

## Logs
I/flutter (30101): **File: '/storage/emulated/0/Download/9df66.jpg'**
D/Surface (30101): Surface::connect(this=0x77a7d30000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (30101): Surface::connect(this=0x778dd90000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/flutter (30101): **9df66.jpg**
I/flutter (30101): PointerDownEvent#8cd58(position: Offset(165.3, 278.8), timeStamp: 3:37:43.694000, pointer: 4, kind: touch, down: true, pressureMin: 0.0, size: 0.1, radiusMajor: 4.5, radiusMinor: 4.5): HitTestResult(RenderParagraph#3ebcb@Offset(1.3, 14.4), RenderPositionedBox#c84bc@Offset(1.3, 14.4), RenderConstrainedBox#6ba23@Offset(1.3, 14.4), RenderExcludeSemantics#ba9df@Offset(1.3, 14.4), RenderSemanticsAnnotations#2ed9f@Offset(1.3, 14.4), RenderPositionedBox#2adc8@Offset(5.3, 18.4), RenderConstrainedBox#2a468@Offset(5.3, 18.4), RenderPadding#4dcf0@Offset(13.3, 26.4), RenderConstrainedBox#dea23@Offset(13.3, 26.4), RenderSemanticsAnnotations#43a3e@Offset(13.3, 26.4), RenderSemanticsAnnotations#5c479@Offset(13.3, 26.4), RenderPointerListener#78772@Offset(13.3, 26.4), RenderPointerListener#e1926@Offset(13.3, 26.4), RenderSemanticsGestureHandler#d79b0@Offset(13.3, 26.4), RenderFlex#f38ad@Offset(13.3, 26.4), RenderBaseline#e375d@Offset(13.3, 25.8), RenderPadding#806a3@Offset(29.3, 25.8), RenderConstrainedBox#e255e@Offset(29.3
D/Surface (30101): Surface::disconnect(this=0x77a7d30000,api=1)
D/Surface (30101): Surface::connect(this=0x77a7d30000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (30101): Surface::disconnect(this=0x778dd90000,api=1)
D/Surface (30101): Surface::connect(this=0x778dd90000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (30101): Surface::disconnect(this=0x77a7d30000,api=1)
D/Surface (30101): Surface::connect(this=0x77a7d30000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (30101): Surface::disconnect(this=0x778dd90000,api=1)
D/Surface (30101): Surface::connect(this=0x778dd90000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (30101): Surface::disconnect(this=0x778dd90000,api=1)
D/Surface (30101): Surface::disconnect(this=0x778dd90000,api=-1)
D/Surface (30101): Surface::disconnect(this=0x77a7d30000,api=1)
V/PhoneWindow(30101): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@2f3a648, this = DecorView@217ece1[MainActivity]
I/flutter (30101): File: '/storage/emulated/0/Download/3887172f582edebdf551427fdb91554b.jpg'
I/flutter (30101): 3887172f582edebdf551427fdb91554b.jpg
I/flutter (30101): null
V/PhoneWindow(30101): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@2f3a648, this = DecorView@217ece1[MainActivity]
D/Surface (30101): Surface::connect(this=0x77a7d30000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (30101): Surface::connect(this=0x778dd90000,api=1)
D/mali_winsys(30101): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/flutter (30101): PointerDownEvent#fe428(position: Offset(63.9, 201.8), timeStamp: 3:37:47.854000, pointer: 5, kind: touch, down: true, pressureMin: 0.0, size: 0.1, radiusMajor: 3.0, radiusMinor: 3.0): HitTestResult(RenderPointerListener#12449@Offset(63.9, 201.8), RenderSemanticsGestureHandler#b5ebb@Offset(63.9, 201.8), RenderExcludeSemantics#e92fd@Offset(63.9, 201.8), RenderBlockSemantics#c8b39@Offset(63.9, 201.8), RenderIgnorePointer#9cb50@Offset(63.9, 201.8), RenderStack#8f334@Offset(63.9, 201.8), _RenderTheatre#f77b5@Offset(63.9, 201.8), RenderSemanticsAnnotations#6c36a@Offset(63.9, 201.8), RenderAbsorbPointer#a4b98@Offset(63.9, 201.8), RenderPointerListener#6ac12@Offset(63.9, 201.8), RenderSemanticsAnnotations#ebce7@Offset(63.9, 201.8), RenderView#a32c6, <WidgetsFlutterBinding>)
I/flutter (30101): You have canceled the menu.
I/flutter (30101): PointerDownEvent#51585(position: Offset(130.8, 198.8), timeStamp: 3:37:49.247000, pointer: 6, kind: touch, down: true, pressureMin: 0.0, size: 0.1, radiusMajor: 4.5, radiusMinor: 4.5): HitTestResult(RenderParagraph#4a6c5@Offset(12.8, 19.8), RenderPositionedBox#bdc1d@Offset(12.8, 19.8), RenderConstrainedBox#a0447@Offset(12.8, 19.8), RenderExcludeSemantics#7a7c7@Offset(12.8, 19.8), RenderSemanticsAnnotations#a4c07@Offset(12.8, 19.8), RenderPositionedBox#52660@Offset(16.8, 23.8), RenderConstrainedBox#6e783@Offset(16.8, 23.8), RenderPadding#141a6@Offset(24.8, 31.8), RenderConstrainedBox#0db52@Offset(24.8, 31.8), RenderSemanticsAnnotations#a8f10@Offset(24.8, 31.8), RenderSemanticsAnnotations#1a7ac@Offset(24.8, 31.8), RenderPointerListener#0b7c6@Offset(24.8, 31.8), RenderPointerListener#b06d7@Offset(24.8, 31.8), RenderSemanticsGestureHandler#ebd25@Offset(24.8, 31.8), RenderPositionedBox#4cffe@Offset(25.8, 32.8), RenderDecoratedBox#eeb72@Offset(25.8, 32.8), RenderConstrainedBox#30eab@Offset(25.8, 32.8), RenderFlex#
I/flutter (30101): PointerDownEvent#6d579(position: Offset(249.2, 216.8), timeStamp: 3:37:51.686000, pointer: 7, kind: touch, down: true, pressureMin: 0.0, size: 0.1, radiusMajor: 4.5, radiusMinor: 4.5): HitTestResult(RenderPointerListener#6e02c@Offset(113.2, 11.8), RenderSemanticsGestureHandler#1cf5e@Offset(113.2, 11.8), RenderAnimatedOpacity#20147@Offset(113.2, 11.8), RenderListBody#a6da7@Offset(113.2, 11.8), RenderPadding#999d7@Offset(113.2, 19.8), _RenderSingleChildViewport#13078@Offset(113.2, 19.8), RenderIgnorePointer#b554a@Offset(113.2, 19.8), RenderSemanticsAnnotations#7aacb@Offset(113.2, 19.8), RenderPointerListener#495bc@Offset(113.2, 19.8), RenderSemanticsGestureHandler#9cabe@Offset(113.2, 19.8), RenderPointerListener#66008@Offset(113.2, 19.8), _RenderScrollSemantics#8ea57@Offset(113.2, 19.8), RenderRepaintBoundary#49a8d@Offset(113.2, 19.8), RenderCustomPaint#2b850@Offset(113.2, 19.8), RenderRepaintBoundary#eb6e0@Offset(113.2, 19.8), RenderSemanticsAnnotations#165f9@Offset(113.2, 19.8), RenderIntrinsicWidth#4c161@Of
I/flutter (30101): value:ImageSource.camera
I/flutter (30101): PointerDownEvent#81a52(position: Offset(136.8, 194.9), timeStamp: 3:38:11.472000, pointer: 8, kind: touch, down: true, pressureMin: 0.0, size: 0.1, radiusMajor: 4.5, radiusMinor: 4.5): HitTestResult(RenderParagraph#4a6c5@Offset(18.8, 15.9), RenderPositionedBox#bdc1d@Offset(18.8, 15.9), RenderConstrainedBox#a0447@Offset(18.8, 15.9), RenderExcludeSemantics#7a7c7@Offset(18.8, 15.9), RenderSemanticsAnnotations#a4c07@Offset(18.8, 15.9), RenderPositionedBox#52660@Offset(22.8, 19.9), RenderConstrainedBox#6e783@Offset(22.8, 19.9), RenderPadding#141a6@Offset(30.8, 27.9), RenderConstrainedBox#0db52@Offset(30.8, 27.9), RenderSemanticsAnnotations#a8f10@Offset(30.8, 27.9), RenderSemanticsAnnotations#1a7ac@Offset(30.8, 27.9), RenderPointerListener#0b7c6@Offset(30.8, 27.9), RenderPointerListener#b06d7@Offset(30.8, 27.9), RenderSemanticsGestureHandler#ebd25@Offset(30.8, 27.9), RenderPositionedBox#4cffe@Offset(31.8, 28.9), RenderDecoratedBox#eeb72@Offset(31.8, 28.9), RenderConstrainedBox#30eab@Offset(31.8, 28.9), RenderFlex#
I/flutter (30101): PointerDownEvent#5101e(position: Offset(238.7, 228.8), timeStamp: 3:38:12.524000, pointer: 9, kind: touch, down: true, pressureMin: 0.0, size: 0.1, radiusMajor: 5.5, radiusMinor: 5.5): HitTestResult(RenderParagraph#a36a5@Offset(38.7, 8.4), RenderPointerListener#47270@Offset(38.7, 8.4), RenderSemanticsGestureHandler#53922@Offset(38.7, 8.4), RenderFlex#c4c8a@Offset(86.7, 24.4), RenderBaseline#ad10b@Offset(86.7, 23.8), RenderPadding#fdab5@Offset(102.7, 23.8), RenderConstrainedBox#74fc5@Offset(102.7, 23.8), RenderPointerListener#349a0@Offset(102.7, 23.8), RenderSemanticsGestureHandler#d4343@Offset(102.7, 23.8), RenderAnimatedOpacity#cd778@Offset(102.7, 23.8), RenderListBody#50189@Offset(102.7, 23.8), RenderPadding#ee4ae@Offset(102.7, 31.8), _RenderSingleChildViewport#cd7b3@Offset(102.7, 31.8), RenderIgnorePointer#02ee0@Offset(102.7, 31.8), RenderSemanticsAnnotations#4484c@Offset(102.7, 31.8), RenderPointerListener#f401b@Offset(102.7, 31.8), RenderSemanticsGestureHandler#6de3e@Offset(102.7, 31.8), RenderPointerLi
E/MethodChannel#plugins.flutter.io/image_picker(30101): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker(30101): java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.hmdglobal.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://com.cbtech.cb_curemantra.flutter.image_provider/external_files/Android/data/com.cbtech.cb_curemantra/files/Pictures/9a337565-346b-4500-a2a5-0c47a3b7f6fc3151795446032035521.jpg} (has extras) } from ProcessRecord{55d12b2 30101:com.cbtech.cb_curemantra/u0a256} (pid=30101, uid=10256) with revoked permission android.permission.CAMERA
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.os.Parcel.createException(Parcel.java:1950)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.os.Parcel.readException(Parcel.java:1918)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.os.Parcel.readException(Parcel.java:1868)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3693)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.app.Activity.startActivityForResult(Activity.java:4586)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.app.Activity.startActivityForResult(Activity.java:4544)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:282)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:263)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:64)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at android.app.ActivityThread.main(ActivityThread.java:6715)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/MethodChannel#plugins.flutter.io/image_picker(30101): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1798)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:723)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:550)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1173)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:492)
E/MethodChannel#plugins.flutter.io/image_picker(30101): 
D/AndroidRuntime(30101): Shutting down VM
E/AndroidRuntime(30101): FATAL EXCEPTION: main
E/AndroidRuntime(30101): Process: com.cbtech.cb_curemantra, PID: 30101
E/AndroidRuntime(30101): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=0, data=null} to activity {com.cbtech.cb_curemantra/com.cbtech.cb_curemantra.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30101): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4393)
E/AndroidRuntime(30101): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4435)
E/AndroidRuntime(30101): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(30101): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(30101): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(30101): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1838)
E/AndroidRuntime(30101): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30101): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(30101): 	at android.app.ActivityThread.main(ActivityThread.java:6715)
E/AndroidRuntime(30101): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30101): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(30101): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/AndroidRuntime(30101): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30101): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/AndroidRuntime(30101): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime(30101): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:462)
E/AndroidRuntime(30101): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult(ImagePickerDelegate.java:405)
E/AndroidRuntime(30101): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:354)
E/AndroidRuntime(30101): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
E/AndroidRuntime(30101): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
E/AndroidRuntime(30101): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(30101): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(30101): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4386)
E/AndroidRuntime(30101): 	... 11 more
I/Process (30101): Sending signal. PID: 30101 SIG: 9
Application finished.

```
```

```
```

**Comment by mrcoalp** [comment]
Had the same problem... They removed "unnecessary" camera permission in version 0.5.0+5, but in reality, I've found that, that permission is needed (unless is something else, but when I give it permission it works). You can check camera permission and ask it before calling the method or use version 0.5.0+3, which automatically prompts you with permission request

**Comment by lifenautjoe** [comment]
Same here!

**Comment by lifenautjoe** [comment]
Thanks for the downgrading tip @mrcoalp ! Worked 👍

**Comment by mrcoalp** [comment]
Let's wait for a fix :)

**Comment by cyanglaz** [comment]
Should be fixed by https://github.com/flutter/plugins/pull/1519. Closing this issue now. If any related issue has been found after applying using the newest Image_picker, please open a another issue with details.
