### ISSUE TITLE
Line's heigh is not stable with 3x Android devices

### ISSUE THREAD

**Issue by liupeinye** [flutter/flutter#29663]
Just open the official demo in GooglePlay. You can simply find that thin line's heigh is not stable with 3x Android devices. At different places, a 1dp line's heigh range from 0px to 3px. I faced the same bug in ReactNative, seems to be a bug in Yoga.

I hope Flutter can solve is problem!!!

Official demo:
![device-2019-03-14-160247](https://user-images.githubusercontent.com/4571916/54666703-817f7d80-4b25-11e9-86db-d6f8c388dc15.png)

Details:
![1552550610342-image](https://user-images.githubusercontent.com/4571916/54666719-89d7b880-4b25-11e9-9e9f-0fc47d16e023.png)

**Comment by liupeinye** [comment]
This problem has a great impact on us

**Comment by HansMuller** [comment]
This looks like a known problem with antialiasing and mapping from logical pixels to device pixels. There's an open issue for a documentation fix: #14288

More info about the problem can be found here:
#14288 (comment)
#17084 (comment)
#15035 (comment)

**Comment by iapicca** [comment]
Hi @liupeinye 
I see there's an open [issue](https://github.com/flutter/flutter/issues/14288) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
