### ISSUE TITLE
[image_picker] Application crashes after taking photo (^ 0.5.0+9)

### ISSUE THREAD

**Issue by freitzzz** [flutter/flutter#29676]
Good afternoon everyone.

I'm currently having some problems with image_picker while taking photos in some devices. After taking the photo, the application screen turns white and crashes after a while. The strange thing is that I can't see and analyze the exception stack trace, as I lose connection to my device after taking the photo.

The procedure we use to take a photo is: 
- Click take photo button
- Open mobile phone image picker functionalities with `ImagePicker.pickImage(source: ImageSource.camera);`
- After taking or choosing a photo we save the image as a file instance in `setState` callback

We are testing our application in the following devices:

- `SM A300F  • 11b4a7b1 • android-arm • Android 5.0.2 (API 21)`(Crashes while taking photos but has no problems with uploading an existent one)

- `GT I9505   • b51eddcf   • android-arm • Android 5.0.1 (API 21)`(Doesn't crash while taking or uploading existing photos, but can't upload correctly)

- `SM J120FN • 42007871e6576377 • android-arm • Android 5.1.1 (API 22)` (Takes and uploads photos with no problems)

image_picker version: ^ 0.5.0+9

Flutter version: 
```
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (4 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

**Comment by aashitvyom** [comment]
Facing the same problem on image_picker version: ^0.6.1+2

**Comment by TahaTesser** [comment]
Hi @freitzzz 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
