### ISSUE TITLE
Android emulator shows a white screen initially - hot reload/restart fixes it

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#29679]
When first doing a `flutter run` on an Android emulator (Pixel 2, on a Macbook Pro), the screen is completely white.  Doing a hot reload or hot restart seems to get it going fine.

I initially thought I messed something up with my emulator (I had been reconfiguring it around the same time), but @shihaohong has noticed this as well.

**Comment by jonahwilliams** [comment]
When did this start happening? If you checkout from ~ month ago does it still happen?

**Comment by dnfield** [comment]
It works on beta.  Trying to narrow it down further.

**Comment by pepegich** [comment]
on windows 10 same issue

**Comment by dnfield** [comment]
Looks like this started with 8f1a430557ec2d3725fee2073e9a1145bab96b14 (#28688), which was a manual engine roll with 19 commits.

/cc @GaryQian

**Comment by dnfield** [comment]
Marking as today - we really should fix this.

**Comment by dnfield** [comment]
Let's keep this open til it rolls through to the framework.

**Comment by dnfield** [comment]
Fixed by https://github.com/flutter/flutter/pull/29715
