### ISSUE TITLE
Flickering when long-press-dragging in material text field

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#29682]
## Steps to Reproduce

1. Open the flutter gallery.
2. Go to the material text fields demo.
3. Type something in the first text field.
4. **Long-press-drag** to select text.
5. See how the selection handles keep flickering as you drag.

The same problem existed for drag-by-mouse and is fixed in https://github.com/flutter/flutter/pull/29563. This issue needs a similar solution.

**Comment by TahaTesser** [comment]
Hi @mdebbar 
Does this issue still exist?
Thank you

**Comment by mdebbar** [comment]
I can't repro it anymore. Thanks for bringing this to my attention.
