### ISSUE TITLE
Improve documentation on Listener

### ISSUE THREAD

**Issue by Koridev** [flutter/flutter#29685]
## Steps to Reproduce

1. run `flutter create --sample=widgets.Listener mysample` and build the project
2. tap the screen relentlessly
3. nothing happens, the events are not called

## Logs

Flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-JP)
    • Flutter version 1.2.1 at /Users/guillaume/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/guillaume/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone 6 • 1F54E7BF-0551-4AEB-9CD8-F63C502A842A • ios • iOS 12.1 (simulator)

• No issues found!

```

Tried with both iOS and android devices.

**Comment by goderbauer** [comment]
From https://docs.flutter.dev/flutter/widgets/Listener-class.html:

> This example makes a [Container] react to being entered by a mouse pointer, showing a count of the number of entries and exits.

The example is for interactions with a **mouse**. It is not meant to react to touches with a finger. We should probably also mention that on the screen that the examples renders.

/cc @gspencergoog

**Comment by Koridev** [comment]
So is it even possible to use a Listener for touch events or is it dedicated to mouse pointers?
In my understanding the word "pointer" could mean both.

**Comment by gspencergoog** [comment]
Makes sense to add that to this example.  Ideally, we should also have another example that deals with touch events.

**Comment by goderbauer** [comment]
Listener works for both. The example only uses `onPointerEnter`, `onPointerHover`, `onPointerExit`, which are currently mouse exclusive. The other callbacks (e.g. onPointerDown, etc) also work for touch.

**Comment by Koridev** [comment]
Ok, it is indeed written in the long version of the documentation of the properties when they are mouse specific, my bad for not reading that far, thank you.

I find it misleading that the properties have the exact same naming convention even though they don't all respond to the same kind of events.
Could `onPointerEnter`, `onPointerHover` and `onPointerExit` be renamed to something like `onMousePointer[...]` to avoid any confusion?

Or at least, could the documentation specify from the very first line their differences, so that it is visible from https://docs.flutter.dev/flutter/widgets/Listener-class.html and not only from the detailed documentation of each property?

**Comment by YmiYugy** [comment]
How could `onPointerEnter` and `onPointerExit` be replicated for touch inputs?

**Comment by dkwingsmt** [comment]
@YmiYugy Entering and exiting doesn't really make sense for touch inputs.

A touch screen can not be interacted without being touched first, therefore `onPointerDown` would be the first moment that a widget can theoretically be aware of the entrance.

Flutter only performs the hit test (finding out all widgets that the tap affects) once at `onPointerDown`, and all subsequent moves use the same hit test result. It means that if you press a button and drag out, it will still be the button that is pressed. This is designed both for fidelity and performance.

With this design, the only way that a widget is free from the press is when the touch is released.

If you want to detect moving in and out of widgets during the press, take a look at `Drag`.

**Comment by dkwingsmt** [comment]
`Listener` now has a demo for counting presses, while `MouseRegion` has a demo for counting enters and exits. I would consider this issue solved. That said, feel free to bring up more cases that you hope the documentation should address.
