### ISSUE TITLE
Inkwell bug  hard to find but still very big 

### ISSUE THREAD

**Issue by ShashankSirmour** [flutter/flutter#29690]
When taping to inkwell with three fingers at a time something unusual happened.
1.  splash  stuck to the inkwell 
2. On scroll instead of going down it come over the appbar

**Comment by HansMuller** [comment]
I was able to reproduce the problem you've reported by tapping the Flutter gallery home page "category" icons with 3 fingers (at once). Doing so causes the button highlight to appear but not disappear when the lifting off the screen; the button's onPressed handler doesn't trigger.

CC @goderbauer

**Comment by ShashankSirmour** [comment]
It also fails while taping to three different inkwell cards at a time  means simulation taping three card with one fine finger in each card

**Comment by nicolasvahidzein** [comment]
Is it similar to this video? https://github.com/flutter/flutter/issues/47152

**Comment by rahuldange09** [comment]
splash stuck to the inkwell
Im facing this issue big issue as this is visible bug on ui
InkWell stuck there.

To reproduce this bug tab on any widget which has parent as inkwell let splash color starts highlighting and then turn of screen by power button and then turn on again and check highlighted splash color is still there present cant be easily removed until you press here and there on some widget.

On Android this bug is easily visible and not removed until other input and on ios its visible but it removes in 1-2sec as u turn on screen.

**Comment by TahaTesser** [comment]
Not able to reproduce this using multiple examples

### Tapping with 3 fingers on bottom items, no issues

<details> 
<summary>Code Sample</summary> 

``` 
// Flutter code sample for BottomNavigationBar

// This example shows a [BottomNavigationBar] as it is used within a [Scaffold]
// widget. The [BottomNavigationBar] has three [BottomNavigationBarItem]
// widgets and the [currentIndex] is set to index 0. The selected item is
// amber. The `_onItemTapped` function changes the selected item's index
// and displays a corresponding message in the center of the [Scaffold].
//
// ![A scaffold with a bottom navigation bar containing three bottom navigation
// bar items. The first one is selected.](https://flutter.github.io/assets-for-api-docs/assets/material/bottom_navigation_bar.png)

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This Widget is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _selectedIndex = 0;
  static const TextStyle optionStyle =
      TextStyle(fontSize: 30, fontWeight: FontWeight.bold);
  static const List<Widget> _widgetOptions = <Widget>[
    Text(
      'Index 0: Home',
      style: optionStyle,
    ),
    Text(
      'Index 1: Business',
      style: optionStyle,
    ),
    Text(
      'Index 2: School',
      style: optionStyle,
    ),
  ];

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('BottomNavigationBar Sample'),
      ),
      body: Center(
        child: _widgetOptions.elementAt(_selectedIndex),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('Home'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.business),
            title: Text('Business'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            title: Text('School'),
          ),
        ],
        currentIndex: _selectedIndex,
        selectedItemColor: Colors.amber[800],
        onTap: _onItemTapped,
      ),
    );
  }
}

``` 

</details> 

### tapping on 3 inkwells with 3 fingers at same no issue,

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          elevation: 0,
        ),
        body: Column(
          children: [
            InkWell(
              onTap: () {},
              child: Container(
                height: 200,
                width: double.infinity,
              ),
            ),
            InkWell(
              onTap: () {},
              child: Container(
                height: 200,
                width: double.infinity,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

``` 

</details>

**Comment by rahuldange09** [comment]
> Not able to reproduce this using multiple examples
> 
> ### Tapping with 3 fingers on bottom items, no issues
> Code Sample
> ### tapping on 3 inkwells with 3 fingers at same no issue,
> Code Sample
> @ShashankSirmour can you please provide a sample with latest?
> 
> flutter doctor -v

Well I tried reproducing this issue and this is no longer present in 1.17 and after.
So it is good to close this issue.

**Comment by ShashankSirmour** [comment]
> Not able to reproduce this using multiple examples
> 
> ### Tapping with 3 fingers on bottom items, no issues
> Code Sample
> ### tapping on 3 inkwells with 3 fingers at same no issue,
> Code Sample
> @ShashankSirmour can you please provide a sample with latest?
> 
> flutter doctor -v

yeah I think it is resolved
