### ISSUE TITLE
InputDecoration labelText (feature request)

### ISSUE THREAD

**Issue by jerryhimmersion** [flutter/flutter#29694]
InputDecoration labelText  is working for me under normal usage, but I have found one usage that is causing me problems and I hope the team will take a look.

Very simple to create: normally labelText is expecting a user to input (type) in some data and works nicely. If you post some data to labelText, this is where it gets weird. I'm downloading some data from the internet and stuffing that data into labelText (rather than having a user input data) this is what I'm seeing:
1- the data to appear along with a header (example: post "john" and the header would be "First Name")
2- if user types over the posted data the box will not show a correct header  (example: user types "mary" and the header shows "mary")

I simply can't find a solution for this use case (which is important to me).
My suggestion is add a couple more items to InputDecoration mostly like the filled and fillColor feature, add "popped" and "poppedLabel" (these are just made up names). If popped is true then have the header display the poppedLabel instead of using the labelText.

If anyone knows of an existing answer I would like to know.

**Comment by HansMuller** [comment]
It would help if you could provide a small self-contained app that demonstrates this problem. You probably need to incorporate a network request, hopefully the labelText value that causes trouble will be enough.

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by jerryhimmersion** [comment]
Weather the inform comes locally or from the internet it doesn't matter in my case. 

1- I put info into my map: titleMapBaseball
2- The TextFormField has a function to set everything: setDisplay(0)
3- If I put info into the TextFormField this is where the TextFormField gets weird.



//====================================
TextFormField(
    decoration: InputDecoration(
     hintText: hints[0],
     labelText: setDisplay(0),
     filled: true,
     fillColor: setFillColor(0),
     labelStyle: setStyle(0),
    ),
     controller: myController,
   )

//====================================
  setDisplay(whichNum) {
    var display1;
    if (MyVars.themode == "new") {
      display1 = titles[whichNum];
    } else {
      if (titleMapBaseball[titleMapBaseball.keys.elementAt(whichNum)] != "") {
        display1 = titleMapBaseball[titleMapBaseball.keys.elementAt(whichNum)];
      } else {
        display1 = titles[whichNum];
      }
    }
    return display1;
  }

//====================================
final Map<String, String> titleMapBaseball = {
  'first name': 'Bobby',
  'last name': '',

![good1](https://user-images.githubusercontent.com/15018986/54787688-f1b00100-4c02-11e9-903f-0776ac78251f.png)

![bad1](https://user-images.githubusercontent.com/15018986/54787707-fd032c80-4c02-11e9-8be5-6602188c8c2c.png)

![bad2](https://user-images.githubusercontent.com/15018986/54787714-042a3a80-4c03-11e9-8c6b-e3a73f379da7.png)

**Comment by justinmc** [comment]
I can't reproduce any bug with the TextFormField like in your screenshots.  Check out the example below that shows dynamically setting the text and label of a TextFormField.  Can you modify my example to demonstrate the problem you're seeing?

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _name = '';
  String _label = 'im a label';

  void _setName() {
    setState(() {
      _name = 'Bobby';
    });
  }


  void _setLabel() {
    setState(() {
      _label = 'First Name';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(
              controller: TextEditingController(
                text: _name,
              ),
              decoration: InputDecoration(
                labelText: _label,
              ),
            ),
            RaisedButton(
              onPressed: _setName,
              child: const Text('Set text to "Bobby"'),
            ),
            RaisedButton(
              onPressed: _setLabel,
              child: const Text('Set label to "First Name"'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by jerryhimmersion** [comment]
FYI, I'm so very new to Flutter, just wanted to point that out as an excuse.  You are doing something different with your controller than I am, so I will play with this over the weekend and post back the first part of the week. Thank you for taking your time to respond to a noob.

**Comment by justinmc** [comment]
Not a problem!  Let me know how it goes.

**Comment by jerryhimmersion** [comment]
@justinmc, over the weekend I has some medical problems, when I get to feeling better I will examine your code.

**Comment by jerryhimmersion** [comment]
@justinmc, back to working on my app and I must say your code sample really helped look at the issue differently. I have 10 TextFormFields and 10 dropdowns and they all are working nicely. Thanks again for your time and samples.

**Comment by justinmc** [comment]
Great, I'm glad that helped! 🎉
