### ISSUE TITLE
P0: we should update the “flutter create” template to pass the new CrOS lint rules after flipping the CrOS analyzer bit

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#29692]
Once we have lints for the CrOS, we should ensure that the flutter create app is lint free (after flipping the flipping the CrOS analyzer bit).

**Comment by devoncarew** [comment]
ping @keertip to ensure she's aware of this issue

**Comment by keertip** [comment]
Thanks Devon! Missed this

**Comment by devoncarew** [comment]
I have confirmed that the default `flutter create` template is free of CrOS lints.

I did find that after adding:

```
  optional-checks:
    chrome-os-manifest-checks
```

to an analysis options file, it was necessary to re-start the analysis server to see CrOS related lints. I don't believe this is a showstopper for this feature, but would be something good to address in the future.

**Comment by keertip** [comment]
Thanks! Have gone through all the manifest template files in Flutter, and they are free of CrOS lints.
