### ISSUE TITLE
Execution failed for task ':url_launcher:generateDebugRFile'. 

### ISSUE THREAD

**Issue by YoungCC2** [flutter/flutter#29713]
i meet this problem.   if  get "url_launcher" package. will get this problem.  
![QQ截图20190321102210](https://user-images.githubusercontent.com/13192993/54730330-3a47ca00-4bc3-11e9-85f1-43479f94400e.png)

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
