### ISSUE TITLE
some function cannot run inside initState

### ISSUE THREAD

**Issue by pranatayudha** [flutter/flutter#29716]
I made a condition inside initState, but only one condition worked. This is my code. If there is a mistake, please correct it, thanks :smile: 

```
if (userType == 'DRIVER') {
    new Future.delayed(Duration(seconds: 5), () {
    if (widget.state == 'FINISH_LOADING') {
        showCupertinoDialog(
            ...
        );
    } else if (widget.state == 'ON_PROCESS') {
        showCupertinoDialog(
            ...
        );
    }
    });
} else {
    if (widget.state == 'FINISH_LOADING') {
    new Future.delayed(Duration(seconds: 5), () {
        showCupertinoDialog(
        ...
        );
    });
    }
}
```

In that code, only FINISH_LOADING in DRIVER works.

**Comment by shingohu** [comment]
showCupertinoDialog need BuildContext，but in initState method the Widget not complete build，and the BuildContex is not association with state,so you can't use context to show a dialog in the initState method

**Comment by pranatayudha** [comment]
But, where the userType is DRIVER and the widget.state is FINISH_LOADING, the showCupertinoDialog is working. thats possible to run any showCupertinoDialog again?

**Comment by shingohu** [comment]
because you delayed 5 seconds,after this time the the BuildContex is association with state，so you can use contex to show a dialog 。if you want to show a dialog in initState， I think you can try
`WidgetsBinding.instance.addPostFrameCallback()`
