### ISSUE TITLE
Issue from website page Flutter文档

### ISSUE THREAD

**Issue by buhuiming** [flutter/flutter#29725]
From URL: https://www.flutterchina.club/docs.md
求助！！Flutter TextField上如何显示表情？（表情gif放在assets的，已经做成了gridView，点击其中一个表情，想把这个表情显示在TextField中，删除的时候也可以删除一个表情！）

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
