### ISSUE TITLE
Unable to load Maven meta-data from https://jcenter.bintray.com/io/grpc/grpc-core/maven-metadata.xml

### ISSUE THREAD

**Issue by SuperSonicLLC** [flutter/flutter#29729]
I used cloud_firestore and firebase_messaging, when i build project some error occur

> Could not resolve all files for configuration ':app:debugCompileClasspath'.
> > Could not resolve io.grpc:grpc-core:[1.12.0].
>   Required by:
>       project :app > project :cloud_firestore > com.google.firebase:firebase-firestore:17.1.1 > io.grpc:grpc-okhttp:1.12.0
>    > Failed to list versions for io.grpc:grpc-core.
>       > Unable to load Maven meta-data from https://jcenter.bintray.com/io/grpc/grpc-core/maven-metadata.xml.
>          > Could not HEAD 'https://jcenter.bintray.com/io/grpc/grpc-core/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

Anyone have idea for fix.

**Comment by nemoryoliver** [comment]
I was also getting this issue.. I just tried again and again and now it worked..

**Comment by SuperSonicLLC** [comment]
I found the issue. Center server is down in 30 minutes, that affected building my app

**Comment by AlexMainaMunyua** [comment]
run the application again and again it will work.
