### ISSUE TITLE
Flutter application build issue

### ISSUE THREAD

**Issue by habeebul** [flutter/flutter#29738]
Launching lib\main.dart on Android SDK built for arm64 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "D:\Development_Avecto\flutter_project\cardflipcarousel\flutter_app\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
  Command: D:\Development_Avecto\flutter_project\cardflipcarousel\flutter_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

I am working in proxy network. 
1. I tried by adding proxy settings to gradle.properites files.
2. I tried by adding proxy setting to settings > Appearance and Behaviour > system settings > http proxy.
3. I tried by enable 'Enable embeded Maven repository'
but not able to solve this. Anyone please help me on this

![error](https://user-images.githubusercontent.com/8637074/54753949-53269e80-4c08-11e9-9394-334a375c6d69.png)

**Comment by habeebul** [comment]
Early response would be appreciated

**Comment by Y132om** [comment]
I also encountered the same problem.

**Comment by escamoteur** [comment]
@Y132om  do you have the exact same problem? Also behind a proxi?

@habeebul Do you still ave this problem?

**Comment by Y132om** [comment]
> @Y132om do you have the exact same problem? Also behind a proxi?
> 
> @habeebul Do you still ave this problem?

I use a proxy. However, I have solved the problem. After setting up several options in the development tool, I modified the image source, synchronized the file, and succeeded. Nothing special. I don't understand why it was successful, I just modified these items.

**Comment by iapicca** [comment]
Hi @habeebul  and @Y132om 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
