### ISSUE TITLE
D8: Program type already present: com.google.android.gms.internal.measurement.zzfe

### ISSUE THREAD

**Issue by debasmitasarkar** [flutter/flutter#29733]
I am getting this issue when added firebase_admob: ^0.8.0+3 plugin.

The error(horror :P )-
```
D8: Program type already present: com.google.android.gms.internal.measurement.zzfe
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.google.android.gms.internal.measurement.zzfe
```

Here is my pubspec.yaml - 
```
name: ******
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.2
  photo_view: ^0.2.2
  cloud_firestore: ^0.9.7
  firebase_admob: ^0.8.0+3
  share: ^0.6.0+1
  permission_handler: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/app_icon.png'
  adaptive_icon_background: '#FFFAFAFA'
  adaptive_icon_foreground: 'assets/icon/app_icon.png'



  assets:
   - assets/rangoli_loader.gif
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
```

**Comment by debasmitasarkar** [comment]
@HansMuller please look into it

**Comment by davidgalarza** [comment]
Any update I'm having the same error

**Comment by HansMuller** [comment]
CC @bparrishMines

**Comment by AndrewPetrovics** [comment]
Experiencing same issue

**Comment by debasmitasarkar** [comment]
any update about this?

**Comment by bparrishMines** [comment]
Hi @debasmitasarkar,

Sorry for the late reply. This bug is a little old now, but I wasn't able to reproduce the exact error. However, i was able to compile when using the latest version of each plugin.

```
firebase_core: ^0.4.0

photo_view: ^0.3.3
cloud_firestore: ^0.11.0+2
share: ^0.6.1+1
permission_handler: ^3.0.2
```

Your crash may be related to androidx compatibility. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by debasmitasarkar** [comment]
> Hi @debasmitasarkar,
> 
> Sorry for the late reply. This bug is a little old now, but I wasn't able to reproduce the exact error. However, i was able to compile when using the latest version of each plugin.
> 
> ```
> firebase_core: ^0.4.0
> 
> photo_view: ^0.3.3
> cloud_firestore: ^0.11.0+2
> share: ^0.6.1+1
> permission_handler: ^3.0.2
> ```
> 
> Your crash may be related to androidx compatibility. https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
I will check if it works now

**Comment by bparrishMines** [comment]
We've added a test to verify all first party plugins compile together, so you shouldn't receive this message from one of our plugins unless a third party plugin is incompatible. Closing this issue for now

**Comment by kroikie** [comment]
@debasmitasarkar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/397. Any further collaboration will be done there.
