### ISSUE TITLE
Crash when Flutter.createView

### ISSUE THREAD

**Issue by Liuzhiyang94** [flutter/flutter#29730]
I have meet some problems when add Flutter in my application.
Here is the crash stackTrace.
` java:
    io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:423)
    io.flutter.view.FlutterNativeView.attach(FlutterNativeView.java:165)
    io.flutter.view.FlutterNativeView.<init>(FlutterNativeView.java:46)
    io.flutter.view.FlutterNativeView.<init>(FlutterNativeView.java:36)
    io.flutter.facade.Flutter.createView(Flutter.java:73)
    xxxxxxxxxxx.onCreate(xxxxxxxx.java:182)
    android.app.Activity.performCreate(Activity.java:7003)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
    android.app.ActivityThread.-wrap11(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6798)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

So I debug my code.And it go to the `FlutterJNI`,when execute the `nativeAttach`
`  @UiThread
    public void attachToNative(boolean isBackgroundView) {
        this.ensureNotAttachedToNative();
        this.nativePlatformViewId = this.nativeAttach(this, isBackgroundView);
    }
`
Here is my `flutter doctor`
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.14-pre.38, on Mac OS X 10.14.1 18B75, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
[✓] Connected device (2 available)

• No issues found!
`

**Comment by Liuzhiyang94** [comment]
I have found the way to resolve this issue.

https://github.com/flutter/flutter/issues/24679

**Comment by PoojaB26** [comment]
Can you tell us what did you do to resolve this? @Liuzhiyang94
