### ISSUE TITLE
Apple Store App reject "Performance - Accurate Metadata"

### ISSUE THREAD

**Issue by BohdanNikoletti** [flutter/flutter#29739]
## Steps to Reproduce

Deploy app to AppStore.
Get reject with.
Guideline 2.3.8 - Performance - Accurate Metadata
We noticed that the app name to be displayed on the App Store and the app name displayed on the device do not sufficiently match, which makes it difficult for users to find the app they just downloaded. The app names are:

- Name on the App Store: Автономери України￼

- Name displayed on the device: Runner ￼

I have all localizations and app has normal app name on device and simulator. 
![Simulator Screen Shot - iPhone XR - 2019-03-21 at 22 17 15](https://user-images.githubusercontent.com/16256553/54754720-8593c400-4c27-11e9-993b-921766e11693.png)
![Group](https://user-images.githubusercontent.com/16256553/54754727-8a587800-4c27-11e9-89bf-62fbb6fe1c05.jpg)

**Comment by tomalabaster** [comment]
Is "Runner" in any of your InfoPlist.strings files or your Info.plist itself?

**Comment by BohdanNikoletti** [comment]
@tomalabaster  "CFBundleDisplayName" & "CFBundleName" are correct in English and Russian too. Checked that twice. I've tried to resubmit app. And got the same reject.

**Comment by neobeppe** [comment]
I’ve the same issue, how did you solve it?

**Comment by BohdanNikoletti** [comment]
@neobeppe I didn't 😣. The story has progressed since this issue. Pls take a look on my [comment](https://github.com/flutter/flutter/issues/9767#issuecomment-488440102) on this [issue](https://github.com/flutter/flutter/issues/9767) for understand full story. And Apple even scheduled a call to discuss my reject. So, stay tuned.

**Comment by BohdanNikoletti** [comment]
> Is "Runner" in any of your InfoPlist.strings files or your Info.plist itself?

No it isn't.

**Comment by neobeppe** [comment]
> @neobeppe I didn't 😣. The story has progressed since this issue. Pls take a look on my [comment](https://github.com/flutter/flutter/issues/9767#issuecomment-488440102) on this [issue](https://github.com/flutter/flutter/issues/9767) for understand full story. And Apple even scheduled a call to discuss my reject. So, stay tuned.

Thanks, please keep me updated. I'm going to open a level-code issue to investigate further because I can't reproduce the mismatch

**Comment by neobeppe** [comment]
Today I’ve got my third rejection for the same reason with a screenshot attached. The screenshot was about a random feature in app instead of iOS springboard. How did you reach an appointment for a call?

**Comment by BohdanNikoletti** [comment]
@neobeppe  I've wrote a 3376 characters letter with attachments that contain video of opening app from TestFlight are name is correct, screenshots from Xcode and simulator. Also with links on apps in AppStore that has less functionality then my. Also yesterday apple told me that can not reach me via provided contact and left theirs contact number. But! I don't have any missed calls on my phone. So today I'm going to call them by contact they have provided to me in latest response.

**Comment by neobeppe** [comment]
Hi @BohdanNikoletti, I've got my app approved this night.
I've attached rejection thread screenshots of language and region iOS settings and springboard with app installed and sent an appeal. 
They wrote me that App Review Board is on my problem, got a new review and finally got approved

**Comment by BohdanNikoletti** [comment]
Got approved too. I don't change nothing except. Build Settings -> Packaging -> Product Name

**Comment by vifird** [comment]
@BohdanNikoletti What did you change `Build Settings -> Packaging -> Product Name` to for passing the Apple Store?  Is `$(PRODUCT_NAME)`, or `Runner`?
