### ISSUE TITLE
A problem occurred configuring root project 'android'

### ISSUE THREAD

**Issue by immanueltedi** [flutter/flutter#29731]
I have a problem with this , please help me

Launching lib\main.dart on SM A600G in debug mode...
* Error running Gradle:
ProcessException: Process "D:\ProjFlutter\hello_world\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:

A problem occurred configuring root project 'android'.

> Could not resolve all artifacts for configuration ':classpath'.

   > Could not download guava.jar (com.google.guava:guava:23.0)

      > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/23.0/guava-23.0.jar'.

         > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/23.0/guava-23.0.jar'. Received status code 502 from server: Bad Gateway

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
  Command: D:\ProjFlutter\hello_world\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by lt94** [comment]
i got the same problem... if seems that the jcenter.bintray.com website has gone away?

**Comment by KNawm** [comment]
[Bintray is down](https://status.bintray.com/), you could try replacing `jcenter()` with `mavenCentral()` twice in `android/build.gradle`.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
