### ISSUE TITLE
+ character is change by a space with some smartphone but work for some other ...  

### ISSUE THREAD

**Issue by nitneuq33** [flutter/flutter#29746]
Hello I have an urgent issue, I use URL_launcher to send sms but with some android phone I have "+" who is changed in space " ". With my galaxy s7 I havn't this issue ... I found this subject who speak about Uri.encodeComponent(numberTypedByUser) Add # sign in tel uri using Url_launcher but I tried but without result :( I tried to change + by \%2B ( it's work for my galaxy s7 but not for other smartphone) 

grade is UTF_8
 localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)

here is my code

  var Phone_Number = '$indicator$number';
   var body_text="\%2B";    //  \%2B is like +

    var uri = 'sms:$Phone_Number?body=$body_text' ;
    if (await canLaunch(uri)) {
      await launch(uri);
    }

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
