### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by dagi3d** [flutter/flutter#2974]
## Steps to Reproduce

While trying to install flutter in my Mac with the command `flutter doctor`, I get this error.
Happened with the source from commit `0eab5e6325ab` in `alpha` branch

## command

flutter doctor

## exception

The null object does not have a method 'group'.

NoSuchMethodError: method not found: 'group'
Receiver: null
Arguments: [1]

dart:core                                                         Object.noSuchMethod
package:flutter_tools/src/ios/mac.dart 72                         XCode.xcodeVersionSatisfactory
package:flutter_tools/src/ios/mac.dart 54                         XCode.isInstalledAndMeetsVersionCheck
package:flutter_tools/src/ios/ios_workflow.dart 47                IOSWorkflow.validate
package:flutter_tools/src/doctor.dart 106                         Doctor.diagnose
package:flutter_tools/src/commands/doctor.dart 23                 DoctorCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/doctor.dart 26                 DoctorCommand.runInProject.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/doctor.dart                    DoctorCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 128         FlutterCommand._run.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._run
package:flutter_tools/src/runner/flutter_command.dart 72          FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 207  FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103

**Comment by eseidelGoogle** [comment]
Turns out we pushed a bad commit to alpha, sorry. :(  This was fixed on master: https://github.com/flutter/flutter/issues/2963  FYI @abarth

**Comment by abarth** [comment]
I've updated the alpha branch just now.  Should be fixed.

**Comment by dagi3d** [comment]
Thank you for such fast response. That last change fixed the issue
