### ISSUE TITLE
Private AuthCredential creates test/simulation problems in firebase_auth

### ISSUE THREAD

**Issue by yamauchieduardo** [flutter/flutter#29750]
We need to mock Firebase Auth for tests. And we also developed a library to simulate Firebase, which works wonders for us, and took a lot of effort to develop. 

Since version 0.7.0 you introduced the AuthCredential class, which has private constructors and private fields. The private fields prevents us to read the credentials, and the private constructor prevents us to create a simulated AuthCredential.

This broke our simulations, and broke our tests.

Please, make AuthCredential constructor public. This will represent no security breach.

**Comment by yamauchieduardo** [comment]
The same issue for the class UserInfo.

**Comment by kroikie** [comment]
@yamauchieduardo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/395. Any further collaboration will be done there.
