### ISSUE TITLE
OnBackKey pressed

### ISSUE THREAD

**Issue by MrYunusOZ** [flutter/flutter#29752]
I'm writing a program, it is radio player and using **fluttery_audio** plugin.
After getting json data,i'm creating ListView with buttons, and when i tap the button the plugin plays it.
When i click to press back button the app is closing but plugin go on to play radio. there is no problem, but when i back to app with menu button, all app reloading :(
so i cant access to plugin, :(
so i cant stop to radio, :(
so i cant change. :(

There is a way saving current state??

Best regards.

**Comment by escamoteur** [comment]
You can use https://api.flutter.dev/flutter/widgets/WillPopScope-class.html to intercept the backbutton.

Please ask questions like that on stackoverflow. We cannot provide personal support here. Thanks!
