### ISSUE TITLE
want to customize MyLocation Button (Google Maps)

### ISSUE THREAD

**Issue by Kreeby** [flutter/flutter#29753]
I want to customize the MyLocation Button provided by the Google Maps, so how can I do it?

**Comment by sh0umik** [comment]
I am also having the same problem with my full screen map. Also we should be able to change its current position at least. My full screen map seems weird :( 

![Screenshot_20190406-011841-01](https://user-images.githubusercontent.com/14281876/55651850-b2d99800-580b-11e9-8fd4-ed6556d95596.jpeg)

**Comment by annakrih** [comment]
I am having the same problem The button looks different on Android and iOS. On Android it is square and in the top right corner, but on iOS it is round and in the bottom right corner.

I would want to be able to define a callback when the button is pressed and be able to style and position it. Alternatively, I would just want to be able to have the map display the location without adding the button, so I could do my own button.

**Comment by timtraversy** [comment]
The MyLocation button is created by the native Google Map and isn’t natively customizable, so there isn’t much Flutter can do about it. If you need a custom button you’d have to put a button in a `Stack` with the Google Map widget, and when it’s pressed fetch the user’s location and animate the camera.

**Comment by collinjackson** [comment]
Closing this issue since it's not in scope for the functionality of the google_maps plugin - as @timtraversy pointed out, it needs to be done as a widget on top.

Please let me know if I'm mistaken and we can revisit.
