### ISSUE TITLE
Reinstalling Android Studio breaks flutter

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#29765]
If I reinstall Android Studio, then I get

```
[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/iam/Library/Android/sdk
      but Android SDK not found at this location.
```

If I then reinstall flutter, it is fixed.

**Comment by bradyt** [comment]
Perhaps I should provide a little more detail on what uninstalling Android Studio entailed. I removed the following directories (I don't recall if some had a slightly different name), as suggested at https://nektony.com/how-to/uninstall-android-studio-on-mac.

```
~/Library/Android
~/Library/Preferences/AndroidStudio
~/Library/Preferences/com.google.android
~/Library/Preferences/com.android
~/Library/Application/Support/AndroidStudio
~/Library/Logs/AndroidStudio
~/Library/Caches/AndroidStudio
```

**Comment by bradyt** [comment]
By reinstall flutter, I mean `rm -rf ~/opt/flutter` and `cp ~/Downloads/flutter ~/opt`, more or less.

And to be clear, reinstalling Android Studio implies following the usual directions starting from any flutter instructions.

**Comment by TahaTesser** [comment]
Hi @bradyt 
Over the past few months, I've reinstalled Flutter tons of times, Android Studio both from a website and using Jetbrain toolbox on macOS, Windows, Linux as part of the job. Never had this issue.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
