### ISSUE TITLE
[video plugin] add support for custom headers

### ISSUE THREAD

**Issue by tapkain** [flutter/flutter#29763]
Hi, I'm using video plugin, but the resource where the video is located needs authentification. I cannot find where to set headers, so It would be nice to have this. Thanks

**Comment by JohnGalt1717** [comment]
Dupe of [https://github.com/flutter/flutter/issues/16466](16466)

There's a pull request outstanding but it hasn't been accepted because of question on iOS and a private command.

**Comment by tapkain** [comment]
Yes, so I'll close as duplicate
