### ISSUE TITLE
Compositing physical layers on all platforms regressed rasterizer worst case performance

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#29761]
On newer devices this doesn't seem to be an issue - e.g. on a Samsung S8 or a iPhone 8, there's actually a less significant rasterizer penalty and a greater increase in frame build time - however, on the devicelab we're seeing about a 20-25% increase in worst case rasterizer time for complex scrolling when we composite physical layers.

I'm going to rebaseline the benchmark for now, but we'd like to get it back down if we can.

/cc @liyuqian

**Comment by liyuqian** [comment]
Do you mean https://github.com/flutter/flutter/commit/5c258366d40dc7d870176559089715e1b4bdb169 caused the regression? I'm having a hard time to find the 20-25% increase in worst rasterizer time in our benchmarks... `complex_layout_scroll_perf_timeline_summary worst_frame_rasterizer_time_millis` and `complex_layout_scroll_perf_ios_timeline_summary worst_frame_rasterizer_time_millis` both look good recently.

**Comment by dnfield** [comment]
That's the right commit.

They look good because I rebaselined them - before rebaslining them they were red or just about touching red.  The increase in time is anywhere from .5ms to close to 1ms depending on the run compared to before that commit.

**Comment by liyuqian** [comment]
Ok, the increasing trend of the green bars is not so obvious to me. Maybe our benchmark is too hard to read because of those early tall red bars and the lack of ability to change time windows...

**Comment by jonahwilliams** [comment]
I was just looking at the test itself, it looks like the flakiness abated though

**Comment by dnfield** [comment]
Closing this - we've rebaselined the related benchmarks.  A good portion of this appears to be from turning on anti-aliasing for physical layers.
