### ISSUE TITLE
connectivity plugin - android build deprecation warning

### ISSUE THREAD

**Issue by danwulff** [flutter/flutter#29770]
After adding the connectivity plugin to a new flutter application (Stable Channel, migrated to androidX) a deprecation warning is present when running a build (Android only).

The warning presented:
> Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details. 

May be related to #27443 

### option 1)
- clone https://github.com/danwulff/flutter_connectivity_deprecation.git
- run `flutter run`

### option 2)
(using stable channel, v1.2.1)
- run `flutter create ___`
- migrate to AndroidX using Android Studio
- add `connectivity: 0.4.2` to pubspec.yaml
- run `flutter run` in a terminal

## Logs

flutter run
```
$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.2s
Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        11.7s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         1.2s
D/EGL_emulation(12915): eglMakeCurrent: 0xec4853c0: ver 3 0 (tinfo 0xec4833c0)
D/        (12915): HostConnection::get() New Host Connection established 0xec4a0540, tid 12937
D/EGL_emulation(12915): eglMakeCurrent: 0xec0f5740: ver 3 0 (tinfo 0xec4832a0)
Syncing files to device Android SDK built for x86...             1,644ms

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:56375/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/dwulff/development/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dwulff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dwulff/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by danwulff** [comment]
> After adding the connectivity plugin to a new flutter application (Stable Channel, migrated to androidX) a deprecation warning is present when running a build (Android only).
> 
> The warning presented:
> 
> > Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
> > Note: Recompile with -Xlint:deprecation for details.
> 
> May be related to #27443
> 
> ## Steps to Reproduce
> ### option 1)
> * clone https://github.com/danwulff/flutter_connectivity_deprecation.git
> * run `flutter run`
> 
> ### option 2)
> (using stable channel, v1.2.1)
> 
> * run `flutter create ___`
> * migrate to AndroidX using Android Studio
> * add `connectivity: 0.4.2` to pubspec.yaml
> * run `flutter run` in a terminal
> 
> ## Logs
> flutter run
> 
> ```
> $ flutter run
> Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
> "--enable-software-rendering".
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Initializing gradle...                                              0.7s
> Resolving dependencies...                                           1.2s
> Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                    
> Running Gradle task 'assembleDebug'...                                  
> Running Gradle task 'assembleDebug'... Done                        11.7s
> Built build/app/outputs/apk/debug/app-debug.apk.
> Installing build/app/outputs/apk/app.apk...                         1.2s
> D/EGL_emulation(12915): eglMakeCurrent: 0xec4853c0: ver 3 0 (tinfo 0xec4833c0)
> D/        (12915): HostConnection::get() New Host Connection established 0xec4a0540, tid 12937
> D/EGL_emulation(12915): eglMakeCurrent: 0xec0f5740: ver 3 0 (tinfo 0xec4832a0)
> Syncing files to device Android SDK built for x86...             1,644ms
> 
> 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
> An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:56375/
> For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
> ```
> flutter doctor -v
> 
> ```
> [✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
>     • Flutter version 1.2.1 at /Users/dwulff/development/flutter
>     • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/dwulff/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/dwulff/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.5.3
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 33.3.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [✓] VS Code (version 1.32.3)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 2.24.0
> 
> [✓] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
> 
> • No issues found!
> ```

**Comment by danwulff** [comment]
It looks like this is likely due to the deprecated functionality of the Android ConnectivityManager:
https://developer.android.com/reference/android/net/ConnectivityManager#TYPE_WIFI 

![image](https://user-images.githubusercontent.com/17821843/55015456-12cd7480-4faa-11e9-8a6f-9a67a7baf7b3.png)

As seen within the `getNetworkType` private method: https://github.com/flutter/plugins/blob/a822896c69cd0135aa7267aba6d825e9f4507fd3/packages/connectivity/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java#L61

**Comment by NTMS2017** [comment]
When will this get fixed. I finished my app but getting same error when I run Flutter build apk.

**Comment by NTMS2017** [comment]
.....
flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2+1/android/src/main/java/io/flutter/plugins/conBUİLD FAILED in 3m 43s                                                                                                                                                                         Running Gradle task 'assembleRelease'...                                                                                                                                       Running Gradle task 'assembleRelease'... Done                     224,5s (!)                                                                                                   Gradle task assembleRelease failed with exit code 1

**Comment by hey24sheep** [comment]
I have created a pr to fix this issue in flutter/plugins [PR](https://github.com/flutter/plugins/pull/1822)

**Comment by Naranmandakh** [comment]
But it is still getting such warning and doesn't install on android 9.0+

```
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+6/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
```

and when i install on android 9.0+ , It freeze up on **Installing build/app/outputs/apk/app.apk...**

**Comment by hey24sheep** [comment]
Okay, so it worked for me because I didn't do flutter clean and then build. 

First issue is: after flutter clean, flutter build will fail showing deprecation error

Second issue that you are getting with installation, I can't repro on my system and with physical device

**Comment by hey24sheep** [comment]
Can anyone help me on this, Why even after supresswarnings and new api code, we are getting this issue?

**Comment by hey24sheep** [comment]
Okay, I found the deprecated code.

Line 58 of ConnectivityPlugin.java is creating this issue.

```
 registrar
        .context()
        .registerReceiver(receiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
```

We will need to create two event receivers for both platforms

**Comment by edex96** [comment]
When will it be fixed?

**Comment by hey24sheep** [comment]
@edex96  I have no idea, I want to help but I don't have the time to research and fix it. A little help from community will be appreciated. Thank You.

**Comment by MrMoronIV** [comment]
Can somebody look into this? I bet a whole lot of flutter apps are relying on this package since it's the only one I can find

**Comment by hey24sheep** [comment]
@cyanglaz  It isn't fixed yet. My pr only fixed a part of it. We need to re write the event handlers as well, then only it will be fully fixed

**Comment by nk19** [comment]
i still having this issue on the latest version:
connectivity-0.4.4/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.

**Comment by edex96** [comment]
It seems most people have figured out another way to implement connectivity checking.
So they won't come across this thread because nobody searches about a problem which they don't use.

**Comment by Nico04** [comment]
> It seems most people have figured out another way to implement connectivity checking.
> So they won't come across this thread because nobody searches about a problem which they don't use.

Well it isn't my case, I still use this very handy plugin, it work very well for now, apart from the deprecation warning.

**Comment by hey24sheep** [comment]
> It seems most people have figured out another way to implement connectivity checking.
> So they won't come across this thread because nobody searches about a problem which they don't use.

It isn't my case either. We are using this in our app and we have parked the feature related to this. Many people need it.

**Comment by antoninobajeli** [comment]
I use the plugin too, and I'm facing the same problem.

**Comment by msc4266** [comment]
same problems here
_Note: ...**connectivity-0.4.4**\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a **deprecated API**._

**Comment by workerbee22** [comment]
As a first party plugin ... yes we need it.

**Comment by josepalbert95** [comment]
Same here:
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.4\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.

**Comment by nihalreddy33** [comment]
same here.

**Comment by ahzmie** [comment]
Did anyone find a way or another package to do the same functionality? I can't believe that there will be any dynamic app now that don't need such a package!

**Comment by syntaxp** [comment]
same here

**Comment by BabkenM** [comment]
same here

**Comment by iapicca** [comment]
Hi all
I see there's an open [issue](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
