### ISSUE TITLE
flutter not compatible with version control

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#29773]
If you migrate to androidx, then commit, build, etc, then checkout an earlier commit, make changes commit, build, flutter errors. If you reinstall flutter, the issue is fixed.

**Comment by bradyt** [comment]
I've got a mental note to see if the above recipe together with the issue at https://github.com/flutter/flutter/issues/28813 will work together to reproduce. I had closed the linked issue as I was not sure how to reproduce in docker.

**Comment by jmagman** [comment]
What was the error?

**Comment by bradyt** [comment]
I don't remember the error. It may require one to get the version of Android Studio from March, maybe flutter stable from March. That last thing I remember noticing, was that maybe Android Studio was showing in the logs that it was modifying .pub-cache, and that's how I was getting such a hard to reproduce issue. I think it was when I was selecting "Migrate to AndroidX". So the first time I did that, I wasn't watching logs carefully enough to see it modifying distant directories. I didn't spend much more time than I could have, narrowing down the issue and producing an error report. Presumably the error report was similar to the one I linked above.

Sorry not more helpful.

**Comment by jmagman** [comment]
I know you created this issue a year ago, it was a long shot.  We're since published https://flutter.dev/docs/development/androidx-migration, so hopefully that would have helped you track down the issue.  Closing since we probably don't have enough info for this to be actionable.  :-\
