### ISSUE TITLE
Firebase Crashlytics plugin is not compatible with swift projects

### ISSUE THREAD

**Issue by robsonfingo** [flutter/flutter#29777]
To reproduce:

$ flutter create -i swift -a kotlin test
# add firebase_crashlytics to pubspec.yaml
$ flutter run
Launching lib/main.dart on iPhone XR in debug mode...
Running pod install...                                              1.2s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Crashlytics
      A Fabric
      A Firebase
      A FirebaseAnalytics
      A FirebaseCore
      A FirebaseInstanceID
      A Flutter
      A GoogleAppMeasurement
      A GoogleUtilities
      A firebase_crashlytics
      A nanopb

    Downloading dependencies

    -> Installing Crashlytics (3.12.0)
      > Copying Crashlytics from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/Crashlytics/3.12.0-07fb1` to `Pods/Crashlytics`

    -> Installing Fabric (1.9.0)
      > Copying Fabric from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/Fabric/1.9.0-f988e` to `Pods/Fabric`

    -> Installing Firebase (5.19.0)
      > Copying Firebase from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/Firebase/5.19.0-c60d4` to `Pods/Firebase`

    -> Installing FirebaseAnalytics (5.8.0)
      > Copying FirebaseAnalytics from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalytics/5.8.0-fd72a` to `Pods/FirebaseAnalytics`

    -> Installing FirebaseCore (5.4.0)
      > Copying FirebaseCore from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/FirebaseCore/5.4.0-22a79` to `Pods/FirebaseCore`

    -> Installing FirebaseInstanceID (3.8.0)
      > Copying FirebaseInstanceID from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/FirebaseInstanceID/3.8.0-cf488` to `Pods/FirebaseInstanceID`

    -> Installing Flutter (1.0.0)

    -> Installing GoogleAppMeasurement (5.8.0)
      > Copying GoogleAppMeasurement from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/GoogleAppMeasurement/5.8.0-16240` to `Pods/GoogleAppMeasurement`

    -> Installing GoogleUtilities (5.5.0)
      > Copying GoogleUtilities from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/GoogleUtilities/5.5.0-6481e` to `Pods/GoogleUtilities`

    -> Installing firebase_crashlytics (0.0.1)

    -> Installing nanopb (0.3.901)
      > Copying nanopb from `/Users/robson/Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.901-2901f` to `Pods/nanopb`
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/robson/work/ddd/ios/Pods/Crashlytics/iOS/Crashlytics.framework and
    /Users/robson/work/ddd/ios/Pods/Fabric/iOS/Fabric.framework)

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:81:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone XR.

**Comment by leoafarias** [comment]
This has been merged
https://github.com/flutter/plugins/pull/1378

**Comment by collinjackson** [comment]
Looks like this has been fixed.

**Comment by kroikie** [comment]
@robsonfingo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/394. Any further collaboration will be done there.
