### ISSUE TITLE
How can i get  the items total height in listview?

### ISSUE THREAD

**Issue by parcool** [flutter/flutter#29781]
<img width="490" alt="loading" src="https://user-images.githubusercontent.com/12092478/54799747-73526e00-4c99-11e9-8be4-dff5d50824d5.png">

In my case, when the datas‘s height not enough to match parent, it showing a `loading` widget at the bottom. the question is how can i know the items total height to compare to `listview`'s height for invoke the `loadmore` function.

there is an another question:
at first, when the `listview` is empty,I add data and invoke the `setState()` function to render it on the `listview`,  but i don't know when it render completed so i can't do to next step as the description above. 

I don't ask the question on stackoverflow because i think it doesn't like a normal question but a issue.

**Comment by peng8350** [comment]
This problem has been bothering me for a long time.
I have two ways to solve this problem.

First Way.
You can use Scrollable.of(context) to get the ScrollPosition in your footer Widget.when position.minScrollExtent==position.maxScrollExtent, It means ScrollView has less than one page
 
Second Way:
implements one render class extends RenverSliver also can help you.In the performance Layout method, you can use constraints. precedingScrollExtent < constraints. viewportMainAxisExtent to determine whether a page is full or not.

**Comment by VladyslavBondarenko** [comment]
Closing since solved
