### ISSUE TITLE
[copy, paste, cut] dialog is scrolling with Text in TextField

### ISSUE THREAD

**Issue by Goolpe** [flutter/flutter#29796]
Hello, I tried 2 different phones, but have the same bug with textfield

 [gif with bug](https://photos.app.goo.gl/jfsgjR8JrtX9Uvwq7)

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14.3 18D109, locale ru-RU)
    • Flutter version 1.3.13 at /Users/ads/Library/flutter
    • Framework revision 59ce7d6bff (4 days ago), 2019-03-18 11:20:10 -0700
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ads/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ads/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Redmi Note 3 • 89ab2252 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by justinmc** [comment]
Thanks for the gif.  It looks like what should happen in your case is the menu should appear at the interface between your text input and the chat messages and not scroll up into the messages like that.  Here's how it works in the native Android Keep app for reference:

<img src="https://user-images.githubusercontent.com/389558/54835767-0d0d2180-4c80-11e9-96e0-2cd4ec63d349.png" width="300"></img>
<img src="https://user-images.githubusercontent.com/389558/54835768-0d0d2180-4c80-11e9-80f2-2bb8beb1b591.png" width="300"></img>
<img src="https://user-images.githubusercontent.com/389558/54835770-0da5b800-4c80-11e9-96d9-52115aa07d67.png" width="300"></img>


I'm collecting a list of text selection bugs and this positioning stuff is at the top of my list.  I hope to dig into this soon.

**Comment by Goolpe** [comment]
@justinmc issue on small device:
![Screenshot_20190710-155103](https://user-images.githubusercontent.com/18518522/60970553-e821e480-a32a-11e9-8a6b-7721357bddb6.png)

flutter: 1.8.0, 
device: ZTE BLADE A0622 • 320376181424 • android-arm • Android 7.1.1 (API 25)

**Comment by justinmc** [comment]
@Goolpe That overflow issue should be covered in this other issue: https://github.com/flutter/flutter/issues/35826
