### ISSUE TITLE
AnimatedContainer on beta doesn't animate

### ISSUE THREAD

**Issue by Shaydoth** [flutter/flutter#29799]
A simple width change of an AnimatedContainer doesn't seem to run on the latest version of the beta channel of flutter.

Using the simple example of:

```
Column(
  mainAxisAlignment: MainAxisAlignment.spaceAround,
  children: <Widget>[
    RaisedButton (
      child: Text('Animate!'),
      onPressed: () {
        setState(() {
          w = 250.0;
        });
      },
    ),
    AnimatedContainer (
      duration: Duration (seconds: 1),
      width: w,
      height: 40,
      color: Colors.red,
    ),
  ],
)
```

Upon pressing the button the value of the width will change (seen by printing it), however the animation will not occur. This does not happen when running on `Flutter (Channel master, v1.3.11-pre.39, on Mac OS X 10.14.3 18D109, locale de-DE)`.

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14 18A391, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by Shaydoth** [comment]
An addition to this is that it does not work on beta v1.3.8 either

## Flutter Doctor

[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.3.8 at /Users/rhysduggan/flutter
    • Framework revision e5b1ed7a7f (2 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rhysduggan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • Shrek's Swamp • f88a459b4e691bbc686e6e1d4c8b9d3a1817285d • ios • iOS 12.0
    • iPhone XS Max • F9EC2B7B-C5B7-49D1-9E08-2F26C302A14B     • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by Piinks** [comment]
Hi @shaydoth,
Thank you for filing this issue. Can you include a complete runnable sample of your code? 

Here I have made the code you provided runnable, but I have not been able to reproduce your issue:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Issue Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double w = 10.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Issue Demo')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            RaisedButton(
              child: Text('Animate!'),
              onPressed: () {
                setState(() {
                  w = w == 10.0 ? 250.0 : 10.0;
                });
              },
            ),
            AnimatedContainer(
              duration: Duration(seconds: 1),
              width: w,
              height: 40,
              color: Colors.red,
            ),
          ],
        ),
      ),
    );
  }
}
```

If your code is different and you are still experiencing this issue, please share it so we can better identify the issue. Thank you!

**Comment by Piinks** [comment]
The no-response bot would have closed this by now. If you would like to return and provide more information to address your issue, please feel free to re-open. :)
