### ISSUE TITLE
Cursor in TextInput is displayed incorrectly

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#298]
When the widget is created with an initial string, cursor is on the right side of the input area.
If you press in the input area to reposition the cursor, the cursor disappears entirely.

**Comment by abarth** [comment]
This sounds like two bugs:
 - [ ] When an input widget is created with an initial string, cursor is on the right side of the input area.
 - [ ] If you press in the input area to reposition the cursor, the cursor disappears entirely.

I'll look at the first one first.

**Comment by abarth** [comment]
I can reproduce the first issue.

**Comment by abarth** [comment]
The cursor no longer disappears when you tap on the input widget.  You can't reposition the cursor yet, however.  If you'd like it to be possible to reposition the cursor, please let me know.  (That's significantly more work.)
