### ISSUE TITLE
Move/hide all "development" tools in flutter_tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29805]
Occasionally users will accidentally run something like `flutter update-packages`, which may completely toast their local flutter repo. If the user isn't skilled with git, then the only fix is often times re-installation.

While these commands are important for development, they should be moved out of the regular flutter tool, or hidden on stable/beta/dev branches

**Comment by christopherfujino** [comment]
could we hide them behind a config setting? maybe something like `sdk-developer`?

**Comment by jonahwilliams** [comment]
I don't just want to hide them though, I also would likely to not have them count against our code coverage metrics :)
