### ISSUE TITLE
firebase_crashlytics build failing  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#29803]
Running with gitlab-runner 11.9.0-rc2 (227934c0)
  on docker-auto-scale 0277ea0f
Using Docker executor with image cirrusci/flutter:latest ...
Pulling docker image cirrusci/flutter:latest ...
Using docker image sha256:a12fc3c81cefcf6d1e9d200f9409fe705077ff031e0bc681cb7c822ed4425595 for cirrusci/flutter:latest ...
Running on runner-0277ea0f-project-10398232-concurrent-0 via runner-0277ea0f-srm-1553269686-d6cf190b...
Initialized empty Git repository in /builds/kw2019ltd/plants_price_flutter_app/.git/
Fetching changes...
Created fresh repository.
From https://gitlab.com/kw2019ltd/plants_price_flutter_app
 * [new branch]      master     -> origin/master
Checking out f9c2ee1e as master...

Skipping Git submodules setup
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/cirrus/sdks/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /docker-java-home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
$ flutter channel
Flutter channels:
  Hixie-patch-1
  beta
  dev
  fix-more-tool-tests-from-terminal
  gallery
  master
  revert-28919-composite_elevations
  revert-29010-re_enable_dart2js
  revert-29323-roll_branch
  stable
$ flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:    479be4447..475d93a17  master     -> origin/master
git:  * [new branch]          revert-29632-gallery_embedded_views -> origin/revert-29632-gallery_embedded_views
git: Switched to a new branch 'stable'
git: Branch stable set up to track remote branch stable from origin.
$ flutter build apk
Running "flutter packages get" in plants_price_flutter_app...        10.0s
Initializing gradle...                                             12.0s
Resolving dependencies...                                         105.1s
Running Gradle task 'assembleRelease'...                        
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.2/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-2.0.3/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.3.1+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-4.0.0+1/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.0.3/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+2/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Calling mockable JAR artifact transform to create file: /home/cirrus/.gradle/caches/transforms-1/files-1.1/android.jar/5a8ccb9080388db5e1825d860fa87203/android.jar with input /opt/android-sdk-linux/platforms/android-28/android.jar

Calling mockable JAR artifact transform to create file: /home/cirrus/.gradle/caches/transforms-1/files-1.1/android.jar/0f6f3b7bb4abb6fed6fac20f77c93544/android.jar with input /opt/android-sdk-linux/platforms/android-27/android.jar

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':firebase_crashlytics:verifyReleaseResources'.

> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

  /builds/kw2019ltd/plants_price_flutter_app/build/firebase_crashlytics/intermediates/res/merged/release/values/values.xml:276: error: resource android:attr/fontVariationSettings not found.

  /builds/kw2019ltd/plants_price_flutter_app/build/firebase_crashlytics/intermediates/res/merged/release/values/values.xml:277: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 45s
Running Gradle task 'assembleRelease'...                          226.4s (!)
Gradle task assembleRelease failed with exit code 1
ERROR: Job failed: exit code 1

**Comment by vinsalmont** [comment]
+1

**Comment by kroikie** [comment]
@kw2019ltd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/393. Any further collaboration will be done there.
