### ISSUE TITLE
Because flutter_tools depends on sockjs_client 0.3.5 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by rlecheta** [flutter/flutter#29801]
Hi,

My flutter isn't working any more.

Doesn't matter if I type:

flutter channel dev
flutter doctor
flutter update-packages --force-upgrade

All this commands shows this errror:

Building flutter tool...
Because flutter_tools depends on sockjs_client 0.3.5 which doesn't match any versions, version solving failed.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

What can I do?

**Comment by rlecheta** [comment]
I don't have proxy, nothing.. my internet is working well.

**Comment by jonahwilliams** [comment]
`flutter update-packages --force-upgrade` This command is for development on flutter, not for upgrading your local packages. You've likely put the flutter repo into an invalid state by trying to update its dependencies.

If you know how to use git, you can reset the files you've changed in the flutter root, it should be mostly pubspec.yaml files

**Comment by rlecheta** [comment]
Thank you. I'll try to reinstall flutter.

**Comment by toshoajibade** [comment]
I solved this by running **git reset --hard** from flutter root directory.
