### ISSUE TITLE
Input widget appears to not respect theme

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2980]
(reporting for a customer)

Input widget has an issue: it will have a blue label and underline regardless of the color of the app theme.

**Comment by abarth** [comment]
The code seems to say it will get the primaryColor from the theme.  How can we reproduce the issue?

**Comment by sethladd** [comment]
cc @daveshuckerow

**Comment by DaveShuckerow** [comment]
I encountered this putting together an app from scratch based on flutter init.  The code I had written was as follows:
...
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
            title: new Text('Flutter Demo'),
            backgroundColor: Colors.amber[500]),
        body: new Center(child: new Input(labelText: 'words.')));
  }
...

which produced an amber appbar with the standard blue theme coloring the Input.

Looking at it again, I'd guess that that's probably intended behavior, but I had no real way to be sure from the default setup of the app how best to colorize.  This is probably a case where setting a default option in the blank project could reduce the possibility of error -- the `theme:` parameter to the `flutter init`-output MaterialApp is not present, and so I had to guess how to set the color on the AppBar, and my intuition was to configure the AppBar directly.  

Having a simple theme set by default maybe with a primarySwatch setting to suggest that that's the appropriate way to color the app would reduce the margin for error here.

**Comment by eseidelGoogle** [comment]
Ah yes, the default theme is blue:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L61
As you've discovered, the right approach is to just change what theme you pass to your app, e.g:
https://github.com/flutter/flutter/blob/master/examples/material_gallery/lib/gallery/app.dart#L31

Without that theme information the Input wouldn't know what primary color you want.

Sounds like this is then a request to update the default template to include a Theme?
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/lib/main.dart.tmpl

**Comment by DaveShuckerow** [comment]
Yeah, that sounds like the most appropriate resolution to an issue like this.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/3020
