### ISSUE TITLE
Cannot interact when using TextField at the top of the screen

### ISSUE THREAD

**Issue by diib** [flutter/flutter#29808]
When I used TextField at the top of the screen, the following problem occurred, the layout was misplaced and could not interact.
![29808_1](https://user-images.githubusercontent.com/48837836/57187388-670c3280-6f20-11e9-8e39-0254542fa90a.png)

```
 flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.14-pre.56, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jiisd** [comment]
I had a similar problem some time ago! But I seem to have fixed that. ；）.
[https://github.com/flutter/flutter/pull/29809](https://github.com/flutter/flutter/pull/29809)
![](https://raw.githubusercontent.com/jiisd/images_temp/master/fix_flutter_issues_29808.png)

**Comment by justinmc** [comment]
This is fixed with https://github.com/flutter/flutter/pull/29809.

To get the changes, you'll need a Flutter version greater than 1.5.8, or you can use the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#master).
