### ISSUE TITLE
TextField weird behaviour

### ISSUE THREAD

**Issue by InterFelix** [flutter/flutter#29802]
I'm trying to implement a login page using flutter. I have successfully built the oauth-login, but experience a weird behaviour when the given password is wrong.
My Application should work like this:
1. display the login page
2. on press of the login button push a gateway page which uses a FutureBuilder to determine whether the login was successful (e.g the entered credentials where correct).
3. depending on the result of the future return either the main content page or the login page once again.

When I enter the password correctly, everything works as expected.
However, when I enter wrong credentials, the login page gets pushed, but every time I try to select one of the text fields to enter my credentials, the callback for the login button is called again. I can confirm it is nowhere in any onChanged callback or anything similar to this.
Also, there's a PopUpMenuButton on the same page which works as expected. Only the TextFields show this behaviour.
I use Navigator.pushReplacement for all the navigation in this case. If needed, I can provide my code for this section of the app.

**Comment by InterFelix** [comment]
Flutter Doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] VS Code, 64-bit edition (version 1.31.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
`

**Comment by InterFelix** [comment]
My Code for this Screen:
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:http/http.dart' as http;
import 'package:plancks_plans/screens/substition_plan_screen.dart';
import 'package:plancks_plans/utilities/constants.dart';
import 'package:plancks_plans/utilities/enums.dart';
import 'package:plancks_plans/utilities/data_repo.dart';

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  _login() {
    _username = _usernameController.text;
    _password = _passwordController.text;
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(
        builder: (BuildContext context) {
          return _LoginGateway(_username, _password);
        },
      ),
    );
  }

  Year _year = Year.Five;

  String _username = '';
  String _password = '';

  final TextEditingController _usernameController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('IServ-Login'),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            PopupMenuButton<Year>(
              child: Row(
                children: <Widget>[
                  Text(yearToString(_year)),
                  Icon(Icons.arrow_drop_down),
                ],
                mainAxisAlignment: MainAxisAlignment.center,
              ),
              itemBuilder: (BuildContext context) => <PopupMenuItem<Year>>[
                    PopupMenuItem<Year>(
                      value: Year.Five,
                      child: Text('5. Klasse'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Six,
                      child: Text('6. Klasse'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Seven,
                      child: Text('7. Klasse'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Eight,
                      child: Text('8. Klasse'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Nine,
                      child: Text('9. Klasse'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Ten,
                      child: Text('E-Jahrgang'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Eleven,
                      child: Text('Q1-Jahrgang'),
                    ),
                    PopupMenuItem<Year>(
                      value: Year.Twelve,
                      child: Text('Q2-Jahrgang'),
                    ),
                  ],
              onSelected: (Year result) {
                setState(() {
                  _year = result;
                });
              },
            ),
            Container(
              height: 25.0,
            ),
            Padding(
              padding: const EdgeInsets.fromLTRB(20.0, 0.0, 20.0, 0.0),
              child: Column(
                children: <Widget>[
                  TextField(
                    controller: _usernameController,
                    autocorrect: false,
                    decoration: InputDecoration(contentPadding: EdgeInsets.all(3.0), hintText: 'IServ-Name', border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(4.0)))),
                  ),
                  Container(height: 10.0),
                  TextField(
                    controller: _passwordController,
                    obscureText: true,
                    autocorrect: false,
                    decoration: InputDecoration(contentPadding: EdgeInsets.all(3.0), hintText: 'IServ-Passwort', border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(4.0)))),
                  ),
                ],
              ),
            ),
            RaisedButton(
              onPressed: () => _login(),
              child: Text(
                'Login',
                textAlign: TextAlign.center,
              ),
            )
          ],
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        ),
      ),
    );
  }
}

class _LoginGateway extends StatefulWidget {
  final String _username;
  final String _password;

  _LoginGateway(this._username, this._password);

  _LoginGatewayState createState() => _LoginGatewayState(_username, _password);
}

class _LoginGatewayState extends State<_LoginGateway> {
  final String _username;
  final String _password;

  _LoginGatewayState(this._username, this._password);

  Future<http.Response> oauthLogin(String username, String password) async {
    var response = await http.post(
      oAuthTokenEndpoint,
      headers: {'content_type': 'application/json'},
      body: {
        'client_id': oAuthClientID,
        'client_secret': oAuthClientSecret,
        'grant_type': 'password',
        'scope': 'openid profile',
        'username': username,
        'password': password,
      },
    );

    return response;
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<http.Response>(
      future: oauthLogin(_username, _password),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        switch (snapshot.connectionState) {
          case ConnectionState.active:
            return Scaffold(
              body: Container(child: CircularProgressIndicator(), alignment: Alignment.center,),
            );
          case ConnectionState.waiting:
            return Scaffold(
              body: Container(child: CircularProgressIndicator(), alignment: Alignment.center,),
            );
          case ConnectionState.none:
            return Scaffold(
              body: Container(child: CircularProgressIndicator(), alignment: Alignment.center,),
            );
          case ConnectionState.done:
            if (snapshot.hasError) {
              Fluttertoast.showToast(msg: 'Dein Login war nicht erfolgreich.');
              return Text(snapshot.error.toString());
            }
            if (snapshot.hasData) {
              if (snapshot.data.body.toString().contains('access_token')) {
                DataRepo.of(context).data.isFirstLaunch = false;
                DataRepo.of(context).data.persist();
                return SubstitutionPlanPage();
              } else {
                Fluttertoast.showToast(msg: 'Nutzername oder Passwort falsch!');
                return LoginPage();
              }
            }
        }
      },
    );
  }
}

```

**Comment by InterFelix** [comment]
What I tried so far:

- Dispose the TextEditingControllers for the TextFields in my  LoginPage in the login-function
- Use Navigator.pushAndRemoveUntil to push LoginGateway instead of pushReplacement

**Comment by InterFelix** [comment]
Maybe @zoechi could look over this and look for potential issues in my approach here...

**Comment by InterFelix** [comment]
I've since developed my app quite a lot further, however, what's stopping me from releasing it publicly is still the login problem. Someone somewhere mentioned the AsyncMemoizer, but that's exactly the opposite of what I need. It would cache the result of my future, but I always need the new result to be able to tell if a login attempt was successful. 
I still don't quite understand why my login-method keeps firing whenever I try and edit a TextField. But I noticed something interesting:
I have recently implemented a logout-Button in my app. When this button is pressed, it changes a value in DataRepo and therefore also SharedPreferences and opens up LoginScreen again. When I do this, I can log in again, no problem. Even when I log into the app and log out immediately after this, I can log in again, the weird behaviour doesn't happen.

**Comment by eseidelGoogle** [comment]
@justinmc would know if this is still valid.    The example provided isn't self-contained enough to run in dartpad.dev, so the only way to know is to inspect the code. :/

**Comment by justinmc** [comment]
This approach looks valid to me.  I was able to get a simplified version of this running on DartPad with a future that randomly resolves to success or failure: https://dartpad.dartlang.org/d0dc15fa325b75eea2c78db1242aef9e

It sounds like the problem could be from the state in `DataRepo` updating.  @InterFelix if this is still a problem for you, could you try modifying my gist code to demonstrate your problem?  Sorry for taking so long to get someone to take a look at this!

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
