### ISSUE TITLE
FlutterFragmentActivity doesn't use AndroidX Support Libraries

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#29819]
I just ran across this in my app where I'm trying to use the compat library's BiometricPrompt (or is it AndroidX library now) which requires a FragmentActivity. 

FlutterFragmentActivity currently uses the old support libraries rather than the new ones which means I couldn't use it.

My temporary workaround is to basically copy-paste the code out of FlutterFragmentActivity.java and change the support libraries to androidx:
```

// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.FragmentActivity;
import io.flutter.app.FlutterActivityDelegate;
import io.flutter.app.FlutterActivityEvents;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.view.FlutterNativeView;
import io.flutter.view.FlutterView;

public class FlutterFragmentxActivity extends FragmentActivity implements FlutterView.Provider, PluginRegistry, FlutterActivityDelegate.ViewFactory {
    private final FlutterActivityDelegate delegate = new FlutterActivityDelegate(this, this);
    private final FlutterActivityEvents eventDelegate;
    private final FlutterView.Provider viewProvider;
    private final PluginRegistry pluginRegistry;

    public FlutterFragmentxActivity() {
        this.eventDelegate = this.delegate;
        this.viewProvider = this.delegate;
        this.pluginRegistry = this.delegate;
    }

    @Override
    public FlutterView getFlutterView() {
        return this.viewProvider.getFlutterView();
    }

    @Override
    public FlutterView createFlutterView(Context context) {
        return null;
    }

    @Override
    public FlutterNativeView createFlutterNativeView() {
        return null;
    }

    @Override
    public boolean retainFlutterNativeView() {
        return false;
    }

    @Override
    public final boolean hasPlugin(String key) {
        return this.pluginRegistry.hasPlugin(key);
    }

    @Override
    public final <T> T valuePublishedByPlugin(String pluginKey) {
        return this.pluginRegistry.valuePublishedByPlugin(pluginKey);
    }

    @Override
    public final Registrar registrarFor(String pluginKey) {
        return this.pluginRegistry.registrarFor(pluginKey);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.eventDelegate.onCreate(savedInstanceState);
    }

    @Override
    protected void onDestroy() {
        this.eventDelegate.onDestroy();
        super.onDestroy();
    }

    @Override
    public void onBackPressed() {
        if (!this.eventDelegate.onBackPressed()) {
            super.onBackPressed();
        }

    }

    @Override
    protected void onStart() {
        super.onStart();
        this.eventDelegate.onStart();
    }

    @Override
    protected void onStop() {
        this.eventDelegate.onStop();
        super.onStop();
    }

    @Override
    protected void onPause() {
        super.onPause();
        this.eventDelegate.onPause();
    }

    @Override
    protected void onPostResume() {
        super.onPostResume();
        this.eventDelegate.onPostResume();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        this.eventDelegate.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!this.eventDelegate.onActivityResult(requestCode, resultCode, data)) {
            super.onActivityResult(requestCode, resultCode, data);
        }

    }

    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        this.eventDelegate.onNewIntent(intent);
    }

    @Override
    public void onUserLeaveHint() {
        this.eventDelegate.onUserLeaveHint();
    }

    @Override
    public void onTrimMemory(int level) {
        this.eventDelegate.onTrimMemory(level);
    }

    @Override
    public void onLowMemory() {
        this.eventDelegate.onLowMemory();
    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        this.eventDelegate.onConfigurationChanged(newConfig);
    }
}
```

**Comment by matthew-carroll** [comment]
@rmtmckenzie do you happen to know if Flutter using the androidx version of `FragmentActivity` would have any negative consequences on apps that are not yet using androidx libs?

**Comment by matthew-carroll** [comment]
CC @dnfield @mklim @jason-simmons @tvolkert

**Comment by rmtmckenzie** [comment]
@matthew-carroll I think if it were switched completely it probably would - apps not using the androidx libs would probably have to update to the androidx libs in that case. However it might be possible to include both versions in the jar file with different names (with a better name than what I've done here for the androidx version =D). 

This documentation from the FlutterFragmentActivity class certainly indicates that, although I don't know what having both in the jar file would mean for unit tests etc:

> Flutter does not bundle the necessary Android v4 Support library classes for this class to work at runtime. It is the responsibility of the app developer using this class to ensure that they link against the v4 support library .jar file when creating their app to ensure that {@link FragmentActivity} is available at runtime.

**Comment by matthew-carroll** [comment]
That's an interest quote about bundling.  Do you think that means that the support FragmentActivity and the AndroidX FragmentActivity are completely interchangeable?  Maybe we just need to have Flutter apps declare a dependency on the lib that they really want?

**Comment by mklim** [comment]
> Do you think that means that the support FragmentActivity and the AndroidX FragmentActivity are completely interchangeable?

AndroidX and the old Support classes are broadly [interchangeable](https://developer.android.com/jetpack/androidx/migrate#artifact_mappings), but incompatible. To the best of my knowledge trying to use both support and AndroidX libraries directly in the same source code simultaneously will result in compile time failures.

I don't think I'm totally understanding the problem and proposed solution here. @rmtmckenzie just to double check, are you using the FlutterFragmentActivity in an app [with Jetifier on in its Gradle properties](https://developer.android.com/jetpack/androidx/migrate#migrate)? We are exposing these classes from `flutter.jar`, which means that it should be possible to use Jetifier to swap out the old support classpaths in the jar already. I briefly tested this out myself on an AndroidX migrated Flutter app and was seeing working AndroidX imports, as long as Jetifier was on. Not 100% sure I'm testing the use case you're talking about though.

```java
// MainActivity.java
package com.example.stabletester;

import android.os.Bundle;
import androidx.annotation.Nullable; // <- AndroidX nullable annotation
import io.flutter.app.FlutterActivity;
import io.flutter.embedding.engine.android.FlutterFragment;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Nullable FlutterFragment test;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
    test = FlutterFragment.newInstance();
  }
}
```

```gradle
// app/build.gradle
// ....
dependencies {
    // ....
    compile "androidx.annotation:annotation:1.0.0"
    compile "androidx.fragment:fragment:1.0.0" // <- At compile time this is needed for FlutterFragment
}
```

```properties
# app/gradle.properties
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by rmtmckenzie** [comment]
Ah that's my bad. I do have jetifier enabled and am only using the androidx libraries elsewhere. I don't know that I fully understood what jetifier was doing but I've read up on it a bit more now =D.

So if I use FlutterFragmentActivity it seems that Android Studio is complaining (it doesn't recognize FragmentActivity or that FragmentActivity inherits Activity, so all the relevant methods in my activity i.e. `getIntent` aren't resolving) but if I ignore that and do a build it does work. So there's no need at all for my workaround. I should have tried building first, I just usually assume Android Studio knows what it's talking about!

**Comment by rmtmckenzie** [comment]
Thanks for looking into it though!

**Comment by mklim** [comment]
No problem! Glad it's not a blocker.

I'm seeing the same issue. I'm guessing that this has something to do with `flutter.jar` having its class paths swapped at compile time by Jetifier, but the IDE trying to find the old support classes that exist in the jar at edit time and not being able to.

I'm not sure the best way to work around this. You could potentially [manually run jetifier as a standalone tool](https://developer.android.com/studio/command-line/jetifier) on the `flutter.jar` Android Studio is using to resolve your app's Flutter dependencies. This is cumbersome and a little risky since you'd be using a locally modified `flutter.jar` from it instead of the known engine version, but I think it would update the jar same as at compile time so that the IDE would look for the right AndroidX class paths while you were editing.

IDE problems like this are a potential reason for us to migrate these usages within Flutter still. Though I think only if we were sure we could do so without causing broader regressions.

**Comment by wuyugege** [comment]
hello,i cannot import androidx libraries,can you help me to find the reason?

//app/build.gradle
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.core:core:1.0.1'
}
```
i cannot find androidx libraries in external libraries panel of android studio, and in MainActivity.java i cannot import androidx.core libraries, only androidx.annotation library can be found.

i really dont know whats wrong with my code @rmtmckenzie
