### ISSUE TITLE
Check that plugin version update makes sense on presubmit

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#29815]
We had a few cases where plugin versions were erroneously went down(0.7.1+1 -> 0.6.1+2), or went up by more than one increment (0.1.1 -> 0.1.3).

This is even more likely when there's a merge conflict with another PR that updated the plugin.

Verifying that the version went up by a single increment as part of the presubmit checks can be a good safeguard.

**Comment by mklim** [comment]
Related to flutter/plugins#27258.

**Comment by iskakaushik** [comment]
This got closed when i closed an earlier PR, not merge. ugh.
