### ISSUE TITLE
CupertinoTimerPicker needs to better handle localized layout

### ISSUE THREAD

**Issue by xster** [flutter/flutter#29825]
On french

<img width="549" alt="Screen Shot 2019-03-22 at 6 22 45 PM" src="https://user-images.githubusercontent.com/156888/54859878-9b5cc400-4ccf-11e9-9983-9c50a4263156.png">

**Comment by xster** [comment]
Rather than having the localization themselves feed in a number, I think we can just make _CupertinoTimePickerState._buildHourColumn etc a bit more dynamic. Also reference the native iOS behavior for reference.

**Comment by xster** [comment]
To leave breadcrumbs, we tested it a bit on iOS. It's hard to say exactly what happens but the column widths are actually fixed despite language and devices. It's hard to tell if the labels are just abbreviated given different language/width or the font is slightly different.

**Comment by xster** [comment]
Based on iOS testing, we should probably have a test that looks for text wrapping and for all the failed ones, go test on iOS to see how the words abbreviate and back-port them into the translation console.

**Comment by TahaTesser** [comment]
Running on iPhone 8 simulator, `CupertinoTimerPicker` looks in French 
Although there are fewer characters compared to your screenshot, I doubt this creates an issue even on physical iPhone 8

![Simulator Screen Shot - 8  - 2020-09-10 at 20 25 39](https://user-images.githubusercontent.com/48603081/92749515-ce06ea80-f3a3-11ea-9fab-ae21c5bd1d16.png)
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.121, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.121 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 6c1a29e54c (13 hours ago), 2020-09-09 20:05:05 -0400
    • Engine revision 564367b297
    • Dart version 2.10.0 (build 2.10.0-107.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details> 



Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you
