### ISSUE TITLE
Custom Keyboard Plugin

### ISSUE THREAD

**Issue by sfaizanh** [flutter/flutter#29823]
Hi is there any way to implement custom keyboard just like wix custom input keyboard [https://github.com/wix/react-native-keyboard-input](https://github.com/wix/react-native-keyboard-input) I have been looking for it in every flutter community and searched on [http://pub.dartlang.org/packages/](http://pub.dartlang.org/packages/) but couldn't find it

![example2](https://user-images.githubusercontent.com/2033963/54859447-199c8300-4d2f-11e9-9110-aa2ec8e035f8.gif)

**Comment by Im-Kevin** [comment]
https://github.com/Im-Kevin/cool_ui

**Comment by sfaizanh** [comment]
@Im-Kevin I found NumberKeyboard example but can you add same example as above so we can understand it properly.

**Comment by Im-Kevin** [comment]
Are you talking about switching keyboards? You can change this by setting KeyboardType.

**Comment by frey1esm** [comment]
https://pub.dev/packages/keyboard_actions

**Comment by ericwindmill** [comment]
+1 to this feature request. On iOS you can implement custom keyboards.

**Comment by CanRau** [comment]
The example looks like it's not actually using a custom keyboard but rather "enhances" it by adding a toolbar on top and for the colorful widgets you can replace the actual keyboard with a `Container`.
You can hide the keyboard like this
```dart
TextField(
  readOnly: true,
  showCursor: true,
  // the next line is not necessarily needed
  enableInteractiveSelection: true,
  controller: _controller,
)
```

via https://github.com/flutter/flutter/issues/16863#issuecomment-567201637
then you can build your keyboard ui and update the `TextField` via 

```dart
final String text = 'YOUR_VALUE_TO_INSERT';
final index = _controller.selection.start;
final splitText = _controller.text.split('').toList();
splitText.insert(index, text);
final newText = splitText.join('');
final offset = index + text.length;
// NOTE: don't set text & selection separately as it'll make the caret flicker
_controller.value = TextEditingValue(
  text: newText,
  selection: TextSelection.collapsed(offset: offset),
);
```

Or maybe I don't understand the gif 🤔 

Remember that your users might miss certain features when you replace the actual keyboard, like auto correct, dictionaries, emojis, swipe to type etc 🤷‍♂️ 

Just realized it's pretty old, maybe someone else might still benefit from it 🎉

**Comment by anoop4real** [comment]
+1 to this feature request... both platforms natively supports custom keyboards

**Comment by justinmc** [comment]
See TextInputControl from https://github.com/flutter/flutter/pull/76072

I'm wondering exactly how people expect this to work, is this a Flutter-drawn drawer that looks like a keyboard and sends input into the Flutter app's TextFields? Or is this a keyboard app, usable in all other apps including non-Flutter apps?

Related: https://github.com/flutter/flutter/issues/151876
