### ISSUE TITLE
Keyboard 'moving in'-animation seems incorrect on iOS

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#29826]
When the keyboard appears on iOS, it should smoothly push any element to the top, until the keyboard is completely visible (if resizeToAvoidBottomPadding is true). 

**The issue is perfectly documented here:**
https://stackoverflow.com/questions/54563854/how-to-animate-flutter-layout-on-keyboard-appearance

**Comment by xster** [comment]
Indeed, something we need to support. Duping into #19279 however since there's already an issue for it.
