### ISSUE TITLE
TextField's cursor above the Leaning upward In ios device when input emoji

### ISSUE THREAD

**Issue by czronaldo11** [flutter/flutter#29839]
## Steps to Reproduce

TextField's cursor above the Leaning upward In ios when input [emoji]

## Logs

```
```

```
```

```
```
![Image](https://user-images.githubusercontent.com/11837386/54865969-2c539e00-4da9-11e9-9131-2aa918c867e3.png)

**Comment by justinmc** [comment]
I'm not seeing this on master:

![Screen Shot 2020-04-06 at 11 22 54 AM](https://user-images.githubusercontent.com/389558/78591879-fab54580-77f8-11ea-852a-c4384d0dc12b.png)

If anyone is still seeing this problem, can you please update with steps to reproduce?

There are some somewhat similar existing issues like https://github.com/flutter/flutter/issues/31818.

**Comment by justinmc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/28192
