### ISSUE TITLE
Image_picker flickers when barcode_scan and image_picker are used together

### ISSUE THREAD

**Issue by ihqrbb** [flutter/flutter#29837]
Image_picker flickers when barcode_scan and image_picker are used together

The problem arises in android. permission. CAMERA.

Barcode_scan requires android.permission.CAMERA.

Image_picker does not need

How can I solve this problem?

**Comment by cyanglaz** [comment]
Should be fixed by https://github.com/flutter/plugins/pull/1519. Closing this issue now. If any related issue has been found after applying using the newest Image_picker, please open a another issue with details.
