### ISSUE TITLE
Invalid request method.

### ISSUE THREAD

**Issue by chaozhouzhang** [flutter/flutter#29833]
Waiting for your authorization...
Authorization received, processing...
Invalid request method
pub finished with exit code 69

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
