### ISSUE TITLE
deleteBackward or keyPress event for Textfield

### ISSUE THREAD

**Issue by SnowXD** [flutter/flutter#29845]
One of the requirements for the project I am working on currently requires performing an action when delete key is received by the TextField widget. Particularly, there is no way to detect that delete was tapped when there is no text in the TextField.

I'd like to propose an onDelete event, or onKeyPress(keyCode) event, propagation to the end user. Please let me know your thoughts.

**Comment by jonahwilliams** [comment]
I believe the soft keyboard on either Android or iOS doesn't actually expose key level events like delete or key press, it only tells us what the current string is.

For Android, see https://stackoverflow.com/questions/4886858/android-edittext-deletebackspace-key-event.

cc @gspencergoog

**Comment by SnowXD** [comment]
The engine already taps into `UIKeyInput` (iOS) and `InputConnection` (Android), we could leverage this into forwarding keys to the plugin. Sample implementation for iOS in https://github.com/SnowXD/engine/commit/fc5197d101645e001de9d8d50974758282cbb095.

**Comment by kangfarih** [comment]
Is this already implemented for current version?

**Comment by SnowXD** [comment]
@kangfarih Nope. I am going to rework it as discussed in the PR. See https://github.com/flutter/engine/pull/8606

**Comment by psyanite** [comment]
I believe this is related to `https://github.com/flutter/flutter/issues/14809`

**Comment by VladyslavBondarenko** [comment]
Please follow up on https://github.com/flutter/flutter/issues/14809, closing as duplicate
