### ISSUE TITLE
Error building app in Release 

### ISSUE THREAD

**Issue by abumoallim** [flutter/flutter#29846]
I have completely migrated my project manually to AndroidX and followed all the steps provided in https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

But still when I try to run ` flutter run --release` , it gives me this error

`FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not find androidx.test.runner:1.1.1:.                        
     Required by:                                                       
         project :app                                                   
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org    `

**Comment by Kretin1** [comment]
I have this problem too. Refactor > Migrate to AndroidX didn't work so I also had to update manually.

I have been able to compile a release version by reverting to:

testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        //testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

and:

androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    //androidTestImplementation 'androidx.test.runner:1.1.0'
    //androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

but I'm concerned that this might cause problems in the release build.

**Comment by abumoallim** [comment]
> I have this problem too. Refactor > Migrate to AndroidX didn't work so I also had to update manually.
> 
> I have been able to compile a release version by reverting to:
> 
> ```
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>         //testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
> ```
> 
> and:
> 
> ```
>     androidTestImplementation 'com.android.support.test:runner:1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
>     //androidTestImplementation 'androidx.test.runner:1.1.0'
>     //androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
> ```
> 
> but I'm concerned that this might cause problems in the release build.
> 
> Edit: So I forgot I'd reverted back to com.android.tools.build:gradle:3.2.1 from com.android.tools.build:gradle:3.3.0 because cloud_firestore has a dependency that isn't compatible with AndroidX. Going back to gradle:3.3.0 fixes the above problem, but restores the firestore problem.

Yeah I did the same to overcome this problem

**Comment by Kretin1** [comment]
So it wasn't a firestore problem, but I hadn't updated the kotlin version at the top of the file from 1.2.7 to 1.3.0. Since then I've been getting inconsistent results. One time it identified 2 plugins that weren't AndroidX compatible yet, but in the process of sorting that out it's now lost androidx.test.runner:1.1.0 again.

If I comment out the those two lines it will compile, but I still have the 2 incompatible plugins in there. I don't know if that will cause problems or not. Everything I've read says it will, but it seems happy to compile so...

**Comment by yash365** [comment]
i am also getting exactly the same problem i updated manually the file mentioned in [https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#not-recommended-manually-migrate-your-app](url) and also i used the plugins in pubspec.yaml which are AndroidX compatible

Do we need to add the kotlin version code in the build.gradle files ?

**Comment by Kretin1** [comment]
My /android/build.gradle has it at the top of the file:
```
buildscript {
    ext.kotlin_version = '1.3.0'
```

**Comment by blasten** [comment]
Please follow the migration steps on https://flutter.dev/docs/development/androidx-migration. Let me know if you still experiment issues.
