### ISSUE TITLE
TextField set maxLines to four.some mobile cann't show whole 4 lines

### ISSUE THREAD

**Issue by czronaldo11** [flutter/flutter#29843]
## Steps to Reproduce

TextField set maxLines to four.some mobile cann't show whole 4 lines

## Logs

```
```

```
```
[âˆš] Flutter (Channel dev, v1.3.13, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    â€¢ Flutter version 1.3.13 at D:\flutter
    â€¢ Framework revision 59ce7d6bff (5 days ago), 2019-03-18 11:20:10 -0700
    â€¢ Engine revision e75f6de01f
    â€¢ Dart version 2.2.1 (build 2.2.1-dev.1.1 None)

[âˆš] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    â€¢ Android SDK at E:\Users\Administrator\AppData\Local\Android\sdk
    â€¢ Android NDK location not configured (optional; useful for native profiling
      support)
    â€¢ Platform android-28, build-tools 28.0.3
    â€¢ ANDROID_HOME = E:\Users\Administrator\AppData\Local\Android\sdk
    â€¢ Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    â€¢ All Android licenses accepted.

[âˆš] Android Studio (version 3.2)
    â€¢ Android Studio at E:\Program Files\Android\Android Studio
    â€¢ Flutter plugin version 29.1.1
    â€¢ Dart plugin version 181.5656
    â€¢ Java version OpenJDK Runtime Environment (build

![Image](https://user-images.githubusercontent.com/11837386/54866458-d255d700-4dae-11e9-928f-e6498aeb57ad.png)

**Comment by TahaTesser** [comment]
Hi @czronaldo11 
Are you still experiencing this issue?
Thank you

**Comment by VladyslavBondarenko** [comment]
@czronaldo11 
I hope it's fixed,
comment please if it's not so and I will reopen it.
Thank you
