### ISSUE TITLE
flutter upgrade crashing

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#29853]
Immediately upon executing `flutter upgrade`:
```
Failed to stash local changes: ProcessException: Process "git" exited abnormally:
fatal: not a git repository (or any of the parent directories): .git
  Command: git stash push -m flutter-upgrade-from-v1.3.13
```

**Comment by jonahwilliams** [comment]
Unfortunately it looks like you landed on the single commit that code was in master before it was rolled back. If you're familiar with git, you could enter the flutter repo and run `git reset --hard v1.3.12`

**Comment by creativecreatorormaybenot** [comment]
@jonahwilliams Thanks, I executed the command in `flutter (master)`:

```
$ git reset --hard v1.3.12
HEAD is now at a1bee54fd Roll engine 5b09204e3037..e75f6de01fee (2 commits) (#29537)
```

However, this leaves me with a different issue:

```
Downloading Dart SDK from Flutter engine e75f6de01fee738eb15f24efb0ec549587009f1a...
Unknown operating system. Cannot install Dart SDK.
```

**Comment by creativecreatorormaybenot** [comment]
Nervermind, only happened in *Git Bash*.

**Comment by josvos** [comment]
This now happened to me when upgrading from 1.3.13 to 1.3.14.  When retrying I see:
```
Failed to stash local changes: ProcessException: Process "git" exited abnormally:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  Command: git stash push -m flutter-upgrade-from-v1.3.14
```
Then I did ``git reset --hard v1.3.13`` (hint given above), but this didn't help, as doing a new upgrade again results in:
```
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x67
version=2.2.1-dev.1.1.flutter-None (Thu Mar 14 15:39:18 2019 +0000) on "linux_x64"
thread=12579, isolate=flutter_tools.snapshot:main()(0x18c0aa0)
  [0x00007fdf0ccc4fa4] Unknown symbol
  [0x00007fdf0ccc4fa4] Unknown symbol
-- End of DumpStackTrace
/home/jos/flutter1/flutter/bin/flutter: line 177: 12128 Aborted                 (core dumped) "$DART" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
```
Can this issue be reopened or can someone explain what's going on here?

**Comment by MayurPrajapati** [comment]
After getting [this](https://github.com/flutter/flutter/issues/29853#issuecomment-476546623) issue i re-ran `flutter upgrade` and it worked for me

**Comment by josvos** [comment]
UPDATE: I now installed the most recent Studio/SDK on another, freshly installed system (Linux Fedora 29 with all updates), everything worked with Flutter 1.4.7 (I could generate working apps), but when I upgrade to 1.4.8 dart crashes in exactly the same way:
```
Building flutter tool...

===== CRASH =====
si_signo=Segmentation fault(11), si_code=128, si_addr=(nil)
version=2.2.1-dev.2.0.flutter-None (Thu Mar 28 00:48:30 2019 +0000) on "linux_x64"
thread=27922, isolate=flutter_tools.snapshot:main()(0x1e48da0)
  [0x00007f99110e5d60] Unknown symbol
  [0x00007f99110e5d60] Unknown symbol
-- End of DumpStackTrace
/home/jos/DEVEL/flutter/bin/flutter: line 177: 27543 Aborted                 (core dumped) "$DART" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
```
When doing `flutter upgrade` again it starts saying `Already up to date.` and then continues with `Upgrading engine...`.

Any suggestions?

**Comment by creativecreatorormaybenot** [comment]
@josvos Please open another issue for that. This is not related to the problem in the original question.

**Comment by josvos** [comment]
@creativecreatorormaybenot I will open a new issue when I have collected some more info. Upgrading from 1.4.8 to 1.4.9 on system #2 did work without a crash, upgrading from 1.4.7 to 1.4.9 on system #1 still crashes...

**Comment by shashi2602** [comment]
$ flutter upgrade
git status failed: ProcessException: Process "git" exited abnormally:
error: bad signature
fatal: index file corrupt
  Command: git status -s


i got this error while upgarding the flutter  any help

**Comment by JasonSleigh** [comment]
@shashi2602 

I ran into the same issue after updating Linux, I managed to fix it with...

`get init`
`flutter upgrade`

**Comment by AR-Kathiresh** [comment]
ProcessException: Process exited abnormally:
fatal: unable to access 'https://github.com/flutter/flutter.git/': Could not resolve host: github.com

what to do..? please help me
