### ISSUE TITLE
I can't run my app on my android device 

### ISSUE THREAD

**Issue by Anizou** [flutter/flutter#29855]
> Launching lib\main.dart on SM G9600 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:60392/ws

everything is good by `flutter doctor` .

**Comment by Schuyten** [comment]
Did you manage to resolve this issue? I'm trying to resolve it for two days now, but no luck yet..

**Comment by blasten** [comment]
This was caused by a bug in the Android Q system image. Please update the system image on Android Studio and try again.
