### ISSUE TITLE
CircularProgressIndicator() is being rendered as a circle in Flutter v1.3.13

### ISSUE THREAD

**Issue by Melvin-Abraham** [flutter/flutter#29850]
Seems like Flutter v1.3.13 messed up the `CircularProgressIndicator()`. The following snippet of code worked fine and rendered a perfect material progress spinner until v1.3.13 where it renders it as an outlined circle rather than a spinner...

## Steps to Reproduce

```dart
...
Center(
    child: Container(
        height: 70.0,
        width: 70.0,
        child: CircularProgressIndicator(
            backgroundColor: Colors.blue,
        ),
    ),
)
...
```

### Output
---

![](https://dl2.pushbulletusercontent.com/ysqUgryqhsO2MkjY0FgEN1ftNkvrxcE8/Screenshot_2019-03-23-23-27-10-75.png)

## Logs

```
C:\Users\DELL> flutter doctor -v

[√] Flutter (Channel dev, v1.3.13, on Microsoft Windows [Version 10.0.17763.379], locale en-IN)
    • Flutter version 1.3.13 at E:\flutter
    • Framework revision 59ce7d6bff (5 days ago), 2019-03-18 11:20:10 -0700
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.1 None)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Android
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.io/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.2)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • CPH1859 • A6JNN7HYZHVCRWDU • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by dark-chocolate** [comment]
@Melvin-Abraham You should use 
```
valueColor: AlwaysStoppedAnimation(Colors.blue),
```

**Comment by Melvin-Abraham** [comment]
@dark-chocolate Thanks a lot. That worked for me...
I'm still curious about the difference between `backgroundColor` and `valueColor`.

**Comment by dark-chocolate** [comment]
@Melvin-Abraham `backgroundColor` is actually the color to applied in the background of the spinner which is by default is `transparent`, and `valueColor` is the color of the moving portion of the spinner. So, generally `valueColor` is the color of your app `primaryAccent` and in your case `valueColor` was blue and you also made `backgroundColor` blue, which is why you didn't see spinner moving. Hope that helps, don't forget to close the issue.

**Comment by Melvin-Abraham** [comment]
@dark-chocolate Thanks for such a wonderful explanation... 👏
