### ISSUE TITLE
FirebaseApp.configure not setting options

### ISSUE THREAD

**Issue by nikeshjobanputra** [flutter/flutter#29856]
```
Future<void> loadFromFirebase() async {

  var options = new FirebaseOptions(
    googleAppID: "***",
    apiKey: "**",
    databaseURL: "**",
  );
  
  final FirebaseApp app = await FirebaseApp.configure(
    name: "name", 
    options: options
  );

  var database = new FirebaseDatabase(app: app);
}
```

When `app` is created the `options` property shows a number of errors  

![image](https://user-images.githubusercontent.com/15944178/54872240-03d3a000-4db9-11e9-9a46-add5af83c4d6.png)

Then when creating `database` the databaseURL is null which means it somehow has not been set up correctly in `app` (as my understanding is that it should grab it from `app`)

The logs don't indicate anything about this issue. What am I missing?

**Comment by kroikie** [comment]
@nikeshjobanputra

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/392. Any further collaboration will be done there.
