### ISSUE TITLE
Is it possible to run my own service from MainActivity?

### ISSUE THREAD

**Issue by woozbooz** [flutter/flutter#29851]
I want to run my own service from MainActivity.
Is it possible?

**Comment by woozbooz** [comment]
When i try to use code like this:

**Comment by pedromassango** [comment]
You should use MethodChannel to start your service from the Flutter code. Read more here:
https://flutter.dev/docs/development/platform-integration/platform-channels

**Comment by woozbooz** [comment]
pedromassango

**Comment by Hixie** [comment]
There doesn't seem to be anything for us to do here so I'm going to close this issue.
