### ISSUE TITLE
Exporting ios .ipa file without developer account

### ISSUE THREAD

**Issue by LoYungSum** [flutter/flutter#29862]
A youtube video: https://youtu.be/kBnUB48wf2w

I try to export the app to a .ipa file without developer account. But when I try to "Archive" it in xcode. It run into an error.

`"Runner" requires a provisioning profile. Enable development signing and select a provisioning profile in the project editor.`

I have already select the signing to "Ad Hoc Code Sign". But it seems to be still not working.

**Comment by welldone217** [comment]
mark it .me too .

**Comment by AirborneEagle** [comment]
yeah,  Is this do-able?

**Comment by jmagman** [comment]
This worked for me: https://stackoverflow.com/a/55963713

I don't think this would be a common workflow for the average Flutter developer, so it doesn't require Flutter-specific documentation.

Closing.

**Comment by omidraha** [comment]
I would like to run this command:

`flutter build ios --release`

With this option:

`CODE_SIGNING_ALLOWED=NO`

Where is associated file to apply this option?
