### ISSUE TITLE
 When flutter is mixed with the original, the problem of gestures

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#29889]
`原生跳转到一个 flutter 页面，这个flutter 页面有个横向滚动的列表，这个横向滚动的列表与原生的侧滑返回事件冲突。怎么解决这种滑动手势冲突`

The native jumps to a flutter page that has a horizontal scrolling list that conflicts with the native skid back event. How to solve this sliding gesture conflict

**Comment by pp126** [comment]
直接让google的工程师帮你开发算了

**Comment by OHeroJ** [comment]
@pp126 那怎么控制两者的冲突，你牛逼你来

**Comment by pp126** [comment]
@OHeroJ 问题你都描述不清楚还怎么聊？？  原生页面跳flutter  意味着进入flutter所依附的activity，你的意思是原生界面的事件带入了后者？？   再者，侧滑返回一般都是边缘触摸，Android有边缘手势管理的方法，不是很方便就能判断是否禁止？

**Comment by OHeroJ** [comment]
> @OHeroJ 问题你都描述不清楚还怎么聊？？ 原生页面跳flutter 意味着进入flutter所依附的activity，你的意思是原生界面的事件带入了后者？？ 再者，侧滑返回一般都是边缘触摸，Android有边缘手势管理的方法，不是很方便就能判断是否禁止？

你是个 android 开发者，那 ios你懂？

**Comment by OHeroJ** [comment]
问题很清楚，一个页面中有个横向滚动的Listview,  页面本身有个侧滑的手势，当 Listview  的元素先左滑然后在右滑的时候，系统的侧滑手势优先了

**Comment by pp126** [comment]
我只是跟你用Android打个比方而已，系统的侧滑手势的禁用与开启，一个状态不就能判断？？ios一般是默认开启，有相应的api来控制是否打开。

**Comment by pp126** [comment]
而且ios也是边缘手势，这里的手势比Android还要简单，只涉及到左边缘右滑

**Comment by OHeroJ** [comment]
看来你没读懂我的问题

**Comment by Aa940728039** [comment]
> 我只是跟你用Android打个比方而已，系统的侧滑手势的禁用与开启，一个状态不就能判断？？ios一般是默认开启，有相应的api来控制是否打开。

你就说怎么解决，瞎比比

**Comment by OHeroJ** [comment]
> 原生跳转到一个 flutter 页面，这个flutter 页面有个横向滚动的列表，这个横向滚动的列表与原生的侧滑返回事件冲突。怎么解决这种滑动手势冲突

https://github.com/flutter/flutter/issues/27071

**Comment by OHeroJ** [comment]
[Flutter 和 iOS 之间的 Battle：手势交互听谁的？](https://www.infoq.cn/article/Cq3Uk6q8eIhFBqyKwwD6)

**Comment by iapicca** [comment]
Hi @OHeroJ 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/27071)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
