### ISSUE TITLE
CircleAvatar not quite cropping to circle

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#29880]
Hey! Firstly, I'm sorry that I haven't produced a minimum code to document this behavior, but I don't have this much time. Reproducing it should be really simple.

## Steps to Reproduce

```dart
return ListView(
  children: [
    const SizedBox(height: 32.0),
    CircleAvatar(
      radius: 48.0,
      backgroundImage: NetworkImage(vm.avatarUrl),
    ),
  ],
);
```

This `ListView` is the `Drawer.child`. My image isn't quite a circle tho...

![image](https://user-images.githubusercontent.com/4085280/54883073-9d568c80-4e61-11e9-94f0-ca2896e12a67.png)

If I close this `CircleAvatar` in a `Center`, everything is okay:

![image](https://user-images.githubusercontent.com/4085280/54883081-b19a8980-4e61-11e9-9955-13bbbe687259.png)

## Logs

No logs.

```
[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.648],
    locale pl-PL)
    • Flutter version 1.3.8 at D:\flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)
```

**Comment by diegoveloper** [comment]
That's because the `CircleAvatar` is trying to fit all the width of the `ListView` parent widget (because there are no constraints). 
You can also use `Align` widget as a parent widget of your `CircleAvatar`

        Align(
                      alignment: Alignment.centerLeft,
                      child: CircleAvatar(
                        radius: 48.0,
                        backgroundImage: NetworkImage(vm.avatarUrl),
                      ),
                    ),
