### ISSUE TITLE
Error building Application in Debug and Release both

### ISSUE THREAD

**Issue by abumoallim** [flutter/flutter#29887]
Suddenly my app is showing this error :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:15.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kimlet** [comment]
It's not flutter's bug, check you network first please

**Comment by rchabot32** [comment]
I have the same issue, it started around 17:30 GMT-4

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
         project :app > com.google.android.gms:play-services-places-placereport:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       9.0s
Gradle task assembleRelease failed with exit code 1

**Comment by abumoallim** [comment]
> It's not flutter's bug, check you network first please

My internet is working fine, Still I am getting this error.

**Comment by abumoallim** [comment]
> 17:30 GMT-4

Yeah something around that. I was continously working for hours and suddenly near the time your specified, I started getting this error. I am unable to understand why suddenly. Now I am unable to build and I need to complete the project.

**Comment by comeonbuddy** [comment]
I have the exact same issue, for a few days now, unable to build android. iOS builds fine tho. 
Let me know if you find a solution.

**Comment by ADARSHAGNIHOTRI** [comment]
> I have the exact same issue, for a few days now, unable to build android. iOS builds fine tho.
> Let me know if you find a solution.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> 
> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> > Could not resolve com.google.android.gms:play-services-location:15.+.
> > Required by:
> > project :app > project :location
> > > Failed to list versions for com.google.android.gms:play-services-location.
> > > Could not list versions using M2 pattern '[https://raw.github.com/g123k/ShortcutBadger/master/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])](https://raw.github.com/g123k/ShortcutBadger/master/%5Borganisation%5D/%5Bmodule%5D/%5Brevision%5D/%5Bartifact%5D-%5Brevision%5D(-%5Bclassifier%5D)(.%5Bext%5D))'.
> > > Could not get resource 'https://raw.github.com/g123k/ShortcutBadger/master/com/google/android/gms/play-services-location/'.
> > > Could not GET 'https://raw.github.com/g123k/ShortcutBadger/master/com/google/android/gms/play-services-location/'. Received status code 400 from server: Bad Request
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 21s
> Finished with error: Gradle task assembleDebug failed with exit code 1

Getting the same error in flutter even though ios build is fair enough. please give a sol if you get one.
thanx in advance.

**Comment by sergioahv15** [comment]
Same issue here:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:15.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Could not list versions using M2 pattern 'https://raw.github.com/g123k/ShortcutBadger/master/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://raw.github.com/g123k/ShortcutBadger/master/com/google/android/gms/play-services-location/'.
               > Could not GET 'https://raw.github.com/g123k/ShortcutBadger/master/com/google/android/gms/play-services-location/'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by zhenghow93** [comment]
A workaround:

Instead of:
`implementation com.google.android.gms:play-services-location:15.+`

use this:
`implementation com.google.android.gms:play-services-location:15.0.0`

or whichever version that you intend to use, just make sure you SPECIFY the exact version instead of leaving it as 15.+

However, this is not a permanent solution. This seems to happen when we import our own maven repo that's hosted on github.
Anyone has a solution, teach us senpai!

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

For future I want to underline the temporary fix proposed by @zhenghow93

> A workaround:
> 
> Instead of:
> `implementation 'com.google.android.gms:play-services-location:15.+'`
> 
> use this:
> `implementation 'com.google.android.gms:play-services-location:15.0.0'`
> 
> or whichever version that you intend to use, just make sure you SPECIFY the EXACT version instead of leaving it as 15.+
> 
> However, this is not a permanent solution. This seems to happen when we import our own maven repo that's hosted on github.
> Anyone has a solution, teach us senpai!

Thanks for your contribution.
