### ISSUE TITLE
Migration to android X not work

### ISSUE THREAD

**Issue by sinsarath** [flutter/flutter#29881]
in android project :
![image](https://user-images.githubusercontent.com/42288051/54883192-dd376700-4e95-11e9-8374-0916c9e93b41.png)

in flutter project :
![image](https://user-images.githubusercontent.com/42288051/54883209-05bf6100-4e96-11e9-969f-22b08cb98d53.png)

**Comment by abumoallim** [comment]
I think you missed the very first line of migration 


    In android/gradle/wrapper/gradle-wrapper.properties change the line starting with distributionUrl like this:

distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
