### ISSUE TITLE
Date picker accent color doesn't change with theme

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#2989]
Load up the gallery app, and go into components, and then Date Picker. See how the accent colors are purple for CANCEL and OK. Then, change the theme to Dark. Load the Date Picker up again.

Expected:

Not sure, but I don't expect Purple color for CANCEL and OK.

Actual:

Purple for CANCEL and OK

**Comment by HansMuller** [comment]
The MD spec has an DatePicker illustrations for the dark theme: https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers. 

![image](https://cloud.githubusercontent.com/assets/1377460/14126556/91463806-f5c6-11e5-92e0-6094b8dce000.png)

The spec isn't specific about what colors are to be used:

> The selected day is indicated by a filled circle. The current day is indicated by a different color and type weight.

Perhaps we should make the selection color configurable.

**Comment by DaveShuckerow** [comment]
The issue I have is more noticeable here:
![image](https://cloud.githubusercontent.com/assets/14947366/14128880/b15295a0-f5d9-11e5-84f8-7aec7f6f71ae.png)

This is from the material_gallery example app, built from alpha yesterday.  The day-theme picker defaults to blue coloring, regardless of the accent color in the app but it should use the same yellow color.

**Comment by abarth** [comment]
I created a label for date picker issues.  It probably makes sense to address them all at once.  I should have time later this week or early next week.

**Comment by HansMuller** [comment]
I have a bunch of DatePicker fixes in the works right now, should have a PR up today.

**Comment by abarth** [comment]
Oh, great.
