### ISSUE TITLE
'package:flutter/src/material/slider.dart': Failed assertion: line 128 pos 15: 'value >= min && value <= max': is not true.

### ISSUE THREAD

**Issue by dhrubajyoti** [flutter/flutter#29896]
## Steps to Reproduce

1. I we use slider or carousel we play any audio or video the press back button and then come back on same index. Then its crash and sow attached page.
![IMG_9537](https://user-images.githubusercontent.com/97309/54899900-cdc11980-4ea7-11e9-97d0-15ed746da2de.PNG)
 
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by HansMuller** [comment]
If you can provided a small self-contained app that demonstrates this problem, we'll be happy to look into it.

CC @clocksmith

**Comment by dhrubajyoti** [comment]
Same issue I also facing.

**Comment by dhrubajyoti** [comment]
import 'package:audioplayers/audio_cache.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'rhymesHome.dart';

import 'package:carousel_slider/carousel_slider.dart';
import 'package:cached_network_image/cached_network_image.dart';

int currentPage = 0;
bool playing = true;

//AudioPlayer advancedPlayer;
AudioCache audioCache;
AudioPlayer advancedPlayer = AudioPlayer();

List<T> map<T>(List list, Function handler) {
  List<T> result = [];
  for (var i = 0; i < list.length; i++) {
    result.add(handler(i, list[i]));
  }
  
  advancedPlayer.onPlayerCompletion.listen((event) { 
    playing = false;
  });
  return result;
}

 class rhymesPlayCarousel extends StatefulWidget {
  final int rhymesDataIndex;
  // receive data from the FirstScreen as a parameter
  rhymesPlayCarousel({Key key, @required this.rhymesDataIndex}) : super(key: key);
  @override
  _rhymesPlayCarouselState createState() => _rhymesPlayCarouselState(rhymesDataIndex:rhymesDataIndex);
}

class _rhymesPlayCarouselState extends State<rhymesPlayCarousel> {
   int rhymesDataIndex;
  // receive data from the FirstScreen as a parameter
  _rhymesPlayCarouselState({Key key, @required this.rhymesDataIndex});


  Duration _duration = new Duration();
  Duration _position = new Duration();

  get _durationText => _duration?.toString()?.split('.')?.first?.substring(2) ?? '0.0';
  get _positionText => _position?.toString()?.split('.')?.first?.substring(2) ?? '0.0';

 
    play(aurl) async {
      int result = await advancedPlayer.play(aurl);
      if (result == 1) {
        // success
      }
      else
      print('Fail to Play Audio');
    }

  void initPlayer(){  print('inside initPlayer'); print(rhymesDataIndex);
        advancedPlayer.stop();
        play(rhymesData[rhymesDataIndex]["rhymeAudioUrl"]);
   // advancedPlayer = new AudioPlayer();
    audioCache =  AudioCache(fixedPlayer: advancedPlayer);

    advancedPlayer.durationHandler = (d) => setState(() {
      print('D >>>');
      print(d);
      _duration = d;
    });

    advancedPlayer.positionHandler = (p) => setState(() {
   //   print('P >>');
  //    print(p);
    _position = p;
    });

    
  //  await audioPlayer.setUrl('clicking.mp3');
    
 //   audioCache.play(rhymesData[rhymesDataIndex]["rhymeAudioUrl"]);

  }

    Widget slider() {
    return Slider(
        activeColor: Color.fromRGBO(255, 255, 255, 0.8),
        inactiveColor: Color.fromRGBO(255, 255, 255, 0.4),
        value: _position.inSeconds.toDouble(),
        min: 0.0,
        max: _duration.inSeconds.toDouble(),
        label: 'max',
        onChanged: (double value) { print('Slider Value - ');
          print(value);
          setState(() {
            seekToSecond(value.toInt());
            value = value;
          });
        });
  }

  void seekToSecond(int second){
    Duration newDuration = Duration(seconds: second);

    advancedPlayer.seek(newDuration);
  }

  Widget playBody(BuildContext context){

      return Container(
        
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            
            Row(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children:[

                         
                
              Container( 
                height: 152,
                width:MediaQuery.of(context).size.width,
                padding: EdgeInsets.fromLTRB(20.0, 0.0, 20.0, 20.0 ),
                decoration: const BoxDecoration(
                  color: Color.fromRGBO(0, 0, 0, 0.2),                  
                ),
                        
              child: new Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                   Text("<< Swipe >>", style: new TextStyle(fontSize: 15.0, color: Color.fromRGBO(255, 255, 255, 0.9))),
                   Row(mainAxisSize: MainAxisSize.max, mainAxisAlignment: MainAxisAlignment.center,  children: [

                     playing ? new IconButton(
                          onPressed: (){
                            advancedPlayer.pause();
                            playing = false;
                            setState(() {});
                          },
                          iconSize: 48.0,
                          tooltip: 'Paused',
                          icon: new Icon(Icons.pause),
                          color: Color.fromRGBO(255, 255, 255, 0.8))
                      :    
                      new IconButton(
                          onPressed: () {
                            advancedPlayer.resume();
                            playing = true;
                            setState(() {});
                          },
                          iconSize: 48.0,
                          tooltip: 'Play',
                          icon: new Icon(Icons.play_arrow),
                          color:Color.fromRGBO(255, 255, 255, 0.8)),
                      
                      new IconButton(
                          onPressed: () {
                            advancedPlayer.stop();
                            playing = false;
                            setState(() {});
                          },
                          iconSize: 48.0,
                          tooltip: 'Stop',
                          icon: new Icon(Icons.stop),
                           color:Color.fromRGBO(255, 255, 255, 0.8)),
                      
                    ]),

                   slider(),
                   Text(
                          _position != null
                              ? '${_positionText ?? ''} / ${_durationText ?? ''}'
                              : _duration != null ? _durationText : '',
                          style: new TextStyle(fontSize: 15.0, color: Color.fromRGBO(255, 255, 255, 0.8) ),
                     //     textAlign: TextAlign.center,
                        )
  
                ], 
              ),
                         
      

        ),



              ]
            )
          ],
        )
        
        

      );

  }

  @override
  void initState() {
    print('object in Play');
    // TODO: implement initState
    super.initState();
    initPlayer();
  }

 Widget appBarWidget (){
   return AppBar(
          title: Text(rhymesData[rhymesDataIndex]["rhymeName"]),
          leading: 
              IconButton(
                icon: new Icon(Icons.arrow_back_ios),
                onPressed: () {
                  advancedPlayer.stop();
                  playing = false;
                  Navigator.of(context).pop();
                  // Route route = MaterialPageRoute(builder: (context) => RhymesHome(title: 'Chotoder Bangla Chora'));
                  //           Navigator.push(context, route);
                },
              ),
          backgroundColor: Color.fromRGBO(172, 50, 54, 1),       
          );
 }

  @override
  Widget build(BuildContext context) {
    final mainSlider = CarouselSlider(
                      viewportFraction: 1.0,
                     // width: MediaQuery.of(context).size.width,
                      height:MediaQuery.of(context).size.height - 75,
                      aspectRatio: 2.0,
                      initialPage: rhymesDataIndex,
                      autoPlay: false,
                      enlargeCenterPage: true,
                      items: map<Widget>(
                        rhymesData,
                        (index, i) {
                          return Container(
                            child: playBody(context),
                            decoration:  BoxDecoration(
                              image: DecorationImage(
                                image: CachedNetworkImageProvider(rhymesData[rhymesDataIndex]["rhymeImage"]), fit: BoxFit.fill,
                              ),
                            ),
                            
                          );
                        },
                      ),
                      onPageChanged: (index) {
                        rhymesDataIndex = index;
                    //    print(rhymesDataIndex);
                        advancedPlayer.stop();
                      //  audioCache.play(rhymesData[rhymesDataIndex]["rhymeAudioUrl"]);
                        play(rhymesData[rhymesDataIndex]["rhymeAudioUrl"]);
                        playing=true;
                        setState(() {
                        });
                      },
                    );

    return MaterialApp(
      title: 'Bangla Rhymes',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: appBarWidget(),
        body: ListView(children: <Widget>[
          Padding(
              padding: EdgeInsets.symmetric(vertical: 0.0),
              child: Column(children: [
                Container(
                  alignment: AlignmentDirectional(0.0, 0.0),
                  child: mainSlider,
                  ),

              ])),
        ])
      ),
    );
    
  }
}

**Comment by shadyshrif** [comment]
any updates? i have the same issue exactly!

**Comment by rahulk8** [comment]
I also i have issue in A audio Player App.
package:flutter/src/material/slider.dart': Failed assertion: line 132 pos 15: 'value >= min && value <= max': is not true.

**Comment by vbv1** [comment]
Hi, 
I have an audio player inside my flutter app. The same issue is occuring for me randomly once the file is playing or has finished playing. 

Has anyone found a solution to this yet ?

**Comment by Row7** [comment]
I have the same error on emulator (Nexus S). I don't know why but In my case the problem has not appeared again when installing the apk on a real device (Xiaomi Note 4).

**Comment by rakeshghasadiya** [comment]
I have issue and found solution.  

 maxValue = maxValue >0?maxValue:0;
progress = maxValue>progress?progress:maxValue;

max value and progress always set positive and progress always <= max value

 Slider(
                        max:maxValue,
                        value: progress,
                        onChanged: onSeek,
                      )

**Comment by rakeshghasadiya** [comment]
I have same issue and found solution.

maxValue = maxValue >0?maxValue:0;
progress = maxValue>progress?progress:maxValue;

max value and progress always set positive and progress always <= max value

Slider(
max:maxValue,
value: progress,
onChanged: onSeek,
)

**Comment by isaacgg** [comment]
For me just setting `max` and `min` (and of course make sure that `max > min`) properties of my `RangeSlider` solved this issue. I guess it would be the same for the `Slider` widget.

**Comment by ShahoodHussain77** [comment]
@dhrubajyoti 
I am having the same issue. And the fix was to hot restart. Because the previous state value was less then ma current min value and performing hot reload does not changes the app state.

**Comment by jbrantl8** [comment]
> @dhrubajyoti
> I was having the same issue. And the fix was to hot restart. Because the previous state value was less then my current min value and performing hot reload does not changes the app state.

Hi @dhrubajyoti , did you come up with a good way to circumvent the possibility of the state value being updated without full sync and the app throwing this error and crashing?

**Comment by islam-Ellithy** [comment]
I have solved it by the following methods

  double progress() => max() > position?.inMilliseconds?.toDouble()
      ? position?.inMilliseconds?.toDouble()
      : 0.0;

  double max() => (duration.inMilliseconds ?? 0.0).toDouble();

**Comment by islam-Ellithy** [comment]
I have solved it by the following methods

```
  double progress() => max() > (position?.inMilliseconds ?? 0).toDouble()
      ? (position?.inMilliseconds ?? 0).toDouble()
      : 0.0;

  double max() => (duration.inMilliseconds ?? 0.0).toDouble();

```

**Comment by parasthekoder** [comment]
This also happens when you put two sliders on top of each other and use Switch to toggle between them. I was building a temperature Slider with option to switch between Celsius and Fahrenheit.
```
                 Switch(
                    value: _tempInCelsius,
                    onChanged: (value) {
                      setState(() {
                        _tempInCelsius = value;
                      });
                    },
                  ),
 _tempInCelsius ? _celsiusSlider(context) : _fahrenheitSlider(context),
```
```
  Widget _celsiusSlider(BuildContext context) {
    return CustomSlider(
      value: _initialTCValue,
      label: "Temperature",
      min: 0,
      max: 50,
      onChange: (value) {
        _finalTCValue = value;
      },
    );
  }

  Widget _fahrenheitSlider(BuildContext context) {
    return CustomSlider(
      value: _initialTFValue,
      label: "Temperature",
      min: 32,
      max: 122,
      onChange: (value) {
        _finalTFValue = value;
      },
    );
  }
```

**Comment by TahaTesser** [comment]
Hi @dhrubajyoti 
There are multiple solutions in this thread, please try them 

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
