### ISSUE TITLE
the comment of file flutter/packages/flutter/lib/src/widgets/app.dart  has error

### ISSUE THREAD

**Issue by clilystudio** [flutter/flutter#29894]
flutter/packages/flutter/lib/src/widgets/app.dart

line: 876

`
///  2. [Locale.languageCode] and [Locale.countryCode] only
`

should be:

`
///  2. [Locale.languageCode] and [Locale.scriptCode] only 
`

line: 879, 880

serial no is wrong

**Comment by HansMuller** [comment]
CC @GaryQian
