### ISSUE TITLE
Programmatically selecting a marker on google map

### ISSUE THREAD

**Issue by scbm** [flutter/flutter#29899]
Is there currently a way to select a marker programmatically?

similar to the iOS sdk below:
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html#a13d41c8eafc158f95bd7e4d0b052c8f5

**Comment by ZeroCool00** [comment]
@scbm check this [marker selection with object data](https://stackoverflow.com/questions/54084934/flutter-dart-add-custom-tap-events-for-google-maps-marker/54820209#54820209)

here is the output video
[recording](https://streamable.com/q4doe)

**Comment by AndrewPetrovics** [comment]
Why was this issue closed?

From my understanding, there is currently not a way to programmatically select a marker on google maps.

We need this functionality in our app to provide a map view similar to AirBnb's.

@scbm, will you please consider re-opening this issue?

**Comment by nafis042** [comment]
@scbm did you find any way to select the marker Programmatically? If so then, please share here. otherwise please re-open the issue

**Comment by cataCostea** [comment]
any updates?

**Comment by viltiki** [comment]
> any updates?

Maybe this https://github.com/flutter/flutter/issues/33481#issuecomment-536334663

**Comment by chickenblood** [comment]
It seems to me that the reason this is not available in the Flutter GoogleMaps plugin is that it is available in the iOS SDK, but not in the Android SDK: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html

**Comment by kalittles** [comment]
> It seems to me that the reason this is not available in the Flutter GoogleMaps plugin is that 'selectedMarker' is available in the iOS SDK, but not in the Android SDK: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html

Does this imply that there is no way to programatically select the marker on Android at all, then?
If that's the case, we'd be gated by an implementation for the Android SDK before even dreaming about getting this functionality using Flutter.

**Comment by chickenblood** [comment]
> > It seems to me that the reason this is not available in the Flutter GoogleMaps plugin is that 'selectedMarker' is available in the iOS SDK, but not in the Android SDK: https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html
> 
> Does this imply that there is no way to programatically select the marker on Android at all, then?
> If that's the case, we'd be gated by an implementation for the Android SDK before even dreaming about getting this functionality using Flutter.

I looked into it and succeeded on the iOS side, but hit a wall with Android. Unless there is a more knowledgeable Android dev here who knows otherwise, I don't think this is possible yet.

**Comment by ephrimlawrence** [comment]
The [place_marker](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/place_marker.dart) example does implements similar effects. It selects the marker by the markerId and changes the icon color using the [copyWith](https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/Marker/copyWith.html) method.

This [example](https://gist.github.com/ephrimlawrence/6445f3471a5aa2efe3bf0678b780b9b6)  uses page view builder to programmatically select the a marker while the user is scrolling.

**Comment by cyanglaz** [comment]
Shout out to @giancarlopro who added this feature in https://github.com/flutter/plugins/pull/2181.
It should be available in 0.5.23+1 and above!
I am going to close the issue.

**Comment by Panarin-U** [comment]
> The [place_marker](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/place_marker.dart) example does similar thing. It selects the marker by the markerId and changes the icon color using the [copyWith](https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/Marker/copyWith.html) method.
> 
> This [example](https://gist.github.com/ephrimlawrence/6445f3471a5aa2efe3bf0678b780b9b6) uses page view builder to programmatically select a marker whilst the user is scrolling.

@ephrimlawrence thank a lot!!
