### ISSUE TITLE
There was a bit of noise in the videos recorded by camera plugin on IOS

### ISSUE THREAD

**Issue by lmgh88** [flutter/flutter#29893]
I use the latest version of `camera ` plugin to record videos.But I found that there was a bit of noise at the beginning of the videos recorded by the plugin on IOS, while it goes well in Android. Also,I found that the example given by official has the same problem. It seems that it goes well while I use the earphone to collect audio.
I was wondering if anyone is aware of this issue or can offer advice on how to work around them. Thank you!
[link](https://github.com/flutter/plugins/blob/master/packages/camera/example/lib/main.dart)

**Comment by Toolenaar** [comment]
I have the same issue. You can hear it at the beginning of this video. 

https://firebasestorage.googleapis.com/v0/b/hiretime-staging.appspot.com/o/video%2F1558181125609..mp4?alt=media&token=1a4c64c3-ae88-4242-81c9-e33b2216c5b0

I also found that when i use the same CameraController to record a second video. This does not happen

**Comment by lmgh88** [comment]
> @lmgh88 did you find a solution ?
> 
> I have the same issue. You can hear it at the beginning of this video.
> 
> https://firebasestorage.googleapis.com/v0/b/hiretime-staging.appspot.com/o/video%2F1558181125609..mp4?alt=media&token=1a4c64c3-ae88-4242-81c9-e33b2216c5b0
> 
> I also found that when i use the same CameraController to record a second video. This does not happen

I still have no solution yet

**Comment by Toolenaar** [comment]
I finally found the Solution. On iOS after initialising the CameraController you need to call:

```
await controller.prepareForVideoRecording();
```

This removed the weird click for me

**Comment by dannycortesv** [comment]
I tried it, and still having that noise at the beginning....
