### ISSUE TITLE
Remove Java keyboard static

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#299]
When there are multiple PlatformViews, we don't have a way for Mojo service clients to specific which view they are associated with. There's a comment in PlatformViewAndroid:

    // TODO(eseidel): We need per-view services!

**Comment by abarth** [comment]
We now support view-specific services.  The task that remains here is to remove the statics and provide the keyboard service directly on the view

**Comment by krisgiesing** [comment]
Flutter side is merged, working on Mojo side now (since the code is duplicated there too).

**Comment by krisgiesing** [comment]
Just realized there is similar static state in InputServiceImpl.java. I couldn't find the equivalent to this class on the Flutter side, not sure if it's a mojo-specific issue.

**Comment by abarth** [comment]
There's no equivalent in Flutter.

**Comment by abarth** [comment]
I believe @krisgiesing did this.

**Comment by krisgiesing** [comment]
I did remove the static on the Flutter side. On the Mojo side, after talking with Jeff Brown it appears that it's not worth trying to remove it until his view manager code is in place.

**Comment by abarth** [comment]
We should probably change the `roll.py` script to not clobber Flutter's keyboard impl with the version from mojo.git then.  In the most recent roll, I needed to manually restore Flutter's copy.

**Comment by krisgiesing** [comment]
Ugh, I didn't realize this would occur. Let's sync on Monday and I can put something in place to avoid this problem.

**Comment by abarth** [comment]
I think we just need to delete this line:

https://github.com/flutter/engine/blob/master/sky/tools/roll/roll.py#L87

**Comment by Hixie** [comment]
What's the story with `KeyboardServiceImpl.java` now then? Does Flutter own its own copy or is the Mojo version the master version?

**Comment by Hixie** [comment]
I assume based on https://github.com/flutter/engine/commit/3c47bd48777b44f0d9a2dae55fbadcb1a37721f1 that Flutter has its own copy now.

**Comment by abarth** [comment]
Correct
