### ISSUE TITLE
Lost 'on tap' event of Card when scroll a list tapping on a native view iOS

### ISSUE THREAD

**Issue by pisa97** [flutter/flutter#29906]
Hi,
I have a problem. I have a list of cards in flutter and a banner inside this list embedded using native UiKitView in iOS. When I scroll the list by tapping on this native view I lost the event 'on tap' into the Card object of the flutter list. Anyone know something about this?

This is my card code:
` final Widget testCard = new Card(
                    color: getRightColorForCells(itemPosition),
                    child: new InkWell(
                      onTap: () {
                        // define function on tap handler
                        print("tapped a card");
                        createInterstitialAd()
                          ..load()
                          ..show();
                      },
                      child: Column(
                        children: [
                          getLogoChannelAndTitle(todo),
                          startAndEndDate(todo),
                          infoAboutChannel(todo),
                          getInfoMovie(todo, context),
                          getInfoSerie(todo, context),
                        ].where(notNull).toList(),
                      ),
                    ));`

This is my Widget for banner:
` Widget getPub(int itemPosition, BuildContext context) {
    bool notNull(Object o) => o != null;
    // AdmobBannerSize bannerSize = AdmobBannerSize.LARGE_BANNER;

    if (itemPosition % 4 != 0 && itemPosition != 0) {
      return null;
    } else {
      return Container(
          child: Column(
              children: <Widget>[
        SizedBox(child: UiKitView(viewType: 'AdView'), width: MediaQuery.of(context).size.width, height: 250,)
      ].where(notNull).toList()));
    }
  }`

Thank you!

**Comment by escamoteur** [comment]
Have you tried IgnorePointer?

Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
