### ISSUE TITLE
Android high memory usage?

### ISSUE THREAD

**Issue by supermnemonic** [flutter/flutter#29902]
## Steps to Reproduce

1. Create new flutter starter project
2. Run on device (Android, my device: vivo 1610 2GB RAM)
3. And inside observatory.
![Screen Shot 2019-03-25 at 16 16 41](https://user-images.githubusercontent.com/5440931/54908438-7f992e00-4f1a-11e9-8720-9f44591020d8.png)

**Notice current memory 132.9MB for this simple starter project. Is this normal?**

## Analyze

No issues found! (ran in 2.5s)

## Doctor

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

**Comment by pisa97** [comment]
Hi, I think you should run your project in release mode. Try this flutter run --release.

**Comment by supermnemonic** [comment]
Hi @pisa97 , how can I check memory usage in release mode?

**Comment by escamoteur** [comment]
you should use profile mode and use the Dart DevTools to monitor your memory.

**Comment by escamoteur** [comment]
As long as there isn't real problem I will close this for now.
