### ISSUE TITLE
play back speed functionality for video player is missing

### ISSUE THREAD

**Issue by JONA-Cureambit** [flutter/flutter#29900]
I want to allow user to change the play back speed (1x, 2x...) of video while watching same but unfortunately there is no method available in video_player plugin to implement this functionality.

**Comment by goyourfly** [comment]
+1

**Comment by Aaron009** [comment]
@iapicca I still can't find the relevant API, is there an example?

**Comment by luckypal** [comment]
https://github.com/flutter/plugins/pull/1400#issuecomment-570912974

**Comment by yyqqing** [comment]
+1

**Comment by ChristianKleineidam** [comment]
It would be really great if the PR could be merged.

**Comment by ditman** [comment]
Published [video_player v0.11.0](https://pub.dev/packages/video_player/changelog), which contains the playback speed feature!
