### ISSUE TITLE
double-slash in import doesn't give analysis errors, but fails at compile time

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#29909]
Open `lib/main.dart` in the `flutter_gallery` app and update the `import` to have two slashes:

```dart
import 'gallery//app.dart';
```

There are no analysis errors as a result of this, however running the app will spit out a lot of compilation errors:

```
Launching lib/main.dart on iPhone XS Max in debug mode...

Compiler message:
lib/gallery//demos.dart:7:8: Error: Error when reading 'lib/gallery/demo/all.dart': No such file or directory
import '../demo/all.dart';
       ^
lib/gallery//demos.dart:99:18: Error: Getter not found: 'ShrineDemo'.
      routeName: ShrineDemo.routeName,
                 ^^^^^^^^^^
lib/gallery//demos.dart:100:51: Error: Method not found: 'ShrineDemo'.
      buildRoute: (BuildContext context) => const ShrineDemo(),
                                                  ^^^^^^^^^^
lib/gallery//demos.dart:107:18: Error: Getter not found: 'FortnightlyDemo'.
      routeName: FortnightlyDemo.routeName,
                 ^^^^^^^^^^^^^^^
lib/gallery//demos.dart:108:45: Error: Method not found: 'FortnightlyDemo'.
      buildRoute: (BuildContext context) => FortnightlyDemo(),
                                            ^^^^^^^^^^^^^^^
```

I would expect this to either work, and the `//` is just treated like a `/` or it should give an analysis issue. I don't know which is correct (@bwilkerson - wdyt?).

**Comment by bwilkerson** [comment]
I agree that URIs should be handled consistently across tools. I'm not sure which is correct. I'm fairly certain (though I haven't double checked the code) that analyzer just uses the class `Uri` to do all of its manipulation, and I would also expect the other tools to handle it the same way.

But in any case, I doubt that this is a flutter specific issue, so we might want to move it to the SDK repository.

**Comment by DanTup** [comment]
You're right, I tried again and could repro outside Flutter (I think it might be the `../` prefix whereas I tried with another folder earlier). I'll move there.

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/sdk/issues/36337 with a clear repo.
