### ISSUE TITLE
Scrollables do not obey MediaQuery devicePixelRatio 

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#29916]
A client in Google is trying to scale the contents of their screen to other screen factors using a combination of Transform and creating a new MediaQuery. Something along these lines:

```dart
Transform(
  transform: Matrix4.diagonal3Values(transformScale, transformScale, 1.0),
  child: MediaQuery(
    data: parentMediaQuery.copyWith(
      size: virtualSize,
      devicePixelRatio: transformScale * parentMediaQuery.devicePixelRatio),
    child: child),
);
```

This works pretty well for their intended use case (e.g. the touch input coordinates are transformed correctly). However, they noticed that the drag gesture is not scaling properly. They worked around this by modifying the device pixel ratio in the embedder. Discussion with @chinmaygarde and others have indicated this is a heavy weight solution and we should instead look into fixing this in the framework; hence this issue.

**Comment by Hixie** [comment]
I don't understand how this would work? e.g. what should we do to pointer events that are routed to multiple widgets that each have a different device pixel ratio?

It would be helpful to have a code sample that shows the weird behaviour.

**Comment by mehmetf** [comment]
Are you saying having a `devicePixelRatio` as part of MediaQuery does not make sense? It is already odd for me to think that an app would need to specify different **device**PixelRatio's for different parts of its widget tree.

customer:dream is looking for changing this at the application level and their solution currently is to change it at `window` so that it is globally applied which means putting the configuration in the embedder. @dballesteros7 who asked for this might be able to provide a better explanation of their use case.

**Comment by goderbauer** [comment]
To better understand this it would be helpful to have a minimal runnable example that shows how this doesn't work. Currently, I don't 100% follow as to what the issue is...

 @mehmetf To answer your question: We do currently allow multiple MediaQuery in the same app that have different devicePixelRatios... I am wondering if that actually makes sense, though...

**Comment by Hixie** [comment]
@mehmetf I'm not saying anything, I'm trying to understand the desire.

**Comment by mehmetf** [comment]
There has been internal conversations around this. Posting here FTR:

From @goderbauer:

> Quick update: I am prototyping if it is possible for us to honor transforms for PointerEvents to see if that's feasible and how much of a breaking change that would be (The system has been designed to not honor them, as documented in https://master-api.flutter.dev/flutter/gestures/PointerEvent-class.html).
> 
> If this doesn't work out, we still have the devicePixelRatio adjustment on the FlutterView as a fallback.
> 
> One other thought we had on that one: Instead of adjusting it in the FlutterView, have you investigated if it would be feasible for Android to lie and give the FlutterView the devicePixelRatio you want as a responds to its call to getDisplayMetrics().density

**Comment by mehmetf** [comment]
The clarification asked by @goderbauer above: 

> I can reproduce the issue there that Scrollables don't stick to your finger anymore after inserting a Transform. This is also documented here: https://master-api.flutter.dev/flutter/gestures/PointerEvent-class.html

**Comment by Hixie** [comment]
Triage meeting update: we are working on this actively. Please stay tuned.
