### ISSUE TITLE
Flutter webview doesn't support "mailto:" and "tell:" functionality. Also I am unable to open storage, gallery, Camera from webview Why? 

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#29910]
Is there any fix to that other than making a flutter button and putting URL launcher plugin?

**Comment by Sarthaktydy** [comment]
I come up with a solution as a temporary fix for this issue, It requires another plugin named "URL_launcher"
What I did :-
navigationDelegate: (NavigationRequest request){
                    if(request.url.contains("mailto:")){
                      launch(request.url);
                      return NavigationDecision.prevent;
                    }
                    else if (request.url.contains("tel:")){
                      launch(request.url);
                      return NavigationDecision.prevent;
                    }
                  },

So whenever we try to open anything that isn't supported by "webview_flutter" plugin it directs to us at error page,we can prevent that by NavigationDecision.prevent and at the same time I'm using "Url_launcher" plugin to launch the URL , since "URl_launcher" supports "mailto:" and "tel:"  functionality it will do the work.

**Comment by techximumsolutions** [comment]
https://stackoverflow.com/q/56421218/9489285

**Comment by HemantSharmaVB** [comment]
I am using WebView_flutter to use WebView but when I click on Mailto: it going on Page not Found. if i use url_launcher to handle mailto: link it open Default mail app but My page also going PAGE NOT FOUND
https://stackoverflow.com/q/56421218/9489285

**Comment by Sarthaktydy** [comment]
> I am using WebView_flutter to use WebView but when I click on Mailto: it going on Page not Found. if i use url_launcher to handle mailto: link it open Default mail app but My page also going PAGE NOT FOUND
> https://stackoverflow.com/q/56421218/9489285

You need to use navigationDelegate to prevent navigation. Answered you on the StackOverflow, Kindly check and let me know if it works or not.
