### ISSUE TITLE
Flutter for Sublime Text

### ISSUE THREAD

**Issue by JatinPandey941** [flutter/flutter#29915]
Please tell that how can I use flutter on sublime text. VS Code and Android Studio use very much ram, and do not work smoothly when I open the emulator,
but sublime text works fine with emulator, so please tell how can I use flutter in sublime text. I am looking for a flutter extension for sublime text just like the extension in vscode.

**Comment by DanTup** [comment]
There isn't an official Flutter plugin for Sublime. There is a Dart package but it hasn't been updated in a while and may have some issues (see https://github.com/guillermooo/dart-sublime-bundle/issues/586).

Another possible route to Dart/Flutter support would be using the [LSP Server](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md). This requires use of an LSP plugin for Sublime and doesn't include syntax highlighting, but it does support the other language features completion, quick-fixes, Flutter refactors, sorting, formatting, etc.

There are no instructions for setting this up for Sublime (yet?) but if you have a go, I'd be interested to hear how you get on. I can't vouch for any of the Sublime LSP plugins, but if there are any issues with the server, I can help diagnose and/or fix.

**Comment by DanTup** [comment]
I had a quick go at setting this up and got some of the way - I'm getting errors reported and squiggles, however the quick fixes aren't as expected:

<img width="519" alt="Screenshot 2019-03-25 at 21 24 20" src="https://user-images.githubusercontent.com/1078012/54955255-ab310e00-4f44-11e9-99d9-e9906e12f6e1.png">

I had to install the other Dart extension to get syntax highlighting, and then I set my LSP config like this:

```js
// Settings in here override those in "LSP/LSP.sublime-settings",

{
  "clients":
  {
    "dart":
    {
      "command": ["/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart", "/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot", "--lsp", "--instrumentation-log-file", "/Users/danny/Dev/Logs/lsp.sublime.txt"],
      "scopes": ["source.dart"],
      "enabled": true,
      "syntaxes": ["Packages/Dart/Dart.tmLanguage"],
      "languageId": "dart"
    }
  }
}
```

I think there would be some work to make this work well (ideally having the existing Dart package resurrected or a new one created), but probably not a huge amount. I'm not a Sublime user so I don't think I'm well-placed to support it, but I'm happy to provide some assistance with the LSP-side of it if someone wants to pick it up.

**Comment by JatinPandey941** [comment]
Thank You very much! But it will be better if you can develop a flutter extension for sublime text.
________________________________

**Comment by DanTup** [comment]
> it will be better if you can develop a flutter extension for sublime text

It would be great if there was official Flutter support for all editors, but there are so many out there that the Dart/Flutter team building them all would take time away that could otherwise spent making Dart and Flutter better.

I think having an extension built by a Sublime user would also result in a much better quality experience than non-Sublime users building it. I remain open to assisting with the LSP side if any Sublime users want to pick this up :-)

**Comment by devoncarew** [comment]
Yeah, to echo what Danny said, we generally focus on providing a first class integrated experience in a few tools - IntelliJ, VS Code, and Android Studio - and then provide tools, protocols, and docs to allow community members to support the longer tail of editors (Sublime, VIM, Emacs, ...). We'd be very happy to support a community effort for improved Sublime support, via docs, protocols (like LSP), and advice.

**Comment by DanTup** [comment]
Closing this since there aren't current plans for the Flutter team to do this, but as mentioned above, the tooling to build on top of (both LSP, and the Flutter tooling APIs) are supported by the Dart & Flutter tools. If anyone picks this up and would like advice/pointers, please do reach out!

**Comment by safield** [comment]
DanTup. You should start implementing a Sublime Flutter debugger and lsp extension. Then enable sponsor on the repo, and I will dump all my GME profits in there for you! TY :)
