### ISSUE TITLE
Surprising behavior of ValueNotifier (doesn't notify on certain changes)

### ISSUE THREAD

**Issue by ravenblackx** [flutter/flutter#29922]
ValueNotifier<SomeProto>, for example, doesn't notify in the case that
```
SomeProto a = new SomeProto();
a.setSomeInt(5);
SomeProto b = new SomeProto();
b.setSomeInt(5);
valueNotifier_ = a;  // listeners are notified.
valueNotifier_ = b;  // listeners are not notified.
```

The cause of this surprising behavior is that ValueNotifier uses the == operator of the contained object to determine whether the value has changed.

The description of ValueNotifier says "When the value is replaced, this class notifies its listeners", which suggests that this is not the intended behavior in this case (and, indeed, if the notifier were supposed to be triggered only on inner content changing then the current behavior also fails at that, since
```
valueNotifier_ = a;
a.setSomeInt(6);
```
would not provoke a notification.)

I have a patch that fixes this and adds a test, will make a PR shortly.

**Comment by najeira** [comment]
SomeProto is overriding == operators, right?

I think that it is correct behavior not to notify because "a" and "b" is the same value and are not "replace".

**Comment by ravenblackx** [comment]
Yes, SomeProto in this case overrides == operators. I think "value" refers to the 'value' contained by the ValueNotifier though, which *is* replaced, just by something which the == operator says is similar.

If the intent is to notify when ValueNotifier<T>.value's == operator against its previous value would return false, under the current implementation that intent is also unsuccessful, as described in the original report, because valueNotifier_.someSubValue = [a new value] does not trigger a notification.

I can't think of any case where one would specifically want to *not* be notified that a value has been replaced with a similar value (but has a different instance), and also not be notified if the inner contents of the value have changed.

But I did encounter an existing use where the behavior was the unexpected thing, resulting in a button being unresponsive if pressed more than once without a different button being pressed in between, which is how I came to be looking at this code in the first place.

Note, in the case that "a" and "b" are actually the *same* value, not just operator== similar, eg.
```
SomeProto a = new SomeProto();
a.setSomeInt(5);
SomeProto b = a;
valueNotifier_ = a;
valueNotifier_ = b;
```
Then I would agree that it's correct not to notify (and my PR matches that behavior). But if a and b are distinct, even if similar, then I would contend that the value was definitely replaced.

I would be open to a counterproposal that instead of changing the behavior, the comment for ValueNotifier could be updated to say "when the value is replaced with a value for which operator== doesn't match the previous value..." but I don't think the current behavior matches the described behavior. To me the current behavior looks more like a result of just not having considered the impact of operator== overrides, rather than an explicitly intentional behavior, because operator== is *usually* the same thing as calling identical() (and a lot of us would habitually treat it as equivalent from other languages).

**Comment by jonahwilliams** [comment]
ValueNotifier implies value semantics, which means that `operator.==` is the correct choice. If you've overriden `operator.==` incorrectly you are absolutely in for a world of pain, regardless of what the behavior of ValueNotifier does.

> because operator== is usually the same thing as calling identical()

This is not true in my experience. Overriding `operator.==` is how one creates value class like behavior.

**Comment by ravenblackx** [comment]
Hm, implied value semantics from the term 'value' is a pretty good argument for using ==. But then, again, ValueNotifier fails at that implied contract because changing the value *without* reassigning it to valueNotifier_.value (or even changing the value in place *and* reassigning it to that new value) will not notify the listeners.

Also I don't think ValueNotifier very strongly implies value semantics, because it's not at all clear what you'd call this template if you meant "content reference change notifier" which is what this *mostly* already is, apart from the not notifying if the content reference changes and the value doesn't.

Which is to say, the current behavior is:
Reference changes and value changes because the newly referenced object is different: notify
Only value changes: do not notify
Only reference changes: do not notify
Nothing changes: do not notify
Reference changes and value changes, but not at the same time: do not notify

Example of that last case, because it's not very clear, where SomeContainer is a class with the obvious overridden ==:
```
var a = SomeContainer(5);
var b = SomeContainer(6);
valueNotifier_ = a;  // A notification happens, assuming the previous value did not == someContainer(6).
a.contents = 6;  // No notification of this change, valueNotifier_.set value isn't even entered.
valueNotifier_ = b;  // No notification because 'previous' [silently updated] value a now == b.
```

If you're comfortable with that being the behavior then by all means reject my PR and I'll drop it, but it looks like an unhelpful, unexpected, and error-prone behavior to me. (At least error-prone enough that I found it in someone else's erroneous use of it!)

(NB. the erroneous case was not "overriding operator== incorrectly", but it probably *was* abusing ValueNotifier as a communication channel. Unfortunately I think that's quite common in web development and frameworks - Polymer, for example, encourages a very similar pattern.)

**Comment by najeira** [comment]
```dart
var a = SomeContainer(5);
var b = SomeContainer(6);
valueNotifier_ = a;  // A notification happens, assuming the previous value did not == someContainer(6).
a.contents = 6;  // No notification of this change, valueNotifier_.set value isn't even entered.
valueNotifier_ = b;  // No notification because 'previous' [silently updated] value a now == b.
```

This is not strange for me. Expecting notification with this code, is a mistake of how to use ValueNotifier.

**Comment by jonahwilliams** [comment]
>  ValueNotifier fails at that implied contract because changing the value without reassigning it to valueNotifier_.value (or even changing the value in place and reassigning it to that new value) will not notify the listeners.

Values types should not be mutable though, like how "a" + "b" gives a new String and 1 + 2 a new number. Though I fully admit the language does not give us good guidelines here because currently the contract for ValueNotifier is not really expressible via the type system, and it is under-documented compared to the functionality it exposes.

**Comment by ravenblackx** [comment]
> value types should not be mutable though

Is that a thing in Dart? It's not a thing of value types. Structs are value types in C, C++ and C# and are very much mutable. Java proponents sometimes say that value types shouldn't be mutable, but it's not generally a constraint. The + operator not mutating its parameters isn't really demonstrative of the parameters not being mutable. Dart strings are explicitly immutable, it's not a property associated with value types.

Also oops, edited my example above to say `valueNotifier_.value =` instead of the mistaken `valueNotifier_ =` as quoted. Not sure if that correction makes any difference to najeira's response.

**Comment by jonahwilliams** [comment]
A value type is not something that is enforced by the type system, nor are there any affordances to make designing them easier in Dart. Consider the lint [hash_and_equals](http://dart-lang.github.io/linter/lints/hash_and_equals.html). If you implement a type with `operator.==` you should generally also create `hashCode`. But if your hashCode changes, because your object is mutable then you will break the constraints of HashMaps. Likewise, if your hashCode doesn't take into account the fields of your class, then equal objects might have different hashCodes.

This implies a much narrower definition of value type than just a struct.

**Comment by dnfield** [comment]
I would suggest if you want these semantics, you should either override == for that object, or create a new (subclass) of ValueNotifier that operates on reference equality.

This would be a massively breaking change.

**Comment by escamoteur** [comment]
@dnfield any reason why you reopened this?

**Comment by dnfield** [comment]
Mistake.
