### ISSUE TITLE
Run section is grayed out in Android Studio v3.4 RC2

### ISSUE THREAD

**Issue by pzagalsky** [flutter/flutter#29921]
## Steps to Reproduce

1. Install and open Android Studio v3.4 RC2
2. Open existing Flutter project
3. Run build
4. Open 'Run' section at the bottom of AS console

![Screenshot 2019-03-25 at 17 44 31](https://user-images.githubusercontent.com/32510877/54938178-2df6a080-4f26-11e9-8ab6-20b76169e672.png)

Note: build process runs fine and tasks execution progress is shown, also with AS v3.3 works fine

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
