### ISSUE TITLE
Textfield text is centered vertically when expands = true and using an OutlineInputBorder

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#29927]
The new changes from @justinmc (#27205 and then #29250) are great but still leave me with a problem. When I set my textfield to expanded, the text is then centered vertically, whereas I want it to be at the top. I can't figure out a way to do this.

I would expect the behaviour of expands to be the same as setting maxlines; that is, the text would stay at the top.

If the default cannot be changed (and now would be the time since it was only introduced recently) then an option to align the text vertically when expanded = true would be great.

**Comment by justinmc** [comment]
I see text aligned to the top when `expands` is true.

<img src="https://user-images.githubusercontent.com/389558/54943701-151ec880-4eef-11e9-905a-dc0bd80b737f.png" width="200" />

```dart
Container(
  height: 200,
  color: Colors.greenAccent,
  child: TextField(expands: true, maxLines: null),
),
```

What does your code look like to get something that is vertically centered?

**Comment by rmtmckenzie** [comment]
Oh interesting. I've just been playing around with it and it turns out that if I use an outline input border, the text is centered, but if I use an UnderlineInputBorder it's at the top.
```dart
OutlineInputBorder(
  borderSide: BorderSide(width: 1, color: Colors.black, style: BorderStyle.solid),
  borderRadius: BorderRadius.circular(0),
)
```

results in:
![IMG_73802D85FF7A-1](https://user-images.githubusercontent.com/3103484/54948152-34baee80-4ef9-11e9-8d2e-1c72e3a72680.jpeg)


whereas with no other changes
```dart
UnderlineInputBorder(
  borderSide: BorderSide(width: 1, style: BorderStyle.solid, color: Colors.black),
),
```
results in:

![IMG_D62047A36D15-1](https://user-images.githubusercontent.com/3103484/54948252-69c74100-4ef9-11e9-935a-6503fbf25254.jpeg)

**Comment by rmtmckenzie** [comment]
That actually resolves the issue for me because I don't want any border at all so I'm setting the border width to 0 and style to .none anyways, so I can easily switch to underline... but I'll leave the issue open because it's likely someone else will run into it soon!

**Comment by justinmc** [comment]
You're right, thanks for pointing that out!  I'll take a look at this.

**Comment by justinmc** [comment]
It looks like text inside of outlined inputs was intentionally centered, as per the Material spec.

@willlarche Do you have an opinion on this?  Is it still true that the material spec wants text in an outlined input to be centered, or is the real solution to implement this via a `TextArea` or something?

**Comment by willlarche** [comment]
Text should be at the top!

**Comment by willlarche** [comment]
Is this a question of how multiline or singleline textfields behave when they are that tall?

If multiline, the text should be at the top.

If singleline, the design guidance doesn't afford for this kind of height. So, feel free to build in an API that allows .start, .center, .end vertical alignment.

The spec technically supports having the label not cross the top line on an outline, an M1.5 design for text areas, which means the text would start even lower than the top on those. So, I guess the text input rect should be vertically relative to the label OR the border.
<img width="264" alt="Screen Shot 2019-03-25 at 10 09 02 PM" src="https://user-images.githubusercontent.com/1271525/54966438-aa9b7600-4f4a-11e9-8559-0778daa1ab58.png">

Does that make sense?

**Comment by justinmc** [comment]
@willlarche That answers my question, thank you! 

So for single line, I'll keep an eye out for people that want alignment functionality.  Right now it's pretty hard to even make a tall single line input (to my knowledge), so I think it's probably an edge case.

For multiline, it sounds like we need a PR to align text to the top even when the input is outlined.  We also might want to add a flag to allow keeping the label below the border to comply with the spec.

I'll keep this issue open to track this.

**Comment by bdshadow** [comment]
I also bumped into this problem (firstly that i didn't manage to expand the `TextField,` later to this issue). I even asked a [question on Stackoverflow](https://stackoverflow.com/questions/55514514/how-to-make-textfield-to-take-all-available-vertical-space/55516278?noredirect=1#comment97740714_55516278), because didn't find these bugs in github first. In my case, i needed a border all around the `TextField`. So i solved this by putting the `TextField` into the DecoratedBox:
```dart
Expanded(
      child: DecoratedBox(
        decoration: BoxDecoration(
            border: Border.all(
                color: _focus.hasFocus ? Theme.of(context).primaryColor : Theme.of(context).disabledColor,
                width: _focus.hasFocus ? 2.0 : 1.0),
            borderRadius: BorderRadius.all(Radius.circular(4.0))),
        child: TextField(
          focusNode: _focus,
          keyboardType: TextInputType.multiline,
          textAlign: TextAlign.start,
          maxLength: null,
          maxLines: null,
          expands: true,
          decoration: const InputDecoration(contentPadding: const EdgeInsets.all(8.0), border: InputBorder.none),
          controller: _textToSubmitController,
        ),
      ),
    )
```

Hope it will save somebody's time

**Comment by justinmc** [comment]
You can now achieve any vertical alignment you want using TextField's new `textAlignVertical` param.  See https://github.com/flutter/flutter/pull/34355#issuecomment-502859669 for a detailed explanation of its effects.

You'll need to be on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) to get this change, or to be using a version greater than 1.7.4 once it's released.

**Comment by gazialankus** [comment]
@justinmc It seems textAlignVertical is not there for `TextFormField`. Would it be possible to have it there as well?

**Comment by justinmc** [comment]
Yes, sorry, I really should have added that in the original PR!  I just opened an issue here: https://github.com/flutter/flutter/issues/39123

**Comment by rmtmckenzie** [comment]
@gazialankus you're probably best off opening a new issue for that and referring to this one in it.

**Comment by rmtmckenzie** [comment]
oops @justinmc you just barely beat me to it =D

**Comment by justinmc** [comment]
Haha yup beat you by a second or two.

**Comment by leonardocustodio** [comment]
I'm reopening this issue because I'm having problems with this even with the textAlignVertical parameter. Here is an example:

`Expanded(
                  child: Container(
                          margin: EdgeInsets.symmetric(vertical: 30.0),
                          decoration: new BoxDecoration(
                            color: Color(0xff3c79ff),
                            borderRadius: BorderRadius.circular(20),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x3f000000),
                                offset: Offset(0, 2),
                                blurRadius: 15,
                                spreadRadius: 1,
                              ),
                            ],
                          ),
                          child: TextField(
                            textAlignVertical: TextAlignVertical.center,
                            focusNode: _nodeText1,
                            expands: true,
                            maxLines: null,
                            textAlign: TextAlign.center,
                            keyboardType: TextInputType.multiline,
                            decoration: InputDecoration(
                              contentPadding: EdgeInsets.symmetric(vertical: 0.0),
                              hintText: 'Texto da pergunta',
                              hintStyle: TextStyle(
                                fontFamily: 'OpenSans',
                                color: Color(0xffffffff),
                                fontSize: 18,
                                fontWeight: FontWeight.w400,
                                fontStyle: FontStyle.normal,
                                letterSpacing: 0.741176470588235,
                              ),
                              border: InputBorder.none,
                              enabledBorder: InputBorder.none,
                              focusedBorder: InputBorder.none,
                            ),
                          ),
                        ),
                     ),`

And the text is still aligned to the top, here is the screenshot:
![Screen Shot 2020-02-20 at 17 24 47](https://user-images.githubusercontent.com/5619696/74975509-ea423a80-5405-11ea-8498-5a973097c034.png)

Here is the flutter version that I'm using:

[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-BR)
