### ISSUE TITLE
webview_flutter - WebView.postUrl method

### ISSUE THREAD

**Issue by rlecheta** [flutter/flutter#29930]
Hi, I'm migrating an app from Android/iOS to Flutter but I didn't find the WebView.postUrl in the webview_flutter plugin. I need to use this method because I can't change de way the server was written. Can you add this feature to the webview_flutter plugin?

**Comment by June93** [comment]
I also encountered the same problem.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/27730

**Comment by stuartmorgan** [comment]
Closing as a duplicate of the above.
