### ISSUE TITLE
Flutter Create fails to create android.manifest file

### ISSUE THREAD

**Issue by brian-dunn** [flutter/flutter#29936]
Flutter fails to create the correct folders and files when creating a new project. The android.manifest file is missing from the android/app/src folder.
## Steps to Reproduce

1. Run FLUTTER CREATE to create a new Flutter project
2. In the android/app/src/ folder, there is no android.manifest file.
3. Instead, an android/app/src/debug folder was created that contains the android.manifest file.

Flutter Doctor says that all is okay.

This bug seems to be introduced in a recent version of Flutter released in March 2019 (or late Feb 2019). Flutter projects created before this time do not have the problem.

**Comment by brian-dunn** [comment]
This bug was introduced in Flutter version 1.2.1. At this moment, it is not possible to create and deploy Flutter projects on an Android device.

**Comment by creativecreatorormaybenot** [comment]
@brian-dunn This did definitely not affect everyone.

**Comment by brian-dunn** [comment]
Is there a setting in Flutter that tells it to not create an android.manifest file? Or, can I create this manually? Does Flutter always require this file to be in the same folder?

**Comment by hush2** [comment]
```
$ find . -name 'AndroidManifest.xml'
./android/app/src/profile/AndroidManifest.xml
./android/app/src/main/AndroidManifest.xml
./android/app/src/debug/AndroidManifest.xml
```

**Comment by awhitford** [comment]
Please forgive the noob question, but why does Flutter create 3?  Which one should we be editing?
 * I've had to add `meta-data` for an API KEY -- I did that to the _main_ version, and
 * I've had to add a `uses-permission` for `ACCESS_FINE_LOCATION` -- I did that to the _profile_ version.

Did I edit the correct files?

**Comment by NathanaelA** [comment]
Ok, color me also very confused.    I attempted to run my app in release mode and the permissions 
weren't added from the profile or debug manifests.   So I assume those are for `profiling`? and `debugging`?

So on a whim, I created a new "release" folder, and copied my manifest from the debug folder into the `release` folder; did a clean and run and it worked.       

I retested, and added another permission (that I've never had in the app) to my release manifest; and rebuilt & reinstalled the app and it picked it up.   

So I assume their is supposed to be a `release` folder also created...

This app was created using Flutter as of today (upgraded everything, to latest versions earlier today).

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
