### ISSUE TITLE
After updating I can no longer debug

### ISSUE THREAD

**Issue by NotLucas** [flutter/flutter#29949]
## Steps to Reproduce
I updated Flutter to the most recent version using the flutter console and now my project will no longer debug.  It says it cannot debug because C:\flutter\packages\flutter\lib\material.dart is referring to C:\flutter\packages\flutter\lib\src\material\two_level_list.dart when the file does not exist on my machine.

## Logs
Results of flutter run --verbose:
[ +118 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +213 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/beta
[   +2 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[ +112 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] beta
[   +3 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[ +107 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[   +3 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[ +126 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +3 ms] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[   +2 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%ar
[ +117 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +3 ms] 4 months ago
[   +3 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +142 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.0.0-0-g5391447fa
[ +463 ms] executing: C:\Users\Lucas\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +80 ms] Exit code 0 from: C:\Users\Lucas\AppData\Local\Android\sdk\platform-tools\adb devices -l
[   +4 ms] List of devices attached
           06157df645205527       device product:marinelteuc model:SAMSUNG_SM_G890A device:marinelteatt transport_id:4
[ +536 ms] Found plugin firebase_auth at
C:\Users\Lucas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.7.0\
[  +34 ms] Found plugin firebase_core at
C:\Users\Lucas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\
[  +14 ms] Found plugin firebase_database at
C:\Users\Lucas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_database-1.1.0+1\
[ +394 ms] Found plugin firebase_auth at
C:\Users\Lucas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.7.0\
[  +14 ms] Found plugin firebase_core at
C:\Users\Lucas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\
[  +13 ms] Found plugin firebase_database at
C:\Users\Lucas\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_database-1.1.0+1\
[ +252 ms] C:\Users\Lucas\AppData\Local\Android\sdk\platform-tools\adb -s 06157df645205527 shell getprop
[ +287 ms] ro.hardware = samsungexynos7420
[+1153 ms] Your application could not be compiled, because its dependencies could not be established.
                    The following Dart file:
                      C:\flutter\packages\flutter\lib\material.dart
                    ...refers, in an import, to the following library:
                      C:\flutter\packages\flutter\lib\src\material\two_level_list.dart
                    Unfortunately, that library does not appear to exist on your file system.
[  +74 ms] "flutter run" took 3,024ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:404:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)

Results of flutter analysis:
info - The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able
          to run on earlier versions - lib\pages\landing_page.dart:64:3 - sdk_version_async_exported_from_core
   info - The value of the local variable 'user' isn't used - lib\pages\landing_page.dart:70:22 - unused_local_variable
warning - The asset icons/luketables.png does not exist - pubspec.yaml:48:7 - asset_does_not_exist
   info - Unused import: 'package:flutter/material.dart' - test\widget_test.dart:8:8 - unused_import

Results of flutter doctor -v:
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Lucas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\Lucas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • SAMSUNG SM G890A • 06157df645205527 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

This is my first project using github and my first github issue/question/plea for help so sorry for poor formatting or any other issues.  I know I'm supposed to provide a file but I don't know what file works best for this.

**Comment by jonahwilliams** [comment]
Are you sure you've updated anything - your flutter version is nearly 4 months old. What versions were you running before updating, and what command did you run to update?
