### ISSUE TITLE
I am having issue installing Flutter on Mac. Flutter Doctor fails.

### ISSUE THREAD

**Issue by ckunda** [flutter/flutter#29952]
I am trying to use Flutter in Visual Studio Code, ran flutter doctor and got the below error:

[flutter] flutter doctor
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to /private/var/folders/jt/yvk9l5nd343_fyj8vbmw_s500000gn/T/dart-code-cmd-run/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
exit code 1

**Comment by jonahwilliams** [comment]
It looks like we're failing to detect that the command line tools are not installed. We should fix this so it does not crash. In the meantime, see

https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

for a fix

**Comment by christopherfujino** [comment]
I believe this was fixed in https://github.com/flutter/flutter/pull/38920
