### ISSUE TITLE
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.

### ISSUE THREAD

**Issue by ChiragRayani** [flutter/flutter#29959]
while running the application for the first time in android studio, I am getting an error

**Comment by tomalabaster** [comment]
Can you share the output you get when running `flutter doctor -v` in a command line window, please?

**Comment by wayuhan** [comment]
Has the problem been solved?

**Comment by ChiragRayani** [comment]
![Screenshot from 2019-04-16 07-25-30](https://user-images.githubusercontent.com/32605614/56176503-ee007600-6018-11e9-8966-5a72213729be.png)

**Comment by wayuhan** [comment]
I think it's better to develop Flutter with Visual Studio Code than Android Studio.

**Comment by ChiragRayani** [comment]
getting the same error in vs code

**Comment by ChiragRayani** [comment]
![Screenshot from 2019-04-16 08-17-58](https://user-images.githubusercontent.com/32605614/56178528-396a5280-6020-11e9-9d45-f98dba78e8a4.png)

**Comment by wayuhan** [comment]
![Uploading TIM截图20190416104920.png…]()

**Comment by wayuhan** [comment]
![Upload
![TIM截图20190416104920](https://user-images.githubusercontent.com/29221167/56178694-bb18ab00-6035-11e9-8b2d-655579bf925a.png)

**Comment by wayuhan** [comment]
Have you solved it?

**Comment by ChiragRayani** [comment]
No.. 
do you know how to add android_sdk path..
because i'm adding it, but every time i close terminal it is remove from PATH

**Comment by wayuhan** [comment]
I use Windows, but you have to download the Android SDK before you can configure its path

**Comment by ChiragRayani** [comment]
Solved.
thanks for help

**Comment by paantiay** [comment]
hello, please i get this error on vs code using flutter "C:\Users\Don Skillion\Downloads\TheGorgeousLogin-master>flutter run
Unable to locate a development device; please run 'flutter doctor' for information about installing
additional components."

**Comment by ChiragRayani** [comment]
$ flutter config --android-sdk /path/to/android/sdk
$ flutter config --android-studio-dir /path/to/android/studio

@paantiay  try to add this in your vs code terminal

**Comment by rsn86** [comment]
In Android Studio, ensure that the API level of your Project SDK (File->Project Structure) <= of the API level of  your AVD.

**Comment by sujitmore21** [comment]
Add SDK API Level 29 on your project 
Go to project file option-> open file -> project Structure -> download API 29
![flutter_issue](https://user-images.githubusercontent.com/32368147/81044653-60692000-8ed2-11ea-9275-fa40a6de7f8c.jpg)

watch this- https://www.youtube.com/watch?v=EvIWwPhMNl4
