### ISSUE TITLE
Ios app build release issue

### ISSUE THREAD

**Issue by wangyankun33** [flutter/flutter#29950]
` flutter build ios --release`
Building com.jointac.lcms for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project:
WKUP7M8BV3
Running Xcode build...                                                  
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Code Signing Error: Runner has conflicting provisioning settings. Runner is automatically signed,
    but code signing identity iPhone Distribution: Shanghai Jointac International Logistics Co., Ltd
    (WKUP7M8BV3) has been manually specified. Set the code signing identity value to "iPhone
    Developer" in the build settings editor, or switch to manual signing in the project editor.
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'

Encountered error while building for device.

`flutter doctor -v`

wykdeMac:lcms wyk$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D42, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/wyk/downloads/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wyk/downloads/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/wyk/downloads/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by moonvader** [comment]
Runner has conflicting provisioning settings.
Open Xcode and make handle signing problems - it is not looks like Flutter issue.

**Comment by iapicca** [comment]
Hi @wangyankun33 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
