### ISSUE TITLE
ValueNotifier does not notify listeners when modifying a list

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#29958]
```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

ValueNotifier<List<String>> numbers = ValueNotifier(['123']);

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ValueListenableBuilder(
          valueListenable: numbers,
          builder: (BuildContext context, List<String> nums, Widget child) {
            return ListView.builder(
              itemCount: numbers.value.length,
              itemBuilder: (BuildContext context, int index) {
                return ListTile(
                  title: Text(nums[index]),
                );
              },
            );
          },
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.star),
          onPressed: () {
            numbers.value.add(Random().nextInt(1000).toString());
          },
        ),
      ),
    );
  }
}
```

It looks like because the reference is the same, the notifiers are not called, for example, this works:
```dart
numbers.value = []..addAll(numbers.value)..add(Random().nextInt(1000).toString());
```

**Comment by jonahwilliams** [comment]
This class is a good candidate for better documentation

**Comment by alecorsino** [comment]
You answered your own question. ValueNotifier doesn't make all object down the object tree observables
`ValueNotifier<List<String>> numbers`
That's your observable value only.
What it does is just create a setter like:
`
set value(T newValue) {
    if (_value == newValue)
      return;
    _value = newValue;
    notifyListeners();
  }
`
` notifyListeners();` will notify listeners when the reference of `numbers.value' changes and nothing else

**Comment by dsjgordon** [comment]
This can be resolved by calling ```valueNotifier.notifyListeners()``` after updating the elements of the value. However, ```notifyListeners()``` is annotated as ```@protected```, triggering IDE warnings. It would be nice if the annotation was removed as this issue describes a valid use-case to include it in the public interface.

**Comment by cgestes** [comment]
Or we could modify the list in an immutable manner to ensure notifyListeners is called.

For example:
```dart
valueNotifier.value = List.from(valueNotifier.value)..add(...);
```

**Comment by esDotDev** [comment]
This would be nice to enable. Since ValueNotifier does not watch nested objects, a method should be provided to allow a developer to trigger manual notifications, in cases where we know we've modified some properties on the underlying value object.

**Comment by ianspryn** [comment]
Came here looking for a solution. A nice alternative to solve this might be [Property Change Notifier](https://pub.dev/packages/property_change_notifier#-readme-tab-). Use a custom add/remove method for a class that contains your list, and notify your listeners in those methods.

**Comment by Skyost** [comment]
@ianspryn Property Change Notifier seems very good, but depending on a third party package just because there is a little `@protected` annotation is a bit annoying for me.

**Comment by gybin02** [comment]
This would be nice to enable  valueNotifier.notifyListeners() for developer.


this is like databinding  in Android。

**Comment by gskinner-shared** [comment]
The trick is to just extend ValueNotifier, and provide a public Notify fxn that calls NotifyListeners.

**Comment by apgapg** [comment]
As per @gskinner-shared suggestion you can use this

```
import 'package:flutter/material.dart';

class PropertyValueNotifier<T> extends ValueNotifier<T> {
  PropertyValueNotifier(T value) : super(value);

  @override
  void notifyListeners() {
    super.notifyListeners();
  }
}
```

**Comment by clragon** [comment]
that's not a bad solution, though it would still be alot nicer if it was like this by default.

**Comment by mozochek** [comment]
You can listen to list length and then changes will be notified. Just wrap list value listenable with list.length value listenable

**Comment by wahyu-handayani** [comment]
@MichaelPriebe @cgestes I have tried your solution in my project and it resolve my case.. thank you so much. But here, I have another case, I would like to update an element inside a list using ValueNotifier, here is what I mean:
```
val.value=[1,2,3,4,5];
```
```
List x=val.value; // I would like to change x[2] to be 33 => [1,2,33,4,5]
List temp=x;
temp[2]=33;
val.value=temp;
```
I have tried to do it, but the value inside val.value doesn't updated. do you guys know the proper way to replace one element inside list of ```val.value``` ?

**Comment by clragon** [comment]
@wahyu-handayani 
but you have completely missed the important point of copying the list, you're only passing around references to the same list.

lets call the List in `val.value` by the name of `Object A`

```dart
List x = val.value; // pass reference to Object A to List x
List temp=x; // pass reference of Object A to List temp
temp[2]=33; // change Object A
val.value=temp; // assign reference to Object A to reference to Object A (nothing changes)
```
this is still the same object and list.

you have to have a different object id for the value notifier to update.
```dart
List x = List.from(val.value); // create a new Object, B, with the same contents as Object A
x[2]=33; // change Object B
val.value = x; // override reference to Object A with reference to Object B, triggering an update
```

**Comment by wahyu-handayani** [comment]
@clragon I am trying your code now and the list is updated successfully. Thank you soooo much for your help @clragon

**Comment by wahyu-handayani** [comment]
@clragon, I would like to inform you that I assign ```val.value``` inside ```ValueListenableBuilder``` here is the code:
```
ValueListenableBuilder(
    valueListenable: modelFoto,
     builder: (_, val, __) {
       if (val.adaFoto){
           Widget dummyList =Text("after click");
            List<Widget> x = List.from(val.independentFoto);
            x[val.index] = dummyList;
            modelFoto.value = ModelRegis(
                                                    loadFoto: modelFoto.value.loadFoto,
                                                    adaFoto: modelFoto.value.adaFoto,
                                                    idFotoUser: modelFoto.value.idFotoUser,
                                                    index: modelFoto.value.index,
                                                    independentFoto: x,
                                                    contentFoto: modelFoto.value.contentFoto);
             print("x: $x");
             print("model. ${modelFoto.value.independentFoto}");
             print("val: ${val.independentFoto}");
             return ListView(
                            physics:const AlwaysScrollableScrollPhysics(),
                            shrinkWrap: false,
                            children: modelFoto.value.independentFoto
                            // children: val.independentFoto
             );

       }else{...}
})
```
when I print ```modelFoto.value.independentFoto```, the elements inside the List is updated successfully, but when I print ```val.independentFoto``` the list doesn't update

**Comment by najibghadri** [comment]
About `List.from` - or `List.of` for that matter - what is the performance of that?? I couldn't find the implementation, it's an `external factory` method which tells me it might or might not create a new list. If it does then what if I _want_ to use notifyListeners in my prod code to keep it performant? Am I making sense here?

**Comment by bretmh** [comment]
> Or we could modify the list in an immutable manner to ensure notifyListeners is called.
> 
> For example:
> 
> ```dart
> valueNotifier.value = List.from(valueNotifier.value)..add(...);
> ```

This works perfectly.

**Comment by subzero911** [comment]
You can use `fast_immutable_collections` (FIC), it has `lock` getter which allows you to modify IList, but will always return a new instance.
You can also use `observabl_ish` or `get` (GetX) package, they both have RxList collection which you can modify directly and it will trigger rebuilds. RxList implements basic List, but keeps a stream of all changes.

**Comment by om-ha** [comment]
@clragon your solution below is pretty good.

> @wahyu-handayani but you have completely missed the important point of copying the list, you're only passing around references to the same list.
> 
> lets call the List in `val.value` by the name of `Object A`
> 
> ```dart
> List x = val.value; // pass reference of Object A to x
> List temp = x; // pass reference of Object A to temp
> temp[2] = 33; // change Object A
> val.value = temp; // override reference to Object A with reference to Object A (nothing changes)
> ```
> 
> this is still the same object and list.
> 
> you have to have a different object id for the value notifier to update.
> 
> ```dart
> List x = List.from(val.value); // create a new Object, B, with the same contents as Object A
> x[2] = 33; // change Object B
> val.value = x; // override reference to Object A with reference to Object B (triggers an update)
> ```

However, as per my comment on [SO here](https://stackoverflow.com/questions/61774608/provider-valuenotifier-listen-not-working-on-some-pages-on-flutter/63883205#comment123546597_63883205) There's an issue with copying the list (only in certain cases.

There's the cost of copying the list with `List.from`. Alternatively using a ValueNotifier subclass, with methods for mutating the list, and notifyListeners() in said method, would be a performance enhancements in some scenarios (list is too big and/or list is updated too frequently)

**Comment by Ldev007** [comment]
> 

Just to point it out, although maybe it is self explanatory but for me I faced this issue because of a below mentioned scenario.

Since I was having a lot of statements being printed in console I missed when this one exception happened and was printed in the console which stated that there was a type conflict happening, to be more clear below is the explanation.

I defined my value notifier as a **List<bool>** explicitly. So following @clragon 's suggested method the implicit type of new **List** was getting set to be **dynamic** (which I would use as a new object) resulting in an exception at the line where I assigned **dynamic** type list to my value notifier (whose type was **bool**).

i.e :
`List<bool> originalVNList = ValueNotifier([some bool values]); //defining the value notifier and booleans to populate it with
List newListObject = List.from(originalVNList.value); //copying elements from the original list object to a new object
newListObject[1] = false; //changing new object which has copied elements from the original list but different object id
originalVNList.value = newListObject; //line at which exception happens since the type of original list is bool but of new list is dynamic
`
So if we are defining the type for value notifier explicitly it is pretty self explanatory that we must also define the type when we are assigning it to a new **List** to make the suggested solution work. I hope it would help someone having similar situation like mine.

**Comment by AceRedminer** [comment]
> Or we could modify the list in an immutable manner to ensure notifyListeners is called.
> 
> For example:
> 
> ```dart
> valueNotifier.value = List.from(valueNotifier.value)..add(...);
> ```

This man is a genius thanks so much

**Comment by nathanfranke** [comment]
In your `ChangeNotifier`:

```dart
final List<Item> _items;
ObservedList<Item> get items => ObservedList(_items, notifyListeners);
```

And your helper class, `ObservedList`:

```dart
import 'dart:collection';
import 'package:flutter/foundation.dart';

class ObservedList<T> with ListMixin<T> {
  final List<T> _list;
  final void Function() _modified;

  ObservedList(this._list, this._modified);

  @override
  int get length => _list.length;

  @override
  set length(final int value) {
    _list.length = value;
    _modified();
  }

  @override
  T operator [](final int index) {
    return _list[index];
  }

  @override
  void operator []=(final int index, final T value) {
    _list[index] = value;
    _modified();
  }

  @override
  void add(final T element) {
    _list.add(element);
    _modified();
  }

  @override
  void insert(final int index, final T element) {
    _list.insert(index, element);
    _modified();
  }

  @override
  bool remove(final Object? element) {
    final value = _list.remove(element);
    _modified();
    return value;
  }

  @override
  T removeAt(final int index) {
    final value = _list.removeAt(index);
    _modified();
    return value;
  }
}
```

**Comment by clragon** [comment]
or, instead of writing that helperclass, you can use [`List.unmodifiable`](https://api.flutter.dev/flutter/dart-core/List/List.unmodifiable.html), 
so you always have to modify your list in an immutable manner.

**Comment by carman247** [comment]
Not sure why but I had to use the spread operator

e.g.

```
_notifier.value = [..._list];
```
