### ISSUE TITLE
VSCode创建的flutter工程没有隐藏的.ios和.android文件

### ISSUE THREAD

**Issue by shuaiwang007** [flutter/flutter#29967]
![屏幕快照 2019-03-26 下午3 55 53](https://user-images.githubusercontent.com/12870683/54980056-b2592a00-4fdf-11e9-9852-702693e9d877.png)

**Comment by DanTup** [comment]
The folder seems to be name `ios`. Can you edit the podfile to change from `.ios` to `ios` and see if that solves the problem?

**Comment by shuaiwang007** [comment]
thank you~
