### ISSUE TITLE
Need meaningful thread names in the timeline

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#2996]
The thread names in the timeline reported by `_getVMTimeline` are not meaningful. Here's an example:

<img width="1175" alt="screen shot 2016-03-29 at 5 12 04 pm" src="https://cloud.githubusercontent.com/assets/211513/14128030/bd6c720a-f5d1-11e5-9524-ea6af10da8b7.png">

/cc @chinmaygarde @johnmccutchan

**Comment by eseidelGoogle** [comment]
base has a call to do this for arbitrary threads (if you aren't already using base to create them):
https://github.com/flutter/engine/blob/master/sky/shell/platform/android/sky_main.cc#L63

**Comment by eseidelGoogle** [comment]
Oh, sorry, I see now that these threads may have names and _getVMTimeline isn't reading them correctly?

**Comment by yjbanov** [comment]
> _getVMTimeline isn't reading them correctly?

I'm actually not sure the Dart VM has access to foreign thread names. We might need to push the name along with the trace event data, which [we are not doing right now](https://github.com/flutter/engine/blob/09972ad11cd9323e3e45b389db869ff5c8604641/sky/shell/tracing_controller.cc#L123). Perhaps it could be one of `arg_names`/`dart_argument_values`?

**Comment by chinmaygarde** [comment]
We correctly forward the extra argument names and values to the Dart
timeline. However, the event type itself may be unsupported. I am going to
verify this next.

**Comment by johnmccutchan** [comment]
@chinmaygarde We might need to add support for meta-data events.

**Comment by chinmaygarde** [comment]
We are dropping the following traces from base without reporting them to the Dart timeline because of missing event types. I don't see a meta-data event. Will have to dig some more into how base reports the same.

Dropped Type: TRACE_EVENT_PHASE_COUNTER 'C' Count: 284
Dropped Type: TRACE_EVENT_PHASE_ASYNC_END 'F' Count: 284
Dropped Type: TRACE_EVENT_PHASE_ASYNC_BEGIN 'S' Count: 284

**Comment by chinmaygarde** [comment]
@johnmccutchan: It is not super critical, but would it be possible to add the Counter, Async Begin and Async End types?

**Comment by chinmaygarde** [comment]
We also definitely need TRACE_EVENT_PHASE_METADATA ('M') for the thread names, CPU count, etc..

**Comment by johnmccutchan** [comment]
@chinmaygarde I'm on it in https://github.com/dart-lang/sdk/issues/26142

**Comment by johnmccutchan** [comment]
VM side is done. Chinmay is going to do a roll.

**Comment by chinmaygarde** [comment]
Yeah, I need to patch base to flush meta-data events while continuously tracing and update the tracing controller too. Will update all three in one go.

Thanks for the quick fix!

**Comment by chinmaygarde** [comment]
Fixed with https://github.com/flutter/engine/pull/2571
