### ISSUE TITLE
Max thread number for platform task runner thread

### ISSUE THREAD

**Issue by nieben** [flutter/flutter#29969]
Hello, in my projet, i use a plugin to do a certain jobs(List), in which will create new threads for each job in jobs(job finish in few seconds normally)

now in dart, it will invoke the methodfor 10 jobs per time(10 threads will be created) recursively.

the problem is after app run some time randomly, the app will crush and ouptput error like below. i guess the problem is the plugin create too much threads, i am not for sure. 

## Logs

F/libc    (25280): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1f0ffed65f03d0 in tid 25280 (nieben.yiqice)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/LLD-AL30/HWLLD-H2:8.0.0/HONORLLD-AL30/133(C00):user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 25280, tid: 25280, name: nieben.yiqice  >>> nieben.yiqice <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1f0ffed65f03d0
    x0   0000000000000060  x1   0000007c8f437dc0  x2   0000007c8f400000  x3   0000000000000006
    x4   0000000000000037  x5   0000007fc10ce078  x6   0000007cb8f23000  x7   0000000022794276
    x8   0000007c96de9898  x9   0000000000000016  x10  0000000000000016  x11  0000000000000009
    x12  0000007c965a0c40  x13  0000000000000010  x14  0000007c965a0c40  x15  f81f0ffed65f03c0
    x16  000000009109c108  x17  0000007cb7ce7948  x18  000000001a5a3a48  x19  0000007cb417f388
    x20  0000000000000017  x21  0000000000000017  x22  000000000000000b  x23  0000000000000044
    x24  000000000000000b  x25  0000007cb417f398  x26  0000007cb40ade70  x27  0000007ca9a0e818
    x28  0000000000000040  x29  0000007ca9a0e818  x30  0000007c965b4810
    sp   0000007fc10ce0f0  pc   0000007c96cee860  pstate 0000000020000000
backtrace:
    #00 pc 00000000013e6860  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #01 pc 0000000000cac80c  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #02 pc 0000000000cac540  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #03 pc 0000000000cac260  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #04 pc 0000000000ce6154  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #05 pc 0000000000cb9d60  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #06 pc 0000000000cbba94  /data/app/nieben.yiqice-kHJTi3gGe9hMTdLsxaaXXQ==/lib/arm64/libflutter.so (offset 0xc90000)
    #07 pc 0000000000015f18  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+808)
    #08 pc 0000000000015b68  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+108)
    #09 pc 000000000011b31c  /system/lib64/libandroid_runtime.so (_ZN7androidL38android_os_MessageQueue_nativePollOnceEP7_JNIEnvP8_jobjectli+44)
    #10 pc 000000000082769c  /system/framework/arm64/boot-framework.oat (offset 0x626000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+140)
    #11 pc 0000000000015c50  /dev/ashmem/dalvik-jit-code-cache (deleted)

```
```

[√] Flutter (Channel master, v1.3.14-pre.38, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
    • Flutter version 1.3.14-pre.38 at C:\src\flutter
    • Framework revision 479be44479 (5 days ago), 2019-03-21 02:11:40 -0400
    • Engine revision 250b99bd27
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\niebe\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\niebe\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\niebe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • LLD AL30 • 6SJRX18B02004681 • android-arm64 • Android 8.0.0 (API 26)

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
