### ISSUE TITLE
Aapt2Exception: Android resource linking failed, fontVariationSettings not found when running flutter build apk

### ISSUE THREAD

**Issue by EngTee** [flutter/flutter#29965]
I'm seeing error below when running `flutter build apk`

> Execution failed for task ':firebase_core:verifyReleaseResources'.
 java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  D:\testApp\build\firebase_core\intermediates\res\merged\release\values\values.xml:276: error: resource android:attr/fontVariationSettings not found.
  D:\testApp\build\firebase_core\intermediates\res\merged\release\values\values.xml:277: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

I've seen similar issue reported and I've made the proposed solution as below but i'm still seeing the error:
`compileSdkVersion 28`

`configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.0'
    }
}`

When i run `flutter clean` followed by `flutter build apk`, apk is generated and i dont this error.
When i rerun `flutter build apk` again, i'm seeing the error.

Output of running `flutter doctor -v` 

>[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.2.1 at C:\Flutter\flutter_windows_v1.0.0-stable\flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

>[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\xx\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\xx\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

>[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

>[√] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

**Comment by fdb713** [comment]
It seems that this issue only occurs when you build from command line. I have similar issue but only  when trying to execute `./gradlew assembleRelease`.
```
* What went wrong:
Execution failed for task ':flutter_boost:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/whalevii/repositories/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_boost-0.0.415/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/whalevii/repositories/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_boost-0.0.415/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/whalevii/repositories/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_boost-0.0.415/android/build/intermediates/res/merged/release/values/values.xml:2611: error: resource android:attr/fontVariationSettings not found.
  /Users/whalevii/repositories/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_boost-0.0.415/android/build/intermediates/res/merged/release/values/values.xml:2612: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

on Android Studio everything's fine.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by EngTee** [comment]
Sorry. I should've close this thread earlier. The problem no longer exist in the latest stable version

**Comment by franzejr** [comment]
I confirm this was happening in the command line only and it has been fixed in the latest stable version. Thanks!

**Comment by iLolz** [comment]
I already have that problem with ":devicelocale:verifyReleaseResources'", and he don't generate my apk, when I compile using Code Magic they generate my apk! My compileSdkVersion it is in API 28 and my min sdk in 18!

**Comment by escamoteur** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
