### ISSUE TITLE
为什么不增强错误提示

### ISSUE THREAD

**Issue by lifetin** [flutter/flutter#29960]
使用了https://pub.dartlang.org/packages/stack_trace这个扩展后,错误信息定位更强大了. 为什么dart不默认实现这个功能?

![11](https://user-images.githubusercontent.com/10474968/54972897-97c78680-4fc8-11e9-95b5-e8292c2fbef2.png)
![22](https://user-images.githubusercontent.com/10474968/54972898-98601d00-4fc8-11e9-9bff-90cdb4bcebcb.png)

**Comment by escamoteur** [comment]
Hi, please describe your Problem in English so that we can help you.
Is this still a problem?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
