### ISSUE TITLE
url_launcher. Can we clear the cache when launching webview?

### ISSUE THREAD

**Issue by BirdyF** [flutter/flutter#29976]
I am using url_launcher (launch and closeWebView) to show Strava login and approval/scope.
It seems that webview (correct me if I am wrong) is keeping stuff in a cache because behavior is different when it is the first run of the app (after install) or the following runs.

Is there a way to clear the cache of the webview from url_launcher?

**Comment by BirdyF** [comment]
Is it possible to add in a future release of url_launcher an option to clear the cache before launching a webview?

**Comment by escamoteur** [comment]
If I understand url_launcher correct it just launches the OS browser.

Best to ask on stackoverflow too.

**Comment by mgalgs** [comment]
Might be able to use the functionality that landed in https://github.com/flutter/plugins/pull/1200 ?

**Comment by mrzhengyue** [comment]
I have the same problem!

**Comment by fifabell** [comment]
I have the same problem ,too..!

No Webview, used url_launch

**Comment by dawid-niedzwiecki** [comment]
Same here, would be great to have a way to clear the webview cache in url_launcher.

**Comment by stuartmorgan** [comment]
`url_launcher` is intended to have a minimal API for launching, and the API of SFViewController is extremely limited so this couldn't be implemented on iOS anyway. Use cases that need detailed control of the webview should build on `webview_flutter` instead.

Closing as out of scope.
