### ISSUE TITLE
Failed to find assets path for "Frameworks/App.framework/flutter_assets"

### ISSUE THREAD

**Issue by melvinm99** [flutter/flutter#29974]
Hi, I'm writing here to report a potential bug I've encountered building and running my app on iOS: it doesn't load any asset I provided. Assets are correctly defined, since on Android it builds ok. They get replaced with question marks or other icons as you can see in this screen:
![error](https://user-images.githubusercontent.com/11243208/54990758-c55a0300-4fbb-11e9-83c3-39786273d31e.jpg)

The error in Xcode log is: Failed to find assets path for "flutter_assets".

I've tried both master and stable channel, getting the same error. Then, I switched to beta channel and now everything is ok (correct assets are loaded in the running app), so maybe it's a problem that has been solved in latest commits/releases.

## Steps to Reproduce
flutter build ios --release 

## Logs

Failed to find assets path for "flutter_assets"
Engine run configuration was invalid.
Could not launch engine with configuration.

Flutter doctor and analyze where ok, sorry but now I don't have all the logs anymore since I switched the channel.

**Comment by hongliang211** [comment]
I have the same problem too

**Comment by yxwandroid** [comment]
I have the same problem too

**Comment by yxwandroid** [comment]
I have the same problem too

**Comment by yxwandroid** [comment]
I have the same problem too

**Comment by CTaoWu** [comment]
I think your 'Script' is Missing!
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
"$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?


Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by aberror** [comment]
The issue still exists, Environment:
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by aberror** [comment]
Flutter page failed to load
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
 [VERBOSE-2:engine.cc(118)] Engine run configuration was invalid.
 [VERBOSE-2:FlutterEngine.mm(308)] Could not launch engine with configuration.

**Comment by aberror** [comment]
flutter pages failed to load, logs are below:
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
 [VERBOSE-2:engine.cc(118)] Engine run configuration was invalid.
 [VERBOSE-2:FlutterEngine.mm(308)] Could not launch engine with configuration.

**Comment by iapicca** [comment]
Hi @aberror 
this issue is dated back 9 months,
please open a new issue proving all or some of the information 
requested in the template, 
thank you

**Comment by AliNaqiAnsari** [comment]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           59.6s
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
[VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
Debug service listening on ws://127.0.0.1:58867/XOWojV3-_ls=/ws
Syncing files to device iPhone 11 Pro Max...

**Comment by dahabit** [comment]
1- rm -rf ios/Flutter/App.framework

2- Change the **Runner** target build settings **Build Phases** > Thin Binary script as follows:

```
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
```

**Comment by davefaliskie** [comment]
> I think your 'Script' is Missing!
> "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
> "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

When I add that I get an error `/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory` this is when running in xcode, and I've cleaned

**Comment by kinan96** [comment]
> I think your 'Script' is Missing!
> "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
> "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

where I should write that ?

**Comment by srenghong** [comment]
> 1- rm -rf ios/Flutter/App.framework
> 
> 2- Change the **Runner** target build settings **Build Phases** > Thin Binary script as follows:
> 
> ```
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
> ```

work for me, thanks

**Comment by oengmengthong** [comment]
create a new flutter project.
and then copy folder lib and file pubspace.yaml from old project to the new project.
I found many file, are missing on folder ios at an old project

**Comment by tong-do** [comment]
> I think your 'Script' is Missing!
> "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build
> "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed

it's worked for me! thx

**Comment by tanmaypandharipande** [comment]
> flutter upgrade

worked for me !

**Comment by Ahmadre** [comment]
> 1- rm -rf ios/Flutter/App.framework
> 
> 2- Change the **Runner** target build settings **Build Phases** > Thin Binary script as follows:
> 
> ```
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed
> /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" thin
> ```

Thank you so much @dahabit you helped me a lot :)
