### ISSUE TITLE
You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode

### ISSUE THREAD

**Issue by kapil708** [flutter/flutter#29975]
i am uploading apk after building it base on the documentation
[](https://flutter.dev/docs/deployment/android)

here is my gradle file code
================================
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

Key.properties file
=====================
storePassword=jasmtsckeystore
keyPassword=jasmtsckeystore
keyAlias=jasmtsckeystore
storeFile=/Users/apple/desktop/Flutter/keystore/jasmtsc/jasmtsckeystore.jks

i will get the apk but at the time of publish on play store it gives me error of.
**Upload failed
You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode. Learn more about signing.**

**Comment by kapil708** [comment]
found on stack
[https://stackoverflow.com/questions/54850298/flutter-release-apk-not-accepted-by-google-play-console](url)

step 1: flutter clean
step 2:  flutter build apk

and done

**Comment by tomalabaster** [comment]
Good to see you found a solution. Are you able to close this issue now?

**Comment by ricardobrg** [comment]
Flutter clean didn't work. I even tried building the apk in Android Studio, by opening app module as a project but the signing failed again for play console.

What solved the problem for me was manually signing the apk. Added the information in stackoverflow too. https://stackoverflow.com/questions/54850298/flutter-release-apk-not-accepted-by-google-play-console/55784618#55784618

**Comment by AkramChauhan** [comment]
Make sure you have "release" in build.gradle

```
buildTypes {
release {
signingConfig signingConfigs.release
}
}
```

as well as just put jasmtsckeystore.jks file in android/app/jasmtsckeystore.jks so that you don't have mention full path.

now path will be 

```
storePassword=jasmtsckeystore
keyPassword=jasmtsckeystore
keyAlias=jasmtsckeystore
storeFile=jasmtsckeystore.jks
```

**Comment by chornbe** [comment]
It would be wonderful to have this all, ya know, actually documented in Flutter's docs. If it's there, seems it's buried somewhere. :\

**Comment by escamoteur** [comment]
Don't know if you have seen https://flutter.dev/docs/deployment/android

Does anyone still have problems here?

**Comment by AkramChauhan** [comment]
I think this issue should be closed now.

**Comment by krolaw** [comment]
I think either:
1) The flutter docs should say run "flutter clean" after following the key setup instructions.
2) or better Flutter build should detect changes to <app dir>/android/app/build.gradle
Because, after following the instructions, Google still said the .aab is signed in debug mode, until I cleaned it.

**Comment by escamoteur** [comment]
@krolaw could you please create a new issue as feature request for this and link this issue?

**Comment by mshenawy22** [comment]
make sure you have the following in your gradle file     
for the keystore properties : check this link https://flutter.dev/docs/deployment/android 
signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

**Comment by incrediblezayed** [comment]
Time to reopen the issue I guess, I'm trying everything the google can say, like clean and all stuff, cross checked all the code(key.properties) and all the parameters, debuggable is false, the is release option in buildtypes, and everything is - [ ] correct, even I check my key itself with the keytool, the key is still same, but I don't know what's causing this issue, please help, I've been trying everything since 2 days now, I'm updating the application after 4 months.

**Comment by SuhailMirjiDCMCompliance** [comment]
> Time to reopen the issue I guess, I'm trying everything the google can say, like clean and all stuff, cross checked all the code(key.properties) and all the parameters, debuggable is false, the is release option in buildtypes, and everything is - [ ] correct, even I check my key itself with the keytool, the key is still same, but I don't know what's causing this issue, please help, I've been trying everything since 2 days now, I'm updating the application after 4 months.

Same here. Been with it for 2 days.
