### ISSUE TITLE
Image turns into black using shared engine instance on iOS real device after upgrade to 1.2.1

### ISSUE THREAD

**Issue by ForelaxX** [flutter/flutter#29981]
## Steps to Reproduce

I'm using flutter with an exist app, so I use a shared engine instance which is shared by multiple FlutterViewControllers. I found that the second time FlutterViewController shows, the Image Widget does not work normal, just like this:

![image](https://user-images.githubusercontent.com/8003181/55007913-2e249800-501b-11e9-9487-4be227d638e0.png)

it should be like this(the first time it shows Image Widget is normal):

![image](https://user-images.githubusercontent.com/8003181/55008219-a723ef80-501b-11e9-9551-53c03ac8eed1.png)

And it can only reproduce when you run on iOS real device.*Everything works just fine on Flutter 1.0.0*, it happens after upgrade Flutter framework to 1.2.1.

I have made a demo to help you to reproduce this bug:

https://github.com/ForelaxX/flutter_bug_demo

Run it on iOS real device and click the button, the FlutterVIewController will present onto current view controller, and it will dismiss in 4 seconds.

The second time you click the button you will reproduce this bug.

## Output of flutter doctor

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G6029, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/forelax/.flutter_sdk_1_2_1
    • Framework revision 8661d8aecd (6 周前), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/forelax/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone XR • 3CF2AB62-921D-4729-92BF-8A938B2608AD • ios • iOS 12.1 (simulator)

**Comment by ZY-Merry** [comment]
fluttter 从入门到放弃！坐等大神解决此bug

**Comment by xster** [comment]
cc @dnfield for sharing engine between view controllers. Wonder if there are any restrictions that need documenting. 

@ForelaxX is there a simple repro project we can look at to demonstrate these issues? 

Also wonder if it's related to #28484

**Comment by dnfield** [comment]
This is very like a resource context issue....

**Comment by dnfield** [comment]
Yup.  On your initial launch, the VC isn't getting a resource context.

Then, on the next launch, it _is_ getting a resource context, but that resource context doesn't have the image.

Looking into a fix for that.

**Comment by dnfield** [comment]
Discussed with @chinmaygarde a bit - it seems like we should be able to make this work if we flip around the order of when we create the resource context today and drop support for rendering images without a resource context.

I'll experiment with that a bit.

**Comment by IchordeDionysos** [comment]
Is there any workaround available for this?

**Comment by dnfield** [comment]
Only thing I know of at the moment is to build your own engine that never uses a resource context.

**Comment by dnfield** [comment]
I believe I have a fix for this - I should have a PR up for it sometime soon.

**Comment by dnfield** [comment]
(My initial milestone estimate was assuming this change might impact other platforms - we should be able to land something sooner that at least fixes this for iOS)

**Comment by ForelaxX** [comment]
@dnfield Thanks a lot, but I wonder why this situation only happens on iOS real device?

**Comment by dnfield** [comment]
We only use OpenGL on real devices - Simulator always uses software rendering.  This issue is OpenGL specific.

**Comment by ForelaxX** [comment]
> We only use OpenGL on real devices - Simulator always uses software rendering. This issue is OpenGL specific.

Got it. So for now seems like I should return to the 1.0.0 as workaround?

**Comment by dnfield** [comment]
That would work - I suspect you don't have to go back quite that far but I'm not really sure what version this change landed in and it's not entirely trivial to figure that out.  This should get fixed on master before very long (I'd say in the next weekish), be on dev not too long after that, and be in beta _probably_ for May.

**Comment by ForelaxX** [comment]
Got it, thanks a lot 😃

**Comment by dnfield** [comment]
This should land on master sometime today.

**Comment by dnfield** [comment]
Rolled into framework https://github.com/flutter/flutter/pull/30335 (https://github.com/flutter/flutter/commit/99f1e507c9fe198fbdccdf8a2b6af63dc010736c)

**Comment by IchordeDionysos** [comment]
Thank you very much for your quick fix, Dan.
I just tried it and everything works fine now :)
