### ISSUE TITLE
Ethereum HD Wallet implementation in Flutter, is there any library in Flutter?

### ISSUE THREAD

**Issue by ishwarchandratiwari** [flutter/flutter#29995]
**Are there any existing libraries in flutter to create Ethereum HD wallet?**
I have used ethereumjs-wallet npm package to generate a unique wallet address in node.js

```
var hdkey = require('ethereumjs-wallet/hdkey');
var hdwallet = hdkey.fromExtendedKey(extPubKey);
```
I want to use the above script in flutter but ethereumjs-wallet library is not available in flutter libraries.

> **Is there any way to generate Ethereum address using mnemonic or privatekey in flutter?**

**Comment by shikhars371** [comment]
have you got any?
