### ISSUE TITLE
Unable to debug / hit breakpoints in flutter app in the visual studio code

### ISSUE THREAD

**Issue by vijayredme** [flutter/flutter#29992]
I am using vs code and trying to debug the application, but when i hit 'Start Debugging' button in vs code, app simply launches and never hits breakpoint. anyone has a clue asto what could be wrong ?

**Comment by zsmjhtn** [comment]
Having same problem! 
When I debugging  flutterApp, only main lib *dart fils  can be debuged.
I can not go on debug flutter-plugin code ,which  invoked  in  main lib/xxx.dart.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by Tabarek** [comment]
having the same problem with flutter version 1.10.4-pre.55 channel master @escamoteur

**Comment by escamoteur** [comment]
@Tabarek is it on Android or iOS that you have the problem?
Could you please post the output of `flutter doctor -v`here.

**Comment by Tabarek** [comment]
@escamoteur both of theme 

[✓] Flutter (Channel master, v1.10.4-pre.55, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.10.4-pre.55 at /Users/tabarekaljaaf/flutter
    • Framework revision abfad9cc49 (7 weeks ago), 2019-09-18 00:14:41 -0400
    • Engine revision 36be89da49
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 f22f62c85d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tabarekaljaaf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM G965F • 24192e34f80c7ece • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by escamoteur** [comment]
@Tabarek Best to raise a new issue here https://github.com/Dart-Code/Dart-Code/issues

**Comment by tberghuis** [comment]
I got this problem when I opened project folder via a symbolic link

**Comment by kazyamof** [comment]
Same problem here VsCode:

[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [versÃ£o 10.0.18363.778], locale pt-BR)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision d3ed9ec945 (11 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\daybs\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\daybs\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\daybs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 7.1.1 (API 25) (emulator)
    • Chrome                       • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                   • web-server    • web-javascript • Flutter Tools

• No issues found!
