### ISSUE TITLE
Icons won't load

### ISSUE THREAD

**Issue by nalkon** [flutter/flutter#300]
After creating basic app (either with Atom or with command line) content folder is missing. Even after adding it manually together with  pngs (content/drawable-xxhdpi/ic_add_white_24dp.png),  the icon still won't load. 

Logcat warning: 

 [WARNING:asset_bundle_impl.cc(45)] Requested asset 'content/drawable-xxhdpi/ic_add_white_24dp.png' does not exist

The same applies to any other icon:
 [WARNING:asset_bundle_impl.cc(45)] Requested asset 'action/drawable-xxhdpi/ic_search_white_24dp.png' does not exist.
[WARNING:asset_bundle_impl.cc(45)] Requested asset 'navigation/drawable-xxhdpi/ic_menu_white_24dp.png' does not exist.

My system:

Ubuntu 14.04
Nexus 5
Android 6.0

**Comment by abarth** [comment]
I think you need to add a flutter.yaml file.  We don't document this very well, unfortunately.  Take a look at the flutter.yaml in the Stocks example.

**Comment by sethladd** [comment]
flutter.yaml is now in our tutorial. We can improve the docs for this, of course, and I'll open an issue for that over on our site.

@nalkon if you're still not able to get icons to load after you added a flutter.yaml, please reopen this issue. Thanks for the report!
