### ISSUE TITLE
Text Cursor Handle Color stays Blue

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#30005]
I am not sure if I should open this issue, but I have tried out all `Theme` and `InputDecoration` attributes I can think of and it just does not change.

[Relevant StackOverflow question](https://stackoverflow.com/q/55366965/6509751)

**Comment by Kartik1607** [comment]
Please post the code you are trying this with.


**Sample working code**
```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      theme: ThemeData.dark().copyWith(cursorColor: Colors.red),
      home: Scaffold(
        body: MainApp(),
      ),
    ));

class MainApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(child: TextField(
      
    ));
  }
}

```

**Comment by creativecreatorormaybenot** [comment]
@Kartik1607 Not for me. Android `28`, Flutter `v1.3.14-pre.64`.

**Comment by creativecreatorormaybenot** [comment]
@Kartik1607 The underlying problem was addressed in an [answer on StackOverflow](https://stackoverflow.com/a/55374072/6509751).
