### ISSUE TITLE
ClipRRect with DateTimePicker as child doesn't change the widget

### ISSUE THREAD

**Issue by yoavabadi** [flutter/flutter#30001]
Not sure if this is intended for this purpose, or if ClipRRect is only for image widgets, but it takes any widget as a child, but doesn't round the DateTimePicker (but DOSEN'T displays any errors).
Can it works for the DateTimePicker?
Thanks,
Yoav.

**Comment by VladyslavBondarenko** [comment]
Hi @yoavabadi 
ClipRRect is not only for images.
I hope you've solved your problem, closing as probably outdated.
If you still experience this,
please provide a minimal code sample to reproduce the problem,
specify plugin version if you are using some, provide your `flutter doctor -v`,
and I'll reopen it
Thank you
