### ISSUE TITLE
Problems with code suggestions in VSCode on Flutter 1.3.8

### ISSUE THREAD

**Issue by Ibtesam-Mahmood** [flutter/flutter#30004]
I recently updated to Flutter version 1.3.8, after updating the auto completion on VSCode stopped working. However, this was working before the update.

<img width="637" alt="Screen Shot 2019-03-26 at 6 17 18 PM" src="https://user-images.githubusercontent.com/29645101/55037232-6f08b680-4ff3-11e9-92db-e039f4d297fe.png">

My flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.3.8, on Mac OS X 10.14.2 18C54, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] VS Code (version 1.32.3)
[!] Connected device
    ! No devices available

**Comment by DanTup** [comment]
This is being investigated at https://github.com/Dart-Code/Dart-Code/issues/1565.
