### ISSUE TITLE
MissingPluginException while adding to existing iOS application

### ISSUE THREAD

**Issue by 463292462** [flutter/flutter#30016]
I developed according to the official [website.](https://flutter.dev/docs/development/platform-integration/platform-channels )in Flutterproject->ios->runner->AppDelegate ,
then flutter clean -> flutter build ios --debug
then drag the file ios->Flutter into  existing project and add App.framework、Flutter.framework to Embedded Binaries

existing project:
FlutterEngine *flutterEngine = [(AppDelegate *)[[UIApplication sharedApplication] delegate] flutterEngine];
FlutterViewController *flutterViewController = [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
[self presentViewController:flutterViewController animated:false completion:nil];

I encountered the following problems when embedding into an existing project.
MissingPluginException(No implementation found for method getAppInfo on channel com.AppInfoPlugin)

**Comment by jkmathew** [comment]
Have you ran `[GeneratedPluginRegistrant registerWithRegistry: flutterEngine]` before instantiating `FlutterViewController ` ?

**Comment by 463292462** [comment]
in Flutterproject->ios->runner->AppDelegate   according to the official [website](https://flutter.dev/docs/development/platform-integration/platform-channels)

#import <Flutter/Flutter.h>
#import "GeneratedPluginRegistrant.h"

@implementation AppDelegate
- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {
  FlutterViewController* controller = (FlutterViewController*)self.window.rootViewController;

  FlutterMethodChannel* batteryChannel = [FlutterMethodChannel
                                          methodChannelWithName:@"samples.flutter.io/battery"
                                          binaryMessenger:controller];

  [batteryChannel setMethodCallHandler:^(FlutterMethodCall* call, FlutterResult result) {
    // TODO
  }];

  [GeneratedPluginRegistrant registerWithRegistry:self];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

**Comment by jkmathew** [comment]
Yes, In the sample its registering `GeneratedPluginRegistrant`. 
see `[GeneratedPluginRegistrant registerWithRegistry:self];`

**Comment by jkmathew** [comment]
Wait, is `com.AppInfoPlugin` your method channel? `getAppInfo` method call handled correctly?

**Comment by 463292462** [comment]
.
