### ISSUE TITLE
 when I run the project, issue this exception and cannot display the app's interface, let me know how to fix it

### ISSUE THREAD

**Issue by doanbh** [flutter/flutter#30018]
## Steps to Reproduce

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28848): The following assertion was thrown attaching to the render tree:
I/flutter (28848): 'package:flutter/src/material/slider_theme.dart': Failed assertion: line 233 pos 16: 'trackHeight !=
I/flutter (28848): null': is not true.
I/flutter (28848): 
I/flutter (28848): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28848): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28848): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28848):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28848): 
I/flutter (28848): When the exception was thrown, this was the stack:
I/flutter (28848): #2      new SliderThemeData (package:flutter/src/material/slider_theme.dart:233:16)
I/flutter (28848): #3      new _mainState (package:musicplayer/main.dart:53:22)
I/flutter (28848): #4      MyApp.createState (package:musicplayer/main.dart:10:16)
I/flutter (28848): #5      new StatefulElement (package:flutter/src/widgets/framework.dart:3809:25)
I/flutter (28848): #6      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:805:38)
I/flutter (28848): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2958:40)
I/flutter (28848): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (28848): #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (28848): #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (28848): #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (28848): #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2257:19)
I/flutter (28848): #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (28848): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (28848): #15     runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (28848): #16     main (package:musicplayer/main.dart:5:16)
I/flutter (28848): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
I/flutter (28848): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
I/flutter (28848): #23     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
I/flutter (28848): #24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
I/flutter (28848): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (28848): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Kartik1607** [comment]
Please provide some minimal code which is causing the error.

**Comment by doanbh** [comment]
My code create new SliderThemeData:
ThemeData darktheme = new ThemeData(
    brightness: Brightness.dark,
    accentColor: Colors.grey[800],
    fontFamily: 'Raleway',
    sliderTheme: new SliderThemeData(
      activeTrackColor: Colors.deepPurpleAccent[700],
      inactiveTrackColor: Colors.deepPurpleAccent[100],
      activeTickMarkColor: Colors.white70,
      inactiveTickMarkColor: Colors.black,
      overlayColor: Colors.black12,
      thumbColor: Colors.purple,
      valueIndicatorColor: Colors.deepPurpleAccent,
      thumbShape: new RoundSliderThumbShape(),
      disabledActiveTrackColor: Colors.red,
      disabledInactiveTickMarkColor: Colors.green,
      disabledInactiveTrackColor: Colors.grey,
      disabledActiveTickMarkColor: Colors.cyanAccent,
      disabledThumbColor: Colors.grey,
      valueIndicatorShape: PaddleSliderValueIndicatorShape(),
      valueIndicatorTextStyle: TextStyle(color: Colors.black87),
      showValueIndicator: ShowValueIndicator.always,
    ),
    dialogBackgroundColor: Colors.black,
  );

**Comment by Kartik1607** [comment]
Hi, if you look at documentation for [SliderThemeData](https://docs.flutter.io/flutter/material/SliderThemeData-class.html), you will find that all of its properties are **required**.

You have not given any value for following properties
1. overShape
2. tickMarkShape
3. trackHeight
4. trackShape

Of course, you may not want to give new properties to all values and would want these properties to use their default values, for which correct way would be use `copyWith`

Example
```dart
    Theme.of(context).sliderTheme.copyWith(
          activeTrackColor: Colors.deepPurpleAccent[700],
          inactiveTrackColor: Colors.deepPurpleAccent[100],
          activeTickMarkColor: Colors.white70,
          inactiveTickMarkColor: Colors.black,
          overlayColor: Colors.black12,
          thumbColor: Colors.purple,
          valueIndicatorColor: Colors.deepPurpleAccent,
          thumbShape: new RoundSliderThumbShape(),
          disabledActiveTrackColor: Colors.red,
          disabledInactiveTickMarkColor: Colors.green,
          disabledInactiveTrackColor: Colors.grey,
          disabledActiveTickMarkColor: Colors.cyanAccent,
          disabledThumbColor: Colors.grey,
          valueIndicatorShape: PaddleSliderValueIndicatorShape(),
          valueIndicatorTextStyle: TextStyle(color: Colors.black87),
          showValueIndicator: ShowValueIndicator.always,
        );
```

**Comment by VladyslavBondarenko** [comment]
Closing since solved
