### ISSUE TITLE
Will flutter suport Js or typescript?

### ISSUE THREAD

**Issue by Allenyn** [flutter/flutter#30017]
As a ReactNative Developer, I do not want to study Dart.
Will flutter support js/ts language ? It will be more attractive.

**Comment by jonahwilliams** [comment]
Hi @Allenyn, Flutter leverages Dart to allow both JIT compilation for fast debugging/hot reload and AOT compilation to native arm code. This is a fairly unique capability that isn't shared by JavaScript/Typescript, which always require a JavaScript VM to run.

You can find more information on why Flutter chose dart in our FAQ https://flutter.dev/docs/resources/faq#why-did-flutter-choose-to-use-dart and in this article https://hackernoon.com/why-flutter-uses-dart-dd635a054ebf

**Comment by xtutu** [comment]
@jonahwilliams 
create a ts-llvm may be a good choice.

for example:
[https://github.com/ts-llvm/ts-llvm](https://github.com/ts-llvm/ts-llvm)
