### ISSUE TITLE
MaterialButton disabledColor is not working.

### ISSUE THREAD

**Issue by yuekungit** [flutter/flutter#30012]
The disabledColor is not working in MaterialButton.

```dart
@override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final ButtonThemeData buttonTheme = ButtonTheme.of(context);

    return RawMaterialButton(
      onPressed: onPressed,
      onHighlightChanged: onHighlightChanged,
      fillColor: color,
      textStyle: theme.textTheme.button.copyWith(color: buttonTheme.getTextColor(this)),
      highlightColor: highlightColor ?? theme.highlightColor,
      splashColor: splashColor ?? theme.splashColor,
      elevation: buttonTheme.getElevation(this),
      highlightElevation: buttonTheme.getHighlightElevation(this),
      padding: buttonTheme.getPadding(this),
      constraints: buttonTheme.getConstraints(this).copyWith(
        minWidth: minWidth,
        minHeight: height,
      ),
      shape: buttonTheme.shape,
      clipBehavior: clipBehavior ?? Clip.none,
      animationDuration: buttonTheme.getAnimationDuration(this),
      child: child,
      materialTapTargetSize: materialTapTargetSize ?? theme.materialTapTargetSize,
    );
  }
```

**Comment by HansMuller** [comment]
I assume that what you're getting at is that a MaterialButton that specifies `disabledColor` and `onPressed: null` doesn't actually use the `disabledColor`? Best way to describe the problem is to provide a small self-contained app that demonstrates it.

**Comment by mateusfsilva** [comment]
We have the same issue here.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage() : super();

  @override
  Widget build(
    BuildContext context,
  ) =>
      Scaffold(
        appBar: AppBar(
          title: Text('Material Button'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              MaterialButton(
                color: Colors.red,
                disabledColor: Colors.grey,
                onPressed: () {},
                child: Text('Enabled'),
              ),
              MaterialButton(
                color: Colors.red,
                disabledColor: Colors.grey,
                onPressed: null,
                child: Text('Disabled'),
              ),
            ],
          ),
        ),
      );
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.4.7, on Mac OS X 10.13.6 17G6030, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.2)
[✓] VS Code (version 1.32.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by HansMuller** [comment]
@mateusfsilva - Thanks for providing a complete test case! A fix should land in the next day or so: #30531.

**Comment by lukepighetti** [comment]
I'm on Flutter `1.14.6` and changing `MaterialApp.ThemeData.ButtonThemeData.disabledColor` doesn't change a `RaisedButton` color from the default gray even if it's `onPressed` handler is null. Is this the purpose of `disabledColor` theme setting?

**Comment by gmaggio** [comment]
> Edit: it appears you have to change `textTheme: ButtonTextTheme.normal`. It's not clear why this is the case.

Okay, first of all, this is unintuitive. Secondly, setting `textTheme` from the `buttonTheme` to `ButtonTextTheme.normal` doesn't allow changing the text color. `RaisedButton`, `OutlineButton`, and `FlatButton`, end up having a black text. Setting the button color in the `textTheme` from the base ThemeData doesn't do anything.

**Comment by sameercarpenter** [comment]
> > Edit: it appears you have to change `textTheme: ButtonTextTheme.normal`. It's not clear why this is the case.
> 
> This shouldn't be the case. First of all, this is unintuitive. Secondly, setting `textTheme` from the `buttonTheme` to `ButtonTextTheme.normal` doesn't allow changing the text color. `RaisedButton`, `OutlineButton`, and `FlatButton`, end up having a black text. Setting the button color in the `textTheme` from the base ThemeData doesn't do anything.
> 
> I think we need a way to fully theme our buttons via the `ThemeData`.

You can change the text color, by using `foreground` in button text theme.
Like this `foreground: Paint()..color=Colors.white`

**Comment by definitelyokay** [comment]
> > > Edit: it appears you have to change `textTheme: ButtonTextTheme.normal`. It's not clear why this is the case.
> > 
> > 
> > This shouldn't be the case. First of all, this is unintuitive. Secondly, setting `textTheme` from the `buttonTheme` to `ButtonTextTheme.normal` doesn't allow changing the text color. `RaisedButton`, `OutlineButton`, and `FlatButton`, end up having a black text. Setting the button color in the `textTheme` from the base ThemeData doesn't do anything.
> > I think we need a way to fully theme our buttons via the `ThemeData`.
> 
> You can change the text color, by using `foreground` in button text theme.
> Like this `foreground: Paint()..color=Colors.white`

Can you give an example?

```
final theme = ThemeData.light().copyWith(
buttonTheme: ButtonThemeData(
          buttonColor: Colors.blue,
          disabledColor: Colors.red,
          textTheme: ButtonTextTheme.normal,
        ),
);
```

**Comment by d9media** [comment]
Having the same issue as described previously

**Comment by HansMuller** [comment]
@d9media - we've updated the Button widgets and I think you'll find that you can customize `TextButton` to get exactly the visuals you want. See the "Migrating buttons with custom disabled colors" in flutter.dev/go/material-button-migration-guide
