### ISSUE TITLE
Document uninstalling flutter sdk for macOS

### ISSUE THREAD

**Issue by xietx1995** [flutter/flutter#30014]
I want to remove flutter, but there is no document on the internet.

**Comment by Nothing-Works** [comment]
just `rm -rf` the sdk floder,

**Comment by Kartik1607** [comment]
![tenor](https://user-images.githubusercontent.com/17377741/55093412-59ba8780-50da-11e9-9503-77567bf69e21.gif)

**Comment by jmagman** [comment]
A request for a `flutter uninstall` is being tracked with https://github.com/flutter/flutter/issues/15202, but it's not split out by platform (maybe it should be).
We can call this a request for documentation for uninstalling on macOS, though.  I don't see anything about uninstalling in any official documentation.  This is the closest thing I see:
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by jmagman** [comment]
Windows request here: https://github.com/flutter/flutter/issues/29278

**Comment by Sameerkash** [comment]
@jmagman should this issue go in the wiki or the flutter site?

**Comment by jmagman** [comment]
The wiki is generally documentation for Flutter contributors (like running Flutter's tests or compiling the engine) and flutter.dev is for developers who use Flutter to make apps.  So this should go on the website https://github.com/flutter/website

**Comment by Sameerkash** [comment]
@jmagman Thanks, I'll reopen an issue there about this. Also, I think we can provide a simple script for windows and Unix/Linux within the flutter SDK that will clean all folders, I'll open a separate issue on it and tag you.

**Comment by Sameerkash** [comment]
@xietx1995 you can track this progress on this [PR](https://github.com/flutter/website/pull/5746)
