### ISSUE TITLE
 NoSuchMethodError: The method 'signOut' was called on null.

### ISSUE THREAD

**Issue by red98** [flutter/flutter#30020]
root.dart

import 'package:flutter/material.dart';
import 'login_signup.dart';
import 'authentication.dart';
import 'mainpage.dart';

class RootPage extends StatefulWidget {
  RootPage({this.auth});

  final BaseAuth auth;

  @override
  State<StatefulWidget> createState() => new _RootPageState();
}

enum AuthStatus {
  NOT_DETERMINED,
  NOT_LOGGED_IN,
  LOGGED_IN,
}

class _RootPageState extends State<RootPage>{
AuthStatus authStatus = AuthStatus.NOT_DETERMINED;
String _userId = "";

@override
void initState(){
  super.initState();
  widget.auth.getCurrentUser().then((user){
    setState((){
      if (user != null) {
      _userId = user?.uid;
      }
      authStatus =
            user?.uid == null ? AuthStatus.NOT_LOGGED_IN : AuthStatus.LOGGED_IN;
    });
  });
}

  void _onLoggedIn() {
    widget.auth.getCurrentUser().then((user){
      setState(() {
        _userId = user.uid.toString();
      });
    });
    setState(() {
      authStatus = AuthStatus.LOGGED_IN;

    });
  }

    void _onSignedOut() {
    setState(() {
      authStatus = AuthStatus.NOT_LOGGED_IN;
      _userId = "";
    });
  }

@override
  Widget build(BuildContext context) {
    switch (authStatus) {
      case AuthStatus.NOT_DETERMINED:
        return MyHomePage(
          auth: widget.auth,
          onSignedIn: _onLoggedIn,
        );
        break;
      case AuthStatus.NOT_LOGGED_IN:
        return new MyHomePage(
          auth: widget.auth,
          onSignedIn: _onLoggedIn,
        );
        break;
      case AuthStatus.LOGGED_IN:
        if (_userId.length > 0 && _userId != null) {
          return new mainpage(
            userId: _userId,
            auth: widget.auth,
            onSignedOut: _onSignedOut,
          );
        }
        break;
      default:
        return MyHomePage(
          auth: widget.auth,
          onSignedIn: _onLoggedIn,
        );
    }
  }
}

mainpage.dart

import 'package:flutter/material.dart';
import 'authentication.dart';
import 'root.dart';
class mainpage extends StatefulWidget{
  mainpage({Key key, this.auth, this.userId, this.username, this.onSignedOut})
      : super(key: key);

final BaseAuth auth;
final VoidCallback onSignedOut;
final String userId;
final String username;

@override
State<StatefulWidget> createState() => new _mainpageState();
}

class _mainpageState extends State<mainpage>{

@override
  _signOut() async {
    try {
      await widget.auth.signOut();
      widget.onSignedOut();
    } catch (e) {
      print(e);
    }
  }

@override
Widget build(BuildContext context){
return Scaffold(
  appBar: new AppBar(
    backgroundColor: Colors.white,
    centerTitle: true,
    title: new Text("TRAVEL PLEASURE",style: TextStyle(color: Colors.deepPurple[300]),),
        actions: <Widget>[
      IconButton(
        icon: Icon(Icons.exit_to_app),
        color: Colors.deepPurple[300 ],
        tooltip: 'Open shopping cart',
        onPressed: _signOut,
      ),
    ],),
          body: new TabBarView(children: <Widget>[
        new travel(),
        new favourite(),
        new account()
      ]),
    bottomNavigationBar: TabBar( // new
          tabs: <Widget>[
            new Tab(
              icon: new Icon(Icons.home,color: Colors.deepPurple[300],),
              //child: new Text("TRAVEL",style: TextStyle(color: Colors.deepPurple[300]),),
      
            ), // 1st Tab
            new Tab(
                icon: new Icon(Icons.favorite_border,color: Colors.deepPurple[300],),
                //child: new Text("FAVORITE",style: TextStyle(color: Colors.deepPurple[300]),),// 2nd Tab
            ),
            new Tab(
                icon: new Icon(Icons.account_circle,color: Colors.deepPurple[300],),
                //child: new Text("ACCOUNT",style: TextStyle(color: Colors.deepPurple[300]),),
            ),],
     ),
      
          
);
}
}

class travel extends StatefulWidget{

  @override
  State<StatefulWidget> createState() => new _travelState();
}

class _travelState extends State<travel>{

  Widget build(BuildContext context){
  return Scaffold(

  );
  }
}

class favourite extends StatefulWidget{

  @override
  State<StatefulWidget> createState() => new _favouriteState();
}

class _favouriteState extends State<favourite>{

  Widget build(BuildContext context){
    return Scaffold(
    appBar: new AppBar(
      backgroundColor: Colors.white,
      centerTitle: true,
      title: new Text("TRAVEL PLEASURE",style: TextStyle(color: Colors.deepPurple[300]),),
    ),
  );
  }
}

class account extends StatefulWidget{
  account({Key key, this.auth, this.userId, this.username, this.onSignedOut})
      : super(key: key);

final BaseAuth auth;
final VoidCallback onSignedOut;
final String userId;
final String username;

  @override
  State<StatefulWidget> createState() => new _accountState();
}

class _accountState extends State<account>{

@override
  _signOut() async {
    try {
      await widget.auth.signOut();
      widget.onSignedOut();
    } catch (e) {
      print(e);
    }
  }

  Widget build(BuildContext context){
    return Scaffold(
    appBar: new AppBar(
      backgroundColor: Colors.white,
      centerTitle: true,
      title: new Text("TRAVEL PLEASURE",style: TextStyle(color: Colors.deepPurple[300]),),
            actions: <Widget>[
      IconButton(
        icon: Icon(Icons.exit_to_app),
        color: Colors.deepPurple[300 ],
        tooltip: 'Open shopping cart',
        onPressed: _signOut,
      ),
    ],
 ),
  );
  }
}

**Comment by red98** [comment]
i want to let my sign out function to move to account class, but after moving it says nosuchmethod for my signout function

**Comment by najeira** [comment]
Pass `auth` param to `account` class.

This seems not to be Flutter's issue. StackOverflow is good for asking how-to.

**Comment by red98** [comment]
ok
