### ISSUE TITLE
Hot reload/restart not working due to null pointer exception

### ISSUE THREAD

**Issue by codmajik** [flutter/flutter#30026]
## Steps to Reproduce
on master channel
flutter upgrade.
then change or update a file for reload you get

> Error running hot-reload: NoSuchMethodError: 
> The method 'isAfter' was called on null.  
> Receiver: null  
> Tried calling: isAfter(Instance of 'DateTime')  

## Logs
flutter doctor -v 

[√] Flutter (Channel master, v1.4.2-pre.3, on Microsoft Windows [Version 10.0.17763.379], locale en-GH)
    • Flutter version 1.4.2-pre.3 at C:\flutter
    • Framework revision bafe7cbbb4 (4 hours ago), 2019-03-26 21:40:53 -0700
    • Engine revision 0d83a2ecd1
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Chinedu\AppData\Local\Android\Sdk\
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Chinedu\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\Chinedu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Nokia 6 1 Plus • DRGGAM5891209280 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by codmajik** [comment]
Sorry, 
Github stopped sending me emails about issues I am interested not sure why. But this was fixed a long time ago.

**Comment by jonahwilliams** [comment]
Thanks @codmajik , I'll close the issue now
