### ISSUE TITLE
Error: A value of type 'Future<Image>' can't be assigned to a variable of type 'Image'. in qr_painter.dart

### ISSUE THREAD

**Issue by LeonLeonski** [flutter/flutter#30031]
After I made a flutter update this Error occoured. 

![image](https://user-images.githubusercontent.com/47663811/55068898-213b8f00-5083-11e9-82c0-e4b595a3b200.png)

I tried to comment out the error and it worked with some other errors but i can work now.

![image](https://user-images.githubusercontent.com/47663811/55069239-dbcb9180-5083-11e9-9a7c-cd2dab757555.png)

flutter docor :
![image](https://user-images.githubusercontent.com/47663811/55069469-7035f400-5084-11e9-9065-19eaab7c0c2a.png)

**Comment by developer-zsg** [comment]
look this:  https://github.com/lukef/qr.flutter/issues/16

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
