### ISSUE TITLE
incomplete documentation for flutter plugin firebase_crashlytics

### ISSUE THREAD

**Issue by abhaumik** [flutter/flutter#30030]
Along with the instructions mentioned, I had to add the following line to [project]/android/app/build.gradle in the dependencies section to get crash reports on the dashboard.

implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'

**Comment by ghunter99** [comment]
Doing this enabled me to get crash reports on the dashboard too.
Seems like an important instruction to add to the firebase_crashlytics plugin readme.

**Comment by kroikie** [comment]
@abhaumik

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1153. Any further collaboration will be done there.
