### ISSUE TITLE
[firebase_crashlytics] Getting started documentation typo ?

### ISSUE THREAD

**Issue by bagintz** [flutter/flutter#30038]
The documentation shows 
`Crashlytics.instance.reportInDevMode = true;`

But it seems that that should be `enableInDevMode` instead.

**Comment by JeffScaturro** [comment]
Looking at [latest](https://github.com/flutter/plugins/tree/master/packages/firebase_crashlytics) this appears to be fixed.

**Comment by kf6gpe** [comment]
Closing as this appears fixed. Feel free to re-open if this is in error.

**Comment by kroikie** [comment]
@bagintz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1152. Any further collaboration will be done there.
