### ISSUE TITLE
Mixing Chinese and English characters create double underline on Huawei phones

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#30041]
To reproduce, render this on a Huawei phone:

```dart
       Text(
          '中文 Button tapped 0 times.',
          style: TextStyle(
            color: Colors.blue,
            fontWeight: FontWeight.bold,
            decoration: TextDecoration.underline,
          )
```

Observe:

![image](https://user-images.githubusercontent.com/6687929/55088822-a2862800-5069-11e9-9169-4c050dea56ca.png)

Could it be the baseline for Chinese vs English is different and we are using both to draw the underline?

This is from a Google customer so they are on the latest Flutter/Engine framework.

**Comment by HansMuller** [comment]
CC @GaryQian
