### ISSUE TITLE
flutter is  throwing  an error about slivers though i dont use any widgets regarding to them. i implemented  a basic scaffold without even a body and still it is throwing error saying 'indexof(child) > index

### ISSUE THREAD

**Issue by krishnagandrath** [flutter/flutter#30045]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by krishnagandrath** [comment]
This is my implementation code:
class _profilePageState extends State<profilePage> {
  FirebaseUser user;
  String username;
  @override
  void initState() async {
    // TODO: implement initState
    super.initState();
    user = await FirebaseAuth.instance.currentUser();
    DocumentSnapshot snapshot = await Firestore.instance.collection("users").document(user.uid).get();
    username = snapshot.data["name"];
    debugPrint(username);
  }
 @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold();
  }
}

**Comment by Kartik1607** [comment]
Please paste complete error log as well.

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

If so please share your code and the output of flutter doctor

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
