### ISSUE TITLE
flutter build ios --release fail

### ISSUE THREAD

**Issue by baipeng1009472720** [flutter/flutter#30042]
=== BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Release ===

 ld: framework not found sqflite clang: error: linker command failed with exit code 1 (use -v to see invocation)

help!!

**Comment by Jensen615** [comment]
Very similar problem as mine, except my build target is Flutter, not sqlite. 

mine says:
 === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by baipeng1009472720** [comment]
我的问题是iOS 添加的target 中会去获取Runner 下的包，获取不到导致的。我最终在我添加的target中也引入了Runner的依赖包 解决了。不知道你能看懂中文吗。。。
