### ISSUE TITLE
Flutter - shows a smudgy login screen

### ISSUE THREAD

**Issue by rlecheta** [flutter/flutter#30049]
my flutter app runs normal in Android/iOS simulators, but in the iPhone X device I got some smudgy login screen, as you can see in this screenshot. This happens just in the first time the apps is launched, if I touch some buttons or sometimes open the keyboard, the screen renders well.

Here you can see the screenshot: https://s3-sa-east-1.amazonaws.com/fluttertmp/error.png

What can I do?

You can replicate this bug, just open this simple project: https://s3-sa-east-1.amazonaws.com/fluttertmp/mapfre_flutter.zip

I am in the stable channel:

flutter channel
Flutter channels:
  beta
  dev
  master
* stable

This is my flutter doctor:

flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-BR)
    • Flutter version 1.2.1 at /Users/rlecheta/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rlecheta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rlecheta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio 3.3 Preview.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone X Livetouch • 3df0b5cd913328b1743d57c2a0f3a61cc5632e42 • ios • iOS 12.1.4

• No issues found!

**Comment by rlecheta** [comment]
If I change the 2 Image.asset to the FlutterLogo, the screen renders ok.

**Comment by Sh1d0w** [comment]
I am facing the same problem on the stable channel.

If I load a jpg or png image either via Image.asset or Image.network the whole screen renders like this. It seems like pretty serious issue? cc @zoechi

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?


Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
