### ISSUE TITLE
flutter is  throwing  an error about slivers though i dont use any widgets regarding to them. i implemented  a basic scaffold without even a body and still it is throwing error saying 'index

### ISSUE THREAD

**Issue by krishnagandrath** [flutter/flutter#30044]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Also does this happen on Android and iOS?

If so please share your code and the output of `flutter doctor`

Thanks a lot

**Comment by escamoteur** [comment]
Double post
