### ISSUE TITLE
Show dialog from widget right when it starts.

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#30050]
I am interested in displaying a dialog, right when a widget is displayed.

```
 Widget build(BuildContext context) {
  // >>>>  display dialog here or wherever  <<<<
    return Container(
         //.....
    )
}
```

In my case I perform some network calls and I am interested in displaying loaders and alerts (in case of no connection or other errors).

Something similar: [this stack question](https://stackoverflow.com/questions/52059024/fluttershow-dialog-on-widget/52062540#52062540)

**Comment by anticafe** [comment]
You can consider using [addPostFrameCallback](https://docs.flutter.io/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)

```
 Widget build(BuildContext context) {
    SchedulerBinding.instance.addPostFrameCallback((_) {
      // Code to show dialog
    }); 
    return Container(
         //.....
    )
}
````

**Comment by HansMuller** [comment]
This question comes up now and then and it should be possible to DTRT without resorting to addPostFrameCallback() however it's probably not clear _how_ to do that.  

An app can start with a nested route, like a dialog, visible:
```
MaterialApp(
  initialRoute: '/dialog',
  routes: <String, WidgetBuilder>{
    '/':   (BuildContext context) => HomePage(),
    '/dialog': (BuildContext context) => DialogPage(),
  },
);
```
In this case, when the app starts the HomePage is pushed and then the DialogPage is pushed on top of that. Here's a complete example: https://gist.github.com/HansMuller/fa4edde00a35e88f6dff40b80d29d58c

Would that work for your use case?

**Comment by durduman** [comment]
@anticafe , @HansMuller 
Thank you for your responses! For the moment I will use Future with delay or addPostFrameCallback is handling my situation.
