### ISSUE TITLE
test manifest creation

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3005]
We should have some tests to ensure that flutter_tools is creating good flx manifests. https://github.com/flutter/flutter/pull/3004 fixed a regresion w/ image loading.

**Comment by devoncarew** [comment]
@vlidholt @krisgiesing

**Comment by eseidelGoogle** [comment]
I'm not sure what this would mean.  This is from the `flutter create` template? or would this be with arbitrary pubspec.yaml files to make sure they're correctly compiled into app.flx files correctly?

**Comment by krisgiesing** [comment]
The latter. The (old) bug here was that the assets part of the manifest was generated incorrectly in some cases.

**Comment by Hixie** [comment]
We're getting rid of FLX in due course. I'm going to close this since it will become moot.
