### ISSUE TITLE
Issues with Licensing 

### ISSUE THREAD

**Issue by HackinSpock** [flutter/flutter#30065]
C:/Users/xxx/Appdata/Local/Android/sdk\tools\bin\sdkmanager --update
Error: Could not find or load main class '-Dcom.android.sdklib.toolsdir=$APP_HOME
Caused by: java.lang.ClassNotFoundException: '-Dcom.android.sdklib.toolsdir=$APP_HOME

From previous threads, I have changed @rem execute sdkmanager and the other one where I appended additional arguments. How would I solve this error?

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?

Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
