### ISSUE TITLE
Flutter ignores iOS low memory events

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3006]
http://developer.android.com/training/articles/memory.html
https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/PerformanceTips/PerformanceTips.html#//apple_ref/doc/uid/TP40007072-CH7-SW8

We should at least log, and ideally plumb this information down into Dart so it can do something sensible.

FYI @johnmccutchan @iposva-google

**Comment by chinmaygarde** [comment]
Are there existing hooks into the Dart VM that low memory notifications need to be plumbed into?

**Comment by johnmccutchan** [comment]
@chinmaygarde We don't have an API for this yet. Maybe @iposva-google has some suggestions here.

**Comment by chinmaygarde** [comment]
Ok. We can fairly easily give the VM information about the kind memory pressure the application as a whole is under. Of course, the VM could also detect this itself using platform specific checks. Whatever works best.

**Comment by Hixie** [comment]
On the short term we should probably just expose this the framework via hooks in dart:ui, similar to onBeginFrame. That would let us implement `Cache` (see #3568) which would solve the problems at the framework layer. We'd presumably also need to pipe this to the GC logic and any caches and buffers in the engine itself.

**Comment by Hixie** [comment]
The `SystemChannels.system.memoryPressure` platform message is what this should send. Android supports it, though the framework doesn't do much with it yet.

**Comment by dnfield** [comment]
This was fixed by https://github.com/flutter/engine/pull/9491 and https://github.com/flutter/engine/pull/14517
