### ISSUE TITLE
Issue from website page 使用缓存图片

### ISSUE THREAD

**Issue by lypcliuli** [flutter/flutter#30088]
From URL: https://www.flutterchina.club/cookbook/images/cached-images.md

![9E6161399540059FEDFE8916BDE435E1](https://user-images.githubusercontent.com/12068023/55134793-caa68180-5164-11e9-9f4a-f0516a5d0808.jpg)
这里设置placeholder应该用这样的吧： placeholder: (context, url) => CircularProgressIndicator(),  我直接按照网站上的写法是报错的。

**Comment by xster** [comment]
flutterchina.club is a community website and we can't update their content.

You can reference the official website https://flutter.dev/docs/cookbook/images/cached-images.
