### ISSUE TITLE
The image_picker plugin cannot select a photo of the ios version other than the screenshot.

### ISSUE THREAD

**Issue by wangyankun33** [flutter/flutter#30083]
`platform `
ios
`problem`
You can only select the picture of the screenshot in the album. After uploading the photo, upload it via the post function of dio, it will trigger DioErrorType. The content of the message is: error code: DioErrorType.RESPONSE, error message: Http status error [500]

`flutter doctor -v`
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D42, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/wyk/downloads/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wyk/downloads/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/wyk/downloads/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Roy的 iPhone • 00008020-00050C800C81002E • ios • iOS 12.1.4

• No issues found!

**Comment by escamoteur** [comment]
Hi, could you please confirm if this problem still exists with the latest versions on stable or master?



Thanks a lot

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
