### ISSUE TITLE
Focus based navigation needs to have the widget Rect.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#30084]
In order to be able to perform focus-based navigation, it is necessary to know the size and location of widgets that might be traversed to.

This is a tracking issue for the breaking change needed to collect this information, in order to fix #1608.

Currently, `FocusScopeNode.reparentIfNeeded` takes only the `FocusNode` that it will reparent. In order to provide services needed for keyboard focus traversal, this method will need to provide a `BuildContext` in order to be able to measure its size and location when determining the next widget to traverse to.
We propose to break the `FocusScopeNode` API by changing it's signature from:
```dart
void reparentIfNeeded(FocusNode node);
```
to
```dart
void reparentIfNeeded(BuildContext context, FocusNode node);
```

To modify code to compile again after this change, you would need to add a context argument to the call.  Typically, this method is called from a build method in order to keep the focus tree up to date with the widget tree, so instead of calling:
```dart
FocusScope.of(context).reparentIfNeeded(focusNode);
```
You would instead call:
```dart
FocusScope.of(context).reparentIfNeeded(context, focusNode);
```

**Comment by xiaoxiaohaozi** [comment]
Error: The method 'reparentIfNeeded' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///Users/Macro/Documents/Flutter/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'reparentIfNeeded'.
          FocusScope.of(context).reparentIfNeeded(context,node);

how to modify it ? thank you
tip: [✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)

**Comment by gspencergoog** [comment]
@xiaoxiaohaozi, you need to use a [`FocusAttachment`](https://api.flutter.dev/flutter/widgets/FocusAttachment-class.html) instead.  See the documentation for [`FocusNode`](https://api.flutter.dev/flutter/widgets/FocusNode-class.html) for an example. The focus system has changed quite a lot since `reparentIfNeeded` was used.  You might also consider switching to use the new [`Focus`](https://api.flutter.dev/flutter/widgets/Focus-class.html) or [`FocusScope`](https://api.flutter.dev/flutter/widgets/FocusScope-class.html) widgets to manage the focus node for you.
