### ISSUE TITLE
Having both a pan gesture recognizer and a scale gesture recognizer is redundant; scale is a 03-28 17:46:30.602 17861-17884/com.ray.flutter_canvas I/flutter: superset of pan. Just use the scale gesture recognizer.

### ISSUE THREAD

**Issue by RayChou1992** [flutter/flutter#30099]
## Steps to Reproduce

1. i just want to develop a widget to show a pic，so ,it need scale and pan absolutely。
but ，this inssue hanppend.scale is a superset of pan,sounds good ,but it does't work at here
2. i browsed @wmleler 's issues.He had a same probleom.
3. ...

## Logs

```
```

```
```

**Comment by RayChou1992** [comment]
Having both a pan gesture recognizer and a scale gesture recognizer is redundant; scale is a
03-28 17:46:30.602 17861-17884/com.ray.flutter_canvas I/flutter: superset of pan. Just use the scale gesture recognizer.

**Comment by escamoteur** [comment]
@Hixie is this so? Why do we have two widgets for this? Could we deprecate one

**Comment by Hixie** [comment]
They're not the same, it's just that you don't need both at the same time.
