### ISSUE TITLE
update to 1.2.1,run my app

### ISSUE THREAD

**Issue by s3hengwu** [flutter/flutter#30095]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  C:\Users\new\flutter\packages\flutter\lib\widgets.dart
...refers, in an import, to the following library:
  C:\Users\new\flutter\.pub-cache\hosted\pub.flutter-io.cn\vector_math-2.0.8\lib\vector_math_64.dart
Unfortunately, that library does not appear to exist on your file system.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
