### ISSUE TITLE
how to use HttpClient send post request with params？

### ISSUE THREAD

**Issue by wangchuanwen** [flutter/flutter#30098]
HttpClientRequest request = await HttpClient().postUrl(requestUri);
but,what about the queryParameters？

**Comment by SBNTT** [comment]
example

```dart
import 'package:http/http.dart' as http;

await http.post(
     url,
     headers: {
          "key": "value"
     },
     body: {
          "key": "value
     }
)
```

**Comment by wangchuanwen** [comment]
Http is a tripartite library. I want to use HttpClient.

Thanks!

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.
