### ISSUE TITLE
Unable to resolve: android

### ISSUE THREAD

**Issue by andreddie81** [flutter/flutter#30097]
Basically the problem is:

- Android side of flutter project started to show errors in Android Studio
 
- Application still runs in emulator without problems, iOS and Android.

- Opening the Android Studio project from Flutter->Open android module on android studio also works and no red error marks.

- Opening android folder on flutter project shows the following:

![image](https://user-images.githubusercontent.com/47588111/55143538-3fff5b80-513f-11e9-9b92-21fc989818de.png)
`flutter doctor:`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
