### ISSUE TITLE
Facing issues with camera in Flutter 0.9.0

### ISSUE THREAD

**Issue by nishant1890** [flutter/flutter#30090]
I am facing issues with camera 0.2.0 with flutter 0.9.0
`E/flutter (12582): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (12582): NoSuchMethodError: Attempted to use type 'CameraDescription' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the CameraDescription constructor and forget the 'new' operator?
E/flutter (12582): Receiver: CameraDescription
E/flutter (12582): Tried calling: CameraDescription(lensDirection: Instance of 'CameraLensDirection', name: "0")
E/flutter (12582): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
E/flutter (12582): #1      availableCameras.<anonymous closure> (package:camera/camera.dart:55)
E/flutter (12582): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
E/flutter (12582): #3      ListIterable.toList (dart:_internal/iterable.dart:219)
E/flutter (12582): #4      availableCameras (package:camera/camera.dart:59)
E/flutter (12582): <asynchronous suspension>
E/flutter (12582): #5      main (file:///home/nishant/alert_on_crises/lib/main.dart:13)
E/flutter (12582): <asynchronous suspension>
E/flutter (12582): #6      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
E/flutter (12582): #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Syncing files to device vivo 1723...                         5.8s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on vivo 1723 is available at: http://127.0.0.1:8101/
For a more detailed help message, press "h". To quit, press "q".`

**Comment by tomalabaster** [comment]
Are you able to share the minimum code required to recreate this? Is there also a reason you haven't upgraded your Flutter to a later version?

**Comment by escamoteur** [comment]
As there was no reply I close this here.
