### ISSUE TITLE
webview_flutter not working for Angular web app url's

### ISSUE THREAD

**Issue by frankps** [flutter/flutter#30100]
The webview_flutter component is not working for all URL's. Some URL's that we tried work, but when we want to show an existing Angular web app inside a flutter app, then nothing is shown, just a white background.
The url is: 
     https://aquasense.birdy.life/
Is this by design, a bug or should we do something extra?

**Comment by emaddoma** [comment]
Have you tried setting the javascriptMode to JavascriptMode.unrestricted?

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
