### ISSUE TITLE
The parent() method in CollectionReference falsely returns a CollectionReference

### ISSUE THREAD

**Issue by grundid** [flutter/flutter#30103]
The parent() method in CollectionReference should return a DocumentReference as stated in the comment in the source code.

The parent() method in DocumentReference is missing altogether.

This is about the cloud_firestore plugin.

**Comment by creativecreatorormaybenot** [comment]
@collinjackson Is the team aware of this issue?
[offending method](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/lib/src/collection_reference.dart#L20)

**Comment by collinjackson** [comment]
Thanks for the fix, @creativecreatorormaybenot

**Comment by kroikie** [comment]
@grundid

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/389. Any further collaboration will be done there.
