### ISSUE TITLE
Xiaomi mi max 3 default keyboard ignores TextInputAction on TextField

### ISSUE THREAD

**Issue by Uzere** [flutter/flutter#30107]
Xiaomi mi max 3 default keyboard always shows DONE button on keyboard, ignoring TextInputAction on TextField.
This happens only with default keyboard, if I switch to google keyboard then it works correctly.

My code:
```
          TextField(
            textInputAction: TextInputAction.search, // also tried newline
            autofocus: this.widget.autofocus,
            onSubmitted: _submit,
            keyboardType: TextInputType.multiline,
            maxLines: null,
            textCapitalization: TextCapitalization.sentences,
            style: TextStyle(
                color: Theme.of(context).textTheme.body1.color,
                fontSize: Consts.CHAT_TEXT_SIZE),
            controller: _textEditingController,
            decoration: InputDecoration.collapsed(
              hintText: this.widget.placeholder ??
                  AppLocalizations.of(context).sendMessage,
              hintStyle: TextStyle(color: CustomColors.fadedColor),
            ),
            focusNode: _focusNode,
          ),
```

Flutter doctor -v, connected device is the one with this issue

```
[✓] Flutter (Channel dev, v1.3.10, on Mac OS X 10.14.3 18D42, locale ru-RU)
    • Flutter version 1.3.10 at /Users/admin/dev/Flutter/flutter
    • Framework revision 4feefa3c9a (2 weeks ago), 2019-03-14 10:21:03 -0400
    • Engine revision 8b1a299ed5
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • MI MAX 3 • ee87cc95 • android-arm64 • Android 9 (API 28)

• No issues found!
```

<img width="346" alt="" src="https://user-images.githubusercontent.com/3975328/55157516-9f746000-516d-11e9-9d4f-38fce02d58c8.png">

**Comment by HansMuller** [comment]
CC @GaryQian

**Comment by GaryQian** [comment]
Do you know if this is only with a Xiaomi mi max 3? I don't have that specific device to test on, but if it repros on any other Xiaomi (or other OEMs) devices, it would help a lot to fix this.

**Comment by Uzere** [comment]
@GaryQian, https://play.google.com/store/apps/details?id=com.facemoji.lite.xiaomi.gp&rdid=com.facemoji.lite.xiaomi.gp - this keyboard app causes this issue. I've reproduced this bug on lg g6 with this keyboard. Non-flutter apps (telegram, for example) correctly show newline button where needed with this keyboard

**Comment by TahaTesser** [comment]
Hi @Uzere 
Are you still experiencing this issue on latest `stable`?

if yes, Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
