### ISSUE TITLE
The test command doesn't support --machine and coverage together

### ISSUE THREAD

**Issue by arturdm** [flutter/flutter#30108]
Running `flutter test` with both machine output and coverage data is not supported now. This means that it's necessary to run tests twice which can take some time. Is it possible to make this command accept both options at the same time?

```
$ flutter test --machine --coverage
Running "flutter packages get" in xxxxx...                     1.0s
The test command doesn't support --machine and coverage together
```

**Comment by zanderso** [comment]
fyi @jonahwilliams

**Comment by kuhnroyal** [comment]
Can't get this to work on current beta. The command runs with both arguments but there is no coverage  output file. If I only run with coverage then there is an output file.

**Comment by coreysprague** [comment]
Just updated to stable, and I'm seeing the same thing @kuhnroyal

**Comment by coreysprague** [comment]
@jonahwilliams should this be re-opened, or should I submit a new issue?

**Comment by zanderso** [comment]
@coreysprague Please file a new issue with `flutter doctor -v` and repro instructions. Thanks!
