### ISSUE TITLE
How to add Marker dymanically in google_maps_flutter ?

### ISSUE THREAD

**Issue by nirav4273** [flutter/flutter#30119]
I am trying to add marker on my current location. On button tap i fetch my location but now able to find any way to marker dynamic in documentation.

I am using `0.4.0` version. In earlier version there is method `addMaker()`. In current version not able to see this method in `GoogleMapController`.

**Comment by Kartik1607** [comment]
You can save the list of markers in the state. Whenever you want to add a new marker, add item to the list through `setState` method.

If you take a look at the example app, the markers are saved in a `Map` [line](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/place_marker.dart#L36)

```dart
Map<MarkerId, Marker> markers = <MarkerId, Marker>{};
```

Whenever, you want to add maker [here](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/place_marker.dart#L80), create new Marker and add to State

```dart
Marker marker = Marker(...)
setState(() {
      markers[markerId] = marker;
});
```

And your build function would just be [like this](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/place_marker.dart#L225)

```dart
child: GoogleMap(
    onMapCreated: _onMapCreated,
    initialCameraPosition: const CameraPosition(
        target: LatLng(-33.852, 151.211),
        zoom: 11.0,
    ),
    markers: Set<Marker>.of(markers.values),
),
```

**Comment by nirav4273** [comment]
@Kartik1607 Thanks.

**Comment by marceloentrada** [comment]
but, how to add a marker to indicate my location on tap? Not using a fixed latitude/longitude.
I can found how to do it.
TIA
Regards!
