### ISSUE TITLE
Gradle task assemble debug crash FileSystemException: Directory listing failed, path = 'C:$Recycle.Bin\<>*' (OS Error: Access is denied.

### ISSUE THREAD

**Issue by gmpravin** [flutter/flutter#30113]
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\elcot\demoapp\flutter_06.log;
please let us know at https://github.com/flutter/flutter/issues.
Gradle task assembleDebug failed with exit code 1

Here log file

flutter build bundle --suppress-analytics --target C:\Users\elcot\demoapp\lib\main.dart --track-widget-creation --compilation-trace-file compilation.txt --target-platform android-arm64 --depfile C:\Users\elcot\demoapp\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir C:\Users\elcot\demoapp\build\app\intermediates\flutter\debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Directory listing failed, path = 'C:\$Recycle.Bin\S-1-5-18\*' (OS Error: Access is denied.
, errno = 5)

#0      _Directory._fillWithDirectoryListing (dart:io/runtime/bindirectory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:249:5)
#2      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#3      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:478:63)
#4      _parseAssetFromFile (package:flutter_tools/src/asset.dart:614:29)
#5      _parseAssets (package:flutter_tools/src/asset.dart:540:7)
#6      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:127:53)
<asynchronous suspension>
#7      buildAssets (package:flutter_tools/src/bundle.dart:176:40)
<asynchronous suspension>
#8      build (package:flutter_tools/src/bundle.dart:145:36)
<asynchronous suspension>
#9      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:111:11)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:48:24)

**Comment by JustGabeHere** [comment]
I've been getting similar errors while running '`flutter run`'. I don't get why it is trying to access the recycle bin?

**Comment by jmagman** [comment]
Similar to https://github.com/flutter/flutter/issues/23519 but without the recycling bin weirdness.

**Comment by blasten** [comment]
This may be fixed by #43760

**Comment by jonahwilliams** [comment]
This issue is quite old and may have already been fixed by the assemble switch. Not sure about the Recycle Bin....

Fixed by https://github.com/flutter/flutter/issues/32925 ???
