### ISSUE TITLE
[google_maps_flutter] ClipRRect of map does not work on iOS

### ISSUE THREAD

**Issue by jamespfinn** [flutter/flutter#30117]
The behavior of the `GoogleMap()` widget differs on Android vs iOS.  When wrapped in a `ClipRRect()` to add a `borderRadius`, the maps displays as expected on Android but not iOS.

Included below is an example project and screenshot displaying the issue:
![image](https://user-images.githubusercontent.com/1694287/55174594-bc983700-514b-11e9-80f8-151e00bd416b.png)

```
class _MyHomePageState extends State<MyHomePage> {
  final Completer<GoogleMapController> _controller = Completer();
  final CameraPosition _googleHQ = CameraPosition(
    bearing: 0,
    target: LatLng(37.422, -122.084),
    tilt: 45,
    zoom: 16,
  );

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          height: 300,
          width: 300,
          child: ClipRRect(
            borderRadius: BorderRadius.all(Radius.circular(50.0)),
            child: GoogleMap(
              mapType: MapType.hybrid,
              initialCameraPosition: _googleHQ,
              onMapCreated: (GoogleMapController controller) {
                _controller.complete(controller);
              },
            ),
          ),
        ),
      )
    );
  }
}
```

Full test project can be found here:  https://github.com/jamespfinn/flutter_maps_clip_test
Be sure to set your maps api key.

**Comment by jamespfinn** [comment]
The `GoogleMap()` widget being a `UiKitView`, this seems to be related to this issue:
https://github.com/flutter/flutter/issues/25965

**Comment by jorg1piano** [comment]
Any updates on this? Any plans of supporting clipping of native UI views in iOS?

**Comment by cyanglaz** [comment]
duplicated with https://github.com/flutter/flutter/issues/25965. The clipping is working on iOS now and I'm closing the issue.

**Comment by amirpacolli03** [comment]
Still not working

**Comment by cto-leaps** [comment]
Any update on this?

**Comment by cyanglaz** [comment]
@cto-leaps This has been fixed on stable for a while now, does it not work for you?
