### ISSUE TITLE
CupertinoNavigationBar changing status bar color based on backgroundColor, no brightness property.

### ISSUE THREAD

**Issue by cosinus84** [flutter/flutter#30114]
CupertinoNavigationBar sets the status bar by its own depends on navigationBar backgroundColor

```
return CupertinoApp(
          theme: CupertinoThemeData(
              brightness: Brightness.light/dark)
          home:  CupertinoPageScaffold(
                  backgroundColor: Colors.white,
                  navigationBar: CupertinoNavigationBar(),
                  child: Center(
                    child: Text("Loading Appplication...."),
                  ),
                );

```
But this works:
```
return Scaffold(
                  appBar: AppBar(
                    brightness: Brightness.dark,
                  ),
                  body: Center(
                    child: Text("Text...."),
                  ),
 );
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.4.4, on Mac OS X 10.14.3 18D109, locale en-RO)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

**Comment by beauchette** [comment]
I have the exact same problem, if I remove the CuppertinoNavigationBar, I have 4 or 5 ways to force the status bar text color, if I put it back, it sets the text color depending on the background color you gave.

Did you find a workaround ?

**Comment by hugocbpassos** [comment]
@beauchette As I explained [here](https://stackoverflow.com/a/56582874/6696558), seems like there's no easy way to work around that, so I edited the `CupertinoNavigationBar` to hold a brightness attribute. Check [this ](https://gist.github.com/hugocbpassos/6a1160117349c7475480490de213e9a5)gist.

**Comment by 5turman** [comment]
I pass an instance of custom Color class with overwritten computeLuminance function to CupertinoNavigationBar as backgroundColor (or to CupertinoThemeData as barBackgroundColor)
```
class _ColorWithFakeLuminance extends Color {
  _ColorWithFakeLuminance(int value, this.luminance)
      : assert(luminance != null),
        super(value);

  final double luminance;

  double computeLuminance() => luminance;
}
```
If luminance < 0.179 then flutter thinks that the color is dark, so the status bark background is dark also (and text is white)

**Comment by BadReese** [comment]
Waiting for an official solution.

**Comment by beauchette** [comment]
While waiting, I highly recommend using 5turman's solution, it's cute and lightweight.

**Comment by BadReese** [comment]
> While waiting, I highly recommend using 5turman's solution, it's cute and lightweight.

Yes u r right

**Comment by rsfarias** [comment]
Thanks @5turman for the workaround! I've adapted it a bit to make it easier to instantiate directly from other colors and to simply tell if it should have light or dark luminance.

```dart
class _ColorWithFakeLuminance extends Color {
  final bool withLightLuminance;

  _ColorWithFakeLuminance(Color color, {@required this.withLightLuminance})
      : super(color.value);

  double get luminance {
    return withLightLuminance ? 0 : 1;
  }

  double computeLuminance() => luminance;
}
```

Usage:
```dart
final fakeColor = _ColorWithFakeLuminance(Colors.blue, withLightLuminance: true);
```

**Comment by TahaTesser** [comment]
Hi @cosinus84 
i can see there is brightness property in `CupertinoNavigationBar`

### Code Sample
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      home: CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          brightness: Brightness.light,
          middle: Text('Cupertino App Bar'),
        ),
        child: Center(
          child: Container(
            child: Text('Hello World'),
          ),
        ),
      ),
    );
  }
}
```

if you disagree please write in the comments and I will reopen it 
Thank you
