### ISSUE TITLE
firebase remote config error "Application name is not set"

### ISSUE THREAD

**Issue by sebastienchouan** [flutter/flutter#30128]
Hello,

I'm trying to integrate firebase remote config in a flutter app.
But when running the application, i've got this error :
**Application name is not set. Call Builder#setApplicationName.**

Library :
https://pub.dartlang.org/packages/firebase_remote_config

Following this example :
https://github.com/flutter/plugins/tree/master/packages/firebase_remote_config/example

Package flutter used:
firebase_remote_config: ^0.1.0+2

app/build.gradle:
implementation 'com.google.firebase:firebase-config:16.4.0'

Full error logs:
> W/zze     (25659): Application name is not set. Call Builder#setApplicationName.
I/FirebaseRemoteConfig(25659): Fetch succeeded!
W/zze     (25659): Application name is not set. Call Builder#setApplicationName.
W/zze     (25659): Application name is not set. Call Builder#setApplicationName.
W/FirebaseRemoteConfig(25659): No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'hello'.
W/FirebaseRemoteConfig(25659): No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'test'.

**Comment by dheeraj2dj** [comment]
@sebastienchouan Hey. Were you able to figure this out. Am facing the same issue.

**Comment by sebastienchouan** [comment]
Hello @dheeraj2dj  

In my case it was due to the fact i was using a wrong google account connexion : 
1. I configure firebase parameter with a google account 
2. I was using the file google-services.json from another google account

Be sure that in the firebase console, you've got the parameter you want to use.
Did it help ?

**Comment by bhanuka96** [comment]
this is working for me.
adding      ` await remoteConfig.fetch(expiration: const Duration(seconds: 0));` and `await remoteConfig.activateFetched();`

```
  void _adminValidate() async {
    try{
      final RemoteConfig remoteConfig = await RemoteConfig.instance;
      await remoteConfig.fetch(expiration: const Duration(seconds: 0));
      await remoteConfig.activateFetched();
      print(remoteConfig.getString('admin'));
    }catch (e){
      print(e);
    }
  }
```
