### ISSUE TITLE
Large / high quality images is rendered fully black on Android

### ISSUE THREAD

**Issue by matte5031** [flutter/flutter#30135]
If i have take a large image and add it as asset or take a picture with the camera that is big then if using asset for instance it would look like below:

                          Image.asset(
                            "assets/water_img.jpg",
                             fit: BoxFit.none,
                          ),

If I use boxfit.none I can see the image but it's really zoomed in so I only see like 1/20 of the image. If i remove the fit entirely or try to use another boxfit option, anyone, the image will be entirely black. I tried resizing the image and what I found was that when the image had width 3071 pixels or lower the image could be seen, but as soon as I set 3072 pixels or higher in width the image is just all black. 

I tried the resizing with the image plugin and with copyResize(image, 3071); for instance.
I'm using a motorola device version 8.0.0 and the latest flutter beta channel version. Migrated to androidx but the problem was seen before migration aswell. Did not see this poblem in january-february but not sure exactly when it started. 

This is my flutter dotctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.32.3)
[√] Connected device (1 available)

• No issues found!

Anyone else had this problem running on physical device only? 
Any help or input appreciated, thanks!

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by crazecoder** [comment]
I have the same issue
```
 Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A602, locale zh-Hans-CN)
```

**Comment by escamoteur** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
