### ISSUE TITLE
BorderRadius.only or .symmetric for circularRadius

### ISSUE THREAD

**Issue by JohnnyDevX** [flutter/flutter#30148]
is there any way to apply circular border radius to one side?

**Comment by tomalabaster** [comment]
Could you do something like:

`borderRadius: BorderRadius.only(topLeft: Radius.circular(16.0), bottomLeft: Radius.circular(16.0)))`

Obviously this assumes you know the height of your widget. If you're not setting a constant, could you use a `LayoutBuilder` widget to get the height constraint, and then set the `Radius.circular`s to be half of the `maxHeight` constraint you get?

**Comment by VladyslavBondarenko** [comment]
Closing since solved
