### ISSUE TITLE
[firebase-crashlytics] Crashes hide exception information and have no stack trace

### ISSUE THREAD

**Issue by anaisbetts** [flutter/flutter#30147]
## Steps to Reproduce

1. Set up firebase_crashlytics
2. Crash the app
3. Go to the console

Crashes appear, but they are pretty anemic:

![image](https://user-images.githubusercontent.com/1396/55200864-8b0d8300-51c0-11e9-8b5d-83bb73428d3f.png)

![image](https://user-images.githubusercontent.com/1396/55200870-9365be00-51c0-11e9-9967-8be61f701c1b.png)

Logs also don't actually show up, despite `
    Crashlytics.instance.log(message);` being called:

![image](https://user-images.githubusercontent.com/1396/55200888-b2645000-51c0-11e9-94f1-6fa5f0675a1c.png)

**Comment by mockturtl** [comment]
related: exception details #31370, logs #30591

**Comment by kroikie** [comment]
@anaisbetts

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1151. Any further collaboration will be done there.
