### ISSUE TITLE
VerticalAlign is needed to align Text

### ISSUE THREAD

**Issue by fantasy525** [flutter/flutter#30159]
```javascript
child: RichText(
                text: TextSpan(
                  style: TextStyle(fontSize: 24, color: Colors.black),
                  children: [
                    TextSpan(text: 'hello'),
                    TextSpan(
                        text: 'Jack',
                        style: TextStyle(fontSize: 40, color: Colors.white)),
                    TextSpan(text: ' doctor'),
                  ]),
          ),
```
![image](https://user-images.githubusercontent.com/22516157/55208459-43ffac00-5219-11e9-82d4-ae8829ebb8e8.png)
and I want 'hello' and 'doctor' align 'Jack' vertical center,like this:
![image](https://user-images.githubusercontent.com/22516157/55208719-3696f180-521a-11e9-8da1-ed519f0a33e0.png)

**Comment by TomLiu-GitHub** [comment]
child: Row(
                        children: <Widget>[
                          Text(
                            'hello',
                            style: TextStyle(fontSize: 24, color: Colors.black),
                          ),
                          Text('Jack',
                              style:
                                  TextStyle(fontSize: 40, color: Colors.white)),
                          Text(
                            ' doctor',
                            style: TextStyle(fontSize: 24, color: Colors.black),
                          ),
                        ],
                      )

**Comment by fantasy525** [comment]
@TomLiu-GitHub hello,This is fine, but it does not inherit from the TextSpan property,In my case my hello and doctor both inherited their parent TextSpan style,So I don't have to write it again.you can see you've written twice again，Of course, we can also save common properties in advance with a variable，But wouldn't it be nice to inherit a TextSpan property?

**Comment by racknoris** [comment]
@HansMuller Is this a feasible feature for the flutter team?

**Comment by GaryQian** [comment]
We have very recently introduced the ability to inline arbitrary widgets within text. See `WidgetSpan`.
You could try something like:
```
TextSpan(
  style: TextStyle(fontSize: 24, color: Colors.black),
  children: [
    TextSpan(text: 'hello'),
    WidgetSpan(
      child: Text(
        'Jack',
        alignment: ui.PlaceholderAlignment.middle,
        style: TextStyle(fontSize: 40, color: Colors.white)
      ),
    ),
    TextSpan(text: ' doctor'),
  ]
),
```

**Comment by HansMuller** [comment]
I'm going to close this for now, based on https://github.com/flutter/flutter/issues/30159#issuecomment-502875830

If the WidgetSpan feature doesn't address your issue, please reopen. Thanks for the feedback!

**Comment by stegrams** [comment]
Unfortunately for now, WidgetSpan does not play well with DartPad. 
See: dart-lang/dart-pad/issues/1537

**Comment by TheKashe** [comment]
I don't think widgetspan is a proper solution for fine-tuning text vertical positioning. [This article](https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align) explains the complexities behind it.

Widgetspan does not support text-top vertical alignment, which depends on font's ascent/descent, as this information is not available to widgetspan.

A solution on TextSpan itself is needed to support use-cases which require fine-tuning on par at least with css capabilities.
