### ISSUE TITLE
Use Android AlarmManager plugins in another file

### ISSUE THREAD

**Issue by pranatayudha** [flutter/flutter#30158]
I've tried Android AlarmManager plugin with StatefulWidget state. Can I use the Android AlarmManager plugins in another state? Because in the example, he use 'main.dart' file and where he use the StatelessWidget too. Somebody can help me or maybe have the same problem?

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.
