### ISSUE TITLE
how to convert FlutterStandardTypedData to [UInt8],help me

### ISSUE THREAD

**Issue by baoolong** [flutter/flutter#30154]
I am an Android developer, I don't know how to write a swift program.help me
I sent the uint8list data to the ios.
In the ios project, how to convert FlutterStandardTypedData to [UInt8], I use the swift language
and how convert [UInt8] to uint8list

**Comment by CaptainHtetAung** [comment]
Hi
Did you solve?
If it does, please kindly share

**Comment by csabag** [comment]
if I'm not mistaken this might be one way... (I'm no swift programmer either but had to do something similar just now)

`let myFlutterData: FlutterStandardTypedData = call.arguments as! FlutterStandardTypedData`
`let myData = Data(myFlutterData.data)`
`let myUInt8bytes: [UInt8] = myData.toArray(type: UInt8.self)`
