### ISSUE TITLE
Flutters app name in launcher and name in recent apps tray is different

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#30161]
![Android Emulator - Pixel_2_XL_API_27_5554 29-03-2019 11_03_44](https://user-images.githubusercontent.com/31410839/55211552-7c4fbc00-5212-11e9-8998-11aebedd9b80.png)
heres my app in launcher
and in the recent apps the name is different 

![Android Emulator - Pixel_2_XL_API_27_5554 29-03-2019 11_05_39](https://user-images.githubusercontent.com/31410839/55211588-b456ff00-5212-11e9-9b4a-c01bb46152dd.png)

How do I change it to app name

**Comment by tomalabaster** [comment]
You change the `title` property on your `MaterialApp` widget. See this answer here: [https://stackoverflow.com/questions/50615006/where-does-the-title-of-material-app-used-in-flutter](https://stackoverflow.com/questions/50615006/where-does-the-title-of-material-app-used-in-flutter)

**Comment by maheshmnj** [comment]
> You change the `title` property on your `MaterialApp` widget. See this answer here: https://stackoverflow.com/questions/50615006/where-does-the-title-of-material-app-used-in-flutter

thanks this perfetly answers my question I am closing the issue

**Comment by patelkrunal78** [comment]
The Flutter documentation points out where you can change the display name of your application for both Android and iOS. This may be what you are looking for:

Preparing an Android App for Release
Preparing an iOS App for Release
For Android

It seems you have already found this in the AndroidManifest.xml as the application entry.

Review the default App Manifest file AndroidManifest.xml located in /android/app/src/main/ and verify the values are correct, especially:

application: Edit the application tag to reflect the final name of the app.

Find More Here
