### ISSUE TITLE
how to set Video resolution

### ISSUE THREAD

**Issue by CatEatFishs** [flutter/flutter#30169]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by CatEatFishs** [comment]
I using video_player: ^0.10.0+4  plugin  ,how to set resolution when I shooting ?

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.
