### ISSUE TITLE
In the Flutter and iOS Mixed Project crash （Flutter和iOS混编崩溃）

### ISSUE THREAD

**Issue by DongyangLiu** [flutter/flutter#30167]
In the Flutter and iOS Mixed Project
Initialize flutter and call iOS native camera crash
IPhone 6-iOS 12 or more)
Flutter 1.2.1
（在Flutter和iOS混编项目中
初始化flutter后调用iOS原生相机崩溃
iPhone 6-iOS12以上）
Flutter 1.2.1 ）

**Comment by xster** [comment]
Unfortunately this issue isn't very actionable. Can you show us the output of `flutter doctor -v`, the crash output and a sample project that can reproduce this issue?
