### ISSUE TITLE
Does Flutter support Dygraph chart library?

### ISSUE THREAD

**Issue by chinmay-ksolves** [flutter/flutter#30168]
Dygraphs is a fast, flexible open source JavaScript charting library.
It allows users to explore and interpret dense data sets.
I found https://pub.dartlang.org/packages/charts_flutter but this does not support graphs like Dygraphs.

Currently, my application is in ionic and I want to migrate an ionic application to Flutter but I have used Dygraph library for large datasets points charts and I do not get any kind of library in Flutter which supports heavy datasets for charts.

**Comment by thedejifab** [comment]
https://github.com/mtcliatt/Flarts/ gives you similar feel in Flutter  @chinmay-ksolves

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.
