### ISSUE TITLE
Questions about the DropdownButton component API

### ISSUE THREAD

**Issue by futureyang** [flutter/flutter#30175]
A horizontal line below this component, with no properties or methods to remove

![image](https://user-images.githubusercontent.com/49013693/55219526-1712bf80-5240-11e9-90e0-84dd98afae23.png)

this.items,
this.value,
this.hint,
this.disabledHint,
this.onChanged,
this.elevation,
this.style,
this.iconSize,
this.isDense,
this.isExpanded,

It's causing me problems

**Comment by HansMuller** [comment]
https://docs.flutter.io/flutter/material/DropdownButtonHideUnderline-class.html
