### ISSUE TITLE
HttpClient.findProxyFromEnvironment does not work correctly on MacOS

### ISSUE THREAD

**Issue by gabidusa** [flutter/flutter#30170]
Hello,

I am developing a Flutter application on MacOS.
I am trying to capture the HTTP traffic for the Flutter application using Charles proxy on the Simulator (device as well, but let's keep it simple).
I  noticed that the traffic is not visible.
I tried to set the proxy settings for my custom HttpClient object to detect the environment proxy like this:
`myHttpClient.findProxy = HttpClient.findProxyFromEnvironment;`
I have also set my environment `http_proxy` and `https_proxy` variables to my Charles local IP.

However, this has no effect on the application.
The HTTP traffic is still not visible.

Thanks!

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.
