### ISSUE TITLE
Cloud Firestore 0.9.7 stucks at Installing BoringSSL-GRPC (0.0.2) during pod install

### ISSUE THREAD

**Issue by iampawan** [flutter/flutter#30185]
![Screenshot 2019-03-29 at 4 40 48 PM](https://user-images.githubusercontent.com/12619420/55228967-a371b200-5241-11e9-94b0-01007d111b11.png)

Tried downgrading the version but didn't work. I am using the latest Xcode and IOS version.
Help @shihaohong @Hixie @jonahwilliams @pepegich

**Comment by dmvvilela** [comment]
Did you managed to fix this  @iampawan  ?

**Comment by iampawan** [comment]
Yes, somehow it got fixed @dmvvilela

**Comment by muhammadzumair** [comment]
@iampawan how did you fix it

**Comment by dmvvilela** [comment]
@muhammadzumair i got it to work too.. some problem with cocoa pods.. had to clean, make some pod update, change cocoapods version and tested a lot of stuff.. and it took a while but now it works again.

**Comment by jafar-albadarneh** [comment]
I've updated the cocoapods in order to fix the issue.
`sudo gem install cocoapods`

**Comment by Balajiks-alt** [comment]
Hey guys, how did you fix this issue? I'm struggling here.  @dmvvilela  @iampawan

**Comment by Chizinski** [comment]
@dmvvilela Kindly outline how you solved the issue?

**Comment by jessalbarian** [comment]
This worked for me, and I'm on Catalina

`brew install ruby`
`sudo gem install -n /usr/local/bin cocoapods`
`pod install`

**Comment by MobileMon** [comment]
I was having the issue too. After upgrading cocoapods, flutter, and my pubspec to the latest versions, I thought the problem was still occurring. Turns out I just had to be patient and let BoringSSL install


**To upgrade cocoapods:**
`sudo gem install cocoapods`

**To upgrade flutter**
`flutter upgrade`

**Comment by nifrasismail** [comment]
seems it is because of the spec download from the repo, you may do it manually and notice it. 

`cd ~/.cocoapods/repos`

`git clone --depth 1 https://github.com/CocoaPods/Specs.git master`

you may notice the size of the repo is approximately 800MB

after this `pod install` is not slow

**Comment by ch-muhammad-adil** [comment]
Let it install for a while, Actually it takes some time like 10-15 minutes.

**Comment by YuyaAbo** [comment]
I was able to install too. In fact, it took a few tens of minutes.

**Comment by ap1ter** [comment]
it took around 30 minutes
