### ISSUE TITLE
Add a Flutter Widget in native iOS App inside an UIView

### ISSUE THREAD

**Issue by pisa97** [flutter/flutter#30183]
I found out that there is the possibility to add a flutter widget inside my native App iOS, but also that the Flutter framework allow me only to create a new View controller to present, as showed into this snippet:

```
let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine;
        let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)!;
        flutterViewController.setInitialRoute("route1")
        self.present(flutterViewController, animated: false, completion: nil)
```

So my question is: Is there the possibility to create a FlutterView and not only the restrictive FlutterViewController?

Thank you so much, Arcangelo

**Comment by xster** [comment]
cc @dnfield

Do we need more docs around this?

**Comment by dnfield** [comment]
It is not currently possible have just a UIView for a Flutter widget.

Can you speak a bit more about what you're trying to do and why you want to avoid using a ViewController?

@xster - I'm not sure what more we'd document here - the current documentation specifies how to use the add2app stuff.  If this really is a FAQ it's worth adding but I don't know if we're getting that request all that much.

**Comment by pisa97** [comment]
@xster @dnfield At first I have tried to include ad UiView native iOS in flutter to allow me to include banner in any place into the screen (that is not possible to do at the moment with AdMob in flutter). This causes the app crash and the lost of gestures and any other problems (I have opened an issue for this). As second test I have tried to create a native App iOS and after to include Flutter widget for the equal parts of the native apps in Android and iOS but it seems that It is not possible at the moment. How can I solve that? My only problem is to add AdMob banner into the flutter App. Thank you!

**Comment by xster** [comment]
I don't have anything too specific. If Android is going to support adding a FlutterView as entries in a table, it would be nice to describe what that looks like with custom UITableViewCells and Flutter inside it, whether as UIViews or UIViewControllers.

**Comment by ahusseini** [comment]
With native magic, anything is possible:

```swift
guard let flutterEngine = (UIApplication.shared.delegate as? AppDelegate)?.flutterEngine,
  let flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil) else {
    return nil
}

addChild(flutterViewController)
flutterViewController.view.translatesAutoresizingMaskIntoConstraints = false

guard let flutterView = flutterViewController.view else { return }

addSubview(flutterView)
flutterView.translatesAutoresizingMaskIntoConstraints = false
flutterView.topAnchor.constraint(equalTo: topAnchor).isActive = true
flutterView.leadingAnchor.constraint(equalTo: leadingAnchor).isActive = true
flutterView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
flutterView.trailingAnchor.constraint(equalTo: trailingAnchor).isActive = true

flutterViewController.didMove(toParent: self)
flutterView.layoutIfNeeded()
```

**Comment by MithunMadhav1112** [comment]
@ahusseini  Have you been able to use the above approach successfully.. My Idea is to develop several small components as flutter widgets and then use them across projects as reusable subviews

**Comment by ahusseini** [comment]
Hey @MithunMadhav1112, I haven't tried this for multiple flutter components, but that use case is on the horizon for us. This method works for us with one component, but I'd wager that we would need to spin up multiple engines for multiple components on screen. I'm not entirely sure though.

**Comment by lyc2345** [comment]
May I ask why this issue been closed? Is any solution or no can do?

**Comment by Gnanendra18** [comment]
> @ahusseini Have you been able to use the above approach successfully? My Idea is to develop several small components as flutter widgets and then use them across projects as reusable subviews

Hi Mithun, My idea is also similar to your approach, How far have you progressed in this regard. Did you able to spin multiple engines and reuse them across the widgets?

**Comment by oscardelgado** [comment]
Thanks, @ahusseini !
