### ISSUE TITLE
How to add new localization language that don't supported by GloabalMaterialLocalizationDelegate, GloabalWidgetsLocalizationDelegate?

### ISSUE THREAD

**Issue by kazbeksultanov** [flutter/flutter#30187]
Currently, I'm working on the localization of an app. I want to add the Kazakh language that currently not supported by GLobalMaterializationLocaliztionDelegate. I've read official documentation on how to add new language but actually, I don't understand the method.

If anybody could write step by step manual how to add, it will help me (and I think a lot of others) so much.

**Comment by alevinetx** [comment]
I came searching the issues for this same problem.  We have several languages that are not currently in the supported list.  I read through the API docs, and have a hard time making sense of them.  I feel being terse was chosen at the sacrifice of losing some concepts.  The documentation could definitely use a revisit.

doc:  https://api.flutter.dev/flutter/material/MaterialApp/localizationsDelegates.html

As an example, this single sentence crosses several concepts and leaves the, admittedly new-ish to Flutter, reader quite confused. 

> Constructing a MaterialApp with a FooLocalizationsDelegate overrides the automatically included 
> delegate for MaterialLocalizations because only the first delegate of each LocalizationsDelegate.type is 
> used and the automatically included delegates are added to the end of the app's 
> localizationsDelegates list.


I did find this issue:  https://github.com/flutter/flutter/issues/19165

Which leads to this: 
https://flutter.dev/docs/development/accessibility-and-localization/internationalization#an-alternative-class-for-the-apps-localized-resources

Which steps you through the exercise of implementing for Belarus, and has some sample code:
https://github.com/flutter/website/blob/master/examples/internationalization/add_language/lib/main.dart

Perhaps after reading through these additional sections some of this may make more sense, but the core documentation itself still needs some attention.

**Comment by HansMuller** [comment]
Kazakh (language code 'kk') is now supported, see https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

We've also updated the docs to explain how to add app-specific support for a new language: https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html

**Comment by kazbeksultanov** [comment]
Thanks a lot. The flutter team is really great!
