### ISSUE TITLE
Size of flutter runtime on device's

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#30184]
My built aps have a large libflutter compared to flutter catalog on my device.

Application: 	Flutter Catalog
Link: 	http://play.google.com/store/apps/details?id=io.github.x_wei.flutter_catalog

Type: 	arm libs
Version Code: 	31
Version Name: 	1.5.3
Apk Location: 	/data/app/io.github.x_wei.flutter_catalog-6PWiFbzeS6vUVnCOx1RtFg==/base.apk

Installed libraries:
armv7	8.0 MiB	libclassifier_jni.so		, dependencies: 	libandroid.so, libjnigraphics.so, liblog.so, libm.so, libdl.so, libz.so, libc.so
armv7	4.8 MiB	libflutter.so		, dependencies: 	libandroid.so, libEGL.so, libGLESv2.so, libc.so, libdl.so, libm.so, liblog.so

Libraries inside APK:
armv7	8.0 MiB	lib/armeabi-v7a/libclassifier_jni.so		, dependencies: 	libandroid.so, libjnigraphics.so, liblog.so, libm.so, libdl.so, libz.so, libc.so
armv7	4.8 MiB	lib/armeabi-v7a/libflutter.so		, dependencies: 	libandroid.so, libEGL.so, libGLESv2.so, libc.so, libdl.so, libm.so, liblog.so
x86	8.3 MiB	lib/x86/libclassifier_jni.so		, dependencies: 	libandroid.so, libjnigraphics.so, liblog.so, libm.so, libdl.so, libz.so, libc.so

Mine:

Application: 	example
Link: 	http://play.google.com/store/apps/details?id=com.zefyr.example

Type: 	arm64 libs
Version Code: 	1
Version Name: 	1.0.0
Apk Location: 	/data/app/com.zefyr.example-VsBk3liCiNwJaH38LQwQ7w==/base.apk

Installed libraries:
arm64	21.3 MiB	libflutter.so		, dependencies: 	libandroid.so, libEGL.so, libGLESv2.so, libc.so, libdl.so, libm.so, liblog.so

Libraries inside APK:
arm64	21.3 MiB	lib/arm64-v8a/libflutter.so		, dependencies: 	libandroid.so, libEGL.so, libGLESv2.so, libc.so, libdl.so, libm.so, liblog.so
x86_64	22.5 MiB	lib/x86_64/libflutter.so		, dependencies: 	libandroid.so, libEGL.so, libGLESv2.so, libc.so, libdl.so, libm.so, liblog.so
x86	21.4 MiB	lib/x86/libflutter.so		, dependencies: 	libandroid.so, libEGL.so, libGLESv2.so, libc.so, libdl.so, libm.so, liblog.so

Suggested things going on ?

**Comment by tomalabaster** [comment]
Are you using `flutter build apk`?

**Comment by gedw99** [comment]
@tomalabaster yes.

I guess i am wondering about bundling for OS and ARCH to reduce the size of the runtime thats deployed. That miht be for later.
Right now i am wondering how on earth Google gets their binaries so small.

**Comment by darshankawar** [comment]
The github user (@ghost) who opened this issue doesn't seem to exist anymore, so not sure if this issue is still valid or not using latest version, since this issue was opened almost 2 years ago.

We are reluctantly going ahead and closing this issue. If the issue author comes back and claims this issue is still valid, write in comments and I'll reopen it.
