### ISSUE TITLE
Google Drive /Dropbox/iCloud drive picker with flutter

### ISSUE THREAD

**Issue by premtemp1** [flutter/flutter#30189]
Hello,
  We are planning to migrate to Flutter. However, We have a use case where users should be able to select a file from google drive or dropbox. The file should then be return to the app . We  will then read the content of the file and do some processing.

Is there a example where on  button click we could launch google/dropbox /iCloud picker and and do the above flow,

Thanks

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

does file_picker plugin not work? https://pub.dev/packages/file_picker

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
