### ISSUE TITLE
How can i prevent that scroll offset be bigger than view content (NestedScrollView and TabBarView)?

### ISSUE THREAD

**Issue by lubritto** [flutter/flutter#30192]
I'm using slivers to get an animated page with a header collapsable and a TabView body, but the offset of scroll is considering the fully page. What i need to do to get the right offset ? I'm putting an example about what happens.

I'm using flutter 1.2.1

```
    NestedScrollView(
      controller: _scrollController,
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
        return [
          SliverAppBar(
            pinned: true,
            backgroundColor: greenColor.withOpacity(0.6),
            flexibleSpace: FlexibleSpaceBar(
              collapseMode: CollapseMode.pin,
              background: _buildHeader(context),
            ),
            expandedHeight: 300.0,
            bottom: _buildTabBar(),
          )
        ];
      },
      body: _buildTabView(context),
    )
```

I expect the offset stops when the header stops of being collapsed

![ezgif com-optimize](https://user-images.githubusercontent.com/14953997/55241054-0d299600-5219-11e9-8443-76c13037aecd.gif)

**Comment by Piinks** [comment]
Hi @lubritto, have you considered using a `SliverOverlapAbsorber` to correct the offset?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
