### ISSUE TITLE
When there's no text in an input widget, the cursor is tiny and in the wrong place

### ISSUE THREAD

**Issue by IvBaranov** [flutter/flutter#302]
RenderEditableParagraph width looks as if it was: 
`'parent_width' + _kCursorGap + _kCursorWidth`
but not `textPainter.size.width + _kCursorGap + _kCursorWidth`

EditableTextWidget becomes horizontally scrollable:
![1](https://cloud.githubusercontent.com/assets/6000572/11090486/5ee79888-8883-11e5-9a87-37a3cf5ed844.png)

Line break looks like:
![2](https://cloud.githubusercontent.com/assets/6000572/11090490/63331a16-8883-11e5-8bce-b4595861e422.png)

But comments say:
// Editable text does not support line wrap.
  bool get allowLineWrap => false;

**Comment by abarth** [comment]
I think I fixed this issue in https://github.com/flutter/flutter/commit/64a645352c80246bcba2bb7d242e05cbf312e419 .  Do you still see the issue after that revision?

**Comment by IvBaranov** [comment]
Right now I see:
![3](https://cloud.githubusercontent.com/assets/6000572/11114544/8b55549c-8936-11e5-8c1b-e059edeccf2c.png)
The cursor is above the hint and there is no way to show keyboard.

P.S. It may be that this issue is caused by dependency error like this one #329. So I just wanted to ask for some tip about proper _local environment updating_.

**Comment by abarth** [comment]
> The cursor is above the hint and there is no way to show keyboard.

Yes, I've seen that issue too.  Will fix.

> Just pub upgrade every time?

I recommend the following workflow:

1. Follow the instructions on http://flutter.io/getting-started/ .  In particular, clone the flutter.git repository, refer to the flutter package in your pubspec.yaml using a relative path, and use the `flutter` command from flutter.git's `bin`.
2. To update:
 - Run `git pull --ff-only` in your clone of flutter.git.
 - Run `pub upgrade` in the same directory as your pubspec.yaml.
3. To run your app:
 - Run `flutter start` in the same directory as your pubspec.yaml.

**Comment by IvBaranov** [comment]
Thank you for clarifying.

**Comment by abarth** [comment]
I've added `flutter upgrade`, which does the work from step 2.

**Comment by abarth** [comment]
Looking at the cursor bug now.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/363
