### ISSUE TITLE
Severe: RoutObserver does not work for iOS swipe gesture. 

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#30200]
I was very surprised to find out, that there is no way to address the iOS 'swipe back gesture' (in Flutter at all), which I assume 95% of iOS user use. Overall, I know of just not a single way in flutter to overwrite or observe the iOS swipe back gesture (besides WillPopScope to simply block it).

So for instance, `didPop()` of RouteObserver is not working (only triggered via back button) so how should I be able to e.g. save a value to a database, if a user pops a route via iOS swipe back (e.g. for unread messages -> timestamp saving or saving of data via back swipe etc.).

How should I be even able to push another route to a swipe back gesture?

This issue is so severe, I would highly suggest that it is implemented asap.

**Comment by msw333** [comment]
Related:
https://github.com/flutter/flutter/issues/29596

**Comment by xster** [comment]
Let's merge into #29596 since it's the same issue.
