### ISSUE TITLE
WidgetTester should be available in integration tests

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#30214]
Flutter app and plugin authors need an API for reliable integration tests that works on unmodified Flutter apps and runs on Firebase Test Lab. We propose to extend the WidgetTester API to include synchronized actions and assertions, which are presently only available in FlutterDriver.

Right now we're using in a `pumpWidget` helper in Google Maps and webview. See flutter/plugins#1420 and flutter/plugins#1409

**Comment by collinjackson** [comment]
Here's an initial API proposal for WidgetTester synchronization: flutter.dev/go/synchronized-widgettester

Feedback welcome.

/cc @liyuqian

**Comment by nilsreichardt** [comment]
@darshankawar Isn't this already possible with the `integration_test` package?

**Comment by darshankawar** [comment]
That is correct. Thanks for notifying @nilsreichardt.
The new `integration_test` package uses `widget_tester` api to write integration tests and all properties and methods of widget tester are available in the package.

I am going ahead and closing this as fixed. If anyone disagrees, please write in comments and I'll reopen it.
