### ISSUE TITLE
Got 'Source error' message while playing a youtube video link with youtube_player plugin

### ISSUE THREAD

**Issue by goldenhuang** [flutter/flutter#30221]
## Steps to Reproduce

1. Please check my attached main.dart file.
2. The build method will return a widget containing a YoutubePlayer with the specific source 
 '8NRQwj3i5y4'
3. Launch the app to the device for playing the video stream and get 'Source error.' as the Logs below. The video cannot be played but with Thumbnail displayed on the screen.
Note: 
   I use the same code to play other youtube video stream links and they work well. 
   I have no idea of what the youtube video stream happens!! 
   I use the same link and can play it in my chrome browser on computer and android phone. 

Any clues about this issue?

## Logs

The Logs after running 'flutter run --verbose' : 

[  +58 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x72475a1218, isolate: {type: @Isolate, fixedId: true, id: isolates/623449983,
name: main.dart$main-623449983, number: 623449983}}]}
[   +2 ms] Connected to _flutterView/0x72475a1218.
[   +6 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[  +74 ms] An Observatory debugger and profiler on LG H830 is available at: http://127.0.0.1:51162/
[   +1 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+2169 ms] E/ExoPlayerImplInternal( 3060): Source error.
[  +26 ms] E/ExoPlayerImplInternal( 3060): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
[   +1 ms] E/ExoPlayerImplInternal( 3060):      at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
[        ] E/ExoPlayerImplInternal( 3060):      at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
[   +1 ms] E/ExoPlayerImplInternal( 3060):      at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
[   +1 ms] E/ExoPlayerImplInternal( 3060):      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
[   +1 ms] E/ExoPlayerImplInternal( 3060):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[   +1 ms] E/ExoPlayerImplInternal( 3060):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[   +2 ms] E/ExoPlayerImplInternal( 3060):      at java.lang.Thread.run(Thread.java:764)

The Logs after running 'flutter analyze' : 

Nothing wrong.

The Logs after running 'flutter doctor -v' : 

[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.18356.16], locale zh-TW)
    • Flutter version 1.3.8 at C:\Projects\Flutter\flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Golden\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Golden\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4892.25

[√] VS Code
    • VS Code at C:\Users\Golden\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • LG H830 • LGH830b443707e • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

[main.zip](https://github.com/flutter/flutter/files/3024706/main.zip)

**Comment by goldenhuang** [comment]
The same youtube link url can work without 'Source error' when flutter_youtube plugin is used instead of youtube_player plugin! Any help on this issue of 'Source error' when youtube_player is used.

**Comment by chaicai333** [comment]
i have this error also !

**Comment by DennisPeqas** [comment]
same hereee !! help

**Comment by escamoteur** [comment]
Hi, this isn't a google plugin, so we can't help you there.

**Comment by verma-arun** [comment]
i have used all flutter youtube player but not able to play video on it, when i'm trying to play video in different youtube player it is showing me following errors
*Youtube player flutter :> error code 150 ( The owner of the requested video may not allow it to be played)
* Youtube player :> error is Java's FIleNotFoundExeption null error when its trying to decode the videoId from video url

**Comment by JahanzebNawaz** [comment]
Same Error, any help, working from last 4 days on an app i need it on urgent basis but at the end when i played on a real devices it show me error.

> Error Code : 150
 the owner of the requested video may not allow it to be played.

any alternative to play youtube videos. 
Thanks
