### ISSUE TITLE
Flutter Firestore code contains errors and fails to compile

### ISSUE THREAD

**Issue by brian-dunn** [flutter/flutter#30230]
When trying to run an app with the latest version of this plugin, the Flutter compiler reports the following error:

`C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.1+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.`

The Android emulator fails to run the app and reports a force close crash.

**Comment by kroikie** [comment]
@brian-dunn

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1238. Any further collaboration will be done there.
