### ISSUE TITLE
Flutter Doc Website Samples are broken

### ISSUE THREAD

**Issue by Kartik1607** [flutter/flutter#30243]
Tested on IconButton page. In chrome, clicking on tab of one sample changes tab of some other sample. In edge, the sample is not rendered.

https://www.youtube.com/watch?v=IdKhHmUbj54&feature=youtu.be

https://www.youtube.com/watch?v=bD7mhvx1lXY&feature=youtu.be

**Comment by escamoteur** [comment]
Hi, could you please check if this is still an issue? Thanks to bring this to our attention.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
