### ISSUE TITLE
Route '/' it's ever called as initialRoute

### ISSUE THREAD

**Issue by panthe** [flutter/flutter#30242]
If you have a situation like this:
```
  initialRoute: '/SplashScreen',
  navigatorKey: Keys.navKey,
  routes: <String, WidgetBuilder>{
  '/': (BuildContext context) => HomePageUI(),
  '/SplashScreen': (BuildContext context) => SplashScreenUI(),
```

the home page it's ever called as initialRoute with the page that you set as initialRoute.

If you change the name of Home Page route from '/' to '/Home' for example this doesn't happens anymore.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
