### ISSUE TITLE
The method '>' was called on null, in release mode

### ISSUE THREAD

**Issue by Nepali-San** [flutter/flutter#30247]
## Steps to Reproduce

1. close and reopen the app

## Logs

To quit, press "q".
I/flutter (15173): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15173): The following NoSuchMethodError was thrown building Builder(dirty):
I/flutter (15173): The method '>' was called on null.
I/flutter (15173): Receiver: null
I/flutter (15173): Tried calling: >()
I/flutter (15173): 
I/flutter (15173): When the exception was thrown, this was the stack:
I/flutter (15173): #0      _NestedScrollCoordinator.get:hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:501)
I/flutter (15173): #1      _NestedScrollViewState.build.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:344)
I/flutter (15173): #2      Builder.build (package:flutter/src/widgets/basic.dart:6035)
I/flutter (15173): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789)
I/flutter (15173): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736)
I/flutter (15173): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559)
I/flutter (15173): #6      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796)
I/flutter (15173): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2748)
I/flutter (15173): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747)
I/flutter (15173): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3559)
I/flutter (15173): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006)
I/flutter (15173): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2748)
I/flutter (15173): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747)
I/flutter (15173): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3559)
I/flutter (15173): #14     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894)
I/flutter (15173): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2748)
I/flutter (15173): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747)
I/flutter (15173): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3559)
I/flutter (15173): #18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273)
I/flutter (15173): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700)
I/flutter (15173): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268)
I/flutter (15173): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988)
I/flutter (15173): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928)
I/flutter (15173): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749)
I/flutter (15173): #32     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
I/flutter (15173): #33     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
I/flutter (15173): #34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
I/flutter (15173): (elided 8 frames from package dart:async)
I/flutter (15173): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

```
```

**Comment by tomalabaster** [comment]
Can you provide the minimum code required to repeat the error, and also the output of running `flutter doctor -v`, please?

**Comment by Nepali-San** [comment]
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/san/Documents/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/san/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/san/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/san/Downloads/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • SM G610F • 52107d5a5357c4c9 • android-arm • Android 8.1.0 (API 27)

• No issues found!

**Comment by Nepali-San** [comment]
This is what my original app intending to do.
***Main page***
-------------------------------------------------------------------------------------------------------
import 'package:debug/homepage.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Debug"),
        ),
        body: HomePage(),
      ),
    );
  }
}
-------------------------------------------------------------------------------------------------------

***Homepage***
---------------------------------------------------------------------------------------------------------------------
import 'package:flutter/material.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List<String> name = [
    'cat',
    'man',
    'sun',
    'sum',
    'more',
    'string',
    'cat',
    'man',
    'sun',
    'sum',
    'more',
    'string',
  ];

  Widget _buildimage() {
    return Container(
      height: 150,
      width: MediaQuery.of(context).size.width,
      decoration: BoxDecoration(border: Border.all(width: 1)),
      child: Image.asset(
        'images/titleimage.jpg',
        fit: BoxFit.fill,
      ),
    );
  }

  Widget _buildText() {
    return Container(
      child: Text(
        'Our Categories',
        style: TextStyle(
          fontWeight: FontWeight.bold,
          color: Colors.black,
        ),
      ),
    );
  }

  Widget horizontalList() {
    return ListView.builder(
      scrollDirection: Axis.horizontal,
      itemBuilder: (context, index) => Card(
            child: Container(
              child: Text(
                name[index],
                style: TextStyle(fontSize: 30),
              ),
            ),
          ),
      itemCount: name.length,
    );
  }

  Widget gridList() {
    return GridView.builder(
      gridDelegate:
          SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
      itemBuilder: (context, index) {
        return Container(
          child: Text(
            name[index],
            style: TextStyle(fontSize: 30),
          ),
        );
      },
      itemCount: name.length,
    );
  }

  @override
  Widget build(BuildContext context) {
    return NestedScrollView(
      headerSliverBuilder: (context, isScrolled) {
        return <Widget>[
          SliverList(
            delegate: SliverChildListDelegate([
              _buildimage(),
              _buildText(),
            ]),
          ),
          SliverToBoxAdapter(
            child: Container(
              height: 50.0,
              child: horizontalList(),
            ),
          ),
          SliverAppBar(
            title: Text(
              'Silver app bar',
              style: TextStyle(fontSize: 15, color: Colors.black),
              textAlign: TextAlign.center,
            ),
            backgroundColor: Colors.grey[200],
            pinned: true,
          ),
        ];
      },
      body: gridList(),
    );
  }
}
------------------------------------------------------------------------------------------------------------------------------

**Comment by Nepali-San** [comment]
Error may or may not show on the app screen, but it will definitely show in your terminal.
Issue is in body property with gridList() , otherwise it is working as expected.

**Comment by Nepali-San** [comment]
Update : I solved the problem using CustomScrollView instead of NestedScrollView.

**Comment by x4080** [comment]
Hi @Nepali-San , I had the same issue and don't know whats wrong but in nested_scroll_view.dart (flutter sdk), position.minScrollExtent can be null sometime, so my solution is patch this
 
'''
  bool get hasScrolledBody {
    for (_NestedScrollPosition position in _innerPositions) {
      if (position.minScrollExtent==null) return true; // patch
'''
