### ISSUE TITLE
ChildView flickers upon resize

### ISSUE THREAD

**Issue by tonygentilcore** [flutter/flutter#3024]
## Steps to Reproduce

Create a ChildView and resize it. Notice that it flickers during the resize.

/cc @abarth @j9brown

**Comment by abarth** [comment]
@j9brown This is the issue I wanted to talk with you about yesterday.

**Comment by abarth** [comment]
Current short-term plan is to switch to janking instead of flickering.  Long-term plan is to improve Mozart.

**Comment by j9brown** [comment]
Yup.  Soon as I can sit down to write code.  It's nontrivial.  My first
attempt at this didn't work out.
