### ISSUE TITLE
Any plans to add support for receiving text/images/files (and sending images/files) in the official share plugin?

### ISSUE THREAD

**Issue by exts** [flutter/flutter#30245]
I don't know much about IOS, but on android from any app you can send files/images and text to other apps using the send intent which [the current plugin](https://pub.dartlang.org/packages/share) does iirc (at least for text, no image/files seem to be possible yet?), but there's no way to receive incoming intent data with said plugin.

I've come across a [3rd party plugin](https://github.com/d-silveira/flutter-share), but I think it would be useful to have this functionality in the main plugin as well. That author hasn't updated that repo in almost a year and it looks like the ios portion is incomplete and currently abandoned (issues piling up)

**Comment by maskaravivek** [comment]
I am also looking for similar functionality. It would be great if someone can comment about future plans regarding this.

**Comment by iapicca** [comment]
HI @exts 
I see there's an open [issue](https://github.com/flutter/flutter/issues/9817) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
