### ISSUE TITLE
TextField label with OutlineInputBorder doesn't match Material design guidelines.

### ISSUE THREAD

**Issue by blazvantur** [flutter/flutter#30249]
```
TextFormField(
    style: const TextStyle(color: Colors.white),
    decoration: InputDecoration(
        labelText: 'Email',
        border: OutlineInputBorder(
            borderSide: BorderSide(
                color: Colors.grey.withAlpha(80), width: 0),
                borderRadius: const BorderRadius.all(
                Radius.circular(8),
    ))),
    validator: (value) {
        if (value.isEmpty) {
            return 'Please enter some text';
        }
    },
)
```

Doesn't we have wrong label positioning on TextFields with OutlineInputBorder? I was working on my app and noticed on the Material design guidelines that the label should be positioned higher as we have it now. Almost as a label is aligned baseline to the top border, but a little lower. Or are there some particular reasons behind that alignment?

Here are some screenshots that were taken from the internet:

Flutter component:
![OutlineInputBorder](https://user-images.githubusercontent.com/20900396/55279255-c9b55180-5316-11e9-9cd9-74b6ca71cf3f.png)

Material design guidelines:
![Material design guidelines](https://user-images.githubusercontent.com/20900396/55279256-c9b55180-5316-11e9-9c55-26ac54aad790.png)

**Comment by justinmc** [comment]
@blazvantur or @filipwin, can you link me to exactly where you're seeing this in the Material spec?

When I look at the [spec for text fields](https://material.io/design/components/text-fields.html#spec), I see something that looks more like what Flutter is doing than the screenshot above.

![Screenshot from 2019-05-01 10-25-44](https://user-images.githubusercontent.com/389558/57031258-192fbb80-6bfc-11e9-8aac-4411c4f7f9b8.png)

![mio-design_assets_1sDssFpR7Lm7le2uI_r17KzCCRQ7ZXCuO_specs-textfields-outlined-active](https://user-images.githubusercontent.com/389558/57031526-ce627380-6bfc-11e9-838b-1a8250958407.png)

**Comment by justinmc** [comment]
I looked over this with some people from the Material team and it seems that the alignment from my comment above is correct.  I'm going to close this since Flutter should be correct to that version of the spec.
