### ISSUE TITLE
Cupertino Icons missing (f413 + f414)

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter#30252]
Hello together 😊 ,

i recognized, that in master and stable branch the icons: 0xf413 and 0xf414 are missing. I added them locally, but I can't branch from master or dev, so i am writing it here:

 /// Three rings overlapped together
  static const IconData rings = IconData(0xf413, fontFamily: iconFont, fontPackage: iconFontPackage);

 /// Three rings overlapped together (filled)
  static const IconData rings_filled = IconData(0xf414, fontFamily: iconFont, fontPackage: iconFontPackage);

Maybe you can add them to icons.dart in: flutter/packages/flutter/lib/src/cupertino/icons.dart

greetings
Rebar

**Comment by matthew-carroll** [comment]
This is a dup of #16102, which tracks the inclusion of all appropriate icons.

**Comment by Ahmadre** [comment]
Thx @matthew-carroll 😊
