### ISSUE TITLE
Cannot debug over Wifi  - Cannot connect to iOS device

### ISSUE THREAD

**Issue by zxl777** [flutter/flutter#30260]
**When connected the USB to iPhone**
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!

**XCODE WIFI DEBUG worked.**
![image](https://user-images.githubusercontent.com/816448/55284236-ee580a80-53a4-11e9-8922-856803a189f2.png)

-----
**When disconnected the USB from iPhone**

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[!] Connected device
    ! No devices available

**And i have run the brew commands for 2 times,No Error **
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller

```
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/sky/Library/Caches/Homebrew/libimobiledevice--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 0584aa9 idevicepair: Fix udid being freed before printing error message containing udid
==> ./autogen.sh
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libimobiledevice/HEAD-0584aa9_3 --without-cython --enable-debug-co
==> make install
```

**Comment by tomalabaster** [comment]
This is already being talked about here: #15072
