### ISSUE TITLE
cant start app on ios 9.x 

### ISSUE THREAD

**Issue by yshuman1** [flutter/flutter#30269]
when i try to run app on ipad iOS 9.x i get the following : https://gist.github.com/yshuman1/0fc58d0d7ae4bcb54ab9106b2af64bab

If I run flutter doctor everything looks fine to me:
```
yasin (master *) pics $ flutter doctor -v
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.8 at /Users/yasin/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by kev52** [comment]
Any updates on this topic - we have the same problem

**Comment by escamoteur** [comment]
Could you both upgrade to latest stable and try also master if the problem still isn't fixed?

**Comment by JoseGeorges8** [comment]
Got 1.10.7 on master. It still happens

**Comment by escamoteur** [comment]
@JoseGeorges8 Which Xcode version are you using and which iOS version has your device?

**Comment by escamoteur** [comment]
Please post all that have this problem their `flutter doctor -v` here.

Can you debug on other iOS versions?

**Comment by iapicca** [comment]
Hi @yshuman1 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
