### ISSUE TITLE
Running On Android Emulator - Unable to read manifest info from

### ISSUE THREAD

**Issue by ueabu** [flutter/flutter#30278]
I am having troubles running my application on an android emulator. I previously only used IOS emulators to develop the application and when I tried testing on Android, I got a ton of errors suggesting I switch to AndroidX which I did everything seemed to work fine. 

When I open the android folder in Android Studio and run the program, everything works well and it runs and installs on the emulator perfectly fine however when I run `flutter run` from the terminal, I get this error. 

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              1.9s
Resolving dependencies...                                           7.4s
Error running com.appname. Manifest versionCode not found
Unable to read manifest info from /Path to APK /build/app/outputs/apk/app.apk.
No application found for TargetPlatform.android_x86.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

I have tried deleting and reinstalling android studio but no luck. I also tried `flutter clean` and running again but still the same problem. 

## Logs
Flutter doctor -v
```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.8 at /Users/umaabu/Documents/Flutter/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/umaabu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by italo2480** [comment]
Conseguiu resolver?

**Comment by jayant07** [comment]
same problem! did you get a solution.

**Comment by escamoteur** [comment]
Hi,

does this still happen on latest stable if you create a new project?
Thanks

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by 1036711153** [comment]
same problem! did you get a solution.

after rename packages

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by 1036711153** [comment]
> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so it's always better to open new issues and reference related issues.


I find when create flutter_project,

for exaplem 

flutter create --org com.example.flutter demo

then,I rename project 'demo' to 'flutter_demo' ,change packages name  'com.example.flutter.demo' to 'com.example.flutter.debug';

when I use flutter run ,this can appear,thank you!

**Comment by Kirito344** [comment]
any fixes facing the same issue ??
