### ISSUE TITLE
PathProvider.getApplicationDocumentsDirectory dir is incompatible with androidx FileProvider

### ISSUE THREAD

**Issue by rockgecko-development** [flutter/flutter#30271]
The directory returned by PathProvider.getApplicationDocumentsDirectory uses `context.getDir("flutter", 0)`, and looks like:
`/data/user/0/com.my.package/app_flutter`

The problem is, there is no way to share this directory using the androidx FileProvider library (https://developer.android.com/reference/androidx/core/content/FileProvider?hl=en), in order to share files with other apps eg GMail.
Even if you add `<files-path name="internal_files" path="." />` to the provider xml config, that uses `context.getFilesDir()` internally to resolve it (which returns eg `/data/user/0/com.my.package/files`, totally incompatible)

`getApplicationDocumentsDirectory()` is supposedly the only supported place to store non-temporary files without WRITE_EXTERNAL_STORAGE permission (which is going away in Android Q anyway). Where else can I persist my own files that I want to be able to share later, without manifest permission?

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
