### ISSUE TITLE
Add onLongTap support for google_maps plugin

### ISSUE THREAD

**Issue by cataCostea** [flutter/flutter#30270]
When will this feature be available? I would like to tap/long tap on map to get de point coordinates and place a pin in that location.

**Comment by KirolousNashaat** [comment]
there is pull request already made https://github.com/flutter/plugins/pull/1349 
but i don't know when it will land ..

**Comment by iskakaushik** [comment]
https://github.com/flutter/plugins/pull/985 merged. This should add support for onTap events.

For long tap @jan1za seems to be interested in implementing the feature. I'll leave this issue open to track it.

**Comment by ivk1800** [comment]
seems implemented
https://github.com/flutter/plugins/blob/8e17ab64d40136b6b097eac3ba25425d10a0291b/packages/google_maps_flutter/lib/src/google_map.dart#L124
