### ISSUE TITLE
I wish the interactive candlestick widget would be developed

### ISSUE THREAD

**Issue by huuang** [flutter/flutter#30283]
The interactive candlestick widget is necessary for all stock and cryptocurrency App, developing a candlestick widget will be appreciated.

**Comment by wiradikusuma** [comment]
IMO, such widget would be best served by the community instead of part of the official package, e.g. for JavaScript is http://techanjs.org/ (random googling). You _could_ probably wrap it inside a webview, although I'm not sure of the performance.
