### ISSUE TITLE
Archive Runner Failed PBXCp

### ISSUE THREAD

**Issue by StephanCassel** [flutter/flutter#30287]
My very first Flutter app is ready for publishing. Installing and running the app from Android Studio and Xcode works perfect but when the XCode (10.2) starts Archive it fails at the very end of the process with **PBXCp** error and error message:

error: '/Users/stephan/Library/Developer/Xcode/DerivedData/Runner-aldqclpvkpdvmwfyjhvexmwcufmi/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/GoogleService-Info.plist' is longer than filepath buffer size (1025).

It looks like recursive loop. 
 
I found one possible solution: Remove Flutter.framework from the build path but it did not help.

Any tips that can make my flutter app to be publish is very welcome.

Stephan

**Comment by StephanCassel** [comment]
A small step for the man......

**App "Runner" successfully uploaded** 
Yes, it was a recursive loop: The **Runner.app** had crawled its way into **Copy Boundle Resources**.
Should be note about this in the excellent "Preparing an iOS App for Release"

**Comment by carmel** [comment]
@StephanCassel I meet the same problem,  could you tell how to resolve it?
`
Xcode's output:
↳
    Building AOT snapshot in release mode (ios-release)...          
    Building App.framework for arm64...

    Building App.framework for armv7...
    Building AOT snapshot in release mode (ios-release)...             37.9s
    Built to build/aot/.
    warning: parsing line table prologue at offset 0x6f697463 found unsupported version 0x00
    warning: line table parameters mismatch. Cannot emit.
    note: while processing /Users/carmel/AppWorkspace/stats/build/aot/armv7/snapshot_assembly.o
    Project /Users/carmel/AppWorkspace/stats built and packaged successfully.
    error:
    '/Users/carmel/AppWorkspace/stats/build/ios/Release-iphoneos/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.
    app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.ap
    p/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/
    Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Runner.app/Debug.xcconfig' is longer than filepath buffer
    size (1025). (in target 'Runner' from project 'Runner')
    note: Using new build systemnote: Planning buildnote: Constructing build descriptionwarning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc
    inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target 'Runner' from project 'Runner')warning: The use of Swift 3 @objc inference in Swift 4 mode is deprecated.
    Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target. (in target
    'Runner' from project 'Runner')

Encountered error while building for device.
`

**Comment by StephanCassel** [comment]
In the Copy Bundle Resources Section, see attachment should not include runner.
Somewhere. I cannot remember where, it said that the Runner must be checked as Target Membership on the right side of Xcode (click on the info.plist and check, see attachment) When I you uncheck the Runner is will not be included in the Copy Bundle Resource Section. 
In summery: remove Runner from Copy Bundle Resources and uncheck the membership.
Hope it helps
![Screenshot 2019-09-28 at 20 50 03](https://user-images.githubusercontent.com/5372762/65821216-de759200-e232-11e9-80e4-2fb57267b7d6.png)
![Screenshot 2019-09-28 at 21 00 11](https://user-images.githubusercontent.com/5372762/65821227-ff3de780-e232-11e9-926d-ec8777ac7634.png)

**Comment by carmel** [comment]
Thank you Stephan,It's just ok  @StephanCassel

**Comment by iapicca** [comment]
Hi @StephanCassel 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by StephanCassel** [comment]
Hi @iapicca 
This issue should be closed. My mistake.

**Comment by imaprototype** [comment]
Thanks @StephanCassel it worked for me :)
