### ISSUE TITLE
GridView Failed assertion 'textDirection' != null

### ISSUE THREAD

**Issue by gavinfuu** [flutter/flutter#30298]
code:
import 'package:flutter/widgets.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    return ConstrainedBox(
      constraints: BoxConstraints(
        minHeight: 600,
        minWidth: 300
      ),
      child: GridView.count(
        primary: false,
        padding: const EdgeInsets.all(20.0),
        crossAxisSpacing: 10.0,
        crossAxisCount: 2,
        children: <Widget>[
          Text('Hed have you all unravel at the', textDirection: TextDirection.ltr),
          Text('Hed have you all unravel at the', textDirection: TextDirection.ltr),
          Text('Hed have you all unravel at the', textDirection: TextDirection.ltr),
        ],
      )
    );
  }

}

## Logs
I/flutter ( 4328): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4328): The following assertion was thrown building
I/flutter ( 4328): RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#02491](state:
I/flutter ( 4328): RawGestureDetectorState#7dbf5(gestures: <none>, behavior: opaque)):
I/flutter ( 4328): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
I/flutter ( 4328): != null': is not true.
I/flutter ( 4328): 
I/flutter ( 4328): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4328): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4328): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4328):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4328): 
I/flutter ( 4328): When the exception was thrown, this was the stack:
I/flutter ( 4328): #2      textDirectionToAxisDirection 
I/flutter ( 4328): #3      Viewport.getDefaultCrossAxisDirection 
I/flutter ( 4328): #4      ShrinkWrappingViewport.createRenderObject 
I/flutter ( 4328): #5      RenderObjectElement.mount 
I/flutter ( 4328): #6      MultiChildRenderObjectElement.mount 
I/flutter ( 4328): #7      Element.inflateWidget 
I/flutter ( 4328): #8      Element.updateChild 
I/flutter ( 4328): #9      SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #10     Element.inflateWidget 
I/flutter ( 4328): #11     Element.updateChild 
I/flutter ( 4328): #12     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #13     Element.inflateWidget 
I/flutter ( 4328): #14     Element.updateChild 
I/flutter ( 4328): #15     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #16     Element.inflateWidget 
I/flutter ( 4328): #17     Element.updateChild 
I/flutter ( 4328): #18     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #19     Element.inflateWidget 
I/flutter ( 4328): #20     Element.updateChild 
I/flutter ( 4328): #21     ComponentElement.performRebuild 
I/flutter ( 4328): #22     Element.rebuild 
I/flutter ( 4328): #23     ComponentElement._firstBuild 
I/flutter ( 4328): #24     StatefulElement._firstBuild 
I/flutter ( 4328): #25     ComponentElement.mount 
I/flutter ( 4328): #26     Element.inflateWidget 
I/flutter ( 4328): #27     Element.updateChild 
I/flutter ( 4328): #28     ComponentElement.performRebuild 
I/flutter ( 4328): #29     Element.rebuild 
I/flutter ( 4328): #30     ComponentElement._firstBuild 
I/flutter ( 4328): #31     ComponentElement.mount 
I/flutter ( 4328): #32     Element.inflateWidget 
I/flutter ( 4328): #33     Element.updateChild 
I/flutter ( 4328): #34     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #35     Element.inflateWidget 
I/flutter ( 4328): #36     Element.updateChild 
I/flutter ( 4328): #37     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #38     Element.inflateWidget 
I/flutter ( 4328): #39     Element.updateChild 
I/flutter ( 4328): #40     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #41     Element.inflateWidget 
I/flutter ( 4328): #42     Element.updateChild 
I/flutter ( 4328): #43     SingleChildRenderObjectElement.mount 
I/flutter ( 4328): #44     Element.inflateWidget 
I/flutter ( 4328): #45     Element.updateChild 
I/flutter ( 4328): #46     ComponentElement.performRebuild 
I/flutter ( 4328): #47     Element.rebuild 
I/flutter ( 4328): #48     ComponentElement._firstBuild 
I/flutter ( 4328): #49     ComponentElement.mount 
I/flutter ( 4328): #50     Element.inflateWidget 
I/flutter ( 4328): #51     Element.updateChild 
I/flutter ( 4328): #52     ComponentElement.performRebuild 
I/flutter ( 4328): #53     Element.rebuild 
I/flutter ( 4328): #54     ComponentElement._firstBuild 
I/flutter ( 4328): #55     StatefulElement._firstBuild 
I/flutter ( 4328): #56     ComponentElement.mount 
I/flutter ( 4328): #57     Element.inflateWidget 
I/flutter ( 4328): #58     Element.updateChild 
I/flutter ( 4328): #59     ComponentElement.performRebuild 
I/flutter ( 4328): #60     Element.rebuild 
I/flutter ( 4328): #61     ComponentElement._firstBuild 
I/flutter ( 4328): #62     StatefulElement._firstBuild 
I/flutter ( 4328): #63     ComponentElement.mount 
I/flutter ( 4328): #64     Element.inflateWidget 
I/flutter ( 4328): #65     Element.updateChild 
I/flutter ( 4328): #66     ComponentElement.performRebuild 
I/flutter ( 4328): #67     Element.rebuild 
I/flutter ( 4328): #68     ComponentElement._firstBuild 
I/flutter ( 4328): #69     ComponentElement.mount 
I/flutter ( 4328): #70     Element.inflateWidget 
I/flutter ( 4328): #71     Element.updateChild 
I/flutter ( 4328): #72     ComponentElement.performRebuild 
I/flutter ( 4328): #73     Element.rebuild 
I/flutter ( 4328): #74     ComponentElement._firstBuild 
I/flutter ( 4328): #75     ComponentElement.mount 
I/flutter ( 4328): #76     Element.inflateWidget 
I/flutter ( 4328): #77     Element.updateChild 
I/flutter ( 4328): #78     RenderObjectToWidgetElement._rebuild 
I/flutter ( 4328): #79     RenderObjectToWidgetElement.mount 
I/flutter ( 4328): #80     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
I/flutter ( 4328): #81     BuildOwner.buildScope 
I/flutter ( 4328): #82     RenderObjectToWidgetAdapter.attachToRenderTree 
I/flutter ( 4328): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
I/flutter ( 4328): #84     runApp 
I/flutter ( 4328): #85     main 
I/flutter ( 4328): #86     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
I/flutter ( 4328): #91     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
I/flutter ( 4328): #92     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
I/flutter ( 4328): #93     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 4328): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter ( 4328): ════════════════════════════════════════════════════════════════════════════════════════════════════
Restarted application in 1,465ms.

**Comment by HansMuller** [comment]
Typically the Directionality widget is created for you by the the WidgetsApp or MaterialApp widget. 

For example:
```
void main() {
  runApp(WidgetsApp: home: MyApp());
}
```

**Comment by gavinfuu** [comment]
> Typically the Directionality widget is created for you by the the WidgetsApp or MaterialApp widget.
> 
> For example:
> 
> ```
> void main() {
>   runApp(WidgetsApp: home: MyApp());
> }
> ```

thanks! it works right with WidgetsApp now!
