### ISSUE TITLE
Navigating to another page , results in previous page rebuilding.

### ISSUE THREAD

**Issue by samarthgupta29** [flutter/flutter#30293]
i have a http call to upload image to server , after navigating from this page to another page , results in another http call , thus uploading the same image multiple times and this process continues . I am navigating to another page using Navigator.push method , can anybody help me in figuring out the solution to this problem.I believe this is a known issue with flutter , while we should assume that rebuilding is as intended but it results in unnecessary http calls.

i have tried calling http request in initState , but did'nt worked.

i expect the image to be uploaded only once after navigating to next page , but the actual result is , multiple copies of that particular image is uploaded.

**Comment by csells** [comment]
@samarthgupta29 I suggest posting this question along with a short bit of code to reproduce the issue you're seeing on Stackoverflow, which is a more appropriate place to ask questions.
