### ISSUE TITLE
some of my flutter packages are not installed on my flutter app

### ISSUE THREAD

**Issue by wicmad** [flutter/flutter#30292]
[+64351 ms] Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
[  +52 ms] pub get failed (69) -- attempting retry 1 in 1 second...
[+1016 ms] Using D:\flutter\flutter_windows_v1.2.1-stable\flutter\.pub-cache for the pub cache.
[   +2 ms] executing: [D:\flutter_app\flutter_test_app\]
D:\flutter\flutter_windows_v1.2.1-stable\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose get
--no-precompile
[+64364 ms] Got socket error trying to find package cupertino_icons at https://pub.dartlang.org.
[  +51 ms] pub get failed (69) -- attempting retry 2 in 2 seconds...
[+2017 ms] Using D:\flutter\flutter_windows_v1.2.1-stable\flutter\.pub-cache for the pub cache.
[   +3 ms] executing: [D:\flutter_app\flutter_test_app\]
D:\flutter\flutter_windows_v1.2.1-stable\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose get
--no-precompile

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
