### ISSUE TITLE
Show image by ByteData

### ISSUE THREAD

**Issue by agnoam** [flutter/flutter#30308]
Hey I'm using `multi_image_picker: 2.4.11` plugin.
This plugin shows a multiple images picker and at the end of it's action, this plugin return a `List<Asset>`.

So how can I show the selected images in my app, in Widget of image or something like this ?

**Comment by Zazo032** [comment]
You can use ListView.builder() to show all the Assets of the list

**Comment by agnoam** [comment]
How ?
Can you show me an example ?

**Comment by agnoam** [comment]
> You can use ListView.builder() to show all the Assets of the list

This [Asset](https://pub.dartlang.org/documentation/multi_image_picker/latest/asset/Asset-class.html)  I need.

**Comment by agnoam** [comment]
Can you write one, Because I didn't understand.

**Comment by dnfield** [comment]
Please consider using one of the other channels mentioned at https://flutter.dev/community for these kinds of questions.

I've posted a question and answered it here: https://stackoverflow.com/questions/55464761/how-to-load-image-widgets-from-bytedata-in-flutter

**Comment by GerGodfrey** [comment]
You have a Asset files right ? 
you need for if you have a lot images : 

ByteData bd = await asset.requestThumbnail(224,224,quality: 100); // width and height
Uint8List a2 = bd2.buffer.asUint8List() ;
listaU8L.add(a2);
Image ( image: MemoryImage(listaU8L[0]) )

**Comment by PrinceKrJha** [comment]
> You have a Asset files right ?
> you need for if you have a lot images :
> 
> ByteData bd = await asset.requestThumbnail(224,224,quality: 100); // width and height
> Uint8List a2 = bd2.buffer.asUint8List() ;
> listaU8L.add(a2);
> Image ( image: MemoryImage(listaU8L[0]) )

I need the whole code. can you give it to me ?
