### ISSUE TITLE
Use cloud_firestore in Android is ok, but Xcode build error

### ISSUE THREAD

**Issue by SinonGit** [flutter/flutter#30306]
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/steve/Development/flutter/saochat/ios/Pods/BoringSSL-GRPC/ssl/t1_lib.cc:3224:9: error: use of undeclared identifier 'SSL_get_secure_renegotiation_support'; did you mean 'GRPC_SHADOW_SSL_get_secure_renegotiation_support'?
          !(SSL_get_secure_renegotiation_support(ssl) &&
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            GRPC_SHADOW_SSL_get_secure_renegotiation_support
    In file included from /Users/steve/Development/flutter/saochat/ios/Pods/BoringSSL-GRPC/ssl/t1_lib.cc:109:

    /Users/steve/Development/flutter/saochat/ios/Pods/Headers/Private/BoringSSL-GRPC/openssl_grpc/ssl.h:4328:5: note: expanded from macro 'SSL_get_secure_renegotiation_support'
        SSL_get_secure_renegotiation_support
        ^
    /Users/steve/Development/flutter/saochat/ios/Pods/Headers/Private/BoringSSL-GRPC/openssl_grpc/ssl.h:1523:20: note: 'GRPC_SHADOW_SSL_get_secure_renegotiation_support' declared here
    OPENSSL_EXPORT int SSL_get_secure_renegotiation_support(const SSL *ssl);
                       ^
    In file included from <built-in>:1:
    /Users/steve/Development/flutter/saochat/ios/Pods/Target Support Files/BoringSSL-GRPC/BoringSSL-GRPC-prefix.pch:232:46: note: expanded from macro 'SSL_get_secure_renegotiation_support'
    #define SSL_get_secure_renegotiation_support GRPC_SHADOW_SSL_get_secure_renegotiation_support
                                                ^
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-JP)
    • Flutter version 1.2.1 at /Users/steve/tools/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

**Comment by cameronpalatas** [comment]
Any update on this?

**Comment by KevinColemanInc** [comment]
@cameronpalatas This "fix" worked for me :-/
https://www.gitmemory.com/issue/flutter/flutter/32202/491577147

**Comment by kroikie** [comment]
@SinonGit

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1237. Any further collaboration will be done there.
