### ISSUE TITLE
i have a error when i am trying to debug my app

### ISSUE THREAD

**Issue by Aajat** [flutter/flutter#30309]
Compiler message:
file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:996:66: Error: Getter not found: 'extChildStyle'.
          final String childPrefixOtherLines ='$prefixChildren${~extChildStyle.linkCharacter}${childConfig.prefixOtherLines}';
                                                                 ^^^^^^^^^^^^^
file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart:996:66: Error: The getter 'extChildStyle' isn't defined for the class 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'extChildStyle'.
          final String childPrefixOtherLines ='$prefixChildren${~extChildStyle.linkCharacter}${childConfig.prefixOtherLines}';
                                                                 ^^^^^^^^^^^^^
Compiler failed on C:\Users\nepal\OneDrive\Desktop\flutter\app2\lib/main.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        16.2s
Gradle task assembleDebug failed with exit code 1

**Comment by Aajat** [comment]
this is the problem i am facing

**Comment by Aajat** [comment]
this is the problem

**Comment by dnfield** [comment]
line 996 of that file is supposed to read `final String childPrefixOtherLines ='$prefixChildren${nextChildStyle.linkCharacter}${childConfig.prefixOtherLines}';`.

I strongly suspect you accidentally edited and saved that file to have a `~` instead of an `n` by accident. 

Please feel free to re-open the issue if that doesn't resolve things.
