### ISSUE TITLE
Flutter TextField multiline fails to wrap when entering space on the Line

### ISSUE THREAD

**Issue by WHATHELWHATHELWHATHEL** [flutter/flutter#30302]
## Steps to Reproduce

First please take a look at this video: [Flutter Textfield Input Bug Video](https://www.youtube.com/watch?v=--vJVFL-kmg)

In this video, you can discover that when input some regular english characters in the end of the line, the text can be correctly wrapped into next line.

But when you enter space in the end of the line (as the later part of the video),  the text fails to wrap to the next line. And the input cursor just simply go outside of TextField box in the same line.

This is a simple demo, code as follow: 

```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text('input space in the following input field'),
            Text('to see if it can properly change line'),
            Container(
              height: 100, width: 200,
              color: Colors.indigo,
              child: TextField(
                style: TextStyle(color: Colors.white),
                keyboardType: TextInputType.multiline,
                maxLines: 3,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

Steps to reproduce:

1.  choose the blue box to select the TextField
2. Keep entering space
3. The problem will occur

Flutter analyze result as follow, no issues

```

Analyzing inputfield_no_change_line...                           
No issues found! (ran in 2.5s)

```

Flutter doctor as follow

```
[✓] Flutter (Channel faceu_dev_1.0.0, v1.0.1-pre.8, on Mac OS X 10.14.3 18D109, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by WHATHELWHATHELWHATHEL** [comment]
Besides, Both IOS and Android has this problem

**Comment by WHATHELWHATHELWHATHEL** [comment]
...Any help here, this is a serious problem, and I failed to discover an existing solution.
Please reponse...

**Comment by justinmc** [comment]
Thanks for the full example!  I can reproduce the problem.  Any TextField that doesn't scroll horizontally will experience it, actually.  The cursor will even go off the screen without wrapping.

This looks serious so I will try to get to it soon.  I can't think of a workaround in the meantime, but you might have luck by downgrading Flutter if this is a regression.

**Comment by WHATHELWHATHELWHATHEL** [comment]
> Thanks for the full example! I can reproduce the problem. Any TextField that doesn't scroll horizontally will experience it, actually. The cursor will even go off the screen without wrapping.
> 
> This looks serious so I will try to get to it soon. I can't think of a workaround in the meantime, but you might have luck by downgrading Flutter if this is a regression.

Thanks, Please try to solve this problem or provide a workaround ASAP.
I temporarily use a TextInputFormatter to trim the input to avoid user entering more than one space in the end of the string. 
But this is serious damage to user experience, any further updates or suggestions is appreciated.

**Comment by justinmc** [comment]
Just as a note, here is how iOS and Android handle this natively.  Spaces exceeding the end of a line cause the cursor to simply stay at the end of the line and do not cause the line to wrap.  The spaces are recorded in the string, however.

![Screenshot_20190402-150221](https://user-images.githubusercontent.com/389558/55439307-0c666c00-5559-11e9-83c3-6bb8689b3a6c.png)
![IMG_2597](https://user-images.githubusercontent.com/389558/55439308-0cff0280-5559-11e9-8012-9acffb9e6d76.jpg)

**Comment by WHATHELWHATHELWHATHEL** [comment]
> Just as a note, here is how iOS and Android handle this natively. Spaces exceeding the end of a line cause the cursor to simply stay at the end of the line and do not cause the line to wrap. The spaces are recorded in the string, however.
> 
> ![Screenshot_20190402-150221](https://user-images.githubusercontent.com/389558/55439307-0c666c00-5559-11e9-83c3-6bb8689b3a6c.png)
> ![IMG_2597](https://user-images.githubusercontent.com/389558/55439308-0cff0280-5559-11e9-8012-9acffb9e6d76.jpg)

Got it, So should Flutter TextField duplicate this feature?

**Comment by justinmc** [comment]
Thanks for the gif, that's much more clear.  I'm not aware of this being on a spec, but it seems intentional.  Flutter should probably duplicate it.  It would at least be much better than allowing the cursor to go out of the input!

**Comment by justinmc** [comment]
Fixed in the PR above!

**Comment by WHATHELWHATHELWHATHEL** [comment]
> Fixed in the PR above!

Thank you very much ! This is gonna to be useful.
