### ISSUE TITLE
Improve _Asset class in flx.dart

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3031]
The class (part of the flutter_tools package) has several similar sounding fields, particularly "source" and "base".  We should do a cleanup pass over this class and improve the naming and field documentation so it's easier to understand how to use the class.

**Comment by sethladd** [comment]
Placed into Milestone 2 so we can eval if we're going to make this API change.

**Comment by Hixie** [comment]
This is just a code health issue, doesn't affect devs. Moving to no-milestone bucket.

**Comment by Hixie** [comment]
This will happen anyway when we remove FLXes.
