### ISSUE TITLE
Generic mechanism to query Flutter runtime "state"

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#30319]
It would be helpful to be able to check the current state of Flutter from the platform in order to determine whether or not you can / should communicate with Flutter. There are definitely cases (see #30000) where you are not able to communicate with Flutter (or probably shouldn't) because the event will be lost.

I couldn't see anything like this in the code/docs. Apologies if it exists.

**Comment by escamoteur** [comment]
I close this here because it is discussed in the other issue already
