### ISSUE TITLE
Running "flutter packages get" in flutter_app...  报错

### ISSUE THREAD

**Issue by xzblog** [flutter/flutter#30313]
C:\SDK\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in flutter_app... 
Scheme not starting with alphabetic character (at character 1)
 https://pub.flutter-io.cn/api/packages/cupertino_icons
^
dart:core                                                                       Uri.parse

package:pub/src/source/hosted.dart 165:16                                       BoundHostedSource._makeUrl

package:pub/src/source/hosted.dart 132:15                                       BoundHostedSource.doGetVersions

===== asynchronous gap ===========================

package:pub/src/source.dart 167:12                                              BoundSource.getVersions

package:pub/src/solver/package_lister.dart 76:44                                PackageLister._versions.<fn>.<fn>

dart:async                                                                      runZoned

package:pub/src/http.dart 272:10                                                withDependencyType

package:pub/src/solver/package_lister.dart 75:33                                PackageLister._versions.<fn>

===== asynchronous gap ===========================

dart:async                                                                      new Future.sync
package:async/src/async_memoizer.dart 43:42                                     AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                                PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                               PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                               VersionSolver._choosePackageVersion.<fn>

===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                               minByAsync

===== asynchronous gap ===========================

package:pub/src/solver/version_solver.dart 350:25                               VersionSolver._choosePackageVersion

===== asynchronous gap ===========================

package:pub/src/solver/version_solver.dart 97:22                                VersionSolver.solve

===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                               resolveVersions.<fn>
package:pub/src/log.dart 378:18                                                 progress
package:pub/src/solver.dart 32:10                                               resolveVersions
package:pub/src/entrypoint.dart 200:24                                          Entrypoint.acquireDependencies
===== asynchronous gap ===========================

package:pub/src/command/get.dart 41:23                                          GetCommand.run

package:args/command_runner.dart 194:27                                         CommandRunner.runCommand

===== asynchronous gap ===========================

package:pub/src/command_runner.dart 168:39                                      PubCommandRunner.runCommand.<fn>
dart:async                                                                      new Future.sync
package:pub/src/utils.dart 109:12                                               captureErrors.<fn>
dart:async                                                                      runZoned
package:pub/src/utils.dart 126:5                                                captureErrors

package:pub/src/command_runner.dart 168:13                                      PubCommandRunner.runCommand

===== asynchronous gap ===========================

package:pub/src/command_runner.dart 117:11                                      PubCommandRunner.run

===== asynchronous gap ===========================

E:\b\rr\tmpxc66kk\w\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (65)

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
