### ISSUE TITLE
Consider support for nested Navigators across ChildViews

### ISSUE THREAD

**Issue by tonygentilcore** [flutter/flutter#3032]
I have a hacked `PageRoute` that has super primitive support for nested navigation stacks. The below code shows the idea, but it's based on an older Flutter API.

``` dart
class HeroSubPageRoute extends HeroPageRoute {
  final NavigatorState parentNavigator;
  NavigatorState childNavigator;

  HeroSubPageRoute(
      {this.parentNavigator,
      WidgetBuilder builder,
      NamedRouteSettings settings,
      HeroController heroController})
      : super(
            settings: settings,
            heroController: heroController,
            builder: builder) {}

  Duration get transitionDuration => const Duration(milliseconds: 1500);

  @override
  WidgetBuilder get builder {
    return (BuildContext context) {
      childNavigator = Navigator.of(context);
      return super.builder(context);
    };
  }

  @override
  void didPush(OverlayState overlay, OverlayEntry insertionPoint) {
   super.didPush(overlay, insertionPoint);
    parentNavigator.push(new StateRoute(onPop: () {
      childNavigator?.pop();
    }));
  }
}
```

Would it be reasonable for Flutter provide a more complete way to nest Navigators? Would it be reasonable to make this work across ChildViews?

/cc @abarth @ianloic

**Comment by Hixie** [comment]
Can you elaborate on what the use case is?

**Comment by tonygentilcore** [comment]
Yes. I have a parent that contains a ChildView. Each has their own Navigator. The catch is that I'd like this to work with the Android system back button. I can have them both handle the input event. But what I'd like (in the simplest case) is a way to make the back button pop the child Navigator until it's empty and then start popping the parent.

**Comment by Hixie** [comment]
so you mean nested navigators across processes, not nested navigators within the same process?

**Comment by tonygentilcore** [comment]
Yes

**Comment by Hixie** [comment]
Ah, ok. I think this is really a Mozart thing then. We'd participate in a nav protocol if there was one, but my understanding is that there isn't one yet. @j9brown, are you tracking that anywhere?

**Comment by Hixie** [comment]
cc @j9brown see above

**Comment by j9brown** [comment]
The protocols which drive navigation will likely need to be defined at a
higher level than Mozart itself, probably at the level of Stories and
Modules.

We haven't done any implementation in this area yet.

**Comment by sethladd** [comment]
@HansMuller is this on the radar at all? Curious if this needs a different milestone.

**Comment by abarth** [comment]
I don't think we need to track this in this issue tracker.  If this is needed for Fuchsia, it will come up again in that context.
