### ISSUE TITLE
Hot reload doesn't apply changes to TextStyle from a variable

### ISSUE THREAD

**Issue by MohammadMRD** [flutter/flutter#30323]
Hello,
I followed "Write Your First Flutter App" tutorial to the end. everything looks great. But while I'm in the debugging mode, changes applied to the `_biggerFont` style are not mirrored in the application by the _Hot reload_. However, if the `TextStyle` is applied directly (without a variable - like the attached file) to the `Text` widget, it will work fine. Also, if debug session is restarted, changes are also applied.

## Steps to Reproduce

1. Follow "Write Your First Flutter App" to the end
2. Change the TextStyle `_fontSize` to a different number or change the color of the Text
3. Save changes while in debugging, see that _Hot reload_ is not applying your changes

## Logs
Logs were too big. I attached them.

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```
[logs.txt](https://github.com/flutter/flutter/files/3030453/logs.txt)
[main.dart.txt](https://github.com/flutter/flutter/files/3030402/main.dart.txt)

**Comment by huangyanxiong01** [comment]
In Dart, static fields are lazily initialized. This means that the first time you run a Flutter app and a static field is read, it is set to whatever value its initializer was evaluated to. Global variables and static fields are treated as state, and are therefore not reinitialized during hot reload.
fllow [Recent code change is included but app state is excluded](https://flutter.dev/docs/development/tools/hot-reload#recent-code-change-is-included-but-app-state-is-excluded)
You can use function,it work just fine

```
TextStyle getTextStyle() {
    return const TextStyle(fontSize: 10);
}
```

**Comment by HugoHeneault** [comment]
Thanks @huangyanxiong01 for the explanation. I'm wondering: wouldn't it slow down the app as at every render this function will be executed? Imagine I have 100+ styles; would these functions be called at every render?

**Comment by AnnaPS** [comment]
Thanks a lot @LinuxUbuntuLearn u save my live with ur solution. 👍
