### ISSUE TITLE
_inheritedWidgets return null ? 

### ISSUE THREAD

**Issue by lifetin** [flutter/flutter#30325]
我在使用bloc开发的时候,一直都获取不到bloc, 调式后发现_inheritedWidgets中有这个类型存在,但是返回是空的.
When I was developing with bloc, I never got bloc. When I used the mode, I found that this type existed in _inherited Widgets, but the return was empty.

![11](https://user-images.githubusercontent.com/10474968/55346525-4d249d80-54e5-11e9-9597-c79335d15131.png)

file address
https://gist.github.com/boeledi/cb9b933b2e2664ae1ee5cc78b0da273a

![22](https://user-images.githubusercontent.com/10474968/55346699-ac82ad80-54e5-11e9-9972-1513697574f6.png)
![33](https://user-images.githubusercontent.com/10474968/55346701-ad1b4400-54e5-11e9-9faf-9fe746809820.png)

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.
