### ISSUE TITLE
TextField longpress dialog beyonds SafeArea.

### ISSUE THREAD

**Issue by loongliu** [flutter/flutter#30321]
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: SafeArea(
        child: Scaffold(
          appBar: AppBar(
            title: TextField(),
          ),
          body: Center(
              child: Container(
            width: 100,
            height: 100,
            color: Colors.blue,
          )),
        ),
      ),
    );
  }
}
```

![image](https://user-images.githubusercontent.com/15890184/55343647-1ac37200-54de-11e9-8640-f364e9ae9216.png)

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.1 18B75, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
@loongliu Thanks for pointing this out.  The positioning of the selection menu is on my radar as something I'd like to improve asap.  I'm going to close this issue to consolidate with https://github.com/flutter/flutter/issues/3945, but I'll mention this over there so we're sure we get this specific problem of it overlapping the cutout.
