### ISSUE TITLE
EventChannel does not work inside an isolate

### ISSUE THREAD

**Issue by softkot** [flutter/flutter#30332]
For some reason EventChannel does not listen for an events emitted from platform side if it runs within FlutterNativeView.runFromBundle isolate started as a part of android background service.

### Plugin-like class implements simple  MethodChannel and EventChannel.
Calling MethodChannel.invokeMethod emits counter on EventChannel.

```
class Plugin(registry: PluginRegistry, val label: String) {
    @Volatile
    private var sink: EventChannel.EventSink? = null
    private val counter = AtomicInteger()

    init {
        registry.registrarFor("isolate").apply {
            MethodChannel(messenger(), "methods").setMethodCallHandler { methodCall, result ->
                sink?.success(hashMapOf(
                        "label" to label,
                        "counter" to counter.incrementAndGet()
                ))
                Log.d("PLUGIN", "Call ${methodCall.method} from $label")
                result.success(null)
            }
            EventChannel(messenger(), "events").setStreamHandler(object : EventChannel.StreamHandler {
                override fun onListen(p0: Any?, s: EventChannel.EventSink?) {
                    sink?.endOfStream()
                    sink = s
                }

                override fun onCancel(p0: Any?) {
                    sink?.endOfStream()
                    sink = null
                }
            })
        }

    }
}
```
### Dart handler use MethodChannel and EventChannel to periodicaly call method and waiting any data on event channel to arrive.

```
void platformChannels() {
  print("Start platform channels test");
  MethodChannel pluginMethods = const MethodChannel('methods');
  EventChannel pluginEvents = const EventChannel('events');
  pluginEvents.receiveBroadcastStream().listen((data) {
    print(data);
  });
  Timer.periodic(Duration(seconds: 1), (timer) {
    pluginMethods.invokeMethod("tick", {});
  });
}

```
### Main activity startup code register the Plugin-like class and start android service
```
Plugin(this,"Activity")
startService(Intent(this,PluginService::class.java))
```

### Service startup code create new dart isolate with backgound FlutterNativeView with dart entrypoint set to platformChannels on main.dart
```
override fun onCreate() {
        super.onCreate()
        FlutterMain.startInitialization(this)
        FlutterMain.ensureInitializationComplete(this, null)
        bgView = FlutterNativeView(this, true)
        Plugin(bgView.pluginRegistry, "Service")
        bgView.runFromBundle(FlutterRunArguments().apply {
            bundlePath = FlutterMain.findAppBundlePath(this@PluginService)
            entrypoint = "platformChannels"
        })
    }
```
Finnaly when app is runnung only Activity bound dart code works as expected. Service bound dart code never prints data on listen closure.

## Steps to Reproduce

```
git clone https://github.com/softkot/flutter_isolate
cd flutter_isolate
```
Connect android device or an emulator and run 
```
flutter run
```

### produced
```
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 2}
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 3}
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 4}
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 5}
```

### expected
```
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 2}
I/flutter (25664): {label: Service, counter: 2}
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 3}
I/flutter (25664): {label: Service, counter: 3}
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 4}
I/flutter (25664): {label: Service, counter: 4}
D/PLUGIN  (25664): Call tick from Service
D/PLUGIN  (25664): Call tick from Activity
I/flutter (25664): {label: Activity, counter: 5}
I/flutter (25664): {label: Service, counter: 5}
```

```
```

## Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by dnfield** [comment]
Duplicate of https://github.com/flutter/flutter/issues/13937

**Comment by softkot** [comment]
> Duplicate of #13937
@dnfield here is some confusion you are mention  #13937 that states about method channels, my issue is related to EventChannels. MethodChannel works fine inside an isolate but EventChannel does not.

**Comment by 1AlexFix1** [comment]
This is really a very necessary thing, because it will be much easier to work with the background on the platform, because at the moment it is impossible to make a webrtc on a dart in the background, without it we can make a webrtc on a dart in the background

**Comment by dmccartney** [comment]
The fix for me was adding the missing `WidgetsFlutterBinding.ensureInitialized()` to the background isolate init. Without it, all background native -> dart messages are quietly dropped. (The foreground isolate does this implicitly when you `runApp()`.)

**Comment by escamoteur** [comment]
This should be fixed in the upcoming PR. you can monitor the PR if you want to follow it. If you still have problems please reopen this issue

**Comment by audkar** [comment]
Maybe issues should be closed after PRs are merged in to master? PRs can be rejected, delayed etc. Noone will go and reopen tickets in these cases.

**Comment by escamoteur** [comment]
If it was an PR from the outside I would agree.

**Comment by iapicca** [comment]
Hi @softkot 
Are you still experiencing the issue with the latest stable version of Flutter?
If so, can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample?
Thank you

**Comment by softkot** [comment]
Hi @iapicca. Now it works just expected, if include suggested fix with WidgetsFlutterBinding.ensureInitialized() thanks!

**Comment by AMiKaH** [comment]
I'm having the same exact issue. My native code receives data from a Bluetooth device and constantly sends them to Dart through the events channel. When I call this line 

`eventsChannel.receiveBroadcastStream().listen(eventReceived)

in the main isolate I can receive the data but the UI freezes, if I create an isolate and call it from within the new isolate I get the message:

> ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.


 I tried adding the WidgetsFlutterBinding.ensureInitialized() as the first line in main but no luck. My isolate is created on a different page.

My flutter doctor output:

> [√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-CA)
>     • Flutter version 1.17.0 at C:\Flutter
>     • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
>     • Engine revision 540786dd51
>     • Dart version 2.8.1
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\ameer\AppData\Local\Android\sdk
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.44.2)
>     • VS Code at C:\Users\ameer\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.10.1
> 
> [√] Connected device (1 available)
>     • SGH I337M • 8c0d323c • android-arm • Android 5.0.1 (API 21)
> 
> • No issues found!

Any input is greatly appreciated

**Comment by AMiKaH** [comment]
I'm having the same exact issue. My native code receives data from a Bluetooth device and constantly sends them to Dart through the events channel. When I call this line 

`eventsChannel.receiveBroadcastStream().listen(eventReceived)
`
in the main isolate I can receive the data but the UI freezes, if I create an isolate and call it from within the new isolate I get the message:

> ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.


 I tried adding the WidgetsFlutterBinding.ensureInitialized() as the first line in main but no luck. My isolate is created on a different page.

My flutter doctor output:

> [√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-CA)
>     • Flutter version 1.17.0 at C:\Flutter
>     • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
>     • Engine revision 540786dd51
>     • Dart version 2.8.1
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\""\AppData\Local\Android\sdk
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.44.2)
>     • VS Code at C:\Users\""\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.10.1
> 
> [√] Connected device (1 available)
>     • SGH I337M • 8c0d323c • android-arm • Android 5.0.1 (API 21)
> 
> • No issues found!

Any input is greatly appreciated

**Comment by tirth-stasis** [comment]
I'm working on a Flutter plugin. Is it possible to use EventChannel in the background? Despite calling success on EventSink instance, on dart-side StreamBuilder is not able to receive the data. I'm not using an isolate but I've created a Foreground Service in my plugin.

**Comment by iapicca** [comment]
@tirth-stasis 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)

**Comment by tirth-stasis** [comment]
Sure! :+1:
