### ISSUE TITLE
Support flushing pending timers in a WidgetTester test

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#30344]
To test the first scenario described in https://github.com/flutter/flutter/issues/30340 I need to write a test that executes code after a timer is scheduled but before the next frame.

The current way to get timers to invoke in a widget test is by calling `WidgetTester#pump`, but this call also schedules a frame. 

This can be done for `AutomatedTestWidgetFlutterBinding` by exposing a method that calls `FakeAsync#flushTimers`, I'm not sure whether this can be done for `LiveTestWidgetFlutterBinding`.

**Comment by amirh** [comment]
WIP patch here: https://github.com/amirh/flutter/commit/7968324c0ae7dc97a1f828da860c9f8eb775367b

**Comment by dnfield** [comment]
Duplicate of https://github.com/flutter/flutter/issues/24166
