### ISSUE TITLE
firebase_auth sendEmailVerification missing actionCodeSettings parameter

### ISSUE THREAD

**Issue by willvlad** [flutter/flutter#30349]
https://firebase.google.com/docs/auth/web/passing-state-in-email-actions:

```
var actionCodeSettings = {
  url: 'https://www.example.com/?email=' + firebase.auth().currentUser.email,
  iOS: {
    bundleId: 'com.example.ios'
  },
  android: {
    packageName: 'com.example.android',
    installApp: true,
    minimumVersion: '12'
  },
  handleCodeInApp: true,
  // When multiple custom dynamic link domains are defined, specify which
  // one to use.
  dynamicLinkDomain: "example.page.link"
};
firebase.auth().currentUser.sendEmailVerification(actionCodeSettings)
  .then(function() {
    // Verification email sent.
  })
  .catch(function(error) {
    // Error occurred. Inspect error.code.
  });
```

Firebase has an ability to pass on action code settings when sending an email verification.

Flutter firebase_auth doesn't seem to have this functionality or is it hidden somewhere?

firebase_auth:
```
 /// Initiates email verification for the user.
  Future<void> sendEmailVerification() async {
    // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
    // https://github.com/flutter/flutter/issues/26431
    // ignore: strong_mode_implicit_dynamic_method
    await FirebaseAuth.channel.invokeMethod(
        'sendEmailVerification', <String, String>{'app': _app.name});
  }
```

**Comment by willvlad** [comment]
Bumping it up as no response five days later...

**Comment by willvlad** [comment]
@goderbauer @FlutterIssues @cbracken

**Comment by willvlad** [comment]
@amirh - hi, perhaps you might know if it's possible to pass action parameters as you commented in the above snippet?

**Comment by alfredoqt** [comment]
This is a very important issue, since it is not possible to let the user go back to the app after email verification or password reset using dynamic links. What is the process of making a pull request? I would like to contribute to this issue @FlutterIssues

**Comment by willvlad** [comment]
@alfredoqt I agree, it looks like Flutter still doesn't seem to expose a way to access actionCodeSettings in sendEmailVerification? @zoechi @Hixie @FlutterIssues

**Comment by dcoleyoung** [comment]
Is there a workaround to pass a continueUrl when using sendEmailVerification()?

**Comment by shadysamir** [comment]
Just spent an hour going in circles for this missing parameter. So sad to see it ignored here.

**Comment by escamoteur** [comment]
Hi,

Firebase has a new home here https://github.com/FirebaseExtended/flutterfire please raise there a new issue and reference this one. 
Thanks

**Comment by willvlad** [comment]
This missing param seems to be ignored in both threads so doesn't make sense to close any of them until it's resolved. Please re-open.

**Comment by sl1mpshady** [comment]
> This is a very important issue, since it is not possible to let the user go back to the app after email verification or password reset using dynamic links. What is the process of making a pull request? I would like to contribute to this issue @FlutterIssues

Hi @alfredoqt . Were you able to make a workaround?
