### ISSUE TITLE
Regression: A stroked line is rendering as a fill instead.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#30341]
When updating the API docs images, I encountered this regression in rendering:
![curve_decelerate_00000](https://user-images.githubusercontent.com/8867023/55363054-b4643280-5490-11e9-978d-2af3a1f69312.png)

It should look like this:
![curve_decelerate](https://user-images.githubusercontent.com/8867023/55362848-1bcdb280-5490-11e9-8f18-a63569768b09.png)

The odd thing is that it only seems to happen to some curves, not all.

I'm going to work on a minimal repro case, but it appears that the curve that is supposed to be rendered as a "stroke" is being rendered as a "fill" instead in some situations, so maybe a context leak on the graphics side?

**Comment by gspencergoog** [comment]
OK, here's a minimal (or at least a lot more minimal) repro case:
```dart
import 'dart:ui' as ui;
import 'package:flutter/widgets.dart';

void main() => runApp(BrokenCurve());

/// A custom painter to draw the graph of the curve.
class CurveDescription extends CustomPainter {
  CurveDescription(this.curve, this.position);

  final Curve curve;
  final double position;

  @override
  void paint(Canvas canvas, Size size) {
    final Rect area = Rect.fromLTRB(0, 0, size.width, size.height);
    final Path graph = Path()..moveTo(area.left, area.bottom);
    final double stepSize = 1.0 / (area.width * ui.window.devicePixelRatio);
    for (double t = 0.0; t <= 1.0; t += stepSize) {
      final Offset point = FractionalOffset(t, 1.0 - curve.transform(t)).withinRect(area);
      graph.lineTo(point.dx, point.dy);
    }
    canvas.drawPath(
        graph,
        Paint()
          ..color = const Color(0xffffffff)
          ..style = PaintingStyle.stroke
          ..strokeWidth = 4.0);
  }

  @override
  bool shouldRepaint(CurveDescription oldDelegate) => true;
}

class BrokenCurve extends StatelessWidget {
  BrokenCurve({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ConstrainedBox(
        constraints: BoxConstraints.tight(const Size(300.0, 200.0)),
        key: UniqueKey(),
        child: CustomPaint(
          painter: CurveDescription(Curves.decelerate, 0.0),
        ),
      ),
    );
  }
}
```

**Comment by gspencergoog** [comment]
Also, I noticed that if I change the `strokeWidth` to less than 0.30, then the artifact goes away, so perhaps something related to that.

**Comment by jason-simmons** [comment]
This started when CCPR was disabled: https://github.com/google/skia/commit/576b2a5596bc8dda294a069e3fdc6b8b8e48ffcf

This doesn't affect all devices, but it can be reproduced on a Nexus 6P

**Comment by cbracken** [comment]
@brianosman has someone on the Skia side had a chance to take a look at this?

**Comment by brianosman** [comment]
I think this may have been fixed by https://skia.googlesource.com/skia/+/cf4ec506ec4bf55471ea1eae294fb280a7540bcb,
which rolled into Flutter's engine with https://github.com/flutter/engine/commit/206cab6e701392fe0433f15a248516e94d4f8025

**Comment by gspencergoog** [comment]
I just verified this on Flutter master at https://github.com/flutter/flutter/commit/e427c2dd8673213565e615f645d7b03a20ff565c, and it is indeed fixed.
