### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by StephanCassel** [flutter/flutter#30368]
Using webview_flutter: ^0.3.2+1 

I get ERR_CLEARTEXT_NOT_PERMITTED for Android and blank page for iOS when I use
http://  urls. https:// urls seems to work.
The very same http:// urls works fine in Chrome. 

I recall I had the same problem in native Android as well.
Is possible to tell webview "please use http://. I will take the risk"

Thanks in advanced

**Comment by adesugbaa** [comment]
Open the android manifest file (android/app/src/main/AndroidManifest.xml) and add 

```
android:usesCleartextTraffic="true"
```

to the application tag

```
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="tangerine_ui"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
```

**Comment by StephanCassel** [comment]
Thanks for you replay.
I have tried that but got the same result and I guess it only help Android. iOS just shows a white screen.
My solution was to open HTTPS in webview and HTTP in an external browser. 
Good enough

**Comment by adesugbaa** [comment]
For IOS, you need to modify the info.plist **(ios/Runner/info.plist)**

Add the following:
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

You may need to be more explicit with the whitelist of http domains you need to support before releasing to the Apple Store.
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>yourdomain.com</key>
        <dict>
            <!--Include to allow subdomains-->
            <key>NSIncludesSubdomains</key>
            <true/>
            <!--Include to allow HTTP requests-->
            <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <!--Include to specify minimum TLS version-->
            <key>NSTemporaryExceptionMinimumTLSVersion</key>
            <string>TLSv1.1</string>
        </dict>
    </dict>
</dict>
```

**Comment by carl1990** [comment]
+1
Using webview_flutter: ^0.2.0
device is PCT AL10  • 46HDU19403003831                     • android-arm64 • Android 9 (API 28)
when I use https://baidu.com   is Ok
when I use https://hao123.com  get ERR_CLEARTEXT_NOT_PERMITTED error
when I use  https://github.com is ok

**Comment by fideldonson** [comment]
As far as i can tell this is still an issue in flutter. The usesCleartextTraffic works in native development but with flutter the 'ERR_CLEARTEXT_NOT_PERMITTED' persists.

**Comment by chrispruitt** [comment]
I am seeing the same issue as @fideldonson in my flutter application when trying to run on an android device

**Comment by werainkhatri** [comment]
> I am seeing the same issue as @fideldonson in my flutter application when trying to run on an android device

Me Too!

**Comment by noninoraikhah** [comment]
any solution for this?

**Comment by msarkrish** [comment]
@noninoraikhah @werainkhatri @chrispruitt @fideldonson 
Try with this Medium article, it's working for me.
https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

**Comment by pulkit8** [comment]
In case you wish to resolve it from the website code side (For people with less hands-on with android coding) following tutorial helped : 

[err_cleartext_not_permitted](https://www.basezap.com/fix-leartext-error-for-websites/)

This basically explains the basic issue on why this error pops up rather than workaround with android code.

**Comment by mannanshafique** [comment]
Same Problem but i simply put **https:**   rather than **http** 
Now its Working Fine 
Try it May be Helpful

**Comment by Amospikins** [comment]
check this out https://stackoverflow.com/questions/55592392/how-to-fix-neterr-cleartext-not-permitted-in-flutter
