### ISSUE TITLE
Android right slide back to invalid.

### ISSUE THREAD

**Issue by cwwng** [flutter/flutter#30367]
When using MaterialPageRoute, iOS can slide back right, but Android right slide back to invalid. MaterialPageRoute internally uses CupertinoPageRoute for iOS. Does Flutter support Android right slide back?

**Comment by Goolpe** [comment]
You can use for all platforms slide back, Navigator.push(context, CupertinoPageRoute(builder: (context) => SomeScreen())), 
you need import 'package:flutter/cupertino.dart'
