### ISSUE TITLE
Expanded Doesn't work anymore

### ISSUE THREAD

**Issue by AngelGordillo** [flutter/flutter#30366]
Hi there,
I hope you can help me. I'm calling an API to get some data and display it. I use Expanded + MarkdownBody. Everything was ok, until today that I get the  A RenderFlex overflowed error.
Has it something happened? Any update on Flutter? I leave my code in case you can help me.
Scaffold(
            appBar: AppBar(
              title: Text(questions.title),
            ),
            body: Container(
              padding: EdgeInsets.fromLTRB(10, 5, 10, 5),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Expanded(
                        child: RichText(
                          text: TextSpan(
                            text: questions.title,
                            style: TextStyle(
                                fontWeight: FontWeight.w600,
                                fontSize: 18.0,
                                color: Colors.black),
                          ),
                        ),
                      ),
                    
                    ],
                  ),
                 
                  Expanded(
                    child: MarkdownBody(
                      data: questions.body,
                    ),
                  )
                ],
              ),
            ),
          );
Thanks!

**Comment by AngelGordillo** [comment]
Fixed, it seems that from now you have to use Markdown instead of using MarkdownBody.
I will not close the issue in case someone knows why this is like this

**Comment by dcov** [comment]
@AngelGordillo I believe it's because `Markdown` uses a `ListView` hence it can scroll so it doesn't overflow. Whereas `MardownBody` uses a `Column` so when the content is bigger than can be displayed it overflows.

Also, consider asking on [StackOverflow](https://stackoverflow.com) first as you're more likely to get help there. This is mainly used for bugs within the framework.

**Comment by AngelGordillo** [comment]
Thanks for the explanation and indeed I should have asked on StackOverflow, sorry for this.
