### ISSUE TITLE
Closing Observatory quits Flutter app on IOS emulator

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#3036]
## Steps to Reproduce

I'm running my Flutter app on a Macbook, with an IOS emulator (iPhone 6s Plus). I'm starting my app and observing console logs through Atom. While my app is running, if I press the Observatory button, it opens a webpage in Chrome showing me the observatory stats. However, as soon as I close this page, my app crashes with the error messages below.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/vanadium/flutter
    • Framework revision 0eab5e6 (4 days ago), engine revision f790903
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002
[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1

## Logs and Crash Reports

SpringBoard: HW kbd: Failed to set (null) as keyboard focus
com.apple.CoreSimulator.SimDevice.894BD26A-F0F6-4633-AD4A-E1FA78B3FA28.launchd_sim[1027] (UIKitApplication:com.yourcompany.testapp[0xc230]: Service exited due to signal: Broken pipe: 13
SpringBoard: Application 'UIKitApplication:com.yourcompany.testapp[0xc230]' exited abnormally via signal.
assertiond: assertion failed: 15E65 13C75: assertiond + 12188 [8CF1968D-3466-38B7-B225-3F6F5B64C552]: 0x1
(last message repeated 1 time)
assertiond: notify_suspend_pid() failed with error 7
SpringBoard: Reply Error: Connection interrupted
routined: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by chinmaygarde** [comment]
This was fixed with a recent Dart roll. Please reopen if you run into this again.
