### ISSUE TITLE
[package_info] uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#30377]
Note: /home/cirrus/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+2/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

**Comment by duzenko** [comment]
I would appreciate a response from flutter team.
Can we resolve this warning?

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by duzenko** [comment]
Yes it is

**Comment by iapicca** [comment]
Hi @kw2019ltd 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you"

**Comment by duzenko** [comment]
@iapicca 
Why? Did you fix it yet?

**Comment by iapicca** [comment]
The issue doesn't seem present with the latest version of [package_info](https://pub.dev/packages/package_info)

<details>
  <summary>sample</summary>

```
import 'package:flutter/material.dart';
import 'package:package_info/package_info.dart';

void main()=> runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) => Scaffold(
    body: FutureBuilder<PackageInfo>(
      future: PackageInfo.fromPlatform(),
      builder: (BuildContext context, AsyncSnapshot<PackageInfo> snapshot) => snapshot.hasData
        ? ListView(
          children: <Widget>[
            Text(snapshot.data.appName),
            Text(snapshot.data.packageName),
            Text(snapshot.data.version),
            Text(snapshot.data.buildNumber),
          ],
        )
        : CircularProgressIndicator(),
  ),);
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Pixel 3a • 965AY0WP5C • android-arm64 • Android 10 (API 29)

• No issues found!
```
 
</details>

I'm closing this issue, if you disagree please write in the comments and I will reopen it
Thank you

**Comment by escamoteur** [comment]
Just checked it with my own App and at least on latest master this is still a problem

Flutter 1.12.16-pre.35 • channel master • https://github.com/flutter/flutter
Framework • revision b9a56b9f48 (3 days ago) • 2019-11-29 20:40:44 -0500
Engine • revision 8672e79af8
Tools • Dart 2.7.0

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\escam\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_info-0.4.1+2\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\escam\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\package_info-0.4.0+11\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\escam\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\path_provider-1.4.5\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by zigang93** [comment]
I am facing same issue now.. 
```
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
```

**Comment by Linus-DuJun** [comment]
I also got the same issue after upgrade to the latest flutter stable version.
注: /Users/someUser/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+13/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/someUser/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
/Users/someUser/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: 警告: [deprecation] FlutterPluginBinding中的getFlutterEngine()已过时
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());

**Comment by Linus-DuJun** [comment]
After add the follow line code as the first line of main() function, I can compile my project.
```WidgetsFlutterBinding.ensureInitialized();```

**Comment by Linus-DuJun** [comment]
> I am facing same issue now..
> 
> ```
> Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
>     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
>                         ^
> 1 warning
> ```

try add ```WidgetsFlutterBinding.ensureInitialized();```as your first line of main() function.

**Comment by riswanmsm** [comment]
> > I am facing same issue now..
> > ```
> > Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
> > Note: Recompile with -Xlint:deprecation for details.
> > C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
> >     setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
> >                         ^
> > 1 warning
> > ```
> 
> try add `WidgetsFlutterBinding.ensureInitialized();`as your first line of main() function.

The warning is showing also after adding WidgetsFlutterBinding.ensureInitialized();

**Comment by brenno951** [comment]
Same issue

> Note: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.3.3/android/src/main/java/vn/hunghd/flutterdownloader/DownloadWorker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                                                               
Note: Some input files use unchecked or unsafe operations.                                                         
Note: Recompile with -Xlint:unchecked for details.                                                                 
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());                   
                        ^                                                                                          
1 warning                                                                                                          
Note: Some input files use or override a deprecated API.                                                           
Note: Recompile with -Xlint:deprecation for details.

**Comment by agersea** [comment]
I'm seeing Deprecated API warnings in a fresh 1.12.13+5 flutter project for the following plugins:
- DeviceInfoPlugin.java
- FirebaseCrashlyticsPlugin.java
- FirebaseMessagingPlugin.java
- PackageInfoPlugin.java
- PathProviderPlugin.java
- SharedPreferencesPlugin.java

Steps to reproduce:
1. Create a new flutter project with Flutter sdk v 1.12.13+5 
2. update pubspec.yaml to include the dependencies listed above:
`device_info: ^0.4.1+4
  firebase_crashlytics: ^0.1.2+4
  firebase_messaging: ^6.0.9
  package_info: ^0.4.0+13
  shared_preferences: ^0.5.6`
3. Install dependencies $ flutter pub get
4. Run the sample project

Flutter Doctor results:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by MahdiPishguy** [comment]
```
C:\Users\mahdi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_info-0.4.1+4\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses or overrides a deprecated API.
```

**Comment by krishnakumarcn** [comment]
> ```
> C:\Users\mahdi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\device_info-0.4.1+4\android\src\main\java\io\flutter\plugins\deviceinfo\DeviceInfoPlugin.java uses or overrides a deprecated API.
> ```

Facing the issue and build is failing

**Comment by hemant17** [comment]
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overri
des a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25:
 warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
i am also getting this thing

**Comment by iapicca** [comment]
Hi all
please read this [answer](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by escamoteur** [comment]
@iapicca as the plugins don't have their own issues I reopen it again

**Comment by erkanmaras** [comment]
Same issue

> Task :package_info:compileDebugJavaWithJavac
Note: D:\Flutter\Sdk\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by oodavid** [comment]
Adding `multiDexEnabled true` to `android/app/build.gradle` fixes this error for me:

```
android {
    ...
    defaultConfig {
        ...
        multiDexEnabled true
    }
```

But I'm not entirely sure if I _should_ do this.
