### ISSUE TITLE
Testing that a Widget disappears (testWidgets)

### ISSUE THREAD

**Issue by msimon16** [flutter/flutter#30372]
I've made a widget (```GirafNotifyDialog```) that uses an ```AlertDialog```. The widget consist of some text, and a single button, which closes the dialog when pressed. 
When testing the widget, I try to confirm that the widget disappears after the button is pressed, but the test keeps failing, and I've tried several other approaches, but none seem to work. 
My test is as follows:
```
void main() {
  GirafNotifyDialog dialog = GirafNotifyDialog(
      title: 'TestingTitle',
      description: 'This description is for testing',
  );
  const String okayBtnKey = 'NotifyDialogOkayButton';

  testWidgets('Notify dialog pops on confirmation',
          (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: dialog,
      )
    );
    await tester.pump(Duration(milliseconds: 500));
    await tester.press(find.byKey(const Key(okayBtnKey)));
    await tester.pump(Duration(milliseconds: 500));
    expect(find.byType(GirafNotifyDialog), findsNothing);
  });
}
```
And the code for the button is as follows:
```
RaisedButton(
                  key: const Key('NotifyDialogOkayButton'),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10.0),
                        side: const BorderSide(
                            color: Color.fromRGBO(0, 0, 0, 0.3))),
                    color: const Color.fromRGBO(255, 157, 0, 1),
                    child: Row(
                      children: const <Widget>[
                        Icon(
                          Icons.check,
                          color: Color.fromRGBO(0, 0, 0, 1),
                        ),
                        Text(
                          'Okay',
                          style: TextStyle(color: Colors.white),
                        ),
                      ],
                    ),
                    onPressed: () {
                      Navigator.pop(context);
                    }),
```
Pictures of the screen can be seen before and after pressing the buttons:

![image](https://user-images.githubusercontent.com/26058779/55398614-4def1b00-5549-11e9-9e87-201f243effab.png)
![image](https://user-images.githubusercontent.com/26058779/55398634-55162900-5549-11e9-872f-fe3281ccc1d7.png)

Any help towards being able to test that the widget disappears from the screen, is greatly appreciated!

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
