### ISSUE TITLE
In the ios device,the page is stuck

### ISSUE THREAD

**Issue by xiaolongwuhpu** [flutter/flutter#30370]
English:    In the ios device, the home page uses VideoPlay or google_map to enter the secondary interface, click the home button to return to the desktop, and then return to the app. When you return to the home page, the page is stuck in the secondary interface.

Chinese:　在ios设备中,首页使用 VideoPlay 或者 google_map , 进入二级界面,点击home键返回桌面,然后返回app,点击返回首页时页面卡在二级界面.无法返回

## --   flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by Nazacheres** [comment]
It is also true for me, with similar circumstances:
1. widget A has the map.
2. pushed widget B.
3. go to a different app (any kind of action triggering the dispose). 
4. go back to the app (widget B). 
5. on the way back to widget A app will be stuck on a halfway there. Also, Performace Graph will be stuck. However, the already visible part of the map is interceptable.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
