### ISSUE TITLE
bata Cupertino version transitionBetweenRoutes Invalid

### ISSUE THREAD

**Issue by chenxianqi** [flutter/flutter#30382]
I found that the  transitionBetweenRoutes transtion animation failed.

[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.3.8 at /Users/chenxianqi/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chenxianqi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/chenxianqi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.6156.11

[✓] VS Code (version 1.32.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Redmi Note 7 • 2f49c4ea • android-arm64 • Android 9 (API 28)

**Comment by xster** [comment]
Unfortunately this issue isn't actionable unless there are some details of how to cause this issue or a simple repro code.
