### ISSUE TITLE
[firebase_messaging] support other click_action value on Android

### ISSUE THREAD

**Issue by ndusart** [flutter/flutter#30400]
Hello,

It may be a great thing to be able to get messages from notification having `click_action` set to another value than `FLUTTER_NOTIFICATION_CLICK`.

We have some other applications that receives message notifications from the same backend but they are not based on Flutter and they were using that key to select the Activity to handle the notification. It would be great if we could just send the same messages to our flutter application.

It would be great to be able to also receive messages with no `click_action` set. This starts the launcher intent when the user clicks on it.

This could be done by registering another callback function that receives the intent and returns `true` if this is an intent related to a firebase message. The application should know that based on the keys in the data payload. The next steps would be the same (calling `onMessage` or `onResume`, ...).

**Comment by escamoteur** [comment]
Hi,

Firebase has a new home here https://github.com/FirebaseExtended/flutterfire please raise there a new issue and reference this one. 
Thanks
