### ISSUE TITLE
CupertinoTextField border color may be wrong

### ISSUE THREAD

**Issue by xster** [flutter/flutter#30403]
According to https://github.com/flutter/flutter/pull/28460, our border color may be wrong. Investigate whether #CCCCCC specifically is a one off color used by text field borders on iOS or whether it's a recurring color that we're getting consistently wrong in other places in the UI as well.

**Comment by TahaTesser** [comment]
Hi @xster 
Is this still valid?

https://github.com/flutter/flutter/blob/8857c4cec89164fdb6293bef69f9d62c62733efa/packages/flutter/lib/src/cupertino/text_field.dart#L22

Thank you

**Comment by DanielEdrisian** [comment]
Note to self: Use https://github.com/flutter/platform_tests/tree/master/ios_widget_catalog_compare to check this.

**Comment by DanielEdrisian** [comment]
Original author of the issue didn't consider that the border color was RGBA, and was using a color picker that didn't account for the alpha value. Closing.
