### ISSUE TITLE
After adding AutomaticKeepAliveClient Mixin, the program will not run.

### ISSUE THREAD

**Issue by lisong15** [flutter/flutter#30418]
![error-fl](https://user-images.githubusercontent.com/15123628/55448280-c7dedd00-55f9-11e9-823f-8589eef2aa84.jpg)
But I didn't add it to main. dart.
![error-fl1](https://user-images.githubusercontent.com/15123628/55448393-2efc9180-55fa-11e9-95d2-4b3d5b999eb2.jpg)

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
