### ISSUE TITLE
Debugger Break Point Issue on Http Post

### ISSUE THREAD

**Issue by chitwoob** [flutter/flutter#30419]
I found and odd problem when adding a beak point just prior to an async http post call. For some reason the post command seemed to be blocked. The app just hung there waiting for a response. I monitored The network traffic. Nothing was sent. What was interesting was if I clicked the back button the network call went through. The app preforms as expected without the break point. 

void _handleCreateBtn() async {
//Break point was here.
var resp = await LoginApi.newUsr(
            nameController.text, usrController.text, passController.text);
}

static Future<StdResp> newUsr(String name, String usr, String pass) async {
    final url = "example.com/NewUser";
    try {
      Map<String, dynamic> json = new Map<String, dynamic>();
      json['name'] = name;
      json['email'] = usr;
      json['password'] = pass;

      var jsonStr =jsonEncode(json);

      var resp = await http.post(url,
          headers: {"Content-Type": "application/json"}, body: jsonStr);

      var ret = StdResp.fromJsonStr(resp.body);
      return ret;
    } catch (e) {
      return null;
    }
  }

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

I'm using a Samsung S7 edge for testing.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
