### ISSUE TITLE
Some event kinds shouldn't allow non-zero pressure

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#30412]
## Reasoning

Currently most pointer event classes accepts a parameter `pressure` in their unnamed constructors and pass it to their superclass `PointerEvent`. This allows them to have non-zero pressure, which however doesn't always makes sense. More specifically, a non-zero pressure indicates that the pointer is in contact with the screen with certain force. The following table lists all event types and whether they are supposed to have a non-zero pressure:

| Pointer event kind | Does non-zero pressure make sense? |
| -- | -- |
| `PointerAddedEvents` | **No**. This event indicates the start of the device tracking the pointer, which should contain no movement. |
| `PointerCancelEvents` | **No**. This event indicates the end the pointer being directed towards this device, which should contain no movement. |
| `PointerScrollEvents` | **No**. It's a pointer signal and doesn't change the state of the pointer.  |
| `PointerSignalEvents` | **No**. Pointer signals doesn't change the state of the pointer. |
| `PointerUpEvents` | **No**. The pointer has stopped making contact with the device, hence the pressure must be zero. |
| `PointerMoveEvents` | **Yes**. The pointer is moving while in contact with the device. |
| `PointerDownEvents` | **Yes**. The pointer has made contact with the device. |
| `PointerExitEvents` | **No**. This event only includes situations where the pointer is not in contact with the device. |
| `PointerEnterEvents` | **No**. This event only includes situations where the pointer is not in contact with the device. |
| `PointerHoverEvents` | **No**. The pointer is moving while not in contact with the device. |
| `PointerRemovedEvents` | **No**. This event indicates the end of the device tracking the pointer, which should contain no movement. |

This parameter was brought in by https://github.com/flutter/flutter/pull/24554, which added pressure to every pointer event classes to support force press gesture. According to [discussion](https://github.com/flutter/flutter/pull/24554/files#r241582381), this change was questioned ([here](https://github.com/flutter/flutter/pull/24554#discussion_r236782663) among many others) at first, but eventually made it due to miscommunication. [A later PR](https://github.com/flutter/flutter/pull/24830) which added Enter and Exit likely followed the same pattern for consistency.

## Changes

We propose to remove `pressure` from the unnamed constructors of the following classes:
- `PointerAddedEvent`
- `PointerRemovedEvent`
- `PointerHoverEvent`
- `PointerEnterEvent`
- `PointerExitEvent`
- `PointerUpEvent`
- `PointerCancelEvent`

Instead, each class will pass `pressure = 0.0` to its superclass.

A proposed PR can be found at https://github.com/flutter/flutter/pull/30414.

## Impact

This change will break code that _explicitly creates_ an instance of the aforementioned classes and specifying pressure.

To migrate the affected code,
- If your constructor has pressure = 0.0, simply remove this argument and the behavior will be the same.
- If your constructor has a non-zero pressure, migrate based on why it was needed. For example,
  - A `PointerHoverEvent` in this way is likely a misuse from `PointerMoveEvent`, which is defined as moving while the pointer is _in contact with the device_ (per class documentation), where a non-zero pressure makes sense.
  - A `PointerAddedEvent` in this way should be expanded into an `Added` followed by a `Down` with the requested `pressure` and `down`.
  - A `PointerRemovedEvent` or `PointerCancelEvent` in this way should be expanded into a `Move` with the requested `pressure` and `down` followed by a `Removed` or `Cancel`.

This change will _not_ break code that uses events dispatched by Flutter framework, including all gestures.

**Comment by JediBurrell** [comment]
It currently takes all mouse events, as with the `down` property, which would explain it. I see it more of a `scale` situation, where this callback overrides `PointerMoveEvent` (though this is not mentioned). Unless I'm misinterpreting it, this seems intentional.

**Comment by dkwingsmt** [comment]
> It currently takes all mouse events, as with the `down` property, which would explain it. I see it more of a `scale` situation, where this callback overrides `PointerMoveEvent` (though this is not mentioned). Unless I'm misinterpreting it, this seems intentional.

Sorry, I don't quite get you, can you elaborate?
As far as my understanding of your point,
- `PointerHoverEvent` does not allow customization of `down`, instead sets `down = false`.
- The definition of Hover and Move are described in their doc, where hover The pointer has moved with respect to the device while the pointer is not in contact with the device." while Move is "The pointer has moved with respect to the device while the pointer is in contact with the device." They are not interchangeable.

**Comment by JediBurrell** [comment]
Upon further looking, I can see I was indeed misinterpreting it. I could have sworn `down` returned its value, but you're right. My apologies.
