### ISSUE TITLE
[image_picker] Released app on play store crashing due to image_picker plugin, help!

### ISSUE THREAD

**Issue by kaxp** [flutter/flutter#30429]
Hello all, 
Recently I have launched an app on play store and on play console under Crashes I have got various crash reports for image_picker. 

My code snippet is as follows:
```dart
void onCamera(BuildContext context) async {
File imgCamera = await ImagePicker.pickImage(source: ImageSource.camera, maxHeight: 500, maxWidth: 500);
if (imgCamera != null) {
Navigator.push(context, new MaterialPageRoute(
builder: (context){
return new Detail(
image: imgCamera,
analytics: widget.analytics,
observer: widget.observer,);}));}}

void onGallary(BuildContext context) async {
File imgGallary = await ImagePicker.pickImage(
source: ImageSource.gallery, maxHeight: 500, maxWidth: 500);
if (imgGallary != null) {
Navigator.push(context, new MaterialPageRoute(builder: (context) {
return new Detail(
image: imgGallary,
analytics: widget.analytics,
observer: widget.observer,);}));}}
```
Google play console ss:
![WhatsApp Image 2019-03-30 at 8 35 04 AM](https://user-images.githubusercontent.com/25891817/55317640-8d0c6600-548e-11e9-8fda-10d8d360e1cc.jpeg)

Please help me resolve this problem. Thanks in advance

**Comment by kaxp** [comment]
After some research and RND I found that that the app was crashing while picking an image from Download folder, So removing the maxheight and maxwidth in the Image_picker stopped the crash but still the path is null.

**Comment by cyanglaz** [comment]
https://github.com/flutter/flutter/issues/28761 might fix your issue. Could you give it a try?

**Comment by cyanglaz** [comment]
@kaxp I saw your closed the issue? Was it fixed in the latest image picker?
