### ISSUE TITLE
webview_flutter crash: Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference

### ISSUE THREAD

**Issue by embpdaniel** [flutter/flutter#30420]
Hi, I have a simple app using Firebase, that displays a webview from `webview_flutter` on my home screen after I log in. When I navigate to the home screen to load the webview, the app crashes. However, if I reload the app after I'm logged in, the app starts at the home page, and the webview loads fine.

## Steps to Reproduce

1. Make sure you are logged out, then log in
2. The app will navigate to the home page
3. The home page appears to load, but when the webview loads the app crashes
4. Reloading the app at this point will allow the webview to load without errors

## Logs

```
[   +6 ms] D/EGL_emulation(24191): eglMakeCurrent: 0xb1db2f40: ver 3 0 (tinfo 0xa8983200)
[  +64 ms] D/        (24191): SurfaceInterface::setAsyncMode: set async mode 1
[  +13 ms] W/zygote  (24191): Attempt to remove non-JNI local reference, dumping thread
[   +7 ms] D/EGL_emulation(24191): eglMakeCurrent: 0xa5d6f0c0: ver 3 0 (tinfo 0x93288890)
[ +119 ms] D/EGL_emulation(24191): eglMakeCurrent: 0xb1db2f40: ver 3 0 (tinfo 0xa8983200)
[   +7 ms] W/zygote  (24191): Attempt to remove non-JNI local reference, dumping thread
[ +162 ms] D/        (24191): SurfaceInterface::setAsyncMode: set async mode 1
[   +3 ms] D/AndroidRuntime(24191): Shutting down VM
[        ] E/AndroidRuntime(24191): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(24191): Process: com.embp.browse, PID: 24191
[        ] E/AndroidRuntime(24191): java.lang.NullPointerException: Attempt to invoke virtual method
'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
[        ] E/AndroidRuntime(24191):     at
org.chromium.ui.display.PhysicalDisplayAndroid.updateFromDisplay(PhysicalDisplayAndroid.java:97)
[        ] E/AndroidRuntime(24191):     at
org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroid
Manager.java:174)
[        ] E/AndroidRuntime(24191):     at
android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal
.java:482)
[        ] E/AndroidRuntime(24191):     at android.os.Handler.dispatchMessage(Handler.java:105)
[        ] E/AndroidRuntime(24191):     at android.os.Looper.loop(Looper.java:164)
[   +4 ms] E/AndroidRuntime(24191):     at android.app.ActivityThread.main(ActivityThread.java:6541)
[        ] E/AndroidRuntime(24191):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(24191):     at
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[        ] E/AndroidRuntime(24191):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

No issues found with flutter analyze command

## Flutter doctor

(I'm using vscode, and not developing for iOS at the moment)

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.2.1 at /Users/naneco/flutter-sdk-1.0.0
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/naneco/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/naneco/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

App files:
[files.zip](https://github.com/flutter/flutter/files/3036670/files.zip)

Thanks in advance!

**Comment by esuvf** [comment]
same problem :(

**Comment by bobdeng** [comment]
same problem.

**Comment by seiwonlee** [comment]
same problem :(

**Comment by yk3372** [comment]
same problem :(

**Comment by karnadii** [comment]
mine too, error collected by crashlytic 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
       at org.chromium.ui.display.DisplayAndroid.updateFromDisplay(DisplayAndroid.java:133)
       at org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:169)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:467)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:234)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Luppakorva** [comment]
Anyone found solution for this? Having the same issue.

**Comment by esuvf** [comment]
in my case, web page crash happened while previous page has a system keyboard shown.system keyboard shown in a new window, which will dismiss when a webpage pushed. guess that  webview update its display from a wrong window.  delay showing webview works for me.

**Comment by Luppakorva** [comment]
@esuvf I'm personally displaying contents of url in a card, if I give it height the crashes are not that common, but it still does it randomly, if I don't give height at all it crashes 90% of the time the card is viewed. Content displayed includes video via <video> tag.

**Comment by esuvf** [comment]
@Luppakorva you can upload your crashed demo.

**Comment by loyasto** [comment]
same problem. when changing screen or change the height of page, webview crashed

**Comment by chuckfu** [comment]
same problem please fix it hurry up

**Comment by ludwiktrammer** [comment]
I'm experiencing the same problem when displaying a modal with a text field above the WebView - the moment the keyboard opens, the app crashes with the `Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference` message.

**Comment by Luppakorva** [comment]
Is there any kind of update for this from Flutter team?

**Comment by tustman** [comment]
same problem please fix it hurry up

**Comment by amirh** [comment]
I believe that this is a chromium bug that was fixed awhile ago by https://chromium-review.googlesource.com/c/chromium/src/+/517913/

I'd expect real devices to have the webview version with the fix, I guess emulator images may be stuck with old webview versions. Is anyone hitting this on a real device? what's the Android webview version your device is using? (you can see that in the application list by clicking "Show system" in the menu)

**Comment by Luppakorva** [comment]
@amirh, yes I'm experiencing this with real device. Is it Android System Webview? The version is 69.0.3497.100

**Comment by amirh** [comment]
@Luppakorva are you hitting this when rotating the device?

**Comment by Luppakorva** [comment]
@amirh nope, am hitting this when I'm scrolling down and widget with webview comes to view / is passed while scrolling, 

I'm displaying a html5 video via webview and that causes the crash though I have experienced this while displaying other content via webview as well. Oddly enough it depends from the quickness you scroll, if you scroll slowly, it works randomly but if you do scroll quickly it's almost certain crash. I'd love to share the project code but unfortunately cannot.

**Comment by amirh** [comment]
Thanks, just to make sure it's the same crash can you share a stack trace (also which device are you using and what Android version).

**Comment by karnadii** [comment]
My app already in production, I use crashlytic to track error. 60% of the crash coming from Samsung with 70% using android 6.

```
34% Galaxy J2 Prime
7% Galaxy J1 Ace
5% Galaxy J3(2016)
15% Other (21)
```

some of my user say that the crash happen when change orientation to landscape or vice versa. and some doen't even need to rotate their device to crash it. (I have a full page with a webview)

in the last 90 days This issue has 64,620 crashes affecting 3,554 users.

if you need more info from my crashlytic, tell me

**Comment by amirh** [comment]
The stack trace points to the  Android WebView issue that was already fixed, but the reports in the wild indicate that very old Android WebView versions are still common enough in the wild.

I sent https://github.com/flutter/plugins/pull/1964 to workaround the bug in the webview plugin.

**Comment by amirh** [comment]
The fix is available starting webview_flutter version 0.3.11+3

**Comment by nemoryoliver** [comment]
Currently using webview_flutter: 1.0.7 and getting this error so I guess it's back?

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
org.chromium.ui.display.DisplayAndroid.updateFromDisplay (DisplayAndroid.java:133)
org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged (DisplayAndroidManager.java:169)
android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage (DisplayManagerGlobal.java:467)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5628)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:853)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:737)
```

**Comment by derjohng** [comment]
webview_flutter: 1.0.7, I meet same crash report.

**Comment by lilianhua** [comment]
webview_flutter: 1.0.7, I also meet same crash report.

**Comment by LiuJQ** [comment]
webview_flutter: 1.0.7, I also meet same crash report.

**Comment by ddikman** [comment]
Same as the others, with `webview_flutter: ^1.0.7` I'm getting the same crash report, especially on Samsung Galaxy J* devices
