### ISSUE TITLE
Flutter Network behind proxy

### ISSUE THREAD

**Issue by tandnd** [flutter/flutter#30426]
Hi, I have a trouble when working with flutter.
My network behind proxy and I configured it. So my emulator's browser easily point to "https://picsum.photos/250?image=9".  But when I call Image.Network in flutter code, it caused SocketException - the connection is refused.

Anyone help, please!

**Comment by tandnd** [comment]
FYI: when I run flutter doctor: 
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.15063], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.32.3)
[√] Proxy Configuration
[√] Connected device (1 available)

**Comment by iapicca** [comment]
Hi @tandnd 
If you are still experiencing this issue 
please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
