### ISSUE TITLE
flutter network video play not response

### ISSUE THREAD

**Issue by shree-krishna-gapi** [flutter/flutter#30427]
E/ExoPlayerImplInternal( 7935): Stop failed.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
