### ISSUE TITLE
Should be able to choose which image to load based on the widget size

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#3043]
I'm writing a widget that needs to know its size. Specifically it wants to know its dimensions so that it can fetch an image of appropriate dimensions from a network API that can return images of arbitrary dimensions, but I think this is a more general need.

I want to allow Flutter to size my widget as appropriate but react to that sizing.

**Comment by Hixie** [comment]
I believe the custom layout and custom paint widgets both report their size. Is that sufficient? I don't fully understand the request.

**Comment by abarth** [comment]
He'd like to decide which network image to load based on the size of the widget (to pick an appropriate number of pixels).  For example, if ImageProvider.loadImage was passed a requested size and device pixel ratio, that would work well for him.

**Comment by Hixie** [comment]
Looks like this requires a whole new widget which is similar to AsyncImage but does the image fetching at layout time rather than at build time.

**Comment by abarth** [comment]
I was thinking we'd change AsyncImage to do that.

**Comment by Hixie** [comment]
That works too. I don't think that class has any customers right now.

**Comment by Hixie** [comment]
I don't plan on doing this any time soon. Please let us know if it is a priority.

**Comment by Hixie** [comment]
The data to do this is plumbed to the asset resolver but not yet used.

**Comment by zoeyfan** [comment]
I am triaging our bug database, and found this from 2017. Are we still planning to do anything? Can we close this now?

**Comment by Hixie** [comment]
Why was this closed??

**Comment by StefanLobbenmeier** [comment]
Pity this bug is still open. I was thinking to use the image provider for this use case, but I discovered that the image provider does not provide the size (null) in my test cases. I think ideally the ImageProvider should be called again when the size becomes known and should check if a new image should be loaded for that size.

**Comment by werainkhatri** [comment]
isn't this a feasible solution to the issue? what am i missing?
(cc @Hixie as you seem to have the context)

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        body: LayoutBuilder(builder: (context, constraints) {
          double width = constraints.maxWidth;
          double height = constraints.maxHeight;
          return Image.network(
            'https://via.placeholder.com/${width.toInt()}x${height.toInt()}',
          );
        }),
      ),
    );
  }
}
```

**Comment by Hixie** [comment]
@werainkhatri Yeah, that's one way to do it. The idea described earlier was to do it automatically in the ImageProvider.

**Comment by Hixie** [comment]
Specifically, this is about implementing the TODO in `_chooseVariant` in `painting/image_resolution.dart`.

**Comment by Hixie** [comment]
Though, I guess that's specifically about AssetImages, whereas this issue is more about NetworkImages...

**Comment by Hixie** [comment]
I guess the problem with network images is you don't know the precise URL that a particular web site will do. Maybe the right solution here is sample code showing a custom NetworkImage-like ImageProvider that implements the ImageConfiguration stuff in its obtainKey.

**Comment by Hixie** [comment]
Ok, I wrote an example that does what the OP is talking about:
    https://github.com/flutter/flutter/pull/131952
