### ISSUE TITLE
flutter channel beta    long time  to  wait

### ISSUE THREAD

**Issue by yuchuan08** [flutter/flutter#30432]
Hello ，My  flutter channel  is   stable，now  I  change it  beta， type in “flutter  channel beta”,but long  long  time，can  you  help  me?

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
