### ISSUE TITLE
assertion in material/input_decorator.dart seems not correct

### ISSUE THREAD

**Issue by fzhangtj** [flutter/flutter#30434]
```
void removeChildRenderObject(RenderObject child) {
    assert(child is RenderBox);
    assert(renderObject.childToSlot.keys.contains(child));
    _updateRenderObject(null, renderObject.childToSlot[child]);
    assert(!renderObject.childToSlot.keys.contains(child));
    assert(!renderObject.slotToChild.keys.contains(slot));
  }
```
The last line  ```assert(!renderObject.slotToChild.keys.contains(slot))``` seems incorrect, since ```slot``` is for ```_RenderDecorationElement```. It should assert !renderObject.slotToChild.keys.contains(renderObject.childToSlot[child]));

**Comment by TahaTesser** [comment]
Hi @fzhangtj 
Are you still experiencing this issue?
if yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
