### ISSUE TITLE
[firebase_admob] - how to use it along with app flavor

### ISSUE THREAD

**Issue by angel1st** [flutter/flutter#30430]
I have my app setup to use flavor for different releases e.g. development, production etc. The essential part of this lays into **app/build.gradle** file and looks like that:

````
    flavorDimensions "flutter-flavours"

    productFlavors {
        development {
            dimension "flutter-flavours"
            applicationIdSuffix ".dev"
        }
        staging {
            dimension "flutter-flavours"
            applicationIdSuffix ".stg"
        }
        production {
            dimension "flutter-flavours"
        }
````
As a result, when I build let's say **development** release, I have got it with following **appId** - `com.example.myapp.dev`, while my **production** release is `com.example.myapp`. So far so good.
Now, I decided to add a firebase_admob plugin to the app. To do so, I made Firebase app into my Firebase account and downloaded corresponding `google-services.json` file required for authentication. Then, I have to put this file into an android/app folder of my app. 
And this is where I found a bummer - basically, I can create `json` file for each of the app flavor, i.e. I can have one json for production and one for development, but I cannot figure out how to put these both into the folder and how gradle will figure out which one to take according to the release flavor.
Any thoughts, hints would be greatly appreciated!

**Comment by angel1st** [comment]
Yet another issue, nobody from the Flutter team cares to answer. I also posted in [Stackoverflow](https://stackoverflow.com/questions/55488355/flutter-firebase-admob-integration-how-to-use-it-along-with-app-flavors) with no luck so far.

**Comment by escamoteur** [comment]
Like this
![image](https://user-images.githubusercontent.com/16635729/65595557-59218180-df95-11e9-9667-8bca2dd53590.png)

Unfortunately we cannot give individual support here.
