### ISSUE TITLE
`flutter --version`/`dart --version` show "None" in place of Dart SDK hash

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#30433]
On master, my output of `flutter --version` and `dart --version` contain `None` where they usually contain hashes.

## Beta:

```
Flutter 1.3.8 • channel beta • https://github.com/DanTup/flutter.git
Framework • revision e5b1ed7a7f (4 weeks ago) • 2019-03-06 14:23:37 -0800
Engine • revision f4951df193
Tools • Dart 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)
```

## Master

```
$ flutter --version
Flutter 1.4.9-pre.20 • channel master • https://github.com/DanTup/flutter.git
Framework • revision a39b55424b (2 hours ago) • 2019-04-03 02:00:41 -0400
Engine • revision cc115500b9
Tools • Dart 2.2.1 (build 2.2.1-dev.3.0 None)

$ dart --version
Dart VM version: 2.2.1-dev.3.0.flutter-None (Tue Apr 2 16:55:41 2019 +0000) on "macos_x64"
```

The `version` file in the SDK folder seems normal, it contains `2.2.1-edge.f6768b6fb3e58bb704aca1e22a7ffd11e7ff07cb`.

This was a convenient way to find out which version of the SDK is in Flutter (to help identify if SDK fixes have been rolled into Flutter yet), I'm not sure if this is intended.

**Comment by jason-simmons** [comment]
Fixed by https://dart-review.googlesource.com/c/sdk/+/99266
