### ISSUE TITLE
Hot reload fails when view references static string

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [flutter/flutter#30442]
I noticed that flutter didn't hot reload changes to my Strings class which contains static variables. However it does reload them when they are const. Why?

To reproduce:
```
void main() => runApp(BugApp());

class BugApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Column(
          children: <Widget>[
            Text(Strings.doesntwork),
            Text(Strings.works),
          ]
        ),
      ),
    );
  }
}

class Strings {
  static String doesntwork = "nope";
  static const String works = "yup";
}
```

Run it, then change both strings, and hot reload. Only one changes.

**Comment by jason-simmons** [comment]
Static field initializers are not rerun during a hot reload.  See https://flutter.dev/docs/development/tools/vs-code#hot-reloads-vs-hot-restarts

**Comment by OliverCulleyDeLange** [comment]
Thanks for the link, Interesting that it works for static constants. Closing
