### ISSUE TITLE
Generate and publish docs for flutter_driver

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3045]
Super cool package here: https://github.com/flutter/flutter/tree/master/packages/flutter_driver

Let's add it to our docs here: docs.flutter.io

**Comment by sethladd** [comment]
cc @yjbanov for driver
cc @eseidel for the buildbot infra and can help point to where the scripts that generate the docs are now

**Comment by eseidelGoogle** [comment]
https://chromium.googlesource.com/chromium/tools/build.git/+/master/scripts/slave/recipes/flutter/flutter.py#77 is our docs generation.
https://github.com/flutter/flutter/tree/master/infra has docs on how to edit these.

**Comment by Hixie** [comment]
this should probably be done via https://github.com/flutter/flutter/issues/2399

**Comment by devoncarew** [comment]
docs here: http://docs.flutter.io/flutter_driver/flutter_driver-library.html
