### ISSUE TITLE
Gallery app bug - "API Documentation" action broken 

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#30450]
Steps to reproduce 
1. Launch app
2. Tap Material
3. Tap "Bottom app bar" or most/all others
4. Tap the list looking thing with tooltip of "API Documentation"
Expected result: Something in the middle of the screen
Observed result: hamburger three lines in upper left, label (e.g. Bottom Appbar) in app bar title, permanent snackbar with flutter version info at the bottom, middle of screen empty white canvas

**Comment by HansMuller** [comment]
I can reproduce this.

Gallery demos use the current (5.0.2) version of the Dart [url launcher](https://pub.dartlang.org/packages/url_launcher) package.

**Comment by HansMuller** [comment]
Filed a url_launcher plugin issue: https://github.com/flutter/flutter/issues/30464
