### ISSUE TITLE
Support output resolution and compression options in Camera plugin

### ISSUE THREAD

**Issue by fvisticot** [flutter/flutter#30459]
- By default this plugin generates very big image 6MB on my iPhoneX
- There is currently no good Dart plugin to resize the image (takes to much time)
- Solution is to use native plugin but those plugin does not work with compute
- It is a currently a pb when we want to upload an image coming from camera to a server

Regarding those 3 remarks, it would be fine to provide "natively" the image with the right resolution and compression.

**Comment by quentinleguennec** [comment]
Hi @fvisticot. I added a way to control video and picture capture quality. 
You can check the PR here:
https://github.com/flutter/plugins/pull/1403
Suggestions are welcome. Don't hesitate to leave a comment to push the review process if that works for you.

**Comment by fvisticot** [comment]
Tx for your PR.
In addition I think i would be fine to allow JPEG compression value. It is set to 1 (max quality) in iOS plugin.
This option would avoid to compress the image a second time.

**Comment by mklim** [comment]
This should be fixed in 0.5.3.
