### ISSUE TITLE
Video play on custom embedder

### ISSUE THREAD

**Issue by galvesribeiro** [flutter/flutter#30467]
Hello folks!

As I've already mentioned on other issues, we're porting flutter to run on custom hardware that is not iOS or Android and also to have a proper embedder for RaspberryPI/Asus Tinkerboard S.

So far we've successfully ported basic engine to the target devices and now we're looking to see how to use the [video_player widget](https://pub.dartlang.org/packages/video_player) widget on our custom port/embedder.

Can someone point me to the directions on how to implement video support?

Thank you!

**Comment by stuartmorgan** [comment]
https://github.com/flutter/engine/pull/7087 and the example linked from it (which uses that API to implement video_player on macOS) would likely be useful references.

**Comment by galvesribeiro** [comment]
Thanks @stuartmorgan!

I've got a lot of good info from @slightfoot and Luigi Rosso (sorry didn't found the alias) from the Flutter Study Group on Slack and I'm working on it now.

Will update the issue once I have a final solution.

Thanks!

**Comment by stuartmorgan** [comment]
Since there's no specific issue here (other than the fact that the embedder API could definitely use more documentation, which is already tracked in another issue), I'm going to close this.
