### ISSUE TITLE
OverlayEntry.remove() causes silent failure

### ISSUE THREAD

**Issue by joeythomaschaske** [flutter/flutter#30479]
If you are using OverlayEntry and call `remove()` on it after is has been removed all code after the `remove()` call will not be called and no error is shown in the console.

```
void search(String query) {
  if (_overlayEntry != null) {
    _overlayEntry.remove();
    //anything after this will not be called if this has been called once before
    _overlayEntry = null;
  }

  List resultingSet = List();
  if (query != null && query.length > 0) {
    resultingSet = widget.items.where((item) {
      return item.name.toString().toLowerCase().contains(query.toLowerCase());
    }).toList();
  }
  if (resultingSet.length == 0 && query != null && query.length > 0 && widget.defaultItem != null) {
    resultingSet.add(widget.defaultItem);
  }
 
  setState(() {
    matchingItems = resultingSet;
  });
  print('set');

  Widget list = buildList();
  _overlayEntry = OverlayEntry(
    builder: (context) {
      return Positioned(
        child: Container(
          constraints: BoxConstraints(
            maxHeight: 200,
            maxWidth: MediaQuery.of(context).size.width
          ),
          child: list,
        ),
      );
    }
  );

  if (resultingSet.length > 0) {
    print('inserting');
    Overlay.of(context).insert(_overlayEntry);
  }
}
```

The example above is for a autocomplete search field. I know the documentation says to avoid calling `remove()` more than once, however, I think it should throw an error and be more obvious

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
