### ISSUE TITLE
Cannot open file, path = '<>/artifacts/engine/darwin-x64/vm_isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by LouisEvans** [flutter/flutter#30474]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target /Users/louisevans/StudioProjects/test_flutter/lib/main.dart --verbose --filesystem-scheme org-dartlang-root --compilation-trace-file compilation.txt --depfile /Users/louisevans/StudioProjects/test_flutter/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --asset-dir /Users/louisevans/StudioProjects/test_flutter/build/app/intermediates/flutter/debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/louisevans/Desktop/Flutter/flutter/bin/cache/artifacts/engine/darwin-x64/vm_isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale en-GB)
    • Flutter version 1.2.1 at /Users/louisevans/Desktop/Flutter/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/louisevans/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by christopherfujino** [comment]
@LouisEvans are you still in this state?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by Zheng7426** [comment]
same problem here....

**Comment by jmagman** [comment]
@Zheng7426 Can we get the output of `flutter doctor -v`?

**Comment by Zheng7426** [comment]
> @Zheng7426 Can we get the output of `flutter doctor -v`?

Hey mate, this problem has been solved. Turned out I had two paths in the $PATH file.

**Comment by eduardn1** [comment]
> > @Zheng7426 Can we get the output of `flutter doctor -v`?
> 
> @jmagman Hello, this problem has been solved. Turned out I had two paths in the $PATH file.

How did you exactly fiexd it. I'm having the exact same problem. I have built and App - > Release after that i can't even RUN the project again in Android Studio. 

**I get this**
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Target debug_android_application failed: FileSystemException: Cannot copy file to '/Users/eduard/Desktop/sudapp/build/app/intermediates/flutter/debug/flutter_assets/isolate_snapshot_data', path = '/Users/eduard/Desktop/flutter/bin/cache/artifacts/engine/darwin-x64/isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/eduard/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/eduard/Desktop/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1


Any idea ?
