### ISSUE TITLE
Flutter tool should release cache lock when killed by a signal.

### ISSUE THREAD

**Issue by fdtl01** [flutter/flutter#30478]
Some problems as follows:
1.Errors occured when run flutter packages get. 
2.No.1 errors occured, I cannot delete lockfile

**Comment by ffey** [comment]
maybe you should shutdown the process of dart. then retry your command.

**Comment by TinoJHB** [comment]
Shutdown the processes of dart. then retry flutter packages get. worked!!

**Comment by xster** [comment]
From offline comment: it's easy to run into in China when the pub mirror is slow and the user ^-c out of the flutter tool and the lockfile is stuck. Consider somehow cleaning when process killed.

**Comment by zanderso** [comment]
Possibly in `handler` here:
https://github.com/flutter/flutter/blob/2a4cdc54d010d110bbf8ec1b1e513614b4627bb9/packages/flutter_tools/lib/src/runner/flutter_command.dart#L547

**Comment by dratushnyy** [comment]
@zanderso 
Thank you for triaging this issue.
I created a pull request for it https://github.com/flutter/flutter/pull/52194

**Comment by surapuramakhil** [comment]
Hey , I am quickly looking for good first issue to start with. but I found that lot of open issues have a PR's and merged to master. 
This issue an ideal example of above saying
is there any label that i can identify as PR raised so that I can skip and rather than figuring out by going through issue

**Comment by daadu** [comment]
@fdtl01 This issue should be closed as #52194 has fixed it.

**Comment by daadu** [comment]
@jmagman This issue should be closed as #52194 has fixed it.
