### ISSUE TITLE
'flutter run' command crashes

### ISSUE THREAD

**Issue by eliavco** [flutter/flutter#30485]
Hello,
I started developing in flutter last week,
I couldn't code even not a single line...
I installed flutter, Android SDK, emulators, Gradle, and everything but I still can't properly run the command "flutter run", hit the play button on android studio or "start without debugging" on VSCode.
I really need help about what to do because I can't find help anywhere. I really tried everything.
I also tried connecting real devices but when I run "flutter devices" it says "no devices connected" and yes, I allowed transferring files between the computer and the phone.
My flutter doctor says everything looks fine.

## Logs

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Oops; flutter has exited unexpectedlSending crash report to Google.
Crash report sent (report ID: 5a9b4e39b3f297df)
Initializing gradle...                                                  Crash report written to C:\Users\PATH\TO\DIRECTORY\flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale
    en-IL)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.32.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
In the error, it says:

> Crash report written to C:\Users\PATH\TO\DIRECTORY\flutter_05.log;

Can you post the error/stack logged in that file?
