### ISSUE TITLE
FlutterTts plugin not giving call back for onRangeStart

### ISSUE THREAD

**Issue by satish754ss** [flutter/flutter#30489]
I am using FlutterTts to read the text, and I need to highlight the spoken text, which is possible if an onRangeStart return calls back. which not giving, otherwise, all method is giving callback.

` private UtteranceProgressListener utteranceProgressListener = new UtteranceProgressListener() {

     @Override
     public void onStart(String utteranceId) {
       channel.invokeMethod("speak.onStart", true);
       Log.d("", "Java: On Start");
     }

    @Override
    public void onDone(String utteranceId) {
      channel.invokeMethod("speak.onComplete", true);
    }

    @Override
    @Deprecated
    public void onError(String utteranceId) {
      channel.invokeMethod("speak.onError", "Error from TextToSpeech");
    }

    @Override
    public void onError(String utteranceId, int errorCode) {
      channel.invokeMethod("speak.onError", "Error from TextToSpeech - " + errorCode);
    }

    @Override
    public void onAudioAvailable(String utteranceId, byte[] audio) {
      Log.d("", "Java:" + utteranceId);
    }

    public void onRangeStart(String utteranceId, int start, int end, int frame) {
      Log.d("", "Java: onRangeStart" + start);
    } };`

**Comment by satish754ss** [comment]
Can anyone answer this question?

**Comment by satish754ss** [comment]
Please give help, I am stuck this issue, API Level 27 onRangeStart is giving the callback but for all languages.

**Comment by escamoteur** [comment]
I don't know if the issue still exists, but this isn't a Google package so please file issues here https://github.com/dlutton/flutter_tts/issues
