### ISSUE TITLE
[firebase_messaging] InvalidRegistration and NotRegistered error when pushing notification on iOS

### ISSUE THREAD

**Issue by worldofsites** [flutter/flutter#30486]
I have done all steps at the following link [firebase messaging](https://pub.dartlang.org/packages/firebase_messaging#ios-integration):

![image](https://user-images.githubusercontent.com/23352829/55534333-53319e80-56de-11e9-926f-00520b5eee01.png)
But when push message to iOS physical device I have got the following errors:
First call:
```
{
    "multicast_id": 4849464581066354269,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "InvalidRegistration"
        }
    ]
}
``` 
Second and next same calls:
```
{
    "multicast_id": 8488879606012873599,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "NotRegistered"
        }
    ]
}
```
I have checked [docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref#table9) and can confirm that the firebase server key and device token is valid. I have tried create new firebase token on device, reinstall app, readd APN certificate, but nothing helps.

Used http pushing notification way:
```
DATA='{"notification": {"body": "this is a body","title": "this is a title"}, "priority": "high", "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, "to": "<FCM TOKEN>"}'
curl https://fcm.googleapis.com/fcm/send -H "Content-Type:application/json" -X POST -d "$DATA" -H "Authorization: key=<FCM SERVER KEY>"
```

Some screens and info:
![image](https://user-images.githubusercontent.com/23352829/55535559-c7ba0c80-56e1-11e9-926f-f5abb1e82bfd.png)
![image](https://user-images.githubusercontent.com/23352829/55535563-cbe62a00-56e1-11e9-8f72-d9773e477507.png)
![image](https://user-images.githubusercontent.com/23352829/55535573-ce488400-56e1-11e9-8bb8-e37395e8f370.png)

```
Ios Settings registered: PushNotificationSettings {sound: true, alert: true, badge: true}
```
```
Doctor summary (to see all details, run flutter doctor -v): 
[✓] Flutter (Channel master, v1.4.9-pre.27, on Mac OS X 10.13.6 17G5019, locale en-US)
[✗] Android toolchain - develop for Android devices 
 ✗ Unable to locate Android SDK. Install Android Studio from: https://developer.android.c... On first launch it will assist you in installing the Android SDK components. (or visit https://flutter.io/setup/#a... for detailed instructions). If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location. You may also want to add it to your PATH environment variable.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1) 
[!] Android Studio (not installed) 
[✓] Connected device (1 available)! 

Doctor found issues in 2 categories.
```
```
  barcode_scan: 1.0.0
  shared_preferences: 0.5.1+2
  http: 0.12.0+1
  device_info: 0.4.0+1
  flutter_speed_dial: 1.1.1
  date_format: 1.0.6
  font_awesome_flutter: 8.4.0
  image_picker: 0.5.0+9
  modal_progress_hud: 0.1.3
  url_launcher: 5.0.2
  tuple: 1.0.2
  cached_network_image: 0.7.0
  intl_translation: 0.17.3
  flutter_html: 0.9.6 
  flutter_pagewise: 1.2.3
  flutter_masked_text: 0.8.0
  permission_handler: 3.0.0
  firebase_messaging: 4.0.0+1
```

### **All works good on android.**

**Comment by worldofsites** [comment]
When app start I see following logs:
```
2019-04-04 13:28:43.430259+0700 Runner[17749:19096892] Configuring the default Firebase app... 
2019-04-04 13:28:43.431202+0700 Runner[17749:19097031] 5.20.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist. 
2019-04-04 13:28:43.665126+0700 Runner[17749:19097033] 5.20.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50800000 started 
2019-04-04 13:28:43.671104+0700 Runner[17749:19097033] 5.20.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r) 
2019-04-04 13:28:43.763120+0700 Runner[17749:19096892] Configured the default Firebase app __FIRAPP_DEFAULT.
```
Is it somehow related?

**Comment by ianko** [comment]
+1

**Comment by worldofsites** [comment]
@zoechi 
Could you please tell who to contact with that issue?
Thanks

**Comment by sbJonas** [comment]
Hi,
i got the same problem. I tried not to create SSL certificates for the APP Id, just because it is not mentioned in the documentation ("Push Notifications should be Configurable"), but this did not change anything. Then after 3 times recreating everything (flutter project, fcm project, Apple  App id + key) i suddenly dont get "NotRegistered" errors anymore, but notification callbacks are still not called on my iPad, though it looks like the message is sent.
I tried also to set "FirebaseAppDelegateProxyEnabled" to NO in the info.plist and generated the App id via XCode and manually via the Apple developer account, which also did not change anything.
(On Android everything is working fine)

Since i am obviously quite new to flutter and app development, i dont know how to get further information about what could be the problem.
Is there a way to test the APN service directly from flutter? (without fcm) 
Would be writing a native iOS App just for testing the APN service a good idea?
Is there a way to check if the connection between Google FCM and Apple APNs is correctly working?

Thanks for any help =)

**Comment by sbJonas** [comment]
Wow...
spent 2 days just to recognize everything works fine after a reboot of the iPad + reconnect to WiFi + reinstalling the app.

**Comment by PurnimaNaik** [comment]
I was facing the same issue. Here is how I fixed it (iOS specific, android was working out of the box)-

 1. Uninstall the app from your phone
 2. Clear ALL the tokens stored in your database for this particular account(or however you have set it up in your backend. In my case, tokens are tied to the account)
 3. In componentDidmount-

      async componentDidMount() {
        this.checkPermission();
        this.createNotificationListeners();
      }

4.

      async checkPermission() {
        const enabled = await firebase.messaging().hasPermission();
        if (enabled) {
          this.getToken();
        } else {
          this.requestPermission();
        }
      }

      async requestPermission() {
        try {
          await firebase.messaging().requestPermission();
          // User has authorised
          this.getToken();
        } catch (error) {
          // User has rejected permissions
          console.log('permission rejected');
        }
      }

      async getToken() {
        try {
          const enabled = await firebase.messaging().hasPermission();
          if (!enabled) {
            await firebase.messaging().requestPermission();
          }
    
          const fcmToken = await firebase.messaging().getToken();
          if (fcmToken) {
            console.log("got token");
            console.log('fcm token:', fcmToken); //-->use this token from the console to send a post request via postman
            this.setState({ fcmToken });
            return fcmToken;
          }
        } catch (error) {
          console.warn('notification token error', error);
        }
      }

5.

     async createNotificationListeners() {
        /*
        * Triggered when a particular notification has been received in foreground
        * */
        this.notificationListener = firebase.notifications().onNotification((notification) => {
            const { title, body } = notification;
            this.showAlert(title, body);
        });
      
        /*
        * If your app is in background, you can listen for when a notification is clicked / tapped / opened as follows:
        * */
        this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
            const { title, body } = notificationOpen.notification;
            this.showAlert(title, body);
        });
      
        /*
        * If your app is closed, you can check if it was opened by a notification being clicked / tapped / opened as follows:
        * */
        const notificationOpen = await firebase.notifications().getInitialNotification();
        if (notificationOpen) {
            const { title, body } = notificationOpen.notification;
            this.showAlert(title, body);
        }
        /*
        * Triggered for data only payload in foreground
        * */
        this.messageListener = firebase.messaging().onMessage((message) => {
          //process data message
          console.log(JSON.stringify(message));
        });
      }

6. Finally, use the token that you see in the console as a value for the "to" key in your post request. You should no longer see the "notRegistered" error and should be getting push notifications.
Done!!

For a more detailed setup/citation-
https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

**Comment by AlexBacich** [comment]
@worldofsites, have you been able to solve the problem at the end? I'm facing exactly the same problem and same steps.

**Comment by AlexBacich** [comment]
@escamoteur , Since worldofsites isn't the only one facing the same issue - maybe its worth giving the issue a try? 

Anyway, posted on StackOverflow too. 
https://stackoverflow.com/questions/60151597/ios-flutter-not-getting-push-notifications

p.s. if not - what would you recommend?

**Comment by AlexBacich** [comment]
After two days of trying pushes just started working. Seems like it was some problem on APNS \ FCM side.

**Comment by worldofsites** [comment]
> @worldofsites, have you been able to solve the problem at the end? I'm facing exactly the same problem and same steps.

@AlexBacich, fixed by using onesignal instead of firebase :) but onesignal is used firebase for messaging as well

**Comment by itsJoKr** [comment]
I had the same problem. The tokens just would not get registered with firebase.

But when I'm building from the XCode it works. It doesn't work from the Studio/VSCode. Not really sure why but I can always reproduce this issue.

**Comment by Yirmerah** [comment]
Hi, 
Did you find a solution ?
I'm facing the same problem, it work fine for android but when it's about IOS, i always get the  Not registered token error.
Check my stackoverflow post for more info : 
https://stackoverflow.com/questions/62476783/error-messaging-registration-token-not-registered

**Comment by sharmavishal914** [comment]
Hi Guys,

Recently I faced same issue. For me after installing diawi link the token was saved on the server & once notification fired on that token then it shows "notRegisted" error.

The issue was on creating IPA. I was creating IPA from xcode & the uploading to diawi but you need to create build using flutter command & follow these steps

1) Generate your iOS build by below command
    flutter build ios --debug

2) You will found exact path of your Runner.app Ex.
-> Built /Users/UserName/Documents/AppName/build/ios/iphoneos/Runner.app. Just find this Runner.app file and do copy/paste it to Desktop.

3) Create folder name is "Payload" (case-sensitive) on Desktop

4) Move your Runner.app File in the "Payload" folder.

5) Compress Payload folder to default .zip

6) Convert/rename Payload.zip to Payload.ipa

7) Upload ipa to diawi & test, Everything should be working now.
