### ISSUE TITLE
ProcessException: Process "/android/gradlew" exited abnormally:

### ISSUE THREAD

**Issue by theromie** [flutter/flutter#30498]
After running flutter app it gives me following error

* Error running Gradle:
ProcessException: Process "/home/user/Documents/development/app/android/gradlew" exited abnormally:

> Configure project :connectivity

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':connectivity'.
> Could not open cp_proj remapped class cache for c7my3okh4e3lb03m55qkyzr23 (/home/app/.gradle/caches/4.10.2/scripts-remapped/build_7666ifimqm1l9c3qt0ox1mpr/c7my3okh4e3lb03m55qkyzr23/cp_proj70b1361a260e0ceb212a59c45f680ebd).
   > Unexpected lock protocol found in lock file. Expected 3, found 0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
  Command: /home/user/Documents/development/app/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by theromie** [comment]
after that if i run flutter doctor 


[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_IN)
    • Flutter version 1.2.1 at /home/user/Documents/development/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Mi A1 • 7341d6280704 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by kashifg4171** [comment]
install jdk.
OR open Gradle-wrapper.jar

**Comment by ezraaaa** [comment]
is there any solution to this? I ran into this error on all flutter channels

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by p0sitive** [comment]
i also have this problem

`
* Error running Gradle:
ProcessException: Process "xxx/android/gradlew" exited abnormally:
> Configure project :flutter
  Command: xxx/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.
`

**Comment by escamoteur** [comment]
@p0sitive could you please add the output of flutter doctor -v here?

Does this also happen if you create a new project?

**Comment by p0sitive** [comment]
flutter doctor list were all ok .
it’s not happened in create a new project.

ps: my project is flutter code mix whit android native code, what run in Android Studio 

i found some solution in my project:

1.update custom flutter plugin project  **kotlin gradle plugin version** 
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':crash_reporter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
```
(this not show in Run Console ,but my teammate remands me of this. - -\)

2.check android native project code ,it may be modified


（forgive my pool English）

**Comment by escamoteur** [comment]
@p0sitive so can you work with that fix?
please add flutter dorcotr so that we use which versions you are using.

**Comment by p0sitive** [comment]
> @p0sitive so can you work with that fix?
> please add flutter dorcotr so that we use which versions you are using.

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/xxx/Library/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • MI CC 9 • f5ca2138 • android-arm64 • Android 9 (API 28)

**Comment by brandonlaguna** [comment]
Hi mate, I wanna know if your have still this problem. 
Or you resolve this, just i have a big problem with this.

So thanks...

**Comment by escamoteur** [comment]
@brandonlaguna I'm sorry to hear that. Is your project a mixed project too or a pure Flutter project?
Could you please add the output of `flutter doctor .v` here?

**Comment by escamoteur** [comment]
For all here I recommend creating a new project and copy all your own files into that this helps quite often with gradle related issues.

**Comment by Lyuji282** [comment]
How about updating kotlin version?

**Comment by theromie** [comment]
I have fixed this issue by recreating app
