### ISSUE TITLE
App renders unusable after loading image

### ISSUE THREAD

**Issue by Sh1d0w** [flutter/flutter#30495]
## Steps to Reproduce

1. Create a sample list view
2. Load image in a page with `Image.asset` or `Image.network`. It is reproducible either with png or jpg images.
3. App renders broken right after the image is loaded for first time
4. If you scroll up, removing the loaded image from the viewport and scroll back to it it will render ok.

## Logs

```
There are no errors or exceptions thrown
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-BG)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)
```

**Comment by HansMuller** [comment]
It would really help if you could provide a small self-contained app that demonstrates this problem. Thanks!

**Comment by Sh1d0w** [comment]
This seems the same problem as reported here https://github.com/flutter/flutter/issues/28227

I can confirm it is fixed on the master branch. I hope it gets to stable channel soon.
