### ISSUE TITLE
Android HostApduService class equivalent

### ISSUE THREAD

**Issue by eredacokmerke** [flutter/flutter#30492]
Hi,
Is there any equivalent class in Flutter to Android's `HostApduService` class ?
for reference :
[https://developer.android.com/reference/android/nfc/cardemulation/HostApduService.html](https://developer.android.com/reference/android/nfc/cardemulation/HostApduService.html)
[https://developer.android.com/guide/topics/connectivity/nfc/hce](https://developer.android.com/guide/topics/connectivity/nfc/hce)

**Comment by escamoteur** [comment]
This isn't a Flutter topic.
Please check these
https://pub.dev/packages?q=nfc
