### ISSUE TITLE
Avoid resizing PageView children when keyboard shows up

### ISSUE THREAD

**Issue by UnaDeKalamares** [flutter/flutter#30494]
Hi,

First of all, apologies if this isn't the correct place to post this.

I've read in other issues, as well as in some StackOverflow posts and in the source code, that PageView forces its children to match the viewport size (or a fraction). With that said, I found out that, whenever the keyboard is displayed, the PageView resizes to match the remaining screen space, even when it was invoked by a TextField inside an AlertDialog (I mean, having the PageView partially covered by that AlertDialog).

Might it be possible to, at least, modify this behaviour via a flag? I've seen that this issue is related to using `android:windowSoftInputMode="adjustResize"` in the AndroidManifest (I'm not sure how it's done in iOS), and I understand that avoid using it is quite dificult, while maintaining the resize behaviour under demand.

Thanks!

**Comment by HansMuller** [comment]
Assuming that you're building a MaterialApp with a Scaffold...

By default, the Scaffold resizes to make room for the keyboard. You can override that with: https://docs.flutter.io/flutter/material/Scaffold/resizeToAvoidBottomInset.html

**Comment by UnaDeKalamares** [comment]
Thank you for your response. I forgot to mention that I already tried that, but it doesn't work with PageView when the keyboard appears. Hence this issue.

**Comment by HansMuller** [comment]
Could you provide a small self-contained app that demonstrates the problem? On the face of it, it's not clear why PageView would resize when the keyboard appears (assuming that the Scaffold body doesn't resize).

**Comment by UnaDeKalamares** [comment]
Ok, now I've found my issue. The thing is, this content resides inside another widget with a BottomNavigationBar. Of course, that Scaffold also needs to set `resizeToAvoidBottomPadding: false`, otherwise whenever the keyboard appears the inner widget will resize.

Thank you very much for your time! I hope this might help somebody else facing a similar situation.
