### ISSUE TITLE
Android Studio下新建一个 Flutter App，push到GitHub后再pull到本地，其中的*.java文件不被识别

### ISSUE THREAD

**Issue by 214682893** [flutter/flutter#30508]
From URL: https://www.flutterchina.club/get-started/setup_windows.md

Android Studio下新建一个 Flutter App，push到GitHub后再pull到本地，其中的*.java文件不被识别

![flutter下java不被识别](https://user-images.githubusercontent.com/30226414/55573771-632c9b00-573d-11e9-86ec-2721b8607a2f.PNG)

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
