### ISSUE TITLE
Use File class constructor and get unknown message as For input string: "1,xxx"  

### ISSUE THREAD

**Issue by goldenhuang** [flutter/flutter#30514]
## Steps to Reproduce

1. Just create a simple flutter app
2. Put the files into specific folder of the external storage of Android phone
3. In the app try to create a Loop to create one File(<file path>) for each file in the folder
4. The you will see the output message as For input string: "1,xxx" in the debug console

Since potentially the messages can be periodic and come with variant number as "xxx", I just wonder that it may cause some performance impact or side effects in the operations of the app. 
Anyone can help to tell why the message comes out.

**Comment by HoX** [comment]
I am having the same behaviour. Did you find anything about it?

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
