### ISSUE TITLE
MediaQuery.devicePixelRatio doesn't update if display settings change while app is running

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#30518]
If a user changes the device size settings (on Android Q: Settings -> Accessibility -> Display size) while a Flutter app is still running, the changes to `MediaQuery.devicePixelRatio` will not be propagated up to the app.

For example:

```dart
import 'package:flutter/material.dart';

void main() => runApp(DevicePixelRatioBug());

class DevicePixelRatioBug extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DevicePixelRatioPage(),
    );
  }
}

class DevicePixelRatioPage extends StatefulWidget {
  @override
  _DevicePixelRatioPageState createState() => _DevicePixelRatioPageState();
}

class _DevicePixelRatioPageState extends State<DevicePixelRatioPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Device pixel ratio bug'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Text('devicePixelRatio = ${MediaQuery.of(context).devicePixelRatio}'),
            Text('textScaleFactor = ${MediaQuery.of(context).textScaleFactor}'),
          ],
        ),
      ),
    );
  }
}
```

When run the default settings will show something like:
![Default settings](https://user-images.githubusercontent.com/7573289/55583154-106bc880-56d6-11e9-9bba-37dd4e4b4e9e.png)

Then while this is still running in the background, update the settings for the display. For example setting them to the largest:
![Settings](https://user-images.githubusercontent.com/7573289/55583160-1661a980-56d6-11e9-8706-a18bbc24a5f4.png)

Then switch back to the app and you will see the devicePixelRatio has not been updated (but if you also change the textScaleFactor, it does work properly):
![After update](https://user-images.githubusercontent.com/7573289/55583231-36916880-56d6-11e9-915b-9a5bd0e970c5.png)

If you kill the app and restart it, it will then show the right values:
![After restart](https://user-images.githubusercontent.com/7573289/55583256-4446ee00-56d6-11e9-925b-7ff88111c0b9.png)

**Comment by TahaTesser** [comment]
Hi @ghost

Running the code sample on, this issue seems to be resolved

```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```
<details>
 <summary>GIF Preview</summary>

![5e6782528abbe260368245](https://user-images.githubusercontent.com/48603081/76310804-87054300-62f5-11ea-89c4-2c4d34ac1849.gif)

</details>

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
