### ISSUE TITLE
Flutter IOS app crashes just after starting

### ISSUE THREAD

**Issue by Sjosh-cronJ** [flutter/flutter#30548]
I am running into an issue while running flutter app in ios.

*** First throw call stack: (

0 CoreFoundation 0x000000010f1941bb __exceptionPreprocess + 331

1   libobjc.A.dylib                     0x000000010e2b6735 objc_exception_throw + 48
2   CoreFoundation                      0x000000010f1b2f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                      0x000000010f198ed6 ___forwarding___ + 1446
4   CoreFoundation                      0x000000010f19ada8 _CF_forwarding_prep_0 + 120
5   UIKitCore                           0x0000000118a3d34a -[UIApplication _checkBackgroundRefreshAPIAdoption] + 174
6   UIKitCore                           0x0000000118a19b52 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1402
7   UIKitCore                           0x00000001182384e9 __111-[__UICanvasLifecycleMonitor_Compatab<…>
I am not getting why this error coming need to fix.

**Comment by kf6gpe** [comment]
Can you work this down to a minimal reproducible case with your application so one of the team can take a look at it in more detail? There's unfortunately not a lot to go on here. Thanks!
