### ISSUE TITLE
 How can I customize my camera ?

### ISSUE THREAD

**Issue by Maketele** [flutter/flutter#30544]
I'm inserting a camera in my app, ImagePicker only accesses the camera but doesn't allow me to customize(like the whatsApp camera) the preview screen or maybe I don know how to do it. Any suggestion of how I can do this?

**Comment by Maketele** [comment]
> I'm inserting a camera in my app, ImagePicker only accesses the camera but doesn't allow me to customize(like the whatsApp camera) the preview screen or maybe I don know how to do it. Any suggestion of how I can do this?

**Comment by rmtmckenzie** [comment]
I think what you're looking for is probably the [camera plugin](https://pub.dartlang.org/packages/camera).

**Comment by Maketele** [comment]
Thats only for ImagePicker. But how can I customise the Camera to look different that the one on my phone.

**Comment by rmtmckenzie** [comment]
Have you taken a close look at the camera plugin? It gives you a CameraPreview widget that you can wrap with whatever UI elements you want,and then you can call methods on the controller like takePicture, startVideoRecording, etc. See their in depth example: https://github.com/flutter/plugins/blob/master/packages/camera/example/lib/main.dart.

If you're wanting to replicate the WhatsApp camera you'll have to do some work but that's the best way I can think of.

If that doesn't do what you need maybe I'm not understanding what you're asking. But this seems like a question for StackOverflow or one of the flutter chatrooms more than a bug in the framework....

**Comment by Maketele** [comment]
This is very helpful. Thank you
