### ISSUE TITLE
Add support to use 'mailto:' and 'telto:' in flutter_webview 

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#30549]

**Comment by techximumsolutions** [comment]
https://stackoverflow.com/q/56421218/9489285

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

**Comment by Sarthaktydy** [comment]
> Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

Hey, I've changed the question. It's more of a feature request than a question.

**Comment by escamoteur** [comment]
I changed the title because the problem with the input tags is already known

**Comment by stuartmorgan** [comment]
Closing as obsolete; the navigation delegate callback provides an opportunity to handle schemes that the webview can't.
