### ISSUE TITLE
helping "...provide substantially more information" (EXCEPTION CAUGHT BY WIDGETS LIBRARY)

### ISSUE THREAD

**Issue by bobwiller** [flutter/flutter#30552]
Stack trace is below, but this exception was being thrown because I was building a Widget tree like so:

```
Widget build(BuildContext context) {
    return Material(
        elevation: 6.0,
        child: Container(
            color: Colors.white,
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: <Widget>[_buildMyColumn()]
            ),
        ),
    );
}
```
My _buildMyColumn() method was then building the Widets of that Column().  However, I was missing the `return` statement.  Once I added that, everything worked fine.  Hope this helps!

I/flutter (28769): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28769): The following assertion was thrown building UnassignedDockControl(dirty, state:
I/flutter (28769): _UnassignedDockControlState#dda85):
I/flutter (28769): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1655 pos 14:
I/flutter (28769): '!children.any((Widget child) => child == null)': is not true.
I/flutter (28769): 
I/flutter (28769): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28769): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28769): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28769):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28769): 
I/flutter (28769): When the exception was thrown, this was the stack:
I/flutter (28769): #2      new MultiChildRenderObjectWidget 
package:flutter/…/widgets/framework.dart:1655
I/flutter (28769): #3      new Flex 
package:flutter/…/widgets/basic.dart:3575
I/flutter (28769): #4      new Column 
package:flutter/…/widgets/basic.dart:4102
I/flutter (28769): #5      _UnassignedDockControlState.build 
package:rooming/…/components/unassigned_dock_control.dart:19
I/flutter (28769): #6      StatefulElement.build 
package:flutter/…/widgets/framework.dart:3825
I/flutter (28769): #7      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3736
I/flutter (28769): #8      Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #9      StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #10     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #11     SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #12     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #13     SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #14     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #15     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #16     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #17     StatelessElement.update 
package:flutter/…/widgets/framework.dart:3796
I/flutter (28769): #18     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #19     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #20     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #21     ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #22     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #23     RenderObjectElement.updateChildren 
package:flutter/…/widgets/framework.dart:4601
I/flutter (28769): #24     MultiChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4992
I/flutter (28769): #25     Element.updateChild 
I/flutter (28769): #40     RenderObjectElement.updateChildren 
package:flutter/…/widgets/framework.dart:4601
I/flutter (28769): #41     MultiChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4992
I/flutter (28769): #42     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #43     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #44     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #45     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #46     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #47     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #48     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #49     ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #50     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #51     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #52     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #53     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #54     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #55     SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #56     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #57     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #58     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #59     StatelessElement.update 
package:flutter/…/widgets/framework.dart:3796
I/flutter (28769): #60     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #61     SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #62     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #63     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #64     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #65     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #66     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #67     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #68     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #69     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #70     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #71     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #72     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #73     ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #74     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #75     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #76     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #77     ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #78     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #79     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #80     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #81     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #82     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #83     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #84     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #85     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #86     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #87     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #88     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #89     ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #90     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #91     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #92     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #93     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #94     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #95     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #96     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #97     StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #98     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #99     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #100    Element.rebuild 
I/flutter (28769): #101    ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #102    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #103    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #104    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #105    StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #106    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #107    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #108    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #109    ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #110    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #111    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #112    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #113    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #114    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #115    StatelessElement.update 
package:flutter/…/widgets/framework.dart:3796
I/flutter (28769): #116    Element.updateChild
I/flutter (28769): #117    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #118    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #119    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #120    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #121    StatelessElement.update 
package:flutter/…/widgets/framework.dart:3796
I/flutter (28769): #122    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #123    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #124    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #125    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #126    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #127    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #128    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #129    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #130    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #131    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #132    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #133    StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #134    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #135    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #136    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #137    StatelessElement.update 
package:flutter/…/widgets/framework.dart:3796
I/flutter (28769): #138    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #139    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #140    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
Reloaded 15 of 734 libraries in 4,048ms.
I/flutter (28769): #141    StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #142    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #143    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #144    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #145    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #146    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #147    ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #148    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #149    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #150    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #151    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #152    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #153    StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (28769): #154    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #155    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #156    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #157    StatelessElement.update 
package:flutter/…/widgets/framework.dart:3796
I/flutter (28769): #158    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #159    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4883
I/flutter (28769): #160    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #161    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #162    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #163    ProxyElement.update 
package:flutter/…/widgets/framework.dart:4006
I/flutter (28769): #164    Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (28769): #165    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (28769): #166    Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (28769): #167    BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2273
I/flutter (28769): #168    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
I/flutter (28769): #169    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:268
I/flutter (28769): #170    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:988
I/flutter (28769): #171    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:928
I/flutter (28769): #172    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:749
I/flutter (28769): #174    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (28769): #175    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (28769): #176    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (28769): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (28769): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by HansMuller** [comment]
You're right, this failure could be more informative than `'!children.any((Widget child) => child == null)': is not true`. The assert's message should explain that the column's children must non-null widgets and it could display the index and value of the first list element that fails the test.
