### ISSUE TITLE
sliver.dart: Failed assertion: line 551 pos 12: 'child != null'

### ISSUE THREAD

**Issue by jeantuffier** [flutter/flutter#30558]
This is the error message I got : 
>'package:flutter/src/widgets/sliver.dart': Failed assertion: line 551 pos 12: 'child != null': is
flutter: not true.

and the following message : 
>Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub

So here I am reporting it. To generate the issue I replaced : 
    
    return ListView.builder(
      itemCount: comics.length,
      itemBuilder: (context, index) => ComicWidget(comics[index]),
      scrollDirection: Axis.horizontal,
    );

by : 

    return GridView.count(
      crossAxisCount: 2,
      children: comics.map((character) {
        ComicWidget(character);
      }).toList(),
    )

**Comment by shihaohong** [comment]
Resolved with https://github.com/flutter/flutter/pull/32487
