### ISSUE TITLE
TabController not working when swiping past last Tab

### ISSUE THREAD

**Issue by sumanthratna** [flutter/flutter#30568]
## Related Issues
- #1126. 

## This Issue
I have a `TabBar` with 3 `Tab`s. The `TabController` has `length` 3. When I open the page, The first tab is correctly shown. I swipe to the second tab. There are no errors. I swipe to the third tab. There are still no errors. I swipe to the right *again* (so it should either not allow further swiping or swipe back to the first `Tab`), but it swipes to the first tab and the indicator remains at the third tab. The `TabBar` is now broken, and clicking the tabs at the bottom changes the indicator but not the content. Swiping, however, changes the content but not the indicator. 

## My Code
```dart
return Scaffold(
      key: _scaffoldKey,
      appBar: /*hidden*/,
      body: TabBarView(children: _tabs, controller: _tabController),
      bottomNavigationBar: TabBar(controller: _tabController, tabs: const <Tab>[
        Tab(icon: Icon(Icons.person), text: 'Home'),
        Tab(icon: Icon(Icons.school), text: 'Grades'),
        Tab(icon: Icon(Icons.settings), text: 'Settings')
      ]),
    );
```
and in `initState()`:
```dart
_tabController = TabController(vsync: this, length: 3);
```

## The `Exception`
```[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 111 pos 12: 'value >= 0 && (value < length || length == 0)': is not true.                                                     #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)                                              #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)                                                 #2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:111:12)                                    #3      TabController.index= (package:flutter/src/material/tab_controller.dart:146:5)                                           #4      _TabBarViewState._handleScrollNotification (package:flutter/src/material/tabs.dart:1219:19)                             #5      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)                          #6      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)                               #7      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)                                                                                                      #8      Eleme<…>```

## Possible Solution
Replace [this `assert`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tab_controller.dart#L111) with `value %= length`. This would allow proper "circular" swiping. 

## `flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/suman/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/suman/android-sdks
      but Android SDK not found at this location.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone 6 • <ID> • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.
```
I zipped up `android-sdk/` since it was taking up too much space and I'm developing for iOS.

**Comment by shihaohong** [comment]
I just tried testing, and this seems to work fine: https://gist.github.com/shihaohong/4e0864b55d7482c7f080fe81047bcdec

Could you share a minimal reproducible sample via a gist?

**Comment by sumanthratna** [comment]
I just ran the Gist on an iPhone 6 Simulator and there were no errors. Earlier I found the issue on the same Simulator. Later I'll run my app on a physical iOS device and see how it works. For now, the relevent file is [here](https://github.com/sumanthratna/grade-view/blob/master/lib/home_page.dart). 

I don't think you'll be able to test it since credentials aren't available. Later, I'll try to create a test user and create minimal reproducible code.

**Comment by sumanthratna** [comment]
This is pretty interesting (unless I'm forgetting something about how `Widget`s work). If you look [here](https://github.com/sumanthratna/grade-view/blob/master/lib/home_page.dart#L71) I create `Container`s for the `Tab`s all in the `build`. 

After creating `StatelessWidget`s for each `Tab`, I didn't get this issue. Later, I'll commit to the repo I just linked to show what I mean. 

I guess this can be closed unless you think this is a bug.

**Comment by sumanthratna** [comment]
Sorry about that, I'm still getting the same issue. 

When I only use the swipe gesture, I get no issues. When I click the tabs at the bottom, I encounter the issue (on my app). 

I'm not getting the issue at all on your gist though. I'm still working on a reproducible sample.

**Comment by shihaohong** [comment]
After looking at your [code](https://github.com/sumanthratna/grade-view/blob/master/lib/home_page.dart#L71), one of my main concerns would be constructing your widgets and calling `_tabs.add()` numerous times in the `build` method. It gets called [many times](https://docs.flutter.io/flutter/widgets/State/build.html) and updating your `_tabs` state in `build` may cause erratic behavior.

**Comment by sumanthratna** [comment]
Thanks, that was it. However, instead of defining `_tabs` in `initState`, I simply used `_tabs[0] = /*the widget I want*/;` instead of `_tabs.add(/*the widget I want*/);`

Note to future developers: Since `add` increases size, it `_tabs`' size went to 6 after a `setState`, swiping past `3` was allowed but there were only `3` tabs.
