### ISSUE TITLE
cloud_firestore not update doc.metadata.hasPendingWrites list collection after update doc

### ISSUE THREAD

**Issue by gustavobrian** [flutter/flutter#30564]
cloud_firestore: ^0.9.11
------------------------------- 
Stream<List<DocumentSnapshot>> getPlayersMatch(String groupKey, String matchKey) {
    return firestore.collection('groupMatchPlayers').document(groupKey).collection(matchKey).snapshots().map((snapshot) {
      print("groupMatchPlayers length:" + snapshot.documents.length.toString());
      return snapshot.documents;
    });
  }

------------------------------- 
await this.firestore.collection('groupMatchPlayers').document(groupKey).collection(matchKey).document(playerMatch.uid).setData(playerMatch.toJson());

------------------------------- 
My problem is  doc.metadata.hasPendingWrites not update in 
firestore.collection('groupMatchPlayers').document(groupKey).collection(matchKey).snapshots()
------------------------------- 
Thanks for your works...
PD: Support for cloud_firestore running in the background on Android is the best and the super best.. I love you!!!!

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

Firebase has a new home here https://github.com/FirebaseExtended/flutterfire please raise there a new issue and reference this one. 
Thanks
