### ISSUE TITLE
GoogleMaps plugin testScrollGesturesEnabled flaky on tablet devices

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#30575]
filing this preemptively. After https://github.com/flutter/plugins/pull/1352 merges there are some timing issues identified for this test. This might hold for other tests on other devices. Once we move plugin testing infra to account for multiple device configurations, we should be able to effectively identify this.

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/30575

**Comment by TahaTesser** [comment]
Hi @iskakaushik 
Does this issue still exist?
Thank you

**Comment by VladyslavBondarenko** [comment]
@iskakaushik 
I hope it's fixed.
If no, could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
