### ISSUE TITLE
flutter tool should provide a way to set Dart VM flags

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#3057]
E.g., flutter run --dart-flags=--startup-timeline

**Comment by abarth** [comment]
@johnmccutchan

**Comment by sethladd** [comment]
Do we still have use cases for this?

**Comment by johnmccutchan** [comment]
It would be really handy for engine development / debugging. No good use cases for Flutter app developers.

**Comment by Hixie** [comment]
We have to be really careful with how we implement this. it would have to be something built into the apk, not an argument to the executable, so that random apps can't trigger us with settings that open up potential security holes.

**Comment by Hixie** [comment]
I recommend WONTFIX because of the risk of implementing this in a dangerous fashion, and because we already have a really complicated `flutter run` setup.

**Comment by Hixie** [comment]
We're going to close this since there doesn't seem to be enough demand for it to justify it.
