### ISSUE TITLE
WebView Plugin PWA Integration

### ISSUE THREAD

**Issue by Immortalin** [flutter/flutter#30582]
Would be really useful if the WebViewController has a way to explicitly download PWAs. A lot of modern API-driven applications that tend to build clients with flutter have a web frontend. and porting to flutter takes a long time. This way apps can be progressively ported using the Strangler pattern among other use cases e.g. tighter integration between JS and Flutter.

**Comment by Immortalin** [comment]
With [a local web server](https://digitalilusion.com/news/embedded-web-server-in-flutter/) this can create a pseudo Electron or Cordova/Phonegap, making migration and integration significantly more frictionless.

**Comment by Immortalin** [comment]
With [a local web server](https://digitalilusion.com/news/embedded-web-server-in-flutter/) this can create a pseudo Electron or Cordova/Phonegap, making migration and integration significantly more frictionless.

**Comment by dnfield** [comment]
I'm not quite sure what this would really look like embedded in Flutter - would you be able to install a PWA from a Flutter app this way? I'm not so sure all platforms support this, and I'm not sure it's a very good user experience.

Things have changed since I last was looking at PWAs (as in apparently iOS now has at least some support for them?).  But I strongly suspect this won't work very well on iOS in particular.

**Comment by Immortalin** [comment]
@dnfield if you try https://github.com/flutter/plugins/pull/1457#issuecomment-480523546, it demonstrates maps without using e.g. https://github.com/johnpryan/flutter_map which are not close to feature parity w.r.t. their JS counterparts.

**Comment by rebootcode** [comment]
@kf6gpe , @Hixie - Any update, this would be cool, if PWA can be injected inside WebView to load the page offline.

**Comment by stuartmorgan** [comment]
There are APIs for loading file or asset content, but if that's not sufficient for this use case you'd need to run a local web server, which isn't in scope for the webview plugin (as running a local server is unrelated to a website itself).

Closing as I don't see anything actionable for the webview plugin here.
