### ISSUE TITLE
"flutter create demo_app" only create .gitignore then exit

### ISSUE THREAD

**Issue by oliver-gomes** [flutter/flutter#30595]
## Whats the Situation

1. I installed Flutter and on Bash flutter doctor runs fine and checks all the required steps
2. When I hit flutter create demo_app, the error appears
3. I reinstalled Flutter and changed sdk path, still it's happening 😨 

## Logs

```

flutter create demo_app
Creating project demo_app...
  demo_app\.gitignore (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 595219dfbd712d18)
Crash report written to C:\Users\asdf\AppData\Local\Temp\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.


```

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\asdf\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\asdf\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.33.0)
    • VS Code at C:\Users\asdf\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by dnfield** [comment]
Can you please re-run it with the verbose flag, or include the contents of ` C:\Users\asdf\AppData\Local\Temp\flutter_04.log`

**Comment by oliver-gomes** [comment]
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create demo_app

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\asdf\OneDrive\Desktop\Mobile Developer\demo_app\.gitignore' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:159:30)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
#7      Template.render (package:flutter_tools/src/template.dart:109:24)
#8      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:541:21)
#9      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:468:23)
<asynchronous suspension>
#10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:319:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ogome\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\ogome\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.33.0)
    • VS Code at C:\Users\ogome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
@dnfield here's the log content

**Comment by dnfield** [comment]
It's an access issue - the user you're running the flutter command as doesn't have access to the folder you're trying to write to.  I suspect you'd find the .gitignore file is empty.

**Comment by oliver-gomes** [comment]
Yes, the .gitignore is empty. How do I give flutter the access?

**Comment by dnfield** [comment]
It's not flutter that needs the access, it's the user you're logged in as.  For example, if you're trying to write to a folder that needs administrator permissions to write a file to, you need to run as admin (which isn't necessarily recommended).

Alternatively, you could try to do `flutter create` in another location on your disk that doesn't require that access.

**Comment by oliver-gomes** [comment]
@dnfield Thank you for clarifying! It worked on another location so I will be sticking to that for now 😄

**Comment by oliver-gomes** [comment]
Closing the issue as it's been solved
