### ISSUE TITLE
[firebase_crashlytics] log should print if debugging and enableInDevMode is not set

### ISSUE THREAD

**Issue by jeffscaturro-aka** [flutter/flutter#30591]
Feature Request
---
When a consumer calls `Crashlytics.instance.log(msg)` while debugging (and without `enableInDevMode` set), we should print the `msg` to the console. When teams write meaningful debug statements, they should be useful in both production and development. Sometimes we may throw some quick temporary `prints` but we're not really discussing those ones.

Use Case
---
Flutter developer/team "X" just implemented Firebase Crashlytics via Flutter's plugin and swapped all their meaningful `print` statements to `Crashlytics.instance.log(msg)`, but now all their logs are gone. They wrote a wrapper method that does both print and log to Crashlytics.

Of course, we could leave it up to them to write the wrapper if they chose, but opening this to get community's thoughts on it.

**Comment by kroikie** [comment]
@jeffscaturro-aka

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/387. Any further collaboration will be done there.
