### ISSUE TITLE
errro on run

### ISSUE THREAD

**Issue by mammadkoma** [flutter/flutter#30597]
I downloaded flutter sdk and android sdk and set variables ANDROID_HOME , JAVA_HOME and flutter bin to path variable. I did it for my labtop win 10 and run it by vscode correctly.
I copied flutter sdk & android sdk & jdk1.8.0_161 folders to my work pc win 10 and set above variables , vscode flutter run get error :

Launching lib\main.dart on HTC One M9 in debug mode...
* Error running Gradle:
ProcessException: Process "E:\Projects\Flutter\app1\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:

A problem occurred configuring root project 'android'.

> Could not resolve all artifacts for configuration ':classpath'.

   > Could not resolve com.android.tools.build:gradle:3.2.1.

     Required by:

         project :

      > Could not resolve com.android.tools.build:gradle:3.2.1.

         > Could not get resource 'https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.

            > Could not HEAD 'https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'. Received status code 503 from server: Service Unavailable

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

Picked up _JAVA_OPTIONS: -Xmx512M
  Command: E:\Projects\Flutter\app1\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by dnfield** [comment]
What version of flutter are you using?

**Comment by mammadkoma** [comment]
![image](https://user-images.githubusercontent.com/17564001/55680329-a0577f80-592d-11e9-945b-577db1dac29e.png)

**Comment by mammadkoma** [comment]
I tested both v1.3.8 beta and v1.2.1 Stable.

**Comment by blasten** [comment]
The tool will retry to get the resource. However, if this host is temporarily down, you won't be able to build the project. I filed https://github.com/flutter/flutter/issues/49403, so we can provide a doctor check to verify if it's a temporary network failure or a persistent failure.
