### ISSUE TITLE
firebase_core on Android is broken

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#30606]
Essentially, [this pull request](https://github.com/flutter/plugins/pull/1443) broke Android builds depending on `firebase_core`. 

`enableFeaturePreview('IMPROVED_POM_SUPPORT')` in `settings.gradle` is supposed to fix it, however, that does not work for me (using Gradle 5.1.1). I solved it [by reverting](https://github.com/flutter/plugins/pull/1443#issuecomment-480499299).

Also, CI builds in `flutter/plugins` seem to not build properly for Android.

The worst part about it is how hard it is to figure it out because [there is no error message]([related](https://github.com/flutter/flutter/issues/30605)). It took me many hours to figure out why the build was failing and I probably only figured it out because I saw the mentioned pull request yesterday when [creating one of my own](https://github.com/flutter/plugins/pull/1450).

**Comment by kroikie** [comment]
@creativecreatorormaybenot if you are using Gradle 5+ then you should not need `enableFeaturePreview('IMPROVED_POM_SUPPORT')`. The BoM support is on by default from Gradle 5. What was the issue you saw in your build?

**Comment by creativecreatorormaybenot** [comment]
@kroikie I described it [here](https://github.com/flutter/flutter/issues/30605). It might be important to add that reverting to the non-BoM dependency solved the issue. Thus, it is the issue for me. Changing that and only that and then rebuilding entirely solves the problem / makes it reappear.

**Comment by kroikie** [comment]
@creativecreatorormaybenot Thanks for the information. Could you state what other plugins you are using with `firebase_core` so I can try to reproduce? Note that only `firebase_core` and `cloud_firestore` have been updated to BoM, if you are using others then you may see issues. I'm in the process of adding BoM to the other FlutterFire plugins.

**Comment by creativecreatorormaybenot** [comment]
@kroikie Does this mean that they all need to be migrated at the same time? If that is the case, you might just want to merge and then I could tell you if the issue still remains.

I am using most of them.

**Comment by omeshwar** [comment]
For Now  `firebase_core: 0.3.1+1`  works Fine!

**Comment by creativecreatorormaybenot** [comment]
@kroikie [This](https://stackoverflow.com/q/55558288/6509751) is why I thought it was not a nice pull request. This user spent a long time (["I'm tried every thing i know but it not work. :(](https://stackoverflow.com/revisions/55558288/1)") trying to fix the issue just like me. I feel like there should be a warning or something to indicate how to solve this issue.

**Comment by kroikie** [comment]
@creativecreatorormaybenot after some offline discussions I'll revert to non-BoM to avoid Gradle version issues.

**Comment by DanMossa** [comment]
I'm not sure where to go from here.

This issue happened after I upgraded flutter after being told there was a flutter upgrade in android studio.

I was then getting issues about weird versioning errors with my firebase stuff.

I then changed to 
`implementation 'com.google.firebase:firebase-core:16.0.8'`
and
```
classpath 'com.android.tools.build:gradle:3.3.2'
classpath 'com.google.gms:google-services:4.2.0'
````

And like everyone else, I'm getting issues with

```*
 What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-core:.
     Required by:
         project :firebase_core
```

At this point, what should we do for a temporary fix? I see suggestions for upgrading the build;gradle?
I tried changed the 16.0.8 to 16.0.4 like others said but that also didn't work.

Any ideas on how to at least get my app to run again?

**Comment by kroikie** [comment]
Thanks Dan, as you point out this only works in Gradle 4, with Gradle 5 which is what @creativecreatorormaybenot was using a different BoM solution is required. So I'm going to revert to non BoM dependencies till we have a more stable BoM solution.

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/386. Any further collaboration will be done there.
