### ISSUE TITLE
I cannot render the ListView with my items from StreamBuilder

### ISSUE THREAD

**Issue by yoonhok524** [flutter/flutter#30607]
```dart
class _TagsState extends State<TagsPage> {

  final TagRepository _tagRepository;
  final TagsBloc bloc;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: StreamBuilder<List<Tag>>(
            stream: bloc.tags,
            builder: (context, snapshot) {
              if (snapshot.data == null || snapshot.data.isEmpty) {
                print("[TagsPage] build - snapshot.data is null");
              } else {
                print("[TagsPage] build - snapshot.data.length: ${snapshot.data.length}");
                return ListView(
                  children: snapshot.data.map(_buildItem).toList(),
                );
              }
            },
          ),
        ),
      );

  _buildItem(Tag tag) => Text(tag.name);

}

```

snapshot.data is not null and not empty.
It has data, but it doesn't render to Text widget.

log is here:

I/flutter (21410): [TagsPage][JOS] build - snapshot.data.length: 1
I/flutter (21410): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21410): The following assertion was thrown building StreamBuilder<List<Tag>>(dirty, dependencies:
I/flutter (21410): [_LocalizationsScope-[GlobalKey#cebbd], _InheritedTheme], state: _StreamBuilderBaseState<List<Tag>,
I/flutter (21410): AsyncSnapshot<List<Tag>>>#1b6a7):
I/flutter (21410): type 'List<dynamic>' is not a subtype of type 'List<Widget>'
I/flutter (21410): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (21410): more information in this error message to help you determine and fix the underlying cause.
I/flutter (21410): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (21410):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (21410): When the exception was thrown, this was the stack:
I/flutter (21410): #0      _TagsState.build.<anonymous closure> (package:jos/pages/tags.dart:54:59)

**Comment by dnfield** [comment]
What's the type of `bloc.tags`?  It looks like there's some type mismatch going on, you very likely need some kind of `.cast`.

This would probably be a good stackoverflow question, or a quetion on one of the other channels at https://flutter.dev/community.  It's not really a bug in the framework (despite what the assertion error says).
