### ISSUE TITLE
Can play video and sound, or video and subtitle same time?

### ISSUE THREAD

**Issue by lequanghiep74** [flutter/flutter#30602]
Can play video and sound, or video and subtitle same time? - Video and sound run in same time, video pause will make sound pause.
In ExoPlayer in android i can do it with `MergeMediaPlayer`, but in flutter i can't see any tutorial for it. Please help me. Thanks.

**Comment by TahaTesser** [comment]
Hi @lequanghiep74 
Are you still experiencing this issue with latest stable?
Thank you

**Comment by TahaTesser** [comment]
Hi @lequanghiep74 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
