### ISSUE TITLE
Widgets disappear after returning to the app on iOS

### ISSUE THREAD

**Issue by jgadsby** [flutter/flutter#30608]
Hi,

I have an iOS app which uses the url_launcher plugin to launch URLs from a sub screen of the main screen (which is a series of tabs). After returning to the app from the URL, the sub screen looks correct, but navigating back from that screen results in messed up widgets like so:

![7638C151-02D4-4B3F-A97E-7EB69C120BDB](https://user-images.githubusercontent.com/4282877/55670550-ea6c3280-5853-11e9-957b-42d95b4e4c53.png)

I’m using Flutter 1.3.8. Any ideas?

**Comment by dnfield** [comment]
Does this reproduce on master?

By chance, are the widgets you're expecting to see text or image heavy?

**Comment by jgadsby** [comment]
It looks like it's actually only happening when the app attempts to return back to a google_maps_flutter widget. I have several other tabs and when returning to those the app is fine.

**Comment by jgadsby** [comment]
I'm guessing this it to do with the iOS requirement to enable 'showEmbeddedViews'?

**Comment by dnfield** [comment]
What is the tab supposed to look like when it's good?  Can you post a screen shot of that?

I recently fixed a but that I believe is related.  Does this problem still happen on master?

**Comment by jgadsby** [comment]
Here's what it normally looks like: ![Screenshot_1554643593](https://user-images.githubusercontent.com/4282877/55767261-2666e980-5a46-11e9-887e-ec0f18d0ed3a.png)

**Comment by yaaqovadam** [comment]
same thing happens with me on android when the app gets sent to the background and theres a signal strength shift (from poor to moderate or vice vesa) and i jump between apps and then return to the flutter app, google_maps_flutter gone!

**Comment by yaaqovadam** [comment]
so, for me the map disappears when i send the app to the background twice. like.. i load the app with the map, i swap apps to gmail for example, swap back to my app, swap back to gmail & then swap back to my app. at that point the map is gone. kind of a drag. this behavior is exhibited in the google_maps_flutter example (in every example).. to bypass i used 

void didChangeAppLifecycleState(AppLifecycleState state) {
 if(state == AppLifecycleState.resumed){
        Navigator.pushReplacement (
            context,
            MaterialPageRoute(builder: (context) =>  PlaceMarkerPage()),
          );
     }
}

i basically reloaded the app after deleting timer & listeners etc in dispose. prolly not the most eloquent solution i admit but for now it will have to do until i understand better how to best deal with the issue :)

**Comment by ianko** [comment]
Just came across this issue with the `url_launcher` but on Android. Found out that removing the `statusBarBrightness` parameter from the `launch()` invocation solved the issue.

Preparing a demo app to open a new issue.

**Comment by RyanRamchandar** [comment]
Similar issues: #40050 #40655 #37619

**Comment by Hixie** [comment]
Does this still happen? One of those bugs said their issue was fixed last month.

To resolve this what we need is a demo app that shows the problem, so that we can reproduce it.

**Comment by ianko** [comment]
@Hixie I have a demo application here: https://gist.github.com/ianko/e5ab0da1c48736e65538305c8ded1a7d

(it was added in the #43373 issue)

**Comment by iapicca** [comment]
Hi @jgadsby 
the issue seems solved w/ the latest stable version of flutter and url_launcher
https://photos.app.goo.gl/19B8pnhjTFvL2rCx9
Closing this issue, if you disagree please write in the comments and I will reopen it
Thank you
