### ISSUE TITLE
[local_auth] custom UI

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#30601]
Is it possible to use th local_auth package and still use a custom UI? So we can build our own designs? At this point we need to use the default implementation for ios and android.

**Comment by dnfield** [comment]
If you can add some more details about what you're looking for and what you've tried it would be helpful.

**Comment by vanlooverenkoen** [comment]
For android this popup is always shown: ![image](https://user-images.githubusercontent.com/21172855/55704795-62b22f80-59dd-11e9-89fc-000ea58bab27.png)

Most of the time we want to build a custom UI around the finger print like 1Password, LastPassword,...
More like this image:
![image](https://user-images.githubusercontent.com/21172855/55704899-b6bd1400-59dd-11e9-8d1b-e951b8759e15.png)

In this case we don't have a popup so the user can still easily change to another username.

**Comment by vanlooverenkoen** [comment]
I think for iOS this is not possible because the os handles the FaceId and TouchId with a popup. For android this is possible and should be available in my opinion

**Comment by dnfield** [comment]
Android has an API for this.  It's a new feature for the plugin AFAIK.

**Comment by lukaszurbanski** [comment]
I've hijacked the local_auth plugin to override the prompt display but local_auth is now using BiometricPrompt. How? Is it resolvable somehow? Or the issue should be closed?

**Comment by vanlooverenkoen** [comment]
With the new biometric prompt this is not possible anymore indeed.
