### ISSUE TITLE
Firebase Auth does not work with twitter

### ISSUE THREAD

**Issue by Bobbyjoness** [flutter/flutter#30618]
## Steps to Reproduce

To reproduce the problem one would just have to attempt to sign in using Flutter_twitter_login and firebase authentication. The twitter auth portion is working. The problem is with the flutter firebase auth portion.

## Logs

```
I/flutter (32385): PlatformException(ERROR_INVALID_CREDENTIAL, The supplied auth credential is malformed or has expired. [ Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 401, http response: {"errors":[{"code":32,"message":"Could not authenticate you."}]} ], null)
```

```
Analyzing _...
No issues found! (ran in 7.7s)
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 1.2.1 at C:\Users\dserr\Flutter\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\dserr\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.33.0)
    • VS Code at C:\Users\dserr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • ONEPLUS A3000 • 2846bfa7 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by mollywoodnini** [comment]
Same issue for me.

**Comment by koskorya** [comment]
When I add flutter_twitter_login: ^1.1.0 to my pubspec.yaml dependencies, my build fails with exception: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

When I comment out the dependency in my pubspec, it builds fine.

**Comment by KieranSteyn** [comment]
I'm fighting the same thing. Has anyone found a fix?

**Comment by filipppp** [comment]
Same issue for me, how is this not fixed?

**Comment by escamoteur** [comment]
@koskorya this is another bug. Does it still occur?

If so please file a separate bug.

@KieranSteyn @EmmanuelAmodu @filipppp  Do you relate to the bug of the thread opener or the one of @koskorya ?

I know that this works because I implemented it in one of our apps.

Looking at the error message
```
I/flutter (32385): PlatformException(ERROR_INVALID_CREDENTIAL, The supplied auth credential is malformed or has expired. [ Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 401, http response: {"errors":[{"code":32,"message":"Could not authenticate you."}]} ], null)
```
Tells me that there is a problem with the Twitter apikey/secret.

Please ask questions like that on stackoverflow. We are not able to give individual support. Thanks for your understanding.

**Comment by filipppp** [comment]
@escamoteur I'm having the same problem as the thread opener @Bobbyjoness and it's not the keys. I tested everything and tried everything. Someone suggested that the twittersdk is deprecated and not being used anymore.. instead FirebaseOAUTH is used in Android for example.

**Comment by escamoteur** [comment]
FirebaseAuth oh yeah, just checked now FirebaseAuth comes with https://pub.dev/documentation/firebase_auth/latest/firebase_auth/TwitterAuthProvider-class.html
So I guess you should use that

**Comment by filipppp** [comment]
> FirebaseAuth oh yeah, just checked now FirebaseAuth comes with https://pub.dev/documentation/firebase_auth/latest/firebase_auth/TwitterAuthProvider-class.html
> So I guess you should use that

Yes I'm using that as shown in my issue #138

**Comment by escamoteur** [comment]
But https://pub.dev/packages/flutter_twitter should work too at least I have used it in the past successfully

**Comment by filipppp** [comment]
I tried that library too. Tried all of them to be precise. It isn't a problem with the library, it's more likely there's something with firebase_auth since this function throws the error after getting passed the correct keys.

**Comment by escamoteur** [comment]
I opened this again to give this issue more attention

**Comment by kroikie** [comment]
@Bobbyjoness

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1113. Any further collaboration will be done there.
