### ISSUE TITLE
WebView keeps opening itself in a new tab (iOS)

### ISSUE THREAD

**Issue by Skyost** [flutter/flutter#30613]
Hi,

I'm having troubles using the [webview_flutter](https://pub.dartlang.org/packages/webview_flutter) plugin on iOS. It works well on Android but each time I'm trying to load some HTML content on iOS (whether it's from a remote website or a local server), the plugin keeps opening it in a new tab like this :

![Actual](https://i.imgur.com/7si5zTV.png)

What I want is this (same content but with my own UI, my actions, ...) :

![Expected](https://i.imgur.com/djOXbBC.png)

If you want more info, well I'm using a standard code :

```dart
return Scaffold(
  appBar: AppBar(
    title: Text('A title'),
    actions: actions,
  ),
  body: WebView(
    initialUrl: "http://localhost:$_PORT/assets/webview/content.html", // Just a local server serving flutter assets on port 8080.
    javascriptMode: JavascriptMode.unrestricted,
  ),
);
```

And I have added the code into my `Info.plist` :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <!-- Other properties... -->
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsLocalNetworking</key>
      <true/>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      <key>NSAllowsArbitraryLoadsInWebContent</key>
      <true/>
    </dict>
    <key>io.flutter.embedded_views_preview</key>
    <true/>
  </dict>
</plist>
```

I don't know if it's a bug or a mistake from me so that's why I'm asking it here.

**Comment by tudorcodarnai** [comment]
Same problem here. Did you manage to solve it?

**Comment by Skyost** [comment]
@tudorcodarnai Yes but I don't remember how. But if you want you can find my implementation [here](https://github.com/Skyost/Bacomathiques/blob/app/lib/screen/html.dart#L72). I think it was a missing property in my `Info.plist`.

**Comment by tudorcodarnai** [comment]
In the meanwhile I've solved my situation. Indeed you found a similar hack as i did now: 

```javascript
import 'package:url_launcher/url_launcher.dart';
import 'package:webview_flutter/webview_flutter.dart' as WV;

...

WV.WebView(
    javascriptMode: WV.JavascriptMode.unrestricted,
    initialUrl:'https://example.com',
    navigationDelegate: (action) {
        if(!action.url.contains("example.com") && action.isForMainFrame == true) { //iOS fix, without this it would navigate to new tab/page at first load
           _launchURL(action.url); 
           return WV.NavigationDecision.prevent;
        }
        return WV.NavigationDecision.navigate;
    }
)

_launchURL(url) async {
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
}
```
I was interested in loading the first link in the webview, while the next clicks should open a new tab.

**Comment by VladyslavBondarenko** [comment]
Hi @Skyost 
I'm glad that you solved  problem, closing the issue
If you disagree please write in the comments and I will reopen it.
Thank you
