### ISSUE TITLE
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.

### ISSUE THREAD

**Issue by surpriso1997** [flutter/flutter#30629]
## Steps to Reproduce
1. create flutter project
2. add firebase dependencies in app level and project level gradle files
3. add firebase_auth and cloud_firestore in pubspec.yaml

Problems:
Problems don't arise until I add cloud firestore dependency in pubsepec file. Tried changing different versions of firebase plugins but couldn't find any solutions.

**Logs:**

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-core:.
     Required by:
         project :firebase_core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

main.dart file:
https://gist.github.com/surpriso1997/1bcea71d23c45a926f7b0a74ac2bb8ef

**Pubspec dependencies:**
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.1
  cloud_firestore: ^0.9.7+2
  google_sign_in: ^4.0.1+1

**app level gradle :**
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.firebase_flutter"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.android.gms:play-services-base:16.1.0'
    implementation 'com.google.firebase:firebase-core:16.0.8'
}
apply plugin: 'com.google.gms.google-services'

**Project level gradle:**
buildscript {
    ext.kotlin_version = '1.3.21'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'

    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://maven.google.com" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Flutter doctor:**

F:\Flutter projects\flutter_firebase\firebase_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.191], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2017.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.33.0)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by DeRealMorgan** [comment]
Same issue!

**Comment by surpriso1997** [comment]
> Same issue!
I'm spending trying to figure out this problem than actual coding.

**Comment by andretietz** [comment]
https://github.com/flutter/flutter/issues/30631

**Comment by Ptanium** [comment]
Same with me

**Comment by cpow** [comment]
Same here. Thanks for reporting!

**Comment by Ptanium** [comment]
I fixed this problem by adding old version of firebase_core to pubspec:
`firebase_core: ^0.3.1+1`
Hope this help.

**Comment by DeRealMorgan** [comment]
> I fixed this problem by adding old version of firebase_core to pubspec:
> `firebase_core: ^0.3.1+1`
> Hope this help.

No this will not as not the plugin broke, but the new version of flutter.

**Comment by GustavoContreiras** [comment]
Same here
