### ISSUE TITLE
Need advice on expected behavior of Cloud Firestore, cache related

### ISSUE THREAD

**Issue by khainhero** [flutter/flutter#30627]
## Steps to Reproduce

I have written a sample code of how I query the firestore plugin:
using bloc format:
https://github.com/khainhero/bloc_firestore
normal format using custom class:
https://github.com/khainhero/firestore_flutter

**I expect:**
Firestore to get fresh data from backend and if there is no fresh data then to retrieve from the internal local cache
**Reality:**
On the first run: I get all documents that I queried. 
Then I close my app and restart it, I get my previous query results from cache. 
I close the app and wait 30 minutes(initial Query at time 0 minutes) and then I run the app again.
It queries the data from backend as new and I get charged for all the reads and also incur bandwidth(because of downloading the documents again..this one is the main biggest issue for end user)

My documents are static, no updates or changes have been made to them.

**Is this an expected behavior?** If this is expected, then I can move on with my life and come up with a solution to counter this, if it isnt then what could the problem be? 

Can you please look at my sample code I have provided. I have a simple version and another with Bloc format. I cannot move on till i get closure :(.

Thank you.

**Comment by escamoteur** [comment]
Have you solved your problem in the meantime?

Please ask questions like this on stackoverflow. We are not able to give individual support here.

**Comment by escamoteur** [comment]
If you still have this problem please ask the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!

**Comment by kroikie** [comment]
@khainhero

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1236. Any further collaboration will be done there.
