### ISSUE TITLE
EXC_BAD_ACCESS in Simulator::Call in custom engine

### ISSUE THREAD

**Issue by lext-7** [flutter/flutter#30628]
I have built a custom engine which can run kernel output (JIT) in iphone device (not simulator). But there is a EXC_BAD_ACCESS Error when calling `Simulator::Call` in dart vm. What's wrong with it ? How can I make it work in iphone device.

It's strange that the same kernel output can work in simulator and profile mode in iphone simulator, but it can not work in debug mode and release mode in iphone device.

1. I run a demo created by `flutter create demo` using my custom engine.
2. I click the plus icon. When I click the plus icon twice, it will crash.

![image](https://user-images.githubusercontent.com/7139516/55678074-7058ae00-5926-11e9-9ea1-b5adc8ace338.png)

![image](https://user-images.githubusercontent.com/7139516/55678075-75b5f880-5926-11e9-93d4-ef3da79808fe.png)

**Comment by limengyun2008** [comment]
meets the same problem...any updates?

**Comment by kf6gpe** [comment]
I'll pass this on to the engine team, although I think we may not have the bandwidth to support custom engine builds.

**Comment by chinmaygarde** [comment]
Closing as this is not a supported workflow.
