### ISSUE TITLE
Flutter command line needs a single-file launch capability

### ISSUE THREAD

**Issue by paul-hammant** [flutter/flutter#30624]
```
Java foo.java
Python3 foo.py
Ruby foo.rb
```

Flutter can't 'run' a single source file example. That file has to site in a standard directory layout.  This facility is needed more for code-sharing, examples and bug reporting that it is for apps in actual phones for consumers.

**Comment by jonahwilliams** [comment]
`flutter run` is not comparable to the examples you've shared - you can run a dart file directly on the vm using `dart foo.dart`, though this won't give you access to dart:ui and won't run most flutter code.

> That file has to site in a standard directory layout.

It doesn't have to, you can run anything with a `main` method using the target option of flutter run. Example:

`flutter run -t ../../../something/foo.dart`

This does have to be done from a directory which contains the standard flutter structure though.

**Comment by paul-hammant** [comment]
Anyone could write a wrapper script, right?  Hastily creates standard flutter directory structure in tmp folder, then do the `flutter run -t ../../../something/foo.dart` trick. Cool. *I feel a homebrew command coming on.*

**Comment by jonahwilliams** [comment]
That would definitely be possible to do, but I don't think we'll include it in the flutter tool directly.  Some drawbacks would be that `flutter create` takes a non-trivial amount of time compared to `flutter run` or `dart`. Another would be that this prevents usage of plugins or dependencies in the example, which would have to be specified in the tmp flutter project's pubspec.

**Comment by paul-hammant** [comment]
Ahh, it's not the source files in that standard directory that's the problem its the binary items that `flutter packages get` would make. Ok, sadly non trivial :-(
