### ISSUE TITLE
Firestore runTransaction cancel all transaction if a document fails

### ISSUE THREAD

**Issue by afnx** [flutter/flutter#30632]
I use `runTransaction()` to create documents; however, all documents that I try to create fail even if there is only one single document that conflicts with Firestore security rules. Is there a way to skip invalid documents and continue the rest of transaction?

```dart
await _firestore.runTransaction((transaction) async {
   for(String id in userIds) {
     final reference = _firestore.collection("users").document(id);
     await transaction.set(reference, data);
   }
});
```

**Comment by escamoteur** [comment]
If you still have this problem please ask the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!

**Comment by kroikie** [comment]
@afnx

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1235. Any further collaboration will be done there.
