### ISSUE TITLE
Make it easier to use material design without unnecessary flx bloat

### ISSUE THREAD

**Issue by tonygentilcore** [flutter/flutter#3063]
I have an flx that is 1.4M. I'd like to use a single material design icon, so I added `uses-material-design: true` to its manifest. This increases its size by 1.6M (to 3.0M total). It appears most of the size increase is due to the Roboto font variations (which I thought were built into Android already).

Is this intentional? If so, is there any mechanism to control which material assets are included at a finer grained level?

**Comment by abarth** [comment]
If you know you're going to run on a system that already has Roboto, you can pass `--no-include-roboto-fonts` when running `flutter build flx`.  The `flutter build apk` command uses this flag internally for this reason.

We also current bundle every variant of Roboto, including the condensed variants.  We could do a better job of including only those variants that the app actually needs.  However, I suspect `--no-include-roboto-fonts` is actually what you want for your use case.

/cc @jason-simmons

**Comment by tonygentilcore** [comment]
Thanks, that did the trick!
