### ISSUE TITLE
Support custom semantics of TextSpan for Android Talkback

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#30636]
## Steps to Reproduce

1. Open Flutter Gallery
2. Navigate to code sample (Material > Buttons > Show example code <> button)
3. The Talkback description starts with "Create a raised button, RaisedButton, child, const Text button title"

The code sample (excerpt) is this:

```dart
// Create a raised button.
RaisedButton(
  child: const Text('BUTTON TITLE'),
  onPressed: () {

  },
);
```

A better description would talk aloud the syntax which Talkback skips.

Need a way to add custom semantics to a `TextSpan`.

## Logs

```
[✓] Flutter (Channel master, v1.4.13-pre.5, on Mac OS X 10.14.4 18E226, locale
    en-US)
    • Flutter version 1.4.13-pre.5 at /Users/droidery/flutter
    • Framework revision ed49122aa3 (70 minutes ago), 2019-04-08 20:22:34 -0700
    • Engine revision ff1bcdc009
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/droidery/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • Moto G 5S Plus •  • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

Edit: Changed issue from initial issue about not being about to read second line of text with Talkback

**Comment by jonahwilliams** [comment]
Hi @droidery, This works exactly as I would expect on on master using Talkback with a pixel 2 - swiping left/right moves to the next block of text divided by the gesture recognizers. Please include the output of `flutter doctor -v` and some information on the device you are using.

**Comment by droidery** [comment]
@jonahwilliams Thanks for testing. Added the logs with test device and upgraded to latest master.

I can get the text description working now, I wasn't using Talkback properly in my tests but the blocks for Talkback still don't seem correct on my device.

Does you device divide the blocks of text like this:

![image](https://user-images.githubusercontent.com/34681083/55773684-07fbff00-5ad5-11e9-8d38-70d38862ad56.png)

![image](https://user-images.githubusercontent.com/34681083/55773693-121dfd80-5ad5-11e9-8857-940ca7c72ab3.png)

Talkback is treating the first line as separate text but when you swipe on the second line, it creates a green box over the remaining lines which you then navigate with swipe left/right.

Seems strange to have two different ways to navigate the text within the same `RichText`.

Also, is there any way to change what's said? I'm making interactive text in Flutter, so every TextSpan needs to be tappable, but the accessibility description isn't very helpful as I need a way to change what is said by TalkBack when tapping certain TextSpan's. Seems like there is no way to set the semantics of a text block? Is it better if I make a separate issue for this?

**Comment by jonahwilliams** [comment]
That is probably because it breaks the span after the newline, so the rectangle needs to include both the first and last lines. The only way to do that is by drawing the rect over the entire text.

The label semantics of the text is the text itself, what are you trying to change? The "double tap to activate" phrase is inserted by talkback itself. The only part that can be customized is the last word - so you could change "double tap to activate" into "double tap to cancel".

I don't think we expose the necessary API to do that on the recognizer directly, but it would probably use via https://docs.flutter.io/flutter/semantics/SemanticsHintOverrides-class.html.

**Comment by droidery** [comment]
> That is probably because it breaks the span after the newline, so the rectangle needs to include both the first and last lines. The only way to do that is by drawing the rect over the entire text.

I tried Talkback in non-Flutter apps and it seems to put the green rectangle over the entire paragraph, whereas in the Flutter example it breaks the first line into many rectangles, then bigger rectangle when using the tap handlers.

Not sure if this matters as I don't use Talkback regularly.

> The label semantics of the text is the text itself, what are you trying to change?

I was hoping for a way to change what is described for the text itself by changing the semantics of the text, this is particularly important when showing code inside a Flutter app.

To give an example, if you open the Flutter Gallery and open a code sample (Material > Buttons > Show example code <> button). This is an excerpt of the code:

```dart
// Create a raised button.
RaisedButton(
  child: const Text('BUTTON TITLE'),
  onPressed: () {

  },
);
```

The Talkback description starts with "Create a raised button, RaisedButton, child, const Text button title", but a better description could be talk aloud the syntax which Talkback skips (as I assume Talkback is for reading non-code text).

I could do this if there was a way to change the semantics of a `TextSpan` so that when it sees the `(` token it knows to say "open bracket", instead of assuming they are parentheses in English non-code text. 

I know you can't wrap a TextSpan in widgets, but if I could use widget compsition, I would use this:

```dart
Semantics(
   child: TextSpan(text: '('),
   label: 'Open bracket'
)
```

**Comment by droidery** [comment]
@jonahwilliams 
> That is probably because it breaks the span after the newline, so the rectangle needs to include both the first and last lines. The only way to do that is by drawing the rect over the entire text.

I tried Talkback in non-Flutter apps and it seems to put the green rectangle over the entire paragraph, whereas in the Flutter example it breaks the first line into many rectangles, then bigger rectangle when using the tap handlers.

Not sure if this matters as I don't use Talkback regularly.

> The label semantics of the text is the text itself, what are you trying to change?

I was hoping for a way to change what is described for the text itself by changing the semantics of the text, this is particularly important when showing code inside a Flutter app.

To give an example, if you open the Flutter Gallery and open a code sample (Material > Buttons > Show example code <> button). This is an excerpt of the code:

```dart
// Create a raised button.
RaisedButton(
  child: const Text('BUTTON TITLE'),
  onPressed: () {

  },
);
```

The Talkback description starts with "Create a raised button, RaisedButton, child, const Text button title", but a better description could be talk aloud the syntax which Talkback skips (as I assume Talkback is for reading non-code text).

I could do this if there was a way to change the semantics of a `TextSpan` so that when it sees the `(` token it knows to say "open bracket", instead of assuming they are parentheses in English non-code text. 

I know you can't wrap a TextSpan in widgets, but if I could use widget compsition, I would use this:

```dart
Semantics(
   child: TextSpan(text: '('),
   label: 'Open bracket'
)
```

Hope that helps clarify what I'm trying to do, but I'm not sure if Talkback + Flutter supports this.

**Comment by jonahwilliams** [comment]
We definitely support swapping out the text semantics at the level of the `Text` widget, but not at the text span. For example see https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/text.dart#L359.

We could expose a similar feature for the text span itself, if that would help here

**Comment by droidery** [comment]
@jonahwilliams A `semanticsLabel` for text span would 100% help, exactly what I'm looking for.

I need the text span for highlighting, but it is also good to know `Text` supports custom semantics.

**Comment by jonahwilliams** [comment]
Also, the reason the selection rectangles are broken up is due to the gesture recognizers. It will be presented as a single paragraph without them
