### ISSUE TITLE
'git rev-parse HEAD' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by gabilanbrc** [flutter/flutter#30638]
## Steps to Reproduce
1 - Installed last versions of git and flutter in Windows 10
2 - Added them to the PATH environmental vars
3 - Git.exe can be executed correctly on the CMD
4 - Flutter.bat also, but then i get the folllowing error
C:\Users\Gabriel>flutter doctor --verbose
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\src\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.2.1 at C:\src\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

|CreateProcessW failed 2
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: fe295decfe5f708a)
\CreateProcessW failed 2                                                                                               Crash report written to C:\Users\Gabriel\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

1. ...
2. ...
3. ...

## Logs

```
```

```
```
[flutter_02.log](https://github.com/flutter/flutter/files/3051623/flutter_02.log)

**Comment by gabilanbrc** [comment]
BTW, if I run the command that gives an error in the log, this is what I get
C:\Users\Gabriel>C:\Users\Gabriel\AppData\Local\Android\Sdk\tools\bin\sdkmanager.BAT --licenses
Warning: File C:\Users\Gabriel\.android\repositories.cfg could not be loaded.
All SDK package licenses accepted.======] 100% Computing updates...

**Comment by shivaniaakanksha** [comment]
is there  any possible solution? as i'm facing the same problem

**Comment by Aishwarya1317** [comment]
I am facing same issue

**Comment by shivaniaakanksha** [comment]
> I am facing same issue

i solved this problem as,my .bat file was corrupted which was denying the access to open it,so i reinstalled the windows,there may be some other way to fix the .bat file of windows but i have no idea how to do that .

**Comment by dansten** [comment]
> i solved this problem as,my .bat file was corrupted which was denying the access to open it,so i reinstalled the windows,there may be some other way to fix the .bat file of windows but i have no idea how to do that .

You mean, you reinstalled Windows 10 all together? 
There must exist an easier solution. 

I am facing the same issue, any other possible solutions?

**Comment by dansten** [comment]
I found a solution that worked for me.
(From [Stackoverflow](https://stackoverflow.com/questions/53469305/flutter-doctor-script-throws-errors-and-then-crashes))

The fix:

- Open Control Panel – System – Advanced system settings and click on button Environment Variables.
- If environment variable ComSpec is set to anything other than %SystemRoot%\system32\cmd.exe expanding usually to C:\Windows\system32\cmd.exe, then reset it to Windows default %SystemRoot%\system32\cmd.exe.

**Comment by shivaniaakanksha** [comment]
> I found a solution that worked for me.
> (From [Stackoverflow](https://stackoverflow.com/questions/53469305/flutter-doctor-script-throws-errors-and-then-crashes))
> 
> The fix:
> 
> * Open Control Panel – System – Advanced system settings and click on button Environment Variables.
> * If environment variable ComSpec is set to anything other than %SystemRoot%\system32\cmd.exe expanding usually to C:\Windows\system32\cmd.exe, then reset it to Windows default %SystemRoot%\system32\cmd.exe.

i tried this too,but it didn't worked! that's why i reinstalled Windows 10 all together

**Comment by shivaniaakanksha** [comment]
> I found a solution that worked for me.
> (From [Stackoverflow](https://stackoverflow.com/questions/53469305/flutter-doctor-script-throws-errors-and-then-crashes))
> 
> The fix:
> 
> * Open Control Panel – System – Advanced system settings and click on button Environment Variables.
> * If environment variable ComSpec is set to anything other than %SystemRoot%\system32\cmd.exe expanding usually to C:\Windows\system32\cmd.exe, then reset it to Windows default %SystemRoot%\system32\cmd.exe.

I tried this too,but it didn't worked for me! that's why i reinstalled Windows 10 all together.

**Comment by MuhmdHsn313** [comment]
Guys I get the same problem, are you solve it?

**Comment by MuhmdHsn313** [comment]
I'm solve the problem, I go to

- Control Panel –> System –> Advanced system settings ->  Environment Variables

and change **ComSpec** from **"%SystemRoot%\system32\cmd.exe;"** to **"C:\Windows\system32\cmd.exe"**.

**Comment by michaellhf** [comment]
Try to delete the ComSpec entry, save it and then re-add it. Just change it to "C:\Windows\system32\cmd.exe" didn't work for me, maybe some hidden charcters there.

**Comment by gabilanbrc** [comment]
> I'm solve the problem, I open
> 
> * Control Panel –> System –> Advanced system settings ->  Environment Variables
> 
> and change **ComSpec** from **"%SystemRoot%\system32\cmd.exe;"** to **"C:\Windows\system32\cmd.exe"**, after that it's return normal.
> You have to check the jdk if not installed! Maybe make a same problem..

That seems to solve the issue!

**Comment by relf108** [comment]
Just confirming that I had to completely delete the ComSpec entry and re-add it.
Simply removing the existing java entries and adding the cmd.exe path was not sufficient.

**Comment by 3amwizard** [comment]
> Just confirming that I had to completely delete the ComSpec entry and re-add it.
> Simply removing the existing java entries and adding the cmd.exe path was not sufficient.

This worked for me

**Comment by KillerBean** [comment]
> I'm solve the problem, I open
> 
> * Control Panel –> System –> Advanced system settings ->  Environment Variables
> 
> and change **ComSpec** from **"%SystemRoot%\system32\cmd.exe;"** to **"C:\Windows\system32\cmd.exe"**, after that it's return normal.
> You have to check the jdk if not installed! Maybe make a same problem..

Thank you so much guy, I was trying everything to solve this problem and nothing. I reinstalled Android Studio, SDK, Git For Windows, I tried a large variety of combinations of PATH environment variables.
And you saved my life.
Thank you so much.
