### ISSUE TITLE
[url_launch] [iOS] Got PlatformException when browser redirect to app via scheme (AppAuth flow)

### ISSUE THREAD

**Issue by nguyenhuutinh** [flutter/flutter#30642]
## Steps to Reproduce

1. Open an url using url_launch
if (await canLaunch(url)) {
      await launch(url);
    }
2. InApp Browser show the link then redirect to my app scheme
3. Browser not close, got exception

## Logs

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error, Error while launching https://demo.com/auth/realms/demo/protocol/openid-connect/auth?redirect_uri=ip://host/path/subpath&client_id=demo&response_type=code&state=qtiAIdxHxEs-ZkcwTqq8cQ&scope=openidemailprofile&code_challenge=Fk92pWtIPKhtl4uGOQvMI3LRcpTQG9hcHEW3NZOpI-g&code_challenge_method=S256&deviceid=19fdd9d5c9191cccddd56e63c546ef8, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:85:38)

   info • Unused import: 'dart:io' • lib/demos/image_size_page.dart:1:8 • unused_import
   info • Unused import: 'package:flutter_wanandroid/ui/pages/main_page.dart' • lib/main.dart:6:8 • unused_import
   info • Unused import: 'dart:io' • lib/ui/pages/login/login.dart:4:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/login/login.dart:123:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/login/login.dart:289:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/login/login.dart:626:10 • non_constant_identifier_names
   info • The value of the field '_latestLink' isn't used • lib/ui/pages/login/login.dart:947:10 • unused_field
   info • The value of the field '_latestUri' isn't used • lib/ui/pages/login/login.dart:948:7 • unused_field
   info • Cancel instances of dart.async.StreamSubscription • lib/ui/pages/login/login.dart:949:22 • cancel_subscriptions
   info • The value of the field '_sub' isn't used • lib/ui/pages/login/login.dart:949:22 • unused_field
   info • Close instances of `dart.core.Sink` • lib/ui/pages/onboarding/onboarding.dart:21:34 • close_sinks
   info • Name non-constant identifiers using lowerCamelCase • lib/ui/pages/onboarding/pager_indicator.dart:49:11 • non_constant_identifier_names

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.2.1 at /Users/nguyenhuutinh/MyProjects/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nguyenhuutinh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 91780377-D15E-4AE5-B7AE-53603FFF2F88 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by vHanda** [comment]
Hi. I'm not the reporter, but I seem to have the same issue which I can reliably reproduce -

```
git clone git@github.com:GitJournal/GitJournal.git
cd gitjournal
flutter run lib/oauthapp.dart
```

Clicking on `Open OAuth URL` - starts an OAuth flow where `launch` is used to open a url like this `https://github.com/login/oauth/access_token?client_id=$_clientID&client_secret=$_clientSecret&code=$authCode` . After the oauth flow is completely the app is called as it has added its own url scheme (gitjournal:// in this case). All of this works perfectly if you've never been authenticated before.

However, in the case when you have once authenticated the app - I get the same error as the reporter -

```
flutter: Caught platform exception: PlatformException(Error, Error while launching https://github.com/login/oauth/authorize?client_id=aa3072cbfb02b1db14ed&scope=repo, null)
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      launch (package:url_launcher/url_launcher.dart:87:38)
<asynchronous suspension>
#3      GitHub.launchOAuthScreen (package:gitjournal/apis/github.dart:76:13)
<asynchronous suspension>
#4      GitHostSetupAutoConfigureState._startAutoConfigure (package:gitjournal/screens/githostsetup_autoconfigure.dart:97:15)
#5      GitHostSetupButton._onPressedWithAnalytics (package:gitjournal/screens/githostsetup_button.dart:58:5)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#17     _rootRunUnary (dart:async/zone.dart:1136:13)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#20     _invoke1 (dart:ui/hooks.dart:263:10)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

The interesting bit, is that before this exception my callback handler is being called - so the url is being launched, and it's being redirected back to the app, and my app receives the OAuth token and continues - it's just the UI that gets stuck on an empty WebView.

My callback handler code is -
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
    NSLog(@"openUrl called with url %@", url);
```

I see this log "open Url called with url .." before the exception.

```                                                                                                                          
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.9.1+hotfix.2 at /Users/vishesh/src/flutter/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vishesh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/vishesh/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/vishesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Àlex's iPhone • 3ce97736a179f79cd9e4a1dd54243c167b8cc31a • ios • iOS 10.3.3

• No issues found!
```

**Comment by escamoteur** [comment]
Thanks for the additional information

**Comment by escamoteur** [comment]
could you open this as a new issue? It would help our workflow. Also I just saw you are not on the latest stable Flutter version. If you could try if the issue still exists if you switch to the master channel this would help us too. Thanks

**Comment by acoutts** [comment]
I'm having this issue in my app as well. I'm not using AppAuth, but we have our own oauth redirect routine that works exactly the same. I'm having the exact same behavior as @vHanda - sometimes it works fine, then sometimes it gets hung up with that exact same exception.

Did you ever figure out how to avoid this?
