### ISSUE TITLE
Solid color performance

### ISSUE THREAD

**Issue by cmkweber** [flutter/flutter#30653]
To help isolate performance issues in our app I created a skeleton project that only animates a color on screen. I'm seeing 4ms durations on the GPU, which may seem small but is essentially 25% of the 16ms budget. Of course, this is before much more complex widgets are added on, so I wouldn't have expected to see 4ms.

Tested on android (Galaxy J7 Perx SM-J727P) in profile.

Simple reproducible, text only performance overlay used:

```Dart
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/widgets.dart';

void main()
{
  runApp(
    ColorBox(
      child: PerformanceOverlay(
          optionsMask: 1 << PerformanceOverlayOption.displayRasterizerStatistics.index
      )
    )
  );
}

class ColorBox extends StatefulWidget
{
  final Widget child;

  ColorBox({this.child});

  @override ColorBoxState createState() { return ColorBoxState(); }
}

class ColorBoxState extends State<ColorBox> with SingleTickerProviderStateMixin
{
  Ticker _ticker;
  Duration _timeStamp;

  @override void initState()
  {
    super.initState();
    _ticker = createTicker(rebuild);
    _ticker.start();
  }

  @override void dispose()
  {
    _ticker.dispose();
    super.dispose();
  }

  void rebuild(Duration timeStamp) { setState(() { _timeStamp = timeStamp; }); }

  @override Widget build(BuildContext context)
  {
    final int progress = _timeStamp != null ? _timeStamp.inMilliseconds % 2000 : 0;
    final double delta = progress <= 1000 ? progress * 0.001 : 1.0 - ((progress - 1000) * 0.001);

    final Color blue = Color.fromRGBO(0, 0, 255, 1.0);
    final Color red = Color.fromRGBO(255, 0, 0, 1.0);

    return DecoratedBox(
      decoration: BoxDecoration(color: Color.lerp(blue, red, delta)),
      child: widget.child
    );
  }
}`
```

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by cmkweber** [comment]
I retested this against the latest master and instead used the new onReportTimings @liyuqian implemented instead of the text performance overlay and it shaved off about 2ms on average. Now it is running at about 2.0ms on average for rasterization of a simple app. Just displaying that simple line of debug performance text was accounting for 2ms. Hopefully the intention is to move the performance statistics off the device and to the attached debugger in the future so the drawing of performance doesn't impact results. I think this is acceptable so I'm going to close this issue.

`import 'package:flutter/scheduler.dart';
import 'dart:ui';
import 'package:flutter/widgets.dart';

void main()
{
  runApp(ColorBox());

  window.onReportTimings = onReportTimings;
}

void onReportTimings(List<FrameTiming> timings)
{
  if(timings == null || timings.length == 0)
    return;

  Duration avg = Duration();
  Duration max = Duration();

  for(int t = 0; t < timings.length; t++)
  {
    final FrameTiming timing = timings[t];

    avg += timing.rasterDuration;

    if(timing.rasterDuration > max)
      max = timing.rasterDuration;
  }

  avg = Duration(microseconds: avg.inMicroseconds ~/ timings.length);

  final double average = avg.inMicroseconds / 1000.0;
  final double maximum = max.inMicroseconds / 1000.0;

  debugPrint('Rasterization avg: ' + average.toStringAsFixed(1)  + ' max: ' + maximum.toStringAsFixed(1));
}

class ColorBox extends StatefulWidget
{
  final Widget child;

  ColorBox({this.child});

  @override ColorBoxState createState() { return ColorBoxState(); }
}

class ColorBoxState extends State<ColorBox> with SingleTickerProviderStateMixin
{
  Ticker _ticker;
  Duration _timeStamp;

  @override void initState()
  {
    super.initState();
    _ticker = createTicker(rebuild);
    _ticker.start();
  }

  @override void dispose()
  {
    _ticker.dispose();
    super.dispose();
  }

  void rebuild(Duration timeStamp) { setState(() { _timeStamp = timeStamp; }); }

  @override Widget build(BuildContext context)
  {
    final int progress = _timeStamp != null ? _timeStamp.inMilliseconds % 2000 : 0;
    final double delta = progress <= 1000 ? progress * 0.001 : 1.0 - ((progress - 1000) * 0.001);

    final Color blue = Color.fromRGBO(0, 0, 255, 1.0);
    final Color red = Color.fromRGBO(255, 0, 0, 1.0);

    return DecoratedBox(decoration: BoxDecoration(color: Color.lerp(blue, red, delta)));
  }
}`

**Comment by escamoteur** [comment]
@cmkweber You can observe performance from the new Dart Devtools https://flutter.dev/docs/development/tools/devtools/overview
