### ISSUE TITLE
Cannot update flutter and Emulator doesn't launch

### ISSUE THREAD

**Issue by anonymouse703** [flutter/flutter#30657]
I update my extension of flutter in VSCode but I got this erro.

```
The term 'Unblock-File' is not recognized as the name of a cmdlet, function, sc
ript file, or operable program. Check the spelling of the name, or if a path wa
s included, verify that the path is correct and try again.
At line:1 char:13
+ Unblock-File <<<<  -Path 'C:\flutter/bin/internal/update_dart_sdk.ps1'; & 'C:
\flutter/bin/internal/update_dart_sdk.ps1'
    + CategoryInfo          : ObjectNotFound: (Unblock-File:String) [], Comman 
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```
and when I launch emulator it doesn't work... but before it's working

**Comment by DanTup** [comment]
Can you confirm what OS and PowerShel version you have? `Unblock-File` was introduced in PoSh 3.0, but I believe Flutter requires PowerShell 5.0 now.

**Comment by anonymouse703** [comment]
> Can you confirm what OS and PowerShell version you have? `Unblock-File` was introduced in PoSh 3.0, but I believe Flutter requires PowerShell 5.0 now.

I used gitbash 2.21.0.windows.1

**Comment by DanTup** [comment]
@anonymouse703 the script that's failing is running in PowerShell (gitbash presumably invokes it to run the .ps1 script), can you confirm what OS and version of PowerShell? You can get the PowerShell version by running "powershell" and then typing `$PSVersionTable.PSVersion`

**Comment by anonymouse703** [comment]
> $PSVersionTable.PSVersion

My OS is Windows 7 and my the powershell version is 2.0 how to upgrade this one? My laptop is 2011 version

**Comment by DanTup** [comment]
I think you probably need to install:

https://www.microsoft.com/en-us/download/details.aspx?id=54616

It's Windows Management Framework which is what includes PowerShell. You may need to first install .NET Framework 4.5.2 if you don't already have it.

**Comment by rakz25** [comment]
After installing https://www.microsoft.com/en-us/download/details.aspx?id=54616 in windows 7 facing same issues

**Comment by DanTup** [comment]
@rakz25 what's the output of running `$PSVersionTable.PSVersion` in the PowerShell window?

**Comment by TurnusSilver** [comment]
> I think you probably need to install:
> 
> https://www.microsoft.com/en-us/download/details.aspx?id=54616
> 
> It's Windows Management Framework which is what includes PowerShell. You may need to first install .NET Framework 4.5.2 if you don't already have it. Let us know if that solves the problem or not.

**Won't it produce any other adverse effect?**

**Comment by DanTup** [comment]
@TurnusSilver I wouldn't expect so, but I couldn't say for certain since it's not something I'm very familiar with. It's been out for a long time though and lots of people have installed it though, so I'd expect any significant backwards-compatibility issues would've been found and fixed.
