### ISSUE TITLE
Exceptions thrown in onGenerateRoute get swallowed

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#30650]
If you create a `MaterialApp` with an `onGenerateRoute` handler that throws an exception, the exception gets swallowed somewhere in the framework (nothing in the logs).

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/issues/28531 might be a related issue. We might want to find and give warnings (maybe in dart analyze) to all places where exceptions are caught but swallowed.

**Comment by Hixie** [comment]
This code certainly isn't trying to swallow exceptions...

**Comment by tvolkert** [comment]
Now that I try to come up with a reproducible test case, I can no longer reproduce (that'll teach me to file a bug without a reproducible test case to begin with!).

Closing.
