### ISSUE TITLE
[macos] Full IME support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30660]
Text input in the macOS shell is currently minimal; we need full unicode support using system IMEs.

**Comment by chopikus** [comment]
So, now, while the unicode in flutter's embedder is not fully supported, you can use go-embedder, which works really good.
https://github.com/go-flutter-desktop/go-flutter

**Comment by stuartmorgan** [comment]
This needs an audit to establish the current state. There's at least IME(Input Method Editor) position error google/flutter-desktop-embedding#345 (I'm not sure if just doing the accessibility API work will resolve that, or we'll need additional work), and we should see if we should be doing any text marking for in-progress compositions (which I know we're currently never sending).

**Comment by GreenLim** [comment]
Is there any progress?  If you use CJK input method, you will always get a wrong word candidate window position.

**Comment by cbracken** [comment]
As of flutter/engine#24533, the composing region is displayed while typing, but the candidates menu is still not positioned and candidate selection is not implemented.

**Comment by knopp** [comment]
@cbracken, I've referenced two PRs that position the candidates menu. I'm not sure what to do about candidate selection through. That is generally implemented by sending arrow key events to `[textInputContet handleEvent:]`. However right now flutter handles all arrow events. I think ideally all keyboard events should be passed to the TextInputPlugin and caret movement / selection should be driven through `NSStandardKeyBindingResponding` methods. That way the experience should be as close to native as possible.

**Comment by stuartmorgan** [comment]
> caret movement / selection should be driven through `NSStandardKeyBindingResponding` methods.

The issue currently is that the framework also does all of that, and if the framework and the engine get out of alignment they fight each other. @gspencergoog and I have talked about changing the source of truth on some of this, but deciding exactly what goes where is something that should be carefully thought (and design-doc'd) out across all platforms rather than continuing to tweaked per platform, IMO.

**Comment by gspencergoog** [comment]
@knopp The keyboard events need to pass through the framework before being sent to the `TextInputPlugin` so that the framework has a chance to override them.  As one example, the TAB key needs to be interpreted as a focus change, and it can't do that if the text field inserts TAB. I agree that caret movement should be driven through the `NSStandardKeyBindingResponding` methods, however. I realize that those two statements are at odds with each other, which is why we need to do some design work around this, as Stuart said. It may be that we need another way to represent caret movement, or that on macOS/iOS that there shouldn't be any default bindings on the framework side for caret movement. The developer should still be able to override those key events, however, and even prevent caret movement by overriding those keys if they want to.

**Comment by knopp** [comment]
One thing to consider here is that framework may not be able to determine whether arrow key moves caret or selection in candidates menu, so TextInputContext as source of truth might not be optional.

@gspencergoog, I agree completely that framework should have first go at the keyboard event and then pass it on. I do realize that this requires a lot more thinking upfront so I wasn't even trying to implement it :) The positioning of menu on the other hand is lot more straightforward.

**Comment by knopp** [comment]
Also, regarding the input being stuck in compositing mode, I have this: https://github.com/flutter/engine/pull/24866 . Not sure if there is any better way to fix it, there doesn't seem to be any specific notification from system to end compositing.

**Comment by cbracken** [comment]
At this point, the remaining known issues on macOS are:
1. https://github.com/flutter/flutter/issues/78061: Backspace collapses composing region on macOS
2. https://github.com/flutter/flutter/issues/64741: Setting composing range to TextRange.collapsed(0) on macOS breaks text input

**Comment by YeungKC** [comment]
related to #85328

**Comment by cbracken** [comment]
Closing in favour of the two remaining issues listed above.
