### ISSUE TITLE
InputDecoration: option to always float label

### ISSUE THREAD

**Issue by cpboyd** [flutter/flutter#30664]
## Steps to Reproduce

It would be nice if there was something like Angular Material's `floatLabel` property to force the label to float which also would show the hint, prefix (as requested in #19488), and suffix: https://material.angular.io/components/form-field/examples

Currently, the InputDecorator only takes into account if the input is empty or focused:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L1616

## Logs

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/chris/dev/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/chris/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/chris/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Users/chris/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by HansMuller** [comment]
CC @justinmc 

This seems like a reasonable feature to add to InputDecorator et al.

**Comment by edster9** [comment]
I would be awesome to have an always float label option... IMHO, it will make the text field more descriptive if it has a label and hint assigned.

**Comment by samuelg123** [comment]
Hi,
I'm also getting issue about the prefix. Still waiting for this update. Thanks

**Not focus**:
<img width="200" alt="portfolio_view" src="https://user-images.githubusercontent.com/12625711/62941070-5f9dd480-bdff-11e9-9fdf-7d3de2dcd1eb.png">

**Focus**:
<img width="200" alt="portfolio_view" src="https://user-images.githubusercontent.com/12625711/62941075-6298c500-bdff-11e9-84c1-d0e715f6df91.png">

**Comment by athornz** [comment]
Any progress here? Definitely a would be a great feature.

**Comment by justinmc** [comment]
I haven't had a chance to work on this, but I agree it seems like a good reasonable feature.  If anyone wants to try working on this in the meantime, please do!  The code that handles the label's animation to the floating position would probably need to be short circuited. See: https://github.com/flutter/flutter/blob/50c8e6b2d614eebd2bbfe810789d9b8566b52637/packages/flutter/lib/src/material/input_decorator.dart#L1867

**Comment by claudneysessa** [comment]
I have an implementation for that!
Do you want to send for inclusion in the official is possible?

**Comment by justinmc** [comment]
Closing this with https://github.com/flutter/flutter/pull/46115

**Comment by BigBrosh** [comment]
@athornz @justinmc thanks for a great feature!
I'm not sure if I'm missing something but how do I make hint visible with FloatingLabelBehavior.always?

**Comment by justinmc** [comment]
@BigBrosh No problem!  Is this what you're looking for, or do you want the hint to be visible even without focus? https://dartpad.dartlang.org/ac99026caecbd2824f8ec57b7ce20da4

**Comment by BigBrosh** [comment]
@justinmc yeap, even without focus :)

**Comment by justinmc** [comment]
Could you create a new issue for that and mention me in it?  I think that might be a bug.  It seems logical that the hint should be visible in the dartpad above, though I can't seem to find an example proving that in the [Material text field docs](https://material.io/components/text-fields).
