### ISSUE TITLE
GLFW shell crashes on minimization

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30668]
Minimizing the window crashes the application under the GLFW implementation; `GLFWFramebufferSizeCallback` is called with a zero size. There's a bug in the GLFW shell (`window_pixels_per_screen_coordinate` calculation needs a zero guard), but fixing that leads to a crash below the shell level, so this will need further debugging/fixing.

**Comment by deekay42** [comment]
Any progress on this? I just tested this and it's still crashing.

**Comment by stuartmorgan** [comment]
That's why the bug is still open.

(Unassigning to reflect the fact that I'm not actively working on this at the moment; if someone want to pick it up before I get to it, they should feel free to do so.)

**Comment by stuartmorgan** [comment]
> fixing that leads to a crash below the shell level, so this will need further debugging/fixing

I'm no longer seeing this, so apparently all that we need now is the trivial fix.

**Comment by stuartmorgan** [comment]
Fixed in https://github.com/flutter/engine/pull/9278
