### ISSUE TITLE
[windows] Full IME support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30661]
Text input in the Windows shell is currently minimal; we need full unicode support using system IMEs.

**Comment by chopikus** [comment]
So, now, while the unicode in flutter's embedder is not fully supported, you can use go-embedder, which works really good.
https://github.com/go-flutter-desktop/go-flutter

**Comment by shoryukenn** [comment]
This is a relatively complicated and relatively long-term job. Is there anyone here to follow up on this issue? If not, I can start doing this.

**Comment by stuartmorgan** [comment]
Yes, it's definitely going to be a significant task. Nobody is currently slated to work on it, so if you want to take in on that would be great.

**Comment by shoryukenn** [comment]
Ok, I will evaluate the plan first.

**Comment by godot0413301** [comment]
hayhv says he integrated support unicode on windows.Is this useful?
https://github.com/google/flutter-desktop-embedding/issues/309#issuecomment-475845560

> Ok, I will evaluate the plan first.

hayhv says he integrated support unicode on windows.Is this useful?
https://github.com/google/flutter-desktop-embedding/issues/309#issuecomment-475845560

**Comment by shoryukenn** [comment]
> > Ok, I will evaluate the plan first.
> 
> hayhv said he integrated support unicode on windows.Is this useful?
> [google/flutter-desktop-embedding#309 (comment)](https://github.com/google/flutter-desktop-embedding/issues/309#issuecomment-475845560)

I think this idea is correct, but you need to use platform-independent code as much as possible.

**Comment by shoryukenn** [comment]
@stuartmorgan @gspencergoog 
PR: https://github.com/flutter/engine/pull/11899

**Comment by stuartmorgan** [comment]
This should be much better with @shoryukenn's PR landed (once the next engine roll into the framework happens). It's still using index-based logic for things like backspace, which means that even with the new UTF-32 model, combining characters are still going to have issues. Longer term, we'll need to use full unicode handling in the model (and likely switch back to UTF-8 at that point).

**Comment by stuartmorgan** [comment]
Moving to Releasable; the current level of unicode handling on Windows is likely fine for alpha.

**Comment by stuartmorgan** [comment]
I think with the last round of fixes this is in pretty good shape. The remaining known issue is grapheme cluster handling with arrow keys and delete/backspace, but that's already being tackled in the framework (and may or may not need fixes in the embeddings once done).

Given that, I'm going to close this, and if there are any specific things that are still not working, please file new bugs so we can track the specific issues.
