### ISSUE TITLE
Firebase Errors are not documented.

### ISSUE THREAD

**Issue by pepsighan** [flutter/flutter#30666]
All the possible errors that are thrown in Flutter while using Firebase (for ex: `firebase_auth`) are not documented. 

For example:

https://github.com/flutter/plugins/blob/6eb5d634249ae49226509686c5050de33bd66b56/packages/firebase_auth/lib/src/firebase_auth.dart#L264-L274 

The `signInWithCredential` only documents 4 errors whereas in my app 'ERROR_SESSION_EXPIRED' was thrown (not one of them). Looking to the Android platform code, I found:

https://github.com/flutter/plugins/blob/6eb5d634249ae49226509686c5050de33bd66b56/packages/firebase_auth/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java#L749-L761

In the above code, you'll find only three viewable error codes, whereas others are coming from the Firebase Java API land (for whom I could not find an exhaustive list of errors page).

Also, in the dart land, it would be awesome if all these error codes and messages could be translated to normal dart errors rather than checking on `error.code`.
We get the documentation of all errors for free while providing confidence in our app (no typos).

**Comment by escamoteur** [comment]
Please ask at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!
