### ISSUE TITLE
Implement release mode for desktop shells

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30672]
This would almost certainly be AOT, although it's potentially possible that it could be a JIT with symbols removed depending on performance characteristics.

**Comment by stuartmorgan** [comment]
See some discussion of early experiments in https://github.com/google/flutter-desktop-embedding/issues/129#issuecomment-480006463

**Comment by stuartmorgan** [comment]
Since release support for the three different platforms will have different schedules, I'm splitting this into #38476, #38477, and #38478. Closing in favor of those.

**Comment by ping996** [comment]
How to use the flutter build bundle to build an AOT flutter app now?

**Comment by stuartmorgan** [comment]
`flutter build bundle` is not used by the desktop embeddings, so that's not relevant to this issue. (Also, this issue is closed, and work is being tracked by platform in the issues linked above per my previous comment.)
