### ISSUE TITLE
HTTP local wifi without internet connection

### ISSUE THREAD

**Issue by wald-tq** [flutter/flutter#30678]
I am creating a app that uses a wifi to connect to a embedded device and request information via HTTP and the local fixed IP address.

Everything works fine as long as the test devices don't have a sim card in the device.

If I use a sim card and have a active data connection (EDGE, 3G, LTE) the app seems to ignore the wifi connection and tries to connect to the ip address with the wrong mobile data network interface.

This only affects android. Tested on a Pixel 2. Android reports the wifi as "without internet connection".

I found following infos on the net: 
* https://android-developers.googleblog.com/2016/07/connecting-your-app-to-wi-fi-device.html
* https://stackoverflow.com/questions/42329775/using-a-wifi-without-internet-connection/51470122#51470122
* https://stackoverflow.com/questions/36653126/send-request-over-wifi-without-connection-even-if-mobile-data-is-on-with-conn/51469732#51469732

How can I make the HTTP requests with flutter to the http server in the wifi?

## Steps to Reproduce

1. You need a wifi with an http server but no internet connection
2. Connect the device to the wifi and a mobile data connection 
3. Make a call from flutter-app to the http-server GET http://192.168.1.1

## Logs

```
> flutter doctor -v
[√] Flutter (Channel master, v1.3.15-pre.26, on Microsoft Windows [Version 10.0.14393], locale de-DE)
    • Flutter version 1.3.15-pre.26 at E:\dev\flutter
    • Framework revision 6e50ccc803 (13 days ago), 2019-03-26 15:26:13 +0800
    • Engine revision 0d83a2ecd1
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\wald-tq\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\wald-tq\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.io/setup/#android-setup for detailed instructions.

[!] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.33.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by wald-tq** [comment]
We did a workaround using our forked library: https://github.com/tq-systems/WiFiFlutter

We used the function forceWifiUsage():
https://github.com/tq-systems/WiFiFlutter/blob/master/lib/wifi_iot.dart#L161

In my opinion this should be possible with the flutter http package, because of the handling of android.

**Comment by escamoteur** [comment]
@wald-tq did you try using the `HttpClient`from dart:io? It's way more configurable

Have you tried this again lately?

**Comment by wald-tq** [comment]
We tried it with dio and http. It was before flutter 1.7 I think.

It has to support somehow to call bindProcessToNetwork:
https://github.com/tq-systems/WiFiFlutter/blob/master/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L490

or setProcessDefaultNetwork:
https://github.com/tq-systems/WiFiFlutter/blob/master/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L497

At first glance I couldn't find it in the dart:io docs.

**Comment by timsneath** [comment]
Glad you found a workaround by calling the underlying native APIs.

Binding to a specific network adapter is not something we're planning to support in the `http` package at this time, so I'm closing this issue for now. 

Thank you for updating it with your solution -- this will help others who may have the same need.
