### ISSUE TITLE
http.MultipartRequest doesn't send a request to my localhost with 5000 port.

### ISSUE THREAD

**Issue by dailyInsight6** [flutter/flutter#30679]
I am trying to use http.MultipartRequest. As you can see the capture below, I got connection refused error when I send the request to my local server, and it shows that my port is 63210. Actually, my Uri has a port with 5000. Anyone can help me to assign my request port?

![Screen Shot 2019-04-08 at 2 12 50 AM](https://user-images.githubusercontent.com/17200314/55712771-34642e00-59a4-11e9-9d2f-cee7443e27ae.png)

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
