### ISSUE TITLE
flutter upgrade printing progress bar on many lines

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3068]
I'm not sure if this is by design? Could we have a single line for the progress bar?

![screen shot 2016-04-04 at 8 49 58 am](https://cloud.githubusercontent.com/assets/5479/14253911/56c82a7e-fa42-11e5-964d-d19c3a53dc9a.png)

```
~/Code/flutter/examples/material_gallery[master*] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision daa0d2d (9 hours ago); engine revision 13f6734
```

I'm on a Mac, in the standard Mac terminal.

**Comment by eseidelGoogle** [comment]
This is a recent regression, likely relating to nesting flutter processes.

**Comment by Hixie** [comment]
The progress bar comes from `curl`. Maybe we're turning `\r`s into `\n`s?

**Comment by devoncarew** [comment]
We might be able to bisect this. I saw it first this weekend.

**Comment by devoncarew** [comment]
Mostly fixed with https://github.com/flutter/flutter/pull/3180 and https://github.com/flutter/flutter/pull/3168. We now display our own progress from Dart, for all but the dart sdk download.

**Comment by devoncarew** [comment]
Fixed now - please re-open if you see this again.
