### ISSUE TITLE
Widget inside Visibility validate data That in the visible condition

### ISSUE THREAD

**Issue by abdallah-gaber** [flutter/flutter#30682]
When I use Visibility Widget and type condition in visible parameter, and inside its child widget I use these values that I checked to not be null in the visible parameter so if crashes (cause error) in this widget, I think this is not the right way, because it should be the replacement of this scenario:
CONDITION ? MY_WIDGET : EMPTY_CONTAINER
and with this way it doesn't fail because I use values in MY_WIDGET that I already checked it on the CONDITION.  

## Steps to Reproduce

1. Create ListView.builder that depends on List data
2. Create on the returned widget Visibility Widget that its child display or do operation on data of the list that may be = null, and make the visible parameter checks if these data != null 

## Logs

I/flutter ( 3928): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3928): The following NoSuchMethodError was thrown building:
I/flutter ( 3928): The method '_subFromInteger' was called on null.
I/flutter ( 3928): Receiver: null
I/flutter ( 3928): Tried calling: _subFromInteger(30)
I/flutter ( 3928): 
I/flutter ( 3928): When the exception was thrown, this was the stack:
I/flutter ( 3928): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 3928): #1      int.- (dart:core/runtime/libintegers.dart:11:38)
I/flutter ( 3928): #2      _InstitutionOffersScreenState.build.<anonymous closure>.<anonymous closure> (package:hadd_institution_owner/View/screens/institution_offers/institution_offers_screen.dart:263:76)
I/flutter ( 3928): #3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:398:15)
I/flutter ( 3928): #4      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1002:67)
I/flutter ( 3928): #5      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:137:29)
I/flutter ( 3928): #6      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1002:26)
I/flutter ( 3928): #7      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1015:55)
I/flutter ( 3928): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter ( 3928): #9      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1008:11)
I/flutter ( 3928): #10     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter ( 3928): #11     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1728:58)
I/flutter ( 3928): #12     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter ( 3928): #13     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1728:13)
I/flutter ( 3928): #14     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter ( 3928): #15     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:407:5)
I/flutter ( 3928): #16     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
I/flutter ( 3928): #17     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
I/flutter ( 3928): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 3928): #19     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter ( 3928): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 3928): #21     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter ( 3928): #22     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter ( 3928): #23     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter ( 3928): #24     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter ( 3928): #25     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 3928): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter ( 3928): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 3928): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 3928): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 3928): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 3928): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 3928): #35     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 3928): #36     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 3928): (elided 3 frames from package dart:async)
I/flutter ( 3928): ════════════════════════════════════════════════════════════════════════════════════════════════════

Analyzing hadd_institution_owner...

   info - Unused import: 'package:hadd_institution_owner/network/api_urls.dart' - lib\View\screens\add_edit_institution\widgets\institution_video_description_dialog.dart:3:8 -
          unused_import
   info - The value of the field '_branches' isn't used - lib\View\screens\institution_details\widgets\institution_branches_widget.dart:5:26 - unused_field
   info - The value of the field '_institutionOffers' isn't used - lib\View\screens\institution_details\widgets\institution_offers_widget.dart:5:32 - unused_field
   info - Unused import: 'package:hadd_institution_owner/network/api_urls.dart' - lib\View\screens\institution_details\widgets\institution_videos_widget.dart:4:8 - unused_import
   info - The value of the field '_mainBranch' isn't used - lib\View\screens\institution_details\widgets\main_branch_widget.dart:5:20 - unused_field
   info - The value of the field '_phone' isn't used - lib\View\screens\institution_details\widgets\name_address_main_buttons_widget.dart:5:34 - unused_field
   info - The value of the field '_googleMap' isn't used - lib\View\screens\institution_details\widgets\name_address_main_buttons_widget.dart:5:42 - unused_field
   info - The value of the field '_website' isn't used - lib\View\screens\institution_details\widgets\name_address_main_buttons_widget.dart:5:54 - unused_field
   info - The value of the field '_mobiles' isn't used - lib\View\screens\institution_details\widgets\name_address_main_buttons_widget.dart:6:22 - unused_field
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: SetNewPasswordView._childInstance -
          lib\View\screens\reset_password\widgets\set_new_password_view.dart:6:7 - must_be_immutable
   info - Name non-constant identifiers using lowerCamelCase - lib\util\common_styles.dart:5:20 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\util\common_styles.dart:10:20 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\util\common_styles.dart:14:20 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\util\common_styles.dart:19:20 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\util\common_styles.dart:24:20 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\util\common_styles.dart:29:20 - non_constant_identifier_names
   info - Name types using UpperCamelCase - lib\util\style.dart:3:7 - camel_case_types

17 issues found. (ran in 7.6s)

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

**Comment by jonahwilliams** [comment]
This is intentional, the `Visibility` widget is not a replacement for `if/else` conditions. You could conceivably define a new widget which passed the child as a thunk to avoid evaluation of nulls, but it would be too breaking to change the existing widget to this behavior.

Example:

```
class Conditional extends StatelessWidget {
  Conditional({this.show, this.thunk, this.placeholder});

  final bool show;
  final Widget Function(BuildContext) thunk;
  final Widget placeholder;

  Widget build(BuildContext context) {
    if (show) {
       return thunk();
    }
    return placeholder;
  }
}

```

**Comment by darek607** [comment]
Now there is a `replacement` property in Visibility widget that can be set to `SizedBox.shrink()`
