### ISSUE TITLE
Live streaming

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#30687]
Hello! Flutter is developing rapidly, which is very nice, but the needs of users (flutter clients) are growing, for example, after surfing the Internet in the repository, I still don’t understand whether it is possible to transfer video from camera to server using flutter, for example, to play a Live broadcast There is a video_player plugin via the hls protocol, but is there a reverse solution, giving the video stream to the server? There are wonderful webrtc, but I have not yet met streaming services using webrtc.
I think this topic will interest many.

**Comment by gbaski** [comment]
The demand is much, RTMP plugin for flutter to publish and playback. WebRTC might be no go area, I have been dealt with, codec incompatibility.  VP8 vs H.264

**Comment by floriangbh** [comment]
We are also waiting for RTMP support ! 👍

**Comment by himiku** [comment]
i hope it will come to reality eraly..

**Comment by premy** [comment]
Doesn't this package do exactly that?
https://pub.dev/packages/flutter_rtmp_publisher

**Comment by ollydixon** [comment]
@premy the package is broken and it uses some custom view instead of a normal view.

**Comment by Loopex2019** [comment]
Any News on that

**Comment by ollydixon** [comment]
I have a fork here which works very well with capturing live video: https://github.com/ollydixon/flutter_rtmppublisher

**Comment by luis901101** [comment]
Very necessary an official plugin supporting Live Streaming through RTMP and if possible the new SRT protocol. I have tested a lot of streaming plugins on pub.dev and wasted a lot of time, finally I found this one [apivideo_live_stream](https://pub.dev/packages/apivideo_live_stream) which seems good enough for RTMPS

**Comment by stuartmorgan** [comment]
Closing, as this is out of scope for the Flutter team. This is something that would be best implemented by the community via plugins using third-party streaming SDKs.
