### ISSUE TITLE
async behaviour of an Isolate's top level function

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#30683]
Aye aye good people,

I'm experiencing a weird behavior

when using the top level function of an isolate asynchronously;

you can find example code [here](https://github.com/iapicca/isolates_logging),

as top level function of an isolate this works:

> String _syncHandle(int data) {
>   return 'done';
> }

and this doesn't:

> Future<String> _syncHandle(int data) async {
>   return 'done';
> }

can anybody explain me why?

(or if should work, why isn't doing so in my code?)

I noticed that I'm not the first one to ask this question, 
which anyway was never answered
https://github.com/flutter/flutter/issues/17671.

I'm begging for help also in [Stackoverflow](https://stackoverflow.com/questions/55571179/dart-flutter-async-behaviour-of-an-isolates-top-level-function) and I can say that I'm [not the only one](https://stackoverflow.com/questions/50334869/call-async-function-from-isolate-function/55571355#55571355) with this problem.

thank you in advance for any help you can give me

Francesco

**Comment by DaGump** [comment]
I can second that problem same here! Simple setup: I have an async encryption method called inside of my isolated method.
**how I call/create the Isolate:**
`ReceivePort receivePort =ReceivePort(); //port for this main isolate to receive messages.

_isolate = await Isolate.spawn(_encryptVault,receivePort.sendPort);

receivePort.listen((data) {
        print("Continue with my work");
        _refresh();
      });`

now what happens:
### Empty Method:
`String _encryptVault(SendPort port) {
      print("encrypting vault");
      return "test";
}`
#### This works like charm.

### Async Method:
`String _encryptVault(SendPort port) async {
      print("encrypting vault");
      String key = await Encoder.encrypt();
      print("vault encrypted");
      return key;
}`
#### This does not work
the outout is
> encrypting vault


### Sync Method with "then":
`String _encryptVault(SendPort port) {
      print("encrypting vault");
      String key = await Encoder.encrypt().then((key) {
            print("vault encrypted");
            return key;
      });
}`
#### This does not work
the outout is
> encrypting vault

**Comment by DaGump** [comment]
##And in case there is a need. Thats the output of my flutter doctor:

> C:\src\flutter\bin\flutter.bat doctor --verbose
> [√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.107], locale de-AT)
>     • Flutter version 1.2.1 at C:\src\flutter
>     • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\mga\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 34.0.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
> 
> [√] Connected device (1 available)
>     • FRD L09 • 73QDU17517001330 • android-arm64 • Android 7.0 (API 24)
> 
> • No issues found!
> Process finished with exit code 0

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
I was young and inexperienced....
and I was passing "send.send" in the isolate pretending to get back complex data
