### ISSUE TITLE
Error when running 'flutter clean'

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#30681]
## Steps to Reproduce

when running **flutter clean**
Deleting 'build\'.
FileSystemException: Deletion failed, path = 'build' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

**Comment by jonahwilliams** [comment]
It seems like you might have a running instance of Gradle or Xcode running. You'll have to exit those processes before flutter clean will work.
