### ISSUE TITLE
Possibly compromised installer available via Homebrew

### ISSUE THREAD

**Issue by bhagyas** [flutter/flutter#30686]
The following GitHub issue on installing Flutter via Homebrew is having references to a possibly insecure third party repository for installing Flutter for Chinese users.

https://github.com/flutter/flutter/issues/14050

Please look into this.

**Comment by HansMuller** [comment]
CC @xster

**Comment by xster** [comment]
You'd have to be more specific. Flutter never published any homebrew formulae for Flutter.

**Comment by bhagyas** [comment]
@xster I was about to attempt to install Flutter via the brew formula recommended as in the following comment. However, I had a look at the brew tap available on the repository recommended.

https://github.com/flutter/flutter/issues/14050#issuecomment-473217774

It appears to talk to an unknown server and make IP address based lookups and serves a different Flutter distribution with geographical discriminations. 

I ended up writing my own that cloned directly from Git.

Having the earlier comment on Flutter issues for Homebrew exposes potential Flutter developers to unknown risk.

**Comment by brianmorton** [comment]
@xster if you guys could just release the official homebrew tap as you alluded to [here](https://github.com/flutter/flutter/issues/14050#issuecomment-386153555) that would be great - this seems to be in demand.

**Comment by ivicel** [comment]
@bhagyas
if your ip located at China, it will download flutter from https://flutter-io.cn
which is an official trusted mirror 
see this:  https://flutter.dev/community/china

**Comment by jonahwilliams** [comment]
Its not clear to me what the difference is between this issue and #14050. Likewise as @xster pointed out, we do not currently provide a homebrew distribution
