### ISSUE TITLE
unit testing exception

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#30695]
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

package:flutter/src/services/platform_channel.dart 300:7  MethodChannel.invokeMethod
===== asynchronous gap ===========================
dart:async                                                _AsyncAwaitCompleter.completeError
package:flutter/src/services/platform_channel.dart        MethodChannel.invokeMethod
===== asynchronous gap ===========================
dart:async                                                _asyncThenWrapperHelper
package:flutter/src/services/platform_channel.dart        MethodChannel.invokeMethod
package:shared_preferences/shared_preferences.dart 28:27  SharedPreferences.getInstance

https://github.com/dart-lang/test/blob/master/pkgs/test/README.md

I wrote with reference to this README，Results appear:
![](https://ws3.sinaimg.cn/large/005BYqpgly1g1vkx9csrqj30bg081t9h.jpg)

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
