### ISSUE TITLE
Support 'flutter create' for Linux targets

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30705]
Once the shell is sufficiently mature, we need to support creation of a Linux runner from a template using `flutter create`.

The lack of a de-facto standard toolchain means we'll need to figure out what the default runner will use, both in terms of compiler (gcc? clang? try to support both?) and build system (make? cmake? gn+ninja?), as well as whether we'll require them to be installed by the developer, or use internally-managed copies.

Relatedly, we'll need to figure out how to handle runner dependencies. E.g., if the shell ends up being GTK-based, then the runner will have GTK dependencies, which will need to either be managed internally, or covered by `flutter doctor`

**Comment by handicraftsman** [comment]
It would be a nice choice to provide some means of packaging for Linux applications, like flatpak or snap. Meanwhile building for flatpak means that you can just get the toolchain and the build system there, so there is no need to ask users to install an additional toolchain. Although flatpak enforces CamelCase application name (the last segment) in its id iirc.

**Comment by stuartmorgan** [comment]
Closing since the pre-stable support for `create` landed. Remaining work to make it stable is tracked in https://github.com/flutter/flutter/issues/52749.
