### ISSUE TITLE
Support copy/paste in macOS shell text input

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30709]
We need to support clipboard.getData and clipboard.setData, as well as shortcut keys for copy and paste.

**Comment by stuartmorgan** [comment]
Shortcut keys will need to wait for Action support, but wiring up the clipboard.* channels should be straightforward.

**Comment by alexelisenko** [comment]
@stuartmorgan I see that there was something merged to master for MacOS, but I wanted to confirm if this is now working? If not, any ETA on this would be greatly appreciated.

**Comment by franciscojma86** [comment]
This change was merged into the framework in [this commit](https://github.com/flutter/flutter/pull/34466).

You can now copy and paste strings into/from the system clipboard, but there are no keyboard shortcuts for it yet.

**Comment by alexelisenko** [comment]
@franciscojma86 This is probably out of scope of this issue, but, how would one access the system clipboard without the keyboard shortcuts?

**Comment by stuartmorgan** [comment]
> how would one access the system clipboard without the keyboard shortcuts?

https://api.flutter.dev/flutter/services/Clipboard-class.html

**Comment by BrunoEleodoro** [comment]
@stuartmorgan I'd like to contribute to that issue, can someone show me the path that I have to take to start contributing and try to solve that issue.

Thanks.

**Comment by stuartmorgan** [comment]
We need a way to coordinate between the Edit menu and the current focus state in Flutter, so that the enable state of Cut/Copy/Paste in the Edit menu is correct, and sends the message to Flutter. @gspencergoog has given this some thought already, so may be able to provide more detail on how to approach this.

**Comment by BrunoEleodoro** [comment]
@gspencergoog Hi Greg! can you help me with some tutorial or how I can help you on that.

Thanks.

**Comment by technolion** [comment]
As I see it, this issue is one of the few remaining show-stoppers that keeps developers to release flutter-based macOS applications (based on master channel), since you all did such a great job to advance macOS support.

Is there any chance copy/paste support gets implemented soon?

**Comment by gspencergoog** [comment]
I actually haven't started looking at the menu support yet, but it's on my radar. We should have the cmd-x/cmd-c/cmd-v support working fairly soon. There is an issue with detecting modifier keys in the keyboard handling: https://github.com/flutter/flutter/issues/38076 Once that gets fixed, it should be simple to add support for keyboard copy/paste in text fields, and the menu support will follow.  cc/ @franciscojma86

**Comment by technolion** [comment]
Great, thank you!

**Comment by gspencergoog** [comment]
I'm going to close this, as I believe that the only remaining work here is to coordinate it with the menu bar, and that would be covered by https://github.com/flutter/flutter/issues/23600.

**Comment by technolion** [comment]
There still seem to be problems with cmd-x/cmd-c/cmd-v/cmd-a support, which stops working after switching between flutter app and other apps. Please see #46151
