### ISSUE TITLE
Support 'flutter build' for desktop targets

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30706]
Tracks being able to `flutter build` for macOS, Windows, and Linux.

In the long term this would use the templates created by `create` (see #30703, #30704, and #30705), but shorter term—and also longer-term to support use cases other than `flutter create`, such as Add-to-App—it would be good to support pluggable build steps.

**Comment by stuartmorgan** [comment]
Any support we can provide for this in the short term is very valuable for the workflow of people trying out early stages of the desktop support, since if it's possible to do one-time setup of a pluggable build step, then once the project is set up manually, the edit-build-run/debug cycle in IDEs that support Flutter will work for free.

**Comment by stuartmorgan** [comment]
For macOS, things I'm aware of remaining within the scope of this bug:
- [ ] Eliminate the need for `name_output.sh`
- [ ] Finalize the copying of resources (e.g., standardizing on putting things in `macos/Flutter/`)
- [ ] Finalize the name/location(s) of the script(s)/command(s) that Xcode invokes

**Comment by ammaratef45** [comment]
This is essential, I can't rely on a code that can't be built and delivered.

**Comment by stuartmorgan** [comment]
I think given the plans around `assemble` and other related plans, we can just close this now. Originally I was leaving it open until the interactions were finalized, but the current state is that building works on all desktop platforms in an initial state. We'll be doing a lot of incremental changes/improvements, and it makes more sense to track those in individual bugs (which in fact is already happening) rather than a single large bug.
