### ISSUE TITLE
Support 'flutter run' for desktop targets

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30707]
Tracks being able to `flutter run` for macOS, Windows, and Linux.

This will likely be implemented in phases, first being able to `flutter run` using a prebuilt application on each platform (already implemented behind flags for macOS), then later once #30706 is done having the full behavior of building and then running.

Any support we can provide for this in the short term is very valuable for the workflow of people trying out early stages of the desktop support, since being able to `flutter run` provides compatibility with existing Flutter support in tools and IDEs (e.g., hot reload, and source-level debugging).

**Comment by stuartmorgan** [comment]
cc @jonahwilliams who has been working on aspects of this already.

**Comment by jonahwilliams** [comment]
We can flutter run the prebuilt macos application, linux and windows need to be done though

**Comment by stuartmorgan** [comment]
We also need to figure out how to bring it out from [behind an environment variable flag](https://github.com/flutter/flutter/blob/c1fabb9860fa04b6a81d4e70637c12907628572b/packages/flutter_tools/lib/src/desktop.dart#L7). In practice, that's been a significant issue for actually using the functionality, because adding a flag to the launch environment of the flutter daemon used by VS Code or IntelliJ isn't a simple thing to do.

**Comment by jonahwilliams** [comment]
I have two fixes for this:

1. Disable the devices/commands on the stable branch https://github.com/flutter/flutter/issues/30152

2. update device discovery to take the current project into consideration. For example, if you have `ios/` and `android/`, then we don't list a `macos` device.

**Comment by jonahwilliams** [comment]
Filled https://github.com/flutter/flutter/issues/30724 for 2.
