### ISSUE TITLE
Embedding platform views into ClipRRect not working

### ISSUE THREAD

**Issue by RafaO** [flutter/flutter#30715]
## Steps to Reproduce
I am not able to wrap the google map widget within a ClipRRect so it displays rounded corners.
```
    return ClipRRect(
      borderRadius: BorderRadius.all(Radius.circular(25.0)),
      child: Container(
        height: 200.0,
        child: GoogleMap(
            initialCameraPosition: CameraPosition(target: LatLng(0.0, 0.0))),
      ),
    );
```

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
