### ISSUE TITLE
Tab underline in Buttons isn't centered

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3071]
![screenshot_20160404-091631](https://cloud.githubusercontent.com/assets/5479/14254779/1d0e6e70-fa46-11e5-8a59-2aa25152f7d2.png)

Notice how the underline under RAISED isn't centered. This is after swiping over to RAISED.

**Comment by sethladd** [comment]
@HansMuller you recently rewrote tabs? Would it have addressed this?

**Comment by HansMuller** [comment]
This has been fixed.
