### ISSUE TITLE
Implement a view-based Linux shell

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30729]
The current Linux shell uses GLFW, which significantly limits flexibility. For instance, there's no way to do a hybrid window (for instance, putting a GTK menu bar at the top of an otherwise-Flutter window).

See previous discussion in https://github.com/google/flutter-desktop-embedding/issues/23

Given the lack of a standard toolkit, what exactly this should be is much less clear on Linux than on macOS or Windows. A likely outcome is that the shell would be implemented with GTK, but more research is needed.

**Comment by lukef** [comment]
re: Menus. Other than for macOS, is the menu bar feature something that has to be a system-level approach? Couldn't the menu bar be rendered in flutter and adapted for each platform or just implemented via a standard approach (a la Material)?

**Comment by stuartmorgan** [comment]
See the last part of https://github.com/google/flutter-desktop-embedding/issues/23#issuecomment-450419064

**Comment by handicraftsman** [comment]
Plasma shell can tell qt and gtk apps to hide the menubar and instead draw it in a separate panel. That was also done by now-discontinued Unity shell.

**Comment by mtcliatt** [comment]
Could the tag `customer: octopod` please be added to this issue?

**Comment by robert-ancell** [comment]
I've been working on a GTK Linux shell.

**Comment by r3flow** [comment]
the GTK shell is a good idea, for example a desktop application should able to use the "native" open/save dialogs too

**Comment by FIREFOXCYBER** [comment]
What about Qt shell? any plan for that?

**Comment by handicraftsman** [comment]
Sadly they have focused only on GTK in their docs.

**Comment by stuartmorgan** [comment]
There is currently no plan for a Qt embedding, but there's also nothing preventing adding one in the future. See https://github.com/flutter/flutter/wiki/Desktop-shells#linux

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/projects/142 is now tracking the work to get the GTK embedding to parity with the current GLFW implementation, for anyone interested in following that.

**Comment by stuartmorgan** [comment]
The switch from GLFW to GTK has landed, so this is now complete!
