### ISSUE TITLE
Implement a Win32/UWP desktop shell

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30726]
The current implementation on Windows is a temporary solution using GLFW; the goal is to implement a more flexible, view-based solution that could be used in an existing application, similar to what currently exists on macOS.

See previous discussion in https://github.com/google/flutter-desktop-embedding/issues/6 and https://github.com/google/flutter-desktop-embedding/issues/101.

**Comment by stuartmorgan** [comment]
CC @clarkezone who is working on this.

**Comment by stuartmorgan** [comment]
For cross-referencing, #14967 is general umbrella feature request for UWP. I'll leave this open separately since this is specifically tracking an initial shell implementation rather than the overall support.

**Comment by WesleyKhoiVo** [comment]
#29795

**Comment by WesleyKhoiVo** [comment]
As UWP developer, I am waiting GG support UWP too much

**Comment by stuartmorgan** [comment]
This actually should have been closed when the last PR above landed; we're now using a Win32 shell rather than the GLFW shell.

#14967 continues to track UWP specifically.
