### ISSUE TITLE
Code examples in "Write Your First Flutter App, part 1" are not working

### ISSUE THREAD

**Issue by netcyrax** [flutter/flutter#30739]
This codelab is working:
https://flutter.dev/docs/get-started/codelab

But not this one:
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1

**Comment by netcyrax** [comment]
According to https://github.com/flutter/flutter/issues/17049 this is fixed, but this code does not compile:
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

**Comment by MaterialTime** [comment]
What error are you getting?

**Comment by hsiehweb** [comment]
Did you **get the package**?
It works fine for me

**Comment by netcyrax** [comment]
My bad, I think it's working.
