### ISSUE TITLE
Add window/application lifecycle delegation for desktop shells

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30735]
Example use case: A document-based Flutter application should be able to prevent a window from being closed (e.g., with an alert) if the document corresponding to that window is unsaved.

At the very least plugins need to be able to register for application and window lifecycle events (as they can for application lifecycle on iOS), but we may want to consider making system channels for the most common cases.

**Comment by dschuyler** [comment]
Would this use the `AppLifecycleState` and `State<LifecycleWatcher>` or would it be some other mechanism (just asking to understand better)?

**Comment by stuartmorgan** [comment]
The specific case that this was originally filed for was delegation, not just observation, so at least some new mechanism would be needed. Supporting the existing lifecycle structure might be part of it though.

**Comment by stuartmorgan** [comment]
Capturing from a Discord discussion about autoupdate on Windows:

> Squirrel supports customizing installation and post-update by running your app with a special command-line flag --squirrel-install, --squirrel-updated, etc etc - your Flutter app needs to do what it wants for that customization (set up shortcuts, file associations, whatever), then immediately exit without opening a Window

Autoupdate is something that we want to facilitate building plugins for, so we should make sure there's a lifecycle hook that's before the window is displayed.

**Comment by hpoul** [comment]
Implementation of `AppLifecycleState` would be great. My use-case: auto-close/lock of open files when the app is in the background/idle for some time. Would be the easiest way to detect when the user hasn't interacted with the app for some time. (ie. `inactive` vs `resumed`)

**Comment by stuartmorgan** [comment]
> Implementation of `AppLifecycleState` would be great. My use-case: auto-close/lock of open files when the app is in the background/idle for some time. Would be the easiest way to detect when the user hasn't interacted with the app for some time. (ie. `inactive` vs `resumed`)

"Idle" isn't a clear, OS-defined application state, and would not be part of this. If you want to do something based on the user not interacting with the app for a while, that is something you would need to implement yourself based on what "idle" means to your use case.

**Comment by hpoul** [comment]
I'm aware, but i think `AppLifecycleState` would be part of this? And my use case is when window is not in focus (i guess that would probably equal to `AppLifecycleState.inactive`), app is idle  :) would be perfectly fine for this

**Comment by stuartmorgan** [comment]
Foreground/background would likely be exposed, but on at least some systems it's possible for users to interact with background windows, so maps poorly to "idle".

If what you want is foreground/background notifications, then yes, this issue is relevant, but that maps poorly to the use case you described ("to detect when the user hasn't interacted with the app for some time").

**Comment by hpoul** [comment]
@stuartmorgan sorry to spam this issue, what exactly do you mean with interacting with background windows? I guess it's possible to scroll in background windows, or have hover effects - do you mean this with interacting? I assume it's not possible anywhere to actively tap buttons or send keyboard events? 🤔️

it's also possible that `idle` is not the right word 😅️ I have also thought about listening on keyboard and/or mouse events but wasn't quite able to figure out how to add global listeners (I assumed somewhere between `SystemChannels.mouseCursor` / `keyEvent` and `GestureBinding` but kind of hit a dead end there since most seem to only allow a single callback. In the end I thought simply detecting the app getting `inactive` would fit my problem easier anyway and would be nicely mapped to how it could work on mobile as well).

**Comment by stuartmorgan** [comment]
> I assume it's not possible anywhere to actively tap buttons or send keyboard events?

This assumption is not correct, at least on macOS.

**Comment by Tasen-pro** [comment]
But how can we respond to AppLifeCycle events in desktop? Will this be available soon or its not implemented for any specific reason?

**Comment by stuartmorgan** [comment]
> But how can we respond to AppLifeCycle events in desktop?

Currently you cannot, thus this issue. If you need a short-term workaround you can wire up the behaviors you need via platform channels in your own application.

> Will this be available soon

There is no specific timeline for it. Anyone interested in accelerating the process is welcome to submit PRs.

> or its not implemented for any specific reason?

It is not implemented because the Flutter team has finite engineering resources.

**Comment by csells** [comment]
cc @cbracken this seems like table stakes for a desktop stable release. thoughts?

**Comment by ltOgt** [comment]
This also prevents desktop apps to react to loss and gain of window focus.

See e.g. https://github.com/flutter/flutter/issues/103446 and https://github.com/flutter/flutter/issues/105230

**Comment by gspencergoog** [comment]
This has been completed. See [AppLifecycleListener](https://api.flutter.dev/flutter/widgets/AppLifecycleListener-class.html) and the related classes.
