### ISSUE TITLE
Snackbar should have unique text each time it comes up

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3073]
* Go to SnackBar section of gallery.
* Tap "Show a SnackBar"
* Wait for the snack bar to appear.
* Tap "Show a SnackBar" two more times, in rapid succession.

Expected:

* Snack Bar to animate down after normal time, and not reappear.

Actual:

* Snack Bar animates back up and down, the number of times you tapped the button.

**Comment by Hixie** [comment]
It's a different snackbar each time. We should probably make the text slightly different (e.g. "Snackbar #1", "Snackbar #2") to make that clearer.

Snackbars are supposed to queue up this way according to the material spec.

**Comment by sethladd** [comment]
Ah, yes, if we change the text in the snackbar, then it will make more sense. Thanks!
