### ISSUE TITLE
Eliminate use of __FlutterEngineFlushPendingTasksNow in GLFW shell

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#30730]
See #16912. Also, having to poll it makes the GLFW implementation take lots of CPU (which we could scale back with sleeps, but that's another hack).

**Comment by boyen747** [comment]
when can this issue be resolved?

**Comment by boyen747** [comment]
when can this issue be resolved? @stuartmorgan

**Comment by stuartmorgan** [comment]
The necessary embedding API is available now, so it could be resolved at any time. It's a question of someone spending the time to write a new event loop for the GLFW shell using that API.

Performance of the GLFW shell, which there are no plans to ship as a product, is not currently the highest-priority work for desktop. But I'm happy to review patches for this if someone wants to work on it in the near future.

**Comment by stuartmorgan** [comment]
Unassigning since this isn't something I'll be working on in the near term.

For anyone interested in working on this, a high level description of what needs to be done:
- Instead of just looping with `glfwPollEvents` [here](https://github.com/flutter/engine/blob/master/shell/platform/glfw/flutter_glfw.cc#L667), the GLFW shell needs a real message loop. This would look very similar to the engine-internal class
[MessageLoopImpl](https://github.com/flutter/engine/blob/master/fml/message_loop_impl.h), using a priority queue of delayed events; at each cycle, it would `glfwWaitEvents` with a timeout of the remaining time until the next delayed task.
- That would be wired up to the embedding API using the [`custom_task_runners` field](https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h#L627), using `glfwPostEmptyEvent` to wake up the main thread if necessary.

**Comment by chinmaygarde** [comment]
Came across this issue while tinkering with the Linux embedder and submitted a patch https://github.com/flutter/engine/pull/9089 that fixes this. Have a few questions that I need to clarify with Stuart but the basic implementation should be good.

**Comment by tmathews** [comment]
Using this diff I get this error. I haven't attempted to fix it, but thought I would report it anyways. Could be I applied the patch on the wrong branch.
```
$ flutter run --local-engine=host_debug_unopt
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                   
[ERROR:flutter/shell/platform/embedder/embedder.cc(50)] Returning error 'kInvalidArguments' (2) from Flutter Embedder API call to 'FlutterEngineRunTask'. Origin: ../../flutter/shell/platform/embedder/embedder.cc:1003
[FATAL:flutter/fml/message_loop.cc(22)] Check failed: loop != nullptr. MessageLoop::EnsureInitializedForCurrentThread was not called on this thread prior to message loop use.
Syncing files to device Linux...                                
Lost connection to device.
```

**Comment by DisDis** [comment]
This problem affects single board computers (RasPi3) very much. Since even a simple example of flutter_gallery is very slow, 1-2 fps (300ms-500ms per frame)

**Comment by thEpisode** [comment]
@stuartmorgan why is closed this issue? is still happening...

**Comment by stuartmorgan** [comment]
This issue is closed because `__FlutterEngineFlushPendingTasksNow` is no longer being called, and event processing is no longer a busy-wait.

If what you are referring to is that you still see high CPU usage, that's now #35995. The cause is no longer the specific issue that was tracked by this bug.

**Comment by Claus1** [comment]
The issue still exists on Linux. Flutter 1.10.1-pre.41 • channel master

**Comment by stuartmorgan** [comment]
Please see my previous comment. *This* issue does not exist.

If you have a scenario where a Flutter app running on Linux uses 100% of a core, please file a new bug with reproduction steps, and we can investigate what is causing that.

I'm going to lock this issue, since there seems to be confusion about the scope.
