### ISSUE TITLE
[firebase_ml_vision] Fix entityId for iOS 

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#30740]
Please fix a typo in ImageLabeler.m row 31:

@"**entityID**" : label.entityID,    =>   @"**entityId**" : label.entityID,

**Comment by escamoteur** [comment]
If the problems still isn't solved, please ask at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!
