### ISSUE TITLE
Tab underline length "pops" before animating over

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3074]
Please check out this video that shows the effect: https://dl.dropboxusercontent.com/u/316685/video2.mp4

Notice that, when I swipe over from RAISED to FLAT, the underline "pops" to its final length, before it animates over to FLAT.

The correct behavior seems to be that the underline should animate to its final length, as soon as the swipe begins. See the Google News app for an example.

**Comment by Hixie** [comment]
@HansMuller Did this get fixed by your recent work?

**Comment by HansMuller** [comment]
It's hard to know for sure, because the original video is gone. However I'm pretty sure the popping that this bug refers to has been gone for some time.
