### ISSUE TITLE
Scrolling performance in ScrollableMixedWidgetList is slow

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3075]
ScrollableMixedWidgetList probably does both a full rebuild and full layout every frame.

Test case here: https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/lib/main.dart

**Comment by abarth** [comment]
It looks like most of the time is spent rebuilding the visible child of the mixed viewport.  We'll need to switch mixed viewport to cache the widget when scrolling, similar to how VirtualViewport works.

**Comment by abarth** [comment]
I'm prototyping a new algorithm for doing variable height infinite lists that should hopefully be much faster.
