### ISSUE TITLE
Issue from website page 升级 Flutter

### ISSUE THREAD

**Issue by hangiangai** [flutter/flutter#30756]
From URL: https://www.flutterchina.club/upgrading.md

**Comment by cloudwebrtc** [comment]
@hangiangai https://www.flutterchina.club/ 看起来是一个爱好者翻译的网站，不像是flutter官方网站，你需要联系网站作者。

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
