### ISSUE TITLE
flutter_tools potential exceptions

### ISSUE THREAD

**Issue by 2dxgujun** [flutter/flutter#30762]
I was doing my secondary development on flutter_tools.

I found this function will throw exception when you invoke multiple times.

> Bad state: Stream has already been listened to.

Seens `stdin` can not been subscribe more than once, and I found `stdin.asBroadcastStream()` which may be the solution.

```dart
Future<int> runInteractively(List<String> command, {
  String workingDirectory,
  bool allowReentrantFlutter = false,
  Map<String, String> environment
}) async {
  final Process process = await runCommand(
    command,
    workingDirectory: workingDirectory,
    allowReentrantFlutter: allowReentrantFlutter,
    environment: environment,
  );
  // The real stdin will never finish streaming. Pipe until the child process
  // finishes.
  unawaited(process.stdin.addStream(stdin));
  // Wait for stdout and stderr to be fully processed, because process.exitCode
  // may complete first.
  await Future.wait<dynamic>(<Future<dynamic>>[
    stdout.addStream(process.stdout),
    stderr.addStream(process.stderr),
  ]);
  return await process.exitCode;
}
```

**Comment by jonahwilliams** [comment]
In general, it might not be safe to switch out a regular Stream to a broadcast Stream - since the former will buffer events while unsubscribed and the latter won't.  I'm not sure sure how that works with stdin though, it would be worth investigating.

**Comment by jonahwilliams** [comment]
I don't think there is anything actionable here for us. Closing for now
