### ISSUE TITLE
Support custom shaders

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#30763]
From internal discussion, a user would like to apply a custom GL vertex or fragment shader program.  This seems like it should be doable - although one thing I'm not sure about is what happens if you're running on a Vulkan or Metal backend.

/cc @liyuqian @chinmaygarde 

/cc @clocksmith

**Comment by liyuqian** [comment]
Is it more or less similar to `PlatformView`? For example, create a gl surface so the custom GL shaders will render into that surface, and Flutter will then composite normal Flutter canvas(es) with that gl surface.

**Comment by dnfield** [comment]
I don't know if this is possible, but my thought was that you'd somehow be able to apply the shader as the shader on a `Paint` object.  Maybe it doesn't work like that though.

Basically, you'd like to apply an arbitrary vertex or fragment shader to a widget.

**Comment by liyuqian** [comment]
I'm not sure if Skia supports putting arbitrary GL shaders into somewhere. I guess not so it won't break its Vulkan backend. It seems that you can only create an `SkShader` to put into a `SkPaint` object (which is basically what `Paint` is).

**Comment by dnfield** [comment]
Ahh I see.  I guess in that case it would just make sense to have a `PlatformView`.

**Comment by cbenhagen** [comment]
@dnfield can you maybe push me into the right direction on how I would use a `PlatformView` to apply a fragment shader to a widget?

This could be a solution for https://github.com/flutter/flutter/issues/55738.

**Comment by dnfield** [comment]
You cannot use a platform view to apply a custom shader to a widget. Your platform view would have to apply it's custom shader to whatever it knew how to draw.

**Comment by cbenhagen** [comment]
@dnfield can we reopen this issue then? Being able to apply shaders would indeed be useful for many applications. Having to apply them on the platform side of the video_player plugin for example would mean that one has to fork and maintain the player and implement the shader for every single platform.

Maybe you might want to chime in on this Skia issue I opened https://crbug.com/skia/10274.

**Comment by cbenhagen** [comment]
@liyuqian It looks like things have changed since this issue was closed. In Skia milestone 81 `SkRuntimeEffect` and friends have been added which would allow custom SkSl shaders and color filters.

**Comment by liyuqian** [comment]
Yes, we've discussed with the Skia team about the new Skia APIs allowing custom SkSL shaders several months ago. At that time, it seems to be still in the experimental phase and not ready for exposing them through Flutter's public APIs. 

@bsalomon : I wonder how it is now from Skia's perspective?
@chinmaygarde: I saw that you raised the SkSL custom shader in go/flutter-skia-sync on April 20th. I wonder if you have more updates on that?

**Comment by roman-petrov** [comment]
I found that some work is done on custom shaders by Flutter Team on https://github.com/chriscraws/ssir repository based on [Flutter shaders design document](https://docs.google.com/document/d/1z9K5LernwQ0LVAzfbAMW6ITx63QRdRsoax1NLYEfm4Y/edit). Are there any future plans to move this work forward or it will be freezed / just dropped?..

**Comment by roman-petrov** [comment]
Thank you, this is fantastic news! Flutter is one step closer to become most attractive and powerful UI development framework!
