### ISSUE TITLE
Flutter run crashes on missing gradlew

### ISSUE THREAD

**Issue by vineethmohanvvdn** [flutter/flutter#30766]
When i am trying to run flutter project in linux os (ubuntu 16.04) which is previously working in windows laptop iam getting an error that
Oops; flutter has exited unexpectedly.                                                                                                                                      

## Steps to Reproduce
This error is getting when i am trying to run command flutter run.
Attaching log file with this issue.
when i am running flutter doctor -v am getting 
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_IN)
    • Flutter version 1.0.0 at /home/vkchlt0099/Development/flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/vkchlt0099/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/vkchlt0099/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/vkchlt0099/Development/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Le X509 • Z9USOFZ5QGOV8LLV • android-arm64 • Android 6.0 (API 23)

• No issues found!

[flutter_01.log](https://github.com/flutter/flutter/files/3057297/flutter_01.log)

**Comment by TahaTesser** [comment]
Hi @vineethmohanvvdn 
This looks like a tool crash issue, `flutter run` doesn't crash anymore when `gradlew` is missing 
Closing, as fixed. If you disagree, please write in the comments and I will reopen it.
Thank you
