### ISSUE TITLE
real device get blacklisted after showing admob banner ad using package firebase_admob

### ISSUE THREAD

**Issue by lhcdims** [flutter/flutter#30773]
There are 2 rules of using admob:

1. 'Any method that artificially generates clicks or impressions on your Google ads is strictly prohibited', which is stated here: 
https://support.google.com/admob/answer/48182

2. 'Ads should not be placed on screens that don’t offer any content', which is stated here:
https://support.google.com/admob/answer/2936217

Now, suppose my app have 4 screens, say, screen A and B have contents, screen C and D do                                                                                                           not have contents(e.g. Login screen, Setting screen), and user navigate between screens by using a BottomNavigationBar.

In order to comply with rule no. 2, I want to show banner ad in screen A and B only.  When user navigate from screen A to screen C (from 'screen with banner ad' to 'screen not allowed to have banner ad'), I called bannerAd.dispose() in screen A before leaving screen A, then when user navigate from screen C to screen B, I re-create the banner ad in screen B.

After the user navigates too much between 'screen with banner ad' and 'screen without banner ad', the user's real device is BANNED(BlackListed) to show any banner ad(successful rate of showing banner ad drops to 0%), I believe that the AI of admob may think that rule no. 1 is violated. (since doing .dispose and re-create banner ad can change the 'content' of the ad, i.e. 'artificially generate impressions')

I wrote a comment in another issue that record the complete incident of how the device got blacklisted:
https://github.com/flutter/flutter/issues/28733#issuecomment-480994999

I think there is a dilemma between rule no. 1 and rule no. 2, is it possible that the flutter package firebase_admob provides a simple '.hide()' method for the bannerAd so that we can hide the banner in screens that banner ads are not allowed?  Or is there any work around to comply with the 2 rules at the same time?

My second question is, how can the real device stated above get removed from the blacklist?

thank you.

**Comment by tomalabaster** [comment]
Did you add your device identifier to the list of test devices?

**Comment by lhcdims** [comment]
> Did you add your device identifier to the list of test devices?

I did, and everything works fine using test devices, until it goes to production test using real app id and ad unit id.  As stated in the comment of another issue, I DID NOT click any ad in production test, which is STRICTLY PROHIBITED.

It seems that the plugin behaves differently with test id and real id, which makes the tests meaningless.

**Comment by WChoy** [comment]
Double check your AdMob "Frequency capping (Limits the number of times ads are shown to the same person per minute, per hour, or per day.)" on https://apps.admob.com

**Comment by 1AlexFix1** [comment]
Any news?

**Comment by d-apps** [comment]
A .hide() method could be a very good idea, or at least a workaround to hide the ad from the view. 

Maybe disposing and re creating the banner is allowed, actually I already saw a lot of apps in Flutter and native with every screen re creating the banner, and they were ok, I think.

**Comment by mulderpf** [comment]
How do you know that these devices were banned?  My app implements this and I turn the ads on and off as the user navigates through the app.  My app has been live since December 2018 like this and I haven't noticed any specific issues.  I just checked and rechecked and rechecked show rates and match rates from the time my app was Android to Flutter and I there is no difference (except for one small issue just after the Flutter launch when I didn't realise iOS has to have it's own ad id which caused a small drop).

**Comment by escamoteur** [comment]
If the problems still isn't solved, please ask at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!
