### ISSUE TITLE
App should make phone calls from app interface not from phone dialer

### ISSUE THREAD

**Issue by Nethram** [flutter/flutter#30778]
I am new to flutter development. 
I would like to create a flutter app which should make phone call  from it's interface with out going to phone default dialer. It should use default phone call method but should stay in app's interface for every call events. Is there any hope for me to do this?
Any help will be appreciated. Thanks.

**Comment by vagrantrobbie** [comment]
this question is probably more appropriate for StackOverflow

**Comment by Nethram** [comment]
Thanks @vagrantrobbie . I did ask about this in stackOverflow also

**Comment by mecidr** [comment]
Can you provide a link to the same question you asked on StackOverflow?

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow, we are not able to give individual development support.
