### ISSUE TITLE
TextField default cursor too short and look abnormal cursor in Thai

### ISSUE THREAD

**Issue by pcbimon** [flutter/flutter#30771]
When typing Thai language , Cursor located above  than character. (Sorry for bad English)
![thai](https://user-images.githubusercontent.com/8252967/55778309-c6675600-5acc-11e9-8882-780153a29a52.PNG)

[√] Flutter (Channel master, v1.4.13-pre.5, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 1.4.13-pre.5 at D:\work\Flutter-SDK
    • Framework revision ed49122aa3 (3 hours ago), 2019-04-08 20:22:34 -0700
    • Engine revision ff1bcdc009
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\work\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\work\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.33.0)
    • VS Code at C:\Users\IT228\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by HansMuller** [comment]
CC @GaryQian @justinmc

**Comment by justinmc** [comment]
Duplicate issues:
https://github.com/flutter/flutter/issues/24182
https://github.com/flutter/flutter/issues/23934

I think this is the first time it has been pointed out explicitly for Thai, though.  I have this on my radar.

**Comment by GaryQian** [comment]
I believe this bug affects all ideographic scripts. Alpha-numeric works fine.

**Comment by pcbimon** [comment]
> Duplicate issues:
> #24182
> #23934
> 
> I think this is the first time it has been pointed out explicitly for Thai, though. I have this on my radar.

Thanks It' work
