### ISSUE TITLE
Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: Cannot find executable for F:\ndkas\platform-tools\adb.

### ISSUE THREAD

**Issue by TimAimee** [flutter/flutter#30772]
## Steps to Reproduce

sdk had add to  enviorment path.

ANDROID_HOME  F:\\ndkas
Path    %ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools;

## Logs

E:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.2.1 at E:\flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\ndkas
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:/ndkas
    X Android SDK file not found: F:\ndkas\platform-tools\adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[!] Android Studio
    • Android Studio at E:\AndroidStudio_2019190409
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = E:\AndroidStudio_2019190409
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: Cannot find executable for F:\ndkas\platform-tools\adb.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:547:5)
#2      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:55:53)
<asynchronous suspension>
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:171:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:99:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:694:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

Process finished with exit code 1

**Comment by TimAimee** [comment]
i have fix it.
download the news platfomr-tools and replace the file.

**Comment by AsombaChinonso** [comment]
but how do you download a new platform-tools and replace file, can you please explain your procedure, i would be glad

**Comment by AsombaChinonso** [comment]
am having the same bug each time i hit flutter doctor

**Comment by diannurdiana86** [comment]
https://developer.android.com/studio/releases/platform-tools

**Comment by patelkrunal78** [comment]
https://icetutor.com/question/flutter-does-not-find-android-sdk-2

**Comment by krrishkhedia** [comment]
Please update your windows and try again. It worked for me.

**Comment by AsombaChinonso** [comment]
I am just seeing this now.

Thanks for taking out the time, problem solved already
