### ISSUE TITLE
Firebase error

### ISSUE THREAD

**Issue by zuzutahan** [flutter/flutter#30779]
Zuhairs-MacBook-Pro:open311_s zuhairhallak$ flutter run
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team
in Xcode project: M6E2BGCTT7
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                          11.7s
 └─Compiling, linking and signing...                         9.6s
Xcode build done.                                           26.8s
5.19.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50800000 started 
5.19.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Installing and launching...                                        16.4s
Error connecting to the service protocol: HttpException: , uri =
http://127.0.0.1:1037/ws

I added camera functionality and this is what I started getting.

**Comment by escamoteur** [comment]
If the problems still isn't solved, please ask at the new  home for Firestore at https://github.com/FirebaseExtended/flutterfire and link this issue to it. Thanks!
