### ISSUE TITLE
DataTable - make scrollable, set background colour and fix/freeze header row and first column

### ISSUE THREAD

**Issue by lukaszbojarski** [flutter/flutter#30770]
I've started developing in Flutter with webview, charts, tables, but I met some problems with tables.

1. I use **DataTable** to represent data in a table.
There is a first problem. By default, it isn't scrollable if data is out of a screen. So I embedded in some Widgets (i.e. SingleChildScrollView, ListView), but it was scrollable only in one direction (vertical or horizontal). I searched something about it and I found a plugin for both directions (*bidirectional_scroll_view 0.0.6*). After compilation I received an error

> Because app depends on bidirectional_scroll_view >=0.0.2 which
> requires SDK version <2.1.0, version solving failed.

I'm using Dart SDK version: >=2.1.0 <3.0.0 in configuration.

Next, I found **PaginatedDataTable** which allows scrollable in both directions, but it is paginated table.
So anybody know is it possible to somehow scroll **DataTable** in both directions (vertical and horizontal)?

2. The second question (more important): is it possible to set background colour in header (first) row and first column in a table? Or even in any cell in a table?

For **DataColumn**/**DataCell** I tried embed Text in Container and then set Container colour, but the background colour was only set for text, the rest of a cell was with default colour.

i.e.

    DataColumn(label: Container(child: Text('2011'), color: Colors.grey,)),
<img width="508" alt="Screen Shot 2019-04-04 at 13 57 38" src="https://user-images.githubusercontent.com/2955370/55777645-d5d0aa00-5aa0-11e9-9800-24a3c1eea60c.png">

3. And is it possible to fixed/freeze header (first) row and first column. I mean the table is scrolled and first row/column is always visible on a screen. I couldn't find any solution ..

**Comment by Richard-Choooou** [comment]
Can not agree anymore, the third problem is most important for me. 
you can use Table, TableRow, TableCell widget custom you table for the third problem, but their widgets look like can not define events.

**Comment by harishshet222** [comment]
is there any one who found solution for the 3rd problem, even I am facing the same. I want to freeze the first row and first column of row, so once scroll down those should be visible. 
![image](https://user-images.githubusercontent.com/32177151/65326642-940b6a00-dbcf-11e9-8756-11fc44b6d3f6.png) , or any other way to do so,


here what I am doing is,
 Widget getTable(BuildContext context, var data) {
    Widget _widget;
    _widget = SingleChildScrollView(
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: DataTable(
          rows: createDataRows(context, data),
          columns: createDataColumns(context, data),
        ),
      ),
    );
    return _widget;
  }

  List<DataRow> createDataRows(BuildContext context, var jsonData) {
    List<DataRow> _dataRows = [];
    List<DataCell> _cells = [];
    String _dataCellTitle;

    Map<String, Object> headers = jsonData['headers'];
    Map<int, String> headerMapping;
    headerMapping = headers.keys
        .toList()
        .asMap()
        .map((index, value) => MapEntry(index + 1, value));

    if (jsonData["data"] == null) {
      _dataRows = [];
    } else {
      for (var j = 0; j < jsonData["data"].length; j++) {
        _cells.add(DataCell(Text('${j + 1}')));
        for (int i = 1; i <= headerMapping.length; i++) {
          _dataCellTitle = "${jsonData["data"][j][headerMapping[i]]}" ?? '-';
          _cells.add(DataCell(Text('$_dataCellTitle')));
        }
        _dataRows.add(DataRow(cells: _cells));
        _cells = [];
      }
    }
    return _dataRows;
  }

  List<DataColumn> createDataColumns(BuildContext context, var jsonData) {
    String columnTitle;
    List<DataColumn> _dataColumns = [];
    Map<String, Object> headers = jsonData['headers'];
    Map<int, String> headerMapping;
    headerMapping = headers.keys
        .toList()
        .asMap()
        .map((index, value) => MapEntry(index + 1, value));
    _dataColumns.add(DataColumn(label: Text('S. No.')));
    for (int i = 1; i <= headerMapping.length; i++) {
      columnTitle = headers[headerMapping[i]];
      _dataColumns.add(
        DataColumn(label: Text('$columnTitle')),
      );
    }
    return _dataColumns;
  }

**Comment by didavid61202** [comment]
same here, the third problem is most important for me too.
really hope someone know if there's any way to implement it.

**Comment by Goostavo** [comment]
There is an specific thread only about the third item (fix/freeze columns). https://github.com/flutter/flutter/issues/21165

Also. We are currently making an workaround on stackOverflow: [StackOverflow Issue on fixing header/row](https://stackoverflow.com/questions/58398787/fixed-column-and-row-header-for-datatable-on-flutter-dart/58467209?noredirect=1#comment103314236_58467209)

**Comment by nikesh03** [comment]
> Can not agree anymore, the third problem is most important for me.
> you can use Table, TableRow, TableCell widget custom you table for the third problem, but their widgets look like can not define events.

this might help https://pub.dev/packages/table_sticky_headers

**Comment by pulstar** [comment]
You can try something like this:

```
ListView(
        shrinkWrap: true,
        children: <Widget>[
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: DataTable(
              columns: widget.columns,
              rows: widget.rows,
              columnSpacing: widget.columnSpacing,
              horizontalMargin: widget.horizontalMargin,
              headingRowHeight: 50.0,
              dataRowHeight: 40.0,
            ),
          ),
        ],
      )
```

**Comment by Viacheslav-Romanov** [comment]
Good points!

**Comment by normidar** [comment]
This problem has been bothering me for a long time, why is it still unsolved after so long?

**Comment by nikesh03** [comment]
Use this for fixed header and first column

https://github.com/AlexBacich/sticky-headers-table

**Comment by Bonsai11** [comment]
I have the feeling the whole DataTable widget needs some work done. The column names should be fixed. Also you should be able to set a header color.

**Comment by normidar** [comment]
> 我觉得整个DataTable小部件需要完成一些工作。列名应固定。另外，您应该能够设置标题颜色。

you are right

**Comment by normidar** [comment]
> I have the feeling the whole DataTable widget needs some work done. The column names should be fixed. Also, you should be able to set a header color.

you are right.

**Comment by Goostavo** [comment]
The main problem is that we cannot have access to internal column width attribute.

The fixed column solution is making a new table with a single title row, and forcing it to overlap the full table behind. To be able to do so, all the columns must have exactly the same width, otherwise header and table will have different column sizes.

To implement a nice solution with dynamic column size we would need to create the table. Get the automatic generated column width array, and create the fixed header using this array as the sizes for titles.

**Comment by pulstar** [comment]
I am using DataTable like a growable scroll list, but as the table grows, it becomes more and more slower.

**Comment by SexyBeast007** [comment]
DataTable needs simple functionality for sticky headers and/or column. This is a necessary basic function of any table or spreadsheet ESPECIALLY when using on small screens such as phones. Try using google sheets on your phone for a big spreadsheet, you will get lost easily without sticky headers or columns. +1 for added functionality, I speak for many!

**Comment by lukepighetti** [comment]
DataTable absolutely needs a rework. Cached declarative sort with typed columns. Scrollable lazy body. More styling options.

**Comment by dipak1267** [comment]
please anyone can gave proper solution for problem 3

**Comment by Bonsai11** [comment]
@dipak1267 I don't think there is a solution yet besides using third party packages, which is often a bad idea. I don't understand why people who have the skills to create their own custom DataTable widgets that have these features don't instead improve the native DataTable widget.

**Comment by baros-code** [comment]
Sticky header is one of the most fundamental feature of  a data table, if the current DataTable implementation doesn't allow to add this feature, a rework should be considered. Still no improvement after 1 year?

**Comment by joo** [comment]
Next 10 years!!!
