### ISSUE TITLE
_TabSwitchingViewState not actually caching tab builds

### ISSUE THREAD

**Issue by kerberjg** [flutter/flutter#30790]
Switching tabs in a CupertinoTabScaffold causes ALL of the tabs to be rebuilt, as the `tabBuilder` function is being called by the `_TabSwitchingViewState` at every tab index change.

## Steps to Reproduce

1. Have an app using a CupertinoTabScaffold inside a CupertinoApp
2. Switch between any tab available
3. All tabs (that have been already opened at least once) will be rebuilt

## Solution proposal

What happens, is the condition for rebuilding a tab, will almost always be true (tab_scaffold.dart@338):

```
if (active || tabs[index] != null) {
     tabs[index] = widget.tabBuilder(context, index);
}
```

This can be easily solved by making sure the tab is only rebuilt `if active, and not already cached`

```
if (active && tabs[index] == null) {
     tabs[index] = widget.tabBuilder(context, index);
}
```

Using Flutter v1.3.8

**Comment by matthew-carroll** [comment]
@kerberjg this was intentional originally.  Can you describe why rebuilding the tab widgets is an issue in your case? In general, we never cache widgets in Flutter because widgets represent a moment in time, rather than mutations over time.

**Comment by kerberjg** [comment]
According to the documentation found [here](https://docs.flutter.io/flutter/cupertino/CupertinoTabScaffold/tabBuilder.html), the behavior of the `tabBuilder` should be as follows:

> When the tab becomes inactive, its content is still cached in the widget tree Offstage

...and we can see that this is more or less what happens in [`_TabSwitchingViewState`'s build()](https://github.com/flutter/flutter/blob/514aba6e36d4c9429d307e643dde3398802ca56a/packages/flutter/lib/src/cupertino/tab_scaffold.dart#L330)... except that the code responsible for building the tabs, is literally defined as: "if we have built this widget, let's rebuild it", as indicated in the code in the first post, which can be found [here](https://github.com/flutter/flutter/blob/514aba6e36d4c9429d307e643dde3398802ca56a/packages/flutter/lib/src/cupertino/tab_scaffold.dart#L336).

What's more, every time a tab is switched, [ALL the tabs are being rebuilt](https://github.com/flutter/flutter/blob/514aba6e36d4c9429d307e643dde3398802ca56a/packages/flutter/lib/src/cupertino/tab_scaffold.dart#L333), including the hidden ones.

This brings 2 potential issues:

- Is it really necessary to rebuild N tab widget trees, when we need to display only *one*?
- What is the purpose of caching tab widgets in Offstage, if we're going to rebuild them anyway?

...also...

- If the aforementioned behavior is indeed correct, the documentation might be considered misleading
- Why would I want to rebuild something I don't see when its state is being intact?
- Does this mean that specifying the tab content either as Stateful or Stateless is meaningless, because it's going be rebuilt regardless of an actual necessity to do so?

**Comment by kerberjg** [comment]
Potential proposed solutions: either...

- Make it explicit in the documentation that all of the tabs *will* and *should* be rebuilt at every tab switch, if that's the case
- Have only the necessary tab widget being built, instead of all of them
- Build only the tabs that haven't been cached already

**Comment by matthew-carroll** [comment]
So, the documentation line you mentioned is accurate:

> When the tab becomes inactive, its content is still cached in the widget tree Offstage

When you're viewing tab content A, and then you switch to tab content B, tab content A remains offstage even though it's not visible. However, by placing the tab in an `Offstage` widget and putting it in a `TickerMode` widget, that widget does not paint itself, nor does it receive ticker updates for animations. This is the caching that the documentation refers to.

You mentioned

> ALL the tabs are being rebuilt

But the line that you linked to shows that only the active tab, and the previously viewed tabs are being rebuilt. Any tab that has not yet been built is represented as an empty `Container()` offstage, which is equivalent to nothing at all.

You asked

> What is the purpose of caching tab widgets in Offstage, if we're going to rebuild them anyway?

I'll look into this more. This may be a legitimate thing to change. It is unclear why the `tabBuilder` needs to be rerun for offstage widgets.

I'll file another ticket to look into the API. We may opt for an approach that places caching in the hands of the developer instead of automatically forcing caching behavior internally.

But I'm still interested to know, is this behavior creating a performance bottleneck for you?  Or is it interfering with some expected UI behavior? Are there any adverse effects for your app as a result of this?

**Comment by matthew-carroll** [comment]
Filed #30822 to investigate a possible new API for caching tab content.

**Comment by kerberjg** [comment]
> But the line that you linked to shows that only the active tab, and the previously viewed tabs are being rebuilt

This is correct, my bad. After further testing, I was able to confirm that it indeed applies only to tabs that have been opened at least once.

**Comment by TahaTesser** [comment]
Issue exist on 
```
[✓] Flutter (Channel dev, v1.16.2, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.2 at /Users/taha/Code/flutter_dev
    • Framework revision 58cad787d8 (4 days ago), 2020-03-23 08:33:41 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E266
    • Chrome        • chrome                    • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server    • web-server                • web-javascript • Flutter Tools

• No issues found!
```

**Comment by xster** [comment]
I'm merging this into https://github.com/flutter/flutter/issues/30822 since it has more up to date discussions with context.
