### ISSUE TITLE
Reciever FCM notification click event.

### ISSUE THREAD

**Issue by MuhammedAlmaz** [flutter/flutter#30806]
How can i receiver the notification click event on flutter ? 

I write this code on main.dart but the onMessage handling events doesn't work.
**main.dart**

`import 'package:flutter/material.dart';
import './ekranlar/kayit_ol/kayit_ol.dart';
import './ekranlar/splash_ekrani/splash_ekrani.dart';
import './ekranlar/sanal_pul_hareketleri/sanal_pul_hareketleri.dart';
import 'dart:io';
import 'package:firebase_messaging/firebase_messaging.dart';

import 'package:flutter_localizations/flutter_localizations.dart';
//Tasarımlar için önemli
import 'package:flutter/rendering.dart';

FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
void iOS_Permission() {
  _firebaseMessaging.requestNotificationPermissions(
      IosNotificationSettings(sound: true, badge: true, alert: true)
  );
  _firebaseMessaging.onIosSettingsRegistered
      .listen((IosNotificationSettings settings)
  {
    print("Settings registered: $settings");
  });
}
void firebaseCloudMessaging_Listeners(BuildContext context) {
  if (Platform.isIOS) iOS_Permission();

  _firebaseMessaging.getToken().then((token){
    print("Token : ${token}");
  });

  _firebaseMessaging.configure(
    onMessage: (Map<String, dynamic> message) async {
      print('on message $message');
    },
    onResume: (Map<String, dynamic> message) async {
      print('on resume $message');
    },
    onLaunch: (Map<String, dynamic> message) async {
      Navigator.pushNamed(context, "/");
      print('on launch $message');
    },
  );
}
void main() {
  print("uygulama Acildi");
  debugPaintSizeEnabled = false;
  runApp(MaterialApp(
    localizationsDelegates: [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ],supportedLocales: [
    const Locale('tr', 'TR'),
  ],
    theme: ThemeData(fontFamily: 'Oswald'),
    initialRoute: '/',
    routes: <String, WidgetBuilder>{
     // '/': (context) => SanalPulHareketleri(),
      '/': (context) => SplashEkrani(),
      '/kayit_ol': (context) => KayitOl(),
    },
  ));
}`

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow, we are not able to give individual development support.
