### ISSUE TITLE
Rendering broken

### ISSUE THREAD

**Issue by xster** [flutter/flutter#30801]
Not sure how to better describe it, but rendering is off. 

This one is just a column with Icon and Text
![flutter_07](https://user-images.githubusercontent.com/156888/55825370-b5ade480-5aba-11e9-8922-5da22577312f.png)

The transforms here are all off
![flutter_08](https://user-images.githubusercontent.com/156888/55825371-b5ade480-5aba-11e9-88a0-a48cb9c9f860.png)

![flutter_09](https://user-images.githubusercontent.com/156888/55825372-b5ade480-5aba-11e9-916d-c2a6065441f9.png)

**Comment by LongCatIsLooong** [comment]
[e5722f32e4db5c3fcce31c47623e82566e74b74c] Roll engine ff1bcdc00941..8a465596533d (21 commits) (#30768) seems to be causing this

**Comment by jason-simmons** [comment]
Traced this to https://github.com/google/skia/commit/7a2ff3c9a86ab4dbd2814134648e19bc5fcce5f5

**Comment by sbaranov** [comment]
Skia change has been reverted in https://github.com/flutter/flutter/commit/514aba6e36d4c9429d307e643dde3398802ca56a

**Comment by xster** [comment]
Fixed on head. Thanks all!
