### ISSUE TITLE
FlutterEventTracer is leaked per shell run.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#30808]
In |InitSkiaEventTracer|.

**Comment by pedromassangocode** [comment]
Can you please provide more information about this issue?
I'm not able to verify if this is still valid or not. Thanks

**Comment by chinmaygarde** [comment]
Yes, the handle given to the `_flutter.enableSkiaTracing` callback [is a small leak](https://github.com/flutter/engine/blob/d85cb10707a29dae9a437a1cf6bfa2e28860d3f7/shell/common/skia_event_tracer_impl.cc#L254) and must be cleaned up when the shell instance is torn down.

**Comment by jason-simmons** [comment]
This callback was removed in https://github.com/flutter/engine/commit/0fc1beac6a727455133384b9873becf55bc0a99f
