### ISSUE TITLE
Using Flutter as a module and Android flavors

### ISSUE THREAD

**Issue by felipethalmic** [flutter/flutter#30816]
I'm integrating Flutter to my existing project and we have flavor on it.
i.e. internal and production

So after making the integration following the Flutter documentation:
[Add-Flutter-to-existing-apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps).
The app crashes when I call
`Flutter.createView(this, lifecycle, "route1")`

but if I change the build.gradle on Flutter ('.android/Flutter/build.gradle')
The app starts to work.
But as far as I know, I shouldn't change this file.

So my question is how can I use flavors on Android with Flutter.

I have uploaded a sample project that reflexes exactly the scenarios.

https://github.com/felipethalmic/flutterIntegration

 
## Steps to Reproduce

1. Just run the project

## Logs

```
2019-04-09 16:57:36.284 4463-4463/com.example.myapplication.internal E/flutter: [ERROR:flutter/runtime/dart_vm.cc(265)] VM snapshot must be valid.
2019-04-09 16:57:36.285 4463-4463/com.example.myapplication.internal A/flutter: [FATAL:flutter/shell/common/shell.cc(208)] Check failed: vm. Must be able to initialize the VM.
2019-04-09 16:57:36.285 4463-4463/com.example.myapplication.internal A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4463 (cation.internal), pid 4463 (cation.internal)
```

```
```

**Comment by chucvv** [comment]
@felipethalmic 
I had same issue and this worked for me in debug mode
 https://github.com/flutter/flutter/issues/24679#issuecomment-444480217

but in release mode, it isn't working.

**Comment by blasten** [comment]
We introduced a new android embedding: https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen. Please let us know if this is still an issue.

**Comment by blasten** [comment]
We introduced a new android embedding and now support flavors if you build an AAR (`flutter build aar`): https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar. Please let us know if this is still an issue.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
