### ISSUE TITLE
Building the engine: Add note about gclient requiring python2

### ISSUE THREAD

**Issue by dcov** [flutter/flutter#30812]
In order to set up the engine environment the `gclient` tool is required,
which itself requires `python2`. There should be a note about this in the ['Setting up the Engine development environment'](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment) guide for people that have environments where the `python` command points to `python3`, instead of `python2`.

**Comment by escamoteur** [comment]
@Hixie is this still the case that we need Python2

**Comment by jonahwilliams** [comment]
I don't know if this is still the case but the issue is so old its unlikely to be true any longer...I hope
