### ISSUE TITLE
Slow, hitchy transition between main screen and Weather

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3082]
Please see this video: https://dl.dropboxusercontent.com/u/316685/video4.mp4

Notice how the transition between the main screen of the Gallery and the Weather demo hitches, as the user goes into and then out of the Weather demo.

```
~/Code/flutter/examples/material_gallery[master*] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision daa0d2d (14 hours ago); engine revision 13f6734
```

Slow mode is off (at least, I don't see the banner and I used `flutter run --no-checked`)

This is on a Nexus 6P.

FWIW the app does seem to warm up eventually on my Nexus 9. After a few hitchy transitions, I can now get in and out of the Weather demo fairly smoothly on the 9.

**Comment by sethladd** [comment]
cc @vlidholt

**Comment by sethladd** [comment]
This seems to be specific to my Nexus 6P. Testing on One+1 and on a Nexus 9, the transition is much faster. Will continue to test. This seems to highlight the issue of device variance.

**Comment by sethladd** [comment]
Here's a capture of the Trace:

![screen shot 2016-04-13 at 11 26 26 am](https://cloud.githubusercontent.com/assets/5479/14504699/b7bc5740-016a-11e6-979e-e27bc9a11ec7.png)

Looks like we're overloading the GPU.

Here's the trace JSON file: https://dl.dropboxusercontent.com/u/316685/for-github-issues/dart-timeline-2016-3-13.json

**Comment by sethladd** [comment]
Here's a capture of the Trace on my Nexus 5:

![screen shot 2016-04-13 at 1 33 14 pm](https://cloud.githubusercontent.com/assets/5479/14508445/51f7e2a0-017c-11e6-8cb0-99d34b7e1587.png)

Here's the trace JSON file: https://dl.dropboxusercontent.com/u/316685/for-github-issues/dart-timeline-2016-3-13%20%281%29.json

**Comment by sethladd** [comment]
@Hixie I just had my mind blown by @johnmccutchan as he showed me how to view the CPU profiler from within the tracing viewer. Happy to show you how it works. We might be able to learn what the Paint call is doing.

**Comment by sethladd** [comment]
Updated traces:

* [cold start into weathers](https://dl.dropboxusercontent.com/u/316685/for-github-issues/timelines/cold_start_into_weathers.json)
* [warm start into weathers](https://dl.dropboxusercontent.com/u/316685/for-github-issues/timelines/warm_start_into_weathers.json)
* [steady state of weathers](https://dl.dropboxusercontent.com/u/316685/for-github-issues/timelines/steady_state_weathers.json)

**Comment by Hixie** [comment]
I don't see the spike on the profile. The performance on the cold profile isn't great, it's probably 30Hz, but it's reasonably steady. There's no 100ms frame. The most I can find is about 20ms (rounding up). I may be misreading the profile?

The profile does include data from Dart (though, it seems that that data isn't truncated to the time you were recording the profile?); from that data pretty much the only thing that the app is doing is running flutter_sprites code, mostly walking the node tree. Looks like drawImageRect in particular might be expensive; I also see "allocating rect" as something that comes up a bunch.

The profile still has lots of GetField calls. Maybe they're from the atlas calls, which I believe @abarth hasn't yet cleaned the GetField calls from?

**Comment by sethladd** [comment]
OK, here's a trace that seems to have everything (from the time of my tap on Weather, through the first "cold" load of the Weather demo)

https://dl.dropboxusercontent.com/u/316685/for-github-issues/first-load-of-weathers.json

**Comment by Hixie** [comment]
Now we're talking. That's got the data we need. Thanks!

**Comment by Hixie** [comment]
Looks like we're decoding the images on the main thread. @abarth

**Comment by Hixie** [comment]
Other issues visible in that trace:
- There's a 50ms GC
- We're uploading the image to the GPU synchronously.
- A bunch of GetFields making paint slow in flutter_sprites

**Comment by sethladd** [comment]
Woot! /me is learning. Love that tools and system has this data exposed.

Thanks for taking a look!

**Comment by eseidelGoogle** [comment]
Weather is no longer with us.
