### ISSUE TITLE
PageView not disposing page

### ISSUE THREAD

**Issue by altherat** [flutter/flutter#30821]
With a PageView with three or more pages, pages at certain indexes do not dispose when swiping off of them.

Here's a demo application:
```
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: PageView(
          children: <Widget>[
            Page1(),
            Page2(),
            Page3()
          ],
        )
      )
    );
  }
}

class Page1 extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => Page1State();

}

class Page1State extends State<Page1> {
  
  @override
  void initState() {
    super.initState();
    print("Page1 initState");
  }

  @override
  void dispose() {
    super.dispose();
    print("Page1 dispose");
  }

  @override
  Widget build(BuildContext context) => Container(color: Colors.red);

}

class Page2 extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => Page2State();

}

class Page2State extends State<Page2> {

  @override
  void initState() {
    super.initState();
    print("Page2 initState");
  }

  @override
  void dispose() {
    super.dispose();
    print("Page2 dispose");
  }

  @override
  Widget build(BuildContext context) => Container(color: Colors.green);

}

class Page3 extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => Page3State();

}

class Page3State extends State<Page3> {

  @override
  void initState() {
    super.initState();
    print("Page3 initState");
  }

  @override
  void dispose() {
    super.dispose();
    print("Page3 dispose");
  }

  @override
  Widget build(BuildContext context) => Container(color: Colors.blue);

}
```

In the above example, when swiping from Page1 to Page2, Page1's `dispose` is called but when swiping from Page2 to Page3, Page2's `dispose` is never called. Is this expected? I've tried adding a PageController to the PageView with `keepAlive: false` and also using `AutomaticKeepAliveClientMixin` on `Page2State` with `wantKeepAlive => false` but neither helps.

In my real app, I want my page to only do stuff when it's visible, so I thought I could rely on `initState` and `dispose` for this. Or is there a different way to accomplish this?

And here's the output from `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-CA)
    • Flutter version 1.2.1 at C:\Flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Matt\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio Canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    • All Android licenses accepted.

[√] VS Code (version 1.33.0)
    • VS Code at C:\Users\Matt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • ONEPLUS A6013 • 9e76e20e • android-arm64 • Android 9 (API 28)
```
\
\
**Edit**: I believe the offending code is this method:
https://github.com/flutter/flutter/blob/421f16a6b9176abb4ab3e9b9d1353300aa51712f/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L66-L69

It tries to resolve the page index based on the scroll position but it fails for some indexes I believe due to floating point precision loss. Resolving the page index is necessary for the `collectGarbage` method to dispose off-screen pages here:
https://github.com/flutter/flutter/blob/421f16a6b9176abb4ab3e9b9d1353300aa51712f/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L155-L167

**Comment by altherat** [comment]
I realized the issue is a lot less specific than I originally thought and updated the original post with a simpler explanation and example.

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by singlakaran** [comment]
@esarbanis @altherat i face same issue while using page view.

**Comment by altherat** [comment]
@singlakaran I believe this was fixed back in May by #30979. My example does not produce the issue anymore so if you're still having this problem it might be an issue with your code.

**Comment by singlakaran** [comment]
here is my  [code](https://stackoverflow.com/q/58670143)

please check @altherat

**Comment by escamoteur** [comment]
@singlakaran if you still have problems please open an new  issue with a detailed description

**Comment by singlakaran** [comment]
i already raised an issue [4402](https://github.com/flutter/flutter/issues/44042)  @escamoteur
