### ISSUE TITLE
Cant get support fragment manager in Flutter Plugin for Android

### ISSUE THREAD

**Issue by drkhannah** [flutter/flutter#30823]
Hello, im trying to create a Flutter plugin that uses an sdk that requires i getSupportFragmentManager() in android

However, im having trouble getting the v4 support fragment manager, i can get the normal fragment manager just fine, but I cant seem to get the support one

`override fun getSupportFragmentManager(): FragmentManager {
    return this.registrar!!.activity().getSupportFragmentManager()
  }`

I have tried many things, activit().fragmentManager() which doesn't return the v4 support fragment manager that I need

I've tried to call context().getSupportFragmentManager(), nothing

please help me get the v4 fragment manager

**Comment by drkhannah** [comment]
i also tried the solution here, https://stackoverflow.com/a/53863614/2411667

but it didn't work for me

**Comment by vishwajit76** [comment]
just extend your main activity to `FLutterFragmentActivity `
