### ISSUE TITLE
Xcode warning message on UIBackgroundMode

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#30839]
I'm getting this warning on the Xcode console.
```
2019-04-10 14:26:13.115576+0800 Runner[13781:2973077] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2019-04-10 14:26:13.115623+0800 Runner[13781:2973077] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
```

It even shows on newly generated Flutter project.

**Comment by piratejoe** [comment]
I'm getting the same warnings even on a fresh Flutter project. Issue started (I think) when I created a bundle id on developer.apple and enabled Push Notifications capability. I've since turned it off but the warning persists even in a new project with a generic bundle id.

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by Heki2017** [comment]
You have to check in the screen signing & capabilities the background mode and within that table the property background fetch

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by OKNoah** [comment]
> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so it's always better to open new issues and reference related issues.

Indeed, happens outside flutter too. (In RN)
