### ISSUE TITLE
library handler failed

### ISSUE THREAD

**Issue by garygogo** [flutter/flutter#30835]
I use "dart-ext:name" to load so ,  put the so in "libs/armeabi-v7a" and generate apk,
install apk and run , i get error "library handler failed"; 

how can i do like window.dart?
thanks

window.dart
void setIsolateDebugName(String name) native 'Window_setIsolateDebugName';

**Comment by liupan163** [comment]
i have same question

**Comment by robert-ancell** [comment]
I found the same problem. It seems that the Dart that comes with Flutter doesn't load extensions, but standard Dart does. Are they disabled for a reason?

**Comment by escamoteur** [comment]
What are you trying to do? Does the problem still persists with the latest Flutter version?

**Comment by robert-ancell** [comment]
I believe that Flutter intentionally doesn't work with Dart extensions. You are supposed to use [platform channels](https://flutter.dev/docs/development/platform-integration/platform-channels) or the new FFI support (this is the method I ended up using).

**Comment by escamoteur** [comment]
Awesome yes FFI is the way to go if it's a c library.
