### ISSUE TITLE
Flutter install Error：ADB exited with exit code -15

### ISSUE THREAD

**Issue by joe223** [flutter/flutter#30847]
## Steps to Reproduce

Create a flutter App via Android Studio，launch emulator and run App.

Just like this:

![image](https://user-images.githubusercontent.com/10026019/55871281-ea09c980-5bbc-11e9-9f0c-da190cac0104.png)

Only crashed on Android.

## Logs
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Error: ADB exited with exit code -15

Error launching application on Android SDK built for x86.

**Comment by mengxiaoixao** [comment]
Has the problem been solved?

**Comment by joe223** [comment]
@mengxiaoixao Not yet.

**Comment by jingle1267** [comment]
mark

**Comment by jingle1267** [comment]
```
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Error: ADB exited with exit code -15

Error launching application on Android SDK built for x86 64.
```

**Comment by BondarenkoStas** [comment]
Is it still an issue with current flutter stable v1.9.1+hotfix.4?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
