### ISSUE TITLE
Display text with a text control. The font size is different in a text.

### ISSUE THREAD

**Issue by yataoSang** [flutter/flutter#30841]
demo：
`Text(
           "杨丹",
             maxLines: 1,
              overflow: TextOverflow.ellipsis,
             style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w500,
              color: Color(0xFF252c41),),
      )
`

![246A81907493B72E88E7530E846705CB](https://user-images.githubusercontent.com/19302010/55862840-dbff7d00-5bab-11e9-8ea4-9314f36656ef.jpg)

display effect，The first word is thick，Second word fine
This is an occasional question. Has anyone encountered it? What is the solution?

**Comment by justinmc** [comment]
@yataoSang I tried this on a Mac in the iOS simulator and I can't reproduce it.  I don't have a great eye for Chinese unfortunately, but the characters look like the same weight to me.  Can you post what platform you're on and the full code of a minimal app that reproduces this?

<img width="274" alt="Screen Shot 2019-04-11 at 9 37 22 AM" src="https://user-images.githubusercontent.com/389558/55975032-e9fdde00-5c3d-11e9-966a-ee36e23df321.png">

**Comment by justinmc** [comment]
@yataoSang I tried this on a Mac in the iOS simulator and I can't reproduce it.  I don't have a great eye for Chinese unfortunately, but the characters look like the same weight to me.  Can you post what platform you're on and the full code of a minimal app that reproduces this?

<img width="274" alt="Screen Shot 2019-04-11 at 9 37 22 AM" src="https://user-images.githubusercontent.com/389558/55975032-e9fdde00-5c3d-11e9-966a-ee36e23df321.png">
