### ISSUE TITLE
Native asset files are not being included into app bundles

### ISSUE THREAD

**Issue by saitbnzl** [flutter/flutter#30846]
## Steps to Reproduce
1. Put some files under /android/app/src/main/assets
2. Run **flutter build appbundle**
3. Inspect the bundle (.aab file) to check if the files inside assets are included under base/assets/

It happens with plugins too, causing my app to crash. This is important for plugins obviously.

**Note:** They are being included with **flutter build apk**

## Flutter Doctor

[✓] Flutter (Channel master, v1.4.13-pre.6, on Mac OS X 10.14 18A391, locale en-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by dnfield** [comment]
@blasten I believe this is fixed, can you confirm?

**Comment by miguelslemos** [comment]
hey @dnfield it's not working on master at the moment

**Comment by blasten** [comment]
I think I found the issue: the Gradle plugin depends on task `cleanMerge(Release/Profile/Debug)Assets` after copying the assets, which removes the pre-existing assets. Somehow this is an issue in app bundles only (entrypoint task `bundleRelease`).

Commenting [this line](https://github.com/blasten/flutter/blob/a25da1f00e300cf61d821ef7fc6eedf336c8a12e/packages/flutter_tools/gradle/flutter.gradle#L509) out fixes the problem. @aam added this in https://github.com/flutter/flutter/pull/14085. I will need to test if the issue that it was solving is still an issue.

**Comment by miguelslemos** [comment]
Hey, We found something about ordering tasks on https://trickyandroid.com/gradle-tip-3-tasks-ordering
>I believe they will be executed in alphabetical order

We are opening a PR changing dependsOn to mustRunAfter

**Comment by jonahwilliams** [comment]
@blasten was this fixed in #33272?

**Comment by blasten** [comment]
Yep!
