### ISSUE TITLE
E/DartVM  (17171): Invalid UTF8 sequence encountered, 

### ISSUE THREAD

**Issue by Chainson** [flutter/flutter#30852]
Android 6.0 pad

Launching lib\main.dart on A89 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
E/DartVM  (17646): Invalid UTF8 sequence encountered, 
E/DartVM  (17646): (Error Code: A5 + idx: 12 )
E/DartVM  (17646): (Error Code: 85 + idx: 13 )
E/DartVM  (17646): (Error Code: 4D + idx: 14 )
E/DartVM  (17646): (Error Code: 62 + idx: 15 )
E/DartVM  (17646): (Error Code: 0 + idx: 16 )
E/DartVM  (17646): (Error Code: 33 + idx: 17 )
E/DartVM  (17646): (Error Code: B + idx: 18 )
E/DartVM  (17646): (Error Code: 40 + idx: 19 )
E/DartVM  (17646): (Error Code: 10 + idx: 20 )
E/DartVM  (17646): (Error Code: 0 + idx: 21 )
E/DartVM  (17646):

**Comment by Mohammad-ezzidden** [comment]
Any solution yet ??

**Comment by ruan65** [comment]
Same here

Installing build/app/outputs/apk/app.apk...
E/DartVM  ( 6527): Invalid UTF8 sequence encountered, 
E/DartVM  ( 6527): (Error Code: A0 + idx: 23 )
E/DartVM  ( 6527): (Error Code: 73 + idx: 24 )
E/DartVM  ( 6527): (Error Code: 68 + idx: 25 )
E/DartVM  ( 6527): (Error Code: 4D + idx: 26 )
E/DartVM  ( 6527): (Error Code: 61 + idx: 27 )
E/DartVM  ( 6527): (Error Code: 70 + idx: 28 )
E/DartVM  ( 6527): 
E/DartVM  ( 6527): ../../third_party/dart/runtime/vm/kernel_loader.h: 108: error: unreachable code
E/DartVM  ( 6527): version=2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "android_arm"
E/DartVM  ( 6527): thread=6562, isolate=vm-service(0xb843a3e8)
E/DartVM  ( 6527):   pc 0xa0232c75 fp 0x9e53d168 /data/app/ru.emc.emc_flutter_new-1/lib/arm/libflutter.so+0xe32c75
E/DartVM  ( 6527): -- End of DumpStackTrace

**Comment by MiLaDTechS** [comment]
Same...

E/DartVM  (12536): (Error Code: 8 + idx: 2 )
E/DartVM  (12536): (Error Code: 40 + idx: 3 )
E/DartVM  (12536): (Error Code: 10 + idx: 4 )
E/DartVM  (12536): (Error Code: 0 + idx: 5 )
E/DartVM  (12536): (Error Code: 3 + idx: 6 )
E/DartVM  (12536): (Error Code: 0 + idx: 7 )
E/DartVM  (12536): (Error Code: 0 + idx: 8 )
E/DartVM  (12536): (Error Code: F4 + idx: 9 )
E/DartVM  (12536): (Error Code: 20 + idx: 10 )
E/DartVM  (12536):
Exited (sigint)

**Comment by idattijo4code** [comment]
Any help! I have similar error.

Launching lib\main.dart on TECNO Y2 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
E/DartVM  ( 8003): Invalid UTF8 sequence encountered, 
E/DartVM  ( 8003): (Error Code: 93 + idx: 17 )
E/DartVM  ( 8003): (Error Code: 9 + idx: 18 )
E/DartVM  ( 8003): (Error Code: 40 + idx: 19 )
E/DartVM  ( 8003): (Error Code: 10 + idx: 20 )
E/DartVM  ( 8003): (Error Code: 0 + idx: 21 )
E/DartVM  ( 8003): (Error Code: B + idx: 22 )
E/DartVM  ( 8003): (Error Code: A0 + idx: 23 )
E/DartVM  ( 8003): (Error Code: 73 + idx: 24 )
E/DartVM  ( 8003): (Error Code: 68 + idx: 25 )
E/DartVM  ( 8003): (Error Code: 4D + idx: 26 )
E/DartVM  ( 8003): 
E/DartVM  ( 8326): Invalid UTF8 sequence encountered, 
E/DartVM  ( 8326): (Error Code: 90 + idx: 1 )
E/DartVM  ( 8326): (Error Code: D9 + idx: 2 )
E/DartVM  ( 8326): (Error Code: 55 + idx: 3 )
E/DartVM  ( 8326): (Error Code: 11 + idx: 4 )
E/DartVM  ( 8326): (Error Code: D6 + idx: 5 )
E/DartVM  ( 8326): (Error Code: A9 + idx: 6 )
E/DartVM  ( 8326): (Error Code: 55 + idx: 7 )
E/DartVM  ( 8326): (Error Code: 49 + idx: 8 )
E/DartVM  ( 8326): (Error Code: 6E + idx: 9 )
E/DartVM  ( 8326): (Error Code: 74 + idx: 10 )
E/DartVM  ( 8326): 
E/DartVM  ( 8326): ../../third_party/dart/runtime/vm/object.cc: 19830: error: unreachable code
E/DartVM  ( 8326): version=2.3.0-dev.0.5.flutter-a1668566e5 (Tue Apr 30 20:35:41 2019 +0200) on "android_arm"
E/DartVM  ( 8326): thread=8340, isolate=main(0x56c26a40)
E/DartVM  ( 8326):   pc 0x5598ac75 fp 0x55d99738 libflutter.so+0xe32c75
E/DartVM  ( 8326): -- End of DumpStackTrace

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

If so, please paste the output of `flutter doctor -v` here

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
