### ISSUE TITLE
AppCenter can't find the android project

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [flutter/flutter#30858]
I have just created a flutter app and setting up CI/CD on AppCenter.

Below is the screenshot of .gitignore that comes with project

![image](https://user-images.githubusercontent.com/10863510/55898356-079c5a80-5be0-11e9-8580-0cef9854fed5.png)

The app center is unable to detect the android app as some files are ignored while committing the code.

![image](https://user-images.githubusercontent.com/10863510/55898137-99f02e80-5bdf-11e9-9b8f-028625fa992f.png)

When I commented on the .gitignore as shown below, the app center is able to detect the android project.

![image](https://user-images.githubusercontent.com/10863510/55898566-7da0c180-5be0-11e9-9984-19ad2aeead39.png)

**Comment by sawankumarbundelkhandi** [comment]
More info here - https://github.com/flutter/flutter/issues/17197#issuecomment-431405615

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by sawankumarbundelkhandi** [comment]
@escamoteur I have solved the problem by commenting on some files in gitignore.

Also, I just created a new project and the .gitignore still ignore those files.

![image](https://user-images.githubusercontent.com/10863510/66125381-6af1cd00-e604-11e9-89a6-d9c25dad930d.png)

**Comment by escamoteur** [comment]
So you mean the generated .gitignore should not comment them?

**Comment by sawankumarbundelkhandi** [comment]
No, It should comment them.

**Comment by escamoteur** [comment]
Ah so more files should be part of the repository.
@jonahwilliams would this have other negative effects on builds?

**Comment by jmagman** [comment]
The screenshot `.gitignore` is in the Flutter SDK, not in the `.gitignore` generated in a new Flutter app.
1. Did you make your app inside the Flutter SDK directory?
1. What is the path of the `.gitignore` where you found those `**/android` lines?

**Comment by sawankumarbundelkhandi** [comment]
@jmagman The screenshots are of a new flutter project created outside of flutter SDK. The path of the gitignore is project_name/.gitignore

**Comment by jmagman** [comment]
> The screenshot `.gitignore` is in the Flutter SDK, not in the `.gitignore` generated in a new Flutter app.

Never mind, here it is in the .gitignore template.
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/package/.gitignore.tmpl

https://github.com/flutter/flutter/pull/21192/files#diff-04b485fe372701a7c887a1399c557f10R32

**Comment by jonahwilliams** [comment]
The default git ignore includes the build directory, where APK files would be built. Usually most projects dont want to upload these to Github or other version control.

If you want to do so, you can always remove the line from your project specific gitignore. In general, this is a good default though so we're unlikely to change it
