### ISSUE TITLE
Required fields are not marked with an asterisk

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3085]
From https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

Looks like we should use an asterisk with Name ?

![screenshot_20160404-134140](https://cloud.githubusercontent.com/assets/5479/14262647/6dee60b4-fa6b-11e5-9110-bc65024375b7.png)

**Comment by sethladd** [comment]
cc @mpcomplete

**Comment by eseidelGoogle** [comment]
There appear to be some subtle issues with animation of labels too.  This may need to wait for full review of this component.  Asterisks would be easy to add though. :)

**Comment by eseidelGoogle** [comment]
Still an issue today.
![simulator screen shot jan 26 2017 3 53 49 pm](https://cloud.githubusercontent.com/assets/11857803/22355487/aa34629a-e3df-11e6-9eaf-6e45bbca2446.png)

**Comment by Hixie** [comment]
In the example in the spec the label text itself goes red, then just the asterisk goes red, and I couldn't figure out the logic there. But other than that, I fixed it.
