### ISSUE TITLE
No Fragment Support

### ISSUE THREAD

**Issue by mritunjay10** [flutter/flutter#30856]
I have been working with flutter it's rich. It would be great if there is a fragment just like in android.
It's not good to always Navigating to a new view.

If it's already in flutter please kindly add some links for reference.

Thanks

**Comment by escamoteur** [comment]
Not sure what you want to achieve with this. What about Dialogs?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
