### ISSUE TITLE
Add support for persistent helper text

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3086]
According to https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

"Helper text, or hint text, should appear below the text field and either be persistently visible, or only visible on focus."

Looks like we don't demo persistent helper/hint text below the field:

![screenshot_20160404-134140](https://cloud.githubusercontent.com/assets/5479/14262706/a4c1ce46-fa6b-11e5-9d8c-d46198215018.png)

**Comment by abarth** [comment]
We don't support persistent helper text.  We do support the kind of hint text that's shown inline in the text field, which is different.  (There are at least four kinds of helper/hint/label/valdiation text in material.)

**Comment by sethladd** [comment]
Thanks for the clarification!

**Comment by eseidelGoogle** [comment]
This is just one more thing for @mpcomplete when he gets back to text fields. :)  Probably not for our first Gallery release.

**Comment by Hixie** [comment]
In the example in the spec the label text itself goes red, then just the asterisk goes red, and I couldn't figure out the logic there.

**Comment by Hixie** [comment]
@HansMuller Can you take a look and determine if you've done this, or if the new UX guidelines for text fields that you are implementing say this should not happen, or if it's something that you want to do soon, and comment and/or close accordingly? Thanks.

**Comment by HansMuller** [comment]
We now render persistent helper text as specified in https://material.io/design/components/text-fields.html
