### ISSUE TITLE
[camera] Without ResolutionPreset  UltraHigh quality is sub optimal

### ISSUE THREAD

**Issue by xellDart** [flutter/flutter#30872]
Hello, I'm using the latest version of the plugin available for the camera, but the quality I get is too bad, is there any way to improve this quality?
Device: Huawei P20
Android 8.0
Flutter: Last version

Code:
```
import 'dart:convert';
import 'dart:io';
import 'package:native_device_orientation/native_device_orientation.dart';
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter_native_image/flutter_native_image.dart';
import 'package:path_provider/path_provider.dart';
import 'package:random_string/random_string.dart';
import 'package:rem/localizations/localizations.dart';

class DocumentScanner extends StatefulWidget {
  final List<CameraDescription> cameras;
  DocumentScanner({Key key, this.cameras}) : super(key: key);
  @override
  DocumentScannerState createState() => DocumentScannerState();
}

class DocumentScannerState extends State<DocumentScanner> {
  CameraController controller;
  bool isComplete = false;
  String legend = '';
  String image;
  String imagePath;

  @override
  void initState() {
    try {
      onCameraSelected(widget.cameras[0]);
      legend = AppLocalizations.of(context).takeRectangle;
    } catch (e) {
      print(e.toString());
    }
    super.initState();
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  void log(String message) => print('Message: $message');

  Widget imageWidget() {
    return ClipRRect(
        borderRadius: BorderRadius.circular(10.0),
        child: Container(
            decoration: BoxDecoration(
          image: DecorationImage(
            fit: BoxFit.fill,
            image: new FileImage(new File(imagePath)),
          ),
        )));
  }

  void onCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) {
      await controller.dispose();
    }
    controller = CameraController(cameraDescription, ResolutionPreset.medium);
    controller.addListener(() {
      if (mounted) setState(() {});
      if (controller.value.hasError) {
        log('Camera error ${controller.value.errorDescription}');
      }
    });
    try {
      controller.initialize().then((_) {
        if (!mounted) {
          return;
        }
        setState(() {});
      });
    } on CameraException catch (e) {
      log(e.description);
    }
    if (mounted) {
      setState(() {});
    }
  }

  tap() {
    if (imagePath != null) {
      setState(() {
        imagePath = null;
        isComplete = false;
        legend = AppLocalizations.of(context).takeRectangle;
      });
      return;
    }
    takePicture().then((String filePath) {
      if (mounted) {
        setState(() {
          imagePath = filePath;
        });
      }
      if (filePath != null) {
        setCameraResult();
      }
    });
  }

  void setCameraResult() async {
    File compressedFile = await FlutterNativeImage.compressImage(imagePath,
        quality: 90, targetWidth: 520, targetHeight: 760);
    List<int> imageBytes = compressedFile.readAsBytesSync();
    image = base64Encode(imageBytes);
    setState(() {
      legend = AppLocalizations.of(context).takeRectangleReset;
      isComplete = true;
    });
  }

  Future<String> takePicture() async {
    if (!controller.value.isInitialized) {
      return null;
    }
    Directory tempDir = await getTemporaryDirectory();
    final String filePath = '${tempDir.path}/${randomAlpha(6)}.jpg';

    if (controller.value.isTakingPicture) {
      return null;
    }
    try {
      await controller.takePicture(filePath);
    } on CameraException catch (e) {
      log(e.description);
      return null;
    }
    return filePath;
  }

  reset() {
    setState(() {
      imagePath = null;
      isComplete = false;
    });
  }

  sendImage() {}

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;

    if (!controller.value.isInitialized) return Container();
    Widget cap = AspectRatio(
        aspectRatio:
        controller.value.aspectRatio,
        child: CameraPreview(controller));
    if (imagePath != null) {
      cap = imageWidget();
    }
    return new Container(
        child: new Stack(
          children: <Widget>[
            Container(
              child: Padding(
                padding: const EdgeInsets.all(1.0),
                child: Center(
                  child: cap,
                ),
              ),
              decoration: BoxDecoration(
                color: Colors.black,
                border: Border.all(
                  color: controller != null && controller.value.isRecordingVideo
                      ? Colors.redAccent
                      : Colors.grey,
                  width: 3.0,
                ),
              ),
            ),

            new ClipPath(
                clipper: new InvertedCircleClipper(width: width/13, heigth: height/3),
                child: new Container(
                  color: new Color.fromRGBO(0, 0, 0, 0.5),
                ),
              ),
          ],
        ),
      );
  }
}


class InvertedCircleClipper extends CustomClipper<Path> {
  final double width;
  final double heigth;
  InvertedCircleClipper({this.width, this.heigth});
  @override
  Path getClip(Size size) {
    return new Path()
      ..addRect(new Rect.fromLTWH(width, heigth, 300, 200))
      ..addRect(new Rect.fromLTWH(0.0, 0.0, size.width, size.height))
      ..fillType = PathFillType.evenOdd;
  }

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) => false;
}
```
[url=https://ibb.co/Gv0yYVZ][img]https://i.ibb.co/tM4gjb0/Screenshot-20190410-160518.jpg[/img][/url]

**Comment by ToxicAlex** [comment]
Try use `ResolutionPreset.high` rather than `ResolutionPreset.medium`.

**Comment by xperiafan13-rom** [comment]
> Try use `ResolutionPreset.high` rather than `ResolutionPreset.medium`.

I alreay set this, but i have some result

**Comment by CodeNextGen** [comment]
What about setting quality:100 in `File compressedFile = await FlutterNativeImage.compressImage(imagePath,
        quality: 90, targetWidth: 520, targetHeight: 760);`

**Comment by andre-bahia** [comment]
I'm having the same problem.

**Comment by tapizquent** [comment]
I am not compressing my image, pretty much just showing it, but for some reason, the quality looks really bad. I am using an example such as the Take a picture with camera from flutter docs. I have bumped up the ResolutionReset to UltraHigh, but I really doubt it needs to be on that all the time for the image to be relatively decent. Any help on that? workarounds?

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by tapizquent** [comment]
As mentioned above, the only workaround seems to be setting the ResolutionPreset to UltraHigh, which I believe shouldn’t be the best solution

**Comment by iapicca** [comment]
Hi @xellDart  and @tapizquent
If you are still experiencing this issue 
could you please provide your updated  `flutter doctor -v`?
Thank you

**Comment by ro0t** [comment]
Using UltraHigh/Max on iOS, still pretty shit.. when will we get an usable camera plugin for flutter? 😢

**Comment by iapicca** [comment]
@ro0t 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem
Thank you

**Comment by digibum** [comment]
What is the actual resolution you get from camera?
I have it set up for veryHigh but get only 1280×720 on Samsung Galaxy S9!

**Comment by digibum** [comment]
Code below should return CameraImage with resolution of 3840×2160px on Samsung Galaxy S9. but it returns only 1280×720.
```
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

class CameraPreviewPage extends StatefulWidget {
  CameraPreviewPage({Key key}) : super(key: key);

  @override
  _CameraPreviewPageState createState() => _CameraPreviewPageState();
}

class _CameraPreviewPageState extends State<CameraPreviewPage> {
  List<CameraDescription> cameras;
  CameraController controller;
  String resolution = '0 × 0';

  @override
  void initState() {
    super.initState();
    setup();
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  Future<Null> setup() async {
    cameras = await availableCameras();
    controller = CameraController(cameras[0], ResolutionPreset.ultraHigh);
    await controller.initialize();
    await controller.startImageStream(onAvailable);
  }

  @override
  Widget build(BuildContext context) {
    Widget preview = Container();
    if (controller.value.isInitialized)
      preview = AspectRatio(
          aspectRatio: controller.value.aspectRatio,
          child: CameraPreview(controller));
    return Scaffold(
        appBar: AppBar(
          title: Text('Camera resolution'),
        ),
        body: ListView(
          children: <Widget>[
            ListTile(
              title: Text(resolution),
            ),
            preview
          ],
        ));
  }

  onAvailable(CameraImage image) {
    setState(() {
      resolution = 'CameraImage ${image.width} × ${image.height}';
    });
  }
}
```

[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18363.476], locale en-SI)
    • Flutter version 1.9.1+hotfix.5 at F:\Flutter
    • Framework revision 1aedbb1835 (7 weeks ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = F:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\Matej\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • SM G960F • 22cd3be09c0d7ece • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by EArminjon** [comment]
> Code below should return CameraImage with resolution of 3840×2160px on Samsung Galaxy S9. but it returns only 1280×720.
> 
> ```
> import 'package:camera/camera.dart';
> import 'package:flutter/material.dart';
> 
> class CameraPreviewPage extends StatefulWidget {
>   CameraPreviewPage({Key key}) : super(key: key);
> 
>   @override
>   _CameraPreviewPageState createState() => _CameraPreviewPageState();
> }
> 
> class _CameraPreviewPageState extends State<CameraPreviewPage> {
>   List<CameraDescription> cameras;
>   CameraController controller;
>   String resolution = '0 × 0';
> 
>   @override
>   void initState() {
>     super.initState();
>     setup();
>   }
> 
>   @override
>   void dispose() {
>     controller?.dispose();
>     super.dispose();
>   }
> 
>   Future<Null> setup() async {
>     cameras = await availableCameras();
>     controller = CameraController(cameras[0], ResolutionPreset.ultraHigh);
>     await controller.initialize();
>     await controller.startImageStream(onAvailable);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     Widget preview = Container();
>     if (controller.value.isInitialized)
>       preview = AspectRatio(
>           aspectRatio: controller.value.aspectRatio,
>           child: CameraPreview(controller));
>     return Scaffold(
>         appBar: AppBar(
>           title: Text('Camera resolution'),
>         ),
>         body: ListView(
>           children: <Widget>[
>             ListTile(
>               title: Text(resolution),
>             ),
>             preview
>           ],
>         ));
>   }
> 
>   onAvailable(CameraImage image) {
>     setState(() {
>       resolution = 'CameraImage ${image.width} × ${image.height}';
>     });
>   }
> }
> ```
> 
> [√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18363.476], locale en-SI)
> • Flutter version 1.9.1+hotfix.5 at F:\Flutter
> • Framework revision [1aedbb1](https://github.com/flutter/flutter/commit/1aedbb1835bd6eb44550293d57d4d124f19901f0) (7 weeks ago), 2019-10-17 08:37:27 -0700
> • Engine revision b863200c37
> • Dart version 2.5.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> • Android SDK at F:\Android\Sdk
> • Android NDK location not configured (optional; useful for native profiling support)
> • Platform android-29, build-tools 28.0.3
> • ANDROID_HOME = F:\Android\Sdk
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 3.4)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 37.0.1
> • Dart plugin version 183.6270
> • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [√] VS Code (version 1.40.2)
> • VS Code at C:\Users\Matej\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.6.0
> 
> [√] Connected device (1 available)
> • SM G960F • 22cd3be09c0d7ece • android-arm64 • Android 9 (API 28)
> 
> • No issues found!

Same issue with emulator 800/1280, I got 320x240... A beautiful joke :D.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by EArminjon** [comment]
https://github.com/flutter/flutter/issues/56760

**Comment by iapicca** [comment]
> Oct 06 and I have the same problem. Anyone get some solution?

@stephancapistrano 
this issue is closed since Dec 5, 2019
therefore nobody is working on it
as you can see from the comment just above yours 
@EArminjon opened an [issue](https://github.com/flutter/flutter/issues/56760) for a similar situation 
if said issue represent the difficulties you are encountering follow up there
otherwise feel free to open a new issue, providing
your `flutter doctor -v`, your` pubspec.yaml` and most importantly a minimal reproducible code sample

**Comment by stephancapistrano** [comment]
My problem: I'm trying to use de ultraHigh resolution (3840x2160), but the max resolution I get is 1920x1080. I wanna know how do I get a better resolution, something above 5mpx.

**flutter doctor -v**

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.20.4 at /Users/stephan/Tools/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/stephan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM A105M (mobile) • RX8M80MMJJT • android-arm • Android 10 (API 29)

• No issues found!

**pubspec.yaml**

name: camera_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  camera: ^0.5.8+7
  path_provider: ^1.6.18
  video_player: ^0.11.0 

dev_dependencies:
  flutter_test:
    sdk: flutter


**Code**

https://pub.dev/packages/camera/example
