### ISSUE TITLE
Error HTTP Exception  1059 flutter usb iPhone

### ISSUE THREAD

**Issue by zuzutahan** [flutter/flutter#30885]
Im getting error when i try to run the app on my iPhone.
I tried to fix it with NO_PROXY=localhost,127.0.0.1; flutter run

flutter run -v gave me this
 +16 ms] Connecting to service protocol: http://127.0.0.1:1059/
[  +43 ms] Error connecting to the service protocol: HttpException: , uri =
           http://127.0.0.1:1059/ws
[   +4 ms] "flutter run" took 49,513ms.
[        ] "flutter run" took 49,513ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:427:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure>
(dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:5)

Second Error same one:

NO_PROXY=localhost,127.0.0.1; flutter run --start-paused
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team
in Xcode project: M6E2BGCTT7
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           3.6s
 └─Compiling, linking and signing...                         4.6s
Xcode build done.                                           11.1s
5.20.0 - [Firebase/Analytics][I-ACS023007] Analytics v.50801000 started 
5.20.0 - [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Installing and launching...                                        22.4s
Error connecting to the service protocol: HttpException: , uri =
http://127.0.0.1:1057/ws

**Comment by c0h1b4** [comment]
Same issue here: https://github.com/flutter/flutter/issues/32651

Please flutter team, solve this long time issue. I see people complaining about this for more than 6 months.

**Comment by escamoteur** [comment]
It seems this issue was solved with https://github.com/flutter/flutter/issues/32651

If it still persists please reopen the issue and please paste the output of `flutter doctor -v` here
