### ISSUE TITLE
Text field line double-flashes when gains or loses focus

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3088]
Here's a movie that shows the behavior: https://dl.dropboxusercontent.com/u/316685/video5.mp4

Notice how, as focus moves between New Password and Re-type Password, the line for the "New Password" field flashes twice to purple.

**Comment by abarth** [comment]
Looks suspiciously like the shadow flashing bug.  I suspect we're somehow using old data to draw in the compositor somewhere.

**Comment by sethladd** [comment]
Fixed!
