### ISSUE TITLE
Firebase pluggins don't use the latest version of the iOS pods

### ISSUE THREAD

**Issue by AYM1607** [flutter/flutter#30888]
I was trying to contribute to the cloud_firestore by adding support for the increment FieldValue, after trying to compile a test app I am getting this xcode build log:

`Xcode's output:
↳
    === BUILD TARGET cloud_firestore OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/aym/Projects/open_source/plugins/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m:240:29: error: no known class
    method for selector 'fieldValueForIntegerIncrement:'
          return [FIRFieldValue fieldValueForIntegerIncrement:[self readValue]];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/aym/Projects/open_source/plugins/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m:243:29: error: no known class
    method for selector 'fieldValueForDoubleIncrement:'
          return [FIRFieldValue fieldValueForDoubleIncrement:[self readValue]];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.`

I was able to track down the issue to the version of the Firebase and Firebase/Firestore being used, after trying to use pod update the versions stayed the same, 5.11 and 0.13.6 respectively. The version of Firebase/Firestore is about 6 months old and is missing some features.

Where is the dependency on 5.11 specified? and why not use the latest version?

**Comment by DarshanGowda0** [comment]
@zoechi FieldValue.increment() is a cool feature that's missing on flutter version of cloud_firestore, can we have an update on this, please?

**Comment by hrag** [comment]
Also having this issue. Womp womp.

**Comment by dakamojo** [comment]
I ran into this issue too.  Please help me understand.  Does version 0.10.0 make reference to functions not in the pod that it targets?  Can I somehow force update that pod?  Or can I somehow go back to a previous version of the plugin?

**Comment by AYM1607** [comment]
The cloud_firestore plugin has beeen updated to support FieldValue.increment

**Comment by nagik23** [comment]
> The cloud_firestore plugin has beeen updated to support FieldValue.increment

Still getting this error with cloud_firestore-0.10.1
