### ISSUE TITLE
Tabs and Scrolling, third tab should be "THREE" ?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3089]
The tabs are "ONE, TWO, FREE, FOUR". Maybe the third one should be THREE ?

![screenshot_20160404-142642](https://cloud.githubusercontent.com/assets/5479/14263792/7c2e4a08-fa71-11e5-91ec-4c709bd0a1e1.png)

**Comment by HansMuller** [comment]
It's about Pink Floyd: https://en.wikipedia.org/wiki/Free_Four
