### ISSUE TITLE
Flutter run crashes with connection reset error

### ISSUE THREAD

**Issue by JohnBanfield** [flutter/flutter#30894]
Hi,

I am just trying this out and am getting the  Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
error from the getting strted sequence, using osx.
I have tried the flutter build --offline xxx .option which succeeds
then I try flutter run xxx and I get the connection reset error from https://github.com/flutter/flutter/issues/25117

I tried making the changes as per https://github.com/flutter/flutter/issues/23727#issuecomment-435019094

I still have the same issue. I am trying to use the android emulator toolchain.

Thanks,
jb

## crash log
[flutter_02.log](https://github.com/flutter/flutter/files/3067115/flutter_02.log)

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G2208, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by JohnBanfield** [comment]
Hi, if there is anyone out there, 
We do have flaky internet here - I can get files to come down but there are retries involved. Is there a way to do a flutter run without calling out to the internet? I really want to do offline development here.

I tried to download the gradle distribution manually and put it in a wrapper/dists folder but no luck.

I am blocked and will have to fall back to another platform soon.

TIA, jb

**Comment by jonahwilliams** [comment]
cc @dnfield , is there a way to manually trigger the gradle download?

**Comment by dnfield** [comment]
```
cd android
./gradlew assembleDebug
```

Should end up downloading whatever is needed.

**Comment by dnfield** [comment]
If this is your first time running Gradle to build an Android project, it's going to try to download a lot of stuff into a cache for you.

**Comment by JohnBanfield** [comment]
Thanks, I'll give it a go this weekend.

**Comment by JohnBanfield** [comment]
Thanks for this, I now have a working app.
To get it working I:

ran ./gradlew assembleDebug multiple times - about 10, until my poor internet connection decided to complete the download without dying.

restored my flutter.gradle file to original from the distro zip file.

ran flutter run a couple of times.

IMHO, I do think that it would be great to have a 'golden image' zip distro for offline customers, that you could just download and install the complete platform.

Anyway, thanks for the help.

Cheers,
jb
