### ISSUE TITLE
How to implement a standard behaviour for a widget

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#30909]
I want to address the following scenario:

A screen/widget is being displayed (pushed).
This screen needs to:

- perform a perform a long task (a request) the first time when it is created
- show a loading while it is performing the task(reqeusting)
- display an error dialog if required (failed request)
- update the list accordingly when the task finishes 
- have an outside trigger to update and restart the long task (request the data again + loading and alerts included)

——————————————————————————

I have reached a conclusion that you cannot have this behaviour without:

- a delay mechanism to display the error dialog (addPostFrameCallback or Future.delayed) 
- a state mechanism for handling the component behaviour (initial/*loading*/non loading/finished). This state mechanism implies a stream for state or calling setState at key moments and reacting to current status.

**Comment by superciccio** [comment]
have you tried using this
https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html

**Comment by durduman** [comment]
@superciccio Yes. Here (https://stackoverflow.com/questions/55631289/how-to-implement-a-standard-behaviour-for-a-widget)  is a more detailed description of the situation:

**Comment by iapicca** [comment]
Hi @durduman 
I believe opening your question on SO has being the right decision.
Please see https://flutter.dev/community for resources for asking questions like this.

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
