### ISSUE TITLE
[bug][ios] UiKitView and url_launcher conflict

### ISSUE THREAD

**Issue by andrea689** [flutter/flutter#30903]
When I use a widget that use a UiKitView (I tested Map and WebView) If I use url_launcher in the same page of UiKitView is ok, but if I use url_launcher in another page and go back to page with UiKitView the UI freezes and only if send to background and reopen the app, it starts working again.

The same problem occurs when I open another app through a click in a notification and go back to my app instead of use url_launcher.

[Demo code](https://gist.github.com/andrea689/5ff5b43506316fa9807de79b85d8996c)

![Bug UiKitView](https://user-images.githubusercontent.com/5927329/55946263-a9599100-5c4c-11e9-9963-827a6b953ff1.gif)

## Steps to Reproduce

1. Open a new page
2. Click a button that launch an URL with url_launcher
3. Close "Safari View Controller"
4. Go back to previous page

## Logs

# flutter analyze

```
Analyzing map_street_names_problem...                            
No issues found! (ran in 2.1s)
```

# flutter doctor -v

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.2.1 at /Users/andrea/Development/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrea/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone di andrea • 4143d720cc928612c001b4f8ddb0eb2d7ecd5d5a • ios • iOS 11.4.1
```

**Comment by sam-toon** [comment]
This looks to be the same as #28920 which has been fixed on the master and dev branches.

**Comment by andrea689** [comment]
I must use Flutter 1.1.8 to solve another issue (flutter#30565), but I confirm that with PR flutter/engine#8175 I solved this issue.
