### ISSUE TITLE
[local_auth] iOS popup blocks underlying animations.

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#30907]
## Steps to Reproduce

1. Open screen 1
2. trigger the `_localAuth.authenticateWithBiometrics(localizedReason: 'reason') in didChangeDependencies. of screen 2
2. navigate to screen 2
3. UI is blocked

This is the result:
<img src="https://user-images.githubusercontent.com/21172855/55952504-17588500-5c5a-11e9-9ad5-c878292c273c.gif" width="300" height="600" />

No problem with Android. 
Same problem with iOS Touch Id and FaceId.

I use a material app. and I just push a named route. Is didchangeDependencies the correct place to trigger this? I need something from my arguments. (userId)

## Logs

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-BE)
    • Flutter version 1.2.1 at /Users/koenvanlooveren/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/koenvanlooveren/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/koenvanlooveren/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone XR                 • 521E3673-75F4-41AF-A74C-6D43E6C1A700 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 1 category.

```

**Comment by vanlooverenkoen** [comment]
`await Future.delayed(Duration(milliseconds: 500));`
before triggering the dialog will fix the issue. 

**WORKAROUND NOT A FIX**

**Comment by ShaiDemri** [comment]
@vanlooverenkoen thanks for the workaround!
what is the status of that issue? Is it fixed already? being worked on?
Thanks!

**Comment by vanlooverenkoen** [comment]
Not that I know of

**Comment by macmatrix** [comment]
I have the same problem, I am trying to call `_localAuth.authenticateWithBiometrics` in `initState()` and I get the same effect. The animation get frozen and no pop up

**Comment by iapicca** [comment]
Hi @vanlooverenkoen 
Are you still experiencing the issue 
with the latest stable version of Flutter and `local_auth`?
If so, can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by VladyslavBondarenko** [comment]
@vanlooverenkoen 
I hope it's fixed,
If it's not so, comment please and I'll reopen it
