### ISSUE TITLE
I want to be able to send action events (e.g. TAP) programatically

### ISSUE THREAD

**Issue by schurik77799** [flutter/flutter#30905]
Hello colleagues. I faced the following problem: DropdownButton / CupertinoPicker doesn't have open API to call tap event programatically. I assume that it would be great to have feature like in iOS **Send action event**: 
[picker sendActionsForControlEvents:UIControlEventTouchDown];

So this will help me present DropdownButton / CupertinoPicker popup programatically without forcing user to do it. Sorry if I am missing already existing solutions.

Thanks in advance any help.

**Comment by escamoteur** [comment]
Hi, you can just set `expanded`parameter to `true` inside a `setState` and it will open.
