### ISSUE TITLE
图片在不同dpi中适配问题

### ISSUE THREAD

**Issue by EvilPalace** [flutter/flutter#30902]
目前公司通用做了3套dpi图，1.0x，2.0x，3.0x，当dpi为240即1.5x时，根据flutter框架中image_resolution.dart中的_findNearest函数会匹配到1.0x图，会让在240dpi设备上展示失真。希望有个方法可以设置匹配情况，而不由我们直接修改framework. 其中framework中适配代码如下:

// Return the value for the key in a [SplayTreeMap] nearest the provided key.
  String _findNearest(SplayTreeMap<double, String> candidates, double value) {
    if (candidates.containsKey(value))
      return candidates[value];
    final double lower = candidates.lastKeyBefore(value);
    final double upper = candidates.firstKeyAfter(value);
    if (lower == null)
      return candidates[upper];
    if (upper == null)
      return candidates[lower];
    if (value > (lower + upper) / 2)
      return candidates[upper];
    else
      return candidates[lower];
  }

**Comment by yohom** [comment]
用工具生成一套1.5x的图？
