### ISSUE TITLE
Red screen error on Android is obscured by the System UI header

### ISSUE THREAD

**Issue by gregsimon** [flutter/flutter#3091]
When a red-screen-of-death appears, the text is hidden behind the Android SystemUI header. Suggest move down the height of the system UI header bar.

**Comment by abarth** [comment]
Yeah, we should probably center the text vertically.  /cc @Hixie

**Comment by Hixie** [comment]
Can do.

For the record, the exception is also logged to the console.

**Comment by sethladd** [comment]
Just ran into this with a designer learning how to code with Flutter. This is really hard to use:

![img_20170111_155359](https://cloud.githubusercontent.com/assets/5479/21872004/b760f3fa-d81a-11e6-81dc-1c22d3fe1469.jpg)

**Comment by sethladd** [comment]
Making this screen really useful would be a selling point. If this is an easy fix, this seems like a easy win for big payoff. Recovering from errors should be quick with Flutter.

**Comment by sethladd** [comment]
Also reported here: https://github.com/flutter/flutter/issues/7483

**Comment by Hixie** [comment]
The line spacing is also way off right now for some reason.

**Comment by dvdwasibi** [comment]
It would be useful if we bump the font size up too.

**Comment by sethladd** [comment]
Agreed, the font is very small and hard to read.
