### ISSUE TITLE
Either the Crashlytics plugin doesn't work, or the instruction is wrong

### ISSUE THREAD

**Issue by wiradikusuma** [flutter/flutter#30913]
I followed the setup instruction from Pub: https://pub.dartlang.org/packages/firebase_crashlytics

I also enabled debug logging: https://firebase.google.com/docs/crashlytics/force-a-crash

Crashlytics seems to be running when my app is started:

	04-11 19:48:09.800  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:09.801  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:09.836  5815  5863 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:09.836  5815  5863 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:09.836  5815  5863 D Fabric  : Generating Crashlytics ApiKey from google_app_id in Strings
	04-11 19:48:09.847  5815  5873 D Fabric  : Using AdvertisingInfo from Preference Store
	04-11 19:48:09.850  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:09.850  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:09.852  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:09.852  5815  5863 D Fabric  : Build ID is: 597ad0fd-xxxx-xxxx-xxxx-cc4204e14e50
	04-11 19:48:09.852  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:09.852  5815  5815 D Fabric  : Generating Crashlytics ApiKey from google_app_id in Strings
	04-11 19:48:09.852  5815  5815 D Fabric  : Build ID is: 597ad0fd-xxxx-xxxx-xxxx-cc4204e14e50
	04-11 19:48:09.853  5815  5815 I CrashlyticsCore: Initializing Crashlytics 2.6.8.32
	04-11 19:48:09.855  5815  5873 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:09.856  5815  5873 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:09.858  5815  5873 D Fabric  : Build ID is: 597ad0fd-xxxx-xxxx-xxxx-cc4204e14e50
	04-11 19:48:09.859  5815  5815 D CrashlyticsCore: Installer package name is: null
	04-11 19:48:09.865  5815  5863 D Fabric  : Build ID is: 597ad0fd-xxxx-xxxx-xxxx-cc4204e14e50
	04-11 19:48:09.882  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:09.882  5815  5815 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:09.883  5815  5815 D CrashlyticsCore: Exception handling initialization successful
	04-11 19:48:09.883  5815  5815 D Fabric  : Initializing io.fabric.sdk.android:fabric [Version: 1.4.8.32], with the following kits:
	04-11 19:48:09.883  5815  5815 D Fabric  : com.crashlytics.sdk.android:crashlytics [Version: 2.9.9.32]
	04-11 19:48:09.883  5815  5815 D Fabric  : com.crashlytics.sdk.android:beta [Version: 1.2.10.27]
	04-11 19:48:09.883  5815  5815 D Fabric  : com.crashlytics.sdk.android:answers [Version: 1.4.7.32]
	04-11 19:48:09.883  5815  5815 D Fabric  : com.crashlytics.sdk.android.crashlytics-core [Version: 2.6.8.32]
	04-11 19:48:09.883  5815  5815 D Fabric  :
	04-11 19:48:09.884  5815  5863 D Fabric  : Requesting settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.myapp/settings
	04-11 19:48:09.884  5815  5863 D Fabric  : Settings query params were: {instance=61ebeb4d13cce55a1f3a99f42e32b65ca2b2xxxx, build_version=1, display_version=0.0.1, source=1, icon_hash=204b9a3f51a1102e42ef65e3a6c4f8cda2ebxxxx}
	04-11 19:48:09.885  5815  5879 D CrashlyticsCore: Opening a new session with ID 5CAF29790373-0001-16B7-47070E28DA82
	04-11 19:48:10.625  5815  5875 D Fabric  : Using AdvertisingInfo from Reflection Provider
	04-11 19:48:11.309  5815  5863 D Fabric  : Settings result was: 200
	04-11 19:48:11.314  5815  5863 D Fabric  : Settings request ID: affca8bcac5aee10b1b37bf2a6cb00f6
	04-11 19:48:11.315  5815  5863 D Fabric  : Writing settings to cache file...
	04-11 19:48:11.320  5815  5863 D Fabric  : Loaded settings: {"settings_version":2,"cache_duration":7200,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":true,"prompt_enabled":false,"push_enabled":true,"firebase_crashlytics_enabled":true},"analytics":{"url":"https:\/\/e.crashlytics.com\/spi\/v2\/events","flush_interval_secs":120,"max_file_count_per_send":1,"track_custom_events":true,"track_predefined_events":true,"track_view_controllers":false,"flush_on_background":true,"max_byte_size_per_file":40000,"max_pending_send_file_count":20,"sampling_rate":1,"forward_to_google_analytics":false,"include_purchase_events_in_forwarded_events":false},"beta":{"update_suspend_duration":1209600,"update_endpoint":""},"app":{"identifier":"com.myapp","status":"activated","url":"https:\/\/api.crashlytics.com\/spi\/v1\/platforms\/android\/apps\/com.myapp","reports_url":"https:\/\/reports.crashlytics.com\/spi\/v1\/platforms\/android\/apps\/com.myapp\/reports","ndk_reports_url":"https:\/\/reports.crashlytics.com\/sdk-api\/v1\/platforms\/android\/apps\/com.myapp\/minidumps","update_required":true},"session":{"log_buffer_size":64000,"max_chained_exception_depth":16,"max_complete_sessions_count":4,"max_custom_exception_events":8,"max_custom_key_value_pairs":64,"identifier_mask":255},"prompt":{"title":"Send Crash Report?","message":"Looks like we crashed! Please help us fix the problem by sending a crash report.","send_button_title":"Send","show_cancel_button":true,"cancel_button_title":"Don't Send","show_always_send_button":true,"always_send_button_title":"Always Send"},"expires_at":1554990491315}
	04-11 19:48:11.322  5815  5863 D Fabric  : Build ID is: 597ad0fd-xxxx-xxxx-xxxx-cc4204e14e50
	04-11 19:48:11.323  5815  5863 D Fabric  : Server says an update is required - forcing a full App update.
	04-11 19:48:11.324  5815  5863 D Fabric  : App icon resource ID is 213136xxxx
	04-11 19:48:11.326  5815  5863 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:11.326  5815  5863 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:11.326  5815  5863 D Fabric  : Generating Crashlytics ApiKey from google_app_id in Strings
	04-11 19:48:11.327  5815  5863 D Fabric  : Build ID is: 597ad0fd-xxxx-xxxx-xxxx-cc4204e14e50
	04-11 19:48:12.193  5815  5863 D Fabric  : Sending app info to https://api.crashlytics.com/spi/v1/platforms/android/apps/com.myapp
	04-11 19:48:12.194  5815  5863 D Fabric  : App icon hash is 204b9a3f51a1102e42ef65e3a6c4f8cda2ebxxxx
	04-11 19:48:12.194  5815  5863 D Fabric  : App icon size is 192x192
	04-11 19:48:12.968  5815  5863 D Fabric  : Update app request ID: 8310b867f89166622217f661de62xxxx
	04-11 19:48:12.968  5815  5863 D Fabric  : Result was 204
	04-11 19:48:12.973  5815  5879 D CrashlyticsCore: Initialization marker file created.
	04-11 19:48:12.976  5815  5873 D Fabric  : Falling back to Crashlytics key lookup from Manifest
	04-11 19:48:12.977  5815  5873 D Fabric  : Falling back to Crashlytics key lookup from Strings
	04-11 19:48:12.977  5815  5873 D Fabric  : Generating Crashlytics ApiKey from google_app_id in Strings
	04-11 19:48:12.984  5815  5869 D CrashlyticsCore: Registered Firebase Analytics event listener for breadcrumbs: true
	04-11 19:48:12.986  5815  5879 D CrashlyticsCore: Finalizing previously open sessions.
	04-11 19:48:12.993  5815  5879 D CrashlyticsCore: Closing open sessions.
	04-11 19:48:12.994  5815  5879 D CrashlyticsCore: Closing session: 5CAF28E302B3-XXXX-YYYY-47070E28DA82
	04-11 19:48:12.994  5815  5879 D CrashlyticsCore: Collecting session parts for ID 5CAF28E302B3-XXXX-YYYY-47070E28DA82
	04-11 19:48:12.994  5815  5879 D CrashlyticsCore: Session 5CAF28E302B3-XXXX-YYYY-47070E28DA82 has fatal exception: false
	04-11 19:48:12.995  5815  5879 D CrashlyticsCore: Session 5CAF28E302B3-XXXX-YYYY-47070E28DA82 has non-fatal exceptions: false
	04-11 19:48:12.995  5815  5879 D CrashlyticsCore: No events present for session ID 5CAF28E302B3-XXXX-YYYY-47070E28DA82
	04-11 19:48:12.997  5815  5879 D CrashlyticsCore: Removing session part files for ID 5CAF28E302B3-XXXX-YYYY-47070E28DA82
	04-11 19:48:13.008  5815  5879 D CrashlyticsCore: Closed all previously open sessions
	04-11 19:48:13.018  5815  5879 D CrashlyticsCore: Initialization marker file removed: true
	04-11 19:48:13.018  5815  5973 D CrashlyticsCore: Starting report processing in 1.0 second(s)...
	04-11 19:48:14.057  5815  5973 D CrashlyticsCore: Checking for crash reports...
	04-11 19:48:14.059  5815  5973 D CrashlyticsCore: No reports found.

And, according to https://github.com/flutter/plugins/blob/master/packages/firebase_crashlytics/example/lib/main.dart I can verify by manually throwing error:

    throw StateError('Uncaught error thrown by app.');

(I've set `enableInDevMode` to `true` as well).

The error is indeed thrown, as shown in Android Studio "Run" panel:

	E/flutter ( 5815): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Uncaught error thrown by app.
	E/flutter ( 5815): #0      SettingsRoute._login (package:app/routes/SettingsRoute.dart:61:3)
	E/flutter ( 5815): <asynchronous suspension>
	E/flutter ( 5815): #1      SettingsRoute.build.<anonymous closure> (package:app/routes/SettingsRoute.dart:47:32)
	E/flutter ( 5815): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)

But my dashboard ( https://console.firebase.google.com/u/0/project/MYPROJECT/crashlytics/app/android:com.myapp/issues?state=open&time=last-seven-days&type=all ) says my app is 100% error-free.

And ABD log doesn't show anything.

What did I miss?

EDIT: Flutter doctor result:

[✓] Flutter (Channel master, v1.4.11-pre.12, on Mac OS X 10.13.6 17G5019, locale en-XX)
    • Flutter version 1.4.11-pre.12 at /java/flutter
    • Framework revision 5e52f5df55 (6 days ago), 2019-04-04 22:48:45 -0400
    • Engine revision 697e541a8d
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /java/android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /java/android
    • Java binary at: /Applications/Development/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Development/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Pixel 2 XL • 709KPRW0070366 • android-arm64 • Android 9 (API 28)

**Comment by ened** [comment]
The crashes take a while to appear. Did you wait for at least 8 hours?

**Comment by wiradikusuma** [comment]
I just checked Crashlytics, still crash-free (during normal days, I should be happy lol).

Do note that there's nothing in the ADB log as well (after enabling debugging for Crashlytics).

**Comment by jmeberst** [comment]
Did you ever see the crashes appear? I'm having this same issue, but it hasn't been 8 hours yet.

**Comment by pavel-ismailov** [comment]
@wiradikusuma 

Probably reason is that plugin treat all crashes as non-fatal. so you need to turn off `Crashes` in filter.

`Filter -> Event type -> Crashes / Non fatal`

**Comment by kentcb** [comment]
Arrived here with similar problems and am completely confounded as to what I should be expecting from this plugin. According to [this](firebase_crashlytics), the plugin doesn't even support crash reports but instead is supposed to log analytics events (I guess `app_exception` from what I've found elsewhere but who knows). If that's the case, it will always say the app is crash-free, no?

But for me, _nothing_ is occurring, despite the debug output suggesting that it has. There's no crash report and no event logged. I've waited a long time (well over 8 hours) already for _anything_ to appear and haven't seen squat yet.

**Comment by kentcb** [comment]
I just ran my app up again and I see four lines like this:

```
I/CrashlyticsCore(11943): Crashlytics report upload complete: 5CD3A7B40320-0001-2CD0-11EFE21375F1
```

That aligns with my final four attempts to get this working last night.

I refreshed Firebase Crashlytics view and, lo and behold, it finally shows me _something_ other than the setup instructions that appear when no crashes have been logged. I switched my filter and can see the non-fatal crashes.

**22 of them!**

So the 18 other crashes I pushed through yesterday and the day before? They weren't visible to me for whatever reason. Whenever I viewed the Crashlytics tab, it would always just show me the instructions for setting up Crashlytics like this:

![image](https://user-images.githubusercontent.com/1901832/57493060-c5f9ef00-7306-11e9-87eb-1bfe95659f05.png)

I am not sure why this is so finicky. Why those 18 other crashes never appeared until now is baffling.

**Comment by caroline171** [comment]
I am having the same problem, have been developing for a month now no crashes appear
![Screen Shot 2019-05-30 at 10 47 28 AM](https://user-images.githubusercontent.com/21244418/58620835-5608d400-82c8-11e9-9aee-e11222064ae9.png)

**Comment by richie-south** [comment]
@caroline171 I'm having the exakt same problem :( Even in the overview page for firebase it says crashes are registered but i cannot se them in the crashlytics page :( 

_firebase overview page_
<img width="1014" alt="Screenshot 2019-05-30 at 22 13 04" src="https://user-images.githubusercontent.com/8655479/58661476-50db7180-8328-11e9-8ae6-8c4672f4bb68.png">

_crashlytics page_
<img width="897" alt="Screenshot 2019-05-30 at 22 13 42" src="https://user-images.githubusercontent.com/8655479/58661489-5769e900-8328-11e9-9950-d18417de03f6.png">

**Comment by nimish17** [comment]
CrashlyticsCore.getInstance().crash()

Result : (Not getting crash report, check my logs)


2019-06-26 16:56:28.783 31789-31789/com.app.ulvms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.ulvms, PID: 31789
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
        at com.crashlytics.android.core.CrashTest.indexOutOfBounds(CrashTest.java:30)
        at com.crashlytics.android.core.CrashlyticsCore.crash(CrashlyticsCore.java:635)
        at com.app.ulvms.home.VentureCardFragment$onViewCreated$3.onClick(VentureCardFragment.kt:96)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-06-26 16:56:28.783 31789-31789/com.app.ulvms D/CrashlyticsCore: Crashlytics is handling uncaught exception "java.lang.ArrayIndexOutOfBoundsException: length=2; index=10" from thread main
2019-06-26 16:56:28.787 31789-31825/com.app.ulvms E/CrashlyticsCore: Tried to write a fatal exception while no session was open.
2019-06-26 16:56:28.787 31789-31825/com.app.ulvms D/CrashlyticsCore: Logging Crashlytics event to Firebase
2019-06-26 16:56:28.789 31789-31825/com.app.ulvms D/CrashlyticsCore: No open sessions to be closed.
2019-06-26 16:56:28.790 31789-31825/com.app.ulvms D/CrashlyticsCore: Opening a new session with ID 5D1356640315-0002-7C2D-0C1FE6FDD584
2019-06-26 16:56:28.796 31789-31789/com.app.ulvms D/CrashlyticsCore: Crashlytics completed exception processing. Invoking default exception handler.

**Comment by braindamagedman** [comment]
Faced same problem. I put logging inside
```
 FlutterError.onError = (FlutterErrorDetails details) {
    Crashlytics.instance.onError(details);
  };
```
and found - this function does not called.

After i moved `Crashlytics.instance.crash();` inside my Application's build() function and got:
`I/flutter (15201): Error reported to Crashlytics.`

I think we should put crash() call somewhere after runApp() call to get all works.

**Comment by PatrickKuijpers** [comment]
Same problem, though iOS only, Android works fine!

Flutter specific initialisation performed as described in the docs, and set forceCrash to true:
`await FlutterCrashlytics().reportCrash(error, stackTrace, forceCrash: false);`
Calling this method to trigger a non-fatal:
```
FlutterCrashlytics crashlytics = FlutterCrashlytics();
// crashlytics passed through a few StatefulWidgets

var testException = new Exception("TestNonFatalException");
crashlytics.logException(testException, null);
```
(is a null stacktrace fine? I expect this to be an optional cause for the exception, docs for this might be a little more extensive)

In the docs I didn't see a test-crash like `crashlytics.crash();` as in the native Crashlytics implementation, so I simply throw an exception like this: `throw new Exception("TestCrash");`

I seem to get a little further than most comments above (not sure how): I don't see the 'Set up Crashlytics' page anymore, as if a crash was reported (and I waited several days already). The view on the top-left shows there was a crash reported (not crash free), but the list below is empty.
<img width="1418" alt="Screenshot 2019-06-28 at 10 10 24" src="https://user-images.githubusercontent.com/4254366/60327883-5a8ae000-998d-11e9-8d02-1f3a4e491051.png">
This was my Debug configuration which I tested yesterday. I also tested the Release configuration and triggered fatal & non-fatals several times on at least 2 different days, but here's even less results:
<img width="1409" alt="Screenshot 2019-06-28 at 10 21 51" src="https://user-images.githubusercontent.com/4254366/60328443-95414800-998e-11e9-8e73-207ef8af6d52.png">

**Comment by hffmnn** [comment]
@PatrickKuijpers you are talking about another [Crashlytics plugin](https://github.com/kiwi-bop/flutter_crashlytics), not the one in this repository. At least that's what I see when looking at you code snippets.

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by RikNorakomi** [comment]
Getting Crashlytics up and running is one big mystery. I wish we could go back to Fabric :(

**Comment by anticafe** [comment]
First time integrate Firebase Crashlytics I also face the same issue: although there is crash in Android Studio logcat, but no crash report in Firebase Crashlytics dashboard (I wait for more than 3 hours). Then, I double check Flutter source code and realize forgot to invoke this method at the beginning of app:
```
runZoned<Future<void>>(() async {
    _runMyApp();
  }, onError: Crashlytics.instance.recordError);
```

After adding such method, then crash report is uploaded into server instantly:
```
I/flutter (25849): Flutter error caught by Crashlytics plugin:
I/flutter (25849): Error reported to Crashlytics.
I/flutter (25849): Flutter error caught by Crashlytics plugin:
I/flutter (25849): Error reported to Crashlytics.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following StateError was thrown building EasyLocalizationProvider:
Bad state: Error thrown by Crashlytics plugin

User-created ancestor of the error-causing widget was: 
  EasyLocalization file:///xxx.../lib/screens/launcher/run_app.dart:64:14
When the exception was thrown, this was the stack: 
#0      Crashlytics.crash (package:firebase_crashlytics/src/firebase_crashlytics.dart:50:5)
#1      _MyAppState.initState (package:xxx/screens/launcher/my_app.dart:34:26)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
I/System.out(25849): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(25849): (HTTPLog)-Static: isSBSettingEnabled false
I/CrashlyticsCore(25849): Crashlytics report upload complete: 5DA0319D00C0-0001-5E3B-B948243A0CC0
```

If you see this status (`Crashlytics report upload complete`) then it's successful.

**Comment by kroikie** [comment]
@wiradikusuma

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1147. Any further collaboration will be done there.

**Comment by schultz9999** [comment]
> @wiradikusuma
> 
> Probably reason is that plugin treat all crashes as non-fatal. so you need to turn off `Crashes` in filter.
> 
> `Filter -> Event type -> Crashes / Non fatal`

You got to be kidding me :) Thank you - saved my day. The app is all read, the console full of bad things and yet saw nothing in Dash. Such a trivial thing helped.
