### ISSUE TITLE
textCapitalization not working as expected in TextField and TextFormField. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#30914]
### Minimal code to reproduce. 

```
void main() => runApp(MaterialApp(home: HomePage()));

class HomePage extends StatelessWidget {
  Widget build(context) {
    return Scaffold(
      body: Container(
        alignment: Alignment.bottomCenter,
        margin: EdgeInsets.symmetric(horizontal: 24, vertical: 8),
        child: TextFormField(
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(hintText: "Enter email"),
        ),
      ),
    );
  }
}
```

### Information
As you can see when a user presses space, the text becomes capital. It should stick to small letters. 

### Video recording
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40364434/55960039-99ac6d80-5c89-11e9-8eb6-1685d46bf6f8.gif)

### Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.13, on Mac OS X 10.14 18A389, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by justinmc** [comment]
It looks like the capitalization you are showing is just the system keyboard trying to intelligently capitalize a proper noun.  Flutter is behaving as it should, which is to show a lowercase keyboard since the default `textCapitalization` is `none`.

You could create an input that only accepts lowercase letters though, if that's what you want.  Look at [WhitelistingTextInputFormatter](https://docs.flutter.io/flutter/services/WhitelistingTextInputFormatter-class.html) and TextField's [inputFormatters](https://docs.flutter.io/flutter/material/TextField/inputFormatters.html) property.

**Comment by chornbe** [comment]
Perhaps this could be reopened...? When I have two text fields on a screen, one with textCapitalization.none and the next with .sentences, switching between the two text fields doesn't change the keyboard appearance, or the upper- / lower- of the first letter of a sentence. 

Using:
```
          TextField(
            controller: tc,
            decoration: InputDecoration(
              hintText: "Name of your medication",
            ),
            onEditingComplete: (){
              FocusScope.of(context).requestFocus(new FocusNode());
            },
            textCapitalization: TextCapitalization.none,
            autocorrect: true,
            keyboardType: TextInputType.text,
          ),

```
          TextField(
            controller: tcd,
            decoration: InputDecoration(
              hintText: "Describe the medication",
            ),
            maxLines: 2,
            textCapitalization: TextCapitalization.sentences,
            autocorrect: true,
            keyboardType: TextInputType.text,
          ),

The cap works if I tap into the second field first, but doesn't reset when I go to the first field, and vice-versa starting at first field.

![2019-08-04 21 29 47](https://user-images.githubusercontent.com/7502201/62432679-119e1800-b6ff-11e9-8d9a-6f4e72894786.gif)

**Comment by chornbe** [comment]
Actually, I'll create a new issue. Thanks.

**Comment by justinmc** [comment]
@chornbe Can you link the new issue here when you've created it?

**Comment by chornbe** [comment]
Ah, yes. Apologies:

https://github.com/flutter/flutter/issues/37613

**Comment by lane-faison** [comment]
`TextInputType.name` conflicts with `TextCapitalization.[any auto-capitalization choice]`. If this is how your input field is setup, try removing your `TextInputType.name`, allowing it to default to `TextInputType.text`. This should fix your issue.

Docs:
```
/// Optimized for a person's name.
  ///
  /// On iOS, requests the
  /// [UIKeyboardType.namePhonePad](https://developer.apple.com/documentation/uikit/uikeyboardtype/namephonepad)
  /// keyboard, a keyboard optimized for entering a person’s name or phone number.
  /// Does not support auto-capitalization.
  ///
  /// On Android, requests a keyboard optimized for
  /// [TYPE_TEXT_VARIATION_PERSON_NAME](https://developer.android.com/reference/android/text/InputType#TYPE_TEXT_VARIATION_PERSON_NAME).
  static const TextInputType name = TextInputType._(8);
```
