### ISSUE TITLE
Swipe Items to Dismiss isn't as animated/smooth as other examples?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3092]
I was looking at the gallery's Swipe Items to Dismiss, as well as Gmail's and Inbox's similar mechanism.

Gmail: https://dl.dropboxusercontent.com/u/316685/video7.mp4
Inbox: https://dl.dropboxusercontent.com/u/316685/video6.mp4
Flutter: https://dl.dropboxusercontent.com/u/316685/video8.mp4

It appears that, compared to Gmail and Inbox, that Flutter's animation to move the item out and to the right is very fast (almost abrupt). Also, the animation to narrow the remaining purple bar, and then the animation to hide the remaining purple bar, is so fast, it's almost as if it's not animated. It seems to be like "next frame, narrow the purple bar; pause; next frame eliminate the purple bar".

In Gmail, it appears (but I can't prove) that there is some easing function on the animation of the item. It appears to slow slightly as it's animated out. It leaves behind words (not an icon), and the user can swipe that away. Also, if you swipe away two emails, the previously deleted email's row is animated out (instead of abruptly removed). Things appear a bit smoother overall.

In Inbox, the swipe out seems as fast as Flutter's. The difference, however, is how the remaining green bar is animated. In Inbox, the remaining green bar (indicating: archived) smoothly animates away.

Recommendation: in Flutter, we can look to make the purple bar animate in and away more smoothly.

Thanks for taking a look!

**Comment by abarth** [comment]
This might just be jank in the shrink animation, which will be improved by my work on https://github.com/flutter/flutter/issues/3075
