### ISSUE TITLE
Translate the documentation into Korean

### ISSUE THREAD

**Issue by sziru** [flutter/flutter#30939]
Hi, I'm interested in Flutter. I would like to translate the documentation into Korean. What I imagine is that users can choose a language with a parameter (hl=ko) as Google's documentation pages work. Can you give me a guide?

**Comment by sfshaza2** [comment]
Hi, @sziru! That would be amazing!  Are you talking about the API docs? We currently don't have infrastructure for that. (We currently don't have infrastructure for the flutter.dev docs either, but I want to be clear as they docs have very different processes.)

**Comment by kf6gpe** [comment]
Hi! Thanks! Are you still interested in doing this? There'd be two steps to it --- one would be updating the code that hosts the API documentation, and then of course the translation.

I'm adding some labels so that the team can think about the infrastructure necessary to support this.

**Comment by Luccasoli** [comment]
Hi @sziru, it would be good idea if this issue was renamed to something like "Translate the documentation to multiple idioms", I would love to translate into portuguese! 😄

**Comment by goderbauer** [comment]
I don't think we actually have a way of maintaining our docs in multiple languages.
