### ISSUE TITLE
pod lib lint error when  flutter product into existing iOS project 

### ISSUE THREAD

**Issue by 463292462** [flutter/flutter#30949]
Export flutter compilation product, integrated into existing iOS project in the form of private pod, error when doing pod lib lint SYDFlutterSDK.podspec --allow-warnings --verbose
 
 Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_FlutterIosPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    ** BUILD FAILED **

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
