### ISSUE TITLE
Why fromJson & toJson instead of fromMap & toMap

### ISSUE THREAD

**Issue by ozum** [flutter/flutter#30956]
Hi,

I'm new to Dart and Flutter, and if this is not right place to ask, sorry.

I see that in official flutter docs and `json_serializable` docs, methods and function converting from/to Dart maps are named as `xyzFromJson` and `xyzToJson`, even they require encode/decode to actual Json string before/after.

I was planning to name my methods `xyzFromMap` and `xyzToMap`, but I see in majority of examples and generators here and there follow `fromJson`/`toJson` convention. Nothing prevents me naming as I wish, but I wonder is there any particular reason for that naming?

Thanks,

See: https://flutter.dev/docs/development/data-and-backend/json and https://pub.dartlang.org/packages/json_serializable

**Comment by huangyanxiong01** [comment]
+1

**Comment by jonahwilliams** [comment]
It's not quite fromMap/toMap, as that would imply any `Map<K, V>` whereas `fromJSON` implies that there can only be string keys for the map and that it can only contain JSON serializable objects.

**Comment by iapicca** [comment]
Hi @ozum 
for issue on [json_serializable](https://pub.dev/packages/json_serializable)
please refer on the dedicated [github](https://github.com/dart-lang/json_serializable/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by LucioPelinson** [comment]
+1
