### ISSUE TITLE
[webview_flutter] WebView vs Talkback

### ISSUE THREAD

**Issue by laurent-humbert** [flutter/flutter#30950]
Hi there,

On Android, Talkback doesn't seem to work at all with webviews (can't say for iOS as I don't generate builds for that platform). 

I tried with the webview_flutter plugin and also the flutter_inappbrowser plugin by Lorenzo Pichilli.

Steps to reproduce:

- Activate Talkback
- Launch the webview_flutter example app
- Try to tap on web page elements, nothing happens.

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E2034, locale en-GB)
    • Flutter version 1.2.1 at /Users/lh/FlutterSDK/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • LLD L31 • FPMNW18A24020056 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by jonahwilliams** [comment]
I believe that per https://github.com/flutter/flutter/issues/19418, this is working in newer versions of flutter, but these have not percolated through to the stable branch yet.
