### ISSUE TITLE
 InkWell widget does not dismiss on iOS 12.2 when long press

### ISSUE THREAD

**Issue by fengqiangboy** [flutter/flutter#30960]
## Steps to Reproduce

1. add Drawer widget
2. add Drawer Item to Drawer
3. run app on iOS
4. long press Drawer Item

## Bug Screen recording
[https://youtu.be/-QkmNP67oJg](https://youtu.be/-QkmNP67oJg)

## Analyzing
```
Analyzing ccell_flutter...                                              

   info • The value of the local variable 'db' isn't used • lib/db/provider/device_info_db_provider.dart:45:9 • unused_local_variable
   info • The method '_buildNameTextFiled' isn't used • lib/page/mode/mode_edit_page.dart:49:10 • unused_element
   info • The function '_addDeviceBindLoaded' isn't used • lib/redux/device_bind_redux.dart:27:27 • unused_element
   info • Avoid empty statements • lib/widget/double_button.dart:61:5 • empty_statements
   info • Dead code • lib/widget/double_button.dart:61:5 • dead_code
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/widget_test.dart:9:8 • unused_import
   info • Unused import: 'package:ccell_flutter/main.dart' • test/widget_test.dart:11:8 • unused_import

8 issues found. (ran in 9.3s)
```

```
[✓] Flutter (Channel dev, v1.4.18, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.4.18 at /usr/local/var/flutter/1.0.0
    • Framework revision 8bea3fb2eb (14 hours ago), 2019-04-11 13:11:22 -0700
    • Engine revision 72986c39ea
    • Dart version 2.2.1 (build 2.2.1-dev.3.1 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fengqiang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/fengqiang/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/fengqiang/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Users/fengqiang/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by justinmc** [comment]
Can you provide the code for a minimal app that reproduces this?

**Comment by fengqiangboy** [comment]
I have write a demo, but it can't reproduces this, and it reproduces in my app.

**Comment by fengqiangboy** [comment]
Our app is on app store now.

**Comment by fengqiangboy** [comment]
I found a open source project, it also have this issue

## Demo project

The project is here: [https://github.com/X-Wei/flutter_catalog](https://github.com/X-Wei/flutter_catalog)

## Screen recording
I also take a Screen recording and upload to youtube: [https://youtu.be/KLsq4aeLVEg](https://youtu.be/KLsq4aeLVEg)

**Comment by justinmc** [comment]
Ok I think I see the problem.  If I install that app on iOS and repeatedly tap the "Buttons" item and then swipe the Drawer away, then sometimes my tap on "Buttons" isn't registered and it just shows a long inkwell animation (like a long press) without opening the drawer.

I'm not sure what would cause that, but the next step is to reproduce the bug in a minimal app.  I wasn't having any luck reproducing it just now with a quick try, but it looks like it should be possible.

**Comment by fengqiangboy** [comment]
> Ok I think I see the problem. If I install that app on iOS and repeatedly tap the "Buttons" item and then swipe the Drawer away, then sometimes my tap on "Buttons" isn't registered and it just shows a long inkwell animation (like a long press) without opening the drawer.
> 
> I'm not sure what would cause that, but the next step is to reproduce the bug in a minimal app. I wasn't having any luck reproducing it just now with a quick try, but it looks like it should be possible.

Can you try to fix it by this open source project?

This project have the same problem.

The project is here: [https://github.com/X-Wei/flutter_catalog](https://github.com/X-Wei/flutter_catalog)

**Comment by justinmc** [comment]
I was able to reproduce the problem in Flutter Catalog too!  Looks like it could be caused by tapping the underlying view before the view above has totally been dismissed?  That sounds like a bug in Flutter if so.

**Comment by fengqiangboy** [comment]
> I was able to reproduce the problem in Flutter Catalog too! Looks like it could be caused by tapping the underlying view before the view above has totally been dismissed? That sounds like a bug in Flutter if so.

Some times, it also reproduce in BottomNavigationBar, but not so often. Hope it can give you some ideas.

**Comment by fengqiangboy** [comment]
So, how is it going?

**Comment by justinmc** [comment]
I haven't had time to dig into this yet, but it's definitely something we should get to.  PRs are always welcome if you or anyone else is inspired to try to fix it!

**Comment by TahaTesser** [comment]
Hi @fengqiangboy 
Are you still experiencing this issue?
Thank you

**Comment by TahaTesser** [comment]
Hi @fengqiangboy 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
