### ISSUE TITLE
flutter build apk crashes in android 9

### ISSUE THREAD

**Issue by 0-php** [flutter/flutter#30961]
flutter 1.2.1 build apk crashes in android 9 
i have S9+ and huawei p20 pro system verdion is android
i use flutter run --release or flutter run --debug is no problem
but i close Developer mode download apk app is crash

this is my build build.Gradle:
`
buildscript {
    ext.kotlin_version = '1.3.21'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
//        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

`

**Comment by 0-php** [comment]
hello?

**Comment by superciccio** [comment]
what's the error in the console ( if you run the app in usb debugging ) ?

**Comment by 0-php** [comment]
@superciccio if i use usb debugging is no problem can run but i download Flash back

**Comment by 0-php** [comment]
fine i fix this bug
how to do:
1.open ~/projectName/android/app/build.gradle
2.add this
    defaultConfig {
        ...
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

3.rebuild

**Comment by saurabhthesuperhero** [comment]
Thank you very much 0-php I love u for this code it works 😍
