### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by YWD** [flutter/flutter#30964]
I'm watching some feature or issues and wander to know is there any schedule about solve issues or implements feature?
I submit an issue ,you've change status or add some tag, but I can't see any 'hope'.
I suggest if you can and something like schedule about the issue?

**Comment by GregorySech** [comment]
Have you looked at [this part of the wiki](https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed)?

**Comment by YWD** [comment]
> Have you looked at [this part of the wiki](https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed)?

Thank you. Maybe I should solve my problem in another way, hah.
