### ISSUE TITLE
Flutter build fails with a gradle exception

### ISSUE THREAD

**Issue by Kennibravo** [flutter/flutter#30971]
Please help flutter apps is not running on my system

> FAILURE: Build failed with an exception.                                                                                                                                                        * Where: Build file 'C:\Users\KenniBRAVO\Documents\flutter projects\kenny\android\build.gradle' line: 24 
> * What went wrong:                                                                             
>  A problem occurred evaluating root project 'android'. 
>  A problem occurred configuring project ':app'.                                                  
>  > Failed to find target with hash string 'android-27' in: C:\Android
> --
> 
> 
>

**Comment by meems1996** [comment]
How did you start your app? Do you have Flutter, Dart, and everything else needed installed and running?

**Comment by christopherfujino** [comment]
@Kennibravo can you share the full logs of the exception, as well as the output of `flutter doctor -v`?

**Comment by jonahwilliams** [comment]
This error will occur if you have a dependency that needs a certain version of the android sdk, but you don't have that downloaded. Ensure you have the correct tools for 27 installed via sdk manager or android studio
