### ISSUE TITLE
Sometime flutter app showing strange 

### ISSUE THREAD

**Issue by namtn** [flutter/flutter#30972]
Sometime my app showing like image below on startup for few seconds, after that its working well.
![A791F7D6-A85C-4790-AE7B-E9162C170669](https://user-images.githubusercontent.com/3005899/56052901-cd1bf480-5d7c-11e9-8da7-9c14e1fcfc9c.png)
Someone can explain to me? My app was build release mode for ios.

**Comment by melvinm99** [comment]
Same for me

**Comment by daniilguit** [comment]
This is old issue (mainly on iOS) when you have Image in background in BoxDecoration. AFAIK this happens when native views integration is enabled and should be gone if disabled.

**Comment by melvinm99** [comment]
@daniilguit do you know what to do in order to avoid it?

**Comment by daniilguit** [comment]
There are bunch of already open tickes about this issue, some containing hacks, like
https://github.com/flutter/flutter/issues/29289

**Comment by melvinm99** [comment]
thank you, I'll see them

**Comment by daniilguit** [comment]
I can confirm this is fixed in 1.4.19

**Comment by vanlooverenkoen** [comment]
This is a skia bug. and fixed on channel master. Changing to channel master results in this issue -> #30840

**Comment by vanlooverenkoen** [comment]
I think this can be closed
