### ISSUE TITLE
There's no way to set debugProfileBuildsEnabled to true

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#30984]
@jonahwilliams  found this issue which makes it impossible to trace which widgets are rebuilt in each frame.

I remembered that there is widgets build tracing in the debug mode a couple months ago so this is likely a recent regression.

Ideally, we should have a command line argument that works across `flutter run` and `flutter drive` (e.g., `--profile`) which would enable such tracing in both debug and profile mode.

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/issues/19349 might be a related issue.

**Comment by liyuqian** [comment]
CC @filiph  who recently tried to trace widget build but failed.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/30867

**Comment by liyuqian** [comment]
@jonahwilliams thanks for the fix! I'd also like to have it work in the profile mode. Sending https://github.com/flutter/flutter/pull/30990 for review.
