### ISSUE TITLE
flutter create, ic_launcher.png, full app icon set

### ISSUE THREAD

**Issue by tedhenry100** [flutter/flutter#30982]
When I create a new Android project with Android Studio, all of the following app icon files are generated

* `cheetah/android/app/src/main/res/drawable/ic_launcher_background.png`
* `cheetah/android/app/src/main/res/drawable-v24/ic_launcher_background.png`
* `cheetah/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.png`
* `cheetah/android/app/src/main/res/mipmap-mdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png`
* `cheetah/android/app/src/main/res/mipmap-hdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png`
* `cheetah/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png`
* `cheetah/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png`
* `cheetah/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png`

and there are two related lines in `app/src/main/AndroidManifest.xml`

    android:icon="@mipmap/ic_launcher"
    android:roundIcon="@mipmap/ic_launcher_round"

Then when I use Android Studio to update app image with a background color, it additionally adds the following files

* `cheetah/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png`
* `cheetah/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png`
* `cheetah/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png`
* `cheetah/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png`
* `cheetah/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png`
* `cheetah/android/app/src/main/res/values/ic_launcher_background.xml`
* `cheetah/android/app/src/main/res/ic_launcher-web.png`

When I create a new Flutter app with `flutter create`, the only app icon files generated are

* `cheetah/android/app/src/main/res/mipmap-mdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-hdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png`
* `cheetah/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png`

and the only line in `android/app/src/main/AndroidManifest.xml` is 

    android:icon="@mipmap/ic_launcher"

I think it would make good sense for `flutter create` to generate the full app icon set as done by Android Studio.

**Comment by tedhenry100** [comment]
It looks like the Flutter app template generates the files that Android Studio would generate if choosing the option "Launcher Icons (Legacy Only)" with one exception. Android studio generates a file `cheetah/android/app/src/main/res/ic_launcher-web.png` but the Flutter app template does not have such a file.

**Comment by escamoteur** [comment]
Check https://pub.dev/packages/flutter_launcher_icons

Please ask questions like this on stackoverflow, we are not able to give individual development support.
