### ISSUE TITLE
TextAlign.justify for rtl languages is not supported

### ISSUE THREAD

**Issue by Khordad36** [flutter/flutter#30986]
### TextAlign.justify for rtl languages 

TextAlign.justify justify the text left, even in `TextDirection.rtl`. 

Code:
`Text(
            text,
            textDirection: TextDirection.rtl,
            textAlign: TextAlign.justify,
          )`

Snapshot:
![flutter_01](https://user-images.githubusercontent.com/34609014/56069156-ef227080-5d96-11e9-98a6-1fbc639bc604.png)

`
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
`

**Comment by SahandAkbarzadeh** [comment]
@Khordad36 i created a small lib as a **temporary solution** you can use it for now til flutter team resolves the issue :

https://github.com/SahandAkbarzadeh/flutter_text_justify_rtl

**Comment by OsamaAbbas** [comment]
This issue too should be closed. Refer to: https://github.com/flutter/flutter/issues/28700#issuecomment-527681906
