### ISSUE TITLE
FutureBuilder hangs the whole UI even when using an Isolate

### ISSUE THREAD

**Issue by devnoname120** [flutter/flutter#30987]
## Steps to Reproduce

1. Create a complex and nested `Widget` that takes a significant time to build (~100 widgets, with ~10 nesting levels).
2. Use an `Isolate` through the `compute` function in order to build it:

```dart
FutureBuilder(
            future: compute<int, Widget>(
                buildComments, this.storyId),
            builder: (BuildContext context, AsyncSnapshot snapshot) {
              switch (snapshot.connectionState) {
                case ConnectionState.none:
                case ConnectionState.active:
                case ConnectionState.waiting:
                  return LinearProgressIndicator();
                case ConnectionState.done:
                  if (snapshot.hasError) {
                    final ArgumentError myError = snapshot.error;
                    return Text('Error: ${myError.message}');
                  } else {
                    final Widget comments = snapshot.data;

                    return comments;
                  }
              }
            },
          )
```
Note that the prototype of the function is `Future<Widget> buildComments(int storyId) async`, so [the future should be executed inside the isolate](https://github.com/flutter/flutter/pull/30275).

3. The linear progress indicator will hang for a visible amount of time.

More information here: https://stackoverflow.com/q/55632971/3634271

![loading_bar_hang](https://user-images.githubusercontent.com/2824100/56069982-eb3a2280-5d85-11e9-8fb1-71e8d3f3e844.gif)
*(Sorry for the quality of this GIF but I think that it helps to understand the issue.)*

## Logs
[hacker_news_core.log](https://github.com/flutter/flutter/files/3075362/hacker_news_core.log)

```
C:\Users\noname120\AndroidStudioProjects\hacker_news_core>flutter analyze
Analyzing hacker_news_core...
No issues found! (ran in 3.7s)
```

<details><summary>Output of `flutter doctor -v`</summary>
<p>

```
C:\Users\noname120\AndroidStudioProjects\hacker_news_core>flutter doctor -v
[√] Flutter (Channel master, v1.4.11-pre.34, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
    • Flutter version 1.4.11-pre.34 at C:\flutter
    • Framework revision 0b8403b61c (5 days ago), 2019-04-07 21:29:32 -0700
    • Engine revision ff1bcdc009
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\noname120\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • ZTE A2017G • 16246042 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 2 categories.
```

</p>
</details>

**Comment by dnfield** [comment]
`dart:ui` is only available on the main isolate.  This almost certainly will never work.

You could use a separate isolate to fetch your network data, but you should be using other strategies if you want to defer building parts of your widget tree (like using a `ListView.builder`).

**Comment by dnfield** [comment]
Please feel free to open a new issue if you're finding bugs in the framework that are leading to slow rendering or building, or if there's something where you can't lazily build these things.

**Comment by devnoname120** [comment]
Thank you for your answer. From my understanding, `ListView.builder()` is meant for linear arrays of widgets.
However here the comments are nested widgets. What would be a good way to make it work nonetheless?

I suppose that I could flatten my nested comments so that they are all at the top level with each a custom padding corresponding to their level. But then I'm not sure how I could collapse comment trees, and also it feels hackish so I'm not sure it's the right way to go.

**Comment by devnoname120** [comment]
Side note: it would be helpful if flutter could throw a runtime warning when `UI` is used outside the main isolate. (I suppose it's hard to do it in the analysis).

**Comment by dnfield** [comment]
Trees are a bit harder than lists. It'd be really interesting to come up with a Tree widget that could use slivers and lazy building like a list.  IF there isn't an open bug for that it may be worth opening one, although I'm not sure when anyone would get to it - it'd also be great to write ap ackage for it if possible.

I'm not sure if we can really detect what isolate you're in well enough to do that right now, but it's not a bad idea.
