### ISSUE TITLE
“Invalid Envelope” errors in Firebase Cloud Functions

### ISSUE THREAD

**Issue by yamauchieduardo** [flutter/flutter#30994]
Sometimes the response of callable CloudFunctions cloud_functions 0.1.2+1 throws CloudFunctionGenericException with "Invalid Envelope" message.

This seems to happen for no specific reason, and nothing is logged to the Firebase Cloud Function Logs.

This occours rarely (once each 25 times approx)  and more frequently when a map is returned, but breaks the app logic.

I know this problem since 0.0.5 version.

Why this is happening and how to fix it?

**Comment by UnnikrishnanBhargavakurup** [comment]
For me this is happening every time don't know how to fix this.

**Comment by shmi89** [comment]
I was having the same issue and actually found out the cause just by setting a breakpoint in the decodeEnvelope method, where the exception occurred, and reading the error message value from debugger.

The error said: `keys must be Strings`, so I changed data object from `{ key: value }` to `{ 'key': value }` and that fixed the issue for me!

Later I found out the Map was actually `Map<Object, Object>` and not `Map<String, Object>`, which is since I didn't specify the type explicitly, but let Dart compiler infer it.

@UnnikrishnanBhargavakurup - not sure if it helps, but this is the way calls worked for me: `CloudFunctions.instance.getHttpsCallable(functionName: 'name').call(data)`

**Comment by kroikie** [comment]
@yamauchieduardo

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1193. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
thank you @shali3 ! @yamauchieduardo did you solve the issue?

**Comment by yamauchieduardo** [comment]
The problems don't appear more. I'm updating the project cloud_functions versions to ^0.4.1. 

Thanks.

**Comment by Xentraxx** [comment]
Hello everyone. I experience the same behaviour on the current version. 
My code:
`final HttpsCallable callable = CloudFunctions.instance
                      .useFunctionsEmulator(origin: "http://localhost:5001")
                      .getHttpsCallable(
                        functionName: 'helloWorld',
                      );
                  await callable.call(
                    <String, dynamic>{'message': 'hello world!'},
                  );`
I tried it with http://localhost:5001, //localhost:5001 (as suggested), and localhost:5001. Same Outcome.

**Comment by mmanela** [comment]
@Xentraxx @iapicca I am hitting this issue also. 

These are my dependencies from pubspec.yaml
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^6.0.0
  firebase_storage: ^4.0.0
  cloud_functions: ^0.6.0
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.1
  provider: ^4.3.2
  shared_preferences: ^0.5.10
  shared_preferences_web: ^0.1.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  uuid: ^2.2.2
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  equatable: ^1.2.4
  flutter_form_bloc: ^0.19.0```

Should I open a new issue on FirebaseExtended/flutterfire?

**Comment by salvadorbarb1** [comment]
I'm getting this issue too.

This code gets a response from the server
`HttpsCallableResult result = await createPaymentIntent.call({'order':'invalid data'});`

And this one doesn't
`HttpsCallableResult result = await createPaymentIntent.call({'order': order.toMap()});`

**Comment by iapicca** [comment]
@Xentraxx  @salvadorbarb1 
please look at the possible [solution](https://github.com/FirebaseExtended/flutterfire/issues/3593#issuecomment-695815099) offered by @mmanela 
if the issue persists I recommend to open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
