### ISSUE TITLE
Sample code in API docs can require horizontal scrolling to read

### ISSUE THREAD

**Issue by jamesderlin** [flutter/flutter#30992]
The box for sample code in the API documentation isn't wide enough to fit 80 characters, requiring horizontal scrolling.  For example, from https://docs.flutter.io/flutter/painting/ImageProvider-class.html:

![Screenshot from 2019-04-12 16-39-30](https://user-images.githubusercontent.com/17391434/56071218-d76ccd00-5d41-11e9-8e49-d93e55760158.png)

The sample code box seems to be constrained to an unnecessarily narrow width.  It would be nice if it grew wider with the browser window to accommodate the code. (In this particular example, there are lines wider than 80 characters, but the box doesn't even manage to fit 80.)

Making this even worse is that there is no horizontal scrollbar to actually scroll horizontally.

I tried this with Firefox 66.0.3 x64 and with Chrome 73.0.3683.103 x64 on Linux.

**Comment by jamesderlin** [comment]
Oh, I realized that there *is* a horizontal scrollbar... but you need to scroll to the bottom to get to it. >_<

**Comment by shihaohong** [comment]
This is related to https://github.com/dart-lang/dartdoc/issues/1942. Will close out as a duplicate, but thanks for posting!
