### ISSUE TITLE
Flutter reloads the widget when using routes in MaterialApp

### ISSUE THREAD

**Issue by SaeedMasoumi** [flutter/flutter#31006]
**Steps to Reproduce**

1. Create a new project
2. Add a `TextField` to the `_MyHomePageState`
3. Remove `home: MyHomePage()` from `MaterialApp`
4. Define the routes `routes: { '/': (context) => MyHomePage()},`
5. Everytime you click on `TextField`, it reloads the widget.

**Note:** It works fine when you remove `routes` and use `home` instead.

**Sample Project**
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
//      home: MyHomePage(),
      routes: {
        '/': (context) => MyHomePage(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    print("REBUILDING WIDGET");
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              obscureText: true,
              decoration: InputDecoration(
                  hintText: 'Enter your name:'),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Logs**
```
I/flutter: REBUILDING WIDGET
I/flutter: REBUILDING WIDGET
I/flutter: REBUILDING WIDGET
...
```

**flutter analyze**

```
❯ flutter analyze  
Analyzing flutter_app...                                                
No issues found! (ran in 1.4s)
```
**flutter doctor -v**

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/saeed/Library/Flutter/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/saeed/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/saeed/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 3.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215

[!] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM N950F • 988a5b43524938593230 • android-arm64 • Android 9 (API 28)

```

**Comment by kpsroka** [comment]
I can't reproduce this using the latest beta version `v1.4.9-hotfix.1`

**Comment by SaeedMasoumi** [comment]
@kpsroka Are you sure? I switched to the beta channel and face this issue again

**Comment by giandifra** [comment]
I have same problem:

with the routes defined into MaterialApp when tap the TextField and keyboard is showed, all the widget tree is rebuilded. Without routes the problem there isn't.

**Comment by kpsroka** [comment]
@SaeedMasoumi I assume that showing/disappearance of keyboard is the key here, right? Because regular tap on a text field doesn't seem to trigger the problem without keyboard collapse/expansion.

**Comment by kpsroka** [comment]
@SaeedMasoumi You can work around this by assigning `MyHomePage` to a variable, and using it in the code:
```dart
  final MyHomePage myHomePage = MyHomePage();

  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      routes: {
        '/': (context) => myHomePage,
      },
    );
  }
```

Naturally, the difference here is that you don't re-initialize the `MyHomePage()` widget on every call of `routes['/']`, which seems to trigger the rebuild().

I do believe that this is actually working as intended, but possibly the examples should note that this is about to happen when constructing new widget instances in `routes`.

**Comment by radzish** [comment]
I had same issue and I fixed it by defining const constructor for MyHomePage and using it in routes builder.

**Comment by rrousselGit** [comment]
That's not a bug.
The size of the screen change, therefore MaterialApp calls the builder again.

The only reason `home: Foo()` don't get rebuilt is that the widget instance doesn't change.

**Comment by SaeedMasoumi** [comment]
@rrousselGit Thank for the clarification.

**Comment by giandifra** [comment]
Why this behavior there isn't without route?

**Comment by rrousselGit** [comment]
```dart
MaterialApp(
  home: Foo()
)
```

is an alias for:

```dart
Widget home = Foo();

MaterialApp(
  routes: {
    '/' : (_) => home, 
  }
)
```


which is different from:

```dart
MaterialApp(
  routes: {
    '/' : (_) => Foo(), 
  }
)
```

Because the function passed to `routes` can be called more than once.
Keyboard appearance is one of those situations.



Overall this shouldn't change anything for you. Widgets being rebuilt or not is purely an optimization factor. It should never have an impact on your application.

**Comment by MuMiMaNz** [comment]
I have a similar problem with this issue and solve it by passing context to route page

**Comment by PhyoeKo** [comment]
I'm facing the same issue, what is the solution for it?

TextInputField inside Stream widget tree, when I try to type something on textfield..
Sreambuilder is rebuilding. I think when softkeyboard is appear, the state full widget is rebuild.
Anyone please Help Me... :'(
