### ISSUE TITLE
The flutter project path in AndroidStudio contains Chinese characters, resulting in a compilation failure

### ISSUE THREAD

**Issue by dakezuo** [flutter/flutter#31001]
11:02:22.645 499 info flutter.tools [+1088 ms] CocoaPods' output:
11:02:22.645 500 info flutter.tools            ↳
11:02:22.645 501 info flutter.tools [        ]       Preparing
11:02:22.645 502 info flutter.tools 
11:02:22.645 503 info flutter.tools                Analyzing dependencies
11:02:22.645 504 info flutter.tools 
11:02:22.645 505 info flutter.tools                Inspecting targets to integrate
11:02:22.645 506 info flutter.tools                [!] Could not automatically select an Xcode project. Specify one in your Podfile like so:
11:02:22.645 507 info flutter.tools 
11:02:22.645 508 info flutter.tools                    project 'path/to/Project.xcodeproj'
11:02:22.645 509 info flutter.tools 
11:02:22.645 510 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer/target_inspector.rb:77:in `compute_project_path'
11:02:22.645 511 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `each'
11:02:22.645 512 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `group_by'
11:02:22.645 513 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
11:02:22.646 514 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
11:02:22.646 515 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
11:02:22.646 516 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
11:02:22.646 517 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:243:in `analyze'
11:02:22.646 518 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
11:02:22.646 519 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
11:02:22.646 520 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
11:02:22.646 521 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
11:02:22.646 522 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
11:02:22.646 523 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
11:02:22.646 524 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
11:02:22.646 525 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
11:02:22.647 526 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `load'
11:02:22.647 527 info flutter.tools                /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `<main>'
11:02:22.647 528 info flutter.tools 
11:02:22.650 529 info flutter.tools [   +3 ms] Error running pod install
11:02:22.650 530 info flutter.tools [   +2 ms] Error launching application on iPhone Xʀ.

**Comment by dakezuo** [comment]
Update the problem, not because of the Chinese path, but because the project external hard disk, but I have not found how to repair

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
