### ISSUE TITLE
done

### ISSUE THREAD

**Issue by LokeshKarki** [flutter/flutter#31017]
done

**Comment by LokeshKarki** [comment]
I can provide the code.

**Comment by gabrc52** [comment]
Please explain what you were trying to do. Don't just link to your whole project.

Also keep in mind that GitHub issues are for reporting problems in Flutter itself.

**Comment by LokeshKarki** [comment]
> Please explain what you were trying to do. Don't just link to your whole project.
> 
> Also keep in mind that GitHub issues are for reporting problems in Flutter itself.

Sorry, I am new to Github. I was trying to search the database in Cloud Firestore in FIrebase, using the app. I ran this code once when it was not complete and it worked fine, but after I completed the code it started showing these issues.
