### ISSUE TITLE
Remove needsPaint and needsLayout getters from RenderObject

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3101]
From discussion on https://github.com/flutter/flutter/pull/3083, needsPaint and needsLayout suggest end-developer use that would usually be mistaken.

We should remove and deprecate these getters, rewriting any existing framework code that is currently using them.

**Comment by krisgiesing** [comment]
@abarth

**Comment by abarth** [comment]
It looks like MixedViewport uses `needsLayout`.  I'm working on replacing MixedViewport and will remove the call there as part of that work.

`needsPaint` doesn't appear to have many clients and might be easier to remove.

**Comment by krisgiesing** [comment]
Looks like VirtualViewportElement also uses needsLayout in its logic.  Other than that, I see it used in a lot of assertions.

**Comment by krisgiesing** [comment]
```needsPaint``` is now removed.

**Comment by Hixie** [comment]
For the assertions we can just expose debugNeedsLayout and have it only be valid in checked mode.

**Comment by Hixie** [comment]
Actually even better, just expose an "debugAssertNotNeedsLayout" method or getter (we haven't yet settled on a particular pattern and have both currently) which just does:
```
   assert(!needsLayout);
```
...or some such. (Maybe make it a method, so later we can add arguments that end up in a detailed FlutterError message.)
