### ISSUE TITLE
MaxTileWidthGrid should not require columnSpacing and rowSpacing

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#3102]
## Steps to Reproduce

I created a [MaxTileWidthGrid](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/basic.dart#L1488)

```
new MaxTileWidthGrid(
        children: profileWidgets, maxTileWidth: style.Size.settingsWidth);
```

where profile widgets are some other sort of list of widgets.

The problem is that when I run this, I get an error and red screen.

```
/usr/local/google/home/alexfandrianto/Documents/vanadium_root/flutter/packages/flutter/lib/src/rendering/grid.dart': Failed assertion: line 194: 'columnSpacing != null && columnSpacing >= 0.0' is not true.
```

This red screen occurs because of [MaxTileWidthGridDelegate](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/grid.dart#L288) and [GridDelegateWithInOrderChildPlacement](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/grid.dart#L188). The latter contains the failed assertions.

And after setting columnSpacing to 0.0...

```
'/usr/local/google/home/alexfandrianto/Documents/vanadium_root/flutter/packages/flutter/lib/src/rendering/grid.dart': Failed assertion: line 195: 'rowSpacing != null && rowSpacing >= 0.0' is not true.
```

And after setting rowSpacing to 0.0... it works as expected.

```
new MaxTileWidthGrid(
        children: profileWidgets, maxTileWidth: style.Size.settingsWidth, columnSpacing: 0.0, rowSpacing: 0.0);
```

I think the MaxTileWidthGrid should set columnSpacing and rowSpacing to 0.0 by default though, to make the widget easier to use.

## Flutter Doctor

[✓] Flutter (on Linux, channel unknown)
    • Flutter at /usr/local/google/home/alexfandrianto/Documents/vanadium_root/flutter
    • Framework revision 4df24ab (4 days ago), engine revision 3d944e1

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /usr/local/google/home/alexfandrianto/mojo/src/third_party/android_tools/sdk
    • Platform android-23, build-tools 23.0.1
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-117372415-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1

**Comment by abarth** [comment]
Makes sense.  Will do.  Thanks!
