### ISSUE TITLE
I/flutter (25384): RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#2e88a](state: I/flutter (25384): RawGestureDetectorState#69a3d(gestures: <none>, behavior: opaque)):

### ISSUE THREAD

**Issue by jinaldo** [flutter/flutter#31023]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
Hi @jinaldo, when filling an issue please include the information from the issue templates, otherwise we will be unable top help you.

**Comment by jinaldo** [comment]
Thanks for your reply.
I’ve just solved the problems.
If other issues, then I’ll contact to you.
Thank you. jinaldo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
