### ISSUE TITLE
TextSpan gesture recognition not working inside of CustomPainter

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#31038]
## Steps to Reproduce

1. compose a TextSpan then paint it on canvas

```
class NumberPainter extends CustomPainter {
  final bool shouldCalculate;
  final int numbers;
  final TextPainter textPaint;
  var textStyle;

  NumberPainter({this.shouldCalculate = false, this.numbers})
      : textPaint = TextPainter()
          ..textAlign = TextAlign.center
          ..textDirection = TextDirection.ltr,
        textStyle = TextStyle(color: Colors.white, fontSize: 16);

  @override
  void paint(Canvas canvas, Size size) {
    canvas.translate(size.width / 2, size.height / 2);
      textPaint.text = TextSpan(
        text: 'My Text',
        style: textStyle,
        recognizer: TapGestureRecognizer()
          ..onTap = () {
          //TODO: this gesture is not working
            print("onTap");
          },
      );

      textPaint.layout();
      textPaint.paint(
          canvas, Offset(-textPaint.width / 2, -textPaint.height / 2),
      );

  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}
```

2. Tap on the text
3. Note that onTap text is not printed on logCat

**Comment by bimaldave13** [comment]
I am facing the same issue. is there any solution for it.

**Comment by mikhail-tokarev** [comment]
hi @pedromassango 
are you still experiencing the issue with the latest Flutter stable release? 
if so, please provide the output of ""flutter doctor -v""

**Comment by amirtabasi** [comment]
Hi, i have the same issue, but for me the text is in rtl type, and ontap dosent recognize well is some word !

here is my flutter doctor


[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\_Flutter\flutter
    • Framework revision 2d2a1ffec9 (8 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Amir Hosein\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8369

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by manojeeva** [comment]
Same for me

**Comment by IvanPavliuk** [comment]
The save here. Any updates?

**Comment by xerotolerant** [comment]
This problem persists
