### ISSUE TITLE
ListWheelScrollView doesn't work

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#31035]
I saw [this article](https://medium.com/flutter-community/flutter-listview-and-scrollphysics-a-detailed-look-7f0912df2754) and wanna implement ListWheelScrollView in my application.

But I couldn't implement for 2 days.... item doesn't move and only wrapping container move. What is the problem? I also asked [stackoverflow](https://stackoverflow.com/questions/55662581/how-can-i-use-listwheelscrollview-exactly-in-flutter)

Here is my code and gif of problem

```
@override
Widget build(BuildContext context) {

  return BlocBuilder<SearchEvent,SearchState>(
    bloc: widget.searchBloc,
    builder: (context,state){
      if(state.isKeyboardOn){
        return SearchProcessingMessage(message: '영화를 검색해주세요.');
      }
      if(state.isMovieAPICallLoading) {
        return SearchProcessingMessage(message: '영화를 찾고 있습니다...');
      }
      if(state.isMovieAPICallSucceeded && widget.movieList.isEmpty) {
        return SearchProcessingMessage(message: '찾으시는 영화가 없습니다.');
      }
      return Expanded(
        child: ListWheelScrollView(
          controller: _controller,
          physics: FixedExtentScrollPhysics(),
          clipToSize: true,
          itemExtent: 200.0,
          children: widget.movieList.map((movie) => 
            Container(
              color: Colors.red,
              child:SearchMovieForm(
              movie: movie,
              searchBloc: widget.searchBloc,
            ))).toList()
        )
      );
    }
  );
}
```

![untitled](https://user-images.githubusercontent.com/35518072/56094088-18640d80-5f0b-11e9-952f-29a05e09e6bd.gif)

Thanks for your reading...

**Comment by MattGson** [comment]
Exact same problem. Only some child widgets seem to be supported.

**Comment by escamoteur** [comment]
I saw there is an answer on the SO question.

Have you solved the problem?

**Comment by iapicca** [comment]
Hi @baeharam 
Are you still experiencing the issue with the latest stable version of Flutter?
If so, can you please provide your `flutter doctor -v` 
and  a reproducible minimal code sample?
Thank you

**Comment by baeharam** [comment]
@iapicca I'm not working on flutter, so I can't know this problem still exists...
