### ISSUE TITLE
Add support for FieldValue.increment to Firestore bindings

### ISSUE THREAD

**Issue by puf** [flutter/flutter#31034]
## Steps to Reproduce
For context, see: https://stackoverflow.com/q/55675911

Recent Cloud Firestore releases allow atomic increments using the `FieldValue.increment` operator. Trying to use this operator in Flutter:
```
Firestore.instance.document('docRef').updateData({"numberOfDocs": FieldValue.increment(1)});
```
Leads to an error message:

> The method 'increment' isn't defined for the class 'FieldValue'

Which makes sense, as the `FieldValue.increment()` operator has not been implemented yet in [`FieldValue.dart`](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/lib/src/field_value.dart) and the underlying [CloudFirestorePlugin.java](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java#L706-L713).

**Comment by kroikie** [comment]
@puf

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1234. Any further collaboration will be done there.
