### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by lanjiachuan** [flutter/flutter#31040]
I found that the BottomNavigationBar has no badge and  hope  can join it.

**Comment by MeFelixWang** [comment]
You can make it your self with Stack etc. By the way, your title is not so advisable I think.

**Comment by DarrenGoog** [comment]
It is hard to help you with so little to go on. Can you give us a more complete description of the issue? Preferably with a code sample showing the problem or what you are trying to do? And, as @MeFelixWang pointed out the title here is not descriptive enough to be helpful.

**Comment by lanjiachuan** [comment]
I apologize for the unclear title. I have encountered some problems with it. I don't know if I can communicate with you in Chinese. In fact, my English is very bad and my statement is not so clear. I am a Chinese user. I will provide some personal experience and opinions if possible.

**Comment by johnsonmh** [comment]
Hi, this is something that will be added into the `BottomNavigationBar` widget at some point. Follow https://github.com/flutter/flutter/issues/31209 for updates.

In the mean time, see this stackoverflow question for how to implement it yourself: 

https://stackoverflow.com/questions/45155104/displaying-notification-badge-on-bottomnavigationbars-icon
