### ISSUE TITLE
Slider label ballon lays out off screen when the Slider is near the top of the screen

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#31042]
![flutter_02](https://user-images.githubusercontent.com/15253456/56106367-9f0df000-5ef5-11e9-94b0-e06ae17d4ebc.png)

**Comment by clocksmith** [comment]
There are a couple avenues here. The simplest would be to say to position the slider lower. Another way to do this would be to change the intrinsic height of the slider to include the value indicator when it has one, so that the extra spacing is automatic.

The other thing that can be done is to override the valueIndicatorShape and flip it to the bottom. We could also provide a flag for valueIndicatorPosition that does this automatically.

**Comment by tvolkert** [comment]
I think providing a flag for valueIndicatorPosition (an enum) probably makes the most sense.

**Comment by bhumkong** [comment]
I also have this problem.
In my app there is a ListView with a slider in each element.
Tried mitigating it by adding a container above the ListView. But I ran into the following issue: when my ListView contains enough elements to be scrollable, slider label ballon still gets under the container. If ListView is not scrollable, it works fine.

![Screenshot_20191120-203219](https://user-images.githubusercontent.com/13270137/69262834-3ac2b580-0bd5-11ea-9f7a-9d80714f3233.png)
![Screenshot_20191120-203246](https://user-images.githubusercontent.com/13270137/69262835-3ac2b580-0bd5-11ea-95b9-b06154731153.png)

Could someone provide code for a workaround until it's fixed?

**Comment by funkju** [comment]
I'm seeing this issue as well.

```flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (5 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

**Comment by Mravuri96** [comment]
Having the same issue

![](https://media.giphy.com/media/WP3P3OM6VHfYy7NT2V/giphy.gif)
**Demo and Source Code**
https://dartpad.dev/6e359f6c0321610cb44302309dc27cd7

**Comment by clocksmith** [comment]
The slider value indicator now draws in the overlay after #52663, so it should no longer get clipped (assuming it actually fits on the screen)
