### ISSUE TITLE
Error while running flutter app in my cmd

### ISSUE THREAD

**Issue by Sudhar4** [flutter/flutter#31046]
Flutter has excited unexceptedly

**Comment by jonahwilliams** [comment]
Hi @Sudhar4, without more information from one of the issue templates (flutter version, error messages/stack trace, err file) we're not going to be able to help you.

**Comment by Sudhar4** [comment]
Ohh kk @jonahwilliams error: 
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
Crash report written to /src/flutter/examples/stocks/flutter_02.log;
please let us know at https://github.com/

**Comment by Sudhar4** [comment]
.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
Crash report written to /src/flutter/examples/stocks/flutter_02.log;
please let us know at https://github.com/

**Comment by Sudhar4** [comment]
Ohh kk @jonahwilliams error:
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
Crash report written to /src/flutter/examples/stocks/flutter_02.log;
please let us know at https://github.com/.....This the error message while iam running flutter run in my windows cmd

**Comment by Sudhar4** [comment]
Ohh kk @jonahwilliams error:
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host lookup: 'clients2.google.com' (OS Error: nodename nor servname provided, or not known, errno = 8)
Crash report written to /src/flutter/examples/stocks/flutter_02.log;
please let us know at https://github.com/.
This the error which I got while running flutter run command in my cmd

**Comment by Sudhar4** [comment]
Ohh kk @jonahwilliams <https://github.com/jonahwilliams> error:
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed
host lookup: 'clients2.google.com' (OS Error: nodename nor servname
provided, or not known, errno = 8)
Crash report written to /src/flutter/examples/stocks/flutter_02.log;
please let us know at https://github.com/
This is my error message while running flutter run command in my cmd
