### ISSUE TITLE
external texture does not support YUV color encoding system on iOS

### ISSUE THREAD

**Issue by yongboQu** [flutter/flutter#31041]
why Flutter engine not support YUV color encoding system, and this would cause more memory usage for video apps.
Also, I found an TODO in the engine source code like this 
// TODO(goderbauer): remove option when skbug.com/7523 is fixed.
This bug has fixed in Dec 1, 2018.
@goderbauer when will Flutter engine  support YUV color encoding system and remove this TODO

**Comment by janiokq** [comment]
support

**Comment by chinmaygarde** [comment]
Just to clarify that the TODO linked in this issue is not related to the format of external textures on iOS. But, I am following up separately on if we can remote that workaround now that the bug is fixed.
