### ISSUE TITLE
Unable to run on android 

### ISSUE THREAD

**Issue by lakhwinderdebut** [flutter/flutter#31047]
[✓] Flutter (Channel master, v1.4.20-pre.2, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 1.4.20-pre.2 at /Users/lakhwinder/Downloads/flutter
    • Framework revision 27b058a414 (2 days ago), 2019-04-12 17:42:25 -0700
    • Engine revision 9aa7c9a48e
    • Dart version 2.2.1 (build 2.2.1-dev.4.2 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lakhwinder/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (2 available)
    • ONEPLUS A5000 • f557a0a6                             • android-arm64 • Android 9 (API 28)

Error shown

Initializing gradle...                                              1.1s
Resolving dependencies...                                           3.4s
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 11s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        12.6s
Gradle task assembleDebug failed with exit code 1

yaml

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: any
  path_provider: ^0.4.1
  shared_preferences: ^0.4.2
  flutter_facebook_login: any
  intl: ^0.15.7
  cached_network_image: ^0.4.2
#  flutter_local_notifications: ^0.3.7
  uuid: ^1.0.3
  webview_flutter: 0.2.0
#  flutter_native_web: ^1.0.1
#  flutter_markdown: ^0.2.0
  flutter_native_timezone: ^1.0.0
  flutter_section_table_view: ^1.0.2
  url_launcher: ^4.0.2
  fluttertoast: ^2.1.2
  encrypt: ^1.0.1
  flarecode:
     path: flarecode
  flutter_local_notifications:
      path: ./flutter_local_notifications-master
  contacts_service:
      path: ./contacts_service-0.1.1
  simple_permissions:
      path: ./simple_permissions-0.1.9
  share: "0.5.3"

  timezone:
       # Need to use git here since there is a bug in the main repository.
       git:
         url: "https://github.com/pinkfish/timezone.git"

**Comment by escamoteur** [comment]
Hi, sorry for the late reply, I would like to ask if you could solve your problem in the meantime?
