### ISSUE TITLE
NoSuchMethodError: The method '>' was called on null on IOS

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#31044]
I found this exception caused by
```
int page = _currentPage > 0 ? _currentPage + 1 : 1
```
_currentPage is a int getter.
a bad news is I can't reproduce it on other simple script.
it can be reproduced on my app (the newest stable and master channel)
perhaps similar to #21628, #21887

**Comment by windrunner414** [comment]
That's my reason

**Comment by ammarmahafeza** [comment]
how did you solve that ?
