### ISSUE TITLE
flutter plugin cannot solve the class refered by bridge-header.h

### ISSUE THREAD

**Issue by shyandsy** [flutter/flutter#31056]
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/5271457/56125547-c3c49f00-5fab-11e9-895e-874d6a5b1985.png)

I wanna use oc bridhge-header file to call the oc method in my plugin implemented by swift 

the building system cannot resolve the class name i refered in bridge-header

are there anyway to use bridge-header in swift plugin code?

**Comment by soleverlee** [comment]
I also have the same problem. it seems that it's much easier to use objective-c instead of swift to implement a plugin, to interact with c or oc.😹

**Comment by soleverlee** [comment]
@shyandsy I got it, it's not needed to add a custom bridge header, there is a xxx-umbrella.h file in Supported Files, just import c header here and you'll be able to call it from swift files.

**Comment by escamoteur** [comment]
Hi, sorry for the late reply, I would like to ask if you could solve your problem in the meantime?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by LiuJQ** [comment]
I wonder how to import objc header files in swift code when I developping flutter plugin  😭

**Comment by iapicca** [comment]
@LiuJQ 
if you need assistance with your code please follow the link `I want help writing my application` in the [new issue menu](https://github.com/flutter/flutter/issues/new/choose)
or, if you are reporting a bug, please open a new issue 
providing your `flutter doctor -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
