### ISSUE TITLE
Laggy animation in TransitionBuilder  ##Navigator.push

### ISSUE THREAD

**Issue by AmolGangadhare** [flutter/flutter#31059]
I'm getting a lag in when `Navigator.push` used with `PageRouteBuilder`. When `SlideTransition` is used it has a little lag when **animation is near to completion**. I referred #16735 but found no concrete solution.

I checked this on Android and iOS this lag can be seen on both.

![animated_builder_lag](https://user-images.githubusercontent.com/33967327/56128315-e7ccb400-5f9c-11e9-9007-291e98b3cf61.gif)

## Steps to Reproduce
```
  Navigator.push(
      context,
      PageRouteBuilder(
          pageBuilder: (BuildContext context, Animation animation,
              Animation secondaryAnimation) {
            return UiCartScreen();
          },
          opaque: true,
          barrierColor: Colors.grey,
          transitionDuration: Duration(milliseconds: 400),
          transitionsBuilder: (BuildContext context,
              Animation<double> animation,
              Animation<double> secondaryAnimation,
              Widget child) {
            return FadeTransition(
              opacity: animation,
              child: SlideTransition(
                position: new Tween<Offset>(
                  begin: const Offset(1.0, 0.0),
                  end: Offset.zero,
                ).animate(animation),
                child: child,
              ),
            );
          }));
```

## Logs
No error logs

## flutter analyze
```
Analyzing flutter_app...                                           
No issues found! (ran in 23.2s)

```
## flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-IN)
• Flutter version 1.2.1 at /Volumes/MyData/Flutter_SDK/flutter
• Framework revision 8661d8a (8 weeks ago), 2019-02-14 19:19:53 -0800
• Engine revision 3757390
• Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/admin/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.2, Build version 10E125
• ios-deploy 1.9.4
• CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 34.0.1
• Dart plugin version 182.5215
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 2.25.0

[✓] Connected device (2 available)
• Moto G 5 Plus • ZY22433CCB • android-arm • Android 8.1.0 (API 27)
• iPhone • 94668ac81f88a784270ca66dbb6c3ae75045de54 • ios • iOS 12.2


```

**Comment by rostopira** [comment]
Is it reproducible in release builds?
I have performance issues with big SVGs on debug, but release builds are smooth
Try `flutter run --release`

**Comment by AmolGangadhare** [comment]
I've checked with the release build, there is a slight improvement but also minor lag persists

**Comment by zurie** [comment]
I am having bad lag as well on Route Animations.  Using default material animations on my routes and when I go from a Detail Route back to the home route, it doesn't even play..  0 frames.  its so slow that it seems flutter just throws it out and says.. well that didn't happen... 

I originally thought my scaffolding was wrong and that my animations weren't playing because of that but I noticed that if i dragged the animation with my finger and let go it played better.

Then I came upon this thread and I tried this animation and its bad.  I tried it at 4000 ms just to really really extend it and you can see a section where the whole app / freezes /skips right as the first frame is about to full cover (say 98% coverage) and then you see the same thing on the way out, the first 2% uncover is super slow.  

I even modified the above animation to just slide.  so were talking a 4 second slide from left to right and i see this choppy "hit" on the app at the same spots.

it makes me wonder if there is a way to do that business logic first and then play the animation, or vice versa.  not sure if thats dispose() or certain areas of the engine that are doing logic / garbage collection, but I am open to any ideas to make the transitions smoother between views.

My main view has a infinite list with Network images / ClipRects / Drop shadows / etc...   but being sold on the 60 FPS game, routing is pretty integral to most all apps, and having slow / choppy transitions really makes the framework look sluggish.

**Comment by elisar4** [comment]
if someone still wondering, I did some workaround on my project to avoid "laggy" start of animation:
```dart
Future<Widget> buildPageAsync() async {
    return Future.microtask(() {
        return HeavyDetailPage();
    });
}
```
How to use this:
```dart
var page = await buildPageAsync();
var route = MaterialPageRoute(builder: (_) => page);
Navigator.push(context, route);
```
^In this case when user clicks a button for transition, there will be very small delay before transition (to build the page), and after this delay animation will start smooth from start. Also flutter --release helps to make animations smooth (compared to debug mode).
After applying this, in debug mode, I have noticed frame build time drop from around 120ms (on animation start) to 17ms, and the animation itself goes on 5-8ms per frame (all the values better in release mode)

**However, I still don't know how to solve small "laggy" animation start on Navigator.pop()**
So, if there is some workaround on that, please leave a message to describe it :)

I did use the code above for very heavy animation and test with release build on slow Android device, and it works perfectly for me. 
//of course, I'm using CustomRouteTransition instead of MaterialPageRoute (this is just a sample code above), basic MaterialPageRoute works fine without any workarounds in my case

**Comment by LeandroMoura3** [comment]
I have this problem too.

A small laggy occurs in end of the transition when the custom route navigator is pushed. The laggy occorus too in the pop of the page, as described.

With more pages, bigger is the laggy.

I use the EnterExitRoute from this tutorial:
https://medium.com/flutter-community/everything-you-need-to-know-about-flutter-page-route-transition-9ef5c1b32823

**Comment by addaedans** [comment]
> if someone still wondering, I did some workaround on my project to avoid "laggy" start of animation:
> 
> ```dart
> Future<Widget> buildPageAsync() async {
>     return Future.microtask(() {
>         return HeavyDetailPage();
>     });
> }
> ```
> 
> How to use this:
> 
> ```dart
> var page = await buildPageAsync();
> var route = MaterialPageRoute(builder: (_) => page);
> Navigator.push(context, route);
> ```
> 
> ^In this case when user clicks a button for transition, there will be very small delay before transition (to build the page), and after this delay animation will start smooth from start. Also flutter --release helps to make animations smooth (compared to debug mode).
> After applying this, in debug mode, I have noticed frame build time drop from around 120ms (on animation start) to 17ms, and the animation itself goes on 5-8ms per frame (all the values better in release mode)
> 
> **However, I still don't know how to solve small "laggy" animation start on Navigator.pop()**
> So, if there is some workaround on that, please leave a message to describe it :)
> 
> I did use the code above for very heavy animation and test with release build on slow Android device, and it works perfectly for me.
> //of course, I'm using CustomRouteTransition instead of MaterialPageRoute (this is just a sample code above), basic MaterialPageRoute works fine without any workarounds in my case

Thanks for this workaround, it works great, but I think it should be a default option, because on my Galaxy J6 then route animation is horrible without this. Hope it will be solved soon because I invest heavily to Flutter in development ;)

**Comment by moda20** [comment]
is there any other way of going from a page to an other because the lag  on the material page route is real.

**Comment by AteqEjaz** [comment]
Same lagging while page transition :(

**Comment by kira1752** [comment]
is there any real solution with this issue? because using Future.microtask() still doesn't solve lag when first time opening Flutter App and doing some page transition (after that transition is become much better but still on END USERS perspective when using my app for the first time this will produce 1 Star review easily :( ).

**Comment by AnisovAleksey** [comment]
Workaround works for me. I hope Flutter team will improve this by default

**Comment by kira1752** [comment]
> Workaround works for me. I hope Flutter team will improve this by default

how to use workaround inside onGenerateRoute?

**Comment by kira1752** [comment]
After through many trials and errors, i find that using **AnimationBuilder** inside transition builder improve animation performance a lots. I don't know if my findings helps improve performance on low end devices because i didn't have any low end devices yet.

**Comment by killmegenius** [comment]
> After through many trials and errors, i find that using **AnimatedBuilder** inside transition builder improve animation performance a lots. 

I wrote method
`void navigatorPush(BuildContext context, Widget page) {
  Navigator.push(
    context,
    PageRouteBuilder(
      pageBuilder: (context, animation, secondaryAnimation) => page,
      transitionsBuilder: (context, animation, secondaryAnimation, child) {
        final begin = Offset(1.0, 0.0);
        final end = Offset.zero;
        final curve = Curves.ease;
        final tween =
            Tween(begin: begin, end: end).chain(CurveTween(curve: curve));

        return SwipeBackDetector(
          child: SlideTransition(
            position: animation.drive(tween),
            child: child,
          ),
        );
      },
    ),
  );
}`

Use like this
`navigatorPush(context, Page2());`

SwipeBackDetector is swipe_back_detector package for enable swipe back gesture

**Comment by darshankawar** [comment]
H @AmolGangadhare,
I tried your code sample on latest stable (1.20.2) using Android 8.1.0 device and didn't notice the lag, unless I missed anything.

[31059.mp4.zip](https://github.com/flutter/flutter/files/5156072/31059.mp4.zip)

<details>
<summary>code sample</summary>

```
return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Tap'),
          onPressed: () {
            Navigator.push(
                context,
                PageRouteBuilder(
                    pageBuilder: (BuildContext context, Animation animation,
                        Animation secondaryAnimation) {
                      return SecondScreen();
                    },
                    opaque: true,
                    barrierColor: Colors.grey,
                    transitionDuration: Duration(milliseconds: 400),
                    transitionsBuilder: (BuildContext context,
                        Animation<double> animation,
                        Animation<double> secondaryAnimation,
                        Widget child) {
                      return FadeTransition(
                        opacity: animation,
                        child: SlideTransition(
                          position: new Tween<Offset>(
                            begin: const Offset(1.0, 0.0),
                            end: Offset.zero,
                          ).animate(animation),
                          child: child,
                        ),
                      );
                    }));
          },
        )
      ),
    );
```

</details>

Can you confirm at your end if you still experience the issue on latest stable or master version ?
Thanks.

**Comment by bgmf** [comment]
For me the default transition lags when I navigate with named routes – I can somehow circumvent this with a variation of the described `async` solution here (I won't go into details, but an artificial delay is involved) and explicitly using `FadeUpwardsPageTransitionsBuilder` in the `pageTransitionsTheme` set up, but still the back animation stutters.   
The app isn't totally unresponsive, but there's a visible lag on many devices – even relatively high end ones (e.g. Huawei Mate 20 Pro 5G & P30 Pro, Samsung S10 5G). 

**`flutter doctor -v`**

```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.20.2 at /home/<...>/tools/flutter
    • Framework revision bbfbf1770c (vor 3 Wochen), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/<...>/tools/android-sdk-linux
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/<...>/tools/android-sdk-linux
    • Java binary at: /home/<...>/tools/ide/jetbrains/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/<...>/tools/ide/jetbrains/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • EVR N29 (mobile) • KVJ5T19708000072 • android-arm64 • Android 10 (API 29)
```

**Comment by 123dma** [comment]
I'm trying to do this. has anyone done?

https://flutter.dev/docs/perf/rendering/shader

**Comment by xiaojielade** [comment]
i have been stucked at this problem for a long time，unfortunately, after searching a lot of answers, still got no perfect solution, and now i postpone the screen data render to the page transition animation end status，then the page transition will be very smooth, however, the page content can only be show after the page transition animation end though the network request has came back while the page transition is going, hope anyone can show a perfect solution,

**Comment by bgmf** [comment]
I will possible try and go the same way @123dma was going. That may at least ease the pain a bit.  
But as @xiaojielade mentioned, we probably need to postpone any "heavy" stuff to some later point, to reduce the stress on the main UI thread. Probably such tasks as fetching data in the background could be done via Isolates?

**Comment by kira1752** [comment]
> i have been stucked at this problem for a long time，unfortunately, after searching a lot of answers, still got no perfect solution, and now i postpone the screen data render to the page transition animation end status，then the page transition will be very smooth, however, the page content can only be show after the page transition animation end though the network request has came back while the page transition is going, hope anyone can show a perfect solution,

Using your suggestion and `Future<Widget>.microstask(Widget())` solution, i decide creating additional `PageLoader()` widget that simply use `FutureBuilder()` that instead listening to **animation end status**, i use the future value of `Future<Widget>.microstask(Widget())` and that work nicely.

**Comment by b3nni97** [comment]
Same problem here

**Comment by winterdl** [comment]
I've got the same issue, the transition from ListView page to Detail page too laggy, the animation of tap in ListTile about 2-3s before display Detail Page.

![listview](https://user-images.githubusercontent.com/302480/101327341-22d1d880-38a1-11eb-9d03-a5487a87e127.gif)

**Comment by Plegizplegiz** [comment]
ma 7.12.2020 klo 10.34 winterdl <notifications@github.com> kirjoitti:
