### ISSUE TITLE
'package:flukit/src/swiper.dart': Failed assertion: line 199 pos 12: 'children.length > 0': is not I/flutter (  465): true.

### ISSUE THREAD

**Issue by luli757304397** [flutter/flutter#31055]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
Hi @luli757304397, it looks like that assertion is coming from https://github.com/flutterchina/flukit ?

It would be better to file an issue with the package maintainers there, thank you!
