### ISSUE TITLE
I/flutter (25140): The following assertion was thrown building Builder(dirty): I/flutter (25140): type 'Future<dynamic>' is not a subtype of type 'Widget'

### ISSUE THREAD

**Issue by Vandana-kanwar** [flutter/flutter#31057]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Vandana-kanwar** [comment]
Restarted application in 4,111ms.
I/flutter (25140): app loaded with init link null 
I/flutter (25140): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25140): The following assertion was thrown building Builder(dirty):
I/flutter (25140): type 'Future<dynamic>' is not a subtype of type 'Widget'
I/flutter (25140): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25140): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25140): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25140):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (25140): When the exception was thrown, this was the stack:
I/flutter (25140): #0      MyApplication.build.<anonymous closure> (package:biz_card_scanner/app.dart:60:29)
I/flutter (25140): #1      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:84:27)
I/flutter (25140): #2      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:655:43)
I/flutter (25140): #3      Builder.build (package:flutter/src/widgets/basic.dart:6035:41)
I/flutter (25140): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (25140): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (25140): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #68     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #80     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #87     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #88     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #90     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (25140): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #93     _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:494:16)
I/flutter (25140): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #99     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #105    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #109    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #115    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #119    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #122    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #128    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #129    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): Loading prifile from cache
I/flutter (25140): contact id 5cb454fb6b0d532ccac4fb1b
I/flutter (25140): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #147    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #148    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #152    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #157    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #158    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #159    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #164    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #165    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #166    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #171    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #172    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #173    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #175    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #176    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #180    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #205    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #208    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (25140): #209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #210    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #212    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #214    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #215    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #216    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #220    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #221    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #223    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #225    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #226    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #227    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #228    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #230    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #232    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #233    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #234    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #235    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #236    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #238    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #239    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #240    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (25140): #241    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #242    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #243    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (25140): #245    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (25140): #246    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (25140): #247    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
I/flutter (25140): #248    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
I/flutter (25140): #249    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (25140): #250    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (25140): #251    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (25140): #252    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (25140): #253    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter (25140): #254    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (25140): #255    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (25140): #256    runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (25140): #257    main (package:biz_card_scanner/main.dart:14:3)
I/flutter (25140): #268    initUniLinks (package:biz_card_scanner/main.dart)
I/flutter (25140): #279    getInitialUri (package:uni_links/uni_links.dart)
I/flutter (25140): #290    getInitialLink (package:uni_links/uni_links.dart)
I/flutter (25140): #301    MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
I/flutter (25140): (elided 54 frames from package dart:async)
I/flutter (25140): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by Butzlabben** [comment]
We need the code, my friend.

**Comment by jonahwilliams** [comment]
hi @Vandana-kanwar, the assertion failure is triggered by MyApplication.build. (package:biz_card_scanner/app.dart:60:29), which looks to be in your application.  For support, please check out one of the channels at flutter.dev/support - thanks!
