### ISSUE TITLE
Switch() does not mimic the native experience

### ISSUE THREAD

**Issue by dmvvilela** [flutter/flutter#31067]
Hey guys, i am using Switch() on my app and there is a problem with it.
It seems that i can only toggle its value by dragging my finger to the right or left.. This should be toggled only by clicking on the switch as the native buttons do.

I am using 1.4.9 hot fix 1 flutter on Mac, but i don't think this matters.

**Comment by jonahwilliams** [comment]
Tapping the switch will toggle it, if the onChanged callback updates the value with setState. From the documentation at https://docs.flutter.dev/flutter/material/Switch-class.html:

> The switch itself does not maintain any state. Instead, when the state of the switch changes, the widget calls the onChanged callback. Most widgets that use a switch will listen for the onChanged callback and rebuild the switch with a new value to update the visual appearance of the switch.

**Comment by dmvvilela** [comment]
Oh i see. I got confused cause dragging works then.. I do not have the back end yet so i did not put a value changing.. Sorry. And Thanks!

**Comment by jonahwilliams** [comment]
No problemo
