### ISSUE TITLE
multiDexEnabled Flashback

### ISSUE THREAD

**Issue by Seifon** [flutter/flutter#31068]
D8: Cannot fit requested classes in a single dex file (# methods: 68017 > 65536)
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.     
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 51s

**Comment by rahulmanthena** [comment]
Add "multiDexEnabled true" to your app level  build.gradle. your build.gradle should look something like this.

file: android/app/src/build.gradle 

android {
     ...
    defaultConfig {
        ...
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        ...
        }
    ...
}

**Comment by Seifon** [comment]
> Add "multiDexEnabled true" to your app level build.gradle. your build.gradle should look something like this.
> 
> file: android/app/src/build.gradle
> 
> android {
> ...
> defaultConfig {
> ...
> minSdkVersion 21
> targetSdkVersion 28
> multiDexEnabled true
> ...
> }
> ...
> }

Already added, the problem still exists

**Comment by yanghengyh** [comment]
@Seifon  Did the problem solve?

**Comment by jonahwilliams** [comment]
Closing as this error is fixed by adding multidex: true
