### ISSUE TITLE
Suggestion: Make fullScreenDialog page in iOS swipeable.

### ISSUE THREAD

**Issue by Butzlabben** [flutter/flutter#31062]
Hi there,

when using normal page routes, either a `MaterialPageRoute` or a `CupertionPageRoute`, you can swipe them away in reverse direction how they flew in on iOS. But when using the `fullScreenDialog` property, you can't do it. Neither from left to right nor from top to bottom. 
It would be way easier to navigate if you could drag it down.

With kind regards
Daniel

**Comment by xster** [comment]
Is there a pattern from standard Xcode iOS you're referencing here? Making it non-swipable is the main intent of fullScreenDialog.

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
