### ISSUE TITLE
problem running my flutter for the first time after installing

### ISSUE THREAD

**Issue by Nzoji** [flutter/flutter#31060]
Launching lib/main.dart on ANSELMO ONE in debug mode...
Initializing gradle...                                                 |
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 318752934b065974)
Initializing gradle...                                                  \ Checking Android licenses is taking an unexpectedly l
Crash report written to C:\Users\Marisa Neto\AndroidStudioProjects\flutter_app\flutter_01.log;

```

**Comment by Butzlabben** [comment]
Please include the log file in `C:\Users\Marisa Neto\AndroidStudioProjects\flutter_app\flutter_01.log;`.
Also, provide some information about your system
