### ISSUE TITLE
Put badges on flutter/plugins README showing issue and PR count for each plugin

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#31078]
The goal would be to make it easy for maintainers/contributors to quickly jump to issues and PRs for a plugin they're interested in. We could also put badges at the top of individual plugin READMEs if it seems like they're useful.

The badges could look like this:

![image](https://user-images.githubusercontent.com/394889/56158208-4df21080-5f76-11e9-99cf-58191e7898cc.png)

I think it should be possible to implement without writing much code, using GitHub API and https://shields.io/

For issues we'd use the plugin labels. For PRs we'd use the PR title.

It might make make more sense to do this somewhere other than the README instead. Feedback welcome.

**Comment by moko256** [comment]
I am generating badges. It looks like:

[![GitHub issues by-label](https://img.shields.io/github/issues/flutter/flutter/p:%20url_launcher)](https://github.com/flutter/flutter/labels/p%3A%20url_launcher) [![GitHub pull requests by-label](https://img.shields.io/github/issues-pr/flutter/plugins/p:%20url_launcher)](https://github.com/flutter/plugins/labels/p%3A%20url_launcher)

Issues:
```md
[![GitHub issues by-label](https://img.shields.io/github/issues/flutter/flutter/p:%20url_launcher)](https://github.com/flutter/flutter/labels/p%3A%20url_launcher)
```

PRs:
```md
[![GitHub pull requests by-label](https://img.shields.io/github/issues-pr/flutter/plugins/p:%20url_launcher)](https://github.com/flutter/plugins/labels/p%3A%20url_launcher)
```


I'll add this in the table in top README.md and each README.md.

**Comment by moko256** [comment]
To align the border, `issues` label in badge would be good.
Some plugin (google_maps_flutter and webview_flutter) has different label in issues and plugin, so in each README.md, `"p: maps" issues` and `"p: google_maps_flutter" pull requests` would be good.
![screenshot of the table](https://user-images.githubusercontent.com/16546008/166250134-a042e8de-4cef-485f-b3d6-3fb99f45f280.png)
