### ISSUE TITLE
[firebase_auth] Need better examples when used with google_sign_in

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#31077]
There are no examples on how to do below 2 things in the firebase_auth plugin.

1. A detailed example for how to listen to the firebase_auth [onAuthStateChanged] stream, especially when signed in using google_sign_in.

2. An example to show how to utilize [signInSilently] in the google_sign_in plugin when using the [firebase_auth] plugin.

**Comment by kroikie** [comment]
@cyanglaz

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1112. Any further collaboration will be done there.
