### ISSUE TITLE
webview_flutter plugin doesn't work when setState is called in onPageFinished function

### ISSUE THREAD

**Issue by ask007learning** [flutter/flutter#31076]
It just shows a blank page when calling setState in onPageFinished function. If I remove setState call, then it works fine.

my code below:
```dart
 void _pageLoadingDone(String value) {
    setState(() {
      _stackToView = 0;
    });
    print(value);
  }

 Widget build(BuildContext context) {
    return WebView(
      key: UniqueKey(),
      javascriptMode: JavascriptMode.unrestricted,
      initialUrl: 'https://google.com',
      onPageFinished: _pageLoadingDone,
    );
}
```

**Comment by iapicca** [comment]
Hi @liyuqian 
Are you still experiencing the issue with the latest stable version of Flutter?
If so, can you please provide your `flutter doctor -v` 
and a reproducible minimal code sample?
Thank you

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
