### ISSUE TITLE
Scroll performance significantly degraded on iPhone X, Xs devices due to irregular input events delivery.

### ISSUE THREAD

**Issue by wemped** [flutter/flutter#31086]
Myself and some others discussing in https://github.com/flutter/flutter/issues/22314 have noticed significant scroll performance issues on iPhone X,Xs devices with scrolling views. 

Anecdotally it seems drag gestures are the main issue, while flings seem slightly better. 
@coreysprague suggested it may be because these devices have a 120hz gesture sample rate (https://www.macworld.com/article/3235709/iphone-x-samples-touch-input-at-120hz-for-faster-smoother-response.html).

Just want to clarify that this does happen even when running in release mode.

## Steps to Reproduce
Here's a tiny sample app where you can reproduce the scroll jitters and frame skips, just grab an iPhone X,Xs and run in release mode.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const padding = EdgeInsets.symmetric(vertical: 10, horizontal: 10);

    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: <Widget>[
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.grey,
            ),
            Container(
              margin: padding,
              height: 200,
              color: Colors.orange,
            ),
          ],
        ),
      ),
    );
  }
}
```

## Logs

No errors in logs w/ `flutter run --verbose`

No issued found w/ `flutter analyze`

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
• Flutter version 1.2.1 at /Users/dwempe/flutter
• Framework revision 8661d8a (8 weeks ago), 2019-02-14 19:19:53 -0800
• Engine revision 3757390
• Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/dwempe/Library/Android/sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
• All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.2, Build version 10E125
• ios-deploy 1.9.4
• CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
• Android Studio at /Applications/Android Studio 2.app/Contents
• Flutter plugin version 34.0.1
• Dart plugin version 182.5215
• Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 2.24.0

[✓] Connected device (2 available)
• Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26)
(emulator)
• _________ iPhone • 00008020-000B25CE0298002E • ios • iOS 12.2
```

**Comment by bobmoff** [comment]
I tried the tiny sample app on my iPhone X and iPhone 5. I can verify that only on the iPhone X there are frequent stutters (lost frames) while drag-scrolling. As soon as I let go of the screen with finger and it only scrolls on inertia, it is fine. There is also an increase of these stutters if I swipe up to app switch on iPhone X and then just taps the app again to resume it, and right when it has been resumed again I start drag scrolling.

**Comment by xster** [comment]
Wild guess but we seem to have seen a similar issue in https://github.com/flutter/flutter/issues/6135 only during touch events. We may need to gate the incoming event flow.

**Comment by liyuqian** [comment]
Thanks to @yunyu 's example app, I reproduced some stutters on iPhone X but not on iPhone 6S. 
Attached is the trace with `--trace-skia` enabled (GPU thread frame time exceeds budget around 26.8s).

[dart-timeline-2019-3-29.json.zip](https://github.com/flutter/flutter/files/3129402/dart-timeline-2019-3-29.json.zip)

Considering that it only happened on iPhoneX but not iPhone6S, I think it's related with the GPU hardware and the OpenGL driver of iPhone X. My hope is that Skia's Metal backend will eventually solve this kind of problem. So far, I'm not sure how Flutter can fix this without Skia's help.

@bsalomon (Skia's GPU lead): can you see something suspicious from the trace? Does Skia currently run tests on iPhone X? I seem to only find iPhone 6/7 on perf.skia.org . I guess as iPhone X gets more market share, such performance issues will become more and more critical. Also note that this performance issue only happened during first launches or app switches. So any performance tests that did a lot of warm up repetitions may not catch it.

**Comment by yunyu** [comment]
@liyuqian Just to note, this performance issue is also noticeable if you hold your finger down while scrolling (it doesn't occur during flings). Not sure if that is a separate issue.

**Comment by tvolkert** [comment]
@yunyu if you're seeing this on the _simulator_, that's a different issue that happens when keeping the finger down on non-Flutter simulator apps too, like the Settings app.

**Comment by yunyu** [comment]
@tvolkert I am seeing this on a physical device with the example app linked previously.

**Comment by msw333** [comment]
The effect is severe on iPhone X and minimal, but still observable, on iPad Pro (2. Gen.). Haven’t tested with other devices yet.

**Comment by bsalomon** [comment]
Sorry for slow response, just got back from vacation. I took a look at the trace. There is a crazy amount of time being spent in GrRenderTargetOpList::onExecute (31ms in one frame) but there isn't enough tracing detail to know what is actually happening in there. We'd need more detailed tracing events to get a better idea of where the time is going.

Side note: it's probably not too early to start trying to integrate the Metal backend. We're at the point where it draws almost everything correctly and performance is approx equal to GL with low hanging fruit still left to pick.

**Comment by rahulgs12** [comment]
@bsalomon what would be the best way to get more detailed tracing?

**Comment by frasza** [comment]
@bsalomon Any update on this matter perhaps from your side?

**Comment by bsalomon** [comment]
I'd try removing this check for android framework so that we can see which ops are taking a long time:

https://cs.chromium.org/chromium/src/third_party/skia/src/gpu/GrRenderTargetOpList.cpp?q=GrRenderTargetOpList.cpp&sq=package:chromium&g=0&l=499

**Comment by derolf** [comment]
I see the same on my iPhone X. 

However, interestingly when I turn on screen recording, the jitter completely disappears and everything is super smooth.

I verified that multiple times.

**Comment by tvolkert** [comment]
I'd be interested to know if the same problems happen with the new Metal backend enabled.

@derolf @rahulgs12 @msw333 @yunyu @frasza @bobmoff @wemped are any of you willing to build a custom Flutter engine and try it out?  Instructions are available at https://github.com/flutter/flutter/issues/18208#issuecomment-491548659

**Comment by derolf** [comment]
@tvolkert I am using platform views. Will the metal backend work with them?

**Comment by derolf** [comment]
Btw another interesting observation: I don’t see jitter when in landscape mode.

**Comment by wemped** [comment]
@derolf I still experience jitter in landscape mode

**Comment by tvolkert** [comment]
> I am using platform views. Will the metal backend work with them?

@derolf it should.  If you're willing to give it an early try, we'd love the feedback on what works for you and what doesn't!

**Comment by derolf** [comment]
@tvolkert I’ll prolly give it a shot tomorrow.

Does anyone else see the jitter going away when doing screen recording?

**Comment by coreysprague** [comment]
@derolf I tested the screen recording theory and still see jitter in my app.

**Comment by coreysprague** [comment]
Out of curiosity, has anyone tested on an XR? If it jitters than it would rule out the 120hz input signal that was originally theorized (the XR is 60hz input).

**Comment by scottbaggett** [comment]
@coreysprague I have tested the XR and there is no jitter.  You can even test in the emulator and see massive difference in performance between {X|Xs|XsMax} vs Xr.

**Comment by bobmoff** [comment]
Tried to compile the fluttere engine but got stuck when trying to install gclient. For some reason could not manage to make it execute ”gclient sync”.

Will give it another try some other time.

**Comment by derolf** [comment]
@tvolkert we are having a hard time compiling flutter for metal. Any chance to get prebuilt bins for Mac?

Btw. I recognized two more things:
- jitter depends on screen lightness. If less than ~30% it jitters, if more it’s smooth
- I see the jitter also while panning a native view that uses OpenGL (map rendering)

**Comment by scottbaggett** [comment]
@derolf I am not seeing screen brightness make any difference in any of our builds.  Same amount of jitter/jank when scrolling no matter how bright the device is.

**Comment by yunyu** [comment]
I wasn't able to compile the Metal engine. I get these (unrelated?) warnings when trying to compile ios_release_metal:
<img width="1680" alt="Screen Shot 2019-06-10 at 12 17 13 AM" src="https://user-images.githubusercontent.com/8008350/59178901-35851900-8b15-11e9-9b04-1d1ffa922933.png">

**Comment by wemped** [comment]
@tvolkert 
I also am having trouble figuring out how we would be able to compile the Metal engine.. Are there more detailed instructions anywhere?

**Comment by liyuqian** [comment]
@wemped : `./flutter/tools/gn --ios --enable-metal <other flags as necessary>`. Additionally, you may see some deprecation errors and @chinmaygarde is working on a patch to fix them.

**Comment by wemped** [comment]
@liyuqian Sorry, I think I'm just out of the loop on how `flutter/engine` fits in on all of this.
Might need to take a couple steps back first

Do I need to clone the https://github.com/flutter/engine repo? 
How would I force flutter commands to use the new local engine?

Best case scenario would be steps to do this from square one, or maybe there already are docs on it somewhere that I don't know about?

**Comment by tvolkert** [comment]
@wemped yep you'll have to clone the flutter/engine repo.  Here are the relevant docs:

https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
https://github.com/flutter/flutter/wiki/Compiling-the-engine

**Comment by wemped** [comment]
@tvolkert @liyuqian 
Running through the setup steps today and running into a problem on Step 6 (`gclient sync`) of this guide https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment

It runs fine up until it prints `Syncing projects: 100% (97/97), done.`
Then it hangs, I let it run on for about 10 minutes or so, but each time I eventually kill the process it looks like it locks up on this instruction
```Failed while running "cipd ensure -log-level error -root /Users/dwempe/***/***/engine -ensure-file /var/folders/n0/3qxxwjk57wn31l8qrgq2j73mm0fzqq/T/tmphTqiwW.ensure"```

Any ideas on how to get passed this?

**Comment by liyuqian** [comment]
@wemped : That step may be trying to download gigabytes of tool chains (Android SDK + NDK + Fuchsia SDK + NDK + ...). Can you try monitor your network usage to see if there's download in progress? If your network is less than 10MB/s, it will take a long time to finish.

**Comment by yunyu** [comment]
@wemped I worked around that by checking out the most recent depot_tools commit. However, the compile still won't work due to the deprecation warning issue mentioned above.

**Comment by wemped** [comment]
@liyuqian @tvolkert 
Thanks so much for your continuous help, those docs are great. Feels like I'm very close to getting this working, but having trouble figuring out how to prepare the host flutter engine build.

https://github.com/flutter/flutter/wiki/Compiling-the-engine
On step 3 in `Compiling for iOS (from macOS)`, I did what @liyuqian suggested before and ran `./flutter/tools/gn --ios --enable-metal` to create `out/ios_debug_metal`. But I can't seem to figure out how to make a matching `out/host_...`

At least, I assume that's what the problem is because when I get to `Running a Flutter app with a local engine` and do `flutter run --local-engine=ios_debug_metal` I get this error
```
No Flutter engine build found at /Users/dwempe/***/engine/src/out/host_debug_metal.
```
and sure enough, that doesn't exist at that path - what does exist are `host_debug_unopt` and `ios_debug_metal`

**Comment by liyuqian** [comment]
@wemped : you need to symlink `ln -s host_profile host_profile_metal` or `ln -s host_debug host_debug_metal`. Find **symlink** in https://github.com/flutter/flutter/wiki/Compiling-the-engine for more details.

@yunyu : we just fixed the deprecation warning issue in https://github.com/flutter/engine/pull/9383. Can you please pull the newest engine and see if it succeeds?

**Comment by wemped** [comment]
@liyuqian 
pulled the most recent changes, ran through all the steps in compiling the engine just to be sure

`flutter run --profile --local-engine=ios_profile_metal -d XXX-XXX`

gives me this error
```
Xcode build done.                                            6.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Profile ===
    Building AOT snapshot in profile mode (ios_profile_metal)...

    Compiler message:

    file:///Users/dwempe/***/flutter/packages/flutter/lib/src/painting/binding.dart:117:43: Error: No named parameter with the name 'decodedCacheRatioCap'.

        return ui.instantiateImageCodec(list, decodedCacheRatioCap: decodedCacheRatioCap); // ignore: deprecated_member_use_from_same_package

                                              ^^^^^^^^^^^^^^^^^^^^

    org-dartlang-sdk:///flutter/lib/ui/painting.dart:1657:15: Context: Found this candidate, but the arguments don't match.

    Future<Codec> instantiateImageCodec(Uint8List list, {

                  ^^^^^^^^^^^^^^^^^^^^^

    Compiler terminated unexpectedly.
    Failed to build /Users/dwempe/***/blank.

Could not build the precompiled application for the device.

Error running application on iPhone.
```

**Comment by liyuqian** [comment]
@wemped : this error seems to be a mismatch of the Flutter framework version and the Flutter engine version. What version of framework (https://github.com/flutter/flutter) are you using? One particular fix you can try is to sync your flutter version to the master branch of https://github.com/flutter/flutter, and then sync your engine (https://github.com/flutter/engine) version according to the [bin/internal/engine.version](https://github.com/flutter/flutter/blob/master/bin/internal/engine.version) file in your framework.

**Comment by wemped** [comment]
@liyuqian 
Ok, switched to the framework master channel and upgraded
```
$flutter --version
Flutter 1.7.10-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision c8cefce300 (49 minutes ago) • 2019-06-26 10:09:14 -0700
Engine • revision 3f4f606105
Tools • Dart 2.4.0
```

Looks like the engine version in bin/internal/engine.version is `3f4f606105a8f6217cfbe08e193aa9a54b19dbef`

How would sync my local engine to that version?

**Comment by liyuqian** [comment]
Run `git checkout 3f4f606105a8f6217cfbe08e193aa9a54b19dbef` in your engine repo checkout (e.g., in `~/flutter/engine/src/flutter`), and then repeat the steps of `gclient sync`, `ninja ...`, ...

**Comment by wemped** [comment]
@liyuqian @tvolkert 
Good news and bad news.

I got it running w/ metal enabled 🎉  (@liyuqian thanks again for your help and patience!)
It doesn't fully solve the scroll performance issues on iPhone X/s 😞 

Charging up my old iPhone 7 now to get a side by side and will report back, but so far I'm seeing the same sort of stuttering/missed frames while dragging. I'm also seeing that flings still look good. Just the slow dragging has issues.

**Comment by liyuqian** [comment]
@wemped : I'm sorry to hear the bad news... I'll trade you with one good news: I just received two Mac Minis and iPhone Xrs that I'm going to add to our device lab so we can catch these kind of iPhone X performance issues.

While I'm busy setting it up, it will be super helpful if you can write a Flutter drive test for your specific case and add it to our device lab: https://github.com/liyuqian/flutter/wiki/How-to-add-a-simple-Flutter-device-lab-drive-perf-test

Landing the drive test in our device lab ensures that we'll never regress its performance again. Hopefully it will also help you reproduce the performance issue with less effort.

**Comment by yunyu** [comment]
@liyuqian Unfortunately, this particular performance issue does not occur on iPhone XR

**Comment by enricobenedos** [comment]
> I tried the tiny sample app on my iPhone X and iPhone 5. I can verify that only on the iPhone X there are frequent stutters (lost frames) while drag-scrolling. As soon as I let go of the screen with finger and it only scrolls on inertia, it is fine.
> There is also an increase of these stutters if I swipe up to app switch on iPhone X and then just taps the app again to resume it, and right when it has been resumed again I start drag scrolling. This might be related to this issue: #28113

With my colleagues we has exactly the same problems you describe with iPhone X/Xs. iPhone 7 Plus hasn't these problems.
Our app has a page that show a DataTable with a lot of records/rows. On Android devices or iPhones < X series there are no problems. With iPhone Xs during the page scroll it become completely stucked. The only thing that you can do is change page.

**Comment by wemped** [comment]
@liyuqian 
I think it's important to note (like @yunyu said) that the iPhone XR does not have this issue.

I'd like to help out with writing a test, but I'm not sure how mine would be any different than a simple scrolling test like the one linked in your wiki (https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart). Unless there's a way to force it to be run on a specific device (iPhone X or Xs).

**Comment by liyuqian** [comment]
Oh, I didn't know that https://github.com/flutter/flutter/blob/master/dev/benchmarks/complex_layout/test_driver/scroll_perf_test.dart is sufficient. We have ways to force it to run on iPhone X in our device lab. Buying iPhone X now.

**Comment by wemped** [comment]
@liyuqian 
How did it go with the new devices? Have you been able to reproduce the scrolling issues?

**Comment by liyuqian** [comment]
@wemped : I can reproduce the issues locally on the device. I've set the iPhone XS up in our lab but some of our scripts timed out consistently for the new Mac Mini and iPhone XS pair. Will figure that out soon.

**Comment by knopp** [comment]
Regarding the stutter on app-switching: It seems to be mostly happening on low brightness setting. I noticed this a while ago on iPhone X (and now Xs). With full brightness, the stutter is pretty much nonexistent, but with brightness all the way down it takes seconds for app to start performing normally after switching.

**Comment by liyuqian** [comment]
@knopp thanks for the information! Can you please also:
1.  Switch flutter to master channel and run this app on iPhone X/XS
     using profile mode with Skia tracing enabled, as follows:
       `flutter channel master && flutter doctor -v && flutter run --profile --trace-skia`
     Then press ‘P’ to enable the performance overlay. Copy/paste
     `flutter doctor -v` result here so we know the exact master version
     that you're using.

     The bleeding edge master channel is encouraged here because Flutter is
     constantly fixing bugs and improving its performance. Your problem in an
     older Flutter version may have already been solved in the master channel.

2.  Record a video of the performance issue using another phone so we
     can have an intuitive understanding of what happened. Don’t use
     "adb screenrecord", as that affects the performance of the profile run.

3.  Open Observatory and save a timeline trace of the performance issue
     so we know which functions might be causing it. See "How to Collect
     and Read Timeline Traces" on this blog post:
       https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af03#a499

**Comment by knopp** [comment]
@liyuqian, I'm traveling right now, I might do that when I get back. I've been using flutter master for a year now, this behavior has been present since I started with the framework. 

It should be pretty straightforward to reproduce though even with Flutter Gallery, just keep the device brightness down. The fact that the behavior is depending on device brightness might perhaps suggest some kind of throttling.

**Comment by coreysprague** [comment]
I’m not seeing brightness affect the performance positively or negatively. I do observe that when I switch back to my app, performance is sometimes degraded for a period of time, but I think that is tangential to this particular issue.

@liyuqian - do you need anything at this point to help reproduce the original issue described (jank while dragging using an iPhone X/XS)?

I’ve wondered about making a demonstration app that allowed for gesture based scrolling OR programmatic scrolling to try to confirm that the jank is gesture related. I haven’t had time to do so though.

**Comment by yunyu** [comment]
@coreysprague I have been able to consistently reproduce the jank with the example app I posted a while back: https://github.com/yunyu/flutter_scroll_stutter_test

**Comment by frasza** [comment]
Let me know if there is anything I can also do. I don't think there is anything special with different projects its just something to do with XS, XS Max.
Personal project runs absolutely flawless on any device until its tested on XS, on which scroll is quite worse.

**Comment by liyuqian** [comment]
I've confirmed that the issue is caused by the change of input event handling by iPhone X/XS. On iPhone X/XS, the input sampling rate is 120Hz and the input event callback/delivery rate is 60Hz. However, the 60Hz callback on iPhone X/XS becomes much more irregular than iPhone 6.

iPhone 6 callback interval:
![callback_interval](https://user-images.githubusercontent.com/22987568/61500913-f488eb80-a981-11e9-9714-9dbc45d34bd8.png)

iPhone XS callback interval:
![callback_interval](https://user-images.githubusercontent.com/22987568/61500940-12565080-a982-11e9-8d5d-0b4000bf8566.png)

During scroll, Flutter's frame is driven by those callbacks. If the callback time is not in sync with the 60 Hz VSYNC signal, there will be missing frames.

We'll figure out a solution soon.

**Comment by coreysprague** [comment]
Awesome work! Thanks for the update!

**Comment by liyuqian** [comment]
A potential fix is posted in https://github.com/flutter/flutter/pull/36616

I've also added some unit tests to verify that before the fix, in the worst case we can miss half of the frames. After the fix, in the worst case we miss only one frame.

The followings are comparisons of flutter_gallery scroll:

Before fix             |  After fix
:-------------------------:|:-------------------------:
![scroll_before_fix_600px](https://user-images.githubusercontent.com/22987568/61583860-09d15780-aaf3-11e9-88bc-6ba6161b4edd.gif)  |  ![scroll_after_fix2_600px](https://user-images.githubusercontent.com/22987568/61583861-0c33b180-aaf3-11e9-9760-3467527f823a.gif)

Please let me know if that patch also fixes the problem on your apps and devices.

**Comment by frasza** [comment]
How can I test it if not yet merged in master?

**Comment by jonahwilliams** [comment]
@frasza you can use git in your flutter checkout:
`git remote add liyuqian git@github.com:liyuqian/flutter.git`
`git fetch liyuqian`
`git checkout liyuqian/input_events`

You may need to rebuild the flutter tool too:
`rm bin/cache/flutter_tools.*`

**Comment by coreysprague** [comment]
I gave the branch a whirl and it's a night and day difference on my iPhone XS Max! Awesome work @liyuqian.

Ship it! 😄

**Comment by wemped** [comment]
@liyuqian
Just gave it try and the fix works great 🎉

**Comment by derolf** [comment]
@liyuqian I am seeing jank on my iPhone XS while drag-scrolling, but also after I lifted the finger and inertia scrolling. Will it fix that as well

**Comment by coolnalu** [comment]
Where do we land on the fix? Has it been shipped yet?

**Comment by wuyugege** [comment]
which version of flutter solved this bug? @liyuqian @

**Comment by liyuqian** [comment]
The fix isn't landed or shipped yet as we're trying to come up with another lower level fix. Many other more critical issues have emerged recently so unfortunately that effort isn't done yet.

If you urgently need to fix this issue on your app, I'd recommend cherry-pick https://github.com/flutter/flutter/pull/36616 into your local Flutter.

**Comment by derolf** [comment]
It's nice that you want to fix it lower level, but can you still merge this fix for the time being? We are waiting for this since almost 6 months now...

**Comment by wuyugege** [comment]
In my opinion ,this bug is the most critical issue flutter should fix, i can accept any bug of flutter except this one. This bug results to such a bad user experience , i cannot publish an app developed by flutter to app store until this bug solved.

**Comment by sooxiaotong** [comment]
> hello @liyuqian , i tried, but that pr doesn't solved the bug. After i tap up , scrolling janky goes on for some distance.
> In my opinion ,this bug is the most critical issue flutter should fix now, i can accept any bug of flutter except this one. This bug results to such a bad user experience , i cannot publish an app developed by flutter to app store until this bug solved.

you can use this hack as temporary solution, try to make the brightness stays above 25% ~ 30% 😎
https://pub.dev/packages/screen

**Comment by liyuqian** [comment]
@wuyugege : can you please post more details of the janky scroll after that patch?

For example, following our performance issue report template:

> 1.  Please tell us exactly how to reproduce the problem you are running into.
> 
> 2.  Please attach a small application (ideally just one main.dart file) that
>      reproduces the problem. You could use https://gist.github.com/ for this.
> 
> 3.  Switch flutter to master channel and run this app on a physical device
>      using profile mode with Skia tracing enabled, as follows:
>        flutter channel master
>        flutter run --profile --trace-skia
>      Then press ‘P’ to enable the performance overlay.
> 
>      The bleeding edge master channel is encouraged here because Flutter is
>      constantly fixing bugs and improving its performance. Your problem in an
>      older Flutter version may have already been solved in the master channel.
> 
> 4.  Record a video of the performance issue using another phone so we
>      can have an intuitive understanding of what happened. Don’t use
>      "adb screenrecord", as that affects the performance of the profile run.
> 
> 5.  Open Observatory and save a timeline trace of the performance issue
>      so we know which functions might be causing it. See "How to Collect
>      and Read Timeline Traces" on this blog post:
>        https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af03#a499

**Comment by wuyugege** [comment]
i found this bug in two scenario. @liyuqian 
1、after the app launched
2、switch the APP from background  to foreground
in both scenario，when i scroll on the screen , the janky hanppens for some distance ,and then disappear. this bug maybe not happen every time, but at least 98% probability.
i tried apps developed by flutter on app store, this bug happens on EVERY APP. i'm surprised how can they accept this bug on production.
now i build my app with flutter 1.7.8 of stable version, 1.8.3 of beta version, 1.9.5 of dev version. this bug still there.
you can try the code provided by the bro who opend this issue to reproduce this bug.
also you try this app:https://apps.apple.com/cn/app/cryptograph-designer-charts/id1375281233 ,
on the iphone x/xs. scroll on the home page of this app you will find this bug apparently.

**Comment by liyuqian** [comment]
@wuyugege : yes, that's a different issue (https://github.com/flutter/flutter/issues/32170, previously known as https://github.com/flutter/flutter/issues/813) not covered by the PR.

**Comment by derolf** [comment]
@wuyungegd

> also you try this app:https://apps.apple.com/cn/app/cryptograph-designer-charts/id1375281233 ,
on the iphone x/xs. scroll on the home page of this app you will find this bug apparently.

I can confirm this app having the jank-disease on my iPhone XR and that’s also the exact behavior I have on the app I am developing.

**Comment by liyuqian** [comment]
@derolf : this issue is specific to iPhone X/Xs. If you have some issues on iPhone XR, maybe it's better to leave comments on https://github.com/flutter/flutter/issues/32170 or create a new issue :)

**Comment by derolf** [comment]
@liyuqian sorry, it was an Xs. I edited my comment above.

**Comment by derolf** [comment]
I still have some questions:

- when should the PR appear in master channel?

- does the PR also fix janky kinetic scrolling?

- does the PR also fix janky scrolling that disappears at landscape or screen recording?

**Comment by liyuqian** [comment]
@derolf :

> * when should the PR appear in master channel?

Unfortunately, the previous patch has been reverted. But I'm relanding it with some additional fixes: https://github.com/flutter/engine/pull/12280

> * does the PR also fix janky kinetic scrolling?

The kinetic scrolling shouldn't be affected by input events so there shouldn't be any jank even without the fix. Can you please attach more details of the jank, especially on how to reproduce it?

> * does the PR also fix janky scrolling that disappears at landscape or screen recording?

I'm not sure how it could disappear. It seems to me that the jank will disappear in all cases after the patch.

**Comment by derolf** [comment]
@liyuqian please see #40042 (reported by me) and #38292 (might be related).

**Comment by christian-muertz** [comment]
Seems to be fixed on master now

**Comment by cbracken** [comment]
@liyuqian should this bug be re-closed?

**Comment by liyuqian** [comment]
Yes, the relaneded fix in the framework since https://github.com/flutter/flutter/commit/b9a34dec7eab35abae3d2e0be37a7d73f9d8aceb . Closing this issue.

**Comment by liyuqian** [comment]
Reopen for another revert...

**Comment by volskaya** [comment]
I'm observing the same irregular input delivery and dropped events on Android OnePlus 7 Pro. Alleviated greatly with cherry picking https://github.com/flutter/flutter/pull/36616 , tho "Miss at most one frame for irregular scroll drag events" is still an issue and is apparent even more so on its 90hz screen, as opposed to iPhone's 60hz.

@derolf reports above that the jitters are gone, when screen recording. I observe the same, while screen recorder locked at 60fps.

**Comment by liyuqian** [comment]
@volskaya : thank you for the report! I'm creating a new issue https://github.com/flutter/flutter/issues/41118 to track it separately.

**Comment by liyuqian** [comment]
The fix has been relanded in https://github.com/flutter/flutter/commit/4891e4a349f8e8973311bd064b143fbf122334fc . Hopefully it won't be reverted this time.
