### ISSUE TITLE
Setting maxHeight and maxWidth on imagePicker increases the selected file size dramatically.

### ISSUE THREAD

**Issue by dshukertjr** [flutter/flutter#31096]
I noticed that the file sizes of images that I upload to firebase storage from my flutter application are way bigger than I expected. I figured out that when I set maxHeight and maxWidth property on the imagePicker plugin, the file size increases to more than what it should be. 

Here are some sample image I tried

raw image: 836x675 px and 48,269 bytes
uploaded with maxHeight and maxWidth set to 720: 836x675 px and 144,559 bytes

Okay, so the plugin's maxWidth property isn't working either, but I want to focus on the size increase here.

**Comment by escamoteur** [comment]
This here might fix the problem https://github.com/flutter/flutter/issues/40831

**Comment by cbracken** [comment]
I believe that this is fixed via https://github.com/flutter/plugins/pull/2070.

If you're still seeing this issue I encourage you to file a new bug with repro instructions and we'll take a look. Thanks again for filing.
