### ISSUE TITLE
[Google maps plugin][Feature request] Polygons in addition to polylines.

### ISSUE THREAD

**Issue by MichalTorma** [flutter/flutter#31094]
Hi, first of all, thanks for a great job with flutter :)
I would like to make a request for polygons in Google maps plugin (not to be confused with polylines that are available since 0.5.6).
Polygons with onTap gesture detection are essential to my app.
Thanks and keep up the good work!

Regards

**Comment by JamesMcIntosh** [comment]
@MichalTorma Polygons are already in the API, you might like to close this ticket

**Comment by JamesMcIntosh** [comment]
Looks like there is a bug as they work for Android but not iOS.

**Comment by JamesMcIntosh** [comment]
Create a PR to fix the issue https://github.com/flutter/plugins/pull/1801
