### ISSUE TITLE
Navigation issue on iOS

### ISSUE THREAD

**Issue by anderscheow** [flutter/flutter#31100]
When I press a button to navigate from first page to second page, there's a glitch when I attempt to slide from left side of the screen to navigate back to first page then quickly press the button to navigate to second page. It unable to show second page and the button no longer proceed the navigation.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11788504/56174207-fca05a80-6023-11e9-9d6c-8082fc357004.gif)

## Steps to Reproduce

Here's the [example](https://gist.github.com/anderscheow/51ab5f85a1324c4d3826ad015b142bf6)

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.2.1 at /Users/anderscheow/Documents/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/anderscheow/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
```

**Comment by najeira** [comment]
same as #28876

**Comment by escamoteur** [comment]
Hi, sorry for the late reply, I would like to ask if you could solve your problem in the meantime?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
