### ISSUE TITLE
Stack：must set textDirection？

### ISSUE THREAD

**Issue by manburenshenglu** [flutter/flutter#31105]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```
![{DDC`$LNP E12@ AQJ~P5TU](https://user-images.githubusercontent.com/13146756/56178589-68d78a00-6035-11e9-96bb-38f8ac9cab5b.png)

**Comment by ffey** [comment]
In widget ```Stack```,  ```textDirection``` is not must added attribute.

**Comment by ffey** [comment]
please close the issue. @jonahwilliams
