### ISSUE TITLE
Issue from website page 代码错误

### ISSUE THREAD

**Issue by Jss-w** [flutter/flutter#31107]
From URL: https://www.flutterchina.club/cookbook/networking/authenticated-requests.md
final json = JSON.decode(response.body); #
应该为

  final responseJson  = json.decode(response.body);

**Comment by ffey** [comment]
你的issue应该到flutterchina.club去提交， flutterchina.club是国内朋友翻译的文档， 跟flutter没有关系。

**Comment by ffey** [comment]
中文翻译文档未参照最新英文文档更新，建议到 https://github.com/flutterchina/website/issues 提issue.

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
