### ISSUE TITLE
TextField and InkWell inconsistent splash

### ISSUE THREAD

**Issue by altherat** [flutter/flutter#31108]
Is there a reason TextField produces a different splash effect than an InkWell when tapped by default?

Example app:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Column(
            children: <Widget>[
              TextField(),
              TextField(),
              Container(
                height: 50,
                child: InkWell(
                  onTap: () {}
                )
              )
            ]
          )
        )
      )
    );
  }
}
```

It appears TextField's splash has no highlight color set? Adding `highlightColor: Colors.transparent` to the InkWell matches the TextField's effect.

**Comment by eseidelGoogle** [comment]
Entertainingly there is no splash at all on Web for TextFields:
https://dartpad.dev/c4a6a6847867e93d1a7b337306a2945e

**Comment by justinmc** [comment]
I believe Material text fields no longer produce a splash at all, in Flutter nor in Material's guidelines.  See the [Material spec](https://material.io/components/text-fields#theming).

I'll close this, but if I'm missing a case where this is relevant, please let me know so I can reopen.

**Comment by vtrikoupis** [comment]
I can confirm the splash is inconsistent
