### ISSUE TITLE
FileSystemException: Deletion failed （OS Error: Operation not supported, errno = 45）

### ISSUE THREAD

**Issue by wangqianjun** [flutter/flutter#31111]
I'm use` flutter run` command to report an error
## Logs

Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...

 ├─Assembling Flutter resources...                           3.2s
 └─Compiling, linking and signing...                         6.3s
Xcode build done.                                           14.4s
Unhandled exception:
FileSystemException: Deletion failed, path = '/var/folders/33/_6pp_4s926d0bq5g594jb_8c0000gn/T/flutter_build_log_pipe.g1bbSC' (OS Error: Operation not supported, errno = 45)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:475:22)
<asynchronous suspension>
#4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:488:37)
<asynchronous suspension>
#5      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:488:37)
<asynchronous suspension>
#6      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:492:39)
<asynchronous suspension>
#7      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:380:48)
<asynchronous suspension>
#8      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:307:15)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:361:54)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#31     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#38     Future._complete (dart:async/future_impl.dart:473:7)
#39     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#42     FlutterProject._readManifest (package:flutter_tools/src/project.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#44     _rootRunUnary (dart:async/zone.dart:1132:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#49     Future._complete (dart:async/future_impl.dart:473:7)
#50     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#51     _rootRunUnary (dart:async/zone.dart:1132:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#53     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#54     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#55     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#56     Future._complete (dart:async/future_impl.dart:473:7)
#57     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#58     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#59     _rootRun (dart:async/zone.dart:1124:13)
#60     _CustomZone.run (dart:async/zone.dart:1021:19)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```
Run `flutter analyze` and attach any output of that command below.
  info • Unused import: 'package:test/test.dart' • lib/main.dart:2:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: MyApp.x • lib/main.dart:7:7 • must_be_immutable
   info • The value of the local variable 'x' isn't used • lib/main.dart:14:12 • unused_local_variable
   info • The method '_incrementCounter' isn't used • lib/main.dart:37:8 • unused_element
   info • The method '_buildTextBody' isn't used • lib/main.dart:52:10 • unused_element
   info • The value of the local variable 'textDecoration' isn't used • lib/main.dart:54:20 • unused_local_variable
```

```
`flutter doctor -v`
[✓] Flutter (Channel master, v1.4.20-pre.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.4.20-pre.2 at /Users/arthur/work/coding/flutter
    • Framework revision 27b058a414 (3 days ago), 2019-04-12 17:42:25 -0700
    • Engine revision 9aa7c9a48e
    • Dart version 2.2.1 (build 2.2.1-dev.4.2 None)


[!] Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    • Android SDK at /Users/arthur/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/arthur/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 37F953B5-6734-449E-90CF-01A90082E36E • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by cakesoft-shailesh** [comment]
You can use:
 final dir = Directory(dirPath); 
 dir.deleteSync(recursive: true);

**Comment by RobertApikyan** [comment]
I receive the error on iOS 12.3.1
I'v tried to delete file in this way, it seems that this work 

  static Future<void> removeAll()  async{
    final directory = await getApplicationDocumentsDirectory();
    final file = File(directory.path);
    final isExists = await file.exists();
    if(isExists){
      await file.delete(recursive: true);
    }
  }
