### ISSUE TITLE
Return from Futures and catchError

### ISSUE THREAD

**Issue by durduman** [flutter/flutter#31119]
I would like to have the main function print StateB and not have an 'Uncaught Error' because of a type miss match.

I am not certain why this does not work as expected.

Here is the code from my [DartPad][1]

```

    import 'dart:async';
    
    abstract class State {
      String toString();
    }
    
    class StateA extends State {
      @override
      String toString() => 'StateA';
    }
    
    class StateB extends State {
      @override
      String toString() => 'StateB';  
    }
    
    void main() async {
      final result = await function1();
      print("Result:" + result.toString());                        // <<<< HERE IT MUST PRINT StateB
    }
    
    Future<State> function1() {
      return Future(() => Future.value()) // some random task
        .then((_) => function2())
        .then((_) => StateA())
    //     .then((_) => Future<State>.value(StateA()))  // COMMENT LINE ABOVE LINE AND SWITCH TO THIS ONE TO MAKE IT WORK AS EXPECTED 
        .catchError((error) {
          return StateB();
    //     	return Future<State>.value(StateB());     // COMMENT LINE ABOVE SWITCH TO THIS ONE TO MAKE IT WORK AS EXPECTED 
      	});
    }
    
    Future<State> function2() {
    //   throw Exception("function2");        
      return Future.error(Exception("function2"));
    }

```

The way we re-throw errors also created a tricky situation. Check [this][2] for more info.

I've left some additional comments on the lines that actually make it work.

Maybe I missed something since in dart's documentation clearly they just return the value not a future with a value.

[Documentation][3] on Futures and Error Handling.

  [1]: https://dartpad.dartlang.org/
  [2]: https://stackoverflow.com/questions/55596257/catch-error-using-catcherror-in-a-future-and-throw-another-type/55608201#55608201
  [3]: https://www.dartlang.org/guides/libraries/futures-error-handling

**Comment by escamoteur** [comment]
It helps finding such bugs by always providing the generic type to the `Future`

Please ask questions like this on stackoverflow because we are not able to give individual support here.
