### ISSUE TITLE
Cascade multiple widgets to scale

### ISSUE THREAD

**Issue by jizhigang** [flutter/flutter#31113]
When using the Stack layout, if I set`alignment: FractionalOffset(0.5, 0.5)`, the widgets will appear in the center in proportion to the constraints. However, if I want to display multiple widgets in different positions in proportion, how can I achieve this? Do not use the`Positioned `

**Comment by ffey** [comment]
How to align the non-positioned and partially-positioned children in thestack.
 The non-positioned children are placed relative to each other such that the points determined by [alignment] are co-located. For example, if the [alignment] is [Alignment.topLeft], then the top left corner of each non-positioned child will be located at the same global coordinate.
Partially-positioned children, those that do not specify an alignment in a particular axis (e.g. that have neither `top` nor `bottom` set), use the alignment to determine how they should be positioned in that under-specified axis.
Defaults to [AlignmentDirectional.topStart].

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow because we are not able to give individual support here.
