### ISSUE TITLE
Progress bars should shrink once complete

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3111]
https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

**Comment by HansMuller** [comment]
I don't see any evidence of a "shrink when complete" feature in the current Material spec: https://material.io/design/components/progress-indicators.html

Maybe this is no longer a thing?

**Comment by Hixie** [comment]
Second set of screenshots after the "Types" header in https://material.io/design/components/progress-indicators.html#usage.

**Comment by HansMuller** [comment]
I don't think that's supposed to be a feature of the component; will ask about it.

**Comment by TahaTesser** [comment]
In new specs,  both progress and circular progress indicators are fading when completion 

https://material.io/components/progress-indicators#linear-progress-indicators
https://material.io/components/progress-indicators#circular-progress-indicators

and also gallery has always loading examples  https://gallery.flutter.dev/#/demo/progress-indicator

Closing the issue, if you disagree please write in the comments and I will reopen it 
Thank you

Looks like gallery always loading progress bars
