### ISSUE TITLE
The setter 'readEventsEnabled=' was called on null

### ISSUE THREAD

**Issue by beijie001** [flutter/flutter#31118]
## Steps to Reproduce

1. When i run "flutter packages get",  Get the flowing error message
2. I use lantern app,and set the global proxy, and i aslo set the proxy in the Android studio.
3. flutter doctor show that everything is ok

Running "flutter packages get" in flutter_app...                The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false

package:pub/src/source/hosted.dart 349:7                                BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 150:7                                BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 167:12                                      BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44                        PackageLister._versions.<fn>.<fn>
dart:async                                                              runZoned
package:pub/src/http.dart 272:10                                        withDependencyType
package:pub/src/solver/package_lister.dart 75:33                        PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                                              new Future.sync
package:async/src/async_memoizer.dart 43:42                             AsyncMemoizer.runOnce
package:pub/src/solver/package_lister.dart 74:58                        PackageLister._versions
package:pub/src/solver/package_lister.dart 111:21                       PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 354:44                       VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 301:39                                       minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 350:25                       VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:22                        VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/solver.dart 35:10                                       resolveVersions.<fn>
package:pub/src/log.dart 378:18                                         progress
package:pub/src/solver.dart 32:10                                       resolveVersions
package:pub/src/entrypoint.dart 203:24                                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 41:23                                  GetCommand.run
package:args/command_runner.dart 194:27                                 CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 171:39                              PubCommandRunner.runCommand.<fn>
dart:async                                                              new Future.sync
package:pub/src/utils.dart 109:12                                       captureErrors.<fn>
dart:async                                                              runZoned
package:pub/src/utils.dart 126:5                                        captureErrors
package:pub/src/command_runner.dart 171:13                              PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 119:11                              PubCommandRunner.run

===== asynchronous gap ===========================
/b/s/w/ir/k/src/third_party/dart/third_party/pkg/pub/bin/pub.dart 8:22  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (1)

Flutter doctor -v result:
 flutter_app flutter doctor -v
[✓] Flutter (Channel beta, v1.3.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.3.8 at /home/jeff/flutter
    • Framework revision e5b1ed7a7f (6 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jeff/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/jeff/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by escamoteur** [comment]
Hi, sorry for the late reply, I would like to ask does this problem still exist?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
