### ISSUE TITLE
method nameof C# equivalent on Flutter

### ISSUE THREAD

**Issue by SilvereNef** [flutter/flutter#31125]
Hello everybody,
I search a method in Flutter who made like "nameof()" in C#.
this method stop mistakes when you encode or decode from json.

I see dart:mirrors but it's not compatible with Flutter.
I also see Reflectable package but I don't find a method like getName(). I just found a method getTypeName() who obtains a name of type object, but it's not that I search.

thanks a lot for your help.

**Comment by SilvereNef** [comment]
Nobody says ??

**Comment by escamoteur** [comment]
Hi, please propose this at https://github.com/dart-lang/language/issues IMHO this should be possible without reflection. You have to make some PR for it so that many people upvote it :-)  please link that issue here.
