### ISSUE TITLE
Ability to disable Drawer edge-swipe 

### ISSUE THREAD

**Issue by dougsatch** [flutter/flutter#31127]
I've been looking for a way to disable edge-swipe open of a Drawer, but can't find a way to do it.

It would be great to be able to open the Drawer only programmatically. Users often find that the Drawer edge-swipe gets in the way, e.g. when using horizontal lists, it's easy to accidentally open the Drawer instead of scrolling the list across.

**Comment by wootz-worakorn** [comment]
Same problem and can't find some answer for google.

**Comment by StoneN** [comment]
Is there any answer now ?

**Comment by misterfourtytwo** [comment]
Have somebody found a way?

**Comment by ledarh** [comment]
Bumping this issue. Would love to see a solution!

**Comment by godlessturtle** [comment]
still waitin for it

**Comment by kelvin1hui** [comment]
Bumping this issue. 
Still cannot find the solution from google

**Comment by ch-muhammad-adil** [comment]
any work around ?

**Comment by serhii-k** [comment]
You can try drawerEdgeDragWidth: 0.0 in your Scaffold.

**Comment by nelsonalexandrino** [comment]
can you try to put **drawerEdgeDragWidth: 0** on you Scaffold

Scaffold(
    **drawerEdgeDragWidth: 0,**
    drawer: Container(width: 100),
    body: Container(),
);


please let me know if this will work for you.

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by shihaohong** [comment]
I believe that this effect is already achievable by combining the use of Scaffold.drawerEdgeDragWidth and ScaffoldState.openDrawer. I created a PR to add sample docs to the `Scaffold.drawer` property.

**Comment by rickmrobin** [comment]
**drawerEdgeDragWidth: 0** works.

But in my app i have both drawer and endDrawer. It disables both drawers to swipe. Is there any way to only disable the endDrawer edge swipe?

**Comment by shihaohong** [comment]
@rickmrobin I took a quick look and it seems like `drawerEdgeDragWidth` unfortunately affects both the `drawer` and `endDrawer`. I created a new issue to track a feature request for enabling a drawer while keeping the other disabled: https://github.com/flutter/flutter/issues/49804

**Comment by shihaohong** [comment]
This issue has already been closed, but I would like to ask for some opinions on disabling drags to open/close the drawers on each end. There is currently a PR in progress (https://github.com/flutter/flutter/pull/50925) that allows developers to disable individual drawer drag gestures in the event that one would like to disable just one drawer but not the other (drawer vs endDrawer).

Given that the drawer can only be opened programmatically and not via a drag gesture, would it be more common that developers/users expect the drawer to also be required to be closed programmatically, or that the drawer can also be closed with a drag gestures?

**Comment by rickmrobin** [comment]
@shihaohong this seems like the solution to the problem to prevent user to drag and open the endDrawer. But disabling drag gestures will also prevent closing the drawer or endDrawer by dragging. As you said it will be more common for users or developers to expect to close the drawer by dragging even if not opened by drag gesture. Closing outside the drawer will close the drawer but still if we can figure out some other way to disable only to open drawer by dragging instead disabling both closing and opening by dragging.

**Comment by perclasson** [comment]
I modified the PR https://github.com/flutter/flutter/pull/50925 now to only disable the open drawer gesture, which should cover the use case now.

**Comment by nt4f04uNd** [comment]
How do I disable the gesture without updating a whole widget tree under Scaffold, because this lead to severe frame drops? I have a very large main screen and I need to disable the scaffold gesture when user expands bottom panel widget (it looks like YouTube bottom video widget).

**Comment by j0nscalet** [comment]
@rickmrobin @shihaohong We have a use case where we'd like to disable the close drag gesture on the drawer. That doesn't seem to be the direction #50925 is going though. Any suggestions? 

(Note: we're handling the tap to close issue by setting the width of the drawer equal to the screen size via MediaQuery.of(context).size.width.)

**Comment by hiashutoshsingh** [comment]
```
drawerEnableOpenDragGesture: false,
drawerEdgeDragWidth: 0,
endDrawerEnableOpenDragGesture: false,
```
set this all 3 values still not working in my case :(

**Comment by absarrahman** [comment]
For those who are still not clear what's the exact solution and searching for answers, then here is your answer. For disabling end drawer gesture, you need to set endDrawerEnableOpenDragGesture: false,. For disabling drawer gesture, you need to set drawerEnableOpenDragGesture: false . I am providing a sample code so that I becomes more clear to you 
`Scaffold(
      drawerEnableOpenDragGesture: false,
      endDrawerEnableOpenDragGesture: false,
      drawer: DrawerWidget(),
      endDrawer: EndDrawerWidget(),
      body: child,
    );`

**Comment by absarrahman** [comment]
For those who are still not clear what's the exact solution and searching for answers, then here is your answer. For disabling end drawer gesture, you need to set endDrawerEnableOpenDragGesture: false,. For disabling drawer gesture, you need to set drawerEnableOpenDragGesture: false . I am providing a sample code so that I becomes more clear to you

`Scaffold(
      drawerEnableOpenDragGesture: false,
      endDrawerEnableOpenDragGesture: false,
      drawer: DrawerWidget(),
      endDrawer: EndDrawerWidget(),
      body: child,
);`
