### ISSUE TITLE
Support progress bar "query indeterminate" mode

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3112]
https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

**Comment by Hixie** [comment]
Specifically this is the same as indeterminate, but going "backwards".

**Comment by HansMuller** [comment]
I don't see this feature in the current material spec: https://material.io/design/components/progress-indicators.html

Maybe it's not longer a thing.

**Comment by Hixie** [comment]
Excellent!
