### ISSUE TITLE
Gridview is not diplay in screen

### ISSUE THREAD

**Issue by kavishamodi97** [flutter/flutter#31124]
I/flutter (27520): Instance of 'Future<List<TimetableData>>'
I/flutter (27520): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (27520): The following assertion was thrown during performLayout():
I/flutter (27520): RenderFlex children have non-zero flex but incoming height constraints are unbounded.
I/flutter (27520): When a column is in a parent that does not provide a finite height constraint, for example if it is
I/flutter (27520): in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
I/flutter (27520): flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
I/flutter (27520): space in the vertical direction.
I/flutter (27520): These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
I/flutter (27520): cannot simultaneously expand to fit its parent.
I/flutter (27520): Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
I/flutter (27520): children (using Flexible rather than Expanded). This will allow the flexible children to size
I/flutter (27520): themselves to less than the infinite remaining space they would otherwise be forced to take, and
I/flutter (27520): then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
I/flutter (27520): constraints provided by the parent.
I/flutter (27520): The affected RenderFlex is:
I/flutter (27520):   RenderFlex#4ab02 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520): The creator information is set to:
I/flutter (27520):   Column ← RepaintBoundary-[<0>] ← IndexedSemantics ← NotificationListener<KeepAliveNotification> ←
I/flutter (27520):   KeepAlive ← AutomaticKeepAlive ← SliverList ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter (27520):   IgnorePointer-[GlobalKey#23191] ← Semantics ← ⋯
I/flutter (27520): See also: https://flutter.io/layout/
I/flutter (27520): If this message did not help you determine the problem, consider using debugDumpRenderTree():
I/flutter (27520):   https://flutter.io/debugging/#rendering-layer
I/flutter (27520):   http://docs.flutter.io/flutter/rendering/debugDumpRenderTree.html
I/flutter (27520): If none of the above helps enough to fix this problem, please don't hesitate to file a bug:
I/flutter (27520):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (27520): 
I/flutter (27520): When the exception was thrown, this was the stack:
I/flutter (27520): #0      RenderFlex.performLayout.<anonymous closure> (package:flutter/src/rendering/flex.dart:691:11)
I/flutter (27520): #1      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:712:10)
I/flutter (27520): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #7      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
I/flutter (27520): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #9      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (27520): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #11     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (27520): #12     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (27520): #13     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (27520): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
I/flutter (27520): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (27520): #31     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (27520): #32     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
I/flutter (27520): #33     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (27520): #34     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (27520): #35     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (27520): #36     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (27520): #37     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (27520): #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (27520): #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (27520): #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (27520): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (27520): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (27520): #43     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (27520): #44     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (27520): 
I/flutter (27520): The following RenderObject was being processed when the exception was fired:
I/flutter (27520):   RenderFlex#4ab02 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520):   creator: Column ← RepaintBoundary-[<0>] ← IndexedSemantics ←
I/flutter (27520):   NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← SliverList ←
I/flutter (27520):   SliverPadding ← Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#23191] ← Semantics ← ⋯
I/flutter (27520):   parentData: <none> (can use size)
I/flutter (27520):   constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
I/flutter (27520):   size: MISSING
I/flutter (27520):   direction: vertical
I/flutter (27520):   mainAxisAlignment: start
I/flutter (27520):   mainAxisSize: max
I/flutter (27520):   crossAxisAlignment: center
I/flutter (27520):   verticalDirection: down
I/flutter (27520): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (27520):   RenderRepaintBoundary#79892 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520):     RenderCustomPaint#52c95 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520):       RenderRepaintBoundary#1b541 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520):         _RenderScrollSemantics#553f8 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520):           RenderSemanticsGestureHandler#814e6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (27520): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (27520): Another exception was thrown: RenderBox was not laid out: RenderFlex#4ab02 relayoutBoundary=up5 NEEDS-PAINT
I/flutter (27520): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#df596 relayoutBoundary=up4 NEEDS-PAINT
I/flutter (27520): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 461 pos 12: 'child.hasSize': is not true.
I/flutter (27520): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (27520): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (27520): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

**Comment by ffey** [comment]
The error logs has been show the cause of it.  maybe you should check your code .

**Comment by escamoteur** [comment]
Please ask questions like this on stackoverflow because we are not able to give individual support here.
