### ISSUE TITLE
Need a ThemeData property for the color of selected rows

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#3113]
ThemeData has:

* accentColor
* highlightColor
* splashColor
* selectionColor
* backgroundColor
* indicatorColor
* unselectedColor
* disabledColor

~~I'm considering renaming unselectedColor to inactiveColor and introducing selectedColor for the table rows.~~

**Comment by Hixie** [comment]
See <https://www.google.com/design/spec/components/data-tables.html>

**Comment by Hixie** [comment]
Actually "inactive" sucks as a name for what unselectedColor is.

**Comment by abarth** [comment]
"selected" is probably too similar to "selection"

**Comment by Hixie** [comment]
and "unselected", agreed.

**Comment by Hixie** [comment]
Maybe "pickedRowColor"...

**Comment by Hixie** [comment]
or selectedRowColor, unselectedWidgetColor, and textSelectionColor?
