### ISSUE TITLE
Official Undo support for IOS

### ISSUE THREAD

**Issue by ghost** [flutter/flutter#31133]
iOS will have Native undo support on mobiles and iPads.

https://9to5mac.com/2019/04/15/ios-13-features-dark-mode/

It's important see support this.

"
The gesture starts as a three-finger tap on the keyboard area, sliding left and right allows the user to undo and redo actions interactively.
"

This events in question should be raised to the flutter level so the develop can handle them.

**Comment by chinmaygarde** [comment]
cc @jmagman for platform integration @goderbauer for context specific undo-redo support in the framework.

**Comment by jmagman** [comment]
I believe this is already covered by https://github.com/flutter/flutter/issues/34749 and https://github.com/flutter/flutter/issues/24222.
