### ISSUE TITLE
Engine crashes when placing cursor in the middle of tab characters

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#31154]
The app is crashing when tapping in the middle of some tab characters in a TextField.

Related:
https://github.com/flutter/engine/pull/8591
https://github.com/flutter/flutter/issues/30173

## Steps to Reproduce

1. In any TextField, enter some text, a few tab characters, and then some more text.
2. Tap in the middle of the tab characters to attempt to place the cursor there.
3. Crash!

Note that most software keyboards don't have a tab key. You'll need to use a physical keyboard (with a simulator or real device), or install a keyboard with tab, like the Keyboard for Excel.

## Logs
Unfortunately I don't get a full stack trace, just this:
```
[VERBOSE-3:opacity_layer.cc(16)] Check failed: layers().size() > 0.
```

**Comment by justinmc** [comment]
Currently I can only reproduce this on iOS when running with a local copy of the engine, for whatever reason.  I can't get it to happen on Android, but I swear I did see it there at some point...

I'm not sure if anyone has ever seen this happen in a production app, but it's something to keep an eye out for.

**Comment by darshankawar** [comment]
@justinmc 
I am unable to replicate this crash on Android and iOS using latest stable version. Tried on emulator with physical keyboard to enter tab characters and then tapped on it which allowed to type in text properly without any issues, unless there are any specific steps to replicate the crash.

[31154_ios.mov.zip](https://github.com/flutter/flutter/files/5615700/31154_ios.mov.zip)
[31154.mov.zip](https://github.com/flutter/flutter/files/5615701/31154.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

I am going ahead and closing this. If you disagree or think this should be kept open for tracking, feel free to write in comments and I'll reopen it.
Thanks.

**Comment by justinmc** [comment]
Thanks for trying this.  I haven't run into this problem again, so I'm ok with it being closed.
