### ISSUE TITLE
WebView access camera

### ISSUE THREAD

**Issue by Julianoze** [flutter/flutter#31166]
I trying to develop a WebView application, using url_launcher.
Can I access the camera, throught the WebView?

I using this site to test, but I don't have any sucess 
https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by ffey** [comment]
you can listening the webview event , and call flutter camera plugins to deal it;

**Comment by Julianoze** [comment]
How can I do that? 
I read the documentation, but I still some issues.

**Comment by ffey** [comment]
use ```navigationDelegate``` get the navagation params.?

**Comment by ffey** [comment]
you can init the webview widget
```

    WebView(
                 initialUrl: 'http://192.168.1.94:8088/',
                javascriptMode: JavascriptMode.unrestricted,
                onWebViewCreated:
                    (WebViewController webViewController) {
                  _controller.complete(webViewController);
                },
                **javascriptChannels: <JavascriptChannel>[
                  _toasterJavascriptChannel(context),
                ].toSet(),**
    ........
```
```
JavascriptChannel _toasterJavascriptChannel(BuildContext context) {
    return JavascriptChannel(
        name: '_Toaster',
        onMessageReceived: (JavascriptMessage message) {
          Scaffold.of(context).showSnackBar(
            SnackBar(content: Text(message.message)),
          );
        });
  }
```

Then you can use the function ```_Toaster.postMessage(yourMessage)``` at your html code.

**Comment by ffey** [comment]
also you can get the info from navigation params use ```navigationDelegate```

**Comment by Julianoze** [comment]
Thank you FFey
I'll try

**Comment by ffey** [comment]
The solution is just for the plugin ```flutter_webview```

**Comment by enfraly** [comment]
Hi, Bro hoy i use this _Toaster.postMessage(yourMessage)

**Comment by luckymehndiratta** [comment]
Is there any way to give camera and microphone permission to webview

**Comment by Dewsworld** [comment]
> Is there any way to give camera and microphone permission to webview

I have similar query
