### ISSUE TITLE
Add 2 app how to communicate with native when using embedding.android.FlutterActivity

### ISSUE THREAD

**Issue by daibao520** [flutter/flutter#31172]
I read this [https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Activity](url)
but i don't know how to use channel communicate with native because "embedding.android.FlutterActivity" not contain "getFlutterView" method

```
new MethodChannel(getFlutterView(), BATTERY_CHANNEL).setMethodCallHandler(
                new MethodChannel.MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
                        if (call.method.equals("getBatteryLevel")) {
                            result.success(1111);
                        } else {
                            result.notImplemented();
                        }
                    }
                }
        );
```

**Comment by truongsinh** [comment]
@daibao520 I just happened to publish an article on this topic several hours ago https://hackernoon.com/how-to-add-flutter-to-your-production-android-app-4b5150de9e44. Your question lies in step 3, 4, and 6 of that article.

Feedback and/or "claps" are appreciated :D

**Comment by daibao520** [comment]
> @daibao520 I just happened to publish an article on this topic several hours ago https://hackernoon.com/how-to-add-flutter-to-your-production-android-app-4b5150de9e44. Your question lies in step 3, 4, and 6 of that article.
> 
> Feedback and/or "claps" are appreciated :D

It is a very goooooooood article. 
Thank you so much.

**Comment by truongsinh** [comment]
@PoojaB26 thanks, I updated the link, though it was a while ago, for Flutter 1.5.4 . For 1.9.1, I have not had time to review yet 😁

**Comment by PoojaB26** [comment]
@truongsinh Yes, the APIs have changed since then!

**Comment by jmagman** [comment]
Does https://flutter.dev/docs/development/platform-integration/platform-channels#step-3-add-an-android-platform-specific-implementation cover your documentation request?

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/46855.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
