### ISSUE TITLE
Getting problem for last 6 months with Google_maps_flutter plugin 

### ISSUE THREAD

**Issue by princeagra21** [flutter/flutter#31180]
1. their is no sample code for line draw between coordinates.

2. unable to apply moving effect like.

![moving-animtion](https://user-images.githubusercontent.com/11417381/56266506-00a6a800-610a-11e9-9f89-2668eeb98d78.gif)

**Comment by darshankawar** [comment]
@princeagra21 
Are you still facing this issue ?
Polyline support for the plugin was added with this [PR](https://github.com/flutter/plugins/pull/1049) long time back which helps to draw lines between two locations. See [this](https://medium.com/flutter-community/drawing-route-lines-on-google-maps-between-two-locations-in-flutter-4d351733ccbe) article on how to do it and confirm if it answers your question.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
