### ISSUE TITLE
Add2App cannot go to non-initial routes when using cached flutter engine

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#31185]
As shared in my [Hackernoon article](https://medium.com/hackernoon/how-to-add-flutter-to-your-production-android-app-4b5150de9e44#83fb)

According to the current official wiki, you can achieve this with either/both `createBuilder().initialRoute` and `createBuilder().dartEntrypoint`. However, we found out that once we use the cached flutter engine, those methods are no longer working. What we have to do now is to convert the top-most widget (MyApp) into a stateful widget, and listen to the platform channel (event channel) and build the widget accordingly.

Coder can achieve it by themselves, but I think the framework can have some support to reduce the boilerplate code.

**Comment by truongsinh** [comment]
cc @matthew-carroll

**Comment by PoojaB26** [comment]
Hey @truongsinh Your article is no longer available at the given location. Can you please send another link?

**Comment by truongsinh** [comment]
Damn hackernoon 😂, I updated the link in the original description, you can click directly here as well https://medium.com/hackernoon/how-to-add-flutter-to-your-production-android-app-4b5150de9e44#83fb . Please be noticed that the instruction there is for `1.5.4-hotix.1`, in current stable and recent versions, it might break/crash (I reported at https://github.com/flutter/flutter/pull/31028#issuecomment-516896683)

**Comment by matthew-carroll** [comment]
The framework probably can provide some help here by providing a top-level widget as described. We've discussed it before, but I don't believe we have this goal prioritized.

CC @xster do you have any thoughts?

**Comment by xster** [comment]
If I understand right, the question is if in Android/iOS, the point in code where you determined that you want to prewarm the Flutter engine isn't the same point where you determine which route the Flutter engine wants to preload right? Or if you already prewarmed the engine and you change your mind on which route the prewarmed engine should show, there isn't easy ergonomics?

The iOS FlutterViewController embedding has push and pop functions. Is that what you want or perhaps a replace-top-route function?

**Comment by matthew-carroll** [comment]
I don't think we want push/pop semantics because what we're probably talking about are independent experiences that should have their own backstack. I think what we'd want to provide is a widget that switches out the entire tree based on some incoming parameter.

**Comment by xster** [comment]
I suspect @matthew-carroll and @truongsinh are possibly alluding to different things. 

My interpretation of what @truongsinh is saying is:
I started with an initial entrypoint / route while prewarming the engine and then I changed my mind, but I have no way of changing it anymore. i.e. a Navigator.pushReplacementNamed function on FlutterEngine would be nice and the existing navigation stack on the navigator doesn't matter.

My interpretation of what @matthew-carroll is saying is:
I want some all-in-one mechanism to toggle between parallel navigation stacks that I can control from the embedding side. Basically something like https://github.com/alibaba/flutter_boost.

**Comment by wanjm** [comment]
any progress on this.  

will route be added to cached engine?

**Comment by xster** [comment]
Added a note to make sure we talk about `flutterEngine.getNavigationChannel().setInitialRoute()` in the docs. https://github.com/flutter/flutter/issues/45220

For a 'replace root route after setting one' type platform side API, we're unlikely to add new APIs to the current navigator until we refactor it altogether in https://github.com/flutter/flutter/issues/45938.

**Comment by matthew-carroll** [comment]
@wanjm the concept of an "initial route" would not be appropriate in the API for launching a `FlutterActivity` or `FlutterFragment` with a cached engine because the idea behind a cached engine is that it's already running, and therefore it's too late to give it an initial route.

However, wherever you pre-warm a `FlutterEngine` you should be able to use the `setInitialRoute()` method that @xster mentioned in his comment above.

**Comment by AugustToko** [comment]
After I tried, I found that if you want to (use) cache `FlutterEngine`, you must declare and set `setInitialRoute(route)`in advance, then you can use cached `FlutterEngine` to open your target route.

`  
flutterEngine = FlutterEngine(this) `
`
flutterEngine.navigationChannel.setInitialRoute("your route")
flutterEngine.dartExecutor.executeDartEntrypoint(DartExecutor.DartEntrypoint.createDefault())
        FlutterEngineCache
                .getInstance()
                .put("my_engine_id", flutterEngine)
`

**Comment by tarek360** [comment]
I think the goal of prewarming the engine is to prewarm only the engine itself, some times I don't want to prewarm my Initial Route (first page), for example, if the Initial Route has some intro animation, the user will not see it, because it's already started with `setInitialRoute()`

**Comment by xster** [comment]
See the note box in https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#step-3-optional-use-a-cached-flutterengine. 

Prewarming the engine will start running your dart code. Once https://github.com/flutter/engine/pull/14002 is in, you can distinguish between running and running+visible by checking that AppLifecycleState is no longer "detached".

**Comment by imTamil** [comment]
> I think the goal of prewarming the engine is to prewarm only the engine itself, some times I don't want to prewarm my Initial Route (first page), for example, if the Initial Route has some intro animation, the user will not see it, because it's already started with `setInitialRoute()`

The same issue, have you found a solution for this.

**Comment by xster** [comment]
https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#initial-route-with-a-cached-engine for Android. https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#route for iOS.
