### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find "libflutter.so" with ArCore

### ISSUE THREAD

**Issue by phucgaoxam** [flutter/flutter#31183]
I'm trying to use ArCore SceneForm in my Flutter app.
The app throws java.lang.UnsatisfiedLinkError in **debug mode** (`flutter run`), and it runs fine when I use command `flutter build apk` then `flutter install apk`.

Here is my Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.4.17-pre.10, on Mac OS X 10.14.3 18D109, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

If you want any information, please let me know.

**Comment by jason-simmons** [comment]
Try using the `--target-platform` flag to specifically select the 32-bit `android-arm` platform.

By default `flutter run` will create an APK targeting ARM64 if the attached device is an ARM64 device.  If the app includes other 32-bit libraries, then the process will be unable to load both the 64-bit version of `libflutter.so` and the 32-bit libraries.  You'll need to build an app containing the 32-bit version of `libflutter.so`

**Comment by BondarenkoStas** [comment]
@phucgaoxam is it still an issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
