### ISSUE TITLE
Add2App does not support AndroidX out of the box

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#31189]
`flutter create -t module -i swift -a kotlin --org [your org prefix] flutter_embedding` does not honor Swift and Kotlin. I'm not sure whether we should, but if we don't, there should be a warning. But then the important thing is that this command creates a module that does not support AndroidX, and we need to check in the code under `.android` and manually convert it to support AndroidX.

**Comment by truongsinh** [comment]
@matthew-carroll

**Comment by truongsinh** [comment]
related to https://github.com/flutter/flutter/issues/23586 and

**Comment by athornz** [comment]
I've got a branch which adds support for AndroidX that you can try out: https://github.com/flutter/flutter/pull/31028

I'm using this in my add2app setup and it's working fine.

**Comment by truongsinh** [comment]
Already thumb up your PR, hopefully @xster will merge soon.

**Comment by jmagman** [comment]
@blasten

**Comment by xster** [comment]
I think this is now fixed in #31028
