### ISSUE TITLE
Add2App register plugin package for Android is verbose

### ISSUE THREAD

**Issue by truongsinh** [flutter/flutter#31188]
As shared in my [Hackernoon article](https://hackernoon.com/how-to-add-flutter-to-your-production-android-app-4b5150de9e44#5880)

Right now, developers can achieve it by themselves by implementing `PluginRegistry` and `PluginRegistry.Registrar`, but it is verbose and not optimized to do so (comparing to the code in `io.flutter.app.FlutterActivity`). I think the framework can have some support to reduce the boilerplate code.

**Comment by truongsinh** [comment]
@matthew-carroll

**Comment by xster** [comment]
The plugin registration on Android is now done by reflection in
