### ISSUE TITLE
Problem with insalling Flutter on Linux

### ISSUE THREAD

**Issue by iManolin** [flutter/flutter#31184]
Hi guys i following get started docs 

i extracted zip file and open flutter folder when i run flutter doctor its not working and

it was working even i'm not change my directory i tested that problem on ubuntu 18.04 and 18.10

please help i can't install flutter on my pc anymore

**Comment by godlessturtle** [comment]
you should add .../flutter/bin to your path in .bash_profile file which located at root directory
