### ISSUE TITLE
Unclear how to import each library we document

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3119]
Love that we have a single list of all libraries you get "out of the box" from Flutter. However, it's not clear how I import them, as I think we have three schemes.

- [x] dart:jni
- [x] dart:ui
- [x] Some come from the flutter package (animation)
- [x] Some come from another package (newton) (solution: inform developers that these libraries are not meant to be used directly)

Any ideas on how to make it more obvious how I import, and thus use, each of these libraries?

**Comment by Hixie** [comment]
One thing we should probably do is put a sample `import` statement in the `library` dartdoc for each one of these. I don't think that's enough; we probably also want to sort the list into categories somehow, but it would definitely help.

**Comment by sethladd** [comment]
Also addressed by https://github.com/flutter/engine/pull/2623
