### ISSUE TITLE
Flutter crashes while creating new app on creating process 2

### ISSUE THREAD

**Issue by Aishwarya1317** [flutter/flutter#31192]
I installed flutter, created env variable also and on android studio I have added plugins though android studio gives an error 
![error](https://user-images.githubusercontent.com/47808347/56280598-2d69b800-6128-11e9-94a1-729fdca08bec.JPG) and on command line it gives below error:
![flutter_error](https://user-images.githubusercontent.com/47808347/56280689-5c802980-6128-11e9-9d89-3fe3c3d4100d.JPG)
Please advise !!

**Comment by zoeyfan** [comment]
I am triaging our bug database, and noticed that this one was opened earlier this year. I wonder with the latest 1.12, is this still repro'ing? @Aishwarya1317

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
