### ISSUE TITLE
[iOS] Paste label tip has wrong position

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#31193]
I am using `CupertinoTextField` and I try to paste text in a field. The device is an iPhone 7.
The tip of the Paste label is a little bit to the left, I expect it to be aligned with the cursor.
Check the screenshots:

![flutter_01](https://user-images.githubusercontent.com/7441453/56283385-3f445e80-611a-11e9-989d-2202aecd3baf.png)
![flutter_02](https://user-images.githubusercontent.com/7441453/56283390-41a6b880-611a-11e9-8829-2546abaa38b6.png)

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.2.1 at /Users/tudor/dev/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Tudor’s iPhone 7 • 6c6f39c58d86256962f6a336f8ebef46f202225e • ios • iOS 12.2

```

**Comment by darshankawar** [comment]
I tested this on latest dev using iPhone 6s and see that the label tip is now displayed / aligned with the cursor.

![IMG-0219](https://user-images.githubusercontent.com/67046386/92396437-9d744600-f142-11ea-9026-2d3299737b3b.jpg)

```
body: Center(
          child: Container(
            width: 200,
            height: 50,
            child: CupertinoTextField(
              placeholder: 'E-mail',
            )
          )
          )
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter: is fully installed. (Channel dev, 1.22.0-9.0.pre, on Mac OS X 10.15.2 19C57, locale
    en-US)
[!] Android toolchain - develop for Android devices: is partially installed; more components are
    available. (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.6)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 3.6)
[✓] Connected device: is fully installed. (5 available)
```

</details>

@tudor07 Can you please confirm if this is still an issue at your end ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
