### ISSUE TITLE
The picture will be jagged when rotation it.

### ISSUE THREAD

**Issue by hanhui6145** [flutter/flutter#31198]
![image](https://user-images.githubusercontent.com/29397969/56294037-d29e8380-615c-11e9-9a38-634a6e860700.png)

**Comment by VladyslavBondarenko** [comment]
Hi @hanhui6145 
does the issue still persist?
could you provide complete minimal reproducible code sample?

**Comment by TahaTesser** [comment]
Hi @hanhui6145 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution
