### ISSUE TITLE
Switch to using the async NDK APIs for hardware key events

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#312]
This will allow applications to say whether or not they handled the event. Right now if they listen for events at all, we assume they are handling all events, so default behaviors for things like back button don't work.

**Comment by collinjackson** [comment]
For example this is what happens when you press the back button in the raw_keyboard.dart example.

![image](https://cloud.githubusercontent.com/assets/394889/11100332/7b36f718-8865-11e5-8a8d-1d4512abdf6d.png)

**Comment by sethladd** [comment]
Curious if this is still planned? I see the referenced PR has been merged.

**Comment by Hixie** [comment]
We're going to close this because we don't have a specific need for it at the moment. If you desire this to be addressed please file a new bug and we'll track your specific need.
