### ISSUE TITLE
copyPixelBuffer  YUV420  error  Failed to create IOSurface image (texture)

### ISSUE THREAD

**Issue by janiokq** [flutter/flutter#31201]
![image](https://user-images.githubusercontent.com/10770735/56299641-07173d00-6167-11e9-8d38-e0dcfaad0b1a.png)
![image](https://user-images.githubusercontent.com/10770735/56299681-18f8e000-6167-11e9-9f5d-4f917a1766c9.png)
My data is normal but the texture creation failed
I don't know why anyone can help me？

**Comment by janiokq** [comment]
fDisableGpuYUVConversion？？？？？

**Comment by goderbauer** [comment]
You'll have to provide more information. What were you doing when you received the error? What does your Flutter code look like? Do you have a minimal sample that shows the failure?

**Comment by janiokq** [comment]
![image](https://user-images.githubusercontent.com/10770735/56326563-1323ee80-61a9-11e9-88fd-5ebf749c8616.png)
Video has sound but no pictures
My custom player USES the ijkplay video format converted from yuv420 to CVPixelBufferRef
Everything else is fine

**Comment by loongliu** [comment]
@janiokq `copyPixelBuffer` requires format BGRA.

**Comment by BondarenkoStas** [comment]
@janiokq did you manage to fix it?

**Comment by janiokq** [comment]
@BondarenkoStas   Yes, I fixed the problem myself
