### ISSUE TITLE
Google Maps are not showing using google_maps_flutter plugin

### ISSUE THREAD

**Issue by sunchit17** [flutter/flutter#31200]

**Comment by sunchit17** [comment]
Only a blank screen appears when I try to load the Google Maps widget

**Comment by goderbauer** [comment]
You'll have to provide more information. What does your Flutter code look like? Do you have a minimal sample that shows the failure?

**Comment by sunchit17** [comment]
Flutter Code:


import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static final CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: Text('To the lake!'),
        icon: Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
}

**Comment by GuiOliveira1995** [comment]
I just followed google_maps_flutter tutorial on GitHub and got the same issue. Blank screen with take me to the lake at the right bottom side.

**Comment by PureW** [comment]
Same here, I followed setup example on https://pub.dartlang.org/packages/google_maps_flutter#-readme-tab-

and with `flutter run` on my Pixel 3, I get a white page with a "Take me to the lake" button in the corner. I'm using an unrestricted API-key.

**Comment by Seinroboter** [comment]
> ~Same here, I followed setup example on https://pub.dartlang.org/packages/google_maps_flutter#-readme-tab-~
> 
> EDIT: I had entered my API-key incorrectly. Fixing that gives me a beautiful map.

Can confirm this solves the issue

**Comment by TahaTesser** [comment]
Hi @sunchit17 
Given this [comment](https://github.com/flutter/flutter/issues/31200#issuecomment-487289770) solution and  [confirmatin](https://github.com/flutter/flutter/issues/31200#issuecomment-581187941)

Please try the solution
If you're still experiencing this issue after trying the solution, please create a new issue and provide necessary details
Thank you

**Comment by anurag-176** [comment]
in my case, I had put the API key meta data above the opening "application" tag
So my issue resolved my placing it just above the "activity" opening tag
