### ISSUE TITLE
[Material] Add support for Badges on `BottomNavigationBarItem`s

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#31209]
The Material spec defines badges that can appear as notifications inside of the Bottom Navigation Bar.

![mio-design_assets_0B6xUSjjSulxcaVpEMk5tZ2RGZ3c_bottomnav-badging-1](https://user-images.githubusercontent.com/4229329/56311219-7b2bf380-611b-11e9-992f-e1a2dce2023c.png)

https://material.io/design/components/bottom-navigation.html#behavior

We should support these in our `BottomNavigationBarItem` widgets.

**Comment by Li-Zepeng** [comment]
是的，虽然icon属性可以解决这个问题，但更希望widget可以直接支持

**Comment by Li-Zepeng** [comment]
class BadgeWidget extends StatefulWidget {
  final Widget icon;
  int num;

  BadgeWidget({
    @required this.icon,
    this.num,
  });

  @override
  State<StatefulWidget> createState() => BadgeWidgetState();
}

class BadgeWidgetState extends State<BadgeWidget> {
  @override
  Widget build(BuildContext context) => Stack(
        children: <Widget>[
          Container(
            child: widget.icon,
            height: 24,
            width: 36,
          ),
          widget.num == 0
              ? Container(
                  height: 14,
                  width: 14,
                )
              : Container(
                  height: 14,
                  width: 14,
                  decoration: BoxDecoration(
                    color: Colors.red,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  constraints: BoxConstraints(
                    minWidth: 14,
                    minHeight: 14,
                  ),
                  child: Center(
                    child: Text(
                      widget.num > 99 ? '99+' : widget.num.toString(),
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 8,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                )
        ],
        alignment: Alignment.topRight,
        overflow: Overflow.visible,
      );

  updateNum(int num) {
    setState(() {
      widget.num = num;
    });
  }
}

**Comment by Li-Zepeng** [comment]
BottomNavigationBarItem(
        icon: badge,
        title: Text('购物车'),
      ),

**Comment by Li-Zepeng** [comment]
var badge = BadgeWidget(
    icon: Icon(Icons.shopping_cart),
    num: 0,
  );

**Comment by HansMuller** [comment]
@Li-Zepeng 
This is the "Google Translate" english translation of https://github.com/flutter/flutter/issues/31209#issuecomment-510786256: 

> Yes, although the icon property can solve this problem, I hope the widget can directly support it

**Comment by willlarche** [comment]
Sync with design.

**Comment by clocksmith** [comment]
The same style badges are also needed for the Navigation Rail

**Comment by bugrevealingbme** [comment]
Any update?
