### ISSUE TITLE
flutter_gallery_ios32__transition_perf 90th_percentile_frame_rasterizer_time_millis regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#31203]
flutter_gallery_ios32__transition_perf 90th_percentile_frame_rasterizer_time_millis regressed probably with https://github.com/flutter/flutter/commit/81913321f3d3c755016a2bdac0eaea382f789208 which contains the skia roll https://github.com/flutter/engine/pull/8590.

**Comment by Hixie** [comment]
I rebaselined the test so we don't miss future regressions, but this hasn't been resolved as of today.
My understanding is that we looked into this but couldn't reproduce it locally, though the devicelab machine still shows it?
Have we tried literally using the devicelab hardware?

**Comment by cbracken** [comment]
@iskakaushik will take a look at this. We have another iPhone 4S that we can dig up to test locally.

**Comment by liyuqian** [comment]
Kaushik just told me that I was using an iPhone 5 to do the test and that's probably why I can't reproduce the regression. Will do the test again once we get a real iPhone 4S device.

**Comment by iskakaushik** [comment]
Upon bisecting, looks like https://github.com/google/skia/commit/c0d79e525fbc7a57da366afc6f662c7d288a0774 caused the regression. https://github.com/flutter/engine/pull/8590 is the corresponding skia roll.

Before that commit:
```
run number 1
19.271
run number 2
17.188
run number 3
18.023
```

With that commit:
```
run number 1
21.456
run number 2
24.528
run number 3
23.012
```

This was run on iPhone 4S.

**Comment by liyuqian** [comment]
According to @bsalomon, this might be due to image shader compilations. We'll try that to apply a semi-transparent and a fully-opaque image shader warm-up.

**Comment by cbracken** [comment]
@iskakaushik @liyuqian any further updates on this?

**Comment by liyuqian** [comment]
I'm going to get an iPhone 4S to try a solution for this issue.

**Comment by cbracken** [comment]
@liyuqian we've got an iPhone 4S when someone's ready to take a look. I assume this hasn't been looked at yet, given that this is a relatively low priority relative to many of the other perf issues/regressions you're looking at.

**Comment by liyuqian** [comment]
I think I've tried something on iPhone 4S several weeks ago but didn't get something promising. Now my plan is to work on https://github.com/flutter/flutter/issues/40686 so these can be easily fixed using the SkSL precompile. Unassign  myself to reflect hat I'm no longer working on this.

**Comment by Hixie** [comment]
Since this appears to have been abandoned and we never determined the cause, I'm going to close it, as it seems no longer actionable.

**Comment by liyuqian** [comment]
As of 08/19/2020, this metric has returned back to the 16-19 ms range before the regression (see comparison in https://github.com/flutter/flutter/issues/31203#issuecomment-488511932)
