### ISSUE TITLE
url_launcher 5.0.2 iOS canLaunch(url): Unhandled Exception: Could not launch

### ISSUE THREAD

**Issue by palmCoconuts** [flutter/flutter#31219]
**Problem:**
I'm running an app that makes a phone call when a user presses a button. In android phones (simulator or native) this code works. For the iPhone simulator, following print line is false for iPhones and true for Android phones.
```
print(canLaunch(url).then((bool){
      print('>>>>>>>>>>>>>>>>>>>>>>>');
      print(bool); 
```
Similar to this issue [#28885](https://github.com/flutter/flutter/issues/28885)
Followed this answer in [This app is not allowed to query for scheme tel](https://stackoverflow.com/questions/48559620/this-app-is-not-allowed-to-query-for-scheme-tel) to add LSApplicationQueriesSchemes in info.plist. 

Also I verified if other schemas worked. I check if the http schema worked by opening a new webpage on the iOS simulator `(http://flutter.io).` It does open in the iPhone simulator. 

At this point, It would be good to know if this error is a result of a configuration error or if this error is because the iPhone simulator can't run the tell schema?

**xCode Simulator Reports this error:**

> "The operation couldn’t be completed. (OSStatus error -10814.)"

**Android iPhone Simulator Reports this Error**

> flutter: >>>>>>>>>>>>>>>>>>>>>>>
> flutter: false
> [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Could not launch tel:1-408-555-5555
> #0      PhoneMethods.callPhoneApp (package:../url.dart:15:7)
> <asynchronous suspension>
> #1      _IncidentsState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:...:139:66)
> #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
> #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
> #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
> #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:246:9)
> #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
> #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
> #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73<…>

**Code**

```
import 'package:url_launcher/url_launcher.dart';

class PhoneMethods {
  callPhoneApp({String number}) async {
    String url = 'tel:1-408-555-5555'; 
    print(canLaunch(url).then((bool){
      print('>>>>>>>>>>>>>>>>>>>>>>>');
      print(bool);
    }));
    if (await canLaunch(url)) {
      await launch(url);
    } else {

      throw 'Could not launch $url';
    }

  }
}
```

**flutter run --verbose**

> `[✓] Flutter (Channel master, v1.4.8-pre.24, on Mac OS X 10.14.4 18E226, locale
>     en-US)
>     • Flutter version 1.4.8-pre.24 at
>       /.../
>     • Framework revision 976223533d (2 weeks ago), 2019-03-31 07:38:41 -0400
>     • Engine revision f3ec767458
>     • Dart version 2.2.1 (build 2.2.1-dev.2.1 None)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /...
>     • Android NDK location not configured (optional; useful for native profiling
>       support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1248-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.2, Build version 10E125
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.6.0
> 
> [✓] Android Studio (version 3.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 34.0.1
>     • Dart plugin version 182.5215
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1248-b01)
> 
> [✓] Connected device (3 available)
>     • SAMSUNG SM G930A          • 89c1a73c                             •
>       android-arm64 • Android 7.0 (API 24)
>     • Android SDK built for x86 • emulator-5554                        •
>       android-x86   • Android P (API 27) (emulator)
>     • iPhone Xʀ                 • A48D9B48-693D-4E0F-A791-FEB5078EF0AC • ios
>       • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
> 
> • No issues found!

**Comment by palmCoconuts** [comment]
The simulator can't simulate making a phone call like Android does. 
As long as you following the iOS instructions to configure info.plist and correctly use the code above this will work on a native iOS device.

**Comment by alimcevik** [comment]
**You can add:**

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`
