### ISSUE TITLE
an error with local_auth plugin flutter

### ISSUE THREAD

**Issue by Jesulonimi21** [flutter/flutter#31215]
i tried using local_auth plugin on infinix hot 4  version 6 that had a fingerprint scanner and i kept on getting the error finger print scanner not detected and i later tried the same code on a tecno k7  which was using  version 7 of android and it worked

**Comment by TahaTesser** [comment]
Hi @Jesulonimi21 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
