### ISSUE TITLE
[webview_flutter] initialRequest instead on initialUrl

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#31223]
Currently when you initialize a `WebView` in flutter, you have an option of passing in an `initialUrl`. We wish to make it `initialRequest`. This allows us to specify more parameters that are considered part of making the request, for example headers (to address https://github.com/flutter/flutter/issues/25831), `Cache-Control`, (potentially adding a `RequestBody` field to make `POST` requests).

**Comment by drkaleem** [comment]
Yes this will be much preferred, as it would give better control on the url begin loaded

**Comment by rxPrachi** [comment]
That Sounds Great !!! 👍🏻
When can we able to use 'initialRequest'?

**Comment by stuartmorgan** [comment]
Closing as obsolete; `initialUrl` was removed in v4.
