### ISSUE TITLE
I need to customize placeholder text alignment for CupertinoTextField

### ISSUE THREAD

**Issue by chenxianqi** [flutter/flutter#31234]
hi Everybody
Can you add it to the list?
Now it's always on the left. 
Its direction should be based on the direction of Cupertino TextField.
Thanks
such as：
See this[#28556](https://github.com/flutter/flutter/pull/28556)
```
 // In the middle part, stack the placeholder on top of the main EditableText
        // if needed.
        if (widget.placeholder != null && text.text.isEmpty) {
          stackChildren.add(
            SizedBox(
              width: double.infinity,
              child: Padding(
                padding: widget.padding,
                child: Text(
                  widget.placeholder,
                  maxLines: 1,
                  textAlign: widget.textAlign,
                  overflow: TextOverflow.ellipsis,
                  style: placeholderStyle
                ),
              ),
            ),
          );
        }
```

[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.4.9-hotfix.1 at /Users/chenxianqi/flutter
    • Framework revision 88fa7ea403 (6 days ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chenxianqi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/chenxianqi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.6156.11

[✓] VS Code (version 1.32.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

**Comment by adriancmurray** [comment]
dupe of https://github.com/flutter/flutter/issues/27946

**Comment by LongCatIsLooong** [comment]
closing in favor of #27946
