### ISSUE TITLE
Running demo app on Nexus 4 fails

### ISSUE THREAD

**Issue by kasperl** [flutter/flutter#3124]
## Steps to Reproduce

I followed the 'Getting Started with Flutter' guide and tried to run the demo app on my Nexus 4. It fails. The phone may have been busy installing updates when I first tried to run.
## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/kasperl/Flutter/flutter
    • Framework revision d5deea4 (8 days ago), engine revision ce3b454

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/kasperl/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)

[ ] iOS toolchain - develop for iOS devices
    x XCode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    x Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1
## Logs and Crash Reports

First I got this:

```
kasperl-macbookpro2:demo kasperl$ flutter run
Building APK...
Warning: signing the APK using the debug keystore.
Generated APK to build/app.apk.
Installing app.apk on device.
Running lib/main.dart on Nexus 4...
failed to read ID_DONE response for 'build/app.flx': Connection reset by peer
21167 KB/s (631289 bytes in 0.029s)

Oops; flutter has exited unexpectedly: "Exit code 1 from: /Users/kasperl/Library/Android/sdk/platform-tools/adb -s 04fdfa1b59543805 push build/app.flx /data/local/tmp/dev.flx"

Crash report written to flutter_01.log.
Please let us know at https://github.com/flutter/flutter/issues!
```

Subsequent attempts lead to this output:

```
kasperl-macbookpro2:demo kasperl$ flutter run
Installing app.apk on device.
Running lib/main.dart on Nexus 4...
Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=com.yourcompany.demo/org.domokit.sky.shell.SkyActivity (has extras) }
Error type 3
Error: Activity class {com.yourcompany.demo/org.domokit.sky.shell.SkyActivity} does not exist.
Error running application on Nexus 4.
```

**Comment by kasperl** [comment]
After installing all the updates is done, I can successfully run the demo app on the Nexus 4.

**Comment by kasperl** [comment]
[flutter_01.log.txt](https://github.com/flutter/flutter/files/205915/flutter_01.log.txt)

**Comment by sethladd** [comment]
I wonder if `flutter doctor` should try to report on the phone. Maybe it can detect old versions of the OS?

Also, do you happen to remember what version of the OS you had before the updates?

Thanks for the report!

**Comment by kasperl** [comment]
I don't think the updates fixed anything. Maybe ```flutter run```has issues installing the APK while someone else is holding onto a lock on some app database on the device.

**Comment by eseidelGoogle** [comment]
The first log looks like adb install failed, possibly due to an interrupted connection with the device.  The second log looks like the hash we install on the device made us think we had a valid APK there but we didn't.

However, I just checked the code, we shouldn't write the hash to the device unless the install succeeded w/o error:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L184

In the flutter_01.log.txt you just uploaded, it looks like adb push is failing, that's only used as part of `flutter run` for pushing the flx to the device:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L221

I'm starting to suspect your USB cable may be bad/dying.  I've had several fail intermittently over the last few years. :(

@devoncarew may have more thoughts.  I'm not sure what we should change here.

**Comment by sethladd** [comment]
I'm also seeing the same "error type 3" in https://github.com/flutter/flutter/issues/3128

**Comment by kasperl** [comment]
I just tried running again. Everything was fine. Then I started installing app updates through Google Play and while my Nexus 4 was upgrading Gmail and some other app, I got all sorts of errors trying to run using ```flutter run```. Once the upgrading through Google Play was done, everything was fine again. 

```
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
Device 04fdfa1b59543805 is not authorized.
You might need to check your device for an authorization dialog.
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
Unexpected failure parsing device information from adb output:
04fdfa1b59543805       offline usb:337641472X product:occam model:Nexus_4 device:mako
Please report a bug at https://github.com/flutter/flutter/issues/new
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
Device 04fdfa1b59543805 is not authorized.
You might need to check your device for an authorization dialog.
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
error: device '04fdfa1b59543805' not found

Oops; flutter has exited unexpectedly: "Exit code 255 from: /Users/kasperl/Library/Android/sdk/platform-tools/adb -s 04fdfa1b59543805 shell pm path com.yourcompany.demo"

Crash report written to flutter_01.log.
Please let us know at https://github.com/flutter/flutter/issues!
kasperl-macbookpro2:demo kasperl$ flutter run
error: device '04fdfa1b59543805' not found

Oops; flutter has exited unexpectedly: "Exit code 255 from: /Users/kasperl/Library/Android/sdk/platform-tools/adb -s 04fdfa1b59543805 shell pm path com.yourcompany.demo"

Crash report written to flutter_02.log.
Please let us know at https://github.com/flutter/flutter/issues!
kasperl-macbookpro2:demo kasperl$ flutter run
No connected devices.
kasperl-macbookpro2:demo kasperl$ flutter run
error: device '04fdfa1b59543805' not found
Unexpected failure from adb: Exit code 255 from: /Users/kasperl/Library/Android/sdk/platform-tools/adb -s 04fdfa1b59543805 shell getprop ro.build.version.sdk
Running lib/main.dart on Nexus 4...
error: device '04fdfa1b59543805' not found
Unexpected failure from adb: Exit code 255 from: /Users/kasperl/Library/Android/sdk/platform-tools/adb -s 04fdfa1b59543805 shell getprop ro.build.version.sdk
Error running application on Nexus 4.
```

**Comment by kasperl** [comment]
[flutter_01.log.txt](https://github.com/flutter/flutter/files/207884/flutter_01.log.txt)
[flutter_02.log.txt](https://github.com/flutter/flutter/files/207885/flutter_02.log.txt)

**Comment by eseidelGoogle** [comment]
This may sound silly, but I honestly would try a different USB cable for a day and see if that helps at all.  Not sure we can blame all problems there, but it is one variable.  I've had several fail in strange ways including spotty connectivity.

**Comment by sethladd** [comment]
What's the resolution for this issue? Still valid?

**Comment by raju-bitter** [comment]
I've been testing with my Nexus 4 over the past week, and never ran into this situation. I didn't have my Nexus 4 connected/powered up for more than 15 months, and it started getting updates. Tried `flutter run` multiple times, and it always worked fine.

**Comment by sethladd** [comment]
Thanks. I think we can close for now.
