### ISSUE TITLE
Flutter plugin is not supported by Android Studio 3.4 

### ISSUE THREAD

**Issue by RobertApikyan** [flutter/flutter#31246]
When it will be supported by studio 3.4 , and switching back to studio 3.3 is the only option for now

**Comment by iqbalmineraltown** [comment]
Did you update your plugins too?
I just updated my AS to 3.4 some hours ago and I'm doing fine

**Comment by potato16** [comment]
i have the same problem.

**Comment by RobertApikyan** [comment]
![image](https://user-images.githubusercontent.com/17802092/56347262-f69dab80-61d4-11e9-8285-ede35154509d.png)
That is strange, because what it displays in my case in plugins section

**Comment by RobertApikyan** [comment]
![image](https://user-images.githubusercontent.com/17802092/56347459-57c57f00-61d5-11e9-9eb7-f15bee73917f.png)

**Comment by RobertApikyan** [comment]
Yes your right, Flutter plugin update is available as well in updates section, I didn't notice it. Problem is solved 
![image](https://user-images.githubusercontent.com/17802092/56347636-c276ba80-61d5-11e9-9068-e3fcec9b8513.png)

**Comment by sunxlfred** [comment]
i have the same problem, but there's nothing in "Updates"
![](https://raw.githubusercontent.com/sunxlfred/RES/master/dart%20bug.png)
![](https://raw.githubusercontent.com/sunxlfred/RES/master/dart2.png)
![](https://raw.githubusercontent.com/sunxlfred/RES/master/dart3.png)

**Comment by RobertApikyan** [comment]
I do not receive this error after making update on mac book, so the only solution in mind is to unistall & intsall the "Dart" and "Flutter" plugins

**Comment by potato16** [comment]
after uninstall flutter plugin, I can't install it back. 
![image](https://user-images.githubusercontent.com/8458733/56370358-45733180-6225-11e9-8726-26f1de8b216d.png)

**Comment by RobertApikyan** [comment]
hmm.. I'm guessing you have already tried "invalidate caches and restart", not sure about this but you can try to reinstall whole environment, like android studio + flutter stuff

**Comment by sunxlfred** [comment]
> hmm.. I'm guessing you have already tried "invalidate caches and restart", not sure about this but you can try to reinstall whole environment, like android studio + flutter stuff

"flutter doctor" also useless

**Comment by sunxlfred** [comment]
> after uninstall flutter plugin, I can't install it back.
> ![image](https://user-images.githubusercontent.com/8458733/56370358-45733180-6225-11e9-8726-26f1de8b216d.png)

I solved this problem temporarily.  (before update to studio 3.4, my environment is studio 3.0.1 + flutter is running ok)

1. install a vpn environment, 
2. click the nut and click "Http Proxy Settings", set the socks
3. "invalidate caches and restart"
4. "Updates" page can update the flutter

ps: but I back to the studio 3.0.1,  the "Instant run" bug reappeared. And in studio 3.4, I haven't open the "Instant run" mode.

![](https://raw.githubusercontent.com/sunxlfred/RES/master/dart4.png)

**Comment by rahulk8** [comment]
> 
> 
> I do not receive this error after making update on mac book, so the only solution in mind is to unistall & intsall the "Dart" and "Flutter" plugins

Or possible u can update plugins and restart android studio.that worked for me
