### ISSUE TITLE
set up a redirect to the issue tracker

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3125]
It would be useful to have a redirect from flutter.io/bugs to https://github.com/flutter/flutter/issues.

**Comment by sethladd** [comment]
We can do this with a configuration file in firebase hosting. Should be fairly straightforward. https://www.firebase.com/docs/hosting/guide/url-redirects-rewrites.html

**Comment by sethladd** [comment]
We did this! :) . https://flutter.io/issues
