### ISSUE TITLE
[Instance of 'UserDetails', Instance of 'UserDetails']

### ISSUE THREAD

**Issue by BashardinhoGitHube** [flutter/flutter#31252]
Hey there!
I'm working on a project, and i need to get data as Map first then as *list like the following:
class UserDetails {
  final int id;
   String name, phone, profileUrl;

  UserDetails(
      {this.id, this.name, this.phone, this.profileUrl = '', });

  factory UserDetails.fromJson(Map<String, dynamic> json) {
    return new UserDetails (
      name: json['name'] ,
      phone: json['phon']
    );
  }
}

*And getting data as List:
List<UserDetails> _userDetails =new List();

The problem when i try to print the list the console gives:

[Instance of 'UserDetails', Instance of 'UserDetails']

Any help?

**Comment by superciccio** [comment]
you to override the `toString` method

**Comment by jonahwilliams** [comment]
For questions like this about Dart and Flutter, please prefer to use one of the channels at https://flutter.dev/community over Github issues.

**Comment by BashardinhoGitHube** [comment]
> you have to override the `toString` method

would you please direct me?
