### ISSUE TITLE
  how to Add《web_socket_channel: 1.0.12 &   quickclient: 0.1.0》

### ISSUE THREAD

**Issue by xcmg** [flutter/flutter#31253]
In my app ,I want to use package of《web_socket_channel: 1.0.12 ，quickclient: 0.1.0》as a library.
1. In  <pubspec.yaml> add   
dependencies:
  web_socket_channel: 1.0.12
  quickclient: 0.1.0

2.Install it
$ flutter packages get

it's running，but  it's  fail！

**Comment by jonahwilliams** [comment]
>it's running，but it's fail!

You did not post how it failed, so it is unlikely that someone can help you. It seems like the formatting might be off?

Something like:
```
dependencies:
  web_socket_channel: 1.0.12
  quickclient: 0.1.0
```
