### ISSUE TITLE
flutter build ios --profile error with  swift project

### ISSUE THREAD

**Issue by yataoSang** [flutter/flutter#31256]
I am creating a new project, then compiling my project with flutter build ios --profile, reporting the following error
![image](https://user-images.githubusercontent.com/19302010/56359102-2ff50c00-6213-11e9-9a12-42faf16ff416.png)

How can I solve it?

**Comment by godlessturtle** [comment]
did you give a chance for `flutter clean`?

**Comment by BondarenkoStas** [comment]
@yataoSang did you manage to fix it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
