### ISSUE TITLE
Windows shell should not open a console in Release

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#31268]
This is something we'll want to address before making a `flutter create` template.

From my preliminary research on this, it seems like what we probably want to do is use the WINDOWS subsystem rather than the CONSOLE subsystem, then AllocConsole in Debug builds.

**Comment by Tokenyet** [comment]
I saw It add in milestone! But If someone need a workaround, I found out a simple way to do it.

1. Open flutter_embedder_example.cpp
2. Add the following code at certain line (I added after the line of plugin loaded):
```
::ShowWindow(::GetConsoleWindow(), SW_HIDE);
```

This would popup up command in a second, but is going to be disappeared finally.

**Comment by gnf** [comment]
adjust linker option:  /subsystem: windows in Release Mode. but I think we need resolve engine release build first. please assign this issuse to me.

**Comment by stuartmorgan** [comment]
> I think we need resolve engine release build first

Isn't this an exe-level setting? The runner executable already has distinct debug and release modes, it's only the Flutter library that's currently debug regardless of the build mode.

**Comment by shoryukenn** [comment]
@stuartmorgan , This modification cannot be mapped to flutter/engine. It only exists in flutter-desktop-embedding/example. What is our migration plan for example/runner?

**Comment by shoryukenn** [comment]
PR: https://github.com/google/flutter-desktop-embedding/pull/511

**Comment by stuartmorgan** [comment]
Fixed by the above PR.
