### ISSUE TITLE
Crashing during hot reload when --track-widget-creation is enabled

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#31274]
If I run a macOS Flutter application in VS Code with the new desktop `flutter run` functionality, hot reload crashes the target app; some searching based on the stack turned up https://github.com/Dart-Code/Dart-Code/issues/1133 and related bugs, which it turned out is the culprit here as well (disabling widget creation tracking fixes the problem).

@DanTup @devoncarew can you provide some more context on what the underlying fix involved? Is there per-platform support that needs to be wired up for this feature in Flutter?

(Note: I haven't tried yet on Linux and Windows; it may happen there as well.)

**Comment by stuartmorgan** [comment]
@jonahwilliams You mentioned in email that we need a flag at creation time (is that 'build bundle', or the compilation?); is that something that should be done unconditionally in debug builds?

**Comment by jonahwilliams** [comment]
We should pass whether track-widget-creation is enabled through to the build script, and then that should be passed to the bundle build

**Comment by stuartmorgan** [comment]
I'll need to solve the problem of passing things into the build from each platform's script before I can do that, but I need to do that for FLUTTER_ROOT anyway.

**Comment by jonahwilliams** [comment]
Even if we build with the right flag (https://github.com/flutter/flutter/pull/31329), it still looks like the engine is using the wrong dill file.

**Comment by stuartmorgan** [comment]
Are you sure the flag is being set? I haven't reviewed in detail yet, but it didn't look like you'd wired up loading the generated xcconfig in the project, which would mean it wouldn't ever actually know to set the flag.

I can add that logic next week.
