### ISSUE TITLE
Adding engine unit testing for iOS.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#31288]
We currently only have a few engine unit tests in ObjC that test some channels implementation. That works because the channels implementation can be run on the Mac with a GTest harness.

There are currently 2 ways that we can do this:

**1. Create a different GTest harness for iOS.** 

    Pros: 
        We have already been using GTest in the Engine code extensively, adding another GTest harness is relatively easier to maintain.
   
    Cons: 
        GTest for iOS might not be too straightforward for people who are familiar with writing iOS test in XCTest.

**2. Using XCTest for iOS**

    Pros: 
        Standard way to test iOS. Easier to people who are familiar with standard iOS development.
        Better Xcode integration.

    Cons:
        Adding another dependency to the Engine, can be a litter harder to maintain.
    
CC @chinmaygarde

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/9388
