### ISSUE TITLE
iOS Textfield caret "start handle"'s top balloon does not allow drag

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#31286]
With both the latest stable and beta versions of Flutter (1.2.1-stable and 1.4.9-hotfix.1), the iOS caret "handles" that allow to expand/shrink text selections on TextField widgets don't allow to drag the start handle when pressing and dragging the balloon at the top of the Start handle.

This can be reproduced with a simple app that just has a TextField widget.

The issue is the Gesture Detector widget is aligned with the top of the text field's text widget, while the caret handle is transformed to be higher. The GestureDetector should be transformed too.

**Comment by dannyvalentesonos** [comment]
![sample_app_bad_gesture_detector_handle](https://user-images.githubusercontent.com/40898687/56393628-07fdac80-6203-11e9-91fd-f806fc4e2d1e.png)
![sample_app_bad_gesture_detector](https://user-images.githubusercontent.com/40898687/56393632-0cc26080-6203-11e9-93d0-8d3d068aff9e.png)

**Comment by justinmc** [comment]
Another good catch.  This seems unrelated to https://github.com/flutter/flutter/issues/31287 for the record.

**Comment by xster** [comment]
Adding today tag to this one too. We need to expand tests on this one too.

**Comment by xster** [comment]
Ah, tested a bit. The issue isn't that it's un-draggable but the touch targets are off. We should fix this but removing today tag for now.

**Comment by justinmc** [comment]
I'm looking into this. When the handle gets rotated to point to the selection, it swings outside of its GestureDetector.

I should check if fixing this can also take care of https://github.com/flutter/flutter/issues/23432 or if that's separate.

**Comment by justinmc** [comment]
I might put in a slightly bigger fix that gets us moving in the right direction for proper selection behavior.  I don't see a quick fix here that isn't hacky, and it looks like this bug has been around at least since January.
