### ISSUE TITLE
IOS move map to location the map will not center on location but will move location to upper left corner

### ISSUE THREAD

**Issue by buttonsquared** [flutter/flutter#31285]
If I move to a lat lon position the position will be in the upper left corner.  Or if I put a marker on the map then I click on it the map will put the marker in the upper left where I can't even see it when it should put it in the center.   It's basically unusable in IOS.

**Comment by TahaTesser** [comment]
Hi @buttonsquared 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
