### ISSUE TITLE
How can I measure child size change parent maxHeight? Thanks for help

### ISSUE THREAD

**Issue by cgalaxy** [flutter/flutter#31298]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by cgalaxy** [comment]
I use SingleChildRenderObjectWidget nest  CustomMultiChildLayout. 
Because CustomMultiChildLayout can get size of each child ,by method of " layoutChild(id, BoxConstraints.loose(size)); " . SingleChildRenderObjectWidget can set view size by method of  performLayout() set "  size = Size(constraints.maxWidth, 20); "
But will report  EXCEPTION 
I/flutter (14905): The following assertion was thrown during performLayout():
I/flutter (14905): RenderVote does not meet its constraints.
I/flutter (14905): Constraints: BoxConstraints(w=360.0, h=692.0)
I/flutter (14905): Size: Size(360.0, 20.0)

What my Requirement is get child of second height  ,default show two children ,then click more button show all children with animation , before  come true by Android dode .

Thanks for help!

**Comment by csells** [comment]
This is a question best asked on Stackoverflow.
