### ISSUE TITLE
Launching app on iOS Simulator intermittently gets stuck waiting for observatory port

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3129]
## Steps to Reproduce

Attempt to launch a Flutter app on an iOS Simulator using either `flutter start` or `flutter drive`. _Sometimes_ the result is:

```
  10 ms • Waiting for observatory port to be available...
  21 ms • tail -n +0 -F /Users/USER/Library/Logs/CoreSimulator/SIMULATOR_ID/system.log
```

This happened on `dea7c347181642c101abfc9fc2664e686659e135

/cc @johnmccutchan @chinmaygarde

**Comment by yjbanov** [comment]
More info:

The app actually starts. I am starting it with paused isolates on start. I can connect to observatory from the browser, unpause the isolate and then everything is great. This unblocks manual testing, but it doesn't for automated driver tests.

**Comment by yjbanov** [comment]
Another observation: 98% of my `system.log` file starts filled with null bytes ( `0x00`), which causes `less` to think it's binary (although `tail` seems to be fine).

**Comment by chinmaygarde** [comment]
We don't write to that log file, so if the null bytes cause any issue, I guess it is OK. Will investigate the hang though. Seems like we had a similar timing issue earlier.

**Comment by yjbanov** [comment]
I'm going to close as obsolete. It hasn't happened on the buildbot for a long while. Will reopen if it happens again.
