### ISSUE TITLE
[Question] How to properly handle PluginRegistry.ActivityResultListener

### ISSUE THREAD

**Issue by Sh1d0w** [flutter/flutter#31301]
When developing flutter plugins, on Android if the plugin needs to implement onActivityResult listener, we register it via PluginRegistry.ActivityResultListener. You define a requestCode in your plugin that you trigger the intent and that requestCode is then sent to the onActivityResult callback when the intent finishes.

My question is: since multiple flutter plugins can register onActivityResult via PluginRegistry.ActivityResultListener, how we can avoid collision between request codes? I mean two plugins request codes can easily be the same, which will result both plugin methods triggered? And if those two methods expect different shape of data it may cause NPE.

**Comment by frankxzx** [comment]
same question

**Comment by Sh1d0w** [comment]
@zoechi Can I get some official statement on this please, it's been a while since I've opened this issue.

**Comment by xster** [comment]
The v1 android embedding has generally been deprecated. See https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html and https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration.
