### ISSUE TITLE
How to correctly add a flutter project to a version control system such as git?

### ISSUE THREAD

**Issue by AzarouAmine** [flutter/flutter#31307]
I'm working on a Flutter school project and we need a version control system. What are the correct steps to follow to create a GitHub repository for a flutter projects? Including files to include in the repo and files to ignore.

**Comment by daniilguit** [comment]
`flutter create` generates project with proper .gitignore files which is similar to what flutter has in it's own repo: https://github.com/flutter/flutter/blob/master/.gitignore
