### ISSUE TITLE
Wrong rendering when positioning with fractional values

### ISSUE THREAD

**Issue by daniilguit** [flutter/flutter#31305]
On Android and iOS on 1.4.19 and stable version.

Elements with fractional positions are wrongly rendered on the edges which produces really annoying artifacts during animations when there are overlapping or strongly connected widgets of different colors, example:
* `Scaffold` with white background and `AppBar` of green color will produce artifact white line at the top of scaffold when animating from bottom to top (PageRoute with fullscreenDialog: true)
* `Scaffold` with white background and `AppBar` of green + AppBar's bottom green container will produce glitch line with scaffold's background color in between them during vertical animations.
* `TabBarView` with background green on a white background will produce vertical white line glitch during animation at the edges of tabs.

Smallest example that illustrates this issue:
We have two exact sized `Container` placed on each other: green on the bottom and white on the front with white scaffold background. This should produce just white screen because white container is on the top. This is what we see when they are positioned with same integral values but when they are positioned with same fractional values we can see horizontal lines on the top and bottom of containers (Device: Mi MIX 2S, same artifacts had with Samsung Galaxy 7, iPhone 5s, iPhone 10):

![Inkedflutterbug_LI](https://user-images.githubusercontent.com/231284/56422826-13f47780-62b2-11e9-8b1b-6b90763e544d.jpg)

Code that generates this image:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Stack(
        children: [
          // Integral positions rendered properly
          Positioned(
            left: 200,
            top: 200,
            child: Container(
              width: 100,
              height: 100,
              color: Colors.blue,
            ),
          ),
          Positioned(
            left: 200,
            top: 200,
            child: Container(
              width: 100,
              height: 100,
              color: Colors.white,
            ),
          ),
          // Fractional positions results in artifact on top and bottom
          Positioned(
            left: 200,
            top: 400.5,
            child: Container(
              width: 100,
              height: 100,
              color: Colors.blue,
            ),
          ),
          Positioned(
            left: 200,
            top: 400.5,
            child: Container(
              width: 100,
              height: 100,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );
  }
}
```
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.4.19, on Microsoft Windows [Version 10.0.16299.125], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code, 64-bit edition (version 1.33.0)
[√] Connected device (1 available)
```

**Comment by daniilguit** [comment]
@HansMuller I don't think it's material related, it looks like it is behaviour of Skia,
Following code that does the same white-rect-over-blue-rect thing using Canvas has the same issue:

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: CustomPaint(
        size: Size(double.infinity, double.infinity),
        painter: MyPainter(),
      ),
    );
  }
}

class MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Rect rect = Rect.fromLTRB(50.5, 50.5, 100.5, 100.5);
    canvas.drawRect(rect, Paint()..color = Colors.blue);
    canvas.drawRect(rect, Paint()..color = Colors.white);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}

**Comment by daniilguit** [comment]
If I disable aliasing, the results are correct (complete white background):
```
    paint.isAntiAlias = false;
    canvas.drawRect(rect, paint..color = Colors.blue);
    canvas.drawRect(rect, paint..color = Colors.white);
```

**Comment by HansMuller** [comment]
@daniilguit I only tagged this "material" because the description referred to AppBar and Scaffold. I agree that the source of the problem is aliasing.

**Comment by TahaTesser** [comment]
Hi @daniilguit 
Trying to reproduce this here

![Screenshot_1582715612](https://user-images.githubusercontent.com/48603081/75339933-74cbe380-58b7-11ea-84d0-2ac8c6557e54.png)

Does this looks like resolved?
Thank you

**Comment by VladyslavBondarenko** [comment]
Seems to be fixed. 
@daniilguit
Please write in the comments if it's not so and I will reopen it.
Thank you
