### ISSUE TITLE
Execution failed for task ':path_provider:verifyReleaseResources'.  > java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details

### ISSUE THREAD

**Issue by jp1017** [flutter/flutter#31300]
>flutter build apk

error: 

Execution failed for task ':path_provider:verifyReleaseResources'.
 java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by BondarenkoStas** [comment]
@jp1017 did you manage to solve it?

**Comment by yasinarik** [comment]
> @jp1017 did you manage to solve it?

I had the same issue.

Change the path_provider version to the newest. For ex. path_provider: 1.3.0

Then in terminal run:

`flutter clean`

Wait for it to delete older iOS and Android build files.

Then run again: 

`flutter build apk`
