### ISSUE TITLE
google_sign_in crash when the user cancel the signing flow

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#31311]
![Screenshot 2019-04-19 at 18 23 05](https://user-images.githubusercontent.com/9283414/56430831-5167fd80-62d0-11e9-8aef-9b3545651be9.png)

**Comment by long1eu** [comment]
I think I found the cause. I'm using a headless runner in the app and the plugins are initialised twice once for the main isolate and again for the background isolate. This way the delegate is set for the last that initialises the plugin witch is the background isolate. So the response comes back on background where the `_accountRequest` is indeed nil.

**Comment by long1eu** [comment]
I've made `_accountRequest` static an it worked perfectly.

**Comment by long1eu** [comment]
Why?

**Comment by BondarenkoStas** [comment]
oh, I thought the issue is solved. Can you confirm it's the same while using current stable and google_sign_in 4.0.7?

**Comment by eseidelGoogle** [comment]
I'm confused by the above conversation.  It sounds like this has been resolved?  Please comment if that's not the case.  Thanks!
