### ISSUE TITLE
Problem using Flutter 'android_alarm_manager' plugin with 'geolocator' plugin

### ISSUE THREAD

**Issue by adityaarora05** [flutter/flutter#31324]
## Steps to Reproduce

I used 'alarm_manager_plugin' and registered a static method in it. Inside that method I am trying to make the 'geolocation' plugin to work. The plugin links are :-

https://pub.dartlang.org/packages/android_alarm_manager
https://pub.dartlang.org/packages/geolocator

## Logs

It throws the following error :-
`**[ +252 ms] E/GooglePlayServicesUtil(19777): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.**

[   +2 ms] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): Failed to handle method call
**[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference**
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.baseflow.googleapiavailability.GoogleApiAvailabilityPlugin.onMethodCall(GoogleApiAvailabilityPlugin.java:64)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at android.os.MessageQueue.next(MessageQueue.java:143)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at android.os.Looper.loop(Looper.java:122)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at java.lang.reflect.Method.invoke(Method.java:372)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
[        ] E/MethodChannel#flutter.baseflow.com/google_api_availability/methods(19777): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
[  +67 ms] E/flutter (19777): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null)
[        ] E/flutter (19777): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
[        ] E/flutter (19777): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
[        ] E/flutter (19777): <asynchronous suspension>
[        ] E/flutter (19777): #2      GoogleApiAvailability.checkGooglePlayServicesAvailability (package:google_api_availability/src/google_api_availability.dart:23:50)
[        ] E/flutter (19777): <asynchronous suspension>
[        ] E/flutter (19777): #3      Geolocator._shouldForceAndroidLocationManager (package:geolocator/geolocator.dart:75:10)
[        ] E/flutter (19777): <asynchronous suspension>
[        ] E/flutter (19777): #4      Geolocator.getCurrentPosition (package:geolocator/geolocator.dart:93:21)
[        ] E/flutter (19777): <asynchronous suspension>
[        ] E/flutter (19777): #5      FGeoLocation.getLocation (package:frienzy/com/backend/geolocation/geolocation.dart:24:44)
[        ] E/flutter (19777): <asynchronous suspension>
[        ] E/flutter (19777): #6      DataOps.collectLocationData (package:frienzy/com/backend/service/DataOps.dart:83:16)
[        ] E/flutter (19777): #7      DataOps._dataCollectionHandler.<anonymous closure> (package:frienzy/com/backend/service/DataOps.dart:69:9)
[        ] E/flutter (19777): #8      _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] E/flutter (19777): #9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (19777): #10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
[        ] E/flutter (19777): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
[        ] E/flutter (19777): #12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
[        ] E/flutter (19777): #13     Future._complete (dart:async/future_impl.dart:473:7)
[        ] E/flutter (19777): #14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
[        ] E/flutter (19777): #15     _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] E/flutter (19777): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (19777): #17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
[        ] E/flutter (19777): #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
[        ] E/flutter (19777): #19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
[        ] E/flutter (19777): #20     Future._completeWithValue (dart:async/future_impl.dart:483:5)
[        ] E/flutter (19777): #21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
[        ] E/flutter (19777): #22     _rootRun (dart:async/zone.dart:1124:13)
[        ] E/flutter (19777): #23     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] E/flutter (19777): #24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[        ] E/flutter (19777): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
[        ] E/flutter (19777): #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] E/flutter (19777): #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ] E/flutter (19777): 
`

**Comment by yoonhok524** [comment]
I have the same problem!!!

**Comment by estevez-dev** [comment]
Looks like this was fixed on geolocator side. I have it working just perfectly. Please update geolocator to the latest version and try again.

**Comment by BondarenkoStas** [comment]
thank you @estevez-dev ! @adityaarora05 do you still have the problem?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
