### ISSUE TITLE
I am wondering if the Flutter itself could call clean on a project after an upgrade.

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#31323]
Many people just forget to call clean when they do an upgrade and start the next time a project. Can flutter not call clean itself after an upgrade happens to avoid misleading errors? Is there a way to delete breakpoints as well after upgrade  (Might be related to #30381)

C:\Projects\obdchk>flutter doctor -v
[√] Flutter (Channel master, v1.5.3-pre.33, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.5.3-pre.33 at c:\sdks\flutter
    • Framework revision eaf058d81d (4 hours ago), 2019-04-19 08:50:30 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[√] VS Code, 32-bit edition (version 1.30.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

**Comment by jonahwilliams** [comment]
The flutter tool has no knowledge of all the potential user created projects and their build directories. This could only work if it was always called from the root of a flutter project, and then only for a single project on a device.

**Comment by ride4sun** [comment]
Is there not information from the old build in the build directory about the flutter version. If not, would it not be possible to add that and compare it with the current. If not the same -> clean

**Comment by escamoteur** [comment]
@jonahwilliams As `flutter upgrade` is mostly from a projects folder like using the terminal of the IDE I think it would be a reasonable idea.
Alternatively could `flutter run` check if the flutter version has changed since the last build?

**Comment by ride4sun** [comment]
@jonahwilliams can we reopen this. I think doing this would avoid many undesired problems, especially for new users.

**Comment by jonahwilliams** [comment]
I'm re-closing this issue - the tool should not need to clean ever, and doing so after a project upgrade will hide bugs and not fix them
