### ISSUE TITLE
FutureBuilder/StreamBuilder infinitely called

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#31322]
I have a future builder that waits for _query method. the method is successfully called and when i printed the values it wasn`t null . the problem is that  the future builder never finishes and the method _query is called forever.

```
class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
            color: Colors.white, borderRadius: BorderRadius.circular(12)),
        margin: EdgeInsets.all(8),
        padding: EdgeInsets.all(8),
        child: _levelGrowth(),
      ),
    );
  }


  Widget _levelGrowth(){
    return Container(
      child: FutureBuilder(
          future:_query('skillId'),
          builder: (context,AsyncSnapshot<Map<String,List>> snapshot){
            if(!snapshot.hasData)
              return Center(child: CircularProgressIndicator());
            return Text(snapshot.toString());
          }),
    );
  }



  Future<Map<String,List>> _query(String skillId) async {
    int xNewbie = 0;
    int yNewbie = 0;


    Map<dynamic, dynamic> tempStartingLevelMap = Map();
    Map<String, String> startingLevelMap;
    Map<dynamic, dynamic> tempCurrentLevelMap = Map();
    Map<String, String> currentLevelMap;

    List<String> participantsIds = await fetchMembersID();  // return list of user ids. currently, its just one
    for (int index = 0; index < participantsIds.length; index++) {
      String id = participantsIds[index];

      DocumentSnapshot userScore =
      await Firestore.instance.collection('pod_status').document(id).get();

      if (userScore.data != null) {
        tempStartingLevelMap = userScore.data['startingLevel'];
        startingLevelMap = Map<String, String>.from(tempStartingLevelMap);
        tempCurrentLevelMap = userScore.data['currentLevel'];
        currentLevelMap = Map<String, String>.from(tempCurrentLevelMap);

        String xLevels = startingLevelMap[skillId];
        if (xLevels == 'Newbie') ++xNewbie;
        //....

        String yLevels = currentLevelMap[skillId];
        if (yLevels == 'Newbie') ++yNewbie;
        //....

      }

    }


    List xLevels = [xNewbie];
    List yLevels = [yNewbie];


    var m = {'currentLevel': xLevels,'startingLeve': yLevels};
    return m;
  }

}

```

[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.2)
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = C:\Program
    X Android Studio not found at C:\Program
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code, 64-bit edition (version 1.32.3)
[√] Connected device (1 available)

**Comment by jonahwilliams** [comment]
This is a common error, because of how you obtain your future each build will cause a new future to be allocated. From the [FutureBuilder](https://docs.flutter.dev/flutter/widgets/FutureBuilder-class.html) documentation:


> The future must have been obtained earlier, e.g. during State.initState, State.didUpdateConfig, or State.didChangeDependencies. It must not be created during the State.build or StatelessWidget.build method call when constructing the FutureBuilder. If the future is created at the same time as the FutureBuilder, then every time the FutureBuilder's parent is rebuilt, the asynchronous task will be restarted.

**Comment by mohamed6996** [comment]
please, could you tell me how to solve this problem in my case!

I have a future that returns 5 items. inside ListView.builder, i call another future that depends on the items obtained from the first future.

**Comment by zmeggyesi** [comment]
I've been using FutureBuilder the same way, and on Android, it's working just fine. On iOS, I ran into the same issue - completely logical, but WHY on Earth are the two behaving so differently?!
