### ISSUE TITLE
cloud_firestore support for get(source)

### ISSUE THREAD

**Issue by MichalMisiaszek** [flutter/flutter#31334]
Hi,
I have a query looking for names in large database.
It works quite slow and I suspect due to loading table to the device.
The firestore API defines get with source which allows to skip cache.
Can we have it as well in plugin ?
Thanks
Michal

**Comment by Stone2517** [comment]
Hey @MichalMisiaszek Check this but it only supports for only android not ios.

**Comment by Mmisiek** [comment]
Thanks but I need both :(

**Comment by larssn** [comment]
Duplicate of https://github.com/flutter/flutter/issues/19078

**Comment by Stone2517** [comment]
@Mmisiek Check this If you want to do it manually on ios and android 
https://github.com/flutter/plugins/pull/1538#issuecomment-496367142

**Comment by BondarenkoStas** [comment]
I'm going to close the issue as a duplicate, please follow #19078 and upvote it.
