### ISSUE TITLE
How to achieve this effect

### ISSUE THREAD

**Issue by Mrjen** [flutter/flutter#31346]
![e7b076038f19f1b1a2788b11251950e4](https://user-images.githubusercontent.com/21222152/56449964-53bf6b80-6353-11e9-9890-2b0c3d1894aa.GIF)

The previous name cannot be inserted into the cursor, and the selection is also selected as a whole.

**Comment by Hixie** [comment]
This appears to be a support request, not a bug report, so I'm going to close this issue. This is a bug database, for actionable changes we can make to Flutter, not for help. Thanks!11
