### ISSUE TITLE
Deleted android/ directory shouldn't be recreated when building an iOS-only app

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#31341]
I should be able to build an iOS-only app with Flutter without needing an `android/` directory. I deleted it, but on build, Flutter added two files back to this folder: 
 - `android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java`
 - `android/local.properties`

As we add more targets to Flutter, it should be possible to delete ones that aren't needed.

**Comment by jonahwilliams** [comment]
I need to fix this anyway for https://github.com/flutter/flutter/issues/30724
