### ISSUE TITLE
Installation app blocked by play protect

### ISSUE THREAD

**Issue by tarkhasi** [flutter/flutter#31349]
Hi there!
when trying to install a signed application  app-release.apk , a "Blocked by Play Protect" message is shown and the app is not installed.

i follow the steps on this page for release apk:
[https://flutter.dev/docs/deployment/android](https://flutter.dev/docs/deployment/android)

why happened this error?

![dc0d3b2f-d974-4767-9ada-c7691b6fdcf9](https://user-images.githubusercontent.com/23034751/56454078-0944eb80-6361-11e9-9b83-830e58517b04.jpg)

**Comment by lucashilles** [comment]
Try to enable Unknown Sources before the installation.
https://developer.android.com/distribute/marketing-tools/alternative-distribution#unknown-sources
