### ISSUE TITLE
Get package version mentioned in pubspec

### ISSUE THREAD

**Issue by daadu** [flutter/flutter#31344]
I want to get the package version mentioned in pubspec inside my code. I want to put that version in UA of all http requests.

Say this is my package name.

```yaml
name: my_pub
description: My Pub
version: 0.0.1
publish_to: none
```
I want "0.0.1" inside the code.

I found [this question on SO](https://stackoverflow.com/questions/23613279/access-to-pubspec-yaml-attributes-version-from-dart-app) but I guess it does not work with flutter.

Another way to do is to have a const global variable with stores the version_name, but in that case, how do I get that in pubspec.yaml. I want both the settings to be in sync.

Also if flutter is missing this as of now, then having this as feature could be useful for a lot of use cases.

**Comment by christopherfujino** [comment]
@daadu did you try the suggestion regarding `package_info_plus` from https://stackoverflow.com/a/55063417 ?
