### ISSUE TITLE
When writing many large files, the interface will be Jammed. Do you know what's going on?

### ISSUE THREAD

**Issue by jlcool** [flutter/flutter#31357]
When writing many large files, the interface will be Jammed. Do you know what's going on?
写多个大文件的时候会卡界面，请问怎么回事知道吗

**Comment by jlcool** [comment]
ui max 1282ms/frame

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`.

> When writing many large files, the interface will be Jammed

Are you using the synchronous File apis? Please include a minimal snippet that reproduces the problem.

**Comment by jlcool** [comment]
@jonahwilliams 
[√] Flutter (Channel master, v1.4.8-pre.22, on Microsoft Windows [Version 10.0.17134.706], locale zh-CN)
    • Flutter version 1.4.8-pre.22 at F:\flutter
    • Framework revision 3c9a81c396 (3 weeks ago), 2019-03-30 20:28:40 -0400
    • Engine revision ae024d7555
    • Dart version 2.2.1 (build 2.2.1-dev.2.1 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:/AndroidStudio/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:/AndroidStudio/Sdk
    • ANDROID_SDK_ROOT = F:\AndroidStudio\Sdk
    • Java binary at: F:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at F:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • MIX 2 • 420543ee • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
Process finished with exit code 0

``` dart
String _data(){
    JsonEncoder encoder = new JsonEncoder.withIndent('  ');
    List<Data> _list=List();
    for(var i=0;i<50000;i++) {
      Data _data = Data();
      _data.d1="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      _data.d2="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      _data.d3="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      _data.d4="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      _data.d5=1111111111;
      _list.add(_data);
    }
    String _data = encoder.convert(_list);
    return _data;
  }

  Future _incrementCounter() async {
    var tempDir = await getTemporaryDirectory();
    for (var i = 0; i < 10; i++) {
      File _file = File(join(tempDir.path, "name$i.txt"));
      _file.writeAsString(_data());//But when I commented on this code, everything went smoothly.
    }
  }
```
thank you

**Comment by jonahwilliams** [comment]
Serializing that much JSON is probable quite costly, you should move that off of the main thread to avoid blocking the ui. Here is an example using the `compute` function from `package:flutter/foundation.dart`:

```
  static bool _data(Map arguments) {
    var index = arguments['index'];
    var tempDir = arguments['tempDir'];
    var encoder = JsonEncoder.withIndent('  ');
    var items = <Map<String, dynamic>>[];
    for(var i = 0; i < 50000; i++) {
      var data = <String, dynamic>{};
      data['d1'] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      data['d2'] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      data['d3'] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      data['d4'] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
      data['d5'] = 1111111111;
      items.add(data);
    }
    var result = encoder.convert(items);
    final output = File('$tempDir/name$index.txt');
    try {
      output.createSync();
      output.writeAsStringSync(result);
    } catch (err) {
      return false;
    }
    return true;
  }

  Future<void> _incrementCounter() async {
    var tempDir = await getTemporaryDirectory();
    for (var i = 0; i < 10; i++) {
      var result = await compute(_data, {'index': i, 'tempDir': tempDir.path});
      if (result) {
        print('Success!');
      }
    }
  }
```

This will still take some time to complete, but it won't caused dropped frames.

**Comment by jonahwilliams** [comment]
Forgot link: https://docs.flutter.io/flutter/foundation/compute.html

**Comment by jlcool** [comment]
It works. Thank you very much.
