### ISSUE TITLE
flutter ios initWithEngine the engine is come from the window.rootViewController when a  push a new FlutterViewController  with this engine the new viewController don't work

### ISSUE THREAD

**Issue by duruochuan** [flutter/flutter#31354]

**Comment by duruochuan** [comment]
step 1  save the engine
_defaultViewController = (KQViewController *)self.window.rootViewController; 
_defaultEngine = _defaultViewController.engine;

KQViewController is a subclass of FlutterViewController
@interface KQViewController : FlutterViewController

FlutterEngine *engine = [AppDelegate defaultEngine];
engine.viewController = nil;
KQViewController *vc = [[KQViewController alloc]initWithEngine:engine nibName:nil bundle:nil];
[engine setViewController:vc];
[vc pushRoute:@"/home"];

when i present the vc the vc is show and push to the route '/home' but the screen can't do any opration just like died!!!!

**Comment by BondarenkoStas** [comment]
@duruochuan is it the same while using current flutter stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
