### ISSUE TITLE
Weird behavior on removing TextField widgets dynamically created

### ISSUE THREAD

**Issue by frideosapps** [flutter/flutter#31352]
Hello, I am facing a weird behavior (or maybe I am doing something wrong): I was working on a dynamic form validation example, where I have two fields (name and age) and a button to add more of these pair of fields and another one for each pair to eliminate them from the screen. When, for example, I have three pairs of these fields, let's say "name: [A,B,C] and age: [1,2,3]" and I click on the delete button of the middle pair of fields, instead of having "name: [A, C] and age: [1, 3]", I have "name: [A, B] and age: [1, 2]" like if the middle textfields retain the old value (instead, in the debug console I have the correct pair of values). I found a workaround using a collection of TextEditingController and setting the value of each textfield to the correct one. Is this behavior intended or an issue?

## Steps to Reproduce

1. Add three new pair of fields by clicking on the button "Add more fields"
2. Insert e.g name A, age 1, name B, age 2, name C, age 3
3. Click to remove the middle pair of name/age fields

https://gist.github.com/frideosapps/fadea58ae7d52d1cdb9537ed833cfa39

Working version (with TextEditingController): https://gist.github.com/frideosapps/1e17e64ec72bad936268730b379aabf3

## Logs

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale
    en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\frata\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4733

[√] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27)
      (emulator)

• No issues found!
```

**Comment by winwintogether** [comment]
I have same issue with adding and removing dynamic form fields.
I added form fields ['1', '2', '3'] and remove '2'.
Then, logically, ['1', '3'] should be left.
But actual result is ['1', '2']

How can I fix this issue?

**Comment by TahaTesser** [comment]
Hi @frideosapps  @winwintogether 
Are you still experiencing this issue?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by leogpinheiro** [comment]
It stills happening with me too. I tried a lot of different directions given in the forums like StackOverflow, but no success at all.
Could you please help us to solve that?

**Comment by iapicca** [comment]
@leogpinheiro 
could you please open a new issue providing the information listed [above](https://github.com/flutter/flutter/issues/31352#issuecomment-611560708)
