### ISSUE TITLE
firebase_auth: 0.8.0+3 FireBaseAuth.verifyPhoneNumber crashes on IOS 12.1 device 

### ISSUE THREAD

**Issue by silversquall** [flutter/flutter#31362]
Hello,

My app crashes on IOS 12.1 when trying to register my phone (I am testing on real device).
FireBaseAuth.verifyPhoneNumber

I had no issues with firebase_auth: 0.6.6.
Any version starting from firebase_auth: 0.8.0+3 crashed my app ( which BTW runs fine on android)
(I recently upgraded my dependencies to match androidX)
I of course ran flutter clean prior building, still the same issue.

**Flutter doctor -v:**

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G65, locale
    en-FR)
    • Flutter version 1.2.1 at /Users/Crono/Development/Mobile/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53
      -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/Crono/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2017.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone … ios •
      iOS 12.1

**The flutter exception:**
18:08:27.006 2560 info flutter.tools [  +41 ms] Service protocol connection closed.
18:08:27.006 2561 info flutter.tools [   +1 ms] Lost connection to device.
18:08:27.006 2562 info flutter.tools [   +2 ms] DevFS: Deleting filesystem on the device
18:08:27.007 2563 info flutter.tools [   +1 ms] Sending to VM service: _deleteDevFS(...)
**The Exception retrieved from xcode:**
2019-04-14 18:21:58.563029+0200 Runner[2949:2458392] flutter: [PhoneRegistrationProvider] IN _signInWithPhoneNumber with verificationId = AM5PThAhkxp09QXVFGSzsJbuSmb04gKnaumYSbwYNKhbjC0Hd1ZSUGrZhpBID8qP2CBxq14nKmxFJSgINW97KgPBqsn-kL03FrXoXDVdnznCiwh2nMROy6fiRmwhWuYyzuGnvsSxts1pUV0sLYD3e2O8bHESlnzZyAuCjLEDMThuAn8EqIrVpcyp9kP-7vKhSMyTT4QR1vei and smsCode = 142558
2019-04-14 18:21:58.568043+0200 Runner[2949:2458375] -[NSNull length]: unrecognized selector sent to instance 0x1eea359b0
2019-04-14 18:21:58.569355+0200 Runner[2949:2458375] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1eea359b0'
*** First throw call stack:
(0x1be2d3ea0 0x1bd4a5a40 0x1be1ecd04 0x1be2d97b8 0x1be2db45c 0x10294ebb4 0x102944930 0x102944164 0x1066db824 0x1066dcdc8 0x1066e4e6c 0x1066e5b60 0x1066efbfc 0x1bdef00dc 0x1bdef2cec)
libc++abi.dylib: terminating with uncaught exception of type NSException

any help is appreciated :)

**Comment by silversquall** [comment]
The crash was caused by the input code that i always set as null, sorry for my negligence.
nevertheless it made the app crash on IOS

**Comment by gisinator** [comment]
I have the exact same problem. On my iPhone 5s with iOS 12.2, running

await _auth.verifyPhoneNumber(phoneNumber: "+491712345678",
        timeout: Duration(seconds: 60),
        verificationCompleted: (e){
          print("completed");
        },
        verificationFailed: (a){
          print("failed" + a.message);
        },
        codeSent: (String a, [int]){
          print("codeSent");
        },
        codeAutoRetrievalTimeout: null);`

the app crashes instantly when I hit the button.

On Android, it works perfectly. Other firebase-operations like e-mail registering work like a charme. Silversquall, could you give a little more details on how you solved that? :)

**Comment by silversquall** [comment]
> 
> 
> I have the exact same problem. On my iPhone 5s with iOS 12.2, running
> 
> await _auth.verifyPhoneNumber(phoneNumber: "+491712345678",
> timeout: Duration(seconds: 60),
> verificationCompleted: (e){
> print("completed");
> },
> verificationFailed: (a){
> print("failed" + a.message);
> },
> codeSent: (String a, [int]){
> print("codeSent");
> },
> codeAutoRetrievalTimeout: null);`
> 
> the app crashes instantly when I hit the button.
> 
> On Android, it works perfectly. Other firebase-operations like e-mail registering work like a charme. Silversquall, could you give a little more details on how you solved that? :)

Hey gisinator could you try to build your app in release mode and try again ?

**Comment by gisinator** [comment]
Thanks silversquall. I just tried in release-mode, but without success. Same crash as soon as I hit the button. I'll go over all those APNs settings and keys and stuff one more time, even though I'd expect flutter to just return an error message if that would be the case...

**Comment by silversquall** [comment]
@gisinator glad to hear that ! lot's f conf @ first sight then it's all smooth...until the next relase of the lib :D
