### ISSUE TITLE
High resolution images (more than 4-5Mb) not display in application.

### ISSUE THREAD

**Issue by dulkith** [flutter/flutter#31363]
```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Image Test App')),
        body: Column(
          children: <Widget>[
            Image.asset('assets/IMG_20190420_193034.jpg',
                scale: 2.0, width: 48.0, height: 48.0),
            Text('Me')
          ],
        ),
      ),
    );
  }
```
This is my code images taken from camera not display in application.

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by dulkith** [comment]
> flutter doctor -v

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-LK)
    • Flutter version 1.2.1 at /Users/Dulkith/Documents/development/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Dulkith/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/Dulkith/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • SM J500F • c1396ac4 • android-arm • Android 6.0.1 (API 23)

**Comment by GustavoContreiras** [comment]
Maybe it's the same problem? https://github.com/flutter/flutter/issues/31374

**Comment by dulkith** [comment]
> Maybe it's the same problem? #31374
> 
> Edit:
> I can post the picture on firestore and see it there (a picture with my rear camera with full quality has 5.8 MB). But on app I can't.

I use this camera library : https://github.com/hramaroson/flutter_cameraview.git
How to reduce the image quality of the camera when taking the image. After taking image and like comress image process take long time to reduce the image quality.

**Comment by GustavoContreiras** [comment]
Another solution is setting maxWidth and maxHeight:
`await ImagePicker.pickImage(source: ImageSource.camera, maxWidth: 1920, maxHeight: 1350);`

**Comment by liushiqi9** [comment]
I have bunch of pictures of 9000*7000 resolution, I can display them, but when I zoom them, I alwasy get a black screen whether using extended-image or photo-view.

**Comment by EricBichara** [comment]
> I have bunch of pictures of 9000*7000 resolution, I can display them, but when I zoom them, I alwasy get a black screen whether using extended-image or photo-view.

I'm seeing the same issue

**Comment by deckerst** [comment]
I believe it's the same issue as https://github.com/flutter/flutter/issues/36191
which was recently tagged as "severe: regression", so hopefully a fix will come soon...

**Comment by BondarenkoStas** [comment]
@dulkith you can use image_picker, starting from 0.6.1 (July 30) there is imageQuality parameter which allows you to compress images.

**Comment by Nidzy** [comment]
> 
> 
> I have bunch of pictures of 9000*7000 resolution, I can display them, but when I zoom them, I alwasy get a black screen whether using extended-image or photo-view.

how you have loaded such high resolution image in flutter app??? which library you have used ?

**Comment by iapicca** [comment]
Hi @dulkith 
if you are still using the [3rd party plugin](https://github.com/hramaroson/flutter_cameraview) you mentioned
(doesn't appear to be listed on [pub.dev](https://pub.dev/)) you may want to open an issue in the dedicated [github](https://github.com/hramaroson/flutter_cameraview/issues).

if you are using [camera](https://pub.dev/packages/camera) or  [image_picker](https://pub.dev/packages/image_picker) please provide your `flutter doctor -v` 
and a reproducible minimal code sample
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
