### ISSUE TITLE
flutter engine no longer builds on Mac

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3136]
Turns out that we're only building the sky_snapshot binary on our bots, otherwise we would have caught this sooner.  Will fix that shortly!

Build log https://gist.github.com/eseidelGoogle/a8e575773169950eb90444a5ff537056

@chinmaygarde @zanderso

**Comment by chinmaygarde** [comment]
When we retired the old Mac bots, I only checked the `gn --release` call :( Didn't see that the build call was only preparing the sky_snapshot.

**Comment by eseidelGoogle** [comment]
Fixed our bots: https://codereview.chromium.org/1868623002  Now we just need to turn them green again. :)  May need some help from @zanderso to do so.

**Comment by zanderso** [comment]
To use the native SSL implementation on Mac/iOS, I think you'll need to update mac_sdk_min in //build/config/mac/mac_sdk.gni from 10.6 to 10.8.

**Comment by chinmaygarde** [comment]
Yeah, I have a PR incoming for that. Some of other engine dependencies use deprecated declarations. In the process of getting rid of them.
