### ISSUE TITLE
[Firebase Messaging] Does FCM support pushing notification, when the app is terminated?

### ISSUE THREAD

**Issue by peek4y** [flutter/flutter#31365]
I've tried pushing notifications via FCM without the data payload (I know the message is lost with data payload), but looks like even without the data payload, just content & title, I don't see any notifications delivered when the app is terminated.

Is this how it's suppose to be? or am I missing something?

**Comment by marianoarga** [comment]
Related to #22072

**Comment by kroikie** [comment]
https://github.com/flutter/plugins/pull/1900 should allow you to handle background messages in your Dart code for Android.

**Comment by BondarenkoStas** [comment]
It was done in https://github.com/FirebaseExtended/flutterfire/pull/38 and merged on September 6, I think it's safe to close the issue.
