### ISSUE TITLE
[image_picker] can't print picture taken with rear camera

### ISSUE THREAD

**Issue by GustavoContreiras** [flutter/flutter#31374]
Using this example: https://github.com/flutter/plugins/blob/master/packages/image_picker/example/lib/main.dart

If I take a picture with rear camera, it shows a white container.
If I take with front camera, it loads ok.

Maybe is something related to that? https://github.com/flutter/flutter/issues/17947 (edit: it's not)

Using flutter run -v these are the message on console when I press OK on native camera after taking a photo:
```
[ +394 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/946374823, name: main.dart:main(), number: 946374823}, timestamp: 1555813689995, extensionRPC:
ext.dart.io.getOpenFiles}}  

[   +3 ms] Notification from VM: {streamId: Isolate, event: {type: Event, kind: ServiceExtensionAdded, isolate: {type: @Isolate, fixedId: true, id: isolates/946374823, name: main.dart:main(), number: 946374823}, timestamp: 1555813689996, extensionRPC:
ext.dart.io.getFileByID}}
```

Maybe the problem is the file size? https://github.com/flutter/flutter/issues/31363
(My rear camera makes pictures with 5.8 MB while the front camera makes with 2.7)

**SOLVED**
You have to set a maxWidth and maxHeight
`await ImagePicker.pickImage(source: ImageSource.camera, maxWidth: 480, maxHeight: 600);`

**Comment by BondarenkoStas** [comment]
Thank you @GustavoContreiras, it is related to the size, and isn't solved yet. I will close the issue in favour to #31363 to avoid duplication.
