### ISSUE TITLE
Crashlytics plugin request: report actual exception mesage instead of harcoded "Dart error"

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#31370]
Currently FirebaseCrashlyticsPluginJava has this code
```java
      Exception exception = new Exception("Dart Error");
     Crashlytics.setString("exception", (String) call.argument("exception"));
      Crashlytics.logException(exception);

```
I propose instead something like this (not exact code, I didn't run it)
```java
 String dartExceptionMessage = (String) call.argument("exception");
 Exception exception = new Exception("Dart Error:" + dartExceptionMessage );
      Crashlytics.logException(exception);
```
This seems like this would be a really big improvement in terms of not getting exceptions grouped improperly... of course, you can put some defensive code around nullchecks, but this would be great.

**Comment by lmckenzie** [comment]
@jonahwilliams would you mind if I make a PR for this?

**Comment by kroikie** [comment]
@neiljaywarner

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1146. Any further collaboration will be done there.
