### ISSUE TITLE
How to upgrade my current flutter to use Dart 2.3

### ISSUE THREAD

**Issue by taylorren** [flutter/flutter#31372]
Hi there, 

Thrilled to know Dart is now in 2.3. I tried `flutter upgrade` just now and it does not upgrade my Dart to 2.3 though, still using 2.1.X. 

Any hints? (I am using flutter-io.cn as the upgrade repo).

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by dcov** [comment]
@taylorren 
It's on the `master` channel. Run `flutter channel master`

**Comment by taylorren** [comment]
@dcov Thanks and it works!

@jonahwilliams Thanks for the follow-up. Attached the output of `flutter doctor -v`

![Ashampoo_Snap_2019年4月21日_15h30m14s_010_cmd](https://user-images.githubusercontent.com/3853711/56466909-b34c7280-644a-11e9-81cf-fdd05855ac43.png)

**Comment by meysammahfouzi** [comment]
It's not stable?
