### ISSUE TITLE
performance mesurements for widget rendering

### ISSUE THREAD

**Issue by taioo** [flutter/flutter#31389]
Hi Flutter team,

I'm currently working on the performance analytical topic regarding flutter. I should measure the rendering time of a Widgets that we have. I found following way how to do this, but not sure if I'm on the right way.

Below you can see a simple Button Widget. I'm using here the **Widget constructor** as init function to count the start time and the **initState** function, which will be called after the render/build is done to count the end time and print it out. 

```
import 'package:flutter/material.dart';

class ButtonStart extends StatefulWidget {
  int Start = 0;

  ButtonStart() : super(key: Key('ButtonStart')) {
    this.Start = DateTime.now().millisecondsSinceEpoch;
  }

  @override
  _ButtonStartState createState() => _ButtonStartState();
}

class _ButtonStartState extends State<ButtonStart> {

  @protected
  @mustCallSuper
  void initState() {
    super.initState();
    debugPrint('######## button: ' +(DateTime.now().millisecondsSinceEpoch - widget.Start).toString() +' millisecond');
  }

  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      shape: new RoundedRectangleBorder(
          borderRadius: new BorderRadius.circular(12.0)),
      color: Colors.blue,
      child: Text('Accept')
    );
  }
}
```

The results are different when I start the app on the (ios) emulator and If I just navigate to different UI that doesn't include the button and switch back.
After I start the app I got 69 ms and if I switch back then I got 3 ms. It seems like there is a cash system behind. Not sure how I should consider this in my results. Are there some options provided by flutter to control this?
The results are without coma because I'm using DateTime API. Maybe there is a better Timer object.

Best Regards,
taioo

**Comment by jonahwilliams** [comment]
This can be done with the debugProfileWidgetBuilds flag, which is currently available in dev from the command line. This causes all widget build times to show up in the timeline - BUT, it does add some overhead to the process, so relative comparisons are most useful.

I'm not sure when this will be available in devtools -  cc @devoncarew

**Comment by taioo** [comment]
Hi @jonahwilliams thank you for your quick reply. But I'm not sure where I can find the debugProfileWidgetBuilds in dev in the command line. In flutter cli I didn't found something:
![Screenshot 2019-04-22 at 11 53 16](https://user-images.githubusercontent.com/14871128/56495258-8608ce80-64f5-11e9-8230-18c84f95cbaf.png)

It seems not to be available now. Meanwhile I would like to go in the way mentioned above, but not sure if this is the correct way. Is in this way something that I need to consider? Or is it completely not the right way?

**Comment by jonahwilliams** [comment]
This flag is available after attaching to an application, not directly from the command line. try flutter run and then press h for more options

**Comment by taioo** [comment]
hi @jonahwilliams  I cannot find this option you mentioned. After flutter run I pressed h and got following options:
![Screenshot 2019-04-23 at 18 05 56](https://user-images.githubusercontent.com/14871128/56597401-ab2f3700-65f2-11e9-8abb-a103ab009e43.png)
**debugProfileWidgetBuilds** is not included

I'm using following flutter cli
![Screenshot 2019-04-23 at 18 10 41](https://user-images.githubusercontent.com/14871128/56597641-2abd0600-65f3-11e9-81d0-e5cacee089d7.png)

**Comment by jonahwilliams** [comment]
This is only available in dev

**Comment by Hixie** [comment]
You can also just set it directly in your code, see the API docs.
