### ISSUE TITLE
Clarify the README.md for the firebase_auth plugin

### ISSUE THREAD

**Issue by abbypro** [flutter/flutter#31386]
For new developers using the firebase_auth plugin, a little error-checking goes a long way. Adding a few lines of code to the "Register a User" section of the firebase_auth README.md would greatly help new developers down the line. 

After creating a user, if the user is null or the userIdToken() is null, it can cause a lot of weird issues. The specific issues depend on how you've set up the rest of your code, and if you have more error-checking down the line.

**Comment by kroikie** [comment]
@abbypro

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1111. Any further collaboration will be done there.
