### ISSUE TITLE
FR: add multiple Flutter modules in an existing app

### ISSUE THREAD

**Issue by hnvn** [flutter/flutter#31384]
I am facing a use-case that I need to integrate two separate modules (library/framework), each has its own part is built in Flutter, into a project. It seems that Flutter doesn't support this use-case because `FlutterEngine` can only load a single specific set of AOT snapshots in an application. In my case, each module has its own Flutter part then each has its own set of AOT snapshots in its distribution. I think it's a valid use-case but currently, I can't find any way to get around it. Is there any idea for this use-case?

**Comment by jmagman** [comment]
@xster Do we have a better duplicate than https://github.com/flutter/flutter/issues/24918?

**Comment by xster** [comment]
Let's move them both into https://github.com/flutter/flutter/issues/39707. It's more detailed so far.

**Comment by jmagman** [comment]
Closing, see https://github.com/flutter/flutter/issues/39707.
