### ISSUE TITLE
flutter_gallery: Launch documentationUrl will only show an empty page on Android

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#31387]
Mobile OS: Android.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.4.12, on Mac OS X 10.13.6 17G4015, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[!] Android Studio (version 3.1)
[✓] VS Code (version 1.33.1)
```

The way I install flutter gallery: 

```
$ cd $FLUTTER_ROOT/examples/flutter_gallery
$ flutter run
```

On a physical android device, I can not launch any GalleryDemo documentationUrls. All give me empty pages. 

On iphone simulater Simulator.app on MacOS, it works fine. The documentation URL can be launched successfully.

**Comment by BondarenkoStas** [comment]
Confirming empty pages on android physical device with v1.9.1+hotfix.4. But actually some of them contain API links which are successfully open in browser.

**Comment by TahaTesser** [comment]
Issue still exist 

![flutter_01](https://user-images.githubusercontent.com/48603081/76417096-3c053180-63c2-11ea-8559-978df539f866.png)

**Comment by TahaTesser** [comment]
Please try new. https://gallery.flutter.dev/#/ 
Closing `flutter_gallery` no longer maintained/available
Thank you
