### ISSUE TITLE
iOS Release version freezing with Google Maps (google_maps_flutter) works fine with debugger

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#31390]
## Steps to Reproduce

1. `flutter build ios --release`
2. Deploy to device via xCode

I'm doing the most vanilla version of this plugin to test there's nothing else interfering. The only thing it does it open another screen.

When running the app with the debugger it works fine.

When running in release mode on iOS it works fine until you open another screen and go back to the maps app 3-2 times.

After the third time the map stops responding to touch events for a few seconds. Not only that but the back animation from the screen is extremely slow often freezing for over 2 seconds.

## Logs

There are no logs that relate.

No issues found! (ran in 4.0s), with Flutter Analyze.

`flutter doctor -v` has all ticks on each section.

**Comment by ollydixon** [comment]
For anyone else having this issue I have migrated to 'FlutterMap' which uses MapBox (https://pub.dartlang.org/packages/flutter_map). It's a lot more feature rich (Markers are Widgets, non of that weird image loading stuff with the Google Maps Lib). Also feels much faster and more bug free.

**Comment by GaryQian** [comment]
cc @amirh @cyanglaz

**Comment by cyanglaz** [comment]
cc @iskakaushik looks like a memory leak? Either on google map or platform view.

**Comment by iskakaushik** [comment]
@ollydixon: I tried to reproduce this issue, I was not able to. Here is my recording https://photos.app.goo.gl/g7PhK1FQ2qhcDiVk6

Could you please try it on the latest version of the google maps plugin and let me know if it's still an issue. It would be useful if you can share a similar recording.

**Comment by ollydixon** [comment]
@iskakaushik, thanks for the help. Maybe I misexplained it, It must be between navigation tabs within the app not going from app to app. Also this is release mode?

**Comment by iskakaushik** [comment]
@ollydixon could you please create a minimal version of your app that can illustrate this bug? It will greatly help us. Thanks!

**Comment by django-wong** [comment]
Think I encountered the same problem with mapbox-gl on WebView. The map gets stuck after a short while I operating (zoom in or zoom out, move the camera) the map.

I'm creating a demo app so you can reproduce the issue. @iskakaushik

**Comment by TahaTesser** [comment]
Hi @ollydixon
I cannot any freeze in release mode or test flight release of the app using official sample 

Sample
https://pub.dev/packages/google_maps_flutter/example


```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.2.0-11.0.pre.215, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.215 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5865c14d67 (7 hours ago), 2021-04-22 06:44:03 +0200
    • Engine revision 7e69744ede
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version unknown)
    ✗ Invalid IntelliJ version number.

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```
	
</details>


To better address the issue, can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
Thank you

**Comment by poovarasanvasudevan** [comment]
Is this issue still exists. I am also facing same issue. works good in debug mode,
when I release the app. screen freezes

I am using flutter 2.0.6 stable
google_maps_flutter 2.0.3
