### ISSUE TITLE
Problem after build release but no proplem after build debug

### ISSUE THREAD

**Issue by majdkz97** [flutter/flutter#31397]
my app get data from http.await
it work Normally when I "flutter build apk --debug"
But it Doesn't Get the data from http 
When i "flutter build apk --release"

my app link
https://github.com/majdkz97/burgerapp

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.4-pre.17, on Microsoft Windows [Version 10.0.14393], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[!] Connected device
    ! No devices available

**Comment by jonahwilliams** [comment]
It looks like your application is missing a permission for Internet activity in the android manifest. For more information, see https://stackoverflow.com/questions/2378607/what-permission-do-i-need-to-access-internet-from-an-android-application

**Comment by majdkz97** [comment]
> It looks like your application is missing a permission for Internet activity in the android manifest. For more information, see https://stackoverflow.com/questions/2378607/what-permission-do-i-need-to-access-internet-from-an-android-application

Thanks A lot
it Works 🥇
