### ISSUE TITLE
How to fix firestore reading/writing data continuously even when no write/read operations have been invoked.

### ISSUE THREAD

**Issue by abbujo** [flutter/flutter#31405]
Hello all, I am using bloc pattern as described in https://github.com/boeledi/blocs for my application. In the application, I am basically fetching and writing data to and from firestore. Recently I noticed that my 20k free writes in firestore are getting over pretty quickly when I am testing the app with very few write requests. Upon monitoring, I found out that my app is continuously writing/reading data from and to firestore(I cannot see any new data being written though.). I monitored the console of my firestore app for about an hour without making any read/write requests and was amazed to see that the requests are being made quite frequently which eats up my 20k write quota in about a couple of hour. 

I have so far tried to figure out why the requests are being continuously made, but I am not able to figure out why it might be happening. After searching through the internet I did not find any concrete answers to this so I am pretty sure it is because of noob mistake that I happened to commit especially since it is my first time working with firestore and flutter.

Read operations:
```
populateItemList(){
    _db.collection('users').document(user.uid).collection('num').getDocuments().then(
        (docs){
          docs.documents.forEach(
              (doc){
                numDetails numm = ItemDetails(doc.data["numName"]);
                listnumm.add(numm);
                itemNameList.add(numm.nummName);
              }

          );
          listIn.add(listnumm); // Sink<List<numDetails>>
          nummNameListIn.add(nummNameList); // Sink<List<String>>
        }
    );
  }

```
Write Operations:
```
setItemData(FirebaseUser user, String itemName, double itemQty, double itemPrice, String itemUnit) async{
    var ref = _db.collection('users').document(user.uid).collection('items').document(itemName.toUpperCase());
    Map<String, dynamic> mapToUpdate ={};
    mapToUpdate = {"ItemName" : itemName.toUpperCase(), "ItemQty" : itemQty, "ItemPrice" : itemPrice, "ItemUnit" : itemUnit};
    await ref.setData(mapToUpdate, merge: true);
  }
```
To invoke the write operation I am listening to a stream that basically will check if the data provided in the text fields related to the itemField is valid. Once it is deemed to be valid the RaisedButton will becoe active and will emit and event to update the information.
```
StreamBuilder<bool>(
            stream: _ItemUpdateFormBloc.registerValid,
            builder: (BuildContext context, AsyncSnapshot<bool> snapshot) {
              return RaisedButton(
                child: Text('Proceed'),
                onPressed: (snapshot.hasData && snapshot.data == true)
                    ? () {
                  _itemUpdateBloc.emitEvent(ItemUpdateEvent(
                      user: widget.user,
                      event: ItemUpdateEventType.working,
                      itemUnit: _itemUnitController.text,
                      itemPrice: double.parse(_itemPriceController.text.toString()),
                      itemQty: double.parse(_itemQtyController.text.toString()),
                      itemName: _itemNameController.text,)
                  );
                }
                    : null,
              );
            }
        )
```
Upon recieving the event, the event handler will do this:
```
Stream<ItemUpdateState> eventHandler(ItemUpdateEvent event, ItemUpdateState currentState) async* {
    if (event.event == ItemUpdateEventType.working){
      yield ItemUpdateState.busy();
      itemService = ItemService(event.user);
      await itemService.setItemDataAndGetInfo(event.user, event.itemName, event.itemQty, event.itemPrice, event.itemUnit);
      yield ItemUpdateState.success();
    }
  }
```

I want to reduce the number of unnecessary writes and read operations that will cost me a fortune if the app goes on making read/write requests this often. Thanks for the help.

**Comment by klaszlo8207** [comment]
Did you find any solution?
