### ISSUE TITLE
Issue from website page 使用缓存图片

### ISSUE THREAD

**Issue by lwh2015** [flutter/flutter#31401]
From URL: https://www.flutterchina.club/cookbook/images/cached-images.md
按照官方给的例子使用后，发现图片没有显示出来，控制台也没有报错，想请教一个是不是flutter本身是不是要配置什么？
![image](https://user-images.githubusercontent.com/16028333/56480229-bf3c4100-64eb-11e9-8ce4-9b3c584dc0ee.png)

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
