### ISSUE TITLE
firebase_auth passwordless sign-in "Dynamic link not found" after link click

### ISSUE THREAD

**Issue by fabriziocacicia** [flutter/flutter#31415]
I'm trying to use the new passwordless sign-in method implemented in the Flutter firebase_auth package. I already followed the steps in order to receive the verification email, but after pressing on the link in the email, instead of being redirected to the app a web page saying "Dynamic Link not found" opens.

I'm on the latest Flutter stable channel 1.2.1, and I'm using the latest version of the firebase_auth package up to now 0.8.4+5. I'm also using the latest version of the firebase_dynamic_links package 0.2.1.

I tried with a manually created dynamic link and if I paste it in the browser it properly opens my app. It seems that the firebase_auth API for the passwordless sign-in generate a bad link. I already tried different combinations of parameters and URLs, without success.

Here's how I call the firebase_auth API:

```dart
_auth.sendSignInWithEmailLink(
      email: email,
      url: 'https://mydomain.app/',
      handleCodeInApp: true,
      iOSBundleID: 'app.mypackage',
      androidPackageName: 'app.mypackage',
      androidInstallIfNotAvailable: false,
      androidMinimumVersion: '16',
    );
```

I also tried to pass a programmatically generated dynamic link:

```
final DynamicLinkParameters parameters = DynamicLinkParameters(
      domain: 'myapp.page.link',
      link: Uri.parse('https://mydomain.app/'),
      androidParameters: AndroidParameters(
        fallbackUrl: Uri.parse('https://mydomain.app/'),
        packageName: 'app.mypackage',
        minimumVersion: 16,
      ),
    );

final ShortDynamicLink link = await parameters.buildShortLink();

_auth.sendSignInWithEmailLink(
      email: email,
      url: link.shortUrl.toString(),
      handleCodeInApp: true,
      iOSBundleID: 'app.mypackage',
      androidPackageName: 'app.mypackage',
      androidInstallIfNotAvailable: false,
      androidMinimumVersion: '16',
    );

```

Also, if I try to open the URL generated by ```link.shortUrl.toString()```manually in the phone browser, my app opens.

I expect that the verification link in the email opens my app but for now it opens that page saying that the dynamic link doesn't work.

**Comment by janmoppel** [comment]
Hello @fabryx92 !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by fabryx92** [comment]
Hi @janmoppel, I simply abandoned the idea to use the passwordless authentication and I opted for the email and password method.

If I will have a bit of free time, I will try to figure out why it doesn't work and maybe open a PR.

**Comment by TahaTesser** [comment]
Hi @fabriziocacicia 
if you're still experiencing this issue, could you please raise this issue in [flutterfire](https://github.com/FirebaseExtended/flutterfire/issues)
Thank you
