### ISSUE TITLE
In the asset resource, when the image name is Chinese, the corresponding resolution image cannot be automatically loaded

### ISSUE THREAD

**Issue by Microgap** [flutter/flutter#31410]
> 目录结构如下
>  > .../pubspec.yaml 
>  > .../icons/中文图片名.png
>  > .../icons/2.0x/中文图片名.png
>  > .../icons/3.0x/中文图片名.png
> 
> 两种方式加载图片
> > Image.asset('icons/中文图片名.png') 
> > AssetImage('icons/中文图片名.png''')
> 
> 程序运行后，均不能自动加载2.0x或3.0x目录下的图片，而是始终使用的../icons/中文图片名.png
> 
>  > .../pubspec.yaml 
>  > .../icons/english.png
>  > .../icons/2.0x/english.png
>  > .../icons/3.0x/english.png
> 
> > Image.asset('icons/english.png') 
> > AssetImage('icons/english.png''')
> 
> 图片名称改为英文时，一切正常，当使用iPhone XR时加载2.0x下的图片，使用iPhone XS时会加入3.0x下的图片
> 
> 请问这是目前flutter的问题，还是需要做什么设置？

(Google translator)
The directory structure is as follows

```bash
.../pubspec.yaml
.../icons/Chinese image name.png
.../icons/2.0x/Chinese picture name.png
.../icons/3.0x/Chinese picture name.png
```
Loading images in two ways

```dart
Image.asset('icons/Chinese image name.png')
AssetImage('icons/Chinese image name.png''')
```

After the program runs, it can't automatically load the images in the 2.0x or 3.0x directory, but always use the ../icons/Chinese image name.png

```bash
.../pubspec.yaml
.../icons/english.png
.../icons/2.0x/english.png
.../icons/3.0x/english.png
```

```dart
Image.asset('icons/english.png')
AssetImage('icons/english.png''')
```

When the image name is changed to English, everything works fine. When using iPhone XR, the image under 2.0x is loaded, and when using iPhone XS, the image under 3.0x will be added.

Is this the current problem with flutter, or what settings do I need to make?

**Comment by shuicheng** [comment]
呵呵，你不会把变量名和类名什么的都写成中文的吧？

**Comment by iapicca** [comment]
Hi @Microgap 
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
