### ISSUE TITLE
Snack Bars should have a light theme when the overall app has a dark theme

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#31418]
Currently snack bar will always default to a dark theme regardless of your app's theme. However, if the app has a dark theme, the snack bar colors should default to a light theme instead.

**Comment by HansMuller** [comment]
The snackbar theme's colors should be configured in terms of the overall theme's [ColorScheme](https://api.flutter.dev/flutter/material/ThemeData/colorScheme.html).

CC @darrenaustin
