### ISSUE TITLE
Add custom option to context menu.

### ISSUE THREAD

**Issue by NCPlayz** [flutter/flutter#31412]
When you select a piece of text, it has a "more info" (the three dots) button where apps register options (like "translate to rot13") and I was wondering if this was possible with Flutter? 

I couldn't quite key in what it would be called in the documentation.

**Comment by chunhtai** [comment]
@justinmc Do we have any plan for this feature?

**Comment by justinmc** [comment]
No concrete plans for custom selection menu items yet.  However, [this issue](https://github.com/flutter/flutter/issues/35826) shows that the current selection menu often overflows, so I was thinking of implementing the "three dots" overflow first.

Also I ran into https://github.com/flutter/flutter/issues/30976, @dkwingsmt are you working on this?

**Comment by dkwingsmt** [comment]
@justinmc Unfortunately I've paused the investigation on context menu, with reason I've just added to that issue. I plan to come back and implement some critical feature in a non-extensible way, but it'll take quite some time.

**Comment by jamesblasco** [comment]
Hello! I made some proposal that would include this feature.
 https://github.com/flutter/flutter/issues/36985#issuecomment-699691218

**Comment by justinmc** [comment]
This is now possible in the latest master for Android-style text selection menus.  I have an example at https://github.com/justinmc/flutter-text-selection-menu-examples/blob/master/lib/custom_menu_page.dart.

Still working on iOS.
