### ISSUE TITLE
Screen frozen

### ISSUE THREAD

**Issue by dragon2934** [flutter/flutter#31426]
Hi, there:

I am doing a chat App, I use a ListView as a container , 
```
 ListView.builder(
              //  controller: _scrollController,
                shrinkWrap: true,
               // physics: ClampingScrollPhysics(),
                itemBuilder: (context, index) {
return chat_widget(index);
}
```
inside the listview, it will be text message, picture, emoji, avatar. between chat, some time if scrolling the listview (moving up and down to check the message), the screen will frozen
is that a way to capture something ? nothing show at Android Studio's Logcat window .

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-CA)
    • Flutter version 1.2.1 at /Users/xxxxx/Desktop/development/flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • Moto E 4 • ZY224VD7WW                           • android-arm • Android 7.1.1 (API 25)
    • iPhone 6 • 24045FE1-7019-452C-8633-D7C0F098C2DF • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by BondarenkoStas** [comment]
@dragon2934 do you still experience the issue?

**Comment by BondarenkoStas** [comment]
are there specific actions to reproduce it? does that happen often enough to be able to catch it while running it with --verbose flag and paste the output here?

**Comment by dragon2934** [comment]
you can create a chat UI (ListView,) , then keep insert all kinds of
widgets (such as Text, Container, Image.network, Icons, ..), then if you
have more than 100 records, then scrolling up or down, it will frozen

**Comment by Hixie** [comment]
I created a chat app UI and added a literally infinite number of items (using ListView.builder, returning a widget for every index) and it didn't freeze.

Please provide the code that shows the problem. Thanks.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
