### ISSUE TITLE
Flutter on Chromebook crash: i965_dri.so 

### ISSUE THREAD

**Issue by opensourcegps** [flutter/flutter#31424]
I can see following crashes in Google Play console, related to i965_dri.so on Chromebook.

Crash 1:
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
update_renderbuffer_surfaces
```
```
Google Chromebook (nami_cheets), Android 7.1
Report 1 of 1
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.appname.app <<<

backtrace:
 
  #00  pc 000000000046775e  /vendor/lib/dri/i965_dri.so (update_renderbuffer_surfaces+1118)
 
  #01  pc 000000000045f609  /vendor/lib/dri/i965_dri.so (brw_upload_pipeline_state+1145)
 
  #02  pc 000000000045f18a  /vendor/lib/dri/i965_dri.so (brw_upload_render_state+26)
 
  #03  pc 000000000044b877  /vendor/lib/dri/i965_dri.so (brw_draw_prims+3831)
 
  #04  pc 00000000001e9519  /vendor/lib/dri/i965_dri.so (vbo_validated_drawrangeelements+345)
 
  #05  pc 00000000001e7ee7  /vendor/lib/dri/i965_dri.so (vbo_exec_DrawRangeElementsBaseVertex+535)
 
  #06  pc 00000000001e703e  /vendor/lib/dri/i965_dri.so (vbo_exec_DrawRangeElements+78)
 
  #07  pc 00000000000051e7  /vendor/lib/egl/libGLESv2_mesa.so (glDrawRangeElements+87)
 
  #08  pc 0000000000036ae1  /system/lib/arm/nb/libtcb.so
```
 
Crash 2:
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
i965_dri.so
```

```
Acer Chromebook R11 (C738T) (cyan_cheets), Android 7.1
Report 1
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.appname.app <<<

backtrace:
 
  #00  pc 000000000046778e  /vendor/lib/dri/i965_dri.so
```

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/flutter/flutter_v1.2.1-stable
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by BondarenkoStas** [comment]
@opensourcegps was the issue solved?

**Comment by opensourcegps** [comment]
Crash 2 still happening with 1.9.1+hotfix.4, always Android 7.1. 
But really small scale bug, I guess not many people run android apps on Chromebook.

**Comment by iapicca** [comment]
Hi @opensourcegps  
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by apecoraro** [comment]
We got this crash, just yesterday, from a user using our app: https://play.google.com/store/apps/details?id=com.rainway&hl=en_US

**Comment by opensourcegps** [comment]
Still hapening on 1.12.13+hotfix.7

**Comment by jonahwilliams** [comment]
It does not appear that there are any flutter frames in the stack above

**Comment by jonahwilliams** [comment]
though it could be a skia GL issue

**Comment by opensourcegps** [comment]
Just to update, I haven't seen this bug in 1.12.13+hotfix.7 yet. But it takes some time to appear as I only switched to this version few days ago. Only "Crash 2" above was happening during the last 60 days.  

![Untitled](https://user-images.githubusercontent.com/7678445/73743542-1e073a00-474f-11ea-8dfb-60a5757803b2.png)

**Comment by chinmaygarde** [comment]
It is unlikely we can make progress on this issue given the lack of any Flutter related frames in the backtrace or a reduced reproducible test case. Closing.
