### ISSUE TITLE
Mention profile and release mode in "Get Started"

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#31439]
See the performance section of https://www.brightec.co.uk/ideas/flutter-answer. 

Maybe put it in https://flutter.dev/docs/get-started/test-drive . We could also do a flow analysis to see how a normal user uses flutter.dev, which page is mostly visited for new developers, etc., to decide the best place to introduce profile and release mode.

**Comment by liyuqian** [comment]
@jayoung-lee : is  https://flutter.dev/docs/get-started/test-drive the right place to first mention "profile" or "release" mode according to our analytics data? Or is it Ok for us to ignore the feedback of adding them to "Get Started" because developers don't read "Get Started" very often, or perhaps those who read "Get Started" always read deeper stuff?

**Comment by jayoung-lee** [comment]
Pages under the "Get Started" section are more popular than any other pages. Other than the landing page, the popularity order is like this:

/docs/get-started/install
/docs/get-started/install/windows
/docs
/docs/get-started/install/macos
/docs/get-started/codelab
/docs/get-started/editor
/docs/development/ui/widgets
/docs/get-started/test-drive
/docs/cookbook
...

I think [codelab](https://flutter.dev/docs/get-started/codelab) or [test-drive](https://flutter.dev/docs/get-started/test-drive) is a good place to briefly mention about the release mode. It seems like less than half of the readers of "Get Started" read other docs..

**Comment by liyuqian** [comment]
Thank you so much @jayoung-lee ! That statistics is really really helpful. I'm [adding profile mode info](https://github.com/flutter/website/pull/2608) to codelab and test-drive so more than half of our readers wouldn't miss it.

**Comment by jayoung-lee** [comment]
Awesome! Thanks :)
