### ISSUE TITLE
Show raster thread frame rasterization times in Flutter Inspector (IDE plugin)

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#31444]
Currently the Flutter Inspector only shows the UI thread frame time in the "Frame rendering time" section of "Performance" panel.

**Comment by liyuqian** [comment]
@devoncarew : can you please specify what's missing in the engine that would enable the IDE plugin to do this?

**Comment by liyuqian** [comment]
CC @kenzieschmoll @jacob314

**Comment by goderbauer** [comment]
I believe this is available in devtools.
