### ISSUE TITLE
Support BoxHeightStyle option for text selection in TextField and CupertinoTextField 

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#31459]
GetRectsForRange already supports various styles of vertical and horizontal boxes, but this is not easily accessible in the framework.

We should add properties to expose this in TextField and CupertinoTextField.

We currently just default to BoxHeightStyle.tight, which often produces uneven selection boxes. TextPainter.getSelectionBoxes() should take a box height style and pass it into dart:ui's Paragraph.getBoxesForRange()

**Comment by GaryQian** [comment]
Extracted from https://github.com/flutter/flutter/issues/21679

**Comment by harshvardhan-takawale** [comment]
Hey @GaryQian ! I'm new here. Can I give this one a try?

**Comment by GaryQian** [comment]
Sure! Let me know if you need any assistance or guidance! This should be relatively straightforwards, mostly just passing a property around. Be sure to follow our style guide (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) and make sure things are well documented and tested.

I'd be happy to review and provide feedback.

**Comment by sharmahit40** [comment]
hello  i am Sharma. i work in a [digital marketing agency in lucknow](https://creativekaam.com). i have written articles on [nautical outdoor lighting](https://marinetreasury.com/nautical-outdoor-lighting), [nautical decor](https://marinetreasury.com/how-to-decorate-restaurant-natutical-decor-items), [nautical searchlight](https://marinetreasury.com/product/original-ships-search-light), [Website Development in lucknow](https://creativekaam.com/website-designing-and-development) and [online earning site](https://creativekaam.com/online-earning-site). I studied in [degree college in allahabad](https://rizvigroup.org)​​​​​​​.

**Comment by GaryQian** [comment]
@sharmahit40 Please keep conversation relevant to the topic. Thanks!

**Comment by MarkBe999** [comment]
> GetRectsForRange already supports various styles of vertical and horizontal boxes, but this is not easily accessible in the framework.
> 
> We should add properties to expose this in TextField and CupertinoTextField.
> 
> We currently just default to BoxHeightStyle.tight, which often produces uneven selection boxes. TextPainter.getSelectionBoxes() should take a box height style and pass it into dart:ui's Paragraph.getBoxesForRange()

**Comment by GaryQian** [comment]
Features were added to support this in #48917
