### ISSUE TITLE
FirebaseMessaging.getToken() to return an error when "Google APIs" dependency is not available

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter#31465]
I wasted multiple hours troubleshooting why my app (running under Android Emulator with API 21 and no Google APIs) was not receiving push notifications sent through the Firebase Cloud Messaging console.  It turns out that Google Services are required for receiving push notifications.  Switching to API 21 with Google APIs solved the problem.  How about saving other engineers time by doing one or both of the following:

1. Point out in the [firebase_messaging webpage](https://pub.dartlang.org/packages/firebase_messaging) that Google APIs are required to receive push notifications on Android.
2. Make FirebaseMessaging.getToken() return an error if Google APIs are not available, since there will never be any hope of receiving a push notification on that device.  Document the type of exception that is returned in that case so the app can handle it appropriately.

**Comment by TahaTesser** [comment]
Hi @mleonhard 
Given the  [comment](https://github.com/flutter/flutter/issues/31465#issuecomment-542744596) above
I feel safe to close this issue
Thank you
