### ISSUE TITLE
unclear how to use flutter build.

### ISSUE THREAD

**Issue by gregsimon** [flutter/flutter#3146]
$ flutter build
Missing subcommand for "flutter build".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

--> what are the subcommands? flutter -h is no help:
...
Available commands:
  analyze      Analyze the project's Dart code.
  build        Flutter build commands.
...

**Comment by abarth** [comment]
@devoncarew

**Comment by abarth** [comment]
`flutter build -h` shows the subcommands.  Probably `flutter build` should print its own help by default.

**Comment by sethladd** [comment]
Dupe of https://github.com/flutter/flutter/issues/3145
