### ISSUE TITLE
How can I send custom data in a request to firestore?

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#31470]
In the security rules for Firestore, I get access to a variable `request`, which has the very useful `request.auth` property, which all rules are base off. Obviously, by authenticating normally through Firebase, I can specify certain fields of `request.auth`, but what if I want my own custom fields? I was redirected to [custom claims](https://firebase.google.com/docs/auth/admin/custom-claims) but this requires setting up a server, which I do not want/feel is necessary. I don't need or want a whole server just to parse some data easily available in the UI. 

My login screen needs to be very simple -- just a username and a password. I already wrote the UI, logic, etc., but I can't seem to figure out how to use Firebase_auth to sign in with **just** a username and password. My security rules are written to expect `request.auth.username` and `request.auth.password`. Any help is appreciated.

**Comment by Levi-Lesches** [comment]
Might I add, I tried subclassing `AuthCredential` (by first giving it a proper constructor), and got an error. 

In the [original code](https://github.com/flutter/plugins/blob/master/packages/firebase_auth/lib/src/auth_credential.dart), the `AuthCredential` class looks like this: 

<pre>
class AuthCredential {
  AuthCredential._(this._provider, this._data);
  final String _provider;
  final Map<String, String> _data;
}
</pre>

I added a public constructor like so: 
<pre>
class AuthCredential {
  AuthCredential(this._provider, this._data);
  AuthCredential._(this._provider, this._data);
  final String _provider;
  final Map<String, String> _data;
}
</pre>

Then, in my code, I wrote a method to sign in: 
<pre>
import "package:firebase_auth/firebase_auth.dart";
void signin() async {
    final FirebaseAuth auth = FirebaseAuth.instance;
    final AuthCredential cred = AuthCredential (
        "the-name-of-my-provider",
        {
            "username": "my-username",
            "password": "my password"
        }
    );
    await auth.signInWithCredential(cred);
}
</pre>

Upon importing and calling this method, I get an error: 
<pre>
E/flutter (10267): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, null reference, null)
E/flutter (10267): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (10267): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): #2      FirebaseAuth.signInWithCredential (file:///C:/Users/my_user/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.4+5/lib/src/firebase_auth.dart:278:54)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): #3      signin (package:my_package/backend/auth.dart:51:13)
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): #4      LoginState.loginWithFirebase (package:my_package/widgets/login.dart:183:3)   // My UI call
E/flutter (10267): <asynchronous suspension>
E/flutter (10267): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (10267): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (10267): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (10267): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (10267): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (10267): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
E/flutter (10267): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (10267): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (10267): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
E/flutter (10267): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (10267): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (10267): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (10267): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (10267): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (10267): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10267): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (10267): #21     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (10267): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
</pre>

Here is the output of flutter doctor -v: 
<pre>
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.2.1 at C:\Users\my_user\flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\my_user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files (x86)\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files (x86)\Android
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 32-bit edition (version 1.26.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.15.0

[√] Connected device (1 available)
    • SM G950U1 • 988861314d554d4f52 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
</pre>

Although I will note that, despite `No Issues found!`, Flutter keeps telling me `This is taking an unexpectedly long time`, along with deleting a couple of lines of log info, despite me manually overriding the `logger.dart` file, which is a whole different issue

**Comment by BondarenkoStas** [comment]
@Levi-Lesches Please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close it here.

**Comment by Levi-Lesches** [comment]
Thanks for reminding me about this. [Custom claims](https://firebase.google.com/docs/auth/admin/custom-claims) are now available to all using the Admin SDK, so this is essentially closed. 

Also, I switched to using Google Sign in.
