### ISSUE TITLE
[camera] - Requesting just Camera Permission

### ISSUE THREAD

**Issue by daimionsg** [flutter/flutter#31477]
Is it possible to get the camera plugin to only request camera permission if not using it for video recording?

The plugin is perfect for my requirements - having a camera preview in a widget. However, the automatic request for microphone permission when just taking a photo has been putting some users off.

**Comment by gellnerm** [comment]
Same situation here.

**Comment by panzerwurst** [comment]
You can request camera permission only by passing the parameter `enableAudio: false` to the `CameraController` (works in 0.5.2+1).

**Comment by bparrishMines** [comment]
As it says above, there is now an `enableAudio` parameter in `CameraController`. Closing

**Comment by amnourius** [comment]
Nope adding it won't delete RECORD_AUDIO from manifest permissions
