### ISSUE TITLE
Motion JPEG stream cannot play on ios

### ISSUE THREAD

**Issue by VishvaRatnayake** [flutter/flutter#31478]
I'm new to flutter and i'm making an app to view live camera stream (Motion JPEG )
i used flutter_webview_plugin 0.3.4 for this and here is my code
```
String component =
          '<html><body><img width="100%"  src="' + streamUrl + '"></body></html>'`
`WebviewScaffold(
            appBar: AppBar(
              title: Text("Live " + camera.name),
            ),
            url: new Uri.dataFromString(component,
                    parameters: {'charset': 'utf-8'}, mimeType: 'text/html')
                .toString());
```

above code is perfectly working on android but not in ios and there is nothing in the logs  
help me, Thanks!

```
```

```
```

```
```

**Comment by BondarenkoStas** [comment]
@VishvaRatnayake did you manage to fix it?

**Comment by VishvaRatnayake** [comment]
yes , i found another way but couldn't play it in the webview

**Comment by BondarenkoStas** [comment]
Just flutter_webview_plugin belongs to flutter community, not to flutter. You can file the issue to https://github.com/fluttercommunity/flutter_webview_plugin/issues. I'm afraid flutter team can't do anything with it, so I think it's safe to close the issue. Thank you!
