### ISSUE TITLE
MyWebsocket need handle ping pong

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#31480]
Hello, We need to know when was ping and pong.
I also looked at the WebSocket class from the dart.io package and could not send where pingInterval is used. The _WebSocketImpl implementation is closed.
The problem is that the connection often disappears in GoingAway if the ping interval is below 10 seconds

**Comment by kf6gpe** [comment]
That sounds like something for the Dart repository itself, rather than being specific to Flutter. If you have a moment, could you please file it over at https://github.com/dart-lang/sdk? Thanks!

**Comment by 1AlexFix1** [comment]
> That sounds like something for the Dart repository itself, rather than being specific to Flutter. If you have a moment, could you please file it over at https://github.com/dart-lang/sdk? Thanks!

Yes, you right
