### ISSUE TITLE
packages get in vscode fails, works on cmd line

### ISSUE THREAD

**Issue by j1dopeman** [flutter/flutter#31482]
I am behind a proxy and I have set the http & https_proxy environment variables. I'm on windows using vscode as my editor. If I try to create a new project from within vscode or make a change to the pubspec file then it will hang at:

Running "flutter packages get"
Get socket error trying to find package cupertino_icons at https://pub.dartlang.org.
pub get failed (69) -- attempting retry

Hitting cancel on the little window for the extension does not actually cancel it. I have to force close various processes so the startup lock will let me do it from the cmd line.

In the project folder at the cmd line I run "flutter packages get" and it will connect and update without errors. Takes about 20 seconds.

Is there something about the dart extension for visual studio that makes it ignore the proxy settings? I'm running everything as Administrator.

**Comment by nsmith1024** [comment]
Wow, i have the same problem just now

**Comment by BaderEddineOuaich** [comment]
Please try run the command: `` flutter clean && pub cache repair ``

**Comment by j1dopeman** [comment]
`flutter clean` doesn't fix it. `pub` is not recognized as a command and `flutter pub` doesn't have a cache repair option.

**Comment by j1dopeman** [comment]
Use `setx` not `set` to make env variables. Then restart anything that needs to look at it.
