### ISSUE TITLE
Multiple Navigators with BottomNavigationBar

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#31483]
There is no clear way to achieve multiple navigators with BottomNavigationBar.

How to make BottomNavigationBar sticking around throughout navigation changes?

How to keep my previous visited screens in navigation stack as in Youtube and Instagram apps?

**Comment by HansMuller** [comment]
Here's an example of a BottomNavigationBar that selects "pages", where each page has its own Navigator: https://gist.github.com/HansMuller/0e76c54b1f2d4423efbdc2c185e761ef

Is this the kind of thing you're trying to do?

**Comment by mohamed6996** [comment]
There is a big problem with this solution. The TextInput, You can’t focus it properly and the keyboard will not open in case of Home and Business tabs, although,  it appears in the School tab.
its seems that it focuses only in the last child in the IndexedStack widget

**Comment by HansMuller** [comment]
I'm not seeing any problems with keyboard focus and [this example](https://gist.github.com/HansMuller/0e76c54b1f2d4423efbdc2c185e761ef). However, a fix for FocusScope that was only added at the end of January is needed: https://github.com/flutter/flutter/pull/27365. What version of Flutter are you testing on?

**Comment by mohamed6996** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

**Comment by HansMuller** [comment]
Flutter 1.0 doesn't include the FocusScope fix (#27365) needed for nested navigators and scaffolds.  If you upgrade to a more recent release or build against the current repo, all should be well.

**Comment by mohamed6996** [comment]
I updated flutter to v1.2.1 and the problem is solved. Thnx alot <3 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by HansMuller** [comment]
Glad to hear that! I'm going to close this issue.
