### ISSUE TITLE
[google_maps_flutter]  Ability to hide the buttons which center the map when MyLocationEnabled is true

### ISSUE THREAD

**Issue by JackLillie** [flutter/flutter#31488]
Is it possible to remove the buttons to center the map when MyLocationEnabled is true? For example, on iOS, the button is at the bottom right and on Android it is at the top right. I was going to design my UI to cover the buttons up but there is no way to cover up the bottom right and top right. If this isn't possible, is there another way to put a marker where the user currently is a constantly update it?

**Comment by stuartmorgan** [comment]
Closing as obsolete; `myLocationButtonEnabled` was added a while ago.
