### ISSUE TITLE
Analyze the output of `flutter create --with-driver-test`

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3149]
After running `flutter create --with-driver-tests .`:

![screen shot 2016-04-06 at 1 47 42 pm](https://cloud.githubusercontent.com/assets/5479/14332400/3c53ec2e-fbfe-11e5-8575-f6a48ac9ff51.png)

**Comment by sethladd** [comment]
cc @yjbanov

**Comment by Hixie** [comment]
When fixing this, please make sure that part of the fix is to put the file under analysis itself so that we catch any future changes that need to be made.

**Comment by sethladd** [comment]
@Hixie good call

**Comment by yjbanov** [comment]
(still need to hook it up to the analyzer)
