### ISSUE TITLE
firebase_messaging with local notification

### ISSUE THREAD

**Issue by minh98** [flutter/flutter#31492]
i know firebase_messaging can't work fine with local notification pub.
let me know solution about using firebase_messaging with local notifi feature or you must create similar feature inside firebase_messaging package. please !

**Comment by minh98** [comment]
react-native can work fine firebase_msg and local notifi. why flutter can't ?

**Comment by devadrianapostol** [comment]
I think the firebase_messaging isn't updated to work with Android X

**Comment by minh98** [comment]
i had a issue about notification,
i want to receive notifi from firebase and schedule notifi daily offline :( 
i can't do it :( pls fix it

**Comment by AppleEducate** [comment]
@minh98 have you tried creating local notification from a data message? instead of firebase message. The data message from firebase does not send the notification and can let you customize how to deliver it!

**Comment by kroikie** [comment]
@minh98

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1062. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
@minh98 do you still encounter the issue?
