### ISSUE TITLE
Measure EngineLayer size

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#31498]

**Comment by dnfield** [comment]
SkPicture gives an approximate size that doesn't include images or fonts.

If we know the image(s) in a layer, we should be abel to figure out the bytes (4 * w * h).

I'm not sure about fonts.

The bigger concern to me is how to do this without hurting frame time.

**Comment by dnfield** [comment]
Would it be worth pooling engine layers rather than trying to get them collected more agressively?

**Comment by liyuqian** [comment]
Since we're only providing an estimation, I guess that we don't need to be very accurate and we can lazily update our estimation.

One economic way of updating the estimation is to do it during `Layer::Paint` tree walk. As long as we have a good estimation for SkPicture and SkImage, we should be able to estimate `EngineLayer` size with a latency of at most 1 frame, without increasing the computational complexity.

The latency is probably good enough since GC wouldn't happen that frequently. My only concern is when  Dart GC reads that estimation. Does it only read it during the EngineLayer construction? We can't measure that during construction since its children are unknown. @jason-simmons @bkonyi @rmacnak-google 

Finally, if we concluded that https://github.com/flutter/flutter/issues/31303 and https://github.com/flutter/flutter/issues/29007 are not caused by this, I may lower the severity of this issue by removing the `severe: performance` tag.

**Comment by rmacnak-google** [comment]
@liyuqian The engine reports the external size to the VM when it creates the finalizer for the Dart wrapper object, i.e. the first time an `EngineLayer` is returned to Dart. There is currently no mechanism to update the external size associated with a handle once set, but it is possible to effectively increase the external size of an object by creating an additional finalizer. If the size of an `EngineLayer` can change significantly over its lifetime, we should probably add an API to inform the VM of these changes.

**Comment by jonahwilliams** [comment]
We no longer provide size estimates to dart for GC as it ended up being counterproductive.
