### ISSUE TITLE
Hot restart ignores the "entryPoint" parameter from FlutterArguments

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#31490]
I am trying to run Flutter in background. For that, I am creating a new flutter native view from an Android Service like this:

```
	private fun startFlutterBackground() {
		if (backgroundView != null) return

		FlutterMain.ensureInitializationComplete(this.applicationContext, null)

		// Note that we're passing `true` as the second argument to our
		// FlutterNativeView constructor. This specifies the FlutterNativeView
		// as a background view and does not create a drawing surface.
		val sBackgroundFlutterView = FlutterNativeView(this.applicationContext, true)
		val args = FlutterRunArguments()
		args.bundlePath = FlutterMain.findAppBundlePath(this.applicationContext)
		args.entrypoint = "backgroundMain"
		sBackgroundFlutterView.runFromBundle(args)
		GeneratedPluginRegistrant.registerWith(sBackgroundFlutterView.pluginRegistry)
		backgroundView = sBackgroundFlutterView

	}

	companion object {
		private val TAG = "SyncService"
		var backgroundView: FlutterNativeView? = null
	}
```

As you cann see I am setting the `args.entrypoint = "backgroundMain"`.
This is a method I create on my main.dart file:

```
void main() {
  print("IT IS RUNNING DART IN FOREGROUND!");
  runApp(MyTestApp(isBackground: false));
}

void backgroundMain() {
  print("INT IS RUNNING DART BACKGROUND!");
  runApp(MyTestApp(isBackground: true));
}
```

Everything works fine until I hit the HOT RESTART button on my IDE. It reloads both flutter views by calling the "main" method and ignoring the "entrypoint" parameter I've set before.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [versÃ£o 10.0.17763.437], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.30.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by 2dxgujun** [comment]
+1, I just got the same problem

**Comment by 2dxgujun** [comment]
I just figure out a way that you can use a special `defaultRouteName` like `backgroundMain` to start the background isolate.

**Comment by shinayser** [comment]
> I just figure out a way that you can use a special `defaultRouteName` like `backgroundMain` to start the background isolate.

Can you provide a sample, please?

**Comment by 2dxgujun** [comment]
```dart
/// main.dart
void main() {
  if (window.defaultRouteName == 'backgroundMain') {
    print("INT IS RUNNING DART BACKGROUND!");
    runApp(MyTestApp(isBackground: true));
  } else {
    print("IT IS RUNNING DART IN FOREGROUND!");
    runApp(MyTestApp(isBackground: false));
  }
}
```

```java
mFlutterNavigationChannel = new MethodChannel(mBackgroundFlutterView, "flutter/navigation",
        JSONMethodCodec.INSTANCE);
mFlutterNavigationChannel.invokeMethod("setInitialRoute", "backgroundMain");

FlutterRunArguments args = new FlutterRunArguments();
args.bundlePath = FlutterMain.findAppBundlePath(appContext);
args.entrypoint = "main";
mBackgroundFlutterView.runFromBundle(args);
```

**Comment by xster** [comment]
Breadcrumbs leaving from @jonahwilliams:

"
Oh I see, yeah we need to expose the entrypoint param to the frontend server

https://github.com/dart-lang/sdk/blob/master/pkg/vm/lib/frontend_server.dart#L123

We'll need to add support for an `--entrypoint` option or similar
"

**Comment by jonahwilliams** [comment]
cc @aam

**Comment by jonahwilliams** [comment]
From looking at the code it isn't clear to me if there is any existing support for compiling non-main entrypoints

**Comment by aam** [comment]
Not sure - why compiler needs to know the entrypoint function name? Compiler just takes dart sources(files) and produces kernel binary file(think AST) which is then passed to VM for reloading, for engine to invoke some entrypoint.

**Comment by jonahwilliams** [comment]
Ahh, if the compiler doesn't care about the specific main then that is not an issue. The other issue would be making sure we can communicate this information on the reload/restart protocol

**Comment by xster** [comment]
@RedBrogdon also tagging you on this. We should have a sample with non-default entrypoint somewhere

**Comment by matthew-carroll** [comment]
@stevemessick have you had a chance to look into this at all? Do you think we're still on pace for the listed milestone?

**Comment by stevemessick** [comment]
@matthew-carroll Sorry for the late reply; was OOO. It looks like we don't need any changes in the IDE now since this has been fixed in the engine.

**Comment by xster** [comment]
woohoo, awesome fix. Thanks @gaaclarke
