### ISSUE TITLE
Wrong script is run when right-click on driver test and choose "Run Application"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3150]
I have a test_driver/main_test.dart file in my project. I've opened that project in Atom. I'm not clear how to run this via Atom.

I tried right-clicking on main_test.dart and choosing "Run Application", but that kicked off:

```
flutter run --checked --debug-port=16162 --start-paused --device-id 84B7N15A07007628 • flutter logs
awesomesauce/ • checked mode • debug
Building APK...
Warning: signing the APK using the debug keystore.
Generated APK to build/app.apk.
Installing app.apk on device.
Running lib/main.dart on Nexus 6P...
Showing Nexus 6P logs:
--------- beginning of system
--------- beginning of main
W/ActivityManager: Permission Denial: getCurrentUser() from pid=22034, uid=10141 requires android.permission.INTERACT_ACROSS_USERS
W/ActivityManager: Permission Denial: getCurrentUser() from pid=22034, uid=10141 requires android.permission.INTERACT_ACROSS_USERS
```

Which isn't what I expected.

I see a comment in main_test.dart: `flutter drive --target=test_driver/main_test.dart`, but I don't know how to run that command via Atom. Can I add that to .atom/main.yaml  as a supported run configuration?

**Comment by sethladd** [comment]
cc @yjbanov

**Comment by eseidelGoogle** [comment]
I don't think Atom has been taught about flutter drive (or flutter test for that matter).  FYI @devoncarew.  I suspect these will just be command-line only and a small wart in our Atom support for a while.

**Comment by sethladd** [comment]
I'm OK with Atom not formally supporting it. But I wonder what we can do to make Atom not run `flutter run` if you right click on the driver test and choose "Run application"

**Comment by devoncarew** [comment]
Yeah, that part we should fix.

**Comment by yjbanov** [comment]
Why should we prevent the developer from being able to launch a driver test app from Atom? After all, it is a plain Flutter app. In some situations a developer might need to debug the test app for a while before they run the driver test. For example, perhaps they want to mock out HTTP with canned data (UI-only integration tests generally won't have a server to talk to).

**Comment by sethladd** [comment]
> Why should we prevent the developer from being able to launch a driver test app from Atom? After all, it is a plain Flutter app.

If you can teach us how to launch it, we might be able to edit the main.yaml file used by Atom to control launches.

**Comment by yjbanov** [comment]
Sorry, misunderstanding on my part. We should allow the developer to launch the _app under test_ from Atom, but not the _driver test_, for now. So yes, I fully agree with

> make Atom not run flutter run if you right click on the driver test and choose "Run application"

**Comment by sethladd** [comment]
Going to close this in favor of the IntelliJ plugin.
