### ISSUE TITLE
image_picker sometimes returns empty image

### ISSUE THREAD

**Issue by aerozavr** [flutter/flutter#31509]
image_picker sometimes(~ 1 of 4 times) returns empty image from camera on Xiaomi Redmi 5.

**Comment by BaderEddineOuaich** [comment]
i believe its the device's camera app cashe issue. could you clear its cashe and try again .

**Comment by aerozavr** [comment]
False alarm I guess - when re-running the app the image is there.

**Comment by aerozavr** [comment]
I guess this is not image_picker's issue.

**Comment by TahaTesser** [comment]
Hi @aerozavr 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
