### ISSUE TITLE
[video_player] plugin should expose a Stream of change events instead of callbacks

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#31504]
From a comment on flutter/plugins#1531

Exposing a `Stream` of notification events on the `VideoPlayerController` would support `StreamBuilder` based widget hierarchies and that might make it easier for the developer to register and unregister safely.

This might be a breaking change to the plugin API.

**Comment by Hixie** [comment]
I think if we did anything like that it should probably just be a Listenable. Streams have all kinds of problems.

Is this still something we think we should do?

**Comment by collinjackson** [comment]
It doesn't seem like a priority to me, based on low activity on this issue.

**Comment by stuartmorgan** [comment]
I'm assuming this is resolved since the controller is a value notifier now.
