### ISSUE TITLE
Test performance has regressed

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#31511]
Caused by https://github.com/flutter/flutter/pull/31207

cc @chunhtai

**Comment by jonahwilliams** [comment]
We can try applying a [Fingerprinter](https://github.com/flutter/flutter/blob/3c8c630f0106b7fca95301d5ad380eab3d930f71/packages/flutter_tools/lib/src/base/fingerprint.dart#L33) to the assets and skip the build if that passes.

As a last resort (though I ad suggested not to do this in part because of the complexity/duplication), we can teach the flutter_tool how to look up each asset from disk directly. The flutter_tool and flutter_test cannot share code however, so the logic would need to be duplicated and tested heavily so that it was kept in sync.

**Comment by Hixie** [comment]
We could also default to off, since most tests don't need this.

**Comment by jonahwilliams** [comment]
> since most tests don't need this.

I think there is some survivorship bias there, since assets haven't ever been supported in tests.

**Comment by chunhtai** [comment]
A lot of test pass because the assets never load. It might cause flakiness without this patch. I will try to come up with a better solution

**Comment by chunhtai** [comment]
Merged, let's see if this fixes it

**Comment by Hixie** [comment]
Doesn't seem to have helped, but it's hard to tell for sure.

**Comment by jonahwilliams** [comment]
We should disable the flag by default to make the work opt-in. I'm concerned this is going to hurt discoverability of the feature - which is incredibly useful for real applications.


Also If we can switch back to the app-jit snapshots we'll get back the lost performance and then some.

**Comment by chunhtai** [comment]
One thing that might worth point out is, the real assets loading also take time in the test. Before this change, the assets loading is stuck at waiting future to finish. so the asset does not really load. Now, the assets does get loaded synchronously. which will actually take times to load. I am not sure whether the time increase is in building the assets or actually assets loading during test.
if it is the later, one other thing I can try will be making the assets load asynchronically. It will not spending time loading during the test unless user use tester.runAsync if they really want to test the assets load. What do you think?

**Comment by jonahwilliams** [comment]
The hello_world example that the benchmark runs on does not use assets, so ideally this change would not regress that time. Maybe we need one more short circuit for an empty asset manifest?

**Comment by Hixie** [comment]
(I've rebaselined the relevant tests, so that we can see further regressions; that doesn't impact the validity of this bug.)

**Comment by chunhtai** [comment]
Merged, let's see if that improve

**Comment by chunhtai** [comment]
I have seen the test performance drop down to normal since yesterday afternoon. Looks like we are good now. Closing this issue
