### ISSUE TITLE
Directory fails to create path

### ISSUE THREAD

**Issue by ezequielgonzalez16** [flutter/flutter#31516]
Version info:
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (10 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

I'm developing an app for iOS, which will have to capture and store images as png files on the device storage. I wanted to create a folder to place them accordingly, however when I try to do so I get an Error that says "No such file or directory". I followed the examples given in this documentation page: https://docs.flutter.io/flutter/dart-io/Directory-class.html

## Steps to Reproduce

This is the code I'm running:

```
static void createDirectory() async {
     var path = await _localPath;
     Directory('$path/CapturedImages').create(recursive: true);
 }

static Future<String> get _localPath async {
    final directory = await getApplicationDocumentsDirectory();
    return directory.path;
}
```

My intention is to simply create a folder to store my images. However I get the following log

## Logs
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Creation failed, path = '/Users/ezequiel/Library/Developer/CoreSimulator/Devices/862DEB82-7DA5-48A1-871E-2E88DDFA3310/data/Containers/Data/Application/AAA8A719-4FEB-456B-ABB8-E58D335076F1/Documents/GameImages' (OS Error: No such file or directory, errno = 2)
#0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:122:11)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zon<…>

## -
```
I KNOW that the path returned by "_localPath" exists, I can print it, and I can create and store files in it. Also, according to the documentation, sending the parameter of "recursive" as true should create the missing folders. To this I quote the documentation: 

> If [recursive] is true, all non-existing path components are created.

This also occurs with the File class. I'm I doing something wrong or is this simply not working as it should?

**Comment by wyattbiker** [comment]
Try it an android emulator. I tested same on Android emulator. Worked fine no errors. Checked folder and it does exist.

```
~$ adb shell
1|generic_x86:/ $ run-as com.example.fl_create_dir
generic_x86:/data/data/com.example.fl_create_dir $ ls
app_flutter cache code_cache files lib
generic_x86:/data/data/com.example.fl_create_dir $ cd app_flutter
generic_x86:/data/data/com.example.fl_create_dir/app_flutter $ ls -lsa
total 24
4 drwxrwx--x 5 u0_a86 u0_a86 4096 2019-04-24 11:55 .
8 drwx------ 6 u0_a86 u0_a86 4096 2019-04-24 11:34 ..
4 drwx------ 2 u0_a86 u0_a86 4096 2019-04-24 11:34 CapturedImages
4 drwx------ 2 u0_a86 u0_a86 4096 2019-04-24 11:34 flutter_assets
0 -rw------- 1 u0_a86 u0_a86    0 2019-04-24 11:34 res_timestamp-1-1556120049411
generic_x86:/data/data/com.example.fl_create_dir/app_flutter $
```

**Comment by sgon00** [comment]
I tried your code on both Android and iOS. Both worked fine. 

## Partial Code

```dart
  Future<String> get _localPath async {
    final Directory directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  Future<void> _createDirectory() async {
    final String path = await _localPath;
    final Directory directory = await Directory('$path/CapturedImages').create(recursive: true);
    print("The directory $directory is created");
  }
```

Note: `recursive: true` is useless here because the path is the root path.

## Android test

flutter run output:

```
An Observatory debugger and profiler on MI ... is available at: http://127.0.0.1:55635/
I/flutter (17346): The directory Directory: '/data/user/0/com.example.tmp/app_flutter/CapturedImages' is created
```

adb shell:

```
$ run-as com.example.tmp
/data/data/com.example.tmp $ ls
app_flutter cache code_cache files 
/data/data/com.example.tmp $ cd app_flutter/                                                                                                                                                                                          
/data/data/com.example.tmp/app_flutter $ ls
CapturedImages flutter_assets flutter_shared res_timestamp-1-1557038725066
```

## iOS test

flutter run output:

```
Running pod install...                                              1.8s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           2.6s
 └─Compiling, linking and signing...                         6.2s
Xcode build done.                                           12.9s
flutter: The directory Directory: '/Users/user/Library/Developer/CoreSimulator/Devices/25634A5D-EBFB-4A21-A6C9-742B66C558DC/data/Containers/Data/Application/B2AB9AA1-F9AD-4B55-AE89-FC8EB62B045E/Documents/CapturedImages' is created
```

Directory check in terminal:

```
$ cd /Users/user/Library/Developer/CoreSimulator/Devices/25634A5D-EBFB-4A21-A6C9-742B66C558DC/data/Containers/Data/Application/B2AB9AA1-F9AD-4B55-AE89-FC8EB62B045E/Documents/CapturedImages

[~/Library/Developer/CoreSimulator/Devices/25634A5D-EBFB-4A21-A6C9-742B66C558DC/data/Containers/Data/Application/B2AB9AA1-F9AD-4B55-AE89-FC8EB62B045E/Documents/CapturedImages]$ pwd
/Users/user/Library/Developer/CoreSimulator/Devices/25634A5D-EBFB-4A21-A6C9-742B66C558DC/data/Containers/Data/Application/B2AB9AA1-F9AD-4B55-AE89-FC8EB62B045E/Documents/CapturedImages
```

**Comment by TristanWYL** [comment]
@ezequielgonzalez16 Hi, I came across with this exact issue, but it only happens after I updated my iOS app. Please check out my post #39221 . I wonder how did you fix this.

**Comment by BondarenkoStas** [comment]
@ezequielgonzalez16 Please try relative path as in https://github.com/flutter/flutter/issues/39221#issuecomment-529844432.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by neenabastin123** [comment]
I am now with the same issue, I created a simple program and created a folder 
 Future<String> get _localPath async {
    final Directory directory = await getApplicationDocumentsDirectory();
    return directory.path;
  }

  Future<void> _createDirectory() async {
    final String path = await _localPath;
    final Directory directory = await Directory('$path/CapturedImages').create(recursive: true);
    print("The directory $directory is created");
  }

D/EGL_emulation(14006): eglMakeCurrent: 0xeaff6780: ver 3 1 (tinfo 0xc942c8e0)
I/flutter (14006): The directory Directory: '/data/user/0/quadauq.ffmpeg_examplebyneena/app_flutter/CapturedImages' is created
D/EGL_emulation(14006): eglMakeCurrent: 0xeafc6d40: ver 3 1 (tinfo 0xdf9af9b0)

Showing as a success, but I cannot see application folder or the created folder anywhere in Andrid/data - can anyone help?
![filenotfound](https://user-images.githubusercontent.com/32053152/91143825-bdcaec00-e6d0-11ea-96e0-3cd1578b2969.PNG)
