### ISSUE TITLE
How to obtain the logs of "Building flutter tool..." ?

### ISSUE THREAD

**Issue by LiteKat** [flutter/flutter#31519]
1.Run "flutter upgrade --verbose" in terminal
2. Everything logs fine until the part where "Building flutter tool..." stays there [works without logging anything ], when it reaches a certain point my system freezes . It might be a package installed in my system that is doing some shady work with flutter so i wanna fix it since i have searched for this particular error everywhere and it seems to be pc-related so it's not in the search results -.-

So... is there a way of logging what happens when flutter "builds" it's tool ?

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`.

When building the flutter tool, we're using the dart compiler's ability to generate a snapshot of code. There are no logs generated by this process, as it is only doing compilation and not, say, downloading binaries.

It definitely shouldn't be freezing though

**Comment by LiteKat** [comment]
When it freezes my system i have to "REISUB" ir, so when the pc boots again and type any flutter related command , it says "Building flutter tool..." again and then freezes again. 

The only solution i have found is to manually download the zip from https://flutter.dev/docs/development/tools/sdk/releases and then replace the content in my flutter folder with that.

However, when using flutter commands, the freeze is random, it can happen when i run an app , i attach an app, i analyze a file,etc so i think i should buy a new computer ;-;.

I have tried using a fresh instalation of lubuntu 18.10 and 19.04 , using multiple flutter versions [manually downloaded] , i even thought it was my bios so i update it . I don't know what flutter or dart does but it's freezing my pc D: it doesn't happen with other program or at least i have not found it , if it happens with other program then at least i would like to know what is dart doing to my system .

The doctor output seems normal [replaced sensitive information]

>  [✓] Flutter (Channel dev, v1.5.4, on Linux, locale ....UTF-8)
>     • Flutter version 1.5.4 at /home/.../flutter
>     • Framework revision b593f5167b (2 days ago), 2019-04-22 07:51:33 -0700
>     • Engine revision ca31a7c57b
>     • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /home/.../Android
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /home/.../Android
>     • Java binary at: /home/.../Java/jdk1.8.0_212/bin/java
>     • Java version Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
>     • All Android licenses accepted.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 2 categories.

**Comment by LiteKat** [comment]
Using script to capture some extensive logs i have found that the las that i can get is this part 

> MSG : Precompiling executables...
> IO  : Writing 33 characters to text file ./.dart_tool/pub/bin/sdk-version.
> FINE: Contents:
>     | 2.3.0-dev.0.1.flutter-1f1592edce
> IO  : Deleting directory ./.dart_tool/pub/bin/kernel.
> IO  : Deleting directory ./.dart_tool/pub/bin/coverage.
> IO  : Deleting directory ./.dart_tool/pub/bin/dart_style.
> IO  : Deleting directory ./.dart_tool/pub/bin/completion.
> IO  : Deleting directory ./.dart_tool/pub/bin/linter.
> IO  : Deleting directory ./.dart_tool/pub/bin/archive.
> IO  : Deleting directory ./.dart_tool/pub/bin/test.
> IO  : Deleting directory ./.dart_tool/pub/bin/csslib.
> IO  : Deleting directory ./.dart_tool/pub/bin/build_runner.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/count_breakdown.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/count_breakdown.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/dump.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/dump.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/size_breakdown.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/size_breakdown.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/split.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/split.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/transform.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/transform.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/type_check.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/type_check.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/coverage/collect_coverage.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/coverage-0.12.4/bin/collect_coverage.dart" in /home/User/flutter/packages/flutter_tools/.
> IO  : Spawning "/home/User/flutter/bin/c

as you may notice the last line is incomplete because the script didn't had enought time to write it to the file . However if i try reconstructing it it would be like 

> Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/build_runner/graph_inspector.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/bin/graph_inspector.dart" in /home/User/flutter/packages/flutter_tools/.

That's the last thing that pub returns in the console -.- 

I think i'm gonna use another computer for flutter since i don't want to deal whit this problem that nobody has. Thank you 7u7

**Comment by 1232209** [comment]
I also encountered this problem.

**Comment by Laotree** [comment]
This is my solution :  
1. delete `~/flutter/bin/cache`
2. run `flutter doctor` 
a few minutes later,  the flutter tool will be built .

**Comment by Prn-Ice** [comment]
> Using script to capture some extensive logs i have found that the las that i can get is this part
> 
> > MSG : Precompiling executables...
> > IO  : Writing 33 characters to text file ./.dart_tool/pub/bin/sdk-version.
> > FINE: Contents:
> > | 2.3.0-dev.0.1.flutter-1f1592edce
> > IO  : Deleting directory ./.dart_tool/pub/bin/kernel.
> > IO  : Deleting directory ./.dart_tool/pub/bin/coverage.
> > IO  : Deleting directory ./.dart_tool/pub/bin/dart_style.
> > IO  : Deleting directory ./.dart_tool/pub/bin/completion.
> > IO  : Deleting directory ./.dart_tool/pub/bin/linter.
> > IO  : Deleting directory ./.dart_tool/pub/bin/archive.
> > IO  : Deleting directory ./.dart_tool/pub/bin/test.
> > IO  : Deleting directory ./.dart_tool/pub/bin/csslib.
> > IO  : Deleting directory ./.dart_tool/pub/bin/build_runner.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/count_breakdown.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/count_breakdown.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/dump.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/dump.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/size_breakdown.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/size_breakdown.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/split.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/split.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/transform.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/transform.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/kernel/type_check.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/kernel-0.3.14/bin/type_check.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/coverage/collect_coverage.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/coverage-0.12.4/bin/collect_coverage.dart" in /home/User/flutter/packages/flutter_tools/.
> > IO  : Spawning "/home/User/flutter/bin/c
> 
> as you may notice the last line is incomplete because the script didn't had enought time to write it to the file . However if i try reconstructing it it would be like
> 
> > Spawning "/home/User/flutter/bin/cache/dart-sdk/bin/dart --packages=file:///home/User/flutter/packages/flutter_tools/.packages --snapshot=./.dart_tool/pub/bin/build_runner/graph_inspector.dart.snapshot.dart2 file:///home/User/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/bin/graph_inspector.dart" in /home/User/flutter/packages/flutter_tools/.
> 
> That's the last thing that pub returns in the console -.-
> 
> I think i'm gonna use another computer for flutter since i don't want to deal whit this problem that nobody has. Thank you 7u7

How did you get these logs, please?
