### ISSUE TITLE
NoSuchMehodError: The getter 'pasteButtonLabel' was called on null happened when textField long press

### ISSUE THREAD

**Issue by 7syw** [flutter/flutter#31529]
Hi,

Our app needs to support multi-languages, here is code as below,
  @override
  Widget build(BuildContext context) {
    return _isLoadConfig?new MaterialApp(
      title: 'Oil Loan App',
      theme: new ThemeData(
         primaryColor: themeColor
      ),
      home: new Scaffold(body: showWelcomePage(context)),
      locale: _locale,
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        CustomLocalizations.delegate
      ],
      supportedLocales: CustomLocalizations.supportedLocales,
      onGenerateRoute: Application.router.generator,
    ):new Center(child:CircularProgress());
  }

but we faced the error as below when any textfield long press 
NoSuchMehodError: The getter 'pasteButtonLabel' was called on null 
receiver: null
tried calling: pasteButonLabel

This error happened on iOS, but we never faced it for android which flutter version is 1.0.0. Recently we are going to upgrade to 1.2.1 and expect to solve this issue once flutter is upgraded to 1.2.1. but the test result is still not as expectation. this error not happened on iOS simulator(iOS 12.1 and iPhoneX), but this error happened on iPhone device. the iPhone device is iPhoneX, the iOS version is 12.2. any ideas?

thanks, Yawei

**Comment by lgfranco** [comment]
This is the exact error reported in:
https://github.com/flutter/flutter/issues/13452

**Comment by lgfranco** [comment]
@HansMuller, @xster ins't this resolved by https://github.com/flutter/flutter/pull/32513 ?

**Comment by 7syw** [comment]
solved with a new class to implement CupertinoLocalizations for specified language.
