### ISSUE TITLE
'flutter run' on desktop is not showing stdout/stderr

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#31521]
Example STR:
- `flutter create` a project
- Copy FDE's macos/linux/windows folder into the project (depending on your platform)
- `flutter run`

You should get Dart exception logging from the unknown target platform, but instead there's no feedback about why the UI is blank.

I tested on macOS, but it's probably happening on all three.

**Comment by stuartmorgan** [comment]
Re-opening, since while working on a plugin I'm still seeing a lot of output missing. An example of a message I see when running from Xcode, but not when using `flutter run` is:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<double>'
[... stack trace here ...]
```

My guess is that we're now getting stdout, but not stderr.

**Comment by stuartmorgan** [comment]
> My guess is that we're now getting stdout, but not stderr.

This is definitely it; confirmed via the hack of changing `stdout` to `stderr` in wiring up the logger, at which point that message shows up (although obviously that's not the right fix, since we lose stdout).

**Comment by tttzof351** [comment]
On linux (as target platform) I still can't see result of print or debugPrint in stdout

**Comment by jonahwilliams** [comment]
You need to have updated to the latest flutter master

**Comment by tttzof351** [comment]
I have latest version from master branch
```
Flutter 1.5.9-pre.138 • channel master • https://github.com/flutter/flutter
Framework • revision 1349be95a3 (58 minutes ago) • 2019-05-03 16:02:17 -0400
Engine • revision 88113925e3
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 1577b95c93)
```
Maybe need switch to dev channel flatter?

**Comment by stuartmorgan** [comment]
That should certainly have the fix. Could you file a new issue please for us to track and investigate your specific problem? While the symptoms may be similar, the specific underlying bug that caused what I was seeing was definitely fixed in general, so your issue must have a different cause.
