### ISSUE TITLE
Feature request: Port Moment.js and Moment Timezone to Dart

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#31523]
The DateTime classes provided by the Dart runtime library are okay but lacking many of the features of e.g. Moment and Moment Timezone. It would be great to have a powerful, world-class library for this, either provided by Flutter itself (to integrate properly with iOS/Android native APIs) or as a package.

https://momentjs.com/

**Comment by jonahwilliams** [comment]
Does this package accomplish those goals? https://pub.dartlang.org/packages/timezone

**Comment by dnfield** [comment]
It's not full featured and not moment.js, but I did write a Gregorian calendar package at some point (https://pub.dartlang.org/packages/date_calendar).  There's also intl (https://pub.dartlang.org/packages/intl) which can help with formatting and parsing of DateTimes in various locales.

**Comment by matthewlloyd** [comment]
I took a deep dive into Dart's datetime and timezone libraries, and compared them with Moment and Moment.timezone. This table summarizes what I found. TLDR; Dart has perhaps 2/3 of the features implemented, but they are scattered across various packages, some official, some 3rd party. Most of what I need has already been written (thanks!), but I still think it would be really nice to have one official and comprehensive package. ;)

| Feature                                                | Moment.js / Moment.timezone | Dart                                                                                      |
|--------------------------------------------------------|-----------------------------|-------------------------------------------------------------------------------------------|
| locale-aware datetime formatting                       | yes, 100+ locales           | yes, 100+ locales                                                                         |
| relative time formatting ("5 minutes ago")             | yes, 100+ locales           | use `timeago` package, supports 21 locales                                                  |
| calendar time formatting ("tomorrow at 2pm")           | yes, 100+ locales           | no                                                                                        |
| datetime parsing                                       | yes, RFC 2822               | yes, RFC 3339                                                                             |
| manipulation: add, subtract, durations, etc.           | yes                         | yes                                                                                       |
| humanized duration formatting ("5 minutes 10 seconds") | yes, 100+ locales                         | no                                                                                        |
| timezone database                             | yes                         | use `timezone` package                                                                      |
| timezone names, abbreviations, formatting etc.         | yes                         | use `timezone` package                                                                      |
| get user's timezone                                    | yes                         | use `flutter_native_timezone` package; full compatibility with `timezone` package not guaranteed |

**Comment by stuartmorgan** [comment]
Based on the updated guidance in https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues, I'm going to close this issue, better reflecting the expectation that this is not something that the Flutter team plans to implement.
