### ISSUE TITLE
Feature request: Extend ThemeData with app-specific palettes

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#31522]
It would be nice to be able to extend ThemeData with app-specific palettes. This would allow switching app-specific colors by using the Theme widget, and would coordinate the colors with the existing theme switching mechanisms including animations.

Currently, it's possible to create one's own theme classes using a parallel class hierarchy to the built-in one, but you don't get automatic integration with the animation that AnimatedTheme provides when switching between themes. That means when the user changes the app's theme, the colors of some elements of the app's UI will tween smoothly, while other app-specific colors will not. 

For example, the app may use a palette to control the color of app-specific widgets, e.g. weather icons. These custom color sets may not match up well with any of the existing colors provided in the Theme class, so the provided colors cannot be used, but the actual color choices may still vary depending on the app's overall theme (e.g. light or dark). Without this feature, the developer has to do extra work to set up his own theme classes and keep them in sync with those provided to the Theme widget, but it's visually jarring to switch themes when these custom colors aren't integrated with the provided theme animations.

**Comment by talatkuyuk** [comment]
I am also in the same point. I need this feature that @matthewlloyd explained. If ThemeData can have forexample Map<String, int> customColorSet or Map<String, Color> customColorSet, that would have been nice, so we are gonna be able to set app spesific custom colors to each theme (light, dark, or custom Theme). And we would use it like: Theme.of(context).customColorSet.myColor

**Comment by pak3nuh** [comment]
I've written my own theme class that implements the `ThemeData` interface, then delegated every property to the original `ThemeData` instance which is stored internally.
The upside is that the compiler will complain if anything changes in the interface allowing me to react. The downside is that is still cumbersome and error-prone.
It is something like this:
```dart
class MyTheme implements ThemeData {
  final ThemeData _base;
  final Color tertiary;
  // constructors and stuff
  @override
  bool get useTextSelectionTheme => _base.useTextSelectionTheme;
}
```

Then just feed this class to the `MaterialApp` or equivalent, and you can do `Theme.of(context)` directly, which applies some localization stuff.

**Comment by Niggelgame** [comment]
> I've written my own theme class that implements the `ThemeData` interface, then delegated every property to the original `ThemeData` instance which is stored internally.
> The upside is that the compiler will complain if anything changes in the interface allowing me to react. The downside is that is still cumbersome and error-prone.
> It is something like this:
> 
> ```dart
> class MyTheme implements ThemeData {
>   final ThemeData _base;
>   final Color tertiary;
>   // constructors and stuff
>   @override
>   bool get useTextSelectionTheme => _base.useTextSelectionTheme;
> }
> ```
> 
> Then just feed this class to the `MaterialApp` or equivalent, and you can do `Theme.of(context)` directly, which applies some localization stuff.

Sadly this doesn't allow you to access these properties like `tertiary` with `Theme.of(context).tertiary.

**Comment by pak3nuh** [comment]
Hi @Niggelgame, you are right, I didn't wrote the full example.
It also contains a static `of` method that translates something like this:
```dart
class MyTheme implements ThemeData {
  final ThemeData _base;
  final Color tertiary;
  // constructors and stuff
  @override
  bool get useTextSelectionTheme => _base.useTextSelectionTheme;

  // other delegating properties and methods

  static MyTheme of(BuildContext context) => Theme.of(context) as MyTheme;
}
```

**Comment by Niggelgame** [comment]
> Hi @Niggelgame, you are right, I didn't wrote the full example.
> 
> It also contains a static `of` method that translates something like this:
> 
> ```dart
> 
> class MyTheme implements ThemeData {
> 
>   final ThemeData _base;
> 
>   final Color tertiary;
> 
>   // constructors and stuff
> 
>   @override
> 
>   bool get useTextSelectionTheme => _base.useTextSelectionTheme;
> 
> 
> 
>   // other delegating properties and methods
> 
> 
> 
>   static MyTheme of(BuildContext context) => Theme.of(context) as MyTheme;
> 
> }
> 
> ```

Oh, thank you very much. This is a nice, hacky way to get this Theming to work. But hopefully Flutter will enable other ways for us to use custom theme properties in future releases.

**Comment by pak3nuh** [comment]
Yes, I also agree it is not the best way to do it, but `Theme.of` applies additional localtization and this wait still applies them.
Let's hope for a first-party option by google.

**Comment by fredgrott** [comment]
here is a refactored improvement:

`mixin AppModThemeData implements ThemeData {

  late final ThemeData _base;

  static AppModThemeData of(BuildContext context) => Theme.of(context) as AppModThemeData;

}

`

Works out better as ou are not overriding 87 methods just adding the new methods you need, which makes it easier to maintain until the MD3 changes appear in Flutter.

**Comment by AliAkberAakash** [comment]
> Hi @Niggelgame, you are right, I didn't wrote the full example. It also contains a static `of` method that translates something like this:
> 
> ```dart
> class MyTheme implements ThemeData {
>   final ThemeData _base;
>   final Color tertiary;
>   // constructors and stuff
>   @override
>   bool get useTextSelectionTheme => _base.useTextSelectionTheme;
> 
>   // other delegating properties and methods
> 
>   static MyTheme of(BuildContext context) => Theme.of(context) as MyTheme;
> }
> ```

I don't understand the use of `final ThemeData _base;` here could you explain please?

**Comment by 0ttik** [comment]
> here is a refactored improvement:
> 
> `mixin AppModThemeData implements ThemeData {
> 
> late final ThemeData _base;
> 
> static AppModThemeData of(BuildContext context) => Theme.of(context) as AppModThemeData;
> 
> }
> 
> `
> 
> Works out better as ou are not overriding 87 methods just adding the new methods you need, which makes it easier to maintain until the MD3 changes appear in Flutter.

I'm not getting how would you use this mixin. I guess, you will have to create a class with this mixin, but then you would have to still override all this 87 methods.
