### ISSUE TITLE
flutter drive is adding "_test" to the filename

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3152]
```
~/flutter/awesomesauce $ flutter drive --target=test_driver/main_test.dart
Found connected device "Nexus 6P"; will reuse it.
Test file not found: /Users/sethladd/flutter/awesomesauce/test_driver/main_test_test.dart
```

Notice how it tries to find test_driver/main_test*_test*.dart

Also note that the generated driver test says this:

```
// To start the test run the following command from the root of your application
// package:
//
//     flutter drive --target=test_driver/main_test.dart
```

**Comment by sethladd** [comment]
cc @yjbanov

**Comment by sethladd** [comment]
FWIW, https://github.com/flutter/flutter/issues/3181 removed the instruction for how to run flutter driver.

**Comment by yjbanov** [comment]
@sethladd, I added the proposal we discussed to the issue description

**Comment by yjbanov** [comment]
Superseded by https://github.com/flutter/flutter/issues/3193. Closing.
