### ISSUE TITLE
Changed channel to error 'env: bash\r: No such file or directory' on Mac

### ISSUE THREAD

**Issue by SinonHub** [flutter/flutter#31531]
## Logs

Steves-MacBook-Pro:~ steve$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale zh-Hans-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

Steves-MacBook-Pro:~ steve$ flutter channel
Flutter channels:
  beta
  dev
  master
* stable

Steves-MacBook-Pro:~ steve$ flutter channel beta
Switching to flutter channel 'beta'...
git: Switched to a new branch 'beta'
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.

Steves-MacBook-Pro:~ steve$ flutter doctor
env: bash\r: No such file or directory

```
```

**Comment by dnfield** [comment]
See https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory

Are your git settings for line-endings forcing you to get Windows style line endings?  What does `git config core.autocrlf` tell you?  Might need to check `git config --global core.autocrlf`.

**Comment by SinonHub** [comment]
is work, Thank you!

**Comment by benwinding** [comment]
What if I don't want to change my global git settings just for a flutter update?

Can't this be included in a `.gitattributes` file?

https://git-scm.com/docs/gitattributes
