### ISSUE TITLE
Uri.encodeFull doesn't encode url

### ISSUE THREAD

**Issue by S60bishoyhanna** [flutter/flutter#31530]
```
var wishoooUrl = Uri.encodeFull('https://www.newzem.com/index.php?route=product/product&product_id=1445');
print('encoded: '  + wishoooUrl);
```

It returned the url as it is not encoded!

had to use the Uri.encodeQueryComponent for the whole url

**Comment by dnfield** [comment]
You may have better luck opening this over at https://github.com/dart-lang/sdk/issues/new

**Comment by Hixie** [comment]
(closed as this is now tracked in dart bug database)
