### ISSUE TITLE
iOS: firebase_messaging "onMessage" is not called if UNUserNotificationCenter.current().delegate was set

### ISSUE THREAD

**Issue by dg76** [flutter/flutter#31545]
On iOS: If another plugin, e.g. flutter_local_notifications, sets UNUserNotificationCenter.current().delegate to a value (i.e. not to nil), then "onMessage" is not called when a Firebase message is received while the app is in foreground.

To test it you can just put firebase_messaging and flutter_local_notifications into your yaml file (and run flutter get), start your app and send a Firebase message to it. The app's "onMessage" method won't be called. Then remove flutter_local_notifications from the yaml file (and run flutter get) and try it again. Now "onMessage" is correctly called.

This seems to be a bug in firebase_messaging. It probably has to put itself into UNUserNotificationCenter.current().delegate and proxy requests to the previous delegate. The plugin flutter_local_notifications should probably do the same. And maybe this problem should be solved in general in the FlutterPluginRegistrar.

**Comment by dg76** [comment]
I saw now that this problem is even mentioned here https://pub.dartlang.org/packages/flutter_local_notifications . There it says

> NOTE: this plugin registers itself as the delegate to handle incoming notifications and actions. This may cause problems if you're using other plugins for push notifications (e.g. firebase_messaging)

But the problem should nevertheless be fixed, either using a proxy for the delegate or by adding a way to add multiple delegates in FlutterPluginRegistrar.

**Comment by BondarenkoStas** [comment]
@dg76 Please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close it here.

**Comment by dg76** [comment]
@BondarenkoStas But the best way to fix it would be to fix it in FlutterPluginRegistrar instead of using workarounds in every plugin. Isn't this the correct place to report bugs in FlutterPluginRegistrar?

**Comment by darshankawar** [comment]
@dg76 
Is this still a valid issue using latest Flutter version ?
Also, `firebase_messaging` has gone through lot of updates recently, so you may want to try by using latest `firebase_messaging` [plugin](https://pub.dev/packages/firebase_messaging) version and see if it has resolved your issue.

**Comment by dg76** [comment]
Hi! I think it is already fixed, there was a similar issue here: #22099

I also looked at the code of firebase_messaging and at least for iOS it does not seem to be necessary any more to keep a reference to the original delegate and "proxy-call" its functions. So I will close this issue now.
