### ISSUE TITLE
Error running gradle

### ISSUE THREAD

**Issue by appchallengr** [flutter/flutter#31546]
I can't debug my application.
First, the error happened when downloading the gradle, I managed to solve it, downloading manual and pointing to local file, but after that started to happen the error in other dependencies, 
It's like I'm using proxy, but I'm not using proxy.
I've tried changing the version of gradle and all the other tips I've seen on the internet but nothing works.
I'm using the latest version of android studio on a macbook
the error message always relates to UnknownHostException.

**Comment by wyattbiker** [comment]
Would be so much easier if you download VS Code IDE and then install Flutter Plugin and Dart Plugins to create projects.

**Comment by appchallengr** [comment]
I´ve tried with VS Code IDE and the same thing happened.
It's like I'm using proxy, but I'm not using proxy.
Exception in thread "main" java.net.UnknownHostException: services.gradle.org

**Comment by iqbalmineraltown** [comment]
did you tried to use other internet connection?
the problem seems related to your internet connection

**Comment by BondarenkoStas** [comment]
@appchallengr was your issue resolved?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
