### ISSUE TITLE
BottomNavigationBar redraw issue

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#31549]
BottomNavigationBar button "pressed" animation is left on screen permanently if you press and hold down a button in the BottomNavigationBar and then press the device's Home button at the same time.

Steps to reproduce the issue using the Flutter Gallery app:
1. Select from menu Material => Bottom Navigation
2. Press and hold down any button in the bottom navigation bar
3. Press the device's Home button at the same time
4. Go back to the Flutter Gallery app.
5. You will see something like this:

![Screenshot_20190424-135940](https://user-images.githubusercontent.com/11364599/56655079-75de2400-669a-11e9-9455-fc488bdd69f0.jpg)

So the navigation bar button animation is still in view even though you don't press the button anymore. Animation is removed only after you navigate to some other view.

I can reproduce the same issue with my own app (so this is not Gallery app specific issue) and it happens often also by accident even if I don't actually try to reproduce the issue. I can also reproduce the same issue occasionally using other device buttons.

Test device: Samsung Galaxy S7 / Android 8
Gallery app version January 2019

**Comment by kinex** [comment]
I can reproduce similar issue with ListView (hold down a list item and press the Home button at the same time). Sample image from Gallery app after navigated back to the app from Home:

![Screenshot_20190424-164849 1](https://user-images.githubusercontent.com/11364599/56664659-27884f80-66b1-11e9-81f5-25470c9ac39c.jpg)

**Comment by kinex** [comment]
I found also "easier" steps to reproduce the issue (no need to hold down any button and use only one finger): tap any button in BottomNavigationBar and rapidly after that press the device's Overview button (also known as Recents button). I think it is quite common to press Overview button by accident when tapping the leftmost button in BottomNavigationBar. This is why I see this redrawing issue quite often in my app.

**Comment by TahaTesser** [comment]
Hi @kinex 
I wasn't able to reproduce this issue with flutter_gallery using latest stable 
Are you using experiencing with latest stable Flutter?
Thank you

**Comment by kinex** [comment]
@TahaTesser  Yes it seems this has been fixed. Thank you!
