### ISSUE TITLE
Firebase Remote Config: FetchThrottledException.throttleEnd is incorrect value (1970...)

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter#31553]
## Steps to Reproduce
1. Setup a Firebase project and basic Flutter app with Remote Config
2. Add some values to your Remote Config
3. In your Flutter app, call `remoteConfig.fetch` with a short `expiration` (I used `Duration(minutes: 1)`)
4. Setup your app to call this very often, on startup, or a delayed loop, etc
5. Run on iOS (havent tried Android)

## Expected 
When called too often `FetchThrottledException` should be thrown and the `throttleEnd`
property should be a DateTime set in the Future.

## Actual
When called too often `FetchThrottledException` is thrown and the `throttleEnd`
property is set to sometime in 1970. Example: `1970-01-16 06:59:25.848`

## Logs
Package version: firebase_remote_config: ^0.1.0+2

[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale en-CA)
    • Flutter version 1.4.9-hotfix.1 at /Users/jrai/dev/flutter
    • Framework revision 88fa7ea403 (13 days ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jrai/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jrai/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • iPad Air 2 • B03E7C5C-5D9B-4024-AEBF-DD55BF378439 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2
      (simulator)

**Comment by Ogiwara-CostlierRain464** [comment]
Same issue.

**Comment by janmoppel** [comment]
Hello @MisterJimson !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by VladyslavBondarenko** [comment]
Hi @MisterJimson 
Sorry for ignoring,
Please open the issue in the [firebase github](https://github.com/FirebaseExtended/flutterfire/issues) if persists.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by MisterJimson** [comment]
I thought most issues were being migrated instead of just closed? I probably won't be spending time looking specifically at this exception for a while. So if not migrated, it will simply be lost.
