### ISSUE TITLE
flutter.dev Inaccessible

### ISSUE THREAD

**Issue by tuckerjt07** [flutter/flutter#31556]
Whenever I attempt to access flutter.dev in Chrome I get the following error. ```This site can’t provide a secure connection flutter.dev sent an invalid response.
ERR_SSL_PROTOCOL_ERROR```

**Comment by tuckerjt07** [comment]
This is only happening on OS X. It worked for a couple of hours on OS X but is now back to not working.

**Comment by MehmetBal** [comment]
This issue still persists. I can open the site from mobile but not on mac os from any browser, any workarounds?

**Comment by MehmetBal** [comment]
solved: https://support.google.com/chrome/thread/2228098?hl=en

**Comment by xurshid29** [comment]
I'm still facing this problem. And there is no dev file in /etc/resolve folder

**Comment by OkelloPablo** [comment]
i can't access flutter.dev on my windows machine either

**Comment by onipedadedayo142** [comment]
I tried accessing flutter.dev last night, it didn't work. Way out please

**Comment by Kellswork** [comment]
I can't access flutter.dev and have no /etc/resolver folder. I'm using mac Catalina 10.15

**Comment by sai00-00** [comment]
What about for windows?

**Comment by vamsee9** [comment]
In windows flutter.dev can't accessible it says this site can't be reached I think blocked in india region if we use tor or vpn it's working

**Comment by huzeyfetas** [comment]
Hi guys, as of this morning I can't login to flutter.dev. how did you solve your problem?
