### ISSUE TITLE
Release build is vastly (x10) slower than debug one with a little nuance

### ISSUE THREAD

**Issue by stellarbear** [flutter/flutter#31552]
## Stating a problem
I faced the following problem:
First of all, i ask to read till the end, thank you. 
#### So i found that there are 4 ways to build apk
1. flutter run (builds debug version)
2. flutter run --release (only on real device)
3. flutter build apk --debug
4. flutter build apk (builds release version, signed or not signed, does not matter)

First two options (1, 2) is not the true way to build it, but I still want to take them into consideration.

I build a small app that could reproduce the problem i encountered. 
Just a simple one-button GUI (main.dart) that triggers some "scrypt" key-derivation function implementation (scrypt.dart file in the repository). When scrypt function finishes it's work, the ellapsed time will be shown upon a button.

#### Some of the results according to the 4 ways i mentioned above:
1. ~ 2.5 seconds to complete (on emulator via adb, on real device via adb, on real device)
2. ~ 2.5 seconds to complete (on real device via adb, on real device)
3. ~ 2.5 seconds (on real device)
4. ~ 12.7 seconds (on real device)

So the fourth option is about 10 times slower that other ones. This confuses me, espesially paying attension that it took just 2.5 seconds on the 2nd option (and that is a nuance i was talking about)

I gave this project to several people, who reported the same issue.

I have a small suspicion that may be this could be connected with Uint32List implementation that i'm currently using in scrypt.dart, but not sure at all

## Steps to Reproduce
clone https://github.com/stellarbear/scrypt_performance_test

## Logs
I can't (or do not know how) to create logs for release version that is gonna be run directly on real device

`[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.2.1 at D:\Program Files\flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\root\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\root\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.`

**Comment by superciccio** [comment]
Hi,
I tried your example in dartpad and  got this result 
> executed in 0:00:00.524639
I think the only diff is the dartpad uses dart sdk 2.2.0

Can you try to use this version and see if is any better? :)

**Comment by jason-simmons** [comment]
Try using `flutter build apk --target-platform=android-arm64`

`flutter run` will build an APK targeting the attached device.  So if the device is 64-bit, then `flutter run` will build a 64-bit APK.

`flutter build apk` will build a 32-bit APK by default.  If you want a 64-bit APK then you'll need to specify that as the target.

**Comment by stellarbear** [comment]
> Try using `flutter build apk --target-platform=android-arm64`
> 
> `flutter run` will build an APK targeting the attached device. So if the device is 64-bit, then `flutter run` will build a 64-bit APK.
> 
> `flutter build apk` will build a 32-bit APK by default. If you want a 64-bit APK then you'll need to specify that as the target.

that makes sence. but is there any way i can debug that slow (i suppose x86) version on emulator?
i made some old phone spec virtual devices, but everything still runs smoothly (~2.5 sec)

**Comment by stellarbear** [comment]
> Hi,
> I tried your example in dartpad and got this result
> 
> > executed in 0:00:00.524639
> > I think the only diff is the dartpad uses dart sdk 2.2.0
> 
> Can you try to use this version and see if is any better? :)

switched to dev flutter branch, no changes

**Comment by stellarbear** [comment]
After some research i found that i can attach to slow version with the following command:
flutter run --release --target-platform=android-arm

And the slowest part of the code is blockXOR function
dst[di++] ^= src[si++];

**Comment by stellarbear** [comment]
I was wrong about XOR, cannot reproduce it outside "scrypt" function. But still stuck in "salsaXOR" function - this is the pleace where release mode is vastly slower than debug

**Comment by iapicca** [comment]
Hi @stellarbear  
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by stellarbear** [comment]
I will try to test it again in the nearest future

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
