### ISSUE TITLE
dev/benchmarks/complex_layout/ is not being analyzed

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3157]
The new project `dev/benchmarks/complex_layout/` is not found by flutter update-packages or flutter analyze. It should probably be moved up one level so that update-packages will find it, and flutter analyze extended a bit to look for packages in dev/ (and not just dev/manual_tests)

**Comment by Hixie** [comment]
We should just fix flutter update-packages and flutter analyze to catch it. It's in the right place, I think.
