### ISSUE TITLE
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113] Install failed

### ISSUE THREAD

**Issue by nitishk72** [flutter/flutter#31579]
When I am trying to install the app in debug mode it works fine but when I try to do the same in Release mode, I get an error. I did lots of googling and none of the solutions works for me.
```
F:\path\to\flutter\project>flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-IN)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\nitishk72\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\nitishk72\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
![tempsnip](https://user-images.githubusercontent.com/15886737/56697427-32bc9900-670c-11e9-826f-2a98967fee42.jpg)

**Comment by fengqiangboy** [comment]
Edit Android/app/build.gradle

1. Add the following code in Android block
```
ndk {
            abiFilters 'armeabi-v7a', 'x86', 'armeabi'
        }
```

2. Create a file ait Android/app/gradle.properties, put following code in it

```
target-platform=android-arm
```

**Comment by iqbalmineraltown** [comment]
when running `flutter build apk`, it will use `--target-platform=android-arm` as default which will generate apk for arm32 architecture
you can see more options for `--target-platform` by running `flutter build apk -h` where only arm and arm64 are available

AFAIK currently Flutter cannot build apk for `x86` architecture
but you can still run debug on simulator, which is `x86`
related to https://github.com/flutter/flutter/issues/9253

**Comment by d-apps** [comment]
> Edit `Android/app/build.gradle`
> 
> 1. Add the following code in Android block
> 
> ```
> ndk {
>             abiFilters 'armeabi-v7a', 'x86', 'armeabi'
>         }
> ```
> 
> 1. Create a file at `Android/app/gradle.properties`, put following code in it
> 
> ```
> target-platform=android-arm
> ```

I was having this error when I was trying to test my app in avd in debug mode. Following this steps it's working now.

**Comment by smallsilver** [comment]
> > Edit `Android/app/build.gradle`
> > 
> > 1. Add the following code in Android block
> > 
> > ```
> > ndk {
> >             abiFilters 'armeabi-v7a', 'x86', 'armeabi'
> >         }
> > ```
> > 
> > 
> > 
> > 1. Create a file at `Android/app/gradle.properties`, put following code in it
> > 
> > ```
> > target-platform=android-arm
> > ```
> 
> I was having this error when I was trying to test my app in avd in debug mode. Following this steps it's working now.

it's work ,good boy!

**Comment by fengqiangboy** [comment]
Because flutter can not package both arm32 and arm64, so, we force gradle to use arm32 package, and arm32 file can run on both arm32 device and arm64 device.

**Comment by fengqiangboy** [comment]
> > > Edit `Android/app/build.gradle`
> > > 
> > > 1. Add the following code in Android block
> > > 
> > > ```
> > > ndk {
> > >             abiFilters 'armeabi-v7a', 'x86', 'armeabi'
> > >         }
> > > ```
> > > 
> > > 
> > > 
> > > 1. Create a file at `Android/app/gradle.properties`, put following code in it
> > > 
> > > ```
> > > target-platform=android-arm
> > > ```
> > 
> > 
> > I was having this error when I was trying to test my app in avd in debug mode. Following this steps it's working now.
> 
> it's work ,good boy.but I don't know why?

Because flutter can not package both arm32 and arm64, so, we force gradle to use arm32 package, and arm32 file can run on both arm32 device and arm64 device.

**Comment by DevarshRanpara** [comment]
Facing a same issue,

Generating apk with `flutter build apk`

and when i try to install that apk with `flutter install`

I got following error.

```
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
Install failed

```

**Comment by Xgamefactory** [comment]
same here

**Comment by iqbalmineraltown** [comment]
@DevarshRanpara @Xgamefactory can you post `flutter doctor -v` outputs?
just checking what architecture is your deployment target

FYI google play store enforce appbundle for everyone, so you might want to try building appbundle  instead

**Comment by nitishk72** [comment]
I don't know the exact solution and still, no developer came with the exact solution.
So, the best solution is to reinstall the flutter and get rid of this problem.

## Wait for Flutter team to come with exact solution

**Comment by guilhermelirio** [comment]
Same here, only release version!

**Comment by Valentin-Seehausen** [comment]
Tried proposed solution without success. +1 from my side.

**Comment by AbelTilahunMeko** [comment]
This Stockoverflow answer might help,
https://stackoverflow.com/a/57848743/9949983

**Comment by r00tvj** [comment]
any update on this ?

**Comment by luckypal** [comment]
My Android Emulator abi architecture is x86.
So, I tried to compile with x86 option.
![image](https://user-images.githubusercontent.com/35539437/72175435-c10fa280-33a1-11ea-843f-d2172aa9343f.png)

![image](https://user-images.githubusercontent.com/35539437/72175452-ce2c9180-33a1-11ea-9dc8-6693564d0f82.png)

But I got this error.
![image](https://user-images.githubusercontent.com/35539437/72175585-1350c380-33a2-11ea-8336-bb02bad65bbd.png)

Flutter version
![image](https://user-images.githubusercontent.com/35539437/72175657-42ffcb80-33a2-11ea-9623-cb8557257663.png)

**Comment by iapicca** [comment]
Hi @nitishk72  
if you are still experiencing this issue with the latest stable version of flutter 
please provide your `flutter doctor -v` ,
your `flutter run --verbose`
and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by HQHAN** [comment]
After adding below in android/app/build.gradle, and run `flutter run --flavor development`,
I was able to solve this issue. You might want to check this article regarding on `flavoring flutter`
https://medium.com/@salvatoregiordanoo/flavoring-flutter-392aaa875f36
```go
flavorDimensions "flutter"

    productFlavors {
        development {
            dimension "flutter"
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
        }
        production {
            dimension "flutter"
        }
    }
```

**Comment by rhenesys** [comment]
What resolved the issue for me: I went on Android Studio and when creating a new Virtual Device I went on x86 Images and selected a image x86_64 and used this one to create my devices. 

![sysImage](https://user-images.githubusercontent.com/11628181/81338127-63b80380-90ac-11ea-9cb9-a3024f555aa1.PNG)

**Comment by saulo-arantes** [comment]
Try `flutter clean` and build it again

**Comment by r0ly4udi** [comment]
in my case, run command in your terminal "flutter clean" its great working......
may help in same case. thx

**Comment by jarl-dk** [comment]
I experienced this too.
Then I
  - uninstalled android studio
  - removed ~/Android
  - Removed ~/.android
  - Reinstalled android-studio
  - reinstalled virtual devices
Then everything was fine

**Comment by akshajdevkv** [comment]
hey I solved it

- run `flutter clean`
- run `flutter build apk`
then run `flutter install`
