### ISSUE TITLE
Latest engine roll caused multiple perf regressions

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#31590]
https://github.com/flutter/flutter/commit/2dc66f0a2464b3b4be714d8b16d731cd5b09c3ba

Has severely regressed frame build times on multiple test cases.

**Comment by dnfield** [comment]
https://github.com/flutter/engine/compare/3e47b4bb39bb...26b30a464684 is the list of engine commits in it.

**Comment by dnfield** [comment]
Skia roll seems to be the culprit.

**Comment by justinmc** [comment]
I'm closing this since the referenced PRs have been merged, the engine has been rolled into this repo, and the build has just gone green.  If there's anything else to check, let me know.
