### ISSUE TITLE
[palette_generator] An error in calculating titleTextColor and bodyTextColor for PaletteColor

### ISSUE THREAD

**Issue by edwardez** [flutter/flutter#31592]
First, I'm not very familiar with color theory so I might be wrong...

But I highly doubt that [palette_generator](https://github.com/flutter/packages/tree/master/packages/palette_generator) is calculating  titleTextColor and bodyTextColor for PaletteColor incorrectly.

As an example, in the [test](https://github.com/flutter/packages/blob/e40537243c1e07cbf47e1ffefc947c4092e34c28/packages/palette_generator/test/palette_generator_test.dart#L91)  `'PaletteGenerator finds dominant color and text colors'`. 

Dominant color is `0xff0000ff` while `titleTextColor` is `0xbc000000` and `bodyTextColor` is `0xda000000`

The contrast ratio between text color and dominant color is extremely low, which doesn't seem correct.
https://contrast-ratio.com/#hsla%280%2C0%25%2C0%25%2C0.85%29-on-%230000ff

I think the problem is `palette_generator` converts `Color` to `HSLColor` then directly uses `lightness` in `HSLColor`. However it seems like relative luminance is different from `lightness` in `HSLColor`.

See line 687, 688 here
https://github.com/flutter/packages/blob/e40537243c1e07cbf47e1ffefc947c4092e34c28/packages/palette_generator/lib/palette_generator.dart#L687

Since it seems to be a easy fix I submitted a pr here :P
https://github.com/flutter/packages/pull/18

**Comment by jonahwilliams** [comment]
cc @gspencergoog
