### ISSUE TITLE
单独运行flutter项目正常，集成到现有安卓项目（有多渠道）转调flutter页面就闪退

### ISSUE THREAD

**Issue by zoubihai** [flutter/flutter#31596]
E/flutter: [ERROR:flutter/runtime/dart_vm_data.cc(19)] VM snapshot invalid and could not be inferred from settings.
E/flutter: [ERROR:flutter/runtime/dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
 E/flutter: [ERROR:flutter/runtime/dart_vm_lifecycle.cc(89)] Could not create Dart VM instance.
 A/flutter: [FATAL:flutter/shell/common/shell.cc(218)] Check failed: vm. Must be able to initialize the VM.
 io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:423)
    io.flutter.view.FlutterNativeView.attach(FlutterNativeView.java:165)
    io.flutter.view.FlutterNativeView.<init>(FlutterNativeView.java:47)
    io.flutter.view.FlutterNativeView.<init>(FlutterNativeView.java:37)
    io.flutter.facade.Flutter.createView(Flutter.java:73)

**Comment by minh98** [comment]
can you speak English ???

**Comment by zr940326** [comment]
中文：同问，我也是这样。English：With q, and so did I

**Comment by zoubihai** [comment]
这个问题我之前解决了，你要在flutter里面的安卓项目的build.grandle文件中复制你多渠道相关代码

**Comment by zoubihai** [comment]
> 中文：同问，我也是这样。English：With q, and so did I

这个问题我之前解决了，你要在flutter里面的安卓项目的build.grandle文件中复制你多渠道相关代码

**Comment by zr940326** [comment]
你是指，flavorDimensions ，productFlavors 和  android.applicationVariants.all吗

**Comment by zr940326** [comment]
能否麻烦楼主给一个对比图，我不知道，我怎么处理

**Comment by zr940326** [comment]
万分感谢

**Comment by zr940326** [comment]
![image](https://user-images.githubusercontent.com/17058316/57823345-b0cf0580-77c9-11e9-8b20-119b5b0cf14e.png)
楼主，你是是这样修改的 ，我这不起作用

**Comment by zr940326** [comment]
> ![image](https://user-images.githubusercontent.com/17058316/57823345-b0cf0580-77c9-11e9-8b20-119b5b0cf14e.png)
> 你是不是这样修改的

**Comment by zoubihai** [comment]
> ![image](https://user-images.githubusercontent.com/17058316/57823345-b0cf0580-77c9-11e9-8b20-119b5b0cf14e.png)
> 楼主，你是不是这样修改的 ，我这不起作用

不是productFlavors相关的，稍等我找一下我的代码

**Comment by zoubihai** [comment]
> productFlavors

app的build.gradle文件：
![image](https://user-images.githubusercontent.com/19750129/57823847-97c75400-77cb-11e9-8572-9edbe60497a6.png)

**Comment by zoubihai** [comment]
> > ![image](https://user-images.githubusercontent.com/17058316/57823345-b0cf0580-77c9-11e9-8b20-119b5b0cf14e.png)
> > 你是不是这样修改的

修改下flutter的build.gradle文件
![image](https://user-images.githubusercontent.com/19750129/57823890-bfb6b780-77cb-11e9-86c8-d94aa60234dc.png)

**Comment by zr940326** [comment]
我这还是报错
原：
![image](https://user-images.githubusercontent.com/17058316/57825428-7701fd00-77d1-11e9-9dad-cefd6e4401a2.png)
flutter：
![image](https://user-images.githubusercontent.com/17058316/57825455-91d47180-77d1-11e9-92c5-99e9697558fe.png)

我改成这样也不行：
![image](https://user-images.githubusercontent.com/17058316/57825478-a7e23200-77d1-11e9-9c97-5df380ee04b9.png)

**Comment by zr940326** [comment]
flavorDimensions 是as 3.3.2 渠道都需要修改

**Comment by zr940326** [comment]
我已经解决，这两篇文章https://www.jianshu.com/p/273c462896c3，https://github.com/flutter/flutter/pull/27154
我是由于修改了app名称

**Comment by LinHuanTanLy** [comment]
哭笑，我竟然看到了我的代码
