### ISSUE TITLE
Adreno-GSL: <gsl_memory_alloc_pure:2124>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed

### ISSUE THREAD

**Issue by yuchuan08** [flutter/flutter#31599]
Flutter version: 1.2.1 channel stable
Dart     version：2.2.0
Android devices：OppoR11  Android7.1.1
When  in  realease mode，app   run   random  crash，I do not  know  the reason，anyone  has  the same  problem？

**Comment by BondarenkoStas** [comment]
Duplicate of #35986
