### ISSUE TITLE
Fix Implementation of Material Design Bottom Navigation Behavior

### ISSUE THREAD

**Issue by FullstackJack** [flutter/flutter#31594]
Material BottomNavigationBar behavior does not correctly implement sub-navigation design specification per material.io. Within a tab, you should be able to navigate to a sub-screen. Each tab in bottom navigation should be a stack.

This behavior can be observed in the following animated guide.
https://material.io/design/components/bottom-navigation.html#behavior

Other known example(s) in the wild:
- Instagram

Please implement the sub-navigation Bottom Navigation behavior as outlined in the spec. Should we feature flag it? persistNavigationBar? Scaffold.navigator?

Current Behavior:
Calling Navigator.push() replaces the entire screen instead of sliding over the current tab's content and persisting the bottom navigation.

Expected Behavior:
Calling Navigator.push() pushes a new screen onto the current tab's navigator.

Potential Issues:
- Focus handling may get confused if other tabs are not unmounted as offstage content may get focused.

**Comment by FullstackJack** [comment]
I was able to work out this behavior with a combination of MaterialApp, CupertinoTabScaffold, CupertinoTabBar, BottomNavigationBarItem, and CupertinoPageRoute...

It would be nice to ensure this behavior is implementable from both Material and Cupertino libraries. Maybe it could be extracted.

**Comment by HansMuller** [comment]
It's now possible of each BottomNavigationBar view (or each TabBarView view etc) to have its own Navigator - https://github.com/flutter/flutter/issues/31483#issuecomment-486344199. There's a small example there. It doesn't do everything the Material spec defines for navigation but the support for multiple persistent stacks of routes is there.

**Comment by premtemp1** [comment]
@HansMuller ,
  Thanks for the example but I am newbie and the example is not easy to follow for me. I have. a pressing need to get this to work for material and don't want to user Cupertino .

Basically, I have multiple pages in separate file (parent and sub pages) and  route 

/home
   p2
   p2
/page1
  /p3
 /p4
/page2
  /p5
  /6

Where page 1,2,3 are the main tab in separate files/classes  and the other are the sub pages also in separate pages/classes
How can I use your design with my layout

Do I have wrap each parent in the navigator like  NavigatorPage(new page1()),? How do I get the child to stay on the same tab

Thanks for your help

**Comment by timsneath** [comment]
Closing this issue with the sample Hans mentioned in the earlier comment.
