### ISSUE TITLE
flutter buttons don't retrieve data from firebase anymore

### ISSUE THREAD

**Issue by frumcrss** [flutter/flutter#31605]
2 days ago everything worked as expected and yesterday I just woke up and my buttons wouldn't retrieve data from firebase anymore.. 

Button's code:

RaisedButton(
                      onPressed: (){
                        tempSearch = [];
                        Search().search('e').then((QuerySnapshot docs){
                          setState(() {
                            for(int i = 0; i < docs.documents.length; ++i) {
                            tempSearchStore.add(docs.documents[i].data);
                          }
                          });
                        });
                      },
                      child: Text("e"),
                    ),

Firebase query : 

class Search {

  search(String cauta) {
    return Firestore.instance
    .collection('clients')
    .orderBy(cauta, descending: true)
    .getDocuments();
  }

}

Brief logs I'm getting:

FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore( 6262): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore( 6262):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore( 6262):     .build();
W/Firestore( 6262): firestore.setFirestoreSettings(settings);

**Comment by frumcrss** [comment]
Hmm sorry but the problem is not firebase related.. the buttons gets pushed only when I try multiple times.. even if the onPressed: () {} so its flutter related not firebase related

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by frumcrss** [comment]
Apparently overflow stack widget doesn't accept any kind of gestures.. so I was right, it was flutter related.. initially I thought I successfully pushed those buttons but couldn't retrieve data from firebase. I'm sorry and I'm also thankful for your support!

**Comment by BondarenkoStas** [comment]
@frumcrss do you encounter the issue while using current flutter stable v1.9.1+hotfix.4?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
