### ISSUE TITLE
url_launcher 5.0.2 mailto scheme doesn't work on iOS where there are dots in the email address

### ISSUE THREAD

**Issue by rockgecko-development** [flutter/flutter#31602]
For example:
mailto:fake.name@gmail.com?subject=hi
Android: works
iOS: doesn't work

mailto:fakename@gmail.com?subject=hi
Android: works
iOS: works

**Comment by long1eu** [comment]
you need to URL encode it

**Comment by techximumsolutions** [comment]
I am using [WebView_flutter](https://pub.dev/packages/webview_flutter) to use WebView but when I click on Mailto: it going on **Page not Found**. if i use **url_launcher** to handle mailto: link it open Default mail app but My page also going PAGE NOT FOUND
https://stackoverflow.com/q/56421218/9489285

**Comment by BondarenkoStas** [comment]
@rockgecko-development @techximumsolutions do you still experience the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
