### ISSUE TITLE
Enhancement: Add a Tree widget that users slivers and lazy building

### ISSUE THREAD

**Issue by devnoname120** [flutter/flutter#31606]
Building a tree-like widget with many children can currently not be done without blocking the main UI thread. It's not possible to use nested `ListView` in order to get lazy loading because the tree is not necessarily balanced so if an element has a lot of nested children, it will take a significant time to build anyway which means the UI will hang.

Here is an issue showing an example of why it's needed: https://github.com/flutter/flutter/issues/30987

Cc @dnfield.

**Comment by dnfield** [comment]
It would be helpful if you provided some examples of apps that do this today.  Something like Reddit or Hackernews maybe?  Are there others?

**Comment by devnoname120** [comment]
Are you talking about Flutter apps? I'm pretty new to this ecosystem so I don't know any.

**Comment by dnfield** [comment]
I'm thinking more of just mobile apps in general.  

There are two design related problems that would be nice to hash out here:

1. What does a really good tree view implementation look like in the mobile form factor? What do we like about apps we use that have them?  What don't we like?
2. What does a really good API for a tree view look like?  For example, my experience in the past using WPF/UWP's tree view classes was often confusing and very easy to get wrong.  Can we improve on that?

**Comment by SoftWyer** [comment]
The React Material-UI team have a[ tree widget](https://material-ui.com/components/tree-view/) in the 'labs' that looks promising. For me, something along these lines would be good from both a UI and API perspective.

**Comment by davidmartos96** [comment]
> It would be helpful if you provided some examples of apps that do this today.  Something like Reddit or Hackernews maybe?  Are there others?

The Boost app (Reddit client) on Android does this kind of tree comments very nicely. Here is an example 

![Screenshot_20211210-200355.jpg](https://user-images.githubusercontent.com/22084723/145628058-c2daf0a0-c844-4c1f-9a3e-c983f380a2f8.jpg)

**Comment by Piinks** [comment]
I found this and https://github.com/flutter/flutter/issues/114299 today. They appear to be the same issue so I am going to close this one since the other has more upvotes. I will reference this one there for more context. 👍
