### ISSUE TITLE
firebase_admob ^0.8.0+4 Android crashes on startup (Release version only)

### ISSUE THREAD

**Issue by xorrior** [flutter/flutter#31617]
## Steps to Reproduce

So I'm having issues getting the flutter firebase_admob plugin to work on Android (Release). It initializes and loads ads perfectly for the debug build on Android and the debug/release builds on iOS. I've already made the necessary changes to the AndroidManifest.xml file and included my admob app id (See screenshot). I'm really lost at this point. I've looked at all of the available solutions for the issue I'm having and none have worked. Please help!

## Logs
![manifest](https://user-images.githubusercontent.com/9156069/56757683-d2a51180-6762-11e9-9315-8e3988071cb8.png)
![logcat](https://user-images.githubusercontent.com/9156069/56757692-dc2e7980-6762-11e9-8b4c-a13f26293506.png)
![plugins](https://user-images.githubusercontent.com/9156069/56757764-04b67380-6763-11e9-9bfb-27d5ac3e6f30.png)

```
```

   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/TwitterApi.dart:30:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/TwitterApi.dart:35:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/TwitterApi.dart:41:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/TwitterApi.dart:47:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/TwitterApi.dart:58:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/TwitterApi.dart:65:3 • sdk_version_async_exported_from_core
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          DeleteProgressDialog.progress, DeleteProgressDialog.timeRemaining • lib/ui/DeleteProgressDialog.dart:5:7 • must_be_immutable
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/ui/Login.dart:22:1 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/ui/Login.dart:76:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/ui/Login.dart:130:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/ui/Login.dart:138:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/ui/Login.dart:146:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions •
          lib/ui/Login.dart:245:3 • sdk_version_async_exported_from_core
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: UserInfoHeader.user •
          lib/ui/UserInfoHeader.dart:5:7 • must_be_immutable

```
```

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/xorrior/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xorrior/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.7019

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Pixel 3 XL • 93VY18Y3R • android-arm64 • Android 9 (API 28)
```
```

**Comment by xorrior** [comment]
Nevermind, resolved it. 🤦‍♂️

**Comment by shashi2602** [comment]
how ?
did you resolved it
