### ISSUE TITLE
[LUCI] Decommision the coverage shard for Flutter Framework

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#31615]
Thanks to some great work by @jonahwilliams, test coverage is now only marginally slower than testing without coverage.

We should decomission https://ci.chromium.org/p/flutter/builders/luci.flutter.prod/Linux%20Coverage and just make the `Linux` framework tests run coverage as part of their normal run.  This will free up a bot per commit and get rid of a bot that has poor visibility right now anyway.

/cc @digiter

**Comment by godofredoc** [comment]
@digiter can we close this one?

**Comment by digiter** [comment]
No, the PR of #45235 is still open, I need to find some time to fix the tests.

**Comment by digiter** [comment]
Getting back to this, test+coverage seems to take 4x the time of only test. Should we put the coverage shard back? @dnfield 

```
time SHARD=framework_tests bin/cache/dart-sdk/bin/dart dev/bots/test.dart
real    10m14.860s
user    37m43.835s
sys     11m7.566s

time SHARD=framework_coverage bin/cache/dart-sdk/bin/dart dev/bots/test.dart
real    29m25.334s
user    112m37.490s
sys     11m6.702s
```

**Comment by dnfield** [comment]
@jonahwilliams didn't you make this faster?  Has that regressed?

**Comment by dnfield** [comment]
We no longer run a coverage shard.
