### ISSUE TITLE
Android Release mode only: IllegalStateException: reply already submitted

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#31612]
It is curious that this does not occur in debug mode...Note: this build does not use proguard.

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl$1.reply(FlutterNativeView.java:197)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)

see: https://github.com/flutter/flutter/issues/29092 - does not happen in debug mode though.. 

It is add2app

**Comment by dnfield** [comment]
What are the steps to reproduce this?

I suspect this could be the same as the linked issue, and it's just harder to reproduce the race in debug mode.  If we can resolve that, we should see if this issue still occurs, and then we'll know if it really is an AOT vs JIT problem.

**Comment by neiljaywarner** [comment]
I hear you
Well. I simplified the code so there is only one call and that did not fix the problem - so that leaves it nothing in common with the linked issue :(

This is basically my flow
1. Open Android host app
2. Setup and present flutter view
e.g. a)         val flutterView = Flutter.createView(activity, lifecycle, flutterUri.toString()) b)         GeneratedPluginRegistrant.registerWith(flutterView.pluginRegistry) .  c) setMethodCallHandler 
3. use Futurebuilder immediately in body of Scaffold to make platform call - just one now
4. result.success to get cookie etc to be able to make network call  in dart/flutter

So nothing too complicated. I did switch to Kotlin recently...

**Comment by neiljaywarner** [comment]
I am still on Flutter 1.2 from stable channel

**Comment by matthew-carroll** [comment]
I'll take a look when I get back in the office. Looks like its most likely the Java embedding API - probably in one of the areas where the old API got migrated to the new API under the surface.

**Comment by neiljaywarner** [comment]
I am going to close this for now because it appears to be closer to a Ebkac+documentation issue.

I did not find out if i even have the same problem as related issue b/c I optimized away call2.
However, i fixed my problem by realizing I was in fact calling call1 twice.

It still is a bit confusing how it appears to be trying to return a result three times or I'm not sure exactly why it would be mismatched, but i fixed it.

however, I fixed it with a hacky boolean flag type solution, so if anyone like @matthew-carroll  or someone else has a better idea I'd welcome it.

here is our basic situation
1) add2app where the flutter page is after a login
2) Immediate (before any user interaction, before network calls by dart/flutter, etc)) Platform call from dart to ask java/kotlin to get auth  type info and send it back to dart/flutter.  
3) A few network calls and Futurebuilders and ui and stuff in dart/flutter
4) an outer observable to listen to lifecycles so that in onResume it can go check the platform and see if that stuff is expired
5) So therefore from an Android perspective onCreate and onResume are both happening and from a Flutter/Dart perspective, initState and resume are both happening.

Problem: This is confusing in general, and I would guess much more so if you don't come from an Android background, which, happily I do.

I would think for someone with an iOS/web/react or possibly even Xamarin/etc background it might be confusing that onresume happens when you are not resuming because you haven't left yet - or even someone from an Android perspective who ready something like "lifecycles are simpler with flutter"

So it seems like a documentation opportunity of some sort?  I might make another issue for that if you want if nothing else as a conversation item to be open.  I don't think it's a bug anymore though.

**Comment by SAGARSURI** [comment]
I am trying to build a messaging app. I am using method channels to send and receive messages. First time when I receive a message its working perfectly i.e passing the message from android to Flutter view using the MethodChannel. But the second it crashes resulting:
 
`java.lang.IllegalStateException: Reply already submitted`

Here is my android code:

`call.method == "receiveMessage" -> receiveMessage(result)`

```
private fun receiveMessage(result: MethodChannel.Result){
        val listenerID="com.sagar.gossip.MainActivity"

        MyChat.addMessageListener(listenerID, object : MyChat.MessageListener() {
            override fun onTextMessageReceived(p0: TextMessage?) {
                Log.d(TAG, "Message received successfully: " + p0?.toString())
                result.success(p0?.text)
            }
        })
    }
```

My Flutter code:
```
Future<String> receiveMessage() async {
    String message = '';
    try{
      message = await platform.invokeMethod('receiveMessage');
    } on PlatformException catch(e){
      message = e.message;
    }
    return message;
  }
```

**Comment by matthew-carroll** [comment]
Let's not close this until it is investigated. Maybe it's a bug, maybe it isn't, but we need to find out.

**Comment by bxxasn** [comment]
I made a mistake like this today.

MethodChannel.Result result = ***
Map <String,Object> map=  new HashMap(String,Object);
map.put.......
result.success(map)


flutter  version: 1.0.4+5

**Comment by matthew-carroll** [comment]
@neiljaywarner @SAGARSURI @bxxasn would each of you mind providing a minimal reproduction app? That's the exact code needed to reproduce the issue, but the minimum functionality necessary to cause the bug? That will help avoid noise that is unrelated to the issue, while allowing me to diagnose the problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
