### ISSUE TITLE
Flutter Desktop macOS Embedding can use NSString methods to improve moveLeft etc.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#31625]
Currently, FLETextInputPlugin.mm add or subtracts 1 from the current position to figure out the next one.

It could follow the work in FlutterTextInputPlugin.mm (iOS version) and use some methods available on NSString to better support Unicode.

**Comment by stuartmorgan** [comment]
@franciscojma86 FYI

**Comment by dnfield** [comment]
I'm going to look at factoring out some of the sanitization logic into something in FML - that should make it easier for both platforms to share.

**Comment by stuartmorgan** [comment]
I ended up removing arrow key handling from the macOS embedding; the framework handles it.
