### ISSUE TITLE
plumb traces recorded in flutter.mojo to mojo:tracing

### ISSUE THREAD

**Issue by ppiet** [flutter/flutter#3162]
Flutter already has support for tracing, but the traces collected by `flutter.mojo` are not exposed to the mojo [tracing service](https://github.com/domokit/mojo/blob/master/mojo/services/tracing/interfaces/tracing.mojom). It would be useful to add the plumbing, so that one can get a unified trace when developing a mojo flutter app.

@johnmccutchan added similar plumbing in the dart content handler. What would be needed for flutter.mojo would be likely similar.

@chinmaygarde

**Comment by abarth** [comment]
Do you have a link to the patch that added this to the dart content handler?

We use `mojo::TracingImpl` in flutter.mojo.  That used to be enough to integrate with the Mojo's tracing system.  Is more required now?  Is there documentation explaining what's needed?

**Comment by ppiet** [comment]
To clarify, we do see some trace events coming from flutter being recorded in mojo:tracing. What is missing are developer-defined trace events, ie. the ones defined in the Flutter app code using https://api.dartlang.org/stable/1.15.0/dart-developer/Timeline-class.html .

@johnmccutchan , could you point us to the code that plumbs these to mojo:tracing in the dart content handler?

**Comment by johnmccutchan** [comment]
@ppiet https://github.com/domokit/mojo/blob/master/services/dart/dart_tracing.h

**Comment by ppiet** [comment]
Thanks, John. I was able to cargo-cult this - https://github.com/flutter/engine/pull/2595 . It's working, although only if I pass the --complete-timeline flag to the VM.
