### ISSUE TITLE
Document what fetch is for

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3163]
There are seemingly three ways to get an HTTP URL in flutter. One way, the `fetch` call, is particularly not intended for most developers.

Can we either make `fetch` and `fetchUrl` private, or at least renamed to something more "scary" ?

Also, we probably want to add some API docs to help direct developers to what they really want. Maybe something like:

"Intended only for use cases that require access to a Mojo pipe of data from an HTTP request. Most developers should use the http library provided by Flutter."  (and link the http library)

Thanks!

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by Hixie** [comment]
there's a bug on this already. my plan is to merge the http and fetch
libraries into one much more useful library.

**Comment by sethladd** [comment]
We can close this when https://github.com/flutter/flutter/pull/3584 lands.
