### ISSUE TITLE
Firebase ID token has invalid signature

### ISSUE THREAD

**Issue by rcrescenti** [flutter/flutter#31635]
I'm writing an app on Flutter and I'm making access with login by email and password, and by google account. This app will communicate with an API hosted in firebase functions, when I receive the request, I validate the user token, which is generated by `FirebaseUser.getIdToken (refresh: true)`, when the login is effected by email and password the token is successfully validated, but when I log in through Google, when I validate the token I get the following error `Firebase ID token has invalid signature. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.`

I'm using the following packages:
- firebase_auth: ^ 0.8.4 + 5
- google_sign_in: ^ 4.0.1 + 3 

Does anyone know how to solve it?

**Comment by rcrescenti** [comment]
I have detected that in the `firebase_user.dart` file of the` firebase_auth` package, in the method that returns the token, the token is being cut off, leaving it with a maximum of 1016 characters, leaving the token invalid.

 To do a test, I created a variable of type String and will be it manually with a valid token, and then gave a `print` of the variable, and even assigning the variable manually with a valid token, in print it shows the cut token  , with only 1016 characters

**Comment by shahidhk** [comment]
@rcrescenti Can you tell us how you solved the issue?

**Comment by rcrescenti** [comment]
There is no problem. I'll explain what made me think it was a problem.

I was creating an API and would start the tests using Postaman, to validate if the client was authenticated, I would send the token generated by google in the request header, so to capture the generated token in the application, I would print a token on the screen, and in Postman, when I validated the token, I received that error reported above (until then I was trying to log in with my google account), so I decided to test using login by email and password, which in this case worked correctly.

After a few days of testing, I discovered that the print() had a maximum output limit, and printed only an initial part of the token, this error did not occur when I logged in via email and password because the token was small, but by google account method, return token was too large, and exceeded the maximum limit.

Do you have a similar problem?

**Comment by shahidhk** [comment]
Thanks for the explanation @rcrescenti. I was helping one of users debug and Invalid JWT error and this was super confusing. 

Did you figure out a way to "print" the entire token?

**Comment by gching** [comment]
@shahidhk  and others that stumble here: https://github.com/flutter/flutter/issues/22665#issuecomment-458186456

This is specifically for printing it out so you can copy it from the console if needed

**Comment by ricardocrescenti** [comment]
Sorry for the delay in responding.  
Since I am using the Token ID for API testing on Postan, I divide it into 3 parts for printing.

**Comment by ricardocrescenti** [comment]
> Thanks for the explanation @rcrescenti. I was helping one of users debug and Invalid JWT error and this was super confusing.
> 
> Did you figure out a way to "print" the entire token?

Sorry for the delay in responding.  
Since I am using the Token ID for API testing on Postan, I divide it into 3 parts for printing.

**Comment by ricardocrescenti** [comment]
> > > Thanks for the explanation @rcrescenti. I was helping one of users debug and Invalid JWT error and this was super confusing.
> > > Did you figure out a way to "print" the entire token?
> > 
> > 
> > Sorry for the delay in responding.
> > Since I am using the Token ID for API testing on Postan, I divide it into 3 parts for printing.
> 
> please explain how u did that

String token = await this.firebaseUser.getIdToken(refresh: true);
while (token.length > 0) {
  int initLength = (token.length >= 500 ? 500 : token.length);
  print(token.substring(0, initLength));
  int endLength = token.length;
  token = token.substring(initLength, endLength);
}

**Comment by jbankz** [comment]
Okay thanks 
, I was able to solve it tho using a different approach which works faster

**Comment by ricardocrescenti** [comment]
> Okay thanks
> , I was able to solve it tho using a different approach which works faster

please explain how u did that

**Comment by Harbdollar** [comment]
@jbankz how did you solve it with different approach?

**Comment by Harbdollar** [comment]
https://stackoverflow.com/questions/49138971/logging-large-strings-from-flutter/49156942#49156942

**Comment by jbankz** [comment]
> > Okay thanks
> > , I was able to solve it tho using a different approach which works faster
> 
> please explain how u did that

sorry for the late response........
i was able to solve it using the below code snippet

void printWrapped(String text) {
    final pattern = new RegExp('.{1,800}'); // 800 is the size of each chunk
    pattern.allMatches(text).forEach((match) {
      print(match.group(0));
    });
  }

kinda wraps the outputs

**Comment by luiscelanomrb** [comment]
> I'm writing an app on Flutter and I'm making access with login by email and password, and by google account. This app will communicate with an API hosted in firebase functions, when I receive the request, I validate the user token, which is generated by `FirebaseUser.getIdToken (refresh: true)`, when the login is effected by email and password the token is successfully validated, but when I log in through Google, when I validate the token I get the following error `Firebase ID token has invalid signature. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.`
> 
> I'm using the following packages:
> - firebase_auth: ^ 0.8.4 + 5
> - google_sign_in: ^ 4.0.1 + 3 
> 
> Does anyone know how to solve it?

It works!! Thank you @ricardocrescenti

**Comment by dipendra-sharma** [comment]
> There is no problem. I'll explain what made me think it was a problem.
> 
> I was creating an API and would start the tests using Postaman, to validate if the client was authenticated, I would send the token generated by google in the request header, so to capture the generated token in the application, I would print a token on the screen, and in Postman, when I validated the token, I received that error reported above (until then I was trying to log in with my google account), so I decided to test using login by email and password, which in this case worked correctly.
> 
> After a few days of testing, I discovered that the print() had a maximum output limit, and printed only an initial part of the token, this error did not occur when I logged in via email and password because the token was small, but by google account method, return token was too large, and exceeded the maximum limit.
> 
> Do you have a similar problem?

This is not always the case. I'm getting this error. I'm sending directly from the client Android/iOS. Any suggetion?

**Comment by ricardocrescenti** [comment]
To check if the token is correct you can copy the token and paste it into the website www.jwt.io, there you can see all its contents.

Also check if the firebase project used in the application is the same used in the API, this has already happened to me in a case where we were moving from a solution project
