### ISSUE TITLE
[image_picker] has memory leak on android

### ISSUE THREAD

**Issue by careyc** [flutter/flutter#31649]
import the image_picker plugin, it will cause memory leak while exit the app.
* ThreadedRenderer$ProcessInitializer.mAppContext
* ↳ MyAppApplication.!(mActivityLifecycleCallbacks)!
* ↳ ArrayList.!(elementData)!
* ↳ array Object[].!([4])!
* ↳ ImagePickerPlugin$1.!(val$delegate)! (anonymous implementation of android.app.Application$ActivityLifecycleCallbacks)
* ↳ ImagePickerDelegate.!(activity)!
* ↳ MainActivity

**Comment by BondarenkoStas** [comment]
@careyc I believe it was fixed in https://github.com/flutter/plugins/pull/1893.
