### ISSUE TITLE
rounded SliverAppBar - shape?

### ISSUE THREAD

**Issue by mtiziano** [flutter/flutter#31656]
I made rounded **AppBar** widget with **shape** property, but this property is missing in **SliverAppBar** widget.

    Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text('Hello'),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(
            bottom: Radius.circular(30),
          ),
        ),
      ),
    )

how to have rounded corners in SliverAppBar?

![](https://i.stack.imgur.com/1Mt7W.png)

**Comment by shihaohong** [comment]
Re-opening this issue, as the implementation was reverted with https://github.com/flutter/flutter/pull/32155 due to failing analyzer tests. Working with @mtiziano to reland this

**Comment by shihaohong** [comment]
@mtiziano Any idea when you'll be able to reland your PR?
