### ISSUE TITLE
android_alarm_manager: Getting alarm ID in callback

### ISSUE THREAD

**Issue by regoje** [flutter/flutter#31658]
Hi, 

Is there any way to get the alarm ID in the callback? In fact is there any way to get any information in the Isolate -- perhaps the entire Intent?

Judging by https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/android/src/main/java/io/flutter/plugins/androidalarmmanager/AlarmService.java#L171 it isn't.

What would then be the recommended way of passing an argument of some kind -- if it's possible at all. 

I've considered saving the alarm trigger DateTime and arguments then once it does trigger querying for the alarm that's due. 

I also tried using noSuchMethod but then the argument for scheduling the alarm isn't acceptable  since the method doesn't exist. Perhaps the argument could can be changed to a string?

**Comment by Afsar-Pasha** [comment]
@regoje Implemented in version 0.4.4 https://github.com/flutter/plugins/pull/1985

**Comment by regoje** [comment]
NIcely done, thanks.
