### ISSUE TITLE
The cursor height of the `TextField` should be consistent, rather than depend on the content typed in.

### ISSUE THREAD

**Issue by yohom** [flutter/flutter#31661]
@GaryQian 

On Android:
1. Type in nothing, the height of cursor depend on white space and is short.
2. Type in Chinese, the height of cursor become to be longer.

![image](https://user-images.githubusercontent.com/10418364/56796241-b4174700-6844-11e9-9d44-7486de8d41d2.png)

On iOS:
1. Type in nothing, the height is good.
2. Type in emoji, the height is still good, but the cursor shifted up.

<img width="354" alt="Screen Shot 2019-04-26 at 17 07 38" src="https://user-images.githubusercontent.com/10418364/56796781-dbbadf00-6845-11e9-8008-a1cad375fc7e.png">

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-CN)
    • Flutter version 1.5.8 at /Users/yohom/Library/Flutter/flutter
    • Framework revision 0ba67226ee (33 hours ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yohom/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/yohom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1
```

**Comment by nillnil** [comment]
mark

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by justinmc** [comment]
This is related to https://github.com/flutter/flutter/issues/24182

**Comment by GaryQian** [comment]
Previously, Flutter used a system of manually adjusted caret heights to visually emulate those found on iOS and Android. I have since discovered that the old solution both does not scale and does not properly reflect carets on each OS.

I have begun work replacing this old system with a more modern, scalable, and accurate way of determining caret sizes. The current version has a centered and dynamically adjusting caret size for Android, and no change for iOS. I will be working on a way to reconcile the differing glyph heights, but as it stands, carets should dynamically fit the text it is surrounding, as the following example makes obvious: 
![image](https://user-images.githubusercontent.com/1887398/56828387-0a20c600-6816-11e9-8bc6-85ef1bf7cb8d.png)
The caret should be smaller for the first `test` and larger for the second `test`. The changing heights for languages is a result of our layout system remaining faithful to font metrics whereas other systems may choose to ignore some metrics in exchange for consistency across the line.

What I can definitely do now is to center the caret against the text for iOS until a more complete solution is developed.

**Comment by GaryQian** [comment]
We should also be able to better align the default no-text caret height with the typical caret height so that any change is unnoticeable. This would involve a slight rework in how we determine caret sizes and what we default to.

**Comment by 100cm** [comment]
any process on this?

**Comment by GaryQian** [comment]
As an update, I have not worked on this directly yet, but recently, fixes for the iOS caret being misaligned have landed. This is in the queue of issues I am look it right now though.

**Comment by 100cm** [comment]
@GaryQian #33175 Is the same reason?

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/9041 Should allow CSS-style line height where the height property overrides the font's provided metrics and instead scales ascent and descent to add up to a multiple of font size.

When the text is styled with `TextStyle(height: <somevalue>)`, we will be able to guarantee that the height of the line will be consistent for same combinations of fontSize and height. This would prevent carets from being different sizes for text of same size. Whether they are vertically aligned with each other or not is still not guaranteed with the above patch.

**Comment by PiN73** [comment]
Cursor height changes significantly even after single space is typed:

![empty text field](https://user-images.githubusercontent.com/18294052/79017124-3fced400-7b79-11ea-8c1b-733a8cd3b9dd.png) ![text field with space](https://user-images.githubusercontent.com/18294052/79017125-41000100-7b79-11ea-8a52-2f3f7392dccc.png)

```dart
Container(
  color: Colors.grey,
  padding: EdgeInsets.all(16),
  child: Container(
    color: Colors.white,
    child: TextField(),
  ),
)
```

Android 10, 1080 x 1260 pixels, xxhdpi

**Comment by tyirvine** [comment]
[Hi, I created a temporary solution for this problem until it gets properly fixed.](https://stackoverflow.com/questions/61145709/how-to-prevent-textfield-widgets-cursor-from-jittering-flutter?noredirect=1#comment108175591_61145709)

Can someone please explain to me why the iOS offset is set to be negative? I made a custom TextField widget and made it positive again and it seems to be working fine.

@GaryQian Thank you for looking into this issue and providing the `height:` property in your pull regarding this 😌

I'm new and loving Flutter! Everyone stay healthy!

**Comment by philipdolenko** [comment]
@GaryQian Are there any updates on the @PiN73 issue? A cursor is noticeable smaller when there is no text, an issue is still on the master channel. Would be awesome if someone fixes that

**Comment by tyirvine** [comment]
> @GaryQian Are there any updates on the @PiN73 issue? A cursor is noticeable smaller when there is no text, an issue is still on the master channel. Would be awesome if someone fixes that

Yeah I’ve been dealing with this recently. You have to set the height of line height I think.

I made a post on it in StackOverflow - look up

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by adeolaex** [comment]
> Cursor height changes significantly even after single space is typed:
> 
> ![empty text field](https://user-images.githubusercontent.com/18294052/79017124-3fced400-7b79-11ea-8c1b-733a8cd3b9dd.png) ![text field with space](https://user-images.githubusercontent.com/18294052/79017125-41000100-7b79-11ea-8a52-2f3f7392dccc.png)
> 
> ```dart
> Container(
>   color: Colors.grey,
>   padding: EdgeInsets.all(16),
>   child: Container(
>     color: Colors.white,
>     child: TextField(),
>   ),
> )
> ```
> 
> Android 10, 1080 x 2160 pixels, xxhdpi

I also have this issue. For some reason its height changes when a space or a character is typed in. 
Really degrades the UI  :|

**Comment by Daniel-Kao** [comment]
same here, cursor shrinks a bit after removing the input, and quickly changes back

**Comment by adeolaex** [comment]
> same here, cursor shrinks a bit after removing the input, and quickly changes back

It's not a solution but it would help for now.

Thanks to https://stackoverflow.com/a/61151526/10304564 , you can navigate to the text_form.dart by right clicking on the TextForm() widget and clicking on **Got to Definition**. Once in the text_form.dart, navigate to line 1059 or find the cursorOffset and change it from its original value Offset(......) to cursorOffset = Offset(0, 0);

Hope that helps.

**Comment by PiN73** [comment]
@adeolaex modifications in text_form.dart will be discarded if you upgrade Flutter / move the project to another computer / use CI/CD like codemagick, won't it?

It might be better to copy text_field.dart in the project and modify it then

**Comment by adeolaex** [comment]
Yes upgrading flutter and moving the project will most likely discard the modifications( don't know if a CI/CD would do that), but you can copy the text_field.dart into another file. The only drawback is you have to copy other dart files from the flutter sdk because they are used by text_form.dart.

**Comment by PiN73** [comment]
CI/CD won't just know about your changes in framework code and will simply use its own version

**Comment by PiN73** [comment]
When copying text_form.dart, there is no need to copy other files. You can just import them in text_dorm.dart as usually

**Comment by adeolaex** [comment]
Can you confirm all the imports work when copying it ? I tried it some days ago and it failed to recognise the URL target

**Comment by PiN73** [comment]
@adeolaex it's because of relative imports. When you write e.g.
```
import 'theme.dart';
```
it tries to find file in the same directory.

Remove all relative imports and add
```
import 'package:flutter/material.dart';
```
instead.

Then you can use it like this:
```
import 'my_text_field.dart' as my_text_field;
...
my_text_field.TextField()
```

**Comment by TahaTesser** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: Container(
            color: Colors.grey,
            padding: EdgeInsets.all(16),
            child: Container(
              color: Colors.white,
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.402, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.402 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2a188eeca3 (35 hours ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by RobiOxx** [comment]
I have the same issue

**Comment by sabetAI** [comment]
Same issue, will this ever get fixed?

**Comment by aadarsh-patel** [comment]
![cursor_bug](https://user-images.githubusercontent.com/53324291/127790072-2ca93b6f-6c50-49e0-b42e-2c6cd16f9dae.gif)

I am facing this type of cursor glitch.

Code:

```dart
                Container(
                  width: 140,
                  child: TextField(
                    controller: _pincodeController,
                    decoration: AppTheme.registrationInputDecoration(
                      labelText: "Pincode",
                      prefixIcon: Icon(
                        FontAwesomeIcons.mapMarkerAlt,
                        color: Colors.black,
                      ),
                    ),
                    style: AppText.registrationFieldStyle(),
                    onSubmitted: (str) => _searchService(),
                  ),
                ),
```
This widget is inside of a column.

**Comment by GaryQian** [comment]
@aadarsh-patel The bug you reported is a separate bug from this issue. Can you file a new issue and cc me on it + link to it here? Thanks!

**Comment by GaryQian** [comment]
The final solution to this issue may be a more configurable caret rendering system. It seems that depending on the use case, different caret behavior is desired. There may not be a one-solution fits all caret.

Perhaps something like the following may work better for most use cases:

```
TextField(
  ...
  caretStyle: CaretStyle.dynamic/fixed/strut/textStyle(
    heightAdjustment: ...,
    (various other params as necessary)
  ),
  ...
)
```

**Comment by GaryQian** [comment]
Meanwhile, we currently have already added the `cursorHeight` parameter to text fields. If you are experiencing the single space changing the caret height, try setting the `cursorHeight` to lock the caret height to a specific value.

**Comment by GaryQian** [comment]
I believe the original issue of caret alignment and height is resolved via new parameters, and more fine tuned control would likely require a breaking overhaul of the caret config system. Breaking changes/deprecating the current config is a large API commitment and thus I will close this issue for now. Let's continue to discuss the tangent bugs mentioned above in separate issues.
