### ISSUE TITLE
I can't launch it in android studio

### ISSUE THREAD

**Issue by ManuchekhrT** [flutter/flutter#31663]
Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;

**Comment by l-k22** [comment]
https://stackoverflow.com/questions/52483773/dartui1-error-not-found-dartui-flutter-dart

**Comment by ManuchekhrT** [comment]
yeah i got it, thx

**Comment by BondarenkoStas** [comment]
thank you @l-k22 ! now I think it's safe to close it.
