### ISSUE TITLE
Getting warning while creating a release build in flutter

### ISSUE THREAD

**Issue by yash365** [flutter/flutter#31669]
Getting the following warning :
Warning: This VM has been configured to obfuscate symbol information which violates the Dart standard. See dartbug.com/30524 for more information.

Added the following code to avoid reverse engineer:

gradle.properties:
`extra-gen-snapshot-options=--obfuscate`

**Comment by realvotum** [comment]
I am getting that to with the following gradle.properties:
`android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536M
extra-gen-snapshot-options=--obfuscate,--save-obfuscation-map=build/symbols.json`

How do we avoid this warning? Or how do we configure VM not to violate the Dart standard (whatever it means)?

**Comment by tzifudzi** [comment]
This issue seems to have been resolved . See [dart bug](https://github.com/dart-lang/sdk/issues/30524).

@jensjoha @mraleph Please confirm.

**Comment by mraleph** [comment]
The warning is still emitted. It is there to remind that obfuscated code behaves slightly differently then the normal Dart code would.

There are currently no plans to remove the warning.
