### ISSUE TITLE
Request: Add a LogOut Icon to the list of icons

### ISSUE THREAD

**Issue by l-k22** [flutter/flutter#31665]
I wanted to add a login/logout button to my application I was surprised to see there is no dedicated icon for logout.

https://docs.flutter.io/flutter/material/Icons-class.html

I don't know what ['Exit_to_app'](https://docs.flutter.io/flutter/material/Icons/exit_to_app-constant.html) is meant to mean, but it definitely isn't right and probably named incorrectly, the icon looks too similar to ['input'](https://docs.flutter.io/flutter/material/Icons/input-constant.html)

The only ones left are ['eject'](https://docs.flutter.io/flutter/material/Icons/eject-constant.html) or  ['phonelink_erase'](https://docs.flutter.io/flutter/material/Icons/phonelink_erase-constant.html) which is what I've settled on.

Thanks

**Comment by minh98** [comment]
yes. i like it :)

**Comment by HansMuller** [comment]
@willlarche are we missing a standard material icon or maybe material is missing a standard icon?

**Comment by willlarche** [comment]
I can put in a request but no there is no public official log out icon.

**Comment by willlarche** [comment]
The request has received a positive response. No promises yet but updating to be transparent.

**Comment by syonip** [comment]
any update?
