### ISSUE TITLE
Error on line 1, column 1 of pubspec.lock: Unexpected character

### ISSUE THREAD

**Issue by MeshkaniMohammad** [flutter/flutter#31660]
I have a problem with upgrading packages. This problem occurred after cloning a repo and running `flutter packages upgrade` in the project.

```
[flutter_architecture_samples] flutter packages get
Building flutter tool...
Running pub upgrade...
Error on line 1, column 1 of pubspec.lock: Unexpected character.
  ╷
1 │ 
  │ ^
  ╵
Error (65): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Running pub upgrade...
Error on line 1, column 1 of pubspec.lock: Unexpected character.
  ╷
1 │ 
  │ ^
  ╵
Error (65): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Running pub upgrade...
Error on line 1, column 1 of pubspec.lock: Unexpected character.
  ╷
1 │ 
  │ ^
  ╵
Error (65): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
Running pub upgrade...
Error on line 1, column 1 of pubspec.lock: Unexpected character.
  ╷
1 │ 
  │ ^
  ╵
Error (65): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
Running pub upgrade...
Error on line 1, column 1 of pubspec.lock: Unexpected character.
  ╷
1 │ 
  │ ^
  ╵
```
here is all errors. and after this, I wasn't able to run `flutter doctor` or `flutter upgrade`
I'm in channel `master` and latest version of flutter.

**Comment by l-k22** [comment]
what happens if you delete the lock file?

**Comment by MeshkaniMohammad** [comment]
@l-k22 I didn't try it because I couldn't find that file. anyway, I solved the problem by reinstalling flutter.
for reinstalling flutter look at [this](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted) link.

**Comment by l-k22** [comment]
Cool. You should close this since you've managed to solve it

**Comment by rohitsainik** [comment]
can you share your lock file with me

**Comment by mayowaegbinola** [comment]
@MillerAdulu Thanks so much!
This worked for me.
The trick - I simply replaced the broken pubspec.lock file in my project directory with the newly generated pubspec.lock file.

**Comment by BalanaguYashwanth** [comment]
No need to replace with new file, Just delete it the PUBSPEC.LOCK file and then run the flutter run
it will automatically generate the new PUBSPEC.LOCK fie 


It will solve your problem😊😊😊
