### ISSUE TITLE
Images and Font not loading on iOS on start

### ISSUE THREAD

**Issue by nafis042** [flutter/flutter#31673]
Everything works on android but in iOS it causes the problem. I have attached a screenshot below. This is the initial screen. I have already done flutter clean, flutter build ios etc. 

![attachment-8262172709298533099Screenshot-0425-152401](https://user-images.githubusercontent.com/26213218/56820279-47fd0900-686d-11e9-9199-8ded9999d8d5.png)

## Steps to Reproduce

1. flutter clean
2. flutter build ios --release
3. flutter install

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E205e, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

```

**Comment by BondarenkoStas** [comment]
@nafis042 was it fixed or you still encounter the issue?

**Comment by nafis042** [comment]
@BondarenkoStas it is fixed. I am closing the issue.
