### ISSUE TITLE
Is it possible to generate Robo Script or record Espresso test?

### ISSUE THREAD

**Issue by PauloKeller** [flutter/flutter#31670]
Regarding Firebase Test Lab, to use Robo Test feature I can upload a robo script, is it possible to create the script with Flutter Apps? When I try Android Studio warning's me that I doesn't have a valid application, the same happen's when I try to record Espresso Test.

**Comment by dnfield** [comment]
There's some work going on right now to make Espresso work better with Flutter.  @adazh may have more information.

**Comment by adazh** [comment]
Robo script or Espresso test recording for Flutter is not supported yet. We are working on adding Flutter support in Espresso, so these functionalities should follow after we have Espresso-Flutter support in place.

**Comment by bartektartanus** [comment]
Any progress on this?

**Comment by adazh** [comment]
We are actively working on the Espresso-Flutter support. Stay tuned :).

**Comment by campioncino** [comment]
> We are actively working on the Espresso-Flutter support. Stay tuned :).

So...what news?

**Comment by TahaTesser** [comment]
Since PR is merged 
 I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
 Thank you
