### ISSUE TITLE
The flutter_tool contains 3 vm_service client implementations

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#31688]
Currently the flutter tool knows how to talk to the vm_service in 3 separate ways.

1. The vm_service_lib which is still pulled in transitively from package:coverage. (@grouma has expressed plans to upgrade this package to use the modern vm_service_client).

2. The vm_service_client, which might only be used transitively, but contains the fully generated API.

3. Our own vm_service client implementation. This does not cover the full API, only the parts require for hot reload.

We should identify the feasibility of replacing our implementation with the generated version.

**Comment by bkonyi** [comment]
FYI @jonahwilliams @devoncarew, it looks like classes from `package:vm_service_client` are exposed through `package:flutter_driver`: https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/serviceClient.html. This might be hard to remove...

**Comment by devoncarew** [comment]
It would be a breaking change to address that, but we may be able to estimate the impact on the community - get a back of the envelope estimate of the number of users actually depending on that part of the API.

**Comment by devoncarew** [comment]
And then it could just follow the std breaking change process.

**Comment by jonahwilliams** [comment]
flutter_driver is not used as heavily as other libraries. I think the breaking change would be fairly simple, provided we address usage in fuchsia and google3.

**Comment by jonahwilliams** [comment]
Going to leave https://github.com/flutter/flutter/issues/37499 as the driver migration, while https://github.com/flutter/flutter/issues/52179 will address the tool migration
