### ISSUE TITLE
Avoid/remove foo.runtimeType.toString()

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#31695]
`AbstractType_toString` is showing up in cpu profiles while scrolling on time zone selection screen on Fuchsia. This is a heavy operation and we should try to avoid it. `AbstractType_toString` is used when `toString()` is called on a result of `foo.runtimeType`.

Profiler points to the following places where this pattern is heavily used in Flutter:

1.` Widget.toStringShort()`:
```dart
String toStringShort() {
  return key == null ? '$runtimeType' : '$runtimeType-$key';
}
```
It is called from `ImplicitlyAnimatedWidgetState.initState()` at line
```dart
debugLabel: '${widget.toStringShort()}',
```

2. `BallisticScrollActivity` constructor at line
```dart
debugLabel: '$runtimeType',
```
3. Function `describeIdentity`:
```dart
String describeIdentity(Object object) => '${object.runtimeType}#${shortHash(object)}';
```

It is called from `Diagnosticable.toStringShort`:
```dart
String toStringShort() => describeIdentity(this);
```
which is called from `Diagnosticable.toString`,
which is called from `SingleTickerProviderStateMixin.createTicker`:
```dart
_ticker = Ticker(onTick, debugLabel: 'created by $this');
```

@alexmarkov

**Comment by eseidelGoogle** [comment]
I'm not sure if this is still actionable as is, or if we should just close this and re-profile when needed?

Speculatively closing, please feel empowered to re-open! (And apologies for the noise if I'm closing incorrectly.)

**Comment by jonahwilliams** [comment]
Also fyi @dnfield

**Comment by dnfield** [comment]
I'm going to re-open this.  At a minimum, we should consider updating the style guide to _not_ recommend using `'$runtimeType(property: $property)'` as a boilerplate for toString.

We should also consider whether we can remove these from all our `toString` implementations, as this is an easy trap to fall into.  It does help when subclasses are depending on the parent class to use the right type, but we could also just add the toString without `$runtimeType` in it.

**Comment by Hixie** [comment]
I don't really understand the issue here. We definitely don't want to stop using `'$runtimeType'` in debug mode. In release mode I'm fine with `toString` in general throwing except for `int` and `String` and maybe `bool` (though of course that's a major breaking change so it would have to be opt-in).

**Comment by Hixie** [comment]
better would be to have a lint that verifies you're not using this outside of asserts. cc @a14n

**Comment by dnfield** [comment]
Perhaps we could just write a wrapper method in foundation like:

```String objectRuntimeType(Object object) {
  String result = '<optimized out>';  
  assert(() {
    result = object.runtimeType.toString();
    return true;
  }
  return result;
}
```

**Comment by Hixie** [comment]
That wouldn't help the original problem, though, which was someone using `runtimeType` in a String intentionally (so they wouldn't call that method).

**Comment by dnfield** [comment]
We could add a check that the strings `$runtimeType` and `runtimeType.toString()` don't occur, right?

**Comment by Hixie** [comment]
Oh actually I misunderstood the original complaint. Those cases are all debug cases that are just wasted in release mode, so yes, it would work for that. Go for it.
