### ISSUE TITLE
docs.flutter.io don't include mojo-specific types/identifiers

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3169]
Some of our APIs expect Mojo types, but those types/identifiers aren't known when we generate the docs for http://docs.flutter.io. This means a developer hits a "wall" when exploring our APIs.

For example, the apparent way to do audio is SoundEffectPlayer from flutter_sprites: http://docs.flutter.io/flutter_sprites/SoundEffectPlayer-class.html  This class wants a `MojoDataPipeConsumer` for its `load()` call. Unfortunately, `MojoDataPipeConsumer` isn't linked to, so I'm not sure what this is.

**Comment by eseidelGoogle** [comment]
mojo is gone.
