### ISSUE TITLE
Links to API docs in gallery don't show contents

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#31708]
e.g. open gallery, go to cupertino > pickers > hit the book icon. You get a blank screen other than the title.

I'm guessing we're not enabling JS and JS is required for our docs, or some such.

**Comment by shihaohong** [comment]
It seems to work just fine when I ran it on an iOS simulator, iPhone 8.

<img width="443" alt="Screen Shot 2019-05-02 at 5 26 23 PM" src="https://user-images.githubusercontent.com/27032613/57114725-6d6f9400-6cff-11e9-8343-0c81ae0d7288.png">

**Comment by shihaohong** [comment]
Fixed with https://github.com/flutter/flutter/pull/30460
