### ISSUE TITLE
Force iOS mode in Cupertino section of Gallery

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#31709]
We should force the Gallery's Cupertino section into full iOS mode, so that e.g. overscroll works like on iOS. In particular, without doing so, the pull-to-refresh demo doesn't work.

**Comment by TahaTesser** [comment]
@Hixie 
Do you think iOS mode in https://github.com/flutter/gallery does this job?
Thank you

**Comment by Hixie** [comment]
This is specific to the old gallery, so closing. We're not going to fix bugs in the old gallery itself now that it's just a benchmarking target.
