### ISSUE TITLE
Support embedding native views in Linux shell

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#31714]
We'll need support for embedding native views in Flutter views (e.g., for embedding a web view, as on mobile).

Obviously this depends on having a view-based Linux shell first (#30729).

**Comment by robert-ancell** [comment]
@stuartmorgan is this a dupe of https://github.com/flutter/flutter/issues/41724?

**Comment by stuartmorgan** [comment]
Indeed! Whoever filed and triaged that issue should really have searched for duplicate issue first! 🙃
