### ISSUE TITLE
flutter run/drive take too long to launch apps on iOS simulator

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3172]
Output:

```
~/flutter/awesomesauce $ flutter -d iPhone run
Running lib/main.dart on iPhone 6s (Flutter)...
Observatory listening on http://127.0.0.1:63403
~/flutter/awesomesauce $ flutter -d iPhone drive
Starting application: lib/main.dart
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
```

Note that `flutter run` does indeed run on the simulator.

**Comment by yjbanov** [comment]
I think what's actually happening is that sometimes the iOS build takes up to 20 seconds before the app is launched. If you wait long enough the app will launch.

**Comment by eseidelGoogle** [comment]
@yjbanov did you mean another bug?

**Comment by yjbanov** [comment]
This is the correct bug. When we were looking at this issue with @sethladd we didn't wait long enough for the app to start. Also, this is not just a `flutter drive` issue, `flutter run` is also affected. This is what's going on:

```
34213 ms • /usr/bin/xcrun simctl launch 827E2B4E-81AE-47C2-BCBE-BD596AB55761
com.yourcompany.sampleApp --flx=/Users/yjbanov/code/tmp/sample_app/build/app.flx
--dart-main=/Users/yjbanov/code/tmp/sample_app/lib/main.dart
--packages=/Users/yjbanov/code/tmp/sample_app/.packages --enable-checked-mode
--start-paused --observatory-port=8183
```

**34 seconds** to launch the app on the iOS Simulator.

Another observation is that it is not happening with the Stocks app, only with the app created using `flutter create`.

**Comment by yjbanov** [comment]
Oh, also, the existence of the `build` directory has no effect.

**Comment by sethladd** [comment]
I wonder if we can show a spinner here?

**Comment by Hixie** [comment]
Is this still an issue? I haven't heard people complain about it...

**Comment by sethladd** [comment]
We have another issue which asks for a spinner here, displaying while we
are going to into the simulator for the first time. That might be
sufficient for now.

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/8937

**Comment by Hixie** [comment]
Closing since it's not clear what is actionable here.
