### ISSUE TITLE
[Feature Request] Support CSS-like Widget Parameter Styling Abilities

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#31722]
Let's say In my medium sized app, that I have a general styling that I use. All ListTiles on a certain page have a contentPadding of `EdgeInsets.zero`. I accomplish this by either, setting this property in each ListTile explicitly, or I create a custom widget and use that. This is a good solution. This also exists with colors for things like icons. You can either set it explicitly or create a custom widget. Flutter also provides a Theme widget for convenience to style all icons below it. Can we have this same third convenience for things other than TextStyles and colors?
The solution would accept a Widget of any type as the `toStyle:` property. and then the other property would be the values to apply. This isn't a suggested implementation, but this effectively illustrates what I'm referring to.

```
WidgetStyle(
     widgetToStyle: ListTile, 
     params: {'contentPadding': EdgeInsets.zero}, 
     child: myChild
    )
```

**Comment by goderbauer** [comment]
Flutter prefers composition here, and we don't have plans to change this.
