### ISSUE TITLE
Issue from website page 在Flutter中构建布局

### ISSUE THREAD

**Issue by xiejibiao** [flutter/flutter#31726]
From URL: https://www.flutterchina.club/tutorials/layout/index.md

这段代码，压根就不能直接运行，能不能不给我这种小白挖坑？

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(32.0),
      child: new Row(
        children: [
          new Expanded(
            child: new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                new Container(
                  padding: const EdgeInsets.only(bottom: 8.0),
                  child: new Text(
                    'Oeschinen Lake Campground',
                    style: new TextStyle(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                new Text(
                  'Kandersteg, Switzerland',
                  style: new TextStyle(
                    color: Colors.grey[500],
                  ),
                ),
              ],
            ),
          ),
          new Icon(
            Icons.star,
            color: Colors.red[500],
          ),
          new Text('41'),
        ],
      ),
    );
    //...
  }

**Comment by IoTServ** [comment]
大哥，稳，在github用中文问问题，关键还不是国内项目，【斜眼笑】

**Comment by hwp1234** [comment]
it work perfect

**Comment by vy12021** [comment]
1.请用英文提问。
2.请按照提问模板提问，使用标记语法(markdown)标记代码区，并注意代码格式。
3.请先检查自己的环境，确认是否是自身配置问题。
4.不要用这种网络喷子的语气。
5.注意形象，你使用中文代表了中国。

**Comment by aaassseee** [comment]
那个网页不是Google翻译的
请稍移玉步
![未命名](https://user-images.githubusercontent.com/2054978/56859609-0af55b80-69c0-11e9-97c1-8c89899721cc.png)

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
