### ISSUE TITLE
Visual studio code Intellisense / Auto complete not working in Flutter stable channel

### ISSUE THREAD

**Issue by muzavvir** [flutter/flutter#31724]
Visual studio code Intellisense / Auto complete not working in Flutter stable channel.

Switching to master channel works.

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.9-pre.43, on Microsoft Windows [Version 10.0.17134.523], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.1)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

**Comment by DanTup** [comment]
Moving this to the Dart-Code repo, but could you add an [Analysis Server log](https://dartcode.org/docs/logging/#analyzer) over there? Thanks!
