### ISSUE TITLE
Strange behaviour when closing app via back button on Android

### ISSUE THREAD

**Issue by Butzlabben** [flutter/flutter#31734]
Hi, 
when you close the app with the back button on Android, the app gets restarted. But plugins not.
With this behaviour, some bugs occur. Plugins get detached but are running in the background. If the plugin sends something to the dart part, this error message gets thrown: `FlutterView.send called on a detached view, channel=xyz.luan/audioplayers`.
But if you open the app again, the old plugin part is still running but is no longer connected to the dart part of the app.
Consequences can look following: https://github.com/luanpotter/audioplayers/issues/144

**Comment by nitinmehtaa** [comment]
@Butzlabben Hi, Can you share piece of code here and flutter:doctor result ?

**Comment by Butzlabben** [comment]
Hi, a piece of code would be the example of this audio player https://github.com/luanpotter/audioplayers
Steps to reproduce:
1. Clone this repo https://github.com/luanpotter/audioplayers
2. Run the example
3. Start the audio stream
4. Close the app via the back button
5. Open app again

The output from `flutter doctor -v`:

`[√] Flutter (Channel beta, v1.5.4, on Microsoft Windows [Version 10.0.17134.706], locale de-DE)
    • Flutter version 1.5.4 at D:\Programs\flutter
    • Framework revision b593f5167b (6 days ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Programs\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at D:\Programs\AndroidStudio
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 35.0.3
    • Dart plugin version 191.7019

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!`

**Comment by nitinmehtaa** [comment]
@Butzlabben As i saw in 'issues' of the above repo, it is a bug. As far as i have tried it must be from Flutter side.
https://github.com/luanpotter/audioplayers/issues/144

**Comment by Butzlabben** [comment]
bump, I think this is a very critical issue.

**Comment by letiagoalves** [comment]
has someone found a quick fix for this yet?

**Comment by BondarenkoStas** [comment]
@Butzlabben is it the same with current flutter stable v1.9.1+hotfix.4?

**Comment by Butzlabben** [comment]
Well, it somehow still exists, but very strange.
First, it is the same behavior. When I waited long enough outside the app, then it stops playing, with the message 
```
W/MediaPlayer-JNI( 4774): MediaPlayer finalized without being released
W/MediaPlayer-JNI( 4774): MediaPlayer finalized without being released
```

But when I get back in very fast, the bug is the same as above

**Comment by TahaTesser** [comment]
Hi @Butzlabben 
Does this issue still exist?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @Butzlabben 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
