### ISSUE TITLE
RaisedButton Text default fontWeight is bold in iOS and normal in Android, is this expected?

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#31730]
Flutter (Channel dev, v1.4.12, on Mac OS X 10.13.6 17G4015, locale en-CN)

Hi, I find out RaisedButton Text default fontWeight is bold in iOS (iphoneX simulator) and normal in Android physical device, is this expected?

I can change the fontWeight manually, but I am wondering why they are different defaults. This doesn't make sense to me. Thanks a lot.

**Comment by nitinmehtaa** [comment]
@sgon00 It is same for me, I've tried MaterialApp "RaisedButton" in CupertinoPageScaffold even
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Center(
        child: RaisedButton(
          child: new Text(
            'Hello there',
          ),
          onPressed: () {},
        ),
      ),
    );
  }
}
`

**Comment by nitinmehtaa** [comment]
@sgon00 It is same for me.
https://gist.github.com/nitinmehtaa/5e3eb8fe08f98854222ba39073b3dd60

**Comment by TahaTesser** [comment]
Hi @sgon00 
This seems to be be fixed


![image](https://user-images.githubusercontent.com/48603081/76618587-f7f36780-654e-11ea-8bcb-031548ef2518.png)


if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
