### ISSUE TITLE
flutter drive does not work if multiple devices/simulators are connected

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3173]
If I have two devices or simulators connected (as I often do), then `flutter drive` fails to run on the selected device.

**Comment by Hixie** [comment]
Is the problem here that there's no way to pick a device, unlike `flutter run`? I thought they shared that code.

**Comment by yjbanov** [comment]
I just tried the following two scenarios and both worked:

- Two Android devices connected to a Linux computer
- A physical iPhone 6 and an iOS Simulator connected to a Mac

In both cases I could select a device using option `-d` as well as have the driver pick a device automatically when a device is selected. Closing this. Feel free to reopen if this is still an issue.

**Comment by DhonyImamS** [comment]
Hi @yjbanov , I want to ask you related this issue,

here your piece of code on drive.dart
  if (devices.isEmpty) {
    printError('No devices found.');
    return null;
  } else if (devices.length > 1) {
    printStatus('Found multiple connected devices:');
    printStatus(devices.map<String>((Device d) => '  - ${d.name}\n').join(''));
  }
  printStatus('Using device ${devices.first.name}.');
  return devices.first;
}

so it has meaning that even multiple device it just follow device first name,.. and never run both simultaneously like @sethladd  want,.. cause i'm try to run flutter drive in multiple device android also

could you give me helping for this ? thanks

**Comment by yjbanov** [comment]
I don't think @sethladd was asking for running on both simultaneously (I think this discussion predates `-d all` option). The issue was that `flutter drive` would not run anything at all when it finds more than one device. If you would like a capability to run a driver test on multiple devices simultaneously, that's a new feature request.

**Comment by yjbanov** [comment]
Just a heads up, that would be a very non-trivial feature, as it implies that a single instance of `FlutterDriver` must learn to coordinate synchronization across multiple devices. Different devices are likely to have different screen sizes, and test code can be sensitive to that. What happens, for example, when 500px scroll offset on one device takes you in the middle of a list view, and on another device it takes you to the bottom of the list?

**Comment by DhonyImamS** [comment]
> I don't think @sethladd was asking for running on both simultaneously (I think this discussion predates `-d all` option). The issue was that `flutter drive` would not run anything at all when it finds more than one device. If you would like a capability to run a driver test on multiple devices simultaneously, that's a new feature request.

oh yeah,.. sorry, its true that it is new feature on this link https://github.com/flutter/flutter/issues/33129, i've got found , thanks to your confirmation

**Comment by DhonyImamS** [comment]
> Just a heads up, that would be a very non-trivial feature, as it implies that a single instance of `FlutterDriver` must learn to coordinate synchronization across multiple devices. Different devices are likely to have different screen sizes, and test code can be sensitive to that. What happens, for example, when 500px scroll offset on one device takes you in the middle of a list view, and on another device it takes you to the bottom of the list?

yeah i know ,.. it just starting for me to dig in in the world of mobile automation testing,.. but espresso has the spoon from gradle, or appium using selenium grid,.. so this is the matter for me to take a look "how about the flutter UI test",..
