### ISSUE TITLE
DraggableScrollableSheet gets stuck and won't move

### ISSUE THREAD

**Issue by mrmko** [flutter/flutter#31739]
If maxChildSize is set to 1.0 and actual fractional value of the parent is less than 1.0 (child can't fill parent completly), then once DraggableScrollableSheet reaches its max it won't scroll back down.

##
## Steps to Reproduce

 

1. Create a DraggableScrollableSheet with maxChildSize set to 1.0
2. Set the parent containers actual fractional value to less than 1.0
3. Run app and scroll the sheet to its highest position. (it will get stuck)

https://gist.github.com/mrmko/40e34852fff8686753e0e9b8b5234784

@dnfield

**Comment by dnfield** [comment]
While I agree something is wrong here, I'm not really sure what the expected behavior would be.

As far as I can tell, you don't actually have enough content in your list for it to actuall scroll.  

Do you expect this to be able to somehow keep dragging to the top of the scaffold, and then be dragged back down?  Do you expect it to stop when there's no more scroll extent, and then be able to drag it back down?

**Comment by dnfield** [comment]
For instance, if you change your widget to instead have a `maxChildSize` of `0.33`, are you seeing the expected behavior?

**Comment by sidazhang123** [comment]
ummmmm

**Comment by Zazo032** [comment]
There's not much information in material docs explaining how it should behave, but as you can see in Google Tasks bottom sheet menu, it stops when there's no more scroll extent, and then you can only drag to close it. That might be the expected behavior, but more docs in material.io according to this case would be nice @dnfield

**Comment by orteney** [comment]
Hello, i'm also facing some kind of freezing when used DraggableScrollableSheet in showModalBottomSheet. If you has ListView with children more than 0.5 and less than 1.0 of parent height, then when you expand sheet you're unable to tap on buttons. In that case any tap registered as tap on body and closes ModalBottomSheet.

Here minimal example: https://gist.github.com/orteney/fc48aab118a52668b59e5b0dc58ea109
Please, modify button's count to get described childred height :)

**Comment by danbydesign** [comment]
I can confirm this as well. Here is a minimal example taken straight from the source:

```dart
@override
Widget build(BuildContext context) {
  return MaterialApp(
    home: Scaffold(
      appBar: AppBar(),
      body: SizedBox.expand(
        child: DraggableScrollableContainer(
          initialChildSize: 0.2,
          minChildSize: 0.2,
          builder: (BuildContext context, ScrollController scrollController) {
            return Container(
              color: Colors.blue[100],
              child: ListView.builder(
                controller: scrollController,
                // Setting this to a higher value (eg. 25) will resolve the issue
                itemCount: 5,
                itemBuilder: (BuildContext context, int index) {
                  return ListTile(title: Text('Item $index'));
                },
              );
            );
          }
        ),
      ),
    )
  );
}
```

**Comment by dnfield** [comment]
#31832 should fix this - anyone experiencing this, please verify that it does.

**Comment by cpboyd** [comment]
@dnfield What about if we want a DraggableScrollableSheet to be exactly 1.0 at all times?
Like the "Filters" bottom sheet in Google's own Google I/O 2019 app?

```dart
      return DraggableScrollableSheet(
        builder: scroll,
        initialChildSize: 1.0,
        minChildSize: 1.0,
      );
```

It currently breaks the ability to scroll the sheet and only ever dismisses it when you interact.

This is potentially also related to a request for drag length in #34111

**Comment by dnfield** [comment]
I'm not sure why you'd use this widget if you want it to be 1.0 at all times - perhaps you could open a new issue with your use case?  Feel free to tag me in it.
