### ISSUE TITLE
Unable to fully execute flutter.bat

### ISSUE THREAD

**Issue by zhuxipeng** [flutter/flutter#31747]
===  My CMD console   ==============================================
d:\flutter\flutter\bin (stable)
λ flutter upgrade
Building flutter tool...
Running pub upgrade...
Got socket error trying to find package mime at https://pub.dartlang.org.
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...
Running pub upgrade...

==============================================================

When I selected /flutter/bin/flutter. Bat, the above problem appeared. Has anyone ever encountered this problem

**Comment by zhuxipeng** [comment]
Got socket error trying to find package mime at https://pub.dartlang.org.
Error Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)


=======There it is===============

**Comment by BaderEddineOuaich** [comment]
See if `` pub cache repair `` will solve that

**Comment by zhuxipeng** [comment]
Thank you for having solved this problem.
I downloaded a new SDK
