### ISSUE TITLE
flutter attach encountered a crash

### ISSUE THREAD

**Issue by lordlamb** [flutter/flutter#31743]
## Steps to Reproduce

1. upgrade flutter to beta channel, version 1.5.4
2. using `flutter attach` command

## Logs

[flutter_01.log](https://github.com/flutter/flutter/files/3124683/flutter_01.log)

**Comment by DanTup** [comment]
@bkonyi this might be related to the VM URI changes:

```
NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:219:78)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
```

**Comment by jonahwilliams** [comment]
It looks like the mdns lookup failed. We should ensure that we exit gracefully at that point

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/attach.dart#L219
