### ISSUE TITLE
CupertinoSwitch vibrates on build

### ISSUE THREAD

**Issue by hgl** [flutter/flutter#31742]
## Steps to Reproduce

1. Use this code in build
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            CupertinoSwitch(
              value: _switchValue,
              onChanged: (bool value) {
                setState(() { _switchValue = value; });
              },
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
```
2. tap floating action button
3. feel the haptic vibration

I think the reason is that in #27114, the logic is that when onChanged callback is re-set, vibration is triggered, and when the widget is being re-build, its `onChanged` is new, thus the vibration.

I wonder if my usage of CupertinoSwitch is incorrect or it should actually vibrate only when its value has changed (and not the callback)

@jslavitz @xster

**Comment by dimitristaufer** [comment]
+1

**Comment by eseidelGoogle** [comment]
_incrementCounter is missing from your example.  Would you be able to add a more complete example?

It's hard to tell from the description as written what happens when the floating action button is pressed without the _incrementCounter code.  (I presume you modified it from the default.)

**Comment by TahaTesser** [comment]
Hi everyone
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
