### ISSUE TITLE
Hi,I am using list view builder for my application. In this, each item has an edit button. In response to action on edit button, I am showing dialog. When I click on textfield in dialog app crashes.

### ISSUE THREAD

**Issue by RajeshBudhiraja** [flutter/flutter#31749]
Code:
IconButton(
//                                            icon: Icon(
//                                              Icons.edit,
//                                              color: Colors.indigo,
//                                            ),
//                                            onPressed: () {
//                                              var currentNews = leagueNews[
//                                                  leagueNews.length -
//                                                      1 -
//                                                      index]["news_item"];
//                                              showDialog(
//                                                  context: context,
//                                                  builder:
//                                                      (BuildContext context) {
//                                                    updateNewsTextController
//                                                        .text = "";
//                                                    return AlertDialog(
//                                                      title:
//                                                          Text("Update News"),
//                                                      content: Container(
//                                                        constraints: BoxConstraints(
//                                                            maxWidth: MediaQuery.of(
//                                                                        context)
//                                                                    .size
//                                                                    .width *
//                                                                0.5),
//                                                        child: TextField(
//                                                          controller:
//                                                              updateNewsTextController,
//                                                          decoration:
//                                                              InputDecoration(
//                                                                  hintText:
//                                                                      currentNews),
//                                                          style: TextStyle(
//                                                            fontSize: 20,
//                                                            color: Colors
//                                                                .grey[900],
//                                                          ),
//                                                        ),
//                                                      ),
//                                                      actions: <Widget>[
//                                                        IconButton(
//                                                          icon:
//                                                              Icon(Icons.done),
//                                                          onPressed: () {
//                                                            setState(() {
//                                                              BackendOperations.updateLeagueNews(
//                                                                  updateNewsTextController
//                                                                      .text,
//                                                                  leagueNews[leagueNews
//                                                                              .length -
//                                                                          1 -
//                                                                          index]
//                                                                      [
//                                                                      "news_item"]);
//                                                              this.leagueNews[
//                                                                      leagueNews
//                                                                              .length -
//                                                                          1 -
//                                                                          index] =
//                                                                  updateNewsTextController
//                                                                      .text;
//                                                              Navigator.pop(
//                                                                  context);
//                                                            });
//                                                          },
//                                                        ),
//                                                        IconButton(
//                                                          icon: Icon(
//                                                              Icons.cancel),
//                                                          onPressed: () {
//                                                            Navigator.pop(
//                                                                context);
//                                                          },
//                                                        )
//                                                      ],
//                                                    );
//                                                  });
//                                            }),

I am using stream builder to populate list builder from backend. Now, i want to edit loaded data. For this, I am using this action.

When I click on textfield inside dialog, I am getting error. I have tried creating a key for scaffold as well as creating different class for building alert widget with no success.

**Comment by RajeshBudhiraja** [comment]
I/flutter (21424): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21424): The following assertion was thrown building Builder(dirty):
I/flutter (21424): Looking up a deactivated widget's ancestor is unsafe.
I/flutter (21424): At this point the state of the widget's element tree is no longer stable. To safely refer to a
I/flutter (21424): widget's ancestor in its dispose() method, save a reference to the ancestor by calling
I/flutter (21424): inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
I/flutter (21424): 
I/flutter (21424): When the exception was thrown, this was the stack:
I/flutter (21424): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3252:9)
I/flutter (21424): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3261:6)
I/flutter (21424): #2      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3276:12)
I/flutter (21424): #3      Theme.of (package:flutter/src/material/theme.dart:128:52)
I/flutter (21424): #4      showDialog.<anonymous closure> (package:flutter/src/material/dialog.dart:705:37)
I/flutter (21424): #5      _DialogRoute.buildPage (package:flutter/src/widgets/routes.dart:1484:14)
I/flutter (21424): #6      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:655:43)
I/flutter (21424): #7      Builder.build (package:flutter/src/widgets/basic.dart:6035:41)
I/flutter (21424): #8      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (21424): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (21424): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (21424): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (21424): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (21424): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (21424): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (21424): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (21424): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (21424): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (21424): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (21424): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (21424): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (21424): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (21424): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (21424): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (21424): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (21424): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (21424): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (21424): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (21424): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (21424): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (21424): #47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (21424): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (21424): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (21424): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (21424): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (21424): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (21424): #56     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (21424): #57     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (21424): (elided 3 frames from package dart:async)

**Comment by harisk92** [comment]
@RajeshBudhiraja first use template and fill it with proper explanation any maybe code snippets.What I see from stack trace you posted you are trying to access to deactivated parent.

**Comment by nitinmehtaa** [comment]
@RajeshBudhiraja You can try this code
https://gist.github.com/nitinmehtaa/7c8d44b1a3cf93dafe6b1ec36f129a68
