### ISSUE TITLE
Slow performance on PowerVR device?

### ISSUE THREAD

**Issue by mesb1** [flutter/flutter#31746]
Hi.

There was application created with latest stable flutter.
When i try use it on old phones with PowerVR GPU, it looks like there is something goes wrong.
For some elements, that used first time, app is very slow.
After first time use, this elements woks fast.
But for some elements problem still there even after first use.

## Steps to Reproduce
Install app into PowerVR device:
https://github.com/mejgun/vbr
Open menu, close menu. Its slow for first time.
Now open menu again, now its fast.
Same with settings in that menu.

But when you try swipe down on main screen, animation with loading always slow.
There is video:
https://youtu.be/5PyRRy93_iQ
https://youtu.be/Uw1wgIQJL1w

Tested on 
lenovo p780 Android 4.4.2 PowerVR sgx544
digma idsq 10 3g Android 4.4.2 PowerVR sgx544mp2
Both of them run gallery flutter app only once, after first start no matter what i do, app crash or something.

This bug isnot appear if device is mali based.
Like lenovo p70  with 4.4 Android and mali GPU.

As i see there is already was issue about old devices with slow work problem on such gpu
https://github.com/flutter/flutter/issues/14036
https://github.com/flutter/flutter/issues/14035
https://github.com/flutter/flutter/issues/11794
https://github.com/flutter/flutter/issues/7150

Is there any workaround (disable some animation maybe) for that to get flutter app work for old devices?

**Comment by darshankawar** [comment]
@mesb1 
Is this still a valid issue using latest Flutter version or has this been resolved ?

**Comment by mesb1** [comment]
> @mesb1
> Is this still a valid issue using latest Flutter version or has this been resolved ?

Hi, yes it is:
Last time it was checked at 19 november 2020, with latest flutter available for that date.
If there was some changes related I can check it once more.

**Comment by mesb1** [comment]
Here you may find lots of other devices mentioned with same gpu that I met with that problem.
https://github.com/flutter/flutter/issues/71315

**Comment by mesb1** [comment]
Looks like fix is included starting from 2.3.0 24pre.

**Comment by mesb1** [comment]
Stable flutter release 2.5.0 included fix for PowerVR GPU devices.
My own devices is now working fine.
