### ISSUE TITLE
Image.asset sometimes display weird

### ISSUE THREAD

**Issue by Liashui** [flutter/flutter#31744]
My ios application presents a flutter page which has serveral Images. these Images sometimes display correct,sometimes display weird

code snippets
pubsec.yaml
```
flutter:
  assets:
  - assets/images/
``` 
about.dart
```
Container(
    child: Image.asset(
         'assets/images/wm_about_logo_icon.png',
          height: 40,
      ),
     margin: EdgeInsets.only(top: 36),
),
```
images folder sructures 
![](https://upload-images.jianshu.io/upload_images/7140351-8b4b07b996890194.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/500)

display snapshoot
![](https://upload-images.jianshu.io/upload_images/7140351-40041984c76d7d2d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/500)

**Comment by BaderEddineOuaich** [comment]
Try to refer to the image with the exact full path in pubspac.yaml like the following:
>flutter:
>  assets:
> \- assets/images/wm_about_logo_icon.png

**Comment by daniilguit** [comment]
Try 
```
flutter channel dev
flutter version 1.4.19
```

This maybe bug related to images on iOS that was broken in 1.2

**Comment by Liashui** [comment]
> Try to refer to the image with the exact full path in pubspac.yaml like the following:
> 
> > flutter:
> > assets:
> > - assets/images/wm_about_logo_icon.png
i set the fulll path in pubspac.yaml before,the problem still exsit

**Comment by Liashui** [comment]
> Try to refer to the image with the exact full path in pubspac.yaml like the following:
> 
> > flutter:
> > assets:
> > - assets/images/wm_about_logo_icon.png

i set the fulll path in pubspac.yaml before,the problem still exsits

**Comment by Liashui** [comment]
> Try
> 
> ```
> flutter channel dev
> flutter version 1.4.19
> ```
> 
> This maybe bug related to images on iOS that was broken in 1.2

My flutter version: 
flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (2 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

I will try version 1.4.19 later,thanks for your reply

**Comment by Liashui** [comment]
> Try to refer to the image with the exact full path in pubspac.yaml like the following:
> 
> > flutter:
> > assets:
> > - assets/images/wm_about_logo_icon.png

I set the fulll path in pubspac.yaml before,the problem still exsits

**Comment by Liashui** [comment]
> > Try
> > ```
> > flutter channel dev
> > flutter version 1.4.19
> > ```
> > 
> > 
> > This maybe bug related to images on iOS that was broken in 1.2
> 
> My flutter version:
> flutter --version
> Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision [8661d8a](https://github.com/flutter/flutter/commit/8661d8aecd626f7f57ccbcb735553edc05a2e713) (2 months ago) • 2019-02-14 19:19:53 -0800
> Engine • revision [3757390](https://github.com/flutter/flutter/commit/3757390fa4b00d2d261bfdf5182d2e87c9113ff9)
> Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> I will try version 1.4.19 later,thanks for your reply



> iOS

flutter 1.5.8 is ok
