### ISSUE TITLE
Support interactive scrollbars

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter#31753]
On desktop platforms, provide support for interactive scrollbars.

This is needed to rewrite the devtools inspector in Flutter as the scrollbars are important to make the large amount of content shown more navigable.
https://flutter.github.io/devtools/inspector

For my use case, making the scrollbars match a specific platform's scrollbar look and feel is not critical.

**Comment by jonahwilliams** [comment]
Interestingly we do have https://docs.flutter.io/flutter/material/Scrollbar-class.html, though I've never seen them IRL

**Comment by stuartmorgan** [comment]
They aren't interactive though (i.e., you can't click and drag on the scroll thumb to scroll), unless that's changed recently; they are feedback-only.

**Comment by AppleEducate** [comment]
Maybe something like this?

https://medium.com/flutter-community/creating-draggable-scrollbar-in-flutter-a0ae8cf3143b

**Comment by stuartmorgan** [comment]
See also ##35829, and discussion of its applicability to desktop in the bug above.

**Comment by PsychoXIVI** [comment]
Any progress on that? I am looking forward using Flutter Web for actual commercial application (website).

**Comment by softmarshmallow** [comment]
yeah it seems quite simple job, need official update on this.

**Comment by jacob314** [comment]
It would be great to have an estimate of when this will be able in Flutter so we can plan whether we can wait for the official support or need to write our own custom scrollbars for https://github.com/flutter/devtools

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/36412, https://github.com/flutter/flutter/issues/44840

**Comment by cad0p** [comment]
Waiting for it!

**Comment by KyleKun** [comment]
Any progress on that?😄

**Comment by Piinks** [comment]
Consolidating into https://github.com/flutter/flutter/issues/70866

**Comment by ImDeZz** [comment]
For those of you who want to have a generic draggable scrollbar on the desktop web browser, I have created a scrollbar. It behaves like the generic desktop browser one.
https://hobbister.com/2020/11/24/flutter-web-scrollbar-with-generic-desktop-feel/

**Comment by romathebest** [comment]
> 
> 
> For those of you who want to have a generic draggable scrollbar on the desktop web browser, I have created a scrollbar. It behaves like the generic desktop browser one.
> https://hobbister.com/2020/11/24/flutter-web-scrollbar-with-generic-desktop-feel/

Thanks, looks very nice! Can you please also add the horizontal scrolling?

**Comment by deviant-studio** [comment]
any news on that? the flutter for web is now officially stable. second major version and no scrollbar support?

**Comment by Piinks** [comment]
> any news on that? the flutter for web is now officially stable. second major version and no scrollbar support?

@deviant-studio interactive scrollbars are already available on the stable channel.
