### ISSUE TITLE
[Feature Request / Doc Enhancement] Assets

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#31756]
There seems to be many questions (for me too) regarding the areas of assets. 
It would nice if:
1. One could see the available resources that are currently loaded in the app. That is, one could run it a line before attempting to load the key to see the available resource, and understand better what is loaded and what is not. If there is such a way, I couldn't find it.
Code example:
`
final assetBundle = DefaultAssetBundle.of(context);
final existingAssets = assetBundle.getLoadedAssets(); // feature request
final content = assetBundle.loadString("assets/dataFile.json"); // this line will throw "Unable to load asset assets/dataFile.json"
`

2. Another way, other than 1 above, to debug problematic assets. Personally, I'm just trying to play around with the .yaml and crossing my fingers. Would be nice to have an actual way of checking things, even if just for android/ios.

3. I can't find any clear conclusion on how sub directories work in flutter. I know flutter will look for the same asset in sub directories, but what about specifying a root directory in the .yaml file, while having sub directories and different assets in them (separated into categories)? e.g.
Actual file tree:
```
/assets
  - /images/image1.jpg
  - /images/image2.png
  - /data/data1.json
  - /data/data2.json
  - /data/data3.xml
  - /data/nested/data5.txt
```

yaml:
```
assets:
  - assets/
```
Is flutter going to load all assets?

**Comment by andrewkolos** [comment]
Closing this primarily because this is stale.

> 1. One could see the available resources that are currently loaded in the app. That is, one could run it a line before attempting to load the key to see the available resource, and understand better what is loaded and what is not. If there is such a way, I couldn't find it.
>    Code example:
>    `final assetBundle = DefaultAssetBundle.of(context); final existingAssets = assetBundle.getLoadedAssets(); // feature request final content = assetBundle.loadString("assets/dataFile.json"); // this line will throw "Unable to load asset assets/dataFile.json"`

The [AssetManifest](https://api.flutter.dev/flutter/services/AssetManifest-class.html) API has since been added to address this.

> 3\. I can't find any clear conclusion on how sub directories work in flutter. I know flutter will look for the same asset in sub directories, but what about specifying a root directory in the .yaml file, while having sub directories and different assets in them (separated into categories)? e.g.

I think the behavior is documented well-enough. From [Adding assets and images](https://docs.flutter.dev/ui/assets/assets-and-images):

> Note: Only files located directly in the directory are included. [Resolution-aware asset image variants](https://docs.flutter.dev/ui/assets/assets-and-images#resolution-aware) are the only exception. To add files located in subdirectories, create an entry per directory.
