### ISSUE TITLE
image_picker doesn't provide metadata for the image selected on IOS

### ISSUE THREAD

**Issue by Quanalogy** [flutter/flutter#31751]
Hi,

It seems like the image picker for ios does not provide the correct image metadata when picking an image. When I use the plugin on android, it is possible to read the metadata from the image, providing latitude and longitude coordinates of the image. When using the same code and the same image on IOS, the image is displayed correctly but no metadata or sparse meta data (5 elements of around 50) is returned.

The following code is used for reproducing this:

```
import 'package:exif/exif.dart';
import 'package:image_picker/image_picker.dart';

...

var userImage = await ImagePicker.pickImage(source: ImageSource.gallery);
var bytes = await userImage.readAsBytes();
var tags = await readExifFromBytes(bytes);
    
tags.forEach((key, value) => print("$key : $value"));
```

which on ios provide:

```
2019-04-28 18:38:56.034770+0200 Runner[56038:217320] flutter: Image Orientation : Horizontal (normal)
2019-04-28 18:38:56.034948+0200 Runner[56038:217320] flutter: Image ExifOffset : 38
2019-04-28 18:38:56.035105+0200 Runner[56038:217320] flutter: EXIF ColorSpace : sRGB
2019-04-28 18:38:56.035271+0200 Runner[56038:217320] flutter: EXIF ExifImageWidth : 4608
2019-04-28 18:38:56.035462+0200 Runner[56038:217320] flutter: EXIF ExifImageLength : 3456
```

while on android provide the following keys (along with many others):

```
static const String latKey = "GPS GPSLatitude";
static const String lngKey = "GPS GPSLongitude";
static const String latRefKey = "GPS GPSLatitudeRef";
static const String lngRefKey = "GPS GPSLongitudeRef";
```

The image used:

![IMG_20190419_150626](https://user-images.githubusercontent.com/6534708/56867422-4d7d5f00-69e5-11e9-8cfe-1b14dfecd7f5.jpg)

The image have been tested both on ios simulator (XR) and a physical phone, 6s I think, with the same result. The image have been validated both in photos app on IOS device, where the location can be displayed (by displaying the photo in photos app and swiping from buttom to top, showing "places", which displays where the image was taken), and on website: http://metapicz.com/#landing

So it seems to me that the image provided is stripped for its metadata, or at least some of it. Hope you can help resolving this issue.

**Comment by Quanalogy** [comment]
Flutter doctor:

```
/Users/develop/Downloads/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale da-DK)
    • Flutter version 1.2.1 at /Users/develop/Downloads/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/develop/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • iPhone Xʀ       • 2CC5290E-989E-404D-8FE2-B4E7BBEA0C50     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by cyanglaz** [comment]
I am working on the fixes. https://github.com/flutter/plugins/pull/1586 is the first step which copies the exif over to the new image. And I will create another PR to copy the GPS over when this PR merges in.

**Comment by cyanglaz** [comment]
Should be fixed in https://github.com/flutter/plugins/pull/1617
I am closing the issue. If any related issues are found, please feel free to open another issue with details.

**Comment by Ihawesome99** [comment]
bro,can u pls give source code or link for get gps loc with upload picture,pls bro, i really appreciate it
