### ISSUE TITLE
Flutter crash fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by gorkovv** [flutter/flutter#31767]
gorkov@gorkov:~$ flutter
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 509a026338fb566f)
Crash report written to /home/gorkov/flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.
[flutter_05.log](https://github.com/flutter/flutter/files/3125871/flutter_05.log)

**Comment by jonahwilliams** [comment]
@kib1org what is the output of `git --version`? Also what operating system + shell are you using?

**Comment by kib1org** [comment]
gorkov@gorkov:~$ git --version
git version 2.7.4
gorkov@gorkov:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by christopherfujino** [comment]
@gorkovv are you still in this state?

It seems to me like the git repo in your flutter install is corrupted (when you issue the `flutter` command, it issues the command `git rev-parse HEAD`, which should work in a valid git repository). Can you paste the output of `git status` and `git rev-parse HEAD` in your flutter install?

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
