### ISSUE TITLE
Typo in pubspec.yaml fonts leads to TypeError instead of helpful error message.

### ISSUE THREAD

**Issue by aidenpierce2** [flutter/flutter#31764]
I can't run my app on my device,when i click the run button, there was no gradle build info tips. and 
no error on my terminal,but only some info in my logs, floowing is the log 

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=GSL0216A23005048 lib\main.dart

## exception

_TypeError: type 'YamlMap' is not a subtype of type 'Iterable<dynamic>'

```
#0      _validateFonts (package:flutter_tools/src/flutter_manifest.dart:409:47)
#1      _validateFlutter (package:flutter_tools/src/flutter_manifest.dart:354:9)
#2      _validate (package:flutter_tools/src/flutter_manifest.dart:312:9)
<asynchronous suspension>
#3      FlutterManifest._createFromYaml (package:flutter_tools/src/flutter_manifest.dart:45:40)
<asynchronous suspension>
#4      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:40:12)
<asynchronous suspension>
#5      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:34:12)
<asynchronous suspension>
#6      FlutterProject._readManifest (package:flutter_tools/src/project.dart:144:60)
<asynchronous suspension>
#7      FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:44:44)
<asynchronous suspension>
#8      FlutterProject.current (package:flutter_tools/src/project.dart:55:46)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:542:59)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:489:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:480:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:111:11)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:51:10)
#40     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#41     main (file:///D:/FlutterSdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.4.9-hotfix.1 at D:\FlutterSdk\flutter
    • Framework revision 88fa7ea403 (2 weeks ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.1 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\dell\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • FRD AL10 • GSL0216A23005048 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by jonahwilliams** [comment]
Can you post your pubspec.yaml? it looks like a format error is triggering a type error (which we should catch anyway)

**Comment by aidenpierce2** [comment]
yeah, of course ,firstly, i check my pubspec.yaml and repair some error, so there is no red alert in my pubspec.file, but my project still report the same error. and  i'm sure my environment is correctly, because when i run demo app,it's normal.
 pubspec.yaml:


name: flutter01
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.1
  json_annotation: ^2.0.0
  flutter_redux: ^0.5.3
  device_info: ^0.4.0+1
  connectivity: ^0.4.2
  url_launcher: ^5.0.1
  flutter_markdown: ^0.2.0
  share: ^0.6.0+1
  flutter_spinkit: ^3.1.0
  flutter_webview_plugin: ^0.2.1+2
  sqflite: ^1.1.1
  pub_semver: ^1.4.2
  flutter_statusbar: ^0.0.1
  flutter_svg: ^0.11.0+1
  photo_view: ^0.2.1
  flutter_slidable: ^0.4.9
  dio: ^2.0.15
  flutter_localizations:
    sdk: flutter
  event_bus:  ^1.0.3
  flutter_cache_manager: ^0.3.1
  path_provider: ^0.5.0+1
  permission_handler: 3.0.0
  scoped_model: ^1.0.1
  package_info: ^0.4.0+1
  rxdart: ^0.21.0
  android_intent: ^0.3.0
  test: ^1.5.1

dev_dependencies:
  build_runner: ^1.2.8
  json_serializable: ^2.0.0
#  flutter_test:
#    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/logo.png
    - static/images/default_img.png
    - static/images/welcome.png
  fonts:
    - family: buttomIconStyle
      fonts:
        -asset: static/font/iconfont.ttf




------------------ 原始邮件 ------------------
发件人: "Jonah Williams"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 上午10:33
收件人: "flutter/flutter"<flutter@noreply.github.com>; 
抄送: "782653219"<782653219@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [flutter/flutter] I can't install my app  (#31764)




Can you post your pubspec.yaml? it looks like a format error is triggering a type error (which we should catch anyway)

**Comment by aidenpierce2** [comment]
that's is my new log





------------------ 原始邮件 ------------------
发件人: "Jonah Williams"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 上午10:33
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "782653219"<782653219@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [flutter/flutter] I can't install my app  (#31764)




Can you post your pubspec.yaml? it looks like a format error is triggering a type error (which we should catch anyway)

**Comment by jonahwilliams** [comment]
This line:

> -asset: static/font/iconfont.ttf

Should be:

> \- asset: static/font/iconfont.ttf

**Comment by aidenpierce2** [comment]
oh, it worked,thank you!




------------------ 原始邮件 ------------------
发件人: "Jonah Williams"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 中午11:24
收件人: "flutter/flutter"<flutter@noreply.github.com>; 
抄送: "782653219"<782653219@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [flutter/flutter] I can't install my app  (#31764)




This line:
  
-asset: static/font/iconfont.ttf
  
Should be:
  
- asset: static/font/iconfont.ttf

**Comment by jonahwilliams** [comment]
Yay, I will repurpose this bug so we can add a better error message to the tool

**Comment by aidenpierce2** [comment]
thanks,I‘m look forward a better flutter tool
happy weekend.




------------------ 原始邮件 ------------------
发件人: "Jonah Williams"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 中午11:37
收件人: "flutter/flutter"<flutter@noreply.github.com>; 
抄送: "782653219"<782653219@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [flutter/flutter] I can't install my app  (#31764)




Yay, I will repurpose this bug so we can add a better error message to the tool

**Comment by jonahwilliams** [comment]
The bug is that on package:flutter_tools/src/flutter_manifest.dart:409:47 we do an unsafe cast from Object/dynamic to Iterable<dynamic>. We should perform an `is` check first and throw an error message instead.
