### ISSUE TITLE
Migrate FlutterActivity and FlutterFragment to androidX?

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#31772]
Hello,

Since the plugins have already migrated to AndroidX, is-there a reason why the `FlutterActivity` and `FlutterFragment` are still using the support library?

Should I open a PR for this migration?

**Comment by athornz** [comment]
I've got a PR open that adds AndroidX support. Try out the branch and see if there are any issues.

https://github.com/flutter/flutter/pull/31028

**Comment by BondarenkoStas** [comment]
Thank you @athornz ! The PR was merged to 1.7.1, so I think it's safe to close the issue. @g123k please report, if you still experience the problem I will re-open it right away.
