### ISSUE TITLE
Use Chinese character make [TextPainter.layout()] cost long time on Android devices

### ISSUE THREAD

**Issue by wilfordw** [flutter/flutter#31774]
When I run the code below on Android devices, `TextPainter.layout()` function cost much more time when I use Chinese title than English ones.

Any friends can tell what cost it? and how can I deal with it?

## Codes

```dart
testPainterLayout() {
    var _clock = Clock();
    _clock.start();
    TextPainter textPainter = TextPainter(textDirection: TextDirection.ltr);
    print("TextPainter() cost ${_clock.stop()}ms");
    _clock.start();
    textPainter.text = TextSpan(text: """
    \n都说人不中二枉少年。\n每个人或多或少都经历过那个时期，...
    """, style: TextStyle(fontSize: 20));
    print("textPainter.text cost ${_clock.stop()}ms");
    _clock.start();
    textPainter.layout(maxWidth: 200);
    print("textPainter.layout cost ${_clock.stop()}ms");
}
```

```dart
@override
Widget build(BuildContext context) {
return Scaffold(
  appBar: AppBar(
    title: Text("为什么那么慢"),
    //title: Text("so fast"),
  ),
  floatingActionButton: FloatingActionButton(
    onPressed: () {
        testPainterLayout();
    },)
  );
}
```

## Logs

when use English title

```
I/flutter (32202): TextPainter() cost 0ms
I/flutter (32202): textPainter.text cost 3ms
I/flutter (32202): textPainter.layout cost 74ms
```

when use Chinese title

```
I/flutter (20918): TextPainter() cost 0ms
I/flutter (20918): textPainter.text cost 0ms
I/flutter (20918): textPainter.layout cost 1610ms
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-CN)
    • Flutter version 1.2.1 at /Users/wangji/development/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wangji/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by HansMuller** [comment]
CC @GaryQian

**Comment by GaryQian** [comment]
Hmm, using chinese vs non-chinese should not be making a noticeable difference in layout times, I can look through our LibTxt benchmarks and see if I can reproduce there.

**Comment by GaryQian** [comment]
Actually, your english layout time looks a few orders of magnitude too slow as well (not as bad as 1610ms though) Layout for simple runs like that should be happening in the sub-2ms range.

I see you only have an emulator connected. Are you running this on an actual device or on an emulator? Emulators have very different performance characteristics than devices and I would expect to see a vastly slower performance compared to a real device. If your emulator is emulating the device RAM on disk due to shortage of real RAM, it may be accessing disk to load chinese fonts as chinese fonts are much larger.

In any case, can you please re-run this on a physical device and report back?

**Comment by jason-simmons** [comment]
If you run the layout multiple times, then do the slow results for Chinese text happen only on the first layout?  Or does it happen for every run of layout?

If the default font does not include Chinese characters, then the first run of layout will need to search for a font that includes the requested characters.  The results of the search will be cached, so later runs should be faster.

You can avoid the font lookup by specifying a `fontFamily` (or `fontFamilyFallback`) in the `TextStyle` that has the right characters.

**Comment by wilfordw** [comment]
@jason-simmons @GaryQian thx for response.
I test the example on my XIAOMI real device. and the characters to layout is much more longer (about 4000 characters). @GaryQian , then layout time made noticeable deference between chinese and non-chinese
the slow results only on the first layout. I guess you a right, @jason-simmons . the problem was on fontFamily. I will specify the fontFamily and try again.
I will more test and run it on profile mode and report later

**Comment by wilfordw** [comment]
add my custom font in `pubspec.yaml`

```
  fonts:
    - family: HaiBao
      fonts:
        - asset: fonts/DFPHaiBaoW12-GB.ttf
```
and specify my font, resolve my problem

```
 textPainter.text = TextSpan(text: text, style: TextStyle(fontSize: 20, fontFamily: "HaiBao"));
 textPainter.layout(maxWidth: 200);
```

thanks for help @jason-simmons @GaryQian
