### ISSUE TITLE
image picker - fixing some bugs, new features

### ISSUE THREAD

**Issue by diver2** [flutter/flutter#31775]
Hi all,
  As I've said in another issue related to image_picker, I'm not used to open source processes. But willing to contribute.
  My folder: https://github.com/diver2/plugins/tree/master/packages/image_picker
  I've made fixes on image_picker, as below:
a) I changed it to return the image in a UInt8List type. Why? Because when writing temp files, in some android versions the system creates copies of those files in the gallery. In Samsung S6, I would see the scaled duplicates in the gallery. Worst of all, to the lay user, he would not know which one was the scaled just looking at the thumbnail, and could later delete the original. When I pass memory objects from the image picker, this does not happen. I changed this in Andorid / IOS.
b) IOS: I had issues that some times (really f*ing random, tried a lot but can't determine the why. It happens sparingly (~1/10), but happens), the image picker will return null when getting picture of gallery BUT won't close the picking (won't pop view) So, for the user, he clicks in a picture, nothing happens. He thinks that he did not press strong enough. He clicks again. Image picker had already returned null. But had not performed the pop. So, it does now, and pops twice, and your user thinks something crashed.
So what I changed was that if image picker returns null it means that this was an error... if you cancelled, it returns the string "cancelled".
So, in dart, you need to create a while 

  ```dart
while (img == null || i == 1) {
      //print ("PASS $i");
      img = await camera.openImagePicker(context, sizeOfPhoto);
}
if (img == "cancelled")
  { //do something cause the user cancelled}
else
  { //you got your UInt8List img }
```
And then I leave to the user to decide what to do with the image (Uint8).
If this is a camera image, you save it to the phone, to the gallery. The original, I mean. The scaled, flutter uses decides what to do with it.
My folder: https://github.com/diver2/plugins/tree/master/packages/image_picker
Pls, contact me if anything (I receive notifs via github and check often)
What I wish is to learn open source contribution process, so I can do it later on my own.
And I know that my modifs to image_picker are now a breaking change, so I would be happy changing them to new features (eg, adding them to new functions, so user can choose if they want a file or an UInt8 type). But I don't know how you guys who control code think, so I won't put up the work if it means zero to the community.
Also, I know dart, C++, not really Java/Obj. C, specially not Android/IOS. So, if there are not awesome ways of coding, it is because of that. But code works as of my means of testing. And I'm more than happy if anyone points errors. 
Cheers
@cyanglaz @zoechi

**Comment by cyanglaz** [comment]
@diver2 Thank you so much for pointing these out. I am also currently thinking about it and planning an update to solve these issues in a public API change. I agree with you that programmers should be able to choose to save the image or not(both cropped or taken with camera). Only returning a `UInt8List` might not be too obvious for some programmers who are not familiar with the data type.

**Comment by diver2** [comment]
@cyanglaz well, tell me if I can be of any help. And of course feel free to copy code from my repository

**Comment by chunhunghan** [comment]
I have similar request not to save photo on disk for security reason.
Thank you for your amazing work.

**Comment by chunhunghan** [comment]
@cyanglaz  Will this function "choose to save the image or not" be supported after CameraX ready? Thanks.

**Comment by chunhunghan** [comment]
I can accept UInt8List or MemoryImage(UInt8List), just do not save it to disk. Thanks

**Comment by pedromassangocode** [comment]
Hi @diver2 
While this is a very helpful issue I think it points to too many problems in the `image_picker` plugin. Can you please elaborate what this issue is about?

It will be better if you could split into two or more separated issues as in Flutter we don't track more than one issue in the same place.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
