### ISSUE TITLE
Getting rid of version numbers on imports

### ISSUE THREAD

**Issue by nsmith1024** [flutter/flutter#31789]
## Use case

ALL

## Proposal

Moving towards getting rid of version numbers on import packages, or some solution related to that.

One time consuming part of development for android was sorting out all the different version numbers for the various packages, some package version dont work with other package versions, some dont work with some API versions and build targets, it seems like an infinite multidimensional matrix of packages and versions and API incompatibilities.

When developing with C#, it was such a breath of fresh air, you just grabbed the latest version of some random package and it just worked, i had zero issues related to one version of a package not working with another unrelated package. 

With flutter seems to have issues related to incompatible package versions. Its possible to waste hours just trying to figure out which version of a package works with another.

Shouldn't we just be able to just use the latest version of a particular package, and that should just work instead of trying to figure out which of a 3 decimal package version works with another 3 decimal package version number of a different package?

Maybe there should be some system, or AI, or database, that knows which version works with some other package version and just gets those versions automatically (based on user feedback i guess), so you can just specify the names of the imports you want and the "system" will fetch the correct versions that work with each other? I dont exactly know how c# does it, but i had zero issues with package versions with C#.

For example simple old school C language, you just do "include stdio.h" and off you go, there is no need to do include "stdio1.4.2.h" or include "stdio^4.3.5.4.h" or something like that, and then wonder if version "stdio.3.4.3+.h" will work with version "string.65.33.2.5.h"  or "memory.3.2.5.h" not to mention the incompatibility with the 10 other includes you are using.

**Comment by apaatsio** [comment]
You can set the version for all packages in pubspec.yaml to `any` and it will automagically find the newest compatible versions.

See also [Resolving Dart package version conflicts, faster than ever](https://iirokrankka.com/2018/08/28/resolving-dart-package-version-conflicts/)

**Comment by goderbauer** [comment]
As per previous comment, this already exists by just setting the version to `any`.
