### ISSUE TITLE
how to modify the drawer shadow?

### ISSUE THREAD

**Issue by zxhwyp** [flutter/flutter#31787]
![e79d65d2-a302-4da1-95e4-0114c56dedce](https://user-images.githubusercontent.com/19204015/56896359-16c74780-6abe-11e9-9b0f-c6967740a140.png)

**Comment by HansMuller** [comment]
The drawer's shadow is defined by its [`elevation`](https://docs.flutter.io/flutter/material/Drawer/elevation.html).  Are you trying to change the size of the drawer's shadow or its color or the color of the "scrim" that appears behind the drawer ...?

**Comment by zxhwyp** [comment]
I want to make the widget behind the drawer show more clear and i have set the elevation to 0.

**Comment by HansMuller** [comment]
If you really want widgets "behind the drawer" to be partially visible, you'd need to make the Drawer translucent. However if what you're referring to are widget's behind the drawer's "scrim" - which would be the gray bar on the left of the screenshot you provided - then you'd need to a way to specify the scrim's color. There's a PR for that being worked on now: https://github.com/flutter/flutter/pull/31025

**Comment by zxhwyp** [comment]
get, thanks.

**Comment by frederickcxa** [comment]
@HansMuller #31025 is already merged, should this be closed?

**Comment by zxhwyp** [comment]
yes, thanks
