### ISSUE TITLE
platformexception(error performing get, failed to get document because the client is offline., null)

### ISSUE THREAD

**Issue by parthvora25** [flutter/flutter#31783]
platformexception(error performing get, failed to get document because the client is offline., null)

i am using this function
FirebaseDatabase()
        .users
        .document(firebaseUser.uid)
        .get()
        .then((onDataSnap) {
      print(onDataSnap);
    });

The get function gives the above error. My internet is working fine. No issues with any other plugins or versions related to this. Dont know how to solve this error.

firebase logs from flutter app:

W/BiChannelGoogleApi(25403): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@aff8d7b
D/FirebaseAuth(25403): Notifying id token listeners about user ( SlTALuXzfRMS8VSdJHXu3ISVWZz2 ).
D/FirebaseApp(25403): Notifying auth state listeners.
D/FirebaseAuth(25403): Notifying auth state listeners about user ( SlTALuXzfRMS8VSdJHXu3ISVWZz2 ).
D/FirebaseApp(25403): Notified 1 auth state listeners.
W/DynamiteModule(25403): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(25403): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(25403): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
V/NativeCrypto(25403): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
I/ProviderInstaller(25403): Installed default security provider GmsCore_OpenSSL
W/art     (25403): Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
W/art     (25403): Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
W/art     (25403): Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
W/Firestore(25403): (18.2.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=NOT_FOUND, description=The project KineApp-4a340 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=KineApp-4a340 to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled., cause=null}
W/Firestore(25403): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
I/flutter (25403): Hight of the screen =======>  592.0

**Comment by wilhuff** [comment]
There are a few things going on here.

First, the code snippet you posted uses `FirebaseDatabase`, but your logs are from Firestore. I don't think that's the right snippet.

In any case, the real issue is right there in the output:

> The project KineApp-4a340 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=KineApp-4a340 to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.

In short, the project you're using doesn't have a Firestore instance associated with it. You need to create one in the console before the SDKs will work.

**Comment by collinjackson** [comment]
Thanks for the help resolving this issue @wilhuff. I think this issue is resolved but if I'm mistaken let me know.

**Comment by parthvora25** [comment]
> There are a few things going on here.
> 
> First, the code snippet you posted uses `FirebaseDatabase`, but your logs are from Firestore. I don't think that's the right snippet.
> 
> In any case, the real issue is right there in the output:
> 
> > The project KineApp-4a340 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=KineApp-4a340 to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.
> 
> In short, the project you're using doesn't have a Firestore instance associated with it. You need to create one in the console before the SDKs will work.

Thanks for the help. It is working now.
