### ISSUE TITLE
ListView.separated returns wrong semanticChildCount

### ISSUE THREAD

**Issue by saprvade** [flutter/flutter#31781]
## Steps to Reproduce

`ListView.separated` calculates the `semanticChildCount` incorrectly. I have 4 items in my `ListView` but the `semanticChildCount` says there are 7. This leads to the incorrect accessibility label - Talkback says "button in a list of 7 items" while there are only 4 on the screen.

I can see this in the scroll_view.dart implementation, which makes no sense to me:
  ```
// Helper method to compute the semantic child count for the separated constructor.
  static int _computeSemanticChildCount(int itemCount) {
    return math.max(0, itemCount * 2 - 1);
  }
```

As a separator I use a simple `const SizedBox(width: 32.0)` widget which should not be considered as an item of course.

**Comment by SugyoIn-LBSTech** [comment]
My solution.

```dart
ListView.custom(
  childrenDelegate: SliverChildBuilderDelegate(
    (_, index) {
      if (index.isEven) {
        return children[index ~/ 2];
      } else {
        return SizedBox(height: 16);
      }
    },
    childCount: math.max(0, children.length * 2 - 1),
    semanticIndexCallback: (_, index) => index.isEven ? index ~/ 2 : null,
  ),
  semanticChildCount: children.length,
);
```
