### ISSUE TITLE
question：'package:flutter/src/widegets/text.dart':failed assertion:line 235 pos 15 : 'data ! = NULL ' : is not true code：

### ISSUE THREAD

**Issue by sarahalramly** [flutter/flutter#31785]
body: Container(
     child: FutureBuilder(
       future: _getQu(),
       builder: (BuildContext context, AsyncSnapshot snapshot){
         if (snapshot.data == null){
           return Container(
          child: Center(
            child: Text(" تحميل البينات........"),
          ),
           );
         }Dn.jpg

**Comment by sarahalramly** [comment]
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:http/http.dart' as http;
import 'dart:convert';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "الواجهه الرئيسية",
      debugShowCheckedModeBanner: false,
      theme: new ThemeData(
        primarySwatch: Colors.green[700]
      ),
      home: new MyhomePage(title: 'الاسئلة'),
    );
  }
  }
  class MyhomePage extends StatefulWidget  {
    MyhomePage({Key key , this.title}):super(key:key);
    final String title;
    @override
    _MyhomePageState createState()=> _MyhomePageState();

  }
  class _MyhomePageState extends State<MyhomePage> {
    var stringData = "";
    Future <List<Qu>> _getQu() async{
   var data= await http.get("http://www.json-generator.com/api/json/get/cfwZmvEBbc?indent=2");
   var jsonData =json.decode(data.body);

    stringData =jsonData;

   List<Qu> qu =[];
   for(var u in jsonData){
     Qu qur = Qu(u["questions"],u["ansar"]);
     qu.add(qur);
   }
   print(qu.length);
   return qu;

    }
    @override
   Widget build(BuildContext context){
     return new Scaffold(
       appBar: new AppBar(
         title: new Text(widget.title),
       ),
       body: Container(
         child: FutureBuilder(
           future: _getQu(),
           builder: (BuildContext context, AsyncSnapshot snapshot){
             
             if (stringData == null){
               return Container(
             child: Center(
                child: Text(" تحميل البينات........" ,  textDirection: TextDirection.rtl,),
              ),
               );
            } else{
             return ListView.builder(
               itemCount: snapshot.data.length,
               itemBuilder: (BuildContext context, int index){
                 return ListTile(
                
                 title: Text(snapshot.data[index].questions),
                 );
               },
             ); 
            }
           },
         ),
       ),
     );
   }
    
  }
  class Qu {
    final String questions;
    final bool ansar;
    Qu(this.questions, this.ansar);
  
  }

**Comment by BaderEddineOuaich** [comment]
`` FutureBuilder<List>
              (
              future: _getBookList(),
              builder: (context, snapshot)
              {
                if (snapshot.hasData)
                {
                  return ListView.builder(
                itemCount: snapshot.data.length,
                itemBuilder: (BuildContext context, int index){
                return ListTile(
                 title: Text(snapshot.data[index].questions),
               );
              },
             ); 
                }
                else if (snapshot.hasError)
                {
                  return Text("${snapshot.error}");
                }
                // By default, show a loading spinner
                return CircularProgressIndicator();
              },
            )
``

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
