### ISSUE TITLE
InputChip delete button is misaligned

### ISSUE THREAD

**Issue by bobatsar** [flutter/flutter#31790]
## Steps to Reproduce

When using e.g. InputChips with onDeleted, the Delete icon is placed outside the chip if the text width is larger than the allowed width for the chip.

![Screenshot_20190429-145705](https://user-images.githubusercontent.com/7723101/56897734-938efd00-6a8f-11e9-911a-14d9d60fffd5.png)

```dart
import 'package:flutter/material.dart';

void main() {
  return runApp(TestChips());
}

class TestChips extends StatelessWidget {
  final String lorem =
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam "
      "nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, "
      "sed diam voluptua. At vero eos et accusam et justo duo dolores et ea "
      "rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem "
      "ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing "
      "elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna "
      "aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo "
      "dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus "
      "est Lorem ipsum dolor sit amet.";

  @override
  Widget build(BuildContext context) {
    List<Widget> chips = [];

    for (var i = 0; i < 12; i++) {
      chips.add(InputChip(
        label: Text(lorem.substring(0, i * 2)),
        onDeleted: () => print("delete"),
      ));
    }

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test Chips"),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            width: 150,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: chips,
            ),
          ),
        ),
      ),
    );
  }
}
```

## Logs

```
flutter analyze
No issues found! (ran in 3.3s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale de_DE.utf8)
    • Flutter version 1.2.1 at /home/xxx/dev_tools/flutter
    • Framework revision 8661d8aecd (vor 2 Monaten), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/xxx/dev_tools/android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/xxx/dev_tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/xxx/dev_tools/android-studio
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • HTC U11 life • HT7AY1C00279 • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by BaderEddineOuaich** [comment]
The problem sounds to be the container's width. works perfectly without specifying the width. even more better with scroll view.
<pre>import 'package:flutter/material.dart';

void main() {
  return runApp(TestChips());
}

class TestChips extends StatelessWidget {
  final String lorem =
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam "
      "nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, "
      "sed diam voluptua. At vero eos et accusam et justo duo dolores et ea "
      "rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem "
      "ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing "
      "elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna "
      "aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo "
      "dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus "
      "est Lorem ipsum dolor sit amet.";

  @override
  Widget build(BuildContext context) {
    List<Widget> chips = [];

    for (var i = 0; i < 50; i++) {
      chips.add(InputChip(
        label: Text(lorem.substring(0, i * 2)),
        onDeleted: () => print("delete"),
      ));
    }

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test Chips"),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SingleChildScrollView(
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Container(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: chips,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
</pre>

**Comment by BaderEddineOuaich** [comment]
The problem sounds to be the container's width preventing the chip from expanding. works perfectly without specifying the width. even more better with scroll view.

<pre>
import 'package:flutter/material.dart';

void main() {
  return runApp(TestChips());
}

class TestChips extends StatelessWidget {
  final String lorem =
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam "
      "nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, "
      "sed diam voluptua. At vero eos et accusam et justo duo dolores et ea "
      "rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem "
      "ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing "
      "elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna "
      "aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo "
      "dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus "
      "est Lorem ipsum dolor sit amet.";

  @override
  Widget build(BuildContext context) {
    List chips = [];

    for (var i = 0; i < 50; i++) {
      chips.add(InputChip(
        label: Text(lorem.substring(0, i * 2)),
        onDeleted: () => print("delete"),
      ));
    }

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test Chips"),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SingleChildScrollView(
            child: SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Container(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: chips,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
</pre>

**Comment by bobatsar** [comment]
@BaderEddineOuaich , for sure it's the width of the container. But that is only here to demonstrate the unwanted behaviour. The chips seem to handle the width constraint correctly by limiting the width and fading the text out, but the icon is placed outside.

I use the chips in a dialog where the width is limited.

**Comment by shihaohong** [comment]
I believe I've currently found a fix, I just need to add tests to ensure that this does not regress in the future. Thanks for sharing additional context, it was very helpful in diagnosing the problem and coming up with a solution!
