### ISSUE TITLE
Note 8 bottom padding issues!

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#31791]
Does anyone has solution for bottom padding issue on Galaxy Note 8?

The device has a soft bottom navigation button. Most user selects an option to hide the bottom navigation. 

My app works for all devices except Note 8. If the user chooses not to hide the Note 8 bottom navigation button, my app become behind that area.

How do I solve it*

**Comment by dnfield** [comment]
Does a `SafeArea` not help you here?

**Comment by BaderEddineOuaich** [comment]
Calling `SystemChrome.setEnabledSystemUIOverlays([])` will probably hide that. 
well if it does. it will be a full screen app. as a temporary solution, you can  hide the system ui only for Note 8  by using  [device_info_package](https://pub.dartlang.org/packages/device_info) to detect.

**Comment by NTMS2017** [comment]
SafeArea didnt help. The `SystemChrome.setEnabledSystemUIOverlays([])` works only if user not use more than twice to hide or show Note 8 bottom navigation button. If they do their Note 8 bottom navigation button stays top of the flutter app. I found solution iPhone X problem, but couldn't find even a questions or answer for Note 8 bottom navigation button.

How can I hide the system ui only for Note 8 by using device_info_package to detect? Have no idea how to do it. Any example?

**Comment by dnfield** [comment]
Hmm.  It looks like this phone was probably created before these APIs were standardized, and you'll have to use some samsung specific APIs.

I'd lean towards saying this logic doesn't belong in the framework - it's unlikely that we'll be able to support every Android customization that every manufacturer does for every phone.  That said, if someone knows of a clean way of handling this that doesn't involve linking against vendor libraries and doesn't require a lot of very vendor-specific hacks to detect these things, it'd be interesting to discuss further.

See https://stackoverflow.com/questions/46107474/android-detect-samsung-galaxy-s8-navigation-bar-hide-or-show-programmatically for what some plugin for this might look like.

**Comment by NTMS2017** [comment]
Best I can found something in here https://github.com/flutter/flutter/issues/24472#issuecomment-440015464. And currently its working. 

Tested with Samsung Galaxy Note 8 emulator and 2 actual Samsung Galaxy Note 8 device. With below code I force my app to show in full scale mode. In my app after login there is a home.dart page. I use AnnotatedRegion<SystemUiOverlayStyle> and I just leave as it is the "value: const SystemUiOverlayStyle()". And set to size too false.

I have a bottom navigation bar and its just shows my app bottom navigation bar. If  user try to show the Samsung Galaxy Note 8 bottom navigation bar device shows the bar and if no user interaction it simply hides.

I am not sure if this is a correct way do it but seems working as I expected.


```
Scaffold(
body: AnnotatedRegion<SystemUiOverlayStyle>(
                  value: const SystemUiOverlayStyle(),
                  sized: false,
                  child: new Stack(
                    children: <Widget>[
                      new PageView(
…
…
```

**Comment by dnfield** [comment]
I strongly suspect we could be making this better either via documentation or a higher level widget that wraps this behavior.  What do you think?

**Comment by NTMS2017** [comment]
If you choose "higher level widget that wraps this behavior" it will be much better.
