### ISSUE TITLE
ListWheelViewport should support horizontal alignment

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#31809]
https://github.com/flutter/flutter/blob/8fd7fa492aaad0d0d4aa062d71b1ecba8b0d4f44/packages/flutter/lib/src/rendering/list_wheel_viewport.dart#L629

Currently, `RenderListWheelViewport` always centers its children horizontally within the viewport.  This prevents certain use cases.  Consider the use case of wanting to build scrolling list of hours and minutes (looking like a settable digital clock).  Currently, given the "always center" layout, this looks like this:

![wheel](https://user-images.githubusercontent.com/15253456/56926608-021b8d00-6a87-11e9-8aee-bc5753996953.gif)

But in this case, it's more appropriate to right-align the single digit "9" rather than center it.

I propose we add a new `ListWheelAlignment` enum, with the same values as `TextAlign`:

* `left`
* `right`
* `center`
* `start`
* `end`
* `justify`

**Comment by Hixie** [comment]
Why not just use TextAlign?

**Comment by Hixie** [comment]
or Alignment

**Comment by tvolkert** [comment]
Actually @Hixie something you said as we were discussing this today stuck with me.  I can get the behavior I want by using `SizedBox.expand` with a nested `Align` (or without the nested `Align` if I was stretch behavior).

Thus, closing this issue.
