### ISSUE TITLE
Remove mirrors usage from flutter_tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#31803]
The flutter_tool transitively depends on code that requires mirrors - specifically I believe it is the mustache package. We should remove this dependency and add a test to ensure that we never add mirrors code in the future.

This will unblock providing an AOT version of the flutter tool in the future.

cc @tvolkert @zanderso

**Comment by zanderso** [comment]
IIRC, mustache is a templating library. What does the tool use templating for?

**Comment by jonahwilliams** [comment]
The flutter create templates use mustache templates, but we could replace it with another approach.

**Comment by blasten** [comment]
It seems the easiest fix is to create two entry points in the Mustache package (one with mirrors, and the other one without). The package's author suggested something similar. I referenced the issue above.

**Comment by jonahwilliams** [comment]
I don't believe our templates are complex enough that we actually need a full templating library, but this could use some investigation. @blasten would you like to look into the feasibility of either option?

**Comment by blasten** [comment]
From looking at the code, it seems the alternative would need to support primitive and compound types.

The ones under [dev/snippets/config/templates](https://github.com/flutter/flutter/tree/262f12b4a9269a77bce499926afa681b20790d6c/dev/snippets/config/templates) seem to only care about primitives.  However, these ones don't: https://github.com/flutter/flutter/blob/a476a08e629533ec5ad2e645a7176f0ddbca24e6/packages/flutter_tools/lib/src/plugins.dart#L120-L122

**Comment by zanderso** [comment]
Is it possible to have a lint for this?

**Comment by jonahwilliams** [comment]
We could try compiling the tool with some sort of --no-mirrors flag to see if succeeds

**Comment by zanderso** [comment]
We could pass `--no-enable-mirrors` in the `bin/flutter` scripts in the invocation where it creates the snapshots. If someone adds a `dart:mirros` import, the pre-submit checks should mostly turn red.
