### ISSUE TITLE
No such method: streamNotify

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#31813]
After adding logic to catch previously swallowed exceptions in json_rpc_2, we're now seeing this exception thrown in devicelab and google3 tests.  

```dart
JSON-RPC error -32601 (method not found): Unknown method "streamNotify".
#0      Server._tryFallbacks._tryNext (package:json_rpc_2/src/server.dart:272:9)
<asynchronous suspension>
#1      Server._tryFallbacks (package:json_rpc_2/src/server.dart:284:20)
```

I suspect this is a timing issue where something is trying to call that method before we've registered it - it gets registered in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L113

**Comment by dnfield** [comment]
This appears to be by design in json_rpc_2 - see https://github.com/dart-lang/json_rpc_2/blob/6c1aa294ae082343a6bcdae5778ce04e1f4c1e3a/lib/src/server.dart#L40

**Comment by dnfield** [comment]
This could be fixed by having JSON_RPC_2 report this exception back to the client instead of not handling it.

**Comment by dnfield** [comment]
This may also be fixable by not using `sendNotification`, which per the spec isn't supposed to send a response.

**Comment by matanshukry** [comment]
I'm having the same exception when running flutter drive. 

test_driver\app_test.dart:
`
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  Future<bool> isPresent(SerializableFinder finder, FlutterDriver driver,
      {Duration timeout = const Duration(seconds: 1)}) async {
    try {
      await driver.waitFor(finder, timeout: timeout);
      return true;
    } catch (e) {
      return false;
    }
  }

  group('Strw App', () {
    final materialAppFinder = find.byValueKey('MainMatApp');

    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed
    tearDownAll(() async {
      if (driver != null) {
        await driver.close();
      }
    });

    test('successfully starts up', () async {
      expect(await isPresent(materialAppFinder, driver), true);
      expect((await driver.checkHealth()).status, HealthStatus.ok);
    });
  });
}
`

Exception:
`
[trace] FlutterDriver: Unhandled RPC error:
JSON-RPC error -32601 (method not found): Unknown method "streamNotify".
#0      Server._tryFallbacks._tryNext (package:json_rpc_2/src/server.dart:272:9)
<asynchronous suspension>
#1      Server._tryFallbacks (package:json_rpc_2/src/server.dart:284:20)
#2      Server._handleSingleRequest (package:json_rpc_2/src/server.dart:181:30)
<asynchronous suspension>
#3      Server._handleRequest (package:json_rpc_2/src/server.dart:157:24)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#5      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#6      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#13     _StreamController._add (dart:async/stream_controller.dart:640:7)
#14     _StreamController.add (dart:async/stream_controller.dart:586:5)
#15     Peer.listen.<anonymous closure> (package:json_rpc_2/src/peer.dart:104:36)
#16     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#18     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#25     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#26     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#27     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#28     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#29     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#36     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#37     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#38     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#39     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#40     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#44     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#45     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#46     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#47     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#54     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#55     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#56     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#57     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#58     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#59     _rootRunUnary (dart:async/zone.dart:1132:38)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#65     _StreamController._add (dart:async/stream_controller.dart:640:7)
#66     _StreamController.add (dart:async/stream_controller.dart:586:5)
#67     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1138:21)
#68     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#69     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#70     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#71     _rootRunUnary (dart:async/zone.dart:1132:38)
#72     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#76     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#77     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#78     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#79     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#80     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#81     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#82     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#83     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#84     _rootRunUnary (dart:async/zone.dart:1132:38)
#85     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#86     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#87     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#88     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#89     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#90     _StreamController._add (dart:async/stream_controller.dart:640:7)
#91     _StreamController.add (dart:async/stream_controller.dart:586:5)
#92     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#93     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:26)
#94     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#95     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:129:14)
#96     _rootRunUnary (dart:async/zone.dart:1136:13)
#97     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#98     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#99     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#100    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#101    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#102    _StreamController._add (dart:async/stream_controller.dart:640:7)
#103    _StreamController.add (dart:async/stream_controller.dart:586:5)
#104    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#105    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#106    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#107    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#108    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#109    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
`

note that the test it self seems to work. That is, it success if the app starts up, and fails if it doesn't (e.g. if I had throw "crash" on start or something like that).
Are there any side effects that this is causing I should be aware about?

**Comment by dnfield** [comment]
I'm updating the logic to ignore these for now - they're safe to ignore.  However, the real fix here is to rewrite notification messages from the client side to actually get responses so that we can handle error conditions correctly on the client.

**Comment by jonahwilliams** [comment]
Fixed by migrating to package:vm_service
