### ISSUE TITLE
flutter android-licenses fails on ubuntu

### ISSUE THREAD

**Issue by a7mefathi** [flutter/flutter#31821]
flutter doctor --android-licenses       =====>my command

A newer version of the Android SDK is required. To update, run:    response
/home/ahmed/Android/Sdk/tools/bin/sdkmanager --update

/home/ahmed/Android/Sdk/tools/bin/sdkmanager --update   ====>

Error occurred during initialization of boot layer       response
java.lang.module.FindException: Module java.se.ee not found

 /home/ahmed/Android/Sdk/tools/bin/sdkmanager --licenses    ====>

Error occurred during initialization of boot layer        response
java.lang.module.FindException: Module java.se.ee not found

=============================================    here is my flutter doctor -v

[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.2.1 at /home/ahmed/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ahmed/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: /home/ahmed/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/ahmed/android-studio
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by insequent** [comment]
I was able to reproduce this using Android Studio's jre (which is Java 8). `java.se.ee` is only needed when running Android Studio with Java > version 8. Check your env vars for something like  `SDKMANAGER_OPTS` or `JAVA_OPTS` and you'll probably see `--add-modules java.se.ee`. Remove that option and your sdkmanager should work again.

**Comment by insequent** [comment]
Wrote a more detailed explanation here: https://github.com/flutter/flutter/issues/31116#issuecomment-492781512

**Comment by BondarenkoStas** [comment]
@insequent I think it will be safe to close the issue in favour of #31116.
