### ISSUE TITLE
_AssertionError ('package:flutter/src/widgets/framework.dart': Failed assertion: line 1654 pos 14: 'children != null': is not true.)

### ISSUE THREAD

**Issue by jfboisvieux** [flutter/flutter#31837]
## Steps to Reproduce

```
```

```
```

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-FR)
    • Flutter version 1.2.1 at /usr/local/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jfb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone Xʀ • D14348D5-11AE-4201-BA0F-804C28EF0FB5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

```
```

**Comment by BaderEddineOuaich** [comment]
It sounds like you are passing a <strong>null</strong > value to a <strong>\<widget>\[]</strong> list. try out that solution .
for example you have:
<pre>
bool isLoading = false:
 Row(
              children: 
                [
                    RaisedButton(),
                    isLoading ? Widget() : null,
                ].where((child) => child != null).toList() // this line will clean the widget list from null values .
              );
</pre>

**Comment by jfboisvieux** [comment]
Thanks

___
##   Ipad email
Jean-Francois Boisvieux
mobile : (33) 6 32 49 26 98
email : jf@boisvieux.com

**Comment by shihaohong** [comment]
I assume that your issue has been resolved and will close this. Feel free to reopen if otherwise
