### ISSUE TITLE
Flutter Google Maps displaying horitzontally

### ISSUE THREAD

**Issue by jeronimolina** [flutter/flutter#31841]
I've been using google maps in my app for two months and i had no problems with my rendering, but today when I opened the google maps widget was displaying horitzontally. I returned to previous commits when the app was working correctly just in case that i touched something but the map was displaying horitzontally too.To reproduce the error I created a new screen with the code that you can find on "https://pub.dartlang.org/packages/google_maps_flutter". Here is the screenshot:

![WhatsApp Image 2019-04-30 at 11 54 31](https://user-images.githubusercontent.com/37617875/56954315-c7752b80-6b3e-11e9-8b28-c1df194f8d9e.jpeg)

The movement of the map works good considering that the map is displaying vertically, is the rendering that is not working. Any ideas?

**Comment by jeronimolina** [comment]
Now it's working correctly, I suppose that it was a problem from the API.

**Comment by jeronimolina** [comment]
Now It's working correctly. I suppose that it was a problem from the API.

**Comment by BondarenkoStas** [comment]
@jeronimolina is it still the same or was it resolved with current maps version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
