### ISSUE TITLE
how to calculate mathematic string in Flutter.  Ex: "2.5+3.3+5*9-8" 

### ISSUE THREAD

**Issue by sagardeveloper** [flutter/flutter#31843]
I read the documentation of the flutter and know the integer to string and string to an integer, but how can I convert the whole string into an integer for calculation.

I have also a program in which I can get 2 values from the string according to the operator and according to BODMAS rule, but also I am not getting the accurate result if I use double number means 2.3 or 1.1.

**Comment by BaderEddineOuaich** [comment]
Check out this [package](https://pub.dartlang.org/packages/math_expressions) for parsing and evaluating mathematical expressions.

**Comment by sagardeveloper** [comment]
> Check out this [package](https://pub.dartlang.org/packages/math_expressions) for parsing and evaluating mathematical expressions.

I am using it as 

 Parser p = new Parser();
 Expression exp = p.parse("5+5+5");
#and 

result is = ((5.0 + 5.0) + 5.0)

**Comment by BaderEddineOuaich** [comment]
To get the result . evaluate:
<pre>
  Parser p = new Parser();
  Expression exp = p.parse("5+5+5");
  print(exp.evaluate(EvaluationType.REAL, null)); // if context is available replace it with null.
</pre>

**Comment by BaderEddineOuaich** [comment]
To get the result . evaluate:

<pre>
  Parser p = new Parser();
  Expression exp = p.parse("5+5+5");
  String result = exp.evaluate(EvaluationType.REAL, null).toString();  // if context is available replace it with null.
  print(result);
</pre>

**Comment by BaderEddineOuaich** [comment]
To get the result . evaluate:

<pre>
  Parser p = new Parser();
  Expression exp = p.parse("5+5+5");
  String result = exp.evaluate(EvaluationType.REAL, null).toString();  // if context is not available replace it with null.
  print(result);
</pre>

**Comment by jonahwilliams** [comment]
Sounds like your question was answered. In the future please do not post generic help questions on the issue tracker.

**Comment by sagardeveloper** [comment]
> Sounds like your question was answered. In the future please do not post generic help questions on the issue tracker.

So, where I should post if I am facing any code related issue?
