### ISSUE TITLE
External padding incorrect for raised and flat buttons

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3184]
When putting RaisedButton or FlatButton in a Row, the spacing between the buttons are incorrect. Also the internal padding to the text may be too small horizontally.

Test case in: /examples/material_gallery/lib/demo/buttons_demo.dart

![flutter_01](https://cloud.githubusercontent.com/assets/1539812/14366753/33e048c8-fcc9-11e5-9618-6e9ee31b1295.png)

Correct spacing (from the material design spec):

<img width="370" alt="screen shot 2016-04-07 at 2 03 08 pm" src="https://cloud.githubusercontent.com/assets/1539812/14366846/970633a4-fcc9-11e5-9913-6dfe0d1426c4.png">

**Comment by abarth** [comment]
This might be due to margin collapsing.  Need to study the spec more.  We might need a special widget for laying out rows of buttons.
