### ISSUE TITLE
Document for FlutterDriver timeout argument 

### ISSUE THREAD

**Issue by sensuikan1973** [flutter/flutter#31842]
## Use case
When I implement integration test, I think that FlutterDriver document is ambiguous about timeout argument.
example: waitFor, waitForAbsent, tap and so on.

if it times out, it **only showes a message not fail**.
FlutterDriver document doesn't mention that.

## Proposal
How about describing the timeout argument behavior on [document](https://docs.flutter.io/flutter/flutter_driver/FlutterDriver-class.html) ?

**Comment by Abhishek01039** [comment]
@TahaTesser can we close this issue because flutter_driver is discontinued?

**Comment by sensuikan1973** [comment]
agree.

e.g. https://api.flutter.dev/flutter/flutter_driver/kUnusuallyLongTimeout-constant.html
