### ISSUE TITLE
How to get current zoom?

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter#31846]
## Use case
It would be nice to add a feature in `GoogleMap` something like `onZoomChanged: (double zoom){}` so that we can see what is the zoom value user has selected. 

When animating camera position, I need to hard code the value by myself, if I knew the current zoom (after user zoomed in/out), it should be a clean move to animate camera. 

Also I didn't see any zoom in/out buttons which native Android has. Are you planning to add them?

**Comment by ZviKarp** [comment]
You can use the method `onCameraMove` like this:

```
class GeoSelectorWidget extends StatelessWidget {
  Completer<GoogleMapController> _controller = Completer();

  void _onGeoChanged(CameraPosition position) {
    print("position: " + position.target.toString());
    print("zoom: " + position.zoom.toString());
  }

  void _onMapCreated(GoogleMapController controller) {
    _controller.complete(controller);
  }

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      onMapCreated: _onMapCreated,
      initialCameraPosition: CameraPosition(
        target: initGeo,
        zoom: initZoom,
      ),
      onCameraMove: _onGeoChanged,
    );
  }
}
```

**Comment by dark-chocolate** [comment]
Thanks @ZviKarp I'll give that a try, closing this for now.

**Comment by anaskhalid98** [comment]
I want the current zoom value, i used the code above but i get the error :

NoSuchMethodError (NoSuchMethodError: The getter 'zoom' was called on null.
Receiver: null
Tried calling: zoom)

**Comment by JegatheshKumarHcl** [comment]
Hi there! please help me out!

      onCameraMove: _onGeoChanged, doesn't trigger cameraMove listener, and the logs inside the _onGeoChanged didn't event print.  I have verified that the method signatures are similar to the one suggested above.

Thanks.
