### ISSUE TITLE
Multiple compile errors in ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart

### ISSUE THREAD

**Issue by dakamojo** [flutter/flutter#31853]
## Steps to Reproduce

I believe I have messed up my Flutter install.  I have a small project that was going smoothly until I did something wrong.  I did a flutter update and also bumped up all my dependencies to the latest versions.  I now see multiple errors in this file.

Dart Analysis shows these errors.  But flutter analyze does not.

ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart

`error: Undefined class 'PointerDataPacket'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:14)
error: Undefined class 'ByteData'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:17)
error: Undefined class 'SemanticsAction'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:17)
error: Undefined class 'ByteData'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:23)
error: Undefined class 'ByteData'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:26)
error: The method 'hashValues' isn't defined for the class 'Locale'. (undefined_method at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:378)
error: Undefined class 'Size'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:441)
error: Undefined class 'Size'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:442)
error: Undefined name 'Size'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:442)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:497)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:500)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:548)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:551)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:570)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:573)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:609)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:612)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:636)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:639)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:658)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:661)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:675)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:678)
error: Undefined class 'Scene'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:750)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:768)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:771)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:784)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:787)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:800)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:803)
error: Undefined class 'SemanticsUpdate'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:813)
error: Undefined class 'ByteData'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:839)
error: Undefined class 'Zone'. (undefined_class at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:859)
error: Undefined name 'Zone'. (undefined_identifier at [liga] ios/.symlinks/flutter/common/flutter_patched_sdk/stub_ui/window.dart:862)`

I can build and run the app in the iOS simulator, but these errors are preventing hot reloading from working.  

## Logs

```
```

```
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/darrelldavis/Development/Flutter/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/darrelldavis/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 346FC64F-6915-41C3-98BF-3C3A86E55AAB • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

```

**Comment by jonahwilliams** [comment]
> I have a small project that was going smoothly until I did something wrong.

You'll need to be more specific.

Those files definitely shouldn't be there. I'm not sure how to help, because i'm not sure what you actions you took to arrive there

**Comment by dakamojo** [comment]
As far as I know I only did flutter upgrade and manually updated all the dependency versions in my pubspec.  Here is that file.

```name: liga
description: liga

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.0.1
  firebase_auth: ^0.8.1+4
  google_sign_in: ^4.0.1+1
  flutter_auth_buttons: ^0.3.1

  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  cloud_firestore: ^0.10.0
  uuid: ^2.0.1
  intl: ^0.15.8
  package_info: ^0.4.0+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  assets:
    - assets/images/logo_1024.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

**Comment by dakamojo** [comment]
Is there a clean way to regenerate everything under flutter_patched_sdk?

**Comment by bawelter** [comment]
Execute "pod deintegrate" in the corresponding ios directory.  It's probably complaining because the plugin example ios symlinks are messed up.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
