### ISSUE TITLE
upgrading flutter to 1.6.3 caused a significant build slow and a much bigger apk

### ISSUE THREAD

**Issue by bestheroforever** [flutter/flutter#31859]

**Comment by bestheroforever** [comment]
can someone help me?‌:(

**Comment by rajeshzmoke** [comment]
This is happening recently , building dart code takes around 200s

**Comment by rajeshzmoke** [comment]
`Building com.xxx.xxx for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxx
Running pod install...                                             10.5s
Running Xcode build...                                                  
                                                   
 ├─Building Dart code...                                         
  182.9s (!)                                       
 ├─Generating dSYM file...                                   0.8s
 ├─Stripping debug symbols...                                0.2s
 ├─Assembling Flutter resources...                           4.0s
 └─Compiling, linking and signing...                        18.9s
Xcode build done. `

**Comment by passsy** [comment]
Which command are you running? Can you confirm increased build times using `flutter build aot`?
What flutter version are you using?

**Comment by rajeshzmoke** [comment]
i'm running `flutter build ios --release`

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at /Users/rajeshkumar/Desktop/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshkumar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rajeshkumar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • HPS’s iPhone • 6d43bae0802ac243f5c1bfe5e8ed54668ce49e6c • ios • iOS 12.2

• No issues found!
```

**Comment by simeonzv** [comment]
I noticed significant build slow down today after upgrading flutter to 1.6.3. In addition the apk size got much bigger. 

I run android release build on linux like this

```
$ flutter clean
$ flutter run --release --flavor staging -t lib/launcher/staging/main_staging.dart -d XXXXXX
```

After some experiments with different versions I can conclude that problems started in the version 1.6.1 and it was much faster/smaller in 1.6.0. I can also confirm that problems with the slow build and bigger apk size still persist in the latest 1.6.7.

Here are some details for comparison

SLOW AND BIG
```
Flutter 1.6.1 • channel unknown • unknown source
Framework • revision d31ce31a27 (2 weeks ago) • 2019-05-20 17:25:59 -0700
Engine • revision e3772232c2
Tools • Dart 2.3.1 (build 2.3.1-dev.0.0 b48c8b1d1c)
```
```
Running Gradle task 'assembleStagingRelease'... Done              393.7s (!)
Built build/app/outputs/apk/staging/release/app-staging-release.apk (22.0MB).
```
FAST AND SMALL
```
Flutter 1.6.0 • channel unknown • unknown source
Framework • revision ed90d05596 (3 weeks ago) • 2019-05-14 17:09:29 -0700
Engine • revision 832cdacc6f
Tools • Dart 2.3.1 (build 2.3.1-dev.0.0 b48c8b1d1c)
```
```
Running Gradle task 'assembleStagingRelease'... Done               67.1s
Built build/app/outputs/apk/staging/release/app-staging-release.apk (14.3MB).
```

Any idea what could cause this?

**Comment by Monkey-D-Code** [comment]
Error connecting to the service protocol: HttpException: Connection closed before full header was received
![image](https://user-images.githubusercontent.com/45763998/62764225-022a2080-baab-11e9-96a0-36026584971e.png)

**Comment by csells** [comment]
@bestheroforever do you see this still happening as of the 1.12 stable build?

**Comment by blasten** [comment]
@Monkey-D-Code you might be using an Android Q emulator. Please update the system image on Android Studio -> Preferences -> Android SDK -> SDK Platforms.

**Comment by jonahwilliams** [comment]
Closing as without more details we're unable to progress any further
