### ISSUE TITLE
Regression of coverage reporting with mixins.

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#31856]
On the master channel, using `flutter test --coverage` on a project with mixins may generate invalid coverage reporting (missing lines).

Running the same command line on stable channel do not have this issue.

The following project contains the bare minimum to reproduce this issue: https://github.com/rrousselGit/coverage_regression_example.git

Steps to reproduce:

- clone the above repository
- run `flutter test --coverage`
- the mixin `Fail` of `/lib/src/foo.dart` has the method `hello` reported as not covered by tests. 
But it is in fact covered in `/test/foo_test.dart` through the `FailTest` class.

During my different experimentations, I noticed that moving `FailTest` class into `/lib/src/foo.dart` correctly report the line as covered.

**Comment by rrousselGit** [comment]
cc @filiph

**Comment by jonahwilliams** [comment]
For additional context: we are filtering out the coverage information from every library that is not in `lib/` to solve https://github.com/flutter/flutter/issues/23157. It seems like in this case the coverage information for mixins might be incorrectly attached to the test script instead of the library.

**Comment by jason-simmons** [comment]
The new coverage collector is doing a `getSourceReport` RPC for each `scriptId` loaded into the isolate.

The old coverage collector was not passing a `scriptId` argument when calling `getSourceReport`.  This returns a source report with a lot more ranges, including multiple ranges for the `foo.dart` script in the attached example.

One of the additional `foo.dart` ranges includes the hit for the mixin method line.

How is Dart's API intended to behave in this case?  I would have assumed that passing the `foo.dart` scriptId would return all ranges associated with `foo.dart`, but Dart does not seem to be doing that.

**Comment by jonahwilliams** [comment]
The fact that it works for abstract classes and not mixins is interesting as well.

**Comment by eseidelGoogle** [comment]
@devoncarew would know (or know who would know).

**Comment by devoncarew** [comment]
@rmacnak-google and @bkonyi can best answer from the VM service protocol perspective; @cbracken has more experience with dart coverage in general

**Comment by rrousselGit** [comment]
Any update?
Because that bug is now on `stable`.

**Comment by acherkashyn** [comment]
Any update on this issue? I'm seeing this as well.

**Comment by ZichangG** [comment]
I haven't looked this issue yet.  But there is a [similar issue](https://github.com/dart-lang/sdk/issues/34841) I'm working on. It is probably because VM recorded script of closures incorrectly.

**Comment by ZichangG** [comment]
[This CL](https://github.com/dart-lang/sdk/commit/f9402d635a0e043d94422bbbd387b8d78b18d1e6) is able to solve this problem. Once it rolls into Flutter, it should be fine.

**Comment by renehansen** [comment]
Unfortunately, the CL that @ZichangG refers to, did not fix the missing coverage of mixins. We are still observing the same behavior as  @rrousselGit originally reported

**Comment by ZichangG** [comment]
That might be another issue or a regression. When did you start to notice that?

Can you run `dart --version`?

**Comment by renehansen** [comment]
We are using:
Flutter 1.12.13+hotfix.8 • channel stable
Framework • revision 0b8abb4724
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

This is our first Flutter app, and we have only recently started using mixins, so I can't say if it has worked in the past. 

However, we are experiencing the exact same issue as @rrousselGit reported: The mixin code is mistakenly not covered in the report when we run `flutter test --coverage` _unless_ we move the implementing class to the same file as the mixin. In that case, the mixin code _is_ covered in the coverage report.

**Comment by ZichangG** [comment]
Unfortunately, I re-run my test(https://github.com/dart-lang/sdk/commit/f9402d635a0e043d94422bbbd387b8d78b18d1e6) and add the same `String hello() => 'Hello World';` to the mixin class.
I'm able to see the corresponding line.

Do you mind posting a snippet of your code which is reported as missing?
