### ISSUE TITLE
Problem with iOS always the app crash in iOS

### ISSUE THREAD

**Issue by KarimMohamed2005** [flutter/flutter#31864]
Actually I am working with **codemagic** and now I am trying to deploy my app is there anyway to debug my app from **codemagic** ? 
_I was have some problems in iOS build my console in **codemagic** was giving me `Self Issue`_ but after some search I got a solution for it from [SOLUTION](https://stackoverflow.com/questions/21577711/block-implicitly-retains-self-explicitly-mention-self-to-indicate-this-is-i)
but after trying this solution it's now build but always crash on iPhone 6
if anyone working with iOS from Mac and Have some experience with this problems can help me
_[Source Code](https://github.com/KarimMohamed2005/updategroup)_

**Comment by BondarenkoStas** [comment]
@KarimMohamed2005 did you manage to resolve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
