### ISSUE TITLE
Error while displaying $20.00 (Dollar Sign) as text  in Text()

### ISSUE THREAD

**Issue by AkramChauhan** [flutter/flutter#31869]
Here for explaining this issue.
I'm just wrapping my Text in Child

**child:Text("$20.00")**

Showing me error "Expected an Identifier" (Missing Identifier).

**Comment by jonahwilliams** [comment]
`$` is used for string interpolation, you need to escape it like `\$20.00`

**Comment by AkramChauhan** [comment]
That worked.
Thanks
