### ISSUE TITLE
Text isn't correctly aligned in drop down menus.

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3187]
Text isn't correctly aligned in drop down menus.

Test case in: /examples/material_gallery/lib/demo/buttons_demo.dart

![flutter_02](https://cloud.githubusercontent.com/assets/1539812/14367081/e4452c82-fcca-11e5-8224-5e95316d706a.png)

**Comment by abarth** [comment]
The text is aligned as described in the spec.  It just doesn't look good.  Previously I tried to change our alignment here to look good but @Hixie thought we should match the spec.

/cc @sethladd

**Comment by Hixie** [comment]
We should annotate a screenshot of flutter with the precise measurements from the spec to show that we match it, and if we do, send that to the material spec team for advice.

**Comment by Hixie** [comment]
This looks fine to me now.
