### ISSUE TITLE
"Unknown platform: windows-x64" when running: flutter build bundle --target-platform windows-x64

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#31883]
I'm having this error when trying to build bundle for windows:

> Unknown platform: windows-x64 

## Steps to Reproduce
1. Checkout the master channel
2. In a flutter project run: **flutter build bundle --target-platform windows-x64**
3. Receiving _Unknown platform: windows-x64_ message

## Logs

<img width="559" alt="Sketch" src="https://user-images.githubusercontent.com/33294549/57002808-00061b00-6bba-11e9-8c0c-8ff07028fe90.png">

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.9-pre.84, on Microsoft Windows [Version 10.0.17134.753], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
```

**Comment by jonahwilliams** [comment]
`windows-x64` is not a supported target platform for the command. The bundle itself is fairly platform agnostic, so use the default bundle command without a specified argument.

**Comment by pedromassango** [comment]
I run it intetionally. As in master channel we have this option
