### ISSUE TITLE
Default icon theme isn't using the correct color

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3188]
The default icon theme isn't using the correct color (it's currently full on black, while it should be dark grey). In the image the leftmost icon should be dark grey.

Test case in: /examples/material_gallery/lib/demo/buttons_demo.dart

![flutter_03](https://cloud.githubusercontent.com/assets/1539812/14367139/38163eb4-fccb-11e5-96d4-c6478888f5ca.png)

**Comment by drkhannah** [comment]
what color gray should it be? gray 900?

**Comment by drkhannah** [comment]
just did a pull request for this change https://github.com/flutter/flutter/pull/19169

**Comment by jonahwilliams** [comment]
@drkhannah I think the spec has changed since that issue was filled, maybe @HansMuller would know?

**Comment by drkhannah** [comment]
Hey Jonah, nice to meet you! I think you are correct

**Comment by willlarche** [comment]
Icons on a light background should be black with 87% alpha
Icons on a dark background should be white with 100% alpha

See [guidelines on icon](https://material.io/design/iconography/system-icons.html#color).

**Comment by HansMuller** [comment]
I believe the current values are wrong:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L185
