### ISSUE TITLE
Version check logic in dev/bots/test.dart is incorrect

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#31880]
This does not account for hotfix branches.

https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L676

**Comment by Hixie** [comment]
I'm marking this as a PM blocker since we're going to want this fixed before the next beta release.

**Comment by Hixie** [comment]
While we're at it we should change the - to a + in the hotfix process (and associated code).

**Comment by jonahwilliams** [comment]
We've landed the fix to the tool to correctly describe the semvar of hotfix branches. We still need to update version check test regexp. That should be fairly easy and I will take a look this week.

Separately, we will need to re-test the hotfix process.

**Comment by jonahwilliams** [comment]
This is done
