### ISSUE TITLE
Remove initial jank in flutter_gallery using more shader warm-up

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#31881]
Our goal is to drop out flutter_gallery worst frame time benchmark down to 16ms on both Android and iOS. Currently it sits at about 120+ms. Part of it is because that we're measuring the wrong thing https://github.com/flutter/flutter/issues/31442 . After fixing #31442, we still have some shader warm-up work to do.

**Comment by miguelpruivo** [comment]
This is also affecting a production app so anything that could contribute to solve it would be great. Every first 3 seconds or so that the app is opened, either from scratch or background, it has a junky performance (a lot of frame rate drops while scrolling) and then becomes smooth. Only seems to affect iOS (currently only tried with iPhone X). 

Any news on this?

**Comment by eseidelGoogle** [comment]
@miguelpruivo note, we're also investigating a couple iPhone X specific bugs: https://github.com/flutter/flutter/issues/31086

**Comment by kf6gpe** [comment]
Giving back to the engine team to triage, please.

**Comment by liyuqian** [comment]
@kf6gpe : we're currently building tools for Android and iOS so we can use the semi-automated SkSL shader warmup to remove the initial jank. In terms of flutter_gallery, I have a bigger concern: the play store is currently offering the new flutter_gallery app that's not covered by our current performance tests. Hence any improvements here may only be for the old flutter_gallery. Do you know if the new flutter_gallery is already in the flutter/flutter repo, and if we have plan to migrate or add performance tests to it?

**Comment by kf6gpe** [comment]
Great question! I don't think it's been merged yet. I don't know what the current plans are --- I know that some of the folks working with @willlarche were working on it, in MUC, I think. @willlarche, do you know the status of migrating that into flutter/flutter, or who we should ask?

**Comment by willlarche** [comment]
The new flutter gallery is not going to be moved into flutter/flutter. This (older) gallery will continue to live in flutter/flutter as a place for performance tests. 

If you'd like performance tests for the new gallery, we'd be happy to discuss!

**Comment by orestesgaolin** [comment]
@willlarche I found some performance bottlenecks in new Flutter Gallery and wonder if we can track or report them somewhere. Should I just post them in issue here?

**Comment by willlarche** [comment]
Great timing! We’re actually doing a performance optimization project on
it. We track that here:
https://github.com/material-components/material-components-flutter-gallery

Do you have the ability to post there?

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/pull/59932 has added SkSL shader warm-up to Android and iOS. Moto G4's worst frame time improved from ~90 ms to ~40
ms, and iPhone 4s improved from ~300 ms to ~80 ms. There are some other things we need to improve to bring the worst time down to 16ms, but the shader warm-up is done so I'm closing this issue.
