### ISSUE TITLE
Listview overflow

### ISSUE THREAD

**Issue by tomkochi** [flutter/flutter#31888]
I am doing a simple restaurant listing page. Below is my code. I could not solve the overflow problem. Please help.

Also, how can I make getRestaurants() GET info from JSON endpoint?

```
void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primaryColor: Colors.white, fontFamily: 'Raleway'),
      home: new ListPage(title: 'Restaurants'),
    );
  }
}

class Restaurant {
  String name;
  String imagePath;
  int discountType;
  double rating;
  String opensAt;

  Restaurant(
      {this.name,
      this.imagePath,
      this.discountType,
      this.rating,
      this.opensAt});
}

class ListPage extends StatefulWidget {
  ListPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _ListPageState createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  List restaurants;

  @override
  void initState() {
    restaurants = getRestaurants();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Container makeList(Restaurant restaurant) => Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Stack(
                children: <Widget>[
                  Image.network(restaurant.imagePath),
                  Positioned(
                    child: restaurant.discountType == 25
                        ? Icon(Icons.ac_unit)
                        : Icon(Icons.access_alarm),
                    top: 30.0,
                  )
                ],
              ),
              Padding(
                padding: const EdgeInsets.all(14.0),
                child: Text(restaurant.name),
              )
            ],
          ),
        );

    Card makeCard(Restaurant restaurant) => Card(
          elevation: 8.0,
          margin: new EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
          child: Container(
            child: makeList(restaurant),
          ),
        );

    final makeBody = Container(
        child: Column(
      children: <Widget>[
        Text('Title before ListView'),
        ListView.builder(
          scrollDirection: Axis.vertical,
          shrinkWrap: true,
          itemCount: restaurants.length,
          itemBuilder: (BuildContext context, int index) {
            return Column(
              children: <Widget>[makeCard(restaurants[index])],
            );
          },
        ),
      ],
    ));

    final topAppBar = AppBar(
      elevation: 0.1,
      title: Text(widget.title),
      actions: <Widget>[
        IconButton(
          icon: Icon(Icons.list),
          onPressed: () {},
        )
      ],
    );

    return Scaffold(
      appBar: topAppBar,
      body: makeBody,
    );
  }
}

List getRestaurants() {
  return [
    Restaurant(
        name: 'Rockers Club',
        imagePath:
            'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
        discountType: 50,
        rating: 3.2,
        opensAt: '10.30 AM'),
    Restaurant(
        name: 'Numa Clora',
        imagePath:
            'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
        discountType: 25,
        rating: 4.3,
        opensAt: '09.30 AM'),
    Restaurant(
        name: 'North Clubbers',
        imagePath:
            'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
        discountType: 50,
        rating: 21,
        opensAt: '10.00 AM')
  ];
}
```

**Comment by BaderEddineOuaich** [comment]
<h3>There you go!</h3>
<pre>
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primaryColor: Colors.white, fontFamily: 'Raleway'),
      home: new ListPage(title: 'Restaurants'),
    );
  }
}

class Restaurant {
  String name;
  String imagePath;
  int discountType;
  double rating;
  String opensAt;

  Restaurant(
      {this.name,
      this.imagePath,
      this.discountType,
      this.rating,
      this.opensAt});

  // this will parse json data to your class data and return a class object.
  factory Restaurant.fromJson(Map<String, dynamic> json) {
    return Restaurant(
      name: json['name'],
      imagePath: json['imagePath'],
      discountType: json['discountType'],
      rating: json['rating'],
      opensAt: json['opensAt'],
    );
  }
}

class ListPage extends StatefulWidget {
  ListPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _ListPageState createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  List restaurants;

  @override
  void initState() {
    restaurants = getRestaurants();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Container makeList(Restaurant restaurant) => Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Stack(
                children: <Widget>[
                  Image.network(restaurant.imagePath),
                  Positioned(
                    child: restaurant.discountType == 25
                        ? Icon(Icons.ac_unit)
                        : Icon(Icons.access_alarm),
                    top: 30.0,
                  )
                ],
              ),
              Padding(
                padding: const EdgeInsets.all(14.0),
                child: Text(restaurant.name),
              )
            ],
          ),
        );

    Card makeCard(Restaurant restaurant) => Card(
          elevation: 8.0,
          margin: new EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
          child: Container(
            child: makeList(restaurant),
          ),
        );

    final makeBody = Scrollbar(
      child: Column(
        mainAxisSize: MainAxisSize.max,
        children: <Widget>[
          Text('Title before ListView'),
          Expanded(
            child: ListView.builder(
              scrollDirection: Axis.vertical,
              //shrinkWrap: true,
              itemCount: restaurants.length,
              itemBuilder: (BuildContext context, int index) {
                return Column(
                  children: <Widget>[makeCard(restaurants[index])],
                );
              },
            ),
          )
        ],
      ),
    );

    final topAppBar = AppBar(
      elevation: 0.1,
      title: Text(widget.title),
      actions: <Widget>[
        IconButton(
          icon: Icon(Icons.list),
          onPressed: () {},
        )
      ],
    );

    return Scaffold(
      appBar: topAppBar,
      body: makeBody,
    );
  }
}

List getRestaurants() {
  var jsonData = [
    {
      "name": "Rockers Club",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
      "discountType": 50,
      "rating": 3.2,
      "opensAt": '10.30 AM'
    },
    {
      "name": "Numa Clora",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
      "discountType": 25,
      "rating": 4.3,
      "opensAt": '09.30 AM'
    },
    {
      "name": "North Clubbers",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
      "discountType": 50,
      "rating": 2.1,
      "opensAt": '10.00 AM'
    },
  ];

  //this will map each json object restaurant and convert it to an object class restaurant and return a list of that.
  return jsonData
      .map((eachJsonRestaurant) => Restaurant.fromJson(eachJsonRestaurant))
      .toList();

  /* Old Data Ignore.
  return [
    Restaurant(
        name: 'Rockers Club',
        imagePath:
        'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
        discountType: 50,
        rating: 3.2,
        opensAt: '10.30 AM'),
    Restaurant(
        name: 'Numa Clora',
        imagePath:
        'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
        discountType: 25,
        rating: 4.3,
        opensAt: '09.30 AM'),
    Restaurant(
        name: 'North Clubbers',
        imagePath:
        'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
        discountType: 50,
        rating: 21,
        opensAt: '10.00 AM')
  ];*/
}

</pre>

**Comment by BaderEddineOuaich** [comment]
<h4>There you go!</h4>

<pre>
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primaryColor: Colors.white, fontFamily: 'Raleway'),
      home: new ListPage(title: 'Restaurants'),
    );
  }
}

class Restaurant {
  String name;
  String imagePath;
  int discountType;
  double rating;
  String opensAt;

  Restaurant(
      {this.name,
      this.imagePath,
      this.discountType,
      this.rating,
      this.opensAt});

  // this will parse json data to your class data and return a class object.
  factory Restaurant.fromJson(Map<String, dynamic> json) {
    return Restaurant(
      name: json['name'],
      imagePath: json['imagePath'],
      discountType: json['discountType'],
      rating: json['rating'],
      opensAt: json['opensAt'],
    );
  }
}

class ListPage extends StatefulWidget {
  ListPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _ListPageState createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  List restaurants;

  @override
  void initState() {
    restaurants = getRestaurants();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Container makeList(Restaurant restaurant) => Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Stack(
                children: <Widget>[
                  Image.network(restaurant.imagePath),
                  Positioned(
                    child: restaurant.discountType == 25
                        ? Icon(Icons.ac_unit)
                        : Icon(Icons.access_alarm),
                    top: 30.0,
                  )
                ],
              ),
              Padding(
                padding: const EdgeInsets.all(14.0),
                child: Text(restaurant.name),
              )
            ],
          ),
        );

    Card makeCard(Restaurant restaurant) => Card(
          elevation: 8.0,
          margin: new EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
          child: Container(
            child: makeList(restaurant),
          ),
        );

    final makeBody = Scrollbar(
      child: ListView.builder(
        scrollDirection: Axis.vertical,
        itemCount: restaurants.length,
        itemBuilder: (BuildContext context, int index) {
          if (index == 0) // if it's the first position show list title
          {
            return Padding(
              padding: EdgeInsets.all(10),
              child: Text(
                'Title before ListView',
                style: TextStyle(
                    color: Colors.blueGrey[800],
                    fontFamily: 'monospace',
                    fontWeight: FontWeight.w600),
              ),
            );
          } else {
            // after list title display items
            index = index - 1;
            return makeCard(restaurants[index]);
          }
        },
      ),
    );

    final topAppBar = AppBar(
      elevation: 0.1,
      title: Text(widget.title),
      actions: <Widget>[
        IconButton(
          icon: Icon(Icons.list),
          onPressed: () {},
        )
      ],
    );

    return Scaffold(
      appBar: topAppBar,
      body: makeBody,
    );
  }
}

List getRestaurants() {
  var jsonData = [
    {
      "name": "Rockers Club",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
      "discountType": 50,
      "rating": 3.2,
      "opensAt": '10.30 AM'
    },
    {
      "name": "Numa Clora",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
      "discountType": 25,
      "rating": 4.3,
      "opensAt": '09.30 AM'
    },
    {
      "name": "North Clubbers",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
      "discountType": 50,
      "rating": 2.1,
      "opensAt": '10.00 AM'
    },
  ];

  //this will map each json object restaurant and convert it to an object class restaurant and return a list of that.
  return jsonData
      .map((eachJsonRestaurant) => Restaurant.fromJson(eachJsonRestaurant))
      .toList();

  /* Old Data Ignore.
  return [
    Restaurant(
        name: 'Rockers Club',
        imagePath:
        'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
        discountType: 50,
        rating: 3.2,
        opensAt: '10.30 AM'),
    Restaurant(
        name: 'Numa Clora',
        imagePath:
        'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
        discountType: 25,
        rating: 4.3,
        opensAt: '09.30 AM'),
    Restaurant(
        name: 'North Clubbers',
        imagePath:
        'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
        discountType: 50,
        rating: 21,
        opensAt: '10.00 AM')
  ];*/
}

</pre>

**Comment by tomkochi** [comment]
> #### There you go!
> import 'package:flutter/material.dart';
> 
> void main() => runApp(new MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return new MaterialApp(
>       title: 'Flutter Demo',
>       theme: new ThemeData(primaryColor: Colors.white, fontFamily: 'Raleway'),
>       home: new ListPage(title: 'Restaurants'),
>     );
>   }
> }
> 
> class Restaurant {
>   String name;
>   String imagePath;
>   int discountType;
>   double rating;
>   String opensAt;
> 
>   Restaurant(
>       {this.name,
>       this.imagePath,
>       this.discountType,
>       this.rating,
>       this.opensAt});
> 
>   // this will parse json data to your class data and return a class object.
>   factory Restaurant.fromJson(Map json) {
>     return Restaurant(
>       name: json['name'],
>       imagePath: json['imagePath'],
>       discountType: json['discountType'],
>       rating: json['rating'],
>       opensAt: json['opensAt'],
>     );
>   }
> }
> 
> class ListPage extends StatefulWidget {
>   ListPage({Key key, this.title}) : super(key: key);
> 
>   final String title;
> 
>   @override
>   _ListPageState createState() => _ListPageState();
> }
> 
> class _ListPageState extends State {
>   List restaurants;
> 
>   @override
>   void initState() {
>     restaurants = getRestaurants();
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     Container makeList(Restaurant restaurant) => Container(
>           child: Column(
>             crossAxisAlignment: CrossAxisAlignment.start,
>             children: [
>               Stack(
>                 children: [
>                   Image.network(restaurant.imagePath),
>                   Positioned(
>                     child: restaurant.discountType == 25
>                         ? Icon(Icons.ac_unit)
>                         : Icon(Icons.access_alarm),
>                     top: 30.0,
>                   )
>                 ],
>               ),
>               Padding(
>                 padding: const EdgeInsets.all(14.0),
>                 child: Text(restaurant.name),
>               )
>             ],
>           ),
>         );
> 
>     Card makeCard(Restaurant restaurant) => Card(
>           elevation: 8.0,
>           margin: new EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
>           child: Container(
>             child: makeList(restaurant),
>           ),
>         );
> 
>     final makeBody = Scrollbar(
>       child: ListView.builder(
>         scrollDirection: Axis.vertical,
>         itemCount: restaurants.length,
>         itemBuilder: (BuildContext context, int index) {
>           if (index == 0) // if it's the first position show list title
>           {
>             return Padding(
>               padding: EdgeInsets.all(10),
>               child: Text(
>                 'Title before ListView',
>                 style: TextStyle(
>                     color: Colors.blueGrey[800],
>                     fontFamily: 'monospace',
>                     fontWeight: FontWeight.w600),
>               ),
>             );
>           } else {
>             // after list title display items
>             index = index - 1;
>             return makeCard(restaurants[index]);
>           }
>         },
>       ),
>     );
> 
>     final topAppBar = AppBar(
>       elevation: 0.1,
>       title: Text(widget.title),
>       actions: [
>         IconButton(
>           icon: Icon(Icons.list),
>           onPressed: () {},
>         )
>       ],
>     );
> 
>     return Scaffold(
>       appBar: topAppBar,
>       body: makeBody,
>     );
>   }
> }
> 
> List getRestaurants() {
>   var jsonData = [
>     {
>       "name": "Rockers Club",
>       "imagePath":
>           'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
>       "discountType": 50,
>       "rating": 3.2,
>       "opensAt": '10.30 AM'
>     },
>     {
>       "name": "Numa Clora",
>       "imagePath":
>           'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
>       "discountType": 25,
>       "rating": 4.3,
>       "opensAt": '09.30 AM'
>     },
>     {
>       "name": "North Clubbers",
>       "imagePath":
>           'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
>       "discountType": 50,
>       "rating": 2.1,
>       "opensAt": '10.00 AM'
>     },
>   ];
> 
>   //this will map each json object restaurant and convert it to an object class restaurant and return a list of that.
>   return jsonData
>       .map((eachJsonRestaurant) => Restaurant.fromJson(eachJsonRestaurant))
>       .toList();
> 
>   /* Old Data Ignore.
>   return [
>     Restaurant(
>         name: 'Rockers Club',
>         imagePath:
>         'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
>         discountType: 50,
>         rating: 3.2,
>         opensAt: '10.30 AM'),
>     Restaurant(
>         name: 'Numa Clora',
>         imagePath:
>         'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
>         discountType: 25,
>         rating: 4.3,
>         opensAt: '09.30 AM'),
>     Restaurant(
>         name: 'North Clubbers',
>         imagePath:
>         'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
>         discountType: 50,
>         rating: 21,
>         opensAt: '10.00 AM')
>   ];*/
> }

Bader,

Thank you for the JSON part. But the view is not what I want to achieve. 

I want the text 'Title before listiew' to stay there while the restaurant card scrolls. In your code it doesn't stay.

Also, your card lists only restaurants.length - 1 cards (that is 2 cards in this case)

Will you try once more?

**Comment by BaderEddineOuaich** [comment]
Hello there, 
with my pleasure!
<pre>
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(primaryColor: Colors.white, fontFamily: 'Raleway'),
      home: new ListPage(title: 'Restaurants'),
    );
  }
}

class Restaurant {
  String name;
  String imagePath;
  int discountType;
  double rating;
  String opensAt;

  Restaurant(
      {this.name,
      this.imagePath,
      this.discountType,
      this.rating,
      this.opensAt});

  // this will parse json data to your class data and return a class object.
  factory Restaurant.fromJson(Map<String, dynamic> json) {
    return Restaurant(
      name: json['name'],
      imagePath: json['imagePath'],
      discountType: json['discountType'],
      rating: json['rating'],
      opensAt: json['opensAt'],
    );
  }
}

class ListPage extends StatefulWidget {
  ListPage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _ListPageState createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  List restaurants;

  @override
  void initState() {
    restaurants = getRestaurants();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Container makeList(Restaurant restaurant) => Container(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Stack(
                children: <Widget>[
                  Image.network(restaurant.imagePath),
                  Positioned(
                    child: restaurant.discountType == 25
                        ? Icon(Icons.ac_unit)
                        : Icon(Icons.access_alarm),
                    top: 30.0,
                  )
                ],
              ),
              Padding(
                padding: const EdgeInsets.all(14.0),
                child: Text(restaurant.name),
              )
            ],
          ),
        );

    Card makeCard(Restaurant restaurant) => Card(
          elevation: 8.0,
          margin: new EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
          child: Container(
            child: makeList(restaurant),
          ),
        );

    final makeBody = Container(
      child: Column(
        children: <Widget>[
          Padding(
            padding: EdgeInsets.all(5),
            child: Text(
              'Title before ListView',
              style: TextStyle(
                  color: Colors.blueGrey[800],
                  fontFamily: 'monospace',
                  fontWeight: FontWeight.w600),
            ),
          ),
          Expanded(
              child: ListView.builder(
            scrollDirection: Axis.vertical,
            itemCount: restaurants.length,
            itemBuilder: (BuildContext context, int index) {
              return makeCard(restaurants[index]);
            },
          )),
        ],
      ),
    );
    final topAppBar = AppBar(
      elevation: 0.1,
      title: Text(widget.title),
      actions: <Widget>[
        IconButton(
          icon: Icon(Icons.list),
          onPressed: () {},
        )
      ],
    );

    return Scaffold(
      appBar: topAppBar,
      body: makeBody,
    );
  }
}

List getRestaurants() {
  var jsonData = [
    {
      "name": "Rockers Club",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_8-Henley-600x400.jpg',
      "discountType": 50,
      "rating": 3.2,
      "opensAt": '10.30 AM'
    },
    {
      "name": "Numa Clora",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/RestaurantArchitects_Denver_9-Cochino-Taco-600x400.jpg',
      "discountType": 25,
      "rating": 4.3,
      "opensAt": '09.30 AM'
    },
    {
      "name": "North Clubbers",
      "imagePath":
          'https://www.denverarchitects.org/wp-content/uploads/2018/01/Webp.net-compress-image-600x400.jpg',
      "discountType": 50,
      "rating": 2.1,
      "opensAt": '10.00 AM'
    },
  ];

  //this will map each json object restaurant and convert it to an object class restaurant and return a list of that.
  return jsonData
      .map((eachJsonRestaurant) => Restaurant.fromJson(eachJsonRestaurant))
      .toList();
}

</pre>

if there is anything else i'll be very happy to help.

**Comment by tomkochi** [comment]
That worked. Perfect. Thank you very much Baber. I am very new to Flutter. No Android or iOS experience. Thank you.
