### ISSUE TITLE
Navigator.push() with Arguments

### ISSUE THREAD

**Issue by DeRealMorgan** [flutter/flutter#31899]
My goal is to push a new `Route` with arguments. This is currently only achievable by calling `Navigator.pushNamed()` which requires you to define the `Routes` in the `MaterialApp`.
For consistency and simplicity it would be nice to have an optional parameter "arguments".

`push()` at the moment:
```
  static Future<T> push<T extends Object>(BuildContext context, Route<T> route) {
    return Navigator.of(context).push(route);
  }
```

`pushNamed()` at the moment:
```
  static Future<T> pushNamed<T extends Object>(
    BuildContext context,
    String routeName, {
    Object arguments,
   }) {
    return Navigator.of(context).pushNamed<T>(routeName, arguments: arguments);
  }
```

Suggestion:
Change the `push()` to work with an argument parameter

```
static Future<T> push<T extends Object>(
    BuildContext context,
    Route<T> route, {
    Object arguments,
   }) {
    return Navigator.of(context).push(route, arguments: arguments);
  }
```

**Comment by pedromassangocode** [comment]
Hi @DeRealMorgan 
What is the use case for this that the `Navigator.of(context).push(route)` can't handle?

I mean, you have the option to pass the arguments directly in the widget that you are about to push:

```dart
    Navigator.of(context).push(MaterialPageRoute(builder: (context) {
      return MyPage2(arguments: myArgs);
    }));
```

Does that works for you?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
