### ISSUE TITLE
Flutter local asset files caching

### ISSUE THREAD

**Issue by YoboZorle** [flutter/flutter#31893]
## Use case
Whenever you open a flutter app local asset images tend to delay before showing, my findings shows that flutter does not cache local asset files like images before app loads.

This happens on both android and ios every time you open the app.

## Proposal
I strongly suggest flutter integrates local asset caching to the framework as it boots user experience.

**Comment by andrewkolos** [comment]
Closing this issue since it's vague and has gone stale.
