### ISSUE TITLE
google_maps_flutter call on moveCamera not triggering GoogleMap.onCameraMove

### ISSUE THREAD

**Issue by fatalcaron** [flutter/flutter#31907]
When calling the function moveCamera, the onCameraMove is not triggering.
Everything fine when we use the map gesture but not with the moveCamera function.

**Comment by minh98** [comment]
let show log console,doctor -v, code or something similar

**Comment by fatalcaron** [comment]
The map widget look like this:
```
@override
void initState() {
  super.initState();

  this.mapBloc = BlocProvider.of<MapBloc>(context);

  this._initialCameraPosition = this.mapBloc.cameraPosition$.hasValue
      ? this.mapBloc.cameraPosition$.value
      : widget.cameraPosition;

  this._mapType = widget.mapType is MapType ? widget.mapType : MapType.normal;
}

@override
Widget build(BuildContext context) {
  return GoogleMap(
    initialCameraPosition: this._initialCameraPosition,
    mapType: this._mapType,
    onMapCreated: this.mapBloc.onMapCreated,
    onCameraMove: this.mapBloc.updateCameraPosition,
  );
}
```

My map logic in another class, look like:
```
class MapBloc implements BlocBase {
  GoogleMapController controller;
  Completer<bool> isReady$ = Completer();

  BehaviorSubject<CameraPosition> cameraPosition$ = BehaviorSubject();

  void onMapCreated(GoogleMapController controller) {
    this.controller = controller;
    Future.delayed(Duration(milliseconds: 100))
        .then((onValue) => this.isReady$.complete(true));
  }

  void updateCameraPosition(CameraPosition position) {
    print('Camera move');
    this.cameraPosition$.sink.add(position);
  }

  @override
  void dispose() {
    this.cameraPosition$.close();
  }
}
```

Flutter doctor -v :

> [√] Flutter (Channel beta, v1.5.4, on Microsoft Windows [Version 10.0.17763.437], locale en-CA)
>     • Flutter version 1.5.4 at C:\flutter
>     • Framework revision b593f5167b (9 days ago), 2019-04-22 07:51:33 -0700
>     • Engine revision ca31a7c57b
>     • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Android\android-sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = C:\Android\android-sdk
>     • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
>     • All Android licenses accepted.
> 
> [!] Android Studio (version 2.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     X Unable to find bundled Java version.
>     • Try updating or re-installing Android Studio.
> 
> [!] Android Studio (version 3.1)
>     • Android Studio at C:\Program Files\Android\Android Studio1
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
> 
> [√] VS Code (version 1.33.1)
>     • VS Code at C:\Users\Alex\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 2.26.0
> 
> [√] Connected device (1 available)
>     • SM G950W • 988ad836334b4d5336 • android-arm64 • Android 9 (API 28)

**Comment by minh98** [comment]
Where is your moveCamera function

**Comment by minh98** [comment]
Initcameraposition only can set one time

**Comment by minh98** [comment]
Try use controller to jump to new position.
Your mapbloc is seem don't have feature jump to new position

**Comment by fatalcaron** [comment]
I made a simpler example, to illustrate this issue.

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapPage extends StatefulWidget {
  @override
  MapPageState createState() => MapPageState();
}

class MapPageState extends State<MapPage> {
  GoogleMapController _controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Carte'),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(45.5, -71),
          zoom: 10,
        ),
        onMapCreated: this._setMapController,
        onCameraMove: (cameraPosition) => print('MAPPP MOVEEE: $cameraPosition'),
      ),
    );
  }

  void _setMapController(GoogleMapController controller) {
    this._controller = controller;

    Future.delayed(Duration(milliseconds: 3000)).then((onValue) =>
        controller.moveCamera(CameraUpdate.newLatLngZoom(LatLng(50, -71), 12)));
  }
}

```

**Comment by BondarenkoStas** [comment]
@fatalcaron is it still in google_maps_flutter 0.5.21+7?

**Comment by peterweb2005** [comment]
same

**Comment by smasinde** [comment]
> I made a simpler example, to illustrate this issue.
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:google_maps_flutter/google_maps_flutter.dart';
> 
> class MapPage extends StatefulWidget {
>   @override
>   MapPageState createState() => MapPageState();
> }
> 
> class MapPageState extends State<MapPage> {
>   GoogleMapController _controller;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Carte'),
>       ),
>       body: GoogleMap(
>         initialCameraPosition: CameraPosition(
>           target: LatLng(45.5, -71),
>           zoom: 10,
>         ),
>         onMapCreated: this._setMapController,
>         onCameraMove: (cameraPosition) => print('MAPPP MOVEEE: $cameraPosition'),
>       ),
>     );
>   }
> 
>   void _setMapController(GoogleMapController controller) {
>     this._controller = controller;
> 
>     Future.delayed(Duration(milliseconds: 3000)).then((onValue) =>
>         controller.moveCamera(CameraUpdate.newLatLngZoom(LatLng(50, -71), 12)));
>   }
> }
> ```



> void _setMapController(GoogleMapController controller) {
>     this._controller = controller;
> 
>     Future.delayed(Duration(milliseconds: 3000)).then((onValue) =>
>         controller.moveCamera(CameraUpdate.newLatLngZoom(LatLng(50, -71), 12)));
>   }

void _moveToCurrentLocation() async {
      final GoogleMapController controller = await _controller.future;
      ....
}

This works for me. You are mutating your context instead of passing it to your local variable. async/await is good too 👍🏾

**Comment by chornbe** [comment]
1) @smasinde , how does that not crash when currentLocation is null?

2) I'd love a little more granular control over when a user drag and/or an animateCamera(...) call does or does not fire the event. It's getting in my way blindly firing equally on both without some way to identify which happened. :(

**Comment by smasinde** [comment]
@chornbe in my code, sometihng like... currentlocation == null  ? <loading> : <GoogleMap>

**Comment by darshankawar** [comment]
@fatalcaron 
Using the code sample you shared [earlier](https://github.com/flutter/flutter/issues/31907#issuecomment-488356590), I verified on latest master and using latest plugin version using which, I see the `onCameraMove` function being called properly, as below:

```
Syncing files to device iPhone 12 Pro Max...
Restarted application in 472ms.
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(45.499999958996106, -71.00000012665988), tilt: 0.0, zoom: 10.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.99999997884885, -71.00000012665988), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.9992644330179, -70.99645256996155), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.99573331153425, -70.984893925488), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.991833991787466, -70.97230531275272), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.98911175976842, -70.96360791474581), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.98638915808824, -70.95548249781132), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.98557989269137, -70.95285058021545), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.98550616565193, -70.95239259302616), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.984475915462596, -70.94987500458956), tilt: 0.0, zoom: 12.0)
flutter: MAPPP MOVEEE: CameraPosition(bearing: 0.0, target: LatLng(49.9776320279077, -70.93568410724401), tilt: 0.0, zoom: 12.0) 
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (10 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```

</details>

I am going ahead and closing this as fixed and working as expected. If you disagree, write in comments and I'll reopen it.
Thanks.
