### ISSUE TITLE
IconButton ink splash should use the color of the button

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3190]
IconButton's ink splash should use the color of the button for drawing the ink splash. See current behavior vs spec below.

Test case in: /examples/material_gallery/lib/demo/buttons_demo.dart

![flutter_04](https://cloud.githubusercontent.com/assets/1539812/14367224/9f3e02fc-fccb-11e5-9a03-f70782d89aca.png)

Spec:
<img width="758" alt="screen shot 2016-04-07 at 2 07 04 pm" src="https://cloud.githubusercontent.com/assets/1539812/14367230/a50573f0-fccb-11e5-8fbd-e4cff92d5c85.png">

**Comment by abarth** [comment]
Is this only for icon buttons or does this affect other sorts of material buttons?

**Comment by vlidholt** [comment]
I've only seen it for the icon buttons

**Comment by Hixie** [comment]
that picture is toggle buttons, not icon buttons. we don't yet implement those. I actually haven't found spec text for icon buttons per se.

**Comment by Hixie** [comment]
I am closing this on the basis that I cannot support the claim presented, as noted above.
