### ISSUE TITLE
Chip child widgets not laying out correctly if Chip's parent is constrained

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#31914]
Currently, if a `Chip`'s parent is constrained, its contents may layout outside of parent's constraints. The tests that currently check for constraints only compare the `label`'s width and height being smaller than or equal to the `Chip`'s width and height, and not the positioning of the items.

![chip_layout](https://user-images.githubusercontent.com/27032613/57028837-f8b03300-6bf4-11e9-9baf-06019a60c07e.png)

I think two questions need to be addressed:
1. Determine what to do in the event that a `Chip`'s parent constraints are too small for the proper layout of the chip, since it has to adhere to the Material design specifications.
2. Update the tests accordingly to verify the corrected layout behavior.

Sample code exhibiting layout behavior: 
```
import 'package:flutter/material.dart';

void main() {
  const double labelWidth = 100.0;
  const double labelHeight = 60.0;
  const double chipParentWidth = 75.0;
  const double chipParentHeight = 32.0;

  return runApp(
    MaterialApp(
      home: Material(
        child: Center(
          child: Container(
            color: Colors.amber,
            width: chipParentWidth,
            height: chipParentHeight,
            child: Chip(
              label: Container(
                decoration: BoxDecoration(color: Colors.green),
                width: labelWidth,
                height: labelHeight,
              ),
            ),
          ),
        ),
      ),
    ),
  );
}
```

`chip_test.dart`
```
  final Size labelSize = tester.getSize(find.byKey(labelKey));
  expect(labelSize.width, lessThan(chipParentWidth));
  expect(labelSize.height, lessThanOrEqualTo(chipParentHeight));

  final Size chipSize = tester.getSize(find.byType(Chip));
  expect(chipSize.width, chipParentWidth);
  expect(chipSize.height, chipParentHeight);
```

**Comment by Hixie** [comment]
I'm tempted to say that if the label is too big, that's just a misuse of the widget. The material specs seem to only expect text there.
