### ISSUE TITLE
[documentation] provide clearer info about AspectRatio requirements

### ISSUE THREAD

**Issue by LinusU** [flutter/flutter#31911]
I ran into something that I found quite unexpecting when trying to play a video in the background, covering the entire device.

Too me, it seems like a `FittetBox(fit: BoxFit.cover)` with a `AspectRatio()` would be a prefect fit. But unfortunately, they don't really work together. Here was the full tree of my first attempt:

```dart
FittetBox(
  fit: BoxFit.cover,
  child: AspectRatio(
    aspectRatio: 750 / 1624,
    child: VideoPlayer(),
  ),
),
```

`VideoPlayer` here is from the [`video_player` package](https://pub.dartlang.org/packages/video_player), but could be any widget that just draws on whatever size they get, not imposing any constraints themselves.

I _think_ that the problem here is that the `FittedBox` will try to layout it's child, then look at the width and height, and scale that while maintaining an aspect ration to fit the box.

What I would really like in this case though, is to just read the aspect ratio from the `AspectRatio` child, and then calculate the appropriate width and height from that.

Would it make sense to have a special case in `FittedBox` for `AspectRatio`, or is this just not how it's supposed to work? 🤔 

-----

For anyone facing the same problem, it can be solved by replacing `AspectRatio(aspectRatio: 750 / 1624)` with `SizedBox(width: 750, height: 1624)`. The `SizedBox` will be scaled to the correct size, while maintaining the aspect ratio.

## Steps to Reproduce

1. Put the above code into a flutter app
2. Add a video controller with any video file
3. Run app and watch results

## Logs

```
Analyzing flutter...                                                    
No issues found! (ran in 4.0s)
```

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.5.8 at /Users/linus/coding/flutter
    • Framework revision 0ba67226ee (7 days ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Linus Unnebäck’s iPhone • f94aa6361e142ab9641a700b2eb487e8611738f4 • ios • iOS 12.2

• No issues found!
```

**Comment by rostopira** [comment]
This issue happens on current master as well (1.5.9-pre.217)
Error log:
```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: RenderAspectRatio has unbounded constraints.
flutter: This RenderAspectRatio was given an aspect ratio of 0.5625 but was given both unbounded width and
flutter: unbounded height constraints. Because both constraints were unbounded, this render object doesn't
flutter: know how much size to consume.
```
My code snippet is similar:
```dart
          RotatedBox(
            quarterTurns: connection.rotation,
            child: FittedBox(
              fit: BoxFit.fitWidth,
              child: AspectRatio(
                child: Texture(
                  key: textureKey,
                  textureId: connection.renderer.textureId,
                ),
                aspectRatio: _aspect,
              ),
            ),
          ),
```

**Comment by Rohan-Doshi** [comment]
I had similar issue using AspectRatio inside a Card. Wrapping it in a ConstrainedBox helped he define the required unbounded width and height constraints.

**Comment by Xgamefactory** [comment]
dont google pay for flutter support team ? )
the project goes down without lack of support and tons of issues. no one cares many "cool" videos marketing stuffs if support abandoned.

**Comment by softronaut** [comment]
I'm facing exactly same problem. Looking for a solution.

**Comment by kenwen** [comment]
There's a workaround that feels a bit hacky, wrap everything in a column and the aspectratio in an expanded

**Comment by chanyut** [comment]
I solved this issue by using LayoutBuilder to get constraint maxWidth, and height, then place videoPlayer inside overflowBox and container. and calculate its width, and height by video aspect ratio. 

```
Container(
    color: Colors.black,
    child: OverflowBox(
        maxWidth: double.infinity,
        maxHeight: double.infinity,
        child: FittedBox(
            fit: BoxFit.fitHeight,
            child: Container(
                width: constraints.maxHeight *
                    _videoPlayerController
                        .value.aspectRatio,
                height: constraints.maxHeight,
                child: VideoPlayer(
                    _videoPlayerController)))))
```

**Comment by szotp** [comment]
```dart
return FittedBox(
      fit: BoxFit.cover,
      child: SizedBox(
        width: aspectRatio,
        height: 1,
        child: QRReaderPreview(controller),
      ),
    );
```
This worked for me, not sure why.

**Comment by BondarenkoStas** [comment]
@LinusU is it the same with current flutter stable?

**Comment by tiagofischer** [comment]
My solution, similar to chanyut's solution:
```dart
LayoutBuilder(
  builder: (context, constraints) {
    return SizedBox.expand(
      child: FittedBox(
        fit: BoxFit.cover,
        child: SizedBox(
          width:
              constraints.maxWidth * controller.value.aspectRatio,
          height: constraints.maxHeight,
          child: CameraPreview(controller),
        ),
      ),
    );
  },
);
```

**Comment by premingiet** [comment]
I am facing the same issue now. I tried putting flutter_videoplayer inside fittedBox widget with fit type contain, but video is rendered outside the bounds of a fittedbox

**Comment by takuro-kira** [comment]
```
FittetBox(
  fit: BoxFit.cover,
  child: AspectRatio(
    aspectRatio: aspectRatio,
    child: Container(color: Colors.red),
  ),
)
```
Container become same problem.
It's not VideoPlayer issue. But I hope VideoPlayer support fit property.

I happened to find the next approach.
VideoPlayer inside SingleChildScrollView behave BoxFit.cover.

So I set up the process as follows.
Get the area size with LayoutBuilder, Disable scrolling and centering.
```
  LayoutBuilder(
    builder: (BuildContext context, BoxConstraints constraints) {
      var videoAspect = _controller.value.size.width / _controller.value.size.height;
      var viewAspect = constraints.maxWidth / constraints.maxHeight;
      var offset = 0.0;
      if (videoAspect < viewAspect) {
        offset = ((constraints.maxWidth / videoAspect) - constraints.maxHeight) / 2;
      }
      _scrollController = ScrollController(initialScrollOffset: offset, keepScrollOffset: true);
      return SingleChildScrollView(
      physics: NeverScrollableScrollPhysics(),
        controller: _scrollController,
        child: AspectRatio(
          aspectRatio: _controller.value.aspectRatio,
          child: VideoPlayer(_controller),
        ),
      );
    },
  ),
```

This is not a good way but it works my case.

**Comment by takuro-kira** [comment]
I lacked understanding OverflowBox.

To display as it is, specify both maxWidth and maxHeight.

If overflow vertically and display as BoxFit.cover, specify maxHeight infinity.
```
OverflowBox(
  maxHeight: double.infinity,
  alignment: Alignment.center, // center is default
  child: AspectRatio(
    aspectRatio: aspectRatio,
    child: Container(color: Colors.red),
  ),
);
```

In VideoPlayer sample
```
FutureBuilder(
  future: _controller.initialize(),
  builder: (BuildContext context, _) {
    _controller.play();
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        final aspect = constraints.maxWidth / constraints.maxHeight;
        return OverflowBox(
          maxHeight: aspect > _controller.value.aspectRatio ? double.infinity : null,
          maxWidth: aspect < _controller.value.aspectRatio ? double.infinity : null,
          child: AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: VideoPlayer(_controller, ),
          ),
        );
      },
    );
  },
);
```

**Comment by yazinsai** [comment]
I was able to get by **without** using a `LayoutBuilder` or querying the screen size:

```dart
    Scaffold(
      body: SizedBox.expand(
        child: FittedBox(
          fit: BoxFit.cover,
          child: SizedBox(
            child: VideoPlayer(_controller),
          ),
        ),
      ),
```

**Comment by iapicca** [comment]
Hi @LinusU 
[AspectRatio](https://api.flutter.dev/flutter/widgets/AspectRatio-class.html) is expected to have a parent with fixed size;
since [FittedBox](https://api.flutter.dev/flutter/widgets/FittedBox-class.html) doesn't fulfil this requirement,
the former needs to wrapped in a widget that provide a fixed size.

I'd not consider the implementations in the comments a workaround, but a legitimate and correct implementation,
moreover I'm hijacking this issue to provide a clearer statement in the docs about `AspectRatio` requirements
Thank you

**Comment by kgrzesiu** [comment]
This worked for me for covering entire available space:

```
SizedBox.expand(
            child: FittedBox(
              fit: BoxFit.cover,
              child: SizedBox(
                height: _videoController.value.size.height,
                width: _videoController.value.size.width,
                child: VideoPlayer(_videoController),
              ),
            ),
          );
```
