### ISSUE TITLE
Support custom Flutter Driver commands

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#3191]
Flutter Driver should support extending the protocol with user-defined gestures and actions.

**Comment by sethladd** [comment]
Would this make sense as API docs or more of a long-form document on the website?

**Comment by yjbanov** [comment]
Actually, my description is misleading. Fixed.

**Comment by sethladd** [comment]
Thanks. Is this a doc issue, or a feature issue for the tool?

**Comment by yjbanov** [comment]
I sealed the API after I filed this issue to prevent custom extensions until our API is stable enough, so now it's a feature issue. We need to open up the API _just enough_ to allow custom extensions without clobbering the built-in commands that the driver supports out-of-the-box, kind of like the [registerExtension](https://api.dartlang.org/stable/1.22.1/dart-developer/registerExtension.html) from `dart:developer`.

**Comment by sethladd** [comment]
Thanks for the clarification. When you have a chance, please add the appropriate labels for triaging. I removed the "docs" label.

**Comment by yjbanov** [comment]
Done

**Comment by Hixie** [comment]
This is done now.

**Comment by davunderscorei** [comment]
This is marked as "Done", however I cannot see any references to this functionality in `driver.dart` (as of v1.1.8). Can we have clarification whether this feature has been completed or not and point to the documentation if it is please?

**Comment by zoechi** [comment]
I think it was https://docs.flutter.io/flutter/flutter_driver_extension/enableFlutterDriverExtension.html with a `handler` that processes requests from the driver test.
See also https://github.com/flutter/flutter/issues/9002#issuecomment-331508430
