### ISSUE TITLE
Remove `assert`s from Android embedding

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#31928]
/cc @matthew-carroll @mklim 

We've discussed this before - the Android linter says these are unreliable.  I'm now working on a bug that appears to be suffering from this (https://github.com/flutter/flutter/issues/31139).  We have code that asserts the transform we're about to pass isn't null, but this makes me suspect there are many things we're asserting that are never triggered.

We should follow the linter suggestion and use `if (BuildConfig.DEBUG)` instead and make sure we're setting that configuration properly for debug versions of the engine.

**Comment by matthew-carroll** [comment]
@dnfield, agreed. I've brought this up in the past trying to determine whether my understanding that asserts shouldn't exist was correct, or if I was missing something and that these asserts had a place. I never got an answer on that so I tried not to delete them. But if this settles that question then I'd be happy to start replacing them as I come across them in the embedding.

**Comment by dnfield** [comment]
See https://issuetracker.google.com/issues/36988757 for some more details

**Comment by matthew-carroll** [comment]
Are you wanting to migrate all this with one PR, or should I also make these changes progressively?

**Comment by dnfield** [comment]
I'm starting with AccessibilityBridge.java.  There aren't many more than in there, I could do them in one PR unless that will cause merge problems for your embedding patches.

**Comment by matthew-carroll** [comment]
Should be fine.

**Comment by dnfield** [comment]
This is getting hung up on some buildroot related issues right now.  Still looking for either a work around or a fix for buildroot to define the debug constant(s).
