### ISSUE TITLE
Gogle maps Authorization failure  trouble

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#31924]
done everything as described here https://pub.dartlang.org/packages/google_maps_flutter

getting error.
maps just shown with google logo at the left bottom corner no tiles visible.

map apis also enabled correctly.

tried workaround here still same error.

https://stackoverflow.com/questions/35164918/android-google-maps-android-api-authorization-failure

```
E/Google Maps Android API(29224): Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
E/Google Maps Android API(29224): In the Google Developer Console (https://console.developers.google.com)
E/Google Maps Android API(29224): Ensure that the "Google Maps Android API v2" is enabled.
E/Google Maps Android API(29224): Ensure that the following Android Key exists:
E/Google Maps Android API(29224): 	API Key: YOUR API KEY
E/Google Maps Android API(29224): 	Android Application (<cert_fingerprint>;<package_name>): 43:F8:54:57:5C:C8:95:02:21:FD:56:84:66:BB:F1:0D:28:94:13:34;com.example.login
W/DynamiteModule(29224): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(29224): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule(29224): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/m.example.logi(29224): Unsupported class loader
W/m.example.logi(29224): Verification of void q.c() took 177.939ms

```

flutter doctor => no errors

also tried uninstall and reinstall.

```
 <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="login"
        android:icon="@mipmap/ic_launcher">
        <meta-data 
            android:name="com.google.android.geo.API_KEY"
            android:value="***********************"/>
```

**Comment by BondarenkoStas** [comment]
@Xgamefactory did you manage to solve it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by sgehrman** [comment]
Same issue, maps was working for weeks, now it crashes my app.  Why would you crash the app?  Why not put a message in the console so I know what's wrong?

**Comment by iapicca** [comment]
@sgehrman 
can you please open a new issue providing 
your `flutter doctor -v`, your `pubspec.yaml`, your `flutter run --release -v` and a minimal reproducible code sample
