### ISSUE TITLE
Unable to run devicelab tests - VM Service not ready yet

### ISSUE THREAD

**Issue by athornz** [flutter/flutter#31932]
## Steps to Reproduce

I'm attempting to run Flutter tool devicelab tests locally, but all tests fail to run.

Command: `../../bin/cache/dart-sdk/bin/dart bin/run.dart -t module_test`

Machine details:

* Macbook pro 2018
* MacOS Mojave 10.14.4

## Logs
Error log:

```
═════════════════════╡ ••• Running task "module_test" ••• ╞═════════════════════


Executing: /Users/user/dev/flutter/dev/devicelab/../../bin/cache/dart-sdk/bin/dart --enable-vm-service=0 --no-pause-isolates-on-exit bin/tasks/module_test.dart
[module_test] [STDOUT] Observatory listening on http://127.0.0.1:60159/Tnt_anXpvpM=/
VM service not ready yet: JSON-RPC error -32601 (method not found): Method not found
Will retry in 0:00:00.200000.
[module_test] [STDOUT] Running task.
[module_test] [STDOUT]
[module_test] [STDOUT]
[module_test] [STDOUT] ══════════════════╡ ••• Checking running Dart processes ••• ╞═══════════════════
[module_test] [STDOUT]
[module_test] [STDOUT] Cleaning up after task...


Cleaning up system after task...

Executing: /Users/user/dev/flutter/dev/devicelab/../../bin/flutter doctor -v
"/Users/user/dev/flutter/dev/devicelab/../../bin/cache/dart-sdk/bin/dart" exit code: -9
stdout: [✓] Flutter (Channel unknown, v1.5.9-pre.100, on Mac OS X 10.14.4 18E226, locale en-AU)
stdout:     • Flutter version 1.5.9-pre.100 at /Users/user/dev/flutter
stdout:     • Framework revision 7690bb47dc (22 minutes ago), 2019-05-01 13:46:36 -0700
stdout:     • Engine revision 6280d42669
stdout:     • Dart version 2.3.0 (build 2.3.0-dev.0.5 5fbf7720f8)
stdout:
stdout: [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
stdout:     • Android SDK at /Users/user/dev/android-sdk
stdout:     • Android NDK location not configured (optional; useful for native profiling support)
stdout:     • Platform android-28, build-tools 28.0.3
stdout:     • ANDROID_HOME = /Users/user/dev/android-sdk
stdout:     • Java binary at: /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/183.5452501/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout:     • All Android licenses accepted.
stdout:
stdout: [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
stdout:     • Xcode at /Applications/Xcode.app/Contents/Developer
stdout:     • Xcode 10.2.1, Build version 10E1001
stdout:     • ios-deploy 1.9.4
stdout:     • CocoaPods version 1.6.1
stdout:
stdout: [!] Android Studio (version 3.4)
stdout:     • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/183.5452501/Android Studio.app/Contents
stdout:     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
stdout:     ✗ Dart plugin not installed; this adds Dart specific functionality.
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout:
stdout: [!] Android Studio (version 3.4)
stdout:     • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/183.5400832/Android Studio.app/Contents
stdout:     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
stdout:     ✗ Dart plugin not installed; this adds Dart specific functionality.
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout:
stdout: [!] Android Studio
stdout:     • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5487692/Android Studio 3.5 Preview.app/Contents
stdout:     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
stdout:     • Dart plugin version 183.5901
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
stdout:
stdout: [✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
stdout:     • IntelliJ at /Users/user/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
stdout:     • Flutter plugin version 35.0.3
stdout:     • Dart plugin version 191.7141.2
stdout:
stdout: [!] VS Code (version 1.29.0)
stdout:     • VS Code at /Applications/Visual Studio Code.app/Contents
stdout:     ✗ Flutter extension not installed; install from
stdout:       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
stdout:
stdout: [✓] Connected device (1 available)
stdout:     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
stdout:
stdout: ! Doctor found issues in 4 categories.
"/Users/user/dev/flutter/dev/devicelab/../../bin/flutter" exit code: 0

Telling Gradle to shut down (JAVA_HOME=/Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/183.5452501/Android Studio.app/Contents/jre/jdk/Contents/Home)

Executing: chmod a+x /var/folders/dy/pmh99r_51_zf07ptfdwgdybr0000gn/T/flutter_devicelab_shutdown_gradle.sDh8Gz/gradlew
"chmod" exit code: 0

Executing: /var/folders/dy/pmh99r_51_zf07ptfdwgdybr0000gn/T/flutter_devicelab_shutdown_gradle.sDh8Gz/gradlew --stop
stdout: No Gradle daemons are running.
"/var/folders/dy/pmh99r_51_zf07ptfdwgdybr0000gn/T/flutter_devicelab_shutdown_gradle.sDh8Gz/gradlew" exit code: 0


Unhandled exception:
JSON-RPC error -32000: Server error
package:json_rpc_2/src/client.dart 110:64              Client.sendRequest
package:json_rpc_2/src/peer.dart 79:15                 Peer.sendRequest
package:vm_service_client/src/scope.dart 64:23         Scope.sendRequestRaw
===== asynchronous gap ===========================
package:vm_service_client/src/isolate.dart 361:19      VMIsolateRef.invokeExtension
package:flutter_devicelab/framework/runner.dart 72:23  runTask
===== asynchronous gap ===========================
bin/run.dart 60:47                                     main
===== asynchronous gap ===========================
dart:isolate-patch/isolate_patch.dart 298:32           _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 171:12           _RawReceivePortImpl._handleMessage
```

**Comment by jonahwilliams** [comment]
I don't believe these tests work on emulators

**Comment by linxuebin1990** [comment]
> on
i have the sam problem, not on emulators

`Unhandled exception:
JSON-RPC error -32000: Server error
package:json_rpc_2/src/client.dart 110:64              Client.sendRequest
package:json_rpc_2/src/peer.dart 68:15                 Peer.sendRequest
package:vm_service_client/src/scope.dart 64:23         Scope.sendRequestRaw
===== asynchronous gap ===========================
package:vm_service_client/src/isolate.dart 361:19      VMIsolateRef.invokeExtension
package:flutter_devicelab/framework/runner.dart 72:23  runTask
===== asynchronous gap ===========================
bin/run.dart 60:47                                     main
===== asynchronous gap ===========================
dart:isolate-patch/isolate_patch.dart 298:32           _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 171:12           _RawReceivePortImpl._handleMessage
`

`stdout: [✓] Flutter (Channel tt_dev_1.5.4, v1.5.4-hotfix.3-pre.20, on Mac OS X 10.14.3 18D42, locale zh-Hans-CN)
stdout:     • Flutter version 1.5.4-hotfix.3-pre.20 at /Users/linxuebin/MyProject/bdFlutter
stdout:     • Framework revision 1306e02629 (4 weeks ago), 2019-06-30 15:25:20 +0800
stdout:     • Engine revision 52c7a1e849
stdout:     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
stdout: 
stdout: [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
stdout:     • Android SDK at /Users/linxuebin/Library/Android/sdk/
stdout:     • Android NDK location not configured (optional; useful for native profiling support)
stdout:     • Platform android-29, build-tools 29.0.1
stdout:     • ANDROID_HOME = /Users/linxuebin/Library/Android/sdk/
stdout:     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout:     • All Android licenses accepted.
stdout: 
stdout: [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
stdout:     • Xcode at /Applications/Xcode.app/Contents/Developer
stdout:     • Xcode 10.2.1, Build version 10E1001
stdout:     • ios-deploy 1.9.4
stdout:     • CocoaPods version 1.5.3
stdout: 
stdout: [✓] Android Studio (version 3.4)
stdout:     • Android Studio at /Applications/Android Studio.app/Contents
stdout:     • Flutter plugin version 37.1.1
stdout:     • Dart plugin version 183.6270
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout: 
stdout: [!] VS Code (version 1.36.1)
stdout:     • VS Code at /Applications/Visual Studio Code.app/Contents
stdout:     ✗ Flutter extension not installed; install from
stdout:       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
stdout: 
stdout: [✓] Connected device (2 available)
stdout:     • MI 9 SE • 3b787abd                                 • android-arm64 • Android 9 (API 28)
stdout:     • it45440 • adf620572e680325bb60ce3cff786c79a889ed85 • ios           • iOS 10.3.1`

**Comment by linxuebin1990** [comment]
> I don't believe these tests work on emulators

Unhandled exception:
JSON-RPC error -32000: Server error
package:json_rpc_2/src/client.dart 110:64              Client.sendRequest
package:json_rpc_2/src/peer.dart 68:15                 Peer.sendRequest
package:vm_service_client/src/scope.dart 64:23         Scope.sendRequestRaw
===== asynchronous gap ===========================
package:vm_service_client/src/isolate.dart 361:19      VMIsolateRef.invokeExtension
package:flutter_devicelab/framework/runner.dart 72:23  runTask
===== asynchronous gap ===========================
bin/run.dart 60:47                                     main
===== asynchronous gap ===========================
dart:isolate-patch/isolate_patch.dart 298:32           _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 171:12           _RawReceivePortImpl._handleMessage


"/Users/linxuebin/MyProject/bdFlutter/dev/devicelab/../../bin/cache/dart-sdk/bin/dart" exit code: -9
stdout: [✓] Flutter (Channel tt_dev_1.5.4, v1.5.4-hotfix.3-pre.20, on Mac OS X 10.14.3 18D42, locale zh-Hans-CN)
stdout:     • Flutter version 1.5.4-hotfix.3-pre.20 at /Users/linxuebin/MyProject/bdFlutter
stdout:     • Framework revision 1306e02629 (4 weeks ago), 2019-06-30 15:25:20 +0800
stdout:     • Engine revision 52c7a1e849
stdout:     • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
stdout: 
stdout: [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
stdout:     • Android SDK at /Users/linxuebin/Library/Android/sdk/
stdout:     • Android NDK location not configured (optional; useful for native profiling support)
stdout:     • Platform android-29, build-tools 29.0.1
stdout:     • ANDROID_HOME = /Users/linxuebin/Library/Android/sdk/
stdout:     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout:     • All Android licenses accepted.
stdout: 
stdout: [✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
stdout:     • Xcode at /Applications/Xcode.app/Contents/Developer
stdout:     • Xcode 10.2.1, Build version 10E1001
stdout:     • ios-deploy 1.9.4
stdout:     • CocoaPods version 1.5.3
stdout: 
stdout: [✓] Android Studio (version 3.4)
stdout:     • Android Studio at /Applications/Android Studio.app/Contents
stdout:     • Flutter plugin version 37.1.1
stdout:     • Dart plugin version 183.6270
stdout:     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
stdout: 
stdout: [!] VS Code (version 1.36.1)
stdout:     • VS Code at /Applications/Visual Studio Code.app/Contents
stdout:     ✗ Flutter extension not installed; install from
stdout:       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
stdout: 
stdout: [✓] Connected device (2 available)
stdout:     • MI 9 SE • 3b787abd                                 • android-arm64 • Android 9 (API 28)
stdout:     • it45440 • adf620572e680325bb60ce3cff786c79a889ed85 • ios           • iOS 10.3.1

**Comment by BondarenkoStas** [comment]
@athornz was it resolved? Do you experience it with current flutter stable or master?

**Comment by linxuebin1990** [comment]
@BondarenkoStas  I found that the operating environment must be in English.

**Comment by BondarenkoStas** [comment]
Fine, then I think it's safe to close the issue, thank you!
