### ISSUE TITLE
Rename foreground and background color in contrast checker to light and dark color

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#31933]
The phrasing is confusing as is, we could even remove the designation entirely...

**Comment by johnsonmh** [comment]
Is it always "light" and "dark" though? What about when the text is light and the background is dark? 

What about `Background` and `Text Color` like is used on this website: https://contrast-ratio.com/#%231a73e8-on-%23e3eefc ?

**Comment by johnsonmh** [comment]
Nevermind, since we can't know in the test what is `background` and what is `text` color, we should stick with `light` and `dark`!
