### ISSUE TITLE
Flutter crashes when pressing the Escape key on a Lenovo Yoga Chromebook

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#31942]
Flutter doctor information:

Doctor summary (to see all details, run flutter doctor -v):[✓] Flutter (Channel beta, v1.5.4-hotfix.1, on Linux, locale en_US.UTF-8)[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)[!] Android Studio (not installed)[✓] VS Code (version 1.33.1)[✓] Connected device (1 available)

ChromeOS version: 73.0.3683.114

Flutter crashes with the following error when the escape key is pressed:

W/EGL-MAIN( 3320): Could not dequeue buffer from native window
F/libc ( 3320): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68 in tid 3337 (1.gpu)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/nami/nami_cheets:7.1.1/R73-11647.154.0/5465689:user/release-keys'
Revision: '0'
ABI: 'x86_64'
pid: 3320, tid: 3337, name: 1.gpu >>> dev.flutter.devRpg <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x68
rax 00007f3a90371320 rbx 0000000000000000 rcx 0000000000000000 rdx 00007f3a989b6600
rsi 00007f3ac0a46070 rdi 0000000000000000
r8 0000000000000001 r9 0000000000000000 r10 00007f3a8e525700 r11 0000000000000001
r12 00007f3ac04dc108 r13 0000000000000000 r14 00007f3aacdd2e78 r15 00007f3ac04d91f0
cs 0000000000000033 ss 000000000000002b
rip 00007f3aacaa251a rbp 00000000ffffffff rsp 00007f3ac0a45ef0 eflags 0000000000010246
backtrace:
#00 pc 000000000042f51a /vendor/lib64/dri/i965_dri.so
Lost connection to device.

**Comment by Hixie** [comment]
cc @cbracken

**Comment by cbracken** [comment]
Our current understanding is that this is a device-specific crasher for the particular Chromebook model in question and that the crasher is very reproducible. @mjohnsullivan has one of these devices that he's promised to let us take a look at next week.

**Comment by Hixie** [comment]
I am informed that @mjohnsullivan gave @cbracken the offending device last week. Reassigned accordingly.

**Comment by darshankawar** [comment]
Hi @mjohnsullivan 
Just checking to see if this is still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
