### ISSUE TITLE
google maps gestures stuck

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#31948]
gestures working very inresponsible on maps.for example after panning it stucks works when after panning in opposite direction.

**Comment by BondarenkoStas** [comment]
@Xgamefactory is it the same in current maps? Can you provide an examle to reproduce it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
