### ISSUE TITLE
Keyboard events should be implemented on iOS

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#31945]
RawKeyboardListener works for Android and other platforms, but not on iOS, because it isn't implemented in the [engine](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/system_channels.dart#L158)

See also #2601, and discussion on flutter/engine#8606

**Comment by lynn** [comment]
> discussion on #8606

Since I was confused here: that's [#8606 on `flutter/engine`](https://github.com/flutter/engine/pull/8606), not this repo.

**Comment by jmagman** [comment]
iPadOS 13.4 (March 24 release) emphasized magic keyboard/trackpad support for 2018 iPad Pro, more users may be hitting this.

**Comment by TVdata** [comment]
> 
> 
> > discussion on #8606
> 
> Since I was confused here: that's [#8606 on `flutter/engine`](https://github.com/flutter/engine/pull/8606), not this repo.
> 
> It seems there is more blocking this than the simple matter of implementing it in the engine.
> 
> I gather that iOS does not actually expose key-level events in its public API. Flutter would only have "insertText" and "deleteBackward" and "UIKeyCommand" events to work with, and mapping those back to the USB keypresses that generated them is not feasible.
> 
> Maybe the situation is different on iOS 13 (but probably not by much). At the very least, from the comments on [this WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=149054), it sounds like a best-effort implementation could handle e.g. arrow keys on iOS 13, but not earlier versions. I certainly don't see the full picture of how close to an implementation of RawKeyboardEvent for iOS it's _possible_ to get, but it seems the answer is "not very close". (I see no way to detect keydown vs. keyup, for example, as one might need for e.g. games that use WASD keys for movement.)


https://developer.apple.com/documentation/uikit/mac_catalyst/handling_key_presses_made_on_a_physical_keyboard
This seems to contradict what you're saying?

**Comment by dgurudot** [comment]
Any updates on it ? iOS allows external bluetooth keyboard to be connected so is it possible to detect keyboard key presses ?

One of my app needs to detect shortcuts like Shift+1, or Ctrl-Z etc and looking for solutions.

**Comment by AndroidNils** [comment]
Is macOS also effected from this issue?

**Comment by gspencergoog** [comment]
No, macOS has keyboard support.

**Comment by incon** [comment]
Possible solution for iOS?
https://developer.apple.com/documentation/uikit/uipress/3526315-key

**Comment by lynn** [comment]
Yes, we have solved this with a platform channel and `UIKey` in our project.
