### ISSUE TITLE
Game controller and DPAD navigation should work

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#31957]
Internal: b/140829915

Along with keyboard navigation (#13264), and handling keycodes for DPAD (#1670), we should also support focus navigation with a game controller and phone DPAD.

**Comment by SpajicM** [comment]
And TV remotes?

**Comment by Hixie** [comment]
@SpajicM This bug is about DPAD on game controllers, please file a separate bug if you would like TV remotes supported. Thanks!

**Comment by mehmetf** [comment]
@jtmcdole we have some questions around this request that is specific to customer: fun. 

1. Do you want this support just for Android? or for iOS as well?
2. Can you give us a canonical example of a controller so we can acquire one to test?
3. We assume you are expecting more than dpad keys to work?  e.g. the proportional joystick controls and all the buttons. Could you confirm?

**Comment by jtmcdole** [comment]
1. Both OS
2. XBox1 Controller  connected over USB HID or Bluetooth HID *should* work assuming you have a later device to map it.  8Bitdo N30Pro 2 has a direct Android and Mac HID Mapping mode.
3. Yes, I'd like to be able to react to the buttons, triggers, and thumb sticks. Navigation via frameowrk and potential for "the user hit the {A,B,X,Y} button on this element" so they can select the element on the screen or we cna handle a "back" navigation.

**Comment by gspencergoog** [comment]
Mapping the various buttons shouldn't be too hard, but right now we don't have any API for delivering/sampling the proportional data from the thumb sticks, so that's a bigger task. Do you just want simulated DPAD events from proportional inputs? (and maybe the platforms already provide this: I haven't looked in detail at the platform APIs yet).

Do you also need the pressure data from buttons (I noticed that some iOS controllers have this)?

**Comment by jtmcdole** [comment]
We do not need pressure data, we only need activation / deactivation. The idea here is not to bubble this up to us, but to support a controller navigating the UI as it does at the Android system level.

**Comment by gspencergoog** [comment]
OK, cool.  So I assume you don't need proportional data from the thumb sticks either, right, just activation of a direction?  Do you need all eight directions, or just combinations of four directions (e.g. combinations of north, south, east, west or do you need n, ne, e, se, s, sw, w, nw)?

**Comment by Hixie** [comment]
I believe the remaining work here is iOS.

**Comment by gspencergoog** [comment]
I believe the desktop platforms also need some work here.

**Comment by jtmcdole** [comment]
Does this mean actual UI navigation will work... or will we still have to use the gamepad inputs and try to invent that?

**Comment by gspencergoog** [comment]
We probably won't want it to work by default, since game controllers are primarily used for games, but we want to make it easy to enable by just supplying the key bindings at the app level.  Right now the key binding part exists, and the function calls exist for moving the focus.  I'm currently building the missing `Action`s that need to exist to make it a reality.  They're pretty trivial to make though, they look something like this:

```dart
/// An [Action] that moves the focus to the next focusable node in the focus
/// order.
///
/// This action is the default action registered for the [key], and by default
/// is bound to the [LogicalKeyboardKey.tab] key in the [WidgetsApp].
class NextFocusAction extends Action {
  /// Creates a [NextFocusAction] with a fixed [key];
  NextFocusAction() : super(key);

  /// The [LocalKey] that uniquely identifies this action to an [Intent].
  static const LocalKey key = ValueKey<Type>(NextFocusAction);

  @override
  void invoke(FocusNode node, Intent tag) {
    super.invoke(node, tag);
    node.nextFocus();
  }
}
```

**Comment by jtmcdole** [comment]
That's worrisome as Android already has gamepad navigation working on the home screen, gmail, the Google Home App, etc. I don't think every application implemented their own navigation graphs.

![anim](https://user-images.githubusercontent.com/1924313/61987467-c2a00680-afcb-11e9-983d-5f4abc1b271f.gif)

**Comment by gspencergoog** [comment]
Oh, I didn't think that was the case (that it was implemented at the system level for apps). Well, maybe we will make it the default on Android then. I'll have to do some more research and see what other platforms provide.

**Comment by jtmcdole** [comment]
I'm only _guessing_ that multiple teams did not re-invent the wheel (plus some did not seem to hint correctly at what's selectable, so it skips over some items on the screen).  We have a navgraph API we could re-use, but that was based on static layouts on other frameworks. Thoughts?

**Comment by jtmcdole** [comment]
Also note: Many controllers only supports HAT_X and HAT_Y axis that are only (-1,0,1). Today these are not converted to "dpad" digital events.

**Comment by timrijckaert** [comment]
Just as a perspective is this something super complicated to include in the Flutter framework?
I would think the implementation could piggy back on the bounding boxes that are used by the accessibility layer right?

**Comment by gspencergoog** [comment]
Well, yes, it is pretty complicated, but it's separate from the accessibility system because they have different needs (for instance, accessibility traverses things like icons and labels, etc.). Also, building the accessibility data structures is pretty expensive because it has to be properly filtered to only include those elements that accessibility is interested in, and we don't want to pay that performance hit unless accessibility is enabled.

The focus infrastructure for this is mostly in place now, but the final step of adding the right default shortcuts for the DPAD keys is still a week or so off while I figure out how to handle focus when applications push and pop navigation routes. I don't want to enable the default shortcuts until they can operate properly in all situations.

**Comment by jkurtw** [comment]
b/140829915

**Comment by gspencergoog** [comment]
Update: the remaining work is just to hook up the default actions.  There has been key support for DPAD key events for a while, but there aren't default navigation bindings yet.

However, I have PRs already in review for most of the remaining work:
https://github.com/flutter/flutter/pull/40166
  - Prerequisite to turning on default navigation shortcuts, so that route scopes are properly focused.
https://github.com/flutter/flutter/pull/40186
  - Draft PR, depends up on https://github.com/flutter/flutter/pull/40706, also in review.
  - Only includes arrow key bindings, but DPAD is mapped to arrow keys, so should also enable DPAD navigation.

Once those are in, the only remaining large piece is that the ENTER, SPACE, or gamepad buttons don't activate controls. For this, we need to rework some of the innards of controls (mainly those that use InkWell) so that reactions occur when an (as yet unbuilt) "activate" Action is invoked from a shortcut. I've started this, and have a draft PR for it:
https://github.com/flutter/flutter/pull/41220

**Comment by gspencergoog** [comment]
Reopening because I had to revert this in https://github.com/flutter/flutter/pull/41945 due to a 5% regression in microbenchmarks_stock_build_iteration. Will re-land as soon as possible.

**Comment by gspencergoog** [comment]
Re-landed.
