### ISSUE TITLE
Support text selection via keyboard

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#31951]
We should support selecting text in text fields using a hardware keyboard.  For instance, using the arrow keys while holding down SHIFT. Also selection to the beginning and end using the begin/end keys and SHIFT (and perhaps selecting words/sentences/paragraphs with other key combinations).

**Comment by gspencergoog** [comment]
There is some basic support for this now, but it's missing some things (like up/down arrow support, for instance). Still more to be done.

**Comment by NicTanghe** [comment]
VIm bindings cough cough
