### ISSUE TITLE
If the website is https, it will can not load http images [webview]

### ISSUE THREAD

**Issue by yhdjy025** [flutter/flutter#31965]
1、If the website is **https,** it will can not load **http** images
2、If jump to other apps and back, it will be white screen for webview.

**Comment by BondarenkoStas** [comment]
@yhdjy025 I think 2nd issue is addressed in https://github.com/flutter/flutter/issues/36437.
I will change the title to treat it as the 1st issue. Btw is it still so?

**Comment by zoeyfan** [comment]
No response from customer since Oct 15 2019, closing this for now. Please feel free to reopen when you have more information.

**Comment by nickwri** [comment]
Hi, I have a similar issue. I am displaying html in webview from strings in my app:
controller.loadUrl('data:text/html;base64,$contentBase64');

Any <img> tags using http are not being downloaded.

Is there a webview setting I can set to allow loading from unsecure http sites?
Thanks.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.900], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
