### ISSUE TITLE
Animate feature for AspectRatio

### ISSUE THREAD

**Issue by zhengbomo** [flutter/flutter#31966]
I want to animate the height or width when the property `aspectRatio` in `AspectRatio` widget is changed or size changed, like `AnimatedContainer`, `AnimatedAlign`

**Comment by TheHemantKaushik** [comment]
You can try `AnimatedBuilder` for this:
https://docs.flutter.io/flutter/widgets/AnimatedBuilder-class.html

**Comment by Zazo032** [comment]
You could also try `AnimatedSize`:
https://docs.flutter.io/flutter/widgets/AnimatedSize-class.html
https://medium.com/flutter-community/flutter-working-with-animatedsize-35253ff8f16a
