### ISSUE TITLE
android.permission.INTERNET permission

### ISSUE THREAD

**Issue by paapu88** [flutter/flutter#31968]
Documentation says:
https://flutter.dev/docs/deployment/android
" Remove the android.permission.INTERNET permission if your application code does not need Internet access."

I did not remove anything from my 
<app dir>/android/app/src/main/AndroidManifest.xml

but there was no line by default
`` <uses-permission android:name="android.permission.INTERNET" /> ``
in <app dir>/android/app/src/main/AndroidManifest.xml

Could you please change the code or documentation, so that they match
( I was wondering why my app in play store could not connect to internet...)

I'm using ubuntu 18.04
Focusing android only

Terveisin, Markus
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/mka/bin/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/mka/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/mka/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at /home/mka/bin/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • moto x4 • ZY224J8WM2 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by ZviKarp** [comment]
Try looking "/android/app/src/profile/AndroidManifest.xml",
or search in your project for `android.permission.INTERNET`.

**Comment by artob** [comment]
Terve, @paapu88. See https://github.com/flutter/flutter/issues/20789

**Comment by BondarenkoStas** [comment]
Thank you @artob ! I think it's safe to close the issue. android.permission.INTERNET is automatically added to debug and profile.

**Comment by Naveed-dev30** [comment]
@BondarenkoStas this permission in debug and profile manifest is used for hot reload and sync files.
