### ISSUE TITLE
API documentation on Overlay and OverlayEntry could be improved

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#3197]
Regarding http://docs.flutter.io/flutter/widgets/OverlayEntry-class.html.

The phrasing "the overlay" is used several times in the documentation. This suggests that there is only one `Overlay` object per application, or even that `Overlay` should be a singleton.

Upon re-reading, I gathered that "the overlay" here referred to whichever `Overlay` object the given `OverlayEntry` was associated with. I think this could be made more clear.

Also, there is confusingly an entry under the `material` package for both `Overlay` and `OverlayEntry`:

http://docs.flutter.io/flutter/material/Overlay-class.html
http://docs.flutter.io/flutter/material/OverlayEntry-class.html

The `widgets` pages sometimes cross-link into these `material` pages.

**Comment by mpcomplete** [comment]
Mentioning an example might help. E.g. "Drop-down menus use overlays. The menu itself is a single OverlayEntry, which is added to the Overlay when open. The Overlay is part of the Scaffold (I think)?" It still escapes me what concept the Overlay actually is.

**Comment by abarth** [comment]
> Also, there is confusingly an entry under the material package for both Overlay and OverlayEntry

Yes, that's a separate issue with the `dartdoc` tool.  Because we re-export these classes from material.dart, they end up with two URLs in the docs.  We should change the dartdoc tool so that each class has a unique canonical URL.

**Comment by abarth** [comment]
> The Overlay is part of the Scaffold (I think)?" It still escapes me what concept the Overlay actually is.

It's created by the Navigator in the MaterialApp.  I'll add that to the docs too.
