### ISSUE TITLE
"flutter run" doesn't quit when the app is closed on ChromeOS

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#31970]
- [set up Flutter on ChromeOS](https://proandroiddev.com/flutter-development-on-a-pixelbook-dde984a3fc1e)
- Run `flutter_gallery` with `flutter run` from the terminal
- Wait for the app to load
- Close the app with the X in the corner

Flutter doesn't seem to notice that the app has closed, and `flutter run` does not terminate.

Same thing happens with the daemon, there's no `app.stop` sent, so if you close the app this way, it doesn't end the debug session in the editor.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by DanTup** [comment]
I no longer have a Chrome OS device to test this so it may need to be tested by someone else.

**Comment by kf6gpe** [comment]
This no longer reproduces.
