### ISSUE TITLE
setState() or markNeedsBuild() called during build - Not clear how to resolve issue

### ISSUE THREAD

**Issue by jhc1982** [flutter/flutter#31981]
I think this problem likely resides behind the keyboard as I am new to Flutter.

That said, I am trying to use a ternary statement in within a StreamBuilder, builder function to redirect based upon some Bloc stream data. 

Here is the Widget in question:

```
import 'package:flutter/material.dart';
import '../blocs/auth_bloc.dart';

class LoginPage extends StatelessWidget {
  final authBloc = AuthBloc();
  final Map<String, bool> initialData = {'loginSuccess': false, 'isLoading': false};

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
        stream: authBloc.redirect,
        initialData: initialData,
        builder: (context, snapshot) {
          return Scaffold(body: _render(context, snapshot));
        });
  }

  _render(BuildContext context, AsyncSnapshot snapshot) {
    return !snapshot.data['loginSuccess'] && snapshot.data['isLoading']
        ? _circularSpinner()
        : snapshot.data['loginSuccess'] && !snapshot.data['isLoading']
            ? _redirect(context)
            : _buildPage();
  }

  _redirect(BuildContext context) {
    return Navigator.of(context).pushReplacementNamed('/dashboard');
  }

  Widget _buildPage() {
    return Container(
      margin: EdgeInsets.all(20.0),
      child: Center(
        child: SingleChildScrollView(
          child: Column(
            children: <Widget>[
              _emailField(authBloc),
              _padding(),
              _passwordField(authBloc),
              _padding(),
              _submitButton(authBloc)
            ],
          ),
        ),
      ),
    );
  }

  Widget _circularSpinner() {
    return Center(
      child: CircularProgressIndicator(),
    );
  }

  Widget _emailField(AuthBloc authBloc) {
    return StreamBuilder(
      stream: authBloc.email,
      builder: (BuildContext context, snapshot) {
        return TextField(
          onChanged: authBloc.emailChanged,
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(
            hintText: 'you@example.com',
            labelText: 'Email Address',
            errorText: snapshot.error,
            border: OutlineInputBorder(),
          ),
        );
      },
    );
  }

  Widget _passwordField(AuthBloc authBloc) {
    return StreamBuilder(
      stream: authBloc.password,
      builder: (BuildContext context, snapshot) {
        return TextField(
          onChanged: authBloc.passwordChanged,
          obscureText: true,
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(
            hintText: '8 characters or more with at least 1 number',
            labelText: 'Password',
            errorText: snapshot.error,
            border: OutlineInputBorder(),
          ),
        );
      },
    );
  }

  Widget _padding() {
    return Padding(
      padding: EdgeInsets.only(top: 20.0),
    );
  }

  Widget _submitButton(AuthBloc authBloc) {
    return StreamBuilder(
        stream: authBloc.submitValid,
        builder: (context, snapshot) {
          return RaisedButton(
            child: Text('Login'),
            color: Colors.blue,
            onPressed: snapshot.hasError ? null : authBloc.submitForm,
          );
        });
  }
}
```

## This results in the following log: 

```
I/flutter ( 4657): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4657): The following assertion was thrown building StreamBuilder<Map<dynamic, dynamic>>(dirty, state:
I/flutter ( 4657): _StreamBuilderBaseState<Map<dynamic, dynamic>, AsyncSnapshot<Map<dynamic, dynamic>>>#a5165):
I/flutter ( 4657): setState() or markNeedsBuild() called during build.
I/flutter ( 4657): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter ( 4657): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter ( 4657): only if one of its ancestors is currently building. This exception is allowed because the framework
```

It is not clear from the log what I need to do to resolve. Or can we not use ternary statements to redirect in this context?

**Comment by jhc1982** [comment]
I seem to have resolved my issue here.

It seems that you just can't Navigator away within a StreamBuilder.

Here is the changed code:

```
 @override
  Widget build(BuildContext context) {
    // Manually listening for redirect conidtions here
    // once a response is received from the server
    authBloc.loginSuccess.listen((data) {
      if (data) {
        Navigator.pushReplacementNamed(context, '/dashboard');
      }
    });

    return StreamBuilder(
        stream: authBloc.isLoading,
        initialData: false,
        builder: (context, snapshot) {
          print(snapshot.data);
          return Scaffold(
            body: snapshot.data ? _circularSpinner() : _buildPage(),
          );
        });
  }
```

I will let someone else decide whether to close or not. The log wasn't overly helpful in resolving the issue. That said I am only just picking up flutter and used to the react way of thinking and logging.

**Comment by Zazo032** [comment]
I faced this issue once, it's probably related to the `onPressed: snapshot.hasError ? null : authBloc.submitForm,` line, try using `onPressed: () => snapshot.hasError ? null : authBloc.submitForm,`

**Comment by jhc1982** [comment]
> I faced this issue once, it's probably related to the `onPressed: snapshot.hasError ? null : authBloc.submitForm,` line.
> Try using `onPressed: () => snapshot.hasError ? null : authBloc.submitForm,` instead.

Thanks. I will have a look at that later and let you know if it worked. I am unsure as there are no errors present.

**Comment by glazec** [comment]
I encounter the same problem. I agree with @jhc1982. It seems that we can't use navigation when the widget is building. I try showDialogue, I can use it neither.

**Comment by glazec** [comment]
We use the stream builder. Thus we can't use the didUpdateWidget to judget whether we need navigation.

**Comment by ashutoshsingh05** [comment]
I think the [addPostFrameCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) is what you are looking for. Please refer to [this](https://www.didierboelens.com/faq/week2/) article on how to use the postFrameCallback for displaying dialog boxes and navigating to screens during or before widget build.

**Comment by BondarenkoStas** [comment]
I think it's safe to close the issue as it got resolved. If you disagree, please comment, I will re-open it right away.

**Comment by leco123** [comment]
Eu esta com o mesmo problema.

`The following assertion was thrown building FutureBuilder<List<dynamic>>(dirty, state: _FutureBuilderState<List<dynamic>>#1f278):
setState() or markNeedsBuild() called during build.`

Para resolver o problema (removi) o final das variáveis.
__________________________________________________________
Exemplo:

**Antes:**
class ListLivroScreen extends StatefulWidget {

  String tipo;
  List<Livro> livros;

**Depois:**
class ListLivroScreen extends StatefulWidget {

  **final** String tipo;
  **final** List<Livro> livros;

**Comment by anysunflower** [comment]
I sovle the problem by add ```async``` and ```await``` when use ``` Navigator.pushNamed``` on tap or press

```
onPressed:()=>navToAttachList(context)

  navToAttachList(context) async{
    await Navigator.pushNamed(
      context, 
      AttachListWidget.routeName,
      arguments: {
        'id':this.id
      }
    );
  }
```

**Comment by AnassErraidi** [comment]
> I sovle the problem by add `async` and `await` when use ` Navigator.pushNamed` on tap or press
> 
> ```
> onPressed:()=>navToAttachList(context)
> 
>   navToAttachList(context) async{
>     await Navigator.pushNamed(
>       context, 
>       AttachListWidget.routeName,
>       arguments: {
>         'id':this.id
>       }
>     );
>   }
> ```

thank you work for me
