### ISSUE TITLE
cloud_firestore snapshots should have stream errors when errors occur in Query

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#31988]
_Originally posted by @ened in https://github.com/flutter/flutter/issues/13904#issuecomment-473118195_

Can confirm Firestore does not crash anymore in case of a missing index. There is clear error description in the logs.

I would, however, expect the AsyncSnapshot to have the error field clearly set.

Sample code:

``` dart
StreamBuilder<QuerySnapshot>(
  stream: state.myQuery,
  builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
    if (snapshot.hasError) {
      return Text('Error: ${snapshot.error}');
    }
    print('snapshot: ${snapshot.connectionState}');
    switch (snapshot.connectionState) {
      case ConnectionState.done:
      case ConnectionState.waiting:
        return Container(
          child: const Center(child: CircularProgressIndicator()),
        );

      default:
        if (snapshot.data.documents.isEmpty) {
          return _buildEmptyPage();
        }

        return _buildListView(snapshot, context);
    }
  },
),
```

`snapshot.error` & `snapshot.hasError` really should be set in that case.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/384. Any further collaboration will be done there.
