### ISSUE TITLE
firebase_dynamic_links 0.2.1 does not support ofl parameter for other platforms

### ISSUE THREAD

**Issue by stephenhuey** [flutter/flutter#31983]
The documentation here mentions the ofl parameter for other platforms, e.g. desktop: 

https://firebase.google.com/docs/dynamic-links/create-manually

Someone might open a dynamic link short URL on desktop that is meant to be opened in a mobile app, in which case it would be ideal to make use of the ofl parameter to instead send them to an appropriate URL for the desktop, e.g. an explanation that they should open it on mobile.  

So far I have not found a way to use the ofl parameter in the documentation or source:

https://pub.dartlang.org/packages/firebase_dynamic_links

**Comment by BondarenkoStas** [comment]
@stephenhuey can you please file the issue to https://github.com/FirebaseExtended/flutterfire/issues and close it here? Firebase packages were moved and another team is working on it.

**Comment by stuartmorgan** [comment]
Closing, since this has moved as noted above.
