### ISSUE TITLE
It's hard to use custom icons

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#3199]
Many, if not most, apps are likely to require custom icons. While it's simple enough to draw an image, some components (e.g. the IconButton) asks for an IconData and not a Widget.

I propose adding an extra, optional field to the IconData that specifies the font to use when drawing the icon. This would make it easy for developers to create a custom icon font and use custom icons.

**Comment by fablue** [comment]
But how can i get the codePoint from https://materialdesignicons.com ?

**Comment by Hixie** [comment]
That's a question you'll have to ask them. Presumably it's documented somewhere, otherwise it's not clear how anyone could use their font (assuming they have a font).

**Comment by Hixie** [comment]
Looks like the answer is on: https://cdn.materialdesignicons.com/1.9.32/

**Comment by fablue** [comment]
Thank you very much :+1:

**Comment by BenSower** [comment]
For anyone coming here from google: I created a tutorial on how to add custom icons to your app: https://medium.com/@emv_tech/add-custom-font-icons-to-a-flutter-project-12bddb841d7

**Comment by KaranChimple** [comment]
@BenSower I tried to work through your process but the problem I'm facing is that I already have a png file in assets folder and I want to include it. Iconmoon doesn't allow to upload png files. It says "Please choose SVG images, SVG fonts or JSONs exported by IcoMoon." Do you guys have any other solutions?

**Comment by BenSower** [comment]
@KaranChimple I am not quite, but pretty sure you won't be able to use a png file like you would use a font-type file. You can however convert your png file to svg and then just convert it into a font: https://stackoverflow.com/questions/1861382/how-to-convert-a-png-image-to-a-svg

**Comment by KaranChimple** [comment]
@BenSower Thanks. I found out a much better way to include png files. I used the following code: 
                    IconButton(
                         icon: **new Image.asset("assets/forward_button.png"),**
                         iconSize: ht > wd ? ht * 0.08 : wd * 0.08,
                         onPressed: () {
                           Navigator.pop(context);
                           Navigator.pop(context);
                           Navigator.pop(context);
                         })

**Comment by BenSower** [comment]
That is of course a way to use a png as an icon, but depending on the image, you might run into problems when scaling the image on larger/smaller devices, since png does not contain any vector information. If that is acceptable then you should be fine :-).

**Comment by raveesh-me** [comment]
Now there is a package that does it for material design icons at least:
https://pub.dartlang.org/packages/material_design_icons_flutter
