### ISSUE TITLE
Apply stub_ui API conformance check in both directions

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#31999]
Currently this only applies dart:ui to stub_ui, but we could move the other direction if we're able to move most platform specific logic into _engine, possibly with a whitelist.

**Comment by zanderso** [comment]
@jonahwilliams Could you provide some more detail about what needs to be done?

**Comment by jonahwilliams** [comment]
Right now we only check that classes and methods that exist in dart:ui also exist in the web implementation, but not that classes and methods that exist in the web implementation exist in dart:ui. This was initially due to the fact that there are several required webOnly* APIs which need to exist, but should probably be cleaned up with an explicit list of these methods to prevent other mistakes.

**Comment by jonahwilliams** [comment]
I'm not currently working on this
