### ISSUE TITLE
the mojo generated libraries don't have library level docs

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#3200]
See
http://build.chromium.org/p/client.flutter/builders/Linux/builds/663/steps/dartdoc%20packages/logs/stdio. If the source material has some docs, we should generate library level docs for the `*.mojom.dart` files.

**Comment by abarth** [comment]
Probably should file in the domokit/mojo.git repo.

**Comment by devoncarew** [comment]
Closing as a dupe of https://github.com/domokit/mojo/issues/624
