### ISSUE TITLE
CupertinoDialogAction.isDefaultAction is a misleading name

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#32005]
`CupertinoDialogAction.isDefaultAction` is a misleading name for iOS developers.

On iOS [`UIAlertAction.Style`](https://developer.apple.com/documentation/uikit/uialertaction/style) is an `enum` with 3 cases:

```swift
case `default`
case cancel
case destructive
```

`CupertinoDialogAction`'s constructor's signature:
```dart
const CupertinoDialogAction({
  VoidCallback onPressed,
  bool isDefaultAction: false,
  bool isDestructiveAction: false,
  TextStyle textStyle,
  @required Widget child
})
```
where `isDefaultAction` is easily mistakable for the `default` case but they do different things and are not mutually exclusive.

Should probably explicitly state in the documentation that `isDefaultAction` is not the same as `UIAlertAction.Style.default`

## Version
Channel master, v1.5.9-pre.117

**Comment by riccardoratta** [comment]
I propose a constructor like this Inspired to [LKAlertController](https://github.com/lightningkite/LKAlertController) library for iOS.

```dart
const CupertinoDialogAction({
  VoidCallback onPressed,
  ActionStyle style = ActionStyle.Default,
  TextStyle textStyle,
  bool preferredAction = false, // this will bold the text in the child
  @required Widget child,
})
```

with the enum:
```dart
enum ActionStyle {
  /// Apply the default style to the action’s button.
  Default,
  /// Apply a style that indicates the action cancels the operation and leaves things unchanged.
  Cancel,
  /// Apply a style that indicates the action might change or delete data.
  Destructive,
}
```
