### ISSUE TITLE
Share the alwaysUse24Hour and textScaleFactor heuristics between iOS and macOS

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#32006]
I _believe_ there should be some way to share, or otherwise keep this logic in sync, though it requires investigation. The code currently lives in the iOS FlutterViewController.

Done:
* [X] alwaysUse24Hour in https://github.com/flutter/engine/pull/53795
* [ ] textScaleFactor

**Comment by stuartmorgan** [comment]
Looks like it should be as simple as pulling it out into a stand-alone utility function in a shared file.
