### ISSUE TITLE
Is there a way in SerializableFinder to find a widget using another relative widget?

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#32012]
Hi, I was wondering if there is a way for SerializableFinder (we are writing integration tests) to get a widget(ex. text) using another widget that is related to it? 

An example scenario is a list view with several rows and each row has its own label and value texts. We want to get the displayed value text using the label text. The label text is constant but the value text varies. 
Kind of like what is being done in relative xpaths where you can get the sibling of a view, is there a way in flutter to get the value text by starting from the label text?

**Comment by goderbauer** [comment]
There are descendant and ancestor matchers:

https://master-api.flutter.dev/flutter/flutter_test/CommonFinders/descendant.html
https://master-api.flutter.dev/flutter/flutter_test/CommonFinders/ancestor.html
