### ISSUE TITLE
promote path_provider plugin to 1.0

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#32042]
Steps required

* [ ] Find a CODEOWNER
* [ ] Add an integration test
* [ ] Update version

**Comment by sroddy** [comment]
@collinjackson do you think it may be worth to review my suggestions here before releasing a 1.0 version?
I'm worried that this might be the last chance to make some important (and probably needed) changes to the plugin...
https://github.com/flutter/flutter/issues/13474

**Comment by sroddy** [comment]
whoops, too late ;)

**Comment by collinjackson** [comment]
I'm sorry about that -- I missed the issue you had linked. I'll take a look and see if there's anything we can do about it.

**Comment by domesticmouse** [comment]
Worst case we can break API with a v2.
