### ISSUE TITLE
google maps mylocation button tap does nothing.

### ISSUE THREAD

**Issue by Xgamefactory** [flutter/flutter#32048]
```
GoogleMap gmapWidget = GoogleMap(
      initialCameraPosition: CameraPosition(target: _initPosition),
      mapType: MapType.normal,
      myLocationEnabled: true,
      myLocationButtonEnabled: true,
      compassEnabled: true,
      tiltGesturesEnabled: true,
      zoomGesturesEnabled: true,
      rotateGesturesEnabled: true,
      scrollGesturesEnabled: true,
      onMapCreated: _onMapCreated,
    );
```
mylocationButton is visible but when tapping does nothing. 
expected behaviour is centering map to user current location as in stock android maps app.

**Comment by Xgamefactory** [comment]
looks like support team abandoned project )

**Comment by BondarenkoStas** [comment]
@Xgamefactory is it the same while using current flutter stable and latest maps?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
