### ISSUE TITLE
Setting text doesn't work with UiAutomator

### ISSUE THREAD

**Issue by alanrussian** [flutter/flutter#32063]
To repro this, use the Android UiAutomator framework to try to set the text contained within a Flutter `TextField` widget. If you'd like to see a simple repro, I'd prefer to provide one using internal infrastructure, because I'm not too familiar with how to set up these UiAutomator tests externally. With that said, here is some code:

In order to find the text field using the UiAutomator library, you need to look for the `EditText` class. Then, you can call setText to try to set the text in the view.

```java
device.findObject(By.clazz("android.widget.EditText")).setText("Hello");
```

However, this does not appear to modify the text whatsoever.

You can see the implementation of `#setText` here: https://android.googlesource.com/platform/frameworks/uiautomator/+/android-support-test/src/main/java/android/support/test/uiautomator/UiObject2.java#573

**Comment by dannfeng** [comment]
Excuse me, is there a solution？

**Comment by markusaksli-nc** [comment]
Hi @alanrussian 
Can you confirm that this issue is still relevant on the latest master and provide a minimal repro project if this is the case?
Thank you.

**Comment by alanrussian** [comment]
I'm sorry, I unfortunately don't work on a Flutter app any longer and don't have the time.

**Comment by markusaksli-nc** [comment]
Closing this for now. If someone can provide a detailed confirmation that this is still an issue on the latest master I'll reopen.
