### ISSUE TITLE
localToGlobal and globalToLocal are not inverses of each other

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#32064]
In https://github.com/flutter/flutter/pull/22985/ `RenderBox.globalToLocal` was fixed to do a correct orthographic projection of a point. 

The inverse, `RenderBox.localToGlobal`, was not updated. It is surprising that chaining the two doesn't yield the original point again.

Should this be changed? Or is there a reason for the two to be different? If so, we should document that.

/cc @sbaranov @Hixie

**Comment by sbaranov** [comment]
They should be inverse of each other as long as the point lies on the widget. In fact, localToGlobal is lossy in that it ignores the Z coordinate, to force the point to be on the widget. I don't know if you can make them behave the same since projection is lossy.
