### ISSUE TITLE
How can I make Flutter use the Device's Default Font?

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#32079]
chinese text random show error ;

so, i have a question: [How can I make Flutter use the Device's Default Font?](https://stackoverflow.com/questions/51913485/how-can-i-make-flutter-use-the-devices-default-font)

i cant't get answer from stackoverflow.

**Comment by KagurazakaHanabi** [comment]
You can try ThemeData.fontFamily

**Comment by v7lin** [comment]
i have same question

**Comment by alexdacoda** [comment]
is there a way to check for the system font and maybe then use it in my flutter project at runtime

**Comment by BondarenkoStas** [comment]
There is an approved answer on SO https://stackoverflow.com/a/52231172, I think it's safe to close the issue.
