### ISSUE TITLE
How do I control animated gifs?

### ISSUE THREAD

**Issue by zanecidan** [flutter/flutter#32083]
Something I want to achieve:
1. When user tap on the screen, show a animated gif as overlay on the tap position.
2. The animated gif should always animated from 1st frame to end frame on each tap.

What can I do to achieve this?

Thank you.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
