### ISSUE TITLE
Issue from website page 起步: 体验

### ISSUE THREAD

**Issue by bdmfloat** [flutter/flutter#32080]
From URL: https://www.flutterchina.club/get-started/test-drive.md

用VS Code开发flutter，需要装Android Studio 或Android SDK吗？

**Comment by hv3s1** [comment]
需要的，别纠结，这问题不至于发issue

**Comment by abc873693** [comment]
可以只裝Android SDK 但要另外設定ANDROID_HOME

**Comment by stuartmorgan** [comment]
That is a community website not maintained by the Flutter team. Try https://github.com/flutterchina/website/issues
