### ISSUE TITLE
Cannot Build Application

### ISSUE THREAD

**Issue by BND10706** [flutter/flutter#32096]
This is what happens when I build.

Error:Android Pre Dex: [flutter.jar] Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in io.flutter.view.AccessibilityBridge.shouldSetCollectionInfo:(Lio/flutter/view/AccessibilityBridge$SemanticsNode;)Z: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
Error:Android Pre Dex: [flutter.jar] 1 error; aborting

I set the minsdkversion in the build.gradle to 26

**Comment by Anik-Roy** [comment]
I'm getting same issue when I'm trying to create a signed apk. Did you get the solution?

**Comment by BND10706** [comment]
No, but the build seems to be ok.. it works on my Android devices. Not sure what the error is.

**Comment by solokingjec** [comment]
I am also having this problem. I was very hopeful with flutter but so many issues.

**Comment by Garciconx** [comment]
I have the same issue!

**Comment by janmoppel** [comment]
Hello @BND10706 !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

It also seems, that similar issue has been already reported here: #28701.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
