### ISSUE TITLE
The problem of using connectivity plugin

### ISSUE THREAD

**Issue by ymyuen** [flutter/flutter#32091]
I am a new leaner on flutter. I am going to the connectivity plugin to check the device network status on my application. And I get the result on iOS  simulator but I get the following compilation error when I try to run the application on my Android mobile device (Android 8.0.0)

_* Error running Gradle:
ProcessException: Process "/Volumes/Fujitsu HDD/FlutterWorkSpace/connection/android/gradlew" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)
         *********************************************************
WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type TaskHistoryRepository using TaskExecutionServices.createTaskHistoryRepository().
> Timeout waiting to lock task history cache (/Volumes/Fujitsu HDD/FlutterWorkSpace/connection/android/.gradle/4.10.2/taskHistory). It is currently in use by another Gradle instance.
  Owner PID: unknown
  Our PID: 75247
  Owner Operation: unknown
  Our operation: 
  Lock file: /Volumes/Fujitsu HDD/FlutterWorkSpace/connection/android/.gradle/4.10.2/taskHistory/taskHistory.lock

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s
  Command: /Volumes/Fujitsu HDD/FlutterWorkSpace/connection/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder._

The following is my dart code .
`import 'package:flutter/material.dart';
import 'package:connectivity/connectivity.dart';
import 'package:async/async.dart';

void main(){
  runApp(MaterialApp(
    title: "connectivity",
    home: Connection(),
  ));
}
class Connection extends StatefulWidget {
  @override
  _ConnectionState createState() => _ConnectionState();
}

class _ConnectionState extends State<Connection> {
  @override
  var _connection ;
  String connectionState = "";
  _ConnectionState(){
    _connection = Connectivity().onConnectivityChanged.listen((ConnectivityResult result){
      setState(() {
        if (result == ConnectivityResult.none)
          connectionState = "No network connection";
        else if (result == ConnectivityResult.mobile)
          connectionState = "Mobile Network";
        else if (result == ConnectivityResult.wifi)
          connectionState = "Wifi network";
      });
    });
    initNetworkState();

  }
  void initNetworkState()async{
    var connection = await(Connectivity().checkConnectivity());
    if (connection == ConnectivityResult.none)
      connectionState = "No network connection";
    else if (connection == ConnectivityResult.mobile)
      connectionState = "Mobile Network";
    else if (connection == ConnectivityResult.wifi)
      connectionState = "Wifi network";
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Connection"),
      ),
      body:Container(
        alignment: Alignment.center,
        child: Text(connectionState),
      ),
    );
  }
  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    _connection.cancel();
  }
}
`
How can I slove this problem ?

**Comment by vargavince91** [comment]
Have you tried following the tutorial that's linked about AndroidX?

https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

**Comment by BondarenkoStas** [comment]
@ymyuen did you manage to fix it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
