### ISSUE TITLE
[maps] Set io.flutter.embedded_views_preview to true (not YES)

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#32097]
## Use case

The [iOS documentation](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter#ios)  for `google_maps_flutter` says:

> Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.

I saw elsewhere that you can also set it to `<true/>`.  Considering that the flag is a _boolean_, and that "YES" is truly a localized value (English), using `<true/>` is more appropriate.

## Proposal

Revise the documentation to indicate setting `io.flutter.embedded_views_preview` to `true`, ideally with an example:
```xml
<key>io.flutter.embedded_views_preview</key>
<true/>
```

**Comment by huzhiren** [comment]
YES is the label of dropdown from Xcode, it is the same as <true/>

**Comment by lukepighetti** [comment]
please provide code examples instead of UI examples, the proposal here is reasonable

**Comment by w4-sglim** [comment]
I agree that. The person who want to use flutter hardly open XCode.

**Comment by cerivera** [comment]
Also would be helpful to know which `Info.plist` file to edit.  I had to chase down the right one.
<img width="591" alt="Screen Shot 2019-11-13 at 8 42 49 AM" src="https://user-images.githubusercontent.com/504445/68773660-98fa0200-05f1-11ea-99da-6199527f5746.png">

**Comment by mhmoudsabry** [comment]
> Also would be helpful to know which `Info.plist` file to edit. I had to chase down the right one: `ios/Runner/Info.plist`
> <img alt="Screen Shot 2019-11-13 at 8 42 49 AM" width="591" src="https://user-images.githubusercontent.com/504445/68773660-98fa0200-05f1-11ea-99da-6199527f5746.png">

secend

**Comment by ride4sun** [comment]
This was listed on May 4, 2019 and all which has to be done is a documentation update - what takes so long? I just run into the same problem

**Comment by manafire** [comment]
A description or link to what the "embedded views preview" is might also also be helpful.  ¯\_(ツ)_/¯

**Comment by stuartmorgan** [comment]
Closing as obsolete; this step is no longer necessary, and has been removed from the README.
