### ISSUE TITLE
mock location

### ISSUE THREAD

**Issue by barzansaeedpour** [flutter/flutter#32105]
Hi,
 i'm writing a Location based application with Flutter and i want to check if my location is fake for not. i mean to check if mobile is using mock Location in developer options.
thanks in advance.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
