### ISSUE TITLE
problem in flutter doctor

### ISSUE THREAD

**Issue by abdulrahman90** [flutter/flutter#32106]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```hello im new to programming , i face many problems  
i want to use vs studio 
i face this issue when running flutter dsoctor

[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 6.1.7601], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
exit code 0
![Untitled](https://user-images.githubusercontent.com/50265193/57190165-d2053b80-6f17-11e9-9eb1-8a787c70d848.gif)

```

```
```

**Comment by CukierPuder420** [comment]
To use Flutter properly, you should get a supported IDE (with official Dart & Flutter SDK plugins), so either Android Studio or Visual Studio Code. Install one of these and install the two mentioned plugins for them. Then, as flutter doctor says, run `flutter doctor --android-licenses`, because you probably didn't agree to them yet and you have to do that before you start developing with Flutter SDK.

**Comment by abdulrahman90** [comment]
thank you it was solved

**Comment by abhikumar63** [comment]
C:\Users\KIIT>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = C:\Program
    X Android Studio not found at C:\Program
[√] VS Code (version 1.53.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.




I am getting these many problems can you help me?
