### ISSUE TITLE
How to use RepaintBoundary screenshot for ListView in long list widget ?

### ISSUE THREAD

**Issue by maxcong** [flutter/flutter#32108]
I want screenshot the Widget with "RepaintBoundary", the ListView is specific scrollable, render metrics over to show. I cant to screenshot on the long list.

How can i use RepaintBoundary snapshot for ListView in long list widget ?

Thanks for everyone !

**Comment by KagurazakaHanabi** [comment]
[https://stackoverflow.com/questions/53646649/how-to-take-screenshot-of-widget-beyond-the-screen-in-flutter](https://stackoverflow.com/questions/53646649/how-to-take-screenshot-of-widget-beyond-the-screen-in-flutter)

**Comment by maxcong** [comment]
> https://stackoverflow.com/questions/53646649/how-to-take-screenshot-of-widget-beyond-the-screen-in-flutter

谢谢，这个可以用！

**Comment by KagurazakaHanabi** [comment]
那就把这个 issue 关掉吧
