### ISSUE TITLE
PlatformView crash when it is displayed on cutout / notch screens

### ISSUE THREAD

**Issue by yuridiniz** [flutter/flutter#32100]
I'm developing an application with the Google Maps plugin, when I tested on Notch display phones, Google Maps did not render, as if it were a Widget with 0.0 opacity.

I was able to emulate this problem in AVD, and it really is caused when a `PlatformView` Widget is outside the "safe area", generating the following message in the log:

`Creating a virtual display of size: [1080, 1794] is not supported. It is larger than the device screen size: [1080, 1668]`

To get around this problem, I used the `SafeArea` Widget, but lost the design that the application should have, displaying the map across the screen size

## Steps to Reproduce

1. Create an AVD with API 28
2. Enable the Developer Mode in the AVD to emulate the Cutout / Notch screen
3. Enable Cutout simulator - [Docs](https://developer.android.com/about/versions/pie/android-9.0#cutout)
4. Add Google Maps Widget to fill the entire screen

```dart 

class _MyHomePageState extends State<MyHomePage> {

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.indigo,
        child: Stack(
          children: <Widget>[
            Center(child: Text("You should be seeing the map, not me.")),
            Positioned(
              top: 0, // set to 200 to run without error
              left: 0,
              right: 0,
              bottom: 0,
              child: GoogleMap(initialCameraPosition: _kGooglePlex),
            ),
          ],
        ),
      ),
    );
  }
}

```

## Logs

```
E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.IllegalArgumentException: Creating a virtual display of size: [1080, 1794] is not supported. It is larger than the device screen size: [1080, 1668].
        at io.flutter.plugin.platform.PlatformViewsController.validateVirtualDisplayDimensions(PlatformViewsController.java:427)
        at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:204)
        at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:142)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:212)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
[✓] Flutter (Channel master, v1.5.9-pre.148, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.5.9-pre.148 at /home/yuri/development/flutter
    • Framework revision d53115ab2e (6 hours ago), 2019-05-04 22:13:25 +0900
    • Engine revision 1d062db4db
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/yuri/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/yuri/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/yuri/android-studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.26.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

• No issues found!
```

_I can not test on the iPhone_

**Comment by yuridiniz** [comment]
It seems that even putting the SafeArea some devices still have the same problem, not all, but of the devices that are happening are the manufacturer Xiaomi, please, I need a support to solve this problem

**Comment by yuridiniz** [comment]
I am looking for what is error in the calculation of SafeArea, could this happen? I found the PR, it seems to have some time for you [https://github.com/flutter/engine/pull/8848](https://github.com/flutter/engine/pull/8848)

**Comment by huonderv** [comment]
It also happens on devices without cutout / notch screens if you hide the status bar with 

`SystemChrome.setEnabledSystemUIOverlays([]);` 

and use the Andorid theme

`android:style/Theme.Black.NoTitleBar`

as launch theme of the `MainActivity` that extends the `FlutterActivity`.

**Comment by huonderv** [comment]
I'm not 100% sure, but I guess that the calculation of the device's real dimension merged in [flutter/engine#8704](https://github.com/flutter/engine/pull/8704) is not correct if a theme with NoTitleBar is used and/or the SystemUI overlays are hidden using SystemChrome.

@amirh you commented on @iskakaushik about why we have to be that strict in `validateVirtualDisplayDimenstions`. I think it is too strict now in above two cases

**Comment by dnfield** [comment]
I don't think the linked PR is going to help you for this specific bug - that PR will only make sure the safe area information is always pumped down even when the keyboard is visible.

**Comment by yuridiniz** [comment]
Does that solve the problem? [https://github.com/flutter/engine/commit/d4794122ab779010f1d69bcbebb61ab2f7a2dae2](https://github.com/flutter/engine/commit/d4794122ab779010f1d69bcbebb61ab2f7a2dae2)

**Comment by iskakaushik** [comment]
addressed by: https://github.com/flutter/engine/pull/9110

**Comment by pratik037** [comment]
How was this issue tackled? Can you help me out please?

**Comment by FaizanAhmad127** [comment]
I wrapped the GoogleMap widget with SafeArea, which worked for me. I even am using appbar.

**Comment by sauravgpt** [comment]
Launching lib\main.dart on SM A505F in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:57752/e8hLJKkOnq0=/ws
Syncing files to device SM A505F...
I/Dialog  (23284): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/zzbz    (23284): Making Creator dynamically
W/Gralloc4(23284): allocator 3.x is not supported
W/Gralloc3(23284): allocator 3.x is not supported
I/DynamiteModule(23284): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule(23284): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule(23284): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/avgpt.cab_ride(23284): ClassLoaderContext classpath element mismatch. expected=/data/app/~~K-5PXcYewBTLYkZooh363Q==/com.sauravgpt.saurav_rider_app-aQ8vlBE8leUheMIHCZGZRA==/base.apk, found=/data/app/~~3FAWUOqBRQqi2soCnWQBMQ==/com.sauravgpt.cab_rider-md72YrqArwumZ70KfDWUbw==/base.apk (DLC[];PCL[/data/app/~~K-5PXcYewBTLYkZooh363Q==/com.sauravgpt.saurav_rider_app-aQ8vlBE8leUheMIHCZGZRA==/base.apk*707039401]{PCL[/system/framework/org.apache.http.legacy.jar*876722329]} | DLC[];PCL[/data/app/~~3FAWUOqBRQqi2soCnWQBMQ==/com.sauravgpt.cab_rider-md72YrqArwumZ70KfDWUbw==/base.apk*4236614036]{PCL[/system/framework/org.apache.http.legacy.jar*876722329]})
W/avgpt.cab_ride(23284): Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/0000009f/MapsDynamite.apk
W/avgpt.cab_ride(23284): NOTE: This wastes RAM and hurts startup performance.
W/avgpt.cab_ride(23284): Found duplicated class when checking oat files: 'Landroid/support/v4/app/RemoteActionCompatParcelizer;' in /data/app/~~3FAWUOqBRQqi2soCnWQBMQ==/com.sauravgpt.cab_rider-md72YrqArwumZ70KfDWUbw==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/0000009f/MapsDynamite.apk
I/Google Maps Android API(23284): Google Play services client version: 12451000
I/Google Maps Android API(23284): Google Play services package version: 210613046
E/MethodChannel#flutter/platform_views(23284): Failed to handle method call
E/MethodChannel#flutter/platform_views(23284): java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/MethodChannel#flutter/platform_views(23284): 	at com.google.maps.api.android.lib6.drd.p.b(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):6)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.maps.api.android.lib6.auth.f.i(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):1)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.maps.internal.CreatorImpl.c(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):24)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):2)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.maps.internal.g.aX(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):18)
E/MethodChannel#flutter/platform_views(23284): 	at dr.onTransact(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):4)
E/MethodChannel#flutter/platform_views(23284): 	at android.os.Binder.transact(Binder.java:1079)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.internal.maps.zza.zza(Unknown Source:10)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.maps.internal.zzf.zza(Unknown Source:19)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source:13)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(com.google.android.gms:play-services-base@@17.1.0:18)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@17.1.0:22)
E/MethodChannel#flutter/platform_views(23284): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source:26)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugins.googlemaps.GoogleMapController.onCreate(GoogleMapController.java:544)
E/MethodChannel#flutter/platform_views(23284): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
E/MethodChannel#flutter/platform_views(23284): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
E/MethodChannel#flutter/platform_views(23284): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:113)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:38)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:53)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/MethodChannel#flutter/platform_views(23284): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:708)
E/MethodChannel#flutter/platform_views(23284): 	at android.app.Dialog.show(Dialog.java:422)
E/MethodChannel#flutter/platform_views(23284): 	at android.app.Presentation.show(Presentation.java:285)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(23284): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/platform_views(23284): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(23284): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/platform_views(23284): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#flutter/platform_views(23284): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
E/MethodChannel#flutter/platform_views(23284): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(23284): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#flutter/platform_views(23284): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (23284): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml, null, java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/flutter (23284): 	at com.google.maps.api.android.lib6.drd.p.b(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):6)
E/flutter (23284): 	at com.google.maps.api.android.lib6.auth.f.i(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):1)
E/flutter (23284): 	at com.google.android.gms.maps.internal.CreatorImpl.c(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):24)
E/flutter (23284): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):2)
E/flutter (23284): 	at com.google.android.gms.maps.internal.g.aX(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):18)
E/flutter (23284): 	at dr.onTransact(:com.google.android.gms.dynamite_mapsdynamite@210613097@21.06.13 (150400-0):4)
E/flutter (23284): 	at android.os.Binder.transact(Binder.java:1079)
E/flutter (23284): 	at com.google.android.gms.internal.maps.zza.zza(Unknown Source:10)
E/flutter (23284): 	at com.google.android.gms.maps.internal.zzf.zza(Unknown Source:19)
E/flutter (23284): 	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source:13)
E/flutter (23284): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(com.google.android.gms:play-services-base@@17.1.0:18)
E/flutter (23284): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@17.1.0:22)
E/flutter (23284): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source:26)
E/flutter (23284): 	at io.flutter.plugins.googlemaps.GoogleMapController.onCreate(GoogleMapController.java:544)
E/flutter (23284): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
E/flutter (23284): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
E/flutter (23284): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:188)
E/flutter (23284): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:113)
E/flutter (23284): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:38)
E/flutter (23284): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:53)
E/flutter (23284): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/flutter (23284): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:708)
E/flutter (23284): 	at android.app.Dialog.show(Dialog.java:422)
E/flutter (23284): 	at android.app.Presentation.show(Presentation.java:285)
E/flutter (23284): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (23284): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (23284): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter (23284): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (23284): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (23284): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (23284): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (23284): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (23284): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23284): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (23284): 	at android.os.Looper.loop(Looper.java:206)
E/flutter (23284): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
E/flutter (23284): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23284): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (23284): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (23284): )
E/flutter (23284): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (23284): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (23284): <asynchronous suspension>
E/flutter (23284): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1036:18)
E/flutter (23284): <asynchronous suspension>
E/flutter (23284): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:742:5)
E/flutter (23284): <asynchronous suspension>
E/flutter (23284): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:195:7)
E/flutter (23284): <asynchronous suspension>
E/flutter (23284):

**Comment by sauravgpt** [comment]
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:58150/CFW35m8x6iw=/ws
Syncing files to device SM A505F...
I/ViewRootImpl@c8c11e4[MainActivity](26623): ViewPostIme pointer 0
I/ViewRootImpl@c8c11e4[MainActivity](26623): ViewPostIme pointer 1
I/Dialog  (26623): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/zzbz    (26623): Making Creator dynamically
W/Gralloc4(26623): allocator 3.x is not supported
W/Gralloc3(26623): allocator 3.x is not supported
I/DynamiteModule(26623): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule(26623): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule(26623): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/avgpt.cab_ride(26623): ClassLoaderContext classpath element mismatch. expected=/data/app/~~K-5PXcYewBTLYkZooh363Q==/com.sauravgpt.saurav_rider_app-aQ8vlBE8leUheMIHCZGZRA==/base.apk, found=/data/app/~~EKR25OU3bzEw9y3sJqQ4IQ==/com.sauravgpt.cab_rider-y1QkKKw9FgGRbyKKzTGcLg==/base.apk (DLC[];PCL[/data/app/~~K-5PXcYewBTLYkZooh363Q==/com.sauravgpt.saurav_rider_app-aQ8vlBE8leUheMIHCZGZRA==/base.apk*707039401]{PCL[/system/framework/org.apache.http.legacy.jar*876722329]} | DLC[];PCL[/data/app/~~EKR25OU3bzEw9y3sJqQ4IQ==/com.sauravgpt.cab_rider-y1QkKKw9FgGRbyKKzTGcLg==/base.apk*4236614036]{PCL[/system/framework/org.apache.http.legacy.jar*876722329]})
W/avgpt.cab_ride(26623): Found duplicate classes, falling back to extracting from APK : /data/user_de/0/com.google.android.gms/app_chimera/m/0000009f/MapsDynamite.apk
W/avgpt.cab_ride(26623): NOTE: This wastes RAM and hurts startup performance.
W/avgpt.cab_ride(26623): Found duplicated class when checking oat files: 'Landroid/support/v4/app/RemoteActionCompatParcelizer;' in /data/app/~~EKR25OU3bzEw9y3sJqQ4IQ==/com.sauravgpt.cab_rider-y1QkKKw9FgGRbyKKzTGcLg==/base.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/0000009f/MapsDynamite.apk
I/Google Maps Android API(26623): Google Play services client version: 12451000
I/Google Maps Android API(26623): Google Play services package version: 210613046
I/TetheringManager(26623): registerTetheringEventCallback:com.sauravgpt.cab_rider
D/ConnectivityManager(26623): ConnectivityManager() mContext=android.app.Application@17418c0 getOpPackageName()=com.sauravgpt.cab_rider getBasePackageName()=com.sauravgpt.cab_rider getPackageName()=com.sauravgpt.cab_rider
I/DecorView(26623): [INFO] isPopOver=false, config=false
I/DecorView(26623): updateCaptionType >> DecorView@e13c38a[], isFloating=false, isApplication=false, hasWindowDecorCaption=false, hasWindowControllerCallback=false
D/DecorView(26623): setCaptionType = 0, this = DecorView@e13c38a[]
D/InputTransport(26623): Input channel constructed: '497f7b ', fd=145
I/ViewRootImpl@36433c4[MainActivity](26623): setView = com.android.internal.policy.DecorView@e13c38a TM=true
E/GoogleMapController(26623): Cannot enable MyLocation layer as location permissions are not granted
I/SurfaceView(26623): onWindowVisibilityChanged(0) true com.google.maps.api.android.lib6.gmm6.api.at{d22dbeb VFE...C.. ......ID 0,0-0,0} of ViewRootImpl@36433c4[MainActivity]
I/SurfaceControl(26623): assignNativeObject: nativeObject = 0 Surface(name=null)/@0xbe93906 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9018 android.view.ViewRootImpl.performTraversals:3373 android.view.ViewRootImpl.doTraversal:2631 android.view.ViewRootImpl$TraversalRunnable.run:9978 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/ViewRootImpl@36433c4[MainActivity](26623): Relayout returned: old=(0,0,1080,2218) new=(0,0,1080,2218) req=(1080,2218)0 dur=15 res=0x7 s={true 542010114048} ch=true fn=-1
I/SurfaceView(26623): windowStopped(false) true com.google.maps.api.android.lib6.gmm6.api.at{d22dbeb VFE...C.. ......ID 0,0-0,0} of ViewRootImpl@36433c4[MainActivity]
I/ViewRootImpl@36433c4[MainActivity](26623): [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:10964 android.view.ViewRootImpl.performTraversals:3858 android.view.ViewRootImpl.doTraversal:2631 
I/SurfaceView(26623): surfaceCreated 1 #8 com.google.maps.api.android.lib6.gmm6.api.at{d22dbeb VFE...C.. ......ID 0,0-1080,2218}
I/SurfaceView(26623): surfaceChanged (1080,2218) 1 #8 com.google.maps.api.android.lib6.gmm6.api.at{d22dbeb VFE...C.. ......ID 0,0-1080,2218}
I/ViewRootImpl@36433c4[MainActivity](26623): [DP] dp(2) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView$1.onPreDraw:225 android.view.ViewTreeObserver.dispatchOnPreDraw:1124 
I/ViewRootImpl@36433c4[MainActivity](26623): [DP] pdf(1) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564 android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
I/ViewRootImpl@36433c4[MainActivity](26623): [DP] pd() Asnyc report
I/SurfaceView(26623): setParentSpaceRectangle: useBLAST = false position = Rect(0, 0 - 1080, 2218) frameNumber = 1 t = android.view.SurfaceControl$Transaction@7db4b51
I/SurfaceView(26623): applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@7db4b51 surfaceControl = Surface(name=SurfaceView - Sys2030:com.sauravgpt.cab_rider/com.sauravgpt.cab_rider.MainActivity@d22dbeb@0)/@0xaf7efb6 frame = 1
I/SurfaceView(26623): applySurfaceTransforms: postScaleX = 1.0 postScaleY = 1.0
I/ViewRootImpl@36433c4[MainActivity](26623): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4681 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
I/ViewRootImpl@36433c4[MainActivity](26623): [DP] rdf()
I/System.out(26623): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(26623): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(26623): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(26623): (HTTPLog)-Static: isSBSettingEnabled false
W/DynamiteModule(26623): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(26623): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule(26623): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
