### ISSUE TITLE
Would like a way to make rounded corners for sliders

### ISSUE THREAD

**Issue by jdeltoft** [flutter/flutter#32102]
I'm using the basic slider, and I found how to update just the parts of the slider theme data that I want to change like trackHeight, but unfortunately I'm not sure how to update the field for "trackShape".  Here is what I do in the main app to update track height for example:

    final SliderThemeData tweakedSliderTheme = Theme.of(context).sliderTheme.copyWith(
        trackHeight: 22.0,
         //trackShape: RectangularSliderTrackShape(),  // How do I update this??
    );

I did try using [ClipRRect()][1] around the slider widget and that had no effect.

Here is a simple page for one slider:

    import 'package:flutter/material.dart';
    
    class RoomControl extends StatefulWidget {
      @override
      _RoomControlState createState() => _RoomControlState();
    }
    
    class _RoomControlState extends State<RoomControl> {
      double _value = 0.0;
      void _setvalue(double value) => setState(() => _value = value);
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text('Name here'),
          ),
          //hit Ctrl+space in intellij to know what are the options you can use in flutter widgets
          body: Container(
            padding: EdgeInsets.all(32.0),
            child: Center(
              child: Column(
                children: <Widget>[
                  Text('Value: ${(_value * 100).round()}'),
                  ClipRRect(
                    borderRadius: BorderRadius.circular(5.0),
                  child:Slider(
                      value: _value,
                      onChanged: _setvalue,
                      divisions: 10,
                  )
        )
                ],
              ),
            ),
          ),
        );
      }
    }

Here is what that slider looks like:

[![enter image description here][2]][2]

  [1]: https://www.youtube.com/watch?v=eI43jkQkrvs
  [2]: https://i.stack.imgur.com/rgwmZ.png

**Comment by jdeltoft** [comment]
I got the answer to this here:

https://stackoverflow.com/questions/55987559/how-can-i-round-the-corners-of-a-slider-in-flutter/55988624#55988624

**Comment by clocksmith** [comment]
The default track shape is now a rounded rect:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/slider_theme.dart#L972

Does that work for you?

**Comment by fluttercorner** [comment]
[How To Create Rounded Corners Image in Flutter](https://fluttercorner.com/how-to-create-rounded-corners-image-in-flutter/)
