### ISSUE TITLE
How to run C++ Native Modules like React-Native do in Flutter

### ISSUE THREAD

**Issue by hugetiny** [flutter/flutter#32113]
## Use case

React-Native have its own way to  reuse some existing Objective-C, Swift or C++ code in app:
https://facebook.github.io/react-native/docs/native-modules-ios.html

## Proposal

How to run C++ Native Modules like React-Native do  in Flutter ?

**Comment by truongsinh** [comment]
For now, we have to use platform channel, that is

C/C++ lib <---binding---> Swift/ObjC <---platform channel---> Dart
C/C++ lib <-----JNI-----> Java/Kotlin <---platform channel---> Dart

For direct access, follow https://github.com/flutter/flutter/issues/7053

**Comment by BondarenkoStas** [comment]
Thank you @truongsinh ! Closing as a duplicate, please follow #7053.
