### ISSUE TITLE
The keyboard is displayed above the text field when use PinYin input method on IOS

### ISSUE THREAD

**Issue by solemilo** [flutter/flutter#32118]
![屏幕快照 2019-05-05 下午9 17 54](https://user-images.githubusercontent.com/9472979/57194771-550cad00-6f7d-11e9-9997-c04e9b9eb1c3.png)

## Steps to Reproduce
```
class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        title: Text('Test App'),
      ),
      body: Form(
        child: ListView(
          children: <Widget>[
           CupertinoTextField(
               keyboardType:TextInputType.text
            )
          ],
        ),
      )
      ,

    );
  }
}
```
![屏幕快照 2019-05-05 下午9 22 04](https://user-images.githubusercontent.com/9472979/57194692-3ce85e00-6f7c-11e9-95fe-86e051c30765.png)

**Comment by BondarenkoStas** [comment]
@solemilo is it the same while using current flutter stable v1.9.1+hotfix.4?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
