### ISSUE TITLE
Dart Analyzer Error after upgrading Flutter to version 1.2.1

### ISSUE THREAD

**Issue by familfamilzade** [flutter/flutter#32119]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by familfamilzade** [comment]
After upgrading to 1.2.1 Android Studio throws Dart Analyzer error and it does not show any suggestion while coding or catches code errors.

**Comment by BondarenkoStas** [comment]
@familfamilzade how is it for you with current flutter stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
