### ISSUE TITLE
RuntimeError - Unsupported workspace file reference type `build`,when i pod install,error occurred

### ISSUE THREAD

**Issue by tangjinzhao** [flutter/flutter#32128]
pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `contact_picker` from `.symlinks/plugins/contact_picker/ios`
Fetching podspec for `flutter_alipay` from `.symlinks/plugins/flutter_alipay/ios`
Fetching podspec for `flutter_baidu_map` from `.symlinks/plugins/flutter_baidu_map/ios`
Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
Fetching podspec for `fluwx` from `.symlinks/plugins/fluwx/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `imsdk` from `.symlinks/plugins/imsdk/ios`
Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`
Downloading dependencies
Using AliPay (2.1.2)
Using BMKLocationKit (1.0.1)
Using Flutter (1.0.0)
Using audioplayers (0.0.1)
Using camera (0.0.1)
Using contact_picker (0.0.1)
Using flutter_alipay (0.0.1)
Using flutter_baidu_map (0.0.1)
Using flutter_sound (0.0.1)
Using fluwx (0.0.1)
Using image_picker (0.0.1)
Using imsdk (0.0.1)
Using package_info (0.0.1)
Using path_provider (0.0.1)
Using permission_handler (2.1.0)
Using shared_preferences (0.0.1)
Using url_launcher (0.0.1)
Using video_player (0.0.1)
Using webview_flutter (0.0.1)
Generating Pods project
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G6030)
       Xcode : 10.1 (10B61)
         Git : git version 2.6.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bb16ff168c626b30ffb941e8eb124bb29aa82d05
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
RuntimeError - Unsupported workspace file reference type `build`
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace/file_reference.rb:74:in `absolute_path'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:201:in `block in load_schemes'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:200:in `each'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:200:in `load_schemes'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:85:in `from_s'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:93:in `create_workspace'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:64:in `integrate!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:645:in `block in integrate_user_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:642:in `integrate_user_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:141:in `install!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Unsupported+workspace+file+reference+type+%60build%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...

[!] Automatically assigning platform `ios` with version `10` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:1384:in `request'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:84:in `get_api_results'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:28:in `search'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
	from /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'
tangjinzhaodeMacBook-Air:ios tangjinzhao$ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `contact_picker` from `.symlinks/plugins/contact_picker/ios`
Fetching podspec for `flutter_alipay` from `.symlinks/plugins/flutter_alipay/ios`
Fetching podspec for `flutter_baidu_map` from `.symlinks/plugins/flutter_baidu_map/ios`
Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
Fetching podspec for `fluwx` from `.symlinks/plugins/fluwx/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `imsdk` from `.symlinks/plugins/imsdk/ios`
Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`
Downloading dependencies
Using AliPay (2.1.2)
Using BMKLocationKit (1.0.1)
Using Flutter (1.0.0)
Using audioplayers (0.0.1)
Using camera (0.0.1)
Using contact_picker (0.0.1)
Using flutter_alipay (0.0.1)
Using flutter_baidu_map (0.0.1)
Using flutter_sound (0.0.1)
Using fluwx (0.0.1)
Using image_picker (0.0.1)
Using imsdk (0.0.1)
Using package_info (0.0.1)
Using path_provider (0.0.1)
Using permission_handler (2.1.0)
Using shared_preferences (0.0.1)
Using url_launcher (0.0.1)
Using video_player (0.0.1)
Using webview_flutter (0.0.1)
Generating Pods project
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G6030)
       Xcode : 10.1 (10B61)
         Git : git version 2.6.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bb16ff168c626b30ffb941e8eb124bb29aa82d05
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
RuntimeError - Unsupported workspace file reference type `build`
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace/file_reference.rb:74:in `absolute_path'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:201:in `block in load_schemes'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:200:in `each'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:200:in `load_schemes'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:85:in `from_s'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:93:in `create_workspace'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:64:in `integrate!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:645:in `block in integrate_user_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:642:in `integrate_user_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:141:in `install!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Unsupported+workspace+file+reference+type+%60build%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - what's wrong with it
   https://github.com/CocoaPods/CocoaPods/issues/8769 [open] [0 comments]
   2 hours ago

 - Resources installed using cocoapods not loaded for xctest bundle
   https://github.com/CocoaPods/CocoaPods/issues/4752 [closed] [47 comments]
   31 Jul 2018

 - Allow :local in podfile
   https://github.com/CocoaPods/CocoaPods/issues/178 [closed] [38 comments]
   22 Nov 2015

[!] Automatically assigning platform `ios` with version `10` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by tangjinzhao** [comment]
I see "The 'Pods-Runner' target has transitive dependencies that include static binaries:" ,so i add "s.static_framework = true" into  project/ios/symlinks/plugins/flutter_baidu_map/ios/flutter_baidu_map.podspec    and then  error occurred~help  me  ,thanks

**Comment by tangjinzhao** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G6030, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!

**Comment by tangjinzhao** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G6030, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at
      /Users/tangjinzhao/Documents/flutter_developer/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tangjinzhao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tangjinzhao/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tangjinzhao/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone XR • A489EBB0-0AA5-4470-BF10-398B41309275 • ios • iOS 12.1
      (simulator)

• No issues found!

**Comment by janmoppel** [comment]
Hello @tangjinzhao !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
