### ISSUE TITLE
[video_player]Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by jol5** [flutter/flutter#32125]
1.i got a error with video_player plugin
 Source error.
E/ExoPlayerImplInternal( 6804): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://XXXXXXXX.m3u8
E/ExoPlayerImplInternal( 6804): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal( 6804): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 6804): 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
E/ExoPlayerImplInternal( 6804): 	at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
E/ExoPlayerImplInternal( 6804): 	at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
E/ExoPlayerImplInternal( 6804): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 6804): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal( 6804): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal( 6804): 	at java.lang.Thread.run(Thread.java:761)
E/ExoPlayerImplInternal( 6804): Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

2. the url can be opened in the browser 

3. but i don`t know how to ignore the SSL cert

**Comment by 26shruti** [comment]
Any updates? Getting the same error

**Comment by Rickyballs** [comment]
public static void handleSSLHandshake() {
    try {
        TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
            public X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[0];
            }
 
            @Override
            public void checkClientTrusted(X509Certificate[] certs, String authType) {
            }
 
            @Override
            public void checkServerTrusted(X509Certificate[] certs, String authType) {
            }
        }};
 
        SSLContext sc = SSLContext.getInstance("TLS");
        // trustAllCerts信任所有的证书
     sc.init(null, trustAllCerts, new SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
        HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                return true;
            }
        });
    } catch (Exception ignored) {
    }
 }

Calling this method in the onCreat () method in the Application class ignores the certificate validation of HTTPS.

**Comment by mrhmamun** [comment]
Any Update???

**Comment by PraveenVerma17** [comment]
I am also facing similar  issue and unable to get proper solution.

**Comment by wzyfrank** [comment]
There is a workaround (assuming you just want to learn video_player plugin instead of playing that specific video)

https://flutter.cn/docs/cookbook/plugins/play-video

In this tutorial, there is another video 'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4'. Replacing the video URL might be able to solve the problem.

**Comment by stuartmorgan** [comment]
Can you clarify what the issue is exactly here? Is the URL in question using a self-signed certificate or something along those lines?

Without having an example URL that causes this problem, we can't reproduce it, which makes it hard to understand what the specific behavior you want is.

**Comment by Rickyballs** [comment]
I guess it should be the certificate verification problem when capturing packets through Fiddler agent.
Many developers will ignore the certificate verification of HTTPS when testing, so as to capture network requests.
If you can't ignore the entry to certificate validation, you can only test it directly to the server.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
