### ISSUE TITLE
Monotonic timer on Windows is not truely monotonic?

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#32121]
Seems like a possible bug in the Engine. Printing out the current time using `FlutterEngineGetCurrentTime` shows that it resets after a while.

![powershell_2019-05-05_15-35-18](https://user-images.githubusercontent.com/2268005/57199349-e5ca9500-6f4b-11e9-9541-2e22e833782b.png)

I have no clue why the timer is resetting at an arbitrary point, but this is causing Flutter to lock up and hang because vsync callbacks don't get scheduled properly.

**Comment by ds84182** [comment]
[fml::TimePoint::Now](https://github.com/flutter/engine/blob/70a1106b509ea3f34febca59967ed7a76c05ce33/fml/time/time_point.cc#L55) on Windows uses the performance counter. However, this can overflow due to `1000000000` being a rather large constant, which should be applied instead to the frequency (which will be well below uint64's limit). The overflow causes the counter to wrap around every 30 minutes, or even less since QueryPerformanceCounter is a global timer.

This solution might work, don't have a Flutter development environment set up:
```c
if (freq < 1000000000) {
  return TimePoint(count * (1000000000 / freq));
} else {
  return TimePoint(count / (freq / 1000000000));
}
```

**Comment by stuartmorgan** [comment]
It's very unlikely that we want integer division in an intermediate part of the calculation. We'll need to figure out if doing `double` calculations and then truncating is sufficient granularity; if not we'll presumably need to do large-integer math (I'm not sure if we already have a library for that).

**Comment by ds84182** [comment]
@stuartmorgan Abseil has 128-bit integer types, perhaps that can be used (it _is_ a Google supported library).

I don't think doubles have enough precision for this, especially near high numbers (QueryPerformanceCounter is allowed to use the entire uint64). In some less-ideal situations (say an extremely precise counter, or more unlikely: 500+ years of uptime at least) this could cause issues.

If you have a Dart 2.3 you can use this piece of code to test QPC:
```dart
import 'dart:ffi';

void main() {
  final ptr = allocate<Uint64>();
  final kernel32 = DynamicLibrary.open("kernel32.dll");
  final int Function(Pointer<Uint64>) QueryPerformanceCounter = kernel32
      .lookup<NativeFunction<Uint32 Function(Pointer<Uint64>)>>(
          "QueryPerformanceCounter")
      .asFunction();
  final int Function(Pointer<Uint64>) QueryPerformanceFrequency = kernel32
      .lookup<NativeFunction<Uint32 Function(Pointer<Uint64>)>>(
          "QueryPerformanceFrequency")
      .asFunction();

  QueryPerformanceCounter(ptr);
  final int counter = ptr.load<int>();
  QueryPerformanceFrequency(ptr);
  final int freq = ptr.load<int>();

  // Original
  print((counter * 1000000000) ~/ freq);

  // Big Integer
  print((BigInt.from(counter) * BigInt.from(1000000000)) ~/ BigInt.from(freq));

  // Probable solution
  print(counter * (1000000000 ~/ freq));

  // Doubles
  print((counter.toDouble() * 1000000000.0) / freq.toDouble());
}
```

On my machine I get this output:
```
186761057069
2106804934274700
2106804934274700
2106804934274699.8
```

**Comment by stuartmorgan** [comment]
Abseil isn't currently an engine dependency though, and I doubt we'd add it just for this. If we don't have a library already pulled in that does it, we could do this one case by hand.

**Comment by stuartmorgan** [comment]
In more detail, the reason this:
```
  // Probable solution
  print(counter * (1000000000 ~/ freq));
```
isn't viable is that the error compounds with `counter`, which is a very large number, rather than being bounded. In this case, the effect would be to cause time to flow slightly faster in the app (with the exact scale being a function of both the timer resolution and the fractional amount that's dropped).

**Comment by stuartmorgan** [comment]
Should be fixed by https://github.com/flutter/engine/pull/8910. Thanks for the report and detailed investigation!
