### ISSUE TITLE
Listener Example is not working

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#32127]
In https://docs.flutter.io/flutter/widgets/Listener-class.html there is a "Sample in a App" example. Created new flutter project and replace the code with "Sample in a App" code.

Example is not working.

**Comment by JordyBaylac** [comment]
Hi @NTMS2017 , did you run `flutter create --sample=widgets.Listener mysample` when creating the flutter project?

**Comment by NTMS2017** [comment]
No. just create a simple flutter and replace with the example code in https://docs.flutter.io/flutter/widgets/Listener-class.html.  And there isnt any big import either. Just simple standart package like import 'package:flutter/material.dart' and import 'package:flutter/gestures.dart'.


I am using latest intellij community editon.

**Comment by dragonetail** [comment]
@JordyBaylac 
Hi, I meet the same problem, when running "flutter create --sample=widgets.Listener.1 mysample" following by https://api.flutter.dev/flutter/widgets/Listener-class.html.

Tested on ios simulator and IPad.

**Comment by BondarenkoStas** [comment]
@NTMS2017 tried it with current flutter stable v1.9.1+hotfix.4, it works just fine. Seems that it's fixed.
