### ISSUE TITLE
Get the size and position of a TextSpan within a RichText

### ISSUE THREAD

**Issue by alexandergottlieb** [flutter/flutter#32137]
## Use case
It would be helpful to get the size and position of a tapped `TextSpan` the same way we can with other widgets (using something like `RenderBox`).

At the moment, `RichText` only takes `TextSpan` children. So calling `context.findRenderObject()` from within a TextSpan can only ever give you the box of the enclosing `RichText`:

```
RichText(
  text: TextSpan(
    children: [
      TextSpan(
        text: 'Tap me',
        recognizer: TapGestureRecognizer()..onTap = () {
          //Gets box around RichText, not around this TextSpan
          RenderBox renderBox = context.findRenderObject();
        },
      ),
    ],
  ),
);
```

## Proposal
Provide an API to get the size and position of a `TextSpan`, ideally in an idiomatic Flutter way like allowing a `Builder` to sit between the `TextSpan` and `RichText`.

**Comment by goderbauer** [comment]
Can you list some use case for this so we can figure out what kind of API this would need?
