### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm.cc(265)] VM snapshot must be valid

### ISSUE THREAD

**Issue by OrdinaryPath** [flutter/flutter#32136]
A new environment，A new project is created，but，I ran it and it gave me an error.
![image](https://user-images.githubusercontent.com/37242300/57219370-71b2ee80-702a-11e9-87e1-6d639c3a17b0.png)
![image](https://user-images.githubusercontent.com/37242300/57219393-88594580-702a-11e9-94c4-2984296121b9.png)
![image](https://user-images.githubusercontent.com/37242300/57219414-96a76180-702a-11e9-85e8-32dc9819b009.png)
I tried many ways，But it failed

**Comment by janmoppel** [comment]
Hello @OrdinaryPath !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by OrdinaryPath** [comment]
> Hello @OrdinaryPath !
> 
> Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by janmoppel** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
