### ISSUE TITLE
[Xcode Build failed] codesign error when I had 2 ambiguous iPhone Developer certificates

### ISSUE THREAD

**Issue by SinCheung** [flutter/flutter#32134]
script code in **xcode_backend.sh**
https://github.com/flutter/flutter/blob/538a1c66186a0e6e2c472ff09274bd59bb104569/packages/flutter_tools/bin/xcode_backend.sh#L379-L384

when identity contains 2 ambiguous iPhone Developer certificates, it would build **failed**!

Error logs below:
`/Users/xxxx/gitlab/xxxflutterproject.ios/Flutter/engine/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h -> /Users/xxxx/Library/Developer/Xcode/DerivedData/MerchantManager-fdsofxomadbluxehdyzunaopujag/Build/Products/Debug-iphoneos/MerchantManager.app/Frameworks/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h
/Users/xxxx/gitlab/xxxflutterproject.ios/Flutter/engine/Flutter.framework/Headers/FlutterBinaryMessenger.h -> /Users/xxxx/Library/Developer/Xcode/DerivedData/MerchantManager-fdsofxomadbluxehdyzunaopujag/Build/Products/Debug-iphoneos/MerchantManager.app/Frameworks/Flutter.framework/Headers/FlutterBinaryMessenger.h
/Users/xxxx/gitlab/xxxflutterproject.ios/Flutter/engine/Flutter.framework/Headers/FlutterCallbackCache.h -> /Users/xxxx/Library/Developer/Xcode/DerivedData/MerchantManager-fdsofxomadbluxehdyzunaopujag/Build/Products/Debug-iphoneos/MerchantManager.app/Frameworks/Flutter.framework/Headers/FlutterCallbackCache.h
/Users/xxxx/gitlab/xxxflutterproject.ios/Flutter/engine/Flutter.framework/Modules -> /Users/xxxx/Library/Developer/Xcode/DerivedData/MerchantManager-fdsofxomadbluxehdyzunaopujag/Build/Products/Debug-iphoneos/MerchantManager.app/Frameworks/Flutter.framework/Modules
/Users/xxxx/gitlab/xxxflutterproject.ios/Flutter/engine/Flutter.framework/Modules/module.modulemap -> /Users/xxxx/Library/Developer/Xcode/DerivedData/MerchantManager-fdsofxomadbluxehdyzunaopujag/Build/Products/Debug-iphoneos/MerchantManager.app/Frameworks/Flutter.framework/Modules/module.modulemap
/Users/xxxx/gitlab/xxxflutterproject.ios/Flutter/engine/Flutter.framework/Info.plist -> /Users/xxxx/Library/Developer/Xcode/DerivedData/MerchantManager-fdsofxomadbluxehdyzunaopujag/Build/Products/Debug-iphoneos/MerchantManager.app/Frameworks/Flutter.framework/Info.plist
iPhone Developer: USER_NAME (Y7MBXXVDVX): ambiguous (matches "iPhone Developer: USER_NAME (Y7MBXXVDVX)" and "iPhone Developer: USER_NAME (Y7MBXXVDVX)" in /Users/xxxx/Library/Keychains/login.keychain-db)
iPhone Developer: USER_NAME (Y7MBXXVDVX): ambiguous (matches "iPhone Developer: USER_NAME (Y7MBXXVDVX)" and "iPhone Developer: USER_NAME (Y7MBXXVDVX)" in /Users/xxxx/Library/Keychains/login.keychain-db)
Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by janmoppel** [comment]
Hello @SinCheung !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
