### ISSUE TITLE
There was something wrong in my app

### ISSUE THREAD

**Issue by aidenpierce2** [flutter/flutter#32138]
hey guys,there was some thing wrong in my app, and i known it's my code's error.
but the log can't show me my error,just from framework ,i had update my flutter and dart to the newest.
following are the logs:
I/flutter (23432): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23432): The following assertion was thrown building Builder(dirty):
I/flutter (23432): 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 343 pos 15: 'locale !=
I/flutter (23432): null': is not true.
I/flutter (23432): 
I/flutter (23432): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23432): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23432): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23432):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (23432): 
I/flutter (23432): When the exception was thrown, this was the stack:
I/flutter (23432): #2      new Localizations (package:flutter/src/widgets/localizations.dart:343:15)
I/flutter (23432): #3      MainApplication.build.<anonymous closure>.<anonymous closure> (package:flutter01/main.dart:47:26)
I/flutter (23432): #4      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:87:27)
I/flutter (23432): #5      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:651:43)
I/flutter (23432): #6      Builder.build (package:flutter/src/widgets/basic.dart:6233:41)
I/flutter (23432): #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (23432): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (23432): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (23432): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (23432): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (23432): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #71     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (23432): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #83     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (23432): #84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (23432): #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (23432): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (23432): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (23432): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (23432): #94     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
I/flutter (23432): #95     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (23432): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #97     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
I/flutter (23432): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #101    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23432): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #105    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23432): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (23432): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #111    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23432): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (23432): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (23432): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23432): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23432): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23432): #119    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (23432): #120    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (23432): #121    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (23432): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (23432): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (23432): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (23432): #128    _invoke (dart:ui/hooks.dart:219:10)
I/flutter (23432): #129    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (23432): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (23432): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/hwaps   (23432): JNI_OnLoad

my pub file:
name: flutter01
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.1
  json_annotation: ^2.0.0
  flutter_redux: ^0.5.3
  device_info: ^0.4.0+1
  connectivity: ^0.4.2
  url_launcher: ^5.0.1
  flutter_markdown: ^0.2.0
  share: ^0.6.0+1
  flutter_spinkit: ^3.1.0
  flutter_webview_plugin: ^0.2.1+2
  sqflite: ^1.1.1
  pub_semver: ^1.4.2
  flutter_statusbar: ^0.0.1
  flutter_svg: ^0.11.0+1
  photo_view: ^0.2.1
  flutter_slidable: ^0.4.9
  dio: ^2.1.3
  flutter_localizations:
    sdk: flutter
  event_bus:  ^1.0.3
  flutter_cache_manager: ^0.3.1
  path_provider: ^0.5.0+1
  permission_handler: 3.0.0
  scoped_model: ^1.0.1
  package_info: ^0.4.0+1
  rxdart: ^0.21.0
  android_intent: ^0.3.0
  test: ^1.5.1
  flutter_test:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.2.8
  json_serializable: ^2.0.0
#  flutter_test:
#    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/logo.png
    - static/images/default_img.png
    - static/images/welcome.png
  fonts:
    - family: buttomIconStyle
      fonts:
        - asset: static/font/iconfont.ttf

**Comment by deadsoul44** [comment]
Your error is stated in the message:

I/flutter (23432): The following assertion was thrown building Builder(dirty):
I/flutter (23432): 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 343 pos 15: 'locale !=
I/flutter (23432): null': is not true.
I/flutter (23432):
I/flutter (23432): Either the assertion indicates an error in the framework itself, or we should provide substantially

Maybe you are using localization package and you didn't set the locale which should not be null?

**Comment by aidenpierce2** [comment]
> Your error is stated in the message:
> 
> I/flutter (23432): The following assertion was thrown building Builder(dirty):
> I/flutter (23432): 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 343 pos 15: 'locale !=
> I/flutter (23432): null': is not true.
> I/flutter (23432):
> I/flutter (23432): Either the assertion indicates an error in the framework itself, or we should provide substantially
> 
> Maybe you are using localization package and you didn't set the locale which should not be null?

thanks,you are right,I forgot to set @require property of Localizations
