### ISSUE TITLE
Using Flutter with non-standard keyboard

### ISSUE THREAD

**Issue by lukejagodzinski** [flutter/flutter#32139]
Hey, thanks for the great work done with Flutter. It's really great tool but there are some flaws. One of the main flaws that I've notice just after a few minutes of playing with Flutter is poor support for non-standard keyboard. It's not possible to execute such commands like CTRL+A, CTRL+X, CTRL+C, CTRL+V or select text by simulating using arrows and the SHIFT key being pressed. There is also a problem with the context menu (after selecting text) not being a system menu.

Here is the video showing this problem: https://youtu.be/ma1hOEX0YTw

## Proposal

It would be great if input fields would support all the commands that are available on desktop as some keyboard take advantage of this. It would also help when you connect phone to the computer and would like to use your computer keyboard to enter text. I also think that by default it should show system context menu after selecting text.

**Comment by goderbauer** [comment]
We have added a lot of support for shortcuts sine this was field. I am going to close this one. If something specific is still missing: please file a new issue.
