### ISSUE TITLE
[google_maps_flutter] Add support for map padding

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#32149]
We should have api that allows the equivalent of https://developers.google.com/maps/documentation/android-sdk/map#map_padding

**Comment by sergicastellsague** [comment]
@iskakaushik any update on this issue?

We cannot comply with 3.2.3.b https://cloud.google.com/maps-platform/terms/

**Comment by iskakaushik** [comment]
fixed in https://github.com/flutter/plugins/pull/1674. Will be in `0.5.17` after https://github.com/flutter/plugins/pull/1749 merges.

**Comment by iskakaushik** [comment]
`0.5.17` has been published
