### ISSUE TITLE
Flutter showcase app shows features which are currently not working in current Flutter release?

### ISSUE THREAD

**Issue by msw333** [flutter/flutter#32141]
Flutter showcases the app ‚Topline‘ from Abbey Road Studios as one of the main apps made with flutter, see https://flutter.dev/showcase

...as well as a respective promotion video, release in December 2018:
https://www.youtube.com/watch?v=_ACWeGGBP4E

What suprised us very much, is that there are not the issues, Flutter is currently facing, such as: Topline supports a loupe for text selection on iOS (https://github.com/flutter/flutter/issues/9507) or the keyboard pop-in animation does not outrun the animation (https://github.com/flutter/flutter/issues/19279)

Well, this app was shown as a showcase to give an example what you can do with Flutter, making developers like us rely on this technology. So I am really curious to get some input by the Flutter team, how to achieve these features with the current Flutter master.

**Comment by alexelsn** [comment]
We are also waiting for these features, till it makes the IOS experience... love to hear Flutters opinion on that

**Comment by audkar** [comment]
Flutter team over promises a lot of things in their conference talks and presentations. I bet that tomorrow (during Google IO), they will talk how Flutter is stable & has support for such features like in-app purchases, maps, crash reporting, etc. When in reality all these plugins are in early developments stage, doesn't have stable versions and lacks essential features.

And who wants to see real situation how Flutter team is overwhelmed with trying to get to basic functionality, can look to this ticket: https://github.com/flutter/flutter/issues/18494 If this will not be solved then soon it will not be possible to upload **default** Flutter apkbundle to Google PlayStore.

**Comment by lukepighetti** [comment]
Just played around with Topline and it looks like it's just an animated container that is slightly faster than the iOS keyboard, nothing more.

**Comment by lukepighetti** [comment]
I wasn't able to find the loupe example, sorry.

**Comment by janmoppel** [comment]
Hello @msw333 !

Are there still any missing features in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
