### ISSUE TITLE
when setting [initialScrollOffset], ListView unnecessarily rendering

### ISSUE THREAD

**Issue by EpicKim** [flutter/flutter#32140]
## Steps to Reproduce

```dart
@override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    ScrollController scrollController = ScrollController(
        initialScrollOffset: height*100,
        keepScrollOffset: false);
    ListView listView = ListView.builder(
      controller: scrollController,
      reverse: false,
      itemCount: 99999,
      scrollDirection: Axis.vertical,
      itemBuilder: (BuildContext context, int index) {
        debugPrint("building: $index");
        return SizedBox.fromSize(
          child: Text("$index"),
          size: Size(MediaQuery.of(context).size.width, height),
        );
      },
    );
    return Scaffold(
      floatingActionButton: RaisedButton(
        onPressed: () {
          // listView.
          scrollController.jumpTo(
            100 * height
          );
        },
      ),
      body: listView,
    );
  }
```

Here's my code. I created a ListView with initialScrollOffset. It suppost to be only render the 100th item. But it rendered all the 100 items.

**Comment by wilin52** [comment]
I also meet the problem with my app.It cost a long time to render the target item.

**Comment by wilin52** [comment]
@EpicKim you can use [staggeredGridView]( https://pub.dev/packages/flutter_staggered_grid_view) to box item. just set crossAxisCount = 1; Don't forget to set value to staggeredTileBuilder, need to give it the value : return StaggeredTile.extent(1, height). You should calculate the each item's height.

**Comment by wilin52** [comment]
If flutter knows each item' height, it has no need to render each item to get the height to know the target offset locates, so it will be faster , I guess.

**Comment by wilin52** [comment]
@EpicKim Actually, there is no need to use StaggeredGridView.
you should Use  itemExtent.

 /// If non-null, forces the children to have the given extent in the scroll
  /// direction.
  ///
  /// Specifying an [itemExtent] is more efficient than letting the children
  /// determine their own extent because the scrolling machinery can make use of
  /// the foreknowledge of the children's extent to save work, for example when
  /// the scroll position changes drastically.
  final double itemExtent;

**Comment by janmoppel** [comment]
Hello @EpicKim !

Have you tried the solution proposed by @wilin52? Or did you manage to solve the issue on your own?
