### ISSUE TITLE
Cannot add latest stream_channel package to flutter project

### ISSUE THREAD

**Issue by markmclaren2** [flutter/flutter#32146]
I've added stream_channel to the dependencies section of my pubspec.yaml file like this:
  stream_channel: ^2.0.0

But now when running "flutter packages get" I get this error:

Because every version of flutter_test from sdk depends on stream_channel 1.6.8 and myprojectname depends on stream_channel ^2.0.0, flutter_test from sdk is forbidden.
So, because myprojectname depends on flutter_test any from sdk, version solving failed.

My flutter version:

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

**Comment by jason-simmons** [comment]
Flutter v1.2.1 was using stream_channel 1.6.8

More recent versions of Flutter have been upgraded to stream_channel 2.0.0

**Comment by markmclaren2** [comment]
Yep fixed in Flutter 1.5.4-hotfix.2 - thanks
