### ISSUE TITLE
Introduce multiplexing UIApplicationDelegate proxy for plugins

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#32159]
Plugins are clobbering each other in iOS apps when they require `UIApplicationDelegate` callbacks (See `#3` here https://github.com/flutter/flutter/issues/24278#issue-380097536).

Flutter should introduce a multiplexing `UIApplicationDelegate` proxy that forwards all `UIApplicationDelegate` callbacks to all plugins that care.

**Comment by matthew-carroll** [comment]
Closing as duplicate due to GitHub bug.

**Comment by tudor07** [comment]
@matthew-carroll you closed both this and the duplicate issue? I think you meant to only close one?

**Comment by matthew-carroll** [comment]
Looks like it, but I would also guess that this issue is either resolved elsewhere or will not be worked. CC @xster
