### ISSUE TITLE
Introduce UIApplicationDelegate for iOS Flutter apps

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#32160]
Plugins are clobbering each other in iOS apps when they require `UIApplicationDelegate` callbacks (See `#3` here https://github.com/flutter/flutter/issues/24278#issue-380097536).

Flutter should introduce a multiplexing `UIApplicationDelegate` proxy that forwards all `UIApplicationDelegate` callbacks to all plugins that care.

**Comment by matthew-carroll** [comment]
CC @xster @dnfield

**Comment by matthew-carroll** [comment]
I closed the other 2 duplicates that resulted from a GitHub bug. This is now the only ticket for this purpose.

**Comment by MatMaul** [comment]
Second duplicate of #32157 ?

**Comment by gaaclarke** [comment]
This hasn't been the case for a long time it appears, at least 9 months ago: https://github.com/flutter/engine/blob/47f17a9ec33d387899dfcd991cff604523836be1/shell/platform/darwin/ios/framework/Source/FlutterPluginAppLifeCycleDelegate.mm#L31
