### ISSUE TITLE
Make _deactivateRecursively static

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#32165]
See https://github.com/flutter/flutter_web/blob/b817e257ef921d4db13d3cb20dea5092e6b3efc2/packages/flutter_web/lib/src/widgets/framework.dart#L1737. This is a recursive _instance_ method. When it recurses it produces a tear off, which is more expensive than recursing into a static function.

**Comment by ferhatb** [comment]
Fixed via https://github.com/flutter/flutter/commit/a32d1ccdced04387406931b98e219731fc183db4#diff-16a8dc6e114c65d7a516fc759bac2316
