### ISSUE TITLE
Failed assertion: line 155 pos 18: '!state.down': is not true.

### ISSUE THREAD

**Issue by markuspedro** [flutter/flutter#32169]
When I click on element of the PageView and then click on the map i receive this error:
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
	[C4.1 668FC5D1-B66C-427B-BA80-229C1BD635A8 192.168.1.4:54212<->216.58.205.142:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 72.289s, DNS @0.002s took 0.003s, TCP @0.009s took 0.034s, TLS took 0.106s
	bytes in/out: 205693/5682, packets in/out: 161/28, rtt: 0.047s, retransmitted packets: 0, out-of-order packets: 0

#My code
**There my code:**
new Material(
        child: Stack(
          children: <Widget>[
            GoogleMap(
              onMapCreated: _onMapCreated,
              initialCameraPosition: CameraPosition(
                target: _center,
                zoom: 11.0,
              ),
            ),
            Positioned(
              bottom: 10,
              child: new SizedBox(
              height: 150,
              width: MediaQuery.of(context).size.width,
              child: PageView.builder(
      itemCount: itemCount,
      scrollDirection: Axis.horizontal,
      itemBuilder: (context, index) {
        return new GestureDetector(
          child:Text("test"),
        );
      },
      onPageChanged: (index) {
        print(index.toString());
      },
    );
            ),)

          ],
        )

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
