### ISSUE TITLE
[firebase_crashlytics] RangeError: Value not in range: -1

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#32178]
I'm seeing a `RangeError` exception at https://github.com/flutter/plugins/blob/f254cd2573db895d927abeff1e2b7a1dfb177b1b/packages/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L189

```
  List<Map<String, String>> _getStackTraceElements(List<String> lines) {
    final List<Map<String, String>> elements = <Map<String, String>>[];
    for (String line in lines) {
      final List<String> lineParts = line.split(RegExp('\\s+'));
      try {
        final String fileName = lineParts[0];
        final String lineNumber =
            lineParts[1].substring(0, lineParts[1].indexOf(":")).trim();
        final String className =
            lineParts[2].substring(0, lineParts[2].indexOf(".")).trim();
        final String methodName =
            lineParts[2].substring(lineParts[2].indexOf(".") + 1).trim();
```

`line` is set to `"package:flutter/src/foundation/assertions.dart 519:9     new FlutterError.fromParts.<fn>"` and the `className` line throws an exception because `lineParts[2]` is `new` which doesn't contain a `.`.

I would add more information but this bug seems pretty self-explanatory :)

The bug was introduced by the new code in https://github.com/flutter/plugins/pull/1080

@kroikie @collinjackson Could you guys take a look?

**Comment by collinjackson** [comment]
Looks like a legitimate issue. I don't have the bandwidth to fix at this moment but I would be happy to review a PR fixing it. We may want to consider unit testing this part of the plugin.

**Comment by kroikie** [comment]
@matthewlloyd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/383. Any further collaboration will be done there.
